### ISSUE TITLE
Add hub

### ISSUE THREAD

**Issue by peaceiris** [actions/virtual-environments#1]
**Tool information**
- Tool name: hub
- Add or update? Add
- Desired version: latest
- Approximate size: 5MB
- If this is an add request:
  - Brief description of tool: A command-line tool that makes git easier to use with GitHub.
  - URL for tool's homepage: https://github.com/github/hub

**Virtual environments affected**
- [x] macOS 10.14
- [x] Ubuntu 16.04 LTS
- [x] Ubuntu 18.04 LTS
- [x] Windows Server 2016 R2
- [x] Windows Server 2019

**Can this tool be installed during the build?**
Just download a binary file. It will take less than a few seconds.

**Are you willing to submit a PR?**

**Comment by peaceiris** [comment]
https://github.com/github/hub/issues/2249#issuecomment-536557540

> To download hub for Linux and place the executable into bin/hub of current directory (no need to install it system-wide just to be used in an action):

```sh
wget -nv -O- \
  https://github.com/github/hub/releases/download/v2.12.7/hub-linux-amd64-2.12.7.tgz  | \
  tar xz --strip-components=1 '*/bin/hub'
```

**Comment by kaylangan** [comment]
:wave: Thanks for the suggestion! Are there specific hub commands that you're looking for? The extended git ones seem to be covered by having git installed, but some of the new commands offered by hub seem interesting.

**Comment by kaylangan** [comment]
Does [actions/github-script](https://github.com/actions/github-script) offer the functionality you're looking for?

**Comment by peaceiris** [comment]
I expected the hub to create issues and pulls easily. `actions/github-script` seems to satisfy my wants. Thank you for your reference.
