### ISSUE TITLE
Snapshot version of Composer in use

### ISSUE THREAD

**Issue by greg0ire** [actions/virtual-environments#1000]
**Describe the bug**
Composer v2 is not out yet, but it seems to be in use:
```
You are using the deprecated option "--no-suggest". It has no effect and will break in Composer 3.
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires dealerdirect/phpcodesniffer-composer-installer ^0.6.2 -> satisfiable by dealerdirect/phpcodesniffer-composer-installer[v0.6.2].
    - dealerdirect/phpcodesniffer-composer-installer v0.6.2 requires composer-plugin-api ^1.0 -> found composer-plugin-api[2.0.0] but it does not match the constraint.

You are using a snapshot build of Composer 2, which some of your plugins seem to be incompatible with. Make sure you update your plugins or report an issue to them to ask them to support Composer 2. To work around this you can run Composer with --ignore-platform-req=composer-plugin-api, but this may result in broken plugins and bigger problems down the line.
```

**Area for Triage**: 
PHP

**Question, Bug, or Feature?**: 
Bug

**Virtual environments affected**
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [x] Ubuntu 18.04 LTS
- [ ] Ubuntu 20.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Expected behavior**
Composer v1 should be used as long as v2 is not released

**Actual behavior**

https://github.com/doctrine/coding-standard/pull/195/checks?check_run_id=735650146

**Comment by maxim-lobanov** [comment]
Hello,
Actually it is not the issue with image. Composer 1.10.6 is installed on image.
Composer 2.0.0-alpha1 is installed by action `shivammathur/setup-php@1.8.2` that you use in your pipeline.

I have forked your repo and added additional steps to print version of composer before `setup-php` action and after that:
![image](https://user-images.githubusercontent.com/16715858/83676915-14e68680-a5e4-11ea-99bc-3301101d1daf.png)

**Comment by greg0ire** [comment]
Thanks for investigating, looks like I'm the best at reporting things to the wrong repo, see https://github.com/shivammathur/setup-php/issues/228 :sweat_smile:
