### ISSUE TITLE
nuget restore started failing on windows-2019 20200531.1

### ISSUE THREAD

**Issue by mcooley** [actions/virtual-environments#1001]
**Describe the bug**
"nuget restore" started encountering the following error in our environment: "NuGet.CommandLine.CommandLineException: MsBuild timeout out while trying to get project to project references."

The pipeline runs successfully with image version 20200524.1:
https://dev.azure.com/ms/calculator/_build/results?buildId=85001&view=logs&j=27ae15c2-a210-5a44-c856-4adc1d2b6ec9&t=023355e4-6a4e-54d0-4c0e-f65a98cfc541

But it fails with image version 20200531.1:
https://dev.azure.com/ms/calculator/_build/results?buildId=85241&view=logs&j=27ae15c2-a210-5a44-c856-4adc1d2b6ec9&t=023355e4-6a4e-54d0-4c0e-f65a98cfc541

**Area for Triage**: 
Packages

**Question, Bug, or Feature?**: 
Bug

**Virtual environments affected**
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Ubuntu 20.04 LTS
- [ ] Windows Server 2016 R2
- [X] Windows Server 2019

**Note**
I confirmed that:
- Updating to a newer version of NuGet.exe does not fix the problem
- Using NuGet.exe to restore the solution works successfully locally

**Expected behavior**
"nuget restore" runs successfully

**Actual behavior**
See links to the pipeline failure above. (The repo and pipeline definitions are open source.)

**Comment by maxim-lobanov** [comment]
Hello, thank you for your report.
I see that the latest your build is green. Could you please try to rerun pipeline a few more times to confirm that it was not temporary network issue?

**Comment by mcooley** [comment]
It appears that the builds are passing today. This is weird because the step that's failing doesn't indicate it's making a network request in any way, but I am happy the issue is resolved.
