### ISSUE TITLE
Setting up conda

### ISSUE THREAD

**Issue by henryiii** [actions/virtual-environments#1003]
**Tool information**
- Tool name: Miniconda
- Tool license: BSD 3-Clause
- Add or update? Add on macOS (already added for Linux and Windows)
- Desired version: 4.6.14 is already on windows-latest and 4.8.2 is on the three Ubuntu's. 4.7.12 is the latest production-stable and 4.8.3 is the latest.
- Approximate size: similar to other OS's
- If this is an add request:
  - Brief description of tool: Binary package manager, strong focus on Python
  - URL for tool's homepage: https://conda.io/projects/continuumio-conda

**Area for Triage**:

Python

**Question, Bug, or Feature?**:
This would be very nice if all three OS's had this, instead of just two.

**Virtual environments affected**
- [x] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Ubuntu 20.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Can this tool be installed during the build?**

**Tool installation time in runtime**

**Are you willing to submit a PR?**

Yes, though it might be possible just to copy what is done in Linux with a very minor change (or less likely, Windows). It is available via homebrew cask, as well, if those are used.

See https://github.com/actions/virtual-environments/blob/master/images/win/Windows2019-Readme.md#miniconda and https://github.com/actions/virtual-environments/blob/master/images/linux/Ubuntu2004-README.md

**Comment by miketimofeev** [comment]
Hi @henryiii! We already have Miniconda 4.8.2 on macOS. Take a look at the readme, please
https://github.com/actions/virtual-environments/blob/master/images/macos/macos-10.15-Readme.md

**Comment by henryiii** [comment]
Great! I did a quick search on that page, and for some reason, it didn't show up because I looked for conda instead of Miniconda (didn't think the browser looked for word boundaries).

It doesn't show up on macOS, though:

```
Run eval "$(conda shell.bash hook)"
/Users/runner/runners/2.263.0/work/_temp/4ccd6dca-c08b-4402-8367-b9da17e860ea.sh: line 1: conda: command not found
```

**Comment by miketimofeev** [comment]
env variable $CONDA pointed to /usr/local/miniconda:
```
    steps:
      - uses: actions/checkout@v2
      - name: check conda
        run: |
          echo ${CONDA}
          ${CONDA}/bin/conda --version
```
The result is
```
/usr/local/miniconda
conda 4.8.2
```

**Comment by henryiii** [comment]
Fantastic! Since this is a question now, is there a recommended way to setup the shells to work with conda? Conda has a function it provides for bash, cmd, powershell, and more that allows `conda activate <env>`, but they are not provided. Currently, this looks like it might be the way to do this cross platform?

```yaml
        shell: bash
        run: |
          eval "$(${CONDA}/bin/conda shell.bash hook)"
          # conda commands here, like activate
```

(on every action that needs conda)

**Comment by henryiii** [comment]
PS: Conda doesn't seem to work on macOS, when I try the above:

```
NotWritableError: The current user does not have write permissions to a required path.
  path: /usr/local/miniconda/envs/.conda_envs_dir_test
  uid: 501
  gid: 20

If you feel that permissions on this path are set incorrectly, you can manually
change them by executing

  $ sudo chown 501:20 /usr/local/miniconda/envs/.conda_envs_dir_test

In general, it's not advisable to use 'sudo conda'.
```

I can see if there's a way to find and source the old-style activate scripts in the environments, as I think the paths can be constructed now that I know about `${CONDA}`.

**Comment by henryiii** [comment]
Just as a test, I ran `conda init --all`, and it tried:

```
Run ${CONDA}/bin/conda init --all
no change     /usr/local/miniconda/condabin/conda
no change     /usr/local/miniconda/bin/conda
no change     /usr/local/miniconda/bin/conda-env
no change     /usr/local/miniconda/bin/activate
no change     /usr/local/miniconda/bin/deactivate
no change     /usr/local/miniconda/etc/profile.d/conda.sh
no change     /usr/local/miniconda/etc/fish/conf.d/conda.fish
no change     /usr/local/miniconda/shell/condabin/Conda.psm1
no change     /usr/local/miniconda/shell/condabin/conda-hook.ps1
no change     /usr/local/miniconda/lib/python3.7/site-packages/xontrib/conda.xsh
no change     /usr/local/miniconda/etc/profile.d/conda.csh
modified      /Users/runner/.bash_profile
modified      /Users/runner/.zshrc
modified      /Users/runner/.config/fish/config.fish
modified      /Users/runner/.xonshrc
modified      /Users/runner/.tcshrc
modified      /Users/runner/.config/powershell/profile.ps1
```

But, the RC scripts are not sourced in the next action, so that doesn't work as an action.

**Comment by henryiii** [comment]
Edit: I get the same macOS error about unwritable paths even when I just try to install an environment. Using the old-style activate more or less works:

```yaml
      - name: Environment install
        run: |
          ${CONDA}/bin/conda create -n testing python=3.8 # Breaks here on macOS
          ${CONDA}/bin/conda info

      - name: Install dependencies
        run: |
          source ${CONDA}/bin/activate testing
          conda env list
          conda install numpy
```
 Linux completes. Windows fails even if `shell: bash` is set since `${CONDA}/bin/conda` is incorrect, so it will need a different path for the two commands (conda init and activate). And macOS fails because the `/usr/local/miniconda/envs/` is not writable.

**Comment by henryiii** [comment]
I've used @goanpeca's action in several repos in the past, but switched to the built in conda, because I thought it was faster (preinstalled and not having to download Conda), and didn't require the `shell: bash -l {0}` workaround. I see that it now can use the built-in conda, which is fantastic and mostly solves my issue.

The way current (4.4+) conda works is this: A custom function called "conda" is installed by shell activation scripts. It wraps the conda executable with the ability to run `conda activate <env>`, which changes the shell environment, something a normal executable cannot do. It is faster than `source activate` and is the same syntax, across platform/shell, which is really nice in GHA. If it was possible to add that init to the base environment, that would be ideal, but might be too much. I don't even know if there are hooks to add shell functions in GHA. If this could be done, however, it would make conda much easier to run directly and might even solve the setup-miniconda's current `shell: bash -l {0}` requirement, too.

The symlink would be nice to have for consistency, and the permissions error on macOS might be good to fix, though.

Thank you!

**Comment by goanpeca** [comment]
Hi @henryiii, some comments:

1. > I see that it now can use the built-in conda, which is fantastic and mostly solves my issue.
Indeed it does, for several weeks (months?) now

2. The action now has caching support so for heavy size environments it makes things much faster. See https://github.com/goanpeca/setup-miniconda/#caching

3. You can now also install custom installers by url, like using [pypy](https://www.pypy.org/) from conda-forge
https://github.com/goanpeca/setup-miniconda/#example-5-custom-installer

4.  There is a "correctness" issue in the way the https://github.com/marketplace/actions/setup-miniconda was built. The idea is to never use the base environment for doing anything but a separate environment (Named by default `test`, but could be anything) that can pull the packages from different (non-compatible, default/conda-forge) channels.

5. Activation step with conda is crucial, since a lot of packages might appear to work fine without it, many others will not. So the `shell: bash -l {0}` is an annoying but necessary step (even if using the base environment). So any of the following is needed on every step:
- the `eval` command,
- the `source` command
- `shell: bash -l {0}` (and other similar) commands

Github Actions could provide a per Job `shell` key so we could just define the `shell: bash -l {0}` once per job.

**Comment by miketimofeev** [comment]
@henryiii we've deployed a new VM image where `conda` symlink is created:
```
  which conda
  conda --version
  shell: /bin/bash -e {0}
/usr/local/bin/conda
conda 4.8.2
```
I'm going to close the issue, but feel free to contact us if you have any concerns.
Thank you!
