### ISSUE TITLE
Add azcopy on Windows

### ISSUE THREAD

**Issue by dhadka** [actions/virtual-environments#1004]
**Tool information**
- Tool name: azcopy
- Tool license: MIT License
- Add or update? Add
- Desired version: v10
- Approximate size: 19 MBs
- If this is an add request:
  - Brief description of tool: AzCopy is a command-line utility that you can use to copy blobs or files to or from a storage account.
  - URL for tool's homepage: https://docs.microsoft.com/en-us/azure/storage/common/storage-use-azcopy-v10

**Area for Triage**:
Scripting and command line

**Question, Bug, or Feature?**:
Feature

**Virtual environments affected**
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Ubuntu 20.04 LTS
- [x] Windows Server 2016 R2
- [x] Windows Server 2019

**Can this tool be installed during the build?**

**Tool installation time in runtime**

**Are you willing to submit a PR?**

**Comment by dhadka** [comment]
AzCopy is installed on Ubuntu and Mac, but not Windows.  Needed for https://github.com/actions/toolkit/pull/493.

**Comment by dhadka** [comment]
Can be installed from https://chocolatey.org/packages/azcopy10

**Comment by maxim-lobanov** [comment]
@alepauly , moved this request directly to the our board since it is request from https://github.com/actions/toolkit/pull/493. Tool is pretty small and it makes sense to pre-install it for consistency.

**Comment by andy-mishechkin** [comment]
azcopy10 deployment has been done, you'll can find this utility after the next Windows Image deployment.
If you'll find some issues, please feel free to report us about it.

**Comment by andy-mishechkin** [comment]
azcopy10 available in Windows images and works good.
