### ISSUE TITLE
Add ImageMagick

### ISSUE THREAD

**Issue by ATiltedTree** [actions/virtual-environments#1009]
**Tool information**
- Tool name: ImageMagick
- Tool license: [custom](https://github.com/ImageMagick/ImageMagick/blob/master/LICENSE)
- Add or update? Add
- Desired version: 7.0.10-16
- Approximate size: About 80MB
- If this is an add request:
  - Brief description of tool: Allow editing and conversion of images using the command line
  - URL for tool's homepage: https://imagemagick.org/index.php or https://github.com/ImageMagick/ImageMagick

**Area for Triage**:
Scripting and command line

**Question, Bug, or Feature?**:
Feature

**Virtual environments affected**
- [x] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Ubuntu 20.04 LTS
- [x] Windows Server 2016 R2
- [x] Windows Server 2019

**Can this tool be installed during the build?**
For Windows:
`choco install imagemagick.tool --yes`
For macOS:
`brew install imagemagick`

**Tool installation time in runtime**
For Windows:
About 3m
For macOS:
About 2m

**Are you willing to submit a PR?**

**Comment by vmapetr** [comment]
@alepauly We already have imagemagick on Ubuntu, perhaps we should add it to other images, to be consistent?

**Comment by maxim-lobanov** [comment]
Hello, thank you for feature request but we wouldn't like to pre-install this tool to images for now. It is intended for specific purposes and could be installed in runtime.
