### ISSUE TITLE
CONTRIBUTING.md links to missing file in help/CreateImageAndAzureResources.md

### ISSUE THREAD

**Issue by nvtkaszpir** [actions/virtual-environments#101]
**Describe the bug**
CONTRIBUTING.md links to missing file in help/CreateImageAndAzureResources.md
This means the documentation how to test the code is totally missing.

**Virtual environments affected**
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

I would say any in above but it's just a documentation error.

**Expected behavior**
URL works and points to valid documentation URL.

**Actual behavior**
1. clik https://github.com/actions/virtual-environments/blob/master/CONTRIBUTING.md
2. in section `Submitting a pull request` in point 4 there `Test your changes by creating VHD and deploying a VM`.
3. click the url with.
4. behold HTTP 404 web page error - https://github.com/actions/virtual-environments/blob/master/help/CreateImageAndAzureResources.md

**Comment by nvtkaszpir** [comment]
OK, looks like it should point to document which describes packer usage such as https://github.com/Microsoft/azure-pipelines-image-generation/blob/master/help/CreateImageAndAzureResources.md

**Comment by maxim-lobanov** [comment]
Thank you for notification!
It was fixed recently with #314 .
