### ISSUE TITLE
Details of included Go version is missing in the included software documentation for windows-2019 and vs2017-win2016 images

### ISSUE THREAD

**Issue by mustafaoral** [actions/virtual-environments#1011]
**Describe the bug**
The included software documents for [`windows-2019`](https://github.com/actions/virtual-environments/blob/master/images/win/Windows2019-Readme.md) and [`vs2017-win2016`](https://github.com/actions/virtual-environments/blob/master/images/win/Windows2016-Readme.md) images are missing details about included Go version as well as Go related environment variables.

Running `go version` in the pipeline using both images produces `go version go1.14.3 windows/amd64`, confirming Go is still included.

Commits that broke documentation are:

`windows-2019`: [44f2342c9e796a4d0c3bd36aff870b38abd6a71b](https://github.com/actions/virtual-environments/commit/44f2342c9e796a4d0c3bd36aff870b38abd6a71b)
`vs2017-win2016`: [e91f2138c0b7304831e9aaa43ea47279d4160ef4](https://github.com/actions/virtual-environments/commit/e91f2138c0b7304831e9aaa43ea47279d4160ef4)

**Area for Triage**: 
Go

**Question, Bug, or Feature?**: 
Bug

**Virtual environments affected**
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Ubuntu 20.04 LTS
- [x] Windows Server 2016 R2
- [x] Windows Server 2019

**Comment by al-cheb** [comment]
@mustafaoral, Hello

We have updated our documentation to provide details about GO. The updated documentation files will be available in one or two weeks for Windows Server 2016/2019.

E.g. - https://github.com/actions/virtual-environments/releases/tag/win16%2F20200604.1

**Windows Server 2019** - https://github.visualstudio.com/virtual-environments/_build/results?buildId=71713&view=logs&j=011e1ec8-6569-5e69-4f06-baf193d1351e&t=72559e73-928c-58e0-b67e-e22d7a78faae
#### Go
| Version | Architecture | Environment Variable |
| ------- | ------------ | -------------------- |
| 1.9.7   | x64          | GOROOT_1_9_X64       |
| 1.10.8  | x64          | GOROOT_1_10_X64      |
| 1.11.13 | x64          | GOROOT_1_11_X64      |
| 1.12.17 | x64          | GOROOT_1_12_X64      |
| 1.13.12 | x64          | GOROOT_1_13_X64      |
| 1.14.4 (Default) | x64          | GOROOT_1_14_X64      |

**Windows Server 2016** - https://github.visualstudio.com/virtual-environments/_build/results?buildId=71711&view=logs&j=011e1ec8-6569-5e69-4f06-baf193d1351e&t=72559e73-928c-58e0-b67e-e22d7a78faae

#### Go
| Version | Architecture | Environment Variable |
| ------- | ------------ | -------------------- |
| 1.9.7   | x64          | GOROOT_1_9_X64       |
| 1.10.8  | x64          | GOROOT_1_10_X64      |
| 1.11.13 | x64          | GOROOT_1_11_X64      |
| 1.12.17 | x64          | GOROOT_1_12_X64      |
| 1.13.12 | x64          | GOROOT_1_13_X64      |
| 1.14.4 (Default) | x64          | GOROOT_1_14_X64      |

**Comment by al-cheb** [comment]
@mustafaoral, Hello
Documentation for Windows Server 2016/2019 was updated and contains info about GO details:
Windows Server 2016 - https://github.com/actions/virtual-environments/blob/master/images/win/Windows2016-Readme.md
Windows Server 2019 - https://github.com/actions/virtual-environments/blob/master/images/win/Windows2019-Readme.md

Feel free to reopen the thread if you have any concerns.
