### ISSUE TITLE
Caching proxy for Homebrew/macOS

### ISSUE THREAD

**Issue by zbeekman** [actions/virtual-environments#1012]
If you have a feature request that is relevant to this repository, the runner, then please include the information below:

**I'm not 100% sure this is the correct location to file this feature request**

**Describe the enhancement**
Improve caching on macOS, especially homebrew bottles by setting `*_proxy` variables in the environment or setting `HOMEBREW_BOTTLE_DOMAIN`.

I saw that there is [an ADR for supporting proxies on self-hosted or enterprise runners](https://github.com/actions/runner/blob/master/docs/adrs/0263-proxy-support.md), but I don't know to what extent GitHub is employing caching proxies to keep things fast on the GitHub hosted runners, especially on macos. Homebrew provides multiple mechanisms for using proxies, but [my experimentation](https://github.com/zbeekman/brew-GHA-profiling/tree/gh-pages#profiling-and-default-homebrew-configuration-in-github-actions) seems to suggest that this may not be happening for homebrew bottles and other assets. Homebrew downloads bottles from the bintray API even for relatively common, highly used formula as can be seen in the logs. If there is any caching proxy it seems that homebrew is not using it or it's deviously sneaky.

**Code Snippet**
Not 100% sure where/how to implement this, but here is the relevant text from `man brew`:

* HOMEBREW_BOTTLE_DOMAIN
  > By  default,  Homebrew  uses  https://homebrew.bintray.com/  as  its  download  mirror  for  bottles.  If  set,  instructs  Homebrew to instead use the specified URL. For example, HOMEBREW_BOTTLE_DOMAIN=http://localhost:8080 will cause all bottles to download from the prefix http://localhost:8080/.
* http_proxy
  > Sets the HTTP proxy to be used by curl, git and svn when downloading through Homebrew.
* https_proxy
  >Sets the HTTPS proxy to be used by curl, git and svn when downloading through Homebrew.
* all_proxy
  >Sets the SOCKS5 proxy to be used by curl, git and svn when downloading through Homebrew.
* ftp_proxy
  > Sets the FTP proxy to be used by curl, git and svn when downloading through Homebrew.

By setting one or more of these environment variables in the macos runner environment and pointing them to a caching proxy that will forward requests to the appropriate location I think macOS installation times could be reduced, as well as reducing network traffic to external sources.

If `HOMEBREW_BOTTLE_DOMAIN` is used, then care must be taken: For any install from https://homebrew.bintray.com things will work fine, but some 3rd party taps host their own bottles, so the caching proxy would have to have logic to determine where to fetch the bottle from if this method was used. On the other hand, setting `http_proxy` and `https_proxy` is a pretty big hammer and you'll end up caching other stuff people grab with `curl` etc.

**Additional information**
FYI, I am a Homebrew-core maintainer.

Thanks for taking the time to read this, and if you think this should be posted elsewhere please point me in the right direction. Cheers!

NOTE: if the feature request has been agreed upon then the assignee will create an ADR.   See docs/adrs/README.md

**Comment by miketimofeev** [comment]
@alepauly we've never heard complaints about macOS brew installation process and this issue seems to take a lot of efforts to implement and maintenance on the Azure side

**Comment by alepauly** [comment]
Hi @zbeekman, I like this idea but it's not something that we can support and maintain at this time. One thought is to create something like a `setup-homebrew` Actions that accepts the bottle domain as a parameter and can use it. This generalizes so that anyone can specify their own domain but it could be followed up with community a maintained or other centralized proxy? Or could maybe the setup could take advantage of the actions/cache and implement a proxy based off it?

and sorry for the delay in responding!

**Comment by alepauly** [comment]
Closing since it's not something we can address in this repo. Please reopen to discuss more if needed.
