### ISSUE TITLE
Update/Add Unity Hub

### ISSUE THREAD

**Issue by StephenHodgson** [actions/virtual-environments#1013]
**Tool information**
- Tool name: Unity Hub
- Tool license: 
- Add or update? Add
- Desired version: 2.3.2
- Approximate size: 
- If this is an add request:
  - Brief description of tool: Unity Hub for installing and managing the Unity Game Engine Editor installations, modules, and licensing.
  - URL for tool's homepage: https://unity3d.com/get-unity/download

**Area for Triage**:

Scripting and command line

**Question, Bug, or Feature?**:

Feature

**Virtual environments affected**
- [x] macOS 10.15
- [x] Ubuntu 16.04 LTS
- [x] Ubuntu 18.04 LTS
- [x] Ubuntu 20.04 LTS
- [x] Windows Server 2016 R2
- [x] Windows Server 2019

**Can this tool be installed during the build?**

yes, see example powershell script [here](https://github.com/StephenHodgson/UnityCI/blob/master/InstallUnityHub.ps1).

**Tool installation time in runtime**

~3-15 minutes

**Are you willing to submit a PR?**

yes, but I'll need guidance

**Comment by maxim-lobanov** [comment]
@StephenHodgson , thank you for providing example script.
Just to clarify request: Do you want to pre-install only Unity Hub or install Unity Editor and additional modules too?
The issue mentions only Unity Hub but its installation in runtime is pretty quick. Installation of Editor and other modules takes the most of the time.

**Comment by StephenHodgson** [comment]
I'd just like to have the Unity Hub pre-installed on Windows, Linux, and Mac so I can easily download whichever editor isn't currently installed on the image. 

As far as editor installations, I think that's something the community should probably answer.
There's the 2019.4 LTS (long term support) which is the latest release. 

There's already an editor installed from Visual Studio, but Microsoft doesn't update it very often.

**Comment by thejoebourneidentity** [comment]
Thanks @StephenHodgson, it's a cool idea. We're not going to plan on adding this tool quite yet to the base image, but will keep this issue open as a way to let others in the community vote on how important it is for them.

**Comment by JesseTG** [comment]
@thejoebourneidentity @maxim-lobanov @StephenHodgson [Good idea!](https://github.com/actions/virtual-environments/issues/109)

**Comment by FejZa** [comment]
Also second this. Having the Unity Hub installed and the Unity Hub CLI available to install editors would be great!

**Comment by StephenHodgson** [comment]
Just an update to this. It seems Microsoft has included it by default in the game workload for visual studio.

This probably wouldn't matter much for windows anymore, but Mac and Linux would likely still need it. Unsure.

**Comment by kuler90** [comment]
Hi all. I had the same problem and created [setup-unity](https://github.com/marketplace/actions/setup-unity) action based on Unity Hub CLI. It works on Ubuntu, macOS and Windows.

**Comment by AlenaSviridenko** [comment]
Hi there,
sorry for a late reply on this request but we are not going to add this tool on the base image for 2 reasons:
1. Tool can be installed in runtime pretty quick
2. The recommended way to interact with tools in through actions if they exist, as they are usually providing more rich functionality. Thank you @kuler90 for the setup-unity action!

I am going to close this issue, please feel free to file a new one if any help needed.
Thanks!

**Comment by StephenHodgson** [comment]
@AlenaSviridenko haha this is def not true. Still having trouble automating the Linux hub setup. (not to mention no reply from Unity bug reports, ya know, bc Unity...)

But yeah afaik it's already installed for win based machines. Mac and Linux, I have no idea.

**Comment by StephenHodgson** [comment]
Also, I'm using Azure Pipelines, so the GitHub Actions are of no use for me.
