### ISSUE TITLE
Add Composer for macOS

### ISSUE THREAD

**Issue by stevegrunwell** [actions/virtual-environments#1014]
**Tool information**
- Tool name: Composer
- Tool license: MIT
- Add or update? Add
- Desired version: latest
- Approximate size: 2MB
- If this is an add request:
  - Brief description of tool: Package manager for PHP
  - URL for tool's homepage: https://getcomposer.org/

**Area for Triage**:
Apple, Packages, PHP

**Question, Bug, or Feature?**:
Feature

**Virtual environments affected**
- [x] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Ubuntu 20.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Can this tool be installed during the build?**
Yes, Composer provides an automated installation script: https://getcomposer.org/download/. This is already being utilized in the Windows and Linux images: https://github.com/actions/virtual-environments/blob/85331140fc0bb5e4cff2adc9f5d70258b793e5f4/images/linux/scripts/installers/php.sh#L96

**Tool installation time in runtime**
< 1min

**Are you willing to submit a PR?**
Yes, but the macOS source is not currently available in the repository.

**Comment by dibir-magomedsaygitov** [comment]
Hello @alepauly!
Installation of this tool takes less than 10 seconds in runtime and approximate size is 2MB. We already have composer in our Windows and Linux images, so adding it to macOS images makes sense.

**Comment by vmapetr** [comment]
Hi @stevegrunwell !
Composer support was added to macOS 10.15.
