### ISSUE TITLE
Android workflow crash for Android 11

### ISSUE THREAD

**Issue by vincent-paing** [actions/virtual-environments#1015]
**Describe the bug**
Crash when compiling with Android-R

**To Reproduce**
1. Setup An android project
2. Change your `targetSdk` and `compileSdk` to Android R ([doc)](https://developer.android.com/preview/)
3. In workflow, set runner to ubuntu-latest
4. Compile the app with `./gradlew assemble`

**Expected behavior**
The build should pass

## Runner Version and Platform
Ubuntu-latest

## Job Log Output

```
File /home/runner/.android/repositories.cfg could not be loaded.
Checking the license for package Android SDK Platform R in /usr/local/lib/android/sdk/licenses
License for package Android SDK Platform R accepted.
Preparing "Install Android SDK Platform R (revision: 4)".
Warning: Failed to read or create install properties file.

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:compile***Kotlin'.
> Failed to install the following SDK components:
      platforms;android-R Android SDK Platform R
  The SDK directory is not writable (/usr/local/lib/android/sdk)
```

**Comment by vmapetr** [comment]
Hi @vincent-paing! 
Sorry for delayed response, fix is prepared and soon be delivered. In a meantime you can use `sudo ./gradlew assemble` as a temporary workaround.

**Comment by miketimofeev** [comment]
@vincent-paing could you check the behavior, please? It is supposed to work now.

**Comment by tnc1997** [comment]
My [workflow](https://github.com/tnc1997/flutter-tfl-api-explorer/runs/810015010?check_suite_focus=true#step:5:48) is now succeeding @miketimofeev, thank you for adding the Android SDK Platform 30.

**Comment by samtstern** [comment]
I can also confirm my Android 30 builds work out of the box now, this issue can be closed.
