### ISSUE TITLE
Mismatch between Python pei-x86-64 and MinGW-w64 pei-i386 arches

### ISSUE THREAD

**Issue by fireundubh** [actions/virtual-environments#102]
**Describe the bug**
When I try to use [Nuitka](https://nuitka.net/pages/overview.html) to compile with x64 Python and MinGW-w64, Nuitka throws the following exception:
```
Mismatch between Python pei-x86-64 and MinGW64 ('pei-i386') arches
```
The maintainer of Nuitka told me this is a real error. The arches must match. Either the x64 arch of MinGW-w64 is not installed, or an undocumented environment variable is needed to switch the arch.

The [Software installed on GitHub-hosted runners](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/software-installed-on-github-hosted-runners) page does not provide any guidance and confusingly lists MinGW instead of MinGW-w64 although `choco install mingw` installs MinGW-w64.

**Virtual environments affected**
- [X] Windows Server 2019

**Comment by fireundubh** [comment]
From testing choco locally, `choco install mingw` appears to install the x86 version of MinGW-w64. Would this issue be better off as a tool request?

**Comment by andy-mishechkin** [comment]
MinGW 64 is planned to add as part of MSYS2:
https://github.com/actions/virtual-environments/issues/30

**Comment by AlenaSviridenko** [comment]
PR with MSYS2 installation: https://github.com/actions/virtual-environments/pull/632. It will be merged after pandemic is going down in order not to bring possibly dangerous changes on image and reduce customers impact.
Thanks!

**Comment by mati865** [comment]
> From testing choco locally, choco install mingw appears to install the x86 arch of MinGW-w64. Would this issue be better off as a tool request?

Choco installs arch matching the OS arch so you get i686 mingw-w64 on 32 bit Windows and x86_64 on 64 bit Windows.
On the CI only x86_64 mingw-w64 is installed: https://github.com/mati865/actions-test/runs/638620890?check_suite_focus=true

**Comment by vsafonkin** [comment]
Hi @fireundubh , MinGW-w64 is installed on Windows images. I've closed this issue, please feel free reopen it if you have any concerns or problems. Thank you!
