### ISSUE TITLE
Add cargo audit & cargo outdated

### ISSUE THREAD

**Issue by sciguy16** [actions/virtual-environments#1029]
**Tool information**
- Tool name: cargo audit and cargo outdated
- Tool license: MIT & Apache2 dual
- Add or update? add
- Desired version: latest from crates.io
- Approximate size: 
- If this is an add request:
  - Brief description of tool: 'cargo audit' checks dependencies against the RustSec security advisory database. 'cargo outdated' checks whether any dependencies are outdated.
  - URL for tool's homepage: https://github.com/RustSec/cargo-audit https://github.com/kbknapp/cargo-outdated

**Area for Triage**:
Rust

**Question, Bug, or Feature?**:
Feature

**Virtual environments affected**
- [x] macOS 10.15
- [x] Ubuntu 16.04 LTS
- [x] Ubuntu 18.04 LTS
- [x] Ubuntu 20.04 LTS
- [x] Windows Server 2016 R2
- [x] Windows Server 2019

**Can this tool be installed during the build?**
cargo install cargo-audit
cargo install cargo-outdated

**Tool installation time in runtime**
cargo-audit: 5m 52s
cargo-outdated: 8m 3s

**Are you willing to submit a PR?**
Yes

**Comment by dmitry-shibanov** [comment]
Hello, thank you for your response, pull requests were merged. Changes will be added in next images rollout.

**Comment by dmitry-shibanov** [comment]
Hello changes were added to images. If you have any concerns feel free to reopen the issue.
