### ISSUE TITLE
VHDs being deprecated

### ISSUE THREAD

**Issue by henti** [actions/virtual-environments#1037]
**Describe the bug**
VHD support in packer is ending, we should switch to using managed images. 

```
==> azure-arm: Warning: You are using Azure Packer Builder to create VHDs which is being deprecated, consider using Managed Images. Learn more http://aka.ms/packermanagedimage
```

**Area for Triage**: 
servers

**Question, Bug, or Feature?**: 
Feature

**Virtual environments affected**
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [x] Ubuntu 20.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

Tho this will impact all images. 

**Expected behavior**
No error and maged image :) 

**Actual behavior**

Warning about VHD deprecation and VHDs.

**Comment by Darleev** [comment]
Hi @henti,
Thank you for the notification. We are aware of the problem, but currently, I do not have additional information, specific ETA, or plans for it.
@alepauly Could you please take a look? Are we planning to migrate from VHDs to Managed Images?

**Comment by maxim-lobanov** [comment]
Is there any accurate date for deprecation VHDs? End of support for VHDs approach
We definitely want to do migration but it would allow us to plan it properly.

**Comment by maxim-lobanov** [comment]
We have got confirmation from Packer team that VHDs won't be deprecated in near future: https://github.com/hashicorp/packer/issues/9647

**Comment by maxim-lobanov** [comment]
Hello! Thank you for sharing your proposal.
Considering the fact that VHDs will work as previously in near future, we don't have close plans to switch to managed images since it will require reworking our current infrastructure.
