### ISSUE TITLE
Add Apache Ant

### ISSUE THREAD

**Issue by ialarmedalien** [actions/virtual-environments#1040]
**Tool information**
- Tool name: ant
- Tool license: [Apache License v2.0](https://www.apache.org/licenses/LICENSE-2.0)
- Add or update? Add
- Desired version: ideally 1.10.x (current version is 1.10.8)
- Approximate size: 4 - 8MB compressed, depending on compression algorithm
- If this is an add request:
  - Brief description of tool: 

> Apache Ant is a Java library and command-line tool whose mission is to drive processes described in build files as targets and extension points dependent upon each other. The main known usage of Ant is the build of Java applications. Ant supplies a number of built-in tasks allowing to compile, assemble, test and run Java applications. Ant can also be used effectively to build non Java applications, for instance C or C++ applications. More generally, Ant can be used to pilot any type of process which can be described in terms of targets and tasks.

  - URL for tool's homepage: https://ant.apache.org

**Area for Triage**:
Packages, Apple

**Question, Bug, or Feature?**:
Feature

**Virtual environments affected**
- [ x ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Ubuntu 20.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Can this tool be installed during the build?**
Yes, by running `brew install ant` as a step in a workflow. [Example](https://github.com/ialarmedalien/kb_sdk/runs/766788749?check_suite_focus=true)

**Tool installation time in runtime**
1m 20s (43s installation time, the rest was looking for mirrors)

**Are you willing to submit a PR?**
If there are examples or documentation that I can follow.

**Comment by al-cheb** [comment]
Hello, @ialarmedalien 
Apache Ant is now pre-installed  on the macOS Catalina 10.15 image - https://github.com/actions/virtual-environments/blob/master/images/macos/macos-10.15-Readme.md
