### ISSUE TITLE
Is there any possibility to have stronger VMs for the CI?

### ISSUE THREAD

**Issue by f-squirrel** [actions/virtual-environments#1043]
**Question**:
In our project[1], we consider migrating to GitHub Actions from Travis CI.
I've created a workflow in the repository.
However, some of our tests fail randomly in GitHub Actions while passing in Travis CI.
As part of our CI, we run a few quite heave tests using a lot of RAM.
I suspect that the slight difference between the VMs(7GB in GA vs. 7.5GB in Travis CI) makes the difference.

Is there any option to have stronger machines in GitHub Actions(in terms of RAM and CPU)?

I know that there is an option to use self-hosted runners but according to GA guidelines they are not recommended for public repositories.

[1] - https://github.com/vmware/concord-bft
**Virtual environments affected**
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [x ] Ubuntu 18.04 LTS
- [ ] Ubuntu 20.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Comment by maxim-lobanov** [comment]
Hello!
Unfortunately, currently, we don't have way to provide stronger machines for CI. 
@alepauly , do you know if there is any options here?

**Comment by maxim-lobanov** [comment]
I am going to close this issue since, currently, there is no way to have stronger machines.
We will announce if there is any improvements in this direction

**Comment by xp-vit** [comment]
https://github.com/github/roadmap/issues/161

Is on the GitHub roadmap for Q3 2021. So, I assume it's coming.

**Comment by maxim-lobanov** [comment]
@xp-vit , Yes, it is correct.
But we can't provide estimation for now, it is better to track via roadmap issue.
