### ISSUE TITLE
MAX_PATH lengths on Windows environment

### ISSUE THREAD

**Issue by bubba** [actions/virtual-environments#1052]
**Describe the bug**
I'm hitting the MAX_PATH restriction on a windows environment, which restricts file paths to 260 characters. Unfortunately in my workflow [gcc here is failing to link](
https://github.com/bubba/haskell-language-server/runs/768413286?check_suite_focus=true#step:7:55) since this rather unwieldily build file hits that limit.

It's not really a problem with the environment runner itself I guess, but it would be really handy if this limit could be disabled: I'm not a windows person myself, but apparently in newer versions of [Windows 10 this limit can be overridden via a registry key](https://docs.microsoft.com/en-gb/windows/win32/fileio/naming-a-file?redirectedfrom=MSDN#enable-long-paths-in-windows-10-version-1607-and-later)

**Area for Triage**: 
Servers

**Question, Bug, or Feature?**: 
Feature

**Virtual environments affected**
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Ubuntu 20.04 LTS
- [ ] Windows Server 2016 R2
- [X] Windows Server 2019

**Expected behavior**
Files with long paths to be created

**Actual behavior**
Files with long paths go missing, and cause tooling errors

**Comment by al-cheb** [comment]
Hello, @bubba 

The `'LongPathsEnabled'` parameter is already set to 1 on Windows Server 2016/2019.

```
- name: Check LongPathsEnabled
      run: |
          (Get-ItemProperty "HKLM:System\CurrentControlSet\Control\FileSystem").LongPathsEnabled
```
![image](https://user-images.githubusercontent.com/47745270/84677826-eea3dd80-af37-11ea-8859-2960e2933c9a.png)

**Comment by bubba** [comment]
My bad, I didn't realise this. I'm not seeing any explicit errors about MAX_PATH in my case, so I can only assume there is an issue with `realgcc.exe`/`ghc.exe` that's silently failing to write the files somehow

**Comment by al-cheb** [comment]
@bubba, Therefore, the issue is related with `realgcc.exe/ghc.exe`  issue I will close the thread if you have any concerns please create a new issue.
