### ISSUE TITLE
Refactor apt/ulimit commands in ubuntu image packer templates

### ISSUE THREAD

**Issue by gswallow** [actions/virtual-environments#1061]
Hi,

I'm toying around with this project as I am building an AWS EC2 AMI, which I can fire up in my own VPCs.  I have a pull request where I take the commands in https://github.com/actions/virtual-environments/blob/40caaf3e2c11a9e4289482cce72e14ed97fa64fe/images/linux/ubuntu2004.json#L80-L93, and move them into their own scripts in the base folder.

Not much value, other than it eases my mind when I look at the code :)

I hope I can submit another PR soon with a packer template that builds AMIs via a separate pipeline.

**Comment by miketimofeev** [comment]
@gswallow Ubuntu images with the changes were deployed, thanks for your contribution!
