### ISSUE TITLE
Add Newman

### ISSUE THREAD

**Issue by m-standfuss** [actions/virtual-environments#1063]
**Tool information**
- Tool name: Newman
- Tool license: Apache-2.0. Copyright Postdot Technologies, Inc.
- Add or update? Add
- Desired version: Latest
- Approximate size: 
- If this is an add request:
  - Brief description of tool: Newman is a command-line collection runner for Postman. It allows you to effortlessly run and test a Postman collection directly from the command-line. It is built with extensibility in mind so that you can easily integrate it with your continuous integration servers and build systems. (taken from their page)
  - URL for tool's homepage: https://github.com/postmanlabs/newman

**Area for Triage**:
Testing and code coverage

**Question, Bug, or Feature?**:
Feature

**Virtual environments affected**
- [x ] macOS 10.15
- [x ] Ubuntu 16.04 LTS
- [x ] Ubuntu 18.04 LTS
- [x ] Ubuntu 20.04 LTS
- [x ] Windows Server 2016 R2
- [x ] Windows Server 2019

**Can this tool be installed during the build?**
npm install -g newman
or 
brew install newman

**Tool installation time in runtime**
Ran on an azure agent and got this in the output
2020-06-16T21:19:36.6365565Z added 157 packages from 197 contributors in 38.651s

**Are you willing to submit a PR?**
If there are examples or documentation that I can follow.

**Comment by vmapetr** [comment]
Installed package size: 41MB
Approximate installation time during image generation: 20 sec

**Comment by vsafonkin** [comment]
Hi @m-standfuss , Newman was added to all images, thank you!
