### ISSUE TITLE
DOS line endings tripped me up?

### ISSUE THREAD

**Issue by gswallow** [actions/virtual-environments#1068]
Both the azpowershell.sh and pypy.sh files have DOS line endings, which may have tripped me up running a packer build.  Stepping through the process manually, at least, I had to convert those files to Unix format for them to run.

When running packer build without the --debug flag, I had two builds pause indefinitely on azpowershell.sh.  Re-running another build to confirm.  Sorry if I got the area for triage wrong, and expect a pull request with changed line endings.

**Area for Triage**: 
['Area: Scripting and command line']

**Question, Bug, or Feature?**: 
Bug

**Virtual environments affected**
- [ ] macOS 10.15
- [x] Ubuntu 16.04 LTS
- [x] Ubuntu 18.04 LTS
- [x] Ubuntu 20.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Expected behavior**
azpowershell.sh runs and completes

**Actual behavior**
run packer build --debug ubuntu2004.json
wait for the azpowershell.sh script runs
build hangs

**Comment by miketimofeev** [comment]
Hi @gswallow! I've prepared PR with the fix
https://github.com/actions/virtual-environments/pull/1069

**Comment by gswallow** [comment]
Wow, you guys are fast.  I'm used to waiting for a few years and forgetting what issues are about.  Thanks!
