### ISSUE TITLE
Add Dart SDK

### ISSUE THREAD

**Issue by cachapa** [actions/virtual-environments#107]
**Tool information**
- Tool name: Dart SDK
- Add or update? Add
- Desired version: Latest stable (currently 2.6)
- Approximate size: ~160MB
- If this is an add request:
  - Brief description of tool: Dart is a modern programming language from Google
  - URL for tool's homepage: https://dart.dev

**Virtual environments affected**
- [x] macOS 10.15
- [x] Ubuntu 16.04 LTS
- [x] Ubuntu 18.04 LTS
- [x] Windows Server 2016 R2
- [x] Windows Server 2019

**Can this tool be installed during the build?**
Yes, using Google's own docker container: ~36s
Using DanTup/gh-actions/setup-dart: ~11s

**Are you willing to submit a PR?**
Yes

**Comment by thisismydesign** [comment]
My similar request here: https://github.community/t5/GitHub-Actions/Native-Dart-availability/m-p/39416

**Comment by tenhobi** [comment]
@thisismydesign Flutter uses it's own Dart, not the system one. So this would not help.

**Comment by thisismydesign** [comment]
Are there other forms of installation? Building from source (and caching) perhaps?

**Comment by thisismydesign** [comment]
Or just by setting the path to use the native Dart and removing Dart from the Flutter installation you could save a lot of space on the cache.

**Comment by alepauly** [comment]
@cachapa thanks for the suggestion but considering that this can be done with existing `setup-dart` Actions and keeping multiple versions of Dart is a maintenance concern, we're not going to install it on the environment by default.
