### ISSUE TITLE
Google Cloud CLI (gcloud) is missing in the latest 24.04 Ubuntu update

### ISSUE THREAD

**Issue by PHGLPagani** [actions/virtual-environments#10769]
### Description

Our GHAs depend on Google Cloud CLI 495.0.0 (`gcloud`), which was previously present in [Ubuntu 22.04](https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2204-Readme.md) image is no longer present in the [Ubuntu 24.04](https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2404-Readme.md) image.

As a result our builds are failing. This is a similar issue to what was flagged on issue #10767

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [X] Ubuntu 24.04
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] macOS 15
- [ ] macOS 15 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Working Image: [Ubuntu 22.04](https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2204-Readme.md)
Non-Working Image: [Ubuntu 24.04](https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2404-Readme.md)

### Is it regression?

Ubuntu 22.04

### Expected behavior

`gcloud` is available

### Actual behavior

`gcloud` is not available

### Repro steps

1. Run anything using `gcloud` CLI in the latest ubuntu runner version.
2. It fails because of missing `gcloud` CLI.

**Comment by soroshansari** [comment]
I fixed the issue by adding this additional step before using the cloud to set up Cloud SDK.

```
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'
        with:
          version: '>= 363.0.0'
```

**Comment by RaviAkshintala** [comment]
Hi @PHGLPagani  Thank you for bringing this issue to our attention. We are looking into this issue and will update you on this issue after investigating.

**Comment by hemanthmanga** [comment]
Hi @PHGLPagani, This [PR](https://github.com/actions/runner-images/pull/10881) will be resolve your issue. Thanks.

**Comment by hemanthmanga** [comment]
Hi @PHGLPagani , The new image 20241103.1 has been rolled out, We are closing this issue. Thanks.
