### ISSUE TITLE
runs-on: ubuntu-latest - Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/*

### ISSUE THREAD

**Issue by classicrocker883** [actions/virtual-environments#10785]
### Description

[from this workflow here](https://github.com/MarlinFirmware/Marlin/actions/runs/11347856073/job/31560271325?pr=27380)

```r
E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/main/m/mesa/libegl-mesa0_24.0.9-0ubuntu0.1_amd64.deb  404  Not Found [IP: 52.147.219.192 80]
E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/main/m/mesa/libgbm-dev_24.0.9-0ubuntu0.1_amd64.deb  404  Not Found [IP: 52.147.219.192 80]
E: Unable to fetch some archives
```

here is a snippet from the workflow:

    - runs-on: ubuntu-latest
    - name: Install Simulator dependencies
      run: |
        sudo apt-get install build-essential

basically something is wrong with http://azure.archive.ubuntu.com
going to [this link](http://azure.archive.ubuntu.com/ubuntu/pool/) manually results in 

```r
NoSuchKeyubuntutx00000203468a7a0b49b3f-00670e7c05-5afce5e-default5afce5e-default-default
This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>NoSuchKey</Code>
<BucketName>ubuntu</BucketName>
<RequestId>tx00000203468a7a0b49b3f-00670e7c05-5afce5e-default</RequestId>
<HostId>5afce5e-default-default</HostId>
...
</Error>
```
yet, http://azure.archive.ubuntu.com/ubuntu/ubuntu/pool/ results in an empty directory. oddly enough one can go to http://azure.archive.ubuntu.com/ubuntu/ubuntu/ubuntu/ubuntu/ubuntu/ubuntu/
(keep clicking `ubuntu` and this will go on forever)

I haven't tried any other Ubuntu images, just the latest

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [X] GitHub Actions - Larger Runners

### Runner images affected

- [X] Ubuntu 24.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] macOS 15
- [ ] macOS 15 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Current runner version: '2.320.0'

### Is it regression?

idk

### Expected behavior

Expected to fetch/download

### Actual behavior

Fails to fetch/download

### Repro steps

1. Start a workflow with ubuntu-latest
2. run sudo apt-get install build-essential
2a. or probably run any install package
3. observe actions

**Comment by RaviAkshintala** [comment]
Hi @classicrocker883 Thank you for bringing this issue to our attention. We are looking into this issue and will update you on this issue after investigating.

**Comment by cmeyer** [comment]
@subir0071 Thanks that worked!
