### ISSUE TITLE
Update/Add Helm v3

### ISSUE THREAD

**Issue by AgrimPrasad** [actions/virtual-environments#108]
**Tool information**
- Tool name: Helm
- Add or update? Add v3 while keeping v2
- Desired version: Helm v3
- Approximate size:
- If this is an add request:
  - Brief description of tool: Helm v3
  - URL for tool's homepage: 

**Virtual environments affected**
- [ ] macOS 10.15
- [x] Ubuntu 16.04 LTS
- [x] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Can this tool be installed during the build?**
Yes, should be quick to install. Sample for installing helm3 while keeping helm v2: https://github.com/deliverybot/helm/blob/a58b37b8a245e76b77e7b39cf715675cf3b8d3d7/Dockerfile

**Are you willing to submit a PR?**
No

**Comment by damlys** [comment]
Also hope to see Helm v3 soon 👍 My team don't use v2 since few months. Changes between these versions are huge and v2 is useless for new projects

**Comment by maxim-lobanov** [comment]
Reopened since changes were not deployed yet.
Changes will be deployed with next image rollout, we will let you know

**Comment by maxim-lobanov** [comment]
Closing since Helm 3 is available on image. Sorry for delayed notification
