### ISSUE TITLE
[ubuntu-24.04] Default Nodejs version will be set to 22 on November, 4

### ISSUE THREAD

**Issue by subir0071** [actions/virtual-environments#10816]
### Breaking changes

We are going to set Nodejs 22 as the default version across all VM images.

### Target date

Image deployment is starting on November, 4 and will take 3-4 days.

### The motivation for the changes

As per the [software support](https://github.com/actions/runner-images#software-and-image-support) policy only 3 latest LTS versions of Nodejs are supported.

### Possible impact

If your builds depend on the default Nodejs 20 they can be broken.

### Platforms affected

- [X] Azure DevOps
- [X] GitHub Actions

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [X] Ubuntu 24.04
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] macOS 15
- [ ] macOS 15 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Mitigation ways

The recommended way is to pin your workflow to the desired nodejs version using:

https://github.com/actions/setup-node action for GH
https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/tool/node-js?view=azure-devops for AzDO

**Comment by TWiStErRob** [comment]
Is this still happening, just not yet?
