### ISSUE TITLE
Update/Add oc cli 3.x/4.x on Ubuntu

### ISSUE THREAD

**Issue by patricksimonian** [actions/virtual-environments#1083]
**Tool information**
- Tool name: oc
- Tool license: Apache-2.0
- Add or update? Add
- Desired version: latest version of 3 (3.11.x) and major versions of 4.x
- Approximate size: 116mb
- If this is an add request:
  - Brief description of tool: The oc cli expands on kubectl to work with Openshift clusters. It has many tools that are not available on k8s clusters. 
  - URL for tool's homepage: 
The tool can be downloaded from Redhat's mirror https://mirror.openshift.com/pub/openshift-v3/
as well as can be viewed from their [repo](https://github.com/openshift/oc)

**Area for Triage**:

**Question, Bug, or Feature?**:

**Virtual environments affected**
- [ ] macOS 10.15
- [x] Ubuntu 16.04 LTS
- [x] Ubuntu 18.04 LTS
- [x] Ubuntu 20.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Can this tool be installed during the build?**

```sh
# Source the helpers
source $HELPER_SCRIPTS/document.sh

# Install the oc CLI
curl "https://mirror.openshift.com/pub/openshift-v3/clients/3.11.232/linux/oc.tar.gz" > oc.tar.gz
tar xvzf oc.tar.gz 
rm oc.tar.gz
mv oc /usr/local/bin

# Validate the installation
echo "Validate the installation"
if ! command -v oc; then
    echo "oc was not installed"
    exit 1
fi

# Document the installed version
echo "Document the installed version"
DocumentInstalledItem "oc CLI ($(oc --version 2>&1))"
```

**Tool installation time in runtime**

From using `time`
```sh
real	0m22.244s
user	0m0.648s
sys	0m0.386s
```
**Are you willing to submit a PR?**

Yes!

**Comment by miketimofeev** [comment]
Hi @patrickcarnahan! Would you like to add this tool on Linux VM only or all images?
As far as I can see the installation size is about ~116mb(judging by the binary size), could you please update the description with it?

**Comment by patricksimonian** [comment]
updated the size @miketimofeev ! As far as what images, I don't have a strong opinion. It's not small in size so i'd see if its important to the community. My guess would be that it would only really needed to be for linux as there's no reason why you'd need to interface with an Openshift cluster from a different OS?

**Comment by miketimofeev** [comment]
@patricksimonian linux sounds reasonable, let's settle on it then. Could you please update the title to Update/Add oc cli 3.x/4.x on Ubuntu?

**Comment by patricksimonian** [comment]
What's the next steps @miketimofeev? Would you like me to offer a PR?

**Comment by miketimofeev** [comment]
@patricksimonian It'd be great if you can!

**Comment by maxim-lobanov** [comment]
@patricksimonian , could you please give us little time to evaluate this request and make decision if we would like to pre-install it to the image before preparing the pull-request? We will update the issue as soon as we have any updates here.

Also, I would like to clarify versioning strategy for this tool. You mentioned `latest version of 3 (3.11.x) and major versions of 4.x`. How many 4.x major versions are released? If it is possible, could you please share a bit more context why you would like to pre-install a few versions of this tool?

**Comment by miketimofeev** [comment]
@patrickcarnahan oc CLI is available across all Ubuntu images now. I'm going to close the issue but feel free to contact us if you have any concerns.
Thank you!
