### ISSUE TITLE
libzip package issues on Ubuntu 20.04

### ISSUE THREAD

**Issue by Technius** [actions/virtual-environments#1084]
**Describe the bug**

In Ubuntu 18.04, libzip is provided by `libzip4`. However, Ubuntu 20.04 provides libzip through `libzip5` instead (I have no idea why this decision was made, esp. given that Debian is still using `libzip4` as the package name). The libzip headers (`libzip-dev`) depends on `libzip4` instead of `libzip5`; moreoever, the version of libzip in `libzip5` is _older_ than that of `libzip4`. Programs will be linked against `libzip.so.4` instead of `libzip.so.5`, which causes errors when trying to run on real computers using Ubuntu 20.04 (https://github.com/xournalpp/xournalpp/issues/2076#issuecomment-646557586).

**Area for Triage**:
Packages

**Question, Bug, or Feature?**: 
Bug

**Virtual environments affected**
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [x] Ubuntu 20.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Expected behavior**
* `libzip-dev` should depend on `libzip5`.
* Having `libzip5` installed should cause programs using libzip to link against `libzip.so.5`.

**Actual behavior**
* `libzip-dev` depends on `libzip4`.
* `libzip4` provides libzip 1.6.1 while `libzip5` provides libzip 1.5.1.
* Programs are linked against `libzip.so.4`

Here is a build log that demonstrates the issue: https://dev.azure.com/technius/xournalpp/_build/results?buildId=384&view=logs&j=1854de8d-d1b1-5029-6b53-96b9a4903ebc&t=1165500b-598f-5895-77f8-a1d50e60a8d8

**Comment by dsame** [comment]
The ubuntu-20.04 image has only libzip4 package installed with 2 shared libraries

```
/usr/lib/x86_64-linux-gnu/libzip.so.4.0
/usr/lib/x86_64-linux-gnu/libzip.so.4
```
So there should not be any problems with libzip-dev

I reviewed the logs of the build you've pointed out and it contains installation of libzip5 (as a dependency i guess)  that causes the problem.

Please confirm i did not miss something

**Comment by Technius** [comment]
Sorry, my build log example probably caused some confusion. Here's a more relevant build log to help clarify what I mean:
https://dev.azure.com/technius/xournalpp/_build/results?buildId=383&view=logs&j=1854de8d-d1b1-5029-6b53-96b9a4903ebc&t=1165500b-598f-5895-77f8-a1d50e60a8d8

In this build, the script ran `apt remove libzip4 && apt install libzip5`. Here, we clearly see that uninstalling `libzip4` also removed `libzip-dev` (i.e. libzip4 and libzip-dev).

The main issue here is that **libzip4 does not exist in Ubuntu 20.04 repositories** ([source](https://packages.ubuntu.com/search?suite=all&searchon=names&keywords=libzip)). The fact that `libzip4` exists in the VM image indicates a possible bug. Only `libzip5` exists on Ubuntu 20.04. Furthermore, even with both `libzip4` and `libzip5` installed, trying to link with libzip (at compile time) will link with `libzip.so.4`, which is not what we want. `libzip4` should not exist, and `libzip-dev` should depend on `libzip5`.

I took a program using libzip compiled on a Ubuntu 20.04 VM image and tried to run it on a real Ubuntu 20.04 installation. This caused a dynamic linking issue:
```
xournalpp: error while loading shared libraries: libzip.so.4: cannot open shared object file: No such file or directory
```
After I patched the executable to load `libzip.so.5` instead of `libzip.so.4`, it ran successfully.

**Comment by dsame** [comment]
Hi @Technius , thank you a lot for discovering this serious issue.

Meanwhile we are preparing the fix can you please to test the workaround by adding the lines before your actual build? 

```
        sudo apt-get remove libzip-dev # it should report there's no libzip-dev installed
                                                              # so it should not break anything
        sudo apt-get install -t focal libzip5 libzip-dev # enforce ubuntu 20.04 repo to be used for
                                                                                     # libzip
```

**Comment by dsame** [comment]
I created a request to fix the php7 repo that  causes the problem https://github.com/oerdnj/deb.sury.org/issues/1417
So far i suggest to use workaround above. If the php7 repo is not fixed timely the PR #1104 should be applied

**Comment by dsame** [comment]
#1104 is merged and will be available on next deploy

**Comment by miketimofeev** [comment]
@Technius the image has been deployed. Could you please check the issue?

**Comment by Technius** [comment]
The fix seems to be working. Thanks!

**Comment by Tongzi-Zhang** [comment]
> Hi @Technius , thank you a lot for discovering this serious issue.
> 
> Meanwhile we are preparing the fix can you please to test the workaround by adding the lines before your actual build?
> 
> ```
>         sudo apt-get remove libzip-dev # it should report there's no libzip-dev installed
>                                                               # so it should not break anything
>         sudo apt-get install -t focal libzip5 libzip-dev # enforce ubuntu 20.04 repo to be used for
>                                                                                      # libzip
> ```

Thanks! The fix is working now. The answer can effectively solve the problem about "xournalpp: error while loading shared libraries: libzip.so.4: cannot open shared object file: No such file or directory". Very nice!
