### ISSUE TITLE
Severe slowdown for unit tests on macos-latest

### ISSUE THREAD

**Issue by alalazo** [actions/virtual-environments#1085]
**Describe the bug**
I'm a core developer of the open source project [Spack](https://github.com/spack/spack). We are currently using Github Actions to run our unit tests on MacOS and this used to work great. Unfortunately, since a while we experience a severe slowdown (in the order of 4-5x) on the times we were used to get and we still have to track the root cause of it. The slowdown only happens in Github Actions and cannot be reproduced on local machines. 

Can you help tracking this down and see if there's a bug on either our code or introduced by any actions/virtual-environments update?

**Area for Triage**: 

Apple Python Testing and code coverage

**Question, Bug, or Feature?**: 

Question

**Virtual environments affected**
- [x] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Ubuntu 20.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Expected behavior**
The last good run on our `develop` branch is at https://github.com/spack/spack/runs/758344523, the first run showing the slowdown (and a failure) is at  https://github.com/spack/spack/runs/760158098

It seems that between the two this update https://github.com/actions/virtual-environments/commit/c954a9f815c241711de842c7c71e2938a6d497a3#diff-e9f9822df5b3b9087dd94d4c3c083277 happened on the virtual environments and I wonder if that is taking a part on what we see. I have currently disabled a failing test in https://github.com/spack/spack/pull/17072 but the slowdown is still present.

**Actual behavior**
The current behavior is something like https://github.com/spack/spack/runs/760158098

**Comment by miketimofeev** [comment]
Hi @alalazo! Could you please provide some simple sample code affected by this slowdown apart from the whole spack project? It'd help us a lot with the investigation.
Thank you!

**Comment by alalazo** [comment]
@miketimofeev I can try to check if the slowest tests are consistent across runs and see if they share some common part in Spack. Would that be enough or still to much to analyze?

**Comment by miketimofeev** [comment]
@alalazo we'd like to test everything on our end, so it'd be great if you can provide some sample code that works much faster locally than on macOS VM now because there were no significant changes between those VM images from your builds except macOS version.

**Comment by miketimofeev** [comment]
@alalazo unfortunately, we can't do it in actions, but can test in another environment with multiple image versions, which also takes some time, if some sample code is provided. Is it enough to fork Spack repo and run some commands to push the tests?

**Comment by alalazo** [comment]
> Is it enough to fork Spack repo and run some commands to push the tests?

This is not a separate piece of code, but you can run:
```console
% git clone git@github.com:spack/spack.git
[ ... ]
% cd spack
% bin/spack test -k test_stack_view_multiple_views
============================================================= test session starts =============================================================
platform darwin -- Python 3.7.3, pytest-3.2.5, py-1.4.34, pluggy-0.4.0
rootdir: /Users/culpo/github/spack, inifile: pytest.ini
collected 2651 items                                                                                                                           

lib/spack/spack/test/cmd/env.py .

========================================================== slowest 20 test durations ==========================================================
10.95s call     lib/spack/spack/test/cmd/env.py::test_stack_view_multiple_views[mock_archive0]
0.02s setup    lib/spack/spack/test/cmd/env.py::test_stack_view_multiple_views[mock_archive0]
0.02s teardown lib/spack/spack/test/cmd/env.py::test_stack_view_multiple_views[mock_archive0]
============================================================ 2650 tests deselected ============================================================
================================================= 1 passed, 2650 deselected in 14.97 seconds =================================================
```
It takes ~15 sec. locally and in the previous virtual-environment, while it seems to be stable at ~90 sec. in the current MacOS virtual-environment. Let me know if that helps.

**Comment by miketimofeev** [comment]
@alalazo thanks! @dsame will give it a try

**Comment by Darleev** [comment]
Hello @alalazo,
I was able to reproduce the issue on the previous image version, but currently, it seems the issue is gone with new macos image release.
Could you please verify on your side?
We are looking forward to your reply.

**Comment by alalazo** [comment]
@Darleev I see that most of the runs went back to the usual ~15 mins. for unit tests, except a few ones like [this one](https://github.com/spack/spack/runs/802696354?check_suite_focus=true). Do you have any hint on what was causing the issue?

**Comment by Darleev** [comment]
@alalazo I believe this pipeline is stuck and needs to start a new one. It seems like something strange happened to the agent machine.
Could you please try to simply restart the pipeline?

**Comment by alalazo** [comment]
@Darleev Just did it.

**Comment by alalazo** [comment]
@Darleev Confirmed that it took the usual ~15 mins. after restart. I'm still puzzled by what was possibly causing the slowdown in the previous image.

**Comment by Darleev** [comment]
@alalazo We have briefly reviewed updated software, but no idea what was causing the issue.
As soon as the issue appears again, please let us know.
Since the initial issue has been resolved, I'm going to close the ticket. In case of any questions feel free to contact us
