### ISSUE TITLE
X11/Xlib.h randomly missing from environment

### ISSUE THREAD

**Issue by AndreMiras** [actions/virtual-environments#1088]
**Describe the bug**
This bug is similar to #1087 in a way it relates to environment inconsistency.
This time it's for macOS environment and the `X11/Xlib.h` header. Most of the time (95%) the header is present and things build properly. But from time to time we get the following error:
```
...(truncated)...
[DEBUG   ] building '_tkinter' extension
[DEBUG   ] clang -Qunused-arguments -fcolor-diagnostics -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall --sysroot=/Applications/Xcode_11.4.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -arch x86_64 -mmacosx-version-min=10.12 -I/Users/runner/runners/2.263.0/work/kivy-ios/kivy-ios/dist/hostlibffi/usr/local/include --sysroot=/Applications/Xcode_11.4.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -arch x86_64 -mmacosx-version-min=10.12 -I/Users/runner/runners/2.263.0/work/kivy-ios/kivy-ios/dist/hostlibffi/usr/local/include -std=c99 -Wextra -Wno-unused-result -Wno-unused-parameter -Wno-missing-field-initializers -Wstrict-prototypes -Werror=implicit-function-declaration -I/Users/runner/runners/2.263.0/work/kivy-ios/kivy-ios/build/hostpython3/x86_64/Python-3.8.2/Include/internal -DWITH_APPINIT=1 -I/System/Library/Frameworks/Tcl.framework/Headers -I/System/Library/Frameworks/Tcl.framework/Versions/Current/PrivateHeaders -I/System/Library/Frameworks/Tk.framework/Headers -I/System/Library/Frameworks/Tk.framework/Versions/Current/PrivateHeaders -I/usr/X11R6/include -I. -I/Users/runner/runners/2.263.0/work/kivy-ios/kivy-ios/dist/hostpython3/include -IObjects -IPython -I/usr/local/include -I/Users/runner/runners/2.263.0/work/kivy-ios/kivy-ios/build/hostpython3/x86_64/Python-3.8.2/Include -I/Users/runner/runners/2.263.0/work/kivy-ios/kivy-ios/build/hostpython3/x86_64/Python-3.8.2/native-build -c /Users/runner/runners/2.263.0/work/kivy-ios/kivy-ios/build/hostpython3/x86_64/Python-3.8.2/Modules/_tkinter.c -o build/temp.macosx-10.15-x86_64-3.8/Users/runner/runners/2.263.0/work/kivy-ios/kivy-ios/build/hostpython3/x86_64/Python-3.8.2/Modules/_tkinter.o -framework Tk
[DEBUG   ] In file included from /Users/runner/runners/2.263.0/work/kivy-ios/kivy-ios/build/hostpython3/x86_64/Python-3.8.2/Modules/_tkinter.c:48:
[DEBUG   ] /Applications/Xcode_11.4.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/tk.h:86:11: fatal error: 
[DEBUG   ]       'X11/Xlib.h' file not found
[DEBUG   ] #       include <X11/Xlib.h>
[DEBUG   ]                 ^~~~~~~~~~~~
[DEBUG   ] 1 error generated.
[DEBUG   ] 
[DEBUG   ] Python build finished successfully!
[DEBUG   ] The necessary bits to build these optional modules were not found:
[DEBUG   ] ossaudiodev           spwd                                     
[DEBUG   ] To find the necessary bits, look in setup.py in detect_modules() for the module's name.
[DEBUG   ] 
[DEBUG   ] 
[DEBUG   ] The following modules found by detect_modules() in setup.py, have been
...(truncated)...
```
https://github.com/kivy/kivy-ios/runs/718264436?check_suite_focus=true

**Area for Triage**: 

**Question, Bug, or Feature?**: 
Bug

**Virtual environments affected**
- [x] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Ubuntu 20.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Expected behavior**
We would except the header is either never there or always there, but it should be consistent.

**Actual behavior**
Sometimes the header is there, sometimes not.
https://github.com/kivy/kivy-ios/runs/718264436?check_suite_focus=true

**Comment by andy-mishechkin** [comment]
Hello, @AndreMiras !
We have found the similar situation here: https://github.com/pinax/pinax-project-teams/issues/1
I have forked your repository and add link creation:
```
- name: Build Python & Kivy
      run: |
        ln -s /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/Tk.framework/Versions/8.5/Headers/X11/ /usr/local/include/X11
        python toolchain.py build python3 kivy
```
Build has been successful and has no any errors:
https://github.com/andy-mishechkin/kivy-ios/runs/807405836?check_suite_focus=true
May you add this link creation to you workflow and to test it ?
Thank you.

**Comment by AndreMiras** [comment]
Thanks for the follow up @andy-mishechkin 
Yes we can definitely add that, actually we could just pull request from your fork (if we remove the `echo $PATH` debugging) https://github.com/kivy/kivy-ios/compare/master...andy-mishechkin:master
But won't that feel like a workaround for the original issue?

**Comment by andy-mishechkin** [comment]
Hello, @AndreMiras.
We have the same images in all your workflows, and I see that you have this error in successful build:
https://github.com/kivy/kivy-ios/runs/815842435?check_suite_focus=true :
![image](https://user-images.githubusercontent.com/57713077/85988940-d7b5be80-ba00-11ea-8b29-0de8acb92b58.png)

**Comment by andy-mishechkin** [comment]
Hello @AndreMiras 
Have you had a chance to test this approach in your workflow ?
May you inform us, please, if your issue was fixed.
Thank you.

**Comment by AndreMiras** [comment]
Thanks for investigating into it @andy-mishechkin 
I got a bit busy lately and I will until end of next week, but I will definitely try to look into it after that.
It's on my todo list and I'll keep you updated with it. Thanks a mil :+1:

**Comment by MaksimZhukov** [comment]
Hello @AndreMiras !
Did you have a chance to test the proposed fix? Do you have any updates? 
We are looking forward to your reply! Thanks

**Comment by MaksimZhukov** [comment]
I am closing this issue. Feel free to reopen if you have any questions
