### ISSUE TITLE
Regression: Postgres installation on windows-latest breaks MinGW

### ISSUE THREAD

**Issue by kentonv** [actions/virtual-environments#1089]
**Describe the bug**

This is a recent regression, probably due to #636.

When compiling C++ code using the MinGW install already on the machine, `#include <pthread.h>` finds a header located in Postgress's install directory, specifically:

    C:/PROGRA~1/POSTGR~1/12/include/pthread.h

This header is not the one MinGW is intending to find.

Note that `pthread.h` is included indirectly from various standard headers. For example, `#include <map>` produces this include stack:

```
C:/ProgramData/chocolatey/lib/mingw/tools/install/mingw64/lib/gcc/x86_64-w64-mingw32/8.1.0/include/c++/map:61
C:/ProgramData/chocolatey/lib/mingw/tools/install/mingw64/lib/gcc/x86_64-w64-mingw32/8.1.0/include/c++/bits/stl_map.h:63
C:/ProgramData/chocolatey/lib/mingw/tools/install/mingw64/lib/gcc/x86_64-w64-mingw32/8.1.0/include/c++/tuple:39
C:/ProgramData/chocolatey/lib/mingw/tools/install/mingw64/lib/gcc/x86_64-w64-mingw32/8.1.0/include/c++/array:39
C:/ProgramData/chocolatey/lib/mingw/tools/install/mingw64/lib/gcc/x86_64-w64-mingw32/8.1.0/include/c++/stdexcept:39
C:/ProgramData/chocolatey/lib/mingw/tools/install/mingw64/lib/gcc/x86_64-w64-mingw32/8.1.0/include/c++/string:52
C:/ProgramData/chocolatey/lib/mingw/tools/install/mingw64/lib/gcc/x86_64-w64-mingw32/8.1.0/include/c++/bits/basic_string.h:39
C:/ProgramData/chocolatey/lib/mingw/tools/install/mingw64/lib/gcc/x86_64-w64-mingw32/8.1.0/include/c++/ext/atomicity.h:35
C:/ProgramData/chocolatey/lib/mingw/tools/install/mingw64/lib/gcc/x86_64-w64-mingw32/8.1.0/include/c++/x86_64-w64-mingw32/bits/gthr.h:148
C:/ProgramData/chocolatey/lib/mingw/tools/install/mingw64/lib/gcc/x86_64-w64-mingw32/8.1.0/include/c++/x86_64-w64-mingw32/bits/gthr-default.h:35
C:/PROGRA~1/POSTGR~1/12/include/pthread.h
```

So this affects a lot of C++ code.

The Postgres version of `pthread.h` transitively includes `windows.h`, which breaks my code due to all the `#define`s it brings in. I'm not sure if this `pthread.h` is otherwise ABI-compatible with MinGW's since I never got to the point of linking or running my program... but chances are it is not compatible.

To fix this problem, either the Postgres install's header files need to be removed from the global include path by default, or the Postgres installation needs to be pruned so that it doesn't shadow system headers like `pthread.h`.

**Area for Triage**: 
C/C++

**Question, Bug, or Feature?**: 
Bug

**Virtual environments affected**
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Ubuntu 20.04 LTS
- [ ] Windows Server 2016 R2
- [x] Windows Server 2019

**Comment by kentonv** [comment]
I was able to work around this by simply deleting the Postgres install using `rmdir /s /q C:\PROGRA~1\POSTGR~1`. See: https://github.com/capnproto/capnproto/pull/1018/commits/2c1b6bb3453e49ddc43f8517f8439c76a4b772f6

**Comment by Darleev** [comment]
Hello @kentonv,
We are working on the issue. I have prepared a [pull request](https://github.com/actions/virtual-environments/pull/1099) to fix the issue. I will verify it and let you know about the results.

**Comment by Darleev** [comment]
Hello @kentonv,
The fix has been merged and will be available after the next image rollout. I will keep you informed.

**Comment by Darleev** [comment]
Hello @kentonv,
PostgreSQL has been removed from PATH at this time, and currently available only through environment variables. So, the issue should not be actual anymore.
Please let us know in case of any questions.
