### ISSUE TITLE
.net 8.0.404 is not installed on all agents

### ISSUE THREAD

**Issue by ghost** [actions/virtual-environments#10986]
### Description

Description
Some of the agents we get from azure devops when running windows-latest does not have .net 8.0.404

So Image [20241113.3.1](https://github.com/actions/runner-images/blob/main/images/windows/Windows2022-Readme.md) is not deployed to all agents yet, normal you only updated the wiki page after all agents are rolled updated

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] macOS 15
- [ ] macOS 15 Arm64
- [ ] Windows Server 2019
- [x] Windows Server 2022

### Image version and build link

Azure devops
Runner Image Provisioner
2.0.384.1
Current image version: '20241113.3.0'

### Is it regression?

20241113.3.0

### Expected behavior

I expect that all agent run the version on the wiki page or a new version.

### Actual behavior

We get the version list on the wiki page or older versions

### Repro steps

Create a pipeline that need .net 8.0.404
Run it until you get an agent with version '20241113.3.0'

**Comment by Prabhatkumar59** [comment]
Hi @HNBEnerginet -Thank you for bringing this issue to our attention. We will look into this issue and will update you after investigating.

**Comment by twofingerrightclick** [comment]
Yes, had this issue as well with a pipeline that uses the "latest windows agent". Even though [the image that was grabbed says version 8.0.404 is pre-installed](https://github.com/actions/runner-images/blob/win22/20241113.3/images/windows/Windows2022-Readme.md#net-core-tools), we had to add the task for making sure it was there to allow us to install the correct workloads for our project with `dotnet workload install`, as `dotnet install` install was installing version 7 packages, even though our global.json specifies to use the latest version 8. 
``` yaml
  - task: UseDotNet@2
    inputs:
      version: "8.x"
```

**Comment by vidyasagarnimmagaddi** [comment]
Hi @HNBEnerginet  , the new image `20241125.1` is rolled out fully on all agents. thanks closing this issue.
