### ISSUE TITLE
Installed Boost unsupported by installed CMake

### ISSUE THREAD

**Issue by Flamefire** [actions/virtual-environments#110]
**Describe the bug**
Boost 1.69 support was added to CMake 3.13, however CMake 3.12 is installed. Hence it is not usable.

**Virtual environments affected**
- [ ] macOS 10.15
- [x] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Expected behavior**
Configuring a Project with CMake using Boost should work out of the box

**Actual behavior**
Error is issued:
```
CMake Warning at /usr/local/share/cmake-3.12/Modules/FindBoost.cmake:847 (message):
  New Boost version may have incorrect or missing dependencies and imported
  targets
```

**Comment by stevencpp** [comment]
Related issue: #56

**Comment by erenon** [comment]
A possible workaround is to specify Boost_ADDITIONAL_VERSIONS:

    cmake -DBoost_ADDITIONAL_VERSIONS=1.69.0 ..

However, it does not help until #83 is fixed (boost is not installed)

**Comment by Flamefire** [comment]
Ah yes, I forgot the above was downgraded to a warning.

**Comment by traversaro** [comment]
Related issue: https://github.com/actions/virtual-environments/issues/10 . It is worth to note that CMake is not the only tool that need to be compatible with the Boost version installed, and also other packages can be broken if the wrong Boost version is used. My personal opinion is that it is great to have a recent version of Boost installed, but its use should be opt-in rather then opt-out, so the official CMake variable `BOOST_ROOT` should not be set by default.

**Comment by erenon** [comment]
I was unable to use CMake with Boost out of the box, due to cmake does not recognize architecture (x64) decorated library names. See: https://gitlab.kitware.com/cmake/cmake/issues/17701
My workaround is:

```
cd $BOOST_ROOT_1_69_0/lib/
sudo ln -s libboost_filesystem-mt-x64.so libboost_filesystem.so
sudo ln -s libboost_unit_test_framework-mt-x64.so libboost_unit_test_framework.so
sudo ln -s libboost_system-mt-x64.so libboost_system.so
cmake -DBOOST_ROOT=$BOOST_ROOT_1_69_0 -DBoost_ADDITIONAL_VERSIONS=1.69.0 ..
```

**Comment by Flamefire** [comment]
@erenon The correct way would be to `-DBoost_ARCHITECTURE=-x64 `

**Comment by erenon** [comment]
@Flamefire : It would be, but `Boost_ARCHITECTURE` was introduced in CMake 3.13, while the GitHub installed CMake on Ubuntu 18.04 is only 3.12.4.

**Comment by zbeekman** [comment]
Isn't this fixed now? It [looks like CMake was bumped to 3.16.2](https://github.com/actions/virtual-environments/commit/f24342d31b78289d03aa400d5a01a8b425578691)

**Comment by mathbagu** [comment]
My pipeline is not able to find boost libraries.

First, I checked that the libraries are installed in BOOST_ROOT_1_69_0/lib:
```
**Run ls -l $BOOST_ROOT_1_69_0/lib/
total 971760
-rw-r--r-- 1 root root    29970 Jan 10 10:05 libboost_atomic-mt-d-x64.a
-rwxr-xr-x 1 root root    23576 Jan 10 10:15 libboost_atomic-mt-d-x64.so
-rwxr-xr-x 1 root root    23576 Jan 10 10:15 libboost_atomic-mt-d-x64.so.1.69.0
-rw-r--r-- 1 root root     2602 Jan 10 09:40 libboost_atomic-mt-s-x64.a
-rw-r--r-- 1 root root    29970 Jan 10 10:04 libboost_atomic-mt-sd-x64.a
-rw-r--r-- 1 root root     2602 Jan 10 09:42 libboost_atomic-mt-x64.a
-rwxr-xr-x 1 root root     7944 Jan 10 09:54 libboost_atomic-mt-x64.so
-rwxr-xr-x 1 root root     7944 Jan 10 09:54 libboost_atomic-mt-x64.so.1.69.0
```

There are two suffixes: one for the multi-thread and one for the architecture. So I tried to pass everything to the command line:
```
cmake $GITHUB_WORKSPACE
  -DCMAKE_BUILD_TYPE=Release
  -DCMAKE_CXX_CLANG_TIDY=clang-tidy
  -DCMAKE_CXX_COMPILER=clang++
  -DBOOST_ROOT=$BOOST_ROOT_1_69_0
  -DBoost_ADDITIONAL_VERSIONS=1.69.0
  -DBoost_ARCHITECTURE=-x64
  -DBoost_USE_MULTITHREADED=ON
  ....
CMake Error at /usr/local/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:146 (message):
  Could NOT find Boost (missing: date_time filesystem program_options system
  unit_test_framework) (found suitable version "1.69.0", minimum required is
  "1.56")
Call Stack (most recent call first):
  /usr/local/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:393 (_FPHSA_FAILURE_MESSAGE)
  /usr/local/share/cmake-3.16/Modules/FindBoost.cmake:2179 (find_package_handle_standard_args)
  CMakeLists.txt:26 (find_package)


CMake Warning (dev) in /usr/local/share/cmake-3.16/Modules/FindBoost.cmake:
  Policy CMP0011 is not set: Included scripts do automatic cmake_policy PUSH
  and POP.  Run "cmake --help-policy CMP0011" for policy details.  Use the
  cmake_policy command to set the policy and suppress this warning.

  The included script

    /usr/local/share/cmake-3.16/Modules/FindBoost.cmake

  affects policy settings.  CMake is implying the NO_POLICY_SCOPE option for
  compatibility, so the effects are applied to the including context.
```

It seems the headers are found (thanks to the definition of the BOOST_ROOT variable), but impossible to find the libraries.

Do I miss something?

**Comment by erenon** [comment]
@mathbagu : Set `-DBoost_DEBUG=ON` to see what paths are tried.

**Comment by mathbagu** [comment]
In fact, it seems these properties (Boost_DEBUG and Boost_ARCHITECTURE) could not be set using the command line... it works only if I set the value in the CMakeLists.txt.
