### ISSUE TITLE
Hosted Macs: upgrade Carthage to version 0.35

### ISSUE THREAD

**Issue by BenjaminBhuyanYoung** [actions/virtual-environments#1100]
Please update Carthage on the hosted mac agents to the latest version, 0.35.  The version now on hosted macs is 0.34 which has a bug in which binary packages must be built on the same version of Swift as XCode uses.  The new version fixes this and without it we cannot build our project at all using hosted macs.

**Comment by vmapetr** [comment]
Hi @BenjaminBhuyanYoung !

We install latest available version of Carthage from Brew, but unfortunately our current macOS images were generated and deployed several days before the Carthage version was bumped. 
Carthage 0.35.0 will be delivered during the next image rollout, approximately in 1 week, but you can use following workaround to avoid waiting:
```
- run: brew update && brew upgrade carthage
```

**Comment by maxim-lobanov** [comment]
Hello, image deployment has finished. Carthage 0.35.0 is [available on latest image](https://github.com/actions/virtual-environments/blob/master/images/macos/macos-10.15-Readme.md#package-management).

**Comment by BenjaminBhuyanYoung** [comment]
> Hello, image deployment has finished. Carthage 0.35.0 is [available on latest image](https://github.com/actions/virtual-environments/blob/master/images/macos/macos-10.15-Readme.md#package-management).

Thank you!
