### ISSUE TITLE
Reduced space on builder

### ISSUE THREAD

**Issue by compnerd** [actions/virtual-environments#1101]
**Describe the bug**
The last round of updates seems to have reduced the available space for builders enough for larger builds to start failing due to out of space errors.

**Area for Triage**: 
Containers

**Question, Bug, or Feature?**: 
Bug

**Virtual environments affected**
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Ubuntu 20.04 LTS
- [ ] Windows Server 2016 R2
- [X] Windows Server 2019

**Expected behavior**
Builder to have enough space for builds.

**Actual behavior**
Large builds result in out of space errors.

**Comment by miketimofeev** [comment]
Hi @compnerd! Could you please provide some details of your build? What disks are being used? As far as I can see there is plenty of space on both drives:
![image](https://user-images.githubusercontent.com/48208649/85370135-f0246580-b536-11ea-9ed1-3eec2b5246ef.png)
According to the https://help.github.com/en/actions/reference/virtual-environments-for-github-hosted-runners each machine has 14 GB of SSD disk space, which is disk D and 1.8 Gb are used for swapfile(can be disabled if needed)

**Comment by compnerd** [comment]
I should have mentioned, it’s the azure builder, not GitHub hosted.  Are the images identical?

I imagine that it’s D drive that’s getting used (default build location).  How can the swap file be disabled?

**Comment by compnerd** [comment]
Yeah, verified that it is the D drive.  I suspect it could be a combined issue of large repositories and builds.  As it is, the space constricts debug info.

**Comment by miketimofeev** [comment]
@compnerd yes, the image is the same. 
You can use the script from this action to change the swap in the runtime
https://github.com/al-cheb/configure-pagefile-action/blob/master/scripts/SetPageFileSize.ps1

**Comment by miketimofeev** [comment]
@compnerd I'm afraid I was mistaken and the swap can only be increased during runtime. Is it possible to use disk C:\ for your build in that case?

**Comment by compnerd** [comment]
I love that idea @miketimofeev!  I will try to figure out how to do that on Azure, but if you have any tips for setting up the `Build.*` variables appropriately, I'd be extremely grateful.

**Comment by miketimofeev** [comment]
@compnerd yes, it can be done quite simple.
For instance, if you'd like to change `Build.ArtifactStagingDirectory` from the default `d:\a\1\a` to `c:\a` you can use the following PowerShell script
```
$NewBuildDir = "C:\a"
New-Item -Type Directory $NewBuildDir -Force
# Change build dir for the current step
$env:BUILD_STAGINGDIRECTORY = $NewBuildDir
# Change build dir for all the next steps
Write-Host "##vso[task.setvariable variable=BUILD_STAGINGDIRECTORY;]$NewBuildDir"
```
Another suggestion is to limit fetching to the specified number of commits if your repository is huge enough. To do that you can set `Shallow fetch` to 1:
![image](https://user-images.githubusercontent.com/48208649/85700942-8d250100-b6e5-11ea-92eb-fca3f593fe9f.png)

**Comment by miketimofeev** [comment]
@compnerd has it helped? We're looking forward to your answer.

**Comment by compnerd** [comment]
Managed to figure out how to do the shallow clones in YAML:

```yaml
fetchDepth: [depth]
```

on the `checkout` task.

Should find out in ~8 hours (yes, the pipeline takes a really long time :-().

**Comment by compnerd** [comment]
Seems that the `fetchDepth` almost works.  Im seeing a failure on one of the builders, but I think that a one time cleanup might help with that.  I'll report back once it gets further :)

**Comment by compnerd** [comment]
Okay, I think that I can get away with the fetch depth for now.  Thanks for all the info for this :)
