### ISSUE TITLE
Is this supposed to build in Azure Devops?

### ISSUE THREAD

**Issue by gregpakes** [actions/virtual-environments#1105]
**Describe the bug**
Is this packer image supposed to be buildable using Azure Pipelines?  The reason I ask is that when I try, I get the following error after 6 hours:

> We stopped hearing from agent Hosted Agent. Verify the agent machine is running and has a healthy network connection. Anything that terminates an agent process, starves it for CPU, or blocks its network access can cause this error. For more information, see: https://go.microsoft.com/fwlink/?linkid=846610 

I realise this is not really an issue with this repo, but I just wanted to ask if that was a valid usecase?

I have opened the following issue with Azure Devops: https://developercommunity.visualstudio.com/content/problem/1089829/unable-to-build-packer-image-for-azure-devops-agen.html

**Question, Bug, or Feature?**: 
Question

**Virtual environments affected**
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Ubuntu 20.04 LTS
- [ ] Windows Server 2016 R2
- [X] Windows Server 2019

**Expected behavior**
If these images are supposed to be built with Azure Pipelines, then there should be working guidance.

**Comment by gregpakes** [comment]
I suspect this issue is due to the 360 minute timeout on the hosted agents.

**Comment by maxim-lobanov** [comment]
@gregpakes , I don't think it is supposed to build our images inside Azure DevOps.
We build our images on self-hosted machines where there is no any job time limitation.

Probably, it is possible to build Ubuntu images inside Azure DevOps since build time is ~3 hours but as for the Windows ones, build takes ~10 hours. Hosted machines can't be extended to run build more than 6 hours.

**Comment by gregpakes** [comment]
Thanks for the info.  I hope someone at Microsoft can see the issue with that.

You need to run a completely separate private agent in order to be able to build the image for your main private agents.....

Seems bizarre to me.

I know it’s not the fault of this repo....

**Comment by miketimofeev** [comment]
@gregpakes @maxim-lobanov actually sometimes it can be built below 6 hours, but not so often.
![image](https://user-images.githubusercontent.com/48208649/85515093-68f1f300-b605-11ea-9568-6ca22ec0d6e1.png)
As a possible solution VM size can be changed in the template to something with more cores\ram to speed up the process
https://github.com/actions/virtual-environments/blob/98df997b11fa85a5d823084aae80d40482c1583e/images/win/Windows2019-Azure.json#L17

**Comment by gregpakes** [comment]
Thanks for the input.  I guess I have no choice but to run a separate private agent with Packer on it.
