### ISSUE TITLE
Google Chrome failing to install with error - Installation process returned unexpected exit code: 1603 on Windows builds

### ISSUE THREAD

**Issue by angaaruriakhil** [actions/virtual-environments#11095]
### Description

Running Windows builds today fails on google chrome installation via script https://github.com/actions/runner-images/blob/main/images/windows/scripts/build/Install-Chrome.ps1 with error: 

```
==> azure-arm.build_vhd: Provisioning with powershell script: /agent/_work/1/s/runner-images/images/windows/scripts/build/Install-Chrome.ps1
    azure-arm.build_vhd: Downloading package from https://dl.google.com/tag/s/dl/chrome/install/googlechromestandaloneenterprise64.msi to C:\Users\packer\AppData\Local\Temp\googlechromestandaloneenterprise64.msi...
    azure-arm.build_vhd: Package downloaded in 4.17 seconds
    azure-arm.build_vhd: Signature for C:\Users\packer\AppData\Local\Temp\googlechromestandaloneenterprise64.msi is valid
    azure-arm.build_vhd: No arguments provided for MSI binary. Using default arguments: /i, /qn, /norestart
    azure-arm.build_vhd: Starting Install ...
    azure-arm.build_vhd: Installation process returned unexpected exit code: 1603
```

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] macOS 15
- [ ] macOS 15 Arm64
- [X] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

Self hosted VMSS

### Is it regression?

Yes

### Expected behavior

Binary should be installed

### Actual behavior

Installation process returned unexpected exit code: 1603

```
==> azure-arm.build_vhd: Provisioning with powershell script: /agent/_work/1/s/runner-images/images/windows/scripts/build/Install-Chrome.ps1
    azure-arm.build_vhd: Downloading package from https://dl.google.com/tag/s/dl/chrome/install/googlechromestandaloneenterprise64.msi to C:\Users\packer\AppData\Local\Temp\googlechromestandaloneenterprise64.msi...
    azure-arm.build_vhd: Package downloaded in 4.17 seconds
    azure-arm.build_vhd: Signature for C:\Users\packer\AppData\Local\Temp\googlechromestandaloneenterprise64.msi is valid
    azure-arm.build_vhd: No arguments provided for MSI binary. Using default arguments: /i, /qn, /norestart
    azure-arm.build_vhd: Starting Install ...
    azure-arm.build_vhd: Installation process returned unexpected exit code: 1603
```

### Repro steps

Clone down runner-images repo and attempt to build either Windows 2019 or Windows 2022 image with Hashicorp Packer

**Comment by Reterino** [comment]
I can confirm this is happening to my builds as well.

The same installer and script to run it works perfectly fine on a fresh VM, but something in the config up to this point causes the issue.

**Comment by hemanthmanga** [comment]
Hi @angaaruriakhil, Thank you for bringing this issue to our attention. We are looking into this issue and will update you on this issue after investigating.

**Comment by McAdamz** [comment]
> I can confirm this is happening to my builds as well.
> 
> The same installer and script to run it works perfectly fine on a fresh VM, but something in the config up to this point causes the issue.

This is the same behaviour I'm experiencing too, self hosted VMSS.

**Comment by fcsbarry** [comment]
Same for us. To add, I logged into the VM afterward and was able to manually run the .msi successfully. Chrome was installed and opened without errors.

**Comment by dd-eg** [comment]
If anyone needs an immediate fix, there is a workaround described in [a comment on that Chromium issue](https://issues.chromium.org/issues/382108340#comment17): you can change the URL in Install-Chrome.ps1 to one that injects tag data into the signing certificate.

**Comment by McAdamz** [comment]
> Chromium team has fixed the issue with chrome msi package and our Windows images are building successfully. Please check at your end and let us know for the closure of this issue. Thanks.

I can confirm this is now working again in my scenario.

**Comment by xianlin** [comment]
the same issue happened again, does anyone have the same issue?

```
==> windows-2022.azure-arm.image: Provisioning with powershell script: runner-images/images/windows/templates/../scripts/build/Install-Chrome.ps1
    windows-2022.azure-arm.image: Downloading package from https://dl.google.com/tag/s/dl/chrome/install/googlechromestandaloneenterprise64.msi to D:\temp\googlechromestandaloneenterprise64.msi...
    windows-2022.azure-arm.image: Package downloaded in 1.03 seconds
    windows-2022.azure-arm.image: Signature for D:\temp\googlechromestandaloneenterprise64.msi is valid
    windows-2022.azure-arm.image: No arguments provided for MSI binary. Using default arguments: /i, /qn, /norestart
    windows-2022.azure-arm.image: Starting Install ...
    windows-2022.azure-arm.image: Installation process returned unexpected exit code: 1603
```
