### ISSUE TITLE
Doc bug: NetCore 2.2 is removed but Windows2019-Readme.md still lists it.

### ISSUE THREAD

**Issue by dannyvv** [actions/virtual-environments#1113]
**Describe the bug**
PR #1017 Removes NetCore 2.2, but the documentation [Windows2019-Readme.md](https://github.com/actions/virtual-environments/blob/master/images/win/Windows2019-Readme.md) Still lists 2.2.x versions in the [.NET Core Runtime](https://github.com/actions/virtual-environments/blob/master/images/win/Windows2019-Readme.md#net-core-runtime) section.

**Area for Triage**: 
.NET Core

**Question, Bug, or Feature?**: 
Bug

**Virtual environments affected**
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Ubuntu 20.04 LTS
- [ ] Windows Server 2016 R2
- [X] Windows Server 2019

**Comment by miketimofeev** [comment]
Hi @dannyvv!
It takes 4-5 days to propagate the new image to all the environments. We're going to finish win19 deployment in 2 next days. Release notes for the new image are available here:
https://github.com/actions/virtual-environments/releases/tag/win19%2F20200621.1
I'm going to close the issue, but feel free to contact us if you have any concerns.
Thank you!
