### ISSUE TITLE
Add soundcore and snd-aloop kernel modules 

### ISSUE THREAD

**Issue by Shamazo** [actions/virtual-environments#1114]
**Tool information**
- Tool name: Linux kernel modules `snd-aloop` and `soundcore`
- Add or update? Add
- Desired version: whatever is latest / easiest to install
- Approximate size: 
- If this is an add request:
  - Brief description of tool: These modules are necessary to create virtual/dummy soundcards for applications which require a sound card. If I am incorrect in this assessment please let me know / direct me to resources on how to create a virtual sound card without these modules. 
  - URL for tool's homepage: [https://alsa-project.org/wiki/Main_Page](https://alsa-project.org/wiki/Main_Page)

**Area for Triage**:
Servers

**Question, Bug, or Feature?**:
Feature

**Virtual environments affected**
- [ ] macOS 10.15
- [x] Ubuntu 16.04 LTS
- [x] Ubuntu 18.04 LTS
- [x] Ubuntu 20.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Can this tool be installed during the build?**
NA: modprobe is unable to find these modules. It may be possible to build the modules and load them without rebooting, but it seems non-trivial. 

**Tool installation time in runtime**
NA. 

**Are you willing to submit a PR?**
If I had the technical know how I would, but unfortunately I do not.

**Comment by Darleev** [comment]
Hello @Shamazo 
I have found a solution( [link ](https://stackoverflow.com/questions/40061291/linux-without-hardware-soundcard-capture-audio-playback-and-record-it-to-fil)) for Ubuntu which possibly can resolve the issue you have reported. Could you please try it?
Also, it would be great to have more details about this problem( language, libraries, error message, etc. ).

We are looking forward to your reply.

**Comment by Shamazo** [comment]
Thank you for that link, it is very useful to know pulseaudio can emulate alsa. That solution did work. 

I am working on a cross platform consumer application written in c99. The application, on linux, uses x11 for display/gui interactions and asoundlib for audio playback. Unfortunately, it is closed source so I cannot share the code itself. 

The snippet to create the audio device which fails because there is no device (without linked solution):
```
audio_device_t *audio_device = malloc(sizeof(audio_device_t));
memset(audio_device, 0, sizeof(audio_device_t));
int res;
res = snd_pcm_open(&audio_device->handle, "default", SND_PCM_STREAM_CAPTURE,   0);
```


The errors:
```
ALSA lib confmisc.c:767:(parse_card) cannot find card '0'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1246:(snd_func_refer) error evaluating name
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM default
```


Thank you again for your help. I'll leave the issue open for now, but feel free to close it.

**Comment by dmitry-shibanov** [comment]
Thank you for your response, we're closing the issue, if you have any concerns feel free to reopen the issue.
