### ISSUE TITLE
Support of ARM64 does not work for UWP apps in a GitHub Actions

### ISSUE THREAD

**Issue by ArchieCoder** [actions/virtual-environments#1115]
**Describe the bug**
The native .NET compiler tool nutc_driver.exe exits with a strange error that does not say the cause: 
C:\Program Files (x86)\Microsoft SDKs\UWPNuGetPackages\microsoft.net.native.compiler\2.2.8-rel-28605-00\tools\Microsoft.NetNative.targets(801,5): error : ILT0005: 'C:\Program Files (x86)\Microsoft SDKs\UWPNuGetPackages\runtime.win10-arm64.microsoft.net.native.compiler\2.2.8-rel-28605-00\tools\ARM64\ilc\Tools64\nutc_driver.exe @"D:\a\MY_PROJECT\obj\ARM64\Release\ilc\intermediate\MDIL\MyApp.App.rsp"' returned exit code 1 

**Area for Triage**: 

**Question, Bug, or Feature?**: 
Bug

**Virtual environments affected**
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Ubuntu 20.04 LTS
- [ ] Windows Server 2016 R2
- [X] Windows Server 2019

**Expected behavior**
No error especially from an internal tool. I suspect it is an out of memory.

**Actual behavior**
Our repo is private. However, the build step is quite simple:
- name: Build the sideload solution
      run: msbuild $env:Solution_Path /p:Platform=ARM64 /p:AppxBundle=$env:AppxBundle /p:AppxBundlePlatforms="ARM64" /p:AppxPackageDir=C:\DeployOutput /p:PackageCertificateKeyFile=$env:SigningCertificate /restore
      env:
        AppxBundle: Always
        BuildMode: StoreUpload
        Configuration: Release

**Comment by Darleev** [comment]
Hello @ArchieCoder,
Thank you for the issue reported.

Did you try to build you code locally? Is it successful?
Do you have a chance to provide us sample repo with minimal steps to reproduce the issue?

**Comment by ArchieCoder** [comment]
@Darleev Thanks for the fast follow-up.

On a regular Dev Command Line prompt, it works locally. It takes so long, but it works. I can see the memory going up to 6.1 GB for the .net tooling.

![image](https://user-images.githubusercontent.com/1608424/85627584-b89fe100-b63c-11ea-91c0-b65d72357312.png)

Would there be a way that you could put some sort of diagnostics? I would not be surprised that it would actually work on a blank solution. It takes so much time to create a full repro.

**Comment by dsame** [comment]
The ARM build confirmed to success https://github.com/akv-platform/ConsoleApplication1ARM/runs/810854812?check_suite_focus=true so we need a specific project to investigate the problem. 

@ArchieCoder 
Is not it possible to imitate the problem with the sample project?
Do you use msbuild or visual studio workflow?
Are you aware about the ways to increase the verbosity of the build? 
Have you investigated the content of `logs` directory in case if you use CMake ?

**Comment by ArchieCoder** [comment]
@Darleev @dsame I have good news! I have a repro. Last night, I created the same solution without ANY cs/xaml files, but just the minimum like icon assets, App.xaml.cs and empty Main.xaml.

1- I started the process to build the ARM64 package only -> it works. I was sad.
2- Before giving up, I said let's add the x64 package also -> The solution didn't build with the same error that I got in my real solution.

Repo: https://github.com/ArchieCoder/GTA
Compilation
Workflow (line 54): https://github.com/ArchieCoder/GTA/blob/master/.github/workflows/storebuilder.yml

In order to trigger the workflow, create and push a tag with the form 1.1.1.3

Thank you and good luck

**Comment by dsame** [comment]
@ArchieCoder the build fails with 
```
 Get tag0s
    DeployPath: DeployOutput
Run dawidd6/action-get-tag@v1
  env:
    SigningCertificate: Sherpany.App_TemporaryKey.pfx
    Solution_Path: EG.Sherpany.Boardroom\Sherpany.sln
    UWP_Project_Path: EG.Sherpany.Boardroom\EG.Sherpany.Boardroom.W10\Sherpany.App.csproj
    UWP_Project_Directory: EG.Sherpany.Boardroom\EG.Sherpany.Boardroom.W10
    DeployPath: DeployOutput
##[error]Not a tag ref (refs/heads/master)
```
https://github.com/dsame/GTA/runs/830788995?check_suite_focus=true

I tried to remove this task but the build failed with 
```
"D:\a\GTA\GTA\EG.Sherpany.Boardroom\Sherpany.sln" (default target) (1:2) ->
"D:\a\GTA\GTA\EG.Sherpany.Boardroom\EG.Sherpany.Boardroom.W10\Sherpany.App.csproj" (default target) (4:6) ->
(_ValidateAppxManifest target) -> 
  D:\a\GTA\GTA\EG.Sherpany.Boardroom\EG.Sherpany.Boardroom.W10\bin\ARM64\Release\AppxManifest.xml : error APPX0501: Validation error. error C00CE169: App manifest validation error: The app manifest must be valid as per schema: Line 10, Column 74, Reason: '' violates minLength constraint of '1'. The attribute 'Version' with value '' failed to parse. 
```
https://github.com/dsame/GTA/runs/829589327?check_suite_focus=true

**Comment by ArchieCoder** [comment]
@dsame you need to create a tag on the form x.y.z.u like 1.1.1.5

**Comment by dsame** [comment]
@ArchieCoder 
So did it https://github.com/dsame/GTA/tree/1.1.1.5

Is it absolutely impossible to have a sample build that just works?

**Comment by dsame** [comment]
The intermediate result: the problem is not alway reproducible:

1.  there's clear OutOfMemory exception
https://github.com/ArchieCoder/GTA/runs/844182819?check_suite_focus=true 

```
2020-07-07T04:49:56.3214127Z   Launching 'C:\Program Files (x86)\Microsoft SDKs\UWPNuGetPackages\runtime.win10-arm64.microsoft.net.native.compiler\2.2.8-rel-28605-00\tools\ARM64\ilc\Tools64\nutc_driver.exe @"D:\a\GTA\GTA\EG.Sherpany.Boardroom\EG.Sherpany.Boardroom.W10\obj\ARM64\Release\ilc\intermediate\MDIL\Sherpany.App.rsp"'
2020-07-07T05:03:49.4410821Z C:\Program Files (x86)\Microsoft SDKs\UWPNuGetPackages\microsoft.net.native.compiler\2.2.8-rel-28605-00\tools\Microsoft.NetNative.targets(801,5): error : Unhandled Exception: OutOfMemoryException. [D:\a\GTA\GTA\EG.Sherpany.Boardroom\EG.Sherpany.Boardroom.W10\Sherpany.App.csproj]
```

2. there's successful build
https://github.com/dsame/GTA/runs/844201838?check_suite_focus=true

3. there's a build failed with the non-explaing error ILT0005
https://github.com/ArchieCoder/GTA/runs/809936481?check_suite_focus=true
```
2020-06-26T05:06:51.2200175Z   C:\Program Files (x86)\Microsoft SDKs\UWPNuGetPackages\microsoft.net.native.compiler\2.2.8-rel-28605-00\tools\Microsoft.NetNative.targets(801,5): error : ILT0005: 'C:\Program Files (x86)\Microsoft SDKs\UWPNuGetPackages\runtime.win10-arm64.microsoft.net.native.compiler\2.2.8-rel-28605-00\tools\ARM64\ilc\Tools64\nutc_driver.exe @"D:\a\GTA\GTA\EG.Sherpany.Boardroom\EG.Sherpany.Boardroom.W10\obj\ARM64\Release\ilc\intermediate\MDIL\Sherpany.App.rsp"' returned exit code 1 [D:\a\GTA\GTA\EG.Sherpany.Boardroom\EG.Sherpany.Boardroom.W10\Sherpany.App.csproj]
```

**Comment by dsame** [comment]
@ArchieCoder 

Can you please try to add
```
<Use64BitCompiler>true</Use64BitCompiler>
```

to the PropertyGroup element of `cproj` files. Also it can be helpful to add `-verbosity:detailed` to msbuild. See this comment as a reference: https://github.com/dsame/GTA/commit/e210e664f65e0775416226544e5729a79cd194f3

Unfortunately i can not confirm this solves the issue in your environment although it worked in my builds because the problem is not always reproducible.

The next step if the build continues to fail is to comment out `<Assembly Name="*Application*" Dynamic="Required All" />` from EG.Sherpany.Boardroom/App1/Properties/Default.rd.xml and EG.Sherpany.Boardroom/EG.Sherpany.Boardroom.W10/Properties/Default.rd.xml

**Comment by ArchieCoder** [comment]
@dsame Bad news: adding Use64BitCompiler to all projects didn't fix the issue. Good news: removing the *Application* + Dynamic works. However, I'm extremely stressed about changing project code to fix the issue of an internal compilation tool.

Also, having deal with .NET Native Tool issues since 2013, I find dangerous to alter Default.rd.xml when the app is working.

Do you have more info about this? Thank you for helping.

**Comment by ArchieCoder** [comment]
@dsame I found this thread https://github.com/dotnet/corert/issues/7408. This seems "safe".

**Comment by dsame** [comment]
@ArchieCoder just a thought - can you please try this action https://github.com/al-cheb/configure-pagefile-action to increase the size of swap (pagefile)?

**Comment by ArchieCoder** [comment]
@dsame I tried with "minimum-size: 32", but still the same error. 

I tried to reach out dotnetnative@microsoft.com mid-June and yesterday about that internal tool and no answer.

**Comment by dsame** [comment]
@ArchieCoder please try to use this setup
```
    - name: configure Pagefile
      uses: al-cheb/configure-pagefile-action@v1.2
      with:
        minimum-size: 8
        maximum-size: 16
        disk-root: "C:"
```

**Comment by ArchieCoder** [comment]
It does not work :(

![image](https://user-images.githubusercontent.com/1608424/87049208-ae4c1e00-c1ca-11ea-9b91-43d56addd0b1.png)

**Comment by al-cheb** [comment]
@ArchieCoder , Could you please set swap?

```
- name: configure Pagefile
  uses: al-cheb/configure-pagefile-action@v1.2
  with:
      minimum-size: 32GB
      maximum-size: 32GB
      disk-root: "C:"
```

**Comment by ArchieCoder** [comment]
@al-cheb wow, your trick worked! Thank you a lot.

@dsame I will close the issue, but I would recommend that the the native team fixes the issue at the source or the default page file is set to 32 gb by default. Thanks for your help too.
