### ISSUE TITLE
macos-10.15-Readme.md is out of date

### ISSUE THREAD

**Issue by incertia** [actions/virtual-environments#1116]
the latest version visible in CI is 20200618.1 but the file is for 20200610.3

notable additions include autoconf and libtool

**Comment by miketimofeev** [comment]
Hi @incertia! Not all macOS environments are updated at the moment. The new readme will be available right after the deployment is finished(approx in next 2-4 hours). Pre-release is available here:
https://github.com/actions/virtual-environments/releases/tag/macos-10.15%2F20200618.1
I'm going to close the issue, but feel free to contact us if you have any concerns.
Thank you!
