### ISSUE TITLE
Add Excel from Microsoft Office Home & Business 2019

### ISSUE THREAD

**Issue by wkschwartz** [actions/virtual-environments#1117]
**Tool information**
- Tool name: Microsoft Excel from Microsoft Office Home & Business 2019
- Tool license: Paid—would appreciate a way to pay via GitHub either per use or per month
- Add or update? Add
- Desired version: Latest version.
- Approximate size: The whole Office download is 1.4 GB, but Excel by itself is much smaller
- If this is an add request:
  - Brief description of tool: Desktop edition of Excel, not the web/Office 365 stuff.  My company's Python apps interact with Excel via the COM interface on Windows.
  - URL for tool's homepage: https://www.microsoft.com/en-us/microsoft-365/p/office-home-business-2019/cfq7ttc0k7cq

**Area for Triage**:

**Question, Bug, or Feature?**:

**Virtual environments affected**
- [x] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Ubuntu 20.04 LTS
- [ ] Windows Server 2016 R2
- [x] Windows Server 2019

**Can this tool be installed during the build?**
Might be possible via Chocolatey?

**Tool installation time in runtime**

**Are you willing to submit a PR?**
It requires figuring out how registration keys, licenses, and payments would interact, so I think this needs to be led by GitHub/Microsoft.

**Comment by thejoebourneidentity** [comment]
Thanks for the suggestion, @wkschwartz. For now, working through the license requirements to support this type of request is not something we can add to our roadmap. Closing this issue for now.

**Comment by PartTimeLegend** [comment]
Can you not install a trial via Chocolatey and then simply use it in trial mode?

**Comment by wkschwartz** [comment]
Interesting idea. I haven't read the license so I'm not sure how many times my CI can do that. Mostly I was hoping that, with GitHub being owned by Microsoft now, Microsoft could find a way to let me pay them to solve the problem for me.

**Comment by PartTimeLegend** [comment]
Seems easier than I thought.

```yaml
- name: Activate Office
  working-directory: C:\Program Files (x86)\Microsoft Office\Office16
  run: cscript ospp.vbs /inpkey:$OFFICE_ACTIVATION_CODE
  env:
    NUGET_AUTH_TOKEN: ${{secrets.OFFICE_ACTIVATION_CODE}}  
```

You then add your Activation Code as a variable in your repo secrets.

**Comment by wkschwartz** [comment]
Very interesting, @PartTimeLegend! Which type of license does that activate code correspond to? And you're running desktop Office, not in-browser web stuff, right? I need to connect to Excel via COM, not the modern Javascript APIs.

**Comment by catthehacker** [comment]
@wkschwartz `ospp.vbs` is included in Microsoft Office installation, see https://docs.microsoft.com/en-us/deployoffice/vlactivation/tools-to-manage-volume-activation-of-office

**Comment by wkschwartz** [comment]
That's for volume license activation. Does that mean I need to buy a volume license?

**Comment by PartTimeLegend** [comment]
> Very interesting, @PartTimeLegend! Which type of license does that activate code correspond to? And you're running desktop Office, not in-browser web stuff, right? I need to connect to Excel via COM, not the modern Javascript APIs.

Desktop Excel. There are various editions of Office available via [Chocolatey](https://chocolatey.org/packages?q=microsoft+office) which you can look at using.

I'm not an expert in licensing by any stretch. I believe that this would work for a volume activated edition, but I expect there will be various ways to do this with other editions.
