### ISSUE TITLE
Waiting for WinRM after moving to Private Agent

### ISSUE THREAD

**Issue by gregpakes** [actions/virtual-environments#1119]
**Describe the bug**
I was previously using the Azure Hosted Agents to build my own Windows 2019 image, but after I was told there was a limit of 6 hours in the hosted agents, I had to move to private agents.

When using the hosted agents, the packer build was successful (if it happened under 6 hours).

However, when using my private agent, I can't get past 

> ==> vhd: Waiting for WinRM to become available...
> ==> vhd: Timeout waiting for WinRM.

I have seen other github issues where it appears that the WinRm can be flaky, but my question is:

- Should this "just work"?  Is Packer supposed to automatically handle the networking side of this given it is creating everything in a temporary resource group for me?
- Or am I supposed to handle this networking side myself?

I have noticed that Packer is not creating an NSG which I would expect.

**Question, Bug, or Feature?**: 
Question

**Virtual environments affected**
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Ubuntu 20.04 LTS
- [ ] Windows Server 2016 R2
- [ X ] Windows Server 2019

**Comment by vmapetr** [comment]
Hi @gregpakes !

Packer behavior with network resources is dependent from builders settings that specified in image template. In case if you have existing network group in your subscription, you can use template parameters `virtual_network_name`, `virtual_network_resource_group_name` and `virtual_network_subnet_name` to force VM created by Packer, to use specified network group. Or, in case if those parameters are not set, Packer will create temporary VM with it's own set of network resources. 

Do you modified image-generation template somehow?
According to error message, seems like outgoing/incoming winRM connections are forbidden for your private build agent. It's quite common issue, if you use public IPs connections in Azure. Most common workaround here, is to place build agent in the same network group, that Packer will use for temporary VMs, so Packer could connect with builders via private IPs.

**Comment by gregpakes** [comment]
@vmapetr - I really appreciate your reply.  All my fault - WinRM was blocked from our build machine outbound. 

Apologies for wasting your time!!! 🤦‍♂️

**Comment by CNTKR** [comment]
I'm using ms  hosted agent in my case so how can I troubleshoot.
