### ISSUE TITLE
Add support for jom compiler

### ISSUE THREAD

**Issue by LorenzE** [actions/virtual-environments#112]
**Tool information**
- Tool name: jom compiler by Qt
- Add or update? Add
- Desired version: Latest
- Approximate size: 1.15MB
- If this is an add request:
  - Brief description of tool: jom is a clone of nmake to support the execution of multiple independent commands in parallel. It basically adds the -j command line switch similar to GNU make. This speeds up compilation quite a bit.
  - URL for tool's homepage: https://wiki.qt.io/Jom

**Virtual environments affected**
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [x] Windows Server 2016 R2
- [x] Windows Server 2019

**Can this tool be installed during the build?**
Yes it can but it would be great if it comes already shipped with the windows envs.

**Are you willing to submit a PR?**
If you point me to the right direction, I am happy to give it a shot :)

**Comment by chuckatkins** [comment]
It would be good to have this in the base image I think.  However, while my PR adds it to the image, jom is small enough that adding a `choco install jom` as a setup step in the workflow shouldn't really add much noticable time to the build.

**Comment by Qv2ray-dev** [comment]
Ping, Any update on this?

**Comment by al-cheb** [comment]
Hello, @Qv2ray-dev 
We are testing https://github.com/actions/virtual-environments/pull/135/files PR.

**Comment by Qv2ray-dev** [comment]
Thanks a lot @al-cheb

**Comment by alepauly** [comment]
@LorenzE sorry it took me so long to answer here but as I mentioned in the contributed PR I dont think we should add Jom to the images for now. It's a quick install that could be facilitated through an Action if needed.
