### ISSUE TITLE
Add ORAS CLI

### ISSUE THREAD

**Issue by mboutet** [actions/virtual-environments#1124]
**Tool information**
- Tool name: ORAS CLI
- Tool license: MIT License
- Add or update? Add
- Desired version: v0.8.1 (latest as of Jun 25 2020)
- Approximate size: 5MB
- If this is an add request:
  - Brief description of tool: Registries are evolving as Cloud Native Artifact Stores. To enable this goal, Microsoft has donated ORAS as a means to enable various client libraries with a way to push OCI Artifacts to OCI Conformant registries.
  - URL for tool's homepage: https://github.com/deislabs/oras

**Area for Triage**:
Packages

**Question, Bug, or Feature?**:
Feature

**Virtual environments affected**
- [ ] macOS 10.15
- [X] Ubuntu 16.04 LTS
- [X] Ubuntu 18.04 LTS
- [X] Ubuntu 20.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Can this tool be installed during the build?**
See https://github.com/deislabs/oras#cli-installation

**Tool installation time in runtime**
Less than 10s

**Are you willing to submit a PR?**
Yes

**Comment by dibir-magomedsaygitov** [comment]
ORAS CLI has been added to all Ubuntu images in scope of [this ](https://github.com/actions/virtual-environments/pull/1194)PR.
Changes are merged and will be delivered to all VM's with the next week's deployment.

**Comment by dibir-magomedsaygitov** [comment]
@mboutet ORAS CLI is available across all Ubuntu images now. I'm going to close the issue but feel free to contact us if you have any concerns.
Thank you!

**Comment by escherstair** [comment]
ORAS CLI has been removed from Ubuntu-24.014 image in PR #10636
