### ISSUE TITLE
Some windows-2019 containers do not have all documented software versions installed

### ISSUE THREAD

**Issue by daniefer** [actions/virtual-environments#1125]
**Describe the bug**
I started experiencing intermittent build failures on a project targeting dotnetcore2.2. The logs indicate that the 2.2 SDK is not installed, however the [documentation says](https://github.com/actions/virtual-environments/blob/master/images/win/Windows2019-Readme.md#net-core-sdk) says several 2.2 versions. 

**Area for Triage**: 
I notice that this issue only appears when a particular container version is used: `20200621.1`

Failing pipeline run
```
Starting: Initialize job
Agent name: 'Azure Pipelines 2'
Agent machine name: 'WIN-BRM6R053O21'
Current agent version: '2.170.1'
Current image version: '20200621.1'
Agent running as: 'VssAdministrator'
Prepare build directory.
Set build variables.
Download all required tasks.
Downloading task: DotNetCoreCLI (2.171.3)
Downloading task: CopyFiles (2.164.2)
Downloading task: PublishBuildArtifacts (1.158.3)
Checking job knob settings.
   Knob: AgentToolsDirectory = C:/hostedtoolcache/windows Source: ${AGENT_TOOLSDIRECTORY} 
   Knob: AgentPerflog = c:\agents\perflog Source: ${VSTS_AGENT_PERFLOG} 
Finished checking job knob settings.
Start tracking orphan processes.
Finishing: Initialize job
```

Successful pipeline run
```
Starting: Initialize job
Agent name: 'Azure Pipelines 2'
Agent machine name: 'WIN-MI55APC537G'
Current agent version: '2.170.1'
##[debug])
##[debug]Task 'dotnet test' has following condition: 'succeeded()'.
##[debug]Parsing expression: <succeeded()>
##[debug]succeeded
##[debug](
##[debug])
##[debug]Task 'dotnet Publish' has following condition: 'succeeded()'.
##[debug]Parsing expression: <succeeded()>
##[debug]succeeded
##[debug](
##[debug])
##[debug]Task 'Copy azuredeploy.json' has following condition: 'succeeded()'.
##[debug]Parsing expression: <succeeded()>
##[debug]succeeded
##[debug](
##[debug])
##[debug]Task 'Publish Artifact: drop' has following condition: 'succeededOrFailed()'.
##[debug]Parsing expression: <succeededOrFailed()>
##[debug]succeededOrFailed
##[debug](
##[debug])
Checking job knob settings.
   Knob: AgentToolsDirectory = C:/hostedtoolcache/windows Source: ${AGENT_TOOLSDIRECTORY} 
   Knob: AgentPerflog = c:\agents\perflog Source: ${VSTS_AGENT_PERFLOG} 
Finished checking job knob settings.
##[debug]Log plugin 'TestResultLogPlugin' is disabled.
##[debug]Log plugin 'TestFilePublisherPlugin' is disabled.
Start tracking orphan processes.
Finishing: Initialize job
```

**Question, Bug, or Feature?**: 
Is this a bug or was this a deliberate change? If it was deliberate, did I miss the announcement?

**Virtual environments affected**
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Ubuntu 20.04 LTS
- [ ] Windows Server 2016 R2
- [X] Windows Server 2019

**Expected behavior**
The dotnetcore2.2 SDKs should be installed

**Actual behavior**
The dotnetcore2.2 SDKs are not installed

**Comment by miketimofeev** [comment]
Hi @daniefer 
There was an announcement https://github.com/actions/virtual-environments/issues/975
It usually takes 4-5 days to propagate the new image to all the environments. We're going to finish win19 deployment today and right after that docs will be updated automatically. Release notes for the new image are available here:
https://github.com/actions/virtual-environments/releases/tag/win19%2F20200621.1
I'm going to close the issue, but feel free to contact us if you have any concerns.
Thank you!
