### ISSUE TITLE
Hosted MacOS hostname changed inside a single step

### ISSUE THREAD

**Issue by Yanjingzhu** [actions/virtual-environments#1127]
When using macos-latest to run a job, there was an intermittent issue. The hostname of the runner changed inside one step. Please check this workflow run: 
https://github.com/tsduck/tsduck/runs/807842947?check_suite_focus=true#step:5:9 
https://github.com/tsduck/tsduck/runs/807842947?check_suite_focus=true#step:5:1668 
The runner hostname changed from `Mac-1720` to `Mac-1784` . 
The issue is reported in this community forum ticket: https://github.community/t/change-runner-host-between-steps-of-a-single-workflow/119937 
How did the runner change inside a job? Is it a bug?

**Comment by miketimofeev** [comment]
Hi @Yanjingzhu @lelegard! This is probably the same issue as described here https://github.com/actions/virtual-environments/issues/978
macOS hostname changes in a few seconds after the build is started. We're working on the fix, but no ETA for now so I'm afraid it's better to avoid using hostname-based variables at the moment.
I'm going to close this issue as a duplicate, let's track everything on the first one, but feel free to contact us if you have any concerns.
Thank you!
