### ISSUE TITLE
Adding bash/sh to Full Disk Access on macOS

### ISSUE THREAD

**Issue by zwaldowski** [actions/virtual-environments#113]
**Tool information**
- Tool name: `/bin/bash` and/or `/bin/sh`
- Add or update? Update

Giving the runner shell Full Disk Access allows equivalent behavior to passwordless sudo on Linux for the purposes of system administration within a workflow. It would allow a workflow to modify system configuration such as the time, or, in particular, to allow actions to send Apple Events to GUI apps.

This is a blocking issue to us automating GUI apps in a workflow. (Our use case: automating a GUI app to export PDFs of a custom file format during a workflow upon CI runs to check for syntax errors.) I don't know of another workaround to allow this type of workflow. This is something we've been able to do on other CI systems and with previous versions of macOS; needing to do this is specific to 10.15.

Note that the Full Disk Access setting is inherited from the topmost user-visible process in the chain, if one is available. For instance, I have to enable Full Disk Access for Terminal to do this on my own machine; other CI systems have needed to add `/usr/sbin/sshd`. This may mean for our purposes that the runner harness be added to the list; I don't know. An action should be able to run `sudo sqlite3 ~/Library/Application\ Support/com.apple.TCC/TCC.db '.dump'` without a permissions error if done correctly.

**Virtual environments affected**
- [x] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Can this tool be installed during the build?**

No, this is a configuration change that must be done with GUI access to the virtual environment.

**Are you willing to submit a PR?**

See above.

**Comment by miketimofeev** [comment]
Hi @zwaldowski  Could you please provide any sample code that faces the issue? It will help us a lot with debugging.

**Comment by miketimofeev** [comment]
Some tweaks have been applied to the image. Waiting for next week rollout

**Comment by miketimofeev** [comment]
@zwaldowski could you please check the behavior now?

**Comment by miketimofeev** [comment]
@zwaldowski I've checked `sudo sqlite3 ~/Library/Application\ Support/com.apple.TCC/TCC.db '.dump'` and everything seems fine. Closing the issue, but feel free to reopen if you have any concerns.
Thank you!
