### ISSUE TITLE
NetCore SDK 2.2 missing in the new Ubuntu Virtual environment version 20200621.1

### ISSUE THREAD

**Issue by wizz2020** [actions/virtual-environments#1134]
**Describe the bug**
We are currently using 16.04 LTS in Azure build and this breaks our build as we are using netcore 2.2 sdk for our application which isn't readily available on any new **Ubuntu virtual environment installed softwares starting from version released on 20200621.1**

**Area for Triage**: 
https://github.com/actions/virtual-environments/blob/master/images/linux/Ubuntu1604-README.md

**Question, Bug, or Feature?**: 
Will it be possible to have the NETCore SDK 2.2 added again as a pre-installed software in Ubuntu virtual environments 16.04, 18.04, 20.04 ?

**Virtual environments affected**
- Ubuntu 16.04 LTS
- Ubuntu 18.04 LTS
- Ubuntu 20.04 LTS

**Expected behavior**
We expected to have NETCore SDK 2.2 like the previous releases of Ubuntu virtual environments.

**Actual behavior**

1. Open a Azure YAML build script and use vmImage: 'ubuntu-16.04'
2. Add build and test task.
3. Run the pipeline.

**Comment by miketimofeev** [comment]
Hi @wizz2020 
There was an announcement https://github.com/actions/virtual-environments/issues/975

If you still need to use .NET Core 2.2.x, you will be able to install it in runtime using the following tasks:
[UseDotNet](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/tool/dotnet-core-tool-installer?view=azure-devops) (Azure DevOps)
[setup-dotnet](https://github.com/actions/setup-dotnet) (GitHub Actions)
I'm going to close the issue, but feel free to contact us if you have any concerns.
Thank you!

**Comment by wizz2020** [comment]
Thank you very much. UseDotNet (Azure DevOps) works for me.
