### ISSUE TITLE
Update/Add AZ module for PowerShell 

### ISSUE THREAD

**Issue by Kamyar5353** [actions/virtual-environments#1135]
**Tool information**
- Tool name: PowerShell / AZ module
- Tool license: N/A
- Add or update? Update
- Desired version: latest, currently 3.8.0 is installed on the machine, the latest at the moment is 4.3.0
- Approximate size: 
- If this is an add request:
  - Brief description of tool: 
  - URL for tool's homepage: 

**Area for Triage**:

**Question, Bug, or Feature?**:

**Virtual environments affected**
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Ubuntu 20.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Can this tool be installed during the build?**

**Tool installation time in runtime**

**Are you willing to submit a PR?**

**Comment by vmapetr** [comment]
@Kamyar5353 Latest Az module version (4.3.0) was added to Ubuntu/Windows images. Changes will be delivered during the next deployment (1-2 weeks approximately).

**Comment by Kamyar5353** [comment]
Thanks. 

a few questions:
1- How could I notice the deployment is done?
2- If it takes like a week or more, is there any way to get that sooner?
3- After the changes delivered, do I need to do anything on my DevOps pipeline?

Thanks.

**Comment by vmapetr** [comment]
> Thanks.
> 
> A few questions:
> 1- How could I notice the deployment is done?
> 2- If it takes like a week or more, is there any way to get that sooner?
> 3- After the changes delivered, do I need to do anything on my DevOps pipeline?
> 
> Thanks.

1. We will notify you , when it's done.
2. To avoid waiting you can add temporary workarounds to your pipelines

windows:
```
    - powershell: |
        Save-Module -Path "C:\Modules\az_4.3.0" -Name "az" -RequiredVersion "4.3.0" -Force -ErrorAction Stop
```
ubuntu:
```
    - bash: |
        pwsh -Command "Save-Module -Name Az -LiteralPath /usr/share/az_4.3.0 -RequiredVersion 4.3.0 -Force"
```
3. Image version that you use in pipelines will be updated automatically, so there is no need for additional changes.

**Comment by Kamyar5353** [comment]
Thanks for your prompt reply. regarding to no 2, where should I add this command; in my PowerShell script?

**Comment by vmapetr** [comment]
It's better to place this workaround as a separate stage in your YAML template, if you use YAML pipelines. In case if you use classic pipeline editor, you can simply create additional powershell/bash task via UI pipeline editor. Though, you can simply add `Save-Module ...` cmdlet in the beginning of your script, and it will do the same thing.

**Comment by Kamyar5353** [comment]
Thanks, I tried the solution and it worked. :)
