### ISSUE TITLE
homebrew executables are superseded by system ones

### ISSUE THREAD

**Issue by andreineculau** [actions/virtual-environments#1136]
**Describe the bug**
Homebrew (or specifically linuxbrew) was added to the mix in https://github.com/actions/virtual-environments/pull/589 .
Then came https://github.com/actions/virtual-environments/pull/789 which turned off the expected behaviour, which is brew executables take precedence over the system ones. This is the expected behaviour, no matter what some might think, and it's what `brew shellenv` outputs as well.

I wrote more on the topic in https://github.com/actions/virtual-environments/pull/789#issuecomment-650087417 .

What is not clear is the reason why the default behaviour (prepending homebrew's paths to PATH) does work well with the Github Actions images.

As per @miketimofeev's comment https://github.com/actions/virtual-environments/pull/789#issuecomment-650121339 , the reason was: `we keep system python is that it contains some pip packages like request, which are essential for some internal teams and we received a complaint right after python from brew was put in the PATH.`

I fear the argument doesn't stand on its own. 

First of all `apt-get install python python-pip && pip list` will show that there are only 3 default packages, namely: pip setuptools wheel. These happens in all 3 Ubuntu distros (`docker run -it ubuntu:XX.04`), both for python (2) and python3 aptitude packages. Thus, whatever packages the internal teams expect to be installed are coming from some obscure intermediate steps, rather than the default installation of python.

Second of all, if the internal teams require a dependency, then they need to make sure that they actually install that dependency. As it is now, the complaint sounds like "Before #589, we had access to our hidden dependency. Now we don't, and we don't want to make the hidden dependency explicit."

PS: if someone takes this bug report with a 30000 feet perspective of fixing the homebrew installation as a whole, note that since homebrew executable will take precedence over the system ones, homebrew installer should be called as one of the very last things, if not the very last thing. Example: installing homebrew, than python (via aptitude) and calling `python` to see if the aptitude installation succeeded is going to yield false results (in its current form) because you will test for and invoke homebrew's python, not the system's python.

**Area for Triage**: 

Deployment/Release ?? 🤷 

**Question, Bug, or Feature?**: 

Bug

**Virtual environments affected**
- [ ] macOS 10.15
- [x] Ubuntu 16.04 LTS
- [x] Ubuntu 18.04 LTS
- [x] Ubuntu 20.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Expected behavior**

I expect that after running `brew install python`, `which python` would actually point to homebrew's `python`, as it is the default behaviour.

**Actual behavior**

The actual behaviour is that `brew install python` followed by `which python` will still point to the system's `python`. I will refrain from detailing why this is a problem, because it would be verbose and I suspect it's rather obvious.

**Comment by miketimofeev** [comment]
@andreineculau thanks for such a detailed explanation! We've switched aws-sam-cli installation to build from sources instead of brew and put brew directories at the beginning of the PATH. Changes will be deployed next week

**Comment by andreineculau** [comment]
@miketimofeev thank you! that's a very nice (quick) development lifecycle 👏

**Comment by miketimofeev** [comment]
@andreineculau clean brew installation is available on the image and brew directories are prepended to the PATH now:
`/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:/usr/share/rust/.cargo/bin:/home/runner/.config/composer/vendor/bin:/home/runner/.dotnet/tools:/snap/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games`

I've also checked 
```
brew install python3
python3 --version
which python3
```
The output looks good
```
Python 3.8.3
/home/linuxbrew/.linuxbrew/bin/python3
```
I'm going to close the issue but feel free to contact us if you have any concerns.
Thank you!
