### ISSUE TITLE
Add ffmpeg

### ISSUE THREAD

**Issue by thomaschaaf** [actions/virtual-environments#1139]
**Tool information**
- Tool name: ffmpeg
- Tool license: LGPL
- Add or update? Add
- Desired version: Stable
- Approximate size:
- If this is an add request:
  - Brief description of tool: A complete, cross-platform solution to record, convert and stream audio and video.
  - URL for tool's homepage: https://www.ffmpeg.org/

**Area for Triage**:
Testing and code coverage

**Virtual environments affected**
- [x] macOS 10.15
- [x] Ubuntu 16.04 LTS
- [x] Ubuntu 18.04 LTS
- [x] Ubuntu 20.04 LTS
- [x] Windows Server 2016 R2
- [x] Windows Server 2019

**Can this tool be installed during the build?**
```
npm i @ffmpeg-installer/ffmpeg
```

**Tool installation time in runtime**
10s

**Are you willing to submit a PR?**
Yes

**Comment by maxim-lobanov** [comment]
Hello @thomaschaaf , thank you for your feature request but we wouldn't like to pre-install this tool to images for now because it is intended for specific use-cases and can be quickly installed in runtime.
