### ISSUE TITLE
Add hardware virtualization in github-hosted runner(ubuntu)

### ISSUE THREAD

**Issue by koteswara-kelam** [actions/virtual-environments#114]
**Tool information**
- Tool name: qemu-kvm libvirt-bin ubuntu-vm-builder bridge-utils
- Add or update? add
- Desired version: 
- Approximate size: 
- If this is an add request:
  - Brief description of tool: To enable hardware virtualization, we need to install qemu-kvm libvirt-bin ubuntu-vm-builder bridge-utils
  - URL for tool's homepage: 

**Virtual environments affected**
- [ ] macOS 10.15
- [*] Ubuntu 16.04 LTS
- [*] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Can this tool be installed during the build?**
sudo apt-get install qemu-kvm libvirt-bin ubuntu-vm-builder bridge-utils
sudo systemctl enable libvirt-bin

**Are you willing to submit a PR?**
yes

**Comment by eleni-salamani** [comment]
Would the software installation suffice though, to have nested virtualization working on the ubuntu runners? To the best of my knowledge, KVM is not enabled on those machines, I think that would be the first thing to address.

**Comment by felipecassiors** [comment]
Issue #183 is required for completing this one.

**Comment by oxr463** [comment]
Please keep this open.

**Comment by Andrei-Pozolotin** [comment]
+1

**Comment by felipecassiors** [comment]
Isn't this a duplicate of https://github.com/actions/virtual-environments/issues/183?

**Comment by oxr463** [comment]
> Isn't this a duplicate of #183?

This lists specific packages for use on Linux. The other pertains to Azure infrastructure limitations.

**Comment by alepauly** [comment]
@koteswara-kelam Unfortunately we are unable to support this at the moment, thanks for suggesting it.

**Comment by MaxPeal** [comment]
+1

**Comment by pp185214** [comment]
+1

**Comment by typetetris** [comment]
+1

**Comment by filipkowicz** [comment]
Android developers need it run emulator way faster. Needed for instrumentation tests

**Comment by AfzalivE** [comment]
> @koteswara-kelam Unfortunately we are unable to support this at the moment, thanks for suggesting it.

If this isn't supported yet, wouldn't it be better to keep this issue open?

**Comment by headsvk** [comment]
Can this be done as part of [Roadmap #161 ](https://github.com/github/roadmap/issues/161)?
