### ISSUE TITLE
Add yamllint (or any similar tool to lint YAML)

### ISSUE THREAD

**Issue by yvele** [actions/virtual-environments#1142]
**Tool information**
- Tool name: yamllint
- Tool license: GNU General Public License v3.0
- Add or update? Add
- Desired version: Latest
- Approximate size: 
- If this is an add request:
  - Brief description of tool: A linter for YAML files
  - URL for tool's homepage: https://github.com/adrienverge/yamllint

**Area for Triage**:

Testing and code coverage

**Question, Bug, or Feature?**:

Feature

**Virtual environments affected**
- [x] macOS 10.15
- [x] Ubuntu 16.04 LTS
- [x] Ubuntu 18.04 LTS
- [x] Ubuntu 20.04 LTS
- [x] Windows Server 2016 R2
- [x] Windows Server 2019

**Can this tool be installed during the build?**

```
sudo apt-get install yamllint
```

**Tool installation time in runtime**

run in 23s on `ubuntu-latest`

```txt
 Set up yamllint 21s
Run sudo apt-get install yamllint
  sudo apt-get install yamllint
  shell: /bin/bash -e {0}
(Reading database ... 100%
(Reading database ... 254558 files and directories currently installed.)
Preparing to unpack .../python3-pathspec_0.5.5-1_all.deb ...
Unpacking python3-pathspec (0.5.5-1) ...
Selecting previously unselected package yamllint.
Preparing to unpack .../yamllint_1.10.0-1_all.deb ...
Unpacking yamllint (1.10.0-1) ...
Setting up python3-pathspec (0.5.5-1) ...
Setting up yamllint (1.10.0-1) ...
Processing triggers for man-db (2.8.3-2ubuntu0.1) ...
```

But there are many other ways to install it, like `pip install`, see https://yamllint.readthedocs.io/en/stable/quickstart.html#installing-yamllint 

**Are you willing to submit a PR?**

Yes (but I don't master Windows Server)

**Comment by maxim-lobanov** [comment]
Hello @yvele , thank you for feature request. We would like to keep this work item opened for awhile to see popularity of this request.

**Comment by al-cheb** [comment]
Hello, @yvele 
All images now contain yamllint package:

macOS - https://github.com/actions/virtual-environments/blob/main/images/macos/macos-10.15-Readme.md#linters
Ubuntu 16.04 - https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu1604-README.md
Ubuntu 18.04 - https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu1804-README.md
Ubuntu 20.04 - https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-README.md
Windows Server 2016 - https://github.com/actions/virtual-environments/blob/main/images/win/Windows2016-Readme.md
Windows Server 2019 - https://github.com/actions/virtual-environments/blob/main/images/win/Windows2019-Readme.md
