### ISSUE TITLE
Run Docker commands on Windows

### ISSUE THREAD

**Issue by michalb-dsg** [actions/virtual-environments#1143]
**Describe the bug**
I'm new to GitHub Actions and facing a few Docker related issues. I'm using Docker SDK for Python, and my tests are failing because image pull is failing. I even added a step and tried to run `docker pull` command via CLI, and I discovered something strange. Some pulls are working, and others just don't.  
For example:
running the following step-
```
- name: Test Docker on Windows
        if: startsWith(runner.os, 'Windows')
        run: |
          docker pull hello-world
```
works just fine, but running this step-
```
- name: Test Docker on Windows
        if: startsWith(runner.os, 'Windows')
        run: |
          docker pull minio/minio
```
will cause the following error:
image operating system "linux" cannot be used on this platform
##[error]Process completed with exit code 1.

I tried to pull the same image (`minio/minio`) on my own windows (10 pro, not server), and this command (`docker pull minio/minio`) actually **did work**. I checked, and my configurations are standard (no experimental mode).

**Area for Triage**: 
Scripting and command line

**Question, Bug, or Feature?**: 
Somewhere in between a question and a bug

**Virtual environments affected**
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Ubuntu 20.04 LTS
- [ ] Windows Server 2016 R2
- [x] Windows Server 2019

I want to understand why I'm not able to pull some images on Windows virtual environments. Is there a way to avoid it?
Thanks :)
(If any other information is needed, please ask)

**Comment by al-cheb** [comment]
Hello, @michalb-dsg 
Sorry we don't support Linux container on Windows Server 2016/2019, because the main requirement is `Docker Desktop Enterprise`. Out of the box, Docker on Windows only run Windows container. To use Linux containers on Windows Server , you need to use the Docker Desktop Enterprise which includes a full LinuxKit system for running Docker Linux containers - https://docs.microsoft.com/en-us/virtualization/windowscontainers/quick-start/quick-start-windows-10-linux. Another drawback is that we can not pre-install Docker Desktop Enterprise due to license policy.

**Comment by michalb-dsg** [comment]
Hi @al-cheb 
Thank you for your quick response! Is it possible to install Docker Desktop as one of my steps in CI? And after the installation, I didn't find any CLI commands for Docker Desktop in order to change some settings after installation- is it possible?

**Comment by al-cheb** [comment]
@michalb-dsg , Currently nope, you can't install Docker Desktop in CI  due to limitations of virtual environments:
1. Microsoft-Hyper-V component is not enabled on Windows Server 2019 image and needs reboot to enable this component
2. DSv2 vm instance, we are currently using, doesn't support nested virtualization

**Comment by michalb-dsg** [comment]
:ok_hand: 
So, the same goes for MacOS, right?

**Comment by al-cheb** [comment]
@michalb-dsg, You can install docker and use minio/minio in runtime for macOS, because we already pre-installed virtualbox on macOS image. We can't pre-install docker on the macOS image due to license policy agreement.

```
jobs:
  build:
    runs-on: 'macos-latest'

    steps:
      - name: Install docker
        run: |
         mkdir -p ~/.docker/machine/cache
         curl -Lo ~/.docker/machine/cache/boot2docker.iso https://github.com/boot2docker/boot2docker/releases/download/v19.03.12/boot2docker.iso
         brew install docker docker-machine
         docker-machine create --driver virtualbox default
         docker-machine env default
      - name: Run container
        run: |
         eval "$(docker-machine env default)" 
         docker pull minio/minio
         docker container run --rm minio/minio minio --help
```

![image](https://user-images.githubusercontent.com/47745270/86219446-e334f100-bb8a-11ea-85cc-a2c235b019be.png)

**Comment by al-cheb** [comment]
Feel free to open the thread if you have any concerns.

**Comment by ItalyPaleAle** [comment]
@al-cheb now that Docker on Windows can use WSL to run Linux containers, is it possible to maybe reopen this?

**Comment by al-cheb** [comment]
@ItalyPaleAle,   WSL2 doesn't support current -  `OS Version: 10.0.17763 Build 1397`

**Comment by mkreidenweis** [comment]
@al-cheb Are the plans to upgrade the OS Version to support WSL2, or is this not possible for some reason?

**Comment by al-cheb** [comment]
@alepauly, Do we have any plans to update Windows Server 2019?

**Comment by thedrow** [comment]
> 
> 
> @alepauly, Do we have any plans to update Windows Server 2019?

That would be most helpful.

**Comment by piekstra** [comment]
> @alepauly, Do we have any plans to update Windows Server 2019?

This would be really great. I'm trying to add windows-OS testing for a Python library which leverages the `rodolpheche/wiremock` docker image which is Linux-based with no Windows-based image at this time, thus breaking my `docker-compose` using the windows runner.

**Comment by h0p3zZ** [comment]
@al-cheb is WSL2 enabled on windows-latest?

**Comment by h0p3zZ** [comment]
The ability to run docker on windows via WSL would be great, because if you need smth. like Electron (as we do) with a windows-build you could still use it.

**Comment by catthehacker** [comment]
@h0p3zZ WSL2 has been removed from Windows Server 2022 so it's not possible to run Linux containers in WSL

**Comment by h0p3zZ** [comment]
> @h0p3zZ WSL2 has been removed from Windows Server 2022 so it's not possible to run Linux containers in WSL See [microsoft/WSL#6301 (comment)](https://github.com/microsoft/WSL/issues/6301#issuecomment-858816891)

Alright... yeah thats real bad :D 

Still... is there a way we can achieve the usecase I mentioned earlier?

**Comment by catthehacker** [comment]
Not sure what are you trying to do, but Electron should work normally through NodeJS

**Comment by h0p3zZ** [comment]
@catthehacker I'm trying to run the spectron tests in an Action. But when I try to run this in ubuntu-latest it does not work at all. In windows all tests pass in ubuntu none do. 

Therefore the request.
