### ISSUE TITLE
Add dotnet core container images (sdk & aspnet)

### ISSUE THREAD

**Issue by JKrag** [actions/virtual-environments#1144]
**Tool information**
- Tool name: mcr.microsoft.com/dotnet/core container images (sdk & aspnet)
- Tool license: MIT
- Add or update? Add
- Desired version: 3.1
- Approximate size: sdk: 700Mb, aspnet: 207Mb
- If this is an add request:
  - Brief description of tool: dotNet Core base images pre-cache for faster builds
  - URL for tool's homepage: https://hub.docker.com/_/microsoft-dotnet-core-sdk/

**Area for Triage**: Containers

**Question, Bug, or Feature?**: Feature

**Virtual environments affected**
- [ ] macOS 10.15
- [X] Ubuntu 16.04 LTS
- [X] Ubuntu 18.04 LTS
- [X] Ubuntu 20.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019
I only need the change on one of the Linux images, but for consistency it makes sense to do it on all 3 Linux images. Is it relevant at all on the Windows ones, or do people then build native instead of using Docker?

**Can this tool be installed during the build?**
Image pulled automatically on demand if used in a Dockerfile. 
E.g.
``` Dockerfile
FROM  mcr.microsoft.com/dotnet/core/sdk:3.1 AS build-env
WORKDIR /app
COPY *.csproj ./
RUN dotnet restore
COPY . ./
RUN dotnet publish -c Release -o out

FROM mcr.microsoft.com/dotnet/core/aspnet:3.1
WORKDIR /app
COPY --from=build-env /app/out .
COPY data /app/data
EXPOSE 80
ENTRYPOINT ["dotnet", "Backend.dll"]
```

**Tool installation time in runtime**
Base image is not really "installed", but pulling it during `docker build` takes about 20 seconds on average by my observations.

**Are you willing to submit a PR?**
Yes, I would be up for trying at least. The code changes seems quite trivial, but I haven't yet looked into what it would take to verify the changes before submitting.

**Comment by maxim-lobanov** [comment]
Hello @JKrag  , thank you for feature request. We would like to keep this work item opened for awhile to see popularity of this request.

Also, I see that you requested version 3.1. How often new versions of containers are released? Should we add new versions in future too? Is it okay to keep the latest one or we will have to keep a few versions.

**Comment by JKrag** [comment]
@maxim-lobanov I think it is a good idea to keep this item open a bit and gather input. If only very few people pitch in, then I agree that is would be a waste of space having these docker images pre-cached.

From my point of view, I would say that having the latest major version available should cover a lot of peoples needs - or maybe having both 2.1 and 3.1 in the latest stable, but it would probably be overkill to have Docker images for all the 56 minor versions of .Net Core SDK that are currently directly installed on the Ubuntu 18.04 machines :-)

But admittedly, I come to this from the DevOps/build perspective, so maybe some .Net developers would like to pitch in on whether my assumption of prioritizing only the latest 3.1 (and maybe 2.1) is reasonable?

**Comment by maxim-lobanov** [comment]
Hello @JKrag , thank you for your patience but we wouldn't like to cache these containers on image for now.
Let me explain this decision: a few months ago we had an incident with free space on Ubuntu images (our images should have at least 14 GB of free space based on official documentation, when we add new software, we can decrease this limit). So currently we have to be very selective about tools that we pre-install.
Considering the facts that these containers are downloaded very quick (20 seconds as you mentioned) and their size is 1 GB, we would not like to pre-cache them for now.

We will be able to revisit this decision in future if we see more requests for it or more freedom from image size side.
I am closing this issue for now but please let me know if you have any additional questions.
