### ISSUE TITLE
Add Docker Desktop (MacOS)

### ISSUE THREAD

**Issue by rpsu** [actions/virtual-environments#115]
**Tool information**
- Tool name: Docker Desktop (MacOS Docker.app)
- Add or update? Add
- Desired version: 2.1.*
- Approximate size: 
- If this is an add request:
  - Brief description of tool: Docker to run containerized applications
  - URL for tool's homepage: https://www.docker.com/community-edition

**Virtual environments affected**
- [x] macOS 10.15

**Can this tool be installed during the build?**
While the app installation itself works, initial startup requires runner user's password. This I do not have nor can set via password reset (as explained by  Thomas Baillie from GitHub Developer Support in an support request email, Nov 27, 10:10 AM UTC ).

Docker.app refuses to start with sudo. It must to be started as a regular user *and* user must provide a password via UI dialog (which could be done with applescript if I had OR could reset the runner user's password).

This is not just adding the Docker.app, but also starting it with correct permissions so that the network settings can be configured. After the initial launch Docker.app can be stopped, and future startups should work fine with no passwords nor sudo's involved.

Project, branch and workflow that is an example of this need (trying to launch a docker-compose -based tool for testing in MacOS):
https://github.com/Exove/local-docker/blob/ci-jobs-initial-test-to-pass/.github/workflows/macos-latest--tests.yml

**Are you willing to submit a PR?**
Sure  if I only get some instructions how to achieve this.

**Comment by rpsu** [comment]
I'd need some help how to add the Docker as this repository contains merely a list of available binaries, but not the binaries .

**Comment by maxim-lobanov** [comment]
Hello @rpsu , thank you for your suggestion!
We already have a bunch of docker cli tools on macOS image: `docker`, `docker-compose`, `docker-machine`. Do they cover your use-case?
Docker Desktop looks pretty huge (2GB) and we worry if it can work as expected on VM (without GUI).
It would be great, if you could share a bit more context on your use-case?

**Comment by rpsu** [comment]
My use case is I'd like to be able to have CI test for an app exactly the way end users do it in MacOS. `docker` is a client, `docker-machine` seems to need a VirtualBox to function  properly, or have the Docker.app to contain all of that - including the hypervisor. 

An alternative option - using docker-machine and Xhyve hypervisor seems not to work (at least I have not found a way yet).

https://github.com/Exove/local-docker/pull/103/checks?check_run_id=574053551

So there are 2 ways I can think of this could be solved:

1. Have some way to install Drupal Desktop *and* launch it (which requires `runner` user's password, not just `sudo` perms) - scriptable if the password can be reset or is known
2. Use existing docker (client), docker-compose and docker-machine, which requires a hypervisor compatible with `docker` (client)



Based on the tests currently launching the docker for the first time requires users _password_

**Comment by rpsu** [comment]
![Screenshot 2020-04-09 at 16 57 53](https://user-images.githubusercontent.com/1099454/78903075-5430a500-7a83-11ea-93fa-c699074283c6.png)

**Comment by maxim-lobanov** [comment]
@rpsu , thank you for provided context.

JFYI: We are installing `virtualbox` to macOS machines in scope of #433 , changes are already merged. The new image is on way.

**Comment by rpsu** [comment]
thanks! 
Is this the correct place to keep eye on to see the new image? 
https://github.com/actions/virtual-environments/blob/master/images/macos/macos-10.15-Readme.md

**Comment by maxim-lobanov** [comment]
Yep, that is correct location. Also we will update #433 as soon as update is available

**Comment by alepauly** [comment]
@rpsu looks like Docker licensing doesn't actually allow us to put this in the hosted images so we won't be adding it at this time. Thanks for the suggestion!

**Comment by rpsu** [comment]
@alepauly okay, I see. I think I can manage with the Virtualbox providing the VM. I do have some difficulties with bash variables (seemingly not working as they do in desktop), can you point me to someone or some docs how to play with them in macos VM?

**Comment by maxim-lobanov** [comment]
@rpsu , Am I right that you need some docs about configuring Docker + Virtualbox on hosted machine?
I think [this guide](https://medium.com/@yutafujii_59175/a-complete-one-by-one-guide-to-install-docker-on-your-mac-os-using-homebrew-e818eb4cfc3) will work for you. virtualbox is already installed to the images. Other software have to be installed in runtime
