### ISSUE TITLE
clang-cl compiler not found on Windows

### ISSUE THREAD

**Issue by jsmolka** [actions/virtual-environments#1152]
**Describe the bug**
`No CMAKE_CXX_COMPILER could be found.` when trying to build with clang-cl with cmake on Windows.

**Area for Triage**: 
C/C++

**Question, Bug, or Feature?**: 
Bug

**Virtual environments affected**
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Ubuntu 20.04 LTS
- [ ] Windows Server 2016 R2
- [x] Windows Server 2019

**Expected behavior**
I am contributing to a C++ project where we use GitHub actions for automated builds. 19 days ago the Windows builds passed without any problem ([link to action](https://github.com/jsmolka/NanoboyAdvance/runs/763007477?check_suite_focus=true)). Now, the same commit causes build errors on Windows ([link to action](https://github.com/jsmolka/NanoboyAdvance/runs/823452843?check_suite_focus=true)).

These are the problematic commands in the cmake file:
```
mkdir build
cd build
set VCPKG_ROOT=C:/vcpkg
cmake -DCMAKE_BUILD_TYPE=Release -T clangcl ..
```

Which gives the following output:
```
-- Building for: Visual Studio 16 2019
-- The CXX compiler identification is unknown
CMake Error at CMakeLists.txt:8 (project):
  No CMAKE_CXX_COMPILER could be found.
-- Configuring incomplete, errors occurred!
See also "D:/a/NanoboyAdvance/NanoboyAdvance/build/CMakeFiles/CMakeOutput.log".
See also "D:/a/NanoboyAdvance/NanoboyAdvance/build/CMakeFiles/CMakeError.log".
##[error]Process completed with exit code 1.
```

Somehow the compiler is not recognized in the GitHub actions environment (on my machine everything is working). Passing the clang-cl binary via the `CMAKE_CXX_COMPILER` flag mitigates the problem to some degree but causes other build errors.

**Actual behavior**
The build errors started happening around 3 days ago (see the [commit history](https://github.com/fleroviux/NanoboyAdvance/commits/master)). Nothing which could cause the error has been changed in the cmake file.

**Comment by Darleev** [comment]
Hello @jsmolka,
The issue probably can be related [to the previously reported](https://github.com/actions/virtual-environments/issues/1089). Could you please try the same workaround by adding the following task before cmake:
`rmdir /s /q C:\PROGRA~1\POSTGR~1`
Looking forward to your reply.

**Comment by jsmolka** [comment]
I changed the part to
```
mkdir build
cd build
set VCPKG_ROOT=C:/vcpkg
rmdir /s /q C:\PROGRA~1\POSTGR~1
cmake -DCMAKE_BUILD_TYPE=Release -T clangcl ..
```
but the errors still persists ([action run](https://github.com/jsmolka/NanoboyAdvance/runs/823748598?check_suite_focus=true)).

**Comment by Darleev** [comment]
@jsmolka 
Thank you for the information provided.
We will investigate the issue.

**Comment by vsafonkin** [comment]
Hi @jsmolka , looks like [the latest release of vcpkg](https://github.com/microsoft/vcpkg/releases/tag/2020.06) has changes that broken your build. I've tried to downgrade vcpkg to the previous release and build was successful: [run action](https://github.com/vsafonkin/NanoboyAdvance/actions/runs/158166955)

As a workaround you can reinstall vcpkg adding next step:
```
- name: Setup vcpkg
  run: |
    Remove-Item "C:\vcpkg" -Recurse -Force
    $Uri = 'https://github.com/Microsoft/vcpkg.git'
    $InstallDir = 'C:\vcpkg'

    git clone -b 2020.04 --single-branch --depth=1 $Uri $InstallDir -q

    Invoke-Expression "$InstallDir\bootstrap-vcpkg.bat"
    vcpkg integrate install
```

**Comment by jsmolka** [comment]
Thanks for investigating the issue. I will open a new one in vcpkg and see it if can be resolved there!
