### ISSUE TITLE
Publish Docker images in DockerHub

### ISSUE THREAD

**Issue by Saibamen** [actions/virtual-environments#1153]
**Describe**
We need to build own Docker images. There should be possible to download builded Docker image from DockerHub.
Now users need to build own image with all software and self-hosted agent

**Feature?**:
Publish Docker images at https://hub.docker.com/publishers/microsoftowner

**Virtual environments affected**
- [x] macOS 10.15
- [x] Ubuntu 16.04 LTS
- [x] Ubuntu 18.04 LTS
- [x] Ubuntu 20.04 LTS
- [x] Windows Server 2016 R2
- [x] Windows Server 2019

**Expected behavior**
Users need to build own Docker image to host it on own Virtual Machines on Docker

**Actual behavior**
Users can simply download builded Docker images from DockerHub to run own self-hosted agents

**Comment by Darleev** [comment]
Hello @Saibamen,
We had [DockerHub project ](https://hub.docker.com/_/microsoft-azure-pipelines-vsts-agent?tab=description)with Azure Pipeline agents some time ago. You can check the source code in GitHub [by the link](https://github.com/microsoft/vsts-agent-docker). The project was deprecated about a year ago, and currently, only ways described in [the official documentation](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/docker?view=azure-devops) are supported.  
We will discuss the feature internally and get back to you as soon as all the details are clear.

**Comment by Darleev** [comment]
@Saibamen similar request has already been reported several months ago. You can follow-up the status of the request in another issue: https://github.com/actions/virtual-environments/issues/666
Also, let me add some similar requests that might be useful:
https://github.com/actions/virtual-environments/issues/783
https://github.com/actions/virtual-environments/issues/196
https://github.com/actions/virtual-environments/issues/252

I'm going to close the issue.
In case of any questions, feel free to contact us, we will be glad to assist you.
