### ISSUE TITLE
Does total concurrent jobs number include forks?

### ISSUE THREAD

**Issue by f-squirrel** [actions/virtual-environments#1154]
According to the documentation, the Free plan includes **20 concurrent jobs**.

For example, a workflow is triggered on push or pull_requests:
`on: [push, pull_request]`.

When a developer pushes to their local branch in a forked repository, the workflow is triggered.

Do the jobs triggered by the forked repository affect the number of available jobs in the original repository?

**Comment by Darleev** [comment]
Hello @f-squirrel, 
No, they don't. According to [the documentation](https://help.github.com/en/github/getting-started-with-github/fork-a-repo):
"Forking a repository allows you to freely experiment with changes without affecting the original project."
If additional information is required, feel free to contact us.
