### ISSUE TITLE
Add swiftlint

### ISSUE THREAD

**Issue by bielikb** [actions/virtual-environments#1156]
**Tool information**
- Tool name: swiftlint
- Tool license: MIT
- Add or update? Add
- Desired version: 0.39.2
- Approximate size: 3 MB
- If this is an add request:
  - Brief description of tool: A tool to enforce Swift style and conventions.
  - URL for tool's homepage: [https://github.com/realm/SwiftLint](https://github.com/realm/SwiftLint)

**Area for Triage**:
Apple

**Question, Bug, or Feature?**:
Feature

**Virtual environments affected**
- [x] macOS 10.15
- [x] Ubuntu 16.04 LTS
- [x] Ubuntu 18.04 LTS
- [x] Ubuntu 20.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Can this tool be installed during the build?**
Yes

**Tool installation time in runtime**
Couple of seconds

**Are you willing to submit a PR?**
No, I don't know how to add this tool to the GHA env

**Comment by maxim-lobanov** [comment]
Hello @bielikb , thank you for feature request. We would like to keep this work item opened for awhile to see popularity of this request.

**Comment by MaxDesiatov** [comment]
This tool is compatible with Linux too, so I think that Ubuntu checkboxes in the description should be checked too.

**Comment by bielikb** [comment]
Thanks @MaxDesiatov. I just updated the description.

**Comment by maxim-lobanov** [comment]
Hello, we are going to pre-install swiftlint only to macOS images for now. We will update the issue as soon as it is done.

**Comment by nikita-bykov** [comment]
We have added SwiftLint installation to macOS.
Images with it will be rolled out around next week.

**Comment by bielikb** [comment]
Perfect! 
Thanks for adding the swiftlint to GHA.

Best,
Boris

**Comment by dmitry-shibanov** [comment]
Hello changes were added to images. If you have any concerns feel free to reopen the issue.
