### ISSUE TITLE
Xamarin iOS build failing on hosted mac agent

### ISSUE THREAD

**Issue by trwalke** [actions/virtual-environments#1165]
**Describe the bug**
This same issue from last year has started popping up for us after we started targeting AndroidX.

https://github.com/microsoft/azure-pipelines-image-generation/issues/1377

Getting this error when trying to build xamarin.ios on azure pipelines.
"error XA0000: Could not determine API level for $(TargetFrameworkVersion) of 'v10.0'."

I have tried all of the suggestions including using this:
```
- bash: |
    SYMLINK="6_4_0"
    # Set Xamarin.Android 10.0
    sudo $AGENT_HOMEDIRECTORY/scripts/select-xamarin-sdk.sh $SYMLINK
    # Set Mono 6.4.0
    echo "##vso[task.setvariable variable=PATH;]/Library/Frameworks/Mono.framework/Versions/$SYMLINK/bin:$PATH"
  displayName: Select Xamarin and Mono Version
```
**Virtual environments affected**
- [x] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Ubuntu 20.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Actual behavior**
https://identitydivision.visualstudio.com/IDDP/_build/results?buildId=560796&view=logs&j=e2947180-533e-5bfa-20d8-0fd436232f61&t=b9a75ac3-3cd5-54dc-2819-e3dc78712474

Yaml: 
https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/blob/152af23f37b631567a08f68a1bdea99b4894566c/build/pipeline-uiautomation.yaml#L44

https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/blob/master/build/template-build-ios-automation.yaml

How can I go about resolving this?

**Comment by miketimofeev** [comment]
Hi @trwalke!
Could you try changing your pool to the following?
```
pool:
  name: Azure Pipelines
  vmImage: internal-macos-10.15
```
Looks like your builds are being run on pretty old High Sierra VM image.

**Comment by miketimofeev** [comment]
@trwalke could you please try changing the pool?

**Comment by trwalke** [comment]
Hi @miketimofeev changing the pool has resolved this for us. But questions though
Why does the macos-10.15 not work for us but internal-macos-10.15 seems to work? what is the difference between internal and not internal.

**Comment by miketimofeev** [comment]
Discussed with @trwalke off-line.
The issue can be closed.
