### ISSUE TITLE
Update/Add Xcode 12 for macOS Universal Apps beta

### ISSUE THREAD

**Issue by markavitale** [actions/virtual-environments#1166]
**Tool information**
- Tool name: Xcode 12 for macOS Universal Apps beta
- Tool license: https://www.apple.com/legal/sla/docs/xcode.pdf
- Add or update? Add
- Desired version: Xcode 12 for macOS Universal Apps beta
- Approximate size: ~15GB, (~10GB on disk)
- If this is an add request:
  - Brief description of tool: The latest beta of Apple's Xcode IDE that enables universal macOS app compilation (for supporting Apple Silicon)
  - URL for tool's homepage: https://developer.apple.com/xcode/

Note: The expectation is that in a future beta release, the standard Xcode 12 beta and this beta will be merged into a single app.

**Area for Triage**:
Apple

**Question, Bug, or Feature?**:
Feature

**Virtual environments affected**
- [x] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Ubuntu 20.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Can this tool be installed during the build?**
Not sure, but all of the other Xcodes are available by default, including other betas.

**Tool installation time in runtime**
Not sure, but all of the other Xcodes are available by default, including other betas.

**Are you willing to submit a PR?**
I think this will be best handled internally like the typical Xcode deployment pattern, but happy to contribute. Opening this as requested in #1133.

**Comment by markavitale** [comment]
@maxim-lobanov opened per your request. Thanks again!

**Comment by maxim-lobanov** [comment]
@markavitale , Btw, I have found the following on Apple site:
![Screen Shot 2020-07-02 at 7 01 49 PM](https://user-images.githubusercontent.com/16715858/86382695-89b9e880-bc96-11ea-8422-247902abda37.png)

Does it mean that both `Xcode 12 for macOS Universal Apps` and `Xcode 12` will be merged in next beta?

**Comment by eschwieb** [comment]
> @markavitale 
> Does it mean that both `Xcode 12 for macOS Universal Apps` and `Xcode 12` will be merged in next beta?

Probably not for beta 2, but yes, Xcode 12 beta 3 should be one single release with support for all Apple platforms and architctures.

**Comment by markavitale** [comment]
@maxim-lobanov FYI Xcode 12 beta 2 has now been released (for both the standard Xcode 12 Beta and the Xcode 12 Beta for macOS Universal Apps). Ideally when this is deployed, it will be with build 12A8161k.

**Comment by miketimofeev** [comment]
@markavitale we're going to deploy VM image with Xcode 12 Beta 2 next week.

**Comment by maxim-lobanov** [comment]
Just to clarify, we are going to deploy VM image with Xcode Beta 2 (12A6163b) next week.
We didn't start adding `Xcode 12 Beta for macOS Universal Apps` yet. We still have some concerns about adding it to images considering the fact that next betas will be merged to the single product. Every Xcode version is pretty huge and significantly increases image-generation / image-deployment time. We will let you know as soon as we have updates on it

**Comment by maxim-lobanov** [comment]
Hello @markavitale , the good news.
Apple just released Xcode 12 beta 3 and they merged both Xcode versions to the single release:
![image](https://user-images.githubusercontent.com/16715858/88212661-48e33d00-cc60-11ea-968a-4fe6066804e4.png)
We are going to deploy new image with Xcode 12 beta 3 next week

**Comment by miketimofeev** [comment]
The image with Xcode beta 3 has been deployed 🥳

**Comment by SebastianBoldt** [comment]
Any Plans to support Beta 4 soon? 
It is currently not possible to upload Builds made with beta 3 to Appstore Connect using beta <3.

`- name: Select Xcode 12`

`ERROR ITMS-90744: "Unsupported Xcode or SDK Version. Your app was built with a version of Xcode or SDK that is not yet supported for upload to App Store Connect. For more information about supported versions of Xcode and SDK for Testflight or App Store submissions, view the App Store Connect What's New page (https://developer.apple.com/app-store-connect/whats-new/).`

**Comment by maxim-lobanov** [comment]
Answered in cross-thread: https://github.com/actions/virtual-environments/issues/1418#issuecomment-674346131
Sorry for delay. Deployment is in progress
