### ISSUE TITLE
Add Homebrew on Linux

### ISSUE THREAD

**Issue by ericallam** [actions/virtual-environments#117]
**Tool information**
- Tool name: Homebrew
- Add or update? Add
- Desired version: Latest
- If this is an add request:
  - Linux dependency manager/installer
  - https://docs.brew.sh/Homebrew-on-Linux

**Virtual environments affected**
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS

**Comment by peaceiris** [comment]
For reference, It takes 20 sec to install.

```yaml
- name: Install Linuxbrew
  run: sh -c "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install.sh)"
```

**Comment by sjackman** [comment]
FWIW there is an official Homebrew Docker image at `homebrew/brew`.
https://hub.docker.com/r/homebrew/brew
https://github.com/Homebrew/brew/packages/29947
That's not meant to be an argument against adding it to the GitHub VM image, just an FYI.

**Comment by dsame** [comment]
PR https://github.com/actions/virtual-environments/pull/589

**Comment by maxim-lobanov** [comment]
New image with homebrew was deployed everywhere. Closing the issue
