### ISSUE TITLE
Version 30.0.0 of Android Build Tools apksigner tool unable to run

### ISSUE THREAD

**Issue by seb-bartholomew-amcs** [actions/virtual-environments#1170]
Version 30 of Android Build Tools apksigner command line tool appears incompatible with Java version included in these images.

Similar issue raised on stackoverflow at https://stackoverflow.com/questions/60441090/apksignertool-issue-with-java-version suggests an issue with version of Java required by this tool.

Explicitly reverting to use v 29.0.3 of build tools resolves this issue. 
This issue appeared in our pipelines as by default we would discover and use latest version of buildtools available.

**Area for Triage**:  Android

**Question, Bug, or Feature?**: Bug

**Virtual environments affected**
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Ubuntu 20.04 LTS
- [x] Windows Server 2016 R2
- [x] Windows Server 2019

**Expected behavior**
apksigner command line tool runs without error

**Actual behavior**
apksigner command line tool returns error
`
java.lang.UnsupportedClassVersionError: com/android/apksigner/ApkSignerTool has been compiled by a more recent version of the Java Runtime (class file version 53.0), this version of the Java Runtime only recognizes class file versions up to 52.0
`
To recreate:
1. Create Release (or other) pipeline
2. Add a Powershell task to the one default stage
3. Set Powershell task to run inline and provide following command
`
& "C:\Program Files (x86)\Android\android-sdk\build-tools\30.0.0\apksigner.bat"
`

Example in YAML
`
steps:
- powershell: '& "C:\Program Files (x86)\Android\android-sdk\build-tools\30.0.0\apksigner.bat"'
  displayName: 'PowerShell Script'
`

Anyone looking for a workaround running v 29.0.3 of Android Build Tools's apksigner works without issue
eg.
`
& "C:\Program Files (x86)\Android\android-sdk\build-tools\29.0.3\apksigner.bat"
`

**Comment by al-cheb** [comment]
Hello, @seb-bartholomew-amcs 
Could you please set up JAVA version above 8(default on the image)?
```
52 = Java 8 - installed
53 = Java 9
54 = Java 10
55 = Java 11 - installed
56 = Java 12
57 = Java 13 - installed
```

```
$env:JAVA_HOME = $env:JAVA_HOME_13_X64
& "C:\Program Files (x86)\Android\android-sdk\build-tools\30.0.0\apksigner.bat"
```

![image](https://user-images.githubusercontent.com/47745270/86465949-5a10ec00-bd3b-11ea-92cb-b4aee578588d.png)


Or you can use https://github.com/actions/setup-java task to setup JAVA:

```
jobs:
  build:
    runs-on: 'windows-latest'

    steps:
      - uses: actions/setup-java@v1
        with:
          java-version: 13
      - name: apksigner
        run: |
          & "C:\Program Files (x86)\Android\android-sdk\build-tools\30.0.0\apksigner.bat"
```

**Comment by seb-bartholomew-amcs** [comment]
Thanks for the quick response @al-cheb .
Confirmed this does resolve the issue our side as well. 
Tested with Java version 11 and 13 on win-2017 and 2019 images.
eg.
```
 $env:JAVA_HOME = $env:JAVA_HOME_11_X64
 & "C:\Program Files (x86)\Android\android-sdk\build-tools\30.0.0\apksigner.bat"
```

So for the moment appears there are 2 options;
Either 
- explicitly setup Java version to >=11
- explicitly use previous version of build tools (<=29.0.3)

**Comment by seb-bartholomew-amcs** [comment]
Closing for now as there are a couple of workarounds available for others to try now if they hit same issue.
Hopefully at least one of them will meet their requirements.
