### ISSUE TITLE
Add clang-tidy on windows-latest

### ISSUE THREAD

**Issue by sbeyer** [actions/virtual-environments#1171]
**Tool information**
- Tool name: clang-tidy
- Tool license: Apache License 2.0 with LLVM Exceptions
- Add or update? Add
- Desired version: 10 (like other clang tools at the moment)
- Approximate size: 
- If this is an add request:
  - Brief description of tool: a clang-based C++ linter tool
  - URL for tool's homepage: https://clang.llvm.org/extra/clang-tidy/

**Area for Triage**: C/C++

**Question, Bug, or Feature?**: Feature

**Virtual environments affected**
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Ubuntu 20.04 LTS
- [ ] Windows Server 2016 R2
- [X] Windows Server 2019

**Can this tool be installed during the build?**
I think so, but it takes too much time to download the source and compile it. Even the binary downloads (full LLVM package) take more than 100 MB, which does not sound reasonable since most of the clang tools are already installed.

**Tool installation time in runtime**
I do not know.

**Are you willing to submit a PR?**
No, sorry. You already install a lot of clang tools (including clang-format), so it is probably easier for you to add clang-tidy from the extra clang tools than for me to get into the whole thing.

**Comment by sbeyer** [comment]
I guess that it is important to not forget the run-clang-tidy script coming with clang-tidy.

**Comment by AshUK** [comment]
I'd like to see clang10 and sub tools all upgraded to 10.0.0 to the latest stable release across across al the virtual environments. 

'llvm-10 clang-10 clang-tidy-10 clang-format-10'

**Comment by sbeyer** [comment]
> I'd like to see clang10 and sub tools all upgraded to 10.0.0

Isn't it at version 10 currently? I thought it is.

**Comment by AshUK** [comment]
@sbeyer 

MacOSX comes with clang10
https://github.com/actions/virtual-environments/blob/c6950533af3e7bb78729ae8be7f459758eb327ce/images/macos/macos-10.15-Readme.md#L16

Linux: https://github.com/actions/virtual-environments/blob/c6950533af3e7bb78729ae8be7f459758eb327ce/images/linux/scripts/installers/clang.sh#L43

Windows: I'm not sure where the windows clang installer is or if it has a clang installer at all. It would be nice if they matched with the unix instances. I'm no powershell hero so reluctant to send a PR.

**Comment by sbeyer** [comment]
> Windows: I'm not sure where the windows clang installer is or if it has a clang installer at all. It would be nice if they matched with the unix instances. I'm no powershell hero so reluctant to send a PR.

```
> C:\msys64\mingw64\bin\clang-format --version
clang-format version 10.0.0 (https://github.com/msys2/MINGW-packages.git 7211ffb882cc3b7e7583c518aad45a22b278bc81)
```

**Comment by MSP-Greg** [comment]
clang-tidy is part of the following package:

```
$ pacman -Si mingw-w64-x86_64-clang-tools-extra
Name            : mingw-w64-x86_64-clang-tools-extra
Version         : 10.0.0-3
Description     : Extra tools built using Clang's tooling APIs (mingw-w64)
Depends On      : mingw-w64-x86_64-gcc  mingw-w64-x86_64-uasm
Optional Deps   : None
Conflicts With  : None
Replaces        : None
Download Size   : 54.89 MiB
Installed Size  : 588.66 MiB
Packager        : Alexey Pavlov <alexpux@gmail.com>
Build Date      : Mon, Jul 13, 2020 1:24:29 AM
Validated By    : MD5 Sum  SHA-256 Sum  Signature
```

I don't use clang much, so I don't know whether clang-tidy should be pre-installed.

**Comment by zufuliu** [comment]
See https://github.com/actions/virtual-environments/issues/921#issuecomment-632970858
you can installer official LLVM with
```
curl -fsSL -o "LLVM-10.0.0-win64.exe" "https://github.com/llvm/llvm-project/releases/download/llvmorg-10.0.0/LLVM-10.0.0-win64.exe"
LLVM-10.0.0-win64.exe /S
```

**Comment by andy-mishechkin** [comment]
Hello, @sbeyer 
Do you need clang-tidy x64 version only ?
Should we also install x32 version package of this utility ?

Thank You.

**Comment by sbeyer** [comment]
I, personally, do not need it. I mean…is there any benefit in having a x32 version?

**Comment by andy-mishechkin** [comment]
I think, only if somebody will want to build x32 application using clang.
Ok, if you don't mind - we will deploy x64 version only. I think you will find clang-tidy after next Windows image deployment (about on the next week).
Thank you.

**Comment by andy-mishechkin** [comment]
This feature has been added to Win19 image and should be available on the next week

**Comment by andy-mishechkin** [comment]
Win19 image has been checked. clang-tidy.exe is present.
