### ISSUE TITLE
Update -- Google_Cloud_Sdk software -- Components

### ISSUE THREAD

**Issue by sandeepnandula** [actions/virtual-environments#1172]
**Tool information**
- Tool name: Google cloud sdk

- Add or update? Update

- If this is an add request:
  - Brief description of tool: We started working on google_cloud_sdk software. But whenever we have to run something related the sdk. Every-time we need to install the components manually. It would be helpful if you guys add the Google_Cloud_Sdk software with pre-installed components.

**Virtual environments affected**
- [ 👍 ] Ubuntu latest

**Comment by Darleev** [comment]
Hello @sandeepnandula,
Could you provide required components for you and the installation time that they take?
We look forward to hearing from you.

**Comment by sandeepnandula** [comment]
Hello @Darleev Thank you for the quick response. 
I've listed down below the components that I'm trying to add.
* google-cloud-sdk-datastore-emulator
* google-cloud-sdk-app-engine-python
* google-cloud-sdk-app-engine-python-extras.

It's taking around 1min : 40sec to install the SDK components.

**Comment by Darleev** [comment]
@sandeepnandula thank you for the provided information. 
We will consider the possibility to add these tools to the images.

**Comment by maxim-lobanov** [comment]
Hello @sandeepnandula ,
Sorry, but we wouldn't like to pre-install this tool to images for now. Recently, we had some issues with free space on Ubuntu images so we have to be very selective about adding new tools.

We will be happy to revise this decision in future if we see more requests and don't have free space issue.
