### ISSUE TITLE
Update Windows Server 2019 Container image to 1909

### ISSUE THREAD

**Issue by markmssd** [actions/virtual-environments#1174]
**Tool information**
- Tool name: Container OS Version 1909
- Tool license: 
- Add or update? Update
- Desired version: 1909
- Approximate size: 
- If this is an add request:
  - Brief description of tool: 
  - URL for tool's homepage: 

**Area for Triage**:
Containers

**Question, Bug, or Feature?**:
Feature

**Virtual environments affected**
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Ubuntu 20.04 LTS
- [ ] Windows Server 2016 R2
- [x] Windows Server 2019

**Can this tool be installed during the build?**
No

**Tool installation time in runtime**

**Are you willing to submit a PR?**
Yes, I can try!

This issue was originally opened here https://github.com/microsoft/azure-pipelines-image-generation/issues/1457

**Comment by Darleev** [comment]
Hello @markmssd,
Thank you for the improvement request.
As far as I see in [the documentation](https://docs.microsoft.com/en-us/virtualization/windowscontainers/deploy-containers/version-compatibility?tabs=windows-server-2019%2Cwindows-10-2004), **Container base image OS version** Windows Server, version 1909 is not compatible with Windows Server 2019.
Could you provide more information about this feature and its usage scenarios?

**Comment by markmssd** [comment]
Oh alright, thanks for the quick reply! I've needed `1909` because I thought it was [needed](https://cloud.google.com/kubernetes-engine/docs/how-to/creating-a-cluster-windows#choose_your_windows_server_node_image) to run on Google Cloud GKE, but then I saw other examples in which they use older versions as well. I guess this this issue can be closed then.
