### ISSUE TITLE
Windows OS command fails when referenced through its symbolic link 

### ISSUE THREAD

**Issue by WhisperingChaos** [actions/virtual-environments#1177]
**Describe the bug**
Attempting to run a Windows ```.cmd``` file through a relative symbolic link appearing within a git repository produces unexpected behavior - that may or may not immediately fail.  The relative link refers to a file contained in the repo.   After installing this git repo into the Windows virtual environment via ```actions/checkout@v2```, the symbolic link is converted into an _actual_ file whose content reflects the link reference, not the content of the file targeted by the link.  Therefore, attempting to run the ```.cmd``` file executes the link reference instead of dereferencing it to execute the content of the actual file.  Furthermore, the command arguments specified on the call aren't forwarded by the link reference.

**Area for Triage**: git

**Question, Bug, or Feature?**: Bug

**Virtual environments affected**
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Ubuntu 20.04 LTS
- [ ] Windows Server 2016 R2
- [x] Windows Server 2019

**Expected behavior**
Given a git repository containing a link file that's copied into a Windows virtual environment via ```actions/checkout@v2```, executing  the command ```dir /al``` via a github actions ```run:``` yaml keyword should display the file as a ```<SYMLINK>```.

**Actual behavior**
The link file is converted into a basic file and executing ```dir /al``` within a git repository directory displays the file as just a file.

A description with steps to reproduce the issue. If your have a public example or repo to share,
please provide the link.

1. The github repo [symbolicLink](https://github.com/WhisperingChaos/symbolicLink) contains a sample of the problem.
2.  Fork the project.
3. Commit an update.
4. View the output of its CI workflow.

The output below was generated by this [workflow](https://github.com/WhisperingChaos/symbolicLink/blob/master/.github/workflows/blank.yml):

```

0s
Hello World 
Run actualBehavior.cmd

Simple dir command to show files


d:\a\symbolicLink\symbolicLink\test>dir
 Volume in drive D is Temporary Storage
 Volume Serial Number is 1EA7-C472

 Directory of d:\a\symbolicLink\symbolicLink\test

07/05/2020  02:54 AM    <DIR>          .
07/05/2020  02:54 AM    <DIR>          ..
07/05/2020  02:54 AM               431 actualBehavior.cmd
07/05/2020  02:54 AM               482 expectedBehavior.cmd
07/05/2020  02:54 AM                27 helloworld.cmd
               3 File(s)            940 bytes
               2 Dir(s)  13,098,856,448 bytes free

Limit dir to only symbolic links. 
Notice no files reported, although
helloWorld.cmd should appear as one.


d:\a\symbolicLink\symbolicLink\test>dir /al 
 Volume in drive D is Temporary Storage
 Volume Serial Number is 1EA7-C472```

```

```
0s
Hello World Arg2-1 Arg2-2
Patch behavior by recreating symbolic link.


d:\a\symbolicLink\symbolicLink\test>del helloWorld.cmd 

d:\a\symbolicLink\symbolicLink\test>mklink  helloWorld.cmd ..\component\helloWorld.cmd 
symbolic link created for helloWorld.cmd <<===>> ..\component\helloWorld.cmd

Command now properly reports file as a symbolic link.


d:\a\symbolicLink\symbolicLink\test>dir /al 
 Volume in drive D is Temporary Storage
 Volume Serial Number is 1EA7-C472

 Directory of d:\a\symbolicLink\symbolicLink\test

07/05/2020  02:54 AM    <SYMLINK>      helloWorld.cmd [..\component\helloWorld.cmd]
               1 File(s)              0 bytes
               0 Dir(s)  13,098,852,352 bytes free

Executing command through link now properly forwards
arguments (Arg2-1 Arg2-2) to actual command and
produces expected behavior.


d:\a\symbolicLink\symbolicLink\test>helloWorld.cmd Arg2-1 Arg2-2 
Hello World Arg2-1 Arg2-2
```

The symlink behavior above seems related to this [ Docker for Windows #5778](https://github.com/docker/for-win/issues/5778) issue.

**Comment by al-cheb** [comment]
Hello, @WhisperingChaos
This behavior is by design `core.symlinks=false` - https://github.com/git-for-windows/git/wiki/Symbolic-Links. I am planning to prepare a pr with `core.symlinks=true` by default.

```
    steps:
      - name: core.symlinks
        run: |
          git config --global core.symlinks true
      - name: Checkout tools repo
        uses: actions/checkout@v2
        with:
          repository: WhisperingChaos/symbolicLin
```
![image](https://user-images.githubusercontent.com/47745270/86589484-7361a480-bf96-11ea-9afd-de66501b3210.png)

**Comment by WhisperingChaos** [comment]
@al-cheb Many thanks for your speedy reply, link to web page explaining the "by design" reasoning, providing the git config option to circumvent it, and future patch to resolve this issue!  Fantastic!  You provided a much better experience than many of ones I encountered for products that I purchased!

**Comment by al-cheb** [comment]
Hello, @WhisperingChaos 
We have deployed a new image with the  `/o:EnableSymlinks=Enabled` parameter is enabled by default - https://github.com/actions/virtual-environments/pull/1186/files.

```
jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout tools repo
        uses: actions/checkout@v2
        with:
          repository: WhisperingChaos/symbolicLink
      - name: dir SYMLINK
        shell: cmd
        run: dir /al test
```


![image](https://user-images.githubusercontent.com/47745270/88145916-d80e3780-cc03-11ea-9f99-c8fe88f73b78.png)

Feel free to open the thread if you have any concerns.
