### ISSUE TITLE
Download a binary and add it to PATH on Windows

### ISSUE THREAD

**Issue by michalb-dsg** [actions/virtual-environments#1179]
**Describe the bug**
I'm trying to run python tests on a Windows environment. These tests are using one application client. To run these tests, I have a step that installs this client binary before running these tests.
```
- name: Install minio client
  if: startsWith(runner.os, 'Windows')
  run: |
      curl "https://dl.min.io/client/mc/release/windows-amd64/mc.exe" --output mc.exe
```
Now I have to add this client to PATH. I tried to run this:
```
- name: Add minio client to path
  if: startsWith(runner.os, 'Windows')
  run: |
      echo "::add-path::$GITHUB_WORKSPACE\mc.exe"
```
but I don't think it worked because my tests have failed due to a missing minio client.

**Area for Triage**: Scripting and command line

**Question, Bug, or Feature?**: Bug\Question

**Virtual environments affected**
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Ubuntu 20.04 LTS
- [ ] Windows Server 2016 R2
- [X] Windows Server 2019

**Expected behavior**
When setting `mc.exe` to PATH, tests won't fail.

What am I doing wrong? Thanks :slight_smile:

**Comment by maxim-lobanov** [comment]
@michalb-dsg , PATH is intended for directory PATHs, not binary PATHs.
Please try `echo "::add-path::$GITHUB_WORKSPACE"`.

**Comment by michalb-dsg** [comment]
@maxim-lobanov, thank you for your quick response.
I tried `echo "::add-path::$GITHUB_WORKSPACE"`.

This is what I got:

##[error]Value cannot be null. (Parameter 'path')
Run echo "::add-path::$GITHUB_WORKSPACE"
##[error]Unable to process command '::add-path::' successfully.
##[error]Value cannot be null. (Parameter 'path')

**Comment by al-cheb** [comment]
@michalb-dsg , You should use `env:` for PowerShell/PowerShell Core shell:

```
- name: add to the path
        run: |
          echo "::add-path::${env:GITHUB_WORKSPACE}"
      - name: test
        run: |
          curl "https://dl.min.io/client/mc/release/windows-amd64/mc.exe" --output "mc.exe"
```
![image](https://user-images.githubusercontent.com/47745270/86576203-15769200-bf81-11ea-81c3-8d0cfd8ad88c.png)

**Comment by michalb-dsg** [comment]
@al-cheb thanks, this was very helpful. Where in the documentation there is a reference to placing `env` before the actual environment variable? 
I looked in [here](https://docs.github.com/en/actions/configuring-and-managing-workflows/using-environment-variables) and in [here](https://docs.github.com/en/actions/reference/workflow-commands-for-github-actions#adding-a-system-path)

**Comment by al-cheb** [comment]
@michalb-dsg, Different shells have different syntax for accessing environment variables, and different OSes have different default shells(Windows - pwsh; macOs/Ubuntu - bash). I honestly don't know why all examples are provided only for `bash` shell. I think the better place to ask the question is - https://github.community/.

Set up `bash` shell for current task:
```
- name: Add minio client to path
  shell: bash
  if: startsWith(runner.os, 'Windows')
  run: |
        echo "::add-path::$GITHUB_WORKSPACE"
```

bash env: https://www.digitalocean.com/community/tutorials/how-to-read-and-set-environmental-and-shell-variables-on-a-linux-vps
powershell: https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_environment_variables?view=powershell-7

**Comment by maxim-lobanov** [comment]
@michalb-dsg , Does proposed solution work for you?

**Comment by al-cheb** [comment]
Feel free to open the thread if you have any concerns.
