### ISSUE TITLE
The composer global bin path isn't added to `$PATH`

### ISSUE THREAD

**Issue by georgeboot** [actions/virtual-environments#118]
**Describe the bug**
The composer global bin path isn't added to `$PATH`

**Virtual environments affected**
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [x] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Expected behavior**
The composer global path (`/home/worker/.composer/vendor/bin`) is added to the `$PATH`.

**Actual behavior**
It isn't in the path. and thus you have to call globally installed executables with their full path. As this might change some day, this isn't ideal.

Note that I have only tested this on 18.04, but it's likely an issue on the other environments too.

**Comment by vsafonkin** [comment]
PR: [#391](https://github.com/actions/virtual-environments/pull/391)

**Comment by vsafonkin** [comment]
Hello @georgeboot , unfortunately, adding "export PATH" command to user's .bashrc file didn't resolve problem, we will continue to work on it.

**Comment by georgeboot** [comment]
Hmm that is strange. Sure it's added to the correct rc file?

**Comment by vsafonkin** [comment]
Yes, user's bashrc contains export instruction, but it works only with terminal session, if we use image for ci it's not working ((

**Comment by vsafonkin** [comment]
PR: [https://github.com/actions/virtual-environments/pull/477](https://github.com/actions/virtual-environments/pull/477)

**Comment by vsafonkin** [comment]
The path `/home/runner/.config/composer/vendor/bin` was added into $PATH. It can use for Github Actions pipelines (user `runner`).

@georgeboot , I close this issue, please reopen it if you have any concerns, thanks!
