### ISSUE TITLE
Windows 2019: Powershell Start-ThreadJob cmdlet no longer working as expected in Azure DevOps Pipeline Using "windows-2019" VM

### ISSUE THREAD

**Issue by Bidthedog** [actions/virtual-environments#1193]
**Describe the bug**
I'm reporting this here as nothing has changed in my pipeline other than the virtual machine image that it runs in.

My pipeline builds have just (today) started to experience an issue with how some Powershell ThreadJob scheduling steps are handled; instead of scheduling jobs immediately and returning, jobs are now taking a considerable amount of time to schedule - more than the few seconds that they were taking previously.

FYI I'm using the ThreadJob module from here: https://www.powershellgallery.com/packages/ThreadJob/2.0.3

The MS documentation for `Start-ThreadJob` is different and makes no reference to the above github url: https://docs.microsoft.com/en-us/powershell/module/threadjob/start-threadjob?view=powershell-7

I'm running a script that includes the `Start-ThreadJob` code as part of a VS2019 msbuild `AfterBuild` target. It's therefore running in PowerShell 5.1.

To demonstrate what is happening, find logs below: there are two sections to the powershell script that deals with jobs

1) Scheduling
2) Checking all the jobs have completed in a loop.

Step 2 takes longer on a build agent than on my local machine, but my my main concern is that step 1 is now taking 5 minutes vs the few seconds it used to take.

The log output for the _working_ pipelines looks like this (note the timestamps for the SCHEDULING entries):

> 2020-07-06T15:04:42.7048507Z          VERBOSE: Scheduling form packing jobs in 'D:\a\1\s\MyFolder'
> 2020-07-06T15:04:42.7082147Z          VERBOSE: JOB | SCHEDULING | 'Job1'
> 2020-07-06T**15:04:42.7467868Z**          VERBOSE: JOB | SCHEDULING | 'Job2'
> ...
> 2020-07-06T**15:04:48.6351895Z**          VERBOSE: JOB | SCHEDULING | 'Job60'
> 2020-07-06T15:04:48.6352212Z          VERBOSE: All form packing jobs scheduled
> 2020-07-06T15:04:48.6352445Z          VERBOSE: CHECKING JOBS | 88 remaining...
> 2020-07-06T15:04:48.6370273Z          VERBOSE: CHECKING JOBS | 88 remaining...
> 2020-07-06T15:05:11.5521026Z          VERBOSE: CHECKING JOBS | 74 remaining...
> 2020-07-06T15:05:16.3021392Z          VERBOSE: CHECKING JOBS | 72 remaining...
> ...
> 2020-07-06T15:05:49.5725860Z          VERBOSE: CHECKING JOBS | 1 remaining...
> 2020-07-06T15:05:50.5792811Z          VERBOSE: Reporting job status / cleaning up:

Whereas the new image now produces the following:

> 2020-07-07T12:13:15.2942132Z          VERBOSE: Scheduling form packing jobs in 'D:\a\1\s\MyFolder'
> 2020-07-07T12:13:15.3024705Z          VERBOSE: JOB | SCHEDULING | 'Job1'
> 2020-07-07T**12:13:15.3483135Z**          VERBOSE: JOB | SCHEDULING | 'Job2'
> ...
> 2020-07-07T**12:17:52.4890778Z**          VERBOSE: JOB | SCHEDULING | 'Job60'
> 2020-07-07T12:17:57.2379325Z          VERBOSE: All form packing jobs scheduled
> 2020-07-07T12:18:01.9871851Z          VERBOSE: CHECKING JOBS | 82 remaining...
> 2020-07-07T12:18:06.7366852Z          VERBOSE: CHECKING JOBS | 82 remaining...
> ...
> 2020-07-07T12:19:02.7206147Z          VERBOSE: CHECKING JOBS | 59 remaining...
> 2020-07-07T12:19:02.7208044Z          VERBOSE: CHECKING JOBS | 57 remaining...
> 2020-07-07T12:19:02.7208888Z          VERBOSE: ERR

OR: Job timeout (120 seconds)

Note that the timestamps for the SCHEDULING section now takes 5 minutes rather than just a few seconds.

For full context, the code that produces the above SCHEDULING output looks like this:

```
    $alljobs = Get-ChildItem -Path $myDir -Directory | ForEach-Object {
        "JOB | SCHEDULING | '$($_.Name)'";
        Start-ThreadJob -Name "$($_.Name)" -ArgumentList $_.FullName -ScriptBlock {
            # Execute job code...
            ...
        } -ThrottleLimit $JobThrottleLimit;
        "JOB | SCHEDULED | '$($_.Name)'";
    };
    "All form packing jobs scheduled";
```

As this has only just started happening today, I believe it might be related to this PR:

https://github.com/actions/virtual-environments/pull/1157

The pipelines that have worked are reporting the following in the job initialisation step:

```
Starting: Initialize job
Agent name: 'Hosted Agent'
Agent machine name: 'fv-az8'
Current agent version: '2.171.1'
Operating System
Microsoft Windows Server 2019
10.0.17763
Datacenter
Virtual Environment
Environment: windows-2019
Version: 20200621.1
Included Software: https://github.com/actions/virtual-environments/blob/win19/20200621.1/images/win/Windows2019-Readme.md
Current image version: '20200621.1'
Agent running as: 'VssAdministrator'
##[debug]Triggering repository: Client.Product. repository type: Git
Prepare build directory.
##[debug]Creating build directory: 'd:\a\1'
##[debug]Delete existing artifacts directory: 'd:\a\1\a'
##[debug]Creating artifacts directory: 'd:\a\1\a'
##[debug]Delete existing test results directory: 'd:\a\1\TestResults'
##[debug]Creating test results directory: 'd:\a\1\TestResults'
##[debug]Creating binaries directory: 'd:\a\1\b'
##[debug]Creating source directory: 'd:\a\1\s'
Set build variables.
Download all required tasks.
Downloading task: PowerShell (2.170.1)
```

The pipelines that have increased the Start-ThreadJob schedule execution, report the following:

```
Starting: Initialize job
Agent name: 'Hosted Agent'
Agent machine name: 'fv-az8'
Current agent version: '2.171.1'
Operating System
Microsoft Windows Server 2019
10.0.17763
Datacenter
Virtual Environment
Environment: windows-2019
Version: 20200630.0
Included Software: https://github.com/actions/virtual-environments/blob/win19/20200630.0/images/win/Windows2019-Readme.md
Current image version: '20200630.0'
Agent running as: 'VssAdministrator'
##[debug]Triggering repository: Client.Product. repository type: Git
Prepare build directory.
##[debug]Creating build directory: 'd:\a\1'
##[debug]Delete existing artifacts directory: 'd:\a\1\a'
##[debug]Creating artifacts directory: 'd:\a\1\a'
##[debug]Delete existing test results directory: 'd:\a\1\TestResults'
##[debug]Creating test results directory: 'd:\a\1\TestResults'
##[debug]Creating binaries directory: 'd:\a\1\b'
##[debug]Creating source directory: 'd:\a\1\s'
Set build variables.
Download all required tasks.
Downloading task: PowerShell (2.170.1)
```

The .md files referenced in the build log brought me here. As you can see, they are different - I believe image `20200630.0` is causing the issues. I do not see any changes to the related module or powershell versions that may affect this in the .md files.

**Area for Triage**: 
.NET Framework

**Question, Bug, or Feature?**: 
Bug

**Virtual environments affected**
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Ubuntu 20.04 LTS
- [ ] Windows Server 2016 R2
- [x] Windows Server 2019

**Expected behavior**
The same behaviour as yesterday!

**Actual behavior**
See description above.

**Comment by Bidthedog** [comment]
Turns out this *might* be related to an Azure DevOps hosted agent issue that my region is currently experiencing:

https://status.dev.azure.com/

I shall let you know if the behaviour keeps happening after the issue is resolved.

**Comment by MaksimZhukov** [comment]
Hello @Bidthedog , thanks for the your report!
Based on [this PR](https://github.com/actions/virtual-environments/pull/1157) we can confirm that we do not have any changes in our `Windows 2019` image that could cause this issue. As far as I see on [this page](https://www.powershellgallery.com/packages/ThreadJob/2.0.3) the `ThreadJob` module has not been updated for 6 months. Probably your issue is related to an Azure DevOps hosted agent issue.
Please keep us updated, we are looking forward to your reply!

**Comment by MaksimZhukov** [comment]
Hello @Bidthedog !
Could you please let us know if you still see the same issue?
Thanks!

**Comment by Bidthedog** [comment]
No, it's working fine now - it was related to the MS Hosted Agent degradation issues, which unfortunately lasted for around two weeks.

The issues have since been resolved and the jobs are performing optimally again.

Thanks for your updates, and apologies for not getting back to you sooner! Closing :)
