### ISSUE TITLE
help

### ISSUE THREAD

**Issue by ojedavidea** [actions/virtual-environments#1197]
is there any tutorial in understandable english to help create actions (automations) for :
- attributing milestone(s) to a pull request upon specific editing (related to specific line(s) in the file or to specific expression newly added) of a specific repository file ;
- attributing label(s) to a pull request upon specific editing (related to specific line(s) in the file or to specific expression newly added) of a specific repository file ;
- attributing project element(s) to a pull request upon specific editing (related to specific line(s) in the file or to specific expression newly added) of a specific repository file.

**Comment by Darleev** [comment]
Hello @ojedavidea,
I'm not sure that I understood properly the main idea, but it seems you can use [GitHub Actions Workflow](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions) for your purposes.
It would be great if you provide examples/use cases for the mentioned points.
We are looking forward to your reply.

**Comment by ojedavidea** [comment]
if I have a file in my repository with at line 1 :

"name:"

and if I commit the change :

"name: Octocat"

I would like at pull-request to automatically give it

a label : "named"

and a Milestone : "identity"

and check the box : "name the file" in my project.

**Comment by maxim-lobanov** [comment]
Hello @ojedavidea , This repository is intended only for content of VM images and we don't own actions / tasks.

General advices on your issue:
1) I don't think that it is possible to attribute PRs based on changed code lines (at least, I didn't see such actions). It is only possible to attribute PRs based on changed files (if file `name.json` is changed, set specific label)
2) There is an official GH action to label PRs based on changed files: https://github.com/actions/labeler
3) You can use [marketplace search](https://github.com/marketplace?type=actions&query=) that contains a lot of community actions. For example, [action to set milestones](https://github.com/marketplace/actions/pull-request-milestone) to PRs based on changed files (didn't use it before, just found in search).
4) You may try to implement some automation / action by yourself using the following approach:
- Subscribe action on [pull-request opened](https://docs.github.com/en/actions/reference/events-that-trigger-workflows#pull_request) event
- Analyze the list of changed files
- Set labels, projects, milestones using [actions/github-script](https://github.com/actions/github-script)

**Comment by ojedavidea** [comment]
Thank you for the advice, I will try to use script.

But I don't understand how actions can perform code reviews if they don't analyze the lines of code and if they only check the file name as you explained ? How can they "know" editing a file contained errors or was successful, on what are these checks based on? I thought that I could manage how the checks perform with automations but according to you I will need to check myself 'manually' the file for errors and then (when?) in between the action's process, 'make use' of the scripts for labels, milestones and projects according to the workflow file? But then I don't understand how can I parameter the way actions perform if errors in files are "submitted manually" at each pull request? Is that correct ? It seems weird thought, I thought actions were fully automated and way easier to use. Thanks.

**Comment by maxim-lobanov** [comment]
Actions is CI/CD system so you can configure "Checks" for your pull-requests. When someone submit pull-requests, checks will be run. Checks is just builds that are run on source code in particular branch. They can build your application, run tests, do any other actions. Please see a bunch of examples here: https://github.com/actions/starter-workflows/tree/master/ci
So if your application has tests, you may run them to make sure that code in PR is healthy but Action doesn't really analyze the diff of PR. It just runs check on particular branch (source branch where PR was done from).

**Comment by ojedavidea** [comment]
Thank you! So to make sure my code in my pull request is what I want it to be, I must create builds that should match to my code during runs (workflow, steps, actions...), if not then it returns the error, am I right? Where do I find and manage my builds on github?

I am also missing the part where builds are specified in the workflow file? Thank you, and I am sorry that I don't understand all this faster.

**Comment by maxim-lobanov** [comment]
Exactly, 
The good example - this repository. It contains source code for VM image-generation. If you submit [PR](https://github.com/actions/virtual-environments/pulls), the automatic checks will be run. These checks will start image-generation based on your branch. If builds pass successfully, we will merge it. If your branch contains invalid changes, image-generation will fail and will prevent PR from merging.
![image](https://user-images.githubusercontent.com/16715858/86903054-78019680-c117-11ea-8cdb-7e49b1fc9d63.png)

I don't have context with your environment so can't suggest good check for that.
I suggest to start with [official documentation for GitHub Actions](https://docs.github.com/en/actions/configuring-and-managing-workflows/configuring-a-workflow) and also you can create question on [GitHub Actions community forum](https://github.community/c/github-actions/41). This repository is intended for narrow part of GitHub Actions - VM images but community forum is intended for general questions like that and probably, someone has already faced with the same goal like you have and could help

**Comment by ojedavidea** [comment]
I am sorry but I am being restricted in the community forum and I can't get help there anymore. I have been trying to create several workflows files to try this but it is still ending with an error. Here is all what i have been trying documented in the forum:
`https://github.community/t/please-impossible-to-add-label-milestone-and-project-with-actions/121804`

[https://github.community/t/please-impossible-to-add-label-milestone-and-project-with-actions/121804](https://github.community/t/please-impossible-to-add-label-milestone-and-project-with-actions/121804)
