### ISSUE TITLE
Add libpq-dev

### ISSUE THREAD

**Issue by swanson** [actions/virtual-environments#12]
**Tool information**
- Tool name: libpq-dev
- Add or update? add
- Desired version: whatever is latest
- Approximate size: 
- If this is an add request:
  - Brief description of tool: `libpq-dev` is a C library for interfacing with Postgres; it is commonly needed for Ruby/Rails environments that create and interact with a database as part of test suites
  - URL for tool's homepage: https://www.postgresql.org/docs/9.5/libpq.html

**Virtual environments affected**
- [ ] macOS 10.14
- [x] Ubuntu 16.04 LTS
- [x] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Can this tool be installed during the build?**
Current workaround is to install manually via `apt-get` -- this adds 1-2 minutes to the workflow time and has to be repeated for every build

**Comment by dmitry-shibanov** [comment]
Hello, pull request with adding libpq-dev was merged and changes will be deployed with next rollout.

**Comment by dmitry-shibanov** [comment]
Hello, libpq-dev was added to ubuntu images. If you have any issue with it please feel free to reopen it.
