### ISSUE TITLE
Update Android NDK on macOS to r20+

### ISSUE THREAD

**Issue by saurik** [actions/virtual-environments#120]
**Tool information**
- Tool name: Android NDK
- Add or update? Update
- Desired version: r19 or r20 (or later)
- Approximate size: 3GB

**Virtual environments affected**
- [X] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Can this tool be installed during the build?**
I do not know, but it is very large and is installed correctly on Ubuntu.

**Are you willing to submit a PR?**
So, I don't see any scripts for generating the macOS system images?

---

Right now, the version of the Android NDK on macOS is 18.1.5063045, which is notably old as Google made a massive change to how the toolchains worked in r19 (moving away from their "standalone toolchain" generation process) and also is still using llvm/clang 7 (newer NDKs moved to llvm/clang 8).

The GitHub Actions Ubuntu machines are documented to be running 20.0.5594570 (I haven't checked), but if that is the case, it might also be good to update all of your machines to r20b, which was pushed to fix what I believe was considered a rather critical flaw in the security properties of std::random.

(One thing to note is that the Android SDK itself has moved to a new way of shipping the NDK as of somewhere between r19 and r20: they now support side-by-side deployment of multiple versions of the NDK at the same time, so if you actually need r18 for some legacy reason, you could do r20 side-by-side.)

**Comment by saurik** [comment]
Apparently, if I don't leave a comment every now and then, the "github-actions" bot will decide the bug has somehow magically been fixed (by gnomes? I don't understand how that makes any sense); so... "bump: GitHub is still shipping an ancient version of the Android NDK--r18, which notably has disclosed security issues--even though there is an r21 LTS version available and particularly even though r22 is soon to be released which will be entirely removing all of the compatibility support for pre-r19 NDK builds, which have been pretty firmly deprecated by Google now for well over a year".

**Comment by martinbonnin** [comment]
This comment to reset the Github gnomes timeout 🙃....

I'm interested by that too.

**Comment by martinbonnin** [comment]
Looks like it can be done manually. See https://github.com/HearthSim/Arcane-Tracker/commit/5533dbb9f37b95b633f05b148777b82317fa9399

**Comment by maxim-lobanov** [comment]
Hello @martinbonnin , we are planning to do this issue, it is on our backlog.
As a temporary workaround, manual installation can be used

**Comment by AlenaSviridenko** [comment]
Hi! Image with updated Android NDK was fully deployed. I am closing this issue. 
If you have any questions or concerns - please, feel free to file the new one.

Thanks!
