### ISSUE TITLE
Checkout does not behave consistently accross pipelines (lfs)

### ISSUE THREAD

**Issue by FrancescElies** [actions/virtual-environments#1201]
**Describe the bug**
Checkout step does not behave consistently with lfs files, sometimes they are pulled, sometimes not.
Migth this be somehow releated to #1064?

**Area for Triage**: 
Git

**Question, Bug, or Feature?**: 
Bug

**Virtual environments affected**
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Ubuntu 20.04 LTS
- [x] Windows Server 2016 R2
- [ ] Windows Server 2019

**Expected behavior**
On lfs false I don't want to retrieve lfs data.

**Actual behavior**
Following snippet sometimes pulls lfs files and sometimes doesn't
```
- checkout: self
    clean: true
    persistCredentials: true 
```
[This build checkout step](https://mbbm-ast.visualstudio.com/AST/_build/results?buildId=35212&view=logs&j=da3f1522-b1d0-563d-800b-8c4df30186bc&t=fd0ef5c8-21fd-52ad-351d-339e0a02bed7): pulls lfs files even though lfs defaults to false. 

[This build checkout step](https://mbbm-ast.visualstudio.com/AST/_build/results?buildId=35214&view=logs&j=da3f1522-b1d0-563d-800b-8c4df30186bc) does **not** pull lfs files, which is correct and showed an error on my pipeline setup. That's why this build failed.

**Comment by miketimofeev** [comment]
Hi @FrancescElies!
Unfortunately, we don't have access to the logs so could you please provide them here?

**Comment by miketimofeev** [comment]
And am I right that this setting is disabled in GUI or do you use yml templates?
![image](https://user-images.githubusercontent.com/48208649/87009118-67135c80-c1cd-11ea-941b-4d4e142136bb.png)

**Comment by FrancescElies** [comment]
I had troubles to find this setting but finally I did.

@miketimofeev well spotted, one pipeline had checkout files from lfs checkbox marked and the other one didn't.


Closing this issue, this was a missconfiguration on our side.
