### ISSUE TITLE
Add Swig

### ISSUE THREAD

**Issue by dot-asm** [actions/virtual-environments#1203]
**Tool information**
- Tool name: swig
- Tool license: GPL
- Add or update? add
- Desired version: 4.0.x
- Approximate size: 6MB
- If this is an add request:
  - Brief description of tool: connects programs written in C and C++ with a variety of high-level programming languages
  - URL for tool's homepage: http://swig.org/

**Area for Triage**: Scripting and command line

**Question, Bug, or Feature?**: Feature

**Virtual environments affected**
- [ ] macOS 10.15
- [x] Ubuntu 16.04 LTS
- [x] Ubuntu 18.04 LTS
- [x] Ubuntu 20.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Can this tool be installed during the build?** It's available pre-packaged for Ubuntu, so it's possible to simply apt-get it.

**Tool installation time in runtime** negligible, in fact one can apt-get it on per-job basis, having it pre-installed simply makes life a little easier.

**Are you willing to submit a PR?**

**Comment by nikita-bykov** [comment]
Hello @dot-asm! Your desired version of Swing is 4.0.x. We investigated that when installing Swing using apt-get, we got the following results:

- On Ubuntu 16.04 - we got SWIG Version 3.0.8
- On Ubuntu 18.04 - we got SWIG Version 3.0.12
- On Ubuntu 20.04 - we got SWIG Version 4.0.1

Is it expected for you?

**Comment by dot-asm** [comment]
Yes. As mentioned in request, pre-packaged version as available through apt-get is what I'm looking for. I suppose I could have filled "3.0.x-4.0.x" as "desired version" in request form... Sorry about confusion :-) Thanks!

**Comment by nikita-bykov** [comment]
We have added Swig installation to Ubuntu.
Images with it will be rolled out around next week.

**Comment by dot-asm** [comment]
Cool! Much appreciated:+1: Thanks!

**Comment by maxim-lobanov** [comment]
@dot-asm , I have reopened.
We usually keep issue in opened state until new image is deployed

**Comment by dot-asm** [comment]
Oh! You'll handle the closing yourself. Got it! Thanks again!

**Comment by miketimofeev** [comment]
@dot-asm Ubuntu 16&18 images were deployed with swig 3 and Ubuntu 20 with swig 4.
I'm going to close the issue, but feel free to contact us if you have any concerns.
Thank you!

**Comment by zllovesuki** [comment]
Is it possible to add Swig to Windows Environment as well?

**Comment by maxim-lobanov** [comment]
@zllovesuki , feel free to create an issue for that and we will consider adding it to Windows too.
