### ISSUE TITLE
windows-latest environment running much slower since 20200630.0

### ISSUE THREAD

**Issue by beechtom** [actions/virtual-environments#1204]
**Describe the bug**
Workflows running on windows-latest environment are running about 2-3x slower than usual since the release of 20200630.0

**Area for Triage**: 
Servers

**Question, Bug, or Feature?**: 
Bug

**Virtual environments affected**
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Ubuntu 20.04 LTS
- [ ] Windows Server 2016 R2
- [x] Windows Server 2019

**Expected behavior**
New releases of Windows environments should not result in significantly slower workflows.

**Actual behavior**
Since the release of 20200630.0, workflows running on windows-latest have been running much slower than usual. Compare the following jobs run for the same pull request with minor changes between commits:

**20200630.0:** https://github.com/puppetlabs/bolt/runs/846247387?check_suite_focus=true
**20200621.1:** https://github.com/puppetlabs/bolt/runs/825368164?check_suite_focus=true

Several steps saw a noticeable increase in time to complete:
- Checkout takes 3x longer, from 8s to 22s
- Running a custom setup script takes 2x longer, from 13s to 23s
- Running tests with rspec takes 3x longer, from 13m to 38m
- Post-checkout takes 5x longer, from 3s to 16s

The overall time for job completion increased ~3.5x from an average of ~8m to an average of ~30m.

**Comment by Darleev** [comment]
Hello @beechtom,
As far as I can see, an only agentless job is slow, agentful job takes the same amount of time.
We will investigate the issue.

**Comment by vsafonkin** [comment]
Hi @beechtom ,
I've checked your build on next release image [20200706.1](https://github.com/actions/virtual-environments/releases/tag/win19%2F20200706.1) and build time is ~11 min: [action run](https://github.com/vsafonkin/bolt/runs/853608853?check_suite_focus=true)

This version will be available soon and your issue will be solved. Thanks!

**Comment by beechtom** [comment]
@vsafonkin Great to hear, thanks for looking into this!

**Comment by vsafonkin** [comment]
Hi @beechtom , new image release for windows-2019 is available, please, check your builds.

**Comment by beechtom** [comment]
@vsafonkin Everything is back to normal with our builds. Thanks!
