### ISSUE TITLE
Update/Add [Visual Studio 2015]

### ISSUE THREAD

**Issue by Farhanfdema** [actions/virtual-environments#1214]
**Tool information**
- Tool name: Visual Studio
- Tool license: 
- Add or update? Add
- Desired version: 2015
- Approximate size: 
- If this is an add request:
  - Brief description of tool: We have some legacy code that needs to be migrated to azure devops. Recently the 2015 agents were removed. But the code we have builds on 2015 versions, and unfortunately so far the code only works on 2015 visual studio. Anyway i can get 2015 visual studio on an agent?

**Comment by AlenaSviridenko** [comment]
HI @Farhanfdema,
we already have a request to add VS 2015 to Windows 2016 image https://github.com/actions/virtual-environments/issues/387, but unfortunately there is no ETA for it now. Please, track request in the issue I attached. 
Closing this one as a duplicate.

Thanks!
