### ISSUE TITLE
apt-get install may ask questions and hang

### ISSUE THREAD

**Issue by greghudson** [actions/virtual-environments#122]
**Describe the bug**
Even though apt-get -y says it runs non-interactively, Debian packages can still ask questions via the default front-end. On github action's current Ubuntu runners, this will generally cause a job's setup stage to hang until it times out.

**Virtual environments affected**
- [ ] macOS 10.15
- [X] Ubuntu 16.04 LTS
- [X] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Expected behavior**
The default front-end should be set to "noninteractive" to disable questions.  Travis does this through a combination of setting DEBIAN_FRONTEND=noninteractive in the environment and configuring sudo to preserve that variable (https://github.com/travis-ci/travis-cookbooks/commit/fa89acd4d3a28bc6a808e054d59d845f5a8794e4). It is also possible to do this via the debconf configuration (dpkg-reconfigure debconf).

**Actual behavior**
Try putting "sudo apt-get -y install slapd" in a job step, and observe that the job hangs until timeout.  "sudo DEBIAN_FRONTEND=noninteractive apt-get -y install slapd" works, but should not be necessary.

**Comment by oldskool** [comment]
With what package are you noticing this behavior? I noticed the following output on an Ubuntu 18.04 runner in one of my pipelines (while installing `cmake`) that seems to suppress question dialogs:

```
debconf: unable to initialize frontend: Dialog
debconf: (Dialog frontend will not work on a dumb terminal, an emacs shell buffer, or without a controlling terminal.)
debconf: falling back to frontend: Readline
debconf: unable to initialize frontend: Readline
debconf: (This frontend requires a controlling tty.)
debconf: falling back to frontend: Teletype
```

And then after that it just continues like normal.

**Comment by greghudson** [comment]
We observed the problem when installing slapd (as mentioned at the end of the issue report).  I put together some simple demonstrations for 16.04 and 18.04 runners; see:

  https://github.com/greghudson/virtual-environments/commit/a9cf779e964a07d9ab94f58774c381baf94cfa59/checks?check_suite_id=345870796
  https://github.com/greghudson/virtual-environments/commit/fea683f10464d693c6c3adc1430c2f2530579937/checks?check_suite_id=345885585

**Comment by al-cheb** [comment]
Hello, @greghudson 
Thank for your time to reporting about the issue.

I have prepared  https://github.com/actions/virtual-environments/pull/366 PR.  It will be included in the next rollouts.

**Comment by miketimofeev** [comment]
@greghudson the image has been deployed. Could you check apt-get install, please?

**Comment by greghudson** [comment]
Yes, the fix works for me for installing the slapd package.
