### ISSUE TITLE
PyPy error on latest Ubuntu 18.04 packer json

### ISSUE THREAD

**Issue by mihsoft** [actions/virtual-environments#1224]
**Describe the bug**

When running from Azure DevOps the following error is produced:

```
    azure-arm: - PyPy:

    azure-arm: Expected PyPy 2.7.* folder is not found!
```

**Area for Triage**: 

**Question, Bug, or Feature?**: 
Bug

**Virtual environments affected**
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [x ] Ubuntu 18.04 LTS
- [ ] Ubuntu 20.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Expected behavior**
packer script should run to completion without error

**Actual behavior**
Run packer script ubuntu1804.json

**Comment by maxim-lobanov** [comment]
@mihsoft , Hello, could you please provide build logs for `pypy.sh` step?

**Comment by mihsoft** [comment]
Hi maxim,

There does not appear to be anything in the build logs from the pypy.sh step,

The provision stage shows the script being included but it never gets executed
`==> azure-arm: Provisioning with shell script: /home/vsts/work/1/s/virtual-environments/images/linux/scripts/installers/pypy.sh
`
Immediately after the output for the python.sh shows
```
==> azure-arm: Provisioning with shell script: /home/vsts/work/1/s/virtual-environments/images/linux/scripts/installers/1804/android.sh

==> azure-arm: Provisioning with shell script: /home/vsts/work/1/s/virtual-environments/images/linux/scripts/installers/azpowershell.sh

==> azure-arm: Provisioning with shell script: /home/vsts/work/1/s/virtual-environments/images/linux/scripts/helpers/containercache.sh

==> azure-arm: Provisioning with shell script: /home/vsts/work/1/s/virtual-environments/images/linux/scripts/installers/hosted-tool-cache.sh

==> azure-arm: Provisioning with shell script: /home/vsts/work/1/s/virtual-environments/images/linux/scripts/installers/pypy.sh

==> azure-arm: Provisioning with shell script: /home/vsts/work/1/s/virtual-environments/images/linux/scripts/installers/python.sh

==> azure-arm: Provisioning with shell script: /home/vsts/work/1/s/virtual-environments/images/linux/scripts/installers/test-toolcache.sh

==> azure-arm: Provisioning with shell script: /home/vsts/work/1/s/virtual-environments/images/linux/scripts/installers/Install-Toolset.ps1

    azure-arm: Installing Python 2.7.* x64...

    azure-arm: Download python-2.7.18-linux-18.04-x64.tar.gz
```

**Comment by mihsoft** [comment]
Further investigation shows the the hosted-tool-cache.sh script doesn't appear to have run either although interestingly the python.sh script did run

**Comment by maxim-lobanov** [comment]
That is pretty strange that your build doesn't contain any logs. Our nightly CI looks green (finished 16 hours ago).
![image](https://user-images.githubusercontent.com/16715858/87327850-4d5f7580-c53d-11ea-8bd9-c935f72f9e28.png)
Link: https://dev.azure.com/github/virtual-environments/_build/results?buildId=75374&view=logs&j=011e1ec8-6569-5e69-4f06-baf193d1351e&t=486c0909-f67d-5748-80b3-bb1d531e7b43

Could it be transient issue or it reproduces constantly?

**Comment by mihsoft** [comment]
thanks Maxim, i'm just running another DevOps pipeline build now, should hit the same point in about 15 minutes or so, will drop a reply once the build has completed.

**Comment by mihsoft** [comment]
Build has failed with a different issue this time,

```
    azure-arm: Err:27 https://storage.googleapis.com/bazel-apt stable/jdk1.8 amd64 Packages

    azure-arm:   File has unexpected size (4147 != 3912). Mirror sync in progress?
```

Might switch to my self-hosted agents to see if that makes any difference

**Comment by mihsoft** [comment]
Ok, re-ran this again last night and encountered the same issue. Nothing in the logs to suggest any errors but no output from the hosted-tool-cache.sh or pypy.sh scripts suggesting they are for some reason not being executed.

**Comment by mihsoft** [comment]
So, managed to get an Ubuntu image built using the Microsoft hosted agents but unable to get the ubuntu1804.json to run through using a Win2019 VMSS agent

Build 'azure-arm' errored: Script disconnected unexpectedly. If you expected your script to disconnect, i.e. from a restart, you can try adding `"expect_disconnect": true` or `"valid_exit_codes": [0, 2300218]` to the shell provisioner parameters.

**Comment by mihsoft** [comment]
Was able to get a build running and an image created. closing
