### ISSUE TITLE
Rename default branch

### ISSUE THREAD

**Issue by andymckay** [actions/virtual-environments#1227]
👋 This issue is to track the move over to using `main` as the default branch for this repo. We’d love your team's help in completing this transition.

**Do not remove your old default branch**, customers are going to be using it. We will be sending messages out about these changes, but if you want to message in your repository, that's fine as well.

- [ ] Create a `main` branch.
- [ ] You might need to rebase any pull requests you want to merge before changing the default branch.
- [ ] Change the default branch in settings to `main`.
- [ ] Update any documentation in this repo to refer to the new branch name, although using the version tag is still preferred.
- [ ] Check that this Action works correctly for users who have a repository with a custom default branch name.
- [ ] Close this issue and celebrate 🎉

We are aiming to complete this work by ~July 17th~ August 28th.

**Comment by maxim-lobanov** [comment]
Done
