### ISSUE TITLE
Add OpenVPN

### ISSUE THREAD

**Issue by sean-krail** [actions/virtual-environments#124]
**Tool information**
- Tool name: OpenVPN
- Add or update? Add
- Desired version: Latest
- Approximate size: 
- If this is an add request:
  - Brief description of tool: OpenVPN client
  - URL for tool's homepage: https://openvpn.net/ and https://help.ubuntu.com/lts/serverguide/openvpn.html

**Virtual environments affected**
- [ ] macOS 10.15
- [x] Ubuntu 16.04 LTS
- [x] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Can this tool be installed during the build?**
Yes, it's as simple as:
```bash
sudo DEBIAN_FRONTEND=noninteractive apt-get -y install openvpn
```
Takes about 20-25 seconds.

**Are you willing to submit a PR?**
Yes

**Comment by sean-krail** [comment]
Created PR at https://github.com/actions/virtual-environments/pull/445

**Comment by thejoebourneidentity** [comment]
Hey @sean-krail, thanks for the suggestion and we also appreciate the PR. We discussed internally, and we think this would be better developed as an `setup-*` action, especially since the tool installs so quickly.

https://github.com/actions/toolkit
