### ISSUE TITLE
Ubuntu1804 image using VMSS takes up to an hour to provision new DevOps agents

### ISSUE THREAD

**Issue by mihsoft** [actions/virtual-environments#1240]
**Describe the bug**
When using a Virtual Machine Scale Set in UKSouth with the ubuntu1804 image from this repository new instances either hang in Creating(Running) or take over an hour to provision.
When not utilising the Azure DevOps extension the instances are able to spin up within a minute or two

**Area for Triage**: 

**Question, Bug, or Feature?**: 
Bug

**Virtual environments affected**
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ x] Ubuntu 18.04 LTS
- [ ] Ubuntu 20.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Expected behavior**
A DevOps VMSS Instance agent should be created in a reasonable timeframe

**Actual behavior**
Create a Virtual Machine Scale Set in UKSouth
Set to 0 instances
Enable System Managed Identity
Set to use a Managed Image based on ubuntu1804 from this repository

Add a new VMSS Agent Pool - 1 Standby instance, 5 Maximum
Create a new pipeline using the agent pool

Observe thhe VMSS instances hanging and multiple health events being raised

**Comment by vmapetr** [comment]
Hi @mihsoft !
Could you, please, confirm that the same issue cannot be reproduced with any other Ubuntu image from Azure marketplace?

**Comment by WillLennon** [comment]
Hi Mihsoft,
Can you please file a ticket in the Azure DevOps developer community and include specific details like your account name and agent pool name.  Thanks.
https://developercommunity.visualstudio.com/content/problem/post.html?space=21

**Comment by mihsoft** [comment]
@vmapetr deploying a new 1804-LTS VMSS using the following Terraform source configuration:
```
  source_image_reference {
    publisher = "Canonical"
    offer     = "UbuntuServer"
    sku       = "18.04-LTS"
    version   = "latest"
  }
```

Will report back as soon as I've gathered some diagnostics.

**Comment by mihsoft** [comment]
@WillLennon thanks - Looks like it has already been raised by another user - https://developercommunity.visualstudio.com/content/problem/1099127/scale-set-vms-taking-long-time-to-create-due-to-lo.html

Appears to be an issue with the specific Azure DevOps provisioning script attempting to chmod entire directories.

**Comment by mihsoft** [comment]
@WillLennon @vmapetr to confirm I have confirmed the issue does not affect the standard 1804-LTS image, mainly because there isn't any software pre-installed so the DevOps agents installation scripts run very quickly indeed. (<1 min)

**Comment by alepauly** [comment]
> Appears to be an issue with the specific Azure DevOps provisioning script attempting to chmod entire directories.

That makes a lot of sense, thank you so much for the info and debugging @mihsoft!

**Comment by WillLennon** [comment]
I pushed out a fix today.  It should be everywhere within a week.

**Comment by mihsoft** [comment]
@WillLennon - Have been using the new VMSS with Ubuntu1804 and not had any issues until we tried to run a dotnet build today - 
```

/usr/bin/dotnet build /agent/_work/1/s/core/src/x -dl:CentralLogger,"/agent/_work/_tasks/DotNetCoreCLI_5541a522-603c-47ad-91fc-a4b1d163081b/2.172.2/dotnet-build-helpers/Microsoft.TeamFoundation.DistributedTask.MSBuild.Logger.dll"*ForwardingLogger,"/agent/_work/_tasks/DotNetCoreCLI_5541a522-603c-47ad-91fc-a4b1d163081b/2.172.2/dotnet-build-helpers/Microsoft.TeamFoundation.DistributedTask.MSBuild.Logger.dll" --configuration Release
Microsoft (R) Build Engine version 16.6.0+5ff7b0c9e for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

MSBUILD : error MSB1025: An internal failure occurred while running MSBuild.
System.ComponentModel.Win32Exception (13): Permission denied
   at System.Diagnostics.Process.set_PriorityClassCore(ProcessPriorityClass value)
   at System.Diagnostics.Process.set_PriorityClass(ProcessPriorityClass value)
   at Microsoft.Build.CommandLine.MSBuildApp.Execute(String[] commandLine)
Unhandled exception. System.ComponentModel.Win32Exception (13): Permission denied
   at System.Diagnostics.Process.set_PriorityClassCore(ProcessPriorityClass value)
   at System.Diagnostics.Process.set_PriorityClass(ProcessPriorityClass value)
   at Microsoft.Build.CommandLine.MSBuildApp.Execute(String[] commandLine)
   at Microsoft.Build.CommandLine.MSBuildApp.Main(String[] args)
##[error]Error: The process '/usr/bin/dotnet' failed with exit code 134
Info: Azure Pipelines hosted agents have been updated to contain .Net Core 3.x (3.1) SDK/Runtime along with 2.1. Unless you have locked down a SDK version for your project(s), 3.x SDK might be picked up which might have breaking behavior as compared to previous versions. 
Some commonly encountered changes are: 
If you're using `Publish` command with -o or --Output argument, you will see that the output folder is now being created at root directory rather than Project File's directory. To learn about more such changes and troubleshoot, refer here: https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/dotnet-core-cli?view=azure-devops#troubleshooting
##[error]Dotnet command failed with non-zero exit code on the following projects: x
```

**Comment by mihsoft** [comment]
@WillLennon see #1287 which is possibly a side effect of this
