### ISSUE TITLE
Add/Update Pulumi

### ISSUE THREAD

**Issue by cnunciato** [actions/virtual-environments#1242]
**Tool information**
- Tool name: Pulumi
- Tool license: Apache License 2.0
- Add or update? Add
- Desired version: latest
- Approximate size: 57MB
- If this is an add request:
  - Brief description of tool: Pulumi is an open-source infrastructure-as-code tool for creating, deploying, and managing cloud infrastructure. It supports dozens of public, private, and hybrid cloud service providers.
  - URL for tool's homepage: https://pulumi.com/docs
  - Provide a basic test case to validate the tool's functionality: `pulumi --version`

**Area for Triage**:
Scripting and command line, Deployment/Release

**Question, Bug, or Feature?**:
Feature.

**Virtual environments affected**
- [x] macOS 10.15
- [x] Ubuntu 16.04 LTS
- [x] Ubuntu 18.04 LTS
- [x] Ubuntu 20.04 LTS
- [x] Windows Server 2016 R2
- [x] Windows Server 2019

**Can this tool be installed during the build?**
Yes:

```
# macOS
brew install pulumi

# Linux
curl -fsSL https://get.pulumi.com | sh

# Windows
choco install pulumi
```

For additional methods, see also https://www.pulumi.com/docs/get-started/install/.

**Tool installation time in runtime**
A few seconds.

```
root@2e5fda0450d4:/# time curl -fsSL https://get.pulumi.com | sh
=== Installing Pulumi v2.6.1 ===
+ Downloading https://get.pulumi.com/releases/sdk/pulumi-v2.6.1-linux-x64.tar.gz...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 57.7M  100 57.7M    0     0  7493k      0  0:00:07  0:00:07 --:--:-- 5875k
+ Extracting to /root/.pulumi/bin

=== Pulumi is now installed! 🍹 ===
+ Please add /root/.pulumi/bin to your $PATH
+ Get started with Pulumi: https://www.pulumi.com/docs/quickstart

real	0m9.471s
user	0m1.287s
sys	0m1.318s
```

**Are you willing to submit a PR?**
Absolutely!

**Comment by maxim-lobanov** [comment]
Hello @cnunciato ,
We don't have objections about adding this tool to images. Feel free to prepare PR.
The single question - do we really need to install this tool to all images? Ubuntu, macOS, Windows?

**Comment by cnunciato** [comment]
@maxim-lobanov Delighted to see someone else got to this before I did. 😄 I suspect most users would be happy with Ubuntu and Windows; I just included macOS because Pulumi is commonly used on macOS desktops, but I don't have a sense of how commonly it'd be used on macOS in CI.

**Comment by maxim-lobanov** [comment]
@cnunciato , in this case, doesn't you mind if we exclude macOS platform for now?
We should be very careful about installing of new software on images from image size, image generation time sides.
We can consider macOS installation later if we see requests for it

**Comment by AlenaSviridenko** [comment]
Hi @cnunciato, 
PRs were merged, so Pulumi will be available on images with the next image rollout in 1-2 weeks. 
We will keep you posted with the updates.
Thanks!

**Comment by LeonidLapshin** [comment]
Pulumi is now available on Ubuntu and Windows :)
