### ISSUE TITLE
Add Az Powershell Module vs. 4.4.0

### ISSUE THREAD

**Issue by juteasl** [actions/virtual-environments#1243]
**Tool information**
- Tool name: Az Powershell
- Tool license:  Default
- Add or update? Add
- Desired version: 4.4.0
- Approximate size: 
- If this is an add request:
  - Brief description of tool: Latest version of Az Powershell to use with Event Grid parameters that aren't in 4.3.0
  - URL for tool's homepage:
https://docs.microsoft.com/en-us/powershell/module/az.eventgrid/new-azeventgridsubscription?view=azps-4.4.0
  - Provide a basic test case to validate the tool's functionality:
Execute New-AzEventGridSubscription using the AzureActiveDirectoryTenantId and AzureActiveDirectoryApplicationIdOrUri parameters

**Area for Triage**:
'Scripting and command line'

**Question, Bug, or Feature?**:
Feature

**Virtual environments affected**
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Ubuntu 20.04 LTS
- [X] Windows Server 2016 R2
- [X] Windows Server 2019

**Comment by al-cheb** [comment]
Hello, @juteasl 
We have deployed new Windows Server 2016/2019 images with Az 4.4.0 PowerShell module. Feel free to reopen the thread if you have any concerns.
