### ISSUE TITLE
Replace SVN with TortoiseSVN

### ISSUE THREAD

**Issue by augustozanellato** [actions/virtual-environments#1246]
**Tool information**
- Tool name: TortoiseSVN
- Tool license: GPL
- Add or update? Sort of update
- Desired version: latest available on Chocolatey
- Approximate size: 
- If this is an add request:
  - Brief description of tool: It provides an updated version of svn cli, now 1.14.x instead of 1.8.17 provided now
  - URL for tool's homepage: https://tortoisesvn.net/
  - Provide a basic test case to validate the tool's functionality: 

**Area for Triage**:

**Question, Bug, or Feature?**:
Feature

**Virtual environments affected**
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Ubuntu 20.04 LTS
- [X] Windows Server 2016 R2
- [X] Windows Server 2019

**Can this tool be installed during the build?**
`choco install tortoisesvn -y`

**Tool installation time in runtime**
~4 minutes

**Are you willing to submit a PR?**
Yes!

**Comment by vmapetr** [comment]
Hi @augustozanellato !
We appreciate your contribution, but could you please provide some additional info about suggested changes? Is there some breaking changes in TortoiseSVN, beside Subversion update, that can impact the users of currently installed SVN?

**Comment by augustozanellato** [comment]
Hi!
There shouldn't be any breaking change, the only difference at a practical level is an svn upgrade, so mostly new features.

**Comment by maxim-lobanov** [comment]
@augustozanellato , sorry that it took so much time to take a look at this issue and PR.
We have published small announcement: https://github.com/actions/virtual-environments/issues/1318
We are planning to merge your PR next week.

**Comment by miketimofeev** [comment]
@augustozanellato we've successfully deployed a new VM image with TortoiseSVN on board! I'm going to close the issue. Feel free to contact us if you have any concerns.
Thank you!
