### ISSUE TITLE
[Announcement] Default Xcode will be switched to 11.6 on July, 22

### ISSUE THREAD

**Issue by AlenaSviridenko** [actions/virtual-environments#1250]
Hi!

Xcode 11.6 stable is out so we are going to switch default Xcode from 11.5 to 11.6 on July, 22.

Please, let us know through this issue if you have any concerns.

Thanks!

**Comment by diogot** [comment]
Do the stable 11.6 Xcode is already deployed?

**Comment by maxim-lobanov** [comment]
@diogot 
It was released yesterday and we are planning to deliver it next week Tue / Wed
