### ISSUE TITLE
[Announcement] Default branch switched from master to main, master will be deleted soon

### ISSUE THREAD

**Issue by alepauly** [actions/virtual-environments#1252]
Hi everyone!

The default branch of the [`actions/virtual-environments`](https://github.com/actions/virtual-environments) repository is now [`main`](https://github.com/actions/virtual-environments/tree/main). We will continue to update the [`master`](https://github.com/actions/virtual-environments/tree/master) until Monday July 27th, when we will delete it. Please update any automation or sync process you might have on your forks that could depend on it. Don't hesitate to reach out if you have any questions.

**Comment by maxim-lobanov** [comment]
We have deleted `master` branch from this repository. `main` branch will the default one.
