### ISSUE TITLE
[Announcement] Update stock Pester on Windows images to 5.0 on July 17

### ISSUE THREAD

**Issue by maxim-lobanov** [actions/virtual-environments#1255]
Hi!

Currently, Pester 3 is installed on Windows 2016 and 2019 images by default.
We are going to update it to Pester 5 on July 17.

The main reason for this update is that we have started to use Pester for image testing during image-generation. Pester 3 is old and can't use it for our purpose.

Please, let us know through this issue if you have any concerns.

Thanks!

**Comment by nohwnd** [comment]
(Owner of Pester here) Would you consider making it 4.10.1, or what’s the latest 4.x a release is? Version five has some issues and most of the community is using v4, and will be for a long time.

**Comment by nohwnd** [comment]
Unless you plan to update it every month from now on, in that case Pester 5 is better.

**Comment by maxim-lobanov** [comment]
Hello @nohwnd , glad to see your input here.
We are planning to install the latest version of Pester on every image-generation (weekly basis) and follow all updates.
I worry that if we freeze on Pester 4.10.1 now and customers start to use pre-installed module, some day it will be a pain for all customers when we update it to V5 (a lot of breaking changes between versions). Probably, it is good for Pester community growing too (Consider, that customers are able to install 4.10.1 in runtime pretty quick if they prefer).

Also, would like to mention that we use Pester V5 for image testing.
We have decided to use Pester V5 because sometime eventually, we will have to switch to V5 and since it contains breaking changes in comparison with V4 (like different scope of `Describe` / `Context` and `It` blocks and etc), it could be painful to rewrite all tests later. So we would like to start with V5 to avoid this work in future.
Our tests [are not super complex](https://github.com/actions/virtual-environments/tree/main/images/win/scripts/Tests)(`Toolset.Tests.ps1` contains example of the most complex test). From this point, V5 works perfect for us and we didn't notice any issues with it.

Anyway, please let us know if you strongly prefer to pre-install and freeze Pester 4.10.1 on images because you definitely have  more experience and context.

**Comment by nohwnd** [comment]
Thanks for the explanation. 5.0 will be better if you plan to update regularly.

**Comment by maxim-lobanov** [comment]
Closing since this change was deployed everywhere.
