### ISSUE TITLE
Add chromium-browser

### ISSUE THREAD

**Issue by martinsbalodis** [actions/virtual-environments#126]
**Tool information**
- Tool name: chromium-browser
- Add or update? Add
- Desired version: Latest (78)
- Approximate size: 244 MB
- If this is an add request:
  - Brief description of tool: A Chrome browser version that doesn't include closed source libraries. Comparing with chrome-browser it can be installed without adding external repositories and could be the popular choice for developers.
  - URL for tool's homepage: https://www.chromium.org/Home

**Virtual environments affected**
- [ ] macOS 10.15
- [x] Ubuntu 16.04 LTS
- [x] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Can this tool be installed during the build?**
 * Yes it can be installed. 
 * Including apt-get update it took 53 seconds. 
 * Note this should be installed in a way that it doesn't mess with default browser settings in Ubuntu for backwards compatibility.
```
sudo DEBIAN_FRONTEND=noninteractive apt-get install -y chromium-browser
```

**Are you willing to submit a PR?**
Yes

**Comment by kaylangan** [comment]
Perhaps a naive question--does this offer additional functionality that Chrome does not?

**Comment by maxim-lobanov** [comment]
@martinsbalodis, Please let us know, if the feature request is still popular.

**Comment by alepauly** [comment]
@martinsbalodis I'll close this but let us know if you see a need to have chromium baked into the virtual-environments image. thanks.
