### ISSUE TITLE
windows-latest environment running much slower since 20200714.1

### ISSUE THREAD

**Issue by beechtom** [actions/virtual-environments#1269]
**Describe the bug**
This is similar to an issue I filed two weeks ago: https://github.com/actions/virtual-environments/issues/1204
Workflows running on windows-latest environment are running about 2.5x slower than usual since the release of 20200714.1

**Area for Triage**: 
Image Administration
Testing and code coverage

**Question, Bug, or Feature?**: 
Bug

**Virtual environments affected**
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Ubuntu 20.04 LTS
- [ ] Windows Server 2016 R2
- [x] Windows Server 2019

**Expected behavior**
New releases of Windows environments should not result in significantly slower workflows.

**Actual behavior**
Since the release of 20200714.1, workflows running on windows-latest have been running much slower than usual. Compare the following jobs run for the same pull request with minor changes between commits:

**20200706.1 (~13m):** https://github.com/puppetlabs/bolt/runs/883584515?check_suite_focus=true
**20200714.1 (~35m):** https://github.com/puppetlabs/bolt/runs/891066891?check_suite_focus=true

Several steps saw a noticeable increase in time to complete:
- Checkout takes 3x longer, from 9s to 20s
- Running a custom setup script takes 2x longer, from 14s to 23s
- Running tests with rspec takes 3x longer, from 12m to 34m
- Post-checkout takes 4.5x longer, from 3s to 14s

The overall time for job completion increased ~2.5x from an average of ~13m to an average of ~35m.

**Comment by maxim-lobanov** [comment]
Hello @beechtom , checkout time and scripts time are very close on both images. The real difference is tests step.
I see that you configure connection to remote machine in runtime. It could be potential reason for this delay. Can we check it somehow?
Interesting point that `Agentful` job takes the same time on both images (11minutes vs 12 minutes) and the difference is only for `Agentless` job. What is the difference between these jobs?

**Comment by beechtom** [comment]
@maxim-lobanov The script only configures a new user on the runner and tests a connection to itself, not a remote machine. You can check it by just running the script on the runner.

While the `Agentful` job takes roughly the same time, if you look at the individual steps they experienced a similar increase in time to complete. Checkout takes over twice as long, post-checkout takes three times as long, etc. Even the tests themselves take about a minute longer. While that's not significant, it _is_ indicative that the environment itself is running slower than it used to be.

I suspect that the reason there isn't as much of a change for the `Agentful` job is because it only runs 6 tests, as opposed to `Agentless` which runs about 1,500 tests. Could it be that a change in the environment is causing startup for scripts/tools take longer, hence the more significant change to a test suite that runs 1,500 individual tests?

The tests run in the `Agentful` job are our most time-intensive tests, as they rely on compiling Puppet code. The `Agentless` tests are primarily unit tests, with a handful of integration tests that test making remote connections (again, the runner just connects to itself).

**Comment by seanyen** [comment]
@maxim-lobanov @al-cheb Would it be possible an issue is on the machine allocated to run the image?

I also experienced the same since few weeks ago. For the slower one, this is the CPU reported by `wmic`:
```
AddressWidth  Architecture  AssetTag  Availability  Caption                               Characteristics  ConfigManagerErrorCode  ConfigManagerUserConfig  CpuStatus  CreationClassName  CurrentClockSpeed  CurrentVoltage  DataWidth  Description                           DeviceID  ErrorCleared  ErrorDescription  ExtClock  Family  InstallDate  L2CacheSize  L2CacheSpeed  L3CacheSize  L3CacheSpeed  LastErrorCode  Level  LoadPercentage  Manufacturer  MaxClockSpeed  Name                                           NumberOfCores  NumberOfEnabledCore  NumberOfLogicalProcessors  OtherFamilyDescription  PartNumber  PNPDeviceID  PowerManagementCapabilities  PowerManagementSupported  ProcessorId       ProcessorType  Revision  Role  SecondLevelAddressTranslationExtensions  SerialNumber  SocketDesignation  Status  StatusInfo  Stepping  SystemCreationClassName  SystemName       ThreadCount  UniqueId  UpgradeMethod  Version  VirtualizationFirmwareEnabled  VMMonitorModeExtensions  VoltageCaps  

64            9             None      3             Intel64 Family 6 Model 85 Stepping 4                                                                    1          Win32_Processor    2095               29              64         Intel64 Family 6 Model 85 Stepping 4  CPU0                                                2                                               0            0                            6      3               GenuineIntel  2095           Intel(R) Xeon(R) Platinum 8171M CPU @ 2.60GHz  2                                   4                                                  None                                                  FALSE                     1F8BFBFF00050654  3              21764     CPU   FALSE                                    None          None               OK      3                     Win32_ComputerSystem     WIN-S1QJGOCMU0T                         6                       FALSE                          FALSE                    4            
```

And for the normal one, this is the CPU reported:
```
AddressWidth  Architecture  AssetTag  Availability  Caption                               Characteristics  ConfigManagerErrorCode  ConfigManagerUserConfig  CpuStatus  CreationClassName  CurrentClockSpeed  CurrentVoltage  DataWidth  Description                           DeviceID  ErrorCleared  ErrorDescription  ExtClock  Family  InstallDate  L2CacheSize  L2CacheSpeed  L3CacheSize  L3CacheSpeed  LastErrorCode  Level  LoadPercentage  Manufacturer  MaxClockSpeed  Name                                           NumberOfCores  NumberOfEnabledCore  NumberOfLogicalProcessors  OtherFamilyDescription  PartNumber  PNPDeviceID  PowerManagementCapabilities  PowerManagementSupported  ProcessorId       ProcessorType  Revision  Role  SecondLevelAddressTranslationExtensions  SerialNumber  SocketDesignation  Status  StatusInfo  Stepping  SystemCreationClassName  SystemName  ThreadCount  UniqueId  UpgradeMethod  Version  VirtualizationFirmwareEnabled  VMMonitorModeExtensions  VoltageCaps  

64            9             None      3             Intel64 Family 6 Model 85 Stepping 4                                                                    1          Win32_Processor    2095               16              64         Intel64 Family 6 Model 85 Stepping 4  CPU0                                      100       179                                             0            0                            6      2               GenuineIntel  2095           Intel(R) Xeon(R) Platinum 8171M CPU @ 2.60GHz  2                                   2                                                  None                                                  FALSE                     1F8BFBFF00050654  3              21764     CPU   FALSE                                    None          None               OK      3                     Win32_ComputerSystem     fv-az686                           6                       FALSE                          FALSE                                 
```

For example, by looking at the `NumberOfLogicalProcessors`, the slower one is 4, but the normal one is 2. And according to [this](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops&tabs=yaml#hardware), for the Microsoft-hosted agent should be `Standard_DS2_v2` and I don't know if the delta means something here.

It might be a coincident, but it seems to be correlated to the slower pipelines in my environment.

**Comment by al-cheb** [comment]
@seanyen, Currently the issue is related to .NET https://github.com/dotnet/announcements/issues/33 and we are planning to fix it - https://github.com/actions/virtual-environments/pull/1316

**Comment by miketimofeev** [comment]
@beechtom We've finished deployment with the fix. This issue isn't supposed to exist anymore.
Feel free to reopen the issue if you have any concerns.
Thank you!
