### ISSUE TITLE
Update GHC to 8.8.4 from 8.8.3

### ISSUE THREAD

**Issue by expipiplus1** [actions/virtual-environments#1271]
**Tool information**
- Tool name: GHC
- Tool license: 3-clause BSD
- Add or update? Update
- Desired version: 8.8.4 (Updating 8.8.3)
- Approximate size: 200MB

**Area for Triage**:

Haskell

**Question, Bug, or Feature?**:

Feature 

**Virtual environments affected**
- [?] macOS 10.15
- [x] Ubuntu 16.04 LTS
- [x] Ubuntu 18.04 LTS
- [x] Ubuntu 20.04 LTS
- [x] Windows Server 2016 R2
- [x] Windows Server 2019

**Can this tool be installed during the build?**

No change

**Tool installation time in runtime**

No change

**Are you willing to submit a PR?**

Sorry, not sure where to look.

**Comment by maxim-lobanov** [comment]
Hello, We are installing latest patch version for 3 latest major.minor pairs on every image-generation. All images should be updated in 1 week and GHC 8.8.4 will be there.

**Comment by expipiplus1** [comment]
Thanks!

**Comment by maxim-lobanov** [comment]
@expipiplus1 , By the way, if you use GitHub Actions, you may use [actions/setup-haskell](https://github.com/actions/setup-haskell) to install any GHC with minor latency. As soon as image is deployed, task will start picking version from cache and latency will be removed.

**Comment by expipiplus1** [comment]
Thanks! I am in fact already making use of it :)

**Comment by miketimofeev** [comment]
@expipiplus1 GHC 8.8.4 is now cached across all the images. I'm going to close the issue.
Thank you!

**Comment by expipiplus1** [comment]
Thanks!

**Comment by miketimofeev** [comment]
Sorry for the misinformation, it seems Ubuntu ppa is not yet updated, reopen the issue
https://launchpad.net/~hvr/+archive/ubuntu/ghc/+index?field.series_filter=focal

**Comment by miketimofeev** [comment]
ghc-8.8.4 finally available across all ubuntu images!

**Comment by expipiplus1** [comment]
Thanks!
