### ISSUE TITLE
Update Chrome and Chromeviewer to 84 version

### ISSUE THREAD

**Issue by bpz** [actions/virtual-environments#1275]
**Tool information**
- Tool name: Chrome and Chromeviewer
- Add or update? Update
- Desired version: Latest (84)

**Question, Bug, or Feature?**:
Feature

**Virtual environments affected**
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [x] Ubuntu 20.04 LTS
- [ ] Windows Server 2016 R2
- [x] Windows Server 2019

**Comment by maxim-lobanov** [comment]
Hello!
We install the latest available version of Google Chrome and Chrome Driver on every image-generation and update images on weekly basis.
Chrome 84 should be available in a week.

**Comment by bpz** [comment]
Great!
Thank you @maxim-lobanov

**Comment by magneticflux-** [comment]
It looks like there are some issues with the deployment of Chrome and the webdriver:

```log
> ng e2e "--protractor-config=e2e/protractor-ci.conf.js"
...
[22:41:06] I/update - chromedriver: unzipping chromedriver_84.0.4147.30.zip
...
** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **
: Compiled successfully.
[22:41:18] I/launcher - Running 1 instances of WebDriver
[22:41:18] I/direct - Using ChromeDriver directly...
[22:41:18] E/launcher - session not created: This version of ChromeDriver only supports Chrome version 84
  (Driver info: chromedriver=84.0.4147.30 (48b3e868b4cc0aa7e8149519690b6f6949e110a8-refs/branch-heads/4147@{#310}),platform=Linux 5.3.0-1032-azure x86_64)
[22:41:18] E/launcher - SessionNotCreatedError: session not created: This version of ChromeDriver only supports Chrome version 84
```
This is my workflow:

```yml
# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2-beta
        with:
          node-version: ${{ matrix.node-version }}
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - run: npm ci
      - run: npm run build
      - run: npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
      - run: npm run e2e -- --protractor-config=e2e/protractor-ci.conf.js
```

**Comment by maxim-lobanov** [comment]
@magneticflux- ,
Currently, the following versions are installed: Google Chrome 83.0.4103.116, ChromeDriver 83.0.4103.39
The next image will contain: Google Chrome 84.0.4147.89, ChromeDriver 84.0.4147.30

You code is trying to update ChromeDriver in runtime to 84.0.4147.30. After this update, Chrome and ChromeDriver become incompatible.
```
[22:41:06] I/update - chromedriver: unzipping chromedriver_84.0.4147.30.zip
```

I suggest to avoid updates in runtime and use pre-installed versions. If you prefer to update ChromeDriver in runtime, you have to update Google Chrome too

**Comment by magneticflux-** [comment]
I see, I assumed the environment variables set for the drivers were standard for Protractor and that it would use them if they exist. I added these options to my `protractor.conf.js` to use the variables:

```javascript
exports.config = {
  // ...
  chromeDriver: process.env.CHROMEWEBDRIVER + '/chromedriver',
  geckoDriver: process.env.GECKOWEBDRIVER + '/geckodriver',
  // ...
}
```

**Comment by bpz** [comment]
> I see, I assumed the environment variables set for the drivers were standard for Protractor and that it would use them if they exist. I added these options to my `protractor.conf.js` to use the variables:
> 
> ```js
> exports.config = {
>   // ...
>   chromeDriver: process.env.CHROMEWEBDRIVER + '/chromedriver',
>   geckoDriver: process.env.GECKOWEBDRIVER + '/geckodriver',
>   // ...
> }
> ```

Hi @magneticflux- ,
Maybe I'm missing something, but does this avoid protractor updating chromedriver will running e2e tests? (Thanks!)

**Comment by magneticflux-** [comment]
@bpz Unfortunately it doesn't, but it's pretty quick to update and Protractor doesn't use the updated version.

**Comment by maxim-lobanov** [comment]
Sorry for late update. Chrome and Chrome Driver 84 were deployed everywhere previous week. Closing feature but please let us know if you have any questions

**Comment by bpz** [comment]
Thanks @maxim-lobanov, my issue is now solved :)))

**Comment by magneticflux-** [comment]
This is an update to my previous solution: https://github.com/actions/virtual-environments/issues/1275#issuecomment-662242402

In `protractor.conf.js`:
```javascript
// If in CI, webdrivers are installed globally
if (process.env.CI) {
  exports.config.chromeDriver = '/usr/bin/chromedriver';
  exports.config.geckoDriver = '/usr/bin/geckodriver';
}
```

In your workflow:
```sh
npm run e2e -- --protractor-config=e2e/protractor-ci.conf.js --webdriver-update=false
```

I ran into strange problems with my previous solution and this fixed them (somehow).
