### ISSUE TITLE
How long will Ubuntu 18.04 be supported?

### ISSUE THREAD

**Issue by kodagiri** [actions/virtual-environments#1277]
I intend to adopt GitHub actions to build the source code. Regarding of the OS of runner (VM), I will select Ubuntu 18.04. But, I'm concerned about the end of the support. I'm not sure that I should ask it here or not. But, I had contact customer support, and I had an advice that here are the maintainers in the best position to answer your question. So, please let me ask a question here. How long will Ubuntu 18.04 LTS be supported for the runners of GitHub actions?

**Comment by maxim-lobanov** [comment]
Hello @kodagiri ,
We support 2 latest LTS versions of Ubuntu. Currently, `ubuntu-16.04` and `ubuntu-18.04` are available. `20.04` is available too but in preview state.
We are planning to support `ubuntu-18.04` until next LTS ubuntu release at least (`22.04` is going to be released in April 2022)

cc: @alepauly for any additional thoughts

**Comment by maxim-lobanov** [comment]
I am closing this issue because initial question was answered. Please let me know if you have any other questions
