### ISSUE TITLE
TF binary is broken on Ubuntu 20.04 image because of default Java 11

### ISSUE THREAD

**Issue by maxim-lobanov** [actions/virtual-environments#1278]
## Issue
`azure-pipelines-agent` fails to checkout TFVC repository on Ubuntu 20.04 image because `tf` binary fails with error 100.
This issue is related to fact that Java 11 is default version on Ubuntu 20.04 image.

## Repro steps:
```
wget -O agent.tar.gz https://vstsagentpackage.azureedge.net/agent/2.172.1/vsts-agent-linux-x64-2.172.1.tar.gz
tar -xzf agent.tar.gz
externals/tee/tf eula -accept
```
This code will fail with exit code 100.
Since Java 11 is set as default on Ubuntu 20.04 image starting from adding this image, looks like this scenario has never worked.

## Workaround
Change default Java to 8 before checkout step
```
echo "##vso[task.setvariable variable=JAVA_HOME]$(JAVA_HOME_8_X64)"
echo "##vso[task.setvariable variable=PATH]$(JAVA_HOME_8_X64)/bin:$(PATH)"
```

## Possible solutions
1) Switch default Java to 8 on Ubuntu 20.04 image
> It could be a breaking changes for some customers who depend on default Java. Also switching default Java to 11 was request in https://github.com/actions/virtual-environments/issues/595

2) Apply lines from work around section on agent side
> `tf` binary is distributed by azure-pipelines-agent so potentially we can switch Java to 8 on agent side before invocation of `tf` and rollback it back later

3) Investigate if `tf` can be updated to support Java 11 (???)

**Comment by maxim-lobanov** [comment]
cc: @brunoborges,
As for this particular issue, we have decided to proceed with solution 2 and 3.
But I am a bit worried that we may face with more such issues in future, when customer uses tool that depends on default Java, it will be obstacle for him to migrate their code to ubuntu-20.04 image
What do you think about it?

**Comment by brunoborges** [comment]
Can you please share a log that shows the error confirming this is a problem due to Java 11?

**Comment by maxim-lobanov** [comment]
Unfortunately, it doesn't produce any logs :(
The single proof is repro steps:
1)
```
pool:
  vmImage: 'ubuntu-20.04'
steps:
- bash: java -version && which java
- script: |
    wget -O agent.tar.gz https://vstsagentpackage.azureedge.net/agent/2.172.1/vsts-agent-linux-x64-2.172.1.tar.gz
    tar -xzf agent.tar.gz
    externals/tee/tf eula -accept
```
Output (first step):
```
openjdk 11.0.8 2020-07-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.8+10)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.8+10, mixed mode)
/usr/lib/jvm/adoptopenjdk-11-hotspot-amd64/bin/java
```
And the second step fails with `##[error]Bash exited with code '100'.`

2) 
```
pool:
  vmImage: 'ubuntu-20.04'
steps:
- bash: |
    echo "##vso[task.setvariable variable=JAVA_HOME]$(JAVA_HOME_8_X64)"
    echo "##vso[task.setvariable variable=PATH]$(JAVA_HOME_8_X64)/bin:$(PATH)"
- bash: java -version && which java
- script: |
    wget -O agent.tar.gz https://vstsagentpackage.azureedge.net/agent/2.172.1/vsts-agent-linux-x64-2.172.1.tar.gz
    tar -xzf agent.tar.gz
    externals/tee/tf eula -accept
```
Output (second step):
```
openjdk version "1.8.0_262"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_262-b10)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.262-b10, mixed mode)
/usr/lib/jvm/adoptopenjdk-8-hotspot-amd64/bin/java
```
And the third step finishes with exit code 0

Also found a few related issues where people had the exactly same issue with [Java 12](https://github.com/microsoft/azure-pipelines-agent/issues/2245) and [Java 9](https://github.com/Microsoft/azure-pipelines-agent/issues/1564)

**Comment by brunoborges** [comment]
I can reproduce the problem locally, and get an `strace` log of the issue:

```Dockerfile
FROM adoptopenjdk:11-jdk-hotspot

RUN apt-get update && apt-get install -y strace wget

RUN wget -O agent.tar.gz https://vstsagentpackage.azureedge.net/agent/2.172.1/vsts-agent-linux-x64-2.172.1.tar.gz \
    && tar -xzf agent.tar.gz

CMD strace -v -s 256 externals/tee/tf eula -accept
```

IMO, to not be blocked here, solution #2 is indeed a good temporary fix. I'd suggest you to shim `tf` with a shell script that sets JAVA_HOME to 8 during its execution.

But frankly, the `tf` tool is what should change here and work with latest versions of Java.

**Comment by brunoborges** [comment]
Also, it seems that `tf` is calling some code that is part of TEE, but TEE is no longer supported?

**Comment by maxim-lobanov** [comment]
Closing this issue since it should be resolved on azure-pipelines-agent side.
