### ISSUE TITLE
MacOS 15.5.6 gfortran missing

### ISSUE THREAD

**Issue by RobertRosca** [actions/virtual-environments#1280]
**Describe the bug**
gfortran is not found on macos 15.5.6 images, whereas it is found on 15.5.5. I don't have a Mac/use MacOS so maybe I'm wrong, but I think this is a bug, or at least unexpected.

**Area for Triage**: Apple

**Question, Bug, or Feature?**: Bug

**Virtual environments affected**
- [x] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Ubuntu 20.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Expected behavior**
Same as in 15.5.5, where gfortran is available. 

On 15.5.5:

```
Current runner version: '2.169.1'
Operating System
  Mac OS X
  10.15.5
  19F101
Virtual Environment
  Environment: macos-10.15
  Version: 20200702.1
  Included Software: https://github.com/actions/virtual-environments/blob/master/images/macos/macos-10.15-Readme.md
Prepare workflow directory
Prepare all required actions
Download action repository 'actions/checkout@v2'
Download action repository 'actions/setup-python@v2'

Run gfortran --version
  gfortran --version
  shell: /bin/bash -e {0}
  env:
    pythonLocation: /Users/runner/hostedtoolcache/Python/3.7.8/x64
GNU Fortran (Homebrew GCC 9.3.0_1) 9.3.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Actual behavior**

On 15.5.6:
```
Current runner version: '2.267.1'
Operating System
  Mac OS X
  10.15.6
  19G73
Virtual Environment
  Environment: macos-10.15
  Version: 20200716.2
  Included Software: https://github.com/actions/virtual-environments/blob/master/images/macos/macos-10.15-Readme.md
Prepare workflow directory
Prepare all required actions
Download action repository 'actions/checkout@v2'
Download action repository 'actions/setup-python@v2'

Run gfortran --version
  gfortran --version
  shell: /bin/bash -e {0}
  env:
    pythonLocation: /Users/runner/hostedtoolcache/Python/3.7.8/x64
/Users/runner/work/_temp/1eb51142-3fab-4789-9f4f-3592cd0d6f3b.sh: line 1: gfortran: command not found
##[error]Process completed with exit code 127.
```

**Comment by maxim-lobanov** [comment]
Hello @RobertRosca , 
Fortran 8 and 9 are available by the separate binaries:
```
gfortran-8 --version
gfortran-9 --version
```
However, based on your logs, looks like `gfortran` was symlink to `gfortran-9` previously that it is pretty surprised for us.
We will take a look what was changed but you can use any of the options above

**Comment by RobertRosca** [comment]
Aha, didn't know that, thanks for the very fast reply!

**Comment by maxim-lobanov** [comment]
Hello, some results of investigation:
> We install fortran as a dependency of `gcc` on macOS image. We install gcc 8 and 9.
Previously, installation of gcc 9 created symlink `gfortran -> gfortran-9`. Recently, gcc 10 was released and installation process for gcc 9 was updated to not create this symlink. Symlink creation was moved to `gcc 10` formula and was removed from `gcc 9` formula. Since we don't pre-install gcc 10 on our images for now, symlink was removed.

@RobertRosca , sorry for breaking you with this update.
We discussed possibility to create the symlink from our side but we don't think that it is good solution from the long term perspective (if we want to install new gcc releases in future).

Also, from the UX side, it is better to use the separated binaries `gfortran-8`, `gfortran-9` always because it will guarantee that your build won't broken some day (just simple example: if we add gcc 10 on image one day, it will replace `gfortran` symlink to point to `gfortran-10` and you can face with breaking changes between versions).

Could you please confirm that `gfortran-8` works for you? Also please let me know if you have any concerns about decision above?

**Comment by RobertRosca** [comment]
No problem!

I can see why you'd be hesitant to add in a symlink on your side, it could definitely cause problems for other peoples workflows when the version silently changes in the background.

My solution for now is to create the symlink myself, which means that I know what version of gcc is being used for the symlink. This seems like the best solution as you'd always know which version you have, and no other changes have to be made after the symlink creation.

Everything works fine once the symlink is created and, to be honest, I prefer the verbosity of doing it manually since it's more obvious what's happening.

Thanks for the help!

**Comment by maxim-lobanov** [comment]
I am closing the issue, please let me know if you have any questions

**Comment by gautierbureau** [comment]
I add the same issue, autoconf tools rely on gfrotran and not gfortran-X so it breaks jobs if the symlink is not added manually. My first reflex was to go [here](https://github.com/actions/virtual-environments/blob/main/images/macos/macos-10.15-Readme.md) maybe adding the info would be good ?

**Comment by miketimofeev** [comment]
@gautierbureau do you mean something like this?
GNU Fortran (Homebrew GCC 8.4.0_1) 8.4.0 — available by `gfortran-8 `alias
GNU Fortran (Homebrew GCC 9.3.0) 9.3.0 — available by `gfortran-9` alias

**Comment by gautierbureau** [comment]
@miketimofeev yes that would be great.

**Comment by miketimofeev** [comment]
@gautierbureau thanks for the suggestion, we'll improve documentation

**Comment by AlenaSviridenko** [comment]
Hi @gautierbureau,
PR with the updated documentation generation was merged, new docs will be available with the next image deployment which is approximately 1-2 weeks.

**Comment by AlenaSviridenko** [comment]
Documentation was updated, I am going to close this issue.

Please, feel free to contact us in case of any questions. Thanks!
