### ISSUE TITLE
A "required" workflow is not started because of ignored files but the results are still required to submit the PR

### ISSUE THREAD

**Issue by f-squirrel** [actions/virtual-environments#1281]
**Describe the bug**
A "required" GitHub Action is not started because a PR's content is ignored by the action rules.
However, GitHub **requires** the results of the check.
As a result, the PR cannot be merged.

The link to [PR](https://github.com/vmware/concord-bft/pull/777).
The action is "clang-tidy".
Link to the [workflow](https://github.com/vmware/concord-bft/blob/master/.github/workflows/clang-tidy.yml).

**Area for Triage**: 

**Bug**

**Virtual environments affected**
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [x] Ubuntu 18.04 LTS
- [ ] Ubuntu 20.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Expected behavior**
I'd expect the required check to be ignored by GitHub.

**Comment by maxim-lobanov** [comment]
Hello @f-squirrel , probably, this workflow is marked as required check in your branch policies.
Could you please check it? You can follow this guide: https://docs.github.com/en/github/administering-a-repository/enabling-required-status-checks

**Comment by f-squirrel** [comment]
@maxim-lobanov , thank you for the quick response.
Yes, the workflow is marked as required.
Do I understand correctly that a required check cannot be ignored even if a changed file is ignored by the workflow's rules?

**Comment by maxim-lobanov** [comment]
Yes, it is correct. Required check means that workflow MUST pass to merge the PR

**Comment by f-squirrel** [comment]
@maxim-lobanov , it looks like a bug.

I'd expect a required workflow to return "true" if the PR's content is ignored by the workflow's rules.
Does it sound reasonable?

**Comment by mscoutermarsh** [comment]
Hi @f-squirrel, we have an internal issue open tracking this problem. We've added your case to it.

It's currently working as we had intended it. Required checks must have a success status for a merge to happen. 

This edge case is frustrating though. We've been discussing other ways to handle it. Such as looking if other commits have a success status. Your issue was added to the list, thanks for letting us know.

**Comment by JavierSegoviaCordoba** [comment]
I think this issue should not be closed. Even I like having the `[skip ci] approach, it adds noise to the commits history, so I don't understand why an intended skipped CI just provokes a dead PR that has to be merged, forced, manually by an administrator.

**Comment by alberttorosyan** [comment]
I have a similar issue. PR workflow runs only for certain directories, but when enabling check in branch protection rules, other PRs cannot be merged (since waiting for the check status).
@f-squirrel how did you overcome this? Is there any workaround I can employ here? Thanks in advance!

**Comment by f-squirrel** [comment]
Hi @alberttorosyan,
Unfortunately, I did not: any change triggers the CI...

**Comment by alberttorosyan** [comment]
> Hi @alberttorosyan,
> Unfortunately, I did not: any change triggers the CI...

@f-squirrel I was thinking of running the CI for every pull request, but checking the change list within the pipeline. It seems this is maximum we can achieve with current state of Github Actions...

**Comment by kurtpattyn-tomtom** [comment]
This issue has been closed. What is the solution? I am encountering the same issue.
