### ISSUE TITLE
The process ‘/usr/bin/unzip’ failed with exit code 9

### ISSUE THREAD

**Issue by BrightRan** [actions/virtual-environments#1284]
Associated community ticket: https://github.community/t/the-process-usr-bin-unzip-failed-with-exit-code-9/124054

In this case, the customer is working on an action which is used to download an artifact from a different workflow run and then unzip the downloaded ZIP file (see [here](https://github.com/getsentry/action-visual-snapshot/blob/main/src/api/downloadOtherWorkflowArtifact.ts#L41)).

This action sometimes fails to unzip with the exit code 9. See [this example](https://github.com/getsentry/sentry/runs/900205530#step:2:57).
```sh
##[error]The process '/usr/bin/unzip' failed with exit code 9
```

**Comment by al-cheb** [comment]
Not related to the image: https://github.community/t/the-process-usr-bin-unzip-failed-with-exit-code-9/124054
