### ISSUE TITLE
dotnetcore 3.1 build fails on Azure DevOps with Virtual Machine ScaleSet using latest Ubuntu1804 image and VMSS Agent Extension - 1.2.1

### ISSUE THREAD

**Issue by mihsoft** [actions/virtual-environments#1287]
**Describe the bug**
Running a simple dotnetcore build on a VMSS using the ubuntu1804 packer file from this repo fails when using dotnetcore 3.x, running using Windows Server 2019 works as expected, as does dotnetcore 3.0.x
```
Starting: DotNetCore Build x.sln - Release
==============================================================================
Task         : .NET Core
Description  : Build, test, package, or publish a dotnet application, or run a custom dotnet command
Version      : 2.172.2
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/build/dotnet-core-cli
==============================================================================
Info: .NET Core SDK/runtime 2.2 and 3.0 are now End of Life(EOL) and have been removed from all hosted agents. If you're using these SDK/runtimes on hosted agents, kindly upgrade to newer versions which are not EOL, or else use UseDotNet task to install the required version.
/usr/bin/dotnet build /agent/_work/1/s/core/src/**x.sln** -dl:CentralLogger,"/agent/_work/_tasks/DotNetCoreCLI_5541a522-603c-47ad-91fc-a4b1d163081b/2.172.2/dotnet-build-helpers/Microsoft.TeamFoundation.DistributedTask.MSBuild.Logger.dll"*ForwardingLogger,"/agent/_work/_tasks/DotNetCoreCLI_5541a522-603c-47ad-91fc-a4b1d163081b/2.172.2/dotnet-build-helpers/Microsoft.TeamFoundation.DistributedTask.MSBuild.Logger.dll" --configuration Release
Microsoft (R) Build Engine version 16.6.0+5ff7b0c9e for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

MSBUILD : error MSB1025: An internal failure occurred while running MSBuild.
System.ComponentModel.Win32Exception (13): Permission denied
   at System.Diagnostics.Process.set_PriorityClassCore(ProcessPriorityClass value)
   at System.Diagnostics.Process.set_PriorityClass(ProcessPriorityClass value)
   at Microsoft.Build.CommandLine.MSBuildApp.Execute(String[] commandLine)
Unhandled exception. System.ComponentModel.Win32Exception (13): Permission denied
   at System.Diagnostics.Process.set_PriorityClassCore(ProcessPriorityClass value)
   at System.Diagnostics.Process.set_PriorityClass(ProcessPriorityClass value)
   at Microsoft.Build.CommandLine.MSBuildApp.Execute(String[] commandLine)
   at Microsoft.Build.CommandLine.MSBuildApp.Main(String[] args)
##[error]Error: The process '/usr/bin/dotnet' failed with exit code 134
```

**Sample Pipeline yaml**

```
trigger: none

pr: none

variables:
  buildConfiguration: 'Release'
  solution: 'x.sln'

jobs:
- job: Build
  displayName: Repro build failure
  pool:
    name: **_removed_**
  steps:
  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '3.x'
  
  - task: DotNetCoreCLI@2
    displayName: 'DotNetCore Build $(solution) - $(buildConfiguration)'
    inputs:
      command: 'build'
      projects: '$(solution)'
      arguments: '--configuration $(buildConfiguration)'
```

**Area for Triage**: 
.NET Core

**Question, Bug, or Feature?**: 
Bug

**Virtual environments affected**
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [x] Ubuntu 18.04 LTS
- [ ] Ubuntu 20.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Expected behavior**
dotnetcore command should execute successfully

**Actual behavior**
134 exit code

1. Create a new yaml pipeline using an Ubuntu1804 VMSS Agent Pool built using the ubuntu1804 packer file from this repository
2. Run the pipeline

**Comment by maxim-lobanov** [comment]
@mihsoft , Am I right that this issue doesn't reproduce on Hosted agents?

**Comment by mihsoft** [comment]
@maxim-lobanov indeed, it appears to be an issue only when utilising the image with a VMSS scale set + the Azure DevOps VMSS extension.

**Comment by maxim-lobanov** [comment]
@mihsoft , I see.
In this case, I think that this repository is incorrect place for both (#1287 and #1240) issues. Our team (this repository) owns only image content and image-generation process and unfortunately, we are not experts with Azure services.

@WillLennon, If this issue looks related to #1240, could you please advice the place where this issue can be transferred for your team to take a look?

**Comment by mihsoft** [comment]
thanks @maxim-lobanov, apologies for logging in the wrong place.

**Comment by mihsoft** [comment]
@maxim-lobanov I think there might be some merit in investigating this,

When executing the linux **nice** command on Microsoft hosted agents it returns **0**, when executing on a VM built using the virtual-environments images it returns **2**. The **/etc/security/limits.conf** is the same on both boxes, is there something else Microsoft is executing on their hosted agents that is not included with the virtual-environments images?

**Comment by maxim-lobanov** [comment]
I think the difference is [azure-pipelines-agent](https://github.com/Microsoft/azure-pipelines-agent) between machine and Azure DevOps that is some kind of wrapper for all commands but I am not sure how it could cause this specific issue 

cc: @al-cheb, @WillLennon for any thoughts.

**Comment by mihsoft** [comment]
@maxim-lobanov just an update from further investigations on our side,

If we use a VM with the default ubuntu-1804 image and install an azure agent on it then the issue is not present and dotnetcore works as expected.

If we use a VM with the packer ubuntu-1804 image from this repository we receive the dotnetcore error

**Comment by mihsoft** [comment]
@maxim-lobanov - I am closing this issue now as it has been picked up by the Azure DevOps team.

For anyone else arriving at this ticket please see the following which provides a workaround: https://developercommunity.visualstudio.com/content/problem/1124438/linux-scale-set-agents-agentlistener-processs-star.html
