### ISSUE TITLE
Add Netlify CLI

### ISSUE THREAD

**Issue by lannonbr** [actions/virtual-environments#1289]
**Tool information**
- Tool name: netlify-cli
- Tool license: MIT
- Add or update? Add
- Desired version: 2.58.0
- Approximate size:
- If this is an add request:
  - Brief description of tool: CLI to interact with Netlify.
  - URL for tool's homepage: https://github.com/netlify/cli
  - Provide a basic test case to validate the tool's functionality: Deploy a website to Netlify
```sh
netlify-cli deploy --dir=<site_dir> --prod
```

**Area for Triage**: Deployment/Release

**Question, Bug, or Feature?**: Feature

**Virtual environments affected**
- [ ] macOS 10.15
- [x] Ubuntu 16.04 LTS
- [x] Ubuntu 18.04 LTS
- [x] Ubuntu 20.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Can this tool be installed during the build?**
```sh
npm i -g netlify-cli
```

**Tool installation time in runtime** About 1 minute

**Are you willing to submit a PR?** Definitely!

**Comment by maxim-lobanov** [comment]
Hello, thank you for feature request.
We would like to keep it in active state for a while to see popularity

**Comment by maxim-lobanov** [comment]
Hello, we don't have concerns about pre-installing this tool on image.
Feel free to submit PR

**Comment by maxim-lobanov** [comment]
Hello, changes are deploying right now. We will report as soon as deployment is finished

**Comment by lannonbr** [comment]
I was able to confirm with the latest build image that this is now installed so I'm going to close the issue as it's complete
