### ISSUE TITLE
Ubuntu 1804 packer file failure - azure-arm: AWS SAM CLI was not installed

### ISSUE THREAD

**Issue by mihsoft** [actions/virtual-environments#1293]
**Describe the bug**
Using the existing ubuntu1804 packer file as a base, I receive an error:
`azure-arm: AWS SAM CLI was not installed
`
Have run this three times and the same error is generated each time.

```
    azure-arm: awslabs-aws-sam-cli-aa21a2d/tests/unit/test_yamlhelper.py

==> azure-arm: cp: cannot create directory '/opt/python-aws-sam-cli': Permission denied

==> azure-arm: /tmp/script_7947.sh: line 24: /opt/python-aws-sam-cli/3.7*/x64/bin/python3: No such file or directory

==> azure-arm: /tmp/script_7947.sh: line 25: /opt/python-aws-sam-cli/3.7*/x64/bin/python3: No such file or directory

==> azure-arm: ln: failed to create symbolic link '/usr/local/bin/sam': Permission denied
    azure-arm: Testing to make sure that script performed as expected, and basic scenarios work
```

**Area for Triage**: 

**Question, Bug, or Feature?**: 
Bug

**Virtual environments affected**
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [x] Ubuntu 18.04 LTS
- [ ] Ubuntu 20.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Expected behavior**
Successful run

**Actual behavior**
A description with steps to reproduce the issue. If your have a public example or repo to share,
please provide the link.

Run the packer file on a Microsoft hosted ubuntu-latest vmImage agent

**Comment by mihsoft** [comment]
Closed this ticket as it looks like this - https://github.com/actions/virtual-environments/commit/16f3e4b83ce020e743104ba413a04892abbf1e7c#diff-b20d8b541c5048ae4994d6d6db9db0e1 may fix the issue.

**Comment by mihsoft** [comment]
azure-arm: awslabs-aws-sam-cli-aa21a2d/tests/unit/test_yamlhelper.py

==> azure-arm: cp: cannot create directory '/opt/python-aws-sam-cli': Permission denied

==> azure-arm: /tmp/script_7947.sh: line 24: /opt/python-aws-sam-cli/3.7*/x64/bin/python3: No such file or directory

==> azure-arm: /tmp/script_7947.sh: line 25: /opt/python-aws-sam-cli/3.7*/x64/bin/python3: No such file or directory

==> azure-arm: ln: failed to create symbolic link '/usr/local/bin/sam': Permission denied
    azure-arm: Testing to make sure that script performed as expected, and basic scenarios work

**Comment by vsafonkin** [comment]
Hi @mihsoft , do you still have problem with Ubuntu image generation?

**Comment by mihsoft** [comment]
@vsafonkin yes, using the latest failed with the same:

```
==> azure-arm: cp: cannot create directory '/opt/python-aws-sam-cli': Permission denied

==> azure-arm: /tmp/script_7947.sh: line 24: /opt/python-aws-sam-cli/3.7*/x64/bin/python3: No such file or directory

==> azure-arm: /tmp/script_7947.sh: line 25: /opt/python-aws-sam-cli/3.7*/x64/bin/python3: No such file or directory

==> azure-arm: ln: failed to create symbolic link '/usr/local/bin/sam': Permission denied
    azure-arm: Testing to make sure that script performed as expected, and basic scenarios work

==> azure-arm: /tmp/script_7947.sh: line 30: sam: command not found
    azure-arm: AWS SAM CLI was not installed

```

**Comment by mihsoft** [comment]
@vsafonkin I think I forgot to update the custom json, sorry, will close and re-open if it fails on the new version.
