### ISSUE TITLE
Update/Add SQL2017 LocalDB

### ISSUE THREAD

**Issue by musmuris** [actions/virtual-environments#1294]
**Tool information**
- Tool name: SQL2017 Local DB
- Tool license: MS redistributeable?
- Add or update? Update from SQL2016
- Desired version: Latest
- Approximate size: 

**Area for Triage**:
Databases

**Question, Bug, or Feature?**:
Feature

**Virtual environments affected**
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Ubuntu 20.04 LTS
- [ ] Windows Server 2016 R2
- [X] Windows Server 2019

**Can this tool be installed during the build?**
?

**Tool installation time in runtime**
?

**Are you willing to submit a PR?**
sure but where to start?

**Comment by carl-berg** [comment]
I am also interested in this, although in my case I would prefer _SQL2019 Local DB_, but just having 2017 would suffice for now.

**Comment by andy-mishechkin** [comment]
Hello, @musmuris 
As far as I know SQL Server LocalDB is a feature of SQL Server Express. Now we have SQL Server Express 2019 deployed with Windows -2019 image.
Would you please check the image version which you using for your tasks. Also may you provide link to your pipeline for detailed analyzing.
Thank you.

**Comment by musmuris** [comment]
@andy-mishechkin  Thanks. We have automated tests that use localdb - so _some_ flavour was installed already. But we got the error 

> OneTimeSetUp: Microsoft.SqlServer.Dac.DacServicesException : An error occurred during deployment plan generation. Deployment cannot continue. ----> Microsoft.Data.Tools.Schema.Sql.Deployment.DeploymentCompatibilityException : A project which specifies SQL Server 2017 as the target platform cannot be published to SQL Server 2016

so assumed it was the old one.  

Image is windows-latest 

I'm also trying to get the default version using:
```yaml
- task: CmdLine@2
  inputs:
    script: 'sqlcmd -S "(localdb)\MSSQLLocalDB" -Q "SELECT @@VERSION;"'
```

but that is timing out as azure pipelines seem to be running real slow right now.

**Comment by musmuris** [comment]
Ah there we go - added a login timeout of 60 seconds.  Default is 2016

> Microsoft SQL Server 2016 (SP1) (KB3182545) - 13.0.4001.0 (X64) 
> 	Oct 28 2016 18:17:30 
> 	Copyright (c) Microsoft Corporation
> 	Express Edition (64-bit) on Windows Server 2019 Datacenter 6.3 <X64> (Build 17763: ) (Hypervisor)
>

**Comment by musmuris** [comment]
@andy-mishechkin  I would also be cool with SQL2019 local DB as well

**Comment by maxim-lobanov** [comment]
Hello @musmuris , we wouldn't like to pre-install SQL2017 LocalDB on images.
But we have an issue to install SQL Server 2019 (and SQL2019 LocalDB too as a part): #1282 
If it works for you, please upvote.

**Comment by musmuris** [comment]
@maxim-lobanov  Yes SQL2019 works fine - and indeed that's what I've been doing as a task anyway 
```yaml
- task: PowerShell@2
  displayName: Install SQL 2019 Localdb
  inputs:
    targetType: 'inline'
    script: |
      Write-Host "Downloading"
      Import-Module BitsTransfer
      Start-BitsTransfer -Source https://download.microsoft.com/download/7/c/1/7c14e92e-bdcb-4f89-b7cf-93543e7112d1/SqlLocalDB.msi -Destination SqlLocalDB.msi
      Write-Host "Installing"
      Start-Process -FilePath "SqlLocalDB.msi" -Wait -ArgumentList "/qn", "/norestart", "/l*v SqlLocalDBInstall.log", "IACCEPTSQLLOCALDBLICENSETERMS=YES";
      Write-Host "Checking"
      sqlcmd -l 60 -S "(localdb)\MSSQLLocalDB" -Q "SELECT @@VERSION;"
```
