### ISSUE TITLE
I believe the version numbers are wrong for the Wix Toolset

### ISSUE THREAD

**Issue by adamsiembida** [actions/virtual-environments#1299]
**Describe the bug**
I believe the version numbers for the Wix Toolset and Wix Visual Studio Extension are flipped in the [readme for Microsoft Windows Server 2019 Datacenter](https://github.com/actions/virtual-environments/blob/master/images/win/Windows2019-Readme.md) and [readme for Microsoft Windows Server 2016 Datacenter](https://github.com/actions/virtual-environments/blob/master/images/win/Windows2016-Readme.md) and possibly elsewhere.

WIX Toolset -- 1.0.0.4
WIX Toolset Studio 2019 Extension -- 3.11.4516

**Area for Triage**: 
?

**Question, Bug, or Feature?**: 
Bug

**Virtual environments affected**
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Ubuntu 20.04 LTS
- [x] Windows Server 2016 R2
- [x] Windows Server 2019

**Expected behavior**
Read the file and become informed.

**Actual behavior**
Confusion.

**Comment by maxim-lobanov** [comment]
Hello @adamsiembida , thank you for report.
Looks like [you are absolutely right](https://github.com/actions/virtual-environments/blob/main/images/win/scripts/SoftwareReport/SoftwareReport.VisualStudio.psm1#L38), we will take care about fixing that.

**Comment by dibir-magomedsaygitov** [comment]
Hello, @adamsiembida.
Changes with the fix to our Windows documentation were merged in scope of [this](https://github.com/actions/virtual-environments/pull/1302) PR. Documentation will be updated with the next image-rollout.

**Comment by dibir-magomedsaygitov** [comment]
Hello, @adamsiembida.
Changes with the fix to our Windows documentation were delivered to all VMs. Documentation now shows correct version numbers for the Wix Toolset and Wix Visual Studio Extension.
I'm closing this issue, feel free to contact us if you have any concerns.
