### ISSUE TITLE
Update/Add awscli

### ISSUE THREAD

**Issue by jherico** [actions/virtual-environments#13]
Aws cli is available on Ubuntu environments, but not on Windows environments

**Tool information**
- Tool name: awscli
- Add or update? add
- Desired version: latest version
- Approximate size: 90 MB
- If this is an add request:
  - Brief description of tool: command line interface for interacting with AWS services
  - URL for tool's homepage: https://aws.amazon.com/cli/

**Virtual environments affected**
- [x] macOS 10.14
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [x] Windows Server 2016 R2
- [x] Windows Server 2019

**Can this tool be installed during the build?**
On windows environments a user can run `pip install awscli` to get a python version of the tool, but there's a small pre-built binary available from Amazon that would be useful to reduce build time

**Comment by kaylangan** [comment]
Thanks for the suggestion! I'm going to check the macOS box too since I think we'll want to have this on all the virtual environments.

**Comment by rayanalsubhi-feenics** [comment]
That would be a great tool to add as we currently waste time on installing it for our Windows workloads.

**Comment by maxim-lobanov** [comment]
The quickest way to install this tool:
```
# Windows
choco install awscli
# macOS
brew install awscli
```
Installation takes about 30 seconds on macOS and 1 minute on Windows.
Probably, it is something that we should pre-install to the image

**Comment by dibir-magomedsaygitov** [comment]
AWS CLI has been successfully added to macOS in scope of [this](https://mseng.visualstudio.com/AzureDevOps/_git/Mac-Cloud/pullrequest/542723) PR and to win16 and win19 in scope of [this](https://github.com/actions/virtual-environments/pull/610) PR.
 Changes were merged and will be delivered to all VMs in a week.

**Comment by dibir-magomedsaygitov** [comment]
AWS CLI has been successfully added to macOS and to win16 and win19. Feel free to contact if you have any issues.
