### ISSUE TITLE
When using 2019 virtual env in Azure Pipeline in ADO it failed for a serverless deploy using AWS CLI

### ISSUE THREAD

**Issue by recintoit** [actions/virtual-environments#1300]
**Describe the bug**
Using Virtual environment Windows Server 2019 in a deployment for deploying Serverless, Powershell exits with error code 1
This deployment worked on 7/21/20, then we had a failed deployment when we tried on 7/22/20.  
I'm considering this a bug because we changed the virtual environent for Azure Pipeline agent to WIndows 2016 and it deploys with no error.  I noticed there was an update to the Win2019 environment used 5 days ago?
I compared the initialization logs from a good deployment and there are some differences in the OS logging.

Example:
2020-07-24T20:31:24.5821308Z ##[section]Starting: Initialize job
2020-07-24T20:31:24.5824498Z Agent name: 'Azure Pipelines 6'
2020-07-24T20:31:24.5828628Z Agent machine name: 'WIN-6FLICLRU763'
2020-07-24T20:31:24.5829238Z Current agent version: '2.172.2'
2020-07-24T20:31:24.5868430Z Current image version: '20200720.1'
2020-07-24T20:31:24.5880122Z Agent running as: 'VssAdministrator'
2020-07-24T20:31:24.5892307Z Prepare release directory.
2020-07-24T20:31:24.5901541Z ReleaseId=208, TeamProjectId=RemovedID, ReleaseDefinitionName= (removed the name)
2020-07-24T20:31:24.6552156Z Release folder: D:\a\r1\a
2020-07-24T20:31:24.6771238Z Environment variables available are below.  Note that these environment variables can be referred to in the task (in the ReleaseDefinition) by replacing "_" with "." e.g. AGENT_NAME environment variable can be referenced using Agent.Name in the ReleaseDefinition: 
				[AGENT_DISABLELOGPLUGIN_TESTFILEPUBLISHERPLUGIN] --> [true]
				[AGENT_DISABLELOGPLUGIN_TESTRESULTLOGPLUGIN] --> [true]
				[AGENT_HOMEDIRECTORY] --> [C:\agents\2.172.2]
				[AGENT_ID] --> [1889]
				[AGENT_JOBNAME] --> [Deploy]
				[AGENT_MACHINENAME] --> [WIN-6FLICLRU763]
				[AGENT_NAME] --> [Azure Pipelines 6]
				[AGENT_OS] --> [Windows_NT]
				[AGENT_OSARCHITECTURE] --> [X64]
				[AGENT_RELEASEDIRECTORY] --> [D:\a\r1\a]
				[AGENT_RETAINDEFAULTENCODING] --> [false]
				[AGENT_ROOTDIRECTORY] --> [D:\a]
				[AGENT_SERVEROMDIRECTORY] --> [C:\agents\2.172.2\externals\vstsom]
				[AGENT_TEMPDIRECTORY] --> [D:\a\_temp]
				[AGENT_TOOLSDIRECTORY] --> [C:/hostedtoolcache/windows]
				[AGENT_VERSION] --> [2.172.2]

**Area for Triage**: 

# Area: Servers
- valueFor: '**Area for Triage**'
  contains: 'Servers'
  addLabels: ['Area: Servers']

**Question, Bug, or Feature?**: 
Bug

**Virtual environments affected**

- [x] Windows Server 2019

**Expected behavior**
We expected the deployment to and run the command serverless.cmd deploy, but it fails.  

**Actual behavior**
AWS logs in but then fails after the serverless deploy command. We initially thougth this was an AWS credential issue or perhaps a Route 53 issue because a false postive error messege when we ran serverless create_domain.

1. Step 1  ( I will send screenshots and update this thread)

**Comment by recintoit** [comment]
To recreate this event the ADO release pipeline, setup Serverless with 'domain manager' configured.  Using ADO variable groups with AWS credentials masked.
Deploy to an existing domain in AWS.  With 2019, PS exits with error,  Win2016 is successful.  

Attaching screenshots, and below are references to serverless domain manager
https://www.serverless.com/blog/serverless-api-gateway-domain 
https://github.com/amplify-education/serverless-domain-manager

Here is the script that fails for 2019 agent:
# Write your PowerShell commands here.

npm install serverless -g
npm install serverless-domain-manager -g

$env:SLS_DEBUG=true
Write-Host "Set AWS credentials for serverless..." 
C:\npm\prefix\serverless.cmd config credentials --provider aws --stage $env:REL_STAGE --account $env:AWS_ACCOUNT  --region $env:AWS_REGION --key $env:AWS_KEY --secret $(AWSDeploySecret)
Write-Host "Running createDomain to apply certificate and host name"
C:\npm\prefix\serverless.cmd create_domain --stage $env:REL_STAGE --account $env:AWS_ACCOUNT --region $env:AWS_REGION --verbose
Write-Host "Running serverless deploy..." 
C:\npm\prefix\serverless.cmd deploy --stage $env:REL_STAGE --account $env:AWS_ACCOUNT --region $env:AWS_REGION --verbose
![ADO_win2019_issue_1](https://user-images.githubusercontent.com/35378940/88479731-2d00c500-cf06-11ea-8bea-f3783bebeb8e.JPG)
![error1](https://user-images.githubusercontent.com/35378940/88479732-2d995b80-cf06-11ea-9807-decbaef01897.JPG)
![log_on_failed_deploy_2019](https://user-images.githubusercontent.com/35378940/88479733-2e31f200-cf06-11ea-9007-6461606cd203.JPG)
![screen_success_configwith_2016](https://user-images.githubusercontent.com/35378940/88479734-2e31f200-cf06-11ea-9000-c1c7bb1f3583.JPG)
![setup_when-error](https://user-images.githubusercontent.com/35378940/88479735-2e31f200-cf06-11ea-849f-bea703fbab9d.JPG)
![success_agent_log](https://user-images.githubusercontent.com/35378940/88479737-2eca8880-cf06-11ea-854c-f29834395126.JPG)
![Success_serverless](https://user-images.githubusercontent.com/35378940/88479738-2eca8880-cf06-11ea-881a-0759ceb3d2b0.JPG)
![successtest_win2016_agent](https://user-images.githubusercontent.com/35378940/88479739-2eca8880-cf06-11ea-9d0f-b828e55ec6db.JPG)

**Comment by vsafonkin** [comment]
Hi @recintoit , as I see in logs, `serverless-domain-manager` is not installed on Win2019 build:
![Screenshot 2020-07-27 at 2 09 26 PM](https://user-images.githubusercontent.com/7628945/88535853-5fe4af00-d013-11ea-9d36-2a809a6ae0e7.png)

Win2016 build:
![Screenshot 2020-07-27 at 2 09 56 PM](https://user-images.githubusercontent.com/7628945/88535879-6c690780-d013-11ea-99f0-c9987a7f26d8.png)

are you sure that script is the same for both builds?

**Comment by recintoit** [comment]
I see that in the screenshot and apologize.  I was testing by removing that out to see if that was the error.  It errors if that command was commented out or not.  Below is the script that was failing at first whether commented out or not.  To test, in the same stage, I created the similar task with 'Agent Job', Extract files, Node.js installer, and the Powershell script.  I kept the same PS script but changed one take to 2016.  I will provide the screenshots.

# Write your PowerShell commands here.

npm install serverless -g
npm install serverless-domain-manager -g

$env:SLS_DEBUG=true
Write-Host "Set AWS credentials for serverless..." 
C:\npm\prefix\serverless.cmd config credentials --provider aws --stage $env:REL_STAGE --account $env:AWS_ACCOUNT  --region $env:AWS_REGION --key $env:AWS_KEY --secret $(AWSDeploySecret)
Write-Host "Running createDomain to apply certificate and host name"
C:\npm\prefix\serverless.cmd create_domain --stage $env:REL_STAGE --account $env:AWS_ACCOUNT --region $env:AWS_REGION --verbose
Write-Host "Running serverless deploy..." 
C:\npm\prefix\serverless.cmd deploy --stage $env:REL_STAGE --account $env:AWS_ACCOUNT --region $env:AWS_REGION --verbose

**Comment by recintoit** [comment]
This is the job log of the jobs where I did the above mentioned.  It is the same task, same stage running 2019 vs 2016
![versions](https://user-images.githubusercontent.com/35378940/88555998-5a6c7200-cfdd-11ea-991d-026686b7ffa1.JPG)
 test

**Comment by recintoit** [comment]
Thank you for pointing that out.  Here is the 'apples to apples' comparision logs.  I actually think it is failing at the serverless deploy command, I can see it checking custom_domain
![PS_log_2019_serverless_deploy](https://user-images.githubusercontent.com/35378940/88556648-1ded4600-cfde-11ea-8e23-b824ebc81a9f.JPG)
![PS_log_2016_serverless_deploy](https://user-images.githubusercontent.com/35378940/88556655-204fa000-cfde-11ea-8036-ca6c28c2e8ad.JPG)

**Comment by al-cheb** [comment]
@recintoit, Could you please use just for test  `cmd` shell for Windows Server 2019 instead of PowerShell?

**Comment by recintoit** [comment]
@al-cheb I don't have the time to work on that validation immediately due to some work priorities.  I am not sure if you would be able to re-create a serverless deploy using 2019.  It's almost like it is failing on the credential phase (line 47 in one screenshot).  I can try to run it in cmd when I get some time. I may just try a 'serverless.cmd aws config' in PS and cmd using the same format, but hardcoded creds to see if that is the issue.  Thanks

**Comment by al-cheb** [comment]
@recintoit ,
We have had the pretty similar behavior - https://github.com/actions/virtual-environments/issues/1151. As another solution you could you: `cmd /c "C:\npm\prefix\serverless.cmd config credentials --provider aws --stage $env:REL_STAGE --account $env:AWS_ACCOUNT --region $env:AWS_REGION --key $env:AWS_KEY --secret $(AWSDeploySecret) 2>&1"`

**Comment by recintoit** [comment]
@al-cheb 
I just want to confirm that you want me run the 'cmd /c' within Powershell Script, and not to create new task for 'Command Line Script' and use the command.
Thank you

**Comment by recintoit** [comment]
I used the workaround you provided and was unsuccessful using 2019. I used Powershell and used the cmd /c method, then I tried to put the same code in with a command line task.
![image](https://user-images.githubusercontent.com/35378940/88729123-00a49e80-d0e8-11ea-965d-3ae096950c77.png)


![image](https://user-images.githubusercontent.com/35378940/88729045-d94dd180-d0e7-11ea-8a09-b70dfc75d87c.png)

**Comment by recintoit** [comment]
@al-cheb  The workaround works.  Thank you.  My team now can decided the best Agent version to use.
![image](https://user-images.githubusercontent.com/35378940/88729919-c4723d80-d0e9-11ea-9986-1e39795d39d8.png)
