### ISSUE TITLE
HOME environment variable not set on Windows machines

### ISSUE THREAD

**Issue by axel-op** [actions/virtual-environments#1301]
**Describe the bug**
On [this page of the documentation](https://docs.github.com/en/actions/configuring-and-managing-workflows/using-environment-variables#default-environment-variables), the `HOME` environment variable is listed as a default variable which should be set "in all runner environments", however it is not when using `windows-latest` environments.

**Area for Triage**: JavaScript and Node.js

**Question, Bug, or Feature?**: Bug

**Virtual environments affected**
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Ubuntu 20.04 LTS
- [ ] Windows Server 2016 R2: haven't tested with this one
- [x] Windows Server 2019

**Expected behavior**
The `HOME` environment variable should be set, or the documentation should be edited.

**Actual behavior**
> A description with steps to reproduce the issue. If your have a public example or repo to share,
please provide the link.

In a Javascript action, check the keys of the `process.env` dictionary.

**Comment by maxim-lobanov** [comment]
Hello, thank you for report.
Actually, HOME variable doesn't exist in Windows by default. Instead it has `HOMEPATH` and `USERPROFILE` (contains the same value).
We will consider adding variable for consistency or updating documentation

**Comment by maxim-lobanov** [comment]
Hello, we wouldn't like to add new variable to Windows environments. We will update documentation to avoid confusing.
