### ISSUE TITLE
Ubuntu 16.04 openssl version

### ISSUE THREAD

**Issue by chancancode** [actions/virtual-environments#1307]
**Describe the bug**

Ubuntu 16.04 comes with openssl 1.0.2g by default. Same goes for related packages like libssl-dev. However, openssl 1.1.1g is installed on the ubuntu-16.04 virtual environment.

**Area for Triage**:  Packages

**Question, Bug, or Feature?**: Bug

**Virtual environments affected**
- [ ] macOS 10.15
- [x] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Ubuntu 20.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Expected behavior**

openssl 1.0.2g should be present, or at least when `apt-get install`-ing `openssl`, `libssl-dev`, etc, that version should be installed.

**Actual behavior**

openssl 1.1.1g is installed instead. This means code compiled on this GH virtual environment that dynamically links against libssl will not work on a stock Ubuntu 16.04 environment. This is unfortunate because one of the reason for picking `ubuntu-16.04` specifically is probably to test and build your package for that environment.

Perhaps this is done intentionally, if it can't be "fixed", it should be explicitly documented/enumerated/called out on the package list, since I think the general expectation of a non-rolling release like Ubuntu is you get the "system" version of packages.

**Comment by chancancode** [comment]
The package appears to be pulled in via https://github.com/actions/virtual-environments/blob/97e4ea8356c3470319eedd442645607ddce6a985/images/linux/scripts/installers/php.sh#L15, intentionally or not.

**Comment by al-cheb** [comment]
Hello, @chancancode 
I will prepare PR to provide additional information about `openssl` and `libssl-dev` packages for Ubuntu, because revert to 1.0.2g will break other customers.

To revert `openssl` and `libssl-dev` packages to previous version you could use:

```
# List available packages
~$ apt-cache madison openssl libssl-dev
   openssl | 1.1.0h-2.0+ubuntu16.04.1+deb.sury.org+1 | http://ppa.launchpad.net/ondrej/php/ubuntu xenial/main amd64 Packages
   openssl | 1.0.2g-1ubuntu4.16 | http://azure.archive.ubuntu.com/ubuntu xenial-updates/main amd64 Packages
   openssl | 1.0.2g-1ubuntu4.16 | http://security.ubuntu.com/ubuntu xenial-security/main amd64 Packages
   openssl | 1.0.2g-1ubuntu4 | http://azure.archive.ubuntu.com/ubuntu xenial/main amd64 Packages
libssl-dev | 1.1.1g-1+ubuntu16.04.1+deb.sury.org+1 | http://ppa.launchpad.net/ondrej/php/ubuntu xenial/main amd64 Packages
libssl-dev | 1.0.2g-1ubuntu4.16 | http://azure.archive.ubuntu.com/ubuntu xenial-updates/main amd64 Packages
libssl-dev | 1.0.2g-1ubuntu4.16 | http://security.ubuntu.com/ubuntu xenial-security/main amd64 Packages
libssl-dev | 1.0.2g-1ubuntu4 | http://azure.archive.ubuntu.com/ubuntu xenial/main amd64 Packages
```

Pipeline:
```
 steps:
    - name: Install openssl&libssl-dev
      run: |
        sudo apt-get install -y --allow-downgrades openssl=1.0.2g-1ubuntu4.16 libssl-dev=1.0.2g-1ubuntu4.16
    - name: Display openssl&libssl-dev versions
      run: dpkg -l openssl libssl-dev | grep '^ii' | cut -c5-
```

![image](https://user-images.githubusercontent.com/47745270/88660626-c2a37c80-d0df-11ea-91c8-54a5cac02029.png)

**Comment by chancancode** [comment]
Yeah that's what we end up doing as well. It seems like you'd need to downgrade libssl itself as well, I thought downgrading openssl/libssl-dev would force the dependencies to be downgraded as well, but that doesn't seem to be the case.

This still seems quite unexpected to me, but I understand it's probably "too late" to fix now. Was this done intentionally, or was it just an accidental side-effect of pulling in the PHP ppa? (FWIW, they seem to suggest that it's optional, so the PHP packages can be installed against the older openssl/libssl, supposedly.)

Is this a rare exception or are there other upgraded "system libraries/packages" that are worth calling out as well?

**Comment by chancancode** [comment]
Update: we end up removing the PHP ppa, removed the packages, then reinstalled them so we will get the "correct" one from the system sources (so we don't pin to a particular version)

**Comment by wagenet** [comment]
Looks like `libssl` is installed as `libssl1.0` so that's ok. It's only `libssl-dev` that's at a newer version.

**Comment by al-cheb** [comment]
The documentation has been updated - https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu1604-README.md

- OpenSSL 1.1.0h 27 Mar 2018 (Library: OpenSSL 1.1.1g 21 Apr 2020)
