### ISSUE TITLE
Add Xcode 11.3 beta

### ISSUE THREAD

**Issue by ydnar** [actions/virtual-environments#131]
**Tool information**
- Tool name: 
- Add or update? 
- Desired version: 11.3 beta
- Approximate size: ~9GB
- If this is an add request:
  - Brief description of tool: most recent version of Xcode
  - URL for tool's homepage: https://developer.apple.com

**Virtual environments affected**
- [x] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Can this tool be installed during the build?**
Sort of—via [`xcode-install`](https://github.com/xcpretty/xcode-install). It takes a while.

**Are you willing to submit a PR?**
Sure?

**Notes**
Xcode 11.3 fixes a [major bug](https://bugs.swift.org/browse/SR-11564) in the Swift toolchain that breaks apps built with Xcode 11.2.x using Swift packages.

**Comment by kaylangan** [comment]
This is currently rolling out (and may have already reached your account). Docs updates will follow.
