### ISSUE TITLE
Add brotli

### ISSUE THREAD

**Issue by vhiairrassary** [actions/virtual-environments#1313]
**Tool information**
- Tool name: brotli (https://github.com/google/brotli)
- Tool license: MIT (https://github.com/google/brotli/blob/master/LICENSE)
- Add or update? Add
- Desired version: No specific need, but latest is from Oct 2018 (https://github.com/google/brotli/releases/tag/v1.0.7). It is available in standard Ubuntu repositories: 18.04 (v1.0.3) & 20.04 (v1.0.7).
- Approximate size: 730.0 kB ([Installed size in Ubuntu 20.04](https://packages.ubuntu.com/bionic/brotli))
- If this is an add request: 
  - Brief description of tool: Brotli is a generic-purpose lossless compression algorithm. It is supported by major browsers (https://caniuse.com/#feat=brotli). It help to reduce bandwidth usage. Usually it is used in CI/CD jobs to compress assets.
  - URL for tool's homepage: 
  - Provide a basic test case to validate the tool's functionality:

```bash
# check installation
brotli --version

# check programme (must output `Hello!`)
echo 'Hello!' | brotli | brotli --decompress
```

**Area for Triage**:

**Question, Bug, or Feature?**:

**Virtual environments affected**
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Ubuntu 20.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Can this tool be installed during the build?**

**Tool installation time in runtime**

**Are you willing to submit a PR?**

**Comment by dibir-magomedsaygitov** [comment]
Hello @vhiairrassary. 
Thank you for your request. Am i right that you want this tool for Ubuntu 18 and Ubuntu 20 images?

**Comment by vhiairrassary** [comment]
Exactly. Thx for that fast answer!

**Comment by maxim-lobanov** [comment]
Thank you for contribution. Changes will be deployed in a week

**Comment by vhiairrassary** [comment]
Awesome! Thank you for your help

**Comment by vhiairrassary** [comment]
Tested & validated with `ubuntu-latest` 🎉 Thank you again for your help!
