### ISSUE TITLE
Add libc++ & libc++abi for all Ubuntu images

### ISSUE THREAD

**Issue by dpaoliello** [actions/virtual-environments#1314]
**Tool information**
- Tool name: libc++ and libc++abi
- Tool license: MIT license
- Add or update? Add
- Desired version: Latest
- Approximate size: ~7Mb
- If this is an add request:
  - Brief description of tool: LLVM C++ Standard Library and "low level support" library.
  - URL for tool's homepage: https://libcxx.llvm.org/index.html
  - Provide a basic test case to validate the tool's functionality:
```
echo "#include <cstdlib>" > test.cpp && clang++ -stdlib=libc++ test.cpp -c
```

**Area for Triage**:
C/C++

**Question, Bug, or Feature?**:
Feature

**Virtual environments affected**
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [X] Ubuntu 18.04 LTS
- [X] Ubuntu 20.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Can this tool be installed during the build?**
Not that I could figure out: installing LLVM via HomeBrew did not include the headers. It may be possible to compile it from source.

**Tool installation time in runtime**
<1 min (using apt)

**Are you willing to submit a PR?**
Yes

**Comment by maxim-lobanov** [comment]
Changes are merged. New image with these libraries will be deployed next week
