### ISSUE TITLE
Update/Add Maven

### ISSUE THREAD

**Issue by colemarkham** [actions/virtual-environments#132]
**Tool information**
- Tool name: Maven
- Add or update? Update
- Desired version: 3.6.3
- Approximate size: 
- If this is an add request:
  - Brief description of tool: 
  - URL for tool's homepage: 

**Virtual environments affected**
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [x ] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Can this tool be installed during the build?**

**Are you willing to submit a PR?**

3.6.2 introduced a regression which is breaking my builds. If possible, I would like to have an upgrade to 3.6.3. I use the ubuntu-latest image.

**Comment by colemarkham** [comment]
Added PR #133

**Comment by maxim-lobanov** [comment]
Looks like Maven was updated a lot of time ago and currently, Maven 3.6.3 is installed on Ubuntu images.
