### ISSUE TITLE
Update/Add VB6.0

### ISSUE THREAD

**Issue by kobi86** [actions/virtual-environments#1325]
**Tool information**
- Tool name: VB6.0
- Tool license: FREE
- Add or update? ADD
- Desired version: 6.0
- Approximate size: 
- If this is an add request:
  - Brief description of tool: Tool to compile VB 6 project , Fits embedded and IOT devices 
  - URL for tool's homepage: https://www.microsoft.com/en-us/download/details.aspx?id=5721
  - Provide a basic test case to validate the tool's functionality: Build and compile VB project 

**Area for Triage**:

**Question, Bug, or Feature?**:
Feature

**Virtual environments affected**
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Can this tool be installed during the build?**
No, it requires access to some windows folders and some configuration 

**Tool installation time in runtime**

**Are you willing to submit a PR?**
No

**Comment by AlenaSviridenko** [comment]
Hi @kobi86,
Unfortunately, it looks like VB 6 doesn't support either Windows Server 2016 or 2019:
![image](https://user-images.githubusercontent.com/8777209/89397985-36b1d600-d719-11ea-9c62-166d5c8e7f9c.png)

We are installing Visual Basic as a Visual Studio component for both platforms. Does it fit your needs?

**Comment by AlenaSviridenko** [comment]
Hi @kobi86,
Due to the inability to install such an outdated version of VB and no response from your side, I am going to close this issue.
Please, feel free to create a new one for any questions. Thank you!

**Comment by DaveInCaz** [comment]
@AlenaSviridenko as a general statement, VB6 can still be installed & operated on modern versions of Windows. Its too bad more specific details of the installation failure were not reported. This might be some known issue.

**Comment by kobi86** [comment]
Hi

Sorry for not updating.
I wanted to know if its possible to install it as a separate component from
Visual studio.

PS, is it possible to add code composer to the windows agent?

Thank you in advance

**Comment by AlenaSviridenko** [comment]
Thank you for clarification, we will continue investigating possible ways to install this software.

**Comment by vsafonkin** [comment]
Hello @kobi86 
Unfortunately, we cannot install visual basic 6.0 for several reasons:
This requires a Visual Studio 6 installation, which is a very outdated product. There is no official source for Visual Studio 6  distribution. The link in the title post points to the patch for the installed Visual Studio 6. In addition, installing such old software requires a variety of tricks and will most likely not be stable, which will entail new problems. And Visual Basic 6 cannot be installed as a separate component for modern Visual Studio versions. Sorry.

About code composer: please, open new issue for it with additional info for this software.

Thank you!

**Comment by kobi86** [comment]
Ok, thank you for the clarification and try.

You can close this issue

**Comment by julianxhokaxhiu** [comment]
Is it possible to reconsider adding VB6.0 in portable mode? All you need installed are the VB6.0 Runtimes ( see https://sourceforge.net/projects/vb6extendedruntime/files/ ).

Regarding portable mode: https://archive.org/details/VisualBasic6Portable

Thank you in advance!

**Comment by miketimofeev** [comment]
@julianxhokaxhiu I believe it can be done in runtime using something like the following script to install runtimes
```
        run: |
          Start-DownloadWithRetry -Url "https://altushost-swe.dl.sourceforge.net/project/vb6extendedruntime/Visual%20Basic%206.0%20Runtime%20Plus%202.2.zip" -Name "vb.zip" -DownloadPath "C:\"
          Extract-7Zip -Path "C:\vb.zip" -DestinationPath "C:\"
          $process = Start-Process -FilePath "C:\VB6 Runtime Plus 2.2.exe" -ArgumentList "/silent" -Wait -PassThru        
          $exitCode = $process.ExitCode
          if ($exitCode -eq 0 -or $exitCode -eq 3010)
          {
              Write-Host "Installation successful"
          }
          else
          {
              Write-Host "Non zero exit code returned by the installation process: $exitCode"
              exit $exitCode
          }
```
