### ISSUE TITLE
Git commands behaving differently between ubuntu-latest & windows-latest vm

### ISSUE THREAD

**Issue by temelj** [actions/virtual-environments#1327]
**Describe the bug**
I have a very simple pipeline that contains absolutely no code, just performs a `-tastk: GitVersion@5` and runs a powershell `pwsh:` task to call `git tag` and `git push` operations.

I am have tested in on both the `windows-latest` and `ubuntu-latest` vmImage and found that it is failing every time for the windows image but passing as expected on ubuntu.

**Area for Triage**: Git

**Question, Bug, or Feature?**:  Bug

**Virtual environments affected**
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Ubuntu 20.04 LTS
- [ ] Windows Server 2016 R2
- [x] Windows Server 2019

**Expected behavior**
The expected behavior is for gitversion to bump the checkin version, and to successfully tag.

**Actual behavior**
I've prepared a repo to re-produce the issue - https://github.com/temelj/pipeline-gitver-tag-test

**Comment by al-cheb** [comment]
Hello, @temelj 
Could you please add `$env:GIT_REDIRECT_STDERR = '2>&1'` command at the top of the pwsh task?

![image](https://user-images.githubusercontent.com/47745270/88939828-aa725f80-d28f-11ea-8837-19fdbb095326.png)

**Comment by temelj** [comment]
Hi @al-cheb thank you for your reply.

How on earth did that fix my issue?

**Comment by al-cheb** [comment]
@temelj , https://stackoverflow.com/questions/34820975/git-clone-redirect-stderr-to-stdout-but-keep-errors-being-written-to-stderr/47232450#47232450
