### ISSUE TITLE
The latest vcpkg is broken, please don't take it

### ISSUE THREAD

**Issue by snnn** [actions/virtual-environments#1332]
**Describe the bug**
see: https://github.com/microsoft/vcpkg/issues/12565

I know your team usually generates a new set of images every week. But, the build script always take vcpkg from master, it is kind of dangerous.  Please consider to use tags.  The issue 12565 is an example, if you rebuild the image now, you'll have the bug, and would break all the vcpkg Windows users. 

**Area for Triage**: 
C/C++

**Question, Bug, or Feature?**: 
Bug

**Virtual environments affected**
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Expected behavior**
Rebuild the image
Try to use vcpkg to install protobuf/libffi or some other open source libraries
The should work fine

**Actual behavior**
It fails, even through it's not your fault. Here just kindly remind you there is a problem.  Please feel free to close this issue without taking extra actions.

**Comment by maxim-lobanov** [comment]
Hello @snnn , Thank you for reaching us.
Am I right that your suggestion to use latest release instead of master branch during installation?
https://github.com/microsoft/vcpkg/releases/latest

**Comment by snnn** [comment]
Yes!

**Comment by larshg** [comment]
It seems that CMake 18 is the culprint and it already hit the pipelines like here:

https://dev.azure.com/PointCloudLibrary/pcl/_build/results?buildId=17096&view=logs&j=d944f354-b9eb-5c76-5ade-3c70deb27a9e&t=fb7e0546-b0fe-5e7c-2a44-5710f4ba7243

So please make a hotfix when VCPKG has solved its bug.

**Comment by kcgen** [comment]
This has tanked our Windows CI since Monday.

**Comment by maxim-lobanov** [comment]
Just to merge discussions in #1340 and this issue:
Looks like rolling back vcpkg to the latest release will cause additional impact because of cmake incompatibility.
Installing master branch looks like the better solution for now.

cc: @strega-nil

**Comment by kcgen** [comment]
@maxim-lobanov , drop and update when the new Windows GitHub images are regenerated w/ the upated vcpkg.

Going on day 8 now with Windows CI broken, so can't wait for the fix :raised_hands: 

![2020-08-03_08-32](https://user-images.githubusercontent.com/1557255/89206500-3a552980-d56e-11ea-95d4-ed4232ab2953.png)

**Comment by maxim-lobanov** [comment]
Hello,
Based on conversation below and in #1340 we have decided to keep the current approach for now, install vcpkg from master branch during image generation. Per discussion, installing vcpkg from latest tag instead of master will bring more problems because of incompatibility with cmake.

I am closing this issue but if you have any other suggestions how we can improve installation process from our side, we are ready to continue discussion
