### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by YANZ-ndroid** [actions/virtual-environments#1333]
**Describe the bug**
A clear and concise description of what the bug is, and why you consider it to be a bug.

**Area for Triage**: 

**Question, Bug, or Feature?**: 

**Virtual environments affected**
- [x] macOS 10.15
- [x] Ubuntu 16.04 LTS
- [x] Ubuntu 18.04 LTS
- [ ] Ubuntu 20.04 LTS
- [x] Windows Server 2016 R2
- [x] Windows Server 2019

**Expected behavior**
A description of what you expected to happen.

**Actual behavior**
A description with steps to reproduce the issue. If your have a public example or repo to share,
please provide the link.

1. Step 1
2. Step 2

**Comment by dibir-magomedsaygitov** [comment]
Hello @YANZ-ndroid.
Could you please provide us ф clear and concise description of what the bug is, and why you consider it to be a bug. 
Thank you.
