### ISSUE TITLE
macOS DNS not resolving own hostname

### ISSUE THREAD

**Issue by rjmholt** [actions/virtual-environments#1335]
**Describe the bug**
Same as https://github.com/actions/virtual-environments/issues/1042.

In https://github.com/PowerShell/PowerShell/pull/13324 we're seeing a test failure in PowerShell code that looks like this:

```powershell
$hostName = [System.Net.Dns]::GetHostName()
[System.Net.Dns]::GetHostEntry($hostName)
```

Last time we were able to work around this by using the gateway address for our `Test-Connection` tests, but those started failing (see https://github.com/PowerShell/PowerShell/issues/13309, I'll try to get a repro in the same PR). Migrating back to our DNS lookup, I hit this issue.

**Area for Triage**: 
Apple

**Question, Bug, or Feature?**: 
Bug

**Virtual environments affected**
- [x] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Ubuntu 20.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Expected behavior**

The `[System.Net.Dns]::GetHostEntry()` call should resolve a DNS entry based on the hostname.

**Actual behavior**

```
  Describing Test-Connection
    [-] Error occurred in Describe block 0ms
      ExtendedSocketException: nodename nor servname provided, or not known
      MethodInvocationException: Exception calling "GetHostEntry" with "1" argument(s): "nodename nor servname provided, or not known"
      at <ScriptBlock>, /Users/runner/work/1/s/test/powershell/Modules/Microsoft.PowerShell.Management/Test-Connection.Tests.ps1: line 49
      at Invoke-Blocks, /Users/runner/work/1/a/bins/publish/Modules/Pester/4.10.1/Functions/SetupTeardown.ps1: line 135
      at Invoke-TestGroupSetupBlocks, /Users/runner/work/1/a/bins/publish/Modules/Pester/4.10.1/Functions/SetupTeardown.ps1: line 121
      at DescribeImpl, /Users/runner/work/1/a/bins/publish/Modules/Pester/4.10.1/Functions/Describe.ps1: line 209
```

As seen [here](https://dev.azure.com/powershell/PowerShell/_build/results?buildId=58829&view=logs&j=dd0d77e4-0911-5114-ec89-d447d00ba5e6&t=b551df83-c97f-5a24-b379-7e608cc7f18b).

**Comment by al-cheb** [comment]
Hello, @rjmholt 

Sorry for the trouble. We are planning to fix the issue in the next image roll-out.
```
jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: change name
      run: |
        name="mac-$(python -c 'from time import time; print int(round(time() * 1000))')"
        sudo scutil --set HostName "${name}.local"
        sudo scutil --set LocalHostName $name
        sudo scutil --set ComputerName "${name}.local"
    - name: resolve
      shell: pwsh
      run: |
        $hostName = [System.Net.Dns]::GetHostName()
        [System.Net.Dns]::GetHostEntry($hostName)
```
![image](https://user-images.githubusercontent.com/47745270/89012835-80667f00-d31b-11ea-8b09-30b0f7f96d56.png)

**Comment by al-cheb** [comment]
Hello, @rjmholt 
The fix has been deployed. The `[System.Net.Dns]::GetHostEntry()`  is working now.

![image](https://user-images.githubusercontent.com/47745270/89988748-a6c7db00-dc88-11ea-90cb-d4e09b37de5f.png)

**Comment by RoyGI** [comment]
Hi i update the mac to Big Sur and try the same code

var hostName = Dns.GetHostName();
var ipHostEntry = Dns.GetHostEntry(hostName);

and it fails but works if i add ".local"

var hostName = Dns.GetHostName();
 var ipHostEntry = Dns.GetHostEntry(hostName + ".local");

has any solution in order to avoid ".local"???

**Comment by zzambers** [comment]
I still [see](https://github.com/zzambers/testovacirepo/actions/runs/9872413421/job/27262479586) this problem on macos-13:
```
+ hostname
Mac-1720605937776.local
...
+ ping -c 4 Mac-1720605937776.local
ping: cannot resolve Mac-1720605937776.local: Unknown host
```
