### ISSUE TITLE
Update/Add gpg

### ISSUE THREAD

**Issue by jherico** [actions/virtual-environments#134]
**Tool information**
- Tool name: gpg
- Add or update? add
- Desired version: latest available
- Approximate size: a few megabytes
- If this is an add request:
  - Brief description of tool: cryptography tool
  - URL for tool's homepage: https://gnupg.org/

**Virtual environments affected**
- [x] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Can this tool be installed during the build?**
Yes via `brew install gnupg`

**Are you willing to submit a PR?**
I have no idea how to submit a PR for the virtual environment setup

gpg is available on Windows, (and I think on Linux) but not on MacOS.  This is strange since it's directly referenced by the actions documentation [here](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/creating-and-using-encrypted-secrets#limits-for-secrets)

While it can be installled via homebrew, having the documentation suggest it's use without also instructing a user to install it can lead to confusion and friction when using Actions.

**Comment by zackify** [comment]
Thanks for this, this article fails to mention it not working on mac os https://help.github.com/en/actions/automating-your-workflow-with-github-actions/creating-and-using-encrypted-secrets

**Comment by andy-mishechkin** [comment]
New images with gpg were deployed and I am closing the issue. 
Feel free to reopen if you'll find some issues in new images
