### ISSUE TITLE
How can I include Boost 1.72.0 on ubuntu-latest?

### ISSUE THREAD

**Issue by Astro36** [actions/virtual-environments#1344]
**Describe the bug**

CMake cannot find Boost 1.72.0 on ubuntu-latest.

I already set `BOOST_ROOT` env, but it doesn't work:

```txt
env:
  BOOST_ROOT: /usr/local/share/boost/1.72.0
```

Set `BOOST_ROOT`: [#661](https://github.com/actions/virtual-environments/issues/661#issuecomment-607680061)

Is there any way to include Boost without modifying `CMakeLists.txt` file?

**Area for Triage**: C/C++

**Question, Bug, or Feature?**: Question and Bug(?)

**Virtual environments affected**
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [x] Ubuntu 18.04 LTS
- [ ] Ubuntu 20.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Expected behavior**
CMake finds Boost Library and starts building.

**Actual behavior**
```txt
CMake Error at /usr/local/share/cmake-3.17/Modules/FindPackageHandleStandardArgs.cmake:164 (message):
  Could NOT find Boost (missing: Boost_INCLUDE_DIR) (Required is at least
  version "1.66")
```

Workflow YML: https://github.com/organization/Libreism/blob/dev/.github/workflows/cpp.yml
Workflow Result: https://github.com/organization/Libreism/runs/937881878
`CMakeLists.txt`: https://github.com/organization/Libreism/blob/dev/CMakeLists.txt

**Comment by maxim-lobanov** [comment]
Hello @Astro36 , I think it is because boost was moved under tool-cache directory ` /opt/hostedtoolcache/boost/1.72.0/x64`
I suggest to use environment variables and avoid hardcoding path:
```
steps:
- run: |
    echo "::set-env name=BOOST_ROOT::$BOOST_ROOT_1_72_0"
```

**Comment by Astro36** [comment]
Thank you!

Setting `BOOST_ROOT` env didn't work in my case, but I solved the problem by giving `Boost_INCLUDE_DIR` option to CMake directly:

```txt
steps:
- run: |
    cmake -S . -B build -DBoost_INCLUDE_DIR=$BOOST_ROOT_1_72_0/include
```

**Comment by varunagrawal** [comment]
@maxim-lobanov where can I find the docs for the environment variables? The README only mentions the installed software with their versions, but I don't see a comprehensive list of env variables.

**Comment by maxim-lobanov** [comment]
In Windows docs, env variables are included: https://github.com/actions/virtual-environments/blob/main/images/win/Windows2019-Readme.md#boost
But it looks like Ubuntu docs miss them. Variables are the same

**Comment by varunagrawal** [comment]
Well that's not good :disappointed: 
I'll open a PR to remedy this.
