### ISSUE TITLE
image :  Alibaba Cli version issue

### ISSUE THREAD

**Issue by vimor-bin** [actions/virtual-environments#1350]
1. There is a bug in the alibaba cli version, can it be updated to v3.0.55?
2. Please ask whether you are responsible for integrating Alibaba cli or alibaba-related students.

**Comment by miketimofeev** [comment]
Hi @vimor-bin!
1. Alibaba cli will be updated to 3.0.55 on Ubuntu & macOS images during this week's deployment.
2. We're not affiliated with Alibaba

**Comment by vimor-bin** [comment]
thx

**Comment by miketimofeev** [comment]
Alibaba Cli has been updated across all the images.
