### ISSUE TITLE
Update fastlane

### ISSUE THREAD

**Issue by mjvdende** [actions/virtual-environments#1357]
**Tool information**
- Tool name: fastlane
- Tool license: 
- Add or update? update
- Desired version: 2.154.0
- Approximate size: ?
- If this is an add request:
  - Brief description of tool: App automation done right
  - URL for tool's homepage: https://fastlane.tools/
  - Provide a basic test case to validate the tool's functionality: fastlane scan

**Area for Triage**:
['Area: Apple']

**Question, Bug, or Feature?**:
['question']

**Virtual environments affected**
- [x] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Ubuntu 20.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Can this tool be installed during the build?**
sudo gem install fastlane
sudo gem cleanup

**Tool installation time in runtime**
2min

**Are you willing to submit a PR?**
Yes

**Comment by miketimofeev** [comment]
Hi @mjvdende!
Fastlane is updated automatically. The new image with version 2.154.0 is supposed to be deployed by Friday

Temporary workaround:

```
    steps:
      - name: update fastlane
        run: |
          gem update fastlane
          fastlane --version

```

**Comment by al-cheb** [comment]
Hello, @mjvdende 
The new image has been deployed and Fastlane 2.154.0 is now available for macOS - https://github.com/actions/virtual-environments/blob/main/images/macos/macos-10.15-Readme.md
