### ISSUE TITLE
Update/Add buster version of buildpack-deps image in github runners image caches

### ISSUE THREAD

**Issue by arroyc** [actions/virtual-environments#1358]
Currently I see that only ‘buildpack-deps:stretch’ image is cached in the runners. Can we please also cache ‘buildpack-deps:buster’ image

**Comment by arroyc** [comment]
@alepauly  ... tagging you because you have some context on this request  from our previous meeting
@kichalla for tracking

**Comment by kichalla** [comment]
@alepauly we are fine with sending out a PR for this.

**Comment by maxim-lobanov** [comment]
@arroyc, could you please update issue description to use [feature request](https://github.com/actions/virtual-environments/blob/main/.github/ISSUE_TEMPLATE/tool-request.md) template?

**Comment by alepauly** [comment]
@arroyc Thanks for opening this issue. For reference so others can see the reasoning behind this request, can you add some details about why `buster` should be added? Thanks!

**Comment by maxim-lobanov** [comment]
Changes were merged and new image will be deployed next week

**Comment by maxim-lobanov** [comment]
Hello! Changes were deployed everywhere.
Please let me know if you have any concerns

**Comment by kichalla** [comment]
Great. Thanks @maxim-lobanov . I see that the Readme file is also updated with the buster image digest
