### ISSUE TITLE
Azure DevOps agent can't install tools to the hostedtoolcache folder

### ISSUE THREAD

**Issue by vladonemo** [actions/virtual-environments#1362]
**Describe the bug**
We use the repo to generate VM image which is then later used in VM Scale Set and registered with Azure DevOps as agent pool. The Install-Tools.ps1 script changes the ownership of the /opt/hostedtoolcache/* folders to SUDO_USER. But when later the Azure DevOps agent is installed and started on the VM, the user (AzDevOps) doesn't have access to this folder. For instance the NodeTool task fails to install another version of node.

**Area for Triage**: 
Scripting and command line

**Question, Bug, or Feature?**: 
Bug

**Virtual environments affected**
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [x] Ubuntu 18.04 LTS
- [ ] Ubuntu 20.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Expected behavior**
The chmod of the folders should be 777 (the /opt/hostedtoolcache is set to 777 in configure-environment.sh which is called before the Install-Tools.ps1)

**Actual behavior**
The folders permissions are 755

**Comment by Darleev** [comment]
Hello @vladonemo,
I have tested the behavior on our agent machines and everything works fine. I'm able to create folders and files in the folder.
After packer template build, a script sets permissions to the folder according to your desire:

**Comment by vladonemo** [comment]
hi @Darleev. Thanks for the answer. What is the script that you are referring to? Would it be possible to add it to the build template, so that if someone else uses the repo to provision their self-hosted agents can leverage from it?

**Comment by Darleev** [comment]
@vladonemo the script cannot be added to build template, because build user(packer) and default pipeline user are not the same, and the second one is created after the packer build process. 
Unfortunately, the script is currently in a private repo and I'm not able to share it, but I definitely can provide access permissions part:

```
                echo "Giving vsts user access to the '/home', '/usr/share', and '/opt' directories."
                sudo chmod -R 777 /home
                setfacl -Rdm "u:$user:rwX" /home
                setfacl -Rb /home/$user
                
                sudo chmod -R 777 /usr/share
                setfacl -Rdm "u:$user:rwX" /usr/share
                
                sudo chmod -R 777 /opt
                setfacl -Rdm "u:$user:rwX" /opt
```
where $user is default pipeline user in our case.
If additional information is required, please let us know, we will be glad to assist you further.

**Comment by Darleev** [comment]
@vladonemo I'm going to close the issue.

In case of any questions, feel free to contact us at any time.
