### ISSUE TITLE
Cannot access VM created from windows packer image

### ISSUE THREAD

**Issue by henti** [actions/virtual-environments#1364]
**Describe the bug**
I used the documentation here to create a Windows2016 VHD image which I've deployed in our Azure subscription, I've tried to use the image in our jenkins setup to test our builds before migrating job to Actions, however I could not get Jenkins to connect to the Image. 

I then created a VM manually using the image, but still could not connect to the VM. I've done similar setup with Linux images which works fine. 

According to https://github.com/actions/virtual-environments/blob/main/help/debuggingFailedBuilds.md during the initial build RDP is accessible, but I'm unsure if this is the case with the completed Image. 

Where can I find more information on what access is created within the Image to allow me to connect and debug/test any builds before migration to Actions ? 

I'm assuming RDP is supported in the final image, or should I use another method ? 

**Area for Triage**: 
Servers

**Question, Bug, or Feature?**: 
Question

**Virtual environments affected**
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Ubuntu 20.04 LTS
- [x] Windows Server 2016 R2
- [ ] Windows Server 2019

**Expected behavior**
Create VM in Azure using the VHD. Connect to VHD using RDP. 

**Actual behavior**
Create VM in Azure and cannot connect.

**Comment by vmapetr** [comment]
Hi @henti !
RDP is supported on the final image, however credentials for deployed VM is not the same credentials, that are used during image generation.
If you deployed VM using [CreateAzureVMFromPackerTemplate.ps1](https://github.com/actions/virtual-environments/blob/main/helpers/CreateAzureVMFromPackerTemplate.ps1) script, you should be able to connect, using the same `AdminUserName` and `AdminPassword` credentials that you used in script.
Could you, please confirm that network interface of your VM, allows incoming connections via RDP port (TCP 3389)?
In case if port is closed, you can use [serial console](https://docs.microsoft.com/en-us/azure/virtual-machines/troubleshooting/serial-console-windows) or [Bastion RDP](https://docs.microsoft.com/en-us/azure/bastion/bastion-connect-vm-rdp) to connect to VM.

**Comment by vmapetr** [comment]
I'm going to close this issue. Feel free to reopen, if the issue still occur.

**Comment by PetrPospisil** [comment]
Just for other people with the same issue...

You need to associate Network security group with the Network interface of the newly created Windows VM machine and allow RDP port in order to be able to connect using RDP.

![obrazek](https://user-images.githubusercontent.com/5891724/100497671-5d2ecd80-315d-11eb-9753-c87374d4fe76.png)
