### ISSUE TITLE
Installers freezing windows-latest as of Aug 5

### ISSUE THREAD

**Issue by jeroen** [actions/virtual-environments#1369]
Apologies for [cross-posting](https://github.community/t/windows-installers-freezing-on-gha-as-of-aug-5), but this seems like a pretty bad bug. All our GHA runs get stuck, waste a lot of time, and then die with a timeout after 6 hours. This is affecting thousands of runs already.

**Describe the bug**

I am the maintainer of [rtools40](https://cran.r-project.org/bin/windows/Rtools/), the Windows toolchain bundle for the R project. The rtools40 installer is a pretty standard innosetup installer. Over a million people use this.

As of recently, all unattended installations of rtools40 on GHA freeze indefinitely. The installer itself has not changed. Has something changed in the `windows-latest` image could cause the installer to present a user confirmation dialog where it did not before? Perhaps UAC related?

Some examples: https://github.com/r-devel/r-svn/actions

**Area for Triage**: 

**Question, Bug, or Feature?**: 
Bug

**Virtual environments affected**
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Ubuntu 20.04 LTS
- [ ] Windows Server 2016 R2
- [x] Windows Server 2019

**Expected behavior**
Installer completes as previously.

**Actual behavior**

Example runs: https://github.com/r-devel/r-svn/actions

**Comment by jeroen** [comment]
OK I think I may see what happened. If https://github.com/actions/virtual-environments/pull/1264 was deployed, rtools40 is now preinstalled, and perhaps that may cause a user prompt dialog to overwrite the existing installation.

**Comment by maxim-lobanov** [comment]
Hello @jeroen , yep, we have recently pre-installed R to images by customers' request. Changes are deploying right now.

**Comment by miketimofeev** [comment]
They have already deployed a few hours ago actually

**Comment by jeroen** [comment]
OK that is unfortunate, we weren't prepared for this. We are now deploying hotfixes everywhere to skip the installation of rtools40 if it is already pre-installed, such that the installer doesn't yield a dialog box. 

I guess this issue can be closed. Btw, versioning your vm's might not be a bad idea...

**Comment by miketimofeev** [comment]
@jeroen versioning is implemented, you can find the exact version here
![image](https://user-images.githubusercontent.com/48208649/89551136-41e92c80-d813-11ea-99e8-d9ee293f3a37.png)

**Comment by jeroen** [comment]
Is it possible to run a workflow on a specific version of the vm ?

**Comment by miketimofeev** [comment]
@jeroen unfortunately, not. We keep only one version due to maintenance effort.

**Comment by jeroen** [comment]
It might be useful to allow people to run on a fixed snapshot ov the vm, to prevent workflows from breaking due to changes in the vm. I don't think you would have to maintain snapshots, people would just use it to get a stable production environment.
