### ISSUE TITLE
Runner path on macOS changes

### ISSUE THREAD

**Issue by JosephDuffy** [actions/virtual-environments#137]
**Describe the bug**
The path the action being run in changes, which means that caching SwiftPM is not possible because it will fail with the following error:

`<unknown>:0: error: PCH was compiled with module cache path '/Users/runner/runners/2.161.0/work/PROJECT/PROJECT/.build/x86_64-apple-macosx/debug/ModuleCache/Z7RNZCZNAHFT', but the path is currently '/Users/runner/runners/2.162.0/work/PROJECT/PROJECT/.build/x86_64-apple-macosx/debug/ModuleCache/Z7RNZCZNAHFT'`

You can see [an example of this in one of my projects](https://github.com/JosephDuffy/Shepherd/pull/20/checks?check_run_id=340950782).

**Virtual environments affected**
- [X] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Expected behavior**
The path of the runner should not change.

**Actual behavior**
The path has (what I assume is) the version of the virtual environment in it, causing it to change.

**Comment by maxim-lobanov** [comment]
Hello @JosephDuffy , We don't set runner path on image-generation side. It is defined by runner, itself.
It is better to move this issue to https://github.com/actions/runner .

**Comment by TingluoHuang** [comment]
@maxim-lobanov the MMS provisioner is the one that downloads and sets up the runner directory.
