### ISSUE TITLE
Request to Install Latest Version Of PowerShell on VS2017 and VS2019 Agents

### ISSUE THREAD

**Issue by PraveenKalavai** [actions/virtual-environments#1371]
**Describe the bug**
I'm using Get-PfxCertificate cmdlet to establish TLS Certificate authentication to Hashicorp Vault using an API call, but getting the below error when I run the cmdlet.
**_Get-PfxCertificate : A parameter cannot be found that matches parameter name 'Password'._**

Upon checking $PSVersionTable on the agent, it shows that the agent only has PS 5.1

Name                           Value                                                                                   
----                           -----                                                                                   
**PSVersion                      5.1.17763.1007**                                                                          
PSEdition                      Desktop                                                                                 
PSCompatibleVersions {1.0, 2.0, 3.0, 4.0...}                                                                 
BuildVersion                  10.0.17763.1007                                                                         
CLRVersion                    4.0.30319.42000                                                                         
WSManStackVersion     3.0                                                                                     
PSRemotingProtocolVersion      2.3                                                                                     
SerializationVersion      1.1.0.1  

_**Can anyone confirm if the agents come with PowerShella version 6 or 7?**_

Per Microsoft documentation,
PowerShell 6 and 7 Supports argument 'Password'
`Get-PfxCertificate` [-FilePath] <String[]> [-Password <SecureString>] [-NoPromptForPassword] [<CommonParameters>]

PowerShell 5.1 doesnot support argument 'Password'. Instead it prompts for password and hence cannot be used in the release pipeline.
`Get-PfxCertificate` [-FilePath] <String[]> [<CommonParameters>]
**Area for Triage**: 

**Question, Bug, or Feature?**: 
"Question"

**Virtual environments affected**
- [x] Windows Server 2016 R2
- [x] Windows Server 2019

**Expected behavior**
Latest version of PowerShell should be installed on the Agents.

**Actual behavior**
Error in Agents : 
Get-PfxCertificate : A parameter cannot be found that matches parameter name 'Password'.
At D:\a\_temp\6f6f9cbd-e6e9-410d-9f4f-9b7984603deb.ps1:10 char:82
+... ilePath D:\a\_temp\certificate.pfx -Password $passwo ...
+CategoryInfo          : InvalidArgument: (:) [Get-PfxCertificate], ParameterBindingException
+FullyQualifiedErrorId : NamedParameterNotFound,Microsoft.PowerShell.Commands.GetPfxCertificateCommand

**Comment by miketimofeev** [comment]
Hi @PraveenKalavai!
Powershell 7 is pre-installed on both images
https://dev.azure.com/mseng/AzureDevOps/_build/results?buildId=12785135&view=logs&j=80d86624-2c9a-5cad-9434-144b838e69fb&t=18025f75-ada1-5e8c-ab96-f2897089918e
https://dev.azure.com/mseng/AzureDevOps/_build/results?buildId=12785135&view=logs&j=80d86624-2c9a-5cad-9434-144b838e69fb&t=18025f75-ada1-5e8c-ab96-f2897089918e

You can select it by specifying shell as `pwsh`
https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#using-a-specific-shell

**Comment by PraveenKalavai** [comment]
@miketimofeev 
Thanks for the response. 
Is this only applicable for yaml builds?
How do I specify `pwsh` argument for the PowerShell task? There seem to be no option for the `pwsh` argument, since it is optional.
![image](https://user-images.githubusercontent.com/36277675/89667773-b28f5800-d8aa-11ea-8119-fd4b25e572bd.png)

**Comment by maxim-lobanov** [comment]
@PraveenKalavai , it should be option under `Advanced` tab:
![image](https://user-images.githubusercontent.com/16715858/89667989-ca380200-d8e5-11ea-93db-8fb5a2d97de3.png)

**Comment by PraveenKalavai** [comment]
@maxim-lobanov  
Ahh! It was hiding in plain sight! I should've noticed it. Sorry about that! 

This can now be closed.
Thank you! 👍
