### ISSUE TITLE
Scripts under installers get the lock-frontend -open error

### ISSUE THREAD

**Issue by prashant6475** [actions/virtual-environments#1372]
**Describe the bug**
A clear and concise description of what the bug is, and why you consider it to be a bug.

**Area for Triage**: 

**Question, Bug, or Feature?**: 

**Virtual environments affected**

- [ ] Ubuntu 18.04 LTS

**Expected behavior**
Expected the basic.sh ,firefox.sh and several other scripts run seamlessly

**Actual behavior**
E:Could not get lock /var/lib/dpkg/lock-frontend - open (11: Resource temporarily unavailable)
E: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), is another process using it?

packer provisioning stops and exits out

**Comment by miketimofeev** [comment]
Hi @prashant6475!
We already have the same issue so I'm going to close this one. Feel free to post details about your error in the thread https://github.com/actions/virtual-environments/issues/1120
Thank you!
