### ISSUE TITLE
WebPlatformInstaller installation is broken on Windows images

### ISSUE THREAD

**Issue by maxim-lobanov** [actions/virtual-environments#1373]
**Describe the bug**
we install “Web Platform Installer” to our Windows images.
Recently, we have found that direct links for downloading version 5.0 are broken and affects our image-generation CI: https://docs.microsoft.com/en-us/iis/install/web-platform-installer/web-platform-installer-direct-downloads

**Possible solution**
Switch to the version 5.1 and download it using the following links:
X86 MSI: http://go.microsoft.com/fwlink/?LinkId=287165
X64: MSI: http://go.microsoft.com/fwlink/?LinkId=287166

**Question, Bug, or Feature?**
Bug

**Virtual environments affected**
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Ubuntu 20.04 LTS
- [x] Windows Server 2016 R2
- [x] Windows Server 2019

**Comment by dibir-magomedsaygitov** [comment]
Changes were merged in scope of [this ](https://github.com/actions/virtual-environments/pull/1379)PR and will be delivered to all VM's with the next week's rollout.

**Comment by dibir-magomedsaygitov** [comment]
Changes were successfully delivered to all VM's.
