### ISSUE TITLE
Permission issues - using snap - Ubuntu 18.04/20.04

### ISSUE THREAD

**Issue by kanika1894** [actions/virtual-environments#1378]
**Describe the bug**
Observed the issue while executing AzureClI task in pipeline. While executing a simple powershell script, it gives an error : "mkrdir: cannot create directory /run/user/1001 : Permission denied". 
This happens when the selected agent is ubuntu 18.04 or 20.04 and it works fine with ubuntu 16.04. This led to the inference that it's a agent specific issue. 
On observing more, figured out ubuntu 20.04 is using snap which has some permission related issues.
Could find some links to the related bug : https://bugs.launchpad.net/ubuntu/+source/snapd/+bug/1751634

So, it seems the permission issue is due to snap. So it requires some handling to prevent the error.

**Question, Bug, or Feature?**: 
Bug

**Virtual environments affected**
- [x] Ubuntu 18.04 LTS
- [x] Ubuntu 20.04 LTS

**Comment by miketimofeev** [comment]
@kanika1894 yeah, we've seen it before, it's likely related to the fact that another user is being used during image generation and snap packages are being installed by this user too. However, this error doesn't seem to affect anything. 
We'll take a look if we can fix it.

**Comment by kanika1894** [comment]
Not really sure what is the reason behind the error. 
The steps which I followed were :
1. A new pipeline
2. Azure cli task with inline script - _echo "hello world"_
3. Agent selected - 20.04

It gave me the issue :_"mkrdir: cannot create directory /run/user/1001 : Permission denied"_ and the pipeline execution fails.

Do you have some expected timeline on when this issue can be addressed?

**Comment by miketimofeev** [comment]
@kanika1894 could you please provide repro steps? I've tried this and it works both for Ub18&20
![image](https://user-images.githubusercontent.com/48208649/89639403-1ff4b600-d8b6-11ea-8833-0291ad06e4d4.png)

**Comment by kanika1894** [comment]
Please set the variable failOnStd Variable 
![image](https://user-images.githubusercontent.com/58769601/89641408-38bd9580-d8cf-11ea-8f96-2f5de8ef7a76.png)

**Comment by miketimofeev** [comment]
@kanika1894 in that case — yes, it fails on Ubuntu 20 because of the snap error. 
This error caused by Powershell 7 snap installation and we can't get rid of it at the moment because native Ubuntu 20 support will be added in Powershell 7.1 only. Ubuntu 20 VM image is still in preview state so it may be better to use Ubuntu18, where no such issues presented, or disable `Fail on Standard Error` checkbox on Ubuntu20 until stable Powershell 7.1 is released.

**Comment by al-cheb** [comment]
Hello, @kanika1894 
https://docs.microsoft.com/en-us/powershell/scripting/install/installing-powershell-core-on-linux?view=powershell-7#ubuntu-2004 - Ubuntu 20.04 is an LTS release. **PowerShell does not currently support this version.** Support for this version is being considered for the PowerShell 7.1 release.

Temporary workaround for Ubuntu 20.04 to add a task before running powershell scripts:
`sudo chmod -R 777 /run/user`
