### ISSUE TITLE
Update/Add GraalVM and graalpython

### ISSUE THREAD

**Issue by KOLANICH** [actions/virtual-environments#138]
**Tool information**
- Tool name: GraalVM
- Add or update? Add
- Desired version: Latest
- Approximate size: 37 MiB for GraalPython and 77.4 MB  for GraalVM debs (xz compression)
- If this is an add request:
  - Brief description of tool: A virtual machine replacing OpenJDK with a framework for jit-compilation of other languages.
  - URL for tool's homepage: https://github.com/oracle/graal and https://github.com/graalvm/graalpython

**Virtual environments affected**
- [ ] macOS 10.15
- [x] Ubuntu 16.04 LTS
- [x] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Can this tool be installed during the build?**
There are prebuilt releases. Building of GraalVM is a bit complicated.

**Are you willing to submit a PR?**
Maybe. I have a deb repo on GitLab platform building deb packages frem prebuilt releases. It may make sense to port the code to GH Actions and then use it to build the packages. Then the packages can be installed using apt.

**Comment by alepauly** [comment]
@KOLANICH since the packages are fairly small and binaries are provided we shouldn't bake this into the environment. Instead I suggest creating an Action to facilitate the installation.

**Comment by ErolPeel** [comment]
> @KOLANICH since the packages are fairly small and binaries are provided we shouldn't bake this into the environment. Instead I suggest creating an Action to facilitate the installation.

I may be mistaken, but to install GraalVM on Linux a 420 MB heavy file has to be downloaded: https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-20.3.0/graalvm-ce-java11-linux-aarch64-20.3.0.tar.gz

This is the installation instruction: https://www.graalvm.org/docs/getting-started-with-graalvm/linux/

To create Java native images, the GraalVM Native Image tool has to be installed as well: https://www.graalvm.org/reference-manual/native-image/#install-native-image

So it would be really helpful if the latest GraalVM would already be included in the Ubuntu virtual environment.

**Comment by KOLANICH** [comment]
They are small ... for Microsoft. ;) It's their resources, so their problems that their software wastes them.

**Comment by bernhardvollnhofer** [comment]
> They are small ... for Microsoft. ;) It's their resources, so their problems that their software wastes them.

In the opening post you have written about the size:

> Approximate size: 37 MiB for GraalPython and 77.4 MB for GraalVM debs (xz compression)

I think @alepauly was more interested in the file size to download. And as I have checked yesterday according to [the instructions](https://www.graalvm.org/docs/getting-started-with-graalvm/linux/), the file size is rather [425 MByte](https://github.com/graalvm/graalvm-ce-builds/releases).

**Comment by ErolPeel** [comment]
> They are small ... for Microsoft. ;) It's their resources, so their problems that their software wastes them.

In the opening post you have written about the size:

> Approximate size: 37 MiB for GraalPython and 77.4 MB for GraalVM debs (xz compression)

I think @alepauly was more interested in the file size to download. And as I have checked yesterday according to [the instructions](https://www.graalvm.org/docs/getting-started-with-graalvm/linux/), the file size is rather [425 MByte](https://github.com/graalvm/graalvm-ce-builds/releases).
