### ISSUE TITLE
Add "Microsoft Visual Studio Installer Projects" Extension

### ISSUE THREAD

**Issue by softworkz** [actions/virtual-environments#1382]
**Tool information**
- Tool name: Microsoft Visual Studio Installer Projects
- Tool license: https://marketplace.visualstudio.com/items/VisualStudioClient.MicrosoftVisualStudio2017InstallerProjects/license
- Add or update? Add
- Desired version: Latest
- Approximate size: 5 MB
- If this is an add request:
  - Brief description of tool: This official Microsoft extension provides support for Visual Studio Installer Projects in Visual Studio
  - URL for tool's homepage: https://marketplace.visualstudio.com/items?itemName=VisualStudioClient.MicrosoftVisualStudio2017InstallerProjects
  - Provide a basic test case to validate the tool's functionality: Any VS solution containing a .vdproj installer project

**Area for Triage**: Visual Studio

**Question, Bug, or Feature?**: Tool Request

**Virtual environments affected**
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Ubuntu 20.04 LTS
- [ ] Windows Server 2016 R2
- [x] Windows Server 2019

**Can this tool be installed during the build?**
AFAIK, no. Otherwise it would still be convenient to have this by default.

**Tool installation time in runtime**
It's just 5 MB, so < 1min

**Are you willing to submit a PR?**
You'll know better how to install a VS extension inside your image generation ecosystem.

**Comment by andy-mishechkin** [comment]
Hello, @softworkz 
I've added MS Visual Studio Installer projects extension to Windows image deployment.
It will be there about on the next week.
If you'll not find it - feel free to ping me
Thank you

**Comment by softworkz** [comment]
Hi @andy-mishechkin,

this is really great news! 

To be honest, I didn't have high hopes for this, as it is a long-standing and frequently requested topic. Here's just a quick compilation of user questions and issues which will be all resolved by this change:

- https://developercommunity.visualstudio.com/idea/382210/add-support-to-build-installer-project-vdproj-in-a.html
- https://developercommunity.visualstudio.com/content/problem/763438/unable-to-build-msi-in-pipelines-via-vdproj.html
- https://developercommunity.visualstudio.com/idea/628434/azure-devops-cannot-build-msi-via-vdproj-project.html
- https://developercommunity.visualstudio.com/content/problem/426725/where-is-the-msi-package-build-functionality-in-az.html
- https://stackoverflow.com/questions/53545164/how-to-properly-build-msi-setup-projects-using-azure-devops-pipelines
- https://stackoverflow.com/questions/55578611/vdproj-is-not-supported-by-msbuild-and-cannot-be-built-in-azure-ci-cd-pipelin
- https://stackoverflow.com/questions/62498975/how-to-generate-setup-msi-or-exe-file-with-the-ci-build-in-azure-devops
- https://stackoverflow.com/questions/60517557/azure-devops-pipeline-use-microsoft-visual-studio-installer-projects
https://stackoverflow.com/questions/54908015/how-to-build-visual-studio-installer-project-in-azure-devops-pipeline-hosted-age

**Thank you very much for making this happen!**

**Comment by miketimofeev** [comment]
@softworkz I'm afraid the new image won't be in the next week, likely the week after.

**Comment by softworkz** [comment]
> @softworkz I'm afraid the new image won't be in the next week, likely the week after.

After waiting years for this, those few days won't really matter 😆 
Thanks for letting me know!

**Comment by miketimofeev** [comment]
@softworkz good news! The image with MS Visual Studio Installer projects extension is already deployed! Could you check it, please?

**Comment by andy-mishechkin** [comment]
I've checked the availability of this VSIX extension on the `windows-latest` runner - "Microsoft Visual Studio Installer Projects" extension is present

**Comment by softworkz** [comment]
@andy-mishechkin @miketimofeev 

Great job! Thanks a lot for making this possible.

I was able to successfully build a Visual Studio Solution including a **Visual Studio Installer Project** (`vdproj`) with **an Azure Build Pipeline** on an **Azure hosted build agent**.


## Instructions

### 1. Don't use the "Visual Studio Build" task

The name of this task is **lying**. It doesn't build with Visual Studio but uses MSBuild instead.

Unfortunately none of the built-in Azure tasks is able to run a build via devenv.exe.

### 2. How to Build Instead

- Command Line
  Of course you can always use a command line task and assemble the required parameters manually, and write some code to detect the installation path of VS (latest or specific version)
- I tried the "DevEnv Build" extension from the marketplace and it worked right away
  https://marketplace.visualstudio.com/items?itemName=mmajcica.devenv-build
  - I entered the solution for `Solution / Project`
  - left `Project` empty
  - `Configuration`: Release
  - `Platform`: Any CPU
  - `Deploy`: Unchecked
  - `Clean`: Checked

### 3. Copy Files Task

Some of the templates include a copy files task with a `Contents` parameter similar to `**\bin\$(BuildConfiguration)\**`

Make sure to change this as it won't copy the generated MSI setup (because there is no 'bin' subfolder).


That's all. I'm sure this will make a lot of people very happy..

**Comment by AngellusMortis** [comment]
I am still not able to get this working on my project. I am getting the error:

```
ERROR: An error occurred while validating.  HRESULT = '8000000A'
```

Which searching around lead me to this as the best explation of why:

https://github.com/it3xl/MSBuild-DevEnv-Build-Server-Workarounds/blob/master/workaround/DevEnv-Vdproj-VS2017_Enterprise-HRESULT-8000000A-EnableOutOfProcBuild.bat

**Comment by softworkz** [comment]
Just add a "Command Line Script" task before the devenv task:

- Script: `DisableOutOfProcBuild.exe`
- Advanced > Working Directory:` C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\CommonExtensions\Microsoft\VSI\DisableOutOfProcBuild`

**Comment by AngellusMortis** [comment]
Oh thanks. It looks like the `working-directory` param was what I was missing. I was trying to `cd` out of the workspace and it would not let me. It seems you are jailed to the working directory. At least for Github actions.

**Comment by marichaux** [comment]
I am using a command line but getting this error for all .modelproj:

Diseño\AccesoDatos\AccesoDatos\AccesoDatos.modelproj: The application which this project type is based on was not found. Please try this link for further information: https://go.microsoft.com/fwlink/?LinkId=660952&projecttype=F088123C-0E9E-452A-89E6-6BA2F21D5CAC
--

**Comment by DavidStrickland0** [comment]
Would be nice if this was done on Windows-2022 as well

**Comment by miketimofeev** [comment]
Hey @DavidStrickland0!
There is an issue for that already https://github.com/actions/virtual-environments/issues/4580
Please keep an eye on it as we are going to add the extension soon.

**Comment by czechdude** [comment]
Hi, great work, could you publish an example **azure-pipelines.yml** to use for building vdproj on azure pipelines? thanks!

**Comment by softworkz** [comment]
.vdproj projects are not MSBuild projects, which means need to do an IDE build calling devenv.exe. There's an extension on the marketplace for this.

**Comment by czechdude** [comment]
i thought this issue is about adding such extension to windows-2019 image for MS hosted agents?

**Comment by softworkz** [comment]
Correct. Sorry for the confusion. 

What I meant above is an Azure DevOps extension on the Azure DevOps MarketPlace.
I looked it up now. This is the one I'm using: https://marketplace.visualstudio.com/items?itemName=mmajcica.devenv-build

**Comment by softworkz** [comment]
You might also need to run this CMD script before:

```yaml
steps:
- script: |
   echo Executing DisableOutOfProcBuild
   
   DisableOutOfProcBuild.exe
  workingDirectory: 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\CommonExtensions\Microsoft\VSI\DisableOutOfProcBuild'
  displayName: 'Command Line Script'

```

Background: https://github.com/it3xl/MSBuild-DevEnv-Build-Server-Workarounds/issues/1

**Comment by gbakeman** [comment]
Apologies if this is off topic, but I'm getting started with GitHub Actions/CI/Workflows and am confused about how Azure Pipelines translate over to the former, if at all. Can someone provide a short example of how one utilizes this .vdproj/devenv build feature from the perspective of a GitHub workflow .yaml?
