### ISSUE TITLE
Update/Add Doxygen

### ISSUE THREAD

**Issue by lianqiw** [actions/virtual-environments#1383]
**Tool information**
- Tool name: Doxygen
- Tool license: GPL
- Add or update? Add
- Desired version: latest is ok
- Approximate size: 30MB
- If this is an add request:
  - Brief description of tool: For generating documentation to be placed in gh-pages
  - URL for tool's homepage: https://www.doxygen.nl/index.html
  - Provide a basic test case to validate the tool's functionality: 

**Area for Triage**:
C/C++

**Question, Bug, or Feature?**:

**Virtual environments affected**
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [X] Ubuntu 18.04 LTS
- [X] Ubuntu 20.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Can this tool be installed during the build?**
System installer is better at installing it and dependencies.

**Tool installation time in runtime**

**Are you willing to submit a PR?**

**Comment by maxim-lobanov** [comment]
Hello @lianqiw , thank you for feature request.
This tool can be installed in runtime using the following code (installation takes 15-20 seconds):
```
sudo apt-get install doxygen
```
Considering very quick installation in runtime, we wouldn't like to pre-install this tool to images right now. We will re-consider this decision in future if we see more requests.

**Comment by mariomastrodicasa** [comment]
What about to have the doxygen tool pre-installed in windows environment too?

**Comment by maxim-lobanov** [comment]
Hello @mariomastrodicasa , the same as for Ubuntu above, we wouldn't like to bake this tool into the images since it can be installed in runtime pretty quick.
