### ISSUE TITLE
Update/Add Visual Studio and .NET Core SDK

### ISSUE THREAD

**Issue by timheuer** [actions/virtual-environments#139]
**Tool information**
- Tool name: Visual Studio and .NET Core SDK
- Add or update? Update
- Desired version: Visual Studio 16.4.1 + .NET Core SDK 3.1.100
- Approximate size: 

**Virtual environments affected**
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [x] Windows Server 2019

**Can this tool be installed during the build?**
Visual Studio cannot.  The SDK can.

**Are you willing to submit a PR?**
If I knew how to update the virtual environment image, sure I'd be willing to do that...but I don't.  If there are doc pointers I'll take a look.

**Comment by kaylangan** [comment]
We pull the latest version of VS that's available when we create the virtual environment. We're in the process of rolling out an update with VS16.4.0. VS16.4.1 will be included in an update following that.

**Comment by timheuer** [comment]
@kaylangan This is great!  Is there a public area for roadmap/rollout details?

**Comment by jozefizso** [comment]
> **Can this tool be installed during the build?**
> Visual Studio cannot. The SDK can.

Although .NET Core SDK can be installed individually, using msbuild to compile a .NET Core 3.1 project will fail, as older Visual Studio does not recognize or support some of the features in 3.1 projects. To correctly build a 3.1 project, it requires the VS 2019 16.4 to be installed.

**Comment by timheuer** [comment]
@jozefizso for .NET Core projects, are you doing custom MSBuild items because you should be able to use `dotnet build` CLI command from the SDK to build Core projects.

**Comment by jozefizso** [comment]
I use the **VSBuild@1** task to compile solution.

PS: projects target .NET 4.0, 4.7 and Core 3.1 simultaneously

**Comment by timheuer** [comment]
@jozefizso got it, so you don't really need it for core, but your solution has other bits that require it.  Makes sense.  If your .NET Framework projects are SDK-style projects than they can be built using `dotnet` as well but I suspect they are not and are classic csproj.

**Comment by MichaelSimons** [comment]
FYI, I created https://github.com/actions/virtual-environments/pull/164 which updates Ubuntu 16.04 and 18.04 to include .NET Core 3.1.

**Comment by stevencpp** [comment]
VisualStudio/16.4.0+29519.181 and .NET Core SDK 3.1.100 are available now :) .
