### ISSUE TITLE
NSIS package cannot be downloaded due to certificate error.

### ISSUE THREAD

**Issue by RFB007** [actions/virtual-environments#1396]
**Tool information**
- Tool name: nsis-3.05-setup.exe
- Tool license: 
- Add or update? update
- Desired version: nsis-3.05-setup.exe
- Approximate size: 
- If this is an add request:
  - Brief description of tool: Windows installer
  - URL for tool's homepage: from 'https://astuteinternet.dl.sourceforge.net/project/nsis/NSIS%203/3.05/nsis-3.05-setup.exe'
  - Provide a basic test case to validate the tool's functionality: 

**Area for Triage**:
# Area: Packages
- valueFor: '**Area for Triage**'
  contains: 'Packages'
  addLabels: ['Area: Packages']

**Question, Bug, or Feature?**:
bug

**Virtual environments affected**
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Ubuntu 20.04 LTS
- [ ] Windows Server 2016 R2
- [x ] Windows Server 2019

**Can this tool be installed during the build?**
NO - The download URL of this package nsis has an expired certificate so building the VM fails trying to install the package.

======
vhd: Attempt to get headers for https://astuteinternet.dl.sourceforge.net/project/nsis/NSIS%203/3.05/nsis-3.05-setup.exe failed.
    vhd:   The remote file either doesn't exist, is unauthorized, or is forbidden for url 'https://astuteinternet.dl.sourceforge.net/project/nsis/NSIS%203/3.05/nsis-3.05-setup.exe'. Exception calling "GetResponse" with "0" argument(s): "The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel."
    vhd: Downloading nsis.install
    vhd:   from 'https://astuteinternet.dl.sourceforge.net/project/nsis/NSIS%203/3.05/nsis-3.05-setup.exe'
    vhd: ERROR: The remote file either doesn't exist, is unauthorized, or is forbidden for url 'https://astuteinternet.dl.sourceforge.net/project/nsis/NSIS%203/3.05/nsis-3.05-setup.exe'. Exception calling "GetResponse" with "0" argument(s): "The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel."
    vhd: This package is likely not broken for licensed users - see https://chocolatey.org/docs/features-private-cdn.
    vhd: The install of nsis.install was NOT successful.
    vhd: Error while running 'C:\ProgramData\chocolatey\lib\nsis.install\tools\chocolateyInstall.ps1'.

**Tool installation time in runtime**
NA

**Are you willing to submit a PR?**
NO

**Comment by al-cheb** [comment]
Hello, @RFB007 
We have prepared temporary workaround https://github.com/actions/virtual-environments/pull/1392 PR  to fix this issue.

**Comment by al-cheb** [comment]
@RFB007, Fix has been merged to the main branch. Please pull the latest change.
