### ISSUE TITLE
Unable to create directory on OS X

### ISSUE THREAD

**Issue by jaxxstorm** [actions/virtual-environments#1397]
**Describe the bug**
I'm trying to run a `mkdirp` on an OS X image:

```
const destination = `/home/runner/.${project}`;
await mkdirp(destination);
```

and that doesn't seem to be supported:

```
Run jaxxstorm/action-install-gh-release@release/v1-alpha
##[error]ENOTSUP: operation not supported on socket, mkdir '/home/runner'
```

How should this be done correctly?

**Area for Triage**: 
Apple

**Question, Bug, or Feature?**: 
Question

**Virtual environments affected**
- [X] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Ubuntu 20.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Expected behavior**
The directory is created

**Comment by maxim-lobanov** [comment]
Hello @jaxxstorm ,
Actually, `/home` and `/home/runner` don't exist on OSX and it is expected. These folders exist only on Ubuntu environment.
On macOS, profile lives under `/Users/runner`.

Looks like you use JS script, so I suggest to use `$HOME` env variable. It points to `/home/runner` for Ubuntu and to `/Users/runner` for macOS.
```
const homePath = process.env.HOME
const destination = `${homePath}/.${project}`;
await mkdirp(destination);
```
Something like that should work for both OSs

**Comment by jaxxstorm** [comment]
thanks, that helps
