### ISSUE TITLE
Update Golang to 1.15

### ISSUE THREAD

**Issue by LKaemmerling** [actions/virtual-environments#1398]
**Tool information**
- Tool name: golang
- Tool license: 
- Add or update? update
- Desired version: 1.15
- Approximate size: 
- If this is an add request:
  - Brief description of tool: 
  - URL for tool's homepage: https://blog.golang.org/go1.15
  - Provide a basic test case to validate the tool's functionality: 

**Area for Triage**:

**Question, Bug, or Feature?**:
Feature

**Virtual environments affected**
- [X] macOS 10.15
- [X] Ubuntu 16.04 LTS
- [X] Ubuntu 18.04 LTS
- [X] Ubuntu 20.04 LTS
- [X] Windows Server 2016 R2
- [X] Windows Server 2019

**Can this tool be installed during the build?**

**Tool installation time in runtime**

**Are you willing to submit a PR?**

Yes

**Comment by maxim-lobanov** [comment]
@LKaemmerling , thank you for providing PR for Ubuntu, Windows. I have left minor question about default version.
Also we will take care about updating macOS (it is not open-sourced yet)

**Comment by dmitry-shibanov** [comment]
Hello, thank you for your response, pull requests were merged and changes will be added in next images rollout.

**Comment by dmitry-shibanov** [comment]
Hello, changes were added to images. If you have any concerns feel free to reopen the issue.

**Comment by kkl-acies** [comment]
So according to [the doc](https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-README.md) both Go 1.14.9 and Go 1.15.2 is installed in the Ubuntu 20.04 image. How do I use Go 1.15.2? Do I need to call a specific command?

**Comment by maxim-lobanov** [comment]
@kkl-acies , you should use https://github.com/actions/setup-go task to switch between pre-installed Go versions
