### ISSUE TITLE
Add SFDX (Salesforce CLI)

### ISSUE THREAD

**Issue by RuneSor** [actions/virtual-environments#14]
**Tool information**

- Tool name: SFDX

- Add or update? Add

- Desired version: Latest

- Approximate size: 40MB

- If this is an add request:
  - Brief description of tool: 
The CLI provides all the commands you need for setting up CI-CD towards the Saleforce env.

  - URL for tool's homepage: 
https://developer.salesforce.com/docs/atlas.en-us.sfdx_setup.meta/sfdx_setup/sfdx_setup_install_cli.htm#sfdx_setup_install_cli

**Virtual environments affected**
- [ ] macOS 10.14
- [x] Ubuntu 16.04 LTS
- [x] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Can this tool be installed during the build?**
  Yes, here's how:

Method 1:
  - (this step is just for neatness in this add request) 
 $ export CLIURL=https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz  

 - Create sfdx directory
 $ mkdir sfdx

 - Install Salesforce CLI
 $ wget -qO- $CLIURL | tar xJ -C sfdx --strip-components 1
 $ ./sfdx/install
 $ export PATH=./sfdx/$(pwd):$PATH

 - verify install and stdout version information
 $ sfdx --version
 or
 $ sfdx force

Method 2: 
 - (npm required)
 $ npm install sfdx-cli --global

**Are you willing to submit a PR?**
Sure

:-)

**Comment by maxim-lobanov** [comment]
Thank you for providing installation steps:
```
export CLIURL=https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz
mkdir sfdx
wget -qO- $CLIURL | tar xJ -C sfdx --strip-components 1
./sfdx/install
export PATH=./sfdx/$(pwd):$PATH
sfdx --version
```
Installation takes about 13 seconds

**Comment by RuneSor** [comment]
No worries, least i could do. Thank you for picking this up!

Let me know if there's anything i can do to help..

Rune

**Comment by alepauly** [comment]
HI @RuneSor, thanks for your suggestion and providing some of the code. At this time we're not going to be adding this to the image considering that's pretty quick to install on demand. To simplify workflows that depend on the SFDX I suggest creating a `setup` Action.
