### ISSUE TITLE
MacOS image reports invalid serial number 

### ISSUE THREAD

**Issue by paulz** [actions/virtual-environments#1400]
**Describe the bug**
getting Mac serial number returns a string containing `+`

**Area for Triage**: 
Apple

**Question, Bug, or Feature?**: 
Bug

**Virtual environments affected**
- [X] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Ubuntu 20.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Expected behavior**
Expecting 12 character alphanumeric uppercase string, see https://igotoffer.com/apple/apple-serial-number-why-is-it-important

**Actual behavior**
https://github.com/sparta-science/connect/runs/974700398?check_suite_focus=true#step:11:317
shows returned serial number: `VM5vodACsc+k` which is invalid because contains `+` and not uppercased.

1. `ioreg -l | grep IOPlatformSerialNumber`
2. should output a string like: `C03XY0ZLHX8F`

Proposal:
Use random 12 character alphanumeric uppercase string that starts with `GH` or `ZZ` not to clash with real Macs.

**Comment by al-cheb** [comment]
Hello, @paulz 
For macOS virtualization we are using VMware ESXi hypervisor. ESXi host generates a "short" unique `serialNumber ` for each macOS vm in the format = `VM([A-Za-z0-9+/]){10}`. We can't hardcoded a single `serialNumber` for all macOS VMs due to unpredictable results.  I don't find any official sources from Apple why serialNumber can't contain characters in lowercase and `+/`.

https://discussions.apple.com/thread/387197 - Serial number case??

![image](https://user-images.githubusercontent.com/47745270/90009892-92dfa180-dca7-11ea-99ee-766f9f068b9d.png)

**Comment by paulz** [comment]
Thank you @al-cheb, it's helpful to know what characters to expect from serial number as we encode them.

Ideally it would be nice to have `VM([A-Z0-9]){12}` pattern as real Macs use since 2010.

We only use GitHub virtual environment for tests, so no serious impact on our production code as we use real hardware not VM. 

For our tests it's hard to predict what macOS tools will fail when serial number is invalid. For example, iMessage and iCloud services sometimes fail on Mac when macOS serial number is invalid.

Could `SMBIOS.use12CharSerialNumber = "TRUE"` be set on VM?

as described in this post: https://communities.vmware.com/message/2303246#2303246

**Comment by al-cheb** [comment]
@paulz,
 SMBIOS.use12CharSerialNumber = "TRUE" - is already enabled, https://www.insanelymac.com/forum/topic/292170-how-to-spoof-real-mac-in-vmware/, before apply the setting -  `VMWVk21tM5F4+1Uty1UOSqjAQ` after you will get something like `VMWVk21tM5F4`=12 chars.

Currently we are discussing  to setup manually property `serialNumber` or take the `serialNumber` from the hardware host.

**Comment by maxim-lobanov** [comment]
Hello @paulz , Sorry, we can't change it for now due to technical limitations. The single option that we can use here is hardcoding the single serial number for all VMs but as @al-cheb mentioned, it could cause unpredictable impact so we would like to avoid it.
