### ISSUE TITLE
Azure Pipelines: Update Visual Studio 2019 to version 16.7

### ISSUE THREAD

**Issue by kmahone** [actions/virtual-environments#1407]
**Tool information**
- Tool name: Visual Studio 2019
- Tool license: Commercial
- Add or update? Update
- Desired version: 16.7

**Virtual environments affected**
- Windows Server 2019

**Can this tool be installed during the build?**
No

**Are you willing to submit a PR?**
Potentially, if someone can point me in the right direction.

Visual Studio 2019 16.7 was released this month. We require 16.7 to build our product. Please update Azure Pipelines Microsoft Hosted Agents image "Windows Server 2019 with Visual Studio 2019 (windows-2019)" from Visual Studio 2019 16.6 to Visual Studio 2019 16.7.

**Comment by maxim-lobanov** [comment]
Hello @kmahone !
We install latest VS on every image-generation. We have already started deployment of new image with VS 16.7, it should be deployed everywhere in 3-4 days: https://github.com/actions/virtual-environments/pull/1402

**Comment by kmahone** [comment]
Perfect! Thanks for the quick response.

**Comment by dotnetprofessional** [comment]
I've just run into this issue today which is blocking my PR. I understand I can fix it with a global.json file, however I can't seem to work out the correct version numbers. If I look on my local machine I see 3.1.6 (see below) however if I specify that in the globla.json file my project doesn't build. So what's a valid version I can use that works with < 16.7 of MSBuild? Alternatively what's the status of the rollout as I understand it started 5 days ago, how long does it take to deploy fully? Is there a status page we can look at?

```
Microsoft.AspNetCore.All 2.1.20 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
Microsoft.AspNetCore.App 2.1.20 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 3.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.NETCore.App 2.1.20 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 3.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.WindowsDesktop.App 3.1.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

**Comment by mattleibow** [comment]
@dotnetprofessional I just tested `3.1.302` in the `UseDotNet` task and it seems to work for me.

**Comment by dotnetprofessional** [comment]
@mattleibow Thanks that has solved my issue! :)

**Comment by maxim-lobanov** [comment]
Hello everyone, small update: we had to stop deployment because of some regression with new VS version.
We are working to investigate the issue and will update this issue as soon as we have updates

**Comment by mattleibow** [comment]
Thanks for the update. So far, using the 3.1.302 version of .NET Core as part of the pipeline has been good and no other issues yet.

**Comment by icnocop** [comment]
I'm thinking not having the latest Visual Studio 2019 installed causes my build to fail with the following errors:
```
CheckForUnsupportedScenarios:
  The specified XPath query did not capture any nodes.
##[error]C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VisualStudio\v16.0\AppxPackage\Microsoft.AppXPackage.Targets(3035,5): error APPX0702: Payload file 'C:\Users\runneradmin\.nuget\packages\microsoft.winui\3.0.0-preview2.200713.0\runtimes\win10-x86\native\Microsoft.UI.Xaml\DensityStyles\Compact.xaml' does not exist. [D:\a\myApp\myApp\src\myApp (Package)\myApp (Package).wapproj]
##[error]C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VisualStudio\v16.0\AppxPackage\Microsoft.AppXPackage.Targets(3035,5): error APPX0702: Payload file 'C:\Users\runneradmin\.nuget\packages\microsoft.winui\3.0.0-preview2.200713.0\runtimes\win10-x86\native\Microsoft.UI.Xaml\DensityStyles\CompactDatePickerTimePickerFlyout.xaml' does not exist. [D:\a\myApp\myApp\src\myApp (Package)\myApp (Package).wapproj]
##[error]C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VisualStudio\v16.0\AppxPackage\Microsoft.AppXPackage.Targets(3035,5): error APPX0702: Payload file 'C:\Users\runneradmin\.nuget\packages\microsoft.winui\3.0.0-preview2.200713.0\runtimes\win10-x86\native\Microsoft.UI.Xaml\Themes\compact_themeresources.xaml' does not exist. [D:\a\myApp\myApp\src\myApp (Package)\myApp (Package).wapproj]
##[error]C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VisualStudio\v16.0\AppxPackage\Microsoft.AppXPackage.Targets(3035,5): error APPX0702: Payload file 'C:\Users\runneradmin\.nuget\packages\microsoft.winui\3.0.0-preview2.200713.0\runtimes\win10-x86\native\Microsoft.UI.Xaml\Themes\generic.xaml' does not exist. [D:\a\myApp\myApp\src\myApp (Package)\myApp (Package).wapproj]
##[error]C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VisualStudio\v16.0\AppxPackage\Microsoft.AppXPackage.Targets(3035,5): error APPX0702: Payload file 'C:\Users\runneradmin\.nuget\packages\microsoft.winui\3.0.0-preview2.200713.0\runtimes\win10-x86\native\Microsoft.UI.Xaml\Themes\themeresources.xaml' does not exist. [D:\a\myApp\myApp\src\myApp (Package)\myApp (Package).wapproj]
```

**Comment by hiraldesai** [comment]
Thank you for your response @maxim-lobanov. Agent/Image details for both failed and successful build was this (windows-2019):
Current agent version: '2.173.0'
Current image version: '20200802.1'

Looking closely at the logs, build server image was not the issue (and it wasn't the MSBuild issue that this thread is referring to either) . Sorry I just assumed that it was the same MSBuild error resurfacing again without looking more into details.

This was the actual error I was getting briefly on Friday 8/21/2020 with "Use .Net Core 3.1.302" task. It resolved itself within couple of hours, so please ignore.

##[error]Failed while installing version: 3.1.302 at path: C:/hostedtoolcache/windows/dotnet with error: Could not download installation package from this URL: https://download.visualstudio.microsoft.com/download/pr/dafb4b49-9990-49aa-b8fe-9002c1a3578a/42acda06cb3d22d886b91aac37fda667/dotnet-sdk-3.1.302-win-x64.zip Error: Error: Unexpected HTTP response: 504

**Comment by miketimofeev** [comment]
Hello, everyone!
VM image with Visual Studio 16.7.30413.136 has been deployed, readme updated
https://github.com/actions/virtual-environments/blob/main/images/win/Windows2019-Readme.md
