### ISSUE TITLE
MacOS + Python 3.7+: Python SSL Causing Failures

### ISSUE THREAD

**Issue by mrmundt** [actions/virtual-environments#1412]
**Describe the bug**
For MacOS + Python 3.7/3.8 as of this week, any attempt to use `pip` results in a message:
```
WARNING: pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/pip/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/pip/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/pip/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/pip/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/pip/
Could not fetch URL https://pypi.org/simple/pip/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/pip/ (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.")) - skipping
```
The expectation is that Pythons on MacOS will all be built with the SSL module included. (Note: Pip works fine for anything prior to Python 3.7)

**Area for Triage**: 

**Question, Bug, or Feature?**: 
"Bug"

**Virtual environments affected**
- [X] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Ubuntu 20.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Expected behavior**
We expect that when `pip install` is called, it will not fail unless the particular package in pip is missing. An example success:
```
Collecting pip
  Downloading pip-20.2.2-py2.py3-none-any.whl (1.5 MB)
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 20.2
    Uninstalling pip-20.2:
      Successfully uninstalled pip-20.2
Successfully installed pip-20.2.2
```

**Actual behavior**
Workflow results can be found here: https://github.com/Pyomo/pyomo/pull/1592/checks?check_run_id=981337756 

1. Initialize workflow with `macos-latest` and `[python-3.7, python-3.8]`
2. Run `setup-python` action
3. Run `python -m pip install --cache-dir cache/pip --upgrade pip`

**Comment by maxim-lobanov** [comment]
Hello @mrmundt , I don't think that this issue is related to image.
Please see these 2 builds:
- successful: https://github.com/Pyomo/pyomo/runs/972013667?check_suite_focus=true
- failed: https://github.com/Pyomo/pyomo/pull/1592/checks?check_run_id=981337785

Both builds are run on the same image version: 20200802.1 (you can check it in `Initialize job` step). It means that the VMs for both builds are identical. So build passes and fails on the same machine.
Can this issue be related to your code or dependencies?

**Comment by mrmundt** [comment]
@maxim-lobanov By this point in the workflow, the only actions are "checking out the repository", "setting up caches", and "setting up python". We haven't changed the dependencies anytime recently - and everything passed on `master` when our last PR was merged >2 days ago (https://github.com/Pyomo/pyomo/actions/runs/204265463). It randomly started failing, and failing everywhere, sometime between Tuesday and Wednesday.

I have tried triggering one of the failures from mid-yesterday to see if there are any changes - the OSX jobs, of course, are the ones that have yet to initialize: https://github.com/Pyomo/pyomo/actions/runs/206201350

**Comment by maxim-lobanov** [comment]
Actually, if you disable all steps before `Set up Python`, `Install Python Packages (pip)` step will start to pass. I have validated it on my fork: https://github.com/maxim-lobanov/pyomo/runs/981738174?check_suite_focus=true
I suggest to investigate how those steps could affect next jobs

**Comment by mrmundt** [comment]
I will continue to investigate. It works "as-is" on my own fork when I run the entire suite, but just won't work on Pyomo-proper.
