### ISSUE TITLE
No version of NDK matched the requested

### ISSUE THREAD

**Issue by prsolucoes** [actions/virtual-environments#1413]
**Describe the bug**
Im trying build an android library project but im receiving this error:

```
* What went wrong:
Execution failed for task ':stripDebugDebugSymbols'.
> No version of NDK matched the requested version 21.0.6113669. Versions available locally: 21.3.6528147, 21.3.6528147
```

I tried install that NDK version but without success:
```
- name: Install NDK
  run: echo "y" | sudo /usr/local/lib/android/sdk/tools/bin/sdkmanager --install "ndk;21.3.6528147" --sdk_root=${ANDROID_SDK_ROOT}
```

Link:
https://github.com/ezored/ezored/runs/982775724#step:14:45

**Area for Triage**: 

**Question, Bug, or Feature?**: 
Bug

**Virtual environments affected**
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [x] Ubuntu 20.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

Image name: ubuntu-latest

**Expected behavior**
Compile the android project

**Actual behavior**
https://github.com/ezored/ezored/runs/982775724#step:14:45

**Comment by maxim-lobanov** [comment]
Hello, Looks like you install incorrect NDK version.
> sdkmanager --install "ndk;**21.3.6528147**"

But your build requires
> requested version **21.0.6113669**

I have checked in my fork and fixing ndk version works: https://github.com/maxim-lobanov/ezored/runs/983511643?check_suite_focus=true

**Comment by maxim-lobanov** [comment]
Closing work item, feel free to reopen if it is still issue for you

**Comment by nitzanw** [comment]
@maxim-lobanov I have exactly the same issue as him

**Comment by maxim-lobanov** [comment]
@nitzanw , The initial issue was related to typo in version string. See my answer above

**Comment by nitzanw** [comment]
@maxim-lobanov Tnx for the reply but the link is broken
