### ISSUE TITLE
Update/Add [kustomize]

### ISSUE THREAD

**Issue by dhananjaya-senanayake** [actions/virtual-environments#1414]
**Tool information**
- Tool name: kustomize
- Tool license:  Apache-2.0 License
- Add or update? Add
- Desired version: v3.8.1
- Approximate size: 12.5 MB
- If this is an add request:
  - Brief description of tool: Kustomize provides a solution for customizing Kubernetes resource configuration free from templates and DSLs.
  - URL for tool's homepage: https://kubernetes-sigs.github.io/kustomize/
  - Provide a basic test case to validate the tool's functionality: https://kubernetes.io/blog/2018/05/29/introducing-kustomize-template-free-configuration-customization-for-kubernetes/

**Area for Triage**:
Containers, Go

**Question, Bug, or Feature?**:
Feature

**Virtual environments affected**
- [ ] macOS 10.15
- [x] Ubuntu 16.04 LTS
- [x] Ubuntu 18.04 LTS
- [x] Ubuntu 20.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Can this tool be installed during the build?**
https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh

**Tool installation time in runtime**
https://kubernetes-sigs.github.io/kustomize/installation/

**Are you willing to submit a PR?**
Yes

**Comment by miketimofeev** [comment]
@dhananjaya-senanayake Kustomize is available across all Ubuntu images. Thanks for your contribution!
