### ISSUE TITLE
Windows 2019 build image - Unable to install NSIS

### ISSUE THREAD

**Issue by IanMoroney** [actions/virtual-environments#1416]
**Describe the bug**
A clear and concise description of what the bug is, and why you consider it to be a bug.

Windows 2019 build fails due to being unable to download NSIS.

**Area for Triage**: 

Packages

**Question, Bug, or Feature?**: 

Bug

**Virtual environments affected**
- [ X ] Windows Server 2019

    vhd: Provisioning with powershell script: C:\agent\_work\1\s\images\win/scripts/Installers/Install-NSIS.ps1
    vhd: Running [#1]: choco install nsis -y
    vhd: Chocolatey v0.10.15
    vhd: Installing the following packages:
    vhd: nsis
    vhd: By installing you accept licenses for the packages.
    vhd: Progress: Downloading nsis.install 3.5.0.20200106... 100%
    vhd: Progress: Downloading nsis 3.5.0.20200106... 100%
    vhd:
    vhd: nsis.install v3.5.0.20200106 [Approved]
    vhd: nsis.install package files install completed. Performing other installation steps.
    vhd: Attempt to get headers for https://astuteinternet.dl.sourceforge.net/project/nsis/NSIS%203/3.05/nsis-3.05-setup.exe failed.
    vhd:   The remote file either doesn't exist, is unauthorized, or is forbidden for url 'https://astuteinternet.dl.sourceforge.net/project/nsis/NSIS%203/3.05/nsis-3.05-setup.exe'. Exception calling "GetResponse" with "0" argument(s): "The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel."
    vhd: Downloading nsis.install
    vhd:   from 'https://astuteinternet.dl.sourceforge.net/project/nsis/NSIS%203/3.05/nsis-3.05-setup.exe'
    vhd: ERROR: The remote file either doesn't exist, is unauthorized, or is forbidden for url 'https://astuteinternet.dl.sourceforge.net/project/nsis/NSIS%203/3.05/nsis-3.05-setup.exe'. Exception calling "GetResponse" with "0" argument(s): "The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel."
    vhd: This package is likely not broken for licensed users - see https://chocolatey.org/docs/features-private-cdn.
    vhd: The install of nsis.install was NOT successful.
    vhd: Error while running 'C:\ProgramData\chocolatey\lib\nsis.install\tools\chocolateyInstall.ps1'.
    vhd:  See log for details.
    vhd:
    vhd: nsis v3.5.0.20200106 [Approved]
    vhd: nsis package files install completed. Performing other installation steps.
    vhd:  The install of nsis was successful.
    vhd:   Software install location not explicitly set, could be in package or
    vhd:   default install location if installer.
    vhd:
    vhd: Chocolatey installed 1/2 packages. 1 packages failed.
    vhd:  See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
    vhd:
    vhd: Failures
    vhd:  - nsis.install (exited 404) - Error while running 'C:\ProgramData\chocolatey\lib\nsis.install\tools\chocolateyInstall.ps1'.
    vhd:  See log for details.

**Comment by al-cheb** [comment]
Duplicate:
https://github.com/actions/virtual-environments/issues/1396
