### ISSUE TITLE
Xcode 12 beta 4 

### ISSUE THREAD

**Issue by SebastianBoldt** [actions/virtual-environments#1418]
The new Beta is the first beta that provides builds that can be uploaded to Appstore Connect.
It would be amazing if if GHA would support this version.

**Tool information**
- Tool name: Xcode
- Add or update? Add
- Desired version: Xcode 12 beta 4
- Approximate size: 10gb
- If this is an add request:
  - Brief description of tool: Xcode IDE for building the iOS/macOS/tvOS/watchOS projects
  - URL for tool's homepage: https://download.developer.apple.com/Developer_Tools/Xcode_12_beta_4/Xcode_12_beta_4.xip

**Area for Triage**:
Apple

**Question, Bug, or Feature?**:

**Virtual environments affected**
- [x] maxOS 11.0 ??
- [x] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Ubuntu 20.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Can this tool be installed during the build?**
No

**Tool installation time in runtime**
10 gb would take to long

**Are you willing to submit a PR?**
Adding new version of Xcode should be covered by GHA team

**Comment by maxim-lobanov** [comment]
@SebastianBoldt , Hello!
We have already started deployment of image with Xcode 12.0 beta 4 on board: https://github.com/actions/virtual-environments/pull/1409
Deployment will be finished on Monday.

**Comment by tonyarnold** [comment]
@maxim-lobanov is there any way that GitHub could accelerate the release of these betas? Having our CI tooling lag behind our seeded tooling by two weeks is becoming a problem.

**Comment by AlenaSviridenko** [comment]
Hi @tonyarnold,
Unfortunately, it is not possible to add new betas to the already deployed images from the technical side. 
We have a lot of virtual machines to deploy new image to, it is a pretty long process, but we are constantly working on improving of this process in order to speed up delivery of the new versions of the critical software. 
Thank you for your patience.

**Comment by maxim-lobanov** [comment]
Hello everyone, just an update:
Deployment of Azure DevOps pools was finished a few hours ago. 
Deployment of GitHub Actions pools is still in progress. We are working to fix deployment issues that we faced. Sorry for inconvenience.

**Comment by maxim-lobanov** [comment]
One more update: 95% of GitHub VMs were updated. Deployment should be finished soon.
Also we have already started to work to deliver `Xcode 12 beta 5` that was released recently. We are expecting it to be deployed significantly faster.

**Comment by maxim-lobanov** [comment]
Deployment of GA images was finished yesterday (sorry for late notification).
Also we are on track to deliver Xcode 12 beta 5. Will update thread as soon as it is done

**Comment by al-cheb** [comment]
The image with Xcode 12 beta 5 has been deployed.

**Comment by maxim-lobanov** [comment]
Closing the issue since Xcode 12 beta 5 is deployed. Feel free to reopen if any

**Comment by Brett-Best** [comment]
Any timelines on Xcode 12 beta 6 and Xcode 11.7 beta 1?

**Comment by maxim-lobanov** [comment]
@Brett-Best, `Xcode 12 beta 6` will be deployed on Monday.
`Xcode 11.7 beta 1` is not included to the next image so will be deployed a bit later (approximately, Thu - Fri)

**Comment by Brett-Best** [comment]
Thanks @maxim-lobanov, would be cool if a page somewhere that gets updated with future image details (changes, eta). (:

**Comment by maxim-lobanov** [comment]
@Brett-Best , There are 2 ways to track next image content:
- pull-request: https://github.com/actions/virtual-environments/pull/1501
- pre-release: https://github.com/actions/virtual-environments/releases/tag/macos-10.15%2F20200825.1

Both pre-release and PR are created automatically right after image-generation as a first step of image-deployment.

**Comment by maxim-lobanov** [comment]
New image with Xcode 11.7 was recently deployed (you can be confused by (beta) label in documentation but it is the stable version. Apple just pushed version with the same build number).
