### ISSUE TITLE
Upgrading terraform version on Ubuntu 18.04 LTS has introduced breaking changes

### ISSUE THREAD

**Issue by elliotchaim** [actions/virtual-environments#1429]
**Describe the bug**
The `ubuntu-latest` runner has been updated with Terraform v0.13.0. This is a breaking change. Furthermore, the docs at [Ubuntu1804-README.md](https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu1804-README.md#L235) have not been updated to reflect this.

**Area for Triage**: 

**Question, Bug, or Feature?**: 
Bug

**Virtual environments affected**
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [x] Ubuntu 18.04 LTS
- [ ] Ubuntu 20.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Expected behavior**
One of:

- Terraform v0.12.29 to be installed on `ubuntu-latest`
- Terraform v0.13.0 to be the listed terraform version at [Ubuntu1804-README.md](https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu1804-README.md#L235)
- Create a new runner image when making breaking changes to the tooling

**Actual behavior**

GitHub workflows which rely on Terraform v0.12.29 fail without updates.

**Comment by Darleev** [comment]
Hello @elliotchaim,
Thank you for the reported issue.
We always install the latest version of tools into images. Terraform was updated in the scope of the newest ubuntu release. You can track deployment status using [the following link](https://github.com/actions/virtual-environments/#available-environments).
The documentation will be updated upon completion of the deployment.

**Comment by maxim-lobanov** [comment]
I suggest to use official `setup-terraform` action to freeze specific version: https://github.com/marketplace/actions/hashicorp-setup-terraform

**Comment by elliotchaim** [comment]
Thanks for the info @Darleev 

@maxim-lobanov That looks like a very good idea, thank you.

**Comment by Darleev** [comment]
@elliotchaim I'm going to close the issue.
In case of any questions, do not hesitate to contact us.

**Comment by khitrenovich** [comment]
@Darleev -
As @elliotchaim mentioned, `v0.13` is _incompatible_ with `v0.12` - Terraform is still in `v0` stage, and their minor changes are breaking. This change broke things for us too. IMHO, such things are not acceptable for mature "CI as a service" provider. Please consider reopening, or at the very least update documentation.

**Comment by Darleev** [comment]
@khitrenovich 
@maxim-lobanov provided good steps to mitigate the issue. 
Deployment is underway and you can track[ status here](https://github.com/actions/virtual-environments/#available-environments). The documentation will be updated as soon as the build is complete([ Link to PR](https://github.com/actions/virtual-environments/pull/1421) ).

**Comment by Obsecurus** [comment]
Is it possible to somehow reference a previous image using `20200806.0` ?

**Comment by khitrenovich** [comment]
> Is it possible to somehow reference a previous image using `20200806.0` ?

Suggestion above by @maxim-lobanov worked perfectly for us, and it will protect you from similar changes in the future.
