### ISSUE TITLE
`ubuntu-latest` should point to `ubuntu-20.04`

### ISSUE THREAD

**Issue by silverwind** [actions/virtual-environments#1430]
**Tool information**
- Tool name: `ubuntu-latest` image
- Desired version: `20.04`

**Question, Bug, or Feature?**:
Bug

**Virtual environments affected**
- [x] Ubuntu 20.04 LTS

The `ubuntu-latest` alias currently points to `ubuntu-18.04` and should be updated to `ubuntu-20.04` to point to the latest version. https://github.com/actions/virtual-environments/issues/228#issuecomment-637362224 mentions the alias was not switched yet because of missing tools, I wonder if those have been resolved yet.

**Comment by maxim-lobanov** [comment]
Hello @silverwind , as it is mentioned in documentation, `ubuntu-20.04` is still in preview:
```
Note: The Ubuntu 20.04 virtual environment is currently provided as a preview only.
The ubuntu-latest YAML workflow label still uses the Ubuntu 18.04 virtual environment.
```

Sorry, for now I can't provide ETA when it will go out of preview but thank you for raising this point. We will discuss and return back with update.

**Comment by silverwind** [comment]
Yeah, I'm aware. I just thought to open a tracking issue as there does not seem to be one yet 😉

**Comment by drpaneas** [comment]
Thanks for opening this issue. It happened to me that a C project was failing to compile to `ubuntu-latest` that is based on `18.04` atm while locally (I have `20.04`) it was running fine. It would be ideal if the GitHub Action documentation points to the exact version of what `ubuntu-latest` means, so there is no confusion.

**Comment by maxim-lobanov** [comment]
@drpaneas , GitHub documentation contains information about meaning `ubuntu-latest` tag. Please check [documentation](https://docs.github.com/en/actions/reference/virtual-environments-for-github-hosted-runners#supported-runners-and-hardware-resources).

**Comment by silverwind** [comment]
Closing this in favor of https://github.com/actions/virtual-environments/issues/1816 which seems to contain a plan for the switch.

**Comment by IGR2014** [comment]
Why don't just `ubuntu-stable` for stable (18.04 now, 20.04 later). And `ubuntu-latest` for latest?
