### ISSUE TITLE
Add Code Composer Studio (CCS)

### ISSUE THREAD

**Issue by kobi86** [actions/virtual-environments#1431]
**Tool information**
- Tool name: Code Composer Studio (CCS) 

- Tool license: Free
- Add or update? Add
- Desired version: 9.2.0.00013_win64.zip
(http://software-dl.ti.com/ccs/esd/CCSv9/CCS_9_2_0/exports/CCS9.2.0.00013_win64.zip)
- Approximate size: 
- If this is an add request:
  - Brief description of tool: Tool that helps compile C code on Windows 
  - URL for tool's homepage: https://www.ti.com/tool/CCSTUDIO
  - Provide a basic test case to validate the tool's functionality: 

**Area for Triage**:

**Question, Bug, or Feature?**:

**Virtual environments affected**
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Ubuntu 20.04 LTS
- [ X] Windows Server 2016 R2
- [X ] Windows Server 2019

**Can this tool be installed during the build?**

**Tool installation time in runtime**

**Are you willing to submit a PR?**

**Comment by maxim-lobanov** [comment]
Hello @kobi86 , thank you for feature request.
Considering the fact that this tool is pretty huge (1GB) and we don't have much requests for it, we wouldn't like to bake it into the image.

I suggest to investigate ways to install it in runtime during the build. You can find some examples on tool forum: https://e2e.ti.com/support/tools/ccs/f/81/t/814799
