### ISSUE TITLE
Ubuntu1804 MySQL password error

### ISSUE THREAD

**Issue by sw586** [actions/virtual-environments#1432]
MySQL password is not root as described in the help document. What is the default password

**Comment by Darleev** [comment]
Hello @sw586,
I have tested MySQL credentials and it seems everything is working as expected:
```
sudo service mysql start
mysql mysql -u root -proot -se "SELECT 0 as id"
```
Could you please verify on your side?

We are looking forward to your reply.

**Comment by Darleev** [comment]
I'm going to close the issue.
In case of any questions, feel free to contact us.
