### ISSUE TITLE
Add Android build-tools;30.0.2

### ISSUE THREAD

**Issue by moallemi** [actions/virtual-environments#1433]
**Tool information**
- Tool name: build-tools;30.0.2
- Add or update? Update

**Question, Bug, or Feature?**:
Feature

**Area for Triage**:
Android

**Virtual environments affected**
- [ ] macOS 10.15
- [X] Ubuntu 16.04 LTS
- [X] Ubuntu 18.04 LTS
- [X] Ubuntu 20.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Are you willing to submit a PR?**
Yes

**Comment by miketimofeev** [comment]
Hi @moallemi!
Thanks for your contribution! We're going to deploy images with 30.0.2 in 1-2 weeks.

**Comment by maxim-lobanov** [comment]
Closing since all changes were deployed
