### ISSUE TITLE
macOS update notification blocks UI tests

### ISSUE THREAD

**Issue by paulz** [actions/virtual-environments#1436]
**Describe the bug**
macOS update notification pops up sometimes while UI tests are running

**Area for Triage**: 
Apple

**Question, Bug, or Feature?**: 
Bug

**Virtual environments affected**
- [X] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Ubuntu 20.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Expected behavior**
No notification

**Actual behavior**
image checks for updates unpredictably. Please disable updates or provide steps to disable updates notifications.

![Screenshot_C2A5B4D2-C870-4767-B721-DA07A85F20A9](https://user-images.githubusercontent.com/59230/90625250-21837f80-e1ce-11ea-9256-3a7b77fd2955.jpg)

1. Run a UI test for longer than 5 minutes
2. Sometimes updates notifications are shown

We tried:
```
launchctl unload -w /System/Library/LaunchAgents/com.apple.notificationcenterui.plist
killall NotificationCenter || true
killall UserNotificationCenter || true
```
unload fails: `/System/Library/LaunchAgents/com.apple.notificationcenterui.plist: Operation not permitted while System Integrity Protection is engaged`

https://github.com/sparta-science/connect/runs/1002532655?check_suite_focus=true#step:5:6

Example of the failure:
https://github.com/sparta-science/connect/runs/1002356825?check_suite_focus=true#step:14:203
see build artifacts for screenshots and details showing running test is loosing focus due to notification window.

**Comment by maxim-lobanov** [comment]
Hello, could you please try to run the following code?:
```
updateName=$(softwareupdate -l | grep "Title: " | awk -F[:,] '{print $2}' | awk '{$1=$1};1')
if [ ! -z "$updateName" ]; then
    sudo softwareupdate --ignore "$updateName"
fi
```

**Comment by al-cheb** [comment]
Hello, @paulz 
As a temporary workaround you could use - https://github.com/sindresorhus/do-not-disturb-cli :
```
- name:  cli
        run: |
          npm install --global
```

**Comment by paulz** [comment]
Thank you @al-cheb, trying it now, works so far!
