### ISSUE TITLE
JAVA_TOOL_OPTIONS environment variable now set on Ubuntu?

### ISSUE THREAD

**Issue by fniephaus** [actions/virtual-environments#1437]
**Describe the bug**
The `JAVA_TOOL_OPTIONS` environment variable is set on Ubuntu, which should be the case according to [this line](https://github.com/actions/virtual-environments/blame/bb03b541e0a63c964dcf851817585d4bb4b38675/images/linux/scripts/installers/java-tools.sh#L49). However, this was not the case about a week ago. We noticed this because the environment variable is picked up by an invocation of `java --module-path ... --describe-module ...`.

**Area for Triage**: 
Java

**Question, Bug, or Feature?**: 
Bug

**Virtual environments affected**
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [x] Ubuntu 18.04 LTS
- [ ] Ubuntu 20.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Expected behavior**
`JAVA_TOOL_OPTIONS` is set, which is the case now.

**Actual behavior**
`JAVA_TOOL_OPTIONS` was not set a few days ago.

Current build:
https://github.com/hpi-swa/trufflesqueak/runs/1002639551?check_suite_focus=true

Same commit from three days ago:
https://github.com/hpi-swa/trufflesqueak/runs/990481739?check_suite_focus=true

We are fixing the build failure on our end. Nonetheless, it is unclear why `JAVA_TOOL_OPTIONS` is now set on Ubuntu. The two workers seem to run the identical software version. Could someone explain this please?

**Comment by Darleev** [comment]
Hello @fniephaus,
I have checked the issue. I believe the issue is not related to the JAVA_TOOL_OPTIONS environment variable. As far as I see, in the pipeline error message:
`AssertionError: ('HAMCREST', 'hamcrest', ['Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF8', 'hamcrest file:///home/runner/.mx/cache/HAMCREST_42a25dc3219429f0e5d060061f71acb49bf010a0/hamcrest.jar automatic', 'requires java.base mandated', 'contains org.hamcrest', 'contains org.hamcrest.core', 'contains org.hamcrest.internal'])`
This issue is Java-related and I think there is some issue in the code.
Please note that `JAVA_TOOL_OPTIONS` variable was not changed in the latest Ubuntu releases.

We are looking forward to your reply.

**Comment by fniephaus** [comment]
Correct, the build broke because of the `AssertionError`, and as I said we are fixing this. However, it is unclear why this wasn't a problem three days ago. `JAVA_TOOL_OPTIONS` was very likely not set, but why?

**Comment by maxim-lobanov** [comment]
@fniephaus , it definitely was set.
Both builds (failed and successful) were run on the same image version `20200806.0` (you can check it on `Set up job` step). It means that both builds were run on identical VMs.

Could it be some issue with your environment that could override or block environment variables on VM?

**Comment by fniephaus** [comment]
> Could it be some issue with your environment that could override or block environment variables on VM?

I don't think so, but it's not impossible. Both jobs were using an identical JDK and called out to `java --module-path ... --describe-module ...`, which checks `JAVA_TOOL_OPTIONS ` and print `Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF8`.

But anyway, we have fixed the issue on our end. Just wanted to double check that the environment has definitely not changed. Thanks for the swift response!

**Comment by andrew2net** [comment]
@fniephaus I bumped the same issue. How have you fixed it?

**Comment by fniephaus** [comment]
If you're a Truffle language dev and you use mx, update it. The fix is already available. If you don't know what I am talking about, you could try unsetting the environment variable before your script runs.

**Comment by andrew2net** [comment]
I'm Ruby dev. One of the gems in my project uses Java which raises the error. Anyway unsetting the environment variable helps. Thank you very much @fniephaus

**Comment by fniephaus** [comment]
In that case, let me reopen this issue. What do you think, @maxim-lobanov?

**Comment by eregon** [comment]
Since `JAVA_TOOL_OPTIONS` produces extra output I think it's going to be problematic for many cases.

**Comment by maxim-lobanov** [comment]
Unfortunately, I don't have context why this variable was set initially.
The single concern from my side about unsetting it is that it could affect customers who are expecting this variable to be set up.

We are not Java experts so if you can provide any context what `JAVA_TOOL_OPTIONS=-Dfile.encoding=UTF8` param does and how unsetting could affect existing customers, it would be helpful

**Comment by fniephaus** [comment]
[`JAVA_TOOL_OPTIONS`](https://docs.oracle.com/javase/8/docs/technotes/guides/troubleshoot/envvars002.html) "can be useful to augment a command line". In this case, it does what the flag suggests: set the file encoding to UTF8. [Here](https://openjdk.java.net/jeps/8187041) is a related JEP, its status however is still "draft". Git unfortunately doesn't tell us much why this environment variable is set (https://github.com/actions/virtual-environments/commit/f396818e23ecba9f79322615a55d190765a5fab5 is the commit). If we remove it, the JVM will fall back to the default encoding (whatever that is on each platform). It appears that `JAVA_TOOL_OPTIONS` is a problem for other projects as well, e.g.:

- https://github.com/ballerina-platform/ballerina-lang/commit/60e12e3dfbfdde60074c8864df4a2d44bd06e141
- https://github.com/relaton/relaton-ietf/commit/7bea391980b4c5cbd12a81dc9e9977de052ddd28#diff-a77b4f53dac18d1e289021f245022811
- https://github.com/dazuma/toys/blob/c4f2aac1f0c553ce796b64adc68d2465f9aa7bfd/.github/workflows/ci.yml#L39

**Comment by maxim-lobanov** [comment]
cc: @brunoborges for any thoughts

**Comment by MaryamZi** [comment]
> [`JAVA_TOOL_OPTIONS`](https://docs.oracle.com/javase/8/docs/technotes/guides/troubleshoot/envvars002.html) "can be useful to augment a command line". In this case, it does what the flag suggests: set the file encoding to UTF8. [Here](https://openjdk.java.net/jeps/8187041) is a related JEP, its status however is still "draft". Git unfortunately doesn't tell us much why this environment variable is set ([f396818](https://github.com/actions/virtual-environments/commit/f396818e23ecba9f79322615a55d190765a5fab5) is the commit). If we remove it, the JVM will fall back to the default encoding (whatever that is on each platform). It appears that `JAVA_TOOL_OPTIONS` is a problem for other projects as well, e.g.:
> 
> * [ballerina-platform/ballerina-lang@60e12e3](https://github.com/ballerina-platform/ballerina-lang/commit/60e12e3dfbfdde60074c8864df4a2d44bd06e141)

Yes, we also observed assertion failures due to the additional output 
`Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF8`.

> * [relaton/relaton-ietf@7bea391#diff-a77b4f53dac18d1e289021f245022811](https://github.com/relaton/relaton-ietf/commit/7bea391980b4c5cbd12a81dc9e9977de052ddd28#diff-a77b4f53dac18d1e289021f245022811)
> * https://github.com/dazuma/toys/blob/c4f2aac1f0c553ce796b64adc68d2465f9aa7bfd/.github/workflows/ci.yml#L39

**Comment by miketimofeev** [comment]
Images without JAVA_TOOL_OPTIONS=-Dfile.encoding=UTF8 were deployed. This issue can be closed.
