### ISSUE TITLE
Add Clang/LLVM 10 to Ubuntu 20.04, and make it the default

### ISSUE THREAD

**Issue by dpaoliello** [actions/virtual-environments#1444]
**Tool information**
- Tool name: Clang
- Tool license:  MIT license
- Add or update? Add
- Desired version: 10
- Approximate size: ~400Mb
- If this is an add request:
  - Brief description of tool: Clang Compiler and LLVM toolchain
  - URL for tool's homepage: https://clang.llvm.org/

**Area for Triage**:
C/C++

**Question, Bug, or Feature?**:
Feature

**Virtual environments affected**
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [X] Ubuntu 20.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Can this tool be installed during the build?**
Not easily or quickly: one could pull down the prebuilt binaries, but it wouldn't integrate with other build tools (e.g., if running the build via CMake).

**Tool installation time in runtime**
~30s for me locally

**Are you willing to submit a PR?**
Yes!

**Comment by al-cheb** [comment]
Hello, @dpaoliello 
The clang-10 is now available on Ubuntu 20.04 - https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-README.md
