### ISSUE TITLE
Update Visual Studio 2019 to install "Blend for Visual Studio" option

### ISSUE THREAD

**Issue by pculver** [actions/virtual-environments#1450]
**Tool information**
- Tool name: Visual Studio 2019 - Blend for Visual Studio option
- Tool license: 
- Update
- Desired version: Latest
- Approximate size: 

**Area for Triage**:
Visual Studio

**Question, Bug, or Feature?**:
"Feature"

**Virtual environments affected**
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Ubuntu 20.04 LTS
- [ ] Windows Server 2016 R2
- [X] Windows Server 2019

**Can this tool be installed during the build?**
I don't know

**Tool installation time in runtime**
Minimal

**Are you willing to submit a PR?**
No, beyond my experience with the environment generation.

**Comment by AlenaSviridenko** [comment]
Hi @pculver,
There is a component Microsoft.ComponentGroup.Blend for VS2019 that can be installed in runtime (takes about 20 seconds) with the following code:
```
steps:
  - name: Install Blend component
    run: |
       Start-Process -FilePath "C:\Program Files (x86)\Microsoft Visual Studio\Installer\vs_installer.exe" -ArgumentList "--add Microsoft.ComponentGroup.Blend --passive --norestart --wait --installpath ""C:\Program Files (x86)\Microsoft Visual 
 Studio\2019\Enterprise""" -Wait -PassThru
    shell: pwsh
```

Does installation in runtime work for you?

**Comment by pculver** [comment]
I am a bit new to Azure pipelines.  It might work.   What task would I add to the build process?  I tried both a command line and powershell tasks and neither produce YAML that exactly matches what you put above?

**Comment by AlenaSviridenko** [comment]
oh, you are using Azure DevOps, I provided step for GitHub Actions.
For Azure DevOps you can use the following code for YAML or use PowerShell V2 task:
```
steps:
- powershell: 'Start-Process -FilePath "C:\Program Files (x86)\Microsoft Visual Studio\Installer\vs_installer.exe" -ArgumentList "--add Microsoft.ComponentGroup.Blend --passive --norestart --wait --installpath ""C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise""" -Wait -PassThru'
  displayName: Install Blend Component
```

**Comment by AlenaSviridenko** [comment]
Hi @pculver, I am going to close this issue.
Please, feel free to reopen or file a new one if any help needed.

Thank you!
