### ISSUE TITLE
NuGet: No packages exist with this id in source: Private Repo

### ISSUE THREAD

**Issue by LekoLabs-DerekDiebold** [actions/virtual-environments#1451]
**Description**  
We are working on our first WPF application, and are being required to use the windows-latest image within our yaml.
Previously, all of our develoment was within .NetCore3.1 for Lambda deployment, so we used ubuntu-latest and the following would allow for restoring of our internal packages:

      name: Setup .NET Core if needed
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
        source-url: https://nuget.pkg.github.com/owner/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.OWNER_PAT}}

      name: Restore
      run: dotnet restore

Attempting to do this on windows-latest leads to the additional source not being referenced.
If we attempt to directly overwrite the NuGet.Config, we still do not find the necessary feed.

**Area for Triage**:  

['Area: .NET Core']
['Area: Servers']
['Area: Packages']
**Question, Bug, or Feature?**:  
"Bug"

**Virtual environments affected**  
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Ubuntu 20.04 LTS
- [ ] Windows Server 2016 R2
- [x] Windows Server 2019

**Expected behavior**  
Uniform behavior of actions/setup-dotnet@v1 regardless of OS, meaning the ultimate NuGet.Config is referenced with all sources

**Actual behavior**  
On windows-latest, partial NuGet.Config is being placed into the workspace, alongside the solution folder, but is not being referenced.

**Repro steps**  
1. Create yaml for windows-latest based upon dotnetcore example
2. Add private repository and Personal Access Token to setup-dotnet@v1
i.e
     name: Setup .NET Core if needed
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
        source-url: https://nuget.pkg.github.com/owner/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.OWNER_PAT}}
3.  Trigger the action, compilation should fail during the restore step.

**Comment by maxim-lobanov** [comment]
Hello @LekoLabs-DerekDiebold ,
I believe it is an issue with [actions/setup-dotnet](https://github.com/actions/setup-dotnet) task rather than VM. But I could be wrong because we don't have much context how Nuget authentication works.
@ZEisinger, could you please take a look?

**Comment by ZEisinger** [comment]
This seems related to https://github.com/actions/setup-dotnet/issues/101. If the suggestions there do not help, please feel free to open a new issue to address the problem. There are some existing inconsistencies with NuGet in that action that need to be addressed.

**Comment by LekoLabs-DerekDiebold** [comment]
Interesting reference point - in the same repository, projects which do not refer to a NuGet package that has UseWPF enabled to true (i.e. our database access NuGet), do restore fine.

Let's see what the folks at setup-dotnet say.

**Comment by maxim-lobanov** [comment]
@LekoLabs-DerekDiebold , thank you for creating an issue in `actions/setup-dotnet` repo. It is better place to address this issue since in this repository we track issues related to pre-installed software on Hosted images.
If you find out that the issue is caused by image, please let us know and we can reopen it.
