### ISSUE TITLE
Add Azure Dev Spaces

### ISSUE THREAD

**Issue by philipwolfe** [actions/virtual-environments#1452]
**Tool information**
- Tool name: Azure Dev Spaces
- Tool license: MIT
- Add or update? Add
- Desired version: Latest
- Approximate size:
- If this is an add request:
  - Brief description of tool: This tool is needed to configure Review Apps and Azure Dev Spaces for AKS.
  - URL for tool's homepage: https://github.com/Azure/dev-spaces
  - Provide a basic test case to validate the tool's functionality: 
From powershell:
 - az aks use-dev-spaces -g myResourceGroup -n myAKSCluster
 - azds show-context

**Area for Triage**:
Tool doesn't install

**Question, Bug, or Feature?**:
Feature

**Virtual environments affected**
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Ubuntu 20.04 LTS
- [ ] Windows Server 2016 R2
- [ X ] Windows Server 2019

**Can this tool be installed during the build?**
I wish.  No.  It does not seem to work on Azure Hosted Machines/Agents/Pipelines.  This is from my Logs:
```
"C:\Program Files\PowerShell\7\pwsh.exe" -NoLogo -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command ". 'D:\a\_temp\azureclitaskscript1597933375334.ps1'"
Installing Dev Spaces commands...
A separate window will open to guide you through the installation process.
Selecting Azure Dev Spaces Controller 'ReviewAppsCluster' in resource group 'Review-Apps' that targets resource 'ReviewAppsCluster' in resource group 'Review-Apps'...1s
Selecting dev space 'default' with controller 'reviewappscluster'...<1s

   Name     DevSpacesEnabled
-  -------  ----------------
*  default  True
Managed Kubernetes cluster 'ReviewAppsCluster' in resource group 'Review-Apps' is ready for development in dev space 'default'. Type `azds prep` to prepare a source directory for use with Azure Dev Spaces and `azds up` to run.
azds : The term 'azds' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At D:\a\_temp\azureclitaskscript1597933375332_inlinescript.ps1:5 char:15
+ $hostSuffix=$(azds show-context -o json | ConvertFrom-Json).controlle …
+               ~~~~
+ CategoryInfo          : ObjectNotFound: (azds:String) [], ParentContainsErrorRecordException
+ FullyQualifiedErrorId : CommandNotFoundException
##[error]Script failed with exit code: 1
```
The code for this step is:
```
          - task: AzureCLI@2
            displayName: get host suffix
            inputs:
              scriptType: pscore
              scriptLocation: inlineScript
              azureSubscription: $(azureConnection)
              inlineScript: |
                $resourceGroupName="Review-Apps"
                $clusterName="ReviewAppsCluster"

                az aks use-dev-spaces -n $clusterName -g $resourceGroupName -s default -y
                $hostSuffix=$(azds show-context -o json | ConvertFrom-Json).controller.hostSuffix
                echo "##vso[task.setvariable variable=HostSuffix]$hostSuffix"
```
So it appears that it doesn't install correctly.

![image](https://user-images.githubusercontent.com/61720289/90814330-9057fa00-e2ee-11ea-8179-fd012479bae4.png)

**Tool installation time in runtime**
Some say 1 min some say 30 min on web searched.

**Are you willing to submit a PR?**
Yes.

**Comment by maxim-lobanov** [comment]
Hello @philipwolfe , thank you for feature request. In our understanding, it makes sense to pre-install Azure Dev Spaces on images.

If you would like to submit PR - please do that (Ubuntu and Windows source code is open source) - we will help you to finalize your changes.

**Comment by LeonidLapshin** [comment]
Hi, @philipwolfe 
Azure Dev Spaces CLI added to image and will be available with next image release in 1-2 weeks :)
Thank you!

**Comment by al-cheb** [comment]
Hello, @philipwolfe 
The new images with Azure Dev Spaces CLI have been deployed.

1. Windows Server 2016 - https://github.com/actions/virtual-environments/blob/releases/win16/20201012/images/win/Windows2016-Readme.md
`Azure Dev Spaces CLI 1.0.20200921.3`

2. Windows Server 2019 - https://github.com/actions/virtual-environments/blob/releases/win16/20201012/images/win/Windows2016-Readme.md
`Azure Dev Spaces CLI 1.0.20200921.3`
