### ISSUE TITLE
Update php to 7.4.9 on windows and macOS.

### ISSUE THREAD

**Issue by shivammathur** [actions/virtual-environments#1456]
**Tool information**
- Tool name: `php`
- Tool license: `PHP License 3.01`
- Add or update? Update
- Desired version: `PHP 7.4.9`
- Approximate size: 20 MB
- If this is an add request:
  - Brief description of tool: PHP is a general-purpose scripting language.
  - URL for tool's homepage: https://www.php.net/
  - Provide a basic test case to validate the tool's functionality: `php -v`

**Area for Triage**: PHP

**Question, Bug, or Feature?**: Bug

**Virtual environments affected**
- [X] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Ubuntu 20.04 LTS
- [ ] Windows Server 2016 R2
- [X] Windows Server 2019

**Can this tool be installed during the build?**
Yes

**Tool installation time in runtime**
2-3 min

**Are you willing to submit a PR?**
Not required. Scripts exist for this I think.

**Notes**
- `windows-2019` has `PHP 7.4.7` and `macos-latest` has `PHP 7.4.8`. Both should be updated to `PHP 7.4.9` to match version on `Ubuntu` images.
- Changelog - https://www.php.net/ChangeLog-7.php
- Also it would be great if in future these are updated regularly like on `Ubuntu` images.

**Comment by maxim-lobanov** [comment]
Hello, PHP will be updated to 7.4.9 with next image rollout.
- MacOS Rollout will happen on Monday ([it is release notes](https://github.com/actions/virtual-environments/pull/1447/files))
- Windows Rollout will happen later next week

**Comment by shivammathur** [comment]
@maxim-lobanov Thanks for the update

**Comment by miketimofeev** [comment]
Hi @shivammathur!
Php 7.4.9 has been deployed both for macOS and Windows.
Thank you!
