### ISSUE TITLE
increase vm.max_map_count

### ISSUE THREAD

**Issue by shusson** [actions/virtual-environments#1457]
elasticsearch requires `vm.max_map_count=262144`. At the moment to run elasticsearch as a service in a workflow we have to do something like:

```
services:
        elasticsearch:
            image: docker.elastic.co/elasticsearch/elasticsearch:6.8.3
        steps:
            # the default github runner doesn't have a high enough max_map_count
            # but since the service runs before the step, we need to workaround
            - name: hack-es
              run: |
                  sudo sysctl -w vm.max_map_count=262144
                  /usr/bin/docker start "${{ job.services.elasticsearch.id }}"
                  sleep 20
                  curl http://localhost:9200/_cat/health
```

Is it possible to set the default vm.max_map_count to 262144 ?

**Virtual environments affected**

- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Ubuntu 20.04 LTS

**Can this tool be installed during the build?**

```
sudo sysctl -w vm.max_map_count=262144
```

**Comment by al-cheb** [comment]
PR to increase default value to  vm.max_map_count=262144: https://github.com/actions/virtual-environments/pull/1463

**Comment by al-cheb** [comment]
@shusson, image with the vm.max_map_count=262144 setting has been deployed:
![image](https://user-images.githubusercontent.com/47745270/91874034-673a5080-ec82-11ea-9466-251d3d5a5b20.png)

**Comment by shusson** [comment]
Thanks @al-cheb !
