### ISSUE TITLE
OpenMP threads count >0 tests stop working on Ubuntu 18.04 & 20.04

### ISSUE THREAD

**Issue by myselfhimself** [actions/virtual-environments#1465]
**Description**  
Since December 2019 pytest test cases in the gmic-py Python c++ binding project would succeed on Ubuntu 18.04.
Since the beginning of july, those tests fail. 
Running the [nektos/act](https://github.com/nektos/act) tool with an ubuntu 18.04 Docker image mimicking your virtual-environments config show 100% passing OpenMP tests with an identical workflow file and show that your online cloud Github Actions environment has issues possibly linked to its Ubuntu 18.04 VM configuration or its kernel (since Ubuntu 20.04 shows the same errors).
Have you changed something on your hosts' kernel or ubuntu images possibly preventing OpenMP from spawning threads?

**Area for Triage**:  
Area: Containers
Area: C/C++
Area: Deployment/Release

**Question, Bug, or Feature?**:  
Bug

**Virtual environments affected**  
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [x] Ubuntu 18.04 LTS
- [x] Ubuntu 20.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Expected behavior**  
When C/C++ OpenMP test for number of threads being run, the number of those should be >0
To help you understand the layers on top: gmic-py under test using the pytest testing framework, bind the libgmic c++ library which embeds openmp pragmas being called through a meta-language for image processing named G'MIC.

**Actual behavior**  
Flakiness of testing with 5% chance or less of having those number of threads >0, when it should be 100% (and is so locally with nektos/act or without any docker image and handmade testing on my bare-bones Ubuntu 18.04).

**Repro steps**
1. [Run the cpython debug workflow file](https://github.com/myselfhimself/gmic-py/actions/runs/218159941)
2. Look at the logs for the 10-times repeated `test_run_gmic_ensure_openmp_linked_and_working` tests, notice they are 99-100% failing.
3. On a Linux OS: git clone the [gmic-py](https://github.com/myselfhimself/gmic-py) project and switch to the `numpy_io` branch or [this very recent same-branch commit](https://github.com/myselfhimself/gmic-py/commit/274571063ae97edca22e2efc1bfb30950bd8d47b). Install https://github.com/nektos/act for Linux, add `-P ubuntu-latest=nektos/act-environments-ubuntu:18.04` into a current directory `.actrc` file, possibly tune your Docker configuration if your /var/lib/docker drive cannot tolerate 6-18GB images (eg. put a user home-based folder instead), run `act` in order to mimick the Github Actions job. Observe 100% passing of the `test_run_gmic_ensure_openmp_linked_and_working` tests.

- The related issue on my side is here: https://github.com/myselfhimself/gmic-py/issues/47
  with related flakiness comment here: https://github.com/myselfhimself/gmic-py/issues/47#issuecomment-678232479
- Full example [logs here: ](https://pipelines.actions.githubusercontent.com/9MiDYuTy3eQpuvrrQPPq0lWobVQUxb871uDlQtJ2k8z2rQfRYd/_apis/pipelines/1/runs/1374/signedlogcontent/3?urlExpires=2020-08-21T11%3A36%3A14.0438596Z&urlSigningMethod=HMACV1&urlSignature=2Tcf0agroYAm6QrVU9aMf%2FwiX8PihKX7owjzGdnkcbw%3D) (look for: test_run_gmic_ensure_openmp_linked_and_working ; the test cases are run 10 times to help showcase flakiness)
The related pytest test case ensuring that the number of openmp threads open is >0 is here: https://github.com/myselfhimself/gmic-py/blob/numpy_io/tests/test_gmic_py.py#L52
- A C [ifdef check ensures that openmp's compilation flags is enabled](https://github.com/myselfhimself/gmic-py/blob/numpy_io/tests/test_gmic_py.py#L45). This check succeeds 100% as needed.
- An handmade ldd of the compiled binding shared library ensures that openmp's .so file is properly linked. Succeeds 100% as needed. Excerpt here:
`	libgomp.so.1 => /usr/lib/x86_64-linux-gnu/libgomp.so.1 (0x00007ff2a807c000)`

**Comment by maxim-lobanov** [comment]
Thank you for providing solution for your issue, it could be helpful for people who face with the same.
Sorry that we didn't have a chance to take a look earlier. Usually, such issues take more time to take a look because they require specific skillset.

Btw, usually, image changes can be tracked by history of readme file: https://github.com/actions/virtual-environments/commits/main/images/linux/Ubuntu1804-README.md

I am closing this issue but please let us know if you still need any assistance

**Comment by myselfhimself** [comment]
Thank you for taking the time to answer and pointing me to the Linux images
changelog. I am wondering if the amount of CPUs or Kernel has changed over
time and thus the OpenMP auto-setup of threads number would have been
impacted. So maybe the images themselves are not so related.
This issue's legacy will definitely help people with similar problems as
mine.
Best wishes :)

po 24. 8. 2020 v 8:59 odesílatel Maxim Lobanov <notifications@github.com>
napsal:
