### ISSUE TITLE
VS install doesn't include C++ UWP support?

### ISSUE THREAD

**Issue by asklar** [actions/virtual-environments#1469]
**Description**  
https://github.com/actions/virtual-environments/blob/main/images/win/Windows2019-Readme.md

It looks like VS install in windows-2019 does not include `Microsoft.VisualStudio.ComponentGroup.UWP.VC`. It includes `Microsoft.VisualStudio.ComponentGroup.UWP.Support` but not the C++ v142 tools.

**Area for Triage**:  
C/C++

**Question, Bug, or Feature?**:  
Bug

**Virtual environments affected**  
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Ubuntu 20.04 LTS
- [ ] Windows Server 2016 R2
- [X] Windows Server 2019

**Expected behavior**  
This payload should be installed

**Actual behavior**  
This payload is installed (vswhere.exe reports it as missing)

**Repro steps**  
`vswhere.exe -requires Microsoft.VisualStudio.ComponentGroup.UWP.VC` returns empty

**Comment by asklar** [comment]
The missing components due to not installing this component group are:
-	Microsoft.VisualStudio.Component.UWP.VC.ARM64
-	Microsoft.VisualStudio.PackageGroup.VC.Runtime.OSSupport.Downlevel
-	Microsoft.VisualStudio.VC.Templates.Windows.UAP

The first is individually included. The 2nd is used for Win7/Win8/Win8.1 support which we don't need. I'm not 100% sure about the 3rd, if it's only "new project" templates then I can see how it might not be needed for building in CI, it just makes it tricky because it is necessary to have this component on the local developer's machine or VS will complain about it and refuse to open the project.

**Comment by andy-mishechkin** [comment]
Hello, @asklar 
`Microsoft.VisualStudio.ComponentGroup.UWP.VC` has been added. You can find it after the next Windows images deployment (during this week).
If you will not find it - feel free to ping me in this ticket. Also it will be good, if you'll notify here if all will works as you wish.
Thank you.

**Comment by asklar** [comment]
Thanks @andy-mishechkin , I will check it out

**Comment by andy-mishechkin** [comment]
vswhere.exe -requires Microsoft.VisualStudio.ComponentGroup.UWP.VC, has been executed on GitHub runner. Workflow returns the component version.

**Comment by andy-mishechkin** [comment]
I've checked on the `windows-latest` runner - vswhere.exe -requires Microsoft.VisualStudio.ComponentGroup.UWP.VC returns the necessary information about workload.
