### ISSUE TITLE
Add [Microsoft.VisualStudio.Workload.WebBuildTools]

### ISSUE THREAD

**Issue by MarikoNakazawa** [actions/virtual-environments#1470]
**Tool information**
- Tool name: Microsoft.VisualStudio.Workload.WebBuildTools
- Tool license: 
- Add or update?: Add
- Desired version: 14.0.0.3
- Approximate size: 
- If this is an add request:
  - Brief description of tool: MSBuild tasks and targets for building web applications.
  - URL for tool's homepage: https://docs.microsoft.com/ja-jp/visualstudio/install/workload-component-id-vs-build-tools?view=vs-2019

**Area for Triage**:
.NET Core
.NET Framework

**Question, Bug, or Feature?**:
Feature

**Virtual environments affected**
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Ubuntu 20.04 LTS
- [○] Windows Server 2016 R2
- [○] Windows Server 2019

**Can this tool be installed during the build?**
Possible
Install using Nuget package
Change the path of the tool referenced at build to that
１．Add the tools you want to install in the project definition and packages.config
２．Changed VsToolPath in the project definition to look under packages from the Visual Studio installation folder.
３．Perform package reconfiguration processing with Nuget Restore

**Tool installation time in runtime**
40Second

**Are you willing to submit a PR?**
yes

**Comment by LeonidLapshin** [comment]
Hey, @MarikoNakazawa
We have added the functionality for Visual Studio Build Tools workloads installation, Microsoft.VisualStudio.Workload.WebBuildTools will be included in the next image rollout :)

**Comment by LeonidLapshin** [comment]
Hey, @MarikoNakazawa
Unfortunately, Visual Studio Build Tools installation along with Visual Studio Enterprise caused unpredictable issues with the default MSBuild behavior(Enterprise one was replaced by the one from Build Tools). We are actively investigating these issues with the Visual Studio team and will be in touch with any new information on this ticket.

**Comment by LeonidLapshin** [comment]
Hi, @MarikoNakazawa
Visual Studio team confirmed Visual Studio Enterprise is the ultimate edition and includes all the components presented in Visual Studio Build Tools. The appropriate workload for VS Enterprise is Microsoft.VisualStudio.Workload.NetWeb
Could you please verify this workload is sufficient for your needs? It can be installed in runtime with the following inline PowerShell script:
```
      - name: add workload
        run: |
          cd "C:\Program Files (x86)\Microsoft Visual Studio\Installer\"
          $InstallPath = "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise"
          $WorkLoads = '--add Microsoft.VisualStudio.Workload.NetWeb'
          $Arguments = ('/c', "vs_installer.exe", 'modify', '--installPath', "`"$InstallPath`"", $WorkLoads, '--quiet', '--norestart', '--nocache')
          $process = Start-Process -FilePath cmd.exe -ArgumentList $Arguments -Wait -PassThru -WindowStyle Hidden
        shell: powershell
```
Thank you!

**Comment by LeonidLapshin** [comment]
Hi, @MarikoNakazawa
I'll close the issue for now, but if the provided workload for Visual Studio Enterprise works for you, feel free to reopen this ticket and we will add it to the image.
Thank you!
