### ISSUE TITLE
Update DacFx 18.5 to 18.5.1

### ISSUE THREAD

**Issue by dzsquared** [actions/virtual-environments#1476]
**Tool information**
- Tool name: DacFx
- Tool license: 
- Add or update? Update
- Desired version: latest, 18.5.1
- Approximate size: 
- If this is an add request:
  - Brief description of tool: 
  - URL for tool's homepage: 
  - Provide a basic test case to validate the tool's functionality: 

**Area for Triage**: Databases

**Question, Bug, or Feature?**: Feature

**Virtual environments affected**
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Ubuntu 20.04 LTS
- [X] Windows Server 2016 R2
- [X] Windows Server 2019

**Can this tool be installed during the build?**

**Tool installation time in runtime**

**Are you willing to submit a PR?**
PR incoming

**Comment by AlenaSviridenko** [comment]
@dzsquared, thank you for contribution!
PR was merged and changes will be delivered in the next image rollout which is approximately 1-2 weeks.

**Comment by miketimofeev** [comment]
@dzsquared we have deployed the new images with DacFX 18.5.1. I'm going to close the issue but please feel free to contact us if you have any concerns.
Thanks again for your contribution!
