### ISSUE TITLE
Update/Add cfg80211 and mac80211 kernel subsystems and mac80211_hwsim module

### ISSUE THREAD

**Issue by davidgoogle** [actions/virtual-environments#1480]
**Tool information**
- Tool name: cfg80211, mac80211, and mac80211_hwsim
- Tool license: GPL
- Add or update? Add
- Desired version: latest
- Approximate size: 
- If this is an add request:
  - Brief description of tool: 802.11 subsystem and testing tool for simulated testing of the 802.11 networking stack
  - URL for tool's homepage: https://www.kernel.org/doc/html/v4.14/driver-api/80211/index.html
  - Provide a basic test case to validate the tool's functionality: modprobe mac80211_hwsim

**Area for Triage**: Testing and code coverage

**Question, Bug, or Feature?**: Feature

**Virtual environments affected**
- [ ] macOS 10.15
- [x] Ubuntu 16.04 LTS
- [x] Ubuntu 18.04 LTS
- [x] Ubuntu 20.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Can this tool be installed during the build?**
No, it has to be enabled in the kernel.

**Tool installation time in runtime**
Unknown

**Are you willing to submit a PR?**
Yes if can be pointed in the right direction.

**Comment by al-cheb** [comment]
Hi, @davidgoogle 
Could you provide steps to install these `cfg80211, mac80211, and mac80211_hwsim`?

**Comment by davidgoogle** [comment]
They would have to be compiled into the Ubuntu kernel on the image that is used for the azure instances. I believe the compile options to be enabled are CONFIG_CFG80211, CONFIG_MAC80211, and CONFIG_MAC80211_HWSIM.

**Comment by Queenj30** [comment]
I believe the compile options to be enabled are CONFIG_CFG80211, CONFIG_MAC80211, and CONFIG_MAC80211_HWSIM.

**Comment by Queenj30** [comment]
@andy-mishechkin

**Comment by maxim-lobanov** [comment]
Thank you for feature request.
But we wouldn't like to perform this request for now. Modifying kernel is dangerous change that can bring maintenance issues on long term. This request covers very specific scenarios and we wouldn't like to take the risk since we need to be sure that our images are stable and healthy.

**Comment by umgefahren** [comment]
Hi,
I still have this issue and I need the mac80211_hswim kernel module. Sadly it can't even be installed through linux-modules-extra-`uname -r` since the Azure build, in contrast to the generic one, doesn't include that module. What is the proposed solution?
