### ISSUE TITLE
Is there a plan to enable virtualization on the windows-2019 image?

### ISSUE THREAD

**Issue by paziz001** [actions/virtual-environments#1481]
I would like to use a windows image with the capability of using docker with linux containers but Hyper-V cannot be enabled on the windows-2019 image

**Comment by AlenaSviridenko** [comment]
Hi @paziz001,
currently, we do not have any plans to enable virtualization on Windows, but [we are keeping in mind this feature](https://github.com/actions/virtual-environments/issues/183#issuecomment-610723516) as we have already received such requests.

Closing it as a duplicate of https://github.com/actions/virtual-environments/issues/183.
Please, let us know if you need any other assistance.
Thank you.
