### ISSUE TITLE
Reduce size of default PATH or provide mechanisms to configure it easily?

### ISSUE THREAD

**Issue by jpfeuffer** [actions/virtual-environments#1484]
**Description**  
We ran into a hard-to-find bug with python's setuptools that runs vcvarsall.bat internally and fails because of the very long default PATH that the windows-latest runner provides. Yes, we add a few entries but nothing compared to the huge default. I looked through the entries and we need only 10% of what is inside there. Is there any suggestion on how to handle this without hard-coding an own path or removing certain wildcard patterns (which may crash with updates to the runner)?

**Area for Triage**:  
Scripting and command line

**Question, Bug, or Feature?**:  
Question

**Virtual environments affected**  
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Ubuntu 20.04 LTS
- [ ] Windows Server 2016 R2
- [X] Windows Server 2019

**Expected behavior**  
I would like to have better control of the PATH and preferably a smaller default PATH.

**Actual behavior**  
See discussion in https://github.com/OpenMS/OpenMS/pull/4779. Starting from https://github.com/OpenMS/OpenMS/pull/4779#issuecomment-679384753

**Repro steps**  
https://github.com/OpenMS/OpenMS/pull/4779
Probably adding a few additional entries to the default path and then calling vcvarsall.bat is enough.

**Comment by nikita-bykov** [comment]
Hello @jpfeuffer! Unfortunately now we have no opportunity to reduce size of default PATH. But after some investigation of your issue we have found that:

1. We have `LongPathsEnabled` parameter enabled on Windows Server 2016/2019. See details in this comment (https://github.com/actions/virtual-environments/issues/1052#issuecomment-644212560);

2. You can try to use this function to remove one path from PATH:
```
function RemoveFrom-Path ($pathToRemove) {
    $parts = $env:PATH.Split(";") | Where-Object { -not ( $_ -match $pathToRemove) }
    $newPATH = [string]::Join(";", $parts)
    $env:PATH = $newPATH
    Write-Host "::set-env name=PATH::$newPATH"
}
RemoveFrom-Path "Google\\Cloud SDK"
RemoveFrom-Path "Microsoft SQL Server"
```
This code will continue to work in future image releases.
If you still have any issues please let us know.

**Comment by jpfeuffer** [comment]
Hi!
Thank you for your comment. While I _think_ 1) does not help much because of vcvarsall.bat calls a batch command to extend the path and therefore reaches the command line length limit, 2) is a nice temporary solution.

I think there should also be some work done on the Visual Studio (not using batch to setup the environment) and setuptools (only setup the environment, if not yet done) side.

**Comment by nikita-bykov** [comment]
Closing this for now since we can't reduce size of default PATH. @jpfeuffer please let us know if you have any concerns.
