### ISSUE TITLE
Installation of AWS SAM CLI fails

### ISSUE THREAD

**Issue by preinking** [actions/virtual-environments#1485]
**Description**  
Installation of AWS SAM CLI fails with error wget: unable to resolve host address ‘null’

**Bug**:  

**Virtual environments affected**  
- [ ] macOS 10.15
- [x] Ubuntu 16.04 LTS
- [x] Ubuntu 18.04 LTS
- [x] Ubuntu 20.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Expected behavior**  
Installation script should handle the permanent redirect returned by api.github.com and complete without errors

**Actual behavior**  
Installation script fails

**Repro steps**  
1. `packer build ubuntu1804.conf`

**Comment by preinking** [comment]
Using `curl -sL https://api.github.com/repos/awslabs/aws-sam-cli/releases/latest` works for me

**Comment by maxim-lobanov** [comment]
@preinking , Hello, could you please try to pull the latest master?
Issue was fixed yesterday in #1482

**Comment by preinking** [comment]
@maxim-lobanov pulling latest master with fix #1482 works for me

**Comment by maxim-lobanov** [comment]
Closing this one but please let me know if you still experience the same issue.
