### ISSUE TITLE
Add AutoHotkey for Windows

### ISSUE THREAD

**Issue by jkremp** [actions/virtual-environments#1486]
**Tool information**
- Tool name: AutoHotkey
- Tool license: GNU GPLv2
- Add or update? Add
- Desired version: Latest, 1.1.33.02
- Approximate size: 10MByte
- If this is an add request:
  - Brief description of tool: automation scripting language for Windows
  - URL for tool's homepage: https://www.autohotkey.com
  - Provide a basic test case to validate the tool's functionality: 

>  ; hotstrings - expand 'btw' to 'By the way' as you type
>   ::btw::By the way
>  
>   ; hotkeys - press winkey-z to go to Google
>   #z::
>   Run http://google.com
>   Return

**Area for Triage**:

**Question, Bug, or Feature?**:
"Feature"

**Virtual environments affected**
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Ubuntu 20.04 LTS
- [x] Windows Server 2016 R2
- [x] Windows Server 2019

**Can this tool be installed during the build?**
- download setup
- run setup
- make sure compiler `Ahk2Exe.exe` is installed, too

**Tool installation time in runtime**
- less than 30 seconds

**Are you willing to submit a PR?**
- depends on required knowledge, in general, yes

**Comment by maxim-lobanov** [comment]
Hello, thank you for feature request!
Considering very quick installation in runtime and specific scenarios, we wouldn't like to bake this tool into the image for now.

As for the installation in runtime, I suggest installation via choco, it requires less manual steps:
```
choco install autohotkey
```
