### ISSUE TITLE
Enabling Test Signing in Windows Server Runners

### ISSUE THREAD

**Issue by DepthDeluxe** [actions/virtual-environments#1497]
**Description**  
Github-managed Windows action runners do not have test-signing turned on for kernel extensions.  This makes it impossible to use managed runners to test kernel drivers as the only way to turn it on is to [reboot the system](https://docs.microsoft.com/en-us/windows-hardware/drivers/install/the-testsigning-boot-configuration-option) which will cause the action process to stop.

Our only other option leveraging GitHub-managed runners is to use a production certificate for testing which is impractical at this stage of our development cycle and raises security concerns regarding uploading our Extended Validation code signing certificate to GitHub.

See the Microsoft [Driver Signing Policy](https://docs.microsoft.com/en-us/windows-hardware/drivers/install/kernel-mode-code-signing-policy--windows-vista-and-later-).

Information on how to enable test signing of drivers is [here](https://docs.microsoft.com/en-us/windows-hardware/drivers/install/the-testsigning-boot-configuration-option).

**Area for Triage**:  Servers

**Question, Bug, or Feature?**: Feature

**Virtual environments affected**  
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Ubuntu 20.04 LTS
- [ ] Windows Server 2016 R2
- [x] Windows Server 2019

**Expected behavior**  
I expect to be able to start a kernel driver signed in test mode to used for automated verification of driver.

**Actual behavior**
In the test environment, the kernel driver cannot start up due to a digital certificate validation failure.

```
[ RUN      ] ServiceStartStopTests.CanStartAndStopOnce
System error 577 has occurred.

Windows cannot verify the digital signature for this file. A recent hardware or software change might have installed a file that is signed incorrectly or damaged, or that might be malicious software from an unknown source.
```

**Repro steps**

1. [Create a test-signed driver kernel driver package](https://docs.microsoft.com/en-us/windows-hardware/drivers/install/how-to-test-sign-a-driver-package)
2. Attempt to start the test-signed driver (`net start MyDriver` for a kernel service)

**Comment by maxim-lobanov** [comment]
Hello @DepthDeluxe ,
We have concerns about enabling test signing of drivers on Hosted images - Enabling test signing of drivers switches OS to [Test-Mode](https://docs.microsoft.com/en-us/windows-hardware/drivers/install/the-testsigning-boot-configuration-option#behavior-of-windows-when-loading-test-signed-code-is-enabled) that can cause unstable work of some apps and affect builds of other customers

**Comment by DepthDeluxe** [comment]
@maxim-lobanov if there are concerns taking this approach, I see 3 alternatives to the initial request:

(1) Create a custom GitHub-internal action that can set these options and trigger a reboot.  Users can import the action and it will trigger a reboot (or simply enable test signing) between steps.

(2) Enable GitHub-managed hosts to restart partway through test execution in a generic fashion.  This could benefit other use-cases as well, perhaps testing that an installed program starts up / runs a task at boot time.

(3) Create an additional virtual host type that supports test signing.  This could get a little unwieldy as you would open yourselves up to an explosion of permutations of configuration (i.e. Win Server 2019 + no test signing, Win Server 2019 + test signing, Win Server 2016 + no test signing, Win Server 2016 + test signing).  This could be mitigated with some type of host tagging to say "I want a host with XYZ feature" and as part of the preparation stage, the host configures itself before execution as part of a setup stage.  This could help scale system dependencies in a generic fashion instead of creating a pre-installed image with all possible software pre-installed.

**Comment by maxim-lobanov** [comment]
Thank you for your suggestions.
Unfortunately, (1) and (2) are not possible with current infrastructure.
As for the (3), different images and more flavors of existing images is something we're always considering. It is not possible for us to provide additional image configurations as you suggest at this time because of maintenance concerns and fragmentation.
We don't have immediate solution for this request but we will keep this request on mind and let you know if we have any updates.
