### ISSUE TITLE
Latest update to Windows-2019 broke our build (again)

### ISSUE THREAD

**Issue by Geod24** [actions/virtual-environments#1498]
**Describe the bug**
The update from:
```
Virtual Environment
  Environment: windows-2019
  Version: 20200802.1
  Included Software: https://github.com/actions/virtual-environments/blob/win19/20200802.1/images/win/Windows2019-Readme.md
```

to:
```
Virtual Environment
  Environment: windows-2019
  Version: 20200820.1
  Included Software: https://github.com/actions/virtual-environments/blob/win19/20200820.1/images/win/Windows2019-Readme.md
```
Led to our tests starting to fail because of a missing `#include`.

**To Reproduce**
I didn't reduce the code, because the issue is quite simple to fix.
Essentially, just run the `build.d` script in https://github.com/bpfkorea/agora/tree/9cd2b987593b038caffa43b97c8b69bff4f03e1a/source/scpp with `dub build.d`.

**Expected behavior**
I would really, really, really like it if Github offered me a way to freeze which runner image I'm using. CI runs should be *reproducible* but with the current setup, they are not, and things start to randomly fail (or can't be rebuilt later) when Github decides to update an image.

The failure itself is quite simple: It's a missing `#include`. While it *is* an issue with our code this time, not having the ability to control whenever updates are applied. This automatic update process completely negates the benefit of having a containerized environment:
1) Releases are not reproducible anymore. If I built my release for tag `1.2.3` using `windows-2019` 10 days ago, and I do it today, I'll get a binary compiled with a different compiler, and different dependencies, with no code change. This is *terrible*.
2) Likewise, tests / scripts written under one environment might suddenly start to fail because of a dependency update. The scripts might be poorly written in the first place, but it's not a reason to break them needlessly.
3) Those failures can be *very hard* to track down for people not intimately familiar with the CI / project setup, because suddenly things fail for reasons independent of their code. When dealing with a CI, you don't expect your main branch to suddenly turn red without change.

Some links:
- Commit before update: https://github.com/bpfkorea/agora/commit/4fc127860126d78610676c92d49fdad55576aa66
- Associated action run: https://github.com/bpfkorea/agora/runs/1024853508
- Commit after update (which doesn't touch any code and just disables a test): https://github.com/bpfkorea/agora/commit/9cd2b987593b038caffa43b97c8b69bff4f03e1a
- Run after update: https://github.com/bpfkorea/agora/runs/1032909322
- The fix we needed: https://github.com/bpfkorea/agora/commit/2aab6f9de31a050f176c13bf40b05f8d96c5690b

This is not the first time it happens, but I'd like it if there could be a way to make it the last.

**Comment by AlenaSviridenko** [comment]
Hi @Geod24,
Thank you for detailed description and for raising this concern.
However, we do not have plans to support image versioning and there are few reasons for it:

1.  It is complicated from the maintenance side to keep and support different images

1. Image versioning is not solving the initial issue with breaking changes in software updates: it wouldn't be possible to keep every image forever, and sooner or later image update will happen and it will bring a lot more issues that a weekly updated software. 
On our side we have a significant amount of tests to catch as many breaking changes as possible, and we are constantly working on improving these tests and coverage but, unfortunately, we cannot test all possible scenarios.

1. To be aware about upcoming updates we are highly recommending tracking new releases in this repo where we post the upcoming software updates. In order to not miss any release you can subscribe to them to get notifications.

Your issue appeared after upgrading Visual Studio to 16.7 and most likely your build will fail on your local machine as well after this upgrade.

Please, let me know if you have any questions. Thanks!

**Comment by Geod24** [comment]
Thanks for taking the time to write a detailed answer @AlenaSviridenko . 

Just to be clear, I originally refrained myself from suggesting a specific approach, as I'm obviously not familiar with the culture or architecture of how things are delivered. However, you raised a few points which seems to be hinting at a specific solution (keeping all weekly images around forever), so I wanted to give some feedback.

> 1. It is complicated from the maintenance side to keep and support different images

I assume supporting means "providing security upgrades for old images" ? If so, I was not advocating for it.
I believe a simple "We release a frozen image every 3 months" would be enough to solve this specific issue, at least in my case.

> 2. Image versioning is not solving the initial issue with breaking changes in software updates: it wouldn't be possible to keep every image forever, and sooner or later image update will happen and it will bring a lot more issues that a weekly updated software.

The issue here is not so much about breaking changes or not, it's about controlling when it happens. Downstream developers want breakage to their projects to happen on their schedule, not on upstream's. SemVer is such a great framework not because it removes breaking change, but because it introduces specific points at which those needs to be dealt with.

As for keeping images around, we're talking about a few images per year (surely not all images), so I would image it isn't *this* hard.

> To be aware about upcoming updates we are highly recommending tracking new releases in this repo where we post the upcoming software updates. In order to not miss any release you can subscribe to them to get notifications.

This got me a bit confused actually. I see you have a "Rollout progress" percentage in the readme. And the failure started last night (KST), while the offending release was 6 days ago. Which means that even if I was subscribing to this repository, the connection between the failure and the upgrade wouldn't be that obvious.
Which actually leads to a side question: Are runners tied to a project, or freely assigned ? Would it be possible for a project to be assigned one version of a runner for one PR, and another version for another PR, while the image is being deployed ?

> Your issue appeared after upgrading Visual Studio to 16.7 and most likely your build will fail on your local machine as well after this upgrade.

My team develop on Linux / Mac, so it didn't.

> Please, let me know if you have any questions. Thanks!

What would the JS ecosystem looks like without `package-lock.json` ?

**Comment by AlenaSviridenko** [comment]
> As for keeping images around, we're talking about a few images per year (surely not all images), so I would image it isn't this hard.

I understand the reason for asking this and your idea, but supporting these images (there are still can be issues with the software even on a frozen images, so it is not only about security patches) and updating them, managing capacity for them and possible fragmentation would bring a lot of pain in maintaining.

>  And the failure started last night (KST), while the offending release was 6 days ago. Which means that even if I was subscribing to this repository, the connection between the failure and the upgrade wouldn't be that obvious.

Usually image is propagated to all customers in a 3-5 days after release is created. 
But the process is built that way that is very unlikely that one PR uses updated version and another one not updated version.

> What would the JS ecosystem looks like without package-lock.json ?

We would have to keep in mind all the required versions 🙂

**Comment by Geod24** [comment]
> would bring a lot of pain in maintaining.

Well, auto-updating just pushes the pain to consumers.

> But the process is built that way that is very unlikely that one PR uses updated version and another one not updated version.

Even something that has one chance in a million to happen will happen pretty frequently with the scale you are dealing with.

> We would have to keep in mind all the required versions 🙂

Good thing `git` commits and tags never go away :)

----

Since it seems that was already discussed internally, I guess I'll just have to agree to disagree, and I suppose I can work around this issue on my end by having my own runners.
