### ISSUE TITLE
Add Swift

### ISSUE THREAD

**Issue by kaylangan** [actions/virtual-environments#15]
**Tool information**
- Tool name: Swift
- Add or update? Add
- Desired version: 
- Approximate size: 
- If this is an add request:
  - Brief description of tool: Swift is a programming language for Apple products
  - URL for tool's homepage: https://developer.apple.com/swift/

**Virtual environments affected**
- [ ] macOS 10.14
- [x] Ubuntu 16.04 LTS
- [x] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Can this tool be installed during the build?**

**Are you willing to submit a PR?**

**Comment by ydnar** [comment]
The Swift team has a great Docker image which could be adapted for this:

https://github.com/apple/swift-docker/blob/master/nightly-5.2/ubuntu/18.04/Dockerfile

**Comment by nikita-bykov** [comment]
We have added Swift support to Ubuntu 16.04 and Ubuntu 18.04. Images with changes will be rolled out around next week.

**Comment by ydnar** [comment]
Just ran three workflows on Ubuntu with the preinstalled swift. All green. Thanks everyone!

**Comment by freak4pc** [comment]
It’s been 11 days since your message and I see rollout is around 50%... any ideas when it’ll be available everywhere? My workflows don’t have Swift available.

**Comment by maxim-lobanov** [comment]
@freak4pc , rollout is still in progress. Usually, we don't deploy on Friday to avoid weekend rollbacks :)
Planning to finalize on Monday

**Comment by freak4pc** [comment]
That's perfect, thank you so much for the quick reply :)

**Comment by nikita-bykov** [comment]
All changes were successfully deployed.
