### ISSUE TITLE
Add Tcl

### ISSUE THREAD

**Issue by vanosg** [actions/virtual-environments#150]
**Tool information**
- Tool name: Tcl and Tcl development files
- Add or update? Add
- Desired version: Tcl 8.5.19, 8.6.0 on Ubuntu 18.04; 8.4.20, 8.5.19, 8.6.0 on Ubuntu 16.04
- Approximate size:
- If this is an add request:
  - Brief description of tool: Tcl is a high-level, general-purpose, interpreted, dynamic programming language.
  - URL for tool's homepage: www.tcl.tk

**Virtual environments affected**
- [ ] macOS 10.15
- [X] Ubuntu 16.04 LTS
- [X] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Can this tool be installed during the build?**
Via apt, less than a minute
For 16.04/18.04:
8.6.0: apt-get install tcl tcl-dev
8.5.19: apt-get install tcl8.5 tcl8.5-dev
For 16.04:
8.4: apt-get install tcl8.4 tcl8.4-dev

**Are you willing to submit a PR?**
Yes, please let me know if you want me to start one, or any guidelines for doing so

Thank you!

**Comment by kaylangan** [comment]
Thanks for the suggestion! Let's hold off on adding this for now. We'd like to see more demand for this addition, especially if it can be installed as part of the workflow and doesn't need to be pre-installed.

**Comment by alepauly** [comment]
@vanosg I'll close this for now but please let us know if you see a change that should make us reconsider baking it into the image. Thanks!
