### ISSUE TITLE
Windows builds have been failed - choco error.

### ISSUE THREAD

**Issue by andy-mishechkin** [actions/virtual-environments#1505]
**Description**  
Windows builds have been failed:
https://dev.azure.com/github/virtual-environments/_build/results?buildId=79718&view=results
https://dev.azure.com/github/virtual-environments/_build/results?buildId=79719&view=results

**Question, Bug, or Feature?**:  
"Bug"

**Virtual environments affected**  
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Ubuntu 20.04 LTS
- [X] Windows Server 2016 R2
- [X] Windows Server 2019

**Expected behavior**  
Windows builds will be successful

**Actual behavior**  
We have a issue with choco installation: Error - hashes do not match. Please see the build logs for details.

**Comment by gep13** [comment]
@andy-mishechkin @al-cheb just to provide some insight into this particular error (if you already know this, then feel free to ignore 😄)

A checksum error can occur for a number of reasons, and I captured the main ones in a blog post that I did here:

https://www.gep13.co.uk/blog/chocolatey-error-hashes-do-not-match

I haven't investigated this particular package, so I can't provide any clarity on exactly "why" it is failing, but the blog post might help guide in the correct direction.

**Comment by al-cheb** [comment]
@gep13 , Thank you for your help. Looks like it's a transient issue with the mingw package.
