### ISSUE TITLE
Add Android emulator images

### ISSUE THREAD

**Issue by eric-labelle** [actions/virtual-environments#1509]
**Tool information**
- Tool name: android emulator images
- Add or update? Add
- Desired version: 
```
- system-images;android-23;default;x86
- system-images;android-23;google_apis;x86
- system-images;android-24;google_apis;x86
- system-images;android-24;google_apis_playstore;x86
- system-images;android-25;google_apis;x86
- system-images;android-25;google_apis_playstore;x86
- system-images;android-26;google_apis;x86
- system-images;android-26;google_apis_playstore;x86
- system-images;android-27;google_apis;x86
- system-images;android-27;google_apis_playstore;x86
- system-images;android-28;default;x86
- system-images;android-28;google_apis;x86
- system-images;android-28;google_apis_playstore;x86
- system-images;android-29;google_apis;x86
- system-images;android-29;google_apis_playstore;x86
- system-images;android-30;google_apis;x86
- system-images;android-30;google_apis_playstore;x86
```
- Approximate size: ~50GB
- If this is an add request:
  - Brief description of tool: these are all the system images used by the Android emulator in UI Testing pipelines
  - URL for tool's homepage: https://developer.android.com/studio/run/managing-avds
  - Provide a basic test case to validate the tool's functionality: 
```
// This will download the default system image for API28
echo "y" | $ANDROID_HOME/tools/bin/sdkmanager --install 'system-images;android-28;default;x86'
--
// This will create an avd for API28 (you can test all system images if needed)
echo "no" | $ANDROID_HOME/tools/bin/avdmanager create avd -n android_emulator -k 'system-images;android-28;default;x86'
// Validate it's successfully created (you should see one avd named android_emulator)
avdmanager list avd
```

**Area for Triage**:
Android 

**Question, Bug, or Feature?**:
"Feature"

**Virtual environments affected**
- [X] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Ubuntu 20.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

** I only use macOS images, but this could be beneficial for any OS since I'm sure people run Android UI Tests on any OS.

**Can this tool be installed during the build?**
Yes, but that's what I'm trying to prevent since It takes an additional 2min+ on every pipelines

**Tool installation time in runtime**
~2min to download system image depending on network speed

**Are you willing to submit a PR?**
Yes, but the OSX image generation script is still not available for contributions

**Comment by maxim-lobanov** [comment]
Hello, thank you for suggestion.
Unfortunately, 50 Gb is very huge size that we can't afford to pre-install on images due to maintenance concerns (it will significantly increase image-generation time, image promotion, deployment time).
Also, previously, we have already discussed installing the latest emulators in #663 and #836  but we don't have such plans for now.

As you mentioned above, emulators can be pre-installed in runtime using sdkmanager. If you would like to speed up installation in runtime, I suggest to take a look at [actions/cache](https://github.com/actions/cache). It is official GH task that allows to cache binaries between builds. It can be used to cache downloaded system images

**Comment by eric-labelle** [comment]
Then why all the [iOS simulator images](https://github.com/actions/virtual-environments/blob/main/images/macos/macos-10.15-Readme.md#installed-simulators) are already installed? 
I know it's huge, but at least one or two images would be nice. I currently use the azure pipeline cache task, but it's really slow and almost take more time to fetch the image from cache compared to simply redownloading it.

**Comment by maxim-lobanov** [comment]
Those iOS simulators are distributed as a part of Xcode versions. We don't pre-install additional iOS simulators for the same reason: https://github.com/actions/virtual-environments/issues/551.
Sorry for inconvenience, we should be very selective about installing new software to avoid maintenance hell.
