### ISSUE TITLE
Do not use snaps on Linux/Ubuntu

### ISSUE THREAD

**Issue by paolomainardi** [actions/virtual-environments#1514]
**Description**  

Currently the project is using Snaps for 2 packages, specifically

1. https://github.com/actions/virtual-environments/blob/main/images/linux/scripts/installers/git.sh
2. https://github.com/actions/virtual-environments/blob/main/images/linux/scripts/installers/kubernetes-tools.sh

While snaps are nice and useful on desktop to have the latest version of a package, they also come with stability and performance issues and they are also dependent by systemd daemon always running.
Just as an example [github/hub](https://github.com/github/hub) [is not recommending to install the snap anymore.](https://github.com/github/hub/issues?q=is%3Aissue+snap).

**Area for Triage**:  

['Area: Scripting and command line']

**Question, Bug, or Feature?**:  

Feature

**Virtual environments affected**  
- [ ] macOS 10.15
- [x] Ubuntu 16.04 LTS
- [x] Ubuntu 18.04 LTS
- [x] Ubuntu 20.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Expected behavior**  

Installing packages without Snap.

**Actual behavior**  

Some packages use Snap.

**Comment by maxim-lobanov** [comment]
@paolomainardi , Thank you for contributions! I have merged both PRs.
We will keep on mind that we should not install software via snap in future.

**Comment by maxim-lobanov** [comment]
New image will be deployed in a week

**Comment by paolomainardi** [comment]
Thanks a lot @maxim-lobanov

**Comment by miketimofeev** [comment]
We've successfully deployed new images. I'm going to close the issue.
@paolomainardi thank you for your contribution!
