### ISSUE TITLE
Is hostedtoolcache do any cacheing etc

### ISSUE THREAD

**Issue by jascodes** [actions/virtual-environments#1517]
Quick question; ist hostedtoolcache it just temp folder or any caching can be done??

Thx

**Comment by dibir-magomedsaygitov** [comment]
Hello, @jascodes. Could you please clarify what do you want to cache?

**Comment by maxim-lobanov** [comment]
@jascodes , hostedtoolcache is just term that describes the set of tools for which we install multiple versions. 
If you use Hosted agent, this folder is reset after every build.

**Comment by jascodes** [comment]
@dithx for reply
@maxim-lobanov Yeah I got it m, thx
