### ISSUE TITLE
Update Python 3.9 release candidate 1

### ISSUE THREAD

**Issue by cclauss** [actions/virtual-environments#1518]
**Tool information**
- Tool name: Python 3.9.0 release candidate 1
- Tool license: Python Software Foundation License https://docs.python.org/3/license.html
- Add or update? Upgrade
- Desired version: Python 3.9.0 release candidate 1
- Approximate size: 
- If this is an add request:
  - Brief description of tool: We ___strongly encourage___ maintainers of third-party Python projects to prepare their projects for 3.9 compatibility during the release candidate phase.
  - URL for tool's homepage: https://www.python.org/download/pre-releases/
    - https://docs.python.org/release/3.9.0rc1/whatsnew/changelog.html
  - Provide a basic test case to validate the tool's functionality: 

**Area for Triage**:

**Question, Bug, or Feature?**:

**Virtual environments affected**
- [x] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [x] Ubuntu 20.04 LTS
- [ ] Windows Server 2016 R2
- [x] Windows Server 2019

**Can this tool be installed during the build?**

**Tool installation time in runtime**

**Are you willing to submit a PR?**

**Comment by maxim-lobanov** [comment]
@cclauss , could you please clarify what does it mean "is not working"?
`python-versions` has already contains `3.9.0-beta.4`, `3.9.0-beta.5`, `3.9.0-rc.1`. All available versions are listed in https://github.com/actions/python-versions/blob/main/versions-manifest.json

- [Example of YAML that selects all these versions](https://github.com/maxim-lobanov/dotnet-multilookup/blob/master/.github/workflows/python-test.yml)
- [Successful build](https://github.com/maxim-lobanov/dotnet-multilookup/runs/1047042187?check_suite_focus=true)

**Comment by cclauss** [comment]
Thank you @maxim-lobanov!!  I was using uses: actions/checkout@__master__ and actions/setup-python@__master__ which is a mistake in these daze...  switching to actions/checkout@__v2__ and actions/setup-python@__v2__ fixed these issues.  Thanks for all your efforts.

**Comment by maxim-lobanov** [comment]
Great!.
Feature to download python versions on-flight from actions/python-versions was released only in actions/setup-python v2.

**Comment by cclauss** [comment]
The issue was actions/setup-python@__master__ --> actions/setup-python@__main__ or actions/setup-python@__v2__

**Comment by cclauss** [comment]
@maxim-lobanov You folks are working on a release for https://www.python.org/downloads/release/python-390/ ?

**Comment by maxim-lobanov** [comment]
Yep, it is on our backlog
