### ISSUE TITLE
Add Homebrew Bundle

### ISSUE THREAD

**Issue by Brett-Best** [actions/virtual-environments#1523]
**Tool information**
- Tool name: Homebrew Bundle
- Tool license: https://github.com/Homebrew/homebrew-bundle/blob/HEAD/LICENSE
- Add or update? Add
- Desired version: N/A
- Approximate size: Unknown
- If this is an add request:
  - Brief description of tool: Bundler for non-Ruby dependencies from Homebrew, Homebrew Cask, Mac App Store and Whalebrew.
  - URL for tool's homepage: https://github.com/Homebrew/homebrew-bundle
  - Provide a basic test case to validate the tool's functionality:
`Brewfile`
```ruby
# https://github.com/Homebrew/homebrew-bundle

brew "rbenv"
brew "zsh"
brew "pandoc"
```

To use it run:
```
echo "--- Installing brew dependencies from Brewfile"
brew bundle
```

**Area for Triage**:
Apple

**Question, Bug, or Feature?**:
Feature

**Virtual environments affected**
- [x] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Ubuntu 20.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Can this tool be installed during the build?**
Yes, using `brew bundle` with a repo that has a `Brewfile` (see above)

**Tool installation time in runtime**
About 1-2mins, to add the `bundle` feature to the existing homebrew install. (it does this automatically when running the command listed)

**Are you willing to submit a PR?**
I don’t believe the macOS environment is open source yet?

**Comment by maxim-lobanov** [comment]
Hello @Brett-Best , actually, `brew bundle` feature is already integrated to brew.
If you do `brew bundle` in folder with `Brewfile`, brew will
1) clone `homebrew/homebrew-bundle` repo
2) install dependencies from Brewfile

From our side, we can just run `brew tap Homebrew/bundle` during image-generation. It will remove first step from your build (clone `homebrew/homebrew-bundle` repo) but actually, it will reduce your build time by 10-15 seconds. Remain time is downloading and installing dependencies

**Comment by Brett-Best** [comment]
```
Mon, 31 Aug 2020 10:55:39 GMT --- Installing brew dependencies from Brewfile
Mon, 31 Aug 2020 10:56:12 GMT ==> Tapping homebrew/bundle
Mon, 31 Aug 2020 10:56:12 GMT Cloning into '/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle'...
Mon, 31 Aug 2020 10:56:12 GMT Tapped 1 command (199 files, 278.8KB).
Mon, 31 Aug 2020 10:56:19 GMT Installing mint
```
Yeah, I had it working, just wondered if it was possible to cut down on the clone/install of the `Homebrew/bundle` download/extraction.
After the first line, I’m immediately calling `brew bundle` which seems to take ~33secs.

I’ll retest if the image is updated to run `brew tap Homebrew/bundle` during generation!

Thanks @maxim-lobanov

**Comment by dmitry-shibanov** [comment]
Hello, pull request was merged. Changes will be added next images rollout.

**Comment by dmitry-shibanov** [comment]
Hello changes were added to image. If you have any concerns feel free to reopen the issue.
