### ISSUE TITLE
Add gnu-tar

### ISSUE THREAD

**Issue by smorimoto** [actions/virtual-environments#1534]
**Tool information**

- Tool name: gnu-tar
- Tool license: GPL 3
- Add or update? Add
- Desired version: latest
- Approximate size: I don't know
- If this is an add request:
  - Brief description of tool: GNU Tar provides the ability to create tar archives, as well as various other kinds of manipulation. For example, you can use Tar on previously created archives to extract files, to store additional files, or to update or list files which were already stored.
  - URL for tool's homepage: https://www.gnu.org/software/tar
  - Provide a basic test case to validate the tool's functionality: `tar --version | grep GNU`

**Area for Triage**:

Packages

**Question, Bug, or Feature?**:

Feature

**Virtual environments affected**

- [x] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Ubuntu 20.04 LTS
- [x] Windows Server 2016 R2
- [x] Windows Server 2019

**Can this tool be installed during the build?**

Sure.

**Tool installation time in runtime**

I don't know.

**Are you willing to submit a PR?**

Sure if I have time at that time.

**Comment by smorimoto** [comment]
Related issues:

- https://github.com/actions/cache/issues/403
- https://github.com/actions/cache/issues/301

**Comment by smorimoto** [comment]
We don't need to replace the default command with gnu-tar on each platform, but by installing it by default, we should be able to avoid quite a few problems just by setting the path without taking installation time when using it from any actions.

**Comment by maxim-lobanov** [comment]
Hello, actually, gnu-tar is already available on Windows images and is located on `C:\Program Files\Git\usr\bin\tar.exe` or `C:\msys64\usr\bin\tar.exe`.
I believe https://github.com/actions/toolkit/pull/553 should fix initial issue?

**Comment by smorimoto** [comment]
Hello again, @maxim-lobanov 🙂 I didn't notice that! Great.

**Comment by maxim-lobanov** [comment]
Is this issue actual for MacOS too? I didn't notice any reports about macOS.

**Comment by smorimoto** [comment]
There may be some differences in flags between BSD tar and GNU tar, but that shouldn't be a big problem. Well, I don't use macOS, so I don't know. What do you think? @dhadka

**Comment by maxim-lobanov** [comment]
Considering the fact that tar is already installed on Windows, I am going to close this issue.
If actions/cache needs gnu tar on MacOS too, please let us know and we will reopen this issue

**Comment by jensens** [comment]
`gnutar` provides the `--owner` and `--group` arguments which are missing with macos default tar (BSD tar?). 
Thus said,  it would be great to have it on macos too. At the moment this is an issue here, testing/building the CMS Plone unified installer using an GH action.

**Comment by anp** [comment]
@maxim-lobanov to work around https://github.com/actions/cache/issues/403 without additional install time it would need to be installed for macOS by default as well.

**Comment by maxim-lobanov** [comment]
@anp thank you for additional info. Probably, if we pre-install gnu-tar, actions/cache can use it by default. I have requested additional information in issue

**Comment by Cyberbeni** [comment]
@maxim-lobanov multiple people have issues with tar on macOS that are solved by switching to gnu-tar:
https://github.community/t/bizarre-issue-with-tar-archive-for-macos-build/145377
https://github.com/Cyberbeni/install-swift-tool/issues/69

**Comment by maxim-lobanov** [comment]
Thank you for everyone for sharing your feedback and requests.
We have decided to revisit this issue and install gnu-tar on MacOS images.
Reopened and moved to backlog

**Comment by Cyberbeni** [comment]
I haven't tested the compatibility between the two tars extensively but I would expect that setting the `tar` command to point to `gnu-tar` instead of just having it installed shouldn't break anything. At least when I restore a cache that was saved with `bsdtar`, I only get a warning, but it works perfectly: `/usr/local/opt/gnu-tar/libexec/gnubin/tar: Ignoring unknown extended header keyword 'LIBARCHIVE.creationtime'`

And this issue is rare enough that if we leave bsdtar as default, there will be issues about tar not working on macOS without any answer because people who know the answer don't read every issue of every repository that comes into contact with GitHub Actions.

(But having it installed by default would already be an improvement at least for my action, so I can avoid using `env HOMEBREW_NO_AUTO_UPDATE=1 brew install gnu-tar`)

**Comment by nikita-bykov** [comment]
We have added gnu-tar installation to macOS.
Images with it will be rolled out around next week.

**Comment by nikita-bykov** [comment]
All changes were successfully deployed
