### ISSUE TITLE
Clang/LLVM 10 will be set as a default one and Clang/LLVM 6 will be deprecated  for Ubuntu 20.04 on September, 23

### ISSUE THREAD

**Issue by AlenaSviridenko** [actions/virtual-environments#1536]
Hi!

We are going to add Clang/LLVM 10 to Ubuntu 20.04 and make it default one on September, 23. Also, we are going to deprecate Clang/LLVM 6 on Ubuntu 20.04.

Please, let us know through this issue if you have any concerns or questions.

Thanks!

**Comment by Shatur95** [comment]
After this change I can't install `clang-tidy`:

```
  clang-tidy-10 : Depends: libllvm10 (= 1:10.0.0-4ubuntu1) but 1:10.0.1~++20200708122807+ef32c611aa2-1~exp1~20200707223407.61 is to be installed
                 Depends: clang-tools-10 but it is not going to be installed
```

**Comment by Shatur95** [comment]
Workaround:

```
sudo apt-get remove libllvm10
sudo apt-get install clang-tidy-10
```

**Comment by al-cheb** [comment]
Hello, @Shatur95 
For clang-10 installation we use third-party repository which is not available after image generation - https://github.com/actions/virtual-environments/blob/main/images/linux/scripts/installers/clang.sh

```
wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key 2>/dev/null | sudo apt-key add -
sudo add-apt-repository 'deb http://apt.llvm.org/focal llvm-toolchain-focal-10 main' -y
sudo apt-get update -q
sudo apt-get install -y clang-tidy-10
```

**Comment by Shatur95** [comment]
Maybe just add `clang-tidy` to the image? Windows images have `clang-tidy` installed.

**Comment by al-cheb** [comment]
@Shatur95,
Sorry, currently we can't pre-install clang-tidy on Ubuntu 16.04/18.04/20.04 due to lack of free space on images. We are going to migrate to the official repository to eliminate additional manipulation with adding llvm repo or remove components(`sudo apt-get remove libllvm10`). I will let you know when a new image with the new repo is available.

**Comment by Shatur95** [comment]
> We are going to migrate to the official repository to eliminate additional manipulation with adding llvm

Thanks, it would be nice.

**Comment by Swatinem** [comment]
I have a similar problems, related to `clang-tools`:

```
> apt install clang-tools
    clang-tools : Depends: clang-tools-10 (>= 10~) but it is not going to be installed

> apt install clang-tools clang-tools-10

    clang-tools-10 : Depends: clang-10 (= 1:10.0.0-4ubuntu1) but 1:10.0.1~++20200708122807+ef32c611aa2-1~exp1~20200707223407.61 is to be installed
```

**Comment by nevun** [comment]
We have the same problem with ubuntu-20.04. relevant part from https://github.com/Yubico/pam-u2f/actions/runs/278140722/workflow#L23

```
sudo apt -q update
sudo apt install -q clang-tools-10
```
results in:

```
[ ... ]
The following packages have unmet dependencies:
 clang-tools-10 : Depends: clang-10 (= 1:10.0.0-4ubuntu1) but 1:10.0.1~++20200708122807+ef32c611aa2-1~exp1~20200707223407.61 is to be installed
E: Unable to correct problems, you have held broken packages.
Error: Process completed with exit code 10
```

**Comment by Swatinem** [comment]
Adding the apt repo as explained in the comment above seems to work

https://github.com/actions/virtual-environments/issues/1536#issuecomment-698537248

**Comment by AlenaSviridenko** [comment]
Default CLang version was updated, image with this update was deployed everywhere. Closing issue
