### ISSUE TITLE
Missing alternate Az Powershell versions on Ubuntu 20.04

### ISSUE THREAD

**Issue by wasabii** [actions/virtual-environments#1539]
https://github.com/actions/virtual-environments/blob/265cc1fb88f10120554ece8793b8fad225c5cee8/images/linux/scripts/installers/azpowershell.sh#L12

So, there's a bug that popped up in the 4.6.1 Az module for powershell. Can't deploy ARM templates with SecureString, or you get some weird error. The suggestion is to just go back to 4.5.0 since it works fine.

However, it looks like the Ubuntu 20.04 image ONLY installs whatever is the latest version at the moment. So, at some point (two days ago for me) the Azure DevOps Hosted Agent got updated to that new version, and my deployments began breaking. I figured, okay, that's not that bad, I can just configure the AzurePowershell@4 task to just use the earlier version.

Except I can't, at least on Ubuntu 20.04, because there are no old versions.

All the other images install multiple module versions from the defined list in toolset.json. Why not 20.04? Seems misguided.

**Comment by maxim-lobanov** [comment]
@wasabii , thank you for suggestion, we will consider installation multiple versions of Az on Ubuntu 20.04 image. As a work around, you can install any version of Az in runtime via PowerShell command:
```
$version = "4.5.0"
Save-Module -Name Az -LiteralPath /usr/share/az_$version -RequiredVersion $version -Force
```

**Comment by wasabii** [comment]
Ahh. Cool. Tried to install it in user scope and it wasn't happy. Didn't know I could just their it into usr/share. Thanks.

**Comment by AlenaSviridenko** [comment]
Closing this issue since installation in runtime fits the needs. 
Please, feel free to create a new one in case of any questions. Thanks!
