### ISSUE TITLE
Available Software list for VMs is Incomplete

### ISSUE THREAD

**Issue by mrmundt** [actions/virtual-environments#154]
**Request** 
The available software list for (at least) the MacOS Runner is incomplete. 
(Note: I reported this to Github Developer Support, and they suggested I report the issue here.)

**Description of Request**
My organization is attempting to implement Github Actions, and we have found that the list of software on the MacOS runners is incomplete. 

There is an old problem solver called "pico" that has been degraded, but we have tests built into our suite that will run if a "pico" executable is found. All of these tests keep triggering when we run our test MacOS github workflow, and one of our developers finally remembered that there is an old editor called "Pico" that exists on Macs. It is NOT listed on your software page (https://help.github.com/en/actions/automating-your-workflow-with-github-actions/software-installed-on-github-hosted-runners#macos-1015) - it would have been easier to diagnose if this was a complete list.

**Comment by AlenaSviridenko** [comment]
Hi @mrmundt !
We are not documenting soft that is built-in to MacOS because it is expected to be on the image, documentation contains the list of additionally installed software, like Xcodes, VS for Mac, Python and so on.

**Comment by maxim-lobanov** [comment]
Hi, I am closing this issue because it looks like @AlenaSviridenko has resolved the initial question, feel free to reopen if needs
