### ISSUE TITLE
Error when running kustomize on a GitHub action

### ISSUE THREAD

**Issue by mcaballeropinto** [actions/virtual-environments#1540]
**Description**  
- When building a [kustomize](https://github.com/kubernetes-sigs/kustomize) configuration that uses a remote resource, it fails with this error:
  ```
  Error: accumulating resources: accumulateFile "accumulating resources from 'git@github.com:mcaballeropinto/kustomize-github-action-test//remote-k8s': evalsymlink failure on '/home/runner/work/kustomize-github-action-test/kustomize-github-action-test/k8s/git@github.com:mcaballeropinto/kustomize-github-action-test/remote-k8s' : lstat /home/runner/work/kustomize-github-action-test/kustomize-github-action-test/k8s/git@github.com:mcaballeropinto: no such file or directory", loader.New "no 'git' program on path: exec: \"git\": executable file not found in $PATH"
  ```
- The error states that it can't find the git executable

**Area for Triage**:  
Go, Containers 

**Question, Bug, or Feature?**:  
Bug

**Virtual environments affected**  
- [ ] macOS 10.15
- [X] Ubuntu 16.04 LTS
- [X] Ubuntu 18.04 LTS
- [X] Ubuntu 20.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Expected behavior**  
kustomize does not return an error.

**Actual behavior**  
Kustomize returns this error:
```
  Error: accumulating resources: accumulateFile "accumulating resources from 'git@github.com:mcaballeropinto/kustomize-github-action-test//remote-k8s': evalsymlink failure on '/home/runner/work/kustomize-github-action-test/kustomize-github-action-test/k8s/git@github.com:mcaballeropinto/kustomize-github-action-test/remote-k8s' : lstat /home/runner/work/kustomize-github-action-test/kustomize-github-action-test/k8s/git@github.com:mcaballeropinto: no such file or directory", loader.New "no 'git' program on path: exec: \"git\": executable file not found in $PATH"
```

**Repro steps**  
- Here there is a failed action: https://github.com/mcaballeropinto/kustomize-github-action-test/actions/runs/236771376
- Here is a repo with reproducible code: https://github.com/mcaballeropinto/kustomize-github-action-test
- To repo it just push a new commit to that repo

**Comment by Darleev** [comment]
Hello @mcaballeropinto,
As far as I see in the sample repo, the issue is actual, however, I tried to do `kustomize build` locally, and got a very similar issue.
According to [kustomize official repository ](https://github.com/kubernetes-sigs/kustomize), I'm not sure that we can use github link in resources section, I also cannot find any information about it in the docs. Why did you use such implementation?

We are looking forward to your reply.

**Comment by mcaballeropinto** [comment]
Hi @Darleev,

Thanks for taking a look to this issue.

> I tried to do kustomize build locally, and got a very similar issue.

This runs on my machine fine. In fact, this same configuration was working when running on a GitHub action from a private repo before 09/01. It stopped working after that date. That is why I created the issue.

> I'm not sure that we can use github link in resources section

You can definitely do such things, it is supported. It is not well documented tho, here is the loader in the source code: https://github.com/kubernetes-sigs/kustomize/blob/16229095b366db0ede60045f68bf9898dbd461de/api/loader/loader.go#L25

> Why did you use such implementation?

Because I want to share common kustomize configuration across different services.

Let me know if you need more information.

**Comment by maxim-lobanov** [comment]
We have recently added kustomize 3.8.1 to our images. https://github.com/actions/virtual-environments/pull/1495/files#diff-43bac3def16599ef5b79ea8b7d9e0a9aR186
Before it was not pre-installed. I wonder if it could be reason for this issue

**Comment by mcaballeropinto** [comment]
@maxim-lobanov That sounds like a great lead. I wonder if the kustomize version that is installed do not use the same PATH environment variable for some reason, so when kustomize calls `LookPath` for "git" it does not find it.

I explain a little bit better my findings in this README: https://github.com/mcaballeropinto/kustomize-github-action-test

**Comment by maxim-lobanov** [comment]
Hm, we use recommended method to install kustomize `curl -s "https://raw.githubusercontent.com/\
kubernetes-sigs/kustomize/master/hack/install_kustomize.sh"  | bash` and actually this script just downloads binary and put it to image. No more configuration

**Comment by mcaballeropinto** [comment]
I can't reproduce this issue myself locally and I do not see any issue in kustomize repo, so my default thinking is that there is an issue in GitHub actions environments.

**Comment by Darleev** [comment]
@mcaballeropinto Could you please provide step by step instruction how to complete kustomize build locally? Unfortunately, I'm getting the following error message:

`Error: accumulating resources: accumulateFile "accumulating resources from 'github.com/mcaballeropinto/kustomize-github-action-test/tree/master/remote-k8s': evalsymlink failure on '/Users/darii.nurgaleev/Akvelon/kustomize-github-action-test/k8s/github.com/mcaballeropinto/kustomize-github-action-test/tree/master/remote-k8s' : lstat /Users/darii.nurgaleev/Akvelon/kustomize-github-action-test/k8s/github.com: no such file or directory", loader.New "evalsymlink failure on '/private/var/folders/w5/mf4zyvs97nx4jw8ckh50v1ph0000gp/T/kustomize-739163081/tree/master/remote-k8s' : lstat /private/var/folders/w5/mf4zyvs97nx4jw8ckh50v1ph0000gp/T/kustomize-739163081/tree: no such file or directory"`

**Comment by mcaballeropinto** [comment]
@Darleev 
> Could you please provide step by step instruction how to complete kustomize build locally?

As I explained in the readme of the repo, the only thing you need to do is run `kustomize build ./k8s` at the root folder of the repo. You can see an example in the `.github/workflows/test.yaml` file.

> Unfortunately, I'm getting the following error message

I think that error happens when an old version of kustomize is used that do not support remote configurations. Please try installing the same version used in GitHub Actions.

**Comment by mcaballeropinto** [comment]
I found a workaround. 

If I remove the by default installed kustomize and install it again, then it works. I added a working test in [the branch](https://github.com/mcaballeropinto/kustomize-github-action-test/tree/workaround-1 ) `workaround-1` of the same repo. There is also [a new successful execution](https://github.com/mcaballeropinto/kustomize-github-action-test/actions/runs/241005191) of an action from that branch.

I believe this probes that the default installation of kustomize on recent images does not work as expected.

Is there a way to fix my actions to a specific version of an image that do not have these updates?

**Comment by Darleev** [comment]
@mcaballeropinto [PR](https://github.com/actions/virtual-environments/pull/1515) should resolve the issue. 
So, we just need to wait for the next image rollout.
I will keep you informed.

**Comment by Darleev** [comment]
@mcaballeropinto good news, I have tested that in the latest ubuntu release the issue is not reproducing anymore.
I have verified in the [forked repository](https://github.com/Darleev/kustomize-github-action-test/runs/1113094131?check_suite_focus=true).
In case of any questions, feel free to contact us.
