### ISSUE TITLE
Matplotlib Qt backend not working

### ISSUE THREAD

**Issue by BrightRan** [actions/virtual-environments#1542]
Associated community ticket: https://github.community/t/matplotlib-qt-backend-not-working/129635

The customer used the "[jurplel/install-qt-action](https://github.com/jurplel/install-qt-action)" action in his workflow to install Qt.
But he encountered an issue when he used the following command from matplotlib:
```
matplotlib.use('Qt5Agg')
```
He got the following error:
```
ImportError: Failed to import any qt binding
```

This can work on his local machine.

**Comment by al-cheb** [comment]
Example: https://github.community/t/matplotlib-qt-backend-not-working/129635/10?u=al-cheb
