### ISSUE TITLE
Chrome no longer present on windows images

### ISSUE THREAD

**Issue by jonsamwell** [actions/virtual-environments#1546]
**Description**  
Google Chrome is no longer accessible in the standard folder location (`C:\Program Files (x86)\Google\Chrome`) this is making selenium test fail as it cannot find the Chrome exe.

**Question, Bug, or Feature?**:  
Bug

**Virtual environments affected**  
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Ubuntu 20.04 LTS
- [x] Windows Server 2016 R2
- [x] Windows Server 2019

**Expected behavior**  
Running command `ls "C:\Program Files (x86)\Google"` and the Chrome folder is present

**Actual behavior**  
Running command `ls "C:\Program Files (x86)\Google"` and the below is listed (notice the missing Chrome folder)

![image](https://user-images.githubusercontent.com/3694497/92210956-05245a00-eed3-11ea-99d0-c7bb4a8d432c.png)

**Comment by maxim-lobanov** [comment]
Hello @jonsamwell , it is known issue. Installation location was changed in Chrome 85 to `C:\Program Files\Google\Chrome\Application\chrome.exe`. It is not change on our side, but on Chrome side.

You can find more details how to mitigate this issue in community ticket: https://developercommunity.visualstudio.com/solutions/1171966/view.html

**Comment by jonsamwell** [comment]
@maxim-lobanov many thanks for this, I have it working now.
