### ISSUE TITLE
Add PowerShell Module Invoke-Build

### ISSUE THREAD

**Issue by Persistent13** [actions/virtual-environments#1548]
**Tool information**
- Tool name: Invoke-Build
- Tool license: Apache 2.0
- Add or update? Add
- Desired version: Latest (5.6.1 at time of issue creation)
- Approximate size: 144KB
- If this is an add request:
  - Brief description of tool: Invoke-Build is a build and test automation tool which invokes tasks defined in PowerShell scripts.
  - URL for tool's homepage: https://github.com/nightroman/Invoke-Build
  - Provide a basic test case to validate the tool's functionality:

This assumes that Invoke-Build is already installed.

Place this script content in a file named `.build.ps1`
```powershell
task . {
    Write-Output 'Hello from the default task!'
}
```
and then from the same directory as the .build.ps1 script
```powershell
Invoke-Build
```
You should expect result like so
```powershell
Build . /path/to/your/.build.ps1
Task /.
Hello from the default task!
Done /. 00:00:00.0301340
Build succeeded. 1 tasks, 0 errors, 0 warnings 00:00:00.1247932
```

**Area for Triage**:
Scripting and command line

**Question, Bug, or Feature?**:
"Feature"

**Virtual environments affected**
- [x] macOS 10.15
- [x] Ubuntu 16.04 LTS
- [x] Ubuntu 18.04 LTS
- [x] Ubuntu 20.04 LTS
- [x] Windows Server 2016 R2
- [x] Windows Server 2019

Since it's a PowerShell module that is platform agnostic, it can be run on all images that contain PowerShell.

**Can this tool be installed during the build?**
Yes, using PowerShell as the shell `Install-Module -Name invokebuild -Force -RequiredVersion 5.6.1`

**Tool installation time in runtime**
Less than a minute.

**Are you willing to submit a PR?**
Yes.

**Comment by maxim-lobanov** [comment]
Hello @Persistent13 , thank you for your proposal.
Considering the fact that this module can be installed in runtime very quick (8-15 seconds), we wouldn't like to bake it into the image this time.
