### ISSUE TITLE
Two different kinds of build agent are in use

### ISSUE THREAD

**Issue by MatthewSteeples** [actions/virtual-environments#1549]
**Description**  
There are (at least) 2 different kinds of build agent provided by hosted pipelines, and they seem to be configured differently but only very slightly. Most builds don't seem to produce a noticeable difference.

The way to tell which kind you're on is whether it's the agent name is `fv-az8` or whether it beings `WIN-`. They look to be running different CPUs (although both are listed under the [Dv2](https://docs.microsoft.com/en-us/azure/virtual-machines/dv2-dsv2-series) page), and fv-az8 also emulates a CD drive (see attached Powershell outputs)

There are also differences in the way that the information output in the "Initialize job" step is rendered

**Area for Triage**:  
Servers

**Question, Bug, or Feature?**:  
Question

**Virtual environments affected**  
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Ubuntu 20.04 LTS
- [ ] Windows Server 2016 R2
- [X] Windows Server 2019

**Expected behavior**  
The same build inputs will produce the same build outputs when the version of the agent remains the same

**Actual behavior**  
The build results are different when run on different agents

**Repro steps**  
I'm unable to reproduce the build running on different agents on demand (I'm assuming it's based on how busy the system is and what machines are available), but I've attached some logs demonstrating the output from each.

[fv-az8 Powershell Info.txt](https://github.com/actions/virtual-environments/files/5179763/fv-az8.Powershell.Info.txt)
[win Powershell Info.txt](https://github.com/actions/virtual-environments/files/5179765/win.Powershell.Info.txt)

[fv-az8 Initialize Job.txt](https://github.com/actions/virtual-environments/files/5179766/fv-az8.Initialize.Job.txt)
[win Initialize Job.txt](https://github.com/actions/virtual-environments/files/5179764/win.Initialize.Job.txt)

**Question**
Is this to be expected? Is it possible for the reason for this to be given?

Thanks

**Comment by miketimofeev** [comment]
Hi @MatthewSteeples!
Yes, this is expected, the difference is in the virtualization methods, but everything else is similar(the same VM image with the same software)

**Comment by miketimofeev** [comment]
I'm going to close the issue. Feel free to create a new one if you have more questions.
Thank you!

**Comment by MatthewSteeples** [comment]
Our CI build on `win-*` agents takes approximately 23 minutes, whereas our build on `fv-az*` images takes 16 minutes. Is this kind of difference to be expected as well?

**Comment by miketimofeev** [comment]
@MatthewSteeples there can be some difference in performance between two agent types. We are working on eliminating the difference, but no ETA for now.

**Comment by MatthewSteeples** [comment]
Just to follow on from this, this is causing us problems in multi stage pipelines because things get executed out of order. Our pipeline is set up as:
Build, Unit Test, {Deploy to test environment, UI tests}, {Deploy to beta environment} etc

The bit in Angle brackets is set up so that there is an Exclusive :ock for the step, and that ensures that "only the latest" is deployed. The problem we have is when 2 builds are queued up, build number 1 takes 25 minutes to perform the first step but then build number 2 does it in 15 minutes (because of the faster hardware). Build number 2 deploys to test environment and runs the UI tests, _and then_ build number 1 does.

Even though it's an earlier build, the step was started later so it breaks the logic of "only the latest" and we end up with an earlier build on our servers
