### ISSUE TITLE
How to revert Visual Studio to 16.3

### ISSUE THREAD

**Issue by ThadHouse** [actions/virtual-environments#155]
**Describe the bug**

Visual Studio 16.4 has some nasty bugs related to codegen, causing our environment to completely break. 

https://developercommunity.visualstudio.com/content/problem/843918/wrong-code-generation-in-1640.html

https://developercommunity.visualstudio.com/content/problem/844870/bad-codegen-after-update-to-vc-2019-1640.html

https://developercommunity.visualstudio.com/content/problem/842917/error-c3538-when-using-scoped-lock-in-derived-temp.html

The last one we can work around, but the first 2 are completely broken with no workarounds. There should be an option to revert to prior VS versions if major bugs like this occur.

**Virtual environments affected**
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [x] Windows Server 2019

**Comment by ThadHouse** [comment]
I realized this was the wrong repo. I moved it to the correct repo https://github.com/microsoft/azure-pipelines-image-generation/issues/1450

**Comment by kaylangan** [comment]
Currently, we do not have a way for you to revert to VS 16.3. We have some investigations on being able to re-run jobs on prior virtual environments, but I don't have a timeline to share at the moment.

**Comment by kaylangan** [comment]
Closing as this is currently as designed.
