### ISSUE TITLE
Maven packages works on local but fails in workflow

### ISSUE THREAD

**Issue by BrightRan** [actions/virtual-environments#1554]
Associated GitHub Community case: https://github.community/t/works-locally-but-on-github-actions-build-cant-transfer-own-github-hosted-parent-pom-receives-bad-request-and-parent-relativepath-points-at-wrong-local-pom/130983

The customer has a project that he wants to build with Maven packages. See the repository [here](https://github.com/joergi/basics).

When he tries to build the project with the Maven packages in the workflow, the workflow always returns the following error:
> [FATAL] Non-resolvable parent POM for io.joergi:basic-user:0.0.1-SNAPSHOT: Could not transfer artifact io.joergi:parent-jdk11-mongo:pom:2.3.3-5.RELEASE from/to github (https://maven.pkg.github.com/joergi/parent-jdk11-mongo): Transfer failed for https://maven.pkg.github.com/joergi/parent-jdk11-mongo/io/joergi/parent-jdk11-mongo/2.3.3-5.RELEASE/parent-jdk11-mongo-2.3.3-5.RELEASE.pom 400 Bad Request and 'parent.relativePath' points at wrong local POM @ line 6, column 10

The customer tried the project on his local machine, it could work fine.

**Comment by miketimofeev** [comment]
Hi @BrightRan @joergi!
It doesn't look like an issue with the VM image. I've found the following community discussions about the same error. Could you please take a look if it helps?
https://github.community/t/github-package-registry-as-maven-repo-trouble-uploading-artifact/14226/37
https://github.community/t/error-on-github-packages-for-snapshot-maven-artifacts-with-a-classifier/116732/5

**Comment by miketimofeev** [comment]
I'm going to close the issue since it's not related to the image.
@BrightRan @joergi feel free to contact us if you have any concerns.
Thank you!
