### ISSUE TITLE
Update/Add terraform to 0.13.2

### ISSUE THREAD

**Issue by larsmaes** [actions/virtual-environments#1559]
**Tool information**
- Tool name: terraform
- Add or update? update
- Desired version: 0.13.2 (Or at least higher than 0.13.1)

**Virtual environments affected**
- [X] macOS 10.15
- [X] Ubuntu 16.04 LTS
- [X] Ubuntu 18.04 LTS
- [X] Ubuntu 20.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

Terraform 0.13.1 contains a serious bug which causes al our pipelines to crash.

**Comment by maxim-lobanov** [comment]
Hello @larsmaes , we install the latest version of terraform on every image-generation. We will start deployment of new image today and terraform 0.31.2 will be included.
As for the macOS, we don't have Terraform installed on MacOS right now

**Comment by maxim-lobanov** [comment]
@larsmaes , as a workaround, I suggest consider using of [HashiCorp - Setup Terraform](https://github.com/marketplace/actions/hashicorp-setup-terraform) action. It would allow to install specific version of terraform in runtime very quick

**Comment by larsmaes** [comment]
> @larsmaes , as a workaround, I suggest consider using of [HashiCorp - Setup Terraform](https://github.com/marketplace/actions/hashicorp-setup-terraform) action. It would allow to install specific version of terraform in runtime very quick

Thanks! We did this for some mission critical pipelines

**Comment by judgewest2000** [comment]
Depending on how you are using terraform - we are calling it from a powershell script or bash shell, both from a linux vm.

If you add a step to your yaml you can download whichever version of terraform you wish, and it just needs to be available in an executable path...

    steps:
    - task: terraformdownload@0
      inputs:
        cwd: '/home/linuxbrew/.linuxbrew/bin'
        tfversion: '0.13.2'

The /home/linuxbrew/.linuxbrew/bin directory is in the $Env:PATH / $PATH environmental variable.

**Comment by miketimofeev** [comment]
@larsmaes Ubuntu images with terraform 0.13.2 were deployed. I'm going to close the issue but feel free to reopen it if you have any concerns.
Thank you!
