### ISSUE TITLE
Add Edge browser and driver versions for 85.0.564.44

### ISSUE THREAD

**Issue by bgoggan** [actions/virtual-environments#1564]
Is it possible to update the edge browser and drivers on the windows 2019 azure hosted environment? I see both the existing and the one marked pre-release are still on v84. v85 appears to be the current version being installed with new Edge browser installs.

**Comment by miketimofeev** [comment]
Hi @bgoggan!
Edge version will be updated automatically during next week's windows deployments.
macOS image with edge 85.0.564.44 is being deployed at the moment, the update is supposed to be finished in a few hours.
As a temporary workaround you can use the following steps:
Windows:
`choco upgrade microsoft-edge`
macOS:
`brew upgrade microsoft-edge`

**Comment by bgoggan** [comment]
@miketimofeev that sounds great. Thanks for the update.

**Comment by bgoggan** [comment]
@miketimofeev thanks for the additional info but I actually download and keep the edge drivers contained as part of my test project so once I added the command to update the existing browser they ran as expected.

**Comment by miketimofeev** [comment]
@bgoggan The new image with Edge 85.0.564.51 has finally deployed.
I'm going to close the issue, please feel free to contact us if you have any concerns.
Thank you!

**Comment by bgoggan** [comment]
@miketimofeev Thanks, I'll remove the update from my release.
