### ISSUE TITLE
homebrew folder owned by wrong user + dirty checkouts

### ISSUE THREAD

**Issue by andreineculau** [actions/virtual-environments#1568]
**Description**  

`/home/linuxbrew/.linuxbrew/Homebrew` and
`/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew-core` are initially owned by runneradmin:runneradmin (the user that is bootstrapping the image by running the homebrew installer).

Later on in a workflow, if the user calls `brew install/update`, some of those folders will start to be owned by runner:docker.

The problem is that the new files will NOT be `chmod o+w` as it is happening in https://github.com/actions/virtual-environments/blob/bb03b541e0a63c964dcf851817585d4bb4b38675/images/linux/scripts/installers/homebrew.sh#L16-L17

and from there on issues arise.

**Area for Triage**:  
Servers

**Question, Bug, or Feature?**:  
Bug

**Virtual environments affected**  
- [ ] macOS 10.15
- [x] Ubuntu 16.04 LTS
- [x] Ubuntu 18.04 LTS
- [x] Ubuntu 20.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Expected behavior**  

I expect `brew doctor` to be clean, rather than complain about a dirty repos (brew and homebrew-core) due to permissions.

**Actual behavior**  

`brew doctor` reports dirty repos and the homebrew files are owned by 2 owners with various permissions.

**Repro steps**  

```
    steps:
      - shell: bash
        run: |
          set -x
          ls -la $(brew --prefix)/Homebrew
          ls -la $(brew --prefix)/Homebrew
          which brew
          brew config
          brew doctor || true
          cd $(brew --prefix)/Homebrew && git diff && cd -
          cd $(brew --prefix)/Homebrew/Library/Taps/homebrew/homebrew-core && git diff && cd -
          brew install exiftool
          ls -la $(brew --prefix)/Homebrew
          ls -la $(brew --prefix)/Homebrew
          exit 1
```

I believe the right fix is to do a `chown -R runner:docker $HOMEBREW_PREFIX` and leave the permissions intact, and thus make it convenient for the workflows to run `brew install/update`, otherwise they would need to run those commands as the runneradmin:runneradmin user (which is implementation detail TBH, which many wouldn't care for).

**Comment by miketimofeev** [comment]
Hi @andreineculau!
Am I right that to get rid of "dirty" status we need to remove this as well as add `chown -R runner:docker $HOMEBREW_PREFIX`
https://github.com/actions/virtual-environments/blob/bb03b541e0a63c964dcf851817585d4bb4b38675/images/linux/scripts/installers/homebrew.sh#L16-L17
Just chown to runner doesn't look like enough

**Comment by andreineculau** [comment]
@miketimofeev yup, you are right. https://github.com/rokmoln/support-firecloud/commit/94a50a28d5987ce067a41a2eec066471f83a23fd

**Comment by andreineculau** [comment]
I realized that my answer is slightly inaccurate in relation to your question.

git doesn't record ownership, so running `chown -R runner:docker` is not to get rid of some dirty status in git, but to actually make it possible to run `brew` as runner:docker. Without `chown`, you need to run `brew` only as runneradmin:runneradmin.

**Comment by miketimofeev** [comment]
@andreineculau we've implemented a fix with `chown -R runner:docker /home/linuxbrew/` in VM provisioning scripts. The fix will be available next week. Then I suppose we will be able to get rid of this line as well https://github.com/actions/virtual-environments/blob/bb03b541e0a63c964dcf851817585d4bb4b38675/images/linux/scripts/installers/homebrew.sh#L16-L17

**Comment by miketimofeev** [comment]
@andreineculau sorry for the delay, we've finally fixed the permissions and the user is "runner" now. Could you please check it? If everything is fine the next step will be ` sudo chmod -R o+w $HOMEBREW_PREFIX ` removal

**Comment by andreineculau** [comment]
@miketimofeev np. Indeed it looks like the owner is "runner" now 👏  https://github.com/rokmoln/support-firecloud/runs/1291173510?check_suite_focus=true#step:2:7453

**Comment by miketimofeev** [comment]
It turned out we change permissions for the whole /home directory during VM provisioning process and thus brew is made dirty. We'll fix internal provisioning scripts to avoid changing permissions.

**Comment by miketimofeev** [comment]
@andreineculau we've finally deployed all the changes and brew version is clean now!
```
Run brew --version
Homebrew 2.6.1
Homebrew/linuxbrew-core (git revision 07337; last commit 2020-12-10)
```

I'm going to close the issue but please feel free to contact us if you have any concerns.
Thank you!

**Comment by andreineculau** [comment]
Thank **you**!
