### ISSUE TITLE
Windows drivers cannot be built because WDK VSIX is not installed

### ISSUE THREAD

**Issue by hansmbakker** [actions/virtual-environments#157]
**Describe the bug**
The Windows Driver Kit is installed, but the VSIX extension is not:

https://github.com/actions/virtual-environments/blob/51d02f26f42e53bb963bb6bc9754501b28a3d2ba/images/win/scripts/Installers/Windows2019/Install-WDK.ps1#L34

Therefore, driver projects cannot be build because the necessary build targets are missing. This leads to build errors.

**Possible fix?**
@christopherco made a PR here https://github.com/microsoft/azure-pipelines-image-generation/pull/1437

**Virtual environments affected**
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [x] Windows Server 2019

**Expected behavior**
WDK projects can be built

**Actual behavior**
Builds fail with errors like

```
Error MSB8020: The build tools for WindowsUserModeDriver10.0 (Platform Toolset = 'WindowsUserModeDriver10.0') cannot be found. To build using the WindowsUserModeDriver10.0 build tools, please install WindowsUserModeDriver10.0 build tools.  Alternatively, you may upgrade to the current Visual Studio tools by selecting the Project menu or right-click the solution, and then selecting "Retarget solution".
```

**Comment by hansmbakker** [comment]
Thank you!

**Comment by hansmbakker** [comment]
@alepauly when will we be able to use the new images based on this change in Azure Pipelines?

**Comment by alepauly** [comment]
> 
> 
> @alepauly when will we be able to use the new images based on this change in Azure Pipelines?

@hansmbakker right now we are in a deployment freeze due to US holidays. The new images should start reaching customers on Monday 1/6/2020, all accounts should see the new images by the end of that week (Friday 1/10/2020)

**Comment by hansmbakker** [comment]
That’s clear, thank you!

**Comment by alepauly** [comment]
@hansmbakker just a quick update to confirm that the images are rolling out now and we are still on track to have them on all accounts by Friday. I would appreciate if you can confirm once you see it working or by Monday let me know if there are still issues. Thanks!

**Comment by hansmbakker** [comment]
@alepauly thank you for letting me know! This week I won't be able to investigate though, hopefully next week.
