### ISSUE TITLE
Downloads from sourceforge mirror fail

### ISSUE THREAD

**Issue by mmuffins** [actions/virtual-environments#1571]
**Description**  
I just tried to build the latest win2019 server release, but the packer build failed because [Install-JavaTools.ps1](https://github.com/actions/virtual-environments/blob/ffc156448efefc9ac8ad7eb9a420f3850b3d9485/images/win/scripts/Installers/Install-JavaTools.ps1#L122) tried to download cobertura from a direct sourceforge mirror which wasn't available.
Updating the download server `ayera.dl.sourceforge.net` to `downloads.sourceforge.net` locally fixed the build. Is it intentional that the script points to that specific server or is it fine to update the location?

**Area for Triage**:  

**Question, Bug, or Feature?**:  
Question

**Virtual environments affected**  
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Ubuntu 20.04 LTS
- [ ] Windows Server 2016 R2
- [x] Windows Server 2019

**Expected behavior**  
Cobertura is downloaded from a valid mirror.

**Actual behavior**  
The download was attempted from a mirror that was unavailable, failing the build

**Repro steps**

**Comment by mmuffins** [comment]
Nevermind, I just saw that other scripts use the regular downloads.sourceforge.net location, so it doesn't look like there is anything special about that download server. I'll post a PR to update the link.

**Comment by krokofant** [comment]
How did you try it locally? To me it looks like the link with `downloads.sourceforge.net` redirects to the download but it's not a direct link.

Maybe replace `ayera` with `master`? Seems like that works as a direct link.
```
https://master.dl.sourceforge.net/project/cobertura/cobertura/2.1.1/cobertura-2.1.1-bin.zip
```

**Comment by mmuffins** [comment]
The full link I used was `https://downloads.sourceforge.net/project/cobertura/cobertura/2.1.1/cobertura-2.1.1-bin.zip`, which worked fine during the packer build. The same location is already used in [Install-NSIS.ps1](https://github.com/actions/virtual-environments/blob/main/images/win/scripts/Installers/Install-NSIS.ps1).

**Comment by maxim-lobanov** [comment]
Issue was fixed in `main` branch
