### ISSUE TITLE
Update miniconda on Windows from 4.6.14 to 4.8.3

### ISSUE THREAD

**Issue by weiji14** [actions/virtual-environments#1580]
**Tool information**
- Tool name: [Miniconda](https://docs.conda.io/en/latest/miniconda.html)
- Tool license: BSD 3-Clause License
- Add or update? Update
- Desired version: 4.8.3
- Approximate size: 54.1MB
- If this is an add request:
  - Brief description of tool: 
  - URL for tool's homepage: https://docs.conda.io/en/latest/miniconda.html#windows-installers
  - Provide a basic test case to validate the tool's functionality: 

**Area for Triage**:
Packages

**Question, Bug, or Feature?**:
Feature

**Virtual environments affected**
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Ubuntu 20.04 LTS
- [x] Windows Server 2016 R2
- [x] Windows Server 2019

**Can this tool be installed during the build?**

**Tool installation time in runtime**

**Are you willing to submit a PR?**
Yes, if someone can guide me a bit on where to start :smile:

These lines seem to suggest that Miniconda was pinned to 4.6.14 (released April 2019) for some reason, is that reason still valid?

https://github.com/actions/virtual-environments/blob/b47ba413c9bd9411407b8a5cf18e2c14ea8bda78/images/win/scripts/Installers/Install-Miniconda.ps1#L10-L15

xref https://github.com/conda-incubator/setup-miniconda/issues/58#issuecomment-687670999

**Comment by maxim-lobanov** [comment]
@weiji14 , no any reason to hardcode specific version. I think it may be upgraded to 4.8.3 or even `latest` (https://repo.anaconda.com/miniconda/Miniconda3-latest-Windows-x86_64.exe) to simplify future maintenance.
Do you want to submit PR?

**Comment by weiji14** [comment]
Sure, I'll give it a go :smile:

**Comment by maxim-lobanov** [comment]
Thank you for the PR,
we would like to get more context why 4.6.14 was hardcoded previously and I have pinged a few people. Hope it will take little time

**Comment by maxim-lobanov** [comment]
Hello @weiji14 , Sorry for delay.
Changes were merged and new image will be deployed in 1-2 weeks

**Comment by weiji14** [comment]
Awesome! Thanks for keeping on top of this, looking forward to the deployment!

**Comment by weiji14** [comment]
Changes appear to deployed, close this?

**Comment by maxim-lobanov** [comment]
Changes are still deploying (Some machines are already updated, some not). It should be finished today. After that we will close issue.
Everything works as expected for you?

**Comment by miketimofeev** [comment]
@weiji14 the images were deployed!
Miniconda version is 4.8.3
https://github.com/actions/virtual-environments/blob/main/images/win/Windows2019-Readme.md#database-tools
I'm going to close the issue, thank you for your contribution!
Please feel free to contact us if you have any concerns.
