### ISSUE TITLE
Add Tarpaulin

### ISSUE THREAD

**Issue by shff** [actions/virtual-environments#1587]
**Tool information**
- Tool name: cargo-tarpaulin
- Tool license: Apache License
- Add or update? Add
- Desired version: latest from crates.io
- Approximate size:
- If this is an add request:
  - Brief description of tool: Coverage measurement tool that is able to upload to coverage services 
  - URL for tool's homepage: https://github.com/xd009642/tarpaulin

**Area for Triage**:
Rust

**Question, Bug, or Feature?**:
Feature

**Virtual environments affected**
- [x] macOS 10.15
- [x] Ubuntu 16.04 LTS
- [x] Ubuntu 18.04 LTS
- [x] Ubuntu 20.04 LTS
- [x] Windows Server 2016 R2
- [x] Windows Server 2019

**Can this tool be installed during the build?**
yes

**Tool installation time in runtime**
0

**Are you willing to submit a PR?**
yes

**Comment by al-cheb** [comment]
Hello, @shff 
Thank you for proposal a new feature. Good news macOS 10.15 source code is now available in the `actions/virtual-environments` repository. Should we add  `cargo-tarpaulin` for macOS 10.15 to preserve consistence for all images?

**Comment by AlenaSviridenko** [comment]
Hi @shff, 
Thank you for contribution. We would like to track popularity of this feature request so we will keep it open for now.

In the meantime, I would suggest taking a look at the `actions/cache` action, it supports Cargo packages caching to decrease build time https://github.com/actions/cache.

**Comment by shff** [comment]
@al-cheb Oh, nice, this is new! Congrats on the release! I created a PR here: https://github.com/actions/virtual-environments/pull/1593 just in case!

@AlenaSviridenko Sounds fair to me! This tool seems like a perfect fit for Github Actions, so this is why I'm adding it! But let's see if more people need it. Thanks for the tip about actions/cache btw, I'll try in one of my repos!

**Comment by AlenaSviridenko** [comment]
Hi @shff,
based on community feedback, this package is not highly required as a pre-installed package, so we'd like not to add it on the images. I am going to close this issue. Please, feel free to open new one in case of any other questions.

Thanks!
