### ISSUE TITLE
Default Python will be switched to 3.8 on Ubuntu 20.04 on October, 6

### ISSUE THREAD

**Issue by maxim-lobanov** [actions/virtual-environments#1591]
Hello everyone!

Currently, Python 2.7 is set by default on Ubuntu 20.04. Python 2 was sunsetted on Jan 1 2020 and this version is not supported anymore. 
Clean Ubuntu 20.04 LTS [has Python 3 as default](https://wiki.ubuntu.com/FocalFossa/ReleaseNotes#Python3_by_default) so we would like to follow the same approach.

If you still need to use Python 2.x on Ubuntu 20.04, you will be able to switch Python to 2.7 using [actions/setup-python](https://github.com/actions/setup-python) and [UsePython](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/tool/use-python-version?view=azure-devops) tasks.

We are planning to deploy the new image with Python 3 as default on October, 6.

Regards,
Maxim

**Comment by rahulsaini** [comment]
@maxim-lobanov Does this also follow for Ubuntu embedded in Windows 10 or does Microsoft follow a separate path for that?

**Comment by maxim-lobanov** [comment]
@rahulsaini , This change will only affect image that you can choose by setting `ubuntu-20.04` image label in YAML file. 

> Ubuntu embedded in Windows 10

What Ubuntu version do you mean? Ubuntu that can be downloaded from store for WSL?

**Comment by rahulsaini** [comment]
yes, for WSL.

**Comment by maxim-lobanov** [comment]
@rahulsaini , We don't own those images so this change won't affect them.
This change will affect only `ubuntu-20.04` image label.

**Comment by bladeoner** [comment]
When will the Ubuntu 20.04 image with Python 3.8 be available?

Thanks in advance.

**Comment by bladeoner** [comment]
Hi there, when will the new image with Python 3.8 go live?

**Comment by maxim-lobanov** [comment]
@bladeoner , 3.8 is already in image for a long time: https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-README.md#python

**Comment by bladeoner** [comment]
How can I point to that image?

I'm using the following in my YML file:

jobs:
  build:
    name: ubuntu-20.04
    runs-on: ubuntu-20.04

Or do I need to define **container:** ?
The container command is already pointed to something else.

**Comment by maxim-lobanov** [comment]
@bladeoner No containers are needed. You should follow official documentation and examples: https://docs.github.com/en/free-pro-team@latest/actions/guides/building-and-testing-python#using-a-specific-python-version

**Comment by bladeoner** [comment]
@maxim-lobanov Thank you for your quick response and information I will dive into that.

**Comment by al-cheb** [comment]
The new Ubuntu 20.04 has been deployed with default Python3 and Python is alias -> Python3.
```
jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: default python
      run: |
         python --version
         python3 --version
```

![image](https://user-images.githubusercontent.com/47745270/95451441-72af2480-0970-11eb-858c-f4dda2299b69.png)
