### ISSUE TITLE
Set ANDROID_SDK_ROOT in addition to ANDROID_HOME on macOS

### ISSUE THREAD

**Issue by jhasse** [actions/virtual-environments#1596]
**Description**  
`ANDROID_HOME` is deprecated in favor of ANDROID_SDK_ROOT: https://developer.android.com/studio/command-line/variables

**Area for Triage**:  
Android

**Question, Bug, or Feature?**:  
Feature

**Virtual environments affected**  
- [x] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Ubuntu 20.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Expected behavior**  
`ANDROID_SDK_ROOT` is set to the same value as `ANDROID_HOME`.

**Actual behavior**  
Only `ANDROID_HOME` is set.

**Comment by maxim-lobanov** [comment]
@jhasse does it make sense to add this variable to Windows images too? Looks like currently it exists only on Ubuntu

**Comment by jhasse** [comment]
Yes, I think so.

**Comment by dmitry-shibanov** [comment]
Hello, pull requests were merged. Changes will be added in the next images rollout.

**Comment by dmitry-shibanov** [comment]
Hello, changes were added to images. If you have any concerns feel free to reopen the issue.
