### ISSUE TITLE
Add LLVM to Windows Server 2019

### ISSUE THREAD

**Issue by kaylangan** [actions/virtual-environments#16]
**Tool information**
- Tool name: LLVM
- Add or update? Add
- Desired version: 
- Approximate size: 
- If this is an add request:
  - Brief description of tool: So we can use clang on windows without downloading any dependencies
  - URL for tool's homepage: 

**Virtual environments affected**
- [ ] macOS 10.14
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [x] Windows Server 2019

**Can this tool be installed during the build?**

**Are you willing to submit a PR?**
Just need to add to the Visual Studio installation:
- `Microsoft.VisualStudio.Component.VC.Llvm.Clang` (C++Compiler Clang for Windows (version8.0.1))
- `Microsoft.VisualStudio.Component.VC.Llvm.ClangToolset` (C++ Clang-cl for v142 Build Tools (x64/x86))

**Comment by kaylangan** [comment]
We're currently working on adding this and it should be available in an upcoming deployment.

**Comment by Milerius** [comment]
Thanks

**Comment by kaylangan** [comment]
We've completed the work to add LLVM to the Windows Server 2019 image. It will roll out in an upcoming deployment.

**Comment by Milerius** [comment]
Great very cool !

**Comment by kaylangan** [comment]
This has been fully deployed.

**Comment by stevencpp** [comment]
Could the documentation in https://help.github.com/en/actions/automating-your-workflow-with-github-actions/software-installed-on-github-hosted-runners be updated to reflect this ?

**Comment by kaylangan** [comment]
@stevencpp I think it's there as `Microsoft.VisualStudio.Component.VC.Llvm.ClangToolset` and `Microsoft.VisualStudio.ComponentGroup.NativeDesktop.Llvm.Clang` under the Visual Studio 2019 description.

**Comment by stevencpp** [comment]
Sorry, I missed the last line of the first post. I thought this was about installing it to `C:\Program Files\LLVM`. I believe the one that comes with VS is 8.0 though ? In my case I need 9.0, so I still need to install it.

**Comment by Milerius** [comment]
@stevencpp You can use scoop for that.

**Comment by stevencpp** [comment]
Yeah I used chocolatey and it worked, just figured I wouldn't need it anymore. Is scoop any faster ? Chocolatey seems to take a long time seemingly not doing much.

**Comment by Milerius** [comment]
scoop is really fast..., check my build.yml in Antara-gaming-sdk repo if you want an example of dl clang 9 with scoop

**Comment by Milerius** [comment]
https://github.com/KomodoPlatform/antara-gaming-sdk/blob/master/.github/workflows/build.yml#L161

**Comment by tommywalkie** [comment]
@kaylangan Does this LLVM instance provide a `llvm-config.exe` executable ? In my use case, all I need is this executable path. Tried installing `llvm` via scoop but it doesn't create any `llvm-config` shim because `llvm-config.exe` is not provided in LLVM prebuilt binaries.

**Comment by zufuliu** [comment]
Hope someone reopen this issue and pre-install latest official LLVM package available at https://github.com/llvm/llvm-project/releases

**Comment by miketimofeev** [comment]
@zufuliu could you please open a new issue with LLVM 10 request?

**Comment by zufuliu** [comment]
@miketimofeev opened #921

**Comment by seven-mile** [comment]
> @kaylangan Does this LLVM instance provide a `llvm-config.exe` executable ? In my use case, all I need is this executable path. Tried installing `llvm` via scoop but it doesn't create any `llvm-config` shim because `llvm-config.exe` is not provided in LLVM prebuilt binaries.

I'm also confused by this issue. What's your solution? I think I have to clone the repo and build it in the CI...
