### ISSUE TITLE
Add DTC

### ISSUE THREAD

**Issue by TheNotOnly** [actions/virtual-environments#160]
**Tool information**
- Tool name: dtc
- Add or update? Add
- Desired version: DTC 1.4.7
- Approximate size:
- If this is an add request:
  - Brief description of tool: Used during android kernel compilation
  - URL for tool's homepage: Available as a package for ubuntu

**Virtual environments affected**
- [ ] macOS 10.15
- [ x] Ubuntu 16.04 LTS
- [ x] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Can this tool be installed during the build?**
No, need root access to install
sudo apt install device-tree-compiler

**Are you willing to submit a PR?**

**Comment by maxim-lobanov** [comment]
The tool can be installed in runtime using the following scripts:
```
sudo apt install device-tree-compiler
```
Installation takes about 7 seconds

**Comment by alepauly** [comment]
@TheNotOnly Considering this is a quick install during build, we won't bake it into the virtual-environments image. Thanks for the suggestion.
