### ISSUE TITLE
Add GCC 10.x

### ISSUE THREAD

**Issue by timangus** [actions/virtual-environments#1604]
**Tool information**
- Tool name: GCC
- Tool license: GPL
- Add or update? Add
- Desired version: 10.2
- Approximate size: 
- If this is an add request:
  - Brief description of tool: GCC is a well known collection of compilers
  - URL for tool's homepage: https://gcc.gnu.org/
  - Provide a basic test case to validate the tool's functionality: 

**Area for Triage**: C/C++

**Question, Bug, or Feature?**: Feature

**Virtual environments affected**
- [ ] macOS 10.15
- [x] Ubuntu 16.04 LTS
- [x] Ubuntu 18.04 LTS
- [x] Ubuntu 20.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Can this tool be installed during the build?**
Potentially from PPAs, at least in the case of 18.04 and 20.04.

**Tool installation time in runtime**
Unknown.

**Are you willing to submit a PR?**
Wouldn't know where to start, to be honest.

**Comment by maxim-lobanov** [comment]
Hello! @timangus , thank you for feature request. We don't have objections to pre-install GCC to images.
If you would like to contribute, we just need to update this file: https://github.com/actions/virtual-environments/blob/main/images/linux/scripts/installers/gcc.sh#L29

**Comment by al-cheb** [comment]
@timangus , gcc-10 is now available for Ubuntu 18.04/20.04. The Ubuntu 16.04 has not been updated due to unavailable gcc-10 pkg in ppa:ubuntu-toolchain-r/test repo .

**Comment by timangus** [comment]
I saw, thanks. Unfortunately for me I need to build on 16.04, but your efforts are nevertheless appreciated. I asked the ubuntu-toolchain maintainers if they would be willing to build GCC 10 for 16.04 a week or so ago, but so far no response.
