### ISSUE TITLE
Failed to merge PR: Resource not accessible by integration

### ISSUE THREAD

**Issue by BrightRan** [actions/virtual-environments#1609]
Associated GitHub Community ticket: https://github.community/t/how-to-auto-merge-pr-from-fork/132552

According to the introduction of the new feature "**Run workflows from fork pull requests**" (see [here](https://github.blog/2020-08-03-github-actions-improvements-for-fork-and-pull-request-workflows/)), if enable the option "**Send write tokens to workflows from fork pull requests.**", the workflows from the fork pull requests can gain the tokens (**GITHUB_TOKEN**) that have the '**write**' permissions. With the '**write**' permissions, the workflow should can merge the fork pull requests. But, it does not work.
![settings](https://user-images.githubusercontent.com/46307996/93435998-c93ebb00-f8fc-11ea-9e88-a88701f598ef.PNG)

When trying to use an action ([pascalgn/automerge-action](https://github.com/pascalgn/automerge-action)) that wraps the "[**Merge a pull request**](https://docs.github.com/en/rest/reference/pulls#merge-a-pull-request)" API to auto-merge the PR from the fork repository to the main repository. But the action always failed to merge the PR and returned the message "**Resource not accessible by integration**".

I also tried other similar actions that wrap the "**Merge a pull request**" API, get the same error message "**Resource not accessible by integration**".
I directly run the "**Merge a pull request**" API in the workflow, get the same error message "**Resource not accessible by integration**".

Obviously, the new feature "**Run workflows from fork pull requests**" does not work as designed. This seems is a bug for this feature.

If I post this issue in the wrong repository, please help transfer to the right repository, thanks.

**Comment by maxim-lobanov** [comment]
Hello @BrightRan !
I think it is incorrect repo for this issue. In this repository, we owns only Hosted runners and their software.
I am not sure that we have public repo where we can address this issue, may be @alepauly can help us to redirect it?

**Comment by jclem** [comment]
We can close this issue—it was in reference to a public repository, for which "Run workflows from fork pull requests" is never enabled, because it would allow anyone that forks the public repository to access secrets and gain write access to the repository.

**Comment by prclqz90** [comment]
> We can close this issue—it was in reference to a public repository, for which "Run workflows from fork pull requests" is never enabled, because it would allow anyone that forks the public repository to access secrets and gain write access to the repository.

It's definitely an concern if forks can get access through this. Do you have any solution? Or this feature will only work for non-fork repos?
