### ISSUE TITLE
Update GitHub cli to 1.0.0

### ISSUE THREAD

**Issue by Trim21** [actions/virtual-environments#1610]
**Tool information**
- Tool name: GitHub cli (gh)
- Tool license: mit
- Add or update? update
- Desired version: 1.0.0 (latest at 2020.9.17)
- Approximate size: 5mb

**Area for Triage**:

**Question, Bug, or Feature?**: Feature" 

**Virtual environments affected**
- [X] macOS 10.15
- [X] Ubuntu 16.04 LTS
- [X] Ubuntu 18.04 LTS
- [X] Ubuntu 20.04 LTS
- [X] Windows Server 2016 R2
- [X] Windows Server 2019

**Can this tool be installed during the build?**

https://github.com/cli/cli#installation

**Tool installation time in runtime**
 5 min

**Are you willing to submit a PR?**

Yes

**Comment by mislav** [comment]
It looks like github cli installer scripts for Linux and Windows all fetch the latest stable release. If so, then I don't think any specific steps need to be done to upgrade gh inside VM images— the version will be auto-upgraded every time the images get rebuilt.

**Comment by Trim21** [comment]
A. I didn't notice that there is a automatic script doing this. I'll close this issue and wait for the update.
