### ISSUE TITLE
Update version of - Git for Windows

### ISSUE THREAD

**Issue by leemacatangay** [actions/virtual-environments#1611]
**Tool information**
- Tool name: Git for Windows (with support for Virtual File System)
- Tool license: None specific
- Add or update? Update
- Desired version: Git-2.28.0.vfs.0.0-64-bit.exe (https://github.com/microsoft/VFSForGit/releases/download/v1.0.20210.1/Git-2.28.0.vfs.0.0-64-bit.exe)
- Approximate size: 

**Area for Triage**: Git

**Question, Bug, or Feature?**: Feature

**Virtual environments affected**
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Ubuntu 20.04 LTS
- [ ] Windows Server 2016 R2
- [ x ] Windows Server 2019

**Can this tool be installed during the build?**
No

**Tool installation time in runtime**
1 minute

**Are you willing to submit a PR?**
Yes

**Comment by maxim-lobanov** [comment]
Hello @leemacatangay , I see you also requested installation of GVFS in #1612. Could you please share some context around these tools?
As I understand, GVFS from #1612 is a separate tool but what is this one `Git-2.28.0.vfs.0.0-64-bit.exe`? Currently, we install Git For Windows from https://github.com/git-for-windows/git. Is it plugin or replacement?

cc: @dscho

**Comment by dscho** [comment]
That would be the replacement installer, but it's not enough for GVFS... there is another component: https://github.com/microsoft/vfsforgit/releases (which includes the VFS for Git-specific Git fork AFAIR).

Taking a step back, I'm not actually sure that it makes sense to include VFS for Git; it requires a kernel driver...

**Comment by leemacatangay** [comment]
Yes, that would be a replacement installer of 2.28 to include support for GVFS.
Then, GVFS component is brought in by another installer. Please see if this can be applied, and if there is installer in Git for Windows that also include support for GVFS.

Thanks,
/ee

**Comment by AlenaSviridenko** [comment]
Hi @leemacatangay,
unfortunately, we cannot add these tools to the image, because Git for Windows is a commonly used tool and its replacement can lead to an unpredictable impact. 
Current Git for Windows https://github.com/git-for-windows/git doesn't have a support for GVFS, as I understand. @dscho please, correct me if I am wrong.

I am closing this issue, please, feel free to open a new one for any other questions.
Thanks!

**Comment by dscho** [comment]
I agree that it makes more sense to support regular Git out of the box, and not force VFS for Git on every Azure Pipeline/GitHub Action user.

The best way to use VFS for Git in CI, from my perspective, is to set up your own VMs and install build agents on them.

**Comment by leemacatangay** [comment]
Thanks for reviewing.

Thanks,
/ee

________________________________
