### ISSUE TITLE
Add SetupGVFS.1.0.20210.1.exe

### ISSUE THREAD

**Issue by leemacatangay** [actions/virtual-environments#1612]
**Tool information**
- Tool name: Virtual file system for Git
- Tool license: None specific
- Add or update? Add
- Desired version: SetupGVFS.1.0.20210.1.exe (https://github.com/microsoft/VFSForGit/releases/download/v1.0.20210.1/SetupGVFS.1.0.20210.1.exe)
- Approximate size: 5.4mb
- If this is an add request:
  - Brief description of tool: Adds Git support for virtual file system
  - URL for tool's homepage: https://github.com/microsoft/VFSForGit/releases/tag/v1.0.20210.1
  - Provide a basic test case to validate the tool's functionality: 
#1 gfvs clone <https repository url>
#1 result - repository clone should succeed, src folder is available in local workspace, size of local workspace folder is in KBs/MBs
#2 gfvs unmount
#2 result - repository should be unmounted, src folder is empty or not found

**Area for Triage**: Git

**Question, Bug, or Feature?**: Feature

**Virtual environments affected**
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Ubuntu 20.04 LTS
- [ ] Windows Server 2016 R2
- [ x ] Windows Server 2019

**Can this tool be installed during the build?**
No

**Tool installation time in runtime**
1 minute

**Are you willing to submit a PR?**
Yes

**Comment by AlenaSviridenko** [comment]
Closing this one as it is a plugin for https://github.com/actions/virtual-environments/issues/1611 that we won't install on the images.
Thank you.
