### ISSUE TITLE
Windows-latest image does not support `cc` command or $(CC) variable in Makefiles

### ISSUE THREAD

**Issue by simonbyrne** [actions/virtual-environments#1613]
**Description**  
On the `windows-latest` image, attempting to use the default `$(CC)` command in a Makefile (which resolves to the `cc` command), results in an error.

**Area for Triage**:  
C/C++

**Question, Bug, or Feature?**:  
Bug

**Virtual environments affected**  
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Ubuntu 20.04 LTS
- [x] Windows Server 2016 R2 (I assume?)
- [x] Windows Server 2019

**Expected behavior**  
C compiler to work

**Actual behavior**  
```
/usr/bin/bash: cc: command not found
```
https://github.com/simonbyrne/cg/runs/1106611718#step:5:12

**Repro steps**  
1. Create a `Makefile` that uses the automatic `$(CC)` variable, e.g.
```
version:
	$(CC) --version
```

2. run `make version`.

**Comment by andy-mishechkin** [comment]
Hello, @simonbyrne 
When you use bash in Windows, the GitHub bash is using by default (https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#using-a-specific-shell), which has no cc installed.
Windows image also contains the MSYS2 bash, which has cc inside.
For using cc from MSYS2 bash, you can add the directory of this shell to PATH variable in previous step.
Please specify the next step before your make (win) step:
```
- name: Add Msys64 to PATH
        if: matrix.os == 'windows-latest'
        run: echo "::add-path::/c/msys64/mingw64/bin:/c/msys64/usr/bin"
        shell: bash
```
after this you can use make without `CC=gcc` key
If you'll still get the same issue - feel free to ping me in this ticket
Thank you.

**Comment by eine** [comment]
Soon, `bash` will default to MSYS2. See #1648.

**Comment by simonbyrne** [comment]
Thanks @andy-mishechkin and @eine!
