### ISSUE TITLE
Docker container actions and service containers only work on 'ubuntu-latest'?

### ISSUE THREAD

**Issue by BrightRan** [actions/virtual-environments#1624]
Associated GitHub Community ticket: https://github.community/t/does-service-containers-only-work-with-ubuntu-latest/133246

We can see the following description from the docs (see [here](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idservices) and [here](https://docs.github.com/en/actions/guides/about-service-containers#about-service-containers)):
> **Note:** If your workflows use Docker container actions or service containers, then you must use a Linux runner:
> * If you are using GitHub-hosted runners, you must use the **ubuntu-latest** runner.
> * If you are using self-hosted runners, you must use a Linux machine as your runner and Docker must be installed.

However, according to our test with **`ubuntu-20.04`**, **`ubuntu-latest`** (**`ubuntu-18.04`**), and **`ubuntu-16.04`**, all of them can run Docker container actions and service containers.

Looks like, the description
> If you are using GitHub-hosted runners, you must use the **ubuntu-latest** runner.

is not accurate, and causing misunderstanding.
It should express clearly that all the GitHub-hosted Linux runners can run Docker container actions, service containers and job containers.

**Comment by mittalyashu** [comment]
Reference: https://github.community/t/does-service-containers-only-work-with-ubuntu-latest/133246?u=mittalyashu

**Comment by Darleev** [comment]
Hello @BrightRan @mittalyashu,
Thank you for the report.
It seems we are not able to assist you with the provided case, since we do not support github docs in out repository. I believe, [the following link](https://docs.github.com/en) "Contact support", should be the right way to find a correct team to handle the case.
If additional information or assistance is required, feel free to contact us.

**Comment by Darleev** [comment]
@BrightRan @mittalyashu, I will try to find a resposible person to handle the case and add the required changes in the documentation.
I will keep you posted.

**Comment by BrightRan** [comment]
Thanks for your help, @Darleev .
