### ISSUE TITLE
Missing requirements in instructions

### ISSUE THREAD

**Issue by zaanposni** [actions/virtual-environments#1633]
**Description**  
For [GenerateResourcesAndImage.ps1](https://github.com/actions/virtual-environments/blob/main/helpers/GenerateResourcesAndImage.ps1) the `AzureRm` ps module is needed but that is not stated in the instructions.

**Expected behavior**  
I would like the documentation to be up to date and describing everything that has to be done.

**Note**
Is [this](https://github.com/actions/virtual-environments/blob/main/help/CreateImageAndAzureResources.md) the instruction one should refer to?
If my assumption with the incomplete requirements is correct, I would like to open a Pull request and correct the documentation.
I would just like to validate if I missed something.

Another potential fix would be to update the `GenerateResourcesAndImage.ps1` script to use the new `Azure` ps module or using the (already linked) `az` module that is already used in [CreateAzureVMFromPackerTemplate.ps1](https://github.com/actions/virtual-environments/blob/main/helpers/CreateAzureVMFromPackerTemplate.ps1).

**Comment by maxim-lobanov** [comment]
@zaanposni , Thank you for pointing to it!
I think updating `GenerateResourcesAndImage.ps1` script to use `Azure` instead of `AzureRM` is better way to fix the issue.

**Comment by zaanposni** [comment]
Fair enough @maxim-lobanov 
I would like to work on the solution and the PR to fix this issue!
In most cases it should be enough to edit all invokes from `AzureRmSomething` to `AzSomething`.
But surely I will test this through.

**Comment by maxim-lobanov** [comment]
I have merged PR, thank you for contribution!
