### ISSUE TITLE
Rename Windows Packer Configuration Files

### ISSUE THREAD

**Issue by hutson** [actions/virtual-environments#1636]
**Description**  

Rename Windows Packer configuration files from `[OS][Release]-[Cloud].json` to `[OS][Release].json` and rely on the `builders` section to describe individual target platforms.

If necessary, `only` may be used at the `provisioner` level to restrict steps to specific target platforms.

**Area for Triage**:  

**Question, Bug, or Feature?**:  

Feature?

**Virtual environments affected**  
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Ubuntu 20.04 LTS
- [x] Windows Server 2016 R2
- [x] Windows Server 2019

**Comment by maxim-lobanov** [comment]
Actually, we support only Azure builders for now. But we don't have concerns to rename templates to avoid confusing

**Comment by hutson** [comment]
@maxim-lobanov I'm glad to hear! Yeah, my team is re-using the Azure configuration file, but with the addition of an `amazon-ebs` builder.

We don't anticipate the maintainers of this repository to own support for alternative target platforms, such as AWS, but based on comments in #671, I am hoping my team can help make it as easy as possible for downstream consumers to build on y'alls work in this repository.

For this issue, that just means a quick file rename that encourages downstream consumers, including ourselves, to re-use the same file for alternative target platforms by extending the `builders` list and using the `-only=[builder]` option to build for a specific target platform.
