### ISSUE TITLE
Add test signing support

### ISSUE THREAD

**Issue by jamesmistry** [actions/virtual-environments#1637]
**Tool information**
- Tool name: Test signing support
- Tool license: N/A
- Add or update? Config update
- Desired version: N/A
- Approximate size: 0
- If this is an add request:
  - Brief description of tool: Test signing allows the loading of test signed kernel drivers. Test signing can't be enabled using MS-hosted agents currently because the configuration change needs a reboot to take effect.
  - URL for tool's homepage: N/A
  - Provide a basic test case to validate the tool's functionality: 1. Build and test sign WDK driver. 2. Load the driver using devcon, pnputil or equivalent Windows APIs. If test signing is correctly enabled, the driver will successfully load.

**Area for Triage**:
C/C++

**Question, Bug, or Feature?**:
Feature

**Virtual environments affected**
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Ubuntu 20.04 LTS
- [X] Windows Server 2016 R2
- [ ] Windows Server 2019

Note: not tested on Server 2019

**Can this tool be installed during the build?**
No. This requires a reboot.

**Tool installation time in runtime**
Time of a reboot

**Are you willing to submit a PR?**
Yes

**Comment by Darleev** [comment]
Hello @jamesmistry,

We had a similar request in the past where we have discussed all points related to the feature. Please check it [by the link.](https://github.com/actions/virtual-environments/issues/1497).

Unfortunately, due to unpredictable impact, we are not able to add the feature at this time, but we will keep this request on mind and let you know if we have any updates.

In case of any questions, do not hesitate to contact us.

**Comment by nibanks** [comment]
I would like to request that this be reopened. Several MSFT Windows teams are open sourcing Windows drivers and are leveraging Azure Pipelines for the automation. Currently, with test signing disabled, this forces us to maintain custom, self-hosted agents/machines. With new restrictions on self-hosted agents being put in place we're even more reliant on the default pool machines.

To your comment above related to "unpredictable impact" would you care to elaborate? It's a sandbox environment, right? Anything that breaks is just thrown away anyways. IMO, this "unknown" should not be reason enough to block this feature.

**Comment by miketimofeev** [comment]
@nibanks are there any drawbacks of the "test-mode" besides the ones provided here?
https://docs.microsoft.com/en-us/windows-hardware/drivers/install/the-testsigning-boot-configuration-option#behavior-of-windows-when-loading-test-signed-code-is-enabled
![image](https://user-images.githubusercontent.com/48208649/133148707-6e199262-be1d-42e2-a687-f8da93910bd1.png)

**Comment by nibanks** [comment]
I'm not expert enough to be able to claim knowledge of all impacts of enabling test-signing, but generally all Windows testing uses it. Additionally, all our self-host machines always have it enabled and never have any problems. I would be surprised if any app development was affected unless it explicitly depended on test-signed drivers not being able to be loaded. I don't think that kind of behavior should block enabling of this. We should be able to use this for driver development.

**Comment by nibanks** [comment]
@miketimofeev so are you Ok with enabling test-signing?

**Comment by miketimofeev** [comment]
@nibanks let's give it a shot on windows-2022 first as it's in beta state at the moment anyway. If there are no complaints for some period of time we can consider enabling it on windows-2019 as well.

**Comment by nibanks** [comment]
Great! Sounds good. I'm most interested in the older builds, but I'm totally fine with starting with 2022.

BTW, I was thinking, you might want a new `Area: Drivers` label for things related to drivers and driver development. This and https://github.com/actions/virtual-environments/issues/3858, as well as all the "update WDK" issues would fall into that category.

**Comment by al-cheb** [comment]
Windows Server 2022 image with enabled Test signing mode has been deployed.

**Comment by nibanks** [comment]
@al-cheb WS2022 is just the first step. We need this on all Windows versions. My understanding was that we'd start with 2022, and if all goes well (after x weeks?) it'd be enabled for the rest. Can we keep this open until it's everywhere please? WS2022 can't even be used yet anyways because of a number of other issues.

**Comment by miketimofeev** [comment]
@nibanks let's get back to this in the mid of October. We will track if there is no complaints for win-2022 and then enable the mode on win-2019

**Comment by al-cheb** [comment]
@nibanks, Windows Server 2019 image with enabled Test signing mode has been deployed.
