### ISSUE TITLE
Update yamllint to be installed using pip

### ISSUE THREAD

**Issue by yvele** [actions/virtual-environments#1657]
**Tool information**

- Tool name: yamllint
- Tool license: GNU General Public License v3.0
- Add or update? Update
- Desired version: Latest
- Approximate size: 

**Area for Triage**:

Testing and code coverage

**Question, Bug, or Feature?**:

yamllint #1142 actually is installed using system packages see #1319 (Ubuntu) and #1320 (Windows).

But this doesn't give us the latest stable version of yamllint and is quite outdated.

We [talked](https://github.com/adrienverge/yamllint/issues/300#issuecomment-675351836) about that issue with the yamllint team and they suggested to use `pip` for the installation:

@adrienverge 

> I'm for using `pip`: even if someone dedicates time to actively maintain the deb package, it will always be late compared to the PyPi version (which is pushed a few seconds after a release is created).

**Virtual environments affected**
- [x] macOS 10.15
- [x] Ubuntu 16.04 LTS
- [x] Ubuntu 18.04 LTS
- [x] Ubuntu 20.04 LTS
- [x] Windows Server 2016 R2
- [x] Windows Server 2019

**Can this tool be installed during the build?**

```sh
pip install yamllint
```

**Tool installation time in runtime**

run in 23s on `ubuntu-latest`

**Are you willing to submit a PR?**

Yes (but I don't master Windows Server at all...)

**Comment by adrienverge** [comment]
For information, and to support this request: the current version installed (`.deb`) is not actively maintained, and is 19 releases behind the official `pip` one.

**Comment by maxim-lobanov** [comment]
@yvele , @adrienverge , thank you for raising this point.

Honestly, we are trying not install tools through `pip` because it often installs additional dependencies or can stop work properly after switching python using `actions/setup-python`.
(P.S: We are not Python experts so could be wrong but previously we had similar issues)

I think we can consider using [pipx](https://pipxproject.github.io/pipx) to install CLI tools like yamllint

**Comment by yvele** [comment]
I'm not a python expert, @adrienverge do you think pipx will do the job?

**Comment by adrienverge** [comment]
I don't know pipx much, but I wouldn't recommend using it. Pip is standard, solid and tested for decades, and if an isolated environment is needed (@maxim-lobanov is it why you propose pipx?) I recommend using a virtualenv (which is a Python standard, like pip).

> we are trying not install tools through pip because it often installs additional dependencies 

For info, yamllint has only 2 dependencies: pyyaml and pathspec. Hard to do less :wink:

**Comment by maxim-lobanov** [comment]
Hello. @adrienverge @yvele , Ubuntu images with yamlint installed via pip (pipx) was deployed everywhere. Could you please validate that it works as expected for you.
After that we will proceed with the same changes on MacOS / Windows

**Comment by yvele** [comment]
I can confirm I have the latest yamllint version 👍  v1.25.0

Thank you @maxim-lobanov

**Comment by maxim-lobanov** [comment]
Cool, we also changing installation approach on other images for consistency. Will report back when it is done

**Comment by nikita-bykov** [comment]
Windows and macOS images with yamlint installed via pipx was deployed everywhere also
