### ISSUE TITLE
Update Xcode to 12 version

### ISSUE THREAD

**Issue by Svardak** [actions/virtual-environments#1659]
**Tool information**
- Tool name: Xcode 
-  update
- Desired version: 12
- Approximate size: 

**Virtual environments affected**
- [x] macOS 10.15

Please install new version of Xcode on the machines that Pipelines uses.

**Comment by maxim-lobanov** [comment]
Hello @Svardak , Actually Xcode 12 is installed on our images for a few weeks. Please follow documentation to find installation location: https://github.com/actions/virtual-environments/blob/main/images/macos/macos-10.15-Readme.md#xcode

Also Xcode 12.2 beta 1 is on way and will be deployed in a few hours.

**Comment by Darleev** [comment]
@Svardak In case of any questions, feel free to contact us.
I'm going to close the issue.

**Comment by st3fan** [comment]
@maxim-lobanov @Darleev  If I understand correctly, the image currently has Xcode 12.0.0, which cannot be used to created builds for the App Store. Apple issued a 12.0.1 update for that soon after Xcode 12 went GM.

**Comment by maxim-lobanov** [comment]
> @maxim-lobanov @Darleev If I understand correctly, the image currently has Xcode 12.0.0, which cannot be used to created builds for the App Store. Apple issued a 12.0.1 update for that soon after Xcode 12 went GM.

We can't install Xcode 12.0.1 to images right now because Apple doesn't provide way to download it. Apple provides Xcode 12.0.1 via AppStore only but Apple Developer site still points to 12.0.0 GM as latest release: 
![image](https://user-images.githubusercontent.com/16715858/94451077-a80c8300-01b6-11eb-916d-331a6da55ca8.png)

We can't update it until it is there

**Comment by st3fan** [comment]
@maxim-lobanov You can download the 12.0.1 XIP file from https://developer.apple.com/download/more/

Direct link at https://download.developer.apple.com/Developer_Tools/Xcode_12.0.1/Xcode_12.0.1.xip

(This download page is not very discoverable - but it is the 'old' downloads list with all packages, including Xcode versions that go back years)

**Comment by maxim-lobanov** [comment]
@st3fan , thank you, looks like it was added recently.

Do we really need to add 12.0.1 to images?
The release notes state the following:
```
Opening the Developer Documentation window no longer causes Xcode to crash. (66690089)
```
Link: https://developer.apple.com/documentation/xcode-release-notes/xcode-12_0_1-release-notes

This update fixes an issue that could cause Xcode to crash when viewing documentation
As this appears to be the only change, it appears immaterial for CI environments, so continuing to build and release your apps with 12.0.0 will be perfectly fine. As far as I know, you can still publish releases to App Store using Xcode 12.0.0

**Comment by st3fan** [comment]
Hmm now I am not sure actualy. I thought 12.0.1 was required for app store submissions, but maybe there was instead a difference between 12.0.0GM and 12.0.0 ? Sorry for the confusion.

**Comment by radekwilczak** [comment]
@maxim-lobanov 
Why the `xcodeVersion: 'default'` is Xcode 11.7?
I think it should pointing to Xcode 12

**Comment by maxim-lobanov** [comment]
@radekwilczak , It will be switched soon. See details in announcement: https://github.com/actions/virtual-environments/issues/1712
Usually, we change default Xcode in a few weeks after adding to make sure that customers adapt to update.
