### ISSUE TITLE
Add mcr.microsoft.com/dotnet/framework/sdk:4.8-windowsservercore-ltsc2019 to Docker cache

### ISSUE THREAD

**Issue by vgubar** [actions/virtual-environments#1661]
**Tool information**
- Tool name: docker image mcr.microsoft.com/dotnet/framework/sdk:4.8-windowsservercore-ltsc2019
- Add or update? Add
- If this is an add request:
  - Brief description of tool: docker image from Microsoft what is most suitable for agent ( VS2019 and .NetFramework SDK inside )
  - URL for tool's homepage: https://hub.docker.com/_/microsoft-dotnet-framework-sdk/

**Area for Triage**:
Docker, Container, Image

**Question, Bug, or Feature?**:
Feature

**Virtual environments affected**
- [x ] Windows Server 2019

**Can this tool be installed during the build?**
no

**Are you willing to submit a PR?**
Yes, if needed

**Comment by maxim-lobanov** [comment]
Hello @vgubar ,
Does "mcr.microsoft.com/dotnet/framework/runtime" image fit for your goals?
We have some concerns about baking this docker image to Hosted images because of the size. It takes 10GB on drive but we have limited disk space on Hosted images.

**Comment by vgubar** [comment]
Hello @maxim-lobanov , 
Unfortunately - no. 
We are using build inside the container to build legacy services with mssql tests. So we need to have VS2019, Nuget, MS SQL server inside the image. Everything except MS SQL server is present inside mcr.microsoft.com/dotnet/framework/sdk. It is logical for us to use it as a base image and just add SQL Server + few small things. I do believe that this image is huge but maybe you will find free space to add it. As for me, it is the most logical image to be used as base image for any builds inside windows containers.

**Comment by AlenaSviridenko** [comment]
Hi @vgubar,
after some internal discussion, we came up with the conclusion not to add this container to the image, sorry. Our decision based on container size and its popularity. We have never had previously any requests to add it.
Hopefully, we will revisit this solution in the future, if there will be other requests to add it. 

I am going to close this issue, please feel free to create a new one in case if any other help is needed.
Thanks!

**Comment by HassanBedawy** [comment]
I'm having the similar issue, takes 20 minutes to build .Net framework docker image.

**Comment by austindrenski** [comment]
@AlenaSviridenko Sorry to dredge this up, but wanted to add another data point here (rather than opening a new issue) because its unclear whether this decision focused on (A) `not enough requests`, or (B) `too big even if there were more requests`.

But having the .NET Framework Docker images pre-cached would have a significant quality of life impact for those of us maintaining containerized legacy apps that are still locked into the .NET Framework.

My organization even recently joined the [Larger Runners Beta](https://github.blog/changelog/2022-09-01-github-actions-larger-runners-are-now-in-public-beta/) in hopes of improving our legacy container build times, but alas, things are still painfully slow. For example, a workflow that runs for 15 minutes will spend 9.5 of those minutes downloading `mcr.microsoft.com/dotnet/framework/{aspnet,runtime}:4.8-windowsservercore-ltsc2019`.

**Comment by austindrenski** [comment]
> @AlenaSviridenko Sorry to dredge this up, but wanted to add another data point here (rather than opening a new issue) because its unclear whether this decision focused on (A) `not enough requests`, or (B) `too big even if there were more requests`.
> 
> But having the .NET Framework Docker images pre-cached would have a significant quality of life impact for those of us maintaining containerized legacy apps that are still locked into the .NET Framework.
> 
> My organization even recently joined the [Larger Runners Beta](https://github.blog/changelog/2022-09-01-github-actions-larger-runners-are-now-in-public-beta/) in hopes of improving our legacy container build times, but alas, things are still painfully slow. For example, a workflow that runs for 15 minutes will spend 9.5 of those minutes downloading `mcr.microsoft.com/dotnet/framework/{aspnet,runtime}:4.8-windowsservercore-ltsc2019`.

...of course, immediately after posting this I went to double check the manifest, and found this:

https://github.com/actions/runner-images/blob/fb3b6fd69957772c1596848e2daaec69eabca1bb/images/win/Windows2019-Readme.md?plain=1#L587-L588

which would seem to imply this decision was reversed at some later point in time and the responsibility for my Docker workflow woes perhaps lies elsewhere. 🤦
