### ISSUE TITLE
GenerateResourcesAndImage throwing "Cannot bind parameter" error

### ISSUE THREAD

**Issue by spowser** [actions/virtual-environments#1664]
**Description**  
When I run the GenerateResourcesAndImage command, I get prompted to enter my credentials.  Once I enter them the script starts and after a while throws the following error

```
GenerateResourcesAndImage : Cannot bind parameter 'PasswordCredential'. Cannot convert the
"System.Security.SecureString" value of type "System.Security.SecureString" to type
"Microsoft.Azure.Commands.ActiveDirectory.PSADPasswordCredential".
At line:1 char:1
+ GenerateResourcesAndImage -SubscriptionId XXXXXXXX-XXXX-XXXX-XXXX-XXe ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [GenerateResourcesAndImage], ParameterBindingException
    + FullyQualifiedErrorId : CannotConvertArgumentNoMessage,GenerateResourcesAndImage

```

When I checked Azure, the storage had been created so part of the script was successful.

**Area for Triage**:  

**Question, Bug, or Feature?**:  

**Virtual environments affected**  
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Ubuntu 20.04 LTS
- [ ] Windows Server 2016 R2
- [X] Windows Server 2019

**Expected behavior**  
Script to run to completion

**Actual behavior**  
Script is throwing an error

**Repro steps**  
A description with steps to reproduce the issue. If your have a public example or repo to share,
please provide the link.

1. Following the instructions found [here](https://github.com/actions/virtual-environments/blob/main/help/CreateImageAndAzureResources.md)
2. Got to the step where I am suppose to run GenerateResourcesAndImage

**Comment by spowser** [comment]
Looks like this is failing on line 170 with 
$sp = New-AzADServicePrincipal -DisplayName $spDisplayName -Password (ConvertTo-SecureString $ServicePrincipalClientSecret -AsPlainText -Force)

**Comment by vsafonkin** [comment]
Hello @spowser , thank you for your report! We've prepared PR with fix, you could see link above.

**Comment by vsafonkin** [comment]
@spowser , PR with fix was merged, could you please check your build?

**Comment by spowser** [comment]
@vsafonkin This is now working as expected.  Thanks!
