### ISSUE TITLE
Add xcbeautify to macOS image

### ISSUE THREAD

**Issue by MarcoEidinger** [actions/virtual-environments#1665]
**Tool information**
- Tool name: xcbeautify
- Tool license: MIT
- Add or update? Add
- Desired version: 0.8.1 (latest)
- Approximate size: 
- If this is an add request:
  - Brief description of tool: xcbeautify is a little beautifier tool for xcodebuild. Similar to xcpretty, but faster and in active development / maintenance.
  - URL for tool's homepage: https://github.com/thii/xcbeautify
  - Provide a basic test case to validate the tool's functionality: ```set -o pipefail && xcodebuild [flags] | xcbeautify```

**Area for Triage**:
Apple

**Question, Bug, or Feature?**:
Feature

**Virtual environments affected**
- [X] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Ubuntu 20.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Can this tool be installed during the build?**
Yes

**Tool installation time in runtime**

**Are you willing to submit a PR?**
For macOS image I believe you don't allow PR at this time

**Comment by AlenaSviridenko** [comment]
Hi @MarcoEidinger,
this tool can be installed in runtime via `brew install xcbeautify` in less than a minute. Considering this fact, we wouldn't like to pre-install it on the image. We are trying not add tools that are easily installed in runtime due to maintenance reasons.

I will close this issue. Please, feel free to open a new one in case of any questions.
Thanks.

**Comment by thomasvl** [comment]
Just curious, given xcpretty is installed (but not really updated), why not eventually move to this instead?  Or atleast stop including xcpretty if the goal is to have fewer things in the images?

**Comment by pronebird** [comment]
Fair point about `xcpretty`. It hasn't been updated in the past 5 years and is entirely broken for parallel testing with newer Xcode. Yet remains a part of macOS image. Baffling to say the least.

**Comment by henrikhelmers** [comment]
Both this and #6198 was closed, yet xcpretty remains. Is there a plan to update to xcbeautify?
