### ISSUE TITLE
Install Azure powershell 4.7.0 (AZ module) (current max version is 4.6.0)

### ISSUE THREAD

**Issue by PaulVrugt** [actions/virtual-environments#1671]
**Tool information**
- Tool name: Azure powershell 
- Add or update? Update
- Desired version: 4.7.0
- Approximate size:

**Area for Triage**:

**Question, Bug, or Feature?**:
Bug: The 4.6 version of Az contains a bug which breaks ARM deployments with secure strings as parameters. See https://github.com/Azure/azure-powershell/issues/12792

**Virtual environments affected**
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Ubuntu 20.04 LTS
- [ ] Windows Server 2016 R2
- [x] Windows Server 2019

**Can this tool be installed during the build?**
No, since the azurepowershell task breaks if you set the az version to 4.7.0

**Tool installation time in runtime**
Not sure

**Are you willing to submit a PR?**
No, lacking knowledge on how to do this

**Comment by dibir-magomedsaygitov** [comment]
Hello, @PaulVrugt!
Thank you for your report! We have prepared PR with the addition of 4.7.0 version of Azure Powershell.
I will post an update message as soon as Image with updated Azure Powershell is available for use.

**Comment by PaulVrugt** [comment]
@dibir-magomedsaygitov  Wow that was fast. Thank you!

**Comment by dibir-magomedsaygitov** [comment]
[PR](https://github.com/actions/virtual-environments/pull/1672) with Azure Powershell v4.7.0 was successfully merged and will be available with the this week's rollout.

**Comment by felixtsem5** [comment]
@dibir-magomedsaygitov Can you please let us know when this will be available? I just checked in Azure Pipelines and the latest is still 4.6.0. Thanks!

**Comment by SamAchten** [comment]
Is there a workaround while we wait for the fix? Our pipelines broke...

**Comment by PaulVrugt** [comment]
@SamAchten the workaround is to revert to azure powershell 4.4. You can do this by using the following properties in the AzurePowerShell@5 task:

```
inputs:
    azurePowerShellVersion: OtherVersion
    preferredAzurePowerShellVersion: '4.4.0'
```

**Comment by SamAchten** [comment]
That worked! 🥳 Thanks

**Comment by dibir-magomedsaygitov** [comment]
Hello everyone! Sorry for the delay, new Windows Images with updated Azure Powershell should be available next week.

**Comment by lpalerm** [comment]
> Hello everyone! Sorry for the delay, new Windows Images with updated Azure Powershell should be available next week.

Do you have a date when this will be updated?

**Comment by dibir-magomedsaygitov** [comment]
Hello everyone! Quick update: Azure Powershell v4.7.0 is available to use on all Ubuntu images and on Windows 19 image. Deployment of Windows 16 was delayed and (hopefully) will be delivered next week. 
I will post update message when Azure Powershell v4.7.0 is available to use on Windows 16 as well. Thank you for your patience.

**Comment by al-cheb** [comment]
Hello, @PaulVrugt 
Az 4.7.0 is now available fo[r Windows Server 2016](https://github.com/actions/virtual-environments/blob/releases/win16/20201012/images/win/Windows2016-Readme.md) and [Windows Server 2019](https://github.com/actions/virtual-environments/blob/releases/win19/20201011/images/win/Windows2019-Readme.md).
