### ISSUE TITLE
[Windows 2016] devenv.exe command not found

### ISSUE THREAD

**Issue by hutson** [actions/virtual-environments#1675]
**Description**  

```
    ami: & : The term '\Common7\IDE\devenv.exe' is not recognized as the name of a cmdlet, function, script file, or operable
    ami: program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
    ami: At C:\Windows\Temp\script-5f6bc08b-ca2e-6df6-ae71-37479f56c6a0.ps1:38 char:3
    ami: + & "$vsInstallRoot\Common7\IDE\devenv.exe" /RootSuffix Exp /ResetSetti ...
    ami: +   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    ami:     + CategoryInfo          : ObjectNotFound: (\Common7\IDE\devenv.exe:String) [], ParentContainsErrorRecordException
    ami:     + FullyQualifiedErrorId : CommandNotFoundException
    ami:
```

I copied the contents of [`virtual-environments/images/win/scripts/Installers/Install-VS.ps1`](https://github.com/actions/virtual-environments/blob/09550baace58a0939352f83ba18937a1d52af429/images/win/scripts/Installers/Install-VS.ps1) directly to a host that has had all the provisioners, [up to, but not including](https://github.com/actions/virtual-environments/blob/184354ad8e12f550801977d5497e0e5881fc0caa/images/win/Windows2016-Azure.json#L163), the `{{ template_dir }}/scripts/Installers/Install-VS.ps1` script.

I deleted all code after the `$vsInstallRoot = Get-VisualStudioPath` line.

Visual Studio is installed successfully.

However, `Get-VisualStudioPath` returns an empty string. Therefore, using `Get-VisualStudioPath` to generate a path to call `devenv.exe` fails the build since `Get-VisualStudioPath` does not provide the path.

<img width="620" alt="Screen Shot 2020-09-24 at 4 03 37 PM" src="https://user-images.githubusercontent.com/6701030/94312365-5c51a380-ff42-11ea-915c-161df7070271.png">

If I restart the server and launch Powershell, the `Get-VisualStudioPath` command returns a valid path:

<img width="444" alt="Screen Shot 2020-09-24 at 4 36 46 PM" src="https://user-images.githubusercontent.com/6701030/94312414-7095a080-ff42-11ea-989a-e9573901b767.png">

The strategy for fetching the Visual Studio installation path was updated here - https://github.com/actions/virtual-environments/commit/128244b89b8532a3604a2ad227eecd05b7a54065#diff-374e11b40c99faf6a33867bb32f94079

It should be noted that I am targeting AWS. The only changes to the `Windows2016-Azure.json` file are to add an `amazon-ebs`  builder, and to remove all provisioners mentioned above.

While it's possible that this issue is specific to the Windows 2016 Data Center edition we use as a base from Amazon, I wanted to see if others were running into this issue.

**Question, Bug, or Feature?**:  

Bug

**Virtual environments affected**  
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Ubuntu 20.04 LTS
- [x] Windows Server 2016 R2
- [ ] Windows Server 2019

**Comment by dmitry-shibanov** [comment]
Hello @hutson  , could you please ensure, that you have installed VSSetup powershell module from [here](https://github.com/actions/virtual-environments/blob/854d90d2058963f1e3cc0c7c404857aa9c898910/images/win/scripts/Installers/Install-PowerShellModules.ps1#L25), because `Get-VisualStudioPath` depends on two methods `Get-VSSetupInstance` and `Select-VSSetupInstance` which come from VSSetup module.

**Comment by dmitry-shibanov** [comment]
Hello @hutson , just a gentle ping.

**Comment by hutson** [comment]
I apologize for not having had time to investigate whether the VSSetup module installed correctly. I still plan to, but in the meantime there is no reason to keep this issue open.
