### ISSUE TITLE
Update DacFx 18.5.1 to 18.6

### ISSUE THREAD

**Issue by dzsquared** [actions/virtual-environments#1676]
**Tool information**
- Tool name: DacFx
- Tool license: 
- Add or update? Update
- Desired version: latest, 18.6
- Approximate size: 
- If this is an add request:
  - Brief description of tool: 
  - URL for tool's homepage: 
  - Provide a basic test case to validate the tool's functionality: 

**Area for Triage**: Databases

**Question, Bug, or Feature?**: Feature

**Virtual environments affected**
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Ubuntu 20.04 LTS
- [X] Windows Server 2016 R2
- [X] Windows Server 2019

**Can this tool be installed during the build?**

**Tool installation time in runtime**

**Are you willing to submit a PR?**
PR incoming

**Comment by maxim-lobanov** [comment]
Hello!
Sorry for delay, PR has been merged. Changes will be deployed next week

**Comment by miketimofeev** [comment]
@dzsquared the images were deployed, dacfx version is available in the readme:
https://github.com/actions/virtual-environments/blob/main/images/win/Windows2019-Readme.md#database-tools
I'm going to close the issue, thank you for your contribution!
