### ISSUE TITLE
Add Microsoft BizTalk project build components

### ISSUE THREAD

**Issue by Elvis-Shi** [actions/virtual-environments#1678]
- Tool name: BizTalk project build component
- Tool license: Developer license
- Add or update? Add
- Desired version: Not decided yet.
- Approximate size: 
- If this is an add request:
  - Brief description of tool:  BizTalk is a Microsoft product, you can refer to [here ](https://docs.microsoft.com/en-us/biztalk/) to get more understanding about what is BizTalk. Our customer use BizTalk development tools, which are built on top of Visual Studio, to create, and build BizTalk solutions. We also created an Azure devOps pipeline component "[Deploy BizTalk Application](https://marketplace.visualstudio.com/items?itemName=ms-biztalk.deploy-biztalk-application)" for deployment, while customers are also willing to use Azure DevOps pipeline hosted agent to do the build.
 
  - URL for tool's homepage: https://docs.microsoft.com/en-us/biztalk/core/developer-tools
  - Provide a basic test case to validate the tool's functionality:  if msbuild biztalk.sln can give success, then it works.

**Area for Triage**:
Servers?

**Question, Bug, or Feature?**:
Feature

**Virtual environments affected**
- [ ] Windows Server 2019

**Can this tool be installed during the build?**
Yes, we will provide a script to copy all the files required into Visual studio directory, or other directories required. 

**Tool installation time in runtime**
Less than 5mins.

**Are you willing to submit a PR?**
Yes.

**Comment by AlenaSviridenko** [comment]
Hi @Elvis-Shi, could you please share how you install it in runtime? 
Could you please clarify what exactly is expected to be installed, I found this guide with BizTalk Server and VS extension installation https://docs.microsoft.com/en-us/biztalk/install-and-config-guides/install-biztalk-server-2020 - is that it?

**Comment by Elvis-Shi** [comment]
@AlenaSviridenko, we don't have a standalone setup for this yet, we know what need to be installed, will create a script, or a MSI to install these files. It is not whole BizTalk, not even the dev tools feature, but a subset of dev tools(only necessary files needed for build).

**Comment by AlenaSviridenko** [comment]
Hi @Elvis-Shi, could you please clarify few unclear moments about this tool:
1. What is the expected tool size? For tools more than 700-800 Mb — we are usually considering the tool popularity before making a decision whether to add it or not, as this is a significant size.
2. What is the expected tool popularity?
3. Will it be an installation binary or a workload/component for Visual Studio?
4. Have you considered creating `setup-biztalk` action so customers could install it in runtime easily?

**Comment by Elvis-Shi** [comment]
> Hi @Elvis-Shi, could you please clarify few unclear moments about this tool:
> 
> 1. What is the expected tool size? For tools more than 700-800 Mb — we are usually considering the tool popularity before making a decision whether to add it or not, as this is a significant size.
Elvis: As i mentioned above, we don't need to install the whole BizTalk, just the build support, should be less than 100M.
> 2. What is the expected tool popularity?
Elvis: Not sure how to detail the popularity. BizTalk has customers around the world during the last 20 years. Most of our customers are enterprise customers.
> 3. Will it be an installation binary or a workload/component for Visual Studio?
Elvis: We will firstly consider a vsix for Visual studio, but probably will be an MSI and a vsix.
> 4. Have you considered creating `setup-biztalk` action so customers could install it in runtime easily?
Elvis: This will be an approach, but not the best way for us, and customer experience. We will approach this direction when we do have problem to install it in the Azure devops hosted machines.

**Comment by AlenaSviridenko** [comment]
Hi @Elvis-Shi,
thank you for the detailed response, we will definitely keep in mind this tool and consider its pre-installation on the image.

But since ETA on this tool is not clear, we would like not to keep this issue open in the repository. I will close it if you don't mind, please, create a new one when the details are clear and will start working on it.

Thanks!

**Comment by Elvis-Shi** [comment]
> Hi @Elvis-Shi,
> thank you for the detailed response, we will definitely keep in mind this tool and consider its pre-installation on the image.
> 
> But since ETA on this tool is not clear, we would like not to keep this issue open in the repository. I will close it if you don't mind, please, create a new one when the details are clear and will start working on it.
> 
> Thanks!

Are we get an approval for this, and can start to create our tool setup and raise a pull request? or what else information do you need before that?
