### ISSUE TITLE
Windows image 20200920.1 - logging problems?

### ISSUE THREAD

**Issue by ABBAPOH** [actions/virtual-environments#1679]
**Description**  
After the image upgrade from version 20200827.1 to 20200920.1, we experience constant failures in our tests. It appears that there are some sort of problems with stderr/stdout with Qt applications.
For instance, the whole output from the test disappears as seen here https://github.com/rweickelt/qbs/runs/1159313492 (there's no output after the line Running Qbs tests (2 jobs in parallel); from the duration of the job I can conclude that tests are run). This job uses new image (20200920.1)
With the image running on the previous image version, the output is present as expected https://github.com/rweickelt/qbs/runs/1159313524 (this job still uses 20200827.1)
If I change the test output format to xml, I can see the logs: https://github.com/ABBAPOH/qbs/runs/1169806396?check_suite_focus=true but that's not very convenient and doesn't explain what happens to the plain text output.
My suspicion was that some ENV variable was set that interferes with the logging, but I do not see anything that could be related

**Area for Triage**:  
Area: C/C++

**Question, Bug, or Feature?**:  
Bug

**Virtual environments affected**  
- [*] Windows Server 2019

**Expected behavior**  
I expect output to be visible

**Actual behavior**  
No output from Qt tests

**Repro steps**  
1. Simply trigger a workflow at https://github.com/qbs/qbs (or forked version)
2. There will be no output from tests at all.

**Comment by dsame** [comment]
While i am investigating the build, can you please make sure the tst_* binaries produce any output at all?

From my build https://github.com/dsame/qbs/runs/1180813452?check_suite_focus=truev i see none of them put anything to stdout in any shells

**Comment by ABBAPOH** [comment]
I've downloaded the artifacts and yes, I do see the output when run manually.
It might be that somehow Qt logging is turned off (the same seem to happen to our binaries as well - all logging from C++ code is missing, that's why tests are failing), but I do not see how this can be possible considering the fact that env doesn't contain any Qt related variables. The logging levels are controlled by the QT_LOGGING_RULES or QT_LOGGING_CONF variables but they are not set AFAIK (https://doc.qt.io/qt-5/qloggingcategory.html#logging-rules).
I also think I've seen the similar problem with TeamCity a year ago, but that was because of the log filtering and I cannot reproduce that with the echo command on GitHub - echo works.

**Comment by ABBAPOH** [comment]
We've found a workaround. Apparently, Qt thinks that there is no console attached to the app (which is case when app is run from IDE, for example). It is possible to force console logging by setting QT_FORCE_STDERR_LOGGING=1 or QT_ASSUME_STDERR_HAS_CONSOLE=1.
