### ISSUE TITLE
Azure DevOps CLI issue in Windows Server 2019

### ISSUE THREAD

**Issue by martingemme** [actions/virtual-environments#1682]
**Description**  
Running `az pipelines pool list --organization $Organization --pool-name $PoolName` in Windows throws the following exception:

I'm currently at commit [956f9257505d3d10e63220e93da37dfd37a55778 ](https://github.com/actions/virtual-environments/commit/956f9257505d3d10e63220e93da37dfd37a55778) (not too far behind).

```
2020-09-28T02:48:48.3895140Z ##[error]UnexpectedError: The command failed with an unexpected error. Here is the traceback:
[WinError 5] Access is denied: 'C:\\Program Files\\Common Files\\AzureCliExtensionDirectory\\azure-devops\\azure_devops-0.18.0.dist-info'
Traceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-2gf5i3x9\knack\cli.py", line 215, in invoke
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-cep_dxyk\azure\cli\core\commands\__init__.py", line 509, in execute
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-cep_dxyk\azure\cli\core\__init__.py", line 436, in load_command_table
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-cep_dxyk\azure\cli\core\__init__.py", line 307, in _update_command_table_from_extensions
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-cep_dxyk\azure\cli\core\extension\__init__.py", line 156, in get_metadata
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-2izf0p5u\pkginfo\wheel.py", line 16, in __init__
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-2izf0p5u\pkginfo\distribution.py", line 108, in extractMetadata
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-2izf0p5u\pkginfo\wheel.py", line 33, in read
PermissionError: [WinError 5] Access is denied: 'C:\\Program Files\\Common Files\\AzureCliExtensionDirectory\\azure-devops\\azure_devops-0.18.0.dist-info'
To open an issue, please run: 'az feedback'
```
I'm unsure if it's during the installation of the extension, but we (almost) follow the exact same pipelines as per this repo, except we publish to Shared Image Gallery.

The same PowerShell function in Ubuntu 20.04 works perfectly.

**Area for Triage**:  

- Deployment/Release
- Scripting and command line

**Question, Bug, or Feature?**:  
Bug

**Virtual environments affected**  
- [ ] ~macOS 10.15~ (we do not have this image to try)
- [ ] ~Ubuntu 16.04 LTS~ (we do not have this image to try)
- [ ] ~Ubuntu 18.04 LTS~ (we do not have this image to try)
- [ ] Ubuntu 20.04 LTS
- [ ] ~Windows Server 2016 R2~ (we do not have this image to try)
- [X] Windows Server 2019

**Expected behavior**  
CLI has the appropriate permission to the tool.

**Actual behavior**  
CLI doesn't have appropriate permission to the tool.

**Repro steps**  
A description with steps to reproduce the issue. If your have a public example or repo to share,
please provide the link.

1. Step 1 - Azure Powershell in Azure Pipelines (Release)
```
Write-Output "Authenticating to Azure DevOps"
$env:AZURE_DEVOPS_EXT_PAT = $AccessToken; # PAT that has appropriate permissions to our Azure DevOps instance

Write-Output "Find Pool"
$pools=$(az pipelines pool list --organization $Organization --pool-name $PoolName);
```
2. Step 2
Error mentioned above.

**Comment by mihsoft** [comment]
@martingemme - Confirmed in the packer file - Windows2019-Azure.json

```
* Bad script
'/agent/_work/1/s/virtual-environments/images/win/scripts/Installers/Install-AzureDevSpacesCli.ps1':
stat
/agent/_work/1/s/virtual-environments/images/win/scripts/Installers/Install-AzureDevSpacesCli.ps1:
no such file or directory
```

**Comment by al-cheb** [comment]
Hello, @martingemme 
Could you please provide image version which you are using? I can't reproduce the issue:

Current image version: '20200920.1'
![image](https://user-images.githubusercontent.com/47745270/94554280-88cb2f80-0262-11eb-8aed-f69e44d2956c.png)

Current image version: '20200927.0'
![image](https://user-images.githubusercontent.com/47745270/94554389-aac4b200-0262-11eb-8146-ca918c1712a2.png)

**Comment by martingemme** [comment]
I'm unsure which image version, we're using our own yyyy.mm.ddBuildNumber scheme.

As stated I'm currently at commit 956f9257505d3d10e63220e93da37dfd37a55778 (not too far behind).

Is there something I could try? We have the same scripts

**Comment by martingemme** [comment]
I updated our repo with the latest and will post back if main (at the time of writing https://github.com/actions/virtual-environments/commit/854d90d2058963f1e3cc0c7c404857aa9c898910) has fixed it.

**Comment by martingemme** [comment]
Unfortunately still the same issue. I'm at 854d90d

**Comment by al-cheb** [comment]
@martingemme , Could you please provide output with `whoami /groups`?

**Comment by martingemme** [comment]
@al-cheb 
![Capture](https://user-images.githubusercontent.com/2473921/94711216-d3f24a80-0315-11eb-8478-79a5bbe1f022.PNG)

**Comment by martingemme** [comment]
![Capture](https://user-images.githubusercontent.com/2473921/94718525-d8236580-031f-11eb-89d8-c2b03c219933.PNG)
@al-cheb

**Comment by al-cheb** [comment]
@martingemme, Try to provide full permissions:

```
- name: grant Full Access to AZURE_EXTENSION_DIR directory
   run: |
         icacls "$env:AZURE_EXTENSION_DIR" /q /c /t /grant Everyone:F
```

**Comment by martingemme** [comment]
![image](https://user-images.githubusercontent.com/2473921/94728802-c5645d00-032e-11eb-95ed-28238dfcf7aa.png)
Unfortunately, the command didn't work. Thanks for the help so far!

**Comment by al-cheb** [comment]
@martingemme, As  we can see above your token has `Mandatory Label\Medium Mandatory Level` = standard user rights. You should run process with `Mandatory Label\High Mandatory Level`=administrator rights. During image generation we disable UAC - https://github.com/actions/virtual-environments/blob/9110b389998666dc0c6a8e9abd9400248bad8dba/images/win/scripts/Installers/Initialize-VM.ps1#L28

**Comment by martingemme** [comment]
We're using VMSS with the Re-image turned on in Azure DevOps. Therefore we do not go into the agents and there is actually in the script the execution of Disable-UserAccessControl at https://github.com/actions/virtual-environments/blob/9110b389998666dc0c6a8e9abd9400248bad8dba/images/win/scripts/Installers/Initialize-VM.ps1#L69

(I believe) The Task Scheduler is also managed by Azure DevOps (and installed by Azure DevOps), so I cannot change on an instance basis when they are always re-imaged after each build.

I verified and in our repo, we have that same line in script that should disable UAC. Perhaps it is an issue that should be fixed from the Azure team?

**Comment by martingemme** [comment]
I confirm that the user is not running the powershell script with admin rights.

The question I thus have if I built the image from your source: Why doing az pipelines list fails because az cli can't access a directory? shouldn't any user be able to run the az cli? why do I need admin rights to run az cli?

**Comment by martingemme** [comment]
```
whoami /groups

$folderName = "C:\Program Files\Common Files\AzureCliExtensionDirectory\azure-devops"
Write-Output $folderName
(get-acl $folderName).access | ft IdentityReference,FileSystemRights,AccessControlType,IsInherited,InheritanceFlags -auto
```
![image](https://user-images.githubusercontent.com/2473921/94747376-bab8c080-034c-11eb-8501-bd3a2c043e0b.png)

**Comment by al-cheb** [comment]
> The question I thus have is if I built the image from your source:
> 
> Why doing az pipelines list fails because az cli (and its extensions) can't access a directory?
> * Shouldn't any user be able to run the az cli and its extensions?
> * Why do I need admin rights to run az cli and its extensions?
> 
> This is bizarre as the user is in the Administrators group, and the folder has full control for administrators (the group). We're not sure why this is going on.

UAC - https://docs.microsoft.com/en-us/windows/security/identity-protection/user-account-control/how-user-account-control-works

When an **administrator logs on**, **two separate access tokens are created for the user: a standard user access token and an administrator access token**. The standard user access token contains the same user-specific information as the administrator access token, but **the administrative Windows privileges and SIDs are removed**. The standard user access token is used to start apps that do not perform administrative tasks (standard user apps). The standard user access token is then used to display the desktop (explorer.exe). Explorer.exe is the parent process from which all other user-initiated processes inherit their access token. **As a result, all apps run as a standard user unless a user provides consent or credentials to approve an app to use a full administrative access token**.

That's why you don't have full access, because you token is `Mandatory Label\Medium Mandatory Level = standard user rights`. 

In our agents as you can see with disabled UAC we have `Mandatory Label\High Mandatory Level=administrator rights`:
![image](https://user-images.githubusercontent.com/47745270/94773907-70275a80-03c5-11eb-8427-ede3a7610d5c.png)

**Comment by martingemme** [comment]
@al-cheb Thanks for the input!

For the people that would like to fix it for their own, we have a VMSS so the fix was to disable (or toggle off) "Configure VMs to run interactive tests" like so:
![image](https://user-images.githubusercontent.com/2473921/94869000-519b8080-0412-11eb-8928-1386c8f563db.png)

Thanks @al-cheb again!

**Comment by al-cheb** [comment]
@martingemme, Thank you for providing resolution.

Put small notes - https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/scale-set-agents?view=azure-devops
Configure VMs to run interactive tests (Windows Server OS Only) - Windows agents can either be configured to run unelevated with autologon and with interactive UI, or they can be configured to run with elevated permissions. **Check this box to run unelevated with interactive UI. In either case, the agent user is a member of the Administrators group.**
