### ISSUE TITLE
Xcode 11.0, 11.1, 11.4.0 will be deprecated on November, 5

### ISSUE THREAD

**Issue by AlenaSviridenko** [actions/virtual-environments#1688]
### Breaking changes
Xcode 11.0, 11.1 and 11.4.0 will be removed from MacOS 10.15 image

### Target date
Deployment of these changes will be started on 5 November and will take a few days.

### The motivation for the changes
Currently, we have 13 Xcode versions on image and it become a problem to deliver important updates quickly because it affects image generation / image deployment time. We would like to get rid of old Xcode versions.

### Possible impact
If you use Xcode 11.0 or 11.1, your builds will stop to work after this change.
If you use Xcode 11.4, your builds will be switched to Xcode 11.4.1 automatically.

### Mitigation ways
Unfortunately, there is no quick way to install Xcode to image in runtime.

**Comment by maxim-lobanov** [comment]
Note: 11.4.0 is deprecated in favor of 11.4.1 and symlink will be created

**Comment by gagancss** [comment]
Hi what about Xcode 11.3.1 -- will that still be supported ?

**Comment by maxim-lobanov** [comment]
@gagancss , Yes. We deprecate only 11.4.0 in favor of 11.4.1. Previously we have done the same for 11.3 (deprecation of 11.3.0 in favor of 11.3.1). It doesn't make much sense to have more than one patch version

**Comment by maxim-lobanov** [comment]
Changes were deployed everywhere
