### ISSUE TITLE
macos-latest workflows not starting

### ISSUE THREAD

**Issue by matthewfeickert** [actions/virtual-environments#1691]
**Description**  

All workflows on `macos-latest` are failing to start.

**Area for Triage**:  Containers (maybe? Not sure given the choices at https://github.com/actions/virtual-environments/tree/main/triage-rules.yml)

**Question, Bug, or Feature?**: "Bug"

**Virtual environments affected**  
- [x] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Ubuntu 20.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Expected behavior**  

Have the `macos-latest` workflow start and run with the `ubuntu-latest` workflows

**Actual behavior**  
All workflows on `macos-latest` are failing to start.

![not_starting](https://user-images.githubusercontent.com/5142394/94503858-0f353200-01cd-11eb-81e6-c2ebe93753f3.png)

**Repro steps**  

Currently all the GitHub Actions workflows for [`scikit-hep/pyhf`](https://github.com/scikit-hep/pyhf) and [`scikit-hep/pylhe`](https://github.com/scikit-hep/pylhe) are not starting workflows for `macos-latest`. So starting any workflow there will give this behavior. Example: https://github.com/scikit-hep/pyhf/runs/1179710999

cc @lukasheinrich @kratsg

**Comment by Darleev** [comment]
Hello @matthewfeickert.
There were temporary issues with insfrastucture which have already been resolved.
As far as I see, all pipelines are in the completed state Could you please verify that everything is fine at the moment?
We are looking forward to your reply.

**Comment by matthewfeickert** [comment]
> There were temporary issues with insfrastucture which have already been resolved.

That's great to hear. Thanks for this important work.

> As far as I see, all pipelines are in the completed state Could you please verify that everything is fine at the moment?

At the moment I'm still seeing issues with the `macos-latest` environments for [`scikit-hep/pylhe`](https://github.com/scikit-hep/pylhe) (I'm trying to restart the jobs that didn't start their workflows). However, things seem fine for [`scikit-hep/pyhf`](https://github.com/scikit-hep/pyhf) now.

**Comment by dsame** [comment]
@matthewfeickert ,I see the workflows are restored now and issue can be closed, feel free to open new issue in case of problems

**Comment by MacFan4000** [comment]
The same issue appears to be happening today, where macOS-latest workflows aren't starting, they are just queued.

**Comment by gregoireLem** [comment]
Same again right now

**Comment by rdrpenguin04** [comment]
And now

**Comment by cbrnr** [comment]
I'm having this issue with `macos-11.0` (which is not `macos-latest` at the moment), so all macOS runners seem to be (still) affected.

**Comment by rdrpenguin04** [comment]
I think `macos-11.0` has more issues because it's newer, and less machines are available. But IDK.

**Comment by kethan1** [comment]
Having this issue with macos-latest now, https://github.com/kethan1/Simple-To-Do-App/actions/runs/559422277

**Comment by halx99** [comment]
This issue come back again: https://github.com/yasio/yasio/actions/runs/708279970

**Comment by seljabali** [comment]
I've just started experiencing this within a private repo.
