### ISSUE TITLE
 Unable to find a destination matching the provided destination - missing older iOS Simulators in latest XCode

### ISSUE THREAD

**Issue by hakkurishian** [actions/virtual-environments#1697]
**Description**  
Latest Xcode Versions can only run latest iOS Simulators. This makes automated testing on older iOS versions impossible, when older XCode versions are not able to build the products.

**Area for Triage**:  

**Question, Bug, or Feature?**:  
Feature

**Virtual environments affected**  
- [x] macOS 10.15
- [ ] Ubuntu 18.04 LTS
- [ ] Ubuntu 20.04 LTS
- [ ] Ubuntu 16.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Expected behavior**  

It should be possible to configure a pipeline step as such: 
`.    xcodeDeveloperDir: '/Applications/Xcode_12.app/Contents/Developer'
      destinationSimulators: 'iPhone 8,OS=13.6'`

to build an app with e.g. XCode 14 and run it on iOS 12/13.

An example for a bigger variety of simulators in the latest XCode version is TravisCI: 
https://docs.travis-ci.com/user/reference/osx/#xcode-12

**Actual behavior**  

For XCode 12, currently only iOS 14.0 is available on Azure Pipeline (https://github.com/microsoft/azure-pipelines-image-generation/blob/master/images/macos/macos-10.15-Readme.md).
```
xcodebuild: error: Unable to find a destination matching the provided destination specifier:
		{ platform:iOS Simulator, OS:13.6, name:iPhone 8 }
```
The 

**Repro steps**  
A description with steps to reproduce the issue. If your have a public example or repo to share,
please provide the link.

1. Configure a pipeline with the latest XCode Version to use an older iOS Simulator
2. see the error described above

**Comment by maxim-lobanov** [comment]
Hello, it is expected behavior. For now, we don't pre-install additional simulators. By default, Xcode contains simulators only for single version. Related discussion in https://github.com/actions/virtual-environments/issues/551 contains some workarounds that can help to use simulators from different Xcode or install simulators in runtime.

Closing in favor of #551

**Comment by hakkurishian** [comment]
@maxim-lobanov. Thank you for the quick advice, the related discussion in #551 really helped and matches my request.
