### ISSUE TITLE
Only tip of original azure-image-pipeline-generation is moved

### ISSUE THREAD

**Issue by riezebosch** [actions/virtual-environments#170]
I fail to understand that with a _decentralized version control system_ you only copied over latest version of scripts thereby losing all history and contributions. There is so much value in _why_ certain scripts are build the way they are and the only thing you can see now is [`Another mop up commit to add missing changes from the last mop-up`](https://github.com/actions/virtual-environments/commit/1dcd276b1e42aaa2ee3c45707fca988e902263db).

**Comment by kaylangan** [comment]
This was an intentional decision with the move to the `actions` org. While it is a bit more cumbersome to navigate, the history is still available in https://github.com/microsoft/azure-pipelines-image-generation.
