### ISSUE TITLE
HttpError: You have triggered an abuse detection mechanism.

### ISSUE THREAD

**Issue by BrightRan** [actions/virtual-environments#1703]
Associated GitHub Community ticket: https://github.community/t/abuse-detection-mechanism-prevent-running-test/134996

The customer has a step to execute the "[lots0logs/gh-action-get-changed-files](https://github.com/lots0logs/gh-action-get-changed-files)" action to list the changed files on a PR.
Recently, this action goes to failure with the following error (see [here](https://github.com/apache/helix/runs/1185866888?check_suite_focus=true#step:4:8)):
> Error: HttpError: You have triggered an abuse detection mechanism. Please wait a few minutes before you try again.

**Comment by BrightRan** [comment]
Also see the issue ticket ([lots0logs/gh-action-get-changed-files#14](https://github.com/lots0logs/gh-action-get-changed-files/issues/14)) I reported in the action repository.

**Comment by kaisun2000** [comment]
Any updates. Till today, I still get this error blocking me from running tests in workflow config-ed.

https://github.com/kaisun2000/helix/runs/1196686202?check_suite_focus=true

**Comment by maxim-lobanov** [comment]
@BrightRan, I don't think that it is correct place for this issue. We own only content of Hosted images in this repository and we are not familiar with rate limits.

@kaisun2000 , I believe it is an issue with third-party action that you use `gh-action-get-changed-files`. On the quick look, it does N requests to server on every push to your PR where N is number of commits in your PR: https://github.com/lots0logs/gh-action-get-changed-files/blob/002a3dec1083f13f4e1853c5c1dc26526ac185bc/index.js#L29. 
It means that for https://github.com/kaisun2000/helix/pull/1, for every push, this action does 541 requests to server and I don't see any delays between them. I don't know the rate limits for GH system token but it looks like a huge number of requests

**Comment by kaisun2000** [comment]
@maxim-lobanov. My pull request has 500 commits history. Let me try to "squash" them to see if that would help.

**Comment by maxim-lobanov** [comment]
Closing the issue because it is not something that we own in this repository
