### ISSUE TITLE
Unable to extract the msi file using msiexec in windows 2019 hosted agents

### ISSUE THREAD

**Issue by raviteja12345** [actions/virtual-environments#1704]
**Description**  
We are facing an issue while trying to extract the msi using msiexec command with arguments /quiet /passive /qn

**Area for Triage**:  
The only thing that is changed is the Agent version. The previously working build and currently failing build versions are like this:
![image](https://user-images.githubusercontent.com/51077849/94670258-f2fdd600-032f-11eb-8f7e-a30971be1028.png)

**Question, Bug, or Feature?**:  
Bug

**Virtual environments affected**  
- [ ] Windows Server 2019

**Expected behavior**  
Msiexec should work like before.

**Actual behavior**  
Now, throwing an error 2502 and 2503 while trying to extract the msi file.
Action start 8:32:13: InstallFinalize.
MSI (s) (A0:C8) [08:32:13:152]: Running Script: C:\windows\Installer\MSI879F.tmp
MSI (s) (A0:C8) [08:32:13:153]: PROPERTY CHANGE: Adding UpdateStarted property. Its value is '1'.
MSI (s) (A0:C8) [08:32:13:154]: Note: 1: 2203 2: C:\windows\Installer\inprogressinstallinfo.ipi 3: -2147287035 
MSI (s) (A0:C8) [08:32:13:155]: Note: 1: 2503 
DEBUG: Error 2503:  Called RunScript when not marked in progress.
The installer has encountered an unexpected error installing this package. This may indicate a problem with this package. The error code is 2503. The arguments are: , , 
MSI (s) (A0:C8) [08:32:13:157]: Product: XXXXXXXXX -- The installer has encountered an unexpected error installing this package. This may indicate a problem with this package. The error code is 2503. The arguments are: , , 

Action ended 8:32:13: InstallFinalize. Return value 3.
MSI (s) (A0:C8) [08:32:13:173]: Note: 1: 2203 2: C:\windows\Installer\inprogressinstallinfo.ipi 3: -2147287035 
MSI (s) (A0:C8) [08:32:13:174]: Note: 1: 2502 
DEBUG: Error 2502:  Called InstallFinalize when no install in progress.
The installer has encountered an unexpected error installing this package. This may indicate a problem with this package. The error code is 2502. The arguments are: , , 
MSI (s) (A0:C8) [08:32:13:177]: Product: XXXXXXXXX -- The installer has encountered an unexpected error installing this package. This may indicate a problem with this package. The error code is 2502. The arguments are: , , 

MSI (s) (A0:C8) [08:32:13:178]: No System Restore sequence number for this installation.
MSI (s) (A0:C8) [08:32:13:179]: Unlocking Server
MSI (s) (A0:C8) [08:32:13:188]: PROPERTY CHANGE: Deleting UpdateStarted property. Its current value is '1'.
Action ended 8:32:13: ADMIN. Return value 3.

**Comment by dsame** [comment]
@raviteja12345, please try to issue the command `icacls "C:\Windows\Temp" /q /c /t /grant Users:F /T` before expanding the msi.

For example add a step:

```
     - name: grant Full Access to c:\windows\temp directory
       run: |
         icacls "C:\Windows\Temp" /q /c /t /grant Users:F /T
```

**Comment by raviteja12345** [comment]
Thanks.!. Its working now after i add the above mentioned step.

**Comment by raviteja12345** [comment]
The above mentioned is a work around only. And we need to update them in multiple places in our build definitions. So, it would be good if we have a fix for this issue.

**Comment by miketimofeev** [comment]
@raviteja12345 is this issue still persists after https://github.com/actions/virtual-environments/pull/1959?

**Comment by dsame** [comment]
@raviteja12345 we made the the changes permanent and deployed to the production, so you do not have to add the step manually anymore
