### ISSUE TITLE
Default Xcode will be changed to Xcode 12.0.1 on October, 20

### ISSUE THREAD

**Issue by AlenaSviridenko** [actions/virtual-environments#1712]
### Breaking changes
Default Xcode version will be switched from 11.7 to 12.0.1

### Target date
Deployment of these changes will be started on 20 October and will take a few days.

### The motivation for the changes
We would like to provide the latest stable Xcode by default on images. Also it will mitigate compatibility issue with Xamarin.iOS 14.0.

### Possible impact
If you use default Xcode version and your project is not compatible with Xcode 12.0.1, your build can be broken.
Also Xcode 12 has some known issues with Carthage: https://github.com/Carthage/Carthage/blob/master/Documentation/Xcode12Workaround.md

- [x] MacOS 10.15

### Mitigation ways
Please consider switching Xcode in runtime to version that you need to build app.
The following snippet can be used to switch Xcode:
```
sudo xcode-select -s "/Applications/Xcode_11.7.app"
The list of all available Xcode versions can be found in [image documentation](https://github.com/actions/virtual-environments/blob/main/images/macos/macos-10.15-Readme.md#xcode)
```

**Comment by DjCantor** [comment]
Hi, is it possible that not all machines have Xcode 12 installed yet? Sometimes we got a machine which runs the build job on an Xcode 11.7 and fails of course, although we have specified the path for the Xcode 12.

**Comment by maxim-lobanov** [comment]
@DjCantor , this particular change was not deployed yet at all.
But if you switch Xcode in runtime, all machines should have Xcode 12 because this change was deployed a long time ago.
Is it possible to share a public repro?

**Comment by DjCantor** [comment]
@maxim-lobanov thanks for the info, I tried to specify the Xcode version in our pipeline in the xcode job, by setting the path to it. However this does not work. What do you mean by share public repo?

**Comment by maxim-lobanov** [comment]
If it fails for you in public repository - give the link to repository.
If not - is it possible to create test public repository with workflow where this problem is reproduced and give the link.
Unfortunately, I can't reproduce it from my side.

P.S. For GitHub Actions, You can try to use [setup-xcode](https://github.com/marketplace/actions/setup-xcode-version) to switch Xcode to check if it works better

**Comment by DjCantor** [comment]
I am using it from Azure Devops. Do you know maybe where can I get support for it?

**Comment by maxim-lobanov** [comment]
Okay, let's try to localize the problem.
Could you please try to add `ls -la /Applications | grep "Xcode"` line (bash) as a first step of your build. Then check the output for build that is trying to run on 11.7 instead of 12.0.

If output contains `Xcode_12.app` folder, it means Xcode 12 is presented on image and it is an issue with Azure DevOps task (should be reported in  https://github.com/microsoft/azure-pipelines-tasks)
If `Xcode_12.app` is not presented on image, we will validate and fix it from image side.

**Comment by DjCantor** [comment]
Yes,  it's an issue with the Azure Devops than, because I see all the newer Xcode versions. Thank you for your help!

**Comment by miketimofeev** [comment]
The new image with Xcode 12.0.1 as the default one has been deployed

**Comment by brian-g** [comment]
My MacOS agent (Azure DevOps) still doesn't have Xcode 12 installed.


Version | Build | Path
-- | -- | --
11.3.1 (default) | 11C505 | /Applications/Xcode_11.3.1.app
11.3 | 11C29 | /Applications/Xcode_11.3.app
11.2.1 | 11B500 | /Applications/Xcode_11.2.1.app
11.2 | 11B52 | /Applications/Xcode_11.2.app
11.1 | 11A1027 | /Applications/Xcode_11.1.app
11.0 | 11A420a | /Applications/Xcode_11.app
10.3 | 10G8 | /Applications/Xcode_10.3.app
10.2.1 | 10E1001 | /Applications/Xcode_10.2.1.app
10.2 | 10E125 | /Applications/Xcode_10.2.app
10.1 | 10B61 | /Applications/Xcode_10.1.app
10.0 | 10A255 | /Applications/Xcode_10.app
9.4.1 | 9F2000 | /Applications/Xcode_9.4.1.app

**Comment by maxim-lobanov** [comment]
> My MacOS agent (Azure DevOps) still doesn't have Xcode 12 installed.
> 
> Version	Build	Path
> 11.3.1 (default)	11C505	/Applications/Xcode_11.3.1.app
> 11.3	11C29	/Applications/Xcode_11.3.app
> 11.2.1	11B500	/Applications/Xcode_11.2.1.app
> 11.2	11B52	/Applications/Xcode_11.2.app
> 11.1	11A1027	/Applications/Xcode_11.1.app
> 11.0	11A420a	/Applications/Xcode_11.app
> 10.3	10G8	/Applications/Xcode_10.3.app
> 10.2.1	10E1001	/Applications/Xcode_10.2.1.app
> 10.2	10E125	/Applications/Xcode_10.2.app
> 10.1	10B61	/Applications/Xcode_10.1.app
> 10.0	10A255	/Applications/Xcode_10.app
> 9.4.1	9F2000	/Applications/Xcode_9.4.1.app

@brian-g  Based on the list of Xcode, you use MacOS 10.14.
New Xcode versions are installed only on MacOS 10.15. Please take a look at readme for details: https://github.com/actions/virtual-environments/tree/main/images/macos

**Comment by brian-g** [comment]
Thanks. After much frustration, I realized we were using the legacy Mac OS Agent rather than Azure Pipelines.

**Comment by EwoutH** [comment]
Now that Xcode 12.2 is being added (in #2054), can we discuss a date when it becomes the default version?

**Comment by maxim-lobanov** [comment]
Xcode 12.2 will become default on 30 November: https://github.com/actions/virtual-environments/issues/2056
But I strongly suggest to not depend on default Xcode and always specify Xcode that you need to build application.
Otherwise, you might be broken in future, if not adapt your app to new Xcode quickly.

**Comment by loveorhatecxy-png** [comment]
> > Můj agent pro MacOS (Azure DevOps) stále nemá nainstalovaný Xcode 12.
> > Version Build Path 
> > 11.3.1 (default) 11C505 /Applications/Xcode_11.3.1.app 
> > 11.3 11C29 /Applications/Xcode_11.3.app 
> > 11.2.1 11B500 /Applications/Xcode_11.2.1.app 
> > 11.2 11B52 /Applications/Xcode_11.2.app 
> > 11.1 11A1027 /Applications/Xcode_11.1.app 
> > 11.0 11A420a /Applications/Xcode_11.app 
> > 10.3 10G8 /Applications/Xcode_10.3.app 
> > 10.2.1 10E1001 /Applications/Xcode_10.2.1.app 
> > 10.2 10E125 /Applications/Xcode_10.2.app 
> > 10.1 10B61 /Aplikace/Xcode_10.1.app 
> > 10.0 10A255 /Aplikace/Xcode_10.app 
> > 9.4.1 9F2000 /Aplikace/Xcode_9.4.1.app
> 
> [@brian-g](https://github.com/brian-g) Na základě seznamu Xcode používáte MacOS 10.14. Nové verze Xcode se instalují pouze na MacOS 10.15. Podrobnosti naleznete v souboru readme: https://github.com/actions/virtual-environments/tree/main/images/macos
