### ISSUE TITLE
Unable to get PyPy3 to install

### ISSUE THREAD

**Issue by Cyb3r-Jak3** [actions/virtual-environments#1716]
**Description**  
Pypy versions appear to be missing from the setup-python action but are but show as cached tools. This is causing jobs using pypy to fail,

**Area for Triage**:  
  contains: 'Python'
  addLabels: ['Area: Python']

**Question, Bug, or Feature?**:  

**Virtual environments affected**  
- [X] macOS 10.15
- [X] Ubuntu 16.04 LTS
- [X] Ubuntu 18.04 LTS
- [X] Ubuntu 20.04 LTS
- [X] Windows Server 2016 R2
- [X] Windows Server 2019

**Expected behavior**  
The virtual environment is able to use pypy and pypy3 to complete python tests

**Actual behavior**  
Get a failure reason:
```
Version pypy3.6.9 with arch x64 not found
The list of all available versions can be found here: https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json
```

I checked the link and there are no pypy versions there. However, all the READMEs for the virtual-environments have pypy3 listed. 

**Repro steps**  
Action that failed: https://github.com/Cyb3r-Jak3/html5validator/actions/runs/283323536. Link the workflow config: https://github.com/Cyb3r-Jak3/html5validator/blob/pypy3_support/.github/workflows/main.yml

Steps to reproduce:
1. Setup up the python action to use either pypy or pypy3 
2. Push the changes and the job will fail to run because it can not find the version.

**Comment by henryiii** [comment]
I've been using these for a while, they worked an hour ago: https://github.com/pybind/pybind11/runs/1196848139?check_suite_focus=true

Wrong spelling, perhaps?

I'd love to see 7.3.2, though. ;)

**Comment by henryiii** [comment]
Unlike normal Python, GHA can't install arbitrary versions of PyPy. It's hard to even write versions of pypy since there's 2 and now 3 (with 3.7 alpha) versions of Python mixed with the PyPy version.

**Comment by maxim-lobanov** [comment]
@Cyb3r-Jak3 , yes, @henryiii is absolutely right.
You can't specify exact pypy version as task input. It is by design for now.
See related code: https://github.com/actions/setup-python/blob/main/src/find-python.ts#L176

**Comment by Cyb3r-Jak3** [comment]
Yup, I was able to get it to work now. My issue is that when I was starting, I was converting from Travis CI. That format is `pypy` for `pypy2` and `pypy3` for `pypy3`.

Thanks all for your help!
