### ISSUE TITLE
Unable to download Spark in the windows-latest

### ISSUE THREAD

**Issue by dclong** [actions/virtual-environments#1722]
**Description**  
A clear and concise description of what the bug is, and why you consider it to be a bug.
My GitHub action workflow needs to download Spark from https://archive.apache.org/dist/spark/spark-3.0.1/spark-3.0.1-bin-hadoop3.2.tgz using the standard Python library `urllib`. The pipeline always succeed on `ubuntu-latest` but always fails on `windows-latest`.

**Area for Triage**:  

**Question, Bug, or Feature?**:  

Bug

**Virtual environments affected**  
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Ubuntu 20.04 LTS
- [x] Windows Server 2016 R2
- [x] Windows Server 2019

**Expected behavior**  
Download Spark from the URL https://archive.apache.org/dist/spark/spark-3.0.1/spark-3.0.1-bin-hadoop3.2.tgz using the Python library `urllib` should work without issues. 

**Actual behavior**  
Fails to download.

**Repro steps**  
A description with steps to reproduce the issue. If your have a public example or repo to share,
please provide the link.

Check the workflow at https://github.com/dclong/xinstall/runs/1203698201?check_suite_focus=true.

**Comment by dsame** [comment]
It looks apache mirros have some downtime now, i checked the URL's and some of them either have certificate problems or refuse to connect

```
 curl -I https://apache.mirrors.hoobly.com/spark/spark-3.0.1/spark-3.0.1-bin-hadoop3.2.tgz
curl: (60) SSL certificate problem: self signed certificate
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```

**Comment by dclong** [comment]
@dsame I confirm that it is no longer an issue any more. Thank you very much!
