### ISSUE TITLE
Update/Add Xcode 12 beta 2

### ISSUE THREAD

**Issue by Steven0351** [actions/virtual-environments#1725]
The Xcode 12 beta 2 bundled Swift toolchain contains a patch for the Swift Package Manager that prevents Swift Package tests from crashing when accessing Swift Package resources (aka files bundled with the package): https://github.com/apple/swift-package-manager/pull/2905

Not sure if this is already on the todo list, but it would be much appreciated if this could be added.

**Tool information**
- Tool name: Xcode 12.2 Beta 2 (build 12B5025f)
- Tool license: Freeware with open-source components (Or at least that's what Wikipedia says...)
- Add or update? Update
- Desired version: 12.2 Beta 2 (build 12B5025f)
- Approximate size: 28 GB

**Area for Triage**: Apple

**Question, Bug, or Feature?**: Feature

**Virtual environments affected**
- [x] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Ubuntu 20.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Can this tool be installed during the build?**
No

**Tool installation time in runtime**
.xip's are known to take eons to decompress, but mileage may vary

**Are you willing to submit a PR?**
N/A

**Comment by maxim-lobanov** [comment]
@Steven0351 , it is in our TO-DO list.
It should be deployed during this week

**Comment by maxim-lobanov** [comment]
Hello!
New image with Xcode 12.2 beta 2 has been deployed recently. Please let us know if you have any troubles with it
