### ISSUE TITLE
GitHub Action - Workflow - Python Package Using Conda

### ISSUE THREAD

**Issue by BrightRan** [actions/virtual-environments#1732]
Associated GitHub Community: https://github.community/t/github-action-workflow-python-package-using-conda/135322

The customer created a workflow (see [here](https://github.com/psilons/pypigeonhole-simple-utils/blob/master/.github/workflows/python-package-conda.yml)) with a conda [environment.yaml](https://github.com/psilons/pypigeonhole-simple-utils/blob/master/environment.yaml) to install some 3rd-party libs.
All the 3rd-party libs look like have been installed successfully, but when using these 3rd-party libs in the subsequent steps, it failed with error like as this:
> ModuleNotFoundError: No module named 'socks'
ModuleNotFoundError: No module named 'Crypto'
. . .

It seems that the conda environment is not activated on the GitHub-hosted runner machine. the customer tried to activate but failed.
The same steps can work fine when the customer run them on the local.

Looks like, there are some issues or restrictions on the virtual environments for the GitHub-hosted runners to prevent the conda environment from being activated.

**Comment by dmitry-shibanov** [comment]
Hello @BrightRan ,as I saw in the github community conversation customer has got an appreciate [answer](https://github.community/t/github-action-workflow-python-package-using-conda/135322/5) for his issue, that it could be resolved by running `conda run`. I think the issue can be closed, but feel free to reopen it if you have any concerns.
