### ISSUE TITLE
Update gh mac homebrew formula name

### ISSUE THREAD

**Issue by samcoe** [actions/virtual-environments#1734]
**Tool information**
- Tool name: gh
- Tool license: MIT License
- Add or update? Update
- Desired version: Latest
- Approximate size: 

**Area for Triage**:

Bug

**Question, Bug, or Feature?**:

`gh` is currently being installed using the homebrew formula `github/gh/gh` 

https://github.com/actions/virtual-environments/blob/7fe98f7934a70fc53b394f3f494ae6a25d6bedf2/images/macos/provision/core/commonutils.sh#L22

That formula name is outdated since `gh` got moved into homebrew core formulae (https://github.com/Homebrew/homebrew-core/blob/38d4781f10b61240c109ad08c4824e1c01f7ca82/Formula/gh.rb). It is now recommend it be installed using just the `gh` formula name. Can we update the installer script to use the new formula name?

**Virtual environments affected**
- [x] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Ubuntu 20.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Can this tool be installed during the build?**

**Tool installation time in runtime**

**Are you willing to submit a PR?**

Yes 👍

**Comment by maxim-lobanov** [comment]
@samcoe Sure! Feel free to submit PR

**Comment by maxim-lobanov** [comment]
@samcoe , PR has been merged. The next image will use gh cli from updated formulae
