### ISSUE TITLE
Obsolete Android build-tools packages will be removed from Ubuntu images on October, 20

### ISSUE THREAD

**Issue by AlenaSviridenko** [actions/virtual-environments#1743]
Hey 👋!

Currently, we are installing a bunch of Android build-tools packages that are marked as obsolete. We are going to stop installing them on images starting of October, 20.

List of packages to be removed:
- 17.0.0
- 18.0.1, 18.1.0, 18.1.1
- 19.0.0, 19.0.1, 19.0.2, 19.0.3
- 21.0.0, 21.0.1, 21.0.2, 21.1.0, 21.1.1
- 22.0.0
- 23.0.0

If you have any concerns or questions — please let us know through this issue.
Thanks!

**Comment by al-cheb** [comment]
PR: https://github.com/actions/virtual-environments/pull/1810

**Comment by hanaputra** [comment]
baejahok@gmail.com

**Comment by al-cheb** [comment]
The Obsolete Android build-tools packages have been remove in a new image rollout(`20201015.1`) for Ubuntu 16/18.
Ubuntu1804 - https://github.com/actions/virtual-environments/blob/releases/ubuntu18/20201015/images/linux/Ubuntu1804-README.md

Ubuntu1604 - https://github.com/actions/virtual-environments/blob/releases/ubuntu16/20201015/images/linux/Ubuntu1604-README.md
