### ISSUE TITLE
C++ boost default installation missing 'boost/uuid/uuid.hpp'

### ISSUE THREAD

**Issue by ritchiecarroll** [actions/virtual-environments#1744]
**Description**  
The default C++ boost installation missing is missing `uuid` include only headers, i.e., `C:\hostedtoolcache\windows\Boost\1.72.0\x86_64\boost\boost\uuid\uuid.hpp`

**Area for Triage**:  
C/C++

**Question, Bug, or Feature?**:  
Bug

**Virtual environments affected**  
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Ubuntu 20.04 LTS
- [ ] Windows Server 2016 R2
- [X] Windows Server 2019

Other environments likely affected.

**Expected behavior**  
When compiling with boost, expecting `uuid.hpp` to be available.

**Actual behavior**  
`uuid` boost include only headers are not included with default boost install.

**Repro steps**  
https://github.com/sttp/cppapi/actions/runs/289098801/workflow
https://github.com/sttp/cppapi/runs/1208301764?check_suite_focus=true

**Comment by dsame** [comment]
@ritchiecarroll, i advise you too change your settings
```
echo "::set-env name=BOOST_INCLUDEDIR::${{ env.BOOST_ROOT }}\boost\include"
```
to
```
echo "::set-env name=BOOST_INCLUDEDIR::${{ env.BOOST_ROOT }}\include\boost"
```

JFI, the uuid header files reside in these paths:

BOOST_ROOT_1_72_0/include/boost/uuid/uuid.hpp
BOOST_ROOT_1_72_0/include/boost-1_72/boost/uuid/uuid.hpp
BOOST_ROOT_1_72_0/libs/uuid/include/boost/uuid/uuid.hpp

Please confirm, this help

**Comment by Whoerr** [comment]
echo "::set-env name=BOOST_INCLUDEDIR::${{ env.BOOST_ROOT }}\boost\include"
to
echo "::set-env name=BOOST_INCLUDEDIR::${{ env.BOOST_ROOT }}\include\boost"
JFI, the uuid header files reside in these paths:
BOOST_ROOT_1_72_0/include/boost/uuid/uuid.hpp
BOOST_ROOT_1_72_0/include/boost-1_72/boost/uuid/uuid.hpp
BOOST_ROOT_1_72_0/libs/uuid/include/boost/uuid/uuid.hpp

**Comment by dsame** [comment]
Hi @ritchiecarroll, i am closing the issue because there's no response.

Please feel free to open new issue or re-open this one in case of any problem

**Comment by ritchiecarroll** [comment]
Thanks - was working on other things and forgot about this one. Looks like changing the include folder helped.

Appreciate the hint.

Ritchie
