### ISSUE TITLE
Add kubelogin

### ISSUE THREAD

**Issue by freeman** [actions/virtual-environments#1746]
**Tool information**
- Tool name: Kubelogin
- Tool license: MIT
- Add or update? Add
- Desired version: latest (0.0.6)
- Approximate size: 15MB
- If this is an add request:
  - Brief description of tool: Allows non interactive logins to AKS clusters with managed AAD integration
  - URL for tool's homepage: https://github.com/Azure/kubelogin/
  - Provide a basic test case to validate the tool's functionality: 

**Area for Triage**:

**Question, Bug, or Feature?**:

**Virtual environments affected**
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Ubuntu 20.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Can this tool be installed during the build?**
probably by downloading the latest release from github

**Tool installation time in runtime**
should be quick, just unpack the binary and add to path

**Are you willing to submit a PR?**

**Comment by dibir-magomedsaygitov** [comment]
Hello, @freeman!
Thank you for your request. Could you please specify on what OS versions you would liked to add this tool?

**Comment by freeman** [comment]
Hello @dibir-magomedsaygitov,

I think this tool is worth having for all platforms. I use  `ubuntu-latest` myself.

**Comment by AlenaSviridenko** [comment]
Hi @freeman,
tool installation in runtime takes 1-2 sec. Considering this fact and a tool size, we would like not to add it to the image. Below are the steps to install it in runtime:
```
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run a multi-line script
        run: |
          curl -LO "https://github.com/Azure/kubelogin/releases/download/v0.0.6/kubelogin-linux-amd64.zip"
          sudo unzip -j "kubelogin-linux-amd64.zip" -d /usr/local/bin
          rm -f "kubelogin-linux-amd64.zip"
          kubelogin --version
```
Does it work for you?
Please, let me know if you have any questions.
Thanks.

**Comment by freeman** [comment]
I thnk you're right. In fact a simple:
```
sudo az aks install-cli
```
will be ok.

Thanks for considering,

**Comment by dibir-magomedsaygitov** [comment]
In this case I'm closing this issue. If you will have any questions, feel free to contact us.
