### ISSUE TITLE
Support for Gen2 Azure VMs

### ISSUE THREAD

**Issue by mmuffins** [actions/virtual-environments#1754]
Hi,
the images for windows and linux are currently built using VM sizes Standard_D4_v2 and Linux Standard_DS2_v2, respectively. Are there any plans (or concerns) to switch to a comparable VM size that supports Azure VM generation 2, e.g. Standard_DS4_v2?

While it probably wouldn't have any direct advantages for the created image, it would future-proof it and give organizations the choice of what generation to use for their own infrastructure.

**Comment by maxim-lobanov** [comment]
Hello @mmuffins , As I can see all Ubuntu images are already use `Standard_DS2_v2`.
As for the Windows images, Windows16 already uses `Standard_DS4_v2` but Windows19 still uses `Standard_D4_v2` for some reason. We have switched it to `Standard_DS4_v2` in https://github.com/actions/virtual-environments/pull/1845
