### ISSUE TITLE
Xcodes are not registered in the central metadata store

### ISSUE THREAD

**Issue by ABBAPOH** [actions/virtual-environments#1760]
**Description**  
We used to use the mdfind tool to find Xcodes installed in the system using the following command:
$ /usr/bin/mdfind "kMDItemCFBundleIdentifier == 'com.apple.dt.Xcode'"

However, this command no longer returns anything, i.e. Xcodes are not registered in the system.

See https://github.com/ABBAPOH/qbs/runs/1221991445?check_suite_focus=true as an example.

**Area for Triage**:  
Area: Apple

**Question, Bug, or Feature?**:  
Bug

**Virtual environments affected**  
- [*] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Ubuntu 20.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Expected behavior**  
I expect mdfind to return the list of installed xcodes

**Actual behavior**  
mdfind output is empty.

**Repro steps**  
1. See
https://github.com/ABBAPOH/qbs/blob/995b3ba56fe54229c82246813d2dcf06fd95fc7a/.github/workflows/main.yml
2. Try this command locally:
$ /usr/bin/mdfind "kMDItemCFBundleIdentifier == 'com.apple.dt.Xcode'"
/Applications/Xcode.app

**Comment by miketimofeev** [comment]
Hi @ABBAPOH!
It's probably related to this change
https://github.com/actions/virtual-environments/blob/17d233cac55acb75f4df25a77070e5866ee6b635/images/macos/provision/configuration/configure-machine.sh#L32
We'll try to figure out a better way to reduce CPU usage rather than disabling mdutil completely.

**Comment by dibir-magomedsaygitov** [comment]
Hello, @ABBAPOH!
We reverted out recent change back. New images with enabled spotlight indexing should be available with the next week's roll-out. I'll post update message.

**Comment by ABBAPOH** [comment]
Sounds great, thanks!

**Comment by al-cheb** [comment]
Hello, @ABBAPOH 
The new image with the  fix  (20201017.1) has been deployed - https://github.com/actions/virtual-environments/blob/main/images/macos/macos-10.15-Readme.md
