### ISSUE TITLE
Update gh windows installer script

### ISSUE THREAD

**Issue by samcoe** [actions/virtual-environments#1765]
**Tool information**
- Tool name: gh
- Tool license: MIT License
- Add or update? Update
- Desired version: Latest
- Approximate size: 

**Area for Triage**:
Windows

**Question, Bug, or Feature?**:
Question

`gh` is currently being installed on Windows using Chocolatey

https://github.com/actions/virtual-environments/blob/0f6fba462ae50d9f3d88046004324403a146664a/images/win/scripts/Installers/Install-GitHub-CLI.ps1#L6

The Chocolatey package is not maintained directly the CLI team and could be a potential security risk. The `gh` [releases](https://github.com/cli/cli/releases/tag/v1.1.0) include an `exe` and an `msi` that could be used directly to ensure the authenticity of the package being installed. Can we update the installer script to use the official `gh` package instead of installing using Chocolatey?

**Virtual environments affected**
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Ubuntu 20.04 LTS
- [x] Windows Server 2016 R2
- [x] Windows Server 2019

**Can this tool be installed during the build?**

**Tool installation time in runtime**

**Are you willing to submit a PR?**

Yes 👍

**Comment by maxim-lobanov** [comment]
Pull-Request has been merged. Next images will consume GH CLI from GH Releases. Thank you for contribution.
