### ISSUE TITLE
Windows Server 2019 Hosted Agents : Error CS0019: Operator '==' cannot be applied to operands of type 'T' and 'default'

### ISSUE THREAD

**Issue by richshadman** [actions/virtual-environments#177]
With no change in our code, as of today, we started getting the following error :

Error CS0019: Operator '==' cannot be applied to operands of type 'T' and 'default'

The bit of code is a generic function with an unconstrained type parameter :

```
private T ExecuteCircuit<T>(Func<T> main, Func<T> fallback)
        {
            T res;
            if (!CanConnect())
            {
                return fallback();
            }
            try
            {
                res = main();
            }
            catch (Exception e)
            {
                Log(NLog.LogLevel.Error, $"Exception processing main path, using fallback: {e.Message}");
                res = default;
            }

            if (res == default) //no result from main approach
            {
                TripCircuit();
                res = fallback();
            }
            return res;
        }
```

The error is failing on if (res == default). This does not fail on any developer workstations and was working in the hosted environment yesterday.

Last working agent version: 2.160.1

Current failing agent version: 2.163.1

I found a related ticket  in the roslyn compiler : https://github.com/dotnet/roslyn/issues/38568

My inference is that this issue was reintroduced in the current agent version?

This issue is currently holding us back as all of our builds are failing.

**Comment by richshadman** [comment]
This issue is apparently in VS 16.4 -> https://developercommunity.visualstudio.com/content/problem/847390/since-164-problem-with-defaut-cs0019.html

**Comment by AlenaSviridenko** [comment]
Closing this issue since no more customers raise this issue.
If the issue still persists, please, feel free to open new ticket.
