### ISSUE TITLE
Macos OpenSSL linking appears broken

### ISSUE THREAD

**Issue by chvck** [actions/virtual-environments#1770]
**Description**  
We have an action which builds a rust project, as a part of this we have to build a C library which tries to link to OpenSSL. Somewhere between 14 and 17 September our build stopped working on Github Actions. I see that [this commit](https://github.com/actions/virtual-environments/commit/9afcb1503a1d367b713aafd3146c945d34fe70d7#diff-94d9decca4b64333b34283f082ce04bb) was created on the 15 September which tinkers with some OpenSSL things. Our change on the 17 September was a docs only change but is where we started to see a failing build (no other changes between 14 and 17).

An example of our failing build can be found at [https://github.com/couchbaselabs/couchbase-shell/actions/runs/295438382](https://github.com/couchbaselabs/couchbase-shell/actions/runs/295438382).

I've tried hardcoding various OpenSSL environment variables and brew installs of OpenSSL but the linker always fails. I'm unsure this is a bug report so much as a question of why has this change triggered this behaviour? There's nothing jumping out at me in the change that should have caused this.

**Area for Triage**:  
Apple

**Question, Bug, or Feature?**:  
Question

**Virtual environments affected**  
- [ x ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Ubuntu 20.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Expected behavior**  
Linking to OpenSSL succeed.

**Actual behavior**  
Linking to OpenSSL fail.

**Repro steps**  
A description with steps to reproduce the issue. If your have a public example or repo to share,
please provide the link.

1. See [https://github.com/couchbaselabs/couchbase-shell/actions/runs/295438382](https://github.com/couchbaselabs/couchbase-shell/actions/runs/295438382)

**Comment by vsafonkin** [comment]
Hello @chvck, thank you for your report. Probably, Rust library linker cannot resolve openssl libs through symlink `/usr/local/Cellar/openssl -> /usr/local/Cellar/openssl@1.0.2t`. As a workaround you can try to add next step for macOS into your workflow:
```
rm -rf /usr/local/Cellar/openssl
ln -sf /usr/local/Cellar/openssl@1.0.2t/1.0.2t /usr/local/opt/openssl
ln -sf /usr/local/Cellar/openssl@1.0.2t/1.0.2t/bin/openssl /usr/local/bin/openssl
```
I've checked it on my test workflow and build was successful: https://github.com/vsafonkin/test-repo/runs/1240480862?check_suite_focus=true

We will continue to investigate this issue.

**Comment by chvck** [comment]
Hi @vsafonkin thanks for replying. I tried your workaround and it didn't work but given that you said 1.0.2t will be removed anyway and I know that we already support 1.1. I tried the following and it worked:

```
rm -rf /usr/local/Cellar/openssl
ln -sf /usr/local/Cellar/openssl@1.1/1.1.1g /usr/local/opt/openssl
ln -sf /usr/local/Cellar/openssl@1.1/1.1.1g/bin/openssl /usr/local/bin/openssl
```

Thank you for your help!

**Comment by vsafonkin** [comment]
@chvck , great! I've closed this issue, feel free reopen it if you have any problems. Thank you!
