### ISSUE TITLE
Possible issue with Ubuntu 18.04 image 20201004.1 for php projects

### ISSUE THREAD

**Issue by matks** [actions/virtual-environments#1773]
**Description**  

Hi, on [PrestaShop\PrestaShop](https://github.com/prestashop/prestashop) we noticed yesterday multiple GitHub Actions checks failing for no weird reasons. The failing Actions were the ones running [phpstan](https://github.com/phpstan/phpstan). After investigation, it seems that the issues happened on Pull Requests where the GA was run using latest 18.04 image 20201004.1 . With previous image 20200920.1 there was no issues.

**Area for Triage**:  PHP

**Question, Bug, or Feature?**:  Bug

**Virtual environments affected**  
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [x] Ubuntu 18.04 LTS
- [ ] Ubuntu 20.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Expected behavior**  

Unless there was a notable breaking change in the software being used inside these images, I expect the same GA to provide the same output with both 20200920.1 and 20201004.1 versions.

**Actual behavior**  

With 20201004.1 image we observe a `Fatal error: require_once(): Failed opening required` being triggered by phpstan.

**Note**: in order for our CI not to be broken by this issue, we switched to Ubuntu 20.04 for the runner.

**Repro steps**  

[This PR is an example of failing build](https://github.com/PrestaShop/PrestaShop/pull/21369/). If you want to reproduce the issue, you can open a PR using base branch `develop` and choose `ubuntu-latest` runner. This should fail just like https://github.com/PrestaShop/PrestaShop/pull/21369/

**Comment by dsame** [comment]
Hi @matks ,

I've checked the required file exists and can be required from PHP script. It seems the problem is with 'require_once' and phpstan logic that attempts to read the class definition more than once
Please try to contact phpstan support to solve the problem.

**Comment by matks** [comment]
> Hi @matks ,
> 
> I've checked the required file exists and can be required from PHP script. It seems the problem is with 'require_once' and phpstan logic that attempts to read the class definition more than once
> Please try to contact phpstan support to solve the problem.

Hi, thank you for the answer !

[We already contacted phpstan maintainer](https://github.com/phpstan/phpstan/issues/3929) and he thinks he knows broadly what the issue is.

However if I look at the facts:
- the file that is, supposedly, responsible for the bad phpstan behavior has been inside PrestaShop for years and did not cause any issues with GitHub Ubuntu 18.04 image 20200920.1
- if I run the very same GA setup with current Ubuntu 16.04 image, no issues
- if I run the very same GA setup with current Ubuntu 20.04 image, no issues

This makes me believe there might be something weird with this 20200920.1 Ubuntu 18.04 image. What exactly ? I dont have the answer. I checked the diff and I see nothing that should trigger such a change.

I understand you cannot take action on such a vague bug report so feel free to close it. I just wanted to provide a warning about this 20200920.1 image. Maybe more issues will arise from GitHub Actions being run with it.

**Comment by miketimofeev** [comment]
@matks thanks for the update! We've started a new image deployment today. Could you check sometime by the end of the week if the issue still persists on the new image?

**Comment by matks** [comment]
@miketimofeev I will 😉

**Comment by matks** [comment]
@miketimofeev It works for us 👍 https://github.com/PrestaShop/PrestaShop/pull/21569 latest image runs correctly our GitHub Action
