### ISSUE TITLE
[macOS] Default Ruby version will be changed to 2.7 on October, 26

### ISSUE THREAD

**Issue by AlenaSviridenko** [actions/virtual-environments#1775]
### Breaking changes
Default Ruby will be upgraded from 2.6 to 2.7 on MacOS images

### Target date
Deployment of these changes will be started on 28 October and will take a few days.

### The motivation for the changes
Ruby 2.7 is current stable version and it is required for a lot of gems so we would like to set it by default.

### Possible impact
If you use default Xcode version and your project is not compatible with Xcode 12.0.1, your build can be broken.

- [x] MacOS 10.13
- [x] MacOS 10.14
- [x] MacOS 10.15

### Mitigation ways
Please, consider using [ruby/setup-ruby](https://github.com/ruby/setup-ruby) (for GitHub Actions) or [UseRuby](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/tool/use-ruby-version?view=azure-devops) (for Azure Pipelines) to switch version of Ruby to 2.6 or any other available.

**Comment by miketimofeev** [comment]
Image with Ruby 2.7 as the default has been deployed
