### ISSUE TITLE
Jobs on Windows fail without logs sometimes

### ISSUE THREAD

**Issue by tysonite** [actions/virtual-environments#1776]
Sometimes, jobs on Windows fail without logs:
![image](https://user-images.githubusercontent.com/196535/95575329-2d095f00-0a37-11eb-8bcc-14fdf8551b31.png)

Examples:
- https://github.com/robotframework/robotframework/runs/1230597456
- https://github.com/robotframework/robotframework/pull/3703/checks?check_run_id=1230632395

This might be related to similar issues on macOS: https://github.com/actions/virtual-environments/issues/841 or https://github.com/actions/virtual-environments/issues/736

**Comment by ChrisWish** [comment]
Looks like Mms views the request as successful, but Actions views it as abandoned which might be related to the failure, but doesn't help with the logs. 

ProductTrace
| where PreciseTimeStamp > ago(7d)
| where OrchestrationId contains 'fe0373b3-a054-444f-8543-79f269e6ed31.test_using_builtin_python.windows-latest_3_5'
//| where OrchestrationId contains 'fe0373b3-a054-444f-8543-79f269e6ed31'

MachinePoolRequestHistory
| where OrchestrationId contains 'fe0373b3-a054-444f-8543-79f269e6ed31.test_using_builtin_python.windows-latest_3_5'

AgentPoolRequestHistory
| where PreciseTimeStamp > ago(7d)
| where HostId == '5bd11d6c-446e-406a-b0aa-4ebb7ddcce03'
| where Result != 'Succeeded'
| where AgentSpecification contains "windows-latest"
| where OrchestrationId == 'fe0373b3-a054-444f-8543-79f269e6ed31.test_using_builtin_python.windows-latest_3_5'

**Comment by konradpabjan** [comment]
Hey @tysonite 

I took a look at the failure! The runner abruptly disconnected which is why the step appears to have hanged and their aren't any logs available at the step.

This is a different error than the errors we've seen with our Mac VMs. We have a team internally investigating this. As a heads up internal telemetry is showing this error to come up very very infrequently. The RCA is unfortunately still unknown on our end 🤔

**Comment by maxim-lobanov** [comment]
@tysonite , do you still experience these issues?
When you have seen repro last time?

**Comment by tysonite** [comment]
I haven't looked into this since I reported it.

As far as I see, issue has been confirmed from github end, no point to look for me further unless there is confirmation that fix was applied.

**Comment by konradpabjan** [comment]
Thanks for initially opening this issue @tysonite 

There can be various causes on our end that lead to jobs failing with no logs. Over the last few months we've made a host of improvements to reduce the chances of these errors happening. For now I'm going to close out this issue. If this happens again please open up a new issue and you can ping me.
