### ISSUE TITLE
Add virtual environment: macOS Big Sur (11.0)

### ISSUE THREAD

**Issue by mxschmitt** [actions/virtual-environments#1781]
I had a conversation with the GitHub support about macOS Big Sur support in Github Actions, opening an issue publicly was recommended so other users find the answer directly over Google.

Currently there is only macOS Catalina supported as a [virtual environment](https://docs.github.com/en/free-pro-team@latest/actions/reference/specifications-for-github-hosted-runners#supported-runners-and-hardware-resources). MacOS Big Sur (11.0) will get released soon and having it available would help users to test their software on it.

Is there already a public tracked issue existing?

**Comment by maxim-lobanov** [comment]
Hello @mxschmitt , we definitely have plans to add MacOS Big Sur to GitHub Actions but I can't provide ETA for now.
I will update this issue as soon as I have update.

**Comment by maxim-lobanov** [comment]
Hello everyone!
Just an update, MacOS Big Sur (11.0) is available in GitHub Actions 🚀 
Please pay attention that currently, it is in preview state so it could contain some issues. Feel free to report them and we will take a look.

Details can be found in announcement issue: https://github.com/actions/virtual-environments/issues/1814

**Comment by mxschmitt** [comment]
@maxim-lobanov great news! Works 😀
