### ISSUE TITLE
Download MacOS image

### ISSUE THREAD

**Issue by mapo80** [actions/virtual-environments#1783]
Guys I have a question for you, I want to download macOS image to run it on my Mac, because it has everything I need to build iOS app. Is it possible? Where can I download it?

Thanks.

**Comment by maxim-lobanov** [comment]
Hello @mapo80 , Unfortunately, it is not possible. We can't distribute the built image due to legal issues.
Related issue: https://github.com/actions/virtual-environments/issues/176

**Comment by mapo80** [comment]
Hi @maxim-lobanov, I understand. Can I create it from scratch using your build system? Is there a tutorial to do this?

**Comment by maxim-lobanov** [comment]
We just open-sourced MacOS image generation code a few weeks ago so don't have guides yet. It could be a bit tricky but I think that the simplest way to configure the same environment locally:
1) Take clean MacOS 10.15 machine
2) `git clone https://github.com/actions/virtual-environments.git`
3) Run all image-generation scripts from `images/macos` folder one by one

Notes:
- The list of all scripts is defined in template file in [provisioners section](https://github.com/actions/virtual-environments/blob/main/images/macos/templates/macOS-10.15.json#L41). It is the most interesting section for you.
- Probably, you would like to edit [toolset](https://github.com/actions/virtual-environments/blob/main/images/macos/toolsets/toolset-10.15.json) and exclude some Xcode versions from installation. We install about 11 Xcode versions that could be very painful locally.
- You can skip some tools that are not needed for you

**Comment by mapo80** [comment]
@maxim-lobanov Thanks very much for your detailed answer.

**Comment by joyhui** [comment]
@maxim-lobanov : I am trying to build the image for macOS. But there are too many scripts under images/macos. Do we have a better solution now?

**Comment by maxim-lobanov** [comment]
@joyhui , unfortunately, no better solution for now. I think you can skip scripts and tools that you don't need on your own image.
