### ISSUE TITLE
Add gfortan-10

### ISSUE THREAD

**Issue by junghans** [actions/virtual-environments#1796]
**Tool information**
- Tool name: gfortran
- Tool license: GPL
- Add or update? update
- Desired version: 10.1.0 (to keep in sync with gcc)
- Approximate size: 

**Area for Triage**:

**Question, Bug, or Feature?**:

See #202 

**Virtual environments affected**
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [x] Ubuntu 18.04 LTS
- [x] Ubuntu 20.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Can this tool be installed during the build?**

**Tool installation time in runtime**

**Are you willing to submit a PR?**

**Comment by mathomp4** [comment]
As a lurker, it would be nice if the macOS image also got gfortran/gcc 10. I think that Ubuntu 18 and Ubuntu 20 have it now, but I'm not smart enough to figure out how to get my matrix right for "if not macos, run gcc-10"...

**Comment by maxim-lobanov** [comment]
No concerns to pre-install it. Moved to the our backlog

**Comment by andy-mishechkin** [comment]
Hello @junghans.
GFortran-10 has been added to Ubuntu 18/20 images. You can use it after the next version deployment (about end of the next week).
If you'll find any issues - feel free to ping me in this ticket

**Comment by mathomp4** [comment]
> GFortran-10 has been added to Ubuntu 18/20 images. You can use it after the next version deployment (about end of the next week).
> If you'll find any issues - feel free to ping me in this ticket

@andy-mishechkin What should I (as an interested gfortran user, see #2176) look for to know when I can use it? Is it when there is a release that isn't "Pre-release" on the Releases page?

**Comment by maxim-lobanov** [comment]
@mathomp4 , yes, you can start use it as soon as "prerelease" label is removed. prerelease means that deployment is still in progress and it can't be predicted if your build goes to updated machine or not

**Comment by andy-mishechkin** [comment]
I've checked gforttan-10 in Ubuntu18/20 images. It present there.
I think, we can close this ticket. If you'll find some issues - feel free to reopen and ping me.
Thank you!
