### ISSUE TITLE
Update Xcode to 12.0.1

### ISSUE THREAD

**Issue by bryansills** [actions/virtual-environments#1797]
**Tool information**
- Tool name: Xcode
- Tool license: ?
- Add or update?: Update
- Desired version: 12.0.1
- Approximate size: 

**Area for Triage**:
Area: Apple

**Question, Bug, or Feature?**:
Bug

**Virtual environments affected**
- [x] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Ubuntu 20.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Can this tool be installed during the build?**
No

**Tool installation time in runtime**
?

**Are you willing to submit a PR?**
Not at this time

**Comment by maxim-lobanov** [comment]
@bryansills , thank you for feature request.
We have investigated this feature request previously and decided to not install Xcode 12.0.1 to images because:
```
The single release not of Xcode 12.0.1 is:
- Opening the Developer Documentation window no longer causes Xcode to crash. (66690089)
Link: https://developer.apple.com/documentation/xcode-release-notes/xcode-12_0_1-release-notes

This update fixes an issue that could cause Xcode to crash when viewing documentation
As this appears to be the only change, it appears immaterial for CI environments, so continuing to build and release your apps with 12.0.0 will be perfectly fine. As far as I know, you can still publish releases to App Store using Xcode 12.0.0
```

Does it make sense to you? Could you please share additional context why we need to install Xcode 12.0.1?

**Comment by bryansills** [comment]
We are seeing an error like `Your app was built with an unsupported SDK or version of Xcode` when trying to upload our build to Fastlane. I believe that Apple might have removed support for the 12.0 version of Xcode.

**Comment by TutuNazarova** [comment]
Hello!
What is the latest Xcode version available?

**Comment by maxim-lobanov** [comment]
@TutuNazarova , https://github.com/actions/virtual-environments/blob/main/images/macos/macos-10.15-Readme.md#xcode

**Comment by maxim-lobanov** [comment]
@bryancross , we are going to replace Xcode 12.0.0 to 12.0.1 on next image. It should be rollout early next week

**Comment by renatosbueno** [comment]
Hello, @maxim-lobanov we are currently facing the same issue. Maybe can you provide some estimated date for this to be deployed/fixed? We need to deploy some improvements at maximum at the beginning of next week. 😕

**Comment by maxim-lobanov** [comment]
@renatosbueno , sorry for delay with deployment. Usually, it takes a few days for us to deploy image with new Xcode.
We had a few blocker issues recently and had to rollback previous image due to an issue with python3/pip3.
We are expecting new image to be deployed on Tue.

**Comment by al-cheb** [comment]
Hello, @bryansills 
The new image with Xcode 12.0.1(`20201017.1`) has been deployed - https://github.com/actions/virtual-environments/blob/main/images/macos/macos-10.15-Readme.md
