### ISSUE TITLE
Update/Add VulkanSDK

### ISSUE THREAD

**Issue by jherico** [actions/virtual-environments#18]
**Tool information**
- Tool name: LunarG Vulkan SDK
- Add or update? Add 
- Desired version: Latest (currently) 1.1.121
- Approximate size: 2 GB installled (on windows)
- If this is an add request:
  - Brief description of tool: Headers and libraries required for loading and accessing Vulkan functionality from a C/C++ based application.  Also includes a suite of tools for SPIRV work
  - URL for tool's homepage: https://vulkan.lunarg.com/

**Virtual environments affected**
- [X] macOS 10.14
- [X] Ubuntu 16.04 LTS
- [X] Ubuntu 18.04 LTS
- [X] Windows Server 2016 R2
- [X] Windows Server 2019

Note that the Ubuntu versions can probably be dealt with via a simple `apt-get`, but the Mac and Windows environments require running an interactive installer.

**Can this tool be installed during the build?**
Uncertain.  It's possible that the installer has an unattended mode that can be used but I've never tried to do so.  Some components included in the SDK (such as the SPIRV tooling) can be acquired via other means, such as using `vcpkg` to install the spirv-tools library.  However, it's worth noting that the `vcpkg` [port](https://github.com/microsoft/vcpkg/blob/master/ports/vulkan/portfile.cmake) for Vulkan specifically says 

> # Due to the complexity involved, this package doesn't install the Vulkan SDK.
> # It instead verifies that Vulkan is installed.
> # Other packages can depend on this package to declare a dependency on Vulkan.

Indicating that building the VulkanSDK from source is extremely non-trivial

**Are you willing to submit a PR?**
I'm uncertain what a PR could accomplish in this area, since the installation of the SDK is typically a manual process.  But sure, I'll submit a PR if someone can provide guidance on a mechanism and within my ability to fix.

**Comment by kudaba** [comment]
I was able to install it on windows during my builds with the following:
```yml
    - name: Setup Vulkan
      run: |
          Invoke-WebRequest -Uri "https://sdk.lunarg.com/sdk/download/1.1.126.0/windows/VulkanSDK-1.1.126.0-Installer.exe" -OutFile VulkanSDK.exe
          $installer = Start-Process -FilePath VulkanSDK.exe -Wait -PassThru -ArgumentList @("/S");
          $installer.WaitForExit();
```
It takes 2-2.5 minutes to run.

**Comment by alepauly** [comment]
Considering this can be installed as suggested above and maintenance could be an issue if we bake it in the environment, we won't add it. Thanks for suggesting it @jherico .

**Comment by kudaba** [comment]
That's a bit unsatisfying. I only shared a way to install it on windows, each other platform will have a different install process, and it can take up to 30% of my entire job (4 of 12 minute) so it's eating a ton of my monthly minutes. The time is a bit inconsistent, though, I've seen as low as 1 minute, but average seems to be 3 minutes looking at some historical builds.

**Comment by Nielsbishere** [comment]
I think it should be added too. At least the tools and lib/include files. The solution @kudaba mentioned didn't work for me, it completed but the %VULKAN_SDK% variable wasn't set on completion and therefore it couldn't complete for me.

**Comment by jadarve** [comment]
@kudaba step to install the SDK works correctly. Below is a step to install the most recent version

```yaml
    - name: Setup Vulkan
      run: |
          Invoke-WebRequest -Uri "https://sdk.lunarg.com/sdk/download/1.2.176.1/windows/VulkanSDK-1.2.176.1-Installer.exe" -OutFile VulkanSDK.exe
          $installer = Start-Process -FilePath VulkanSDK.exe -Wait -PassThru -ArgumentList @("/S");
          $installer.WaitForExit();
```

To use the SDK in another step, you need to manually set the `VULKAN_SDK` environment variable prior to using it:

```yaml
    - name: Use the Vulkan SDK
      run: |
          $Env:VULKAN_SDK = "C:/VulkanSDK/1.2.176.1"
          $Env:Path += ";C:/VulkanSDK/1.2.176.1/Bin"
          # your command goes here
```

**Comment by Kapilarny** [comment]
> @kudaba step to install the SDK works correctly. Below is a step to install the most recent version
> 
> ```yaml
>     - name: Setup Vulkan
>       run: |
>           Invoke-WebRequest -Uri "https://sdk.lunarg.com/sdk/download/1.2.176.1/windows/VulkanSDK-1.2.176.1-Installer.exe" -OutFile VulkanSDK.exe
>           $installer = Start-Process -FilePath VulkanSDK.exe -Wait -PassThru -ArgumentList @("/S");
>           $installer.WaitForExit();
> ```
> 
> To use the SDK in another step, you need to manually set the `VULKAN_SDK` environment variable prior to using it:
> 
> ```yaml
>     - name: Use the Vulkan SDK
>       run: |
>           $Env:VULKAN_SDK = "C:/VulkanSDK/1.2.176.1"
>           $Env:Path += ";C:/VulkanSDK/1.2.176.1/Bin"
>           # your command goes here
> ```

When i used it and tried to build a cmake project using vulkan it said

**Comment by kudaba** [comment]
I forgot to leave an update here. AFAICT 1.2.176.1 isn't available for download anymore. I've updated my scripts to dynamically get the latest sdk, and fixed some issues with the powershell download step taking forever to complete.

```
    env:
      VULKAN_SDK: C:\VulkanSDK\
...
    - name: Setup Vulkan
      run: |
          $ver = (Invoke-WebRequest -Uri "https://vulkan.lunarg.com/sdk/latest.json" | ConvertFrom-Json).windows
          echo Version $ver
          $ProgressPreference = 'SilentlyContinue'
          Invoke-WebRequest -Uri "https://sdk.lunarg.com/sdk/download/$ver/windows/VulkanSDK-$ver-Installer.exe" -OutFile VulkanSDK.exe
          echo Downloaded
          .\VulkanSDK.exe --root C:\VulkanSDK  --accept-licenses --default-answer --confirm-command install
```
