### ISSUE TITLE
Cannot find Xcode 12.0.1 GM on guthub runner

### ISSUE THREAD

**Issue by sagimann** [actions/virtual-environments#1809]
**Description**  
I'm trying to build a production version of my iOS app using Xcode 12, but the app store does not accept it, says it's not built with a GM Xcode. Looking in the /Applications folder for any Xcode 12.x, I see:
```
lrwxr-xr-x   1 runner  admin    26 Oct  3 21:15 Xcode_12.0.0.app -> /Applications/Xcode_12.app
lrwxr-xr-x   1 runner  admin    28 Oct  3 21:40 Xcode_12.2.0.app -> /Applications/Xcode_12.2.app
drwxr-xr-x   3 runner  wheel    96 Sep 24 23:05 Xcode_12.2.app
drwxr-xr-x   3 runner  wheel    96 Sep  9 18:30 Xcode_12.app
drwxr-xr-x   4 runner  wheel   128 Oct  3 21:15 Xcode_12_beta.app
```
Officially, Xcode 12.0.1 is GM, which does not exist on the runner. How do I build correctly using Xcode 12 (whatever sub version) GM?

**Area for Triage**:  Apple

**Question, Bug, or Feature?**:  Question

**Virtual environments affected**  
- [x] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Ubuntu 20.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Expected behavior**  
Xcode 12.0.1 GM should be available on the runner

**Actual behavior**  
Xcode 12.0.1 GM does not seem to be available on the runner, and any attempt to select the other versions result in a build which the app store does not accept, indicating it's not built with Xcode GM..

**Repro steps**  
Repo is private, so cannot share explicit steps. However, here are the general steps to take:
1. create an action which lists the available apps:
`ls -la /Applications/`
2. observe there is no xcode 12.0.1 - not as a soft link nor as anything else

**Comment by maxim-lobanov** [comment]
Hello @sagimann , Please follow [image documentation](https://github.com/actions/virtual-environments/blob/main/images/macos/macos-10.15-Readme.md#xcode) to find all installed Xcode versions.
Xcode 12.0.0 GM is installed in `/Applications/Xcode_12.app`. Please double check that you use `/Applications/Xcode_12.app` but not `/Applications/Xcode_12_beta.app`.
As for the Xcode 12.0.1, it is not added to runners yet. It will be available next week

**Comment by sagimann** [comment]
Hello @LeonidLapshin , the versions are there, as I listed them above. It seems like the issue was with the build process, which uses Fastlane: when setting the xcode version in Fastlane to "12" or "12.0" or "12.0.0", Fastlane seems to detect the beta Xcode, as we can see in their logs:
```
DEBUG [2020-10-13 13:45:43.55]: Found Xcode version 12.0 at /Applications/Xcode_12_beta.app satisfying requirement 12.0.0
INFO [2020-10-13 13:45:43.55]: Setting Xcode version to /Applications/Xcode_12_beta.app for all build steps
```

To workaround it, I forcefully removed /Applications/Xcode_12_beta.app so that Fastlane doesn't find it. Then it uses the rught xcode:
```
DEBUG [2020-10-13 13:45:43.55]: Found Xcode version 12.0 at /Applications/Xcode_12_beta.app satisfying requirement 12.0.0
INFO [2020-10-13 13:45:43.55]: Setting Xcode version to /Applications/Xcode_12.app for all build steps
```

**Comment by LeonidLapshin** [comment]
Hey, @sagimann 
I'll close this issue for now, Xcode 12 beta 6 will be fully removed with the next images rollout, usually it takes a week or two, feel free to reopen this ticket if you still have problems or they will appear again.
Thank you!
