### ISSUE TITLE
MySQL fails to run on Github Actions using Kind

### ISSUE THREAD

**Issue by tamalsaha** [actions/virtual-environments#181]
**Describe the bug**
We are trying to run an official MySQL pod inside a Kind cluster on GitHub actions. Here is our demo repo: https://github.com/tamalsaha/mysql-kind-demo

The problem is mysql pod fails to run with the error message:

```
+ mysqld --verbose --help
mysqld: Can't read dir of '/etc/mysql/conf.d/' (OS errno 13 - Permission denied)
mysqld: [ERROR] Fatal error in defaults handling. Program aborted!
```

You can see the full log here: https://github.com/tamalsaha/mysql-kind-demo/commit/dfef4e188accdb6334b75f4658bd0fc1dd35c732/checks?check_suite_id=364071606

The puzzling this is that if I just run `docker run mysql:8.0.14 mysqld --verbose --help` it works! You can see full log here: 
https://github.com/tamalsaha/mysql-kind-demo/commit/d452e672fa2219fb5ea5174bd99108d6d0b2728a/checks?check_suite_id=364034120

When I try these on my Ubuntu 18.04 Desktop (using pod in a Kind cluster and Direct Docker), both modes work.

You can see the diff between pod log from my Desktop (left) and Github action (right). They mostly look identical: https://www.diffchecker.com/D64wMscf

*Can you help my understand why `mysqld --verbose --help` fails when run as a pod inside a Kind v1.16.3 cluster on GitHub actions?*

**Virtual environments affected**
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [x] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Expected behavior**
A description of what you expected to happen.

**Actual behavior**

Here is our demo repo: https://github.com/tamalsaha/mysql-kind-demo

If you want to run locally, try this:

```
kind create cluster
kubectl apply -f https://github.com/tamalsaha/mysql-kind-demo/raw/master/hack/kubernetes/mysql.yaml
```

**Anything else we need to know?**:

One hack we found is that if we mount an emptyDir to /etc/mysql/conf.d folder, `mysqld --verbose --help` command starts working.

**Environment:**

- kind version: (use `kind version`): v0.6.1
- Kubernetes version: (use `kubectl version`): v1.16.3
- Docker version: (use `docker info`): 

```
Client:
 Debug Mode: false
 Plugins:
  buildx: Build with BuildKit (Docker Inc., v0.3.1)

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 13
 Server Version: 3.0.8
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: b34a5c8af56e510852c35414db4c1f4fa6172339
 runc version: 3e425f80a8c931f88e6d94a8c831b9d5aa481657
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.0.0-1027-azure
 Operating System: Ubuntu 18.04.3 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 6.783GiB
 Name: fv-az86
 ID: KRSI:74QW:YCD2:XEK7:4WO2:DOAO:FRYG:MP4B:J2YH:N63L:5SGR:JV5A
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

- OS (e.g. from `/etc/os-release`):

```
PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
NAME="Debian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

Reposted from Kind issue queue: https://github.com/kubernetes-sigs/kind/issues/1179

**Comment by robertdebock** [comment]
Suffering from the [same issue here](https://github.com/robertdebock/ansible-role-mysql/runs/453639351?check_suite_focus=true). Don't know how to solve it though.

**Comment by al-cheb** [comment]
Hello, @tamalsaha 

```
 -R, --remove
           This flag is used to remove an AppArmor definition already in the kernel.  Note that it still requires a
           complete AppArmor definition as described in apparmor.d(5) even though the contents of the definition
           aren't used.
```

Please update your ci to exclude mysql:
```
- name: apparmor
  run: |
      set -x
      sudo apt-get remove mysql-server --purge
      sudo apt-get install apparmor-profiles
      sudo apparmor_parser -R /etc/apparmor.d/usr.sbin.mysqld
```
![build](https://user-images.githubusercontent.com/47745270/78772716-de510e80-799a-11ea-9575-77ee00379926.JPG)

Log output:
```
2020-04-08T10:06:49.6199372Z brk(0x55814ceb3000)                     = 0x55814ceb3000
2020-04-08T10:06:49.6199553Z futex(0x7f2ac4eb74e4, FUTEX_WAKE_PRIVATE, 2147483647) = 0
2020-04-08T10:06:49.6199734Z futex(0x7f2ac5124bb0, FUTEX_WAKE_PRIVATE, 2147483647) = 0
2020-04-08T10:06:49.6199896Z brk(0x55814ced4000)                     = 0x55814ced4000
2020-04-08T10:06:49.6200078Z brk(0x55814cefc000)                     = 0x55814cefc000
2020-04-08T10:06:49.6200261Z brk(0x55814cf2b000)                     = 0x55814cf2b000
2020-04-08T10:06:49.6200433Z fstat(1, {st_mode=S_IFIFO|0600, st_size=0, ...}) = 0
2020-04-08T10:06:49.6200596Z brk(0x55814cf58000)                     = 0x55814cf58000
2020-04-08T10:06:49.6200784Z write(1, "mysqld  Ver 8.0.18 for Linux on "..., 4096) = 4096
2020-04-08T10:06:49.6201271Z mysqld  Ver 8.0.18 for Linux on x86_64 (MySQL Community Server - GPL)
2020-04-08T10:06:49.6201486Z Copyright (c) 2000, 2019, Oracle and/or its affiliates. All rights reserved.
```

**Comment by al-cheb** [comment]
@tamalsaha, Feel free to open the thread if you have any concerns.
