### ISSUE TITLE
macOS 11.0 (Big Sur) is available as a preview 🚀

### ISSUE THREAD

**Issue by AlenaSviridenko** [actions/virtual-environments#1814]
macOS Big Sur (11.0) is available as a preview for GitHub Action users!

To use it set `runs-on: macos-11.0` in your workflow file.
![image](https://user-images.githubusercontent.com/8777209/96004544-34b87180-0e44-11eb-9b55-901e7f2ace3f.png)

**Since this is a preview, some issues with the image are expected. Please, report them in this repository and we will take a look at them.**

 **NOTE:** Pay attention that software list on macOS Catalina and macOS Big Sur is different. Please, review it below.
Full list of installed software can be found here: [images/macos/macos-11.0-Readme.md](https://github.com/actions/virtual-environments/blob/main/images/macos/macos-11.0-Readme.md)

#### Software changes:

- PyPy is not supported at the moment.
- Default Ruby is set to the latest one.
- .NET Core 3.0 has reached EOL so now we are installing .NET Core 2.1 and 3.1 only.

#### Packages that won’t be installed on macOS Big Sur:
- xctool
- parallel
- bats
- nomad-cli
- node-gyp
- mobile-center-cli

|Tool Name| Catalina  | Big Sur |
|---|---|---|
| XCode | 12.2_beta, 12 <br/>  11.7, 11.6, 11.5, 11.4.1  <br/>  11.4, 11.3.1, 11.2.1, 11.1 <br/>  11, 10.3 | 12.2_beta, <br/>  11.7 |
| Java| 7, 8 <br/>  11, 12 <br/>  13, 14 | 8 <br/> 11 |
| .Net Core | 2.1 <br/>  3.0 <br/>  3.1 | 3.0 |
| Xamarin.Mono | 6.12.0.93, 6.10.0.106 <br/>  6.8.0.123, 6.6.0.166 <br/>  6.4.0.208 | 6.12.0.93 | 
| Xamarin.iOS | 13.20.2.2, 13.18.2.1, 13.16.0.13  <br/>  13.14.1.39, 13.10.0.21, 13.8.3.0  <br/> 13.6.0.12, 13.4.0.2, 13.2.0.47 | 13.20.2.2 |
| Xamarin.Mac | 6.20.2.2, 6.18.3.2, 6.16.0.13  <br/>  6.14.1.39, 6.10.0.21, 6.8.3.0 <br/>  6.6.0.12, 6.4.0.2, 6.2.0.47 | 6.20.2.2 |
| Xamarin.Android | 11.0.2.0  <br/>  10.3.1.4  <br/>  10.2.0.100  <br/>  10.1.3.7  <br/>  10.0.6.2 | 11.0.2.0 |
| Android Platform | android-24 &mdash; android-30 | android-27 &mdash; android-30 |
| Android Build Tools | 24.0.0 &mdash; 30.0.2 | 27.0.0 &mdash; 30.0.2 |
| Android Extra |  android;m2repository  <br/>  google;m2repository  <br/>  google;google_play_services <br/>  intel;Hardware_Accelerated_Execution_Manager <br/>  m2repository;com;android;support;constraint;constraint-layout-solver;\* <br/>  m2repository;com;android;support;constraint;constraint-layout;\*  | android;m2repository <br/> google;m2repository <br/>  google;google_play_services <br/>  intel;Hardware_Accelerated_Execution_Manager |
| Android Add-On | addon-google_apis-google-24 <br/>  addon-google_apis-google-23 <br/>  addon-google_apis-google-22 <br/>  addon-google_apis-google-21 | &mdash; |
| ndk | 15.2.4203891 <br/>  18.1.5063045 <br/>  21.3.6528147 | 21.3.6528147 |

**Comment by jessejiang0214** [comment]
What's the MacOS 11.0 name in DevOps pipeline?
I used macOS 11.0 but failed. it said [warning]An image label with the label macOS-11.0 does not exist.

**Comment by maxim-lobanov** [comment]
@jessejiang0214 , MacOS 11.0 is not available in Azure DevOps yet. Unfortunately, we don't have ETA yet.
You can track progress in https://github.com/actions/virtual-environments/issues/2072

**Comment by riverar** [comment]
How does this runner comply with the macOS 11 [software license agreement](https://www.apple.com/legal/sla/docs/macOSBigSur.pdf) terms?

![image](https://user-images.githubusercontent.com/475132/100724975-50d28c80-3378-11eb-9ea5-076e3affb089.png)

**Comment by AlenaSviridenko** [comment]
@chrispat and @alepauly could you please take a look at the question above regarding licenses?

**Comment by filiptronicek** [comment]
The Big Sur runner should work on private repos too, right? I tried running a simple Node workflow with all the OSs but only the Big Sur doesn't run. (last time they timed out after ~30 minutes)

![screenshot of job overview](https://user-images.githubusercontent.com/29888641/103565968-8ad80680-4ec1-11eb-9ab0-72a84b701786.png)

**Comment by AlenaSviridenko** [comment]
Hi @filiptronicek,
unfortunately, we are currently experiencing queuing issues with macOS 11.0 and investigating possible ways to handle them. Thank you for your patience.

**Comment by MaxOstrowski** [comment]
If a job on macos-11.0 is finally started, it never stops running.
https://github.com/potassco/clingcon/runs/1693835438?check_suite_focus=true
The job was finished after 2 minutes, but instead of showing:
`succeeded 36 minutes ago in 2m 13s `
it shows
`Started 35m 46s ago`

**Comment by maxim-lobanov** [comment]
@MaxOstrowski , thank you for reporting. Looks like some UI bug. I have escalated it to our engineers.

**Comment by tonyarnold** [comment]
Has any progress been made on this at all? macOS 11 has been out for months now, and we're dependant on it to produce Apple Silicon builds of our macOS app. As it stands, my team has been unable to run CI checks, produce beta builds or release updates to our app for weeks. 

Can someone at GitHub please provide a more meaningful update and timeline than what's been provided so that I can plan accordingly? The delays in finding a fix for this issue are somewhat understandable, given the holidays, but now it is getting to the point where I am going to need to find an alternative CI & build provider so that we can continue to ship our app to users.

**Comment by AlenaSviridenko** [comment]
We are sorry for the delays in eliminating of this issue. We are already preparing a plan for the future of macOS 11.0 on GitHub Actions, but there are a lot of aspects to consider and review. Mitigation of this degraded experience is one of the highest priorities for us now.

Until then, please, whenever possible, use `macos-10.15` (or `macos-latest` which is also macOS 10.15), it contains Xcode versions that allows you building Universal Apps.

**Comment by AlenaSviridenko** [comment]
We are transiting macOS 11.0 pools to private preview due to growing demand that is outspacing our initial capacity plan. Please, see the details here https://github.com/actions/virtual-environments/issues/2486. 

I am closing this issue until we come up with the final go-to production plan.
