### ISSUE TITLE
Update Xcode 11.3 GM

### ISSUE THREAD

**Issue by orj** [actions/virtual-environments#182]
**Tool information**
- Tool name: Xcode
- Add or update? Update
- Desired version: 11.3 GM (11C29)
- Approximate size: 7gb

**Virtual environments affected**
- macOS 10.15

**Can this tool be installed during the build?**
Yes, but not really ideal.

**Are you willing to submit a PR?**
No.

**Comment by colinhumber** [comment]
Bump

**Comment by kaylangan** [comment]
@colinhumber sorry for the delay. We typically do have weekly updates, however due to the holidays, we [froze deployments](https://github.blog/changelog/2019-12-19-github-actions-updates-to-the-virtual-environments/). Deployments are resuming this week and the next one will have Xcode 11.3 GTM.

**Comment by colinhumber** [comment]
@kaylangan Awesome! Thanks for the quick update! Much appreciated. 🙌

**Comment by kaylangan** [comment]
This has been fully deployed. Docs will be updated shortly.
