### ISSUE TITLE
Symbolic links for Xcode (latest-stable, latest-beta, etc)

### ISSUE THREAD

**Issue by maxgoedjen** [actions/virtual-environments#1822]
**Description**  
It would be nice to be able to explicitly specify a preference for keeping up to date with Xcode. I know the defaults change over time (eg: #1712) but they do lag behind general availability of Xcode. It'd be awesome to have a symbolic link of `Xcode-LatestStable.app` and a similar one for latest beta/stable that I could point to and ALWAYS build on the latest.

**Area for Triage**:  
Apple

**Question, Bug, or Feature?**:  
Feature

**Virtual environments affected**  
- [x] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Ubuntu 20.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Expected behavior**  
NA

**Actual behavior**  
NA

**Repro steps**  
NA

**Comment by maxim-lobanov** [comment]
@maxgoedjen , I suggest trying [setup-xcode](https://github.com/marketplace/actions/setup-xcode-version) task. It supports `latest` and `latest-stable` tags and any other SemVer notation.

**Comment by maxgoedjen** [comment]
TIL, thanks!
