### ISSUE TITLE
Update to Xcode 12.1 GM

### ISSUE THREAD

**Issue by maxgoedjen** [actions/virtual-environments#1823]
**Tool information**
- Tool name: Xcode 12.1 GM
- Tool license: Proprietary
- Add or update? Update
- Desired version: 12.1 GM
- Approximate size: Unknown
- If this is an add request:
  - Brief description of tool: NA
  - URL for tool's homepage: NA
  - Provide a basic test case to validate the tool's functionality: NA

**Area for Triage**:
Apple

**Question, Bug, or Feature?**:
Feature

**Virtual environments affected**
- [x] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Ubuntu 20.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Can this tool be installed during the build?**
No

**Tool installation time in runtime**
~20m

**Are you willing to submit a PR?**
No (I would if I knew what I was doing on this one :P)

**Comment by maxim-lobanov** [comment]
Xcode 12.1 was added via https://github.com/actions/virtual-environments/pull/1805. It will be included to next image rollout.
Approximately, the begin of next week.

**Comment by maxgoedjen** [comment]
Awesome, thanks for the quick response!

**Comment by maxim-lobanov** [comment]
Let's keep the issue opened until the new Xcode is available on images.

**Comment by maxgoedjen** [comment]
Loooooooks like this got deployed (I can select it in a trial run, but the readme isn't updated yet).

**Comment by maxim-lobanov** [comment]
@maxgoedjen , Yes, deployment is still in progress but it is almost complete. Readme will be updated as soon as we have finished. You can track software list for new image in https://github.com/actions/virtual-environments/pull/1851

**Comment by maxgoedjen** [comment]
Awesome thanks for update 👍 
Is there any documentation around the deployment process? From your description I'm assuming its not an "all at once" deal :P

**Comment by miketimofeev** [comment]
@maxgoedjen there is no such documentation, but yeah, it usually takes a few days to propagate the image to all environments.

**Comment by al-cheb** [comment]
Hello, @maxgoedjen 
The new image with Xcode 12.1 GM (`20201017.1`) has been deployed - https://github.com/actions/virtual-environments/blob/main/images/macos/macos-10.15-Readme.md
