### ISSUE TITLE
Xamarin ios build fails with missing namespace

### ISSUE THREAD

**Issue by markdrizd** [actions/virtual-environments#1826]
**Description**  
I have implemented tracking privacy permission on ios which require Xamarin.iOS 14 and Xcode 12. It works perfectly fine locally, but fails on a pipeline. I'm using macOS 10.15 agent which, as far as I understood, should include Xamarin.iOS 14 and Xcode 12. 

I tried to use bash script to set Xcode version to 12 and Xamarin Sdk version to 6.12.0 but it didn't help.

Please let me know if there's any solution for this issue.

**Area for Triage**:  
Xamarin, Apple

**Question, Bug, or Feature?**:  
Bug

**Virtual environments affected**  
- [x] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Ubuntu 20.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Expected behavior**  
Successful build. 

**Actual behavior**  
Build fails with an error CS0246: The type or namespace name 'AppTrackingTransparency' could not be found (are you missing a using directive or an assembly reference?).

**Repro steps**  
1. Reference AppTrackingTransparency namespace in xamarin ios solution 
2. Produce a build

**Comment by maxim-lobanov** [comment]
Hello @markdrizd , Xamarin.iOS 14.0 is included but it is not set by default.
See details in this issue: https://github.com/actions/virtual-environments/issues/1698#issuecomment-705012474

**Comment by maxim-lobanov** [comment]
If you use AzureDevOps or task doesn't work for you, could you please share steps that you use to switch Xamarin / Xcode?

**Comment by markdrizd** [comment]
I've used bash/powershell scripts

### Xamarin SDK 
**bash**
sudo $AGENT_HOMEDIRECTORY/scripts/select-xamarin-sdk.sh 6_12_0

### Xcode
**powershell** 
##vso[task.setvariable variable=MD_APPLE_SDK_ROOT;]'/Applications/Xcode_12.2.app;

**bash**
sudo xcode-select -s  /Applications/Xcode_12.2.app/Contents/Developer

Will go ahed and try [Setup Xamarin](https://github.com/marketplace/actions/setup-xamarin) task

**Comment by maxim-lobanov** [comment]
@markdrizd , Please try to use `6_12_1` instead of `6_12_0`.
See details in [toolset.json](https://github.com/actions/virtual-environments/blob/main/images/macos/toolsets/toolset-10.15.json#L25)

**Comment by markdrizd** [comment]
Changing to `6_12_1` did the trick. Also powershell script is not needed. After update bash scripts looks like this: 

**Xamarin SDK**
`sudo $AGENT_HOMEDIRECTORY/scripts/select-xamarin-sdk.sh 6_12_1`

**Xcode**
`echo '##vso[task.setvariable variable=MD_APPLE_SDK_ROOT;]'$(xcodeRoot);sudo xcode-select --switch $(xcodeRoot)/Contents/Developer`

xcodeRoot is pipeline variable xcodeRoot=/Applications/Xcode_12.2.app

Thank you for your help.
