### ISSUE TITLE
Update/Add swift[c]

### ISSUE THREAD

**Issue by rockwotj** [actions/virtual-environments#1827]
Right now only the `swift` tool is installed (added to the path) to github actions linux runners.

https://github.com/actions/virtual-environments/blob/abec49dcd9d21df471c7a7ed83cc0218d0516c7f/images/linux/scripts/installers/swift.sh#L18

Some tools (such as `bazel`'s [swift rules][1]) look for `swiftc` specifically, and only `swift` is provided. Can we add a symlink for that?

**Tool information**
- Tool name: Swiftc
- Add or update? Update

**Area for Triage**:

**Question, Bug, or Feature?**:
Feature?

**Virtual environments affected**
- [ ] macOS 10.15
- [X] Ubuntu 16.04 LTS
- [X] Ubuntu 18.04 LTS
- [X] Ubuntu 20.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Are you willing to submit a PR?**
Sure!

[1]: https://github.com/bazelbuild/rules_swift/blob/6ae82f57ebefa13df5ce1daf7a2fd3080e41df55/swift/internal/swift_autoconfiguration.bzl#L205

**Comment by LeonidLapshin** [comment]
Hey @rockwotj 
It looks good, are there any symlinks beside this one that should be included to images?
Thank you!

**Comment by rockwotj** [comment]
Thanks @LeonidLapshin! When will this be available in the runner?
