### ISSUE TITLE
apt-get update failing on ubuntu-latest (ubuntu-18.04 Version: 20201012.1)

### ISSUE THREAD

**Issue by matthewfeickert** [actions/virtual-environments#1828]
**Description**  

In `ubuntu-latest` (ubuntu-18.04 Version: 20201012.1) `sudo apt-get update` fails.

**Area for Triage**: 

Containers (maybe? Not sure given the choices at https://github.com/actions/virtual-environments/tree/main/triage-rules.yml)

**Question, Bug, or Feature?**:  

"Bug"

**Virtual environments affected**  
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [x] Ubuntu 18.04 LTS
- [ ] Ubuntu 20.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Expected behavior**

Have `sudo apt-get update` succeed without errors.  

**Actual behavior**

When

```
sudo apt-get update
```

is run in a workflow it starts to get the package lists but then fails on `https://packages.microsoft.com/ubuntu/18.04/prod/dists/bionic/main/binary-amd64/Packages.bz2`

```
Get:53 http://ppa.launchpad.net/ondrej/php/ubuntu bionic/main Translation-en [29.5 kB]
Fetched 8452 kB in 3s (2560 kB/s)
Reading package lists...
E: Failed to fetch https://packages.microsoft.com/ubuntu/18.04/prod/dists/bionic/main/binary-amd64/Packages.bz2  File has unexpected size (141364 != 141252). Mirror sync in progress? [IP: 13.90.21.104 443]
   Hashes of expected file:
    - Filesize:141252 [weak]
    - SHA512:dffbaf15f537ae643df110b279248993b2828e99352dff51a5df9648cf39531ffb7022ec2f0d9e553287c9889addcb5e734d9df95f749c456db04fd328a67ef4
    - SHA256:6757f7f09fb2a0491657aac899faa29bd67fe7b9dfd849844f7fafca9afcc33e
    - SHA1:37be76673db70e808db91294af54fddf476aae7f [weak]
    - MD5Sum:ecc0d5d8d9373eee7aeceda58d7be8f9 [weak]
   Release file created at: Tue, 13 Oct 2020 22:35:00 +0000
E: Some index files failed to download. They have been ignored, or old ones used instead.
Error: Process completed with exit code 100.
```

**Repro steps**  

Run a workflow that has `sudo apt-get update`. c.f. https://github.com/scikit-hep/pyhf/pull/1120 for a pretty isolated example of this happening.

It is worth noting that this has started happening only in the last few hours. On https://github.com/scikit-hep/pyhf/pull/1119 a [workflow using this succeeded at `Thu, 15 Oct 2020 23:32:34 GMT`](https://github.com/scikit-hep/pyhf/runs/1261856532) but then when that PR was merged into `pyhf`'s `master` branch at [`Thu, 16 Oct 2020 02:45 GMT` it failed](https://github.com/scikit-hep/pyhf/runs/1262590265) and has failed since.

(cc @lukasheinrich @kratsg)

**Comment by Milerius** [comment]
E: Failed to fetch https://packages.microsoft.com/ubuntu/16.04/prod/dists/xenial/main/binary-amd64/Packages  Writing more data than expected (934716 > 934130)
E: Some index files failed to download. They have been ignored, or old ones used instead.
Error: The process 'sudo' failed with exit code 100

![image](https://user-images.githubusercontent.com/21139416/96215771-2b7fef80-0f7f-11eb-8f94-99afb1fbe1ce.png)

**Comment by al-cheb** [comment]
Hello, @matthewfeickert
Sorry for the inconvenience. This issue is not related to the current  ubuntu-18.04 Version: 20201012.1 image itself, because I have found the similar issue which can be reproduced locally - https://github.com/microsoft/vscode/issues/107793. Looks like the issue is resolved from repository side, because I can't reproduce it now.

Temporary workaround:
```
- name: remove microsoft repos
  run: |
         sudo rm /etc/apt/sources.list.d/microsoft-prod*
         sudo rm /etc/apt/sources.list.d/azure-cli*
         sudo apt-get update
```

**Comment by matthewfeickert** [comment]
> This issue is not related to the current ubuntu-18.04 Version: 20201012.1 image itself, because I have found the similar issue which can be reproduced locally - [microsoft/vscode#107793](https://github.com/microsoft/vscode/issues/107793). Looks like the issue was resolved from repository side, because I can't reproduce it now.

Thanks for the info and fast reply @al-cheb. Indeed, things are working again on our side as https://github.com/scikit-hep/pyhf/pull/1120 is now passing CI. I'll go ahead and close this.
