### ISSUE TITLE
Update apt-fast to 1.9.10

### ISSUE THREAD

**Issue by shivammathur** [actions/virtual-environments#1841]
**Tool information**
- Tool name: apt-fast
- Tool license: GPL-3.0 License
- Add or update? Update
- Desired version: 1.9.10
- Approximate size: ~50 KB

**Area for Triage**: Packages

**Question, Bug, or Feature?**: Feature

**Virtual environments affected**
- [ ] macOS 10.15
- [X] Ubuntu 16.04 LTS
- [X] Ubuntu 18.04 LTS
- [X] Ubuntu 20.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Can this tool be installed during the build?**
Yes, already in scripts.

**Tool installation time in runtime**: ~ 30s

**Are you willing to submit a PR?**
Not required

1.9.10 version of `apt-fast` fixes exit codes. 
https://github.com/ilikenwf/apt-fast/compare/1.9.9...1.9.10

**Comment by miketimofeev** [comment]
Hi @shivammathur!
Current week deployment already started, therefore this version will be in the next week's only. I'll notify you when it's done.
In the meantime, I've created a PR to output an apt-fast version to the readme
https://github.com/actions/virtual-environments/pull/1846

**Comment by miketimofeev** [comment]
@shivammathur images with apt-fast 1.9.10 have been deployed and the version is available in the readme:
https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-README.md#tools
I'm going to close the issue, but please feel free to contact us if you have any concerns.
Thank you!

**Comment by shivammathur** [comment]
@miketimofeev Thanks! I have verified the upgrade.
