### ISSUE TITLE
[Ubuntu] [Windows] Boost 1.69.0 will be deprecated on November, 10

### ISSUE THREAD

**Issue by AlenaSviridenko** [actions/virtual-environments#1847]
### Breaking changes
Boost 1.69 will be removed from Windows / Ubuntu images

### Target date
Deployment of these changes will be started on 10 November and will take a few days.

### The motivation for the changes
Currently, we have a lack of free space on images so we would like to deprecate old software 

### Possible impact
If you use default Xcode version and your project is not compatible with Xcode 12.0.1, your build can be broken.

- [x] Ubuntu 1604
- [x] Ubuntu 1804
- [x] Ubuntu 2004
- [x] Windows 2016
- [x] Windows 2019

### Mitigation ways
You can use the following snippet to install Boost 1.69.0 in runtime at the first step of the build:
Windows:
```pwsh
$url = "https://github.com/actions/boost-versions/releases/download/1.69.0-20200608.1/boost-1.69.0-win32-msvc14.1-x86_64.tar.gz"
(New-Object System.Net.WebClient).DownloadFile($url, "$($env:TEMP)\boost.tar.gz")
7z.exe x "$($env:TEMP)\boost.tar.gz" -o"$($env:TEMP)" -y | Out-Null
$tarPath = Get-ChildItem -Path "$($env:TEMP)" -Filter "boost-*.tar" | Select-Object -First 1
7z.exe x $tarPath -o"$($env:TEMP)/boost" -y | Out-Null
Push-Location -Path "$($env:TEMP)\boost"
Invoke-Expression .\setup.ps1
```

Ubuntu 1604:
```pwsh
$url = "https://github.com/actions/boost-versions/releases/download/1.69.0-20200608.1/boost-1.69.0-linux-16.04-gcc-x64.tar.gz"
(New-Object System.Net.WebClient).DownloadFile($url, "/tmp/boost.tar.gz")
mkdir "/tmp/boost"
tar -xzf "/tmp/boost.tar.gz" -C "/tmp/boost"
Push-Location -Path "/tmp/boost"
Invoke-Expression "bash ./setup.sh"
```

Ubuntu 1804:
```pwsh
$url = "https://github.com/actions/boost-versions/releases/download/1.69.0-20200608.1/boost-1.69.0-linux-16.04-gcc-x64.tar.gz"
(New-Object System.Net.WebClient).DownloadFile($url, "/tmp/boost.tar.gz")
mkdir "/tmp/boost"
tar -xzf "/tmp/boost.tar.gz" -C "/tmp/boost"
Push-Location -Path "/tmp/boost"
Invoke-Expression "bash ./setup.sh"
```

**Comment by nathsmaR** [comment]
Default

**Comment by Toni-d-e-v** [comment]
$url = "https://github.com/actions/boost-versions/releases/download/1.69.0-20200608.1/boost-1.69.0-win32-msvc14.1-x86_64.tar.gz"
(New-Object System.Net.WebClient).DownloadFile($url, "$($env:TEMP)\boost.tar.gz")
7z.exe x "$($env:TEMP)\boost.tar.gz" -o"$($env:TEMP)" -y | Out-Null
$tarPath = Get-ChildItem -Path "$($env:TEMP)" -Filter "boost-*.tar" | Select-Object -First 1
7z.exe x $tarPath -o"$($env:TEMP)/boost" -y | Out-Null
Push-Location -Path "$($env:TEMP)\boost"
Invoke-Expression .\setup.ps1
Where is installed I need to specify in cmake list

**Comment by maxim-lobanov** [comment]
Rollout of these changes has been finished.
