### ISSUE TITLE
[macOS] Built-in Python 2.7 will be used on macOS instead of Homebrew formula on November, 3rd.

### ISSUE THREAD

**Issue by AlenaSviridenko** [actions/virtual-environments#1848]
Hey!

Due to maintenance concerns, we are going to stop installing Python 2.7 from the Homebrew formula, which was deprecated at the beginning of 2020, and instead, use the macOS built-in Python.

As a drawback — the python 2 version will be slightly outdated (2.7.16 instead of 2.7.17)

Please, let us know through this issue if you have any questions or concerns. 
Thanks!

**Comment by miketimofeev** [comment]
Decided to stay on brew formula because we've worked out a solution to keep the brew clean.
