### ISSUE TITLE
Update dotnet

### ISSUE THREAD

**Issue by tejasd1990** [actions/virtual-environments#1857]
**Tool information**
- Tool name: dotnet
- Tool license: 
- Add or update? update
- Desired version: 5
- Approximate size: 
- If this is an add request:
  - Brief description of tool: 
  - URL for tool's homepage: 
  - Provide a basic test case to validate the tool's functionality: 

**Area for Triage**:

**Question, Bug, or Feature?**:
Feature

**Virtual environments affected**
- [x] macOS 10.15
- [x] Ubuntu 16.04 LTS
- [x] Ubuntu 18.04 LTS
- [x] Ubuntu 20.04 LTS
- [x] Windows Server 2016 R2
- [x] Windows Server 2019

**Can this tool be installed during the build?**

**Tool installation time in runtime**

**Are you willing to submit a PR?**
yes https://github.com/actions/virtual-environments/pull/1856

Azure Pipelines hosted agents will soon be updated to contain .Net Core 5.x SDK/Runtime along with older lts versions. Unless you have locked down a SDK version for your project(s), 5.x SDK might be picked up which might have breaking behavior as compared to previous versions.

You can learn more about the breaking changes here:
https://docs.microsoft.com/en-us/dotnet/core/tools/
https://docs.microsoft.com/en-us/dotnet/core/compatibility/

To learn about more such changes and troubleshoot, refer here:
https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/dotnet-core-cli?view=azure-devops#troubleshooting

**Comment by miketimofeev** [comment]
Hi, @tejasd1990!
Thanks for your contribution. Could you please change your PR to install a stable version of .Net 5 only? We'll merge it as soon as a stable version is released.

**Comment by tejasd1990** [comment]
Hi @miketimofeev , I have added this issue for adding an announcement. My team owns the dotnetcore ecosystem, and we have made this change in the pr for the dotnet 5 release day 0 readiness.

**Comment by bishal-pdMSFT** [comment]
>Azure Pipelines hosted agents have been updated 

They have not yet been updated. We will be updating them soon.

This is a hands-up to make folks aware of this change. Please update the message to call that out.

**Comment by tejasd1990** [comment]
hi @miketimofeev , we want to make this an announcement as I said earlier. Whats the way forward for that?

**Comment by maxim-lobanov** [comment]
@tejasd1990 , Alyona has create announcement in repository: https://github.com/actions/virtual-environments/issues/1891
It will also be included to image documentation for all images next week

**Comment by bishal-pdMSFT** [comment]
@maxim-lobanov could you please update this issue after announcement is public this week? Would like to spread that information.

**Comment by maxim-lobanov** [comment]
Hello, I am closing this issue in favor of https://github.com/actions/virtual-environments/issues/1891.
We will deploy new images with .NET 5 in two weeks. We will keep announcement post updated.
