### ISSUE TITLE
Update/Add VS2010 Build tools into Visual Studio 2019

### ISSUE THREAD

**Issue by AraHaan** [actions/virtual-environments#1858]
**Tool information**
- Tool name: Visual Studio 2010 Build Tools
- Tool license: I do not know.
- Add or update? Add
- Desired version: whatever is latest from the vs2010 build tools ~~provided in the Visual Studio Installer~~ I thought was provided in the Visual Studio Installer, now can be found with ``choco install vsexpress2010``.
- Approximate size: 
- If this is an add request:
  - Brief description of tool: The Visual Studio 2010 Build tools from Visual Studio 2010 gets automatically picked up by Visual Studio 2019 and allows building and loading of Visual Studio 2010 projects without needing to upgrade to the absolute latest toolset.
  - URL for tool's homepage: ~~visualstudio.microsoft.com~~ I thought it was in the Visual Studio Installer, found it here https://my.visualstudio.com/Downloads?q=visual%20studio%202010&wt.mc_id=o~msft~vscom~older-downloads
  - Provide a basic test case to validate the tool's functionality: This repository shows example usage of this tool and requires it for dependencies that I do not control however as well https://github.com/AraHaan/pthmgr/.

**Area for Triage**:

**Question, Bug, or Feature?**:

I think Feature?

**Virtual environments affected**
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Ubuntu 20.04 LTS
- [x] Windows Server 2016 R2
- [x] Windows Server 2019

**Can this tool be installed during the build?**

Not sure, I would prefer it to be included with Visual Studio 2019 on the image itself.

**Tool installation time in runtime**

It varies by machine.

**Are you willing to submit a PR?**

I mean if it's that easy to add the tool to the vs2019 installation on the windows-latest image.

**Comment by miketimofeev** [comment]
Hi @AraHaan!
Could you please clarify  — is VS2010 Build tools a component of Visual Studio 2019? I couldn't find anything related in the VS2019 enterprise installer.

**Comment by AraHaan** [comment]
Sure, I can take an image of it from my installer if you like where I selected it.

**Comment by AraHaan** [comment]
Interesting it seems that Visual Studio 2019 on my device actually allowed using the vs2010 build tools only because I also had vs2010 installed.

in that case I also found that vs2010 can be installed by ``choco install vsexpress2010`` as well but it would be missing the following however on the environment variables:
- PATH: C:\Program Files (x86)\Microsoft Visual Studio 10.0\Common7\IDE
- PATH: C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\BIN
- PATH: C:\Windows\Microsoft.NET\Framework\v4.0.30319
- LIB: C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\LIB;%LIB%
- LIB: C:\Program Files (x86)\Microsoft SDKs\Windows\v6.0A\Lib;%LIB%
- LIB: C:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\Lib;%LIB%
- INCLUDE: C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\include;%INCLUDE%

**Comment by maxim-lobanov** [comment]
@AraHaan thank you for feature request but we don't have plans to install Visual Studio 2010 to images.
Currently, we have the following images: Windows2016 (with Visual Studio 2017 on board) and Windows2019 (with Visual Studio 2019 on board). Unfortunately, we don't support older versions of Visual Studio on images.

**Comment by cooljeanius** [comment]
> in that case I also found that vs2010 can be installed by `choco install vsexpress2010` as well

@AraHaan does this still work for you? I tried adding it to my workflow, but got this output:
```
Run choco install vsexpress2010
Chocolatey v2.2.2
Installing the following packages:
vsexpress2010
By installing, you accept licenses for the packages.
vsexpress2010 not installed. The package was not found with the source(s) listed.
 Source(s): 'https://community.chocolatey.org/api/v2/'
 NOTE: When you specify explicit sources, it overrides default sources.
If the package version is a prerelease and you didn't specify `--pre`,
 the package may not be found.
Please see https://docs.chocolatey.org/en-us/troubleshooting for more
 assistance.

Chocolatey installed 0/1 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Failures
 - vsexpress2010 - vsexpress2010 not installed. The package was not found with the source(s) listed.
 Source(s): 'https://community.chocolatey.org/api/v2/'
 NOTE: When you specify explicit sources, it overrides default sources.
If the package version is a prerelease and you didn't specify `--pre`,
 the package may not be found.
Please see https://docs.chocolatey.org/en-us/troubleshooting for more
 assistance.
Error: Process completed with exit code 1.
```
