### ISSUE TITLE
windows-2016 has postgres 13 but documentation says postgres 12

### ISSUE THREAD

**Issue by shusson** [actions/virtual-environments#1859]
**Description**  
Based on https://github.com/actions/virtual-environments/blob/main/images/win/Windows2016-Readme.md I expected windows-2016 to have postgres 12. It looks like it has postgres 13.

![image](https://user-images.githubusercontent.com/2106638/96558485-06131e80-12bc-11eb-9176-128a0c8b67da.png)
![image](https://user-images.githubusercontent.com/2106638/96558381-e0861500-12bb-11eb-9e95-dad8a92f476d.png)

**Virtual environments affected**  
- [ ] Windows Server 2016 R2

**Comment by al-cheb** [comment]
Hello, @shusson 
Currently, Windows Server 2016 is updating to the version `20201012.1` - https://github.com/actions/virtual-environments/releases/tag/win16%2F20201012.1. After the deployment is complete, the documentation will be updated to the latest version.

**Comment by shusson** [comment]
@al-cheb thanks for the update 👍
