### ISSUE TITLE
Ruby versions aren't stable

### ISSUE THREAD

**Issue by Haegin** [actions/virtual-environments#186]
I'm trying to set up Github Actions as our CI solution but ran into an issue when I tried to specify the Ruby version as 2.6.2. After looking through other issues on here I found actions/setup-ruby#8 and from that discovered that when 2.6.3 was released 2.6.2 was dropped and that the recommendation was to 

If this is to be usable for CI then I need to be able to test against the same Ruby version that my app uses in production. With the current way Ruby versions are managed by this project it seems like unless I'm using a very specific Ruby version and upgrading the version I use in prod to stay in sync. Is Github Actions not intended for use as a CI solution or is there a better way to test against a particular Ruby version?

**Comment by eregon** [comment]
FWIW https://github.com/eregon/use-ruby-action allows to use exact Ruby versions.
There are plans to support that in `setup-ruby` too eventually: https://github.com/actions/setup-ruby/issues/44

**Comment by alepauly** [comment]
@Haegin, apologies for the delay in getting to this. I'm going to close this in favor of #281 simply because that one has more discussion and I think what we do for that one will solve this issue. Thanks for reporting.
