### ISSUE TITLE
Updating Brew fails on macos-latest

### ISSUE THREAD

**Issue by mcmarkj** [actions/virtual-environments#1864]
**Description**  
Installation or Upgrading of Homebrew on macos-latest fails with a critical error 
```
Error: Fetching /usr/local/Homebrew/Library/Taps/local/homebrew-openssl failed!
Fetching /usr/local/Homebrew/Library/Taps/local/homebrew-python2 failed!
...
Failed during: /usr/local/bin/brew update --force
Error: Process completed with exit code 1.
```

This doesn't happen if I use the macos-11, where it updates as expected. We run this step before we checkout any code from our repo. Hence why I believe this to be an issue with the environment. 

**Area for Triage**:  Packages

**Question, Bug, or Feature?**:  Bug

**Virtual environments affected**  
- [X] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Ubuntu 20.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Expected behavior**  
Homebrew should update correctly and continue with a 0 exit code. 

**Actual behavior**  
Homebrew unable to update, installing old versions of packages. 

**Repro steps**  

1. Run `brew update`
or
1. Install homebrew again

**Comment by al-cheb** [comment]
Hello, @majorvin 
Duplicate https://github.com/actions/virtual-environments/issues/1811 ,as a temporary workaround - https://github.com/actions/virtual-environments/issues/1811#issuecomment-708480190
