### ISSUE TITLE
Homebrew installation broken on macos runners

### ISSUE THREAD

**Issue by rdzman** [actions/virtual-environments#1869]
**Description**  
It appears the Homebrew installation on macos runners is currently broken, preventing `brew update`.

**Area for Triage**:  
Apple

**Question, Bug, or Feature?**:  
Bug

**Virtual environments affected**  
- [x] macOS 10.15
- [x] macOS 11.0
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Ubuntu 20.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Expected behavior**  
`brew update` should run successfully (and always has in the past)

**Actual behavior**  
`brew update` fails with the following error (first noticed on 10/20/20) ...
```
fatal: 'origin' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: 'origin' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: 'origin' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: 'origin' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Error: Fetching /usr/local/Homebrew/Library/Taps/local/homebrew-openssl failed!
Fetching /usr/local/Homebrew/Library/Taps/local/homebrew-python2 failed!
fatal: invalid upstream 'origin/master'
fatal: invalid upstream 'origin/master'
```

**Repro steps**  
Any GitHub Action workflow that uses a macOS runner and attempts to run `brew update` currently fails for me. Here is the link to an example repo: https://github.com/MATPOWER/mptest

Link to workflow file: https://github.com/MATPOWER/mptest/blob/master/.github/workflows/continuous-integration.yml

**Comment by al-cheb** [comment]
Hello, @rdzman 
Duplicate #1811 ,as a temporary workaround - #1811 (comment)
