### ISSUE TITLE
Installation of aws-cli on macOS using pkg with sudo is incompatible with Homebrew

### ISSUE THREAD

**Issue by joehorsnell** [actions/virtual-environments#1874]
**Description**  

PR #1830 switched the macOS image to install `aws-cli` using the [recommended `sudo`/pkg approach](https://docs.aws.amazon.com/cli/latest/userguide/install-macos.html), to address some dependency issues from the Homebrew formula.

This approach is incompatible with Homebrew, which [does not use sudo](https://docs.brew.sh/FAQ#why-does-homebrew-say-sudo-is-bad). If you subsequently try and install `aws-cli` using Homebrew (eg to test dev env provisioning) it fails.

Obviously a work around is to uninstall the provided `aws-cli` first, as described in the [docs](https://docs.aws.amazon.com/cli/latest/userguide/install-macos.html#install-macosos-bundled-uninstall), but if the package was at least installed _without_ sudo, then I think a `brew link --force aws-cli` would be able to overwrite the `/usr/local/bin/aws` entry. 

**Area for Triage**:  
Packages

**Question, Bug, or Feature?**:  
Bug

**Virtual environments affected**  
- [x] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Ubuntu 20.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Comment by miketimofeev** [comment]
Hi @joehorsnell!
Thanks for your suggestion, but, unfortunately, aws-cli installation without sudo is more complicated than just run a package installer and requires additional maintenance in case the username has changed one day. 
Applying these 3 strings before brew installation looks like a simpler solution and it doesn't take more than 5 seconds to delete all these files.
```
sudo rm /usr/local/bin/aws
sudo rm /usr/local/bin/aws_completer
sudo rm -rf /usr/local/aws-cli
```
I'm going to close the issue, but feel free to reopen it if you have any concerns.
Thank you!

**Comment by joehorsnell** [comment]
Thanks for the quick response @miketimofeev.

Yep, as I mentioned in my comment above, the workaround of uninstallation is not too onerous. There is an additional small subtlety that it's different on macOS vs Linux. I haven't checked why, but on macOS `aws_completer` also gets installed to `/usr/local/bin/aws_completer`, whereas on Linux is does not, but anyway.

I suggest that a useful improvement might be to modify the [README](https://github.com/actions/virtual-environments/blob/main/images/macos/macos-10.15-Readme.md) for each image to make the list of installed software a table rather than a simple list, then it could have a column for "Installation Notes" to say how each package was installed (ie using `brew` or a link to the installation notes).

Thoughts?

**Comment by maxim-lobanov** [comment]
@joehorsnell , thank you for your suggestion.
We will keep it on mind but we wouldn't like to add this information to readme now. In our understanding, it is very specific information that could be useful only for customers who is trying to modify existing installation but useless for the customers who use pre-install software. Also there is a maintenance concern to support this information up-to-date.
Image generation source code is open source for all images so everyone can look into installation details and learn how tool is installed.

**Comment by joehorsnell** [comment]
> @joehorsnell , thank you for your suggestion.
> We will keep it on mind but we wouldn't like to add this information to readme now. In our understanding, it is very specific information that could be useful only for customers who is trying to modify existing installation but useless for the customers who use pre-install software. Also there is a maintenance concern to support this information up-to-date.
> Image generation source code is open source for all images so everyone can look into installation details and learn how tool is installed.

That's fair enough. I hadn't looked, but assumed that the list of installed software in the README would be generated from source of truth (ie the installation steps) but if that's not the case and it's maintained manually, then yes that would make it more difficult to maintain.
