### ISSUE TITLE
Add pull request template

### ISSUE THREAD

**Issue by kaylangan** [actions/virtual-environments#188]
We need a pull request template to guide contributions.

Things to include (not exhaustive):
- [ ] Link an issue that describes why this change should be made
- [ ] Note to not update the README files since they will be updated once the updates have been deployed
- [ ] Any testing performed / tests written
- [ ] Field for "Area" so it can be triaged to the right owner? And/or add CODEOWNERS

**Comment by maxim-lobanov** [comment]
Fixed in #603
