### ISSUE TITLE
Update/Add Clang-11, lld and libc++

### ISSUE THREAD

**Issue by advancedwebdeveloper** [actions/virtual-environments#1882]
- Tool name: Clang-11
- Tool license: Apache License v2.0
- Add or update? Update
- Desired version: [11.0](https://github.com/llvm/llvm-project/releases/tag/llvmorg-11.0.0)
- Approximate size: 400 MB
- If this is an add request:
  - Brief description of tool: [Clang C/C++ compiler](https://clang.llvm.org/) , [lld linker](https://lld.llvm.org/) and [libc++](https://libcxx.llvm.org/)
  - URL for tool's homepage: [https://llvm.org/](https://llvm.org/)
  - Provide a basic test case to validate the tool's functionality: good question; I would run 

> $clang --version
> $clang++ --version
> $lld version
> $ld -lc++
> 

**Area for Triage**:
C/C++

**Question, Bug, or Feature?**:
Feature

**Virtual environments affected**
- [X] macOS 10.15
- [X] Ubuntu 16.04 LTS
- [X] Ubuntu 18.04 LTS
- [X] Ubuntu 20.04 LTS
- [X] Windows Server 2016 R2
- [X] Windows Server 2019

**Can this tool be installed during the build?**
I tested 
> $sudo cp -R * /usr/
on Linux - I downloaded [this file](https://github.com/llvm/llvm-project/releases/download/llvmorg-11.0.0/clang+llvm-11.0.0-x86_64-linux-gnu-ubuntu-20.04.tar.xz) and extracted in a custom directory, before that.
I tried [https://apt.llvm.org/](https://apt.llvm.org/) , as a 3rd party .deb package repo - but installed libc++ package had some loader issues

**Tool installation time in runtime**
Not more then 30 sec.

**Are you willing to submit a PR?**
Maybe.

CC @zmodem 
CC @shadyysf @alepauly

**Comment by maxim-lobanov** [comment]
Hello, we don't have concerns to pre-install CLang 11 to images.
We have moved this work item to backlog but feel free to submit PR if you have a chance

**Comment by maxim-lobanov** [comment]
As I mentioned in PR, we can't accept this contribution for now since clang 11 is not available in default repo.
Installing via llvm `https://apt.llvm.org/llvm.sh` doesn't work for our case.
As soon as Clang 11 is added to default repo, we will be able to reopen this issue.

**Comment by advancedwebdeveloper** [comment]
I was already added
