### ISSUE TITLE
Xcode 12.1 GM is not available anymore

### ISSUE THREAD

**Issue by bguidolim** [actions/virtual-environments#1887]
**Description**  
Issue #1823 requested Xcode 12.1, it was deployed 2 days ago, but now Xcode 12.1 is not available anymore.

**Area for Triage**:  
Apple

**Question, Bug, or Feature?**:  
Bug

**Virtual environments affected**  
- [x] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Ubuntu 20.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Expected behavior**  
Xcode 12.1 GM should be available.

**Actual behavior**  
Xcode 12.1 GM is not available anymore.

**Comment by miketimofeev** [comment]
Hi @bguidolim! code 12.1 GM should be available across all environments, but, looks like some infrastructure changes resulted in the old image version in some of them. We'll update the version soon, sorry for the inconvenience! I will keep you posted.

**Comment by miketimofeev** [comment]
@bguidolim all the environments should be updated now. I'm going to close the issue but please feel free to contact us if you have any concerns.
Thank you!
