### ISSUE TITLE
Purge npm/yarn cache before shipping images

### ISSUE THREAD

**Issue by smorimoto** [actions/virtual-environments#1890]
Basically, as the title says. It was re-opened as a new issue by a member's request, but this is a continuation of https://github.com/actions/virtual-environments/issues/522.

**Comment by miketimofeev** [comment]
@smorimoto could you please follow the bug report template and provide all the requested details?

**Comment by smorimoto** [comment]
It's possible, but I think it was in the image of Ubuntu that I experienced it. I don't know about other images because I don't use other ones. Perhaps you all are easier to access the image details, right?

**Comment by dibir-magomedsaygitov** [comment]
Hello, @smorimoto! 
PR's directed to clean yarn and npm cache were merged. I'll post update message when images with these changes will be available to use.

**Comment by smorimoto** [comment]
Great, thanks. I wish I could help, but I didn't have much time these days.

**Comment by dibir-magomedsaygitov** [comment]
Hello @smorimoto!
Changes were delivered to all images. I'm going to close this issue. In case of any concerns feel free to contact us.

**Comment by smorimoto** [comment]
Great. Thanks @dibir-magomedsaygitov.
