### ISSUE TITLE
.NET 5.0 will become a default .NET version on December, 14

### ISSUE THREAD

**Issue by AlenaSviridenko** [actions/virtual-environments#1891]
### Breaking changes
.NET 5.0 will become a default .NET version on macOS and Ubuntu (Windows already contains .NET 5.0 as a default, it came along with Visual Studio 16.8)

### Target date
Deployment of these changes will start on ~December 7~ December, 14 and will take 3-4 days. (date is moved due to deployments freeze on a week of December, 7)

### The motivation for the changes
We would like to provide the latest .NET by default on images. 

### Possible impact
All pipelines that are not using [actions/setup-net-core-sdk](https://github.com/marketplace/actions/setup-net-core-sdk) action for GitHub Actions or [Use .NET Core](https://docs.microsoft.com/ru-ru/azure/devops/pipelines/tasks/tool/dotnet-core-tool-installer?view=azure-devops&viewFallbackFrom=tfs-2018) task for Azure Pipelines might be affected due to a lot of possible breaking changes in new .NET version

- [x] Ubuntu 16.04
- [x] Ubuntu 18.04
- [x] Ubuntu 20.04
- [x] macOS 10.13
- [x] macOS 10.14
- [x] macOS 10.15
- [x] macOS 11.0
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

### Mitigation ways
Please consider using of [actions/setup-net-core-sdk](https://github.com/marketplace/actions/setup-net-core-sdk) action for GitHub Actions or [Use .NET Core](https://docs.microsoft.com/ru-ru/azure/devops/pipelines/tasks/tool/dotnet-core-tool-installer?view=azure-devops&viewFallbackFrom=tfs-2018) task for Azure Pipelines to specify the needed .NET version.

The list of all available .NET versions can be found in corresponding documentation:
- [Ubuntu-1604](https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu1604-README.md#net-core-sdk)
- [Ubuntu-1804](https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu1604-README.md#net-core-sdk)
- [Ubuntu-2004](https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu1604-README.md#net-core-sdk)
- [macOS 10.15](https://github.com/actions/virtual-environments/blob/main/images/macos/macos-10.15-Readme.md)
- [macOS 11.0](https://github.com/actions/virtual-environments/blob/main/images/macos/macos-11.0-Readme.md)

**Comment by ManuelGalindo** [comment]
Is there a test branch to do some internal testing

**Comment by AlenaSviridenko** [comment]
@ManuelGalindo unfortunately, this is not available in public yet and will become available after the official release.

**Comment by alepauly** [comment]
I've updated the date. Once released publicly .NET 5.0 will be available by using the `setup-dotnet` [Action](https://github.com/actions/setup-dotnet) in GitHub or the `UseDotNet` [task](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/tool/dotnet-core-tool-installer?view=azure-devops) in Azure DevOps.

**Comment by alepauly** [comment]
> Is there a test branch to do some internal testing

@ManuelGalindo we've delayed this by a week but you should be able to use `setup-dotnet` in GitHub Actions or `UseDotNet` in Azure Pipelines to test .NET 5 once it's launched during .NET Conf.

**Comment by Tratcher** [comment]
Will this also include the required update of VS to 16.8?

**Comment by alepauly** [comment]
> Will this also include the required update of VS to 16.8?

@Tratcher That part might actually drop with the Windows 2019 image as soon as it's released, provided it passes all our validation.

**Comment by jackbond** [comment]
Unless I'm missing something, installing .NET5 via "Use .NET Core task" in an Azure pipeline is insufficient as long as Visual Studio is stuck below 16.8. Now that "the week of Nov 16" has been scratched, can you at least confirm that VS 16.8 will be part of the image?

**Comment by maxim-lobanov** [comment]
@jackbond , you can track progress of VS 16.8 in https://github.com/actions/virtual-environments/issues/2022

**Comment by taspeotis** [comment]
Forgive my ignorance, if the hold up is Visual Studio being updated side-by-side .NET 5 would it at least be possible to update the *nix-based build agents? I appreciate I can use the tool installer, but having it natively on the agent with NuGet pre-populated makes builds more quick.

Thank you in advance.

**Comment by alepauly** [comment]
Hi @taspeotis, since .NET 5 has a few breaking changes, we want to give some time for people to react to them before we make it the default in the images. We are targeting on preinstalling .NET 5 on all images a week after we make VS 16.8 available which we are targeting next week, so the .NET 5 change is currently targeted to the week after next. We want to make the change as soon as possible so those builds speed up, but not so soon that we cause a lot of failures for existing builds.

**Comment by Naninani** [comment]
@maxim-lobanov, was this change silently pushed? It looks like in our ado instance the image is already updated and we have a lot of builds previously defaulting to 3.x currently failing. A heads up to the MS org would have been appreciated.
In addition the ESRP CodeSigning task depends on older .net core/runtime versions and its also failing on the ado hosted pools.

**Comment by maxim-lobanov** [comment]
@Naninani Nope, the new image contains only Visual Studio 16.8 with Net 5 support. Separate installation of Net Core don't include Net 5 yet. Please check that you don't use UseDotNet tasks in pipeline and they don't start consuming Net 5 suddenly

**Comment by ccjx** [comment]
Hi everyone, I'm dropping this question here as I thought this might be related. 

My .Net framework 4.7.2 builds have been failing on Azure DevOps build agent (windows-2019) starting last evening/this morning. From this thread it seems that it should not have been upgraded, but I could not see any reason why the build is failing with the following message:
##[error]C:\Program Files\dotnet\sdk\5.0.100\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets(241,5): Error NETSDK1005: Assets file 'D:\a\1\s\...\project.assets.json' doesn't have a target for 'net472'. Ensure that restore has run and that you have included 'net472' in the TargetFrameworks for your project.

I have tried the following flags:
``` /p:TargetFrameworkVersion=v4.7.2 /p:tv=16```

Has there been a update in windows-2019 relating to .Net 5.0 SDK?

**Comment by Robar666** [comment]
> @maxim-lobanov, was this change silently pushed? It looks like in our ado instance the image is already updated and we have a lot of builds previously defaulting to 3.x currently failing. A heads up to the MS org would have been appreciated.
> In addition the internal tasks depending on older .net core/runtime versions are going to start failing on the ado hosted pools.

Same here 😕
We now added a task which installs the correct .NET Core version.

**Comment by smkanadl** [comment]
> Hi everyone, I'm dropping this question here as I thought this might be related.
> 
> My .Net framework 4.7.2 builds have been failing on Azure DevOps build agent (windows-2019) starting last evening/this morning. From this thread it seems that it should not have been upgraded, but I could not see any reason why the build is failing with the following message:
> ##[error]C:\Program Files\dotnet\sdk\5.0.100\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets(241,5): Error NETSDK1005: Assets file 'D:\a\1\s...\project.assets.json' doesn't have a target for 'net472'. Ensure that restore has run and that you have included 'net472' in the TargetFrameworks for your project.
> 
> I have tried the following flags:
> ` /p:TargetFrameworkVersion=v4.7.2 /p:tv=16`
> 
> Has there been a update in windows-2019 relating to .Net 5.0 SDK?

Can either explicitly downgrade the dotnet sdk with the UseDotNet task or update NuGet to at least 5.8 which should fix your [issue](https://developercommunity.visualstudio.com/content/problem/1248649/error-netsdk1005-assets-file-projectassetsjson-doe.html).

**Comment by ccjx** [comment]
> > Hi everyone, I'm dropping this question here as I thought this might be related.
> > My .Net framework 4.7.2 builds have been failing on Azure DevOps build agent (windows-2019) starting last evening/this morning. From this thread it seems that it should not have been upgraded, but I could not see any reason why the build is failing with the following message:
> > ##[error]C:\Program Files\dotnet\sdk\5.0.100\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets(241,5): Error NETSDK1005: Assets file 'D:\a\1\s...\project.assets.json' doesn't have a target for 'net472'. Ensure that restore has run and that you have included 'net472' in the TargetFrameworks for your project.
> > I have tried the following flags:
> > ` /p:TargetFrameworkVersion=v4.7.2 /p:tv=16`
> > Has there been a update in windows-2019 relating to .Net 5.0 SDK?
> 
> You can either explicitly downgrade the dotnet sdk with the UseDotNet task or update NuGet to at least 5.8 which should fix your [issue](https://developercommunity.visualstudio.com/content/problem/1248649/error-netsdk1005-assets-file-projectassetsjson-doe.html).

Thank you @smkanadl for the help. For anyone else facing this issue, upgrading Nuget to at least 5.8 solved this problem for a project on .Net Framework 4.7.2 (running on hosted agent windows-2019). I could not use UseDotNet as that is only for .Net Core and not for .Net Framework.

**Comment by DrGriff** [comment]
> "date will be defined later"

Could a date be confirmed please?  I'd like to stop actively checking this and just add a date to my diary for when I can remove the UseDotNet step.  Many thanks.

**Comment by AlenaSviridenko** [comment]
Hi @DrGriff ,
it is already available on Windows images since VS 16.8 brought it with itself. 
On Ubuntu and macOS images it will be added approximately in 2 weeks. But we are recommending keep using UseDotNet step even after it, just to be sure that your build won't be broken if the default .NET will change.

**Comment by SimonCropp** [comment]
>  But we are recommending keep using UseDotNet step even after it, just to be sure that your build won't be broken if the default .NET will change.

if that is the recommendation, then there is no point having dotnet on the default image. also doesnt UseDotNet significantly slow down a build, and also waste a non trivial amount of resources?

**Comment by MatthewSteeples** [comment]
@SimonCropp UseDotNet adds 3 seconds on our Azure Hosted builds (because what we're after is already installed, but it will install it if it isn't)

**Comment by SimonCropp** [comment]
@MatthewSteeples what will the impact be when the default dotnet on the VMs is 5.1?

**Comment by MatthewSteeples** [comment]
_In theory_ if it's one of the ones off these lists ([Windows](https://github.com/actions/virtual-environments/blob/main/images/win/Windows2019-Readme.md#net-core-sdk), [Ubuntu](https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu1804-README.md#net-core-sdk), [Mac](https://github.com/actions/virtual-environments/blob/main/images/macos/macos-10.15-Readme.md#language-and-runtime)) then it should just be a few seconds. It's when you want one that's newer than is available on the server that causes the delay

**Comment by mikeblakeuk** [comment]
Give Monday 14 Dec (aka Dec 14) 2020
When using vmImage: 'ubuntu-20.04'
and Agent name: 'Azure Pipelines 4'
and Agent machine name: 'fv-az879-972'
and Current agent version: '2.179.0'

then this fails with (SDK Version: 3.1.404)

```
##[error]/usr/share/dotnet/sdk/3.1.404/Microsoft.Common.CurrentVersion.targets(1177,5): Error MSB3644: The reference assemblies for .NETFramework,Version=v5.0 were not found. To resolve this, install the Developer Pack (SDK/Targeting Pack) for this framework version or retarget your application. You can download .NET Framework Developer Packs at https://aka.ms/msbuild/developerpacks
```

We could add the installer, but whats the point? It takes time and if a latest .net fails, we want to know.

Also, there is a side affect of using the installer that it changes the .net probing path so if you have 5.0 and 3.1 you need to install **both**

Please update the agents with the latest .net 5.0

Thanks
cc @AlenaSviridenko

**Comment by AlenaSviridenko** [comment]
@mikeblakeuk , based on our current deployment progress, Ubuntu images with .NET 5.0 will likely be fully deployed late 16th if there will be no unexpected issues.
Unfortunately, we cannot update all agents at once due to possible capacity issues and infrastructure, so we have to it iteratively.

**Comment by Cyberboss** [comment]
I've been experiencing intermittent issues restoring nuget pacakges on `windows-latest` over the past week. Is this related?

https://github.com/tgstation/tgstation-server/pull/1164/checks?check_run_id=15737103821

```
Build FAILED.

D:\a\tgstation-server\tgstation-server\src\Tgstation.Server.Host\Tgstation.Server.Host.csproj : error NU1101: Unable to find package BetterWin32Errors. No packages exist with this id in source(s): Microsoft Visual Studio Offline Packages [D:\a\tgstation-server\tgstation-server\tgstation-server.sln]
D:\a\tgstation-server\tgstation-server\src\Tgstation.Server.Host\Tgstation.Server.Host.csproj : error NU1101: Unable to find package Byond.TopicSender. No packages exist with this id in source(s): Microsoft Visual Studio Offline Packages [D:\a\tgstation-server\tgstation-server\tgstation-server.sln]
D:\a\tgstation-server\tgstation-server\src\Tgstation.Server.Host\Tgstation.Server.Host.csproj : error NU1101: Unable to find package Cyberboss.AspNetCore.AsyncInitializer. No packages exist with this id in source(s): Microsoft Visual Studio Offline Packages [D:\a\tgstation-server\tgstation-server\tgstation-server.sln]
D:\a\tgstation-server\tgstation-server\src\Tgstation.Server.Host\Tgstation.Server.Host.csproj : error NU1101: Unable to find package Cyberboss.SmartIrc4net.Standard. No packages exist with this id in source(s): Microsoft Visual Studio Offline Packages [D:\a\tgstation-server\tgstation-server\tgstation-server.sln]
D:\a\tgstation-server\tgstation-server\src\Tgstation.Server.Host\Tgstation.Server.Host.csproj : error NU1101: Unable to find package Discord.Net.WebSocket. No packages exist with this id in source(s): Microsoft Visual Studio Offline Packages [D:\a\tgstation-server\tgstation-server\tgstation-server.sln]
D:\a\tgstation-server\tgstation-server\src\Tgstation.Server.Host\Tgstation.Server.Host.csproj : error NU1101: Unable to find package GitLabApiClient. No packages exist with this id in source(s): Microsoft Visual Studio Offline Packages [D:\a\tgstation-server\tgstation-server\tgstation-server.sln]
...
```
And many others

**Comment by nullpainter** [comment]
> I've been experiencing intermittent issues restoring nuget packages on `windows-latest` over the past week. Is this related?
> 
> https://github.com/tgstation/tgstation-server/pull/1164/checks?check_run_id=15737103821
> 
> ```
> Build FAILED.
> 
> D:\a\tgstation-server\tgstation-server\src\Tgstation.Server.Host\Tgstation.Server.Host.csproj : error NU1101: Unable to find package BetterWin32Errors. No packages exist with this id in source(s): Microsoft Visual Studio Offline Packages [D:\a\tgstation-server\tgstation-server\tgstation-server.sln]
> D:\a\tgstation-server\tgstation-server\src\Tgstation.Server.Host\Tgstation.Server.Host.csproj : error NU1101: Unable to find package Byond.TopicSender. No packages exist with this id in source(s): Microsoft Visual Studio Offline Packages [D:\a\tgstation-server\tgstation-server\tgstation-server.sln]
> D:\a\tgstation-server\tgstation-server\src\Tgstation.Server.Host\Tgstation.Server.Host.csproj : error NU1101: Unable to find package Cyberboss.AspNetCore.AsyncInitializer. No packages exist with this id in source(s): Microsoft Visual Studio Offline Packages [D:\a\tgstation-server\tgstation-server\tgstation-server.sln]
> D:\a\tgstation-server\tgstation-server\src\Tgstation.Server.Host\Tgstation.Server.Host.csproj : error NU1101: Unable to find package Cyberboss.SmartIrc4net.Standard. No packages exist with this id in source(s): Microsoft Visual Studio Offline Packages [D:\a\tgstation-server\tgstation-server\tgstation-server.sln]
> D:\a\tgstation-server\tgstation-server\src\Tgstation.Server.Host\Tgstation.Server.Host.csproj : error NU1101: Unable to find package Discord.Net.WebSocket. No packages exist with this id in source(s): Microsoft Visual Studio Offline Packages [D:\a\tgstation-server\tgstation-server\tgstation-server.sln]
> D:\a\tgstation-server\tgstation-server\src\Tgstation.Server.Host\Tgstation.Server.Host.csproj : error NU1101: Unable to find package GitLabApiClient. No packages exist with this id in source(s): Microsoft Visual Studio Offline Packages [D:\a\tgstation-server\tgstation-server\tgstation-server.sln]
> ...
> ```
> 
> And many others

Same for me, FWIW:

```
\a\sanchez\sanchez\Sanchez.Workflow\Sanchez.Workflow.csproj : error NU1101: Unable to find package Serilog. No packages exist with this id in source(s): Microsoft Visual Studio Offline Packages [D:\a\sanchez\sanchez\Sanchez.sln]
D:\a\sanchez\sanchez\Sanchez.Workflow\Sanchez.Workflow.csproj : error NU1101: Unable to find package ShellProgressBar. No packages exist with this id in source(s): Microsoft Visual Studio Offline Packages [D:\a\sanchez\sanchez\Sanchez.sln]
D:\a\sanchez\sanchez\Sanchez.Workflow\Sanchez.Workflow.csproj : error NU1101: Unable to find package WorkflowCore. No packages exist with this id in source(s): Microsoft Visual Studio Offline Packages [D:\a\sanchez\sanchez\Sanchez.sln]
D:\a\sanchez\sanchez\Sanchez.Workflow\Sanchez.Workflow.csproj : error NU1101: Unable to find package SonarAnalyzer.CSharp. No packages exist with this id in source(s): Microsoft Visual Studio Offline Packages [D:\a\sanchez\sanchez\Sanchez.sln]
D:\a\sanchez\sanchez\Sanchez.Workflow\Sanchez.Workflow.csproj : error NU1101: Unable to find package Ardalis.GuardClauses. No packages exist with this id in source(s): Microsoft Visual Studio Offline Packages [D:\a\sanchez\sanchez\Sanchez.sln]
D:\a\sanchez\sanchez\Sanchez.Workflow\Sanchez.Workflow.csproj : error NU1101: Unable to find package FluentValidation. No packages exist with this id in source(s): Microsoft Visual Studio Offline Packages [D:\a\sanchez\sanchez\Sanchez.sln]
D:\a\sanchez\sanchez\Sanchez.Workflow\Sanchez.Workflow.csproj : error NU1101: Unable to find package Microsoft.Extensions.DependencyInjection.Abstractions. No packages exist with this id in source(s): Microsoft Visual Studio Offline Packages...

**Comment by Cyberboss** [comment]
Related issue with work around

**Comment by AlenaSviridenko** [comment]
Images are deployed everywhere, if you see any issues - please, file a new ticket.
Closing this one.

**Comment by muhammedazheruddin** [comment]
Hi all,

I'm learning ASP.NET CORE and getting this error while running the command "dotnet run" in my sandbox. Request you to kindly guide me here for the resolution.

Many thanks!
