### ISSUE TITLE
Update .NET Core SDK to 3.0.100

### ISSUE THREAD

**Issue by Cryru** [actions/virtual-environments#19]
**Tool information**
- Tool name: .NET Core SDK
- Add or update? Update
- Desired version: 3.0.100
- Approximate size: 150mb

**Virtual environments affected**
- [X] macOS 10.14
- [X] Ubuntu 16.04 LTS
- [X] Ubuntu 18.04 LTS
- [X] Windows Server 2016 R2
- [X] Windows Server 2019

**Can this tool be installed during the build?**
Yes using chocolatey and the other package managers it is possible to install it during build time. However, it takes ~3 min to do so and creates unnecessary traffic.

**Are you willing to submit a PR?**
Sure

**Comment by kaylangan** [comment]
Thanks for the suggestion! We're currently in the process of adding .NET Core SDK 3 to the images. They will be available in a coming update.

**Comment by Cryru** [comment]
Any updates?

**Comment by SimonCropp** [comment]
looking [here](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/software-installed-on-github-hosted-runners) this seems to be done already
