### ISSUE TITLE
Failing Jest tests on Windows does not result in failed CI

### ISSUE THREAD

**Issue by SimenB** [actions/virtual-environments#1904]
**Description**  
See e.g. https://github.com/facebook/jest/pull/10697/checks?check_run_id=1308922681

![image](https://user-images.githubusercontent.com/1404810/97194540-8baa3900-17aa-11eb-8275-cd92a529f204.png)

Even though we have assertion errors, CI still reports a passing test suite.

**Area for Triage**:  
JavaScript and Node.js

**Question, Bug, or Feature?**:  
Bug

**Virtual environments affected**  
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Ubuntu 20.04 LTS
- [ ] Windows Server 2016 R2
- [x] Windows Server 2019

**Expected behavior**  
The job should fail

**Actual behavior**  
It does not fail

**Repro steps**  
See https://github.com/SimenB/jest-exit-gh-actions (https://github.com/SimenB/jest-exit-gh-actions/runs/1309918833 at time of writing)

**Comment by maxim-lobanov** [comment]
@SimenB , I guess it can be related to different default shell. It is bash for Ubuntu / macOS but PowerShell for Windows.
Try to use bash on all platforms to see if it helps:
```
- run: <your_command>
  shell: bash
```

Related documentation: https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#using-a-specific-shell

**Comment by SimenB** [comment]
I'll give it a try! https://github.com/facebook/jest/pull/10714

Still seems like a bug, tho

**Comment by SimenB** [comment]
I was able to put together a reduced example - this seems to be a bug in Yarn v2. See https://github.com/SimenB/jest-exit-gh-actions

/cc @arcanis @merceyz

**Comment by SimenB** [comment]
@maxim-lobanov https://github.com/facebook/jest/pull/10714/checks?check_run_id=1309857051 completed, so swapping `shell` didn't make a difference

**Comment by maxim-lobanov** [comment]
@SimenB , Yep, it looks like a bug in yarn.
I have extended your example a bit to explicitly print exit code:
```
- run: |
    yarn test
    $LASTEXITCODE
  shell: pwsh
```

It prints exit code 1 on Ubuntu and macOS but prints 0 on Windows:
https://github.com/maxim-lobanov/jest-exit-gh-actions/runs/1309984690?check_suite_focus=true

**Comment by merceyz** [comment]
Indeed it is, fixed 11 days ago in https://github.com/yarnpkg/berry/pull/1985

**Comment by SimenB** [comment]
Can confirm installing yarn from sources fixes it 🎉 

![image](https://user-images.githubusercontent.com/1404810/97200120-18f08c00-17b1-11eb-892b-72a2bbf6d91b.png)

Thanks!
