### ISSUE TITLE
New Software - DynamicsSDK

### ISSUE THREAD

**Issue by s-abram** [actions/virtual-environments#1908]
Hi, 
I am using Azure pipelines with the agent spec of vs-2017-win2016.

Getting error:  "No agent found in pool Azure Pipelines which satisfies the following demand: DynamicsSDK. All demands: DynamicsSDK, Agent.Version -gtVersion 2.103.0"

Can you please install DynamicsSDK?

**Comment by maxim-lobanov** [comment]
@s-abram , it is prohibited to use demands with Hosted agents, please remove all demands and try to rerun builds.

From Azure DevOps documentation:
> Demands and capabilities are designed for use with self-hosted agents so that jobs can be matched with an agent that meets the requirements of the job. When using Microsoft-hosted agents, you select an image for the agent that matches the requirements of the job, so although it is possible to add capabilities to a Microsoft-hosted agent, you don't need to use capabilities with Microsoft-hosted agents.

All Hosted VMs have identical configuration and you shouldn't use demands

**Comment by s-abram** [comment]
thank you, I will try that.

**Comment by s-abram** [comment]
I did remove the demand but the build failed as it is looking for the software.

. : The term 'D:\a\10\s\$(DynamicsSDK)\PrepareForBuild.ps1' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again. At line:1 char:3 + . 'D:\a\10\s\$(DynamicsSDK)\PrepareForBuild.ps1' -DatabaseBackupToRes ... + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ + CategoryInfo : ObjectNotFound: (D:\a\10\s\$(Dyn...areForBuild.ps1:String) [], CommandNotFoundException + FullyQualifiedErrorId : CommandNotFoundException

**Comment by maxim-lobanov** [comment]
So looks like this tool is not installed on images. Could you please modify your first message to follow tool-request template: https://github.com/actions/virtual-environments/blob/main/.github/ISSUE_TEMPLATE/tool-request.md

**Comment by al-cheb** [comment]
Close, the new thread: https://github.com/actions/virtual-environments/issues/1910

**Comment by hugginssd** [comment]
I'm facing the same issue and the provided link is no longer found.

https://github.com/actions/virtual-environments/blob/main/.github/ISSUE_TEMPLATE/tool-request.md

Can anyone provide feedback on how this was resolved?
