### ISSUE TITLE
Add [DynamicsSDK]

### ISSUE THREAD

**Issue by s-abram** [actions/virtual-environments#1910]
**Tool information**
- Tool name: DynamicsSDK
- Tool license: Free
- Add or update? Add
- Desired version: 
- Approximate size: 
- If this is an add request:
  - Brief description of tool: Dynamics Software Development Kit
  - URL for tool's homepage: https://docs.microsoft.com/en-us/dynamics365/customerengagement/on-premises/developer/download-dynamics-365-sdk-v9
  - Provide a basic test case to validate the tool's functionality: 

**Area for Triage**:

**Question, Bug, or Feature?**:

**Virtual environments affected**
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Ubuntu 20.04 LTS
- [ X] Windows Server 2016 R2
- [ ] Windows Server 2019

**Can this tool be installed during the build?**

**Tool installation time in runtime**

**Are you willing to submit a PR?**

**Comment by al-cheb** [comment]
Hello, @s-abram 
You can install the Dynamic SDK libs in rutime - https://docs.microsoft.com/en-us/dynamics365/customerengagement/on-premises/developer/download-tools-nuget. It takes ~ 30s.

```
jobs:
  build:
    runs-on: windows-2016
    steps:
    - name: Install DynamicSDK
      shell: powershell
      run: |
        ##Download Plugin Registration Tool
        nuget install Microsoft.CrmSdk.XrmTooling.PluginRegistrationTool -O C:\Tools
        md C:\Tools\PluginRegistration
        $prtFolder = Get-ChildItem C:\Tools | Where-Object {$_.Name -match 'Microsoft.CrmSdk.XrmTooling.PluginRegistrationTool.'}
        move C:\Tools\$prtFolder\tools\*.* C:\Tools\PluginRegistration
        Remove-Item C:\Tools\$prtFolder -Force -Recurse
        
        ##Download CoreTools
        nuget install  Microsoft.CrmSdk.CoreTools -O C:\Tools
        md C:\Tools\CoreTools
        $coreToolsFolder = Get-ChildItem C:\Tools | Where-Object {$_.Name -match 'Microsoft.CrmSdk.CoreTools.'}
        move C:\Tools\$coreToolsFolder\content\bin\coretools\*.* C:\Tools\CoreTools
        Remove-Item C:\Tools\$coreToolsFolder -Force -Recurse
        ##Download Configuration Migration
        nuget install  Microsoft.CrmSdk.XrmTooling.ConfigurationMigration.Wpf -O C:\Tools
        md C:\Tools\ConfigurationMigration
        $configMigFolder = Get-ChildItem C:\Tools | Where-Object {$_.Name -match 'Microsoft.CrmSdk.XrmTooling.ConfigurationMigration.Wpf.'}
        move C:\Tools\$configMigFolder\tools\*.* C:\Tools\ConfigurationMigration
        Remove-Item C:\Tools\$configMigFolder -Force -Recurse
        ##Download Package Deployer 
        nuget install  Microsoft.CrmSdk.XrmTooling.PackageDeployment.WPF -O C:\Tools
        md C:\Tools\PackageDeployment
        $pdFolder = Get-ChildItem C:\Tools | Where-Object {$_.Name -match 'Microsoft.CrmSdk.XrmTooling.PackageDeployment.Wpf.'}
        move C:\Tools\$pdFolder\tools\*.* C:\Tools\PackageDeployment
        Remove-Item C:\Tools\$pdFolder -Force -Recurse
        ##Download Package Deployer PowerShell module
        nuget install Microsoft.CrmSdk.XrmTooling.PackageDeployment.PowerShell -O C:\Tools
        $pdPoshFolder = Get-ChildItem C:\Tools | Where-Object {$_.Name -match 'Microsoft.CrmSdk.XrmTooling.PackageDeployment.PowerShell.'}
        move C:\Tools\$pdPoshFolder\tools\*.* C:\Tools\PackageDeployment.PowerShell
        Remove-Item C:\Tools\$pdPoshFolder -Force -Recurse

```

**Comment by s-abram** [comment]
thank you.  would you be able to advise how to add this runtime install to the pipepline?

**Comment by al-cheb** [comment]
> thank you. would you be able to advise how to add this runtime install to the pipepline?

1. Create a pipeline - https://dev.to/michaelcurrin/intro-tutorial-to-ci-cd-with-github-actions-2ba8
2. Add step above to your pipeline 

```
steps:
    - name: Install DynamicSDK
      shell: powershell
      run: |
        ##Download Plugin Registration Tool
        ..................
    - name: Step2
      run:  echo "Hello, world!"
```

**Comment by s-abram** [comment]
Thank you.  I was able to execute the Install DynaicsSDK script but my next stp is not able to find where the SDK is installed.  Can you tell me what path I should be using for the DynamicsSDK folder or where the PrepareForBuild.ps1 script is being installed?

Here is the command I am tying to run:
$(DynamicsSDK)\PrepareForBuild.ps1 -DatabaseBackupToRestore "$(DatabaseBackupToRestore)" -Verbose -RestorePackagesAllFiles

**Comment by al-cheb** [comment]
> Thank you. I was able to execute the Install DynaicsSDK script but my next stp is not able to find where the SDK is installed. Can you tell me what path I should be using for the DynamicsSDK folder or where the PrepareForBuild.ps1 script is being installed?
> 
> Here is the command I am tying to run:
> $(DynamicsSDK)\PrepareForBuild.ps1 -DatabaseBackupToRestore "$(DatabaseBackupToRestore)" -Verbose -RestorePackagesAllFiles
We can't preinstalled this platform on our images due to license, size and os support limitations. You should use Azure Services - https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/perf-test/continuous-build-test-automation

**Comment by LuisVanegas17** [comment]
Hi, s-abram, I have exactly the same error, how do you solve this finally?
