### ISSUE TITLE
brew update on OS X fails with 

### ISSUE THREAD

**Issue by JasonGross** [actions/virtual-environments#1914]
**Description**  
Recently our builds (such as [this one](https://github.com/mit-plv/fiat-crypto/runs/1315697876)) started failing on just the OS  X runner with
```
fatal: 'origin' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: 'origin' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: 'origin' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: 'origin' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Error: Fetching /usr/local/Homebrew/Library/Taps/local/homebrew-openssl failed!
Fetching /usr/local/Homebrew/Library/Taps/local/homebrew-python2 failed!
fatal: invalid upstream 'origin/master'
fatal: invalid upstream 'origin/master'
```

**Area for Triage**:  Apple

**Question, Bug, or Feature?**:  Bug

**Virtual environments affected**  
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [X] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Expected behavior**  
I expect `brew update` to work fine.

**Actual behavior**  
`brew update` fails and makes the job fail

**Repro steps**  
https://github.com/mit-plv/fiat-crypto/runs/1315697876

**Comment by al-cheb** [comment]
Hello, @JasonGross 
We are working on fix for macOS. Temporary workaround - https://github.com/actions/virtual-environments/issues/1811#issuecomment-708480190

Close as duplicate :https://github.com/actions/virtual-environments/issues/1811
