### ISSUE TITLE
Update/Add Rust cargo-fmt

### ISSUE THREAD

**Issue by aibaars** [actions/virtual-environments#1916]
**Tool information**
- Tool name: Rust auto-formatter

When running `cargo fmt --all -- --check` on OSX I get the following error:
```
error: 'cargo-fmt' is not installed for the toolchain 'stable-x86_64-apple-darwin'
To install, run `rustup component add rustfmt --toolchain stable-x86_64-apple-darwin`
```
On both Ubuntu and Linux environments the cargo-fmt package is pre-installed. It would be nice to have a more consistent experience between environments.

**Area for Triage**:

**Question, Bug, or Feature?**:
Bug, other environments have this tool out of the box

**Virtual environments affected**
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [x] macOS 10.15
- [x] macOS 11.0
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Can this tool be installed during the build?**
```
rustup component add rustfmt --toolchain stable-x86_64-apple-darwin
```

**Tool installation time in runtime**
Very little

**Are you willing to submit a PR?**
Yes

**Comment by maxim-lobanov** [comment]
Hello @aibaars , thank you for feature request.
We don't have objections to add this module to macOS images for consistency.
Feel free to submit or please let us know and we will take care about it.

**Comment by aibaars** [comment]
@maxim-lobanov I think pr #1958 should do the trick.

**Comment by maxim-lobanov** [comment]
@aibaars , I have merged PR. Thank you for contribution.
Changes should be deployed with next image rollout (approximately next week).
We will keep issue opened until it is deployed

**Comment by aibaars** [comment]
Thanks!

**Comment by miketimofeev** [comment]
@aibaars the new image was deployed with cargo-fmt on board. I'm going to close the issue, but feel free to contact us if you have any concerns.
Thank you!
