### ISSUE TITLE
Job fails with: Error: The operation was canceled

### ISSUE THREAD

**Issue by f-squirrel** [actions/virtual-environments#1918]
**Description**  
Jobs randomly fails with `Error: The operation was canceled`

**Area for Triage**:  

**Bug**

**Virtual environments affected**  
- [ ] Ubuntu 16.04
- [x] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Expected behavior**  
Jobs are expected to run smoothly.

**Actual behavior**  
Jobs fail with the error:
```
Session terminated.
ERRO[0343] error waiting for container: unexpected EOF  
Error: The operation was canceled.
```
Failing job: https://github.com/vmware/concord-bft/runs/1314380260
Workflow: https://github.com/vmware/concord-bft/blob/master/.github/workflows/build_and_test.yml

**Comment by al-cheb** [comment]
Hello, @f-squirrel 
It could be related to lack of memory for container. Could you please test?
1. Clean up some tools
```
sudo rm -rf /usr/share/dotnet
sudo rm -rf /opt/ghc
sudo rm -rf "/usr/local/share/boost"
sudo rm -rf "$AGENT_TOOLSDIRECTORY"
```

2. Use memory swap limits for docker run:
`--memory-swap -1`

**Comment by f-squirrel** [comment]
@al-cheb , thank you for the quick reply.
I'll try and get back with the results.

**Comment by f-squirrel** [comment]
@al-cheb , the issue is not reproducible anymore.
Thank you very much for your help!

**Comment by cb-shivamagarwal** [comment]
If memory leak is not the issue, `Error: The operation was canceled` also comes up if the job run hits the timeout mentioned in the GitHub Actions Workflow file.

**Comment by masudpatwary** [comment]
Session terminated.
ERRO[0343] error waiting for container: unexpected EOF  
Error: The operation was canceled.

**Comment by Maxpicca-Li** [comment]
Hello, if a job randomly fails with `Error: The operation was canceled`, and the reason for not enough memory (runner memory is 1T, local tests can be executed normally) and timeouts can be drained, what could be the reason?

Failing job: https://github.com/OpenXiangShan/XiangShan/actions/runs/10862088821/job/30181075043
Workflow: https://github.com/OpenXiangShan/XiangShan/blob/master/.github/workflows/perf.yml
