### ISSUE TITLE
Update/Add SDL2

### ISSUE THREAD

**Issue by mslinklater** [actions/virtual-environments#192]
**Tool information**
- Tool name: SDL2
- Add or update? Add
- Desired version: Latest libsdl2-dev
- Approximate size: 
- If this is an add request:
  - Brief description of tool: sdl2 libraries to build against
  - URL for tool's homepage: https://www.libsdl.org/

**Area for Triage**: See https://github.com/actions/virtual-environments/tree/master/triage-rules.yml for areas
**Question, Bug, or Feature?**:

**Virtual environments affected**
- [X] macOS 10.15
- [X] Ubuntu 16.04 LTS
- [X] Ubuntu 18.04 LTS
- [X] Windows Server 2016 R2
- [X] Windows Server 2019

**Can this tool be installed during the build?**
I tried doing 'sudo apt-get install libsdl2-dev' but it fails with error 100

**Are you willing to submit a PR?**

**Comment by thejoebourneidentity** [comment]
Thanks for the suggestion, at this time the SDL2 library is not something we're going to add. Have you had any luck installing it as part of your build? If not, maybe we can help, please post over at the community forum https://github.community/t5/GitHub-Actions/bd-p/actions and maybe we can help get you going.

**Comment by elpiel** [comment]
For anyone landing here from a google search and still interested to install SDL2 you can follow this article CI workflow https://alexene.dev/2019/09/04/Github-actions-CI-rust-SDL2.html

Here's the solution:

```
steps:
    - uses: actions/checkout@v1
    - name: install_dependencies
      run: |
        sudo add-apt-repository -y "deb http://archive.ubuntu.com/ubuntu `lsb_release -sc` main universe restricted multiverse"
        sudo apt-get update -y -qq
        sudo apt-get install libsdl2-dev

```

**Comment by b5i** [comment]
And here's for macOS:
```
steps:
    - uses: actions/checkout@v3
    - name: Install SDL2
      run: brew install SDL2
```

If you get an error telling you that <SDL2/SDL.h> is not found, make sure you test both `/usr/local/include/SDL2` and `/opt/homebrew/include/SDL2` because Homebrew changed their default installation path in [Homebrew v3.0.0](https://stackoverflow.com/a/71186857/16456439), now using `/usr/local/` for Intel based Macs and `/opt/homebrew` Apple Silicons Macs.
