### ISSUE TITLE
Composer updated to v2?

### ISSUE THREAD

**Issue by carestad** [actions/virtual-environments#1924]
**Description**  
It seems that the composer version has been updated to v2 for runners now, which is causing a lot of distress since it isn't necessarily a plug-and-play upgrade. The [virtual environment documentation](https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-README.md#php) has not been updated to reflect this, and it seems to be causing some issues (for us at least).

Is there a composer@v1 version still available or is the global `composer` now replaced with v2 for good?

**Area for Triage**:  
PHP

**Question, Bug, or Feature?**:  
Question

**Virtual environments affected**  
- [x] Ubuntu 16.04
- [x] Ubuntu 18.04
- [x] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Expected behavior**  
Successful running of `composer install` in our existing Laravel project.

**Actual behavior**  

`composer install` now fails due to dependencies not being ready for composer@v2.

**Repro steps**  

1. Check out existing Laravel project
2. Run `composer install`

**Comment by carestad** [comment]
It seems this is due to the [PHP installer script](https://github.com/actions/virtual-environments/blob/main/images/linux/scripts/installers/php.sh#L94) just downloads the most recent version of composer from its installer URL (as described here: https://getcomposer.org/download/)

Perhaps it could be an idea to just curl/wget the latest [v1](https://getcomposer.org/composer-1.phar) and/or [v2](https://getcomposer.org/composer-2.phar) instead?

**Comment by tyrann0us** [comment]
Workaround using [`shivammathur/setup-php`](https://github.com/marketplace/actions/setup-php-action):
```
- name: Force Composer v1
  uses: shivammathur/setup-php@v2
  with:
    tools: composer:v1
```
Also see https://github.com/marketplace/actions/setup-php-action#wrench-tools-support.

<img width="1085" alt="Bildschirmfoto 2020-10-28 um 14 20 14" src="https://user-images.githubusercontent.com/8144115/97441171-b5896a00-1928-11eb-9e61-525d3d3cec78.png">

**Comment by al-cheb** [comment]
Hello, @carestad 
As you mentioned above, we always try to install the latest version. If a deployment is not yet complete, we don't update documentation files in main branch. You can find a documentation file for current build:

![image](https://user-images.githubusercontent.com/47745270/97442592-1457df00-193b-11eb-8251-d7f063ce8b8e.png)

**Comment by tyrann0us** [comment]
Not sure if this is clear or not: Contrary to the checkboxes ticked by @carestad, this issue not only affects Ubuntu 20.04, but also Ubuntu 18.04 (which is `ubuntu-latest` still).

**Comment by carestad** [comment]
> Hello, @carestad
> As you mentioned above, we always try to install the latest version. If a deployment is not yet complete, we don't update documentation files in main branch. You can find a documentation file for current build or try to find a pr with delta - [actions/virtual-environments/pulls](https://github.com/actions/virtual-environments/pulls) (e.g. #1901):
> 
> ![image](https://user-images.githubusercontent.com/47745270/97442592-1457df00-193b-11eb-8251-d7f063ce8b8e.png)

Aha! Nice to know. Thanks for the info. :+1:

**Comment by carestad** [comment]
> Not sure if this is clear or not: Contrary to the checkboxes ticked by @carestad, this issue not only affects Ubuntu 20.04, but also Ubuntu 18.04 (which is `ubuntu-latest` still).

That is true. The readme for 18.04 mentions this, and refers to this issue regarding that: https://github.com/actions/virtual-environments/issues/1816

**Comment by al-cheb** [comment]
The documentation files related to Ubuntu were updated in main branch.

**Comment by zauni** [comment]
As a temporary workaroung it also helps to have a script section with `sudo composer self-update --1` in it.

**Comment by Chrico** [comment]
> As a temporary workaround it also helps to have a script section with sudo composer self-update --1 in it.

This will not work 100% safe, since the default User is "runner" and with `sudo` you'll write with a different User and change the folder permissions for Composer cache, which might causes problems for Composer and Composer Plugins which are trying to write to that cache folder.

```
sudo composer self-update --1
You are running composer as "root", while "/home/runner/.composer" is owned by "runner"
```

which results in:

```
Cannot create cache directory /home/runner/.composer/cache/repo/https---repo.packagist.org/, or directory is not writable. Proceeding without cache
Cannot create cache directory /home/runner/.composer/cache/files/, or directory is not writable. Proceeding without cache
Cannot create cache directory /home/runner/.composer/cache/repo/https---repo.packagist.org/, or directory is not writable. Proceeding without cache
```

**Comment by tyrann0us** [comment]
Am I the only one who finds it problematic that a "low-level API" like Composer has received a major upgrade on an existing operating system? I'm all for doing that on `ubuntu-20.04`, but Composer `v2` breaks backward compatibility, so it should not be updated automatically on existing OSs IMHO.

The AWS CLI has not been updated to `v2` either, although this version has been [available for a long time](https://github.com/aws/aws-cli/releases/tag/2.0.0).

**Comment by zauni** [comment]
@Chrico Good to know!
I tried this script section in a Azure pipeline and here it was okay. Or maybe we don't have plugins which use the cache folder.

**Comment by hanoii** [comment]
> This will not work 100% safe, since the default User is "runner" and with `sudo` you'll write with a different User "root".

In relation to https://github.com/actions/virtual-environments/issues/1924#issuecomment-719617834 I am doing 

```yml
    - name: Make sure we are using composer v1
      run: |
        sudo composer self-update --1
        sudo chown $USER $HOME/.composer
```

Early on `steps:` which should make it 100% safe. At least is working for me and I am using the cache.
