### ISSUE TITLE
Update Boost version 1.74

### ISSUE THREAD

**Issue by ahaeber** [actions/virtual-environments#1925]
**Tool information**
- Tool name: Boost
- Tool license: Boost software license (https://www.boost.org/LICENSE_1_0.txt)
- Add or update? Update (in https://github.com/actions/boost-versions)
- Desired version: 1.74
- Approximate size: 

**Area for Triage**:
C/C++

**Question, Bug, or Feature?**:
Question

**Virtual environments affected**
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

We started working on a Azure Pipeline to build our C++ application. Because we use Boost 1.74 we would like to see support for that. At https://github.com/actions/boost-versions it says that we should submit issues to this project to request support for new Boost versions.

Will we be able to follow the workaround suggested in https://github.com/actions/virtual-environments/issues/1847 to download a release for 1.74 and use it on a hosted agent?

**Comment by al-cheb** [comment]
Hello, @ahaeber 
Which OS are you planning to use?

**Comment by ahaeber** [comment]
Hi @al-cheb,
We currently build with Windows 2016 so hopefully that will work fine.

**Comment by al-cheb** [comment]
Hello, @ahaeber 
You can install boost 1.74 in runtime on Windows Server 2016.

Use resources to donwload:
https://sourceforge.net/projects/boost/files/boost-binaries/1.74.0/
https://bintray.com/boostorg/release/boost-binaries/1.74.0#files/1.74.0/binaries

```
- run: |
        $url64 = "https://bintray.com/boostorg/release/download_file?file_path=1.74.0%2Fbinaries%2Fboost_1_74_0-msvc-14.1-32.exe"
        $url86 = "https://bintray.com/boostorg/release/download_file?file_path=1.74.0%2Fbinaries%2Fboost_1_74_0-msvc-14.1-64.exe"
        $path = "C:\boost.exe"
        [Net.WebClient]::new().DownloadFile($url86, $path)
        Start-Process C:\boost.exe -ArgumentList "/DIR=C:\boost","/VERYSILENT" -Wait
        Get-ChildItem C:\boost
```

**Comment by maxim-lobanov** [comment]
Hello,
Per our internal discussion, we wouldn't like bake Boost 1.74 into the images because it is pretty huge library that requires extra effort to maintain.
Provided snippet should install it in runtime and should work for the most of the cases.

Please let us know if you have any additional questions
