### ISSUE TITLE
"brew install octave" fails

### ISSUE THREAD

**Issue by rdzman** [actions/virtual-environments#1926]
**Description**  
A previously working workflow is now failing at the command `brew install octave`. It appears it may be related to a dependency on `python@3.9` (possibly new?) which fails at the `brew link` step.

**Area for Triage**:  
Apple

**Question, Bug, or Feature?**:  
Bug

**Virtual environments affected**  
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [x] macOS 10.15
- [x] macOS 11.0
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Expected behavior**  
Successful install of `octave`.

**Actual behavior**  
`brew install octave` fails. The only error lines I see in the log are:
```
==> Installing octave dependency: python@3.9
==> Pouring python@3.9-3.9.0_1.catalina.bottle.tar.gz
Error: The `brew link` step did not complete successfully
Warning: These files were overwritten during `brew link` step:
The formula built, but is not symlinked into /usr/local
Could not symlink lib/pkgconfig/python3-embed.pc
Target /usr/local/lib/pkgconfig/python3-embed.pc
is a symlink belonging to python@3.8. You can unlink it:
  brew unlink python@3.8

To force the link and overwrite all conflicting files:
  brew link --overwrite python@3.9

To list all files that would be deleted:
  brew link --overwrite --dry-run python@3.9

Possible conflicting files are:
/usr/local/lib/pkgconfig/python3-embed.pc -> /usr/local/Cellar/python@3.8/3.8.6/lib/pkgconfig/python3-embed.pc
/usr/local/lib/pkgconfig/python3.pc -> /usr/local/Cellar/python@3.8/3.8.6/lib/pkgconfig/python3.pc
/usr/local/Frameworks/Python.framework/Headers -> /usr/local/Cellar/python@3.8/3.8.6/Frameworks/Python.framework/Headers
/usr/local/Frameworks/Python.framework/Python -> /usr/local/Cellar/python@3.8/3.8.6/Frameworks/Python.framework/Python
/usr/local/Frameworks/Python.framework/Resources -> /usr/local/Cellar/python@3.8/3.8.6/Frameworks/Python.framework/Resources
/usr/local/Frameworks/Python.framework/Versions/Current -> /usr/local/Cellar/python@3.8/3.8.6/Frameworks/Python.framework/Versions/Current
/usr/local/bin/2to3
/usr/local/bin/idle3
/usr/local/bin/pydoc3
/usr/local/bin/python3
/usr/local/bin/python3-config
/usr/local/share/man/man1/python3.1

They have been backed up in /Users/runner/Library/Caches/Homebrew/Backup
.
.
.
==> Installing octave
==> Pouring octave-5.2.0_10.catalina.bottle.tar.gz
🍺  /usr/local/Cellar/octave/5.2.0_10: 2,266 files, 55.2MB
==> Caveats
.
.
.
Error: Process completed with exit code 1.
```

**Repro steps**  
Use a workflow with OS set to `macos-latest` with the following lines:
```
brew update
brew install octave
```

For an example, see the `ci-testing` branch of the [MP-Test repo](https://github.com/MATPOWER/mptest).

**Comment by maxim-lobanov** [comment]
Hello @rdzman , this issue is not related to Hosted images. I can reproduce it on both old and new images (20201018.1 and 20201026.2).
I even can reproduce it locally using the following commands:
```
brew update
brew install python@3.9
```
![image](https://user-images.githubusercontent.com/16715858/97487725-4a628680-196e-11eb-8722-034329f6ec8b.png)

It is definitely issue on brew side.
I could be wrong but it was introduced by this commit: https://github.com/Homebrew/homebrew-core/commit/200fc9d393a9ec9f2830c493b1013320f6bdb182

At least If I run
```
brew update
cd $(brew --repository)/Library/Taps/homebrew/homebrew-core
git checkout  a4d29eb6431ac9b57f07d6b29f3c5a1238ef2370
brew install octave
```
It works as expected. `a4d29eb6431ac9b57f07d6b29f3c5a1238ef2370` is last commit before this change.

@rdzman I suggest to report this issue to brew.

**Comment by maxim-lobanov** [comment]
I guess it could be related to the fact that `python@3.9` was set as default formula 8 hours ago but when `python@3.9` was initially added to image (when image was built) it was not default. The same for my local box.

**Comment by maxim-lobanov** [comment]
@rdzman , Brew team has fixed the formula with https://github.com/Homebrew/homebrew-core/pull/63665 and now it works as expected 🚀 
I am closing the issue but please let me know if you have any concerns
