### ISSUE TITLE
boost::serialization from the boost 1.74 library fails to compile on AppleClang

### ISSUE THREAD

**Issue by jngrad** [actions/virtual-environments#1927]
**Description**  
`brew install boost` install boost 1.74, which is not compatible with the AppleClang 12 compiler. Compiling C++ code containing a include to `boost::serialization` headers can fail with `error: explicit specialization of undeclared template struct 'version'`. Can be solved by rolling back to boost 1.73.

**Area for Triage**:  

**Question, Bug, or Feature?**:  
Bug

**Virtual environments affected**  
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [x] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Expected behavior**  
`brew install boost boost-mpi` should install a boost version other than 1.74.
`brew install boost@1.73 boost-mpi@1.73` should install the 1.73 version.

**Actual behavior**  
`brew install boost boost-mpi` install the 1.74 version, which cannot compile with AppleClang: [run 1322746536](https://github.com/jngrad/espresso/runs/1322746536).
The previous version of boost available until today was 1.73, but cannot be installed anymore: [run 1322911956](https://github.com/jngrad/espresso/runs/1322911956), [run 1322700474](https://github.com/jngrad/espresso/runs/1322700474).

**Repro steps**  

1. run `brew install boost boost-mpi`
2. compile any .cpp file containing `#include <boost/serialization/optional.hpp>` with AppleClang

Here is a minimal project: [jngrad/espresso@boost174-appleclang12](https://github.com/jngrad/espresso/tree/boost174-appleclang12). The GitHub Action fails.

The regression was introduced in the boost 1.74 library and will probably get fixed in 1.75. See tickets boostorg/serialization#210 and boostorg/serialization#217. Here are links to the MWE that [passes with 1.73](https://gcc.godbolt.org/z/5vq8r6) and [fails with 1.74](https://gcc.godbolt.org/z/67s1o3).

**Comment by maxim-lobanov** [comment]
@jngrad Hello,
Could you please clarify what is the issue with GitHub Actions images? We don't provide boost on MacOS images and don't control version that is installed from brew.

**Comment by jngrad** [comment]
> We don't provide boost on MacOS images and don't control version that is installed from brew.

My mistake. Ticket can be closed. Sorry for the inconvenience!

**Comment by maxim-lobanov** [comment]
Sure, no problem.
I suggest reporting this issue to brew or boost team. Probably they can provide formula for 1.73 separately from 1.74
