### ISSUE TITLE
[macOS] Default Python will be upgraded to 3.9

### ISSUE THREAD

**Issue by AlenaSviridenko** [actions/virtual-environments#1929]
**Breaking changes**
Default Python will be upgraded from 3.8 to 3.9 on macOS images

**Target date**
Deployment of these changes will be started on November, 16 and will take a few days.

**The motivation for the changes**
Homebrew set Python 3.9 as a default Python formula, and there is no simple option to keep Python 3.8 as a default version.

**Possible impact**
Project dependencies that are not supporting Python 3.9 might be impacted.

- [x] macOS 10.13
- [x] macOS 10.14
- [x] macOS 10.15
- [x] macOS 11.0
- [ ] Windows 2016
- [ ] Windows 2019
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04

**Mitigation ways**
Please, consider using [actions/setup-python](https://github.com/marketplace/actions/setup-python) (for GitHub Actions) or [UsePython](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/tool/use-python-version?view=azure-devops) (for Azure Pipelines) to switch Python versions based on your project requirements.

**Comment by MaksimZhukov** [comment]
Hello everyone!
The default Python version has been updated to 3.9 on the macOS 10.15 and macOS 11.0.
The macOS 10.13 and macOS 10.14 images are deployed once a month. Python 3.9 as a default version for these images will be delivered with the next image rollout which will take approximately 1-2 weeks.

I'm closing this issue, but feel free to contact us if you have any concerns.
