### ISSUE TITLE
Update NodeJS tools to 12.14

### ISSUE THREAD

**Issue by cbundy** [actions/virtual-environments#193]
**Tool information**
- Tool name: NodeJS
- Update
- Desired version: 12.14
- Approximate size: 
- Reason: Latest security release of LTS which addresses vulnerability in NPM

**Area for Triage**: JavaScript and Node.js
**Question, Bug, or Feature?**: Feature

**Virtual environments affected**
- [ ] macOS 10.15
- [x] Ubuntu 16.04 LTS
- [x] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [x] Windows Server 2019

**Comment by alepauly** [comment]
confirmed deployed.

**Comment by bryanmacfarlane** [comment]
Note that for future reference, while waiting on versions like this, you can add actions/setup-node to workflow and specify that exact version.  It will pull it and only add 10 or seconds to your build.
