### ISSUE TITLE
Update Xamarin.iOS 14.2

### ISSUE THREAD

**Issue by arkadiuszokon** [actions/virtual-environments#1935]
**Tool information**
- Tool name: Xamarin.iOS
- Tool license: http://download.xamarin.com/content/licenses/Xamarin.Forms.rtf
- Add or update? update
- Desired version: 14.2.*.*
- Approximate size: 
- If this is an add request:
  

**Area for Triage**:
Area: Xamarin

**Question, Bug, or Feature?**:

**Virtual environments affected**
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [x] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Can this tool be installed during the build?**

**Tool installation time in runtime**

**Are you willing to submit a PR?**

**Comment by al-cheb** [comment]
The Xamarin.IOS was updated in the https://github.com/actions/virtual-environments/pull/1930 PR and waiting for deployment rollout.

**Comment by arkadiuszokon** [comment]
@al-cheb there is no way to speed up this rollout? current version is not compatible with latest Xamarin.Forms package which is required for latest ios version 14.1 ;) 

I got typical errors on devops pipelines for not compatible Xamarin.iOS version like:

error GBDAA8BF8: cannot find protocol declaration for 'NSFileProviderItemDecorating'
error GBDAA8BF8: cannot find protocol declaration for 'NSFileProviderItemFlags'

MTOUCH : error MT2101: Can't resolve the reference 'System.Void UIKit.UIDatePicker::set_PreferredDatePickerStyle(UIKit.UIDatePickerStyle)', referenced from the method 'System.Void Xamarin.Forms.Platform.iOS.DatePickerRendererBase`1::OnElementChanged(Xamarin.Forms.Platform.iOS.ElementChangedEventArgs`1<Xamarin.Forms.DatePicker>)' in 'Xamarin.iOS, Version=0.0.0.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065'

**Comment by maxim-lobanov** [comment]
Hello everyone!
Deployment has been finished. Xamarin.iOS 14.2 is available on image.
Please pay attention that it is not set by default. You can find more info how to switch Xamarin in https://github.com/actions/virtual-environments/issues/1698#issuecomment-705012474
