### ISSUE TITLE
GCC has -Werror by default

### ISSUE THREAD

**Issue by phadej** [actions/virtual-environments#1938]
**Description**  

When `gcc` invoked without any specific parameters there is `-Werror`

**Question, Bug, or Feature?**:  

Bug

**Virtual environments affected**  
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [x] macOS 10.15
- [x] macOS 11.0
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

I'm not sure which macOS environment it is: 

**Expected behavior**  

`-Werror` shouldn't be enabled by default.

**Actual behavior**  

`-Werror` is enabled by default.

**Repro steps**  

Example: https://github.com/haskell/cabal/pull/7140/checks?check_run_id=1331569269

```
stderr:
*** Exception: Command /usr/bin/gcc -o uselib UseLib.c -l myforeignlib -L /Users/runner/work/cabal/cabal/cabal-testsuite/PackageTests/ForeignLibs/setup.dist/usr/lib failed.
Output:
UseLib.c:5:3: error: implicit declaration of function 'myForeignLibInit' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
  myForeignLibInit();
  ^
```

**Comment by vsafonkin** [comment]
Hello @phadej, thank you for your report, gcc compiler on macOS image is clang launcher that provided from Xcode, so, unfortunately we cannot change it default options.

**Comment by vsafonkin** [comment]
I've closed this issue, @phadej feel free to reopen it if you have any questions, thanks!

**Comment by phadej** [comment]
I would been helpful if there were a possibility to `ssh` (remote access) the builder. I cannot provide more info: My local mac's `gcc = clang` doesn't have such `-Werror` behaviour, but it is most likely of different version.

Who knows.

**Comment by JamesTheAwesomeDude** [comment]
Is this closed as "completed", or "wontfix"?

This is [breaking one of my own builds](https://github.com/JamesTheAwesomeDude/pypqc/actions/runs/7718046156/job/21038489329#step:5:459), and is currently a blocker for getting Mac OS wheels published.

Is there *any* way to suppress `-Werror` on Mac OS on Github Actions?

**Comment by JamesTheAwesomeDude** [comment]
Great workaround I found; modify to fit your own build system:

```python
  ...
  if platform.system() == 'Darwin':
    # https://developer.apple.com/documentation/xcode-release-notes/xcode-12-release-notes
    # https://github.com/actions/virtual-environments/issues/2440
    # https://github.com/actions/runner-images/blob/macOS-11/20210523.1/images/macos/toolsets/toolset-11.json#L3
    # https://github.com/actions/runner-images/issues/1938
    extra_compile_args.extend([
        '-DHB_NO_PRAGMA_GCC_DIAGNOSTIC_ERROR',   # https://github.com/harfbuzz/harfbuzz/issues/1763#issuecomment-500574443
        '-Wno-error=implicit-function-declaration',
        '-Wno-error=pedantic',
        '-Wno-error=macro-redefined',
    ])
  ...
```

(obviously, add more flags for whatever other pending security holes await your project)
