### ISSUE TITLE
Deleting files on ubuntu based runner is sometimes extremely slow, possibly applies to all disk IO

### ISSUE THREAD

**Issue by lhotari** [actions/virtual-environments#1939]
**Description**  

In some cases, deleting a lot of files is extremely slow on ubuntu-latest based runners. The disk IO operations seem to become slow after this point.

2 examples from apache/pulsar workflows:
"clean disk" step took 7 minutes 25 seconds
https://github.com/apache/pulsar/pull/8402/checks?check_run_id=1323968384#step:8:1
"clean disk" took 6 minutes 47 seconds
https://github.com/apache/pulsar/runs/1331699395?check_suite_focus=true

Sometimes "clean disk" completes in 26-27 seconds.

This is the "clean disk" step used in apache/pulsar workflows:
```
      - name: clean disk
        if: steps.docs.outputs.changed_only == 'no'
        run: |
          sudo swapoff -a
          sudo rm -rf /swapfile /usr/share/dotnet /usr/local/lib/android /opt/ghc
          sudo apt clean
          docker rmi $(docker images -q) -f
          df -h
```

**Virtual environments affected**  
- [x] Ubuntu 16.04
- [x] Ubuntu 18.04
- [x] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Expected behavior**  

Deleting files should be fast and disk IO should be consistent. The "clean disk" step should take less than 30 seconds to complete.

**Actual behavior**  

Deleting files is slow and "clean disk" step takes sometimes over 7 minutes. After this the disk IO seems to be very slow.

**Repro steps**  

See https://github.com/apache/pulsar workflows, for example https://github.com/apache/pulsar/blob/master/.github/workflows/ci-integration-process.yaml . History of previous runs that failed in https://github.com/apache/pulsar/actions?query=is%3Afailure .
A lot of the failed ones fail because the performance is so bad.

1. Create a workflow that contains a similar "clean disk" step as https://github.com/apache/pulsar/blob/master/.github/workflows/ci-integration-process.yaml .
2. Run multiple times, at different times of the day. Sometimes it's very slow.

**Comment by lhotari** [comment]
I looked on the community forum for similar reports. I did find one about inconsistent CPU and IOPS performance, that was https://github.community/t/github-actions-have-inconsistent-cpu-and-iops/123185/7

**Comment by lhotari** [comment]
I was doing some analysis on the Github Runner VM using https://github.com/marketplace/actions/debugging-with-tmate action which gives a shell inside a running job.

One detail that I noticed is that the the root filesystem is using `discard` option:
```
$ mount |grep /dev/sd
/dev/sda1 on / type ext4 (rw,relatime,discard)
/dev/sda15 on /boot/efi type vfat (rw,relatime,fmask=0022,dmask=0022,codepage=437,iocharset=iso8859-1,shortname=mixed,errors=remount-ro,discard)
/dev/sdb1 on /mnt type ext4 (rw,relatime,x-systemd.requires=cloud-init.service)
```

The documentation Azure documentation mentions in [TRIM/UNMAP support for Linux in Azure](https://docs.microsoft.com/en-us/azure/virtual-machines/linux/attach-disk-portal#trimunmap-support-for-linux-in-azure):
> In some cases, the `discard` option may have performance implications

Blog post of the performance implications of `discard`: https://patrick-nagel.net/blog/archives/337 (not about Azure Disks)

It's possible to switch discard off on the fly by running `sudo mount -o remount,nodiscard /` command. 

It possible to improve the filesystem performance even further:
* `commit=999999`, effectively disables automatic syncing to disk (default is every 5 seconds)
* `nobarrier`, loosen data consistency to optimize performance (see ext4 docs for more details)
* `data=writeback` (not supported for remount), loosen data consistency to optimize performance (see ext4 docs for more details)

ext4 docs: https://www.kernel.org/doc/Documentation/filesystems/ext4.txt

example of a workflow step to optimize filesystem performance

```
      - name: optimize filesystem performance
        run: |
          sudo mount -o remount,nodiscard,commit=999999,nobarrier /
          sudo mount -o remount,nodiscard,commit=999999,nobarrier /mnt
```

I'll create a separate issue for fine tuning the mount options.

I also noticed that the VM has swappiness set to 60. This is bad for jobs that use a lot of RAM. A better default for swappiness would be 10. I'll create a separate issue about this change.

**Comment by lhotari** [comment]
It might be the case that remounting would change the discard or barrier settings at all. Therefore it's hard to experiment the impact unless the VM has the mount options from the boot. I added a comment in https://github.com/actions/virtual-environments/pull/1942#issuecomment-719917419 with references.

**Comment by lhotari** [comment]
@andy-mishechkin @miketimofeev  PTAL #1942 . I created that PR after investigating the issue with build performance. It would be possible to optimize the Linux OS settings to improve performance for most Github Actions users. 
I'd be happy to receive feedback on that PR.  Thank you

**Comment by maxim-lobanov** [comment]
Hello @lhotari , thank you for submitting PR and providing really great context / explanation.
Sorry for delay, we are focusing on some internal staff this week & begin of the next week.
We will be able to take a look and review your proposal at the middle of next week.
Thank you for your patience

**Comment by lhotari** [comment]
> We will be able to take a look and review your proposal at the middle of next week.

@maxim-lobanov ping, PTAL #1942

**Comment by LeonidLapshin** [comment]
Hey, @lhotari !
We have tested your changes with 'fio':
Random read-write performance
`time fio --randrepeat=1 --ioengine=libaio --direct=1 --gtod_reduce=1 --name=test --filename=test --bs=4k --iodepth=64 --size=4G --readwrite=randrw --rwmixread=75`

Random write performance
`time fio --randrepeat=1 --ioengine=libaio --direct=1 --gtod_reduce=1 --name=test --filename=test2 --bs=4k --iodepth=64 --size=4G --readwrite=randwrite`

Random read performance
`time fio --randrepeat=1 --ioengine=libaio --direct=1 --gtod_reduce=1 --name=test --filename=test3 --bs=4k --iodepth=64 --size=4G --readwrite=randread`

10 times before changes and 10 times after, but unfortunately do not see any improvement in test results (execution time, IOPS, utilization) within the margin of error (1%). 

The average output (before and after changes) is:
```
Random read-write performance
test: (g=0): rw=randrw, bs=(R) 4096B-4096B, (W) 4096B-4096B, (T) 4096B-4096B, ioengine=libaio, iodepth=64
fio-3.16
Starting 1 process
test: Laying out IO file (1 file / 4096MiB)

test: (groupid=0, jobs=1): err= 0: pid=2138: Sat Dec 12 23:08:14 2020
  read: IOPS=6265, BW=24.5MiB/s (25.7MB/s)(3070MiB/125441msec)
   bw (  KiB/s): min=23848, max=27344, per=100.00%, avg=25065.42, stdev=297.93, samples=250
   iops        : min= 5962, max= 6836, avg=6266.35, stdev=74.49, samples=250
  write: IOPS=2093, BW=8375KiB/s (8576kB/s)(1026MiB/125441msec); 0 zone resets
   bw (  KiB/s): min= 7704, max= 9440, per=100.00%, avg=8377.54, stdev=249.22, samples=250
   iops        : min= 1926, max= 2360, avg=2094.37, stdev=62.31, samples=250
  cpu          : usr=2.03%, sys=8.48%, ctx=145209, majf=0, minf=8
  IO depths    : 1=0.1%, 2=0.1%, 4=0.1%, 8=0.1%, 16=0.1%, 32=0.1%, >=64=100.0%
     submit    : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     complete  : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.1%, >=64=0.0%
     issued rwts: total=785920,262656,0,0 short=0,0,0,0 dropped=0,0,0,0
     latency   : target=0, window=0, percentile=100.00%, depth=64

Run status group 0 (all jobs):
   READ: bw=24.5MiB/s (25.7MB/s), 24.5MiB/s-24.5MiB/s (25.7MB/s-25.7MB/s), io=3070MiB (3219MB), run=125441-125441msec
  WRITE: bw=8375KiB/s (8576kB/s), 8375KiB/s-8375KiB/s (8576kB/s-8576kB/s), io=1026MiB (1076MB), run=125441-125441msec
  
Disk stats (read/write):
  sdb: ios=785075/262552, merge=28/56, ticks=5927336/1964472, in_queue=6592212, util=99.65%

real	3m7.157s
user	0m4.131s
sys	0m15.904s

Random write performance
test: (g=0): rw=randwrite, bs=(R) 4096B-4096B, (W) 4096B-4096B, (T) 4096B-4096B, ioengine=libaio, iodepth=64
fio-3.16
Starting 1 process
test: Laying out IO file (1 file / 4096MiB)

test: (groupid=0, jobs=1): err= 0: pid=2418: Sat Dec 12 23:15:13 2020
  write: IOPS=2922, BW=11.4MiB/s (11.0MB/s)(4096MiB/358773msec); 0 zone resets
   bw (  KiB/s): min= 8152, max=18912, per=99.92%, avg=11681.02, stdev=634.88, samples=717
   iops        : min= 2038, max= 4728, avg=2920.25, stdev=158.72, samples=717
  cpu          : usr=0.83%, sys=6.03%, ctx=149423, majf=0, minf=9
  IO depths    : 1=0.1%, 2=0.1%, 4=0.1%, 8=0.1%, 16=0.1%, 32=0.1%, >=64=100.0%
     submit    : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     complete  : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.1%, >=64=0.0%
     issued rwts: total=0,1048576,0,0 short=0,0,0,0 dropped=0,0,0,0
     latency   : target=0, window=0, percentile=100.00%, depth=64

Run status group 0 (all jobs):
  WRITE: bw=11.4MiB/s (11.0MB/s), 11.4MiB/s-11.4MiB/s (11.0MB/s-11.0MB/s), io=4096MiB (4295MB), run=358773-358773msec

Disk stats (read/write):
  sdb: ios=10/1049656, merge=0/30108, ticks=179/22426330, in_queue=20905696, util=99.66%

real	5m59.419s
user	0m3.733s
sys	0m22.751s

Random read performance
test: (g=0): rw=randread, bs=(R) 4096B-4096B, (W) 4096B-4096B, (T) 4096B-4096B, ioengine=libaio, iodepth=64
fio-3.16
Starting 1 process
test: Laying out IO file (1 file / 4096MiB)

test: (groupid=0, jobs=1): err= 0: pid=2828: Sat Dec 12 23:19:20 2020
  read: IOPS=8360, BW=32.7MiB/s (34.2MB/s)(4096MiB/125424msec)
   bw (  KiB/s): min=32974, max=36776, per=100.00%, avg=33443.97, stdev=216.23, samples=250
   iops        : min= 8243, max= 9194, avg=8360.98, stdev=54.06, samples=250
  cpu          : usr=1.79%, sys=8.14%, ctx=137276, majf=0, minf=73
  IO depths    : 1=0.1%, 2=0.1%, 4=0.1%, 8=0.1%, 16=0.1%, 32=0.1%, >=64=100.0%
     submit    : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     complete  : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.1%, >=64=0.0%
     issued rwts: total=1048576,0,0,0 short=0,0,0,0 dropped=0,0,0,0
     latency   : target=0, window=0, percentile=100.00%, depth=64

Run status group 0 (all jobs):
   READ: bw=32.7MiB/s (34.2MB/s), 32.7MiB/s-32.7MiB/s (34.2MB/s-34.2MB/s), io=4096MiB (4295MB), run=125424-125424msec

Disk stats (read/write):
  sdb: ios=1048125/192, merge=0/57, ticks=7902684/3437, in_queue=6621492, util=99.68%

real	3m7.048s
user	0m3.815s
sys	0m15.399s
```
Could you please provide any other tests that can show the changes significance?

**Comment by lhotari** [comment]
@LeonidLapshin Thanks for the feedback.

> We have tested your changes with 'fio':

Just confirming, are you referring to changes in PR #1942?

**Comment by LeonidLapshin** [comment]
@lhotari yep, exactly.

**Comment by LeonidLapshin** [comment]
Hi, @lhotari !
As I previously mentioned, your changes looks good, but unfortunately we don't have any test results that prove efficiency of these fs/memory options. I'll close this issue for now but if you can provide any tests that can show fs/memory operations speed up, please open a discussion in corresponding category, and we will revisit them.
Thank you!

**Comment by maxim-lobanov** [comment]
https://github.com/actions/virtual-environments/pull/1942#issuecomment-776545498

**Comment by aagmv** [comment]
> we don't have any test results that prove efficiency of these fs/memory options.
> please open a discussion in corresponding category, and we will revisit them.

I have started a discussion in https://github.com/orgs/community/discussions/177899
