### ISSUE TITLE
Improve workflows for building and installing PHP extensions from source

### ISSUE THREAD

**Issue by shivammathur** [actions/virtual-environments#1944]
**Tool information**
- Tool name: `php-dev` and `php-pear`
- Tool license:
    - **php-dev:** [`The PHP License, version 3.01`](https://github.com/php/php-src/blob/master/LICENSE)
    - **php-pear:** [`2-Clause BSD License`](https://github.com/pear/pear-core/blob/master/LICENSE)
- Add or update? Add
- Desired version: `latest`
- Approximate size: around 500kb for `php-dev` for each PHP version and around 280kb for `php-pear`
- If this is an add request:
  - Brief description of tool: Both `php-dev` and `php-pear` contain scripts to build PHP extensions.
  - URL for tool's homepage:
    - **php-dev:** https://github.com/php/php-src/tree/master/scripts
    - **php-pear:** https://github.com/pear/pear-core
  - Provide a basic test case to validate the tool's functionality:
    - **php-dev:** `phpize --version` or `php-config --version`
    - **php-pear:** `pecl -V`

**Area for Triage**: PHP

**Question, Bug, or Feature?**: Feature

**Virtual environments affected**
- [X] Ubuntu 16.04
- [X] Ubuntu 18.04
- [X] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Can this tool be installed during the build?**
Yes,
```
apt-get install -y php$version-dev
apt-get install -y php-pear
```

**Tool installation time in runtime**: less than a minute

**Are you willing to submit a PR?** Yes

**Notes: **
- Currently `PHP 7.3` and `PHP 7.4` have `php-dev` installed, while lower PHP versions do not. It should be uniformly installed along with PHP versions.
Because of the current setup when `php-dev` is updated on `ppa:ondrej/php`. For PHP 7.2 and lower, installing `php-dev` takes 2 to 3 minutes long as all the PHP packages are updated along with it. Installing it on the runner for a minimal 2 to 3 mb space would save 2 to 3 minutes per workflow run for people building and installing PHP extensions from source.

- `php-pear` package adds `pecl` which is used to install php extensions from source.

**Comment by maxim-lobanov** [comment]
No objections for these changes. Thank you for submitting PR. We will review it soon
