### ISSUE TITLE
Add Microsoft.VisualStudio.Component.VC.Redist.MSM for Visual Studio 2019 in Windows Server 2019

### ISSUE THREAD

**Issue by allexzander** [actions/virtual-environments#195]
**Tool information**
- Tool name: Microsoft.VisualStudio.Component.VC.Redist.MSM
- Add
- Desired version: 
- Approximate size: 
- If this is an add request:
  - Brief description of tool: Visual Studio Enterprise 2019 individual component "Redist MSM"
  - URL for tool's homepage: https://docs.microsoft.com/en-us/visualstudio/install/workload-component-id-vs-build-tools?view=vs-2019

**Area for Triage**: C/C++
**Question, Bug, or Feature?**: Feature

**Virtual environments affected**
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [x] Windows Server 2019

**Can this tool be installed during the build?**
Currently, as a workaround, we install this component via the PowerShell, using the following command:
`Start-Process "C:\Program Files (x86)\Microsoft Visual Studio\Installer\vs_installer.exe" -ArgumentList 'modify --installPath "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise" --quiet --add Microsoft.VisualStudio.Component.VC.Redist.MSM' -Wait -PassThru`

It takes 10-15 minutes to install, that's why we would like to have it installed in advance to reduce the duration of every build.

**Are you willing to submit a PR?**
Kindly, add this component name `Microsoft.VisualStudio.Component.VC.Redist.MSM` into the VS 2019 installation script here https://github.com/actions/virtual-environments/blob/master/images/win/scripts/Installers/Windows2019/Install-VS2019.ps1 into `$WorkLoads` list. This should do it.

**Comment by alepauly** [comment]
@allexzander sorry for the delay in looking at this. Is it still an issue for you?

**Comment by allexzander** [comment]
> @allexzander sorry for the delay in looking at this. Is it still an issue for you?

Hi @alepauly,

We are using a workaround by manually installing this component during the build process. It would be nice to have it added by default into a virtual OS image, so we would save the time spent for the installation for every build.

**Comment by alepauly** [comment]
Hi @allexzander, we briefly looked into it and considering the size of the component and maintenance concerns, we won't be baking it into the image at this time.

**Comment by qminds** [comment]
@alepauly And how about now? In fact, the merge modules is a crucial component in many CI/CD builds where an MSI package depends on this type of VC runtime redistribution.

**Comment by slonopotamus** [comment]
https://github.com/actions/virtual-environments/blob/main/images/win/Windows2019-Readme.md claims that winndows-2019 image contains `Microsoft.VisualStudio.Component.VC.Redist.MSM` at least for the past two years.

Note that `Microsoft.VisualStudio.Component.VC.Redist.MSM` is missing from windows-2022 image, that is supposed to be fixed in https://github.com/actions/virtual-environments/issues/5143.
