### ISSUE TITLE
Unit test run failed caused by Chinese in assertion

### ISSUE THREAD

**Issue by BrightRan** [actions/virtual-environments#1952]
Associated GitHub Community topic: https://github.community/t/unit-test-run-failed-caused-by-chinese-in-assertion/140474

The customer has a .NET Core project. The unit test of this project run failed, because of the assertion includes Chinese (**`zh_CN`**).
The project can work well on his personal computer.

I forked the customer's project and test on my side.
I tried to change the system locale to **`zh_CN`** like as below (reference to #762):
```yaml
    - name: Test
      run: |
        sudo apt-get update && sudo apt-get install tzdata locales -y && sudo locale-gen zh_CN.UTF-8
        sudo localectl set-locale LANG="zh_CN.UTF-8"
        export LANG="zh_CN.UTF-8"
        sudo update-locale

        dotnet test Sophon.Toolkit.sln --no-restore --verbosity normal
```
But it did not work, the unit test still run failed (see [this run](https://github.com/ForksForTest/Sophon.Toolkit/actions/runs/341211315/workflow)).

**Comment by al-cheb** [comment]
Resolved: https://github.community/t/unit-test-run-failed-caused-by-chinese-in-assertion/140474/5?u=al-cheb
