### ISSUE TITLE
Unnoticed virtual environment change causes software failure

### ISSUE THREAD

**Issue by cxn-mkalinovits** [actions/virtual-environments#1982]
**Description**  
My team faced the second time that the actual virtual environment under our builds changed silently and uncontrollable (latest ubuntu-16.04 20201012.1 => ubuntu-16.04 20201026.1).
This slight change causes some unexpected behaviour in compiled Java code. (Resolution order of dependencies changed.)

**Area for Triage**:  
Containers

**Question, Bug, or Feature?**:  
Question, Bug

**Virtual environments affected**  
- [x] Ubuntu 16.04
- [x] Ubuntu 18.04

**Expected behavior**  
My built artifact shoud change only if code changed. (Unseen/uncontrolled build environment changes should not affect it.)

**Actual behavior**  
Operating system patch update caused change in artifact (JAR) that caused runtime malfunction.
Changing Virtual Environment to 18.04 solved the issue. (But previously we faced the exact same behaviour with previous 18.04 version. Solution was changing to 16.04.)

**Repro steps**  
Cannot do that. Sorry.

**Comment by maxim-lobanov** [comment]
@cxn-mkalinovits , could you please provide more context about what exactly was broken and why your build was affected.
We update images on weekly basis and usually install latest versions for all software.
Recently we had the following updates
- Ubuntu 16: 20201012.1 -> 20201015.1: https://github.com/actions/virtual-environments/pull/1838/files
- Ubuntu 16: 20201015.1 -> 20201026.1: https://github.com/actions/virtual-environments/pull/1899/files
- Ubuntu 18: 20201012.1 -> 20201015.1: https://github.com/actions/virtual-environments/pull/1834/files
- Ubuntu 18: 20201015.1 -> 20201026.1: https://github.com/actions/virtual-environments/pull/1900/files

You can track every change on images via these PRs. Usually, PRs are created right after deployment started and merged after deployment is finished.

**Comment by cxn-mkalinovits** [comment]
It is a bit hard to provide clear description of the caused issue as it happened in a moderately complex system. However...

Context:
We develop a spring-boot based application.
We use a library that handles custom authentication for our platform ([spring-boot-synergy-starter](https://github.com/ChemAxon/spring-boot-synergy-starter)).
Artifacts built with ubuntu-16.04 20201012.1 work perfectly.
Artifacts built with ubuntu-16.04 20201026.1 loose custom authentication, but not other features that are provided by the library.
Artifacts built with ubuntu-18.04 20201026.1 work perfectly.

After debugging we found that the JAR archives are behaving differently. It seems that dependency load order changed somehow.

**Comment by maxim-lobanov** [comment]
Sorry, we don't have much experience with Java building and JAR archives.
Is it possible to provide minimal repro steps for this issue? It could be help to confirm that issue is not related to your changes and could help us to debug it.
Did you find any suspicious changes in image diff (links that I sent above)? They reflect all changes that are done between images

**Comment by cxn-mkalinovits** [comment]
Hi Maxim,

Unfortunately I'm not an expert on OS related debugging.
Plus nothing suspicious.

However I'm going to try creating a minimal example for you.

*Mark Kalinovits*
*Developer*
*ChemAxon *
Building Hx, GraphiSoft Park
Záhony utca 7., Budapest, 1031 Hungary
Tel: +361 4532658
Fax: +361 4532659
http://www.chemaxon.com
mkalinovits@chemaxon.com

**Comment by maxim-lobanov** [comment]
I am closing this issue since we can't do further investigation without repro-steps and we didn't hear any other reports about this issue.
All software updates can be tracked via pull-requests as I mentioned above.

Thank you.
