### ISSUE TITLE
UsePythonVersion task is broken on 20201102.0 Windows images

### ISSUE THREAD

**Issue by QuLogic** [actions/virtual-environments#1986]
**Description**  
With the Windows image update 20201102.0, the paths are all messed up and the `UsePythonVersion` task no longer appears to work. The linked build below shows 3 jobs on windows, two of which use 20201021.0, while the third uses 20201102.0. Only the latter failed because `python` is found in the msys2 path instead of the tools path.

All followup pipelines in the project are now failing in all 3 Windows builds now that the new image is available on all agents.

**Area for Triage**:  Python

**Question, Bug, or Feature?**:  Bug

**Virtual environments affected**  
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11.0
- [x] Windows Server 2016 R2
- [x] Windows Server 2019

**Expected behavior**  
`python` is run from the correct path, and is able to install things.

**Actual behavior**  
`python` is run from the msys2 path (`C:/msys64/mingw64/bin/python.exe`) instead of the Python hosted cache. Since the former does not include `pip`, it cannot install any packages.

**Repro steps**  
https://dev.azure.com/matplotlib/matplotlib/_build/results?buildId=15461&view=logs&j=84c7942d-5208-5fb3-5dc8-74e831a0653c&t=f17d63b8-dacd-45cf-a243-18325584e9bc

1. Add UsePythonVersion task in pipeline.
2. Run `python -m pip install ...` in `bash`

**Comment by maxim-lobanov** [comment]
@QuLogic , thank you for your report. We have found an issue with image and are working to rollback it.
As a workaround, you can switch to Windows19 image or use `python3` binary in scripts

**Comment by maxim-lobanov** [comment]
cc: @al-cheb to notify when rollback is finished

**Comment by al-cheb** [comment]
Hello, @QuLogic 
Windows Server 2016&2019 pools have been rollbacked to the previous version.
