### ISSUE TITLE
Update/Add phive

### ISSUE THREAD

**Issue by mpdude** [actions/virtual-environments#199]
**Tool information**
- Tool name: phive
- Add or update? Add
- Desired version: latest (?)
- Approximate size: 159kB
- If this is an add request:
  - Brief description of tool: Dependency manager for PHP .phar archives
  - URL for tool's homepage: https://phar.io/

**Area for Triage**: PHP

**Question, Bug, or Feature?**: Feature

**Virtual environments affected**
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019
All that provide PHP (all?)

**Can this tool be installed during the build?**
Yes, see instructions on the tools website. Takes about 30-45s, mostly because PGP keyservers (for integrity checks) seem to be slow

**Are you willing to submit a PR?**
Sure. Documentation is where?

**Comment by alepauly** [comment]
@mpdude - considering the added effort to maintain, at this time I don't think we can preinstall this in the image. Thanks for the suggestion.

**Comment by mpdude** [comment]
Thank your for the consideration.
