### ISSUE TITLE
Add MongoDB Community Edition

### ISSUE THREAD

**Issue by Ignigena** [actions/virtual-environments#20]
**Tool information**
- Tool name: mongo and mongod
- Add or update? Add
- Desired version: 3.x, 4.x
- Approximate size: 250-300MB
- If this is an add request:
  - Brief description of tool: NoSQL database server and CLI tool
  - URL for tool's homepage: https://github.com/mongodb/mongo

**Virtual environments affected**
- [x] macOS 10.14
- [x] Ubuntu 16.04 LTS
- [x] Ubuntu 18.04 LTS
- [x] Windows Server 2016 R2
- [x] Windows Server 2019

**Can this tool be installed during the build?**

**Are you willing to submit a PR?**

**Comment by maxim-lobanov** [comment]
Tool can be installed in runtime using the following script
```
# Ubuntu
sudo apt install -y mongodb
# macOS
brew tap mongodb/brew
brew install mongodb-community
# Windows
choco install mongodb
```
Installation takes about 1 minute.

**Comment by dsame** [comment]
PR https://github.com/actions/virtual-environments/pull/591

**Comment by dsame** [comment]
Ubuntu PR https://github.com/actions/virtual-environments/pull/591

**Comment by dsame** [comment]
The changes are merged and will be in the production  on the next deploy
