### ISSUE TITLE
Add Unreal Engine

### ISSUE THREAD

**Issue by Ludea** [actions/virtual-environments#2003]
**Tool information**
- Tool name: Unreal Engine
- Tool license: https://www.unrealengine.com/en-US/eula/publishing
- Add or update? add
- Desired version: 4.25
- Approximate size: 30Gb
- If this is an add request:
  - Brief description of tool: The Unreal Engine is a game engine developed by Epic Games
  - URL for tool's homepage: https://www.unrealengine.com/en-US/
  - Provide a basic test case to validate the tool's functionality: 

**Area for Triage**:
.NET Framework C/C++

**Question, Bug, or Feature?**:
Feature

**Virtual environments affected**
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [x ] Ubuntu 20.04
- [ ] macOS 10.15
- [x ] macOS 11.0
- [ ] Windows Server 2016 R2
- [x ] Windows Server 2019

**Can this tool be installed during the build?**
Yes, if you pull source and build it from GH

**Tool installation time in runtime**
depend a lot of host

**Are you willing to submit a PR?**
Why not

**Comment by maxim-lobanov** [comment]
Hello @Ludea , thank you for your proposal.

Unfortunately, we won't be able to add Unity to Hosted images:
1) Disk space concern. For now, we don't have 30 GB of free space on images and I don't think that we will be able to afford it in future.
2) License issue. Unreal Engine is distributed by EULA license. As I remember, we can't install software with EULA license to our images (it is the reason why we don't have Docker on macOS images, for example).

I suggest to consider using of [self-hosted agents](https://docs.github.com/en/free-pro-team@latest/actions/hosting-your-own-runners/about-self-hosted-runners) for this goal.
