### ISSUE TITLE
[Question] windows-2019 memory ram

### ISSUE THREAD

**Issue by eddynaka** [actions/virtual-environments#2004]
Hi,

I'm using azure devops pipeline with windows-2019 vmimage and I would like to know how much memory RAM does the VM have.

I have one task that i can set some limitations to memory RAM. Right now, I fixed to 4GB, butt it is taking too much time.

Thank you.

**Comment by maxim-lobanov** [comment]
Hello!
You can find specification of Hosted runners in GItHub Actions documentation: https://docs.github.com/en/free-pro-team@latest/actions/reference/specifications-for-github-hosted-runners#supported-runners-and-hardware-resources
A bit more information where agents are hosted in https://docs.github.com/en/free-pro-team@latest/actions/reference/specifications-for-github-hosted-runners#cloud-hosts-for-github-hosted-runners

**Comment by eddynaka** [comment]
oohhh. thank you!

didn't see that!
