### ISSUE TITLE
Add php 7.4

### ISSUE THREAD

**Issue by Geolim4** [actions/virtual-environments#201]
**Tool information**
- Tool name: php 7.4
- Add or update? Add
- Desired version: 7.4
- Approximate size: 
- If this is an add request:
  - Brief description of tool: Latest stable version of php
  - URL for tool's homepage: https://www.php.net/manual/fr/migration74.php

**Area for Triage**: PHP

**Question, Bug, or Feature?**: Feature

**Virtual environments affected**
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [x] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Can this tool be installed during the build?**
Not sure tho

**Are you willing to submit a PR?**
I'm not yet knowing the actions well enough, maybe later :)

**Comment by Lctrs** [comment]
FYI, [the PR](https://github.com/actions/virtual-environments/pull/121) for this has been merged few days ago. It should land in the first week of january.

**Comment by Geolim4** [comment]
This issue is now resolved as I tested & validated new 7.4 containers, thanks you ❤️

**Comment by zoispag** [comment]
@Geolim4 you did? How? I don't see the php 7.4 binary available yet on ubuntu-latest

**Comment by Lctrs** [comment]
@zoispag Probably by using its own docker images or using https://github.com/shivammathur/setup-php.

**Comment by zoispag** [comment]
@Lctrs that's what I thought. Thanks
