### ISSUE TITLE
Software OpenGL renderer on macOS 10.15 virtual environment

### ISSUE THREAD

**Issue by balsamiqPaolo** [actions/virtual-environments#2014]
**Description**  
When launching UI tests on Xcode 12 + macOS 10.15 virtual environment I get many of these console logs:
> Core Image is now using the software OpenGL renderer. This will be slow.

Many tests fail because of a timeout.

My current CI configuration runs on macstadium and has not this kind of problem.
Is this a bug of my script? Is there anything I can do to fix this?

**Area for Triage**:  
Apple, Containers

**Question, Bug, or Feature?**:  
Question, Bug

**Virtual environments affected**  
- [X] macOS 10.15

**Expected behavior**  
An HW accelerated renderer would be ideal to run UI tests.

**Actual behavior**  
I get warnings of a "software OpenGL renderer" being used and many UI tests time out.

**Repro steps**  
Launch some non trivial UI tests that drive a desktop application.
You will get a warning:

> Core Image is now using the software OpenGL renderer. This will be slow.

some test may timeout

**Comment by Darleev** [comment]
Hello,
Thank you for the issue reported.

Could you please provide more details about the configuration of your macOS machine on macstadium? What UI tests are you using?
We are looking forward to your reply.

**Comment by balsamiqPaolo** [comment]
Thanks for your prompt reply.

The specs reported are:
Mac mini (Late 2012)
2.6 GHz Quad-Core Intel Core i7
Memory 16GB
Intel HD Graphics 4000
VRAM (Dynamic, Max):	1536 MB
Metal: Supported, feature set macOS GPUFamily1 v4

Among other unit tests, I run a set of UI tests that startup my application, interact with simple dialogs, check for some label  strings and shut down the application. They wait for the app and document to load and for menus/dialogs to appear.

**Comment by Darleev** [comment]
Hello @balsamiqPaolo,
We have very similar things in [another issue](https://github.com/actions/virtual-environments/issues/1779) related to GPU passthrough.
I was trying to find a way how to avoid the issue, but it seems the best way is to use mac-stadium Mac machines.

**Comment by balsamiqPaolo** [comment]
Thanks for your help @Darleev 
Before giving up I'll try to see if I can tweak timeouts to make tests run with sw renderer.
And maybe try to use our mac-stadium machine as a self-hosted runner...
👍
