### ISSUE TITLE
Update/Add pypy 3.7

### ISSUE THREAD

**Issue by mattip** [actions/virtual-environments#2017]
**Tool information**
- Tool name: pypy
- Tool license: 
- Add or update? update
- Desired version: add pypy 3.7 (for python version 3.7), pypy3.6 is already provided
- Approximate size: 
- If this is an add request:
  - Brief description of tool: 
  - URL for tool's homepage: 
  - Provide a basic test case to validate the tool's functionality: 

**Area for Triage**:

**Question, Bug, or Feature?**:

**Virtual environments affected**
- [ ] Ubuntu 16.04
- [x] Ubuntu 18.04
- [x] Ubuntu 20.04
- [x] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Can this tool be installed during the build?**

**Tool installation time in runtime**

**Are you willing to submit a PR?**
yes. I looked around but could not find where to add pypy3.7 to the already existing pypy3.6

**Comment by maxim-lobanov** [comment]
@mattip , This issue should be addressed in [actions/setup-python](https://github.com/actions/setup-python) repo.
For now, `actions/setup-python` doesn't support separation `3.6` vs `3.7` so even if we add PyPy 3.7 to images, you won't be able to use it (more precisely, all customers will be switched automatically on 3.7 and will lose ability to use 3.6)
As I can see, there is the same issue in `actions/setup-python`: https://github.com/actions/setup-python/issues/136 so I will close this as duplicate. Not much we can do from image side until actions/setup-python is updated.
