### ISSUE TITLE
Install supported Az Module for Azure Stack

### ISSUE THREAD

**Issue by rakku-ms** [actions/virtual-environments#2030]
The current ubuntu-latest image doesn't have Azure Stack supported Az Module installed.
https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu1804-README.md#az-module

Azure Stack supports '2.0.2-preview' version of the module. This version is needed in the image to run Github actions against Azure Stack. Can you please make the same part of the ubuntu-latest image?
https://docs.microsoft.com/en-us/azure-stack/operator/powershell-install-az-module?view=azs-2005#4-connected-install-with-internet-connectivity

**Comment by rakku-ms** [comment]
@bganapa, @sarathys, @garvitarai FYI

**Comment by bganapa** [comment]
Modules needed for AzureStack Az - 0.10.0-preview - https://www.powershellgallery.com/packages/Az/0.10.0-preview

**Comment by maxim-lobanov** [comment]
Hello @rakku-ms , @bganapa , we don't bake preview versions of Az module into the image.
Also version 0.10.0-preview looks pretty old. Currently, 5.x is actual version.
Please consider installation of this module in runtime.
Module can be installed using the following command (installation takes about 20 seconds):
```pwsh
Install-Module -Name Az -RequiredVersion 0.10.0-preview -AllowPrerelease -Force
```

**Comment by maxim-lobanov** [comment]
I am closing the issue for now but please let me know if you have any concerns / objections
