### ISSUE TITLE
latest windows2019.json creates invalid image, potentially failed generalization?

### ISSUE THREAD

**Issue by mihsoft** [actions/virtual-environments#2037]
**Description**  
Using the latest from the main branch as of 19:32pm last night the packer file ran to completion however it broke our Virtual Machine Scale Set with an invalid image. Attempting to create a VM from the image results in the same failure.

`OS Provisioning for VM 'win2019_622' did not finish in the allotted time. This error occurred too many times consecutively from image 'windows2019-v74'. Make sure the image has been properly prepared`

**Area for Triage**:  

**Question, Bug, or Feature?**:  

**Virtual environments affected**  
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [x] Windows Server 2019

**Expected behavior**  
It should not be possible to produce an invalid image without the packer file failing

**Actual behavior**  
`OS Provisioning for VM 'win2019_622' did not finish in the allotted time. This error occurred too many times consecutively from image 'windows2019-v74'. Make sure the image has been properly prepared`

**Repro steps**  
Run the packer file for windows2019.json

**Comment by maxim-lobanov** [comment]
Hello @mihsoft ,
We generate images on daily basic based on main branch and deploy it to test environment. Current main branch looks healthy for us and image passed all validation checks.
Could you please review logs of image generation process to make sure that you didn't have silent issues during it.
As for the deployment to ScaleSet, unfortunately we don't use Scale Set for image deployments and don't have much experience with it to help debug it.

**Comment by mihsoft** [comment]
Hi @maxim-lobanov, in this case the image that was produced failed when using a regular Virtual Machine. I've got another build from the main branch running now, hopefully it'll work as expected

**Comment by Darleev** [comment]
Hello @mihsoft,
Could you please provide us details about latest build from the main branch? Is the issue still actual?
We are looking forward to your reply.

**Comment by Darleev** [comment]
Hello @mihsoft,
I'm going to close the issue until further clarifications from your side.
If additional information or assistance is required, do not hesitate to contact us
