### ISSUE TITLE
latest ubuntu1804.json from main sporadically fails installing dotnet-sdk

### ISSUE THREAD

**Issue by mihsoft** [actions/virtual-environments#2038]
**Description**  
At around 30 minutes or so in to the packer build we get this error (repeated dozens of times):

```
    azure-arm: Configuring...

    azure-arm: --------------

    azure-arm: A command is running to populate your local package cache to improve restore speed and enable offline access. This command takes up to one minute to complete and only runs once.

```
```
    azure-arm: Adding https://dotnetcli.blob.core.windows.net/dotnet/Sdk/2.1.505/dotnet-sdk-2.1.505-linux-x64.tar.gz to list to download later

    azure-arm: Adding https://dotnetcli.blob.core.windows.net/dotnet/Sdk/2.1.504/dotnet-sdk-2.1.504-linux-x64.tar.gz to list to download later
    azure-arm: Adding https://dotnetcli.blob.core.windows.net/dotnet/Sdk/2.1.503/dotnet-sdk-2.1.503-linux-x64.tar.gz to list to download later
    azure-arm: Adding https://dotnetcli.blob.core.windows.net/dotnet/Sdk/2.1.502/dotnet-sdk-2.1.502-linux-x64.tar.gz to list to download later
    azure-arm: Adding https://dotnetcli.blob.core.windows.net/dotnet/Sdk/2.1.500/dotnet-sdk-2.1.500-linux-x64.tar.gz to list to download later
    azure-arm: Adding https://dotnetcli.blob.core.windows.net/dotnet/Sdk/2.1.403/dotnet-sdk-2.1.403-linux-x64.tar.gz to list to download later
    azure-arm: Adding https://dotnetcli.blob.core.windows.net/dotnet/Sdk/2.1.402/dotnet-sdk-2.1.402-linux-x64.tar.gz to list to download later
    azure-arm: Adding https://dotnetcli.blob.core.windows.net/dotnet/Sdk/2.1.401/dotnet-sdk-2.1.401-linux-x64.tar.gz to list to download later
    azure-arm: Adding https://dotnetcli.blob.core.windows.net/dotnet/Sdk/2.1.302/dotnet-sdk-2.1.302-linux-x64.tar.gz to list to download later
    azure-arm: Adding https://dotnetcli.blob.core.windows.net/dotnet/Sdk/2.1.301/dotnet-sdk-2.1.301-linux-x64.tar.gz to list to download later

    azure-arm: Adding https://dotnetcli.blob.core.windows.net/dotnet/Sdk/2.1.300/dotnet-sdk-2.1.300-linux-x64.tar.gz to list to download later
```
**Area for Triage**:  

**Question, Bug, or Feature?**:  

**Virtual environments affected**  
- [ ] Ubuntu 16.04
- [x] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Expected behavior**  
Image should be processed successfully

**Actual behavior**  
    azure-arm: Adding https://dotnetcli.blob.core.windows.net/dotnet/Sdk/2.1.505/dotnet-sdk-2.1.505-linux-x64.tar.gz to list to download later

**Repro steps**  
Run the ubuntu1804.json file

**Comment by LeonidLapshin** [comment]
Hey, @mihsoft !
`azure-arm: Adding https://dotnetcli.blob.core.windows.net/dotnet/Sdk/*/dotnet-sdk-*-linux-x64.tar.gz to list to download later` is expected behavior of the packer build process, this stage is described here https://github.com/actions/virtual-environments/blob/7f0fed72d74083eabd07ef4454caeca05f9bfcfd/images/linux/scripts/installers/dotnetcore-sdk.sh#L57-L61
If the process ends unexpectedly on/after this stage it probably happens because of network download errors. 
Could you please share the full installation process log?
In the meantime, we are going to add more debug messages and implement download retries to this script

**Comment by LeonidLapshin** [comment]
Hi, @mihsoft !
We have done some dotnet-sdk installation improvements so this stage should not fail.
Thank you!
