### ISSUE TITLE
win19/20201021.0 release has invalid link to SQLSysClrTypes.msi

### ISSUE THREAD

**Issue by mihsoft** [actions/virtual-environments#2044]
**Description**  
```
    vhd: Downloading package from: https://download.microsoft.com/download/8/7/2/872BCECA-C849-4B40-8EBE-21D48CDF1456/ENU/x64/SQLSysClrTypes.msi to path C:\Users\packer\AppData\Local\Temp\SQLSysClrTypes.msi .

    vhd: There is an error during package downloading:

    vhd:  Exception calling "DownloadFile" with "2" argument(s): "The remote server returned an error: (404) Not Found."
```

Obviously the path has changed slightly which was fixed in:
https://github.com/actions/virtual-environments/commit/303f963f21b297f9fe8f0d07f0ceca7adf1cad55

**Area for Triage**:  

**Question, Bug, or Feature?**:  
Bug

**Virtual environments affected**  
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [x] Windows Server 2019

**Expected behavior**  
Valid download link

**Actual behavior**  
404 on download

**Repro steps**  
Pull the repo at tag win19/20201021.0
Run the Windows 2019.json

Observe error after 3 hours and 30 minutes or so

**Comment by mihsoft** [comment]
Closing as this issue was fixed 15 days ago but means the previous release is broken.

**Comment by mihsoft** [comment]
Actually thinking about it, can this be backported to win19/20201021.0 or a new release created?

**Comment by maxim-lobanov** [comment]
@mihsoft , usually we don't backport changes to previous tags and fix all issues only in main branch.
https://github.com/actions/virtual-environments/tree/win19/20201108.1 will become "release" tomorrow.
