### ISSUE TITLE
MS SQL Server Client Tools is in the MySQL section

### ISSUE THREAD

**Issue by shogo82148** [actions/virtual-environments#2045]
**Description**  

In Ubuntu documents, MS SQL Server Client Tools is in the MySQL section.

But, in my understanding, MS SQL Server means Microsoft SQL Server.
It is an SQL server, but not the MySQL server.

**Area for Triage**:  

**Question, Bug, or Feature?**:  
Documentation Bug

**Virtual environments affected**  
- [x] Ubuntu 16.04
- [x] Ubuntu 18.04
- [x] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Expected behavior**  
MS SQL Server Client Tools should be in the Database tools section.

**Actual behavior**  
MS SQL Server Client Tools is in the MySQL section.

**Repro steps**  

- [Ubuntu 20.04#mysql](https://github.com/actions/virtual-environments/blob/5adf802f77253689b3030f7a12f06137c487c24d/images/linux/Ubuntu2004-README.md#mysql)
- [Ubuntu 18.04#mysql](https://github.com/actions/virtual-environments/blob/7f0fed72d74083eabd07ef4454caeca05f9bfcfd/images/linux/Ubuntu1804-README.md#mysql)
- [Ubuntu 16.04#mysql](https://github.com/actions/virtual-environments/blob/7f0fed72d74083eabd07ef4454caeca05f9bfcfd/images/linux/Ubuntu1604-README.md#mysql)

**Comment by vsafonkin** [comment]
Hi @shogo82148 , thank you for your report! Please, see PR with fix above.

**Comment by shogo82148** [comment]
Thank you for your quick fix. LGTM!

**Comment by vsafonkin** [comment]
PR with fix was merged, document files will be updated after next Ubuntu release.
