### ISSUE TITLE
MacOS 10.15 20201107.1 breaks build that works in 20201003.1

### ISSUE THREAD

**Issue by JGuille** [actions/virtual-environments#2052]
**Description**
I have a React Native application. Release 20201107.1 was rolled out and now one of my archives is failing. There are errors exporting the archive. I'm not sure what exactly changed between 20201107.1 and the last working version 20201003.1.

**Area for Triage:**
Apple

**Question, Bug, or Feature?:**
Bug

**Virtual environments affected**
-  [ ]  Ubuntu 16.04 LTS
-  [ ]  Ubuntu 18.04 LTS
-  [ ]  Ubuntu 20.04 LTS
-  [x] macOS 10.15
-  [ ]  Windows Server 2016 R2
-  [ ]  Windows Server 2019

**Expected behavior**
Xcode (5.175.1)
In 20201003.1, the build log shows the following output for exporting the archive:
>```
>/usr/bin/security cms -D -i /Users/runner/work/1/s/AppName.xcarchive/Products/Applications/AppName.app/embedded.mobileprovision
>/usr/libexec/PlistBuddy -c Print ProvisionsAllDevices _xcodetasktmp.plist
>Entry, "ProvisionsAllDevices", Does Not Exist
>/usr/libexec/PlistBuddy -c Print Entitlements:get-task-allow _xcodetasktmp.plist
>false
>/usr/libexec/PlistBuddy -c Print ProvisionedDevices _xcodetasktmp.plist
>Entry, "ProvisionedDevices", Does Not Exist
>/bin/rm -f _xcodetasktmp.plist
>/usr/libexec/PlistBuddy -c Clear _XcodeTaskExportOptions.plist
>Unrecognized Type: 
>File Doesn't Exist, Will Create: _XcodeTaskExportOptions.plist
>Initializing Plist...
>/usr/libexec/PlistBuddy -c Add method string app-store _XcodeTaskExportOptions.plist
>/usr/bin/security cms -D -i >/Users/runner/work/1/s/AppName.xcarchive/Products/Applications/AppName.app/embedded.mobileprovision
>/usr/libexec/PlistBuddy -c Print Entitlements:com.apple.developer.icloud-container-environment _xcodetasktmp.plist
>Entry, "Entitlements:com.apple.developer.icloud-container-environment", Does Not Exist
>/bin/rm -f _xcodetasktmp.plist
>/usr/libexec/PlistBuddy -c Add signingStyle string manual _XcodeTaskExportOptions.plist
>/usr/libexec/PlistBuddy -c Add provisioningProfiles dict _XcodeTaskExportOptions.plist
>/usr/bin/security cms -D -i >/Users/runner/work/1/s/Flowyformmobile.xcarchive/Products/Applications/Flowy.app/embedded.mobileprovision
>/usr/libexec/PlistBuddy -c Print Name _xcodetasktmp.plist
>appcertificate
>/bin/rm -f _xcodetasktmp.plist
>/usr/libexec/PlistBuddy -c Print CFBundleIdentifier >/Users/runner/work/1/s/AppName.xcarchive/Products/Applications/AppName.app/Info.plist
>com.app.identifier
>/usr/libexec/PlistBuddy -c Add provisioningProfiles:com.app.identifier string appcertificate _XcodeTaskExportOptions.plist
>/usr/bin/xcodebuild -exportArchive -archivePath /Users/runner/work/1/s/AppName.xcarchive -exportPath >/Users/runner/work/1/s/output/$(SDK)/$(Configuration) -exportOptionsPlist _XcodeTaskExportOptions.plist | >/usr/local/lib/ruby/gems/2.6.0/bin/xcpretty --no-color
>xcodebuild[18939:45917] [MT] IDEDistribution: -[IDEDistributionLogging _createLoggingBundleAtPath:]: Created bundle at path '/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/AppName_2020-10-19_23-38-01.208.xcdistributionlogs'.
>Export Succeeded
>Finishing: Xcode
>```

**Actual Behavior**
Xcode (5.177.0)
In 20201107.1, the build logs shows the following output instead:
>```
>/usr/bin/security cms -D -i /Users/runner/work/1/s/AppName.xcarchive/Products/Applications/AppName.app/embedded.mobileprovision
>usr/libexec/PlistBuddy -c Print ProvisionsAllDevices _xcodetasktmp.plist
>Entry, "ProvisionsAllDevices", Does Not Exist
>/usr/libexec/PlistBuddy -c Print Entitlements:get-task-allow _xcodetasktmp.plist
>false
>/usr/libexec/PlistBuddy -c Print ProvisionedDevices _xcodetasktmp.plist
> Entry, "ProvisionedDevices", Does Not Exist
>/bin/rm -f _xcodetasktmp.plist
>/usr/libexec/PlistBuddy -c Clear _XcodeTaskExportOptions.plist
>Unrecognized Type: 
>File Doesn't Exist, Will Create: _XcodeTaskExportOptions.plist
>Initializing Plist...
>/usr/libexec/PlistBuddy -c Add method string app-store _XcodeTaskExportOptions.plist
>/usr/bin/security cms -D -i >/Users/runner/work/1/s/AppName.xcarchive/Products/Applications/Flowy.app/embedded.mobileprovision
>/usr/libexec/PlistBuddy -c Print Entitlements:com.apple.developer.icloud-container-environment _xcodetasktmp.plist
> Entry, "Entitlements:com.apple.developer.icloud-container-environment", Does Not Exist
>/bin/rm -f _xcodetasktmp.plist
>/usr/libexec/PlistBuddy -c Add signingStyle string manual _XcodeTaskExportOptions.plist
>/usr/libexec/PlistBuddy -c Add provisioningProfiles dict _XcodeTaskExportOptions.plist
>/usr/bin/security cms -D -i /Users/runner/work/1/s/AppName.xcarchive/Products/Applications/AppName.app/embedded.mobileprovision
>usr/libexec/PlistBuddy -c Print Name _xcodetasktmp.plist
>flowycertificate
>/bin/rm -f _xcodetasktmp.plist
>/usr/libexec/PlistBuddy -c Print CFBundleIdentifier /Users/runner/work/1/s/AppName.xcarchive/Products/Applications/Flowy.app/Info.plist
>com.app.identifier
>/usr/libexec/PlistBuddy -c Add provisioningProfiles:com.app.identifier string appcertificate _XcodeTaskExportOptions.plist
>/usr/bin/xcodebuild -exportArchive -archivePath /Users/runner/work/1/s/AppNAme.xcarchive -exportPath /Users/runner/work/1/s/output/$(SDK)/$(Configuration) -exportOptionsPlist _XcodeTaskExportOptions.plist | /usr/local/lib/ruby/gems/2.7.0/bin/xcpretty --no-color
>error: archive at path '/Users/runner/work/1/s/AppName.xcarchive' is malformed
>Error: /usr/bin/xcodebuild failed with return code: 65
>Finishing: Xcode
>```

**Xcode Task**

>```
>  - task: Xcode@5
>    inputs:
>      actions: "clean archive"
>      scheme: "scheme"
>      sdk: "iphoneos"
>      configuration: 'Release'
>      xcWorkspacePath: "**/AppName.xcworkspace"
>      xcodeVersion: '11'
>      packageApp: true
>      signingOption: 'manual'
>      signingIdentity: '$(APPLE_CERTIFICATE_SIGNING_IDENTITY)'
>      provisioningProfileUuid: '$(APPLE_PROV_PROFILE_UUID)'
>```

**Comment by Darleev** [comment]
Hello @JGuille,
I found [the following topic](https://developercommunity.visualstudio.com/content/problem/1241119/xcode-archive-export-randomly-fails-react-native.html) where a very similar issue was reported. Could you please check and try the workaround provided?
We are looking forward to your reply.

**Comment by Darleev** [comment]
Hello @JGuille,
I'm going to close the issue.
Please let us know if additional assistance is required.
