### ISSUE TITLE
[macOS] Default Xcode will be set to Xcode 12.2 on November, 30.

### ISSUE THREAD

**Issue by AlenaSviridenko** [actions/virtual-environments#2056]
**Breaking changes**
Default Xcode will be changed to 12.2, and default Xamarin bundle will be changed to 6_12_3 which includes Xamarin.iOS 14.4, Xamarin.Android 11.1, Xamarin.Mac 6.22, Mono 6.12

**Target date**
Update propagation will start on November, 30 and will take 2-3 days.

**The motivation for the changes**
We would like to provide images with the latest stable updates as a default ones.

**Possible impact**
If you use default Xcode version and your project is not compatible with Xcode 12.2 your build can be broken.

**Virtual environments affected**
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.13
- [ ] macOS 10.14
- [x] macOS 10.15
- [x] macOS 11.0
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Mitigation ways**
Please consider switching Xcode in runtime to version that you need to build app.
The following snippet can be used to switch Xcode:

`sudo xcode-select -s "/Applications/Xcode_12.0.app"`

The list of all available Xcode versions can be found in [image documentation](https://github.com/actions/virtual-environments/blob/main/images/macos/macos-10.15-Readme.md#xcode)

**Comment by maxim-lobanov** [comment]
New images with Xcode 12.2 as default were deployed everywhere. Closing the issue
