### ISSUE TITLE
Windows cant find boost or find it then build fail.

### ISSUE THREAD

**Issue by Toni-d-e-v** [actions/virtual-environments#2059]
**Description**  
Everything was working fine with my workflow for my project but then all broke.
Windwos cant find boost!!!!!!!!
**Area for Triage**:  
https://github.com/RedStoneCoin/redstone/blob/development/.github/workflows/build.yml
https://github.com/RedStoneCoin/redstone/blob/development/CMakeLists.txt

**Question, Bug, or Feature?**:  
Eveything was fine but it broke. Cant find boost I tried everything! everything!!!

**Virtual environments affected**  
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [✅] Windows Server 2019

**Expected behavior**  
To find boost and build for windwos.

**Actual behavior**  
Not finding boost or finding it and failing. For ubutnu works fine so code is okay.
**Repro steps**  
I don't know how to fix it  :(

**Comment by maxim-lobanov** [comment]
I guess it could be related to https://github.com/actions/virtual-environments/issues/1847

**Comment by Toni-d-e-v** [comment]
@maxim-lobanov  https://github.com/RedStoneCoin/redstone/commit/159a2400413f8f60d6996241f83ed637fbb527ae 
Is this how i set it up sorry for distruping.

**Comment by maxim-lobanov** [comment]
Could you please add one more line to installation step?
```pwsh
"BOOST_ROOT_1_69_0=C:\hostedtoolcache\windows\Boost\1.69.0\x86_64" | Out-File -FilePath $env: GITHUB_ENV -Encoding utf8 -Append
```
So the final snippet should be
```pwsh
$url = "https://github.com/actions/boost-versions/releases/download/1.69.0-20200608.1/boost-1.69.0-win32-msvc14.1-x86_64.tar.gz"
(New-Object System.Net.WebClient).DownloadFile($url, "$($env:TEMP)\boost.tar.gz")
7z.exe x "$($env:TEMP)\boost.tar.gz" -o"$($env:TEMP)" -y | Out-Null
$tarPath = Get-ChildItem -Path "$($env:TEMP)" -Filter "boost-*.tar" | Select-Object -First 1
7z.exe x $tarPath -o"$($env:TEMP)/boost" -y | Out-Null
Push-Location -Path "$($env:TEMP)\boost"
Invoke-Expression .\setup.ps1
"BOOST_ROOT_1_69_0=C:\hostedtoolcache\windows\Boost\1.69.0\x86_64" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
```

**Comment by Toni-d-e-v** [comment]
@maxim-lobanov  Okay i will try thanks!

**Comment by maxim-lobanov** [comment]
@Toni-d-e-v , any updates? Did fix above help to resolve your issue?

**Comment by Toni-d-e-v** [comment]
> @Toni-d-e-v , any updates? Did fix above help to resolve your issue?

I did thanks
