### ISSUE TITLE
Add Google Cloud SDK for Windows

### ISSUE THREAD

**Issue by scothis** [actions/virtual-environments#206]
**Tool information**
- Tool name: Google Cloud SDK
- Add or update? Add
- Desired version: latest
- Approximate size: 
- If this is an add request:
  - Brief description of tool: Command-line interface for Google Cloud Platform products and services
  - URL for tool's homepage: https://cloud.google.com/sdk/

**Area for Triage**: Scripting and command line

**Question, Bug, or Feature?**: Feature

**Virtual environments affected**
- [x] macOS 10.15
- [x] Ubuntu 16.04 LTS
- [x] Ubuntu 18.04 LTS
- [X] Windows Server 2016 R2
- [X] Windows Server 2019

**Can this tool be installed during the build?**
This tool is already available on the Mac and Ubuntu environments. There is a chocolatey package available, although it is currently failing. 

**Are you willing to submit a PR?**

**Comment by maxim-lobanov** [comment]
Hello,
Google Cloud SDK can be installed in runtime via the following commands:
```
Invoke-WebRequest "https://dl.google.com/dl/cloudsdk/channels/rapid/GoogleCloudSDKInstaller.exe" -OutFile "GoogleCloudSDKInstaller.exe"
Start-Process -FilePath "GoogleCloudSDKInstaller.exe" -ArgumentList "/S" -Wait
```

**Comment by al-cheb** [comment]
Hello, @scothis 
Sorry for long delay. The https://github.com/actions/virtual-environments/pull/1102 PR was merged and the Google Cloud SDK will be available in the next rollout one/two weeks on Windows Server 2016/2019.

**Comment by al-cheb** [comment]
@scothis,The Google Cloud SDK is now available on Windows Server 2016/2019. Could you please check from your side?

**Comment by scothis** [comment]
@al-cheb looks good. Thanks
