### ISSUE TITLE
[feature request] Windows-2019 support for WSLv1: clarify README on WSLv1 support / point to setup-wsl task for WSLv1 distro installation

### ISSUE THREAD

**Issue by vadimkantorov** [actions/virtual-environments#2060]
From https://github.com/actions/virtual-environments/blob/main/images/win/Windows2019-Readme.md it is not clear whether WSLv1 or WSLv2 is enabled. Both are useful for testing builds: e.g. Perl5 fails `make install` step on WSLv1 https://github.com/Perl/perl5/issues/18254, and cperl fails build on case-insensitive mount point on WSLv1 https://github.com/perl11/cperl/issues/424)

**Comment by al-cheb** [comment]
Hello, @vadimkantorov 
Currently, only WSL1[Microsoft-Windows-Subsystem-Linux] is available on Windows Server 2019[10.0.17763 Build 1518] without any Linux distro pre-installed.

**Comment by vadimkantorov** [comment]
Maybe separate `windows-latest-wslv1-ubuntu-latest`-like environments would be useful to spare users installing the distro every time, but it can quickly get combinatorial

**Comment by al-cheb** [comment]
> Maybe separate `windows-latest-wslv1-ubuntu-latest`-like environments would be useful to spare users installing the distro every time, but it can quickly get combinatorial

Sorry, we don't have any plans to change the current infrastructure and provide a separate image. At the moment, you have two approaches:
1. Install Ubuntu in runtime, using a task - https://github.com/marketplace/actions/setup-wsl
2. Use your own preconfigured [self-hosted runners]( https://docs.github.com/en/free-pro-team@latest/actions/hosting-your-own-runners/about-self-hosted-runners)

**Comment by al-cheb** [comment]
@vadimkantorov , I have created a tiny https://github.com/actions/virtual-environments/pull/2070 PR with updated wsl version. We can't include info about the setup-wsl task into the documentation file,  because we use the same image for Azure PipeLines where the task  is not available.

**Comment by vadimkantorov** [comment]
Thanks for this README fix! Could it also mention that no distro is installed and that needs to be handled separately?

Should I file a separate feature request for providing an official Action (official equivalent of setup-wsl) to install a WSLv1 distro?

**Comment by maxim-lobanov** [comment]
@vadimkantorov Why do you want to have official equivalent of setup-wsl?
Unfortunately, GitHub can't provide official actions for everything but it provides actions marketplace where everyone can write own action and share it with the world. [setup-wsl](https://github.com/marketplace/actions/setup-wsl) is good example to show how it works.
If this action suits for you purposes, I suggest continue using it.

**Comment by al-cheb** [comment]
I am planning close the thread. I'll let you know if there's any change related to WSL.
