### ISSUE TITLE
Stale Cross-Jobs output is coming back

### ISSUE THREAD

**Issue by dougpagani** [actions/virtual-environments#2067]
**Description**  
This may not be the appropriate place for this bug report; please point me in the right direction if that is the case. It seems to be a problem with the runner, but I'm at a loss for a broad-strokes understanding the implementation of some of these features. I may have misunderstood how cross-jobs outputs referencing works, but I believe this is a bug.

Old data from (a previous run of) the same workflow seems to be polluting later runs of workflows. This bug is really hard to reproduce (which makes it particularly annoying), and I'm not entirely sure what is going on, but I do know I've seen this 3 times now. I've caught it this time clearly, by modifying a workflow from `tiket` -> `ticket`; even more strangely is that only one interpolation picked up the "stale" data, but the rest used the new. I tried to capture this succinctly in the following image:
![image](https://user-images.githubusercontent.com/18250753/99256292-2e226e80-27e3-11eb-83d1-edc646d7448f.png)

Perhaps inter-job communication is an immature feature, and I should just lump everything into mega-jobs instead for now? It is really bizarre. It could be that different workflows are making use of the same, un-sanitized environment? 

**Area for Triage**:  

**Question, Bug, or Feature?**:  
Bug

**Virtual environments affected**  
- [ ] Ubuntu 16.04
- [x ] Ubuntu 18.04
- [x ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Expected behavior**  
The `needs`-object only produces the values associated with the current run.

**Actual behavior**  
The `needs`-object is producing old values.

**Repro steps**  
This repo is not public, unfortunately. I've noticed this when you use `echo "::set-output"` style of step-outputs, then passing it up to the job-outputs scope.

1. Create a job that depends on another intraworkflow job, referring to it with `needs:` and `${{ needs.job-id.outputs.outputname }} (making sure that the variable is dynamic)
2. Run it once
3. Run it again, not necessarily on the same commit.
3. Run it again

**Comment by maxim-lobanov** [comment]
Hello @dougpagani , I guess this issue should go to https://github.com/actions/runner
Let's see if we can transfer it

cc:  @thboop @dakale could you please take a look?

**Comment by maxim-lobanov** [comment]
@dougpagani , is it possible to share YAML file to see how you use `set-output` and `needs`? Or share approximate structure?

**Comment by dougpagani** [comment]
Yep I absolutely can -- do you want me to do that here, or open a ticket with the /runner group and do that there? Unsure of how handoff is best organized.

**Comment by dakale** [comment]
Hey @dougpagani I can take a look into this. If possible, can you share the workflow file yaml here, with anything private removed, or as @maxim-lobanov suggested, if its private, just the approximate structure of the jobs, and how you are referencing them in the `set-output` and `needs` sections? 

Ill see if I can reproduce this and understand whats going on, then if necessary I can transfer the issue, so its fine to have the repro steps here in the issue

**Comment by dougpagani** [comment]
@dakale 

This is the general chain of references which are somehow yielding two different results, seemingly from different runs. It's had me pretty confused so I figured I'd put together a diagram to explain what is going awry in the workflow file. Attached is the a markdown-embedded workflow file & expected/actual data outputs. I was hesitant to post, because I thought I may accidentally be grabbing the stale data from AWS via its cli, but no, I'm referring to it explicitly. I can add some more printf-debugging if need be, and that is probably my next move.
 

![image](https://user-images.githubusercontent.com/18250753/100256735-22d1f000-2f13-11eb-8588-eb38b439a901.png)

---- 

The Workflow file in question:
## expected:
```
  Deployment Completed.
  - app url: http://CWA-ticket-872081174.eba-cwuqbgah.us-east-1.elasticbeanstalk.com
  - to terminate when review is done: 
    - cli: npm run deploy:terminate CWA-ticket-872081174
    - gha: go to github actions, and paste-in the ticket-id from monday.com
  - guru doc on process: link to diagram or whatever for context
  - monday.com ticket: https://autotiv.monday.com/boards/406613495/pulses/872081174
  - eb-env mgmt: REDACTED
```

## actual:
```
  Deployment Completed.
  - app url: http://CWA-ticket-545045568.eba-cwuqbgah.us-east-1.elasticbeanstalk.com
  - to terminate when review is done: 
    - cli: npm run deploy:terminate CWA-ticket-872081174
    - gha: go to github actions, and paste-in the ticket-id from monday.com
  - guru doc on process: link to diagram or whatever for context
  - monday.com ticket: https://autotiv.monday.com/boards/406613495/pulses/872081174
  - eb-env mgmt: REDACTED, but this is also wrong, in the same way (app url & eb-env-url both reference ${{ steps.deployment_name.outputs.name }} )
```

## Workflow File in question:
```md
name: Ticket Deployment
on:
  pull_request

env: REDACTED

jobs:
  log-event:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/upload-artifact@v2
      name: upload artifact
      with:
        name: gha-${{ github.event_name }}.json
        path: ${{ github.event_path }}

  deployment: 
    runs-on: ubuntu-latest
    outputs:
      branch_name: ${{ steps.branch.outputs.branch_name }}
      ticket_id: ${{ steps.branch.outputs.ticket_id }}
      deployment_name: ${{ steps.deployment_name.outputs.name }}
      eb_mgmt_url: ${{ steps.eb_mgmt.outputs.url }}
      deployed_app_url: ${{ steps.beanstalk_app.outputs.url }}
    steps:
      - name: debugging info
        run: |
          env
      - name: Get ticket number from branch
        id: branch
        run: |
          branch_name=${{ github.event.pull_request.head.ref }}
          echo "::set-output name=branch_name::${branch_name}"
          ticket_id=$( echo ${branch_name} | \egrep -o -- '^[0-9]{9}' )
          echo "::set-output name=ticket_id::${ticket_id}"


      - name: Verify ticket number
        run: |
          echo ${{ steps.branch.outputs.ticket_id }}
          echo ${{ steps.branch.outputs.branch_id }}

      - name: Format deployment name
        id: deployment_name
        run: |
          echo "::set-output name=name::CWA-ticket-${{ steps.branch.outputs.ticket_id }}"

      - name: Checkout
        uses: actions/checkout@v2.3.3

      - name: Setup Python
        uses: actions/setup-python@v2.1.4
        with:
          # Version range or exact version of a Python version to use, using SemVer's version range syntax.
          python-version: 3 # optional
      - name: check python version
        run: |
          type -a python
          python --version
      - name: power-up as an opsperson
        run: REDACTED
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: do a fresh deployment
        run: CI=false npm run deploy:fresh ${{ steps.deployment_name.outputs.name }}

      - name: Get app url 
        id: beanstalk_app
        run: |
          set -x
          url=http://$(eb status ${{ steps.deployment.outputs.deployment_name }} | grep CNAME | sed 's/.*CNAME: //')
          echo "::set-output name=url::${url}"

      - name: Get AWS:EB management console url
        id: eb_mgmt
        run: |
          set -x
          ebStatus="$(eb status ${{ steps.deployment.outputs.deployment_name }} )"
          echo "$ebStatus"
          region=$(echo "$ebStatus" | grep "Region" | sed 's/.*Region: //')
          appName=$(echo "$ebStatus" | grep "Application name" | sed 's/.*Application name: //' )
          envId=$(echo "$ebStatus" | grep "Environment ID" | sed 's/.*Environment ID: //')

          url="https://console.aws.amazon.com/elasticbeanstalk/home?region=${region}#/environment/dashboard?applicationName=${appName}&environmentId=${envId}"
          echo "::set-output name=url::${url}"

          # Sample sketch:
          # url="https://console.aws.amazon.com/elasticbeanstalk/home?region=us-east-1#/environment/dashboard?applicationName=CustomerWebApp&environmentId=e-3n7yurgyi2"
          # echo "::set-output name=url::${url}"

  notify-reviewers:
    runs-on: ubuntu-latest
    needs: deployment
    steps:

    # General Message Format Example:
        # Deployment Completed.
        # - app url: https://cwa-ticket-1234.eba-cwuqbgah.us-east-1.elasticbeanstalk.com/
        # - to terminate when review is done: 
        #   - cli: npm run deploy:terminate CWA-ticket-595090142
        #   - gha: go to github actions, and past-in the ticket # from monday.com
        # - guru doc on process: link to page + diagram or whatever for context
        # - monday.com ticket: https://autotiv.monday.com/boards/406613495/pulses/595090142

    - name: Format message for plaintext
      run: |
        cat > plaintext.txt << HERE
        Deployment Completed.
        - app url: ${{ needs.deployment.outputs.deployed_app_url }}
        - to terminate when review is done: 
          - cli: npm run deploy:terminate ${{ needs.deployment.outputs.deployment_name }}
          - gha: go to github actions, and paste-in the ticket-id from monday.com
        - guru doc on process: ${{ env.PROCESS_DOC }}
        - monday.com ticket: https://autotiv.monday.com/boards/${{ env.devTicketsBoardNumber }}/pulses/${{ needs.deployment.outputs.ticket_id }}
        - eb-env mgmt: ${{ needs.deployment.outputs.eb_mgmt_url }}
        HERE
    - name: Format message for Email
      run: |
        cat > email.txt << HERE
        <u><i>Deployment Completed.</i></u>
        <br>
          <ul>
          <li><b>app url:</b> ${{ needs.deployment.outputs.deployed_app_url }}</li>
          <li>to terminate when review is done:</li>
            <ul>
              <li><b>cli</b>: <code>npm run deploy:terminate ${{ needs.deployment.outputs.deployment_name }}</code></li>
              <li><b>gha</b>: go to github actions, and paste-in the ticket-id from monday.com</li>
            </ul>
          <li><b>guru doc</b> on process: ${{ env.PROCESS_DOC }}</li>
          <li><b>MDC ticket:</b> https://autotiv.monday.com/boards/${{ env.devTicketsBoardNumber }}/pulses/${{ needs.deployment.outputs.ticket_id }}</li>
          <li>eb-env mgmt: ${{ needs.deployment.outputs.eb_mgmt_url }}</li>
          </ul>
        <br>
        HERE
    - name: Format message for GH-PR
      run: |
        cat > gh-pr.txt << HERE
        _Deployment Completed._ @${{env.codeReviewerGithubName}} @${{env.productManagerGithubName}}
        - **app url:** ${{ needs.deployment.outputs.deployed_app_url }}
        - to terminate when review is done: 
          - **cli:** \`npm run deploy:terminate ${{ needs.deployment.outputs.deployment_name }}\`
          - **gha:** go to github actions, and paste-in the ticket-id from monday.com
        - **guru doc** on process: ${{ env.PROCESS_DOC }}
        - **monday.com ticket:** https://autotiv.monday.com/boards/${{ env.devTicketsBoardNumber }}/pulses/${{ needs.deployment.outputs.ticket_id }}
        - **eb-env mgmt**: ${{ needs.deployment.outputs.eb_mgmt_url }}
        HERE
      
    - name: Send mail 
      uses: dawidd6/action-send-mail@v2
      with:
        server_address: smtp.gmail.com
        server_port: 465
        # Key piece for configuring this email:
        # https://support.google.com/accounts/answer/6010255
        username: ${{secrets.MAIL_USERNAME}}
        password: ${{secrets.MAIL_PASSWORD}}
        subject: "Ready for CR/DR: ${{ needs.deployment.outputs.branch_name }}"
        body: file://email.txt
        # # Read file contents as body:
        # body: file://README.md
        to: ${{ env.codeReviewerEmail }},${{ env.productManagerEmail }}
        from: App Builder # <user@example.com>
        # Optional content type (defaults to text/plain):
        content_type: text/html
        # # Optional attachments: (if generating any build artifacts)
        # attachments: attachments.zip,git.diff,./dist/static/main.js

    - name: Sticky Pull Request Comment
      uses: marocchino/sticky-pull-request-comment@v1.6.0
      with:
        path: gh-pr.txt
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}



```

**Comment by dougpagani** [comment]
Nevermind; I finally found the error. I was getting a null-reference instead of an actual value. 

basically, instead of: 

`${{ steps.deployment_name.outputs.name }}`

I was doing:
`${{ steps.deployment.outputs.deployment_name }}`

This was made more confusing by the fact that the cli tool this workflow uses in those spots has default behavior for a no-argument invocation. 

Seeing as this was such a costly but quiet oversight, I wonder if it would be a smart idea to warn on `${{steps.INVALID_NAME.outputs.key}}`. It is probably too late to reject workflow-runs outright at this point, since there's probably 100s of people who depend on `undefined` in context expressions mapping to `""` in the interpolated shell, but a warning could potentially save a lot of frustration for future developers. Obviously knowing this I'll be more careful to never hit this case myself, but just a thought for improving the platform for all.
