### ISSUE TITLE
Error when building image based on packer file for Windows Server 2019 - 

### ISSUE THREAD

**Issue by mihsoft** [actions/virtual-environments#2068]
**Description**  
```
==> vhd: Provisioning with Powershell...

==> vhd: Provisioning with powershell script: /agent/_work/1/s/virtual-environments/images/win/scripts/Installers/Update-ImageData.ps1

==> vhd: Out-File : Cannot bind argument to parameter 'FilePath' because it is null.

==> vhd: At C:\Windows\Temp\script-5fb292dc-b5fe-fb88-7b7c-d6024f89b614.ps1:35 char:28
```

**Area for Triage**:  

**Question, Bug, or Feature?**:  

**Virtual environments affected**  
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [x] Windows Server 2019

**Expected behavior**  
Successful image build

**Actual behavior**  
Error

**Repro steps**  
A description with steps to reproduce the issue. If your have a public example or repo to share,
please provide the link.

1. Clone the repository using the win19/20201108.1 tag

**Comment by al-cheb** [comment]
Hello, @mihsoft 
The script https://github.com/actions/virtual-environments/blob/main/images/win/scripts/Installers/Update-ImageData.ps1 contains statement:
```
$imageVersion = $env:IMAGE_VERSION
$imageDataFile = $env:IMAGEDATA_FILE
......
$json | Out-File -FilePath $imageDataFile
```

Tee variables `IMAGE_VERSION` and `IMAGEDATA_FILE` we define in the file - https://github.com/actions/virtual-environments/blob/main/images/win/windows2019.json :
```
 "imagedata_file": "C:\\imagedata.json",
 "image_version": "dev",
        {
            "type": "powershell",
            "environment_vars": [
                "IMAGE_VERSION={{user `image_version`}}",
                "IMAGEDATA_FILE={{user `imagedata_file`}}"
            ],
            "scripts": [
                "{{ template_dir }}/scripts/Installers/Update-ImageData.ps1",
            ]
        },
```

Please correct update your packer template.
