### ISSUE TITLE
Update/Add MacOS Visual Studio Tools for Unity

### ISSUE THREAD

**Issue by StephenHodgson** [actions/virtual-environments#2071]
**Tool information**
- Tool name: Visual Studio Tools for Unity
- Tool license: Free
- Add or update? Update
- Desired version: 
- Approximate size: 
- If this is an add request:
  - Brief description of tool: It is a free extension for Visual Studio that is already installed on windows images but not the mac ones.
  - URL for tool's homepage: https://docs.microsoft.com/en-us/visualstudio/gamedev/unity/get-started/getting-started-with-visual-studio-tools-for-unity?view=vsmac-2019&pivots=macos
  - Provide a basic test case to validate the tool's functionality: For building Unity Engine based applications.

**Area for Triage**:

**Feature**:

**Virtual environments affected**
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [x] macOS 10.15
- [x] macOS 11.0
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Can this tool be installed during the build?**

**Tool installation time in runtime**

**Are you willing to submit a PR?**

yes

**Comment by maxim-lobanov** [comment]
Hello @StephenHodgson , thank you for your proposal.
I have a few questions:
1) Do you know what is the size of this extension?
2) You mentioned that you are ready to submit PR. Sorry, as it is mentioned in readme, we don't accept contributions to macOS right now but we would be very appreciate if you point us to the code / guide how this extension can be installed via terminal. We didn't install extensions for Visual Studio For Mac before.

**Comment by StephenHodgson** [comment]
It's an installation option when installing visual studio, so I have no idea what the size is.

It can likely be added when visual studio is installed with additional parameters.

**Comment by nikita-bykov** [comment]
Hello @StephenHodgson. Tools for Unity is installed as a default extension in Visual Studio for macOS. It is mentioned on the [Get started with Visual Studio and Unity ](https://docs.microsoft.com/en-us/visualstudio/gamedev/unity/get-started/getting-started-with-visual-studio-tools-for-unity?view=vsmac-2019&pivots=macos#install-unity-support-for-visual-studio)wiki page. We've checked this on the macOS 10.15 image and as You can see on the image below this extension is already installed.
![изображение](https://user-images.githubusercontent.com/49442273/101151496-c8334500-3632-11eb-98ed-908ae76baff7.png)
 Also You can find it along this path `/Applications/Visual Studio.app/Contents/Resources/lib/monodevelop/AddIns/MonoDevelop.Unity`
Could you please provide us with more details about the problem you faced?

**Comment by StephenHodgson** [comment]
Ah I see. There is a discrepancy between the Windows and Mac VS Installers. The Windows version also installs the Unity Hub as part of the game development workload. I guess I just need to take that up with MSFT. Thanks
