### ISSUE TITLE
Install-WDK failing on Windows 2019 image

### ISSUE THREAD

**Issue by riezebosch** [actions/virtual-environments#208]
**Describe the bug**
In the last release from the old repo this script portion was disabled: https://github.com/microsoft/azure-pipelines-image-generation/blob/releases/vs2019/20191209/images/win/scripts/Installers/Vs2019/Install-WDK.ps1

**Virtual environments affected**
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [x ] Windows Server 2019

**Expected behavior**
[Running the VSIXnstaller](https://github.com/actions/virtual-environments/blob/96e9a6ab664d4f11077194f5ac5c70baedcebab3/images/win/scripts/Installers/Windows2019/Install-WDK.ps1#L35) from the VS2019 directory should _probably_ take place _after_ the VS2019 installation script is run.

**Actual behavior**
In [current packer template](https://github.com/actions/virtual-environments/blob/master/images/win/Windows2019-Azure.json#L156) the `Install-WDK` script is run prior to the `Install-VS2019` script.

From our logs:
```
==> vhd: Start-Process : This command cannot be run due to the error: The system cannot find the file specified.
==> vhd: At C:\Windows\Temp\script-5e0206cb-ef62-b1b3-285f-0beff0e0b781.ps1:34 char:13
    vhd: Unsuccessful exit code returned by the installation process: .
```

**Comment by kaylangan** [comment]
Fixed in #157 and awaiting deployment.
