### ISSUE TITLE
Update Visual Studio to v8.8 for virtual environment macOS 11

### ISSUE THREAD

**Issue by AlexSrizhevskiy** [actions/virtual-environments#2082]
Update Visual Studio to v8.8 for virtual environment macOS 11 as [required](https://dotnet.microsoft.com/download/dotnet/5.0) for .net 5.0.100

**Tool information**
- Tool name: Visual Studio 2019 for Mac
- Tool license: free
- Add or update? update
- Desired version: 8.8

**Virtual environments affected**
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [x] macOS 10.15
- [x] macOS 11.0
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Comment by AlenaSviridenko** [comment]
Hey @AlexSrizhevskiy, macOS 11.0 image is on its way with new Visual Studio and will be deployed in 1-2 days.

You can track its releases here: https://github.com/actions/virtual-environments/releases/tag/macOS-11.0%2F20201116.13

**Comment by AlexSrizhevskiy** [comment]
Hi @AlenaSviridenko, is there any way to understand that MacOS 11.0 is available at ADO? Currently macOS 11.0 (20201116 update) has label 'Latest release', but still unavailable on AzureDevOps.

**Comment by maxim-lobanov** [comment]
@AlexSrizhevskiy , MacOS 11.0 is not available in AzDO yet.

Actually, Visual Studio For Mac 8.8 will be available on both MacOS 10.15 and 11.0. 10.15 is available in ADO and will be updated.
We are expecting these changes to be rollout tomorrow

**Comment by dibir-magomedsaygitov** [comment]
Hello, @AlexSrizhevskiy, rollout of images with Visual Studio For Mac 8.8 has been completed.
