### ISSUE TITLE
(Az available image 4.8)  Use of New-AzSqlDatabaseExport is failing on MS Hosted agent 

### ISSUE THREAD

**Issue by zakariaaazair** [actions/virtual-environments#2088]
MS Support team told us that this is fixed on Az.Sql 2.11.1 but needs Az 5.0.0 module installed on MS hosted agent.

So it needs the MS Hosted agent to be updated and we don't have any ETA on this.

**Comment by maxim-lobanov** [comment]
@zakariaaazair , could you please follow proper template for your request? https://github.com/actions/virtual-environments/blob/main/.github/ISSUE_TEMPLATE/tool-request.md
Please adjust issue description according to template

**Comment by dibir-magomedsaygitov** [comment]
I'm going to close this issue. Feel free to open new one in case of any questions.
