### ISSUE TITLE
Update Ruby to 2.7

### ISSUE THREAD

**Issue by mislav** [actions/virtual-environments#209]
**Tool information**
- Tool name: Ruby
- Add or update? update
- Desired version: 2.7.0
- Approximate size: 30 MB (without docs)

**Area for Triage**: Ruby

**Question, Bug, or Feature?**: feature

**Virtual environments affected**
- [ ] macOS 10.15
- [x] Ubuntu 16.04 LTS
- [x] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Can this tool be installed during the build?**
no

**Are you willing to submit a PR?**
I would, but from [the current installer script](https://github.com/actions/virtual-environments/blob/95954b3f022a1c4626d112bd4fe82d0812fa6f4b/images/linux/scripts/installers/ruby.sh) it's not clear to me how individual Ruby versions are installed. It looks like pre-built Ruby versions [are downloaded](https://github.com/actions/virtual-environments/blob/95954b3f022a1c4626d112bd4fe82d0812fa6f4b/images/linux/scripts/installers/1804/hosted-tool-cache.sh#L16-L18) from [something called "tool cache"](https://github.com/microsoft/azure-pipelines-tool-lib/blob/master/docs/overview.md#tool-cache), but the end process is opaque and I can't find how to add new Ruby versions there.

https://www.ruby-lang.org/en/news/2019/12/25/ruby-2-7-0-released/
See also https://github.com/actions/virtual-environments/issues/95

**Comment by eregon** [comment]
Until Ruby 2.7.0 is supported here, https://github.com/eregon/use-ruby-action can be used for testing against Ruby 2.7.0 in GitHub Actions.

**Comment by maxim-lobanov** [comment]
Ruby 2.7 is available on Ubuntu images
