### ISSUE TITLE
[macOS] Backward compatibility of Az and AzureRM will be dropped on December, 14

### ISSUE THREAD

**Issue by AlenaSviridenko** [actions/virtual-environments#2090]
**Breaking changes**
We are going to stop adding backward compatibility of Az and AzureRM by Enable-AzureRmAlias cmdlet.

**Target date**
Image rollout will start on ~December, 7~ December, 14 and will take 2-3 days.

**The motivation for the changes**
Az.Accounts from Az module 5.х is not working correctly when this alias is enabled, the following warning is generated:
`WARNING: Token cache encryption is not supported in current environment and token cache will be fallen back as plain text`

**Possible impact**
If you are using cmdlet's with RM prefix — your builds will be broken.

**Virtual environments affected**
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [x] macOS 10.13
- [x] macOS 10.14
- [x] macOS 10.15
- [x] macOS 11.0
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Mitigation ways**
Run `Enable-AzureRmAlias` at the beginning of your build.

**Comment by rmccarrick** [comment]
We are using Rundeck 3.1.2-20190927 running on Ubuntu and a node in Microsoft Windows Server 2016 . We use Rundeck to run powershell scripts that live on the Windows node. Until the last week, all was working well. But now all rundeck jobs start out with the warning "WARNING: INITIALIZATION: Token cache encryption is not supported in current environment and token cache will be fallen back as plain text" Even the scripts that are not using powershell. One of the scripts deploys VMs in Azure.
When we run the script on the powershell command line, it works. When we run it from Rundeck it fails. Rundeck starts with the above warning, and then Connect-AzAccount  results in the following error:

Connect-AzAccount : UsernamePasswordCredential authentication failed: Persistence check failed. Inspect inner exception for details

Again, running the same code on the command line works. The credentials are correct.

It looks like Az.Accounts was updated on Dec 9.
 Directory of C:\Program Files\WindowsPowerShell\Modules\Az.Accounts

12/09/2020  01:27 PM    <DIR>          .
12/09/2020  01:27 PM    <DIR>          ..
12/05/2019  02:28 PM    <DIR>          1.6.4
07/31/2020  02:36 PM    <DIR>          1.9.1
12/09/2020  01:27 PM    <DIR>          2.2.2


Any ideas would be greatly appreciated

**Comment by AlenaSviridenko** [comment]
Hi @rmccarrick,
we didn't deploy any images last week, but I see Az.Accounts 2.2.2 was released exactly 8 days ago https://www.powershellgallery.com/packages/Az.Accounts/2.2.2, maybe you are installing it during the build.
Since this issue is not related to the image, please, create an issue in the [official Azure-PowerShell repo ](https://github.com/Azure/azure-powershell/issues) and module owners will investigate it. Thanks!

**Comment by al-cheb** [comment]
The mac OS rollout, without RM prefix, has been finished.
