### ISSUE TITLE
MacOS builds not finishing

### ISSUE THREAD

**Issue by peterdanis** [actions/virtual-environments#2093]
**Description**  
Hi, I have a small sample repo to check compatibility of various version of some software, which is running on Linux, Windows and MacOS.

Until approx. beginning of November everything worked fine, but now the MacOS builds just hang on last step and timeouts after 6 hours. The last step is finishing successfully but it still timeouts.

![image](https://user-images.githubusercontent.com/26599181/99586991-bde53a00-29e8-11eb-8cc2-36304ccaf316.png)

![image](https://user-images.githubusercontent.com/26599181/99587362-4c59bb80-29e9-11eb-9383-baf2436ad7df.png)

**Area for Triage**:  Apple

**Question, Bug, or Feature?**:  Bug

**Virtual environments affected**  
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [x] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Expected behavior**  
Build finishes.

**Actual behavior**  
Build hangs.

**Repro steps**  
https://github.com/peterdanis/electron-puppeteer-demo/runs/1384797118?check_suite_focus=true

**Comment by vsafonkin** [comment]
Hi @peterdanis , looks like the reason of issue is [update version of jest to 26.6.3](https://github.com/peterdanis/electron-puppeteer-demo/commit/e48363cf58ba258b717bb54405ceb86376005135). Package `fsevents` has version 2.2.0 in package-lock.json, but you need 2.2.1. You should regenerate your package-lock.json, it works for me: https://github.com/vsafonkin/electron-puppeteer-demo/runs/1424213452?check_suite_focus=true

**Comment by peterdanis** [comment]
Thanks @vsafonkin ! I did help and MacOS builds are working in my repo again.
