### ISSUE TITLE
You have reached your pull rate limit

### ISSUE THREAD

**Issue by hutson** [actions/virtual-environments#2094]
**Description**  

When building Ubuntu images (It may also effect Windows) using a fork of this repository, I get the following error: `toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit`

**Area for Triage**:  

**Question, Bug, or Feature?**:  

Bug

**Virtual environments affected**  
- [x] Ubuntu 16.04
- [x] Ubuntu 18.04
- [x] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Expected behavior**  

I imagine I can extend the provisioners for the Ubuntu images to setup the appropriate authentication credentials, or to point to a Docker Hub mirror (The latter is preferred), which would avoid the rate limiting imposed on unauthenticated requests.

I simply do not know the best way to apply that change without it becoming difficult to maintain in a fork.

**Actual behavior**  

When building Ubuntu images (It may also effect Windows) using a fork of this repository, I get the following error: `toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit`

```
    ami:  OSType: linux
    ami:  Architecture: x86_64
    ami:  CPUs: 2
    ami:  Total Memory: 7.59GiB
    ami:  Name: ip-172-31-197-208
    ami:  ID: Y7LB:2E63:E6EC:M3FG:HQPG:XFD2:E6XT:CKZL:KOLY:4BBJ:NFFU:A3FT
    ami:  Docker Root Dir: /var/lib/docker
    ami:  Debug Mode: false
    ami:  Registry: https://index.docker.io/v1/
    ami:  Labels:
    ami:  Experimental: false
    ami:  Insecure Registries:
    ami:   127.0.0.0/8
    ami:  Live Restore Enabled: false
    ami:
    ami: 3.7: Pulling from library/alpine
==> ami: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
==> ami: Provisioning step had errors: Running the cleanup provisioner, if present...
==> ami: Terminating the source AWS instance...
==> ami: Cleaning up any extra volumes...
==> ami: No volumes to clean up, skipping
==> ami: Deleting temporary security group...
==> ami: Deleting temporary keypair...
Build 'ami' errored after 9 minutes 29 seconds: Script exited with non-zero exit status: 1.Allowed exit codes are: [0]
```

**Repro steps**  

```
packer build \
  -only=ami \
  -var install_password=$(uuidgen) \
  -var github_feed_token=${FEED_TOKEN} \
  ./virtual-environments/images/linux/ubuntu1804.json
```

Where we use a custom AMI builder in the Packer config file with the name `ami`.

**Comment by maxim-lobanov** [comment]
Hello @hutson , we didn't face with this issue on our test and prod CI yet but probably can face in future.
As for the solution, we would prefer to authorize in original DockerHub. I think we can just add two more optional variables to packer template like `DOCKERHUB_LOGIN`, `DOCKERHUB_PASSWORD`. If both variables are set, script will login to docker, download images and loggout.

What do you think about such solution?

**Comment by PedroFonsecaDEV** [comment]
Same on MacOs(BigSur - MacBook Pro 2018)
```Pulling login (kristophjunge/test-saml-idp:)...
ERROR: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit```

**Comment by hutson** [comment]
`

DOCKERHUB_LOGIN, DOCKERHUB_PASSWORD

**Comment by hutson** [comment]
`DOCKERHUB_LOGIN, DOCKERHUB_PASSWORD` would work for my use case for the purpose of getting the unlimited rare limit of an authenticated account.

**Comment by MaksimZhukov** [comment]
I'm going to close this issue since the [PR](https://github.com/actions/virtual-environments/pull/2548) was merged. 
Feel free to contact us if you have any questions

**Comment by aaron-prindle** [comment]
I am currently seeing a pull rate limit issue attempting to run a CI job with github actions using minikube with the virtualbox driver:
`minikube start --driver=virtualbox`

Error encountered:
```
        unable to stream build output: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit. Please fix the Dockerfile and try again..
    --- FAIL: TestInitKustomize/kustomize_init (3.73s)
```
full logs here:
https://github.com/GoogleContainerTools/skaffold/runs/2766918300?check_suite_focus=true

My understanding is that github actions shouldn't be rate limited by docker hub API from the discussion above.  Does anyone have any ideas on why we might be seeing this 500 issue and how we might able to fix this?  Thanks

**Comment by miketimofeev** [comment]
@aaron-prindle thls rate limit does not affect windows and Linux since both OSs have docker preinstalled. We can't pre-install docker on the mac due to license concerns thus can't apply higher rates.

**Comment by aaron-prindle** [comment]
@miketimofeev thanks for the response here!  Is there any way to configure a locally installed docker on a mac github action to have the configuration required that windows & linux have to not be pull rate limited?  Thanks

**Comment by catthehacker** [comment]
I suggest creating a separate service account with no access to push images, that way you could authenticate via standard docker login action
https://docs.docker.com/docker-hub/service-accounts/
