### ISSUE TITLE
Similar to #2093:  Build never finish on windows

### ISSUE THREAD

**Issue by Milerius** [actions/virtual-environments#2098]
**Description**  
Hello everyone, I'm looking for someone who has experience with GitHub Actions and C++, I have a very strange bug, indeed it looks like I have an infinite loop when I compile on the GitHub actions machine ( windows only) and this absolutely does not happen on my local windows:

On Github actions after 360 minutes it's timing out:
```cpp
[686/688] Linking CXX executable bin\atomicdex-desktop_tests.exe
SIGINT: Interrupted by Ctrl-C.
ninja: build stopped: interrupted by user.
Error: The operation was canceled.
```

I have absolutely no idea how to debug that, especially that's work locally, i have the commit that produced this behaviour: https://github.com/KomodoPlatform/atomicDEX-Desktop/commit/ecf3d0d44cbd28b1cbc275d76597e9f83bca2dc7

But there is no spurious stuff inside, any idea or recommendation would be nice

The problem really seems to come from the remote machine - the compilation works on all other platforms and especially works locally on windows, there will not have been an update which will produce this bug ?

Extra infos:

compiler: clang-11

<img width="1680" alt="Capture d’écran 2020-11-20 à 06 30 41" src="https://user-images.githubusercontent.com/21139416/99762964-f6286d80-2af9-11eb-9780-afd8c2279bf9.png">

<img width="1680" alt="Capture d’écran 2020-11-20 à 06 31 46" src="https://user-images.githubusercontent.com/21139416/99763016-122c0f00-2afa-11eb-87d0-406990fffb4a.png">

**Area for Triage**:  
Windows

**Question, Bug, or Feature?**:  
Bug

**Virtual environments affected**  
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [x] Windows Server 2019

**Expected behavior**  

Builds to finish

**Actual behavior**  

Hanging out for ever

**Repro steps**  

Commits to the following pull request: https://github.com/KomodoPlatform/atomicDEX-Desktop/pull/577

**Comment by Milerius** [comment]
Seems that CMake 3.19 is causing the big trouble, was updated from CMake 3.18.4 from scoop installer, i will let this issue open and link it to a CMake and a scoop issue for transparence.

**Comment by vsafonkin** [comment]
Hello @Milerius , thank you for your report! We're investigating your issue, but unfortunately we have not any positive results yet, sorry.

**Comment by Milerius** [comment]
@vsafonkin Yes, it's seems to come from CMake regression directly, i think it's nothing related to virtual-environments, but can happens to every user that have an automatic update to last official CMake version aka (3.19)
