### ISSUE TITLE
Add Skaffold

### ISSUE THREAD

**Issue by bernhardvollnhofer** [actions/virtual-environments#2099]
**Tool information**
- Tool name: Skaffold
- Tool license: Apache 2.0
- Add or update? Add
- Desired version: latest
- Approximate size: 
- If this is an add request:
  - Brief description of tool: Skaffold is a command line tool that facilitates continuous development for Kubernetes applications. You can iterate on your application source code locally then deploy to local or remote Kubernetes clusters. Skaffold handles the workflow for building, pushing and deploying your application. It also provides building blocks and describe customizations for a CI/CD pipeline.
  - URL for tool's homepage: https://skaffold.dev/
  - Provide a basic test case to validate the tool's functionality: `skaffold version`

**Area for Triage**:

**Question, Bug, or Feature?**:
Feature

**Virtual environments affected**
- [ ] Ubuntu 16.04
- [x] Ubuntu 18.04
- [x] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Can this tool be installed during the build?**
```
curl -Lo skaffold https://storage.googleapis.com/skaffold/releases/latest/skaffold-linux-amd64 && \
sudo install skaffold /usr/local/bin/
```

**Tool installation time in runtime**
1 second

**Are you willing to submit a PR?**
No

**Comment by maxim-lobanov** [comment]
Hello @bernhardvollnhofer , thank you for feature request.
Usually, we don't bake into the image software that could be installed very quick in runtime due to maintenance concerns.
As you mentioned, this tool can be installed in runtime in 1 second.
Also I see that there is a community action to install it: https://github.com/marketplace/actions/skaffold-build-action

**Comment by bernhardvollnhofer** [comment]
> Hello @bernhardvollnhofer , thank you for feature request.
> Usually, we don't bake into the image software that could be installed very quick in runtime due to maintenance concerns.
> As you mentioned, this tool can be installed in runtime in 1 second.
> Also I see that there is a community action to install it: https://github.com/marketplace/actions/skaffold-build-action

OK.
Thank you very much for your quick reply. 🙂

**Comment by dibir-magomedsaygitov** [comment]
I'm going to close this issue. In case of any questions feel free to contact us.
