### ISSUE TITLE
Add Flutter SDK

### ISSUE THREAD

**Issue by cachapa** [actions/virtual-environments#21]
**Tool information**
- Tool name: Flutter SDK
- Add or update? Add
- Desired version: Whatever is latest
- Approximate size: 500 MB
- If this is an add request:
  - Brief description of tool: Flutter is a Google SDK for building cross-platform Android, iOS (MacOS host only), Web and desktop apps.
  - URL for tool's homepage: https://flutter.dev

**Virtual environments affected**
- [x] macOS 10.14
- [x] Ubuntu 16.04 LTS
- [x] Ubuntu 18.04 LTS
- [x] Windows Server 2016 R2
- [x] Windows Server 2019

**Can this tool be installed during the build?**
Yes, using subosito/flutter-action, takes ~60s to complete

**Comment by river2202** [comment]
+1

**Comment by alepauly** [comment]
@cachapa Thanks for the suggestion, there's a pretty good setup-flutter Action available and we have concerns over version maintenance on the virtual environment so we won't be adding it at this time.
