### ISSUE TITLE
Unable to import powershell module

### ISSUE THREAD

**Issue by igagis** [actions/virtual-environments#2105]
**Description**  
When trying to import CoAPP powershell module it fails with an error.

It works on Appveyor, see log https://ci.appveyor.com/project/igagis/utki/builds/36356667
So this is why I think something is wrong with the image.

**Area for Triage**:  
.NET Framework

**Question, Bug, or Feature?**:  
Bug

**Virtual environments affected**  
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [x] Windows Server 2019

**Expected behavior**  
Module is imported without errors.

**Actual behavior**  
The following error occurs:

````
Line |
   3 |  Import-Module CoApp
     |  ~~~~~~~~~~~~~~~~~~~
     | Could not load type 'System.Web.HttpException' from assembly 'System.Web, Version=4.0.0.0,
     | Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
````

**Repro steps**  

See build: https://github.com/cppfw/utki/runs/1434602700?check_suite_focus=true

**Comment by al-cheb** [comment]
Hello, @igagis 
The default shell for Windows Server 2019 is PowerShell Core, not a PowerShell Desktop. You should set up PowerShell Desktop in your pipeline:

```
    - name: import CoAPP module
      shell: powershell
      run: |
        $env:PSModulePath = $env:PSModulePath + ';C:\Program Files (x86)\Outercurve Foundation\Modules'
        Import-Module CoApp
```

![image](https://user-images.githubusercontent.com/47745270/99934782-03e72880-2d70-11eb-9905-d8df297c3728.png)

**Comment by igagis** [comment]
Hi @al-cheb 
Thanks, it worked.

One more question, my build now fails on build step saying that no `msbuild` is found, see build: https://github.com/cppfw/utki/runs/1442074622?check_suite_focus=true
Though, on previous step of `nuget update` seems like it has found some `msbuild`.
Any idea why could this be?

The build phase is done by the ps1 script https://github.com/cppfw/utki/blob/master/nuget/build_nuget.ps1
as you can see from that script, I'm running `%VS142COMNTOOLS%\VsMSBuildCmd.bat` first, so, in my understanding it should initialize all the PATHs needed to find proper build tools including `msbuild`...

**Comment by maxim-lobanov** [comment]
@igagis , I think this issue contains information about msbuild behavior: https://github.com/actions/virtual-environments/issues/1978

**Comment by igagis** [comment]
@maxim-lobanov Thanks, that worked as well!

One more small question: is it possible to append something to an environment variable?
For example, now I'm doing it inside of the step's `run`:
````
run: |
        $env:PSModulePath = $env:PSModulePath + ';C:\Program Files (x86)\Outercurve Foundation\Modules'
        Import-Module CoApp
````

is it possible to do it somehow in `env:` property, so that I could do it once for all steps? Something like this:
````
env:
  PSModulePath: $PSModulePath;C:\Program Files (x86)\Outercurve Foundation\Modules
steps:
   ....
````
I tried this and it does not work as expected, `$PSModulePath` is not substituted. But maybe there is some correct syntax to achieve that?

**Comment by maxim-lobanov** [comment]
Unfortunately, it is not possible in `env` section.

But you can use GA workflow command:
```yaml
steps:
- run: echo "PSModulePath=$(env:PSModulePath);C:\Program Files (x86)\Outercurve Foundation\Modules" | Out-File -FilePath $env: GITHUB_ENV -Encoding utf8 -Append
```

This way, updated variable will be available in all next steps. See details in https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-commands-for-github-actions#environment-files

**Comment by igagis** [comment]
@maxim-lobanov Thanks a lot! It worked!
To ease the appending paths to env vars I have wrapped that command to an action: https://github.com/marketplace/actions/append-path-to-an-environment-variable-using-powershell
