### ISSUE TITLE
Unable to run web server on windows

### ISSUE THREAD

**Issue by abdullah-lt** [actions/virtual-environments#2106]
**Description**  
I am trying to run a webserver written in golang on port 8090. When I a make curl request to `localhost:8090/hello`, it says `Connection refused`. I have a local window machine with me and I am running same golang binary and it is working there. When I check port usage `netstat -aon`, I can clearly see that 8090 TCP port is listening.

Note : This works fine on macOS

Sample action run
https://github.com/LambdaTest/lambda-github-actions/runs/1438201772?check_suite_focus=true

**Virtual environments affected**  
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11.0
- [x] Windows Server 2016 R2
- [x] Windows Server 2019

**Expected behavior**  
localhost should be recheable

**Actual behavior**  
localhost is not recheable

**Repro steps**  
1. Create and build simple golang web app running on port 8090 - https://gobyexample.com/http-servers
Attaching a sample binary
[web.zip](https://github.com/actions/virtual-environments/files/5579651/web.zip)
2. Run the golang binary
3. Try hitting the url (localhost:8090/hello) using curl from local windows system and through github actions

Yaml file for github actions

````
on: [push, workflow_dispatch]
jobs:
  build:
    name: Greeting
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run a multi-line script
      shell: cmd
      run: |
        netsh advfirewall set allprofiles state off
        START /B web.exe
        netstat -aon
        tasklist
        curl -L http://127.0.0.1:8090/hello
`````

**Comment by andy-mishechkin** [comment]
Hello, @abdullah-lt 
As I see you use START /B web.exe for running the your web server. In this case your web.exe starts as child process of command shell in the 'Run a multi-line script' step. 
When this step will be finished - all process tree with web.exe will be killed.
![image](https://user-images.githubusercontent.com/57713077/100086334-b8637600-2e66-11eb-8de6-7fdd8f2d9640.png)
And web.exe will not present for the next steps.
For preventions of this situation you can use the next variant:
`cmd /c "START web.exe"`
or you can use PowerShell command:
`Start-Process -FilePath web.exe`

**Comment by abdullah-lt** [comment]
Thanks @andy-mishechkin for the help :+1:
