### ISSUE TITLE
Upgrade some repos from http to https

### ISSUE THREAD

**Issue by KOLANICH** [actions/virtual-environments#2108]
Here is a fragment from one of my actions:

```bash
sudo find /etc/apt -name "*.list" -exec sed -i 's%http://azure.archive.ubuntu.com%https://mirrors.edge.kernel.org%g' {} \; ;
sudo find /etc/apt -name "*.list" -exec sed -i 's%http://dl.google.com%https://dl.google.com%g' {} \; ;
sudo find /etc/apt -name "*.list" -exec sed -i 's%http://packages.cloud.google.com%https://packages.cloud.google.com%g' {} \; ;
sudo find /etc/apt -name "*.list" -exec sed -i 's%http://apt.postgresql.org%https://apt.postgresql.org%g' {} \; ;
sudo find /etc/apt -name "*.list" -exec sed -i 's%http://download.opensuse.org%https://download.opensuse.org%g' {} \; ;
```

**Comment by dibir-magomedsaygitov** [comment]
Hello, @KOLANICH. We have merged [PR ](https://github.com/actions/virtual-environments/pull/2133) with the related changes. I'll post an update message as soon as new images are ready to use.

**Comment by dibir-magomedsaygitov** [comment]
Hello, @KOLANICH. Changes are delivered to all images. I'm going to close this issue. In case of any questions feel free to contact us.

**Comment by KOLANICH** [comment]
Thanks for everyone involved!

**Comment by KOLANICH** [comment]
...

https://github.com/KOLANICH/AnyVer.py/runs/1565300970

> Get:12 http://dl.google.com/linux/chrome/deb stable InRelease [1811 B]

It's strange.
