### ISSUE TITLE
Cannot edit ~/.gnupg/gpg.conf, get Permission denied

### ISSUE THREAD

**Issue by KOLANICH** [actions/virtual-environments#2109]
**Description**  
Cannot edit `~/.gnupg/gpg.conf`, get `Permission denied`
The code is: `cat ${{github.action_path}}/gpg.conf >> ~/.gnupg/gpg.conf;`

**Area for Triage**:  

**Question, Bug, or Feature?**:  

**Virtual environments affected**  
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [x] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Expected behavior**  
The file should be edited;

**Actual behavior**  
`Permission denied`

**Repro steps**  

```bash
mkdir -p ~/.gnupg;
touch ~/.gnupg/gpg.conf;
chmod -R 600 ~/.gnupg;
cat ${{github.action_path}}/gpg.conf >> ~/.gnupg/gpg.conf;
```

**Comment by al-cheb** [comment]
Hello, @KOLANICH 
This behavior is by design - https://askubuntu.com/questions/83788/accessing-files-in-a-directory-without-x-permission
```
- name: chmod gnupg
  run: |
         mkdir -p ~/.gnupg
         touch ~/.gnupg/gpg.conf
         chmod -R 600 ~/.gnupg/*
         cat ${{github.action_path}}/gpg.conf >> ~/.gnupg/gpg.conf
```
![Uploading image.png…]()

**Comment by KOLANICH** [comment]
My bad, shame on me. ﻿🤦
