### ISSUE TITLE
Impossible to install wxPython package on Windows runner using pip

### ISSUE THREAD

**Issue by robbyb67** [actions/virtual-environments#2110]
**Description**  
When having wxPython in requirements.txt of a python project, running 

`
pip install -r requirements.txt
` 

fails on Windows runner.

**Area for Triage**:  
Python

**Question, Bug, or Feature?**:  
Bug

**Virtual environments affected**  
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [x ] Windows Server 2019

**Expected behavior**  
wxPython package succeeds to install. 

**Actual behavior**  

pip install wxPython 

fails with the following error:
`    Checking for C:\Users\runneradmin\AppData\Local\Temp\pip-install-e4qjtaxe\wxpython\bin\waf-2.0.19...
    MSVC: C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\amd64\cl.exe
    "c:\hostedtoolcache\windows\python\3.9.0\x64\python.exe" C:\Users\runneradmin\AppData\Local\Temp\pip-install-e4qjtaxe\wxpython\bin\waf-2.0.19 --msvc_arch=x64 --python="c:\hostedtoolcache\windows\python\3.9.0\x64\python.exe" --out=build/waf/3.9/x64/release configure build
    Setting top to                           : C:\Users\runneradmin\AppData\Local\Temp\pip-install-e4qjtaxe\wxpython
    Setting out to                           : C:\Users\runneradmin\AppData\Local\Temp\pip-install-e4qjtaxe\wxpython\build\waf\3.9\x64\release
    msvc: Impossible to find a valid architecture for building ['msvc 14.2'] - ['msvc 16.7', 'msvc 14.0']
    (complete log in C:\Users\runneradmin\AppData\Local\Temp\pip-install-e4qjtaxe\wxpython\build\waf\3.9\x64\release\config.log)
    Command '"c:\hostedtoolcache\windows\python\3.9.0\x64\python.exe" C:\Users\runneradmin\AppData\Local\Temp\pip-install-e4qjtaxe\wxpython\bin\waf-2.0.19 --msvc_arch=x64 --python="c:\hostedtoolcache\windows\python\3.9.0\x64\python.exe" --out=build/waf/3.9/x64/release configure build ' failed with exit code 1.
`

**Repro steps**  

1. Have the following steps in a workflow action using Windows runner:

`
    - name: Set up Python
      uses: actions/setup-python@v2
    - name: Install dependencies
      run:  pip install -r requirements.txt
`

**Comment by LeonidLapshin** [comment]
Hey, @robbyb67!
I guess that problem in somehow Python version-related, I'll check it, for workaround you can set Python version to 3.8 or 3.7 for this task, if possible
```
  my_job:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 
        uses: actions/setup-python@v2 
        with:
          python-version: "3.8"
      - run: pip install -r requirements.txt
```
Do you use wxPython with Python 3.9 locally?

**Comment by robbyb67** [comment]
I didn't catch that specifying python-version is that important.
Thx a lot for your help - everything is working as expected. :smile:

**Comment by LeonidLapshin** [comment]
Hi, @robbyb67 !
I'll close this issue, but if the problem persist, please feel free to reopen this one ;)
Thank you!
