### ISSUE TITLE
How to get the updates about the changes on Microsoft Hosted agent pools  in advance. is there a way ?

### ISSUE THREAD

**Issue by ReddyStuff** [actions/virtual-environments#2113]
**Question, Bug, or Feature?**:

**Feature:** 

As of today, we are able to see the latest pre-installed software list of Microsoft Hosted agent pool info through the public documentation, inturn which is navigating to respective github docs.

Softwares on MS hosted agent pool: 
https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops&tabs=yaml#software

At times when the minor version of any pre-installed version is updated there, the pipelines are getting failed. Identifying these changes is a tedious task during troubleshooting. Feature requests are as below

**Feature Request**

**Point 1:**  If there is a heads up on the changes on any pre-installed software on Microsoft hosted agent pool, will give a better understanding on up-changes.

**Point 2:**  If the above point is feasible, let us know how can we get notified/subscribe to newsletters/features. 
 

**Virtual environments affected**
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Comment by LeonidLapshin** [comment]
Hey, @ReddyStuff !
Usually we try to get the latest version possible for the most of software installed and you can track software versions changes via subscription on repository releases. When the image update process starts, we create the pre-release package and when it finishes - the release package.

**Comment by krokofant** [comment]
@LeonidLapshin With what frequency do you rollout the new releases? Looking at the releases now _Windows Server 2019 (20201116 update)_ is released, and earlier versions as well. But the latest rollout progress shows the latest 2019 image as 20201021.0.

I'm using win19/20201108.1 now but the MS hosted agents seems older.

**Comment by LeonidLapshin** [comment]
Hey, @krokofant !
The image information on banners is broken and will be fixed soon :) So the releases subscription is still the best option to understand which changes will be applied in the next release :)

**Comment by LeonidLapshin** [comment]
Hi, @krokofant !
Banners have been fixed :)

**Comment by LeonidLapshin** [comment]
Hi, @krokofant @ReddyStuff 
I hope that the release subscription is suitable option. I'll close the issue, but please feel free to reopen it if you have any questions
Thank you!
