### ISSUE TITLE
Add PostgreSQL server

### ISSUE THREAD

**Issue by zombiezen** [actions/virtual-environments#212]
**Tool information**
- Tool name: PostgreSQL
- Add or update? Add
- Desired version: 11
- Approximate size: 
- If this is an add request:
  - Brief description of tool: Open source database
  - URL for tool's homepage: https://www.postgresql.org/

**Area for Triage**: Databases

**Question, Bug, or Feature?**: Feature

**Virtual environments affected**
- [X] macOS 10.15
- [X] Ubuntu 16.04 LTS
- [X] Ubuntu 18.04 LTS
- [X] Windows Server 2016 R2
- [X] Windows Server 2019

**Can this tool be installed during the build?**
Yes, using a step like this on Ubuntu 18.04:

```yaml
    - name: Install PostgreSQL
      run: |
        echo 'deb http://apt.postgresql.org/pub/repos/apt/ bionic-pgdg main' | sudo tee /etc/apt/sources.list.d/pgdg.list
        sudo curl -fsSL https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends postgresql-11
        echo '::add-path::/usr/lib/postgresql/11/bin'
```

This takes roughly 75 seconds to execute.

**Are you willing to submit a PR?**
Depending on difficulty. I took a cursory look at the MySQL script and it has more steps than I would expect.

**Comment by mprins** [comment]
Should have the Postgis extension installed as well

**Comment by mprins** [comment]
Why would this be limited to only linux? 
Note there is a choco package https://chocolatey.org/packages/postgresql11

**Comment by zombiezen** [comment]
> Why would this be limited to only linux?

Probably shouldn't be. My needs are Linux-only, so that's all I checked. I'll update the description.

**Comment by mprins** [comment]
@github-actions I cannot remove the label

**Comment by alepauly** [comment]
Thanks for the suggestion @zombiezen, just took us a bit to get here 😨. We'll look into it and confirm there are no issues adding it.

**Comment by Darleev** [comment]
@zombiezen We have added PostgreSQL serve to the image and it will be rolled out next week.
In case of any questions, please let us know, we will be glad to assist you further.

**Comment by Darleev** [comment]
@zombiezen We have implemented PostgreSQL server installation on out agents. Could you please verify on your side?

**Comment by Darleev** [comment]
I'm going to close the issue until further clarifications.
In case of any questions feel free to contact us.
