### ISSUE TITLE
Run code analysis throwing many errors in azure devops build solution task is ran

### ISSUE THREAD

**Issue by adityaakella123** [actions/virtual-environments#2124]
**Description:**
When pipeline is running on Microsoft hosted agent with agent specification : **windows-2019**, getting many errors when run code analysis is running. Task is getting failed with number of errors reported.

It was fine before but seeing this issue from last few days

I am not getting this issue when running with agent specification : **vs2017-win2016**.

Please find the sample log screenshot and let me know if more details needed. 

![log screenshot](https://user-images.githubusercontent.com/65285851/100117959-5c671480-2e9b-11eb-8b95-a2fd8435476f.jpg)

**Comment by maxim-lobanov** [comment]
@adityaakella123 , unfortunately, it is known issue with Visual Studio 16.8 (I guess you will catch the same errors locally if update VS on local box).
Could you please try workarounds provided by the link and let us know if it helps you?
https://developercommunity2.visualstudio.com/t/After-168-update-getting-lot-of-code-an/1251574?preview=true#T-N1255914
