### ISSUE TITLE
[Ubuntu] Improvement - CMake - Install the latest version always

### ISSUE THREAD

**Issue by maxim-lobanov** [actions/virtual-environments#2129]
**Tool information**
- Tool name: CMake

Currently, version of Cmake for Ubuntu is hardcoded and we have to update it manually like https://github.com/actions/virtual-environments/pull/2126
We need to rework it to install the latest version always like we do on Windows and macOS.

**Question, Bug, or Feature?**:
Improvement

**Virtual environments affected**
- [x] Ubuntu 16.04
- [x] Ubuntu 18.04
- [x] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Can this tool be installed during the build?**

**Tool installation time in runtime**

**Are you willing to submit a PR?**

**Comment by EwoutH** [comment]
@nikita-bykov Sorry, I didn't see you got already assigned to this issue. You can use my proposed solution in #2131 if you want.

**Comment by nikita-bykov** [comment]
That's all right @EwoutH. Thank you for contribution!
