### ISSUE TITLE
github_feed_token is no longer needed for Windows build

### ISSUE THREAD

**Issue by snnn** [actions/virtual-environments#2132]
**Description**  
The line 207 in https://github.com/actions/virtual-environments/blob/main/helpers/GenerateResourcesAndImage.ps1 should be removed.

**Area for Triage**:  
Packages

**Question, Bug, or Feature?**:  
Bug

**Virtual environments affected**  

- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Expected behavior**  
A description of what you expected to happen.

**Actual behavior**  
A description of what is actually happening.

**Repro steps**

**Comment by maxim-lobanov** [comment]
That makes sense,
we just need to wait for these PRs:
- https://github.com/actions/virtual-environments/pull/2085
- https://github.com/actions/virtual-environments/pull/2084

They will remove the same variable for Ubuntu and macOS. Currently, this script is used for all platforms.
