### ISSUE TITLE
Update Pester v5.1

### ISSUE THREAD

**Issue by alagoutte** [actions/virtual-environments#2134]
**Tool information**
- Tool name: Pester
- Tool license: 
- Add or update? Update
- Desired version: 5.1
- Approximate size: < 1Mb ?

**Area for Triage**:

**Question, Bug, or Feature?**:

**Virtual environments affected**
- [X] Ubuntu 16.04
- [X] Ubuntu 18.04
- [X] Ubuntu 20.04
- [X] macOS 10.15
- [x] macOS 11.0
- [X] Windows Server 2016 R2
- [x] Windows Server 2019

**Comment by LeonidLapshin** [comment]
Hi, @alagoutte !
Pester will be updated on the next week :)

**Comment by alagoutte** [comment]
> Hi, @alagoutte !
> Pester will be updated on the next week :)

Thanks, it is automatically ? 
there is no information about release version on linux README...

**Comment by maxim-lobanov** [comment]
@alagoutte , sorry for confusion.
As for the Windows and MacOS images, Pester is already installed and will be updated to 5.1 with next image-generation (approximately end of next week). We always install latest version so no actions are required here.
As for the Ubuntu images, there is no Pester on this image yet. We will add Pester to Ubuntu but it could take some time so I suggest to install it in runtime for now. Moved work item to backlog.

Just a recommendation, I suggest always use `Install-Module <> -MinimumVersion <> -MaximumVersion` even if module is available on image. If module is already installed and version satisfies it will take no time to run.
On images, we always install latest version of package, so if latest version of module contains breaking changes and you rely on pre-installed version, you can be broken (for example, Pester 5.x brought a lot of breaking changes when was just released).

**Comment by alagoutte** [comment]
Thanks @maxim-lobanov for explication !

but Pester is already available on ubuntu image, i using for try my CI for a powershell module (but i need Pester 5.1)
https://github.com/alagoutte/PowerFGT/runs/1436217916?check_suite_focus=true

**Comment by maxim-lobanov** [comment]
You are right. Not sure why it is not reflected in documentation. We will update it.

**Comment by Darleev** [comment]
Hello,
Documentation was updated in the scope of linked PR. Information about PowerShell tools will be available after the next image rollout.
I will keep you informed.

**Comment by Darleev** [comment]
Hello @alagoutte,
We have updated [the documentation](https://github.com/actions/virtual-environments/blob/releases/ubuntu18/20201210/images/linux/Ubuntu1804-README.md#powershell-modules) for Ubuntu. Currently, information about pre-installed PowerShell modules is publicly available.

In case of any questions do not hesitate to contact us.

**Comment by alagoutte** [comment]
Thanks Guys !
