### ISSUE TITLE
libgd-dev can not be installed

### ISSUE THREAD

**Issue by joto** [actions/virtual-environments#2139]
**Description**  
libgd-dev can not be installed due to version mismatch

**Area for Triage**:  

**Question, Bug, or Feature?**:  
Bug

**Virtual environments affected**  
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [x] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Expected behavior**  
I expected libgd-dev to be installed.

**Actual behavior**  
Error message: The following packages have unmet dependencies:
 libgd-dev : Depends: libgd3 (= 2.2.5-5.2ubuntu2) but 2.3.0-2+ubuntu20.04.1+deb.sury.org+1 is to be installed

**Repro steps**  
Run these in workflow:
```
sudo apt-get update -q
sudo apt-get install -yq libgd-dev 
```

Example run: https://github.com/taginfo/taginfo-tools/runs/1459251139?check_suite_focus=true

**Comment by LeonidLapshin** [comment]
Hi, @joto !
These packages are installed by php 7.4, you can use this workaround:
```
sudo apt-get remove libgd3 
sudo apt-get install -yq libgd-dev
```
Thank you!

**Comment by joto** [comment]
Thanks for the quick reply. The workaround works for me.

**Comment by LeonidLapshin** [comment]
Hi, @joto!
I'll close the issue for now, but if the problem persist, please feel free to reopen the ticket.
Thank you!

**Comment by vergoh** [comment]
The suggested workaround stopped working within the last 24 hours:

```
apt-get remove libgd3
Reading package lists...
Building dependency tree...
Reading state information...
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 nginx : Depends: nginx-core (< 1.18.0-0ubuntu1.1~) but it is not going to be installed or
                  nginx-full (< 1.18.0-0ubuntu1.1~) but it is not going to be installed or
                  nginx-light (< 1.18.0-0ubuntu1.1~) but it is not going to be installed or
                  nginx-extras (< 1.18.0-0ubuntu1.1~) but it is not going to be installed
         Depends: nginx-core (>= 1.18.0-0ubuntu1) but it is not going to be installed or
                  nginx-full (>= 1.18.0-0ubuntu1) but it is not going to be installed or
                  nginx-light (>= 1.18.0-0ubuntu1) but it is not going to be installed or
                  nginx-extras (>= 1.18.0-0ubuntu1) but it is not going to be installed
E: Error, pkgProblemResolver::Resolve generated breaks, this may be caused by held packages.
```

Example run: https://github.com/vergoh/vnstat/runs/1834018377?check_suite_focus=true

**Comment by miketimofeev** [comment]
hi @vergoh! Since nginx package depends on libgd3 it needs to be removed as well.
```
sudo apt-get remove nginx
sudo apt-get remove libgd3
sudo apt-get install -yq libgd-dev
```

**Comment by mohawk2** [comment]
This is happening again as of yesterday, with the GHA config not having changed at all (https://github.com/PDLPorters/pdl/runs/7473608493?check_suite_focus=true):

```
  The following packages have unmet dependencies:
   libgd-dev : Depends: libgd3 (= 2.2.5-5.2ubuntu2.1) but 2.3.3-5+ubuntu20.04.1+deb.sury.org+1 is to be installed
  E: Unable to correct problems, you have held broken packages.
```
