### ISSUE TITLE
Update document to reflect Clang 12 on macOS 10.15 and 11.0

### ISSUE THREAD

**Issue by tetrachrome** [actions/virtual-environments#2143]
**Description**  
The documentations for [macOS-10.15](https://github.com/actions/virtual-environments/blob/main/images/macos/macos-10.15-Readme.md) and [macOS-11.0](https://github.com/actions/virtual-environments/blob/main/images/macos/macos-11.0-Readme.md) specify the Clang/LLVM version to be `11.0.0`.

However, I noticed that the Clang version (AppleClang) has been updated to `Apple clang version 12.0.0 (clang-1200.0.32.2)` on both environments.

Here's what `clang --version` says on one of my macOS-10.15 runs:

```
Run clang --version
Apple clang version 12.0.0 (clang-1200.0.32.2)
Target: x86_64-apple-darwin19.6.0
Thread model: posix
InstalledDir: /Applications/Xcode_12.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

Do the documentations need to change to reflect that?

**Area for Triage**:  

**Question, Bug, or Feature?**:  
Bug

**Virtual environments affected**  
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [x] macOS 10.15
- [x] macOS 11.0
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Expected behavior**  
Should say Clang/LLVM `12.0.0`?

**Actual behavior**  
Currently it says Clang/LLVM `12.0.0`?

**Repro steps** 
Already said above.

**Comment by LeonidLapshin** [comment]
Hi, @tetrachrome !
There are 2 clang installations: 
```
Apple clang version 12.0.0 (clang-1200.0.32.2)
Target: x86_64-apple-darwin19.6.0
Thread model: posix
InstalledDir: /Applications/Xcode_12.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
clang version 11.0.0
Target: x86_64-apple-darwin19.6.0
Thread model: posix
InstalledDir: /usr/local/opt/llvm/bin
```
and only one is mentioned in docs. We definitely should add information about the second one. I'll leave this issue opened until we add this section to docs. 
Thank you!

**Comment by tetrachrome** [comment]
> Hi, @tetrachrome !
> There are 2 clang installations:
> 
> ```
> Apple clang version 12.0.0 (clang-1200.0.32.2)
> Target: x86_64-apple-darwin19.6.0
> Thread model: posix
> InstalledDir: /Applications/Xcode_12.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
> clang version 11.0.0
> Target: x86_64-apple-darwin19.6.0
> Thread model: posix
> InstalledDir: /usr/local/opt/llvm/bin
> ```
> 
> and only one is mentioned in docs. We definitely should add information about the second one. I'll leave this issue opened until we add this section to docs.
> Thank you!

Ah, I see. Thanks for clarifying. I certainly did not know that. :-)

**Comment by LeonidLapshin** [comment]
Hey, @tetrachrome !
Software report fixed and will show correct information about both Clang versions with next VM rollout.
Thank you!

**Comment by ospfranco** [comment]
I can see on the [latest versions](https://github.com/actions/runner-images/blob/main/images/macos/macos-14-arm64-Readme.md) there are two clang versions. I there anyway to set the latest as the default one?

I have a rust app that is using clang and fails to compile if not using the latest version.
