### ISSUE TITLE
Windows runners are currently affected by numpy issue: https://tinyurl.com/y3dm3h86

### ISSUE THREAD

**Issue by robbyb67** [actions/virtual-environments#2148]
**Description**  
Windows runners are currently affected by the following Bug:
RuntimeError: The current Numpy installation ('.....') fails to pass a sanity check due to a bug in the windows runtime. See this issue for more information: https://tinyurl.com/y3dm3h86
So it is not possible to create executables using pyinstaller.

**Area for Triage**:  
Python

**Question, Bug, or Feature?**:  
Bug

**Virtual environments affected**  
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11.0
- [x] Windows Server 2016 R2
- [x] Windows Server 2019

**Expected behavior**  
Executable generated by pyinstaller able to execute

**Actual behavior**  
Executable generated by pyinstaller fails to start with following error:
```
File "numpy\__init__.py", line 302, in _win_os_check
RuntimeError: The current Numpy installation ('.....\\AppData\\Local\\Temp\\_MEI71482\\numpy\\__init__.pyc') fails to pass a sanity check due to a bug in the windows runtime. See this issue for more information: https://tinyurl.com/y3dm3h86
```

**Repro steps**  
Have the following steps in your workfile

1. 
```
    - name: Install dependencies
      run: |
        pip install pyinstaller
```

2. 
```
    - name: Build pyinstaller
      run: |
        pyinstaller --clean -F <app using numpy>.py
```

**Comment by dmitry-shibanov** [comment]
Hello @robbyb67. I have found the issue in this [link](https://developercommunity.visualstudio.com/content/problem/1207405/fmod-after-an-update-to-windows-2004-is-causing-a.html) and as Steve Wishnousky [MSFT] mentioned it’s the [issue](https://developercommunity.visualstudio.com/comments/1243113/view.html) with work of numpy in windows itself. You can try the following approaches to workaround:
 - install pip with 1.19.3 version: `pip install numpy==1.19.3`
 - try to switch to another python.

**Comment by dmitry-shibanov** [comment]
Hello @robbyb67. Do you have any updates on it?

**Comment by dmitry-shibanov** [comment]
Hello @robbyb67 , I am closing this issue, because it's external issue not related directly to GitHub Runners . If you have any concerns feel free to reopen the issue.

**Comment by robbyb67** [comment]
Hi Dmitry -
Sry for answering late - I've tried the things you've mentioned:
* numpy version pinning does not compile/link on the runner
* tried both original numpy/version pinned numpy with other python without success

In my eyes this could be solved if conda python would be available on the runner:

> 
> Solution by Milos Korenciak   04/11 um 09:31
> avatar image
> Use conda - it ships its own ucrtbase.dll in its portable isolated venv (applies for Win only). When you activate it, you will use that sane version of ucrtbase.dll .

It's in the comments of your 2nd link ...

**Comment by maxim-lobanov** [comment]
We already install Miniconda 4.9.2 on Windows images
