### ISSUE TITLE
Add wasmtime

### ISSUE THREAD

**Issue by jhpratt** [actions/virtual-environments#215]
**Tool information**
- Tool name: wasmtime
- Add or update? Add
- Desired version: Latest (currently v0.8.0)
- Approximate size: 
- If this is an add request:
  - Brief description of tool: Wasmtime is a WebAssembly runtime.
  - URL for tool's homepage: [wasmtime.dev](https://wasmtime.dev/)

**Area for Triage**: Scripting and command line, Packages

**Question, Bug, or Feature?**: Feature

**Virtual environments affected**
- [x] macOS 10.15
- [x] Ubuntu 16.04 LTS
- [x] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

<sup>(unsure on Windows Server)</sup>

**Can this tool be installed during the build?**
Yes, using the install script provided on its website. It doesn't take terribly long, as there are pre-built binaries for certain systems.

**Are you willing to submit a PR?**
If someone can show me what needs to be changed, I'd absolutely submit a PR.

---

My use case is that I have a pre-compiled binary, but it would be best to avoid guarantees of the system architecture. I can do this by targeting wasmtime. The alternative is to build the binary new each time, though that's quite wasteful.

**Comment by jhpratt** [comment]
Just checking one of the situations I'm using this. It only took 2 seconds to install, so it's far from a hassle. However, the command `wasmtime` can't be used until the terminal is reloaded, so it's necessary to give the path to the script.

**Comment by syrusakbary** [comment]
Hi @jhpratt, have you tried [Wasmer](https://wasmer.io)? I think that would be a great addition to GH actions as well!

**Comment by jhpratt** [comment]
@syrusakbary I've heard of it but never used it. It seems to have an identical use case to this, so adding it wouldn't be a bad idea.

**Comment by syrusakbary** [comment]
I'll be creating a PR soon :)

**Comment by alepauly** [comment]
@jhpratt I think this is better suited for a setup style Action that does that install considering it's pretty small instead of baking it into the environment.
