### ISSUE TITLE
[macOS] Add Docker to macOS

### ISSUE THREAD

**Issue by karimhm** [actions/virtual-environments#2150]
**Tool information**
- Tool name: **Docker**
- Tool license: **Enterprise**
- Add or update? **Add**
- Desired version: **Any**
- Approximate size: **1.7 GB**
- If this is an add request:
  - Brief description of tool: Docker is an application that run containerized applications
  - URL for tool's homepage: https://hub.docker.com/editions/community/docker-desktop-ent

**Virtual environments affected**
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [x] macOS 10.15
- [x] macOS 11.0
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Tool installation time in runtime**
Approximately 10 minutes.

**Are you willing to submit a PR?**
No.

I am aware about the previous discussion:
> Unfortuately the docker community licensing is such that we are not able to install the docker for mac on our hosted runners.  We have had some discussions with Docker about doing this but they have held firm on their request that using Docker on a service requires an enterprise license and docker enterprise is not at all supported on macOS.
> 
> For Windows Microsoft holds the license for Docker Enterprise on Windows so we do not have any issues there and for Linux we use a specific build of Docker for Linux that is built and maintained by Azure.

**But things changed and Docker offer an enterprise edition now**

According to Docker:
> Docker Desktop Enterprise for Mac is an easy-to-install desktop app for building, debugging, and testing Dockerized apps on a Mac.

**Comment by maxim-lobanov** [comment]
@karimhm , thank you for raising feature request.
As I can see, Docker Desktop Enterprise is distributed with [EULA license](https://hub.docker.com/editions/community/docker-desktop-ent) too. As far as I know, it doesn't allow us to install it since CI machine is not the end user in this chain.
> By downloading this, you agree to the terms of the Docker Software End User License Agreement and the Docker Data Processing Agreement (DPA).

@alepauly @chrispat do you have any thoughts about it? Should we engage legal team to take a look deeper?
On Windows, we install Docker via https://github.com/OneGet/MicrosoftDockerProvider but not sure how we deal with license here.

**Comment by miketimofeev** [comment]
@karimhm you can try [this guide](https://medium.com/crowdbotics/a-complete-one-by-one-guide-to-install-docker-on-your-mac-os-using-homebrew-e818eb4cfc3) to install docker by yourself. Virtualbox is already installed on the images. Other software will be installed in the runtime.
In the meantime, as @maxim-lobanov said we'll investigate license restrictions a bit deeper.

**Comment by chrispat** [comment]
Docker Desktop for Mac is an end user tool for developing with docker on your Mac.  To my knowledge the license restriction are still in place because Docker Desktop for Mac contains closed source software that is licensed independently from the core docker engine and CLIs.  As for Windows we that license is offered by Microsoft and we have been given clearance to use it.

**Comment by karimhm** [comment]
> Docker Desktop for Mac is an end user tool for developing with docker on your Mac. To my knowledge the license restriction are still in place because Docker Desktop for Mac contains closed source software that is licensed independently from the core docker engine and CLIs. As for Windows we that license is offered by Microsoft and we have been given clearance to use it.

😭

**Comment by maxim-lobanov** [comment]
I am closing the issue since we can't bake this tool into the image due to license issue. Hope something will be changed in future.

**Comment by mvgijssel** [comment]
Solved this using https://github.com/abiosoft/colima (example: https://github.com/mvgijssel/setup/pull/103/commits/dab0918a59d8e303ee8de0a931379b8f1d5aeea9). 

Would it be possible to bake a tool like this in the macOS base image? 🤔.

**Comment by miketimofeev** [comment]
@mvgijssel how long does it take to install the tool in runtime? Looks like it's really popular so we can consider adding it if the installation time in runtime is long enough. Feel free to create a new issue using the Tool request template

**Comment by mvgijssel** [comment]
> @mvgijssel how long does it take to install the tool in runtime? Looks like it's really popular so we can consider adding it if the installation time in runtime is long enough. Feel free to create a new issue using the Tool request template

Looking at the last two GitHub action runs, it takes about ~1 minute to run

```shell
brew install docker colima
```

Personally, I think saving 1 minute on each execution would be a big win for me 😍.

**Comment by mvgijssel** [comment]
Submitted colima as a tool request! https://github.com/actions/runner-images/issues/6216
