### ISSUE TITLE
Ubuntu 20.04 `apt-get update` fails

### ISSUE THREAD

**Issue by jralls** [actions/virtual-environments#2156]
**Description**  
The Ubuntu 20.04 VM is unable to complete `apt-get update`.
**Area for Triage**:  

Packages
**Question, Bug, or Feature?**:  

Bug
**Virtual environments affected**  
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ x] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Expected behavior**  
A workflow containing `apt-get upgrade` to succeed.
**Actual behavior**  
The workflow fails:
```
Trying to migrate /boot/efi into esp config
Installing grub to /boot/efi.
Installing for x86_64-efi platform.
grub-install: warning: Internal error.
grub-install: error: failed to register the EFI boot entry: Operation not permitted.
dpkg: error processing package grub-efi-amd64-signed (--configure):
 installed grub-efi-amd64-signed package post-installation script subprocess returned error exit status 1
Processing triggers for systemd (245.4-4ubuntu3.3) ...
Processing triggers for man-db (2.9.1-1) ...
Processing triggers for dbus (1.12.16-2ubuntu2.1) ...
Processing triggers for install-info (6.7.0.dfsg.2-5) ...
Processing triggers for mime-support (3.64ubuntu1) ...
Processing triggers for initramfs-tools (0.136ubuntu6.3) ...
update-initramfs: Generating /boot/initrd.img-5.4.0-1031-azure
Processing triggers for hicolor-icon-theme (0.17-2) ...
Processing triggers for libc-bin (2.31-0ubuntu9.1) ...
Errors were encountered while processing:
 grub-efi-amd64-signed
E: Sub-process /usr/bin/dpkg returned an error code (1)
Error: Process completed with exit code 100.
```
**Repro steps**  
An example run may be found at https://github.com/Gnucash/gnucash/runs/1470216645
Create and run a workflow using ubuntu-20.04 that includes `sudo apt-get upgrade`

**Comment by al-cheb** [comment]
Duplicate: https://github.com/actions/virtual-environments/issues/1605
