### ISSUE TITLE
[macOS] Big Sur Runner Fails to build Ruby Gems

### ISSUE THREAD

**Issue by carlocab** [actions/virtual-environments#2166]
**Description**  
Some ruby gems don't build on the Big Sur runners.

**Area for Triage**:  
Apple

**Question, Bug, or Feature?**:  
Bug

**Virtual environments affected**  
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [x] macOS 11.0
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Expected behavior**  
Ruby gems should build.

**Actual behavior**  
They don't.

**Repro steps**  

Apologies in advance if this isn't a MWE. I'm new to GH Actions and Homebrew's workflows.

Run this workflow: https://github.com/carlocab/homebrew-personal/blob/main/.github/workflows/tests.yml on the `macos-11.0` runner by creating a pull request that adds or modifies a Homebrew formula. [1] [2]

The `brew test-bot --only-setup` step will produce a long series of errors, starting with:

```
Installing sorbet-static 0.5.6111 (universal-darwin-20)
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

current directory:
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/byebug-11.1.3/ext/byebug
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby -
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0 -r
./siteconf20201130-2372-1qwyiud.rb extconf.rb
creating Makefile

current directory:
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/byebug-11.1.3/ext/byebug
make "DESTDIR=" clean

current directory:
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/byebug-11.1.3/ext/byebug
make "DESTDIR="
make: *** No rule to make target
`/Applications/Xcode_11.7.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/include/ruby-2.6.0/universal-darwin20/ruby/config.h',
needed by `breakpoint.o'.  Stop.

make failed, exit code 2
```

See https://github.com/carlocab/homebrew-personal/runs/1471591712?check_suite_focus=true

Also attaching build logs: 
[6_Run brew test-bot --only-setup.txt](https://github.com/actions/virtual-environments/files/5617121/6_Run.brew.test-bot.--only-setup.txt)

[1] If you don't have your own tap, you can use any of the ones here: https://github.com/carlocab/homebrew-personal/tree/main/Formula

[2] This line will need to be modified: 

https://github.com/carlocab/homebrew-personal/blob/515198c87057e33b23faa14109a64e3188966882/.github/workflows/tests.yml#L10

**Comment by miketimofeev** [comment]
Hi @carlocab!
macOS-11 runners are still in preview state so that some software may not working properly.
We'll take a look at what's wrong with the gems.

**Comment by carlocab** [comment]
Not sure what's changed (maybe the default Xcode?) since then, but I don't get this error anymore.

Should I close this?

**Comment by maxim-lobanov** [comment]
@carlocab , I see this warning in logs:
```
Warning: Your Xcode (11.7 => /Applications/Xcode_11.7.app/Contents/Developer) is too outdated.
Please update to Xcode 12.2 (or delete it).
```
Looks like, recently, some homebrew formula was updated and started require Xcode 12.2.
Yesterday, we have updated images and set Xcode 12.2 as default Xcode.

I guess this issue could be fixed by manual switching of Xcode to 12.2 before it become default

**Comment by carlocab** [comment]
I saw that warning too, but I believed it was unrelated to the Ruby issue.

I'll experiment with switching Xcode back to the old one and see if that brings back the problem.

**Comment by carlocab** [comment]
Haven't found the time to play around with this, but just thought to leave a note that the following may be related:

https://github.com/Homebrew/homebrew-core/pull/66290
https://github.com/Homebrew/brew/issues/9410

**Comment by maxim-lobanov** [comment]
@carlocab , I see that this issue was also fixed on brew side. Is it still a problem for you?

**Comment by carlocab** [comment]
No, it seems to have been fixed by switching to Xcode 12. 

I've been ok with closing this for a while now; I just wasn't sure if your team was still interested in investigating it.
