### ISSUE TITLE
Add aws-iam-authenticator

### ISSUE THREAD

**Issue by chenrui333** [actions/virtual-environments#2168]
**Tool information**
- Tool name: aws-iam-authenticator
- Tool license: Apache-2.0
- Add or update? Add
- Desired version: 0.5.2
- Approximate size: 41MB
- If this is an add request:
  - Brief description of tool: help authenticate the IAM access to EKS clsuter
  - URL for tool's homepage: https://docs.aws.amazon.com/eks/latest/userguide/managing-auth.html
  - Provide a basic test case to validate the tool's functionality: See code in [here](https://github.com/Homebrew/homebrew-core/blob/master/Formula/aws-iam-authenticator.rb#L32-L41)

**Area for Triage**:
Area: Scripting and command line

**Question, Bug, or Feature?**:
Feature

**Virtual environments affected**
- [x] Ubuntu 16.04
- [x] Ubuntu 18.04
- [x] Ubuntu 20.04
- [x] macOS 10.15
- [x] macOS 11.0
- [] Windows Server 2016 R2
- [] Windows Server 2019

**Can this tool be installed during the build?**
Yes, download the binary.

**Tool installation time in runtime**
few seconds (as simply download the binary)

**Are you willing to submit a PR?**
Yes, absolutely.

**Comment by miketimofeev** [comment]
@chenrui333 thanks for your contribution! I've left a few comments in the PR.

**Comment by miketimofeev** [comment]
@chenrui333 I'm going to close the issue since there is no progress in PR for 2 months. Please contact us when you ready to create a new PR.
Thank you!
