### ISSUE TITLE
Add Kotlin/Native Compiler

### ISSUE THREAD

**Issue by Sonicskater** [actions/virtual-environments#2172]
**Tool information**
- Tool name: Kotlin/Native
- Tool license: Apache 2.0
- Add or update? Add
- Desired version: 1.4.20
- Approximate size: ~590 MB
- If this is an add request:
  - Brief description of tool: It compiles Kotlin code to a native binary. Our usecase is for Kotlin Multiplatform development, compiling the iOS version of the app. 
  - URL for tool's homepage: https://github.com/JetBrains/kotlin-native
  - Provide a basic test case to validate the tool's functionality: Not mine, but here is a sample project with the same requirements as our code. It should be able to compile this sample with no errors: https://github.com/JetBrains/kotlin-native/tree/master/samples/calculator

**Area for Triage**:
Apple

**Question, Bug, or Feature?**:
"Feature"

**Virtual environments affected**
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [x] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Can this tool be installed during the build?**
Kotlin/Native projects will install it if its missing

**Tool installation time in runtime**
~4-6 minutes

**Are you willing to submit a PR?**
I can look into it, but unsure what it entails at this time.

**Comment by miketimofeev** [comment]
Hi @Sonicskater!
Could you please update the title? It's from the template at the moment.

**Comment by Sonicskater** [comment]
> Hi @Sonicskater!
> Could you please update the title? It's from the template at the moment.

Sorry about that, done!

**Comment by miketimofeev** [comment]
@Sonicskater Have you tried kotlin-native installation via homebrew? Is it enough for your needs? It takes about 45 seconds to install in runtime.
`brew install --cask kotlin-native`

**Comment by Sonicskater** [comment]
@miketimofeev Ok I'll give that a shot, I had been letting gradle install it + the required clang and linker versions as part of the build script, I'll let you know.

**Comment by Sonicskater** [comment]
Unfortunately, the kotlin gradle plugin will not use kotlinc-native from path as far as I can tell, so while brew is faster, I can't make it useful without changing our product config, unless I can get that cask installed to /Users/runner/.konan, as that's where it expects the tools to be installed. I might be able to change that location, but kotlin/native doesn't have any docs that i can find to help. There is also the problem that we need a specific version of Clang installed to that location as well, which gradle also fetches automatically, but is another ~350mb of download, and isn't included with this cask. I tried caching the folder with azure, but that doesn't seem optimized for caching downloads as it takes longer to fetch from there than it does to just do it normally.

I could try manually installing the binaries to the konan folder, but i'm not sure if that's an acceptable method for integration into the image.

I'm not super experienced with macOS development, I'm a windows/android dev but I'm the only one who knows CI/CD tools on our local team so I'm stuck doing the fiddling, hopefully that's not too annoying for you guys.

**Comment by maxim-lobanov** [comment]
@Sonicskater , if we install kotlin/native to images, we prefer to follow recommended installation approach: installing using brew to default locations. This way we will be sure that it will work for the most of customers by default.

If you confirm that that brew installation (`brew install --cask kotlin-native`) works for you, we will consider baking it into the image.

**Comment by Sonicskater** [comment]
Alright, I'll mess with it further, I'll try using symlinks to get it to work, or changing the target directory. But that would likely need to be documented, kotlin-native gradle plugin expects them to be in the konan directory by default so installing them anywhere else would not be expected by developers. I think the preferred method would be to use a different installation method, as brew does not install it the way that jetbrains seemingly intends it to be used for large projects. (Those using a build system). Maybe its just not feasible at this time.

**Comment by Sonicskater** [comment]
My proposal would be to download the mac release tar.gz from kotlin natives release stream (i.e. GitHub releases), and unzip it to ~/.konan. That would mirror what the default toolchain does.

**Comment by fwilhe2** [comment]
Not a solution, but maybe my [setup-kotlin](https://github.com/fwilhe2/setup-kotlin) action is a little bit more convenient as a workaround?

**Comment by maxim-lobanov** [comment]
Hello, after some internal discussion, we have decided to not pre-install this tool into the images. Please consider using `setup-kotlin` action to install in runtime
