### ISSUE TITLE
Add gfortran-10 (to macOS)

### ISSUE THREAD

**Issue by mathomp4** [actions/virtual-environments#2176]
**Tool information**
- Tool name: gfortran-10
- Tool license: GPL
- Add or update? Add
- Desired version: 10.2.0
- Approximate size: 
- If this is an add request:
  - Brief description of tool: GNU Fortran Compiler
  - URL for tool's homepage: https://gcc.gnu.org/

**Area for Triage**:

Packages (??)

**Question, Bug, or Feature?**:

Feature. 

This is similar to #1796 but for macOS

**Virtual environments affected**
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [X] macOS 10.15
- [X] macOS 11.0
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Can this tool be installed during the build?**
Yes (with brew)

**Tool installation time in runtime**
2-3 minutes? I think it's a brew...bottle? 

**Are you willing to submit a PR?**
~Yes. I think I see how to do it (looking at https://github.com/actions/virtual-environments/pull/2074/files)~ Whoops. I just read [CONTRIBUTING.md](https://github.com/actions/virtual-environments/blob/main/CONTRIBUTING.md). I guess I can't submit a PR for macOS?

**Comment by AlenaSviridenko** [comment]
Hi @mathomp4 , yeah, we still cannot accept contributions to macOS. We will add it to macOS by ourselves, I'll put on our TODO list. Thanks!

**Comment by mathomp4** [comment]
@AlenaSviridenko Thanks. I was pretty sure that adding:
```
echo "Installing GCC@10 using homebrew..."
brew install gcc@10
```
to `images/macos/provision/core/gcc.sh` was how I'd have done it. Does that sound about right? (I.e., for when I can contribute?)

**Comment by miketimofeev** [comment]
@mathomp4 looks like  `brew install --cask gfortran` should be enough. Could you please try it in runtime? Gfortran-10 will be available with `gfortran` alias after that

**Comment by mathomp4** [comment]
@miketimofeev Eeeee. That might be hard. I do not use `brew` to install compilers on my local macOS laptop because I'm paranoid (and old). I never want a stray `gcc` in my base PATH that isn't the system one and any fancy version has to come from an Lmod modulefile. So I build all my compilers by hand and in a special directory. I've been burned by brew with low-level things, so I tend to avoid it for those (I build MPI by hand as well). I can definitely tell you how to build it from source... 😄

**Comment by miketimofeev** [comment]
@mathomp4 PR has been merged! The next week is deployment freeze so that the new image will be deployed the week after.

**Comment by miketimofeev** [comment]
@mathomp4 the image has been finally deployed with gfotran-10 on board!
[GNU Fortran (Homebrew GCC 10.2.0) 10.2.0 - available by gfortran-10 alias](https://github.com/actions/virtual-environments/blob/main/images/macos/macos-10.15-Readme.md#language-and-runtime)
I'm going to close the issue, but please feel free to contact us if you have any concerns.
Thank you!
