### ISSUE TITLE
Github action couldn't start

### ISSUE THREAD

**Issue by jboo7** [actions/virtual-environments#2178]
**Description**  
Using ubuntu-latest action couldn't start. It was just saying "starting your workflow..."

**Area for Triage**:  
Containers

**Question, Bug, or Feature?**:  
Bug

**Virtual environments affected**  
- [ ] Ubuntu 16.04
- [x] Ubuntu 18.04
- [x] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Expected behavior**  
Action started.

**Actual behavior**  
Github Action doesn't start. Just a message which says starting your workflow...

**Repro steps**  
Try to start github action using run-on: ubuntu-latest

**Comment by jboo7** [comment]
![image](https://user-images.githubusercontent.com/16625501/100798870-7e750f80-3424-11eb-8b24-de4d8867e74a.png)

**Comment by jboo7** [comment]
![image](https://user-images.githubusercontent.com/16625501/100799413-4a4e1e80-3425-11eb-8a79-4a3a3512cc12.png)

**Comment by miketimofeev** [comment]
Hi @jboo7!
Thanks for reaching us. There was an incident 10 hours ago, which is resolved now.
https://www.githubstatus.com/incidents/sxthxvdlljk4
I'm going to close the issue, but please feel free to contact us if you have any concerns.
