### ISSUE TITLE
GitHub Actions has encountered an internal error when running your job.

### ISSUE THREAD

**Issue by gmlewis** [actions/virtual-environments#2179]
**Description**  
GitHub Actions has encountered an internal error when running your job:
* https://github.com/google/go-github/actions/runs/394351921
* https://github.com/google/go-github/actions/runs/394351139

**Area for Triage**:  
Go

**Question, Bug, or Feature?**:  
Bug

**Virtual environments affected**  
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [x] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Expected behavior**  
All tests should pass.

**Actual behavior**  
GitHub Actions has encountered an internal error when running your job.

**Repro steps**  
Submit or merge a PR to this repo: https://github.com/google/go-github
Two examples:
* https://github.com/google/go-github/actions/runs/394351921
* https://github.com/google/go-github/actions/runs/394351139

**Comment by miketimofeev** [comment]
Hi @gmlewis!
Thanks for reaching us. There was an incident 10 hours ago, which is resolved now.
https://www.githubstatus.com/incidents/sxthxvdlljk4
I'm going to close the issue, but please feel free to contact us if you have any concerns.

**Comment by MeghalBisht** [comment]
Hey @miketimofeev I encountered this today. 
OS - Ubuntu 20.04
https://github.com/fossasia/open-event-frontend/actions/runs/842359793

**Comment by wayne-o** [comment]
seems to be happening again

![image](https://user-images.githubusercontent.com/178060/118282687-74246a80-b4c6-11eb-904f-7362a5a1a6ef.png)

**Comment by mnegrean** [comment]
Also happened to me. Everything seems to be ok on the github status page except that it doesn't work:

![Screenshot from 2021-05-14 17-16-36](https://user-images.githubusercontent.com/8396921/118283608-37616f00-b4d8-11eb-836b-48d65cdae34b.png)

**Comment by LorenzoBettini** [comment]
Same for me... about an hour ago...

**Comment by paresy** [comment]
Same here. `GitHub Actions has encountered an internal error when running your job.`

**Comment by miketimofeev** [comment]
Hello, everyone!
We are aware of the issue and working on it at the moment

**Comment by byunguk** [comment]
Is it fixed? I'm still having the issue. Can you at least update the status? It shows `All Systems Operational` but it's not.
![Screen Shot 2021-05-14 at 7 54 06 AM](https://user-images.githubusercontent.com/16727541/118289041-cb581a00-b489-11eb-8654-7b90cb100a2f.png)

**Comment by wayne-o** [comment]
I see this now 
![image](https://user-images.githubusercontent.com/178060/118289256-0e87ac80-b4cd-11eb-8eaf-0d34fa3dbeb8.png)

**Comment by ydahal1** [comment]
oh wow !! O thought I was doing smth wrng

**Comment by wayne-o** [comment]
BACK IN THE GAME!

**Comment by LorenzoBettini** [comment]
Indeed

**Comment by izvolte** [comment]
Again :(

**Comment by MeghalBisht** [comment]
Again I face the same error https://github.com/fossasia/open-event-frontend/actions/runs/853410218

**Comment by polaris218** [comment]
Same here
https://github.com/AA-Design-Development/opticus-backend/actions/runs/853818511

**Comment by GorgeousPuree** [comment]
Same

**Comment by woctezuma** [comment]
> 
> 
> Same

Check https://www.githubstatus.com/

**Comment by GorgeousPuree** [comment]
> > Same
> 
> Check https://www.githubstatus.com/

thanks

**Comment by yujuchen-agoop** [comment]
I have the same error. But my repository is private, so I can't share here.

**Comment by lanctot** [comment]
Just a heads-up: I was encountering this yesterday along with others above, and then it got fixed. But it seems like it's happening again today: e.g. https://github.com/deepmind/open_spiel/actions/runs/856534139

**Comment by zog** [comment]
I still have the same issue, while the status page says everything is working :(
![image](https://user-images.githubusercontent.com/254393/119005904-29a46180-b990-11eb-8c52-6ba99ef3a379.png)

**Comment by woctezuma** [comment]
> I still have the same issue, while the status page says everything is working :(

![Degraded](https://i.imgur.com/DaccWSc.png)

![Status](https://i.imgur.com/oGb2zwr.png)

**Comment by jamiemkass** [comment]
I am having this issue for the first time today. The status says Github Actions is functional, but I am getting these exact errors for all OS. Any fixes in the works?

**Comment by wernich-vg** [comment]
Also having the same issue today. Any fixes?

**Comment by enis-j** [comment]
I'm also having issues with this today...

**Comment by WGillmer** [comment]
Having the same issue right now.

**Comment by pribanerjee** [comment]
Having the same issue right now

**Comment by EdStevenson-IT** [comment]
Just to add to the flames, I am also seeing this error 😂 🔥

**Comment by woctezuma** [comment]
![Pic](https://i.ibb.co/jv9WYfm/firefox-2022-03-22-12-45-34.png)

Reference: https://www.githubstatus.com/

**Comment by WGillmer** [comment]
Status is green now on the github status page, but jobs are still not running for me. Just stuck in "waiting for pending jobs", but there is no pending jobs in the workflow

**Comment by rubiatoEJ** [comment]
Same here, having this issue right now.

![image](https://user-images.githubusercontent.com/88638065/159601412-0fe9ee03-92f0-414f-9f1e-883333f7feb2.png)

**Comment by WGillmer** [comment]
and it's broken again. Seems to be a daily occurrence now, at more or less the same time.

**Comment by AmaliaGM** [comment]
Hello ! I'm having this issue today. Should I just wait?

**Comment by kieranajp** [comment]
Ditto - you're not alone @AmaliaGM :D

**Comment by hakrishi** [comment]
Hello, I've started having this issue today. Note that I am self hosting my Github Action.

**Comment by veryresto** [comment]
Hi, it seems to be happened again

**Comment by AmaliaGM** [comment]
Wait..we are more..🥺

Obtener Outlook para Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by walid-meurs** [comment]
![jOXvo-7i_400x400](https://user-images.githubusercontent.com/104774004/210764664-54791d97-9c8d-45c0-9893-fb90a1e3a4ff.jpg)

**Comment by abdulsamadCS** [comment]
Hi, it happened again!

**Comment by Armando-Cierra** [comment]
Yes, notifying it is happening again 😞

**Comment by gowelaine** [comment]
Hi, my action run into this today :(
```
GitHub Actions has encountered an internal error when running your job.
```

**Comment by muzakkirsaifi123** [comment]
> Yes, notifying it is happening again disappointed
> 
> Extra: When I want to check the details about the GitHub Actions process everything is laggy, and usually after some time it is redirecting to an error/unicorn page, saying that it is taking too long.
> 
> So, basically, I cannot even stop the workflow.

Actually, I am facing the same issue. May I know if this is the issue from GitHub or my repo?

**Comment by Yagya-omnius** [comment]
#reopening
This is again failing from today.
Can anyone can look into it

**Comment by FawadAbbas12** [comment]
> #reopening This is again failing from today. Can anyone can look into it

maybe it is due to high load just reran the same job again and it was successful

**Comment by AdityaRao1996** [comment]
Seems to have been fixed 👍🏽 Was running into internal errors for a while. The jobs are running okay now

**Comment by alexef** [comment]
Same for me today

**Comment by msorens** [comment]
Just started getting "GitHub Actions has encountered an internal error when running your job." about an hour ago on a couple GitHub Action runs, yet the GitHub status show everything nominal:
<img width="594" alt="image" src="https://github.com/actions/runner-images/assets/6817500/e2675ef3-076f-475a-adcc-99840973d8d9">

**Comment by MatheusBordin** [comment]
Same here just right now

**Comment by sercanbayrambey** [comment]
Same here right now.

**Comment by NikitaChelombitko** [comment]
Same here right now:
![image](https://github.com/actions/runner-images/assets/31968392/df272293-45ed-431e-98e5-03cb6749d8ec)

10:34 PM GMT+2

**Comment by binarybaron** [comment]
I'm having this issue right now as well. Anyone else?

**Comment by fzyzcjy** [comment]
+1 same on https://github.com/fzyzcjy/flutter_rust_bridge

![image](https://github.com/actions/runner-images/assets/5236035/13e3b52f-ed58-41f7-a32c-a73aa0bb10a6)
