### ISSUE TITLE
Node.js tools doesn't use color outputs because of wrong TTY detection

### ISSUE THREAD

**Issue by ai** [actions/virtual-environments#218]
**Describe the bug**

`chalk` is the most popular tool for color output in the Node.js ecosystem. Unfortunately, it can’t detect that GitHub Actions support color and use colorless output.

I created [an issue](https://github.com/chalk/supports-color/issues/106) and we found that Node.js does not detect `TTY` on stdout.

```js
process.stdout.isTTY //=> undefined
```

As a result, we have less readable output in all npm tools.

**Area for Triage**: JavaScript and Node.js

**Question, Bug, or Feature?**: Bug

**Virtual environments affected**
- [ ] macOS 10.15
- [x] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Expected behavior**

Color output for `chalk` based tools.

**Actual behavior**

1. Create empty `index.js`
1. Add `npx size-limit index.js` step
2. Check step output on the website: it has no colors.

**Comment by ai** [comment]
Auto assigning script was failed, so I will mention people manually. Sorry if I will mention somebody wrong:

@leantk @vijayma @bryanmacfarlane

**Comment by arcanis** [comment]
Yarn 2 is currently impacted as well. I'll use a workaround in the meantime, but I'll monitor these issues to add the right fix when possible 🙂

**Comment by bryanmacfarlane** [comment]
This may be an issue for actions/runner.  @TingluoHuang and @dakale , is that correct?

**Comment by TingluoHuang** [comment]
@bryanmacfarlane yes, I think the issue already tracked
https://github.com/actions/runner/issues/241

**Comment by kaylangan** [comment]
Closing in favor of tracking in https://github.com/actions/runner/issues/241

**Comment by kirillgroshkov** [comment]
Jest doesn't output colors too
