### ISSUE TITLE
Add mediainfo (for Ubuntu 16+)

### ISSUE THREAD

**Issue by mfn** [actions/virtual-environments#2185]
**Tool information**
- Tool name: mediainfo
- Tool license: BSD-2-clause
- Add or update? Add
- Desired version: just the default shipped with Ubuntu
- Approximate size: 29.5 kB for the base package and ~2MB with the dependencies, in total **~2MB**
- If this is an add request:
  - Brief description of tool: command-line utility for reading information from audio/video files
  - URL for tool's homepage: https://mediaarea.net/MediaInfo
  - Provide a basic test case to validate the tool's functionality: `mediainfo https://github.com/fluidicon.png`

<details>
<summary>The above command output</summary>

```
General
Complete name                            : https://github.com/fluidicon.png
Format                                   : PNG
Format/Info                              : Portable Network Graphic
File size                                : 32.5 KiB

Image
Format                                   : PNG
Format/Info                              : Portable Network Graphic
Format_Compression                       : LZ77
Width                                    : 512 pixels
Height                                   : 512 pixels
Bit depth                                : 32 bits
Compression mode                         : Lossless
Stream size                              : 32.5 KiB (100%)
```
</details>

**Use case**:
Allow integration tests to make actual use of this tool and verify it works on the sample media. Commonly used is it's XML output for parsing, e.g. `--Output=XML` (or `JSON` but only on alter version, e.g. Ubuntu 20+)

**Area for Triage**:

**Question, Bug, or Feature?**: Feature

**Virtual environments affected**
- [x] Ubuntu 16.04
- [x] Ubuntu 18.04
- [x] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Can this tool be installed during the build?**
`sudo apt-get install mediainfo`

**Tool installation time in runtime**
Should not take more than 10 seconds:
![image](https://user-images.githubusercontent.com/87493/100857193-b31cb180-348c-11eb-988f-07cd9b7910ef.png)

However multiple times I've seen runtimes for `sudo apt-get install` for only this package (and it's dependencies) to take >2m
![image](https://user-images.githubusercontent.com/87493/100857215-b9129280-348c-11eb-8e06-5006e0f4feaf.png)

<details>
<summary>Github action output of the >2m installation time, no obvious issues to me</summary>

```
Run sudo apt-get install mediainfo
Reading package lists...
Building dependency tree...
Reading state information...
The following additional packages will be installed:
  libmediainfo0v5 libmms0 libtinyxml2-6 libzen0v5
Suggested packages:
  mediainfo-gui
The following NEW packages will be installed:
  libmediainfo0v5 libmms0 libtinyxml2-6 libzen0v5 mediainfo
0 upgraded, 5 newly installed, 0 to remove and 12 not upgraded.
Need to get 2044 kB of archives.
After this operation, 7024 kB of additional disk space will be used.
Get:1 http://azure.archive.ubuntu.com/ubuntu bionic/universe amd64 libmms0 amd64 0.6.4-2 [27.4 kB]
Get:2 http://azure.archive.ubuntu.com/ubuntu bionic/universe amd64 libtinyxml2-6 amd64 6.0.0+dfsg-1 [27.9 kB]
Get:3 http://azure.archive.ubuntu.com/ubuntu bionic/universe amd64 libzen0v5 amd64 0.4.37-1 [94.0 kB]
Get:4 http://azure.archive.ubuntu.com/ubuntu bionic-updates/universe amd64 libmediainfo0v5 amd64 17.12-1ubuntu0.1 [1865 kB]
Get:5 http://azure.archive.ubuntu.com/ubuntu bionic/universe amd64 mediainfo amd64 17.12-1 [29.5 kB]
Fetched 2044 kB in 0s (31.3 MB/s)
Selecting previously unselected package libmms0:amd64.
(Reading database ... 
(Reading database ... 5%
(Reading database ... 10%
(Reading database ... 15%
(Reading database ... 20%
(Reading database ... 25%
(Reading database ... 30%
(Reading database ... 35%
(Reading database ... 40%
(Reading database ... 45%
(Reading database ... 50%
(Reading database ... 55%
(Reading database ... 60%
(Reading database ... 65%
(Reading database ... 70%
(Reading database ... 75%
(Reading database ... 80%
(Reading database ... 85%
(Reading database ... 90%
(Reading database ... 95%
(Reading database ... 100%
(Reading database ... 274023 files and directories currently installed.)
Preparing to unpack .../libmms0_0.6.4-2_amd64.deb ...
Unpacking libmms0:amd64 (0.6.4-2) ...
Selecting previously unselected package libtinyxml2-6:amd64.
Preparing to unpack .../libtinyxml2-6_6.0.0+dfsg-1_amd64.deb ...
Unpacking libtinyxml2-6:amd64 (6.0.0+dfsg-1) ...
Selecting previously unselected package libzen0v5:amd64.
Preparing to unpack .../libzen0v5_0.4.37-1_amd64.deb ...
Unpacking libzen0v5:amd64 (0.4.37-1) ...
Selecting previously unselected package libmediainfo0v5:amd64.
Preparing to unpack .../libmediainfo0v5_17.12-1ubuntu0.1_amd64.deb ...
Unpacking libmediainfo0v5:amd64 (17.12-1ubuntu0.1) ...
Selecting previously unselected package mediainfo.
Preparing to unpack .../mediainfo_17.12-1_amd64.deb ...
Unpacking mediainfo (17.12-1) ...
Setting up libtinyxml2-6:amd64 (6.0.0+dfsg-1) ...
Setting up libmms0:amd64 (0.6.4-2) ...
Setting up libzen0v5:amd64 (0.4.37-1) ...
Setting up libmediainfo0v5:amd64 (17.12-1ubuntu0.1) ...
Setting up mediainfo (17.12-1) ...
Processing triggers for man-db (2.8.3-2ubuntu0.1) ...
Processing triggers for libc-bin (2.27-3ubuntu1.3) ...
```
</details>

**Are you willing to submit a PR?**
Yes!

**Comment by miketimofeev** [comment]
Hi @mfn!
Please feel free to submit a PR.

**Comment by mfn** [comment]
I've created https://github.com/actions/virtual-environments/pull/2188 !

**Comment by miketimofeev** [comment]
@mfn PR has been merged! The next week is deployment freeze so that the new image will be deployed the week after.

**Comment by al-cheb** [comment]
MediaInfo version is now available:
https://github.com/actions/virtual-environments/blob/releases/ubuntu16/20201210/images/linux/Ubuntu1604-README.md
https://github.com/actions/virtual-environments/blob/releases/ubuntu18/20201210/images/linux/Ubuntu1804-README.md
https://github.com/actions/virtual-environments/blob/releases/ubuntu20/20201210/images/linux/Ubuntu2004-README.md

**Comment by mfn** [comment]
Thank you all!
