### ISSUE TITLE
Add zstd

### ISSUE THREAD

**Issue by liborty** [actions/virtual-environments#219]
**Tool information**
- Tool name: Zstd Zstandard 
- Add or update? Add
- Desired version:  latest stable 
- Approximate size: 571536 
- If this is an add request:
  - Brief description of tool: Modern compression tool (by Facebook) 
  - URL for tool's homepage:  https://facebook.github.io/zstd/  

**Area for Triage**: 

**Question, Bug, or Feature?**:  "Feature" 

**Virtual environments affected**
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [x] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Can this tool be installed during the build?**

**Are you willing to submit a PR?**

**Comment by liborty** [comment]
On second thoughts, this is perhaps not so urgent. Lzma is already in your virtual environment and it is in many ways just as good.

**Comment by joshmgross** [comment]
@vtbassmatt this is a duplicate of https://github.com/actions/virtual-environments/issues/89, it might be worth closing one of them.

**Comment by liborty** [comment]
In response to @joshmgross, I am closing this issue.

**Comment by krcroft** [comment]
> Lzma is (...) just as good.

Please take a moment to research the comparison of zstd to lzma-based compressors like xz and lzma. 

Zstd offers compression speed options (and commensurate resulting data compression) ranging from extremely fast (mullti-GB/s) to extremely slow (and tightly packed).  Decompression speeds, for any level of compression, are roughly the same and can approach several orders of magnitude faster than lzma.  

This is why zstd is now being added to or outright replacing gzip/libz in most software areas today.
