### ISSUE TITLE
Official Ruby binaries will be installed on images by default

### ISSUE THREAD

**Issue by AlenaSviridenko** [actions/virtual-environments#2193]
**Breaking changes**
We are switching pre-cached Ruby binaries to official Ruby binaries on all images.

**Context**
Tasks [actions/setup-ruby](https://github.com/actions/setup-ruby) (GitHub Actions) and [UseRuby](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/tool/use-ruby-version?view=azure-devops) (Azure DevOps) switches Ruby versions pre-installed on images.
Previously, we built Ruby from source code and cached them into images.
We are switching Ruby binaries to official ones provided by Ruby community on https://github.com/ruby/ruby-builder

**Target date**
Images with these changes will be deployed the week of November, 30

**The motivation for the changes**
We should use official binaries on our images. It will allow reduce maintenance concerns and reduce the number of issues.

**Possible impact**
Officially, Ruby 2.4 and 2.5 don't have pre-installed Bundler. Bundler was built-in only in Ruby 2.6 and 2.7.
Our previous binaries were customized and contained bundler for Ruby 2.4, 2.5.

So after these changes, you could face with issues like `bundle: command not found` if using Ruby 2.4 or 2.5.
It could also affect default Ruby on Windows images since Ruby 2.5 is used as default.

**Virtual environments affected**
- [x] Ubuntu 16.04
- [x] Ubuntu 18.04
- [x] Ubuntu 20.04
- [x] Windows Server 2016 R2
- [x] Windows Server 2019

**Mitigation ways**
1. For GitHub Actions, consider using official Ruby action `ruby/setup-ruby` instead of `actions/setup-ruby`. It has input params to specify bundler version
2. Run `gem install bundler` to install bundler in runtime

**Comment by maxim-lobanov** [comment]
Changes were deployed everywhere. Closing the issue
