### ISSUE TITLE
Roam-Git: Ubuntu-20.04 

### ISSUE THREAD

**Issue by karisgriley** [actions/virtual-environments#2194]
**Description**  
A clear and concise description of what the bug is, and why you consider it to be a bug.
update for Roam-Git GitHub Action workflow: 
Ubuntu-20.04 is ready to be the default version for the “ubuntu-latest” label in GitHub Actions and Azure DevOps. This change will be rolled out over a period of several weeks beginning on November, 30. (December, 22 - January, 4 will be a migration break due to holidays)

**Area for Triage**:  

**Question, Bug, or Feature?**:  

Question

**Virtual environments affected**  
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04 ?
- [ ] Ubuntu 20.04
- [ ] macOS 10.15 ?
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Expected behavior**  
A description of what you expected to happen.

I get this warning:
WARNING: You are using pip version 20.2.4; however, version 20.3.1 is available.
41
You should consider upgrading via the '/opt/hostedtoolcache/Python/3.8.6/x64/bin/python -m pip install --upgrade pip' command.

Do roam-git users need to transition back to Ubuntu 18.04? What are the consequences if we don't? Data loss?

**Actual behavior**  
A description of what is actually happening.

**Repro steps**  
A description with steps to reproduce the issue. If your have a public example or repo to share,
please provide the link.

1. Step 1
2. Step 2

**Comment by miketimofeev** [comment]
Hi @karisgriley!
This warning is expected and shouldn't break the pipeline.
You can stay on Ubuntu 18 if Ubuntu 20 doesn't suit your needs.

**Comment by miketimofeev** [comment]
@karisgriley I'm going to close the issue since no additional details provided.
Please feel free to contact us if you have any concerns.
