### ISSUE TITLE
Obsolete packages ready for autoremove

### ISSUE THREAD

**Issue by liborty** [actions/virtual-environments#220]
**Describe the bug**
While installing zstd manually, via apt-get install, I noticed a fair number of packages in your Ubuntu environment being reported as obsolete and ready for 'autoremove'.

**Area for Triage**: probably most of them

**Question, Bug, or Feature?**: Bug

**Virtual environments affected**
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [x] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Expected behavior**
I suggest you run 'autoremove' automatically over your environments. You could save yourself quite a lot of space, as well as the users of unnecessary warnings.

**Actual behavior**
Installing anything with 'apt-get install packagename' produces the list of obsolete packages.
As in my workflow:
https://github.com/liborty/TokenCrypt/blob/master/.github/workflows/test.yml

**Comment by al-cheb** [comment]
Hello, @liborty 

The `apt-get autoremove` command provide list of packages that we can't delete, because it will break some customers who use e.g.`bc` in their scripts.
```
The following packages will be REMOVED:
  bc dns-root-data dnsmasq-base ebtables grub-pc-bin landscape-common
  liblldb-6.0 liblldb-8 liblxc-common liblxc1 libuv1 linux-headers-4.15.0-99
  lxcfs lxd lxd-client python3-attr python3-automat python3-click
  python3-colorama python3-constantly python3-hyperlink python3-incremental
  python3-pam python3-pyasn1 python3-pyasn1-modules python3-service-identity
  python3-twisted python3-twisted-bin python3-zope.interface xdelta3
0 upgraded, 0 newly installed, 30 to remove and 12 not upgraded.
After this operation, 198 MB disk space will be freed.
```
198 MB is not large amount of space that we can save on an image.

To suppress message about obsolete package, please use one of the workarounds:

1. flag -qq
`sudo apt-get -qq install zstd`

2. apt.conf
```
sudo bash -c 'cat << EOF >  /etc/apt/apt.conf
        APT::Get::AutomaticRemove "0";
        APT::Get::HideAutoRemove "1";
        EOF'
```

I will prepare a PR and include these changes to suppress autoremove output.

**Comment by miketimofeev** [comment]
@liborty The image with suppressed output has been deployed. Feel free to open a new issue if you have any concerns.
Thank you!
