### ISSUE TITLE
Files written by UWP app running in CI are not there

### ISSUE THREAD

**Issue by asklar** [actions/virtual-environments#2207]
**Description**  
We have a UWP that gets built and runs during CI. As part of the app's run, it saves a file to [LocalFolder](https://docs.microsoft.com/en-us/uwp/api/windows.storage.applicationdata.localfolder?view=winrt-19041#Windows_Storage_ApplicationData_LocalFolder), which maps to `%localappdata%\Packages\OurAppsPFN\LocalState`.

The app also saves the path of the first file it saved as a txt file in the Documents library (the app has the documentsLibrary capability and the txt file extension).

The app verifies that the files were written correctly and prints out the file sizes. Everything works fine when we run the app locally, but in Azure DevOps CI, after the app runs, neither files are there. 

trying to type the content of the output file fails with "file not found":

```
type C:\Users\VssAdministrator\AppData\Local\Packages\ReactUWPTestApp_cezq6h4ygq1hw\LocalState\ControlStyleRegularBorder.json 
```
https://dev.azure.com/ms/react-native-windows/_build/results?buildId=126499&view=logs&j=d748dad3-a0b7-5fdb-711c-b2cdfdfc24a4&t=0c4b12d4-4b27-5b18-f5ca-846c1e804c8f&l=11

**Question**
The only explanation I can come up with is either something else is deleting the files after the app exits, or the filesystem access is being virtualized for the app in the context of the CI environment (and the app doesn't know it). Is there anything like that going on?

**Area for Triage**:  
Scripting and command line

**Question, Bug, or Feature?**:  
Question

**Virtual environments affected**  
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [X] Windows Server 2019

**Expected behavior**  
The files are there

**Actual behavior**  
The files are not there

**Repro steps**  
https://dev.azure.com/ms/react-native-windows/_build/results?buildId=126499&view=logs&j=d748dad3-a0b7-5fdb-711c-b2cdfdfc24a4&t=8d532d4b-2069-5b82-7380-1bb5d8e43618&l=162

https://dev.azure.com/ms/react-native-windows/_build/results?buildId=126499&view=logs&j=d748dad3-a0b7-5fdb-711c-b2cdfdfc24a4&t=0c4b12d4-4b27-5b18-f5ca-846c1e804c8f&l=11

**Comment by maxim-lobanov** [comment]
Hello @asklar , we are not aware about something that could remove those files after running apps.
Can we add additional logging to application to confirm that it writes files properly and may be write file paths to logs too to make sure that you are looking for files in correct location?

**Comment by asklar** [comment]
thanks for the reply @maxim-lobanov . Yes, I added the logging, it prints the full path of the files it writes to, as well as the size. However once the app is closed, and I try showing the content of the file in a subsequent task, or copying it to the artifact folder, etc., the files are not found. I also tried finding the files under other folders to no avail.

I then even figured I'd start a procmon trace and upload the results, and I can see procmon starts etc but the files that procmon produces can't be found either so I'm not really sure what is going on... I don't assume there is any way to remote into one of the agents so I can live debug this?

**Comment by al-cheb** [comment]
@asklar,
There are no any files local either:

1.  git branch
* e2etest_pfn

2. Installing application
```
PS C:\Users\testAdm2\Desktop\react-native-windows\packages\E2ETest> C:\Users\testAdm2\Desktop\ReactUWPTestApp_1.0.0.0_x86_Test\Add-AppDevPackage.ps1 -Force
Found package: C:\Users\testAdm2\Desktop\ReactUWPTestApp_1.0.0.0_x86_Test\ReactUWPTestApp_1.0.0.0_x86.appx
Found certificate: C:\Users\testAdm2\Desktop\ReactUWPTestApp_1.0.0.0_x86_Test\ReactUWPTestApp_1.0.0.0_x86.cer

Before installing this app, you need to do the following:
        - Install the signing certificate
WARNING:
You are about to install a digital certificate to your computer's Trusted People certificate store. Doing so carries serious security risk and should only be done if you trust the originator of this digital
certificate.

When you are done using this app, you should manually remove the associated digital certificate. Instructions for doing so can be found here: http://go.microsoft.com/fwlink/?LinkId=243053

Are you sure you wish to continue?


Installing app...
Found dependency package(s):
C:\Users\testAdm2\Desktop\ReactUWPTestApp_1.0.0.0_x86_Test\Dependencies\x86\Microsoft.NET.CoreFramework.Debug.2.2.appx
C:\Users\testAdm2\Desktop\ReactUWPTestApp_1.0.0.0_x86_Test\Dependencies\x86\Microsoft.NET.CoreRuntime.2.2.appx
C:\Users\testAdm2\Desktop\ReactUWPTestApp_1.0.0.0_x86_Test\Dependencies\x86\Microsoft.UI.Xaml.2.5.appx
C:\Users\testAdm2\Desktop\ReactUWPTestApp_1.0.0.0_x86_Test\Dependencies\x86\Microsoft.VCLibs.x86.14.00.appx
C:\Users\testAdm2\Desktop\ReactUWPTestApp_1.0.0.0_x86_Test\Dependencies\x64\Microsoft.NET.CoreRuntime.2.2.appx
C:\Users\testAdm2\Desktop\ReactUWPTestApp_1.0.0.0_x86_Test\Dependencies\x64\Microsoft.UI.Xaml.2.5.appx
C:\Users\testAdm2\Desktop\ReactUWPTestApp_1.0.0.0_x86_Test\Dependencies\x64\Microsoft.VCLibs.x64.14.00.appx

Success: Your app was successfully installed.
```

3. List files
```
PS C:\Users\testAdm2\Desktop\react-native-windows\packages\E2ETest> dir $env:UserProfile\AppData\Local\Packages\ReactUWPTestApp_cezq6h4ygq1hw -Recurse


    Directory: C:\Users\testAdm2\AppData\Local\Packages\ReactUWPTestApp_cezq6h4ygq1hw


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----       12/10/2020   8:17 AM                AC
d-----       12/10/2020   8:17 AM                AppData
d-----       12/10/2020   8:17 AM                LocalCache
d-----       12/10/2020   9:15 AM                LocalState
d-----       12/10/2020   8:17 AM                RoamingState
d-----       12/10/2020   8:21 AM                Settings
d-----       12/10/2020   8:17 AM                SystemAppData
d-----       12/10/2020   8:17 AM                TempState


    Directory: C:\Users\testAdm2\AppData\Local\Packages\ReactUWPTestApp_cezq6h4ygq1hw\AC


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----       12/10/2020   8:17 AM                Temp


    Directory: C:\Users\testAdm2\AppData\Local\Packages\ReactUWPTestApp_cezq6h4ygq1hw\LocalState


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----       12/10/2020   9:15 AM                react-native


    Directory: C:\Users\testAdm2\AppData\Local\Packages\ReactUWPTestApp_cezq6h4ygq1hw\LocalState\react-native


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----       12/10/2020   9:15 AM            196 asyncStorage.txt


    Directory: C:\Users\testAdm2\AppData\Local\Packages\ReactUWPTestApp_cezq6h4ygq1hw\Settings


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----       12/10/2020   8:17 AM              0 roaming.lock
-a----       12/10/2020   9:24 AM           8192 settings.dat

```
 
![image](https://user-images.githubusercontent.com/47745270/101753085-4d12d880-3ae3-11eb-88b0-75dda7ef4e38.png)

**Comment by asklar** [comment]
thanks a lot for taking a look @al-cheb ! The files are created by the Legacy* pages towards the end.

I found the problem though, some piece of the app was clearing the files from under the piece that was creating them :)
