### ISSUE TITLE
An error occurred while trying to link with `libclang.dll`

### ISSUE THREAD

**Issue by aleksuss** [actions/virtual-environments#2208]
**Description**  
My project has `libclang.dll` dependency. I install `llvm` package which contains `libclang.dll` inside via `choco` package manager. Everything was ok but about 24 days ago I found out an error while trying to link with `libclang.dll`. I guess the reason is that `msys2` became to contain `libclang.dll` as well.

**Area for Triage**:  Rust

**Question, Bug, or Feature?**:  Bug

**Virtual environments affected**  
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [x] Windows Server 2019

**Expected behavior**  
Linking with `libclang.dll` without errors.

**Actual behavior**  
An error occurred while trying to link with `libclang.dll`.  

**Repro steps**  
https://github.com/rust-rocksdb/rust-rocksdb/pull/481/checks?check_run_id=1509349758#step:5:107

**Comment by dibir-magomedsaygitov** [comment]
Hello, @aleksuss.
I have made an investigation and looks like your workflow somehow adds MSYS to the PATH and creates dll collision. We are  intentionally not adding MSYS to the PATH just to avoid these kind of issues.
I see two solutions here:
1) Add step to your workflow that deletes MSYS from the image:
 ```
- name: remove msys64
        if: runner.os == 'Windows'
        run: Remove-Item -LiteralPath "C:\msys64\" -Force -Recurse
```
2) Try to investigate why MSYS is used by your code despite the fact that it is not added to the PATH

Looking forward to your replay.

**Comment by aleksuss** [comment]
Hello, @dibir-magomedsaygitov. Thanks for advice. The first workaround works well. To be fair I thought about such approach    but then decided to create the issue for getting more elegant solution 😄  But It's ok. 
By the way. I did nothing related to PATH and I don't know why linker is trying to link with `C:\\msys64\\mingw64\\bin\\libclang.dll` rather than library from `llvm` package. It's weird. So. Thank you once again. It works now. 👍🏻
