### ISSUE TITLE
JUnit test failure only on Github Action CI

### ISSUE THREAD

**Issue by bencalegari** [actions/virtual-environments#2213]
**Description**:  
We're experiencing a JUnit test failure only on the CI container that can't be replicated on any other developer machines. I recognize this doesn't necessarily implicate the contianer, but given that it's just a [unit test](https://github.com/codeforamerica/shiba/blob/master/src/test/java/org/codeforamerica/shiba/output/applicationinputsmappers/CoverPageInputsMapperTest.java) that doesn't use network requests or interact with the database, I don't see any obvious places where test pollution might occur. 

**Area for Triage**:  Java, Testing and code coverage
**Question, Bug, or Feature?**:  Bug
**Virtual environments affected**  
- [x] Ubuntu 18.04
- [x] Ubuntu 20.04
- [x] macOS 10.15

**Expected behavior**  
Running `./gradlew test` passes on any environment.

**Actual behavior**  
One particular [unit test](https://github.com/codeforamerica/shiba/blob/master/src/test/java/org/codeforamerica/shiba/output/applicationinputsmappers/CoverPageInputsMapperTest.java) fails, only on CI. 
**Repro steps** 
- Run `./gradlew test`. Project is [open source](https://github.com/codeforamerica/shiba) so feel free to clone it and use the readme instructions to run the test yourselves.
- [Test failure on 20.04](https://github.com/codeforamerica/shiba/commit/c50ede4197c361a176a5e2167a279dbcc95c94e6/checks)
- [Failure on 18.04](https://github.com/codeforamerica/shiba/runs/1512753983?check_suite_focus=true)

**Comment by dsame** [comment]
@bencalegari i see the test seems to be fixed by removing  `@ContextConfiguration` annotation of `CoverPageInputsMapperTest` class . Please confirm the problem is solved now

**Comment by bencalegari** [comment]
I'm not sure what version of the file you're referencing, but we ended up resolving the issue by getting the `Locale` from the `LocaleContextHolder`, and elevating it to a SpringBoot test. Unsure exactly what happened but I'll close this for now.
