### ISSUE TITLE
Getting "No valid image label found in agent specification" despite providing valid agent name in yaml build definition

### ISSUE THREAD

**Issue by ericcjobes** [actions/virtual-environments#2214]
**Description**  
Build release stages are failing with error `No valid image label found in agent specification`. We are trying to allocate an agent from pool `Release-Pool-Public` maintained by IC3 ES Agent Provider Service.

**Area for Triage**:  

**Question, Bug, or Feature?**:  
Bug

**Virtual environments affected**  
- [ ] Ubuntu 16.04
- [x] Ubuntu 18.04
- [x] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Expected behavior**  
Job is scheduled and allocated appropriate agent from available pool

**Actual behavior**  
Job is canceled with ADO error message `No valid image label found in agent specification`. Recreating the pipeline with identical settings sometimes temporarily resolves the problem, but this is not a sustainable workaround.
![image](https://user-images.githubusercontent.com/56457218/101413624-704a4780-3899-11eb-8d39-327275329245.png)

**Repro steps**  
1. Trigger release pipeline agent job with pool set to `Azure Pipelines` with `Ubuntu 16.04` or `Ubuntu 18.04` agent selected
2. Observe ADO-canceled job due to no image label found.

**Comment by al-cheb** [comment]
Hello, @ericcjobes 
Could you please provide a minimal yaml file to reproduce the issue?

**Comment by ericcjobes** [comment]
@al-cheb I have tried reproducing this with minimal release definition (using classic UI editor as we don't use yaml releases yet) and have not created a successful repro. But, I still do have multiple occurrences of this across several pipelines. I will share the pipeline details those use, but I have not noticed any patterns between repros as far as what steps are executed in each job, besides that they all use `Azure Pipelines` agents.

Sorry for the UI pictures, as there seems to be no way to "view yaml" for classic UI pipelines any more (these have no 'runs' page as far as I can tell)

**First repro:**
Agent Setup:
![image](https://user-images.githubusercontent.com/56457218/102283925-2fc97a00-3ee8-11eb-87d5-22be55751941.png)
Tasks:
![image](https://user-images.githubusercontent.com/56457218/102283932-32c46a80-3ee8-11eb-98ba-0fb6e3dd24d8.png)
![image](https://user-images.githubusercontent.com/56457218/102283938-3526c480-3ee8-11eb-8dec-ce0aa08177b4.png)

**Second repro**
Same agent pool (Azure Pipelines)
Tasks:
![image](https://user-images.githubusercontent.com/56457218/102283976-4374e080-3ee8-11eb-841b-21ccfeb4734d.png)

My attempt to repro using Azure Pipelines pool looked like the following:
Agent setup:
![image](https://user-images.githubusercontent.com/56457218/102284987-27723e80-3eea-11eb-95e3-4b3a9813dd76.png)
Tasks:
![image](https://user-images.githubusercontent.com/56457218/102285041-3bb63b80-3eea-11eb-838f-ccb4b50ddd89.png)

I triggered 5 releases each on Ubuntu-16.04 and Ubuntu-18.04 and was not able to repro. But there are still repros coming in from other pipelines, just not often. I think this issue is best diagnosed via added logging/telemetry from your side if possible.

**Comment by maxim-lobanov** [comment]
@ericcjobes , I suggest contact Azure DevOps support about this issue and attach links to failed builds. They will be able to retrieve more information for analyze and answer properly.
In this repository, we are trying to manage only issues related content of Hosted images. Your issue looks more like an issue with some ADO backend logic and assigning builds. I feel that ADO support will have more ways to help you with it.

**Comment by al-cheb** [comment]
@ericcjobes ,
Please remove all demands from your pipelines for hosted-agents. 
https://docs.microsoft.com/en-us/azure/devops/pipelines/process/demands
`Demands and capabilities are designed for use with self-hosted agents so that jobs can be matched with an agent that meets the requirements of the job. When using Microsoft-hosted agents, you select an image for the agent that matches the requirements of the job, so although it is possible to add capabilities to a Microsoft-hosted agent, you don't need to use capabilities with Microsoft-hosted agents.`


![image](https://user-images.githubusercontent.com/47745270/102315036-7d93c000-3f84-11eb-99b3-02762b8036c3.png)

**Comment by ericcjobes** [comment]
We found a solution to this issue!

Somehow, ADO lets pipelines (or at least specific releases) be saved even when no `Agent Specification` is set. I missed this in my investigation as I was looking at the latest release definition, and not the release definition used in the repros. 

When navigating to the release definition which repros this issue, and going to Agent Job area, it is clear that `Agent Specification` field is empty, despite owners of this pipeline stating they had previously selected the relevant agent. Here's the view with no edits made on my side (as in, this is the current state of the release as ADO understands it)
![image](https://user-images.githubusercontent.com/56457218/102538416-15ff7280-4061-11eb-87ff-52cf76bed702.png)

We can fix this by reselecting the correct `Agent Specification` and saving the pipeline and ensuring it has propagated correctly.
