### ISSUE TITLE
GCC-9 not installed correctly on macOS 10.15?

### ISSUE THREAD

**Issue by jlconlin** [actions/virtual-environments#2215]
**Description**  
I'm trying to compile on macOS 10.15 using g++-9. Everything compiles fine, but when it gets to the linking stage, it fails. See [here](https://github.com/njoy/NJOY21/runs/1514174589?check_suite_focus=true). It looks like g++-9 is using g++-8 libraries as the `-L` command-line option points to the g++8 installation.

**Area for Triage**:  

C/C++
**Question, Bug, or Feature?**:  

Bug

**Virtual environments affected**  
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ x] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Expected behavior**  
I would expect that g++-9 would look for c++ libraries associated with the g++-9 installation.

**Actual behavior**  
When linking, g++-9 seems to look in these location for libraries:
```
-L/usr/local/Cellar/gcc@8/8.4.0_1/lib/gcc/8/gcc/x86_64-apple-darwin19/8.4.0  
-L/usr/local/Cellar/gcc@8/8.4.0_1/lib/gcc/8  
```

**Repro steps**  
Please see my failed linking [here](https://github.com/njoy/NJOY21/runs/1514174589?check_suite_focus=true), (line 252 of the make step).

**Comment by jlconlin** [comment]
I'm no expert on this, but it seems that gcc-9 (including g++-9) was not installed correctly on macOS 10.15.

**Comment by dsame** [comment]
@jlconlin can you please confirm your build is working with osx 10.14?

I can not deduce where the '-L/usr/local/Cellar/gcc@8/8.4.0_1/lib/gcc/8/gcc/x86_64-apple-darwin19/8.4.0' path is coming from so far.

While neither `brew` (it is used to install gcc) nor `cmake` are not supposed to be the reason of such misbehaviour  i guess the '-L' is going from Xcode. 

Before i'll be digging more in the dependencies, please confirm, it is possible to use gcc-9 with your build system at all.

**Comment by dsame** [comment]
@jlconlin this build confirms gcc++-9 installed correctly, cmake does not add false '-L' options and the symbols which are undefined in your build are linked successfully: 

https://github.com/dsame/actions-demo/runs/1537008123

Thus the '-L' linker options seems to go from some of the dependencies of your project

**Comment by jlconlin** [comment]
@dsame Thanks for looking at this. the `-L` is just telling the compiler where to find libraries to link to. I think this is a problem with the installation because our code compiles on Linux with GCC and LLVM and on Mac with LLVM without any problems. Using the same configuration on Mac with GCC is where issues arise. 

I can see that your action does compile, but it doesn't look like it's compiling C++ code. There is this `TutorialConfig.h` file, but it doesn't look like C++ to me. Perhaps I'm not looking at the right thing.

**Comment by dsame** [comment]
@jlconlin you generate your makefiles with cmake tool, which is responsible to create the necessary command line options including the `-L`. As you see from the my build the cmake creates the Makefile to build c++ code that is linked agains the symbols which are `undefined` in you failed build:

```
int main(int argc, char* argv[]) {
  if (argc < 2) {	    std::basic_string<char> s(argv[0]);
    // report version	    std::__cxx11::basic_string<char> s11(argv[0]);
    std::cout << argv[0] << " Version " << "." << std::endl;	
    std::cout << "Usage: " << argv[0] << " number" << std::endl;	    std::basic_regex ninth ("\\bd\\w+", 0);     
    return 1;	
  }	    std::string subject = "Duddy the duck";
// c++11	    std::string replacement = "yup";
  const double inputValue = std::stod(argv[1]);	
  return 0;	    std::cout << "Usage: " << s << s11 << regex_replace (subject, ninth, replacement) << std::endl;

    return 0;
}	
}
```

Thus proves neither gcc nor cmake is responsible for adding the wrong option, it seems  there's a some dependency with the wrong discovery code. I'll take a close look to those deps, but there's a lot of them an it will take significant amount of time

**Comment by dsame** [comment]
@jlconlin can you please double check you should not use gfortran-9 alongside with gcc-9? 
I mean this matrix item in https://github.com/njoy/NJOY21/blob/3bbef78c212c3752fa63fbcd7d651e7f44259ffe/.github/workflows/ContinuousIntegration.yml:

```
jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ ubuntu-18.04, macos-10.15 ]
        cxx: [ g++-9, clang++ ]
        vFortran: [ gfortran-8 ]
        build_type: [ Debug, Release ]
```

I tried to run your build with fortran-9 and makefile does not seem to have reference to gcc-8 library anymore, although it fails with some compilation errors

https://github.com/dsame/NJOY21/runs/1555663462?check_suite_focus=true

**Comment by jlconlin** [comment]
@dsame Now I'm somewhat embarrassed. I should have used g++-9 and gfortran-9 together, I hadn't noticed the difference earlier. I suspect that is likely the cause of the original problem, but I'm not smart enough to demonstrate that definitively. 

Now as to the new compilation problem, I'm not sure the cause of it. It's probably not worth dealing with on this thread.
