### ISSUE TITLE
Update aws cli v2 on Ubuntu 20.04 to include ecr-public subcommand

### ISSUE THREAD

**Issue by pmalek-sumo** [actions/virtual-environments#2219]
**Tool information**
- Tool name: AWS CLI
- Tool license: `Apache License, Version 2.0`
- Add or update? update (from `2.1.4`)
- Desired version: `2.1.6` or `2.1.7` 
- Approximate size:

**Area for Triage**: Scripting and command line

**Virtual environments affected**
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [x] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Can this tool be installed during the build?**
https://github.com/aws/aws-cli/tree/v2#installation or https://docs.aws.amazon.com/cli/latest/userguide/install-cliv2.html

latest version installation:

```
curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
unzip awscliv2.zip
sudo ./aws/install
```

or specific version

```
curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64-2.0.30.zip" -o "awscliv2.zip"
unzip awscliv2.zip
sudo ./aws/install
```

**Tool installation time in runtime**
Not verified just yet.

**Are you willing to submit a PR?**
Sure

NOTE: `2.1.6` introduced `ecr-public` subcommand which handles requests towards recently launched [AWS public ECR](https://aws.amazon.com/about-aws/whats-new/2020/12/announcing-amazon-ecr-public-and-amazon-ecr-public-gallery/)

**Comment by al-cheb** [comment]
Hello, @pmalek-sumo 
The https://github.com/actions/virtual-environments/blob/main/images/linux/scripts/installers/aws.sh script is updated to install the latest version for Ubuntu 20.04.

**Comment by pmalek-sumo** [comment]
Thanks @al-cheb for clarification

So do I understand it correctly that it all depends on which runner I end up running my job on because of the time when the runner was provisioned? 

Or is there a different reason for my job getting aws `2.1.4` in here: https://github.com/SumoLogic/sumologic-kubernetes-collection/runs/1517520296?check_suite_focus=true#step:4:4 ?

**Comment by maxim-lobanov** [comment]
@pmalek-sumo , the script that Alex mentioned install always the latest version of AWS to Ubuntu 20.04 images.
Currently, it is 2.1.4 that was released 14 days ago. With next image rollout, images will be updated to AWS CLI 2.1.8 automatically.

Usually, it takes less time to propagate new version but we have deployment freeze this week due to Universe so i would expect new image with latest AWS next week

**Comment by pmalek-sumo** [comment]
Ok, got it.

Can we leave this issue open until new rollout so that we get a notification when can we change our workflows?

**Comment by maxim-lobanov** [comment]
Sure, we will update an issue as soon as deployment is finished

**Comment by crazy-max** [comment]
GitHub Runners does not currently support `ecr-public` command. See docker/login-action#37 for more info.

* `ubuntu-latest` / `ubuntu-18.04`: AWS CLI 1.18.185 (needs [1.18.193](https://docs.aws.amazon.com/cli/latest/reference/ecr-public/index.html))
* `ubuntu-20.04`: AWS CLI 2.1.4 (needs [2.1.10](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/ecr-public/index.html))

Thanks.

**Comment by bhautikpip** [comment]
Any updates on deployment?

**Comment by maxim-lobanov** [comment]
Deployment of Ubuntu 20.04 has been finished yesterday.
AWS CLI was updated to 2.1.9.
Closign the issue.
