### ISSUE TITLE
Managed Images

### ISSUE THREAD

**Issue by thepaulmacca** [actions/virtual-environments#2224]
I've only just come across this repo and have found it to be a great resource. I was wondering if there were plans to move to managed images in future?

The reason I ask - when I run `packer build` I'm being advised  `Warning: You are using Azure Packer Builder to create VHDs which is being deprecated, consider using Managed Images`. It's also advising that we don't need to use `Object_Id` any more

Thanks

**Comment by miketimofeev** [comment]
Hi @thepaulmacca!
We've come across this question previously — please take a look at this thread https://github.com/actions/virtual-environments/issues/1037

**Comment by thepaulmacca** [comment]
Thanks for the quick reply and attaching that thread @miketimofeev! I have peace of mind now 👍
