### ISSUE TITLE
run docker-compose on ubuntu-* results in connection error

### ISSUE THREAD

**Issue by Hackebein** [actions/virtual-environments#2227]
**Description**  
As mentioned in #765 run docker-compose results in error `Couldn't connect to Docker daemon at http+docker://localhost - is it running?`. Especially on an invalide docker-compose-file.

Me personally reached the error by using the environment variable `github.repository` (which can contains upper case letters) as a part of a docker image tag (where no upper case letters allowed). 

**Area for Triage**:  
Deployment/Release

**Question, Bug, or Feature?**:  
Bug

**Virtual environments affected**  
- [X] Ubuntu 16.04
- [X] Ubuntu 18.04
- [X] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Expected behavior**  
executing docker-compose to get something back from the docker engine like an error or success message.

**Actual behavior**  
executing docker-compose results in connection error.

**Repro steps**  
1. write an invalid docker-compose.yml file (for example with an upper case letter in tag)
2. npm install lodash
3. docker-compose build

It's independent from ubuntu environments and independent from preinstalled node versions (8, 10, 12, 14).
It depends on what npm package(s) you are installing.
128 of top 250 npm packages (sorted my pagerank) causing this problem.

Test repository can be found here: https://github.com/Hackebein/github-action-docker-compose-connection-error-example
I haven't tested mac and windows environments yet. Maybe the error exists there too.

**Comment by Hackebein** [comment]
I did some more research. My results are clear even they make no sense for me at the moment.
* removing `node_modules` folder fixes the problem always.
* It doesn't depend on `node_modules` folder is located. It can be in any subfolder.
* Uninstalling the package(s) with `npm uninstall` fixes the problem often but not always (works in my test repo for `lodash` and `prop-types` but not for `request`)

**Comment by Hackebein** [comment]
I added a new commit to https://github.com/Hackebein/github-action-docker-compose-connection-error-example
this commit removes npm completely from the process. As i mentioned in my last comment `npm uninstall` doesn't work for npm package `request`. I took the remains after uninstallation of `request` and stripped the files down to the bare minimum what is needed to cause this error.
I have now 16 `README.md` files. Now comes the part where it makes no sense for me anymore. Removing one of the `README.md` files or removing `.git` folder solves the problem.

**Comment by andy-mishechkin** [comment]
Hello, @Hackebein 
Thank you for your note.
We've preproduced this situation on clear Ubuntu machine, clone your repository and have made all steps, which you specified in this ticked.
Before `npm install lodash` we've got the valid error message:
```
/test/github-action-docker-compose-connection-error-example# docker-compose -f docker-compose.fails.yml build
Building latest
ERROR: invalid reference format: repository name must be lowercase
```
After `npm install lodash` we tried to execute the same:

```
/test/github-action-docker-compose-connection-error-example# npm install lodash
/test/github-action-docker-compose-connection-error-example
└── lodash@4.17.20 
npm WARN enoent ENOENT: no such file or directory, open '/test/github-action-docker-compose-connection-error-example/package.json'
npm WARN github-action-docker-compose-connection-error-example No description
npm WARN github-action-docker-compose-connection-error-example No repository field.
npm WARN github-action-docker-compose-connection-error-example No README data
npm WARN github-action-docker-compose-connection-error-example No license field.
/test/github-action-docker-compose-connection-error-example# docker-compose -f docker-compose.fails.yml build
Building latest
ERROR: Couldn't connect to Docker daemon at http+docker://localhost - is it running?
If it's at a non-standard location, specify the URL with the DOCKER_HOST environment variable.
```
Then to make sure that node_modules folder is causing the issue, I’ve removed it and made the test again:
```
/test/github-action-docker-compose-connection-error-example# rm -rf node_modules/
/test/github-action-docker-compose-connection-error-example# docker-compose -f docker-compose.fails.yml build
Building latest
ERROR: invalid reference format: repository name must be lowercase
```
I think, this is a not build issue, but it's a docker issue. Perhaps make sense to ping docker support service about it.

**Comment by Hackebein** [comment]
Thanks for your response. I tested that earlier and it works for me. That's why i was only focused on the virtual environments. But i can't reproduce my results anymore. I think i did something different/wrong earlier.

I found this bug in docker-compose issue tracker:
https://github.com/docker/compose/issues/7920

**Comment by andy-mishechkin** [comment]
Thank you, @Hackebein
I think we can close this ticket
