### ISSUE TITLE
Update/Add CMake 3.18.1 in Android SDK

### ISSUE THREAD

**Issue by atsushieno** [actions/virtual-environments#2228]
**Tool information**
- Tool name: CMake 3.18.1 in Android SDK components
- Tool license: Apache2
- Add or update?: maybe it is an "update" ?
- Desired version: it is fixed to 3.18.1 (provided by Android SDK)
- Approximate size: 50MB-ish in uncompressed state

**Area for Triage**: Android

**Question, Bug, or Feature?**: Feature

**Virtual environments affected**
- [x] Ubuntu 16.04
- [x] Ubuntu 18.04
- [x] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11.0
- [x] Windows Server 2016 R2
- [x] Windows Server 2019

**Can this tool be installed during the build?**

No on Linux. Maybe no on Windows. Maybe yes on macOS (CMakes are not installed there on existing images either).

**Tool installation time in runtime**

no right idea.

**Are you willing to submit a PR?**

I come up with a PR.

**Comment by atsushieno** [comment]
Additional Information: CMake 3.18 is actually REQUIERD at the moment wherever the Android project builds native libs and it does not specify CMake version.

The related Android issue I reported: https://issuetracker.google.com/issues/175241013

**Comment by atsushieno** [comment]
I wrote "no" to "can be installed during the build" question, but I'm not sure about what this actually means - if we write some tricky setup scripts then it is maybe doable. It cannot be automatically done in standard manner, hence my general answer.

**Comment by maxim-lobanov** [comment]
Closing related issue according to https://github.com/actions/virtual-environments/pull/2229#issuecomment-743186160

**Comment by ggfan** [comment]
CMake 3.18.1 is in stable channel, may you kindly add it into the virtual environment?

The installation command seems to work:
   `echo y | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "cmake;3.18.1"`

**Comment by miketimofeev** [comment]
@ggfan could you please open a new issue?

**Comment by ggfan** [comment]
done: https://github.com/actions/virtual-environments/issues/3321
Thank you!
