### ISSUE TITLE
Packer Build Hanging on Install-VS.ps1 Script

### ISSUE THREAD

**Issue by thepaulmacca** [actions/virtual-environments#2231]
**Description**  
I'm running `packer build` locally using the windows2019.json template, and at the **Install-VS.ps1** step, it's been hanging at `starting install...` for the best part of a few hours now. Is this expected behaviour?

I'd also like to have a rough idea of how long this image creation should take if possible, so i know whether to just be patient, or come to the conclusion that something's failed in the process. Seems to be taking a *very* long time, but understand that it's also installing a lot of software

Thanks

**Area for Triage**:  
Scripting and command line

**Question, Bug, or Feature?**:  
Question

**Virtual environments affected**  
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [X] Windows Server 2019

**Expected behavior**  
Script to continue past the Install-VS.ps1 step after a short period of time

**Actual behavior**  
Script hanging at the Install-VS.ps1 step

**Repro steps**  
A description with steps to reproduce the issue. If your have a public example or repo to share,
please provide the link.

1. Rub `packer build` locally using the windows2019.json template
2. Wait until it gets to the Install-VS.ps1 step

![image](https://user-images.githubusercontent.com/41340540/101764395-ee942d00-3ad7-11eb-82d8-bbdf4ea0a2c9.png)

**Comment by al-cheb** [comment]
Hello, @thepaulmacca 
Image creation for Windows Server 2019 takes more than 7 hours, e.g. the latest build in our repo was [7h 11m] - https://github.visualstudio.com/virtual-environments/_build/results?buildId=91772&view=results

Now you can see how much time each steps take - https://github.visualstudio.com/virtual-environments/_build/results?buildId=91772&view=logs&j=011e1ec8-6569-5e69-4f06-baf193d1351e&t=8b69240d-5eca-52e7-db53-21813d4d30a5

```
- 00:27:14 | ./scripts/Installers/Finalize-VM.ps1
- 01:01:34 | ./scripts/Installers/Install-VS.ps1
- 01:14:21 | ./scripts/Installers/Install-DotnetSDK.ps1
```

With fast internet and disk speed the Install-VS.ps1 script takes:
`- 01:01:34 | ./scripts/Installers/Install-VS.ps1`

**Comment by thepaulmacca** [comment]
Hi @al-cheb thanks for the quick reply! Wow so i am being impatient then 😃

Thanks for those links, they provide some good insight, and didn't realise i could view the yml files being used so i can create this pipeline in my own org aswell!

I'd be looking to use the generated VHD to create a VM Scale Set so we're using agents dynamically, is this possible?

**Comment by al-cheb** [comment]
@thepaulmacca , some helpful links abos vmss you can found - https://github.com/actions/virtual-environments/issues/1837

1. https://github.com/actions/virtual-environments/blob/main/help/CreateImageAndAzureResources.md
2. https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/scale-set-agents?view=azure-devops

**Comment by thepaulmacca** [comment]
Thanks @al-cheb i'll take a look. Appreciate your help 👍
