### ISSUE TITLE
Missing bash version in software installed reference 

### ISSUE THREAD

**Issue by mik-laj** [actions/virtual-environments#2232]
Hello,

The documentation does not describe the version of bash that is installed on virtual machines.
https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-README.md
https://docs.github.com/en/free-pro-team@latest/actions/reference/specifications-for-github-hosted-runners#supported-software

And different versions have different compatibility issues, so I sometimes need to check what version is installed.

Related: https://github.com/apache/airflow/pull/12967

**Comment by al-cheb** [comment]
Hello, @mik-laj 
Would you like to submit a PR for Windows and Linux with bash version?

**Comment by mik-laj** [comment]
@al-cheb  Unfortunately, I have no experience with PS1, so I cannot do that.

**Comment by al-cheb** [comment]
@mik-laj, Thank you. We will prepare a PR with your request soon.

**Comment by mik-laj** [comment]
@al-cheb  Is Bash installed on Mac OS?

**Comment by al-cheb** [comment]
@mik-laj, Yep, documentation for all images(Linux,Windows,macOS) will be updated.

**Comment by al-cheb** [comment]
@mik-laj, The software refrence files for Windows/Ubuntu have been updated and now provided bash version.
