### ISSUE TITLE
Add windows:1809 to the list of cached docker image on the Windows build agent

### ISSUE THREAD

**Issue by LaurentGoderre** [actions/virtual-environments#2233]
**Tool information**
- Tool name: Windows image (pre-cached)
- Add or update? add
- Desired version: windows:1809
- Approximate size: 13gb

**Area for Triage**:

**Question, Bug, or Feature?**:
"Feature"

**Virtual environments affected**
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [x] Windows Server 2019

**Can this tool be installed during the build?**
Yes, but the purpose of this request is to not download 4gb every build.

**Tool installation time in runtime**
10+ minutes

**Comment by maxim-lobanov** [comment]
Hello @LaurentGoderre , thank you for your proposal.
Unfortunately, we can't afford bake more docker images into Hosted images for now. We are limited in free space on images and adding 13Gb more will reduce free space that we provide on clean image for customers.
We will be happy to revisit it later if we switch to larger disks for Hosted images but not sure when it will happen
