### ISSUE TITLE
GenerateResourcesAndImage doesn't allow automation

### ISSUE THREAD

**Issue by spowser** [actions/virtual-environments#2236]
We are trying to create a pipeline around the scripts that are provided in the [documentation](https://github.com/actions/virtual-environments/blob/main/help/CreateImageAndAzureResources.md).  The challenge is that GenerateResourcesAndImage.ps1 has a call to Connect-AzAccount which prompts for authentication.

The request is to allow parameters be passed in to allow this script to be used in a CI environment

**Comment by al-cheb** [comment]
Hello, @spowser 
You should create a custom script based on script which we provide in the documentation. As an example in the [build-image.ps1](https://github.com/actions/virtual-environments/blob/main/images.CI/linux-and-win/build-image.ps1) script we use in a CI:
https://www.packer.io/docs/builders/azure/arm
`client_id (string) - The Active Directory service principal associated with your builder.`

If you want to use Connect-AzAccount in the CI:
1. [create-an-azure-active-directory-application](https://docs.microsoft.com/en-us/azure/active-directory/develop/howto-create-service-principal-portal#create-an-azure-active-directory-application)
2. [create-an-azure-active-directory-application](https://docs.microsoft.com/en-us/azure/active-directory/develop/howto-create-service-principal-portal#option-2-create-a-new-application-secret)
3. Use secrets(prefer use a certificate)

```
$azureAplicationId = "<your ad app application id>"
$azureTenantId = "<your tenant id>"
$azurePassword = ConvertTo-SecureString "<the secret of your ad app>" -AsPlainText -Force
$credential = New-Object System.Management.Automation.PSCredential($azureAplicationId , $azurePassword)
Connect-AzAccount -ServicePrincipal -TenantId $azureTenantId  -Credential $credential
```

[Sign in with Azure PowerShell](https://docs.microsoft.com/en-us/powershell/azure/authenticate-azureps?view=azps-5.2.0)
[Create an Azure service principal with Azure PowerShell](https://docs.microsoft.com/en-us/powershell/azure/create-azure-service-principal-azureps?view=azps-5.2.0)
[Azure PowerShell context objects](https://docs.microsoft.com/en-us/powershell/azure/context-persistence?view=azps-5.2.0)
