### ISSUE TITLE
Update Rust version

### ISSUE THREAD

**Issue by caulagi** [actions/virtual-environments#224]
**Tool information**
- Tool name: Rust
- Add or update? Update
- Desired version: 1.40
- Approximate size: 
- If this is an add request:
  - Brief description of tool: 
  - URL for tool's homepage: 

**Area for Triage**: Rust

**Question, Bug, or Feature?**: Bug

**Virtual environments affected**
- [ ] macOS 10.15
- [x] Ubuntu 16.04 LTS
- [x] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Can this tool be installed during the build?**

**Are you willing to submit a PR?**
This doesn't require a PR. It seems to me that just running the install script for Linux should suffice.

**Comment by caulagi** [comment]
**Area for Triage**: Rust

**Comment by MikailBag** [comment]
I think that both stable and nightly should be installed.

**Comment by kaylangan** [comment]
We pull the latest version of Rust available when we generate the image. This update is rolling out at the moment.

**Comment by alepauly** [comment]
confirmed deployed.
