### ISSUE TITLE
brew update/brew upgrade failing with Error: Not a directory @ dir_s_rmdir error strikes back

### ISSUE THREAD

**Issue by traversaro** [actions/virtual-environments#2248]
**Description**  
On some scheduled jobs on macOS, since a few hours the `brew update` and `brew upgrade` commands are failing. 

**Area for Triage**:  

**Question, Bug, or Feature?**:  
Bug 

**Virtual environments affected**  
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [x] macOS 10.15
- [x] macOS 11.0
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Expected behavior**  
The commands: 
* `brew update` 
* `brew upgrade` 

Should work fine.

**Actual behavior**  
* `brew update` 
* `brew upgrade` 
commands fail with error:
~~~
2020-12-11T14:20:31.2785670Z [34m==>[0m [1mPouring openssl@1.1-1.1.1i.catalina.bottle.tar.gz[0m
2020-12-11T14:21:54.9827160Z [31mError:[0m Not a directory @ dir_s_rmdir - /usr/local/Cellar/openssl
2020-12-11T14:21:54.9844860Z [34m==>[0m [1mCaveats[0m
~~~

See for example https://github.com/robotology/robotology-superbuild/runs/1534684566?check_suite_focus=true . 

**Repro steps**  
A description with steps to reproduce the issue. If your have a public example or repo to share,
please provide the link.

1. Run `brew update`
2. Run `brew upgrade`

**Comment by traversaro** [comment]
This is probably related to the similar older bug (that was however solved) https://github.com/actions/virtual-environments/issues/1811 .

cc @Nicogene

**Comment by miketimofeev** [comment]
Hi @traversaro!
Yes, this is related and fixed recently, however, the new image is not yet deployed. We're going to deploy the image next week.
As a workaround, you can add one more line before updating and upgrading.
```
brew uninstall openssl@1.0.2t
brew update
brew upgrade
```

**Comment by traversaro** [comment]
Thanks @miketimofeev ! If you agree, I think it would be nice to keep the issue open until the images are deployed, for better visibility for users that may have this problem, thanks!

**Comment by traversaro** [comment]
Since ~24 hours the workaround provided in https://github.com/actions/virtual-environments/issues/2248#issuecomment-743235054 is still necessary in macOS 10.15 machine, while it is not necessary (and actually it breaks the build) in macOS 11.0 . Is this due to the time necessary for the deployment, or it is intended difference between the two images? Thanks a lot!

**Comment by maxim-lobanov** [comment]
@traversaro , We are deploying new image with fix right now.
MacOS 11.0 has been already deployed (it takes little time).
MacOS 10.15 is still in process and should be deployed in 1 day

**Comment by traversaro** [comment]
Thanks for the quick reply!

**Comment by miketimofeev** [comment]
@traversaro the new image has been deployed, everything works without workarounds now.
I'm going to close the issue, but please feel free to contact us if you have any concerns, thank you!

**Comment by traversaro** [comment]
> 
> 
> @traversaro the new image has been deployed, everything works without workarounds now.
> I'm going to close the issue, but please feel free to contact us if you have any concerns, thank you!

Thanks a lot for the great support!
