### ISSUE TITLE
Update Terraform to v0.14.2+

### ISSUE THREAD

**Issue by frli** [actions/virtual-environments#2249]
**Tool information**
- Tool name: Terraform
- Add or update? update?
- Desired version: v0.14.2+

**Virtual environments affected**
- [x] Ubuntu 16.04
- [x] Ubuntu 18.04
- [x] Ubuntu 20.04
- [x] macOS 10.15
- [x] macOS 11.0
- [x] Windows Server 2016 R2
- [x] Windows Server 2019

The currently bundled version (v0.13.5) is incompatible with terraform state files generated by 0.14.2.
>Error: Error loading state: state snapshot was created by Terraform v0.14.2, which is newer than current v0.13.5; upgrade to Terraform v0.14.2 or greater to work with this state
 
Thanks for doing an excellent job bundling all kinds of nifty things on these images!

**Comment by maxim-lobanov** [comment]
@frli , On Ubuntu images, we always install the latest version of terraform on image-generation so no actions are required from our side. New images with latest version of terraform (0.14.2) will be deployed during next week.

You also mentioned Windows and macOS images but for now we don't install terraform on these images. Are you proposing to install it?

**Comment by maxim-lobanov** [comment]
Also, I suggest to consider using [official terraform action](https://github.com/marketplace/actions/hashicorp-setup-terraform). It allows to install specific version in runtime and it takes just a couple of seconds. One more benefit is that you can specify exact version and future breaking changes won't affect you (since we always pre-cache latest version on image, sometimes it happens)

**Comment by frli** [comment]
Slightly off topic but you know if there is there any corresponding official task for Terraform installation for Azure devops pipelines? Hashicorp themselves do not appear to provide one in the marketplace and the one from Microsoft Devlabs seems very out of date.

[This one](https://marketplace.visualstudio.com/items?itemName=charleszipp.azure-pipelines-tasks-terraform&ssr=false#overview) by Charles Zipp seems to contain a separate task for terraform installation (although the rest of the tasks in the extension seems very focused on deploying things purely to Azure).

**Comment by maxim-lobanov** [comment]
@frli, I am not aware about any Azure DevOps task for it but you can setup any version in runtime using the following code:
```
TERRAFORM_VERSION="0.14.2"
curl -LO "https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip"
unzip "terraform_${TERRAFORM_VERSION}_linux_amd64.zip"
sudo rm -f "/usr/local/bin/terraform"
sudo mv terraform /usr/local/bin/terraform
```

**Comment by miketimofeev** [comment]
@frli the new Ubuntu images were deployed with Terraform 0.14.2 on board.
I'm going to close the issue, but please feel free to contact us if you have any concerns.
Thank you!
