### ISSUE TITLE
Question: different versions of a tool under different versions of an environment

### ISSUE THREAD

**Issue by paulo-ferraz-oliveira** [actions/virtual-environments#2251]
I'm using GitHub Actions over different Erlang/OTP versions, and `rebar3` to support compiling and testing. I've not yet understood how `rebar3` is available in different environments in different versions e.g. OTP 19.3 has `rebar3` 3.8.0 and OTP 22.3 has rebar3 `3.14.3`, especially since I haven't found any doc. on how the virtual environments are build/fetched - is it Docker hub, daily? is it manually, but updating something somewhere?

Any help would be much appreciated.

**Comment by maxim-lobanov** [comment]
Hello @paulo-ferraz-oliveira ,
Currently, we install `rebar3` only on Ubuntu images and all Ubuntu images contains `rebar 3.14.2 on Erlang/OTP 23 Erts 11.1`

**Comment by paulo-ferraz-oliveira** [comment]
Thanks for your reply.

I'm still missing something, though.

1. if I use `container` (in my YAML) what is the origin for the container (is it some internal mirror? Is it Docker Hub?)?
2. I'm not getting rebar 3.14.2, but 3.14.3, so I might be looking for this in the wrong place (as explained in my initial message).
3.`container: image: erlang:${{matrix.otp_vsn}}` is the container I'm using to target a specific Erlang version

Cheers.

**Comment by paulo-ferraz-oliveira** [comment]
Thanks for your reply.

I'm not using the stock elements from `ubuntu-latest` but rather a container (e.g. `erlang:19.3`) so I figure this is probably not the proper forum to ask this question.

In any case, your reply advances my knowledge.
