### ISSUE TITLE
Upgrade Android SDK tools from deprecated "SDK Tools" to new "Command Line Tools"

### ISSUE THREAD

**Issue by remyjette** [actions/virtual-environments#2252]
**Tool information**
- Tool name: Android Command Line Tools
- Tool license: https://developer.android.com/studio/terms
- Add or update? Update
- Desired version: latest
- Approximate size: Command line tools zip file is 83 MB. Unsure of size on disk.

**Area for Triage**:
Android

**Question, Bug, or Feature?**:
Feature

**Virtual environments affected**
- [ X ] Ubuntu 16.04
- [ X ] Ubuntu 18.04
- [ X ] Ubuntu 20.04
- [ X ] macOS 10.15
- [ X ] macOS 11.0
- [ X ] Windows Server 2016 R2
- [ X ] Windows Server 2019

Virtual environments currently installs Android "SDK Tools", which is deprecated: https://developer.android.com/studio/releases/sdk-tools

Google suggests using the new "cmdline-tools" package instead:
https://developer.android.com/studio/command-line

The updated `sdkmanager` also supports newer versions of Java, so the workaround to set Java 8 explicitly in https://github.com/actions/virtual-environments/blob/main/images/linux/scripts/installers/android.sh would no longer be required.

**Comment by maxim-lobanov** [comment]
No concerns to add it to the images. Moved to the backlog

**Comment by maxim-lobanov** [comment]
@remyjette do you know if it will be a breaking change to update "SDK Tools" to "Command Line Tools"?

**Comment by remyjette** [comment]
My initial thought when I created this issue was that it's an update, as it would switch to the latest version of these packages.

However `cmdline-tools` also installs to a new path by default (`$ANDROID_SDK_ROOT/cmdline-tools` rather than `$ANDROID_SDK_ROOT/tools`, and some of the tools have been split out into separate packages like `build-tools` and `platform-tools`). So scripts relying on the old tools at the old path would no longer find them if they were to be removed.

"SDK Tools" and "Command Line Tools" can be installed side-by-side, so we could instead treat this as a new tool rather than a tool update and simply install both for the time being.

**Comment by maxim-lobanov** [comment]
Thank you for additional information! It is very useful since we don't have much experience with Android.

As for the installing side by side,
Currently, we download SDK Tools via link like https://dl.google.com/android/repository/sdk-tools-darwin-3859397.zip. Command Line tools can be downloaded via https://dl.google.com/android/repository/commandlinetools-mac-6858069_latest.zip
So I guess we can:
- Download both and install them to the same folder (they will be installed side by side)
- install SDK Tools and then install cmdline-tools using sdkmanager provided by SDK Tools

**Comment by dsame** [comment]
@remyjette do you think anybody needs to have the previous versions of the command line tools or the latest one is good for everyone?

**Comment by remyjette** [comment]
As mentioned above, `cmdline-tools` has a new default path underneath `$ANDROID_SDK_ROOT`.

I would imagine that there are projects which have hardcoded `$ANDROID_SDK_ROOT/tools/bin` which would need to be updated to `$ANDROID_SDK_ROOT/cmdline-tools/latest/bin` to use the new tools.

**Comment by dsame** [comment]
@remyjette my opinion it is not good idea to switch the clients to another version without their will. I'll add the documentation note

**Comment by EwoutH** [comment]
Great that this is being worked on!

**Comment by miketimofeev** [comment]
@remyjette we've finished image deployments with command line tools on board. I'm going to close the issue, but please feel free to contact us if you have any concerns.
Thank you!
