### ISSUE TITLE
Add XcodeGen

### ISSUE THREAD

**Issue by stihl-fritz** [actions/virtual-environments#2260]
**Tool information**
- Tool name: XcodeGen
- Tool license: MIT
- Add or update? Add
- Desired version: Latest (currently 2.18.0)
- Approximate size: ~10 MB
- If this is an add request:
  - Brief description of tool: XcodeGen is a command line tool written in Swift that generates your Xcode project using your folder structure and a project spec.
  - URL for tool's homepage: https://github.com/yonaskolb/XcodeGen
  - Provide a basic test case to validate the tool's functionality: See https://github.com/yonaskolb/XcodeGen/blob/master/Docs/Usage.md

**Area for Triage**:
Apple, Xcode

**Question, Bug, or Feature?**:
Feature

**Virtual environments affected**
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [x] macOS 10.15
- [x] macOS 11.0
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Can this tool be installed during the build?**
Yes.
```
$ brew tap yonaskolb/XcodeGen https://github.com/yonaskolb/XcodeGen.git
$ brew install xcodegen
```

**Tool installation time in runtime**
~2-3 minutes

**Are you willing to submit a PR?**
Yes.

**Comment by AlenaSviridenko** [comment]
Hey @stihl-fritz ,
tool installation time in runtime is 13 seconds by `brew install xcodegen` which is a pretty small amount of time. Usually we are trying not to pre-install such small tools on image. Also, there is an action for it [actions/xcodegen](https://github.com/marketplace/actions/xcodegen), will it fit your needs?

**Comment by stihl-fritz** [comment]
Hi @AlenaSviridenko

that's interesting.🤔 Installing the tool takes about 1 Minute (69s) for me. Therefor I thought it would safe some time to not do it on every pipeline run.

I call the xcodegen installation directly from a fastlane "script". Do you think this could explain the delta (69s-13s=56s)? Could try to install xcodegen in it's own step and then just call it from fastlane and see if it makes a difference.

Unfortunately [actions/xcodegen](https://github.com/marketplace/actions/xcodegen) is not an option for our setup.

Here's an excerpt of my log:
```
[11:53:36]: Installing XcodeGen
[11:53:36]: $ brew tap yonaskolb/XcodeGen https://github.com/yonaskolb/XcodeGen.git
...
[11:54:45]: ▸ 🍺  /usr/local/Cellar/xcodegen/2.18.0: 29 files, 9.7MB
```

**Comment by AlenaSviridenko** [comment]
yeah, that could be the reason, please, check installation in a separate step. 
![image](https://user-images.githubusercontent.com/8777209/102085744-1b25ad00-3e28-11eb-90d1-bb29c5596853.png)

Anyway, since the installation time is small for XcodeGen, I am going to close this issue. 
Please, feel free to create a new one in case if any other help is needed. Thanks.
