### ISSUE TITLE
Intermittent Network Errors Connecting to `vault.centos.org`

### ISSUE THREAD

**Issue by charlespierce** [actions/virtual-environments#2264]
**Description**  
Starting today, I am seeing failures to connect to `vault.centos.org` during `docker build` with the error: "Cannot assign requested address"

**Area for Triage**:  

Servers

**Question, Bug, or Feature?**:  

Bug

**Virtual environments affected**  
- [X] Ubuntu 16.04
- [X] Ubuntu 18.04
- [X] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Expected behavior**  
`docker build` Completes successfully and can access the internet to update / install fresh packages.

**Actual behavior**  
During the `yum -y update` step of `docker build`, the command fails with the error message:
```
http://vault.centos.org/6.10/os/x86_64/repodata/repomd.xml: [Errno 14] PYCURL ERROR 7 - "Failed to connect to 2600:1f13:2e7:2901:d2b0:c3b2:9347:934c: Cannot assign requested address"
```
All the information I could find on that error message indicates that it is a networking problem. I'm able to access the above URL directly, so it doesn't appear to be an issue with the source. Additionally, this exact setup worked consistently before today, and no changes were made (other than swapping the environment to test if that would have an impact (it didn't).

**Repro steps**  
This is happening on a CentOS 6 Docker image during the `docker build` stage. The repo is: https://github.com/volta-cli/volta and you can see the failing jobs here:

* https://github.com/volta-cli/volta/actions/runs/422143760
* https://github.com/volta-cli/volta/actions/runs/422199976

**Comment by andy-mishechkin** [comment]
Hello, @charlespierce 
I see here: https://github.com/volta-cli/volta/actions?query=workflow%3AProduction, your other builds had a successful connections to 'vault.centos.org'. Perhaps it was a temporary connection issue.
Have you still get these connection issues in the last time ?
Thank you.

**Comment by charlespierce** [comment]
Hi @andy-mishechkin, it does seem to be fixed this morning. Yesterday it resolved itself for a while and then came back, which is why I opened the issue, but it's working again today. Feel free to close, thanks!

**Comment by andy-mishechkin** [comment]
Thank you, closed

**Comment by charlespierce** [comment]
Hi @andy-mishechkin, this happened again today. Re-running the job a few minutes after the failure didn't change anything, but now several hours later it appears to be working. Given that it's intermittent, I don't expect there's enough to go on to determine what is happening, but the fact that it popped up again seems relevant.

**Comment by gliptak** [comment]
I also observed at https://github.com/gliptak/python-snappy/runs/5192552115?check_suite_focus=true
