### ISSUE TITLE
Bind all the repos to their public key files

### ISSUE THREAD

**Issue by KOLANICH** [actions/virtual-environments#227]
**Describe the bug**
https://wiki.debian.org/DebianRepository/UseThirdParty prescribes to bind all the third party repos to their key files. IMHO it makes sense to do so for all the repos. I have even written [a tool](https://gitlab.com/KOLANICH/AptSourcesHardener.py) for doing so.

**Area for Triage**: 

**Question, Bug, or Feature?**: Bug

**Virtual environments affected**
- [x] Ubuntu 16.04 LTS
- [x] Ubuntu 18.04 LTS

**Expected behavior**
All the repos should be pinned.

**Actual behavior**
They are mostly not.

**Comment by al-cheb** [comment]
Hello, @KOLANICH 
I don't see any pros to use this kind of tools. Only cons:
1.  Depend on third party unsupported tools/library
2.  No security benefits
3.  Increase maintenance effort
4.  Can break customer CI
5.  Apply unnecessary restrictions to customers
6.  Cannot be applied at runtime
7. Every changes request rerun script
8. Don't prevent from poorly configured third party repos


https://wiki.debian.org/DebianRepository/UseThirdParty - `Note that the procedures documented here aim to prevent a repository from shipping packages that the administrator does not expect that repository to ship. For example, a repo that ships a video game emulator and its mods shouldn't be able to override libc6.
However, the installation of any single malicious package from a malicious repository can currently undo these protections, for example by running a MaintainerScripts command to override the configured preferences or by authorizing new OpenPGP keys. For the purposes of this page, attacks by a package that belongs to a given repository are out of scope. To restrict what an installed package can do, see the larger UntrustedDebs problem, and particularly Teams/Dpkg/Spec/DeclarativePackaging for a potential solution.
`

**Comment by miketimofeev** [comment]
@KOLANICH Close this issue for now but feel free to reopen if you have any concerns.
Thank you for your suggestions!
