### ISSUE TITLE
Add pnpm

### ISSUE THREAD

**Issue by autumnblazey** [actions/virtual-environments#2279]
**Tool information**
- Tool name: pnpm
- Tool license: MIT
- Add or update? add
- Desired version: latest (but dont update randomly, obviously)
- Approximate size: 10.9MB unpacked (according to npm)
- If this is an add request:
  - Brief description of tool: performant npm/yarn alternative for managing node.js dependencies
  - URL for tool's homepage: https://pnpm.js.org/
  - Provide a basic test case to validate the tool's functionality: 

**Area for Triage**:

JavaScript and Node.js

**Question, Bug, or Feature?**:

feature

**Virtual environments affected**
- [X] Ubuntu 16.04
- [X] Ubuntu 18.04
- [X] Ubuntu 20.04
- [X] macOS 10.15
- [X] macOS 11.0
- [X] Windows Server 2016 R2
- [X] Windows Server 2019

**Can this tool be installed during the build?**

yes
1. use this action somewhere in the build process https://github.com/marketplace/actions/setup-pnpm
2. its added to the path, so you can use it as if you did a npm global install (can run `pnpm install` for example)

**Tool installation time in runtime**

~3-5 seconds

**Are you willing to submit a PR?**

not completely sure how the runner works so I'll have to take a look around in the repo, but I'm willing to PR

**Comment by AlenaSviridenko** [comment]
Hi @autumnblazey, 
given the small installation time in runtime and the existence of action with a wider functionality where you can select which version you want to use, we'd prefer not to pre-install this tool on images.
Usage of action is more safe and reliable way to install and use any tool that will guarantee that your workflow won't be broken with unexpected tool upgrade.

I am closing this issue. Please, feel free to create a new one in case if any other help is needed.

**Comment by autumnblazey** [comment]
FYI to anyone who finds this, the action hasn't had any updates since after the add-path command was deprecated and disabled, so a workaround (for now at least) is to use the [setup node action](https://github.com/marketplace/actions/setup-node-js-environment) (it doesnt work without using this, i've tried), then running `npm i -g pnpm@version`

**Comment by nickmccurdy** [comment]
Once https://github.com/actions/setup-node/pull/482 is merged, you can use corepack instead

**Comment by autumnblazey** [comment]
that would be nice, thanks for the heads up!

**Comment by kkazala** [comment]
Since v16.13, Node.js is shipping [Corepack](https://nodejs.org/api/corepack.html) for managing package managers: https://pnpm.io/installation#using-corepack

windows-latest (2022) and ubuntu-latest (22.04) already include Node v16, so it's enough to use `corepack enable`:
```yaml
pool:
  vmImage: 'ubuntu-latest'
  demands:
  - npm
  - node.js

steps:
- powershell: |
    Write-Host "node: $(node --version)"
    corepack enable
    Write-Host "npm: $(npm --version)"
    Write-Host "pnpm: $(pnpm --version)"
  name: install_Software
```

prints out:
```bash
node: v16.17.0
npm: 8.15.0
pnpm: 7.5.2

```
