### ISSUE TITLE
Windows, Ruby, MSYS2 update/install

### ISSUE THREAD

**Issue by MSP-Greg** [actions/virtual-environments#229]
1. Please see https://github.com/actions/virtual-environments/issues/30

2. Windows currently has three old Rubies, all with embedded MSYS2 installs.

3. Windows Rubies are self contained and have all the dll's needed to run the code contained in them.  See the bin/ruby_builtin_dlls folder.

3. Windows Ruby releases are available at https://github.com/oneclick/rubyinstaller2/releases.  If you look at the the 2.7.0 release at https://github.com/oneclick/rubyinstaller2/releases/tag/RubyInstaller-2.7.0-1, there is the rubyinstaller-2.7.0-1-x64.7z file, which contains Ruby without the embedded MSYS2 install.  It does contain html doc files, which are not needed for most CI, if you're concerned about image size.

4. For building extension gems (which require compile tools/gcc), the Rubies have OS specific code to look for MSYS2.  A standard location is C:\msys64.

5. Lots of other software uses MSYS2 for compiling.

So, rather than have three MSYS2 installs, could we have one, located at C:/msys64?

Over the years, AppVeyor has determined that adding many packages to their images was helpful for their users' CI.  I'll not address that, but MSYS2 with current base, base-devel, and mingw-w64-x86_64-gcc would be a good start.

JFYI, a few people involved with Ruby are setting up actions to allow downloading and installing current Rubies for CI use on all platforms.

**Comment by eine** [comment]
Ref #234

**Comment by maxim-lobanov** [comment]
Recently, we have removed embedded MSYS from Ruby in scope of https://github.com/actions/virtual-environments/pull/2047
MSYS2 is available by default in C:/msys64
I think this issue can be closed for now but please let me know if you have any concerns
