### ISSUE TITLE
Azure kernel are missing from Ubuntu repo

### ISSUE THREAD

**Issue by khancyr** [actions/virtual-environments#2291]
**Description**  
Some Azure kernel were removed on Ubuntu because of securities issues like : linux-modules-extra-5.4.0-1032-azure 
see https://ubuntu.com/security/notices/USN-4658-1 
Therefor, trying to install this on Ubuntu machine failed.

**Area for Triage**:  

**Question, Bug, or Feature?**:  

Bug

**Virtual environments affected**  
- [X] Ubuntu 16.04
- [X] Ubuntu 18.04
- [X] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Expected behavior**  
Running `sudo apt-get -y install linux-modules-extra-$(uname -r)` shouldn't failed.

**Actual behavior**  
```
Hit:1 http://security.ubuntu.com/ubuntu focal-security InRelease
Hit:2 http://archive.ubuntu.com/ubuntu focal InRelease
Hit:3 http://archive.ubuntu.com/ubuntu focal-updates InRelease
Hit:4 http://archive.ubuntu.com/ubuntu focal-backports InRelease
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package linux-modules-extra-5.4.0-1032-azure
E: Couldn't find any package by glob 'linux-modules-extra-5.4.0-1032-azure'
E: Couldn't find any package by regex 'linux-modules-extra-5.4.0-1032-azure'
Error: Process completed with exit code 100.
```
Full log at : https://github.com/ArduPilot/ardupilot/runs/1562605359?check_suite_focus=true

**Repro steps**  
As simple workflow with `sudo apt-get -y install linux-modules-extra-$(uname -r)` on `runs-on: ubuntu-20.04` trigger the issue.
a complete log could be find here : https://github.com/ArduPilot/ardupilot/runs/1562605359?check_suite_focus=true and the related workflow .yaml here : https://github.com/ArduPilot/ardupilot/blob/master/.github/workflows/test_sitl_periph.yml

**Comment by Darleev** [comment]
Hello @khancyr,
I found [another topic](https://askubuntu.com/questions/1265137/avoid-missing-kernel-linux-modules-extra-xx-generic-when-updating-kernel) with the similar issue, and probably solution can help you to avoid it in your build.
Could you please try it?

We are looking forward to your reply.

**Comment by khancyr** [comment]
Hummm I can try but the issue isn't the same.
In my case, some of the tests are using a specific version of the kernel that what removed from Ubuntu, some aren't. It was working well until the start of this week. 
The docker images we are using don't have kernel stuff on them, we are doing the install inside the workflow. So in IMHO the issue come from the VM that is used for the action and not the docker image.

**Comment by al-cheb** [comment]
> Hummm I can try but the issue isn't the same.
> In my case, some of the tests are using a specific version of the kernel that what removed from Ubuntu, some aren't. It was working well until the start of this week.
> The docker images we are using don't have kernel stuff on them, we are doing the install inside the workflow. So in IMHO the issue come from the VM that is used for the action and not the docker image.

Looks like the issue is reproduced only on Ubuntu 20.04. As a temporary workaround:
```
sudo apt-get update 
sudo apt-get install crda wireless-crda
pkgName=linux-modules-extra-5.4.0-1032-azure_5.4.0-1032.33_amd64.deb
wget "http://launchpadlibrarian.net/506842029/${pkgName}"
sudo dpkg -i $pkgName
```

**Comment by al-cheb** [comment]
@khancyr, The new image version has been deployed. Feel free to open the thread if you have any concerns.
