### ISSUE TITLE
Ruby 2.6.4 support

### ISSUE THREAD

**Issue by xijo** [actions/virtual-environments#230]
Essentially the same problem as actions/setup-ruby#8.

Since `2.6.4` is a release for security reasons everyone should be able update ASAP, which gives the topic a certain urgency.

Has anyone found a way to install a specific ruby version manually?

Thanks in advance,
Jo

**Comment by eregon** [comment]
FWIW https://github.com/eregon/use-ruby-action supports all Ruby 2.6.x versions.

**Comment by alepauly** [comment]
This is done, Windows and Linux runners are now in 2.6.5
