### ISSUE TITLE
SSH tunneling in Windows Server 2019 does not seem to work

### ISSUE THREAD

**Issue by amoszheng** [actions/virtual-environments#2300]
**Description**  
When trying to use the built-in ssh command in windows-latest (Windows Server 2019) for local port forwarding, the specified ports are not being listening on or forwarded.

**Area for Triage**:  
SSH

**Question, Bug, or Feature?**:  
Question/Bug

**Virtual environments affected**  
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [x] Windows Server 2019

**Expected behavior**  
Upon issuing the ssh command and having ssh running, the ports specified in the ssh command should be listening and forwarding the packets to the destination via ssh.

**Actual behavior**  
The ports specified in the ssh command are not opened or listened locally.

**Repro steps**  
The GitHub Actions script is as follows (with the sensitive info replaced by placeholders):

    name: CD
    
    on:
      push:
        branches: [ master ]
      workflow_dispatch:
  
    jobs:
      build:
    
        runs-on: windows-latest
    
        steps:
        - name: Checkout Code
          uses: actions/checkout@v2
            
        - name: Cache Dependencies
          uses: actions/cache@v2
          id: cache-dependencies
          with:
            path: ~/.nuget/packages
            key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
        
        - name: Open SSH tunnel
          run: |
            echo "${{ secrets.SSH_KEY }}" > key.pem
            $acl = Get-Acl key.pem
            $acl.SetAccessRuleProtection($True,$False)
            $rule = New-Object System.Security.AccessControl.FileSystemAccessRule("$env:UserDomain\$env:UserName", "FullControl", "Allow")
            $acl.AddAccessRule($rule)
            Set-Acl key.pem $acl
            Start-Process ssh -ArgumentList "-tt -L 1433:<server int ip>:1433 -L 8172:<server int ip>:8172 <username>@<ssh host ip> -i key.pem"
            Start-Sleep -s 10
            Get-Process -Name ssh | echo
            netstat -an
        
        - name: Deploy to Dev
          run: |
            Get-Process -Name ssh | echo
            netstat -an
            dotnet publish -c Release `
            -p:PublishProfile=<publish profile> `
            -p:Password=${{ secrets.DEPLOY_PASSWORD }} `
            -p:AllowUntrustedCertificate=True
             
        - name: Close SSH tunnel
          run: kill -Name ssh
`
Notes:
- The commands in the script to open the SSH tunnel and do the deployment run fine locally in a Windows 10 Pro 1909 machine and I am able to build and deploy to the server from my local machine.
- The commands ` Start-Sleep -s 10`, `Get-Process -Name ssh | echo` and ` netstat -an` are for debugging purposes only. I included the ` Start-Sleep -s 10` command to account for the time taken to make the SSH connection, which when connecting to the server using a local machine takes less than 5 secs (turns out adding this command made no difference). While the `Get-Process -Name ssh | echo` command shows that the ssh process is indeed running in both the Open SSH tunnel and the Deploy to Dev steps, the ` netstat -an` command shows that the specified ports 1433 and 8172 are not being listened on locally in either step, so the deployment fails with the error 
    
    MSDEPLOY : error Code: ERROR_DESTINATION_NOT_REACHABLE
    MSDEPLOY : error : Unable to connect to the remote server
    MSDEPLOY : error : No connection could be made because the target machine actively refused it 127.0.0.1:8172 

Is there something wrong in my code, or something else that I should/shouldn't have done to make SSH tunneling work? Any help would be greatly appreciated.

**Comment by dsame** [comment]
@amoszheng i suppose you use ssh tunnel to communicate between the processes on the same host. Can you please try to use localhost instead of network interfaces addresses. I am not sure right now but there's high probability the opening listen sockets are disable on agent hosts.

Also, can you intercept the output of ssh server, please?

**Comment by amoszheng** [comment]
> 
> 
> @amoszheng i suppose you use ssh tunnel to communicate between the processes on the same host. Can you please try to use localhost instead of network interfaces addresses. I am not sure right now but there's high probability the opening listen sockets are disable on agent hosts.
>

Correct me if I am wrong, but localhost would resolve to 127.0.0.1 as well, right?

> Also, can you intercept the output of ssh server, please?

Could you give me instructions on how to do that without interrupting the main process?

**Comment by Darleev** [comment]
Hello @amoszheng,
You are right, localhost resolves to 127.0.0.1. I verified it using the folowing commands on agents:

```
ping localhost
Pinging WIN-61K18E5PQA9 [::1] with 32 bytes of data:
Reply from ::1: time<1ms 
Reply from ::1: time<1ms 
Reply from ::1: time<1ms 
Reply from ::1: time<1ms 
ping localhost -4 
Pinging WIN-61K18E5PQA9 [127.0.0.1] with 32 bytes of data:
Reply from 127.0.0.1: bytes=32 time=1ms TTL=128
Reply from 127.0.0.1: bytes=32 time<1ms TTL=128
Reply from 127.0.0.1: bytes=32 time<1ms TTL=128
Reply from 127.0.0.1: bytes=32 time<1ms TTL=128
```
I've tried to reproduce the issue on the agent's side, and it seems it's not possible to open the local socket on agent machines. I tried to add additional flags to ssh command -vvv and to Start-Process command "-Verb open", but there is no additional information about what is causing the issue.
We are investigating the issue.

**Comment by Darleev** [comment]
@amoszheng since Start-Process starts ssh in background mode it's really hard to get logs from there. So, I suggest to start ssh without "Start-Process" just for debugging purposes with -vvv flag, in order to understand why local sockets do not work.

We are looking forward to your reply.

**Comment by amoszheng** [comment]
@Darleev I found what the problem was. Since every workflow run on GitHub runners happens in a fresh VM, there was no known_hosts file, so every time ssh is called it is stuck in the ssh prompt

    The authenticity of host <host ip> can't be established.
    RSA key fingerprint is <fingerprint>.
    Are you sure you want to continue connecting (yes/no)?

So a solution that worked for me was creating a new SSH_KNOWN_HOSTS secret and adding the following before the ssh command:

    mkdir ~/.ssh
    echo "${{ secrets.SSH_KNOWN_HOSTS }}" > ~/.ssh/known_hosts

Since the server fingerprint is probably not a secret, it could also be defined in an environment variable or hard-coded in the Action code instead of being stored in a GitHub secret. 

An [alternative](https://superuser.com/questions/125324/how-can-i-avoid-sshs-host-verification-for-known-hosts) would be to add the argument `-o "StrictHostKeyChecking no"` to the ssh command, but that would make the script susceptible to ssh MITM attacks.

Thanks for all the help troubleshooting the issue!
