### ISSUE TITLE
Sed Command in PowerShell?

### ISSUE THREAD

**Issue by thepaulmacca** [actions/virtual-environments#2301]
Hi i'm hoping someone can help me. I'm building a self-hosted agent using some of these scripts, but when trying to run a sed command in Azure CLI (PowerShell), i'm getting a `sed : The term 'sed' is not recognized as the name of a cmdlet, function, script file, or operable program` error

Can someone advise what scripts i need to run on my agent to get this working please? I'm not building the full image as i'm trying to keep the footprint as small as possible. Just need some insight on how it's configured on the hosted agents really

Thanks

**Comment by maxim-lobanov** [comment]
@thepaulmacca , what image do you build? Windows or Linux one?

**Comment by thepaulmacca** [comment]
Sorry @maxim-lobanov i should've mentioned that! I'm building a Windows 2019 one

**Comment by al-cheb** [comment]
@thepaulmacca, add `C:\Program Files\Git\usr\bin\` to PATH where `sed` util is stored.

```
PS > $env:Path += ";C:\Program Files\Git\usr\bin"
PS > Get-Command sed

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Application     sed.exe                                            0.0.0.0    C:\Program Files\Git\usr\bin\sed.exe
```

**Comment by thepaulmacca** [comment]
@al-cheb thanks very much i'll give that a go 👍
