### ISSUE TITLE
Add pass credential helper

### ISSUE THREAD

**Issue by crazy-max** [actions/virtual-environments#2302]
**Tool information**
- Tool name: pass
- Tool license: GPLv2
- Add
- Desired version: Nothing specific. The one from standard apt repo is ok.
- Approximate size:
- If this is an add request:
  - Brief description of tool: The standard unix password manager
  - URL for tool's homepage: https://www.passwordstore.org/
  - Provide a basic test case to validate the tool's functionality:

**Area for Triage**:

**Feature**:

We need a standard [credential store](https://docs.docker.com/engine/reference/commandline/login/#credentials-store) like [`pass` credential helper](https://www.passwordstore.org/) on Ubuntu GitHub Runners to handle Docker login in a safest way (see docker/login-action#30). Otherwise credentials are stored unencrypted:

```
🔑 Logging into docker.pkg.github.com...
WARNING! Your password will be stored unencrypted in /home/runner/.docker/config.json.
Configure a credential helper to remove this warning. See
https://docs.docker.com/engine/reference/commandline/login/#credentials-store
```

**Virtual environments affected**
- [x] Ubuntu 16.04
- [x] Ubuntu 18.04
- [x] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Can this tool be installed during the build?**

**Tool installation time in runtime**

**Are you willing to submit a PR?**

**Comment by maxim-lobanov** [comment]
Hello @crazy-max ,  we don't have objections to bake this tool into the image. Do you want to submit PR?

**Comment by crazy-max** [comment]
Hi @maxim-lobanov, sure!

**Comment by maxim-lobanov** [comment]
@crazy-max , thank you for contribution! I have merged PR.
Unfortunately, these changes will be deployed only in January since we have deployment freeze next 2 weeks

**Comment by crazy-max** [comment]
@maxim-lobanov Great thanks!

**Comment by crazy-max** [comment]
@maxim-lobanov 

> Unfortunately, these changes will be deployed only in January since we have deployment freeze next 2 weeks

As a side note it would be nice to have staging runners (eg. `ubuntu-latest-preview`) allowed for specific users (like GitHub Actions developers) to be able to make some tests and give you some feedback before deployment.

**Comment by maxim-lobanov** [comment]
@crazy-max , if you don't mind, let's keep issue opened until deployment is finished

**Comment by miketimofeev** [comment]
@crazy-max Ubuntu 20 with pass 1.7.3 on board was deployed https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-README.md#tools
I'm going to close the issue but please feel free to contact us if you have any concerns.
Thanks for your contribution!
