### ISSUE TITLE
Update/Add AzTable PowerShell module

### ISSUE THREAD

**Issue by vexingpos** [actions/virtual-environments#2306]
**Tool information**
- Tool name: AzTable (PowerShell module)
- Tool license: MIT
- Add or update? Add
- Desired version: latest (v2.0.3 at time of writing)
- Approximate size: unknown
- If this is an add request:
  - Brief description of tool: Set of cmdlets to add/retrieve/update entities on Azure Table Storage using PowerShell
  - URL for tool's homepage: https://www.powershellgallery.com/packages/AzTable/2.0.3
  - Provide a basic test case to validate the tool's functionality: `New-AzStorageTable –Name $tableName –Context $ctx`

**Area for Triage**:
Scripting and command line

**Question, Bug, or Feature?**:
Feature

**Virtual environments affected**
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11.0
- [x] Windows Server 2016 R2
- [x] Windows Server 2019

**Can this tool be installed during the build?**
Yes. To the best of my understanding, all that needs to be done is adding an entry for AzTable in the `images/win/toolsets/toolset-2019.json` and `images/win/toolsets/toolset-2016.json` files under the `powershellModules` section. Is this correct? 

**Tool installation time in runtime**
30 seconds maximum! PowerShell modules installed via PSGallery take a few seconds to install at most.

**Are you willing to submit a PR?**
Yes :)

**Comment by AlenaSviridenko** [comment]
Hi @vexingpos,
given the pretty small installation time we'd rather not to install this tool on the image. Please, continue installing it in runtime.
Note, that we do not provide the default Az module version, so you should set it by yourself.

I am closing this issue, feel free to create a new one in case if any other help is needed.
Thanks!
