### ISSUE TITLE
Support for older ruby versions

### ISSUE THREAD

**Issue by cristi** [actions/virtual-environments#231]
Thank you for this repo and for github actions.
We're looking to move to actions, but one of our projects is still on ruby 2.3.3 Any chance older Ruby versions would be supported? I wrote a workflow using Ruby 2.3.7 and it worked fine until a few days ago.
As of today I get an error: `##[error]Version 2.3.7 not found`
I remember reading the only latest patch version are available, which would be ruby 2.3.8, but I get the same `##[error]Version 2.3.8 not found`
Thank you

**Comment by kaylangan** [comment]
Ruby 2.3 was removed since it's been EOL'd: https://github.blog/changelog/2019-10-17-github-actions-removing-python-3-4-and-ruby-2-3-from-the-virtual-environments/
