### ISSUE TITLE
Ruby bundler should be installed by default

### ISSUE THREAD

**Issue by ioquatix** [actions/virtual-environments#232]
When using setup-ruby, on ubuntu, bundler is not installed, and can be installed by `gem install bundler`.

But on macos, bundler is available by default, but also breaks if you try to install it using `gem install bundler`.

Can we just have it installed by default?

**Comment by eregon** [comment]
https://github.com/eregon/use-ruby-action installs Bundler by default for versions which don't already have it.
But it's an interesting question a general which version of Bundler should be provided.
For use-ruby-action it's currently Bundler 1.x for Ruby <= 2.6 (2.6 ships with Bundler 1) and Bundler 2 for Ruby 2.7 (2.7 ships with it).

**Comment by miketimofeev** [comment]
@ioquatix bundler has to be included now. Could you check it, please?

**Comment by ioquatix** [comment]
@miketimofeev thanks for your effort. I am now using a different workflow so not affected by this, but I'm glad it's now the default as I'm sure it is logical and will save time for future users!
