### ISSUE TITLE
brew upgrade fails for Python's 2to3 conflict 

### ISSUE THREAD

**Issue by traversaro** [actions/virtual-environments#2322]
**Description**  
If I run the commands `brew update` and `brew upgrade`, the job fails. This is similar to https://github.com/actions/virtual-environments/issues/2248 and https://github.com/actions/virtual-environments/issues/1811, but the specific error is different and is probably due to some other Python being installed. 

**Area for Triage**:  

**Question, Bug, or Feature?**:  
Bug 

**Virtual environments affected**  
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [x] macOS 10.15
- [x] macOS 11.0
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Expected behavior**  
I would expect that brew upgrade works fine.

**Actual behavior**  
`brew upgrade`  is failing with error: 
~~~
2020-12-21T12:59:17.7407310Z The formula built, but is not symlinked into /usr/local
2020-12-21T12:59:17.7430550Z Could not symlink bin/2to3
2020-12-21T12:59:17.7443870Z Target /usr/local/bin/2to3
2020-12-21T12:59:17.7446720Z already exists. You may want to remove it:
2020-12-21T12:59:17.7452220Z   rm '/usr/local/bin/2to3'
2020-12-21T12:59:17.7482600Z 
2020-12-21T12:59:17.7485390Z To force the link and overwrite all conflicting files:
2020-12-21T12:59:17.7547210Z   brew link --overwrite python@3.9
2020-12-21T12:59:17.7599790Z 
2020-12-21T12:59:17.7652130Z To list all files that would be deleted:
2020-12-21T12:59:17.7663330Z   brew link --overwrite --dry-run python@3.9
2020-12-21T12:59:17.7667290Z 
2020-12-21T12:59:17.7678030Z Possible conflicting files are:
~~~

**Repro steps**  

Run the following commands in a macos image:
- `brew update`
- `brew upgrade`

See https://github.com/traversaro/github-actions-brew-update-upgrade-check/actions/runs/435789601 for a minimal job that is failing.

**Comment by sunjayBhatia** [comment]
Running into the same issue in Envoy CI

**Comment by sunjayBhatia** [comment]
Looks like it is coming from the system python?

```
$ which python
/usr/local/bin/2to3
$ ls -la $(which python)
lrwxr-xr-x  1 root  wheel  66 Dec 12 21:22 /usr/local/bin/2to3 -> ../../../Library/Frameworks/Python.framework/Versions/2.7/bin/2to3

```

**Comment by maxim-lobanov** [comment]
Most likely caused by https://github.com/actions/virtual-environments/pull/2217 where we switched Python 2 installation from to official pkg. This pkg brings this symlink and brew can't override it later

**Comment by maxim-lobanov** [comment]
@miketimofeev I guess we should leave default MacOS Python 2 without any updates (just install pip) to avoid issues with brew

**Comment by miketimofeev** [comment]
@maxim-lobanov @Darleev but in that case `python` will be pointed to `python3` instead of `python2` as it's now

**Comment by miketimofeev** [comment]
@maxim-lobanov there are some issues with pip installation in this case. I suggest removing the 2to3 symlink created by python2 before the python3 installation.
@traversaro as a workaround you can add `rm -rf /usr/local/bin/2to3` as a first step until we've fixed it. Sorry for the inconvenience.

**Comment by traversaro** [comment]
Thanks a lot @miketimofeev @maxim-lobanov !

**Comment by miketimofeev** [comment]
We've finally finished image deployment, and this shouldn't be the issue anymore

**Comment by louwers** [comment]
This is still an issue. Can it be reopened or should I create a new issue?
