### ISSUE TITLE
Ruby, Windows, MSYS2

### ISSUE THREAD

**Issue by MSP-Greg** [actions/virtual-environments#234]
I'm still on the 'wait list' for Actions, so I haven't been able to look into it seriously.

To fully support Ruby on Windows, it would certainly be helpful to have the MSYS2 build system installed, along with access to the packages used to build Ruby.  Restricting Ruby to 2.4 and later, I believe all the packages are shared, with the exception of OpenSSL.

Ruby 2.4 currently uses OpenSSL 1.0.2, Ruby 2.5 and later use 1.1.1.  This is due to the std-lib version of Ruby OpenSSL being used (2.0.9 for 2.4, 2.1.2 for 2.5 and later).

Otherwise, the only package commonly used that isn't repo specific would be ragel.

**Comment by kaylangan** [comment]
Closing in favor of #30. Let me know if there's additional info that needs to be pulled out of this issue besides adding MSYS2.
