### ISSUE TITLE
macos-10.14 image is using macos-10.15

### ISSUE THREAD

**Issue by fbaptista** [actions/virtual-environments#2347]
**Description**  
We are trying to run our pipeline using macos-10.14 image https://github.com/actions/virtual-environments/blob/releases/macOS-10.14/20201214/images/macos/macos-10.14-Readme.md

**Area for Triage**:  
Apple
Deployment/Release

**Question, Bug, or Feature?**:  
Bug

**Virtual environments affected**  
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [X] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Expected behavior**  
When using
    runs-on: macos-10.14
we expect to have macOS 10.14 image. 

**Actual behavior**  
An image containing macOS 10.15 is used. 

**Repro steps**  
Create a simple workflow using: 
name: Apptim Desktop [macOS]

```
on:
  push:

jobs:
  run-package-macOS:
    name: Build on macos-10.14
    runs-on: macos-10.14
```

The pipeline shows that is using 10.15: 
`Current runner version: '2.275.1'
Operating System
  Mac OS X
  10.15.7
  19H15
Virtual Environment
  Environment: macos-10.15
  Version: 20201212.1
  Included Software: https://github.com/actions/virtual-environments/blob/macOS-10.15/20201212.1/images/macos/macos-10.15-Readme.md`

**Comment by maxim-lobanov** [comment]
@fbaptista , `macos-10.14` is available only for Azure DevOps.

- GitHub Actions provide `macos-10.15` and `macos-11.0`
- Azure DevOps provide `macos-10.15` and `macos-10.14`

You can find more details in https://docs.github.com/en/free-pro-team@latest/actions/reference/specifications-for-github-hosted-runners#supported-runners-and-hardware-resources

**Comment by maxim-lobanov** [comment]
I have updated README with #2355 to be clearer about this point.

**Comment by Margen67** [comment]
This prevents using Xcode 9.4.1: #859
