### ISSUE TITLE
Preinstall GNU Scientific Library (`libgsl-dev` + `libgsl23` from APT repository) in Ubuntu environments

### ISSUE THREAD

**Issue by iBug** [actions/virtual-environments#2356]
### Tool information

- Tool name: GNU Scientific Library
- Tool license: GNU GPLv3
- Add or update? Add
- Desired version: The version available from Ubuntu's official software repository, i.e. using `apt-get install`
- Approximate size: 2 MB
- If this is an add request:
  - Brief description of tool: The GNU Scientific Library is a software library for numerical computations in applied mathematics and science.
  - URL for tool's homepage: <https://www.gnu.org/software/gsl/>
  - Provide a basic test case to validate the tool's functionality: Not needed - as long as it's installed from Ubuntu APT repository and not an external source.

### Question, Bug, or Feature?

Feature.

### Virtual environments affected

- [x] Ubuntu 16.04
- [x] Ubuntu 18.04
- [x] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

### Can this tool be installed during the build?

Yes. As simple as `apt-get -y install libgsl-dev`.

### Tool installation time in runtime

20 seconds (dpkg database processing is unknownly slow)

### Are you willing to submit a PR?

Yes.

**Comment by maxim-lobanov** [comment]
Hello @iBug , feel free to submit PR.
I think it should be enough to update toolset files for all affected platforms: https://github.com/actions/virtual-environments/blob/main/images/linux/toolsets/toolset-1804.json

**Comment by iBug** [comment]
Hi @maxim-lobanov, thanks for the response. Would you mind taking a look at #2360?

**Comment by miketimofeev** [comment]
@iBug thanks for your contribution, all ubuntu images were deployed last week!
