### ISSUE TITLE
Update/Add NDK r22

### ISSUE THREAD

**Issue by mirabilos** [actions/virtual-environments#2365]
**Tool information**
- Tool name: Android NDK
- Tool license: eh, same as before I guess
- Add or update? update
- Desired version: r22 (currently `22.0.7026061` but any newer stable release will also work)
- Approximate size: 

**Area for Triage**: Android

**Question, Bug, or Feature?**: Feature

**Virtual environments affected**
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [x] ubuntu-latest (why is that still 18.04 by the way?)
- [ ] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Can this tool be installed during the build?**
I have no idea.

**Tool installation time in runtime**
I have no idea.

**Are you willing to submit a PR?**
I wouldn’t know how to even do that.

**Comment by dibir-magomedsaygitov** [comment]
Hello, @mirabilos. 
Thank you for your report. We install latest available NDK on our images. Next rollout should be in the beginning of January. I will post an update message when images with new version of Android NDK are available to use.

**Comment by mirabilos** [comment]
Apparently deployed now, thanks.

**Comment by maxim-lobanov** [comment]
@mirabilos , please keep on mind that deployment is not finished yet. Some pools still contain previous image version. We are expecting the deployment to finish on Monday

**Comment by mirabilos** [comment]
Maxim Lobanov dixit:

>@mirabilos , please keep on mind that deployment is not finished yet.
>@Some pools still contain previous image version. We are expecting the
>@deployment to finish on Monday

Ah okay. I got a failure for the _old_ NDK version yesterday, so
I was switching to the new one already, thinking this finished.

**Comment by mirabilos** [comment]
Nope, it’s not finished:

   > No version of NDK matched the requested version 22.0.7026061. Versions available locally: 21.3.6528147

**Comment by miketimofeev** [comment]
@mirabilos, unfortunately, we have to rollback NDK r22 from all the images due to the breaking changes, more information can be found here https://github.com/actions/virtual-environments/issues/2481#issuecomment-763700114

**Comment by mirabilos** [comment]
Mikhail Timofeev dixit:

>@mirabilos, unfortunately, we have to rollback NDK r22 from all the
>@images due to the breaking changes, more information can be found here
>@https://github.com/actions/virtual-environments/issues/2481#issuecomment-763700114

It was stated there that the images should stay on r22 and those
people should fix their äpps to work with r22 or install the older
as part of the build step. Why is not that done?

Anyway then I did right in reopening this bugreport. I’ll wait
for you to fix this again.

Thanks,
//mirabilos
-- 
tarent solutions GmbH
Rochusstraße 2-4, D-53123 Bonn • http://www.tarent.de/
Tel: +49 228 54881-393 • Fax: +49 228 54881-235
HRB 5168 (AG Bonn) • USt-ID (VAT): DE122264941
Geschäftsführer: Dr. Stefan Barth, Kai Ebenrett, Boris Esser, Alexander Steeg

**Comment by dibir-magomedsaygitov** [comment]
Android NDK has been added to Ubuntu20 image and should be available with the next week's rollout. I'll post an update message here.

**Comment by mirabilos** [comment]
So… I got failing builds again… what’s the official word on this?

**Comment by miketimofeev** [comment]
@mirabilos due to lack of free space on the images, we've added NDK r22 only to Ubuntu 20, both windows versions and macOS. Unfortunately, we are a bit delayed with Ubuntu-latest transition at the moment so it's better to specify the exact version.
I'm going to close this issue, but feel free to contact us if you have any concerns.

**Comment by mirabilos** [comment]
Mikhail Timofeev dixit:

>@mirabilos due to lack of free space on the images, we've added NDK r22
>@only to Ubuntu 20, both windows versions and macOS. Unfortunately, we

OK, so this is now officially part of the ubuntu-20.04 image, not
just there by accident and possibly subject to rollback again. Thanks.

>@are a bit delayed with Ubuntu-latest transition at the moment so it's
>@better to specify the exact version.

Right, did that yesternight.

> I'm going to close this issue,
>@but feel free to contact us if you have any concerns.

Thanks, but with the confirmation it’s now officially there I’m good.

bye,
//mirabilos
-- 
tarent solutions GmbH
Rochusstraße 2-4, D-53123 Bonn • http://www.tarent.de/
Tel: +49 228 54881-393 • Fax: +49 228 54881-235
HRB 5168 (AG Bonn) • USt-ID (VAT): DE122264941
Geschäftsführer: Dr. Stefan Barth, Kai Ebenrett, Boris Esser, Alexander Steeg

**Comment by EwoutH** [comment]
For anyone that wants to use the latest NDK with Bazel, add this step:
```
      - name: Set NDK path
        run: echo "ANDROID_NDK_HOME=$ANDROID_NDK_LATEST_HOME" >> $GITHUB_ENV
```
If there's a more elegant way, please share.

**Comment by mirabilos** [comment]
Ewout ter Hoeven dixit:

>If there's a more elegant way, please share.

This is fun, as the Android toolchain positively warns about the
use of ANDROID_NDK_HOME; the side-by-side (instead of bundle) NDK
is preferred these days and I have to explicitly execute
	unset ANDROID_NDK_HOME
(part of my run command) to avoid running into that warning.

bye,
//mirabilos
-- 
Infrastrukturexperte • tarent solutions GmbH
Am Dickobskreuz 10, D-53121 Bonn • http://www.tarent.de/
Telephon +49 228 54881-393 • Fax: +49 228 54881-235
HRB AG Bonn 5168 • USt-ID (VAT): DE122264941
Geschäftsführer: Dr. Stefan Barth, Kai Ebenrett, Boris Esser, Alexander Steeg
