### ISSUE TITLE
Add Alibaba cloud aliyun-cli

### ISSUE THREAD

**Issue by ethomson** [actions/virtual-environments#237]
**Tool information**
- Tool name: aliyun-cli
- Add or update? Add
- Desired version: Latest
- Approximate size: 
- If this is an add request:
  - Brief description of tool: Alibaba cloud CLI
  - URL for tool's homepage: https://www.alibabacloud.com/help/doc-detail/90765.htm

**Area for Triage**: 

**Question, Bug, or Feature?**:  Feature

**Virtual environments affected**
- [X] macOS 10.15
- [X] Ubuntu 16.04 LTS
- [X] Ubuntu 18.04 LTS
- [X] Windows Server 2016 R2
- [X] Windows Server 2019

**Can this tool be installed during the build?**
Yes - https://www.alibabacloud.com/help/doc-detail/90765.htm

In [chocolatey](https://chocolatey.org/packages/aliyun-cli) and homebrew, but not apt and it would be nice to have this installed already.

**Comment by nikita-bykov** [comment]
We have added Alibaba cloud aliyun-cli installation to Windows, Linux, macOS.
Images with it will be rolled out around next week.

**Comment by nikita-bykov** [comment]
All changes were successfully deployed.
