### ISSUE TITLE
ICU 68.1: ucnv.h Source File [FALL-BACK v4.0]

### ISSUE THREAD

**Issue by IAM-db** [actions/virtual-environments#2380]
https://unicode-org.github.io/icu-docs/apidoc/dev/icu4c/ucnv_8h_source.html

**Comment by IAM-db** [comment]
"I C U 4 C" I CARE ULTIMATELY 4 CHRIST

**Comment by maxim-lobanov** [comment]
Please provide clear description of the issue following issue template.
Closing for now
