### ISSUE TITLE
Update/Add flex

### ISSUE THREAD

**Issue by beroset** [actions/virtual-environments#2384]
**Tool information**
- Tool name: flex
- Tool license: modified BSD
- Add or update? add
- Desired version: latest
- Approximate size: 
- If this is an add request:
  - Brief description of tool: The Fast Lexical Analyzer - scanner generator for lexing in C and C++ 
  - URL for tool's homepage: https://github.com/westes/flex
  - Provide a basic test case to validate the tool's functionality: 

**Area for Triage**:
C/C++

**Question, Bug, or Feature?**:
Feature

**Virtual environments affected**
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [X] Windows Server 2019

Note that flex is already available under `mac-latest` and `ubuntu-latest`.

**Can this tool be installed during the build?**
Yes:   `choco install winflexbison3` should work and has the added benefit of also installing `bison`.

**Tool installation time in runtime**

**Are you willing to submit a PR?**
Willing, yes, but I don't know how yet.

**Comment by maxim-lobanov** [comment]
Hello @beroset , thank you for your proposal.
Considering the fact that installation in runtime is pretty simple, we wouldn't like to bake this tool into the images due to maintenance concerns. Please consider installation in runtime.

**Comment by beroset** [comment]
I had thought that because the other platforms already included it, it would make sense on Windows, too, but I can see the point of avoiding additional complexity.  I'll make the required adjustments in my scripts. Thanks!

**Comment by maxim-lobanov** [comment]
Thank you for understanding. To provide a bit more context around it - currently, we feel that images are overcrowded with installed software and it is becoming nightmare to maintain them. So we have to be extra-careful about adding the new tools.

Thanks!
