### ISSUE TITLE
Add chromium-browser to Ubuntu

### ISSUE THREAD

**Issue by Krinkle** [actions/virtual-environments#2388]
**Description**

Most package managers on Linux do not provide Google Chrome, they provide Chromium. As such, when projects provide bindings to different browsers across platforms, it often assumed that Chrome is used on Windows or macOS and Chromium on Linux.

As the Ubuntu image appears to be missing Chromium, this is making it difficult for developers to manage their local dev environment and CI setup in a way that works for contributors across operating systems.

**Area for Triage**:  
Containers, JavaScript and Node.js, Packages, Testing and code coverage

**Question, Bug, or Feature?**:  
Feature

**Virtual environments affected**  
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [x] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

See also:
- Follows-up https://github.com/actions/virtual-environments/issues/126.
- Ref https://github.com/karma-runner/karma-chrome-launcher/issues/141.

**Comment by CatTheHacker** [comment]
From what I remember, Google Chrome is already installed on Ubuntu runners (https://github.com/actions/virtual-environments/blob/main/images/linux/scripts/installers/google-chrome.sh). Is there any preferred difference in Chromium over Chrome?

**Comment by Krinkle** [comment]
This is not about preference. I do prefer Chromium over Chrome, and I think CI is the last place I expected Google Chrome to be installed over plain Chromum. It is provided by Ubuntu and Debian package managers out of the box, and is much more aligned with the ethos of the ecosystem it runs in. The end-user convenience trade-off that a Google setup offers afaik doesn't really apply to a CI context.

But... this ticket isn't about preference. It's about interoperability. Developer tooling that expects to find Chromium on Linux currently fails on GitHub Actions because neither `chromium` nor `chromium-browser` are discoverable in the PATH.

**Comment by CatTheHacker** [comment]
What could be done is to create `chromium`/`chromium-browser` symlinks that point to `chrome`/`chrome-browser` in the image but that might sabotage people who install Chromium by themselves during workflow.
Removing Google Chrome would have far-wide impact on many people that already use it and installing Chromium additionally would take space, time during build and can affect workflows which install Chromium.
From quick search I did not find anyone mentioning that issue earlier and Chromium was proposed only once in this repo. I find that `chromium` a must have assumption weird since it was never mentioned here nor listed in software installed (https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-README.md#browsers-and-drivers).

**Comment by Krinkle** [comment]
Yeah, that's no reason to remove the non-standard `google-chrome` install. That seems fine to keep for back compat and as convenience for those who specifically prefer Google on Linux for some reason.

The differences between Chromium and its derivatives (Google Chrome, Opera, Brave, Microsoft Edge, etc.) aren't huge in terms of Web APIs. I don't expect major features missing. If one is developing a new open source project, I'm sure if it can work on one it'll probably work on the other, and the same for developer tooling. However, they are definitely different browsers with significant differences in how they're compiled, which Web APIs are enabled, and when, and the proprietary capabilities, restrictions, and tracking the vendors add to the binaries. There are also some browser features, especially around DRM and media codecs, that e.g. Google supports but Chromium does not. And conversely there is notable distractions in the network stack in Google Chrome (by default) that can make network and performance testing quite hard, compared to the less noisyy defaults in Chromium.

I think you'll find that in general when people install a chromium browser on Linux, especialy on Ubuntu, they install Chromium and not Google Chrome. Perhaps because google-chrome isn't permitted the default package manager, or for privacy reasons around usage at home, or other reasons. The reasons for why people choose one over the other don't really matter since this is not an issue of preference, nor an issue of how easy it is to switch for an individual GitHub project.

Instead, I'm raising it as an issue of interoperability. When developer tooling is written for Linux, it generally binds against chromium. It requires additional changes for every single project to change the entire stack from top to bottom to use google-chrome instead and/or to take the delay in CI and manually install the missing package.

This is friction can be reduced and even eliminated entirely, by including `chromium-browser` in the list of apt-installed packages from Ubuntu's default package manager, so that more developer tooling "just works", based on assumptions baked into a large ecosystem that mostly predate GitHub's new CI infrastructure.

**Comment by maxim-lobanov** [comment]
Hello @Krinkle ,
In general, we don't have objections for baking chromium into the images. But for now, we have issues with free space on Ubuntu 16.04 and 18.04.
So our proposal is installing chromium to Ubuntu 20.04 only (Ubuntu 20.04 is going to become `ubuntu-latest` soon).
For previous Ubuntu images, you can install it in runtime via apt install.

Does it work for you?

**Comment by Krinkle** [comment]
Yes! 🙂

**Comment by andy-mishechkin** [comment]
Hello, @Krinkle 
Chromium browser has been added to Ubuntu 20 image. You can find it after the next deployment (on the next week).
If you will got some issues with it - please ping me in this ticket.
Thank you.

**Comment by miketimofeev** [comment]
@Krinkle we've finished Ubuntu20 image deployment with chromium on board https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-README.md#browsers-and-drivers 
I'm going to close the issue but please feel free to contact us if you have any concerns.
Thank you!
