### ISSUE TITLE
Actions scheduled on ubuntu-latest are failing and don't get scheduled on ubuntu-18.04

### ISSUE THREAD

**Issue by Ne02012** [actions/virtual-environments#2392]
**Description**  
I had a workflow that used "ubuntu-latest" to schedule the cron job every 5 minutes, but it was always failing. I was able to trigger the same workflow manually successfully. So, I switched to using ubuntu-18.04 for the action per the recommendations here, but now the cron job has not been scheduled, yet.

**Area for Triage**:  
Here is the status badge for the run on "ubuntu-latest": ![Scrape latest data](https://github.com/Ne02012/NYT-2021-GA-Sen-Runoff-Vote-Tracker/workflows/Scrape%20latest%20data/badge.svg)

**Question, Bug, or Feature?**:  
"Bug"

**Virtual environments affected**  
- [ ] Ubuntu 16.04
- [x] Ubuntu 18.04
- [x] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Expected behavior**  
I expect the action to be triggered every 5 minutes. 

**Actual behavior**  
When the action got scheduled on ubuntu-latest it failed. I tried re-running it, but it still failed. So, I switched to using ubuntu-18.04 at https://github.com/Ne02012/NYT-2021-GA-Sen-Runoff-Vote-Tracker/blob/main/.github/workflows/scrape-latest.yml, but haven't seen the cron job scheduled there as well, yet. I am able to trigger the action manually and it completes successfully on ubuntu-18.04.

**Repro steps**  
Check the action at https://github.com/Ne02012/NYT-2021-GA-Sen-Runoff-Vote-Tracker/actions?query=workflow%3A%22Scrape+latest+data%22.

**Comment by Ne02012** [comment]
I gave up on using this action and instead using a batch script on my laptop to auto-scrape and commit the file every 3 minutes. It is more reliable than this git action, which is a shame.

**Comment by LeonidLapshin** [comment]
Hey, @Ne02012 !
You should wait a bit after adding schedule workflow to your repo, it can take some time (an hour in my case while testing your workflow). After some time your jobs will be successfully scheduled :) You still can add the scheduled workflow to your repo and check if it runs soon.

**Comment by LeonidLapshin** [comment]
Hi, @Ne02012 
I'll close this issue, but feel free to reopen it if you have any concerns.
