### ISSUE TITLE
Add Vault

### ISSUE THREAD

**Issue by rtselizondo** [actions/virtual-environments#24]
**Tool information**
- Tool name: Hashicorp Vault
- Add or update? Add
- Desired version: latest
- Approximate size: 31MB
- If this is an add request:
  - Brief description of tool: A tool for secrets management, encryption as a service, and privileged access management
  - URL for tool's homepage: https://github.com/hashicorp/vault

**Virtual environments affected**
- [ ] macOS 10.14
- [x] Ubuntu 16.04 LTS
- [x] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Can this tool be installed during the build?**
Yes, include binary in image.

**Are you willing to submit a PR?**
willing to try.

**Comment by maxim-lobanov** [comment]
Vault can be installed to Ubuntu using the following script:
```
wget https://releases.hashicorp.com/vault/0.11.4/vault_0.11.4_linux_amd64.zip
unzip vault_0.11.4_linux_amd64.zip
sudo mv vault /usr/bin
vault --version
```
Installation takes less than 5 seconds

**Comment by alepauly** [comment]
thanks @maxim-lobanov for the suggestion. @rtselizondo at this time we won't be adding Vault to the virtual-environments by default since it's an easy on demand install. Sorry it us so long to respond!
