### ISSUE TITLE
SQLite database gets corrupted in CI workflow on Ubuntu

### ISSUE THREAD

**Issue by pemistahl** [actions/virtual-environments#2409]
**Description**  
I've written a command-line tool in Rust. Upon first execution, it unzips a bundled SQlite database to the user's home directory. The database is created and zipped when building the source code. I have a CI workflow using GitHub Actions running on Windows, macOS and Ubuntu. The integration test step fails on Ubuntu because it cannot access the database properly. On Ubuntu 16.04 the error says `no such table` so the database seems to be empty. On Ubuntu 20.04 it even says `database disk image is malformed`.

The executable path is: `/home/runner/work/chr/chr/target/x86_64-unknown-linux-musl/debug/chr`
The database path is: `/home/runner/.chr/chr_1_0_0.db`

**Area for Triage**:
Rust

**Question, Bug, or Feature?**:  
Bug

**Virtual environments affected**  
- [x] Ubuntu 18.04
- [x] Ubuntu 20.04

**Expected behavior**  
The SQlite database should be accessed properly on Ubuntu.

**Actual behavior**  
The SQlite database is either empty or even corrupted on Ubuntu.

**Repro steps**
Run the integration test step using `cargo test` which unzips the bundled database to disk and then tries to access it in the tests.
[CI workflow file](https://github.com/pemistahl/chr/blob/v1.1.0-wip/.github/workflows/chr-ci.yml)
[Ubuntu 16.04 stacktrace](https://github.com/pemistahl/chr/runs/1674207911?check_suite_focus=true#step:8:37)  
[Ubuntu 20.04 stacktrace](https://github.com/pemistahl/chr/runs/1674263249?check_suite_focus=true#step:8:107)

**Comment by al-cheb** [comment]
Hello, @pemistahl 
I can't reproduce the issue from my side with a custom database. Sample database - https://www.sqlitetutorial.net/sqlite-sample-database/

```
 runs-on: ubuntu-20.04
    steps:
      - name: sqllite
        run: |
            wget https://cdn.sqlitetutorial.net/wp-content/uploads/2018/03/chinook.zip
            unzip chinook.zip
            sqlite3 chinook.db '.tables'
            sqlite3 chinook.db 'SELECT * FROM albums LIMIT 10;'
```
![image](https://user-images.githubusercontent.com/47745270/104153572-bee88580-53f3-11eb-90b2-da06065119f9.png)

**Comment by pemistahl** [comment]
Thanks for your quick response @al-cheb.

I don't think that the problem is caused by the database itself but by the tools or threads accessing the database. Perhaps it is a combination of the working threads in your virtual environment on Ubuntu and the way cargo executes the integration tests. 

I'm attaching the database file [chr_1_0_0.db.zip](https://github.com/actions/virtual-environments/files/5797341/chr_1_0_0.db.zip) that I created on my local machine running on macOS Catalina 10.15. I don't have an Ubuntu machine here. The file was created with the [rusqlite library](https://github.com/rusqlite/rusqlite), maybe a possible cause of the problem as well.

Thank you very much in advance for any further investigation.

**Comment by al-cheb** [comment]
@pemistahl,
The db works as expected.

```
steps:
      - name: shell
        run: |
            wget --quiet https://github.com/actions/virtual-environments/files/5797341/chr_1_0_0.db.zip
            unzip chr_1_0_0.db.zip
            sqlite3 chr_1_0_0.db '.tables'
            sqlite3 chr_1_0_0.db 'SELECT * FROM UnicodeData LIMIT 10;'
```
![image](https://user-images.githubusercontent.com/47745270/104219178-d7d25480-544e-11eb-8581-fa7af5e00eac.png)

**Comment by pemistahl** [comment]
Exactly, that's what I expected. So the problem seems to be in the code but it's strange that it only occurs on Ubuntu and not on the other operating systems. Do you have any other idea what might cause the problem? If not, I will probably have to close this issue, I'm afraid.

**Comment by al-cheb** [comment]
@pemistahl , Could you please add in your pipeline just for test at the first step?
```
- name: db
        run: |
            mkdir .chr
            cd .chr
            wget --quiet https://github.com/actions/virtual-environments/files/5797341/chr_1_0_0.db.zip
            unzip chr_1_0_0.db.zip
```

**Comment by pemistahl** [comment]
Interesting, with the database I created on my local machine, [it works now on Ubuntu](https://github.com/pemistahl/chr/runs/1683516031?check_suite_focus=true#step:9:23). So the db that is created in the Ubuntu environment is corrupt. This will most probably be a problem with either sqlite3 or rusqlite then. I doubt that the environment is the cause. You would say so as well, wouldn't you?

**Comment by al-cheb** [comment]
> Interesting, with the database I created on my local machine, [it works now on Ubuntu](https://github.com/pemistahl/chr/runs/1683516031?check_suite_focus=true#step:9:23). So the db that is created in the Ubuntu environment is corrupt. This will most probably be a problem with either sqlite3 or rusqlite then. I doubt that the environment is the cause. You would say so as well, wouldn't you?

I am trying to reproduce on my local virtual vm with Ubuntu 20.04 and building process is so slow, ~ 100kb in a minute for ` chr.db`.

![image](https://user-images.githubusercontent.com/47745270/104230262-64d0da00-545e-11eb-892d-886c7a3d8761.png)

**Comment by pemistahl** [comment]
> building process is so slow, ~ 100kb in a minute for chr.db

I know, some files from the Unicode character database are downloaded, parsed and written to the SQlite db during the build. This takes some time in addition to compiling the Rust dependencies.

**Comment by al-cheb** [comment]
@pemistahl ,
Looks like the `unzip_database` method blocks a chr_1_0_0.db file. I can reproduce on my local vm with Ubuntu.

![image](https://user-images.githubusercontent.com/47745270/104276413-dd16ba00-54b5-11eb-8926-85bd56fe9b67.png)

The second attempt without invoking  `unzip_database` method , works fine:
```
      - name: Test in debug mode
        run: cargo test --target x86_64-unknown-linux-musl
      - name: if failure
        if: ${{ failure() }}
        run: |
          cargo test --target x86_64-unknown-linux-musl
```
![image](https://user-images.githubusercontent.com/47745270/104276474-f881c500-54b5-11eb-82cf-8e4eb5083fb1.png)

**Comment by pemistahl** [comment]
Thanks a lot @al-cheb. 👍  

Without your help, I would probably have searched for a very long time for the solution. But my intuition was right that it had to do with cargo and multithreading. I'm still surprised that it only occurred on Ubuntu. Perhaps it is the way it handles threads in general.
