### ISSUE TITLE
[macOS] Homebrew is updated to 2.7 with few major changes

### ISSUE THREAD

**Issue by AlenaSviridenko** [actions/virtual-environments#2415]
**Breaking changes**
Homebrew was updated to version 2.7 with few breaking changes inside it:
1. `brew cask install` syntax is deprecated in favor of `brew install --cask`
2. don’t fall back to building from source code if bottle is not found for unsupported packages/macOS versions

**Target date**
Image deployment starts January, 11 and will take 3-4 days.

**The motivation for the changes**
We provide the latest Homebrew versions on images.

**Possible impact**
1. Scripts that are using old syntax will fail.
2. Unsupported packages/macOS versions will require a workaround for building from source code.

**Virtual environments affected**
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [x] macOS 10.13
- [x] macOS 10.14
- [x] macOS 10.15
- [x] macOS 11.0
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Mitigation ways**
1. Migrate to new syntax `brew install --cask`
2. Use flag `--build-from-source` to explicitly build from source code if no bottle is found. You can refer to our PR https://github.com/actions/virtual-environments/pull/2354 as an example.

**Comment by wieseaka** [comment]
Acces

**Comment by nightlark** [comment]
Would it be possible to get Homebrew updated to 2.7.3 or newer in the macOS VM? In particular I'm looking to get macFUSE, and the latest version 4.0.5 was just added as a new package a few days ago -- currently this means running a `brew update` which is rather slow.

**Comment by maxim-lobanov** [comment]
This week image contains Homebrew 2.7.2. Image with 2.7.3 will be deployed in a week

**Comment by nightlark** [comment]
Awesome, thanks!
