### ISSUE TITLE
[all OS versions] Android NDK is updated to r22.

### ISSUE THREAD

**Issue by AlenaSviridenko** [actions/virtual-environments#2420]
**Breaking changes**
Default Android NDK was updated to r22.

**Target date**
Images deployment starts January, 11 and will take 3-4 days.

**The motivation for the changes**
We provide only the latest NDK by default due [to space concerns](https://github.com/actions/virtual-environments/issues/643#issuecomment-624608154)

**Possible impact**
If your workflow uses features that were removed from r22 — your build will be broken. Please, refer to [NDR r22 changelog](https://github.com/android/ndk/wiki/Changelog-r22) for more information.

**Virtual environments affected**
- [x] Ubuntu 16.04
- [x] Ubuntu 18.04
- [x] Ubuntu 20.04
- [x] macOS 10.13
- [x] macOS 10.14
- [x] macOS 10.15
- [x] macOS 11.0
- [x] Windows Server 2016 R2
- [x] Windows Server 2019

**Mitigation ways**
- Ubuntu: `sudo ${ANDROID_HOME}/tools/bin/sdkmanager --install "ndk;<exact_version>"`
- macOS: `${ANDROID_HOME}/tools/bin/sdkmanager --install "ndk;<exact_version>"`
- Windows: `$env:ANDROID_HOME/tools/bin/sdkmanager --install "ndk;<exact_version>"`

If the time is critical for you, consider using [actions/cache](https://github.com/actions/cache) to win some installation time.

**Comment by carstenhag** [comment]
Hello there! We use Azure DevOps pipelines with the macOS 10.15 image to build our Android apps.

Yesterday we wanted to build releases of our apps, but we got gradle errors back that the NDK version was not available. We googled and found this issue :). We then tried out your specified mitigation way, but that unfortunately did not work.

We tried out all of these commands, but they all failed:

```
sudo ${ANDROID_HOME}/tools/bin/sdkmanager --sdk_root=${ANDROID_HOME} --install "ndk;22.0.7026061"
```

```
sudo ${ANDROID_HOME}/tools/bin/sdkmanager --install "ndk;22.0.7026061"
```

```
export JAVA_OPTS='-XX:+IgnoreUnrecognizedVMOptions --add-modules java.se.ee'
sudo ${ANDROID_HOME}/tools/bin/sdkmanager --install "ndk;22.0.7026061"
```

Error:
```
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema
	at com.android.repository.api.SchemaModule$SchemaModuleVersion.<init>(SchemaModule.java:156)
	at com.android.repository.api.SchemaModule.<init>(SchemaModule.java:75)
	at com.android.sdklib.repository.AndroidSdkHandler.<clinit>(AndroidSdkHandler.java:81)
	at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:73)
	at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:48)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.XmlSchema
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:602)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 5 more
```

Could you please tell us when the migration will be finished, or how we can mitigate the issue? Seems like today is the last day of migration, but the rollout progress is only at 25%. Thanks in advance!

**Comment by maxim-lobanov** [comment]
Hello @carstenhag, Could you please provide image version from your last successful build and first failed build? (Image version can be found in the logs of first step of build).
What exact version of NDK do you need to use in your build?
The previous image version (`20201212.1`) contained NDK 21.3.6528147. The new image version (`20210110.1`) contains NDK 22.0.7026061.
If your build started to fail after image upgrade, I guess you need to install NDK 21.3.6528147 in runtime, not 22.0.7026061 (if I understand you correctly)

**Comment by ystefinko** [comment]
ndk-bundle now don't contain directory called : `platforms`. We faced issue with gradle:
_Configure project :app
NDK is missing a "platforms" directory.
If you are using NDK, verify the ndk.dir is set to a valid NDK directory. It is currently set to /usr/local/lib/android/sdk/ndk-bundle.
If you are not using NDK, unset the NDK variable from ANDROID_NDK_HOME or local.properties to remove this warning._

Issue happened first time yesterday afternoon and continues today. Can you please support ?

**Comment by carstenhag** [comment]
Hello there! We have been using `21.3.6528147` for some months now. Our builds failed with that (because we got a new image), the logs said that we should use `22.0.7026061`, so we did so and we committed that.

But now we seem to always get old images again which don't have `22.0.7026061` so I wanted to manually install it :D

**Comment by dentuzhik** [comment]
We just hit the NDK mismatch on our CI, and while I understand you have to keep them updated, is there any way to announce it through some other channels?

**Comment by carstenhag** [comment]
Same here. I know that Azure DevOps does announce brownouts of image and have seen those before. Would have been very good to announce this as well.

**Comment by maxim-lobanov** [comment]
@ystefinko, could you please try mitigation step above? Adding `sudo ${ANDROID_HOME}/tools/bin/sdkmanager --install "ndk;21.3.6528147"` as a first step of your build?

@carstenhag , sorry for inconvenience, deployment should be finished on Monday.
I think you have two options:
- reverting your app to NDK `21.3.6528147` and use mitigation step `sudo ${ANDROID_HOME}/tools/bin/sdkmanager --install "ndk;21.3.6528147"`
- leave on `22.0.7026061` and manually install `22.0.7026061`. As soon as new image is fully deployed, installation time will be reduced to zero since NDK will be already available.

**Comment by carstenhag** [comment]
@maxim-lobanov unfortunately the suggested line does not work (I had posted the errors we got at https://github.com/actions/virtual-environments/issues/2420#issuecomment-760767063).

**Comment by maxim-lobanov** [comment]
@dentuzhik , have you tried to subscribe to releases?
> Regular Weekly Rhythm can be followed by watching Releases. Pre-release is created when deployment is started. As soon as deployment is finished, it is converted to release.

@carstenhag , sorry for inconvenience. Usually deployment of macOS takes less 2 days but this week we have stuck with multiple environment issues.

**Comment by carstenhag** [comment]
Maybe we are talking past eachother, I will try to be more specific :). It is not a problem that the rollout takes some time.

For us it is a problem, that the mitigation does not work. We would have been happy if the mitigation would have installed the ndk version.

**Comment by Kerizer** [comment]
For us root cause was in bug with Android gradle plugin - https://issuetracker.google.com/issues/144111441
With 4.1.1 version it's possible to completely remove hardcoded `ndkVersion` and let plugin to resolve it automatically

**Comment by maxim-lobanov** [comment]
@carstenhag , oh, just realized an issue.
Try without sudo `${ANDROID_HOME}/tools/bin/sdkmanager --install "ndk;21.3.6528147"`. `sudo` is needed only for Ubuntu images. Will fix the first post.

**Comment by carstenhag** [comment]
Thanks, that did work (I used `${ANDROID_HOME}/tools/bin/sdkmanager --sdk_root=${ANDROID_HOME} --install "ndk;22.0.7026061"` to be precise, but I guess `--sdk_root` can be omitted)

**Comment by maxim-lobanov** [comment]
I have logged bug for an issue with sudo: https://github.com/actions/virtual-environments/issues/2454
sdkmanager refers incorrect Java version via sudo. It is reason why initial command fails on macOS.

**Comment by al-cheb** [comment]
This behavior is by design for sudo:
`-E' The -E (preserve environment) option indicates to the security policy that the user wishes to preserve their existing environment variables. The security policy may return an error if the -E option is specified and the user does not have permission to preserve the environment.`

you should use flag -E to pass env variables, because JAVA_HOME is missing:
```
Mac-1610725225646:~ runner$ sudo java -version
openjdk version "14.0.2" 2020-07-14
OpenJDK Runtime Environment AdoptOpenJDK (build 14.0.2+12)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 14.0.2+12, mixed mode, sharing)

Mac-1610725225646:~ runner$ sudo -E java -version
openjdk version "1.8.0_275"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_275-b01)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.275-b01, mixed mode)
```

unset JAVA_HOME:
```
Mac-1610725225646:~ runner$ unset JAVA_HOME
Mac-1610725225646:~ runner$ java -version
openjdk version "14.0.2" 2020-07-14
OpenJDK Runtime Environment AdoptOpenJDK (build 14.0.2+12)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 14.0.2+12, mixed mode, sharing)
```

**Comment by ystefinko** [comment]
@maxim-lobanov
I tried out all of these commands, but they all failed:

sudo ${ANDROID_HOME}/tools/bin/sdkmanager --sdk_root=${ANDROID_HOME} --install "ndk;22.0.7026061"
sudo ${ANDROID_HOME}/tools/bin/sdkmanager --sdk_root=${ANDROID_HOME} --install "ndk;21.3.6528147"
unset ANDROID_NDK_HOME
Gradle 5.1.1, Android gradle plugin 3.4.0(tried 3.4.3).
Our android example app still not compiling: https://dev.azure.com/heremaps/here-data-sdk/_build?definitionId=3&_a=summary
We need urgent support , as our development became blocked by changes on your side.

**Comment by carstenhag** [comment]
@ystefinko As maxim wrote at https://github.com/actions/virtual-environments/issues/2420#issuecomment-760998986, leave out the `sudo`, then it works. I also confirmed that this works some comments ago...

`${ANDROID_HOME}/tools/bin/sdkmanager --sdk_root=${ANDROID_HOME} --install "ndk;22.0.7026061` will install the ndk version `22.0.7026061`. If you need any other version, specify that in its place.

**Comment by ystefinko** [comment]
@carstenhag and @maxim-lobanov issue still exist. I ran it without `sudo` too.

**Comment by dmitry-shibanov** [comment]
Hello @ystefinko. As a solution you can try 
- setup build gradle to the 4.1.0 : `classpath 'com.android.tools.build:gradle:4.1.0'`
- update gradle version to 6.5.1: `distributionUrl=https\://services.gradle.org/distributions/gradle-6.5.1-all.zip`
- Update build.sh part to this:
```
${ANDROID_HOME}/tools/bin/sdkmanager --install "ndk;21.3.6528147" --sdk_root=${ANDROID_HOME} > /dev/null
export ANDROID_NDK_HOME=$ANDROID_HOME/ndk/21.3.6528147

mkdir -p build && cd build
cmake .. -DCMAKE_TOOLCHAIN_FILE="$ANDROID_HOME/ndk/21.3.6528147/build/cmake/android.toolchain.cmake" \
	-DANDROID_PLATFORM=android-28 \
	-DANDROID_NDK="$ANDROID_HOME/ndk/21.3.6528147" \
	-DANDROID_ABI=arm64-v8a \
	-DOLP_SDK_ENABLE_TESTING=NO \
	-DOLP_SDK_BUILD_EXAMPLES=ON
```

**Comment by ystefinko** [comment]
@dmitry-shibanov hello!
Thanks for advice!

All your suggestions helped. Build passed.
Minor issues detected:
1. Gradle detected incorrect version of NDK -
_> Configure project :app
2021-01-19T11:16:48.6826915Z Checking the license for package NDK (Side by side) 21.1.6352462 in /usr/local/lib/android/sdk/licenses
2021-01-19T11:16:48.6827494Z License for package NDK (Side by side) 21.1.6352462 accepted.
2021-01-19T11:16:48.6828028Z Preparing "Install NDK (Side by side) 21.1.6352462 (revision: 21.1.6352462)".
2021-01-19T11:18:09.0800388Z "Install NDK (Side by side) 21.1.6352462 (revision: 21.1.6352462)" ready.
2021-01-19T11:18:09.0801346Z Installing NDK (Side by side) 21.1.6352462 in /usr/local/lib/android/sdk/ndk/21.1.6352462
2021-01-19T11:18:09.0801881Z "Install NDK (Side by side) 21.1.6352462 (revision: 21.1.6352462)" complete.
2021-01-19T11:18:09.3817717Z "Install NDK (Side by side) 21.1.6352462 (revision: 21.1.6352462)" finished._

2. $GRADLE_HOME variable is available but I can't use it. Seems like PATH is incorrect, because we can't access any file there. This is minor as we are sill using gradlew.

**Comment by sashaweiss** [comment]
This broke our CI as well - would love for there to be an announcement channel for stuff like this. Quick note that the docs [here](https://github.com/actions/virtual-environments/blob/main/images/macos/macos-10.15-Readme.md) for the macos-10.15 installed software (and probably in the lists for other images) don't show this as updated, noticed when I went googling for a solution.

**Comment by AlenaSviridenko** [comment]
Hi all,
we are started working on rolling back the image due to huge impact. It can take 1-2 days.

We will revisit strategy of NDK support, and will rollout image with the fix next week.
Sorry for inconveniences and thank you for your patience.

**Comment by carstenhag** [comment]
@sashaweiss About the readme being out of date: The readmes only get updated after the rollout is 100% through. No clue where I saw it, but a contributor mentioned this

**Comment by miketimofeev** [comment]
@carstenhag @sashaweiss the proper link to the readme can be found in the set up job step 
![image](https://user-images.githubusercontent.com/48208649/105201096-8a8e6b00-5b51-11eb-81d6-e1bea8ace3fa.png)

**Comment by sashaweiss** [comment]
@miketimofeev thanks for the tip! I'll use that next time, that'll be handy.

**Comment by typeoneerror** [comment]
Earlier in the week I bumped to 22.x and a few actions have run fine. 

This morning...

> No version of NDK matched the requested version 22.0.7026061. Versions available locally: 21.3.6528147

Was this rolled back in `ubuntu-latest`?

**Comment by maxim-lobanov** [comment]
Unfortunately, yes. We have got a lot of reports from customers about breaking builds with NDK 22.x. Also we have got feedback from Xamarin.Android team - NDK 22 is not supported ye. We have to roll images back and freeze NDK 21 on images for a while. A bit more context in https://github.com/actions/virtual-environments/issues/2481#issuecomment-763700114

**Comment by AlenaSviridenko** [comment]
Closing this issue, because we reverted image with r22 and will deploy this week with default to r21.

**Comment by amq** [comment]
Here we go again https://github.com/actions/virtual-environments/issues/4144
