### ISSUE TITLE
Update/Add GNU automake on Mac OS hosts

### ISSUE THREAD

**Issue by daztucker** [actions/virtual-environments#2423]
**Tool information**
- Tool name: GNU Automake
- Tool license: GPL
- Add or update? Add
- Desired version: latest production release (currently 1.16.3).
- Approximate size: 2.3MB installed
- If this is an add request:
  - Brief description of tool: "GNU Automake is a tool for automatically generating Makefile.in files compliant with the GNU Coding Standards."
  - URL for tool's homepage: https://www.gnu.org/software/automake/
  - Provide a basic test case to validate the tool's functionality:

mkdir test
cd test
touch AUTHORS ChangeLog COPYING INSTALL Makefile.am NEWS README install-sh missing test.c
cat >configure.ac <<EOD
AC_INIT([test], [1.0])
AC_CONFIG_SRCDIR([test.c])
AM_INIT_AUTOMAKE
AC_CONFIG_FILES([Makefile])
EOD
aclocal
automake
[ $? = 0 ] && echo success

**Area for Triage**: C/C++

**Question, Bug, or Feature?**: Feature

**Virtual environments affected**
- [x] macOS 10.15
- [x] macOS 11.0

**Can this tool be installed during the build?**
Yes, either:
brew install automake
or manually:
https://ftp.gnu.org/gnu/automake/automake-1.16.3.tar.xz
xz -dc automake-1.16.3.tar.xz | tar xf -
cd automake-1.16.3
./configure
make
make install

**Tool installation time in runtime**
Approx 10 seconds.

**Are you willing to submit a PR?**
My understanding is that's not currently possible for Mac OS X hosts.

**Comment by miketimofeev** [comment]
Hi @daztucker!
Considering tool installation time and package size we wouldn't like to add it to the image.
I'm going to close the issue but please feel free to contact us if you have any concerns.
Thank you!
