### ISSUE TITLE
Add Zulu JDK to MS hosted agent

### ISSUE THREAD

**Issue by gkgaurav31** [actions/virtual-environments#2424]
The Azure App Service uses Zulu JDKs. However, the MS hosted agents use AdoptJDK. The best-practice is to maintain same JRE/JDK version in build and production environment. Please add Zulu JDK as well for consistency.

**Comment by miketimofeev** [comment]
Hi @gkgaurav31!
We've switched from Zulu openjdk to Adopt openjdk intentionally — https://github.com/actions/virtual-environments/issues/1057
Currently, we don't have any plans to add additional jdks to the images.
Please consider using the following task\action, they use Zulu jdk as far as I know:
- [Azure DevOps — Java Tool Installer task](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/tool/java-tool-installer?view=azure-devops)
- [Actions — setup-java](https://github.com/actions/setup-java)
