### ISSUE TITLE
ANDROID_NDK_ROOT environment variable should be preset

### ISSUE THREAD

**Issue by dmitry-shibanov** [actions/virtual-environments#2426]
**Description**
Add `ANDROID_NDK_HOME` and `ANDROID_NDK_ROOT` to the all images. According to discussion: `ANDROID_NDK_HOME` and `ANDROID_NDK_ROOT` are widely used by many other softwares. In most cases, If `ANDROID_NDK_HOME` is not defined, the value in `ANDROID_NDK_ROOT` is used. but some software only use `ANDROID_NDK_HOME`, others only use `ANDROID_NDK_ROOT`. so, both are preset is the best.
- Discussion: https://github.com/actions/virtual-environments/discussions/2399
### References:
- https://github.com/openssl/openssl/issues/11205
- https://github.com/android/ndk-samples

**Question, Bug, or Feature?**:
Feature request

**Virtual environments affected**
- [x] Ubuntu 16.04
- [x] Ubuntu 18.04
- [x] Ubuntu 20.04
- [x] macOS 10.15
- [x] macOS 11.0
- [x] Windows Server 2016 R2
- [x] Windows Server 2019

**Comment by ystefinko** [comment]
vote for this feature!

**Comment by nikita-bykov** [comment]
The [PR](https://github.com/actions/virtual-environments/pull/2472) has been merged. The new environment variables will be available after the next vm rollout.

**Comment by miketimofeev** [comment]
ANDROID_NDK_ROOT variable is now available across all the images
