### ISSUE TITLE
MacOS brew install mono-libdgiplus failure

### ISSUE THREAD

**Issue by michaelgsharp** [actions/virtual-environments#2428]
**Description**  
After the recent changes to the MacOS hosted pool, when doing `brew install mono-libgdiplus` it lists `python@3.9` as a dependency. This dependency fails to install with this error:
```
Error: The `brew link` step did not complete successfully
The formula built, but is not symlinked into /usr/local
Could not symlink bin/2to3
Target /usr/local/bin/2to3
already exists. You may want to remove it:
  rm '/usr/local/bin/2to3'
```

Python 3.9 did not used to be a dependency ([prior passing build](https://dev.azure.com/dnceng/public/_build/results?buildId=926030&view=logs&j=4b233af4-7b14-5f68-27c6-9c4d7ac87519&t=3202febe-17fc-5774-b8fa-63004f4cf385&l=469)), but has been added recently ([recent failed build](https://dev.azure.com/dnceng/public/_build/results?buildId=941204&view=logs&j=23576d1c-355e-5d27-4c31-0725f923794b&t=08a5e2f7-221f-519d-fb5b-6dcc3a524e60&l=2154))

**Area for Triage**:  
Apple

**Question, Bug, or Feature?**:  
Bug

**Virtual environments affected**  
- [x] macOS 10.14

**Expected behavior**  
Since python 3.9 is already installed, I expected either the installation to not happen, or to not fail.

**Actual behavior**  
Install fails because python 3.9 is already installed.

**Repro steps**  

1. Run build pipeline in MacOS Hosted pool
2. `brew install mono-libgdiplus`

**Comment by michaelgsharp** [comment]
I see you already have a PR merged in (#2326) just waiting for the image rollout. Do you have a rough ETA on when that may happen?

**Comment by al-cheb** [comment]
Hello, @michaelgsharp 
Sorry for the inconvenience. Waiting for a new image rollout with fix - https://github.com/actions/virtual-environments/pull/2326. Temporary workaround - https://github.com/actions/virtual-environments/issues/2322#issuecomment-749211076

**Comment by michaelgsharp** [comment]
Thanks for the workaround, I will go ahead and apply that. Thanks for your help and quick response!

**Comment by michaelgsharp** [comment]
Closing this issue as the provided workaround worked and builds passed.
