### ISSUE TITLE
Install-PHP.ps1 attempt to enable openssl extension appears to be incorrect

### ISSUE THREAD

**Issue by mcdurdin** [actions/virtual-environments#2436]
**Description**  

Changes in #588 to enable PHP openssl extension make the following string replacement in [PHP.ini](https://github.com/MIchaelMainer/virtual-environments/blob/030197e844770f3fe5bc46c0544499f43655f9aa/images/win/scripts/Installers/Install-PHP.ps1#L17):

```
-replace 'extension=";php_openssl.dll"','extension_dir = "php_openssl.dll"'
```

This has two problems:

1. It does nothing because the search string will not be matched (the search string should probably be `;extension=openssl`)
2. The replacement should be `extension=openssl`, not touching the `extension_dir` property...

**Area for Triage**:

PHP

**Question, Bug, or Feature?**:  

Bug

**Virtual environments affected**  
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [x] Windows Server 2019

**Comment by miketimofeev** [comment]
Hi @mcdurdin! Thanks for reporting this problem, we'll make an investigation and prepare a fix.

**Comment by LeonidLapshin** [comment]
Hey, @mcdurdin !
We have fixed this issue, it will be released on the next week with Windows image updates.

**Comment by mcdurdin** [comment]
Thank you 😁

**Comment by miketimofeev** [comment]
We've finished image deployments!
