### ISSUE TITLE
[ubuntu, windows] Default Go version will be set to 1.15 on February, 8

### ISSUE THREAD

**Issue by AlenaSviridenko** [actions/virtual-environments#2447]
**Breaking changes**
We will set Go 1.15 as a default version for Ubuntu and Windows images.

**Target date**
Image deployment will start February, 8 and will take 3-4 days

**The motivation for the changes**
Go 1.15 is the most popular version on our images, so we'd like to provide it as a default one.

**Possible impact**
If your project is incompatible with Go 1.15 — your builds will be broken.

**Virtual environments affected**
- [x] Ubuntu 16.04
- [x] Ubuntu 18.04
- [x] Ubuntu 20.04
- [ ] macOS 10.13
- [ ] macOS 10.14
- [ ] macOS 10.15
- [ ] macOS 11.0
- [x] Windows Server 2016 R2
- [x] Windows Server 2019

**Mitigation ways**
Consider using [actions/setup-go](https://github.com/marketplace/actions/setup-go-environment) for GitHub Actions and [GoTool](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/tool/go-tool?view=azure-devops) for Azure DevOps to install required Go version in runtime.

**Comment by FelipeF1198** [comment]
> **Breaking changes**
> We will set Go 1.15 as a default version for Ubuntu and Windows images.
> 
> **Target date**
> Image deployment will start February, 8 and will take 3-4 days
> 
> **The motivation for the changes**
> Go 1.15 is the most popular version on our images, so we'd like to provide it as a default one.
> 
> **Possible impact**
> If your project is incompatible with Go 1.15 — your builds will be broken.
> 
> **Virtual environments affected**
> 
> * [x]  Ubuntu 16.04
> * [x]  Ubuntu 18.04
> * [x]  Ubuntu 20.04
> * [ ]  macOS 10.13
> * [ ]  macOS 10.14
> * [ ]  macOS 10.15
> * [ ]  macOS 11.0
> * [x]  Windows Server 2016 R2
> * [x]  Windows Server 2019
> 
> **Mitigation ways**
> Consider using [actions/setup-go](https://github.com/marketplace/actions/setup-go-environment) for GitHub Actions and [GoTool](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/tool/go-tool?view=azure-devops) for Azure DevOps to install required Go version in runtime.

**Comment by andy-mishechkin** [comment]
Default Go version has been set to 1.15. PR has been merged

**Comment by miketimofeev** [comment]
All the deployments finished
