### ISSUE TITLE
Add Qt

### ISSUE THREAD

**Issue by kaylangan** [actions/virtual-environments#245]
Copied over from https://github.com/microsoft/azure-pipelines-image-generation/issues/272

**Tool information**
- Tool name: Qt
- Add or update? Add
- Desired version: latest
- Approximate size: 
- If this is an add request:
  - Brief description of tool: 
  - URL for tool's homepage: 

**Area for Triage**: Common tools

**Question, Bug, or Feature?**: Feature

**Virtual environments affected**
- [x] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [x] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [x] Windows Server 2019

**Can this tool be installed during the build?**

**Are you willing to submit a PR?**

**Comment by linville** [comment]
See also #8.

**Comment by simonsan** [comment]
Now that there is a general Qt Account required to download and install, it would be pretty lovely to preinstall it to spare people the hussle installing it manually during their CI-builds and use their cache for it.

https://www.qt.io/blog/qt-offering-changes-2020

**Comment by skalee** [comment]
On the other hand, it is quite important to be able to choose Qt version in case the newest one is buggy or introduces breaking changes. Soon this will be even more important, as LTS versions will be available only for those who have paid plans. Preinstalled Qt may work in many cases, but for many this won't be flexible enough.

**Comment by simonsan** [comment]
@skalee What do you propose as a solution to this whole problem?

**Comment by skalee** [comment]
@simonsan There are some ways to install Qt. For now I suggest checking out this simple Python script: https://github.com/engnr/qt-downloader. Although it does not install additional components like Qt Web Engine, I am pretty sure that enhancing it is quite simple.

Alternatively, there is my own solution: https://github.com/skalee/non-interactive-qt-installer. Unfortunately it stopped working recently (they made changes to the online installer, precisely Qt account is now required). While it's probably fixable, I am not relying on this tool any more and I don't think I'll put much effort in maintaining. Nevertheless, pull requests are welcome, so is forking, obviously.

Also, this thread in Qt bug tracker has some information on topic and in future may reveal other approaches: https://bugreports.qt.io/browse/QTIFW-166.

This is what we have now. Proper headless installer is expected to arrive in Qt 6 later this year:

> The good piece of news is that we continue developing the installer framework to support binary installations in Qt 6. And yes, there is now headless installation in the 2020 roadmap. There are other urgent things we need to finish, so the support should be available in mid Q3 according to current plans. 
(https://bugreports.qt.io/browse/QTIFW-166?focusedCommentId=489428&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-489428)

**Comment by simonsan** [comment]
@skalee Yeah, that is the main problem already mentioned here in this issue. 
[aqtinstall](https://github.com/miurahr/aqtinstall/) is a working and maintained solution. Here as a GHA - https://github.com/jurplel/install-qt-action

So it's not that we are in need of an action/solution for this. It's about the time and resources to install and cache it. You might have misunderstood the problem here.

**Comment by thejoebourneidentity** [comment]
Adding Qt is not something we're going to put on our roadmap at this time due to maintainability concerns. We recommend continuing to install Qt at run-time and selecting the specific version you need.

**Comment by Shatur95** [comment]
It would be nice to have at least latest LTS version provided... As for Boost, for example.
