### ISSUE TITLE
Request: Add environment variable reference/list

### ISSUE THREAD

**Issue by carstenhag** [actions/virtual-environments#2452]
Hello there! I really like the image Readme's like https://github.com/actions/virtual-environments/blob/main/images/macos/macos-10.15-Readme.md. But when I need to add/write scripts for the CI runner, I am always confused as on what environment variables are available and how they are called.

Is it $ANDROID_HOME, $ANDROID_SDK_HOME, $ANDROID_SDK_ROOT or what is it? I pretty much have to find out doing trial and error.

**Comment by miketimofeev** [comment]
Hi @carstenhag!
Thanks for your proposal! We'll investigate how many custom env variables (like $ANDROID_HOME, $ANDROID_SDK_HOME, etc) we have and think about the best way of adding them to the docs. Probably they can be added to the related tool section as we currently do for Java
![image](https://user-images.githubusercontent.com/48208649/104712843-2411e300-5734-11eb-9d57-67c83cba90e9.png)

**Comment by carstenhag** [comment]
Sounds good!

**Comment by maxim-lobanov** [comment]
Found the following environment variables that are mentioned in documentation:
```
All platforms:
ANDROID_HOME
ANDROID_SDK_ROOT
ANDROID_NDK_HOME
CHROMEWEBDRIVER
EDGEWEBDRIVER
GECKOWEBDRIVER
VCPKG_INSTALLATION_ROOT
CONDA
ANT_HOME
GRADLE_HOME
M2_HOME

Ubuntu:
GOROOT
GOROOT_1_13_X64
GOROOT_1_14_X64
GOROOT_1_15_X64
```

`ANDROID_*` and `GOROOT` definitely should be in documentation. Other variables are optional since those tools are already in PATH and variables are not needed to use. Moved this work item to backlog

**Comment by carstenhag** [comment]
Thanks for integrating this :) We can close it now imo, or is there still something to do?

**Comment by miketimofeev** [comment]
@carstenhag yes, I'm going to close the issue. Thanks for your proposal!
