### ISSUE TITLE
Update/Add PHP 7.4

### ISSUE THREAD

**Issue by qualmon** [actions/virtual-environments#2453]
**Tool information**
- Tool name: PHP
- Tool license: 
- Add or update? Add
- Desired version: 7.4
- Approximate size: 
- If this is an add request:
  - Brief description of tool: Our pipelines stopped working when you changed the default PHP version to 8.0.1
  - URL for tool's homepage: 
  - Provide a basic test case to validate the tool's functionality: 

**Area for Triage**:

**Question, Bug, or Feature?**:

**Virtual environments affected**
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [x] Windows Server 2019

**Can this tool be installed during the build?**

**Tool installation time in runtime**

**Are you willing to submit a PR?**

**Comment by maxim-lobanov** [comment]
Hello @qualmon , could you please try [setup-php](https://github.com/marketplace/actions/setup-php-action) according to https://github.com/actions/virtual-environments/issues/2416 ?

**Comment by qualmon** [comment]
Hi @maxim-lobanov, can you give me any pointers on how to get started? We are running Azure Pipelines through Microsoft hosted agents. The documentation only covers changing php version on the ubuntu virtual environment.

**Comment by miketimofeev** [comment]
@qualmon Could you please try running
`choco install php --version=7.4.14 --allow-downgrade` as the very first step of your pipeline? Does it help?

**Comment by qualmon** [comment]
Thanks, that kind of works. It's installing PHP v7.4.14 but it's extremely slows (takes about 2 minutes). Also subsequent steps fail with php: command not found, even though it looks like the new path is added to the path.

**Comment by miketimofeev** [comment]
@qualmon oh, sorry, haven't thought about the path. Can you try installing PHP into the same directory as 8.0?
`choco install php --version=7.4.14 --allow-downgrade -package-parameters='"/InstallDir:C:\tools\php"'`

**Comment by qualmon** [comment]
That works, thank you. It was a bit faster the second time (or maybe it's random) but still quite slow (47 seconds).

**Comment by maxim-lobanov** [comment]
Hello @qualmon , we are glad to hear that workaround above helped you.
Sorry for inconvenience, but we wouldn't like to bake PHP 7.4 into images by default due to maintenance concerns (installing multiple PHP versions side by side on Windows images). Currently, we install the latest stable version.

Please let us know if you have any concerns
