### ISSUE TITLE
Set AGENT_TOOLSDIRECTORY in packer template instead of in Install-Ruby.ps1

### ISSUE THREAD

**Issue by ryanspletzer** [actions/virtual-environments#2456]
AGENT_TOOLSDIRECTORY environment variable is set in `Install-Ruby.ps1` [here](https://github.com/actions/virtual-environments/blob/69370b14c4d6cb9685655e06917ec6a507a37e22/images/win/scripts/Installers/Install-Ruby.ps1#L101-L104) whereas I think it makes more sense to have it be set in the packer template as this variable is referenced in multiple other install scripts. PR incoming with suggested change.

https://github.com/actions/virtual-environments/blob/69370b14c4d6cb9685655e06917ec6a507a37e22/images/win/scripts/Installers/Install-Ruby.ps1#L101-L104

**Comment by maxim-lobanov** [comment]
Closing an issue since PR was merged.
Thank you for contribution!
