### ISSUE TITLE
Update cabal-install

### ISSUE THREAD

**Issue by juhp** [actions/virtual-environments#2458]
**Tool information**
- Tool name: cabal-install
- Add or update?  Update
- Desired version: 3.2.0.0
- Approximate size: 

**Area for Triage**:

Haskell

**Question, Bug, or Feature?**:
Bug

**Virtual environments affected**
- [x] Ubuntu 16.04
- [x] Ubuntu 18.04
- [x] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Can this tool be installed during the build?**

**Tool installation time in runtime**

**Are you willing to submit a PR?**

Probably

**Details**:
The problem is that the latest version (3.4.0.0) of cabal-install in hvr's ppa is a _prerelease_ (RC4) but haskell-setup defaults latest to 3.2.0.0.  So with either `cabal-version: 3.2` or without one gets the warning:

```
  Warning: cabal 3.2.0.0 was not found in the cache. It will be downloaded.
  If this is unexpected, please check if version 3.2.0.0 is pre-installed.
  The list of pre-installed versions is available here: https://help.github.com/en/actions/reference/software-installed-on-github-hosted-runners
  The above list follows a common haskell convention that the two latest major releases of cabal are commonly supported.
  If the list is outdated, please file an issue here: https://github.com/actions/virtual-environments
  by using the appropriate tool request template: https://github.com/actions/virtual-environments/issues/new/choose
  Attempting to install cabal-install 3.2 using apt-get
```

Admittedly cabal-install-3.4 should be released RSN but the RC's have already been out for months: maybe they are waiting for ghc 9.0 to be released, I dunno?

My suggestion is to override cabal-install to install 3.2.0.0 in the image and wait for 3.4 to be released but changing it back.
I mean here: https://github.com/actions/virtual-environments/blob/main/images/linux/scripts/installers/haskell.sh#L29
It is lucky that the ppa does not have a ghc-9.0 pre-release build yet. ;-)
Actually even ghc-8.10.3 is rather on the new side: Stackage LTS is still on 8.8.4.

I could open a haskell/actions ticket too to confirm about cabal-install.

**Comment by juhp** [comment]
To add to this: I don't feel the solution taken in https://github.com/actions/virtual-environments/blob/main/images/linux/scripts/installers/haskell.sh is good - it is not really safe to assume that the latest version of ghc or cabal-install is always stable.
So in my opinion it would be better to hard-code it for now, at least until a better solution can be found.

Basically the latest versions defined by haskell/actions should be used.

**Comment by nikita-bykov** [comment]
We have updated Cabal installation on Ubuntu and now it installs via GHCup. Images with changes will be rolled out around next week.

**Comment by miketimofeev** [comment]
@juhp we have deployed Ubuntu images with Cabal 3.2.0.0, thanks for your proposal!
I'm going to close the issue, please feel free to contact us if you have any concerns.

**Comment by juhp** [comment]
Thank you looking forward to test this.

In the meantime ghc-9.0.1 was released and I believe I saw it is already getting pulled in too :-(
