### ISSUE TITLE
python3 command missing on Windows runners

### ISSUE THREAD

**Issue by henryiii** [actions/virtual-environments#2461]
**Description**  
Currently, the command `python` is supported on all platforms, with some random version of Python, often Python 2. (See https://docs.github.com/en/actions/guides/building-and-testing-python#using-the-default-python-version). The command `python3` at least promises a 3.x version of Python; however, it is oddly absent on Windows runners. It would make it much easier to use this cross platform, especially in composite actions, where something simple is being done using Python but Python 3 is required because 2 is a year past EOL and packaging/pip is dropping support now.

`python` is Python 3.7 on the current windows-latest, I would simply like `python3` to also be available and point at the same Python as `python`.

**Area for Triage**:  

Python

**Question, Bug, or Feature?**:  
Somewhere between a bug or a feature.

**Virtual environments affected**  
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11.0
- [x] Windows Server 2016 R2
- [x] Windows Server 2019

**Comment by maxim-lobanov** [comment]
I don't have objections about adding symlink `python3` -> `python` on Windows images. Moved to backlog

**Comment by vsafonkin** [comment]
Hello @henryiii, the `python3` symlink was added to python on Windows and will be available in the next release of Windows images (in about two weeks).

**Comment by henryiii** [comment]
Fantastic, thank you very much!

**Comment by miketimofeev** [comment]
We've finished windows image deployments with python3 symlink!
