### ISSUE TITLE
Install Azure Functions Core Tools v3

### ISSUE THREAD

**Issue by mnriem** [actions/virtual-environments#2464]
**Tool information**
- Tool name: Azure Functions Core Tools
- Tool license: MIT
- Add or update? Add
- Desired version: Latest
- Approximate size: 
- If this is an add request:
  - Brief description of tool: Tool for managing Azure Functions on Azure
  - URL for tool's homepage: https://docs.microsoft.com/en-us/azure/azure-functions/functions-run-local
  - Provide a basic test case to validate the tool's functionality: func

**Area for Triage**:
Unsure

**Question, Bug, or Feature?**:
Feature

**Virtual environments affected**
All

**Can this tool be installed during the build?**
See https://docs.microsoft.com/en-us/azure/azure-functions/functions-run-local

**Tool installation time in runtime**
Minutes

**Are you willing to submit a PR?**
Sure

**Comment by maxim-lobanov** [comment]
The tool can be installed in runtime pretty quick:
```
# macOS (25 seconds)
brew tap azure/functions
brew install azure-functions-core-tools@3
# if upgrading on a machine that has 2.x installed
brew link --overwrite azure-functions-core-tools@3

# Ubuntu (40 seconds)
sudo apt-get install azure-functions-core-tools-3

# Windows (50 seconds)
Install-Binary -Url "https://go.microsoft.com/fwlink/?linkid=2135274" -Name "func-cli-x64.msi"
```

Usually, we don't pre-install tools that could be easily installed in runtime on images. We would like to keep this request opened for while to see popularity

**Comment by asklar** [comment]
@maxim-lobanov FWIW we (RNW) could probably use this too; we have a PR out to introduce this dependency were planning of consuming it via choco; https://github.com/microsoft/react-native-windows/pull/6900/
CC @nickgerleman

**Comment by AlenaSviridenko** [comment]
Hi!
after some internal discussions and given tool popularity and pretty fast installation time in runtime (steps are provided above), we'd rather not to add this tool to the image. 
I am closing it. Please, feel free to create a new one in case of any other questions.
Thanks.
