### ISSUE TITLE
[Ubuntu 20.04] Apt not installing dependencies

### ISSUE THREAD

**Issue by raphaelreyna** [actions/virtual-environments#2465]
**Description**  
I am trying to install [MiKTeX](https://miktex.org/howto/install-miktex-unx) using an install script that works on the ubuntu:20.04 Docker image but not with the Ubuntu 20.04 image in this repo.

**Area for Triage**:  
Packages

**Question, Bug, or Feature?**:  
Bug

**Virtual environments affected**  
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [x] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Expected behavior**  
A working MiKTeX installation.

**Actual behavior**  
MiKTeX is unable to be installed due to missing dependencies that are uninstallable.
```
 miktex : Depends: libc6 (>= 2.29) but 2.27-3ubuntu1.4 is to be installed
          Depends: libhunspell-1.7-0 but it is not installable
          Depends: libicu66 (>= 66.1-1~) but it is not installable
          Depends: libqt5core5a (>= 5.12.2) but 5.9.5+dfsg-0ubuntu2.5 is to be installed
          Depends: libqt5widgets5 (>= 5.12.2) but 5.9.5+dfsg-0ubuntu2.5 is to be installed
```

**Repro steps**  
Run this installation script:
```
#! /bin/bash

# Ensure the script doesnt hang waiting for user input
export DEBIAN_FRONTEND=noninteractive

# Add packages needed for adding a new repo, then add its key and the repo itself
echo "Installing packages needed for adding repositories ..."
apt update && apt install -y tzdata gnupg ca-certificates
apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys D6BC243565B2087BC3F897C9277A7293F59E4889
echo "deb http://miktex.org/download/ubuntu focal universe" >> /etc/apt/sources.list.d/miktex.list

# Refresh repos and install miktex
echo "Installing MiKTeX ..."
apt update && apt install -y --no-install-recommends miktex

echo "Running post-installation processes for MiKTeX ..."
# Miktex needs to run some post-installation scripts
miktexsetup --shared=yes finish
initexmf --admin --set-config-value [MPM]AutoInstall=1
mpm --find-updates

echo "Finished installing MiKTeX!"
```

**Comment by al-cheb** [comment]
Hello, @raphaelreyna 
I am not able to reproduce the issue from my side.

```
jobs:
  compile:
    runs-on: ubuntu-20.04
    steps:
      - name: Install MiKTeX 
        run: |
          # Ensure the script doesnt hang waiting for user input
          export DEBIAN_FRONTEND=noninteractive
          # Add packages needed for adding a new repo, then add its key and the repo itself
          echo "Installing packages needed for adding repositories ..."
          sudo apt update && sudo apt install -y tzdata gnupg ca-certificates
          sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys D6BC243565B2087BC3F897C9277A7293F59E4889
          echo "deb http://miktex.org/download/ubuntu focal universe" | sudo tee -a /etc/apt/sources.list.d/miktex.list
          # Refresh repos and install miktex
          echo "Installing MiKTeX ..."
          sudo apt update && sudo apt install -y --no-install-recommends miktex
          echo "Running post-installation processes for MiKTeX ..."
          # Miktex needs to run some post-installation scripts
          sudo miktexsetup --shared=yes finish
          sudo initexmf --admin --set-config-value [MPM]AutoInstall=1
          sudo mpm --find-updates
          echo "Finished installing MiKTeX!"
```
![Uploading image.png…]()

**Comment by raphaelreyna** [comment]
Hi @al-cheb, thanks for the quick response!
I see you used the ubuntu-20.04 image while the error I was getting was while using the ubuntu-latest image.

Based upon [this post](https://github.blog/changelog/2020-10-29-github-actions-ubuntu-latest-workflows-will-use-ubuntu-20-04/) I thought I was using ubuntu-20.04 but looking back through the logs it looks like ubuntu-latest was still an alias for ubuntu-18.04.

Switching from using ubuntu-latest to ubuntu-20.04 has solved the issue for me.

Any idea on when we can expect the migration to ubuntu-20.04 to be completed?

**Comment by al-cheb** [comment]
@raphaelreyna, To install on Ubuntu 18.04 you should use repo for [bionic](https://miktex.org/download):
`echo "deb http://miktex.org/download/ubuntu bionic universe" | sudo tee /etc/apt/sources.list.d/miktex.list` 
or
`echo "deb http://miktex.org/download/ubuntu $(lsb_release -cs) universe" | sudo tee /etc/apt/sources.list.d/miktex.list`

![image](https://user-images.githubusercontent.com/47745270/104946508-35285180-59cb-11eb-8d34-33969fb3e6d0.png)

сс @AlenaSviridenko

**Comment by AlenaSviridenko** [comment]
Hi @raphaelreyna,
current ETA for migration to be completed is the middle of February if there will be no unexpected delays 🤞.
Thank you for your patience.

**Comment by raphaelreyna** [comment]
@al-cheb thanks for your help!

@AlenaSviridenko thanks for the info! Is it safe to assume that _all_ workflows with the `ubuntu-latest` runner label will be run on Ubuntu 18.04 until mid February?

**Comment by AlenaSviridenko** [comment]
We can guarantee that all workflows within one account (or organization) will run on the same OS version (there should be no cases when one`ubuntu-latest` workflow runs on 18.04 and the other one on 20.04), but we do transition by portions of accounts, so we can switch some accounts even before mid February.
