### ISSUE TITLE
Set HOMEBREW_NO_AUTO_UPDATE and HOMEBREW_NO_INSTALL_CLEANUP on Ubuntu and macOS runners by default

### ISSUE THREAD

**Issue by smorimoto** [actions/virtual-environments#2466]
**Description**

Since update and cleanup are invoked in the CI environment each time, the installation process using brew is very slow. However, these are generally not needed in CI environments and we can disable them using the following environment variables:

- `HOMEBREW_NO_AUTO_UPDATE`
- `HOMEBREW_NO_INSTALL_CLEANUP`

**Area for Triage**: 

None.

**Question, Bug, or Feature?**:  

Other.

**Virtual environments affected**  
- [x] Ubuntu 16.04
- [x] Ubuntu 18.04
- [x] Ubuntu 20.04
- [x] macOS 10.15
- [x] macOS 11.0
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Comment by maxim-lobanov** [comment]
It is already done for macOS: https://github.com/actions/virtual-environments/blob/main/images/macos/provision/configuration/environment/bashrc#L30
```
export HOMEBREW_NO_AUTO_UPDATE=1
export HOMEBREW_CLEANUP_PERIODIC_FULL_DAYS=3650
```

`HOMEBREW_CLEANUP_PERIODIC_FULL_DAYS` is equivalent of `HOMEBREW_NO_INSTALL_CLEANUP` and says that brew cleanup will be invoked only in case if image is not updated for 10 years :) See https://github.com/Homebrew/brew/pull/9477

It makes sense to set the same variables for Ubuntu.

**Comment by smorimoto** [comment]
Are they really included in macOS images that are already deployed?

**Comment by maxim-lobanov** [comment]
@smorimoto , Yes, these variables were added to macOS a long time ago

**Comment by smorimoto** [comment]
Hm, it seems that `$HOMEBREW_CLEANUP_PERIODIC_FULL_DAYS` is not included yet. This probably caused the cleanup to run and the process to be very slow. It's good to know that it will be included in the next deployment anyway.

**Comment by dsame** [comment]
The related PR has been merged and the next image update will include environment chanegs

**Comment by smorimoto** [comment]
Cool. Is there an ETA?

**Comment by miketimofeev** [comment]
@smorimoto highly likely the end of next week

**Comment by smorimoto** [comment]
Got it. Thanks.

**Comment by smorimoto** [comment]
Already deployed?

**Comment by miketimofeev** [comment]
@smorimoto about 80% of environments judging by the status badge
![image](https://user-images.githubusercontent.com/48208649/106025202-90e49000-60d9-11eb-9502-771cc6aee4d0.png)

**Comment by smorimoto** [comment]
@maxim-lobanov Great.

**Comment by miketimofeev** [comment]
@smorimoto deployment finished, $HOMEBREW_CLEANUP_PERIODIC_FULL_DAYS set to 3650 and $HOMEBREW_NO_AUTO_UPDATE set to 1

**Comment by smorimoto** [comment]
@miketimofeev Thanks!
