### ISSUE TITLE
Add CHROMEDRIVER_BIN variable to environment

### ISSUE THREAD

**Issue by cdunklau** [actions/virtual-environments#248]
As of the 20200102.1 update, chromedriver is installed, but it doesn't look like the CHROMEDRIVER_BIN variable gets added to the environment. This would be nice to have, in the same vein as CHROME_BIN.

**Tool information**
- Tool name: chromedriver
- Add or update? Tweak env var for existing tool
- Desired version: N/A
- Approximate size: N/A

**Area for Triage**:
Testing and code coverage

**Question, Bug, or Feature?**:
Feature

**Virtual environments affected**
I need it for Linux, but the change is probably useful for users of the other images
- [ ] macOS 10.15
- [x] Ubuntu 16.04 LTS
- [x] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Can this tool be installed during the build?**
N/A

**Are you willing to submit a PR?**
Sure

**Comment by kaylangan** [comment]
@cdunklau thanks for the feedback. It'd be great if you submitted a PR for this change!

**Comment by cdunklau** [comment]
Looks like #262 duplicates this, but I didn't realize the env var was documented on the other VMs. It's been resolved in #269, but N.B. the env var name is `CHROMEWEBDRIVER`, not `CHROMEDRIVER_BIN` as I initially suggested.
