### ISSUE TITLE
Unable to build windows2019 Install-Docker exits not 0

### ISSUE THREAD

**Issue by tehho** [actions/virtual-environments#2484]
**Description**  
Unable to build windows2019. Get an error on Install-Docker.ps1

**Area for Triage**:  
Area: Deployment/Release

**Question, Bug, or Feature?**:  
Bug

**Virtual environments affected**  
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [X] Windows Server 2019

**Expected behavior**  
Installation to complete. 

**Actual behavior**  
2021-01-19T12:22:07.4918893Z [1;32m==> vhd: Provisioning with powershell script: /workspace/31/s/images/win/scripts/Installers/Install-Docker.ps1[0m
2021-01-19T12:22:09.6756553Z [0;32m    vhd: Install-Package Docker[0m
2021-01-19T12:22:16.7073866Z [1;32m==> vhd: Provisioning step had errors: Running the cleanup provisioner, if present...[0m

**Repro steps** 
This is our main part of our azure-pipelines.yaml file.
`
cd images/win
packer_data=$(cat windows2019.json | jq ".variables.install_password = \"$(WINDOWS_PASSWORD)\"")

packer_data=$(echo $packer_data | jq '.variables.vm_size = "Standard_F8s_v2"')
packer_data=$(echo $packer_data | jq '.variables.image_name = "{{env `ARM_IMAGE_NAME`}}"')
packer_data=$(echo $packer_data | jq '.builders[0].managed_image_name = "{{user `image_name`}}"')
packer_data=$(echo $packer_data | jq '.builders[0].managed_image_resource_group_name = "{{user `resource_group`}}"') 

packer_data=$(echo $packer_data | jq 'del(.builders[0].resource_group_name)')
packer_data=$(echo $packer_data | jq 'del(.builders[0].storage_account)')
packer_data=$(echo $packer_data | jq 'del(.builders[0].capture_container_name)')
packer_data=$(echo $packer_data | jq 'del(.builders[0].capture_name_prefix)')
packer_data=$(echo $packer_data | jq 'del(.variables.storage_account)')

echo ${packer_data} > temp.json

packer -v
\# PACKER_LOG=1 packer build -on-error=abort temp.json # debug
packer build temp.json
`

**Other**
I can run the command without problem on the machine after -on-error=abort. 
Guessing it can't handle the background progress of the script

**Comment by al-cheb** [comment]
Hello, @tehho 
Are you able to reproduce the issue with changes?
1. packer version 1.6.2
2. vm_size:  "vm_size": "Standard_DS4_v2"

**Comment by tehho** [comment]
Running with packer 1.6.6 atm. 

"vm_size": "Standard_DS4_v2" seems to work. 
Succeeded beyond Install-Docker.ps1 atleast.

We're able to build ubuntu-1804 on Standard_F8s_v2. Changed to this sku to speed up the installation process.

Will post an update when build finishes

**Comment by tehho** [comment]
Build finished without problems.
Guess Series-F is not docker ready?

**Comment by miketimofeev** [comment]
@tehho we've faced the same issue with Standard_D8s_v4, which is in combining with premium storage is the fastest option for a build (about 5-5.5h), sometimes docker installation passed, sometimes not, both on Win16 and Win19. We're trying to find the root cause at the moment.
