### ISSUE TITLE
Update/Add cpan

### ISSUE THREAD

**Issue by JJ** [actions/virtual-environments#2487]
**Tool information**
- Tool name: cpan
- Tool license: Artistic 2.0
- Update. It's already installed, only not listed.

**Area for Triage**: 

**Question, Bug, or Feature?**: Feature

**Virtual environments affected**
- [x] Ubuntu 16.04
- [x] Ubuntu 18.04
- [x] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Can this tool be installed during the build?**

It's already installed

**Are you willing to submit a PR?**

Yep, I'm on it.

**Comment by maxim-lobanov** [comment]
Docs were updated and contain cpan version so I am closing this issue.
Thank you for contribution!
