### ISSUE TITLE
Add Apache and Nginx

### ISSUE THREAD

**Issue by shivammathur** [actions/virtual-environments#2501]
**Tool information**
- Tool name: `Apache` and `Nginx`
- Tool license: 
  - `Apache`: Apache 2.0 license
  - `Nginx`: 2-clause BSD license
- Add or update? Add
- Desired version: Apache 2.x and Nginx 1.x (latest versions in distributions)
- Approximate size: depends on OS
- If this is an add request:
  - Brief description of tool: 
    - Apache is a free and open-source cross-platform web server software.
    - Nginx is an HTTP and reverse proxy server and more.
  - URL for tool's homepage:
    - `Apache`: https://httpd.apache.org/
    - `Nginx`: https://www.nginx.com/

**Area for Triage**: Packages, Servers

**Question, Bug, or Feature?**: Feature

**Virtual environments affected**
- [X] Ubuntu 16.04
- [X] Ubuntu 18.04
- [X] Ubuntu 20.04
- [X] macOS 10.15
- [X] macOS 11.0
- [X] Windows Server 2016 R2
- [X] Windows Server 2019

**Can this tool be installed during the build?**
Yes, but it will save time in the workflows if these are installed on images.
Just like `mysql` these can be installed with their services stopped and users can start them as required in their workflows.
- `ubuntu`
```bash
sudo apt-fast install -y apache2
sudo service apache2 stop

sudo apt-fast install -y nginx
sudo service nginx stop
```

- `Windows`
```ps1
# In my testing `IIS` was using port 80, we can stop `w3svc` service and start it after installing.
Stop-Service -Name w3svc

choco install apache-httpd --params "/installLocation:C:\tools /port:80" -y --force
Stop-Service -Name Apache

choco install nginx --params "/installLocation:C:\tools /port:80" -y --force
Stop-Service -Name nginx

Start-Service -Name w3svc
```

- `macOS`
```bash
brew install httpd
sudo sed -Ei '' 's/Listen .*/Listen 80/' $(brew --prefix)/etc/httpd/httpd.conf

brew install nginx
sudo sed -Ei '' 's/listen.*/listen 80;/' $(brew --prefix)/etc/nginx/nginx.conf
```

**Tool installation time in runtime**
Test workflows: [Ubuntu](https://github.com/shivammathur/test-setup-php/actions/runs/498551812/workflow), [Windows](https://github.com/shivammathur/test-setup-php/actions/runs/498679015/workflow), [macOS](https://github.com/shivammathur/test-setup-php/actions/runs/498784388/workflow)

**Are you willing to submit a PR?**: Yes

**Comment by maxim-lobanov** [comment]
Hello @shivammathur ,
We don't have objections to pre-install these tools to images.
Feel free to submit PRs for Ubuntu and Windows (please create separate pr for every os) and we will take care about macOS (since we don't accept contributions to macOS yet).

**Comment by arvindpdmn** [comment]
I am trying a HTTPS request to Apache. Using self-signed certificate, hence `--insecure` option to curl:
`curl --insecure --user-agent "Mozilla/4.0 (compatible; MSIE 5.01; Windows NT 5.0)" -o home.html https://localhost/mysite/`
but got this error:
`curl: (35) error:1408F10B:SSL routines:ssl3_get_record:wrong version number`

[A StackOverflow entry](https://stackoverflow.com/questions/50840101/curl-35-error1408f10bssl-routinesssl3-get-recordwrong-version-number) claims it has something to do with proxy. Is there a proxy running in VM? Don't really understand this. I tried this:
`curl --proxy http://127.0.0.1/ --proxy-insecure --insecure --user-agent "Mozilla/4.0 (compatible; MSIE 5.01; Windows NT 5.0)" -o home.html https://localhost/mysite/`
but got this error:
`curl: (7) Failed to connect to 127.0.0.1 port 1080: Connection refused`
