### ISSUE TITLE
Update/Add NDK went back to 21.x from 22.x?

### ISSUE THREAD

**Issue by typeoneerror** [actions/virtual-environments#2504]
**Tool information**
- Tool name: NDK
- Add or update? re-update or version clarification
- Desired version: version shown in https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu1804-README.md (22.0.7026061)

**Area for Triage**:
Android

**Question, Bug, or Feature?**:
Bug/Question

**Virtual environments affected**
- [ ] Ubuntu 16.04
- [x] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Issue**

Earlier this week we upgraded our `ubuntu-latest` action to NDK 22.x as indicated in https://github.com/actions/virtual-environments/issues/2420. Builds worked for a day or two and now this morning we are getting:

> No version of NDK matched the requested version 22.0.7026061. Versions available locally: 21.3.6528147

Was the update rolled back or did something happen during the maintenance period last night? Perhaps we did something wrong?

**Comment by al-cheb** [comment]
Hello, @typeoneerror 

> Hi all,
> we started working on rolling back images due to huge impact. It can take 1-2 days.
> 
> We will revisit the strategy of NDK support, and will rollout image with the fix next week.
> Sorry for inconveniences and thank you for your patience.

https://github.com/actions/virtual-environments/issues/2481#issuecomment-763700114

**Comment by typeoneerror** [comment]
Thank you @al-cheb, I missed that.
