### ISSUE TITLE
Why Different Virtual Environment version was used for same workflow

### ISSUE THREAD

**Issue by sromano88-svc** [actions/virtual-environments#2505]
**Description**  
I have an already running job that was executed on ubuntu-latest (by now ubuntu-18.04) with Virtual Environment Version: 20210111.1.
Next Action build was executed with the same ubuntu-18.04 but with Virtual Environment Version: 20201210.0.
I did nothing to select one or another.

**Question, Bug, or Feature?**:  
The question is, how do I select or specify which environment version to run.
My workflow work with Virtual Environment Version: 20210111.1. since it has SAM CLI 1.15, but no with Virtual Environment Version: Version: 20201210.0 because it has SAM CLI 1.13.

**Virtual environments affected**  
- [ ] Ubuntu 16.04
- [X] Ubuntu 18.04
- [X] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Expected behavior**  
To use the latest Virtual Environment Version or allow to specify which one to use.

**Actual behavior**  
Don't know how the Virtual Environment Version is selected.

**Repro steps**  
```
jobs:
    tests:
        runs-on: ubuntu-latest
        steps:
            - run: sam --version

```

**Comment by CatTheHacker** [comment]
As new versions are rolled out, it takes few days to completely update all runners with new build. It appears your builds happened on previous build and new build.
It's not possible to pin to specific build version of GitHub actions runner.
> What image version is used in my build? Usually, image deployment takes 3-4 days, and documentation in the main branch is only updated when deployment is finished. To find out which image version and what software versions are used in a specific build, see Set up job (GitHub Actions) or Initialize job (Azure DevOps) step log.

**Comment by maxim-lobanov** [comment]
Hello @sromano88-svc , unfortunately, it is not possible to specify exact image version for now.
The reason why your builds still assigned to 20201210.0 is that we are currently rolling back 20210111.1 image due to an issue with Android NDK. We are going to deploy the new image with SAM CLI 1.15 early next week.

**Comment by bricker** [comment]
This rollout strategy can cause problems when the installed software is updated. For example, on the macOS images, if the version of Cocoapods or Bundler are updated, then running `bundle install` or `pod install` causes a discrepancy in the `*.lock` file, depending on which VM the job happened to run on and the jobs can fail. I don't mind updating my local versions of these package managers when the VMs are updated, but it's the inconsistency that makes it hard to deal with. To deal with it, I can either reset the lock files occasionally during the jobs, or install the necessary version from scratch, which negates the benefits of the pre-installed software.

I would love if we could pin jobs to a specific build version, that would give us an easy way to work around issues like this.

**Comment by maxim-lobanov** [comment]
The new set of images with SAM CLI 1.15 were deployed everywhere. Please let me know if you still experience the issue
