### ISSUE TITLE
 No runner matching the specified labels was found: macos-11.0.

### ISSUE THREAD

**Issue by scottgigante** [actions/virtual-environments#2506]
**Description**  
Big Sur doesn't seem to be available.

**Area for Triage**:  
Containers, Apple

**Question, Bug, or Feature?**:  
Bug

**Virtual environments affected**  
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [X] macOS 11.0
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Expected behavior**  
The runner should run in MacOS 11.0

**Actual behavior**  
> X This check failed.
> No runner matching the specified labels was found: macos-11.0.

**Repro steps**  
https://github.com/scottgigante/s_gd2/actions/runs/499768168

**Comment by al-cheb** [comment]
Hello, @scottgigante 
[macOS 11.0 pools will be transited to private preview. #2486](https://github.com/actions/virtual-environments/issues/2486)

**Comment by scottgigante** [comment]
Thank you @al-cheb . If you'll excuse my ignorance, this was very much not clear from [the docs](https://docs.github.com/en/actions/reference/specifications-for-github-hosted-runners).
