### ISSUE TITLE
ImageVersion vs IMAGE_VERSION

### ISSUE THREAD

**Issue by jmos5156** [actions/virtual-environments#2508]
I believe this to be a small, code clean up, change.
In both the Windows 2016 and 2019 packer files, `ImageVersion` environment variable is written in two different ways:
- IMAGE_VERSION
- ImageVersion

```
        {
            "type": "powershell",
            "inline": [
                "setx ImageVersion {{user `image_version` }} /m"
                "setx ImageOS {{user `image_os` }} /m"
            ]
        },
```
```
        {
            "type": "powershell",
            "environment_vars": [
                "IMAGE_VERSION={{user `image_version`}}",
```

Not wanting to complicate future matters and hoping to help keep a clean repo, I have looked through the scripts, functions, and modules, and can only see `ImageVersion` used in one location, Report Generator Script. It seems this may have been nothing more than an oversight as things have evolved and to keep things clean I would suggest setting this to`IMAGE_VERSION`, which 
- holds the same information
- is the same format as other env vars
- and is used in several other places.

**Comment by al-cheb** [comment]
Hello, @jmos5156 
```
 "IMAGE_VERSION={{user `image_version`}}" - temporary per step
 "setx ImageVersion {{user `image_version` }} /m" - keep on an image
```

I think we can remove `IMAGE_VERSION` per step. Would you like to prepare a PR?

**Comment by AlenaSviridenko** [comment]
Hi @jmos5156, 
PR was merged, are we ok to close the issue? It doesn't require deployment, so please, feel free to close the issue if everything is done.
Thanks!
