### ISSUE TITLE
Add Windows Agent with Docker in Linux container mode

### ISSUE THREAD

**Issue by kaylangan** [actions/virtual-environments#252]
Copied from https://github.com/microsoft/azure-pipelines-image-generation/issues/702

**Tool information**
- Tool name: Docker with Linux Containers (On Windows)
- Add or update? Add
- Desired version: 
- Approximate size: 
- If this is an add request:
  - Brief description of tool: 
  - URL for tool's homepage: 

**Area for Triage**: Containers, .NET Core, Testing and code coverage

**Question, Bug, or Feature?**: Feature

**Virtual environments affected**
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [x] Windows Server 2016 R2
- [x] Windows Server 2019

**Can this tool be installed during the build?**

**Are you willing to submit a PR?**

**Comment by AButler** [comment]
+1

**Comment by jromero** [comment]
As a project providing Windows binaries that interact with Linux Docker images we'd like to have acceptance tests run in GitHub actions with this configuration.

**Comment by alepauly** [comment]
Unfortunately this is not something we can support at the moment.

**Comment by jromero** [comment]
Is there a technical limitation if we were to create a custom runner with this configuration?

**Comment by alepauly** [comment]
> Is there a technical limitation if we were to create a custom runner with this configuration?

hi @jromero yes, to support this we would need to enable hyper-v in the VM running the builds and that is not supported.

**Comment by Piedone** [comment]
Since two years have passed, is probably a better time to introduce this? For us, this is interesting to run SQL Server on Windows, for which there are only Linux official images available.
