### ISSUE TITLE
Add Meson

### ISSUE THREAD

**Issue by nordmoen** [actions/virtual-environments#2521]
**Tool information**
- Tool name: Meson
- Tool license: Apache 2 license
- Add or update? Add
- Desired version: Latest
- Approximate size: 1.8 MB GZiped
- If this is an add request:
  - Brief description of tool: Meson is an open source build system meant to be both extremely fast, and, even more importantly, as user friendly as possible.
  - URL for tool's homepage: https://mesonbuild.com/
  - Provide a basic test case to validate the tool's functionality:
 ```bash
$ mkdir testproject
$ cd testproject
$ meson init --name testproject --build
```

**Area for Triage**:
Packages

**Question, Bug, or Feature?**:
Feature

**Virtual environments affected**
- [x] Ubuntu 16.04
- [x] Ubuntu 18.04
- [x] Ubuntu 20.04
- [x] macOS 10.15
- [x] macOS 11.0
- [x] Windows Server 2016 R2
- [x] Windows Server 2019

`Meson` is available on all the systems above, which is why I marked them, but one could probably focus on Ubuntu and macOS to begin with.

**Can this tool be installed during the build?**
Both Ubuntu and macOS (through `brew`) have the possibility of installing `Meson`. The default version in Ubuntu 20.04 is a bit old, but can easily be remedied through installing `Meson` through `pip`.

**Tool installation time in runtime**
Takes a few seconds

**Are you willing to submit a PR?**
Sure

**Comment by AlenaSviridenko** [comment]
Hi @nordmoen,
given the pretty fast installation in runtime, we'd rather not to add this tool to the images. Also, there is a task [meson-build](https://github.com/marketplace/actions/meson-build) that provides likely wider functionality than just pre-installed tool, please, take a look at it if it fits your needs.

I am closing this issue. Please feel free to contact us for any support. Thanks.
