### ISSUE TITLE
[Windows 2019] Microsoft.VisualStudio.MinShell.Msi.Resources cannot be installed (vs_Enterprise)

### ISSUE THREAD

**Issue by martingem** [actions/virtual-environments#2527]
**Description**  
Installing vs_Enterprise fails (I'm currently at 0ed014bc91145fb672999e94cadf7d789166966d). Namely: Microsoft.VisualStudio.MinShell.Msi.Resources.

**Area for Triage**:  
Bug

**Question, Bug, or Feature?**:  
```
==> azure-arm: Provisioning with powershell script: /agent/_work/1/s/images/win/scripts/Installers/Install-VS.ps1
    azure-arm: Downloading Bootstrapper ...
    azure-arm: Downloading package from: https://aka.ms/vs/16/release/vs_Enterprise.exe to path C:\Users\installer\AppData\Local\Temp\vs_Enterprise.exe .
    azure-arm: Enable short name support on Windows needed for Xamarin Android AOT, defaults appear to have been changed in Azure VMs
    azure-arm: Starting Install ...
    azure-arm: Something went wrong with the install.
    azure-arm:
    azure-arm: You can troubleshoot the package failures by:
    azure-arm:
    azure-arm:     1. Search for solutions using the search URL below for each package failure
    azure-arm:     2. Modify your selections for the affected workloads or components and then retry the installation
    azure-arm:     3. Remove the product from your machine and then install again
    azure-arm:
    azure-arm: If the issue has already been reported on the Developer Community, you can find solutions or workarounds there. If the issue has not been reported, we encourage you to create a new issue so that other developers will be able to find solutions or workarounds. You can create a new issue from within the Visual Studio Installer in the upper-right hand corner using the "Provide feedback" button.
    azure-arm:
    azure-arm: ================================================================================
    azure-arm:
    azure-arm: Package 'Microsoft.VisualStudio.MinShell.Msi.Resources,version=16.8.30530.185,language=en-US' failed to install.
    azure-arm:     Search URL
    azure-arm:         https://aka.ms/VSSetupErrorReports?q=PackageId=Microsoft.VisualStudio.MinShell.Msi.Resources;PackageAction=Install;ReturnCode=1601
    azure-arm:     Details
    azure-arm:         MSI: C:\ProgramData\Microsoft\VisualStudio\Packages\Microsoft.VisualStudio.MinShell.Msi.Resources,version=16.8.30530.185,language=en-US\Microsoft.VisualStudio.MinShell.Msi.Resources.msi, Properties:  REBOOT=ReallySuppress ARPSYSTEMCOMPONENT=1  MSIFASTINSTALL="7"  VSEXTUI="1"
    azure-arm:         Return code: 1601
    azure-arm:         Return code details: The Windows Installer Service could not be accessed. This can occur if the Windows Installer is not correctly installed. Contact your support personnel for assistance.
    azure-arm:     Log
    azure-arm:         C:\Users\installer\AppData\Local\Temp\dd_setup_20210122154013_004_Microsoft.VisualStudio.MinShell.Msi.Resources.log
    azure-arm:     Impacted workloads
    [Removed Tools to be installed to reduce the ticket's length]
    azure-arm:     Impacted components
    [Removed Tools to be installed to reduce the ticket's length]
    azure-arm:
    azure-arm: Non zero exit code returned by the installation process : 1
==> azure-arm: Provisioning step had errors: Running the cleanup provisioner, if present...
==> azure-arm: 
==> azure-arm: The resource group was not created by Packer, deleting individual resources ...
==> azure-arm: Removing the created Deployment object: 'pkrdp9brsnc1ovo'
==> azure-arm: 
==> azure-arm: The resource group was not created by Packer, deleting individual resources ...

```

**Virtual environments affected**  
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [X] Windows Server 2019

**Expected behavior**  
Install Microsoft.VisualStudio.MinShell.Msi.Resources correctly

**Actual behavior**  
Package 'Microsoft.VisualStudio.MinShell.Msi.Resources,version=16.8.30530.185,language=en-US' failed to install.

**Repro steps**  
Using 0ed014bc91145fb672999e94cadf7d789166966d, I started the pipeline for Windows 2019. Although we use Shared Image Gallery as a destination, the rest of the pipeline is identical.

**Comment by martingem** [comment]
I noticed that I changed vm_size to Standard_D4s_v3. Reverted back to Standard_DS4_v2. Unsure why it wouldn't work on certain VM size but at least it's working.

**Comment by miketimofeev** [comment]
Hi @martingem!
I haven't seen any issues using Standard_D4s_v3 and Standard_D4s_v4 except this one with docker https://github.com/actions/virtual-environments/pull/2525
Have you tried multiple times?

**Comment by martingem** [comment]
Yes @miketimofeev, I was and still am at 4f6ab057d8edbf7823368597fa181d3b6101ff94, but for some reason that change to Standard_DS4_v2 isn't cutting it with said error. I tried 4 times, and I brang back Standard_D4s_v3 and it works now.

**Comment by BalloIbrahima** [comment]
if in your log file you have

Could not register type library for file C:\Program Files (x86)\Common Files\Microsoft Shared\MSEnv\dte90.olb

    Firstly open CMD or Windows PowerShell as administrator and execute the following command

    sfc /scannow

to scan for corruptions in Windows system files and restore corrupted files

    Then reboot your computer,
    Disable all antivirus software on your computer, including Windows Defender
    Reopen VS Installer to repair or retry your VS installation.

it solved my problem
