### ISSUE TITLE
Chocolatey Hangs for 1m on first run

### ISSUE THREAD

**Issue by kaylangan** [actions/virtual-environments#253]
**Describe the bug**
Running any chocolatey command hangs on "[Pending] Removing all pending packages that should not be considered installed..." message in debug, taking at least 1 minute to complete before moving on

**Area for Triage**: Scripting and command line

**Question, Bug, or Feature?**: Bug

**Virtual environments affected**
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [x] Windows Server 2016 R2
- [x] Windows Server 2019

**Expected behavior**
Chocolatey is initialized and indexed and ready to install software quickly on the build host

**Actual behavior**
A description with steps to reproduce the issue.

azure-pipelines.yaml
```
- powershell: cinst -yvd terraform --version '0.12'
  displayName: Chocolatey Install Terraform 0.12
```

Copied from https://github.com/microsoft/azure-pipelines-image-generation/issues/977

**Comment by kaylangan** [comment]
See https://github.com/microsoft/azure-pipelines-image-generation/issues/977#issuecomment-523971525

**Comment by miketimofeev** [comment]
@JustinGrote is the issue still valid? 
I can see the difference with and w\o your workaround, but it's only 7 seconds.

**Comment by miketimofeev** [comment]
@JustinGrote Closing this issue for now, but feel free to reopen if it still bothers you.
Thank you!
