### ISSUE TITLE
Update/Add LLVM 

### ISSUE THREAD

**Issue by tomesendam** [actions/virtual-environments#2530]
Seeing as Mac build agents already have LLVM installed I would like the same for Windows. This would remove about 3 minutes of the build time in my project. 

**Virtual environments affected**
- [*] Windows Server 2016 R2
- [*] Windows Server 2019

**Can this tool be installed during the build?**
Yes trough choco

**Tool installation time in runtime**
~ 3.5 minutes

**Are you willing to submit a PR?**
Yes

**Comment by andy-mishechkin** [comment]
Hello, @tomesendam 
LLVM already present in Windows Server 2019 Image as Visual Studio 2019 component.
Do you need the additional LLVM installed from choco ?
Thank you.

**Comment by tomesendam** [comment]
> Hello, @tomesendam 
> LLVM already present in Windows Server 2019 Image as Visual Studio 2019 component.
> Do you need the additional LLVM installed from choco ?
> Thank you.

Yes I need the additional one from choco

**Comment by AlenaSviridenko** [comment]
Hi @tomesendam,
we don't mind adding this tool to Windows image. Please, feel free to submit PR.

**Comment by tomesendam** [comment]
@AlenaSviridenko Thanks I'll be making a PR when I have the time.

**Comment by MaksimZhukov** [comment]
Hello @tomesendam! Is it still actual for you to have LLVM preinstalled on Windows images?
