### ISSUE TITLE
Update libseccomp to 2.4.4

### ISSUE THREAD

**Issue by junghans** [actions/virtual-environments#2531]
Currently one can not use a simple Fedora 34 container with a Dockerfile like this: 
```
FROM registry.fedoraproject.org/fedora:rawhide
RUN echo "echo test" > test.sh
RUN chmod +x test.sh
RUN ls -l test.sh
RUN test -x test.sh
```
or similarly using the `container:` keyword

Details of the issue are summarized in https://bugzilla.redhat.com/show_bug.cgi?id=1900021 and ,https://github.com/moby/moby/issues/41704 but in a nutshell we need  libseccomp-2.4.4 in the base image to make `faccessat()` and hence Fedora 34 containers working again.

**Comment by andy-mishechkin** [comment]
Official site: https://github.com/seccomp/libseccomp
This library should be build from source code

**Comment by AlenaSviridenko** [comment]
Hi @junghans,
we will review the idea of adding this library to the Ubuntu images. 
Meanwhile, to unblock workflow, you can install the latest version of this library in runtime from tarball with the following script (it will take ~1 min):
```
sudo apt-get install -y gperf

TarballUrl=$(curl -s https://api.github.com/repos/seccomp/libseccomp/releases/latest | jq -r '.tarball_url')
TarballPath="/tmp/libseccomp.tar.gz"

wget $TarballUrl -O $TarballPath
tar -xzvf $TarballPath -C /tmp

cd /tmp/seccomp*

autoreconf --install
./configure
sudo make [V=0|1]
sudo make install
```

we will keep you posted. Thanks.

**Comment by junghans** [comment]
Seems not to work, Docker needs to be compiled against it, too, I guess.

**Comment by junghans** [comment]
Ok installing `libseccomp` doesn't work with `container:` as it would install `libseccomp` in the container, but it needs to be update outside to make rawhide image works.

Here is an example workflow that fails:
https://github.com/junghans/test-actions/blob/46f84fb9741021f592ba24b77433a2df5e48d2d0/.github/workflows/continuous-integration-workflow.yml
and the build
https://github.com/junghans/test-actions/runs/1766713526

**Comment by miketimofeev** [comment]
@junghans installing `libseccomp 2.5.1` doesn't seem to help. I've tried it on the Ubuntu20 VM based on the same image as a hosted agent. Running with seccomp disabled (`--security-opt seccomp=unconfined`) makes it work
![image](https://user-images.githubusercontent.com/48208649/105853476-cbc1c780-5ff6-11eb-8835-f195f51679b6.png)

**Comment by junghans** [comment]
Cool, is there a way to make it with the `container:` keyword?

**Comment by miketimofeev** [comment]
@junghans yup! It can be passed via options, this workflow works just fine:
```
jobs:
  CI:
    runs-on: ubuntu-latest
    container:
      image: registry.fedoraproject.org/fedora:rawhide
      options:
        --security-opt seccomp=unconfined
    steps:
      - name: super-step
        shell: bash
        run: |
          echo "echo test" > test.sh
          chmod +x test.sh
          ls -l test.sh
          test -x test.sh
```

**Comment by junghans** [comment]
Thanks!

**Comment by miketimofeev** [comment]
@junghans can we close this issue since installing libseccomp 2.5.1 doesn't seem to help?

**Comment by junghans** [comment]
Sure
