### ISSUE TITLE
macos-11.0 should be called macos-11

### ISSUE THREAD

**Issue by jrtc27** [actions/virtual-environments#2533]
Previously, macOS versions were 10.major.minor, but with macOS 11 they are now following an iOS-like schema with just major.minor, so next year's release will be macOS 12 (and we already have macOS 11.1 released and 11.2 in beta testing). The name of the image should thus drop the extra .0, as otherwise it will either be incorrect if the runners are on 11.1 or above, or it will have to be renamed every time Apple release a minor update.

**Comment by andy-mishechkin** [comment]
Hello, @jrtc27 
Please clarify, where do you have the issues with macOS versions (your builds, pipelines, etc.). Also will be good, if you provide some links, where you've got the issue and and some repro steps.
Thank you

**Comment by AlenaSviridenko** [comment]
Hi @jrtc27,
thanks for noticing it, we will revisit label naming strategy in the future. 
Anyway, our current macOS images are of version 11.0.1, so label `macos-11.0` is fair now. 

I am closing this issue. Please, feel free to contact us in case of any other questions.
Thanks!
