### ISSUE TITLE
Add Linux/Arm64 runners

### ISSUE THREAD

**Issue by rickardp** [actions/virtual-environments#2536]
When building Docker multiarch images, my jobs are timing out due to compilation over qemu takes too long. I know it is probably possible to set up cross compilation on x64 and move the output to some temporary storage etc, but it is a lot of work and the buildx/multiarch case is becoming very common with the Raspberry Pi and now the Apple Silicon. Any chance of setting up Arm64 runners and integrate with buildx so that the arm64 targets are built on these?

(And yes, I know you're probably building in Azure and Azure doesn't have Arm64 IIRC, but now that you're Microsoft maybe you can put the pressure on :) Arm64 in Azure would not be bad either).

Edit: Sorry about the labels, I was trying to add the "feature request" label and now I can't revert it.

**Comment by AlenaSviridenko** [comment]
Hi @rickardp,
unfortunately, we don't have plans to add more images now due to maintenance and possible segmentation concerns. Our current focus is on stabilizing and improving existing images

Anyway, thank you for your suggestion and explained use case, it will help us to understand image popularity if we will revisit this decision in the future.

I am closing this issue. Please, feel free to create a new one in case of any other questions.

**Comment by rickardp** [comment]
It's unfortunate but I can see your reasoning (also I would argue your problem is not creating the image, but fixing the infra). Self-hosted runners sort of defeats the purpose of a cloud-based build system (at least in lack of a fully managed way to provision VMs and build their images), so I hope you will revisit this decision soon as Arm64 gain popularity.

**Comment by AlenaSviridenko** [comment]
By "maintenance" I mean a combination of things that we'll have to consider if we decide to add Arm64 runners: 
- image generation (reviewing all the software we have on current Linux images to check if it works for Arm64)
- image deployment (which means updating infra as you mentioned)
- team resources for supporting this image

So, yeah, you are partially right about infra, but that is not the whole picture. 
Anyway, I'll escalate the request, so we will put it at our horizon.

**Comment by dennisameling** [comment]
Just wanted to chime in here regarding hosted Linux arm64 runners. I created [an example build script](https://github.com/dennisameling/sharp/blob/temp-arm64-test/arm64-build-and-test.sh) for `lovell/sharp` and ran it on both a x64 host (Windows WSL2 Ubuntu 20.04, i7-9700) and on an arm64 host (Windows WSL2 Ubuntu 20.04, Microsoft SQ1 in Surface Pro X).

The results:

**x64 host** (leverages Docker's `arm64` emulation using QEMU)
```
$ time ./arm64-build-and-test.sh
....
prebuild info build Packing build/Release/sharp.node into prebuilds/sharp-v0.27.1-napi-v3-linux-arm64.tar.gz
prebuild info build Prebuild written to prebuilds/sharp-v0.27.1-napi-v3-linux-arm64.tar.gz

real    18m8.544s
user    0m0.810s
sys     0m1.052s
```

**arm64 host**
```
$ time ./arm64-build-and-test.sh
....
prebuild info build Packing build/Release/sharp.node into prebuilds/sharp-v0.27.1-napi-v3-linux-arm64.tar.gz
prebuild info build Prebuild written to prebuilds/sharp-v0.27.1-napi-v3-linux-arm64.tar.gz

real    2m34.083s
user    0m0.422s
sys     0m0.678s
```

So the difference really is night and day (~6-7x slower on QEMU)! Would be fantastic if the GH Actions team could consider offering native arm64 Linux runners 🤞🏼

**Comment by shaneutt** [comment]
ARM has a lot of momentum and I'm seeing that momentum growing. I have some projects which do not yet support ARM which is partially due to the fact that it's not a supported platform in our CI (Github Actions). I too would like to ask you to please consider this feature strongly, because as soon as the demand for the platform increases a bit further I'll be in a position where I'll need it and while Github Actions is a great CI if it's not offering ARM and another platform does I may need to migrate and I ultimately want to avoid doing that because it's time consuming.

**Comment by codefromthecrypt** [comment]
I know the relationship is loose, but last year [Azure Pipelines](https://azure.microsoft.com/en-us/updates/azure-devops-pipelines-introduces-support-for-linuxarm64/) added support for arm64.

Having this issue closed seems more about timing vs a won't fix, right? Other platforms such as Travis added arm64 and it would be unlikely GitHub Actions never has a free runner (I hope!)

Is there a way we can get a product manager of GitHub Actions to comment or re-open this, or in worst case point people to the correct forum for the product gap?

**Comment by rickardp** [comment]
@codefromthecrypt the problem is, as far as I understand it that Azure does not expose general purpose compute nodes (VM scale sets) with arm64 CPU types. GitHub can either wait for Azure or use AWS (unlikely I suppose given ownership). I hope Azure publishes Arm64 VM sizes soon, not only because of this issue.

**Comment by exchgr** [comment]
in the meantime, i've found that an efficient way to handle this gap is to cross-compile. here's an [example](https://gist.github.com/exchgr/0fd441994297b5119e20bbcffc8aa4e8) using yarn berry (and aws ecr)

**Comment by otterley** [comment]
GitHub announced the future availability (Q1 2024) of Arm64-based runners today: 

https://github.blog/changelog/2023-10-30-accelerate-your-ci-cd-with-arm-based-hosted-runners-in-github-actions/

**Comment by AlexBaranowski** [comment]
Is this still actively developed? The private beta started about a half-year ago, and there is still no GA for Arm64 builders.

I understand that custom runners, cross-compilation, or even creating qemu-performance-abomination are possible solutions. However, these feel more like temporary fixes on what should be readily available, especially if GitHub aims to lead, not just follow.

Also, if you compile/build something, the ability to test it in tolerable time is quite important, so after cross-compilation (which in most cases is slower), the dynamic QA should have tolerable execution time. Without it, the whole GitHub action CI/CD solution is meaningless.

**Comment by bobrik** [comment]
https://github.blog/2024-06-03-arm64-on-github-actions-powering-faster-more-efficient-build-systems/

**Comment by AlexBaranowski** [comment]
@bobrik Thank you for update, I will wait for GA for open source projects then :octocat: . I'm super excited about that.
