### ISSUE TITLE
[macOS] Bazel 4.0.0 breaking changes

### ISSUE THREAD

**Issue by MaksimZhukov** [actions/virtual-environments#2547]
**Breaking changes**
Bazel will be updated from `3.7.1` to `4.0.0`.

**Target date**
Image deployment will start January, 25 and will take 3-4 days.

**The motivation for the changes**
We would like to provide images with the latest stable updates.

**Possible impact**
Bazel has a bunch of breaking changes, find details in https://blog.bazel.build/2021/01/19/bazel-4-0.html

Also you could experience the issues if use Bazel on macOS with non-default Xcode: Bazel 4.0 doesn't support Xcode <= 11.3.1 (because of Clang incompatibility). If you need to use Bazel with old Xcode, make sure that you freeze Bazel < 4.0. Find more details in https://github.com/bazelbuild/bazel/pull/12882

**Virtual environments affected**
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.13
- [ ] macOS 10.14
- [x] macOS 10.15
- [x] macOS 11.0
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Mitigation ways**
Please, use the following workaround to install bazel 3.7.1 in runtime:
```
export USE_BAZEL_VERSION="3.7.1"
bazel --version
```

**Comment by gtothe7** [comment]
#924

**Comment by MaksimZhukov** [comment]
Rollout of these changes has been finished.
