### ISSUE TITLE
GCC/MinGW 32-bit compilers don't work on 'windows-latest'

### ISSUE THREAD

**Issue by LexouDuck** [actions/virtual-environments#2549]
**Description**:  
There are two 32-bit C compilers that come with the MSYS2 installation on 'windows-latest':
`/c/msys64/mingw32/bin/gcc` (the GNU GCC)
`/c/msys64/mingw32/bin/i686-w64-mingw32-gcc` (the MinGW GCC)
Both of these seem to not have been installed properly on the 'windows-latest' runner machine.
I am unable to compile a simple `helloworld.c` file with them (and no error is given: the process simply exits out, returning exit code '1').
Furthermore, simply attempting to show the compiler version info (with the `-v` verbose flag) does a similar crash/exit:
![image](https://user-images.githubusercontent.com/35985773/105741264-60b2bb00-5f3a-11eb-99d6-d2f0339459e1.png)

```sh
/c/msys64/mingw32/bin/gcc -v --version
/c/msys64/mingw32/bin/i686-w64-mingw32-gcc -v --version
```
Both of the commands written above crash and return exit code 1, which should never be the case. Because of this behavior, I am confident there was a problem during installation of MSYS2 (perhaps windows "run as administrator" mode was not enabled when installing ?)

**Area for Triage**:  
C/C++

**Question, Bug, or Feature?**:  
Bug

**Virtual environments affected**  
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [x] Windows Server 2019

**Expected behavior**  
The two 32-bit compilers should not crash halfway when showing version info, and should be able to compile a helloworld test.

**Actual behavior**  
The two 32-bit compilers seem to be corrupt in some way, invoking these 2 programs always fails.

**Repro steps**  
1. On a 'windows-latest' runner, try the following commands:
```sh
/c/msys64/mingw32/bin/gcc -v --version
/c/msys64/mingw32/bin/i686-w64-mingw32-gcc -v --version
```
2. Also, try to use both compilers to compile a simple helloworld, like this one for example:
```c
#include <stdio.h>

int main(int argc, char** argv)
{
	printf("Hello world!\nprogram args:\n");
	for (int i = 0; i < argc; ++i)
	{
		printf("\t%s\n", argv[i]);
	}
	return (0);
}
```

**Comment by vsafonkin** [comment]
@MSP-Greg , @eregon, as MSYS2 experts, could you please help us with it? We install these compilers in  `mingw32` packages via pacman, maybe there are any additional settings to install it?

**Comment by MSP-Greg** [comment]
@vsafonkin

I'm looking at it...

**Comment by MSP-Greg** [comment]
@LexouDuck

Not sure about this.  Both the below run from steps using the default shell.  See [MSYS2 gcc 32 bit](https://github.com/MSP-Greg/actions-image-testing/runs/1792732722?check_suite_focus=true#step:17:15).

Your above comment shows *nix paths, so you may need to adjust $PATH to run the 32 bit?

```
$env:Path = "C:/msys64/mingw64/bin;C:/msys64/usr/bin;$env:Path"
gcc -v --version
```

```
$env:Path = "C:/msys64/mingw32/bin;C:/msys64/usr/bin;$env:Path"
gcc -v --version
```

**Comment by LexouDuck** [comment]
Ah, my bad - I forgot to mention that I do use the bash shell as default (in fact, you did find, and linked, the previous issue I made where i mentioned this as a solution)
```yml
defaults:
  run:
    shell: bash
```
I believe this uses the "git bash" shell that typically comes with windows installations of git, right ? I am not very familiar with that shell, I typically use cygwin.

It might be, like you say, a $PATH problem - but then that would mean i need to replace the exisiting `mingw64` folder in the PATH with the `mingw32` one instead ?
Note that I am using the' windows-latest' runner to both compile 64-bit, and "cross-compile" 32-bit.

Furthermore, here is the YML script for the job I was running to test that it functions properly:
```yml
    - name: Build (with ${{matrix.compiler}}, for 'windows-latest')
      if: matrix.os == 'windows-latest' && matrix.compiler == 'gcc'
      run: |
        /c/msys64/mingw64/bin/x86_64-w64-mingw32-gcc -v --version
        echo "debug"
        /c/msys64/mingw32/bin/i686-w64-mingw32-gcc -v --version
        echo "debug"
        /c/msys64/mingw32/bin/i686-w64-mingw32-gcc -o main -Wall -Wextra -Winline -Wpedantic -D__USE_MINGW_ANSI_STDIO=1 ./lib/libccc/test/_helloworld.c
        echo "COMPILED HELLOWORLD"
        ./main
        echo "RAN HELLOWORLD"
        make release CC=/c/msys64/mingw32/bin/i686-w64-mingw32-gcc OSMODE=win32
```
What is surprising to me is that `/c/msys64/mingw64/bin/x86_64-w64-mingw32-gcc` (64-bit) works just fine, but `/c/msys64/mingw32/bin/i686-w64-mingw32-gcc` (32-bit) can't even show version info ? What sort of PATH problem would cause that ?

**Comment by MSP-Greg** [comment]
> What is surprising to me is that...

I did try to repo locally, and couldn't.

I've never used the bash shell much on Windows, and lately I've been working with WSL2/Ubuntu.

Re MSYS2, most of the work I've done is is 'configure, make, make check/test, make install', and that often requires the path to be setup correctly.  Hence, I always do that.  I also haven't used the 32 bit tool chain for a while...

**Comment by vsafonkin** [comment]
@LexouDuck , I've tried to add mingw32 to the PATH and it works for me:
```
- name: add mingw32 to path
      shell: bash
      run: |
        echo "C:\msys64\mingw32\bin" >> $GITHUB_PATH
    
    - run: i686-w64-mingw32-gcc --version

    - name: compile helloworld.c
      run: |
        i686-w64-mingw32-gcc -v helloworld.c -o helloworld
        $LASTEXITCODE
```
build: https://github.com/vsafonkin/test-repo/runs/1804678077?check_suite_focus=true

@MSP-Greg thank you for your help!

**Comment by vsafonkin** [comment]
Closed, @LexouDuck feel free to reopen it if you have any issues.
