### ISSUE TITLE
[macOS] Xcode Toolchain doesn't have arm64 support.

### ISSUE THREAD

**Issue by xiaoyu2006** [actions/virtual-environments#2557]
**Description** 

It turns out that the default toolchain in macOS 11.0 doesn't have architect `arm64` support.

**Area for Triage**

C/C++

**Question, Bug, or Feature?**

Question/Bug

**Virtual environments affected**

- [x] macOS 11.0

**Expected behavior**

`clang -arch arm64 -c someobject.o somesource.c` should work fine. But it failed with `error: Unsupported architecture` in the VM.

**Actual behavior**

```
  In file included from /Applications/Xcode_12.2.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/12.0.0/include/stdint.h:52:
  In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/stdint.h:52:
  In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/sys/_types.h:32:
  /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/sys/cdefs.h:807:2: error: Unsupported architecture
  #error Unsupported architecture
   ^
```

**Additional infomation**
Partical content of `/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/sys/cdefs.h`:
```c
/*
 * Architecture validation for current SDK
 */
#if !defined(__sys_cdefs_arch_unknown__) && defined(__i386__)
#elif !defined(__sys_cdefs_arch_unknown__) && defined(__x86_64__)
#else
#error Unsupported architecture
```
(https://github.com/xiaoyu2006/ss-buildbot/runs/1769514620?check_suite_focus=true#step:3:834)

**Comment by Darleev** [comment]
Hello @xiaoyu2006,
I forked your repository, in order to check possible fixes. I've added one string to change the default Xcode version to 12.3:

`sudo xcode-select -s "/Applications/Xcode_12.3.app"`

It seems this is resolved the issue with arm64 architecture, but another issue appears:

```
          ld: symbol(s) not found for architecture arm64
          clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

I believe something should be changed inside the project itself, to fix current issue.

Also, we've updated the default Xcode version to 12.3 for macOS 10.15/11.0, and this update should be applied after the next image rollout.

**Comment by xiaoyu2006** [comment]
Hi @Darleev.
The commit you fork I actually another attempt and it should fail like that. I didn’t expect to work.

**Comment by Darleev** [comment]
Hi @xiaoyu2006,
During the investigation, I found an answer [at the link](https://travis-ci.community/t/osx-image-xcode12-2-does-not-come-with-macos-11-sdk-no-way-to-compile-for-arm/10611). Proposed solution is:

1) Update Xcode to version 12.3
2) Remove Xcode SDK folder using command:

`sudo rm -Rf /Library/Developer/CommandLineTools/SDKs/*`

In the forked repo, [I was able to complete the build step](https://github.com/Darleev/ss-buildbot/runs/1787409584?check_suite_focus=true).

Could you please check it and try the same solution on your side?

We are looking forward to your reply.

**Comment by xiaoyu2006** [comment]
@Darleev Thanks! This solves my problem.
