### ISSUE TITLE
Add Packages

### ISSUE THREAD

**Issue by FigBug** [actions/virtual-environments#256]
**Tool information**
- Tool name: Packages
- Add or update? Add
- Desired version: 1.2.8
- Approximate size: 5.5 MB
- If this is an add request:
  - Brief description of tool: Creates installer packages for macOS
  - URL for tool's homepage: http://s.sudre.free.fr/Software/Packages/about.html

**Area for Triage**: Apple

**Question, Bug, or Feature?**: Feature
 
**Virtual environments affected**
- [X] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Can this tool be installed during the build?**
Not sure

**Are you willing to submit a PR?**
No, not sure how

**Comment by alepauly** [comment]
@FigBug thanks for the suggestion but at this time we won't add Packages to the environment. I could suggest creating an Action that will facilitate adding it when needed.
