### ISSUE TITLE
Update Apple clang compiler on macos-latest

### ISSUE THREAD

**Issue by shz0116** [actions/virtual-environments#257]
**Tool information**
- Tool name: Apple clang compiler
- Add or update? update  version 11.0.0 (clang-1100.0.33.12)
- Desired version: version 11.0.0 (clang-1100.0.33.16)
- Approximate size: 
- If this is an add request:
  - Brief description of tool: 
  - URL for tool's homepage: 

**Area for Triage**:

**Question, Bug, or Feature?**:

**Virtual environments affected**
- [ x] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Can this tool be installed during the build?**

**Are you willing to submit a PR?**

**Comment by al-cheb** [comment]
Hello, shz0116
Xcode 11.2.1(clang-1100.0.33.12) set by default - https://github.com/actions/virtual-environments/blob/master/images/macos/macos-10.15-Readme.md 

You should switch from Xcode 11.2.1(default) to Xcode 11.3, if you want to use clang-1100.0.33.16 compiler.
`sudo xcode-select -s /Applications/Xcode_11.3.app/Contents/Developer`

Example:
```
- name: Set Xcode 11.3
      run: |
        sudo xcode-select -s /Applications/Xcode_11.3.app/Contents/Developer
        clang -v
```

**Comment by kaylangan** [comment]
Closing as solved. Let me know if you feel this should be reopened.
