### ISSUE TITLE
Update/Add NDK (Side by side)

### ISSUE THREAD

**Issue by vvb2060** [actions/virtual-environments#2572]
**Tool information**
- Tool name: NDK (Side by side)
- Tool license: Apache License Version 2.0
- Add or update? Add
- Desired version: N/A
- Approximate size: N/A
- If this is an add request:
  - Brief description of tool: NDK (Side by side) allows multiple NDKs to be installed.
  - URL for tool's homepage: https://developer.android.com/studio/projects/install-ndk
  - Provide a basic test case to validate the tool's functionality: N/A

**Area for Triage**: Android

**Question, Bug, or Feature?**: Feature

**Virtual environments affected**
- [x] Ubuntu 16.04
- [x] Ubuntu 18.04
- [x] Ubuntu 20.04
- [x] macOS 10.15
- [x] macOS 11.0
- [x] Windows Server 2016 R2
- [x] Windows Server 2019

**Can this tool be installed during the build?**
Yes. `${ANDROID_SDK_ROOT}/cmdline-tools/latest/bin/sdkmanager --install "ndk;version"`

**Tool installation time in runtime**
1 minute

**Are you willing to submit a PR?**
I think we should discuss it first.

NDK (Side by side) allows multiple NDK to be installed, And ndk-bundle should keep the NDK LTS version.
We should at least install the latest version, AGP default version and LTS version.

| AGP | Default NDK version |
| ---- | ----------------------- |
| 4.1  |        21.1.6352462       |
| 4.0  |        21.0.6113669       |
| 3.6  |        20.0.5594570       |

  Path             | Version      | Description                    | Suggest
  -----------------|--------------|--------------------------------|-----------------------
  ndk-bundle       | 22.0.7026061 | NDK (Bundle)                   | symbolic link to last LTS version (21.X)
  ndk;16.1.4479499 | 16.1.4479499 | NDK (Side by side) 16.1.4479499|
  ndk;17.2.4988734 | 17.2.4988734 | NDK (Side by side) 17.2.4988734|
  ndk;18.1.5063045 | 18.1.5063045 | NDK (Side by side) 18.1.5063045|
  ndk;19.2.5345600 | 19.2.5345600 | NDK (Side by side) 19.2.5345600|
  ndk;20.0.5594570 | 20.0.5594570 | NDK (Side by side) 20.0.5594570| Install (AGP Default)
  ndk;20.1.5948944 | 20.1.5948944 | NDK (Side by side) 20.1.5948944|
  ndk;21.0.6113669 | 21.0.6113669 | NDK (Side by side) 21.0.6113669|
  ndk;21.1.6352462 | 21.1.6352462 | NDK (Side by side) 21.1.6352462| Install (AGP Default)
  ndk;21.2.6472646 | 21.2.6472646 | NDK (Side by side) 21.2.6472646|
  ndk;21.3.6528147 | 21.3.6528147 | NDK (Side by side) 21.3.6528147| Install (last LTS)
  ndk;22.0.7026061 | 22.0.7026061 | NDK (Side by side) 22.0.7026061| Install (last)

**Comment by AlenaSviridenko** [comment]
Hi @vvb2060,

we are already implementing installation of latest (currently r22) and LTS (currently r21) versions side by side, you can track process in these PRs: [Ubuntu](https://github.com/actions/virtual-environments/pull/2556), [macOS](https://github.com/actions/virtual-environments/pull/2542), [Windows](https://github.com/actions/virtual-environments/pull/2555). 

We are also getting rid of ndk-bundle due to possible breaking changes when it updates to new version.

I will keep this issue open, we'll notify you when changes go to the rollout stage (approx. next week). Thanks!

**Comment by vvb2060** [comment]
Will you install the default NDK version of AGP?  I think that many people have not configured the NDK version, and due to an AGP bug, AGP is likely to ignore the configured version and download the default NDK version.

**Comment by AlenaSviridenko** [comment]
Do you mean `21.1.6352462` that is specified as a default version for AGP 4.1?
Our future strategy is to always install latest patch of LTS and latest non-LTS versions. Unfortunately, we cannot afford to install a wide range of versions due to space concerns, especially for Ubuntu images.

**Comment by maxim-lobanov** [comment]
Closing this issue for now. Currently, images contain NDK 21 (latest LTS) and NDK 22 (latest) will be added next week in https://github.com/actions/virtual-environments/issues/2365
As Alena mentioned above, we can't afford to pre-install more NDK versions to images. If you need any specific version - please install it in runtime.
