### ISSUE TITLE
Devops Pipeline fails Can't resolve the reference System.Void UIKit.UIPageControl::set_AllowsContinuousInteraction

### ISSUE THREAD

**Issue by developer9969** [actions/virtual-environments#2574]
Hi everyone. I am getting the below error 

`MTOUCH : error MT2101: Can't resolve the reference 'System.Void UIKit.UIPageControl::set_AllowsContinuousInteraction(System.Boolean)', referenced from the method 'System.Void Xamarin.Forms.Platform.iOS.IndicatorViewRenderer::OnElementChanged(Xamarin.Forms.Platform.iOS.ElementChangedEventArgs1<Xamarin.Forms.IndicatorView>)' in 'Xamarin.iOS, Version=0.0.0.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065'. ]`

I have been  STUCK for days now and run out ideas of what could be wrong. I double checked and I am using the latest everywhere.It only happens using xamarin forms 5.x  as it requires xamarin.iOS 14 miminum .

I am using microsoft agent (macOS-latest) 

- Looking at the Devops build logs at some point it mentions "Xamarin.iOS 13.20.2.2" why does it pick this version is this default?
- How do I force the pipeline to run a particula version of Xamarin.iOS anything >=14.

My Bash script is as follows:

```
monoVersion: '6_12_0'
xCodeVersion: '12.3'

task: Bash@3 displayName: 'Switch to Mono Version ${{ parameters.monoVersion }}' inputs: targetType: 'inline' script: 'sudo $AGENT_HOMEDIRECTORY/scripts/select-xamarin-sdk.sh ${{ parameters.monoVersion }}' bash: echo '##vso[task.setvariable variable=MD_APPLE_SDK_ROOT;]'/Applications/Xcode_${{ parameters.xCodeVersion }}.app;sudo xcode-select --switch /Applications/Xcode_${{ parameters.xCodeVersion }}.app/Contents/Developer
```
 **My Settings**
- Pipeline : We are using Microsoft Hosted agent (we have no control over what is installed)
- Pool='macOS-latest' (macos-10.15) which according to the document it has the latest installed
- https://github.com/actions/virtual-environments/blob/main/images/macos/macos-10.15-Readme.md
- Visual studio iOS Project Deployment Target=12.0
- Visual Studio Version : 16.8.4
-
Really grateful for anybody feedback or suggestions or how to force agent to build with Xamarin.iOS anything >=14.

**Comment by andy-mishechkin** [comment]
Hello, @developer9969
May you provide some links to any your pipelines or workflow. It can help us to check and identify the issue.
Thank you.

**Comment by developer9969** [comment]
@andy-mishechkin  thanks for your reply I  have just managed to solve the issue and basically omitting all together that script that was selecting the mono version and xcode version the agent picked up.

Now by removing this script the agent picks up the latest xamarin.iOS.

We been using this script for nearly a year now without a hitch,  as in the past we had problems with agents not picking up the correct version, so something must have changed to the point that this script is no longer necessary .

**Comment by miketimofeev** [comment]
@developer9969 we configure bundles here https://github.com/actions/virtual-environments/blob/main/images/macos/toolsets/toolset-10.15.json and there is `"bundle-default"` setting, which currently points to the latest xamarin bundle 6_12_5 with Xamarin Ios 14 — that was changed not so long ago in the scope of switching default Xcode to 12.3 here https://github.com/actions/virtual-environments/pull/2526
When you specify `monoVersion: '6_12_0'` it pick ups 6_12_0 bundle with Xamarin ios 13.20.2.2.
Hope it's more clear for you now.

**Comment by developer9969** [comment]
@miketimofeev Hi there that is perfect it all makes sense now but for whatever the reasons I could not find the answer!

thanks for replying!

**Comment by miketimofeev** [comment]
@developer9969 yeah, we constantly work on improving the documentation, sorry for the inconvenience. 
I'm going to close the issue, but please feel free to contact us if you have any concerns.
Thank you!

**Comment by rt-miller** [comment]
This helped us as well... to disabled the simple tasks that set the xCode and Mono versions.  Odd, but happy it works now.

**Comment by miketimofeev** [comment]
@developer9969 @rt-miller we've created a PR with to update the docs with the symlinks https://github.com/actions/virtual-environments/pull/3113 
Please feel free to add comments there if something is unclear
