### ISSUE TITLE
running on openstack

### ISSUE THREAD

**Issue by vasiliy-t** [actions/virtual-environments#2576]
**Description**  
I'm experimenting with virtual-environments on openstack. My goal is to run private self hosted runners which are identical to public ones (same software installed, same version, developer expectations etc.). It takes just a few minor changes to build image for openstack which is great! Now I have questions:

- there is no actions runner installed inside image. Am I supposed to install it separately? Is there any reason to not install it on packer build? 
- there are walinuxagent configuration and deprovision steps but we use cloud-init. any recommendations on cleaning up without waagent deprovision?

**Question, Bug, or Feature?**:  
"Question"

**Virtual environments affected**  
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [x] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Comment by al-cheb** [comment]
Hello, @vasiliy-t 
1. You should install a runner agent separately. Reasons:
- Support overhead
- Lack of free space on an image
- Store different kinds of agents (Azure Pipeline, GitHub Actions, etc)
- Outdated agent version 
2. We don't support any non Azure environments.  You can disable walinuxagent using follow instruction:  [Disable or remove the Linux Agent from VMs and images](https://docs.microsoft.com/en-us/azure/virtual-machines/linux/disable-provisioning)

**Comment by vasiliy-t** [comment]
Got it. I should run custom cleanup/deprovision without walinuxagent. @al-cheb thank you!
