### ISSUE TITLE
Hosted Agent with azure-pipelines-agent 2.181.0 does not always have git-lfs installed

### ISSUE THREAD

**Issue by MaxB504** [actions/virtual-environments#2578]
**Description**  
I was going to log this on azure-pipelines-agent, but the issue template suggested https://github.com/Microsoft/vsts-image-generation for such issues, which doesnt exist, so I ended up here.
Azure DevOps Repos support Git-LFS, and Azure pipelines is also supposed to support Git-LFS.  Not all hosted agents do.  https://github.com/microsoft/azure-pipelines-agent/issues/3041#issuecomment-754408192
I have seen one successful pull, but continued failures since.  All agents are 2.181, which is supposed to support git-lfs and installing git-lfs is not neccessary according to link above.

Starting: Initialize job
Agent name: 'Hosted Agent'
Agent machine name: 'fv-az91-844'
Current agent version: '2.181.0'
Operating System
Virtual Environment
Current image version: '20210121.0'
Agent running as: 'VssAdministrator'

**Area for Triage**:  
Packages

**Question, Bug, or Feature?**:  
Bug

**Virtual environments affected**  
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [x] Windows Server 2019

**Expected behavior**  
During pulling repo stage from AzDO repo, git-lfs is supported by the build agent.

**Actual behavior**  
git-lfs is not installed on hosted agents and pulling the repo cannot be completed.

**Repro steps**  
Create a repo with git-lfs, 
Create pipeline utilising this repo and specify git-lfs required.
Run Build
Error during Checkout step:

Task         : Get sources
Description  : Get sources from a repository. Supports Git, TfsVC, and SVN repositories.
Version      : 1.0.0
Author       : Microsoft
Help         : [More Information](https://go.microsoft.com/fwlink/?LinkId=798199)
==============================================================================
Syncing repository: xxxxxxxxx (Git)
Prepending Path environment variable with directory containing 'git.exe'.
git version
git version 2.28.0.windows.1
**git lfs version
git: 'lfs' is not a git command. See 'git --help'.**

git init "D:\a\1\s"
Initialized empty Git repository in D:/a/1/s/.git/
git remote add origin https://xxxxxxxxxxxxxxxxxxxxxxxxxxxx
git config gc.auto 0
git config --get-all http.https://xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
git config --get-all http.proxy
git config http.version HTTP/1.1
**git lfs install --local
git: 'lfs' is not a git command. See 'git --help'.
##[error]Git-lfs installation failed with exit code: 1**

**Comment by andy-mishechkin** [comment]
Hello @MaxB504 
I've checked git lfs on GH Windows 2019 runner and Azure Devops windows-latest agent - both contains git lfs installed (see the screenshot)
![image](https://user-images.githubusercontent.com/57713077/106152666-285be880-6197-11eb-9dfb-b268c6bcc28c.png)
May you provide link to workflow, where you've got this error ?
Thank you.

**Comment by MaxB504** [comment]
Hello @andy-mishechkin 
Thank you for looking at this for me.  I do not know what you mean by workflow, do you want the YAML or the build logs?  I'm sorry, I am just getting started with pipelines.  This link is for the [build logs](https://sita365-my.sharepoint.com/:t:/g/personal/max_byrne_sita_aero/ESLMe7BgGE9JoPvkk4BwZGsB0CMazhGLOvVCjQrw2h3FNQ?e=pSYPdg)

**Comment by andy-mishechkin** [comment]
Hello, @MaxB504 
Thank you for log. Your log looks like Azure Devops log (not log of GitHub Actions, workflow relates to it)
As I've said, I also checked Azure DevOps agent, and I've found github lfs there. 
May you provide also link to the yaml, or to pipeline, where you try to use github lfs
Thank you

**Comment by MaxB504** [comment]
Hello again @andy-mishechkin 
On further investigation I established that re-runnning older build attempts that did work, still worked, and taking the YAML from those builds and running in the most recent pipeline environ didn't work. 
I have established that the declaration of a variable in the pipeline, (not within the YAML, but using the pipelines variable form), which I naively called 'path' was somehow stopping the use of git-LFS.  Perhaps messing up some PATH system/environ variable.
I am sorry for taking your time and I do appreciate your assistance.  Please consider this issue closed.

**Comment by andy-mishechkin** [comment]
@MaxB504 , thank you for your response
Closing issue
