### ISSUE TITLE
Unable to access/run Ghostscript `gs`

### ISSUE THREAD

**Issue by kylekeesling** [actions/virtual-environments#2585]
**Description**  
As recently as yesterday (1/27/2021 @3:43pm EST) I was able to use ghostscript (the `gs` command) in my test code, but starting this morning (1/28/20201 @ 10:05am EST) my tests fail with the error message: `No such file or directory - gs`

I have made no changes to the underlying code that uses ghostscript or my Actions workflow config, so I was beginning to wonder if this was removed from the standard Ubuntu packages, but I can't find anything mentioning it in the READMEs

Any light you can shed on this would be much appriciated

**Area for Triage**:  
Packages
Scripting and command line

**Question, Bug, or Feature?**:  
Bug

**Virtual environments affected**  
- [ ] Ubuntu 16.04
- [X] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Repro steps**  
I'm attempting to run the command via Ruby's Open3 class/library, so the code looks something like:

```
def run_ghostscript(input:, output:)
    cmd =
      %W[
        gs
        -dSAFER -dBATCH -dNOPAUSE -dNOCACHE -sDEVICE=pdfwrite
        -sColorConversionStrategy=LeaveColorUnchanged
        -dAutoFilterColorImages=true
        -dAutoFilterGrayImages=true
        -dDownsampleMonoImages=false
        -dDownsampleGrayImages=false
        -dDownsampleColorImages=false
        -sOutputFile=#{output} #{input}
      ].join(" ")

    _stdout_str, err = Open3.capture3(cmd)
    if !err.nil? && !err.empty? && !err.include?("Output may be incorrect")
      raise StandardError.new("ghostscript processing error (when calling '#{cmd}'): '#{err.strip}'")
    end
  end
```

**Comment by andy-mishechkin** [comment]
Hello, @kylekeesling 
I've checked last Ubuntu 18.04 image, and it looks like it doesn't contain ghostscript (did you mean ghostscript, which can be installed trough apt ?). Also I can't find it in previous versions of this image.
May you provide link to your workflow where you tried to use gs ?

**Comment by miketimofeev** [comment]
@kylekeesling @andy-mishechkin it looks like ghostscript package was previously installed [as a dependency of HHVM](https://github.visualstudio.com/virtual-environments/_build/results?buildId=94175&view=logs&j=011e1ec8-6569-5e69-4f06-baf193d1351e&t=5431112d-2b61-5a5f-7042-ef698f761043&l=34971):
```
    azure-arm: Selecting previously unselected package ghostscript.
    azure-arm: Preparing to unpack .../14-ghostscript_9.26~dfsg+0-0ubuntu0.18.04.13_amd64.deb ...
    azure-arm: Unpacking ghostscript (9.26~dfsg+0-0ubuntu0.18.04.13) ...

```

But it's not true anymore.
Ghostscript can be installed using the following steps:
```
sudo apt-get update
sudo apt-get install ghostscript -y
```
Installation takes about 15 seconds.

**Comment by kylekeesling** [comment]
That did the trick. Thanks for for providing the forensics for me 🙏

**Comment by EmmaB** [comment]
Do you happen to know how to install a particular version of Ghostscript on Github actions? `sudo apt-get install ghostscript -y` installs a version that I can't use, for reasons.

**Comment by maxim-lobanov** [comment]
apt allows to specify version for some packages: https://askubuntu.com/questions/428772/how-to-install-specific-version-of-some-package

**Comment by EmmaB** [comment]
Ah, alas `E: Version '9.53.3' for 'ghostscript' was not found` but thanks. I'll just have to hammer away with a manual install somehow. Thanks anyway.
