### ISSUE TITLE
Add dpkg-dev package

### ISSUE THREAD

**Issue by JavierPalaciosNexplore** [actions/virtual-environments#2589]
**Tool information**
- Tool name: dpkg-dev:
- If this is an add request:
  - Brief description of tool: Builds debian packages

**Virtual environments affected**
- [x] Ubuntu 20.04

**Can this tool be installed during the build?**
Yes, just by adding it to some `apt-get` command

**Tool installation time in runtime**
Negligible

**Are you willing to submit a PR?**
I'll try, although I have not clear idea yet about the build process for this repository

**Comment by AlenaSviridenko** [comment]
Hi @JavierPalaciosNexplore,
dpkg-dev is already installed on Ubuntu 20.04:
![image](https://user-images.githubusercontent.com/8777209/106455444-44180500-649d-11eb-8eb1-8b31e9ad11a4.png)

Do you need another version of it? Could you please provide a bit more info why pre-installed package doesn't work for you?

**Comment by JavierPalaciosNexplore** [comment]
We're landing, and I've not yet tried. It was just that I didn't found it on https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-README.md.  
If already installed it should work because the packages we make are targeted to ubungu-20.04.
