### ISSUE TITLE
Put MSBuild on the PATH

### ISSUE THREAD

**Issue by lol768** [actions/virtual-environments#26]
**Describe the bug**

Can you put `C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\MSBuild` on the `PATH` please?

**Virtual environments affected**
- [ ] macOS 10.14
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [x] Windows Server 2019

**Comment by maxim-lobanov** [comment]
Hello!
Could you please check answer in #294? I believe it will resolve this issue too

**Comment by lol768** [comment]
I think this should work out of the box @maxim-lobanov - is there a reason it can't?

**Comment by maxim-lobanov** [comment]
On my local box, `MSBuild` is available only from `Visual Studio Command Prompt`. It is not available from `Command Line`. So I believed that it is expected.

If it works for you locally, probably, it may depend on version of VS / .NET Framework. Do you have any documentation links to confirm that msbuild should be available outside `Visual Studio Command Prompt`?

**Comment by lol768** [comment]
No, it's not based on documentation - rather than how I thought this would intuitively work. If I installed a package on any Linux distro and the executables weren't available in `PATH` afterwards, I'd consider the installation process broken... .NET Core does this properly, for instance.

Maybe my expectations are just not aligned with how this is supposed to work on Windows (where everything seems to be 10x more painful!).

**Comment by maxim-lobanov** [comment]
Hm, good point. I didn't consider that `msbuild` is on PATH for macOS / Ubuntu and available without `Visual Studio Command Prompt`. For macOS, for example, it comes from `/Library/Frameworks/Mono.framework/Versions/Current/Commands/msbuild`
In this case, probably, we should add it on PATH for Windows too.

@alepauly , @al-cheb , any thoughts?

**Comment by alepauly** [comment]
@maxim-lobanov @lol768 I wouldn't expect it to be in the PATH on Windows and instead I would want to use the Dev Command Prompt bat to set it up (or maybe a platform agnostic action, say `setup-msbuild`?). One thing to consider is that it's possible that there are differences between dotnet core MSBuild and the one packaged with Visual Studio. It could be confusing to know which one is getting used. I rather we don't add too many things to the PATH since it can create problems going forward.

**Comment by alepauly** [comment]
@lol768 thanks for your suggestion but I'm going to close this as won't fix . If you feel strongly about it and want to discuss it further please don't hesitate to reopen.
