### ISSUE TITLE
version number containing tilde should escape before output to Markdown

### ISSUE THREAD

**Issue by zhangyoufu** [actions/virtual-environments#260]
**Describe the bug**
See https://github.com/actions/virtual-environments/blob/master/images/linux/Ubuntu1804-README.md

Version number of Clang 6.0 is shown as version 6.0.1-svn334776-1~exp1~20190309042703.125

**Area for Triage**: 
Scripting and command line

**Question, Bug, or Feature?**: 
Bug

**Virtual environments affected**
- [ ] macOS 10.15
- [x] Ubuntu 16.04 LTS
- [x] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Expected behavior**
version number containing `~` should be displayed correctly

**Actual behavior**
`~` is treated as strike through

**Comment by al-cheb** [comment]
Hi, @zhangyoufu
Thank you for taking the time to report a bug. I have created PR to fix this issue([PR #240 261](https://github.com/actions/virtual-environments/pull/261))

**Comment by zhangyoufu** [comment]
LGTM

I am surprised that tilde can be escaped using backslash. Your [cheatsheet](https://enterprise.github.com/downloads/en/markdown-cheatsheet.pdf) does not mention that tilde is also eligible for escape. The [spec](https://github.github.com/gfm/#backslash-escapes) makes it clear that `any ASCII punctuation character may be backslash-escaped`.

And by the way, the email notification I received contains the following HTML content:
```html
Thank you for taking the time to report a bug. I have created PR to fix this issue(<a href="https://github.com/actions/virtual-environments/pull/261" data-hovercard-type="pull_request" data-hovercard-url="/actions/virtual-environments/pull/261/hovercard">PR #240 261</a>)
```
I have no idea where `PR #240 261` comes from.

**Comment by al-cheb** [comment]
Closed in https://github.com/actions/virtual-environments/pull/261
