### ISSUE TITLE
[Ubuntu, windows] M2_HOME variable will be removed on February, 15

### ISSUE THREAD

**Issue by AlenaSviridenko** [actions/virtual-environments#2600]
**Breaking changes**
M2_HOME variable will be removed from Ubuntu and Windows images on February, 15

**Target date**
Image deployment will start on February, 15 and will take 3-4 days.

**The motivation for the changes**
Since Maven 3.5.0, environment variable [M2_HOME is not used/supported anymore](https://maven.apache.org/docs/3.5.0/release-notes.html#overview-about-the-changes), but on our images it is set and causes issues: https://github.com/actions/virtual-environments/issues/2534

**Possible impact**
If you hardcoded this variable somewhere in your pipeline — your build will be broken

**Virtual environments affected**
- [x] Ubuntu 16.04
- [x] Ubuntu 18.04
- [x] Ubuntu 20.04
- [ ] macOS 10.13
- [ ] macOS 10.14
- [ ] macOS 10.15
- [ ] macOS 11.0
- [x] Windows Server 2016 R2
- [x] Windows Server 2019

**Mitigation ways**
Set this variable manually with the following command:
`echo "M2_HOME=/usr/share/apache-maven-<version>" >> $GITHUB_ENV`

**Comment by famod** [comment]
@AlenaSviridenko What's the status of this? Still awaiting deployment? Thanks!

**Comment by miketimofeev** [comment]
@famod Windows images are not yet deployed. We'll probably finish the deployment by the end of this week.

**Comment by saikirangit** [comment]
Migitation way did not work for my build. It was still complaining about same error of M2_HOME not being set. 

@maxim-lobanov above solution did not work for me and still threw same error... I had to do this to get it working.

This worked. Not the cleanest way but I will convert this to use which mvn than hardcoding the value

    - name: Set up Maven
      uses: stCarolas/setup-maven@v4
      with:
        maven-version: 3.6.3
        
    - name: Set environment variables
      uses: allenevans/set-env@v2.0.1
      with:
        M2_HOME: /opt/hostedtoolcache/maven/3.6.3/x64

**Comment by AlenaSviridenko** [comment]
Windows images were also fully deployed, closing this issue.
