### ISSUE TITLE
python2 code started failing on ubuntu-latest runners

### ISSUE THREAD

**Issue by chenrui333** [actions/virtual-environments#2603]
**Description**  
A clear and concise description of what the bug is, and why you consider it to be a bug.

**Area for Triage**:  

Area: Python

**Bug**:  

Looks like python2 code suddenly failed on CI runners.

```
Use --sandbox_debug to see verbose messages from the sandbox
  File "tools/xx.py", line 104
    print "starting %s..." % xx
          ^
```

**Virtual environments affected**  
- [ ] Ubuntu 16.04
- [x] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Image version**
ubuntu-latest

**Comment by chenrui333** [comment]
Using setup-python action combined with shebang update solved my issue.

**Comment by chenrui333** [comment]
Still not quite sure why it suddenly becomes an issue today.

**Comment by andy-mishechkin** [comment]
Hello, @chenrui333 
Could you provide link to workflow, where you've got the error with python2.
Thank you

**Comment by andy-mishechkin** [comment]
Closing the ticket.
@chenrui333 if this issue still actual and you will be ready to provide any additional information - feel free to reopen.
Thank you.
