### ISSUE TITLE
How does the macOS 11 runner comply with the macOS 11 software license agreement terms?

### ISSUE THREAD

**Issue by riverar** [actions/virtual-environments#2604]
How does this runner comply with the macOS 11 [software license agreement](https://www.apple.com/legal/sla/docs/macOSBigSur.pdf) terms?

![image](https://user-images.githubusercontent.com/475132/100724975-50d28c80-3378-11eb-9ea5-076e3affb089.png)

_Originally posted by @riverar in https://github.com/actions/virtual-environments/issues/1814#issuecomment-736366027_

**Comment by riverar** [comment]
Never got an answer to this, so opening a new issue to track.

**Comment by schen623** [comment]
Also curious about this.

**Comment by miketimofeev** [comment]
I'm afraid we can't provide the information due to NDA so I'm going to close this issue.

**Comment by KalleOlaviNiemitalo** [comment]
I suppose that means a user of GitHub-hosted macOS runners might not have the subleasing right defined in clause 3.B.
