### ISSUE TITLE
Can't run karma with Electron

### ISSUE THREAD

**Issue by DamienCassou** [actions/virtual-environments#2605]
**Description**  

Given this karma configuration file:

```js
config.set({
    frameworks: ["jasmine"],
    port: 9876,
    colors: true,
    logLevel: config.LOG_INFO,
    autoWatch: true,
    browsers: ["Electron"],
    singleRun: true,
    concurrency: Infinity,
});
```

and these dependencies in package.json:

- "karma": "4.4.1",
- "karma-electron": "^6.3.0",
- "karma-electron-launcher": "^0.3.0",
- "karma-jasmine": "^4.0.1",
- "karma-jasmine-diff-reporter": "^2.0.0",
- "electron": "^11.2.1",
- "jasmine": "^3.5.0",
- "jasmine-core": "^3.4.0",

I would expect GitHub Actions to launch Karma with Electron successfully but I get:

```
 $ karma start --single-run
02 02 2021 05:41:00.368:INFO [karma-server]: Karma v4.4.1 server started at http://0.0.0.0:9876/
02 02 2021 05:41:00.371:INFO [launcher]: Launching browsers Electron with concurrency unlimited
02 02 2021 05:41:00.376:INFO [launcher]: Starting browser electron
02 02 2021 05:41:00.833:ERROR [launcher]: Cannot start electron
	
02 02 2021 05:41:00.833:ERROR [launcher]: electron stdout: 
02 02 2021 05:41:00.834:ERROR [launcher]: electron stderr: 
02 02 2021 05:41:00.839:INFO [launcher]: Trying to start electron again (1/2).
02 02 2021 05:41:01.097:ERROR [launcher]: Cannot start electron
	
02 02 2021 05:41:01.097:ERROR [launcher]: electron stdout: 
02 02 2021 05:41:01.098:ERROR [launcher]: electron stderr: 
02 02 2021 05:41:01.099:INFO [launcher]: Trying to start electron again (2/2).
02 02 2021 05:41:01.360:ERROR [launcher]: Cannot start electron
	
02 02 2021 05:41:01.360:ERROR [launcher]: electron stdout: 
02 02 2021 05:41:01.360:ERROR [launcher]: electron stderr: 
02 02 2021 05:41:01.364:ERROR [launcher]: electron failed 2 times (cannot start). Giving up.
error Command failed with exit code 1.
```

**Area for Triage**:  
JavaScript and Node.js

**Question, Bug, or Feature?**:  
Bug

**Virtual environments affected**  
- [ ] Ubuntu 16.04
- [x] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Image version**
20210123.1

**Comment by andy-mishechkin** [comment]
Hello, @DamienCassou 
Could you provide link to your workflow and/or some repro steps ?
Thank you

**Comment by DamienCassou** [comment]
@andy-mishechkin I created a repository with a PR showing the problem: https://github.com/DamienCassou/2021-01-github-actions-karma/pull/1.

In this project, there is an error message that doesn't appear in my real project:

> The futex facility returned an unexpected error code.

**Comment by DamienCassou** [comment]
You solved my problem, thank you very much! You may close the issue.

**Comment by dmitry-shibanov** [comment]
Thank you @DamienCassou. You're welcome
