### ISSUE TITLE
Ubuntu-20.04 runner insufficient disk space

### ISSUE THREAD

**Issue by justusranvier** [actions/virtual-environments#2606]
I have a job that builds some c++ dependencies using vcpkg, and one of them is qt5-declarative.

This job ran successfully from the 15th until the 27th, but as of today it's failing because the vm is running out of storage. I'm using the same version of vcpkg and nothing appreciable has changed in the repo I'm checking out, so something must have changed with the vm image.

The exact same job also runs on windows-2019 and macos-10.15 and neither of them have this issue.

![image](https://user-images.githubusercontent.com/1255702/106404178-6dbe2700-63de-11eb-8d9e-e382ce4a0929.png)

**Comment by justusranvier** [comment]
> Based on documentation, we provide at least 14 GB of free space (https://docs.github.com/en/actions/reference/specifications-for-github-hosted-runners#supported-runners-and-hardware-resources).
> Some images can have more for now but it can be reduced in any moment to 14 GB

That would explain the problem I was seeing because qt5-declarative and its dependencies are enormous.

When I build the same list of packages on my local dev machine (https://github.com/Open-Transactions/opentxs/blob/develop/vcpkg/vcpkg.txt) the resulting vcpkg directory is considerably larger than 14 GB.

![image](https://user-images.githubusercontent.com/1255702/106640622-bd156c00-6532-11eb-8b1c-c450b808f64d.png)

**Comment by maxim-lobanov** [comment]
Not much that we can do here so I am closing the issue.
A few workarounds:
```
sudo rm -rf /usr/local/lib/android # will release about 10 GB if you don't need Android
sudo rm -rf /usr/share/dotnet # will release about 20GB if you don't need .NET
```

**Comment by karuppiah7890** [comment]
thanks a lot @maxim-lobanov !! :D

**Comment by jerrychong25** [comment]
In my case, I've used [Free Disk Space Ubuntu](https://github.com/marketplace/actions/free-disk-space-ubuntu) in GitHub Actions to solve my problem.

Hope this helps those face same issue.

**Comment by jerrychong25** [comment]
> > In my case, I've used [Free Disk Space Ubuntu](https://github.com/marketplace/actions/free-disk-space-ubuntu) in GitHub Actions to solve my problem.
> > Free Disk Space Ubuntu GitHub Actions Sample Code:
> > ```
> > name: sample-github-actions
> > 
> > jobs:
> >   sample_job:
> >     # The host should always be Linux
> >     runs-on: ubuntu-20.04
> >     name: Build on ubuntu-20.04 armv8
> >     steps:
> >       - name: Checkout 🛎️
> >         uses: actions/checkout@v2
> > 
> >       - name: Free Up GitHub Actions Ubuntu Runner Disk Space 🔧
> >         uses: jlumbroso/free-disk-space@main
> >         with:
> >           # This might remove tools that are actually needed, if set to "true" but frees about 6 GB
> >           tool-cache: false
> > 
> >           # All of these default to true, but feel free to set to "false" if necessary for your workflow
> >           android: true
> >           dotnet: true
> >           haskell: true
> >           large-packages: true
> >           swap-storage: true
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Hope this helps those face same issue.
> 
> can i replace the runs-on to self-hosted as in github runner setup it is self-hosted there , or its okay with ubuntu (aws machine image) .

Never tried self-hosted. You can proceed to test and see if it's working or not.

Do update here if working =)

**Comment by subhadip001** [comment]
> 

and also after adding that android:true ....
Unexpected input(s) 'tool-cache', 'android', 'dotnet', 'haskell', 'large-packages', 'swap-storage', valid inputs are ['always-auth', 'node-version', 'node-version-file', 'architecture', 'check-latest', 'registry-url', 'scope', 'token', 'cache', 'cache-dependency-path']
this comes as warning
