### ISSUE TITLE
Some operations in the Github Actions Ubuntu VM extremely slow, causing timeouts

### ISSUE THREAD

**Issue by sulkaharo** [actions/virtual-environments#2607]
**Description**  

The cgm-remote-monitor repository runs unit tests in Github Actions. We have recently observed some tests timing out for no apparent reason. On investigating the issue, it was found that the issue is loading a front end javascript bundle in a headless front end unit test is over 500x slower in Github Actions than when the test is run locally. For example, on the previous unit test run this specific line of code that triggers the import took 45 seconds to execute, while this executes in 78 milliseconds on my laptop.

I've so far worked around this by just adding high timeout allowance to the tests, but this means the unit tests also run very slowly and looks like even a minute / test is currently not enough, for tests that run in <500ms locally on this 4 year old Core i5 laptop.

The call on this line has been timed to be over 500x slower when run in Actions VM than locally:

https://github.com/nightscout/cgm-remote-monitor/blob/dev/tests/fixtures/headless.js#L28

**Area for Triage**:

JavaScript and Node.js

**Question, Bug, or Feature?**: 

Bug

**Virtual environments affected**  
- [ ] Ubuntu 16.04
- [X] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Image version**
20210123.1

**Expected behavior**  
The performance of the VM used to run Actions should roughly linearly scale with the hosting capacity used in Actions, so the code execution speed is roughly in the same ballpark as when run outside of Actions, and definitely not over 100x slower, so a unit test execution time would be max 5x that of test run locally.

**Actual behavior**  
Some logic run in our unit tests is consistently extremely slow in Github Actions, causing random unit test timeouts.

**Repro steps**  
See above for the repo with the problematic unit tests. For an example of a run that timed out, see https://github.com/nightscout/cgm-remote-monitor/pull/6834/checks?check_run_id=1814768839

**Comment by sulkaharo** [comment]
FYI I tried making a minimal repro case for this and the operation mentioned above is running at expected speed when it's the only logic that executes in a build, so looks like the slowdown is caused by some combination of things interacting with the VM running in GA. https://github.com/sulkaharo/reprotest

**Comment by sulkaharo** [comment]
If you want to run the problematic unit tests locally, clone the dev branch of the repo and run `nvm use; npm install; npm run test`(assuming you have nvm, node and MongDB installed). Depending on your hardware, you should see the full test run of all 500 tests complete in 20-30 seconds.

**Comment by jennet333** [comment]
Update

**Comment by andy-mishechkin** [comment]
Hello, @sulkaharo 
Btw. here the specification of GH runner: https://docs.github.com/en/actions/reference/specifications-for-github-hosted-runners#supported-runners-and-hardware-resources, and I think you Core i5 laptop is a more powerful then GH runner. May it cause to performance of your tests ?
Also I see, something your tests have been successful: https://github.com/nightscout/cgm-remote-monitor/runs/1828901134?check_suite_focus=true, also as Careportal test, which was failed here:
https://github.com/nightscout/cgm-remote-monitor/pull/6834/checks?check_run_id=1814768839.
Have you these timeouts always when you run your tests or periodically ? 
Thank you.

**Comment by sulkaharo** [comment]
Hi! Yes - I'm assuming the runner to be slower than the laptop, but I'm expecting the performance should scale roughly linearly and that the tests should run in maybe around half the time compared to local. Right now the difference is the unit test suite completes in 9x the time when run in the GH runner and the individual operations that seem to be contributing the most to the slowdown are over 500x slower.

The tests have mostly been successful due to me adding longer timeouts to the tests. For example, the "careportal" test consistently runs in around 500ms locally and used to run within 45 seconds in GH, but started recently timing out so I bumped the timeout to 60 seconds and it's still randomly failing (so, running >120x slower than locally).

It does look like the execution time of the tests in GH depends slightly on when the tests are run, where on some occasions tests pass without issues, and sometimes the the run time of the test suite is consistently such that the builds fail with random tests timing out and no amount of re-running the tests helps. When run locally, the time does not fluctuate in this manner.

I can work around this by keeping incrementing the test timeouts, but it'd still be better to figure out what's going on, as with the current timeouts and run time it's impossible to catch any performance issues.

**Comment by dmitry-shibanov** [comment]
Hello @sulkaharo. Looks like you project uses some kind of caching. So on your local machine it uses existing cache and run pretty quick. In CI, you build is run on clean machine always and cache is not used.
I was able to confirm it using the following pipeline: https://github.com/dmitry-shibanov/cgm-remote-monitor/runs/1830669855?check_suite_focus=true
In workflow, I run tests 4 times in series. The first run takes ~4 minutes, the next ones - ~2 minutes

**Comment by sulkaharo** [comment]
Hi @dmitry-shibanov - if you look at the build and test scripts, all the files used in the test run are generated in the Install Dependencies phase and the tests actually explicitly flush the database before run. The app logic and the tests don't write anything to disk, so unless one of the frameworks secretly caches data somewhere in an undocumented manner, there is no persistent caching in the app that would explain the speed difference. I have no idea why the subsequent runs in your test are faster - is this the filesystem of the underlying VM having files in a memory cache between the runs?

Also the question is, why are some operations dramatically slower in GH than elsewhere? If you look at the build results from the build you posted:

```
Setting up benv 14
Nightscout bundle ready
Nightscout report bundle start
Nightscout report bundle ready
Bundle loaded 45460
```

the difference of these numbers on these lines is the execution time of the one line of logic in our app, which in this case too about 45 seconds to execute. What that line does is it calls for the benv library to deserialise the javascript bundle created in the Install Dependencies phase to memory. This is the single operation that's causing the most timeout fails and when timed locally, at worst takes ~150ms. Why is there such as _huge_ speed difference between the runtime environments for no obvious reason? Also note the same bundle is loaded multiple times across the tests and load times vary hugely when run in GH specifically, but always runs at least 10x faster locally. So the question I'm posing here really is, what's special about the GH runtime environment that causes these operations to run significantly slower than in other environments?

**Comment by sulkaharo** [comment]
Right, I experimented locally with a clean clone and looks like the behavior you observed between the runs is caused by the line coverage tool (nyc) caching the instrumented code. On a clean run, the worst case local performance jumps to ~2.5 seconds with on that problematic code load. This still means the the performance of this operation is 20-30x slower in GH than locally (depending on the run), so there's an order of magnitude of unexplained performance loss in the GH environment.

**Comment by jennet333** [comment]
TYPO3 Extension

**Comment by dmitry-shibanov** [comment]
Hello @sulkaharo , thank you for your response. We are still pretty sure that the issue is related to caching. If we run the same command 3-4 times in the same workflow, only first run takes a lot of time. All next runs take 2-4.5 seconds that is pretty similar time like you have on local machine.
Could you please try to simplify your repro steps to check if the issue reproduces without `benv` and browser environment? 
We have a bunch of smoke node projects (non-browser related) and we don't notice any performance issues with in comparison with local box.

**Comment by dmitry-shibanov** [comment]
Hello @sulkaharo. Unfortunately, we still can’t reproduce the issue on minimal repro steps (outside of your repository and framework). It looks like the issue comes from framework and caching. If you have any minimum repro steps without or node to show performance degradation on Ubuntu images, please let us know

**Comment by dmitry-shibanov** [comment]
Hello everyone, I'm closing the issue because we can't reproduce it from outside `benv` library or on small repro steps. If you have any concerns feel free to reopen the issue.
