### ISSUE TITLE
Add ability to download built image as artefact in build or GitHub release

### ISSUE THREAD

**Issue by bergmeister** [actions/virtual-environments#2615]
**Tool information**

For self-hosted agents, I would like to re-use the built image, ideally as a Docker image but other formats are probably acceptable as well.
Is this possible to provide as part of the build output on the `main` branch or a GitHub release?

**Area for Triage**:

Servers

**Question, Bug, or Feature?**:

Feature

**Virtual environments affected**
- [x] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [x] Windows Server 2019

**Can this tool be installed during the build?**

NA

**Tool installation time in runtime**
NA

**Are you willing to submit a PR?**

Depending on complexity of build system but I don't think the build system is public?

**Comment by catthehacker** [comment]
@bergmeister are you asking about the images (virtual environments) built from this repository or generally images built with Docker?

**Comment by bergmeister** [comment]
The images produced by this repo so that we have the same software for our self hosted agents and don't have to think about updating the software by just continually pulling the latest image. Image can be docker for hosting within AKS or other image type suitable for azure  scaleset

**Comment by catthehacker** [comment]
I've explained [here](https://github.com/actions/virtual-environments/discussions/2320#discussioncomment-328445) why Docker image of virtual environments is **massive** effort to maintain, make it work and be compatible with upstream.
And here is explanation for why it's not possible to provide images for download: [#176](https://github.com/actions/virtual-environments/issues/176#issuecomment-613117622)

**Comment by maxim-lobanov** [comment]
We can't upload built images anywhere due to legal concerns. Some software installed on images are not allowed for redistribution. 
See details in https://github.com/actions/virtual-environments/issues/176#issuecomment-620638942
