### ISSUE TITLE
broken gcc install on macOS 10.15?

### ISSUE THREAD

**Issue by rdzman** [actions/virtual-environments#2616]
**Description**  
A previously working GitHub action that builds IPOPT from source on macOS runners is now failing due to `configure` not being able to compile a fortran program. Adding `brew reinstall gcc` fixes the problem.

**Area for Triage**:  

Apple

**Question, Bug, or Feature?**:  

Bug

**Virtual environments affected**  
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [x] macOS 11.0
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Image version**

Image version where you are experiencing the issue.
20210130.1

**Expected behavior**  
Build should continue working fine as it has in the past.

**Actual behavior**  
One of the build steps fails as a `configure` script reports `error: cannot compile a simple Fortran program`.

**Repro steps**  
The configuration I am using performs the following steps. I suspect some of steps 2-4 may not be critical for this issue. Step 8 is where the failure happens. Inserting `brew reinstall gcc` between steps 3 and 4 fixes the problem.

1. `brew update`
2. `brew install bash`
3. `rm -rf /usr/local/bin/2to3`
4. `brew install octave`
5. `git clone https://www.github.com/coin-or/coinbrew`
6. `cd coinbrew`
7. `./coinbrew fetch Ipopt --no-prompt`
8. `./coinbrew build Ipopt --prefix=$HOME/install --test --no-prompt`

Here is a link to a [failed run](https://github.com/MATPOWER/matpower/runs/1826534725), and another to a [successful run](https://github.com/MATPOWER/matpower/runs/1832342959) with the `brew reinstall gcc` workaround.

**Comment by vsafonkin** [comment]
Hello @rdzman. I suppose, your build is failed because coinbrew uses `gfortran` symlink that is created during gcc installation through brew. But this symlink is removed on macOS image now, you can find more details here: https://github.com/actions/virtual-environments/issues/1280

You can either re-install gcc via brew (as you`ve  done) or create this symlink manually to point needed gfortran version.

**Comment by rdzman** [comment]
Thanks for the tip.
