### ISSUE TITLE
ChromeWebDriver env variable missing on Ubuntu

### ISSUE THREAD

**Issue by nicojs** [actions/virtual-environments#262]
**Describe the bug**
The [ChromeWebDriver env variable](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/software-installed-on-github-hosted-runners#chrome-driver) seems to be missing on ubunty

**Area for Triage**: 
Bash

**Question, Bug, or Feature?**: 
Bug

**Virtual environments affected**
- [ ] macOS 10.15
- [x] Ubuntu 16.04 LTS
- [x] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Expected behavior**
```yml
    steps:
    - run: env
```

Should also list: CHROMEWEBDRIVER

**Actual behavior**

CHROMEWEBDRIVER is missing

**Comment by maxim-lobanov** [comment]
Hi @nicojs,
This section describes Windows image and this variable is available there. Ubuntu docs doesn't contain this section and variable.
On Ubuntu images, Chrome Driver is available on `/usr/bin/chromedriver`
Probably, it makes sense to introduce this variable on Ubuntu images for consistency.

**Comment by kaylangan** [comment]
Related to #184
