### ISSUE TITLE
binutils removed?

### ISSUE THREAD

**Issue by desolat** [actions/virtual-environments#2621]
**Description**  
Before #986 the Ubuntu images included the `coreutils` and `binutils` packages which now seem to be missing.

**Area for Triage**:  
Packages

**Question, Bug, or Feature?**:  
unknown

**Virtual environments affected**  
- [ ] Ubuntu 16.04
- [x] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Image version**
20210131.1

**Expected behavior**  
`coreutils` and `binutils` are available in the (Ubuntu) images (was the case in beginning of 2020)

**Actual behavior**  
`coreutils` and `binutils` are not available in the (Ubuntu) images

**Repro steps**  

1. Try using commands like `mv` (coreutils) and `strip` (binutils)

**Comment by al-cheb** [comment]
Hello, @desolat 
Could you please check a version property?

```
- name: pkgs
        run: |
          apt list --installed | grep -E "^(bin|core)utils"
```

Ubuntu 18.04:
![image](https://user-images.githubusercontent.com/47745270/106997471-ff89b380-6793-11eb-94c0-3c18cf668a2b.png)

Ubuntu 20.04:
![image](https://user-images.githubusercontent.com/47745270/106997499-0ca6a280-6794-11eb-908d-064d5fe191e7.png)

**Comment by desolat** [comment]
@al-cheb I'm getting the same version info as in your screenshot for Ubuntu 18.04. I'm also a little further with my investigation of what causes the commands to fail: I was using backslashes to break a long command onto multiple lines. [I read that this is supported by Github workflows](https://stackoverflow.com/a/62044610/47407) and the workflow was also executed. Just got `mv: command not found`. Removed that backslash line-continuations and commands are working.
