### ISSUE TITLE
Update Carthage to 0.37.0

### ISSUE THREAD

**Issue by sushant40** [actions/virtual-environments#2623]
**Tool information**
- Tool name: Carthage
- Add or update? Update
- Desired version: 0.37.0
- Approximate size: ??

**Area for Triage**:
iOS, Apple, Xcode

**Question, Bug, or Feature?**:
Feature

**Virtual environments affected**
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [X] macOS 10.15
- [X] macOS 11.0
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Comment by Darleev** [comment]
Hello @sushant40,
Carthage version 0.37.0 will be automatically added to macOS agents right after the next image rollout.
I will keep you informed.

**Comment by sushant40** [comment]
Fantastic thanks! For my own general knowledge. How often are images updated?

**Comment by maxim-lobanov** [comment]
@sushant40 , weekly. Next image with updated Carthage will come by next Wed / Thu

**Comment by sushant40** [comment]
I can see the new carthage on github actions (for personal projects) - however cant see it on Azure Devops (for work projects) - that's still using 20210207.2. Not sure how I originally ended up here - but is Azure DevOps a totally different repository?

**Comment by maxim-lobanov** [comment]
It is the same repo. Deployment process takes some time (~3 days) to update all VMs and these changes are not deployed everywhere yet. We will update this issue when deployment is finished

**Comment by Darleev** [comment]
Hello @sushant40,
We've deployed the required version of Carthage.
I'm going to close the issue. Feel free to contact us.
