### ISSUE TITLE
Unable to use docker-compose with ssh context: OpenSSL version mismatch

### ISSUE THREAD

**Issue by arisudesu** [actions/virtual-environments#2628]
**Description**  
When trying to use docker-compose on ssh docker context, it fails immediately with the error:
```
OpenSSL version mismatch. Built against 1010106f, you have 101000cf
Error: Process completed with exit code 141.
```
Reproduces with real host address (my deploy target) and also with non-existing host, e.g. "ssh://docker@example.host". It did not happen earlier than 01 Feb 2020. Does not repro on local environment (WSL2), that is, it is caused by the actions environment.

Probably installed version is linked against incorrect OpenSSL version?

**Area for Triage**:  

**Question, Bug, or Feature?**:  
Bug

**Virtual environments affected**  
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [x] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Image version**
20210131.1

**Expected behavior**  
Docker-compose working as expected, e.g. connecting to remote hosts.

**Actual behavior**  
Docker-compose failing with OpenSSL error.

**Repro steps**  
I've setup small repo where error is clearly seen: https://github.com/arisudesu/test-repo/runs/1837340166

**Comment by al-cheb** [comment]
Hello, @arisudesu 
Could you please check a workaround from - https://github.com/docker/compose/issues/7724 ?
`sudo pip install docker-compose`

**Comment by arisudesu** [comment]
I've applied this workaround and it does not produce OpenSSL error anymore: https://github.com/arisudesu/test-repo/runs/1837525767. it still fails with exit code 141, but this is due to non-existent ssh host. I've applied the same workaround in private repo where I am using docker-compose on remote context, and the issue is fixed.

**Comment by al-cheb** [comment]
Close as external bug - https://github.com/docker/compose/issues/7686

**Comment by arisudesu** [comment]
It does look to me as environment issue, though. Why does original distribution of compose work, though environment-provided is broken? I expect tools provided by github actions to be working, me not having to fix them with workarounds.

**Comment by al-cheb** [comment]
> It does look to me as environment issue, though. Why does original distribution of compose work if installed from pip, though environment-provided compose is broken? I expect tools provided by github actions to be working, me not having to fix them with workarounds.

We install docker-compose using pre-build release packages - https://github.com/docker/compose#linux. For e.g. take https://github.com/docker/compose/releases/download/1.28.2/docker-compose-Linux-x86_64 package -  pyinstaller bundles   a Python application and all its dependencies into a single package. You can run the packaged app without installing a Python interpreter or any modules.  When started it creates a temporary folder in /tmp with  name _MEIxxxxxx, where xxxxxx is a random number.

```
Using pre-build package:
# /usr/local/bin/docker-compose version
docker-compose version 1.28.2, build 67630359
docker-py version: 4.4.1
CPython version: 3.7.9
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019

# strace docker-compose --context remote up -d --build |& grep libssl
stat("/tmp/_MEIM8k7CS/libssl.so.1.1", 0x7ffe3de07cf0) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/tmp/_MEIM8k7CS/libssl.so.1.1", O_WRONLY|O_CREAT|O_TRUNC, 0666) = 
```
![image](https://user-images.githubusercontent.com/47745270/107218241-6ae7b580-6a20-11eb-90a2-c3a988240381.png)

Installing via pip:
```
# docker-compose version
docker-compose version 1.28.2, build unknown
docker-py version: 4.4.1
CPython version: 3.8.5
OpenSSL version: OpenSSL 1.1.1i  8 Dec 2020

# strace python3 $(which docker-compose) --context remote up -d --build |& grep libssl
openat(AT_FDCWD, "/lib/x86_64-linux-gnu/libssl.so.1.1", O_RDONLY|O_CLOEXEC) = 3
```
Compare outputs above when using pip approach it uses a system library `/lib/x86_64-linux-gnu/libssl.so.1.1`  and works as expected, unlike a pyinstaller bundle.

PS. I agree with you, sometimes  it's painful to use a workaround, but for my mind this issue should be fixed from vendor side.

Why don't we want use pip as the main approach?

If a customer switches the default Python version the docker-compose tool should be reinstalled again.
```
# which python
/opt/hostedtoolcache/Python/3.9.1/x64/bin/python

# which docker-compose
/opt/hostedtoolcache/Python/3.9.1/x64/bin/docker-compose

# pip show docker-compose | grep Location
Location: /opt/hostedtoolcache/Python/3.9.1/x64/lib/python3.9/site-packages
```

**Comment by arisudesu** [comment]
Thanks a lot for the detailed explanation. This is really a vendor-side problem, or even a problem with the delivery of python programs. Github actions are not to blame.
