### ISSUE TITLE
Xcode 12.5 requires macOS 11

### ISSUE THREAD

**Issue by diogot** [actions/virtual-environments#2638]
The next version of Xcode (12.5) will require macOS 11 to run as noted in the [release notes](https://developer.apple.com/documentation/xcode-release-notes/xcode-12_5-beta-release-notes/)

![Screen Shot 2021-02-05 at 11 10 25](https://user-images.githubusercontent.com/885516/107044573-3e733580-67a3-11eb-92e3-ae2efc826be3.png)

It still in beta, but we can expect to have stable release in the next 1 or 2 weeks.
Will the macOS 11 be out of private preview when that happens?

**Comment by Brett-Best** [comment]
Some details here https://github.com/actions/virtual-environments/issues/2486#issuecomment-782034281

**Comment by miketimofeev** [comment]
Hi @diogot!
I'm going to close the issue since we already have Xcode-12.5 on macOS 11 image. Please feel free to ask questions in the https://github.com/actions/virtual-environments/issues/2486
Thank you!
