### ISSUE TITLE
Pester test for msys2 is failing

### ISSUE THREAD

**Issue by majorvin** [actions/virtual-environments#2639]
**Description**  
Pester test for msys2 is failing.

Anyone getting the same issue?

```
 vhd: MSYS2 installation completed
    vhd:
    vhd: Starting discovery in 1 files.
    vhd: Discovering in C:\image\Tests\MSYS2.Tests.ps1.
    vhd: Found 7 tests. 845ms
    vhd: Discovery finished in 1.56s.
    vhd:
    vhd: Running tests from 'C:\image\Tests\MSYS2.Tests.ps1'
    vhd: Describing MSYS2
    vhd:   [+] bash.exe 882ms (581ms|301ms)
    vhd:   [+] tar.exe 4ms (3ms|2ms)
    vhd:   [+] make.exe 4ms (3ms|2ms)
    vhd:   [-] gcc.exe
    vhd:  182ms (179ms|3ms)
    vhd:
    vhd:    at <ScriptBlock>, C:\image\Tests\MSYS2.Tests.ps1:21
    vhd:   [-] cmake.exe 6ms (5ms|2ms)
    vhd:    Expected path 'C:\msys64\mingw64\bin\cmake.exe' to exist, but it did not exist.
    vhd:    at Join-Path $msys2mingwDir $ToolName | Should -Exist, C:\image\Tests\MSYS2.Tests.ps1:21
    vhd:    at <ScriptBlock>, C:\image\Tests\MSYS2.Tests.ps1:21
    vhd:   [-] g++.exe 7ms (5ms|2ms)
    vhd:    Expected path 'C:\msys64\mingw64\bin\g++.exe' to exist, but it did not exist.
    vhd:    at Join-Path $msys2mingwDir $ToolName | Should -Exist, C:\image\Tests\MSYS2.Tests.ps1:21
    vhd:    at <ScriptBlock>, C:\image\Tests\MSYS2.Tests.ps1:21
    vhd:   [-] clang-tidy.exe 6ms (5ms|1ms)
    vhd:    Expected path 'C:\msys64\mingw64\bin\clang-tidy.exe' to exist, but it did not exist.
    vhd:    at Join-Path $msys2mingwDir $ToolName | Should -Exist, C:\image\Tests\MSYS2.Tests.ps1:21
    vhd:    at <ScriptBlock>, C:\image\Tests\MSYS2.Tests.ps1:21
    vhd: Tests completed in 5.5s
    vhd: Tests Passed: 3, Failed: 4, Skipped: 0 NotRun: 0
```

**Virtual environments affected**  
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11.0
- [x ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Comment by Darleev** [comment]
Hello @majorvin,
Did you get the issue during the packer image build? Could you please provide more details about the issue
- packer version
- template file
- minimal repro steps or what did you do to reproduce the issue
We are looking forward to your reply.

**Comment by majorvin** [comment]
Hi @Darleev 
I'm using packer 1.5.1
I'm using the current vs2016 json based off development based off this SHA: 19201a07358e9234ef2c49e8a87bc67895e2f130 Feb 2, 2021

There's no specific way of running it but just running the template. It seems to work but the pester test is failing.

**Comment by LeonidLapshin** [comment]
Hey, @majorvin !
Could you please pull the latest main and try to use Packer 1.6.2 for the image generation since we have no issues using this version? And if it is not successful too, please attach the full installation log from the Install-Msys2.ps1 step.
Thank you!

**Comment by LeonidLapshin** [comment]
Hey, @majorvin !
We have seen this error only 1 error time in a month for all Windows 2016 builds (more than 100), so it looks like it happens very rarely and is related to underlying msys infrastructure. Unfortunately, there is nothing we can do from our side at the moment.
Thank you!
