### ISSUE TITLE
Consider adding Apple M1(ARM-based) virtual environment?

### ISSUE THREAD

**Issue by leiless** [actions/virtual-environments#2641]
Currently, All GitHub-hosted runner virtual environments are based on `x86_64` arch.

Is there any chance to add Apple M1(ARM64-based) virtual environment?

More generally, is there any chance to add ARM-based virtual environments? (Including but not limited to Apple M1)

see:
https://docs.github.com/en/actions/reference/specifications-for-github-hosted-runners#supported-runners-and-hardware-resources

**Comment by catthehacker** [comment]
See https://github.com/actions/virtual-environments/issues/2552#issuecomment-771478000 for general arm64
See https://github.com/actions/virtual-environments/issues/2187#issuecomment-737339211 for darwin/arm64 (Apple)

**Comment by leiless** [comment]
Thx, I'll close this.
