### ISSUE TITLE
Missing GHC 8.10.4 on `windows-latest`

### ISSUE THREAD

**Issue by asr** [actions/virtual-environments#2645]
GHC 8.10.4 was [released](https://mail.haskell.org/pipermail/ghc-devs/2021-February/019490.html). From [this](https://github.com/actions/virtual-environments/blob/main/images/win/Windows2019-Readme.md) list, GHC 8.10.4 is missing on `windows-latest`.

Blocking https://github.com/agda/agda/issues/5178.

**Comment by maxim-lobanov** [comment]
Images are updated on weekly basis so the new image with GHC 8.10.4 will be deployed by the end of this week. Please use official Haskell Action to install the version in runtime: https://github.com/haskell/actions/tree/main/setup

**Comment by miketimofeev** [comment]
@asr ghc 8.10.4 is now available on both windows images. I'm going to close the issue, but please feel free to contact us if you have any concerns.
Thank you!
