### ISSUE TITLE
Add upx

### ISSUE THREAD

**Issue by rflaperuta** [actions/virtual-environments#265]
**Tool information**
- Tool name: upx
- Add or update? Add
- Desired version: latest
- Approximate size: 
- If this is an add request:
  - Brief description of tool: UPX is a free, portable, extendable, high-performance executable packer for several executable formats.
  - URL for tool's homepage: https://upx.github.io/

**Area for Triage**:
Deployment/Release or Packages

**Question, Bug, or Feature?**:
Feature

**Virtual environments affected**
- [ ] macOS 10.15
- [X] Ubuntu 16.04 LTS
- [X] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Can this tool be installed during the build?**
Should be in the Distro Package already

**Are you willing to submit a PR?**
How?

**Comment by al-cheb** [comment]
Hello, @rflaperuta 

Thank you for taking the time to report about new util. I have created PR to fix this issue(https://github.com/actions/virtual-environments/issues/265)
