### ISSUE TITLE
Add Scons

### ISSUE THREAD

**Issue by MCOfficer** [actions/virtual-environments#2650]
**Tool information**
- Tool name: SCons
- Tool license: MIT
- Add or update? Add
- Desired version: Any (as of writing 4.1.0 is latest, but ubuntu repositories are still on 3.x)
- Approximate size: ~3MB
- If this is an add request:
  - Brief description of tool: SCons is a Python-based build system, for the same use cases as Make, CMake, Ninja, Meson etc.
  - URL for tool's homepage: https://scons.org/
  - Provide a basic test case to validate the tool's functionality: `scons -v`

**Area for Triage**: Packages (help, I always think I'm doing these wrong)

**Question, Bug, or Feature?**: Feature

**Virtual environments affected**
- [x] Ubuntu 16.04
- [x] Ubuntu 18.04
- [x] Ubuntu 20.04
- [x] macOS 10.15
- [x] macOS 11.0
- [x] Windows Server 2016 R2
- [x] Windows Server 2019

**Can this tool be installed during the build?**
- Ubuntu: `apt-get install scons`
- MacOS: `brew install scons`
- Windows: This is the tricky one: Scons is not part of the Choco repositories, so it has to be installed from sourceforge. Here's one option, assuming `curl` and `7z` are available.

```powershell
curl -sSf -L http://sourceforge.net/projects/scons/files/scons-local/4.0.1/scons-local-4.0.1.tar.gz > scons-local.tar.gz
7z x scons-local.tar.gz -o C:\whereever\you\want\
# Now add C:\whereever\you\want\ to PATH, I'm sure there's a helper method for it
```

**Tool installation time in runtime**
Depends wildly on OS (and how slow `brew update` is). In best conditions, less than 10s is realistic.

**Are you willing to submit a PR?**
If really necessary, but I can't be sure when I'll have time for it. Obviously I'd prefer it if somebody experienced with the build process for these images could take care of it.

Edit: *Takes 30m to complete the entire issue, and then forgets to give it a title :sweat_smile: *

**Comment by AlenaSviridenko** [comment]
Hi @MCOfficer,
given pretty small installation time, tool popularity, and also non-trivial installation for Windows, we'd rather not to add Scons on our images. Please, continue installing it in runtime.

I am closing this issues, please, feel free to create a new one in case of any other questions. Thanks.

**Comment by MCOfficer** [comment]
> given pretty small installation time, tool popularity, and also non-trivial installation for Windows, we'd rather not to add Scons on our images. Please, continue installing it in runtime.

I should've mentioned it in the initial issue, but the installation time is not the issue. The problem is that we continue to see download failures from sourceforge. We have seen various causes (see the links below), but regardless, this makes our tests rather unreliable.

That's why I opened this issue: If Scons is installed at buildtime, the installation cannot fail at runtime.

Here's how many times the scons installation failed our pipeline, just in the past week:
https://github.com/endless-sky/endless-sky/runs/1855252982?check_suite_focus=true
https://github.com/endless-sky/endless-sky/runs/1827935657?check_suite_focus=true
https://github.com/endless-sky/endless-sky/runs/1819132923?check_suite_focus=true
https://github.com/endless-sky/endless-sky/runs/1819131024?check_suite_focus=true
https://github.com/endless-sky/endless-sky/runs/1819129582?check_suite_focus=true
https://github.com/endless-sky/endless-sky/runs/1808382632?check_suite_focus=true

Considering this, are you willing to reopen?

**Comment by catthehacker** [comment]
You can use https://github.com/actions/cache to cache the download and restore it in the next builds

**Comment by MCOfficer** [comment]
> 
> 
> You can use [actions/cache](https://github.com/actions/cache) to cache the download and restore it in the next builds

That is a possibility, although not one i'm too happy with.

**Comment by MCOfficer** [comment]
I suppose that's a no?
