### ISSUE TITLE
Ubuntu images incorrectly set GOROOT

### ISSUE THREAD

**Issue by FiloSottile** [actions/virtual-environments#2655]
**Description**  

The Ubuntu images should not be setting the `GOROOT` environment variable.

The `GOROOT` environment variable is mostly deprecated, and no setup requires it. The go tool knows to look next to the binary path as well as at the path at which it was built (or at the build-time `GOROOT_FINAL` value), so it can find its `GOROOT` automatically.

The problem with hardcoding a `GOROOT` is that if any other go tool is in use (for example, because one compiled Go tip), the environment variable will override its autodetected `GOROOT`. The result is that the `GOROOT` and the go binary will mismatch, leading to obscure errors.

Related: #2452

**Area for Triage**:  
Go

**Question, Bug, or Feature?**:  
Bug

**Virtual environments affected**  
- [x] Ubuntu 16.04
- [x] Ubuntu 18.04
- [x] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Image version**
20210131.1

**Comment by maxim-lobanov** [comment]
Just a note: `GOROOT` variable is set up on images for a long time (~2-3 years). #2452 just adds it to the documentation.
If we would like to get rid of this variable - we should do proper communication around it to make sure that we won't break any use-cases. Also it makes sense to do these changes consistency across all images.

@FiloSottile , do you aware about any use-cases that could be broken by removing this variable?

**Comment by FiloSottile** [comment]
The only breakage I can imagine is from scripts that use `$GOROOT` directly for some reason, instead of `$(go env GOROOT)`. These scripts would only work in the GitHub Actions environment, since most systems don't have `$GOROOT` defined.

**Comment by dsame** [comment]
The changes are moved to vm rollout and will be available soon

**Comment by miketimofeev** [comment]
The changes were deployed everywhere.
@FiloSottile thanks for bringing this up!
