### ISSUE TITLE
Add PSScriptAnalyzer Powershell module

### ISSUE THREAD

**Issue by bergmeister** [actions/virtual-environments#2659]
**Tool information**
- Tool name: [PSScriptAnalyzer](https://www.powershellgallery.com/packages/PSScriptAnalyzer)
- Tool license: [MIT](https://github.com/PowerShell/PSScriptAnalyzer/blob/master/LICENSE)
- Add or update? Add
- Desired version: Latest (1.19.1)
- Approximate size: 288 MB
- If this is an add request:
  - Brief description of tool: PowerShell's main linter
  - URL for tool's homepage: https://github.com/PowerShell/PSScriptAnalyzer
  - Provide a basic test case to validate the tool's functionality: `Invoke-ScriptAnalyzer -ScriptDefinition 'gci'`

**Area for Triage**:
Packages

**Question, Bug, or Feature?**:
Feature

**Virtual environments affected**
- [x] Ubuntu 16.04
- [x] Ubuntu 18.04
- [x] Ubuntu 20.04
- [x] macOS 10.15
- [x] macOS 11.0
- [x] Windows Server 2016 R2
- [x] Windows Server 2019

If size is an issue, then just Windows would be OK as well. Ubuntu would be a nice to have as Ubuntu is faster.

**Can this tool be installed during the build?**
Yes, see PR below, which is just adding to an existing list of installed PowerShell modules. Or just run `Install-Module -Name PSScriptAnalyzer -Force`

**Tool installation time in runtime**
Around 8 seconds in an Azure DevOps agent (`windows-2019`) using PowerShell Core, its likely a bit faster on an Ubuntu agent.

**Are you willing to submit a PR?**
Yes, there you go: https://github.com/actions/virtual-environments/pull/2644

**Comment by Windos** [comment]
I would love this *so* much, considering *all* of my pipelines (both GitHub Actions and on Azure DevOps) include a step that uses it.

![PSSA](https://user-images.githubusercontent.com/6955786/107291980-ece1e800-6acd-11eb-8c09-a7119d65ae9d.png)

**Comment by maxim-lobanov** [comment]
@bergmeister , thank you for submitting pull-request.
We don't have objections to pre-install this module into the macOS and Windows images. As for the Ubuntu images, let's pre-install module into Ubuntu 20.04 only for now.
Ubuntu 20.04 is going to become `ubuntu-latest` in a few weeks and used by the most of customers so it should work for us.
We have issues with free space on Ubuntu 16.04 and 18.04 so we wouldn't like to install additional tools there for now.
If it sounds good to you - please update PR to exclude ubuntu-1604 and ubuntu-1804 toolsets and we will run validation builds

**Comment by bergmeister** [comment]
@maxim-lobanov  Thanks, I am very happy with solution 😊. I've removed the ubuntu 16.04 and 18.04 entries in PR #2644

**Comment by maxim-lobanov** [comment]
@bergmeister your PR has been merged. Changes should be rollout everywhere next week.

**Comment by bergmeister** [comment]
Awesome, thanks. I am still very impressed with how quick and slick the process is.

**Comment by maxim-lobanov** [comment]
Just an update:
- Changes were deployed to all macOS images and Windows2019
- Ubuntu 20.04 and Windows2016 are still in progress

**Comment by miketimofeev** [comment]
@bergmeister  Both windows images deployed! 
I'm going to close the issue, please feel free to contact us if you have any concerns.
Thank you!
