### ISSUE TITLE
Wrong NDK version on Ubuntu 20.04

### ISSUE THREAD

**Issue by HenrikBacher** [actions/virtual-environments#2675]
**Description**  
During building of a kotlin based android app, the task fails while remove symbols from the bundle. This step relies on Android NDK 21.3.6528147

It fails with this error suggesting that version is not present on the build agent: "No version of NDK matched the requested version 21.3.6528147. Versions available locally: 21.4.7075529, 21.4.7075529, 21.4.7075529, 22.0.7026061"

The readme for the image confirms that version 21.3.6528147 (the current LTS version of NDK) should be present on the build agent
https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-README.md#android

**Area for Triage**:  
Android

**Question, Bug, or Feature?**:  
Bug

**Virtual environments affected**  
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [x] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Image version**

Agent machine name: 'fv-az123-27'
Current agent version: '2.181.1'
Operating System
Ubuntu
20.04.2
LTS
Virtual Environment
Environment: ubuntu-20.04
Version: 20210208.0
Included Software: https://github.com/actions/virtual-environments/blob/ubuntu20/20210208.0/images/linux/Ubuntu2004-README.md
Current image version: '20210208.0'
Agent running as: 'vsts'

**Comment by dibir-magomedsaygitov** [comment]
Hello @HenrikBacher. Thank you for report. Could you please provide minimal repro steps. It would help us to investigate the issue.

**Comment by miketimofeev** [comment]
@HenrikBacher @dibir-magomedsaygitov usually it takes 3-4 days to propagate the image to all the environments, so the build already run on the new image version `20210208.0`, link to the updated software list is available in the logs, that you provided:
![image](https://user-images.githubusercontent.com/48208649/107526909-601c5480-6bc9-11eb-9969-7fc9f5a8e938.png)
https://github.com/actions/virtual-environments/blob/ubuntu20/20210208.0/images/linux/Ubuntu2004-README.md

**Comment by HenrikBacher** [comment]
@miketimofeev That makes sense, didn't think to look at that specific one. The readme in the main branch still lists NDK 21.3: https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-README.md#android

Seems like it was a mistake on our end to rely on a specific version of NDK. Where would be the best place to monitor for when new image rollouts starts?

**Comment by miketimofeev** [comment]
@HenrikBacher main branch readme will be updated once the deployment is finished. We have this section on the page main branch readme will be updated once the deployment is finished, which can be used to track new images rollout progress
![Uploading image.png…]()

**Comment by jackmichalak** [comment]
How do I get this to stay consistent? This is a very frustrating experience. We're barely 40 days into the year and this is the third time I've had to update the NDK version for GH Actions because all our CI is failing.

**Comment by HenrikBacher** [comment]
@jackmichalak My work around was to remove the specific NDK version requirement, long term solution is upgrading to Android Gradle plugin 4.1 which allows you to specify the path to NDK regardless of version: https://developer.android.com/studio/projects/configure-agp-ndk?language=agp4-1

Alternative, you can install the specifc version you require using sdkmanager:
`echo "y" | sudo $ANDROID_HOME/tools/bin/sdkmanager --install "ndk;21.0.6113669" --sdk_root=${ANDROID_SDK_ROOT} `

**Comment by jackmichalak** [comment]
Does that work? I originally added in the specific NDK version because CI was failing with just about the same error without it. I previously tried doing the manual installation you mentioned but it significantly increases the time taken for results. I think we're already on AGP 4.1 so I will try pointing to it directly; thank you for the link.

**Comment by HenrikBacher** [comment]
Works in my build pipeline at least, had the same problem originally that I needed to specify a version already or install the one needed (the install added ~2 minutes to build time).
But after reverting it now, I saw no issues.

**Comment by jackmichalak** [comment]
Yep, that worked. Hopefully it stays that way. Thank you!
