### ISSUE TITLE
Update/Add fastlane

### ISSUE THREAD

**Issue by alwell-kevin** [actions/virtual-environments#2676]
**Tool information**
- Tool name: [fastlane](https://github.com/fastlane/fastlane)
- Tool license: MIT
- Add or update? Add
- Desired version: latest
- Approximate size: unknown
- If this is an add request:
  - Brief description of tool: fastlane is a tool for iOS and Android developers to automate tedious tasks like generating screenshots, dealing with provisioning profiles, and releasing applications.
  - URL for tool's homepage: https://docs.fastlane.tools/
  - Provide a basic test case to validate the tool's functionality:

```
Navigate your terminal to your project's directory and run

_fastlane init_
You'll be asked to confirm that you're ready to begin, and then for a few pieces of information. To get started quickly:

Provide the package name for your application when asked (e.g. io.fabric.yourapp)
Press enter when asked for the path to your json secret file
Answer 'n' when asked if you plan on uploading info to Google Play via fastlane (we can set this up later)
That's it! fastlane will automatically generate a configuration for you based on the information provided.

You can see the newly created ./fastlane directory, with the following files:

Appfile which defines configuration information that is global to your app
Fastfile which defines the "lanes" that drive the behavior of fastlane
```

**Area for Triage**:

**Question, Bug, or Feature?**:

**Virtual environments affected**
- [X] Ubuntu 16.04
- [X] Ubuntu 18.04
- [X] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Can this tool be installed during the build?**

**Tool installation time in runtime**

**Are you willing to submit a PR?**

**Comment by maxim-lobanov** [comment]
Hello @alwell-kevin , we don't have objections to pre-install fastlane on Ubuntu.
Moved to the backlog

**Comment by miketimofeev** [comment]
@alwell-kevin don't you mind if we install Fastlane only on Ubuntu 20 since we have a lack of free space on Ubuntu 18 and Ubuntu 16? Furthermore, Ubuntu 16 is not supported as Fastlane requires Ruby 2.4 and above, but we have 2.3 there.

**Comment by alwell-kevin** [comment]
Hi @miketimofeev @maxim-lobanov let me confirm with the ENG I am working with who made the initial request, thank you!

**Comment by Chuckv01** [comment]
@alwell-kevin / @miketimofeev we're currently running on `ubuntu-20.04`. If Fastlane was installed on that Virtual environment that would be perfect 👍

**Comment by miketimofeev** [comment]
@Chuckv01 @alwell-kevin by the way, Fastlane can be installed using the following command (approx. 4min) until we roll out a new VM image:
`sudo gem install fastlane`

**Comment by Chuckv01** [comment]
@miketimofeev yup! We're currently manually installing Fastlane and requested this ticket so we wouldn't have to do that any longer.

**Comment by miketimofeev** [comment]
@Chuckv01 @alwell-kevin We've finished Ubuntu 20 image deployment with Fastlane 2.175.0 on board.
I'm going to close the issue, but please feel free to contact us if you have any concerns.
Thank you!

**Comment by alwell-kevin** [comment]
Awesome, thank you!

**Comment by Chuckv01** [comment]
Thanks much!
