### ISSUE TITLE
Increase max number of open files. 

### ISSUE THREAD

**Issue by MmtBkn** [actions/virtual-environments#268]
**Describe the bug**
When I run my javascript builds on Ubuntu images, I get the following error message; 
`EMFILE: too many open files`

Related SO Question;
https://stackoverflow.com/questions/8965606/node-and-error-emfile-too-many-open-files

**Area for Triage**: 
Ubuntu image

**Question, Bug, or Feature?**: 
Bug

**Virtual environments affected**
- [ ] macOS 10.15
- [x] Ubuntu 16.04 LTS
- [x] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Expected behavior**
Build shouldn't throw `EMFILE: too many open files` error. 

**Actual behavior**
Build throws `EMFILE: too many open files` error. 

See https://github.com/veritone/veritone-sdk/commit/48fe61ccd51f5358bed65a6a765f0aeeb5cef1a8/checks?check_suite_id=398732036

Increasing the maximum number of open files on OS level should resolve the issue. When I try to add this into the workflow file, I get permission denied. 
`ulimit -Sn 65536`

**Comment by MikailBag** [comment]
Did you try this?
```bash
sudo ulimit -Sn 65536
```

**Comment by miketimofeev** [comment]
@MmtBkn we have implemented a fix and it should be rolled out in 1-2 weeks. Feel free to open a new issue if it still not working.

**Comment by miketimofeev** [comment]
@MmtBkn the image has been deployed. Could you check that everything is fine now, please?

**Comment by MmtBkn** [comment]
Everything works fine, thank you.

**Comment by RainbowMango** [comment]
@miketimofeev and @andy-mishechkin I met this issue on ubuntu-20.04 when I tried to [promote from ubuntu-18.04 to ubuntu-20.04](https://github.com/karmada-io/karmada/pull/2404). Yeah, sure it works on ubuntu-18.04.

You can get the full logs from :
https://github.com/karmada-io/karmada/runs/7952115182?check_suite_focus=true

I tried to find what's the default node number on ubuntu-20.04 as per #340, but seems the configuration changed a lot, I can't figure out it. Can you help to point that?

**Comment by RainbowMango** [comment]
Yeah, I find it:
https://github.com/actions/runner-images/blob/c08d3333864a501c7e0a703c655e391d360da917/images/linux/scripts/base/limits.sh#L9-L10

Seems the limitation is equal to ubuntu-18.04.  Does that mean the ubuntu-20.04 itself uses more files than ubuntu-18.04?

**Comment by miketimofeev** [comment]
@RainbowMango a bit more:
9921 for ub18
10635 for ub20
You can check it using the `lsof | wc -l` command

**Comment by yy158775** [comment]
I check it in the e2e test process.
14685 for lsof | wc -l  
65536 for ulimit -n

But error still appears.
`webhook server exits unexpectedly: too many open files`

**Comment by al-cheb** [comment]
@RainbowMango, @yy158775. Could you check?

```
- name: run e2e
  run: |
          sudo prlimit --pid $$ --nofile=640000:640000
          sudo sysctl fs.inotify.max_user_instances=1280
          sudo sysctl fs.inotify.max_user_watches=655360
          export ARTIFACTS_PATH=/home/runner/work/karmada/karmada/karmada-e2e-logs/v1.24.2/
          hack/run-e2e.sh
```

**Comment by yy158775** [comment]
Thank you.
I add these in the e2e script,it has no such error.
But now I am not very clear how max_user_instances and max_user_watches affect the result.It maybe has to do with kubernetes or kind. By the way,in ubuntu 20.04 these default to 54107 for max_user_watches and 128 for max_user_instances.

**Comment by miketimofeev** [comment]
@yy158775 @RainbowMango the fix is now deployed so no need for a workaround anymore. Sorry for the inconvenience.

**Comment by RainbowMango** [comment]
thanks for your notice @miketimofeev.
I've started my job and I can see the image is [Version: 20220828.1](https://github.com/karmada-io/karmada/runs/8089086951?check_suite_focus=true#step:1:9) now.
