### ISSUE TITLE
Branch fails CI check only on Github Actions. Git corruption? Invisible caching?

### ISSUE THREAD

**Issue by andrioid** [actions/virtual-environments#2682]
**Description**  
One of our branches stopped building. Even re-building an existing ref (that built last week just fine) now fails. It is like the filesystem is in an inconsistant state on the Action Runner. Github support (1015844) told me to create this issue.

Symptoms:
- Our `feature/tag-operations` branch fails only on Github Actions. Other branches work fine on Github Actions.
- I modifed my workflow to seperate the graphql-generation from the typechecking and extracted both the generated file, and the schema. The schema file is at least 3 revisions too old on Github Actions.
- Builds fine on my machine (and the other 3 on my team)
- Builds fine on the action emulator (act)

**Area for Triage**: Git

**Question, Bug, or Feature?**: Bug

**Virtual environments affected**  
- [ ] Ubuntu 16.04
- [x] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Image version**

I can't find where I'm supposed to find this. I'm using "ubuntu-latest" for the workflow file.

**Expected behavior**  

Branch should build (it does so, cleanly on any other system)

**Actual behavior**  

Our `feature/tag-operations` branch fails only on Github Actions while building locally just fine.

**Repro steps**  

You need access to our private repo. Support has already been granted access. Support Ref: 1015844

1. Run the "check.yml" workflow on `feature/tag-operations` branch.
2. Perhaps try to check out the branch and try running the `yarn install && yarn run graphql && yarn run typecheck` manually.

**Theories**

- I've excluded the TypeScript builder (tsc) since the files I extracted via artifacts indicate that they input to the compiler is wrong.
- I've excluded any caching that I control, since I'm not using any.
- It looks like some sort of Git corruption that exists only on the Github runner.
- I've tried removing `fetch-depth: 0`, it had no effect
- I've tried upgrading actions/checkout to `v2` without effect
- **I simply cannot understand how the schema file can look completely different in the build artifact than the one I get when I check the branch out.**

**Comment by vsafonkin** [comment]
Hi @andrioid , unfortunately I have not access to your private repository. If I caught correctly, the `actions/checkout` task is failed on your workflow run. Could you please provide task logs if it possible?

**Comment by andrioid** [comment]
Hi @vsafonkin. AFAIK, the actions/checkout isn't failing. At least I can't see any indication of it. If this was simply an old checkout, then the TypeScript code wouldn't be referencing something that doesn't exist.

Task log follows

```
# Setup
Current runner version: '2.277.1'
Operating System
Virtual Environment
GITHUB_TOKEN Permissions
Prepare workflow directory
Prepare all required actions
Getting action download info
Download action repository 'actions/checkout@v2'
Download action repository 'actions/setup-node@v2'
Download action repository 'actions/upload-artifact@v2'
```

```
# Checkout Action v2
Run actions/checkout@v2
  with:
    fetch-depth: 0
    repository: venue-pos/venuepos
    token: ***
    ssh-strict: true
    persist-credentials: true
    clean: true
    lfs: false
    submodules: false
Syncing repository: venue-pos/venuepos
Getting Git version info
  Working directory is '/home/runner/work/venuepos/venuepos'
  /usr/bin/git version
  git version 2.30.0
Deleting the contents of '/home/runner/work/venuepos/venuepos'
Initializing the repository
  /usr/bin/git init /home/runner/work/venuepos/venuepos
  hint: Using 'master' as the name for the initial branch. This default branch name
  hint: is subject to change. To configure the initial branch name to use in all
  hint: of your new repositories, which will suppress this warning, call:
  hint: 
  hint: 	git config --global init.defaultBranch <name>
  hint: 
  hint: Names commonly chosen instead of 'master' are 'main', 'trunk' and
  hint: 'development'. The just-created branch can be renamed via this command:
  hint: 
  hint: 	git branch -m <name>
  Initialized empty Git repository in /home/runner/work/venuepos/venuepos/.git/
  /usr/bin/git remote add origin https://github.com/venue-pos/venuepos
Disabling automatic garbage collection
  /usr/bin/git config --local gc.auto 0
Setting up auth
  /usr/bin/git config --local --name-only --get-regexp core\.sshCommand
  /usr/bin/git submodule foreach --recursive git config --local --name-only --get-regexp 'core\.sshCommand' && git config --local --unset-all 'core.sshCommand' || :
  /usr/bin/git config --local --name-only --get-regexp http\.https\:\/\/github\.com\/\.extraheader
  /usr/bin/git submodule foreach --recursive git config --local --name-only --get-regexp 'http\.https\:\/\/github\.com\/\.extraheader' && git config --local --unset-all 'http.https://github.com/.extraheader' || :
  /usr/bin/git config --local http.https://github.com/.extraheader AUTHORIZATION: basic ***
Fetching the repository
  /usr/bin/git -c protocol.version=2 fetch --prune --progress --no-recurse-submodules origin +refs/heads/*:refs/remotes/origin/* +refs/tags/*:refs/tags/* +74245b96a546cda59687d9890a9b3da0ef573cbb:refs/remotes/pull/602/merge
  remote: Enumerating objects: 144, done.        
  remote: Counting objects:   0% (1/144)        
  remote: Counting objects:   1% (2/144)
  *snip*
  remote: Counting objects: 100% (144/144)        
  remote: Counting objects: 100% (144/144), done.        
  remote: Compressing objects:   0% (1/124)        
  remote: Compressing objects:   1% (2/124)        
  *snip*
  remote: Compressing objects: 100% (124/124)        
  remote: Compressing objects: 100% (124/124), done.        
  Receiving objects:   0% (1/41537)
  Receiving objects:   1% (416/41537)
  *snip*
  Receiving objects:  99% (41122/41537), 42.36 MiB | 28.26 MiB/s
  remote: Total 41537 (delta 40), reused 56 (delta 14), pack-reused 41393        
  Receiving objects: 100% (41537/41537), 42.36 MiB | 28.26 MiB/s
  Receiving objects: 100% (41537/41537), 50.03 MiB | 29.54 MiB/s, done.
  Resolving deltas:   0% (0/31319)
  Resolving deltas:   1% (314/31319)
  *snip*
  Resolving deltas: 100% (31319/31319)
  Resolving deltas: 100% (31319/31319), done.
  From https://github.com/venue-pos/venuepos
   * [new branch]        feature/tag-operations                   -> origin/feature/tag-operations
   * [new branch]        feature/tag-operations-2                 -> origin/feature/tag-operations-2
   * [new branch]        master                                   -> origin/master
   * [new branch]        test-tag-operations-3                    -> origin/test-tag-operations-3
   *snip*
   * [new tag]           v1.19.3                                  -> v1.19.3
   * [new ref]           74245b96a546cda59687d9890a9b3da0ef573cbb -> pull/602/merge
Determining the checkout info
Checking out the ref
  /usr/bin/git checkout --progress --force refs/remotes/pull/602/merge
  Note: switching to 'refs/remotes/pull/602/merge'.
  
  You are in 'detached HEAD' state. You can look around, make experimental
  changes and commit them, and you can discard any commits you make in this
  state without impacting any branches by switching back to a branch.
  
  If you want to create a new branch to retain commits you create, you may
  do so (now or later) by using -c with the switch command. Example:
  
    git switch -c <new-branch-name>
  
  Or undo this operation with:
  
    git switch -
  
  Turn off this advice by setting config variable advice.detachedHead to false
  
  HEAD is now at 74245b96 Merge b0960384fd4b3af1afffc2201d593e20636896f8 into 83880a6514f08f1a947c0dba4a7f24262fe2b352
/usr/bin/git log -1 --format='%H'
'74245b96a546cda59687d9890a9b3da0ef573cbb'
```

```
# Checks (runs after the graphql generation)
yarn run v1.22.5
$ yarn workspace admin tsc -b && yarn workspace pos tsc -b && yarn workspace admin tsc -b
$ /home/runner/work/venuepos/venuepos/node_modules/.bin/tsc -b
*snip 8 similar errors*
Error: src/screens/account-payments/accounts/tag/tags-create-tab.tsx(38,48): error TS2339: Property 'customerId' does not exist on type 'GQTagInput'.
```

**Comment by andrioid** [comment]
Another weird thing. I decided to print the `git log | head` from the task and also on my computer:

> My computer
>commit 9337b5613b3debb739a0d82e0ece49ead967bfc3
>Author: Andri Oskarsson <myworkemail@company.com>
>Date:   Thu Feb 11 12:43:42 2021 +0100
>
>   added more logging

This same command from the Github task is:

>commit 6f5f497dd66aecca6450c25911c0dd4a3d780e89
>Merge: ee73c976 9337b561
>Author: Another Dev <person@company.com>
>Date:   Thu Feb 11 11:44:11 2021 +0000
>
>Merge 9337b5613b3debb739a0d82e0ece49ead967bfc3 into ee73c976909ce7c4d2f508011bcc2498c305a6bf

**Comment by vsafonkin** [comment]
Yes, it looks weird. Could you check the latest commit of this branch on your repo through GitHub UI? Is it the same as your local version?

**Comment by andrioid** [comment]
Yes.
- Local: 9337b5613b3debb739a0d82e0ece49ead967bfc3
- Github UI: 9337b5613b3debb739a0d82e0ece49ead967bfc3

**Comment by vsafonkin** [comment]
Could you try to update `feature/tag-operations` from master?
```
- checkout to branch
- run `git merge origin/master`
- commit changes and push to repo
```

**Comment by andrioid** [comment]
It's not based off of master, but I updated from the base branch.

Local checkout Ref
>commit 6f690f3abd2d8b8e484f4b6d5c9236d7da047796 (HEAD -> feature/tag-operations, origin/feature/tag-operations)
>Merge: 9337b561 ee73c976
>Date:   Thu Feb 11 15:01:52 2021 +0100
>
>     Merge remote-tracking branch 'origin/release/v1.20' into feature/tag-operations

Github Task
>commit 134425ea3f9f4614b9db52aa5974ba3ff38d80dd
>Merge: ee73c976 6f690f3a
>Date:   Thu Feb 11 14:02:32 2021 +0000
>
>    Merge 6f690f3abd2d8b8e484f4b6d5c9236d7da047796 into ee73c976909ce7c4d2f508011bcc2498c305a6bf

As you can see, it appears to be stuck on some old ref.

**Comment by andrioid** [comment]
If I do as the Github task does; Merge 6f690f3abd2d8b8e484f4b6d5c9236d7da047796 into ee73c976909ce7c4d2f508011bcc2498c305a6bf. Then I get the same build errors.

But why exactly is it doing this merge? It makes no sense to me.

**Comment by vsafonkin** [comment]
Is it correct that you have PR from `feature/tag-operations` to 'origin/release/v1.20' and branch 'origin/release/v1.20' has the latest commit `ee73c976909ce7c4d2f508011bcc2498c305a6bf`?

**Comment by andrioid** [comment]
Yes. Correct.

**Comment by andrioid** [comment]
I can reproduce the error now, after the merge from origin. Let's close this... as weird as it is; I don't think actions are to blame.

**Comment by vsafonkin** [comment]
Anyway, thank you for your help!

**Comment by andrioid** [comment]
Thank you, for your help. You asked some very helpful questions.
