### ISSUE TITLE
[ubuntu, windows] GOROOT environment variable will be removed on March, 1

### ISSUE THREAD

**Issue by AlenaSviridenko** [actions/virtual-environments#2683]
**Breaking changes**
Predefined GOROOT environment variable will be removed on March, 1 from all Ubuntu and Windows images

**Target date**
Images deployment will start on March, 1 and will take 3-4 days.

**The motivation for the changes**
> The GOROOT environment variable is mostly deprecated, and no setup requires it. The problem with hardcoding a GOROOT is that if any other go tool is in use (for example, because one compiled Go tip), the environment variable will override its autodetected GOROOT.

Please, see more details in https://github.com/actions/virtual-environments/issues/2655

**Possible impact**
If your workflow directly use GOROOT — your build will be broken.

**Virtual environments affected**
- [x] Ubuntu 16.04
- [x] Ubuntu 18.04
- [x] Ubuntu 20.04
- [ ] macOS 10.13
- [ ] macOS 10.14
- [ ] macOS 10.15
- [ ] macOS 11.0
- [x] Windows Server 2016 R2
- [x] Windows Server 2019

**Mitigation ways**
Set environment variable as
`echo "GOROOT=$GOROOT_1_15_X64" >> $GITHUB_ENV`

**Comment by miketimofeev** [comment]
We've finished image deployments!
