### ISSUE TITLE
[macOS] Default Xcode will be set to Xcode 12.4 on February, 22

### ISSUE THREAD

**Issue by AlenaSviridenko** [actions/virtual-environments#2685]
**Breaking changes**
Default Xcode will be changed to 12.4, and default Xamarin bundle will be changed to 6_12_6 which includes Xamarin.iOS 14.10, Xamarin.Android 11.1, Xamarin.Mac 7.4, Mono 6.12

**Target date**
Update propagation will start on February, 22 and will take 2-3 days.

**The motivation for the changes**
We would like to provide images with the latest stable updates as a default ones.

**Possible impact**
If you use default Xcode version and your project is not compatible with Xcode 12.4 your build can be broken.

**Virtual environments affected**
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.13
- [ ] macOS 10.14
- [x] macOS 10.15
- [x] macOS 11.0
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Mitigation ways**
Please consider switching Xcode in runtime to version that you need to build app.
The following snippet can be used to switch Xcode:

`sudo xcode-select -s "/Applications/Xcode_12.3.app"`

The list of all available Xcode versions can be found in [image documentation](https://github.com/actions/virtual-environments/blob/main/images/macos/macos-10.15-Readme.md#xcode)

**Comment by dgonzalezp** [comment]
Hi, is AppTrackingTransparency going to be included in this release?

Even forcing Xcode 12.4 if would say

AppDelegate.cs(89,26): error CS0103: The name 'AppTrackingTransparency' does not exist in the current context.

Thanks in advance

**Comment by dgonzalezp** [comment]
Nevermind, found the solution here #1826

Thanks!

**Comment by miketimofeev** [comment]
The image with the default Xcode 12.4 has been deployed
