### ISSUE TITLE
[windows] unable to get the lates MSVC

### ISSUE THREAD

**Issue by pbor** [actions/virtual-environments#2688]
**Description**  

From the documentation I can see that the latest visual studio (16.8) should be available on the images.
However when i run `cl.exe` I see that it is an older version.

If I try to run the following commands I see:

```
 MSVC_INSTALL_DIR=`vswhere -latest -products * -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64 -property installationPath`
cat "${MSVC_INSTALL_DIR}/VC\Auxiliary\Build\Microsoft.VCToolsVersion.default.txt"

14.28.29333
```

How can the latest MSVC be used?
 
I also tried to use https://github.com/microsoft/setup-msbuild/ since some messages suggested that this action could bring in the latest MSVC, but that does not seem to help in my case.

**Area for Triage**:  
Area: C/C++

**Question, Bug, or Feature?**:  
"Question"

**Virtual environments affected**  
- [ ] Windows Server 2019

**Image version**
Version: 20210202.1

**Expected behavior**  
the latest MSVC is available

**Actual behavior**  
MSVC 14 is available

**Comment by al-cheb** [comment]
@pbor, Hey
The latest stable release of the MSVC is 14.28.29333 [14.28	1928 (Visual Studio 2019 Version 16.8)
] - https://en.wikipedia.org/wiki/Microsoft_Visual_C%2B%2B .

**Comment by pbor** [comment]
Ah I see, so MSVC versioning != Visual Studio versioning, thanks for clearing that up.

My CI is failing because it cannot find `<stdalign.h>` even if I specify `/std:c11`, I assumed the problem was the MSVC version, since that is only supported on the latest MSVC.
If MSVC is the latest version,  my problem is somewhere else. 

Closing

Thank you for the quick reply!
