### ISSUE TITLE
Virtual environment request: Arch Linux

### ISSUE THREAD

**Issue by Janrupf** [actions/virtual-environments#27]
**Environment information**
I would like to be able to request Arch Linux as a build platform because honestly Ubuntu is sometimes horribly failing to provide a clean build environment (outdated compiler, g++-9 wont install due to a  package conflict rendering ubuntu unusable for one of my projects). Arch shouldn't have such issues and is a very small OS, there are exisiting VM images to start of with. It would be nice to have an AUR helper (namely `yay`) installed in case AUR packages are required.

**Are you willing to submit a PR?**
Yes

**Comment by kaylangan** [comment]
:wave: Thanks for the suggestion! At this time, we do not have plans to offer alternative Linux distributions. We will offer self-hosted runners at GA (11/13) which will allow you to customize the build agents as you wish.
