### ISSUE TITLE
Please Update the installed Azure RM Powershell module

### ISSUE THREAD

**Issue by mwc360** [actions/virtual-environments#270]
The installed version of Azure RM PowerShell is 2.1.0 which is 7 months old. Please install the latest stable version. It would be great to cut out the 3+min. just to install a newer powershell as part of my release pipelines. 

OR - is there a schedule where the installed version of PS gets update (once a year?, twice a year?). Just looking to see when I can anticipate having a newer version be the default installed. Thx

**Comment by sugarjig** [comment]
The version that I'm actually seeing when using the Azure PowerShell task is 2.6.0, but I agree, it needs to be updated. This is what I see in my logs:
```
Import-Module -Name C:\Modules\az_2.6.0\Az.Accounts\1.6.2\Az.Accounts.psd1 -Global
```
If it helps to have a concrete reason, we use Front Door, and we'd like to set the minimum TLS version using this command: https://docs.microsoft.com/en-us/powershell/module/az.frontdoor/enable-azfrontdoorcustomdomainhttps?view=azps-3.3.0. Version 3.3 of the Az module has a `MinimumTlsVersion` that allows us to do it, but version 2.6. does not.

**Comment by mwc360** [comment]
For my use case, there are a bunch of Azure Data Factory ARM deployment capabilities for features that have been out for a year in ADF that are only available in Version 3.1.0 and greater of PS

**Comment by miketimofeev** [comment]
Hi @mwc360! We have a bunch of new versions installed now, please take a look at the readme
https://github.com/actions/virtual-environments/releases/tag/win19%2F20200301.1
Is this issue still actual?

**Comment by maxim-lobanov** [comment]
@mwc360 , currently, the following versions of `Azure RM Powershell` are available:
- 2.1.0 (default one)
- 3.8.0
- 4.2.1
- 5.1.1
- 6.7.0
- 6.13.1

I am closing the issue for now. Feel free to reopen if you see any issues

**Comment by mwc360** [comment]
The issue was more that the installed version is very old. Installing a new
one every time adds 3+ min on to every CI/CD pipeline when using Azure
hosted agents. I switched to using a self-hosted agent as a workaround so I
could keep the newer version installed. Thx

**Comment by al-cheb** [comment]
Hello, @mwc360 
The Azure RM 6.13.1 module is the latest version. The Az 3.5.0 also presents on our images.
