### ISSUE TITLE
Update Azure Powershell Module, Az

### ISSUE THREAD

**Issue by aholler2** [actions/virtual-environments#2701]
**Tool information**
- Tool name: Az
- Tool license: 
- Add or update? Update to 5.x
- Desired version: 5.5.0
- Approximate size: 

**Area for Triage**:
Scripting and command line

**Question, Bug, or Feature?**:
Feature

**Virtual environments affected**
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [x] Windows Server 2019

**Can this tool be installed during the build?**
Yes,
`
Install-Module Az
`

**Tool installation time in runtime**
2-3 minutes

**Are you willing to submit a PR?**
Not familiar with this repository's PRs

**Comment by LeonidLapshin** [comment]
Hey, @aholler2 
We always try to install the latest version on images and the new one will be installed with the next release this week. We plan to finish the update process until Friday and the new image will be shipped with the latest Azure CLI version.
If you have some problems with current Az version you can update it while the new image rollout is coming.
I'll keep this ticket until the end of update process.
Thank you!

**Comment by LeonidLapshin** [comment]
@aholler2 , sorry, I have mix up Az and Azure CLI :( 
Az tool is installed via toolset and we don't install the latest version each time, so we need to investigate is it possible to add this version to image or not.

**Comment by AlenaSviridenko** [comment]
Hi @aholler2,
we don't mind installing this module to our Windows 2019 image, I will move this ticket to our backlog. 
Thanks!

**Comment by LeonidLapshin** [comment]
Hello, @aholler2 !
New version (5.5) will be available with the next images release next week. I'll check it and report you in this ticket.
Thank you!

**Comment by aholler2** [comment]
@LeonidLapshin Thank you! Much appreciated!

**Comment by slaneyrw** [comment]
> Hello, @aholler2 !
> New version (5.5) will be available with the next images release next week. I'll check it and report you in this ticket.
> Thank you!

Which images are going to be updated?  Just Windows or across the board.  I'm waiting to use the ContainerRegistry module and our Agent is current ubuntu

**Comment by maxim-lobanov** [comment]
Both Windows images for now. Currently, we don't have enough disk space on Ubuntu images. it should be resolved soon (in 1-2 weeks)

**Comment by slaneyrw** [comment]
> Both Windows images for now. Currently, we don't have enough disk space on Ubuntu images. it should be resolved soon (in 1-2 weeks)

Thanks for the update.  Is there an issue I can track for deployed to the other images ?

**Comment by miketimofeev** [comment]
@slaneyrw Az 5.5 will be probably added in the scope of this PR https://github.com/actions/virtual-environments/pull/2735

**Comment by miketimofeev** [comment]
@aholler2 we've successfully deployed both Windows images with Az 5.5.0 on board. I'm going to close the issue, but please feel free to contact us if you have any concerns.
Thank you!
