### ISSUE TITLE
Update CLI from 2.18.0 to 2.19.0

### ISSUE THREAD

**Issue by JPGRodrigues** [actions/virtual-environments#2702]
**Tool information**
- Tool name: Azure CLI
- Tool license: 
- Add or update? Update
- Desired version: 2.19.0
- Approximate size: 

Note: Update request related to bug reported at https://github.com/Azure/azure-cli/issues/16867 

**Area for Triage**:

**Question, Bug, or Feature?**:
Feature

**Virtual environments affected**
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [x] Windows Server 2019

**Can this tool be installed during the build?**

**Tool installation time in runtime**

**Are you willing to submit a PR?**

**Comment by iyerusad** [comment]
Also on virtual environment:

* [X]  Ubuntu 16.04

Possible all others.

---

Similarly have broken deploy pipelines due to Azure/azure-cli#16867

**Comment by LeonidLapshin** [comment]
Hey, @JPGRodrigues 
We always try to install the latest version on images and the new one will be installed with the next release this week. We plan to finish the update process until Friday and the new image will be shipped with the latest Azure CLI version.
I'll keep this issue opened until the appropriate release finished.
Thank you!

**Comment by JPGRodrigues** [comment]
@LeonidLapshin ,
Thank you for the feedback!

**Comment by LeonidLapshin** [comment]
Hey, @JPGRodrigues !
All images will use 2.19 version except Windows 2016, because it now uses the image from 9 of February, Windows 2016 will use 2.19 Azure CLI with the next image rollout. I'll close the issue, but if you have any concerns, feel free to reopen it.
Thank you!
