### ISSUE TITLE
getaddrinfo omits IPv6 info on macOS, Windows runners

### ISSUE THREAD

**Issue by jaraco** [actions/virtual-environments#2705]
**Description**  
In [this run](https://github.com/jaraco/jaraco.net/runs/1893905906?check_suite_focus=true) based on [this minimal repro](https://github.com/jaraco/jaraco.net/tree/bug/bad-lookup), I run a simple command that emits the result of the lookup of an internet name and asserts that it has IPv6 results:

```
python -c "import socket, pprint; pprint.pprint(socket.getaddrinfo('jaraco.com', None)); assert any(':' in item[4][0] for item in socket.getaddrinfo('jaraco.com', None))"
```

This command passes on Linux, but fails on macOS 10.15 and Windows 2019. The same command passes on my local macOS workstation (10.15 and 11.2) and Windows workstation a decade ago.

**Area for Triage**:  
Area: Apple
Area: Containers
Area: Python

**Question, Bug, or Feature?**:  
Bug

**Virtual environments affected**  
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [X] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [X] Windows Server 2019

**Image version**
macos-latest, windows-latest

**Expected behavior**  
The image should have IPv6 enabled and be able to resolve names to IPv6 addresses on Python.

**Actual behavior**  
IPv6 support appears to be incomplete.

**Comment by vsafonkin** [comment]
Hi @jaraco, unfortunately, I don't know something about python' `socket` module implementation, but GitHub hosted runners are not supporting IPv6 at the moment: https://github.com/actions/virtual-environments/issues/668

**Comment by jaraco** [comment]
In this case, I’m not even looking for IPv6 connectivity, only for the OS to have a functional IPv6 stack and to resolve IPv6 addresses over IPv4.

I don’t think the referenced issue is relevant because it’s about Linux and my tests pass on Linux runners. Also, that issue is closed.

is there a feature request thread I can follow where this deficiency can be tracked until it’s addressed?

**Comment by vsafonkin** [comment]
@jaraco , I'm afraid there are no any threads to track it.
