### ISSUE TITLE
Add diffs to releases

### ISSUE THREAD

**Issue by vadi2** [actions/virtual-environments#2706]
I'm monitoring all releases using Github's watch functionality to know when new updates are coming - however, without diffs, it is too difficult to know what changes from one release to another.

Please add diffs to release notes!

**Comment by AlenaSviridenko** [comment]
Hi @vadi2,
for each release we have a corresponding PR where you can review the diff. But even easier way is to click commit next to the release and you will see the diff between release branch and `main` branch 
![image](https://user-images.githubusercontent.com/8777209/107917590-35d7e780-6f79-11eb-877a-f133f56f8b58.png)

Does it work for you?

**Comment by vadi2** [comment]
Perfect. Thanks!
