### ISSUE TITLE
podman requires dnsmasq

### ISSUE THREAD

**Issue by aojea** [actions/virtual-environments#2708]
**Description**  
podman requires dnsmasq to implement custom networks

**Area for Triage**:  

**Question, Bug, or Feature?**:  

Bug, since podman is preinstalled I assume it is expected to be fully functional

**Virtual environments affected**  
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [x] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Image version**

  Version: 20210208.0

**Expected behavior**  
`kind create cluster` using podman should work

**Actual behavior**  
`kind create cluster` fails because podman doesn't find dnsmasq to configure the network dns

**Repro steps**  

You have a failing job here

this is the log https://github.com/kubernetes-sigs/kind/runs/1897246238?check_suite_focus=true
```
ERROR: failed to create cluster: podman run error: command "podman run --hostname kind-control-plane --name kind-control-plane --label io.x-k8s.kind.role=control-plane --privileged --tmpfs /tmp --tmpfs /run --volume 8e70bb2070bb8a9529ce05d177cad46f0717906498affb089d2f2d6857c63048:/var:suid,exec,dev --volume /lib/modules:/lib/modules:ro --detach --tty --net kind --label io.x-k8s.kind.cluster=kind -e container=podman --publish=127.0.0.1:41797:6443/tcp kindest/node@sha256:8f7ea6e7642c0da54f04a7ee10431549c0257315b3a634f6ef2fecaaedb19bab" failed with error: exit status 126

Command Output: WARNING: The same type, major and minor should not be used for multiple devices.
time="2021-02-14T10:42:57Z" level=error msg="Error adding network: unable to locate dnsmasq in path"
time="2021-02-14T10:42:57Z" level=error msg="Error while adding pod to CNI network \"kind\": unable to locate dnsmasq in path"
```

**Comment by aojea** [comment]
opened another issue in podman, because I guess it may be solved if the package requires dnsmasq
https://github.com/containers/podman/issues/9359

**Comment by dibir-magomedsaygitov** [comment]
Hello @aojea. I was able to reproduce the issue and `podmad` indeed requires `dnsmasq` in order to create custom networks. But we prefer to not install such kind of software on our Images due to potential breaking changes.

**Comment by aojea** [comment]
> Hello @aojea. I was able to reproduce the issue and `podmad` indeed requires `dnsmasq` in order to create custom networks. But we prefer to not install such kind of software on our Images due to potential breaking changes.

:+1: that is fair enough, 
Thanks
