### ISSUE TITLE
Add Julia

### ISSUE THREAD

**Issue by SaschaMann** [actions/virtual-environments#271]
**Tool information**
- Tool name: Julia
- Add or update? Add
- Desired version: Latest stable, currently that's v1.3.1
- Approximate size: ~350 MB installed on Linux (70-90 MB download size)
- If this is an add request:
  - Brief description of tool: The Julia programming language. There are many action-like tools written in Julia that run frequently and would benefit a lot from a default installation of Julia, such as [CompatHelper.jl](https://github.com/bcbi/CompatHelper.jl), [Registry Auto Merging](https://github.com/JuliaRegistries/RegistryCI.jl) or [VersionVigilante.jl](https://github.com/bcbi/VersionVigilante.jl)
  - URL for tool's homepage: https://julialang.org/

**Area for Triage**:

**Question, Bug, or Feature?**:
Feature

**Virtual environments affected**
- [X] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [X] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [X] Windows Server 2019

**Can this tool be installed during the build?**
Yes, it can be installed using the [julia-actions/setup-julia](https://github.com/julia-actions/setup-julia) action. It takes approximately 10s per build. Many of the tools mentioned above run many times an hour. Overall this causes multiple TB traffic per day to download and install the tool.

**Are you willing to submit a PR?**
Yes

**Comment by DilumAluthge** [comment]
This issue is still active.

@SaschaMann

**Comment by alepauly** [comment]
reopening, we'll close it once we verify the change has been deployed.

**Comment by maxim-lobanov** [comment]
Julia 1.3.1 is available on all images.

**Comment by SaschaMann** [comment]
Awesome! Thank you all :)
