### ISSUE TITLE
Update Python 3.8 to 3.8.1

### ISSUE THREAD

**Issue by jack1142** [actions/virtual-environments#272]
**Tool information**
- Tool name: Python
- Add or update? Update
- Desired version: 3.8.1
- Approximate size:

**Area for Triage**:
Python

**Question, Bug, or Feature?**:
Feature

**Virtual environments affected**
- [x] macOS 10.15
- [x] Ubuntu 16.04 LTS
- [x] Ubuntu 18.04 LTS
- [x] Windows Server 2016 R2
- [x] Windows Server 2019

**Can this tool be installed during the build?**
I think so?

**Are you willing to submit a PR?**
I could be, but I also never contributed to this repo and don't immediately see what would have to be modified here.

**Comment by jack1142** [comment]
It seems like virtual environment has been updated and now has Python 3.8.1?

**Comment by maxim-lobanov** [comment]
@jack1142 , image rollout is still in progress so some machines can be not updated (usually, rollout takes a few days).
We will report as soon as rollout is finished, thanks!

**Comment by jack1142** [comment]
@maxim-lobanov hi, it's getting close to 2 weeks since your comment, is there any update on image rollout?

**Comment by maxim-lobanov** [comment]
@jack1142 , Sorry for delayed response. Python 3.8.1 should be available on all images.
I am closing the issue, feel free to reopen if you see any issues.
