### ISSUE TITLE
Windows regression: Undefined symbol `strtoflt128` when using MSYS toolchain

### ISSUE THREAD

**Issue by dhermes** [actions/virtual-environments#2721]
**Description**  

For `IMAGEOS=win19`, when `IMAGEVERSION=20210202.1` my project (https://github.com/dhermes/bezier) builds fine. But when `IMAGEVERSION=20210211.1` there is (at least one) missing symbol:

```
...
C:\msys64\mingw64\bin\gfortran.exe -g  -static -shared -o bezier.dll -Wl,--out-implib,bezier.lib -Wl,--major-image-version,2021,--minor-image-version,2 -Wl,--whole-archive CMakeFiles\bezier.dir/objects.a -Wl,--no-whole-archive 
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0\libgfortran.a(read.o):(.text$_gfortrani_convert_real+0xb7): relocation truncated to fit: IMAGE_REL_AMD64_REL32 against undefined symbol `strtoflt128'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0\libgfortran.a(read.o):(.text$_gfortrani_convert_infnan+0xb3): relocation truncated to fit: IMAGE_REL_AMD64_REL32 against undefined symbol `strtoflt128'
collect2.exe: error: ld returned 1 exit status
...
```

Some example failures:

- https://github.com/dhermes/bezier/runs/1907379785?check_suite_focus=true
- https://github.com/dhermes/bezier/runs/1906702188?check_suite_focus=true
- https://github.com/dhermes/bezier/runs/1906726063?check_suite_focus=true

**Area for Triage**:  Packages

**Question, Bug, or Feature?**:  Bug

**Virtual environments affected**  
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [x] Windows Server 2019

**Image version**: `20210211.1`

**Expected behavior**  

Successful compilation

**Actual behavior**  

Missing symbols

**Repro steps**  

1. Run `.github/workflows/windows.yml` from https://github.com/dhermes/bezier

**Comment by dsame** [comment]
@dhermes It looks like you have missed to link `quadmath` library for some reason. I believe the problem is in CMake but it will take the some time to find exact reason. 

Can you please try to enforce `-lquadmath` option in the nox step ?

**Comment by dhermes** [comment]
I manually included `-lquadmath` and the same error occurs: https://github.com/dhermes/bezier/runs/1919653429?check_suite_focus=true

Also (RE: `cmake`) note that the same set compiler commands are emitted in a successful run ([e.g.][1]) and an unsuccessful run ([e.g.][2]):

```
C:\msys64\mingw64\bin\gfortran.exe   -g -fno-second-underscore -Wall -Wextra -Wno-compare-reals -Wimplicit-interface -fmax-errors=1 -std=f2008 -fcheck=all -fbacktrace -fimplicit-none -pedantic -g -ffixed-form -c D:\a\bezier\bezier\src\fortran\quadpack\d1mach.f -o CMakeFiles\quadpack.dir\d1mach.f.obj
C:\msys64\mingw64\bin\gfortran.exe   -g -fno-second-underscore -Wall -Wextra -Wno-compare-reals -Wimplicit-interface -fmax-errors=1 -std=f2008 -fcheck=all -fbacktrace -fimplicit-none -pedantic -g -ffixed-form -c D:\a\bezier\bezier\src\fortran\quadpack\dqagse.f -o CMakeFiles\quadpack.dir\dqagse.f.obj
C:\msys64\mingw64\bin\gfortran.exe   -g -fno-second-underscore -Wall -Wextra -Wno-compare-reals -Wimplicit-interface -fmax-errors=1 -std=f2008 -fcheck=all -fbacktrace -fimplicit-none -pedantic -g -ffixed-form -c D:\a\bezier\bezier\src\fortran\quadpack\dqelg.f -o CMakeFiles\quadpack.dir\dqelg.f.obj
C:\msys64\mingw64\bin\gfortran.exe   -g -fno-second-underscore -Wall -Wextra -Wno-compare-reals -Wimplicit-interface -fmax-errors=1 -std=f2008 -fcheck=all -fbacktrace -fimplicit-none -pedantic -g -ffixed-form -c D:\a\bezier\bezier\src\fortran\quadpack\dqk21.f -o CMakeFiles\quadpack.dir\dqk21.f.obj
C:\msys64\mingw64\bin\gfortran.exe   -g -fno-second-underscore -Wall -Wextra -Wno-compare-reals -Wimplicit-interface -fmax-errors=1 -std=f2008 -fcheck=all -fbacktrace -fimplicit-none -pedantic -g -ffixed-form -c D:\a\bezier\bezier\src\fortran\quadpack\dqpsrt.f -o CMakeFiles\quadpack.dir\dqpsrt.f.obj
C:\msys64\mingw64\bin\gfortran.exe -Dbezier_EXPORTS  -g -fno-second-underscore -Wall -Wextra -Wno-compare-reals -Wno-conversion -Wimplicit-interface -fmax-errors=1 -std=f2008 -fcheck=all -fbacktrace -fimplicit-none -pedantic -g -c D:\a\bezier\bezier\src\fortran\types.f90 -o CMakeFiles\bezier.dir\types.f90.obj
C:\msys64\mingw64\bin\gfortran.exe -Dbezier_EXPORTS  -g -fno-second-underscore -Wall -Wextra -Wno-compare-reals -Wno-conversion -Wimplicit-interface -fmax-errors=1 -std=f2008 -fcheck=all -fbacktrace -fimplicit-none -pedantic -g -c D:\a\bezier\bezier\src\fortran\helpers.f90 -o CMakeFiles\bezier.dir\helpers.f90.obj
C:\msys64\mingw64\bin\gfortran.exe -Dbezier_EXPORTS  -g -fno-second-underscore -Wall -Wextra -Wno-compare-reals -Wno-conversion -Wimplicit-interface -fmax-errors=1 -std=f2008 -fcheck=all -fbacktrace -fimplicit-none -pedantic -g -c D:\a\bezier\bezier\src\fortran\curve.f90 -o CMakeFiles\bezier.dir\curve.f90.obj
C:\msys64\mingw64\bin\gfortran.exe -Dbezier_EXPORTS  -g -fno-second-underscore -Wall -Wextra -Wno-compare-reals -Wno-conversion -Wimplicit-interface -fmax-errors=1 -std=f2008 -fcheck=all -fbacktrace -fimplicit-none -pedantic -g -c D:\a\bezier\bezier\src\fortran\status.f90 -o CMakeFiles\bezier.dir\status.f90.obj
C:\msys64\mingw64\bin\gfortran.exe -Dbezier_EXPORTS  -g -fno-second-underscore -Wall -Wextra -Wno-compare-reals -Wno-conversion -Wimplicit-interface -fmax-errors=1 -std=f2008 -fcheck=all -fbacktrace -fimplicit-none -pedantic -g -c D:\a\bezier\bezier\src\fortran\curve_intersection.f90 -o CMakeFiles\bezier.dir\curve_intersection.f90.obj
C:\msys64\mingw64\bin\gfortran.exe -Dbezier_EXPORTS  -g -fno-second-underscore -Wall -Wextra -Wno-compare-reals -Wno-conversion -Wimplicit-interface -fmax-errors=1 -std=f2008 -fcheck=all -fbacktrace -fimplicit-none -pedantic -g -c D:\a\bezier\bezier\src\fortran\triangle.f90 -o CMakeFiles\bezier.dir\triangle.f90.obj
C:\msys64\mingw64\bin\gfortran.exe -Dbezier_EXPORTS  -g -fno-second-underscore -Wall -Wextra -Wno-compare-reals -Wno-conversion -Wimplicit-interface -fmax-errors=1 -std=f2008 -fcheck=all -fbacktrace -fimplicit-none -pedantic -g -c D:\a\bezier\bezier\src\fortran\triangle_intersection.f90 -o CMakeFiles\bezier.dir\triangle_intersection.f90.obj
C:\msys64\mingw64\bin\gfortran.exe -g  -static -shared -o bezier.dll -Wl,--out-implib,bezier.lib -Wl,--major-image-version,2021,--minor-image-version,2 -Wl,--whole-archive CMakeFiles\bezier.dir/objects.a -Wl,--no-whole-archive
```

(I actually stripped out the timestamps from the raw logs and all lines are identical up to the error except for a runtime pointer in `<function makedirs...` and the ordering of the line `Using pre-installed ...` due to buffered STDOUT)

[1]: https://github.com/dhermes/bezier/runs/1908017867?check_suite_focus=true
[2]: https://github.com/dhermes/bezier/runs/1916171858?check_suite_focus=true

**Comment by dhermes** [comment]
I have been trying to take CMake out of the loop in https://github.com/dhermes/bezier/tree/windows-debug-2721 and just compiling directly, with no luck no matter where `-lquadmath` showed up.

I got rid of the `-static` flag and it compiled / linked without issue. This indicates to me that there is something wrong with the static archive (these are the locations on the image):

```
...
2021-02-17T21:07:02.1986401Z     Directory: C:\msys64\mingw64\lib\gcc\x86_64-w64-mingw32\10.2.0
...
2021-02-17T21:07:02.3670508Z -a----       12/10/2020  12:50 AM        4611392 libgfortran.a
2021-02-17T21:07:02.3691946Z -a----       12/10/2020  12:50 AM        1273122 libgfortran.dll.a
2021-02-17T21:07:02.3721154Z -a----       12/10/2020  12:50 AM            269 libgfortran.spec
...
2021-02-17T21:07:02.4019009Z -a----       12/10/2020  12:50 AM         530340 libquadmath.a
2021-02-17T21:07:02.4035534Z -a----       12/10/2020  12:50 AM          76394 libquadmath.dll.a
...
```

**Comment by dsame** [comment]
@dhermes 

I see there's `--default-image-base-high` linker flag which may cause the problem. While i'm still investigating the problem can you please replace it with --default-image-base-low and/or make sure the option is applied to the filed build?


![image](https://user-images.githubusercontent.com/245540/108952589-8fcc6180-768b-11eb-90e9-993d15c14013.png)

MSys2 team changed the default behaviour of mingw

https://www.msys2.org/news/#2021-01-31-aslr-enabled-by-default

**Comment by dhermes** [comment]
Thank you!

- https://github.com/dhermes/bezier/commit/bfbaf2d8ce8024666105494216f370281730f11d
- https://github.com/dhermes/bezier/actions/runs/596491986

From https://github.com/msys2/MINGW-packages/issues/7023#issuecomment-697952052 it seems like it's an accidental regression in MinGW `gfortran` (and other packages) and hopefully will be fixed in a later version.
