### ISSUE TITLE
[Ubuntu] AzCopy 7 will be removed from Ubuntu images on March, 2

### ISSUE THREAD

**Issue by AlenaSviridenko** [actions/virtual-environments#2724]
**Breaking changes**
AzCopy 7 will be removed from Ubuntu images on March, 2, default will be changed to AzCopy 10.

**Target date**
Image deployment will start on March, 2 and will take 3-4 days.

**The motivation for the changes**
We remove old software versions from Ubuntu images due to a lack of free space. AzCopy 7 was released in 2018 and has never been updated since then. Version 10 is recommended to use since it is in active development and receives regular updates.

**Possible impact**
If you use AzCopy 7-specific commands in your pipeline — it could be broken

**Virtual environments affected**
- [x] Ubuntu 16.04
- [x] Ubuntu 18.04
- [x] Ubuntu 20.04
- [ ] macOS 10.13
- [ ] macOS 10.14
- [ ] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Mitigation ways**
Install AzCopy 7 manually with the following steps:
```
rm -rf /usr/local/bin/azcopy
wget -O azcopy.tar.gz https://aka.ms/downloadazcopylinux64
tar -xf azcopy.tar.gz
rm azcopy.tar.gz
./install.sh
```

**Comment by miketimofeev** [comment]
Done! Azcopy7 was removed from all the images
