### ISSUE TITLE
containerd should be >=1.4.1

### ISSUE THREAD

**Issue by crazy-max** [actions/virtual-environments#2725]
**Description**  

I just saw [virtual envs have been updated](https://github.com/actions/virtual-environments/releases) with Docker 20.10.2 but [containerd is still 1.3.9](https://github.com/docker/build-push-action/runs/1905935045?check_suite_focus=true#step:4:24)  and should be [>=1.4.1](https://github.com/docker/docker-ce-packaging/blob/644c1dda5497e039c27cd47efe42531cce994e39/deb/common/control#L30) no?.

Maybe your release process should follow the [same dependencies provided by docker-ce-packaging control file](https://github.com/docker/docker-ce-packaging/blob/644c1dda5497e039c27cd47efe42531cce994e39/deb/common/control)? WDYT @thaJeztah?

**Area for Triage**:  

**Question, Bug, or Feature?**:  

**Virtual environments affected**  
- [x] Ubuntu 16.04
- [x] Ubuntu 18.04
- [x] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Image version**

Image version where you are experiencing the issue.

Virtual env dumps can be seen here: https://github.com/docker/build-push-action/actions/runs/571262089

**Expected behavior**  
A description of what you expected to happen.

**Actual behavior**  
A description of what is actually happening.

**Repro steps**  
A description with steps to reproduce the issue. If your have a public example or repo to share,
please provide the link.

1. Step 1
2. Step 2

**Comment by catthehacker** [comment]
Microsoft Ubuntu repository has `moby-engine=20.10.2+azure-1` that depends on `moby-containerd (>= 1.3.9)` which is currently latest available `containerd` available from Microsoft repo.
<details>
  <summary>moby-engine</summary>

```
Package: moby-engine
Priority: optional
Section: admin
Installed-Size: 117234
Maintainer: Microsoft <support@microsoft.com>
Architecture: amd64
Version: 20.10.2+azure-1
Replaces: docker, docker-ce, docker-ee, docker-engine, docker-engine-cs, docker.io, lxc-docker, lxc-docker-virtual-package
Depends: moby-containerd (>= 1.3.9), moby-runc (>= 1.0.0~rc10), libc6 (>= 2.8), libdevmapper1.02.1 (>= 2:1.02.97)
Recommends: apparmor, ca-certificates, iptables, kmod, moby-cli, pigz, xz-utils
Suggests: aufs-tools, cgroupfs-mount | cgroup-lite, git
Conflicts: docker, docker-ce, docker-ee, docker-engine, docker-engine-cs, docker.io, lxc-docker, lxc-docker-virtual-package
Filename: pool/main/m/moby-engine/moby-engine_20.10.2+azure-1_amd64.deb
Size: 24737244
MD5sum: c99c5d58936c3fcf3a16ac27196ed67a
SHA1: 483d49fb4b90c9ca1deaf109d1eddf8d01154447
SHA256: 5782d03398d3820b1badffcbd3381c569ad99de24ce6fad57d04ce55cf1b3cd9
SHA512: 58fcf02ff24a7ba6605becedd71fe8424a4f0dbddd02812122c6e3b8aabe9834566b9fd52a4535edd5bc366a9d6212055ec5601038623e57950f71a00597525c
Description: Docker container platform (engine package)
  Moby is an open-source project created by Docker to enable and accelerate software containerization.
Description-md5: 56806acdf606de9d3d33b23f3fe9f631
Homepage: https://github.com/moby/moby
```
</details>
<details>
  <summary>moby-containerd</summary>


```
Package: moby-containerd
Priority: optional
Section: admin
Installed-Size: 126931
Maintainer: Microsoft <support@microsoft.com>
Architecture: amd64
Version: 1.3.9+azure-1
Replaces: containerd, containerd.io
Provides: containerd, containerd.io
Depends: libc6 (>= 2.4), libseccomp2 (>= 2.4.1), moby-runc (>= 1.0.0~rc10)
Recommends: ca-certificates
Conflicts: containerd, containerd.io, moby-engine (<= 3.0.12)
Filename: pool/main/m/moby-containerd/moby-containerd_1.3.9+azure-1_amd64.deb
Size: 27658608
MD5sum: e3065c7306973ab44be8755306bfcf1f
SHA1: 62f3bab380917929a58e75ee600f2a414918fe5c
SHA256: 84c208d774bd93f4b35567359fe4ac51b52aba7861b4b426f58c014818b219c5
SHA512: 999c9cead91dc4b522f2ba977c93beded5356c0e006876c9b939fb463a215f6372ae18aa487165741aa0cf0ceb80258cf7db5b66cc001bddd7eea85ca08e194c
Description: industry-standard container runtime
 containerd is an industry-standard container runtime with an emphasis on
 simplicity, robustness and portability. It is available as a daemon for Linux
 and Windows, which can manage the complete container lifecycle of its host
 system: image transfer and storage, container execution and supervision,
 low-level storage and network attachments, etc.
 .
 containerd is designed to be embedded into a larger system, rather than being
 used directly by developers or end-users.
Description-md5: 0ae6664d1613be15d1579f67c2ad1458
Homepage: https://github.com/containerd/containerd
```
</details>

**Comment by cpuguy83** [comment]
It looks like 20.10.2 was accidentally pushed to the main repos where it should only be in the testing ones (also where 1.4.3 is).

**Comment by cpuguy83** [comment]
I went ahead and updated these to 20.10.3 and 1.4.3 on the main apt repos.

**Comment by crazy-max** [comment]
@cpuguy83 Thanks!

**Comment by maxim-lobanov** [comment]
Thank you @cpuguy83 for fixing it. The updated images should be rollout next week

**Comment by catthehacker** [comment]
@maxim-lobanov Ubuntu images are already rolling out with next version after previous one which fixed the problem so I think the issue can be closed.
