### ISSUE TITLE
Update Go to 1.16 (virtual environments and setup action)

### ISSUE THREAD

**Issue by circa10a** [actions/virtual-environments#2728]
**Tool information**
- Tool name: Go
- Tool license: https://github.com/golang/go/blob/master/LICENSE
- Add or update? Update
- Desired version: 1.16
- Approximate size: Unknown
- If this is an add request:
  - Brief description of tool: Go programming language
  - URL for tool's homepage: https://golang.org/
  - Provide a basic test case to validate the tool's functionality: `go version`

**Area for Triage**: Go

**Question, Bug, or Feature?**: Feature

**Virtual environments affected**
- [x] Ubuntu 16.04
- [x] Ubuntu 18.04
- [x] Ubuntu 20.04
- [x] macOS 10.15
- [x] macOS 11.0
- [x] Windows Server 2016 R2
- [x] Windows Server 2019

**Can this tool be installed during the build?** Yes

**Tool installation time in runtime**: 60s

**Are you willing to submit a PR?**: Sure

**Comment by maxim-lobanov** [comment]
Moved to backlog.

**Comment by LeonidLapshin** [comment]
Hey, @circa10a !
Go 1.16 was added to Windows 2016/2019, Ubuntu 20 and MacOS 10.15/11 and will be available with the next images release next week, I'll check it and report you here.
Thank you!

**Comment by circa10a** [comment]
Thank you @LeonidLapshin !

**Comment by FireFart** [comment]
Hi,
the readme states that go1.16 is already present in the ubuntu 20 images, but running a `go version` on github actions still shows `go version go1.15.8 linux/amd64`. Is there still something missing?

The main problem here is go1.16 deprecated the ioutil package and introduced new methods so code that already changed this will currently not build on github actions with the default tooling (but there is the setup-go action workaround)

**Comment by maxim-lobanov** [comment]
@FireFart ,

**Comment by maxim-lobanov** [comment]
> but there is the setup-go action workaround

@FireFart `setup-go` is not a workaround. It is official and recommended solution how to use Go on Hosted images.
[GitHub Action documentation](https://docs.github.com/en/actions/reference/specifications-for-github-hosted-runners#supported-software) says:
> We recommend using actions to interact with the software installed on runners. This approach has several benefits:
> - Usually, actions provide more flexible functionality like versions selection, ability to pass arguments, and parameters
> - It ensures the tool versions used in your workflow will remain the same regardless of software updates

Hosted Images still have Go 1.15 as default but also contains pre-cached versions 1.14, 1.15, 1.16. `setup-go` will retrieve these versions from cache and switch Go without latency. 
As for the default version, usually we update a default with some delay (2-3 months) to give customers time to adopt projects to new version and don't break customers immediately.

**Comment by FireFart** [comment]
Thanks for the explanation @maxim-lobanov ! Will use the setup-go action then thanks!

**Comment by miketimofeev** [comment]
@circa10a Go 1.16 is now available across all the images. I'm going to close the issue, but please feel free to contact us if you have any concerns.
Thank you!
