### ISSUE TITLE
Update Azure CLI version from 2.0.78 to latest (at least 2.0.80)

### ISSUE THREAD

**Issue by xmaluenda** [actions/virtual-environments#273]
We are building a deployment pipeline which uses Azure CLI to rerefencing KeyVault values into an Appconfig using command:

 ` az appconfig kv set-keyvault ...`
Unfortunatelly, it fails because current installed version of Azure CLI in Azure devops is 2.0.78 and this subcommand is available from version 2.0.79 (last released Azure Cli version is 2.0.80)

Could you update deployed version of Azure Devops Hosted agents as soon as possible, please?

**Comment by heaths** [comment]
Supersedes microsoft/azure-pipelines-image-generation#1362

**Comment by xmaluenda** [comment]
Azure CLI version has been upgraded to 2.0.80 in windows 2019 images last January 21st.
Thanks
