### ISSUE TITLE
Update/Add GDIProcessHandleQuota capability

### ISSUE THREAD

**Issue by quasarea** [actions/virtual-environments#2740]
**Information**
Increase the maximum amount of GDI Object for Windows to maximal decimal value (65536)
https://docs.microsoft.com/en-us/windows/win32/sysinfo/gdi-objects
https://stackoverflow.com/questions/38612364/how-to-increase-the-maximum-amount-of-gdi-object-for-windows-10

**Feature**:

**Virtual environments affected**
- [x] Windows Server 2019

**Can this tool be installed during the build?**
No, requires restart of os

**Description**
Unfortunately windows needs to be restarted after below change is made, so I cant use ms hosted agents. 
```batch
@echo OFF
setlocal ENABLEEXTENSIONS

REM 65536(dec) is the maximum allowed value, resgen.exe runs out of gdi handles when the default 10000(dec) is set
REM see https://developercommunity.visualstudio.com/content/problem/419658/resgenexe-fails-with-large-resx-files.html?childToView=423402#comment-423402

echo Administrative permissions required. Detecting permissions...
net session >nul 2>&1
if %errorLevel% == 0 (
	echo Success: Administrative permissions confirmed.
	set KEY_NAME_x64="HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Windows"
	REG ADD %KEY_NAME_x64% /v "GDIProcessHandleQuota" /t REG_DWORD /d 65536 /f
	set KEY_NAME_x32="HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Windows NT\CurrentVersion\Windows"
	REG ADD %KEY_NAME_x32% /v "GDIProcessHandleQuota" /t REG_DWORD /d 65536 /f
) else (
	echo Failure: Current permissions inadequate, skipping setting registry values.
)
```
**Example Error**
```batch
"C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.8 Tools\ResGen.exe" "D:\a\1\s\Build\Release\Icons.resx" "D:\a\1\s\Build\Release\Icons.resources"
##[error]D:\a\1\s\Build\Release\Icons.resx(425008,5): Error RG0000: The parameter is incorrect Line 425008, position 5.
```

**Comment by al-cheb** [comment]
Hey, @quasarea 
Could you please provide the Icons.resx file to test from our side if changing the GDIProcessHandleQuot setting helps to resolve the issue?

**Comment by quasarea** [comment]
We now have about 4000 icons packaged as resx (provided resx with 4001 icons, but multiplicated as smaller) :
[icons.zip](https://github.com/actions/virtual-environments/files/6024578/icons.zip)

Depending on installed tools resgen can also be in:
```
NETFX 4.6.2 Tools\ResGen.exe
NETFX 4.7.2 Tools\ResGen.exe
```

My azure-pipelines.yml:
```
jobs:
  - job: Build
    pool:
      vmImage: 'windows-latest'
    steps:
      - script: |
          "C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.8 Tools\ResGen.exe" icons.resx icons.resources
```

Running above by windows-latest agent should yield:
```
icons.resx(80112,5): error RG0000: The parameter is incorrect Line 80112, position 5.
1 error(s).
```

Running above by my local agent with registry updated:
```
Read in 4001 resources from ".\icons.resx"
Writing resource file...  Done.
```

Changes made:
```
REG ADD "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Windows" /v "GDIProcessHandleQuota" /t REG_DWORD /d 65536 /f
REG ADD "HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Windows NT\CurrentVersion\Windows" /v "GDIProcessHandleQuota" /t REG_DWORD /d 65536 /f
```
**By default those values are set to 10000 (decimal), after update they are 10000 (hex) which may be confusing**

**OS needs to be reloaded after the change is made.**

**Comment by al-cheb** [comment]
Confirm increase value to 20000 resolve the issue - https://github.com/actions/virtual-environments/pull/2780

**Comment by miketimofeev** [comment]
@quasarea we've deployed the images with the increased value. I'm going to close the issue, but please feel free to contact us if you have any concerns.
Thank you!
