### ISSUE TITLE
System UI isn't responding shows up on Android emulators

### ISSUE THREAD

**Issue by greenEkatherine** [actions/virtual-environments#2741]
**Description**  
Randomly on some android emulators, I got a "System UI isn't responding" error. It pops up and hides the app, so my tests couldn't run correctly.

I tried several approaches to avoid this: increase memory size and delete the app before a new one will be installed. After that, I met it more rarely but still, it happens too often to rely on the results of running tests.

I run out of ideas about what I can do to prevent it from my side or at least how to catch it. Could you please help me to investigate the issue on the agent's side and suggest a way to prevent this?

**Area for Triage**:  
Android

**Question, Bug, or Feature?**:  
Bug

**Virtual environments affected**  
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [x] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Image version**
Environment: macos-10.15
Version: 20210213.1
Included Software: https://github.com/actions/virtual-environments/blob/macOS-10.15/20210213.1/images/macos/macos-10.15-Readme.md
Current image version: '20210213.1'

**Expected behavior**  
Running the instrumentation tests on an android emulator with nothing overlapped on the screen and without performance issues

**Actual behavior**  
Randomly on some devices, I got "System UI isn't responding error". It pops up and hides the app, so my tests couldn't run correctly

**Repro steps**  
Example of the failed job https://dev.azure.com/warpedomen/warpedomen/_build/results?buildId=224&view=logs&j=fef5d8be-9ecf-5e7a-84d5-f2c0b04a2d13&t=eb62fe69-9cc1-5350-b0e0-2918c363984a&l=34580

Also, there you may find screencast in the pipeline artifacts

**Comment by dsame** [comment]
@greenEkatherine we do not have access to your test report, but,  please, confirm you are sure you  are using -x86 HAXM emulator on OSX platform

**Comment by greenEkatherine** [comment]
@dsame thank you for the response.

> please, confirm you are sure you are using -x86 HAXM emulator on OSX platform

I've set `-accel on` and remove `-gpu` to use the default value.  Is it enough? Example of the yaml is here https://github.com/omen273/crosswordApp/blob/check-haxm/azure-pipelines.yml

I still see this error, mostly on API 30 devices. I've attached the log here (API 30)
[logs_272.zip](https://github.com/actions/virtual-environments/files/6018103/logs_272.zip)

Also I noticed in the run where all tests failed the command `adb shell mkdir /mnt/sdcard/DCIM` also failed with "No such file or directory". Example log here (API 28) 
[logs_262.zip](https://github.com/actions/virtual-environments/files/6018366/logs_262.zip)

**Comment by dsame** [comment]
@greenEkatherine  i see your tests waits for the view 10 seconds, please try to increase the timeout to 30 seconds in order to let the emulator to start. 

Also you need to add a delay (or wait for the mount completed in loop) before the accessing external card

**Comment by dsame** [comment]
@greenEkatherine did the timeout help?

Also can you please try to issue `emulator -avd -wipe-data` (or `emulator -avd Your_Device_Name -wipe-data`) before the test run in case if timeout does not help?

**Comment by greenEkatherine** [comment]
Thanks @dsame I will update my PR according to your recommendations today and provide the results here

**Comment by greenEkatherine** [comment]
@dsame unfortunately it doesn't help. I've attached logcat from failed API 30:
[device-30 (1).log](https://github.com/actions/virtual-environments/files/6084409/device-30.1.log)
 and full pipeline log :
[logs_289.zip](https://github.com/actions/virtual-environments/files/6084418/logs_289.zip) .
If it would be better to check in a pipeline just let me know how I may grant you an access.

For this build I added `-wipe-data` and increase timeout https://github.com/omen273/crosswordApp/pull/103/commits/151398ae3b71704f590eafbac92b9da47d8637d9

I didn't add special check for media mounted because I've already have one for one of my test: https://github.com/omen273/crosswordApp/blob/7b3c9b132fdb1f5c4c54fe21f0d924e534fba36e/app/src/androidTest/java/com/example/crosswordToLearn/BadImageReadingInstrumentedTest.kt#L27. I throw an exception if media is not mounted. This exception was never thrown in case of "System UI is not responding" and all tests failed.

**Comment by dsame** [comment]
@greenEkatherine 
which of the pipelines are actual for the moment? 
In one you've mentioned before i still see 10 second timeout
https://dev.azure.com/warpedomen/warpedomen/_build/results?buildId=310&view=logs&j=6a6103bf-e1bd-5dbb-398f-caac80b8eea9&t=b136c181-4a85-5fc4-3778-0dcc8b532602
![image](https://user-images.githubusercontent.com/245540/111418437-8aea5300-8709-11eb-9a3f-f677cc8ddd7a.png)

Please use your test framework API timeout (like this one https://junit.org/junit4/javadoc/4.12/org/junit/rules/Timeout.html)

**Comment by dsame** [comment]
@greenEkatherine Can you please add a command `ls /usr/local/opt/runner/settings/instancename` to your mac os build in order we can identify the machine processes your pipeline and detect possible performance problems?

**Comment by greenEkatherine** [comment]
sure, added

**Comment by greenEkatherine** [comment]
@dsame with correct timeout it looks much better now, but there are few emulator starting failures  - where jobs were cancelled like here https://dev.azure.com/warpedomen/warpedomen/_build/results?buildId=341&view=logs&j=6a6103bf-e1bd-5dbb-398f-caac80b8eea9&t=9e934b8a-9b7e-528c-f2fb-b9d388be27c2&l=620

**Comment by miketimofeev** [comment]
@greenEkatherine the job was canceled due to 40 minutes timeout https://docs.microsoft.com/en-us/azure/devops/pipelines/process/phases?view=azure-devops&tabs=yaml#timeouts But I suppose that even with the increased timeout, the job would never finish

**Comment by greenEkatherine** [comment]
@miketimofeev yes, the emulator there didn't start and it shouldn't be related to initial issue

**Comment by greenEkatherine** [comment]
I didn't see this error any more, I think the issue may be closed. Thanks for the help!

**Comment by miketimofeev** [comment]
@greenEkatherine thanks for confirming! Please feel free to contact us if you have any questions.

**Comment by greenEkatherine** [comment]
I've got that error again https://dev.azure.com/warpedomen/warpedomen/_build/results?buildId=363&view=logs&j=6a6103bf-e1bd-5dbb-398f-caac80b8eea9&t=9e934b8a-9b7e-528c-f2fb-b9d388be27c2&l=12
@miketimofeev @dsame could you please re-open the issue?

**Comment by miketimofeev** [comment]
@greenEkatherine sorry to hear this. We'll take a look

**Comment by dsame** [comment]
The problem is different now

Instead of "System UI isn't responding" there's "test timed out after 30000 milliseconds"

It can be caused either app logic changes or hosts performance problem. 
@greenEkatherine  i do not see the output of `ls /usr/local/opt/runner/settings/instancename` anymore, can you please add it once again in order we can investigate possible performance problem.

**Comment by greenEkatherine** [comment]
@dsame this error message wasn't in log it was on the screen and I still see it on the screencast from the job with all failed tests i.e. 

https://user-images.githubusercontent.com/19972657/112956405-baa14e00-9140-11eb-96df-3d9f1776a057.mp4

`instancename` also is still there at the top of `Run Android Emulator` step. From that run the issue was on CUS1PMC1015G1032-0018

**Comment by dsame** [comment]
@greenEkatherine while we are checking the environment can you increase the timeout to 60sec to ensure with we face performance issue

**Comment by greenEkatherine** [comment]
> @greenEkatherine while we are checking the environment can you increase the timeout to 60sec to ensure with we face performance issue

done

**Comment by dsame** [comment]
@greenEkatherine does increasing the timeout to 60 seconds eliminated the problem or at least make it to appear less often?

**Comment by greenEkatherine** [comment]
@dsame sorry for the late answer, I've noticed that my changes didn't increase timeouts. I'm trying to find where it should be properly increased. Also, I found a way to close the message with a system error, will run several builds to check if it helps

**Comment by greenEkatherine** [comment]
It turned out that changing timeout is not an easy thing so I decided that other optimizing parameters should be enough for my purposes. It doesn't work _always_, but it works in 85% of cases.

**Comment by exeptionerror** [comment]
[[Solved] The system UI isn’t responding in android emulator (Flutter)](https://fluttercorner.com/the-system-ui-isnt-responding-in-android-emulator-flutter/)

**Comment by akamel1** [comment]
> It turned out that changing timeout is not an easy thing so I decided that other optimizing parameters should be enough for my purposes. It doesn't work _always_, but it works in 85% of cases.

what was the final resolution ?

**Comment by charlbury** [comment]
@greenEkatherine how did you figure out how to do this:

> Also, I found a way to close the message with a system error, will run several builds to check if it helps

Also, same as @akamel1 what was the final resolution?

**Comment by amrsa1** [comment]
> @greenEkatherine how did you figure out how to do this:
> 
> > Also, I found a way to close the message with a system error, will run several builds to check if it helps
> 
> Also, same as @akamel1 what was the final resolution?
> 

@charlbury 

I have summarized the entire flow in this article  

https://www.linkedin.com/posts/amrsalem1_the-ultimate-guide-for-cross-platform-e2e-activity-7069617399565541376-yU9m?utm_source=share&utm_medium=member_android


https://www.linkedin.com/posts/amrsalem1_guide-for-cross-platform-e2e-test-for-native-activity-7070388411206905858-QZk3?utm_source=share&utm_medium=member_android

**Comment by charlbury** [comment]
Thanks @amrsa1. I will check that out.
