### ISSUE TITLE
[Feature request] Choosing an action runner other than DSV2

### ISSUE THREAD

**Issue by deepak-bala** [actions/virtual-environments#2743]
**Description**  
I had asked this question to Github support initially, and they pointed me to create an issue in this repo.

We have a couple of Github actions that run on our repository. Github's documentation says that they run on Azure machines of type `dsv2-series`.

We run integration tests that would require a faster machine to complete those jobs quickly (we run several in parallel). Can the action instances that are run be hosted on a `Standard_B4ms` machine instead? The B-series burstable virtual machine is ideal for this type of workload and would provide 4 cores instead of 2.

I'm aware that I can also run self hosted runners myself, but would prefer if Github can swap machines for me. Would it be possible to mention in the `.yml` the kind of machine I want? This can affect the minutes I consume of course.

Something like `jobs.<job_id>.runs-on-machine` = `Standard_B4ms`

**Area for Triage**:  
Containers

**Question, Bug, or Feature?**:  
Feature

**Virtual environments affected**  
- [x] Ubuntu 16.04
- [x] Ubuntu 18.04
- [x] Ubuntu 20.04
- [x] macOS 10.15
- [x] macOS 11.0
- [x] Windows Server 2016 R2
- [x] Windows Server 2019

**Image version**
Not applicable

**Expected behavior**  
I'd like to be able to choose the machine on which a job runs

**Actual behavior**  
All jobs run on DSV2

**Repro steps**  
Not applicable. This is a feature request.

**Comment by maxim-lobanov** [comment]
Hello @deepak-bala ,
Currently, it is not possible to specify type of VM but it is on our roadmap.
See https://github.com/github/roadmap/issues/161 (target date Jul-Sep 2021)

**Comment by deepak-bala** [comment]
That's sweet. I'll close this issue and watch that one instead. Thanks for linking to the roadmap issue.
