### ISSUE TITLE
Add Tkinter

### ISSUE THREAD

**Issue by RealOrangeOne** [actions/virtual-environments#275]
**Tool information**
- Tool name: Tkinter
- Add or update? Add, ish
- Desired version: latest
- Approximate size: 
- If this is an add request:
  - Brief description of tool: Enables the use (or at least import of) the `tkinter` Python module in the standard library
  - URL for tool's homepage: https://wiki.python.org/moin/TkInter

**Area for Triage**:
Python
Packages

**Question, Bug, or Feature?**:
Feature, I guess?

**Virtual environments affected**
- [x] macOS 10.15
- [x] Ubuntu 16.04 LTS
- [x] Ubuntu 18.04 LTS
- [x] Windows Server 2016 R2
- [x] Windows Server 2019

**Can this tool be installed during the build?**
Not to my knowledge. Attempting to install `python3-tk` and `tk-dev` before `@actions/setup-python`, but it doesn't seem to work. Likely requires a rebuild of Python.

**Are you willing to submit a PR?**
If I knew what to do, sure.

**Comment by thejoebourneidentity** [comment]
Thanks for the suggestion @RealOrangeOne , we're accepting this issue and will begin working on it shortly!

**Comment by andy-mishechkin** [comment]
Tkniter already is present in Windows and MacOS images, but because it's a GUI interface, you can't check it from serial console, where you'll lost control, when you run tkniter application.
Additional libraries have been added to Ubuntu images for Tkniter support

**Comment by andy-mishechkin** [comment]
We have tested all Ubuntu version and have got the correct results from test python script - closing the ticket.
Please feel free to reopen this ticket, if you'll find some issues.

**Comment by miketrethewey** [comment]
To be fair, the Windows part of the issue wasn’t really addressed in a descriptive way about how to get around it as opposed to skipping tests or whatever regarding TKinter and Windows.

**Comment by dmitry-shibanov** [comment]
Hello @miketrethewey, thank you for your response. We use PyInstaller to install Python versions on  Windows image. It includes Tkinter by default so everything should work.
Example for Python 3.7:
```
import sys
print(sys.version)
import tkinter as tk
print(tk.TkVersion)
```
Output:
![image](https://user-images.githubusercontent.com/28229110/75750266-e632e880-5d34-11ea-9e16-6c64246ab565.png)
If it doesn’t work for you, could you please share minimal repro steps?

**Comment by miketrethewey** [comment]
Needed a series of hacks to make it work. Our tests include making a `Tk()` element and it's not happy because of that.
[Here](https://github.com/miketrethewey/tkinter-test/runs/481867211)'s an Actions Run that did work properly.

**Comment by miketrethewey** [comment]
@dmitry-shibanov Please see above. Is there a way to streamline that or make it more-visible since people still seem to be running into it?

**Comment by dmitry-shibanov** [comment]
Hello, @miketrethewey, thank you for your response. Am I right that you mention the following code?:
```
        disp=:99
        screen=0
        geom=640x480x24
        exec Xvfb $disp -screen $screen $geom 2>/tmp/Xvfb.log &
        export DISPLAY=:99
        python tkinter_issue.py
```
In our understanding this configuration is user specific and we shouldn’t set it in image generation.
