### ISSUE TITLE
Update/Add Lerna

### ISSUE THREAD

**Issue by Faboli7** [actions/virtual-environments#2754]
**Tool information**
- Tool name:  Lerna
- Tool license: MIT
- Add or update? Add
- Desired version: 3.x or latest
- Approximate size: 80mb
- If this is an add request:
  - Brief description of tool: A tool for managing JavaScript projects with multiple packages => enabling monorepo projects. 
  - URL for tool's homepage: https://github.com/lerna/lerna#readme 
  - Provide a basic test case to validate the tool's functionality:   
   `npm install lerna --global`
`git init lerna-repo && cd lerna-repo`
`lerna init`

**Area for Triage**: JavaScript and Node.js

**Question, Bug, or Feature?**: Feature

**Virtual environments affected** (could of course be installed on all of them, but here's my preference if only one)
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [x] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Can this tool be installed during the build?**

Once Node.js is installed, run npm install --global lerna

**Tool installation time in runtime**

Less than 1 minute

**Are you willing to submit a PR?**

I don't know how to do that but why not.

**Comment by AlenaSviridenko** [comment]
Hi @Faboli7,
we don't mind installing this tool to Ubuntu 20.04, I'll put this ticket to our backlog. 
We'll keep you posted. Thanks

**Comment by Faboli7** [comment]
Great news ! This will significantly improve our pipelines speed. Thanks a lot !

**Comment by Faboli7** [comment]
Hi!
Thank you for the change. 

I have a question though, I don't see it in the image version [20210302.0](https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-README.md), will it be in the next version ?
When I check my latest pipeline runs that use this image version it doesn't seem to be installed either, as the installation step still adds all the packages as if it weren't present yet.

**Comment by miketimofeev** [comment]
@Faboli7 sorry for the inconvenience, I'll take a look

**Comment by miketimofeev** [comment]
@Faboli7 lerna is definitely installed but looks like we forgot to add it to the docs
![image](https://user-images.githubusercontent.com/48208649/110773907-4b85b780-826e-11eb-9f3c-529a0f092389.png)
We will add it to the docs, thanks for noticing that!

**Comment by Faboli7** [comment]
That's weird because I just tried to remove the installation step from my pipeline and then when I try to use lerna I get this:
```
2021-03-11T10:22:16.9374800Z Generating script.
2021-03-11T10:22:16.9388186Z Script contents:
2021-03-11T10:22:16.9389854Z lerna bootstrap
2021-03-11T10:22:16.9391319Z ========================== Starting Command Output ===========================
2021-03-11T10:22:16.9412819Z [command]/bin/bash --noprofile --norc /home/vsts/work/_temp/d2ab21f2-1c0a-45f8-8320-a58cd962b3a7.sh
2021-03-11T10:22:16.9469565Z /home/vsts/work/_temp/d2ab21f2-1c0a-45f8-8320-a58cd962b3a7.sh: line 1: lerna: command not found
2021-03-11T10:22:16.9530130Z ##[error]Bash exited with code '127'.
2021-03-11T10:22:16.9579938Z ##[section]Finishing: Lerna bootstrap
```

If it can help, I'm using node 14
```
Found tool in cache: node 14.16.0 x64
2021-03-11T10:22:00.2246186Z Prepending PATH environment variable with directory: /opt/hostedtoolcache/node/14.16.0/x64/bin```

Is it possible that it was added to another version of node ? Since I see the image also contains node 10 and node 12.
