### ISSUE TITLE
Always yarn install failed  on macOS runnner

### ISSUE THREAD

**Issue by arvinxx** [actions/virtual-environments#2756]
**Description**  
I use macOS Runner to test and build on an electron project( based on npm and yarn). And when I run yarn install. It always failed.

Although I use the taobao npm registry, I don't think the install fail is due to general network connection. Because the install process pass on linux and windows runner.

Here is an example: https://github.com/arvinxx/umi-electron-template/actions/runs/579846219

**Area for Triage**:  

Npm

**Question, Bug, or Feature?**:  
Bug

**Virtual environments affected**  
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [x] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Image version**

 Environment: macos-10.15
  Version: 20210213.1

**Expected behavior**  
Expect macOS runner install dependencies correctly.

**Actual behavior**  
Install failed due to network error. Like this: https://github.com/arvinxx/github-action-macos-runner-install-failed/runs/1931795195?check_suite_focus=true

**Repro steps**  
I have made a mini repo : https://github.com/arvinxx/github-action-macos-runner-install-failed. 

You can see the failed ci here: https://github.com/arvinxx/github-action-macos-runner-install-failed/actions

**Comment by dsame** [comment]
@arvinxx i see the most recent build succeeded, also i forked your repo and had the success build as well.
It seems the temporary network fault has gone.

please confirm

**Comment by arvinxx** [comment]
I have just tried three build action, two pass and one failed :

- ✅  https://github.com/arvinxx/umi-electron-template/actions/runs/580009339 
- ✅  https://github.com/arvinxx/umi-electron-template/runs/1933414880?check_suite_focus=true
- ❌  https://github.com/arvinxx/umi-electron-template/runs/1933417703?check_suite_focus=true

I think it's not a temporary network fault but a network stability problem on macOS runner. Because linux and windows runner can work well all the time.

**Comment by dsame** [comment]
@arvinxx i see the problem appears only for taobao npm registry and the others works works without a problem. I suggest there's a problem with taobao CDN node which services macos datacenter. 

Can you please enforce your build to use the other registry with 
`npm config set registry ...` or `npm install --registry=` ?

the info about taobao npm regitry mirrors can be found here https://npm.taobao.org/mirrors

**Comment by dsame** [comment]
@arvinxx were you able to solve the problem with the tabao mirror? I see the most recent build succeeded and am going to close the issue

**Comment by arvinxx** [comment]
Yeah. Thanks a lot
