### ISSUE TITLE
Error while Creating Image for Azure Devops Self Hosted Agents using the image genration helpers

### ISSUE THREAD

**Issue by Divya1388** [actions/virtual-environments#2760]
**Description**  
I have been using the image generation helpers and trying to create an image for ubuntu 18.04. The script runs for 3 hours and fails. 

**Expected behavior**  
Create an Image for Ubuntu1804 self hosted agents

**Actual behavior**  
I have followed the instructions specified here:  https://github.com/actions/virtual-environments/blob/main/help/CreateImageAndAzureResources.md  to create a image for Ubuntu 18.04 and the script runs for around 3h and fails with the following exception:

![Screen Shot 2021-02-19 at 11 14 13 AM](https://user-images.githubusercontent.com/47507148/108549576-efed8d00-72b2-11eb-8b0b-40df540b97b6.png)

**Repro steps**  
Environment:
Os: MacOS
Packer : v1.7.0
PowerShell:  7.0.3
azure-cli: 2.15.1 *
          core: 2.15.1 *
          telemetry:1.0.6
Az Powershell: 3.3.0     
git: 2.20.1            

Steps:
# clone repo
git clone https://github.com/actions/virtual-environments.git

cd virtual-environments

# Import Helper Modules
Import-Module .\helpers\GenerateResourcesAndImage.ps1

GenerateResourcesAndImage -SubscriptionId "*******************************" -ResourceGroupName "***********" -ImageGenerationRepositoryRoot "$pwd" -ImageType "ubuntu1804" -AzureLocation "eastus" -GithubFeedToken "************************************" -verbose

**Comment by vsafonkin** [comment]
Hi @Divya1388, could you please share a full log? There are many tests for all installed software, these tests run during image generation and any failed test can throws this error.

**Comment by Divya1388** [comment]
Hi @vsafonkin Thank you for the response, i have been building the image on mac and unfortunately i do not have the full logs now. However i observed that the vhd file was created though the build failed. 

And yesterday night i have run the image generation on my parallels and fortunately the image was built successfully.

And now this makes me wonder if the build failed because i ran it on Mac

**Comment by miketimofeev** [comment]
@Divya1388 it shouldn't be the issue since packer is multiplatform — we generate ubuntu images using windows-based agents. 
I'm going to close the issue, but please feel free to contact us if you need any help.
Thank you!
