### ISSUE TITLE
Update/Add rclone

### ISSUE THREAD

**Issue by meidlinga** [actions/virtual-environments#2770]
**Tool information**
- Tool name: rclone
- Tool license: MIT
- Add or update? Add
- Desired version: latest
- Approximate size: 
- If this is an add request:
  - Brief description of tool: Rclone is a command line program to manage files on cloud storage. It is a feature rich alternative to cloud vendors' web storage interfaces having capabilities for partial sync using checksums, instead of modification time. Specifically I would line to use it instead of `azcopy` and `az storage blob sync`. Because of Bugs in both, we are currently forced to use `upload-batch` which always copies everything.
  - URL for tool's homepage: https://rclone.org/
  - Provide a basic test case to validate the tool's functionality:
```
$ rclone version 
rclone v1.50.2
- os/arch: linux/amd64
- go version: go1.13.6

```

**Area for Triage**:
Deployment/Release

**Question, Bug, or Feature?**:
Feature.
(Bug, if forced workaround, because of bugs in azcopy and az cli are considered.)

**Virtual environments affected**
- [ ] Ubuntu 16.04
- [x] Ubuntu 18.04
- [x] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Can this tool be installed during the build?**
apt-get install rclone

**Tool installation time in runtime**
On my machine around 7 seconds using apt.

**Are you willing to submit a PR?**
Yes

**Comment by miketimofeev** [comment]
Hi @meidlinga!
As the tool can be installed pretty quickly in runtime,  we'd rather not add it to the image to avoid additional maintenance.
I'm going to close the issue, but please feel free to contact us if you have any concerns.
Thank you!
