### ISSUE TITLE
switch to a newer ubuntu with podman, buildah and skopeo in default distro repos

### ISSUE THREAD

**Issue by lsm5** [actions/virtual-environments#2774]
So, my teammate @cevich pointed me to https://github.com/actions/virtual-environments/blob/e773a0c743ed249777691014b18d9f071782dcdf/images/linux/scripts/installers/containers.sh#L10 which says that the Kubic project repos are being used to install podman, buildah and skopeo. 

While I'm really glad to see it being used in such a widely used env, I would recommend you consider switching to an Ubuntu version which has podman and related packages available in the default distro repos itself. In the case of Ubuntu, it would be Ubuntu 20.10. For LTS releases, it would be Ubuntu 22.04 (more than a year away).

The Kubic repo should be stable for the most part, but it does not go through the testing process that official Debian/Ubuntu packages go through, and we mention so in the [official install docs](https://github.com/containers/podman.io/blob/master/getting-started/installation.md#ubuntu) as well.

So, would this switch be doable? If not right away, could you please let us know an ETA?

**Comment by miketimofeev** [comment]
Hi @lsm5!
We're not going to add non-LTS versions of Ubuntu to the list of available environments, so let's get back to the proposal when 22.04 has arrived.
I'm going to close the issue, but please feel free to contact us if you have any concerns.
Thank you!
