### ISSUE TITLE
Update default git version

### ISSUE THREAD

**Issue by neutrinog** [actions/virtual-environments#278]
**Tool information**
- Tool name: Git
- Add or update? Update
- Desired version: 2.25.0
- Approximate size: 
- If this is an add request:
  - Brief description of tool: 
  - URL for tool's homepage: 

**Area for Triage**: git

**Question, Bug, or Feature?**: Bug

**Virtual environments affected**
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [x] Windows Server 2016 R2
- [x] Windows Server 2019

**Can this tool be installed during the build?**

**Are you willing to submit a PR?**
It appears that running the install script will automatically install the latest version.

**My Additional Notes**
The currently installed version of git (2.24) contains what I think is a pretty severe bug since it can prevent you from cloning your repository.
See the following from the [Git 2.25 Release Notes](https://raw.githubusercontent.com/git/git/master/Documentation/RelNotes/2.25.0.txt):

```
 * An earlier update to Git for Windows declared that a tree object is
   invalid if it has a path component with backslash in it, which was
   overly strict, which has been corrected.  The only protection the
   Windows users need is to prevent such path (or any path that their
   filesystem cannot check out) from entering the index.
   (merge 224c7d70fa js/mingw-loosen-overstrict-tree-entry-checks later to maint).
```

**Comment by maxim-lobanov** [comment]
Hello!
We install git on Windows images using choco so it updates automatically with each image rollout.
Currently, win images has git 2.25.0 so I am closing this issue.
![image](https://user-images.githubusercontent.com/16715858/74813308-3f972280-5306-11ea-8d32-ca1af70e87af.png)
