### ISSUE TITLE
Add .Net to cached docker images

### ISSUE THREAD

**Issue by dylan-smith** [actions/virtual-environments#2784]
**Tool information**
- Tool name: .Net docker image (pre-cached)
- Add or update? Add
- Desired version: dotnet/sdk:5.0 and dotnet/runtime:5.0
- Approximate size: 617MB and 186MB
- If this is an add request:
  - Brief description of tool: base images for building and deploying .Net docker images, if these were pre-cached in the image it would make docker build for .Net applications faster
  - URL for tool's homepage: https://hub.docker.com/_/microsoft-dotnet

**Area for Triage**:
Containers

**Question, Bug, or Feature?**:
Feature

**Virtual environments affected**
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [X] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [X] Windows Server 2019

**Can this tool be installed during the build?**
Yes
docker pull mcr.microsoft.com/dotnet/sdk:5.0
docker pull mcr.microsoft.com/dotnet/runtime:5.0

**Tool installation time in runtime**
10 seconds

**Are you willing to submit a PR?**
Sure!

**Comment by AlenaSviridenko** [comment]
Hi @dylan-smith,
we don't mind installing it to Ubuntu 20.04 and Windows 2019. Please, feel free to submit PR.
Thank you.

**Comment by miketimofeev** [comment]
@dylan-smith could you please pull the latest main to your branch? Sorry for the delay

**Comment by maxim-lobanov** [comment]
Closing with the same reason like PR above.
