### ISSUE TITLE
Add sqlpackage

### ISSUE THREAD

**Issue by XREvo** [actions/virtual-environments#2787]
**Tool information**
- Tool name: SqlPackage
- Tool license: I don't know, same as DacFx, already present on the windows image
- Add or update? Add
- Desired version: Latest
- Approximate size: 38 Mb
- If this is an add request:
  - Brief description of tool: SqlPackage.exe is a command-line utility that automates the database development tasks (for SQL Server related database)
  - URL for tool's homepage: [https://docs.microsoft.com/fr-fr/sql/tools/sqlpackage/sqlpackage?view=sql-server-ver15](https://docs.microsoft.com/fr-fr/sql/tools/sqlpackage/sqlpackage?view=sql-server-ver15)
  - Provide a basic test case to validate the tool's functionality: `sqlpackage /version`

**Area for Triage**: Databases

**Question, Bug, or Feature?**: Feature"

**Virtual environments affected**
- [x] Ubuntu 16.04
- [x] Ubuntu 18.04
- [x] Ubuntu 20.04
- [x] macOS 10.15
- [ ] macOS 11.0
- [x] Windows Server 2016 R2
- [x] Windows Server 2019

**Can this tool be installed during the build?**
Yes :
1. Install dotnet core (already done on each platform)
2. Install dacfx/sqlpackage. Already done on windows at this time. Installation process and package links are available here : [https://docs.microsoft.com/fr-fr/sql/tools/sqlpackage/sqlpackage-download?view=sql-server-ver15](https://docs.microsoft.com/fr-fr/sql/tools/sqlpackage/sqlpackage-download?view=sql-server-ver15)
3. Add sqlpackage to path environment variable

**Tool installation time in runtime**
I'm not sure. Maybe less than 10 minutes.

**Are you willing to submit a PR?**
Why not!
But first I have to understand how image building works before doing a PR.

**Comment by miketimofeev** [comment]
Hi @XREvo!
Am I right that sqlpackage already exists on windows images in the following path and thus you'd like it to be preinstalled to macOS and Linux as well? `C:\Program Files\Microsoft SQL Server\150\DAC\bin\sqlpackage.exe`

**Comment by miketimofeev** [comment]
@XREvo I've tried to install sqlpackage during runtime using the following steps:
**Ubuntu, takes about 3s**
```
curl "https://go.microsoft.com/fwlink/?linkid=2143497" -4 -sL -o '/tmp/sqlpackage.zip'
unzip /tmp/sqlpackage.zip -d $HOME/sqlpackage
chmod +x $HOME/sqlpackage/sqlpackage
sudo ln -sf $HOME/sqlpackage/sqlpackage /usr/local/bin
sqlpackage /version
```
**macOS, takes about 6s**
```
curl "https://go.microsoft.com/fwlink/?linkid=2143659" -4 -sL -o '/tmp/sqlpackage.zip'
unzip /tmp/sqlpackage.zip -d $HOME/sqlpackage
chmod +x $HOME/sqlpackage/sqlpackage
sudo ln -sf $HOME/sqlpackage/sqlpackage /usr/local/bin
sqlpackage /version
```
Considering the installation time we wouldn't like to add the tool to the image, please use the steps above in your workflow.
I'm going to close the issue, but feel free to contact us if you have any concerns.
Thank you!

**Comment by XREvo** [comment]
Wow! You've answered really fastly!
Thank you very much i appreciate it.

You're right, my main point was to get it pre-installed on osx and ubuntu.
But also get it available in the path env variable (which is not the case under Windows). This would allow us to do not specify a hard encoded path on ours calls to sqlpackage. Right now, if you try to use `sqlpackage /version` on script task under Windows VM, it fails (at least on Azure Pipelines, where i tried it this morning). We have to use the full path in order to use sqlpackage.exe, which is not "fair" compared to nodejs, dotnet, ... a many other tools that are directly available (without specifying a path).

Anyway, i'll migrate my pipeline under ubuntu, and use the script you pasted. Thanks you very much for it.

Have a nice day.

**Comment by miketimofeev** [comment]
@XREvo @caohai the PR adding SqlPackage to Ubuntu images was merged. We are going to deploy new images this week.

**Comment by miketimofeev** [comment]
@XREvo @caohai the images were deployed. I'm going to close the issue.
Thank you for your contribution!
