### ISSUE TITLE
Update/Add Haskell compilers on virtual runner

### ISSUE THREAD

**Issue by recursion-ninja** [actions/virtual-environments#2789]
**Tool information**
- Tool name: ghc & cabal
- Add or update? update
- Desired version: ghc-8.10.4, ghc-9.0.1, cabal-3.4.0.0
- Approximate size: ~200MB
**Area for Triage**:
Haskell

**Question, Bug, or Feature?**:
Feature, using newest version of compiler and build tool

**Virtual environments affected**
- [X] Ubuntu 16.04
- [X] Ubuntu 18.04
- [X] Ubuntu 20.04
- [X] macOS 10.15
- [X] macOS 11.0
- [X] Windows Server 2016 R2
- [X] Windows Server 2019

**Can this tool be installed during the build?**
Yes

**Tool installation time in runtime**
Seconds

**Are you willing to submit a PR?**
Yes, but not sure how.

**Comment by miketimofeev** [comment]
Hi @recursion-ninja!
We install cabal and 2-3 latest Haskell versions through ghcup installer. These particular versions will be deployed next week. The recommended way is to install a specific Haskell version is via https://github.com/actions/setup-haskell action.
I'm going to close the issue, but feel free to contact us if you have any concerns.
Thank you!
