### ISSUE TITLE
AWS CLI: Copy local file to remote bucket started failing

### ISSUE THREAD

**Issue by Avaq** [actions/virtual-environments#2791]
**Description**  

I have a GitHub action that runs something along the lines of the following command:

```sh
aws s3 cp ./local.zip 's3://remote-bucket'
```

This has been working for a long time, but started failing a few weeks ago (the last successful build was on Feb 1, 2021; the first failing build on Feb 8, 2021). The error message it fails with gives me the impression that it's a python dependency issue with a dependency installed for the awscli package.

**Area for Triage**:  
Scripting and command line; Packages

**Question, Bug, or Feature?**:  
Bug

**Virtual environments affected**  
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [x] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Image version**
20210208.0

**Expected behavior**  
The command succeeds and the AWS bucket now contains the zip file. The same command does work on my local machine, where I have used it with several versions of the awscli package.

**Actual behavior**  
The command immediately exits with the following output:

```txt
<botocore.awsrequest.AWSRequest object at 0x7fb6fc4e6668>
Error: Process completed with exit code 255.
```

**Repro steps**  
A description with steps to reproduce the issue. If your have a public example or repo to share,
please provide the link.

1. Create a github workflow containing a `job` with a `step` with a `run` with `aws s3 cp ./local.zip 's3://MY_BUCKET'`
2. Create `local.zip`: `zip -FI local.zip <(echo 'hi')`
3. Commit and push it to GitHub

**Comment by miketimofeev** [comment]
Hi @Avaq! 
I assume you use the `ubuntu-latest` image label, which is now being transitioned from Ubuntu-18 to Ubuntu-20 and thus from AWS cli v1 to v2 — https://github.com/actions/virtual-environments/issues/1816
For AWS cli v2 there is an issue when the region is not specified — https://github.com/aws/aws-cli/issues/5623
Could you please try either specify the region or set `AWS_EC2_METADATA_DISABLED=true` environmental variable?

**Comment by Avaq** [comment]
@miketimofeev Very helpful! Thank you. Setting the region fixed the issue. I should probably use an image label that doesn't cover multiple major versions to avoid confusion in the future. :flushed:
