### ISSUE TITLE
Add Packer

### ISSUE THREAD

**Issue by nielsvbrecht** [actions/virtual-environments#280]
**Tool information**
- Tool name: Packer
- Add or update? Add
- Desired version: latest
- Approximate size: 0.5-2MB
- If this is an add request:
  - Brief description of tool: Packer allows for building (immutable) machine images. Having Packer as a separate standalone binary on the build agents allows for the use of features that are _not_ provided by the Azure DevOps YAML pipeline task. Such as the use of the Shared Image Gallery feature that is possible through the latest version of Packer.
  - URL for tool's homepage: https://www.packer.io

**Area for Triage**:

**Question, Bug, or Feature?**:
"Feature"

**Virtual environments affected**
- [X] macOS 10.15
- [X] Ubuntu 16.04 LTS
- [X] Ubuntu 18.04 LTS
- [X] Windows Server 2016 R2
- [X] Windows Server 2019

**Can this tool be installed during the build?**
It is possible. It will take approximately 1-3 minutes.

**Are you willing to submit a PR?**
If I feel comfortable enough to add code I'm willing :)

**Comment by nielsvbrecht** [comment]
I've created PR 295 for this issue 
[https://github.com/actions/virtual-environments/pull/295](url)

**Comment by maxim-lobanov** [comment]
@nielsvbrecht , thank you for contribution! I have merged PR and changes will be deployed with next image rollout (approximately 1 week).

As for the adding Packer to macOS image, we will take care about it but it will take some time

**Comment by nielsvbrecht** [comment]
@maxim-lobanov I'm happy I am/was able to contribute. Looking forward to the new rolled out machines! :) thank you for your help on this. Also big thanks to @alepauly !

**Comment by maxim-lobanov** [comment]
I have added Packer to macOS images. It will be available next week

**Comment by maxim-lobanov** [comment]
Packer 1.5.4 is present on all images.
