### ISSUE TITLE
Update/Add istioctl

### ISSUE THREAD

**Issue by treyhendon** [actions/virtual-environments#2801]
**Tool information**
- Tool name: istioctl
- Tool license: Apache-2.0
- Add or update? Add
- Desired version: latest (1.72)
- Approximate size: 120MB
- If this is an add request:
  - Brief description of tool: Istio command line diagnostic tool
  - URL for tool's homepage: https://istio.io/
  - Provide a basic test case to validate the tool's functionality: `istioctl -h`

**Area for Triage**:

**Question, Bug, or Feature?**:
Feature

**Virtual environments affected**
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [x] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [x] Windows Server 2019

**Can this tool be installed during the build?**
Yes: https://istio.io/latest/docs/ops/diagnostic-tools/istioctl/

**Tool installation time in runtime**
Download time.

**Are you willing to submit a PR?**
Yes? Any guidelines or examples?

**Comment by miketimofeev** [comment]
It takes 6-7s to install the tool in runtime using the following steps:
```
curl -sL https://istio.io/downloadIstioctl | sh -
export PATH=$PATH:$HOME/.istioctl/bin
```

**Comment by treyhendon** [comment]
Yeah, it wasn't too long of a delay.  I think I was more concerned about the bandwidth - but maybe that's a non-issue?

**Comment by miketimofeev** [comment]
@treyhendon bandwidth shouldn't be the issue. Considering quick installation time, we'd rather not add the tool to the image to avoid additional maintenance efforts.
I'm going to close the issue, but feel free to contact us if you have any concerns.
Thank you!

**Comment by photosca381-cpu** [comment]
Please add istio as well @miketimofeev
