### ISSUE TITLE
[Ubuntu]libgcc_s.so.1 must be installed for pthread_cancel to work

### ISSUE THREAD

**Issue by frostming** [actions/virtual-environments#2803]
**Description**  
I have a GitHub actions workflow that involves installing packages in a multithread manner.

But it randomly fails on Ubuntu ONLY, the error message shows:
```
libgcc_s.so.1 must be installed for pthread_cancel to work
```
I say randomly because I have to retry the build several times(it usually requires about 5 retries) before it finally turns green. I'm annoyed a lot.

**Area for Triage**:  
Area: Python
Area: Packages

**Question, Bug, or Feature?**:  

Bug

**Virtual environments affected**  
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [x] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Image version**

```
Environment: ubuntu-20.04
  Version: 20210219.1
  Included Software: https://github.com/actions/virtual-environments/blob/ubuntu20/20210219.1/images/linux/Ubuntu2004-README.md
```

**Expected behavior**  
A description of what you expected to happen.

**Actual behavior**  
Workflow run successfully without errors

**Repro steps** 

https://github.com/frostming/pdm/runs/1975357854?check_suite_focus=true

**Comment by dmitry-shibanov** [comment]
Hello @frostming. Could you please for ubuntu builds make this setup: 
 - In `Install Dev Dependencies` add environment variable `LD_PRELOAD=/lib/x86_64-linux-gnu/libgcc_s.so.1`:
 ```
      - name: Install Dev Dependencies
        run: |
          export LD_PRELOAD=/lib/x86_64-linux-gnu/libgcc_s.so.1
          pdm config parallel_install true
          pdm install -dvv
 ```

I rerun ubuntu builds with this configuration 3 time in a row and they were green.

**Comment by frostming** [comment]
Thanks @dmitry-shibanov I added following step to the workflow and it works rightly:
```yaml
- name: Fix Ubuntu Env
  run: |
    echo "LD_PRELOAD=/lib/x86_64-linux-gnu/libgcc_s.so.1" >> $GITHUB_ENV
  if: runner.os == 'Linux'
```
So my last question is: why does it not become the default libgcc?
