### ISSUE TITLE
Update/Add Cygwin

### ISSUE THREAD

**Issue by Endle** [actions/virtual-environments#2806]
**Tool information**
- Tool name: cygwin
- Tool license: LGPLv3
- Add or update? Add
- Desired version:
- Approximate size: Latest
- If this is an add request:
  - Brief description of tool: A large collection of GNU and Open Source tools which provide functionality similar to a Linux distribution on Windows.
  - URL for tool's homepage: https://cygwin.com/index.html
  - Provide a basic test case to validate the tool's functionality: 

**Area for Triage**: Scripting and command line

**Question, Bug, or Feature?**: Feature

**Virtual environments affected**
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11.0
- [x] Windows Server 2016 R2
- [x] Windows Server 2019

**Can this tool be installed during the build?**
https://github.com/marketplace/actions/install-cygwin

**Tool installation time in runtime**
Less than 10 minutes

**Are you willing to submit a PR?**
Yes. I'm not familiar of Github Action configuration yet.

**Comment by maxim-lobanov** [comment]
Thank you for your proposal, considering tool size and existence action to install it in runtime, we are not sure that it makes sense to pre-install this tool into the images.
We will the issue opened for some time to see votes for this request

**Comment by AlenaSviridenko** [comment]
Hi!
given the tool popularity, we wouldn't like to add it to the images. Please, keep installing it in runtime using action. Actions are the recommended way to interact with the images.
I am closing this issue. Please, feel free to contact us for any questions.

**Comment by vintagepc** [comment]
Can this be reconsidered? I have an action that compiles on Cywin and currently I have to spend 20+ minutes of every single run waiting for it to install cygwin and its dependencies. And that is even more painful considering this eats into my minutes at double the rate of a Linux install.

**Comment by miketimofeev** [comment]
@vintagepc have you tried https://github.com/cygwin/cygwin-install-action action? It takes 1.5 min for me to install cygwin in runtime or most of the time is spent downloading the dependencies?

**Comment by vintagepc** [comment]
Most of the time is installing the required build packages/mingw toolchain, yes.

**Comment by vintagepc** [comment]
Update: seems like fontconfig is the major instigator here. That is what has been running for 15 minutes (and still going) in the run I'm currently watching... 
`running: C:\tools\cygwin\bin\bash.exe --norc --noprofile "/etc/postinstall/zp_mingw64-x86_64-fontconfig_cache.sh"`
