### ISSUE TITLE
Intermittent curl SSL error on ubuntu-18.04

### ISSUE THREAD

**Issue by rsese** [actions/virtual-environments#2810]
**Description**  

Opening an issue on behalf of a user that wrote in to support -- their workflow that uses curl to download fedora RPM packages fails occasionally with this error:

```
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
Error: Process completed with exit code 123.
```

I asked if the problem was recent and they mentioned that it was and it started around Wed, 24 Feb 2021 16:19:24 GMT without changes to their workflow.

**Area for Triage**:  

**Question, Bug, or Feature?**:  

Bug

**Virtual environments affected**  
- [ ] Ubuntu 16.04
- [x] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Image version**

20210219.1

**Expected behavior**  

No error when using curl to download these RPM packages.

**Actual behavior**  

The error mention aboved most of the time but not all the time (also re-running a failed run will also sometimes succeed).

**Repro steps**  

Created a reproduction here:

https://github.com/rsese/curl-test

Looking at the runs:

https://github.com/rsese/curl-test/actions

The first four all failed with the same error, e.g in the 4th run:

https://github.com/rsese/curl-test/actions/runs/612785760

We see the SSL error at https://github.com/rsese/curl-test/runs/2010027866?check_suite_focus=true

But then the 5th run completed successfully:

https://github.com/rsese/curl-test/actions/runs/612790876

Could it also maybe an issue on the Fedora side?

**Comment by al-cheb** [comment]
Hello, @rsese 
I can reproduce error from my local machine. 

```
PS /tmp> curl https://mirror.vcu.edu/pub/gnu+linux/epel/8/Everything/x86_64/Packages/o/openvpn-2.4.10-1.el8.x86_64.rpm
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```
Issue:
```
ERROR: cannot verify mirror.vcu.edu's certificate, issued by ‘CN=InCommon RSA Server CA,OU=InCommon,O=Internet2,L=Ann Arbor,ST=MI,C=US’:
  Unable to locally verify the issuer's authority.
```

Looks like the `https://mirror.vcu.edu` mirror is configured incorrect. 

Workaround:

```
-k, --insecure

(TLS) By default, every SSL connection curl makes is verified to be secure. This option allows curl to proceed and operate even for server connections otherwise considered insecure.

The server connection is verified by making sure the server's certificate contains the right name and verifies successfully using the cert store.

See this online resource for further details:  https://curl.se/docs/sslcerts.html

See also --proxy-insecure and --cacert.

```

Example:
` run: xargs -n 1 curl -skSLO < urls.txt`

**Comment by rsese** [comment]
ahh thanks for the notes @al-cheb :bow:, so seems like not an Actions issue and intermittent because of the mirror chosen changes?  I also went ahead and mentioned your comment + workaround to the user.

**Comment by al-cheb** [comment]
Looks like the certificate is fixed for the mirror `https://mirror.vcu.edu`:

```
 Server certificate:
*  subject: C=US; postalCode=23284; ST=Virginia; L=Richmond; street=910 W Franklin St; O=Virginia Commonwealth University; CN=mirror.vcu.edu
*  start date: Feb 23 00:00:00 2021 GMT
*  expire date: Mar 26 23:59:59 2022 GMT
*  subjectAltName: host "mirror.vcu.edu" matched cert's "mirror.vcu.edu"
*  issuer: C=US; ST=MI; L=Ann Arbor; O=Internet2; OU=InCommon; CN=InCommon RSA Server CA
*  SSL certificate verify ok.
```

Close as external issue,
