### ISSUE TITLE
Waiting for pending jobs all the time

### ISSUE THREAD

**Issue by leleliu008** [actions/virtual-environments#2811]
**Description**  
![image](https://user-images.githubusercontent.com/3040852/109600340-ecca8a80-7b57-11eb-87d7-087b54e8c68a.png)

**Virtual environments affected**  
**All**

workflow can not cancel.
this problem can not reproduce.

https://github.com/leleliu008/ndk-pkg-formula/actions/runs/610092403

**Comment by maxim-lobanov** [comment]
Hello @leleliu008 ,
We had an incident with build scheduling recently, most likely it is root cause: https://www.githubstatus.com/incidents/xn0sd2x4nd7f

I guess we have some build queue as an incident afterwards. Let's wait a bit to see if the situation is stabilized.

**Comment by ffisc** [comment]
@maxim-lobanov @al-cheb I'm having the same issue and it seems there isn't or hasn't been a recent incident, so I'm not sure that's the root cause.

![image](https://github.com/actions/runner-images/assets/29397125/95e2561e-c2fb-4517-8c3e-1da24a766f9a)
