### ISSUE TITLE
The ubuntu-18.04 environment is not suitable for building packages intended for deployment to other 18.04 systems

### ISSUE THREAD

**Issue by sree314** [actions/virtual-environments#2816]
**Description**  
If a package is built on the ubuntu-18.04 virtual environment (using `runs-on: ubuntu-18.04`), the resulting `.deb` file may not run on actual ubuntu 18.04 systems because of spurious dependencies. For example, a dependency on `libgcc-s1` can be introduced because the virtual environment contains newer versions of gcc than those present in upstream Ubuntu 18.04.

Thus, it seems the ubuntu-18.04 environment is suitable for _running_ stuff, but not for _building_ stuff intended for deployment to other 18.04 systems.

The right way to build packages is probably to use a container from Canonical.

**Area for Triage**:  

This is probably a documentation issue.

**Question, Bug, or Feature?**:  

Bug

**Virtual environments affected**  
- [ ] Ubuntu 16.04
- [X] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Image version**

ubuntu-18.04

**Expected behavior**  
A build in 18.04 can be deployed to other 18.04 machines.

**Actual behavior**  
The resulting .deb package refuses to install on actual 18.04 systems.

**Repro steps**  
See https://github.com/diffblue/cbmc/pull/5875

**Comment by al-cheb** [comment]
Hello, @sree314 
Agree, this point should be updated in the official docs. Please create an issue - https://github.com/github/docs.
