### ISSUE TITLE
Add clang 11 on ubuntu 20.04

### ISSUE THREAD

**Issue by dmitryikh** [actions/virtual-environments#2819]
In continue to ##2130 Seems like clang11  is available to be installed ubuntu 20.04.

It works in my workflow:
```
sudo apt-get install clang-11 libc++-11-dev libc++abi-11-dev
```

**Virtual environments affected**
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [x] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Comment by al-cheb** [comment]
Hello, @dmitryikh 
Would you like to prepare a PR to add clang-11 (https://github.com/actions/virtual-environments/blob/main/images/linux/toolsets/toolset-2004.json)?

**Comment by dmitryikh** [comment]
Hi @al-cheb , I will try!

**Comment by andersfylling** [comment]
Nice work! Is there a planned release date for this feature?

**Comment by maxim-lobanov** [comment]
New image should be deployed next week

**Comment by rurban** [comment]
This went wrong with the image update 3 days ago.
clang++ is still 10, but when using libc++, it needs the matching libstdc++, which is 11. 
Hence all libc++ projects fail with something Like "could not find <algorithm>"
This worked ok before.

**Comment by miketimofeev** [comment]
@rurban thanks for reporting this! We'll take a look

**Comment by vsafonkin** [comment]
Hi @rurban, could you please see this comment: https://github.com/actions/virtual-environments/issues/2995#issuecomment-804124705

**Comment by vsafonkin** [comment]
> libc++ needs a matching g++ libstdc++ version, which is currently 9.
> So the docs need to add the two possibilities to fix libc++ projects:
> 
> Either upgrade g++ to 10 (recommended, as gcc-9 is horribly broken, 10 looks much better)

@rurban, what do you mean?  As I see, if the any g++ versions are removed, clang 10 works anyway with installed `libc++abi-dev` and `libc++-dev`:
https://github.com/vsafonkin/test-repo/runs/2174222670?check_suite_focus=true

Looks like `-stdlib=libc++` option requires corresponding packages for each clang version.

**Comment by rurban** [comment]
Yes, purging also works ok.

**Comment by miketimofeev** [comment]
@rurban we have removed the packages that caused the issue, everything should work fine now, thanks!

**Comment by Remi-Coulom** [comment]
The default clang-tidy is still clang-tidy-10, which causes problems. cmake will use new options of clang-11, such as `-fpch-instantiate-templates` that clang-tidy-10 does not understand, causing a compilation error.
