### ISSUE TITLE
Please document the list of used ports for each image

### ISSUE THREAD

**Issue by jsoref** [actions/virtual-environments#2820]
**Description**  

https://github.community/t/is-there-a-list-of-used-ports/17016/3

> I am currently experimenting with GitHub Actions, and although my first impression is pretty good, a question came up: In my tests I am building a number of Docker containers (this is actually part of the test), and after that I start them using docker run.
> Basically, this works (at least on Ubuntu), but some of the ports I would like to use are already being used.
> So, my question is: Is there a list of already used ports available somewhere?

**Area for Triage**:  

**Question, Bug, or Feature?**:  
Question

**Virtual environments affected**  
- [x] Ubuntu 16.04
- [x] Ubuntu 18.04
- [x] Ubuntu 20.04
- [x] macOS 10.15
- [x] macOS 11.0
- [x] Windows Server 2016 R2
- [x] Windows Server 2019

**Image version**

Current for all

**Expected behavior**  
Each of:
* https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-README.md
* https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu1804-README.md
* https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu1604-README.md
* https://github.com/actions/virtual-environments/blob/main/images/win/Windows2019-Readme.md
* https://github.com/actions/virtual-environments/blob/main/images/win/Windows2016-Readme.md
* https://github.com/actions/virtual-environments/blob/main/images/macos/macos-11.0-Readme.md
* https://github.com/actions/virtual-environments/blob/main/images/macos/macos-10.15-Readme.md
* (older images if still available)
* (newer images when announced/released)

Should have a section akin to:
### Web Servers
| Name  | Version  | ConfigFile                      | ServiceStatus | ListenPort |
| ----- | -------- | ------------------------------- | ------------- | ---------- |
| httpd | 2.4.46_2 | /usr/local/etc/httpd/httpd.conf | stopped       | 80         |
| nginx | 1.19.7   | /usr/local/etc/nginx/nginx.conf | stopped       | 80         |

With at least enough information for people to be able to stop any services that are using ports.

**Actual behavior**  
While the two http servers are listed, that `mono` (?) is listening on `8084` isn't documented for Ubuntu-20 (?) and people have to spend time debugging instead of reading the docs.

**Repro steps**  
A description with steps to reproduce the issue. If your have a public example or repo to share,
please provide the link.

1. run a github action workflow (in docker, not in docker) that tries to listen to a port (e.g. :8084)
2. get an error that the port is in use

Fwiw, here's the argoproj/argo-cd [run](https://github.com/argoproj/argo-cd/actions/runs/615273805), [failure](https://github.com/argoproj/argo-cd/runs/2016460526?check_suite_focus=true), argoproj/argo-cd#5658 to workaround, and [workaround](https://github.com/argoproj/argo-cd/blob/53fabec8455ccfbe9482c0a122fb091f2c38e25d/.github/workflows/ci-build.yaml#L359-L361)

**Comment by jsoref** [comment]
Oh, notably, on `ubuntu-20.04`, the `Web Servers` table should list `mono-xsp4`, since apparently, it's a web server! (Even if the rest of this request isn't addressed.)
>       If  run  as `xsp4', the process provides a minimalistic web server which hosts the ASP.NET

**Comment by maxim-lobanov** [comment]
Hello @jsoref , thank you for your proposal and shared information.
We will prepare PR to add Mono in WebServers section. It definitely makes sense.

But in general, we wouldn't like to list used ports in documentation due to maintenance concerns.
The list of used ports can be easily retrieved via `sudo netstat -lpn` command in runtime.
If you need to free specific port, you don't need to know what service uses it and how it can be stopped, you can use the following universal command to free port: `sudo kill -9 $(sudo lsof -t -i:8084)`

**Comment by ForsakenHarmony** [comment]
I'm sorry, but I don't understand why you'd have any web servers running by default.
If someone needs to start a server for their testing that should probably be explicit.

`xsp4` suddenly being added broke one of our workflows, and it took a while to figure out why port 8084 was suddenly in use.

Shutting down the service doesn't really seem like a future proof solution.

Yes it may add a bit of maintenance burden, but you should list used ports somewhere and also probably check if you add a new service with an update which uses a port that wasn't used before.

**Comment by miketimofeev** [comment]
As @maxim-lobanov mentioned we've decided to add Mono web server to the documentation since it might be confusing to have a busy 8084 port. The docs will be updated in two weeks.
For a complete list of used ports, please run the following snippets:
**Ubuntu**:
`sudo netstat -lpn`
**macOS**:
`sudo lsof -PiTCP -sTCP:LISTEN`
**Windows**:
`Get-NetTCPConnection -State Listen -RemoteAddress "0.0.0.0"`

**Comment by jsoref** [comment]
@miketimofeev: it feels like you might as well include the above content in each read me:

> Instances of this VM may be running services using additional ports (and this may change with image updates). For a complete list of used ports, please run the following snippet:

(Depending on which platform read me, insert appropriate snippet.)

**Comment by ForsakenHarmony** [comment]
Again, can someone explain why webservers run by default and not when they're needed?

**Comment by jsoref** [comment]
@ForsakenHarmony: the short answer is that GitHub is just using Ubuntu base images. The ubuntu base image policy includes defaulting to enabling services by default (roughly so that when one installs a package it works out of the box, no extra steps required) -- other distributions (RHEL?) take other stances (requiring one to manually enable/start). GitHub doesn't want to micromanage packages (they could set a base policy to default to services off, it's possible, but it's work, and it would diverge their Ubuntu instances from upstream).

I'm not defending any of this. I'd personally prefer for this thing not to be running by default, but that's clearly a bridge too far, so this issue is my request for them to at least document things which I feel is not a bridge too far.

If you want to fight for getting the service not running, I'd rather you use your own issue. (I'm not opposed, but I don't want to be forced to be subscribed to it.)

**Comment by ForsakenHarmony** [comment]
@jsoref ah yes that makes sense, they'd probably not want to deal with that, still meh, but ubuntu is ubuntu

Didn't mean to hijack this issue in any way, just seemed like relevant information, don't think I have the motivation to try and convince microsoft to change the way they do things

**Comment by AlenaSviridenko** [comment]
Hi,
@jsoref' description is quite accurate, we pre-install packages in the standard way, without additional management unless it is something critical. 
As for the documentation update, we believe it should remain unchanged. We document things that can behave in a non-standard way, or when behavior is different between different OS versions (like the situation with Mono service). If something works the same way on the local station and on our images — we consider it the default behavior that shouldn't be documented.
As for the documenting the way to define used ports and how to release them — this is more about Ubuntu managing, which is a bit out of our image README scope

I am closing this issue. Please, let us know if you have any concerns, and feel free to create a new ticket if any other help needed.
Thanks.

**Comment by jsoref** [comment]
@AlenaSviridenko: I was suggesting you could offer information about how to find port consumers on macOS and Windows as well since @miketimofeev provided commands for all three. Your users aren't going to be experts in all platforms, they could easily be Windows users who are using GitHub to cross build for macOS and Linux (or Linux users cross building for macOS and Windows).

That said. I'll take whatever improvements I can get, as well as link rank to this issue since the issue alone is a form of documentation (certainly better than the forums).

**Comment by banool** [comment]
I find that even if I kill things running on ports I need, they come back. It'd be nice to be able to say in a job that certain ports are needed for the workflow and the runner won't use them.

**Comment by jsoref** [comment]
@banool: you're going to have to stop the services that are trying to use the things, otherwise they're going to be resurrected...
