### ISSUE TITLE
Mono is running on ubuntu-20.04 on port 8084

### ISSUE THREAD

**Issue by jsoref** [actions/virtual-environments#2821]
**Description**  
On ubuntu-18.04, port 8084 is available for use. https://github.com/argoproj/argo-cd/ uses this port.
On ubuntu-20.04, port 8084 is not available by default.

Apparently it's occasionally found, e.g. in https://askubuntu.com/questions/829353/what-is-this-mono-process-running-at-startup Lubuntu 14.04

That this service is running and isn't documented (see #2820) makes it harder to do things..

**Area for Triage**:  

Area: .NET Framework
Area: Servers

**Question, Bug, or Feature?**:  
Bug

**Virtual environments affected**  
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [x] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Image version**
  Version: 20210219.1

**Expected behavior**  
mono shouldn't be running on 8084 or it should be clearly documented (with a hint about how to stop it)

**Actual behavior**  
mono is running on 8084 and there's no hint about what it is/how to stop it.

**Repro steps**  

1. Visit https://github.com/jsoref/gha-debug/runs/2017914841?check_suite_focus=true
2. See that port 8084 is in use under `List ports` for `ubuntu-20.04` but not for `ubuntu-18.04

**Comment by al-cheb** [comment]
Hello, @jsoref 
You can disable  `mono-xsp4` service in runtime:
```
- name: disable and stop mono-xsp4.service
  run: |
       sudo systemctl stop mono-xsp4.service 
       sudo systemctl disable mono-xsp4.service
```
I am planning to close the thread and continue discussion in #2820.

**Comment by jsoref** [comment]
Thanks. This was a "filed on behalf of".

But note that your suggestion will break the build the next time the system jitters between having/not having it (especially while `ubuntu-latest` is jittering between `ubuntu-20.04` and `ubuntu-18.04`).

So one should probably do something closer to:

```
- name: disable and stop mono-xsp4.service
  run: |
       sudo systemctl stop mono-xsp4.service || true
       sudo systemctl disable mono-xsp4.service || true
```
