### ISSUE TITLE
Update/Add buildifier

### ISSUE THREAD

**Issue by chandlerc** [actions/virtual-environments#2822]
**Tool information**
- Tool name: buildifier
- Tool license:  Apache-2.0 License
- Add or update? Add
- Desired version: Whatever is latest
- Approximate size: 7.1mb
- If this is an add request:
  - Brief description of tool: "buildifier is a tool for formatting bazel BUILD and .bzl files with a standard convention."
  - URL for tool's homepage: https://github.com/bazelbuild/buildtools/blob/master/buildifier/README.md
  - Provide a basic test case to validate the tool's functionality:

```
$(go env GOPATH)/bin/buildifier --version
```

**Area for Triage**:

**Question, Bug, or Feature?**:

**Virtual environments affected**
- [x] Ubuntu 16.04
- [x] Ubuntu 18.04
- [x] Ubuntu 20.04
- [x] macOS 10.15
- [x] macOS 11.0
- [x] Windows Server 2016 R2
- [x] Windows Server 2019

**Can this tool be installed during the build?**
Yes:
```
go get github.com/bazelbuild/buildtools/buildifier
```

**Tool installation time in runtime**
Very fast -- should be the same as `bazelisk` with similar utility.

**Are you willing to submit a PR?**
Not at this time.

**Comment by maxim-lobanov** [comment]
Thank you for your proposal @chandlerc ,
Considering pretty quick and simple installation in runtime, we wouldn't like to pre-install this tool into the images.
We are trying to avoid pre-installing small tools to avoid maintenance concerns.
