### ISSUE TITLE
Add Python 3.9.2

### ISSUE THREAD

**Issue by kumaraditya303** [actions/virtual-environments#2825]
**Tool information**
- Tool name:  Python
- Tool license:  PSF
- Add or update?  Add
- Desired version:  3.9.2
- Approximate size: 
- If this is an add request:
  - Brief description of tool: 
  - URL for tool's homepage: 
  - Provide a basic test case to validate the tool's functionality: 

**Area for Triage**:

**Question, Bug, or Feature?**:

**Virtual environments affected**
- [x] Ubuntu 16.04
- [x] Ubuntu 18.04
- [x] Ubuntu 20.04
- [x] macOS 10.15
- [x] macOS 11.0
- [x] Windows Server 2016 R2
- [x] Windows Server 2019

**Can this tool be installed during the build?**

**Tool installation time in runtime**

**Are you willing to submit a PR?**

**Comment by al-cheb** [comment]
Hello, @kumaraditya303 
We are planning to deploy new images with Python 3.9.2 in a week or two.

**Comment by maxim-lobanov** [comment]
Python 3.9.2 is already available for GitHub Actions via https://github.com/actions/setup-python

**Comment by kumaraditya303** [comment]
https://github.com/microsoft/playwright-python/pull/543/checks?check_run_id=2020011803 See still Python 3.9.1 is used @maxim-lobanov

**Comment by maxim-lobanov** [comment]
Try to specify exact version `3.9.2`.
At first, the task tries to resolve version locally, it finds 3.9.1 that satisfies `3.9.x` input and use it.
If you specify `3.9.2`, it won't find it locally and will install in runtime (pretty quick).

As Aleks mentioned, 3.9.2 will be added to images very soon and after that task will resolve 3.9 correctly

**Comment by maxim-lobanov** [comment]
Python 3.9.2 was added to all images recently. Closing the issue
