### ISSUE TITLE
Add libvips

### ISSUE THREAD

**Issue by masa-iwasaki** [actions/virtual-environments#2829]
**Tool information**
- Tool name:  libvips
- Tool license: LGPL 2.1+
- Add or update?  Add
- Desired version: 8.9.1
- Approximate size:  Installed size 143.00 KB (according to https://ubuntu.pkgs.org/20.04/ubuntu-universe-amd64/libvips-tools_8.9.1-2_amd64.deb.html)
- If this is an add request:
  - Brief description of tool: libvips is a demand-driven, horizontally threaded image processing library.
  - URL for tool's homepage: https://libvips.github.io/libvips/

**Virtual environments affected**
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [x] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Can this tool be installed during the build?**

```bash
sudo apt-get install libvips-dev 
```

**Tool installation time in runtime**

Finished in 29 seconds 

https://github.com/masa-iwasaki/github_actions_playground/runs/2022292006?check_suite_focus=true

**Are you willing to submit a PR?**

Yes

**Comment by AlenaSviridenko** [comment]
Hi @masa-iwasaki,
we'd rather not to install this package on the image due to its popularity (it seems to be a pretty specific tool) and its pretty fast installation time in runtime.
I am closing this issue. Please, feel free to contact us in case of any other questions. Thank you.

**Comment by nvick** [comment]
Now that `vips` is the default image processor on Rails 7, would you all reconsider adding `libvips` to default packages installed? We see wildly different install times during Action build ~ 30 secs - 2 mins.

**Comment by al-cheb** [comment]
> Now that `vips` is the default image processor on Rails 7, would you all reconsider adding `libvips` to default packages installed? We see wildly different install times during Action build ~ 30 secs - 2 mins.

We will check that if  installation time is more than 2 minutes we add libips library on images.

**Comment by arg** [comment]
Are there any updates?

**Comment by thisismydesign** [comment]
You can use https://github.com/awalsh128/cache-apt-pkgs-action

**Comment by yordis** [comment]
@thisismydesign from the readme

> Important
> Looking for co-maintainers to help review changes, and investigate issues. I haven't had as much time to stay on top of this action as I would like to and want to make sure it is still responsive and reliable for the community. If you are interested, please reach out.

😭
