### ISSUE TITLE
Fix php extensions 

### ISSUE THREAD

**Issue by shivammathur** [actions/virtual-environments#2830]
**Description**  
Recently dependency structure of PHP extensions has changed.
Installing `php-memcached` package for example, only installs `memcached` extension for the default version PHP 8.0.

More details here: https://www.patreon.com/posts/47793617

So extensions in `php.sh` which were installed using unversioned packages should be installed using their versioned packages.

Except php-pear all these should be moved to the [above for loop](https://github.com/actions/virtual-environments/blob/main/images/linux/scripts/installers/php.sh#L19) and versioned.
https://github.com/actions/virtual-environments/blob/ff72158a2a30de91c925a392694e8195c1ae994f/images/linux/scripts/installers/php.sh#L69-L80

**Area for Triage**:  
Packages, PHP

**Question, Bug, or Feature?**:  
Bug

**Virtual environments affected**  
- [X] Ubuntu 16.04
- [X] Ubuntu 18.04
- [X] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Image version**: 20210302.0

**Expected behavior**  
PHP extensions like `memcached` and `redis` are installed correctly for all PHP versions.

**Actual behavior**  
PHP Extensions installed using unversioned packages are only being installed for the default version PHP 8.0

**Repro steps**  
- Install PHP 7.4 and 8.0 on ubuntu using `ppa:ondrej`.
- Install `php-memcached`.
- Memcached extension is only installed for PHP 8.0.

**Comment by AlenaSviridenko** [comment]
Hi @shivammathur, we merged your PR, changes will be released with the next image deployment.
We will keep you posted. Thanks.

**Comment by shivammathur** [comment]
Thanks for the update @AlenaSviridenko

**Comment by miketimofeev** [comment]
@shivammathur changes were deployed. Thank you for your contribution!
