### ISSUE TITLE
Prblem with ubuntu18.04 to ubuntu20.04 transition

### ISSUE THREAD

**Issue by litman90** [actions/virtual-environments#2831]
**Description**  
When our workflow transitionated from ubuntu18.04 to ubuntu20.04 our regression tests started to fail.
We could not identify the specific source of the error. Our code (https://github.com/i-pi/i-pi) runs atomistic simulations and it contains python3 and Fortran language.

**Virtual environments affected**  
- [x ] Ubuntu 20.04

**Repro steps**  
Example of a successful set of tests in ubuntu18.04 (https://github.com/i-pi/i-pi/actions/runs/617770427)
Example of a set of tests with failures in Ubuntu 20.04: https://github.com/i-pi/i-pi/actions/runs/617668833

**Comment by al-cheb** [comment]
Hello, @litman90 
I think you can switch back to ubuntu 18.04 in the pipeline.
`os: ["ubuntu-latest"]` -> `os: ["ubuntu-18.04"]`

**Comment by litman90** [comment]
Thank you @al-cheb 
We did that indeed and for now, it solves the problem.
However at some point, ubuntu-18.04 will become deprecated, so we have to think ahead.

**Comment by miketimofeev** [comment]
@litman90 we don't have a plan to drop Ubuntu-18.04 support shortly
