### ISSUE TITLE
net-tools, specifically netstat is missing from Ubuntu 20.04 image

### ISSUE THREAD

**Issue by mconnew** [actions/virtual-environments#2837]
**Description**  
Ubuntu-18.04 had the net-tools package installed. Ubuntu-20.04 does not. This is a regression in command line tools available. I'm specifically needing the netstat command for a unit test to validate that a fresh connection isn't created under certain conditions.

**Area for Triage**:  

**Question, Bug, or Feature?**:  Bug

**Virtual environments affected**  
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [x] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Image version**
20210302.0

**Expected behavior**  
netstat to be available to execute on the path

**Actual behavior**  
netstat is missing

**Repro steps**  
The tests for https://github.com/CoreWCF/CoreWCF execute the process "netstat -a -n" which provides a compatible parse-able output for Windows and Linux. It is expected that the netstat executable is available on the path. Note, the path of netstat has changed between Ubuntu 20.04 (/usr/bin/netstat) and Ubunutu 18.04 (/bin/netstat).

**Comment by maxim-lobanov** [comment]
Hello @mconnew , thank you for your proposal!
Yes, the list of tool is different on Ubuntu 20.04. As for this particular tool, we don't have concerns to pre-install it on Ubuntu 20.04. Moved to backlog

**Comment by al-cheb** [comment]
Hello, @mconnew 
The https://github.com/actions/virtual-environments/pull/2838 PR is merge. Awaiting for new image deployment in a week or two.

**Comment by mconnew** [comment]
I presume this issue will be closed once it's deployed?

**Comment by al-cheb** [comment]
> I presume this issue will be closed once it's deployed?

Yep, that's right.

**Comment by al-cheb** [comment]
Hello, @mconnew 
The new images with net-tools package have been deployed.
