### ISSUE TITLE
some runner auto canceled

### ISSUE THREAD

**Issue by leleliu008** [actions/virtual-environments#2839]
![image](https://user-images.githubusercontent.com/3040852/109923253-736a9d80-7cf9-11eb-8441-7dbb1d2ce045.png)

https://github.com/leleliu008/ndk-pkg-formula/actions/runs/620016463

It seems that GItHub Actions service is not stable recently.

**Comment by Darleev** [comment]
Hello @leleliu008,
Sometimes our automated systems flag accounts that need further manual review which can cause some issues during the GitHub actions build. Currently, the issue should not appear anymore.
In case of any questions regarding the issue, feel free to contact [github support](https://support.github.com).
