### ISSUE TITLE
MacOS resource error - ENFILE: file table overflow

### ISSUE THREAD

**Issue by mathisonian** [actions/virtual-environments#2842]
**Description**  
I am using GitHub Actions to build a release of an electron app each time a new tag is committed. For the most part it works great, so thank you for that. 

I run this job on `windows-latest`, `linux-latest` and `macos-latest`. All three were working fine until recently a new dependency was added to the project, which seems to have pushed the resource usage over the edge for macos builds. 

Now every time the MacOS build tries to run its code signing step, I get the following error:

```
We need to package your application before we can make it
✔ Preparing to Package Application for arch: x64
- Preparing native dependencies
✔ Preparing native dependencies
- Packaging Application
WARNING: Code sign failed; please retry manually. Error: ENFILE: file table overflow, open '/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/electron-packager/darwin-x64/idyll-studio-darwin-x64/idyll-studio.app/Contents/Resources/app/node_modules/victory-core/es/victory-util/transitions.js'

An unhandled rejection has occurred inside Forge:
Error: Apple failed to notarize your application, check the logs for more info

Status Code: 2
Message: Package Invalid
Logs: https://osxapps-ssl.itunes.apple.com/itunes-assets/Enigma124/v4/8e/de/62/8ede62e4-7e74-26e8-8cce-b090b8f124c7/developer_log.json?accessKey=1615016354_1885946357011491732_rV4Nmj7XbEQyZveubLk2KwU1gN47FJV%2F%2B8Q%2BvoFk5JEaxXAqP7h5zf5L%2BmRG513SVzjG1iwGmG8sfb8dJA13OEZtSFwX1hZ1D907Jafa4ED7%2FDKnxRjUJ67PaMy%2FYTN3r1bYkztsQ3GR5p0e03Kt2YkQrPCg%2Fy%2F95OdHpYV9XF0%3D
    at /Users/runner/work/idyll-studio/idyll-studio/node_modules/@electron-forge/core/node_modules/electron-notarize/lib/index.js:114:19
    at Generator.next (<anonymous>)
    at fulfilled (/Users/runner/work/idyll-studio/idyll-studio/node_modules/@electron-forge/core/node_modules/electron-notarize/lib/index.js:4:58)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

Electron Forge was terminated. Location:
{}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! idyll-studio@0.8.41 make: `electron-forge make`
npm ERR! Exit status 1
```

To alleviate it, I have attempted to increase resource availability with the following brute force commands (they don't have any effect):

```
          echo kern.maxfiles=4194304 | sudo tee -a /etc/sysctl.conf
          echo kern.maxfilesperproc=4194304 | sudo tee -a /etc/sysctl.conf
          echo fs.inotify.max_user_watches=4194304 | sudo tee -a /etc/sysctl.conf
          sudo sysctl -w kern.maxfiles=4194304
          sudo sysctl -w kern.maxfilesperproc=4194304
          ulimit -n 524288 unlimited
          sudo launchctl limit maxfiles 4194304 unlimited
```

See https://github.com/idyll-lang/idyll-studio/runs/2027215725?check_suite_focus=true for the full build

**Area for Triage**:  
Servers, Deployments

**Question, Bug, or Feature?**:  
Question or Bug

**Virtual environments affected**  
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [x] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Image version**

Image version where you are experiencing the issue.

**Expected behavior**  
The error doesn't occur, or goes away after `ulimit` is increased. 

**Actual behavior**  
```
WARNING: Code sign failed; please retry manually. Error: ENFILE: file table overflow, open '/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/electron-packager/darwin-x64/idyll-studio-darwin-x64/idyll-studio.app/Contents/Resources/app/node_modules/victory-core/es/victory-util/transitions.js'
```

**Repro steps**  
A description with steps to reproduce the issue. If your have a public example or repo to share,
please provide the link.

See this job run: https://github.com/idyll-lang/idyll-studio/runs/2027215725?check_suite_focus=true

I have currently disabled the macos code signing but this isn't a long term solution. To add the code signing back for reproduction purposes, [uncomment these lines](https://github.com/idyll-lang/idyll-studio/blob/master/forge.config.js#L4-L14).

**Comment by mathisonian** [comment]
Please let me know if there is anything else I can do on my end to help resolve @al-cheb. This is a blocker for us

**Comment by al-cheb** [comment]
Hello, @mathisonian 
Have you tried these https://docs.reactioncommerce.com/docs/requirements limits?

```
echo kern.maxfiles=65536 | sudo tee -a /etc/sysctl.conf
echo kern.maxfilesperproc=65536 | sudo tee -a /etc/sysctl.conf
sudo sysctl -w kern.maxfiles=65536
sudo sysctl -w kern.maxfilesperproc=65536
ulimit -n 65536 65536
echo "ulimit -n 65536 65536" >> .bashrc
source .bashrc
```

**Comment by mathisonian** [comment]
Ahh - thanks @al-cheb!

It seems like the last two lines may have been the crucial thing missing from other suggestions i had found 

```
echo "ulimit -n 65536 65536" >> .bashrc
source .bashrc
 ```

Using the entire block it as you have it above seems to have fixed the problem.
