### ISSUE TITLE
Update to Azure CLI 2.20.0+

### ISSUE THREAD

**Issue by LordHMX** [actions/virtual-environments#2846]
**Tool information**
- Tool name: Azure CLI
- Add or update? Update
- Desired version: 2.20.0

**Area for Triage**:

**Question, Bug, or Feature?**: "Bug"

**Virtual environments affected**
- [x] Ubuntu 16.04
- [x] Ubuntu 18.04
- [x] Ubuntu 20.04
- [x] macOS 10.15
- [x] macOS 11.0
- [x] Windows Server 2016 R2
- [x] Windows Server 2019

According to this issue ([Link](https://github.com/Azure/azure-cli/issues/16908)), there is a breaking bug with the 'az storage blob sync' command which fails all pipelines that uses them with Azure CLI 2.19.1. The issue was apparently resolved in Azure CLI 2.20.0 ([Link](https://github.com/Azure/azure-cli/issues/17031)). The agent need to be updated to that version at least.

**Comment by maxim-lobanov** [comment]
Hello @LordHMX , we are deploying the new set of images with Azure CLI 2.20.0 right now.
Deployment of Ubuntu and macOS should be finished today.
Windows deployment should be finished by mid of next week

**Comment by miketimofeev** [comment]
@LordHMX we have updated all the images with Azure CLI 2.20. I'm going to close the issue but please feel free to contact us if you have any concerns.
Thank you!
