### ISSUE TITLE
Add AutoIt

### ISSUE THREAD

**Issue by micwoj92** [actions/virtual-environments#2849]
**Tool information**
- Tool name: AutoIt Scripting Language, AutoIt 3
- Tool license: Custom https://www.autoitscript.com/autoit3/docs/license.htm
- Add or update? Add
- Desired version:Latest stable  v3.3.14.5 and latest beta v3.3.15.3
- Approximate size: About 30-40MB
- If this is an add request:
  - Brief description of tool: AutoIt v3 is a freeware BASIC-like scripting language designed for automating the Windows GUI and general scripting.
  - URL for tool's homepage: https://www.autoitscript.com/site/
  - Provide a basic test case to validate the tool's functionality: 
Hello world in autoit
```
 #include <MsgBoxConstants.au3>

MsgBox($MB_OK, "Tutorial", "Hello World!") 
```

**Area for Triage**:
'Scripting and command line' 

**Question, Bug, or Feature?**:
"Feature"

**Virtual environments affected**
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11.0
- [x] Windows Server 2016 R2
- [x] Windows Server 2019

**Can this tool be installed during the build?**
I don't know if I understand this question, I guess?

**Tool installation time in runtime**
About 10 to 20 seconds.

**Are you willing to submit a PR?**
Not sure. I haven't looked at other pr's yet so I have no idea what to add. But I will help.

**Comment by al-cheb** [comment]
Hello, @micwoj92 
You can install autoit in runtime:
`- run: choco install autoit`

**Comment by micwoj92** [comment]
Oh, I wasn't aware it was in chocolatey. I don't think that it's needed then. My current installation method was to download installer and execute it. I guess this will be simpler. Does the chocolatey install the same way as regular installer?

**Comment by micwoj92** [comment]
I am now reading about issue https://github.com/actions/virtual-environments/issues/2693 , so what are the plans now?

**Comment by al-cheb** [comment]
> Oh, I wasn't aware it was in chocolatey. I don't think that it's needed then. My current installation method was to download installer and execute it. I guess this will be simpler. Does the chocolatey install the same way as regular installer?

Yep, you can check the src - https://github.com/chocolatey-community/chocolatey-coreteampackages/tree/master/automatic/autoit

**Comment by micwoj92** [comment]
Thanks for answers, I will look into using chocolatey, but now this depends whether community chocolatey repo gets removed or not. 
I think this should wait because of this.

**Comment by maxim-lobanov** [comment]
@micwoj92 , we don't have plans to get rid of chocolatey from images.
This issue is mostly about using or not choco community repository during image-generation. Anyway, choco tool itself will be installed on images and this installation way will continue to work

**Comment by micwoj92** [comment]
@maxim-lobanov So the community repo will be still available? If yes then this issue can be closed. Thanks for quick answers!

**Comment by maxim-lobanov** [comment]
Yes, it is true.
The question - will community repo will be used for pre-installed software or not.
