### ISSUE TITLE
Missing uninstalled Microsoft SDK in release notes win19/20200113.1

### ISSUE THREAD

**Issue by pavel-mikula-sonarsource** [actions/virtual-environments#285]
**Description**
Our build failed on Azure DevOps this week due to unexpected removal of `\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.7.2 Tools\` path from build environment.

Build is using `vmImage: 'windows-latest'`

Issue is easy to fix by updating to latest SDK 4.8.

**Problem**
Problem is, that this update of image is not documented in the release notes.

**Virtual environments affected**
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [x] Windows Server 2019

**Comment by dmitry-shibanov** [comment]
Hello @pavel-mikula-sonarsource thank you for response. We have updated documentation generation logic with new sdk paths.

**Comment by rectified95** [comment]
@pavel-mikula-sonarsource How were you able to pick a specific SDK version in your build in Github Actions?
I'm seeing a failing build that uses headers from the **20348** SDK which is supposed to be available in the windows-2019 image but is somehow not getting pulled in.. (https://github.com/actions/virtual-environments/blob/main/images/win/Windows2019-Readme.md#installed-windows-sdks)

**Comment by pavel-mikula-sonarsource** [comment]
@rectified95 this was not related to GitHub actions. We had a script that explicitly used that path. 

This was the commit to fix it:
https://github.com/SonarSource/sonar-dotnet/pull/3031/files
