### ISSUE TITLE
Xcode tests are failing on mac runners due to lack of resources to load files from disk under 1s

### ISSUE THREAD

**Issue by CyrilCermak** [actions/virtual-environments#2853]
**Description**  
Hi, we are having a problem with failed async tests on GH macOS runners that executes the iOS framework tests. In some cases, it takes more than 1s to load a JSON (mocked HTTP response) file that has eta 200 bytes in size to memory. This results in many failing tests in our frameworks. 

I have also noticed that heavy operational tests where for example an image gets rendered are also taking longer than 1s. All those tests are running perfectly fine on very old Mac minis which we moved away from. 

We are experiencing such issues for a month or so now.

Tests are executed via Fastlane scan
https://docs.fastlane.tools/actions/scan/

**Area for Triage**:  

contains: 'Apple'
contains: 'Xcode'

**Question**:  
The issue can be fixed by setting longer expectations times for the async tests, however, what time is enough then and why is it taking so long to load a file from a disk? 

Thank you very much for any kind of answers.

**Virtual environments affected**  
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [*] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Image version**
Versions affected past 1-2 months or so.

**Expected behavior**  
Loading a file from disk during unit-testing takes nanoseconds 

**Actual behavior**  
Loading a file from disk during unit-testing takes more than a second

**Repro steps**  
I don't have a public repo where I could showcase it.

**Comment by Darleev** [comment]
Hello @CyrilCermak,
Could you please provide some sample repo and steps to reproduce the issue? It would be great to reproduce it somehow to investigate the issue further.
We are looking forward to your reply.

**Comment by CyrilCermak** [comment]
Hello @Darleev, thanks for your answer. I will provide the example ASAP.

**Comment by Darleev** [comment]
Hello @CyrilCermak,
In order to continue the investigation for the case, we are waiting for steps to reproduce the issue or sample repo.
We look forward to hearing from you.

**Comment by CyrilCermak** [comment]
Hey @Darleev, I am sorry it took so long, but I took the time and investigated a bit more so that I could give an explanation as clear as possible. 

Here is the example repository + PR with workflows:
https://github.com/CyrilCermak/-GHEnvTesting/pull/2

Now this repository is on my private free account, however, the issue happens also on our corporate account.

On our repository there are many developers working on simultaneously, we have heaps of PRs and unlimited runners restrictions. I think it can easily happen that there are around 60+ workers running in parallel.  

Nevertheless, what I managed to reproduce in the provided repository is that the compile time of one function differs from 1 minute up to 5 minutes plus the computational tests are failing randomly. This is the same on the corporate account.

The test on my local machine which is 2018 MBP, 2,6GHz takes 2s to complete. Three runners were not able to finish it under 20s. 

Unfortunately, I was not able to reproduce the long load time from the disk drive. That seems to be very random, yet it happens from time to time in a very similar environment. 

What I experienced many times was that test that takes ~10 minutes took 50 minutes to complete. It mostly happens when there are a lot of runners running in parallel.

If I manage to reproduce or figure out more about the load from the disk I would update it here.

Thank you very much for looking into it.

**Comment by Darleev** [comment]
Hello @CyrilCermak,
Could you please add an additional step to the workflow(), in order to determine the hostname for slow/fast jobs:
It can be
`$ hostname`
or 
`echo $HOSTNAME`
and when the next time the issue appears again, please provide hostname and link to the job. 
Meantime, could you please send a couple of links where the issue was actual?

**Comment by CyrilCermak** [comment]
Yes, I can do that. 

I am sorry I let the repo private, it's now public so you should be able to access it. 

By links, do you mean a link to the concrete runner?

Thanks!

**Comment by Darleev** [comment]
Hello @CyrilCermak,
Thank you for the provided repository, it's very useful for the investigation.
I found that some machines are slower than others, and we need to investigate it deeper in collaboration with platform engineers.
I'll keep you informed.

**Comment by Darleev** [comment]
@CyrilCermak In order to investigate the issue further, an engineering team created a task for an internal investigation. I put this task to "Waiting for Response" status until any updates from their side.
In case of any questions, feel free to contact us.

**Comment by CyrilCermak** [comment]
@Darleev, thank you very much for your help! If I find out more useful info I will keep you updated as well. 

Thanks!

**Comment by miketimofeev** [comment]
@CyrilCermak is this still actual for you?

**Comment by CyrilCermak** [comment]
Hi @miketimofeev, it's been quite stable lately so I think it's all good. Thank you.

**Comment by aloviedo** [comment]
Closing per last comment
