### ISSUE TITLE
README needs updating to match the ubuntu-latest tag changes

### ISSUE THREAD

**Issue by arjunmadan** [actions/virtual-environments#2854]
**Description**  
It looks like in the last few days the `ubuntu-latest` tag has started pointing to Ubuntu 20.04, but the README hasn't been updated yet.

**Virtual environments affected**  
- [ ] Ubuntu 16.04
- [x] Ubuntu 18.04
- [x] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Expected behavior**  
The README should have the `ubuntu-latest` pointing to Ubuntu 20.04.

**Actual behavior**  
The README has `ubuntu-latest` pointing to Ubuntu 18.04.

**Comment by maxim-lobanov** [comment]
Hello @arjunmadan , migration `ubuntu-latest` from 18.04 to 20.04 is still in progress and will take a one more week. We will update README file as soon as migration is finished.
Related issue: https://github.com/actions/virtual-environments/issues/1816

**Comment by arjunmadan** [comment]
@maxim-lobanov gotcha. We saw some of our actions runs that were using `ubuntu-latest` start up with 20.04 which is why I opened this issue and the associated PR. If there's another PR that's going to be merged, that's perfectly fine and I can close mine. :)

**Comment by maxim-lobanov** [comment]
I will close this issue in favor of #1816 but let's keep your PR opened. I think we can merge it when migration is complete. cc: @AlenaSviridenko
