### ISSUE TITLE
Test runner runs for 6 hours after version update

### ISSUE THREAD

**Issue by oliv0533** [actions/virtual-environments#2855]
**Description**  
As the title says, the test runner in Github Actions runs forever after you updated the versions for 18.04 and 20.04 to 20210302.0.

We have a testrunner that connects to a series of docker containers for integration testing. Works fine on 20210219.1 and on local machines.

20210219.1:
`2021-03-04T10:08:30.7596666Z Building with native build. Learn about native build in Compose here: https://docs.docker.com/go/compose-native-build/`
`2021-03-04T10:08:30.7619275Z Creating network "src_internal" with driver "bridge"`
`2021-03-04T10:08:30.9693216Z Creating tests-localstack ... `
`2021-03-04T10:08:30.9778675Z Creating tests-mongo-primary ... `
`2021-03-04T10:08:30.9825703Z Creating tests-redis         ...`
`2021-03-04T10:08:31.0078893Z Creating tests-mongo-arbiter ... `
`2021-03-04T10:08:31.0295503Z Creating tests-mongo-secondary ... `
`2021-03-04T10:08:31.0640688Z Creating tests-active-mq       ... `
`2021-03-04T10:08:31.0851333Z Creating tests-elasticsearch   ... `
`2021-03-04T10:08:37.2905119Z Creating tests-mongo-secondary ... done`
`2021-03-04T10:08:37.3584292Z Creating tests-mongo-primary   ... done`
`2021-03-04T10:08:38.3078405Z Creating tests-mongo-arbiter   ... done`
`2021-03-04T10:08:38.3934959Z Creating tests-active-mq       ... done`
`2021-03-04T10:08:38.4477510Z Creating tests-elasticsearch   ... done`
`2021-03-04T10:08:39.0395616Z Creating tests-localstack      ... done`
`2021-03-04T10:08:39.3828272Z Creating tests-redis           ... done`
`2021-03-04T10:08:39.3911569Z Creating tests-redacted       ... `
`2021-03-04T10:08:40.4588508Z Creating tests-redacted       ... done`
`2021-03-04T10:08:40.4720756Z Attaching to tests-mongo-secondary, tests-mongo-primary, tests-mongo-arbiter, tests-active-mq, tests-elasticsearch, tests-localstack, tests-redis, tests-redacted`
`2021-03-04T10:08:40.4722945Z [36mtests-active-mq    |[0m 2021-03-04 10:08:39,028 CRIT Supervisor running as root (no user in config file)`
`2021-03-04T10:08:40.4724461Z [36mtests-active-mq    |[0m 2021-03-04 10:08:39,028 WARN Included extra file "/etc/supervisor/conf.d/activemq.conf" during parsing`
`2021-03-04T10:08:40.4725979Z [36mtests-active-mq    |[0m 2021-03-04 10:08:39,028 WARN Included extra file "/etc/supervisor/conf.d/cron.conf" during parsing`
`2021-03-04T10:08:40.4727375Z [36mtests-active-mq    |[0m 2021-03-04 10:08:39,118 INFO RPC interface 'supervisor' initialized`
`2021-03-04T10:08:40.4728805Z [36mtests-active-mq    |[0m 2021-03-04 10:08:39,131 CRIT Server 'unix_http_server' running without any HTTP authentication checking`
`2021-03-04T10:08:40.4730285Z [36mtests-active-mq    |[0m 2021-03-04 10:08:39,131 INFO supervisord started with pid 1`
`2021-03-04T10:08:40.4731342Z [36mtests-active-mq    |[0m 2021-03-04 10:08:40,133 INFO spawned: 'cron' with pid 16`
`2021-03-04T10:08:40.4732427Z [36mtests-active-mq    |[0m 2021-03-04 10:08:40,135 INFO spawned: 'activemq' with pid 17`
`2021-03-04T10:08:40.4756165Z [32mtests-localstack   |[0m Waiting for all LocalStack services to be ready`
`2021-03-04T10:08:40.4757550Z [35mtests-mongo-arbiter |[0m [38;5;6mmongodb [38;5;5m10:08:38.36 [0m`
`2021-03-04T10:08:40.4759328Z [35mtests-mongo-arbiter |[0m [38;5;6mmongodb [38;5;5m10:08:38.36 [0m[1mWelcome to the Bitnami mongodb container[0m`
`2021-03-04T10:08:40.4761163Z [35mtests-mongo-arbiter |[0m [38;5;6mmongodb [38;5;5m10:08:38.37 [0mSubscribe to project updates by watching [1mhttps://github.com/bitnami/bitnami-docker-mongodb[0m`
`2021-03-04T10:08:40.4763613Z [35mtests-mongo-arbiter |[0m [38;5;6mmongodb [38;5;5m10:08:38.38 [0mSubmit issues and feature requests at [1mhttps://github.com/bitnami/bitnami-docker-mongodb/issues[0m`
`2021-03-04T10:08:40.4765250Z [35mtests-mongo-arbiter |[0m [38;5;6mmongodb [38;5;5m10:08:38.38 [0m`
`2021-03-04T10:08:40.4766527Z [35mtests-mongo-arbiter |[0m [38;5;6mmongodb [38;5;5m10:08:38.38 [0m[38;5;2mINFO [0m ==> ** Starting MongoDB setup **`
`2021-03-04T10:08:40.4767963Z [35mtests-mongo-arbiter |[0m [38;5;6mmongodb [38;5;5m10:08:38.42 [0m[38;5;2mINFO [0m ==> Validating settings in MONGODB_* env vars...`
`2021-03-04T10:08:40.4769377Z [35mtests-mongo-arbiter |[0m [38;5;6mmongodb [38;5;5m10:08:38.46 [0m[38;5;2mINFO [0m ==> Initializing MongoDB...`
`2021-03-04T10:08:40.4770773Z [35mtests-mongo-arbiter |[0m [38;5;6mmongodb [38;5;5m10:08:38.51 [0m[38;5;2mINFO [0m ==> Deploying MongoDB from scratch...`
`2021-03-04T10:08:40.4771989Z [36;1mtests-mongo-secondary |[0m [38;5;6mmongodb [38;5;5m10:08:37.32 [0m`
`2021-03-04T10:08:40.4773286Z [36;1mtests-mongo-secondary |[0m [38;5;6mmongodb [38;5;5m10:08:37.32 [0m[1mWelcome to the Bitnami mongodb container[0m`
`2021-03-04T10:08:40.4775144Z [36;1mtests-mongo-secondary |[0m [38;5;6mmongodb [38;5;5m10:08:37.32 [0mSubscribe to project updates by watching [1mhttps://github.com/bitnami/bitnami-docker-mongodb[0m`
`2021-03-04T10:08:40.4777336Z [36;1mtests-mongo-secondary |[0m [38;5;6mmongodb [38;5;5m10:08:37.33 [0mSubmit issues and feature requests at [1mhttps://github.com/bitnami/bitnami-docker-mongodb/issues[0m`
`2021-03-04T10:08:40.4778929Z [36;1mtests-mongo-secondary |[0m [38;5;6mmongodb [38;5;5m10:08:37.33 [0m`
`2021-03-04T10:08:40.4780174Z [36;1mtests-mongo-secondary |[0m [38;5;6mmongodb [38;5;5m10:08:37.34 [0m[38;5;2mINFO [0m ==> ** Starting MongoDB setup **`
`2021-03-04T10:08:40.4809614Z [36;1mtests-mongo-secondary |[0m [38;5;6mmongodb [38;5;5m10:08:37.36 [0m[38;5;2mINFO [0m ==> Validating settings in MONGODB_* env vars...`
`2021-03-04T10:08:40.4811137Z [36;1mtests-mongo-secondary |[0m [38;5;6mmongodb [38;5;5m10:08:37.38 [0m[38;5;2mINFO [0m ==> Initializing MongoDB...`
`2021-03-04T10:08:40.4812759Z [36;1mtests-mongo-secondary |[0m [38;5;6mmongodb [38;5;5m10:08:37.41 [0m[38;5;2mINFO [0m ==> Deploying MongoDB from scratch...`
`2021-03-04T10:08:40.4823865Z [33;1mtests-redis        |[0m 1:C 04 Mar 2021 10:08:39.578 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo`
`2021-03-04T10:08:40.4825323Z [33;1mtests-redis        |[0m 1:C 04 Mar 2021 10:08:39.578 # Redis version=6.2.1, bits=64, commit=00000000, modified=0, pid=1, just started`
`2021-03-04T10:08:40.4828145Z [33;1mtests-redis        |[0m 1:C 04 Mar 2021 10:08:39.578 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf`
`2021-03-04T10:08:40.4830508Z [33;1mtests-redis        |[0m 1:M 04 Mar 2021 10:08:39.579 * monotonic clock: POSIX clock_gettime`
`2021-03-04T10:08:40.4853510Z [33;1mtests-redis        |[0m 1:M 04 Mar 2021 10:08:39.582 * Running mode=standalone, port=6379.`
`2021-03-04T10:08:40.4855259Z [33;1mtests-redis        |[0m 1:M 04 Mar 2021 10:08:39.582 # Server initialized`
`2021-03-04T10:08:40.4857588Z [33;1mtests-redis        |[0m 1:M 04 Mar 2021 10:08:39.582 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.`
`2021-03-04T10:08:40.4859495Z [33;1mtests-redis        |[0m 1:M 04 Mar 2021 10:08:39.588 * Ready to accept connections`
`2021-03-04T10:08:40.4860542Z [34mtests-mongo-primary |[0m [38;5;6mmongodb [38;5;5m10:08:37.35 [0m`
`2021-03-04T10:08:40.4862416Z [34mtests-mongo-primary |[0m [38;5;6mmongodb [38;5;5m10:08:37.36 [0m[1mWelcome to the Bitnami mongodb container[0m`
`2021-03-04T10:08:40.4864871Z [34mtests-mongo-primary |[0m [38;5;6mmongodb [38;5;5m10:08:37.36 [0mSubscribe to project updates by watching [1mhttps://github.com/bitnami/bitnami-docker-mongodb[0m`
`2021-03-04T10:08:40.4867192Z [34mtests-mongo-primary |[0m [38;5;6mmongodb [38;5;5m10:08:37.36 [0mSubmit issues and feature requests at [1mhttps://github.com/bitnami/bitnami-docker-mongodb/issues[0m`
`2021-03-04T10:08:40.4868740Z [34mtests-mongo-primary |[0m [38;5;6mmongodb [38;5;5m10:08:37.36 [0m`
`2021-03-04T10:08:40.4870100Z [34mtests-mongo-primary |[0m [38;5;6mmongodb [38;5;5m10:08:37.36 [0m[38;5;2mINFO [0m ==> ** Starting MongoDB setup **`
`2021-03-04T10:08:40.4871625Z [34mtests-mongo-primary |[0m [38;5;6mmongodb [38;5;5m10:08:37.38 [0m[38;5;2mINFO [0m ==> Validating settings in MONGODB_* env vars...`
`2021-03-04T10:08:40.4873109Z [34mtests-mongo-primary |[0m [38;5;6mmongodb [38;5;5m10:08:37.40 [0m[38;5;2mINFO [0m ==> Initializing MongoDB...`
`2021-03-04T10:08:40.4874710Z [34mtests-mongo-primary |[0m [38;5;6mmongodb [38;5;5m10:08:37.42 [0m[38;5;2mINFO [0m ==> Deploying MongoDB from scratch...`
`2021-03-04T10:08:40.5271851Z [32mtests-localstack   |[0m 2021-03-04 10:08:40,526 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.`
`2021-03-04T10:08:40.5364338Z [32mtests-localstack   |[0m 2021-03-04 10:08:40,535 INFO supervisord started with pid 14`
`2021-03-04T10:08:41.2991237Z [36mtests-active-mq    |[0m 2021-03-04 10:08:41,298 INFO success: cron entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)`
`2021-03-04T10:08:41.2998655Z [36mtests-active-mq    |[0m 2021-03-04 10:08:41,298 INFO success: activemq entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)`
`2021-03-04T10:08:41.5405315Z [32mtests-localstack   |[0m 2021-03-04 10:08:41,539 INFO spawned: 'dashboard' with pid 20`
`2021-03-04T10:08:41.5415225Z [35mtests-mongo-arbiter |[0m [38;5;6mmongodb [38;5;5m10:08:41.53 [0m[38;5;2mINFO [0m ==> Creating users...`
`2021-03-04T10:08:41.5565814Z [35mtests-mongo-arbiter |[0m [38;5;6mmongodb [38;5;5m10:08:41.55 [0m[38;5;2mINFO [0m ==> Users created`
`2021-03-04T10:08:41.5572327Z [34mtests-mongo-primary |[0m [38;5;6mmongodb [38;5;5m10:08:41.53 [0m[38;5;2mINFO [0m ==> Creating users...`
`2021-03-04T10:08:41.5595993Z [36;1mtests-mongo-secondary |[0m [38;5;6mmongodb [38;5;5m10:08:41.55 [0m[38;5;2mINFO [0m ==> Creating users...`
`2021-03-04T10:08:41.5616964Z [36;1mtests-mongo-secondary |[0m [38;5;6mmongodb [38;5;5m10:08:41.56 [0m[38;5;2mINFO [0m ==> Users created`
`2021-03-04T10:08:41.5627343Z [34mtests-mongo-primary |[0m [38;5;6mmongodb [38;5;5m10:08:41.56 [0m[38;5;2mINFO [0m ==> Creating root user...`
`2021-03-04T10:08:41.5649830Z [36;1mtests-mongo-secondary |[0m [38;5;6mmongodb [38;5;5m10:08:41.56 [0m[38;5;2mINFO [0m ==> Writing keyfile for replica set authentication...`
`2021-03-04T10:08:41.5652114Z [35mtests-mongo-arbiter |[0m [38;5;6mmongodb [38;5;5m10:08:41.56 [0m[38;5;2mINFO [0m ==> Writing keyfile for replica set authentication...`
`2021-03-04T10:08:41.5960303Z [32mtests-localstack   |[0m 2021-03-04 10:08:41,594 INFO spawned: 'infra' with pid 21`
`2021-03-04T10:08:41.5967995Z [32mtests-localstack   |[0m 2021-03-04 10:08:41,596 INFO exited: dashboard (exit status 0; expected)`
`2021-03-04T10:08:41.6707687Z [36;1mtests-mongo-secondary |[0m [38;5;6mmongodb [38;5;5m10:08:41.66 [0m[38;5;2mINFO [0m ==> Configuring MongoDB replica set...`
`2021-03-04T10:08:41.6714628Z [35mtests-mongo-arbiter |[0m [38;5;6mmongodb [38;5;5m10:08:41.67 [0m[38;5;2mINFO [0m ==> Configuring MongoDB replica set...`
`2021-03-04T10:08:41.6871188Z [36;1mtests-mongo-secondary |[0m [38;5;6mmongodb [38;5;5m10:08:41.67 [0m[38;5;2mINFO [0m ==> Stopping MongoDB...`
`2021-03-04T10:08:41.7062877Z [35mtests-mongo-arbiter |[0m [38;5;6mmongodb [38;5;5m10:08:41.70 [0m[38;5;2mINFO [0m ==> Stopping MongoDB...`
`2021-03-04T10:08:42.0452910Z [32mtests-localstack   |[0m (. .venv/bin/activate; exec bin/localstack start --host)`
`2021-03-04T10:08:42.0968760Z [32;1mtests-redacted    |[0m The following arguments have been ignored : "--no-build --no-restore"`
`2021-03-04T10:08:42.1321854Z [34mtests-mongo-primary |[0m [38;5;6mmongodb [38;5;5m10:08:42.12 [0m[38;5;2mINFO [0m ==> Users created`
`2021-03-04T10:08:42.1348701Z [34mtests-mongo-primary |[0m [38;5;6mmongodb [38;5;5m10:08:42.13 [0m[38;5;2mINFO [0m ==> Writing keyfile for replica set authentication...`
`2021-03-04T10:08:42.2276390Z [34mtests-mongo-primary |[0m [38;5;6mmongodb [38;5;5m10:08:42.22 [0m[38;5;2mINFO [0m ==> Configuring MongoDB replica set...`
`2021-03-04T10:08:42.2629417Z [34mtests-mongo-primary |[0m [38;5;6mmongodb [38;5;5m10:08:42.25 [0m[38;5;2mINFO [0m ==> Stopping MongoDB...`
`2021-03-04T10:08:42.4560849Z [32;1mtests-redacted    |[0m Microsoft (R) Test Execution Command Line Tool Version 16.9.0`
`2021-03-04T10:08:42.4562835Z [32;1mtests-redacted    |[0m Copyright (c) Microsoft Corporation.  All rights reserved.`
`2021-03-04T10:08:42.4563865Z [32;1mtests-redacted    |[0m `
`2021-03-04T10:08:42.6127092Z [32mtests-localstack   |[0m 2021-03-04 10:08:42,611 INFO success: infra entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)`
`2021-03-04T10:08:42.8612861Z [32;1mtests-redacted    |[0m Starting test execution, please wait...`
`2021-03-04T10:08:43.0858396Z [32;1mtests-redacted    |[0m A total of 3 test files matched the specified pattern.`
`2021-03-04T10:08:46.1403571Z [32mtests-localstack   |[0m Waiting for all LocalStack services to be ready`
`2021-03-04T10:08:48.5424560Z [36;1mtests-mongo-secondary |[0m [38;5;6mmongodb [38;5;5m10:08:48.54 [0m[38;5;2mINFO [0m ==> Trying to connect to MongoDB server mongo-primary...`
`2021-03-04T10:08:48.5646910Z [35mtests-mongo-arbiter |[0m [38;5;6mmongodb [38;5;5m10:08:48.56 [0m[38;5;2mINFO [0m ==> Trying to connect to MongoDB server mongo-primary...`
`2021-03-04T10:08:48.8923247Z [34mtests-mongo-primary |[0m [38;5;6mmongodb [38;5;5m10:08:48.89 [0m[38;5;2mINFO [0m ==> Configuring MongoDB primary node`
`2021-03-04T10:08:49.0656182Z [36;1mtests-mongo-secondary |[0m [38;5;6mmongodb [38;5;5m10:08:49.06 [0m[38;5;2mINFO [0m ==> Found MongoDB server listening at mongo-primary:27017 !`
`2021-03-04T10:08:49.0912697Z [35mtests-mongo-arbiter |[0m [38;5;6mmongodb [38;5;5m10:08:49.08 [0m[38;5;2mINFO [0m ==> Found MongoDB server listening at mongo-primary:27017 !`
`2021-03-04T10:08:49.5569844Z [34mtests-mongo-primary |[0m [38;5;6mmongodb [38;5;5m10:08:49.55 [0m[38;5;2mINFO [0m ==> Stopping MongoDB...`
`2021-03-04T10:08:49.6658168Z [35mtests-mongo-arbiter |[0m [38;5;6mmongodb [38;5;5m10:08:49.66 [0m[38;5;2mINFO [0m ==> MongoDB server listening and working at mongo-primary:27017 !`
`2021-03-04T10:08:51.6562916Z [34mtests-mongo-primary |[0m [38;5;6mmongodb [38;5;5m10:08:51.65 [0m[38;5;2mINFO [0m ==> Enabling authentication...`

20210302.0:
`Run docker-compose \`
`Creating network "src_internal" with driver "bridge"`
`Creating tests-elasticsearch ... `
`Creating tests-mongo-secondary ... `
`Creating tests-mongo-arbiter   ... `
`Creating tests-active-mq       ... `
`Creating tests-mongo-primary   ... `
`Creating tests-redis           ... `
`Creating tests-localstack      ... `
`Creating tests-redis           ... done`
`Creating tests-localstack      ... done`
`Creating tests-mongo-arbiter   ... done`
`Creating tests-active-mq       ... done`
`Creating tests-mongo-primary   ... done`
`Creating tests-elasticsearch   ... done`
`Creating tests-redacted       ... `
`Creating tests-mongo-secondary ... done`
`Creating tests-redacted       ... done`
`Attaching to tests-redacted`
`tests-redacted    | The following arguments have been ignored : "--no-build --no-restore"`
`tests-redacted    | Microsoft (R) Test Execution Command Line Tool Version 16.9.0`
`tests-redacted    | Copyright (c) Microsoft Corporation.  All rights reserved.`
`tests-redacted    | `
`tests-redacted    | Starting test execution, please wait...`
`tests-redacted    | A total of 3 test files matched the specified pattern.`
`Error: The operation was canceled.`

**Area for Triage**:  
Containers, Deployment/Release

**Question, Bug, or Feature?**:  
Bug

**Virtual environments affected**  
- [ ] Ubuntu 16.04
- [ x ] Ubuntu 18.04
- [ x ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Image version**
20210302.0

**Expected behavior**  
Expected the test runner to attach to the tests and run. but the docker containers seems to not be spawning or something, since there is no output from them.

**Actual behavior**  
Test container spawns, but no tests are being run. The actions just waits for 6 hours and then cancels the job

**Comment by Darleev** [comment]
Hello @oliv0533,
Could you please provide some sample repo or steps to reproduce the issue on our side?
We are looking forward to your reply.

**Comment by Darleev** [comment]
Hello @ffMathy,
You can check all software changes in the closed PRs, below an example for Ubuntu20:
https://github.com/actions/virtual-environments/pull/2815/files

I see only docker-compose and alpine cached image changes, and I believe these changes do not affect anything from a performance perspective. Hardware specs weren't changed as well.

**Comment by ffMathy** [comment]
We have resolved the issue.

In our docker-compose.yml, we had chosen the "none" log driver for each of our services. Now, after removing that, our run goes through.

How on earth disabling logging can impact the test run, I have no idea. And it happened without code changes from our side, right after the last environment update.

**Comment by Darleev** [comment]
Thank you @ffMathy for the information provided. Most probably something was changed in one of the latest docker-compose updates.
[Docker compose release notes ](https://docs.docker.com/compose/release-notes/). Maybe it is somehow related to "Removed the log driver filter." update?
@oliv0533 could you please also check the provided solution?

**Comment by oliv0533** [comment]
@Darleev The solution works for me as well, since @ffMathy and I work in the same organisation. We will take a look at the release notes, thanks.

**Comment by Darleev** [comment]
@oliv0533 @ffMathy thank you for the investigation details and solution provided.
I'm going to close this case, let us know in case of any questions.
