### ISSUE TITLE
The only breakage I can imagine is from scripts that use `$GOROOT` directly for some reason, instead of `$(go env GOROOT)`. These scripts would only work in the GitHub Actions environment, since most systems don't have `$GOROOT` defined.

### ISSUE THREAD

**Issue by king2web** [actions/virtual-environments#2856]
The only breakage I can imagine is from scripts that use `$GOROOT` directly for some reason, instead of `$(go env GOROOT)`. These scripts would only work in the GitHub Actions environment, since most systems don't have `$GOROOT` defined.

_Originally posted by @FiloSottile in https://github.com/actions/virtual-environments/issues/2655#issuecomment-776057096_

**Comment by Darleev** [comment]
Hello @king2web,
Could you please clarify your request and provide more details here?
We are looking forward to your reply.

**Comment by catthehacker** [comment]
@Darleev it's a spam bot just like #2370, #2591, #2590

**Comment by Darleev** [comment]
Hello @catthehacker,
Thank you for clarifying this. I'm going to close the issue.
