### ISSUE TITLE
Update zstd

### ISSUE THREAD

**Issue by smorimoto** [actions/virtual-environments#2858]
Currently, different versions of zstd are installed on each platform, and this often causes hassle in projects like actions/cache, and makes performance predictions more difficult. So I would suggest installing it from source on all platforms. There are also significant improvements in 1.4.9, which is one of the very big reasons to do so.
https://www.phoronix.com/scan.php?page=news_item&px=Zstd-1.4.9-Released

**Comment by maxim-lobanov** [comment]
@smorimoto , Yep, apt package and choco package look unmaintainable. Do you know whether zstd owners have plans to update them in future?
Brew package looks up-to-date. It is updated automatically.

**Comment by smorimoto** [comment]
For apt, it's still maintaining, but they have a different packaging policy than brew. Once they do a release, they maintain that release only - so they will only update it to fix bugs, but not to add features. It often doesn't fit well with us, but stability is more important than the latest version for many users. In that sense, we need to build and install it from source.

**Comment by smorimoto** [comment]
As for choco one, it doesn't seem to be actively updated. Since zstd is used by a fairly fundamental action in Actions, it makes a lot of sense for us to have full control of it.

**Comment by al-cheb** [comment]
Thank you @maki-chan to help me with updating zstd to 1.4.9 in choco - https://chocolatey.org/packages/zstandard/1.4.9

**Comment by smorimoto** [comment]
@maxim-lobanov @al-cheb What about other platforms?

**Comment by smorimoto** [comment]
It seems brew is already up to date, so we only need to install it from source on the Ubuntu runners. Or, you can use Linuxbrew. I personally recommend using Linuxbrew for ease of maintenance, but I leave it to your policy.

**Comment by miketimofeev** [comment]
@smorimoto we have a plan about adding it to Ubuntu images, but no ETA for now

**Comment by smorimoto** [comment]
Since this is important for the next actions cache release, good to know.

**Comment by al-cheb** [comment]
OS | zstd version
----|--------------
Windows Server 2016/2019 | 1.4.9
macOS-10.15/11| 1.4.9
Ubuntu 16.04/18.04/20.04 | 1.4.4

I was not able to find repositories with updated version of the zstd package for Ubuntu 16/18/20.  Currently we don't have any plans to build zstd from source.

Workaround for Ubuntu:
1. `brew install zstd`
2. manually build zstd from source
```
- run: sudo apt-get remove zstd
- run: |
   git clone https://github.com/facebook/zstd
   cd zstd
   make && sudo make install
- run: which zstd
- run: zstd -V 
```

![image](https://user-images.githubusercontent.com/47745270/114519684-535bc180-9c49-11eb-918f-a60804dc56c6.png)

**Comment by smorimoto** [comment]
Why can't you install from the source? Since actions/cache uses zstd by default, fixing its version is important to make official actions more reliable.

**Comment by maxim-lobanov** [comment]
We don't build any tools from source code due to maintenance concerns (image-gen time, complexity, dependencies issues, any potential issues that we won't be able to fix from our side).
I suggest logging issue against https://github.com/facebook/zstd and ask keeping apt source up-to-date or providing another way for installation.

P.S. As an alternative, we can consider installation of zstd via Homebrew on Linux (Linuxbrew). They provide binaries for Ubuntu: https://github.com/Homebrew/linuxbrew-core/blob/HEAD/Formula/zstd.rb#L13

**Comment by smorimoto** [comment]
> I suggest logging issue against https://github.com/facebook/zstd and ask keeping apt source up-to-date or providing another way for installation.

I have already explained here why that is not possible or has no meaning in many cases: https://github.com/actions/virtual-environments/issues/2858#issuecomment-795606526
Also, be aware of the risk of using a repository that you have no confidence about trustworthy with a CI.

> P.S. As an alternative, we can consider installation of zstd via Homebrew on Linux (Linuxbrew). They provide binaries for Ubuntu: https://github.com/Homebrew/linuxbrew-core/blob/HEAD/Formula/zstd.rb#L13

I have already suggested that: https://github.com/actions/virtual-environments/issues/2858#issuecomment-814588134
This is definitely worth doing.

CC: @dhadka

**Comment by al-cheb** [comment]
@smorimoto, The new images with zstd have been deployed.

**Comment by smorimoto** [comment]
Great!

**Comment by smorimoto** [comment]
@joshmgross Will we be able to eliminate the platform-specific differences in actions/cache by this and the change to prefer gnu tar?

**Comment by joshmgross** [comment]
> Will we be able to eliminate the platform-specific differences in actions/cache by this and the change to prefer gnu tar?

I'm not sure if we can remove all the platform-specific differences, but this should definitely help. Windows might still have some issues with preferring GNU tar.
