### ISSUE TITLE
Installation of package libphp7.4-embed fails on Ubuntu 20.04

### ISSUE THREAD

**Issue by flashcode** [actions/virtual-environments#2859]
**Description**  
Installation of package `libphp7.4-embed` fails on Ubuntu 20.04

**Area for Triage**:  

**Question, Bug, or Feature?**:  Bug

**Virtual environments affected**  
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [X] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Image version**

Version: 20210302.0

**Expected behavior**  
Package `libphp7.4-embed` can be installed without errors.

**Actual behavior**  
Error while installing package:

    The following packages have unmet dependencies:
     libphp7.4-embed : Depends: php7.4-common (= 7.4.3-4ubuntu2.4) but 7.4.15-7+ubuntu20.04.1+deb.sury.org+1 is to be installed
    E: Unable to correct problems, you have held broken packages.
    Error: Process completed with exit code 100.

**Repro steps**  
See: https://github.com/weechat/weechat/runs/2042779070?check_suite_focus=true

**Comment by Darleev** [comment]
Hello @flashcode,
Most probably the issue somewhere in PHP dependencies and should be resolved on their side, however, we will investigate it deeper.
As a workaround, you can use the following commands:

```
sudo apt remove php7.4-common
sudo apt install libphp7.4-embed
```
We will keep you informed.

**Comment by vsafonkin** [comment]
Hi @flashcode, it looks like ubuntu 20.04 has php7.4-common version that is incompatible with libphp7.4-embed package. You can either remove pre-installed php7.4-common and it will be installed as dependency with required version, or use ubuntu 18.04, that has compatible version php7.4-common. Thanks!

**Comment by vsafonkin** [comment]
Closed, because we can't do anything from our side.

**Comment by flashcode** [comment]
@Darleev, @vsafonkin: thanks I can make it work by first removing php7.4-common then installing libphp7.4-embed, but I find that weird to have to do this (and now my workflow takes more time, because many packages are removed as well when removing this one).

Is this an issue in Ubuntu 20.04 itself?

As far as I know, in Ubuntu there is this version of php7.4-common: 7.4.3-4ubuntu2.4 (see: https://packages.ubuntu.com/focal/php7.4-common).

But when trying to install libphp7.4-embed in my GitHub workflow, it tries to install version `7.4.15-7+ubuntu20.04.1+deb.sury.org+1` of php7.4-common. Where does this version come from? Ubuntu, GitHub, somewhere else?

**Comment by vsafonkin** [comment]
@flashcode, we install this package without specifying any version: [installer script](https://github.com/actions/virtual-environments/blob/main/images/linux/scripts/installers/php.sh)
As I see, there are many apt package sources on runner: https://github.com/vsafonkin/test-repo/runs/2131221426?check_suite_focus=true
Unfortunately, I can't understand where the package from. Logs contain only destination folder:
```
Verification finished successfully. file=/var/cache/apt/apt-fast/php7.4-common_7.4.16-1+ubuntu20.04.1+deb.sury.org+1_amd64.deb
Download complete: /var/cache/apt/apt-fast/php7.4-common_7.4.16-1+ubuntu20.04.1+deb.sury.org+1_amd64.deb
```

**Comment by flashcode** [comment]
@vsafonkin: thanks for the links, I see you do `apt-add-repository ppa:ondrej/php -y`, and the package version `7.4.15-7+ubuntu20.04.1+deb.sury.org+1` comes from this PPA.

If I do this myself as well in my CI workflow, it works fine without having to first remove `php7.4-common` package.

Thank you.
