### ISSUE TITLE
add lerna

### ISSUE THREAD

**Issue by awentzel** [actions/virtual-environments#286]
**Tool information**
- Tool name: Lerna
- Add or update? Add
- Desired version: Latest
- Approximate size: 
- If this is an add request:
  - Brief description of tool: Lerna is a common package manager for monorepositories
  - URL for tool's homepage: https://lerna.js.org/

**Area for Triage**:

**Question, Bug, or Feature?**:

**Virtual environments affected**
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [] Windows Server 2016 R2
- [X] Windows Server 2019

**Can this tool be installed during the build?**

**Are you willing to submit a PR?**

**Comment by alepauly** [comment]
@awentzel - can this be installed during a build?

**Comment by awentzel** [comment]
@alepauly we have been installing during the build for a few years.  However, it takes twice as long to install on Windows as Linux or Mac.  Lerna is very common for enterprise projects.  Oddly, building on Windows, in general, takes 36% longer with twice the memory and same cores as Circle CI.  Trying to find a way to squeeze faster builds out of Windows environments or we'll have to keep using Circle CI.  We can Linux, but, it would be nice to run on Windows to ensure reliability for Windows users.

**Comment by miketimofeev** [comment]
PR has been merged https://github.com/actions/virtual-environments/pull/374

**Comment by miketimofeev** [comment]
@awentzel Win16 and 19 images have been deployed. Could you check that lerna is presented, please?

**Comment by miketimofeev** [comment]
@awentzel I'm going to close the issue. Feel free to reopen if you have any concerns, thanks!
