### ISSUE TITLE
Xdebug seems to be disabled in PHP 7.3 and 7.4 on Ubuntu 18.04 version 20210302.0

### ISSUE THREAD

**Issue by ngmy** [actions/virtual-environments#2863]
**Description**  
Xdebug seems to be disabled in PHP 7.3 and 7.4 on Ubuntu 18.04 version 20210302.0 (`php -i | grep -i xdebug` is not found and the coverage xml is not generated by PHPUnit).

It seems to be enabled in PHP 8.0 (`php -i | grep -i xdebug` is found and the coverage xml is generated by PHPUnit).

It seems to have been enabled in PHP 7.3, 7.4, and 8.0 on version Ubuntu 18.04 version 20210219.1 (The coverage xml is generated by PHPUnit. I have not checked `php -i | grep -i xdebug`). 

**Area for Triage**:  
PHP

**Question, Bug, or Feature?**:  
Question

**Virtual environments affected**  
- [ ] Ubuntu 16.04
- [x] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Image version**
20210302.0

**Expected behavior**  
Xdebug is enabled in PHP 7.3, 7.4, and 8.0.

**Actual behavior**  
Xdebug is disabled in PHP 7.3, 7.4.

**Repro steps**  
1. Version 20210302.0: https://github.com/ngmy/php-typed-array/actions/runs/627561956
2. Version 20210219.1: https://github.com/ngmy/php-typed-array/actions/runs/616429869

**Comment by Darleev** [comment]
Hello @ngmy,
As far as I see, a fix for the issue was added in the scope of https://github.com/actions/virtual-environments/pull/2834 .
So, the issue should be fixed after the next image rollout.
I'll keep you informed.

**Comment by caseyw** [comment]
This is also broken for us on PHP 7.2 and started to fail all builds on March 3rd.

What's your release cycle so I can take it back to our team?

**Comment by Darleev** [comment]
Hello @caseyw,
We usually deploy a new version of the image every week, but sometimes it happens every two weeks.

**Comment by ngmy** [comment]
@Darleev 
Thank you.
Version 20210309.1 came to me and fixed the issue.
