### ISSUE TITLE
Add iOS 12.4 or older to Xcode 11 or newer

### ISSUE THREAD

**Issue by fermoya** [actions/virtual-environments#2864]
Could we add `iOS 12.4` simulators to some Xcode other than `10.3`? For instance, `Xcode 12.4`
https://github.com/actions/virtual-environments/blob/main/images/macos/macos-10.15-Readme.md#installed-sdks

**Tool information**
- Tool name: `iOS 12.4`
- Tool license:  N/A
- Add or update?  Add
- Desired version:  `iOS 12.4`
- Approximate size:  ~3GB
- If this is an add request:
  - Brief description of tool:  `iOS 12.4` simulator in some Xcode later than 11.0
  - URL for tool's homepage:  
  - Provide a basic test case to validate the tool's functionality:  I'd like to validate my code against legacy iOS versions. I have a target that supports iOS 13+ inside a project targeting iOS 12. I want to build the project against iOS 12 to verify it compiles.

**Area for Triage**:

Apple

**Question, Bug, or Feature?**:
Feature

**Virtual environments affected**
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [✅ ] macOS 10.15
- [✅ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Can this tool be installed during the build?**
N/A

**Tool installation time in runtime**
N/A

**Are you willing to submit a PR?**
N/A

**Comment by miketimofeev** [comment]
Hi @fermoya! Take a look at this comment, please https://github.com/actions/virtual-environments/issues/551#issuecomment-788822538

**Comment by fermoya** [comment]
Thanks @miketimofeev , [this workaround](https://github.com/actions/virtual-environments/issues/551#issuecomment-669226983) is great 👍🏻
