### ISSUE TITLE
workflow fails but no log from failing step

### ISSUE THREAD

**Issue by dehesselle** [actions/virtual-environments#2866]
**Description**  
My workflow keeps failing on me (which I expect to be my fault) but the log archive is missing the log from the failing step. I have no means to debug the situation without the log.

**Area for Triage**:  
Apple

**Question, Bug, or Feature?**:  
Bug

**Virtual environments affected**  
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [x] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Image version**
 20210302.1

**Expected behavior**  
Every step in the job produces a log, regardless of success or failure, and all logs can be accessed via GitHub website and are present in the archive when clicking "download log archive".

**Actual behavior**  
The log from the failing step is lost. It is not accessible via GitHub website nor present in the archive when clicking "download log archive".

**Repro steps**
Run this workflow   
https://github.com/dehesselle/mibap/actions/workflows/inkscape_only.yml
for the develop branch.
It will fail on the "compile Inkscape" step without providing a log.

(I have more examples, as the code from inkscape_only.yml is also present in mibap.yml, but it takes about 2 hours until we get to that point.)

**Comment by Darleev** [comment]
Hello @dehesselle,
Thank you for the issue reported.
We will investigate the issue and get back to you.

**Comment by thomabr** [comment]
I'm seeing this in our logs. I think there is something in `210-inkscape_build.sh` that is causing resource starvation which disconnects our runner. Can the customer make sure that script is doing what they expect without significant resource utilization? 

https://dataexplorer.azure.com/clusters/vso/databases/VSO?query=H4sIAAAAAAAA/3xTzW7bPBC86ykWwnewAcb68tMWTaFD4KaNAScx1Bg5M9RKYkJxVXIVJ2j67oXkH8mCE9043BnN7C6jqDLSzlL4s0zmf+EIfiJ74AJhYaSFWQqZoxKkhVAq1mR95GrrQ1gm88Agw4YeA5NX0kg3WjhKa8V3TioM3mBVoENoTxVpyxDHcPJ/850Gb4AvjDaFm/tbiJuDk4ofPdlR+N9kSpbxhScJVuQ1k3sNBVyj9zLHcce9J/eUGVodFMh0XjvZGJ9cS21/aIMLycVBoaReJ3nPRnP9HvGmLh/QfUhelxwUWCZziMGzU5JHYcFc+fMoyjUX9cNEURmFommRCKP+EKJQtJ7Guy63OjEcUkixQO/RGIxK/SCrfaXPJ1/PTr8cfzoLe6kw+2gm2cEki+06DHi3ThXoeT2KWYqWdaaH3agcPaLijUjwBiyfEI7H34JM2xS0hdGFYv2s+XVOuYCLHC0viEyCv2v0fKV9syUCrpir25pz0jbf3HkBex5agT2k+esmnoD+Eo+DdXcHGcCzdOxXmovtKyAHlyeXs+/NENZQsMvkUGmPd7rEXyzLSkAAm2+g27vpXo3YYVMqS2n7VZsOCuigpTPNmveKEvQVWY9TSrEHz/EZjYAogowcKDLktM3hfLyr2HZ8z1ibsvN0+aKwatxvrXRGPLp2TB3UDGdqNFq+kSXu49fIBaXdOrVUiEGRNOgVjjq97XPpaALCo1AM9Me9xTqSK/naszS00rcQ/AMAAP//AQAA//+0qG8mGgUAAA==


```
Job failed with an infrastructure job failures: The hosted runner: GitHub Actions 2 lost communication with the server. Anything in your workflow that terminates the runner process, starves it for CPU/Memory, or blocks its network access can cause this error.
```

**Comment by dehesselle** [comment]
Thank you for investigating. The step in question builds a big application and uses `ninja`, which by default is resource intensive. I will limit resource usage and report back.

**Comment by dehesselle** [comment]
I have been running a lot of builds (try & error) but haven't arrived at a satisfying solution yet. I've forced `make` to a single core, I removed a possible memory-intensive step and I still get breakages, sometimes during steps that haven't shown any kind of problems before. 
I think I need one or two more days to make further experiments (I can only work on this a few hours per day since this is not my day job; also it takes at least 45 min for a run), but then I will have gotten to a point where I exhausted all my (sensible) options. Once I get there, I'll give you another workflow run of mine to inspect, hoping that you'll be able to tell me exactly what resource (CPU, memory, disk I/O, ...) is causing the problems.

**Comment by dehesselle** [comment]
I believe I have it under control now. It appears that working off a compressed dmg union-mounted with a writable overlay causes these problems (that I don't have on my self-hosted infrastructure).
I'm able to run my workflow now sing `ninja´ and without limiting CPU cores.

Thank you for your support!

**Comment by Darleev** [comment]
@dehesselle thank you for the provided investigation details. It's nice to hear that the problem has been resolved.
In case of any questions, feel free to contact us, we will be glad to assist you further.
