### ISSUE TITLE
Update/Add PowerShell Az Module v5.6.0

### ISSUE THREAD

**Issue by cognitionIT** [actions/virtual-environments#2867]
**Tool information**
- Tool name: PowerShell Az Module
- Add or update? Update
- Desired version: 5.6.0

**Area for Triage**:

**Question, Bug, or Feature?**:
Feature

**Virtual environments affected**
- [x] Ubuntu 16.04
- [x] Ubuntu 18.04
- [x] Ubuntu 20.04
- [x] macOS 10.15
- [x] macOS 11.0
- [x] Windows Server 2016 R2
- [x] Windows Server 2019

**Can this tool be installed during the build?**
According to this [link](https://github.com/Azure/bicep), the PowerShell Az module v5.6.0+ has built-in support for resource deployments in Azure, using a bicep template file instead of a JSON template file. Unfortunately I cannot use Update-Module to update the module myself to the latest version as it was not installed using Install-Module (so it cannot be Updated via an inline script using the PowerShell GitHub Action).

**Comment by Darleev** [comment]
Hello @cognitionIT,
In our scripts, we use the automatic installation of the latest stable version of the az module. So, the version of the module should be updated after the next image rollout(most probably during this week).
I'll keep you informed.

**Comment by cognitionIT** [comment]
Thank you @Darleev for the quick response, getting the latest stable version in the image rollout is fast enough for me, so it makes me happy to know I'll have some GitHub Actions fun to look forward to next weekend :-)

**Comment by Darleev** [comment]
Hello @cognitionIT,
We've received a new update, that az module update will be delayed due to code refactoring. We are waiting for the following PRs:
https://github.com/actions/virtual-environments/pull/2827
https://github.com/actions/virtual-environments/pull/2828
When PRs are completed, we will definitely upgrade az module to the latest stable version.
I'll keep you informed.

**Comment by krokofant** [comment]
I added this as a workaround for now
```yaml
$minAzModuleVersion = '5.6.0'
if(!(Test-Path "C:\Modules\az_$minAzModuleVersion")) {
  Install-Module -Name Az -AllowClobber -Scope CurrentUser -Force
  Save-Module -Path "C:\Modules\az_$minAzModuleVersion" -Name Az -RequiredVersion $minAzModuleVersion -Force -ErrorAction Stop
}
$env:PSModulePath = "C:\Modules\az_$($minAzModuleVersion);$($env:PSModulePath)"
Import-Module Az
```

**Comment by cognitionIT** [comment]
> I added this as a workaround for now
> 
> ```yaml
> $minAzModuleVersion = '5.6.0'
> if(!(Test-Path "C:\Modules\az_$minAzModuleVersion")) {
>   Install-Module -Name Az -AllowClobber -Scope CurrentUser -Force
>   Save-Module -Path "C:\Modules\az_$minAzModuleVersion" -Name Az -RequiredVersion $minAzModuleVersion -Force -ErrorAction Stop
> }
> $env:PSModulePath = "C:\Modules\az_$($minAzModuleVersion);$($env:PSModulePath)"
> Import-Module Az
> ```

Thanks for this workaround, I'll add it to the workflow and test it in a couple of hours as I'd rather run on the latest windows runner than a self-hosted runner :-)

**Comment by ricohomewood** [comment]
Az `5.6.0` has a major P0 bug in Az.Automation that has now been fixed in `5.7.0` which has now been released :https://github.com/Azure/azure-powershell/issues/14431 . Do we know when the Hosted Agents will install the real latest version of the Az powershell module? Currently they are still on 5.5.0 as their defined latest which is now 2 versions behind.

**Comment by maxim-lobanov** [comment]
Hello everyone!
No need to wait, both [azure/powershell](https://github.com/azure/powershell) (GitHub Actions task) and [AzurePowerShell](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-powershell?view=azure-devops) (Azure DevOps) were recently upgraded and can install any version of Az on-flight with 1-2 seconds delay.

```yml
    steps:
    - task: AzurePowerShell@5
      inputs:
        azureSubscription: '<>'
        ScriptType: 'InlineScript'
        preferredAzurePowerShellVersion: '5.7.0'
```

**Comment by krokofant** [comment]
Now 5.7 is out which also fixes a critical issue about nested bicep files.

**Comment by miketimofeev** [comment]
@cognitionIT @krokofant we've added version 5.7.0 to all the images and started a rollout. It will be finished in 3-4 days.

**Comment by miketimofeev** [comment]
@cognitionIT the rollout is finished for all the images.
I'm going to close the issue. Please feel free to contact us if you have any concerns.
Thank you!

**Comment by brwilkinson** [comment]
Is there a standard procedure in place to request an AZ Module version update ? Or is it best to just open a new issue each x months Etc. ?

Does the team have any plans to always stay N-1 or something on the latest version of AZ ?

**Comment by miketimofeev** [comment]
@brwilkinson we tend to manually update Az versions to avoid critical bugs that can be introduced in the new versions. Please create an issue if you'd like the new version to be added

**Comment by brwilkinson** [comment]
Thanks @miketimofeev sounds good.

#3558
