### ISSUE TITLE
Update RubyGems to at least 3.0.5

### ISSUE THREAD

**Issue by thejoebourneidentity** [actions/virtual-environments#287]
**Tool information**
- Tool name: RubyGems https://rubygems.org/pages/download
- Add or update? Update
- Desired version: 3.0.5 or higher
- Approximate size: 

**Area for Triage**:
Ruby

**Question, Bug, or Feature?**:
Feature

**Virtual environments affected**
- [X] macOS 10.15
- [X] Ubuntu 16.04 LTS
- [X] Ubuntu 18.04 LTS
- [X] Windows Server 2016 R2
- [X] Windows Server 2019

**Comment by dmitry-shibanov** [comment]
Hello, we prepared draft [pull request](https://github.com/actions/virtual-environments/pull/296) to update RubyGems to the latest version (3.1.2) and right now waiting for image validation.

**Comment by dmitry-shibanov** [comment]
Hello, [pull request](https://github.com/actions/virtual-environments/pull/296) with our changes have been merged and gem would be the latests version (3.1.2). Changes will be deployed next week.

**Comment by maxim-lobanov** [comment]
Hi!
Gem 3.1.2 is presented on all VM images: win, ubuntu, macos. I am closing this issue.
Feel free to reopen if you see any issues
