### ISSUE TITLE
Nmake not present on windows images

### ISSUE THREAD

**Issue by rhpvorderman** [actions/virtual-environments#2870]
**Description**  
Running "nmake" even with the VS environment activated will result in an error. The project I am trying to build is the [isa-l](https://github.com/intel/isa-l) project. It comes with clear instructions how to build with nmake. 

**Area for Triage**:  

**Question, Bug, or Feature?**:  
bug

**Virtual environments affected**  
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11.0
- [x] Windows Server 2016 R2
- [x] Windows Server 2019

**Image version**
Current runner version: '2.277.1'
Operating System
  Microsoft Windows Server 2019
  10.0.17763
  Datacenter
Virtual Environment
  Environment: windows-2019
  Version: 20210219.1
  Included Software: https://github.com/actions/virtual-environments/blob/win19/20210219.1/images/win/Windows2019-Readme.md

**Expected behavior**  
Since visual studio 2019 is installed, the script should be able to execute nmake.

**Actual behavior**  
https://github.com/pycompression/python-isal/runs/2040994130

When running nmake in a python subprocess it gives a System can not find the file specified error

**Repro steps**  
~~Run the python-isal ci.yml at this specific commit https://github.com/pycompression/python-isal/tree/6b0690785acf9572f258b645f78b922460a3e68b~~

EDIT: I created a minimal reproducer here: https://github.com/rhpvorderman/test-nmake-github-actions

**Debugging steps already taken**
Nmake can not be found. However it should be installed as Microsoft.VisualStudio.Component.VC.Tools.x86.x64 is installed. (Or I have the component wrong?). Nmake installed on my version of Visual Studio 2019 community. I did a side-by-side comparision and there are no modules that I have on my installation that are not present on the windows-2019 runner.

I did write a script to find the full path to nmake.exe using vswhere: pycompression/python-isal@2ff6f42
Unfortunately that gives an error that looks like mingw32-make is used instead: `mingw32-make: *** No rule to make target '/f'. Stop.`
`/f` of course being the file switch on `nmake`. The command being: `nmake /f Makefile.nmake`. It seems like nmake is linked to mingw32-make?

I don't understand why this is not working. Nmake works just fine on my own PC and also on the ISA-L conda package I manage (which uses an azure VM with visual studio installed). But it does not work on the github runner.

I tried installing with choco install visualstudio2019-workload-vctools but that requires a reboot and that does not work of course. Trying to ignore the reboot also does not work.

I tried using jom as a workaround, but that does not work with this particular makefile.

Is there any way to get nmake on the windows-latest runner?

**Comment by maxim-lobanov** [comment]
Hello @rhpvorderman , could you please try to add https://github.com/microsoft/setup-msbuild to your workflow?

**Comment by rhpvorderman** [comment]
@maxim-lobanov Wow, thanks for the ligthning fast reply.

I did what you suggested: https://github.com/pycompression/python-isal/actions/runs/631979863

setup-msbuild works fine for my Dynamic linking tests (that only need the C-compiler) but my static linking tests that need to build the isa-l project can't find nmake unfortunately.

**Comment by rhpvorderman** [comment]
Minimal reproducer here: https://github.com/rhpvorderman/test-nmake-github-actions

**Comment by maxim-lobanov** [comment]
Could you please try to use `seanmiddleditch/gha-setup-vsdevenv@master` instead of `microsoft/setup-msbuild@v1.0.2`.
With `gha-setup-vsdevenv`, it works for me: https://github.com/maxim-lobanov/test-repo/runs/2056598448?check_suite_focus=true

**Comment by rhpvorderman** [comment]
Thanks.
I checked it out on the minimal reproducer and that works.

On the python-isal project however it messes up the compiler vars, so python can not find the proper C compiler.

At least the root of the problem is not that nmake is not present. 
I will report a bug in the setup-msbuild project.

**Comment by rhpvorderman** [comment]
Turns out that the setup-msbuild project does not want to ad nmake. It is only for msbuild.

But luckily there is another action that works: https://github.com/ilammy/msvc-dev-cmd

I found it thanks to searching issues for nmake on msbuild.

Thanks for all your help @maxim-lobanov!
