### ISSUE TITLE
GitHub Actions failes with: "no space left on device"

### ISSUE THREAD

**Issue by Imipenem** [actions/virtual-environments#2875]
**Description**  
A clear and concise description of what the bug is, and why you consider it to be a bug.
I recently noticed that one of my GitHub workflows failed with the above mentioned error. 
Link to one of those runs: https://github.com/Imipenem/mypytest/runs/2060441074. 

i followed https://github.com/actions/virtual-environments/issues/709 and added:
`sudo rm -rf "/usr/local/share/boost"`
`sudo rm -rf "$AGENT_TOOLSDIRECTORY"`

But this lead to the error that I could not execute some python packages etc which is crucial for my workflow.

So I decided to remove some space consuming packages, but the error still persists. 

**Area for Triage**:  

**Question, Bug, or Feature?**:  

Bug

**Virtual environments affected**  
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [x] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Image version**

Image version where you are experiencing the issue.
Version: 20210302.0

**Expected behavior**  
A description of what you expected to happen.
The workflow should pass.

**Actual behavior**  
A description of what is actually happening.
Workflow keeps failing with running out of space

**Repro steps**  
A description with steps to reproduce the issue. If your have a public example or repo to share,
please provide the link.

1. https://github.com/Imipenem/mypytest/runs/2060441074 link for example WF run (accidently ran WF another time, so link is not the initial run)

Exact error:
`Error processing tar file(exit status 1): write /home/user/miniconda/envs/mypytest/lib/python3.9/site-packages/torch/lib/libtorch_cuda_cu.so: no space left on device
Error: exit status 1`

Any ideas @miketimofeev or others?

Thanks ;)

**Comment by al-cheb** [comment]
Hello, @Imipenem 
I think you can delete donet&ghc locations - https://github.com/actions/virtual-environments/issues/2840#issuecomment-790492173

**Comment by Imipenem** [comment]
Thanks @al-cheb will try this

**Comment by Imipenem** [comment]
@al-cheb So I tried running it with removing some packages running the following: 
```sudo apt-get remove -y azure-cli
  sudo apt-get remove -y ghc-9.0.1
  sudo apt-get remove -y ghc-8.10.4
  sudo apt-get remove -y adoptopenjdk-11-hotspot
  sudo rm -rf /usr/bin/firefox
  sudo rm -rf /usr/bin/google-chrome-stable
  ```
But I still get the error: WF run link is : https://github.com/Imipenem/mypytest/runs/2070428457
Any suggestions/ideas? ;)

**Comment by Imipenem** [comment]
This worked, thanks @al-cheb

**Comment by jlumbroso** [comment]
@Imipenem Having faced this siutation so many times, I decided to stop rewriting the wheel 😁 and wrote a GitHub Actions to do this properly:

https://github.com/marketplace/actions/free-disk-space-ubuntu

Open to suggestions. I noticed these lines:
```
sudo rm -rf "/usr/local/share/boost"
sudo rm -rf "$AGENT_TOOLSDIRECTORY"
```
but I am not sure what they remove?
