### ISSUE TITLE
Update/Add VS Enterprise 2019 16.9.0

### ISSUE THREAD

**Issue by sam20908** [actions/virtual-environments#2878]
**Tool information**
- Tool name: Visual Studio Enterprise 2019
- Tool license: Microsoft Software License
- Add or update? Update
- Desired version: 16.9.0
- Approximate size:
- If this is an add request:
  - Brief description of tool: 
  - URL for tool's homepage: 
  - Provide a basic test case to validate the tool's functionality: 

**Area for Triage**:

**Question, Bug, or Feature?**:

Feature

**Virtual environments affected**
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [x] Windows Server 2019

**Can this tool be installed during the build?**

**Tool installation time in runtime**

**Are you willing to submit a PR?**

**Comment by dibir-magomedsaygitov** [comment]
Hello everyone! Quick update: Windows 19 with VS Studio 16.9.0 on the board should be available on Monday. Friday is deployment freeze day, so we have to postpone it until Monday. I'll post an update message as soon as deployment is finished.

**Comment by dibir-magomedsaygitov** [comment]
Hello everyone! Windows 19 with VS Studio 16.9.0 on the board should be available now. In case of any questions feel free to contact us.
