### ISSUE TITLE
Add Microsoft.VisualStudio.Component.WinXP to Visual Studio

### ISSUE THREAD

**Issue by canihavesomecoffee** [actions/virtual-environments#288]
**Tool information**
- Tool name: Microsoft.VisualStudio.Component.WinXP
- Add or update? Add
- Desired version: The one that comes with Visual Studio
- Approximate size: 
- If this is an add request:
  - Brief description of tool: This is a component of Visual Studio that enables compiling C/C++ with XP compatibility
  - URL for tool's homepage: 

**Area for Triage**:

**Question, Bug, or Feature?**:
Feature

**Virtual environments affected**
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [x] Windows Server 2019

**Can this tool be installed during the build?**

Manual install at each run consumes ~14 minutes (refer to https://github.com/canihavesomecoffee/ccextractor/commit/821f20dc0e443e74155a8eee486957f1cecb51ff/checks?check_suite_id=408296775), so I believe it's more efficient to add this by default.

**Are you willing to submit a PR?**

Yes! I'll make the modification and open a PR.

**Comment by miketimofeev** [comment]
The component is presented on the image
https://github.com/actions/virtual-environments/releases/tag/win19%2F20200301.1
Closing the issue
