### ISSUE TITLE
cannot access environment variables passing it from GH-pages to ReactApp

### ISSUE THREAD

**Issue by nikonov91-dev** [actions/virtual-environments#2885]
I'm not sure that is right repo for this bug but
I'm trying to use environment variables in ReactApp deploying at Github-pages.

The variable is added through ***process.env*** and starts with ***REACT_APP*** as docs prescribe

```
export default class WeatherService {
  constructor() {
    this.API_BLOB_URL = process.env.REACT_APP_DEV_SERVER_URL + 'api/blob/';
  }
```

and ***.env*** created with ***GitHub Actions yml*** 

```
jobs:
  front-build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Store variables
        run: |
          cd front-app
          touch .env
          REACT_APP_DEV_SERVER_URL=${{ secrets.DEV_SERVER_URL }} >> .env

      - name: Build
        run: |
          cd front-app
          npm install
          npm run-script build
      - name: Deploy
          ...
```

but the app gets wrong values from GitHub Secrets.

 [![enter image description here][1]][1]

see the react-app at GH-pages receives a wrong object, not what i've passed ("username.azurewebsites.net/api"):

```
this.API_BLOB_URL = Object({
                NODE_ENV: "production",
                PUBLIC_URL: "/azure-flask-react",
                WDS_SOCKET_HOST: void 0,
                WDS_SOCKET_PATH: void 0,
                WDS_SOCKET_PORT: void 0,
                FAST_REFRESH: !0
            }).REACT_APP_DEV_SERVER_URL + "api/blob/"
```

At the same time when I build locally with ***npm run build***. React successfully replaces the env. variables

[![environmental variable replaced with react][2]][2]

As used to the purpose is to use different environment settings as api dev server in 
- *development (127.0.0.1:5000)* and 
- *production (username.cloudTech.com/api)*.

I've already tried to use ***env-cmd*** and ***dotenv*** lib but it neither worked

_________________________________________________
Note:

If I pass another variable*REACT_APP_FRONT_APP_URL=nikonov91-dev.github.io/azure-flask-react/'* npm script - it passes this variable successfully:
```
"scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "build:staging": "REACT_APP_FRONT_APP_URL=nikonov91-dev.github.io/azure-flask-react/ npm run build"
    ...
}
```

And then voila.

[![environment variable in deployed react app][3]][3]

_____________________________________

I've also tried
I've quoted my line:

```
run: |
  cd front-app
  touch .env
  echo 'REACT_APP_DEV_SERVER_URL=${{ secrets.DEV_SERVER_URL }}' >> .env
```
_____________________________________

I've tried also the answer of @peterevans
```
        run: |
          cd front-app
          echo "DEV_SERVER_URL=${{ secrets.DEV_SERVER_URL }}" >> $GITHUB_ENV
          touch .env
          echo "REACT_APP_DEV_SERVER_URL=${{ env.DEV_SERVER_URL }}" >> .env
```

but the value is still empty in JS ch:
[![enter image description here][4]][4]
instead of ```this.API_BLOB_URL="username.azurewebsites.net/api/blob/"```

  [1]: https://i.stack.imgur.com/7a1Ot.png
  [2]: https://i.stack.imgur.com/JbQ8F.jpg
  [3]: https://i.stack.imgur.com/piV7X.png
  [4]: https://i.stack.imgur.com/7wXSF.png

**Comment by nikonov91-dev** [comment]
Update:
One more thing I'm sure my approach is should work because if I hardcode the variable in **YML** it works as should and can be easily accessed in my Appv

```
 - name: Store variables
        run: |
          cd front-app
          touch .env
          echo "REACT_APP_DEV_SERVER_URL='https://first-py-app.azurewebsites.net/'" >> .env
```
and 
```this.API_BLOB_URL = process.env.REACT_APP_DEV_SERVER_URL + 'api/blob/';``` becomes 
```this.API_BLOB_URL = "https://first-py-app.azurewebsites.net/api/blob/"```

**Comment by LeonidLapshin** [comment]
Hey, @nikonov91-dev !
As far as I can see secret should work:
I have created a secret named DEV_SERVER_URL and containing 'https://first-py-app.azurewebsites.net/' (including quotes)
```
      - name: give it a try
        run: | 
          echo "lets try quotes"
          echo 'REACT_APP_DEV_SERVER_URL=${{ secrets.DEV_SERVER_URL }}' >> .env_quotes
          cat .env_quotes
          echo "==="
          echo "lets try double quotes"
          echo "REACT_APP_DEV_SERVER_URL=${{ secrets.DEV_SERVER_URL }}" >> .env_double_quotes
          cat .env_double_quotes
          echo "==="
          echo "lets try plaintext"
          echo "REACT_APP_DEV_SERVER_URL='https://first-py-app.azurewebsites.net/'" >> .env_plaintext
          cat .env_plaintext
```
the output is:
```
lets try quotes
REACT_APP_DEV_SERVER_URL=
https://first-py-app.azurewebsites.net/
===
lets try double quotes
REACT_APP_DEV_SERVER_URL=***
===
lets try plaintext
REACT_APP_DEV_SERVER_URL=***
```
so I guess that "REACT_APP_DEV_SERVER_URL=${{ secrets.DEV_SERVER_URL }}" is the right one. 
Could you please check it?

**Comment by nikonov91-dev** [comment]
Thanks for your hints!
I understood my issue:

it works but only for REPOSITORY SECRETS, but all the time I've tried to access ENVIRONMENT SECRETS.

I tried to access it with next syntax but I haven't found in Gh-Actions docs any solid answer how to use it.
```echo TEST_VAR=${{ secrets.TEST1 }}``` 
nor 
```echo TEST_VAR=${{  secrets.first-env.TEST1 }}``` 

Here is where I set the Environment Secrets

![Screenshot at Mar 14 23-06-05](https://user-images.githubusercontent.com/31586394/111084295-55334780-851a-11eb-999d-6c782f2f97f2.png)

and here I can access Repository Secrets only

![Screenshot at Mar 14 23-08-27](https://user-images.githubusercontent.com/31586394/111084300-56fd0b00-851a-11eb-87d6-e1fdb5b300eb.png)

**Comment by LeonidLapshin** [comment]
Hey, @nikonov91-dev 
Glad to hear that you can access them now successfully :)
I'll close the issue but if you have any questions, feel free to reopen it :)

**Comment by maxim-lobanov** [comment]
@nikonov91-dev , to access environments secrets, you should specify environment on job level: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idenvironment

See YAML example:
https://github.com/maxim-lobanov/test-repo/commit/af835258340c33747ecef91cc10bd242ca1e553e
The first job won't be able to access environment secrets. The second one will be.

**Comment by nikonov91-dev** [comment]
> @nikonov91-dev , to access environments secrets, you should specify environment on job level: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idenvironment
> 
> See YAML example:
> [maxim-lobanov/test-repo@af83525](https://github.com/maxim-lobanov/test-repo/commit/af835258340c33747ecef91cc10bd242ca1e553e)
> The first job won't be able to access environment secrets. The second one will be.

in provided YAML example the jobs are looks the same
```
jobs:
  job1:
    runs-on: 'ubuntu-latest'
    steps:
    - run: echo "${{ secrets.MY_VAR1 }}"
  job2:
    runs-on: 'ubuntu-latest'
    environment: test-env
    steps:
    - run: echo "${{ secrets.MY_VAR1 }}"
  ```
