### ISSUE TITLE
Node.js 15.x is failing when GitHub Action to test Node.js is triggered. 

### ISSUE THREAD

**Issue by andrewkirima** [actions/virtual-environments#2893]
**Description**  
Ubuntu-latest workflows will use Ubuntu-20.04 soon. For more details, see https://github.com/actions/virtual-environments/issues/1816 

**Area for Triage**:  

Area: JavaScript and Node.js
- valueFor: '**Area for Triage**'
  contains: 'JavaScript and Node.js'
  addLabels: ['Area: JavaScript and Node.js']

**Question, Bug, or Feature?**:  

Bug

**Virtual environments affected**  
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [x ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Image version**

  Environment: ubuntu-20.04
  Version: 20210302.0
  Included Software: https://github.com/actions/virtual-environments/blob/ubuntu20/20210302.0/images/linux/Ubuntu2004-README.md
  Image Release: https://github.com/actions/virtual-environments/releases/tag/ubuntu20%2F

**Expected behavior**  
For the test to pass. 

**Actual behavior**  
The test didn't pass. 

**Repro steps**  
A description with steps to reproduce the issue. If your have a public example or repo to share, please provide the link.

1. Push or pull to develop branch.
2. (Workflow begins) Build 10.x, 12.x, 14.x pass, but Build 15.x fails. 

Here is how the workflow for Build 15.x looks like: 
![image](https://user-images.githubusercontent.com/51974854/110626324-6fa1a580-8155-11eb-96e2-57d86aa8a3c4.png)

**Comment by maxim-lobanov** [comment]
`missing script: test` usually means that `package.json` file doesn't contain `test` command in `scripts` section.

**Comment by andrewkirima** [comment]
> `missing script: test` usually means that `package.json` file doesn't contain `test` command in `scripts` section.

I attempted to fix it and now all my test failed.

This is the last few lines of my scripts `section` in my `package.json` after my changes:

`    "ios": "expo start --ios",
    "web": "expo start --web",
    "eject": "expo eject"
    "test": "npm test"`

I added `"test: "npm test"` , so I'm assuming I did this wrong. I saw another example that showed `"test": "npm run unit"` is that correct?

**Comment by maxim-lobanov** [comment]
I am not sure because I am unfamiliar with your `package.json`. How do you run your tests locally and what is the results?

**Comment by andrewkirima** [comment]
I'm not running any test locally, these are GitHub actions configured to run once I push or create a PR in the remote repo. 

Here is the full picture of that part of the script: 
![image](https://user-images.githubusercontent.com/51974854/110738179-ade5a600-81e3-11eb-91bd-085fdb469b02.png)

Just noticed the little red highlighting but don't know what that means since it's in place properly. @maxim-lobanov

**Comment by andrewkirima** [comment]
I'm an idiot, I didn't see there was a comma right before, but I added that and changed where it says"npm test"` to the `"mocha"` framework.

**Comment by maxim-lobanov** [comment]
@andrewkirima, could you please run your tests on local box before and make sure that they pass locally. Debugging in CI is always complicated so the first step should be validating tests locally.

**Comment by andrewkirima** [comment]
I apologize I just read another article on this and realized I'm doing this backward. I'm trying to automate the test before making them. I don't know why but I thought this was just thought this was to make sure I didn't have errors with any other versions of node.js by itself. **First time creating my CI/CD pipeline and I'm doing it all on my own so big-time mistake.**
