### ISSUE TITLE
Pin runner

### ISSUE THREAD

**Issue by pixie79** [actions/virtual-environments#2894]
How do i pin the runner to a specific build in order to eliminate whether the runner or my changes have affected a build?

Lately I have noticed a few times as we have some of our repos set to automatically rebuild once a week where a working build stops building which no changes from us. The only change has been within the Ubuntu github runner. This makes it very difficult to release and test.

As such it would be good if we could do something like:

name: Publish Docker
on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 4 * * 0' # Weekly on Sundays at 04:00
jobs:
  test:
   runs-on: ubuntu-20.04:20210219.1

To allow us to pin to a known good version of the runner and then update once we have tested and are ready to each new version.

Thanks

Mark

**Comment by AlenaSviridenko** [comment]
Hi @pixie79, unfortunately, there is no possibility to pin exact runner version.
We have plans to support at least previous image versions, as a fallback in case of breaking changes, but no ETA for now.

**Comment by AlenaSviridenko** [comment]
I am closing this issue. Please, feel free to contact us in case of any questions.
Thank you.

**Comment by jamesmundy** [comment]
I know this issue is closed but IMO this feature is really essential. As an example our workflows broke last week due to a bug with the Azure CLI https://github.com/Azure/azure-cli/issues/32286 in version 2.8. All the windows runners have 2.8 pre-installed with this bug. It took quite some time to work out what was happening and now I have to write more custom code to handle this scenario and replace v2.8, there should be a way to freeze the runner version.

**Comment by erik-bershel** [comment]
We're aware of this community need. Unfortunately, we currently don't have the capacity to do so, but organizing the functionality is a priority. Until recently, it was architecturally blocked, but now there's a chance it can move forward. As soon as we have news on this topic, we'll make a separate announcement, as this functionality is truly in high demand.

**Comment by johnpetersjr** [comment]
Considering the latest Azure CLI / Bicep change that was made in the ubuntu latest image that broke several people's programs, I recommend you reopen this and make it a priority.

See: https://github.com/Azure/bicep/issues/18617

If we are to be held against our will to accept only ubuntu-latest, and breaking changes are introduced by Microsoft/GitHub, how can I deliver a solid solution using this platform?
