### ISSUE TITLE
GitHub Actions Not Respecting Trigger "On Create Tags"

### ISSUE THREAD

**Issue by yousefcodes** [actions/virtual-environments#2898]
**Description**  
I have two github workflows, one that fires when pushing a branch to master. And another that fires only when a tag is created. However, I am itermittently seeing my tags workflow fire, even when I push a branch. This doesn't always happen, it only happens ocassionally and generally it follows the tag creation rule. However, this is our production github workflow, and we simply cannot have a branch push cause that action to fire. What gives?

Dev:
```
on:
  push:
    branches:
      - master
```

Prod:
```
on:
  create:
    tags:
      - v*
```

**Area for Triage**:  

**Question, Bug, or Feature?**:  

Bug

**Virtual environments affected**  
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [x] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Image version**

Image version where you are experiencing the issue.

**Expected behavior**  
I would expect the on tag create action to not fire at all, unless I create a tag.

**Actual behavior**  
The on create tag github workflow is firing even when I push a branch.

**Repro steps**  
A description with steps to reproduce the issue. If your have a public example or repo to share,
please provide the link.

1. Create a github actions workflow that fires on:
```
on:
  create:
    tags:
      - v*
```
2. Push a branch up to the repo, don't create a tag. The workflow fires. This is itermittent and can't always be replicated. So I'm perplexed here. It happens often enough to be a problem.

**Comment by maxim-lobanov** [comment]
Should be in https://github.com/actions/runner since we maintain content of Hosted images only in this repository.
@thboop, @TingluoHuang could you please assist?

**Comment by yousefcodes** [comment]
Thanks - I created the issue here as well: https://github.com/actions/runner/issues/1007

**Comment by maxim-lobanov** [comment]
Cool, so I will close this one.
P.S. Sorry, don't have permissions to transfer the current issue
