### ISSUE TITLE
Update/Add postgresql-client

### ISSUE THREAD

**Issue by marton78** [actions/virtual-environments#29]
**Tool information**
- Tool name: postgresql-client
- Add or update? add
- Desired version: latest
- Approximate size: Package size: 913 kB | Installed size: 3128 kB
- If this is an add request:
  - Brief description of tool: CLI for PostgreSQL
  - URL for tool's homepage: https://www.postgresql.org/

**Virtual environments affected**
- [x] macOS 10.14
- [x] Ubuntu 16.04 LTS
- [x] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Can this tool be installed during the build?**

* Ubuntu:  apt-get. Takes about 1 minute.
* Mac: `brew install libpq` (this fixes also #12)

**Are you willing to submit a PR?**
Sure, but where are the sources?

**Comment by marton78** [comment]
Note that this is related to #12 but not a duplicate. Ideally both should be added, libpq-dev and postgresql-client.

**Comment by dmitry-shibanov** [comment]
Hello, postgresql-client was added to macos and linux images. If you get any issues with it, please feel free to reopen.
