### ISSUE TITLE
Update Docker to 3.2.0 or higher for BuildKit 

### ISSUE THREAD

**Issue by jjangga0214** [actions/virtual-environments#290]
**Tool information**
- Tool name: Docker
- Add or update? update
- Desired version: 3.2.0 or higher (See [release-notes](https://docs.docker.com/ee/ucp/release-notes/))
- Approximate size: 

As of 3.2.0, a feature called `BuildKit` can be used. This significantly boosts docker build time, which makes sense to use it in CI. 

**Area for Triage**: Docker

**Question, Bug, or Feature?**: Question

**Virtual environments affected**
- [ ] macOS 10.15
- [x] Ubuntu 16.04 LTS
- [x] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Can this tool be installed during the build?**

It's update of enterprise version of docker, so I don't know if people want to do it manually. 
So I think the best is for GitHub to update it by itself.  

**Are you willing to submit a PR?**

If applicable.

**Comment by alepauly** [comment]
Our installed version of moby might already support this, we just need to make sure the version maps to Docker 3.2.0 or later.

**Comment by m-minasyan** [comment]
Hi @jjangga0214. I made several fixes and we now correctly display the version as docker-moby, since we have docker-moby installed instead of docker. docker-moby has been updated to the latest version.

**Comment by jjangga0214** [comment]
@m-minasyan Thanks. Good to hear I can use `buildkit` in GitHub Action.
> we now correctly display the version as docker-moby
But what do you mean by this? `images/linux/Ubuntu1804-README.md` still shows the old version `3.0.10`.

I see `DocumentInstalledItem "Docker-Moby ($docker_version)"` in 
https://github.com/m-minasyan/virtual-environments/blob/f0e4d780060478aa6aa178ba7dc7335eb7ec0f1a/images/linux/scripts/installers/docker-moby.sh#L51, and guess the markdown file is auto-generated (on production VM creation phase?).

So does it mean docker has not updated yet, though your PR(#470) is merged?

**Comment by m-minasyan** [comment]
@jjangga0214 
Version `3.0.10` is the latest version of Docker-Moby. 
Please check if `buildkit` is working properly at the moment, because at the moment I think there should be no problems with it.

**Comment by m-minasyan** [comment]
@jjangga0214 
Documentation has been updated and Docker Moby has the latest version installed. If you have questions, you can re-open issue. Thank you.
