### ISSUE TITLE
Ubuntu 20.04 apt-get upgrade fails on msodbcsql17

### ISSUE THREAD

**Issue by jralls** [actions/virtual-environments#2904]
**Description**  
The command
```
Run sudo apt-get update -y
2  sudo apt-get update -y
3  sudo apt-get upgrade -y
4  shell: /usr/bin/bash -e {0}
5  env:
6    TZ: America/Los_Angeles
```
Fails because
```
252 Preparing to unpack .../28-msodbcsql17_17.7.2.1-1_amd64.deb ...
253 ERROR: The EULA was not accepted. Installation aborted.
254 dpkg: error processing archive /tmp/apt-dpkg-install-0rlLDF/28-msodbcsql17_17.7.2.1-1_amd64.deb (--unpack):
255 new msodbcsql17 package pre-installation script subprocess returned error exit status 1
```

**Area for Triage**:  
Packages

**Question, Bug, or Feature?**:  
Bug
**Virtual environments affected**  
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [X ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Image version**
```
Virtual Environment
7  Environment: ubuntu-20.04
8  Version: 20210302.0
9  Included Software: https://github.com/actions/virtual-environments/blob/ubuntu20/20210302.0/images/linux/Ubuntu2004-README.md
10  Image Release: https://github.com/actions/virtual-environments/releases/tag/ubuntu20%2F
```

Image version where you are experiencing the issue.

**Comment by al-cheb** [comment]
Hello, @jralls 
You should set `ACCEPT_EULA=Y` environment variable - https://docs.microsoft.com/en-us/sql/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server?view=sql-server-ver15

```
- run: |
    sudo apt-get update -y
    sudo ACCEPT_EULA=Y apt-get upgrade -y
```
![image](https://user-images.githubusercontent.com/47745270/110901360-492a6880-8315-11eb-8083-72d8499e490c.png)

The `apt-get upgrade` it too time consuming operation, it's our recommendation always invoke `sudo apt-get update -y` command and install only necessary packets.

**Comment by jralls** [comment]
Or maybe packages that need EULAs shouldn't be included in the VM by default.

Regardless, we've resolved this by following your second recommendation and updating only the packages that we depend on directly. Thanks.
