### ISSUE TITLE
Update Kind

### ISSUE THREAD

**Issue by jjangga0214** [actions/virtual-environments#292]
**Tool information**
- Tool name: Kind
- Add or update? Update
- Desired version: v0.7.x or higher
- Approximate size: 

Is there any specific reason not to update it? If not, I'd like to request update.

**Area for Triage**: Go

**Question, Bug, or Feature?**: Feature

**Virtual environments affected**
- [ ] macOS 10.15
- [x] Ubuntu 16.04 LTS
- [x] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Can this tool be installed during the build?** Yes

**Are you willing to submit a PR?**

Yes, if applicable.

**Comment by miketimofeev** [comment]
@jjangga0214 there is a PR already
https://github.com/actions/virtual-environments/pull/179

**Comment by miketimofeev** [comment]
@jjangga0214 PR has been merged and kind 0.7 will be rolled out in 1-2 weeks

**Comment by miketimofeev** [comment]
@jjangga0214 kind has been updated. Feel free to reopen the issue if you have any concerns.
