### ISSUE TITLE
GitHub Actions - Ratelimiting poping up suddenly after not having affected me before. 

### ISSUE THREAD

**Issue by FxllenCode** [actions/virtual-environments#2921]
**Description**  
Over the last week, I have noticed GitHub is consistently rate limiting me whereas this has never happened before. I have not made any changes to the actions workflow. There is not at all anything that should be causing this. You can find my repository that is affected here:

https://github.com/Status-Plus/StatusPlus

This is critical for me, it has completely broken my system as I rely on actions, it is simply disappointing that I am being rate limited now, considering this "rate limit" is clearly undocumented. 

**Area for Triage**:  
Deployment/Release

**Question, Bug, or Feature?**:  
Bug.

**Virtual environments affected**  
All.

**Expected behavior**  
GitHub actions should run as it does normally, like it did before. 

**Actual behavior**  
I am being rate limited to the point where my systems do not work at all now:

![WF5T7R4Lgt](https://user-images.githubusercontent.com/40151425/111054405-86d4e180-843a-11eb-99d9-83f90a829a35.gif)

You can see where this starting coming in place:

![bCEfdxqTiK](https://user-images.githubusercontent.com/40151425/111054422-a1a75600-843a-11eb-8bea-5590c9d9812f.png)

Here is the error message:

![chrome_wOuhOWNoIH](https://user-images.githubusercontent.com/40151425/111054452-c996b980-843a-11eb-85de-1f530f1fb45f.png)

From what I am reading, it says that the issue is related to missing authentication, however I don't see where this may have changed. I will look into that however.

**Repro steps**  
I'm really not sure how I can reproduce this, it just started randomly happening to me. Here is the repo:

https://github.com/Status-Plus/StatusPlus

Thank you.

**Comment by Darleev** [comment]
Hello @FxllenCode,
I found a well-documented page regarding API rate limits you can find it below
[Rate limit page](https://docs.github.com/en/rest/reference/rate-limit)
Also, we had a very similar request in the past, which possibly can be helpful to resolve the current issue:
https://github.com/actions/virtual-environments/issues/602
Additionally, I would like to provide you StackOverflow solution on how it is possible to increase the number of unauth/auth requests:
https://stackoverflow.com/questions/13394077/is-there-a-way-to-increase-the-api-rate-limit-or-to-bypass-it-altogether-for-git

Could you please check all information provided and let us know if we need to investigate the issue further?
We are looking forward to your reply.

**Comment by FxllenCode** [comment]
Hello @Darleev 

I've checked everything, (and to be fair I am no expert in GitHub actions,) it seems that the VM being used is Linux, so MacOS should not be the problem. I am not too sure why it just started happening recently, I did not make the requests happen any faster. (It says that all 1000 of the rate limit is being used by the actual number should be around 100...)

I do believe this is probably a bug relating to some update in the past couple of weeks as I can't find any reason I would suddenly start getting rate-limited. 

Thanks!

**Comment by Darleev** [comment]
@FxllenCode Could you please add a rate limit checker as per documentation?

```
curl \
  -H "Accept: application/vnd.github.v3+json" \
  https://api.github.com/rate_limit
```
It should return a number of remaining API connections for authenticated users.

**Comment by FxllenCode** [comment]
@Darleev unless I misunderstood, this already is here:

![chrome_ktpCsnJ5h6](https://user-images.githubusercontent.com/40151425/111076063-263cb780-84c1-11eb-8e13-75d244258e34.png)

I know for a fact there have not been 1000 calls of GitHub actions here-- thus why I think this is a problem related to the way GitHub actions is checking rate limits.

**Comment by maxim-lobanov** [comment]
@FxllenCode , on the quick look, it definitely looks like your actions exhaust GH Rate limits.
[graphs.yml](https://github.com/Status-Plus/StatusPlus/blob/master/.github/workflows/graphs.yml) is run every 10 minutes and based on the [logs](https://github.com/Status-Plus/StatusPlus/runs/2107351882?check_suite_focus=true) it does ~549 requests as minimum.
It means ~5490 requests per hours that is more than 5k limitation. In additional, you have other actions that do API requests too. 

I suggest temporary disabling graph.yml scheduling to see if other actions will work as expected.

**Comment by FxllenCode** [comment]
@maxim-lobanov gotcha. I will attempt this and see how it goes, thanks.

**Comment by maxim-lobanov** [comment]
@FxllenCode , Btw, looks like Rate limit is 1000 requests only [if you use system token](https://docs.github.com/en/rest/overview/resources-in-the-rest-api#rate-limiting):
> When using the built-in GITHUB_TOKEN in GitHub Actions, the rate limit is 1,000 requests per hour per repository. 

If you replace it to your own PAT, rate limit will be 5k requests per hour but you should understand security concern whether you trust actions that you use (upptime/uptime-monitor and others) or you probably can try generating PAT with minimal permissions.

**Comment by FxllenCode** [comment]
> @FxllenCode , Btw, looks like Rate limit is 1000 requests only [if you use system token](https://docs.github.com/en/rest/overview/resources-in-the-rest-api#rate-limiting):
> 
> > When using the built-in GITHUB_TOKEN in GitHub Actions, the rate limit is 1,000 requests per hour per repository.
> 
> If you replace it to your own PAT, rate limit will be 5k requests per hour but you should understand security concern whether you trust actions that you use (upptime/uptime-monitor and others) or you probably can try generating PAT with minimal permissions.

That's odd. I thought I was using PAT. I'll look into that, as well.

**Comment by maxim-lobanov** [comment]
@FxllenCode , I am not sure that you use own PAT.
In YAML file, you are referencing repository (system) token: https://github.com/Status-Plus/StatusPlus/blob/master/.github/workflows/graphs.yml#L32
According to the documentation: https://docs.github.com/en/actions/reference/authentication-in-a-workflow

If you would like to use own PAT, it should be placed in repository secrets to some variable like `GH_TOKEN` and reference this variable in YAML. As far as I know, `secrets.GITHUB_TOKEN` is referencing system token.

**Comment by maxim-lobanov** [comment]
Update:
I think if PAT is expired - it would fail on the first request (I am not sure honestly).
Also, if your own PAT is located in variable with name `GITHUB_TOKEN`, I suggest renaming it to be different from system token variable. I am not sure how this conflict is actually resolved.

**Comment by FxllenCode** [comment]
The PAT is named `GH_PAT`, so I am not too sure if that is a problem. 

As for upptime, I am just following the documentation here:

https://upptime.js.org/docs/get-started#add-repository-secrets

I just updated my PAT token as according to GitHub it was last used 2 weeks ago, when the problem started. For now, I'll assume the token got expired. (No idea why however). 

The only reason I assume this isn't an upptime problem and is a GitHub problem is because I have had zero issues for the last 3 months until about 2 weeks ago. 

It's important to note that PAT may not be expired because a couple of requests go through, not many however.

I have also slowed down Graphs CI significantly to once every 24 hours so that may also solve the issue.

I just wonder why this issue only popped up recently.

**Comment by maxim-lobanov** [comment]
@FxllenCode , `GH_PAT` is not used in your workflow.
It is not enough to just add `GH_PAT` in repository secrets, you should add it to YAML file.

```
- name: Generate graphs
  uses: upptime/uptime-monitor@v1.26.1
    with:
      command: "graphs"
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GH_PAT: ${{ secrets.GH_PAT }}
```

**Comment by FxllenCode** [comment]
I'll bring this up with the creator of upptime. Thanks for your help. I'll take a look and see if it fixes on my end, will close this for now as I assume you are correct about this. Thanks again!

**Comment by maxim-lobanov** [comment]
Cool, 
Btw, looks like official upptime example use correct way to pass own PAT: https://github.com/upptime/upptime/blob/master/.github/workflows/graphs.yml#L32
`GITHUB_TOKEN: ${{ secrets.GH_PAT }}` - map `GH_PAT` to `GITHUB_TOKEN`.

**Comment by FxllenCode** [comment]
> Cool,
> Btw, looks like official upptime example use correct way to pass own PAT: https://github.com/upptime/upptime/blob/master/.github/workflows/graphs.yml#L32
> `GITHUB_TOKEN: ${{ secrets.GH_PAT }}` - map `GH_PAT` to `GITHUB_TOKEN`.

It looks like the official upptime repo is incorrectly calling `GH_PAT` as `GITHUB_TOKEN`, probably from the latest update. Unfortunately this fix has to be done on their end as workflows are run and updated on that side. I'll have to manually rename `GH_PAT` to `GITHUB_TOKEN` for now as the code itself is looking for a secret called that:

![Code_M6xFkq1Gvc](https://user-images.githubusercontent.com/40151425/111080143-79b80100-84d3-11eb-9bb6-06d7b029e3d4.png)

Thanks!

**Comment by catthehacker** [comment]
`GITHUB_TOKEN` is automatic token secret that gives read/write access to repo and packages - https://docs.github.com/en/actions/reference/authentication-in-a-workflow#using-the-github_token-in-a-workflow
What you need to do is change `secrets.GITHUB_TOKEN` to `secrets.GH_PAT` in workflow and add your own PAT in secrets of that repo.
`upptime` repo is correctly calling everything. They use `env.GITHUB_TOKEN` for auth and it's user responsibility to assign valid auth token to that environment variable.
