### ISSUE TITLE
It looks like libffi6 is not being found during db migrate (postgres)

### ISSUE THREAD

**Issue by keithmgould** [actions/virtual-environments#2923]
**Description**  

The following failure just started.

On a Rails 6 app, during my action, when running DB migrate I get the following error (which works just fine for me locally on my MacBook Pro 10.15.7)...

Run bin/rails db:migrate
rails aborted!
LoadError: libffi.so.6: cannot open shared object file: No such file or directory - /home/runner/work/trade_tribe/trade_tribe/vendor/bundle/ruby/2.7.0/gems/ffi-1.14.2/lib/ffi_c.so
/home/runner/work/trade_tribe/trade_tribe/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.7.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
/home/runner/work/trade_tribe/trade_tribe/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.7.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
/home/runner/work/trade_tribe/trade_tribe/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.7.1/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/home/runner/work/trade_tribe/trade_tribe/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.7.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
/home/runner/work/trade_tribe/trade_tribe/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.7.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
/home/runner/work/trade_tribe/trade_tribe/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.3.5/lib/active_support/dependencies.rb:324:in `block in require'
/home/runner/work/trade_tribe/trade_tribe/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.3.5/lib/active_support/dependencies.rb:291:in `load_dependency'
/home/runner/work/trade_tribe/trade_tribe/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.3.5/lib/active_support/dependencies.rb:324:in `require'
/home/runner/work/trade_tribe/trade_tribe/vendor/bundle/ruby/2.7.0/gems/ffi-1.14.2/lib/ffi.rb:6:in `rescue in <main>'
/home/runner/work/trade_tribe/trade_tribe/vendor/bundle/ruby/2.7.0/gems/ffi-1.14.2/lib/ffi.rb:3:in `<main>'
/home/runner/work/trade_tribe/trade_tribe/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.7.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
/home/runner/work/trade_tribe/trade_tribe/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.7.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
/home/runner/work/trade_tribe/trade_tribe/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.7.1/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/home/runner/work/trade_tribe/trade_tribe/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.7.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
/home/runner/work/trade_tribe/trade_tribe/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.7.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
/home/runner/work/trade_tribe/trade_tribe/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.3.5/lib/active_support/dependencies.rb:324:in `block in require'
/home/runner/work/trade_tribe/trade_tribe/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.3.5/lib/active_support/dependencies.rb:291:in `load_dependency'
/home/runner/work/trade_tribe/trade_tribe/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.3.5/lib/active_support/dependencies.rb:324:in `require'
/home/runner/work/trade_tribe/trade_tribe/vendor/bundle/ruby/2.7.0/gems/sassc-2.4.0/lib/sassc/native.rb:3:in `<main>'
/home/runner/work/trade_tribe/trade_tribe/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.7.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
/home/runner/work/trade_tribe/trade_tribe/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.7.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
/home/runner/work/trade_tribe/trade_tribe/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.7.1/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/home/runner/work/trade_tribe/trade_tribe/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.7.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
/home/runner/work/trade_tribe/trade_tribe/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.7.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
/home/runner/work/trade_tribe/trade_tribe/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.3.5/lib/active_support/dependencies.rb:324:in `block in require'
/home/runner/work/trade_tribe/trade_tribe/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.3.5/lib/active_support/dependencies.rb:291:in `load_dependency'
/home/runner/work/trade_tribe/trade_tribe/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.3.5/lib/active_support/dependencies.rb:324:in `require'
/home/runner/work/trade_tribe/trade_tribe/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.7.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:53:in `require_relative'
/home/runner/work/trade_tribe/trade_tribe/vendor/bundle/ruby/2.7.0/gems/sassc-2.4.0/lib/sassc.rb:31:in `<main>'
/home/runner/work/trade_tribe/trade_tribe/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.7.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
/home/runner/work/trade_tribe/trade_tribe/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.7.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
/home/runner/work/trade_tribe/trade_tribe/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.7.1/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/home/runner/work/trade_tribe/trade_tribe/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.7.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
/home/runner/work/trade_tribe/trade_tribe/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.7.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
/home/runner/work/trade_tribe/trade_tribe/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.3.5/lib/active_support/dependencies.rb:324:in `block in require'
/home/runner/work/trade_tribe/trade_tribe/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.3.5/lib/active_support/dependencies.rb:291:in `load_dependency'
/home/runner/work/trade_tribe/trade_tribe/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.3.5/lib/active_support/dependencies.rb:324:in `require'
/home/runner/work/trade_tribe/trade_tribe/vendor/bundle/ruby/2.7.0/gems/sassc-rails-2.1.2/lib/sassc/rails.rb:5:in `<main>'
/home/runner/work/trade_tribe/trade_tribe/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.7.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
/home/runner/work/trade_tribe/trade_tribe/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.7.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
/home/runner/work/trade_tribe/trade_tribe/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.7.1/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/home/runner/work/trade_tribe/trade_tribe/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.7.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
/home/runner/work/trade_tribe/trade_tribe/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.7.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
/home/runner/work/trade_tribe/trade_tribe/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.3.5/lib/active_support/dependencies.rb:324:in `block in require'
/home/runner/work/trade_tribe/trade_tribe/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.3.5/lib/active_support/dependencies.rb:291:in `load_dependency'
/home/runner/work/trade_tribe/trade_tribe/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.3.5/lib/active_support/dependencies.rb:324:in `require'
/home/runner/work/trade_tribe/trade_tribe/vendor/bundle/ruby/2.7.0/gems/sass-rails-6.0.0/lib/sass-rails.rb:1:in `<main>'
/home/runner/work/trade_tribe/trade_tribe/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.7.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
/home/runner/work/trade_tribe/trade_tribe/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.7.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
/home/runner/work/trade_tribe/trade_tribe/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.7.1/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/home/runner/work/trade_tribe/trade_tribe/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.7.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
/home/runner/work/trade_tribe/trade_tribe/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.7.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
/home/runner/work/trade_tribe/trade_tribe/config/application.rb:20:in `<main>'
/home/runner/work/trade_tribe/trade_tribe/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.7.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
/home/runner/work/trade_tribe/trade_tribe/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.7.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
/home/runner/work/trade_tribe/trade_tribe/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.7.1/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/home/runner/work/trade_tribe/trade_tribe/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.7.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
/home/runner/work/trade_tribe/trade_tribe/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.7.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
/home/runner/work/trade_tribe/trade_tribe/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.7.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:53:in `require_relative'
/home/runner/work/trade_tribe/trade_tribe/Rakefile:6:in `<main>'
/home/runner/work/trade_tribe/trade_tribe/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.7.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:59:in `load'
/home/runner/work/trade_tribe/trade_tribe/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.7.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:59:in `load'
/home/runner/work/trade_tribe/trade_tribe/vendor/bundle/ruby/2.7.0/gems/railties-6.0.3.5/lib/rails/commands/rake/rake_command.rb:22:in `block in perform'
/home/runner/work/trade_tribe/trade_tribe/vendor/bundle/ruby/2.7.0/gems/railties-6.0.3.5/lib/rails/commands/rake/rake_command.rb:20:in `perform'
/home/runner/work/trade_tribe/trade_tribe/vendor/bundle/ruby/2.7.0/gems/railties-6.0.3.5/lib/rails/command.rb:48:in `invoke'
/home/runner/work/trade_tribe/trade_tribe/vendor/bundle/ruby/2.7.0/gems/railties-6.0.3.5/lib/rails/commands.rb:18:in `<main>'
/home/runner/work/trade_tribe/trade_tribe/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.7.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
/home/runner/work/trade_tribe/trade_tribe/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.7.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
/home/runner/work/trade_tribe/trade_tribe/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.7.1/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/home/runner/work/trade_tribe/trade_tribe/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.7.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
/home/runner/work/trade_tribe/trade_tribe/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.7.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
bin/rails:4:in `<main>'

Caused by:
LoadError: cannot load such file -- 2.7/ffi_c
/home/runner/work/trade_tribe/trade_tribe/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.7.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:34:in `require'
/home/runner/work/trade_tribe/trade_tribe/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.3.5/lib/active_support/dependencies.rb:324:in `block in require'
/home/runner/work/trade_tribe/trade_tribe/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.3.5/lib/active_support/dependencies.rb:291:in `load_dependency'
/home/runner/work/trade_tribe/trade_tribe/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.3.5/lib/active_support/dependencies.rb:324:in `require'
/home/runner/work/trade_tribe/trade_tribe/vendor/bundle/ruby/2.7.0/gems/ffi-1.14.2/lib/ffi.rb:4:in `<main>'
/home/runner/work/trade_tribe/trade_tribe/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.7.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
/home/runner/work/trade_tribe/trade_tribe/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.7.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
/home/runner/work/trade_tribe/trade_tribe/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.7.1/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/home/runner/work/trade_tribe/trade_tribe/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.7.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
/home/runner/work/trade_tribe/trade_tribe/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.7.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
/home/runner/work/trade_tribe/trade_tribe/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.3.5/lib/active_support/dependencies.rb:324:in `block in require'
/home/runner/work/trade_tribe/trade_tribe/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.3.5/lib/active_support/dependencies.rb:291:in `load_dependency'
/home/runner/work/trade_tribe/trade_tribe/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.3.5/lib/active_support/dependencies.rb:324:in `require'
/home/runner/work/trade_tribe/trade_tribe/vendor/bundle/ruby/2.7.0/gems/sassc-2.4.0/lib/sassc/native.rb:3:in `<main>'
/home/runner/work/trade_tribe/trade_tribe/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.7.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
/home/runner/work/trade_tribe/trade_tribe/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.7.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
/home/runner/work/trade_tribe/trade_tribe/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.7.1/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/home/runner/work/trade_tribe/trade_tribe/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.7.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
/home/runner/work/trade_tribe/trade_tribe/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.7.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
/home/runner/work/trade_tribe/trade_tribe/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.3.5/lib/active_support/dependencies.rb:324:in `block in require'
/home/runner/work/trade_tribe/trade_tribe/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.3.5/lib/active_support/dependencies.rb:291:in `load_dependency'
/home/runner/work/trade_tribe/trade_tribe/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.3.5/lib/active_support/dependencies.rb:324:in `require'
/home/runner/work/trade_tribe/trade_tribe/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.7.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:53:in `require_relative'
/home/runner/work/trade_tribe/trade_tribe/vendor/bundle/ruby/2.7.0/gems/sassc-2.4.0/lib/sassc.rb:31:in `<main>'
/home/runner/work/trade_tribe/trade_tribe/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.7.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
/home/runner/work/trade_tribe/trade_tribe/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.7.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
/home/runner/work/trade_tribe/trade_tribe/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.7.1/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/home/runner/work/trade_tribe/trade_tribe/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.7.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
/home/runner/work/trade_tribe/trade_tribe/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.7.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
/home/runner/work/trade_tribe/trade_tribe/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.3.5/lib/active_support/dependencies.rb:324:in `block in require'
/home/runner/work/trade_tribe/trade_tribe/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.3.5/lib/active_support/dependencies.rb:291:in `load_dependency'
/home/runner/work/trade_tribe/trade_tribe/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.3.5/lib/active_support/dependencies.rb:324:in `require'
/home/runner/work/trade_tribe/trade_tribe/vendor/bundle/ruby/2.7.0/gems/sassc-rails-2.1.2/lib/sassc/rails.rb:5:in `<main>'
/home/runner/work/trade_tribe/trade_tribe/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.7.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
/home/runner/work/trade_tribe/trade_tribe/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.7.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
/home/runner/work/trade_tribe/trade_tribe/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.7.1/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/home/runner/work/trade_tribe/trade_tribe/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.7.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
/home/runner/work/trade_tribe/trade_tribe/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.7.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
/home/runner/work/trade_tribe/trade_tribe/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.3.5/lib/active_support/dependencies.rb:324:in `block in require'
/home/runner/work/trade_tribe/trade_tribe/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.3.5/lib/active_support/dependencies.rb:291:in `load_dependency'
/home/runner/work/trade_tribe/trade_tribe/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.3.5/lib/active_support/dependencies.rb:324:in `require'
/home/runner/work/trade_tribe/trade_tribe/vendor/bundle/ruby/2.7.0/gems/sass-rails-6.0.0/lib/sass-rails.rb:1:in `<main>'
/home/runner/work/trade_tribe/trade_tribe/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.7.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
/home/runner/work/trade_tribe/trade_tribe/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.7.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
/home/runner/work/trade_tribe/trade_tribe/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.7.1/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/home/runner/work/trade_tribe/trade_tribe/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.7.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
/home/runner/work/trade_tribe/trade_tribe/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.7.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
/home/runner/work/trade_tribe/trade_tribe/config/application.rb:20:in `<main>'
/home/runner/work/trade_tribe/trade_tribe/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.7.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
/home/runner/work/trade_tribe/trade_tribe/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.7.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
/home/runner/work/trade_tribe/trade_tribe/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.7.1/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/home/runner/work/trade_tribe/trade_tribe/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.7.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
/home/runner/work/trade_tribe/trade_tribe/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.7.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
/home/runner/work/trade_tribe/trade_tribe/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.7.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:53:in `require_relative'
/home/runner/work/trade_tribe/trade_tribe/Rakefile:6:in `<main>'
/home/runner/work/trade_tribe/trade_tribe/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.7.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:59:in `load'
/home/runner/work/trade_tribe/trade_tribe/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.7.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:59:in `load'
/home/runner/work/trade_tribe/trade_tribe/vendor/bundle/ruby/2.7.0/gems/railties-6.0.3.5/lib/rails/commands/rake/rake_command.rb:22:in `block in perform'
/home/runner/work/trade_tribe/trade_tribe/vendor/bundle/ruby/2.7.0/gems/railties-6.0.3.5/lib/rails/commands/rake/rake_command.rb:20:in `perform'
/home/runner/work/trade_tribe/trade_tribe/vendor/bundle/ruby/2.7.0/gems/railties-6.0.3.5/lib/rails/command.rb:48:in `invoke'
/home/runner/work/trade_tribe/trade_tribe/vendor/bundle/ruby/2.7.0/gems/railties-6.0.3.5/lib/rails/commands.rb:18:in `<main>'
/home/runner/work/trade_tribe/trade_tribe/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.7.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
/home/runner/work/trade_tribe/trade_tribe/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.7.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
/home/runner/work/trade_tribe/trade_tribe/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.7.1/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/home/runner/work/trade_tribe/trade_tribe/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.7.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
/home/runner/work/trade_tribe/trade_tribe/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.7.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
bin/rails:4:in `<main>'
(See full trace by running task with --trace)
Error: Process completed with exit code 1.

**Comment by dibir-magomedsaygitov** [comment]
Hello @keithmgould. Could you please provide us minimal repro steps to speed up investigation process.

**Comment by nilesh-n** [comment]
Hi. We ran into a similar issue with a rails 6 app that we're running. We narrowed down the issue to be `ubuntu:latest` being upgraded to 20.04 in our github action. It seems that ubuntu 20.04 upgraded from `libffi6` to `libffi7`, and this is what caused the issue.

To fix the issue, we busted the bundle cache in our github action so that the gems had to reinstall and the necessary gems recomplied with `libffi7`.

We changed our cache key from v2 to v3 in the following step in our github action to clear our cache:

```yaml
    - name: Cache Ruby dependencies
      uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: bundle-v3-${{ hashFiles('.ruby-version') }}-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          bundle-v3-${{ hashFiles('.ruby-version') }}-
```

Hope this helps.

**Comment by maxim-lobanov** [comment]
Ubuntu 18.04 contains `libffi6` by default.
Ubuntu 20.04 contains `libffi7` by default.

Related investigation: https://github.com/actions/virtual-environments/issues/2823#issuecomment-789485737
The simplest way to resolve the issue will be switching to Ubuntu 18.04

**Comment by keithmgould** [comment]
Gotcha, thank you.
