### ISSUE TITLE
Ubuntu: Document requirement to always run "apt-get update" before install

### ISSUE THREAD

**Issue by marc-hb** [actions/virtual-environments#2924]
**Description**  

This is a documentation gap/"bug".

As explained in #1757, virtual environments are carefully version controlled to make test results reliable and predictable. They do not include the very latest software as soon as it is released by Ubuntu but only some time later after some image validation first.

As an unfortunate side-effect, the apt package indexes in virtual environments can point at old (and insecure?) package dependencies that have been removed by Ubuntu, which means `apt-get install` commands can fail. See several examples in #1757

The fix/workaround is of course that everyone must run `apt-get update` before any `apt-get install`, however this is not documented and should be, hence this issue.

It is IMHO important to document this `apt-get update` requirement because it's not obvious:

- Many (most?) other Ubuntu installations run `apt-get update` in the background and do not have this requirement.

- It's a bit confusing because virtual environments _are_ updated from time to time, just more slowly. This makes `apt-get install` failures unpredictable, they come and go for no obvious reason. See examples in #1757 

- Each worflow of each project running `apt-get update` takes some time (~10s?) and is a massively duplicated effort that would be much more efficient at the image level - without affecting test results predictability. `apt-get update` has no effect on test results unless you actually `apt-get install` something (and then you can forget about determinism anyway).

**Area for Triage**: 
Containers or Packages?
( See https://github.com/actions/virtual-environments/tree/main/triage-rules.yml for areas)

**Question, Bug, or Feature?**:  
Documentation gap/"bug"?

(Choose "Question", "Bug", or "Feature" )

**Virtual environments affected**  
- [ x ] Ubuntu 16.04
- [ x ] Ubuntu 18.04
- [ x ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Image version**

Version: 20210309.1

**Expected behavior**  
More documentation.

**Actual behavior**  
Less documentation.

**Repro steps**  
1. Step 1 Read documentation
2. Step 2 Do not find information in documentation

**Comment by maxim-lobanov** [comment]
Just an update, we are working with docs team on updating GH documentation.

**Comment by maxim-lobanov** [comment]
https://docs.github.com/en/actions/using-github-hosted-runners/customizing-github-hosted-runners

**Comment by marc-hb** [comment]
Perfect, thank you @maxim-lobanov
