### ISSUE TITLE
Issue resizing MacOS runner screen size

### ISSUE THREAD

**Issue by hfaulds** [actions/virtual-environments#2933]
**Description**  

Setting the resolution of a MacOS runner to `1080x2160` results in a resolution of `1080x1600`

**Area for Triage**:  
Scripting and command line

**Question, Bug, or Feature?**:  
Bug/Question

**Virtual environments affected**  
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [x] macOS 10.15
- [ ] macOS 11.0
  maybe?
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Image version**
   Version: 20210307.1

**Expected behavior**  
```
Requested resolution: 1080x2160
Effective resolution: 1080x2160
```

**Actual behavior**  

The ```"/Library/Application Support/VMware Tools/vmware-resolutionSet" 1080 2160``` shows the following output:
```
Requested resolution: 1080x2160
Effective resolution: 1080x1600
```

**Repro steps**  

Reproduced in https://github.com/cpintado-org/screen-size/runs/2078159736?check_suite_focus=true#step:3:5

The https://github.com/cpintado-org/screen-size/blob/main/.github/workflows/blank.yml workflow uses the same steps to change the screen size we suggested to the customer based in https://github.com/actions/virtual-environments/issues/393#issuecomment-619569769.

**Comment by miketimofeev** [comment]
@hfaulds Unfortunately, it's not possible to set the vertical resolution to more than 1600px due to technical limitations. The maximum screen resolution is 2560x1600

**Comment by hfaulds** [comment]
Thanks @miketimofeev
