### ISSUE TITLE
Ability to change the display resolution on Windows

### ISSUE THREAD

**Issue by AndrewSazonov** [actions/virtual-environments#2935]
**Description**  
Is there a way to change the default display resolution (1024x768) on a Windows runner? Something similar to macOS: https://github.com/actions/virtual-environments/issues/393 

**Area for Triage**:  
Scripting and command line

**Question, Bug, or Feature?**:  
Question

**Virtual environments affected**  
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11.0
- [x] Windows Server 2016 R2
- [x] Windows Server 2019

**Comment by miketimofeev** [comment]
Hi @AndrewSazonov!
Could you try the following PowerShell command? Does it work for you?
`Set-DisplayResolution -Width 1920 -Height 1080 -Force`

**Comment by AndrewSazonov** [comment]
Yes, it works with 1920x1080, thank you! I have tried this before, but unfortunately with a resolution that is not supported (1440x1080).

**Comment by miketimofeev** [comment]
@AndrewSazonov yes, unfortunately, not all the combinations are possible. I'm going to close the issue, but please feel free to contact us if you have any concerns or questions.
Thank you!

**Comment by Matenko** [comment]
I'm just curious to what resolutions are possible? What would be the max resolution supported?

**Comment by miketimofeev** [comment]
@Matenko we haven't investigated it, but it seems that the max possible resolution is 1080p — 1920x1080.

**Comment by Matenko** [comment]
Awesome. Thank you.

**Comment by kayazlan93** [comment]
@AndrewSazonov hi Andrew, im new on this, how is it to configure the screen size for windows runner on github action. do i need to write it on yml file ?
