### ISSUE TITLE
Update/Add RC.exe

### ISSUE THREAD

**Issue by agersant** [actions/virtual-environments#294]
**Tool information**
- Tool name: Resource Compiler
- Add or update? Add
- Desired version: Any
- Approximate size:  75kB
- If this is an add request:
  - Brief description of tool: The Microsoft Windows Resource Compiler (RC) is a tool used in building Windows-based applications. Most common use case it to compile graphical resources like icons to be used in an application.
  - URL for tool's homepage: https://docs.microsoft.com/en-us/windows/win32/menurc/resource-compiler

**Area for Triage**:
Artifacts

**Question, Bug, or Feature?**:
Feature

**Virtual environments affected**
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [x] Windows Server 2016 R2
- [x] Windows Server 2019

**Can this tool be installed during the build?**
Not easily

**Are you willing to submit a PR?**
With guidance on the work required

I see [here](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/software-installed-on-github-hosted-runners#windows-server-2019) that the Windows SDK is already installed but RC does not seem to be in the Path when running commands. Is there an environment variable to access binaries installed as part of the Windows SDK?

**Comment by agersant** [comment]
It turns out the tool is actually there and I was able to reference it by its absolute path at `"C:\Program Files (x86)\Windows Kits\10\bin\10.0.18362.0\x64" RC.exe`.

I think an environment variable pointing to the binaries for the most recent version of the SDK in the image would be useful to future proof this.

**Comment by fakufaku** [comment]
I think I am running into a related issue. My workflow compiles a C++ extension for a python package and fails in the last step when unable to find RC.exe for linkage.

Here is the link to the failed workflow:
https://github.com/LCAV/pyroomacoustics/runs/400344485

And here is the error message:
```
2020-01-21T07:44:27.8854075Z Finished generating code
2020-01-21T07:44:28.1471429Z LINK : fatal error LNK1158: cannot run 'rc.exe'
2020-01-21T07:44:28.1774456Z C:\hostedtoolcache\windows\Python\3.5.4\x64\lib\site-packages\Cython\Compiler\Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: D:\a\pyroomacoustics\pyroomacoustics\pyroomacoustics\build_rir.pyx
2020-01-21T07:44:28.1775091Z tree = Parsing.p_module(s, pxd, full_module_name)
2020-01-21T07:44:28.1775769Z error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\link.exe' failed with exit status 1158
2020-01-21T07:44:28.5229664Z ##[error]Process completed with exit code 1.
2020-01-21T07:44:28.5257501Z Cleaning up orphan processes
```

Here is what seems to be related issues on stackoverflow: 
* https://stackoverflow.com/questions/14372706/visual-studio-cant-build-due-to-rc-exe?newreg=f00ac10c2a4448ceb438f258e5c229a4
* https://stackoverflow.com/questions/43858836/python-installing-clarifai-vs14-0-link-exe-failed-with-exit-status-1158

**Comment by kyamagu** [comment]
For windows server 2019, I could workaround by adding the following.

```bash
echo "::add-path::/c/Program Files (x86)/Windows Kits/10/bin/10.0.18362.0/x64"
```

**Comment by kyamagu** [comment]
For Windows Server 2019, adding the following fixed the issue.

```sh
echo "::add-path::C:\Program Files (x86)\Windows Kits\10\bin\10.0.18362.0\x64"
```

**Comment by fakufaku** [comment]
@kyamagu Thank you very much. This fixed the issue for me too.

**Comment by thejoebourneidentity** [comment]
We can probably add an environment variable that points to the latest SDK.

**Comment by al-cheb** [comment]
Hello, @agersant 

Visual Studio team doesn't support  being in fixed locations. Running vsdevcmd.bat to set up your dev PATH is what they recommend.

https://github.com/microsoft/vswhere/wiki/Start-Developer-Command-Prompt


Workaround to use the VsDevCmd.bat file sets the appropriate environment variables to enable command-line builds:

```
function Invoke-VSDevEnvironment {
	$vswhere = "${env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer\vswhere.exe"
    $installationPath = & $vswhere -prerelease -legacy -latest -property installationPath
    $Command = Join-Path $installationPath "Common7\Tools\vsdevcmd.bat"
	& "${env:COMSPEC}" /s /c "`"$Command`" -no_logo && set" | Foreach-Object {
        if ($_ -match '^([^=]+)=(.*)') {
            [System.Environment]::SetEnvironmentVariable($matches[1], $matches[2])
        }
    }
}
```

Example:

```
jobs:
  build:
    runs-on: [windows-latest]
    steps:
      - name: RC.exe
        run: |
          function Invoke-VSDevEnvironment {
            $vswhere = "${env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer\vswhere.exe"
              $installationPath = & $vswhere -prerelease -legacy -latest -property installationPath
              $Command = Join-Path $installationPath "Common7\Tools\vsdevcmd.bat"
            & "${env:COMSPEC}" /s /c "`"$Command`" -no_logo && set" | Foreach-Object {
                  if ($_ -match '^([^=]+)=(.*)') {
                      [System.Environment]::SetEnvironmentVariable($matches[1], $matches[2])
                  }
              }
          }
          Invoke-VSDevEnvironment
          Get-Command rc.exe | Format-Table -AutoSize
```

GitHub Windows Server 2019:
![github - Copy](https://user-images.githubusercontent.com/47745270/74814611-b9c8a680-5308-11ea-963a-74be773e929c.JPG)


Azure Devops Windows Server 2016:
![vsts - Copy](https://user-images.githubusercontent.com/47745270/74814628-c220e180-5308-11ea-81de-ed56ee09c108.JPG)

**Comment by agersant** [comment]
Thanks a lot. I wasn't aware of vswhere.exe and this example is very useful.
