### ISSUE TITLE
Install sbt without depending on Bintray

### ISSUE THREAD

**Issue by yutannihilation** [actions/virtual-environments#2944]
Currently, sbt is installed from PPA that is on Bintray, which is announced to start to fade away on April 12th, 2021, and become completely unavailable on May 1st, 2021 (c.f., <https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/>).

https://github.com/actions/virtual-environments/blob/875891b86b39572d2c947197c4222d4d62d38d39/images/linux/scripts/installers/sbt.sh#L9

I know there's no alternative PPA and all we can do might be just to wait, but I'm filing this to make sure the problem will be addressed until the day. Note that, it's not only Scala related projects that this problem matters but also all users because `apt-get update` fails if the PPA is not available (c.f., <https://github.com/actions/runner/issues/932>).

**Tool information**
- Tool name: sbt
- Tool license: 
- Add or update?: update
- Desired version: any
- Approximate size: 

**Area for Triage**:

Scala

**Question, Bug, or Feature?**:
Feature

**Virtual environments affected**
- [x] Ubuntu 16.04
- [x] Ubuntu 18.04
- [x] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Can this tool be installed during the build?**

**Tool installation time in runtime**

**Are you willing to submit a PR?**

I think I cannot as I know almost nothing about sbt or Scala.

**Comment by maxim-lobanov** [comment]
@yutannihilation , thank you for the report. Moved to the backlog to take a look.

**Comment by yutannihilation** [comment]
Thanks for taking a look!

**Comment by miketimofeev** [comment]
@yutannihilation thanks for bringing this up! We've reworked the installation to get rid of bintray. The new image will be deployed in 2 weeks.

**Comment by yutannihilation** [comment]
Cool, thanks for fixing quickly!

**Comment by miketimofeev** [comment]
@yutannihilation the new images were deployed! I'm going to close the issue, thanks again for your suggestion!

**Comment by yutannihilation** [comment]
:tada:

**Comment by modernptz** [comment]
The documentation still not updated https://www.scala-sbt.org/1.x/docs/Installing-sbt-on-Linux.html

**Comment by yutannihilation** [comment]
As the doc suggests, DEB package will be provided eventually, but I believe it stays legal to install sbt directly without DEB. Any concerns?

> DEB package is officially supported by sbt. (sbt 1.4.8 and onwards do not have DEB packaging yet due to Bintray going away)
