### ISSUE TITLE
Microsoft hosted agent builds are failing on macos-latest 20210314.1

### ISSUE THREAD

**Issue by keerthinathganjam** [actions/virtual-environments#2945]
**Description**  
MTOUCH : error MT5210: Native linking failed, undefined symbol: _CheckTokenMembership. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in. [/Users/runner/work/1/s/Source/ProarcMobile.iOS/ProarcMobile.iOS.csproj]

**Area for Triage**:  
Apple

**Bug**:  

**Virtual environments affected**  
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [* ] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Image version**

Image version where you are experiencing the issue.
20210314.1

was passing till the image 20210307.1

**Expected behavior**  
build to be passed

**Actual behavior**  
failing cos of below error

 MTOUCH : error MT5210: Native linking failed, undefined symbol: _CheckTokenMembership. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in. [/Users/runner/work/1/s/Source/ProarcMobile.iOS/ProarcMobile.iOS.csproj]
  MTOUCH : error MT5210: Native linking failed, undefined symbol: _CloseHandle. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in. [/Users/runner/work/1/s/Source/ProarcMobile.iOS/ProarcMobile.iOS.csproj]
  MTOUCH : error MT5210: Native linking failed, undefined symbol: _DuplicateHandle. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in. [/Users/runner/work/1/s/Source/ProarcMobile.iOS/ProarcMobile.iOS.csproj]
  MTOUCH : error MT5210: Native linking failed, undefined symbol: _DuplicateTokenEx. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in. [/Users/runner/work/1/s/Source/ProarcMobile.iOS/ProarcMobile.iOS.csproj]
  MTOUCH : error MT5210: Native linking failed, undefined symbol: _GetCurrentProcess. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in. [/Users/runner/work/1/s/Source/ProarcMobile.iOS/ProarcMobile.iOS.csproj]
  MTOUCH : error MT5210: Native linking failed, undefined symbol: _GetCurrentThread. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in. [/Users/runner/work/1/s/Source/ProarcMobile.iOS/ProarcMobile.iOS.csproj]
  MTOUCH : error MT5210: Native linking failed, undefined symbol: _GetTokenInformation. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in. [/Users/runner/work/1/s/Source/ProarcMobile.iOS/ProarcMobile.iOS.csproj]
  MTOUCH : error MT5210: Native linking failed, undefined symbol: _ImpersonateLoggedOnUser. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in. [/Users/runner/work/1/s/Source/ProarcMobile.iOS/ProarcMobile.iOS.csproj]
  MTOUCH : error MT5210: Native linking failed, undefined symbol: _LocalAlloc. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in. [/Users/runner/work/1/s/Source/ProarcMobile.iOS/ProarcMobile.iOS.csproj]
  MTOUCH : error MT5210: Native linking failed, undefined symbol: _LocalFree. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in. [/Users/runner/work/1/s/Source/ProarcMobile.iOS/ProarcMobile.iOS.csproj]
  MTOUCH : error MT5210: Native linking failed, undefined symbol: _LsaClose. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in. [/Users/runner/work/1/s/Source/ProarcMobile.iOS/ProarcMobile.iOS.csproj]
  MTOUCH : error MT5210: Native linking failed, undefined symbol: _LsaFreeMemory. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in. [/Users/runner/work/1/s/Source/ProarcMobile.iOS/ProarcMobile.iOS.csproj]
  MTOUCH : error MT5210: Native linking failed, undefined symbol: _LsaFreeReturnBuffer. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in. [/Users/runner/work/1/s/Source/ProarcMobile.iOS/ProarcMobile.iOS.csproj]
  MTOUCH : error MT5210: Native linking failed, undefined symbol: _LsaGetLogonSessionData. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in. [/Users/runner/work/1/s/Source/ProarcMobile.iOS/ProarcMobile.iOS.csproj]
  MTOUCH : error MT5210: Native linking failed, undefined symbol: _LsaLookupNames2. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in. [/Users/runner/work/1/s/Source/ProarcMobile.iOS/ProarcMobile.iOS.csproj]
  MTOUCH : error MT5210: Native linking failed, undefined symbol: _LsaLookupSids. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in. [/Users/runner/work/1/s/Source/ProarcMobile.iOS/ProarcMobile.iOS.csproj]
  MTOUCH : error MT5210: Native linking failed, undefined symbol: _LsaOpenPolicy. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in. [/Users/runner/work/1/s/Source/ProarcMobile.iOS/ProarcMobile.iOS.csproj]
  MTOUCH : error MT5210: Native linking failed, undefined symbol: _OpenProcessToken. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in. [/Users/runner/work/1/s/Source/ProarcMobile.iOS/ProarcMobile.iOS.csproj]
  MTOUCH : error MT5210: Native linking failed, undefined symbol: _OpenThreadToken. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in. [/Users/runner/work/1/s/Source/ProarcMobile.iOS/ProarcMobile.iOS.csproj]
  MTOUCH : error MT5210: Native linking failed, undefined symbol: _RevertToSelf. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in. [/Users/runner/work/1/s/Source/ProarcMobile.iOS/ProarcMobile.iOS.csproj]
  MTOUCH : error MT5210: Native linking failed, undefined symbol: _RtlNtStatusToDosError. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in. [/Users/runner/work/1/s/Source/ProarcMobile.iOS/ProarcMobile.iOS.csproj]
  MTOUCH : error MT5202: Native linking failed. Please review the build log. [/Users/runner/work/1/s/Source/ProarcMobile.iOS/ProarcMobile.iOS.csproj]
  clang : error : linker command failed with exit code 1 (use -v to see invocation) [/Users/runner/work/1/s/Source/ProarcMobile.iOS/ProarcMobile.iOS.csproj]

**Comment by keerthinathganjam** [comment]
is it possible to specify a specific image version similar to choosing the image label in the yaml file

**Comment by dibir-magomedsaygitov** [comment]
Hello @keerthinathganjam. Thank you for your report. Could you please provide us minimal repro steps to speed up investigation process?

**Comment by JRallee** [comment]
> Hello @keerthinathganjam. Thank you for your report. Could you please provide us minimal repro steps to speed up investigation process?

Is it possible to specify a particular image to be used?
Example, 20210307.1

**Comment by catthehacker** [comment]
@JRallee it's not possible to choose image version.

**Comment by nikita-bykov** [comment]
Hello @keerthinathganjam.
As @catthehacker mentioned before you cannot choose a specific image version in your yaml file.
Previously we've updated our Xamarin iOS from `14.10` to `14.14` version. Most likely, this may have affected your builds. To see available Xamarin versions follow to our [toolset for macOS 10.15](https://github.com/Darleev/virtual-environments/blob/b3dcf7fbd7e278e905af26de388bf3cdff7a7ced/images/macos/toolsets/toolset-10.15.json). 
You can try the previous Xamarin tools bundle with symlink `6_12_6` (contains Xamarin iOS `14.10`) by running this command: 
```
/bin/bash -c "sudo $AGENT_HOMEDIRECTORY/scripts/select-xamarin-sdk.sh 6_12_6"
```
Mentioned in this documentation: https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops&tabs=yaml#xamarin
Please let us know if you have any questions.

**Comment by keerthinathganjam** [comment]
Thanks @nikita-bykov  this solved our issue, i had tried this earlier but coudnt get to the exact version no you mentioned, is there any documentation to know which version of xamarin sdk we need to use for which version of xamarin iOS

**Comment by nikita-bykov** [comment]
Unfortunately, there is no such documentation now, but soon we will update our documentation for Xamarin to be more informative. I'll close this issue, but if you have any questions, feel free to ask us.
Thank you @keerthinathganjam!
