### ISSUE TITLE
Unable to install gcc-multilib on Ubuntu 16.04

### ISSUE THREAD

**Issue by igsilya** [actions/virtual-environments#2946]
**Description**  
Unable to install gcc-multilib on Ubuntu 16.04:
`gcc-multilib : Depends: gcc-5-multilib (>= 5.3.1-3~) but it is not going to be installed`

**Area for Triage**:  
Packages

**Question, Bug, or Feature?**:  
Bug

**Virtual environments affected**  
- [x] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Image version**

20210309.1

**Expected behavior**  
gcc-multilib successfully installed

**Actual behavior**  
`gcc-multilib : Depends: gcc-5-multilib (>= 5.3.1-3~) but it is not going to be installed`

**Repro steps**  
Try to install gcc-multilib with apt.
Failed job example: https://github.com/igsilya/ovs/runs/2122751650?check_suite_focus=true#step:4:39

**Comment by al-cheb** [comment]
Duplicate https://github.com/actions/virtual-environments/issues/2917 .
