### ISSUE TITLE
[regression] Unable to install "jo" brew package

### ISSUE THREAD

**Issue by speedym** [actions/virtual-environments#2947]
**Description**  
"brew install jo" command fails on macOS 10.15 instances. This used to work a few days ago so it's very likely a regression.

**Area for Triage**:  

**Question, Bug, or Feature?**:  
Bug

**Virtual environments affected**  
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [x] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Image version**
20210307.1

**Expected behavior**  
I expect "brew install jo" to work.

**Actual behavior**  
It fails with:
==> Downloading https://homebrew.bintray.com/bottles/jo-1.4.catalina.bottle.tar.gz
curl: (35) LibreSSL SSL_connect: SSL_ERROR_SYSCALL in connection to homebrew.bintray.com:443 
Error: Failed to download resource "jo"
Download failed: https://homebrew.bintray.com/bottles/jo-1.4.catalina.bottle.tar.gz
Error: Process completed with exit code 1.

**Repro steps**  
Run a job on macos-latest with following commands:

1. export HOMEBREW_NO_INSTALL_CLEANUP=1
2. brew install jo

Observe the second step will fail with above quoted error message.

**Comment by dibir-magomedsaygitov** [comment]
Hello @speedym. I've tried to reproduce the issue, but `brew install jo` works as expected for me.

**Comment by dibir-magomedsaygitov** [comment]
@speedym could you please try to run `brew install curl-openssl` before running `brew install jo` and see if it helps.

**Comment by speedym** [comment]
I just tested it, and it seems that the issue has been fixed meanwhile:

  # no reason to waste time on brew cleanup on transient CI instances
  export HOMEBREW_NO_INSTALL_CLEANUP=1
  brew install curl-openssl
  brew install jo
  shell: /bin/bash --noprofile --norc -e -o pipefail {0}
  env:
    tharp_framework_path: build/ios/Release-iphoneos/Tharp.framework/Tharp
    CLOUDSDK_METRICS_ENVIRONMENT: github-actions-setup-gcloud
    GCLOUD_PROJECT: ***
    GOOGLE_APPLICATION_CREDENTIALS: /Users/runner/work/tharp/tharp/cdfe8573-d989-4095-a995-76dd83a06616
Warning: curl 7.75.0 is already installed and up-to-date.
To reinstall 7.75.0, run:
  brew reinstall curl
==> Downloading https://homebrew.bintray.com/bottles/jo-1.4.catalina.bottle.tar.gz
==> Pouring jo-1.4.catalina.bottle.tar.gz
==> Caveats
Bash completion has been installed to:
  /usr/local/etc/bash_completion.d
==> Summary
🍺  /usr/local/Cellar/jo/1.4: 10 files, 53.3KB

We can probably close this issue?

Ps. I can confirm that it also works without "brew install curl-openssl" as well.
