### ISSUE TITLE
Update homebrew

### ISSUE THREAD

**Issue by marblenix** [actions/virtual-environments#2952]
**Tool information**
- Tool name: homebrew
- Add or update? update
- Desired version: 4e6840b6d6805e40e869991fb139b6db1094a1b2 or newer

**Area for Triage**:
A bug in homebrew has been fixed:
* https://github.com/Homebrew/brew/pull/10548
* https://github.com/marblenix/homebrew-onivim2/runs/2117763861?check_suite_focus=true

Current workaround:
* running `brew update --force` in your github actions file 
  * https://github.com/marblenix/homebrew-onivim2/runs/2125667692?check_suite_focus=true

**Question, Bug, or Feature?**:
Bug

**Virtual environments affected**
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [x] macOS 10.15
- [x] macOS 11.0
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Are you willing to submit a PR?**
yes

**Comment by dibir-magomedsaygitov** [comment]
Hello @marblenix. Thank you for your report. We install latest available version of Homebrew on our images and it should be delivered with the next week's rollout. I'll post an update message.

**Comment by dibir-magomedsaygitov** [comment]
Hello, @marblenix. Quick update on Homebrew: we had to rollback `macOS 10.15` image due to [issue ](https://github.com/actions/virtual-environments/issues/3014)with Java. `macOS 11.0 `was successfully updated.
I'll post an update message as soon as new version of Homebrew is available to use on `macOS 10.15`.

**Comment by dibir-magomedsaygitov** [comment]
Hello, @marblenix. Updated Homebrew should be available on `macOS 10.15` as well. I'm going to close this issue. In case of any questions feel free to contact us.

**Comment by dibir-magomedsaygitov** [comment]
Sorry for false alert, deployment of `macOS 10.15` is not finished yet. I'll reopen the issue.

**Comment by marblenix** [comment]
Thanks for keeping us up-to-date

**Comment by dibir-magomedsaygitov** [comment]
Hello, @marblenix. `macOS 10.15` deployment is finally finished. I'm going to close this issue. In case of any questions feel free to contact us.
