### ISSUE TITLE
[Ubuntu] jekyll/builder and node8-typescript docker images will be removed from images on March, 22

### ISSUE THREAD

**Issue by MaksimZhukov** [actions/virtual-environments#2958]
**Breaking changes**
The `jekyll/builder` and `mcr.microsoft.com/azure-pipelines/node8-typescript` docker images will be removed from Ubuntu images

**Target date**
Image deployment will start March, 22 and will take 3-4 days.

**The motivation for the changes**
We are reconsidering the space usage policy on Ubuntu images and are going to deprecate these docker images due to lack of free space.

**Possible impact**
If the required docker image is not available locally on a machine (for example, when we use the `docker container run` command), the docker daemon will automatically pull the latest copy of the image from your configured registry. This will increase build time by approximately 15 seconds for each docker image.

**Virtual environments affected**
- [x] Ubuntu 16.04
- [x] Ubuntu 18.04
- [x] Ubuntu 20.04
- [ ] macOS 10.13
- [ ] macOS 10.14
- [ ] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Mitigation ways**
If you need to pull these images from a registry by yourself, please consider using the following commands:

1) **mcr.microsoft.com/azure-pipelines/node8-typescript**
```
docker image pull mcr.microsoft.com/azure-pipelines/node8-typescript
```
2) **jekyll/builder**
```
docker image pull jekyll/builder
```

**Comment by miketimofeev** [comment]
The new images were deployed
