### ISSUE TITLE
Add diffstat to ubuntu images

### ISSUE THREAD

**Issue by toddwalstad-eaton** [actions/virtual-environments#2960]
**Tool information**
- Tool name: diffstat
- Tool license:  MIT-X11
- Add or update? add
- Desired version: latest
- Approximate size: 72.7 kB
- If this is an add request:
  - Brief description of tool: diffstat reads the output of diff and displays a histogram of the insertions, deletions, and modifications per-file. It is useful for reviewing large, complex patch files.
  - URL for tool's homepage: [Diffstat](https://invisible-island.net/diffstat/)
  - Provide a basic test case to validate the tool's functionality: diffstat -v 

**Area for Triage**:

**Question, Bug, or Feature?**:

**Virtual environments affected**
- [X ] Ubuntu 16.04
- [X ] Ubuntu 18.04
- [X ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Can this tool be installed during the build?**
yes,  apt-get install -y --no-install-recommends diffstat

**Tool installation time in runtime**
seconds

**Are you willing to submit a PR?**
Yes, I can work through this change

I would like to use these scripts to create our own image with larger build drive space as we are building our own distro, this is the only package that is missing for us to do this.

**Comment by maxim-lobanov** [comment]
Hello @toddwalstad-eaton , thank you for proposal.
Considering pretty quick installation in runtime we wouldn't like to bake this tool into the images due to maintenance concerns
