### ISSUE TITLE
Replace the microsoft/aspnetcore-build:1.0-2.0 cached Docker image with newer image

### ISSUE THREAD

**Issue by MichaelSimons** [actions/virtual-environments#2962]
**Docker image information**
- Image tag:  microsoft/aspnetcore-build:1.0-2.0
- Approximate size: ltsc2019 - 3.99GB (extracted on disk)
- Add or update? update
- New tag: mcr.microsoft.com/dotnet/framework/sdk:4.8-windowsservercore-ltsc2019/ltsc2016
- New size: ltsc2019 - 10.8 GB (extracted on disk)  ** 7.66 GB of this image's layers are already cached via the `mcr.microsoft.com/dotnet/framework/runtime:4.8-windowsservercore-ltsc2019` image and the base OS `mcr.microsoft.com/windows/servercore:ltsc2019` image.

I didn't investigate the size image on ltsc2016.

**Justification**
The `microsoft/aspnetcore-build:1.0-2.0` image is two year old and is not supported.  The `mcr.microsoft.com/dotnet/framework/sdk` images have replaced the `microsoft/aspnetcore-build` images.  Given that the  `mcr.microsoft.com/dotnet/framework/aspnet:4.8-windowsservercore-ltsc2019/ltsc2016` and `mcr.microsoft.com/dotnet/framework/runtime:4.8-windowsservercore-ltsc2019/ltsc2016` images are already cached, it is natural to also cache the sdk image.

**Area for Triage**:

**Question, Bug, or Feature?**:
Bug

**Virtual environments affected**
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11.0
- [x] Windows Server 2016 R2
- [x] Windows Server 2019

**Are you willing to submit a PR?**
yes

**Comment by AlenaSviridenko** [comment]
Hi @MichaelSimons,
we need some time for initial investigation. We will get back once we have something. Thanks.

**Comment by AlenaSviridenko** [comment]
Hi @MichaelSimons, 
PR with new image was merged, changes deployment has started today and will take 3-4 days. We'll let you know when it finished.

**Comment by miketimofeev** [comment]
@MichaelSimons we've finished the deployment! Both win16 & win19 now contain `sdk:4.8-windowsservercore` images.
I'm going to close the issue. Please feel free to contact us if you have any concerns.
Thank you!
