### ISSUE TITLE
Update the cached Docker images in the Ubuntu environments

### ISSUE THREAD

**Issue by MichaelSimons** [actions/virtual-environments#2963]
The following cached OS images have reached EOL (some are still in extended support).  The pure EOL images should be removed.  The ones in extended support are questionable and should be considered for removal.

EOL:
alpine:3.7

EOL (in extended support):
debian:8
ubuntu:14.04

It is unclear what the Docker image caching policy is.  It would seem beneficial to cache the latest alpine and maybe n-1.  It also seems reasonable to cache the latest version of Debian.  For Unbuntu, cache the latest lts and possibly n-1.  Given this, the following images should be added:
alpine:3.13
alpine:3.12
debian:10
ubuntu:20.04
ubuntu:18.04
ubuntu:16.04

**Area for Triage**:

**Question, Bug, or Feature?**:
Bug

**Virtual environments affected**
- [x] Ubuntu 16.04
- [x] Ubuntu 18.04
- [x] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Are you willing to submit a PR?**
yes

**Comment by tusharb86** [comment]
+1 I would love to see debian:10 in the cached images on the host agent. I am also willing to submit a PR to get things updated. Thanks!

**Comment by AlenaSviridenko** [comment]
Hi @MichaelSimons, 
we need some time for initial investigation. We will get back once we have something. Thanks.

**Comment by dsame** [comment]
The PR to update cached docker images for Ubuntu merged and will be alive on the next VM rollout

**Comment by miketimofeev** [comment]
@MichaelSimons the rollout is finished.
I'm going to close the issue. Please feel free to contact us if you have any concerns.
Thank you!
