### ISSUE TITLE
Chromium fails to launch in Ubuntu 20 due to permissions

### ISSUE THREAD

**Issue by amclin** [actions/virtual-environments#2967]
**Description**  
In Ubuntu 20, the Chromium browser installed fails to launch due to permissions (18 didn't have Chromium provided). GitHub actions just [switched from the Ubuntu 18 to 20 image as the default](https://github.com/actions/virtual-environments/issues/1816).

As a result, in pipelines where available browsers are auto-detected, Chromium is now detected, but when it is launched it fails due to permission errors when attempting to create the profile directory.

```
17 03 2021 13:18:07.841:INFO [framework.detect-browsers]: which.sync(process.env[browser.ENV_CMD]):  /usr/bin/google-chrome
17 03 2021 13:18:07.844:INFO [framework.detect-browsers]: The following browsers will be used: [ 'Chrome', 'Chromium', 'Firefox' ]
17 03 2021 13:18:08.942:INFO [karma-server]: Karma v6.2.0 server started at http://localhost:9876/
17 03 2021 13:18:08.942:INFO [launcher]: Launching browsers Chrome, Chromium, Firefox with concurrency unlimited
17 03 2021 13:18:08.951:INFO [launcher]: Starting browser Chrome
17 03 2021 13:18:08.965:INFO [launcher]: Starting browser Chromium
17 03 2021 13:18:08.978:INFO [launcher]: Starting browser Firefox
17 03 2021 13:18:11.821:ERROR [launcher]: Cannot start Chromium
	/bin/bash: /etc/profile.d/env_vars.sh: Permission denied
mkdir: cannot create directory ‘/run/user/1001’: Permission denied
No protocol specified
[3065:3065:0317/131811.781769:ERROR:browser_main_loop.cc(1390)] Unable to open X display.
```

**Area for Triage**:  
['Area: JavaScript and Node.js']['Area: Testing and code coverage']

**Question, Bug, or Feature?**:  
Bug

**Virtual environments affected**  
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [x] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Image version**

`20210309.1`

**Expected behavior**  
Chromium launches consistent with Chrome and Firefox launching

**Actual behavior**  
Chromium fails to launch with permission errors for the profile paths

**Repro steps**  
A description with steps to reproduce the issue. If your have a public example or repo to share,
please provide the link.

1. Setup a repo with NodeJS, NPM, Karma and `karma-chrome-launcher`
2. Configure Karma to launch `Chromium`
3. Run Karma via GitHub action

**Example GitHub Actions run failing:**
https://github.com/amclin/videojs-scene7/pull/595/checks?check_run_id=2130920709#step:7:96

**Same GitHub Action passing when Chromium is suppressed:**
https://github.com/amclin/videojs-scene7/pull/597/checks?check_run_id=2134619300#step:7:94

**Comment by nikita-bykov** [comment]
Hello @amclin. We have reworked our Chromium installation and this should solve your issue. Images with changes will be rolled out around next week.

**Comment by miketimofeev** [comment]
@amclin we've finished the deployment, but, unfortunately the executable name changed — https://github.com/actions/virtual-environments/issues/3133
We're going to fix it soon. Until then, could you please use a workaround?
`sudo ln -s /usr/bin/chromium /usr/bin/chromium-browser`

**Comment by amclin** [comment]
Seems to be working in my scenario even without symlinking the executable names, I suspect because the underlying library used for auto-detection is doing a good job of finding binaries by various names.

Here's a successful run using the image tagged `20210405.1`:
https://github.com/amclin/videojs-scene7/pull/622/checks?check_run_id=2298984480#step:7:94

**Comment by miketimofeev** [comment]
@amclin great! I'm going to close the issue then.
Please feel free to contact us if you have any concerns.
Thank you!
