### ISSUE TITLE
Add databricks connect to Ubuntu images

### ISSUE THREAD

**Issue by TakeshiKovacs** [actions/virtual-environments#2971]
Hi Guys

Would it be possible to get the Databricks connect tool added to the Ubuntu images?
This would help immensely in deploying to Databricks from a Devops pipeline.

Many Thanks
Mat

**Comment by dibir-magomedsaygitov** [comment]
Size of Databricks connect tool is about 230-240MB. Installation takes about 1 min. 
Installation is pretty easy:
`pip install -U databricks-connect==version`

**Comment by maxim-lobanov** [comment]
Hello , thank you for proposal.
Unfortunately, we wouldn't like to bake this tool into the images. Please consider installation in runtime like shared above
