### ISSUE TITLE
Sonarqube Task not working with Win2019 image. java version error: ##[error]No agent found in pool Default which satisfies the specified demands: java, Agent.Version -gtVersion 2.144.0

### ISSUE THREAD

**Issue by unclevit** [actions/virtual-environments#2976]
**Description** 
Hello everybody,

when Sonarqube tasks are present in the build pipeline the following error occurs using the self-hosted agent based on the latest Win2019 release (20210309.0):

##[error]No agent found in pool Default which satisfies the specified demands: java, Agent.Version -gtVersion 2.144.0

**Area for Triage**:  
Java

**Question, Bug, or Feature?**:  
Bug

**Virtual environments affected**  
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [X] Windows Server 2019

**Image version**
20210309.0

**Expected behavior**  
Sonarqube Tasks Work

**Actual behavior**  
Pipeline not start and stop working with this error:
##[error]No agent found in pool Default which satisfies the specified demands: java, Agent.Version -gtVersion 2.144.0

**Repro steps**  
A description with steps to reproduce the issue. If your have a public example or repo to share,
please provide the link.

1. Step 1
2. Step 2

**Comment by al-cheb** [comment]
Hello, @unclevit 
Could you please provide screenshots?
1. Agent PoolName
![image](https://user-images.githubusercontent.com/47745270/111741374-79cf4c80-8897-11eb-9867-f82000453617.png)

2. Demands section
![image](https://user-images.githubusercontent.com/47745270/111741418-8ce21c80-8897-11eb-8d5e-d2c60bc97ebf.png)

**Comment by unclevit** [comment]
![immagine](https://user-images.githubusercontent.com/44055862/111747478-a8492980-888f-11eb-850e-4024adce671b.png)

![immagine](https://user-images.githubusercontent.com/44055862/111747612-cdd63300-888f-11eb-89ac-833b41544013.png)

**Comment by al-cheb** [comment]
@unclevit , Sorry we don't support self-hosted pools. You should create a ticket in Azure DevOps support. Try to remove demands related to java and run a new build.

**Comment by unclevit** [comment]
@al-cheb , The self-hosted pool contains only one agent based on the Win2019 image generated from this project.

The condition on java is inserted automatically when I add the Sonarqube task to the pipeline.
I also tried to change the default version of java on the agent (JDK 11) but this didn't fix the problem. I think it is really an agent configuration problem in the sense that some components/configurations, necessary to make Sonarqube's tasks work, may be missing:
https://docs.sonarqube.org/latest/analysis/scan/sonarscanner-for-azure-devops/
https://docs.sonarqube.org/latest/requirements/requirements/

However, I will follow your advice and open a ticket to the AzureDevOps support team.

Thank you

**Comment by maxim-lobanov** [comment]
@unclevit , Sorry, we are not experts with Azure DevOps so can't help outside of the image.

Just an idea: Sonarqube task requires agent with `Java` demand. Looks like your self-hosted agent doesn't have this demand despite the fact that generated image has installed Java (you have to assign demands by yourself). You can try to add `java` demand (capability) on your agent. Try to following the guide: https://docs.microsoft.com/en-us/azure/devops/pipelines/process/demands?view=azure-devops&tabs=yaml#manually-entered-demands

**Comment by unclevit** [comment]
@maxim-lobanov thank you for your suggestion because it helped me to solve the problem.

The problem is due to the fact that in the Environment Variable the default PATH of java is defined as JAVA_HOME and not JAVA.
The System Capabilities of the agent in AzureDevOps are automatically inserted based on the name of the variables as you can see from the image below.

To solve the problem I simply added a new capabilities manually from the AzureDevOps panel naming it JAVA and giving it as PATH that of JAVA_HOME.

Another possible solution is to change the name of the Environment Variable from JAVA_HOME to JAVA so that it is automatically added to the System Capabilities.

Thanks so much

![immagine](https://user-images.githubusercontent.com/44055862/111756679-c8321a80-889a-11eb-8d00-aa42e7072010.png)
