### ISSUE TITLE
OpenSSL downgraded on the latest Ubuntu 18.04 image (20210315.1)

### ISSUE THREAD

**Issue by GabrielNagy** [actions/virtual-environments#2977]
**Description**  
The OpenSSL version that comes with the newest Ubuntu 18.04 image is way older than the previous one (1.1.1 vs 1.1.1j).

**Area for Triage**:  

**Question, Bug, or Feature?**:  
Bug

**Virtual environments affected**  
- [ ] Ubuntu 16.04
- [x] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Image version**
20210315.1

**Expected behavior**  
OpenSSL has a similar version as the previous image (20210309.1):
```
OpenSSL Library Version - OpenSSL 1.1.1j  16 Feb 2021
```

**Actual behavior**  
OpenSSL version is older than previous image:
```
OpenSSL Library Version - OpenSSL 1.1.1  11 Sep 2018
```

The difference in version is observed in the following workflow runs (Run tests on Linux step):
- passing (20210309.1): https://github.com/puppetlabs/puppet/runs/2131250735#step:6:21
- failing (20210315.1): https://github.com/puppetlabs/puppet/pull/8544/checks?check_run_id=2140754928#step:6:21

Running `apt-cache policy openssl` on the new image version gives:

```
openssl:
  Installed: 1.1.1-1ubuntu2.1~18.04.8
  Candidate: 1.1.1-1ubuntu2.1~18.04.8
  Version table:
 *** 1.1.1-1ubuntu2.1~18.04.8 1000
        500 http://azure.archive.ubuntu.com/ubuntu bionic-updates/main amd64 Packages
        500 http://security.ubuntu.com/ubuntu bionic-security/main amd64 Packages
        100 /var/lib/dpkg/status
     1.1.0g-2ubuntu4 1000
        500 http://azure.archive.ubuntu.com/ubuntu bionic/main amd64 Packages
```

**Repro steps**  
Fire up a runner and run `openssl version`

**Comment by dibir-magomedsaygitov** [comment]
Hello, @GabrielNagy. Thank you for your report. I've checked current version of `openssl` on Ubuntu 18 and can confirm that it shows `OpenSSL Library Version - OpenSSL 1.1.1  11 Sep 2018`. 
As a simple workaround I would suggest you to uninstall and install OpenSSL again:
```
sudo apt-get remove openssl
sudo apt-get install -y openssl
```
In this case `openssl version` outputs expected version of OpenSSL:
`OpenSSL 1.1.1j  16 Feb 2021`

**Comment by dibir-magomedsaygitov** [comment]
Hello @GabrielNagy. Sorry for misleading you in my last reply. Previously, OpenSSL was updated from `ppa:ondrej/php`, but now the ppa doesn't contain updated packages and Ubuntu images started to use the default version of OpenSSL (`OpenSSL 1.1.1  11 Sep 2018` for Ubuntu18). To get back to the desired version of OpenSSL you can compile the package manually using the following steps:
```
wget https://www.openssl.org/source/openssl-1.1.1j.tar.gz
tar xzvf openssl-1.1.1j.tar.gz
cd openssl-1.1.1j
./config -Wl,--enable-new-dtags,-rpath,'$(LIBRPATH)'
make
sudo make install
openssl version
```

**Comment by GabrielNagy** [comment]
Thanks for investigating @dibir-magomedsaygitov. It was a bit weird that we had such a recent openssl version on Ubuntu 18.04 which is LTS after all. From my perspective the issue can be closed.
