### ISSUE TITLE
Breaking change due to missing '.dotnet/tools to path'

### ISSUE THREAD

**Issue by edumserrano** [actions/virtual-environments#2978]
**Description**  

Today I've noticed my workflow failing on the step that is trying to run the installed dotnet tool because it can't find it.

I've noticed that there is a difference in the last line of the logs produced by the `actions/setup-dotnet@v1` from when it was working to now when it is failing:

* output from previously working `actions/setup-dotnet@v1`:
```
/home/runner/work/_actions/actions/setup-dotnet/v1/externals/install-dotnet.sh --version 5.0.201
dotnet_install: Warning: Unable to locate zlib. Probable prerequisite missing; install zlib.
dotnet-install: Downloading link: https://dotnetcli.azureedge.net/dotnet/Sdk/5.0.201/dotnet-sdk-5.0.201-linux-x64.tar.gz
dotnet-install: Extracting zip from https://dotnetcli.azureedge.net/dotnet/Sdk/5.0.201/dotnet-sdk-5.0.201-linux-x64.tar.gz
dotnet-install: Adding to current process PATH: `/home/runner/.dotnet`. Note: This change will be visible only when sourcing script.
dotnet-install: Installation finished successfully.
/home/runner/.dotnet:/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:/opt/pipx_bin:/usr/share/rust/.cargo/bin:/home/runner/.config/composer/vendor/bin:/usr/local/.ghcup/bin:/home/runner/.dotnet/tools:/snap/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
```

* output from now failing `actions/setup-dotnet@v1`:
```
/home/runner/work/_actions/actions/setup-dotnet/v1/externals/install-dotnet.sh --version 5.0.201
dotnet_install: Warning: Unable to locate zlib. Probable prerequisite missing; install zlib.
dotnet-install: Downloading link: https://dotnetcli.azureedge.net/dotnet/Sdk/5.0.201/dotnet-sdk-5.0.201-linux-x64.tar.gz
dotnet-install: Extracting zip from https://dotnetcli.azureedge.net/dotnet/Sdk/5.0.201/dotnet-sdk-5.0.201-linux-x64.tar.gz
dotnet-install: Adding to current process PATH: `/home/runner/.dotnet`. Note: This change will be visible only when sourcing script.
dotnet-install: Installation finished successfully.
/home/runner/.dotnet:/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:/opt/pipx_bin:/usr/share/rust/.cargo/bin:/usr/local/.ghcup/bin:/snap/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
```

The last line is different and it seems to me that it's the path which in the working version includes `.dotnet/tools` (among others).  It seems something changed that made the path contain much less in the latest version of the virtual environment image. 

Another point of difference is that now the step to install a global dotnet tool outputs the following warning:

```
Since you just installed the .NET SDK, you will need to logout or restart your session before running the tool you installed.
```

The version of the virtual environment where this was working is `20210302.0`, the version where it's failing is `20210315.1`.

My workflow has only been using Ubuntu 18.04 and Ubuntu 20.04 so I don't know if this is a change that affected other virtual environments.

I wasn't sure if this was an issue with the `actions/setup-dotnet@v1` or the virtual environment but after looking at both repos I believe this is a regression on https://github.com/actions/virtual-environments/issues/213.

**Area for Triage**:  

.NET Core

**Question, Bug, or Feature?**:  

Bug

**Virtual environments affected**  
- [ ] Ubuntu 16.04
- [x] Ubuntu 18.04
- [x] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Image version**

20210315.1

**Expected behavior**  
I expect to be able to install globally a dotnet tool and then execute it. This has been working for at least the last month.

**Actual behavior**  
I cannot execute a globally installed dotnet tool.

**Repro steps**  

The example extract of yaml can reproduce the issue:

```yaml
- name: Setup .NET
  uses: actions/setup-dotnet@v1
  with:
    dotnet-version: 5.0.x
- name: Install reportgenerator dotnet tool
  shell: pwsh
  run:  dotnet tool install --global dotnet-reportgenerator-globaltool
- name: reportgenerator
  shell: pwsh
  run: reportgenerator -h
```

Instead of getting the version  of the installed reportgenerator dotnet tool when running the step with name `reportgenerator` I get an error saying:

```
reportgenerator: /home/runner/work/_temp/8936da25-343a-47d4-9cb6-3b4bf5fe5e46.ps1:2
Line |
   2 |  reportgenerator `
     |  ~~~~~~~~~~~~~~~
     | The term 'reportgenerator' is not recognized as a name of a
     | cmdlet, function, script file, or executable program. Check
     | the spelling of the name, or if a path was included, verify
     | that the path is correct and try again.

Error: Process completed with exit code 1.
```

You can see this on [my Publish Nuget packages workflow](https://github.com/edumserrano/dot-net-sdk-extensions/actions/workflows/nuget-publish.yml). Last successful run was on 13th March 2021. Noticed it started failing on 18th March 2021.

**Comment by al-cheb** [comment]
Hello, @edumserrano 
I can reproduce the issue. As a quick workaround please use fullpath to the `reportgenerator` util or use bash as a shell:
`& $env:DOTNET_ROOT/tools/reportgenerator`
or
`
"$(pwd)/tests/test-results/coverage-results/coverage.opencover.xml"
`

**Comment by al-cheb** [comment]
@edumserrano, The new image with fix has been deployed.

**Comment by edumserrano** [comment]
I can confirm it's working. Thank you!
