### ISSUE TITLE
Announce/Feedback: Default Xcode changing to 11.3.1 on 2/3/2020

### ISSUE THREAD

**Issue by alepauly** [actions/virtual-environments#298]
Hi!

We're changing MacOS 10.15 runners to use Xcode 11.3.1 by default starting the week of ~2/1/2020~ ~1/27/2020~ 2/3/2020.

If you have any concerns or questions please let use know through this issue.

Thanks!

**Comment by alepauly** [comment]
Please note that I just updated the date for this update to 1/27/2020. Human error, I didn't do date math correctly when I first posted this, please let us know if this date update could cause issues for you.

**Comment by alepauly** [comment]
This has been delayed to the week of 2/3/2020 due to an issue rolling out the latest image.

**Comment by dbJones77** [comment]
When is the update happening? It appears default XCode version is still 11.2.1 as of 2/6/2020

**Comment by miketimofeev** [comment]
Hi @dbJones77 
The update has been finished recently. Could you check one more time, please?

**Comment by miketimofeev** [comment]
@dbJones77 we are going to close this issue. Feel free to open a new one in case of any inconvenience.
