### ISSUE TITLE
Please update Google chrome browser and driver version

### ISSUE THREAD

**Issue by VasanthChidambaram** [actions/virtual-environments#299]
**Tool information**
- Tool name: Google chrome driver
- Add or update? Update
- Desired version: Latest
- Approximate size: 
- If this is an add request:
  - Brief description of tool: 
  - URL for tool's homepage: 

**Virtual environments affected**
- [ ] Windows Server 2016 R2

**Can this tool be installed during the build?**
Yes. 

**Are you willing to submit a PR?**
No

**Comment by vmapetr** [comment]
Hi @VasanthChidambaram. Thank you for the report! Chrome Driver for Windows was updated in PR https://github.com/actions/virtual-environments/pull/185. It will be deployed during current image-rollout.

**Comment by VasanthChidambaram** [comment]
@vmapetr - Thank you very much !
