### ISSUE TITLE
Android API28 (Xamarin) looks to be missing with VS 16.9 update

### ISSUE THREAD

**Issue by BretJohnson** [actions/virtual-environments#2992]
**Description**  
Since the hosted agents moved to having VS 16.9 installed instead of 16.8, we are now seeing build errors for our Xamarin project, saying it can't find android.jar for API 28 - that API 28 doesn't look to be installed.

However, API 28 is supposed to still be installed on the hosted agent, per the doc here: https://github.com/actions/virtual-environments/blob/main/images/win/Windows2019-Readme.md

**Area for Triage**:  
Xamarin

**Question, Bug, or Feature?**:  
Bug

**Virtual environments affected**  
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [x] Windows Server 2019

**Image version**
windows-2019

**Expected behavior**  
See description

**Actual behavior**  
See description

**Repro steps**  
See description

**Comment by LeonidLapshin** [comment]
Hi, @BretJohnson !
Images are updated weekly (it takes 3+ days on all runners) and the readme page in the main branch updates only after the deployment completion. However, you can get the actual software list from your run from 'Set up job' step/'Virtual Environment' tab, it looks like:
```
Virtual Environment
  Environment: windows-2019
  Version: 20210316.1
  Included Software: https://github.com/actions/virtual-environments/blob/win19/20210316.1/images/win/Windows2019-Readme.md
  Image Release: https://github.com/actions/virtual-environments/releases/tag/win19%2F20210316.1
```
I'm pretty sure that [Windows Server 2019 (20210309 update) ](https://github.com/actions/virtual-environments/pull/2895/files)  causes your build failures due to the fact that Component.Android.SDK28 was updated to Component.Android.SDK30. According to the article, this is [the only available SDK version ](https://docs.microsoft.com/en-us/visualstudio/install/workload-component-id-vs-enterprise?view=vs-2019#components-included-by-this-workload-11)

Is it possible to update your application to use the latest SDK version?

**Comment by BretJohnson** [comment]
@LeonidLapshin Thanks for the reply. I do expect the switch to Component.Android.SDK30 (the default in VS 16.9) triggered this issue. However, something doesn't seem right.  There should be several versions of the Android SDK installed, as shown in the screenshot below from the Android SDK section of the vm image doc.

When setting up a machine manually the process would typically be: Install VS 16.9, which includes Android API 30 (and only API 30) by default. And then go to the Android SDK manager to download all the other Android SDK images that you care about. It's normal to have several of them installed and choose on an app by app basis which SDK version you want to target. There must be something in the hosted agent setup process that automates doing this - downloading the SDKs for API levels 19 - 30 to ensure they are present, matching the doc. But maybe something went wrong there.

Is it possible for you to see what files are physically on the machine? The `platforms` directory under the Android SDK should have subdirectories named `android-xx`, for each SDK installed (e.g. `android-30`, `android-29`, etc.). Among other files each of those subdirectories should have an `android.jar` file. If you can launch VS on the machine, go to Tools / Options / Xamarin / Android Settings to see the Android SDK root directory that's configured there.

BTW, the specific error we're getting here is `Could not find android.jar for API Level 28`. It's similar behavior to the old issue here https://stackoverflow.com/questions/52297174/build-pipeline-for-xamarin-android-project-targeting-api-28.

Thx for your help.

![image](https://user-images.githubusercontent.com/245892/112436725-7404bb80-8d1c-11eb-87b7-938485d798a7.png)

**Comment by LeonidLapshin** [comment]
Hey, @BretJohnson 
The `C:\Program Files (x86)\Android\android-sdk\platforms\android-28` directory contains android.jar on image, so the 28 SDK is installed correctly. Android SDKs are installed independently to VS, so I guess your project try to find SDK somewhere, but not on this path. Does your build try to find android.jar on this path? Could you please share the full error message?

**Comment by LeonidLapshin** [comment]
Hi, @BretJohnson !
Do you need any additional help/information or we can close the issue?

**Comment by LeonidLapshin** [comment]
Hey, @BretJohnson !
I'll close the issue for now, but if you have any concerns, please feel free to reopen it :)
