### ISSUE TITLE
Broken Ubuntu 20 clang builds as of ~12 hours ago

### ISSUE THREAD

**Issue by drewcassidy** [actions/virtual-environments#2995]
**Description**  
My C++/Cmake project has been failing to build on github actions for the past 12 hours. see https://github.com/drewcassidy/quicktex/actions, build [121](https://github.com/drewcassidy/quicktex/actions/runs/664078687) succeeded before I reran it an hour ago to confirm it was the build environment causing my issues and not the code. It seems like `libc++-dev` and/or `libc++-11-dev` are not installed correctly.

**Area for Triage**:  
C/C++

**Question, Bug, or Feature?**:  
Bug

**Virtual environments affected**  
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [x] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Image version**
20210315.1

**Expected behavior**  
Clang build succeeds

**Actual behavior**  
Either a failure to find Libc++ (C++11 libraries are unable to be found) or a failure to find the abi (`cannot find -lc++abi`) when clang 11 is used

**Comment by brianlheim** [comment]
I'm also experiencing this: https://github.com/supercollider/supercollider/runs/2155446920?check_suite_focus=true, it might be related to this update: https://github.com/actions/virtual-environments/commit/c253e7f4d192e492988596167a1d461e99698c13#diff-6be9f9ce03ba57ca01e4ae937d5c2bb04893520fdf391ea87eb46acbc43ecdc5

since our last successful build on this configuration was ~5 days ago.

**Comment by drewcassidy** [comment]
That sounds about right. I had a successful build a few days after that commit but I don't know how long it takes for new images to roll out to github's infrastructure

**Comment by catthehacker** [comment]
@drewcassidy 
https://github.com/actions/virtual-environments/blob/f178f0ec83f136647a01e01872a69d79b2af181d/README.md#L30

In the README there is also status of all images deployed for each platform.

**Comment by vsafonkin** [comment]
Hi @drewcassidy, looks like the `libc++-11-dev` and `libc++-11-dev` libs installation is reason of failure. Could you please try this step as workaround?
```
- run: sudo apt-get purge -y libc++abi-11-dev libc++-11-dev && sudo apt-get install -y libc++abi-dev libc++-dev
```
It should work for clang 10.

**Comment by miketimofeev** [comment]
@drewcassidy we have removed clang11-related libs from the image, thanks @catthehacker for the contribution.
The new image will be deployed next week.

**Comment by miketimofeev** [comment]
@drewcassidy the image has been deployed! I'm going to close the issue but please feel free to contact us if you have any concerns.
Thank you!

**Comment by drewcassidy** [comment]
nope, everything seems to be working fine now, with the exception of my own code 😁
