### ISSUE TITLE
Cannot access the internet for github action workflow

### ISSUE THREAD

**Issue by Khalian** [actions/virtual-environments#2996]
**Description**  
I cannot access the internet for github actions workflow 

**Question, Bug, or Feature?**:  
Bug

https://github.com/Khalian/Modulo12/pull/14/checks?check_run_id=2160911242

**Comment by LeonidLapshin** [comment]
Hey, @Khalian!
I see 403 http error in your build, it seems that the URL is incorrect or it need authorization, but the connection is ok.
Could you please check it?

**Comment by Khalian** [comment]
The URL is correct. The way my code works is, i need to fetch a DTD of an xml type (called music xml) in order to parse the music xml file into an internal format i prefer. 

I know for a fact its correct, since I run the same exact code in travis CI and it succeeds there, and I was considering migrating to github actions, but it seems there are technical limitations to your project to allow outbound connectivity to URLs from your build server.

**Comment by Khalian** [comment]
For instance here is a successful build in travis CI: https://travis-ci.com/github/Khalian/Modulo12/builds/220743765

And here is the PR i tried with both in tandem https://github.com/Khalian/Modulo12/pull/14 and as you can see, the github actions one fails and the travis one succeeds.

**Comment by maxim-lobanov** [comment]
Hello @Khalian , Looks like your Travis build uses Java 14. Why do you use Java 8 in GitHub Actions build pipeline? (https://github.com/Khalian/Modulo12/pull/14/files#diff-d65baf3ad59488720aa50001fc7eb86b8f6ec0ca91534edb708dfe39e22aece0R19)

After switching Java to 14, build passes successfully. 
See build results in my fork: https://github.com/maxim-lobanov/Modulo12/runs/2181818758?check_suite_focus=true
Corrected YAML: https://github.com/maxim-lobanov/Modulo12/actions/runs/682094650/workflow

**Comment by Khalian** [comment]
@maxim-lobanov oh boy. This is embarrassing. Thanks a ton. I used the default template and forgot about JDK.

**Comment by Khalian** [comment]
Yep sorry about that. I just copied the default scala template and forgot about JDK version.

**Comment by akkim31** [comment]
#2951
