### ISSUE TITLE
Actions-workflow changed behavior (Lint results)

### ISSUE THREAD

**Issue by hb0** [actions/virtual-environments#2997]
**Description**  
We have a Gtihub Action Workflow which runs `./gradlew build` executing `:lint`.
The result of that Lint execution did change without us changing anything.

There seems to be an issue with the CI environment.
In other CI environments (e.g. Bitrise) or a local Ubuntu 20.04 environment the Lint result is still as it was 2 months ago.
If we run the same workflow on commits which succeeded before, the Lint execution now fails on the same commits on Github.

I know you changed the default environment from 18.04 to Ubuntu 20.04, so I checked it with the current 18.04 version which produces the same unexpected behavior. Thus, I did not post this problem [here](https://github.com/actions/virtual-environments/issues/1816).

**Area for Triage**:  

**Question, Bug, or Feature?**:  
Bug

**Virtual environments affected**  
- [x] Ubuntu 18.04
- [x] Ubuntu 20.04

**Image version**
ubuntu-18.04_20210309.1
ubuntu-20-04_20210315.1

**Expected behavior**  
The `./gradlew :lint` execution should:
- behave the same as before / same as on other environments

```
> Task :persistence:lint
Ran lint on variant debug: 0 issues found
Ran lint on variant release: 0 issues found
```

- _(If a bug fix lead to this, I need to know how to reproduce this "new" behavior locally)_

**Actual behavior**  
Github CI is showing errors which cannot be reproduced anywhere else and which did not appear on the same commit and workflow 2 months ago:

```
> Task :persistence:lint
Ran lint on variant debug: 28 issues found
Ran lint on variant release: 28 issues found
```

**Repro steps**  
This build did work before: _(ubuntu-18.04_20201210.0)_
https://github.com/cyface-de/android-backend/runs/1761525795?check_suite_focus=true

Executing this commit now again, without changing anything, now fails:
https://github.com/cyface-de/android-backend/runs/2132482596?check_suite_focus=true

Here the same Build on Bitrise CI which still behaves as Github did 2 months ago:
https://app.bitrise.io/build/54082a61f67372d6

**Comment by LeonidLapshin** [comment]
Hey, @hb0 !
I have successfully reproduced this issue on fork, but seems that java-gradle is the same version as used in green build. As far as I can see, you have updated some dependencies on January, 25 that are used in this lint tests. Can be the issue somehow connected to them?

**Comment by hb0** [comment]
Hi @LeonidLapshin !
Thanks for your response.

Let me clarify I understood you correctly:
Do you mean the dependencies updated in the commit `400c536e`, the bottom one in the screenshot?
![Screenshot](https://user-images.githubusercontent.com/6112241/111990557-a55e6b00-8b13-11eb-8ada-424a5b4bbdbf.png)

The build which is tested in this issue (commit `78760756`, upper one in the screenshot) comes **after** `400c536e`.
- it did [build](https://github.com/cyface-de/android-backend/runs/1761525795?check_suite_focus=true) before
- but does not [build](https://github.com/cyface-de/android-backend/runs/2165990296?check_suite_focus=true) anymore

I don't see how these changes can have a delayed effect? :)

**Comment by LeonidLapshin** [comment]
@hb0, thank you for quick response, I mean dependencies that are required for gradle, they come from 
`https://maven.pkg.github.com/cyface-de/android-utils/de/cyface/android-utils/2.0.1/android-utils-2.0.1.pom`
as I understood, may be there is some version mismatch or they are hardcoded?

**Comment by maxim-lobanov** [comment]
Hello @hb0 , looks like your builds were switched from Ubuntu 18.04 to Ubuntu 20.04 according to https://github.com/actions/virtual-environments/issues/1816 since you use `ubuntu-latest` in YAML workflow.
Could you please try to switch back to 18.04?

**Comment by hb0** [comment]
@maxim-lobanov 
I tried this before without success, but did this again a moment ago to demonstrate: [here](https://github.com/cyface-de/android-backend/runs/2169048423?check_suite_focus=true) (`ubuntu-18.04_20210315.1`)

**Comment by vsafonkin** [comment]
Hi @hb0, could you please check Android `lint` version on Bitrise?
```
$ANDROID_HOME/tools/bin/lint --version
```
Maybe different lint default rules for different lint version are reason of these warnings.

**Comment by hb0** [comment]
@vsafonkin Both locally and on Bitrise this version is used:

```
lint: version 26.1.1
```

**Comment by miketimofeev** [comment]
@hb0 I've cloned your repo to my local box, run `./gradlew lint` from the root, and got the same results:
```
* What went wrong:
Execution failed for task ':persistence:lint'.
> Lint found errors in the project; aborting build.
  
  Fix the issues identified by lint, or add the following to your build script to proceed with errors:
  ...
  android {
      lintOptions {
          abortOnError false
      }
  }
  ...
  The first 3 errors (out of 28) were:
  
  /Users/mikhail.timofeev/Downloads/android-backend-main/persistence/src/main/java/de/cyface/persistence/DatabaseHelper.java:217: Error: Value must be ≥ 0 [Range]
                                          .getLong(selectedMeasurementsCursor.getColumnIndex(BaseColumns._ID)));
                                                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  /Users/mikhail.timofeev/Downloads/android-backend-main/persistence/src/main/java/de/cyface/persistence/serialization/EventsFileSerializer.java:120: Error: Value must be ≥ 0 [Range]
                  final String value = eventsCursor.getString(eventsCursor.getColumnIndex(EventTable.COLUMN_VALUE));
                                                              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  /Users/mikhail.timofeev/Downloads/android-backend-main/persistence/src/main/java/de/cyface/persistence/serialization/EventsFileSerializer.java:127: Error: Value must be ≥ 0 [Range]
                          .getString(eventsCursor.getColumnIndex(EventTable.COLUMN_TYPE));
                                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by hb0** [comment]
@miketimofeev Good to know. Unfortunately, this does not really help me reproducing the errors,
as I still don't know what changed on the Github Actions side which made those error disappear before and appear after.

The only differences I notices between both builds are:
- Runner version: `2.276.1` => `2.277.1`
- OS: `ubuntu-18.04_20201210.0` => `ubuntu-18.04_20210315.1`

**Comment by miketimofeev** [comment]
@hb0 there are a lot of changes since then. Could you take a look at the diff for Ubuntu-18 software list, maybe it will help?
https://github.com/actions/virtual-environments/compare/46df370..be672cb2?short_path=8d528b6#diff-8d528b68ca937dfe5a0194829f0eb2633bc3d7a3105a637ccb534a4da765f7a3

**Comment by miketimofeev** [comment]
@hb0 did this information help you?

**Comment by hb0** [comment]
@miketimofeev Well,
* I checked the versions in the `Android` section with my local versions but was not able to reproduce the Lint errors locally.
* I also search again for a `lint.xml` on my computer or `lintOptions` in the gradle build files.
* When I execute `Android Studio > Analysis > Code Inspections` I get 15 errors but not the ones shown above (which are 28 anyways).
* **So I still only get 2 "issues" but 0 errors when I run `./gradlew :persistence:lint`.**

I'm sort of giving up that I will understand any time soon why the behavior of Github Actions changed all of a sudden and why I still get the previous behavior anywhere else.

If you have another idea, I'm happy to check it out.
