### ISSUE TITLE
Add lavapipe

### ISSUE THREAD

**Issue by qarmin** [actions/virtual-environments#2998]
**Tool information**
- Tool name: Lavapipe
- Tool license: MIT(this is Mesa license)
- Add or update? Add
- Desired version: The latest, not sure which lavapipe uses(maybe none at the moment)
- Approximate size: -
- If this is an add request:
  - Brief description of tool: 
Lavapipe is tool which allow to run Vulkan apps on CPU without needing to have external GPU card. Already exists in Github CI llvmpipe, which works but only with OpenGL(Godot already use this to open editor and test project in Ci - https://github.com/godotengine/godot/blob/c0b3ad2f7bd09c3b0b905842c3b90be6381fe1e0/.github/workflows/linux_builds.yml#L204-L206)
  - URL for tool's homepage: https://gitlab.freedesktop.org/mesa/mesa/
  - Provide a basic test case to validate the tool's functionality: 
Something like this:
```
sudo apt install unzip wget2 xvfb-run
sudo apt-get install build-essential scons pkg-config libx11-dev libxcursor-dev libxinerama-dev  libgl1-mesa-dev libglu-dev libasound2-dev libpulse-dev libudev-dev libxi-dev libxrandr-dev yasm # Required to build Godot, but most are needed in runtim
wget2 https://archive.hugo.pro/builds/godot/master/editor/godot-linux-nightly-x86_64.zip
unzip godot-linux-nightly-x86_64.zip
xfvb-run ./godot # It should for now crash Godot
```
I already setup CI which fails for now - https://github.com/qarmin/RegressionTestProject/blob/4.0/.github/workflows/linux_builds_master.yml

 

**Area for Triage**:

Testing and code coverage

**Question, Bug, or Feature?**:

Feature

**Virtual environments affected**
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [x] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Can this tool be installed during the build?**

It can't be installed for now from PPA or similar, but it can be compiled from source(Mesa compilation)

**Tool installation time in runtime**

In CI compilation of Mesa will took I think 2-4h

**Are you willing to submit a PR?**

Not really, because I don't know how to do this

**Comment by LeonidLapshin** [comment]
Hey, @qarmin 
Unfortunately, we can't afford to add this tool considering time consuming (2h+) installation and limitation to specific use-cases.

**Comment by fintelia** [comment]
On the ubuntu 22.04 runners you can install lavapipe/llvmpipe and related tools with:
```bash
sudo apt-get install -y mesa-vulkan-drivers libvulkan1 vulkan-tools vulkan-validationlayers
```
