### ISSUE TITLE
Add VirtualBox and Vagrant for macOS Big Sur instances

### ISSUE THREAD

**Issue by AkihiroSuda** [actions/virtual-environments#2999]
**Tool information**
- Tool name: VirtualBox and Vagrant
- Tool license: VirtualBox: GPL2 (https://www.virtualbox.org/wiki/Licensing_FAQ), Vagrant: MIT (https://github.com/hashicorp/vagrant/blob/main/LICENSE)
- Add or update?: Add
- Desired version: Arbitrary version
- Approximate size: Hundreds of megabytes
- If this is an add request:
  - Brief description of tool: Create virtual machines
  - URL for tool's homepage: https://www.virtualbox.org/ https://www.vagrantup.com/
  - Provide a basic test case to validate the tool's functionality: `vagrant init fedora/33-cloud-base && vagrant up`

**Area for Triage**:

**Question, Bug, or Feature?**:

Feature

**Virtual environments affected**
- [X] macOS 11.0

VirtualBox and Vagrant have been available for macOS 10.15 hosts (https://github.com/actions/virtual-environments/issues/433), but they seem to have been removed for Big Sur, probably because it was not stable on Big Sur at that time.

The release note of VirtualBox (https://www.virtualbox.org/wiki/Changelog) now has been mentioning Big Sur since v6.1.16, so it seems properly supporting Big Sur.

**Can this tool be installed during the build?**

No

**Tool installation time in runtime**

N/A

**Are you willing to submit a PR?**

No

**Comment by AlenaSviridenko** [comment]
Hi @AkihiroSuda,
until we don't have a defined plan for macOS 11 support, we'd rather not to add anything new to it, except critical software like Xcode, we only update and support  what we have now on this image.
These tools can be installed from Homebrew pretty easy in runtime:
1. `brew install --cask vagrant` - takes 30 seconds
2. `brew install --cask virtualbox` - takes 40 seconds. 
Also, there is an action for it https://github.com/marketplace/actions/vagrant-virtualbox, it may fit all your needs, please, take a look.

I am closing this issue. Feel free to create a new one if any help needed. Thanks.

**Comment by palfrey** [comment]
They are in Homebrew, but they don't work without some manual GUI changes (see https://stackoverflow.com/a/52813517). Also the action does stuff with an installed Vagrant/Virtualbox setup, but won't do the install for you.
