### ISSUE TITLE
Add GTK+ 3 to Ubuntu and macOS Runners

### ISSUE THREAD

**Issue by NinjaCheetah** [actions/virtual-environments#3004]
**Tool information**
- Tool name: GTK+ 3
- Tool license: GNU Lesser General Public License
- Add or update? Add
- Desired version: Latest version of GTK+ 3
- Approximate size: 24.1 MB total on Ubuntu, 53.7 MB without dependencies on macOS
- If this is an add request:
  - Brief description of tool: Library needed to compile programs that rely on GTK+
  - URL for tool's homepage: https://www.gtk.org/
  - Provide a basic test case to validate the tool's functionality: I don't have a good example but the best way to test would be to compile a program that relies on it

**Area for Triage**:
```
- valueFor: '**Area for Triage**'
  contains: 'C/C++'
  addLabels: ['Area: C/C++']
```

**Question, Bug, or Feature?**:
Feature

**Virtual environments affected**
- [ ] Ubuntu 16.04
- [x] Ubuntu 18.04
- [X] Ubuntu 20.04
- [X] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Can this tool be installed during the build?**
Yes, with
`brew install gtk+3` on macOS
or
`sudo apt install libgtk-3-0 libgtk-3-dev` on Ubuntu

**Tool installation time in runtime**
Around 10-20 seconds on Ubuntu and 2-4 minutes on macOS

**Are you willing to submit a PR?**
Depending on how hard it would be to add, possibly

**Comment by AlenaSviridenko** [comment]
Hi @NinjaCheetah,
given the pretty quick installation time and tool popularity, we'd rather not to add to the image due to maintenance concerns, please, keep installing it in runtime. 

I am closing this issue. Feel free to create a new one if any other help needed.
