### ISSUE TITLE
Update/Add ALSA (Advanced Linux Sound Architecture)

### ISSUE THREAD

**Issue by dsherry** [actions/virtual-environments#3009]
**Tool information**
- Tool name: ALSA
- Tool license: GNU General Public License (GPL)
- Add or update? Add
- Desired version: Latest
- Approximate size: 
- If this is an add request:
  - Brief description of tool: The Advanced Linux Sound Architecture (ALSA) provides audio and MIDI functionality to the Linux operating system.
  - URL for tool's homepage: https://www.alsa-project.org/wiki/Main_Page
  - Provide a basic test case to validate the tool's functionality:
Running `lsmod | grep snd` should show the `snd-seq` kernel plugin, which does not currently appear on `ubuntu-latest`.

A simple way to test this with python:
```bash
pip3 install rtmidi
python3 -c "import rtmidi; rtmidi.MidiOut(rtapi=rtmidi.API_LINUX_ALSA)"
```
If the `snd-seq` kernel plugin and ALSA are not correctly installed, the above will error out with
> rtmidi._rtmidi.SystemError: MidiOutAlsa::initialize: error creating ALSA sequencer client object.
> ...
> LSA lib seq_hw.c:466:(snd_seq_hw_open) open /dev/snd/seq failed: No such file or directory

**Area for Triage**:

**Question, Bug, or Feature?**:
Feature

**Virtual environments affected**
- [ ] Ubuntu 16.04
- [x] Ubuntu 18.04
- [X] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Can this tool be installed during the build?**
If the `snd-seq` kernel module has been installed correctly, then yes, something like `sudo apt-get install libasound2-dev alsa-base alsa-utils` should do it. [This page](https://alsa.opensrc.org/Quick_Install) has comprehensive info on installation.

**Tool installation time in runtime**
I don't know.

**Are you willing to submit a PR?**
Maybe! I don't know much about linux kernel modules. If someone could help ensure that the `snd-seq` kernel module is installed correctly (which it appears not to be at the moment), I could try to learn how to include ALSA in the ubuntu images by default.

**Comment by al-cheb** [comment]
Hello, @dsherry
Sorry, we don't have any plans to replace  or manually build a new  kernel. I am trying to find `linux-modules-extra`  package for Azure kernel  that contains additional sound modules but with no luck. In that case our recommendation is to use self-hosted agent with generic/oracle/gcp kernel.

**Comment by melanchall** [comment]
@dsherry Hello! You can up (just click "This bug affects you and 2 other people" at the top) [this bug](https://bugs.launchpad.net/ubuntu/+source/linux-aws/+bug/1970586) as I did. Probably it will help to increase its priority and get what we need.
