### ISSUE TITLE
Pre-Install Az PWSH Modules on windows-2019/windows-latest

### ISSUE THREAD

**Issue by kngohil** [actions/virtual-environments#301]
Currently there does not seem to be any Az.* modules pre-installed as part of the windows-2019/windows-latest hosted container image. However the equivalent Linux Ubuntu 16.04 image seems to have the modules installed (but not loaded) i.e. it has Az Module (1.0.0)/(1.6.0)/(2.3.2)/(2.6.0)/(2.8.0)/(3.1.0). 

Using the Linux based container is just not good enough for an Azure DevOps pipeline that is heavy on PowerShell. PowerShell behaviour is not native on Ubuntu. 

Can the latest version (or at least the last 3 or 4 versions) of the Az module please be fully pre-installed onto the container image. Currently I am having to do an unnecessary step of installing the modules in my YAML DevOps pipeline before my actual CI/CD steps run (because they expect Az to exist). I'd expect a Windows-2019 image which already has PWSH to also have Az. 

Having these modules will remove the need to do something like: 

```
Install-Module -Name Az -AllowClobber -Scope CurrentUser -Force -Confirm:$false
```

Also please ensure that the AzureRM module is kept away from this - both together will cause issues. AzureRM should soon be deprecated so best not to have both together that could cause issues in the future.

**Comment by thejoebourneidentity** [comment]
@kmkumaran & @roopeshnair, can you take a look at this and offer a suggested path forward?

**Comment by maxim-lobanov** [comment]
Hello, currently, the following versions are pre-installed on Windows images:
- [AzureRM PowerShell module](https://github.com/actions/virtual-environments/blob/master/images/win/Windows2019-Readme.md#azurerm-powershell-module): 2.1.0 (default), 3.8.0, 4.2.1, 5.1.1, 6.7.0, 6.13.1
- [Azure PowerShell module](https://github.com/actions/virtual-environments/blob/master/images/win/Windows2019-Readme.md#azure-powershell-module): 2.1.0 (default), 3.8.0, 4.2.1, 5.1.1, 5.3.0 
- [Az PowerShell module](https://github.com/actions/virtual-environments/blob/master/images/win/Windows2019-Readme.md#az-powershell-module): 1.0.0, 1.6.0, 2.3.2, 2.6.0, 3.1.0, 3.5.0

Could you please confirm that it resolves initial issue?

**Comment by maxim-lobanov** [comment]
@kngohil I am closing the issue based on my message above but please feel free to reopen if you have any concerns
