### ISSUE TITLE
Android builds breaking on macOS-10.15 20210321 update

### ISSUE THREAD

**Issue by SaintNicholas** [actions/virtual-environments#3014]
**Description**  
My Android builds are breaking on the macOS-10.15 20210321 update, but they are still working on the 20210314 update.

The error I get is:
`> Task :app:kaptGenerateStubsAlphaDebugKotlin FAILED
e: [kapt] 'com.sun.tools.javac.util.Context' class can't be found ('tools.jar' is absent in the plugin classpath). Kapt won't work.`

In the 20210321 update the path for JDK 1.8 was updated, and when I print out the environment variable on the Hosted Agent I see `JAVA_HOME=/Users/runner/hostedtoolcache/Java_Adopt_jdk/8.0.282+8/x64/Contents/Home/`/

I think the `+8` might be causing problems. The reason is, when I ran the Android build again with --debug, I saw commands like the following:
`2021-03-24T02:41:34.1349770Z 2021-03-24T02:41:31.678+0000 [DEBUG] [org.gradle.api.Task] [KOTLIN] Kotlin compiler classpath: /Users/runner/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-compiler-embeddable/1.4.21/87db94500aaf883536ae8c8efdee76bdc839d582/kotlin-compiler-embeddable-1.4.21.jar, /Users/runner/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-reflect/1.4.21/748f681f4e3edbe9285ff46710c79049c70f4dfa/kotlin-reflect-1.4.21.jar, /Users/runner/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib/1.4.21/4a668382d7c38688d3490afde93b6a113ed46698/kotlin-stdlib-1.4.21.jar, /Users/runner/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-script-runtime/1.4.21/1247decba314790165b4fe94d09c45b09db6b07f/kotlin-script-runtime-1.4.21.jar, /Users/runner/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-daemon-embeddable/1.4.21/bc95bcebdc871d45d9852b0c01abe9bec373bb52/kotlin-daemon-embeddable-1.4.21.jar, /Users/runner/.gradle/caches/modules-2/files-2.1/org.jetbrains.intellij.deps/trove4j/1.0.20181211/216c2e14b070f334479d800987affe4054cd563f/trove4j-1.0.20181211.jar, /Users/runner/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-common/1.4.21/7f48a062aa4b53215998780f7c245a4276828e1d/kotlin-stdlib-common-1.4.21.jar, /Users/runner/.gradle/caches/modules-2/files-2.1/org.jetbrains/annotations/13.0/919f0dfe192fb4e063e7dacadee7f8bb9a2672a9/annotations-13.0.jar, /Users/runner/hostedtoolcache/Java_Adopt_jdk/8.0.282 8/x64/Contents/Home/lib/tools.jar`

The important part here is the path `/Users/runner/hostedtoolcache/Java_Adopt_jdk/8.0.282 8/x64/Contents/Home/lib/tools.jar`. you can see that the + is totally gone in the log. I'm not sure that this is the problem, or if it's just a weird artifact in the log but not really causing a problem, it's just an idea.

**Area for Triage**:  
Android

**Question, Bug, or Feature?**:  
Bug

**Virtual environments affected**  
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [x] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Image version**
macOS-10.15 20210321

**Expected behavior**  
The build succeeds.

**Actual behavior**  
The build fails.

**Comment by maxim-lobanov** [comment]
@SaintNicholas could you please share minimal repro steps?
@dmitry-shibanov to take a look at this issue.

**Comment by tyagirajnish** [comment]
I am also facing the same issue from yesterday evening. 
**Agent** : macOS-10.15
`/Users/runner/work/1/s/gradlew assembleDebug`

**Comment by dmitry-shibanov** [comment]
Hello @tyagirajnish. Thank you for your response. Could you please provide some project for repro steps. If it's a private project, could you please provide build steps. Besides, If you don't mind, could you also add information about versions of kotlin, gradle and dependencies for the project ?

**Comment by tyagirajnish** [comment]
hi @dmitry-shibanov, can't share my repo due to private project,  please find the details below 
Kotlin_version : 1.3.72
classpath 'com.android.tools.build:gradle:4.0.1'

![Screenshot 2021-03-24 at 15 43 51](https://user-images.githubusercontent.com/46373586/112281044-a3c7ab00-8cab-11eb-8792-923d5ab3844d.png)
![Screenshot 2021-03-24 at 15 44 02](https://user-images.githubusercontent.com/46373586/112281058-a62a0500-8cab-11eb-91bd-d66b96abff0a.png)



Meanwhile, can some tell me how to use a specific release in agents as @SaintNicholas mention he is not facing the issue in **20210314**

**Comment by dawidhyzy** [comment]
Having the same issue since yesterday
```
Task :SomeModule:kaptGenerateStubsDebugKotlin FAILED
e: [kapt] 'com.sun.tools.javac.util.Context' class can't be found ('tools.jar' is absent in the plugin classpath). Kapt won't work.
```

**Comment by miketimofeev** [comment]
@tyagirajnish @dawidhyzy we're going to rollback the image to unblock you and then continue the investigation. Sorry for the inconvenience and thank you for provided details

**Comment by francosang** [comment]
Same error since yesterday.

 :x: Failing environment versions:

```
Virtual Environment
Environment: macos-10.15
Version: 20210321.1
Included Software: https://github.com/actions/virtual-environments/blob/macOS-10.15/20210321.1/images/macos/macos-10.15-Readme.md
Image Release: https://github.com/actions/virtual-environments/releases/tag/macOS-10.15%2F20210321.1
Current image version: '20210321.1'
```

![imagen](https://user-images.githubusercontent.com/25726643/112286321-7cf97c80-8c8b-11eb-8f62-fc5471a20deb.png)

:white_check_mark: Working environment versions:

```
Virtual Environment
Environment: macos-10.15
Version: 20210314.1
Included Software: https://github.com/actions/virtual-environments/blob/macOS-10.15/20210314.1/images/macos/macos-10.15-Readme.md
Image Release: https://github.com/actions/virtual-environments/releases/tag/macOS-10.15%2F20210314.1
Current image version: '20210314.1'
Agent running as: 'runner'
```

![imagen](https://user-images.githubusercontent.com/25726643/112286295-7408ab00-8c8b-11eb-867a-bbc4e9cb80e8.png)

**Comment by SaintNicholas** [comment]
I was able to reproduce this locally with the following steps:

1. Create a new project and add the plugin 'room', with a kapt step. I've attached my project ([Reproduce.zip](https://github.com/actions/virtual-environments/files/6197447/Reproduce.zip)).
2. Install AdoptOpenJDK. This installed on my Mac to /Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk.
3. Change the AdoptOpenJDK folder name to be adoptopenjdk-8+8.jdk, so the path to the jdk is now /Library/Java/JavaVirtualMachines/adoptopenjdk-8+8.jdk.
4. Make javac use that jdk by running `export JAVA_HOME=/Library/Java/JavaVirtualMachines/adoptopenjdk-8+8.jdk/Contents/Home/`.
5. Build my project with `./gradlew clean build -no-build-cache`

That failed with:
`> Task :app:kaptGenerateStubsDebugKotlin FAILED
e: [kapt] 'com.sun.tools.javac.util.Context' class can't be found ('tools.jar' is absent in the plugin classpath). Kapt won't work.`

**Comment by maxim-lobanov** [comment]
@SaintNicholas thank you for providing repro steps.
We have already started image rollback so the issue should be resolved in a few hours.
Your repro steps will help to avoid repeating it in future

**Comment by miketimofeev** [comment]
The rollback has been finished

**Comment by maxim-lobanov** [comment]
I think the issue can be closed since images were rolled back. Please let us know if you still experience this issue.
