### ISSUE TITLE
Add oracle client to Microsoft-hosted agents

### ISSUE THREAD

**Issue by valfrid-ly** [actions/virtual-environments#3039]
**Tool information**
- Tool name: Microsoft-hosted agents
- Tool license: Any
- Add or update? Add
- Desired version: I believe 11g client works with all existing versions of the database
- Approximate size: 
- If this is an add request:
  - Brief description of tool: Oracle client with SQL Plus to allow publishing for this database
  - URL for tool's homepage: https://www.oracle.com/database/technologies/instant-client/
  - Provide a basic test case to validate the tool's functionality: 
create a file with "select sysdate from dual" inside.

call -> sqlplus user/pass @filename

**Area for Triage**:

**Question, Bug, or Feature?**:
"Feature"

**Virtual environments affected**
- [X] Ubuntu 16.04
- [X] Ubuntu 18.04
- [X] Ubuntu 20.04
- [X] macOS 10.15
- [X] macOS 11.0
- [X] Windows Server 2016 R2
- [X] Windows Server 2019

**Can this tool be installed during the build?**
No

**Tool installation time in runtime**
Few minutes

**Are you willing to submit a PR?**
I'd like too... gonna check

**Comment by AlenaSviridenko** [comment]
Hi @valfrid-ly,
unfortunately, we cannot pre-install Oracle products due to legal issues.

I am closing this issue. Please, feel free to create a new one if any other help needed. Thanks.
