### ISSUE TITLE
Can't use nuke.build to build .net core app. Nuke is missing

### ISSUE THREAD

**Issue by jubayerarefin** [actions/virtual-environments#305]
**Tool information**
- Tool name: Nuke
- Add or update? Add
- Desired version: 0.23.6
- Approximate size: 
- If this is an add request:
  - Brief description of tool: A cross-platform build automation system with C# DSL.
  - URL for tool's homepage: http://www.nuke.build/

**Area for Triage**: .NET Core, .NET Framework

**Question, Bug, or Feature?**: Feature

**Virtual environments affected**
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Can this tool be installed during the build?**
No

**Are you willing to submit a PR?**
No

**Comment by jubayerarefin** [comment]
@miketimofeev hi any idea when this will be implemented?

**Comment by miketimofeev** [comment]
@jubayerarefin sorry, it's still untriaged at the moment.
@alepauly can we add it?

**Comment by miketimofeev** [comment]
@jubayerarefin by the way, could you try to install it during the run, looks like it's quite fast

**Comment by jubayerarefin** [comment]
I'll give it a try

With Kind Regards,
Jubayer Arefin

________________________________

**Comment by jubayerarefin** [comment]
@miketimofeev it can be installed during the run :)

**Comment by al-cheb** [comment]
Hello, @jubayerarefin 
Feel free to open thread if you have any questions.
