### ISSUE TITLE
Add clang-format 

### ISSUE THREAD

**Issue by ashok-arora** [actions/virtual-environments#3053]
**Tool information**
- Tool name: clang-format
- Tool license: 
- Add or update? Add
- Desired version: The latest version
- Approximate size: 
- If this is an add request:
  - Brief description of tool: It is a tool to format C++ code against a supplied set of rules. 
  - URL for tool's homepage: https://clang.llvm.org/docs/ClangFormat.html 
  - Provide a basic test case to validate the tool's functionality: 

**Area for Triage**: C/C++

**Question, Bug, or Feature?**: Feature

**Virtual environments affected**
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [x] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Can this tool be installed during the build?**
Yes using `sudo apt install -y clang-format`

**Tool installation time in runtime**
A few seconds. 

**Are you willing to submit a PR?**
Sure.

**Comment by miketimofeev** [comment]
Hi @ashok-arora!
We install clang-format as a part of clang installation here
https://github.com/actions/virtual-environments/blob/826fed960459993d41c2f9310d220b7cf2c015e8/images/linux/scripts/installers/clang.sh#L19
Has the process changed and we need to install it in a different way?

**Comment by ashok-arora** [comment]
Hello @miketimofeev! 
Thanks for the quick response!

Oh right, it does come pre-installed on Github's Ubuntu 20.04. 

My first instinct was to search it in this README file
https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-README.md
and I installed it manually since it wasn't there. 


Would it be possible to add `clang-format` to that README file?

**Comment by miketimofeev** [comment]
@ashok-arora yes, I think we need to provide information about all additional clang tools that are installed along with the clang. Thanks for your suggestion!

**Comment by miketimofeev** [comment]
@ashok-arora we've added Clang-format to the software report generator! The new docs will be available along with the new image next week

**Comment by miketimofeev** [comment]
@ashok-arora we've added clang-format to the readme
![image](https://user-images.githubusercontent.com/48208649/114062861-a8da4c00-98a0-11eb-9c88-7f172704ffe4.png)
I'm going to close the issue. Please feel free to contact us if you have any concerns.
Thank you!

**Comment by ashok-arora** [comment]
Thanks a lot @miketimofeev! :tada:
