### ISSUE TITLE
Browser testing issues since latest 20.04 update

### ISSUE THREAD

**Issue by deivid-rodriguez** [actions/virtual-environments#3060]
**Description**  

Since https://github.com/actions/virtual-environments/releases/tag/ubuntu20%2F20210318.0, our CI became flaky. Previously we had ~10 jobs that were consistently green. After the upgrade 1/2 jobs fail most of the times.

**Area for Triage**:  Testing and code coverage

**Question, Bug, or Feature?**:  Bug

**Virtual environments affected**  
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [x] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Image version**
20210318.0

**Expected behavior**  
Jobs keep passing as with the previous image version.

**Actual behavior**  
Sometimes test fail to connnect to local chrome.

**Repro steps**  
The public repo example is https://github.com/activeadmin/activeadmin. In https://github.com/activeadmin/activeadmin/pull/6874 I downgraded to 18.04 as a workaround and now the CI is green again, but if the worfklow files are changed in back to ubuntu 20.04 in the default branch it should fail again. 

I noticed that there's some work being done regarding how chrome is installed on ubuntu 20.04, so I guess it could be related and you're already aware of it, but I thought I'd report it just in case.

Thanks so much for this awesome CI environment! :heart_eyes:

**Comment by miketimofeev** [comment]
Hi @deivid-rodriguez and thanks for such kind words about the CI 😃
Could you please provide a few links to the particular runs with issues in https://github.com/activeadmin/activeadmin?

**Comment by deivid-rodriguez** [comment]
Sure, all failures here should be due to this issue: https://github.com/activeadmin/activeadmin/actions?page=2.

The last ones include some changes I made to investigate the errors. Due to the tool we're using for parallelizing our cucumber scenarios, the effect a very slow executions resulting in timeouts with no error information. With those changes I enabled sequential execution of our tests, and `--fail-fast` mode and the errors become more clear. For example, in this run: https://github.com/activeadmin/activeadmin/actions/runs/699216880, which shows

> Failed to open TCP connection to 127.0.0.1:36429 (Connection refused - connect(2) for "127.0.0.1" port 36429) (Errno::ECONNREFUSED)

**Comment by miketimofeev** [comment]
@deivid-rodriguez thanks, it would also be great if you could find the run when the issue appeared for the first time

**Comment by miketimofeev** [comment]
@deivid-rodriguez thanks for the links! Is it possible to create a minimal repro because running the whole workflow every time to get the issue might be overkill?

**Comment by deivid-rodriguez** [comment]
Sure, sorry for the delay, let me try do that now!

**Comment by deivid-rodriguez** [comment]
Well, I don't seem to repro this anymore on ubuntu 20.04, so whatever the problem was, it seems not really related to the upgrade I was pointing to.

Sorry for the false alarm and thanks for your help!

**Comment by miketimofeev** [comment]
@deivid-rodriguez thanks for the update! Feel free to reopen the issue if it reoccurs
