### ISSUE TITLE
SoftwareReport has incorrect Erlang version, Erlang Pester test is stuck

### ISSUE THREAD

**Issue by catthehacker** [actions/virtual-environments#3061]
**Description**  
SoftwareReport has incorrect Erlang version and test for Erlang is stuck.

**Area for Triage**: Erlang / Elixir

**Question, Bug, or Feature?**:  
Bug

**Virtual environments affected**  
- [x] Ubuntu 16.04
- [x] Ubuntu 18.04
- [x] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Image version**
https://github.com/actions/virtual-environments/tree/master

**Expected behavior**  
Pester test for Erlang is not stuck. `Ubuntu-XX04-README.md` contains proper Erlang and Eshell version.

**Actual behavior**  
Pester test for Erlang is stuck on `Describing 'Erlang'`. Current software report contains `eshell` version rather than Erlang itself.

**Repro steps**  
I'm using `docker` builder in Packer but the fix should be working for both Azure VMs and Docker builders as the current test is not good at the moment.
PR will be submitted right after.

**Comment by miketimofeev** [comment]
@catthehacker thanks for reporting and the contribution!

**Comment by miketimofeev** [comment]
@catthehacker thanks for your contribution!
The new image will be deployed next week

**Comment by miketimofeev** [comment]
@catthehacker we have deployed the images.
Thanks for you contribution!
