### ISSUE TITLE
Circular symlink in AppData\Local folder (windows-2019)

### ISSUE THREAD

**Issue by bobbrow** [actions/virtual-environments#3065]
**Description**  
I'm encountering an issue trying to onboard CI for Windows for our CMake Tools extension for VS Code. I've been trying to work around it, but haven't been successful yet, so I decided to open an issue for it.  There is a file watcher that ends up trying to index the %LocalAppData% folder during the test (I haven't figured out why yet since it doesn't appear to be our extension's file watchers).  This should normally be benign and not a problem, but it turns out that there is a circular symlink inside that folder in your windows-2019 image and it causes the test to fail.

**Area for Triage**:  
Containers

**Question, Bug, or Feature?**:  
Bug

**Virtual environments affected**  
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [x] Windows Server 2019

**Image version**
  Environment: windows-2019
  Version: 20210316.1
  Included Software: https://github.com/actions/virtual-environments/blob/win19/20210316.1/images/win/Windows2019-Readme.md
  Image Release: https://github.com/actions/virtual-environments/releases/tag/win19%2F20210316.1

**Expected behavior**  
I expect there to be no circular symlinks in the %LocalAppData% folder

**Actual behavior**  
The node module 'readdirp' complains that there is a circular symlink.
See the failure in [this build](https://github.com/microsoft/vscode-cmake-tools/runs/2230270341?check_suite_focus=true)

**Repro steps**  
I'm not sure if you will be able to run the [CI (Windows)](https://github.com/microsoft/vscode-cmake-tools/actions/workflows/ci-develop-win.yml) action against the **bobbrow/windowsCI** branch, but that's the only way I can repro it now.

If there's a way you can just check the image and verify the bad symlink is there, it might be faster.

**Comment by miketimofeev** [comment]
Hi @bobbrow!
We will take a look at it.

**Comment by bobbrow** [comment]
Actually, I may have successfully worked around it with https://github.com/microsoft/vscode-cmake-tools/commit/79c9ac8a2894e6fa0a704d3b362a2d0f38c4e9f2.  I'm seeing the tests proceed past this issue now.

**Comment by vsafonkin** [comment]
Hi @bobbrow, as I see, this symlink in `AppData/Local` is default part on Windows for backwards compatibility: https://answers.microsoft.com/en-us/windows/forum/windows_7-files/why-are-there-multiple-layers-of-application-data/4ec2c92c-a691-432b-b86a-c76d2b9a3faa

I believe, you can just remove this symlink in runtime.
