### ISSUE TITLE
HTTP 429 errors when trying to reproduce the Windows 2019 image

### ISSUE THREAD

**Issue by slime-uk** [actions/virtual-environments#3074]
**Description**  

For various reasons we are generating our own copy of the Windows Server 2019 image. We have found the process to be flaky and our build of the image often fails at downloading from visual studio marketplace with HTTP 429 error.  After some 3.5 hrs into the build, we try again and it still fails on a subsequent attempt, again after some 3.5 hrs.  I appreciate there is a retry step around this download - and this is failing the image after 20 attempts.

```
:
:
    vhd: Waiting 30 seconds before retrying. Retries left: 2
    vhd: Downloading package from: https://marketplace.visualstudio.com/_apis/public/gallery/publishers/ProBITools/vsextensions/MicrosoftAnalysisServicesModelingProjects/2.9.5/vspackage to path C:\Users\packer\AppData\Local\Temp\Microsoft.DataTools.AnalysisServices.vsix .
    vhd: There is an error during package downloading:
    vhd:  Exception calling "DownloadFile" with "2" argument(s): "The remote server returned an error: (429)."
    vhd: Waiting 30 seconds before retrying. Retries left: 1
    vhd: Downloading package from: https://marketplace.visualstudio.com/_apis/public/gallery/publishers/ProBITools/vsextensions/MicrosoftAnalysisServicesModelingProjects/2.9.5/vspackage to path C:\Users\packer\AppData\Local\Temp\Microsoft.DataTools.AnalysisServices.vsix .
    vhd: There is an error during package downloading:
    vhd:  Exception calling "DownloadFile" with "2" argument(s): "The remote server returned an error: (429)."
    vhd: File can't be downloaded. Please try later or check that file exists by url: https://marketplace.visualstudio.com/_apis/public/gallery/publishers/ProBITools/vsextensions/MicrosoftAnalysisServicesModelingProjects/2.9.5/vspackage
==> vhd: Script exited with non-zero exit status: 1.Allowed exit codes are: [0]
==> vhd: Step "StepProvision" failed, aborting...
==> vhd: aborted: skipping cleanup of step "StepConnectWinRM"
:
:
```

The error mentions checking that you can download the file - and clicking the link interactively downloads via Chrome successfully.  However, I also tried to RDP into to the packer VM (as local installer user) in a failed state before packer destroyed it and tried using PowerShell to download the file and I receive a similar 429 error but maybe with more detail which may help?

```
PS C:\Users\installer> [string]$uri = "https://marketplace.visualstudio.com/_apis/public/gallery/publishers/ProBITools/vsextensions/MicrosoftAnalysisServicesModelingProjects/2.9.5/vspackage"
Invoke-WebRequest -UseBasicParsing -Uri $uri
Invoke-WebRequest : {"$id":"1","innerException":null,"message":"Request was blocked due to exceeding usage of resource 'Count' in namespace 'AnonymousId'. For more information on 
why your request was blocked, see the topic \"Rate limits\" on the Microsoft Web site 
(https://go.microsoft.com/fwlink/?LinkId=823950).","typeName":"Microsoft.TeamFoundation.Framework.Server.RequestBlockedException, 
Microsoft.TeamFoundation.Framework.Server","typeKey":"RequestBlockedException","errorCode":0,"eventId":3000}
At line:2 char:1
+ Invoke-WebRequest -UseBasicParsing -Uri $uri
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand
```

Is there some environment variable we can use so we are not downloading anonymously?  Any other ideas?  I searched and found similar on issue #507 

**Area for Triage**:  
Deployment/Release

**Question, Bug, or Feature?**:  
Question/Bug?

**Virtual environments affected**  
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [X] Windows Server 2019

**Image version**
Windows 2019

**Expected behaviour**  
Windows 2019 packer build runs correctly on a repeatable basis.

**Actual behaviour**  
Aborted image build on download step from Visual Studio Marketplace for https://marketplace.visualstudio.com/_apis/public/gallery/publishers/ProBITools/vsextensions/MicrosoftAnalysisServicesModelingProjects/2.9.5/vspackage after 20 retries

**Repro steps**  
Clone the master branch and then build Windows 2019 image using packer.  Fails with http 429 errors when downloading this https://marketplace.visualstudio.com/_apis/public/gallery/publishers/ProBITools/vsextensions/MicrosoftAnalysisServicesModelingProjects/2.9.5/vspackage even though the file can be downloaded successfully outside of these scripts/packer environment.

**Comment by miketimofeev** [comment]
@slime-uk thanks for bringing this up, we will take a look

**Comment by slime-uk** [comment]
Just to let you know, I tried again today and on the 4th attempt, managed to get past this blocker.  25% success rate is not fantastic - so anything you can do to make this more robust would be appreciated!  The error mentions reading the header value for 429 errors and waiting for specified amounts before retry - or is there a backup location for the file if error 429 20 times?

**Comment by miketimofeev** [comment]
@slime-uk no, there is no backup location. We're trying to engage package owners to help with the investigation

**Comment by tiernano** [comment]
having the same issue for the last few weeks... posting here to watch thread...

**Comment by Darleev** [comment]
Hello @slime-uk @tiernano.
Thank you for reporting the issue to us.
We're forwarding the issue to our engineering team for further investigation. As soon as the update is received, I'll let you know.

**Comment by tiernano** [comment]
i reran the build of the VHD on Friday night in Central US, and it succeded... there were a couple of 429 errors, but the retry logic retries them 20 times, and they all finished in the end...

**Comment by Darleev** [comment]
Hello @slime-uk @tiernano,
We've received a response from our engineering team. They advised us to use CDN URLs to avoid downloading issue. Currently, we are working on it.
We will keep you updated.

**Comment by miketimofeev** [comment]
@slime-uk @tiernano we have changed the installation process, and the extensions are now installed using CDN URLs. There should be no 429 errors anymore. Could you please pull the latest main and test the behavior?

**Comment by tiernano** [comment]
I kicked off a build yesterday, and it looks like it finished in just under 7 hours with no issues... I cant see any 429 errors in the logs, so it must be all good. Thanks.

**Comment by miketimofeev** [comment]
@tiernano thanks for the confirmation!
@slime-uk I'm going to close the issue. Please feel free to contact us if you have any concerns.
Thank you!
