### ISSUE TITLE
GitHub Actions has encountered an internal error when running your job.

### ISSUE THREAD

**Issue by mrustl** [actions/virtual-environments#3079]
**Description**  
GitHub Actions has encountered an internal error when running your job:
https://github.com/KWB-R/dwc.ar4gw/actions/runs/708372505
https://github.com/KWB-R/kwb.nextcloud/actions/runs/708144823

**Area for Triage**:  

Deployment/Release

**Question, Bug, or Feature?**:  
Bug

**Virtual environments affected**  
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [x] macOS 11.0
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Image version**
Current runner version: '2.277.1'

**Expected behavior**  
No error 

**Actual behavior**  
GitHub Actions has encountered an internal error when running your job

**Repro steps**  
A description with steps to reproduce the issue. If your have a public example or repo to share,
please provide the link.

1. Push commit to repo
2. Github actions hangs in "queue" and finally errors with message above

**Comment by miketimofeev** [comment]
Hey @mrustl! We're experiencing service degradation at the moment, sorry for the inconvenience, it should be resolved shortly

**Comment by RJacksonm1** [comment]
One of my projects has been suffering from this for about 3 hours. Please can y'all make sure to update your status page?  https://www.githubstatus.com/

**Comment by miketimofeev** [comment]
Status page updated https://www.githubstatus.com/incidents/fjrtcnfz2cpd

**Comment by tahirmt** [comment]
Still facing the same issue on macos-10.15

**Comment by Milo123459** [comment]
Also on Ubuntu latest 🙃

**Comment by mrustl** [comment]
Worked a few hours but now service is degraded again. 
Github already investigates: https://www.githubstatus.com/incidents/fwtx9db6hz2y

**Comment by csm10495** [comment]
Still hitting this now in macos-latest. It stays stuck on 
```
Starting workflow run
```

then eventually errors on timeout.

**Comment by strager** [comment]
I think this issue is still happening. macOS jobs for my project are failing. Example failing workflow run: https://github.com/quick-lint/quick-lint-js/runs/2262617164

**Comment by aouinizied** [comment]
Same on our CI since several days:https://github.com/nfstream/nfstream/actions/runs/742628578

**Comment by maxim-lobanov** [comment]
@aouinizied , you macOS builds failed by timeout. The `pypy-3.7` job was not started due to `fail-fast: true` in YAML file.

**Comment by miketimofeev** [comment]
I'm going to close the issue since everything should be fine now
