### ISSUE TITLE
MS docs on VMimages for OSX out of sync

### ISSUE THREAD

**Issue by Sauraus** [actions/virtual-environments#308]
**Describe the bug**
The documentation here https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops is out of sync with what is listed in this repo, also no 10.15 OSX image can be instantiated using YAML build pipelines at present

**Virtual environments affected**
- [X] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Expected behavior**
YAML::
pool:
  vmImage: 'macOS-10.15'

would load the proper image.

**Actual behavior**
Build error in pipeline because no image with 'macOS-10.15' can be found

**Comment by alepauly** [comment]
@Sauraus MacOS 10.15 is not available yet in Azure Pipelines, @lupine86/@thejoebourneidentity might have info as to when it might become available.

For now the info that's specific to the Mac images used in Hosted Agents of Azure Pipelines still lives in https://github.com/microsoft/azure-pipelines-image-generation

**Comment by lupine86** [comment]
Similar to https://github.com/actions/virtual-environments/issues/81

**Comment by lupine86** [comment]
https://devblogs.microsoft.com/devops/azure-pipelines-hosted-pools-updates/
