### ISSUE TITLE
Can I build images in this repo locally

### ISSUE THREAD

**Issue by chenbohua3** [actions/virtual-environments#3084]
This may be helpful for debugging purpose when i need to construct new images based on images in this repo.

**Comment by al-cheb** [comment]
Hello, @chenbohua3 
You can build images loccaly - https://github.com/actions/virtual-environments/issues/931#issue-623549762

**Comment by miketimofeev** [comment]
Hi @chenbohua3!
As @al-cheb mentioned a few solutions are described in the previous issue. 
I'm going to close this one but please feel free to ask additional questions in the discussions https://github.com/actions/virtual-environments/discussions — it's more convenient to use them for such topics.
Thank you!

**Comment by chenbohua3** [comment]
@al-cheb @miketimofeev thanks a lot!
