### ISSUE TITLE
Windows2019-Readme.md has duplicate Python entries

### ISSUE THREAD

**Issue by dumbledad** [actions/virtual-environments#310]
https://github.com/actions/virtual-environments/blob/master/images/win/Windows2019-Readme.md contains the following duplicated text

Python
Version: 2.7.17 (x64)
Version: 3.5.4 (x64)
Version: 3.6.8 (x64)
Version: 3.7.6 (x64)
Version: 3.8.1 (x64)

Python
Version: 2.7.17 (x64)
Version: 3.5.4 (x64)
Version: 3.6.8 (x64)
Version: 3.7.6 (x64)
Version: 3.8.1 (x64)
Version: 2.7.17 (x86)
Version: 3.5.4 (x86)
Version: 3.6.8 (x86)
Version: 3.7.6 (x86)
Version: 3.8.1 (x86)

(I think the first of these two Python sections can be deleted since it is repeated in the second one. Or one heading should conatin the python x64 entries and the second just the x86 ones)

**Comment by miketimofeev** [comment]
@dumbledad We haven't seen any duplicates, but anyway decided to make some improvements, which will be rolled out this week. 
Thank you!

**Comment by miketimofeev** [comment]
Readme has been modified. Closing the issue.
