### ISSUE TITLE
sshpass has disappeared from command line on Ubuntu 18.04

### ISSUE THREAD

**Issue by kauemendes** [actions/virtual-environments#3102]
Hi all. 

I am currently using an image that I have built on April 1st. Using the Ubuntu 18.04 branch `releases/ubuntu18/20210330`. 

In the VMs using the previous builds, I was able to use `sshpass` command fine. l look through a lot of commits before coming here, trying to understand if perhaps some step was added at the process removing/not installing the sshpass command for "security reasons", but I couldn't find anything in the repository if someone could enlight me, why sshpass is not available on this new image built from `releases/ubuntu18/20210330`. 

Perhaps it was included on the openssh-client package (I couldnt find anything related to that) or perhaps it was already there on Ubuntu since always, but a new patch removed. I don't know.  Hope you guys could help me with this. 

(I am not sure if this is supposed to be here or at the Community Forum.)

THANKS ;)

**Comment by al-cheb** [comment]
Hello, @kauemendes 
Previously the `sshpass` pkg was pre-installed as part of `ansible.sh` script. We are planning to pre-install the `sshpass` pkg in scope of the https://github.com/actions/virtual-environments/pull/3103 PR.

E.g:
https://github.visualstudio.com/virtual-environments/_build/results?buildId=103704&view=logs&j=011e1ec8-6569-5e69-4f06-baf193d1351e&t=5431112d-2b61-5a5f-7042-ef698f761043

```
 azure-arm: The following additional packages will be installed:
    azure-arm:   python-cffi-backend python-cryptography python-ecdsa python-enum34
    azure-arm:   python-httplib2 python-idna python-ipaddress python-jinja2 python-markupsafe
    azure-arm:   python-paramiko python-pkg-resources python-pyasn1 python-setuptools
    azure-arm:   python-yaml sshpass
```

Temporary workaround:
`        run:   sudo apt install sshpass`

**Comment by kauemendes** [comment]
Cheers @al-cheb for your prompt response. 

I already sent the workaround for our developers here.

And I will be attentive to PR #3103 to generate a new image here! 

Thanks Again!

**Comment by al-cheb** [comment]
The new images with `sshpass` have been deployed.
