### ISSUE TITLE
Add powershell core to hosted agents

### ISSUE THREAD

**Issue by digeler** [actions/virtual-environments#3106]
**Tool information**
- Tool name: powershell core
- Tool license: 
- Add or update? Add
- Desired version:  latest
- Approximate size: 
- If this is an add request:
  - Brief description of tool: powershell core
  - URL for tool's homepage: 
  - Provide a basic test case to validate the tool's functionality: 

**Area for Triage**:

**Question, Bug, or Feature?**:
Question

**Virtual environments affected**
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [ x] Windows Server 2019

**Can this tool be installed during the build?**

**Tool installation time in runtime**

**Are you willing to submit a PR?**

**Comment by al-cheb** [comment]
Hello, @digeler 
PowerShell Core is the default shell for Windows Server hosted agents and pre-installed on Windows Server/Ubuntu/macOS. Please check PowerShell section in the documentation:
Windows Server 2016 - https://github.com/actions/virtual-environments/blob/main/images/win/Windows2016-Readme.md
Windows Server 2019 - https://github.com/actions/virtual-environments/blob/releases/win19/20210330/images/win/Windows2019-Readme.md

#### PowerShell Tools
- PowerShell 7.1.3

E.g:
```
jobs:
  build:
    runs-on: windows-latest
    steps:

      - name: pwsh
        run:  $PSVersionTable
```

![image](https://user-images.githubusercontent.com/47745270/113666430-f47dd180-96b7-11eb-8023-96aec2381a94.png)
