### ISSUE TITLE
[windows, ubuntu] Few outdated Docker images will be removed on April, 12

### ISSUE THREAD

**Issue by AlenaSviridenko** [actions/virtual-environments#3111]
**Breaking changes**
The following Docker images will be removed from Ubuntu images on April, 12:
- alpine:3.7
- alpine:3.8
- alpine:3.9
- alpine:3.10
- debian:8
- ubuntu:14.04

The following Docker image will be removed from Windows images on April, 12:
- microsoft/aspnetcore-build:1.0-2.0

**Target date**
Images deployment will start on April, 12, and will take 3-4 days.

**The motivation for the changes**
These images have reached EOL and will be replaced with new ones. More details can be found in https://github.com/actions/virtual-environments/issues/2963 and https://github.com/actions/virtual-environments/issues/2962
New images for Ubuntu:
- alpine:3.13
- alpine:3.12
- alpine:3.12
- debian:10
- ubuntu:20.04
- ubuntu:18.04
- ubuntu:16.04

New image for Windows:
- mcr.microsoft.com/dotnet/framework/sdk:4.8-windowsservercore-ltsc2019

**Possible impact**
If the required docker image is not available locally on a machine, the docker daemon will automatically pull the latest copy of the image from your configured registry. This will increase build time by approximately 15 seconds for each docker image.

**Virtual environments affected**
- [x] Ubuntu 16.04
- [x] Ubuntu 18.04
- [x] Ubuntu 20.04
- [ ] macOS 10.13
- [ ] macOS 10.14
- [ ] macOS 10.15
- [ ] macOS 11.0
- [x] Windows Server 2016 R2
- [x] Windows Server 2019

**Mitigation ways**
If you need to pull these images from a registry by yourself, please consider using `docker image pull <image_name>`.

**Comment by AlenaSviridenko** [comment]
Images with the changes were deployed everywhere, closing this ticket

**Comment by BrianMouncer** [comment]
I am looking through the existing issues looking for the support lifetime of your Ubuntu 16.04 hosted agent (not this docker image).

Can you please confirm that the Ubuntu 16.04 msft hosted agent will still be hosted for at least the next year?

Thanks,

**Comment by AlenaSviridenko** [comment]
Hi, @BrianMouncer
Actually, Canonical drops support of Ubuntu 16.04, and its usage is pretty low, so we are in a process of planning its deprecation in the next 6 month.
