### ISSUE TITLE
Cannot run Ansible playbook

### ISSUE THREAD

**Issue by PawPaw** [actions/virtual-environments#3114]
**Description**  
I am not able to run ansible playbook on latest image of Ubuntu 20.04.

**Area for Triage**:  

**Bug**:  

**Virtual environments affected**  
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [X] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Image version**

ubuntu-20.04 20210330.1

**Expected behavior**  
Ansible playbook will run wihout error

**Actual behavior**  
2021-04-06T07:45:06.8417009Z ERROR! Unexpected Exception, this is probably a bug: No module named 'msrest'
2021-04-06T07:45:06.9046952Z the full traceback was:
2021-04-06T07:45:06.9047577Z 
2021-04-06T07:45:06.9048399Z Traceback (most recent call last):
2021-04-06T07:45:06.9049836Z   File "/opt/pipx_bin/ansible-playbook", line 123, in <module>
2021-04-06T07:45:06.9050250Z     exit_code = cli.run()
2021-04-06T07:45:06.9050898Z   File "/opt/pipx/venvs/ansible-base/lib/python3.8/site-packages/ansible/cli/playbook.py", line 110, in run
2021-04-06T07:45:06.9051378Z     loader, inventory, variable_manager = self._play_prereqs()
2021-04-06T07:45:06.9052283Z   File "/opt/pipx/venvs/ansible-base/lib/python3.8/site-packages/ansible/cli/__init__.py", line 467, in _play_prereqs
2021-04-06T07:45:06.9053446Z     inventory = InventoryManager(loader=loader, sources=options['inventory'])
2021-04-06T07:45:06.9055119Z   File "/opt/pipx/venvs/ansible-base/lib/python3.8/site-packages/ansible/inventory/manager.py", line 166, in __init__
2021-04-06T07:45:06.9055941Z     self.parse_sources(cache=True)
2021-04-06T07:45:06.9056689Z   File "/opt/pipx/venvs/ansible-base/lib/python3.8/site-packages/ansible/inventory/manager.py", line 224, in parse_sources
2021-04-06T07:45:06.9057149Z     parse = self.parse_source(source, cache=cache)
2021-04-06T07:45:06.9058136Z   File "/opt/pipx/venvs/ansible-base/lib/python3.8/site-packages/ansible/inventory/manager.py", line 275, in parse_source
2021-04-06T07:45:06.9058607Z     for plugin in self._fetch_inventory_plugins():
2021-04-06T07:45:06.9059292Z   File "/opt/pipx/venvs/ansible-base/lib/python3.8/site-packages/ansible/inventory/manager.py", line 203, in _fetch_inventory_plugins
2021-04-06T07:45:06.9059739Z     plugin = inventory_loader.get(name)
2021-04-06T07:45:06.9060324Z   File "/opt/pipx/venvs/ansible-base/lib/python3.8/site-packages/ansible/plugins/loader.py", line 782, in get
2021-04-06T07:45:06.9061348Z     return self.get_with_context(name, *args, **kwargs).object
2021-04-06T07:45:06.9062450Z   File "/opt/pipx/venvs/ansible-base/lib/python3.8/site-packages/ansible/plugins/loader.py", line 802, in get_with_context
2021-04-06T07:45:06.9062956Z     self._module_cache[path] = self._load_module_source(name, path)
2021-04-06T07:45:06.9063883Z   File "/opt/pipx/venvs/ansible-base/lib/python3.8/site-packages/ansible/plugins/loader.py", line 766, in _load_module_source
2021-04-06T07:45:06.9064362Z     spec.loader.exec_module(module)
2021-04-06T07:45:06.9064707Z   File "<frozen importlib._bootstrap_external>", line 783, in exec_module
2021-04-06T07:45:06.9065143Z   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
2021-04-06T07:45:06.9065644Z   File "/home/vsts/.ansible/collections/ansible_collections/azure/azcollection/plugins/inventory/azure_rm.py", line 130, in <module>
2021-04-06T07:45:06.9071570Z     from msrest import ServiceClient, Serializer, Deserializer
2021-04-06T07:45:06.9072534Z ModuleNotFoundError: No module named 'msrest'

**Repro steps**  
1. In ansible.cfg enable in section [inventory] in enable_plugins plugin "azure_rm":
enable_plugins = host_list, ini, azure_rm yaml, auto
Run any playbook.
2. output from pip3 list on agent:
Package                        Version             
------------------------------ --------------------
adal                           1.2.7               
ansible                        3.2.0               
ansible-base                   2.10.7              
applicationinsights            0.11.9              
argcomplete                    1.12.2              
attrs                          19.3.0              
Automat                        0.8.0               
azure-cli-core                 2.11.1              
azure-cli-nspkg                3.0.2               
azure-cli-telemetry            1.0.6               
azure-common                   1.1.11              
azure-core                     1.14.0b1            
azure-graphrbac                0.61.1              
azure-keyvault                 1.0.0a1             
azure-mgmt-authorization       0.51.1              
azure-mgmt-automation          0.1.1               
azure-mgmt-batch               5.0.1               
azure-mgmt-cdn                 3.0.0               
azure-mgmt-compute             10.0.0              
azure-mgmt-containerinstance   1.4.0               
azure-mgmt-containerregistry   2.0.0               
azure-mgmt-containerservice    9.1.0               
azure-mgmt-core                1.2.0               
azure-mgmt-cosmosdb            0.5.2               
azure-mgmt-devtestlabs         3.0.0               
azure-mgmt-dns                 2.1.0               
azure-mgmt-hdinsight           0.1.0               
azure-mgmt-iothub              0.7.0               
azure-mgmt-keyvault            1.1.0               
azure-mgmt-loganalytics        1.0.0               
azure-mgmt-managedservices     1.0.0               
azure-mgmt-marketplaceordering 0.1.0               
azure-mgmt-monitor             0.5.2               
azure-mgmt-network             10.2.0              
azure-mgmt-nspkg               2.0.0               
azure-mgmt-privatedns          0.1.0               
azure-mgmt-rdbms               1.4.1               
azure-mgmt-redis               5.0.0               
azure-mgmt-resource            10.2.0              
azure-mgmt-servicebus          0.5.3               
azure-mgmt-sql                 0.10.0              
azure-mgmt-storage             11.1.0              
azure-mgmt-trafficmanager      0.50.0              
azure-mgmt-web                 0.41.0              
azure-nspkg                    2.0.0               
azure-storage                  0.35.1              
bcrypt                         3.2.0               
blinker                        1.4                 
cachetools                     4.2.1               
certifi                        2019.11.28          
cffi                           1.14.5              
chardet                        3.0.4               
Click                          7.0                 
cloud-init                     20.4                
colorama                       0.4.4               
command-not-found              0.3                 
configobj                      5.0.6               
constantly                     15.1.0              
crcmod                         1.7                 
crit                           0.0.1               
cryptography                   2.8                 
dbus-python                    1.2.16              
distro                         1.4.0               
distro-info                    0.23ubuntu1         
docker                         4.4.4               
entrypoints                    0.3                 
google-auth                    1.28.0              
httplib2                       0.14.0              
humanfriendly                  8.2                 
hyperlink                      19.0.0              
idna                           2.8                 
importlib-metadata             1.5.0               
incremental                    16.10.1             
isodate                        0.6.0               
Jinja2                         2.10.1              
jmespath                       0.10.0              
jsonpatch                      1.22                
jsonpointer                    2.0                 
jsonschema                     3.2.0               
junit-xml                      1.9                 
keyring                        18.0.1              
knack                          0.7.2               
kubernetes                     12.0.1              
language-selector              0.1                 
launchpadlib                   1.10.13             
lazr.restfulclient             0.14.2              
lazr.uri                       1.0.3               
MarkupSafe                     1.1.0               
more-itertools                 4.2.0               
msal                           1.0.0               
msal-extensions                0.1.3               
msrest                         0.6.10              
msrestazure                    0.6.4               
netifaces                      0.10.4              
ntlm-auth                      1.5.0               
oauthlib                       3.1.0               
openshift                      0.12.0              
packaging                      20.9                
paramiko                       2.7.2               
pexpect                        4.6.0               
pip                            20.0.2              
pipx                           0.16.1.0            
pkginfo                        1.7.0               
portalocker                    1.7.1               
protobuf                       3.6.1               
py3winrm                       0.0.1               
pyasn1                         0.4.2               
pyasn1-modules                 0.2.1               
pycparser                      2.20                
Pygments                       2.3.1               
PyGObject                      3.36.0              
PyHamcrest                     1.9.0               
PyJWT                          1.7.1               
pymacaroons                    0.13.0              
pymssql                        2.1.5               
PyNaCl                         1.3.0               
pyOpenSSL                      19.0.0              
pyparsing                      2.4.7               
pyparted                       3.11.2              
pyrsistent                     0.15.5              
pyserial                       3.4                 
pyspnego                       0.1.5               
python-apt                     2.0.0+ubuntu0.20.4.4
python-dateutil                2.8.1               
python-debian                  0.1.36ubuntu1       
python-string-utils            1.0.0               
pywinrm                        0.4.1               
PyYAML                         5.3.1               
requests                       2.22.0              
requests-credssp               1.2.0               
requests-ntlm                  1.1.0               
requests-oauthlib              1.3.0               
requests-unixsocket            0.2.0               
rsa                            4.7.2               
ruamel.yaml                    0.17.2              
ruamel.yaml.clib               0.2.2               
SecretStorage                  2.3.1               
service-identity               18.1.0              
setuptools                     45.2.0              
simplejson                     3.16.0              
six                            1.14.0              
sos                            4.0                 
ssh-import-id                  5.10                
systemd-python                 234                 
tabulate                       0.8.9               
Twisted                        18.9.0              
ubuntu-advantage-tools         20.3                
ufw                            0.36                
urllib3                        1.25.8              
userpath                       1.4.2               
wadllib                        1.3.3               
WALinuxAgent                   2.2.46              
websocket-client               0.58.0              
wheel                          0.34.2              
xmltodict                      0.12.0              
zipp                           1.0.0               
zope.interface                 4.7.1

**Comment by al-cheb** [comment]
Hello, @PawPaw 
We reworked ansible installation to use pipx. Please install module 'msrest' in runtime.

```
 - name: Install Ansible dependencies
   run: pipx inject ansible-base msrest
```
![image](https://user-images.githubusercontent.com/47745270/113681016-2f890080-96ca-11eb-85d6-5cdaceb7cf6d.png)

**Comment by PawPaw** [comment]
Solved, thanks for fast reply.
