### ISSUE TITLE
Windows 20210330.2 image causes NuGet restore to fail when using a MSBuild.Sdk.Extras project

### ISSUE THREAD

**Issue by Maxgamerboy1** [actions/virtual-environments#3116]
**Description**  
Using new Windows 20210330.2 image causes NuGet restore to fail when using a MSBuild.Sdk.Extras project. May be caused by using the new MSBuild v16.9.0.16703
The old Windows image 20210316.1 uses MSBuild v16.9.0.11203 and this works

**Area for Triage**:  

Scripting and command line, Packages

**Question, Bug, or Feature?**:  

Bug

**Virtual environments affected**  
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [x] Windows Server 2019

**Image version**

Image version where you are experiencing the issue.
20210330.2 

**Expected behavior**  
To restore the MSBuild.Sdk.Extras correcly

**Actual behavior**  
Runtime error describing the MSBuild.Sdk.Extras cannot be found when restoring
```
Starting: NuGet Restore
==============================================================================
Task         : NuGet
Description  : Restore, pack, or push NuGet packages, or run a NuGet command. Supports NuGet.org and authenticated feeds like Azure Artifacts and MyGet. Uses NuGet.exe and works with .NET Framework apps. For .NET Core and .NET Standard apps, use the .NET Core task.
Version      : 2.179.0
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/package/nuget
==============================================================================
"C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/MSBuild/Current/Bin/msbuild.exe" /version /nologo
SYSTEMVSSCONNECTION exists true
SYSTEMVSSCONNECTION exists true
C:\Windows\system32\chcp.com 65001
Active code page: 65001
Detected NuGet version 5.9.0.7134 / 5.9.0+685acd761481e83715ba76ecddc680f5ed2378b5.685acd761481e83715ba76ecddc680f5ed2378b5
SYSTEMVSSCONNECTION exists true
C:\hostedtoolcache\windows\NuGet\5.9.0\x64\nuget.exe sources Add -NonInteractive -Name NuGetOrg -Source https://api.nuget.org/v3/index.json -ConfigFile D:\a\1\Nuget\tempNuGet_516201.config
Package source with Name: NuGetOrg added successfully.
C:\hostedtoolcache\windows\NuGet\5.9.0\x64\nuget.exe restore D:\a\1\s\[path.to.project].sln -Verbosity Detailed -NonInteractive -ConfigFile D:\a\1\Nuget\tempNuGet_516201.config
D:\a\1\s\[path.to.project].csproj : error : Unable to find package MSBuild.Sdk.Extras. No packages exist with this id in source(s): Microsoft Visual Studio Offline Packages
D:\a\1\s\[path.to.project].csproj : error : C:\Program Files\dotnet\sdk\5.0.201\Sdks\MSBuild.Sdk.Extras\Sdk not found. Check that a recent enough .NET SDK is installed and/or increase the version specified in global.json.
D:\a\1\s\[path.to.project].csproj : error MSB4236: The SDK 'MSBuild.Sdk.Extras/2.0.54' specified could not be found.

NuGet Version: 5.9.0.7134
MSBuild auto-detection: using msbuild version '16.9.0.16703' from 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\bin'. Use option -MSBuildVersion to force nuget to use a specific version of MSBuild.

```

**Repro steps**  
Use Azure Pipelines to restore a MSBuild.Sdk.Extras project. See the NuGet Restore step fails

**Comment by al-cheb** [comment]
Hello, @Maxgamerboy1 
Could you please check the workaround - https://github.com/xamarin/XamarinCommunityToolkit/pull/1173 ?

**Comment by Maxgamerboy1** [comment]
I have applied this change and it appears to have worked! Thanks for the quick response!
Do you know if this will be changed in a future Windows image?

**Comment by al-cheb** [comment]
> I have applied this change and it appears to have worked! Thanks for the quick response!
> Do you know if this will be changed in a future Windows image, so we can remove this workaround?

It can unpredictable happen if you don't have a nuget.config file in your repro -  https://github.com/NuGet/Home/issues/10586#issuecomment-783689013 . Example nuget.config - https://github.com/actions/setup-dotnet/issues/155#issuecomment-761195782

**Comment by Maxgamerboy1** [comment]
Awesome, I'll look into adding this. I'm happy to close this issue for now. Thanks again.
