### ISSUE TITLE
Azure Pipeline started failing for image version 20210330.2.

### ISSUE THREAD

**Issue by agkusha** [actions/virtual-environments#3118]
**Description**  
Our pipeline started failing after agent version changed to 20210330.2. It was working fine for version 20210316.1. 
Is there a way that I can specify agent version along with agent windows-2019? 

**Area for Triage**:  

**Question, Bug, or Feature?**:  
Bug

**Image version**
20210330.2

**Expected behavior**  
Pipeline should run successfully as it was running in 20210316.1. 

**Actual behavior**  
Pipeline is failing for agent version 20210330.2

**Repro steps**  
Successful pipeline:
https://msdata.visualstudio.com/A365/_releaseProgress?releaseId=63278&_a=release-environment-logs&environmentId=270577

Failed pipeline:
https://msdata.visualstudio.com/A365/_releaseProgress?releaseId=63278&_a=release-environment-logs&environmentId=270576

**Comment by al-cheb** [comment]
Hello, @agkusha 
We don't have access to the pipelines logs. Could you please update the title and attach the logs?

**Comment by agkusha** [comment]
Hi,
I have attached failed and success log.
[failed.log](https://github.com/actions/virtual-environments/files/6266289/failed.log)
[success.log](https://github.com/actions/virtual-environments/files/6266291/success.log)

**Comment by al-cheb** [comment]
> Hi,
> I have attached failed and success log. These are init job logs.
> [failed.log](https://github.com/actions/virtual-environments/files/6266289/failed.log)
> [success.log](https://github.com/actions/virtual-environments/files/6266291/success.log)

These logs don't contain any details related to a build.

**Comment by agkusha** [comment]
Yes, these logs were the reference to agent version details. We are trying to download and install az cli extension. By referring to failed and success 'download and install' task, we figured out agent version differs. All failed 'download and install task' have updated agent version (20210330.2)

**Comment by al-cheb** [comment]
> Yes, these logs were the reference to agent version details. We are trying to download and install az cli extension. By referring to failed and success 'download and install' task, we figured out agent version differs. All failed 'download and install task' have updated agent version (20210330.2)

Could you please provide steps to reproduce an issue?

**Comment by maxim-lobanov** [comment]
@agkusha, Consider the privacy of repository, I suggest contact Azure DevOps support for further investigation of this issue. Support engineers will be able to retrieve full logs from your builds and escalate to appropriate team. it will simplify analyzing.

In this repository, we won't be able to access your logs.
