### ISSUE TITLE
Ubuntu 18.04 agents have unexpected default locale

### ISSUE THREAD

**Issue by dougbu** [actions/virtual-environments#3120]
**Description**  
We (ASP.NET Core team) are attempting to move from Ubuntu 16.04 to 18.04 Microsoft-hosted agents. Our builds are failing because `libicu60` is not installed on the newer agents. See also https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu1604-README.md (where `libicu55` is installed) versus https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu1804-README.md (where the string `icu` isn't matched at all).

**Area for Triage**:  

Packages

**Question, Bug, or Feature?**:  

Bug

But if there's a task to install `libicu60` (the version aligned with Ubuntu 18.04) in our pipelines, I'm all ears.

**Virtual environments affected**  
- [x] Ubuntu 16.04
- [x] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Image version**

Image version where you are experiencing the issue.
20210330.1

**Expected behavior**  
A description of what you expected to happen.
Expect our tests to continue working correctly. Note https://docs.microsoft.com/en-us/dotnet/core/install/linux-ubuntu#dependencies lists `libicu60` as a prerequisite for .NET Core on Ubuntu.

**Actual behavior**  
A description of what is actually happening.
`libicu60` is missing from the image and some of our tests are failing due to string ordering issues. See for example failures in https://dev.azure.com/dnceng/public/_build/results?buildId=1073540

**Repro steps**  
A description with steps to reproduce the issue. If your have a public example or repo to share,
please provide the link.

Rerun one of the following PR validation builds
- https://github.com/aspnet/BuildTools/pull/997
- https://github.com/dotnet/aspnetcore/pull/31547
- https://github.com/dotnet/extensions/pull/3855
- https://github.com/dotnet/efcore/pull/24592

**Comment by al-cheb** [comment]
Hello, @dougbu 
The `libicu60` is already pre-install on Ubuntu Server 18.04.

```
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:

      - name: libicu60
        run: dpkg -l | grep libicu60
```

![image](https://user-images.githubusercontent.com/47745270/113763646-976b3580-9722-11eb-9e5d-6525b3c3e505.png)

**Comment by dougbu** [comment]
@al-cheb was that changed in the last day or so❔ And, are you saying https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu1804-README.md is not up-to-date❔

Separately, are the agents used for Azure Pipelines and GitHub Actions different despite the fact https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops&tabs=yaml#software links to the above README.md file❔

The missing package would _completely_ explain the test failures we're seeing for the listed PRs.

**Comment by dougbu** [comment]
Shoot. The agents aren't appropriate for our builds but the problem isn't as simple as adding `libicu60`. For example, I tried a manual installation of the package in aspnet/BuildTools#998 and saw similar output to you @al-cheb: `libicu60 is already the newest version (60.2-3ubuntu3.1).` at https://dev.azure.com/dnceng/public/_build/results?buildId=1074813&view=logs&j=5818c23b-5f5e-5596-064a-6c64d403371a&t=28aca32c-5ccf-5757-b167-7b688276e977&l=17. This is now basically a documentation issue because https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu1804-README.md doesn't list the included `libicu60` package.

Not sure where to look next to enable us to use the newer Ubuntu agents&hellip;

**Comment by al-cheb** [comment]
> @al-cheb was that changed in the last day or so❔ And, are you saying https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu1804-README.md is not up-to-date❔

We don't include every version of pre-installed  packages in the documentation file.

> Separately, are the agents used for Azure Pipelines and GitHub Actions different despite the fact https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops&tabs=yaml#software links to the above README.md file❔

It's the same image Azure Pipelines and GitHub Action .

**Comment by al-cheb** [comment]
Looks like the tests are fixed - https://github.com/aspnet/BuildTools/pull/1000

**Comment by dougbu** [comment]
@al-cheb that PR validated using Ubuntu 16.04. The root cause of the test failures is an unexpected locale (`C.UTF-8`) on the 18.04 agents. Will let you know when I've tested the solution. Still catching up on the morning's email&hellip;

**Comment by dougbu** [comment]
Did a quick test with aspnet/BuildTools#999. On Ubuntu 16.04 agents, the default locale is `en_US.UTF-8` while on 18.04 agents, it's `C.UTF-8`. This isn't a great idea for .NET Core 2.1 and the difference between the two platforms is unexpected. Does this repo set the locale for the agents❔ Or is this a change Canonical made between the two versions❔

I only see `LC_ALL` mentioned in https://github.com/actions/virtual-environments/blob/b7f276c003aea42575b52247bdb2183e355fca2f/images/macos/provision/configuration/environment/bashrc but there are other ways to control the locale&hellip;

## Ubuntu 16.04

``` text
Script contents:
locale
========================== Starting Command Output ===========================
/bin/bash --noprofile --norc /home/vsts/work/_temp/46cde479-ce11-437b-a209-2ffec3c7eea6.sh
LANG=en_US.UTF-8
LANGUAGE=
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
```

## Ubuntu 18.04

``` text
Script contents:
locale
========================== Starting Command Output ===========================
/bin/bash --noprofile --norc /home/vsts/work/_temp/b531dbb7-bdb2-4246-95f9-6c8990e6bda0.sh
LANG=C.UTF-8
LANGUAGE=
LC_CTYPE="C.UTF-8"
LC_NUMERIC="C.UTF-8"
LC_TIME="C.UTF-8"
LC_COLLATE="C.UTF-8"
LC_MONETARY="C.UTF-8"
LC_MESSAGES="C.UTF-8"
LC_PAPER="C.UTF-8"
LC_NAME="C.UTF-8"
LC_ADDRESS="C.UTF-8"
LC_TELEPHONE="C.UTF-8"
LC_MEASUREMENT="C.UTF-8"
LC_IDENTIFICATION="C.UTF-8"
LC_ALL=
```

## Workaround

Fortunately, the workaround is pretty simple and no `locale-gen` is needed. I just set `LC_ALL`, `LANG` and `LANGUAGE` to `en_US.UTF-8`.

But, if it's an unintended change between the two images, I suggest that be corrected.

**Comment by dougbu** [comment]
Renamed to reflect current understanding of the problem.

/btw
> > @al-cheb was that changed in the last day or so❔ And, are you saying https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu1804-README.md is not up-to-date❔

> We don't include every version of default pre-installed packages in the documentation file.

Ah, makes sense 😺

**Comment by al-cheb** [comment]
We don't have any plans to change the default locale on Azure Ubuntu iamges provided by Canonical - https://stackoverflow.com/questions/55673886/what-is-the-difference-between-c-utf-8-and-en-us-utf-8-locales

![image](https://user-images.githubusercontent.com/47745270/113979774-5ec87a80-984e-11eb-8fe6-c36bdd1bc02d.png)

OS|locale|locale -a | /etc/default/locale
---|-------|----------|---------------------
Ubuntu Server 16.04|LANG=en_US.UTF-8<br>LANGUAGE=<br>LC_CTYPE="en_US.UTF-8"<br>LC_NUMERIC="en_US.UTF-8"<br>LC_TIME="en_US.UTF-8"<br>LC_COLLATE="en_US.UTF-8"<br>LC_MONETARY="en_US.UTF-8"<br>LC_MESSAGES="en_US.UTF-8"<br>LC_PAPER="en_US.UTF-8"<br>LC_NAME="en_US.UTF-8"<br>LC_ADDRESS="en_US.UTF-8"<br>LC_TELEPHONE="en_US.UTF-8"|C<br>C.UTF-8<br>en_US.utf8<br>POSIX | LANG=en_US.UTF-8
Ubuntu Server 18.04|LANG=C.UTF-8<br>LANGUAGE=<br>LC_CTYPE="C.UTF-8"<br>LC_NUMERIC="C.UTF-8"<br>LC_TIME="C.UTF-8"<br>LC_COLLATE="C.UTF-8"<br>LC_MONETARY="C.UTF-8"<br>LC_MESSAGES="C.UTF-8"<br>LC_PAPER="C.UTF-8"<br>LC_NAME="C.UTF-8"<br>LC_ADDRESS="C.UTF-8"<br>LC_TELEPHONE="C.UTF-8"<br>LC_MEASUREMENT="C.UTF-8"<br>LC_IDENTIFICATION="C.UTF-8"<br>LC_ALL=|C<br>C.UTF-8<br>POSIX<br>en_US.utf8|LANG=C.UTF-8
Ubuntu Server 20.04|LANG=C.UTF-8<br>LANGUAGE=<br>LC_CTYPE="C.UTF-8"<br>LC_NUMERIC="C.UTF-8"<br>LC_TIME="C.UTF-8"<br>LC_COLLATE="C.UTF-8"<br>LC_MONETARY="C.UTF-8"<br>LC_MESSAGES="C.UTF-8"<br>LC_PAPER="C.UTF-8"<br>LC_NAME="C.UTF-8"<br>LC_ADDRESS="C.UTF-8"<br>LC_TELEPHONE="C.UTF-8"<br>LC_MEASUREMENT="C.UTF-8"<br>LC_IDENTIFICATION="C.UTF-8"<br>LC_ALL=|C<br>C.UTF-8<br>POSIX<br>en_US.utf8|LANG=C.UTF-8
Ubuntu Server 20.10|LANG=C.UTF-8<br>LANGUAGE=<br>LC_CTYPE="C.UTF-8"<br>LC_NUMERIC="C.UTF-8"<br>LC_TIME="C.UTF-8"<br>LC_COLLATE="C.UTF-8"<br>LC_MONETARY="C.UTF-8"<br>LC_MESSAGES="C.UTF-8"<br>LC_PAPER="C.UTF-8"<br>LC_NAME="C.UTF-8"<br>LC_ADDRESS="C.UTF-8"<br>LC_TELEPHONE="C.UTF-8"<br>LC_MEASUREMENT="C.UTF-8"<br>LC_IDENTIFICATION="C.UTF-8"<br>LC_ALL=|C<br>C.UTF-8<br>POSIX<br>en_US.utf8|LANG=C.UTF-8

**Comment by dougbu** [comment]
:ok: I'll stick w/ our workaround.

/cc @juntaoluo @wtgodbe, please do the same in the branches and repos you're updating.

**Comment by dougbu** [comment]
See the bottom of https://github.com/actions/virtual-environments/issues/3120#issuecomment-815244409 for the workaround I meant
