### ISSUE TITLE
Azure OMSExtension fails to install in Ubuntu 20.04 due to python-ctypes problem

### ISSUE THREAD

**Issue by bartwitkowski** [actions/virtual-environments#3123]
**Description**  
According to Microsoft problems regarding Python and OMSExtension in Ubuntu 20.04 were resolved from version 1.13.27 of the agent. Meaning, that the installer can use either Python 2.x or Pyton 3.x but ctypes module is required in both. MS Azure Ubuntu 20.04 image works with OMSExtension.

**Area for Triage**:  
Python

**Question, Bug, or Feature?**:  
Bug

**Virtual environments affected**  
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [x] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Image version**
Release 20210318

**Expected behavior**  
OMSExtension installer should use Python ctypes module.

**Actual behavior**  
Installing OMSExtension using ARM template or Ansible with arm module or az cli throws an error:
> 2021/04/06 10:43:37 Using python2
2021/04/06 10:43:37 Checking for ctypes python module...
2021/04/06 10:43:37 Error: Python does not support ctypes on this system.  Please install the ctypes module for Python or upgrade to a newer version of python that comes with the ctypes module.
2021/04/06 10:43:37 Please remove the omi package and try again after installing the ctypes module or upgrading Python.  You can check if the ctypes module is installed by starting python and running the command: 'import ctypes'

**Comment by bartwitkowski** [comment]
Just tested in Ubuntu 18.04 release 20210405 using ARM template and az cli. And it works as expected. So problem is in Ubuntu 20.04.

**Comment by Darleev** [comment]
Hello @bartwitkowski,
It seems I found [very similar issue](https://github.com/microsoft/OMS-Agent-for-Linux/issues/1217) in OMS agent Github repository. Could you please check your OMG agent version and select it accordingly?
If it does not help with the issue, I would recommend you address this question directly to [OMS agent repository](https://github.com/microsoft/OMS-Agent-for-Linux).
We are looking forward to you reply.

**Comment by Darleev** [comment]
Hello @bartwitkowski,
Did you try to change OMS agent versions? Could you please provide an update on this?
We are looking forward to your reply.

**Comment by Darleev** [comment]
@bartwitkowski [the following issue](https://github.com/microsoft/OMS-Agent-for-Linux/issues/1318) contains the same problem as described in the initial request. You can track the status in the OMG Agent repository further.
I'm going to close the issue for now.
Feel free to contact us in case of any questions.

**Comment by bartwitkowski** [comment]
Hi @Darleev , yesterday I've tried to add comment, but comments were disabled - strange :/.
Anyway, OMSExtension version 1.13.35 works for me on Ubuntu 18.04 release 20210405 but not Ubuntu 20.04.
