### ISSUE TITLE
Error trying to rebuild 2019 Server image: Votive2019.vsix returing 2003

### ISSUE THREAD

**Issue by tiernano** [actions/virtual-environments#3125]
**Description**  
When trying to rebuild a Windows Server 2019 image for our own scale set buids, the process fails after 1 hour 22 min with the following error 2003 and fails VHD build.

**Area for Triage**:  
Packages

**Question, Bug, or Feature?**:  
Bug

**Virtual environments affected**  
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [X] Windows Server 2019

**Image version**
Main branch on 7 April 2021 12.10PM GMT

**Expected behavior**  
Package installs without error

**Actual behavior**  
    vhd: Package installed: wixtoolset|3.11.2
    vhd: Downloading package from: https://wixtoolset.gallerycdn.vsassets.io/extensions/wixtoolset/wixtoolsetvisualstudio2019extension/1.0.0.4/1563296438961/Votive2019.vsix to path C:\Users\packer\AppData\Local\Temp\Votive2019.vsix .
    vhd: Starting Install Votive2019.vsix...
    vhd: Unsuccessful exit code returned by the installation process: 2003.
==> vhd: Provisioning step had errors: Running the cleanup provisioner, if present...

and then VHD and build is destroyed.

**Repro steps**  
A description with steps to reproduce the issue. If your have a public example or repo to share,
please provide the link.

1. clone repo
2. create variable file for 2019
3. run packer build -var-file .\win2019-var.json .\windows2019.json
4. watch after 1 hour 22 min (give or take) as the build fails and the image is killed.

**Comment by al-cheb** [comment]
Hello, @tiernano 
Could you please provide?
1. `curl.exe -v https://wixtoolset.gallerycdn.vsassets.io/extensions/wixtoolset/wixtoolsetvisualstudio2019extension/1.0.0.4/1563296438961/Votive2019.vsix --output Votive2019.vsix`
2. Location
3. `curl ipinfo.io`

**Comment by tiernano** [comment]
I need to get a build server built up again today and make sure it doesnt get killed when it fails. It will take a few hours, so leave it with me. My Geo location is Dublin, but i am building these inside Central US in Azure... I will get that info ASAK.

**Comment by al-cheb** [comment]
> I need to get a build server built up again today and make sure it doesnt get killed when it fails. It will take a few hours, so leave it with me. My Geo location is Dublin, but i am building these inside Central US in Azure... I will get that info ASAK.

We use `West US 2` Azure location for the image generation process - https://github.visualstudio.com/virtual-environments/_build. The second location we use `Central US`, but  we don't have any network issue with it too.

**Comment by tiernano** [comment]
i will try west us 2 if this fails again today and see if that makes any difference.

**Comment by tiernano** [comment]
just reran the build of 2019 in central US, and it failed, but for a different reason... seems the issue with that VSIX file is solved... thanks. going to close this off and open the different one...
