### ISSUE TITLE
MSBuild.Sdk.Extras no longer on latest agent pool

### ISSUE THREAD

**Issue by eekamouse** [actions/virtual-environments#3130]
**Description**  
MSBuild.Sdk.Extras is no longer on the latest agent pool as of last week's push of windows-latest

**Question, Bug, or Feature?**:  
Can we get this added back? It's breaking our build.

**Virtual environments affected**  
Windows Server 2019

**Image version**
windows-latest

**Comment by al-cheb** [comment]
Duplicate - https://github.com/actions/virtual-environments/issues/3038, Temporary workadound - https://github.com/actions/virtual-environments/issues/3038#issuecomment-814979307
