### ISSUE TITLE
GitHub build failed - GitHub Actions has encountered an internal error when running your job

### ISSUE THREAD

**Issue by priyanka-amzn** [actions/virtual-environments#3131]
**Description**  
I'm trying to setup a GitHub action for my repo. When this action is run, it fails with 
```
GitHub Actions has encountered an internal error when running your job.
```
Example: https://github.com/aws-cloudformation/aws-cloudformation-resource-providers-cloudformation/actions/runs/727685484
**Area for Triage**:  

Java
**Question, Bug, or Feature?**:  

Bug
**Virtual environments affected**  
- [x] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Image version**

Image version where you are experiencing the issue.

**Expected behavior**  
The github action should run

**Actual behavior**  
build is failing

**Repro steps**  
github actions config file is here: https://github.com/aws-cloudformation/aws-cloudformation-resource-providers-cloudformation/blob/e7d2e1fab7b66c929358f500f272a1e469d59114/.github/workflows/java-ci-with-maven.yml

**Comment by mlagoma** [comment]
+1, was working ~4pm PST
It changed to getting stuck on "Starting workflow run..." ~5:30pm PST

**Comment by priyanka-amzn** [comment]
+1 build triggered 1 hour ago is stuck in `Queued` state.

**Comment by al-cheb** [comment]
Hello, @priyanka-amzn , @mlagoma 
We're experiencing service degradation at the moment, sorry for the inconvenience -  https://www.githubstatus.com/

**Comment by priyanka-amzn** [comment]
builds are all green now

**Comment by Arjunsah454** [comment]
Hello Team,
I am also getting the page build and deployment error
