### ISSUE TITLE
chromium-browser executable renamed to chromium in Ubuntu environment

### ISSUE THREAD

**Issue by weavejester** [actions/virtual-environments#3133]
**Description**  
Some GH actions I had set up stopped working as they could no longer find the `chromium-browser` executable.

I believe this regression was caused by #3029, which links `/usr/bin/chromium` but not `/usr/bin/chromium-browser`. Note that in Ubuntu 20.04, the Chromium executable is called `chromium-browser`, not `chromium` (according to the [package file list](https://packages.ubuntu.com/focal/amd64/chromium-browser/filelist)).

**Area for Triage**:  
Packages

**Question, Bug, or Feature?**:  
Bug

**Virtual environments affected**  
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [X] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Image version**
20210405.1

**Expected behavior**  
For `chromium-browser` to be an executable on the `$PATH`

**Actual behavior**  
The Chromium executable has been moved to `/usr/bin/chromium`

**Repro steps**  
1. Have an action that runs `chromium-browser`.
2. This action will fail because it can no longer find the `chromium-browser` executable.

**Comment by nikita-bykov** [comment]
Hello @weavejester! We have fixed this issue. Images with changes will be available in a couple of days.

**Comment by weavejester** [comment]
Thanks! And I see you even left the `chromium` link intact for backward compatibility.
