### ISSUE TITLE
Update/Add Windows Server 2022 image

### ISSUE THREAD

**Issue by ykuijs** [actions/virtual-environments#3138]
**Tool information**
- Tool name: Windows Server 2022 VM image
- Tool license: Same as Windows Server 2019
- Add or update? Add
- Desired version: 2022
- Approximate size: Similar to Server 2019
- If this is an add request:
  - Brief description of tool: New OS version
  - URL for tool's homepage: https://cloudblogs.microsoft.com/windowsserver/2021/03/02/announcing-windows-server-2022-now-in-preview/
  - Provide a basic test case to validate the tool's functionality: 

**Area for Triage**:
Windows Server 2019 has a very specific performance issue when running PowerShell unit tests, that cause my unit tests to require twice the amount of time. The issue also exists in Windows 10 and I have been able to validate that improvements were implemented in the 2004 build of Windows 10 and Windows Server (bi-annual versions, not 2019).

I know Windows Server 2022 is still in Prreview, but I am hoping a VM image can be created because this issue is seriously impacting efficiency in our project. 

**Question, Bug, or Feature?**:
Question

**Virtual environments affected**
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019
- [x] Windows Server 2022

**Can this tool be installed during the build?**
No

**Tool installation time in runtime**
N/A

**Are you willing to submit a PR?**
N/A

**Comment by maxim-lobanov** [comment]
Hello @ykuijs , thank you for your proposal!
We definitely will add Windows Server 2022 when the stable version is released.

As for the adding new image while it is in preview, we would like to keep this issue opened for a while to track popularity of this request.
Usually, adding new images is not fast and simple process.

**Comment by EwoutH** [comment]
This might be interesting: [Announcing a New Windows Server Container Image Preview](https://techcommunity.microsoft.com/t5/containers/announcing-a-new-windows-server-container-image-preview/ba-p/2304897)

**Comment by miketimofeev** [comment]
@AtOMiCNebula yes, there is a chance. We've made similar changes during Ubuntu 20 onboarding.

**Comment by maxim-lobanov** [comment]
Hello everyone!

Windows Server 2022 image is available for Azure DevOps and GitHub users! 🚀 
Please find more details in https://github.com/actions/virtual-environments/issues/3949

#### GitHub Actions
```yaml
jobs:
  jobName:
    runs-on: windows-2022
```

#### Azure DevOps
```yaml
jobs:
- job: jobName
  pool:
    vmImage: windows-2022
```

**Comment by ykuijs** [comment]
Thanks @maxim-lobanov, I am indeed able to use Windows Server 2022 and my pipelines now complete over 50% quicker!!
