### ISSUE TITLE
sbt compile failure in ubuntu-18.04 after 20210405.1

### ISSUE THREAD

**Issue by sezruby** [actions/virtual-environments#3146]
**Description**  
Azure pipeline sbt build failure after 20210405.1 version.

https://github.com/microsoft/hyperspace

failed log: 
https://dev.azure.com/ossspark/public/_build/results?buildId=1859&view=logs&j=df231af6-32dd-547b-29be-d8756af88091&t=5d7595c6-3f6b-52ad-175f-d5d559db9724
succeeded log: https://dev.azure.com/ossspark/public/_build/results?buildId=1828&view=logs&j=057097eb-ba45-5660-ddec-1e9f78989293&t=f0957aa0-d85e-50b5-644d-67f036df1159

**Area for Triage**:  Scala

**Question, Bug, or Feature?**:  Bug

**Virtual environments affected**  
- [ ] Ubuntu 16.04
- [x] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Image version**

20210405.1

**Expected behavior**  
build succeeded

**Actual behavior**  
sbt version - 0.13.18
sbt compile failed with the following log: 
```
sbt.InvalidComponent: Could not find required component 'xsbti'
	at sbt.ComponentManager.invalid(ComponentManager.scala:57)
	at sbt.ComponentManager.sbt$ComponentManager$$notFound$1(ComponentManager.scala:34)
	at sbt.ComponentManager.sbt$ComponentManager$$createAndCache$1(ComponentManager.scala:37)
	at sbt.ComponentManager$$anonfun$sbt$ComponentManager$$fromGlobal$1$1.apply(ComponentManager.scala:27)
	at sbt.ComponentManager$$anonfun$sbt$ComponentManager$$fromGlobal$1$1.apply(ComponentManager.scala:26)
	at sbt.ComponentManager$$anon$1.call(ComponentManager.scala:50)
	at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:55)
	at xsbt.boot.Locks$.apply0(Locks.scala:47)
	at xsbt.boot.Locks$.apply(Locks.scala:36)
	at sbt.ComponentManager.lock(ComponentManager.scala:50)
	at sbt.ComponentManager.lockGlobalCache(ComponentManager.scala:49)
	at sbt.ComponentManager.sbt$ComponentManager$$fromGlobal$1(ComponentManager.scala:25)
	at sbt.ComponentManager$$anonfun$files$1$$anonfun$apply$2.apply(ComponentManager.scala:44)
```

**Repro steps**  
Push a new PR for test or rerun the pipeline

**Comment by Darleev** [comment]
Hello @sezruby,
According to the [latest Ubuntu changes](https://github.com/actions/virtual-environments/pull/3094), I see that `sbt `has been upgraded to version 1.5.0 which possibly contains some breaking changes. Could you please check this on your side locally or provide us required steps to reproduce the issue?
We are looking forward to your reply.

**Comment by sezruby** [comment]
I reproduced this on my local. 

0) git clone https://github.com/sezruby/hyperspace.git
0-1) git fetch origin master
0-2) git checkout origin/master
1)  wget https://github.com/sbt/sbt/releases/download/v1.5.0/sbt-1.5.0.tgz
2) tar -xzf sbt-1.5.0.tgz
3)  sudo apt-get install openjdk-8-jre
4)  path/to/sbt/bin/sbt clean
5)  path/to/sbt/bin/sbt update
5)  path/to/sbt/bin/sbt compile

**Comment by Darleev** [comment]
@sezruby if the issue can be reproduced locally, it means that the issue in the latest `sbt` update. There two possible ways to avoid the issue:
1) Downgrade `sbt` to compatible version;
2) Adapt your code to the latest `sbt`

We are looking forward to your reply.

**Comment by sezruby** [comment]
@Darleev It's not syntax or compile error, but missing component error. I wasn't able to resolve the problem from my side, so I created an issue on sbt/sbt repo. Is it possible to downgrade the version?

**Comment by Darleev** [comment]
@sezruby you can downgrade `sbt` version using the following steps:

```
          wget -O /tmp/sbt.tgz "https://github.com/sbt/sbt/releases/download/v1.4.9/sbt-1.4.9.tgz"
          sudo tar zxf /tmp/sbt.tgz -C /usr/share
          sudo rm -rf /usr/bin/sbt
          sudo ln -s /usr/share/sbt/bin/sbt /usr/bin/sbt
```

**Comment by sezruby** [comment]
Thanks for the tip! 😄  I made a workaround for our repo. https://github.com/microsoft/hyperspace/pull/416

I think it's sbt side issue & we could close this issue.

**Comment by Darleev** [comment]
If additional assistance or information is required, do not hesitate to contact us.
