### ISSUE TITLE
Update/Add MSBuild on macOS and Linux

### ISSUE THREAD

**Issue by mattleibow** [actions/virtual-environments#3148]
It seems the msbuild and VS on the non-Windows bots are a fair bit out of date, with MSBuild being 16.6 and the Windows version 16.9. This means that since I am using some of the new MSBuild features, my macOS builds are failing.

**Tool information**
- Tool name: msbuild
- Tool license: MS?
- Add or update? Update
- Desired version: 16.9+
- Approximate size: 
- If this is an add request:
  - Brief description of tool: 
  - URL for tool's homepage: 
  - Provide a basic test case to validate the tool's functionality: 

**Area for Triage**:

**Question, Bug, or Feature?**:
Feature

**Virtual environments affected**
- [x] Ubuntu 16.04
- [x] Ubuntu 18.04
- [x] Ubuntu 20.04
- [x] macOS 10.15
- [x] macOS 11.0
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Can this tool be installed during the build?**

**Tool installation time in runtime**

**Are you willing to submit a PR?**

**Comment by Darleev** [comment]
Hello @mattleibow,
Thank you for contacting us.
We will check the possibility to add the latest MSBuild to macOS and Ubuntu images. 
We'll keep you informed.

**Comment by miketimofeev** [comment]
@mattleibow msbuild comes along with Mono distribution and currently, the latest Mono contains msbuild 16.6. However, it looks like the 16.9 version was added recently and will be available in the nearest Mono releases:
https://github.com/mono/mono/pull/20979

**Comment by miketimofeev** [comment]
@mattleibow we have added the MSBuild version to the documentation so you can follow when the version is updated. The docs will be updated on the next image rollout.

**Comment by miketimofeev** [comment]
@mattleibow the new images with updated documentation have been deployed — please keep an eye on the updates in it.
I'm going to close the issue. Please feel free to contact us if you have any concerns.
Thank you!
