### ISSUE TITLE
cannot create directory ‘/run/user/0’: Permission denied - ubuntu-latest - Bash Shell

### ISSUE THREAD

**Issue by alvinseville7cf** [actions/virtual-environments#3149]
**Description**  
` mkdir: cannot create directory ‘/run/user/1001’: Permission denied` error happens after `drawio` snap execution in `publish` job `Convert Flowchart` step.

![image](https://user-images.githubusercontent.com/42812113/114409942-4d84c280-9bee-11eb-9ff7-58735e56020a.png)

**Area for Triage**:  

**Question, Bug, or Feature?**:  
Bug

**Virtual environments affected**  
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [x] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Image version**

Image version where you are experiencing the issue.

**Expected behavior**  
Normal `drawio` snap execution.

**Actual behavior**  
` mkdir: cannot create directory ‘/run/user/1001’: Permission denied` error.

**Repro steps**  
Push any `v*` tag to [repo](https://github.com/alvinseville7cf/CSharp---Exercise---Other---Laboratory-Work-4) or run [cd.yml](https://github.com/alvinseville7cf/CSharp---Exercise---Other---Laboratory-Work-4/blob/master/.github/workflows/cd.yml) manually.

[Here](https://github.com/alvinseville7cf/CSharp---Exercise---Other---Laboratory-Work-4/runs/2324634162?check_suite_focus=true#step:4:16) are my logs.

**How to avoid this issue**
Use wget for example to download and install .deb package:
```yml
        sudo apt update
        
        sudo apt-get install -y libappindicator3-1
        
        sudo apt -y install wget
        wget https://github.com/jgraph/drawio-desktop/releases/download/v12.3.2/draw.io-amd64-12.3.2.deb
        sudo dpkg -i draw.io-amd64-12.3.2.deb
        sudo apt -y -f install
```
But it is a workaround and not the best decision. :)

**Comment by Darleev** [comment]
Hello @alvinseville7cf,

I tried to reproduce the issue using the following workflow:

```
on: [push]
jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: Plain job
        run: |
          sudo apt update
          sudo apt install snapd
          sudo snap install drawio
        shell: bash
```

but everything works fine. Could you please provide step-by-step instructions on how to reproduce the issue or sample repo?
We are looking forward to your reply.

**Comment by alvinseville7cf** [comment]
@Darleev, I've update my first message.

**Comment by miketimofeev** [comment]
@alvinseville7cf unfortunately it's a known issue with snap packages, a few similar issues:
https://github.com/actions/virtual-environments/issues/1378
https://github.com/actions/virtual-environments/issues/1475
https://github.com/actions/virtual-environments/issues/2967

We have not found the solution yet, so it's better to use the .deb packages as you mentioned as a workaround.

**Comment by Darleev** [comment]
@alvinseville7cf I'm going to close the issue.
In case of any questions, feel free to contact us.
