### ISSUE TITLE
Windows runner failing to download file from external server

### ISSUE THREAD

**Issue by kroggen** [actions/virtual-environments#3150]
**Description**
Windows runner is not downloading a file from external server.

**Area for Triage**:  
Area: Scripting and command line

**Question, Bug, or Feature?**:  
"Bug"

**Virtual environments affected**  
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [x] Windows Server 2019

**Image version**
Version: 20210404.2

**Expected behavior**
It should download the file

**Actual behavior**
It returns `Unable to connect to the remote server`:

```
Run Invoke-WebRequest http://litesync.io/download/litesync-free-windows-x86_64.tar.gz -OutFile litesync-free-windows-x86_64.tar.gz
  Invoke-WebRequest http://litesync.io/download/litesync-free-windows-x86_64.tar.gz -OutFile litesync-free-windows-x86_64.tar.gz
  shell: C:\Windows\System32\WindowsPowerShell\v1.0\powershell.EXE -command ". '{0}'"
Invoke-WebRequest : Unable to connect to the remote server
At D:\a\_temp\9ac62775-3eea-4c93-921f-ff9fc83d04a9.ps1:2 char:1
+ Invoke-WebRequest http://litesync.io/download/litesync-free-windows-x ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebExc 
   eption
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand
 
Error: Process completed with exit code 1.
```

**Repro steps**  

```yaml
- run: Invoke-WebRequest http://litesync.io/download/litesync-free-windows-x86_64.tar.gz -OutFile litesync-free-windows-x86_64.tar.gz
```

As can be seen on [build.yml](https://github.com/kroggen/better-sqlite3/blob/master/.github/workflows/build.yml#L41)

Here is the [job output](https://github.com/kroggen/better-sqlite3/runs/2320719615?check_suite_focus=true)

**Comment by Darleev** [comment]
Hello @kroggen.
Thank you for contacting us.
We will investigate the issue.

**Comment by Darleev** [comment]
Hello @kroggen,
I've tried to reproduce the issue outside of Azure cloud, but with no luck. Also, I tried to compare results from different regions, and it seems it's not our case here. It's definitely a network issue, but need more time to investigate it deeper.
I'll keep you updated.

**Comment by Darleev** [comment]
Hello @kroggen,
In order to workaround the issue, it is possible to use the following context on windows-2019,windows-2016 machines:

```
      - name: wget
        run: curl -x 188.166.209.200:8080 http://litesync.io/download/litesync-free-windows-x86_64.tar.gz --output litesync-free-windows-x86_64.tar.gz
        shell: bash
```
In other words, use proxy to avoid direct traffic through the Azure firewall. Full downloading procedure takes about 5 seconds to complete.

Could you please check the solution on your side and let us know?

**Comment by kroggen** [comment]
Hello @Darleev 

It failed the first time but then it worked when I asked to re-run the job.

Thank you for your help!
