### ISSUE TITLE
Ubuntu 18.04: Missing python-setuptools

### ISSUE THREAD

**Issue by aparcar** [actions/virtual-environments#3158]
**Description**  
The list of installed packages for Ubuntu 18.04 [states](https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu1804-README.md) the Python package `setuptools` is installed, however it's missing in the actual images.

[Here](https://github.com/ynezz/openwrt-ucentral-schema/runs/2304056468?check_suite_focus=true#step:7:33) is an actually failing CI job.

**Area for Triage**:  
Python

**Question, Bug, or Feature?**:  
**Bug**

**Virtual environments affected**  
- [ ] Ubuntu 16.04
- [x] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Image version**
  Version: 20210405.1

**Expected behavior**  
Have setuptools available

**Actual behavior**  
Setuptools is not available

**Repro steps**  
Try to install [python-json2yaml](https://pypi.org/project/python-json2yaml/) on a Ubuntu machine via Pip.

**Comment by miketimofeev** [comment]
Hi @aparcar!
The `python-setuptools` package contains setuptools for python2. There is a separate package with `setuptools` for python3 — `python3-setuptools`.
Could you please try to install it using `sudo apt-get install python3-setuptools`? Does it help?

**Comment by aparcar** [comment]
That does help, thanks.
