### ISSUE TITLE
Add last Node LTS version image to the cache

### ISSUE THREAD

**Issue by armandabric** [actions/virtual-environments#3159]
Given https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-README.md#cached-docker-images the Node v14 image is not cached yet. As [Node v14 is the active LTS](https://nodejs.org/en/about/releases/) it could justify to have it cached to speed up a lot of GitHub action run.

**Tool information**
- Tool name: Node
- Add or update? Update
- Desired version: 14
- Approximate size: 

**Area for Triage**:

JavaScript and Node.js

**Question, Bug, or Feature?**:
Feature

**Virtual environments affected**
- [x] alpine
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [x] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Are you willing to submit a PR?**

Yes if you point me out where is the script to generated docker cached images.

**Comment by Darleev** [comment]
Hello @armandabric @shouze,
Thank you for contacting us.
As soon as we make a decision regarding your request, we'll let you know.

**Comment by AlenaSviridenko** [comment]
Hi @armandabric,
thanks for the suggestion, I added this issue to our backlog, we will let you know once changes are merged and available.

**Comment by miketimofeev** [comment]
@armandabric we've added node14 & node14-alpine to all Ubuntu images. The new image rollout will start on Monday and take 3-4 days.

**Comment by armandabric** [comment]
That's a freat news! This will avoid a lot of computation on a lot of GitHub action run :horse_racing: :dash:

**Comment by miketimofeev** [comment]
@armandabric the images have been deployed!
I'm going to close the issue. Please feel free to contact us if you have any concerns.
Thank you!
