### ISSUE TITLE
Update terraform to 0.14.10

### ISSUE THREAD

**Issue by shouze** [actions/virtual-environments#3160]
**Tool information**
- Tool name:  terraform
- Add or update?  update
- Desired version:  0.14.10
- Approximate size: 
- If this is an add request:
  - Brief description of tool: 
  - URL for tool's homepage: 
  - Provide a basic test case to validate the tool's functionality: 

**Area for Triage**:

**Question, Bug, or Feature?**:

**Virtual environments affected**
- [x] Ubuntu 16.04
- [x] Ubuntu 18.04
- [x] Ubuntu 20.04
- [x] macOS 10.15
- [x] macOS 11.0
- [x] Windows Server 2016 R2
- [x] Windows Server 2019

**Are you willing to submit a PR?**

yes, I've found the [install script](https://github.com/actions/virtual-environments/blob/b7f276c003aea42575b52247bdb2183e355fca2f/images/linux/scripts/installers/terraform.sh) but I don't know where I have to bump the TERRAFORM_VERSION variable.

**Comment by Darleev** [comment]
Hello @shouze,
Terraform will be upgraded to version 0.14.10 after the next image rollout. It should be completed by the end of this week.
We'll keep you updated.

**Comment by al-cheb** [comment]
The new images with `terraform 0.14.10` have been deployed.
