### ISSUE TITLE
Crash when building a Python wheel on Windows since version 20210330

### ISSUE THREAD

**Issue by liZe** [actions/virtual-environments#3161]
**Description**  
Building a Python wheel for my package on Windows crashes since version 20210330. It used to work with version 20210316 and still works on Linux and macOS with recent versions.

**Area for Triage**:  
?

**Question, Bug, or Feature?**:  
Bug

**Virtual environments affected**  
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [X] Windows Server 2019

**Image version**
Fails since 20210330, not fixed by more recent versions.

**Expected behavior**  
The build used to pass with 20210316: https://github.com/Kozea/WeasyPrint/runs/2263895060?check_suite_focus=true

**Actual behavior**  
It now fails with error 3221225477: https://github.com/Kozea/WeasyPrint/runs/2269219782?check_suite_focus=true

As far as I can tell, nothing related to the wheel build changed between these two runs. The only difference I can spot is the new virtual-environments version. The version of Python and the version of Python packages are the same.

Relaunching runs that were passing now fail. It means that the problem is not caused by a change in our repository code.

I didn’t find anything interesting online about error 3221225477 😒, even if some other users seem to have the same problem for random packages on various platforms.

As the error is not in some Python code, but probably a crash of the Python interpreter itself, I don’t know how to debug it. I’ve tried to set verbose flags, but it didn’t help. Nothing in virtual-environments’ changelog seems to be related.

**Repro steps**  
Relaunching the run always fail, with the same error code.

**Comment by Darleev** [comment]
Hello @liZe,
Thank you for contacting us.
We will investigate the issue on our side.

**Comment by dsame** [comment]
@liZe 
I noticed the Pango version changed from mingw-w64-x86_64-pango-1.48.3 to mingw-w64-x86_64-pango-1.48.4 between the succeeded and and failed builds.

If i remove pango from `pacman -S mingw-w64-x86_64-ttf-dejavu mingw-w64-x86_64-pango mingw-w64-x86_64-ghostscript --noconfirm` the build fails with the library not found (it is expected), but at least is passes the point where the bug appears. 

Can you please open the discussion with the pango support ?

**Comment by liZe** [comment]
Hello @dsame,

Thanks a lot for your very quick answer.

I’ve tried to rebuild without installing Pango, and as you said it fails because the library not found. But it actually fails during the same step, it doesn’t pass the point where the bug appears.

I’ve tried to [install Pango 1.48.3](https://github.com/Kozea/WeasyPrint/runs/2337246822?check_suite_focus=true), and it fails too. Unfortunately, Pango doesn’t seem to be involved 😞.

**Comment by liZe** [comment]
This build passed, I don’t know why…

https://github.com/Kozea/WeasyPrint/runs/2360920871?check_suite_focus=true

**Comment by dsame** [comment]
@liZe i guess there's some deps involved in the issue. do you have another success/fail builds?

**Comment by liZe** [comment]
> @liZe i guess there's some deps involved in the issue. do you have another success/fail builds?

WeasyPrint is unfortunately the only repository where we have the problem (we don’t have many repositories with Windows tests though).

By "deps", do you mean Python deps or MinGW deps? We can try to remove some of the deps and see if the build crashes. Would it help?

**Comment by dsame** [comment]
@liZe Yes, correct. By "deps" i meant 3rd party python and mingw artefacts we can not control. The pipelines team confirmed all the github windows environments are the very same.  

But currently the question is do we still have the problem? 

```
This build passed, I don’t know why…

https://github.com/Kozea/WeasyPrint/runs/2360920871?check_suite_focus=true
```

I guess a 3rd party deps has updated and this why the build passed

**Comment by liZe** [comment]
> @liZe Yes, correct. By "deps" i meant 3rd party python and mingw artefacts we can not control. The pipelines team confirmed all the github windows environments are the very same.

OK, I’ll try to find which dependency is causing the problem.

> But currently the question is do we still have the problem?

Yes, we do. The build that passed just passed once, only for Python 3.6 (3.7-3.9 failed). The other builds launched before and after this build failed, with no obvious change. It just means that the crash happens very very frequently, but not always.

**Comment by liZe** [comment]
> Yes, we do. The build that passed just passed once, only for Python 3.6 (3.7-3.9 failed). The other builds launched before and after this build failed, with no obvious change. It just means that the crash happens very very frequently, but not always.

Well… Actually, tests pass right now. I really don’t know what happened, there’s no visible difference in the dependencies.

…

I’m closing this ticket, I’ll reopen it if anything strange happens again. Thanks for your support.
