### ISSUE TITLE
macOS-10.15 agent uses Homebrew 3.0.10 which uses Bintray

### ISSUE THREAD

**Issue by thisisthekap** [actions/virtual-environments#3165]
**Description**  

According to https://github.com/Homebrew/discussions/discussions/691, Homebrew switched from Bintray to GitHub Packages. Homebrew 3.1.0 uses the new CDN. The Microsoft Hosted Agents should imho be updated accordingly to avoid issues when downloading/installing packages using Homebrew.

**Area for Triage**: 
Artifacts, Packages, Servers

**Question, Bug, or Feature?**:  
Bug

**Virtual environments affected**  
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [x] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Comment by maxim-lobanov** [comment]
Hello @thisisthekap , I think nothing is required from our side to switch CDN.
As I can see, 5 hours ago the new version of brew with support of new CDN was released: https://github.com/Homebrew/brew/releases/tag/3.1.0

We will update Homebrew to this version with new image rollout (approx middle of next week since this week rollout has been already started).

**Comment by thisisthekap** [comment]
@maxim-lobanov Thank you for the quick response!

Updating Homebrew to 3.1.0 is indeed the solution I was hoping for :)

Once again: Thank you very much 😎

**Comment by jsonfry** [comment]
Right now bintray have started what they're calling a 'brown out' https://status.bintray.com/incidents/4mzph0y8l6hk
 but actually means they're failing all requests to bintray for the next few hours, so any `brew` installs in macos runners are failing / will fail.

Did you have to update brew as part of your ci job?

**Comment by thisisthekap** [comment]
I just execute `brew update` prior to the needed `brew install` call to make sure Homebrew is on the lastest version.

**Comment by jsonfry** [comment]
Hmm not ideal. 

@maxim-lobanov  I guess there's no chance of brew being updated before bintray finished their thing in about 6 hours?

**Comment by jonathanhood** [comment]
Some kind of guidance, or a notification of some kind on the actions status page, may be necessary. It took me, at least, a good portion of the morning chasing down links to find myself here. Such a notification, email, or whatever could save a lot of people a lot of time this morning - especially since the brownout doesn't end until 2pm pacific.

**Comment by ColinPitrat** [comment]
I'm seeing some "403 forbidden" when executing `brew install` today from GitHub Actions. Is this linked to this issue?

**Comment by jonathanhood** [comment]
Yes. To recap the issue:

1. Bintray is issuing `403 Forbidden` errors today as part of a scheduled "brownout" in preparation for their take down of the service.
2. A version of brew is available that uses github packages instead. This version is not installed by default on the mac actions runners.

While we wait for the runners to be updated, you can do `brew update` manually in your github actions workflow and sidestep the issue.

**Comment by mathbagu** [comment]
When can we expect the runners to be updated, just to know if we should use the suggested workaround?

**Comment by miketimofeev** [comment]
@mathbagu we've decided to start the new rollout tomorrow to deliver the fix asap

**Comment by maxim-lobanov** [comment]
Issue is related to planned brown-out session on Bintray side.
Bintray is going to recover in a few hours so issue should disappear: https://status.bintray.com/incidents/4mzph0y8l6hk

With next image rollout, homebrew should stop using bintray. Updating runners take about 3-4 days usually.

**Comment by maxim-lobanov** [comment]
The deployment of new set of images has been already started and will be finished in a few days.

**Comment by miketimofeev** [comment]
@thisisthekap We have deployed macOS images with brew 3.1.1 on board! All the packages are now retrieved from GitHub Packages.
I'm going to close the issue. Please feel free to contact us if you have any concerns.
Thank you!
