### ISSUE TITLE
Improve SQLite3 support on Python versions - All platforms

### ISSUE THREAD

**Issue by pedrocamargo** [actions/virtual-environments#317]
**Tool information**
- Tool name: SQLite3/Python
- Add or update? Update
- Desired version: Same as current, but with improved SQLite capabilities
- Approximate size: 

**Area for Triage**: Python

**Question, Bug, or Feature?**:
Feature

**Virtual environments affected**
- [X] macOS 10.15
- [X] Ubuntu 16.04 LTS
- [X] Ubuntu 18.04 LTS
- [X] Windows Server 2016 R2
- [X] Windows Server 2019

**Can this tool be installed during the build?**
Maybe it could, but it would change completely how a Python workflow would look like

**Are you willing to submit a PR?**
I looked at the source code and I am not sure I have the chops

Currently, when attempting to enable extension loading, we get an error that such a feature is not available.  Below

   conn.enable_load_extension(True)
   AttributeError: 'sqlite3.Connection' object has no attribute 'enable_load_extension'

**Comment by miketimofeev** [comment]
Hi @pedrocamargo. Are you sure windows python has that issue as well?

**Comment by pedrocamargo** [comment]
@miketimofeev my last test on Windows says that it is all good on Windows now.

**Comment by simonw** [comment]
Here's a workaround: if you `pip install pysqlite3-binary` you can do `import pysqlite3 as sqlite3` and get a much more recent version of SQLite that allows you to load extensions.

**Comment by pedrocamargo** [comment]
Thanks, @simonw . I found that implementing the workaround would mean patching the software in a few places and the result would be particularly ugly and not really justifiable, so I will wait for this to be implemented. Thanks again!

**Comment by pedrocamargo** [comment]
Can we increase the size of the issue request and add the shipping of RTree with the SQLite binary?

It would solve the remaining problems of testing with Spatialite

![image](https://user-images.githubusercontent.com/7377666/82790170-fcbd8b80-9eae-11ea-8c53-66d8ed073dfe.png)

**Comment by vmapetr** [comment]
Hi @pedrocamargo !
Our current Python versions were rebuilded with support of sqlite load extensions, they should be available during the next image rollout, it's 1-2 weeks approximately. Unfortunately, UsePython task cannot download latest Python release for version that already installed on image in runtime, but if build version of Python is not viral to your project, you can temporary set UsePython version to X.Y.Z-1, to avoid waiting for rollout.     
Please consider, that for [nix systems `enable_load_extensions` flag is available for Python3 only](https://docs.python.org/3/library/sqlite3.html#sqlite3.Connection.enable_load_extension), so if you use Python2 you may still need workaround with installation of `pysqlite3`.

Regarding, RTree support in sqlite, could you please create separate issue?

**Comment by pedrocamargo** [comment]
That is absolutely awesome!! Thanks!!!!

**Comment by miketimofeev** [comment]
All the images have been deployed!
@pedrocamargo I'm going to close the issue, feel free to contact us if you have any concerns.
Thank you!
