### ISSUE TITLE
GithubFeedToken parameter is not specified

### ISSUE THREAD

**Issue by howardjones** [actions/virtual-environments#3182]
**Description**  

Following the documentation to build an ADO Ubuntu 20 agent image, and the docs don't align with the script. 
https://github.com/actions/virtual-environments/blob/main/docs/create-image-and-azure-resources.md

**Area for Triage**:  

**Question, Bug, or Feature?**:  
Bug

**Virtual environments affected**  
- [*] Ubuntu 16.04
- [*] Ubuntu 18.04
- [*] Ubuntu 20.04
- [*] macOS 10.15
- [*] macOS 11.0
- [*] Windows Server 2016 R2
- [*] Windows Server 2019

**Image version**
Didn't get that far, but cloned from 'main' today.

**Expected behavior**  
Azure resource created.

**Actual behavior**  

    GenerateResourcesAndImage: Missing an argument for parameter 'GithubFeedToken'. Specify a parameter of type 'System.String' and try again.

**Repro steps**  
A description with steps to reproduce the issue. If your have a public example or repo to share,
please provide the link.

1. On Ubuntu 20.04 LTS host, Powershell 7.1.3 just installed and Az module.
2. Import GenerateResourcesAndImage.ps1 from helpers directory
3. GenerateResourcesAndImage -SubscriptionId {YourSubscriptionId} -ResourceGroupName "myTestResourceGroup" -ImageGenerationRepositoryRoot "$pwd" -ImageType Ubuntu1604 -AzureLocation "East US"

What is a GithubFeedToken? What is a GitHub Package Registry?

**Comment by Darleev** [comment]
Hello @howardjones,
As far as I see in the provided documentation:
`- github_feed_token - Github PAT. Required for NPM toolcache installation. Will be depricated soon.`
So, need to provide an additional parameter `GithubFeedToken`.
Here the link to the documentation: [How to generate GitHub PAT](https://docs.github.com/en/github/authenticating-to-github/creating-a-personal-access-token)
We are looking forward to your reply.

**Comment by howardjones** [comment]
Then you should remove the check from GenerateResourcesAndImage.ps1 that aborts the run if it isn't supplied. I noticed that the parameter was actually not mandatory, but there is a check immediately after the parameters that exits if it isn't set. I commented that out and the build seems to be going (but very slowly - at least an hour so far).

The page I linked to above, which is the one the README points you to if you want to build images, doesn't mention `--GithubFeedToken` command-line parameter at all. I see the other spelling you mention for the variables file.

**Comment by Darleev** [comment]
@howardjones thank you for pointing to this. 
We'll definitely check this and update you as soon as new information appears.

**Comment by howardjones** [comment]
Just saw your PR, but this is the section I meant:

```
--- a/helpers/GenerateResourcesAndImage.ps1
+++ b/helpers/GenerateResourcesAndImage.ps1
@@ -120,11 +120,11 @@ Function GenerateResourcesAndImage {
         [Switch] $Force
     )
 
-    if ([string]::IsNullOrEmpty($GithubFeedToken))
-    {
-        Write-Error "'-GithubFeedToken' parameter is not specified. You have to specify valid GitHub PAT to download tool packages from GitHub Package Registry"
-        exit 1
-    }
+    #if ([string]::IsNullOrEmpty($GithubFeedToken))
+    #{
+    #    Write-Error "'-GithubFeedToken' parameter is not specified. You have to specify valid GitHub PAT to download tool packages from GitHub Package Registry"
+    #    exit 1
+    #}
 
     $builderScriptPath = Get-PackerTemplatePath -RepositoryRoot $ImageGenerationRepositoryRoot -ImageType $ImageType
     $ServicePrincipalClientSecret = $env:UserName + [System.GUID]::NewGuid().ToString().ToUpper();
```

**Comment by Darleev** [comment]
> Just saw your PR, but this is the section I meant:
> 
> ```
> --- a/helpers/GenerateResourcesAndImage.ps1
> +++ b/helpers/GenerateResourcesAndImage.ps1
> @@ -120,11 +120,11 @@ Function GenerateResourcesAndImage {
>          [Switch] $Force
>      )
>  
> -    if ([string]::IsNullOrEmpty($GithubFeedToken))
> -    {
> -        Write-Error "'-GithubFeedToken' parameter is not specified. You have to specify valid GitHub PAT to download tool packages from GitHub Package Registry"
> -        exit 1
> -    }
> +    #if ([string]::IsNullOrEmpty($GithubFeedToken))
> +    #{
> +    #    Write-Error "'-GithubFeedToken' parameter is not specified. You have to specify valid GitHub PAT to download tool packages from GitHub Package Registry"
> +    #    exit 1
> +    #}
>  
>      $builderScriptPath = Get-PackerTemplatePath -RepositoryRoot $ImageGenerationRepositoryRoot -ImageType $ImageType
>      $ServicePrincipalClientSecret = $env:UserName + [System.GUID]::NewGuid().ToString().ToUpper();
> ```

Thank you, I've added GithubFeedToken removal as well

**Comment by Darleev** [comment]
@howardjones We've merged the PR with the required changes. Could you please pull the latest main and try to build again?
Thanks for helping us improve the image generation process.
I'm going to close the issue, in case of any questions feel free to contact us.
