### ISSUE TITLE
Environment variable BOOST_ROOT will be deprecated in 2 month. 

### ISSUE THREAD

**Issue by AlenaSviridenko** [actions/virtual-environments#319]
Hi!

Due to a lot of customers complaints to predefined environment variable `$BOOST_ROOT` - we decided to deprecate this variable in 2 month.

Please, swith to `$BOOST_ROOT_<VERSION>` variable to point to certain version. Currently available `$BOOST_ROOT_1_69_0` only. 

If you have any concerns or questions please let us know through this issue.

Thanks!

**Comment by e-kwsm** [comment]
On ubuntu-latest `/usr/local/share/boost/1.72.0` exists but `BOOST_ROOT_1_72_0` is currently unavailable.

**Comment by henryiii** [comment]
Are the "BOOST_ROOT_1_69_0" and "BOOST_ROOT_1_72_0" variables documented somewhere? I was only able to find them to get CMake to fine Boost after finding this issue.

**Comment by al-cheb** [comment]
@henryiii ,
Windows Server 2016 - https://github.com/actions/virtual-environments/blob/releases/win16/20200811/images/win/Windows2016-Readme.md#boost
Windows Server 2019 - https://github.com/actions/virtual-environments/blob/releases/win19/20200802/images/win/Windows2019-Readme.md#boost

**Comment by henryiii** [comment]
@al-cheb: Ahh, maybe it's because I looked here:
https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu1804-README.md

**Comment by al-cheb** [comment]
@henryiii, 
I see. We are planning to fully rework Ubuntu documentation  to be consistence with Windows and we will include boost env variables .
