### ISSUE TITLE
Update/Add Azure CLI

### ISSUE THREAD

**Issue by RickXMoore** [actions/virtual-environments#3194]
**Tool information**
- Tool name: Azure CLI
- Tool license: MS
- Add or update? update
- Desired version: 2.21.0
- Approximate size: 
- If this is an add request:
  - Brief description of tool: 
  - URL for tool's homepage: 
  - Provide a basic test case to validate the tool's functionality: 

**Area for Triage**:
See https://docs.microsoft.com/azure/devops/pipelines/tasks/deploy/azure-cli

**Question, Bug, or Feature?**:
Feature

**Virtual environments affected**
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [X] Windows Server 2019

**Can this tool be installed during the build?**

**Tool installation time in runtime**

**Are you willing to submit a PR?**

**Comment by Darleev** [comment]
Hello @RickXMoore,
According to the latest [Windows 2019 documentation](https://github.com/actions/virtual-environments/blob/main/images/win/Windows2019-Readme.md#cli-tools), Azure CLI 2.21.0 should be installed on agent machines.
I'll additionally check it and let you know

**Comment by Darleev** [comment]
@RickXMoore actual version of Azure CLI is `2.21.0` as requested. Version 2.22.0 will be available on next week after the image rollout. 
I'm going to close the issue.
In case of any questions, do not hesitate to contact us.

**Comment by RickXMoore** [comment]
Much appreciated.
