### ISSUE TITLE
sha256sum -c in Windows fails without .gitattributes

### ISSUE THREAD

**Issue by emlun** [actions/virtual-environments#32]
**Description**
In a `runs-on: windows-latest` job running a `shell: bash` step, the `sha256sum -c` command fails because of an unexpected CR byte in the file name:

```
sha256sum: 'libusb-1.0.22.7z'$'\r': No such file or directory
```

Setting `text eol=lf` for the checksum file in `.gitattributes` fixes the issue.

Maybe this isn't really a bug (it would arguably be a bug in `sha256sum` if anything), but at least it is surprising behaviour.

**Virtual environments affected**
- [ ] macOS 10.14
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2 (probably this one too, haven't tested)
- [x] Windows Server 2019

**Expected behavior**
The `sha256sum` command, when run in a `bash` shell, behaves as it would in Linux/MacOS, and successfully verifies the checksum of the file.

**Actual behavior**
The checksum file is by default checked out with CRLF line endings, and `sha256sum` fails to find the file to be checked because of the trailing CR in the file name.

For reproduction, see [this build](https://github.com/Yubico/yubikey-manager/commit/2666e19113bc2beb1205df54a187e5e33d3a58f0/checks?check_suite_id=261342821) and the [github-actions-windows-sha256sum-bug-report](https://github.com/Yubico/yubikey-manager/tree/github-actions-windows-sha256sum-bug-report) branch in [YubiKey Manager](https://github.com/Yubico/yubikey-manager)

**Comment by ethomson** [comment]
Wow, this is fascinating.  Unfortunately, I think that there's little that we can do here: as you point out, this really is a deficiency (or, potentially, a feature) with `sha256sum` itself.

Regarding the line endings - in the absence of a `.gitattributes` file, there's no well-defined behavior for Git to deal with line endings.  This is controlled by the `core.autocrlf` configuration setting, which is configured on a per-user basis.  The Git for Windows installer defaults to setting `core.autocrlf=true` globally, and is therefore the best default we can use to model our behavior and so we also set `core.autocrlf=true` globally on our Windows build environments.

This is the best we can do with limited information.  But `core.autocrlf` is the old way of dealing with line endings and should not be relied upon.

We would always encourage you to check in the desired line ending behavior into your repository with `.gitattributes` (for all text files, not just the ones that are being treated poorly in this instance).

I realize that this is not an ideal situation, but I think that our build environment is setup as best as the circumstances around these settings will allow us.

**Comment by emlun** [comment]
Yeah, that's about what I expected. :slightly_smiling_face: But hopefully this thread can help future folks hitting the same snag find the workaround. Thanks for your attention!
