### ISSUE TITLE
Update Visual Studio Enterprise 2019

### ISSUE THREAD

**Issue by elieassi** [actions/virtual-environments#3200]
**Tool information**
- Tool name: Visual Studio Enterprise 2019
- Tool license: MS
- Add or update? update
- Desired version: latest
- Approximate size: 
- If this is an add request:
  - Brief description of tool: 
  - URL for tool's homepage: 
  - Provide a basic test case to validate the tool's functionality: 

**Area for Triage**:

**Question, Bug, or Feature?**:
Feature

**Virtual environments affected**
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [ x] Windows Server 2019

**Can this tool be installed during the build?**

**Tool installation time in runtime**

**Are you willing to submit a PR?**

Would it be possible to update to the latest version?  the current image is lacking the Microsoft.NETCore.App 3.1.14 , updating to the latest release of Visual Studio Enterprise solves this issue or, or at least include version 3.1.14 ?

Thank you

**Comment by Darleev** [comment]
Hello @elieassi,
Microsoft.NETCore.App 3.1.14 will be available after the next image rollout.
The new image rollout will start on Monday and take 3-4 days.

**Comment by elieassi** [comment]
Good morning @Darleev ,  awesome new.. thank you guys!

**Comment by miketimofeev** [comment]
@elieassi the deployment finished.
I'm going to close the issue. Please feel free to contact us if you have any concerns.
Thank you!
