### ISSUE TITLE
macOS-10.15 image is broken, generated unexecable files.

### ISSUE THREAD

**Issue by Halo-Michael** [actions/virtual-environments#3201]
**Description**  
A clear and concise description of what the bug is, and why you consider it to be a bug.
macOS-10.15 image is broken, generated unexecable files.
Here is the repo which used the broken image and generated broken file:
https://github.com/Halo-Michael/suer

And here is the broken build:
https://github.com/Halo-Michael/suer/runs/2363905101

**Area for Triage**:  Apple

**Question, Bug, or Feature?**:  Bug

**Virtual environments affected**  
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [√ ] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Image version**

Image version where you are experiencing the issue.
20210412.2

**Expected behavior**  
A description of what you expected to happen.
Binaries header should be like this:
![image](https://user-images.githubusercontent.com/45062120/115057731-014fc000-9f17-11eb-84f9-39270253a1d9.png)
This binary was build from my own computer.

**Actual behavior**  
A description of what is actually happening.
This is the damaged binary file header:
![Q)HGLTWMAUEG49C${2B@ Z0](https://user-images.githubusercontent.com/45062120/115057657-e67d4b80-9f16-11eb-82d4-fe72774f226c.png)

Attach a copy of both:
[archive_files.zip](https://github.com/actions/virtual-environments/files/6326773/archive_files.zip)

**Repro steps**  
A description with steps to reproduce the issue. If your have a public example or repo to share,
please provide the link.

1. Step 1
Build it.

**Comment by Halo-Michael** [comment]
So uha... any help?

**Comment by dibir-magomedsaygitov** [comment]
@Halo-Michael Thank you for your report. We will investigate this issue and let you know as soon as we have some results to share.

**Comment by dsame** [comment]
@Halo-Michael 

Is there are any evidences the executable binary must have 0xc8 byte in 0x16 offset?

I confirm the binary built with the current build does not have it 

```
0000000 ca fe ba be 00 00 00 03 00 00 00 0c 00 00 00 09
0000010 00 00 40 00 00 00 00 00 00 00 00 0e 01 00 00 0c
```
```
                                      00 00 c8 10
```

but `file suer` still shows correct file format

```
suer: Mach-O universal binary with 3 architectures: [arm_v7:Mach-O executable arm_v7] [arm64:Mach-O 64-bit executable arm64] [arm64e:Mach-O 64-bit executable arm64e]
suer (for architecture armv7):	Mach-O executable arm_v7
suer (for architecture arm64):	Mach-O 64-bit executable arm64
suer (for architecture arm64e):	Mach-O 64-bit executable arm64e
```

Are you sure the crash is caused by the invalid binary? Is there any clear evidences of this?

**Comment by Halo-Michael** [comment]
> @Halo-Michael
> 
> Is there are any evidences the executable binary must have 0xc8 byte in 0x16 offset?
> 
> I confirm the binary built with the current build does not have it
> 
> ```
> 0000000 ca fe ba be 00 00 00 03 00 00 00 0c 00 00 00 09
> 0000010 00 00 40 00 00 00 00 00 00 00 00 0e 01 00 00 0c
> ```
> 
> ```
> 0000010 00 00 40 00 00 00 c8 10                                   
> ```
> 
> but `file suer` still shows correct file format
> 
> ```
> suer: Mach-O universal binary with 3 architectures: [arm_v7:Mach-O executable arm_v7] [arm64:Mach-O 64-bit executable arm64] [arm64e:Mach-O 64-bit executable arm64e]
> suer (for architecture armv7):	Mach-O executable arm_v7
> suer (for architecture arm64):	Mach-O 64-bit executable arm64
> suer (for architecture arm64e):	Mach-O 64-bit executable arm64e
> ```
> 
> Are you sure the crash is caused by the invalid binary? Is there any clear evidences of this?

Try to use lipo to cut slices, will generate empty file.

**Comment by Halo-Michael** [comment]
I think the relevant bytes indicate how the system gets the correct slice, but in fact I don’t know much about these. All in all, if you manually replace the damaged binary with the correct header and re-sign it, it will work normally.

**Comment by dsame** [comment]
@Halo-Michael 

Have your ever have succeeded build with the same pipeline?
What is the device you run the binary on? Are you sure it has the arm architecture?

**Comment by Halo-Michael** [comment]
> @Halo-Michael
> 
> Have your ever have succeeded build with the same pipeline?
> What is the device you run the binary on? Are you sure it has the arm architecture?

The last time I used github action and works is https://github.com/Halo-Michael/Generator-Auto-Setter/runs/2260079781
The devices that can run binary on is iPhone/iPad (iOS).

**Comment by Halo-Michael** [comment]
And in fact there have no any exact message because it can't even running.
![DP @)1A8W9NH Q3H{$C7T1R](https://user-images.githubusercontent.com/45062120/115430476-fce91700-a236-11eb-9d7f-f7736a93335c.png)

**Comment by dsame** [comment]
> > @Halo-Michael
> > Have your ever have succeeded build with the same pipeline?
> > What is the device you run the binary on? Are you sure it has the arm architecture?
> 
> The last time I used github action and works is https://github.com/Halo-Michael/Generator-Auto-Setter/runs/2260079781
> The devices that can run binary on is iPhone/iPad (iOS).

I see this is the different repo, not suer. Have you ever had `suer` build with the expected header? I need this info to identify the differences of the images

**Comment by Halo-Michael** [comment]
The only different is not used image 20210412.2.

**Comment by dsame** [comment]
@Halo-Michael 

Meanwhile i compared the headers of suer and suer_broken and identified the differences as having empty "size" field in the broken binary:

![image](https://user-images.githubusercontent.com/245540/115500764-698e0100-a28b-11eb-8f7f-0650925c4007.png)

Comparing the Makefiles of Suer and Generatore-Auto-Setter i see the extra clang flag `-arch armv7` of the broken suer build:

```xcrun -sdk iphoneos clang -arch armv7 -arch arm64 -arch arm64e -O3 -miphoneos-version-min=9.0```

vs

```xcrun -sdk iphoneos clang -arch arm64 -arch arm64e -miphoneos-version-min=9.0```

As the next step, please try to build suer without `-arch armv7` flag and confirm is it broken or not. 
Also it makes sense to ask the clang team/support/community for the reason why the "size" header field is zeroed

**Comment by Halo-Michael** [comment]
Xcode11.7 or macOS10.15 did not remove support for armv7 builds, so I don’t know why I need to do this.
I think it's a bug of your image.

**Comment by Halo-Michael** [comment]
> Xcode11.7 or macOS10.15 did not remove support for armv7 builds, so I don’t know why I need to do this.
> I think it's a bug of your image.

Even Xcode12 or macOS11 has not removed support for armv7 builds.

**Comment by Halo-Michael** [comment]
To be honest, I just use github active to run build tests and not really need the packages built by it. I am now distributing packages compiled from my personal device. Even if I don't raise/you don't fix this problem, it won't affect me in any way, I just think you should know that there is a problem with your stuff.

**Comment by Halo-Michael** [comment]
If you don’t want to study this issue, I can close this issue right now.

**Comment by Halo-Michael** [comment]
If you don’t want to research this issue, I can close this issue now.

**Comment by dsame** [comment]
i confirm arm-v7 is not an issue and removing it still does not populate `size` field of mach-o header.

https://github.com/dsame/suer/runs/2397809208?check_suite_focus=true

The local build with xcode-12.0.1 produces correct  mach-o binary though

**Comment by Halo-Michael** [comment]
> i confirm arm-v7 is not an issue and removing it still does not populate `size` field of mach-o header.
> 
> https://github.com/dsame/suer/runs/2397809208?check_suite_focus=true
> 
> The local build with xcode-12.0.1 produces correct mach-o binary though

The only one reason I used Xcode11.7 insted of Xcode12 is Apple just changed the ABI of arm64e since iOS14/Xcode12, The new ABI compatible the old one but otherwise is not. So I have to build on Xcode11.7 in order to provide compatibility with the old system as much as possible.

**Comment by dsame** [comment]
@Halo-Michael 
jfi: the problem is with `ldid` - it erases `size` field of the header
https://github.com/dsame/suer/runs/2400475328?check_suite_focus=true

**Comment by dsame** [comment]
@Halo-Michael 
I've built ldid from the sources and not the build succeeded 
https://github.com/dsame/suer/runs/2400773904?check_suite_focus=true

Moreover the success build you've provided https://github.com/Halo-Michael/Generator-Auto-Setter/runs/2260079781
used ldid@2.1.2 alike local build

and the failed build https://github.com/Halo-Michael/suer/runs/2363905101  used ldid@2.1.3

Thus i believe the problem is identified and it is ldid@2.1.3 and we can not do something with it. 

Do you think the issue can be closed with this?

**Comment by Halo-Michael** [comment]
> @Halo-Michael
> I've built ldid from the sources and not the build succeeded
> https://github.com/dsame/suer/runs/2400773904?check_suite_focus=true
> 
> Moreover the success build you've provided https://github.com/Halo-Michael/Generator-Auto-Setter/runs/2260079781
> used ldid@2.1.2 alike local build
> 
> and the failed build https://github.com/Halo-Michael/suer/runs/2363905101 used ldid@2.1.3
> 
> Thus i believe the problem is identified and it is ldid@2.1.3 and we can not do something with it.
> 
> Do you think the issue can be closed with this?

Yes, the cause of the problem is that brew released a broken version of ldid. Although it was repaired afterwards, github active cached the installation information of the problematic ldid, and I did not execute brew update.
