### ISSUE TITLE
Add Clojure CLI tools

### ISSUE THREAD

**Issue by benknoble** [actions/virtual-environments#322]
**Tool information**
- Tool name: Clojure CLI tols
- Add or update? Add
- Desired version: The latest stable is 1.10.1
- Approximate size: 21.1MB
- If this is an add request:
  - Brief description of tool: Clojure CLI tools provides a native toolset for managing Clojure projects and is now the de-facto way to use Clojure.
  - URL for tool's homepage: [https://clojure.org]()

**Area for Triage**: None seemed appropriate

**Question, Bug, or Feature?**: Feature

**Virtual environments affected**
- [x] macOS 10.15
- [x] Ubuntu 16.04 LTS
- [x] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

I don't know if Windows would want this, but I assume it could be supported by all? I do know that Windows folks struggle with Clojure installations.

**Can this tool be installed during the build?**

On a mac, at least, using brew: `brew install clojure`. Not including download time, takes about 4-7s.

For linux, they give the following as install instructions, suggesting it may not be so easy:

```
curl -O https://download.clojure.org/install/linux-install-1.10.1.502.sh
chmod +x linux-install-1.10.1.502.sh
sudo ./linux-install-1.10.1.502.sh
```

I'm not sure if Ubuntu has a Clojure package, and I don't have access to a machine to check.

**Are you willing to submit a PR?**

Yes, except that I don't know how to add a tool to the virtual environments.

**Comment by thejoebourneidentity** [comment]
Thanks for your suggestion 🙏. Considering how easy it is to install during your run, this is not something we will add to the image at this time.
