### ISSUE TITLE
Ubuntu: `GRADLE_HOME` set to nonexistent directory

### ISSUE THREAD

**Issue by eamonnmcmanus** [actions/virtual-environments#3221]
**Description**  
[`java-tools.sh`](https://github.com/actions/virtual-environments/blob/main/images/linux/scripts/installers/java-tools.sh)
unpacks the latest Gradle distribution directly into `/usr/share`, leading to a directory like `/usr/share/gradle-7.0`. It then correctly links `/usr/bin/gradle` to `/usr/share/gradle-7.0/bin/gradle`. But then it sets `GRADLE_HOME` to `/usr/share/gradle`, which doesn't exist.

I think it should set `GRADLE_HOME` to `/usr/share/gradle-7.0`, or it should symlink or rename `/usr/share/gradle-7.0` to `/usr/share/gradle`.

**Area for Triage**:  
Java

**Question, Bug, or Feature?**:  
Bug

**Virtual environments affected**  
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [x] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Image version**
https://github.com/actions/virtual-environments/releases/tag/ubuntu20%2F20210412.1

**Expected behavior**  
`GRADLE_HOME` set to a directory containing the Gradle installation.

**Actual behavior**  
`GRADLE_HOME` set to a nonexistent directory.

**Repro steps**  
Depend on `GRADLE_HOME` to contain a Gradle installation.

**Comment by dibir-magomedsaygitov** [comment]
Hello, @eamonnmcmanus. Thank you for your report. We will take a look and come back with the results.

**Comment by dibir-magomedsaygitov** [comment]
Hello, @hashtagchris. We have merged PR with the fix. Images should be available with the next week's Rollout. I'll post an update message.

**Comment by dibir-magomedsaygitov** [comment]
Hello @eamonnmcmanus. Images with the fix were successfully updated. I'm going to close this issue. Feel free to contact us if you have any concerns.
