### ISSUE TITLE
Haskell windows 2019 fails with version check

### ISSUE THREAD

**Issue by AHuusom** [actions/virtual-environments#3223]
**Description**  
The sorting mechanism on the versioning is off and shows 3 different outcomes on 3 different VMS.
The if statement testing if version is < 8 is testing against a unused variable.

**Area for Triage**:  
Haskell

**Question, Bug, or Feature?**:  
Bug

**Virtual environments affected**  
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11.0
- [x] Windows Server 2016 R2
- [x] Windows Server 2019

**Image version**
?

**Expected behavior**  
That it sets the newest version as default

**Actual behavior**  
As the sorting mechanism isn't working, if version 9 is shown as the newest it works as haskell path is always set to the versions 9's executable.
This is because it tests against a $null variable and thus always sets the path to version 9

**Repro steps**  
Just run the haskel section on windows 2019

I've made a PR with the corrections [/pull/3219] please review it

**Comment by miketimofeev** [comment]
@AHuusom Thanks for your fix. However, it looks like we need to raise the issue in the choco repository because we should have 3 latest versions, but not 3 random versions

**Comment by AHuusom** [comment]
@miketimofeev Choco definetely gives you over 3 versions... but the sorting done by the code to get the latest was faulty, as it sorted on the count instead of the version naming.

**Comment by miketimofeev** [comment]
@AHuusom yeah, it gives, but sometimes not all the versions
https://github.com/actions/virtual-environments/issues/2882#issuecomment-819356981

**Comment by miketimofeev** [comment]
Create a bug in the choco repository regarding version 9.0.1
https://github.com/chocolatey/choco/issues/2271

**Comment by miketimofeev** [comment]
We've implemented a test to make sure version 9.* is installed.
@AHuusom I'm going to close the issue. Thank you for your contribution!

**Comment by AHuusom** [comment]
It's failing now again.
The test fails if version 9.* isn't installed, but when I run the install-haskell script my vm's only get presented with sub version 9.*
So the test will always fail, and I cannot install version 9 as I don't get the option.

**Comment by miketimofeev** [comment]
@AHuusom test is failed if version 9.0.1 is not found among the others. We did it intentionally to avoid a sudden GHC downgrade. I've created an issue in choco repo regarding inconsistent search chocolatey/choco#2271

**Comment by AHuusom** [comment]
Thanks, I followed the link to the issue and integrated the Odata query in our solution so our build doesn't fail.
Version 9.0.1 will now be installed.
