### ISSUE TITLE
GitHub Actions has encountered an internal error when running your job.

### ISSUE THREAD

**Issue by KSXGitHub** [actions/virtual-environments#3224]
**Description**  
When using matrix, some check fail due to internal error, some don't.

**Workflows:**

* https://github.com/KSXGitHub/padded-column/actions/runs/769697506
* https://github.com/KSXGitHub/padded-column/actions/runs/769719087
* https://github.com/KSXGitHub/padded-column/actions/runs/769794294

**Comment by gep13** [comment]
Looks like there is a known issue currently:

https://www.githubstatus.com/incidents/cj7gzzj30411

**Comment by dibir-magomedsaygitov** [comment]
Hello, @KSXGitHub. As @gep13 mentioned, we are experiencing service degradation at the moment. Sorry for the inconvenience.

**Comment by KSXGitHub** [comment]
It's working now
