### ISSUE TITLE
Add Xcode 12.5 RC

### ISSUE THREAD

**Issue by bielikb** [actions/virtual-environments#3226]
**Tool information**
- Tool name: Xcode
- Add or update? Update
- Desired version: Xcode 12.5 RC
- Approximate size:  -

Download link:
[https://developer.apple.com/services-account/download?path=/Developer_Tools/Xcode_12.5_Release_Candidate/Xcode_12.5_Release_Candidate.xip](https://developer.apple.com/services-account/download?path=/Developer_Tools/Xcode_12.5_Release_Candidate/Xcode_12.5_Release_Candidate.xip)

**Area for Triage**:
Apple
Xcode

**Question, Bug, or Feature?**:
Feature

**Virtual environments affected**
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [x] macOS 10.15
- [x] macOS 11.0
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Can this tool be installed during the build?**
This tool should come prebuilt on the image

**Tool installation time in runtime**
-

**Are you willing to submit a PR?**
I have no prior knowledge how to update Xcode for GHA

**Comment by miketimofeev** [comment]
Hi @bielikb!
Xcode 12.5 is available for macOS 11 only. The version has been updated recently:
https://github.com/actions/virtual-environments/pull/3222#pullrequestreview-640801757
I'm going to close the issue. Please feel free to contact us if you have any concerns/
Thank you!

**Comment by bielikb** [comment]
Hi @miketimofeev,

thanks, that's perfect!

Best,
Boris

**Comment by marcbaldwin** [comment]
However macOS 11 is still only available as private preview, when will this be made public?

**Comment by al-cheb** [comment]
> However macOS 11 is still only available as private preview, when will this be made public?

Please check - https://github.com/actions/virtual-environments/issues/2072

**Comment by AlenaSviridenko** [comment]
@marcbaldwin, please track the progress in the pinned issue https://github.com/actions/virtual-environments/issues/2486
