### ISSUE TITLE
Rootless podman broken in Ubuntu 20.04 20210419.1

### ISSUE THREAD

**Issue by bgilbert** [actions/virtual-environments#3229]
**Description**  

On Ubuntu 20.04 20210419.1 (with Podman 3.1.0), running Podman as non-root fails with errors about overlay mounts ([example](https://github.com/coreos/fedora-coreos-docs/runs/2403706798?check_suite_focus=true)).  20210412.1 (with Podman 3.0.1) does not have this problem, nor does Ubuntu 18.04 20210419.1 (which also has Podman 3.0.1).  Running Podman with `sudo` avoids the problem.

**Area for Triage**:  
Containers

**Question, Bug, or Feature?**:  
Bug

**Virtual environments affected**  
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [x] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Image version**
20210419.1

**Expected behavior**  
podman runs containers successfully.

```
Run podman run -i --rm quay.io/coreos/butane --version
Trying to pull quay.io/coreos/butane:latest...
Getting image source signatures
Copying blob sha256:d3c6293bedac09477b0e3313e3878b708e4fb98ff540904b4b4dc406177a19f9
Copying config sha256:02a0f41a4d52be21eadbb708ad186784146221bf09fa8f8e18d4e8c2a6c8ca15
Writing manifest to image destination
Storing signatures
Butane v0.11.0-10-gca69de7
```

**Actual behavior**  
podman fails.

```
Run podman run -i --rm quay.io/coreos/butane --version
Trying to pull quay.io/coreos/butane:latest...
Getting image source signatures
Copying blob sha256:d3c6293bedac09477b0e3313e3878b708e4fb98ff540904b4b4dc406177a19f9
Copying config sha256:02a0f41a4d52be21eadbb708ad186784146221bf09fa8f8e18d4e8c2a6c8ca15
Writing manifest to image destination
Storing signatures
time="2021-04-21T19:28:11Z" level=error msg="error unmounting /home/runner/.local/share/containers/storage/overlay/7bef383521d9eb4947017f545da278d3b8201cd7d45a76657f8ea63fb475441b/merged: invalid argument"
Error: error mounting storage for container f50b72958c2c594bade85c921bdc2ca6ed51ae2048b8e749d8ad89ee0d598cb0: error creating overlay mount to /home/runner/.local/share/containers/storage/overlay/7bef383521d9eb4947017f545da278d3b8201cd7d45a76657f8ea63fb475441b/merged, mount_data=",lowerdir=/home/runner/.local/share/containers/storage/overlay/l/BY3WIG5HI7QJUKJFQ2KZLFZUUH,upperdir=/home/runner/.local/share/containers/storage/overlay/7bef383521d9eb4947017f545da278d3b8201cd7d45a76657f8ea63fb475441b/diff,workdir=/home/runner/.local/share/containers/storage/overlay/7bef383521d9eb4947017f545da278d3b8201cd7d45a76657f8ea63fb475441b/work,userxattr": invalid argument
Error: Process completed with exit code 126.
```

**Repro steps**  
A description with steps to reproduce the issue. If your have a public example or repo to share,
please provide the link.

1. Add a job step:

```
      - name: Trivial Podman run
        run: podman run -i --rm quay.io/coreos/butane --version
```

**Comment by dibir-magomedsaygitov** [comment]
Hello @bgilbert. Thank you for your report. We will take a look at this issue.

**Comment by dsame** [comment]
The workaround to make the build succeeded is to add fuse overlay and activate it for the containers
```
      - name: insall fuse
        run: |
          sudo apt-get install fuse-overlayfs
          mkdir -vp ~/.config/containers
          printf "[storage.options]\nmount_program=\"/usr/bin/fuse-overlayfs\"" > ~/.config/containers/storage.conf
```

**Comment by dsame** [comment]
@bgilbert please try the suggest workaround and confirm if it works for you

**Comment by dsame** [comment]
@bgilbert i see few green builds since the workaround commit, does it solve the problem?

**Comment by bgilbert** [comment]
I applied a different workaround in the repo that was having this problem.  I will try the workaround you suggested and report back.

**Comment by bgilbert** [comment]
@dsame Yup, looks like the workaround works.

**Comment by bgilbert** [comment]
It appears this is fixed in 20210425.1.

**Comment by miketimofeev** [comment]
@bgilbert good news, thanks! 20210425.1 contains podman 3.1.2

**Comment by miketimofeev** [comment]
@bgilbert the new images with podman 3.1.2 have been deployed.
I'm going to close the issue. Please feel free to contact us if you have any concerns.
Thank you!
