### ISSUE TITLE
NPE in JS action causes Error: Dr instead of useful error message

### ISSUE THREAD

**Issue by rnett** [actions/virtual-environments#3231]
**Description**  
I have an action running ~`git add -A`~ `git commit`.  This fails with `Error: Dr` or `Error: ls` which tells me nothing.  I'm not sure if this is the right place for the issue, as I have no idea what's responsible.

Logs: https://github.com/rnett/krosstalk/runs/2406588263?check_suite_focus=true

I'm running this command through a custom action, which uses `actions/exec`.  The command does not show up in the terminal.  This initially led me to believe the issue was with `git add`, but running just the add works fine.

**Area for Triage**:  
Git

**Question, Bug, or Feature?**:  
Bug

**Virtual environments affected**  
- [x] Ubuntu 20.04

**Image version**
20210412.1

**Expected behavior**  
The command works, or fails with a reasonable error message.

**Actual behavior**  
The command fails with `Error: Dr` or `Error: ls`.

**Repro steps**  
See https://github.com/rnett/krosstalk/runs/2406588263?check_suite_focus=true

**Comment by rnett** [comment]
After splitting the `git add -A` into `git add .` and `git add -u`, only `git add -u` fails with `Error: is`.

**Comment by rnett** [comment]
Furthermore, capturing the output of the command and printing it manually regardless of the error code (via actions/exec) does not seem to work.

**Comment by rnett** [comment]
This is especially odd since `git` is version `2.31.1`, which means `git add .` is `git add -A` by default.

**Comment by rnett** [comment]
Well, `git add .` fails if it's all I run, so it's likely not either of the add commands failing, but instead a subsequent command that isn't shown in the log for some reason.

**Comment by rnett** [comment]
Alright, so this was because of a NPE in my JS action.  I'm leaving it open because the error messages (or rather lack thereof) seems like a environment issue.

**Comment by maxim-lobanov** [comment]
Hello @rnett , I think https://github.com/actions/toolkit is correct repo because they own actions/exec.
