### ISSUE TITLE
Ubuntu agent pool 2004 (20210419 update) - some agents are on Chrome v89 and some on v90

### ISSUE THREAD

**Issue by simonDominos** [actions/virtual-environments#3234]
At some point overnight we noticed some tests passing and some failing in our build pipeline. I had a look  and it looks like some Ubuntu 20.04 agents have Chrome v89 installed and some have v90. 

Further looks into this when we run the initialise job i noticed the build is selecting a different image version even though we use the same agent pool...

Current image version: '20210412.1' - this has Chrome v89
Current image version: '20210419.1' - this has Chrome v90

I presume all agents in this pool should be on the same image version

**Comment by miketimofeev** [comment]
Hi @simonDominos! it takes time to propagate the image to all the environments. We're going to finish the 20210419.1 image deployment today. Sorry for the inconvenience!
I'm going to close the issue. Please feel free to contact us if you have any concerns.
Thank you!
