### ISSUE TITLE
[ubuntu] Clang 9 will be removed on May, 17th and default will be set to Clang 11

### ISSUE THREAD

**Issue by AlenaSviridenko** [actions/virtual-environments#3235]
**Breaking changes**
Clang 9 will be removed from Ubuntu 20.04 images in favor of Clang 12, also default will be set to Clang 11

**Target date**
Image deployment will start on May, 17th and will take 3-4 days

**The motivation for the changes**
Based on our [guidelines](https://github.com/actions/virtual-environments/blob/main/docs/software-and-images-guidelines.md#software-and-images-support-policy) we support 3 latest major versions of Clang, so in order to add a new one, we are removing Clang 9.

**Possible impact**
Projects that depend on Clang 9 or Clang 10 will be broken.

**Virtual environments affected**
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [x] Ubuntu 20.04
- [ ] macOS 10.13
- [ ] macOS 10.14
- [ ] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Mitigation ways**
The snippet below allows you installing Clang 9
```
sudo apt-get update
sudo apt-get install -y "clang-9" "lldb-9" "lld-9" "clang-format-9"
```

The following snippet will change default version to Clang 10 back:
```
update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++-10 100
update-alternatives --install /usr/bin/clang clang /usr/bin/clang-10 100
update-alternatives --install /usr/bin/clang-format clang-format /usr/bin/clang-format-10 100
```

**Comment by AlenaSviridenko** [comment]
Good point, we can do that as well. I'll update the announcement, thanks!

**Comment by claremacrae** [comment]
> **Possible impact**
> Projects that depend on Clang 9 or Clang 10 will be broken.

Why could projects that depend on Clang 10 be broken?

**Comment by miketimofeev** [comment]
@claremacrae looks like there is a mistake in the initial message. We're going to remove clang 9 only.

**Comment by miketimofeev** [comment]
The deployment was completed.
