### ISSUE TITLE
NuGet 5.9.1.11 seems to not work

### ISSUE THREAD

**Issue by dovholuknf** [actions/virtual-environments#3240]
**Description**  
Using latest windows, our builds are failing in our nuget restore stage.  Issue appears to have started "a few days ago" but it's pretty consistent today. I noticed that recently nuget was updated and it certainly feels relevant. I posted on the community but it's gotten no traction here: https://github.community/t/nuget-packages-are-failing-to-resolve/176103

**Area for Triage**:  
'Area: .NET Framework'

**Question, Bug, or Feature?**:  
Bug

**Virtual environments affected**  
- [ ] Windows Server 2019 is the only one I've tested

**Image version**
Version: 20210419.1

**Expected behavior**  
I expect `nuget restore ZitiDesktopEdge.sln` to succeed

**Actual behavior**  
`nuget restore ZitiDesktopEdge.sln` fails with numerous errors:
```
Errors in packages.config projects
    Unable to find version '12.0.3' of package 'Newtonsoft.Json'.
      C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\: Package 'Newtonsoft.Json.12.0.3' is not found on source 'C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\'.
    Unable to find version '4.7.8' of package 'NLog'.
```

**Repro steps**  
Build is here: https://github.com/openziti/desktop-edge-win/runs/2410365193?check_suite_focus=true
github action declared here: https://github.com/openziti/desktop-edge-win/blob/e5d227fc516269773b2d0211ff4c1261791a3134/.github/workflows/installer.build.yml#L56-L57

**Comment by maxim-lobanov** [comment]
Could you please try to downgrade nuget version in runtime via https://github.com/marketplace/actions/setup-nuget-exe-for-use-with-actions and confirm that it fixes the issue

**Comment by mary-dcouto** [comment]
Clint and I tested 2 different Nuget versions, but both of them failed. Later we used the 'latest' tag in the nuget version and it worked. Thanks for the help. 

      - uses: nuget/setup-nuget@v1
        with:
          nuget-api-key: ${{ secrets.NuGetAPIKey }}
          nuget-version: 'latest'

**Comment by dovholuknf** [comment]
Looks like that ran and succeeded with:
nstalled nuget.exe version 5.8.1

https://github.com/openziti/desktop-edge-win/runs/2417370034?check_suite_focus=true

**Comment by FlorianReimold** [comment]
We are having the same issues in our project. Downgrading nuget to 5.8.x solved the issue.

https://github.com/continental/ecal/commit/6d3e96be348a8240116883d3217fade94bef901c

**Comment by maxim-lobanov** [comment]
Closing as "external" and related to NuGet
