### ISSUE TITLE
Add [Sfdx CLI]

### ISSUE THREAD

**Issue by hectorgb** [actions/virtual-environments#3249]
**Tool information**
- Tool name: Sfdx CLI
- Tool license: 
- Add or update? Add
- Desired version: latest
- Approximate size: 27Mb
- If this is an add request:
  - Brief description of tool: A CLI to manage Salesforce developments. Is a tool to push/retrieve, package, env organizer, etc.
  - URL for tool's homepage: https://developer.salesforce.com/tools/sfdxcli#
  - Provide a basic test case to validate the tool's functionality: 

**Area for Triage**:

**Question, Bug, or Feature?**:

**Virtual environments affected**
- [ x] Ubuntu 16.04
- [ x] Ubuntu 18.04
- [ x] Ubuntu 20.04
- [ x] macOS 10.15
- [ x] macOS 11.0
- [ x] Windows Server 2016 R2
- [ x] Windows Server 2019

**Can this tool be installed during the build?**
yes, but takes time. It can be istalles with npm or bin

**Tool installation time in runtime**
depends, can take around 30-40 seconds

**Are you willing to submit a PR?**
Yes, i do.

**Comment by maxim-lobanov** [comment]
Hello, have you tried an action for Salesforce?
https://github.com/marketplace/actions/salesforce-sfdx-cli-action

**Comment by hectorgb** [comment]
@maxim-lobanov thanks!
