### ISSUE TITLE
The macos-latest CI check always shows as cancelled after renaming branch

### ISSUE THREAD

**Issue by Integralist** [actions/virtual-environments#3251]
**Description**  
I renamed a repository branch from `master` to `main` and subsequently discovered the CI check for macos stopped working with a vague message that simply stated `This check was cancelled` ([example PR](https://github.com/fastly/cli/pull/264)).

I tried to move from `macos-latest` to `macos-11.0` just to see if there was an issue with 'latest' and what happened instead was that the Ubuntu and Windows 'latest' CI checks (which were working fine) suddenly failed with the `This check was cancelled` error while the macos check changed to `This check failed`. In either case the error message isn't detailed enough for me to make any meaningful progress.

**Virtual environments affected**  
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [x] Ubuntu 20.04
- [x] macOS 10.15
- [x] macOS 11.0
- [ ] Windows Server 2016 R2
- [x] Windows Server 2019

**Comment by LeonidLapshin** [comment]
Hey, @Integralist !
We will investigate the issue and return with details soon :)

**Comment by LeonidLapshin** [comment]
@Integralist, seems that this problem related to runner, not the image, i guess that [this is the correct repo for issue](https://github.com/actions/runner), could you please create an issue on runner's repo?

**Comment by Integralist** [comment]
Closing this issue as it's been moved to the appropriate repo: https://github.com/actions/runner/issues/1065
