### ISSUE TITLE
Update Visual Studio Enterprise

### ISSUE THREAD

**Issue by jakemumu** [actions/virtual-environments#3252]
**Tool information**
- Tool name: Visual Studio Enterprise
- Add or update? Update
- Desired version: 16.10.0 / 16.9.4

**Question, Bug, or Feature?**:
The change the VS studio version on these runner has caused a regression.

https://developercommunity.visualstudio.com/t/Toolset-169-regression-vcxproj-producin/1356639

**Virtual environments affected**
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [x] Windows Server 2019

**Can this tool be installed during the build?**
Unsure

**Are you willing to submit a PR?**
No sure how : )

**Comment by LeonidLapshin** [comment]
Hey, @jakemumu !
We always try to install the latest available VS version. Currently the VisualStudio/16.9.4+31205.134 is installed on Windows 2019 image and as far as I can see on [Microsoft docs](https://docs.microsoft.com/en-us/visualstudio/releases/2019/release-notes) page, 16.10 version is not released yet. Comments from the link that you have provided tell that 16.9.4 is ok, so you can use Windows 2019 image for your app. 
Could you please check your build with Windows 2019 image?

**Comment by friendlyanon** [comment]
I'm not sure if this would resolve my issue as well, but there are bugs in the Windows SDK version 10.0.17763.0 that cause [`C5105` warnings](https://github.com/friendlyanon/cmake-init/runs/2433960762?check_suite_focus=true) with the new standards conforming preprocessor (enabled with `/Zc:preprocessor`), which are fixed in a later version (locally I have 10.0.18362.0 and that reports no such warnings).

**Comment by miketimofeev** [comment]
@friendlyanon we have a lot of SDKs preinstalled and 10.0.18362.0 is one of them:
![image](https://user-images.githubusercontent.com/48208649/116068354-d4c44280-a692-11eb-933b-7e6b55bf0ca7.png)

**Comment by friendlyanon** [comment]
Yes, you are correct and my comment is unrelated to this issue. Sorry for that.

I should look into how to set a newer version to be the default used by CMake.
