### ISSUE TITLE
Proposal: Increase Linux stack space

### ISSUE THREAD

**Issue by robburger** [actions/virtual-environments#3257]
**Description**  
When passing the output from one action to the input of another, there's a chance of receiving an `Error: Argument list too long` message, causing the workflow to fail.

By default, the modern stack space allocation in Linux distros is `8192KB`, of which 1/4 (`2048KB`) is available to the argument list. See [Limits on size of arguments and environment](https://manpages.debian.org/buster/manpages-dev/execve.2.en.html#Limits_on_size_of_arguments_and_environment) (taken from Debian `man` because they have an anchor link, but all distros are the same.)

Get the current values:  
```shell
# Get the current stack space allocation, returned in KB
$ ulimit -s
8192
# Get the allocation to argument list, returned in bytes
$ getconf ARG_MAX
2097152
```

**Why raise this issue?**
I'm maintaining the [terraform-pr-commenter](https://github.com/robburger/terraform-pr-commenter) action that takes in the output of a Terraform `plan` step and adds a formatted GitHub PR comment. If the `plan` output step returns data greater than `2048KB`, which, granted, is a massive plan, the workflow fails as the output cannot be passed to the container in the argument list.

I'm sure that someone in future will likely face a similar problem.

**Area for Triage**:  

Servers

**Question, Bug, or Feature?**:  

Question

**Virtual environments affected**  
- [x] Ubuntu 16.04
- [x] Ubuntu 18.04
- [x] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Image version**

Ubuntu*

**Expected behavior**  
As a consumer of output data returned from another action in a workflow, I expect to be able to pass the data to the next action.

**Actual behavior**  
If the data passed in to the action input is more than 2048KB, an `Error: Argument list too long` message is returned, and the workflow fails.

**Repro steps**  
1. Produce more than 2048KB output in an action step and pass it in as an argument to a subsequent action step.

**Proposal:**  
To resolve this, there could be a step added to https://github.com/actions/virtual-environments/blob/cd4ecad2e636fbea5182332679e04d793fbf642c/images/linux/scripts/base/limits.sh that doubles the available stack space:  
```shell
ulimit -s 16384
```

I'm happy to create a PR that adds this (if it's the right place) and there's an agreement on a `16384KB` stack size?

**Comment by maxim-lobanov** [comment]
@robburger thank you for reporting and proposal. The change looks safe enough for me.
@al-cheb , @miketimofeev do you see any objections / potential issues if we increase limits?

**Comment by miketimofeev** [comment]
@maxim-lobanov no objections. The change sounds reasonable.

**Comment by maxim-lobanov** [comment]
@robburger , feel free to prepare PR:
> To resolve this, there could be a step added to https://github.com/actions/virtual-environments/blob/cd4ecad2e636fbea5182332679e04d793fbf642c/images/linux/scripts/base/limits.sh that doubles the available stack space:
ulimit -s 16384

Your proposal sounds good.

**Comment by robburger** [comment]
Thanks @maxim-lobanov, PR opened. Please let me know if you'd like me to build and test the images or if there are any additional docs to update.

**Comment by maxim-lobanov** [comment]
@robburger , thank you for contribution!
Changes were merged into the main and should be propagated everywhere by the end of next week. Will keep issue opened and let you know when deployment is finished

**Comment by miketimofeev** [comment]
@robburger The PR has been merged. The new images with the changes will be deployed next week.
Thank you!

**Comment by al-cheb** [comment]
@robburger , New images have been deployed.

![image](https://user-images.githubusercontent.com/47745270/118135386-a329d600-b40b-11eb-84ff-d30ae05ad6d5.png)
