### ISSUE TITLE
windows-2019 image is running out of space in drive C:

### ISSUE THREAD

**Issue by jneira** [actions/virtual-environments#326]
**Describe the bug**
The default space in drive C: after just start job is very slow. Installing packages with chocolatey in the deafult drive `C:` fails with "not enough disk space error". Drive `D:` has a lot of free space though. I think the space is slowly being eaten by default installations cause it had enough space to run my jobs one month ago.

* space in c: after installing ghc using chocolatey ([see job log](https://dev.azure.com/jneira/haskell-ide-engine/_build/results?buildId=523&view=logs&j=0182ba76-f1d3-5f57-02fc-8d483fa8bef0&t=29d7819d-506a-5e05-e75a-6d382d179d97))
```
Chocolatey installed 1/1 packages. 
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
Filesystem           1K-blocks      Used Available Use% Mounted on
C:/Program Files/Git 133703676 127843192   5860484  96% /
D:                    14678972   1897100  12781872  13% /d
```

**Area for Triage**: Servers

**Question, Bug, or Feature?**: Bug

**Virtual environments affected**
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [X] Windows Server 2019

**Expected behavior**
The main drive C: should have a reasonable amount of free space.

**Actual behavior**
Insatlling two ghc's fill up the drive.

1. Install default ghc with `choco install -y ghc --version=8.6.5`
2. Install another ghc version: `choco install -y ghc --version=8.4.4`

Unfortunately installing ghc with choco has not options to choose another drive to make the install and move it consumes time and it is not very reliable.

**Comment by miketimofeev** [comment]
@jneira thanks for reporting this!
We're already working on extending disk C:\ to 256Gb
[Upsize Win19 to 256 GB](https://github.com/actions/virtual-environments/pull/309)

**Comment by jneira** [comment]
@miketimofeev wow, thanks for the quick response and for your amazing work.
I think we can close this then :smiley_cat:
