### ISSUE TITLE
Setup 403 errors returned when downloading action

### ISSUE THREAD

**Issue by retbrown** [actions/virtual-environments#3269]
**Description**  
During the setup phase the latest ubuntu images seem to be returning a 403 error when trying to download an action from github api. This is in relation to the following action: InVisionApp/private-action-loader. Previous version of the ubuntu image (20210412.1) was able to download but (20210419.1) now seems unable to download this action. Issue in original repo: https://github.com/InVisionApp/private-action-loader/issues/305

**Area for Triage**:  

Servers

**Question, Bug, or Feature?**:  

Bug

**Virtual environments affected**  
- [ ] Ubuntu 16.04
- [x] Ubuntu 18.04
- [x] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Image version**

20210419.1

**Expected behavior**  

private-action-loader action is downloaded successfully.

**Actual behavior**  

private-action-loader returns 403 (Forbidden) error when downloading

**Repro steps**  

Example repo can be found here: https://github.com/realyse/actions-testing with a failed run found here: https://github.com/realyse/actions-testing/runs/2436937901?check_suite_focus=true

**Comment by LeonidLapshin** [comment]
Hey, @retbrown !
We'll look at this issue and return with details soon :)

**Comment by retbrown** [comment]
Version 20210425.1 seems to have resolved the issue. I can't work out from the release notes why that might have been the case though. I can only assume it must be the updated github-cli version
