### ISSUE TITLE
Add GCC 11

### ISSUE THREAD

**Issue by EwoutH** [actions/virtual-environments#3280]
Today GCC 11.1 [was released](https://gcc.gnu.org/pipermail/gcc/2021-April/235922.html), the first stable release of GCC 11. 

Currently GCC gets installed using the [gcc.sh](https://github.com/actions/virtual-environments/blob/main/images/linux/scripts/installers/gcc.sh) installer script, using the versions in the [toolset-2004.json](https://github.com/actions/virtual-environments/blob/main/images/linux/toolsets/toolset-2004.json#L253) and [toolset-1804.json](https://github.com/actions/virtual-environments/blob/main/images/linux/toolsets/toolset-1804.json#L251) files. It uses the [ubuntu-toolchain-r/test](https://launchpad.net/~ubuntu-toolchain-r/+archive/ubuntu/test) repository, which doesn't have gcc-11 available.

At this moment, a stable GCC 11 version is not yet available on either [Ubuntu packages](https://packages.ubuntu.com/search?keywords=gcc-11&searchon=names&suite=all&section=all) (so not for focal-updates) or [Debian packages](https://packages.debian.org/search?keywords=gcc-11&searchon=names&suite=all&section=all) (only on experimental), which is where the complication starts.

Options to install GCC-11:
 - Building from source
 - Building once and caching/hosting somewhere
 - Using experimental toolchain
 - Waiting for package managers to update
 - More?

Lets use this issue to discuss how GCC 11 can be installed best on the Ubuntu images.

> **Tool information**
> - Tool name: GCC (GNU Compiler Collection)
> - Tool license: [Modified GNU General Public License version 3](https://gcc.gnu.org/onlinedocs/libstdc++/manual/license.html)
> - Add or update? Update
> - Desired version: [11](https://gcc.gnu.org/gcc-11/)
> - Approximate size: 199 MB installed
> 
> **Area for Triage**: C/C++
> 
> **Question, Bug, or Feature?**: Feature
> 
> **Virtual environments affected**
> - [x] Ubuntu 18.04
> - [x] Ubuntu 20.04
> 
> **Can this tool be installed during the build?**
> Yes
> 
> **Tool installation time in runtime**
> Probably about the same other GCC versions
> 
> **Are you willing to submit a PR?**
> Depends

**Comment by AlenaSviridenko** [comment]
Hi @EwoutH,
we'd prefer to wait until package is releases in the official package managers to avoid maintenance of a separate script.
We can keep this issue open for tracking progress.

**Comment by MehdiChinoune** [comment]
https://launchpad.net/~ubuntu-toolchain-r/+archive/ubuntu/test?field.series_filter=focal

**Comment by EwoutH** [comment]
Wow that was fast! Thanks for the heads-up @MehdiChinoune, I opened a PR: #3291

**Comment by dsame** [comment]
@EwoutH Hi, there's a potential problem with gcc-11: it brings GLIBCXX_3.4.29 version of libstdc++ tha is 1 minor version above  GLIBCXX_3.4.28 of users of  ubuntu 2.0 expect to have. 

I afraid the binaries compiled against GLIBCXX_3.4.29 on actions won't work on fresh ubuntu 20.04 images. The bad thing is the user's won't notice the problems during the using the action but may get the crashes on their production systems and definitely will be frustrated because of unclear reason.

Can you please confirm the capability of binaries compiled against GLIBCXX_3.4.29 to live in runtime with GLIBCXX_3.4.28 ?

**Comment by dsame** [comment]
@EwoutH can you please take a look at this PR https://github.com/actions/virtual-environments/pull/3451 - do you think the solution works to you?
