### ISSUE TITLE
Update podman to 3.1.2

### ISSUE THREAD

**Issue by tetchel** [actions/virtual-environments#3282]
**Tool information**
- Tool name:  podman
- Tool license: 
- Add or update?  Update
- Desired version:  3.1.2
- Approximate size: 
- If this is an add request:
  - Brief description of tool: 
  - URL for tool's homepage: 
  - Provide a basic test case to validate the tool's functionality: 

**Area for Triage**:

**Question, Bug, or Feature?**:

Bug

**Virtual environments affected**
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [x] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Can this tool be installed during the build?**

**Tool installation time in runtime**

**Are you willing to submit a PR?**

<hr/>

The current version of podman on 20.04 is 3.1.0 which has some issues with storage. 
- https://github.com/containers/podman/issues/9936 
- https://github.com/redhat-actions/push-to-registry/issues/37#issuecomment-827549256

It looks like this was fixed in 3.1.1, and since then there is a new version 3.1.2

Please upgrade to the latest version 3.1.2

https://build.opensuse.org/package/binaries/devel:kubic:libcontainers:stable/podman/xUbuntu_20.04

it looks like https://github.com/actions/virtual-environments/blob/main/images/linux/scripts/installers/containers.sh has the install logic, and may just have to be re-run to pull the latest?

**Comment by miketimofeev** [comment]
Hi @tetchel!
We've already started image deployment with podman 3.1.2 onboard — https://github.com/actions/virtual-environments/blob/releases/ubuntu20/20210425/images/linux/Ubuntu2004-README.md
The propagation usually takes 3-4 days and is going to be finished on Thursday.

**Comment by miketimofeev** [comment]
@tetchel the new images with podman 3.1.2 have been deployed.
I'm going to close the issue. Please feel free to contact us if you have any concerns.
Thank you!
