### ISSUE TITLE
Update PIP please

### ISSUE THREAD

**Issue by josesimoes** [actions/virtual-environments#3285]
**Tool information**
- Tool name: PIP
- Update
- Desired version: 21.1
- Approximate size: 

**Area for Triage**:

**Question, Bug, or Feature?**:

Starting this week, I start seeing this error message on our pipelines:

`##[error]WARNING: You are using pip version 21.0.1; however, version 21.1 is available.`

Log [here](https://dev.azure.com/nanoframework/nf-interpreter/_build/results?buildId=17178&view=logs&j=ce7e3aa6-10f6-56a8-2e88-42daf53c0dba&t=b16fb403-5bbb-550a-ac3b-906e5530bf73).

**Virtual environments affected**
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Can this tool be installed during the build?**

**Tool installation time in runtime**

**Are you willing to submit a PR?**

**Comment by miketimofeev** [comment]
Hi @josesimoes!
The new image with pip 21.1 will be deployed today. However, this warning shouldn't fail the pipeline, it seems that you have a non-default task configuration. If it's necessary to have the task modified you can add the following command as a very first line of the step to make sure pip is updated:
`python -m pip install --upgrade pip`

**Comment by josesimoes** [comment]
Hey @miketimofeev !
Thank you very much for the prompt reply and, of course, for letting me know that the update will roll out today.

As for your suggestions on how to workaround this, I've added them to the yaml. Thanks for the review. 😃 👍🏻

**Comment by miketimofeev** [comment]
@josesimoes the windows images have been updated.
I'm going to close the issue. Please feel free to contact us if you have any concerns.
Thank you!
