### ISSUE TITLE
Apple silicon builds fail with GNU autoconf

### ISSUE THREAD

**Issue by grendello** [actions/virtual-environments#3288]
**Description**  
I'm building GNU Binutils on the `macOS 10.15` builder with a script that detects whether the installed toolchain is capable of building Apple silicon binaries:

```shell
local xcode_dir="$(xcode-select -p | head -1)"
if [ $? -ne 0 ]; then
	die Could not find Xcode
fi

local sdksettings_path="${xcode_dir}/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/SDKSettings.plist"
local architectures="$(plutil -extract SupportedTargets.macosx.Archs json -o - "${sdksettings_path}")"

if [ $? -ne 0 ]; then
	die Could not obtain the list of supported architectures from Xcode
fi

local flags=""
if echo ${architectures} | grep '"arm64"' > /dev/null 2>&1; then
	flags="-arch arm64"
fi
if echo ${architectures} | grep '"x86_64"' > /dev/null 2>&1; then
	flags="${flags} -arch x86_64"
fi

echo -n "${flags}"
```

The same detection approach is used elsewhere with CMake and it works fine, however with my binutils build, configure fails as follows:

```
configure:4378: /usr/bin/clang -O2 -m64 -arch arm64 -arch x86_64 -mmacosx-version-min=10.9  -O2 -m64 -arch arm64 -arch x86_64 -mmacosx-version-min=10.9 conftest.c  >&5
ld: warning: ignoring file /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/lib/libSystem.tbd, missing required architecture arm64 in file /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/lib/libSystem.tbd
ld: dynamic main executables must link with libSystem.dylib for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
configure:4382: $? = 1
configure:4420: result: no
configure: failed program was:
| /* confdefs.h */
| #define PACKAGE_NAME ""
| #define PACKAGE_TARNAME ""
| #define PACKAGE_VERSION ""
| #define PACKAGE_STRING ""
| #define PACKAGE_BUGREPORT ""
| #define PACKAGE_URL ""
| /* end confdefs.h.  */
| 
| int
| main ()
| {
| 
|   ;
|   return 0;
| }
configure:4425: error: in `/Users/runner/work/xamarin-android-binutils/xamarin-android-binutils/build/darwin-arm':
configure:4427: error: C compiler cannot create executables
```

The same build script works on my local machine (running macOS 11, but it shouldn't better I believe?)

**Area for Triage**:  
Xcode

**Question, Bug, or Feature?**:  
Bug

**Virtual environments affected**  
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [x] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Image version**
20210423.1

**Expected behavior**  
Apple silicon compilation should work, considering that XCode settings report support for both `x86_64` and `arm64` architectures

**Actual behavior**  
Build fails because of missing required `arm64` toolchain components

**Repro steps**  
https://github.com/grendello/xamarin-android-binutils 

Run the `build.sh` script passing it the version of Binutils to compile:

```shell
./build.sh 2.36.1
```

**Comment by LeonidLapshin** [comment]
Hey, @grendello !
We'll investigate this issue and return with details soon :)

**Comment by grendello** [comment]
@LeonidLapshin the build doesn't have anything related to Xamarin - it's pure C/C++ upstream GNU Binutils code that's being built for use with Xamarin.Android, but no Xamarin is used in the build process itself.

**Comment by dsame** [comment]
@grendello 
The root of the problem is the detection of supported architectures uses `${xcode_dir}/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk` which is link to `${xcode_dir}/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk` and thus `libSystem.tbd` has arm architectures targets

But compiler test uses `/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk`  (the difference in MacOS version) which has not arm targets.

I expect ./configure needs some extra hint to pick up the correct SDK and autotools teem can provide better support with this problem, but if you need more investigation from us please provide a link to the source codebase with the `./configure` script which causes the problem

**Comment by grendello** [comment]
@dsame thanks for your reply, the weird thing is that locally the same codebase and the exact build script work for me without any issues (I don't have gcc installed though, just Xcode). I suspected `gcc` being present in the path on the both could be a problem, that's why I forced `CC=/usr/bin/clang` and `CXX=/usr/bin/clang++` but maybe they aren't dispatchers to the current Xcode instance, but rather part of the command line tools package and I need to tell configure to use compilers from within Xcode.app. I'll investigate some more and update this issue with my findings. Can we keep it open for a while more?

**Comment by grendello** [comment]
OK, so this is a bit messy but I got it to work. 

Binutils didn't like cross-compiling (with `--host=arm64-apple-darwin`) prefix, but it does work when `--host=x86_64-apple-darwin` is used and two architectures are targeted. To get it to work, the following needed to be done:

```bash
function get_xcode_dir()
{
	local xcode_dir="$(xcode-select -p | head -1)"
	if [ $? -ne 0 ]; then
		die Could not find Xcode
	fi

	echo ${xcode_dir}
}

function configure_mac_compilers()
{
	if [ "${OS}" != "Darwin" ]; then
		return
	fi

	local xcode_dir="$(get_xcode_dir)"
	export CC="${xcode_dir}/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang"
	export CXX="${xcode_dir}/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++"
}

function detect_mac_arch_flags()
{
	if [ "${OS}" != "Darwin" ]; then
		return
	fi

	local xcode_dir="$(get_xcode_dir)"
	local sdksettings_path="${xcode_dir}/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/SDKSettings.plist"
	local architectures="$(plutil -extract SupportedTargets.macosx.Archs json -o - "${sdksettings_path}")"

	if [ $? -ne 0 ]; then
		die Could not obtain the list of supported architectures from Xcode
	fi

	local flags=""

	if echo ${architectures} | grep '"arm64"' > /dev/null 2>&1; then
		flags="-arch arm64"
	fi

	if echo ${architectures} | grep '"x86_64"' > /dev/null 2>&1; then
		flags="${flags} -arch x86_64"
	fi

	local sysroot=""$(xcrun --sdk macosx --show-sdk-path)""

	#
	# The `-isysroot` and `-isystem` flags are required for autoconf to detect system headers when cross-compiling (which
	# technically is the case in the presence of multiple `-arch` arguments)
	#
	# Even though the search paths are set up correctly, autoconf fails to detect `string.h` when checking if all ANSI C
	# headers are defined (even though it detects it shortly after, "standalone"), so we need to define `STDC_HEADERS` here.
	# Similarly, `fcntl.h` is not detected (only in libiberty), so we force it here.
	#
	echo -n "${flags} -mmacosx-version-min=${MACOS_TARGET} -isysroot ${sysroot} -isystem ${sysroot} -DSTDC_HEADERS=1 -DHAVE_FCNTL_H"
}
```

Autoconf in binutils insists on using `gcc` which on my local machine is a hardlink to `clang`, but on the build bots it probably picks up the brew-installed `gcc` in path, and that's why it probably failed to build. Forcing autoconf to use compilers from inside the Xcode bundle was the first step. Then `-isystem` and `-isysroot` had to be set correctly in order for autoconf tests to find the header files. The binaries built with the above work fine.

I'm going to close the issue as there's nothing to fix in the virtual image :) Thanks!
