### ISSUE TITLE
Add PHP 7.4 on macos using homebrew

### ISSUE THREAD

**Issue by shivammathur** [actions/virtual-environments#329]
**Tool information**
- Tool name: PHP
- Add or update? Add
- Desired version: 7.4
- Approximate size: 
- If this is an add request:
  - Brief description of tool: PHP is a widely used programming language
  - URL for tool's homepage: https://www.php.net/

**Area for Triage**: PHP

**Question, Bug, or Feature?**: Feature

**Virtual environments affected**
- [X] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Can this tool be installed during the build?**
Yes, but it takes around 3 to 5 minutes on each run, while it takes less than a minute on `ubuntu` and `windows`. 
Installing this on the runner will have following benefits
- The system PHP version on `macos` is `7.3.9` which is old and needs to be update to `7.4`.
- Anyone using PHP on `macos` would most likely be testing their PHP extension and would do that on different PHP versions. Once a PHP version is installed on the runner using homebrew, installing other versions will be faster as most dependencies are same between versions. 

**Are you willing to submit a PR?**

Yes, if possible, these are the commands to do this.
```bash
brew install php
brew link --force --overwrite php
```

**Comment by ruudboon** [comment]
Currently MacOS is our bottleneck during our tests. This could would definitely speed up the process.

**Comment by shivammathur** [comment]
@alepauly, @thejoebourneidentity Please add this to the project.

**Comment by miketimofeev** [comment]
Hi @shivammathur 
We have added brew PHP installation to macOS image generation. Image with PHP 7.4 will be rolled out next week. I will provide additional information when it's done.

**Comment by shivammathur** [comment]
@miketimofeev Thanks

**Comment by shivammathur** [comment]
@alepauly @miketimofeev 
Tested PHP 7.4.2 on `macOS` runner. Works perfectly. Also now it takes less than a minute to setup other PHP versions using brew.

**Comment by maxim-lobanov** [comment]
Closing since changes were deployed to all VMs
