### ISSUE TITLE
Add poetry as python package manager

### ISSUE THREAD

**Issue by omBratteng** [actions/virtual-environments#3292]
**Tool information**
- Tool name: poetry
- Tool license: MIT
- Add or update? Add
- Desired version: latest
- Approximate size: 73 MB installed
- If this is an add request:
  - Brief description of tool: A python package manager, I would say it's similar to npm/yarn
  - URL for tool's homepage: https://python-poetry.org/
  - Provide a basic test case to validate the tool's functionality: `poetry init` in an empty directory

**Area for Triage**: Python

**Question, Bug, or Feature?**: Feature

**Virtual environments affected**
- [ ] Ubuntu 16.04
- [x] Ubuntu 18.04
- [x] Ubuntu 20.04
- [x] macOS 10.15
- [x] macOS 11.0
- [x] Windows Server 2016 R2
- [x] Windows Server 2019

**Can this tool be installed during the build?**
Yes
```console
pipx install poetry
```

**Tool installation time in runtime**
Less than a minute

**Are you willing to submit a PR?**
Yes

**Comment by AlenaSviridenko** [comment]
Hi @omBratteng,
considering the pretty fast installation and a lot of available actions in marketplace to setup poetry, we'd rather not to preinstall it on the images. Please, use actions as it is the recommended way to interact with images. 
I am closing this issue and corresponding PR. Please, feel free to contact us in case of any questions. Thanks.

**Comment by omBratteng** [comment]
Hi @AlenaSviridenko, I think a lot of people would prefer it being officially supported in the image, and it would overall reduce the runtime duration of all workflows.

I would say the same as yarn, it's a fast install, yet included in the image.

**Comment by Kurt-von-Laven** [comment]
I second the value of including Poetry in the image. I suspect Poetry ([29k stars](https://github.com/python-poetry/poetry)) is significantly more popular than Miniconda ([conda has 6k stars](https://github.com/conda/conda)).
