### ISSUE TITLE
Update/Add VS Build Tools 2017 to `windows-2019`

### ISSUE THREAD

**Issue by hrueger** [actions/virtual-environments#3294]
**Tool information**
- Tool name: Visual Studio Build Tools 2017
- Tool license: ???
- Add or update? Add
- Desired version: 2017
- Approximate size: 
- If this is an add request:
  - Brief description of tool: It's an older version of VS Build Tools
  - URL for tool's homepage: docs.microsoft.com/en-us/visualstudio/productinfo/2017-redistribution-vs#vs2017-download

**Area for Triage**:
Windows / C/C++

**Question, Bug, or Feature?**:
Feature

**Virtual environments affected**
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [x] Windows Server 2019

**Can this tool be installed during the build?**
As far as I know, no.

**Tool installation time in runtime**
I don't know, probably as long as VS 2019 does.

**Are you willing to submit a PR?**
If there's docs on how to do this, sure.

This issue is already posted in #35 and I commented there (https://github.com/actions/virtual-environments/issues/35#issuecomment-826809306), however, I can't reopen this issue.

My needs are the following:
I'm trying to build https://github.com/stream-labs/obs-studio-node with a custom version of https://github.com/obsproject/obs-studio . `obs-studio-node` requires Visual Studio 2015 or 2017, so I went with the `windows-2016` actions environment. However, the installed version of the Windows 10 SDK is 10.0.14393.0. OBS on the other hand requires Windows 10 SDK 10.0.19041.0 or newer. 
I tried installing another version of the Windows 10 SDK with `choco install windows-sdk-10-version-2004-all` but although the installation process finishes successfully, OBS still only detects the old Windows 10 SDK.

So I want to move to the `windows-2019` environment but Visual Studio 2017 is not available there.

Any idea?

**Comment by hrueger** [comment]
Never mind, although the documentation of `obs-studio-node` states that it can't be built with Visual Studio 2019, it seems to work just fine.

**Comment by seladb** [comment]
Now that [`windows-2016`](https://github.blog/changelog/2021-10-19-github-actions-the-windows-2016-runner-image-will-be-removed-from-github-hosted-runners-on-march-15-2022/) is being deprecated, are there plans to add VS 2017 to the newer Windows images?

**Comment by Jaifroid** [comment]
I need to build an appxbundle from jsproj with VS 2017 build tools (VS 2019 doesn't support jsproj solution types). 

`windows-2016` is the only version that has VS 2017, but `windows-2016` is about to be removed. Is there a way to install it on VS 2019, or can it be built-in as an option that can be enabled instead of 2019 or 2022 in one of the later windows images, please?
