### ISSUE TITLE
macOS 11 env

### ISSUE THREAD

**Issue by saltzmanjoelh** [actions/virtual-environments#3297]
**Tool information**
- Tool name: macOS
- Add or update? Update
- Desired version: >= 11

**Question, Bug, or Feature?**:
It looks like the macOS build servers are running 10.15.7. There is a bug in the obj-c runtime that is fixed in new versions of the os:
https://bugs.swift.org/browse/SR-14013

Are you accepting requests for the macOS 11 env? If so, may I please get access to the private preview? 👏

Thanks!

**Virtual environments affected**
- [ x ] macOS 10.15
- [ ] macOS 11.0

**Comment by miketimofeev** [comment]
@saltzmanjoelh I'm going to close the issue as a duplicate. Please follow this thread about macOS-11
https://github.com/actions/virtual-environments/issues/2486
Thank you!
