### ISSUE TITLE
Inconsistent drive letter case for Windows

### ISSUE THREAD

**Issue by hudochenkov** [actions/virtual-environments#33]
**Describe the bug**
Lately Windows environment has random case drive letter for partition D:. Sometime it's `D:\`, and sometime it's `d:\`. In the same logs I see that Node.js installed on partition C: all the time (it's uppercased). This drive letter case difference makes our tests fail. Because Node.js for some reason always use uppercase drive letter in it's core modules.

**Virtual environments affected**
- [ ] macOS 10.14
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [x] Windows Server 2016 R2
- [x] Windows Server 2019

Not sure which one, we use `windows-latest`.

**Expected behavior**
Expecting that drive letter always would be uppercased. E. g. `D:`.

**Actual behavior**
I can't spot any pattern when this happen. If our build failed, I could restart it _n_ times and it would be still failing, but on _n + 1_ time it would succeed.

Here's our workflow: https://github.com/stylelint/stylelint/blob/e8bf1a1e47e02100c268bd903ab1e06195a41e8e/.github/workflows/nodejs.yml#L37-L62

Successful run, with drive letter `D:`: https://github.com/stylelint/stylelint/runs/253213464 for this commit https://github.com/stylelint/stylelint/commit/20a79549bba9e9650ff3e54458ac0098cd512be1

Failed run, with drive letter `d:`: https://github.com/stylelint/stylelint/runs/253528783 for this commit https://github.com/stylelint/stylelint/commit/febfbb6efbb754c86bd08953992662b05efe71f0

It's a two sequential commits 5 hours apart. Test fails because path Node.js provides (always uppercase drive letter) doesn't match real drive letter (sometimes lowercase).

**Comment by hudochenkov** [comment]
Current [workaround](https://github.com/stylelint/stylelint/blob/902cc9913097b1e9b6a0c8ca73412fd159d02d70/.github/workflows/nodejs.yml#L62-L68) we use:

```
cd .. && cd D:\a\stylelint\stylelint
```

Before running Node.js scripts.

**Comment by alepauly** [comment]
@hudochenkov It's not clear to me where the drive letter is coming from. Is the output from a script on the machine or your code?

**Comment by alepauly** [comment]
@hudochenkov This is fixed, should all be lower-case now. However, we don't make any guarantees for the casing in Windows path so it's probably a good idea to make your check more resilient in the Windows case?

**Comment by hudochenkov** [comment]
It's great to hear! But why it was decided to use lower-case over upper-case? Upper-case is the most common on Windows.

Also it might create more problem for Node.js tools, because of Node.js behavior. I understand that Node.js behavior out-of-scope for this repository. It's just a note keep in mind.

**Comment by hudochenkov** [comment]
There is one odd thing with having lower-cased `d:`. I just restarted failed build, so new environment probably has fix, @alepauly mentioned, in place. And this environment has two drives: `C:` (uppercased) and `d:` (lowercased). This was also happening before the fix.

<img width="682" alt="Screenshot 2019-10-23 at 23 38 29" src="https://user-images.githubusercontent.com/654597/67436426-a58ccb00-f5ee-11e9-948c-db70402c5d61.png">

Here's the build: https://github.com/stylelint/stylelint/pull/4372/checks?check_run_id=272347026

Logs attached: [logs_215.zip](https://github.com/actions/virtual-environments/files/3764608/logs_215.zip)
