### ISSUE TITLE
Ruby installation fails on Ubuntu 2004

### ISSUE THREAD

**Issue by AHuusom** [actions/virtual-environments#3303]
Ubuntu 2004 fails at the same spots when run from  2 different computers.
I cannot troubleshoot this as my linux skills aren't that great.

Bug

- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [X] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

2021/05/04 14:07:06 ui:     azure-arm: Installing ri documentation for jmespath-1.4.0
2021/05/04 14:07:06 ui:     azure-arm: Parsing documentation for aws-partitions-1.451.0
2021/05/04 14:07:06 ui:     azure-arm: Installing ri documentation for aws-partitions-1.451.0
2021/05/04 14:07:06 ui:     azure-arm: Parsing documentation for aws-eventstream-1.1.1
2021/05/04 14:07:06 ui:     azure-arm: Installing ri documentation for aws-eventstream-1.1.1
2021/05/04 14:07:06 ui:     azure-arm: Parsing documentation for aws-sigv4-1.2.3
2021/05/04 14:07:06 ui:     azure-arm: Installing ri documentation for aws-sigv4-1.2.3
2021/05/04 14:07:06 ui:     azure-arm: Parsing documentation for aws-sdk-core-3.114.0
2021/05/04 14:07:06 ui:     azure-arm: Installing ri documentation for aws-sdk-core-3.114.0
2021/05/04 14:07:06 ui:     azure-arm: Parsing documentation for aws-sdk-kms-1.43.0
2021/05/04 14:07:06 packer.exe plugin: [ERROR] Remote command exited with '1': sudo sh -c 'DEBIAN_FRONTEND='noninteractive' HELPER_SCRIPTS='/imagegeneration/helpers' INSTALLER_SCRIPT_FOLDER='/imagegeneration/installers' PACKER_BUILDER_TYPE='azure-arm' PACKER_BUILD_NAME='azure-arm'  /tmp/script_5240.sh'
2021/05/04 14:07:06 packer.exe plugin: [INFO] RPC endpoint: Communicator ended with: 1
2021/05/04 14:07:06 [INFO] 6032 bytes written for 'stderr'
2021/05/04 14:07:06 [INFO] 35783 bytes written for 'stdout'
2021/05/04 14:07:06 [INFO] RPC client: Communicator ended with: 1
2021/05/04 14:07:06 [INFO] RPC endpoint: Communicator ended with: 1
2021/05/04 14:07:06 packer.exe plugin: [INFO] 35783 bytes written for 'stdout'
2021/05/04 14:07:06 packer.exe plugin: [INFO] 6032 bytes written for 'stderr'
2021/05/04 14:07:06 ui:     azure-arm: Installing ri documentation for aws-sdk-kms-1.43.0
2021/05/04 14:07:06 packer.exe plugin: [INFO] RPC client: Communicator ended with: 1
2021/05/04 14:07:06 ui:     azure-arm: Parsing documentation for aws-sdk-s3-1.94.0
2021/05/04 14:07:06 ui:     azure-arm: Installing ri documentation for aws-sdk-s3-1.94.0
2021/05/04 14:07:06 ui:     azure-arm: Parsing documentation for fastlane-2.181.0
2021/05/04 14:07:06 ui:     azure-arm: Installing ri documentation for fastlane-2.181.0
2021/05/04 14:07:06 [INFO] (telemetry) ending shell
2021/05/04 14:07:06 ui error: ==> azure-arm: Script exited with non-zero exit status: 1.Allowed exit codes are: [0]
2021/05/04 14:07:06 ui: ==> azure-arm: Step "StepProvision" failed
2021/05/04 14:07:06 ui: ask: ==> azure-arm: [c] Clean up and exit, [a] abort without cleanup, or [r] retry step (build may fail even if retry succeeds)?
2021/05/04 14:15:22 ui: ==> azure-arm: Provisioning step had errors: Running the cleanup provisioner, if present...
2021/05/04 14:15:23 ui: ==> azure-arm:

**Comment by miketimofeev** [comment]
@AHuusom thanks for reporting! We've already started the investigation a few hours ago. It seems that the root cause is in the updated rdoc gem  (6.3.0->6.3.1), which is used for fastlane.

**Comment by miketimofeev** [comment]
The issue in the Fastlane repo
https://github.com/fastlane/fastlane/issues/18642

**Comment by miketimofeev** [comment]
@AHuusom we've made a workaround https://github.com/actions/virtual-environments/pull/3308. Please pull the latest main and try one more time.

**Comment by AHuusom** [comment]
Hi @miketimofeev.
This workaround seems to be working.
Thanks 👍
