### ISSUE TITLE
Ubuntu 2004 image build fails when install ruby with script ruby.sh

### ISSUE THREAD

**Issue by pamontag** [actions/virtual-environments#3307]
**Description**  
Ubuntu 2004 image build fails when install ruby.sh

**Area for Triage**:  
Ruby

**Question, Bug, or Feature?**:  
Cannot build the image with packer

**Virtual environments affected**  
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [X] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Image version**
Ubuntu 2004

**Expected behavior**  
Packer installation ends with success

**Actual behavior**  
Packer installation shows those errors when install gem dependencies of ruby. Image build is canceled

Raw logs are here:
[rawlog.txt](https://github.com/actions/virtual-environments/files/6421887/rawlog.txt)

Here the errors during the execution of ruby.sh
azure-arm: Building native extensions. This could take a while...
==> azure-arm: ERROR:  Error installing readline-ext:
==> azure-arm: 	ERROR: Failed to build gem native extension.
==> azure-arm:
==> azure-arm:     current directory: /var/lib/gems/2.7.0/gems/readline-ext-0.1.1/ext/readline
==> azure-arm: /usr/bin/ruby2.7 -I /usr/lib/ruby/2.7.0 -r ./siteconf20210504-187946-lnaij1.rb extconf.rb
==> azure-arm: checking for tgetnum() in -lncurses... yes
==> azure-arm: checking for readline/readline.h... no
==> azure-arm: checking for editline/readline.h... no
==> azure-arm: *** extconf.rb failed ***
==> azure-arm: Could not create Makefile due to some reason, probably lack of necessary
==> azure-arm: libraries and/or headers.  Check the mkmf.log file for more details.  You may
==> azure-arm: need configuration options.

azure-arm: Successfully installed google-apis-storage_v1-0.3.0
    azure-arm: Building native extensions. This could take a while...
==> azure-arm: invalid options: -SHN
==> azure-arm: (invalid options are ignored)
==> azure-arm: /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require': cannot load such file -- rdoc/markup/table (LoadError)

    azure-arm: Parsing documentation for aws-sdk-kms-1.43.0
    azure-arm: Installing ri documentation for aws-sdk-kms-1.43.0
    azure-arm: Parsing documentation for aws-sdk-s3-1.94.0
    azure-arm: Installing ri documentation for aws-sdk-s3-1.94.0
    azure-arm: Parsing documentation for fastlane-2.181.0
    azure-arm: Installing ri documentation for fastlane-2.181.0
==> azure-arm: Provisioning step had errors: Running the cleanup provisioner, if present...

**Repro steps**  
Launch ./images.CI/linux-and-win/build-image.ps1 with parameters
-ResourcesNamePrefix 1_1 `

Other parameters depends by environment
                        -ClientId $(CLIENT_ID) `
                        -ClientSecret $(CLIENT_SECRET) `
                        -TemplatePath $(TemplatePath) `
                        -ResourceGroup $(AZURE_RESOURCE_GROUP) `
                        -StorageAccount $(AZURE_STORAGE_ACCOUNT) `
                        -SubscriptionId $(AZURE_SUBSCRIPTION) `
                        -TenantId $(AZURE_TENANT) `
                        -Location $(AZURE_LOCATION) `
                        -VirtualNetworkName $(BUILD_AGENT_VNET_NAME) `
                        -VirtualNetworkRG $(BUILD_AGENT_VNET_RESOURCE_GROUP) `
                        -VirtualNetworkSubnet $(BUILD_AGENT_SUBNET_NAME)

**Comment by miketimofeev** [comment]
Duplicate https://github.com/actions/virtual-environments/issues/3303
