### ISSUE TITLE
Jarsinger.exe in all current builds of Adopt OpenJDK fail to verify cerificates.

### ISSUE THREAD

**Issue by BrianMouncer** [actions/virtual-environments#3313]
**Description**  
I believe the 4/25 image update changed the default JDK or updated it to a newer minor release.
This caused all hosted builds that verify the signatures on JAR and ARR files to start failing.

See OpenJDK issue report for more details.
https://github.com/adoptium/adoptium-support/issues/302

**Area for Triage**:  
Java OpenJDK update breaks certificate validation on JAR and ARR files.

**Question, Bug, or Feature?**:  
Bug

**Virtual environments affected**  
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [X] Windows Server 2019

**Image version**
Environment: windows-2019
Version: 20210425.1

**Expected behavior**  
"jarsigner.exe --verify --strict my.jar" should pass.

**Actual behavior**  
Jarsigner.exe has a bug in current version, causing signature verification for our Microsoft cert chain to fail.

**Repro steps**  
use the default OpenJDK8 version of the jarsigner.exe tool
run "jarsigner.exe --verify --strict my.jar"
See that it fails with error about invalid certificate chain.

Download and install previous release of OpenJDK8 from adopt and run the same command line, see that verification passes with the old version but not the current version.

**Comment by miketimofeev** [comment]
Hi @BrianMouncer!
Thanks for reporting this. The default java version was changed from 8.0.282+8 to 8.0.292+10 in the 20210425.1 image.
We recommend using [setup-java](https://github.com/actions/setup-java) action to stick to any version you prefer and to be on the safe side across image updates.

**Comment by BrianMouncer** [comment]
[setup-java](https://github.com/actions/setup-java) action just didn't work in our ADO Git pipelines.

I was able to use [JavaToolInstaller@0](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/tool/java-tool-installer?view=azure-devops) to install the previous version of Open JDK. The down side is that you no longer have the previous JDK version staged on the images, so I had to download the Open JDK zip file and host it on our own Azure Blob storage.  Note: there is also a bug in the JavaToolInstaller path parsing code, which causes it to build a bad path to zip files in sub folders, so to use this I had to store the JDK zip file in the root of our blog storage container, rather than in a subfolder.

It would be very helpfull if you would include the previous version of JDK, so users can just use JavaToolInstaller with the "jdkSourceOption: 'PreInstalled'" option.

**Comment by MaksimZhukov** [comment]
Hello @BrianMouncer!
We pre-install tools on images in accordance with the [Software and images support policy](https://github.com/actions/virtual-environments/blob/main/docs/software-and-images-guidelines.md#software-and-images-support-policy) guide. The following versions of Java are available on Windows images: `8.x`, `11.x`, `13.x` ([Windows2016-Readme](https://github.com/actions/virtual-environments/blob/main/images/win/Windows2016-Readme.md#java) and [Windows2019-Readme](https://github.com/actions/virtual-environments/blob/main/images/win/Windows2019-Readme.md#java)). If any other Java version is required, please use the [JavaToolInstaller@0](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/tool/java-tool-installer?view=azure-devops) ADO task. Feel free to post an issue in the [azure-pipelines-tasks](https://github.com/Microsoft/azure-pipelines-tasks) repository if you notice a bug in the `JavaToolInstaller` task.

I'm going to close this issue. Please let us know if you have any questions. Thank you!
