### ISSUE TITLE
Problem installing libzmq3-dev

### ISSUE THREAD

**Issue by jwillemsen** [actions/virtual-environments#3317]
**Description**  
On ubuntu-18.04 we run the following commands
```
sudo apt-get --yes update
sudo apt-get --yes install libxerces-c-dev libssl-dev libzmq3-dev g++-6
```
Which started to fail after May 2nd 2021 with

```
Reading state information...
libssl-dev is already the newest version (1.1.1-1ubuntu2.1~18.04.9).
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libzmq3-dev : Depends: libzmq5 (= 4.2.5-1ubuntu0.2) but 4.3.1-5+ubuntu18.04.1+deb.sury.org+1 is to be installed
E: Unable to correct problems, you have held broken packages.
Error: Process completed with exit code 100.
```

See https://github.com/RemedyIT/axcioma/runs/2509593210?check_suite_focus=true

**Area for Triage**:  
Packages

**Question, Bug, or Feature?**:  
Bug

**Virtual environments affected**  
- [ ] Ubuntu 16.04
- [X] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Image version**
Version: 20210504.1

**Expected behavior**  

```
libssl-dev is already the newest version (1.1.1-1ubuntu2.1~18.04.9).
The following additional packages will be installed:
  comerr-dev cpp-6 gcc-6 gcc-6-base krb5-multidev libasan3 libgcc-6-dev
  libgssrpc4 libkadm5clnt-mit11 libkadm5srv-mit11 libkdb5-9 libkrb5-dev
  libnorm-dev libpgm-dev libsodium-dev libsodium23 libstdc++-6-dev
  libxerces-c3.2
Suggested packages:
  doc-base gcc-6-locales g++-6-multilib gcc-6-doc libstdc++6-6-dbg
  gcc-6-multilib libgcc1-dbg libgomp1-dbg libitm1-dbg libatomic1-dbg
  libasan3-dbg liblsan0-dbg libtsan0-dbg libubsan0-dbg libcilkrts5-dbg
  libmpx2-dbg libquadmath0-dbg krb5-doc krb5-user libnorm-doc libstdc++-6-doc
  libxerces-c-doc
The following NEW packages will be installed:
  comerr-dev cpp-6 g++-6 gcc-6 gcc-6-base krb5-multidev libasan3 libgcc-6-dev
  libgssrpc4 libkadm5clnt-mit11 libkadm5srv-mit11 libkdb5-9 libkrb5-dev
  libnorm-dev libpgm-dev libsodium-dev libstdc++-6-dev libxerces-c-dev
  libxerces-c3.2 libzmq3-dev
The following packages will be upgraded:
  libsodium23
1 upgraded, 20 newly installed, 0 to remove and 222 not upgraded.
```

**Actual behavior**  

```
Reading state information...
libssl-dev is already the newest version (1.1.1-1ubuntu2.1~18.04.9).
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libzmq3-dev : Depends: libzmq5 (= 4.2.5-1ubuntu0.2) but 4.3.1-5+ubuntu18.04.1+deb.sury.org+1 is to be installed
E: Unable to correct problems, you have held broken packages.
Error: Process completed with exit code 100.
```

**Repro steps**  

See https://github.com/RemedyIT/axcioma/blob/master/.github/workflows/linux.yml

**Comment by miketimofeev** [comment]
Hi @jwillemsen!
We will take a look

**Comment by miketimofeev** [comment]
@jwillemsen could you please add the following workaround before installing the packages until we've found a root cause
`sudo apt-get remove libzmq5`

**Comment by jwillemsen** [comment]
Created https://github.com/RemedyIT/axcioma/pull/89 to try this workaround

**Comment by jwillemsen** [comment]
The jobs are passed the `apt-get install` so the workaround works, waiting for the CI jobs to finish before I merge them to master, thanks @miketimofeev

**Comment by al-cheb** [comment]
@jameswhite,
During Ubuntu image generation process  we install PHP using 3rd-party repository `ppa:ondrej/php`.  At the end of the process this repo is deleted(in scope of the https://github.com/actions/virtual-environments/pull/3272 PR) which why we get the error `libzmq3-dev : Depends: libzmq5 (= 4.2.5-1ubuntu0.2) but 4.3.1-5+ubuntu18.04.1+deb.sury.org+1 is to be installed`:

```
$ apt-cache madison libzmq5 libzmq3-dev
libzmq5 | 4.3.1-5+ubuntu18.04.1+deb.sury.org+1 | http://ppa.launchpad.net/ondrej/php/ubuntu bionic/main amd64 Packages
$ apt-cache madison libzmq3-dev
libzmq3-dev | 4.3.1-5+ubuntu18.04.1+deb.sury.org+1 | http://ppa.launchpad.net/ondrej/php/ubuntu bionic/main amd64 Packages
``` 

Workarounds:
1. Remove `libzmq5`
`sudo apt-get remove libzmq5`
2. Add `ppa:ondrej/php` repo
`sudo apt-add-repository "ppa:ondrej/php" -y`


E.g.:
```
    runs-on: ubuntu-18.04
    steps:
           - name: install zmq5
             run: |
                sudo apt-add-repository "ppa:ondrej/php" -y
                sudo apt-get --yes update
                sudo apt-get --yes install libxerces-c-dev libssl-dev libzmq3-dev g++-6
```
![image](https://user-images.githubusercontent.com/47745270/117265380-d93fe680-ae5c-11eb-82d3-d504147ba02e.png)

**Comment by ferdnyc** [comment]
@al-cheb In my PPA runs from before 2021-05-04 I see libzmq3-dev being pulled in from the ondrej/php PPA, just as you say, so apparently the PPA was previously allowed to remain in the image configs. Why was deletion of that PPA added to the image build, presumably recently, and can it be reversed? 

(Deleting a PPA from which packages are currently installed, though presumably well-intentioned and meant to avoid "polluting" the image configs, is just not a good idea — it leads to issues exactly like this. All things considered,  a more "polluted" image with a complete set of PPAs configured to satisfy all dependencies is preferable.)

**Comment by al-cheb** [comment]
> @al-cheb In my PPA runs from before 2021-05-04 I see libzmq3-dev being pulled in from the ondrej/php PPA, just as you say, so apparently the PPA was previously allowed to remain in the image configs. Why was deletion of that PPA added to the image build, presumably recently, and can it be reversed?
> 
> (Deleting a PPA from which packages are currently installed, though presumably well-intentioned and meant to avoid "polluting" the image configs, is just not a good idea — it leads to issues exactly like this. All things considered, a more "polluted" image with a complete set of PPAs configured to satisfy all dependencies is preferable.)

We have intentionally deleted this repository  - https://github.com/actions/virtual-environments/issues/2951

**Comment by al-cheb** [comment]
PR reverted - https://github.com/actions/virtual-environments/pull/3340

**Comment by al-cheb** [comment]
New  Ubuntu 18.04 image with `http://ppa.launchpad.net/ondrej/php/ubuntu` repo has been deployed.

**Comment by jwillemsen** [comment]
Problem is back but now on ubuntu 16.04

```
The following packages have unmet dependencies:
 libzmq3-dev : Depends: libzmq5 (= 4.1.4-7ubuntu0.1) but 4.3.1-5+ubuntu16.04.1+deb.sury.org+1 is to be installed
E: Unable to correct problems, you have held broken packages.
```

```
Current runner version: '2.278.0'
Operating System
  Ubuntu
  16.04.7
  LTS
Virtual Environment
  Environment: ubuntu-16.04
  Version: 20210531.0
  Included Software: https://github.com/actions/virtual-environments/blob/ubuntu16/20210531.0/images/linux/Ubuntu1604-README.md
  Image Release: https://github.com/actions/virtual-environments/releases/tag/ubuntu16%2F20210531.0
```
