### ISSUE TITLE
Add vhci-hcd kernel module

### ISSUE THREAD

**Issue by emlun** [actions/virtual-environments#332]
**Tool information**
- Tool name: Linux kernel module `vhci-hcd` (USB Virtual Host Controller Interface)
- Add or update? Add
- Desired version: any/latest
- Approximate size:
- If this is an add request:
  - Brief description of tool: The `vhci-hcd` kernel module is required for the `usbip` client.
  - URL for tool's homepage: http://vhci.a-singer.de/

**Area for Triage**:
Servers

**Question, Bug, or Feature?**:
Feature

**Virtual environments affected**
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [x] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Can this tool be installed during the build?**
No: `modprobe vhci-hcd` is unable to find the module.

**Are you willing to submit a PR?**
No, I lack the necessary expertise (but would be willing if I had it).

**Comment by thejoebourneidentity** [comment]
Thanks for your suggestion 🙏. Considering the current compatibility issues, and maintenance concerns, this is not something we will add to the image at this time.

**Comment by emlun** [comment]
Ok, thanks for considering!
