### ISSUE TITLE
Update/Add CMake 3.18.1 for Android build

### ISSUE THREAD

**Issue by ggfan** [actions/virtual-environments#3321]
**Tool information**
- Tool name: CMake 3.18.1
- Tool license: should be the same as previous CMakes. 
- Add or update? Add, please also keep the existing one like 3.10.2 version
- Desired version: 3.18.1
- Approximate size: ~50MB
  - Brief description of tool: CMake 3.18.1 is the default version for Android Studio 4.2.0(Android Gradle Plugin version 4.2.0)
  - URL for tool's homepage: echo y | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "cmake;3.18.1"
  - Provide a basic test case to validate the tool's functionality: building NDK samples seems ok, do not see any problems.

**Area for Triage**:

CMake 3.18.1 is in stable channel now,  it is the default version for Android Studio 4.2. 

**Question, Bug, or Feature?**:
Feature

**Virtual environments affected**
- [x ] Ubuntu 16.04
- [ x] Ubuntu 18.04
- [ x] Ubuntu 20.04
- [ x] macOS 10.15
- [ x] macOS 11.0
- [ x] Windows Server 2016 R2
- [ x] Windows Server 2019
may you please include this version of CMake to be part of Android build environment?

**Can this tool be installed during the build?**
yeah, with sdkmanager:
`echo y | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "cmake;3.18.1"`

**Tool installation time in runtime**
less than a minutes
**Are you willing to submit a PR?**

probably not, I am not familiar with action environment.

thank you

**Comment by miketimofeev** [comment]
@ggfan we've added CMake 3.18 to all the images. They will be deployed next week.

**Comment by ggfan** [comment]
thank you!

**Comment by miketimofeev** [comment]
@ggfan we'll leave this issue open until the images are deployed if you don't mind

**Comment by miketimofeev** [comment]
@ggfan we've deployed all the images with CMake 3.18.1 on board.
I'm going to close the issue. Please feel free to contact us if you have any concerns.
Thank you!
