### ISSUE TITLE
MySQL Testcontainers stopped working correctly after 2021-05-04

### ISSUE THREAD

**Issue by trajano** [actions/virtual-environments#3325]
**Description**  

I noticed that there's a change to the Ubuntu images that got rolled out starting 2021-05-04.  I had a builds that were working correctly before that suddenly stopped functioning due to issues with TestContainers.  I haven't done an MVCE as of yet but it appears the tests that are failing fall on those which use TestContainers.

**Area for Triage**:  

Java

**Question, Bug, or Feature?**:  

Bug

**Virtual environments affected**  
- [ ] Ubuntu 16.04
- [X] Ubuntu 18.04
- [X] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Image version**

Image version where you are experiencing the issue.

**Expected behavior**  
A description of what you expected to happen.

**Actual behavior**  
A description of what is actually happening.

**Repro steps**  
A description with steps to reproduce the issue. If your have a public example or repo to share,
please provide the link.

1. Step 1
2. Step 2

**Comment by miketimofeev** [comment]
Hi @trajano!
Could you please provide the exact error you're observing and minimal repro steps?

**Comment by trajano** [comment]
Yup will do, still narrowing it down.  It worked on a smaller Gradle project so I am still trying to diaganose it.

**Comment by trajano** [comment]
I narrowed it down further and have a workaround.  At least so far it's working, I am going to test some more.

The connection to MySQL appears to *require* the use SSL.  I added `useSSL=false` in the connection properties.

**Comment by trajano** [comment]
Confirmed, the general fix for this at least on my projects was to set `useSSL` to `false`

        @Bean
        public DataSource dataSource() {

            final DriverManagerDataSource dataSource = new DriverManagerDataSource();
            dataSource.setUrl(mysql.getJdbcUrl());
            dataSource.setUsername(mysql.getUsername());
            dataSource.setPassword(mysql.getPassword());
            final Properties connectionProperties = new Properties();
            connectionProperties.setProperty("useSSL", "false"); // add this
            dataSource.setConnectionProperties(connectionProperties);
            return dataSource;

        }

Also using 20.04 makes things run slower or run out of disk space.  But switching to 18.04 (which is what I originally had) remains working.

**Comment by rnorth** [comment]
@trajano just FYI, I think this is to do with removal of TLS 1.0/1.1 support in the latest patch update of the OpenJDK. This seems to impact connections to older MySQL docker images. Please follow the issue Sergei linked above.

Downgrading your test environment may not be the best solution, since this problem may impact your ability to connect to real MySQL servers in prod with updated JDKs.

**Comment by trajano** [comment]
Thanks for the tip @rnorth  we actually don't use SSL when we run our test containers when doing the Integration Tests since we do not want to manage certificates, also our tests are slow enough as it is. 

Right now we're dealing with the fact that after the changes to the virtual environments and the fixes to explicitly state we don't use SSL for MySQL connections the hosted agent just stops responding after 40 minutes.

**Comment by rnorth** [comment]
> the hosted agent just stops responding after 40 minutes

Tangential to the original issue, but: yikes! I hope you're able to get things working.
