### ISSUE TITLE
IMAPS connection failing on windows-latest image

### ISSUE THREAD

**Issue by mblaschak-clinone** [actions/virtual-environments#3331]
**Description**  
Issue connecting to imaps gmail server via java selenium project.
Issue may have started as early as April 25th, but have only confirmed it as of today (May 6th)

**Area for Triage**:  
Java, Testing and code coverage

**Question, Bug, or Feature?**:  
Bug

**Virtual environments affected**  
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [x] Windows Server 2019

**Image version**
Environment: windows-2019
Version: 20210425.1

**Expected behavior**  
Java Selenium project using javax.mail should be able to successfully connect to gmail imap store

**Actual behavior**  
Connection is failing with the message: "No appropriate protocol (protocol is disabled or cipher suites are inappropriate)".
Same execution on a local environment is able to connect without issue.

**Repro steps**  
1. Snippet to set up connection to gmail store:
```
private synchronized void connect() {
    String host = "imap.gmail.com";
    String user = "<gmail-username-here>";
    String password = "<gmail-password-here>";
    String protocol = "imaps";
    int port = 993;

    Properties props = new Properties();
      props.setProperty("mail.mime.multipart.ignoreexistingboundaryparameter", "true");
      props.setProperty("mail.smtp.connectiontimeout", "150000");
      props.setProperty("mail.smtp.timeout", "150000");
      props.setProperty("mail.smtp.writetimeout", "150000");
      props.setProperty("mail.store.protocol", protocol);
      props.setProperty("mail.imap.user", user);
      props.setProperty("mail.imaps.starttls.enable", "true");
      props.setProperty("mail.imap.ssl.enable", "true");

    Session session = Session.getInstance(props);
    session.setDebug(true);
    if (store == null) {
      try {
        Logger.logInfo("Get GMail Store");
        store = session.getStore(protocol);
      } catch (NoSuchProviderException e) {
        Logger.logWarning("Getting Store is failed: " + e.getMessage());
      }
    } else {
      Logger.logWarning("Store is already defined");
    }
    if (store != null) {
      try {
        Logger.logInfo("connect to GMail store with Host:"+host+" port:"+port+" user:"+user+" password:"+password+" and Store URL:"+store.getURLName());
        store.connect(host, port, user, password);
      } catch (MessagingException e) {
        Logger.logWarning("Store connection is failed: " + e.getMessage());
      }
        Logger.logInfo("imapStore ---" + store);
    }
  }
```
2. Local execution should successfully connect (see image_1)
![image_1](https://user-images.githubusercontent.com/77249642/117370409-5a66a000-ae94-11eb-842c-c80381e08c98.png)

3. Execution in hosted agent will fail (see image_2)
![image_2](https://user-images.githubusercontent.com/77249642/117370497-779b6e80-ae94-11eb-9825-8905c7ae8266.png)

**Comment by miketimofeev** [comment]
Hi @mblaschak-clinone!
We will take a look at this soon.

**Comment by Darleev** [comment]
Hello @mblaschak-clinone,
Could you please add one more property to the code and test it?
props.setProperty("mail.smtp.ssl.trust", "smtp.gmail.com");
In order to speed up the investigation, It would be great if you provide some sample repo where it is possible to reproduce the issue or step-by-step instructions on how to execute it in runtime.
We are looking forward to your reply.

**Comment by mblaschak-clinone** [comment]
Hi @Darleev, apologies for the delay.

I've created [this repository](https://github.com/mblaschak-clinone/imapsdemo) with an azure-pipelines.yaml to recreate the issue within the context of a junit test executed via maven.

Adding the property you suggested didn't seem to change anything.

**Comment by Darleev** [comment]
@mblaschak-clinone First of all thank you for the repo provided. 
It seems in the latest java version TLS 1.0 and 1.1 have been disabled and that's the issue appears:

```
What’s New
TLS 1.0 and 1.1 is turned off

TLS 1.0 and 1.1 are turned off in the PSU builds in this release. This change affects the following Azul Zulu versions:

16.30 (CA and SA)
15.32.15 (CA), 15.32.16 (SA)
13.40.15 (CA), 13.40.16 (SA)
11.48.21 (CA), 11.48.22 (SA)
8.54.0.21 (CA), 8.54.0.22 (SA)
7.46.0.11 (CA), 7.46.0.12 (SA)
This may cause incompatibility issues if your application uses TLS 1.0/1.1.
```

And most probably to fix the issue, it is required to enforce Java to use TLS v1.2.
I'm trying to do this in my internal project, but with no luck. Could you please try from your side as well?

**Comment by mblaschak-clinone** [comment]
Hi @Darleev,

Thanks much for the insight! I wasn't able to figure out exactly how to enforce TLS v1.2, but by changing the javax.mail dependency from 

`<dependency>
    <groupId>javax.mail</groupId>
    <artifactId>javax.mail-api</artifactId>
    <version>1.6.2</version>
</dependency>`

to

`<dependency>
    <groupId>com.sun.mail</groupId>
    <artifactId>javax.mail</artifactId>
    <version>1.6.2</version>
</dependency>`

I think we essentially achieved that. We'll keep in mind the latest TLS minimum for the future if connection issues present themselves again.

Thanks for your help!
