### ISSUE TITLE
So I think the issue is from this commit #3247 that changes the maven version from 3.6.3 to 3.8.1. Is there a way to temporary downgrade back to 3.6.3

### ISSUE THREAD

**Issue by thierno22** [actions/virtual-environments#3332]
So I think the issue is from this commit #3247 that changes the maven version from 3.6.3 to 3.8.1. Is there a way to temporary downgrade back to 3.6.3

_Originally posted by @ldttmt in https://github.com/actions/virtual-environments/issues/3327#issuecomment-833128621_

**Comment by miketimofeev** [comment]
@thierno22 please follow these bash steps to downgrade maven
```
curl -sL https://www-eu.apache.org/dist/maven/maven-3/3.6.3/binaries/apache-maven-3.6.3-bin.zip -o maven.zip
unzip -qq -d /usr/share maven.zip
rm maven.zip
sudo ln -sf /usr/share/apache-maven-3.6.3/bin/mvn /usr/bin/mvn
```
