### ISSUE TITLE
Latest change to ondrej php ppa broke libzip-dev installs

### ISSUE THREAD

**Issue by vadi2** [actions/virtual-environments#3335]
**Description**  
The [recent Ubuntu 16.04 update](https://github.com/actions/virtual-environments/releases/tag/ubuntu16%2F20210504.1) which switched to the ondrej broke `libzip-dev` installs:

```
The following packages have unmet dependencies:
 libzip-dev : Depends: libzip4 (= 1.0.1-0ubuntu1) but 1.7.3-1+ubuntu16.04.1+deb.sury.org+2 is to be installed
E: Unable to correct problems, you have held broken packages.
```

**Area for Triage**:  
Area: C/C++

**Question, Bug, or Feature?**:  

**Virtual environments affected**  
- [x] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Image version**
20210504.1

**Expected behavior**  
`libzip-dev` installs fine as it did previously.

**Actual behavior**  
It fails to install due to conflicts with libzip that's included in the new PPA.

**Repro steps**  
https://github.com/Mudlet/Mudlet/blob/development/.github/workflows/build-mudlet.yml#L148

**Comment by al-cheb** [comment]
Hi, @vadi2 
We decided to cut down the count of apt sources - https://github.com/actions/virtual-environments/issues/2951 and provide these changes in doc files.

Please update your pipeline:
```
Add ppa:ondrej/php repo
sudo apt-add-repository "ppa:ondrej/php" -y

```

**Comment by vadi2** [comment]
Sorry, but I don't need the ondrej repository, I don't use php and I was happy installing `libzip-dev` from the Xenial sources. From what I understand it is your addition of the PPA to default builds (see https://github.com/actions/virtual-environments/commit/09c30790e1eb1362dbeb967dfc4944094693fbb0#diff-13c32e50a93846c2ce39a041f2893dad4ddf1263edaac708ffff365379473d21R115 where it is now listed) broke the environment.

Could you double-check?

**Comment by al-cheb** [comment]
> Sorry, but I don't need the ondrej repository, I don't use php and I was happy installing `libzip-dev` from the Xenial sources. From what I understand it is your addition of the PPA to default builds (see [09c3079#diff-13c32e50a93846c2ce39a041f2893dad4ddf1263edaac708ffff365379473d21R115](https://github.com/actions/virtual-environments/commit/09c30790e1eb1362dbeb967dfc4944094693fbb0#diff-13c32e50a93846c2ce39a041f2893dad4ddf1263edaac708ffff365379473d21R115) where it is now listed) broke the environment.
> 
> Could you double-check?

Some packages depend on this "ppa:ondrej/php" repo.
![image](https://user-images.githubusercontent.com/47745270/117406855-58452580-af16-11eb-8ea8-0347b65ed9ba.png)

**Comment by vadi2** [comment]
Thanks, that worked :+1:

**Comment by Technius** [comment]
I'm seeing this issue occur on Ubuntu 18.04 images too; Ubuntu 20.04 is not affected. I don't think that PPA workaround is going to work, because it's going to run into #1084 which I reported a year ago.

Azure Pipeline logs: https://dev.azure.com/xournalpp/xournalpp/_build/results?buildId=13131&view=logs&j=dcc56f4b-525b-5250-e214-a3048e57065b&t=2bc5dade-12d9-50c6-3ff5-343c1f268ba1

Package install commands: https://github.com/xournalpp/xournalpp/blob/master/azure-pipelines/steps/install_deps_ubuntu.yml
