### ISSUE TITLE
[Ubuntu] .NET SDK pre-installation policy will be changed on June 14

### ISSUE THREAD

**Issue by MaksimZhukov** [actions/virtual-environments#3338]
**Breaking changes**

The .NET versions maintenance strategy will be changed on Ubuntu images. Currently, we install all available and supported versions of .NET SDK (2.1.x, 3.1.x, 5.0.x). This approach will be changed in favor of installing the latest patch version for every feature version.

What does it mean?

The SDK version is composed of the following parts: `x.y.znn`. `z` is the feature version and `nn` is the patch version. For example, for version `2.1.302`, feature version is `3` and `02` is the patch version.

According to the new approach we will only install the latest patch version for every feature version, i.e. only `2.1.302` will be installed for `2.1.3x`, only `2.1.403` for `2.1.4x` and etc. All versions of the .NET SDK that are not the latest patch versions will be removed from Ubuntu images on June 14

**Target date**

Image deployment will start June 14 and will take 3-4 days.

**The motivation for the changes**

We are reconsidering the .NET SDK preinstallation policy on Ubuntu images to provide more free space for customers usage and new tools requests.

For more information related to software and images support policy please see the [Software and image guidelines](https://github.com/actions/virtual-environments/blob/main/docs/software-and-images-guidelines.md) doc.

**Possible impact**

If you use the [actions/setup-dotnet](https://github.com/actions/setup-dotnet) action or the [UseDotNet](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/tool/dotnet-core-tool-installer?view=azure-devops) task, you will not be affected. Also, if you don't use the `global.json` file to specify .NET SDK version, there will be no change for you.

If you use the `global.json` file, your build will be affected in the following cases:
1) Your build will fail, if the `global.json` file contains the `rollForward: disable` property and SDK version that is not the latest patch version, for example:
```
{
  "sdk": {
    "version": "3.1.100",
    "rollForward": "disable"
  }
}
```
2) .NET SDK version will be automatically changed to the latest patch if the `global.json` file contains the `rollForward: patch` property and SDK version that is not the latest patch version, for example:
```
{
  "sdk": {
    "version": "3.1.100",
    "rollForward": "patch"
  }
}
```

If the `rollForward` field is not specified in your `global.json` file, there will be no change for you. The latest installed patch level is used.

Please visit the [global.json overview](https://docs.microsoft.com/en-us/dotnet/core/tools/global-json?tabs=netcore3x) doc to learn more about the global.json schema and matching rules.

**Virtual environments affected**

- [x] Ubuntu 16.04
- [x] Ubuntu 18.04
- [x] Ubuntu 20.04
- [ ] macOS 10.13
- [ ] macOS 10.14
- [ ] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Mitigation ways**

If you need to use the exact .NET SDK version that is not the latest patch, please consider using actions to install it on-flight:

1) GitHub Actions: [actions/setup-dotnet](https://github.com/actions/setup-dotnet) action
```yaml
steps:
- uses: actions/checkout@main
- uses: actions/setup-dotnet@v1
  with:
    dotnet-version: '<dotnet version>'
- run: dotnet build <my project>
```

2) Azure DevOps: [UseDotNet](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/tool/dotnet-core-tool-installer?view=azure-devops) task
```yaml
steps:
- task: UseDotNet@2
  displayName: 'Use .NET Core sdk'
  inputs:
    version: <dotnet version>
```

**Comment by dsame** [comment]
The PR merged and will be available on the next image roll out

**Comment by miketimofeev** [comment]
The images with reduced .NET packages count were deployed
