### ISSUE TITLE
Issues running puppeteer@2.1.0 (chromium 80) on a Windows container

### ISSUE THREAD

**Issue by chrispat** [actions/virtual-environments#334]
**Describe the bug**
Project: https://github.com/wixplosives/mocha-pup

When upgrading from puppeteer@2.0.0 (chromium 79) to puppeteer@2.1.0 (chromium 80), the Windows containers get stuck during `yarn test` (which executes headless Chrome several times):

https://github.com/wixplosives/mocha-pup/pull/1/checks?check_run_id=412835391

I tried reproducing on a local Windows 10 machine, but the tests consistently passed.

I wonder whether this is because GitHub Actions use Windows Server 2019? see: https://docs.microsoft.com/en-us/office365/troubleshoot/miscellaneous/chrome-behavior-affects-applic...

More specifically: is KB4534273 installed?

From https://github.community/t5/forums/replypage/board-id/actions/message-id/5792

**Area for Triage**: 

**Question, Bug, or Feature?**:  Bug

**Virtual environments affected**
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [x] Windows Server 2019

**Comment by miketimofeev** [comment]
@chrispat answered about KB4534273  inside github.community question

**Comment by AviVahl** [comment]
This can be closed. See update @ https://github.community/t5/GitHub-Actions/Issues-running-puppeteer-2-1-0-chromium-80-on-a-Windows/m-p/44540#M5813

**Comment by miketimofeev** [comment]
@AviVahl thanks for the update. Feel free to open a new issue if you need some help.
