### ISSUE TITLE
Add PHP extensions: imagick, pcov and sodium

### ISSUE THREAD

**Issue by shivammathur** [actions/virtual-environments#3341]
**Tool information**
- Tool name: imagick, pcov and sodium PHP extensions
   imagick on all supported PHP versions, sodium on PHP 7.0 and 7.1 and pcov on PHP 7.1 and newer.
- Tool license: 
    - imagick: [PHP-3.01](https://github.com/Imagick/imagick/blob/master/LICENSE)
    - pcov: [PHP-3.01](https://github.com/krakjoe/pcov/blob/develop/LICENSE)
    - sodium: [BSD-2-Clause](https://github.com/jedisct1/libsodium-php/blob/master/LICENSE)
- Add or update? Add
- Desired version: latest versions in `ppa:ondrej/php`
- Approximate size:
- If this is an add request:
  - Brief description of tool:
    - imagick: PHP extension to modify images using `imagemagick` library.
    - pcov: Widely used code coverage driver in PHP. This is an alternative to `Xdebug`.
    - sodium: PHP extension providing cryptography functions from `libsodium` library.
  - URL for tool's homepage:
    - imagick: https://github.com/Imagick/imagick
    - pcov: https://github.com/krakjoe/pcov
    - sodium: https://github.com/jedisct1/libsodium-php
  - Provide a basic test case to validate the tool's functionality: `php -m`

**Area for Triage**:
PHP

**Question, Bug, or Feature?**:
Feature

**Virtual environments affected**
- [X] Ubuntu 16.04
- [X] Ubuntu 18.04
- [X] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Can this tool be installed during the build?**
Yes

**Tool installation time in runtime**
~10s

**Are you willing to submit a PR?**
Yes

**Comment by AlenaSviridenko** [comment]
Hi!
PR was merged and will be available with the next deployment next week.

**Comment by shivammathur** [comment]
@AlenaSviridenko Thanks for the update

**Comment by Darleev** [comment]
Hello @shivammathur,
Could you please check that PHP extensions are in place?
We're looking forward to your reply.

**Comment by shivammathur** [comment]
@Darleev 
As per the build logs of the PR #3405, extensions should be ok. I will be able to verify this once the changes are deployed.

**Comment by tao** [comment]
Is there some delay before this is enabled all over? I've been testing `imagick` on my pipeline but it's sometimes installed and sometimes not there.

On my `beta` branch:

```bash
Current runner version: '2.278.0'
Operating System
  Ubuntu
  20.04.2
  LTS
Virtual Environment
  Environment: ubuntu-20.04
  Version: 20210517.1
  Included Software: https://github.com/actions/virtual-environments/blob/ubuntu20/20210517.1/images/linux/Ubuntu2004-README.md
  Image Release: https://github.com/actions/virtual-environments/releases/tag/ubuntu20%2F20210517.1
  
  ---
  
  ### Step: Verify Imagick
> Run php -r 'echo "imagick is ".(extension_loaded("imagick")?"":"not ")."installed\n";'
> imagick is not installed
  ```
  
  On my `staging` branch (running at the exact same time):

```bash
Current runner version: '2.278.0'
Operating System
  Ubuntu
  20.04.2
  LTS
Virtual Environment
  Environment: ubuntu-20.04
  Version: 20210524.1
  Included Software: https://github.com/actions/virtual-environments/blob/ubuntu20/20210524.1/images/linux/Ubuntu2004-README.md
  Image Release: https://github.com/actions/virtual-environments/releases/tag/ubuntu20%2F20210524.1

---

  ### Step: Verify Imagick
> Run php -r 'echo "imagick is ".(extension_loaded("imagick")?"":"not ")."installed\n";'
> imagick is installed
```

On the staging pipeline with imagick I was able to use and generate my thumbnails correctly, but not on the `beta` branch.

However, I notice the version number is slightly different `20210524.1` ... should or can we specify a specific version of Ubuntu in the Github Actions to get this working or will this random bug or imagick sometimes not being installed disappear over time?

**Comment by shivammathur** [comment]
@Darleev I have verified the extensions.

**Comment by miketimofeev** [comment]
@tao Ubuntu 20 image version 20210524.1 will be fully deployed in the next few hours. Sorry for the inconvenience.
