### ISSUE TITLE
Add Swig for macOS and Windows

### ISSUE THREAD

**Issue by chezou** [actions/virtual-environments#3342]
**Tool information**
- Tool name: swig
- Tool license: GPL
- Add or update?: Add
- Desired version: 4.0.x
- Approximate size: 6MB
- If this is an add request:
  - Brief description of tool: connects programs written in C and C++ with a variety of high-level programming languages
  - URL for tool's homepage: http://swig.org/
  - Provide a basic test case to validate the tool's functionality: `swig -version`

**Area for Triage**: Scripting and command line

**Question, Bug, or Feature?**: Feature

**Virtual environments affected**
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [x] macOS 10.15
- [x] macOS 11.0
- [x] Windows Server 2016 R2
- [x] Windows Server 2019

**Can this tool be installed during the build?**
It can be installed via Homebrew for macOS and via chocolatey for Windows

**Tool installation time in runtime**
Not so match since we can install pre-packaged one from package managers.

**Are you willing to submit a PR?**
I'm afraid I'm too unfamiliar to make a PR.

This request is a follow-up for https://github.com/actions/virtual-environments/issues/1203 which has been done for Ubuntu one year ago.

**Comment by AlenaSviridenko** [comment]
Hi @chezou,
we don't mind adding Swig to macOS and Windows. I will put this issue to our backlog, and we will keep you posted with the updates. Thanks.

**Comment by kassannk** [comment]
@chezou 
Hi, PR has been released, will be available with the next deployment

**Comment by kassannk** [comment]
@chezou Hi. Images are fully deployed, swig is available

**Comment by chezou** [comment]
@kassannk Thank you so much for your support!

**Comment by iurii-provizio** [comment]
Is there a reason SWIG is not included in macos runners newer than macos-12? It's present in 12: https://github.com/actions/runner-images/blob/main/images/macos/macos-12-Readme.md but not in 13 or newer: https://github.com/actions/runner-images/blob/main/images/macos/macos-13-Readme.md.
