### ISSUE TITLE
3.10 is not aliased(?) to latest 3.10 beta

### ISSUE THREAD

**Issue by Freso** [actions/virtual-environments#3343]
**Description**  
Specifying 3.9 in `python-versions` will give you the most recent version of Python 3.9, but there seem to be no way to specify most recent 3.10 (beta) version which means that you will have to manually keep up with the most recent beta. An option for "development" or "3-dev" or something could also work.

**Area for Triage**:  
Python

**Question, Bug, or Feature?**:  
Question, Bug, or Feature (not sure which is most applicable here)

**Virtual environments affected**  
- [x] Ubuntu 16.04
- [x] Ubuntu 18.04
- [x] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

Probably all of them? I don’t know how this whole thing works. :\

**Image version**

https://github.com/actions/virtual-environments/releases/tag/ubuntu20%2F20210504.1

**Expected behavior**  
I expected the build to run with the most recent version of 3.10.

**Actual behavior**  
Got an "Error: Version 3.10 with arch x64 not found"

**Repro steps**  

1. Add `'3.10'` to a `python-versions` array.
2. Run job

See https://github.com/JonnyJD/musicbrainz-isrcsubmit/pull/134/checks?check_run_id=2539409850 for an example.

**Comment by maxim-lobanov** [comment]
I think this issue should come to https://github.com/actions/setup-python
@Freso , please follow action's documentation. It contains description how to specify pre-release versions:

> Download and set up an accurate pre-release version of Python:
> ```yml
> steps:
> - uses: actions/checkout@v2
> - uses: actions/setup-python@v2
>   with:
>     python-version: '3.9.0-beta.4'
> - run: python my_script.py
> ```
> Download and set up the latest available version of Python (includes both pre-release and stable versions):
> ```yml
> steps:
> - uses: actions/checkout@v2
> - uses: actions/setup-python@v2
>   with:
>     python-version: '3.9.0-alpha - 3.9.0' # SemVer's version range syntax
> - run: python my_script.py

**Comment by nulano** [comment]
You can use `3.10-dev`. It is undocumented, but seems to be used by a lot of projects anyway. See also https://github.com/actions/setup-python/issues/177
