### ISSUE TITLE
Documentation for contributing macOS environment updates missing

### ISSUE THREAD

**Issue by zbeekman** [actions/virtual-environments#335]
### Update & Edit

For anyone else stumbling across this issue, GH staff have confirmed that macOS infrastructure is not yet public, and, therefore, you cannot open a PR against the macOS environment. I'm hoping they will either document this fact or make the infrastructure public sometime soon.

---

**Describe the bug**

There is no obvious documentation for contributing PRs to update the macOS environment. [CONTRIBUTING.md](https://github.com/actions/virtual-environments/blob/master/CONTRIBUTING.md) has instructions that appear to be applicable to Linux (and maybe windows) only. Furthermore, the [`images/macos`](https://github.com/actions/virtual-environments/tree/master/images/macos) directory is effectively empty with a readme that does not provide any further detail on how to submit a PR.

FYI, I'm a Homebrew maintainer and was looking into some ways to improve the performance of `brew install xyz` on GHA and also looking into adding one or more packages to the default environment (graphviz and gcc which includes gcc, g++, gfortran and some compilers/tooling).

**Area for Triage**: 
Apple

**Question, Bug, or Feature?**: 
"Question"

But also, kind of a "bug".

**Virtual environments affected**
- [x] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Expected behavior**

Better documentation for how to contribute to the macOS environment via PR. Or an explanation of why you can't.

**Actual behavior**

No observable documentation on updating the macOS environment.

**Comment by zbeekman** [comment]
I've set up a small experiment to:

1. Gather information about how Homebrew is being used in the environment, and
2. See if I can improve the performance at all of homebrew installs

You can view the results on the [repo's gh-pages branch](https://github.com/zbeekman/brew-GHA-profiling/tree/gh-pages) including some timings for `brew install $PKG` for the default setup and then two experimental setups:

1. Tweaking some environment variables to see if I can coerce homebrew into not communicating with the outside world as much and
2. Setting up caching for the `brew --cache`

The data are in CSV files at the root of the gh-pages branch. To see how I'm generating the data, take a look at the [workflows on master](https://github.com/zbeekman/brew-GHA-profiling/tree/master/.github/workflows)

My very preliminary results seem to suggest that caching downloaded "bottles" has some performance benefit and is a worthwhile endeavor. Also, between the output from interrogating the default environment and this result I would be that there is no caching proxy setup in front of Homebrew on macOS runners. Is this true?

FYI, Homebrew provides a number of mechanisms to setup a caching proxy. If you take a look at the manpage (`man brew`) near the bottom it lists a bunch of environment variables that affect the behavior. You should be able to use either
`HOMEBREW_BOTTLE_DOMAIN` or one or more of the `*_proxy` environment variables to set up a caching proxy for GitHub Actions on macOS. I may re-post this comment as a new issue.

**Comment by thejoebourneidentity** [comment]
https://github.com/actions/virtual-environments/pull/457 to more clearly document missing macOS source, and we are still working on it!

**Comment by zbeekman** [comment]
@thejoebourneidentity Looks good to me! Feel free to close this or keep it open.

**Comment by thejoebourneidentity** [comment]
I'm going to close for now but I am adding enhancement tag so we come back to it later once we've open sourced our mac scripts.
