### ISSUE TITLE
ubuntu-20.04: libutil not found since image version 20210419.1

### ISSUE THREAD

**Issue by br101** [actions/virtual-environments#3351]
**Description**  

While cross-building an OpenWRT package with ubuntu-20.04 image version '20210419.1' the build fails because it can not find "libutil". 

OpenWRT builds are cross-compiling for a different architecture. The package inside the OpenWRT build uses Meson. The error message is:
  
meson.build:7:0: ERROR: C shared or static library 'libutil' not found

The exact same build worked well until image version '20210412.1'.

Is there some new environment variable overriding the location to libutil? 
Is there any way to interactively login to a build agent to debug the situation?

**Question, Bug, or Feature?**:  
Bug

**Virtual environments affected**  
- [ ] Ubuntu 16.04
- [x] Ubuntu 18.04
- [ X] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Image version**
20210419.1

**Expected behavior**  
The OpenWRT build should complete as it did in the previous version '20210412.1'.

**Actual behavior**  
The build fails because libutil can not be found.

**Repro steps**  

Unfortunately I can not share the OpenWRT repository.

**Comment by al-cheb** [comment]
Hi, @br101 
Could you please check logs what was the path for the 'libutil' before image version 20210419.1?

![image](https://user-images.githubusercontent.com/47745270/117764870-d0bd2680-b235-11eb-9ef2-570db52b40f8.png)

**Comment by br101** [comment]
I would do that but unfortunately I cannot find out how to specify the image version for Azure pipelines...

**Comment by al-cheb** [comment]
> I would do that but unfortunately I cannot find out how to specify the image version for Azure pipelines...

Currently you can't specify the image version for Azure pipelines - https://github.com/github/roadmap/issues/161.

**Comment by al-cheb** [comment]
Could please test workaround to set a path to the libutil - https://github.com/GNOME/glib/blob/c0b339372cf3cf29cc8fee212a2debc41ea93cd2/gio/tests/meson.build#L15 ?

```
ldconfig -p | grep libutil
	libutil.so.1 (libc6,x86-64, OS ABI: Linux 3.2.0) => /lib/x86_64-linux-gnu/libutil.so.1
	libutil.so.1 (libc6, OS ABI: Linux 3.2.0) => /lib32/libutil.so.1
	libutil.so (libc6,x86-64, OS ABI: Linux 3.2.0) => /lib/x86_64-linux-gnu/libutil.so
```

**Comment by dibir-magomedsaygitov** [comment]
Hello, @br101. Have you tried suggested workaround? Is the issue still appearing for you?

**Comment by br101** [comment]
I don't see how the workaround applies to this situation. libutil is not found in the *cross*-build, also the cross-build is using MUSL (https://www.musl-libc.org/) and there is only libutil.a, not libutil.so

**Comment by br101** [comment]
Funny thing is it worked before and it stopped working with this version, so I wonder is there something overriding the libutil path now similar to -DLIBUTIL_SONAME?

**Comment by dibir-magomedsaygitov** [comment]
Hello @br101. I tried to reproduce the issue by building sample project using [Meson ](https://mesonbuild.com/SimpleStart.html)and this project was successfully built. Could you please provide us minimal repro steps to help with investigation process.

**Comment by br101** [comment]
I'm sorry but I can't do that. It is an adapted version of OpenWRT that I can not share. I have solved the issue for me by building inside a docker image. Sorry...

**Comment by dibir-magomedsaygitov** [comment]
Hello @br101. Thank you for the update. I'm going to close the issue. In case of any questions feel free to contact us.

**Comment by br101** [comment]
Interestingly this issue appeared again in image version: '20210726.1' - now even though I run the build inside my own docker image which hasn't changed. in image version: '20210718.1' it is still okay...

**Comment by miketimofeev** [comment]
@br101 we have recently deployed 20210803 images. Does the issue persist there?

**Comment by br101** [comment]
@miketimofeev Same problem with image version: '20210803.0'

**Comment by miketimofeev** [comment]
@br101 we will reopen the issue in case you are able to provide a minimal repro, otherwise we can't help, unfortunately
