### ISSUE TITLE
Malformed /etc/hosts.

### ISSUE THREAD

**Issue by igsilya** [actions/virtual-environments#3353]
**Description**  
/etc/hosts file contains following:
```
127.0.0.1 localhost

# The following lines are desirable for IPv6 capable hosts
::1     localhost ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
ff02::3 ip6-allhosts
Note: Don't Delete this file. Also, don't remove this line. And empty file will break pool provisioning.
127.0.0.1 cpu-pool.com
127.0.0.1 MiningMadness.com
127.0.0.1 stratum-na.rplant.xyz
127.0.0.1 do-dear.com
127.0.0.1 web.do-dear.com
127.0.0.1 git.workflows.live
10.1.0.62 fv-az50-195.grzltbmokehuzjyc5b133kdqgh.cx.internal.cloudapp.net fv-az50-195
```
The `Note: ...` line is not a valid line for this file and it breaks libunbound that is no longer able to parse this file.
This breaks unit tests at least for openvswitch project. 

**Area for Triage**:  

**Question, Bug, or Feature?**:  

Bug

**Virtual environments affected**  
- [ ] Ubuntu 16.04
- [x] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Image version**

20210504.1

**Expected behavior**  
There should be no extra text in /etc/hosts.  At least, it should be a comment, not just a text.

**Actual behavior**  
libunbound is broken, not able to parse the /etc/hosts.

**Repro steps**  
Failed unit tests for openvswitch project:
https://github.com/ovsrobot/ovs/runs/2547843800

**Comment by igsilya** [comment]
For the time being we worked around this issue by `sed -i "/don't remove this line/d" /etc/hosts`, but would like to revert this change as soon as the issue fixed.

**Comment by al-cheb** [comment]
@igsilya , The fix has been deployed.
