### ISSUE TITLE
macOS 10.15 and 10.14 public IP addresses

### ISSUE THREAD

**Issue by WoopsDoops** [actions/virtual-environments#3354]
Hi there,
Is there anyway to determine list of public IP addresses for macOS machines in Azure DevOps? I made a small investigation and found that addresses bound to different organisations(macstadium,microsoft,azure). This information is required to pass through the firewall during a job execution using macOS machines.

Any help would be much appreciated. Thanks.

**Comment by maxim-lobanov** [comment]
Please follow the guide provided below the message that you mentioned:
> To get a list of IP address ranges that GitHub Actions uses for GitHub-hosted runners, you can use the GitHub REST API . For more information, see the actions key in the response of the "Get GitHub meta information" endpoint. You can use this list of IP addresses if you require an allow-list to prevent unauthorized access to your internal resources.

https://docs.github.com/en/rest/reference/meta#get-github-meta-information this endpoint returns the list of IP addresses including macOS Hosted runners

**Comment by WoopsDoops** [comment]
@maxim-lobanov thanks you for the provided information and pointing to correct way how to obtain IP addresses. Unfortunately, the list does not contain all possible addresses for mac machines, for example, I've got the following addresses which are not presented in the list obtained by the API:
13.105.49.76
199.19.85.226
13.105.49.42
...
Am I doing something wrong?

**Comment by miketimofeev** [comment]
@WoopsDoops just a quick update — we're working on updating the API with the actual list, but, unfortunately, it'll take some time. I'll keep you posted.

**Comment by miketimofeev** [comment]
@WoopsDoops we will update the API list in the next few weeks. Until then you can use this full list:
<details>
  <summary>macOS ips</summary>
13.105.49.106/31
13.105.49.96/31
13.105.49.46/31
13.105.49.180/31
13.105.49.80/31
13.105.49.52/31
13.105.49.154/31
13.105.49.38/31
13.105.49.108/31
13.105.49.2/31
13.105.49.182/31
13.105.49.16/31
13.105.49.30/31
13.105.49.48/31
13.105.49.66/31
13.105.49.174/31
13.105.49.24/31
13.105.49.98/31
13.105.49.50/31
13.105.49.164/31
13.105.49.40/31
13.105.49.12/31
13.105.49.84/31
13.105.49.158/31
13.105.49.42/31
13.105.49.26/31
13.105.49.94/31
13.105.49.88/31
13.105.49.32/31
13.105.49.20/31
13.105.49.6/31
13.105.49.104/31
13.105.49.22/31
13.105.49.102/31
13.105.49.10/31
13.105.49.14/31
13.105.49.160/31
13.105.49.170/31
13.105.49.34/31
13.105.49.68/31
13.105.49.60/31
13.105.49.156/31
13.105.49.162/31
13.105.49.152/31
13.105.49.56/31
13.105.49.4/31
13.105.49.168/31
13.105.49.100/31
13.105.49.28/31
13.105.49.36/31
13.105.49.58/31
13.105.49.126/31
13.105.49.64/31
13.105.49.18/31
13.105.49.112/31
13.105.49.74/31
13.105.49.54/31
13.105.49.166/31
13.105.49.70/31
13.105.49.172/31
13.105.49.178/31
13.105.49.110/31
13.105.49.86/31
13.105.49.62/31
13.105.49.90/31
13.105.49.44/31
13.105.49.82/31
13.105.49.76/31
13.105.49.176/31
13.105.49.114/31
13.105.49.8/31
13.105.49.92/31
13.105.49.0/31
13.105.49.72/31
13.105.49.78/31
199.7.166.8/29
199.19.85.24/29
199.19.85.224/29
208.83.5.224/29
</details>

**Comment by WoopsDoops** [comment]
Thank you, great job!

**Comment by miketimofeev** [comment]
@WoopsDoops API was updated:
`curl -H "Accept: application/vnd.github.v3+json" https://api.github.com/meta` returns the full list now.
I'm going to close the issue. Please feel free to contact us if you have any concerns.
Thank you!

**Comment by WoopsDoops** [comment]
@miketimofeev thanks again for the assistance. I'm using the file( https://www.microsoft.com/en-us/download/confirmation.aspx?id=56519 ) with the list of Azure IP addresses from official Microsoft documentation, I'm not sure should it be updated or not.
I think this is not a reason to rediscover this problem, so, let's leave that up to you.

**Comment by hungkvbn** [comment]
> 13.105.49.106/31 13.105.49.96/31 13.105.49.46/31 13.105.49.180/31 13.105.49.80/31 13.105.49.52/31 13.105.49.154/31 13.105.49.38/31 13.105.49.108/31 13.105.49.2/31 13.105.49.182/31 13.105.49.16/31 13.105.49.30/31 13.105.49.48/31 13.105.49.66/31 13.105.49.174/31 13.105.49.24/31 13.105.49.98/31 13.105.49.50/31 13.105.49.164/31 13.105.49.40/31 13.105.49.12/31 13.105.49.84/31 13.105.49.158/31 13.105.49.42/31 13.105.49.26/31 13.105.49.94/31 13.105.49.88/31 13.105.49.32/31 13.105.49.20/31 13.105.49.6/31 13.105.49.104/31 13.105.49.22/31 13.105.49.102/31 13.105.49.10/31 13.105.49.14/31 13.105.49.160/31 13.105.49.170/31 13.105.49.34/31 13.105.49.68/31 13.105.49.60/31 13.105.49.156/31 13.105.49.162/31 13.105.49.152/31 13.105.49.56/31 13.105.49.4/31 13.105.49.168/31 13.105.49.100/31 13.105.49.28/31 13.105.49.36/31 13.105.49.58/31 13.105.49.126/31 13.105.49.64/31 13.105.49.18/31 13.105.49.112/31 13.105.49.74/31 13.105.49.54/31 13.105.49.166/31 13.105.49.70/31 13.105.49.172/31 13.105.49.178/31 13.105.49.110/31 13.105.49.86/31 13.105.49.62/31 13.105.49.90/31 13.105.49.44/31 13.105.49.82/31 13.105.49.76/31 13.105.49.176/31 13.105.49.114/31 13.105.49.8/31 13.105.49.92/31 13.105.49.0/31 13.105.49.72/31 13.105.49.78/31 199.7.166.8/29 199.19.85.24/29 199.19.85.224/29 208.83.5.224/29

@miketimofeev Could you tell me how to get this macos ips.
When I using curl -H "Accept: application/vnd.github.v3+json" https://api.github.com/meta. It response too much actions ips.
