### ISSUE TITLE
Add GCC 11.1.0 and update GCC 10.2.0 to 10.3.0 on macOS

### ISSUE THREAD

**Issue by PragmaTwice** [actions/virtual-environments#3359]
**Tool information**
- Tool name: GCC
- Tool license: GPL-3.0-or-later with GCC-exception-3.1
- Add or update? update
- Desired version: 11.1.0 and 10.3.0 (now only GCC 10.2.0)

**Area for Triage**:
C/C++

**Question, Bug, or Feature?**:
Feature

**Virtual environments affected**
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [x] macOS 10.15
- [x] macOS 11.0
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Can this tool be installed during the build?**
GCC [11.1.0](https://github.com/Homebrew/homebrew-core/pull/74843) and [10.3.0](https://github.com/Homebrew/homebrew-core/pull/76894) have been added to the homebrew

**Are you willing to submit a PR?**
Yes, if I have time

**Comment by miketimofeev** [comment]
@PragmaTwice we have added gcc 11.1.0 to all the macOS images. They will be delivered next week.

**Comment by miketimofeev** [comment]
@PragmaTwice the new image was deployed yesterday.
I'm going to close the issue. Please feel free to contact us if you have any concerns.
Thank you!
