### ISSUE TITLE
packer templates don't support using build_resource_group_name variable

### ISSUE THREAD

**Issue by shawnz88** [actions/virtual-environments#3365]
**Description**  
Getting the following error when passing "build_resource_group_name" variable into "packer build" command without specifying "temp_resource_group_name" variable:

Syntax-only check passed. Everything looks okay.
Show Packer Version
1.7.2
Build windows2019 VM
Error: Failed to prepare build: "vhd"

1 error(s) occurred:

 Specify either a location to create the resource group in or an existing
build_resource_group_name, but not both.

**Area for Triage**:  
scripting and command line

**Question, Bug, or Feature?**:  
Feature

**Virtual environments affected**  
- [x] Ubuntu 16.04
- [x] Ubuntu 18.04
- [x] Ubuntu 20.04
- [x] macOS 10.15
- [x] macOS 11.0
- [x] Windows Server 2016 R2
- [x] Windows Server 2019

**Image version**

All versions

**Expected behavior**  
When "build_resource_group_name" variable is passed to "packer build" command and "temp_resource_group_name" is omitted, vhd should be built with existing resource group specified by "build_resource_group_name".

**Actual behavior**  
The following error happens:

1 error(s) occurred:

* Specify either a location to create the resource group in or an existing
build_resource_group_name, but not both.

**Repro steps**  

1. Run this command:
       packer build    -var "capture_name_prefix=$ResourcesNamePrefix" `
                -var "client_id=$ClientId" `
                -var "client_secret=$ClientSecret" `
                -var "install_password=$InstallPassword" `
                -var "resource_group=$ResourceGroup" `
                -var "build_resource_group_name=$TempResourceGroup" `
                -var "subscription_id=$SubscriptionId" `
                -var "tenant_id=$TenantId" `
                -var "storage_account=$StorageAccount" `
                -var "run_validation_diskspace=$env:RUN_VALIDATION_FLAG" `
                $TemplatePath `

**Comment by al-cheb** [comment]
PR Windows&Ubuntu -  https://github.com/actions/virtual-environments/pull/3369
