### ISSUE TITLE
docker-compose hangs on Ubuntu 20.04

### ISSUE THREAD

**Issue by mausch** [actions/virtual-environments#3367]
**Description**  
A docker-compose step on one of my projects started hanging one day.
Successful run: https://github.com/SolrNet/SolrNet/runs/1935733271?check_suite_focus=true#step:1:1
Unsuccessful run: https://github.com/SolrNet/SolrNet/runs/2540761670?check_suite_focus=true#step:1:1

GitHub support found that the difference is the environment version, and with it the version of docker-compose. They suggested opening an issue about this here.

The environment version 20210504.1 has docker-compose 1.29.1.
So I tried downgrading docker-compose to 1.28.6 first, which still failed: https://github.com/SolrNet/SolrNet/actions/runs/833337149
Then I downgraded to 1.28.2 which works: https://github.com/SolrNet/SolrNet/actions/runs/833360864

So it seems there's some issue with 1.29.1 ?

**Area for Triage**:  

**Question, Bug, or Feature?**:  

Bug

**Virtual environments affected**  
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [x] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Image version**

Image version where you are experiencing the issue.
20210504.1

**Expected behavior**  
docker-compose should not hangs

**Actual behavior**  
docker-compose hangs when stopping containers.

**Repro steps**  
Already provided links to the repo above.

**Comment by al-cheb** [comment]
Hi, @mausch 
Please check this recommendation  - https://github.com/docker/compose/issues/3927. Could you please create an issue in the repo - https://github.com/docker/compose/issues?

**Comment by mausch** [comment]
Hi Aleksandr, thanks yes I've seen that issue.
I tried increasing the timeout but that only made it hang for a longer period of time.
I tried disabling tty, no difference.
I can't follow the suggestions about restarting the daemon or similar as that sort of stuff is out of my control in this context.

As there's already an open issue about this (which now links to this issue too), I don't think it's necessary to create another one?

I already have a workaround (downgrading docker-compose) so maintainers of this project can handle it however you want :slightly_smiling_face:

**Comment by Darleev** [comment]
@mausch since docker-compose downgrade helped with the issue, it means that the issue exactly not in virtual-environments agents and should be investigated by docker-compose team.
For now, nothing to do from our side. I'm going to close the issue.
In case of any questions, feel free to contact us.
