### ISSUE TITLE
Update/Add [MacOS 10.16] and xcode 12.5 as ios is not accepting the build file below this version

### ISSUE THREAD

**Issue by Priyankakum** [actions/virtual-environments#3368]
**Tool information**
- Tool name: <MacOS 10.16>
- Tool license: 
- Add or update? <Add>
- Desired version: <MacOS 10.16] and xcode 12.5>
- Approximate size: 
- If this is an add request:
  - Brief description of tool: <Update/Add [MacOS 10.16] and xcode 12.5 as ios is not accepting the build file below this version>
  - URL for tool's homepage: <microsoft hosted macos version 10.16>
  - Provide a basic test case to validate the tool's functionality: <not able to build the application using xcode 12.5 upgrade by apple>

**Area for Triage**:

**Question, Bug, or Feature?**:

**Virtual environments affected**
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Can this tool be installed during the build?**

**Tool installation time in runtime**

**Are you willing to submit a PR?**

**Comment by AlenaSviridenko** [comment]
Hi @Priyankakum,
do you mean macOS 11? You can track progress of onboarding this OS in the pinned issue https://github.com/actions/virtual-environments/issues/2486

**Comment by Priyankakum** [comment]
Classification: Confidential
Hi,

No I mean macOS 11.6 in azure agent pool option in azure devops pipeline.
Currently I can have only macOS 11.14 and 11.15.


Thanks,
Priyanka Kumari

**Comment by AlenaSviridenko** [comment]
Currently, Azure Pipelines have macOS 10.14 and macOS 10.15. Xcode 12.4 is the latest supported on macOS 10.15. 
Xcode 12.5 supports macOS 11, and it is still not available for Azure Pipelines, but you can track the onboarding timeline in the issue I linked above https://github.com/actions/virtual-environments/issues/2486.

**Comment by Priyankakum** [comment]
Classification: Confidential
Thanks for the information.

**Comment by Priyankakum** [comment]
Classification: Confidential
Hi,


Sorry instead of 10 I put it in below mail as 11.


Thank you so much for your quick reply.

No I mean macOS 11in azure agent pool option in azure devops pipeline.
Currently I can have only macOS 10.14 and 10.15.


Thanks,
Priyanka Kumari

From: Priyanka Kumari
Sent: Wednesday, May 12, 2021 3:47 PM
To: actions/virtual-environments ***@***.***>; actions/virtual-environments ***@***.***>
Cc: Mention ***@***.***>
Subject: RE: [actions/virtual-environments] Update/Add [MacOS 10.16] and xcode 12.5 as ios is not accepting the build file below this version (#3368)

Classification: Confidential
Hi,

No I mean macOS 11.6 in azure agent pool option in azure devops pipeline.
Currently I can have only macOS 11.14 and 11.15.


Thanks,
Priyanka Kumari
