### ISSUE TITLE
[Ubuntu] Failed to apt-get libmysqlclient-dev

### ISSUE THREAD

**Issue by ivailop** [actions/virtual-environments#337]
**Describe the bug**
On Ubuntu 16.04, since today (1/29/2020), installation of `libmysqlclient-dev` errors out:
```
sudo apt-get libmysqlclient-dev
...
Err:87 http://security.ubuntu.com/ubuntu xenial-security/main amd64 libmysqlclient-dev amd64 5.7.28-0ubuntu0.16.04.2
  404  Not Found
Fetched 30.0 MB in 0s (30.3 MB/s)
E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/m/mysql-5.7/libmysqlclient-dev_5.7.28-0ubuntu0.16.04.2_amd64.deb  404  Not Found

E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
```

**Area for Triage**: 

**Question, Bug, or Feature?**: 
Bug

**Virtual environments affected**
- [ ] macOS 10.15
- [x] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Expected behavior**
Install successfully

**Actual behavior**
Errors out.

```
E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/m/mysql-5.7/libmysqlclient-dev_5.7.28-0ubuntu0.16.04.2_amd64.deb  404  Not Found
```

**Comment by ivailop** [comment]
FYI, similar issue (but with `5.7.27`) happened couple of months ago - https://github.com/microsoft/azure-pipelines-image-generation/issues/1410

To prevent this environment volatility wouldn't it be better to have a more stable version of MySQL (e.g. `5.5`, instead of `5.7`) installed on the hosted images?

**Comment by miketimofeev** [comment]
@ivailop thanks for reporting this issue. MySQL will be updated to 5.7.29 on the next rollout, and the problem should disappear. 
We will also consider adding libmysqlclient-dev during the image generation step to avoid such inconvenience in the future.

**Comment by al-cheb** [comment]
Temporary workaround:
```
jobs:
  build:
    runs-on: [ubuntu-16.04]
    steps:
    - name: libmysql
      run: |
        sudo apt-get update && sudo apt-get install libmysqlclient-dev
```

![image](https://user-images.githubusercontent.com/47745270/73518157-9d72d180-440e-11ea-93b1-76799036f46b.png)

**Comment by miketimofeev** [comment]
@ivailop the installation has been added to image-generation scripts and will be rolled out in 1-2 weeks

**Comment by miketimofeev** [comment]
@ivailop the image has been rolled out. Could you check that ibmysqlclient-dev is preinstalled?

**Comment by ivailop** [comment]
It appears to be working fine now.
