### ISSUE TITLE
Unable to create deployment slots using azure-cli 2.23.0

### ISSUE THREAD

**Issue by CReich02** [actions/virtual-environments#3379]
**Description**  
There is a bug in the latest version of azure-cli version 2.23.0 that is causing issues with creating deployment slots.
Bug reported in https://github.com/Azure/azure-cli/issues/18072
This is causing issues deploying due to hosted agents being updated to use latest azure-cli

Please downgrade version of azure-cli on hosted agents until this issue is resolved.

**Area for Triage**:  
Deployment/Release

**Question, Bug, or Feature?**:  
Bug

**Virtual environments affected**  
- [x] Ubuntu 16.04
- [x] Ubuntu 18.04
- [x] Ubuntu 20.04
- [x] macOS 10.15
- [x] macOS 11.0
- [x] Windows Server 2016 R2
- [x] Windows Server 2019

**Expected behavior**  
Should be able to use azure-cli commands to create deployment slots.

**Actual behavior**  
There is an error described in https://github.com/Azure/azure-cli/issues/18072

**Repro steps**  
1. Create pipeline using hosted agent
2. Add AzureCLI@2 task to create deployment slot
3. Run pipeline
4. Get error

**Comment by al-cheb** [comment]
Hi, @CReich02 

You can downgrade azure-cli version in runtime:

1. Workaround for macOS:
```
brew uninstall azure-cli
brew tap-new $USER/old-azure-cli
brew extract --version=2.20.0 azure-cli $USER/old-azure-cli
brew install azure-cli@2.20.0
az version
```

2. Workaround for Windows:
```
(Get-WmiObject Win32_Product -Filter "Caption='Microsoft Azure CLI'").Uninstall()
choco install azure-cli --version 2.20.0
az version
```

3. Workaround for Ubuntu:
```
sudo apt-get remove azure-cli
curl -sL https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/microsoft.gpg > /dev/null
echo "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/azure-cli.list
sudo apt-get update
sudo apt-get install azure-cli=2.20.0-1~$(lsb_release -cs)
az version
```

**Comment by Darleev** [comment]
Hello @CReich02,
Since we don't receive any update from you side for a long time. I'm going to close the issue.
In case of any questions, feel free to write us back.
