### ISSUE TITLE
Node.js: Support "lts", "latest" and "stable" version

### ISSUE THREAD

**Issue by martinheidegger** [actions/virtual-environments#3384]
**Tool information**
- Tool name: nodejs docker image
- Add or update? update
- Desired version: latest, lts

**Area for Triage**:
JavaScript and Node.js

**Feature**:
Add support for "lts", "latest" and "stable" version to node.js setup action.

When building Node.js libraries it is of interest to know if a given library breaks with new Node.js versions. Also it is often okay if a library does not work anymore with a version that is not maintained anymore.

As such, rather than specifying a concrete version for Node.js it would be much healthier for the scripts to be able to specify `["lts", "stable", "latest"]` in the matrix and have a [`on.schedule`](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#onschedule) setting to run the tests regularly and make sure that a given library doesn't break in new node.js versions.

**Tool installation time in runtime**
No change to current.

**Are you willing to submit a PR?**
No. As I am very unfamiliar with this setup, starting from the programming language.

**Comment by al-cheb** [comment]
Duplicate - https://github.com/actions/setup-node/issues/26
