### ISSUE TITLE
GitHub Actions has encountered an internal error when running your job. All jobs not starting.

### ISSUE THREAD

**Issue by TannerBrunscheon** [actions/virtual-environments#3387]
**Description**  
A clear and concise description of what the bug is, and why you consider it to be a bug.

**Area for Triage**:  
Deployment/Release

**Question, Bug, or Feature?**:  
Bug

**Virtual environments affected**  
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [x] Ubuntu 20.04
- [ ] macOS 10.15
- [x] macOS 11.0
- [ ] Windows Server 2016 R2
- [x] Windows Server 2019

**Expected behavior**  
All my jobs working

**Actual behavior**  
All of my actions are unable to run. The get stuck on Starting workflow run for about 3 minutes and fail with GitHub Actions has encountered an internal error when running your job. The jobs themselves show Canceled. This is for 4 different jobs across windows and linux platforms. 

![image](https://user-images.githubusercontent.com/25444146/118288330-f0ed1f80-b499-11eb-94fc-dc96e0b010cd.png)
![image](https://user-images.githubusercontent.com/25444146/118288384-019d9580-b49a-11eb-8043-caefeac16237.png)

**Comment by paresy** [comment]
They are on it already: https://github.com/actions/virtual-environments/issues/2179#issuecomment-841277181
And: https://www.githubstatus.com/

**Comment by TannerBrunscheon** [comment]
@paresy I did not see it. Thanks
