### ISSUE TITLE
GitHub Actions has encountered an internal error when running your job.

### ISSUE THREAD

**Issue by kenessajr** [actions/virtual-environments#3388]
**Description**  
GitHub Actions has encountered an internal error when running your job.
- https://github.com/pindoio/pindo-cli/actions/runs/842362071

**Area for Triage**:  
python

**Question, Bug, or Feature?**:  

**Virtual environments affected**  
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [+] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Image version**

Image version where you are experiencing the issue.

**Expected behavior**  
It should run build and test

**Actual behavior**  
GitHub Actions has encountered an internal error when running your job.

**Repro steps**  
A description with steps to reproduce the issue. If you have a public example or repo to share,
please provide the link.

1. https://github.com/pindoio/pindo-cli/actions/runs/842362071

**Comment by maxim-lobanov** [comment]
https://www.githubstatus.com/incidents/plk7zdvpftby

**Comment by Darleev** [comment]
Hello @kenessajr,
It seems there were some issues with GitHub environment, and now it should works as expected. Could you please confirm that everything is fine at the moment?
We are looking forward to your reply.

**Comment by Darleev** [comment]
I'm going to close the issue until further updates.
In case of any questions, feel free to contact us.

**Comment by kenessajr** [comment]
@Darleev I'm still having the same issue. it was working a couple of hours ago. The error https://github.com/pindoio/pindo-cli/actions/runs/853659656

**Comment by Darleev** [comment]
@kenessajr it's another github action incident: https://www.githubstatus.com you check check it here.

**Comment by kenessajr** [comment]
Just saw it!
