### ISSUE TITLE
Avx512

### ISSUE THREAD

**Issue by philiprbrenan** [actions/virtual-environments#3389]
Some of the computers running Github actions have avx512 enables. others do not. This affects whether they can run the software in:

https://github.com/philiprbrenan/NasmX86/

correctly or not. For examples of identical software running on computers with different capabilities see:

https://github.com/philiprbrenan/NasmX86/runs/2571585573?check_suite_focus=true

versus:

https://github.com/philiprbrenan/NasmX86/runs/2571598006?check_suite_focus=true

Is there some way that I can consistently obtain a computer with avx512 enabled to run an action?

**Comment by Darleev** [comment]
Hello @philiprbrenan,
Unfortunately, at this time out agents are not guaranteed to have AVX-512, and only the way to enable the feature for you on permanent basis is to use self-hosted agents(where it is possible to control the underlying hardware).
In case of any additional questions, do not hesitate to contact us.

**Comment by Darleev** [comment]
@philiprbrenan I'm going to close the issue.
In case of any questions, do not hesitate to contact us.
