### ISSUE TITLE
Please add Ubuntu interim releases

### ISSUE THREAD

**Issue by rbalint** [actions/virtual-environments#339]
**Tool information**
- Tool name: Ubuntu interim (non-LTS) releases
- Add or update? Add
- Desired version: Supported releases
- Approximate size:
- If this is an add request:
  - Brief description of tool: Ubuntu interim releases are releases between LTS releases and have more recent versions of the tools than the prior LTS releases. They have shorter support period, but are very useful for developers and users looking for the most recent tool chains. Building and testing projects on interim releases also helps ensuring that moving to the next LTS release will be smooth because potential incompatibilities can be discovered earlier.
I think probably it would be better to keep `ubuntu-latest`'s meaning and keep it referring to the latest LTS release and the latest interim or LTS release could be tracked with a different name.
  - URL for tool's homepage: https://ubuntu.com/about/release-cycle

**Area for Triage**:

**Question, Bug, or Feature?**:

**Virtual environments affected**
- [ ] macOS 10.15
- [x] Ubuntu 16.04 LTS
- [x] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Can this tool be installed during the build?**
Not really. In theory the environment can be upgraded, before a build but the extra installed tools may not support the latest interim release yet, thus could fail. Upgrading between releases is also time consuming, can take more than 10 minutes.

**Are you willing to submit a PR?**
Yes.

**Comment by rbalint** [comment]
This will also help resolving in #228 in smaller steps regarding the tooling changes.

**Comment by alepauly** [comment]
@rbalint Unfortunately this is not something we can support at this time, thanks for contributing with your suggestion.
