### ISSUE TITLE
Open file descriptors while actions run

### ISSUE THREAD

**Issue by mgree** [actions/virtual-environments#3391]
**Description**  

When porting my CI to GitHub actions, it seems that FDs 11 and 14 are open for all processes.

One of my integration tests for [smoosh](https://github.com/mgree/smoosh) checks file descriptors up to 20 (to make sure my shell isn't misbehaving, leaving FDs open, etc.). You can see [the original test](https://github.com/mgree/smoosh/blob/ecdd5bf79d89ad227c17ad6e237e07439a8d9b07/tests/shell/semantics.fds.plain.test) and [my fd debugging utility](https://github.com/mgree/smoosh/blob/ecdd5bf79d89ad227c17ad6e237e07439a8d9b07/tests/util/fds.c). Here's a [failing run](https://github.com/mgree/smoosh/runs/2573176966?check_suite_focus=true#step:6:134) (`-` is expected, `+` is got).

Are these FDs open for a reason, or could the parent CI process set them as `FD_CLOEXEC` so that these low numbers aren't in use?

**Area for Triage**:  Scripting and command line

**Question, Bug, or Feature?**:  Bug

**Virtual environments affected**  
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [x] Ubuntu 20.04
- [x] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Image version**
20210510.1

**Expected behavior**  
I would expect all file descriptors other than 0, 1, and 2 to be closed in jobs I'm running. These tests passed on Travis CI (no longer visible, sorry) and my local machine.

**Actual behavior**  
File descriptors 11 and 14 are open.

**Repro steps**  
You can see a [failing run](https://github.com/mgree/smoosh/runs/2573176966?check_suite_focus=true#step:6:134) in my test suite (`-` is expected, `+` is got).

The test is [semantics.fds.plain.test](https://github.com/mgree/smoosh/blob/ecdd5bf79d89ad227c17ad6e237e07439a8d9b07/tests/shell/semantics.fds.plain.test) and the expected output is [semantics.fds.plain.out](https://github.com/mgree/smoosh/blob/ecdd5bf79d89ad227c17ad6e237e07439a8d9b07/tests/shell/semantics.fds.plain.out).

**Comment by Darleev** [comment]
Hello @mgree,
Thank you for the issue reported. We will investigate it.

**Comment by al-cheb** [comment]
@mgree ,
> Are these FDs open for a reason, or could the parent CI process set them as FD_CLOEXEC so that these low numbers aren't in use?

https://devblogs.microsoft.com/dotnet/introducing-diagnostics-improvements-in-net-core-3-0/ :
`In 3.0-preview5, every .NET Core application opens a duplex pipe named EventPipe (Unix domain socket on *nix/named pipe on Windows) over which it can emit events. While we’re still working on the controller protocol, dotnet-trace implements the preview version of this protocol.`

I think you can close these fd's manually before running a test:
```
- name: Run smoosh integration tests
        run: |
          if [ -d /proc/$$/fd/ ]; then
            for descriptor_path in /proc/$$/fd/*; do
                descriptor="$(basename "$descriptor_path")"
                # Don't close stdin/stderr/stdout (-gt 2)
                if [ $descriptor -gt 2 ]; then
                  exec {descriptor}<&-
                fi
            done
          fi
          PATH="$(pwd)/src:$PATH" TEST_DEBUG=1 TEST_TIMEOUT=15 make -C tests/ test 
```

**Comment by mgree** [comment]
Ah---clever trick! macOS doesn't have `/proc`, but I could also just run `for fd in seq 3 20; do eval "exec $fd>&-"; done`. It won't close all FDs, but it'll close enough for my tests to pass.

Thank you!

**Comment by Darleev** [comment]
@mgree I'm going to close the issue.
In case of any questions feel free to contact us.
