### ISSUE TITLE
macOS: media capture permission missing

### ISSUE THREAD

**Issue by letmaik** [actions/virtual-environments#3396]
**Description**  
I'm trying to capture output from a virtual camera with OpenCV, however there seem to be some permissions missing: https://developer.apple.com/documentation/avfoundation/cameras_and_media_capture/requesting_authorization_for_media_capture_on_macos?language=objc

**Area for Triage**:  

Apple

**Question, Bug, or Feature?**:  
Bug

**Virtual environments affected**  
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [x] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Image version**

20210510.1

**Expected behavior**  
macOS should not interactively ask for permissions in CI.

**Actual behavior**  
Not sure, but likely a permission prompt pops up.

**Repro steps**  
Install OBS (or just the virtual camera with https://github.com/letmaik/pyvirtualcam/blob/master/.github/scripts/install-macos-obs-virtual-cam.sh), then run:
```py
# pip install opencv-python
import cv2
vc = cv2.VideoCapture(0)
assert vc.isOpened()
```

Linked: https://github.com/opencv/opencv/issues/20094 https://github.com/opencv/opencv-python/issues/291

**Comment by Darleev** [comment]
Hello @letmaik,
We will investigate the issue.

**Comment by Darleev** [comment]
Hello @letmaik,
Unfortunately, at this time it's not possible to prove required permissions on agent machines, since there is no way to accept pop-up window with permissions access. We had [similar request](https://github.com/actions/virtual-environments/issues/3286), but could not find any suitable solution for this. Maybe you have ideas or a probable solution for this?
We are looking forward to your reply.

**Comment by Darleev** [comment]
@letmaik I'm going to close the issue.
If additional assistance is required, do not hesitate to contact us.

**Comment by letmaik** [comment]
I understand there may not be an immediate solution but it is still an unresolved issue. Why not keep the issue open? Other CI providers seem to have [resolved this issue](https://circleci.com/docs/2.0/testing-macos/), and I'd rather not switch away from GitHub Actions because of this.

**Comment by Darleev** [comment]
@letmaik Unfortunately, at this time, we made a decision to keep System Integrity Protection enabled on our macOS images( please refer [the link](https://github.com/actions/virtual-environments/issues/650#issuecomment-610541765) for more information). However, with SIP enabled, it is not possible to automatically accept a security pop-up window.
