### ISSUE TITLE
ubuntu-latest no postgresql-server-dev-13

### ISSUE THREAD

**Issue by jcflack** [actions/virtual-environments#3397]
**Description** 

The `ubuntu-latest` runner has recently begun failing to find `postgresql-server-dev-13` via `apt-get` (see [this step][failstep]).

The `ubuntu-latest` runner is documented to provide PostgreSQL 13.2 from the PGDG Apt repo (see [this step][docstep] and the [associated doc][doc]).

The runner does indeed report that `PostgreSQL 13.2 (Ubuntu 13.2-1.pgdg20.04+1)` is the server version installed (see [this step][verstep]).

That server version should have come from the PGDG Apt repo and that repository does indeed contain the `postgresql-server-dev-13` package (see [its `Packages` index][pidx]).

Any idea why `apt-get` is reporting failure to find the package? Only my recent runs have shown this problem; earlier runs (from, e.g., March 28) were successful, same `ubuntu-latest` runner spec, same PostgreSQL 13.2 version (but an earlier image version).

I notice in the failing job that `apt-get update` does not report fetching the PGDG repo metadata. Has that repo somehow been lost from the runner configuration, even though the installed PostgreSQL version is from it?

[failstep]: https://github.com/tada/pljava/runs/2536203324?check_suite_focus=true#step:6:38
[docstep]: https://github.com/tada/pljava/runs/2536203324?check_suite_focus=true#step:1:9
[doc]: https://github.com/actions/virtual-environments/blob/ubuntu20/20210504.1/images/linux/Ubuntu2004-README.md
[verstep]: https://github.com/tada/pljava/runs/2536203324?check_suite_focus=true#step:4:40
[pidx]: http://apt.postgresql.org/pub/repos/apt/dists/focal-pgdg/main/binary-amd64/Packages.bz2

(related [ticket opened with GitHub Actions support][suptik])

**Area for Triage**:  

Databases
Packages

**Question, Bug, or Feature?**:  

Bug

**Virtual environments affected**  
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [x] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Image version**

  Environment: ubuntu-20.04
  Version: 20210510.0

**Expected behavior**  

`apt-get` should successfully install `postgresql-server-dev-13` from the same repo that the already installed PostgreSQL 13 server came from.

**Actual behavior**  

`apt-get` reports `E: Unable to locate package postgresql-server-dev-13`

**Repro steps**  
A description with steps to reproduce the issue. If your have a public example or repo to share,
please provide the link.

Run the `ubuntu-latest`/`amd64` CI actions from [this branch][brnch].

[brnch]: https://github.com/tada/pljava/blob/bug/REL1_6_STABLE/issue352/.github/workflows/ci-runnerpg.yml
[suptik]: https://support.github.com/ticket/personal/0/1142305

**Comment by Darleev** [comment]
Hello @jcflack,
In order to keep our images safe from possible untrusted and harmful packages, we made a decision to remove all repositories except ubuntu default. In order to add PostgreSQL repository back please follow the steps below:
```
echo "deb $REPO_URL `lsb_release -cs`-pgdg main" | tee /etc/apt/sources.list.d/pgdg.list
apt update
```
It should help to resolve the issue. Could you please try to apply this solution in your workflow?
We are looking forward to your reply.

**Comment by Darleev** [comment]
@jcflack I'm going to close the issue.
In case of any questions, feel free to contact us.

**Comment by alv16106** [comment]
For anyone else stumbling upon this issue, I was able to install the packages I needed from postgre repository by doing this
```      # Add build package for psycog2
      - name: psycopg2 prerequisites
        shell: bash
        run: |
          curl https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
          echo "deb http://apt.postgresql.org/pub/repos/apt `lsb_release -cs`-pgdg main" | tee /etc/apt/sources.list.d/pgdg.list
          sudo apt update
          sudo apt install libpq-dev cmake -y 
```

**Comment by jcflack** [comment]
It took me a long time to get back to this, but Darleev's suggestion worked for me, and I did not need the additional step of fetching the key first.

That seems ok if it means the key is already in the image. I hope it does not mean the `apt-get` was done without signature checking. As I did not say `--allow-unauthenticated`, I should be confident it would simply fail without the key, right?
