### ISSUE TITLE
Cannot build Python C extensions on Windows

### ISSUE THREAD

**Issue by qwhelan** [actions/virtual-environments#34]
**Describe the bug**
The following standard build command for C extensions in Python fails for all Windows environments for all supported Python versions:
```
python setup.py build_ext --inplace
```
It appears that the appropriate versions of Microsoft Visual C++ are not installed/configured.

Please note that the correct MSVC++ version varies across Python versions; see [here](https://wiki.python.org/moin/WindowsCompilers) for specifics.

**Virtual environments affected**
- [ ] macOS 10.14
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [x] Windows Server 2016 R2
- [x] Windows Server 2019

**Expected behavior**
It should be possible to build Python C extensions in Windows virtual environments. For a Python build/test pipeline, this means selecting the correct version to use for a given Python version.

**Actual behavior**
This should be reproducible for any Python library with any C (or Cython) components on Windows. I encountered the issue while attempting to configure Github Actions for such a library that I maintain. An example of a failed build log is https://github.com/pydata/bottleneck/runs/240915673

1. Use the workflow file found here: https://github.com/pydata/bottleneck/commit/630a39884f66a52a24c470ec83b986606aca844f#diff-fd3c00174dcaf7b8a36765f1a3de6791
2. Build will fail at C compilation step  as the appropriate version of MS Visual C++ is not installed.
![Screenshot from 2019-10-05 13-55-10](https://user-images.githubusercontent.com/440095/66695523-79309080-ec77-11e9-9133-d97610180987.png)
3. When fixed, it should be possible to build Python C extensions on Windows.

**Comment by elprans** [comment]
This is specific for Python 3.5, since it lacks the code needed to find recent versions of VS properly.
https://bugs.python.org/issue30389.  I was able to make it work by monkey-patching `distutils._msvccompiler` with code from 3.7.

**Comment by qwhelan** [comment]
@elprans The example I gave has it failing on 2.7 as well

**Comment by elprans** [comment]
@qwhelan Yea, 2.7 is a different story. It requires a very specific version of the MSVC compiler.

**Comment by ethanhs** [comment]
It seems now I get issues during link time like https://github.com/ethanhs/pynanosvg/runs/395962346

**Comment by miketimofeev** [comment]
Ho @qwhelan Is that bug still actual for you?

**Comment by qwhelan** [comment]
@miketimofeev I switched back to another provider for Windows-based testing due to this bug, so can't say. There doesn't seem to be anyone suggesting this is fixed.

**Comment by miketimofeev** [comment]
@qwhelan Closing this for now in that case. Feel free to reopen if you have any concerns.
Thank you!
