### ISSUE TITLE
Update macOS 10.15 to include XCode 12.5

### ISSUE THREAD

**Issue by ramtechjoe** [actions/virtual-environments#3406]
**Tool information**
- Tool name:  macOS 10.15 virtual environment

**Area for Triage**:

**Question**:
Will XCode 12.5 be added to the macOS 10.15 image?  macOS 11.0 cannot be used with Azure DevOps Pipeline so builds that require XCode 12.5 fail

**Virtual environments affected**
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [x] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Comment by al-cheb** [comment]
Hi, @ramtechjoe 
Xcode 12.5 requires a Mac running **macOS Big Sur 11 or later** - https://developer.apple.com/documentation/xcode-release-notes/xcode-12_5-release-notes

**Comment by ramtechjoe** [comment]
Thank you for reply and clarification.  I guess the issue is really Azure DevOps PIpeline not supporting macOS 11.0.

**Comment by Darleev** [comment]
Hello @ramtechjoe,
There is a [similar request](https://github.com/actions/virtual-environments/issues/2072) regarding macOS 11 for Azure DevOps, you can follow up current status in it.
In case of any questions, feel free to contact us.

**Comment by ramtechjoe** [comment]
Thank you, I also have opened an with MS about supporting macOS 11.0 from Azure DevOps Pipeline.  Right now I am running a self hosted build agent, which works, but I would not consider a good long term solution

**Comment by Darleev** [comment]
@ramtechjoe I'm going to close the issue for now.
If additional or assistance is required, do not hesitate to contact us.
