### ISSUE TITLE
Github Actions stuck in Queued status

### ISSUE THREAD

**Issue by sachingade20** [actions/virtual-environments#3409]
**Description**  
Github Actions stuck in Queued status. it was working hour back but stuck from last 2 hours. all jobs  are same status.

**Area for Triage**:  

**Question, Bug, or Feature?**:  
Bug

**Virtual environments affected**  
 Environment: ubuntu-20.04

**Image version**

 runner version: '2.278.0'
 Environment: ubuntu-20.04
 Version: 20210510.0

**Expected behavior**  
Actions  should start running jobs which builds and pushes builds.

**Actual behavior**  
Github Actions stuck in Queued status. it was working hour back but stuck from last 2 hours. all jobs  are same status.

**Repro steps**  
1. Commit code to repo branch
2.   Actions gets triggered
3.  Job  stuck in Queued

**Comment by miketimofeev** [comment]
@sachingade20 there is an active incident https://www.githubstatus.com/incidents/m16jzl31gnqt 
You can track the resolution there.
