### ISSUE TITLE
Github actions has encountered an internal error when running your job

### ISSUE THREAD

**Issue by GabyCT** [actions/virtual-environments#3412]
**Description**  
While running github actions, I got the following error
```
Github Actions has encountered an internal error when running your job.
```

**Area for Triage**:  

Go

**Question, Bug, or Feature?**:  

Bug

**Virtual environments affected**  
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [X] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Expected behavior**  
All tests should pass.

**Actual behavior**  
GitHub Actions has encountered an internal error when running your job.

**Repro steps**  
A description with steps to reproduce the issue. If your have a public example or repo to share,
please provide the link.

1. Submitted a PR to this repository https://github.com/kata-containers/tests/pull/3542
2. Github actions will be triggered and you will get the error

**Comment by abitmore** [comment]
Same here https://github.com/bitshares/awesome-bitshares/actions/runs/843439724

**Comment by sio** [comment]
Same here: https://github.com/sio/homelab/actions/runs/854159795

**Comment by Darleev** [comment]
Hello,
There was an active incident https://www.githubstatus.com/incidents/m16jzl31gnqt
You can track the resolution there.
In case of any questions feel free to contact us.
