### ISSUE TITLE
Update rustup to v1.24.2

### ISSUE THREAD

**Issue by hkratz** [actions/virtual-environments#3418]
**Tool information**
- Tool name: rustup
- Tool license: Apache 2.0 /MIT
- Add or update? Update
- Desired version: v1.24.2
- Approximate size: 
- If this is an add request:
  - Brief description of tool: Updates/installs Rust toolchains.
  - URL for tool's homepage: https://github.com/rust-lang/rustup
  - Provide a basic test case to validate the tool's functionality: 

**Area for Triage**:

**Question, Bug, or Feature?**:
Rustup has had an issue causing intermittent OOMs on Windows installations. The new release fixes that, see [changelog](https://github.com/rust-lang/rustup/blob/master/CHANGELOG.md).

**Virtual environments affected**
- [X] Ubuntu 16.04
- [X] Ubuntu 18.04
- [X] Ubuntu 20.04
- [X] macOS 10.15
- [X] macOS 11.0
- [X] Windows Server 2016 R2
- [X] Windows Server 2019

**Can this tool be installed during the build?**

**Tool installation time in runtime**

**Are you willing to submit a PR?**

**Comment by Darleev** [comment]
Hello @hkratz,
Rustup v.1.24.2 will be delivered to all the images by the end of next week.
I'll keep you updated.

**Comment by JohnTitor** [comment]
FYI: Rustup v1.24.3 is upcoming along with https://github.com/rust-lang/rustup/pull/2779 and we might want to wait for the release.

**Comment by SONJAYA80026** [comment]
evaluate.py

**Comment by Darleev** [comment]
@JohnTitor Rustup has been updated, feel free to verify it.
I'm going to close the issue.
In case of any questions, feel free to contact us.
