### ISSUE TITLE
Any base image other than the cached ones fail on docker for windows

### ISSUE THREAD

**Issue by jelmansouri-legion** [actions/virtual-environments#3422]
**Description**  
If you base a container on a base image other than the cached on, for example mcr.microsoft.com/windows/servercore:20H2.
docker fails with the following error:

> no matching manifest for windows/amd64 10.0.17763 in the manifest list entries

**Area for Triage**:  

**Question, Bug, or Feature?**:  

Bug

**Virtual environments affected**  
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016 R2
- [x] Windows Server 2019

**Image version**

Image version where you are experiencing the issue.
Microsoft Windows Server 2019
  10.0.17763
  Datacenter
 Environment: windows-2019
  Version: 20210509.1
  Included Software: https://github.com/actions/virtual-environments/blob/win19/20210509.1/images/win/Windows2019-Readme.md
  Image Release: https://github.com/actions/virtual-environments/releases/tag/win19%2F20210509.1

**Expected behavior**  
The proper base image to be pulled, or a documented reason why it will not

**Actual behavior**  
Just errors out with:
> no matching manifest for windows/amd64 10.0.17763 in the manifest list entries

**Repro steps**  
A description with steps to reproduce the issue. If your have a public example or repo to share,
please provide the link.

build the following image on the virtual environment:

```dockerfile
FROM mcr.microsoft.com/windows/servercore:20H2

RUN echo "hello"
```

**Comment by Darleev** [comment]
Hello @jelmansouri-legion,
Could you please try to use `FROM mcr.microsoft.com/windows/servercore:20H2-amd64` image?

**Comment by jelmansouri-legion** [comment]
I'm guessing the error above is what should have been displayed in the first place?

**Comment by Darleev** [comment]
@jelmansouri-legion I'm going to close the issue. In case of any questions feel free to contact us.

**Comment by jelmansouri-legion** [comment]
Thanks @Darleev !
