### ISSUE TITLE
Provide Android build-tools 31.0.0-rc4 for Ubuntu and Windows

### ISSUE THREAD

**Issue by colintheshots** [actions/virtual-environments#3423]
**Tool information**
- Tool name: Android build-tools 31.0.0-rc4
- Add or update? Update
- Desired version: 31.0.0-rc4 (31.x versions are required by the latest stable Android Gradle Plugin)

**Virtual environments affected**
- [x] Ubuntu 16.04
- [x] Ubuntu 18.04
- [x] Ubuntu 20.04
- [?] macOS 10.15
- [?] macOS 11
- [x] Windows Server 2016 R2
- [x] Windows Server 2019

**Can this tool be installed during the build?**
yes | ./sdkmanager --install "build-tools;31.0.0-rc4"

**Tool installation time in runtime**
Less than a minute

**Are you willing to submit a PR?**
Yes

**Comment by colintheshots** [comment]
This looks like the current code's pattern recognition simply doesn't see 31.0.0-rc4 as a valid pattern. I'll submit a PR to match these.

**Comment by Darleev** [comment]
Hello, @colintheshots,
Thank you for your contribution.
However, at this time we only install a stable version of Android tools on our agents. So, it is required to wait until the stable 31.0.0 version will be released.

**Comment by colintheshots** [comment]
Oh, it seems I misread a message in my IDE. It said, "The specified Android SDK Build Tools version (30.0.0) is ignored, as it is below the minimum supported version (30.0.2) for Android Gradle Plugin 4.2.1.
Android SDK Build Tools 30.0.2 will be used."

So I didn't actually need the RC version to run the stable AGP 4.2.0 as it seemed from the messages at first. Nevermind.
