### ISSUE TITLE
Support for Docker Images

### ISSUE THREAD

**Issue by heroku-miraheze** [actions/virtual-environments#3428]
**Breaking changes**
Docker Images will be published at 27/05/2021 in Microsoft organization, at Docker Hub.

**Target date**
27/05/2021

**The motivation for the changes**
Because of #1153, all docker images will be published in Microsoft organization, at Docker Hub.

**Possible impact**
All docker images, such as Ubuntu 20.04, etc, will be published in Microsoft organization, at Docker Hub.

The following docker images will be available in Docker Hub:
* Ubuntu 16.04
* Ubuntu 18.04
* Ubuntu 20.04
* Windows Server 2016 R2
* Windows Server 2019

**Virtual environments affected**
- [x] Ubuntu 16.04
- [x] Ubuntu 18.04
- [x] Ubuntu 20.04
- [ ] macOS 10.13
- [ ] macOS 10.14
- [ ] macOS 10.15
- [ ] macOS 11
- [x] Windows Server 2016 R2
- [x] Windows Server 2019

**Mitigation ways**
Done.

**Comment by Darleev** [comment]
Hello @heroku-miraheze,
It's not clear from the initial message what do you mean In your request. Could you please add more details?
We are looking forward to your reply.

**Comment by heroku-miraheze** [comment]
I have added more details.

**Comment by heroku-miraheze** [comment]
@Darleev

**Comment by catthehacker** [comment]
This seems like you want @actions team to publish Docker images of `virtual-environments` to Docker Hub?

**Comment by heroku-miraheze** [comment]
Ok, but some pre-installed software will not be included.

**Comment by AlenaSviridenko** [comment]
@heroku-miraheze , do you mean that you want to publish images built based on our repo to Docker Hub?

**Comment by heroku-miraheze** [comment]
Yes.

**Comment by maxim-lobanov** [comment]
Unfortunately, We don't have plans to maintain the separate "reduced" image for publishing to DockeHub for now. See details in #176

**Comment by AlenaSviridenko** [comment]
Please, feel free to build them and push on your behalf. But I have to mention that we won't be able to support them from our side.

**Comment by heroku-miraheze** [comment]
OK.
