### ISSUE TITLE
Update/Add [mint]

### ISSUE THREAD

**Issue by mrgrauel** [actions/virtual-environments#343]
**Tool information**
- Tool name: Mint
- Add or update? Add
- Desired version: .13
- Approximate size: 
- If this is an add request:
  - Brief description of tool: A package manager that installs and runs Swift command line tool packages.
  - URL for tool's homepage: https://github.com/yonaskolb/Mint

**Area for Triage**:

**Question, Bug, or Feature?**:
It's very useful for swift packages like `SwiftLint` or `xcodegen` to install as dependencies. With a local `Mintfile` it's possible to pin it to a defined version.

**Virtual environments affected**
- [x] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Can this tool be installed during the build?**
`brew install mint`

**Are you willing to submit a PR?**
I'd but have no experience with the virtual environments for Github Actions.

**Comment by maxim-lobanov** [comment]
Tool can be installed in runtime using the following script:
```
brew install mint
```
Installation takes about 12 seconds

**Comment by alepauly** [comment]
hi @mrgrauel, considering that installing `mint` is fast on demand, we won't be adding it to the image at this time. thanks for the suggestion.

**Comment by miketimofeev** [comment]
@irgaly please consider using a setup-action https://github.com/marketplace/actions/setup-mint — it takes about 1s to install mint in runtime.
Actions is a recommended way to install a piece of software.

**Comment by irgaly** [comment]
setup-mint is for mint lang https://github.com/mint-lang/mint .

Swift command package manager is not mint-lang.
https://github.com/yonaskolb/Mint

**Comment by irgaly** [comment]
I published setup-mint action for Mint Swift Package Manager 🎉 

https://github.com/marketplace/actions/setup-mint-swift-package-manager

**Comment by miketimofeev** [comment]
@irgaly great! Thank you for your efforts!
