### ISSUE TITLE
Visual Studio build failed "Error MSB4041: The default XML namespace of the project must be the MSBuild XML namespace"

### ISSUE THREAD

**Issue by shawnz88** [actions/virtual-environments#3430]
**Description**  

Self-hosted Windows 2019 agent based on image version 20210516.0 gives the following error when building a project:

Starting: Build solution **\*.sln
==============================================================================
Task         : Visual Studio build
Description  : Build with MSBuild and set the Visual Studio version property
Version      : 1.183.0
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/build/visual-studio-build
==============================================================================
"C:\a\_tasks\VSBuild_71a9a2d3-a98a-4caa-96ab-affca411ecda\1.183.0\ps_modules\MSBuildHelpers\vswhere.exe" -version [16.0,17.0) -latest -format json
"C:\a\_tasks\VSBuild_71a9a2d3-a98a-4caa-96ab-affca411ecda\1.183.0\ps_modules\MSBuildHelpers\vswhere.exe" -version [16.0,17.0) -products Microsoft.VisualStudio.Product.BuildTools -latest -format json
"C:\a\_tasks\VSBuild_71a9a2d3-a98a-4caa-96ab-affca411ecda\1.183.0\ps_modules\MSBuildHelpers\vswhere.exe" -version [15.0,16.0) -latest -format json
"C:\a\_tasks\VSBuild_71a9a2d3-a98a-4caa-96ab-affca411ecda\1.183.0\ps_modules\MSBuildHelpers\vswhere.exe" -version [15.0,16.0) -products Microsoft.VisualStudio.Product.BuildTools -latest -format json
##[warning]Visual Studio was not found. Try installing a supported version of Visual Studio. See the task definition for a list of supported versions.
##[warning]Unable to find MSBuild version '14.0' for architecture 'x86'. Falling back to version '4.0'.
"C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe" "C:\a\1\s\BearerTokenRetrieve.sln" /nologo /nr:false /dl:CentralLogger,"C:\a\_tasks\VSBuild_71a9a2d3-a98a-4caa-96ab-affca411ecda\1.183.0\ps_modules\MSBuildHelpers\Microsoft.TeamFoundation.DistributedTask.MSBuild.Logger.dll";"RootDetailId=3ae0aa00-b7cf-48a7-a6c1-274e07ae7fbd|SolutionDir=C:\a\1\s"*ForwardingLogger,"C:\a\_tasks\VSBuild_71a9a2d3-a98a-4caa-96ab-affca411ecda\1.183.0\ps_modules\MSBuildHelpers\Microsoft.TeamFoundation.DistributedTask.MSBuild.Logger.dll"  /p:platform="any cpu" /p:configuration="release" /p:_MSDeployUserAgent="VSTS_98303c26-7eb0-4b02-96b4-1e5861ecad4c_build_9344_0"
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
Build started 5/20/2021 4:15:09 PM.
Project "C:\a\1\s\BearerTokenRetrieve.sln" on node 1 (default targets).
ValidateSolutionConfiguration:
  Building solution configuration "release|any cpu".
##[error]BearerTokenRetrieve\BearerTokenRetrieve.csproj(1,1): Error MSB4041: The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.
Project "C:\a\1\s\BearerTokenRetrieve.sln" (1) is building "C:\a\1\s\BearerTokenRetrieve\BearerTokenRetrieve.csproj" (2) on node 1 (default targets).
C:\a\1\s\BearerTokenRetrieve\BearerTokenRetrieve.csproj(1,1): error MSB4041: The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.
Done Building Project "C:\a\1\s\BearerTokenRetrieve\BearerTokenRetrieve.csproj" (default targets) -- FAILED.
Done Building Project "C:\a\1\s\BearerTokenRetrieve.sln" (default targets) -- FAILED.

Build FAILED.

"C:\a\1\s\BearerTokenRetrieve.sln" (default target) (1) ->
"C:\a\1\s\BearerTokenRetrieve\BearerTokenRetrieve.csproj" (default target) (2) ->
  C:\a\1\s\BearerTokenRetrieve\BearerTokenRetrieve.csproj(1,1): error MSB4041: The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.

    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:01.40
##[error]Process 'msbuild.exe' exited with code '1'.
Finishing: Build solution **\*.sln

**Area for Triage**:  
.NET Framework

**Question, Bug, or Feature?**:  
Bug

**Virtual environments affected**  
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016 R2
- [x] Windows Server 2019

**Image version**
20210516.0

**Expected behavior**  
Visual Studio build of a netstandard2.0 project should succeed.

**Actual behavior**  
Visual Studio build of a netstandard2.0 project failed with warning message "Visual Studio was not found" and error message MSB4041.

**Repro steps**  
Build a Visual Studio project with targetframework netstandard2.0

**Comment by maxim-lobanov** [comment]
@shawnz88 , does this project build successfully on your local box with Visual Studio 2019?
Have you tried to reproduce the issue on Hosted runners?

Based on `Unable to find MSBuild version '14.0' for architecture 'x86'. Falling back to version '4.0'.`, looks like that [Visual Studio build](https://github.com/microsoft/azure-pipelines-tasks/tree/master/Tasks/VSBuildV1) task can't find installed Visual Studio properly. I suggest the following approach to debug it:
- Login to self-hosted VM manually and try building project in Visual Studio directly
- If it works - most likely, the issue is related to VSBuild task and should be reported to https://github.com/microsoft/azure-pipelines-tasks
- If it doesn't work - suggest rebuild self-hosted agent to make sure that Visual Studio is installed properly

**Comment by shawnz88** [comment]
The project builds successfully with Visual Studio 2019 locally or on MS hosted Windows agents. Will try to rebuild the self-hosted agent.

**Comment by shawnz88** [comment]
From the VHD build log, Visual Studio was installed properly. Once the VHD was built and converted to managed image and then attached to VM scale set, the post-generation scripts never got a chance to run. Is that the reason why Visual Studio can't be found?

**Comment by shawnz88** [comment]
Run $Env:Path from self-hosted Windows2019 agent on VMSS returns this:

C:\agent\externals\git\cmd;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Users\AzDevOps\AppData\Local\Microsoft\WindowsApps


Run $Env:Path from Microsoft hosted Windows2019 agent returns this:

C:\agents\2.186.1\externals\git\cmd;C:\Users\VssAdministrator\.dotnet\tools;C:\Program Files\MongoDB\Server\4.4\bin;C:\aliyun-cli;C:\vcpkg;C:\cf-cli;C:\Program Files (x86)\NSIS\;C:\tools\zstd;C:\Program Files\Mercurial\;C:\hostedtoolcache\windows\stack\2.7.1\x64;C:\tools\ghc-9.0.1\bin;C:\Program Files\dotnet;C:\mysql-5.7.21-winx64\bin;C:\Program Files\R\R-4.0.5\bin\x64;C:\SeleniumWebDrivers\GeckoDriver;C:\Program Files (x86)\sbt\bin;C:\Rust\.cargo\bin;C:\Program Files (x86)\GitHub CLI;C:\Program Files\Git\bin;C:\Program Files (x86)\pipx_bin;C:\hostedtoolcache\windows\go\1.15.12\x64\bin;C:\hostedtoolcache\windows\Python\3.7.9\x64\Scripts;C:\hostedtoolcache\windows\Python\3.7.9\x64;C:\hostedtoolcache\windows\Ruby\2.5.9\x64\bin;C:\hostedtoolcache\windows\Java_Adopt_jdk\8.0.292-10\x64\bin;C:\npm\prefix;C:\Program Files\Microsoft SDKs\Azure\Azure Dev Spaces CLI;C:\Program Files\Microsoft SDKs\Azure\Azure Dev Spaces CLI\;C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin;C:\ProgramData\kind;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\ProgramData\Chocolatey\bin;C:\Program Files\Microsoft\Web Platform Installer\;C:\Program Files\Docker;C:\Program Files\PowerShell\7\;C:\Program Files\dotnet\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\;C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\;C:\Program Files (x86)\Microsoft SQL Server\110\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\120\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\130\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\140\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\150\DTS\Binn\;C:\Program Files\nodejs\;C:\ProgramData\chocolatey\lib\pulumi\tools\Pulumi\bin;C:\ProgramData\chocolatey\lib\maven\apache-maven-3.8.1\bin;C:\Program Files\Microsoft Service Fabric\bin\Fabric\Fabric.Code;C:\Program Files\Microsoft SDKs\Service Fabric\Tools\ServiceFabricLocalClusterManager;C:\Program Files\OpenSSL\bin;C:\Strawberry\c\bin;C:\Strawberry\perl\site\bin;C:\Strawberry\perl\bin;C:\Program Files\Git\cmd;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;c:\tools\php;C:\Program Files (x86)\sbt\bin;C:\Program Files\TortoiseSVN\bin;C:\SeleniumWebDrivers\ChromeDriver\;C:\SeleniumWebDrivers\EdgeDriver\;C:\Program Files\CMake\bin;C:\Program Files\Amazon\AWSCLIV2\;C:\Program Files\Amazon\SessionManagerPlugin\bin\;C:\Program Files\Amazon\AWSSAMCLI\bin\;C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\bin;C:\Program Files (x86)\Microsoft BizTalk Server\;C:\Users\VssAdministrator\AppData\Local\Microsoft\WindowsApps

**Comment by shawnz88** [comment]
It turned out that the wrong VHD was being used.
