### ISSUE TITLE
Update GitHub CLI to v1.10.0

### ISSUE THREAD

**Issue by simar7** [actions/virtual-environments#3431]
**Tool information**
- Tool name: GitHub CLI
- Tool license: MIT
- Add or update? Update
- Desired version: v1.10.0 https://github.com/cli/cli/releases/tag/v1.10.0
- Approximate size: 
- If this is an add request:
  - Brief description of tool: GitHub CLI
  - URL for tool's homepage: 
  - Provide a basic test case to validate the tool's functionality: 
  ```gh repo view --json defaultBranchRef --jq .defaultBranchRef.name)```

**Question, Bug, or Feature?**:
Upgrade the existing tool to version v1.10.0 which includes the --json flag

**Virtual environments affected**
- [x] Ubuntu 16.04
- [x] Ubuntu 18.04
- [x] Ubuntu 20.04
- [x] macOS 10.15
- [x] macOS 11
- [x] Windows Server 2016 R2
- [x] Windows Server 2019

**Can this tool be installed during the build?**
No

**Tool installation time in runtime**
The same as now.

**Are you willing to submit a PR?**
Yes

**Comment by Darleev** [comment]
Hello @simar7,
Github CLI will be updated to version v.1.10.2 by the end of the next week.
I'll keep you informed.

**Comment by Darleev** [comment]
@simar7 Github CLI has been updated.
I'm going to close the issue.
