### ISSUE TITLE
apt-get appears to intermittently fail for some github actions

### ISSUE THREAD

**Issue by senhuang42** [actions/virtual-environments#3433]
**Description**  
Getting a 404 error when trying to `apt-get` a package. I am able to locally `apt-get` the package, as well as download it directly from the browser, but it seems like the github-actions is failing.

**Area for Triage**:  
Containers

**Bug**
`E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/main/c/ceph/librados2_15.2.8-0ubuntu0.20.04.1_amd64.deb  404  Not Found [IP: 52.250.76.244 80]`
**Virtual environments affected**  
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [x] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Image version**
2.278.0

**Expected behavior**  
Expect apt-get to work.

**Actual behavior**  
`E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/main/c/ceph/librados2_15.2.8-0ubuntu0.20.04.1_amd64.deb  404  Not Found [IP: 52.250.76.244 80]`

**Repro steps**  
Multiple runs on the `github.com/facebook/zstd` repository.
Example 1: https://github.com/facebook/zstd/pull/2680/checks?check_run_id=2641161932
Example 2: https://github.com/facebook/zstd/pull/2678/checks?check_run_id=2640942661

**Comment by catthehacker** [comment]
Run `apt-get update` before since index cache is not updated automatically.

**Comment by maxim-lobanov** [comment]
Yes, please follow this documentation if we would like to install any packages in runtime: https://docs.github.com/en/actions/using-github-hosted-runners/customizing-github-hosted-runners#installing-software-on-ubuntu-runners

**Comment by maxim-lobanov** [comment]
Closing the issue since no response.
