### ISSUE TITLE
Update zstd to v1.5.0

### ISSUE THREAD

**Issue by smorimoto** [actions/virtual-environments#3435]
https://github.com/facebook/zstd/releases/tag/v1.5.0

**Comment by dibir-magomedsaygitov** [comment]
Hello @smorimoto. We are trying to install latest available version of zstd. Windows Images are already with zstd 1.5.0 on board and Ubuntu/macOS images will be updated with this week's rollout. I'll post an update message.

**Comment by smorimoto** [comment]
Great! Once it's done, we can make changes to the official actions for it.

**Comment by dibir-magomedsaygitov** [comment]
Hello @smorimoto. Zstd 1.5.0 is available across all images now. I'm going to close this issue. In case of any questions feel free to contact us. Thank you.

**Comment by smorimoto** [comment]
Great thanks!
