### ISSUE TITLE
Add Android SDK/NDK

### ISSUE THREAD

**Issue by larvacea** [actions/virtual-environments#344]
**Tool information**
- Tool name: Android SDK and NDK
- Add or update? Add
- Desired version: Android SDK 29.0.1, NDK 21.0.6113669
- Approximate size: 
- If this is an add request:
  - Brief description of tool: The full SDK/NDK combination is required to build and test (via the Android Emulator) for Android.
  - URL for tool's homepage: 

**Area for Triage**:
Android

**Question, Bug, or Feature?**:
Feature

**Virtual environments affected**
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [X ] Windows Server 2019

**Can this tool be installed during the build?**
I have no idea; I'm now looking into building a Docker image.

**Are you willing to submit a PR?**
Possibly, if you can suggest a starting point.

**Comment by hannesa2** [comment]
I want to have the desired version: Android SDK 29.0.1, NDK 21.0.6113669 too

But I don't know if this it the solution https://github.com/actions/virtual-environments/pull/169 ?
Does some one knows it ?

**Comment by NotMoni** [comment]
I an also having this issue.

**Comment by larvacea** [comment]
You can arrange to download the SDK and NDK versions you want. You can download sdkmanager from the source of your choice, and then use it to download the components (such as SDK and NDK) that you need. Afaik, you will not be able to run the Android emulator in a GitHub runner VM, but you certainly can gradle-build both Java and C++ into APK or AAR, as you prefer, and you can run Java-only unit-tests (what Android documentation calls a "unit test" as opposed to an "instrumented test") in the VM.

If you want a simple solution, I like [Chocolatey](https://chocolatey.org/).

If you need instrumented tests, Google does offer testing in their Firebase Test product (and they offer a free subscription for a limited number of tests per day). It's fairly straightforward to set it up and run tests, at least when I tried it on my code.

Hope this helps. I'm sorry to say that the project I've been using this on is not yet public, so I don't have examples to share.

**Comment by NotMoni** [comment]
Oh, thanks. I will test and let you know.

**Comment by Darleev** [comment]
@NotMoni @larvacea @hannesa2 Hello,
Let me provide you steps to install desired versions of Android SDK/NDK in runtime:
```
"$ANDROID_HOME/tools/bin/sdkmanager.bat" "build-tools;29.0.1"
"$ANDROID_HOME/tools/bin/sdkmanager.bat" --install "ndk;21.0.6113669"
```
In the meantime, I will prepare a PR to add these versions to Windows images.

**Comment by NotMoni** [comment]
Alright

**Comment by Darleev** [comment]
@larvacea we have added Android SDK 29.0.1 and latest NDK to Windows image and it will be rolled out next week. 
In case of any questions, please let us know.

**Comment by NotMoni** [comment]
this action seems to solve it for me.

```yml
 
name: Android CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Unit tests
      run: bash ./gradlew test --stacktrace
```

**Comment by Darleev** [comment]
I'm going to close the issue since the initial packages were successfully added to the agents.

Let us know in case of any questions.

**Comment by NotMoni** [comment]
Alright.

**Comment by hannesa2** [comment]
@NotMoni 
I can't confirm this is working
```
jobs:
  build:

    runs-on: ubuntu-latest
```

What I tested to see if NDK is included
* `runs-on: ubuntu-latest` 👎 
* `runs-on: ubuntu-20.04` 👎 
* `runs-on: macOS-latest` ✅
