### ISSUE TITLE
Environment variables: Add ImageOS companion to ImageVersion 

### ISSUE THREAD

**Issue by MSP-Greg** [actions/virtual-environments#345]
This request is suggested as a means of simplifying the inputs needed to some actions.

In https://github.com/actions/virtual-environments/tags, new images are tagged as below:
```
win16/20200120.1
ubuntu18/20200119.1
 ```

ImageVersion is the second part of the tag.  Having the first part of the tag ('OS String') set to an environment variable ImageOS would be helpful.  As to macOS, maybe just that?

One use is building separate packages/binaries for use on all platforms.  Obviously, one can use 'runs-on:' or '${{ matrix.os }}' as an action input, but having the image name as an env variable would be simpler...

Note: submitted to 'GitHub Community Forums', which was then closed with the suggestion to post to [Feedback form for GitHub Actions](https://support.github.com/contact/feedback?contact%5Bcategory%5D=actions), which I did.  I thought an issue might result in feedback/discussion...

**Comment by al-cheb** [comment]
Hello, @MSP-Greg 

To double check am i right it should be?

| Name  |ImageOS   | ImageVersion   | 
|---|---|---|
| Windows 2016  |win16   |  20200120.1 |
|  Windows Server 2019 |win19   | 20200120.1  |
| Ubuntu 16.04  |ubuntu16   | 20200120.1|
| Ubuntu 18.04  |ubuntu18   | 20200120.1|
| macOS Catalina 10.15  |macOS   | 20200120.1|

**Comment by MSP-Greg** [comment]
@al-cheb

Thanks.

Yes, that is what I intended.

Not sure about whether macOS needs any numeric suffix.  If so, maybe macOS10.15 or macOS1015 ?

**Comment by al-cheb** [comment]
Hello, @MSP-Greg 
We have added `ImageOS` for all GitHub images.
