### ISSUE TITLE
Az cli 2.24.0 break 'what-if' command

### ISSUE THREAD

**Issue by Jian-Huang-Dev** [actions/virtual-environments#3460]
Once az cli is updated to 2.24.0, then running 'az deployment sub what-if ..' command will get an error
**'str' object has no attribute 'value'**

**Bug**:  

**Image version**
All microsoft hosted agents with az cli 2.24.0 installed

**Expected behavior**  
If you choose a earlier version of az cli, for example 2.23.0, then the 'what-if' command runs successfully and gives you the expected results.

**Actual behavior**  
Got an error when running 'what-if' command - ERROR:**'str' object has no attribute 'value'**

note: running the command with 'create' is working fine, no issue. Such as 'az deployment sub create -f .. -p .. -l ..'

**Repro steps**  
Run az cli command such as 'az deployment sub what-if -f .. -p .. -l ..' with version 2.24.0 (latest as of writing)
Then you will get an error: **'str' object has no attribute 'value'**

**Comment by maxim-lobanov** [comment]
Hello @Jian-Huang-Dev , have you reported this issue to Azure CLI repo? https://github.com/Azure/azure-cli

**Comment by Jian-Huang-Dev** [comment]
not yet, I guess I opened the issue at the wrong location, I will open it in azure-cli repo, thanks @maxim-lobanov

**Comment by jwettstrom** [comment]
Not just what if is failing but also regular deployment quit working. Even a very simple resource group create failed. Worked before upgrade to latest 2.24.0

**Comment by mariuszdotnet** [comment]
@Jian-Huang-Dev  have you created this issue under the Azure CLI repo?  I can't find it.  My customer is experiencing the same issue with 2.24.0 release and 'what-if'

**Comment by Jian-Huang-Dev** [comment]
Hi Mariusz,

I did create one under azure cli repo 
https://github.com/Azure/azure-cli/issues/18248
