### ISSUE TITLE
Add Bicep

### ISSUE THREAD

**Issue by ljtill** [actions/virtual-environments#3461]
**Tool information**
- Tool name: Bicep
- Tool license: MIT
- Add or update? Add
- Desired version: Latest (v0.4.63)
- Approximate size: 40 MB
- If this is an add request:
  - Brief description of tool: Provides the ability to compile Bicep DSL into ARM Templates
  - URL for tool's homepage: https://github.com/Azure/bicep
  - Provide a basic test case to validate the tool's functionality: `bicep --help` / `bicep build main.bicep` 

**Area for Triage**:

**Can this tool be installed during the build?**

Yes

[Instructions - Linux](https://github.com/Azure/bicep/blob/main/docs/installing.md#linux)
```bash
# Fetch the latest Bicep CLI binary
curl -Lo bicep.bin https://github.com/Azure/bicep/releases/latest/download/bicep-linux-x64
# Mark it as executable
chmod +x ./bicep.bin
# Add bicep to your PATH (requires admin)
sudo mv ./bicep.bin /usr/local/bin/bicep
# Verify you can now access the 'bicep' command
bicep --help
```

[Instructions - macOS](https://github.com/Azure/bicep/blob/main/docs/installing.md#macos)
```bash
# Fetch the latest Bicep CLI binary
curl -Lo bicep https://github.com/Azure/bicep/releases/latest/download/bicep-osx-x64
# Mark it as executable
chmod +x ./bicep
# Add Gatekeeper exception (requires admin)
sudo spctl --add ./bicep
# Add bicep to your PATH (requires admin)
sudo mv ./bicep /usr/local/bin/bicep
# Verify you can now access the 'bicep' command
bicep --help
```

[Instructions - Windows](https://github.com/Azure/bicep/blob/main/docs/installing.md#windows)
```powershell
# Create the install folder
$installPath = "$env:USERPROFILE\.bicep"
$installDir = New-Item -ItemType Directory -Path $installPath -Force
$installDir.Attributes += 'Hidden'
# Fetch the latest Bicep CLI binary
(New-Object Net.WebClient).DownloadFile("https://github.com/Azure/bicep/releases/latest/download/bicep-win-x64.exe", "$installPath\bicep.exe")
# Add bicep to your PATH
$currentPath = (Get-Item -path "HKCU:\Environment" ).GetValue('Path', '', 'DoNotExpandEnvironmentNames')
if (-not $currentPath.Contains("%USERPROFILE%\.bicep")) { setx PATH ($currentPath + ";%USERPROFILE%\.bicep") }
if (-not $env:path.Contains($installPath)) { $env:path += ";$installPath" }
# Verify you can now access the 'bicep' command.
bicep --help
```

**Tool installation time in runtime**

Pre-compiled binary which can be downloaded (~40 MB) from GitHub Releases

**Are you willing to submit a PR?**

Yes

**Comment by AlenaSviridenko** [comment]
Hi @ljtill,
have you considered using one of these actions for Bicep setup:  [setup-bicep](https://github.com/marketplace/actions/setup-bicep), [bicep-build](https://github.com/marketplace/actions/bicep-build) ? 
Usually we recommend using actions instead of baking tools to the image, because it provides more flexibility and stability.

**Comment by AlenaSviridenko** [comment]
After some internal discussions, we decided not to install this tool to our images due to maintenance concerns and existing actions, which is the preferred way to interact with images. 

I am closing this issue. Please, feel free to contact us in case of any questions. Thanks.

**Comment by MarcusFelling** [comment]
@AlenaSviridenko - I would like to request that this gets re-opened. There should not be maintenance concerns or conflicts with existing actions. Bicep is production-ready and fully supported by Microsoft support plans as of the 0.3 release.

**Comment by al-cheb** [comment]
@ljtill , Bicep is on board.
