### ISSUE TITLE
GenerateResourcesAndImage reaches error that Connect-AzAccount is not recognized

### ISSUE THREAD

**Issue by norihiro** [actions/virtual-environments#3465]
**Description**  
Following [this instruction](https://github.com/actions/virtual-environments/blob/main/docs/create-image-and-azure-resources.md),
the script `helpers/GenerateResourcesAndImage.ps1` calls `Connect-AzAccount` but it is not found.

**Area for Triage**:  

I'm sorry, I'm not sure.

**Question, Bug, or Feature?**:  
Bug
Maybe documentation need to be updated how to install `Connect-AzAccount` or the script should be revised not to use `Connect-AzAccount`.

**Virtual environments affected**  
- [x] Ubuntu 16.04
- [x] Ubuntu 18.04
- [x] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [x] Windows Server 2016 R2
- [x] Windows Server 2019

**Image version**
n/a

**Expected behavior**  
The script `GenerateResourcesAndImage.ps1` successfully runs.

**Actual behavior**  
The script `GenerateResourcesAndImage.ps1` shows an error as below.
```
GenerateResourcesAndImage : The term 'Connect-AzAccount' is not recognized as the name of a cmdlet, function, script
file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct
and try again.
```

**Repro steps**  
A description with steps to reproduce the issue. If your have a public example or repo to share,
please provide the link.

1. Open a Windows PowerShell
2. Run these commands
   - `choco install packer`
   - `Invoke-WebRequest -Uri https://aka.ms/installazurecliwindows -OutFile .\AzureCLI.msi; Start-Process msiexec.exe -Wait -ArgumentList '/I AzureCLI.msi /quiet'; rm .\AzureCLI.msi`
   - `Set-Location c:\`
   - `git clone https://github.com/actions/virtual-environments.git`
   - `Set-Location C:\virtual-environments`
   - `Import-Module .\helpers\GenerateResourcesAndImage.ps1`
   - `GenerateResourcesAndImage -SubscriptionId {YourSubscriptionId} -ResourceGroupName "myTestResourceGroup" -ImageGenerationRepositoryRoot "$pwd" -ImageType Ubuntu1604 -AzureLocation "East US"`

**Comment by maxim-lobanov** [comment]
> Install Azure CLI - https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-windows?view=azure-cli-latest&tabs=azure-cli.

Looks like guide is incorrect. You should install Azure PowerShell instead of Azure CLI: https://docs.microsoft.com/en-us/powershell/azure/new-azureps-module-az?view=azps-6.0.0

**Comment by al-cheb** [comment]
@norihiro, I have created https://github.com/actions/virtual-environments/pull/3466 PR with a section how to install Az module.

**Comment by norihiro** [comment]
I checked `Apps & features` shows `Microsoft Azure CLI 2.24.0` but `Connect-AzAccount` is not found.
![azure-cli](https://user-images.githubusercontent.com/780600/119811762-6b01b780-bf22-11eb-84ff-12d111c67708.png)

**Comment by maxim-lobanov** [comment]
@norihiro `Azure CLI` != `Azure PowerShell`. It is two different tools. See updated guide: https://github.com/actions/virtual-environments/pull/3466/files

**Comment by norihiro** [comment]
Thanks @maxim-lobanov,
I can install Azure PowerShell by `Install-Module -Name Az -Scope CurrentUser -Repository PSGallery -Force` and now the command is found now.
Unfortunately I got another error below. It would be another problem I need to debug.
```
Set-AzContext : SharedTokenCacheCredential authentication failed: AADSTS9002332: Application
'1950a258-227b-4e31-a9cf-717495945fc2'(Microsoft Azure PowerShell) is configured for use by Azure Active Directory
users only. Please do not use the /consumers endpoint to serve this request.
```
