### ISSUE TITLE
[ubuntu] GCC and Gfortran 11 will be removed on May, 31

### ISSUE THREAD

**Issue by AlenaSviridenko** [actions/virtual-environments#3467]
**Breaking changes**
GCC and Gfortran 11 will be removed from Ubuntu images on May, 31 in the scope of https://github.com/actions/virtual-environments/pull/3436

**Target date**
Image deployment will start on May, 31 and will take 3-4 days.

**The motivation for the changes**
GCC 11 contains an experimental toolchain that is not compatible with older GCC versions, so it breaks existing workflows. More details can be found in the discussion https://github.com/actions/virtual-environments/discussions/3464

**Possible impact**
Projects that depends on GCC-11 features will be broken

**Virtual environments affected**
- [ ] Ubuntu 16.04
- [x] Ubuntu 18.04
- [x] Ubuntu 20.04
- [ ] macOS 10.13
- [ ] macOS 10.14
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Mitigation ways**
```
sudo apt-get update
sudo apt-get install g++-<version> -y

# For example, use this command to install gcc 11
sudo apt-get install g++-11 -y
```

```
sudo apt-get update
sudo apt-get install gfortran-<version> -y

# For example, use this command to install gfortran 11
sudo apt-get install gfortran-11 -y
```

**Comment by JCash** [comment]
Our executables currently link towards the erroneous `GLIBCXX_3.4.29`.
Since the rollout is 7 days away, do you have a workaround in the meantime?

**Comment by Milerius** [comment]
> Our executables currently link towards the erroneous `GLIBCXX_3.4.29`.
> Since the rollout is 7 days away, do you have a workaround in the meantime?

You can use 16.04 meanwhile this time - but today it's should already be solved

**Comment by MaksimZhukov** [comment]
The deployment was completed. GCC and Gfortran 11 were removed from Ubuntu images
