### ISSUE TITLE
Add Snapcraft

### ISSUE THREAD

**Issue by MateusAmin** [actions/virtual-environments#3468]
**Tool information**
- Tool name: snapcraft
- Tool license: GPL 3.0
- Add or update? Add

- Approximate size:  74 MB
- If this is an add request:
  - Brief description of tool:  This tool is used to create snaps!
  - URL for tool's homepage: https://snapcraft.io/
  - Provide a basic test case to validate the tool's functionality:
 
```sh
# Install Snapcraft
sudo snap install snapcraft --classic
sudo snap install lxd
sudo lxd init --auto

# Use Snapcraft
mkdir snapcraft-test-delete-me
cd snapcraft-test-delete-me

snapcraft init
snapcraft --use-lxd # Using lxd because no kvm access.
```

**Area for Triage**:
Packages

**Question, Bug, or Feature?**:
Feature

**Virtual environments affected**
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [x] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Can this tool be installed during the build?**
It is hard and [buggy](https://github.com/samuelmeuli/action-snapcraft/issues/30). Tried to do it in-build to reuse local scripts but could not get it installed.

Currently, this forces me to use an action and maintain a fork between local and CI.

**Tool installation time in runtime**
Fast

**Are you willing to submit a PR?**
Yes, if you give me some pointers.

**Comment by AlenaSviridenko** [comment]
Hi @MateusAmin,
due to maintenance concerns, we'd rather not to add this tool to the images. Instead, consider using action for it: [snapcraft-action](https://github.com/marketplace/actions/snapcraft-action), it seems pretty popular and high rated. Actions are always a recommended way to interact with images, because it provides more stability and flexibility.

I am going to close this issue. Please, let me know if you have any concerns. Feel free to contact us in case of any questions.
Thanks!

**Comment by MateusAmin** [comment]
Hi @AlenaSviridenko, thanks for taking a look.

No big concerns, like you said there is a workaround. And I can always maintain an extended image and runner down the line. I try to avoid running actions so that local runs the same code as the ci.

Turns out after looking through my logs my first run worked. Not sure how I missed that... For anyone that finds this these cmds will work find in the ubuntu 20.04 image.

``sh
sudo snap install snapcraft --classic
sudo snap install lxd
sudo lxd init --auto

sudo snapcraft snap --use-lxd --output linux.snap
```
