### ISSUE TITLE
[ubuntu] Error 404 while running apt-get command

### ISSUE THREAD

**Issue by NicoG60** [actions/virtual-environments#3469]
**Description**  
One of my workflow runs the following command:
```
sudo apt install -y \
    qtbase5-dev \
    libqt5websockets5-dev \
    libqt5svg5-dev \
    qtdeclarative5-dev \
    libqt5x11extras5-dev \
    libqt5opengl5-dev \
    qt5-gtk-platformtheme
```
Nothing fancy, just packages available in official repos.
The command fails with the following message:
```
E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/libx/libx11/libx11-xcb-dev_1.6.4-3ubuntu0.3_amd64.deb  404  Not Found [IP: 52.252.75.106 80]
```

I experienced a similar error 1 day ago. same workflow, same runner version, slightly different ip address:
```
E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/libx/libx11/libx11-xcb-dev_1.6.4-3ubuntu0.3_amd64.deb  404  Not Found [IP: 52.147.219.192 80]
```

Both runs were billed 46s each. Not that it makes a huge difference at the end of the month but still fills a bit unfair as it looks like a very common thing.

**Area for Triage**:  
Scripting and command line

**Question, Bug, or Feature?**:  
Bug

**Virtual environments affected**  
- [ ] Ubuntu 16.04
- [x] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Image version**
```
Environment: ubuntu-18.04
Version: 20210524.1
Included Software: https://github.com/actions/virtual-environments/blob/ubuntu18/20210524.1/images/linux/Ubuntu1804-README.md
Image Release: https://github.com/actions/virtual-environments/releases/tag/ubuntu18%2F20210524.1
```

**Expected behavior**  
The command runs normally.

**Actual behavior**  
The command fails.

**Repro steps**  
1. run the command above.

**Comment by maxim-lobanov** [comment]
@NicoG60 Have you tried to run `sudo apt-get update` before running install?
You should run apt-get update according to the GItHub Actions documentation https://docs.github.com/en/actions/using-github-hosted-runners/customizing-github-hosted-runners#installing-software-on-ubuntu-runners

**Comment by NicoG60** [comment]
I didn't and I'm an idiot!
Thanks for that and apologies 🙇‍♂️
