### ISSUE TITLE
PHP Extension pcov is broken on Azure Pipeline

### ISSUE THREAD

**Issue by sylfabre** [actions/virtual-environments#3470]
**Description**  
The PR https://github.com/actions/virtual-environments/pull/3405/files#diff-95ffb9615f2b3417624ab00cf732ddb0ef86f44d8872bb35ab729001179abaffR83 makes it impossible to use pcov as it removes the content of the configuration file `/etc/php/$version/mods-available/pcov.ini`

This configuration file is to be copied to `/etc/php/$version/[cli|apache2|fpm|...]/conf.d/` to enable the extension.
And the file from `/etc/php/$version/[cli|apache2|fpm|...]/conf.d/` is to be removed to disable the extension.
Or use `phpenmod` and `phpdismod` (https://tecadmin.net/enable-disable-php-modules-ubuntu/) as `php-common` is available

=> Removing the content of /etc/php/$version/mods-available/pcov.ini is a very bad way to disable the extension...

Anyway, pcov can't be used at the same time that xdebug which is already installed by default.
So the right and simple solution is just not to install pcov, or install it but disabling it the right way.
And let experienced developers install/setup/use it if they need it.

**Area for Triage**:  
PHP

**Question, Bug, or Feature?**:  
Bug

**Virtual environments affected**  
- [x] Ubuntu 16.04
- [x] Ubuntu 18.04
- [x] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Image version**
20210524.1

**Expected behavior**  
Possible to replace xdebug with pcov

**Actual behavior**  
Impossible to enable/use pcov as its configuration file have been wiped out

**Repro steps**  
```
phpenmod -v 7.4 pcov
php -m
```
=> pcov is not listed

**Comment by sylfabre** [comment]
Workaround is adding `echo 'extension=pcov.so' | sudo tee /etc/php/$(PHP_VERSION)/cli/conf.d/20-pcov.ini` to your pipeline

**Comment by dibir-magomedsaygitov** [comment]
Hello @sylfabre. Thank you for your report. We will take a look.

**Comment by al-cheb** [comment]
@sylfabre , Feel free to open the thread if you have any concerns.
