### ISSUE TITLE
Windows Kernel and arm64 Build Failures (ver 20210525.0)

### ISSUE THREAD

**Issue by nibanks** [actions/virtual-environments#3471]
**Description**  
In the last 24 hours, we've all of a sudden started seeing build errors on code that previous built just fine. Most of the errors are in our Windows kernel (driver) builds, but a user mode arm64 is also failing:

**Area for Triage**:  
'C/C++

**Question, Bug, or Feature?**:  
Bug

**Virtual environments affected**  
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016 R2
- [x] Windows Server 2019

**Image version**
Version: 20210525.0

**Expected behavior**  
The code should build successfully.

**Actual behavior**  
We are getting build failures. For example:

Windows user mode arm64 - https://dev.azure.com/ms/msquic/_build/results?buildId=171110&view=logs&j=4d0fd125-75c7-50ac-fc26-b67ddf842163&t=e5d4cfa3-fc5e-5590-091d-78c7f7025024&l=249
Windows kernel mode - https://dev.azure.com/ms/msquic/_build/results?buildId=171110&view=logs&j=016f7194-5c74-5f78-04de-96aae761eae1&t=45de86e9-e5a8-528f-e4ae-0a8e98172ca8

**Repro steps**  
Run MsQuic Pipeline on latest main: https://dev.azure.com/ms/msquic/_build?definitionId=347&_a=summary

**Comment by nibanks** [comment]
cc @anrossi @thadhouse

**Comment by nibanks** [comment]
I _think_ I've been able to work around most of the changes with https://github.com/microsoft/msquic/pull/1646. But I still have one link error I can't figure out how to fix:
```
##[error]core.lib(library.obj)(0,0): Error LNK2001: unresolved external symbol __stdio_common_vsnprintf_s
```

**Comment by nibanks** [comment]
FYI, this is blocking internal Windows kernel development, because this is an undocked component of the Windows OS.

**Comment by nibanks** [comment]
I have tracked this down to the Visual Studio 2019 v16.10 update. After I updated locally, I can now reproduce the failures seen in our pipeline. I have opened the following on Visual Studio: https://developercommunity.visualstudio.com/t/v1610-broke-windows-kernel-builds-c/1434854. Unless we can figure out a work around in MsQuic, I'd really prefer to hold on this upgrade, since it blocks all development for this project.

**Comment by maxim-lobanov** [comment]
@nibanks thank you for heads up. Unfortunately, it is not possible to hold on this upgrade since VS team doesn't provide way to install non-latest version of Visual Studio. Installer always install the latest one. Hosted VMs are regenerated on weekly basis and we can't freeze 16.9 on new machines.

**Comment by nibanks** [comment]
What's the work around then? With this in place, we are unable to take any security critical fixes (if needed) into this Windows component.

**Comment by maxim-lobanov** [comment]
We have to wait for answer from VS team with possible workaround / hotfix

**Comment by nibanks** [comment]
@maxim-lobanov do you (or anyone else) have any contacts on the VS side of things that we could work with to speed things up? Our whole team is practically blocked by this.

**Comment by ThadHouse** [comment]
If you do, I know the compiler team has a lot of builds they internally test with. We've broken in small ways every release the last 3 or 4 weeks, so we should get them to add our build to their test suite as well. Because its not a complicated build, and doesn't do that much weird stuff, but it shouldn't be breaking in the ways it does.

**Comment by maxim-lobanov** [comment]
@ThadHouse @nibanks , I have started email thread "Build failures after upgrade to VS 16.10" with VS team . Hope they will be able to route us to correct team.  Added you both in CC to provide any additional context

**Comment by maxim-lobanov** [comment]
I will close this issue as external  for now. If it is fixed from Visual Studio side, we will take a fix on board as soon as possible.
