### ISSUE TITLE
error MSB4057: The target "*****" does not exist in the project .

### ISSUE THREAD

**Issue by FrancescElies** [actions/virtual-environments#3475]
**Description**
Starting from today on we are seeing jobs failing with Error MSB4057 where before we had no errors.

I have narrowed two builds for the same commit that present different behaviours.
Both throw Error MSB4057 but in different jobs.

[Build 1](https://mbbm-ast.visualstudio.com/AST/_build/results?buildId=59762)
  - Image DAta: Microsoft Windows Server 2019\n10.0.17763\nDatacenter
  - Agent.Id: 153
  - Agent.MachineName: fv-az33-885

[Build 2 (same commit as Build 1)](https://mbbm-ast.visualstudio.com/AST/_build/results?buildId=59745)
  - Image Data: Microsoft Windows Server 2019\n10.0.17763\nDatacenter
  - Agent.Id: 193
  - Agent.MachineName: fv-az33-885

I guess this has to do with some sort of update on msbuild or the agents, maybe with [Pre-release
win19/20210525.0](https://github.com/actions/virtual-environments/releases/tag/win19%2F20210525.0)?

**Area for Triage**:
- C/C++
- .NET Core

**Question, Bug, or Feature?**:
Bug

**Virtual environments affected**
- [x] Windows Server 2019

**Image version**
 - Image Data: Microsoft Windows Server 2019\n10.0.17763\nDatacenter

**Expected behavior**
No Error MSB4057 as it used to be.

**Actual behavior**
Error MSB4057 being thrown

**Repro steps**
See build links.

I am aware this links belong to a private repository and it makes little sense for me to make a a minimal reproducible example.

**Comment by dibir-magomedsaygitov** [comment]
Hello @FrancescElies. Thank you for your report. We will take a look.

**Comment by maxim-lobanov** [comment]
Most likely related to upgrade Visual Studio from 16.9 to 16.10.

**Comment by FrancescElies** [comment]
I will try to get around this issue with vswhere. I'll keep you posted.

Thanks for your help

**Comment by andy-c-jones** [comment]
We are seeing this in Azure DevOps. Is there any way of use forcing version 20210516 of the image?
None of the workarounds are working for us at the minute.

**Comment by maxgolov** [comment]
The minimal trivial reproducible example can be found here in OSS repo:
https://github.com/microsoft/cpp_client_telemetry/pull/883

Failing with MSBuild from vs2019 16.10.0

```console
msbuild solution.sln /target:zlib,sqlite
```

The workaround is a bit ugly - scan all affected batch files, all target lists, all vcpkg port files, etc. And append `:Rebuild` to each target. Works okay with MSBuild from vs2019 16.10.0, but requires manual intervention.

```console
msbuild solution.sln /target:zlib:Rebuild,sqlite:Rebuild
```

Looks like the hot-fix would be available in a few weeks in 16.10.1? But the issue would affect more than one customer in the next few weeks for certain. I had at least 5 devs / different teams affected by this bug in one day. It's been a hot 🔥 issue for us.

**Comment by rhuijben** [comment]
Already reinstalled a machine in an attempt to fix this. Eagerly waiting for a fix

**Comment by aronbardsley** [comment]
This is very frustrating. I'm trying to add :Rebuild and its not working. Perhaps this scenario should be added to some sort of test framework by the MSBuild team?

I know it's no-one's fault, but these kinds of avoidable issues are a complete productivity killer

**Comment by FrancescElies** [comment]
@maxgolov Thanks for the workaround! 

`:Rebuild` has partially solved the problem for us. We also have solutions with c# projects even after this workaround they were still broken, not all `dlls` are included in the output folder.

For c projects, the following works:
    
     msbuild solution.sln /target:zlib:Rebuild

For c# projects, the following seems to help but I got other errors now (I'll write back as soon as I know more why):

     msbuild solution.sln /target:csharpproject:Rebuild,csharpproject:Publish

We make extensive usage of `/target` filtering. It's a pity this was broken.

I'm also pretty disappointed with https://github.com/dotnet/msbuild/issues/6373 , eagerly waiting for a fix as well.

**Comment by Bouke** [comment]
So this is breaking builds for a lot of people. How about rolling back this breaking change until Visual Studio 16.10.1 Hotfix is released?

**Comment by maxim-lobanov** [comment]
As I mentioned above, there is no way to install non-latest version of Visual Studio on VM images.
If we just roll back VMs to the previous image version, we will have to freeze image version and any VM updates until the next VS release that is not acceptable considering that Hosted VMs have a lot of software except Visual Studio.

If you upgrade VS to the 16.10 on your local machine, you won't be able to downgrade it too.

**Comment by Bouke** [comment]
I'm very disappointed by your reaction. In a professional organisation one assumes there are procedures to revert changes when there are serious problems. I would argue breaking various people's builds would warrant such a roll-back. If you don't have a way to restore the previous version of Visual Studio (16.9), then there must be something seriously wrong with the procedures you have in place.

**Comment by maxim-lobanov** [comment]
We always try to rollback images in case of any issues and fix it on our side if it is possible.
In case of Visual Studio, we install and use it as usual customers and we don't control update process from our side like selecting specific version to install and etc. If Visual Studio team doesn't provide way to install non-latest version or downgrade version, unfortunately, we won't be able to do it from our side like no one user won't be able to do it on their local machine.

**Comment by Bouke** [comment]
What about [Installing an earlier release](https://docs.microsoft.com/en-us/visualstudio/releases/2019/history#installing-an-earlier-release)?

**Comment by kim3er** [comment]
This must be related to https://github.com/microsoft/azure-pipelines-tasks/issues/14922. We use the target parameter in our DevOps pipeline.

**Comment by skalpin** [comment]
I noticed our powershell script was still working properly with msbuild targets. This might work for people having issues right now. Setup an inline powershell task and run

```ps
$currentLocation = Get-Location

# Developer Powershell
Import-Module 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\Tools\Microsoft.VisualStudio.DevShell.dll'
Enter-VsDevShell -Path 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise'

Set-Location $currentLocation

msbuild "<your msbuild arguments>"
```

**Comment by FrancescElies** [comment]
@maxgolov it seems like Visual Studio released 16.10.1 and it's available for download.

**Comment by miketimofeev** [comment]
@FrancescElies we've already started the new image deployment. It will be finished on Monday, but some customers may expect the new version earlier since the deployment is performed gradually.

**Comment by kim3er** [comment]
I can confirm the targets cli parameter is work on VSBuild 1.187.0.

**Comment by miketimofeev** [comment]
@FrancescElies could you please confirm that the issue is resolved with the new image version?

**Comment by FrancescElies** [comment]
@miketimofeev  👌 checking at the moment, I will close the issue as soon as I removed the workaround from our codebase and everything works fine.

**Comment by FrancescElies** [comment]
Closing. We removed the workaround and everything seems to be working fine.

@maxim-lobanov @miketimofeev thanks for your support!
