### ISSUE TITLE
conda command not found

### ISSUE THREAD

**Issue by Bengt** [actions/virtual-environments#3477]
**Description**  

I cannot run the conda command in any shell.

**Question, Bug, or Feature?**:  

Bug

**Virtual environments affected**  

- [x] Windows Server 2019

**Image version**

20210516.0

**Expected behavior**  

conda command is available in PATH.

**Actual behavior**  

conda is somehow not available in PATH.

**Repro steps**  

```
Run conda install -c conda-forge portaudio
  conda install -c conda-forge portaudio
  shell: C:\Program Files\Git\bin\bash.EXE --noprofile --norc -e -o pipefail {0}
  env:
    pythonLocation: C:\hostedtoolcache\windows\Python\3.6.8\x64
D:\a\_temp\888e27e0-e1f7-47c9-b6e9-9ab21dfdf859.sh: line 1: conda: command not found
Error: Process completed with exit code 127.
```

Source: https://github.com/Bengt/multisensor-pipeline/runs/2694187190 (Shell: BASH)

```
Run conda install -c conda-forge portaudio
  conda install -c conda-forge portaudio
  shell: C:\Windows\System32\WindowsPowerShell\v1.0\powershell.EXE -command ". '{0}'"
  env:
    pythonLocation: C:\hostedtoolcache\windows\Python\3.6.8\x64
conda : The term 'conda' is not recognized as the name of a cmdlet, function, script file, or operable program. Check 
the spelling of the name, or if a path was included, verify that the path is correct and try again.
At D:\a\_temp\0a620263-0805-4018-a249-0af113d1bc61.ps1:2 char:1
+ conda install -c conda-forge portaudio
+ ~~~~~
    + CategoryInfo          : ObjectNotFound: (conda:String) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : CommandNotFoundException
```

Source: https://github.com/Bengt/multisensor-pipeline/runs/2694001593 (Shell: Powershell)

```
Run conda install -c conda-forge portaudio
  conda install -c conda-forge portaudio
  shell: C:\Windows\system32\cmd.EXE /D /E:ON /V:OFF /S /C "CALL "{0}""
  env:
    pythonLocation: C:\hostedtoolcache\windows\Python\3.6.8\x64
'conda' is not recognized as an internal or external command,
operable program or batch file.
Error: Process completed with exit code 1.
```

Source: https://github.com/Bengt/multisensor-pipeline/runs/2695775890 (Shell: cmd)

**Comment by dibir-magomedsaygitov** [comment]
Hello @Bengt. Thank you for your report. We will take a look.

**Comment by Bengt** [comment]
Hello @dibir-magomedsaygitov. Thanks for looking into this. I am still trying to fill in the bug report form.

**Comment by Bengt** [comment]
I can also try the cmd shell ...

**Comment by dmitry-shibanov** [comment]
Hello @Bengt. Thank you for your report. We have preinstalled `miniconda` to our images, but it's not added to the PATH. You can use this [task](https://github.com/s-weigand/setup-conda) to setup conda and install required python version or use existing one. It will use existing CONDA environment variable, add it to the Path and provide other customisation.

**Comment by Bengt** [comment]
Hello @dmitry-shibanov. Thanks for looking into this. I will try the setup-conda task. What does this mean for this issue, though? Would it be sensible to add the preinstalled miniconda to the PATH as well or is there a reason not to do that?

**Comment by maxim-lobanov** [comment]
We shouldn't add miniconda to PATH because it will cause conflicts with pre-installed Python. Using action - is recommended way.

**Comment by Bengt** [comment]
Hello @maxim-lobanov. Thanks for the explanation. Since the conda command is intentionally not in PATH, we can consider this issue closed as "won't fix" or so. Since the design decision of not adding conda to the PATH was not obvious to me, others will likely also stumble upon that. I was looking at the environment documentation, which list miniconda as preinstalled.[1, 2] So, I falsely assumed miniconda was also in PATH. Interestingly, there are notes about MSYS2 being installed, but not in PATH.[3, 4] Should the miniconda setup be documented in the same way?

1: https://github.com/actions/virtual-environments/blob/main/images/win/Windows2016-Readme.md
2: https://github.com/actions/virtual-environments/blob/main/images/win/Windows2019-Readme.md

3: https://github.com/actions/virtual-environments/blob/main/images/win/Windows2016-Readme.md#msys2
4: https://github.com/actions/virtual-environments/blob/main/images/win/Windows2019-Readme.md#msys2

**Comment by miketimofeev** [comment]
@maxim-lobanov @Bengt Looks like it's a good idea to update our docs to avoid such confusion in the future

**Comment by AlenaSviridenko** [comment]
Agreed to add such note to our README docs.

**Comment by dmitry-shibanov** [comment]
Hello @Bengt. [Pull request](https://github.com/actions/virtual-environments/pull/3513) was merged. Changes will be added in the next images rollout.

**Comment by Bengt** [comment]
Hello @dmitry-shibanov. Awesome! Thanks for the fix.

**Comment by dmitry-shibanov** [comment]
Hello @Bengt. Documentation was updated. I'm closing the issue.
