### ISSUE TITLE
Support for Windows 20H2 in Virtual environment

### ISSUE THREAD

**Issue by jahanarun** [actions/virtual-environments#3480]
Is there a plan to add support for Windows 20H2 in the Virtual environment?

I cannot build docker image in Github using `FROM mcr.microsoft.com/windows/servercore:20H2` without the support for 20H2 in the Virtual Environment.

**Comment by maxim-lobanov** [comment]
Duplicate https://github.com/actions/virtual-environments/issues/3138

**Comment by jahanarun** [comment]
@maxim-lobanov 
The issue you linked is for Windows 2022.
But, 20H2 is based off Windows 2019.

**Comment by maxim-lobanov** [comment]
@jahanarun , oh, You are right, sorry. 

As for the Windows Server 20H2, we don't have plans to add it.
We are supporting only LTS versions but 20H2 is not LTS based on https://docs.microsoft.com/en-us/windows-server/get-started/windows-server-release-info#windows-server-current-versions-by-servicing-option 
The next Windows OS that we have plans to add will be Windows Server 2020
