### ISSUE TITLE
SQL Server is failing to download in GH Action VM

### ISSUE THREAD

**Issue by mcdurdin** [actions/virtual-environments#3493]
**Description**  
We're running some integration tests as a GH action that rely on a local instance of SQL Server to complete. We have been using chocolatey to install SQL Server successfully for some time:

```
choco install sql-server-2019 --no-progress --params "'/IGNOREPENDINGREBOOT /INSTANCEID=KEYMANAPI /INSTANCENAME=KEYMANAPI /SAPWD=*** /SECURITYMODE=SQL /UPDATEENABLED=FALSE /FEATURES=SQLENGINE,FULLTEXT'"
```

However, today, the action has started failing to download the ISO:

```
Chocolatey v0.10.15
Installing the following packages:
sql-server-2019
By installing you accept licenses for the packages.

sql-server-2019 v15.0.2000.20210324 [Approved]
sql-server-2019 package files install completed. Performing other installation steps.
Downloading sql-server-2019 
  from 'https://download.microsoft.com/download/7/c/1/7c14e92e-bdcb-4f89-b7cf-93543e7112d1/SQLServer2019-x64-ENU-Dev.iso'
ERROR: The remote file either doesn't exist, is unauthorized, or is forbidden for url 'https://download.microsoft.com/download/7/c/1/7c14e92e-bdcb-4f89-b7cf-93543e7112d1/SQLServer2019-x64-ENU-Dev.iso'. Exception calling "Read" with "3" argument(s): "Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host."
The install of sql-server-2019 was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\sql-server-2019\tools\chocolateyinstall.ps1'.
 See log for details.

Chocolatey installed 0/1 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Failures
 - sql-server-2019 (exited 404) - Error while running 'C:\ProgramData\chocolatey\lib\sql-server-2019\tools\chocolateyinstall.ps1'.
 See log for details.
Error: Process completed with exit code 404.
```

I have checked that the file is available (https://download.microsoft.com/download/7/c/1/7c14e92e-bdcb-4f89-b7cf-93543e7112d1/SQLServer2019-x64-ENU-Dev.iso) and have even downloaded it successfully on a private Azure VM. So I am unclear as to why this is failing on the GH Action VM.

**Area for Triage**:  

Databases

**Question, Bug, or Feature?**:  

Bug

**Virtual environments affected**  
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016 R2
- [x] Windows Server 2019

**Image version**

20210525.0

**Expected behavior**  
The download should succeed, similar to:

```
Chocolatey v0.10.15
Installing the following packages:
sql-server-2019
By installing you accept licenses for the packages.

sql-server-2019 v15.0.2000.20210324 [Approved]
sql-server-2019 package files install completed. Performing other installation steps.
Downloading sql-server-2019 
  from 'https://download.microsoft.com/download/7/c/1/7c14e92e-bdcb-4f89-b7cf-93543e7112d1/SQLServer2019-x64-ENU-Dev.iso'

Download of SQLServer2019-x64-ENU-Dev.iso (1.33 GB) completed.
Hashes match.
```

The last successful run was 21 days ago.

**Actual behavior**  
The download is failing with error "Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host."

**Repro steps**  
1. Run the following command in a GH action (fixup `SAPWD` parameter first):

```
choco install sql-server-2019 --no-progress --params "'/IGNOREPENDINGREBOOT /INSTANCEID=KEYMANAPI /INSTANCENAME=KEYMANAPI /SAPWD=*** /SECURITYMODE=SQL /UPDATEENABLED=FALSE /FEATURES=SQLENGINE,FULLTEXT'"
```

Ref: https://github.com/keymanapp/api.keyman.com/blob/master/.github/workflows/ci.yml
Ref: https://github.com/keymanapp/api.keyman.com/pull/153/checks?check_run_id=2714098977.

**Comment by miketimofeev** [comment]
Hi @mcdurdin!
Looks like it was some intermittent issue with https://download.microsoft.com. I've tried your pipeline and the run was succeeded 5 times in a row:
![image](https://user-images.githubusercontent.com/48208649/120307157-52efb680-c2db-11eb-8c4b-6cbb6627868f.png)
https://github.com/miketimofeev/api.keyman.com/actions

**Comment by mcdurdin** [comment]
Hi @miketimofeev :) Yes, I just re-ran the action now and it succeeded, so that's good news. Thank you!

I guess these kinds of transient network problems can never be completely eliminated -- so will just have to work with that.

**Comment by mcdurdin** [comment]
This issue has returned: https://github.com/keymanapp/api.keyman.com/runs/2732594202?check_suite_focus=true

Is it possible that download.microsoft.com is rate limiting requests from GitHub Action VMs?

**Comment by miketimofeev** [comment]
@mcdurdin no, we're not aware of any limiting requests and there are a lot of packages that customers download from download.microsoft.com. 
I've tried to download the file 100 times in a row and have no issues at all.
I suggest writing simple retry logic for choco installation. Please let me know if you need any help with that.

**Comment by mcdurdin** [comment]
Thanks @miketimofeev. I found #721 which gives good retry logic for choco and seems to work well for our needs.
