### ISSUE TITLE
Add Puppet Development Kit

### ISSUE THREAD

**Issue by michaeltlombardi** [actions/virtual-environments#3502]
**Tool information**
- Tool name: Puppet Development Kit (PDK
- Tool license: Apache License 2.0
- Add or update? Add
- Desired version: 2.1.0
- Approximate size: 
- If this is an add request:
  - Brief description of tool: The Puppet Development Kit (PDK) includes key Puppet code development and testing tools for Linux, Windows, and OS X workstations, so you can install one package with the tools you need to create and validate new modules.

    PDK includes testing tools, a complete module skeleton, and command line tools to help you create, validate, and run tests on Puppet modules. PDK also includes all dependencies needed for its use.
  - URL for tool's homepage: https://puppet.com/docs/pdk/2.x/pdk.html
  - Provide a basic test case to validate the tool's functionality:
    ```sh
    # create and cd into a new module
    pdk new module foo --skip-interview
    cd ./foo
    # runs linting
    pdk validate
    # runs all unit tests
    pdk test unit
    # Exports reference docs for a Puppet module
    pdk bundle exec puppet strings generate --format markdown --out REFERENCE.md
    ```

**Area for Triage**:
Packages, Scripting and command line, testing and code coverage

**Question, Bug, or Feature?**:
Feature

**Virtual environments affected**
- [x] Ubuntu 16.04
- [x] Ubuntu 18.04
- [x] Ubuntu 20.04
- [x] macOS 10.15
- [x] macOS 11
- [x] Windows Server 2016 R2
- [x] Windows Server 2019

**Can this tool be installed during the build?**
Yes.

```sh
# ubuntu 16.04
wget https://apt.puppet.com/puppet-tools-release-xenial.deb
sudo dpkg -i puppet-tools-release-xenial.deb
sudo apt-get update
sudo apt-get install pdk
# Ubuntu 18.04
wget https://apt.puppet.com/puppet-tools-release-bionic.deb
sudo dpkg -i puppet-tools-release-bionic.deb
sudo apt-get update
sudo apt-get install pdk
# Ubuntu 20.04
wget https://apt.puppet.com/puppet-tools-release-focal.deb
sudo dpkg -i puppet-tools-release-focal.deb
sudo apt-get update
sudo apt-get install pdk
# MacOS
brew install --cask puppetlabs/puppet/pdk
# Windows
choco install pdk
```

**Tool installation time in runtime**
< 5m - install is noticeably longer on Windows than other platforms.

**Are you willing to submit a PR?**
Yes!

**Comment by miketimofeev** [comment]
@AlenaSviridenko @maxim-lobanov For reference:
| OS                | Installation time                  | Size
| ----------------------- | ---------------------- | ------------------ |
| win19                   |  4.5 min |         **2Gb**                             |
| macos1015 |  2 min |        **1.6Gb**             |
| ubuntu18 |  1 min  |         **1.15Gb**              |

**Comment by AlenaSviridenko** [comment]
Hi @michaeltlombardi,
unfortunately, at the moment we cannot afford to install such large tools due to the image space concerns. Some time ago we received several incidents related to disk space, so now our images considered as pretty full of software, so we are trying to avoid installing big tools in favor of smaller and more requested tools.

I am closing this issue. Please, let me know if you have any concerns. Thanks.
