### ISSUE TITLE
Update/Add [Xcode 12.5]

### ISSUE THREAD

**Issue by BrentMifsud** [actions/virtual-environments#3503]
**Tool information**
- Tool name: Xcode 12.5
- Tool license: n/a
- Add or update?: update
- Desired version: 12.5
- Approximate size: 

**Area for Triage**:
Apple

**Question, Bug, or Feature?**:
Feature

**Virtual environments affected**
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [x] macOS 11
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Can this tool be installed during the build?**
no, it would take far too long

**Tool installation time in runtime**
20-30 min

**Are you willing to submit a PR?**
no

Other:

here is a screenshot from a recent build using macOS latest. Xcode 12.5 is missing:

![image](https://user-images.githubusercontent.com/18543934/120348203-f84e5e80-c2ca-11eb-8d30-e40476d37668.png)

**Comment by AlenaSviridenko** [comment]
Hi @BrentMifsud,
`macos-latest` tag still points to macOS 10.15. MacOS 11 contains Xcpde 12.5 but this OS is still in private preview, although we start opening it. You can track progress here https://github.com/actions/virtual-environments/issues/2486.

Closing this issue, please let me know if you have any concerns.
Thanks!

**Comment by BrentMifsud** [comment]
thanks for the heads up. I didnt realize macOS-latest was still pointing to 10.15.
