### ISSUE TITLE
VM vs2017-win2016 cannot resolve some domain names

### ISSUE THREAD

**Issue by liyuanqiu** [actions/virtual-environments#3512]
**Description**  
For this domain name `smtphost.redmond.corp.microsoft.com`, I can't resolve its IP address in VM `vs2017-win2016`.

I can ping this address in my own PC, in my self-hosted vms, in everywhere but not the VM `vs2017-win2016`

Simple steps to reproduce:
1. Create a pipeline that uses VM `vs2017-win2016`
2. Add a `Command line` task, and write `ping smtphost.redmond.corp.microsoft.com`
3. Run that pipeline

You'll get the error in logs:
`2021-06-02T06:35:43.0459138Z Ping request could not find host smtphost.redmond.corp.microsoft.com. Please check the name and try again.`

**Area for Triage**:  

Containers

**Question, Bug, or Feature?**:  

Bug

**Virtual environments affected**  
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [x] Windows Server 2016 R2
- [ ] Windows Server 2019

**Image version**

20210525.0

**Expected behavior**  
The domain name should be able to resolved.

**Actual behavior**  
The domain name can not be resolved.

**Repro steps**  
1. Create a pipeline that uses VM `vs2017-win2016`
2. Add a `Command line` task, and write `ping smtphost.redmond.corp.microsoft.com`
3. Run that pipeline

You'll get the error in logs:
`2021-06-02T06:35:43.0459138Z Ping request could not find host smtphost.redmond.corp.microsoft.com. Please check the name and try again.`

**Comment by miketimofeev** [comment]
Hi @liyuanqiu!
I also can't ping this domain from my local mac with MSFT VPN disabled:
```
mikhail.timofeev$ ping smtphost.redmond.corp.microsoft.com
ping: cannot resolve smtphost.redmond.corp.microsoft.com: Unknown host
```
However, if I enable the VPN everything works fine:
```
mikhail.timofeev$ ping smtphost.redmond.corp.microsoft.com
PING smtphost.gtm.corp.microsoft.com (10.222.122.39): 56 data bytes
64 bytes from 10.222.122.39: icmp_seq=0 ttl=105 time=214.810 ms
64 bytes from 10.222.122.39: icmp_seq=1 ttl=105 time=214.352 ms
```
I assume that you have the VPN enabled on your local VM and your self-hosted VMs since corpnet is not supposed to be available without the VPN.

**Comment by miketimofeev** [comment]
@liyuanqiu I'm going to close the issue.
Please feel free to contact us if you have any concerns.
Thank you!

**Comment by liyuanqiu** [comment]
Thanks @miketimofeev, you are right, the domain is a corpnet domain 😅
