### ISSUE TITLE
[macOS] Default Xcode on Big Sur image will be set to Xcode 12.5 on June, 15

### ISSUE THREAD

**Issue by miketimofeev** [actions/virtual-environments#3522]
**Breaking changes**
Default Xcode will be changed to 12.5 on macOS 11 Big Sur.

**Target date**
Update propagation will start on June, 15 and will take 2-3 days.

**The motivation for the changes**
We would like to provide images with the latest stable updates as default ones.

**Possible impact**
If you use the default Xcode version and your project is not compatible with Xcode 12.5 your build can be broken.

**Virtual environments affected**
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.13
- [ ] macOS 10.14
- [ ] macOS 10.15
- [x] macOS 11
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Mitigation ways**
Please consider switching Xcode in runtime to the version that you need to build an app.
The following snippet can be used to switch Xcode:

`sudo xcode-select -s "/Applications/Xcode_12.4.app"`

The list of all available Xcode versions can be found in the [image documentation
](https://github.com/actions/virtual-environments/blob/main/images/macos/macos-10.15-Readme.md#xcode)

**Comment by KarlHarnois** [comment]
Any way to use Xcode 12.5 in a GitHub action while waiting for this change?

**Comment by btfranklin** [comment]
> Any way to use Xcode 12.5 in a GitHub action while waiting for this change?

Yes, if you're in on the preview. Take a look at how I have this one set up:

https://github.com/dunesailer/Utilities/actions

**Comment by EwoutH** [comment]
Maybe a few old Xcode versions and SDKs can be removed, Xcode 12.2 and 12.3 for example, especially since the macos-11 image is very lightly used currently (so now would be the ideal moment for such a change).

**Comment by AlenaSviridenko** [comment]
@EwoutH good idea, we will remove them in 2.5 weeks, here is the announcement https://github.com/actions/virtual-environments/issues/3555. Thanks for raising up this point.

**Comment by miketimofeev** [comment]
The image with the default Xcode 12.5 was deployed
