### ISSUE TITLE
No virtual audio output device available on macOS11 images

### ISSUE THREAD

**Issue by esteluk** [actions/virtual-environments#3526]
**Description**  

We've encountered a regression in our iOS test suite when migrating to the macOS 11 images. It manifests in one unit tests resulting in a deadlock on the build server, and UI test failures that are caused by in-app video players not starting the playback of videos.

After some investigation, I _think_ this is caused by changes in the construction of the VMs where they no longer have a virtual audio device. 

Working around this wasn't too hard, and required the installation of `blackhole` using homebrew. This allows my tests to run successfully.

I'm raising this issue because I'm not sure if it's a bug or feature request. It definitely represents a regression in behaviour between the macOSX and 11 images that I wanted to highlight if you weren't aware. I understand if it's a niche enough requirement that you'd recommend just continuing with the manual install, rather than modifying the image.

**Area for Triage**:  
Apple

**Question, Bug, or Feature?**:  
Question

**Virtual environments affected**  
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [X] macOS 11
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Image version**
20210531.1

**Comment by miketimofeev** [comment]
Hi @esteluk!
This is most likely related to the lack of audio device provisioning script on Big Sur
https://github.com/actions/virtual-environments/blob/main/images/macos/provision/core/audiodevice.sh
When we onboarded Big Sur these homebrew packages were incompatible with the new macOS version. We will revisit the packages one more time.
If the packages are still not available we can consider adding the blackhole package.

**Comment by esteluk** [comment]
Ahh great thanks. When addressing this locally I also started trying `soundflower` but had to switch over to `blackhole` to make macOS happy. Glad to know it's something on your radar.

**Comment by miketimofeev** [comment]
@esteluk good news! We've added blackhole in the scope of this PR https://github.com/actions/virtual-environments/pull/3542 along with sox and switchaudiodevice utilities.
The new image will be available later this week. I'll keep you posted.

**Comment by miketimofeev** [comment]
@esteluk the new image deployed. The audio device is set to `BlackHole 2ch`
![image](https://user-images.githubusercontent.com/48208649/121334221-26165180-c922-11eb-9c08-db25eded2360.png)
I'm going to close the issue. Please feel free to contact us if you have any concerns.
Thank you!

**Comment by esteluk** [comment]
@miketimofeev Brilliant, thank you!
