### ISSUE TITLE
Problem installing libzmq3-dev on ubuntu 16.04

### ISSUE THREAD

**Issue by jwillemsen** [actions/virtual-environments#3530]
**Description**  
Problem installing libzmq3-dev on ubuntu 16.03

```
sudo apt-get --yes install libxerces-c-dev libssl-dev libzmq3-dev g++-4.8
```

Results in

```
The following packages have unmet dependencies:
 libzmq3-dev : Depends: libzmq5 (= 4.1.4-7ubuntu0.1) but 4.3.1-5+ubuntu16.04.1+deb.sury.org+1 is to be installed
E: Unable to correct problems, you have held broken packages.
```

**Area for Triage**:  
Packages

**Question, Bug, or Feature?**:  
Bug

**Virtual environments affected**  
- [X] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Image version**
20210531.0

**Expected behavior**  
Package to be installed

**Actual behavior**  
```
The following packages have unmet dependencies:
 libzmq3-dev : Depends: libzmq5 (= 4.1.4-7ubuntu0.1) but 4.3.1-5+ubuntu16.04.1+deb.sury.org+1 is to be installed
E: Unable to correct problems, you have held broken packages.
```

**Repro steps**  
```
   sudo apt-get --yes update
  sudo apt-get --yes install libxerces-c-dev libssl-dev libzmq3-dev g++-4.8
```

**Comment by jwillemsen** [comment]
Similar to #3317 but now on ubuntu 16.04

**Comment by miketimofeev** [comment]
Hi @jwillemsen!
It seems that `ppa:ondrej/php` dropped ubuntu 16 support recently. I recommend you switch to either Ubuntu 18 or Ubuntu 20 as we are also deprecating Ubuntu 16 at the moment — https://github.com/actions/virtual-environments/issues/3287

**Comment by jwillemsen** [comment]
Thanks for the quick response, I created a bunch of PRs to use gcc4.8 on ubuntu 18.04, will take some time to get these all ran, will let you know when that worked.
