### ISSUE TITLE
[Ubuntu 16] Php can't be installed from ppa:ondrej/php

### ISSUE THREAD

**Issue by miketimofeev** [actions/virtual-environments#3531]
**Description**  
It looks like ppa:ondrej/php dropped support for Ubuntu 16
![image](https://user-images.githubusercontent.com/48208649/120969914-65eb0680-c773-11eb-869f-a9a97a31eab5.png)
This leads to the failures during Ubuntu 16 image generation:
```
==> azure-arm: E: Unable to locate package php7.0-sodium
==> azure-arm: E: Couldn't find any package by glob 'php7.0-sodium'
==> azure-arm: E: Couldn't find any package by regex 'php7.0-sodium'
    azure-arm: Reading package lists...
    azure-arm: Building dependency tree...
    azure-arm: Reading state information...
==> azure-arm: E: Unable to locate package php7.0-sodium
==> azure-arm: E: Couldn't find any package by glob 'php7.0-sodium'
==> azure-arm: E: Couldn't find any package by regex 'php7.0-sodium'
    azure-arm: Installing PHP 7.1
    azure-arm: [apt-fast 00:51:53]
    azure-arm: [apt-fast 00:51:53]Working... this may take a while.
==> azure-arm: E: Unable to locate package php7.1
==> azure-arm: E: Couldn't find any package by glob 'php7.1'
==> azure-arm: E: Couldn't find any package by regex 'php7.1'
```
and so on.

**Area for Triage**:  
PHP

**Question, Bug, or Feature?**:  
Bug

**Virtual environments affected**  
- [x] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Image version**
not applicable

**Expected behavior**  
DIfferent PHP versions are installed

**Actual behavior**  
PHP versions can't be installed

**Repro steps**  
https://github.visualstudio.com/virtual-environments/_build/results?buildId=110800&view=logs&j=011e1ec8-6569-5e69-4f06-baf193d1351e&t=5431112d-2b61-5a5f-7042-ef698f761043

**Comment by al-cheb** [comment]
https://github.com/oerdnj/deb.sury.org/issues/1567#issuecomment-855091229

**Comment by miketimofeev** [comment]
Hi @shivammathur! Could you please suggest to us the best way of handling this? We're thinking of removing PHP support from Ubuntu 16, but maybe there are some alternate paths?

**Comment by shivammathur** [comment]
Yes, I would recommend removing PHP from Ubuntu 16.04 images. On GitHub Actions, anyone using `setup-php` would not be affected till August 1, 2021. Afterward, most projects should be able to switch to ubuntu 20.04 or 18.04 without any effect on their workflows.

Azure users using PHP 5.6 and 7.0 might be affected as there would be no easy upgrade path for them in CI. I think if requested, adding these to Ubuntu 18.04 might be a good idea, since `ppa:ondrej/php` builds have security patches backported.

**Comment by miketimofeev** [comment]
We have removed PHP from Ubuntu 16 provision scripts but decided not to update the currently deployed hosted image with PHP on board as Ubuntu 16 will be retired in September.
