### ISSUE TITLE
Podman: support "cgroupManager: systemd" for non-root users

### ISSUE THREAD

**Issue by fauust** [actions/virtual-environments#3536]
**Description**  
It is impossible at the moment -- or I did not find how -- to start a podman container with systemd without using sudo.
It would be very nice to be able to do so for molecule/ansible testing where a container needs to be running in the background to test ansible deployments.

**Area for Triage**:  
Containers

**Question, Bug, or Feature?**:  
Feature/bug?

**Virtual environments affected**  
- [ ] Ubuntu 16.04
- [X] Ubuntu 18.04
- [X] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Image version**
20210531.0

**Expected behavior**  
Start the container with non-root user, use it with molecule (deploy, test, start/stop service, destroy).

**Actual behavior**  
The container won't start and molecule can not execute the scenario (see: https://github.com/ansible-community/molecule-podman/issues/2#issuecomment-848677138).

**Repro steps**  
https://github.com/fauust/ansible-role-mariadb/runs/2762058922?check_suite_focus=true OK
https://github.com/fauust/ansible-role-mariadb/runs/2762054851?check_suite_focus=true NOK

See: https://github.com/fauust/ansible-role-mariadb/commit/453c3201e0735c3b97e01fe1eae5082ab258ae32
See also: https://github.com/actions/runner/issues/1134

**Comment by miketimofeev** [comment]
Hi @fauust!
We will take a look at this and get back with the results.

**Comment by kassannk** [comment]
@fauust Hi, I invested in issue and it is reproduced on pure ubuntu, which means that issue refers to podman. Please create a ticket in the spoof repository https://github.com/containers/podman. Let me know if you have any questions.

**Comment by fauust** [comment]
Hi @kassannk!
Thanks for looking into this.

I have just created an Ubuntu 20.04 VM from scratch and then installed the latest podman version from the Kubic project (as suggested [here](https://podman.io/getting-started/installation)). I guess it's exactly the same version that GH runner [use](https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-README.md).

And I am not able to reproduce the problem, see bellow:

```console
faust@ubuntu2004:~$ podman version
Version:      3.1.2
API Version:  3.1.2
Go Version:   go1.15.2
Built:        Thu Jan  1 00:00:00 1970
OS/Arch:      linux/amd64
faust@ubuntu2004:~$ podman run --systemd=always -it fauust/docker-systemd:debian-10
ERRO[0000] overlay test mount with multiple lowers failed, but succeeded with a single lower
✔ docker.io/fauust/docker-systemd:debian-10
Trying to pull docker.io/fauust/docker-systemd:debian-10...
Getting image source signatures
Copying blob 69692152171a done
Copying blob bccd2dc83439 done
Copying config 232cddc109 done
Writing manifest to image destination
Storing signatures
systemd 241 running in system mode. (+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD -IDN2 +IDN -PCRE2 default-hierarchy=hybrid)
Detected virtualization container-other.
Detected architecture x86-64.

Welcome to Debian GNU/Linux 10 (buster)!

Set hostname to <f2204b0aa3eb>.
File /lib/systemd/system/systemd-journald.service:12 configures an IP firewall (IPAddressDeny=any), but the local system does not support BPF/cgroup based firewalling.
Proceeding WITHOUT firewalling in effect! (This warning is only shown for the first loaded unit using IP firewalling.)
[  OK  ] Listening on Journal Socket (/dev/log).
[  OK  ] Reached target Slices.
[  OK  ] Reached target Swap.
[  OK  ] Started Dispatch Password Requests to Console Directory Watch.
[  OK  ] Reached target Paths.
[  OK  ] Reached target Local Encrypted Volumes.
[  OK  ] Reached target Local File Systems.
[  OK  ] Listening on Journal Socket.
         Starting Journal Service...
         Starting Create System Users...
[  OK  ] Reached target Sockets.
[  OK  ] Started Journal Service.
         Starting Flush Journal to Persistent Storage...
[  OK  ] Started Create System Users.
[  OK  ] Reached target System Initialization.
[  OK  ] Reached target Basic System.
[  OK  ] Reached target Multi-User System.
[  OK  ] Reached target Graphical Interface.
[  OK  ] Started Daily Cleanup of Temporary Directories.
[  OK  ] Reached target Timers.
[  OK  ] Started Flush Journal to Persistent Storage.
```

**Comment by kassannk** [comment]
Hello @fauust ,
It seems there is a mismatch between access rights on clean Ubuntu-20 and Ubuntu-20 agent machine. In order to avoid the issue and start your workflow according to your needs, you can add the following command right before `podman start` command:
`chmod o+rwx -R /sys/fs/cgroup/systemd/`
I've just tested the solution and it works fine. Could you please check on your side as well and confirm that everything works as expected?
We are looking forward to your reply.

**Comment by fauust** [comment]
Hi @kassannk !
Thanks, it seems that now I am able to start rootless container with systemd.

I am still stuck because starting the container in a molecule context does not work, see https://github.com/fauust/ansible-role-mariadb/runs/2797968500?check_suite_focus=true.

I have asked for help on the ansible community because the molecule-podman driver is maybe the culprit https://github.com/ansible-community/molecule/discussions/3155.

Anyway, there is still something strange with the GitHub `ubuntu-latest` runner because I am not able to reproduce the problem on my fresh Ubuntu 20.04 VM.

**Comment by kassannk** [comment]
@fauust Hi. I seem to have found a solution to your problem with a molecule.

Your molecule instances are created in docker but they were stopped when your rebooted and were not restarted automatically. Molecule sees them as created but cannot access them as they are not running.

You have 2 solutions to fix this problem.

Restart the stopped instances

find the relevant name(s) of the container(s) with docker ps -a
restart the instance(s) with docker start <name>
Restart from scratch

You can simply run molecule destroy [-s scenarion_name]. This will cleanup the left over instances and you can start your tests from scratch after that.

Could you please check on your side as well and confirm that everything works as expected?
We are looking forward to your reply.

**Comment by fauust** [comment]
Hi @kassannk thanks again for your help.

Just to clarify, I am not trying to use docker but podman.

And as described [here](https://github.com/ansible-community/molecule/discussions/3155), the problem is that instance started with molecule are not working/running (whereas if I use podman, directly, it seems to work). But in order to use molecule, the container needs to be started and created via molecule.

> You can simply run molecule destroy [-s scenarion_name]. This will cleanup the left over instances and you can start your tests from scratch after that.

The `molecule test` command, that is used in the full test suite, already destroy and recreate the instance in the default scenario.

**Comment by kassannk** [comment]
> Hi @kassannk thanks again for your help.
> 
> Just to clarify, I am not trying to use docker but podman.
> 
> And as described [here](https://github.com/ansible-community/molecule/discussions/3155), the problem is that instance started with molecule are not working/running (whereas if I use podman, directly, it seems to work). But in order to use molecule, the container needs to be started and created via molecule.
> 
> > You can simply run molecule destroy [-s scenarion_name]. This will cleanup the left over instances and you can start your tests from scratch after that.
> 
> The `molecule test` command, that is used in the full test suite, already destroy and recreate the instance in the default scenario.

Thank you for your message. I studied a lot of materials on the molecule, and came to the conclusion that the molecule cannot be launched without root rights. And the problem is in the drivers of the molecule. Tell me please, do you have a molecule running with root?

**Comment by DanNixon** [comment]
I believe I am seeing a similar issue.

https://github.com/DanNixon/ansible-system/actions/runs/946150577 shows the result of (what boils down to) `molecule test`)

https://github.com/DanNixon/ansible-system/actions/runs/946150577 shows the same issue @fauust describes where the container is not running when created via molecule.

I'll echo that this works fine for me locally so am inclined to agree that this is something specific to the Ubuntu actions environment.

**Comment by kassannk** [comment]
@fauust I suggest you to create a new one issue according to the template - Add a new tool, we will consider. Thanks

**Comment by fauust** [comment]
> Thank you for your message. I studied a lot of materials on the molecule, and came to the conclusion that the molecule cannot be launched without root rights. And the problem is in the molecule. Tell me please, do you have a molecule running with root?

So, I have tested with root (`sudo molecule test`) and it seems it's indeed working as root.
So that's a workaround, thank you, see https://github.com/fauust/ansible-role-mariadb/actions/runs/960288619.

That said, in the long run, I thing GitHub action runner should be able to use rootless podman container with molecule, there is clearly something specific to Ubuntu GH action environment that prevent it, as confirmed by @DanNixon.

**Comment by kassannk** [comment]
> > Thank you for your message. I studied a lot of materials on the molecule, and came to the conclusion that the molecule cannot be launched without root rights. And the problem is in the molecule. Tell me please, do you have a molecule running with root?
> 
> So, I have tested with root (`sudo molecule test`) and it seems it's indeed working.
> So that's a workaround, thank you, see https://github.com/fauust/ansible-role-mariadb/actions/runs/960288619.
> 
> That said, in the long run, I thing GitHub action runner should be able to use rootless podman container with molecule, there is clearly something specific to Ubuntu GH action environment that prevent it, as confirmed by @DanNixon.

Hello. Thank you for your message. I will look for options to make molecules without root rights. I looked through the options, but there is a danger of opening a vulnerability in the Github Actions, but I'm looking for options. Something is wrong with the drivers of the molecule.

**Comment by DanNixon** [comment]
> I looked through the options, but there is a danger of opening a vulnerability in the Github Actions.

Could you elaborate on this please. Is this related to the use of unprivileged user namespeces?

**Comment by kassannk** [comment]
@fauust @DanNixon

**Comment by kassannk** [comment]
@fauust @DanNixon 
HI,
Having studied the problem in detail, I also looked at the official repository of the molecule and came to the conclusion that running the molecule as root is the official recommended way to start it.

I also found that it is possible to start without root rights if changes are made to the bootloader grub. It looks like this:

```
1.Edit /etc/default/grub, change:

GRUB_CMDLINE_LINUX_DEFAULT="quiet splash"

to:

GRUB_CMDLINE_LINUX_DEFAULT="quiet splash systemd.legacy_systemd_cgroup_controller=1"
2. sudo update-grub
3. Reboot
```
But the problem is that launching systemd with flags, so that it works without root for you, can lead to an unpredictable impact of other customers.

As an option, I suggest you run a podman without root rights, but molecules with root rights. Until the drivers of the molecule are fixed

Thanks for your patience.

**Comment by DanHam** [comment]
@kassannk @fauust 

It seems we've been working on the same issue but from different directions - see the issue I opened for Podman [HERE](https://github.com/containers/podman/issues/10439).

We came to much the same conclusion as @kassannk - namely that the issue first reported by @fauust is caused by the user/group (`runner:podman`) not having write permissions to the required directory under `/sys/fs/cgroup/systemd/`. Giving the user the required write permissions allows podman to run systemd based containers in 'rootless' mode.

However, there is no need to change permissions on `/sys/fs/cgroup/systemd` as a whole. Changing permissions on ` /sys/fs/cgroup/systemd/system.slice/runner-provisioner.service` is all that is required:

```yaml
    - name: Change ownership on the cgroup to allow rootless podman to run systemd containers
      run: sudo chown -R $(id -un):$(id -gn) /sys/fs/cgroup/systemd/system.slice/runner-provisioner.service
```

**Comment by DanHam** [comment]
@kassannk

My feeling is that `runner:docker` should be the owner of `/sys/fs/cgroup/systemd/system.slice/runner-provisioner.service` by default.

This would be much the same as on a 'normal' system - When the user logs on, they are given read/write permissions on their user slice - typically `user.slice/user-1000.slice/user@1000.service`. 

The same should be true within the virtual environments provided by GitHub Actions.

**Comment by DanHam** [comment]
@fauust @DanNixon 

Forgive me if I've got some of the details wrong - I've only just come across this thread.

I too have been looking to use molecule + podman in a GitHub actions workflow so I'm reading through the above with great interest.

To summarise my understanding so far:

* You are both using Molecule with Podman as a driver
* Your container is running systemd as PID 1 - in other words the container is running `/lib/systemd/systemd` as the first command either via the `entrypoint` or `cmd` settings. 
* You are **not** able to run `molecule test` within the GitHub Actions environment as a normal user. However, you **are** able to run `molecule test` on your local systems as a normal user.
* Running `sudo molecule test` within the GitHub Actions environment works

@fauust 

* Running `chmod o+rwx -R /sys/fs/cgroup/systemd/` allowed you to successfully run your systemd based container with root-less podman
* Running `chmod o+rwx -R /sys/fs/cgroup/systemd/` **did not** resolve the issue with running `molecule test` as  a normal user

**Comment by fauust** [comment]
Hi @DanHam!
Your accurate synthesis is very welcome.

> Running chmod o+rwx -R /sys/fs/cgroup/systemd/ allowed you to successfully run your systemd based container with root-less podman

yes (with container `fauust/docker-systemd:debian-10` for instance)

> Running chmod o+rwx -R /sys/fs/cgroup/systemd/ did not resolve the issue with running molecule test as a normal user

yes

My understanding is that something in the molecule-podman driver make the container starting in a different way than when using podman commands and it leads to the issue that we are facing with GH Action runners.

Please note also that debugging the issue is not facilitated by a wrong error message from molecule IMO, see https://github.com/ansible-community/molecule-podman/issues/2#issuecomment-859075089.

**Comment by kassannk** [comment]
@fauust HI,
I apologize, but the problem has not yet been fully resolved. The problem is clearly on the side of the molecule drivers.
Also in GA there is no full-fledged management of a group of users, as in local ubuntu / debian, as a result of which this error arose. And more drastic changes need to be made, but this will affect the work of other users as well.
I recommend using the recommendations that have been listed in previous messages so far.
I am going to close this issue, please do not hesitate to contact us if the suggested methods stop working. Thank you.

**Comment by DanNixon** [comment]
@fauust

> > Running chmod o+rwx -R /sys/fs/cgroup/systemd/ allowed you to successfully run your systemd based container with root-less podman
> 
> yes (with container `fauust/docker-systemd:debian-10` for instance)
> 

Just to note, there is one difference between the working (where you invoke `podman` manually) and non-working (invoking via `molecule`) case, in the working case you pass the `--systemd` parameter to `podman run`.

This is supported by the Molecule Podman driver, but not yet released, if you manually install the prerelease version (see https://github.com/ansible-community/molecule-podman/releases/tag/v1.0.0a0) you will be able to use e.g. the following platform config and all will be good:
```yaml
  - name: ubuntu2004
    image: docker.io/geerlingguy/docker-ubuntu2004-ansible
    systemd: always
    override_command: false
    pre_build_image: true
```

@kassannk

> The problem is clearly on the side of the molecule drivers.

I disagree with this, despite what I mentioned above regarding the Molecule Podman driver. Could you explain your reasoning why the driver is at fault rather than differences between the actions environment and stock Ubuntu 20.04.

**Comment by kassannk** [comment]
@Da

> @fauust
> 
> > > Running chmod o+rwx -R /sys/fs/cgroup/systemd/ allowed you to successfully run your systemd based container with root-less podman
> > 
> > 
> > yes (with container `fauust/docker-systemd:debian-10` for instance)
> 
> Just to note, there is one difference between the working (where you invoke `podman` manually) and non-working (invoking via `molecule`) case, in the working case you pass the `--systemd` parameter to `podman run`.
> 
> This is supported by the Molecule Podman driver, but not yet released, if you manually install the prerelease version (see https://github.com/ansible-community/molecule-podman/releases/tag/v1.0.0a0) you will be able to use e.g. the following platform config and all will be good:
> 
> ```yaml
>   - name: ubuntu2004
>     image: docker.io/geerlingguy/docker-ubuntu2004-ansible
>     systemd: always
>     override_command: false
>     pre_build_image: true
> ```
> 
> @kassannk
> 
> > The problem is clearly on the side of the molecule drivers.
> 
> I disagree with this, despite what I mentioned above regarding the Molecule Podman driver. Could you explain your reasoning why the driver is at fault rather than differences between the actions environment and stock Ubuntu 20.04.

Hi.

Please note that GA is not the same as local ubuntu. This system has its own characteristics. Also, you may have noticed that there are no authorizations and user accounts in GA. And this is partly the problem, and it is not so easy to solve, and this will affect the rest of the GA components.
Why did I come to the conclusion that the problem is in the drivers of the molecule, because the podman is launched without root rights, but the molecule is not. That is, there are molecule specific systemd call commands, and this is the problem of the molecule

**Comment by fauust** [comment]
> Just to note, there is one difference between the working (where you invoke `podman` manually) and non-working (invoking via `molecule`) case, in the working case you pass the `--systemd` parameter to `podman run`.
> 
> This is supported by the Molecule Podman driver, but not yet released, if you manually install the prerelease version (see https://github.com/ansible-community/molecule-podman/releases/tag/v1.0.0a0) you will be able to use e.g. the following platform config and all will be good:
> 
> ```yaml
>   - name: ubuntu2004
>     image: docker.io/geerlingguy/docker-ubuntu2004-ansible
>     systemd: always
>     override_command: false
>     pre_build_image: true
> ```

Oh, I already test this but not using the latest molecule-podman driver! I will definitively try this tomorrow and let you know if that works. Having a CI running under `root` user is clearly not a comfortable situation even if it's not my infra. And this is one huge advantage from podman over docker (and one of the reason I am moving to podman).

BTW, `override_command: false` is interesting, I will try this one too, thanks!
(I understand that molecule will not start the `while true` loop but use the Docker entrypoint CMD)?

**Comment by DanNixon** [comment]
I thought I was getting somewhere earlier, but it seems not. I now seem to have an issue where rootless containers will sometimes start (i.e. the same commit will sometimes run `molecule test` as expected, or fail with the original error).

I've spent enough time on this and will likely just launch privileged containers on GH Actions, the benefits of rootless containers largely do not apply here anyway.

@kassannk 

> because the podman is launched without root rights, but the molecule is not.

Neither should be launched as root. One of the selling points of Podman is support for rootless containers, making them much more appropriate for use cases such as Molecule (for local use at least). Regardless, that does not quite explain why the driver is at fault.

@fauust 

> BTW, `override_command: false` is interesting, I will try this one too, thanks!
> (I understand that molecule will not start the `while true` loop but use the Docker entrypoint CMD)?

Pretty much, yes. It is useful if the Dockerfile already has an appropriate entrypoint and you don't want to repeat it in `molecule.yml`.

**Comment by fauust** [comment]
@DanNixon agree, I don't see why the molecule-podman driver is faulty (also given that, as said earlier, the molecule test suite works perfectly well locally on a very similar environment).

But I have also spent too much time on this and it works finally as root so, I will keep it that way for now.

> Pretty much, yes. It is useful if the Dockerfile already has an appropriate entrypoint and you don't want to repeat it in molecule.yml.

done https://github.com/fauust/ansible-role-mariadb/commit/4185f44164fb0b99965c377fe94ed6e4c74f9ff1

**Comment by fauust** [comment]
Hey @DanNixon!
I finally may have found a solution (thanks to @gotmax23, see https://github.com/ansible-community/molecule/discussions/3155#discussioncomment-1399189 and https://github.com/fauust/ansible-role-mariadb/commit/be3e1a07ee5d0992f2c3d03f22a4f3755a7343df
