### ISSUE TITLE
Rails feature tests have stopped running javascript feature tests

### ISSUE THREAD

**Issue by IanVaughan** [actions/virtual-environments#3548]
**Description**  
Our CI pipeline started failing our builds this morning, with errors relating to not running JavaScript.
Rerunning any previously passing CI builds also fails with the same errors.
This occurred a few times over the last year, of which last time it just started working again after a period of days.
See here for previous time https://github.community/t/rails-feature-tests-have-stopped-running-javascript/129485

**Question, Bug, or Feature?**:  
Bug

**Virtual environments affected**  
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [x] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Image version**
```
Environment: ubuntu-20.04
Version: 20210531.0
```

**Repro steps**  
Workflow yml and build log output: https://gist.github.com/IanVaughan/3add69d297d1f237f653ff8f65bdae54

**Comment by miketimofeev** [comment]
Hi @IanVaughan!
Could you please provide any repro steps besides the log and workflow and\or successful run logs on the same image version and commit? 
Unfortunately, it's pretty hard to investigate anything having only workflow files and failing logs.

**Comment by IanVaughan** [comment]
Hi @miketimofeev I really appreciate that, sorry for not sorting it out before raising it, but I wanted to get it logged sooner in case it correlated to anything.
I will extract code from my private repo into a public one over the next few days to reproduce this.

**Comment by dsame** [comment]
@IanVaughan 
I see ```raise ActionController::RoutingError, "No route matches [#{env['REQUEST_METHOD']}] #{env['PATH_INFO'].inspect}"``` that definitely says there's a problem in the code responsible to map request method+url  to the backend code and it has nothing to with the actions environment.

Moreover i see a note ` clicking on a link that performs a POST, now does a GET.` - i suppose you do not have a handler for POST methog in the code that used to handle GET requests.

**Comment by IanVaughan** [comment]
Hiya @dsame , thanks for your comments.
The raise occurs because the POST request that the JS should be doing is now doing a GET, which there is no route for.
When the tests are run locally or the action used via the server, it correctly does a POST and works fine.
Its only in the now current running GitHub Actions do these tests fail, and I've scheduled time this week to create a public repo to reproduce this issue, sorry for the delay so far.

**Comment by IanVaughan** [comment]
Hi, while reducing my current codebase to a simple example test repo, I found that it started working when removing some tests.
So far its non-deterministic, in that, I have 10 commits removing sub-folders of tests, and one commit onwards it starts passing. If I rebase that commit to the end, then it starts working onwards from a different commit.

What I've seen is that the assets have not loaded, eg there is no css or javascript loaded.
If I get the failed test artifact from GitHub a part of it looks like this:
<img width="470" alt="Screenshot 2021-06-23 at 17 45 55" src="https://user-images.githubusercontent.com/158600/123136503-e59ef380-d44a-11eb-86af-f66ec6ae2972.png">
Verses what it looks like when ran locally:
<img width="686" alt="Screenshot 2021-06-23 at 17 46 48" src="https://user-images.githubusercontent.com/158600/123136571-fea7a480-d44a-11eb-8a42-1395c4505040.png">

The tests are run with the same command both on CI and locally, via `bundler exec rspec`.

I'm still learning the internals of the asset pipeline so there might be something I'm missing, so I'm sure you might be tempted to mark this as a user issue.
But the fact that it works locally and not on GitHub Actions is odd to me, and the fact previous older commits that once passed now fail on re-runs should point to something outside the repo source and outside my control.
Its looking unlikely though that I will be able to produce a public repo to demonstrate this, so on those grounds I guess you may have to close this, and I fully understand that reasoning.
But regardless of the issue state, I will continue to dig in and report any findings on this, I'm on this task all this week!

**Comment by IanVaughan** [comment]
We found the issue, a cleaver colleague than me, dig into the logs and spotted 2 issues, the first I think being the cause.

1. running out of inotify watchers:
```
        FATAL: Listen error: unable to monitor directories for changes.
        Visit https://github.com/guard/listen/blob/master/README.md#increasing-the-amount-of-inotify-watchers for info on how to fix this.
```
1.1 The fix was to set `DISABLE_SPRING: true` in GitHub actions

2. syntax error in test.js
```
Compiling...
Compilation failed:
/home/runner/work/org/repo/config/webpack/test.js:7
import $ from 'jquery';
```
2.1 `test.js` hasn't changed for nearly a year, but JS libraries have been upgraded each week.
