### ISSUE TITLE
[macOS] Xcode 12.2 and 12.3 will be removed from Big Sur on June, 28

### ISSUE THREAD

**Issue by AlenaSviridenko** [actions/virtual-environments#3555]
**Breaking changes**
Xcode 12.2 and 12.3 will be removed from macOS 11 Big Sur on June, 28

**Target date**
Deployment will start on June, 28 and will take 2 days

**The motivation for the changes**
Big Sur is mostly requested for building with the latest Xcode 12.5, that provides new Swift 5.4 features and other fixes. So we'd like to keep Xcode 11.7 for old emulators and 2 latest stable Xcode versions.

**Possible impact**
Your project CI will be broken if it depends on Xcode 12.2 or 12.3

**Virtual environments affected**
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.13
- [ ] macOS 10.14
- [ ] macOS 10.15
- [x] macOS 11
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Mitigation ways**
Migrate your project to Xcode 12.4 or higher if you are using macOS 11, or use macOS 10.15 image where these Xcode versions will still live.

**Comment by miketimofeev** [comment]
The image without Xcodes 12.2 & 12.3 deployed.
