### ISSUE TITLE
AZ PowerShell Module Update + Bicep support

### ISSUE THREAD

**Issue by brwilkinson** [actions/virtual-environments#3558]
**Tool information**
- Tool name:                       AZ PowerShell Module
- Tool license: 
- Add or update?               Update
- Desired version: current 5.7.0, requesting 5.9.0 (or 5.8.0), latest is 6.0.0
- Approximate size: 
- If this is an add request:
  - Brief description of tool: 
  - URL for tool's homepage: https://docs.microsoft.com/en-us/powershell/azure/release-notes-azureps?view=azps-6.0.0
  - Provide a basic test case to validate the tool's functionality: 

The current issue that I am seeing is related to this: Az.Resources Module (**5.8.0 - April 2021**) in the current version that is installed on the Agents, was updated for Bicep to show warnings instead of errors (which break the deployment/pipeline)
[release notes for AZ PowerShell Module](https://docs.microsoft.com/en-us/powershell/azure/release-notes-azureps?view=azps-6.0.0#azresources-2) . . fixed in 5.8.0, however I think it makes sense  to go to 5.9.0 since it's the latest minor update prior to the major update?

![image](https://user-images.githubusercontent.com/3605266/121395970-c3b05780-c907-11eb-8b28-e5b84c71fca3.png)

I would also like to add another point here as well.

Since this update of the Az.Resources Module (**5.6.0 - March 2021**) the Cmdlet New-AzResourceGroupDeployment, now supports deploying file.bicep Bicep file extensions. However this does have a dependency on bicep.exe  which is not currently installed. https://github.com/azure/bicep#faq

https://docs.microsoft.com/en-us/powershell/azure/release-notes-azureps?view=azps-6.0.0#azresources-4

![image](https://user-images.githubusercontent.com/3605266/121396511-4df8bb80-c908-11eb-8d22-62d8136becc1.png)

#3461 has detailed instructions on the install. That issue was closed, however it would be great if this could also be installed/supported. (Several Tasks require this pre-req, which currently need a manual pre-step to install it.) This is also documented here:  https://docs.microsoft.com/en-us/azure/azure-resource-manager/bicep/install Like I mentioned it's a pre-requisite to using the Az.Resources Module for some Cmdlets since March.

**Area for Triage**:

**Question, Bug, or Feature?**:

**Virtual environments affected**
- [x] Ubuntu 16.04
- [x] Ubuntu 18.04
- [x] Ubuntu 20.04
- [x] macOS 10.15
- [x] macOS 11
- [x] Windows Server 2016 R2
- [x] Windows Server 2019

**Can this tool be installed during the build?**

**Tool installation time in runtime**

**Are you willing to submit a PR?**

**Comment by sugam192** [comment]
Hey guys, do we know when  AZ powershell v6 is planned for Windows Server 2019?
I am specifically looking for Az.Websites
https://docs.microsoft.com/en-us/powershell/azure/release-notes-azureps?view=azps-6.0.0#azwebsites-2

**Comment by brwilkinson** [comment]
@sugam192 did you have a specifc issue that you are running into? I was told that upgrades are on an as needed basis, so if you have a specifc bug that was resolved for you, you could mention it as a reason. 6.0.0 is a major release, which also brings breaking changes, so it's harder to update, or often may take more time. It may also contain new bugs, which need patching. So generally a 6.0.x release would likely be more stable.

You can also use the following to upgrade during the deployment. It runs fairly fast. 

steps​:
    - ​task​: ​AzurePowerShell@5​
      ​inputs​:
        ​azureSubscription​: ​'​<>​'​
        ​ScriptType​: ​'​InlineScript​'​
        ​preferredAzurePowerShellVersion​: ​'​6.0.0​'

**Comment by AlenaSviridenko** [comment]
Hi @brwilkinson, as for the separate bicep support - we do not have plans to add it to the images, because there are 2 actions for this tool, and using actions is a preferred way to interact with the images. See details here https://github.com/actions/virtual-environments/issues/3461
Thanks.

**Comment by miketimofeev** [comment]
We have added azure powershell 5.9.0 to all the images.
The new image rollout will start on Monday\Tuesday and take 3-4 days to propagate to all the environments.

**Comment by jikuja** [comment]
> Hi @brwilkinson, as for the separate bicep support - we do not have plans to add it to the images, because there are 2 actions for this tool, and using actions is a preferred way to interact with the images. See details here #3461
> Thanks.

Let's try to remember that the same environment is used also as Azure pipeline agents. Those actions do not help with that.

**Comment by jikuja** [comment]
For Powershell bicep support it might be better to ask Az.Resources module bundles bicep binary just like AZ CLI handles bicep currently.

**Comment by AlenaSviridenko** [comment]
It can be installed in runtime in Azure Pipelines, there are steps on how to install it in the issue I linked above. We are currently focused on stabilizing our current images, because they are overloaded with different tools, we are reconsidering tools installation approach and the content of the images itself to come up with better solution in the future.

**Comment by miketimofeev** [comment]
@brwilkinson we have updated the az powershell module to 5.9.0 on all the images. Bicep will be added a bit later — you can follow this issue https://github.com/actions/virtual-environments/issues/3461
I'm going to close this issue. Please feel free to contact us if you have any concerns.
Thank you!
