### ISSUE TITLE
Add Boost on MacOS

### ISSUE THREAD

**Issue by mathbagu** [actions/virtual-environments#356]
**Tool information**
- Tool name: Boost library
- Add or update? Add
- Desired version: 1.69 (same everywhere)
- Approximate size:
- If this is an add request:
  - Brief description of tool: Use GitHub actions to compile open-source C++ projects on every supported environment (linux, windows and MacOS).
  - URL for tool's homepage: https://www.boost.org/doc/libs/1_69_0/doc/html/quickbook/install.html

**Area for Triage**:

C/C++

**Question, Bug, or Feature?**:

Feature
**Virtual environments affected**
- [X] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Can this tool be installed during the build?**

Not sure

**Are you willing to submit a PR?**

No

**Comment by thejoebourneidentity** [comment]
Thanks for your suggestion 🙏. Considering the maintenance concerns for the added disk footprint, this is not something we will add to the image at this time.

**Comment by erenon** [comment]
I understand that inflating the image size is not desirable. As an alternative solution, would you consider to setup a cache space, where jobs can save temp artifacts, e.g: a boost build? That way we could avoid the extreme load of downloading and building boost to run tests on OSX.

**Comment by maxim-lobanov** [comment]
@erenon , I would advice to take a look at https://github.com/actions/cache. This task can help build Boost once and save result. And then use cached build results

**Comment by erenon** [comment]
@maxim-lobanov : Thanks! This works. I raised a PR to add the relevant example to actions/cache:
https://github.com/actions/cache/pull/206
