### ISSUE TITLE
error during connect: This error may indicate that the docker daemon is not running.

### ISSUE THREAD

**Issue by gonchalo620** [actions/virtual-environments#3565]
**Description**  
I generated the windows 2019 image, configured it in a scale set in Azure and configured the agent pools in Azure DevOps. When I try to run docker commands I get the following error.

![image](https://user-images.githubusercontent.com/12538951/121571643-e6ff0380-c9e8-11eb-9876-25b437098404.png)

"C:\Program Files\Docker\docker.exe" pull hello-world:latest
error during connect: This error may indicate that the docker daemon is not running.: Post http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/images/create?fromImage=hello-world&tag=latest: open //./pipe/docker_engine: Access is denied.
"C:\Program Files\Docker\docker.exe" inspect hello-world:latest
error during connect: This error may indicate that the docker daemon is not running.: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/containers/hello-world:latest/json: open //./pipe/docker_engine: Access is denied.

**Question, Bug, or Feature?**:  
Bug"

**Virtual environments affected**  
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016 R2
- [*] Windows Server 2019

**Image version**
# Microsoft Windows Server 2019 Datacenter
- OS Version: 10.0.17763 Build 1935
- Image Version: 20210516.0

**Comment by miketimofeev** [comment]
Hi @gonchalo620!
Do you have Configure VMs to run interactive tests option enabled?
![image](https://user-images.githubusercontent.com/48208649/121574415-ebe6a600-ca2e-11eb-89c3-7e3289a42774.png)

**Comment by miketimofeev** [comment]
@gonchalo620 could you please also take a look at this answer?
https://github.com/actions/virtual-environments/issues/3180#issuecomment-835298904

**Comment by miketimofeev** [comment]
@gonchalo620 
https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/scale-set-agents?view=azure-devops
![image](https://user-images.githubusercontent.com/48208649/122094035-5b380d80-ce14-11eb-9ff6-520e71264534.png)
