### ISSUE TITLE
Update AWS SAM CLI to version 1.24.1

### ISSUE THREAD

**Issue by benjaminfiliatrault** [actions/virtual-environments#3566]
**Tool information**
- Tool name: AWS SAM CLI
- update
- Desired version: 1.24.1

**Area for Triage**:

**Virtual environments affected**
- [ ] Ubuntu 16.04
- [x] Ubuntu 18.04
- [x] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Bug**:
The current version of SAM CLI is failing with the current error:
```
ModuleNotFoundError: No module named 'configparser'
```
The only way to solve this is with the version 1.24.1
https://github.com/aws/aws-sam-cli/issues/2927

**Can this tool be installed during the build?**
The tool could be upgraded during build time but as per the AWS SAM CLI doc, both upgrade command doesn't work on the pipeline.

```
sudo ./sam-installation/install --update
```
```
brew upgrade aws-sam-cli
```

### Temporary solution 
use Ubuntu-16.04 which is still using the version 1.23.0

**Comment by miketimofeev** [comment]
Hi @benjaminfiliatrault!
The new images with updated aws-sam-cli will be deployed next week.
You can update to the latest version in runtime using the following snippet:
```
zipName="aws-sam-cli-linux-x86_64.zip"
zipUrl="https://github.com/aws/aws-sam-cli/releases/latest/download/${zipName}"
curl $zipUrl -4 -sL --compressed -o "/tmp/$zipName"
unzip -qq /tmp/${zipName} -d /tmp
sudo /tmp/install --update
sam --version
```

**Comment by miketimofeev** [comment]
@benjaminfiliatrault Ubuntu 18&20 images have been updated with aws-sam-cli 1.24.1 ob board.
I'm going to close the issue. Please feel free to contact us if you have any concerns.
Thank you!
