### ISSUE TITLE
Windows Aarch64 builds fail due to missing libcpmt.lib

### ISSUE THREAD

**Issue by dholmes-ora** [actions/virtual-environments#3567]
**Description**  

In the OpenJDK project our Windows Aarch64 builds have been failing due to:

LINK : fatal error LNK1104: cannot open file 'libcpmt.lib' 

A google search suggests this is may be due to a misconfigured Visual Studio environment.

**Area for Triage**:  

Java ?

**Question, Bug, or Feature?**:  

Bug

**Virtual environments affected**  
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016 R2
- [x] Windows Server 2019

**Image version**

 Version: 20210531.1

**Expected behavior**  

No LINK error

**Actual behavior**  

LINK : fatal error LNK1104: cannot open file 'libcpmt.lib' 

**Repro steps**  

https://github.com/dholmes-ora/jdk/runs/2769789699?check_suite_focus=true

**Comment by miketimofeev** [comment]
Hi @dholmes-ora!
Is it possible to create any minimal repro as the current workflow looks pretty complicated and it can take significant time for us to analyze all the steps in the search of the root cause?

**Comment by dsame** [comment]
@dhadka can you please double check `libcpmt.lib` picked up by linker is the same (64/32bit architecture) as the build target?

**Comment by dhadka** [comment]
@dholmes-ora ☝️ (I believe that mention was meant for you 😄)

**Comment by dholmes-ora** [comment]
Sorry my github notifications are disabled to avoid getting duplicated notices from our workflows.

I can't help with any minimal repro I'm afraid, I am simply an end-user.

**Comment by dholmes-ora** [comment]
This is a cross-compilation situation:

checking for cl... $FIXPATH /cygdrive/c/progra~2/micros~1/2019/enterp~1/vc/tools/msvc/1428~1.293/bin/hostx64/arm64/cl.exe
checking resolved symbolic links for CXX... no symlink
configure: Using microsoft C++ compiler version 19.28.29337 [Microsoft (R) C/C++ Optimizing Compiler Version 19.28.29337 for ARM64]

So possibly it is finding the wrong architecture library.

**Comment by dholmes-ora** [comment]
Correction. The tool being built (adlc.exe) runs on the build host, so in this case it should be an x86_64 binary. So perhaps the problem is that the wrong link.exe is being used ...

**Comment by dsame** [comment]
@dholmes-ora 
I double checked the instructions for building OpenJDK on the windows and it says they supports only cygwin build.

According to that i removed the VC related lines from the workflow https://github.com/dsame/jdk/commit/f13d168e147fe6e8b847dd497be18a1981e7658d

and i got the success build https://github.com/dsame/jdk/runs/2844995406?check_suite_focus=true

Can you please follow my steps and make sure the artefact can be used your environment?

Also i want to note you do not have any of the actions tasks and there's no specific github related problems during the build. The more productive way to cross build aarch64 binary on windows host is to contact OpenJDK support team.

**Comment by dholmes-ora** [comment]
@dsame Appreciate the assistance here. I'm now treating this as a bug at our end. We have removed the problematic windows-aarch64 build from our project workflow until the folks in charge of that port determine exactly what the problem is. It was working in the past and no longer does, so something changed, but it is up to others to determine exactly what. Thanks again for the help - much appreciated. I will add your findings to our bug report. I guess I can just close this issue now.

**Comment by dholmes-ora** [comment]
@dsame I don't have  a specific link - not sure how to find one. The support for building Windows-Aarch64 was added to our repo back on Dec 9, 2020 and AFAIK was working until a some weeks ago (unsure when exactly it started).

**Comment by magicus** [comment]
Just for the record; cl.exe and cygwin work fine together. The special care needed to make this work is handled by the JDK build system. Building on Windows/aarch64 used to work fine in the past.

@dsame The relevant change you did was dropping `--with-msvc-toolset-version` from the configure line. Without that, `configure` tries to use the default installed version of Visual Studio, which was 14.29. And this works fine. 

I'm pretty certain 14.28 used to work for us, and I have a hard time imagining any changes done in our code base that could have caused this breakage, so I assume something has changed in the environment of the VMs. Perhaps an additional msvc package that we indirectly need was installed by default before, but not anymore..? If so, the fault is arguably ours, since we try to make sure that all parts that we need are installed explicitly, instead of relying on defaults.
