### ISSUE TITLE
Add clang-tidy on Ubuntu and MacOS

### ISSUE THREAD

**Issue by mathbagu** [actions/virtual-environments#357]
**Tool information**
- Tool name: clang-tidy
- Add or update? Add
- Desired version: Same version than clang
- Approximate size: 2 Mo
- If this is an add request:
  - Brief description of tool: C++ linter
  - URL for tool's homepage: https://clang.llvm.org/extra/clang-tidy/

**Area for Triage**:
C/C++

**Question, Bug, or Feature?**:
Feature

**Virtual environments affected**
- [X] macOS 10.15
- [X] Ubuntu 16.04 LTS
- [X] Ubuntu 18.04 LTS
- [X] Windows Server 2016 R2
- [X] Windows Server 2019

**Can this tool be installed during the build?**
Probably

**Are you willing to submit a PR?**
No

**Comment by mathbagu** [comment]
I tried to install it on ubuntu using `sudo apt install clang-tidy` but it fails:
```
```

**Comment by diagprov** [comment]
The "obvious way" of installing `clang-tidy` during the build, i.e. installing it via apt, fails:

```
Run sudo apt-get install -y clang-tidy
Reading package lists...
Building dependency tree...
Reading state information...
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 clang-tidy : Depends: clang-tidy-6.0 (>= 6.0~) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
##[error]Process completed with exit code 100.
```

This is likely because the ubuntu images add a PPA for clang/llvm, which causes ubuntu packages to conflict with ppa packages and generally creates a mess.

**Comment by thejoebourneidentity** [comment]
Thanks for your suggestion 🙏. Considering the current compatibility issues, and maintenance concerns, this is not something we will add to the image at this time.

**Comment by mathbagu** [comment]
@thejoebourneidentity @diagprov 
I install manually clang-tidy-9 on ubuntu using what I found in [llvm.sh](https://apt.llvm.org/llvm.sh) used by the [clang.sh](https://github.com/actions/virtual-environments/blob/master/images/linux/scripts/installers/clang.sh) script:
```
- name: Install clang-tidy
  run: |
      sudo apt-get install -y clang-tidy-9
      sudo update-alternatives --install /usr/bin/clang-tidy clang-tidy /usr/bin/clang-tidy-9 100
```
It also works fine for clang-tidy-8 but it's not ok for clang-tidy-6.0:
```
The following packages have unmet dependencies:
 clang-tidy-6.0 : Depends: libllvm6.0 (= 1:6.0-1ubuntu2) but 1:6.0.1~svn334776-1~exp1~20190309042703.125 is to be installed
E: Unable to correct problems, you have held broken packages.
```

**Comment by diagprov** [comment]
@mathbagu thanks, that's useful to know and better than my solution :). I'm not generally familiar with ubuntu's internals and didn't look too hard to be honest.
