### ISSUE TITLE
/usr/local/bin/bundle disappeared from the latest ubuntu-20.04 image

### ISSUE THREAD

**Issue by anthonyfok** [actions/virtual-environments#3573]
**Description**  
/usr/local/bin/bundle (and /usr/local/bin/bundler) was in ubuntu-20.04 image version 20210419.1, but no longer found in version 20210606.1.

GitHub Actions such as limjh16/jekyll-action-ts which relies on `bundle` now fails with the error:

> Error: Unable to locate executable file: bundle. Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also check the file mode to verify the file is executable.

See limjh16/jekyll-action-ts#18 and OpenDRR/documentation#13 for more details.

**Area for Triage**:  

Packages?  Ruby?

**Question, Bug, or Feature?**:  

Bug?

**Virtual environments affected**  
- [ ] Ubuntu 16.04 (I did not check)
- [ ] Ubuntu 18.04 (I did not check)
- [x] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Image version**

Image version where you are experiencing the issue.
20210606.1

**Expected behavior**  
/usr/local/bin/bundle is available like in image version 20210419.1

**Actual behavior**  
/usr/local/bin/bundle is not available.

`bundle` is still available in other paths or in other names elsewhere on the system, but not as `bundle` in the system PATH:

```
[-rwxrwxrwx runner   docker          2841 Apr  5 11:46]  /opt/hostedtoolcache/Ruby/2.5.9/x64/lib/ruby/gems/2.5.0/gems/rake-12.3.3/bin/bundle
[-rwxrwxrwx runner   docker           557 Apr  5 17:00]  /opt/hostedtoolcache/Ruby/2.6.7/x64/bin/bundle
[-rwxrwxrwx runner   docker           559 Apr  5 17:00]  /opt/hostedtoolcache/Ruby/2.6.7/x64/bin/bundler
[-rwxrwxrwx runner   docker          2841 Apr  5 11:48]  /opt/hostedtoolcache/Ruby/2.6.7/x64/lib/ruby/gems/2.6.0/gems/rake-12.3.3/bin/bundle
[-rwxrwxrwx runner   docker           557 Apr  5 17:00]  /opt/hostedtoolcache/Ruby/2.7.3/x64/bin/bundle
[-rwxrwxrwx runner   docker           559 Apr  5 17:00]  /opt/hostedtoolcache/Ruby/2.7.3/x64/bin/bundler
[-rwxrwxrwx runner   docker          2841 Apr  5 12:39]  /opt/hostedtoolcache/Ruby/2.7.3/x64/lib/ruby/gems/2.7.0/gems/rake-13.0.1/bin/bundle
[-rwxrwxrwx runner   docker           557 Apr  5 17:01]  /opt/hostedtoolcache/Ruby/3.0.1/x64/bin/bundle
[-rwxrwxrwx runner   docker           559 Apr  5 17:01]  /opt/hostedtoolcache/Ruby/3.0.1/x64/bin/bundler
[-rwxrwxrwx runner   docker          2841 Apr  5 12:33]  /opt/hostedtoolcache/Ruby/3.0.1/x64/lib/ruby/gems/3.0.0/gems/rake-13.0.3/bin/bundle
[-rwxr-xr-x root     root             529 Apr 15 14:38]  /usr/bin/bundle2.7
[-rwxr-xr-x root     root             531 Apr 15 14:38]  /usr/bin/bundler2.7
[-rwxrwxrwx root     root            2841 Apr  1  2020]  /usr/share/rubygems-integration/all/gems/rake-13.0.1/bin/bundle
```

**Repro steps**  
See the GitHub workflow run at https://github.com/OpenDRR/documentation/actions/runs/926023494

(In latest run, I have worked around the issue with `sudo apt update && sudo apt install ruby-bundler`.)

**Final thoughts**
I suspect the disappearance of /usr/local/bin/bundle was unintended, and I wasn't able to find any commit that explicitly removed it from the Ubuntu runners.  (I did find its removal from Windows, but that's not related to this bug.)

Admittedly, while "Bundler version 2.1.4" is listed under "Package Management" in images/macos/macos-10.15-Readme.md, Bundler was apparently never listed in images/linux/Ubuntu2004-README.md or alike.

Regardless whether you want to have /usr/local/bin/bundle available or not, I guess a bit more clarification on this would be helpful so that GitHub Actions developers can know whether to rely on `bundle` being available or not.

Many thanks!

**Comment by al-cheb** [comment]
Hello, @anthonyfok.
Thank you for your report. We will take a look.

**Comment by al-cheb** [comment]
@anthonyfok,
It is recommended to use official Ruby action to make sure that your build uses specific Ruby version: https://github.com/ruby/setup-ruby, [Official Ruby binaries will be installed on images by default](https://github.com/actions/virtual-environments/issues/2193).

**Comment by dibir-magomedsaygitov** [comment]
Hello @anthonyfok. I'm going to close this issue since it is not image related. As @al-cheb mentioned, we recommend you to use https://github.com/ruby/setup-ruby action and install `bundler `in runtime. In case of any questions feel free to contact us. Thank you.
