### ISSUE TITLE
extremely slow Network and Disk IO on Windows agent compared to Ubuntu/Mac

### ISSUE THREAD

**Issue by jetersen** [actions/virtual-environments#3577]
**Description**  
Actually we are seeing the same behavior on GitHub actions running a shell command for `dotnet restore` takes a very long time on windows even when using actions/cache 😅

_Originally posted by @jetersen in https://github.com/actions/virtual-environments/issues/1733#issuecomment-860123620_

I cannot replicate locally where a restore with a full nuget cache it takes less than a second.

**Area for Triage**:  
.NET Core

**Question, Bug, or Feature?**:  
Bug

**Virtual environments affected**  
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [x] Windows Server 2016
- [x] Windows Server 2019
- [x] Windows Server 2022

**Image version**
```
Current runner version: '2.278.0'
Operating System
  Microsoft Windows Server 2019
  10.0.17763
  Datacenter
Virtual Environment
  Environment: windows-2019
  Version: 20210531.1
  Included Software: actions/virtual-environments@win19/20210531.1/images/win/Windows2019-Readme.md
  Image Release: actions/virtual-environments@win19%2F20210531.1 (release)
```

**Expected behavior**  
actions/cache should speed up dotnet restore to take a few seconds

**Actual behavior**  
Dotnet restore even with actions/cache takes well over 30 seconds.

**Repro steps**  
https://github.com/jetersen/dotnet.restore.slow.github.action

**Comment by al-cheb** [comment]
Hello, @jetersen.
Please provide a small repo how to reproduce the issue.

**Comment by jetersen** [comment]
Well repro was super easy actually.

https://github.com/jetersen/dotnet.restore.slow.github.action

[No cache 41s](https://github.com/jetersen/dotnet.restore.slow.github.action/runs/2826777499?check_suite_focus=true)
[Cached 33s](https://github.com/jetersen/dotnet.restore.slow.github.action/runs/2826786383?check_suite_focus=true)

Locally on my machine the cache speeds up the restore to under 1 seconds. Starting dotnet restore also seem relatively slow when called through pwsh shell 😰

**Comment by jetersen** [comment]
The scary part is that the slowness is consistent at least according to the dotnet restore timings.

**Comment by jetersen** [comment]
WOW...

[Ubuntu-20.04 no cache 14s](https://github.com/jetersen/dotnet.restore.slow.github.action/runs/2826850092)
[Ubuntu-20.04 with cache 7s](https://github.com/jetersen/dotnet.restore.slow.github.action/runs/2826869419?check_suite_focus=true)
MacOS seems to also benefit from the cache with 7s before cache it was 57s.

This is more along the lines of what I would expect.

**Comment by jetersen** [comment]
In log you can clearly see the timescale on windows not making sense but it is consistent.

```
  Determining projects to restore...
  Restored D:\a\dotnet.restore.slow.github.action\dotnet.restore.slow.github.action\tests\Library.UnitTests\Library.UnitTests.csproj (in 20.78 sec).
  Restored D:\a\dotnet.restore.slow.github.action\dotnet.restore.slow.github.action\tests\Api.UnitTests\Api.UnitTests.csproj (in 20.78 sec).
  Restored D:\a\dotnet.restore.slow.github.action\dotnet.restore.slow.github.action\src\Library\Library.csproj (in 2 ms).
  Restored D:\a\dotnet.restore.slow.github.action\dotnet.restore.slow.github.action\src\Api\Api.csproj (in 9 ms).
```

**Comment by jetersen** [comment]
@al-cheb Hope the repro is good enough, we were seeing the similar behavior in our private repo on our unit test project but also on some of our projects with more dependencies. We do restore our internal packages from an internal nuget source but it shouldn't effect caching.

**Comment by al-cheb** [comment]
@jetersen, Looks like it doesn't work only with `.net core 5.0.301`. It is recommended to use `actions/setup-dotnet@v1` task to pick up version:

E.g. - https://github.com/vsafonkin-test-organization/dotnet.restore.slow.github.action/runs/2829395627?check_suite_focus=true
```
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.300'

      - uses: actions/cache@v2
        with:
          path:
            ~/.nuget/packages
          key: ${{ runner.os }}-nuget-5.0.300-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-
            
      - name: dotnet restore
        run: |
          dotnet restore --verbosity n
```

![image](https://user-images.githubusercontent.com/47745270/122054955-d12a7d80-cdf0-11eb-8eba-beb8a82cbcd6.png)

**Comment by jetersen** [comment]
Good thing is you now have an good repro case to fix it and hopefully it won't reappear in the next dotnet release 😅

**Comment by vsafonkin** [comment]
Hi @jetersen, dotnet 6.0 (preview version) also works properly. Looks like this bug affects only the latest patch version of 5.0

**Comment by jetersen** [comment]
@vsafonkin odd, I guess someone else already caught the regression 😅

**Comment by jetersen** [comment]
@vsafonkin @al-cheb I think we can close it as you mentioned it only affects the latest patch. I would still like to know what went wrong in the latest patch but not sure it is something we can fix here :)

**Comment by SteveDesmond-ca** [comment]
This is still happening with the latest version of .NET (6.0.x) -- I have projects consistently taking multiple minutes to restore a minimal set of dependencies.

**Comment by jetersen** [comment]
I have noticed the same thing recently.

**Comment by jetersen** [comment]
Just saw a 1 minute restore for very basic test packages:
https://github.com/specshell/specshell.software.ndde/runs/4481718755?check_suite_focus=true

**Comment by vsafonkin** [comment]
Hi @jetersen, I cannot reproduce it for 6.0.100 version:
restore without caching about 2 min: [run](https://github.com/vsafonkin-test-organization/dotnet.restore.slow.github.action/runs/4483733816?check_suite_focus=true)
restore with caching about 3 sec: [run](https://github.com/vsafonkin-test-organization/dotnet.restore.slow.github.action/runs/4483750809?check_suite_focus=true)

Looks like it works properly or I miss something?

**Comment by SteveDesmond-ca** [comment]
My latest test shows that it's not just `dotnet restore`, but almost the entire `windows-latest` environment is at least an order of magnitude slower than the exact same workflow running on `ubuntu-latest` ([diff](https://github.com/ecoAPM/WiFiSurveyor/compare/48463a8..b1427ae)).

| Step | Ubuntu [run](https://github.com/ecoAPM/WiFiSurveyor/runs/4475788253?check_suite_focus=true) | Windows [run](https://github.com/ecoAPM/WiFiSurveyor/runs/4483942534?check_suite_focus=true) |
|:----|----:|----:|
| Checkout | 1 s | 12 s |
| Install .NET | 13 s | 64 s |
| Restore | 8 s | 120 s |
| Build | 4 s | 8 s |
| Test | 6 s | 7 s |
| Total | 34 s | 216 s |

The build and test steps are close enough, but all of the actions that require some sort of network transfer are extremely slow. Is this a known issue with Windows environments, and if so, can something be added to documentation somewhere to indicate that the huge performance hit is expected?

**Comment by jetersen** [comment]
@SteveDesmond-ca nice comparison, I can definitely attest to this based on our private repos.

**Comment by jetersen** [comment]
Ya, okay now the issue is no longer dotnet restore but networking is a significant issue in the test case I built:

[action: skip telemetry and other slow downs DotNet #7](https://github.com/jetersen/dotnet.restore.slow.github.action/runs/4495662274?check_suite_focus=true)
![image](https://user-images.githubusercontent.com/1661688/145697415-160a09e7-0a29-467a-89a1-9573d299c275.png)
![image](https://user-images.githubusercontent.com/1661688/145697386-62715fba-a302-4f8e-bd92-fc3de85fd1ed.png)

**Comment by zcsizmadia** [comment]
I had cases when restore took a long time when nuget.org was not available to check the signatures. Setting env var    NUGET_CERT_REVOCATION_MODE to offline solved that perticular problem. Maybe it is the same issue? 
https://docs.microsoft.com/en-us/nuget/reference/errors-and-warnings/nu3028

**Comment by jetersen** [comment]
@zcsizmadia well as we just discussed in the last two comments is that restore is not really the issue but rather the networking seems to be a order of magnitude slower.

**Comment by jetersen** [comment]
@vsafonkin @al-cheb the slowness seems to affect all the windows VM: https://github.com/jetersen/dotnet.restore.slow.github.action/actions/runs/1568508906

Although windows 2022 seems to handle have a little faster tar.exe which is good I guess 😄

I am not saying we should fix windows 2016 but at least look at 2019 and 2022. And figure out why they are SO much slower than ubuntu or even macos.

![image](https://user-images.githubusercontent.com/1661688/145856265-91791ada-2379-4004-9ec5-dbe979f9bc14.png)

**Comment by jetersen** [comment]
I think I found the culprit on windows it is the System.Net.HttpClient:
https://github.com/jetersen/dotnet.restore.slow.github.action/blob/main/.github/workflows/ci.yml

Note I tried to switch from use of powershell to pwsh with no luck. It is still the System.Net.HttpClient being slow.

Here I tried using curl.exe which seems to be able to download it 2-3x faster.
![image](https://user-images.githubusercontent.com/1661688/145875197-b5dd9d74-a924-4888-9ba7-ada94704e166.png)
![image](https://user-images.githubusercontent.com/1661688/145875847-7ce15236-8c43-4e66-811b-764d6c788891.png)

**Comment by SteveDesmond-ca** [comment]
I'm starting to look at timestamps in various actions, which is leading me to believe this is actually a disk I/O issue, not a network I/O issue.

**Comment by jetersen** [comment]
@SteveDesmond-ca care to explain the speed difference in curl than? 😅

**Comment by SteveDesmond-ca** [comment]
Turns out it's both! Here is a minimal repro that doesn't even use .NET at all: downloading dependencies via `yarn` (for a real-world medium-sized app) has the same discrepancies between `ubuntu-latest` and `windows-latest`

https://github.com/SteveDesmond-ca/gh-actions-windows-slow/actions/runs/1574970778
| OS | Shell | Startup | Download 500 `tgz` | Create 1K dirs | Copy 12K files |
| --- | --- | ---:| ---:| ---:| ---:|
| `ubuntu-latest` | `bash` | 0.4 s | 8.8 s | 2.1 s | 3.5 s |
| `ubuntu-latest` | `pwsh` | 0.4 s | 11.0 s | 1.8 s | 4.9 s |
| `windows-latest` | `bash` | 11.1 s | 85.4 s | 2.3 s | 4.4 s |
| `windows-latest` | `pwsh` | 10.0 s | 99.9 s | 3.9 s | 6.0 s |

As you can see, there are also compounding performance issues when using `pwsh` (the default on `windows-latest`) vs `bash` -- this may also contribute to @jetersen's remark that `windows-2022` is slightly faster, since `pwsh` on `windows-2022` is probably running a newer (faster) version of .NET under the hood.

**Comment by jetersen** [comment]
I don't think it is specifically `pwsh` that is the issue since I have several .NET repos using `pwsh` and `ubuntu-latest` with no restore penalty.

**Comment by jetersen** [comment]
@SteveDesmond-ca decided to test it, with your test... it is scary how bad this actually is.

2019 is a whole minute slower than 2022 🤯


| OS |	Shell |	Startup |	Download 500 `tgz` |	Create 1K dirs |	Copy 12K files |
|---|---|---|---|---|---|
| `ubuntu-latest` | `bash` | 0.4 s | 8.8 s	| 2.1 s | 3.5 s |
| `ubuntu-latest` | `pwsh` | 0.4 s | 11.0 s	| 1.8 s | 4.9 s |
| `windows-2019` | `bash` | 11.1 s | 85.4 s | 2.3 s | 4.4 s |
| `windows-2019` | `pwsh` | 10.0 s | 99.9 s | 3.9 s | 6.0 s |
| `windows-2022` | `bash` | 11.1 s | 85.4 s | 2.3 s | 4.4 s |
| `windows-2022` | `pwsh` | 10.0 s | 99.9 s | 3.9 s | 6.0 s |

**Comment by jetersen** [comment]
misclick 😅

**Comment by jetersen** [comment]
Timings from yesterday around 14:00 CET. Shows that this is still an issue.

![image](https://user-images.githubusercontent.com/1661688/147471716-1e57b186-e662-4119-9587-e8c4694d5713.png)

**Comment by vsafonkin** [comment]
@jetersen, we are still investigating it, actually I'm confused that downloading via curl has very similar performance. For example, powershell script (download ~200 Mb 200 times):
```
For ($i = 0; $i -lt 200; $i++) {
  $outfile = "dotnet-$i.zip"
  curl https://dotnetcli.azureedge.net/dotnet/Sdk/5.0.403/dotnet-sdk-5.0.403-win-x64.zip -o $outfile
  rm $outfile
}
```
and result:
<img width="340" alt="Screenshot 2021-12-28 at 4 40 57 PM" src="https://user-images.githubusercontent.com/7628945/147572419-a0bfe635-d2b6-45ec-9ff1-56b09f83ac2a.png">

**Comment by al-cheb** [comment]
@jetersen , @SteveDesmond-ca , Could you check a restore step with params?
```
- name: Restore deps
  run: |
        dotnet new nugetconfig
        dotnet restore -v n --packages D:\pkgs
```

**Comment by jetersen** [comment]
@al-cheb that does not resolve the fact that downloading .NET 6 is also slower.
The issue title has changed to be generic: Network and Disk IO in general seems slower on the windows agent.
Where curl on windows for some reason does not have this issue.

**Comment by al-cheb** [comment]
> @al-cheb that does not resolve the fact that downloading .NET 6 is also slower. The issue title has changed to be generic: Network and Disk IO in general seems slower on the windows agent. Where curl on windows for some reason does not have this issue.

Ubuntu agents have slightly higher IOPS disk performance configuration.  We use [install-dotnet.ps1](https://github.com/actions/setup-dotnet/blob/main/externals/install-dotnet.ps1) script for installation provided by DotNet team . The  `DownloadFile` and `Extract-Dotnet-Package` functions are being slow. We will investigate how to improve performance  those 
 functions if we replace `DownloadFile` -> `WebClient` and  `Extract-Dotnet-Package` -> 7zip

![image](https://user-images.githubusercontent.com/47745270/148731948-25edc5b6-2be1-4688-a4d9-c0f76e7b465b.png)

**Comment by jetersen** [comment]
@al-cheb https://github.com/jetersen/dotnet.restore.slow.github.action/commit/f342429d66b14ce848b79cd59733e00bd9536cb1 does indeed help with nuget restore. I used a different approach to what you mentioned.

**Comment by vsafonkin** [comment]
@jetersen, how we see this issue is not related to network configuration of the Windows runner. We have tested Windows image from Azure Marketplace and got the same network performance. Looks like the problem appears from .NET side because we see performance degradation with newer versions of .NET(for example restore on .NET 5.0 is slower then restore on .NET 3.1). Also there is an issue with precached Nuget packages placed on `C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\` directory on the runner: restoring packages from cache is more slowly then downloading from nuget.org, so default nuget config (command `dotnet new nugetconfig`) contains only nuget.org feed and has better performance. Probably it's related to IO disk operations and looks like there is nothing we can do from our side unfortunately. 

As @al-cheb mentions above Ubuntu agents have slightly higher IOPS disk performance configuration.

**Comment by jetersen** [comment]
I think `dotnet new nugetconfig` is a fine solution perhaps some of these things should be documented in the `setup-dotnet` action or somewhere it makes sense.

Of course there is still the issue with `setup-dotnet` being slow to install .NET SDK

**Comment by vsafonkin** [comment]
> Of course there is still the issue with `setup-dotnet` being slow to install .NET SDK

Yes, but to install the .NET SDK, the `setup-dotnet` action uses scripts maintained by DotNet team as the recommended approach and we also cannot to do anything with it.

https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-install-script

**Comment by vsafonkin** [comment]
Closed, because there is nothing we can do from our side.

**Comment by jetersen** [comment]
Created https://github.com/actions/setup-dotnet/issues/260 😓

**Comment by ItalyPaleAle** [comment]
We have I/O perf issues as well, and it's not related to .NET.

For example, when using the `actions/cache@v3` Action to restore something from cache. The cache contains a lot of small files that are then unpacked.

Windows:

![image](https://user-images.githubusercontent.com/43508/172702611-d323028f-0a34-4915-b095-f61ddad8308a.png)

It took Windows 428 seconds to restore 1337MB.

Linux:

![image](https://user-images.githubusercontent.com/43508/172702667-a6e62cb0-9018-47a0-ac50-1daeabc4d3f4.png)

Although Linux had to restore only 1074MB, it took only 34 seconds.

As you can see, Windows was actually downloading files from the cache faster than Windows. However, I suspect that what took the longest was extracting them: to us, it seems to be more of a disk I/O issue rather than a network one.

This is one big example, but we see Windows agents being much slower in other things that perform disk I/O, such as pulling/pushing Docker images.

**Comment by ItalyPaleAle** [comment]
@miketimofeev the performance different is very significant however. I don't know what disks are used, but Linux agents processed 1000MB in 32s and WIndows ones in 320s in our tests above, so 10x slower. (I am aware that it's not apples-to-apples as the files in the caches aren't exactly the same, but this difference should be significant regardless)

**Comment by wrexbe** [comment]
This is very frustrating, the nuget downloading was slow on windows, even timing out sometimes, so to make it faster, and more reliable I wanted to use the cache, only to find out that the cache action is also very slow on windows.
https://github.com/space-wizards/space-station-14/runs/7017334343?check_suite_focus=true
The windows server took 2 minutes, and 29 seconds to restore the compressed file, and the Ubuntu server took 16 seconds. Is there a way to work around this?

**Comment by ericmutta** [comment]
Unfortunately, this is still a problem as of July/2023. The `dotnet restore` command on `ubuntu-latest` runs in seconds, but for both `windows-2019` and `windows-latest` it takes a minute or more. Is there a fix for this? The problem actually _costs us money_ because of per-minute billing 😞

**Comment by thomhurst** [comment]
I've got a pipeline that I run against Linux, Mac and Windows to test cross platform-ness. The Linux and Mac ones take a few minutes. The windows one can take 7, 8 or 9 minutes.

**Comment by wrexbe** [comment]
Yeah, windows is still like 11 minutes slower then linux for us.
https://github.com/space-wizards/space-station-14/actions/runs/6272151167/job/17033126765

**Comment by Danielku15** [comment]
I also see similar timings:
![image](https://github.com/actions/runner-images/assets/674916/2c8de131-47f6-4d84-b71f-8d6158246bae)
https://github.com/CoderLine/alphaSkia/actions/runs/6441066466
 
My build times are overall significantly slower in Windows. A `dotnet build` (with restore) of my Nuke build project takes 15secs on `ubuntu-latest` and >1min on `windows-latest`. But also other compilations take significantly more time.

**Comment by jetersen** [comment]
To speed up `dotnet restore` on Windows GitHub Actions runner I'd suggest setting `NUGET_PACKAGES` env to `D:\nuget\packages`
This does should not apply to large runners or self hosted. Only public or private hosted runners.

There are potential for other folders to consider when it comes to NuGet, like http cache folder: https://learn.microsoft.com/en-us/nuget/consume-packages/managing-the-global-packages-and-cache-folders

There are several ways to do this, if your workflow is windows only use env block:

```yaml
env:
  NUGET_PACKAGES: D:\nuget\packages
```

Or under the job:

```yaml
jobs:
  windows:
  	runs-on: windows-latest
    env:
      NUGET_PACKAGES: D:\nuget\packages
```

Or even under a build step with conditional logic:

```yaml
jobs:
  build:
    runs-on: ${{ matrix.os }}
    name: Test
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
      fail-fast: false
    steps:
      - name: Set Windows Environment Variables
        if: startsWith(matrix.os, 'windows')
        shell: pwsh
        run: |
          echo "NUGET_PACKAGES=D:\nuget\packages" >> $ENV:GITHUB_ENV
```

For caching nuget packages you can do something like this:

```yaml
      - name: Cache NuGet packages
        if: matrix.cache
        uses: actions/cache@v4
        with:
          path: ${{ env.NUGET_PACKAGES }}
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: ${{ runner.os }}-nuget-
```

**Comment by TsengSR** [comment]
> Unfortunately, this is still a problem as of July/2023. The `dotnet restore` command on `ubuntu-latest` runs in seconds, but for both `windows-2019` and `windows-latest` it takes a minute or more. Is there a fix for this? The problem actually _costs us money_ because of per-minute billing 😞

Having same issue. I switched form ubuntu-latest where the pipeline did run in 1 min 15 sec in the hope to save the 10 second from dotnet-setup, since ubuntu-latest doesn't have dotnet runtimes installed and I need 1-5 runtimes for multi-target builds. But instead the build times increased from 1m15s to 4m30s, quadrupled and that's WITHOUT the dotnet-setup tasks.

Install GitVersion from 6s to 33s
Restore Nuget Packages from 6 seconds with cache to 45 seconds
dotnet build from 6 to 39 seconds
dotnet tests from 6 to 53 seconds

Its crazy. This needs to be addressed urgently, the windows agents are useless as its now and for some tasks, like nuget packages with symbol server and full pdbs windows agents are a must.

**Comment by PureKrome** [comment]
This is the biggest crime 👮🏻 out of this entire cluster-thread:

![image](https://github.com/user-attachments/assets/5db80378-e948-4471-bb02-aa4a5c056420)
