### ISSUE TITLE
Update macOS-11 image to use Mono with MSBuild version 16.9

### ISSUE THREAD

**Issue by jahmai-ca** [actions/virtual-environments#3583]
**Tool information**
- Tool name: MSBuild
- Tool license: 
- Add or update? Update
- Desired version: 16.9
- Approximate size: 

**Area for Triage**:
Xamarin

**Question, Bug, or Feature?**:
Feature

**Virtual environments affected**
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [x] macOS 11
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Can this tool be installed during the build?**
Yes

- task: Bash@3
  displayName: 'Install mono package'
  inputs:
    targetType: 'inline'
    script: |
      #!/bin/bash
      set -ex
      
      MONO_MACOS_PKG_DOWNLOAD_URL='https://download.mono-project.com/archive/6.12.0/macos-10-universal/MonoFramework-MDK-6.12.0.140.macos10.xamarin.universal.pkg'
      
      # install the desired mono package
      mkdir -p /tmp/mono-install
      cd /tmp/mono-install
      wget -q -O ./mono-installer.pkg "$MONO_MACOS_PKG_DOWNLOAD_URL"
      sudo installer -pkg ./mono-installer.pkg -target /
      
      # output to make sure the update applied correctly
      mono --version
      ls -alh /Library/Frameworks/Mono.framework/Versions/Current

**Tool installation time in runtime**
About 40 seconds

**Are you willing to submit a PR?**
Wouldn't know how sorry!

**Comment by al-cheb** [comment]
Hello, @jahmai-ca 
We have decided to revert mono version and not to pre-install 6.12.0.140  due to some issues - https://github.com/actions/virtual-environments/pull/3543.

**Comment by jahmai-ca** [comment]
Hi @al-cheb fair enough, we can continue installing it during the pipelines. Can I keep this issue open until its resolved?

**Comment by al-cheb** [comment]
@jahmai-ca, Sure, we will keep it open.

**Comment by al-cheb** [comment]
> Hey @al-cheb. Is there any schedule for updating mono to 6.12.0.140?

Currently, no ETA. We are still investigating the issue.

**Comment by al-cheb** [comment]
@jahmai-ca , @mierzynskim , Mono 6.12.0.140 is on board.
