### ISSUE TITLE
Update ChromeDriver from 91.0.4472.19 to 91.0.4472.101

### ISSUE THREAD

**Issue by christophs78** [actions/virtual-environments#3593]
**Description**  
Chromium introduced a significant regression in 91.0.4472.19:
https://bugs.chromium.org/p/chromium/issues/detail?id=1205107
This was fixed with 91.0.4472.101

**Question, Bug, or Feature?**:  
Bug

**Virtual environments affected**  
All

**Image version**
20210607.1 (depending on plattform)

**Expected behavior**  
Please update ChromeDriver to 91.0.4472.101

**Comment by al-cheb** [comment]
Hello, @christophs78 
ChromeDriver will be updated at the next image rollout in a week or two.

**Comment by miketimofeev** [comment]
@christophs78 the new images were deployed.
I'm going to close the issue, please feel free to contact us if you have any concerns.
Thank you!
