### ISSUE TITLE
No logging output when command line asks for user input.

### ISSUE THREAD

**Issue by Danack** [actions/virtual-environments#3594]
I setup a CI step that apparently asks for user input, which obviously isn't going to work.

However this took me a while to figure out, as the job doesn't show _any_ output at all, until it is cancelled, which means that you can't see which step is causing the issue.

I had added quite a few lines of debug to that action, to try to narrow down what was causing the problem. But as none of those lines are shown until the job is cancelled

**Area for Triage**:  
'Scripting and command line' - probably

**Question, Bug, or Feature?**:  
"Bug"

**Virtual environments affected**  
- [X] Ubuntu 20.04

**Image version**
Version: 20210606.1

**Expected behavior**  
Output to be shown, so that users can figure out which run step in the job is causing the issue. 

**Actual behavior**  
No output is shown until the job is cancelled.

![github_action_stalling](https://user-images.githubusercontent.com/1505719/122239239-b15e8c80-ceb8-11eb-9774-fd93a47c5320.PNG)

**Repro steps**  
Git repo - https://github.com/Imagick/imagick/tree/package_testing

Run that is currently showing this issue - https://github.com/Imagick/imagick/runs/2840186682?check_suite_focus=true

I'm pretty sure the output will be shown once I cancel the job, or when it times out.

**Comment by al-cheb** [comment]
Hello, @Danack 
It's not related to images. Please create another issue in the https://github.com/actions/runner/issues repository.
