### ISSUE TITLE
Build VM fails as Microsoft repository file not found (packages-microsoft-prod.deb)

### ISSUE THREAD

**Issue by darrens280** [actions/virtual-environments#3604]
**Description**  
Microsoft repository file (packages-microsoft-prod.deb) not found as per ..\linux\scripts\base\repos.sh

**Area for Triage**:  
https://github.com/actions/virtual-environments/blob/main/images/linux/scripts/base/repos.sh

**Question, Bug, or Feature?**:  
Bug

**Virtual environments affected**  
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [X] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Image version**
Ubuntu20.04/20210614.1

**Expected behavior**  
Packer build of VM to complete

**Actual behavior**  
"Build VM" step fails, as file/url not found: https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb

**Repro steps**  
run pipeline causes Build VM step to fail with following extract from logs:

```
==> azure-arm: Getting the VM's IP address ...
==> azure-arm: Waiting for SSH to become available...
==> azure-arm: Connected to SSH!
==> azure-arm: Provisioning with shell script: C:\Users\AzDevOps\AppData\Local\Temp\packer-shell538432755
==> azure-arm: Provisioning with shell script: C:\a\1\s\images\linux/scripts/base/apt-mock.sh
==> azure-arm: Provisioning with shell script: C:\a\1\s\images\linux/scripts/base/repos.sh
==> azure-arm: --2021-06-17 09:26:13--  https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb
==> azure-arm: Resolving packages.microsoft.com (packages.microsoft.com)... 40.114.136.21
==> azure-arm: Connecting to packages.microsoft.com (packages.microsoft.com)|40.114.136.21|:443... connected.
==> azure-arm: HTTP request sent, awaiting response... 404 Not Found
==> azure-arm: 2021-06-17 09:26:14 ERROR 404: Not Found.
==> azure-arm:
==> azure-arm: Provisioning step had errors: Running the cleanup provisioner, if present...
==> azure-arm: Removing the created Deployment object: 'pkrdphz06bpwy9j'
==> azure-arm: 
==> azure-arm: Cleanup requested, deleting resource group ...
==> azure-arm: Resource group has been deleted.
```

**Comment by al-cheb** [comment]
@darrens280 , Looks like issue isolated to Europe:
https://github.com/dotnet/core/issues/6381
https://docs.microsoft.com/en-us/answers/questions/439491/pyodbc-install-error-in-azure-databricks-file-not.html

I'm going to close the issue as external.
