### ISSUE TITLE
Apt install failing due to inability to download from  https://packages.microsoft.com/ubuntu/20.04/prod 

### ISSUE THREAD

**Issue by Danack** [actions/virtual-environments#3606]
**Description**  

Apt install is failing continually on project that was working yesterday. The error message implies an inability to download a file:

> Err:21 https://packages.microsoft.com/ubuntu/20.04/prod focal Release
>   Could not handshake: Error in the pull function. [IP: 13.66.3.153 443]
> Reading package lists...
> E: The repository 'https://packages.microsoft.com/ubuntu/20.04/prod focal Release' no longer has a Release file.

**Area for Triage**:  
Packages ?

**Question, Bug, or Feature?**:  
"Bug"

**Virtual environments affected**  
- [X] Ubuntu 20.04

**Image version**

Virtual Environment
  Environment: ubuntu-20.04
  Version: 20210614.1

**Expected behavior**  
Apt install works

**Actual behavior**  
Apt install fails

**Repro steps**  

The last few runs on https://github.com/Imagick/imagick have failed:

https://github.com/Imagick/imagick/runs/2848734831?check_suite_focus=true

There have been at least two slightly different error messages:

![github_actions PNG](https://user-images.githubusercontent.com/1505719/122418191-f13d7680-cf81-11eb-928f-d0a77ab47d25.jpg)
![MustConstructAdditionalFileDescriptors](https://user-images.githubusercontent.com/1505719/122418209-f4386700-cf81-11eb-955e-c15838171936.jpg)

The actions were working reliably up until today. And the commits made today don't appear to be related to the issue.

**Comment by al-cheb** [comment]
Hi, @Danack 
Close as external, please follow threads:
https://github.com/dotnet/core/issues/6381
https://docs.microsoft.com/en-us/answers/questions/439491/pyodbc-install-error-in-azure-databricks-file-not.html

**Comment by Danack** [comment]
Thankyou.
