### ISSUE TITLE
Update dacfx to 18.7.1

### ISSUE THREAD

**Issue by dzsquared** [actions/virtual-environments#3607]
**Tool information**
- Tool name: dacfx
- Tool license: 
- Add or update? update
- Desired version: latest, 18.7.1
- Approximate size: 
- If this is an add request:
  - Brief description of tool: 
  - URL for tool's homepage: https://docs.microsoft.com/en-us/sql/tools/sqlpackage/sqlpackage
  - Provide a basic test case to validate the tool's functionality: 

**Area for Triage**: Databases

**Question, Bug, or Feature?**: Feature

**Virtual environments affected**
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [x] Windows Server 2016 R2
- [x] Windows Server 2019

**Can this tool be installed during the build?**

**Tool installation time in runtime**

**Are you willing to submit a PR?**

PR incoming

**Comment by miketimofeev** [comment]
@dzsquared the new images were deployed.
I'm going to close the issue, please feel free to contact us if you have any concerns.
Thank you!
