### ISSUE TITLE
Add Visual Studio 2022 Preview

### ISSUE THREAD

**Issue by jwillemsen** [actions/virtual-environments#3609]
**Tool information**
- Tool name: Visual Studio 2022
- Tool license: Commercial
- Add or update? Add
- Desired version: Preview
- Approximate size: 
- If this is an add request:
  - Brief description of tool: Visual Studio 2022 preview could help to assess this new compiler
  - URL for tool's homepage: https://visualstudio.microsoft.com/vs/preview/vs2022/
  - Provide a basic test case to validate the tool's functionality: 

**Area for Triage**:
C/C++

**Question, Bug, or Feature?**:
Feature

**Virtual environments affected**
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016 R2
- [X] Windows Server 2019

**Can this tool be installed during the build?**

**Tool installation time in runtime**

**Are you willing to submit a PR?**

**Comment by maxim-lobanov** [comment]
Hello @jwillemsen , we have a plan to add Visual Studio 2022 to the Windows Server 2022.
Installing multiple Visual Studio instances side by side is pretty painful so we would like to keep one VS on one Windows platform.
ETA for adding Windows Server 2022 is 2-3 months. We are working on plan for it now.

**Comment by jwillemsen** [comment]
Ok, that would be great, would make it much easier to test this new compiler when it is on github actions

**Comment by maxim-lobanov** [comment]
Hello everyone!

Windows Server 2022 image with Visual Studio 2022 on board is available for Azure DevOps and GitHub users! 🚀 
Please find more details in https://github.com/actions/virtual-environments/issues/3949

#### GitHub Actions
```yaml
jobs:
  jobName:
    runs-on: windows-2022
```

#### Azure DevOps
```yaml
jobs:
- job: jobName
  pool:
    vmImage: windows-2022
```

**Comment by Aurumaker72** [comment]
The windows-2022 image doesn't include VS 2022 preview. The enterprise version is preinstalled, which means this issue remains unresolved.

**Comment by ghost1372** [comment]
@maxim-lobanov vs2022 preview is not available
