### ISSUE TITLE
 GitHub Actions has encountered an internal error when running your job.

### ISSUE THREAD

**Issue by vladimirarevshatyan** [actions/virtual-environments#3610]
Currently, I am facing an issue with one of my projects and no jobs could run.

No logs , nothing.

It just won't go past the stage "Starting workflow..."

It will eventually say that the job was cancelled.

I am suffering from this issue for around an hour already.

Surely GitHub status webpage gives false and misleading information as always saying everything operates correctly.

**Comment by striezel** [comment]
> Surely GitHub status webpage gives false and misleading information as always saying everything operates correctly.

Looks like the GitHub status updates are lagging a bit behind. However, it seems like the issue has been fixed already. (Also see #3611.)

**Comment by Darleev** [comment]
Hello @vladimirarevshatyan,
The reply above is correct, and there was the degraded performance on GitHub actions side, which leads to the problem.
Sometimes it takes additional time to change status In [github status page](https://www.githubstatus.com/).
In case of any questions feel free to contact us. I'm closing the case.
