### ISSUE TITLE
GitHub Actions do not start / run.

### ISSUE THREAD

**Issue by striezel** [actions/virtual-environments#3611]
**Description**  

GitHub Actions has encountered an internal error when running your job.

https://github.com/striezel/botvinnik/actions/runs/950386057
https://github.com/striezel/botvinnik/actions/runs/950386058
and
https://github.com/striezel/botvinnik/actions/runs/950443491
https://github.com/striezel/botvinnik/actions/runs/950443498

**Area for Triage**:  
Deployment/Release

**Question, Bug, or Feature?**:  
Bug

**Virtual environments affected**  
- [ ] Ubuntu 16.04
- [x] Ubuntu 18.04
- [x] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Image version**
unknown, probably 2.278.0 or later

**Expected behavior**  
No error, GitHub Actions should start / run.

**Actual behavior**  
GitHub Actions did not start and display the message "GitHub Actions has encountered an internal error when running your job".

**Repro steps**  
A description with steps to reproduce the issue. If your have a public example or repo to share,
please provide the link.

1. Push commit to repository.
2. Github Actions hangs in queue and finally errors with message above.

**Comment by calvin-sentry** [comment]
Yes I'm experiencing this same issue.

**Comment by vladimirarevshatyan** [comment]
Same on my end as well.

Seems github issue

**Comment by striezel** [comment]
> Seems github issue

Maybe, but https://www.githubstatus.com/ says "All systems operational" and GitHub Actions are "normal", i. e. there is no service degradation so far.

**Comment by imilchev** [comment]
Same here

**Comment by njbmartin** [comment]
Just spent the last 30 mins trying to work out why my builds are failing as the messaging is confusing:

"This check was cancelled" - Why, what did I do wrong?
"GitHub Actions has encountered an internal error when running your job" - I'm assuming this isn't me, but https://www.githubstatus.com/ isn't showing an issue.

**Comment by aitormagan** [comment]
GitHub Status is already showing a degraded performance for GitHub Actions

**Comment by striezel** [comment]
@calvin-sentry @vladimirarevshatyan @imilchev @njbmartin:
For all those of you who are experiencing similar issues, you might want to link to the corresponding workflow runs. Maybe that helps the GitHub people with the investigation of the issue.

**Comment by g138** [comment]
![image](https://user-images.githubusercontent.com/36992519/122594840-7cd90500-d05f-11eb-8ef8-5a6f5c81eb4c.png)

**Comment by striezel** [comment]
> GitHub Status is already showing a degraded performance for GitHub Actions

Yes, it did. However, that was not the case when I opened this issue. Maybe it needs a bit of time to update the status page. Although one might think that there is an automatism in place that detects such problems.

Anyway ... In the meantime, the issues seems to be fixed, GitHub Actions seem to work normal again. When I re-run some of the jobs that showed the internal error, they are runing again. Therefore I am closing this issue.
