### ISSUE TITLE
GitHub Actions has encountered an internal error when running your job.

### ISSUE THREAD

**Issue by g138** [actions/virtual-environments#3612]
We are receiving this message “GitHub Actions has encountered an internal error when running your job.” across all of our CI builds across every repository in our organisation.

Github Status page is currently reporting no issues. Can someone from Github please look into this? This has started within the last hour.

![image](https://user-images.githubusercontent.com/36992519/122591020-43ea6180-d05a-11eb-9685-a34219ee1652.png)

**Comment by striezel** [comment]
See https://github.com/actions/virtual-environments/issues/3611, seems to be the same issue.

**Comment by g138** [comment]
Yeah right, so closing the issue from here
