### ISSUE TITLE
GitHub Actions has encountered an internal error when running your job

### ISSUE THREAD

**Issue by filipaGitHub** [actions/virtual-environments#3613]
Hi, I am getting this error when I try to run GitHub actions
**GitHub Actions has encountered an internal error when running your job.**

![image](https://user-images.githubusercontent.com/78536080/122596925-83b54700-d062-11eb-8cc2-ea935e15da31.png)
![image](https://user-images.githubusercontent.com/78536080/122597121-d68efe80-d062-11eb-87f5-9186e2230399.png)

**Comment by rnayabed** [comment]
Wow today is the first time I started using github actions, and after 1-2 successful runs it started giving me these errors. I thought I am doing something wrong, after 1-2 hrs of head scratching I see this. 

also checked https://www.githubstatus.com/

**Comment by striezel** [comment]
See https://github.com/actions/virtual-environments/issues/3611, this seems to be the same kind of issue. However, it looks like the issue has been fixed already.

**Comment by Darleev** [comment]
Hello @filipaGitHub,
There was Github actions outage, currently, everything works fine.
In case of any questions, feel free to contact us.
