### ISSUE TITLE
Update/Add [net472]

### ISSUE THREAD

**Issue by zfengms** [actions/virtual-environments#363]
**Tool information**
- Tool name: .net framework 4.7.2
- Add or update? Add
- Desired version: 4.7.2
- Approximate size: 
- If this is an add request:
  - Brief description of tool: Our application needs .net framework 4.7.2 but could not find it on hosted agent
  - URL for tool's homepage: https://dotnet.microsoft.com/download/dotnet-framework/thank-you/net472-developer-pack-offline-installer

**Area for Triage**:
.NET Framework

**Question, Bug, or Feature?**:
Feature

**Virtual environments affected**
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [x] Windows Server 2016 R2
- [x] Windows Server 2019

**Can this tool be installed during the build?**
Do not know

**Are you willing to submit a PR?**
No

**Comment by vmapetr** [comment]
@zfengms .net framework 4.7.2 developer tools were added to Windows images. They will be available after next image rollout (1-2 weeks approximately)

**Comment by miketimofeev** [comment]
@zfengms the image has been rolled out. Could you check everything is fine now?

**Comment by maxim-lobanov** [comment]
I am closing the issue since image was deployed. Feel free to reopen if you see any issues
