### ISSUE TITLE
Xcode 13 beta is installed as "stable"

### ISSUE THREAD

**Issue by mattleibow** [actions/virtual-environments#3632]
**Description**  
Typically, the path to the Xcode installs are /Application/Xcode_<version>_<beta>.app.

I see this PR got merged: https://github.com/actions/virtual-environments/pull/3540

Just wondering if this maybe is should really be installed to Xcode_13.0_beta.app?

**Area for Triage**:  
Xcode

**Question, Bug, or Feature?**:  
Bug

**Virtual environments affected**  
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [x] macOS 11
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Image version**
20210614.1

**Expected behavior**  
Xcode to be installed as a beta

**Actual behavior**  
Xcode is installed as stable.

**Repro steps**  
N/A

**Comment by maxim-lobanov** [comment]
Hello @mattleibow , we don't have any special naming for beta and GM versions so the current naming is intended.

Having the separate path for beta versions causes problems when stable is released and `Xcode_beta.app` is renamed to `Xcode.app`. All users who already use hardcoded path `Xcode_beta.app` will be broken by this renaming so we have to keep `Xcode_beta.app` as a symlink to `Xcode.app` to not break users and it causes even more confusion.

Please follow [image documentation](https://github.com/actions/virtual-environments/blob/main/images/macos/macos-11-Readme.md#xcode) to find out paths for all installed Xcode versions. Or you can use [community action](https://github.com/marketplace/actions/setup-xcode-version) to switch Xcode as an alternative solution to not take care about paths.
