### ISSUE TITLE
[all OS versions] Android SDK tools will be changed to Command line tools on July, 12

### ISSUE THREAD

**Issue by miketimofeev** [actions/virtual-environments#3638]
**Breaking changes**
All the Android tools will be installed using `sdkmanager` from the Command line tools package rather than `sdkmanager` from SDK tools.

**Target date**
Image deployment will start July, 12 and will take 3-4 days.

**The motivation for the changes**
SDK Tools package is deprecated and no longer receiving updates, google recommends using command-line tools instead.
https://developer.android.com/studio/releases/sdk-tools
![image](https://user-images.githubusercontent.com/48208649/122936829-23801700-d37a-11eb-84bf-c66074c9d918.png)

**Possible impact**
There should be no visible impact, but it is better to switch your pipeline to use command line tools' sdkmanager as well.

**Virtual environments affected**
- [ ] Ubuntu 16.04
- [x] Ubuntu 18.04
- [x] Ubuntu 20.04
- [ ] macOS 10.13
- [x] macOS 10.14
- [x] macOS 10.15
- [x] macOS 11
- [x] Windows Server 2016 R2
- [x] Windows Server 2019

**Mitigation ways**
Change the path to the sdkmanager in your code:
- Windows
`$env:ANDROID_SDK_ROOT/tools/bin/sdkmanager.bat` -> `$env:ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager.bat` 
- Linux & macOS
`$ANDROID_SDK_ROOT/tools/bin/sdkmanager` -> `$ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager
`

**Comment by CaoMinhThien** [comment]
Ok

**Comment by miketimofeev** [comment]
All the images were deployed
