### ISSUE TITLE
Update/Add graphviz

### ISSUE THREAD

**Issue by zbeekman** [actions/virtual-environments#364]
**Tool information**
- Tool name: graphviz
- Add or update? add
- Desired version: latest (no need for a specific version, afaict)
- Approximate size: ~ 256M on macOS, not including dependencies
- If this is an add request:
  - Brief description of tool: Graph visualization software from AT&T and Bell Labs used by CMake and other tools to depict dependencies
  - URL for tool's homepage: https://www.graphviz.org/

**Area for Triage**:
Packages

**Virtual environments affected**

I know for sure it's not present on macOS. I don't believe it's present on Ubuntu either. I have no idea about Windoze

- [x] macOS 10.15 (Definitely)
- [x] Ubuntu 16.04 LTS (Pretty sure)
- [x] Ubuntu 18.04 LTS (Pretty sure)
- [x] Windows Server 2016 R2 (Wild guess)
- [x] Windows Server 2019 (Wild guess)

**Can this tool be installed during the build?**
Yes: `brew install graphviz` or `apt-get install graphviz`
On macOS this takes [about 45 seconds to over a minute](https://github.com/zbeekman/brew-GHA-profiling/blob/gh-pages/graphviz.csv) not including other overheads.

**Are you willing to submit a PR?**
Sure but I'll need a little bit of guidance, and there's no way to submit a PR for macOS where I'm most comfortable.

**Comment by thejoebourneidentity** [comment]
Hey @zbeekman, thanks so much for your suggestion 🙏. Considering how easy it is to install during a build, we have some maintenance concerns especially since it won't be something used by the majority of Actions customers. For those reasons, it's not something we will add to the image at this time.

**Comment by zbeekman** [comment]
Thanks for considering it! Cheers!
