### ISSUE TITLE
Add libcurl4-openssl-dev

### ISSUE THREAD

**Issue by rnett** [actions/virtual-environments#3640]
**Tool information**
- Tool name: libcurl4-openssl-dev
- Tool license: [curl](https://curl.se/docs/copyright.html), similar to MIT/X
- Add or update? Add
- Desired version: matching `libcurl`
- Approximate size: 
- If this is an add request:
  - Brief description of tool: Development headers for `libcurl`.
  - URL for tool's homepage: https://curl.se/libcurl/
  - Provide a basic test case to validate the tool's functionality: check for `[installed]` in `sudo apt -qq list libcurl4-openssl-dev` or try linking against `curl`.

**Area for Triage**:
Scripting and command line, C/C++

**Question, Bug, or Feature?**:
Feature

**Virtual environments affected**
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [x] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Can this tool be installed during the build?**
`sudo apt-get install libcurl4-openssl-dev -y`

**Tool installation time in runtime**
~5s

**Are you willing to submit a PR?**
Yes, assuming it's as simple as adding it [here](https://github.com/actions/virtual-environments/blob/main/images/linux/toolsets/toolset-2004.json#L119).

**Why?**
This is easy to install, but is preinstalled on mac and windows.  The primary reason to do this is for parity.  Anything that links against `curl` currently requires a separate step to install this, only on linux.

**Comment by AlenaSviridenko** [comment]
Hi @rnett,
we are currently trying to avoid adding more packages to our images as they bring conflicts sometimes, increase `apt update` time, and we are trying to reconsider images tool installation strategy. 
Given that, we'd rather not to add this package to our runners, please, install it in runtime.

I am closing this issue, please, feel free to reach out to us in case of any questions.
Thanks.

**Comment by ericuni** [comment]
From sometime, libcurl4-openssl-dev couldn't be installed on unbuntu-latest.
The error message is as follows:
```
Run sudo apt-get install -y libcurl4-openssl-dev libgoogle-perftools-dev
xxx
[25](https://github.com/ericuni/code/runs/6244247067?check_suite_focus=true#step:3:25)
E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/main/c/curl/libcurl4-openssl-dev_7.68.0-1ubuntu2.7_amd64.deb  404  Not Found [IP: 40.81.13.82 80]
[26](https://github.com/ericuni/code/runs/6244247067?check_suite_focus=true#step:3:26)
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
[27](https://github.com/ericuni/code/runs/6244247067?check_suite_focus=true#step:3:27)
Error: Process completed with exit code 100.
```

**Comment by ericuni** [comment]
run `sudo apt-get update` before the install could succeed.

**Comment by TonGarcia** [comment]
There is any kind of libcurl4-openssl-dev for Mac M1?

**Comment by Sivakajan-tech** [comment]
@TonGarcia Did you find anything?

> There is any kind of libcurl4-openssl-dev for Mac M1?

cc: @rnett  @AlenaSviridenko
