### ISSUE TITLE
Windows image: Add Windows 10 SDK 10.0.20348.0

### ISSUE THREAD

**Issue by DSMitten** [actions/virtual-environments#3641]
**Tool information**
- Tool name: Windows 10 SDK 10.0.20348.0
- Add or update? Add
- Desired version: 10.0.20348.0
- Approximate size: 
- If this is an add request:
  - Brief description of tool: The latest published version of the Windows 10 SDK
  - URL for tool's homepage: https://developer.microsoft.com/en-us/windows/downloads/windows-10-sdk/

**Area for Triage**:

**Question, Bug, or Feature?**:

**Virtual environments affected**
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016 R2
- [X] Windows Server 2019

**Can this tool be installed during the build?**
Yes, just run Win10 SDK installer, but it takes a long time.

**Tool installation time in runtime**
5-15 minutes.

**Are you willing to submit a PR?**
no

**Comment by AlenaSviridenko** [comment]
Hi @DSMitten,
we are installing Windows 10 SDK here to install WDK 
https://github.com/actions/virtual-environments/blob/405a368b22cbac48f31ce7b35f415369d31a27b1/images/win/scripts/Installers/Install-WDK.ps1#L9

Do I get it right that it doesn't fit your needs, and you are asking for `Windows 10 SDK version 2104 and Server development`?

**Comment by DSMitten** [comment]
Yes, we're asking for Windows 10 SDK version 2014 and Server development, link https://go.microsoft.com/fwlink/?linkid=2164145

When we switched from C++17 to C++20, we had compile errors in Windows header files, and we had to upgrade to the most recent release in order to build successfully. We are currently running the SDK installer now, but installing the SDK takes as long as building our application, so it would be very helpful if it was part of the VM image.

**Comment by urkle** [comment]
This would be nice as I'm dealing with all sorts of issues with 10.0.17763 SDK (as there are bugs in many headers that cause compilation errors when using /W4 or /Wall as one project I'm building does).. and everything works fine w/ 10.0.14393.0 on the windows-2016 image.

**Comment by AlenaSviridenko** [comment]
Hi,
We are concerned about installing this new big tools to our Windows images due to its size, possible maintenance effort and tool popularity, so I would suggest keep installing it in runtime. 
I am closing this issue, please, feel free to contact us in case of any questions.

**Comment by jpark37** [comment]
I would also like 20348 because there's a new WinRT class that I want to use, GraphicsCaptureAccess:
https://docs.microsoft.com/en-us/uwp/api/windows.graphics.capture.graphicscaptureaccess

I've PR'd a similar upgrade in the past to bump the SDK to 19041, #935. I have a commit that will attempt to do the same, https://github.com/jpark37/virtual-environments/commit/f1fa5a44a7edcb227676ab21f133a1347ee6d31c, but I don't want to make a PR until I can test, and image generation seems to be busted until the selenium download location gets updated, #3940.
