### ISSUE TITLE
Add yq (the command-line YAML processor)

### ISSUE THREAD

**Issue by damlys** [actions/virtual-environments#365]
**Tool information**

- Tool name: `yq`
- Add or update? Add
- Desired version: Latest
- Approximate size: about 10 MB
- If this is an add request:
  - Brief description of tool: `yq` is a command-line YAML processor  (same as `jq` for JSON files)
  - URL for tool's homepage: https://github.com/mikefarah/yq

**Question, Bug, or Feature?**:

Feature request

**Virtual environments affected**

- [ ] macOS 10.15
- [x] Ubuntu 16.04 LTS
- [x] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Can this tool be installed during the build?**

Yes. It'll took about a minute to install it. It can be installed with `snap` and `apt` managers on Ubuntu and with `brew` on macOS.

See installation docs here: https://mikefarah.gitbook.io/yq/

**Comment by thejoebourneidentity** [comment]
Thanks for your suggestion 🙏. Considering how popular this tool is, and how easy it is to install during your run, it's not something we will add to the image at this time.

**Comment by damlys** [comment]
I think it is as popular as `jq` which is already installed on the Ubuntu machines. Thanks anyway
