### ISSUE TITLE
Android UI Tests fail on GitHub actions but pass locally

### ISSUE THREAD

**Issue by TheReprator** [actions/virtual-environments#3663]
Description
My All UI android test fail on Github action but when I run the tests locally, all tests pass.

Expected behavior
All tests should pass

Actual behavior
All UI tests are failing

Repro Details

Workflow Result:
https://github.com/TheReprator/Wipro/actions/runs/979383000

Repo: https://github.com/TheReprator/Wipro
Branch: codeCoverage
workflow: non_master_push.yml

Looking forward for a solution.

Regards,
Vikram Singh

**Comment by dibir-magomedsaygitov** [comment]
Hello @TheReprator. Thank you for your report. We will take a look.

**Comment by Darleev** [comment]
Hello @TheReprator,
I tried to find a simple way to reproduce the issue, but with no luck. Maybe you already have some repo where it is possible to easily reproduce the issue or you can write exact steps to start your tests locally.
We're looking forward to your reply.

**Comment by Darleev** [comment]
Hello @TheReprator,
I'm going to close the issue until further clarifications from your side.
In case of any questions, feel free to contact us.
