### ISSUE TITLE
Add Firebase CLI

### ISSUE THREAD

**Issue by alexleonov-tactiq** [actions/virtual-environments#3666]
**Tool information**
- Tool name: Firebase CLI (firebase-tools)
- Tool license: MIT
- Add or update? Add
- Desired version: whatever is latest in NPM (https://www.npmjs.com/package/firebase-tools)
- Approximate size: 1.79MB
- If this is an add request:
  - Brief description of tool: The Firebase Command Line Interface (CLI) Tools can be used to test, manage, and deploy Firebase projects from the command line.
  - URL for tool's homepage: https://github.com/firebase/firebase-tools
  - Provide a basic test case to validate the tool's functionality: `firebase help`

**Virtual environments affected**
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [x] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Can this tool be installed during the build?**
Yes

**Tool installation time in runtime**
~40sec

**Are you willing to submit a PR?**
Yes

**Comment by AlenaSviridenko** [comment]
Hi @alexleonov-tactiq, there are plenty of [actions](https://github.com/marketplace?query=firebase&type=actions) to setup and use Firebase CLI, that one has a lot of stars [github-action-for-firebase](https://github.com/marketplace/actions/github-action-for-firebase), will it fit your needs?
Using actions is recommended way to work with the images https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#using-preinstalled-software

**Comment by alexleonov-tactiq** [comment]
@AlenaSviridenko I'll check it close this week, thanks.

Still, I feel uncomfortable with using an action that only wraps a call to an executable to a security-critical piece of infrastructure without providing any additional value/logic. Firebase CLI is there along with google-cloud-sdk, azure cli and others. The action above just becomes another risk in the supply chain, and adds to the workload - it's a set of scripts plus a docker image that will get access to our production environment.

**Comment by AlenaSviridenko** [comment]
I am closing this issue, and suggest using action for Firebase CLI.
Please, let me know if you have any concerns. Thanks.

**Comment by mklarsen** [comment]
Hi There,
basically I disagree in the result/solution given: Use GitHub-Actions. 
if so, why even make these platforms like Ubuntu, Mac, etc.?

My take on these platforms (Like Ubuntu, Mac et.c) at there were super swiss army knives and therefor had many tools preinstalled.  

In my case I have a flutter barley. Who will build an android, ios and a Docker / web images. all in all it takes 20-30 just to install tools. That is, before anything is built at all.   So if I have to build / test my app 10-20 times a day, then the use of github actions ends up being very expensive, probably WAY too expensive.

Please reopen this case, or my issue.

And btw. If I can participate, help make these platforms better then I would like to participate, just reach out. :-)

BR,
Martin
