### ISSUE TITLE
cmake g++ builds fail using GitHub actions, but run successfully on local machines and other CI hosts

### ISSUE THREAD

**Issue by rogerfraser** [actions/virtual-environments#3669]
### Description

For [/icsm/DynAdjust](https://github.com/icsm-au/DynAdjust), cmake workflows using g++ fail unexpectedly, yet the same build script and steps run successfully on other (local and remote) Linux distros and other CI environments (docker, travis, etc.).

### Virtual environments affected

- [ ] Ubuntu 16.04
- [X] Ubuntu 18.04
- [X] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019

### Image version and build link

Version: 20210621.1

Build link: 
https://github.com/icsm-au/DynAdjust/runs/2941874821?check_suite_focus=true

### Expected behavior

All dependencies installed by apt-get
All dependencies are found
All binaries are successfully built.

See the following for working examples of the same script:
https://github.com/icsm-au/DynAdjust/runs/2941874804?check_suite_focus=true#step:5:1881
https://travis-ci.com/github/icsm-au/DynAdjust/builds/231228435#L826

### Actual behavior

**OK** All dependencies installed by apt-get
**OK** All dependencies are found

**FAIL** Upon invoking `make -j $(nproc) || exit 1` (see [here](https://github.com/icsm-au/DynAdjust/blob/master/resources/make_dynadjust_gcc.sh#L285)), the build terminates with the following errors:

`cc1plus: error: too many filenames given.  Type cc1plus --help for usage`
`cc1plus: error: too many filenames given.  Type cc1plus --help for usage`
`cc1plus: fatal error: CMakeFiles/dnareftran.dir/__/__/include/io/dnaiobase.cpp.d: No such file or directory`

Sample error:

![image](https://user-images.githubusercontent.com/18198507/123796533-8fd5ba00-d928-11eb-8d0d-759177c77cad.png)

### Repro steps

Any push or pull request.

The cmake action uses [cmake.yml](https://github.com/icsm-au/DynAdjust/blob/master/.github/workflows/cmake.yml).

**Comment by dibir-magomedsaygitov** [comment]
Hello @rogerfraser. Thank you for your report. We will take a look.

**Comment by dsame** [comment]
@rogerfraser 
i was able to found the reason of the build to fail: it is the set of build options `-MD -MT dynadjust/dnaimport/CMakeFiles/dnaimport.dir/__/__/include/io/dnaioaml.cpp.o -MF CMakeFiles/dnaimport.dir/__/__/include/io/dnaioaml.cpp.o.d` add to the gcc call

Currently i have no idea where they come from and continue the investigating (most probably we have some CMake deps in the path) but may be you have some knowing about details of your build system which may cause the options?

**Comment by dsame** [comment]
@rogerfraser
The build has a problem with most recent cmake 3.20.5

Downgrading the cmake to 3.16 solves it

```
   - name: Remove cmake 3.20.5
      run: |
        CMAKE=$(which cmake)
        sudo rm $CMAKE
    
    - name: install cmake 3.16
      run: |
        sudo apt-get install cmake
        hash -r
```   

The success build: https://github.com/dsame/DynAdjust/runs/2988373961?check_suite_focus=true

**Comment by rogerfraser** [comment]
Thanks very much @dsame and @dibir-magomedsaygitov for looking into this so promptly and solving the issue. Well done on finding the cause, which to my surprise was cmake.  As you've shown, cmake action builds fine now.  Many thanks.

**Comment by dsame** [comment]
@rogerfraser i am closing the issue. Feel free to create a new one or re-open this issue in case of a problem
