### ISSUE TITLE
Add aria2 on windows

### ISSUE THREAD

**Issue by jmarrec** [actions/virtual-environments#3670]
### Tool name

aria2

### Tool license

GPL 2

### Add or update?

- [X] Add
- [ ] Update

### Desired version

1.35.0

### Approximate size

2MB

### Brief description of tool

aria2 is already available on linux and on macOS

aria2 - The ultra fast download utility

aria2 is a utility for downloading files. The supported protocols are HTTP(S), FTP, SFTP, BitTorrent, and Metalink. aria2 can download a file from multiple sources/protocols and tries to utilize your maximum download bandwidth. It supports downloading a file from HTTP(S)/FTP/SFTP and BitTorrent at the same time, while the data downloaded from HTTP(S)/FTP/SFTP is uploaded to the BitTorrent swarm. Using Metalink's chunk checksums, aria2 automatically validates chunks of data while downloading a file like BitTorrent.

### URL for tool's homepage

https://github.com/aria2/aria2

### Provide a basic test case to validate the tool's functionality.

```bash
aria2c --version
```

### Virtual environments affected

- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [X] Windows Server 2016
- [X] Windows Server 2019

### Can this tool be installed during the build?

```bash
choco install
```

### Tool installation time in runtime

1s

### Are you willing to submit a PR?

Yes

**Comment by AlenaSviridenko** [comment]
Closing this one https://github.com/actions/virtual-environments/pull/3671#issuecomment-885529702

**Comment by jmarrec** [comment]
Can you reopen this issue please? I was just out on vacation. The PR only needed to have main merged in...

**Comment by jmarrec** [comment]
Thanks @AlenaSviridenko

**Comment by AlenaSviridenko** [comment]
Re-opened issue, thanks for confirming the status of the tool 🙂
