### ISSUE TITLE
Update Azure PowerShell Module 

### ISSUE THREAD

**Issue by lujinlou** [actions/virtual-environments#3674]
### Tool name

Azure PowerShell Module

### Tool license

Azure PowerShell

### Add or update?

- [ ] Add
- [X] Update

### Desired version

6.1.0

### Brief description of tool

We are using Microsoft-Hosted Agent in Azure DevOps .When we use Azure PowerShell to run the Set-AzWebApp command to set up the WebApp Application Setting , the pipeline runs successfully, but the application setting of the WebApp is not updated.

This is the known issue in Azure PowerShell 5.9. Here is the related link: https://github.com/Azure/azure-powershell/issues/15078 This issue has been fixed in the Azure PowerShell Version 6.1.0(latest).

Based on the Microsoft Hosted Agent Configuration, the latest installed version in Microsoft-Hosted Agent is 5.9.0.

When we select the Latest installed version in Azure PowerShell task, it will use the 5.9.0 version.

We request to update the Azure PowerShell module of the Microsoft-hosted agent  to latest so that when we choose the latest installed version, the Azure PowerShell task will use version 6.x to avoid this issue.

### URL for tool's homepage

https://docs.microsoft.com/en-us/powershell/azure/install-az-ps?view=azps-6.1.0

### Virtual environments affected

- [X] Ubuntu 16.04
- [X] Ubuntu 18.04
- [X] Ubuntu 20.04
- [X] macOS 10.15
- [X] macOS 11
- [X] Windows Server 2016
- [X] Windows Server 2019

### Can this tool be installed during the build?

```bash
We could define the Azure PowerShell Version to 6.1.0 in Azure DevOps Azure PowerShell task.
```

**Comment by dibir-magomedsaygitov** [comment]
Hello @lujinlou. Thank you for your report. We prepared PR's to upgrade Azure PowerShell module to 6.1.0.

**Comment by lujinlou** [comment]
@dibir-magomedsaygitov  Could you please share the ETA of this update?

**Comment by dibir-magomedsaygitov** [comment]
Hello @lujinlou. Approximately 2 week's (next week is holidays week). I'll post an update message.

**Comment by dibir-magomedsaygitov** [comment]
Hello @lujinlou. Azure PowerShell Version to 6.1.0 has been added to all VM's. I will post an update message as soon as they are available to use.

**Comment by dibir-magomedsaygitov** [comment]
Hello @lujinlou. Azure PowerShell Version to 6.1.0 is available across all the VM's. I'm going to close this issue. In case of any questions feel free to contact us. Thank you.
