### ISSUE TITLE
Update helm

### ISSUE THREAD

**Issue by josefschabasser** [actions/virtual-environments#3680]
### Tool name

helm

### Tool license

Apache 2.0

### Add or update?

- [ ] Add
- [X] Update

### Desired version

3.6.2

### Brief description of tool

There is a bug in helm v3.6.1 which breaks compatibility with azure-cli (`az acr helm repo add`) and forces users to use `--pass-credentials` when adding an Azure Container Registry. Helm v3.6.2 fixes this issue.

### Virtual environments affected

- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019

**Comment by dibir-magomedsaygitov** [comment]
Hello @josefschabasser. Thank you for your report. We update images on weekly basis. Updated Help should be available on all images in about 2 weeks (next week is holidays week). I'll post an update message. Thank you.

**Comment by dibir-magomedsaygitov** [comment]
Hello @josefschabasser. Helm was successfully updated to 3.6.2 version across all the images. I'm going to close this issue. In case of any questions feel free to contact us.
