### ISSUE TITLE
Update Swift to latest stable release: 5.4.2

### ISSUE THREAD

**Issue by buttaface** [actions/virtual-environments#3683]
### Tool name

Swift

### Tool license

Apache 2

### Add or update?

- [ ] Add
- [X] Update

### Desired version

5.4.2

### Virtual environments affected

- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [X] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019

**Comment by buttaface** [comment]
[It was released earlier this week](https://swift.org/download/). I think someone at github just needs to run the installer script again, don't know if there is any way for outsiders like me to trigger that.

**Comment by dibir-magomedsaygitov** [comment]
Hello @buttaface. We install latest available version of Swift on our images. New version of Swift should be available with the next image rollout (~ in 2 week's). I'll post an update message.

**Comment by dibir-magomedsaygitov** [comment]
Hello @buttaface. Swift was successfully updated to 5.4.2 version on Ubuntu Images. I'm going to close this issue. In case of any questions feel free to contact us. Thank you.
