### ISSUE TITLE
Add Kotlin

### ISSUE THREAD

**Issue by LouisCAD** [actions/virtual-environments#3687]
### Tool name

Kotlin

### Tool license

Apache 2.0

### Add or update?

- [X] Add
- [ ] Update

### Desired version

1.5.20

### Brief description of tool

Having Kotlin installed would enable developers to use Kotlin scripts in place of bash scripts.

Startup time of the scripts would be a bit longer, but on the other hand, much more can be done, and much more safely as it's much easier to run logic and abstract things away with Kotlin compared to bash.

Also, the script syntax would be checked before they run by the compiler, unlike bash/shell that will crash at runtime, mid-flight.

### URL for tool's homepage

https://kotlinlang.org/docs/command-line.html

### Provide a basic test case to validate the tool's functionality.

```bash
Run the following script sitting inside a file with executable permission:

#!/usr/bin/env kotlin

println("Hello Kotlin!")
```

### Virtual environments affected

- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [X] Ubuntu 20.04
- [ ] macOS 10.15
- [X] macOS 11
- [ ] Windows Server 2016
- [X] Windows Server 2019

### Can this tool be installed during the build?

```bash
For Ubuntu, yes as a snap package with the following shell command:

sudo snap install --classic kotlin
```

### Tool installation time in runtime

~10s

### Are you willing to submit a PR?

Not at the moment because I'm busy with other OSS projects.

**Comment by LeonidLapshin** [comment]
Hey, @LouisCAD , we'll consider adding Kotlin to images and return back with the answer soon :)

**Comment by LeonidLapshin** [comment]
Hi, @LouisCAD 
We'll make a PR and add this tool to image soon, all details will be in this issue :)

**Comment by LouisCAD** [comment]
@AlenaSviridenko In don't think the "Area: Android" tag is accurate.
Kotlin is to Android what C++ is to Windows: just one of the possible targets.

The "Area: Scripting and command line" and "Area: Common Tools" tags would fit this request better IMO.
The "Area: Java" would also work since many folks run Kotlin in the JVM, and that's the only option for Kotlin scripts for now.

**Comment by AlenaSviridenko** [comment]
@LouisCAD, thank you for the clarification, updated tags.

**Comment by mikhailshaganov** [comment]
Hey, PRs for all OS with Kotlin are merged. Mac and Ubuntu have already got an update with Kotlin. Win will get with the next deploy.

**Comment by LouisCAD** [comment]
Hello, is it still awaiting deployment completion, or is the rollout done?

**Comment by mikhailshaganov** [comment]
hello, the rollout is done, all changes are applied.
