### ISSUE TITLE
Macos 11 not starting

### ISSUE THREAD

**Issue by julianhille** [actions/virtual-environments#3690]
### Description

Having a matrix with macos-11 or macos-11.0  just stops with "check failed" .

### Virtual environments affected

- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [X] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019

### Image version and build link

https://github.com/julianhille/MuhammaraJS/runs/2997140303?check_suite_focus=true

### Expected behavior

Environment starts

### Actual behavior

Just check failed

### Repro steps

Add macos-11 as a runner.

**Comment by AlenaSviridenko** [comment]
Hi @julianhille, please, find the information about current state of macOS 11 pool and how to join the image preview in our README file under (Available Environments)[https://github.com/actions/virtual-environments#available-environments] section.

I am closing this issue. Please, feel free to contact us in case of any questions. Thanks.

**Comment by julianhille** [comment]
Thanks. Must have overlooked it.
