### ISSUE TITLE
Add SQL Server Express LocalDB

### ISSUE THREAD

**Issue by JohanPetersson** [actions/virtual-environments#3691]
### Tool name

SQL Server Express LocalDB

### Tool license

Developer edition - Free

### Add or update?

- [X] Add
- [ ] Update

### Desired version

Latest

### Brief description of tool

Makes it possible to test applications requiring MS SQL Server without the need to manage a full server instance of SQL Server. From Microsoft:
> LocalDB installation copies a minimal set of files necessary to start the SQL Server Database Engine. Once LocalDB is installed, you can initiate a connection using a special connection string. When connecting, the necessary SQL Server infrastructure is automatically created and started, enabling the application to use the database without complex configuration tasks. Developer Tools can provide developers with a SQL Server Database Engine that lets them write and test Transact-SQL code without having to manage a full server instance of SQL Server.

### URL for tool's homepage

https://docs.microsoft.com/en-us/sql/database-engine/configure-windows/sql-server-express-localdb?view=sql-server-ver15

### Provide a basic test case to validate the tool's functionality.

```bash
var connectionstring = $"Data Source=(LocalDb)\\MSSQLLocalDB;AttachDbFilename={path to MDF file};Initial Catalog=example-catalog;Integrated Security=True;Connect Timeout=30;MultipleActiveResultSets=True";
```

### Virtual environments affected

- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [X] Windows Server 2019

**Comment by miketimofeev** [comment]
Hi @JohanPetersson!
There were such requests before 
https://github.com/actions/virtual-environments/issues/1282
https://github.com/actions/virtual-environments/issues/1551
https://github.com/actions/virtual-environments/issues/1294

Could you please try the following PowerShell script to install SQL localdb in runtime? Does it work for your needs?
```
      Write-Host "Downloading"
      Import-Module BitsTransfer
      Start-BitsTransfer -Source https://download.microsoft.com/download/7/c/1/7c14e92e-bdcb-4f89-b7cf-93543e7112d1/SqlLocalDB.msi -Destination SqlLocalDB.msi
      Write-Host "Installing"
      Start-Process -FilePath "SqlLocalDB.msi" -Wait -ArgumentList "/qn", "/norestart", "/l*v SqlLocalDBInstall.log", "IACCEPTSQLLOCALDBLICENSETERMS=YES";
      Write-Host "Checking"
      sqlcmd -l 60 -S "(localdb)\MSSQLLocalDB" -Q "SELECT @@VERSION;"
```

**Comment by JohanPetersson** [comment]
Please excuse me, should have researched this a bit more before creating the issue. Installing in runtime should be good enough for my needs. Thanks!

**Comment by davidbuckleyni** [comment]
Do we know if this is achievable yet

**Comment by jonathanbex** [comment]
yes just add this step.

 - name: Install SQL LocalDB
        shell: pwsh
        run: |
          try {
            Write-Host "Checking if SQL LocalDB exists..."
            $instanceExists = & sqllocaldb info MSSQLLocalDB -ErrorAction SilentlyContinue
            if (-not $instanceExists) {
              Write-Host "SQL LocalDB not found. Downloading and installing..."
              Import-Module BitsTransfer
              Start-BitsTransfer -Source https://download.microsoft.com/download/7/c/1/7c14e92e-bdcb-4f89-b7cf-93543e7112d1/SqlLocalDB.msi -Destination SqlLocalDB.msi
              Write-Host "Installing SQL LocalDB..."
              Start-Process -FilePath "SqlLocalDB.msi" -Wait -ArgumentList "/qn", "/norestart", "/l*v SqlLocalDBInstall.log", "IACCEPTSQLLOCALDBLICENSETERMS=YES"
              Write-Host "SQL LocalDB installed successfully."
            } else {
              Write-Host "SQL LocalDB is already installed."
            }
          } catch {
            Write-Host "An error occurred during SQL LocalDB installation: $_"
            Write-Host "Continuing with the workflow as successful."
          } finally {
            Write-Host "SQL LocalDB installation step completed."
          }
           exit 0  # Ensure the step always exits with a success code
