### ISSUE TITLE
Update/Add Java

### ISSUE THREAD

**Issue by sfragata** [actions/virtual-environments#3693]
### Tool name

Java

### Tool license

same

### Add or update?

- [ ] Add
- [X] Update

### Desired version

java 15 and java 16

### Brief description of tool

The actual virtual environments supports until Java 14.
I'd like to upgrade java to 15 and 16

### Virtual environments affected

- [ ] Ubuntu 16.04
- [X] Ubuntu 18.04
- [X] Ubuntu 20.04
- [X] macOS 10.15
- [X] macOS 11
- [ ] Windows Server 2016
- [X] Windows Server 2019

**Comment by LeonidLapshin** [comment]
Hey, @sfragata, we'll consider this change and return back with response soon :)

**Comment by sfragata** [comment]
thanks

**Comment by catthehacker** [comment]
https://github.com/actions/virtual-environments/pull/3651#issuecomment-867805288

**Comment by LeonidLapshin** [comment]
Hi, @sfragata, as @catthehacker mentioned we install only LTS Java versions on Hosted images and Java 16 is not LTS.
Please use official action to setup any Java in runtime : https://github.com/actions/setup-java#basic 
Thanks!
