### ISSUE TITLE
macos-11 runner is broken

### ISSUE THREAD

**Issue by AshStefanOltmann** [actions/virtual-environments#3697]
### Description

Running the macos-11 environment shows nothing on the console and after that it says "This check failed".

### Virtual environments affected

- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [X] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019

### Image version and build link

I don't have anything here.

### Expected behavior

To work

### Actual behavior

Showing nothing on the console and failing.

### Repro steps

Change the machine from "macos-latest" to "macos-11"

**Comment by LeonidLapshin** [comment]
Hey, @AshStefanOltmann ! We'll check it and return back with information soon :)

**Comment by LeonidLapshin** [comment]
@AshStefanOltmann , the correct label is `macos-11` and now macos 11 available not for all customers, but you can[ sigh up for participating](https://github.com/actions/virtual-environments/blob/main/docs/macos-11-onboarding.md). I'll close the issue but feel free to reopen it if you have any concerns :)

**Comment by AshStefanOltmann** [comment]
@LeonidLapshin It's not documented that I can't use it.

And it also took a lot of my runner minutes before failing.

Why don't you at least let the whole build fail with something like "macos-11" runner is not available or so?

**Comment by AshStefanOltmann** [comment]
I signed up for participating. I need XCode 13.0 for async-await 

Now I found the preview hint in gray text, barely noticeable... 
I would really suggest that you make add a "(closed beta)" to the table itself.
I did not read all the text below that table.

**Comment by AshStefanOltmann** [comment]
@LeonidLapshin Do you have an idea how long it may take until I can build with Xcode 13?
May that be a week, a month or do you not know?

I must know if I need to plan a migration to CircleCI for the next sprint or not. Thank you.
