### ISSUE TITLE
Install full version of Boost on Windows

### ISSUE THREAD

**Issue by pitrou** [actions/virtual-environments#370]
**Tool information**
- Tool name: boost

**Area for Triage**:

**Question, Bug, or Feature?**: Feature

**Virtual environments affected**
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [x] Windows Server 2019

**Description**
Currently, only some stub install of boost seems provided in `BOOST_ROOT`. Libraries are not available, so they must be compiled in each workflow execution.

**Can this tool be installed during the build?**
`choco install -boost-msvc-14.1` should do it. It's a large install (2+GB), so preferable not to do it at each workflow execution.

**Comment by AlenaSviridenko** [comment]
Hi @pitrou ! Thanks for reporting the issue.
Could you please provide some additional information about the problem, maybe it is possible to share some steps to reproduce?

Also, please, take a look at this ticket https://github.com/actions/virtual-environments/issues/74, it could be the same issue you are experiencing now. If so, the fix will be delivered in a couple of days.

**Comment by pitrou** [comment]
@AlenaSviridenko I'm not sure what you mean here. According to my investigations, the Boost binary libraries are not provided in the `BOOST_ROOT` directory tree. This means that to actually link software with Boost, the Boost libraries have to be built first during the workflow execution, which is wasteful.

This issue is not about Boost.Build, which we are not using.

**Comment by pitrou** [comment]
By the way, here is how we worked around the issue:
https://github.com/apache/arrow/pull/6325/files#diff-f656dcc6ce6cd7f889b4a660d36866d4R185

This change replaced ~10 minutes of compiling with ~3 minutes of downloading and installing the Boost binaries. Still, that's probably 3 wasted minutes on every build :-)

**Comment by al-cheb** [comment]
Hi, @pitrou 
Could you please provide quick steps to reproduce the issue?

**Comment by erenon** [comment]
Hi, I have the same issue, my build fails with Boost 1.72:
https://github.com/Morgan-Stanley/binlog/runs/439567374?check_suite_focus=true

It was previously working with 1.69:
https://github.com/Morgan-Stanley/binlog/runs/426277644?check_suite_focus=true

The headers are found, but the libraries to be linked appears to have been built for a different version of msvc.

**Comment by al-cheb** [comment]
@erenon Hello,

Please try to use at the top in CMAKEList.txt

```
SET(Boost_USE_STATIC_LIBS OFF)
IF( WIN32 )
    # The auto-linking feature has problems with USE_STATIC_LIBS off, so we use
    # BOOST_ALL_NO_LIB to turn it off.
    # Several boost libraries headers aren't configured correctly if
    # USE_STATIC_LIBS is off, so we explicitly say they are dynamic with the
    # remaining definitions.
    ADD_DEFINITIONS(-DBOOST_ALL_NO_LIB -DBOOST_PROGRAM_OPTIONS_DYN_LINK -DBOOST_IOSTREAMS_DYN_LINK -DBOOST_THREAD_DYN_LINK)
ENDIF( )
```

CMAKELIST.txt - https://pastebin.com/raw/G87fCHxB
My example:

```
jobs:
  build:
    runs-on: [windows-latest]
    steps:
      - name: git clone
        run: |
          cd $env:UserProfile\Desktop
          git clone https://github.com/Morgan-Stanley/binlog.git
          cd  binlog
          Invoke-WebRequest https://pastebin.com/raw/G87fCHxB -OutFile CMakeLists.txt
          mkdir Release
          cd Release
          cmake -DBINLOG_FORCE_TESTS=ON ..
      - name: Build
        run: |
          cd $env:UserProfile\Desktop\binlog
          cmake --build Release --config Release -j2
      - name: Test
        run: |
          cd $env:UserProfile\Desktop\binlog
          $Env:path += ";${env:BOOST_ROOT}\lib"
          cd Release
          ctest -VV -C Release
```


![boost_1 72 0 ](https://user-images.githubusercontent.com/47745270/74525229-a779f180-4f31-11ea-9349-061b35b8bc70.JPG)

**Comment by erenon** [comment]
@al-cheb : wow, this is a really nice repro and fix!

Unfortunately, I don't get it.
Setting only `BOOST_ALL_NO_LIB` and `BOOST_ALL_DYN_LINK` doesn't work.
`SET(Boost_USE_STATIC_LIBS OFF)` is also needed, despite that the [documentation](https://cmake.org/cmake/help/latest/module/FindBoost.html) says the default is OFF.

At least the build is now green... Thanks!

**Comment by flexferrum** [comment]
I'm not sure is this correct issue or not, BTW, the problem somehow related.

Seems like the initial problem has been solved. Partially. But now it looks like that "static crt" versions of boost 1.72 libraries are actually linked with dynamic version of CRT:
https://github.com/jinja2cpp/Jinja2Cpp/runs/492758600?check_suite_focus=true#step:3:169
```console
libboost_filesystem-vc142-mt-x64-1_72.lib(path_traits.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MD_DynamicRelease' doesn't match value 'MT_StaticRelease' in basic_tests.obj [D:\a\Jinja2Cpp\Jinja2Cpp\.build\jinja2cpp_tests.vcxproj]
libboost_filesystem-vc142-mt-x64-1_72.lib(path.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MD_DynamicRelease' doesn't match value 'MT_StaticRelease' in basic_tests.obj [D:\a\Jinja2Cpp\Jinja2Cpp\.build\jinja2cpp_tests.vcxproj]
libboost_filesystem-vc142-mt-x64-1_72.lib(operations.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MD_DynamicRelease' doesn't match value 'MT_StaticRelease' in basic_tests.obj [D:\a\Jinja2Cpp\Jinja2Cpp\.build\jinja2cpp_tests.vcxproj]
```

I'm pretty sure the project itself is OK:
1. Linking with boost 1.69 works fine
2. I tested the same build configurations on the other CI farm and it worked well

**Comment by al-cheb** [comment]
Hello, @flexferrum 
Try to add flag /MT in CMakeLists.txt: 
`set(CMAKE_CXX_FLAGS_RELEASE "${CMAKE_CXX_FLAGS_RELEASE} /MT")`

**Comment by flexferrum** [comment]
Hello, @al-cheb 
I know this trick, but in this case it's unrelated. The root probolem is in another place.
`Windows-2019` build uses boost cmake finder (non-standard) which is different from `windows-2016` version (from the CMake distro). And this finder:
- Has separate `find` methods for some libraries from boost. With this finder you can write `find(boost_filesystem)` and it will work
- This finder ignores standard hints (such as `BOOST_ROOT`). I was failed to specify `1.69` version of boost for my builds

I managed to solve problem with my build. But, I think, usage of custom Boost 1.72 CMake finders for Windows-2019 host should be mentoined in the docs.

**Comment by al-cheb** [comment]
@flexferrum 
BOOST_ROOT will be deprecated in several week.

**Comment by flexferrum** [comment]
@al-cheb 
> The `BOOST_ROOT` env variable will be deprecated in several week.
And what will be new way to point boost installation? Are there any docs regarding to this?

**Comment by al-cheb** [comment]
https://github.com/actions/virtual-environments/blob/releases/win19/20200301/images/win/Windows2019-Readme.md: BOOST_ROOT_1_69_0 and BOOST_ROOT_1_72_0

**Comment by flexferrum** [comment]
> https://github.com/actions/virtual-environments/blob/releases/win19/20200301/images/win/Windows2019-Readme.md: BOOST_ROOT_1_69_0 and BOOST_ROOT_1_72_0

I read this. BTW I found no way to point CMake to the 1.69 installation. Looks like path to boost 1.72 cmake helpers is hardcoded somehow  in CMAKE_MODULES_PATH. But I'm not completely sure.

**Comment by al-cheb** [comment]
@flexferrum 
We don't have any hardcoded path for CMAKE. Only predefined `BOOST_ROOT=C:\hostedtoolcache\windows\Boost\1.72.0`

**Comment by flexferrum** [comment]
> @flexferrum
> We don't have any hardcoded path for CMAKE. Only predefined: `BOOST_ROOT=C:\hostedtoolcache\windows\Boost\1.72.0`

I'm pretty sure about this. But in the windows-2016 (with Boost 1.69) environment CMake uses the default finder:
```
-- [ C:/Program Files/CMake/share/cmake-3.16/Modules/FindBoost.cmake:1463 ]
```
https://github.com/jinja2cpp/Jinja2Cpp/runs/495118084?check_suite_focus=true#step:3:184

On the windows-2019 it uses finder shipped with Boost 1.72:
```
-- Found Boost 1.72.0 at C:/hostedtoolcache/windows/Boost/1.72.0/lib/cmake/Boost-1.72.0
```
https://github.com/jinja2cpp/Jinja2Cpp/runs/495118215?check_suite_focus=true#step:3:192

Somehow CMake able to find these modules.

**Comment by al-cheb** [comment]
@flexferrum 
What happens if try to delete `C:/hostedtoolcache/windows/Boost/1.72.0/lib/cmake` folder before build?

**Comment by flexferrum** [comment]
@al-cheb 
It uses the standard CMake finder:
```
-- [ C:/Program Files/CMake/share/cmake-3.16/Modules/FindBoost.cmake:1463 ] 
```

https://github.com/jinja2cpp/Jinja2Cpp/runs/498202815?check_suite_focus=true

**Comment by al-cheb** [comment]
@flexferrum 
https://cmake.org/cmake/help/latest/module/FindBoost.html

If Boost was built using the boost-cmake project or from Boost 1.70.0 on it provides a package configuration file for use with find_package’s config mode. This module looks for the package configuration file called BoostConfig.cmake or boost-config.cmake and stores the result in CACHE entry “Boost_DIR”. If found, the package configuration file is loaded and this module returns with no further action. See documentation of the Boost CMake package configuration for details on what it provides.

Set Boost_NO_BOOST_CMAKE to ON, to disable the search for boost-cmake.

**Comment by flexferrum** [comment]
@al-cheb , thanks, I'll try. I still think, it should be mentoined in the docs.

**Comment by al-cheb** [comment]
@flexferrum , Sure I will add this section to the Windows2019-Readme.md.

**Comment by al-cheb** [comment]
The docs were updated. Feel free to open the thread if you have any questions.
