### ISSUE TITLE
[Windows] Update gfortran

### ISSUE THREAD

**Issue by everythingfunctional** [actions/virtual-environments#3702]
### Tool name

gfortran

### Tool license

GPL

### Add or update?

- [ ] Add
- [X] Update

### Desired version

11

### Brief description of tool

The Gnu Compiler Collection (GCC) fortran compiler. The currently installed version (8) is three years old, and doesn't support features of the latest Fortran standard.

### URL for tool's homepage

gcc.gnu.org

### Virtual environments affected

- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [X] Windows Server 2019

### Can this tool be installed during the build?

```bash
No, there are no command line installers available (or at least I haven't been able to find one).
```

**Comment by miketimofeev** [comment]
Hi @everythingfunctional!
We have MSYS2 GCC package which includes gfortran 10.3.0, which will probably be updated to version 11 one day. To use it you need to add MSYS2 to the path:
```
$env:PATH = "C:\msys64\mingw64\bin;C:\msys64\usr\bin;$env:PATH"
gfortran --version
```
Does it suit your needs? 
We wouldn't like to add a separate gfortran installation to the image due to maintenance concerns.

**Comment by everythingfunctional** [comment]
Hi @miketimofeev , Thanks for the quick response. Version 10.3.0 should be sufficient for my needs. I did not realize it was installed already. I will try adding it to the path and see if that works.

Is there any way documentation somewhere could be updated for this? I couldn't find any indication that gcc (or gfortran) was even installed in the Windows environment, let alone what version or how to access it.

**Comment by miketimofeev** [comment]
@everythingfunctional, unfortunately, no, as the msys2 package configuration is subject to change — probably in the future we will provide bare MSYS2 installation as the packages are installed in a few seconds

**Comment by everythingfunctional** [comment]
That's disappointing. Also, for future reference to anybody that happens across this issue, I had to amend the `PATH` using this step in my CI script:

```yml
    - name: Add newer gfortran to PATH
      shell: bash
      run: |
        echo "C:\msys64\mingw64\bin" >> $GITHUB_PATH
        echo "C:\msys64\usr\bin" >> $GITHUB_PATH
```

**Comment by miketimofeev** [comment]
@everythingfunctional another possible option is to use https://github.com/msys2/setup-msys2 action, which adds installation to the path.
I'm going to close the issue. Please feel free to contact us if you have any concerns.
Thank you!

**Comment by miketimofeev** [comment]
@praynaud we have decided not to install MSYS2 toolchains\components on windows-2022 image. The discussion around it can be found in this PR https://github.com/actions/virtual-environments/pull/4245
