### ISSUE TITLE
msbuild failure in CI loop using .net sdk version 3.1.201

### ISSUE THREAD

**Issue by kmelmon** [actions/virtual-environments#3704]
### Description

It looks like the virtual environment is installing the .net sdk version 3.1.201 to a different location than the build target expects.

According to the readme, this sdk is being installed to C:\Program Files\dotnet\sdk.
I have a CI loop that uses .net 3.1.201 as a target and I'm hitting a build failure that expects the SDK to be installed to C:\Users\runneradmin\AppData\Local\Microsoft.  Since it's not installed there the build fails in the CI loop.

### Virtual environments affected

- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [X] Windows Server 2019

### Image version and build link

Version:  20210628.1

Link to failed build:  https://github.com/microsoft/Xaml-Islands-Samples/pull/48/checks?check_run_id=3033380491

### Is it regression?

yes last version where it worked was Version: 20210425.1, link:  https://github.com/microsoft/Xaml-Islands-Samples/runs/2560511721?check_suite_focus=true#step:1:6

### Expected behavior

build should succeed

### Actual behavior

build fails with this error:

C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\DesktopBridge\Microsoft.DesktopBridge.targets(16,3): error MSB4019: The imported project "C:\Users\runneradmin\AppData\Local\Microsoft\dotnet\sdk\3.1.201\Sdks\Microsoft.NET.Sdk\Sdk\Sdk.NuGet.targets" was not found. Confirm that the expression in the Import declaration "C:\Users\runneradmin\AppData\Local\Microsoft\dotnet\sdk\3.1.201\Sdks\Microsoft.NET.Sdk\Sdk\Sdk.NuGet.targets" is correct, and that the file exists on disk.

### Repro steps

Easiest way to repro would be to clone this repo and submit a PR:
https://github.com/microsoft/Xaml-Islands-Samples

**Comment by miketimofeev** [comment]
Hi @kmelmon!
We will take a look at this. 
Have you tried to use https://github.com/actions/setup-dotnet actions that we are own? Does it help? I'm also asking this because the latest patch version for 3.1.2xx is 3.1.202 and we will probably remove all the versions except the latest patch in the future as we did for Ubuntu https://github.com/actions/virtual-environments/issues/3338

**Comment by kmelmon** [comment]
@miketimofeev thanks for looking!  Using setup-dotnet won't really help for our repo as we have native C++ samples mixed in with the C# samples.

**Comment by LeonidLapshin** [comment]
Hey, @kmelmon !
Removing setup dotnet action fixes previous error, now I see ' A certificate with thumbprint '2867B7231CC8D45237825E1DE3394146A3B09134' that is specified in the project cannot be found in the certificate store'  while building. [Could you please take a look](https://github.com/microsoft/Xaml-Islands-Samples/pull/49)?

**Comment by LeonidLapshin** [comment]
Hey, @kmelmon !
I'll close this issue due to inactivity, but feel free to mention me here and we'll continue to research the problem if it still persist.
