### ISSUE TITLE
Update ansible to 2.11.x: rename ansible-base to ansible-core

### ISSUE THREAD

**Issue by petermylemans** [actions/virtual-environments#3708]
### Tool name

ansbile

### Tool license

GNU GPL 3.0

### Add or update?

- [ ] Add
- [X] Update

### Desired version

2.11.x (latest)

### Brief description of tool

https://docs.ansible.com/ansible/latest/installation_guide/intro_installation.html#upgrading-from-ansible-3-or-ansible-core-2-10

Ansible base package seems to renamed from ansible-base to ansible-core so auto patching is no longer working at the moment.

### Virtual environments affected

- [ ] Ubuntu 16.04
- [X] Ubuntu 18.04
- [X] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019

**Comment by miketimofeev** [comment]
Hi @petermylemans!
Thanks for notifying us about such changes. We will take a look and prepare a PR if needed.

**Comment by al-cheb** [comment]
Hi, @petermylemans 
To install ansible 2.11 in runtime, you can use:
```
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
        - run: |
            pipx uninstall ansible-base
            pipx install ansible-core
            pipx inject ansible-core ansible
            ansible --version
```
![image](https://user-images.githubusercontent.com/47745270/125249573-0944b380-e2fe-11eb-8e80-664ab04c05cb.png)

**Comment by al-cheb** [comment]
The new images have been deployed with ansible 2.11.2.

![image](https://user-images.githubusercontent.com/47745270/126483630-9d19215a-a9b8-46f0-b546-3c7c665dac7c.png)
