### ISSUE TITLE
Include XCode 12.5

### ISSUE THREAD

**Issue by aprilmintacpineda** [actions/virtual-environments#3709]
### Description

I got the following error when archiving our app:

```
❌ ld: could not reparse object file in bitcode bundle: 'Invalid bitcode version (Producer: '1205.0.22.9.0_0' Reader: '1200.0.32.29_0')', using libLTO version 'LLVM version 12.0.0, (clang-1200.0.32.29)' for architecture arm64
```

After researching, I found that this was because of xcode version, and sure enough this does not happen when I try to archive locally -- because I'm using xcode 12.5.1 -- one of our dependencies probably depends on xcode 12.5.1

### Virtual environments affected

- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [X] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019

### Image version and build link

Don't really have one, sorry.

### Is it regression?

N/A

### Expected behavior

N/A

### Actual behavior

N/A

### Repro steps

N/A

**Comment by maxim-lobanov** [comment]
@aprilmintacpineda , 12.5.1 is installed on the image alongside with 12.5.
Have you tried to switch default Xcode? The full list of installed Xcode versions is available in readme: https://github.com/actions/virtual-environments/blob/main/images/macos/macos-11-Readme.md#xcode

**Comment by miketimofeev** [comment]
@aprilmintacpineda the following snippet can be used to switch Xcode in runtime
`sudo xcode-select -s "/Applications/Xcode_12.5.1.app"`
If you need access to macOS-11 in azure pipelines as I noticed in this comment https://github.com/actions/virtual-environments/issues/2072#issuecomment-877894854 please send an e-mail with the name of your Azure DevOps organization and the # of concurrent jobs you expect to run on macOS-11 to @vijayma

**Comment by aprilmintacpineda** [comment]
Ah sorry, I did not specify that we are using azure pipelines, the docs https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops&tabs=yaml lead me here, according to the docs, only macos-10.15 is supported....

**Comment by aprilmintacpineda** [comment]
> @aprilmintacpineda the following snippet can be used to switch Xcode in runtime
> `sudo xcode-select -s "/Applications/Xcode_12.5.1.app"`
> If you need access to macOS-11 in azure pipelines as I noticed in this comment [#2072 (comment)](https://github.com/actions/virtual-environments/issues/2072#issuecomment-877894854) please send an e-mail with the name of your Azure DevOps organization and the # of concurrent jobs you expect to run on macOS-11 to @vijayma

That's way above me in this case, but I will ask my superiors about this, thank you.

**Comment by miketimofeev** [comment]
@aprilmintacpineda I'm going to close the issue then since it's not related to the image content directly. 
Please feel free to contact us if you have any concerns.
Thank you!
