### ISSUE TITLE
Install full version of OpenSSL on Windows

### ISSUE THREAD

**Issue by pitrou** [actions/virtual-environments#371]
**Tool information**
- Tool name: OpenSSL

**Area for Triage**:

**Question, Bug, or Feature?**:
Feature

**Virtual environments affected**
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [x] Windows Server 2019

**Can this tool be installed during the build?**
Yes, using `choco install openssl` (*not* `openssl.light`)

**Description**
The Windows Server 2019 only provides a "light" version of OpenSSL in `C:\Program Files\OpenSSL`. It doesn't provide any development headers, so the software under test cannot be compiled against OpenSSL. It would be better to provide a full version of OpenSSL, using the [openssl](https://chocolatey.org/packages/openssl) chocolatey package, rather than [openssl.light](https://chocolatey.org/packages/OpenSSL.Light).

**Comment by thejoebourneidentity** [comment]
Thanks @pitrou, is the full version of OpenSSL much larger than the light? How big is the full installation?

**Comment by pitrou** [comment]
On my VM I can see:
- `C:\Program Files\OpenSSL` (light version): ~10 MB
- `C:\Program Files\OpenSSL-Win64` (full version): ~270 MB

Most of the full version is the `lib` subdirectory (~215 MB), but part of it is the `tests` subdirectory (~40 MB). I suppose the latter could be omitted.

**Comment by MSP-Greg** [comment]
The largest part (166 MB) of the lib directory is the VC\static *.lib files.  I've never used them to build against OpenSSL...

**Comment by alepauly** [comment]
Hi @pitrou - sorry for the delay in responding here. Considering maintenance concerns and the fact that it can be installed during the build, we are not going to pre-install this into the virtual environments. Thanks for reaching out.

**Comment by MilindVaidya03** [comment]
Can we install win32 version of OpenSSL using choco install function
