### ISSUE TITLE
[Ubuntu] Ansible will be updated to Ansible 4 on July, 19th

### ISSUE THREAD

**Issue by AlenaSviridenko** [actions/virtual-environments#3714]
### Breaking changes

`Ansible-base` package will be updated to `ansible-core`, which will upgrade Ansible 3 -> Ansible 4 https://docs.ansible.com/ansible/latest/installation_guide/intro_installation.html#upgrading-from-ansible-3-or-ansible-core-2-10

### Target date

Deployment will start on July, 19th and will take 3-4 days.

### The motivation for the changes

We'd like to keep images up-to-date with recent software updates.

### Possible impact

Projects that depend on `ansible-base` or Ansible 3 can be broken after upgrade. More information about breaking changes can be found on the official changelog https://github.com/ansible-community/ansible-build-data/blob/main/4/CHANGELOG-v4.rst

### Virtual environments affected

- [ ] Ubuntu 16.04
- [X] Ubuntu 18.04
- [X] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019

### Mitigation ways

Use the following snippet to uninstall `ansible-core` and install `ansible-base` with Ansible 3.
```
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
        - run: |
            pipx uninstall ansible-core
            pipx install ansible-base
            pipx inject ansible-base ansible==3.4.0
            ansible --version
```

**Comment by al-cheb** [comment]
The new images have been deployed:
![image](https://user-images.githubusercontent.com/47745270/126483725-339c757f-43bc-4f23-954a-844554fa23cf.png)
