### ISSUE TITLE
PHP Composer triggers deprecation notice

### ISSUE THREAD

**Issue by oldskool** [actions/virtual-environments#372]
**Describe the bug**
I've been receiving several emails from GitHub in the last 2-3 days stating:

> On February 5th, 2020 at 14:33 (UTC) your personal access token (github-actions) using Composer/1.9.2 (Linux; 5.0.0-1028-azure; PHP 7.1.33) was used as part of a query parameter to access an endpoint through the GitHub API:
> 
> https://api.github.com/repositories/(...)/zipball/(...)
> 
> Please use the Authorization HTTP header instead, as using the `access_token` query parameter is deprecated.
> 
> Depending on your API usage, we'll be sending you this email reminder once every 3 days for each token and User-Agent used in API calls made on your behalf.
> Just one URL that was accessed with a token and User-Agent combination will be listed in the email reminder, not all.
> 
> Visit https://developer.github.com/changes/2019-11-05-deprecated-passwords-and-authorizations-api/#authenticating-using-query-parameters for more information.

This is a known issue and [a fix has been published in Composer](https://github.com/composer/composer/issues/8454#issuecomment-581875987). However the mails keep triggering, so it seems some Actions machines still run an older version. Is there any way this can be synced to the latest version? 

The key mentioned in the email is *exclusively* used by our GitHub Actions flow, so the workers seem to be running an outdated version.

**Area for Triage**: PHP

**Question, Bug, or Feature?**: Feature

**Virtual environments affected**
- [ ] macOS 10.15
- [x] Ubuntu 16.04 LTS
- [x] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

Confirmed on Ubuntu machines, probably applies to more.

**Expected behavior**
Composer being able to pull packages from the GitHub API without triggering those emails.

**Actual behavior**
The email as quoted above is being sent out.

**Comment by miketimofeev** [comment]
@oldskool thanks for reporting this. Composer will be updated to 1.9.3 automatically on next image rollout(approx. 1-2 weeks)

**Comment by miketimofeev** [comment]
@oldskool composer has been updated as you can see here
https://github.com/actions/virtual-environments/releases/tag/ubuntu18%2F20200217.1
https://github.com/actions/virtual-environments/releases/tag/ubuntu16%2F20200217.1
Is everything ok now?

**Comment by miketimofeev** [comment]
@oldskool I'm going to close the issue. Feel free to reopen if you have any concerns, thanks!
