### ISSUE TITLE
[Ubuntu] Fail to install Node.js package globally for default Node.js

### ISSUE THREAD

**Issue by maxim-lobanov** [actions/virtual-environments#3727]
### Description

When trying to install any Node.js package globally, it fails with permission errors.
For example: `npm install -g pnpm`.

Installation will success with sudo but it is not recommended to use `sudo` for it.

### Virtual environments affected

- [X] Ubuntu 16.04
- [X] Ubuntu 18.04
- [X] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019

### Image version and build link

Any image version. Build link: https://github.com/maxim-lobanov/test-repo/runs/3065927346?check_suite_focus=true

### Is it regression?

No, looks like it has never worked

### Expected behavior

`npm install -g pnpm` command passes without any errors and `pnpm --version` works after that.

### Actual behavior

Installation fails with the following error message:
```
##[debug]/usr/bin/bash -e /home/runner/work/_temp/19383bb5-f7aa-40e5-a20d-504343d9aec7.sh
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules
npm ERR! code EACCES
npm ERR! syscall access
npm ERR! path /usr/local/lib/node_modules
npm ERR! errno -13
npm ERR! Error: EACCES: permission denied, access '/usr/local/lib/node_modules'
npm ERR!  [Error: EACCES: permission denied, access '/usr/local/lib/node_modules'] {
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/usr/local/lib/node_modules'
npm ERR! }
npm ERR! 
```

The issue can be fixed in runtime by running the following commands:
```bash
sudo chmod 777 /usr/local/lib/node_modules -R
sudo chmod 777 /usr/local/bin
```

Please note that it is not enough to set permissions for `/usr/local/lib/node_modules` because installation will continue to fail on creating symlink to `/usr/local/bin` with error message:
```
npm ERR! code EACCES
npm ERR! syscall symlink
npm ERR! path ../lib/node_modules/pnpm/bin/pnpm.cjs
npm ERR! dest /usr/local/bin/pnpm
npm ERR! errno -13
npm ERR! Error: EACCES: permission denied, symlink '../lib/node_modules/pnpm/bin/pnpm.cjs' -> '/usr/local/bin/pnpm'
npm ERR!  [OperationalError: EACCES: permission denied, symlink '../lib/node_modules/pnpm/bin/pnpm.cjs' -> '/usr/local/bin/pnpm'] {
npm ERR!   cause: [Error: EACCES: permission denied, symlink '../lib/node_modules/pnpm/bin/pnpm.cjs' -> '/usr/local/bin/pnpm'] {
npm ERR!     errno: -13,
```

### Repro steps

```yml
on: [ push, pull_request ]

jobs:

  test1:
    runs-on: ubuntu-latest
    steps:
      - run: npm install -g pnpm
      - run: pnpm --version
```

**Comment by LeonidLapshin** [comment]
npm global modules can be installed without sudo/workarounds after the next image rollout.

**Comment by miketimofeev** [comment]
@maxim-lobanov the images were deployed, feel free to contact us if you have any concerns 😉

**Comment by isaacegglestone** [comment]
Why did we decide making /usr/local/bin writable by all users on the machine was safe?
Typically thats a bad idea on a linux system.

Just trying to understand the logic here.
