### ISSUE TITLE
Runner leaks file descriptors to user processes

### ISSUE THREAD

**Issue by rfjakob** [actions/virtual-environments#3729]
**Describe the bug**

Github Actions creates processes with seemingly unrelated file descriptors open.

Affected job: https://github.com/rfjakob/earlyoom/runs/2987949357?check_suite_focus=true

**To Reproduce**

Add the line
```
    - run: ls -l /proc/self/fd
```
to your workflow.

Run the workflow and you get:

```
Run ls -l /proc/self/fd
total 0
lr-x------ 1 runner docker 64 Jul  5 07:53 0 -> pipe:[32613]
l-wx------ 1 runner docker 64 Jul  5 07:53 1 -> pipe:[32614]
lr-x------ 1 runner docker 64 Jul  5 07:53 106 -> pipe:[31552]
l-wx------ 1 runner docker 64 Jul  5 07:53 109 -> pipe:[31553]
lrwx------ 1 runner docker 64 Jul  5 07:53 11 -> socket:[31953]
lrwx------ 1 runner docker 64 Jul  5 07:53 14 -> socket:[31988]
l-wx------ 1 runner docker 64 Jul  5 07:53 2 -> pipe:[32615]
lr-x------ 1 runner docker 64 Jul  5 07:53 3 -> /proc/1647/fd
lr-x------ 1 runner docker 64 Jul  5 07:53 45 -> /dev/urandom
lr-x------ 1 runner docker 64 Jul  5 07:53 47 -> /dev/urandom
lrwx------ 1 runner docker 64 Jul  5 07:53 8 -> socket:[23730]
```

What are file descriptors 8,11,14,45,47,106,109 and why you do you pass them to user processes?

**Expected behavior**

No leaked / unrelated file descriptors:

Plain Ubuntu:
```
vagrant@ubuntu2004:~$ ls -l /proc/self/fd
total 0
lrwx------ 1 vagrant vagrant 64 Jul  5 08:06 0 -> /dev/pts/0
lrwx------ 1 vagrant vagrant 64 Jul  5 08:06 1 -> /dev/pts/0
lrwx------ 1 vagrant vagrant 64 Jul  5 08:06 2 -> /dev/pts/0
lr-x------ 1 vagrant vagrant 64 Jul  5 08:06 3 -> /proc/4775/fd
```

Docker on Ubuntu:
```
vagrant@ubuntu2004:~$ docker run -it ubuntu
Unable to find image 'ubuntu:latest' locally
latest: Pulling from library/ubuntu
c549ccf8d472: Pull complete 
Digest: sha256:aba80b77e27148d99c034a987e7da3a287ed455390352663418c0f2ed40417fe
Status: Downloaded newer image for ubuntu:latest
root@9f9bdee4ce17:/# ls -l /proc/self/fd
total 0
lrwx------ 1 root root 64 Jul  5 08:06 0 -> /dev/pts/0
lrwx------ 1 root root 64 Jul  5 08:06 1 -> /dev/pts/0
lrwx------ 1 root root 64 Jul  5 08:06 2 -> /dev/pts/0
lr-x------ 1 root root 64 Jul  5 08:06 3 -> /proc/9/fd
```

## Runner Version and Platform

```
Current runner version: '2.278.0'
Operating System
  Ubuntu
  20.04.2
  LTS
Virtual Environment
  Environment: ubuntu-20.04
  Version: 20210628.1
  Included Software: https://github.com/actions/virtual-environments/blob/ubuntu20/20210628.1/images/linux/Ubuntu2004-README.md
  Image Release: https://github.com/actions/virtual-environments/releases/tag/ubuntu20%2F20210628.1
```

## What's not working?

The extra file descriptor cause the test suite to believe there is a fd leak in the software and fails:

https://github.com/rfjakob/earlyoom/runs/2987949357?check_suite_focus=true

## Job Log Output

```
=== RUN   TestCli/#00
countFds: earlyoom has too many open fds:
/proc/2439/fd/0 -> /dev/null, err=<nil>
/proc/2439/fd/1 -> pipe:[35123], err=<nil>
/proc/2439/fd/2 -> pipe:[35124], err=<nil>
/proc/2439/fd/3 -> /proc/meminfo, err=<nil>
/proc/2439/fd/8 -> socket:[23730], err=<nil>
/proc/2439/fd/11 -> socket:[31953], err=<nil>
/proc/2439/fd/14 -> socket:[31988], err=<nil>
/proc/2439/fd/45 -> /dev/urandom, err=<nil>
/proc/2439/fd/47 -> /dev/urandom, err=<nil>
/proc/2439/fd/106 -> pipe:[31552], err=<nil>
/proc/2439/fd/109 -> pipe:[31553], err=<nil>
    testsuite_cli_test.go:180: High number of open file descriptors: 11
```

**Comment by al-cheb** [comment]
Hi, @rfjakob
Please take a look - https://github.com/actions/virtual-environments/issues/3391#issuecomment-842139475. After applying a workaround:
![image](https://user-images.githubusercontent.com/47745270/125740876-a25bbe7e-f40f-4891-b113-e7fad9a3dd45.png)

**Comment by rfjakob** [comment]
Hi, thanks for the reply, but why would you pass .net debugging descriptors on to arbitrary user processes? In my case, it's a C app.

**Comment by rfjakob** [comment]
Also, two of the fds point to /dev/urandom, which is obviously not .net tracing.

**Comment by al-cheb** [comment]
> Hi, thanks for the reply, but why would you pass .net debugging descriptors on to arbitrary user processes? In my case, it's a C app.

It's by default:
https://docs.fedoraproject.org/en-US/Fedora_Security_Team/1/html/Defensive_Coding/sect-Defensive_Coding-Tasks-Descriptors-Child_Processes.html

`Child processes created with fork share the initial set of file descriptors with their parent process. By default, file descriptors are also preserved if a new process image is created with execve (or any of the other functions such as system or posix_spawn).`

**Comment by rfjakob** [comment]
There's something interesting: https://github.com/actions/virtual-environments/issues/3391#issuecomment-842139475 : 

```
      \_ /home/runner/runners/2.278.0/bin/Runner.Worker spawnclient 106 109
          \_ /usr/bin/bash -e /home/runner/work/_temp/9e49bfdd-bcb2-4ff2-a51b-6640bb1d79ec.sh
```
In the original description I noted that fds 106,109 are among those that are open.

Looks like they are explicitely created by `Runner.Worker spawnclient 106 109`.

**Comment by al-cheb** [comment]
@TingluoHuang, Could you please clarify a bit about `Runner.Worker spawnclient 106 109` decriptors?

**Comment by TingluoHuang** [comment]
that's the communication channel between `Runner.Listener` and `Runner.Worker`, so the Listener can send job message or cancellation to the Worker

**Comment by rfjakob** [comment]
Does the bash script use them as well?

**Comment by TingluoHuang** [comment]
no

**Comment by rfjakob** [comment]
Ok, I can workaround this using the bash hack mentioned by @al-cheb . But I would call this a minor bug.

**Comment by al-cheb** [comment]
Not a bug.

**Comment by rfjakob** [comment]
Just for people stumbling on this old ticket: Looks like as of Feb 9, 2025, all extra fds except two (155,158 below) have been cleaned up by github 👍

```
Run ls -l /proc/self/fd
total 0
lr-x------ 1 runner docker 64 Feb  9 21:19 0 -> pipe:[10836]
l-wx------ 1 runner docker 64 Feb  9 21:19 1 -> pipe:[10837]
lr-x------ 1 runner docker 64 Feb  9 21:19 155 -> pipe:[11630]
l-wx------ 1 runner docker 64 Feb  9 21:19 158 -> pipe:[11631]
l-wx------ 1 runner docker 64 Feb  9 21:19 2 -> pipe:[10838]
lr-x------ 1 runner docker 64 Feb  9 21:19 3 -> /proc/1806/fd
```
