### ISSUE TITLE
Add .net core SDK 5.0.302

### ISSUE THREAD

**Issue by asklar** [actions/virtual-environments#3731]
### Tool name

.net core SDK

### Tool license

https://dotnet.microsoft.com/en/dotnet_library_license.htm

### Add or update?

- [X] Add
- [ ] Update

### Desired version

5.0.302

### Brief description of tool

new version of .net 5.0.302

### URL for tool's homepage

https://dotnet.microsoft.com/

### Virtual environments affected

- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [X] Windows Server 2019

**Comment by miketimofeev** [comment]
Hi @asklar!
The version will be available after next week's image rollout. Until then https://github.com/actions/setup-dotnet action can be used.

**Comment by asklar** [comment]
thanks for the quick reply!

**Comment by miketimofeev** [comment]
@asklar all the images were deployed. I'm going to close the issue. Please feel free to contact us if you have any concerns.
Thank you!
