### ISSUE TITLE
[macOS] Update Xcode 13 to 13A5192i (beta 3)

### ISSUE THREAD

**Issue by zhuorantan** [actions/virtual-environments#3732]
### Tool name

Xcode 13

### Tool license

Copyrighted

### Add or update?

- [ ] Add
- [X] Update

### Desired version

13A5192i (beta 3)

### Virtual environments affected

- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [X] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019

**Comment by miketimofeev** [comment]
Hi @zhuorantan! The new image version with updated Xcode will be available early next week.

**Comment by miketimofeev** [comment]
@zhuorantan the new image has been deployed.
I'm going to close the issue. Please feel free to contact us if you have any concerns.
Thank you!
