### ISSUE TITLE
Update/Add a way to communicate between github runners

### ISSUE THREAD

**Issue by akramdhiabii** [actions/virtual-environments#3736]
### Description

The idea is simple.
Suppose I have 2 independent jobs:

1)  JOB-A using its runner and running application A ( a web server)

1)  JOB-B using its runner and running application B ( an API)

Application A needs to invoke Application B.

Is there a way to make it happen?

Thanks in advance

### Virtual environments affected

- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [X] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019

### Image version and build link

ubuntu-lates image

### Repro steps

See above

**Comment by miketimofeev** [comment]
Hi @akramdhiabii!
Well, there is no simple way to do it with the current configuration since runners are completely isolated from each other on the network level. The only thoughts that come to my mind are to either create a tunnel between these 2 VMs with some software or run both services on the same runner in docker containers.

**Comment by akramdhiabii** [comment]
> Hi @akramdhiabii!
> Well, there is no simple way to do it with the current configuration since runners are completely isolated from each other on the network level. The only thoughts that come to my mind are to either create a tunnel between these 2 VMs with some software or run both services on the same runner in docker containers.

Hi @miketimofeev  I thought about running both services on the same runner in docker containers but application B has been conceived to run in parallel ( a job by itself) so it has to be separated from application A.

**Comment by maxim-lobanov** [comment]
@akramdhiabii , I think you can create two docker containers and configure docker compose to connect them. It will allow to run both in parallel.

**Comment by akramdhiabii** [comment]
> @akramdhiabii , I think you can create two docker containers and configure docker compose to connect them. It will allow to run both in parallel.

Hi @maxim-lobanov , this will not help as the application-B should run similar jobs in parallel with different inputs on a runner(a parallel github actions job) , those jobs have to interfere in the same time with a single application-A which should be hosted in a different runner (job).

**Comment by miketimofeev** [comment]
@akramdhiabii you can pass different inputs to the docker-compose services. We're not aware of any possible interaction methods between separate runners as they are isolated.

**Comment by miketimofeev** [comment]
I'm going to close the issue. Please feel free to contact us if you have any concerns.
Thank you!
