### ISSUE TITLE
Changing the linux configuration.

### ISSUE THREAD

**Issue by Prajwal-Koirala** [actions/virtual-environments#3738]
### Description

Hello,
How would I update the github actions DNS resolvers?
Also, how would I run this command on  github actions? `ulimit -n 500000`
- prajwal

### Virtual environments affected

- [X] Ubuntu 16.04
- [X] Ubuntu 18.04
- [X] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019

### Image version and build link

```
Current runner version: '2.278.0'
Operating System
  Ubuntu
  20.04.2
  LTS
Virtual Environment
  Environment: ubuntu-20.04
  Version: 20210712.0
  Included Software: https://github.com/actions/virtual-environments/blob/ubuntu20/20210712.0/images/linux/Ubuntu2004-README.md
  Image Release: https://github.com/actions/virtual-environments/releases/tag/ubuntu20%2F20210712.0
GITHUB_TOKEN Permissions
  Actions: write
  Checks: write
  Contents: write
  Deployments: write
  Discussions: write
  Issues: write
  Metadata: read
  Packages: write
  PullRequests: write
  RepositoryProjects: write
  SecurityEvents: write
  Statuses: write
Prepare workflow directory
Prepare all required actions
Getting action download info
Download action repository 'actions/setup-go@v2'
Download action repository 'actions/checkout@v2'
```

https://github.com/complexorganizations/content-blocker/runs/3081270137

**Comment by miketimofeev** [comment]
Hi @Prajwal-Koirala!
Could you please clarify what problem are you trying to solve?

**Comment by Prajwal-Koirala** [comment]
> Hi @Prajwal-Koirala!
> Could you please clarify what problem are you trying to solve?

Hey,
Because some DNS providers have a rate limit, I'd like to update the dns resolvers that github activities is utilizing.

In Linux, there is a pretty awful feature that I really dislike: they limit the number of files that can be opened and closed at once, and the only way to remedy it is to adjust the limits with `ulimit -n 500000`, but how would I run that on my github actions?


https://github.com/complexorganizations/content-blocker/runs/3077357903?check_suite_focus=true

Take a look at that, i have tried 
```
sudo rm -f /etc/resolv.conf
sudo echo "nameserver 8.8.8.8" >>/etc/resolv.conf
```
It still dosent work.

**Comment by al-cheb** [comment]
> ulimit -n 500000
1. Set 8.8.8.8 as a dns server
2. Set new limits per process in rutime
3. 
```
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Set 8.8.8.8 as dns server
          run: |
            sudo sed -i 's/#DNS=/DNS=8.8.8.8 8.8.4.4/g' /etc/systemd/resolved.conf
            sudo systemctl daemon-reload
            sudo systemctl restart systemd-networkd
            sudo systemctl restart systemd-resolved
        - run: |
              sudo prlimit --pid $$ --nofile=500000:500000
              ulimit -a
```

![image](https://user-images.githubusercontent.com/47745270/125901475-1f248ae8-25ae-4c97-9ba2-eb36e28fe488.png)

**Comment by Prajwal-Koirala** [comment]
Do you have any idea why deleting the file isn't permitted?

**Comment by al-cheb** [comment]
> Do you have any idea why deleting the file isn't permitted?
```
 # Third party programs must not access this file directly, but only through the
# symlink at /etc/resolv.conf. To manage man:resolv.conf(5) in a different way,
# replace this symlink by a static file or a different symlink.
```
```
- run: |
              echo "nameserver 8.8.8.8" |  sudo tee  /etc/resolv.conf.DNSoverride
              sudo ln -sf /etc/resolv.conf.DNSoverride /etc/resolv.conf
              cat /etc/resolv.conf 
```
