### ISSUE TITLE
VCPKG will stop working

### ISSUE THREAD

**Issue by snnn** [actions/virtual-environments#3742]
### Description

If you build a Windows image from the latest code, vcpkg in the image will not work.

See: https://github.com/microsoft/vcpkg/issues/18952

Basically,  you need them add this change https://github.com/snnn/vcpkg/commit/406b984248fe32f04faa4129e93b0078ce29e00f to vcpkg. 

Otherwise it will just crash. 

### Virtual environments affected

- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [X] Windows Server 2019

### Image version and build link

I build it from the latest source. 

### Is it regression?

Yes. Before cmake 3.21 was released, it was fine. So currently the latest version win19/20210711 works fine. But once you generate and publish the new one, it will stop working.

### Expected behavior

Can use vcpkg.

### Actual behavior

vcpkg.exe crashes. 

### Repro steps

In the image, run:
```
C:\vcpkg\vcpkg.exe install protobuf:x64-windows-static
```
Related PR: https://github.com/microsoft/vcpkg-tool/pull/107

**Comment by miketimofeev** [comment]
@snnn thanks for reporting this! I've built the image today and run
`C:\vcpkg\vcpkg.exe install protobuf:x64-windows-static` on it, everything seems fine so far:
```
Building package protobuf[core]:x64-windows-static... done
Installing package protobuf[core]:x64-windows-static...
Installing package protobuf[core]:x64-windows-static... done
Elapsed time for package protobuf:x64-windows-static: 7.599 min

Total elapsed time: 17.04 min

The package protobuf:x64-windows-static provides CMake targets:

    find_package(protobuf CONFIG REQUIRED)
    target_link_libraries(main PRIVATE protobuf::libprotoc protobuf::libprotobuf protobuf::libprotobuf-lite)
```
Does it mean that VCPKG will stop working a bit later?

**Comment by snnn** [comment]
Interesting. It crashed on my side. 

So, could you please help check which vcpkg version do you use? 


C:\vcpkg\vcpkg.exe is downloaded from https://github.com/microsoft/vcpkg-tool/releases/ . You can compare the things to figure out the version. The latest one 2021-07-16 works fine. And the release note clearly says it was released for fixing an crash issue when used with CMake 3.21.

**Comment by miketimofeev** [comment]
@snnn we don't use releases (at least yet) — we always build vcpkg from the main branch:
 https://github.com/actions/virtual-environments/blob/47c20dcaa31b0223f41b62624ecbdd4e5f7e94c5/images/win/scripts/Installers/Install-Vcpkg.ps1#L6-L10
Looks like the current main is in the same state as 07-16 release
![image](https://user-images.githubusercontent.com/48208649/126201909-72f5ae11-c223-4f45-84d0-491c4a27be07.png)

**Comment by snnn** [comment]
There are two repos: vcpkg and vcpkg-tools. You use vcpkg from master, but vcpkg references vcpkg-tools by release tags.

**Comment by Be-ing** [comment]
The root cause has been [fixed in CMake](https://gitlab.kitware.com/cmake/cmake/-/issues/22444) and is included in CMake 3.21.1. Could you update CMake to 3.21.1?

**Comment by miketimofeev** [comment]
@Be-ing the new image with Cmake 3.21.1 will be available later this week, ETA is Wednesday-Thursday

**Comment by Be-ing** [comment]
Great, thank you for taking care of this quickly.
