### ISSUE TITLE
[all OS] MongoDB will be updated to version 5 on July, 26th

### ISSUE THREAD

**Issue by AlenaSviridenko** [actions/virtual-environments#3749]
### Breaking changes

MongoDB will be updated to version 5 on July, 26th for all images.

### Target date

Deployment will start on July, 26th and will take 3-4 days.

### The motivation for the changes

We provide the latest software updates, and we always install the latest MongoDB versionon our images. This week we stuck to MongoDB 4.4.7 in order to give a heads-up about the upcoming update.

### Possible impact

If your project is incompatible with MongoDB 5 - it will be broken. See this page for compatibility changes of new version https://docs.mongodb.com/manual/release-notes/5.0-compatibility/

### Virtual environments affected

- [ ] Ubuntu 16.04
- [X] Ubuntu 18.04
- [X] Ubuntu 20.04
- [X] macOS 10.15
- [X] macOS 11
- [X] Windows Server 2016
- [X] Windows Server 2019

### Mitigation ways

Use the following snippets to downgrade MongoDB in runtime:
1. Windows
```
choco uninstall mongodb
choco install mongodb -y --version=4.4.7 --no-progress
```
2. Ubuntu
```
sudo apt-get remove mongodb-org
wget -qO - https://www.mongodb.org/static/pgp/server-4.4.asc | sudo apt-key add -
REPO_URL="https://repo.mongodb.org/apt/ubuntu"
version=$(lsb_release -cs)
echo "deb [ arch=amd64,arm64 ] $REPO_URL $version/mongodb-org/4.4 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-4.4.list
sudo apt-get update
sudo apt-get install -y mongodb-org
```
3. macOS
```
brew tap mongodb/brew
brew uninstall mongodb-community
brew install mongodb-community@4.4
ln -sf $(brew --prefix mongodb-community@4.4)/bin/* /usr/local/bin/
```

**Comment by Kevinprince1976** [comment]
> ### Breaking changes
> MongoDB will be updated to version 5 on July, 26th for all images.
> 
> ### Target date
> Deployment will start on July, 26th and will take 3-4 days.
> 
> ### The motivation for the changes
> We provide the latest software updates, and we always install the latest MongoDB versionon our images. This week we stuck to MongoDB 4.4.7 in order to give a heads-up about the upcoming update.
> 
> ### Possible impact
> If your project is incompatible with MongoDB 5 - it will be broken. See this page for compatibility changes of new version https://docs.mongodb.com/manual/release-notes/5.0-compatibility/
> 
> ### Virtual environments affected
> * [ ]  Ubuntu 16.04
> * [x]  Ubuntu 18.04
> * [x]  Ubuntu 20.04
> * [x]  macOS 10.15
> * [x]  macOS 11
> * [x]  Windows Server 2016
> * [x]  Windows Server 2019
> 
> ### Mitigation ways
> Use the following snippets to downgrade MongoDB in runtime:
> 
> 1. Windows
> 
> ```
> choco uninstall mongodb
> choco install mongodb -y --version=4.4.7 --no-progress
> ```
> 
>  1. Ubuntu
> 
> ```
> sudo apt-get remove mongodb-org
> wget -qO - https://www.mongodb.org/static/pgp/server-4.4.asc | sudo apt-key add -
> REPO_URL="https://repo.mongodb.org/apt/ubuntu"
> version=$(lsb_release -cs)
> echo "deb [ arch=amd64,arm64 ] $REPO_URL $version/mongodb-org/4.4 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-4.4.list
> sudo apt-get update
> sudo apt-get install -y mongodb-org
> ```
> 
>  1. macOS
> 
> ```
> brew tap mongodb/brew
> brew uninstall mongodb-community
> brew install mongodb-community@4.4
> ln -sf $(brew --prefix mongodb-community@4.4)/bin/* /usr/local/bin/
> ```

**Comment by Sercandem** [comment]
> ### Breaking changes
> MongoDB will be updated to version 5 on July, 26th for all images.
> 
> ### Target date
> Deployment will start on July, 26th and will take 3-4 days.
> 
> ### The motivation for the changes
> We provide the latest software updates, and we always install the latest MongoDB versionon our images. This week we stuck to MongoDB 4.4.7 in order to give a heads-up about the upcoming update.
> 
> ### Possible impact
> If your project is incompatible with MongoDB 5 - it will be broken. See this page for compatibility changes of new version https://docs.mongodb.com/manual/release-notes/5.0-compatibility/
> 
> ### Virtual environments affected
> * [ ]  Ubuntu 16.04
> * [x]  Ubuntu 18.04
> * [x]  Ubuntu 20.04
> * [x]  macOS 10.15
> * [x]  macOS 11
> * [x]  Windows Server 2016
> * [x]  Windows Server 2019
> 
> ### Mitigation ways
> Use the following snippets to downgrade MongoDB in runtime:
> 
> 1. Windows
> 
> ```
> choco uninstall mongodb
> choco install mongodb -y --version=4.4.7 --no-progress
> ```
> 
> 1. Ubuntu
> 
> ```
> sudo apt-get remove mongodb-org
> wget -qO - https://www.mongodb.org/static/pgp/server-4.4.asc | sudo apt-key add -
> REPO_URL="https://repo.mongodb.org/apt/ubuntu"
> version=$(lsb_release -cs)
> echo "deb [ arch=amd64,arm64 ] $REPO_URL $version/mongodb-org/4.4 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-4.4.list
> sudo apt-get update
> sudo apt-get install -y mongodb-org
> ```
> 
> 1. macOS
> 
> ```
> brew tap mongodb/brew
> brew uninstall mongodb-community
> brew install mongodb-community@4.4
> ln -sf $(brew --prefix mongodb-community@4.4)/bin/* /usr/local/bin/
> ```

**Comment by al-cheb** [comment]
All images with MongoDB 5.0 on board have been deployed.

**Comment by luislobo** [comment]
Is there a way to downgrade to mongodb 4.4?
I need to run tests on different mongodb versions

**Comment by ilia-shipitsin** [comment]
@luislobo , may containers work for you ?

```
  mongo:
    runs-on: ubuntu-latest
    container:
      image: mongo:${{ matrix.mongodb_version }}
    strategy:
      matrix:
        mongodb_version: ["4.2", "4.4"]
        
    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: mongod -version
```

**Comment by luislobo** [comment]
The issue is with a windows based test. The linux ones work just fine (and I'm using containers).

Windows don't have containers unfortunately. I'm playing around now with installing a separate mongod in another port, even though the pre-installed mongodb service on windows is disabled, just to have more control.

Have it working half way but for some reason now it fails on Mongo 6, but that could be a problem of my code... Will need to check.

(for reference: https://github.com/luislobo/sails-mongo/blob/update-eslint-and-code-based-on-changes/.github/workflows/ci.yaml All the code for windows is commented out. It does work for 4.4 and 5.0)
