### ISSUE TITLE
Announce/Feedback: MySQL will become shut down by default on Ubuntu images on 03/12/2020

### ISSUE THREAD

**Issue by AlenaSviridenko** [actions/virtual-environments#375]
Hi!

We are going to make MySQL service shut down by default on Ubuntu images on 03/12/2020.

If you have any concerns or questions please let use know through this issue.

Thanks!

**Comment by Croydon** [comment]
Generally speaking, please create something like a news feed for these kind of breaking and/or major changes to images

It is unrealistic that people can watch all issues for important changes 😄

**Comment by AlenaSviridenko** [comment]
Hi @Croydon !
unfortunately GitHub doesn't allow to pin more then 3 issues, so we were waiting for ability to remove the announcement about Xcode so we could pin this one instead.
 Thanks!

**Comment by thejoebourneidentity** [comment]
Hey @Croydon, please make sure you subscribe to the GitHub changelog which is where we usually post news about changes like this. This post should go out today sometime. https://github.blog/changelog/

**Comment by ivailop** [comment]
I suppose, there will be appropriate documentation explaining how to start it, when needed?

Would it be expected to run MySQL as a [separate `job-service`](https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idservices)? If that is the case why do you need to provide MySQL server in the hosted Ubuntu images?

Meanwhile, for those still using Azure Pipelines, as same Ubuntu images are being used, it would be nice to expand the [documentation](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/phases?view=azure-devops&tabs=yaml) on how to do same.

**Comment by thejoebourneidentity** [comment]
So for GitHub Actions, here is the change to make in order to make this work. https://github.blog/changelog/2020-02-21-github-actions-breaking-change-ubuntu-virtual-environments-will-no-longer-start-the-mysql-service-automatically/

The same should work for azure pipelines, you just need to run the shell command
 `sudo /etc/init.d/mysql start`

**Comment by hkdobrev** [comment]
I'm interested to understand why this is needed. Would that mean faster GitHub Actions runs for those who do not use MySQL in their workflow? Thanks!

**Comment by al-cheb** [comment]
Hello, @hkdobrev 
Request - [Ability to shutdown/disable system services on an image](https://github.com/actions/virtual-environments/issues/348)

**Comment by AlenaSviridenko** [comment]
PR for swithcing off MySQL was merged https://github.com/actions/virtual-environments/pull/498

Changes will become alive with the next image rollout.

**Comment by martinsbalodis** [comment]
Just curious. What was the reasoning behind this? Does this reduce CPU usage or make the runner faster? Or were you getting too many issues about not being able to use port 3306?

**Comment by al-cheb** [comment]
Hello, @martinsbalodis 
Request - [Ability to shutdown/disable system services on an image](https://github.com/actions/virtual-environments/issues/348)

**Comment by AlenaSviridenko** [comment]
Closing it since Ubuntu Image with this update is availble for all customers now.
