### ISSUE TITLE
Add [Microsoft Fakes]

### ISSUE THREAD

**Issue by agukasm** [actions/virtual-environments#3751]
### Tool name

Microsoft Fakes

### Tool license

Visual Studio Enterprise license

### Add or update?

- [X] Add
- [ ] Update

### Desired version

Visual Studio 2019 version 16.10, Fakes for .NET Core and SDK-Style projects

### Brief description of tool

Microsoft Fakes helps you isolate the code you are testing by replacing other parts of the application with stubs or shims. These are small pieces of code that are under the control of your tests. By isolating your code for testing, you know that if the test fails, the cause is there and not somewhere else. Stubs and shims also let you test your code even if other parts of your application are not working yet.
It is critical to mock static methods and properties for example DateTime.Now.

### URL for tool's homepage

https://docs.microsoft.com/en-us/visualstudio/test/isolating-code-under-test-with-microsoft-fakes?view=vs-2019

### Provide a basic test case to validate the tool's functionality.

```bash
[TestClass]
public class TestClass1
{
        [TestMethod]
        public void TestCurrentYear()
        {
            int fixedYear = 2000;

            // Shims can be used only in a ShimsContext:
            using (ShimsContext.Create())
            {
              // Arrange:
                // Shim DateTime.Now to return a fixed date:
                System.Fakes.ShimDateTime.NowGet =
                () =>
                { return new DateTime(fixedYear, 1, 1); };

                // Instantiate the component under test:
                var componentUnderTest = new MyComponent();

              // Act:
                int year = componentUnderTest.GetTheCurrentYear();

              // Assert:
                // This will always be true if the component is working:
                Assert.AreEqual(fixedYear, year);
            }
        }
}
```

### Virtual environments affected

- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [X] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [X] Windows Server 2019

**Comment by AlenaSviridenko** [comment]
Hi @agukasm, the page you are referring to states that `Microsoft Fakes assembly generation previewed in Visual Studio Enterprise 2019 Update 6 and is enabled by default in Update 8.`
https://docs.microsoft.com/en-us/visualstudio/test/isolating-code-under-test-with-microsoft-fakes?view=vs-2019#microsoft-fakes-in-sdk-style-net-framework-net-core-and-net-50-projects

So it should be already installed and available. Please, let me know if you have any questions.

**Comment by agukasm** [comment]
Thank You for the answer. I have tried to use MSBuild instead of dotnet, which seems to generate FakeAssemblies, but dotnet test fails with: https://github.com/web-eid/web-eid-authtoken-validation-dotnet/runs/3113949192?check_suite_focus=true#step:8:229
Not sure what should I put on COR_PROFILER_PATH and COR_PROFILER variables.

**Comment by AlenaSviridenko** [comment]
Unfortunately, we are not experts in configuring .NET projects for tests, I would suggest asking in https://developercommunity.visualstudio.com/home as it has a large community of experts and support engineers for .NET-related questions.

**Comment by AlenaSviridenko** [comment]
I am closing this issue as MS Fakes setup is out of our expertise scope. Please, feel free to contact us in case of any questions.
Thanks.
