### ISSUE TITLE
Add JDK 16

### ISSUE THREAD

**Issue by haileh** [actions/virtual-environments#3753]
### Tool name

Adopt OpenJDK 16.0.1+9

### Tool license

GPLv2+CE

### Add or update?

- [X] Add
- [ ] Update

### Desired version

16.0.1+9

### Virtual environments affected

- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [X] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019

**Comment by AlenaSviridenko** [comment]
Hi @haileh,
based on our [policy](https://github.com/actions/virtual-environments/blob/main/docs/software-and-images-guidelines.md#software-and-images-support-policy), we pre-install only LTS Java versions, so the next installed version will be Java 17. 
For other versions, please, use [setup-java](https://github.com/actions/setup-java) action, it supports installation of any Java version.

I am closing this issue. Please, let me know if you have any concerns.
Thanks.
