### ISSUE TITLE
Add nix package manager

### ISSUE THREAD

**Issue by adrian-gierakowski** [actions/virtual-environments#376]
**Tool information**
- Tool name: nix
- Add or update? Add
- Desired version: latest (currently 2.3.2)
- Approximate size: 
- If this is an add request:
  - Brief description of tool: The Purely Functional Package Manager
  - URL for tool's homepage: https://nixos.org/nix/

**Area for Triage**:
??

**Question, Bug, or Feature?**:
Feature

**Virtual environments affected**
- [ x ] macOS 10.15
- [ x ] Ubuntu 16.04 LTS
- [ x ] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Can this tool be installed during the build?**
Yes, there is an action which does it: https://github.com/cachix/install-nix-action
Install takes around:
15s on Linux
90s on MacOs

**Are you willing to submit a PR?**
Yes

**Comment by thejoebourneidentity** [comment]
Thanks for your suggestion 🙏. Considering how popular this tool is, and how easy it is to install during your run, it's not something we will add to the image at this time.
