### ISSUE TITLE
Update Xcode for iOS 15 compatibility

### ISSUE THREAD

**Issue by mobilesavvy** [actions/virtual-environments#3763]
### Tool name

X Code

### Tool license

implicit

### Add or update?

- [ ] Add
- [X] Update

### Desired version

XCode 13.0

### Brief description of tool

XCode 13 is required to support apps that needs to run on upcoming iOS 15.0 version.

### Virtual environments affected

- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [X] macOS 10.15
- [X] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019

**Comment by mobilesavvy** [comment]
Hi Team - would like to know when can we expect the supported XCode 13 to be available in the Mac OS hosted agent

**Comment by al-cheb** [comment]
Hey, @mobilesavvy 
The latest XCode 13.0(13A5192j) build  is already preinstalled on macOS 11(Big Sur) and not supported for macOS below 11.

**Comment by mobilesavvy** [comment]
Hi @al-cheb 
We use Miscrosoft hosted agents and I dont see the macOS 11 listed under available hosted agents here - https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops&tabs=yaml

Hope Im checking the right path.

Can you share the exact value to be set if you did already? My current one is below.
 pool:
      vmImage: 'macOS-10.15'

**Comment by al-cheb** [comment]
> Hi @al-cheb
> We use Miscrosoft hosted agents and I dont see the macOS 11 listed under available hosted agents here - https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops&tabs=yaml
> 
> Hope Im checking the right path.
> 
> Can you share the exact value to be set if you did already? My current one is below.
> pool:
> vmImage: 'macOS-10.15'

https://github.com/actions/virtual-environments/issues/2072#issuecomment-854812898

**Comment by Prince2k3** [comment]
I've been trying to get Xcode 13 (not beta) to work. The action keeps using beta and I have no idea how to not point to that version. Can anyone help with what step I need to use in order for it to use the correct Xcode version.

**Comment by miketimofeev** [comment]
@Prince2k3 have you tried the following?
`sudo xcode-select --switch /Applications/Xcode_13.0.app/Contents/Developer`

**Comment by Prince2k3** [comment]
@miketimofeev Thank you for your reply and help. Greatly appreciated! I ended up resolving the issue. I was running the wrong version of macOS. It was using v 11 instead of 12.
