### ISSUE TITLE
Add gvfs.exe

### ISSUE THREAD

**Issue by JohnFKennedy** [actions/virtual-environments#3764]
### Tool name

GVFS

### Tool license

none

### Add or update?

- [X] Add
- [ ] Update

### Desired version

Newest

### Brief description of tool

It's your own tool to allow VFS for git to work on Microsoft hosted agents

### URL for tool's homepage

https://github.com/Microsoft/VFSForGit/releases/tag/v1.0.21085.9

### Provide a basic test case to validate the tool's functionality.

```bash
- task: vfs-for-git@0
  inputs:
    command: 'clone'
    projectId: 
    gitRepositoryId: 
    enlistmentRootPath: '$(Build.SourcesDirectory)'
```

### Virtual environments affected

- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [X] Windows Server 2019

**Comment by al-cheb** [comment]
Hi, @JohnFKennedy 
You can install GVFS in rutime using powershell script:

```
jobs:
  build:
    runs-on: windows-latest
    steps:
         - name: Download GVFS
           run: |
                $r = Invoke-RestMethod https://api.github.com/repos/microsoft/VFSForGit/releases/latest
                $url = $r.assets.where{$_.Name -match "SetupGVFS.+.exe"}.browser_download_url
                Invoke-WebRequest $url -OutFile C:\SetupGVFS.exe
         - name: Install GVFS
           run: |
                $env:GVFS_UNATTENDED = "1"
                Start-Process C:\SetupGVFS.exe -ArgumentList "/VERYSILENT", "/NORESTART", "/NOCANCEL", "/SP-", "/CLOSEAPPLICATIONS", "/RESTARTAPPLICATIONS", "/LOG=gvfs.log", "/SUPPRESSMSGBOXES" -PassThru | Wait-Process
         - run: |
                & $env:ProgramFiles\GVFS\GVFS.exe version
```

![image](https://user-images.githubusercontent.com/47745270/126444211-0ace081a-10d5-4556-b161-d11d3d1d11c5.png)

**Comment by AlenaSviridenko** [comment]
PR was merged and will be available with the next image rollout. We will keep you posted.

**Comment by al-cheb** [comment]
Windows images with GVFS on board have been deployed.
