### ISSUE TITLE
PKIX path building failed after "ubuntu-latest" update

### ISSUE THREAD

**Issue by timotta** [actions/virtual-environments#3769]
### Description

Two days ago there was a release of ubuntu-18.04 and ubuntu-20.04 and exactly now this is rollouted to 95%.

My build was working before, but now is getting this error without any change on our side:

```
      > Could not resolve org.springframework.boot:spring-boot-gradle-plugin:2.0.0.M7.
         > Could not get resource 'https://repo.spring.io/snapshot/org/springframework/boot/spring-boot-gradle-plugin/2.0.0.M7/spring-boot-gradle-plugin-2.0.0.M7.pom'.
            > Could not GET 'https://repo.spring.io/snapshot/org/springframework/boot/spring-boot-gradle-plugin/2.0.0.M7/spring-boot-gradle-plugin-2.0.0.M7.pom'.
               > PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
```

Here is a part of my workflow:

```yaml
jobs:
  quality:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '8'

      - name: Run code quality
        run: ./gradlew -Dorg.gradle.daemon=false -s :clean :test
``` 

### Virtual environments affected

- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [X] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019

### Image version and build link

ubuntu-latest

### Repro steps

Run the workflow

**Comment by miketimofeev** [comment]
Hi @timotta!
This link returns 404 for some reason
https://repo.spring.io/snapshot/org/springframework/boot/spring-boot-gradle-plugin/2.0.0.M7/spring-boot-gradle-plugin-2.0.0.M7.pom
Do we need any authorization in place?

**Comment by timotta** [comment]
> Hi @timotta!
> This link returns 404 for some reason
> https://repo.spring.io/snapshot/org/springframework/boot/spring-boot-gradle-plugin/2.0.0.M7/spring-boot-gradle-plugin-2.0.0.M7.pom
> Do we need any authorization in place?

Maybe this is the problem, and the error about PKIX is misleading. Reviewing my yesterday build this download worked fine: 

```
Download https://repo.spring.io/milestone/org/springframework/boot/spring-boot-gradle-plugin/2.0.0.M7/spring-boot-gradle-plugin-2.0.0.M7.pom
``` 

I'm going to try another version and get back here
