### ISSUE TITLE
Pipelines broken

### ISSUE THREAD

**Issue by asehgalxom** [actions/virtual-environments#3770]
### Description

Getting following error:

`##[error]An error occurred while provisioning resources (Error Type: Failure).
,##[error]The remote provider was unable to process the request.`

I found a similar issue from earlier this year (https://github.com/actions/virtual-environments/issues/2575) and a lot of people are adding comments to that. Figured since that issue is closed no one is probably paying attention to it.

### Virtual environments affected

- [ ] Ubuntu 16.04
- [X] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019

### Image version and build link

Image: Ubuntu-18.04

### Repro steps

Queue a build and it fails immediately.

**Comment by vamshiivkinduri** [comment]
Also having the same issue right now.

**Comment by mcordovaf** [comment]
Same problem here.

**Comment by mataxetos** [comment]
Same problem:

##[error]An error occurred while provisioning resources (Error Type: Failure).
,##[error]The remote provider was unable to process the request.
Pool: Azure Pipelines
Image: ubuntu-latest

**Comment by shaunlavallee** [comment]
##[error]An error occurred while provisioning resources (Error Type: Failure).
,##[error]The remote provider was unable to process the request.
Pool: Azure Pipelines
Image: Ubuntu-latest

**Comment by e14olua** [comment]
Same issue here

##[error]An error occurred while provisioning resources (Error Type: Failure).
,##[error]The remote provider was unable to process the request.
Pool: Azure Pipelines
Image: ubuntu-latest

Job preparation parameters

**Comment by gfrankel97** [comment]
same here, not to worry though
![Screen Shot 2021-07-21 at 3 28 58 PM](https://user-images.githubusercontent.com/30882239/126548499-28e61352-38fd-4fa7-8ca7-26d53c43a3f2.png)

**Comment by gavinsteinhoff** [comment]
Same here
Pool: Azure Pipelines
Image: windows-latest

**Comment by LR4Discovery** [comment]
same issue in North Central  with build and release pipelines

**Comment by alelfreitas** [comment]
Same with image 'ubuntu-latest'

**Comment by ghwilley** [comment]
samesies
##[error]An error occurred while provisioning resources (Error Type: Failure).
,##[error]The remote provider was unable to process the request.
Pool: Azure Pipelines
Image: Ubuntu-latest

**Comment by jngibert** [comment]
Same issue

**Comment by VikingHobo** [comment]
Having the same issue

**Comment by jjcaraballo01** [comment]
Same here blocked on builds in Central US. Will miss deadlines for conversion of pipelines to YAML from another CI/CD system.

**Comment by warleyxavier** [comment]
Same problem here.

**Comment by gorziza** [comment]
Region East US
![Selection_006](https://user-images.githubusercontent.com/8699254/126548821-40c2ef39-12f5-43c2-984c-0696a7e7887b.png)

**Comment by jason-e-gross** [comment]
Same issue, Classic Releases or Pipeline YAML.    All jobs fail immediately with what everyone is reporting above, or for Classic Release:

**Status**
Not deployed

**Sub-status**
Deployment was canceled by Microsoft.VisualStudio.Services.ReleaseManagement

**Comment by poveilleux** [comment]
I guess we'd be better off all opening tickets with Microsoft directly

**Comment by kylelaverty** [comment]
I am having the same issue, 
![image](https://user-images.githubusercontent.com/12103001/126548964-b4e3cddf-d08d-4882-bbba-d104628ec92c.png)
Tech support says to go to the status page to report an issue but that page has nowhere to notify from.

**Comment by jeev20** [comment]
Down at Norway-West region. 

```
##[error]An error occurred while provisioning resources (Error Type: Failure).
,##[error]The remote provider was unable to process the request.
Pool: Azure Pipelines
Image: ubuntu-20.04
```

**Comment by maacaro** [comment]
same here

**Comment by ghwilley** [comment]
I've reported the issue through here: [https://developercommunity.visualstudio.com/report?space=21&entry=problem](https://developercommunity.visualstudio.com/report?space=21&entry=problem)

**Comment by Aaronmyster** [comment]
same here. lots of people.
![image](https://user-images.githubusercontent.com/2602543/126549689-7ba2272b-3b26-460a-917a-b8d6b2686671.png)

**Comment by alelfreitas** [comment]
We can report a bug on devops at this site: https://azure.microsoft.com/en-us/support/devops/

**Comment by alelfreitas** [comment]
> same here. lots of people.
> ![image](https://user-images.githubusercontent.com/2602543/126549689-7ba2272b-3b26-460a-917a-b8d6b2686671.png)

Yes! that one!

**Comment by derekrprice** [comment]
@alelfreitas can you please link that report so that i can vote it up?

**Comment by guilhermepozo** [comment]
Here too:
![image](https://user-images.githubusercontent.com/18023489/126550151-0fbbfd19-1f61-4a1e-adea-b895aed4e0bb.png)

**Comment by aristosvo** [comment]
Vote on one, i.e. https://developercommunity.visualstudio.com/t/errorAn-error-occurred-while-provisi/1481083

**Comment by jngibert** [comment]
Azure DevOps status page finally showing an alert on the outage...

**Comment by MattJeanes** [comment]
https://status.dev.azure.com/_event/251790226

![image](https://user-images.githubusercontent.com/2363642/126551118-0915c95c-76a1-418d-b450-8fb8e961de0c.png)

**Comment by MattJeanes** [comment]
An additional event has been raised in Azure DevOps status:

https://status.dev.azure.com/_event/251788647

![image](https://user-images.githubusercontent.com/2363642/126551922-c6ed0706-b550-4242-94d5-ba1a0e76a8f7.png)

**Comment by MattJeanes** [comment]
Update, some people are reporting successful pipeline runs now as well:

![image](https://user-images.githubusercontent.com/2363642/126555786-26226aa2-8143-4c4d-b12e-ff40c09f70b1.png)

**Comment by MattJeanes** [comment]
Final update, issue is now resolved according to Microsoft

![image](https://user-images.githubusercontent.com/2363642/126557042-6bb970ee-6115-4027-9c6e-bdb7d312d5a7.png)

**Comment by asehgalxom** [comment]
Underlying problem has been fixed so I am closing this issue.

**Comment by pakistanzinda8048048292-cyber** [comment]
1481083 free fire diamond
