### ISSUE TITLE
Memory Regression in Latest Ubuntu

### ISSUE THREAD

**Issue by ArquintL** [actions/virtual-environments#3773]
### Description

We are using `ubuntu-latest` to run a docker container. In the container, we use `sbt` to build and test our Scala project.
Starting ~2 days ago, our tests stop with an `EOFException` and exit code 137 hinting at not sufficient heap memory.
The docker container has not changed and rerunning workflows that succeeded 3-4 days ago now fail with the same error.
We suspect that this memory issue is caused by a regression in the virtual environment `20210718.1` for `ubuntu-20.04`. One of the last successful runs was using virtual environment `20210712.0`.

First of all, is there a way to explicitly set the virtual environment such that I can test that the issues are indeed caused by the virtual environment?

Are there any memory related settings that have changed?

### Virtual environments affected

- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [X] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019

### Image version and build link

`20210718.1`
[Failing run](https://github.com/viperproject/gobra/runs/3131328549)

### Is it regression?

yes, `20210712.0` [successful run](https://github.com/viperproject/gobra/runs/3104361513)

### Expected behavior

`sbt test` runs to completion without memory issue an exception

### Actual behavior

`sbt test` fails because of not enough memory

### Repro steps

Rerun the failing run above

**Comment by al-cheb** [comment]
Hi, @ArquintL 
Could you please check recommendations from the https://www.programmersought.com/article/47811098599/ article ?
`-Xms2048m -Xmx2048m -Xmn512m`

**Comment by ArquintL** [comment]
@al-cheb Thanks a lot for the recommendation. I've tried it several combinations of specifying these parameters. The error looks now slightly differently but the tests are still killed with error 137 as can be seen for example [here](https://github.com/viperproject/gobra/runs/3133367384). Is there anything that has changed in the environment?

**Comment by al-cheb** [comment]
@ArquintL, Could you please try to rerun failed build, because we have rolled back a recent configuration change- https://github.com/actions/virtual-environments/issues/3805#issuecomment-887884901?

**Comment by dsame** [comment]
@ArquintL  the tests start to pass https://github.com/akv-platform/gobra/runs/3186048348?check_suite_focus=true

**Comment by ArquintL** [comment]
@al-cheb @dsame thanks a lot for your help! The tests indeed start to work again.
In the meantime, I've added logging of the RAM consumption of Java to our CI and the results are impressive:

## Before the rollback
- executing tests with `sbt test`: 5.7GB and exit code 137 [run](https://github.com/viperproject/gobra/runs/3181827928)
- executing tests directly with `java`: 3.6GB [run](https://github.com/viperproject/gobra/runs/3182822991)

## After the rollback
- executing tests with `sbt test`: 2.4GB [run](https://github.com/viperproject/gobra/runs/3188896379)
- executing tests directly with `java`: 2.39GB [run](https://github.com/viperproject/gobra/runs/3188907769)

One question though: Is it possible that the problematic virtual environment and the rolled back one both have version `20210718.1`?

**Comment by al-cheb** [comment]
@ArquintL, Yep, it should be the same version.

https://github.com/viperproject/gobra/runs/3181827928 - Ok
![image](https://user-images.githubusercontent.com/47745270/127444692-10f23ee3-47b1-4cb3-a6b3-dae95ae610be.png)

https://github.com/viperproject/gobra/runs/3182822991 - Failed
![image](https://user-images.githubusercontent.com/47745270/127444740-73460158-c600-4c0c-98e9-070a9d6c776f.png)

**Comment by ArquintL** [comment]
@al-cheb I've seen that but was just wondering how I can differentiate before rollback vs after rollback

**Comment by al-cheb** [comment]
> @al-cheb I've seen that but was just wondering how I can differentiate before rollback vs after rollback

In that particular case we reverted internal changes. I don't think it's easy to differentiate it.

**Comment by dmitry-shibanov** [comment]
Hello @ArquintL. As @al-cheb mentioned, it was our internal issues and they were reverted. I'm closing the issue, because you should not experience this issue anymore.
