### ISSUE TITLE
IP Addresses for macOS cloud for whitelisting

### ISSUE THREAD

**Issue by seemantk-schweitzer** [actions/virtual-environments#3796]
Hello Github Actions team,

Wondering if there's a way to find the public IP addresses of the github-hosted MacOS runners?

The only conversation I've been able to locate about it is here: https://github.community/t/ip-ranges-for-macos-github-actions-runners/17349/2

And the GET /meta information doesn't seem to specify it.

Thank you
Seemant

**Comment by maxim-lobanov** [comment]
Hello @seemantk-schweitzer , there is an API endpoint to retrieve the list of IP Addresses. Looks like they are not split to platforms but it should work.
See the following page for details:
https://docs.github.com/en/github/authenticating-to-github/keeping-your-account-and-data-secure/about-githubs-ip-addresses

**Comment by seemantk-schweitzer** [comment]
Thank you @maxim-lobanov.  As stated in the original comment, there is no breakout about the list for macOS, as most of the runners are on Azure cloud, and we are trying to get a smaller list of IPs to whitelist....

**Comment by Darleev** [comment]
Hello @seemantk-schweitzer,
Please check [the following issue](https://github.com/actions/virtual-environments/issues/3354#issuecomment-837185684) to obtain a list of IP addresses for macOS GitHub runner pools:

We're looking forward to your reply,.

**Comment by seemantk-schweitzer** [comment]
@Darleev thank you so much!!

Is this list likely to remain fairly stable for the foreseeable future?

**Comment by Darleev** [comment]
@seemantk-schweitzer according to the documentation provided by @maxim-lobanov:
`We make changes to our IP addresses from time to time. We do not recommend allowing by IP address, however if you use these IP ranges we strongly encourage regular monitoring of our API.`
So, probably in the future addresses can be changed.

**Comment by Darleev** [comment]
@seemantk-schweitzer I'm going to close the issue.
In case of any questions feel free to reopen it.
