### ISSUE TITLE
ubuntu-latest reports spurious SSL errors when checking links

### ISSUE THREAD

**Issue by weaverba137** [actions/virtual-environments#3797]
### Description

I have an action that tests the validity of http(s) links in a documentation set.  On `ubuntu-latest`, I see errors like this:

```
(       pydlutils: line    3) broken    https://space.mit.edu/~molly/mangle/ - HTTPSConnectionPool(host='space.mit.edu', port=443): Max retries exceeded with url: /~molly/mangle/ (Caused by SSLError(SSLError(1, '[SSL: DH_KEY_TOO_SMALL] dh key too small (_ssl.c:1131)')))
468
(           index: line   18) broken    https://www.sdss.org/surveys/eboss/ - HTTPSConnectionPool(host='www.sdss.org', port=443): Max retries exceeded with url: /surveys/eboss/ (Caused by SSLError(SSLError(1, '[SSL: WRONG_SIGNATURE_TYPE] wrong signature type (_ssl.c:1131)')))
484
```

When I visit these links in a browser, or run the same test in `ubuntu-18.04` or `macos-latest`, I do not see these errors.  I have links to some full examples below.

### Virtual environments affected

- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [X] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019

### Image version and build link

Example failed job: https://github.com/weaverba137/pydl/actions/runs/1044165073
```
  Environment: ubuntu-20.04
  Version: 20210718.1
  Included Software: https://github.com/actions/virtual-environments/blob/ubuntu20/20210718.1/images/linux/Ubuntu2004-README.md
  Image Release: https://github.com/actions/virtual-environments/releases/tag/ubuntu20%2F20210718.1
```

### Expected behavior

Here is an example test that runs successfully in `ubuntu-18.04`: https://github.com/weaverba137/pydl/runs/3158626789

### Actual behavior

Here is a failed test. All the links are in fact valid, but the SSL errors make them appear broken: https://github.com/weaverba137/pydl/actions/runs/1044165073

### Repro steps

It would be easiest to just copy [the action workflow](https://github.com/weaverba137/pydl/blob/main/.github/workflows/ci_cron_weekly.yml).  Simply replace `ubuntu-18.04` with `ubuntu-latest` to reproduce the error.

**Comment by al-cheb** [comment]
Hello, @weaverba137 
This behavior is by design for Ubuntu 20.04 - https://bugs.launchpad.net/ubuntu/+source/openssl/+bug/1864689, because the default level is `CipherString = DEFAULT@SECLEVEL=2` now.

```
On Ubuntu 20.04 LTS:

man SSL_CTX_get_security_level.3ssl

--
Level 2
On Ubuntu, TLS versions below 1.2 are not permitted.

NOTES
The default security level can be configured when OpenSSL is compiled by setting -DOPENSSL_TLS_SECURITY_LEVEL=level. On Ubuntu, 2 is used.
```

Both sites support many weak TLSv1.2 ciphersuites:

1. https://www.ssllabs.com/ssltest/analyze.html?d=space.mit.edu
2. https://www.ssllabs.com/ssltest/analyze.html?d=www.sdss.org

You can easily reproduce this behavior on Ubuntu 20.04:
```
 alex$ curl -v https://space.mit.edu
*   Trying 18.25.64.10:443...
* TCP_NODELAY set
* Connected to space.mit.edu (18.25.64.10) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (OUT), TLS alert, handshake failure (552):
* error:141A318A:SSL routines:tls_process_ske_dhe:dh key too small
* Closing connection 0
curl: (35) error:141A318A:SSL routines:tls_process_ske_dhe:dh key too small
```
```
alex$ curl -v https://www.sdss.org
*   Trying 128.220.233.141:443...
* TCP_NODELAY set
* Connected to www.sdss.org (128.220.233.141) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (OUT), TLS alert, handshake failure (552):
* error:1414D172:SSL routines:tls12_check_peer_sigalg:wrong signature type
* Closing connection 0
curl: (35) error:1414D172:SSL routines:tls12_check_peer_sigalg:wrong signature type
```

And works if you decrease `DEFAULT:@SECLEVEL=2` to `DEFAULT:@SECLEVEL=1 `:
`curl -v --ciphers 'DEFAULT:@SECLEVEL=1' https://space.mit.edu`

**Comment by weaverba137** [comment]
OK, good to know.  In the meantime I can at least continue to run tests on 18.04.  I have sent a note to the sdss.org maintainers, who I happen to know.
