### ISSUE TITLE
Update Visual Studio 2019 to version 16.10.4 to include .NET 5 SDK

### ISSUE THREAD

**Issue by osobeso** [actions/virtual-environments#3798]
### Tool name

Visual Studio 2019

### Tool license

Enterprise

### Add or update?

- [ ] Add
- [X] Update

### Desired version

16.10.4

### URL for tool's homepage

https://visualstudio.microsoft.com

### Provide a basic test case to validate the tool's functionality.

```bash
Our Visual Studio IntelliCode Team Completions github action requires for Visual Studio to build a solution and extract patterns from the solution.

You can find our action's docs here:
https://github.com/microsoft/vs-intellicode

When trying to run this action against a .NET 5 project, it fails because the Visual Studio that's currently installed is 16.10.31424.327 and the .NET 5 docs (https://dotnet.microsoft.com/download/dotnet/5.0) stipulates that the SDK was not included until version 16.10.4

Here's a repository that uses .NET 5 SDK, for which the extension is currently failing: https://github.com/osobeso/dotnet-web-api-boilerplate
```

### Virtual environments affected

- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [X] Windows Server 2019

### Are you willing to submit a PR?

Yes

**Comment by Darleev** [comment]
Hello @osobeso,
We will check the possibility to update Visual Studio to version 16.10.4. I'll keep you informed.

**Comment by Darleev** [comment]
@osobeso Visual Studio 16.10.4 will be delivered by the end of this week. 
I'll let you know.

**Comment by Darleev** [comment]
@osobeso Visual Studio has been updated to the aforementioned version.
Let me know in case of any questions.

**Comment by osobeso** [comment]
Thanks @Darleev 
When running the action I still see the same Visual Studio version:
CSharp: Using Visual Studio instance: Visual Studio Enterprise 2019 (16.10.31515.178)

But I'm guessing it might take some time for the changes to take effect probably.
I'll keep you posted.

Oscar.

**Comment by MaksimZhukov** [comment]
Hello @osobeso! `16.10.31515.178` is a build version of the Visual Studio 16.10.4. For more information, please see the [Visual Studio build numbers and release dates](https://docs.microsoft.com/en-us/visualstudio/install/visual-studio-build-numbers-and-release-dates?view=vs-2019) doc. Thanks!

**Comment by osobeso** [comment]
@MaksimZhukov Thanks! I can see it now.
Then I guess the problem is still half resolved from my end. I still need to figure out what might be causing the building problems on the github action. Good news is that we should now have the binaries we need alvailable on the windows agent.
Thanks again for the quick response!
