### ISSUE TITLE
Device or resource busy when building images using buildkit

### ISSUE THREAD

**Issue by marcosnils** [actions/virtual-environments#38]
**Describe the bug**
Getting the following error when building docker images using `DOCEKR_BUILDKIT: 1` env variable. This is the error we're getting:
```
error creating overlay mount to /var/lib/docker/overlay2/g4qhyt5fquj0qo1a3jeywbyo8/merged: device or resource busy
```

Seems to be related to this `moby` issue which was fixed in the last version of docker released a week ago: https://github.com/docker/for-linux/issues/711

**Virtual environments affected**
- [ ] macOS 10.14
- [ ] Ubuntu 16.04 LTS
- [x] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Expected behavior**
Image to be built without errors.

**Actual behavior**
Build any docker image using multi-stage builds and buildkit.

**Comment by ethomson** [comment]
We're investigating this now.

**Comment by ethomson** [comment]
We're rolling out the fix for this now.  Most of the machines in the pool should now be updated.

**Comment by marcosnils** [comment]
Thx @ethomson we'll re enable this tomorrow just to make sure it works. I'll keep this issue updated

**Comment by alepauly** [comment]
@marcosnils can you confirmed this issue is resolved? thanks.

**Comment by marcosnils** [comment]
It is
