### ISSUE TITLE
apt-get install of QT5 started failing fetching libudev

### ISSUE THREAD

**Issue by ColinPitrat** [actions/virtual-environments#3802]
### Description

For the past 5 days our nightly has been failing on:

`sudo apt-get install qt5-default qt5-qmake qtdeclarative5-dev`

with:

```
Get:98 http://azure.archive.ubuntu.com/ubuntu focal/multiverse amd64 vice amd64 3.4.0.dfsg-1build1 [5038 kB]
Fetched 38.8 MB in 1s (48.3 MB/s)
E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/main/s/systemd/libudev-dev_245.4-4ubuntu3.7_amd64.deb  404  Not Found [IP: 52.250.76.244 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
```

Example of such a failed build: https://github.com/leuat/TRSE/actions/runs/1069183074

### Virtual environments affected

- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [X] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019

### Image version and build link

Virtual Environment
  Environment: ubuntu-20.04
  Version: 20210718.1
  Included Software: https://github.com/actions/virtual-environments/blob/ubuntu20/20210718.1/images/linux/Ubuntu2004-README.md
  Image Release: https://github.com/actions/virtual-environments/releases/tag/ubuntu20%2F20210718.1

### Is it regression?

yes

### Expected behavior

Finish install without error

### Actual behavior

Fail to fetch packet

### Repro steps

sudo apt-get install qt5-default qt5-qmake qtdeclarative5-dev

**Comment by catthehacker** [comment]
You need to run `apt-get update` before `apt-get install`

**Comment by maxim-lobanov** [comment]
Hello @ColinPitrat , please make sure that you have run `sudo apt-get update` command before installation

**Comment by ColinPitrat** [comment]
Ah sorry, I was sure we had this already but actually no.

Sorry for the noise!
