### ISSUE TITLE
Update Google Chrome up to the latest version 92.0.4515.107

### ISSUE THREAD

**Issue by Nebyt** [actions/virtual-environments#3803]
### Tool name

Google Chrome

### Tool license

Proprietary freeware, based on open source components.

### Add or update?

- [ ] Add
- [X] Update

### Desired version

92.0.4515.107

### Virtual environments affected

- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [X] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019

**Comment by Darleev** [comment]
Hello @Nebyt,
According to the [Ubuntu pull request ](https://github.com/actions/virtual-environments/pull/3793)for the current week, Chrome will be updated by the end of this week. I'll keep you informed.

**Comment by Nebyt** [comment]
@Darleev Thank you!

**Comment by abek101** [comment]
@Darleev other OS'es needs this upgrade as well, should I create new task?

**Comment by Darleev** [comment]
@abek101 other OS'es will be upgraded as well by the end of this week. you can check the result for Ubuntu/macOS at this time. Windows will be delivered a little bit later.

**Comment by Darleev** [comment]
@abek101 I'm going to close this issue, since Google Chrome was updated.
Let me know in case of any questions.
