### ISSUE TITLE
Ubuntu 20.04: Qt5 started to look for libQt5XcbQpaAndroidEmu.so.5

### ISSUE THREAD

**Issue by ColinPitrat** [actions/virtual-environments#3804]
### Description

we have a nightly build running on GitHub Actions where we build an AppImage.
It used to work fine with the following virtual environment:

```
2021-07-14T22:45:31.0399113Z Environment: ubuntu-20.04
2021-07-14T22:45:31.0399682Z Version: 20210628.1
```

But it started failing with the following error:

```
ERROR getDeps: did not find library libQt5XcbQpaAndroidEmu.so.5
```

in the latest run that uses the following virtual environment:

```
  Environment: ubuntu-20.04
  Version: 20210712.0
```

I’m pretty sure this is related to this change because there was no change in the code on our side and no change in appimage tool code either.

I suspect this comes from an update in Ubuntu Qt packages that makes something depend on this library, but I’m not sure which package exactly and I’m not sure how to investigate it more.

The workflow in question:
https://github.com/leuat/TRSE/actions/workflows/linux.yml

In particular run that succeeded: https://github.com/leuat/TRSE/actions/runs/1031965107
and run that failed: https://github.com/leuat/TRSE/actions/runs/1047965011

### Virtual environments affected

- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [X] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019

### Image version and build link

  Environment: ubuntu-20.04
  Version: 20210712.0

### Is it regression?

yes

### Expected behavior

No failure of appimage-tool

### Actual behavior

Fail with  libQt5XcbQpaAndroidEmu.so.5 not found

### Repro steps

It's relatively complex to reproduce and I can't run on an old environment to check my assumptions, but I think a ldd on Qt libraries should allow to verify whether they depend on this library or not.

**Comment by Darleev** [comment]
Hello @ColinPitrat,
We will investigate the issue.

**Comment by mikhailshaganov** [comment]
Hello @ColinPitrat ,

**Comment by mikhailshaganov** [comment]
Hello @ColinPitrat ,
After investigation we have found that libQt5XcbQpaAndroidEmu.so.5 are located in a directory: /usr/local/lib/android/sdk/emulator/lib64/qt/lib. 

Decision.
u should add this part of the code in Build AppImage step:
```
      - name: Build AppImage
        run: |
          export ANDROID_HOME=/usr/local/lib/android/sdk
          export LD_LIBRARY_PATH=${ANDROID_HOME}/emulator/lib64/qt/lib:${LD_LIBRARY_PATH}
```

But after resolving this error we have got a new one:
```
ERROR patchelf --print-rpath /usr/local/lib/android/sdk/emulator/lib64/qt/plugins/xcbglintegrations/: patchelf: getting info about '/usr/local/lib/android/sdk/emulator/lib64/qt/plugins/xcbglintegrations/': No such file or directory
/usr/bin/patchelf --print-rpath /usr/local/lib/android/sdk/emulator/lib64/qt/plugins/xcbglintegrations/
: exit status 1
2021/08/04 13:56:46 Perhaps it is not dynamically linked, or perhaps it is a script. Continuing...
ERROR getDeps: binary does not exist: /usr/local/lib/android/sdk/emulator/lib64/qt/plugins/xcbglintegrations/
Error: Process completed with exit code 1.
```

Do you have any suggestions?

**Comment by mikhailshaganov** [comment]
Hey, we are waiting for a response from u. If u have suggestions we will be glad to help u.

**Comment by mikhailshaganov** [comment]
Hey, we have fixed an initial problem. Do u need any help from us with resolving the second one or we can close a ticket?

**Comment by mikhailshaganov** [comment]
Hey @ColinPitrat! 
We have fixed an initial problem. Do u need any help from us with resolving the second one or we can close a ticket?

**Comment by mikhailshaganov** [comment]
Hello @ColinPitrat!
I'm closing the issue, but do not hesitate to contact us if you have any questions.
Thanks!
