### ISSUE TITLE
Builds are failing at Ubuntu-latest based Microsoft hosted pool agents 

### ISSUE THREAD

**Issue by arroyc** [actions/virtual-environments#3807]
### Description

I have a privately hosted pool (OryxLinux) and I'm trying to move to Microsoft hosted pool where image is ubuntu-latest.As part of the test I create docker container with port mapping and then access those access those container ports from test (simple get http call) to see if they are working. I'm getting following error message and tests are failing left and right.

Did not get the port mapping in expected format.

> 
>    at Microsoft.Oryx.Tests.Common.EndToEndTestHelper.RunAndAssertAppAsync(String imageName, ITestOutputHelper output, IEnumerable`1 volumes, List`1 environmentVariables, Int32 port, String link, String runCmd, String[] runArgs, Func`2 assertAction, DockerCli dockerCli) in /home/vsts/work/1/s/tests/Oryx.Tests.Common/EndToEndTestHelper.cs:line 228
>    at Microsoft.Oryx.Tests.Common.EndToEndTestHelper.BuildRunAndAssertAppAsync(ITestOutputHelper output, IEnumerable`1 volumes, String buildImage, String buildCmd, String[] buildArgs, String runtimeImageName, List`1 environmentVariables, Int32 port, String link, String runCmd, String[] runArgs, Func`2 assertAction) in /home/vsts/work/1/s/tests/Oryx.Tests.Common/EndToEndTestHelper.cs:line 182
>    at Microsoft.Oryx.Integration.Tests.DotNetCoreRuntimeVersion21Tests.CanBuildAndRunApp_WhenRecursiveLookUpIsDisabled_ButProjectSettingIsSupplied() in /home/vsts/work/1/s/tests/Oryx.Integration.Tests/DotNetCore/DotNetCoreRuntimeVersion21Tests.cs:line 683
> --- End of stack trace from previous location where exception was thrown ---
>   Standard Output Messages:
>  
>  Debugging Information:
>  ----------------------
>  StdOut: Found build manifest file at '/oryxtests/a0ec176690a54017897a4006e2bfd16d/oryx-manifest.toml'. Deserializing it...
>          Build Operation ID: |IM7kOncAsTk=.1ad74fbc_
>          
>          Agent extension 
>          Before if loop >> DotNet Runtime 2.1.26
>          DotNet Runtime 2.1.26Writing output script to '/run.sh'
>          Found startup DLL name from manifest file
>          Running the command: dotnet "MyWebApp.dll"
>          Hosting environment: Production
>          Content root path: /oryxtests/a0ec176690a54017897a4006e2bfd16d
>          Now listening on: http://[::]:3000
>          Application started. Press Ctrl+C to shut down.

All these tests are running fine locally as well as in the privately hosted oryxlinux pool. I'm guessing some  port restriction is there. Can you please take a look into it?
Here is a sample build

https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=5029380&view=logs&j=72dd53dc-cc7e-5359-419d-190601712c34&t=28831f2f-ff0f-5427-ca18-e78664bf3d01

### Virtual environments affected

- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [X] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019

### Image version and build link

image: ubuntu-latest
failed build (hosted in azure pipelines) link: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=5029380&view=results
successful build (hosted in private pool - OryxLinux) link: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=5029191&view=results

relevant PR: https://github.com/microsoft/Oryx/pull/1064/files

### Is it regression?

n/a

### Expected behavior

all the tests should run successfully, container ports should be accessible from tests

### Actual behavior

all the tests failing with following error message

> [xUnit.net 00:15:10.10]     Microsoft.Oryx.Integration.Tests.DotNetCoreRuntimeVersion21Tests.CanBuildAndRunApp_WhenRecursiveLookUpIsDisabled_ButProjectSettingIsSupplied [FAIL]
>   X Microsoft.Oryx.Integration.Tests.DotNetCoreRuntimeVersion21Tests.CanBuildAndRunApp_WhenRecursiveLookUpIsDisabled_ButProjectSettingIsSupplied [29s 753ms]
>   Error Message:
>    Did not get the port mapping in expected format. StdOut: 0.0.0.0:49206
> :::49206
> 

### Repro steps

Not sure if this works .. but the easiest repro would be ...

rerun the failed job of the following build ...
https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=5029380&view=results

**Comment by Darleev** [comment]
Hello @arroyc,
We will check the issue

**Comment by dsame** [comment]
@arroyc can you please point out the script or yml file where is the step `As part of the test I create docker container with port mapping`

**Comment by arroyc** [comment]
@Darleev  any update?

**Comment by arroyc** [comment]
@dsame thanks for your reply .. i believe this is what you are asking .. this is where we populate docker arguments for port mapping https://github.com/microsoft/Oryx/blob/a389296f4a1a52b0581660c43a2ba641c04b77d8/tests/Oryx.Tests.Common/DockerCli.cs#L355
https://github.com/microsoft/Oryx/blob/a389296f4a1a52b0581660c43a2ba641c04b77d8/tests/Oryx.Tests.Common/DockerCli.cs#L291
This is how we run docker once we populate all the necessary arguments
https://github.com/microsoft/Oryx/blob/a389296f4a1a52b0581660c43a2ba641c04b77d8/tests/Oryx.Tests.Common/DockerCli.cs#L121
https://github.com/microsoft/Oryx/blob/a389296f4a1a52b0581660c43a2ba641c04b77d8/src/BuildScriptGenerator.Common/ProcessHelper.cs#L97


let me know if thats not what you are looking for, I can share other details as you need

**Comment by arroyc** [comment]
> @arroyc can you please point out the script or yml file where is the step `As part of the test I create docker container with port mapping` ?
> 
> The root of the problem the docker listen on both IPv4 and IPv6 interfaces, so the detected ports string is
> 
> ```
>  0.0.0.0:49263
> :::49263
> ```
> 
> which cases the assert to fail:
> 
> ```
> var portMapping = stdOut?.Split(":");
>                     Assert.NotNull(portMapping);
>                     Assert.True(
>                         (portMapping.Length == 2),
> ```
> 
> In order to provide the fix i need to know the command which runs the docker.

so we are into that famous issue where docker is binding to both ipv4 and ipv6 and we want only ipv4, hmm doing a quick search on internet shows I need to  set net.ipv6.bindv6only to 0. Is that the fix?

**Comment by arroyc** [comment]
I was able to find an workaround by installing a stable docker ce 
here is the build id https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=5035925&view=logs&s=ff05ad62-bb9a-53b6-ce9f-72f329a63e7c&j=65e01c55-aa95-5d41-4bd2-87f2a532974e
