### ISSUE TITLE
Installing MYSYS2 fails

### ISSUE THREAD

**Issue by Zach-Zone** [actions/virtual-environments#3810]
### Description

When generating the Image it fails on the MYSYS2 install step due to  the GPG key for this package being invalid:

`vhd:` ---------------------------------------- pacman --noconfirm -Syuu (2nd pass)
==> vhd: error: mingw32: signature from "Christoph Reiter (MSYS2 development key) <reiter.christoph@gmail.com>" is unknown trust
==> vhd: error: mingw64: signature from "Christoph Reiter (MSYS2 development key) <reiter.christoph@gmail.com>" is unknown trust
==> vhd: error: ucrt64: signature from "Christoph Reiter (MSYS2 development key) <reiter.christoph@gmail.com>" is unknown trust
==> vhd: error: clang64: signature from "Christoph Reiter (MSYS2 development key) <reiter.christoph@gmail.com>" is unknown trust
==> vhd: error: msys: signature from "Christoph Reiter (MSYS2 development key) <reiter.christoph@gmail.com>" is unknown trust
    vhd: :: Synchronizing package databases...
    vhd:  mingw32 downloading...
==> vhd: error: mingw32: signature from "Christoph Reiter (MSYS2 development key) <reiter.christoph@gmail.com>" is unknown trust
    vhd:  mingw64 downloading...
==> vhd: error: mingw64: signature from "Christoph Reiter (MSYS2 development key) <reiter.christoph@gmail.com>" is unknown trust
==> vhd: error: ucrt64: signature from "Christoph Reiter (MSYS2 development key) <reiter.christoph@gmail.com>" is unknown trust
==> vhd: error: clang64: signature from "Christoph Reiter (MSYS2 development key) <reiter.christoph@gmail.com>" is unknown trust
    vhd:  ucrt64 downloading...
    vhd:  clang64 downloading...
==> vhd: error: msys: signature from "Christoph Reiter (MSYS2 development key) <reiter.christoph@gmail.com>" is unknown trust
==> vhd: error: failed to synchronize all databases (invalid or corrupted database (PGP signature))
    vhd:  msys downloading...
    vhd:
    vhd: INFO: No tasks running with the specified criteria.
    vhd:
==> vhd: error: mingw32: signature from "Christoph Reiter (MSYS2 development key) <reiter.christoph@gmail.com>" is unknown trust
==> vhd: error: mingw64: signature from "Christoph Reiter (MSYS2 development key) <reiter.christoph@gmail.com>" is unknown trust
    vhd: ---------------------------------------- Install msys2 packages
==> vhd: error: ucrt64: signature from "Christoph Reiter (MSYS2 development key) <reiter.christoph@gmail.com>" is unknown trust
==> vhd: error: clang64: signature from "Christoph Reiter (MSYS2 development key) <reiter.christoph@gmail.com>" is unknown trust
    vhd:
    vhd: INFO: No tasks running with the specified criteria.
    vhd:
    vhd: ---------------------------------------- Remove p7zip/7z package due to conflicts
    vhd: Installing mingw-w64-x86_64 packages
==> vhd: error: msys: signature from "Christoph Reiter (MSYS2 development key) <reiter.christoph@gmail.com>" is unknown trust
==> vhd: error: database 'mingw32' is not valid (invalid or corrupted database (PGP signature))
==> vhd: error: database 'mingw64' is not valid (invalid or corrupted database (PGP signature))
==> vhd: error: database 'ucrt64' is not valid (invalid or corrupted database (PGP signature))
==> vhd: error: database 'clang64' is not valid (invalid or corrupted database (PGP signature))
    vhd: The following packages will be installed: mingw-w64-x86_64-clang mingw-w64-x86_64-cmake mingw-w64-x86_64-ragel mingw-w64-x86_64-clang-tools-extra mingw-w64-x86_64-libxml2 mingw-w64-x86_64-llvm mingw-w64-x86_64-toolchain
    vhd: Installing mingw-w64-i686 packages
==> vhd: error: database 'msys' is not valid (invalid or corrupted database (PGP signature))
==> vhd: error: mingw32: signature from "Christoph Reiter (MSYS2 development key) <reiter.christoph@gmail.com>" is unknown trust
    vhd: The following packages will be installed: mingw-w64-i686-clang mingw-w64-i686-cmake mingw-w64-i686-ragel mingw-w64-i686-libxml2 mingw-w64-i686-llvm mingw-w64-i686-toolchain
    vhd:
    vhd: ---------------------------------------- Clean packages
    vhd:
    vhd: Cache directory: /var/cache/pacman/pkg/
==> vhd: error: mingw64: signature from "Christoph Reiter (MSYS2 development key) <reiter.christoph@gmail.com>" is unknown trust
==> vhd: error: ucrt64: signature from "Christoph Reiter (MSYS2 development key) <reiter.christoph@gmail.com>" is unknown trust
==> vhd: error: clang64: signature from "Christoph Reiter (MSYS2 development key) <reiter.christoph@gmail.com>" is unknown trust
==> vhd: error: msys: signature from "Christoph Reiter (MSYS2 development key) <reiter.christoph@gmail.com>" is unknown trust
==> vhd: error: target not found: p7zip
    vhd: :: Do you want to remove ALL files from cache? [Y/n]
    vhd: removing all files from cache...
    vhd:
==> vhd: error: mingw32: signature from "Christoph Reiter (MSYS2 development key) <reiter.christoph@gmail.com>" is unknown trust
    vhd: Database directory: /var/lib/pacman/
    vhd: :: Do you want to remove unused repositories? [Y/n]
==> vhd: error: mingw64: signature from "Christoph Reiter (MSYS2 development key) <reiter.christoph@gmail.com>" is unknown trust
    vhd: removing unused sync repositories...
    vhd:
    vhd: ---------------------------------------- Installed mingw-w64-x86_64 packages
    vhd:
    vhd: ---------------------------------------- Installed mingw-w64-i686 packages
==> vhd: error: ucrt64: signature from "Christoph Reiter (MSYS2 development key) <reiter.christoph@gmail.com>" is unknown trust
    vhd:
==> vhd: error: clang64: signature from "Christoph Reiter (MSYS2 development key) <reiter.christoph@gmail.com>" is unknown trust
    vhd: MSYS2 installation completed
==> vhd: error: msys: signature from "Christoph Reiter (MSYS2 development key) <reiter.christoph@gmail.com>" is unknown trust
==> vhd: error: database 'mingw32' is not valid (invalid or corrupted database (PGP signature))
==> vhd: error: database 'mingw64' is not valid (invalid or corrupted database (PGP signature))
==> vhd: error: database 'ucrt64' is not valid (invalid or corrupted database (PGP signature))
==> vhd: error: database 'clang64' is not valid (invalid or corrupted database (PGP signature))
==> vhd: error: database 'msys' is not valid (invalid or corrupted database (PGP signature))
==> vhd: error: mingw32: signature from "Christoph Reiter (MSYS2 development key) <reiter.christoph@gmail.com>" is unknown trust
==> vhd: error: mingw64: signature from "Christoph Reiter (MSYS2 development key) <reiter.christoph@gmail.com>" is unknown trust
==> vhd: error: ucrt64: signature from "Christoph Reiter (MSYS2 development key) <reiter.christoph@gmail.com>" is unknown trust
==> vhd: error: clang64: signature from "Christoph Reiter (MSYS2 development key) <reiter.christoph@gmail.com>" is unknown trust
==> vhd: error: msys: signature from "Christoph Reiter (MSYS2 development key) <reiter.christoph@gmail.com>" is unknown trust
==> vhd: error: database 'mingw32' is not valid (invalid or corrupted database (PGP signature))
==> vhd: error: database 'mingw64' is not valid (invalid or corrupted database (PGP signature))
==> vhd: error: database 'ucrt64' is not valid (invalid or corrupted database (PGP signature))
==> vhd: error: database 'clang64' is not valid (invalid or corrupted database (PGP signature))
==> vhd: error: database 'msys' is not valid (invalid or corrupted database (PGP signature))
==> vhd: error: mingw32: signature from "Christoph Reiter (MSYS2 development key) <reiter.christoph@gmail.com>" is unknown trust
==> vhd: error: mingw64: signature from "Christoph Reiter (MSYS2 development key) <reiter.christoph@gmail.com>" is unknown trust
==> vhd: error: ucrt64: signature from "Christoph Reiter (MSYS2 development key) <reiter.christoph@gmail.com>" is unknown trust
==> vhd: error: clang64: signature from "Christoph Reiter (MSYS2 development key) <reiter.christoph@gmail.com>" is unknown trust
==> vhd: error: msys: signature from "Christoph Reiter (MSYS2 development key) <reiter.christoph@gmail.com>" is unknown trust
==> vhd: error: mingw32: signature from "Christoph Reiter (MSYS2 development key) <reiter.christoph@gmail.com>" is unknown trust
==> vhd: error: mingw64: signature from "Christoph Reiter (MSYS2 development key) <reiter.christoph@gmail.com>" is unknown trust
==> vhd: error: ucrt64: signature from "Christoph Reiter (MSYS2 development key) <reiter.christoph@gmail.com>" is unknown trust
==> vhd: error: clang64: signature from "Christoph Reiter (MSYS2 development key) <reiter.christoph@gmail.com>" is unknown trust
==> vhd: error: msys: signature from "Christoph Reiter (MSYS2 development key) <reiter.christoph@gmail.com>" is unknown trust
    vhd:
    vhd: Starting discovery in 1 files.
    vhd: Discovering in C:\image\Tests\MSYS2.Tests.ps1.
    vhd: Found 35 tests. 860ms
    vhd: Discovery finished in 1.41s.
    vhd: Running tests.`

I have seen this looks to be an issue with the MYSYS2 package here: https://github.com/msys2/MSYS2-packages/issues/2397

Is anyone else build failing on this step, is there any way to resolve this issue as part of the solution?

Thanks  

### Virtual environments affected

- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [X] Windows Server 2019

### Image version and build link

trying to create image to be used. 

### Expected behavior

Installation to complete successully

### Actual behavior

Image generation is failing

### Repro steps

choco install packer
Install-Module -Name Az -Repository PSGallery -Force
Invoke-WebRequest -Uri https://aka.ms/installazurecliwindows -OutFile .\AzureCLI.msi; Start-Process msiexec.exe -Wait -ArgumentList '/I AzureCLI.msi /quiet'; rm .\AzureCLI.msi
Set-Location c:\
git clone https://github.com/actions/virtual-environments.git
Set-Location C:\virtual-environments

Import-Module .\helpers\GenerateResourcesAndImage.ps1

GenerateResourcesAndImage -SubscriptionId {YourSubscriptionId} -ResourceGroupName "myTestResourceGroup" -ImageGenerationRepositoryRoot "$pwd" -ImageType Ubuntu1604 -AzureLocation "East US"

**Comment by Darleev** [comment]
Hello @Zach-Zone,
We will investigate the issue.

**Comment by nehagargSeequent** [comment]
@Darleev/ @al-cheb, we are experiencing the same issue while building a Win2019 image. I can see that the PR was _Closed_ instead of being _Merged_. Should I expect it to work anyways?

Thanks

**Comment by al-cheb** [comment]
@Zach-Zone, The PR has been merged to main branch. Please pull the latest changes.

**Comment by Zach-Zone** [comment]
@al-cheb looks to be working now thanks for your help.
