### ISSUE TITLE
This check failed, unable to find any online and idle runners

### ISSUE THREAD

**Issue by mattBrzezinski** [actions/virtual-environments#3815]
### Description

We use GitHubActions to host nightly CI builds as part of the [Julia](https://github.com/JuliaLang/julia) ecosystem. Last night we've received notifications that our CI jobs were failing. Looking into it all of them just have a message stating `This check failed`. Apparently we are unable to connect to any of the hosted runners, existing repos attempting to run nightly builds have the following message appear in their logs:

```
Can't find any online and idle self-hosted or hosted runner in the current repository, account/organization that matches the required labels: 'ubuntu-latest'
Waiting for a self-hosted or a hosted runner to pickup this job...
```

Below are links to various repos which have this issue:
- https://github.com/invenia/Checkpoints.jl/actions/runs/1073405172
- https://github.com/invenia/Syslogs.jl/actions/runs/1073396424
- https://github.com/invenia/KeyedFrames.jl/actions/runs/1073395358

We perform nightly CI builds in other organizations, which do not have issues:
- https://github.com/JuliaCloud/AWS.jl/actions/runs/1077072313

This seems to be isolated to our [Invenia](https://github.com/invenia/) organization. When I manually select `Re-Run All Jobs`, everything works as expected.

### Virtual environments affected

- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [X] Ubuntu 20.04
- [ ] macOS 10.15
- [X] macOS 11
- [ ] Windows Server 2016
- [X] Windows Server 2019

### Image version and build link

```
Virtual Environment
  Environment: ubuntu-20.04
  Version: 20210726.1
  Included Software: https://github.com/actions/virtual-environments/blob/ubuntu20/20210726.1/images/linux/Ubuntu2004-README.md
  Image Release: https://github.com/actions/virtual-environments/releases/tag/ubuntu20%2F20210726.1
```

### Expected behavior

The GHA to connect to a runner, and run the workflow automatically.

### Actual behavior

We need to manually select `cancel run`, then start all jobs for it to begin.

### Repro steps

Our GHA workflow can be found [here](https://github.com/invenia/Checkpoints.jl/blob/main/.github/workflows/CI.yml).

**Comment by mattBrzezinski** [comment]
I will note, I have recently been working on a project [KeepActionsAlive](https://github.com/invenia/KeepActionsAlive) which may have caused this in some way.

We develop many packages for the Julia ecosystem. Some of these are not actively developed, but are actively used. GHA has a 60 day limit for automated workflows becoming cancelled if the project is not worked in. The KeepActionsAlive project is run on AWS Lambda and loops over all our workflows and hits the [enable a workflow](https://docs.github.com/en/rest/reference/actions#enable-a-workflow) REST endpoint to re-enable the workflow automatically.

I ran through this yesterday afternoon before our nightly jobs would have began. Not sure if there is something to it or not.

**Comment by mattBrzezinski** [comment]
cc: @morris25 @wynand

**Comment by maxim-lobanov** [comment]
Can be related to past incident with GitHub Actions? https://www.githubstatus.com/incidents/8qy34dmg4kdm
Does it work for you now?

**Comment by mattBrzezinski** [comment]
Thanks for the response Maxim! I did not see this incident open yesterday. We did have some failures with out nightly builds this morning. They are scheduled to start at 2am UTC. It seems this issue was marked resolved just past 9pm UTC.

I'll check in again some time this weekend with an update.

**Comment by Darleev** [comment]
Hello,
We are going to close the issue.
If additional information is required, do not hesitate to contact us.
