### ISSUE TITLE
moby-containerd fails to install for Ubuntu 20.04

### ISSUE THREAD

**Issue by itdevops-channelcapital** [actions/virtual-environments#3818]
### Description

I am trying to build a new Ubuntu 20.04 build agent from the latest image, but keep getting a failure using the latest version 20210726.1. I have also tried using previous versions and am experiencing the same problem.

I did build an Ubuntu build agent around 2 weeks ago and had no problems.

The error seems to be related to a mismatch in file size when trying to download the package for moby-containerd.

    azure-arm: Reading package lists...
    azure-arm: Building dependency tree...
    azure-arm: Reading state information...
    azure-arm: Package 'moby-cli' is not installed, so not removed
    azure-arm: Package 'moby-engine' is not installed, so not removed
    azure-arm: 0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
    azure-arm: Hit:1 http://azure.archive.ubuntu.com/ubuntu focal InRelease
    azure-arm: Hit:2 http://azure.archive.ubuntu.com/ubuntu focal-updates InRelease
    azure-arm: Hit:3 http://azure.archive.ubuntu.com/ubuntu focal-backports InRelease
    azure-arm: Hit:4 http://security.ubuntu.com/ubuntu focal-security InRelease
    azure-arm: Hit:5 https://packages.microsoft.com/ubuntu/20.04/prod focal InRelease
    azure-arm: Reading package lists...
    azure-arm: Reading package lists...
    azure-arm: Building dependency tree...
    azure-arm: Reading state information...
    azure-arm: The following additional packages will be installed:
    azure-arm:   moby-buildx moby-containerd moby-runc pigz
    azure-arm: Suggested packages:
    azure-arm:   aufs-tools cgroupfs-mount | cgroup-lite
    azure-arm: The following NEW packages will be installed:
    azure-arm:   moby-buildx moby-cli moby-containerd moby-engine moby-runc pigz
    azure-arm: 0 upgraded, 6 newly installed, 0 to remove and 0 not upgraded.
    azure-arm: Need to get 91.9 MB of archives.
    azure-arm: After this operation, 398 MB of additional disk space will be used.
    azure-arm: Get:1 http://azure.archive.ubuntu.com/ubuntu focal/universe amd64 pigz amd64 2.4-1 [57.4 kB]
    azure-arm: Get:2 https://packages.microsoft.com/ubuntu/20.04/prod focal/main amd64 moby-buildx amd64 0.6.0+azure-1 [21.0 MB]
    azure-arm: Get:3 https://packages.microsoft.com/ubuntu/20.04/prod focal/main amd64 moby-cli amd64 20.10.7+azure-1 [12.1 MB]
    azure-arm: Get:4 https://packages.microsoft.com/ubuntu/20.04/prod focal/main amd64 moby-runc amd64 1.0.1+azure-1 [6695 kB]
    azure-arm: Get:5 https://packages.microsoft.com/ubuntu/20.04/prod focal/main amd64 moby-containerd amd64 1.4.8+azure-1 [27.3 MB]
    azure-arm: Err:5 https://packages.microsoft.com/ubuntu/20.04/prod focal/main amd64 moby-containerd amd64 1.4.8+azure-1
    azure-arm:   File has unexpected size (26978268 != 27328778). Mirror sync in progress? [IP: 52.230.121.169 443]
    azure-arm:   Hashes of expected file:
    azure-arm:    - SHA512:b39ced7ce38f547be20d7cd64ae85c7acd77e669f0764fa54d6f2962b8a00b79a11822c22ae3843da26b67eb6c2f436d13dae74dcc4933683b65e2a971c3a6ac
    azure-arm:    - SHA256:5f8a73e8b1dd7ef167b85fe8778d3879ed0cb76c7493d89bfc286e8c03a1cbd7
    azure-arm:    - SHA1:f4b5659e140b1570f9e3ca60d574c40b0a2486ea [weak]
    azure-arm:    - MD5Sum:668986ddc3a68462cbcfef33cd0088dd [weak]
    azure-arm:    - Filesize:27328778 [weak]
    azure-arm: Get:6 https://packages.microsoft.com/ubuntu/20.04/prod focal/main amd64 moby-engine amd64 20.10.7+azure-1 [24.7 MB]
    azure-arm: Fetched 64.6 MB in 7s (9852 kB/s)
==> azure-arm: E: Failed to fetch https://packages.microsoft.com/ubuntu/20.04/prod/pool/main/m/moby-containerd/moby-containerd_1.4.8+azure-1_amd64.deb  File has unexpected size (26978268 != 27328778). Mirror sync in progress? [IP: 52.230.121.169 443]
==> azure-arm:    Hashes of expected file:
==> azure-arm:     - SHA512:b39ced7ce38f547be20d7cd64ae85c7acd77e669f0764fa54d6f2962b8a00b79a11822c22ae3843da26b67eb6c2f436d13dae74dcc4933683b65e2a971c3a6ac
==> azure-arm:     - SHA256:5f8a73e8b1dd7ef167b85fe8778d3879ed0cb76c7493d89bfc286e8c03a1cbd7
==> azure-arm:     - SHA1:f4b5659e140b1570f9e3ca60d574c40b0a2486ea [weak]
==> azure-arm:     - MD5Sum:668986ddc3a68462cbcfef33cd0088dd [weak]
==> azure-arm:     - Filesize:27328778 [weak]
==> azure-arm: E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
    azure-arm: Reading package lists...
    azure-arm: Building dependency tree...
    azure-arm: Reading state information...
    azure-arm: Recommended packages:
    azure-arm:   moby-cli
    azure-arm: The following NEW packages will be installed:
    azure-arm:   moby-buildx
    azure-arm: 0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
    azure-arm: Need to get 0 B/21.0 MB of archives.
    azure-arm: After this operation, 61.4 MB of additional disk space will be used.
    azure-arm: Selecting previously unselected package moby-buildx.
    azure-arm: (Reading database ... 60249 files and directories currently installed.)
    azure-arm: Preparing to unpack .../moby-buildx_0.6.0+azure-1_amd64.deb ...
    azure-arm: Unpacking moby-buildx (0.6.0+azure-1) ...
    azure-arm: Setting up moby-buildx (0.6.0+azure-1) ...
==> azure-arm: debconf: unable to initialize frontend: Dialog
==> azure-arm: debconf: (Dialog frontend will not work on a dumb terminal, an emacs shell buffer, or without a controlling terminal.)
==> azure-arm: debconf: falling back to frontend: Readline
==> azure-arm: debconf: unable to initialize frontend: Readline
==> azure-arm: debconf: (This frontend requires a controlling tty.)
==> azure-arm: debconf: falling back to frontend: Teletype
==> azure-arm: dpkg-preconfigure: unable to re-open stdin:
==> azure-arm: Failed to start docker.service: Unit docker.service not found.
==> azure-arm: Provisioning step had errors: Running the cleanup provisioner, if present...
==> azure-arm: Removing the created Deployment object: 'pkrdpurg1pscfty'
==> azure-arm: Azure token expired. Saving the refreshed token...
==> azure-arm:
==> azure-arm: Cleanup requested, deleting resource group ...
==> azure-arm: Resource group has been deleted.
Build 'azure-arm' errored after 8 minutes 27 seconds: Script exited with non-zero exit status: 5.Allowed exit codes are: [0]

### Virtual environments affected

- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [X] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019

### Image version and build link

Using Self-hosted Agents and running locally.

### Is it regression?

N/A

### Expected behavior

To complete the building of Ubuntu 20.04 agent successfully.

### Actual behavior

Keeps failing to download / install the moby-containerd package.

### Repro steps

Execute Packer build of the Ubuntu 20.04 template from release 20210726.

**Comment by maxim-lobanov** [comment]
Please make sure that you have run `sudo apt-get update` before installation new packages.

**Comment by itdevops-channelcapital** [comment]
Hi @maxim-lobanov ,

I am not 100% familiar with packer, but how would I change the template in _/images/linux/ubuntu2004.json_ to run a `sudo apt-get update`?
I thought that was the purpose of the template and running packer to create the image in a desired state.

**Comment by maxim-lobanov** [comment]
Hm, we already have `sudo apt-get update` in `ubuntu2004` scripts so it should be okay.
I see that our CI failed with the same error: https://dev.azure.com/github/virtual-environments/_build/results?buildId=114275&view=logs&j=011e1ec8-6569-5e69-4f06-baf193d1351e&t=5431112d-2b61-5a5f-7042-ef698f761043

**Comment by catthehacker** [comment]
Maybe @cpuguy83 can help with that?

Package index does indeed has different size than the `deb` file in repo
```
moby-containerd_1.4.8+azure-1_amd64.deb            19-Jul-2021 23:40            26978268
```

```
❯ sha512sum moby-containerd_1.4.8\%2Bazure-1_amd64.deb
2598617443648302c5ca39b145497e238bf17b10567ff9f9ab96ef05cafc9825fc4786bf31ed7d10e5f8da686acd689b9d75145e490ac0e5884dcdc08de6a731  moby-containerd_1.4.8%2Bazure-1_amd64.deb
```

```
Package: moby-containerd
Priority: optional
Section: admin
Installed-Size: 120026
Maintainer: Microsoft <support@microsoft.com>
Architecture: amd64
Version: 1.4.8+azure-1
Replaces: containerd, containerd.io
Provides: containerd, containerd.io
Depends: init-system-helpers (>= 1.18~), libc6 (>= 2.4), moby-runc (>= 1.0.0~rc10)
Recommends: ca-certificates
Conflicts: containerd, containerd.io, moby-engine (<= 3.0.12)
Filename: pool/main/m/moby-containerd/moby-containerd_1.4.8+azure-1_amd64.deb
Size: 27328778
MD5sum: 668986ddc3a68462cbcfef33cd0088dd
SHA1: f4b5659e140b1570f9e3ca60d574c40b0a2486ea
SHA256: 5f8a73e8b1dd7ef167b85fe8778d3879ed0cb76c7493d89bfc286e8c03a1cbd7
SHA512: b39ced7ce38f547be20d7cd64ae85c7acd77e669f0764fa54d6f2962b8a00b79a11822c22ae3843da26b67eb6c2f436d13dae74dcc4933683b65e2a971c3a6ac
```

**Comment by miketimofeev** [comment]
@catthehacker thanks @cpuguy83 is the right person, I also dropped an e-mail to the moby team.

**Comment by cpuguy83** [comment]
This looks like a temporary error that can occur when apt repos are being updated.
As far as I can tell it seems too be ok now. If not let me know and I'll get the repos team involved.

**Comment by miketimofeev** [comment]
@cpuguy83 looks good now! Thanks!

**Comment by miketimofeev** [comment]
@itdevops-channelcapital I'm going to close the issue. Please feel free to contact us if you have any concerns.
Thank you!

**Comment by itdevops-channelcapital** [comment]
All good now! Thanks to all involved!
