### ISSUE TITLE
vcpkg error in latest win enviroments

### ISSUE THREAD

**Issue by mbonani** [actions/virtual-environments#3823]
### Description

in our CI https://dev.azure.com/mobsya/Thymio%20Software%20Suite/_build?definitionId=6 latest enviroments make the vcpkg task faile with this errror. 

##[error]Last command execution failed with error code '3221225477'.
##[error]Error: Last command execution failed with error code '3221225477'.
##[error]vcpkg failed with error: 'Error: Last command execution failed with error code '3221225477'.'.

Previous build was working fine. I also try to reset the cache.

### Virtual environments affected

- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [X] Windows Server 2019

### Image version and build link

https://dev.azure.com/mobsya/Thymio%20Software%20Suite/_build/results?buildId=2296&view=logs&j=a9b00659-32c6-5402-b915-6e59842632b3&t=231163c4-92bd-5036-1f66-6ec310c8b636

### Is it regression?

https://dev.azure.com/mobsya/Thymio%20Software%20Suite/_build/results?buildId=2295&view=logs&j=86cc0671-9d4b-5882-15c7-fafb7442c616

### Repro steps

New builds are no more working for windows because of the failed of vcpkg

**Comment by dibir-magomedsaygitov** [comment]
Hello @mbonani. Thank you for your report. We will take a look.

**Comment by mbonani** [comment]
Works with Current image version: '20210803.1'
