### ISSUE TITLE
Update/Add Rust + Cargo to 1.54.0

### ISSUE THREAD

**Issue by lukechu10** [actions/virtual-environments#3825]
### Tool name

Rust + Cargo

### Tool license

MIT/Apache 2.0

### Add or update?

- [ ] Add
- [X] Update

### Desired version

1.54

### Brief description of tool

Current version of rustc and cargo on build image is 1.53.0
1.54.0 was released 2 days ago.

### URL for tool's homepage

https://www.rust-lang.org/

### Virtual environments affected

- [X] Ubuntu 16.04
- [X] Ubuntu 18.04
- [X] Ubuntu 20.04
- [X] macOS 10.15
- [X] macOS 11
- [X] Windows Server 2016
- [X] Windows Server 2019

### Can this tool be installed during the build?

```bash
Use `actions-rs/toolchain` action.
```

### Are you willing to submit a PR?

Probably won't find the time so somebody else is welcome to do it

**Comment by dibir-magomedsaygitov** [comment]
Hello @lukechu10. Thank you for your report. Images with updated rustc and cargo should be available with the next week's rollout. I'll post an update message about that.

**Comment by dibir-magomedsaygitov** [comment]
Hello @lukechu10. Updated rust+cargo are available across all images. I'm going to close this issue. In case of any questions feel free to contact us.
