### ISSUE TITLE
Cargo audit 0.15.0 is causing error during the build in Azure DevOps

### ISSUE THREAD

**Issue by Chaouki-Tiouassiouine** [actions/virtual-environments#3840]
### Description

The new images from Ubuntu 18.04 and from Windows Server 2019 are causing issues. The error is coming from cargo-audit v0.15.0. See the log:

error[E0495]: cannot infer an appropriate lifetime due to conflicting requirements
==> azure-arm:   --> /usr/share/rust/.cargo/registry/src/github.com-1ecc6299db9ec823/git2-0.13.18/src/attr.rs:74:15
==> azure-arm:    |
==> azure-arm: 74 |         match (self, other) {
==> azure-arm:    |               ^^^^^^^^^^^^^
==> azure-arm:    |
==> azure-arm: note: first, the lifetime cannot outlive the anonymous lifetime defined on the method body at 73:26...
==> azure-arm:   --> /usr/share/rust/.cargo/registry/src/github.com-1ecc6299db9ec823/git2-0.13.18/src/attr.rs:73:26
==> azure-arm:    |
==> azure-arm: 73 |     fn eq(&self, other: &AttrValue<'_>) -> bool {
==> azure-arm:    |                          ^^^^^^^^^^^^^
==> azure-arm: note: ...so that the types are compatible
==> azure-arm:   --> /usr/share/rust/.cargo/registry/src/github.com-1ecc6299db9ec823/git2-0.13.18/src/attr.rs:74:15
==> azure-arm:    |
==> azure-arm: 74 |         match (self, other) {
==> azure-arm:    |               ^^^^^^^^^^^^^
==> azure-arm:    = note: expected `(&AttrValue<'_>, &AttrValue<'_>)`
==> azure-arm:               found `(&AttrValue<'_>, &AttrValue<'_>)`
==> azure-arm: note: but, the lifetime must be valid for the lifetime `'_` as defined on the impl at 72:30...
==> azure-arm:   --> /usr/share/rust/.cargo/registry/src/github.com-1ecc6299db9ec823/git2-0.13.18/src/attr.rs:72:30
==> azure-arm:    |
==> azure-arm: 72 | impl PartialEq for AttrValue<'_> {
==> azure-arm:    |                              ^^
==> azure-arm: note: ...so that the types are compatible
==> azure-arm:   --> /usr/share/rust/.cargo/registry/src/github.com-1ecc6299db9ec823/git2-0.13.18/src/attr.rs:79:16
==> azure-arm:    |
==> azure-arm: 79 |             | (Self::Bytes(bytes), AttrValue::String(string)) => string.as_bytes() == *bytes,
==> azure-arm:    |                ^^^^^^^^^^^^^^^^^^
==> azure-arm:    = note: expected `AttrValue<'_>`
==> azure-arm:               found `AttrValue<'_>`
==> azure-arm:
==> azure-arm:    Compiling abscissa_core v0.5.2
==> azure-arm: error: aborting due to previous error
==> azure-arm:
==> azure-arm: For more information about this error, try `rustc --explain E0495`.
==> azure-arm: error: could not compile `git2`
==> azure-arm:
==> azure-arm: To learn more, run the command again with --verbose.
==> azure-arm: warning: build failed, waiting for other jobs to finish...
==> azure-arm: error: failed to compile `cargo-audit v0.15.0`, intermediate artifacts can be found at `/tmp/cargo-installxpIVbW`

### Virtual environments affected

- [ ] Ubuntu 16.04
- [X] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [X] Windows Server 2019

### Image version and build link

For Ubuntu 18.04 -> Image Version: 20210726.1
For Windows 2019 -> Image Version: 20210725.1

### Repro steps

Build the image with Packer in Azure DevOps

**Comment by dibir-magomedsaygitov** [comment]
Hello @Chaouki-Tiouassiouine. Thank you for your report. Cargo-audit 0.15.0 is broken https://docs.rs/crate/cargo-audit/0.15.0 and we downgraded its version to 0.14.1. Images with downgraded cargo-audit should be available later this week. I'll post an update message.

**Comment by spoelstraethan** [comment]
Is there a way to use a cargo-lock file to avoid these bad versions for people building their own images from this repository without needing to wait for a new release?

**Comment by dibir-magomedsaygitov** [comment]
Hello @Chaouki-Tiouassiouine, @spoelstraethan. Cargo-audit was downgraded to version 0.14.1 and now available across all images. I'm going to close this issue. In case of any questions feel free to contact us.
