### ISSUE TITLE
is there any way to access github runner(not self hosted) using tmux?

### ISSUE THREAD

**Issue by sriedjx** [actions/virtual-environments#3849]
### Description

I need a requirement which i should able to access current github runner and troubleshoot issue which related to my application.

when i run any build on github runner it should run via tmux session which i should able to access that tmux session and see current running build process/logs

### Virtual environments affected

- [X] Ubuntu 16.04
- [X] Ubuntu 18.04
- [X] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019

### Image version and build link

ubuntu-latest

### Repro steps

NA

**Comment by dibir-magomedsaygitov** [comment]
Hello @sriedjx. Thank you for your question. We will take a look.

**Comment by LeonidLapshin** [comment]
Hey, @sriedjx 
Live troubleshooting is not the purpose of Github Actions runners, they created as a 'cattle', not a 'pet', so the main approach is to create a job/script/action to get some information from anything you want to do in terms of your build/test/deploy/publish process.  
If you just want to read some logs that you get from some remote session you can somehow redirect output from this session and read it as far as I understand. If you want manual troubleshooting, I guess that any VM from any cloud provider or even local troubleshooting will be the best approach to make a script that automate logs redirection first and than use it with Actions. 
Thank you!

**Comment by LeonidLapshin** [comment]
Hey, @sriedjx 
I'll close the issue, but feel free to tag me here if you have any concerns
