### ISSUE TITLE
Cannot install libgl1-mesa-glx:i386 anymore

### ISSUE THREAD

**Issue by marceltaeumel** [actions/virtual-environments#3852]
### Description

About 2 days ago, one of our preparation scripts started to fail. We need several i386 packages. One of them is `libgl1-mesa-glx:i386`

### Virtual environments affected

- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [X] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019

### Image version and build link

2021-08-04 PACKAGE INSTALL FAILs
Image version: 20210726.1
https://github.com/OpenSmalltalk/opensmalltalk-vm/runs/3236686104?check_suite_focus=true
Workflow: https://github.com/OpenSmalltalk/opensmalltalk-vm/blob/2c4ce31b8d6edf3c906958a7bf59b92d7fe52428/.github/workflows/linux.yml
Package install: https://github.com/OpenSmalltalk/opensmalltalk-vm/blob/2c4ce31b8d6edf3c906958a7bf59b92d7fe52428/scripts/ci/actions_prepare_linux_x86.sh

### Is it regression?

Yes

### Expected behavior

2021-08-03 PACKAGE INSTALL OK
Image version: 20210726.1
https://github.com/OpenSmalltalk/opensmalltalk-vm/runs/3225541738?check_suite_focus=true
Workflow: https://github.com/OpenSmalltalk/opensmalltalk-vm/blob/5e7a35243adb3cdddf8ef78e5dc1df7028249864/.github/workflows/linux.yml
Package install: https://github.com/OpenSmalltalk/opensmalltalk-vm/blob/5e7a35243adb3cdddf8ef78e5dc1df7028249864/scripts/ci/actions_prepare_linux_x86.sh

### Actual behavior

The package manager now gives the following error:

```
runner@fv-az82-65:~/work/opensmalltalk-vm/opensmalltalk-vm$ sudo apt-get install libgl1-mesa-glx:i386
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libgl1-mesa-glx:i386 : Depends: libgl1:i386 but it is not going to be installed
                        Depends: libglx-mesa0:i386 but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

### Repro steps

```bash
sudo dpkg --add-architecture i386
sudo apt-get update
sudo apt-get install libgl1-mesa-glx:i386
```

**Comment by dibir-magomedsaygitov** [comment]
Hello @marceltaeumel. Thank you for your report. We will take a look.

**Comment by marceltaeumel** [comment]
I think I kind of found a solution. Maybe it is related to some recent changes ... somewhere.

```
sudo apt-get install libllvm12:i386
```

After installing "libllvm12:i386", the package manager could finally resolve the other dependency issues:

```
libgl1-mesa-dri:i386
libglx-mesa0:i386
libglx0:i386
libgl1-mesa-glx:i386
```

Hope this helps.

**Comment by LeonidLapshin** [comment]
Hello, @marceltaeumel !
We have not changed anything connected to this package as far as I can see, I suppose that exact arch match is the  proper way to install 32 bit packages, is this workaround acceptable for you?

**Comment by marceltaeumel** [comment]
>  is this workaround acceptable for you?
Yes. If have too little knowledge about package-dependency management in Ubuntu to find the actual cause of the issue. i386 packages might disappear in future Ubuntu releases anyway.

**Comment by LeonidLapshin** [comment]
@marceltaeumel , I'll close the issue, but feel free to tag me here if something will went wrong :)
Thanks!

**Comment by catthehacker** [comment]
Small hint, you can try running `sudo apt install -f` after failed `apt install` which should try to fix dependencies for you, but if it will not be able, it should show you a more informative description on why it doesn't want to install main package.
