### ISSUE TITLE
ghc-8.10.5 not found in github action environment

### ISSUE THREAD

**Issue by SamuelSchlesinger** [actions/virtual-environments#3854]
### Description

The job is here: https://github.com/SamuelSchlesinger/stm-actor/runs/3243492990?check_suite_focus=true

If you look, you'll see that all the other GHC versions are found, but not that one. I would like to have my code under test with that version of GHC specifically, as its one under use for a lot of applications.

### Virtual environments affected

- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [X] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019

### Image version and build link

https://github.com/SamuelSchlesinger/stm-actor/runs/3243492990?check_suite_focus=true

### Expected behavior

I want ghc-8.10.5 to be found

### Actual behavior

ghc-8.10.5 is not found

### Repro steps

Make an ubuntu-latest build action which uses ghc 8.10.5, try to trigger the build. It will fail finding ghc-8.10.5

**Comment by dibir-magomedsaygitov** [comment]
Hello @SamuelSchlesinger. Thank for your report. 
GHC 8.10.4 is the latest available version via `apt-cache search "^ghc-"` for 8.10.* versions (we use `apt-cache search "^ghc-"` to extract 2 latest major.minor versions). You can use official Haskell Action to install any desired  version in runtime: https://github.com/haskell/actions/tree/main/setup

**Comment by dibir-magomedsaygitov** [comment]
Hello @SamuelSchlesinger. Any updates on the issue? Was suggested fix helpful for you?

**Comment by dibir-magomedsaygitov** [comment]
Hello @SamuelSchlesinger. Suggested fix should help you to let your workflows to pass. I'm going to close this issue. Feel free to open new one in case of any concerns.
