### ISSUE TITLE
[All platforms] Add Adoptium Temurin binaries to Hosted agents

### ISSUE THREAD

**Issue by maxim-lobanov** [actions/virtual-environments#3859]
### Tool name

Adoptium Temurin

### Tool license

The same like Adopt OpenJDK

### Add or update?

- [X] Add
- [ ] Update

### Desired version

all LTS: 8, 11

### Brief description of tool

Currently, we cache Adopt OpenJDK binaries on Hosted agents. Adopt OpenJDK will be deprecated soon so we need to switch to Adoptium Temurin binaries.

New binaries should be placed to the following toolcache folders:
- Windows: `C:\hostedtoolcache\windows\Java_Temurin-Hotspot_jdk\16.0.2-7\x64`
- Ubuntu: `/opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/16.0.2-7/x64`
- macOS: `/Users/runner/hostedtoolcache/Java_Temurin-Hotspot_jdk/16.0.2-7/x64/Contents/Home`
**Note:** Version format stays the same but tool name will be `Java_Temurin-Hotspot_jdk`.

For now, new binaries should be placed on images alongside with Adopt OpenJDK binaries since `actions/setup-java` has a lot of people who use Adopt OpenJDK yet and we would like to continue to speed up their builds for now.
But `JAVA_HOME`, `JAVA_HOME_8_X64` and `JAVA_HOME_11_X64` environment variables should point to the new Temurin binaries.

Both Adopt OpenJDK and Adoptium provide identical API so the most of scripts and logic can be reused.
Only endpoint should be changed from `https://api.adoptopenjdk.net/v3` to `https://api.adoptium.net/v3`

In documentation, we should write information only about Adoptium binaries.

### URL for tool's homepage

https://adoptium.net/

### Virtual environments affected

- [X] Ubuntu 16.04
- [X] Ubuntu 18.04
- [X] Ubuntu 20.04
- [X] macOS 10.15
- [X] macOS 11
- [X] Windows Server 2016
- [X] Windows Server 2019

**Comment by mikhailkoliada** [comment]
MacOS and Windows are done, for Linux we are waiting for https://github.com/adoptium/installer/issues/330

**Comment by mikhailkoliada** [comment]
The Linux installer (the last one) has been merged, the images with the Eclipse Temurin jdk will be deployed next week.

**Comment by mikhailkoliada** [comment]
The last installer (ubuntu) has been deployed
