### ISSUE TITLE
Xamarin.IOS version 14.20.x not supported in macOS 10.15

### ISSUE THREAD

**Issue by keerthinathganjam** [actions/virtual-environments#3860]
### Description

We are using a third party dll in our xmarin project which requires Xamarin.IOS version 14.20.x which is still not supported in macOS 10.15.

### Virtual environments affected

- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [X] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019

### Image version and build link

Environment: macos-10.15
Version: 20210801.1
Included Software: https://github.com/actions/virtual-environments/blob/macOS-10.15/20210801.1/images/macos/macos-10.15-Readme.md
Image Release: https://github.com/actions/virtual-environments/releases/tag/macOS-10.15%2F20210801.1
Current image version: '20210801.1'
Agent running as: 'runner'

### Repro steps

Environment: macos-10.15
Version: 20210801.1
Included Software: https://github.com/actions/virtual-environments/blob/macOS-10.15/20210801.1/images/macos/macos-10.15-Readme.md
Image Release: https://github.com/actions/virtual-environments/releases/tag/macOS-10.15%2F20210801.1
Current image version: '20210801.1'
Agent running as: 'runner'

**Comment by miketimofeev** [comment]
Hi @keerthinathganjam!
We are not going to add Xamarin ios 14.20 to macOS 10.15 image as it's not fully compatible with preinstalled Xcode versions. Please consider using macOS-11 image that has 14.20 onboard. You can apply for a private preview using steps in this guide
https://github.com/actions/virtual-environments/blob/main/docs/macos-11-onboarding.md
