### ISSUE TITLE
MacOS Security failed to load

### ISSUE THREAD

**Issue by TingDaoK** [actions/virtual-environments#3861]
### Description

Our CI using macOS-latest start failing to load credentials from yesterday. Apple functions like `SecItemImport` and `SecPKCS12Import` all returns `errSecAuthFailed`. No code and credentials changed. I assume it's something updated from the virtual environments result in the error. And it does not happen for my local mac. I am not sure, but it's my best guess. 
Check the failures from this two PR. Nothing related to the test changed with the latest commit, but the CI failed.
https://github.com/awslabs/aws-crt-java/runs/3252926181#step:3:1549
https://github.com/awslabs/aws-c-io/runs/3246621983#step:2:1029

### Virtual environments affected

- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [X] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019

### Image version and build link

[failed link](https://github.com/awslabs/aws-crt-java/pull/363/checks?check_run_id=3255802141#step:1:8)
version is 20210801.1

[Previous succeed link](https://github.com/awslabs/aws-crt-java/runs/3225727824#step:1:8)
version is 20210725.1

### Is it regression?

yes

### Expected behavior

Apple functions like `SecItemImport` and `SecPKCS12Import` should success. 

### Actual behavior

All the Sec related function failed with `errSecAuthFailed`.

### Repro steps

Test the same code existing in aws-crt-java. All the tests passed three days ago, and without any code change, the test failed now. Please check this [PR](https://github.com/awslabs/aws-crt-java/pull/363)

**Comment by al-cheb** [comment]
Hello, @TingDaoK 
Could you please provide steps how we can verify `SecItemImport` and `SecPKCS12Import` from out side?

**Comment by al-cheb** [comment]
Sorry for the inconvenience. I am able to reproduce the issue. We are planning to deploy a fix till next Thursday.

**Comment by TingDaoK** [comment]
Thank you for quick investigation. Do we have a way to run on previous version? I did a quick search yesterday, and not able to find one.

**Comment by miketimofeev** [comment]
@TingDaoK unfortunately, it's not possible to select the image version at the moment

**Comment by TingDaoK** [comment]
Our CI passed now. Thanks for the fix!

**Comment by al-cheb** [comment]
Feel free to open the thread if you have any concerns.

**Comment by remyjette** [comment]
This is fixed for us in Azure DevOps for macOS-10.15, but still appears to be broken in macOS-10.14. Any chance we could get a fix for those agents too? Thanks!

**Comment by miketimofeev** [comment]
Hey @remyjette! Sorry for the inconvenience, we will update 10.14 pools next week.

**Comment by doodlesbykumbi** [comment]
@al-cheb (or @miketimofeev) Could you please shed light on how this bug came about in that particular image version ?

**Comment by miketimofeev** [comment]
@doodlesbykumbi it's not only the image but the underlying infrastructure as well. I'm afraid we can't share the details as it's related to the security aspect
