### ISSUE TITLE
Workflows stuck after version upgrade

### ISSUE THREAD

**Issue by ocelotl** [actions/virtual-environments#3869]
### Description

Our workflows started timing out after the ubuntu virtual environment version was updated from 20210726.1 to 20210803.0:

https://github.com/open-telemetry/opentelemetry-python-contrib/runs/3233334812?check_suite_focus=true#step:1:8
https://github.com/open-telemetry/opentelemetry-python-contrib/runs/3246276144?check_suite_focus=true#step:1:8

### Virtual environments affected

- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [X] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019

### Image version and build link

https://github.com/open-telemetry/opentelemetry-python-contrib/runs/3246276144?check_suite_focus=true#step:1:8

### Expected behavior

Tests run completely

### Actual behavior

Tests get stuck

### Repro steps

1. Open up a PR with a trivial change at https://github.com/open-telemetry/opentelemetry-python
2. Watch how tests get stuck

**Comment by LeonidLapshin** [comment]
Hey, @ocelotl 
We'll take a look soon :)

**Comment by dibir-magomedsaygitov** [comment]
Hello @ocelotl. Is the issue still appearing for you? I checked [software diff](https://github.com/actions/virtual-environments/commit/33004045ddbcfdf9f720afd42ce4c75a9e11b121#diff-6be9f9ce03ba57ca01e4ae937d5c2bb04893520fdf391ea87eb46acbc43ecdc5) from `20210726.1` to `20210803.0` image version and I can't see any suspicious update that could cause your workflows to fail. I re-run your workflow and it [succeeded](https://github.com/dibir-magomedsaygitov/opentelemetry-python-contrib/actions/runs/1134618853). Looks like it was temporary issue with the Elasticsearch.

**Comment by ocelotl** [comment]
Right, @dibir-magomedsaygitov , we are good to go now, thanks! :v:

I'll close this issue.
