### ISSUE TITLE
Uploading to Sentry using sentry cli stucks on macOS-11 machines

### ISSUE THREAD

**Issue by grzegorzkrukowski** [actions/virtual-environments#3870]
### Description

Our CI for the macOS application requires an upload of debug symbols to Sentry.

We are using Sentry CLI (newest 1.68.0 version) to upload it:
`sentry-cli --auth-token {auth_token} upload-dif "{dsyms_path}" --org {organization} --project {project}`

It is all working on macOS10.15 machines, but when we try to switch to macOS 11 it is failing.

The upload stucks - there is no error being thrown and the whole action is getting canceled because of the 40-minute timeout (we already increased it from 20 minutes). 
The upload has over 30 minutes to upload - normally it takes few seconds on macOS10.15 machines.

We tried locally on the same machines macOS-11 and it all works - so it's not related to CLI itself - more something related to network file transfers.

### Virtual environments affected

- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [X] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019

### Image version and build link

Current runner version: '2.279.0'
Operating System  macOS  11.5  20G71
Virtual Environment  Environment: macos-11.5  Version: 20210801.1

### Expected behavior

Upload to Sentry should succeed

### Actual behavior

Upload to Sentry is making the job stuck and hitting the timeout.

### Repro steps

1. Try uploading to Sentry using Sentry CLI:
`sentry-cli --auth-token {auth_token} upload-dif "{dsyms_path}" --org {organization} --project {project}`

2. Check stucking file transfer hitting the timeout of the job.

**Comment by LeonidLapshin** [comment]
Hey, @grzegorzkrukowski we'll take a look and return with updates soon :)

**Comment by vsafonkin** [comment]
Hi @grzegorzkrukowski, could you please clarify, you use `Azure DevOps` CI? I've  tried to build simple macOS application with dSYM on `macOS-11` and push debug symbols to `Sentry` from `Azure pipelines`, I have the following logs:
```
sentry-cli --auth-token *** upload-dif "/Users/runner/work/1/s/build/Debug/demo-macos.app.dSYM" --org "akvelon-0p" --project "akvelon-0p"

> Found 2 debug information files
> Prepared debug information files for upload
> Uploaded 2 missing debug information files
> File upload complete:

  PENDING 7b339f02-e932-3efe-b2a8-9a35c3379f54 (Contents/Resources/DWARF/demo-macos; x86_64 debug companion)
  PENDING 08d71fdd-665d-33b9-94cc-be33b69cbff8 (Contents/Resources/DWARF/demo-macos; arm64 debug companion)
> No new debug symbols to associate.
``` 
and looks like the task is finished successfully. It works on `macOS-10.15` as well.

**Comment by grzegorzkrukowski** [comment]
Hey @vsafonkin 

Your response looks correct.

We are using our custom Python scripts. 
As for sentry CLI itself, we are using exactly the same command as you, but for us, it stuck.
All works fine for macOS-10.15 on our end, but after upgrading to macOS-11 it is freezing CI completely.

The exact Python command we are using is:
```
upload_command = f'{script_path} --auth-token {auth_token} upload-dif "{dsyms_path}" --org {organization} --project {project}'
subprocess.run(upload_command, shell=True, check=True)
```

It could be related to the existing bug report for their CLI:
https://github.com/getsentry/sentry-cli/issues/988

I also posted mine there:
https://github.com/getsentry/sentry-cli/issues/1004

**Comment by grzegorzkrukowski** [comment]
No - we are using GitHub runners.

**Comment by vsafonkin** [comment]
@grzegorzkrukowski, unfortunately, I couldn't reproduce your issue with simple macos application on `macos-11`:
https://github.com/roasted-eggplant/circleci-demo-macos/runs/3298344488?check_suite_focus=true
Python script for uploading to Sentry: https://github.com/roasted-eggplant/circleci-demo-macos/blob/master/upload_to_sentry.py

Could you please take a look, maybe I've missed some details?

**Comment by vsafonkin** [comment]
@grzegorzkrukowski , unfortunately, I can't reproduce your issue with simple macos application on `macos-11`:
https://github.com/vsafonkin/circleci-demo-macos/runs/3301338590?check_suite_focus=true
Upload to Sentry is successful.

Could you please take a look, maybe I've missed some details?

**Comment by grzegorzkrukowski** [comment]
@vsafonkin Thanks for looking into that issue.

It looks exactly the same on my end in terms of what I do - build and upload dsyms.
I have been trying to get more info from Sentry CLI itself, I used `--log-level trace` to get as much info as I can.

With highest possible log it looks like this:
`DEBUG   2021-08-11 13:47:26.568848 +00:00 sentry-cli version: 1.68.0, platform: "darwin", architecture: "x86_64"
  INFO    2021-08-11 13:47:26.570640 +00:00 sentry-cli was invoked with the following command line: "sentry-cli" "--log-level" "trace" "--auth-token" "***" "upload-dif" "/Users/runner/work/archive/my.xcarchive/dSYMs" "--org" "ORG_NAME" "--project" "PROJECT_NAME"
  INFO    2021-08-11 13:47:26.571230 +00:00 Issuing a command for Organization: ORG_NAME Project: PROJECT_NAME`
  And then nothing for 20 minutes until:
`Error: The operation was canceled.`

The weirdest thing is that:
- it works fine on my local machine on exactly the same scripts and on macOS11.5 - which suggests that SentryCLI works fine and it's nothing on their end in combination with OS itself
- it works on macOS10

I cannot really see a difference in what you are doing and what I have on my end.

**Comment by grzegorzkrukowski** [comment]
I also found something quite similar being reported on Sentry GitHub:
https://github.com/getsentry/sentry-cli/issues/840

Which is fixed with this PR:
https://github.com/getsentry/sentry-cli/pull/896

I wonder if that could be also affecting our case. Maybe my files are just much bigger than yours.

**Comment by grzegorzkrukowski** [comment]
I can confirm that problem seems to be related to running it as `subprocess.run` - when I forced Sentry to run directly via GitHub YML it worked fine.

**Comment by grzegorzkrukowski** [comment]
I moved Sentry to an external step in .YML, but that didn't help - so it's not a problem with `subprocess.run` itself.

I also tried to make a simpler workflow - I uploaded my dSYM files and tried to only upload it without all other steps - and that worked... I run it 3 times and it always worked.

Then I tried the full workflow - with build & archive - and if stucks every single time on macOS11.

**Comment by vsafonkin** [comment]
@grzegorzkrukowski, maybe you can provide a simple example of failed uploading to Sentry? I'm afraid, if we can't reproduce it we can't do something from our side.

**Comment by grzegorzkrukowski** [comment]
@vsafonkin sure I will try to prepare a minimal public example that is failing.

**Comment by grzegorzkrukowski** [comment]
@vsafonkin I tried to prepare a simpler example that will not involve our production code, but it seems that it's somehow related to the project itself. When I replaced our project with `Hello World` it all works on exactly the same release scripts. Even when I just stripped down the project size to 10% of its size to share it - it works...

So it must be somehow related to the size of dSYMs - for our production app, it's around 30MB.
When I just upload only dSYMs in a job - it works (I tried to prepare an example with pure dSYMs to not share the code).

On production machines, when we build xcode and upload dSYMs all in one job it fails, but I cannot really share all this to public.

**Comment by grzegorzkrukowski** [comment]
I failed in producing a smaller example that works.

When I strip down our macOS project to bare minimum - it starts working.
When I move Sentry upload to a separate job (to run on the fresh machine) - it all works for the same dSYMs and same Python code.

Only case that makes it failing is to run it on the same machine that is building our main xCode project - but I cannot really share that one for debugging.

We will stick for now with having Sentry upload being done post-build process on separate, fresh machine.

**Comment by vsafonkin** [comment]
@grzegorzkrukowski, I see, obviously, some changes are taking place in VM during the build of the project which break Sentry cli. Honestly, I can't find the ways to help you without repro, looks like the problem most likely arises from the features of your project.

**Comment by vsafonkin** [comment]
Closed, because we can do nothing from our side.
