### ISSUE TITLE
Keychain access failing due to errSecAuthFailed (-25293).

### ISSUE THREAD

**Issue by grzegorzkrukowski** [actions/virtual-environments#3871]
### Description

One of our swift tests is using Keychain from Apple's Security framework.

We are using `SecItemAdd` in Swift codebase - but it started to fail with `errSecAuthFailed (-25293).` error.
Code has been used for a few years already and was working correctly before. 

With the latest updates around two weeks ago, it started to constantly fail.

### Virtual environments affected

- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [X] macOS 10.15
- [X] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019

### Image version and build link

Current runner version: '2.279.0'

### Is it regression?

yes

### Expected behavior

Keychain should be working on all macOS machines

### Actual behavior

Keychain is returning login error and fails

### Repro steps

1. Setup Swift Tests that use a Security framework
2. Use `SecItemAdd` with any sample data - make sure to log returned status
3. Observe Tests failing with `errSecAuthFailed (-25293).` error

**Comment by LeonidLapshin** [comment]
Hey, @grzegorzkrukowski !
As far as I know, that is a known issue (with the image) and it will be fixed with next image rollout this week. I'll check this information and return with update soon.
Thanks!

**Comment by rmarinho** [comment]
this week? our builds are failing and we can't ship our product. we need a fix ASAP

**Comment by al-cheb** [comment]
@grzegorzkrukowski , Could you please check if the issue is still reproduced?

**Comment by grzegorzkrukowski** [comment]
Hey @al-cheb. I can confirm it works for us on `Current runner version: '2.280.1'` - just tested it out - thanks !

**Comment by miketimofeev** [comment]
@grzegorzkrukowski thank you for the confirmation.
I'm going to close the issue, please feel free to contact us if you have any concerns.
