### ISSUE TITLE
Windows built from image always shows Network discovery message

### ISSUE THREAD

**Issue by jake8787** [actions/virtual-environments#3874]
### Description

If you apply windows image to an agent / machine it appears to have Network discovery message right away
![image](https://user-images.githubusercontent.com/74557823/128826425-973bf835-10d5-4623-8cac-812b5f78aadb.png)

I'm using Azure services (Scalable agents) to run Selenium UI tests on these machines and part of the screen obviously not visible because of it.
Tried to send there a command like 
runas /user:administrator netsh advfirewall firewall set rule group="Network Discovery" new enable=No
but it doesn't allow me to execute it:
![image](https://user-images.githubusercontent.com/74557823/128826994-8ce5ce32-ca70-46d1-8559-c66fe2e2f7c8.png)

Is there any way how get an image without any additional messages popping up?

### Virtual environments affected

- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [X] Windows Server 2019

### Image version and build link

For instance:
Windows Server 2019 (20210803 update)
https://github.com/actions/virtual-environments/releases/tag/win19%2F20210803.1

### Expected behavior

I expect clear screen without any messages

### Actual behavior

Check out screenshot from one of the machines

### Repro steps

1) Build an image with any Windows version, e.g. https://github.com/actions/virtual-environments/releases/tag/win19%2F20210803.1
2) Install it to Azure agents (Scalable ones in my case)
3) Check out a machine with installed image
![image](https://user-images.githubusercontent.com/74557823/128827430-184a19f7-00cb-4289-9792-d7aebe9ea7ad.png)

**Comment by al-cheb** [comment]
Hi, @jake8787 
We will take a look at this issue.

**Comment by catthehacker** [comment]
You need to run `runas /user:administrator "netsh advfirewall firewall set rule group=\"Network Discovery\" new enable=No"` in CMD or ```runas /user:administrator "netsh advfirewall firewall set rule group=`"Network Discovery`" new enable=No"``` in PowerShell

**Comment by al-cheb** [comment]
PR#3875 has been merged, you can start to regenerate image with the latest changes.

**Comment by jake8787** [comment]
> You need to run `runas /user:administrator "netsh advfirewall firewall set rule group=\"Network Discovery\" new enable=No"` in CMD or `` runas /user:administrator "netsh advfirewall firewall set rule group=`"Network Discovery`" new enable=No" `` in PowerShell
Thanks! I'm definitely taking notes here :)

**Comment by jake8787** [comment]
@al-cheb 
Just today generated new image from the same version and the message is still there
https://github.com/actions/virtual-environments/releases/tag/win19%2F20210803.1
Did I misunderstood you and you meant it will be available only in new versions?

**Comment by catthehacker** [comment]
@jake8787 
You need to pull latest changes from the repository since it was added after the tag was created (in https://github.com/actions/virtual-environments/commit/a64db791f32ffe355d7397c1ac896d42686e9dfa)
You can run `git checkout a64db791f32ffe355d7397c1ac896d42686e9dfa` and build it.

**Comment by jake8787** [comment]
@catthehacker 
Well...
We are using Azure (Packer build task) to build images. I'm not pulling all these files on my own, it's built in process. Is there any way how do I do it there? Anyways, if will be available right away in the upcoming releases, no worries, I could wait :)
![image](https://user-images.githubusercontent.com/74557823/129148912-a8f7b6c5-5970-4860-96b1-4f2c6310a85c.png)
![image](https://user-images.githubusercontent.com/74557823/129149330-9eb60539-c2de-4ab8-9375-cac7600013d6.png)
![image](https://user-images.githubusercontent.com/74557823/129149727-8c35aaa0-6c6b-4d23-ad14-705f6ba1860e.png)

**Comment by catthehacker** [comment]
> We use Azure (Packer build task) to build images. I'm not pulling all these files on my own, it's built in process. Is there any way how do I do it there?
> ![image](https://user-images.githubusercontent.com/74557823/129148912-a8f7b6c5-5970-4860-96b1-4f2c6310a85c.png)

You could try this:
![image](https://user-images.githubusercontent.com/31106839/129152901-cd4791dd-62ee-4fb7-a07f-51a30d3d70ea.png)

> Anyways, if it will be available right away in the upcoming releases, no worries, I could wait :)

Should be available next week if I'm not mistaken

**Comment by jake8787** [comment]
Thanks guys! @al-cheb @catthehacker 
It's now working as expected 👍
