### ISSUE TITLE
Keychain access failing due to error (Could not add password to keychain: security: SecKeychainItemCreateFromContent (<default>): The user name or passphrase you entered is not correct.)

### ISSUE THREAD

**Issue by mishraabhi1297** [actions/virtual-environments#3881]
### Description

The iOS release build is failing on Azure due to Keychain access.
This started happening only a few days ago when agent version was upgraded from '2.189.0' to '2.190.0'.

We are getting the following error when we are trying to log into appcenter from cmd:
Error: Could not add password to keychain: security: SecKeychainItemCreateFromContent (<default>): The user name or passphrase you entered is not correct.

### Virtual environments affected

- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [X] macOS 10.15
- [X] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019

### Image version and build link

Agent version: 2.190.0

### Is it regression?

yes

### Expected behavior

Keychain should be working on all macOS machines

### Actual behavior

Keychain is returning login error and fails

### Repro steps

Try logging into any website using macOS terminal and it will throw the same error mentioned above

**Comment by al-cheb** [comment]
Duplicate: https://github.com/actions/virtual-environments/issues/3861
