### ISSUE TITLE
AVD download is failing when API level is 29

### ISSUE THREAD

**Issue by LensSDK** [actions/virtual-environments#3891]
### Description

Getting below error when starting emulator

Error: Package path is not valid. Valid system image paths are:
null

Attached logs for reference.

[logs_9628422.zip](https://github.com/actions/virtual-environments/files/6981418/logs_9628422.zip)

### Virtual environments affected

- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [X] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019

### Image version and build link

Build link: https://office.visualstudio.com/OC/_build/results?buildId=9623726&view=results

Azure Dev ops: (under "Initialize job" -> "Virtual Environment" -> "Version".)
Version: 20210808.1

### Is it regression?

https://office.visualstudio.com/OC/_build/results?buildId=9606960&view=results

### Expected behavior

Emulator should be created & start without any error.

### Repro steps

Queue any job to below pipeline:

https://office.visualstudio.com/OC/_build?definitionId=15976&_a=summary

Observe the job fails while creating & starting Android Emulator

**Comment by miketimofeev** [comment]
Hi @LensSDK!
We will take a look.

**Comment by dmitry-shibanov** [comment]
Hello everyone. Looks like It’s an expected change from Android side. The `system-images;android-29;google_apis;x86` package was removed from stable channel. You can try to switch channel to “canary” to continue using this package or switch to another package ?
```
sdkmanager --update --channel=3
sdkmanager “system-images;android-29;google_apis;x86"
```

**Comment by LensSDK** [comment]
We were trying to use “system-images;android-27;google_apis;x86" and is working.

**Comment by LensSDK** [comment]
We shall check with above workaround and update here

**Comment by LensSDK** [comment]
@dmitry-shibanov can you share the release notes where it is mentioned that android-29  image is removed?
Also, the workaround is working fine.

Thanks

**Comment by dmitry-shibanov** [comment]
Hello @LensSDK. Unfortunately, we do not have the link. But we have checked and this package doesn’t exist in the stable channel anymore. You can check similar [issue](https://stackoverflow.com/questions/55504508/package-android-emulator-with-revision-at-least-28-1-9-not-available/).
I’m closing the issue for now since it is not related to the image. If you have any concerns feel free to ping me in the thread.
