### ISSUE TITLE
Add [g++ or gcc] for aarch64 and arm on ubuntu

### ISSUE THREAD

**Issue by anatawa12** [actions/virtual-environments#3892]
### Tool name

g++(gcc)(-9/-10)-aarch64-linux-gnu and g++(gcc)(-9/-10)-arm-linux-gnueabi

### Tool license

GPL

### Add or update?

- [X] Add
- [ ] Update

### Desired version

9.3.0-1ubuntu2

### Brief description of tool

The compiler and toolchain for building a binary for aarch64 and arm 32bit.

The `macos-11` (should) have a toolchain for aarch64 and [`windows-2019` also have for arm and arm64][windows-arm].
(I don't have access to `macos-11` so I don't know if actually installed for virtual environments but in my local macOS, there's a toolchain for aarch64)

So I think there should be a toolchain for arm & aarch64 on ubuntu.

[windows-arm]: https://github.com/actions/virtual-environments/blob/773f03950109be63099c757145fba3e0109fb5a0/images/win/Windows2019-Readme.md#workloads-components-and-extensions

### URL for tool's homepage

https://gcc.gnu.org/

### Provide a basic test case to validate the tool's functionality.

```bash
aarch64-linux-gnu-gcc --version
aarch64-linux-gnu-g++ --version
arm-linux-gnueabi-gcc --version
arm-linux-gnueabi-g++ --version
```

### Virtual environments affected

- [X] Ubuntu 16.04
- [X] Ubuntu 18.04
- [X] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019

### Can this tool be installed during the build?

```bash
apt install -y g++-aarch64-linux-gnu
apt install -y g++-arm-linux-gnueabi
# apt install -y gcc-aarch64-linux-gnu
# apt install -y gcc-arm-linux-gnueabi
```

### Tool installation time in runtime

each take about 13 seconds

### Are you willing to submit a PR?

yes but I think we need to talk about actual installation package. I probably should add 'g++-10-aarch64-linux-gnu' or 'g++-9-aarch64-linux-gnu'

**Comment by al-cheb** [comment]
Hello, @anatawa12 
Sorry, due to maintenance concerns, we'd rather not to add this tool to the images. Please continue install them in runtime.
