### ISSUE TITLE
Add Xcode 13

### ISSUE THREAD

**Issue by mbrar10** [actions/virtual-environments#3893]
### Tool name

Xcode 13

### Tool license

Enterprise

### Add or update?

- [X] Add
- [ ] Update

### Desired version

Xcode 13

### Brief description of tool

Requesting to add Xcode 13 to the hosted macOS agent pool. 

### Virtual environments affected

- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019

**Comment by miketimofeev** [comment]
Xcode 13 beta already added to macOS-11 image.

**Comment by mbrar10** [comment]
Thank you @miketimofeev!

how should I define Xcode directory in the Yaml pipeline to use Xcode 13 beta?

current we use Xcode 12 and it's defined as.

pool:
  vmImage: 'macos-latest'

and Xcode version as:
xcodeVersion: 'specifyPath'
xcodeDeveloperDir: '/Applications/Xcode_12.app'

**Comment by miketimofeev** [comment]
@mbrar10 do you use Azure Devops? If yes, you need to get access to macos-11 first. Please send an e-mail to @vijayma, more details are available here https://github.com/actions/virtual-environments-internal/issues/2599
