### ISSUE TITLE
Update/Add python3.8

### ISSUE THREAD

**Issue by Poolitzer** [actions/virtual-environments#39]
**Tool information**
- Tool name: python
- Add or update? Add
- Desired version: 3.8, no dev needed since released :)
- Approximate size: 
**Virtual environments affected**
- [x] macOS 10.14
- [x] Ubuntu 16.04 LTS
- [x] Ubuntu 18.04 LTS
- [x] Windows Server 2016 R2
- [x] Windows Server 2019

**Can this tool be installed during the build?**
I guess so

**Are you willing to submit a PR?**
If you are willing to share code lol

**Comment by kaylangan** [comment]
Thanks for the suggestion! We're currently working on adding this. I'll post an update when we start the roll-out of the updated images.

**Comment by kaylangan** [comment]
We've started rolling this out.

**Comment by Poolitzer** [comment]
uhm, can I just add python 3.8 to my building matrix and it will work?

**Comment by Poolitzer** [comment]
apparently its closed? https://github.com/actions/setup-python/issues/30#issuecomment-549554778

**Comment by kaylangan** [comment]
Yup! This has been fully deployed. Thanks for the patience!
