### ISSUE TITLE
Tests are failing in Linux Microsoft build image

### ISSUE THREAD

**Issue by Chaouki-Tiouassiouine** [actions/virtual-environments#3914]
### Description

The Linux Microsoft build for the build image is causing errors due to errors that are failing in test.helpers.psm1:141. See for the track trace:

    azure-arm: TotalCount            : 307
    azure-arm: Duration              : 00:00:45.9560313
    azure-arm: Executed              : True
    azure-arm: ExecutedAt            : 08/17/2021 08:28:55
    azure-arm: Version               : 5.2.2
    azure-arm: PSVersion             : 7.1.4
    azure-arm: PSBoundParameters     : {[Configuration, PesterConfiguration]}
    azure-arm: Plugins               :
    azure-arm: PluginConfiguration   :
    azure-arm: PluginData            :
    azure-arm: Configuration         : PesterConfiguration
    azure-arm: DiscoveryDuration     : 00:00:02.9205435
    azure-arm: UserDuration          : 00:00:40.6531997
    azure-arm: FrameworkDuration     : 00:00:02.3822881
    azure-arm: Failed                : {[-] homebrew}
    azure-arm: FailedBlocks          : {}
    azure-arm: FailedContainers      : {}
    azure-arm: Passed                : {[+] Sdkmanager from SDK tools is available, [+] Sdkman
    azure-arm:                         ager from Command-line tools is available, [+] platform
    azure-arm:                         s/android-23, [+] platforms/android-24…}
    azure-arm: Skipped               : {[!] graalvm, [!] native-image}
    azure-arm: NotRun                : {}
    azure-arm: Tests                 : {[+] Sdkmanager from SDK tools is available, [+] Sdkman
    azure-arm:                         ager from Command-line tools is available, [+] platform
    azure-arm:                         s/android-23, [+] platforms/android-24…}
    azure-arm: CodeCoverage          :
    azure-arm:
==> azure-arm: Exception: /imagegeneration/helpers/Tests.Helpers.psm1:41
==> azure-arm: Line |
==> azure-arm:   41 |          throw "Test run has failed"
==> azure-arm:      |          ~~~~~~~~~~~~~~~~~~~~~~~~~~~
==> azure-arm:      | Test run has failed
==> azure-arm: 
==> azure-arm: Provisioning step had errors: Running the cleanup provisioner, if present...

### Virtual environments affected

- [X] Ubuntu 16.04
- [X] Ubuntu 18.04
- [X] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019

### Image version and build link

https://github.com/actions/virtual-environments/blob/main/images/linux/ubuntu1804.json

### Repro steps

See for the repro steps the description. If you build an image, it will fail due to errors in the test script.

**Comment by al-cheb** [comment]
Hello, @Chaouki-Tiouassiouine 
Please pull the latest changes. PR https://github.com/actions/virtual-environments/pull/3908
