### ISSUE TITLE
GitHub hosted runner stopped picking up jobs

### ISSUE THREAD

**Issue by paulz** [actions/virtual-environments#3917]
### Description

GitHub Actions workflow are not starting since few hours ago:

```
Can't find any online and idle self-hosted runner in the current repository, account/organization that matches the required labels: 'macos-11.0'
Waiting for a self-hosted runner to pickup this job...
```

### Virtual environments affected

- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [X] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019

### Image version and build link

latest

### Repro steps

create workflow with GitHub runner

**Comment by paulz** [comment]
looks like it's working after renaming `macos-11.0` to `macos-11`

did we miss an announcement about the breaking change?

**Comment by al-cheb** [comment]
Hi, @paulz 
Look like we forgot to mention about it in the blog post - https://github.blog/changelog/2021-08-16-github-actions-macos-11-big-sur-is-generally-available-on-github-hosted-runners/

**Comment by miketimofeev** [comment]
@paulz both specs are available now, sorry for the inconvenience. Please migrate to `macOS-11` image spec as `macOS-11.0` can be deprecated in the future (with an announcement this time 😅)

**Comment by paulz** [comment]
Thank you, we did update our workflows. 

And thank you for the runners as they work great most of time and essential to our business.

Please make announcements if changes cause CI outages.
