### ISSUE TITLE
wkhtmltopdf installation fail

### ISSUE THREAD

**Issue by gaetanbuellet** [actions/virtual-environments#3921]
### Description

since this morning, when I try to install wkhtmltopdf like that,
```
      - name: Setup wkhtmltopdf
        run: sudo apt-get install wkhtmltopdf;cp /usr/bin/wkhtmltopdf /usr/local/bin/wkhtmltopdf
```

I have this error : 
```
E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/main/m/mesa/libegl-mesa0_21.0.3-0ubuntu0.2~20.04.1_amd64.deb  404  Not Found [IP: 52.252.75.106 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
Error: Process completed with exit code 100.
```

### Virtual environments affected

- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [X] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019

### Image version and build link

private repo

Current runner version: '2.280.2'
Operating System
  Ubuntu
  20.04.2
  LTS
  
Virtual Environment
  Environment: ubuntu-20.04
  Version: 20210810.1
  Included Software: https://github.com/actions/virtual-environments/blob/ubuntu20/20210810.1/images/linux/Ubuntu2004-README.md
  Image Release: https://github.com/actions/virtual-environments/releases/tag/ubuntu20%2F20210810.1
  
Virtual Environment Provisioner
  1.0.0.0-master-20210802-2

### Is it regression?
Works fine since 3 month
latest /  runner version: '2.279.0'

### Actual behavior

```
E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/main/m/mesa/libegl-mesa0_21.0.3-0ubuntu0.2~20.04.1_amd64.deb  404  Not Found [IP: 52.252.75.106 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
Error: Process completed with exit code 100.
```

### Repro steps

add this step :

```
      - name: Setup wkhtmltopdf
        run: sudo apt-get install wkhtmltopdf;cp /usr/bin/wkhtmltopdf /usr/local/bin/wkhtmltopdf
```

**Comment by al-cheb** [comment]
Hello @gaetanbuellet
Please make sure that you have run `sudo apt-get update` command before installation according to [documentation](https://docs.github.com/en/actions/using-github-hosted-runners/customizing-github-hosted-runners#installing-software-on-ubuntu-runners).

**Comment by gaetanbuellet** [comment]
Thanks a lot, it forks fine now. :heart:
