### ISSUE TITLE
ubuntu2004 fails to install git-email due to missing ppa:git-core apt sources

### ISSUE THREAD

**Issue by stefanha** [actions/virtual-environments#3923]
### Description

If a workflow tries to install the `git-email` package, there is a failure because the ppa:git-core apt sources from which git was installed has been removed in the ubuntu2004 image:
```yml
- name: Install git-email
  run: sudo apt-get install -qy git-email
```
The following `apt-get` error occurs:
```
The following packages have unmet dependencies:
 git-email : Depends: git (< 1:2.25.1-.) but 1:2.32.0-1~ppa0~ubuntu20.04.1 is to be installed
             Recommends: libemail-valid-perl but it is not going to be installed
```
The ubuntu2004 scripts remove the ppa:git-core repository here:
https://github.com/actions/virtual-environments/blob/main/images/linux/scripts/installers/git.sh#L27

@dibir-magomedsaygitov This is a regression introduced by commit https://github.com/actions/virtual-environments/commit/d1de678b65e3c6f6adee1297afc90c18cd867198

### Virtual environments affected

- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [X] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019

### Image version and build link

ubuntu2004 20210810.1

### Is it regression?

Yes, introduced by https://github.com/actions/virtual-environments/commit/d1de678b65e3c6f6adee1297afc90c18cd867198

### Expected behavior

The ppa:git-core ppa from which the `git` package was installed should be available so further git-related packages can be installed without dependency conflicts. Resolving the dependency conflict manually is time-consuming and not user-friendly. Furthermore, this is a regression because ppa:git-core used to be available in the image.

### Actual behavior

The ppa:git-core ppa is removed when the image is built. Attempts to install git-related packages can fail with dependency conflicts because apt tries to install Ubuntu system git packages instead of the ppa:git-core packages.

### Repro steps

Try this:
```yml
- name: Install git-email
  run: sudo apt-get install -qy git-email
```

**Comment by al-cheb** [comment]
Hi, @stefanha 

We intentionally removed this repo in the https://github.com/actions/virtual-environments/pull/3095 PR. Please add manually the repo in runtime.

```
jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
        - run: |
            GIT_REPO="ppa:git-core/ppa"
            sudo add-apt-repository $GIT_REPO -y
            sudo apt-get update
            sudo apt-get install -qy git-email
```

**Comment by stefanha** [comment]
> Hi, @stefanha
> 
> We intentionally removed this repo in the #3095 PR. Please add manually the repo in runtime.
> 
> ```
> jobs:
>   build:
>     name: Build
>     runs-on: ubuntu-20.04
>     steps:
>         - run: |
>             GIT_REPO="ppa:git-core/ppa"
>             sudo add-apt-repository $GIT_REPO -y
>             sudo apt-get update
>             sudo apt-get install -qy git-email
> ```

I know how to work around this but removing the git apt sources isn't user-friendly.

Although the points in #2951 seem valid to me, they ignore that users will need to troubleshoot dependency problems due to this policy of removing apt sources that have installed packages. That troubleshooting is time-consuming and you'll get more bug reports like this one in the future from other users.

Please either use system git if you want to minimize apt sources or keep the ppa:git-core apt sources in the image if you really need that version of git.

A more long-term solution would be to see if apt sources can be configure or apt can be extended to support smart updates that avoid refreshing unnecessarily or failing due to network errors from non-essential apt sources.

**Comment by al-cheb** [comment]
> Although the points in #2951 seem valid to me, they ignore that users will need to troubleshoot dependency problems due to this policy of removing apt sources that have installed packages. Troubleshooting is time-consuming and you'll get more bug reports like this one in the future from other users.
> 
> Please either use system git if you want to minimize apt sources or keep the ppa:git-core apt sources in the image if you really need that version of git.
> 
> A more long-term solution would be to see if apt sources can be configured or apt can be extended to support smart updates that avoid refreshing unnecessarily or failing due to network errors from non-essential apt sources.

We used to this approach and installed from official repo, but git version is outdated, that's why we got requests to update to the latest version - https://github.com/actions/virtual-environments/issues/3923#issuecomment-901743833. The best approach for our mind is to pre-installed the latest one and remove ppa repo.

**Comment by stefanha** [comment]
Ideally the failed job output would contain a message saying you may need to manually enable repos that were used in the creation of this image. That would save time when people hit this type of issue in the future.

Also, this change broke existing GitHub Actions workflows. Maybe only introduce breaking changes when releasing new virtual environment so existing ones aren't affected?

Thanks for the discussion. I understand there's no perfect solution and I just wanted to share drawbacks I see with this policy.

**Comment by al-cheb** [comment]
Thank you. We will think about it.
