### ISSUE TITLE
windows-2019 image claims to have msvc 2015 c++ compiler (v140 tools) but it doesn't work

### ISSUE THREAD

**Issue by mucki-at** [actions/virtual-environments#3925]
### Description

Trying to build a project using the MSVC 2015 c++ compiler in visual studio 2019 ('v140' toolset). The description of available software says that this component is supposed to be installed, yet it seems to be missing on the agent:

    Project "D:\a\1\b\CMakeFiles\3.21.1\VCTargetsPath.vcxproj" on node 1 (default targets).
    C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VC\v160\Microsoft.CppBuild.targets(439,5): error MSB8020: The build tools for Visual Studio 2015 (Platform Toolset = 'v140') cannot be found. To build using the v140 build tools, please install Visual Studio 2015 build tools.  Alternatively, you may upgrade to the current Visual Studio tools by selecting the Project menu or right-click the solution, and then selecting "Retarget solution". [D:\a\1\b\CMakeFiles\3.21.1\VCTargetsPath.vcxproj]
    Done Building Project "D:\a\1\b\CMakeFiles\3.21.1\VCTargetsPath.vcxproj" (default targets) -- FAILED.

### Virtual environments affected

- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [X] Windows Server 2019

### Image version and build link

Virtual Environment
Environment: windows-2019
Version: 20210810.1
Included Software: https://github.com/actions/virtual-environments/blob/win19/20210810.1/images/win/Windows2019-Readme.md
Image Release: https://github.com/actions/virtual-environments/releases/tag/win19%2F20210810.1

### Is it regression?

unknown

### Expected behavior

building works using toolset v140

### Actual behavior

toolset is not found

### Repro steps

try to run cmake with '-G "Visual Studio 16 2019" -T v140 '

**Comment by al-cheb** [comment]
Hello, @mucki-at 
We will take a look at the issue.

**Comment by dibir-magomedsaygitov** [comment]
Hello @mucki-at. We tried to reproduce the issue with the given reprosteps, but our [run ](https://github.com/dibir-magomedsaygitov/stm-actor/runs/3372258627?check_suite_focus=true)successfully passed. See the [workflow file](https://github.com/dibir-magomedsaygitov/stm-actor/blob/master/.github/workflows/test-123.yml). Could you please provide link to the your failed build or update reprosteps?

**Comment by mucki-at** [comment]
Yes, I tried a few more things yesterday and found that regular desktop
builds work fine, but UWP/store builds do not work with downlevel toolsets:

cmake -G "Visual Studio 16 2019" -DCMAKE_SYSTEM_NAME=Windows -T v140 #
works fine
cmake -G "Visual Studio 16 2019" -DCMAKE_SYSTEM_NAME=Windows -T v141 #
works fine
cmake -G "Visual Studio 16 2019" -DCMAKE_SYSTEM_NAME=Windows -T v142 #
works fine


cmake -G "Visual Studio 16 2019" -DCMAKE_SYSTEM_NAME=WindowsStore -T v140 #
DOES NOT WORK
cmake -G "Visual Studio 16 2019" -DCMAKE_SYSTEM_NAME=WindowsStore -T v141 #
DOES NOT WORK
cmake -G "Visual Studio 16 2019" -DCMAKE_SYSTEM_NAME=WindowsStore -T v142 #
works fine

msvc2015 with UWP is an iffy case and I don't really need it, but msvc2017
with UWP I do need and it definitely
works on my devbox.

Also: Is there a "test" agent pool for developing new scripts? It is very
annoying having to wait in the queue
15 minutes every time, just for a job to immediately fail.

**Comment by dibir-magomedsaygitov** [comment]
Hello @mucki-at. Thank you for your reply. We were able to reproduce the issue. Unfortunately, Visual Studio Enterprise 2019	version 16.11.31605.320 doesn't support `C++(v140) Universal Windows Platform tools` (see related [discussion](https://developercommunity.visualstudio.com/t/cannot-build-c-app-depending-on-v140-tools-invalid/55585)). But after adding `C++(v141) Universal Windows Platform tools` project was successfully built. 
As for waiting 15 minutes in the queue - how often it happens? Looking forward for your reply.

**Comment by mucki-at** [comment]
Cool. Does this mean you will update the windows-2019 VMs to include that
feature? IF so, how long will that take?

I am inside microsoft so I am running into the 200 parallel job limit all
the time. For a full build (which takes about an hour) waiting a bit in
queue is inconsequential, but for setting up a new pipeline it is really
annoying. I would like a "sandbox" pool which has the exact same VMs as the
regular one, but has a job run limit of 5 minutes or so, specifically to
quickly test the basic job setup (YAML syntax, typos in scripts, etc ...).

**Comment by dibir-magomedsaygitov** [comment]
Hello @mucki-at. I've prepared PR to add `ComponentGroup.UWP.VC.v141` component to Visual Studio 2019 and it should be available with the next week's rollout. I'll post an update message.
As for job limit - you should contact your organization's administrator and ask to increase parallel job limit.

**Comment by mucki-at** [comment]
Thank you for fixing that, I am looking forward to the update. As for the
job limit - this is the generic "Microsoft" pool (ie: not self hosted or
paid for by a specific team). I thought you guys managed that, but I guess
it is someone else. I don't think they will change things, but I will
inquire.

**Comment by mucki-at** [comment]
I see that your change made it into "main". Do you have any idea when the
next release will be created for windows-2019?

**Comment by dibir-magomedsaygitov** [comment]
Hello @mucki-at. Sorry for the late reply. We have started deployment of Windows-2019 and changes should be available later next week. I'll post an update message.

**Comment by mucki-at** [comment]
Thanks for the update!

**Comment by dibir-magomedsaygitov** [comment]
Hello @mucki-at. Windows-2019 with `ComponentGroup.UWP.VC.v141` has been deployed. I'm going to close this issue. In case of any questions feel free to contact us.
