### ISSUE TITLE
windows-2019 20210810.1 running slower than previous versions

### ISSUE THREAD

**Issue by beechtom** [actions/virtual-environments#3926]
### Description

Our RSpec tests running on windows-2019 runners have been seeing degraded performance since the runner was updated to use 20210810.1. Previously, tests on Windows finished on average within 25 minutes, but are now taking an average of 40 minutes.

We also noticed that a previous RSpec test that connected to the runner itself over WinRM is now consistently failing without any changes on our end. We suspect this might be due to degraded performance on the runner causing our tests to throw a hardcoded timeout error, as the runner is responding to the connection too slowly now.

Relevant workflow is [here](https://github.com/puppetlabs/bolt/actions/workflows/windows.yaml) under the "Agentless" job. [This job](https://github.com/puppetlabs/bolt/runs/3326607864?check_suite_focus=true) is the last to run with 20210803.1 and [this job](https://github.com/puppetlabs/bolt/runs/3344604675?check_suite_focus=true) is the first to run with 20210810.1.

### Virtual environments affected

- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [X] Windows Server 2019

### Image version and build link

20210810.1

### Is it regression?

20210803.1

### Repro steps

Not sure if this is reproducible with other workflows, but at least for ours:

1. Run the [Windows workflow](https://github.com/puppetlabs/bolt/actions/workflows/windows.yaml) on 20210810.1
2. Compare to running the same workflow on 20210803.1

**Comment by al-cheb** [comment]
Hello, @beechtom 
We will take a look at the issue.

**Comment by al-cheb** [comment]
@beechtom, Could you please run this https://github.com/actions/virtual-environments/blob/main/images/win/scripts/Installers/Run-NGen.ps1 script before test and provide a result?

**Comment by al-cheb** [comment]
@beechtom, Any updates?

**Comment by al-cheb** [comment]
I'm going to close the issue until further clarifications from your side.
Feel free to contact us at any time.
