### ISSUE TITLE
Update Visual Studio Enterprise 2019

### ISSUE THREAD

**Issue by arttet** [actions/virtual-environments#3927]
### Tool name

Visual Studio Enterprise 2019

### Tool license

Microsoft Visual Studio 2019 Licensing

### Add or update?

- [ ] Add
- [X] Update

### Desired version

16.11.0

### Virtual environments affected

- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [X] Windows Server 2019

### Can this tool be installed during the build?

```bash
No
```

### Are you willing to submit a PR?

Yes

**Comment by al-cheb** [comment]
Hi, @arttet 
Waiting for the new deployment with https://github.com/actions/virtual-environments/pull/3905 the latest VS 2019 update. It should be available by tomorrow.

**Comment by al-cheb** [comment]
The new images have been deployed.

```
Run vswhere.exe -latest
Visual Studio Locator version 2.8.4+ff0de50053 [query version 2.7.3111.17308]
Copyright (C) Microsoft Corporation. All rights reserved.

instanceId: 262ec23d
installDate: 8/15/2021 3:43:22 AM
installationName: VisualStudio/16.11.0+31605.320
installationPath: C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise
installationVersion: 16.11.31605.320
```

**Comment by arttet** [comment]
Thank you so much
