### ISSUE TITLE
azure.archive.ubuntu.com 404

### ISSUE THREAD

**Issue by maennchen** [actions/virtual-environments#3928]
### Description

`sudo apt-get install -y wkhtmltopdf poppler-utils`

Produces

```
E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/main/m/mesa/libegl-mesa0_21.0.3-0ubuntu0.2~20.04.1_amd64.deb  404  Not Found [IP: 52.252.75.106 80]
```

### Virtual environments affected

- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [X] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019

### Image version and build link

20210816.1

https://github.com/jshmrtn/hygeia/pull/424/checks?check_run_id=3369027576

### Is it regression?

https://github.com/jshmrtn/hygeia/runs/3358451145?check_suite_focus=true

### Expected behavior

It should install without any errors.

### Actual behavior

Produces an error

### Repro steps

1. sudo apt-get install -y wkhtmltopdf poppler-utils

**Comment by al-cheb** [comment]
Hey, @maennchen 
Hello @gaetanbuellet
Please make sure that you have run sudo apt-get update command before installation according to [documentation](https://docs.github.com/en/actions/using-github-hosted-runners/customizing-github-hosted-runners#installing-software-on-ubuntu-runners).

**Comment by maennchen** [comment]
That solved the issue 👍
