### ISSUE TITLE
Ability to configure virtual display size

### ISSUE THREAD

**Issue by wadeww** [actions/virtual-environments#393]
I'm trying to run e2e tests for an electron app in the macOS runner using Spectron. I have some tests that are failing because the window size is too small even though I've maximized the application. It looks like the virtual display size is being set to **1176 x 694**. Is there any way to configure the default display size in the macOS runner (or any of the virtual environments)?

**Area for Triage**: 
Apple

**Question, Bug, or Feature?**: 
Question

**Virtual environments affected**
- [x] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Comment by alepauly** [comment]
We should start by investigating any side-effects of this.

**Comment by al-cheb** [comment]
Hello, @wadeww 
 
We have extended ability to set screen resolution size to a maximum size - 2560 x 1600.

Example how to change in runtime: 
```
- name: screen resolution
      run: |
        system_profiler SPDisplaysDataType | grep Resolution
        "/Library/Application Support/VMware Tools/vmware-resolutionSet" 2560 1440
        system_profiler SPDisplaysDataType | grep Resolution
```

![s - Copy](https://user-images.githubusercontent.com/47745270/80311948-3c7b4f80-87eb-11ea-9b37-918103d553c7.JPG)


Feel free to open the thread if you have any concerns.

**Comment by gokultw** [comment]
How to change resolution on Ubuntu ?

**Comment by lemnis** [comment]
Ubuntu doesn't have a (virtual) screen as far as I know 😉  https://github.com/actions/runner-images/discussions/5943

**Comment by souravd000** [comment]
Will it work for the **windows server 2019** also?
