### ISSUE TITLE
Add Microsoft.ACE.OLEDB.12.0

### ISSUE THREAD

**Issue by sbollap1** [actions/virtual-environments#3941]
### Tool name

Microsoft.ACE.OLEDB.12.0  Microsoft Office 12.0 Access Database Engine OLE DB Provider

### Tool license

Microsoft

### Add or update?

- [X] Add
- [ ] Update

### Desired version

12.0

### Brief description of tool

As of Aug 2021 Windows-2019 image doesn't have Microsoft.ACE.OLEDB.12.0  Microsoft Office 12.0 Access Database Engine OLE DB Provider. Appreciate if you can update this Microsoft hosted agent

### Virtual environments affected

- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [X] Windows Server 2019

### Are you willing to submit a PR?

No

**Comment by Darleev** [comment]
Hello @sbollap1,
We will consider a possibility to add the tool.

**Comment by miketimofeev** [comment]
@sbollap1 could you try to install the package using the following snippet? Does it work for you?
```
Install-Binary -Url "https://download.microsoft.com/download/2/4/3/24375141-E08D-4803-AB0E-10F2E3A07AAA/AccessDatabaseEngine_X64.exe" -Name "AccessDatabaseEngine_X64.exe" -ArgumentList ("/quiet", "/norestart")
(New-Object system.data.oledb.oledbenumerator).GetElements() | select SOURCES_NAME, SOURCES_DESCRIPTION
```

**Comment by miketimofeev** [comment]
I'm going to close the issue.
Please feel free to contact us if you have any concerns.
Thank you!
