### ISSUE TITLE
(Public Beta) Windows Server 2022 with Visual Studio 2022 is now available

### ISSUE THREAD

**Issue by maxim-lobanov** [actions/virtual-environments#3949]
### Windows Server 2022 availability 🚀 
Hello everyone!

We are happy to announce that Windows Server 2022 is available for GitHub Actions and Azure DevOps users 🥳  
You can use `windows-2022` image label in your YAML to select this image.

#### GitHub Actions
```yaml
jobs:
  jobName:
    runs-on: windows-2022
```

#### Azure DevOps
```yaml
jobs:
- job: jobName
  pool:
    vmImage: 'windows-2022'
```

### "Beta" status
The image is marked as "beta" for now. It means some software can be unstable on the new platform. Also there could be queueing issues as the capacity will be balanced only throughout the next weeks.
Known issues:
- Some build software is not compatible with Visual Studio 2022 yet (For example: Bazel)
- Some Azure DevOps tasks don't work on the new platform properly yet: VSBuild, MSBuild, UsePython (PyPy only)

**Please report any problems with the new image to this repository.**
**Any issues related to Azure DevOps tasks should be reported to https://github.com/microsoft/azure-pipelines-tasks.**

### Software differences
The full documentation of Windows Server 2022 image can be found in [image README](https://github.com/actions/virtual-environments/blob/main/images/win/Windows2022-Readme.md).  
The software set is different between Windows Server 2019 and 2022. We have deprecated some legacy software with low usage and temporarily disabled software that is not supported on the new platform yet. Also, for tools with multiple installed versions we have reconsidered the list of versions based on usage.

Please find differences in the table below:

| Tool name | Windows 2019 | Windows 2022 | Notes |
| - | - | - | - |
| Windows Server | 2019&nbsp;(10.0.17763&nbsp;Build&nbsp;2061) | 2022&nbsp;(10.0.20348&nbsp;Build&nbsp;112) |  |
| Visual Studio | 2019 (16.10.31515.178) <br> Workloads: [recommended + custom + wix components](https://github.com/actions/virtual-environments/blob/main/images/win/Windows2019-Readme.md#workloads-components-and-extensions) | 2022 Preview (17.0.31521.260) <br>Workloads: recommended set | Our policy is installing one VS version per platform. On Windows Server 2022, we install only VS 2022 (it is in Preview for now but will be released in future).<br>If your use-case requires using VS 2019, continue using Windows Server 2019 image. We don't have plans to deprecate it in near future.|
| Python | Default version: 3.7.x<br>Architectures: x64 & x86<br>Pre-cached versions: 2.7, 3.5, 3.6, 3.7, 3.8, 3.9 | Default version: 3.9.x<br>Architectures: x64<br>Pre-cached versions: 3.7, 3.8, 3.9 | On GitHub Actions, [actions/setup-python](https://github.com/actions/setup-python) can install any version on-flight so this change doesn't impact users |
| PyPy | 2.7, 3.6, 3.7 |2.7, 3.7 | Version 3.6 is officially deprecated in favor of 3.7 and is not updated anymore. |
| Ruby | Default version: 2.5.x<br>Pre-cached versions: 2.4, 2.5, 2.6, 2.7, 3.0| Default version: 3.0.x<br>Pre-cached versions: 2.7, 3.0 | On GitHub Actions, [ruby/setup-ruby](https://github.com/ruby/setup-ruby) can install any version on-flight so this change doesn't impact users |
| Go | Default&nbsp;version:&nbsp;1.15.x<br>Pre-cached versions: 1.13, 1.14, 1.15, 1.16 | Default&nbsp;version:&nbsp;1.16.x<br>Pre-cached versions: 1.15, 1.16 | If your use-case requires using any of these versions, consider using tasks to install Go on-flight: <br>- [actions/setup-go](https://github.com/actions/setup-go) (GitHub Actions)<br>- [Go Tool Installer](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/tool/go-tool?view=azure-devops) (Azure DevOps) |
| Java | Default version: 8 <br>Pre-installed versions: 8, 11, 13 | Default version: 8 <br> Pre-installed versions: 8, 11 | Our [policy](https://github.com/actions/virtual-environments/blob/main/docs/software-and-images-guidelines.md#software-and-images-support-policy) is pre-installing only LTS versions of Java. if your use-case requires using non-LTS Java version, please consider using tasks to install it on-flight: <br>- [actions/setup-java](https://github.com/actions/setup-java) (GitHub Actions)<br>- [Java Tool Installer](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/tool/java-tool-installer?view=azure-devops) (Azure DevOps)|
| Android | Build-tools: >= 19.x <br> Platforms: >= 19.x <br> CMake: 3.10.2, 3.18.1<br>Google APIs: 21, 22, 23, 24 <br> NDK: 21, 22 | Build-tools: >= 27.x <br> Platforms: >= 27.x <br> CMake: 3.18.1<br>Google APIs: - <br> NDK: 21, 22 | |
| .NET Core SDK | 2.1, 3.1, 5.0 | 3.1, 5.0 | .NET Core 2.1 End Of Support [is scheduled](https://dotnet.microsoft.com/platform/support/policy/dotnet-core#lifecycle) on  August 21, 2021. <br> Please consider using tasks to install any version on-flight: <br>- [actions/setup-dotnet](https://github.com/actions/setup-dotnet) (GitHub Actions)<br>- [Use .NET Core](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/tool/dotnet-core-tool-installer?view=azure-devops) (Azure DevOps)|
| Az modules | Installed: 6.1.0 <br> Zipped: 1.0.0, 1.6.0, 2.3.2, 2.6.0, 3.1.0, 3.5.0, 3.8.0, 4.3.0, 4.4.0, 4.7.0, 5.5.0, 5.9.0, 6.1.0 | Installed: 6.1.0 <br> Zipped: - | If your use-case requires using any of these versions, consider using tasks to install Az modules on-flight: <br>- [azure-powershell-action](https://github.com/marketplace/actions/azure-powershell-action) (GitHub Actions)<br>- [Azure PowerShell](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-powershell?view=azure-devops) (Azure DevOps) |
| MSYS2 | [A lot of pre-installed msys packages](https://github.com/actions/virtual-environments/blob/99fa3a3396bfa39d6a059f43e44f36df811133ef/images/win/toolsets/toolset-2019.json#L176) | Only pure MSYS2 is installed. No additional packages | On Windows Server 2016 and 2019 we had a lot of pre-installed MSYS2 packages. We had [a long discussion](https://github.com/actions/virtual-environments/issues/1572#issue-698526141) about "pre-installing them" vs "installing in runtime and caching". Our recommendation is using [official setup-msys2 action](https://github.com/marketplace/actions/setup-msys2) to install packages on-flight and cache them.  |

The following software were not installed on Windows Server 2022 images by default: Miniconda, Google Cloud SDK, InnoSetup, NSIS, Perl, sbt, Cloud Foundry CLI, BizTalk Server and Client, WebPlatformInstaller, Windows Driver Kit

**Comment by Mint-6263** [comment]
:blush:

**Comment by robertmclaws** [comment]
Can you please update the Visual Studio version on this image to Preview 4? Thanks!

**Comment by miketimofeev** [comment]
Hi @robertmclaws!
We always install the latest VS version available at the moment of image generation, so the preview 4 image should be accessible later this week.

**Comment by robertmclaws** [comment]
Thanks Mike! It's really cool that you folks have automated these releases and such... thanks so much for your efforts! 

Would be really nice though if you folks could put out image updates day-and-date with Visual Studio releases, especially around major versions (like Release Candidates). OR give us an easy way to trigger VS updates from a task. It's tough to meet our deadlines when builds that run locally won't run in CI because VS releases in our pipeline are a week behind.

Thanks again!

**Comment by miketimofeev** [comment]
@robertmclaws unfortunately, we are usually not aware of such major changes in VS beforehand. It would be great if you or any other VS user would create an issue here in advance next time so we can push the critical update on time rather than follow up our usual deployment schedule (start on Monday and finish on Wednesday-Thursday).

**Comment by miketimofeev** [comment]
@robertmclaws the new image with update VS has been deployed

**Comment by jackbond** [comment]
Does the image have the .NET Core SDK 6? In the table above, it only indicates 3.1 and 5, which seems strange.

**Comment by robertmclaws** [comment]
By virtue of having Visual Studio 2022 on there, it should also have the .NET 6 SDK that ships with that version.

Having said that, I always have a ".NET Core SDK" task in my pipeline that installs the version specified in global.json. Ensures I'm using the right version no matter what is on the box.

**Comment by jackbond** [comment]
You guys might want to make that explicit in your table. It's possible to install Visual Studio without .NET support isn't it?

**Comment by MaksimZhukov** [comment]
Hello @jackbond!
The Windows Server 2022 image contains .NET Core SDK 6. Please find more details about included software in the [Windows2022-Readme.md](https://github.com/actions/virtual-environments/blob/main/images/win/Windows2022-Readme.md#net-core-sdk) file

**Comment by MSP-Greg** [comment]
Please consider installing the base-devel and compression groups to the MSYS2 installation on Windows-2022.  Both were installed on previous images.

A few issues:

1. The base-devel group is shared by the separate build tool chains.  For example, mingw or ucrt gcc won't run unless MSYS2 base-devel is installed.  It contains many build tools that are platform/compiler agnostic.

2. Without compression, there's no tar.  Pretty common command for CI.  I haven't checked for a while, but at one time the Windows tar did not support all the formats that MSYS2/*nix tar does.

3. At some point, parity with Ubuntu or WSL2 should be considered.

4. Working with Ruby, the time to install ucrt64 or mingw64 is one half the time it takes to install the portion of the MSYS2 base-devel group that we need.  The time needed is to extract the files from a single file (which we create), so caching won't improve the time much.

MSYS2 base-devel packages:
```
asciidoc            diffutils           pacman *
autoconf            dos2unix            patch
autoconf2.13        file                patchutils
autogen             flex                perl *
automake-wrapper    gawk *              pkgconf
automake1.10        gdb                 pkgfile
automake1.11        gettext *           quilt
automake1.12        gettext-devel       reflex
automake1.13        gperf               scons
automake1.14        grep *              sed *
automake1.15        groff               swig
automake1.16        help2man            texinfo
automake1.6         intltool            texinfo-tex
automake1.7         libtool             ttyrec
automake1.8         libunrar            unrar
automake1.9         libunrar-devel      wget *
bison               m4                  xmlto
btyacc              make                
diffstat            man-db              

* Seven packages already installed on Windows-2022
```

**Comment by xavier2k6** [comment]
For anyone interested:

[Visual Studio 2022 hits general availability (GA) on November 8](https://devblogs.microsoft.com/visualstudio/join-us-november-8th-for-the-launch-of-visual-studio-2022/)

[Visual Studio 2022 Launch Event Monday November 8, 2021 | 8:30am PT](https://visualstudio.microsoft.com/launch/)

**Comment by sylveon** [comment]
Is it possible to install the Windows SDK, version 10.0.22000 on those images?

Also, `VSTest` is not listed in the broken tasks but is broken.

**Comment by nesherhh** [comment]
ok, thanks

**Comment by miketimofeev** [comment]
@database64128 @sylveon the image with windows11 SDK will be deployed next week

**Comment by sylveon** [comment]
Awesome, thank you!

**Comment by RolandoMalena** [comment]
Is WSL2 something that can happen on this new agent? One nice use case that we would love to have on our CI pipelines is to have integration testing where we test the integration between our Windows Desktop App and our NodeJS API running on Ubuntu (which is what we use on Production). The former would send data via HTTP requests to the latter.

I would love to be able to run Linux containers in a Windows Agent, so we can ramp our API in a Docker Container and run our Desktop App against it.

**Comment by andreineculau** [comment]
@RolandoMalena  unfortunately there is no wsl2 on Windows Server 2022. Nothing to do with GitHub turning on a switch, it's all about Windows - see https://github.com/microsoft/WSL/issues/6301#issuecomment-858816891

We are many that would be interested in WSL2 and I hope there are alternatives considered by GitHub, but specifically to your case, while I haven't tried it myself but why can't you run your tests against 1. a backend running on wsl1? 2. Or a Docker?

**Comment by RolandoMalena** [comment]
@andreineculau Currently I am unable to run docker within wsl1, the error I get indicates the docker daemon never starts and I haven't figured out how to start it yet. I will keep trying of course.

Another alternative might be to just download the source code and run the API but I would rather not do that if possible.

Here is my test repo with a workflow and some failed runs, feel free to contribute. https://github.com/RolandoMalena/windows_wsl_workflow

**Comment by juanmalm** [comment]
@maxim-lobanov would be possible to include Microsoft.VisualStudio.Component.Windows10SDK.17763 as part of the included software?? We have to keep 17763 as minimum version for our UWP project.

**Comment by julianxhokaxhiu** [comment]
Please consider updating VS2022 to the official release instead of the preview one. Thank you!

**Comment by miketimofeev** [comment]
@julianxhokaxhiu the image rollout has started and will be finished tomorrow.

**Comment by krokofant** [comment]
Any idea when `windows-latest` will point to `windows-2022`? If it will switch just after windows-2022 goes stable then maybe it should be mentioned.

**Comment by miketimofeev** [comment]
@krokofant we are working on a migration plan and will announce the timeline a bit later.

**Comment by miketimofeev** [comment]
We are going to stop treating the image as beta starting from November, 15.
The announcement available here
https://github.com/actions/virtual-environments/issues/4488

**Comment by KVROHITH098** [comment]
I willl do this one do not worry

**Comment by KVROHITH098** [comment]
I have a idea on this Jake.

**Comment by nwaf999** [comment]
H

**Comment by Pyzyryab** [comment]
Hello.

How can I enable on the `windows-2022` machine the support for the C++20 modules support? I need to "enable" this component like if it where selected in the visual studio installer to download it for vstudio.

I am getting this error on my Action, btw: 

```
fatal error C1011: cannot locate standard module interface. Did you install the library part of the C++ modules feature in VS setup? 
```

**Comment by sylveon** [comment]
I would recommend moving away from `import std.core;` and back to `#include <thing>` or `import <thing>;`

The standard library was not modularized for C++20 so you're using a non-standard extension. Using `#include` or `import <thing>;` does not require to install an additional component. If you really need them, you can simply run the VS setup from a powershell script:
```ps1
Set-Location "C:\Program Files (x86)\Microsoft Visual Studio\Installer\"
$InstallPath = "C:\Program Files\Microsoft Visual Studio\2022\Preview"
$componentsToAdd = @(
  # add components here, i don't know the name of the component with the standard library modules
)
[string]$workloadArgs = $componentsToAdd | ForEach-Object {" --add " +  $_}
$Arguments = ('/c', "vs_installer.exe", 'modify', '--installPath', "`"$InstallPath`"",$workloadArgs, '--quiet', '--norestart', '--nocache')
$process = Start-Process -FilePath cmd.exe -ArgumentList $Arguments -Wait -PassThru -WindowStyle Hidden
if ($process.ExitCode -eq 0)
{
    Write-Host "components have been successfully added"
}
else
{
    Write-Host "components were not installed"
    exit 1
}
```

**Comment by Pyzyryab** [comment]
So I must add the modules component, copy paste your script into my project and create a new named action inside the current one?

That location (Set-Location "C:\Program Files (x86)\Microsoft Visual Studio\Installer\") is the real location of the preinstalled msvc2022 on the `windows-2022` machine?

**Comment by sylveon** [comment]
> That location (Set-Location "C:\Program Files (x86)\Microsoft Visual Studio\Installer") is the real location of the preinstalled msvc2022 on the windows-2022 machine?

yes

**Comment by Pyzyryab** [comment]
I found the name of the component, but I am getting a syntax error that I am not able to get rid out of it 

```
Set-Location "C:\Program Files (x86)\Microsoft Visual Studio\Installer\"
$InstallPath = "C:\Program Files\Microsoft Visual Studio\2022\Preview"
$componentsToAdd = @(
    'Microsoft.VisualStudio.Component.VC.Modules.x86.x64'
)
[string]$workloadArgs = $componentsToAdd | ForEach-Object {" --add " +  $_}
$Arguments = ('/c', "vs_installer.exe", 'modify', '--installPath', "`"$InstallPath`"",$workloadArgs, '--quiet', '--norestart', '--nocache')
$process = Start-Process -FilePath cmd.exe -ArgumentList $Arguments -Wait -PassThru -WindowStyle Hidden
if ($process.ExitCode -eq 0)
{
    Write-Host "components have been successfully added"
}
else
{
    Write-Host "components were not installed"
    exit 1
}
```

The output: 
```
$ ./.github/scripts/setup_msvc.ps1 
./.github/scripts/setup_msvc.ps1: line 7: syntax error near unexpected token `)'
./.github/scripts/setup_msvc.ps1: line 7: `$Arguments = ('/c', "vs_installer.exe", 'modify', '--installPath', "`"$InstallPath`"",$workl
```

**Comment by Pyzyryab** [comment]
@sylveon sorry, but I am not being able of make the script works. I get the name of the component directly from the Microsoft page.
Do you think I am missing something?

Thanks!

**Comment by dougmassay** [comment]
Not excited that InnoSetup is no longer included on windows-latest.

**Comment by alexreinking** [comment]
@Pyzyryab -- did you ever solve the C++ modules issue? It's been affecting me, too.
