### ISSUE TITLE
Need a way to work around the GitHub PAT requirement

### ISSUE THREAD

**Issue by samrobillard** [actions/virtual-environments#395]
**Describe the bug**
A GitHub PAT is now a requirement but cannot be used in our shared Azure DevOps. I won't put my own PAT in a pipeline that other people have access to. Is there a workaround for my problem?

**Question, Bug, or Feature?**: 
Question

**Virtual environments affected**
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [X] Windows Server 2019

**Comment by maxim-lobanov** [comment]
Hello,
Currently, it is not possible to generate image without token because GitHub Packages requires PAT to be specified to download public packages.

**Comment by samrobillard** [comment]
Thanks for the quick reply. It seems to be a limitation of GitHub Package Registry.

For Reference: https://github.community/t5/GitHub-API-Development-and/Download-from-Github-Package-Registry-without-authentication/td-p/35255
