### ISSUE TITLE
[windows-2022]  VS2022: missing system runtime libraries

### ISSUE THREAD

**Issue by MehdiChinoune** [actions/virtual-environments#3952]
### Description

I don't if this is related to a missing component from VS2022 or cmake is not ready for VS2022 . 
I get these messages from cmake:

```
CMake Warning at C:/Program Files/CMake/share/cmake-3.21/Modules/InstallRequiredSystemLibraries.cmake:601 (message):
  system runtime library file does not exist:
  'MSVC_REDIST_DIR-NOTFOUND/x64/Microsoft.VC142.CRT/msvcp140.dll'
CMake Warning at C:/Program Files/CMake/share/cmake-3.21/Modules/InstallRequiredSystemLibraries.cmake:601 (message):
  system runtime library file does not exist:
  'MSVC_REDIST_DIR-NOTFOUND/x64/Microsoft.VC142.CRT/vcruntime140.dll'
CMake Warning at C:/Program Files/CMake/share/cmake-3.21/Modules/InstallRequiredSystemLibraries.cmake:601 (message):
  system runtime library file does not exist:
  'MSVC_REDIST_DIR-NOTFOUND/x64/Microsoft.VC142.CRT/concrt140.dll'
```

I don't see these messages on my system, but I have VS2019 installed. Maybe cmake is picking these libraries from VS2019?!

### Virtual environments affected

- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

windows-2022: 20210819.7
https://github.com/MehdiChinoune/makhber/runs/3402633594 (Configuring)

### Repro steps

include this line in a CMakeLists.txt file:
```
include(InstallRequiredSystemLibraries)
```

**Comment by Darleev** [comment]
Hello @MehdiChinoune,
Thank you for the report.
We will investigate the issue.

**Comment by MehdiChinoune** [comment]
I have created a minimum reproducer here: https://github.com/MehdiChinoune/vs22_libs

**Comment by MehdiChinoune** [comment]
I think this issue is related to cmake. First it treats VS 17.0 as v142 which is not correct, second v143 is not yet supported by InstallRequiredSystemLibraries module https://gitlab.kitware.com/cmake/cmake/-/blob/master/Modules/InstallRequiredSystemLibraries.cmake#L240

I have reported two issues to cmake:
https://gitlab.kitware.com/cmake/cmake/-/issues/22585
https://gitlab.kitware.com/cmake/cmake/-/issues/22586
