### ISSUE TITLE
MacOS 11 images contain invalid link to release and software report

### ISSUE THREAD

**Issue by maxim-lobanov** [actions/virtual-environments#3953]
### Description

![image](https://user-images.githubusercontent.com/16715858/130491627-ca337aeb-b69e-459a-b61f-a012742af392.png)
Environment and links contain `macos-11.5` term. It is invalid and all links are broken due to that.

The correct environment should be `macos-11`.

Looks like issue come from our repo and [preimagedata.sh](https://github.com/actions/virtual-environments/blob/main/images/macos/provision/configuration/preimagedata.sh#L11) file.

`label_version=$(echo $os_version | cut -d. -f1,2)` works correctly for `10.14`, `10.15` but for Big Sur, we need to invoke `cut -d. -f1` only.

### Virtual environments affected

- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [X] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

https://github.com/maxim-lobanov/test-repo/runs/3403094283?check_suite_focus=true

### Is it regression?

No

### Repro steps

See above

**Comment by Darleev** [comment]
Hello,
The issue has been fixed.
