### ISSUE TITLE
Issue with Long Path in Windows

### ISSUE THREAD

**Issue by ManuelJNunez** [actions/virtual-environments#3956]
### Description

I was trying to compile all the sources from an [examples repository](https://github.com/rticommunity/rticonnextdds-examples) using the Windows 2016 machine on [my fork](https://github.com/ManuelJNunez/rticonnextdds-examples) using [this configuration](https://github.com/ManuelJNunez/rticonnextdds-examples/blob/9c25577b1547bf523d9e2f963926ae8d981acced/.github/workflows/build.yml).

While compiling, I'm receiving this error with some examples with long names:

> C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\VC\VCTargets\Microsoft.CppBuild.targets(321,5): error MSB3491: Could not write lines to file "x64\Release\content_filtered_topic_string_filter_CXX11_sources\content_.ED6EA502.tlog\content_filtered_topic_string_filter_CXX11_sources.lastbuildstate". The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters. [D:\a\rticonnextdds-examples\rticonnextdds-examples\examples\connext_dds\build\content_filtered_topic_string_filter\c++11\content_filtered_topic_string_filter_CXX11_sources.vcxproj]

It's supposed that the Long Path is enabled (see issue #1052), but with the previous error, it looks that it isn't.

### Virtual environments affected

- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [X] Windows Server 2016
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

20210815.1
https://github.com/ManuelJNunez/rticonnextdds-examples/runs/3399643219

### Is it regression?

No

### Expected behavior

The Long Path should be activated, and the compilation should be completed with no errors due to the path limit.

### Actual behavior

There are some errors due to the path limit.

### Repro steps

See the logs of the [build](https://github.com/ManuelJNunez/rticonnextdds-examples/runs/3399643219). I can't help you with this because we are using private libraries but I'm trying to reproduce it with a simple example.

**Comment by Darleev** [comment]
Hello @ManuelJNunez,
I've verified that longpath feature is enabled on Windows 2016, but just in case: Could you please add the following job at the begging of your workflow?
```
- name: Check LongPathsEnabled
  run: |
     (Get-ItemProperty "HKLM:System\CurrentControlSet\Control\FileSystem").LongPathsEnabled
```
We're looking forward to your reply

**Comment by ManuelJNunez** [comment]
Hello @Darleev

I added the step to the [workflow configuration](https://github.com/ManuelJNunez/rticonnextdds-examples/blob/master/.github/workflows/build.yml). You can find the logs [here](https://github.com/ManuelJNunez/rticonnextdds-examples/runs/3410259200).

Thank you for your response :)

**Comment by Darleev** [comment]
Hello @ManuelJNunez,
I'm going to close the issue until further clarifications from your side.
Feel free to contact us at any time.
