### ISSUE TITLE
Unable to locate 'afxres.h'.  Ensure you have installed the ATL/MFC component of Visual Studio. (Windows-2022 Image)

### ISSUE THREAD

**Issue by xavier2k6** [actions/virtual-environments#3957]
### Description

While testing out the new windows-2022 image for a project.

I receive this error:

```
Starting package 1/101: atlmfc:x64-windows-static-release
Building package atlmfc[core]:x64-windows-static-release...
-- [OVERLAY] Loading triplet configuration from: D:\a\qBittorrent\qBittorrent\triplets_overlay\x64-windows-static-release.cmake
CMake Error at ports/atlmfc/portfile.cmake:7 (message):
  Unable to locate 'afxres.h'.  Ensure you have installed the ATL/MFC
  component of Visual Studio.
Call Stack (most recent call first):
  scripts/ports.cmake:140 (include)


Error: Building package atlmfc:x64-windows-static-release failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: atlmfc:x64-windows-static-release
  Vcpkg version: 2021-08-12-85ab112d5ee102bc6eac8cdbbfdd173a71374e04

Additionally, attach any relevant sections from the log files above.
Error: Process completed with exit code 1.
```

### Virtual environments affected

- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

Current runner version: '2.280.3'
Operating System
  Microsoft Windows Server 2022
  10.0.20348
  Datacenter
Virtual Environment
  Environment: windows-2022
  Version: 20210819.7
  Included Software: https://github.com/actions/virtual-environments/blob/win22/20210819.7/images/win/Windows2022-Readme.md
  Image Release: https://github.com/actions/virtual-environments/releases/tag/win22%2F20210819.7
Virtual Environment Provisioner
  1.0.0.0-master-20210816-1

### Expected behavior

For ATL/MFC latest or even the spectre mitigation versions to be installed by default/picked up

### Repro steps

Unsure....

**Comment by maxim-lobanov** [comment]
Hello @xavier2k6 ,
Do you have a public repro steps or may be minimal project with repro?
It will help us to understand what packages exactly should be installed to resolve the issue

**Comment by xavier2k6** [comment]
@maxim-lobanov

Link to repo:
https://github.com/xavier2k6/qBittorrent/tree/vcpkg_test

Here's the workflow file being used:
https://github.com/xavier2k6/qBittorrent/blob/7562ba7d98609fb9fe285b7484bec1a90c1c69f3/.github/workflows/ci_windows.yaml

Attached logs:
[logs_1711.zip](https://github.com/actions/virtual-environments/files/7038440/logs_1711.zip)

**Comment by xavier2k6** [comment]
FYI

When installing Visual Studio 2022 on my own PC, I noticed:

Under "Desktop development with C++" heading in Visual Studio 2022.
**C++ MFC is not checked by default.**
**C++ ATL  is checked by default.**

**C++ MFC** not being checked by default when being installed on image could be the issue!

**Comment by xavier2k6** [comment]
@maxim-lobanov @dmitry-shibanov
Thank you both for your help, the inclusion of `Microsoft.VisualStudio.Component.VC.ATLMFC.Spectre` in `Windows Server 2022 (20210901 update)` PR https://github.com/actions/virtual-environments/pull/4004 resolved my issue & build completed successfully.

Closing, as resolved.
