### ISSUE TITLE
Add .net core 3.1 sdk to ubuntu-latest vmImage

### ISSUE THREAD

**Issue by parrainc** [actions/virtual-environments#396]
**Tool information**
- Tool name: ubuntu-latest vm Image
- Add or update? Add
- Desired version: .NET Core SDK 3.1.100
- Approximate size: 
- If this is an add request:
  - Brief description of tool: .NET Core 3.1.x SDK
  - URL for tool's homepage: https://dotnet.microsoft.com/download/dotnet-core/3.0

**Area for Triage**:
.NET Core

**Question, Bug, or Feature?**:
Feature

**Virtual environments affected**
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [X] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Can this tool be installed during the build?**
I think by using .netsdk installer task we can get the latest version of the sdk, but I'd be great if we have that built-in in the default vm image.

**Are you willing to submit a PR?**
Sure

**Comment by parrainc** [comment]
Apologize! Just figure there's an open issue in microsoft/azure-pipelines-image-generation repo, which seems to be the same problem I just reported here and looks like it was merged.

**Comment by maxim-lobanov** [comment]
@parrainc , please use this repository to track the issue. `microsoft/azure-pipelines-image-generation` is not maintained anymore.

PR https://github.com/actions/virtual-environments/pull/164 was merged recently, Changes will be delivered in 1 week.

**Comment by parrainc** [comment]
Perfect, thanks for the update!

**Comment by maxim-lobanov** [comment]
Closing the issue since changes were deployed
