### ISSUE TITLE
Different maven version on different system

### ISSUE THREAD

**Issue by slawekjaranowski** [actions/virtual-environments#3969]
### Description

Currently we have (runner version: '2.280.3')

 - ubuntu-latest   - maven `3.8.1`
 - windows-latest  - maven `3.8.1`
 - macos-latest - maven `3.8.2`

So testing on different operating system cause use different maven version. 

### Virtual environments affected

- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [X] Ubuntu 20.04
- [ ] macOS 10.15
- [X] macOS 11
- [ ] Windows Server 2016
- [X] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

  Version: 20210815.1

### Expected behavior

It will be good if all operating system have the same version of maven.

### Repro steps

run `mvn -v` with   runs on os matrix like: [ ubuntu-latest, windows-latest, macOS-latest ]

**Comment by dibir-magomedsaygitov** [comment]
Hello @slawekjaranowski. We reworked installation approach of Maven on Ubuntu and Windows images. Now installed version should be the latest available. Changes will be delivered to VM's with this week's rollout.

**Comment by dibir-magomedsaygitov** [comment]
Hello @slawekjaranowski. Images with updated Maven are available for use. I'm going to close this issue. In case of any questions feel free to contact us.
