### ISSUE TITLE
Update Windows WDK to 22000.1 (Windows 11)

### ISSUE THREAD

**Issue by nibanks** [actions/virtual-environments#3976]
### Tool name

Windows WDK (2200.1)

### Tool license

N/A

### Add or update?

- [ ] Add
- [X] Update

### Desired version

22000.1

### Brief description of tool

https://docs.microsoft.com/en-us/windows-hardware/drivers/download-the-wdk has the WDK/SDK for Windows 11 available to install.

### URL for tool's homepage

https://docs.microsoft.com/en-us/windows-hardware/drivers/download-the-wdk

### Virtual environments affected

- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [X] Windows Server 2019
- [X] Windows Server 2022

### Are you willing to submit a PR?

Possibly

**Comment by MaksimZhukov** [comment]
Hello @nibanks!
Thank you for the request, we will take a look

**Comment by al-cheb** [comment]
The new image has been deployed with WDK 11.
