### ISSUE TITLE
PostgreSQL repository sources removed - unable to install extensions

### ISSUE THREAD

**Issue by alextech** [actions/virtual-environments#3977]
### Description

Is removal of postgresql apt sources really necessary at https://github.com/actions/virtual-environments/pull/3091 ?

Postgresql integration tests rely on installing extensions to the database. PostGIS is a common one.
But trying to install them without original repository downloads not only incompatible versions from distribution's main repository, but also conflicting lower version of postgres-12 is installed in parallel with existing working version 13. 

As first step in all builds I have to readd the sources and rerun repository synchronization, which, besides being not obvious to do, adds time and bandwidth to the build run:

```
#####
## This is to undo removal of postgres repository sources that 
## https://github.com/actions/virtual-environments/blob/main/images/linux/scripts/installers/postgresql.sh
## end of the script removes
######
REPO_URL="https://apt.postgresql.org/pub/repos/apt/"
echo "deb $REPO_URL `lsb_release -cs`-pgdg main" | sudo tee /etc/apt/sources.list.d/pgdg.list
sudo apt-get update

sudo apt-get -y install postgresql-13-postgis-3
sudo -u postgres psql -c "create extension postgis" integration_test_db
```

### Virtual environments affected

- [ ] Ubuntu 16.04
- [X] Ubuntu 18.04
- [X] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

20210816.1

### Expected behavior

Can install postgres extensions to complete integration tests.

### Actual behavior

Because sources for currently installed postgres version are removed, not only incompatible versions are downloaded from main repository, conflicting lower version of postgres is installed in parallel with existing working version.

### Repro steps

sudo apt-get -y install postgresql-13-postgis-3
sudo -u postgres psql -c "create extension postgis" integration_test_db

**Comment by dibir-magomedsaygitov** [comment]
Hello @alextech,
Using apt repositories brings a bunch of problems and potential risks for the GitHub Actions CI environment so we have reduced the number of apt sources. For more information, please see this [issue](https://github.com/actions/virtual-environments/issues/2951).

**Comment by dibir-magomedsaygitov** [comment]
I'm going to close this issue. Feel free to contact us in case of any questions.
