### ISSUE TITLE
incorrect PATH and HOMEBREW_* vars

### ISSUE THREAD

**Issue by andreineculau** [actions/virtual-environments#3981]
### Description

`PATH` and `HOMEBREW_*` vars are surrounded by literal double quotes

```
$ cat /etc/environment | grep '"'
PATH="/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:/home/runner/.local/bin:/opt/pipx_bin:/usr/share/rust/.cargo/bin:/home/runner/.config/composer/vendor/bin:/usr/local/.ghcup/bin:/home/runner/.dotnet/tools:/snap/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin"
HOMEBREW_PREFIX="/home/linuxbrew/.linuxbrew"
HOMEBREW_CELLAR="/home/linuxbrew/.linuxbrew/Cellar"
HOMEBREW_REPOSITORY="/home/linuxbrew/.linuxbrew/Homebrew"
```

`/etc/environment` is evaluated by PAM, and it's supposed to be [a simple KEY=VALUE store](http://www.linux-pam.org/Linux-PAM-html/sag-pam_env.html), so including `FOO="BAR"` in `/etc/environment` is not the equivalent of `export FOO="BAR"` in the shell, but of `export FOO=\"BAR\"` !

So running `$HOMEBREW_PREFIX/bin/brew config` complains that it cannot find `"/home/linuxbrew/.linuxbrew"/bin/brew`.

I believe this might be new behavior due to the recent https://github.com/actions/virtual-environments/pull/3920 . ping @al-cheb @maxim-lobanov @miketimofeev

### Virtual environments affected

- [X] Ubuntu 16.04
- [X] Ubuntu 18.04
- [X] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

20210816.1

### Expected behavior

`$HOMEBREW_PREFIX/bin/brew config` succeeds

### Actual behavior

`$HOMEBREW_PREFIX/bin/brew config` fails with command not found

### Repro steps

Run `$HOMEBREW_PREFIX/bin/brew config`

**Comment by al-cheb** [comment]
Hey, @andreineculau 
Thank you for mentioned about the issue. I have prepared the https://github.com/actions/virtual-environments/pull/3984 PR to remove quotes around HOMEBREW_* env vars. 

By default on Ubuntu PATH contains double quotes like:
```
$ cat /etc/environment
PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin"
```

That's why we redefine the PATH env var with the same values, but without double quotes:
```
cat /etc/environment | grep ^PATH
PATH="/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:/home/runner/.local/bin:/opt/pipx_bin:/usr/share/rust/.cargo/bin:/home/runner/.config/composer/vendor/bin:/usr/local/.ghcup/bin:/home/runner/.dotnet/tools:/snap/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin"
PATH=/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:/home/runner/.local/bin:/opt/pipx_bin:/usr/share/rust/.cargo/bin:/home/runner/.config/composer/vendor/bin:/usr/local/.ghcup/bin:/home/runner/.dotnet/tools:/snap/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
```

**Comment by andreineculau** [comment]
Thanks!
I've backtracked the fix to PATH to https://github.com/actions/virtual-environments/pull/1970

At first sight, I would have said that my suggestion to remove the quotes from HOMEBREW vars is wrong. Now I'm simply confused about the behavior and the quoted-by-default PATH.

I leave it to you to close this as you see fit, but afaics the PR closes this issue.

**Comment by al-cheb** [comment]
@andreineculau , Should be fixed now:
![image](https://user-images.githubusercontent.com/47745270/131872270-03c70846-69e1-464d-9c90-93706f73b994.png)

**Comment by andreineculau** [comment]
Confirmed. Thanks!
