### ISSUE TITLE
Windows Server 2022 still defaults to non-Az PowerShell modules

### ISSUE THREAD

**Issue by AtOMiCNebula** [actions/virtual-environments#3986]
### Description

Any chance the Az PowerShell modules can replace the 2+ year old versions of Azure/AzureRM modules on-path for the new Server 2022 image?  Introducing a new agent image is as good of an opportunity as you're going to get to make breaking changes like this.  I'm not against keeping older versions pre-cached in the image, I just wish Az v6.1.0 could be the one on-path, instead of AzureRM v2.1.0... ☹️

### Virtual environments affected

- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

20210819.7

### Is it regression?

n/a

### Repro steps

Compare:
* Windows Server 2019 Azure PowerShell Modules: https://github.com/actions/virtual-environments/blob/main/images/win/Windows2019-Readme.md#azure-powershell-modules
* Windows Server 2022 Azure PowerShell Modules: https://github.com/actions/virtual-environments/blob/main/images/win/Windows2022-Readme.md#azure-powershell-modules

**Comment by maxim-lobanov** [comment]
Hello @AtOMiCNebula , we would be happy to get rid of legacy Azure / AzureRM modules on images but unfortunately, we have to keep them to support some Azure DevOps tasks and other software that depends on it.

There is a big set of Azure related tasks for Azure DevOps (presented here https://github.com/microsoft/azure-pipelines-tasks/tree/master/Tasks) that still depend on Azure / AzureRM and will stop to work after changing default. Per discussion with related team, we still need to keep them working as previously on the new platform. That is the reason why we will keep Azure / AzureRM modules as default on Windows Server 2022 😢 

Generally, we recommend to use tasks ([GitHub Actions](https://github.com/marketplace/actions/azure-powershell-action) and [Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-powershell?view=azure-devops)) to not depend on "default" at all. Depending on default can bring unpredictable issues when new version is released and added to image. Tasks allow to avoid such breaking behavior.
