### ISSUE TITLE
Tests on homebrew installation failed

### ISSUE THREAD

**Issue by shawnz88** [actions/virtual-environments#3988]
### Description

VHD image build failed with error during homebrew validation test.

### Virtual environments affected

- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [X] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

releases/ubuntu20/20210816
releases/ubuntu20/20210810

### Expected behavior

No validation error and image should be built successfully.

### Actual behavior

    Image build failed with the following error:

    azure-arm: Describing Homebrew
    azure-arm:   [-] homebrew 40ms (36ms|4ms)
    azure-arm:    Command 'brew --version' has finished with exit code
    azure-arm:        /usr/bin/bash: brew: command not found
    azure-arm:    at "brew --version" | Should -ReturnZeroExitCode, /imagegeneration/tests/Tools.Tests.ps1:242
    azure-arm:    at <ScriptBlock>, /imagegeneration/tests/Tools.Tests.ps1:242

    azure-arm: ExecutedAt            : 08/31/2021 00:10:25
    azure-arm: Version               : 5.3.0
    azure-arm: PSVersion             : 7.1.4
    azure-arm: PSBoundParameters     : {[Configuration, PesterConfiguration]}
    azure-arm: Plugins               :
    azure-arm: PluginConfiguration   :
    azure-arm: PluginData            :
    azure-arm: Configuration         : PesterConfiguration
    azure-arm: DiscoveryDuration     : 00:00:03.6642155
    azure-arm: UserDuration          : 00:01:08.2521397
    azure-arm: FrameworkDuration     : 00:00:02.7800907
    azure-arm: Failed                : {[-] homebrew}
    azure-arm: FailedBlocks          : {}
    azure-arm: FailedContainers      : {}
    azure-arm: Passed                : {[+] Sdkmanager from SDK tools is available, [+] Sdkman
    azure-arm:                         ager from Command-line tools is available, [+] platform
    azure-arm:                         s/android-27, [+] platforms/android-28…}
    azure-arm: Skipped               : {}
    azure-arm: NotRun                : {}
    azure-arm: Tests                 : {[+] Sdkmanager from SDK tools is available, [+] Sdkman
    azure-arm:                         ager from Command-line tools is available, [+] platform
    azure-arm:                         s/android-27, [+] platforms/android-28…}
    azure-arm: CodeCoverage          :
    azure-arm:
==> azure-arm: Exception: /imagegeneration/helpers/Tests.Helpers.psm1:41
==> azure-arm: Line |
==> azure-arm:   41 |          throw "Test run has failed"
==> azure-arm:      |          ~~~~~~~~~~~~~~~~~~~~~~~~~~~
==> azure-arm:      | Test run has failed
==> azure-arm: 
==> azure-arm: Provisioning step had errors: Running the cleanup provisioner, if present...

### Repro steps

Try to build the VM with packer for releases/ubuntu20/20210816 or releases/ubuntu20/20210810.

**Comment by al-cheb** [comment]
Hey, @shawnz88 
Please don't use the release branches, you should only use the main branch to image generation process. Duplicate: [#3922](https://github.com/actions/virtual-environments/issues/3922)
