### ISSUE TITLE
Ubuntu-latest fails to fetch packets

### ISSUE THREAD

**Issue by ssbanerje** [actions/virtual-environments#3989]
### Description

The `ubuntu-latest` virtual environment fails to fetch certain packages from the 

### Virtual environments affected

- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [X] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

ubuntu-latest

### Expected behavior

Install packages successfully.

### Actual behavior

```
E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/main/s/samba/samba-libs_4.11.6+dfsg-0ubuntu1.9_amd64.deb  404  Not Found [IP: 52.147.219.192 80]
13
E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/main/s/samba/libsmbclient_4.11.6+dfsg-0ubuntu1.9_amd64.deb  404  Not Found [IP: 52.147.219.192 80]
14
E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/main/m/mesa/libegl-mesa0_21.0.3-0ubuntu0.2~20.04.1_amd64.deb  404  Not Found [IP: 52.147.219.192 80]
15
E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/main/m/mesa/libxatracker2_21.0.3-0ubuntu0.2~20.04.1_amd64.deb  404  Not Found [IP: 52.147.219.192 80]
16
E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/main/m/mesa/mesa-vulkan-drivers_21.0.3-0ubuntu0.2~20.04.1_amd64.deb  404  Not Found [IP: 52.147.219.192 80]
17
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
```

### Repro steps

Example Run: https://github.com/ssbanerje/dotfiles/runs/3475233510?check_suite_focus=true

**Comment by maxim-lobanov** [comment]
Hello @ssbanerje , please make sure that you have run `sudo apt-get update` before installation packages.

**Comment by ssbanerje** [comment]
That seems to have done the trick. Thanks. I am closing this issue.
