### ISSUE TITLE
Announcement/Feedback: Python@2 on all images will be deprecated starting of 04/06/2020

### ISSUE THREAD

**Issue by AlenaSviridenko** [actions/virtual-environments#399]
Hi!

Due to the recent deprecation of Python@2 we are going to deprecate it too on MacOS, Windows, Ubuntu images on 04/06/2020.
We give it 1.5 month to live so that developers could migrate their code.

If you have any concerns or questions please let use know through this issue.

Thanks!

**Comment by thejoebourneidentity** [comment]
FYI
https://github.blog/changelog/2020-02-27-github-actions-breaking-change-python-2-being-removed-from-all-virtual-environments/

**Comment by maxim-lobanov** [comment]
We see a lot of customers' feedback about this announcement and decided to keep Python 2 on our images.
Cancelling this announcement. Thank you for your feedback

**Comment by asottile** [comment]
fwiw the blog post is still live -- might want to update that: https://github.blog/changelog/2020-02-27-github-actions-breaking-change-python-2-being-removed-from-all-virtual-environments/

**Comment by maxim-lobanov** [comment]
@asottile , thank you for notice.
@thejoebourneidentity , could you please update blob post?
