### ISSUE TITLE
Update/Add Mysql 8

### ISSUE THREAD

**Issue by paulrrogers** [actions/virtual-environments#40]
**Tool information**
- Tool name: Mysql
- Add or update? update
- Desired version: 8.0
- Approximate size: 
- If this is an add request:
  - Brief description of tool: RDBMS
  - URL for tool's homepage: https://dev.mysql.com/

**Virtual environments affected**
- [ ] macOS 10.14
- [x] Ubuntu 16.04 LTS
- [x] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Can this tool be installed during the build?**
yes, minutes

**Are you willing to submit a PR?**
maybe

**Comment by maxim-lobanov** [comment]
@paulrrogers , currently, our images contain MySQL 5.7. Do you have acontext, will it be a breaking change for other customers who use MySQL 5.7 if we update it to MySQL 8?

**Comment by paulrrogers** [comment]
@maxim-lobanov Mysql 8 has significant changes, though if BC is a concern it can be configured to behave similarly to the defaults in v5.7.

https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html

**Comment by Darleev** [comment]
Hello, @paulrrogers.
Mysql 8 update on Ubuntu 20 pull request has been merged. All changes will be available after the next image rollout.
I will let you know additionally when the change is applied.

**Comment by Darleev** [comment]
Hello, @paulrrogers,
We have deployed MySQL 8 on Ubuntu 20 only due to potential impact and significant changes in latest MySQL version. So, MySQL 8 has already been delivered to Ubuntu 20, feel free to use it.

I'm going to close the issue.
Please let us know in case of any questions.
