### ISSUE TITLE
Update/Add Ubuntu 21.04 VM

### ISSUE THREAD

**Issue by jerabaul29** [actions/virtual-environments#4011]
### Tool name

provide Ubuntu 21.04

### Tool license

Ubuntu

### Add or update?

- [X] Add
- [ ] Update

### Desired version

21.04

### Brief description of tool

Not sure it this is the right place to ask - if not, let me know where I should ask for it :) - but I was wondering if it would be possible to get support also for the latest "non LTS" Ubuntu. 

User case: in my case (I guess I am not alone), I cannot run the tests I want for the latest version of one of my package using Ubuntu 20.04, because of the "old" versions of packages available there that are not enough to run my code. For now I perform testing on my personal Ubuntu 21.04 laptop, but would be very convenient to be able to have actions for these tests too :) . The issue I see, having no "non LTS" test environment, is that it means that it takes 2 years before being able to run tests with "recent" Ubuntu packages, which is a really slow down on testing with actions.

### Virtual environments affected

- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [ ] Windows Server 2022

**Comment by MehdiChinoune** [comment]
You can use container
```
jobs:
  build:
    name: ubuntu 21.04
    runs-on: ubuntu-20.04
    container: ubuntu:21.04
```
see:
https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idcontainer
https://hub.docker.com/_/ubuntu

**Comment by jerabaul29** [comment]
Aah, thanks.

Just wondering: this is running an ubuntu 21.04 container, inside an ubuntu 20.04 VM, right? Is this not a lot of unneeded overhead / load on the data center and potentially introducing some delays on my tests?

**Comment by jerabaul29** [comment]
Mmmh, I went through the links, not clear how to use it to me. Do you know of a real world example of running tests this way?

**Comment by MehdiChinoune** [comment]
> Mmmh, I went through the links, not clear how to use it to me. Do you know of a real world example of running tests this way?

Unlike github-actions images, ubuntu:21.04 container comes with minimal preinstalled programs,  you have to install the prerequisties yourself. Beside that, there is no difference as you can use the same syntax.

**Comment by maxim-lobanov** [comment]
Hello @jerabaul29 , we don't have plans to add Ubuntu 21.04. Our policy is supporting only LTS versions of Ubuntu.
The recommended solution is using docker container as it was suggested above.
The workflow steps shouldn't differ. You are only need to specify [container](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idcontainer) property to YAML.

A few links that can be helpful:
- https://docs.cypress.io/guides/continuous-integration/github-actions
- https://towardsdatascience.com/speed-up-your-pytest-github-actions-with-docker-6b3a85b943f

**Comment by jerabaul29** [comment]
Thanks, that worked well. As you say, the container for 21.04 is very barebone, a bit painful to get to work, but works in the end, thanks!
