### ISSUE TITLE
Update chocolatey

### ISSUE THREAD

**Issue by jetersen** [actions/virtual-environments#4012]
### Tool name

chocolatey

### Tool license

https://github.com/chocolatey/choco/blob/master/LICENSE

### Add or update?

- [ ] Add
- [X] Update

### Desired version

0.11.1

### Brief description of tool

A nee version of Chocolatey v0.11.1 has been released that should address this issue. If we could get it installed on the build agent machine and test to ensure if it is fixed, that would be great. Thanks!

_Originally posted by @gep13 in https://github.com/actions/virtual-environments/issues/3010#issuecomment-912273248_

This seems to require a rebuild of the windows images based on
https://github.com/actions/virtual-environments/blob/126faeedce84fedfeef6e525691aec3b72427a78/images/win/scripts/Installers/Install-Choco.ps1#L21

resolves #3010

### URL for tool's homepage

https://chocolatey.org/

### Provide a basic test case to validate the tool's functionality.

```bash
Already heavily used in the repo 😅
```

### Virtual environments affected

- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [x] Windows Server 2016
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Can this tool be installed during the build?

```powershell
Invoke-Expression ((new-object net.webclient).DownloadString('https://chocolatey.org/install.ps1'))
```

### Are you willing to submit a PR?

N/A as the script installs the latest already

**Comment by dibir-magomedsaygitov** [comment]
Hello @jetersen.  Updated chocolatey should be available with the next week's rollout. I'll post an update message.

**Comment by jetersen** [comment]
Note that [win19/20210903](https://github.com/actions/virtual-environments/blob/releases/win19/20210903/images/win/Windows2019-Readme.md) includes chocolatey 0.11.1
Win2016, Win2022 have yet to receive new images :)

**Comment by dibir-magomedsaygitov** [comment]
Hello @jetersen. Chocolatey was updated across all Windows images. I'm going to close this issue. In case of any questions feel free to contact us.

**Comment by jetersen** [comment]
Thanks for the update @dibir-magomedsaygitov 👏
