### ISSUE TITLE
Need help with installation of prerequisites

### ISSUE THREAD

**Issue by vesubramanian** [actions/virtual-environments#4017]
### Description

**Note**: Please excuse me for categorizing it as a bug, although it is not. There is no other category where I could clarify these and the documentation is also missing many things. 

I am trying to build a self hosted Ubuntu runner with all the pre-reqs provided in this repository. I am not sure why there is no documentation around how to build this. It would have been really great if there was a step by step documentation on how to build an image targeting VMWare or Docker or AWS or install pre-reqs. 

However, after a lot of research, I found that the ubuntu2004.json is the file to refer to. I am refering this file and trying to build a shell script which will create imagegeneration directory, clone the repository and then run the scripts one by one in the order specified in that json file. However, I am still strugging to get this going and I have some questions. It will be great if someone can please help me.
1. In ubuntu2004.json, there is a template_dir. Not sure what value gets assigned to this?
2. Are the scripts mentioned in ubuntu2004.json executed in a loop by an external utility like packer? I am raising this question because I am curious how every subsequent script gets access to the PATH or any other environment variable added by the previous script. When I execute all the scripts in order from a single shell script, I run into issues where some of the scripts after execution display a message saying I need to relogin to the terminal or open a new terminal for the environment variable changes to take effect.
3. Many of my tests are failing, although the packages seem to be getting installed properly.
4. In install.sh and Tests.Helpers.psm1 files, there is a path "/imagegeneration". I am curious how this works. In Linux, do they create any new mounts, since  /imagegeneration looks similar to /etc, /usr, /tmp etc. 
5. In some scripts, although there is -y flag for some commands like apt update, I see prompts. I am not sure how to pass DEBIAN_FRONTEND=noninteractive to suppress these prompts.
6. In some scripts like git.sh, haskell.sh and surprisingly during testing of PHPUnit, I get prompts. I have no idea why. There are -y flags. But still the scripts pause and prompts.
7. While installing PIP, I get warning that installing using PIP can create issues. I am surprised to see this, because I use a non root user with sudo privileges, which is what the ubuntu2004.json also shows.
8. I have not been able to install brew using homebrew.sh, even when I run it using non root user. No idea what should I do to install it correctly.
9. There is a reboot.sh which does the reboot. How does the subsequent script resumes after reboot?
10. How are the various environment variables like IMAGE_FOLDER, IMAGEDATA_FILE, INSTALLER_SCRIPT_FOLDER, HELPER_SCRIPTS etc persisted without adding to /etc/environment?
11.  What values get assigned to {{ .Vars }} and {{ .Path }} variables in ubuntu2004.json?
12.  Most of the scripts seem to be executed from {{template_dir}} whereas some of them are getting executed from {{image_folder}}. Why is this?
13.  Brew is installed using /bin/sh. Please explain the reason for this?
14.  Why are some scripts written in PowerShell?

### Virtual environments affected

- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [X] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Ubuntu 20.04

### Repro steps

No steps.

**Comment by vesubramanian** [comment]
2 more queries.
11.  What values get assigned to {{ .Vars }} and {{ .Path }} variables in ubuntu2004.json?
12.  Most of the scripts seem to be executed from {{template_dir}} whereas some of them are getting executed from {{image_folder}}. Why is this?
13.  Brew is installed using /bin/sh. Please explain the reason for this?
14.  Why are some scripts written in PowerShell?

**Comment by catthehacker** [comment]
I'm not part of actions team but I've spent quite a lot of time with the templates in this repo as well with Packer and I've maintained before a Docker image based on this repository but without using Packer.

> I am trying to build a self hosted Ubuntu runner with all the pre-reqs provided in this repository. I am not sure why there is no documentation around how to build this. It would have been really great if there was a step by step documentation on how to build an image targeting VMWare or Docker or AWS or install pre-reqs.

There is documentation here: https://github.com/actions/virtual-environments/blob/main/docs/create-image-and-azure-resources.md

> However, after a lot of research, I found that the ubuntu2004.json is the file to refer to. I am refering this file and trying to build a shell script which will create imagegeneration directory, clone the repository and then run the scripts one by one in the order specified in that json file. However, I am still strugging to get this going and I have some questions. It will be great if someone can please help me.

Don't do that, it's not worth it. Maintenance cost is just too much and it will break whenever something is changed in original template, just use Packer it's much easier (although I'm not going to say that Packer works great always, especially the Docker plugin).

> 1. In ubuntu2004.json, there is a template_dir. Not sure what value gets assigned to this?

It's a directory where template (`ubuntu2004.json`) is stored, so it will be https://github.com/actions/virtual-environments/tree/main/images/linux.

> 2. Are the scripts mentioned in ubuntu2004.json executed in a loop by an external utility like packer? I am raising this question because I am curious how every subsequent script gets access to the PATH or any other environment variable added by the previous script. When I execute all the scripts in order from a single shell script, I run into issues where some of the scripts after execution display a message saying I need to relogin to the terminal or open a new terminal for the environment variable changes to take effect.

Yes, Packer is used. Scripts are not accustomed to work without Packer and break *quite* often in many places.

> 4. In install.sh and Tests.Helpers.psm1 files, there is a path "/imagegeneration". I am curious how this works. In Linux, do they create any new mounts, since  /imagegeneration looks similar to /etc, /usr, /tmp etc.

It's just a standard directory.

https://github.com/actions/virtual-environments/blob/6968a424be7df5d6ca1d9065438b05395e2e0b25/images/linux/ubuntu2004.json#L17

https://github.com/actions/virtual-environments/blob/6968a424be7df5d6ca1d9065438b05395e2e0b25/images/linux/ubuntu2004.json#L60-L67

> 5. In some scripts, although there is -y flag for some commands like apt update, I see prompts. I am not sure how to pass DEBIAN_FRONTEND=noninteractive to suppress these prompts.

bash example
```sh
# single command
DEBIAN_FRONTEND=noninteractive ./path/to/script.sh

# multiple commands
export DEBIAN_FRONTEND=noninteractive
some_command
./path/to/script.sh
```

packer example
https://github.com/actions/virtual-environments/blob/6968a424be7df5d6ca1d9065438b05395e2e0b25/images/linux/ubuntu2004.json#L73-L82

> 3. Many of my tests are failing, although the packages seem to be getting installed properly.
> 6. In some scripts like git.sh, haskell.sh and surprisingly during testing of PHPUnit, I get prompts. I have no idea why. There are -y flags. But still the scripts pause and prompts.
> 8. I have not been able to install brew using homebrew.sh, even when I run it using non root user. No idea what should I do to install it correctly.

Most likely because the environment is not carried over to next process. Hard to tell since all scripts are meant to work together with Packer.

> 9. There is a reboot.sh which does the reboot. How does the subsequent script resumes after reboot?
> 10. How are the various environment variables like IMAGE_FOLDER, IMAGEDATA_FILE, INSTALLER_SCRIPT_FOLDER, HELPER_SCRIPTS etc persisted without adding to /etc/environment?

Packer handles that.
https://github.com/actions/virtual-environments/blob/6968a424be7df5d6ca1d9065438b05395e2e0b25/images/linux/ubuntu2004.json#L301
https://www.packer.io/docs/provisioners/shell#expect_disconnect

> 11. What values get assigned to {{ .Vars }} and {{ .Path }} variables in ubuntu2004.json?

- `Path` is the path to the script to run
- `Vars` is the list of environment_vars, if configured.
- `EnvVarFile` is the path to the file containing env vars, if use_env_var_file is true.

https://www.packer.io/docs/provisioners/shell#execute_command

> 13. Brew is installed using /bin/sh. Please explain the reason for this?

`sudo` is not used since homebrew doesn't support root installation.
As for `/bin/sh` rather than `sh`, there seems to be no reason for that, just author preference. (https://github.com/actions/virtual-environments/pull/589)

> 14. Why are some scripts written in PowerShell?

Can't speak for the maintainers but it's much easier and clear to write/maintain PowerShell scripts in comparison to `bash` with `jq`.

**Comment by vesubramanian** [comment]
Hi Ryan,

First of all, a big thank you for taking the time out and patiently answering my queries. But I am still curious about a few things.
1. Why GitHub is not open sourcing the packer build script?
2. Why are they targeting only Azure (is it just because GitHub is acquired by MS)?
3.  If you have packer script / docker image, can you please share it or open source it? I am sure there are lots of people who have a similar requirement as me.
4.  I had already gone through the first [link] (https://github.com/actions/virtual-environments/blob/main/docs/create-image-and-azure-resources.md) you provided. However it seems to be targeted to Azure. In my case, I just want it as a normal image (say. VMWare or HyperV or Docker).
5.  Even if I learn packer now, it will take sometime. Hence I am requesting.

**Comment by catthehacker** [comment]
> 1. Why GitHub is not open sourcing the packer build script?

It is open source. It's in this repository, Packer template is here: https://github.com/actions/virtual-environments/blob/main/images/linux/ubuntu2004.json and helper scripts are here: https://github.com/actions/virtual-environments/tree/main/helpers but helper scripts are not required for building the image. 
The only thing you need is Packer and [that is open source too](https://github.com/hashicorp/packer)

> 2. Why are they targeting only Azure (is it just because GitHub is acquired by MS)?

Because GH Actions runners are hosted on Azure infrastructure.

> 3. If you have packer script / docker image, can you please share it or open source it? I am sure there are lots of people who have a similar requirement as me.

As mentioned in 1. all pre-requisites for building VM is in this repository, if you want to build Docker image you can [check out my fork](https://github.com/catthehacker/virtual-environments-fork/tree/master/images/linux) but Packer is still required and unfortunately the built image is not perfect due to how current Packer Docker plugin works but I'm working on fixing that. Other builders might also work but you need to adjust templates yourself.

> 4. I had already gone through the first [link] ([https://github.com/actions/virtual-environments/blob/main/docs/create-image-and-azure-resources.md](https://github.com/actions/virtual-environments/blob/main/docs/create-image-and-azure-resources.md?rgh-link-date=2021-09-05T05%3A28%3A53Z)) you provided. However it seems to be targeted to Azure. In my case, I just want it as a normal image (say. VMWare or HyperV or Docker).

You need to adapt Packer template yourself to target whichever builder you want. It's not possible for Actions team to support Packer builders they don't use.
In case of [VMware](https://www.packer.io/docs/builders/vmware/vmx)/[Hyper-V](https://www.packer.io/docs/builders/hyperv/vmcx) it's very simple, you only need to have a clean Ubuntu VM.

**Comment by vesubramanian** [comment]
Thanks a lot once again. If I want to just execute Packer build (by following the steps without Azure part), should I run it on the same Ubuntu server on which I am installing prereqs or from another server? Sorry for being naive, but I am very new to all these. The GenerateResourcesAndImage.ps1 calls packer build with lots of Azure related arguments, not sure how to skip them or what will be the consequences? Once I run the packer build script, what sort of Image should I expect? Please explain. Thanks a lot once again.

**Comment by catthehacker** [comment]
> If I want to just execute Packer build (by following the steps without Azure part), should I run it on the same Ubuntu server on which I am installing prereqs or from another server?

Not sure what you mean by that, you should run Packer on machine that has management tools/can connect to Hyper-V/VMware.

> The GenerateResourcesAndImage.ps1 calls packer build with lots of Azure related arguments, not sure how to skip them or what will be the consequences?

It's better to not use it if you are not building VM in Azure. Just replace builder in the template and run Packer pointing to template. Don't forget to set environment variables for Dockerhub credentials.

> Once I run the packer build script, what sort of Image should I expect?

For Hyper-V/VMware builders it will leave a VM intact, you can then copy/move/delete it as you wish

**Comment by vesubramanian** [comment]
> > If I want to just execute Packer build (by following the steps without Azure part), should I run it on the same Ubuntu server on which I am installing prereqs or from another server?
> 
> Not sure what you mean by that, you should run Packer on machine that has management tools/can connect to Hyper-V/VMware.
> What I want is to just install all the prerequisites on an Ubuntu server and take a snapshot of it in VMWare. This can act as a template in my case. In such a simple scenario, all I need to do it just install packer (and follow the steps in the [documentation](https://github.com/actions/virtual-environments/blob/main/docs/create-image-and-azure-resources.md) in my Ubuntu server (where I want to install the prerequisites) and run the packer build after removing the builder section, right?

> > The GenerateResourcesAndImage.ps1 calls packer build with lots of Azure related arguments, not sure how to skip them or what will be the consequences?
> 
> It's better to not use it if you are not building VM in Azure. Just replace builder in the template and run Packer pointing to template. Don't forget to set environment variables for Dockerhub credentials.
> I can completely remove the build section from the json, you mean? Also, the images pulled are all public images, I think I could pull them even without credentials. Not sure why they are expecting Dockerhub credentials.

> > Once I run the packer build script, what sort of Image should I expect?
> 
> For Hyper-V/VMware builders it will leave a VM intact, you can then copy/move/delete it as you wish

**Comment by vesubramanian** [comment]
Thanks a lot once again for your prompt response.

I can completely remove the build section from the json, you mean? Also, the images pulled are all public images, I think I could pull them even without credentials. Not sure why they are expecting Dockerhub credentials. Anyways, I will try to create a test login and provide that.
 
What I want is to just install all the prerequisites on an Ubuntu server and take a snapshot of it in VMWare. This can act as a template in my case. In such a simple scenario, all I need to do it just install packer (and follow the steps in the [documentation](https://github.com/actions/virtual-environments/blob/main/docs/create-image-and-azure-resources.md) in my Ubuntu server (where I want to install the prerequisites) and run the packer build after removing the builder section, right?

**Comment by vesubramanian** [comment]
I was wondering how you generated Docker image using packer, since some scripts have systemctl commands which is not supported on Docker.
Also, since their base script (GenerateImageAndResources.ps1) is a PowerShell, I was wondering, if they execute packer build from a Windows machine even for building Ubuntu image.

It will be great, if you could please clarify these.

**Comment by catthehacker** [comment]
> Also, since their base script (GenerateImageAndResources.ps1) is a PowerShell, I was wondering, if they execute packer build from a Windows machine even for building Ubuntu image.

PowerShell is available for Linux.

> I was wondering how you generated Docker image using packer, since some scripts have systemctl commands which is not supported on Docker.

I modified the scripts.



> I can completely remove the builder section from the json, you mean?

Replace it with the builder of your choice: https://www.packer.io/docs/builders

> Also, the Docker images pulled are all public images, I think I can pull them even without credentials. Not sure why they are expecting Dockerhub credentials.

Credentials are provided to prevent rate limit when pulling images.

> What I want is to just install all the prerequisites on an Ubuntu server and take a snapshot of it in VMWare. This can act as a template in my case. In such a simple scenario, all I need to do is to just install packer (and follow the steps in the [documentation](https://github.com/actions/virtual-environments/blob/main/docs/create-image-and-azure-resources.md?rgh-link-date=2021-09-06T18%3A56%3A54Z) in my Ubuntu server (where I want to install the prerequisites) and run the packer build after removing the builder section, right?

Packer needs to be installed and run on the machine that has access to VMware/Hyper-V, not in a VM which is going to be built.

**Comment by miketimofeev** [comment]
Thanks, @catthehacker for all the provided instructions.
@vesubramanian we have the discussions section available here https://github.com/actions/virtual-environments/discussions It's better to ask such kind of configuration questions there.
I'm going to close this issue.
