### ISSUE TITLE
Line ending problem in workflow file.

### ISSUE THREAD

**Issue by kms1212** [actions/virtual-environments#4018]
### Description

The single line ending is replaced into space, and the Double line ending is replaced into a single line ending in a workflow configuration file. This bug is for Windows runner. I've not tested other versions of Windows, but at least in the 2019 version, I had this problem.

Or is this any of my mistakes?

### Virtual environments affected

- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [X] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

[Workflow link](https://github.com/kms1212/OpenFSL/runs/3513456390?check_suite_focus=true)

Part of workflow configuration file:
`
...
        mkdir -p packages
        
        cmake -G "Visual Studio 16 2019" -A x64 -S. -Bbuild \
              -DBUILD_TESTING=true \
              -DDOXYGEN_GENERATE=false \
              -DNO_BUILD=false \
              -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} \
              -DPACKAGE_TYPE=NIGHTLY \
              -DPACKAGE_GENERATE=true \
              -DPACKAGE_GENERATOR=TGZ \
              -DBUILD_FAT32=true

        cmake --build build --config ${{env.BUILD_TYPE}} --target all_build run_tests

        cd build

        cpack

        cpack -P ZIP

        cpack -P NSIS64

        cp openfsl-* ../packages/

        cd ..
        
        rm -rf build
...
`

Part of workflow log:
`
cmake -G "Visual Studio 16 2019" -A Win32 -S. -Bbuild \ -DBUILD_TESTING=true \ -DDOXYGEN_GENERATE=false \ -DNO_BUILD=false \ -DCMAKE_BUILD_TYPE=Release \ -DPACKAGE_TYPE=NIGHTLY \ -DPACKAGE_GENERATE=true \ -DPACKAGE_GENERATOR=TGZ \ -DBUILD_FAT32=true
  cmake --build build --config Release --target all_build run_tests
  cd build
  cpack
  cpack -P ZIP
  cpack -P NSIS
  cp openfsl-* ../packages/
  cd ..
  rm -rf build
`

### Repro steps

1. Create a workflow file that runs Windows runner.
2. Add a step to the workflow file that runs on bash on Windows with following example code: <pre><code>echo Build
Test</code></pre>
3. And the output will be: `Build Test`

**Comment by al-cheb** [comment]
Hello, @kms1212 
This issue is not related to image generation process. Please create a new issue on - https://github.community/
