### ISSUE TITLE
Add  Wireguard

### ISSUE THREAD

**Issue by cmosh** [actions/virtual-environments#402]
**Tool information**
- Tool name:  Wireguard Client
- Add
- Desired version:  latest
- Approximate size: 
- If this is an add request:
  - Brief description of tool: A VPN client
  - URL for tool's homepage: https://www.wireguard.com/

**Area for Triage**:

Packages

**Question, Bug, or Feature?**:

Feature

**Virtual environments affected**
- [ ] macOS 10.15
- [x] Ubuntu 16.04 LTS
- [x] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Can this tool be installed during the build?**
- It can be installed, available as an apt repository for Ubuntu
- It takes about 2 minutes

**Are you willing to submit a PR?**
Yes -- Here it is #403

**Comment by thejoebourneidentity** [comment]
Thanks for your suggestion 🙏. Considering how easy it is to install during your run, this is not something we will add to the image at this time.

**Comment by tyrann0us** [comment]
Hi @thejoebourneidentity, sorry for commenting on a closed issue. After over four years, I wanted to follow up on this issue and ask if there are any reconsiderations on adding WireGuard to the image.
Thank you!
