### ISSUE TITLE
Add HAXM

### ISSUE THREAD

**Issue by JavierSegoviaCordoba** [actions/virtual-environments#4023]
### Tool name

HAXM

### Tool license

https://github.com/intel/haxm/blob/master/LICENSE

### Add or update?

- [X] Add
- [ ] Update

### Desired version

7.7.0

### Brief description of tool

Currently, Android developers only can run tests on macOS, adding HAXM on Windows will fix this problem.

### URL for tool's homepage

https://github.com/intel/haxm

### Virtual environments affected

- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [X] Windows Server 2019
- [X] Windows Server 2022

**Comment by al-cheb** [comment]
Hey, @JavierSegoviaCordoba 
Currently, we can't add HAXM due to unable to use nested virtualization on Azure agents.

![image](https://user-images.githubusercontent.com/47745270/132211082-0b70100d-2976-48b0-9718-ecf1db6ae0ed.png)

**Comment by mazgajmaciek** [comment]
@al-cheb how about Hyper-V / Windows Hypervisor Platform (WHPX) for Windows Server runners? Reading this https://docs.microsoft.com/en-us/xamarin/android/get-started/installation/android-emulator/hardware-acceleration?pivots=windows#accelerating-android-emulators-on-windows we should be enabling it to run android emulator. My use case is to switch from macos runners running android emulator to windows one.

**Comment by al-cheb** [comment]
> Hyper-V / Windows Hypervisor Platform (WHPX

https://github.com/actions/virtual-environments/issues/183#issuecomment-610723516
