### ISSUE TITLE
Add windowsservercore-ltsc2022 cached docker images

### ISSUE THREAD

**Issue by damienpontifex** [actions/virtual-environments#4035]
### Tool name

Docker windowsservercore-ltsc2022

### Tool license

Unknown

### Add or update?

- [X] Add
- [ ] Update

### Desired version

mcr.microsoft.com/dotnet/framework/aspnet:4.8-windowsservercore-ltsc2022

### Brief description of tool

Cached docker images on machine help speed up builds (especially in this case of windows container base). The ltsc2022 images are now available as shown on https://hub.docker.com/_/microsoft-dotnet-framework-aspnet/. It'd be nice to have these also cached alongside the ltsc2019 that are currently cached as listed on https://github.com/actions/virtual-environments/blob/main/images/win/Windows2019-Readme.md#cached-docker-images

### URL for tool's homepage

https://hub.docker.com/_/microsoft-dotnet-framework-aspnet/

### Provide a basic test case to validate the tool's functionality.

```bash
docker pull mcr.microsoft.com/dotnet/framework/aspnet:4.8-windowsservercore-ltsc2022
```

### Virtual environments affected

- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Are you willing to submit a PR?

Yes

**Comment by miketimofeev** [comment]
Hi @damienpontifex!
The image is not supported by windows server-2019:
`a Windows version 10.0.20348-based image is incompatible with a 10.0.17763 host`
We don't have any objections to adding the image to the windows-2022, feel free to submit a PR.

**Comment by viceice** [comment]
I've prepared PR #4040. anything else i need to add /change?

**Comment by miketimofeev** [comment]
@viceice thanks for your contribution!
The new VM image with cached docker images will be deployed next week.

**Comment by miketimofeev** [comment]
@damienpontifex the image has been deployed.
I'm going to close the issue. Please feel free to contact us if you have any concerns.
Thank you!
