### ISSUE TITLE
[Ubuntu] Alpine 3.11 docker image will be removed on September, 20

### ISSUE THREAD

**Issue by miketimofeev** [actions/virtual-environments#4042]
### Breaking changes

We are going to remove alpine:3.11 docker image from the list of pre-cached images on VM.

### Target date

Image deployment will start September, 20 and will take 3-4 days.

### The motivation for the changes

According to our [Software and images support policy](https://github.com/actions/virtual-environments/blob/main/docs/software-and-images-guidelines.md#software-and-images-support-policy) we support not more than 3 latest LTS versions of images. As we added the alpine 3.14 image we have to deprecate 3.11 one.

### Possible impact

If your builds rely on the alpine:3.11 docker image they can be slower due to the necessity of downloading alpine:3.11 image.

### Virtual environments affected

- [ ] Ubuntu 16.04
- [X] Ubuntu 18.04
- [X] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Mitigation ways

Nothing is required — if there is no local image docker will pull it automatically from the docker hub.

**Comment by miketimofeev** [comment]
The images without Alpine 3.11 have been deployed.

**Comment by Arifan998** [comment]
Write
