### ISSUE TITLE
Update/Add cargo-audit back to 0.15

### ISSUE THREAD

**Issue by dotdash** [actions/virtual-environments#4045]
### Tool name

cargo-audit

### Tool license

 Apache-2.0 or MIT 

### Add or update?

- [ ] Add
- [X] Update

### Desired version

0.15

### Virtual environments affected

- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [ ] Windows Server 2022

**Comment by dotdash** [comment]
I couldn't figure out how to modify the template before submitting, and none of the fields felt fit for this additional info.

I saw that cargo-audit was downgraded to 0.14.1 due to #3817 and #3840. At that point in time, the corresponding bug in `git2` had already been fixed, but due to the `--locked` flag in the `cargo install` command, cargo was forced to use the dependencies as specified in the `Cargo.lock` file, i.e. the old, broken version of `git2`. The default behaviour for `cargo install` is to ignore the lockfile and just use the most up-to-date semver compatible version of the dependencies.

Since you already removed the `--locked` flag from the new install command for the old version of `cargo-audit`, I'd like to ask you to update it back to 0.15 as well, as version 0.14.1 has a severe flaw when it comes to parsing version numbers of pre-release crates, generating bug reports for issues that have long been fixed.

**Comment by al-cheb** [comment]
Hey, @dotdash 
If we revert the changes it will not compile - https://github.visualstudio.com/virtual-environments/_build/results?buildId=116195&view=logs&j=011e1ec8-6569-5e69-4f06-baf193d1351e&t=5431112d-2b61-5a5f-7042-ef698f761043

![image](https://user-images.githubusercontent.com/47745270/132524111-fb4bcbb5-172a-4053-bb0a-00c3a55324f9.png)

**Comment by dotdash** [comment]
Yeah, simply reverting won't do, as that includes the `--locked` flag again, so it's using the old version of `git2` again. 

Depending on your preferences, you can either revert the change and additionally remove the `--locked` option, or keep the change, but remove the version constraint from the `cargo install` command for `cargo-audit`.

**Comment by miketimofeev** [comment]
@dotdash previously we faced an issue when updated dependency also broke the image generation https://github.com/actions/virtual-environments/pull/2545
After finding this thread we decided to set `--locked` flag to stay on the safe side https://github.com/rust-lang/cargo/issues/7169
Is it possible to update `cargo.lock` file in cargo-audit https://github.com/rustsec/rustsec/blob/main/cargo-audit/Cargo.lock with the new version of git2?

**Comment by dotdash** [comment]
@miketimofeev thanks for the heads up! I've filed an issue for a new cargo-audit release at https://github.com/rustsec/rustsec/issues/429 - depending on your rust version, it either fails with or without `--locked`, so a new release seems appropriate. I'll ping here again when a new release is out.

**Comment by dotdash** [comment]
cargo-audit 0.15.1 has been released.

**Comment by al-cheb** [comment]
The new images with cargo-audit have been deployed.
