### ISSUE TITLE
Installing nginx now fails on macOS-10.14

### ISSUE THREAD

**Issue by wtgodbe** [actions/virtual-environments#4049]
### Description

This worked up until at least 1 month ago. We install nginx like this:

https://github.com/dotnet/aspnetcore/blob/main/eng/scripts/install-nginx-mac.sh

Our release/3.1 and release/5.0 branches use vmimage `macOS-10.14`, which now fails in `brew install` with a failure to link `bin2to3`:

> Error: The `brew link` step did not complete successfully
The formula built, but is not symlinked into /usr/local
Could not symlink bin/2to3
Target /usr/local/bin/2to3
already exists. You may want to remove it:
  rm '/usr/local/bin/2to3'

> To force the link and overwrite all conflicting files:
  brew link --overwrite python@3.9

> To list all files that would be deleted:
  brew link --overwrite --dry-run python@3.9

> Possible conflicting files are:
/usr/local/bin/2to3 -> /Library/Frameworks/Python.framework/Versions/2.7/bin/2to3

We're working around this by setting that step to `ContinueOnError`, as the build still works after it & it's just a test job, but the install step now takes around 6 minutes instead of 2, and continuing on error means we're less likely to notice new failures in that step in the future.

### Virtual environments affected

- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [X] macOS 10.14
- [ ] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

macOS-10.14

https://dev.azure.com/dnceng/public/_build/results?buildId=1349397&view=results

### Is it regression?

Yes

### Expected behavior

brew install exits successfully

### Actual behavior

Error: The `brew link` step did not complete successfully
The formula built, but is not symlinked into /usr/local
Could not symlink bin/2to3
Target /usr/local/bin/2to3
already exists. You may want to remove it:
  rm '/usr/local/bin/2to3'

To force the link and overwrite all conflicting files:
  brew link --overwrite python@3.9

To list all files that would be deleted:
  brew link --overwrite --dry-run python@3.9

Possible conflicting files are:
/usr/local/bin/2to3 -> /Library/Frameworks/Python.framework/Versions/2.7/bin/2to3

### Repro steps

Run aspnetcore-ci against branch release/3.1 or release/5.0

**Comment by wtgodbe** [comment]
Note - there was no option for macOS-10.14, so I checked the macOS-10.15 box. This works fine on 10.15, but we don't want to change the platforms we test on in servicing.

**Comment by miketimofeev** [comment]
Hi @wtgodbe!
It's a known issue — https://github.com/actions/virtual-environments/issues/4020
We will fix the root cause and update 10.14 VM image in the next 2-3 weeks.
Please use the suggested workaround until:
`rm -rf /usr/local/bin/2to3`

**Comment by mikhailkoliada** [comment]
New image version has been released, the problem must be solved by now.
