### ISSUE TITLE
Pre-installed JDKs on Hosted Agents

### ISSUE THREAD

**Issue by brunoborges** [actions/virtual-environments#405]
It would be good to see a cohesive and consistent map of pre-installed JDKs across GitHub Actions and Azure Pipelines virtual environments / hosted build agents.

As of December 2019, these were the pre-installed versions and what was the default one:

Azure Pipelines Image Name | Image version | Java versions installed | Default Java
-- | -- | -- | --
Hosted Windows 2019 with VS2019 | v20191009.1 | 1.7.0_232, 1.8.0_222, 11.0.4 | 1.8.0_222
Hosted VS2017 | v20191009.1 | 1.7.0_232, 1.8.0_222, 11.0.4 | 1.8.0_222
Hosted Ubuntu 1804 | v20191025.1 | 1.7.0_242, 1.8.0_232, 11.0.5, 12.0.2 | 12.0.2
Hosted Ubuntu 1604 | v20191025.1 | 1.7.0_242, 1.8.0_232, 11.0.5, 12.0.2 | 12.0.2
Hosted macOS | macOS-10.14 | 1.7.0_242, 1.8.0_232, 11.0.5, 12.0.2, 13.0.1 | 13.0.1
Hosted macOS High Sierra | macOS-10.13 | 1.7.0_242, 1.8.0_232, 11.0.5, 12.0.2, 13.0.1 | 13.0.1

**Comment by FelixLitli** [comment]
Thank you

**Comment by maxim-lobanov** [comment]
Hello, docs for all images contain the list of installed OpenJDK:
- [macOS](https://github.com/actions/virtual-environments/blob/master/images/macos/macos-10.15-Readme.md#language-and-runtime)
- [Windows](https://github.com/actions/virtual-environments/blob/master/images/win/Windows2019-Readme.md#java-development-kit)
- [Ubuntu](https://github.com/actions/virtual-environments/blob/master/images/linux/Ubuntu1804-README.md)

I am planning to close the issue. Please let me know if you have any concerns

**Comment by brunoborges** [comment]
@maxim-lobanov the links you provide point to bullet lists that do not provide consistent defaults. In fact, the only image that states which JDK is the default is macOS image.

Plus, images have different defaults. I know that on macOS, default is Java 8, while on Ubuntu the default is *not* Java 8.

I'd appreciate a better resolution than just closing this issue because there is a bullet list somewhere.

**Comment by maxim-lobanov** [comment]
I got your point. That makes sense to put information about default versions to the docs.

**Comment by brunoborges** [comment]
I'd also very much like to see a single unique version being the default across all images. Right now, it is not consistent.

The latest LTS release is Java 11, fwiw, and a vendor-neutral build would be very much preferred, such as AdoptOpenJDK.

**Comment by nikita-bykov** [comment]
We have updated the information about default version of JDK. Images with new docs will be rolled out around next week.
If you want to suggest using a single unique version of JDK for all images, could you please open a separate issue for it.

**Comment by rbellamy** [comment]
Recent change to the [java-tools.sh](https://github.com/actions/virtual-environments/blob/0ddeb1ac4b2e81f45ba752d49ec5825b77141d40/images/linux/scripts/installers/java-tools.sh) file indicates that JDK 12 is the default, but the script sets `JAVA_HOME` to JDK 8. Shouldn't the script set `JAVA_HOME` to the default JDK?

https://github.com/actions/virtual-environments/blob/0ddeb1ac4b2e81f45ba752d49ec5825b77141d40/images/linux/scripts/installers/java-tools.sh#L10

https://github.com/actions/virtual-environments/blob/0ddeb1ac4b2e81f45ba752d49ec5825b77141d40/images/linux/scripts/installers/java-tools.sh#L75

**Comment by brunoborges** [comment]
@nikita-bykov Java 12 is not LTS. We on the Java team at Microsoft strongly advise to set an LTS as the default across all agents. Currently, the latest LTS is Java 11.

**Comment by nikita-bykov** [comment]
Fixed default label on Ubuntu. It was my typo and thank you for your report!
As for the suggestion to set the LTS version (Java 11) as default consistently across all images, we like this suggestion but worry about regression for some customers because if we update default Java from 8 to 11, their builds could be broken.
Probably, the appropriate communication is required here. That is the reason why we would like to track this request as a separate issue.

**Comment by brunoborges** [comment]
Ok, I'll submit a new issue then. Thanks.
