### ISSUE TITLE
[windows-2022] Some Visual C++ 2022 toolsets are not installed

### ISSUE THREAD

**Issue by zufuliu** [actions/virtual-environments#4051]
### Description

See build logs at https://github.com/zufuliu/notepad2/runs/3557274613?check_suite_focus=true
1. v141_xp  toolset (`Microsoft.VisualStudio.Component.WinXP`, `C++ Windows XP Support for VS 2017 (v141) tools [Deprecated]`) is not installed
> C:\Program Files\Microsoft Visual Studio\2022\Preview\MSBuild\Microsoft\VC\v170\Microsoft.CppBuild.targets(436,5): error MSB8020: The build tools for v141_xp (Platform Toolset = 'v141_xp') cannot be found. To build using the v141_xp build tools, please install v141_xp build tools.  Alternatively, you may upgrade to the current Visual Studio tools by selecting the Project menu or right-click the solution, and then selecting "Retarget solution". [D:\a\notepad2\notepad2\build\VS2017\Notepad2.vcxproj]

2. v143 ARM toolset (`Microsoft.VisualStudio.Component.VC.Tools.ARM`, `MSVC v143 - VS 2022 C++ ARM build tools (Latest)`) is not installed
> D:\a\notepad2\notepad2\build\VS2017\..\bin\Release\ARM\obj\Notepad2\LexAsm.obj : fatal error LNK1112: module machine type 'x64' conflicts with target machine type 'ARM' [D:\a\notepad2\notepad2\build\VS2017\Notepad2.vcxproj]

3. v143 ARM64 toolset (`Microsoft.VisualStudio.Component.VC.Tools.ARM64`, `MSVC v143 - VS 2022 C++ ARM64 build tools (Latest)`) is not installed
> C:\Program Files\Microsoft Visual Studio\2022\Preview\MSBuild\Microsoft\VC\v170\Microsoft.CppBuild.targets(436,5): error MSB8020: The build tools for v143 (Platform Toolset = 'v143') cannot be found. To build using the v143 build tools, please install v143 build tools.  Alternatively, you may upgrade to the current Visual Studio tools by selecting the Project menu or right-click the solution, and then selecting "Retarget solution". [D:\a\notepad2\notepad2\build\VS2017\Notepad2.vcxproj]

### Virtual environments affected

- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

https://github.com/zufuliu/notepad2/runs/3557274613?check_suite_focus=true

### Repro steps

```batch
git clone --depth=1 https://github.com/zufuliu/notepad2.git
cd notepad2\build\VS2017

call build_arm.bat
call build_arm64.bat
call build_win32.bat
```

**Comment by miketimofeev** [comment]
Hi @zufuliu!
We would rather avoid adding deprecated components (Microsoft.VisualStudio.Component.WinXP) to the VS as they may be removed in future VS updates. Does adding v143 ARM and ARM64 work for you in that case? In the meantime, could you please try to install all 3 workloads in runtime using the following powershell snippet?
```
Set-Location "C:\Program Files (x86)\Microsoft Visual Studio\Installer\"
$InstallPath = "C:\Program Files\Microsoft Visual Studio\2022\Preview"
$WorkLoads = '--add Microsoft.VisualStudio.Component.WinXP --add Microsoft.VisualStudio.Component.VC.Tools.ARM --add Microsoft.VisualStudio.Component.VC.Tools.ARM64'
$Arguments = ('/c', "vs_installer.exe", 'modify', '--installPath', "`"$InstallPath`"", $WorkLoads, '--quiet', '--norestart', '--nocache')
$process = Start-Process -FilePath cmd.exe -ArgumentList $Arguments -Wait -PassThru -WindowStyle Hidden
if ($process.ExitCode -eq 0)
{
    Write-Host "components have been successfully added"
}
else
{
    Write-Host "components were not installed"
    exit 1
}
```

**Comment by zufuliu** [comment]
Hi @miketimofeev, thanks for the snippet, it works.
Tested at https://github.com/zufuliu/notepad2/runs/3568843057?check_suite_focus=true#step:4:1
and (for clang-cl) https://github.com/zufuliu/notepad2/runs/3568842880?check_suite_focus=true

For XP, as https://docs.microsoft.com/en-us/visualstudio/releases/2022/compatibility#-visual-studio-2022-support-for-windows-development explicitly said no support for XP and Vista targeting, I'm fine to migrate to v143.

**Comment by miketimofeev** [comment]
@zufuliu thanks for the confirmation! We will add `Microsoft.VisualStudio.Component.VC.Tools.ARM `and `Microsoft.VisualStudio.Component.VC.Tools.ARM64` components to the image.

**Comment by MaksimZhukov** [comment]
Hello @zufuliu!
We've merged [related PR](https://github.com/actions/virtual-environments/pull/4081). The new image with these Visual Studio components will be deployed next week.

**Comment by miketimofeev** [comment]
@zufuliu the image has been deployed. I'm going to close the issue.
Feel free to contact us if you have any concerns.
Thank you!
