### ISSUE TITLE
Update/Add Microsoft GDK (GameCore) build support

### ISSUE THREAD

**Issue by DougGal-Microsoft** [actions/virtual-environments#4053]
### Tool name

Microsoft GDK (GameCore) build support

### Tool license

MICROSOFT PUBLIC GAME DEVELOPMENT KIT LICENSE AGREEMENT

### Add or update?

- [X] Add
- [ ] Update

### Desired version

June 2021 GDK Update 2 [19041.7011.210820-1500]

### Brief description of tool

In order to build a library for consumption in the GDK / GameCore environment, we need to build against the Gaming.Desktop.x64, Gaming.Xbox.Scarlett.x64, and Gaming.Xbox.XboxOne.x64 build platform in Visual Studio.  These ensure that we are linking against the appropriate libraries (the Gamecore umbrella GDK library instead of the Windows SDK link libraries) along with ensuring that the appropriate instruction set is used for the Xbox consoles.

In the short term, the Gaming.Desktop.x64 build platform is the most important as that includes the libraries and subset of instructions that will work across desktop and all console types.  The console specific build platforms add additional vector and other performance improvements, but their use is gated behind membership in the Xbox developer program.  The public desktop version of the GDK is available here: https://github.com/microsoft/GDK.

We'd like to have the public version of the GDK pri-installed for our builds (in this particular instance the msquic library: https://github.com/microsoft/msquic) so that we can automate it in our CI.

### URL for tool's homepage

https://github.com/microsoft/GDK

### Virtual environments affected

- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [X] Windows Server 2019
- [X] Windows Server 2022

**Comment by miketimofeev** [comment]
Hi @DougGal-Microsoft!
Could you please provide installation instructions so we can test the installation and consider adding the GDK to the images?

**Comment by DougGal-Microsoft** [comment]
1. Download the appropriate release (June 2021 Update 2) from the github repository: https://github.com/microsoft/GDK
2. Run the PGDK.exe from the downloaded release.

**Comment by al-cheb** [comment]
> 1. Download the appropriate release (June 2021 Update 2) from the github repository: https://github.com/microsoft/GDK
>    -https://github.com/microsoft/GDK/tree/June_2021_Update_2
> 2. Run the PGDK.exe from the downloaded release.

@DougGal-Microsoft , How can we install GDK in silent mode at runtime ?

**Comment by DougGal-Microsoft** [comment]
pgdk.exe /quiet /norestart

**Comment by miketimofeev** [comment]
@DougGal-Microsoft does GDK support visual studio 2022 or not yet? I'm asking as we try to understand should we add GDK to windows-2022 image or not

**Comment by nibanks** [comment]
@DougGal-Microsoft would be the one to know for sure, but I think it might just be best to start with windows-2019 for now.

**Comment by miketimofeev** [comment]
@nibanks thanks! We already discussed it with Doug and VS-2022 is not yet supported, so we have added GDK only for the windows-2019 image for now. The changes will be deployed next week.

**Comment by shilovmaksim** [comment]
Hi @DougGal-Microsoft , @nibanks .
GDK package installing on a machine whole bunch of tools including AzureRM PowerShell modules which breaking our tests.
Could you please tell us whether installation can be minimized to the list of tools required only?

**Comment by nibanks** [comment]
I don't know any useful details here, so I'll have to leave it to @DougGal-Microsoft to answer.

**Comment by DougGal-Microsoft** [comment]
I can't find any way to install it only partially.  Several studios are known to install it on one machine and just copy binaries around through their build system, but that's not an officially supported scenario.  In this case, it's unclear if there is a parallel or not.

**Comment by shilovmaksim** [comment]
@DougGal-Microsoft , is it possible to you to install GDK during runtime?

**Comment by shilovmaksim** [comment]
@DougGal-Microsoft , gentle reminder.
Could you please try whether it's applicable to you to install GDK in the runtime as a step before your build with a [snippet provided earlier](https://github.com/actions/virtual-environments/issues/4053#issuecomment-930206263)?

**Comment by nibanks** [comment]
Just to be clear, @DougGal-Microsoft, does installing the GDK require a reboot? If so, it can't be installed at runtime.
