### ISSUE TITLE
Since yesturday my driver build actions fail

### ISSUE THREAD

**Issue by DavidXanatos** [actions/virtual-environments#4055]
### Description

Since yesterday (or may be a few days before) something has changed with the CI for VS2019 on server2019, it fails to build my driver : https://github.com/sandboxie-plus/Sandboxie/runs/3559852778?check_suite_focus=true
with the error
```         C:\Program Files (x86)\Windows Kits\10\build\WindowsDriver.common.targets(222,5): error : A WDK corresponding to target version '10.0.19041.0' was not found. Please install this WDK version before building. [D:\a\Sandboxie\Sandboxie\Sandboxie\core\drv\SboxDrv.vcxproj]```
on my end nothing changed, i tried changing WDK version and also building on server2022 but nothing worked.

Please help me resolving this issue.

### Virtual environments affected

- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [X] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Current runner version: '2.281.1'

### Is it regression?

yes a week ago everythign worked perfectly

### Expected behavior

Build success

### Actual behavior

Build fails with the aforementioned error

### Repro steps

Try building the sandboxie+ repo

**Comment by al-cheb** [comment]
Hey, @DavidXanatos 
Could you try to set wdk version - https://docs.microsoft.com/en-us/windows-hardware/drivers/wdk-known-issues?

**Error ‘A WDK corresponding to target ’10.0.19041.0’ was not found.’**
When selecting [Windows SDK Version] to '10.0 (latest installed version)' with WDK 10.0.19041.0 causes the "A WDK corresponding to target version '10.0.19041.0' was not found" error even if the SDK version is installed.

Workaround: In the properties page for the driver project (Configuration Properties >General) set Windows SDK Version to $(LatestTargetPlatformVersion). If this option is not available to select then select the option inherit from parent or project default.

**Comment by DavidXanatos** [comment]
thanks using $(LatestTargetPlatformVersion) fixed the issue thanks
