### ISSUE TITLE
Powershell task AzurePowerShell@5 fails on Microsoft Hosted Agents windows-2019

### ISSUE THREAD

**Issue by ITSTord** [actions/virtual-environments#4057]
### Description

Since this morning powershell scripts have failed with: A parameter cannot be found that matches parameter name ***
This only happens on Microsoft hosted agents and have worked prior to this morning. Successful builds from yesterday have been rerun and ends with same failure. 

### Virtual environments affected

- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [X] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

image version: 20210907.4

### Is it regression?

image version: 20210903.7

### Expected behavior

Parameters to be resolved and resource to be created

### Actual behavior

Throws an error stating that the parameter can not be found even though it worked with same commit the day before. 

### Repro steps

Create a powershell function and call it later on: 
function testBehaviour([string]$test , [string]$test2 ){write-host "will not work cause of $test or $test2"}

testBehaviour "firstparameter" "secondparameter"

**Comment by al-cheb** [comment]
Hey, @ITSTord 
Could you provide logs?

- Task version
- Yaml 
- Error screen

**Comment by ITSTord** [comment]
Yes, 
Task version : AzurePowerShell@5


`parameters:
  azureSubscription: ""
  env: ""
jobs:
  - deployment: Infrastructure
    displayName: Creating Infrastructure for ${{ parameters.env }}
    pool:
      vmImage: "windows-latest"
    workspace:
      clean: all
    environment: ${{ parameters.env }}
    strategy:
      runOnce:
        deploy:
          steps:

            - checkout: self
              path: core

            - checkout: templates
              path: templates

            - task: AzurePowerShell@5
              condition: and(succeeded(), or(eq(variables['Build.SourceBranch'], 'refs/heads/main'), startsWith(variables['Build.SourceVersionMessage'], 'preview:')))
              displayName: "Create KeyVault and ResourceGroup in env: ${{ parameters.env }}"
              inputs:
                azureSubscription: ${{ parameters.azureSubscription }}
                ScriptPath: "../core/Infrastructure/deploy.ps1"
                ScriptArguments: "-environment ${{ parameters.env }} -templateFileAP ../templates/AKV/accessPolicy.json"
                azurePowerShellVersion: LatestVersion`

![taskFailure](https://user-images.githubusercontent.com/54802153/132843326-e3b35796-8c4f-4768-a449-104424ebca92.png)

**Comment by al-cheb** [comment]
@ITSTord,
How do  you pass `kvname` param to the deploy.ps1 script?
 
 E.g. output:
```
 steps:
- task: AzurePowerShell@5
  displayName: 'Azure PowerShell script: FilePath'
  inputs:
    azureSubscription: 'sub'
    ScriptPath: deploy.ps1
    ScriptArguments: '-environment env_test -templateFileAP ../templates/AKV/accessPolicy.json'
    azurePowerShellVersion: LatestVersion
```
![123](https://user-images.githubusercontent.com/47745270/132845145-d7491d42-3502-489b-9473-b3089ef6caec.JPG)

**Comment by ITSTord** [comment]
![scriptFailure](https://user-images.githubusercontent.com/54802153/132845539-fb48483b-e143-4d4f-a729-50952594f28c.png)
We have multiple other different scripts throwing exceptions on not found parameter as well. So this is just one example.

**Comment by ITSTord** [comment]
![scriptFailure](https://user-images.githubusercontent.com/54802153/132845833-c7f40368-8822-44f7-b116-33f016f52d26.png)
This is just one example, we have multiple scripts throwing the same exception regarding parameters after the agent image version where bumped.

**Comment by al-cheb** [comment]
@ITSTord,
I can't reproduce. Looks like the issue in the script and not related to the task itself.

```
param(
    $environment,
    $templateFileAP
)

function CreateKeyVault([string]$kvname, [string]$rg, [string]$loc, [string]$tag, [string]$sp) {
    Write-Host $PsBoundParameters
}

Write-Host "`$environment: $environment, `$templateFileAP: $templateFileAP"
CreateKeyVault "kvname" "rg" "loc" "tag" "sp"
```
![Capture](https://user-images.githubusercontent.com/47745270/132846900-62757546-8ec7-4625-a149-19e3ee7f1638.JPG)

**Comment by ITSTord** [comment]
Fair point that you can't reproduce. But the exact same commit ran fine on previous image version. Ill try to further debug it and come back with some more information.

**Comment by al-cheb** [comment]
@ITSTord ,
I couldn't find find alias kvname for `New-AzResourceGroupDeployment` which you use in the script at line 14. Could you check it?
```
PS > (Get-Command New-AzResourceGroupDeployment).Parameters.GetEnumerator() | % {$_.Value.Aliases}
DeploymentName
AzContext
AzureRmContext
AzureCredential
vb
db
ea
wa
infa
ev
wv
iv
ov
ob
pv
wi
cf

```

**Comment by ITSTord** [comment]
the templatefile specified (accessPolicy.json) have kvname as a parameter. But it works on all images except windows-2019.

**Comment by al-cheb** [comment]
@ITSTord , Are you sure that kvname param exists?
![image](https://user-images.githubusercontent.com/47745270/132863512-1f3171fb-081a-4d1c-9953-1f9a62e80ba2.png)

**Comment by ITSTord** [comment]
yes, and as i've said it ran fine on previous versions of windows-2019. Stopped working yesterday, no changes to the code. I run it fine on windows-2022/ ubuntu-latest. So if it did not exist in the templatefile it would fail for all agent images.

**Comment by ajhanson** [comment]
We are seeing the same issue in an AzurePowerShell@4 task (deploying an arm template)

Just started failing yesterday morning when 20210907.4 is used (if a retry gets 20210903.7, it succeeds).

````
Friday, September 10, 2021 1:08:41 PM
An error occurred:
A parameter cannot be found that matches parameter name 'keyVaultName'.
use existing connection was true and disconnect will be ignored
##[warning]A parameter cannot be found that matches parameter name 'and'.
##[error]A parameter cannot be found that matches parameter name 'keyVaultName'.
````

**Comment by al-cheb** [comment]
> yes, and as i've said it ran fine on previous versions of windows-2019. Stopped working this morning, no changes to the code. I run it fine on windows-2022/ ubuntu-latest. So if it did not exist in the templatefile it would fail for all agent images.

The same error on local machine:
```
PS > New-AzResourceGroupDeployment -TemplateFile .\template.json -kvname "abc" -sp $sp -ResourceGroupName test
New-AzResourceGroupDeployment : A parameter cannot be found that matches parameter name 'kvname'.
```

**Comment by al-cheb** [comment]
Looks like the known issue with New-AzResourceGroupDeployment cmdlet - https://github.com/Azure/azure-powershell/issues/15841

Try to set `Azure PowerShell version to 6.3.0`

**Comment by ITSTord** [comment]
setting psversion to 6.3.0 solved it. Thank you

**Comment by mattnpvm** [comment]
![image](https://user-images.githubusercontent.com/90461837/133448013-f6db7752-b9ce-4d9a-84d0-343031fdbfbd.png)
Using an inline script in Azure PowerShell v4/5

**Comment by al-cheb** [comment]
@mattnpvm , please set Az at least version 6.3.0 in the task.

**Comment by mattnpvm** [comment]
> @mattnpvm , please set Az at least version 6.3.0 in the task.

How do I do that if 6.3 isn't installed on the Microsoft hosted agent? 
![image](https://user-images.githubusercontent.com/90461837/133452739-a2bc8da2-d18c-4086-b72c-9d1dee81b01f.png)

**Comment by al-cheb** [comment]
@mattnpvm , It will be downloaded at runtime.
![image](https://user-images.githubusercontent.com/47745270/133565270-4422487a-50f6-4e18-8663-f24c4065ce91.png)

**Comment by jikuja** [comment]
Does the task cache downloaded Az modules properly or would it be better to use an older version for performance?

**Comment by al-cheb** [comment]
> Does the task cache downloaded Az modules properly or would it be better to use an older version for performance?

It takes 3-5s to install a new version to the cache and works quite good.

**Comment by jikuja** [comment]
Are files downloaded by task into $env:SystemDrive + "\Modules" or "/usr/share" folder cached between multiple jobs?

**Comment by al-cheb** [comment]
> Are files downloaded by task into $env:SystemDrive + "\Modules" or "/usr/share" folder cached between multiple jobs?
@jikuja,
 
Windows:
```
Extracting archive: C:\Modules\az_6.3.0.zip
Import-Module -Name C:\Modules\az_6.3.0\Az.Accounts\2.5.2\Az.Accounts.psd1 -Global
```
Ubuntu:
```
Saved!
Az version 6.3.0 not avaiable locally on the agent. Downloading dynamically.
Import-Module -Name /usr/share/az_6.3.0/Az.Accounts/2.5.2/Az.Accounts.psd1 -Global
```

**Comment by al-cheb** [comment]
The new Windows Server images with Az 6.4.0 on board have been deployed.

**Comment by PaulVrugt** [comment]
We have the same issue on our private agent, but in our case we have already installed azure powershell 6.4.0. Even when specifying a different preferredAzurePowerShellVersion the warning still appears

**Comment by al-cheb** [comment]
> We have the same issue on our private agent, but in our case we have already installed azure powershell 6.4.0. Even when specifying a different preferredAzurePowerShellVersion the warning still appears

Could you please show `Get-Module Az.Resources -ListAvailable` ?

**Comment by PaulVrugt** [comment]
```
ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     4.3.1      Az.Resources                        {Get-AzProviderOperation, Remove-AzRoleAssignment, Get-AzR...
Script     3.4.1      Az.Resources                        {Get-AzProviderOperation, Remove-AzRoleAssignment, Get-AzR...
Script     3.1.1      Az.Resources                        {Get-AzProviderOperation, Remove-AzRoleAssignment, Get-AzR...
Script     2.5.1      Az.Resources                        {Get-AzProviderOperation, Remove-AzRoleAssignment, Get-AzR...
Script     2.3.0      Az.Resources                        {Get-AzProviderOperation, Remove-AzRoleAssignment, Get-AzR...
```

**Comment by PaulVrugt** [comment]
Yes that seems to fix the issue. Thanks @al-cheb

**Comment by mfe-** [comment]
Is it possible that this failure occurs on PowerShell tasks as well?

```
Starting: Generate Changelog with PowerShell
==============================================================================
Task         : PowerShell
Description  : Run a PowerShell script on Linux, macOS, or Windows
Version      : 2.194.0
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/powershell
==============================================================================
Generating script.
========================== Starting Command Output ===========================
"C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe" -NoLogo -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command ". 'D:\a\_temp\88ee244f-88c6-4858-90d6-4fe42e998d32.ps1'"
Generating Changelog
D:\a\1\s\AdbApp\generate_changelog.ps1 : A parameter cannot be found that matches parameter name 'cdgitfolder'.
At D:\a\_temp\88ee244f-88c6-4858-90d6-4fe42e998d32.ps1:6 char:34
+ AdbApp\generate_changelog.ps1 -cdgitfolder AdbApp -branch "main ...
+                                  ~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [generate_changelog.ps1], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : NamedParameterNotFound,generate_changelog.ps1
 
##[error]PowerShell exited with code '1'.
Finishing: Generate Changelog with PowerShell
```

I can execute the powershell script locally with the same parameters without any problems. It looks like the maximum parameters I can use within azure pipelines are two.

```
Agent name: 'Azure Pipelines 2'
Agent machine name: 'fv-az182-808'
Current agent version: '2.194.0'
Operating System
Microsoft Windows Server 2019
10.0.17763
Datacenter
Virtual Environment
Environment: windows-2019
Version: 20211102.4
Included Software: https://github.com/actions/virtual-environments/blob/win19/20211102.4/images/win/Windows2019-Readme.md
Image Release: https://github.com/actions/virtual-environments/releases/tag/win19%2F20211102.4
Virtual Environment Provisioner
1.0.0.0-master-20211022-1
Current image version: '20211102.4'
Agent running as: 'VssAdministrator'
Prepare build directory.
Set build variables.
Download all required tasks.
Downloading task: CmdLine (2.182.0)
Downloading task: PowerShell (2.194.0)
```

**Comment by al-cheb** [comment]
@mfe- , Could you please provide the script and how do you pass parameters to it?

**Comment by mfe-** [comment]
@al-cheb I just tried to create a public repository where the issue occurs, but it looks like it's not reproduceable anymore. Maybe I have overlooked something.  If I find something I'll let you know. Thanks
