### ISSUE TITLE
Not able to compila a C++ application that include cstdint/cstdbool using Ninja generator

### ISSUE THREAD

**Issue by kenr** [actions/virtual-environments#406]
**Describe the bug**
Not able to compile a C++ application that include cstdint/cstdbool using ninja as generator.

**Area for Triage**: 
C/C++

**Question, Bug, or Feature?**: 
Bug

**Virtual environments affected**
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ X] Windows Server 2016 R2
- [X ] Windows Server 2019

**Expected behavior**
Successful compilation of code using cstdint/cstdbool

**Actual behavior**
Code: https://github.com/kenr/repro
Build: https://dev.azure.com/KenRedergard/repro/_build?definitionId=1&_a=summary

**Comment by al-cheb** [comment]
Hello, @kenr 

I was able to compile from your repo with parameters: `-Dspdlog_DIR=C:\vc\packages\spdlog_x64-windows\share\spdlog -Dfmt_DIR=C:\vc\packages\fmt_x64-windows\share\fmt -DCatch2_DIR=C:\vc\packages\catch2_x64-windows\share\Catch2`

Example:
```
name: CI
on: [push]

jobs:
  build:
    runs-on: [windows-latest]
    steps:
      - name: vcpkg
        run: |
          git clone https://github.com/Microsoft/vcpkg.git C:\vc
          cd /d C:\vc
          bootstrap-vcpkg.bat
        shell: cmd
      - name: cmake
        run: |
          call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\vc\Auxiliary\build\vcvarsall.bat" x64
          del "C:\ProgramData\chocolatey\bin\c++.exe"
          del "C:\ProgramData\chocolatey\bin\g++.exe"
          del "C:\ProgramData\chocolatey\bin\gcc.exe"
          del "C:\Strawberry\c\bin\c++.exe"
          del "C:\Strawberry\c\bin\g++.exe"
          del "C:\Strawberry\c\bin\gcc.exe"
          mkdir C:\test
          cd /d C:\test
          git clone https://github.com/kenr/repro.git
          cd repro
          C:\vc\vcpkg.exe install spdlog:x64-windows catch2:x64-windows 
          cmake -H. -B_build -GNinja -DCMAKE_CXX_STANDARD=17 -DCMAKE_INSTALL_PREFIX=C:\artifact -DBUILD_SHARED_LIBS=ON -Dspdlog_DIR=C:\vc\packages\spdlog_x64-windows\share\spdlog -Dfmt_DIR=C:\vc\packages\fmt_x64-windows\share\fmt -DCatch2_DIR=C:\vc\packages\catch2_x64-windows\share\Catch2
          cmake --build _build --config debug --target install
        shell: cmd

```
![cmake - Copy](https://user-images.githubusercontent.com/47745270/74684314-a8827b80-51dc-11ea-801d-fd7ab97ab7bb.JPG)

**Comment by kenr** [comment]
Thank you for getting back to me @al-cheb, 
I tried providing the parameters you use to the Azure DevOps build, but I still get the same problem. 

I also stripped away vcpkg and made the repro much smaller, it still does not compile. I run this on a Microsoft hosted Azure DevOps agent.

The code is updated in the repo, here is the build:
https://dev.azure.com/KenRedergard/repro/_build/results?buildId=12&view=results

**Comment by al-cheb** [comment]
I was able to compile: -Dspdlog_DIR=C:\vc\packages\spdlog_x64-windows\share\spdlog -Dfmt_DIR=C:\vc\packages\fmt_x64-windows\share\fmt -DCatch2_DIR=C:\vc\packages\catch2_x64-windows\share\Catch2

Example:

```
pool:
   name: 'Azure Pipelines'
   vmImage: 'vs2017-win2016'
steps:
  - script: |
     choco install ninja
  - script: |
     git clone https://github.com/Microsoft/vcpkg.git C:\vc
     cd /d C:\vc
     bootstrap-vcpkg.bat
  - script: |
     call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\vc\Auxiliary\build\vcvarsall.bat" x64
     del "C:\ProgramData\chocolatey\bin\c++.exe"
     del "C:\ProgramData\chocolatey\bin\g++.exe"
     del "C:\ProgramData\chocolatey\bin\gcc.exe"
     del "C:\Strawberry\c\bin\c++.exe"
     del "C:\Strawberry\c\bin\g++.exe"
     del "C:\Strawberry\c\bin\gcc.exe"
     C:\vc\vcpkg.exe install spdlog:x64-windows catch2:x64-windows 
     cmake -H. -B_build -GNinja -DCMAKE_CXX_STANDARD=17 -DCMAKE_INSTALL_PREFIX=C:\artifact -DBUILD_SHARED_LIBS=ON -Dspdlog_DIR=C:\vc\packages\spdlog_x64-windows\share\spdlog -Dfmt_DIR=C:\vc\packages\fmt_x64-windows\share\fmt -DCatch2_DIR=C:\vc\packages\catch2_x64-windows\share\Catch2
     cmake --build _build --config debug --target install
```


![compile - Copy](https://user-images.githubusercontent.com/47745270/74751334-264a9380-527e-11ea-8eff-44595ca68958.JPG)

**Comment by kenr** [comment]
@al-cheb , I do not understand this, we are doing the exact same thing and it works on your build but not mine.

Could there be a difference between [regions](https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/change-organization-location?view=azure-devops)? I have region West Europe.

Could you provide the raw build that you have? For both the cmake generator step and the build step?

**Comment by al-cheb** [comment]
@kenr, Region: West Central US

repo - https://github.com/al-cheb/repro/edit/master/azure-pipelines.yml

[1 step - ninja.txt](https://github.com/actions/virtual-environments/files/4234833/1.step.-.ninja.txt)
[2 step - cmake.txt](https://github.com/actions/virtual-environments/files/4234834/2.step.-.cmake.txt)
[3 step- cmake build.txt](https://github.com/actions/virtual-environments/files/4234832/3.step-.cmake.build.txt)

**Comment by kenr** [comment]
It seems like the cmake cache did not capture the full path for everything when running the generator. Calling vcvarsall.bat for all scripts make it work.
