### ISSUE TITLE
macOS-latest workflows will use macOS-11

### ISSUE THREAD

**Issue by miketimofeev** [actions/virtual-environments#4060]
### Breaking changes

macOS-11 is ready to be the default version for the "macos-latest" label in GitHub Actions and Azure DevOps.

### Target date

This change will be rolled out over a period of several weeks beginning on September, 15. We plan to complete the migration by ~~November, 3~~ ~~December, 13~~ January 14.

### The motivation for the changes

GitHub Actions and Azure DevOps have supported macOS-11 in preview mode since October 2020, and starting from August 2021 macOS-11 is generally available for all customers. For almost a year we have monitored customer feedback to improve the macOS-11 image stability and now we are ready to set it as the latest.

### Possible impact

The macOS-11 image has a different set of software than macOS-10.15. The most significant changes are listed in the table below:

|Tool name|macOS-10.15|macOS-11|Notes|
|-|:-:|-|-|
|R lang|4.*|-| R was not available for Big Sur when we prepared the image for the first time. Please use standard tool request process if the tool needs to be added |
|Virtualbox and Vagrant|6.* and 2.*|-| Virtualbox on macOS 11 requires security preferences changes, which can't be easily done. The PR with virtualbox is not yet merged https://github.com/actions/virtual-environments/pull/4010 |
|Java|8(default)<br>11<br>12<br>13|8(default)<br>11| Due to our software guidelines we left only LTS versions on the image. If you need to use other versions of Java, consider using [setup-java](https://github.com/actions/setup-java) and [Java tool installer](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/tool/java-tool-installer?view=azure-devops) tasks |
|Python toolcache|2.7<br>3.5<br>3.6<br>3.7<br>3.8<br>3.9|3.7<br>3.8<br>3.9| EOL python versions were deprecated |
|PyPy toolcache|2.7<br>3.6<br>3.7|2.7<br>3.7| Version 3.6 was deprecated as it won't receive any updates |
|Go toolcache|1.13<br>1.14<br>1.15<br>1.16<br>1.17|1.15<br>1.16<br>1.17| EOL go versions were deprecated |
|Xamarin.Mono| 6.4 - 6.12 | 6.12 | Old versions and versions incompatible with the pre-installed Xcodes were removed |
|Xamarin.iOS| 13.2 - 14.10 | 13.20 - 14.20 | Old versions and versions incompatible with the pre-installed Xcodes were removed |
|Xamarin.Mac| 6.2 - 7.8 | 6.20 - 7.14 | Old versions and versions incompatible with the pre-installed Xcodes were removed |
|Xamarin.Android| 10.0 - 11.2 | 11.0 - 11.3 | Old versions and versions incompatible with the pre-installed Xcodes were removed |
|Xcode| 12.4 (default)<br>12.3<br>12.2<br>12.1.1<br>12.1<br>12.0.1<br>11.7<br>11.6<br>11.5<br>11.4.1<br>11.3.1<br>11.2.1<br>10.3 | 13.0 (beta)<br>12.5.1 (default)<br>12.5<br>12.4<br>11.7 | Only OS-compatible versions left + the latest 11 version |
|Android SDK build-tools and platforms | 24 - 31 | 27 - 31 | Android Platforms and build tools < 27.0 were removed from image. Consider installation in runtime using sdkmanager |

### Virtual environments affected

- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [X] macOS 10.15
- [X] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Mitigation ways

If you see any issues with your workflows during this transition period:

- File an issue in this repository
- Switch back to macOS 10.15 by specifying the “macOS-10.15" label. We will continue to support macOS 10.15.

**Comment by spoelstraethan** [comment]
This should probably be given higher priority or a sooner release date, with iOS 15 becoming widely available to end users on September 20.

In our experience the iOS 15 betas are already requiring the new digital signatures that only seem to be available in Xcode 12.5.x, so any Apple Enterprise program users signing applications with the `macos-10.15` image are going to see their apps not launching on iOS 15 if they are installing them via AppCenter.ms or anywhere but TestFlight/App Store.

It appears that Xcode 12.5.x is only available on the macos-11 image and Apple doesn't support it on Catalina aka 10.15 so either you will have a LOT of customers using the default `macos-latest` image reaching out for support or spending hours (or days) trying to figure out the issue, or you could save them a lot of hassle and update the tag for everybody.

**Comment by zi6xuan** [comment]
When I compiled the ios version of the flutter project on actions, the script script of the ios project got stuck. Stuck at the last script running. I was stuck for six hours and was eventually cancelled because time ran out.

```
Project type: flutter
Compilation platform: iOS
Compilation tool: fastlane
```

**Comment by miketimofeev** [comment]
@zi6xuan feel free to create a new issue and we will try to help you

**Comment by ettore** [comment]
Meanwhile, this forum post highlights the iOS re-signing details on macOS 10.15 / Xcode 12 to solve the new signature issues on iOS 15 devices:
https://developer.apple.com/forums/thread/682775

**Comment by jimhester** [comment]
FWIW the first R-4.1.1.pkg link for Intel based Macs at https://cloud.r-project.org/bin/macosx/ does support Big Sur (I have been using it on Big Sur myself for months now), however the explanatory text does not seem to have been updated to reflect this.

**Comment by miketimofeev** [comment]
@jimhester feel free to open Add request in this repo and we will add R to the Big Sur image.

**Comment by bionanek** [comment]
Just out of curiosity - why does this update take so long after new iOS and MacOS has been already officially released by Apple? I mean, If it's gonna be done by November 3rd it's gonna be +/- 3 months without proper GitHub support for this kind of environments.

**Comment by ShadowJonathan** [comment]
> EOL python versions were deprecated

Technically 2.7 is also deprecated, why is it included in the image?

**Comment by palumbo67** [comment]
Getting the following error when running tns test android on macOS-latest (11.6)
```
Execution failed for task ':app:stripDebugDebugSymbols'.
No toolchains found in the NDK toolchains folder for ABI with prefix: arm-linux-androideabi
```

I even get this error when running it against 10.15. Did something change?

**Comment by miketimofeev** [comment]
@palumbo67 could be related to this https://github.com/actions/virtual-environments/issues/3894

**Comment by palumbo67** [comment]
@miketimofeev so I can technically run my unit tests in ubuntu-latest instead of macOS-latest

**Comment by FarahaDadvarDeveloper** [comment]
Hi All, 
Any update on when the macOS host agent will support XCode 13?
Kind regards

**Comment by al-cheb** [comment]
> Hi All, Any update on when the macOS host agent will support XCode 13? Kind regards

It is already available.
https://github.com/actions/virtual-environments/blob/main/images/macos/macos-11-Readme.md
<html>
<body>
<h3 style="box-sizing: border-box; margin-top: 24px; margin-bottom: 16px; font-size: 1.25em; font-weight: 600; line-height: 1.25; color: rgb(36, 41, 47); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Xcode</h3>

Version | Build | Path
-- | -- | --
13.0 (beta) | 13A5212g | /Applications/Xcode_13.0_beta.app
13.0 | 13A233 | /Applications/Xcode_13.0.app


</body>
</html>

**Comment by sami1971** [comment]
Any update when Xamarin IOS builds will support XCode 13? There doesn't seem to be way to make Visual Studio to use 13 instead of Xcode_12.5.1.

**Comment by sami1971** [comment]
> xamarin/xamarin-macios#12778

Yes, the updates were published today. Wondering when they will be available on the Azure pipeline. Currently the builds use 12.5.1 as Xamarin.iOS 14.20 is the latest available. Will we be getting 15.0.0.6 anytime soon on the image?

**Comment by hbeni** [comment]
Hi, I get the following error (https://github.com/hbeni/fgcom-mumble/actions/runs/1293281303):
The log tells me, that on `macos-latest` openssl is not found.
Yesterday it run just fine. Today even switching back to `macOS-10.15` does drop the same error.

```
2021-10-01T01:03:56.8559230Z make CC=g++-11 outname=fgcom-mumble-macOS.bundle CFLAGS="-I/usr/local/opt/openssl/include/ -L/usr/local/opt/openssl/lib/" plugin
2021-10-01T01:03:56.9026430Z g++-11 -shared -fPIC -o fgcom-mumble-macOS.bundle lib/radio_model.o lib/audio.o lib/io_plugin.o lib/io_UDPServer.o lib/io_UDPClient.o lib/garbage_collector.o fgcom-mumble.cpp -lssl -lcrypto -DSSLFLAGS -I/usr/local/opt/openssl/include/ -L/usr/local/opt/openssl/lib/ -Wall -O3 -I. -I./lib  -pthread
2021-10-01T01:03:57.2057260Z In file included from ./lib/updater.cpp:55,
2021-10-01T01:03:57.2060090Z                  from fgcom-mumble.cpp:1148:
2021-10-01T01:03:57.2061970Z ./lib/http/httplib.h:210:10: fatal error: openssl/err.h: No such file or directory
```

**Comment by miketimofeev** [comment]
Hi @hbeni, you faced the same issue probably https://github.com/actions/virtual-environments/issues/4195

**Comment by al-cheb** [comment]
Hey, @hbeni
Could you please use `/usr/local/opt/openssl` ->  `/usr/local/opt/openssl@1.1` path?

**Comment by hbeni** [comment]
@al-cheb @miketimofeev 
Thank you, works!

**Comment by AraHaan** [comment]
Too bad we cant specify that we want the latest MacOS 12 Beta if we are writing code that depends on explicitly using that to build + run tests.

**Comment by miketimofeev** [comment]
@mportune-bw you don't need this rollout to build for iOS15. `macos-11` runners are already available so the change only affects the `macos-latest` tag

**Comment by pronebird** [comment]
Since macOS 11 it's impossible to symlink iOS 12.4 runtime anymore since Xcode 10.3 is not shipped with the image anymore. Without it it's impossible to run tests for apps that support iOS 12 - 15 range. The one would need Xcode 13 for that. 

Using `Xcode-install` I can easily add iOS 12 sim but it takes 10 minutes to install. It takes ages then to run tests.

```
xcversion simulators --install='iOS 12.4 Simulator'
```

Please provide some sort of solution to avoid doing that because it takes very long time to get anything tested.

**Comment by Rus1an31** [comment]
@miketimofeev Today is November, 2. We're still see warnings "##[warning]macOS-latest pipelines will use macOS-11 soon" in our builds. Can you tell please when migration will be completed? It's blocking us to use iOS 15.

**Comment by miketimofeev** [comment]
@Rus1an31 sorry for the inconvenience, the migration is delayed till December. You can explicitly point your builds to the `macos-11` image label until that.

**Comment by joshepkt** [comment]
When doing a nuget restore on a xamarin solutions with windows, ios, and android I am getting ##[error]The nuget command failed with exit code(1) and error(/Users/runner/work/1/s/YYY/YYY.UWP/YYYY.UWP.csproj : error MSB4057: The target "_IsProjectRestoreSupported" does not exist in the project.  It works if the vmImage version is 11.6, but not 11.6.1

**Comment by MaksimZhukov** [comment]
Hello @joshepkt! 
We have updated Mono version from `6.12.0.125` to `6.12.0.140`. The default behavior of the `nuget restore` command has been changed. Previously, this command skipped restoring for project if the project file is invalid. For now, it throws the error. 

Could you please confirm if restoring for the `YYYY.UWP.csproj` project was skipped in your successful builds?

Also, could you please try using  `dotnet restore` or `msbuild -t:restore` command as a possible workaround?

**Comment by krishpranav** [comment]
is there any way to sign development team to building a swift app in GitHub workflows????

**Comment by joshepkt** [comment]
@MaksimZhukov, Yes in the ones that worked, it looks like it errored out and skipped the UWP project.

From a working one:
/Users/runner/work/1/s/YYYY/YYYY.UWP/YYYY.UWP.csproj : error MSB4057: The target "_IsProjectRestoreSupported" does not exist in the project.
/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/NuGetScratch/rque8wsk.68l.nugetrestore.targets(315,5): warning : Skipping restore for project '/Users/runner/work/1/s/YYYY/YYYY.UWP/YYYY.UWP.csproj'. The project file may be invalid or missing targets required for restore. [/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/NuGetScratch/9ax69yfn.nz4.nugetinputs.targets]

I was able to work around by explicitly running the restore command for the csproj file and its referenced project(s).  I will work on switching it to `msbuild -t:restore` and see if that works.

**Comment by chowarth** [comment]
> When doing a nuget restore on a xamarin solutions with windows, ios, and android I am getting ##[error]The nuget command failed with exit code(1) and error(/Users/runner/work/1/s/YYY/YYY.UWP/YYYY.UWP.csproj : error MSB4057: The target "_IsProjectRestoreSupported" does not exist in the project. It works if the vmImage version is 11.6, but not 11.6.1

We're also seeing this same issue today. So far I've not had much luck getting it sorted; using `msbuild -t:restore` allowed the NuGet restore to complete but caused the iOS build to fail (Android was fine) thinking that the packages/references weren't there.

**Comment by TriplEight** [comment]
using the `macos-latest` just got a job executed by
![image](https://user-images.githubusercontent.com/17856421/140303182-652236ab-d32b-4c24-9c4d-7ef5128967a7.png)
and my binary is no longer executable neither on macos-11 nor macos-10.5

**Comment by chevdor** [comment]
FYI: I had CI runs this morning using `macos-latest`. They did run on MacOS 11. They produced binaries running in the runner but **not** valid on an Intel Mac running 11.6 (Big Sur).

Specifying `macos-10.15` instead of `macos-latest` as suggested in the issue indeed solves the issue for now.

**Comment by anders9ustafsson** [comment]
> When doing a nuget restore on a xamarin solutions with windows, ios, and android I am getting ##[error]The nuget command failed with exit code(1) and error(/Users/runner/work/1/s/YYY/YYY.UWP/YYYY.UWP.csproj : error MSB4057: The target "_IsProjectRestoreSupported" does not exist in the project. It works if the vmImage version is 11.6, but not 11.6.1

It seems like a temporary workaround is to add a dummy target in the UWP project file, i.e.

      <Target Name="_IsProjectRestoreSupported" />

I guess this workaround should be handled with caution, since I think including this target in the UWP project file will override correctly implemented instances of the `_IsProjectRestoreSupported` target. But until the original problem is fixed, this might be a better way forward e.g. than downgrading the Xamarin SDK.

**Comment by MuddyChrisA** [comment]
> > When doing a nuget restore on a xamarin solutions with windows, ios, and android I am getting ##[error]The nuget command failed with exit code(1) and error(/Users/runner/work/1/s/YYY/YYY.UWP/YYYY.UWP.csproj : error MSB4057: The target "_IsProjectRestoreSupported" does not exist in the project. It works if the vmImage version is 11.6, but not 11.6.1
> 
> It seems like a temporary workaround is to add a dummy target in the UWP project file, i.e.
> 
> ```
>   <Target Name="_IsProjectRestoreSupported" />
> ```
> 
> I guess this workaround should be handled with caution, since I think including this target in the UWP project file will override correctly implemented instances of the `_IsProjectRestoreSupported` target. But until the original problem is fixed, this might be a better way forward e.g. than downgrading the Xamarin SDK.

This does not work for me as it breaks my UWP build 

Error WMC9999: Type universe cannot resolve assembly: System.Runtime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a.

**Comment by JoeDiesel40** [comment]
So running  this  would  do what?

**Comment by 3033071101** [comment]
> ### Breaking changes
> macOS-11 is ready to be the default version for the "macos-latest" label in GitHub Actions and Azure DevOps.
> 
> ### Target date
> This change will be rolled out over a period of several weeks beginning on September, 15. We plan to complete the migration by ~November, 3~ December, 13.
> 
> ### The motivation for the changes
> GitHub Actions and Azure DevOps have supported macOS-11 in preview mode since October 2020, and starting from August 2021 macOS-11 is generally available for all customers. For almost a year we have monitored customer feedback to improve the macOS-11 image stability and now we are ready to set it as the latest.
> 
> ### Possible impact
> The macOS-11 image has a different set of software than macOS-10.15. The most significant changes are listed in the table below:
> 
> Tool name	macOS-10.15	macOS-11	Notes
> R lang	4.*	-	R was not available for Big Sur when we prepared the image for the first time. Please use standard tool request process if the tool needs to be added
> Virtualbox and Vagrant	6.* and 2.*	-	Virtualbox on macOS 11 requires security preferences changes, which can't be easily done. The PR with virtualbox is not yet merged #4010
> Java	8(default)
> 11
> 12
> 13	8(default)
> 11	Due to our software guidelines we left only LTS versions on the image. If you need to use other versions of Java, consider using [setup-java](https://github.com/actions/setup-java) and [Java tool installer](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/tool/java-tool-installer?view=azure-devops) tasks
> Python toolcache	2.7
> 3.5
> 3.6
> 3.7
> 3.8
> 3.9	3.7
> 3.8
> 3.9	EOL python versions were deprecated
> PyPy toolcache	2.7
> 3.6
> 3.7	2.7
> 3.7	Version 3.6 was deprecated as it won't receive any updates
> Go toolcache	1.13
> 1.14
> 1.15
> 1.16
> 1.17	1.15
> 1.16
> 1.17	EOL go versions were deprecated
> Xamarin.Mono	6.4 - 6.12	6.12	Old versions and versions incompatible with the pre-installed Xcodes were removed
> Xamarin.iOS	13.2 - 14.10	13.20 - 14.20	Old versions and versions incompatible with the pre-installed Xcodes were removed
> Xamarin.Mac	6.2 - 7.8	6.20 - 7.14	Old versions and versions incompatible with the pre-installed Xcodes were removed
> Xamarin.Android	10.0 - 11.2	11.0 - 11.3	Old versions and versions incompatible with the pre-installed Xcodes were removed
> Xcode	12.4 (default)
> 12.3
> 12.2
> 12.1.1
> 12.1
> 12.0.1
> 11.7
> 11.6
> 11.5
> 11.4.1
> 11.3.1
> 11.2.1
> 10.3	13.0 (beta)
> 12.5.1 (default)
> 12.5
> 12.4
> 11.7	Only OS-compatible versions left + the latest 11 version
> Android SDK build-tools and platforms	24 - 31	27 - 31	Android Platforms and build tools < 27.0 were removed from image. Consider installation in runtime using sdkmanager
> ### Virtual environments affected
> * [ ]  Ubuntu 16.04
> * [ ]  Ubuntu 18.04
> * [ ]  Ubuntu 20.04
> * [x]  macOS 10.15
> * [x]  macOS 11
> * [ ]  Windows Server 2016
> * [ ]  Windows Server 2019
> * [ ]  Windows Server 2022
> 
> ### Mitigation ways
> If you see any issues with your workflows during this transition period:
> 
> * File an issue in this repository
> * Switch back to macOS 10.15 by specifying the “macOS-10.15" label. We will continue to support macOS 10.15.

**Comment by 3033071101** [comment]
，

**Comment by ramondeklein** [comment]
Adding `<Target Name="_IsProjectRestoreSupported" />` broke the UWP build when running in AppCenter.

**Comment by anders9ustafsson** [comment]
@ramondeklein @MuddyChrisA 
> Adding `<Target Name="_IsProjectRestoreSupported" />` broke the UWP build when running in AppCenter.

I found a more sufficient workaround [here](https://github.com/jonathanpeppers/boots/issues/87#issuecomment-963947168). Instead of adding a dummy `<Target/>´, when building the iOS or Android apps, the UWP project(s) is removed from the solution in the post-clone build script.

**Comment by ramondeklein** [comment]
@anders9ustafsson Love the hacks that people make to workaround this issue. :joy: My hack was a bit different. I patch out the `<Target Name="_IsProjectRestoreSupported" />` using the `appcenter-post-clone.sh` script... Also works.

**Comment by miketimofeev** [comment]
Azure DevOps users have been fully migrated.
Migration for GitHub actions users will be finished in the next 5-10 days.

**Comment by JoeDiesel40** [comment]
🎊

**Comment by edgiardina** [comment]
Seeing an issue with our Azure Devops Build Pipeline. We have two pipelines, a CI pipeline and a release pipeline. The release pipeline signs the app for Store distribution, but otherwise is the same. the CI pipeline passes and the build pipeline fails. Pretty sure its related to the macOS 11 switch (both pipelines use macos-latest)

```MTOUCH : error MT2101: Can't resolve the reference 'System.String CoreFoundation.CFString::FromHandle(System.IntPtr)', referenced from the method 'System.String Bind_TOCropViewController.TOCropToolbar::get_CancelTextButtonTitle()' in 'Xamarin.iOS, Version=0.0.0.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065'.```

The builds on Friday ran, the same commit that built friday fails with the above message. TOCropViewController is pulled from a nuget package we include.

**Comment by filipworksdev** [comment]
Some of my repos have been updated but others still on 11. I guess is slowly being rolled out to different repos?

**Comment by miketimofeev** [comment]
@filipworksdev correct, we migrate gradually. Sorry for the inconvenience!

**Comment by miketimofeev** [comment]
The migration is completed — all the jobs on `macos-latest` now run on `macos-11`.

**Comment by filipworksdev** [comment]
My job doesn't run yet on macos-11 https://github.com/goblinengine/goblin/actions/runs/1730824706

**Comment by miketimofeev** [comment]
@filipworksdev the build took place 6 days ago, we finished the migration yesterday

**Comment by filipworksdev** [comment]
@iMonZ @miketimofeev  Guys you were right. Everything is done. The build was old. I did a fresh build and is all been ported. Is all good . Thank you everyone! Now I can finally use C++17 for iOS 👍
