### ISSUE TITLE
Update podman to 3.3.1

### ISSUE THREAD

**Issue by tetchel** [actions/virtual-environments#4063]
### Tool name

podman

### Tool license

Apache

### Add or update?

- [ ] Add
- [X] Update

### Desired version

3.3.1 https://github.com/containers/podman/releases/tag/v3.3.1

### Brief description of tool

Please update podman to v3.3.1 to resolve a bug in v3.2.3 which causes backwards-compatibility issues for users pulling images from Docker image storage.

https://github.com/containers/podman/issues/10998
https://github.com/redhat-actions/push-to-registry/issues/42

### Virtual environments affected

- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [X] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [ ] Windows Server 2022

**Comment by Darleev** [comment]
Hello @tetchel,
Currently, we install podman according to the podman documentation for Ubuntu, however the latest available version in the repository is 3.2.3, it seems there is some discrepancy between GitHub podman versioning and Ubuntu's repository.
We will investigate the issue.

**Comment by al-cheb** [comment]
@lsm5, Hey, Lokesh
We use `download.opensuse.org/` [current version in the repo is 3.2.3] repo to install `podman buildah skopeo`  in the [container.sh](https://github.com/actions/virtual-environments/blob/main/images/linux/scripts/installers/containers.sh) script as the recommendation from `https://podman.io/getting-started/installation` help.  As a packer maintainer could you update package version to 3.3.1 and help us and your college @tetchel to fix the issue?

```
Package: podman
Maintainer: Lokesh Mandvekar <lsm5@fedoraproject.org>
```

`Buildah, Podman and Skopeo ONLY from EITHER the Kubic repo OR the official Ubuntu repos. Mixing and matching may lead to unpredictable situations including installation conflicts.`

**Comment by lsm5** [comment]
@al-cheb I'll update the kubic package. Btw, any chance you could switch to Ubuntu 21.04? That would have podman and buildah in the default repos itself.

**Comment by lsm5** [comment]
> @al-cheb I'll update the kubic package. Btw, any chance you could switch to Ubuntu 21.04? That would have podman and buildah in the default repos itself.

err, never mind, I do recall sometime back you mentioned you'd only switch from one LTS to another.

**Comment by lsm5** [comment]
Just sent podman v3.3.1 update to Kubic, give it maybe an hour to complete. https://build.opensuse.org/package/show/devel:kubic:libcontainers:stable/podman . Let me know if any other packages need changes.

**Comment by al-cheb** [comment]
@lsm5, Many thanks for the help. I will generate a test image build and let you know.

**Comment by al-cheb** [comment]
@tetchel , We are planning to start a new image rollout next week.
```
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: update podman
        run: |
          source /etc/os-release
          REPO_URL="https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable"
          sudo sh -c "echo 'deb ${REPO_URL}/x${NAME}_${VERSION_ID}/ /' > /etc/apt/sources.list.d/devel:kubic:libcontainers:stable.list"
          wget -qnv https://download.opensuse.org/repositories/devel:kubic:libcontainers:stable/x${NAME}_${VERSION_ID}/Release.key -O Release.key
          sudo apt-key add Release.key
          sudo apt-get update -qq
          sudo apt-get -qq -y install podman buildah skopeo
      - run: podman -v
```

![image](https://user-images.githubusercontent.com/47745270/133386216-d7a9827a-cd9f-41b5-8497-feac82571238.png)

**Comment by al-cheb** [comment]
The Ubuntu Server 20.04 with podman 3.3.1  have been deployed.
