### ISSUE TITLE
Microsoft Build of OpenJDK

### ISSUE THREAD

**Issue by bowlerma** [actions/virtual-environments#4064]
### Tool name

Microsoft Build of OpenJDK

### Tool license

GPLv2+CE

### Add or update?

- [X] Add
- [ ] Update

### Desired version

LTS

### Brief description of tool

Is there any intention to replace the Adopt OpenJDK on the Microsoft hosted agents with the Microsoft build of OpenJDK?

### URL for tool's homepage

https://docs.microsoft.com/en-gb/java/openjdk/

### Virtual environments affected

- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [X] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [X] Windows Server 2019
- [X] Windows Server 2022

**Comment by miketimofeev** [comment]
Hi @bowlerma!
No, we don't have such intentions. We're currently replacing adopt with Eclipse Timurin as adopt openjdk is being deprecated — https://github.com/actions/virtual-environments/issues/3859
If you need Microsoft openjdk please consider opening an issue to add Microsoft jdk support in https://github.com/actions/setup-java
I'm going to close the issue, please feel free to contact us if you have any questions or objections.
Thank you!
