### ISSUE TITLE
Add SBT to MacOS runners

### ISSUE THREAD

**Issue by bfdes** [actions/virtual-environments#4065]
### Tool name

SBT

### Tool license

Apache License 2.0 

### Add or update?

- [X] Add
- [ ] Update

### Desired version

Latest

### Brief description of tool

I came here from https://github.com/actions/setup-java/issues/50.

SBT is the most common build tool for Scala projects. 

I notice that it is available on Windows and Ubuntu runners, but not MacOS: 
- https://github.com/bfdes/Collections/commit/ce4041cad958f56bb7c0ce207a8e26e9900892e4, which runs`sbt test` on all platforms, [fails on MacOS](https://github.com/bfdes/Collections/runs/3578981546) because "sbt cannot be found"
- https://github.com/bfdes/Collections/commit/a0bd54fca63a7a115625bc73481645511953414f only runs `sbt test` on Windows and Linux. It passes.

### URL for tool's homepage

https://www.scala-sbt.org/

### Provide a basic test case to validate the tool's functionality.

```bash
`sbt --help`
```

### Virtual environments affected

- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [X] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Can this tool be installed during the build?

```bash
SBT can be installed using Homebrew, which is already available:

`brew install sbt`
```

### Tool installation time in runtime

~4 seconds

### Are you willing to submit a PR?

Yes

**Comment by Darleev** [comment]
Hello @bfdes,
We will consider adding sbt tool to the macOS runners.

**Comment by MaksimZhukov** [comment]
All the images with SBT have been deployed.
