### ISSUE TITLE
Update YQ

### ISSUE THREAD

**Issue by wzshiming** [actions/virtual-environments#4069]
### Tool name

yq

### Tool license

Apache-2.0 License

### Add or update?

- [ ] Add
- [X] Update

### Desired version

latest

### Brief description of tool

About Command-line YAML, XML, TOML processor - jq wrapper for YAML/XML/TOML documents

https://github.com/mikefarah/yq (Currently default, experience `jq` incompatibility)
https://github.com/kislyuk/yq (`jq` wrapper)

I think whether it is possible to provide a `yq` that is consistent with the experience of `jq`

### URL for tool's homepage

https://github.com/kislyuk/yq

### Virtual environments affected

- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Are you willing to submit a PR?

YES

**Comment by Yann-J** [comment]
Hmm, I didn't realize there were 2 tools with the same name, thanks for spotting that...

My 2 cts would be that consistency with `jq` isn't really a huge benefit IMHO. And judging from the github repos and docs, the original `yq` (https://github.com/mikefarah/yq) seems more popular (more stars, forks, has a popular Github action, a popular docker image with 6M pulls), better maintained, and from what I can see, seems more capable (the other one isn't native YAML but works by first converting documents to JSON and piping to `jq`, which will inevitably lose YAML-specific features like comments and references).

If `jq` syntax is desired, piping `yq --output-format=json` to `jq`, and then back to `yq --prettyPrint` seems like it should work.

I'd personally vote to stick to https://github.com/mikefarah/yq

**Comment by Darleev** [comment]
Hello @wzshiming,
@Yann-J answer looks pretty convincing, I think it does not make sense to change anything in the existing yq tool installation. Anyway, if you have any others questions or concerns, feel free to contact us here.
I'm going to close the issue.
