### ISSUE TITLE
Add Xcode 13 RC (13A233)

### ISSUE THREAD

**Issue by owjsub** [actions/virtual-environments#4084]
### Tool name

Xcode 13 in macOS 11 Virtual Environment

### Tool license

macOS 11

### Add or update?

- [X] Add
- [ ] Update

### Desired version

Xcode 13 RC (13A233)

### Brief description of tool

Xcode 13 RC released Sep 14, 2021

### URL for tool's homepage

https://developer.apple.com/news/releases/?id=09142021e

### Virtual environments affected

- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [X] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [ ] Windows Server 2022

**Comment by miketimofeev** [comment]
Hi @owjsub!
We are going to start the new image rollout with Xcode 13 RC on board tomorrow.

**Comment by Brett-Best** [comment]
Can we keep the current Xcode beta version too as the RC doesn’t include the macOS 12 SDK?

**Comment by miketimofeev** [comment]
@Brett-Best looks like it makes sense, we did the same for Xcode 12 beta back in the days https://github.com/actions/virtual-environments/issues/1599#issuecomment-692990109

**Comment by owjsub** [comment]
@miketimofeev Looks great! I was able to submit an app for review using the new image! Thank you!

**Comment by erikng** [comment]
What is the Xcode 13 path for non-RC? I looked at the merge commit and only the read me is updated. My current GitHub actions are broken as I'm trying to build macOS releases.

**Comment by erikng** [comment]
It appears the beta version did not make it onto the new build :/

I ran `ls -la /Applications` on a job just now and only the RC path is available for use.

**Comment by Brett-Best** [comment]
@erikng it will be part of this deployment https://github.com/actions/virtual-environments/pull/4109/, unfortunate that it was removed even though I mentioned the issue with plenty of time

**Comment by miketimofeev** [comment]
@erikng as @Brett-Best mentioned the image is not yet fully deployed. We are going to finish the deployment tomorrow. Sorry for the inconvenience.

**Comment by erikng** [comment]
Is there any chance to start the deployment early?

For context, this tool is used on hundreds of thousands of macOS devices at companies like Uber, Facebook, Pinterest, etc. 

I have a bug fix that I need to get out, but I'm hard blocked due to this.

**Comment by miketimofeev** [comment]
@erikng got it, the deployment was already started a few hours ago, but we will try to speed it up a bit.

**Comment by miketimofeev** [comment]
@erikng @Brett-Best @owjsub the image should be deployed now. Could you check that both xcode versions are now available? 
Xcode 13 located on path: /Applications/Xcode_13.0.app
Xcode 13 beta located on path: /Applications/Xcode_13.0_beta.app

**Comment by erikng** [comment]
Thanks so much for this! I've confirmed the beta application is on the image. I was able to create a new release.

**Comment by owjsub** [comment]
Thanks @miketimofeev! I confirmed that Xcode 13 located on path: /Applications/Xcode_13.0.app continues to work as expected. I was able to create a new release with it.
