### ISSUE TITLE
Add JDK 17

### ISSUE THREAD

**Issue by mikeharder** [actions/virtual-environments#4085]
### Tool name

openjdk version "17"

### Tool license

GPLv2+CE

### Add or update?

- [X] Add
- [ ] Update

### Desired version

latest

### Virtual environments affected

- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [ ] Windows Server 2022

**Comment by miketimofeev** [comment]
Hi @mikeharder!
We are currently switching our pre-installed Java to adoptium openjdk — https://github.com/actions/virtual-environments/issues/3859
We will add Java 17 LTS once installers are available for adoptium https://github.com/adoptium/adoptium/issues/74

**Comment by mikhailkoliada** [comment]
Windows and MacOS are done, jdk 17 should be available there as soon as new images are deployed next week

**Comment by wimdeblauwe** [comment]
What about Linux ?

**Comment by mvysny** [comment]
@wimdeblauwe for me it works well with ubuntu-latest and jdk17, please see an example here: https://github.com/mvysny/karibu-tools/blob/main/.github/workflows/gradle.yml

**Comment by miketimofeev** [comment]
@wimdeblauwe we are waiting for adoptium linux installers https://github.com/adoptium/installer/issues/330

**Comment by mikhailkoliada** [comment]
> Windows and MacOS are done, jdk 17 should be available there as soon as new images are deployed next week

Both are in place by now.

**Comment by tinolazreg** [comment]
Any status updates on Linux?

**Comment by miketimofeev** [comment]
@tinolazreg still waiting for adoptium binaries https://github.com/adoptium/installer/issues/330

**Comment by Davio** [comment]
> @tinolazreg still waiting for adoptium binaries [adoptium/installer#330](https://github.com/adoptium/installer/issues/330)

This issue seems close to completion, I wonder when this will be complete.

**Comment by miketimofeev** [comment]
@Davio thanks for the update! We will get back to this soon

**Comment by miketimofeev** [comment]
@Davio we will postpone this as it is said  
> the installers are not stable and the hostname will change from adoptium.jfrog.io to packages.adoptium.net. 

https://github.com/adoptium/installer/issues/346#issuecomment-995636161

**Comment by m0dul3** [comment]
accept

**Comment by mikhailkoliada** [comment]
The Linux installer (the last one) has been merged, the images with the Eclipse Temurin 17 jdk will be deployed next week.

**Comment by martoncsukas** [comment]
Hi @mikhailkoliada , any ETA on when Java 17b be available in `ubuntu-latest` image for Azure DevOps? Thanks in advance.

**Comment by miketimofeev** [comment]
@martoncsukas the new image is currently being deployed. Some environments already have JDK17 the rest will have it tomorrow.

**Comment by Davio** [comment]
It seems like most of the code is in place, but the README(s), such as https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-Readme.md still need to be amended.

**Comment by miketimofeev** [comment]
@Davio Ubuntu20.04 is not yet updated. Will be finished next week

**Comment by Davio** [comment]
It seems like the scripts were already fixed though, is it just a matter of deployment now?

**Comment by miketimofeev** [comment]
@Davio correct

**Comment by Davio** [comment]
It seems like the Ubuntu agents have been updated, thanks for all the hard work everyone. :)

**Comment by mikhailkoliada** [comment]
Yes, everything has been deployed, closing now.
