### ISSUE TITLE
"/usr/bin/ghc" broken?

### ISSUE THREAD

**Issue by hasufell** [actions/virtual-environments#4094]
### Description

After this patch https://github.com/actions/virtual-environments/commit/ee69b89103cee75483f6ed348e1c307129a20c8c#diff-be47a081552c94d85c52955897f314f7f38270b6444a776f793397e440fa0c85R47 I believe we forgot to adjust the following line:

https://github.com/actions/virtual-environments/blob/65da2f8781b5cae348a655f61365191c1b679ec1/images/linux/scripts/installers/haskell.sh#L47

I'm not sure if that has any effect on the images?

### Virtual environments affected

- [X] Ubuntu 16.04
- [X] Ubuntu 18.04
- [X] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Not sure

### Repro steps

None

**Comment by al-cheb** [comment]
Hey,  @hasufell 
We should remove this line from the script: 
`lrwxrwxrwx 1 root root 17 Sep 13 03:41 /usr/bin/ghc -> /opt/ghc//bin/ghc`

We are not affected, because `/usr/local/.ghcup/bin` before `/usr/bin/ghc`.
```
/home/linuxbrew/.linuxbrew/bin
/home/linuxbrew/.linuxbrew/sbin
/home/runner/.local/bin
/opt/pipx_bin
/usr/share/rust/.cargo/bin
/home/runner/.config/composer/vendor/bin
/usr/local/.ghcup/bin
/home/runner/.dotnet/tools
/snap/bin
/usr/local/sbin
/usr/local/bin
/usr/sbin
/usr/bin
/sbin
/bin
/usr/games
/usr/local/games
/snap/bin
```

Do you want to create a PR?

**Comment by miketimofeev** [comment]
@hasufell the PR is merged, thanks for the quick fix!
I will close the issue once we deploy the new image without the link.

**Comment by quark17** [comment]
I think the original commit also forgot to add this:
```
echo 'export PATH="$PATH:$HOME/.ghcup/bin"' >> "$HOME/.bashrc"
```
That line appears in the macOS script (`images/macos/provision/core/haskell.sh`), which had already been using ghcup to install.  I am finding that the Ubuntu VMs (as deployed) don't have `ghc`, `ghc-pkg`, or `cabal` in the default search path.  I have to explicitly add `$HOME/.ghcup/bin` and then my Ubuntu CI jobs start working.  But this is not needed for macOS VMs.

**Comment by al-cheb** [comment]
> I think the original commit also forgot to add this:
> 
> ```
> echo 'export PATH="$PATH:$HOME/.ghcup/bin"' >> "$HOME/.bashrc"
> ```
> 
> That line appears in the macOS script (`images/macos/provision/core/haskell.sh`), which had already been using ghcup to install. I am finding that the Ubuntu VMs (as deployed) don't have `ghc`, `ghc-pkg`, or `cabal` in the default search path. I have to explicitly add `$HOME/.ghcup/bin` and then my Ubuntu CI jobs start working. But this is not needed for macOS VMs.

The main difference between macOS and Ubuntu is that for macOS we don't delete a user profile after image generation that's why we can't use the user profile for Ubuntu images and should put ghc at the global path.

**Comment by hasufell** [comment]
you can install into `/usr` now with ghcup, e.g.

```sh
ghcup install ghc --isolate /usr --force 8.10.7
```

Should we maybe do that?

**Comment by al-cheb** [comment]
The `/usr/bin/ghc` path has been removed.
