### ISSUE TITLE
VM build failing with packer for Windows 2019/Linux

### ISSUE THREAD

**Issue by vamshisiram** [actions/virtual-environments#4096]
### Description

I am following the steps from this article https://github.com/actions/virtual-environments/blob/main/docs/create-image-and-azure-resources.md to create a windows 2019 image and ubuntu2004 from which i can create a VM to use as a self hosted agent for Azure DevOps.

The Linux image process worked fine, but the windows one is failing with different error each time. retried 3 times so far and still failing.

![image](https://user-images.githubusercontent.com/90816346/133547088-8ad71b88-c61f-4c60-a645-10763ce26ca3.png)

![image](https://user-images.githubusercontent.com/90816346/133547113-dcfb058b-87a3-4822-a57b-c659c611ecd8.png)

![image](https://user-images.githubusercontent.com/90816346/133547142-521363a9-fad0-4690-92e3-29ec61fa3175.png)

Any suggestions on fixing this issue?

### Virtual environments affected

- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [X] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

i am not using devops or github, i am manually running the PS Scripts to build the image.

### Expected behavior

i expected to get the VHD and JSON file to be generated.

### Actual behavior

 the windows one is failing with different error each time. retried 3 times so far and still failing.

![image](https://user-images.githubusercontent.com/90816346/133547088-8ad71b88-c61f-4c60-a645-10763ce26ca3.png)

![image](https://user-images.githubusercontent.com/90816346/133547113-dcfb058b-87a3-4822-a57b-c659c611ecd8.png)

![image](https://user-images.githubusercontent.com/90816346/133547142-521363a9-fad0-4690-92e3-29ec61fa3175.png)

### Repro steps

Follow the steps from the article in description and then choose windows 2019, it should fail as shown in my attachments.

**Comment by Darleev** [comment]
Hello @vamshisiram,
Could you please provide a packer version and make sure that you use the latest main templates from the virtual environments repository?
We're looking forward to your reply.

**Comment by vamshisiram** [comment]
@Darleev thanks for the response.

I am using packer version 1.7.4 for windows 64 bit. And i downloaded (aka cloned) the git repo just few hours ago, so it should be latest repo.

**Comment by Darleev** [comment]
@vamshisiram Which region do you use for image build? Could you please try to build the image using Central US?

**Comment by vamshisiram** [comment]
@Darleev I was using North central US.

Sure, i will try using Central US shortly and let you know.

**Comment by vamshisiram** [comment]
@Darleev  i tried it again with central US as the region. and it failed again, similar error as last time. :-(

SO, i created a new Resource Group, Storage account and specified the SA name in the generate script, then followed the steps from the git article.

here is the error:

![image](https://user-images.githubusercontent.com/90816346/133640830-b1e1adb8-fa58-4468-b3be-a71180f3fd66.png)

**Comment by miketimofeev** [comment]
@vamshisiram what VM size do you use?

**Comment by vamshisiram** [comment]
@miketimofeev I am still in the process of image generation. I am not specifying any VM size variable in the generate command. 

I would love to specify a VM Size. Can you tell me how to that, pls @miketimofeev .

Also @Darleev i kicked off an image generation about 3.5 hrs ago and it is still going on. I made a change to the install-choco.ps1 script in your repo locally (commented out the remove item line). I am hoping this finishes this time.

**Comment by mortenlerudjordet** [comment]
VM size is hardcoded in: https://github.com/actions/virtual-environments/blob/main/images/win/windows2019.json
Should probably make it an input parameter and set a default value outside the json?

**Comment by vamshisiram** [comment]
@Darleev  @miketimofeev  @mortenlerudjordet the vm creation is failing. it is failing indicating that the NIC cannot be found and when i look into the operation details, i am seeing a 404 error code.

![image](https://user-images.githubusercontent.com/90816346/134437214-90d28d3d-32c9-400b-b756-e643209c0282.png)

but when i go to the Resource Group, the script is actually creating the NIC, PIp etc. during the VM creation step it is just failing that the resource NIC is not found.

Any thoughts on resolving this, pls?

**Comment by vamshisiram** [comment]
@Darleev @miketimofeev i found that it works only if the resource group/storage account/vm all are in central us. I was using north central earlier.

Even with central us, it was failing at some parts indicating the replication failure for vm creation, but when I retried it was fine.

Wanted to let you know that this can now be closed.

**Comment by Darleev** [comment]
@vamshisiram thank you for your effort and the information provided.
I'm going to close the issue.
Feel free to contact us at any time
