### ISSUE TITLE
Support for ChromeDriver

### ISSUE THREAD

**Issue by nathany** [actions/virtual-environments#41]
Is there an equivalent to `circleci/node:jessie-browsers` for GitHub Actions?

I'm trying to test an Electron app but Chrome isn't available. 

```
unknown error: Chrome failed to start: exited abnormally
      (unknown error: DevToolsActivePort file doesn't exist)
      (The process started from chrome location /home/runner/work/.../node_modules/spectron/lib/launcher.js is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
```

I imagine there are other use case too for integration tests on any front-end app.

**Comment by bryanmacfarlane** [comment]
moving to the virtual-environment repo since this appears to be an issue with the chrome driver on the image.

**Comment by kaylangan** [comment]
Related to #9

@nathany which OS/virtual environment are you using? Are you seeing failures on all of them?

**Comment by nathany** [comment]
@kaylangan Sorry for the delay. If I recall, the failures were on Linux. Though I was hoping to be able to run the tests on all 3 environments. 

TBH, I was pulled off that project, so this may not be a high priority for me.

**Comment by mhanberg** [comment]
@nathany Possible clarification. The Ubuntu environments have Chrome installed on them, but not ChromeDriver, which is a separate utility.

It would be nice if ChromeDriver, GeckoDriver, etc were included in these images, but for I have found success using this action to install ChromeDriver, https://github.com/nanasess/setup-chromedriver

**Comment by kaylangan** [comment]
> The Ubuntu environments have Chrome installed on them, but not ChromeDriver, which is a separate utility.

Yup, closing this in favor of #9 (for Ubuntu).

We also have #7 (for macOS).
