### ISSUE TITLE
Update Cocoapods on Mac images

### ISSUE THREAD

**Issue by pyanierothef** [actions/virtual-environments#4103]
### Tool name

Cocoapods

### Tool license

MIT

### Add or update?

- [ ] Add
- [X] Update

### Desired version

latest (1.11.2)

### Brief description of tool

macOS 10.15 has CocoaPods version 1.11.0 installed. 
They introduced a bug on that version that makes the tool fail when trying to clone azure repos with ssh. 

The bug was fixed in 1.11.1

### Virtual environments affected

- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [X] macOS 10.15
- [X] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [ ] Windows Server 2022

**Comment by typeoneerror** [comment]
Current version is 1.11.2 as of my latest action run.

**Comment by Darleev** [comment]
Hello @pyanierothef,
We've just updated macOS images, and they contain required version of Cocoapods.
If you have any questions, feel free to contact us.
I'm going to close the issue.

**Comment by typeoneerror** [comment]
>  We've just updated macOS images, and they contain required version of Cocoapods.

Hey, @Darleev, might you have an idea of how we could pick a specific version of Cocoapods on the macOS VM? Similar to how actions/ruby or actions/node allow us?

**Comment by Darleev** [comment]
@typeoneerror we install only the latest cocoapods version on the macOS images. Currently, version 1.11.2 is installed. However, you can use the following action to install required version in runtime: https://github.com/marketplace/actions/setup-cocoapods
