### ISSUE TITLE
Maven build fail due to an API incompatibility while executing net.alchim31.maven:scala-maven-plugin:4.2.0:compile

### ISSUE THREAD

**Issue by maminetahiri** [actions/virtual-environments#4105]
### Description

Maven Build task fail due to an API incompatibility while executing net.alchim31.maven:scala-maven-plugin:4.2.0:compile:

The message error: [ERROR] Failed to execute goal net.alchim31.maven:scala-maven-plugin:4.2.0:compile (scala-compile-first) on project spark-raw-prepared: Execution scala-compile-first of goal net.alchim31.maven:scala-maven-plugin:4.2.0:compile failed: An API incompatibility was encountered while executing net.alchim31.maven:scala-maven-plugin:4.2.0:compile: java.lang.NoSuchMethodError: org.fusesource.jansi.AnsiConsole.wrapOutputStream(Ljava/io/OutputStream;)Ljava/io/OutputStream;

When i try to build my artifact locally it works but using azure devops fail.
The Maven build worked well in the past and even if there is no change in the task (maven build) the build fail.
 There is some update in the hosted image ? 

### Virtual environments affected

- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

OS name: "windows server 2019", version: "10.0", arch: "amd64", family: "windows"

### Repro steps

run the maven build task:

  - task: Maven@3
    inputs:
      mavenPomFile: 'path/to/pomfile.xml'
      # skip test is mandatory because they will fail during package deployment
      goals: '-DskipTests=true package'
      publishJUnitResults: false 
      javaHomeOption: 'JDKVersion' # Options: jDKVersion, path
      jdkVersionOption: '1.8' # Options: default, 1.11, 1.10, 1.9, 1.8, 1.7, 1.6
      jdkArchitectureOption: 'x64' # Optional. Options: x86, x64
      mavenVersionOption: 'Default' # Options: default, path
      mavenOptions: '-Xmx1024m' # Optional
      mavenAuthenticateFeed: false 
      effectivePomSkip: false 
      sonarQubeRunAnalysis: false 
      checkStyleRunAnalysis: false # Optional

**Comment by Darleev** [comment]
Hello @maminetahiri,
We will investigate the issue.

**Comment by Darleev** [comment]
@maminetahiri In order to speed up the investigation: Could you please provide us sample repository or steps to reproduce the issue?

**Comment by maminetahiri** [comment]
Hello @Darleev, thanks for response.

Sorry, i don't have a sample repository but in my description i put it the maven build task.

I can also send you the dependencies with version that i use for the build let me know if you it will helpfull to have this dependencies.

**Comment by dibir-magomedsaygitov** [comment]
Hello @maminetahiri. Could you please add one step before the maven task and execute this command:
`mvn clean scala:compile compile package`
And, also, could you please share the content of your POM file?

**Comment by dibir-magomedsaygitov** [comment]
Hello @maminetahiri. Any updates on the issue?

**Comment by dibir-magomedsaygitov** [comment]
Hello @maminetahiri. I'm going to close this issue for now. Feel free to reopen it if you have any concerns or questions.
