### ISSUE TITLE
Update/Add Node v13.x

### ISSUE THREAD

**Issue by nathanblair** [actions/virtual-environments#412]
**Tool information**
- Tool name: Node v13 (Current Release Cycle)
- Add or update? Update
- Desired version: v13 (Current on Release blog)
- Approximate size:

**Area for Triage**:
JavaScript and Node.js

**Question, Bug, or Feature?**:
Feature

**Virtual environments affected**
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [x] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Can this tool be installed during the build?**
Yes, using setup-node action and with `input`. Which I'm doing currently and would be happy to continue doing so, especially given Node v13's relatively short `Current` lifespan. The only reason I'm suggesting adding it explicitly is that starting with Node v13, the `--experimental-modules` flag is enabled by default. This means one less flag that has to be maintained between Node release versions including and following 13.

**Are you willing to submit a PR?**
Definite maybe. Haven't looked at the Contributing guidelines yet.

**Comment by maxim-lobanov** [comment]
@alepauly , I think we should keep LTS version Node.JS as default one on the image. Currently, it is 12.x.
13.x can be easily installed during the build using `setup-node` task.

**Comment by alepauly** [comment]
I agree @maxim-lobanov, thanks. @nathanblair - we can't move to Node 13.x right now out of the box but we are working on some overall improvements so that we can cache more version of Node and download on demand via `setup` Actions when necessary. Apologies for the delay looking at this.
