### ISSUE TITLE
Build fails with "poetry: command not found" message on macOS 10.15 environment.

### ISSUE THREAD

**Issue by zoj613** [actions/virtual-environments#4120]
### Description

When trying to run the automated release github action that is supposed to build and publish wheels to pypi, I get an error message that shows the build failed on macos 10.15. This error did not occur on merge of the latest PR or when running the "build-and-test" CI action. I get the message: `/Users/runner/work/_temp/57cdff42-7f35-44cb-bd4a-06bc8f0f526b.sh: line 3: poetry: command not found` even though the script shows that the `poetry` package is installed. The last time I released a package (which was around a month or two ago) this issue did not exist.

### Virtual environments affected

- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [X] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

```
   Version: 20210914.1
  Included Software: actions/virtual-environments@macOS-10.15/20210914.1/images/macos/macos-10.15-Readme.md
  Image Release: actions/virtual-environments@macOS-10.15%2F20210914.1 (release)
```

Link to build: https://github.com/zoj613/polyagamma/runs/3657447479?check_suite_focus=true

### Is it regression?

https://github.com/zoj613/polyagamma/runs/3331014953?check_suite_focus=true

### Expected behavior

Successful build and release of package.

### Actual behavior

Build failure on macOS, possibly other OS too but the build stopped before I could find out.

### Repro steps

running this workflow would reproduce this issue: https://github.com/zoj613/polyagamma/actions/runs/1255513615

**Comment by dibir-magomedsaygitov** [comment]
Hello @zoj613. Thank you for your report. We will take a look.

**Comment by zoj613** [comment]
@dibir-magomedsaygitov Strangey enough, this commit: https://github.com/zoj613/polyagamma/commit/9f0ecd53dc96791b36f75d6d831a5e892a76c200 seems to have resolved the issue. Maybe the environment needs an alias for pip that points to pip3? This wasn't an issue the last time I ran the workflow and I still use just `pip` on other workflows that install poetry on macos 10.15 with no issue. not sure if I should close this or not.

**Comment by vsafonkin** [comment]
Hi @zoj613, looks like `python-version` is missed in matrix of your release workflow: 
https://github.com/zoj613/polyagamma/blob/main/.github/workflows/release.yml#L25

As i see it uses pip from python 2.7 in the failed release:
```
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained.
```
and also:
```
WARNING: The script poetry is installed in '/Library/Frameworks/Python.framework/Versions/2.7/bin' which is not on PATH.
```


I can't understand how it worked before, because `pip` is alias for pip from python 2.7 all this time. I recommend that you use `setup-python` task with specified version. In this case `pip` is equal `pip3`:
![Screenshot 2021-09-21 at 5 59 20 PM](https://user-images.githubusercontent.com/7628945/134195546-e5334e2b-4963-45c7-b913-d321ba55d8dd.png)

**Comment by zoj613** [comment]
> Hi @zoj613, looks like `python-version` is missed in matrix of your release workflow:
> [https://github.com/zoj613/polyagamma/blob/main/.github/workflows/release.yml#L25](https://github.com/zoj613/polyagamma/blob/main/.github/workflows/release.yml?rgh-link-date=2021-09-21T15%3A00%3A55Z#L25)
> 
> As i see it uses pip from python 2.7 in the failed release:
> 
> ```
> DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained.
> ```
> 
> and also:
> 
> ```
> WARNING: The script poetry is installed in '/Library/Frameworks/Python.framework/Versions/2.7/bin' which is not on PATH.
> ```
> 
> I can't understand how it worked before, because `pip` is alias for pip from python 2.7 all this time. I recommend that you use `setup-python` task with specified version. In this case `pip` is equal `pip3`:
> ![Screenshot 2021-09-21 at 5 59 20 PM](https://user-images.githubusercontent.com/7628945/134195546-e5334e2b-4963-45c7-b913-d321ba55d8dd.png)

Thanks for the detailed reply. I will make sure to specify the python version. Just to be sure, setting it to a particular version wont conflict with the `pypa/cibuildwheel` action,right?

**Comment by vsafonkin** [comment]
> Just to be sure, setting it to a particular version wont conflict with the `pypa/cibuildwheel` action,right?

I guess it won't.
