### ISSUE TITLE
SBT fails to run tests due to memory issue

### ISSUE THREAD

**Issue by PenghaiZhang** [actions/virtual-environments#4134]
### Description

My project uses SBT to run around 620 tests with TestNG, and it was all good until the`Version: 20210913.1`.  The build logs show `OutOfMemoryError` and I have updated  `jvmopts` and `sbtopts` to have more memory but still failed.

### Virtual environments affected

- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [X] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

20210913.1

[Failed build](https://github.com/openequella/openEQUELLA/runs/3681684382#step:13:3004) 

### Is it regression?

Yes,  `20210906.1` was fine.

### Expected behavior

Tests can run without memory issue.

### Actual behavior

After about half of the tests are executed, the step fails due to `OutOfMemoryError`. 

### Repro steps

Rerun the step

**Comment by dibir-magomedsaygitov** [comment]
Hello @PenghaiZhang. Thank you for your report. We will take a look.

**Comment by PenghaiZhang** [comment]
> Hello @PenghaiZhang. Thank you for your report. We will take a look.

Thank you!!!!!!!

**Comment by PenghaiZhang** [comment]
Hello @dibir-magomedsaygitov , just let you know that I have switched to Ubuntu18.04 and it works fine.

**Comment by PenghaiZhang** [comment]
Unfortunately this issue now happens on Ubuntu 18.04 as well...
It was all good until `Version: 20210929.1`...

**Comment by PenghaiZhang** [comment]
[A failed build](https://github.com/openequella/openEQUELLA/pull/3429/checks?check_run_id=3762348101#step:13:3015)

**Comment by PenghaiZhang** [comment]
May I ask if it is possible to specify the VM version in the yaml file ?

**Comment by vsafonkin** [comment]
Hi @PenghaiZhang, sorry for the delay, we're investigating it.



> May I ask if it is possible to specify the VM version in the yaml file ?

Unfortunately, it's impossible.

**Comment by PenghaiZhang** [comment]
> Actually, I could not find out the reason of memory error, probably it can be some external tools (maybe chromedriver).

Thanks for your investigation @vsafonkin !! Yeah we have successful builds today and I noticed that the VM version now is `20211004.1`.

**Comment by PenghaiZhang** [comment]
Hi @vsafonkin , could you please reopen this issue ? We have had this issue again since 27th Jan 2022.

We run our Selenium tests on Ubuntu-18.04 and the issue started happening after the VM version was updated to `20220123.1`.

Here is a failed [build](https://github.com/openequella/openEQUELLA/runs/4966729216?check_suite_focus=true#step:13:3120) .

Previously, you mentioned that the issue could be caused by `chromedriver`. I noticed that there is a Chrome update in `20220123.1`, but not `chromedriver`.

**Comment by vsafonkin** [comment]
Hi @PenghaiZhang, I can't reproduce this issue on Ubuntu-18.04 and Ubuntu-20.04 at this moment, could you please check your builds?

**Comment by PenghaiZhang** [comment]
> Hi @PenghaiZhang, I can't reproduce this issue on Ubuntu-18.04 and Ubuntu-20.04 at this moment, could you please check your builds?

Thanks for investigating! Yes since the version of `20220207.1` this issue has been fixed again. 

It has happened a few times, but each time after a newer version was released the issue just disappeared.

Maybe we can close this ticket again.
