### ISSUE TITLE
404  Not Found [IP: 40.81.13.82 80]

### ISSUE THREAD

**Issue by daniel-mohr** [actions/virtual-environments#4136]
### Description

I use [Ubuntu 18.04.5 LTS](https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu1804-README.md) in a github action. Now I realized that using `sudo apt install ...` results in:

```
...
E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/q/qtbase-opensource-src/libqt5core5a_5.9.5+dfsg-0ubuntu2.5_amd64.deb  404  Not Found [IP: 40.81.13.82 80]
E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/q/qtbase-opensource-src/libqt5dbus5_5.9.5+dfsg-0ubuntu2.5_amd64.deb  404  Not Found [IP: 40.81.13.82 80]
E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/q/qtbase-opensource-src/libqt5network5_5.9.5+dfsg-0ubuntu2.5_amd64.deb  404  Not Found [IP: 40.81.13.82 80]
E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/q/qtbase-opensource-src/libqt5gui5_5.9.5+dfsg-0ubuntu2.5_amd64.deb  404  Not Found [IP: 40.81.13.82 80]
E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/q/qtbase-opensource-src/libqt5widgets5_5.9.5+dfsg-0ubuntu2.5_amd64.deb  404  Not Found [IP: 40.81.13.82 80]
E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/q/qtbase-opensource-src/libqt5printsupport5_5.9.5+dfsg-0ubuntu2.5_amd64.deb  404  Not Found [IP: 40.81.13.82 80]
E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/q/qtbase-opensource-src/qt5-gtk-platformtheme_5.9.5+dfsg-0ubuntu2.5_amd64.deb  404  Not Found [IP: 40.81.13.82 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
Error: Process completed with exit code 100.
```

About 3 days ago it was still working.

### Virtual environments affected

- [ ] Ubuntu 16.04
- [X] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

  Environment: ubuntu-18.04
  Version: 20210913.1
  Included Software: https://github.com/actions/virtual-environments/blob/ubuntu18/20210913.1/images/linux/Ubuntu1804-README.md
  Image Release: https://github.com/actions/virtual-environments/releases/tag/ubuntu18%2F20210913.1

### Is it regression?

About 3 days ago it was still working with the same Version.

### Expected behavior

`apt install` can reach and update the repositories.

### Actual behavior

E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/q/qtbase-opensource-src/libqt5core5a_5.9.5+dfsg-0ubuntu2.5_amd64.deb  404  Not Found [IP: 40.81.13.82 80]

### Repro steps

use github action with:

```
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: install dependencies (ubuntu packages)
      run: sudo apt install python3-pytest
```

**Comment by dibir-magomedsaygitov** [comment]
Hello @daniel-mohr  please make sure that you have run `sudo apt-get update` before installation packages.

**Comment by daniel-mohr** [comment]
@dibir-magomedsaygitov Thank you for this hint.

It [was not necessary](https://github.com/dlr-pa/fuse_git_bare_fs/runs/3291136492) and [is still not necessary in all cases](https://github.com/daniel-mohr/i/actions/runs/1264927457).

But at least [for some packages it seems to be necessary now](https://github.com/daniel-mohr/i/actions/runs/1264957576).
