### ISSUE TITLE
Missing GNU Make in various readme.md

### ISSUE THREAD

**Issue by Mizux** [actions/virtual-environments#4140]
### Description

Following #4138 (but not only for ubuntu images) I would like to know which version of GNU Make is installed in each environments (`ubuntu-latest`, `windows-latest` and  `macos-latest`) when looking at their respective README.md

In google/or-tools we still have a Make based build so we need to know which version is installed by default on each of these github action runners...
I feel unproductive to push a dummy commit in order to reverse the runner environment to check which version of make is installed...

note: while on Ubuntu 20.04 `build-essential` package will pull make I feel sad to not have the version displayed in the readme.md like you did for bazel, cmake or gcc.

note2: make seems installed on macos and windows but again won't appear in the Readme.md...

### Virtual environments affected

- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [X] Ubuntu 20.04
- [X] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [X] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

https://github.com/Mizux/inspect-ci/actions/runs/1265694653

### Is it regression?

NO

### Expected behavior

Having this tools and its version documented (like other build systems)

### Actual behavior

Do not appear in the REAME.md as Included Software...

### Repro steps

simply add to any workflow:
```yml
    - name: Check Make
      run: make --version
```
Then you'll spot its presence...

**Comment by catthehacker** [comment]
Windows has `make.exe` from MinGW64
https://github.com/actions/virtual-environments/blob/b7f276c003aea42575b52247bdb2183e355fca2f/images/win/scripts/Installers/Install-Mingw64.ps1#L1-L13

**Comment by Mizux** [comment]
@catthehacker so will it be possible to update

Report to add it to the README.md aka
* https://github.com/actions/virtual-environments/blob/main/images/linux/scripts/tests/Tools.Tests.ps1
* https://github.com/actions/virtual-environments/blob/main/images/macos/software-report/SoftwareReport.Common.psm1
* https://github.com/actions/virtual-environments/blob/main/images/win/scripts/SoftwareReport/SoftwareReport.Tools.psm1

As well as having a test to check its presence e.g.
* https://github.com/actions/virtual-environments/blob/main/images/linux/scripts/tests/Tools.Tests.ps1

note: I may try to provide a PR for this but if maintainer are against these QoL changes I don't want to waste my time on it...

**Comment by catthehacker** [comment]
> so will it be possible to update the following files ?

most likely, someone from action should chime in here soon and clarify if they want to add this or not

PR content would be something like this:
```pwsh
function Get-MakeVersion {
    $version = make --version | Select-Object -First 1
    return "$version"
}
```
or
```pwsh
function Get-MakeVersion {
    $version = make --version | Select-Object -First 1 | Take-Part -Part 2
    return "GNU Make $version"
}
```

**Comment by mikhailkoliada** [comment]
Hello!

Unlike gcc, make releases happen hardly ever [1] and usually introduce very small amount of changes, which possibly makes 'make' not worth being shown in the README files.

[1] - http://ftp.gnu.org/gnu/make/

**Comment by mikhailkoliada** [comment]
I am going to close this now, feel free to reopen if you have any questions.

**Comment by Mizux** [comment]
Actually, for me, it matter since macos env use make 3.80 instead of 4.2.21 (IIRC) on `windows-latest` and `ubuntu-latest`

and make `$(foreach ...)` is not correctly evaluated... 
e.g. https://github.com/google/or-tools/blob/b37d9c786b69128f3505f15beca09e89bf078a89/cmake/Makefile#L146-L182

Also in the C++ realm, when using CMake (which is a build **generator**) this one default to make based build generator so knowing the make version do matter for C++ devs...

todo(me): try to create a minimal reproducible example
