### ISSUE TITLE
Gradle failing for NDK23

### ISSUE THREAD

**Issue by WPrins** [actions/virtual-environments#4144]
### Description

Android builds started failing today. The previous build was done on Monday 20 sept which still succeeded. I noticed that in the meantime the default NDK was updated to 23.
This is the error message:

* What went wrong:
Execution failed for task ':app:stripDevelopReleaseDebugSymbols'.
> 1 exception was raised by workers:
  org.gradle.process.internal.ExecException: A problem occurred starting process 'command '/Users/runner/Library/Android/sdk/ndk/23.0.7599858/toolchains/llvm/prebuilt/darwin-x86_64/bin/arm-linux-androideabi-strip''

### Virtual environments affected

- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [X] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Virtual Environment
Environment: macos-10.15
Version: 20210919.1
Included Software: https://github.com/actions/virtual-environments/blob/macOS-10.15/20210919.1/images/macos/macos-10.15-Readme.md

### Is it regression?

Yes, Version: 20210914.1

### Repro steps

Install Flutter
flutter build apk --target-platform=android-arm,android-arm64,android-x64 --build-number=2021092405 --flavor=develop --target=lib/main_dev.dart

or 

flutter build appbundle --build-number=2021092404 --flavor=prod --target=lib/main_prod.dart

both apk and appbundle builds fail

**Comment by dibir-magomedsaygitov** [comment]
Hello @WPrins. Thank you for your report. Could you please share content of `gradle-wrapper.properties` and `build.gradle` files?

**Comment by WPrins** [comment]
The gradle-wrapper.properties:

```
distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
distributionUrl=https\://services.gradle.org/distributions/gradle-6.7.1-bin.zip
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
```

and build.gradle

```
`buildscript {
    ext.kotlin_version = '1.3.72'
    repositories {
        google()
        maven { url 'https://repo1.maven.org/maven2' }
        maven { url 'https://maven.fabric.io/public' }
        jcenter()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:3.6.4'
        classpath 'com.google.firebase:firebase-crashlytics-gradle:2.4.1'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath 'com.google.gms:google-services:4.3.4'
    }
}

allprojects {
    repositories {
        google()
        maven { url 'https://repo1.maven.org/maven2' }
        maven { url 'https://maven.fabric.io/public' }
        jcenter()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
```

**Comment by dibir-magomedsaygitov** [comment]
Could you please try to change:
`classpath 'com.android.tools.build:gradle:3.6.4'` -> `classpath 'com.android.tools.build:gradle:4.1.0'`
`distributionUrl=https\://services.gradle.org/distributions/gradle-6.7.1-bin.zip` -> `distributionUrl=https\://services.gradle.org/distributions/gradle-6.5-bin.zip`
and check if it helps to resolve the issue?

**Comment by anjebarnard-deloitte** [comment]
We also saw a similar error in our build (on the macOS 10.15 environment):

* What went wrong:
Execution failed for task ':app:stripReleaseDebugSymbols'.
> No toolchains found in the NDK toolchains folder for ABI with prefix: arm-linux-androideabi

Updating the gradle tools version to 4.1.0 and the gradle distribution version to gradle-6.5-bin, made the build work again. (P.S. We also didn't make any code changes before it started breaking.)

@dibir-magomedsaygitov Thanks for the suggestion.

**Comment by styluo** [comment]
ndk version from 22.1.7171670 to 23.0.7599858 in macos-latest
The NdkLocator.kt in gradle plugin 3.5.0 will use the highest version
```kt
private fun findNdkPathImpl(
    ndkDirProperty: String?,
    androidNdkHomeEnvironmentVariable: String?,
    sdkFolder: File?,
    ndkVersionFromDsl: String?,
    getNdkVersionedFolderNames: (File) -> List<String>,
    getNdkSourceProperties: (File) -> SdkSourceProperties?
): File? {
	...
       // From the existing NDKs find the highest. We'll use this as a fall-back in case there's an
      // error. We still want to succeed the sync and recover as best we can.
      val highest = versionedLocations.firstOrNull()
}

fun findNdkPath(
    ndkVersionFromDsl: String?,
    projectDir: File
): NdkLocatorRecord {
    val properties = gradleLocalProperties(projectDir)
    val sdkPath = SdkLocator.getSdkLocation(projectDir).directory
    return findNdkPathWithRecord(
        ndkVersionFromDsl,
        properties.getProperty(NDK_DIR_PROPERTY),
        System.getenv("ANDROID_NDK_HOME"),
        sdkPath,
        ::getNdkVersionedFolders,
        ::getNdkVersionInfo
    )
}
```
So the environment variable (ANDROID_NDK_HOME) has no effect

**Comment by styluo** [comment]
ndk version from 22.1.7171670 to 23.0.7599858(ANDROID_NDK_LATEST_HOME) in macos-latest
The NdkLocator.kt in gradle plugin 3.5.0 will use the highest version
```kt
private fun findNdkPathImpl(
    ndkDirProperty: String?,
    androidNdkHomeEnvironmentVariable: String?,
    sdkFolder: File?,
    ndkVersionFromDsl: String?,
    getNdkVersionedFolderNames: (File) -> List<String>, // function that returns the NDK folders under $SDK/ndk
    getNdkSourceProperties: (File) -> SdkSourceProperties?
): File? {
 ...
       // From the existing NDKs find the highest. We'll use this as a fall-back in case there's an
      // error. We still want to succeed the sync and recover as best we can.
      val highest = versionedLocations.firstOrNull()
}

fun findNdkPath(
    ndkVersionFromDsl: String?,
    projectDir: File
): NdkLocatorRecord {
    val properties = gradleLocalProperties(projectDir)
    val sdkPath = SdkLocator.getSdkLocation(projectDir).directory
    return findNdkPathWithRecord(
        ndkVersionFromDsl,
        properties.getProperty(NDK_DIR_PROPERTY),
        System.getenv("ANDROID_NDK_HOME"),
        sdkPath,
        ::getNdkVersionedFolders,
        ::getNdkVersionInfo
    )
}
```
So the environment variable (ANDROID_NDK_HOME) has no effect

**Comment by dibir-magomedsaygitov** [comment]
Hello @WPrins. Have you tried to update gradle tools version to 4.1.0 and the gradle distribution version to gradle-6.5-bin to check if it helps to resolve the issue?

**Comment by palumbo67** [comment]
I get this issue when running `tns test android` on the Microsoft Hosted Mac agent. This was running fine but I am getting the error message:
```
Execution failed for task ':app:stripDebugDebugSymbols'.
No toolchains found in the NDK toolchains folder for ABI with prefix: arm-linux-androideabi
```

**Comment by nkarczmarzyk** [comment]
@palumbo67 We have the same issue when running `tns build android` on a Microsoft Hosted Mac agent (macOS-10.15).

**Comment by pluck011** [comment]
Saw this issue as well - supplying a working `ndkVersion` in the `build.gradle` fixed it for me.

**Comment by nkarczmarzyk** [comment]
Please don't make the same like mistake I did.
In the [readme](https://github.com/actions/virtual-environments/blob/main/images/macos/macos-10.15-Readme.md) for macos-10.15 it says that the NDK version 21.4.7075529 is the default. This is apparently wrong. After I set the version manually via `ndkVersion`, the build suceeded again.

**Comment by miketimofeev** [comment]
@nkarczmarzyk thanks for the heads up! The default means that `ndk-bundle` points to this ndk version, probably we need to be more specific about it.

**Comment by WPrins** [comment]
Thanks! We also fixed this for now by setting the `ndkVersion` in our gradle.build. In parallel we're looking into updating our gradle version furthe, this however also requires a different Java version requiring extra testing on our side.

**Comment by dibir-magomedsaygitov** [comment]
In this case I'm going to close the issue. Feel free to contact us if any.
