### ISSUE TITLE
Alibaba Cloud CLI installation fails when building Ubuntu images

### ISSUE THREAD

**Issue by aiceball** [actions/virtual-environments#4146]
### Description

When building an Ubuntu 20.04 image with `packer`, the following errors occur:

```
Error — Either HTTP response code for 'https://github.com/aliyun/aliyun-cli/releases/download/v3.0.93/aliyun-cli-linux-3.0.93-amd64.tgz' is wrong - '200' or exit code is not 0 - '23'. Waiting 30 seconds before the next attempt, 19 attempts left
Error — Either HTTP response code for 'https://github.com/aliyun/aliyun-cli/releases/download/v3.0.93/aliyun-cli-linux-3.0.93-amd64.tgz' is wrong - '200' or exit code is not 0 - '23'. Waiting 30 seconds before the next attempt, 18 
attempts left
...
```
Etc

Upon further inspection of the `aliyun-cli.sh` it seems the issue is caused by line
```
https://api.github.com/repos/aliyun/aliyun-cli/releases/latest | jq -r '.assets[].browser_download_url | select(contains("aliyun-cli-linux"))
```
returning 2 entries:
```
https://github.com/aliyun/aliyun-cli/releases/download/v3.0.93/aliyun-cli-linux-3.0.93-amd64.tgz
https://github.com/aliyun/aliyun-cli/releases/download/v3.0.93/aliyun-cli-linux-3.0.93-arm64.tgz
```

Adding `select(contains("arm"))` to the filter resolved the issue for me.

### Virtual environments affected

- [X] Ubuntu 16.04
- [X] Ubuntu 18.04
- [X] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

N/A

### Is it regression?

Yes

### Expected behavior

Build an Ubuntu image without issues

### Actual behavior

Fails to build an Ubuntu image

### Repro steps

Build an Ubuntu image using `packer`

**Comment by dibir-magomedsaygitov** [comment]
Hello @aiceball. Thank you for your report. I'll prepare PR with the fix.

**Comment by dibir-magomedsaygitov** [comment]
[PR](https://github.com/actions/virtual-environments/pull/4147) with the fix is merged. Closing the issue.
