### ISSUE TITLE
`instruments -s devices` command failing in workflow running on macOS 11 Xcode 13

### ISSUE THREAD

**Issue by simondelphia** [actions/virtual-environments#4157]
### Description

In my macOS-11 workflow I run the following shell command to get a list of available devices

    instruments -s devices

This used to work fine with Xcode 12.5 but now when I switched to Xcode 13 it isn't working.

When I ran it locally Xcode wanted to install additional command line tools… I assume then the reason why it's failing on GitHub actions is because these additional tools weren't installed for Xcode 13?

> instruments: error: Failed to locate 'instruments'.
> xcode-select: Failed to locate 'instruments', requesting installation of command line developer tools.

### Virtual environments affected

- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [X] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Not sure where this is

### Is it regression?

Maybe?

### Expected behavior

Should output list of devices

### Actual behavior

> Shell command exited with exit status 72 instead of 0.

(the shell command is executed via Fastlane)

### Repro steps

Run `instruments -s devices` with Xcode 13 selected in a GitHub actions workflow

**Comment by woodrufs** [comment]
FWIW, instruments was removed from the CLI in Xcode 13: 

> The deprecated instruments command-line tool has been removed; instead, use xctrace

https://developer.apple.com/documentation/xcode-release-notes/xcode-13-release-notes

**Comment by simondelphia** [comment]
Ah ok, thank you
