### ISSUE TITLE
Add SqlPackage to Windows

### ISSUE THREAD

**Issue by krokofant** [actions/virtual-environments#4158]
### Tool name

SqlPackage

### Tool license

Unsure. The tool already exists in the Ubuntu image.

### Add or update?

- [X] Add
- [ ] Update

### Desired version

latest/any

### Brief description of tool

This tool already exists in the Ubuntu image since #2787, see that issue for reference.
Please add this to Windows as well.

### URL for tool's homepage

https://docs.microsoft.com/en-us/sql/tools/sqlpackage/sqlpackage-download?view=sql-server-ver15

### Virtual environments affected

- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [x] Windows Server 2016
- [X] Windows Server 2019
- [X] Windows Server 2022

**Comment by al-cheb** [comment]
Hello, @krokofant 
We already pre-installed DACFx - https://github.com/actions/virtual-environments/blob/main/images/win/scripts/Installers/Install-DACFx.ps1

`sqlpackage.exe` util exists `C:\Program Files\Microsoft SQL Server\150\DAC\bin\sqlpackage.exe`

**Comment by krokofant** [comment]
@al-cheb Aha! Could this be made clearer in the readme?

The [Ubuntu18.04](https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu1804-README.md) lists SqlPackage but the [Windows ones](https://github.com/actions/virtual-environments/blob/main/images/win/Windows2019-Readme.md) does not. 😕

**Comment by al-cheb** [comment]
> @al-cheb Aha! Could this be made clearer in the readme?
> 
> The [Ubuntu18.04](https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu1804-README.md) lists SqlPackage but the [Windows ones](https://github.com/actions/virtual-environments/blob/main/images/win/Windows2019-Readme.md) does not. 😕

It's part of DacFx 15.0.5164.1.

**Comment by krokofant** [comment]
@al-cheb I get what you're saying, I just think it's not especially clear.

**Comment by Brains** [comment]
Getting error on `windows-latest` and `windows-2019`

> An error occurred trying to start process `'C:\Program Files\PowerShell\7\pwsh.EXE'` 
> with working directory `'C:\Program Files\Microsoft SQL Server\150\DAC\bin\'.`
> The directory name is invalid.

It worked before. Last time was `January 13, 2022`.

**Comment by Brains** [comment]
> Getting error on `windows-latest` and `windows-2019`
> 
> > An error occurred trying to start process `'C:\Program Files\PowerShell\7\pwsh.EXE'`
> > with working directory `'C:\Program Files\Microsoft SQL Server\150\DAC\bin\'.`
> > The directory name is invalid.
> 
> It worked before, last time was `January 13, 2022`.

Fixed with https://github.com/marketplace/actions/setup-sqlpackage which has run
```
C:\ProgramData\Chocolatey\bin\vswhere.exe -find **\SQLDB\**\15*\SqlPackage.exe
```
and found `sqlpackage` at
```
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\Extensions\Microsoft\SQLDB\DAC\150\sqlpackage.exe
```
