### ISSUE TITLE
macos-11 agents stuck on "Queued" status for hours 

### ISSUE THREAD

**Issue by pluck011** [actions/virtual-environments#4171]
### Description

Starting on 9/28/21, my builds in on Azure hosted agents (United States) running macos-11 are stuck in the "Queued" state for hours on end with the only output being: 
```
Acquiring an agent from the cloud:
Request queue position information is unavailable.
```

I have 5 Azure hosted agents (United States) and my builds have two parallel jobs that run. There are free agents and they are operational, but the pipeline doesn't progress for over an hour. 

They do eventually start progressing and finish, but instead of 15 minutes normally, it's over 2 hours. 

It also seems that many others are having issues as well as of the past few days:
https://developercommunity.visualstudio.com/t/Build-pipeline-stuck-for-hours/1541300?space=21&entry=problem&sort=newest&moreInfo=true&viewtype=all

https://developercommunity.visualstudio.com/t/Azure-DevOps:-Agent-Microsoft-hosted-MAC/1541643?space=21&entry=problem&sort=newest&moreInfo=true&viewtype=all

https://developercommunity.visualstudio.com/t/macOS-11-VM-Stuck-in-Empty-Queue/1537876?space=21&entry=problem&sort=newest&q=stuck

### Virtual environments affected

- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [X] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Current Image Version: `20210917.1`

### Repro steps

Seems to only be on macos-11 environments.

**Comment by miketimofeev** [comment]
Hi @pluck011!
We are aware of the issue and the engineering team is currently working on adding capacity to macOS-11 in Azure DevOps. Sorry for the inconvenience.
