### ISSUE TITLE
Maven installer does not use supplied download url

### ISSUE THREAD

**Issue by spyder007** [actions/virtual-environments#4172]
### Description

The Maven install section retrieves information from github (https://api.github.com/repos/apache/maven/tags) but then extracts the latest version number and manually builds a download link from www-eu.apache.org/dist/maven.

I ran into an issue this morning where that mirror was behind and the appropriate version (in this case, 3.8.3) wasn't there.  So we're pulling version numbers from github but downloading from apache?

I would think we'd want to be consistent:  either pull latest version from github and download from there OR get latest version from apache and download from there.

Github has a `zipball_url` property to pull from the binary.  

Can replace 
```
json=$(curl -s "https://api.github.com/repos/apache/maven/tags")
latestMavenVersion=$(echo $json | jq -r '.[] | select(.name | match("^(maven-[0-9.]*)$")) | .name' | head -1 | cut -d- -f2)
mavenDownloadUrl="https://www-eu.apache.org/dist/maven/maven-3/${latestMavenVersion}/binaries/apache-maven-${latestMavenVersion}-bin.zip"
```
with
```
json=$(curl -s "https://api.github.com/repos/apache/maven/tags")
$mavenDownloadUrl=$(echo $json | jq -r '.[] | select(.name | match("^(maven-[0-9.]*)$")) | .zipball_url' | head -1)
```

Alternatively, if the desire is to pull from apache, need to determine where their metadata is published and update accordingly.

### Virtual environments affected

- [X] Ubuntu 16.04
- [X] Ubuntu 18.04
- [X] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

No using public images, trying to build a private image using the provisioning scripts.

### Is it regression?

no

### Repro steps

Was only able to reproduce when www-eu.apache.org didn't have the most up-to-date version of maven as retrieved from https://api.github.com/repos/apache/maven/tags

**Comment by catthehacker** [comment]
I assumed that since there is no 'release' but only tags on maven repo they don't distribute binaries via GitHub (`apache-maven-${latestMavenVersion}-bin.zip` suggests it's a zip with a compiled binary) so that's why I recommended using GitHub for latest tag.

**Comment by spyder007** [comment]
@catthehacker Honestly, that works 9 times out of ten, but, right now, it's causing an issue because Github is reporting version 3.8.3 available, but apache doesn't have that version up yet.  Not sure how to remedy that.

**Comment by al-cheb** [comment]
Hello, @spyder007 
As a temporary workaround please update the [java-tools.sh](https://github.com/actions/virtual-environments/blob/main/images/linux/scripts/installers/java-tools.sh) script:
```
# Install Maven
mavenDownloadUrl=$(curl -sL https://maven.apache.org/download.cgi | grep -oP 'https://[^/"].+/apache-maven-.+-bin.zip(?=")')
download_with_retries $mavenDownloadUrl "/tmp" "maven.zip"
```

**Comment by spyder007** [comment]
@al-cheb Thank you, I've actually just been using the replacement I suggested above for the time being (downloading using the zipball_url provided by github).  Once this is fixed I will just discard my changes.

Thanks again!

**Comment by al-cheb** [comment]
PR https://github.com/actions/virtual-environments/issues/4172 is merged.
