### ISSUE TITLE
Set Xcode 13 as default for macOS agents

### ISSUE THREAD

**Issue by MP91** [actions/virtual-environments#4175]
### Description

Since Xcode 13 is released, it should be the default for the builds.

### Virtual environments affected

- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [X] macOS 10.15
- [X] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Every build with default Xcode uses Xcode 12.5.1

### Repro steps

Just start a build with Xcode and leave the version as default.

**Comment by miketimofeev** [comment]
Hi @MP91!
We have no objections to setting Xcode 13 as default. We will announce the change and switch the version in two weeks.

**Comment by miketimofeev** [comment]
@MP91 announcement created https://github.com/actions/virtual-environments/issues/4180
I'm going to close this issue, please track the progress in the announcement.
Thank you!
