### ISSUE TITLE
Azure CLI DevOps is not installed on Ubuntu images

### ISSUE THREAD

**Issue by maxim-lobanov** [actions/virtual-environments#418]
**Describe the bug**
Azure CLI DevOps should be installed as part of `Azure CLI` and should be available

**Question, Bug, or Feature?**: 
Bug

**Virtual environments affected**
- [ ] macOS 10.15
- [x] Ubuntu 16.04 LTS
- [x] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Expected behavior**
Azure CLI DevOps should be installed:
1) `az devops -h` should show correct help
2) `az --version` should show `azure-devops` in extensions section

**Actual behavior**
1) `az devops -h` fails
2) `az --version` doesn't show `azure-devops`

Additional information:
It is pretty strange that azure-devops is not installed because we have [a step to install it](https://github.com/actions/virtual-environments/blob/51d02f26f42e53bb963bb6bc9754501b28a3d2ba/images/linux/scripts/installers/azure-devops-cli.sh). Looks like step doesn't work properly

**Comment by maxim-lobanov** [comment]
Created based on https://github.com/microsoft/azure-pipelines-image-generation/issues/1478

**Comment by al-cheb** [comment]
Hello, @SiM22
I have prepared https://github.com/actions/virtual-environments/pull/442 PR.  Changes will be available after next image rollout (1-2 weeks approximately)

**Comment by al-cheb** [comment]
Hello, @SiM22
Azure CLI (azure-devops 0.17.0) has been rolled out. Feel free to reopen the issue if you have any concerns.
