### ISSUE TITLE
Ansible installed failing - ansible-playbook: command not found

### ISSUE THREAD

**Issue by u605902** [actions/virtual-environments#4186]
### Description

The installer which installs ansible is failing with the following error
azure-arm: Provisioning with Ansible...
    azure-arm: Creating Ansible staging directory...
    azure-arm: Creating directory: /tmp/packer-provisioner-ansible-local/6154885c-8288-a706-acb5-69242dde5123
    azure-arm: Uploading main Playbook file...
    azure-arm: Uploading inventory file...
    azure-arm: Executing Ansible: cd /tmp/packer-provisioner-ansible-local/6154885c-8288-a706-acb5-69242dde5123 && ANSIBLE_FORCE_COLOR=1 PYTHONUNBUFFERED=1 ansible-playbook /tmp/packer-provisioner-ansible-local/6154885c-8288-a706-acb5-69242dde5123/playbook.yml --extra-vars "packer_build_name=azure-arm packer_builder_type=azure-arm packer_http_addr=ERR_HTTP_ADDR_NOT_IMPLEMENTED_BY_BUILDER -o IdentitiesOnly=yes" --extra-vars ansible_python_interpreter=/usr/bin/python3 -c local -i /tmp/packer-provisioner-ansible-local/6154885c-8288-a706-acb5-69242dde5123/packer-provisioner-ansible-local127016377
**==> azure-arm: bash: ansible-playbook: command not found**

### Virtual environments affected

- [X] Ubuntu 16.04
- [X] Ubuntu 18.04
- [X] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

latest

### Expected behavior

Ansible installed

### Actual behavior

azure-arm: bash: ansible-playbook: command not found

### Repro steps

build the Linux runner

**Comment by al-cheb** [comment]
Hey, @u605902 
Please provide steps how to reproduce the issue. I don't see any issues with nightly builds.

**Comment by u605902** [comment]
Hi @al-cheb 

here is the step we are following

1. cloning the repo
2. using packer to build the image from ubuntu1804.json using azure pipelines
3. we are getting the above error 

azure-arm: Executing Ansible: cd /tmp/packer-provisioner-ansible-local/6154885c-8288-a706-acb5-69242dde5123 && ANSIBLE_FORCE_COLOR=1 PYTHONUNBUFFERED=1 ansible-playbook /tmp/packer-provisioner-ansible-local/6154885c-8288-a706-acb5-69242dde5123/playbook.yml --extra-vars "packer_build_name=azure-arm packer_builder_type=azure-arm packer_http_addr=ERR_HTTP_ADDR_NOT_IMPLEMENTED_BY_BUILDER -o IdentitiesOnly=yes" --extra-vars ansible_python_interpreter=/usr/bin/python3 -c local -i /tmp/packer-provisioner-ansible-local/6154885c-8288-a706-acb5-69242dde5123/packer-provisioner-ansible-local127016377
==> azure-arm: bash: ansible-playbook: command not found

**Comment by al-cheb** [comment]
@u605902 , We don't use ansible to build an image. Please provide a script with test repo what we can reproduce the issue from our side.

**Comment by u605902** [comment]
@al-cheb  we are using packer to build the image here are the steps

1. clone repo 
 git clone https://github.com/actions/virtual-environments.git

2. running this on azure pipeline as step
packer build \
          -force  \
          -var 'subscription_id=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx \
          -var 'resource_group=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx' \
          -var 'location=eastus2' \
          -var 'announcements=devops-build-agent-image' \
          -var 'private_virtual_network_with_public_ip=false' \
          -var 'github_feed_token=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx' \
          -var 'storage_account=xxxxxxxxxxxxxxxxxx' \
          -var 'managed_image_resource_group_name=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx' \
          -var 'managed_image_name=devops-agent-image-ubuntu1804' \
          fl_ubuntu1804.json

build fails.

**Comment by al-cheb** [comment]
> @al-cheb we are using packer to build the image here are the steps
> 
> 1. clone repo
>    git clone https://github.com/actions/virtual-environments.git
> 2. running this on azure pipeline as step
>    packer build 
>    -force  
>    -var 'subscription_id=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx 
>    -var 'resource_group=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx' 
>    -var 'location=eastus2' 
>    -var 'announcements=devops-build-agent-image' 
>    -var 'private_virtual_network_with_public_ip=false' 
>    -var 'github_feed_token=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx' 
>    -var 'storage_account=xxxxxxxxxxxxxxxxxx' 
>    -var 'managed_image_resource_group_name=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx' 
>    -var 'managed_image_name=devops-agent-image-ubuntu1804' 
>    fl_ubuntu1804.json
> 
> build fails.

We don't have `fl_ubuntu1804.json` template. I will close the thread, because  the issue doesn't related to current repo. All additional question you can ask - https://github.com/actions/virtual-environments/discussions

**Comment by u605902** [comment]
@al-cheb  that was typo. here is the file what we are using 

packer build
-force
-var 'subscription_id=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
-var 'resource_group=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
-var 'location=eastus2'
-var 'announcements=devops-build-agent-image'
-var 'private_virtual_network_with_public_ip=false'
-var 'github_feed_token=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
-var 'storage_account=xxxxxxxxxxxxxxxxxx'
-var 'managed_image_resource_group_name=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
-var 'managed_image_name=devops-agent-image-ubuntu1804'
ubuntu1804.json

**Comment by al-cheb** [comment]
> @al-cheb that was typo. here is the file what we are using
> 
> packer build -force -var 'subscription_id=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx -var 'resource_group=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx' -var 'location=eastus2' -var 'announcements=devops-build-agent-image' -var 'private_virtual_network_with_public_ip=false' -var 'github_feed_token=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx' -var 'storage_account=xxxxxxxxxxxxxxxxxx' -var 'managed_image_resource_group_name=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx' -var 'managed_image_name=devops-agent-image-ubuntu1804' ubuntu1804.json

Our repo doesn't contain any steps related to invoke ansible or ansible-playbook(playbook.yml) commands.
