### ISSUE TITLE
CocoaPods from build report doesn't match version in Readme. 

### ISSUE THREAD

**Issue by ccorneliusHsv** [actions/virtual-environments#4198]
### Description

Trying to build latest version of our code. I'm attempting to update some code that requires a newer version of CocoaPods. I am using macOS 11. I expected the CocoaPods version to be CocoaPods 1.11.2..but when I ran the build I received the following error: 

> [21:09:36]: ▸ [!] `React` requires CocoaPods version `>= 1.10.1`, which is not satisfied by your current version, `1.10.0`.

The information about the OS was:

> Current runner version: '2.283.1'
> Operating System
>   macOS
>   11.6
>   20G165
> Virtual Environment
>   Environment: macos-11
>   Version: 20210917.1
>   Included Software: https://github.com/actions/virtual-environments/blob/macOS-11/20210917.1/images/macos/macos-11-Readme.md
>   Image Release: https://github.com/actions/virtual-environments/releases/tag/macOS-11%2F20210917.1

Of note - I just went through this same issue on my development machine where I had installed a newer version of CocoaPods, but it kept building with the older version. I found a solution to my problem here https://stackoverflow.com/questions/25016382/cocoa-pods-need-to-completely-re-install/25021772#25021772  Not sure if that helps..just thought I would include it just in case. 

### Virtual environments affected

- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [X] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

  Environment: macos-11
  Version: 20210917.1
  Included Software: https://github.com/actions/virtual-environments/blob/macOS-11/20210917.1/images/macos/macos-11-Readme.md
  Image Release: https://github.com/actions/virtual-environments/releases/tag/macOS-11%2F20210917.1

### Repro steps

I have a React Native project that requires a version of CocoaPods >= 1.10.1. Building this project is reporting an error on the 'pod install' step. I have run the build multiple times and the same error is reported each time: 

> [15:15:03]: ▸ [!] `React` requires CocoaPods version `>= 1.10.1`, which is not satisfied by your current version, `1.10.0`.

**Comment by miketimofeev** [comment]
Hi @ccorneliusHsv!
Could you provide steps and sample code to reproduce the issue? It will significantly help us investigating the issue

**Comment by ccorneliusHsv** [comment]
Unfortunately, original source is in a private repo. I'll see what I can put together to reproduce the issue in a public repo.

**Comment by miketimofeev** [comment]
@ccorneliusHsv another question — what version do you set in your podfile? 
Could you try to use for example this action https://github.com/maxim-lobanov/setup-cocoapods, does it solves the issue?

**Comment by ccorneliusHsv** [comment]
@miketimofeev  I've put together a coding sample and it builds correctly. That leads me to believe that it's my project setup that is somehow triggering the older version of cocoapods. I am going to close this bug report as it does not appear to be an issue with the vitrual-environment. If I can establish what causes this, I will add info here.

**Comment by ccorneliusHsv** [comment]
Looks like the GemFile.lock had a specific version of CocoPods specified. Used `bundle update` and not CocoaPods runs correctly.
