### ISSUE TITLE
Version 20210919.1: Cannot find libsystemd or libsystemd-journal

### ISSUE THREAD

**Issue by agostinofacotti** [actions/virtual-environments#4199]
### Description

From the introduction of version 20210919.1 our build workflow became broken.

We use setuptools to build a python package and the workflow was working good until the introduction of the 20210919.1 ubuntu version.

The error now is during the installation of the package:
```
ERROR: Command errored out with exit status 1:
     command: /usr/local/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-wheel-vbapp9yh/systemd-python_2470fd7b4c6c4b0a95f9097a4a80369e/setup.py'"'"'; __file__='"'"'/tmp/pip-wheel-vbapp9yh/systemd-python_2470fd7b4c6c4b0a95f9097a4a80369e/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-nqwkfi_c
         cwd: /tmp/pip-wheel-vbapp9yh/systemd-python_2470fd7b4c6c4b0a95f9097a4a80369e/
    Complete output (12 lines):
    Cannot find libsystemd or libsystemd-journal:
    
    Package libsystemd was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libsystemd.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libsystemd' found
    
    Package libsystemd-journal was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libsystemd-journal.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libsystemd-journal' found
    
    ----------------------------------------
```

Workaround
========

Adding an  `apt-get update` and `apt-get install libsystemd-dev` at the beginning of the workflow solved the problem. 

### Virtual environments affected

- [ ] Ubuntu 16.04
- [X] Ubuntu 18.04
- [X] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

  Environment: ubuntu-20.04
  Version: 20210919.1

Failed build link: https://github.com/covmatic/stations/runs/3743352202?check_suite_focus=true

### Is it regression?

Yes, it worked before. Link to the latest good build: https://github.com/covmatic/stations/actions/runs/1279583569

### Expected behavior

To work as before.

### Actual behavior

The package libsystemd needed for the build that in the previous image was already present in the 20210919.1 image is missing.

### Repro steps

Launch just launch a build on that repo.

**Comment by al-cheb** [comment]
Hello, @agostinofacotti 
We will take a look at it.

**Comment by al-cheb** [comment]
@agostinofacotti ,
I see the image version did not change -  `20210919.1`:
![image](https://user-images.githubusercontent.com/47745270/135588688-8e4974cc-8fc3-480e-85b6-25c41d79030e.png)
![image](https://user-images.githubusercontent.com/47745270/135588715-13d13379-0e1b-4505-9658-e48750dad6ca.png)

**Comment by agostinofacotti** [comment]
@al-cheb Yes, you are right!
I compared at first the last good run with a newest one ([this](https://github.com/covmatic/stations/actions/runs/1292092224)).
So the problem is hidden somewhere else.

I'll take a look to find anything different...

Thanks for your support 👍
