### ISSUE TITLE
exe is not compatible with the version of Windows you're running. 

### ISSUE THREAD

**Issue by FrancescElies** [actions/virtual-environments#4204]
### Description

When I call the following executable [tokei-x86_64-pc-windows-msvc.exe](https://github.com/XAMPPRocky/tokei/releases/download/v12.1.2/tokei-x86_64-pc-windows-msvc.exe) I get the following error.

```
This version of D:\a\1\s\venv\packages\tokei.exe is not compatible with the version of Windows you're running. 
Check your computer's system information and then contact the software publisher.
```

I am pretty sure this executable works on x64 (locally does at least). Why is it failing on CI?

### Virtual environments affected

- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [X] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

No build link, we are on a private repo.

Microsoft Windows Server 2019
10.0.17763
Current agent version: '2.192.0'
Current image version: '20210928.2'

### Expected behavior

I expect to be able to run the executable

### Actual behavior

exe throws an error

### Repro steps

1. get the exe
2. run it
3. 💥

**Comment by al-cheb** [comment]
Hey, @FrancescElies 
I can't reproduce the same issue:
![image](https://user-images.githubusercontent.com/47745270/135616118-526bb112-6e03-485b-8c3f-f9e856c39bfc.png)

**Comment by FrancescElies** [comment]
you are right! I tried with `invoke-webrequest` and it worked.

I realized the mistake I made, the file I was using it was lfs but the checkout was with `lfs: false`. 😓

Sorry for the false alarm @al-cheb
