### ISSUE TITLE
Add nasm to Windows virtual machine

### ISSUE THREAD

**Issue by snowstakeda** [actions/virtual-environments#421]
**Tool information**
- Tool name: nasm
- Add or update? Add
- Desired version: 2.14.02
- Approximate size: 1 MB
- If this is an add request:
  - Brief description of tool: OpenSSL requires to compile assemble code using nasm
  - URL for tool's homepage: https://www.nasm.us/

**Area for Triage**:
C/C++

**Question, Bug, or Feature?**:
Feature

**Virtual environments affected**
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [x] Windows Server 2016 R2
- [x] Windows Server 2019

**Can this tool be installed during the build?**
Download https://www.nasm.us/pub/nasm/releasebuilds/2.14.02/win64/nasm-2.14.02-win64.zip and extract it.

**Are you willing to submit a PR?**
not sure where I should patch yet.

**Comment by thejoebourneidentity** [comment]
Thanks for your suggestion 🙏. This is not something we will add to the image at this time. Please consider [writing a `setup-nasm` action](https://github.com/actions/toolkit) that installs this tool as part of your build and share with the community!

**Comment by EwoutH** [comment]
@thejoebourneidentity Could you reconsider it at this time?

@sfc-gh-stakeda Thanks for this issue! I would also like to see Nasm on Ubuntu 20.04. The most recent version now is 2.15.05.

**Comment by maxim-lobanov** [comment]
@EwoutH , there is a community task [setup-nasm](https://github.com/marketplace/actions/set-up-nasm) to install it in runtime. Please consider using it.
Considering the fact that tool is pretty small and can be installed in runtime, we wouldn't like to bake it into the image due to maintenance concerns
