### ISSUE TITLE
Add Tex Live

### ISSUE THREAD

**Issue by j-marcon** [actions/virtual-environments#4217]
### Tool name

Tex Live

### Tool license

https://www.tug.org/texlive/copying.html

### Add or update?

- [X] Add
- [ ] Update

### Desired version

latest

### Brief description of tool

System for building (La)TeX documents, widely used in the science community.

### URL for tool's homepage

https://www.tug.org/texlive/

### Virtual environments affected

- [X] Ubuntu 16.04
- [X] Ubuntu 18.04
- [X] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Can this tool be installed during the build?

```bash
sudo apt-get install texlive-full
```

### Tool installation time in runtime

7m 27s

### Are you willing to submit a PR?

I can look into it but should be fairly straightforward otherwise

**Comment by mikhailkoliada** [comment]
@j-marcon Hello!

We will discuss it and come back to you as soon as possible.

**Comment by mikhailkoliada** [comment]
@j-marcon

 we are unlikely to add texlive to our hosted images, the resulting weight of the installed files is too high (full texlive distribution might take up to 15Gb of the disk space). As a person who has been contributing to the texlive upstream I can tell you that the distribution itself is consisting of thousands of tiny macros packages taken from [CTAN](https://ctan.org/tex-archive/systems/texlive/tlnet?lang=en). These files then are being packed by the Linux distro developers (the original texlive has its own installer, but the distro's maintainers must do repackage those collections of macros provided by the upstream to make it work inside the distro).

Apart from that the `texlive-full` is just a meta package, it installs so-called texlive collections I've mentioned above. Say, it is going to pull the `texlive-graphics` collection (consists of packages like `beamer`, `pgf`, etc), or the `texlive-fontsextra` one (consists of thousands of font files, as neither `pdftex` nor `pdflatex` compiler might work with the system otf/ttf fonts, they only work with [T1](https://helpx.adobe.com/fonts/kb/postscript-type-1-fonts-end-of-support.html) ones). All those collections are unlikely to find their target audience in the future.

I would suggest you using the [setup-texlive](https://github.com/marketplace/actions/setup-texlive) action instead or indeed install the packages you need in runtime.

**Comment by miketimofeev** [comment]
@j-marcon, as @mikhailkoliada mentioned the recommended way to install the tools, is to use an action. For tex there are at least two actions available:
https://github.com/marketplace/actions/github-action-for-latex
https://github.com/marketplace/actions/setup-texlive
Considering tool size and maintenance concerns we wouldn't like to bake it into the image. I'm going to close the issue. Feel free to contact us if you have any concerns.
Thank you!

**Comment by blackdesert575** [comment]
> [@j-marcon](https://github.com/j-marcon), as [@mikhailkoliada](https://github.com/mikhailkoliada) mentioned the recommended way to install the tools, is to use an action. For tex there are at least two actions available: https://github.com/marketplace/actions/github-action-for-latex https://github.com/marketplace/actions/setup-texlive Considering tool size and maintenance concerns we wouldn't like to bake it into the image. I'm going to close the issue. Feel free to contact us if you have any concerns. Thank you!

Thanks a lot!
