### ISSUE TITLE
Error when compile flutter app

### ISSUE THREAD

**Issue by bitsjoanrobira** [actions/virtual-environments#4225]
### Description

Hello:

No toolchains found in the NDK toolchains folder for ABI with prefix: arm-linux-androideabi
Cause: android license not accepted

Thank you very much

### Virtual environments affected

- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [X] Ubuntu 20.04
- [ ] macOS 10.15
- [X] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Current

### Repro steps

[!] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

No toolchains found in the NDK toolchains folder for ABI with prefix: arm-linux-androideabi
Cause: android license not accepted

**Comment by miketimofeev** [comment]
Hi @bitsjoanrobira!
Is it the same issue as described here?
https://github.com/actions/virtual-environments/issues/4144#issuecomment-929295216
Does the workarounds help?

**Comment by bitsjoanrobira** [comment]
> Hi @bitsjoanrobira! Is it the same issue as described here? [#4144 (comment)](https://github.com/actions/virtual-environments/issues/4144#issuecomment-929295216) Do the workarounds help?

yes, is the same

**Comment by Darleev** [comment]
@bitsjoanrobira Does the workaround help you to resolve the issue?
We're looking forward to your reply.

**Comment by miketimofeev** [comment]
@bitsjoanrobira I'm going to close the issue as we haven't received a reply from you.
Please feel free to contact us if you have any concerns.
Thank you!
