### ISSUE TITLE
Python.sh - 3.6.9 is causing errors in pipx-packages.sh

### ISSUE THREAD

**Issue by Chaouki-Tiouassiouine** [actions/virtual-environments#4236]
### Description

While running the pipx-packages.sh in our Docker file we are getting an error.
We make use of the python.sh install (it installs version 3.6.9) which provided via the virtual environments. 
When we adjust the python.sh to install a version 3.7 or higher we do not get the error down below.
Could you refactor the script so it installs 3.7 or higher?

> [32/38] RUN ./virtual-environments/installers/pipx-packages.sh:
#36 0.329 Install yamllint into default python
#36 9.579 Note: '/root/.local/bin' is not on your PATH environment variable. These apps
#36 9.579     will not be globally accessible until your PATH is updated. Run `pipx
#36 9.579     ensurepath` to automatically add it, or manually modify your PATH in your
#36 9.579     shell's config file (i.e. ~/.bashrc).
#36 9.579 done!
#36 9.579 creating virtual environment...
#36 9.579 creating shared libraries...
#36 9.579 upgrading shared libraries...
#36 9.579 installing yamllint...
#36 9.579   installed package yamllint 1.26.3, Python 3.6.9
#36 9.579   These apps are now globally available
#36 9.579     - yamllint
#36 9.603 Install ansible-core into default python
#36 15.62 Fatal error from pip prevented installation. Full pip output in file:
#36 15.62     /root/.local/pipx/logs/cmd_2021-10-07_12.44.07_pip_errors.log
#36 15.63
#36 15.63 pip seemed to fail to build package:
#36 15.63     ansible-core
#36 15.63
#36 15.63 Some possibly relevant errors from pip install:
#36 15.63     UnicodeEncodeError: 'ascii' codec can't encode character '\xe9' in position 117: ordinal not in range(128)
#36 15.63 Error installing ansible-core.
#36 15.63 creating virtual environment...
#36 15.63 installing ansible-core...

### Virtual environments affected

- [ ] Ubuntu 16.04
- [X] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

We do use the ubuntu 18.04 of the virtual environments

### Repro steps

Docker file with the steps as described in the ubuntu18.04 json.
We download and install the prerequisites. 

When pipx-packages is ready to get installed, it is generating errors as shown in the description.

**Comment by Chaouki-Tiouassiouine** [comment]
@vsafonkin that is great, did you found the log files when the error occurs? If yes, could you please provide it so that @mikhailkoliada can check the log files. It would be best if this team decides to upgrade to 3.7 or higher so that the workaround is not needed

**Comment by Chaouki-Tiouassiouine** [comment]
I run the Docker Build and Push step in Azure DevOps. Oke so with other words we will have to adjust the pipx scripts ourselves and keep it in our repo.

**Comment by vsafonkin** [comment]
@Chaouki-Tiouassiouine, sorry, I thought your last comment was not a question. Yes, since we can't do something from our side you can try to adjust the pipx scripts ourselves.

**Comment by vsafonkin** [comment]
Closed, because we cannot do anything from our side.
