### ISSUE TITLE
Windows Server 2022 with Visual Studio 2022 ARM64 missing atls.lib

### ISSUE THREAD

**Issue by fcharlie** [actions/virtual-environments#4244]
### Description

When I built my project based on Windows Server 2022 (Visual Studio 2022), the ARM64 platform failed to build and reported missing atls.lib. I suspect that this problem is caused by not installing `Microsoft.VisualStudio.Component.VC.ATL.ARM64`. 

https://github.com/baulk/baulk/runs/3844027152?check_suite_focus=true

### Virtual environments affected

- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

20211003.1

### Repro steps

Enter the image and run the following command(powershell):  

```powershell
ls "C:\Program Files\Microsoft Visual Studio\2022\Preview\VC\Tools\MSVC\14.30.30528\ATLMFC\lib\ARM64"
```

**Comment by dibir-magomedsaygitov** [comment]
Hello @fcharlie. We have added `Microsoft.VisualStudio.Component.VC.ATL.ARM64` component to WIndows-2022 and it should be available later next week. I'll post an update message.

**Comment by fcharlie** [comment]
@dibir-magomedsaygitov Thanks

**Comment by dibir-magomedsaygitov** [comment]
Hello @fcharlie. `Microsoft.VisualStudio.Component.VC.ATL.ARM64` should available across all the WIndows images. I'm going to close this issue. Feel free to contact us in case of any questions.

**Comment by fcharlie** [comment]
@dibir-magomedsaygitov Great
