### ISSUE TITLE
Add Python 3.11 pre-releases

### ISSUE THREAD

**Issue by scop** [actions/virtual-environments#4246]
### Tool name

Python

### Tool license

PSF

### Add or update?

- [ ] Add
- [X] Update

### Desired version

Whatever is latest 3.11 pre-release, currently 3.11.0a1

### Virtual environments affected

- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [ ] Windows Server 2022

**Comment by EwoutH** [comment]
Quick question: Is Python 3.11 available in the Azure `UsePythonVersion` task? I can't find it in the [docs](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/tool/use-python-version?view=azure-devops).

**Comment by miketimofeev** [comment]
@EwoutH no, it is not as the task can't download versions on the fly and Python 3.11 is not pre-cashed on the image.
