### ISSUE TITLE
Add Pyston

### ISSUE THREAD

**Issue by scop** [actions/virtual-environments#4247]
### Tool name

Pyston

### Tool license

PSF

### Add or update?

- [X] Add
- [ ] Update

### Desired version

Whatever is latest, currently 2.3.1

### Brief description of tool

Performance enhanced Python.

### URL for tool's homepage

 https://github.com/pyston/pyston

### Virtual environments affected

- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [ ] Windows Server 2022

**Comment by miketimofeev** [comment]
@scop given the popularity of the tool and maintenance concerns, we would not like to add it to images. We can revisit this request in the future, but for now, we recommend installing pyston either in runtime or consider creating an action for the installation.
I'm going to close the issue. Please feel free to contact us if you have any concerns.
Thank you!
