### ISSUE TITLE
Update [azure-sdk-for-java<1.29.0] to fix RELEASE_7 WARNING

### ISSUE THREAD

**Issue by sorryusernameisalreadytaken** [actions/virtual-environments#425]
**Tool information**
- Tool name: azure-sdk-for-java
- Add or update? update
- Desired version: <1.29.0 or latest
- Approximate size: 

**Area for Triage**:

**Question, Bug, or Feature?**:
Feature

**Virtual environments affected**
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
I dont know if affected:
- [ ] macOS 10.15
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Can this tool be installed during the build?**
?

**Are you willing to submit a PR?**
No but it should be availibe here: https://github.com/Azure/azure-sdk-for-java
Here is the mentioned WARNING fix: https://github.com/Azure/azure-sdk-for-java/issues/1653#issuecomment-563928086

**Comment by miketimofeev** [comment]
@sorryusernameisalreadytaken could you provide a bit more details, please? What pipelines are affected? I can't see preinstalled azure-sdk-for-java in Ubuntu readmes'
https://github.com/actions/virtual-environments/releases/tag/ubuntu18%2F20200217.1
https://github.com/actions/virtual-environments/releases/tag/ubuntu16%2F20200217.1

**Comment by maxim-lobanov** [comment]
@sorryusernameisalreadytaken , Hello, as @miketimofeev mentioned, we don't pre-install any `azure-sdk-for-java` on our images.
But please let me know if we missed something
