### ISSUE TITLE
Allow software version to lag

### ISSUE THREAD

**Issue by Diggsey** [actions/virtual-environments#4269]
### Description

Recently Github updated all images to Postgres 14. This has caused a lot of breakage, from issues like https://github.com/actions/virtual-environments/issues/4243 to https://www.postgresql.org/message-id/flat/16040-eaacad11fecfb198%40postgresql.org

This policy of immediately updating all existing images across major software versions is doomed to cause problems for end-users when we have no way to pin images.

It should be possible for users to pin to a major version of important software on an image. If I ask for image X one day that has postgres 13, then when I ask for image X the next day I should not get postgres 14.

To reduce maintenance cost on Github, I think it would be reasonable to impose limits (eg. when postgres 15 is released, then 13 can stop being supported).

### Virtual environments affected

- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

N/A

### Repro steps

N/A

**Comment by mikhailkoliada** [comment]
I have opened separate tasks for each package and we will handle them separately. This issue now can be closed.
@Diggsey Thanks a lot!
