### ISSUE TITLE
WDK should be installed after VS 2019 and not before

### ISSUE THREAD

**Issue by jimlamb** [actions/virtual-environments#428]
**Describe the bug**
The WDK needs to be installed after VS 2019, not before.

**Area for Triage**: 

**Question, Bug, or Feature?**: 
Bug

**Virtual environments affected**
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [x] Windows Server 2019

**Expected behavior**
If you take the output of the VS 2019 KMDF project template and try to build it, it should build successfully.

**Actual behavior**
If the WDK is installed before VS 2019, you'll get the following error when you try to build that basic KMDF project:

    Error MSB8020: The build tools for WindowsKernelModeDriver10.0 (Platform Toolset = 'WindowsKernelModeDriver10.0') cannot be found.

**Comment by vmapetr** [comment]
Hi @jimlamb! This issue has been discussed in https://github.com/actions/virtual-environments/issues/259 previously. We working on the fix now.

**Comment by jimlamb** [comment]
Thanks, @vmapetr. I'm the one who helped nibanks diagnose the issue. Let me know if I can help verify the fix.
