### ISSUE TITLE
Update installer scripts to pass superlinter

### ISSUE THREAD

**Issue by jeffj254** [actions/virtual-environments#4283]
### Description

We use a fork of this repo to build an ami for our internal self-hosted runners.  We've added some installers of our own to our fork, and we have superlint enabled on our repo to keep us writing quality code.  We've noticed though, that most of the install scripts from this repo do not currently pass the default linting checks in superlinter.  For now we're excluding scripts from this repo from superlinter and only including our internal scripts, but that's not the nicest workaround, especially as we add additional customizations.

Looking at this repo, it seems superlinter is enabled, but only for JSON and markdown files.  Enabling superlinter for all of the setup scripts here and updating them to pass, would improve their code quality and help them match expected industry standards.

### Virtual environments affected

- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [X] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Ubuntu 20.04 20211011.1

### Is it regression?

No

### Expected behavior

All install, helper, and report scripts pass superlinter

### Actual behavior

Numerous scripts fail default linting checks

### Repro steps

1. Enable Superlinter for all files and all languages
2. Run against the repo

**Comment by miketimofeev** [comment]
@jeffj254 we have created separate issues for each OS and put them in the backlog so this issue can be closed for now.
