### ISSUE TITLE
Npm Restore 15x slower when going from Ubuntu 1604 > Newer

### ISSUE THREAD

**Issue by andtii** [actions/virtual-environments#4284]
### Description

NPM Restore is 15x slower when changing base image från Ubuntu 1604 to any newer 18 or 20. A simple npm restore for 1600 packages goes from 1 minute to 15 or more on any newer Ubuntu version

### Virtual environments affected

- [ ] Ubuntu 16.04
- [X] Ubuntu 18.04
- [X] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

All Ubuntu above 1604

### Is it regression?

No

### Expected behavior

Since Ubuntu 1604 is deprecated and we need to move to newer version the expected behavior is that a NPM Restore should be as fast as on Ubuntu 1604

### Actual behavior

When just simply moving the agent spec from Ubuntu 1604 to any never Ubuntu 18 or 20 The NPM restore times goes from 1 minute (on ubuntu 1604) to a whopping 15 Minutes. Totally crazy

### Repro steps

Run a NPM restore task on a project with lots of dependencies like React Project and you will see a big difference between Ubuntu 1604 and all newer versions

**Comment by dibir-magomedsaygitov** [comment]
Hello @andtii. Thank you for your report. We will take a look.

**Comment by andtii** [comment]
![image](https://user-images.githubusercontent.com/1434571/137887018-8d97b8cf-7109-4353-822f-727d87aad3c5.png)

**Comment by dsame** [comment]
It is confirmed npm of version 6 is very slow on ubuntu and osx images. It is the problem of npm v6 it self and reproduced on the local machines.

@andtii as a workaround please upgrade npm to version 7 or use alternatives - yarn or pnpm
@miketimofeev i believe the default npm should be upgraded to at least 7th version on the images.

**Comment by miketimofeev** [comment]
@dsame we install npm as a part of Nodejs version. Npm version 7 comes along with the Nodejs 16 yet we install version 14 at the moment as it is LTS. Ubuntu16 image also came with npm6, the only difference is the version 6.14.13 vs 6.14.15
