### ISSUE TITLE
DMG image creation fails on Big Sur

### ISSUE THREAD

**Issue by huskeee** [actions/virtual-environments#4288]
### Description

A workflow that uses macos-latest (currently Big Sur for our repository) will fail on the DMG image creation step with the error ```hdiutil: create failed - No space left on device
could not access /Volumes/Pixelorama/Pixelorama.app/Contents/Resources/Pixelorama.pck - No space left on device```. This does not happen when using macos-10.15, and wasn't happening when macos-latest was running Catalina either. It has been ensured that we don't exceed the hard disk space limit.

### Virtual environments affected

- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [x] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Virtual environment version: 20211011.3
Latest failed build: https://github.com/Orama-Interactive/Pixelorama/runs/3918898560

### Expected behavior

hdiutil is expected to create a DMG image from the macOS build folder.

### Actual behavior

hdiutil fails to create the DMG image with the error ```hdiutil: create failed - No space left on device
could not access /Volumes/Pixelorama/Pixelorama.app/Contents/Resources/Pixelorama.pck - No space left on device```.

### Repro steps

1. Create a workflow that runs on macos-latest (Big Sur) and uses hdiutil to create a DMG image.
2. hdiutil will fail to create the image, complaining that there's no space left on the device.

**Comment by al-cheb** [comment]
@huskeee , Could you try to set size or fs?
`hdiutil create -srcfolder ./build/mac -fs HFS+ -volname Pixelorama ./build/mac/Pixelorama.dmg`
or 
`hdiutil create -size 100mb -srcfolder ./build/mac -volname Pixelorama ./build/mac/Pixelorama.dmg`

**Comment by huskeee** [comment]
Specifying the file system fixes the error. Specifying the image size has not worked for us before (gave us an error that there was no space left in image, even though it was large enough for the contents.

Weird thing is that it only happens with Big Sur. On Catalina it works without setting the file system, [as you can see in this run](https://github.com/huskeee/Pixelorama/runs/3919281446).

**Comment by al-cheb** [comment]
> @al-cheb, Specifying the file system fixes the error. Specifying the image size has not worked for us before (gave us an error that there was no space left in image, even though it was large enough for the contents.
> 
> Weird thing is that it only happens with Big Sur. On Catalina it works without setting the file system, [as you can see in this run](https://github.com/huskeee/Pixelorama/runs/3919281446).

If the size is set up:
![image](https://user-images.githubusercontent.com/47745270/137702903-f4bc715a-27ea-438c-82ab-f775990ae5d5.png)

I think better to ask at https://developer.apple.com/forums why the behavior has been changed in macOS Big Sur.

**Comment by al-cheb** [comment]
I am planning to close the thread as external. Feel free to open the thread if you have any concerns.
