### ISSUE TITLE
Add macOS 12

### ISSUE THREAD

**Issue by Brett-Best** [actions/virtual-environments#4299]
### Tool name

macOS 12

### Tool license

https://www.apple.com/au/legal/sla/

### Add or update?

- [X] Add
- [ ] Update

### Desired version

12.0.1

### Brief description of tool

macOS 12 will be released to the public next Monday, I’m requesting access to a macOS 12 runner

### URL for tool's homepage

https://developer.apple.com/documentation/macos-release-notes/macos-12-release-notes

### Virtual environments affected

- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Can this tool be installed during the build?

```bash
No
```

**Comment by al-cheb** [comment]
Duplicate: https://github.com/actions/virtual-environments/issues/3649
