### ISSUE TITLE
MacOS runner takes 6 hours to run a 1 minute workflow

### ISSUE THREAD

**Issue by BrightRan** [actions/virtual-environments#430]
The customer has a [CI workflow](https://github.com/solodon4/Boost-for-Android/blob/master/.github/workflows/ci.yml) to build a subset of Boost libraries for Android, he setup a metrix job with the runners are `ubuntu-latest` and `macos-latest` in the workflow.
Normally, the job just needs a few minutes to complete, and it can run fine on  `ubuntu-latest`, but when the same job runs on `macos-latest`, the step **`Build Boost for Android on ${{ matrix.variation }}`** always is stuck until the job cancelled by timeout.
The step **`Build Boost for Android on ${{ matrix.variation }}`** only has one line command to execute:
```
- name: Build Boost for Android on ${{ matrix.variation }}
  run: CXXFLAGS="-std=c++14" ./build-android.sh --boost=1.70.0 --arch=armeabi-v7a --with-libraries=atomic,system "${NDK_ROOT}"
```
The customer try the same commands on his MacBook Air, it can work fine and only takes a few minutes.
I forked the customer's repository and tested, I can reproduce the same problem. Looks like, there is something wrong on the GitHub-hosted macOS runner.
I also have reported this issue [here](https://github.com/github/c2c-actions-compute/issues/467).

Associated ticket: https://github.community/t5/GitHub-Actions/BUG-MacOS-runner-takes-6-hours-to-run-a-1-minute-workflow/td-p/46053

**Comment by vsafonkin** [comment]
Hi @BrightRan! Thanks for the report! Unfortunately, we don’t support boost on our hosted macos systems. You can check details in [Add Boost on MacOS](https://github.com/actions/virtual-environments/issues/356)

**Comment by vsafonkin** [comment]
Hello @BrightRan, sorry for the delay.

We’ve figured out the reason of problem, Android NDK use some shared libs that are forbidden by default security policy on macOS. As temporary workaround for it  use brew android ndk install with `—no-quarantine` flag. Kernel extention security policies has been disabled recently, changes will be available in next image rollout (1-2 weeks approximately). Before that customer can use this as a workaround:
```
- name: Install dependencies (MacOS))
      run: |
        brew update
        brew cask install android-ndk --no-quarantine
        export NDK_ROOT="$(brew --prefix)/share/android-ndk"
        echo "::set-env name=NDK_ROOT::$NDK_ROOT"
```

**Comment by miketimofeev** [comment]
@BrightRan  @solodon4 
The issue has been fixed, could you check everything is fine now?

**Comment by solodon4** [comment]
Thank you Mikhail!

Do I need to change any versions of actions etc. or simply rerun my last failed commit?

Thank you!
Yuriy

**Comment by miketimofeev** [comment]
@solodon4 simply rerun should be fine 😃

**Comment by solodon4** [comment]
I can confirm the issue is gone. I was able to re-run successfully workflow from last failed commit and I have since had another commit in preparation for the pull request upstream.

Thank you guys!
