### ISSUE TITLE
php-intl extension missing

### ISSUE THREAD

**Issue by schrankenstein** [actions/virtual-environments#432]
**Describe the bug**
Hi everyone,

we use the azure build pipeline with the following image: ubuntu-latest.

We install php as in your sample here: https://docs.microsoft.com/en-us/azure/devops/pipelines/ecosystems/php?view=azure-devops

From this week on there is suddently the php-intl extension missing.

I thought you were using the following repo to build the agent/image: https://github.com/actions/virtual-environments redirected from here: https://github.com/microsoft/azure-pipelines-image-generation

As you can see here in the php.sh file, the intl extension should be installed: https://github.com/actions/virtual-environments/blob/master/images/linux/scripts/installers/1804/php.sh

Can you please have a look at it, as everyone must install the extension via apt install, which lasts in  extra build time.

Here is what should be installed:

apt-fast install -y --no-install-recommends \ php7.4 \ php7.4-bcmath \ php7.4-bz2 \ php7.4-cgi \ php7.4-cli \ php7.4-common \ php7.4-curl \ php7.4-dba \ php7.4-dev \ php7.4-enchant \ php7.4-fpm \ php7.4-gd \ php7.4-gmp \ php7.4-imap \ php7.4-interbase \ php7.4-intl \ php7.4-json \ php7.4-ldap \ php7.4-mbstring \ php7.4-mysql \ php7.4-odbc \ php7.4-opcache \ php7.4-pgsql \ php7.4-phpdbg \ php7.4-pspell \ php7.4-readline \ php7.4-snmp \ php7.4-soap \ php7.4-sqlite3 \ php7.4-sybase \ php7.4-tidy \ php7.4-xml \ php7.4-xmlrpc \ php7.4-xsl \ php7.4-zip
output from php -m:

PHP 7.4.2 (cli) (built: Feb  5 2020 16:50:38) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.2, Copyright (c), by Zend Technologies
    with Xdebug v2.9.1, Copyright (c) 2002-2020, by Derick Rethans
[PHP Modules]
amqp
apcu
bcmath
bz2
calendar
Core
ctype
curl
date
dba
dom
enchant
exif
FFI
fileinfo
filter
ftp
gd
gettext
gmp
hash
iconv
igbinary
imap
json
ldap
libxml
mbstring
memcache
memcached
mongodb
msgpack
mysqli
mysqlnd
odbc
openssl
pcntl
pcre
PDO
pdo_dblib
PDO_Firebird
pdo_mysql
PDO_ODBC
pdo_pgsql
pdo_sqlite
pgsql
Phar
posix
pspell
readline
redis
Reflection
session
shmop
SimpleXML
snmp
soap
sockets
sodium
SPL
sqlite3
standard
sysvmsg
sysvsem
sysvshm
tidy
tokenizer
xdebug
xml
xmlreader
xmlrpc
xmlwriter
xsl
yaml
Zend OPcache
zip
zlib
zmq

Best Regards,

Leo Schrank

**Area for Triage**: 
PHP

**Question, Bug, or Feature?**: 
Bug

**Virtual environments affected**
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [x] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Expected behavior**
PHP-intl extension should be installed

**Actual behavior**
PHP-intl extension isn't installed

**Comment by miketimofeev** [comment]
@schrankenstein thanks for reporting this. We've checked image-generation logs, and it seems powershellcore installation process removes php-intl packages for some reason. We will investigate a possible workaround
```
Reading package lists...
Building dependency tree...
Reading state information...
The following packages were automatically installed and are no longer required:
  bc dns-root-data dnsmasq-base ebtables grub-pc-bin landscape-common
  libdumbnet1 liblxc-common liblxc1 libuv1 linux-headers-4.15.0-72 lxcfs lxd
  lxd-client python3-attr python3-automat python3-click python3-colorama
  python3-constantly python3-hyperlink python3-incremental python3-pam
  python3-pyasn1 python3-pyasn1-modules python3-service-identity
  python3-twisted python3-twisted-bin python3-zope.interface uidmap xdelta3
Use 'sudo apt autoremove' to remove them.
The following packages will be REMOVED:
  libicu64 php7.1-intl php7.2-intl php7.3-intl php7.4-intl
0 upgraded, 0 newly installed, 5 to remove and 23 not upgraded.
After this operation, 34.8 MB disk space will be freed.
(Reading database ... 256693 files and directories currently installed.)
Removing php7.4-intl (7.4.1-1+ubuntu18.04.1+deb.sury.org+1) ...
Removing php7.3-intl (7.3.13-1+ubuntu18.04.1+deb.sury.org+1) ...
Removing php7.1-intl (7.1.33-3+ubuntu18.04.1+deb.sury.org+1) ...
Removing php7.2-intl (7.2.26-1+ubuntu18.04.1+deb.sury.org+1) ...
Removing libicu64:amd64 (64.2-0.1+ubuntu18.04.1+deb.sury.org+1) ...
Processing triggers for php7.1-fpm (7.1.33-3+ubuntu18.04.1+deb.sury.org+1) ...
Processing triggers for php7.4-fpm (7.4.1-1+ubuntu18.04.1+deb.sury.org+1) ...
Processing triggers for libc-bin (2.27-3ubuntu1) ...
Processing triggers for php7.3-fpm (7.3.13-1+ubuntu18.04.1+deb.sury.org+1) ...
Processing triggers for php7.2-fpm (7.2.26-1+ubuntu18.04.1+deb.sury.org+1) ...
```

**Comment by miketimofeev** [comment]
It looks like previously made workaround for powershell breaks the php-intl
https://github.com/actions/virtual-environments/blob/11cce431f0238e3eb62a05881f68d1d00239f070/images/linux/scripts/installers/1804/powershellcore.sh#L16
associated issue:
https://github.com/PowerShell/PowerShell/issues/9746

**Comment by miketimofeev** [comment]
@schrankenstein the image has been deployed. Could you check that extension is present now?

**Comment by limonte** [comment]
@miketimofeev all is well now, thank you :rocket: 

https://github.com/limonte/php-ext-intl-github-actions/runs/480001125

**Comment by miketimofeev** [comment]
@schrankenstein closing the issue. Feel free to reopen it if you have any concerns.
Thank you!
