### ISSUE TITLE
Add jazzy to macOS images

### ISSUE THREAD

**Issue by Richard-Gist** [actions/virtual-environments#4320]
### Tool name

jazzy

### Tool license

MIT

### Add or update?

- [X] Add
- [ ] Update

### Desired version

whatever is latest (currently 0.14.1)

### Brief description of tool

jazzy is a command-line utility that generates documentation for Swift or Objective-C

### URL for tool's homepage

https://github.com/realm/Jazzy

### Provide a basic test case to validate the tool's functionality.

```bash
jazzy -v

// if you could clone or create an xcode project, you can simply run:
// jazzy
// from the folder where the .xcodeproj can be found. Then if you can:
// ls docs/index.html
// And that returns a file, then all is working.
```

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [X] macOS 10.15
- [X] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Can this tool be installed during the build?

```bash
gem install jazzy
```

### Tool installation time in runtime

4m 26s

### Are you willing to submit a PR?

Yes, but I don't know how to add it. Will need directions.

**Comment by miketimofeev** [comment]
@Richard-Gist the images have been deployed.
I'm going to close the issue. Please feel free to contact us if you have any concerns.
Thank you!
