### ISSUE TITLE
Update/Add NSIS

### ISSUE THREAD

**Issue by nightlark** [actions/virtual-environments#4325]
### Tool name

NSIS

### Tool license

zlib/libpng license for everything except the bzip2 and lzma compression modules. bzip2 module is under the bzip2 license, and lzma module is under the Common Public License version 1.0

### Add or update?

- [X] Add
- [ ] Update

### Desired version

Whatever is the latest, or the same version as is installed on windows-2019 images

### Approximate size

7.1mb

### Brief description of tool

NSIS (Nullsoft Scriptable Install System) is a professional open source system to create Windows installers. It is designed to be as small and flexible as possible and is therefore very suitable for internet distribution. 

### URL for tool's homepage

https://nsis.sourceforge.io/Main_Page

### Provide a basic test case to validate the tool's functionality.

```bash
makensis /LICENSE
```

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Can this tool be installed during the build?

```bash
It looks like this script was used for installing NSIS in previous Windows VM images: https://github.com/actions/virtual-environments/blob/main/images/win/scripts/Installers/Install-NSIS.ps1

################################################################################
##  File:  Install-NSIS.ps1
##  Desc:  Install NSIS
################################################################################

Install-Binary -Url 'https://downloads.sourceforge.net/project/nsis/NSIS%203/3.06.1/nsis-3.06.1-setup.exe' -Name  nsis-3.06.1-setup.exe -ArgumentList ('/S')

$NsisPath = "${env:ProgramFiles(x86)}\NSIS\"
Add-MachinePathItem $NsisPath
$env:Path = Get-MachinePath

Invoke-PesterTests -TestFile "Tools" -TestName "NSIS"
```

### Tool installation time in runtime

Should be a few seconds, maybe an upper bound of 20 seconds if the download mirror is slow.

### Are you willing to submit a PR?

Sure, I should be able to figure out how to add it based on the older windows images.

**Comment by miketimofeev** [comment]
@nightlark the new image with pre-installed NSIS is deployed.
I'm going to close the issue. Please feel free to contact us if you have any concerns.
Thank you!
