### ISSUE TITLE
Update Android NDK to r23b LTS

### ISSUE THREAD

**Issue by Javernaut** [actions/virtual-environments#4328]
### Tool name

Android NDK

### Tool license

Same as before

### Add or update?

- [ ] Add
- [X] Update

### Desired version

23.1.7779620

### Virtual environments affected

- [X] Ubuntu 18.04
- [X] Ubuntu 20.04
- [X] macOS 10.15
- [X] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [ ] Windows Server 2022

**Comment by miketimofeev** [comment]
@Javernaut ubuntu and macOS images with the latest NDK r23 were deployed.
I'm going to close the issue. Please feel free to contact us if you have any concerns.
Thank you!
