### ISSUE TITLE
aws eks --get-token error

### ISSUE THREAD

**Issue by heronrs** [actions/virtual-environments#4329]
### Description

While installing a terraform managed Kubernetes cluster using the [exec-plugin](ghghgv3-us-east-1b-70bf7b3797eafd89)  authentication I'll start getting 255 errors from the aws cli. Updating the cli with `pip install -U awscli` seems to have solved it.

Some users mentioned this in https://github.com/kubernetes/kubectl/issues/747

### Virtual environments affected

- [ ] Ubuntu 18.04
- [X] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

```
  Environment: ubuntu-20.04
  Version: 20211017.0
  Included Software: https://github.com/actions/virtual-environments/blob/ubuntu20/20211017.0/images/linux/Ubuntu2004-README.md
  Image Release: https://github.com/actions/virtual-environments/releases/tag/ubuntu20%2F20211017.0
```

https://github.com/convox/convox/runs/3979816109?check_suite_focus=true#step:9:5143

### Is it regression?

no

### Expected behavior

`aws eks get-token --cluster-name name` returns a json response with an eks token

### Actual behavior

`getting credentials: exec: executable aws failed with exit code 255`

### Repro steps

It's difficult to understand how to reproduce because terraform successfully applies some k8s resources and then starts failing.
One could try installing some k8s resources using terraform or simulate the Action install step by downloading the [convox](https://github.com/convox/convox/releases/tag/3.0.55) bin and inside the ubuntu image setup aws creds and run `convox rack install aws somename`

**Comment by dibir-magomedsaygitov** [comment]
Hello @heronrs. Could you please check if the issue still persists?

**Comment by dibir-magomedsaygitov** [comment]
Hello @heronrs. Any updates on the issue?

**Comment by dibir-magomedsaygitov** [comment]
I'm going to close this issue for now. In case of any concerns or question feel free to reopen it or create new one.
