### ISSUE TITLE
Add VirtualBox and Vagrant for macOS instances

### ISSUE THREAD

**Issue by AkihiroSuda** [actions/virtual-environments#433]
**Tool information**
- Tool name: VirtualBox and Vagrant
- Add or update? Add
- Desired version: The version that can be installed with `brew`, or the latest version if possible.
- Approximate size: Hundreds of megabytes
- If this is an add request:
  - Brief description of tool: Create virtual machines
  - URL for tool's homepage: https://www.virtualbox.org/ https://www.vagrantup.com/

**Area for Triage**:

**Question, Bug, or Feature?**:

Feature

**Virtual environments affected**
- [X] macOS 10.15

(Only macOS instances seem to support nested virtualization currently)

**Can this tool be installed during the build?**
No, because of the VirtualBox's kernel extension issue: https://github.com/actions/virtual-environments/issues/429

So VirtualBox needs to be preinstalled as in [HAXM](https://github.com/actions/virtual-environments/blob/11cce431f0238e3eb62a05881f68d1d00239f070/images/macos/macos-10.15-Readme.md#extra-packages).

**Are you willing to submit a PR?**
No

**Comment by Beenhakker** [comment]
Did you stop any active Virtualbox instances before upgrading?

That was something I forgot to do.

**Comment by mvgijssel** [comment]
I would also be interested in this! Or at least approving the virtualbox team id kext, which allows folks to install virtualbox themselves.

**Comment by oxr463** [comment]
Is this already supported on Linux then?

**Comment by AkihiroSuda** [comment]
No, only macOS instances seem to support nested virtualization currently

**Comment by dmitry-shibanov** [comment]
Hello, pull request with vagrant and virtualbox was merged and changes would be added to next images rollout.

**Comment by oxr463** [comment]
> Hello, pull request with vagrant and virtualbox was merged and changes would be added to next images rollout.

Only for macOS though? The Linux issue was closed.

**Comment by maxim-lobanov** [comment]
@oxr463 , Yes, only for macOS.

**Comment by dmitry-shibanov** [comment]
Hello, Vagrant and VirtualBox were added to macOS. If you have any concerns feel free to reopen the issue.

**Comment by AkihiroSuda** [comment]
This seems removed on macOS 11.0 instances? :cry:

**Comment by al-cheb** [comment]
@AkihiroSuda, There is no stable VirtualBox release for macOS Big Sur.

**Comment by AkihiroSuda** [comment]
VirtualBox 6.1.16 seems working fine on macOS 11.1, though I haven't tested macOS 11.0.

**Comment by AkihiroSuda** [comment]
Opened https://github.com/actions/virtual-environments/issues/2999 for Big Sur

**Comment by dmotte** [comment]
FYI, now that the [`macos-10.15` environment is deprecated](https://github.com/actions/virtual-environments/issues/5583), I've switched to `macos-12` for my projects and it's working :)

Here are my workflow files:

- [dmotte/vagrant-dockerbox](https://github.com/dmotte/vagrant-dockerbox/blob/main/.github/workflows/release.yml)
- [dmotte/vagrant-podmanbox](https://github.com/dmotte/vagrant-podmanbox/blob/main/.github/workflows/release.yml)
