### ISSUE TITLE
Warning "macOS-latest workflows will use macOS-11 soon" even when not using "-latest" 

### ISSUE THREAD

**Issue by augustoproiete** [actions/virtual-environments#4332]
### Description

A warning "macOS-latest workflows will use macOS-11 soon" is shown on GitHub Actions Workflows that are **not** using `macos-latest` - but instead are using a specific version of macos, such as `macos-10.15`

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [X] macOS 10.15
- [X] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

- Workflow: https://github.com/augustoproiete/ExcelDnaPack-NuGet/blob/v1.5.0/.github/workflows/ci.yml#L29-L37
- Build with warning: https://github.com/augustoproiete/ExcelDnaPack-NuGet/actions/runs/1378917286

### Expected behavior

Given that the GitHub Actions Workflow does not use `macos-latest`, and instead use a specific version e.g. `macos-10.15`, no warnings should be emitted

### Actual behavior

Warning is emitted:

```
.github/workflows/ci.yml : .github#L1
macOS-latest workflows will use macOS-11 soon. For more details, see https://github.com/actions/virtual-environments/issues/4060
```

![image](https://user-images.githubusercontent.com/177608/138617407-c04d84cc-9b60-46a5-bc9f-51df90915a67.png)

### Repro steps

Create a workflow that runs on either `macos-10.15` or `macos-11` and you should see the warning described above.

**Comment by miketimofeev** [comment]
@augustoproiete this is fixed now, the messages are shown only in the following cases:
- macos-latest points to macos-10.15
- macos-latest points to macos-11 and the run is failed

In case a specific version e.g. macos-10.15 is used — no warnings are displayed.
I'm going to close the issue.
Please feel free to contact us if you have any concerns.
Thank you!
