### ISSUE TITLE
Add v142 toolset to VS 2022 images

### ISSUE THREAD

**Issue by sylveon** [actions/virtual-environments#4341]
### Tool name

MSVC v142 - VS 2019 C++ build tools

### Tool license

VS License

### Add or update?

- [X] Add
- [ ] Update

### Desired version

14.29 - 16.11

### Brief description of tool

The VS 2019 build tools for VS 2022, available in the VS installer. Required to build certain projects that have parts which cannot use VS 2022 due to compatibility issues. All 4 architectures and their respective Spectre-mitigated libs should be added (x86/x64/ARM/ARM64).

### Provide a basic test case to validate the tool's functionality.

```bash
vcvarsall.bat -vcvars_ver=14.29
```

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Are you willing to submit a PR?

Maybe? Depends how complex it is to do.

**Comment by miketimofeev** [comment]
@sylveon the new image with pre-installed components is deployed.
I'm going to close the issue. Please feel free to contact us if you have any concerns.
Thank you!

**Comment by jaholme** [comment]
@miketimofeev was this the correct deployment? I'm using a more recent windows-2022 image but I'm still seeing compiler errors about missing v142 toolset.  Building locally with Visual Studio 2022 and V142 tools installed the solution works.

##[error]C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Microsoft\VC\v170\Microsoft.CppBuild.targets(436,5): Error MSB8020: The build tools for Visual Studio 2019 (Platform Toolset = 'v142') cannot be found. To build using the v142 build tools, please install Visual Studio 2019 build tools.  Alternatively, you may upgrade to the current Visual Studio tools by selecting the Project menu or right-click the solution, and then selecting "Retarget solution".

**Comment by sylveon** [comment]
Works on the windows-2022 image for me.

Are you building UWP projects? The "v142 UWP tools" component (which is different from the v142 build toolset) being missing will trigger this error on UWP projects. I would suggest filling a request for this to be added to the image.

![image](https://user-images.githubusercontent.com/6440374/150565937-dd0ace7c-71f8-4a47-bacf-b2dd8c241b7e.png)

**Comment by jaholme** [comment]
@sylveon you're right I am building UWP components so that must be what is missing.  I'll get the request filed.

**Comment by wizlee** [comment]
Is it possible to also include an older version of v142, i.e. 14.28.29333 ?

**Comment by sylveon** [comment]
I believe that's possible, yes, but you would need to create another issue to request it

**Comment by wizlee** [comment]
> I believe that's possible, yes, but you would need to create another issue to request it

Thanks! I think I might have mistaken this to be a feature request for the visual studio installer. When logging the issue to request this only I noticed that this is more for github actions and virtual environment!
