### ISSUE TITLE
Add ARM64 Spectre mitigated libs to VS 2022

### ISSUE THREAD

**Issue by sylveon** [actions/virtual-environments#4342]
### Tool name

MSVC v143 - VS 2022 C++ ARM64 Spectre-mitigated libs

### Tool license

VS License

### Add or update?

- [X] Add
- [ ] Update

### Desired version

Latest

### Brief description of tool

The Spectre-mitigated C++ runtime libraries for ARM64. Required to build ARM64 code with /Qspectre on.

### Provide a basic test case to validate the tool's functionality.

```bash
vcvarsall.bat x64_arm64 spectre
```

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Are you willing to submit a PR?

Maybe? Depends how complex it is to do.

**Comment by miketimofeev** [comment]
@sylveon the new image with pre-installed components is deployed.
I'm going to close the issue. Please feel free to contact us if you have any concerns.
Thank you!
