### ISSUE TITLE
[All OSs] Node.js version 10 will be removed from the images on November, 15

### ISSUE THREAD

**Issue by miketimofeev** [actions/virtual-environments#4356]
### Breaking changes

The pre-cached Node.js version 10 will be removed from all operating systems.

### Target date

November 15, 2021

### The motivation for the changes

Node.js 16 has moved to Active LTS status and is ready for general use. According to our [Software and image guidelines
](https://github.com/actions/virtual-environments/blob/main/docs/software-and-images-guidelines.md) we support 3 latest LTS versions of Node.js, which are 12, 14 & 16 at the moment.

### Possible impact

If your project depends on a pre-installed Node version 10 it can be broken.

### Virtual environments affected

- [X] Ubuntu 18.04
- [X] Ubuntu 20.04
- [X] macOS 10.15
- [X] macOS 11
- [X] Windows Server 2016
- [X] Windows Server 2019
- [X] Windows Server 2022

### Mitigation ways

Consider using the following actions\tasks as they can install any Node.js version in runtime:
- [GH Actions] https://github.com/actions/setup-node
- [Azure DevOps] [Node.js Tool Installer task](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/tool/node-js?view=azure-devops)

**Comment by mikhailkoliada** [comment]
nodejs 10 should have gone by now.
