### ISSUE TITLE
[Ubuntu] Node:10 docker images will be removed on November, 15

### ISSUE THREAD

**Issue by miketimofeev** [actions/virtual-environments#4357]
### Breaking changes

We are going to remove `node:10` and `node:10-alpine` docker images from the list of pre-cached images on VM.

### Target date

November 15, 2021

### The motivation for the changes

Node.js 16 has moved to Active LTS status and is ready for general use. According to our [Software and image guidelines
](https://github.com/actions/virtual-environments/blob/main/docs/software-and-images-guidelines.md) we support not more than 3 latest LTS OS\tool versions docker images, which for Node.js are 12, 14 & 16 at the moment.

### Possible impact

If your builds rely on either `node:10` or `node:10-alpine` docker images they can be slower due to the necessity of pulling the images from the docker hub.

### Virtual environments affected

- [X] Ubuntu 18.04
- [X] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Mitigation ways

Nothing is required — if there is no local image docker will pull it automatically from the docker hub.

**Comment by m7kvqbe1** [comment]
Will you be making `16.x.x` the default node runtime for `ubuntu-latest`?

**Comment by miketimofeev** [comment]
@m7kvqbe1 yes, we will announce it soon.

**Comment by miketimofeev** [comment]
The images were deployed
