### ISSUE TITLE
Access is denied on rename in Windows 

### ISSUE THREAD

**Issue by mosyp** [actions/virtual-environments#4367]
### Description

When rust's `std::fs::rename` (window's `MoveFileEx`) is called then the 
```
Access is denied. (os error 5)
```
is called. 

Discovered in https://github.com/delta-io/delta-rs/runs/4011135260?check_suite_focus=true

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [X] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

```
  Version: 20211018.0
```

### Is it regression?

No, we have the successful build on the same version

### Expected behavior

the rename call works

### Actual behavior

access denied error

### Repro steps

Call `std::fs::rename` (`MoveFileEx`)

**Comment by mosyp** [comment]
It has been "fixed" in https://github.com/delta-io/delta-rs/pull/485 by suing shared lock, so seems like you're assumption regarding race condition might be tru

**Comment by al-cheb** [comment]
I am planning to close as external fix. Feel free to open the thread if you have any concerns.
