### ISSUE TITLE
[all OSs] Selenium server version will be upgraded from 3 to 4 on November, 15

### ISSUE THREAD

**Issue by miketimofeev** [actions/virtual-environments#4376]
### Breaking changes

Selenium server version will be upgraded from 3 to 4 on all available images.

### Target date

November 15, 2021

### The motivation for the changes

We'd like to keep images up-to-date with recent software updates.

### Possible impact

There are a few breaking changes in selenium server 4 thus your builds can be broken after the update. More information about breaking changes can be found on the official changelog https://github.com/SeleniumHQ/selenium/releases/tag/selenium-4.0.0

### Virtual environments affected

- [X] Ubuntu 18.04
- [X] Ubuntu 20.04
- [X] macOS 10.15
- [X] macOS 11
- [X] Windows Server 2016
- [X] Windows Server 2019
- [X] Windows Server 2022

### Mitigation ways

Revert to selenium 3 using the following snippets:
**macOS**
```bash
cd $(brew --repo homebrew/core)
git checkout dc37198
brew install selenium-server-standalone
```
**Windows**
```pwsh
$seleniumDirectory = "C:\selenium\"
Remove-Item -Path $seleniumDirectory\* -Recurse -Force
$seleniumFileName = "selenium-server-standalone.jar"
$seleniumDownloadUrl = "https://github.com/SeleniumHQ/selenium/releases/download/selenium-3.141.59/selenium-server-standalone-3.141.59.jar"
Start-DownloadWithRetry -Url $seleniumDownloadUrl -Name $seleniumFileName -DownloadPath $seleniumDirectory
```
**Ubuntu**
```bash
SELENIUM_JAR_NAME="selenium-server-standalone.jar"
SELENIUM_DOWNLOAD_URL="https://github.com/SeleniumHQ/selenium/releases/download/selenium-3.141.59/selenium-server-standalone-3.141.59.jar"
SELENIUM_JAR_PATH="/usr/share/java"
rm $SELENIUM_JAR_PATH/selenium-server*
curl $SELENIUM_DOWNLOAD_URL -sL -o "$SELENIUM_JAR_PATH/$SELENIUM_JAR_NAME"
```

**Comment by dibir-magomedsaygitov** [comment]
All PR's ([macOS](https://github.com/actions/virtual-environments/pull/4472). [Windows](https://github.com/actions/virtual-environments/pull/4473) and [Ubuntu](https://github.com/actions/virtual-environments/pull/4472)) were merged.

**Comment by dibir-magomedsaygitov** [comment]
Selenium was updated up to 4.* version across all the images. Closing this issue.

**Comment by nanish94** [comment]
main

**Comment by nanish94** [comment]
SELENIUM_JAR_NAME= " Selenium-server-standalone.jar " 
SELENIUM_DOWNLOAD_URL= " https://github.com/SeleniumHQ/selenium/releases/download/selenium-3.141.59/selenium-server-standalone-3.141.59.jar " 
SELENIUM_JAR_PATH " /usr/share/java " 
rm $SELENIUM_JAR_PATH /selenium-server * 
curl $SELENIUM_DOWNLOAD_URL -sL -o " $SELENIUM_JAR_PATH / $SELENIUM_JAR_NAME "

**Comment by nanish94** [comment]
$SeleniumDirectory  =  " C:\Selenium\ "
 Remove-Item  - Path $SeleniumDirectory \ *  - Recurse - Force
 $seleniumFileName  =  " Selenium-server-standalone.jar "
 $seleniumDownloadUrl  =  " https://github.com/SeleniumHQ/selenium /releases/download/Selenium-3.141.59/selenium-server-standalone-3.141.59.jar "
 Start-DownloadWithRetry  - URL $seleniumDownloadUrl  - Ad $seleniumDosyaAdı  - İndirme Yolu $seleniumDirectory

**Comment by nanish94** [comment]
#4050 comment

**Comment by nanish94** [comment]
[tüm işletim sistemleri] Selenium sunucu sürümü 3'ten 4'e yükseltilecek, 15 Kasım #4376
