### ISSUE TITLE
ANDROID_NDK_LATEST_HOME environment variable is missing in ubuntu-18.04

### ISSUE THREAD

**Issue by leleliu008** [actions/virtual-environments#4383]
### Description

`ANDROID_NDK_LATEST_HOME` environment variable is missing in `ubuntu-18.04`, it exits in `ubuntu-20.04` `macos-11` `macos-10.15`

### Virtual environments affected

- [X] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

https://github.com/leleliu008/ndk-pkg-formula-repository/runs/4040946356?check_suite_focus=true

### Repro steps

https://github.com/leleliu008/ndk-pkg-formula-repository/runs/4040946356?check_suite_focus=true

**Comment by dibir-magomedsaygitov** [comment]
Hello @leleliu008. Thank you for your report. We will take a look.

**Comment by dibir-magomedsaygitov** [comment]
Hello @leleliu008. `ANDROID_NDK_LATEST_HOME` env variable was added in scope of this PR. Changes should be delivered with the next week's deployment. I'll post an update message.

**Comment by dibir-magomedsaygitov** [comment]
Hello @leleliu008. `ANDROID_NDK_LATEST_HOME` env var should be available on Ubuntu 18 image. I'm going to close this issue. Feel free to contact us in case of any questions.
