### ISSUE TITLE
,##[error]The remote provider was unable to process the request.

### ISSUE THREAD

**Issue by Sushma-tiwari** [actions/virtual-environments#4390]
### Description

We have set up CI/CD deployment in azure and working from past 2 year with it.
Now whenever release using CI /CD getting error like remote provider was unable to process the request.
please check to snap : 
[https://prnt.sc/1y1xjvm](url)

Getting this error from past 7 days :
##[warning]An image label with the label ubuntu-16.04 does not exist.
,##[error]The remote provider was unable to process the request.

Check error snap :
[https://prnt.sc/1y1xped](url)

Thanks,
Sushma Tiwari

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

[https://prnt.sc/1y1xjvm](url)

### Repro steps

We have set up CI/CD deployment in azure and working from past 2 year with it.
Now whenever release using CI /CD getting error like remote provider was unable to process the request.
please check to snap : 
[https://prnt.sc/1y1xjvm](url)

**Comment by dibir-magomedsaygitov** [comment]
Hello @Sushma-tiwari. Thank you for your report. Could you please provide minimal repro steps with full description.

**Comment by miketimofeev** [comment]
@Sushma-tiwari please follow advice from this issue https://github.com/actions/virtual-environments/issues/3287

**Comment by miketimofeev** [comment]
I'm going to close the issue, feel free to contact us if you have any concerns.
Thank you!
