### ISSUE TITLE
Unable to Install Prereqs on an Ubuntu 20.04.3 VM in vSphere using the scripts provided

### ISSUE THREAD

**Issue by vesubramanian** [actions/virtual-environments#4391]
### Description

On my Ubuntu 20.04.3 VM, I installed Packer 1.7.7. My vSphere version is 6.7.0.50000. I am using the [ubuntu2004.json](https://github.com/actions/virtual-environments/blob/main/images/linux/ubuntu2004.json) and modified the builders section for provisioning a VM in vSphere and kept the provisioners section exactly the same. When I run the packer build, I am running to multiple issues, during the execution of provisioners section.
1. The Image Folder name is "/imagegeneration". For me, it works only without the slash.
2.  In configure-environment.sh, it throws an error saying "can't find /etc/waagent.conf". So, I need to install the walinuxagent as part of my provisioners.
3. I am running into an error " The specified module 'imagegeneration/helpers/Tests.Helpers.psm1' was not loaded because no valid module file was found in any module directory." during the execution of Install-PowershellModules.ps1.

Are these scripts supposed to be run from a Windows machine?
Are these scripts targeted only for Azure VM image?

Please help.

### Virtual environments affected

- [ ] Ubuntu 18.04
- [X] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Virtual Environment -> Linux -> 20.04

### Repro steps

On my Ubuntu 20.04.3 VM, I installed Packer 1.7.7. My vSphere version is 6.7.0.50000. I am using the [ubuntu2004.json](https://github.com/actions/virtual-environments/blob/main/images/linux/ubuntu2004.json) and modified the builders section for provisioning a VM in vSphere and kept the provisioners section exactly the same. When I run the packer build, I am running to multiple issues, during the execution of provisioners section.
1. The Image Folder name is "/imagegeneration". For me, it works only without the slash.
2.  In configure-environment.sh, it throws an error saying "can't find /etc/waagent.conf". So, I need to install the walinuxagent as part of my provisioners.
3. I am running into an error " The specified module 'imagegeneration/helpers/Tests.Helpers.psm1' was not loaded because no valid module file was found in any module directory." during the execution of Install-PowershellModules.ps1.

**Comment by dibir-magomedsaygitov** [comment]
Hello @vesubramanian. Thank you for your report. We will take a look.

**Comment by dibir-magomedsaygitov** [comment]
Hello @vesubramanian. Your setup won't work as we don't have support for vSphere. If you want to build the image in Azure, you should follow [this guideline](https://github.com/actions/virtual-environments/blob/main/docs/create-image-and-azure-resources.md). I'm going to close this issue. Feel free to contact us in case of any questions.

**Comment by vesubramanian** [comment]
So, these scripts are targeted only for Azure VM Image? Please confirm so that I can inform the relevant people in my organization. Also, just curious. From packer, I am able to provision the Ubuntu 20.04 VM in vSphere. Aren't these scripts supposed to run on Ubuntu 20.04.3 irrespective of whether the VM is in vSphere or Azure? I am just trying to understand the exact issue. Please help me understand.

**Comment by dibir-magomedsaygitov** [comment]
@vesubramanian yes, we support only Azure.
