### ISSUE TITLE
Add `docker` to mac images

### ISSUE THREAD

**Issue by scbedd** [actions/virtual-environments#4399]
### Tool name

docker

### Tool license

Uncertain what our licensing issue is for Windows/Linux version. Would be the same on Mac.

### Add or update?

- [X] Add
- [ ] Update

### Desired version

latest

### Brief description of tool

I don't think I need to tell you folks what `docker` is. I'd be willing to put money on the fact that you know more about it than I do :) 

That being said, right now, it comes pre-installed on the `Windows` and `Linux` images. What can I do to get a similar experience on `mac`? I'm willing to listen to suggestions here 👍 

### URL for tool's homepage

https://www.docker.com/

### Provide a basic test case to validate the tool's functionality.

```bash
docker container create -p 5001:5001 -p 5000:5000 --name ambitious_azsdk_test_proxy azsdkengsys.azurecr.io/engsys/testproxy-lin:1108695
docker container start ambitious_azsdk_test_proxy
```

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [X] macOS 10.15
- [X] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Can this tool be installed during the build?

```bash
To my knowledge, no. Whenever I have attempted installation of `docker` via any CLI, I need to restart the agent to see an affect.

This is why I want to say it's seemingly an agent level change.
```

### Tool installation time in runtime

~5 minutes, mostly download time.

### Are you willing to submit a PR?

Totally willing to help. Will just need some pointers on testing a macos specific change :)

**Comment by dibir-magomedsaygitov** [comment]
Hello @scbedd. Thank you for your request. We will take a look.

**Comment by miketimofeev** [comment]
Hi @scbedd!
Unfortunately, we can not add docker due to license restrictions. Please take a look at this issue and the advice given there https://github.com/actions/virtual-environments/issues/2150
I'm going to close this issue. Please feel free to contact us if you have any concerns.
Thank you!
