### ISSUE TITLE
Update Az module to 3.5.0

### ISSUE THREAD

**Issue by bgelens** [actions/virtual-environments#440]
**Tool information**
- Tool name: Az (PowerShell Module)
- Add or update? Update
- Desired version: 3.5.0

- Approximate size: 
- If this is an add request:
  - Brief description of tool: Modules to interact with Azure used by Azure PowerShell task
  - URL for tool's homepage: https://github.com/azure/azure-powershell

**Area for Triage**:

**Question, Bug, or Feature?**:

**Virtual environments affected**
- [ ] macOS 10.15
- [x] Ubuntu 16.04 LTS
- [x] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Can this tool be installed during the build?**

```powershell
Install-Module Az -Repository PSGallery -RequiredVersion '3.5.0'
```

This will take a couple of minutes and is repeated almost every build as new functionality is included (management / tenant scope deployment of ARM templates) and some module dependencies like Az.RecoveryServices (installed as dependency) are updated to a version that Microsoft has send information on to update

**Are you willing to submit a PR?**
Yes #441

**Comment by bgelens** [comment]
For Windows, an external blob needs to be updated that is referenced here: images/win/scripts/Installers/Install-AzureModules.ps1 . Right now this blob is downloaded https://vstsagenttools.blob.core.windows.net/tools/azurepowershellmodules/AzPSModules.M163.20191211.17769.zip. I don't know how to figure out a newer version

**Comment by maxim-lobanov** [comment]
@bgelens , thank you for Linux contribution!
I will assign work item to me and will take care about updating Azure Modules on Windows.
Currently, we are discussing getting rid of custom blob and switch to `Install-Module` approach so it can take a bit more time. Sorry for inconvenience.

**Comment by AtOMiCNebula** [comment]
There's been discussion over in #390 about `Install-AzureModules.ps1` being problematic for reliability on Windows, so it's good to hear that there might be bigger plans afoot.  Any chance we can get some comment from the team on that thread too, if we don't have it already? :smile:

**Comment by maxim-lobanov** [comment]
Both Windows and Ubuntu images were deployed and Az 3.5.0 is there. I am closing the issue. Feel free to reopen if any issues
