### ISSUE TITLE
Python 3.10 32bit missing in cloud machines

### ISSUE THREAD

**Issue by FrancescElies** [actions/virtual-environments#4400]
### Description

All python versions have 32 bit except 3.10, see [here](https://github.com/actions/virtual-environments/blob/main/images/win/Windows2019-Readme.md#python).

We still have a private project where we test a 32 bit dll on windows, this means if we want to upgrade python we can't use the cloud without installing python 3.10 32 its ourselves. 

Before going into the details on _why we don't upgrade to 64bit_, let's say that we test a dll that will run on embedded 32bit arch on windows via python.

Furthermore we need other packages too, like numpy.

Numpy seems not to provide any 32 wheels anymore, but they seem to have tested things on 32bit arch for [python3.9-32bits](https://github.com/numpy/numpy/blob/main/azure-pipelines.yml#L247-L251), but they do not provide wheels for python3.10-32bit. Might be the reason for them to drop support py310-32bit because python3.10-32bit on azure cloud is missing?

Of course there are workarounds to all this, see [stackoverflow question](https://stackoverflow.com/questions/69805894/will-numpy-wheels-for-python-3-10-32-bits-be-available/69806586#69806586) but we would be happy if those packages

This seems to have been an [intentional decision](https://github.com/actions/virtual-environments/issues/4226), but could we reconsider? Python provides a [32bit installer](https://www.python.org/downloads/release/python-3100/) 😄

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [X] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

[virtual-environments/Windows2019-Readme.md at main · actions/virtual-environments](https://github.com/actions/virtual-environments/blob/main/images/win/Windows2019-Readme.md#python)

### Repro steps

Any job, has no py310-32bit

**Comment by miketimofeev** [comment]
Hi @FrancescElies!
Yes, this makes sense to add Python x86 as this is not the first time it is asked for. We will also submit a feature request to the build task team to support downloading and installing python in runtime in AzDO using https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/tool/use-python-version?view=azure-devops task

**Comment by miketimofeev** [comment]
@FrancescElies the changes are merged and will be deployed next week.

**Comment by FrancescElies** [comment]
Closing 😄

**Comment by miketimofeev** [comment]
@FrancescElies I would prefer to leave this open until the images are deployed if you don't mind

**Comment by miketimofeev** [comment]
@FrancescElies the images have been deployed!
