### ISSUE TITLE
Xcode 13, iOS 15 sim: The test runner encountered an error (Failed to establish communication with the test runner).

### ISSUE THREAD

**Issue by JolandaArends** [actions/virtual-environments#4402]
### Description

We've updated our Github workflow (where we run unit and snapshot tests), to Xcode 13.0 and simulator 15.0.
This workflow worked with Xcode 12.5.1 and simulator 14.5, but with the updated version numbers we get the following error:
_The test runner encountered an error (Failed to establish communication with the test runner)._

We can't seem to figure out why we get this error or how to fix it and would really appreciate some help.

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [X] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Version: 20211018.1

Link to PR with failed build.
https://github.com/restocks-net/app-ios/pull/389

### Is it regression?

Version: 20211018.1, Link to PR with successful build: https://github.com/restocks-net/app-ios/pull/388

### Expected behavior

We expected our unit tests job to run.

### Actual behavior

Instead it fails with the following error: 
_The test runner encountered an error (Failed to establish communication with the test runner)._

### Repro steps

Updated our existing workflow with:
1. Xcode 12.5.1 to Xcode 13.0
2. Simulator 14.5 to 15.0

**Comment by dibir-magomedsaygitov** [comment]
Hello @JolandaArends. Thank you for your report. Could you please create public repo with reprosteps as your repo is private.

**Comment by JolandaArends** [comment]
As you can see, we haven't made much changes, so we're a bit hesitant in setting up a new public repo to reproduce it:
yml file before: [before_tests.txt](https://github.com/actions/virtual-environments/files/7459801/before_tests.txt)
yml file after: [after_tests.txt](https://github.com/actions/virtual-environments/files/7459803/after_tests.txt)

With this information, do you still think we need to set up a new public repo to reproduce it?

**Comment by dibir-magomedsaygitov** [comment]
@JolandaArends Thank you for the provided information. Public repo with sample project would be more helpful.

**Comment by JolandaArends** [comment]
@dibir-magomedsaygitov 
I've set-up a sample (simplified) project in a public repo with the same structure we use in our own project.

This is the Xcode 12 pipeline that's running fine: https://github.com/restocks-net/app-ios-test/pull/1
This is the Xcode 13 pipeline with the issue we have: https://github.com/restocks-net/app-ios-test/pull/2

Hope this helps.

**Comment by dibir-magomedsaygitov** [comment]
@JolandaArends Thank you for the provided details. We will take a look.

**Comment by vsafonkin** [comment]
Hi @JolandaArends, could you try to check your builds again? I have the successful build in my fork of your sample at the moment.

**Comment by JolandaArends** [comment]
@vsafonkin Good morning!
I was just checking the sample project this morning and noticed that the pipeline is now running correctly. 
Took some time to check it in our real project as well, just to be sure, and there the tests are running again too!
Very happy with that, because that means we can upgrade to Xcode 13 now.

So I was just about to ask if there were any changes made and then I saw your message. :) 
I don't know what you did, but thanks a lot!

**Comment by JolandaArends** [comment]
If you are fine with it, I can close the issue now I think?

**Comment by vsafonkin** [comment]
@JolandaArends, I think yes, looks like some simulators was not installed correctly on the previous runner version.

**Comment by JolandaArends** [comment]
Allright, then I'll close the issue. Thanks a lot for looking into it and fixing it!
