### ISSUE TITLE
Add .NET 6 SDK

### ISSUE THREAD

**Issue by akyamada-ms** [actions/virtual-environments#4424]
### Tool name

.NET 6 SDK

### Tool license

N/A

### Add or update?

- [X] Add
- [ ] Update

### Desired version

N/A

### Brief description of tool

I’m support engineer in Japan. One of my customers is using Ubuntu latest OS image for Microsoft-hosted agents in Azure DevOps Services. Does not have .NET 6 installed in Ubuntu latest OS image, so he adds the following definition to Pipeline and installs it every time.

steps:
- task: UseDotNet@2
displayName: 'Use .NET Core sdk'
inputs:
packageType: sdk
version: 6.0.100-rc.2.21505.57
installationPath: $(Agent.ToolsDirectory)/dotnet

I think you already have a plan, but I would like to request to include .NET 6 in the OS image.

Also, I would appreciate it if you could let me know when the OS image will include .NET 6 and if there is any publicly available information about future plans.

### URL for tool's homepage

https://github.com/dotnet/core/tree/main/release-notes/6.0

### Virtual environments affected

- [X] Ubuntu 18.04
- [X] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Can this tool be installed during the build?

```bash
steps:
- task: UseDotNet@2
displayName: 'Use .NET Core sdk'
inputs:
packageType: sdk
version: 6.0.100-rc.2.21505.57
installationPath: $(Agent.ToolsDirectory)/dotnet
```

### Tool installation time in runtime

N/A

**Comment by al-cheb** [comment]
Hey, @akyamada-ms 
.NET 6 will launch at .NET Conf November 9-11(https://devblogs.microsoft.com/dotnet/announcing-net-6-release-candidate-2/) and take 1 or 2 weeks to new rollout.

**Comment by miketimofeev** [comment]
Hi @akyamada-ms!
How long does it take to install .Net 6 in runtime? We are thinking of changing the policy and do not pre-install .NET on the images due to maintenance and security concerns.

**Comment by akyamada-ms** [comment]
Thank you, @al-cheb @miketimofeev 
I tried it five times with ubuntu-latest and it took an average of 8.6 seconds. It looks like there is no problem with the Pipeline execution time.

**Comment by epvanhouten** [comment]
@miketimofeev is the guidance going forward to rely on UseDotNet@2 to get dotnet onto the agent?

**Comment by miketimofeev** [comment]
@epvanhouten using setup-* actions or Use* tasks is a recommended way to install the desired version.

**Comment by mikeblakeuk** [comment]
Make sure you force the base path
https://github.com/MicrosoftDocs/azure-devops-docs/issues/9690

**Comment by AraHaan** [comment]
.NET 6 has been out today (a day early), I can manually install it today however when invoking an .NET global tool it will fail on me saying that the ``Microsoft.NETCore.App`` version 6.0.0 was not found in ``/usr/share/dotnet/shared/``.

**Comment by AraHaan** [comment]
Ok I found a workaround for this:

use the following locally and commit these to repository:

```
dotnet new tool-manifest
```
from repository root.

Then install all the tools you need without ``-g`` or ``--global`` in the command so they get added to that manifest.

Then in the github actions workflows run ``dotnet tool restore`` and then run the commands like normal and they will run exactly the way they was made to even if they use the .NET 6 runtime itself.

**Comment by mikeblakeuk** [comment]
You are hitting the bug I had
https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/1906
I'm just going to wait this time.
Note; .net 6.0 is on the windows-2022 builds, just not ubuntu yet

**Comment by zcsizmadia** [comment]
@AraHaan 

This will install the latest .NET 3.1, 5.0 and 6.0 in the github action. Adding this will make the action future proof, in case Github decides to remove the dotnet SKDs from the latest imgages. @miketimofeev mentioned earlier, that it is under consideration. Btw each SDK install takes 6-7s.

```
    # Install .NET SDKs
    - name: Setup .NET Core 3.1
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Setup .NET 5.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Setup .NET 6.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
```

**Comment by LanceMcCarthy** [comment]
Just to add, this request is more than just installing NET6 RTM to the runner. We also need `VS 2022 Current` and it's NET6.0 based tooling.

**Comment by miketimofeev** [comment]
@LanceMcCarthy the VS2022 stable image with .NET 6.0 is currently rolling out and will be generally available tomorrow.

**Comment by al-cheb** [comment]
@LanceMcCarthy , Windows Server 2022 with VS2022 has been deployed.

**Comment by AraHaan** [comment]
Actually I replaced the setup-dotnet github action, but I figured out a solution to the .NET Core global tools issue.

**Comment by miketimofeev** [comment]
As we decided not to add .NET for all the images (at least for now) I'm going to close the issue.
Please feel free to contact us if you have any concerns.
Thank you!

**Comment by mikeblakeuk** [comment]
When will the **Ubuntu 20.04** DevOps agent have .NET 6.0 pre installed? (in the same style that it has 5.0)

**Comment by KVROHITH098** [comment]
Yes it we are working on this one as of now

**Comment by miketimofeev** [comment]
@mikeblakeuk please consider using the task https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/tool/dotnet-core-tool-installer?view=azure-devops 
Please provide a reason if it's not possible for you.

**Comment by AtOMiCNebula** [comment]
> As we decided not to add .NET for all the images (at least for now) I'm going to close the issue. Please feel free to contact us if you have any concerns. Thank you!

@miketimofeev, can you elaborate on how this decision was reached?  The answer isn't obvious to me (and a few others, given the downvotes on your comment).  .NET 6 _is_ ultimately getting installed in the windows-2022 images, likely from the VS2022 installation process (it's not listed in the dotnet toolset section for either -2019 or -2022).

What will happen to the -2019 image when .NET 5 reaches EoL in May 2022, or when .NET Core 3.1 reaches EoL in December 2022?

**Comment by AraHaan** [comment]
I think they uninstall the EOL versions of .NET.

**Comment by AtOMiCNebula** [comment]
Will we have no pre-installed SDKs then?  Is that a happy position?  It feels inconsistent to me, especially if getting .NET 6 onto the windows-2022 agents is a side-effect and not necessarily an intended effect.

**Comment by AraHaan** [comment]
In the mean time I would suggest using the github action I made and follow the steps I posted above using my workflow as an example. This should work 100% of all needed usage of the .NET 6 SDK.

**Comment by Meertman** [comment]
The proposed work-around of specifying the .NET SDK version to use, does not work when executing unit and integration tests using multiple target frameworks. (For example when building a library that targets ASP.NET Core 3.1, ASP.NET 5 and ASP.NET 6)

This will ensure that the tests for .NET Core 3.1 and .NET 5 fail with the following message:

**ASP.NET Core 3.1:**
 The framework 'Microsoft.AspNetCore.App', version '3.1.0' (x64) was not found.
  - The following frameworks were found:
      6.0.0 at [/opt/hostedtoolcache/dotnet/shared/Microsoft.AspNetCore.App]

**ASP.NET 5**
The framework 'Microsoft.AspNetCore.App', version '5.0.0' (x64) was not found.
  - The following frameworks were found:
      6.0.0 at [/opt/hostedtoolcache/dotnet/shared/Microsoft.AspNetCore.App]

**Comment by AraHaan** [comment]
> The proposed work-around of specifying the .NET SDK version to use, does not work when executing unit and integration tests using multiple target frameworks. (For example when building a library that targets ASP.NET Core 3.1, ASP.NET 5 and ASP.NET 6)
> 
> This will ensure that the tests for .NET Core 3.1 and .NET 5 fail with the following message:
> 
> **ASP.NET Core 3.1:** The framework 'Microsoft.AspNetCore.App', version '3.1.0' (x64) was not found.
> 
>     * The following frameworks were found:
>       6.0.0 at [/opt/hostedtoolcache/dotnet/shared/Microsoft.AspNetCore.App]
> 
> 
> **ASP.NET 5** The framework 'Microsoft.AspNetCore.App', version '5.0.0' (x64) was not found.
> 
>     * The following frameworks were found:
>       6.0.0 at [/opt/hostedtoolcache/dotnet/shared/Microsoft.AspNetCore.App]

That is because when you specified .NET 6 you did not install the other SDKs before that in order to install their runtimes for those other TFMs.

**Comment by Meertman** [comment]
@AraHaan, that is correct, so the work-around does not work in this case, or am I missing something?

Or can you specify multiple SDK's?

**Comment by maxkoshevoi** [comment]
> Or can you specify multiple SDK's?

Just execute setup-... task multiple times with different SDK versions

**Comment by zcsizmadia** [comment]
@Meertman https://github.com/actions/setup-dotnet/pull/240 just got merged. It got much easier to deploy multiple frameworks. Check https://github.com/actions/setup-dotnet for more examples:

```
steps:
- name: Setup dotnet
- uses: actions/checkout@v2
-  uses: actions/setup-dotnet@v1
  with:
    dotnet-version: | 
      3.1.x
      5.0.x
- run: dotnet build <my project>
```

**Comment by AraHaan** [comment]
I guess I could update my setup-latest-dotnet action with the ability to specify multiple .NET versions as well.

**Comment by GGG-KILLER** [comment]
> @Meertman [actions/setup-dotnet#240](https://github.com/actions/setup-dotnet/pull/240) just got merged. It got much easier to deploy multiple frameworks. Check https://github.com/actions/setup-dotnet for more examples:
> 
> ```
> steps:
> - name: Setup dotnet
> - uses: actions/checkout@v2
> - uses: actions/setup-dotnet@v1
>   with:
>     dotnet-version: | 
>       3.1.x
>       5.0.x
>       6.0.x
> - run: dotnet build <my project>
> ```

Just a reminder that the `v1` tag hasn't been updated to it yet, so the snippet you posted isn't working yet

**Comment by LanceMcCarthy** [comment]
Indeed, the latest published version (v1.8.3) was released on Sept 14th 2021. Additionally, I do not see any pending builds in the release workflow https://github.com/actions/setup-dotnet/actions/workflows/release-new-action-version.yml 

So, the current readme is a bit misleading.

**Comment by GGG-KILLER** [comment]
> FYI - `setup-dotnet` v1.9 is now available https://github.com/actions/setup-dotnet/releases/tag/v1.9.0.
> 
> You can replace your consecutive individual dotnet-install steps (or custom install-dotnet.sh scripts), with the following:
> 
> ```
> - uses: actions/setup-dotnet@v1
>   with:
>     dotnet-version: | 
>       3.1.x
>       5.0.x
>       6.0.x
> ```

The [workflow run](https://github.com/actions/setup-dotnet/actions/runs/1498303938) to update the `v1` tag is still pending, so if you want to use this, you'll have to use `actions/setup-dotnet@v1.9.0` until the workflow has finished running

**Comment by mikeblakeuk** [comment]
What should we use for Azure DevOps when using latest ubuntu?

**Comment by LanceMcCarthy** [comment]
> What should we use for Azure DevOps when using latest ubuntu?

@mikeblakeuk In ADO, you can add a step for each version of .NET you want installed. For example, here I am adding 6.0 at the top of my stack:

![image](https://user-images.githubusercontent.com/3520532/144287862-f4b25939-61a4-4f8a-944b-548c546169fb.png)

If you need more than one, add additional steps for each version you need.

**Comment by weshaggard** [comment]
>please consider using the task https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/tool/dotnet-core-tool-installer?view=azure-devops
Please provide a reason if it's not possible for you.

While we can use the task it is far less reliable then having it already on the agent. We just switched to .NET 6.0 SDK a few days ago and already seeing random issues like:

```
gzip: stdin: unexpected end of file
/usr/bin/tar: Unexpected EOF in archive
/usr/bin/tar: Unexpected EOF in archive
/usr/bin/tar: Error is not recoverable: exiting now
##[error]Failed while installing version: 6.0.100 at path: /opt/hostedtoolcache/dotnet with error: Failed while extracting downloaded package with error: Error: The process '/usr/bin/tar' failed with exit code 2
```

**Comment by LanceMcCarthy** [comment]
@weshaggard That end of file error is something that happens when an archive is empty or corrupt (i.e. a bad download)

You'll want to use the "Use .NET" Task instead of manually installing stuff. Mainly, it's more reliable, but much neater 😎 It will detect the OS, properly install it in the correct location and will update PATH.

In GitHub Actions

```yaml
- uses: actions/setup-dotnet@v1
  with:
    dotnet-version: '6.0.x'
```

In Azure DevOps
```
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '6.0.x'
```

If you're still using ADO Classic pipeline, see my previous reply for a screenshot.

**Comment by weshaggard** [comment]
We are using the DevOps task I just didn't post the full log:
```
Starting: Use .NET Core SDK
==============================================================================
Task         : Use .NET Core
Description  : Acquires a specific version of the .NET Core SDK from the internet or the local cache and adds it to the PATH. Use this task to change the version of .NET Core used in subsequent tasks. Additionally provides proxy support.
Version      : 2.195.0
Author       : Microsoft Corporation
Help         : https://aka.ms/AA4xgy0
==============================================================================
get-os-distro: Error: Distribution specific OS name and version could not be detected: UName = Linux
Found version 6.0.100 in channel 6.0 for user specified version spec: 6.0.100
Getting URL to download .NET Core sdk version: 6.0.100.
Detecting OS platform to find correct download package for the OS.
/mnt/vss/_work/_tasks/UseDotNet_b0ce7256-7898-45d3-9cb5-176b752bfea6/2.195.0/externals/get-os-distro.sh
Primary:linux-x64
Legacy:-x64
Detected platform (Primary): linux-x64
Detected platform (Legacy): -x64
Version 6.0.100 was not found in cache.
Downloading: https://download.visualstudio.microsoft.com/download/pr/17b6759f-1af0-41bc-ab12-209ba0377779/e8d02195dbf1434b940e0f05ae086453/dotnet-sdk-6.0.100-linux-x64.tar.gz
Extracting downloaded package /mnt/vss/_work/_temp/0d61359d-0e06-4967-81ce-813ed3b62856.
Extracting archive
/usr/bin/tar xC /mnt/vss/_work/_temp/72b79f24-d279-4669-a01b-d01991e9f316 -f /mnt/vss/_work/_temp/0d61359d-0e06-4967-81ce-813ed3b62856

gzip: stdin: unexpected end of file
/usr/bin/tar: Unexpected EOF in archive
/usr/bin/tar: Unexpected EOF in archive
/usr/bin/tar: Error is not recoverable: exiting now
##[error]Failed while installing version: 6.0.100 at path: /opt/hostedtoolcache/dotnet with error: Failed while extracting downloaded package with error: Error: The process '/usr/bin/tar' failed with exit code 2
Finishing: Use .NET Core SDK
```

**Comment by lindexi** [comment]
Any update?

**Comment by jetersen** [comment]
@miketimofeev any chance this can be reconsidered? On Windows VM it is at least 30 seconds slower on average when compared to Ubuntu VM for GitHub runner.
Most likely due to network issues reported in #3577

**Comment by AraHaan** [comment]
I am working on something with my github action to do something about this.

I plan to do stuff like allowing to pass in a list of .NET versions to install.

However it would be nice to implement caching for those who specify explicit versions and does not wildcard a specific version (for the .NET install scripts to install).

**Comment by miketimofeev** [comment]
@jetersen we will discuss this internally. There is a chance we will pre-install only the latest available 6.* version on the image

**Comment by AraHaan** [comment]
So basically there is a chance that it may be ``6.0.102`` or ``6.0.200``.

**Comment by jchannon** [comment]
I've just hit this issue having moved all our code to .NET 6, I have a separate task that uses `ubuntu-latest` only to find that MS have decided not to include .NET 6 and now our deployment is broken. (https://github.com/actions/virtual-environments/issues/4424#issuecomment-967012616)

What was the reasoning by not including .NET 6 on ubuntu images, this is nuts!

**Comment by akrock** [comment]
@miketimofeev You posted a month ago that this would be under discussion. How is that discussion coming???

The rest of us out here in the real world are still pretty shocked that the windows hosted agents come with NET 6, and the linux ones do not. So much for an equitable approach for dotnet 5+ ...

The sheer cost in lost engineering time that this questionable decision is going to cause is only going to grow over time as more teams try to adopt NET 6 only to find it doesn't work out of the box if they run linux hosted agents.

**Comment by jetersen** [comment]
🤯 I was not aware of the fact that Windows had .NET 6 installed and the active decision is to NOT install it on ubuntu.

But it clear shown here:
https://github.com/actions/virtual-environments/blob/main/images/win/Windows2022-Readme.md#net-core-sdk

Though seems the script for this is broken.

The toolset is defined here:
https://github.com/actions/virtual-environments/blob/8e0e0d68b96a85314b5e16a6a5896244672a83f6/images/win/toolsets/toolset-2022.json#L281-L286

Seems the powershell script ignores that based on the software report.
https://github.com/actions/virtual-environments/blob/8e0e0d68b96a85314b5e16a6a5896244672a83f6/images/win/scripts/Installers/Install-DotnetSDK.ps1#L91-L100

**Comment by jetersen** [comment]
@miketimofeev 
> We are thinking of changing the policy and do not pre-install .NET on the images due to maintenance and security concerns.

If the argument is security and maintenance why is it installed on Windows machines and not ubuntu/macos images?

Again if the argument is security and maintenance just give us the latest patched .NET LTS (Active) and Current? Much like NodeJS.
For now this would mean:

* .NET 3.1.x LTS (since it is still active) 
* .NET 5.0.x Current
* .NET 6.0.x LTS

according to https://dotnet.microsoft.com/en-us/platform/support/policy/dotnet-core#lifecycle

I think it would be fine to support the lifecycle and for anything else or a if you need a specific patch or minor version of .NET use `setup-dotnet` action.

**Comment by shoter** [comment]
I think it should be listed higher on list of Microsoft priorities to bring it up because in less than 4 months you are dropping support of .NET 5 whereas .NET 6 is not yet fully ready as we see.

Or increase support time for .NET 5 if you are not yet ready for whatever "security" reasons you have.

**Comment by Steve-Glass** [comment]
👋  Hi everyone! I’m Steve, the Product Manager working in the virtual environments domain. We’ve been actively reviewing feedback from the community on this issue and have been internally discussing the addition of the .NET 6 SDK to the Ubuntu image. The community feedback, internal discussions, and review of security and maintenance concerns/requirements have led us to the following solution:

- We will keep the Ubuntu image updated with the latest .NET SDK by default.
- If you would like to use any other version of .NET, the setup/dotnet action should be utilized. 

In regards to ETA, I’ll be working with the team to prioritize software updates and we will communicate via this issue. Please let us know if you have any additional questions and thank you for voicing concerns with our team!

**Comment by jetersen** [comment]
@Steve-Glass Thanks for reaching a decision. Latest SDK is a good compromise which I hope the majority will find acceptable. For my own case that is very true ☺️

**Comment by zcsizmadia** [comment]
> * We will keep the Ubuntu image updated with the latest .NET SDK by default.

@Steve-Glass Is that true for all supported SDKs, right, and not just 6.0? So the latest 3.1 5.0 and 6.0 SDKs would be included.

**Comment by nikolai-frolov** [comment]
Changes have been deployed to production environments.

**Comment by AraHaan** [comment]
I have a better idea for keeping the images up to date:
have the dotnet-install scripts be on the images globally and in the path where actions can invoke them (without having to bundle them in their repository). This would help people like me who bundle them in our repos and then have to worry about forgetting to update the scripts whenever the .NET Foundation updates them.
