### ISSUE TITLE
Azure Devops Microsoft-hosted Ubuntu agent integration tests fail to call Docker Rest Api

### ISSUE THREAD

**Issue by zordark** [actions/virtual-environments#4426]
### Description

We have a problem with Azure pipeline. 
Our pipeline is executed on Microsoft-hosted Ubuntu based agent.
Inside pipeline we are running integration tests, those tests interacts with Docker Rest API to run specific containers (we are using Docker.DotNet for that). Everything works on on-premise hosted build agent (but we are using our own image for that), but doesn't on Microsoft-hosted. All calls to Docker REST API ends with timeout exception. Does Docker engine in Microsoft-hosted Ubuntu build agent contains Docker REST API?

### Virtual environments affected

- [ ] Ubuntu 18.04
- [X] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Virtual Environment
Environment: ubuntu-20.04
Version: 20211101.1

### Repro steps

Run pipeline which will call Docker Rest API

**Comment by al-cheb** [comment]
Hello, @zordark 
Please provide logs of the failed builds and steps to reproduce the issue.

**Comment by mikhailkoliada** [comment]
@zordark Hello!
I am going to close this issue now as we are lacking any repro steps and therefore can't help anyhow.
Please feel free to ping us if you have questions or are ready to share some more info.
