### ISSUE TITLE
Swift installer script no longer works

### ISSUE THREAD

**Issue by JayDoubleu** [actions/virtual-environments#4427]
### Description

```
    azure-arm: Downloading 'https://swift.org/builds/swift--release/ubuntu1804/swift--RELEASE/swift--RELEASE-ubuntu18.04.tar.gz' to '/tmp/swift--RELEASE-ubuntu18.04.tar.gz'...
    azure-arm: Download completed
==> azure-arm:
==> azure-arm: gzip: stdin: not in gzip format
==> azure-arm: tar: Child returned status 1
==> azure-arm: tar: Error is not recoverable: exiting now
==> azure-arm: mv: cannot stat 'swift--RELEASE-ubuntu18.04': No such file or directory
```

https://github.com/actions/virtual-environments/blob/main/images/linux/scripts/installers/swift.sh#L12 no longer returns swift version.

### Virtual environments affected

- [X] Ubuntu 18.04
- [X] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

https://github.visualstudio.com/virtual-environments/_build/results?buildId=118803&view=logs&j=011e1ec8-6569-5e69-4f06-baf193d1351e&t=5431112d-2b61-5a5f-7042-ef698f761043&l=4851

### Repro steps

N/A

**Comment by JayDoubleu** [comment]
Perhaps worth switching to `SWIFT_VERSION=$(curl -s "https://api.github.com/repos/apple/swift/releases/latest" | grep -Po '"tag_name": "swift-\K[0-9.]+')`

**Comment by mikhailkoliada** [comment]
@JayDoubleu Hello!

The easiest thing is just to pass the `--compressed` option to curl, as the output is compressed, I will prepare a pull request this week.

**Comment by JayDoubleu** [comment]
Yes, until it breaks down again. 🙃

**Comment by miketimofeev** [comment]
@JayDoubleu thank you for your contribution!
