### ISSUE TITLE
This check failed

### ISSUE THREAD

**Issue by hhhaiai** [actions/virtual-environments#4432]
### Description

MY PROJECT  BUILD FAILED, build success at 12:00, then 13:00 failed , what happen ? 

eRROR LOG:

```
This check failed


Found online and idle hosted runner in the current repository's organization account that matches the required labels: 'ubuntu-latest'
Waiting for a Hosted runner in the 'organization' to pick this job...
Job is waiting for a hosted runner to come online.
Job is about to start running on the hosted runner: GitHub Actions 2 (hosted)
```

### Virtual environments affected

- [ ] Ubuntu 18.04
- [X] Ubuntu 20.04
- [X] macOS 10.15
- [X] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

HAS NO

### Expected behavior

bUILD SUCCESS.

### Repro steps

1. commit
2. auto build
3. success, but failed

**Comment by al-cheb** [comment]
Hello, @hhhaiai 
Please provide logs to the failed builds and organization name.

**Comment by hhhaiai** [comment]
hi:     hhhaiai/analysys-dev-sdk.

has no log

![image](https://user-images.githubusercontent.com/5738285/140694996-39b4bf58-07d8-4074-8f60-201db525e353.png)

**Comment by al-cheb** [comment]
@hhhaiai , Are you still experiencing this problem if set image label to `ubuntu-20.04` or `macos-11`?

**Comment by hhhaiai** [comment]
> @hhhaiai， 您的免费分钟限制已结束（2046 分钟 > 2000 分钟）- [https://docs.github.com/en/billing/managing-billing-for-github-actions/about-billing-for-github-动作](https://docs.github.com/en/billing/managing-billing-for-github-actions/about-billing-for-github-actions) 您可以查看分钟和存储的使用细节GitHub的行动- https://docs.github.com/en/billing/managing-billing-for-github-actions/viewing-your-github-actions-usage
> 
> 我打算关闭线程。

ok. thx.
