### ISSUE TITLE
Xcode 13 is not default for macOS 11 or not found.

### ISSUE THREAD

**Issue by bitsydarel** [actions/virtual-environments#4445]
### Description

A simple xcodebuild -version step fail.

Run xcodebuild -version
  xcodebuild -version
  shell: /bin/bash -e {0}
  env:
    PR_NUMBER: 
    DEVELOPER_DIR: /Applications/Xcode_13.app/Contents/Developer
    JAVA_HOME_12.0.2_x64: /Users/runner/hostedtoolcache/jdk/12.0.2/x64
    JAVA_HOME: /Users/runner/hostedtoolcache/jdk/12.0.2/x64
    JAVA_HOME_12_0_2_X64: /Users/runner/hostedtoolcache/jdk/12.0.2/x64
    FLUTTER_ROOT: /Users/runner/hostedtoolcache/flutter/2.5.2-stable/x64
    PUB_CACHE: /Users/runner/hostedtoolcache/flutter/2.5.2-stable/x64/.pub-cache
xcrun: error: missing DEVELOPER_DIR path: /Applications/Xcode_13.app/Contents/Developer
Error: Process completed with exit code 1.

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [X] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

 Environment: macos-11
  Version: 20211029.3
  Included Software: https://github.com/actions/virtual-environments/blob/macOS-11/20211029.3/images/macos/macos-11-Readme.md
  Image Release: https://github.com/actions/virtual-environments/releases/tag/macOS-11%2F20211029.3

### Repro steps

1. Create pipeline
2. use macOS-11
3. run xcodebuild -version

**Comment by bitsydarel** [comment]
Seems like the directory "/Applications/Xcode_13.app" does not exist but directory exist "/Applications/Xcode_13.0.app"

As specified here https://github.com/actions/virtual-environments/issues/4355

**Comment by bitsydarel** [comment]
The directory path is wrong
```shell
/Applications/Xcode_13.app/Contents/Developer
```

Should be
```shell
/Applications/Xcode_13.0.app/Contents/Developer
```

**Comment by al-cheb** [comment]
Hello, @bitsydarel 
Please check Xcode section in the documenation - https://github.com/actions/virtual-environments/blob/main/images/macos/macos-11-Readme.md#xcode

### Xcode
| Version        | Build    | Path                              |
| -------------- | -------- | --------------------------------- |
| 13.2 (beta)    | 13C5066c | /Applications/Xcode_13.2.app      |
| 13.1           | 13A1030d | /Applications/Xcode_13.1.app      |
| 13.0 (default) | 13A233   | /Applications/Xcode_13.0.app      |
| 13.0 (beta)    | 13A5212g | /Applications/Xcode_13.0_beta.app |
| 12.5.1         | 12E507   | /Applications/Xcode_12.5.1.app    |
| 12.4           | 12D4e    | /Applications/Xcode_12.4.app      |
| 11.7           | 11E801a  | /Applications/Xcode_11.7.app      |

**Comment by bitsydarel** [comment]
@al-cheb  Yes but the github actions pipeline is using the wrong directory path
`DEVELOPER_DIR: /Applications/Xcode_13.app/Contents/Developer`

**Comment by bitsydarel** [comment]
seems like missing a '.0' in the xcode app name

**Comment by al-cheb** [comment]
@bitsydarel, As I can see you manually set up these variables in your pipeline and `DEVELOPER_DIR` env var points to the wrong dir.
```
env:
PR_NUMBER:
DEVELOPER_DIR: /Applications/Xcode_13.app/Contents/Developer
JAVA_HOME_12.0.2_x64: /Users/runner/hostedtoolcache/jdk/12.0.2/x64
JAVA_HOME: /Users/runner/hostedtoolcache/jdk/12.0.2/x64
JAVA_HOME_12_0_2_X64: /Users/runner/hostedtoolcache/jdk/12.0.2/x64
FLUTTER_ROOT: /Users/runner/hostedtoolcache/flutter/2.5.2-stable/x64
PUB_CACHE: /Users/runner/hostedtoolcache/flutter/2.5.2-stable/x64/.pub-cache
```

**Comment by al-cheb** [comment]
@bitsydarel, Any updates?

**Comment by al-cheb** [comment]
I am going to close the thread if you have any concerns feel free to open.
