### ISSUE TITLE
[all OSs] Default Nodejs version will be set to 16 on November, 29

### ISSUE THREAD

**Issue by miketimofeev** [actions/virtual-environments#4446]
### Breaking changes

We are going to set Nodejs 16 as the default version across all VM images.

### Target date

Image deployment is starting on November 29 and will take 3-4 days.

### The motivation for the changes

Node.js 16 has moved to Active LTS status and is ready for general use. We would like to provide images with the latest stable updates as default ones.

### Possible impact

If your builds depend on the default Nodejs 14 or npm 6 they can be broken.

### Virtual environments affected

- [X] Ubuntu 18.04
- [X] Ubuntu 20.04
- [X] macOS 10.15
- [X] macOS 11
- [X] Windows Server 2016
- [X] Windows Server 2019
- [X] Windows Server 2022

### Mitigation ways

The recommended way is to pin your workflow to the desired nodejs version using:
- https://github.com/actions/setup-node action for GH
- https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/tool/node-js?view=azure-devops for AzDO

**Comment by ejntaylor** [comment]
Is there a good place to subscribe to updates like this so we can prepare in advance for it... Or best just to keep an eye on the Issues here in GH? Thanks

**Comment by mikhailkoliada** [comment]
All the images are deployed with 16 by default

**Comment by hinchley2018** [comment]
@ejntaylor we subscribed to github releases for this repo so that we are notified in the future

**Comment by phun-ky** [comment]
Is there a better way to communicate breaking changes like this? Changes like this has to be communicated on the organization level of the consumers of this service, not the individual github users. We are now, again, having breaking builds due to the lack of proper communication regarding changes in Azure.

**Comment by miketimofeev** [comment]
@phun-ky Sorry for the inconvenience. I will raise this issue internally and we will try to figure out possible announcement options for ADO

**Comment by phun-ky** [comment]
@miketimofeev  the issue is a zlib error (https://github.com/isaacs/minizlib/issues/8#issuecomment-990112556) from npm with the `npm pack` command. Usually migated by downgrading node and npm, but since we're using your image, that way is not possible.
