### ISSUE TITLE
Update/Add Miniconda to windows-2022 image

### ISSUE THREAD

**Issue by MichaelGoulding** [actions/virtual-environments#4450]
### Tool name

Miniconda

### Tool license

same as what's on windows-latest

### Add or update?

- [X] Add
- [ ] Update

### Desired version

same as what's on windows-latest

### Brief description of tool

Miniconda is missing from the windows-2022 image

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [X] Windows Server 2022

**Comment by miketimofeev** [comment]
Hi @MichaelGoulding!
Could you please clarify — do you use conda in AzureDevOps or GH actions? I'm asking since there is a popular action for GH to install and prepare conda environment in runtime https://github.com/marketplace/actions/setup-miniconda

**Comment by miketimofeev** [comment]
@MichaelGoulding the changes have been merged. The new image will be deployed next week. I'll let you know once the deployment is finished

**Comment by mikhailkoliada** [comment]
Should be finished as per https://github.com/actions/virtual-environments/commit/1fc7895bd9e469460c143cabef1e85a848b7a39c#diff-a1f67f5c4a583bf90c239743379ad9473fbf1fa9d11c5cb7739c8012404dcc7a
