### ISSUE TITLE
`vcpkg` upgrade required since `pcre` issue

### ISSUE THREAD

**Issue by arsdever** [actions/virtual-environments#4458]
### Description

Hi guys. I'd like to ask the `vcpkg` upgrade on (at least) windows build machines because of the `pcre` package issues reported here https://github.com/microsoft/vcpkg/issues/21201.

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [X] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

20211102.4

### Expected behavior

It's possible to install `pcre` through `vcpkg`

### Actual behavior

It's failing to install `pcre` 

### Repro steps

Setup a job that installs `pcre` (in my case I install `boost-test`, `qt5-base`, and `spdlog`: `pcre` as a dependency).
https://github.com/arsdever/lcd/runs/4162600024?check_suite_focus=true

**Comment by al-cheb** [comment]
Hey, @arsdever 
We have been starting a new image rollout with `Vcpkg (build from master <70033db>)` https://github.com/actions/virtual-environments/pull/4460.  Will it work for you?

**Comment by arsdever** [comment]
> Hey, @arsdever We have been starting a new image rollout with `Vcpkg (build from master <70033db>)` #4460. Will it work for you?

Do I have any ways to check if the proposed image for the build machine will work? AKA, can I run my action on the proposed machine image?

**Comment by arsdever** [comment]
If it works, then I'd guess I'll be good with that image. Will update on this thread if the issue is still there after the image is published.

**Comment by al-cheb** [comment]
@arsdever , Windows Server 2019 has been deployed with `Vcpkg (build from master <70033db>)`.

**Comment by arsdever** [comment]
I have rerun my workflow and it succeeded. Thanks for taking care of the upgrade. 👍🏼 🥇
