### ISSUE TITLE
Default `bash` shell doesn't seem to run with `-o pipefail`

### ISSUE THREAD

**Issue by j-boivie** [actions/virtual-environments#4459]
### Description

I had an issue where I piped the output of my tests to `tee`, which would make the test step exit with success, even if the tests failed. Setting the shell parameter to use pipefail explicitly solved the issue.

```yaml
    - name: Run tests
       shell: bash -eo pipefail {0}
       run: test-command | tee output.txt
```
According to the [docs](https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#exit-codes-and-error-action-preference) this should be the default behavior, but that doesn't seem to be the case here. Additionally the step `run` logs shows
```yaml
  shell: /usr/bin/bash -e {0}
``` 

 Have I misunderstood how this is supposed to work, or is this a bug? 

### Virtual environments affected

- [ ] Ubuntu 18.04
- [X] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Current runner version: `'2.284.0'`

### Expected behavior

Failing commands will fail the entire pipeline.

### Actual behavior

Failing commands are swallowed by the rightmost command in the pipeline

### Repro steps

Run a failing command, pipe it to a successful command (like `tee`). According to the docs this should fail the step, but from what I can tell the step is marked as successful.

**Comment by al-cheb** [comment]
https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#exit-codes-and-error-action-preference
For **built-in shell** keywords, we provide the following defaults that are executed by GitHub-hosted runners.

E.g.:
```
-  name: ls
   shell: bash
   run: |
         ls
```
![image](https://user-images.githubusercontent.com/47745270/141132584-f99ebee6-2297-4b61-a800-135627d95ec4.png)

If you want to request on changing the default behavior you should create an issue in the https://github.com/actions/runner repo.

**Comment by hholst80** [comment]
A unix beard will know that bash pipefail is a POSIX sh extension not part of the POSIX sh itself.

Set `shell: bash` if you need pipefail in your github steps.

**Comment by hholst80** [comment]
@al-cheb 
I think there is an opportunity here to fix this for the majority of the users it would make sense that the default (which *is* bash!) to also include pipefail.

If I do not specify the shell, GitHub actions will use

```
 shell: /usr/bin/bash -e {0}
```

Why not simply include `-o pipefail` here as well? It would be an improvement for most users of GitHub. If a pipeline is breaking you almost surely want your GitHub action step to fail. Otherwise, specify `shell: sh` for POSIX behavior.

**Comment by Pixelatex** [comment]
god damnit, you guys broke my pipelines! this change has messed with my ci and caused everything to fail... can you please not change default values?

**Comment by n0099** [comment]
https://stackoverflow.com/questions/75419587/does-a-github-action-step-use-set-e-semantics-by-default
