### ISSUE TITLE
Add vcpkg to macOS agents

### ISSUE THREAD

**Issue by gjasny** [actions/virtual-environments#446]
**Tool information**
- Tool name: vcpkg
- Add or update? Add
- Desired version: Same as on Windows and Ubuntu

**Area for Triage**:
- Apple
- C/C++

**Question, Bug, or Feature?**:
Feature

**Virtual environments affected**
- [ x] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Can this tool be installed during the build?**
Installing vcpkg on-the-fly would take about one to two minutes. But shipping it pre-installed would bring the macOS agents in line with Windows and Ubuntu where it is already provided. Also pre-installing it would allow more aggressive caching of packaging (see #11) and shave off some build time.

**Are you willing to submit a PR?**
Yes

Thanks,
Gregor

**Comment by miketimofeev** [comment]
@gjasny thanks for your suggestion. We will consider adding vcpkg to macOS.

**Comment by miketimofeev** [comment]
@gjasny vcpkg has been added and will be rolled out next week.

**Comment by miketimofeev** [comment]
@gjasny the image has been rolled out. Could you check vcpkg is available, please?

**Comment by gjasny** [comment]
@miketimofeev Working like a charm! Thank you!

**Comment by miketimofeev** [comment]
@gjasny thanks for checking! Closing the issue.
