### ISSUE TITLE
Cannot define the machine for the Microsoft Agent

### ISSUE THREAD

**Issue by gabrielbaptista** [actions/virtual-environments#4464]
### Description

For some reason, I have tried to setup a new environment to build in my Azure DevOps Account, and I could not set the virtual environment.

![image](https://user-images.githubusercontent.com/4146065/141162673-1daec788-ccf5-4387-93cc-6320d5c0659e.png)

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [X] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

-

### Repro steps

Create a new .NET Desktop Build 
Setup up the Agent pool to pipelines

**Comment by miketimofeev** [comment]
Hi @gabrielbaptista!
We will contact the team responsible for AzDO and ask what can be done.

**Comment by miketimofeev** [comment]
@gabrielbaptista there was an issue on the AzureDevOps side, which should be resolved by now. I'm going to close the issue. Please feel free to contact us if you have any concerns.
Thank you!
