### ISSUE TITLE
Update/Add nvm to windows-latest

### ISSUE THREAD

**Issue by ljharb** [actions/virtual-environments#4471]
### Tool name

nvm

### Tool license

MIT

### Add or update?

- [X] Add
- [ ] Update

### Desired version

v0.39.0

### Brief description of tool

nvm is already included on ubuntu-latest and macos-latest. nvm also supports WSL, but it's not included on windows-latest. Could it be added?

(i'm the nvm maintainer)

### URL for tool's homepage

https://nvm.sh

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [X] Windows Server 2016
- [X] Windows Server 2019
- [X] Windows Server 2022

### Can this tool be installed during the build?

```bash
Yes, just like on the mac and ubuntu images.
```

### Are you willing to submit a PR?

Yes, but I'll need some pointers.

**Comment by al-cheb** [comment]
Hello, @ljharb 
We don't have any plans to pre-install WSL environment related to maintenance concern. Could we install nvm on Windows Server without using WSL?

**Comment by ljharb** [comment]
nvm also works in git bash and cygwin; https://github.com/actions/virtual-environments/blob/main/images/win/Windows2019-Readme.md doesn’t mention those but it does mention Bash - it’s only bash if it’s posix compliant, and nvm works in posix shells, so i assumed that “bash” meant that WSL is installed.

**Comment by fowl2** [comment]
a potential alternative to this would be to [enhance the NodeTask to support nvmrc files](https://github.com/microsoft/azure-pipelines-tasks/pull/15615) :)

**Comment by fowl2** [comment]
Also potentially relevant is this from the [nvm README](https://github.com/nvm-sh/nvm/blob/master/README.md):

> **Note:** `nvm` also support Windows in some cases. It should work through WSL (Windows Subsystem for Linux) depending on the version of WSL. It should also work with [GitBash](https://gitforwindows.org/) (MSYS) or [Cygwin](https://cygwin.com). Otherwise, for Windows, a few alternatives exist, which are neither supported nor developed by us:
> 
>   - [nvm-windows](https://github.com/coreybutler/nvm-windows)
>   - [nodist](https://github.com/marcelklehr/nodist)
>   - [nvs](https://github.com/jasongin/nvs)

**Comment by maxim-lobanov** [comment]
Support of nvmrc files was recently added to setup-node task: https://github.com/actions/setup-node/releases/tag/v2.5.0
We wouldn't like to bake nvm into the images

**Comment by ljharb** [comment]
ping; i'd still like to hear an answer to the question.

**Comment by ljharb** [comment]
@maxim-lobanov @shamil-mubarakshin ?
