### ISSUE TITLE
Update/Add  workload .NET WebAssembly build tools

### ISSUE THREAD

**Issue by ceccomil** [actions/virtual-environments#4479]
### Tool name

wasm-tools

### Tool license

MIT

### Add or update?

- [X] Add
- [ ] Update

### Desired version

latest

### Brief description of tool

Enables WebAssmbly AOT for Blazor applications

### URL for tool's homepage

https://github.com/mono/mono/tree/bdd772531d379b4e78593587d15113c37edd4a64/sdks/wasm

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [X] Windows Server 2022

**Comment by miketimofeev** [comment]
Hi @ceccomil!
This component is included in [the Microsoft.VisualStudio.Workload.NetWeb](https://docs.microsoft.com/en-us/visualstudio/install/workload-component-id-vs-enterprise?view=vs-2022#aspnet-and-web-development), which is installed on VS2022:
https://github.com/actions/virtual-environments/blob/60dcd87ff38380e3b67d6a2cdd4d8e1b37131782/images/win/toolsets/toolset-2022.json#L233

**Comment by ceccomil** [comment]
Hi @miketimofeev thanks for the prompt reply... To be honest, that is what I thought but then I don't understand why the build on Azure agent is failing:
![image](https://user-images.githubusercontent.com/40296947/141321266-56d433ab-605f-4add-8afb-fa8b19600c7e.png)

`

       "D:\a\1\s\B~~~es\K~~~App\K~~~App.csproj" (Restore target) (1) ->
       "D:\a\1\s\B~~~es\K~~~App\K~~~App.csproj" (_GenerateRestoreGraphProjectEntry target) (1:5) ->
       (_CheckForMissingWorkload target) -> 
         C:\Program Files\dotnet\sdk\6.0.100-rc.2.21505.57\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.ImportWorkloads.targets(38,5): error NETSDK1147: To build this project, the following workloads must be installed: wasm-tools`

**Comment by miketimofeev** [comment]
@ceccomil could you create a simple repro project so we can take a look?

**Comment by ceccomil** [comment]
https://dev.azure.com/milanifrancesco/Public%20Tests/_git/BlazorAotTest/commits

![image](https://user-images.githubusercontent.com/40296947/141331014-bed18611-bd94-4e90-8169-46b12623aed9.png)

As you can see the pipeline build successfully from the feature branch where AOT is disabled but fails when AOT (from main)

Locally it works fine see logs below:
**********************************************************************
PS D:\Dev\PublicTests\BlazorAotTest> dotnet publish -c Release
Microsoft (R) Build Engine version 17.0.0+c9eb9dd64 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  All projects are up-to-date for restore.
  WasmApp -> D:\Dev\PublicTests\BlazorAotTest\WasmApp\bin\Release\net6.0\WasmApp.dll
  WasmApp (Blazor output) -> D:\Dev\PublicTests\BlazorAotTest\WasmApp\bin\Release\net6.0\wwwroot
  Optimizing assemblies for size, which may change the behavior of the app. Be sure to test after publishing. See: https://aka.ms/dotnet-illink
  Optimizing assemblies for size, which may change the behavior of the app. Be sure to test after publishing. See: https://aka.ms/dotnet-illink
  AOT'ing 29 assemblies
  [1/28] Microsoft.Extensions.Configuration.Abstractions.dll -> Microsoft.Extensions.Configuration.Abstractions.dll.bc
  [2/28] System.Collections.dll -> System.Collections.dll.bc
  [3/28] System.Runtime.CompilerServices.Unsafe.dll -> System.Runtime.CompilerServices.Unsafe.dll.bc
  [4/28] System.ComponentModel.dll -> System.ComponentModel.dll.bc
  [5/28] System.Collections.Concurrent.dll -> System.Collections.Concurrent.dll.bc
  [6/28] System.Net.Http.Json.dll -> System.Net.Http.Json.dll.bc
  [7/28] WasmApp.dll -> WasmApp.dll.bc
  [8/28] Microsoft.Extensions.Configuration.Json.dll -> Microsoft.Extensions.Configuration.Json.dll.bc
  [9/28] Microsoft.AspNetCore.Components.Web.dll -> Microsoft.AspNetCore.Components.Web.dll.bc
  [10/28] Microsoft.Extensions.Primitives.dll -> Microsoft.Extensions.Primitives.dll.bc
  [11/28] Microsoft.Extensions.Options.dll -> Microsoft.Extensions.Options.dll.bc
  [12/28] Microsoft.Extensions.Configuration.dll -> Microsoft.Extensions.Configuration.dll.bc
  [13/28] System.Text.Encodings.Web.dll -> System.Text.Encodings.Web.dll.bc
  [14/28] System.Runtime.dll -> System.Runtime.dll.bc
  [15/28] Microsoft.Extensions.Logging.Abstractions.dll -> Microsoft.Extensions.Logging.Abstractions.dll.bc
  [16/28] System.Private.Runtime.InteropServices.JavaScript.dll -> System.Private.Runtime.InteropServices.JavaScript.dll.bc
  [17/28] Microsoft.Extensions.DependencyInjection.Abstractions.dll -> Microsoft.Extensions.DependencyInjection.Abstractions.dll.bc
  [18/28] System.Net.Primitives.dll -> System.Net.Primitives.dll.bc
  [19/28] System.Memory.dll -> System.Memory.dll.bc
  [20/28] Microsoft.Extensions.Logging.dll -> Microsoft.Extensions.Logging.dll.bc
  [21/28] System.Private.Uri.dll -> System.Private.Uri.dll.bc
  [22/28] Microsoft.JSInterop.dll -> Microsoft.JSInterop.dll.bc
  [23/28] Microsoft.Extensions.DependencyInjection.dll -> Microsoft.Extensions.DependencyInjection.dll.bc
  [24/28] Microsoft.AspNetCore.Components.WebAssembly.dll -> Microsoft.AspNetCore.Components.WebAssembly.dll.bc
  [25/28] System.Net.Http.dll -> System.Net.Http.dll.bc
  [26/28] Microsoft.AspNetCore.Components.dll -> Microsoft.AspNetCore.Components.dll.bc
  [27/28] System.Text.Json.dll -> System.Text.Json.dll.bc
  [28/28] System.Private.CoreLib.dll -> System.Private.CoreLib.dll.bc
  Compiling native assets with emcc. This may take a while ...
  [1/3] pinvoke.c -> pinvoke.o [took 0.51s]
  [2/3] corebindings.c -> corebindings.o [took 0.60s]
  [3/3] driver.c -> driver.o [took 0.69s]
  Compiling assembly bitcode files...
  [1/28] System.Net.Http.Json.dll.bc -> System.Net.Http.Json.dll.o [took 0.99s]
  [2/28] System.Net.Primitives.dll.bc -> System.Net.Primitives.dll.o [took 1.48s]
  [3/28] WasmApp.dll.bc -> WasmApp.dll.o [took 1.48s]
  [4/28] Microsoft.Extensions.DependencyInjection.Abstractions.dll.bc -> Microsoft.Extensions.DependencyInjection.Abstractions.dll.o [took 1.49s]
  [5/28] System.Runtime.dll.bc -> System.Runtime.dll.o [took 1.00s]
  [6/28] System.Collections.Concurrent.dll.bc -> System.Collections.Concurrent.dll.o [took 1.99s]
  [7/28] System.ComponentModel.dll.bc -> System.ComponentModel.dll.o [took 1.99s]
  [8/28] Microsoft.Extensions.Primitives.dll.bc -> Microsoft.Extensions.Primitives.dll.o [took 1.99s]
  [9/28] Microsoft.AspNetCore.Components.Web.dll.bc -> Microsoft.AspNetCore.Components.Web.dll.o [took 1.99s]
  [10/28] Microsoft.Extensions.Configuration.Json.dll.bc -> Microsoft.Extensions.Configuration.Json.dll.o [took 1.99s]
  [11/28] System.Collections.dll.bc -> System.Collections.dll.o [took 1.99s]
  [12/28] Microsoft.Extensions.Configuration.Abstractions.dll.bc -> Microsoft.Extensions.Configuration.Abstractions.dll.o [took 1.99s]
  [13/28] Microsoft.Extensions.Options.dll.bc -> Microsoft.Extensions.Options.dll.o [took 1.99s]
  [14/28] Microsoft.Extensions.Configuration.dll.bc -> Microsoft.Extensions.Configuration.dll.o [took 1.99s]
  [15/28] System.Runtime.CompilerServices.Unsafe.dll.bc -> System.Runtime.CompilerServices.Unsafe.dll.o [took 1.99s]
  [16/28] Microsoft.Extensions.Logging.Abstractions.dll.bc -> Microsoft.Extensions.Logging.Abstractions.dll.o [took 2.29s]
  [17/28] System.Memory.dll.bc -> System.Memory.dll.o [took 2.97s]
  [18/28] System.Text.Encodings.Web.dll.bc -> System.Text.Encodings.Web.dll.o [took 1.53s]
  [19/28] System.Private.Runtime.InteropServices.JavaScript.dll.bc -> System.Private.Runtime.InteropServices.JavaScript.dll.o [took 3.43s]
  [20/28] Microsoft.Extensions.Logging.dll.bc -> Microsoft.Extensions.Logging.dll.o [took 3.45s]
  [21/28] Microsoft.JSInterop.dll.bc -> Microsoft.JSInterop.dll.o [took 4.96s]
  [22/28] System.Private.Uri.dll.bc -> System.Private.Uri.dll.o [took 4.99s]
  [23/28] Microsoft.Extensions.DependencyInjection.dll.bc -> Microsoft.Extensions.DependencyInjection.dll.o [took 5.72s]
  [24/28] Microsoft.AspNetCore.Components.WebAssembly.dll.bc -> Microsoft.AspNetCore.Components.WebAssembly.dll.o [took 6.33s]
  [25/28] System.Net.Http.dll.bc -> System.Net.Http.dll.o [took 8.42s]
  [26/28] Microsoft.AspNetCore.Components.dll.bc -> Microsoft.AspNetCore.Components.dll.o [took 17.48s]
  [27/28] System.Text.Json.dll.bc -> System.Text.Json.dll.o [took 24.84s]
  [28/28] System.Private.CoreLib.dll.bc -> System.Private.CoreLib.dll.o [took 58.03s]
  Linking with emcc. This may take a while ...
   "C:\Program Files\dotnet\packs\Microsoft.NET.Runtime.Emscripten.2.0.23.Sdk.win-x64\6.0.0\tools\bin\wasm-ld.exe" -o D:\Dev\PublicTests\BlazorAotTest\WasmApp\obj\Release\net6.0\wasm\for-publish\dotnet.wasm D:\Dev\PublicTests\BlazorAotTest\WasmApp\obj\Release\net6.0\wasm\for-publish\Microsoft.AspNetCore.Components.dll.o D:\Dev\PublicTests\BlazorAotTest\WasmApp\obj\Release\net6.0\wasm\for-publish\Microsoft.AspNetCore.Components.Web.dll.o D:\Dev\PublicTests\BlazorAotTest\WasmApp\obj\Release\net6.0\wasm\for-publish\Microsoft.AspNetCore.Components.WebAssembly.dll.o D:\Dev\PublicTests\BlazorAotTest\WasmApp\obj\Release\net6.0\wasm\for-publish\Microsoft.Extensions.Configuration.dll.o D:\Dev\PublicTests\BlazorAotTest\WasmApp\obj\Release\net6.0\wasm\for-publish\Microsoft.Extensions.Configuration.Abstractions.dll.o D:\Dev\PublicTests\BlazorAotTest\WasmApp\obj\Release\net6.0\wasm\for-publish\Microsoft.Extensions.Configuration.Json.dll.o D:\Dev\PublicTests\BlazorAotTest\WasmApp\obj\Release\net6.0\wasm\for-publish\Microsoft.Extensions.DependencyInjection.dll.o D:\Dev\PublicTests\BlazorAotTest\WasmApp\obj\Release\net6.0\wasm\for-publish\Microsoft.Extensions.DependencyInjection.Abstractions.dll.o D:\Dev\PublicTests\BlazorAotTest\WasmApp\obj\Release\net6.0\wasm\for-publish\Microsoft.Extensions.Logging.dll.o D:\Dev\PublicTests\BlazorAotTest\WasmApp\obj\Release\net6.0\wasm\for-publish\Microsoft.Extensions.Logging.Abstractions.dll.o D:\Dev\PublicTests\BlazorAotTest\WasmApp\obj\Release\net6.0\wasm\for-publish\Microsoft.Extensions.Options.dll.o D:\Dev\PublicTests\BlazorAotTest\WasmApp\obj\Release\net6.0\wasm\for-publish\Microsoft.Extensions.Primitives.dll.o D:\Dev\PublicTests\BlazorAotTest\WasmApp\obj\Release\net6.0\wasm\for-publish\Microsoft.JSInterop.dll.o D:\Dev\PublicTests\BlazorAotTest\WasmApp\obj\Release\net6.0\wasm\for-publish\WasmApp.dll.o D:\Dev\PublicTests\BlazorAotTest\WasmApp\obj\Release\net6.0\wasm\for-publish\System.Collections.Concurrent.dll.o D:\Dev\PublicTests\BlazorAotTest\WasmApp\obj\Release\net6.0\wasm\for-publish\System.Collections.dll.o D:\Dev\PublicTests\BlazorAotTest\WasmApp\obj\Release\net6.0\wasm\for-publish\System.ComponentModel.dll.o D:\Dev\PublicTests\BlazorAotTest\WasmApp\obj\Release\net6.0\wasm\for-publish\System.Memory.dll.o D:\Dev\PublicTests\BlazorAotTest\WasmApp\obj\Release\net6.0\wasm\for-publish\System.Net.Http.Json.dll.o D:\Dev\PublicTests\BlazorAotTest\WasmApp\obj\Release\net6.0\wasm\for-publish\System.Net.Http.dll.o D:\Dev\PublicTests\BlazorAotTest\WasmApp\obj\Release\net6.0\wasm\for-publish\System.Net.Primitives.dll.o D:\Dev\PublicTests\BlazorAotTest\WasmApp\obj\Release\net6.0\wasm\for-publish\System.Private.Runtime.InteropServices.JavaScript.dll.o D:\Dev\PublicTests\BlazorAotTest\WasmApp\obj\Release\net6.0\wasm\for-publish\System.Private.Uri.dll.o D:\Dev\PublicTests\BlazorAotTest\WasmApp\obj\Release\net6.0\wasm\for-publish\System.Runtime.CompilerServices.Unsafe.dll.o D:\Dev\PublicTests\BlazorAotTest\WasmApp\obj\Release\net6.0\wasm\for-publish\System.Runtime.dll.o D:\Dev\PublicTests\BlazorAotTest\WasmApp\obj\Release\net6.0\wasm\for-publish\System.Text.Encodings.Web.dll.o D:\Dev\PublicTests\BlazorAotTest\WasmApp\obj\Release\net6.0\wasm\for-publish\System.Text.Json.dll.o D:\Dev\PublicTests\BlazorAotTest\WasmApp\obj\Release\net6.0\wasm\for-publish\System.Private.CoreLib.dll.o D:\Dev\PublicTests\BlazorAotTest\WasmApp\obj\Release\net6.0\wasm\for-publish\pinvoke.o D:\Dev\PublicTests\BlazorAotTest\WasmApp\obj\Release\net6.0\wasm\for-publish\driver.o D:\Dev\PublicTests\BlazorAotTest\WasmApp\obj\Release\net6.0\wasm\for-publish\corebindings.o "C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Runtime.Mono.browser-wasm\6.0.0\runtimes\browser-wasm\native\libicui18n.a" "C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Runtime.Mono.browser-wasm\6.0.0\runtimes\browser-wasm\native\libicuuc.a" "C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Runtime.Mono.browser-wasm\6.0.0\runtimes\browser-wasm\native\libmono-component-debugger-stub-static.a" "C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Runtime.Mono.browser-wasm\6.0.0\runtimes\browser-wasm\native\libmono-component-diagnostics_tracing-stub-static.a" "C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Runtime.Mono.browser-wasm\6.0.0\runtimes\browser-wasm\native\libmono-component-hot_reload-stub-static.a" "C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Runtime.Mono.browser-wasm\6.0.0\runtimes\browser-wasm\native\libmono-ee-interp.a" "C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Runtime.Mono.browser-wasm\6.0.0\runtimes\browser-wasm\native\libmono-icall-table.a" "C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Runtime.Mono.browser-wasm\6.0.0\runtimes\browser-wasm\native\libmono-ilgen.a" "C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Runtime.Mono.browser-wasm\6.0.0\runtimes\browser-wasm\native\libmono-profiler-aot.a" "C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Runtime.Mono.browser-wasm\6.0.0\runtimes\browser-wasm\native\libmonosgen-2.0.a" "C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Runtime.Mono.browser-wasm\6.0.0\runtimes\browser-wasm\native\libSystem.IO.Compression.Native.a" "C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Runtime.Mono.browser-wasm\6.0.0\runtimes\browser-wasm\native\libSystem.Native.a" "-LC:\Program Files\dotnet\packs\Microsoft.NET.Runtime.Emscripten.2.0.23.Sdk.win-x64\6.0.0\tools\emscripten\cache\sysroot\lib\wasm32-emscripten" "C:\Program Files\dotnet\packs\Microsoft.NET.Runtime.Emscripten.2.0.23.Sdk.win-x64\6.0.0\tools\emscripten\cache\sysroot\lib\wasm32-emscripten\libgl.a" "C:\Program Files\dotnet\packs\Microsoft.NET.Runtime.Emscripten.2.0.23.Sdk.win-x64\6.0.0\tools\emscripten\cache\sysroot\lib\wasm32-emscripten\libal.a" "C:\Program Files\dotnet\packs\Microsoft.NET.Runtime.Emscripten.2.0.23.Sdk.win-x64\6.0.0\tools\emscripten\cache\sysroot\lib\wasm32-emscripten\libhtml5.a" "C:\Program Files\dotnet\packs\Microsoft.NET.Runtime.Emscripten.2.0.23.Sdk.win-x64\6.0.0\tools\emscripten\cache\sysroot\lib\wasm32-emscripten\libc.a" "C:\Program Files\dotnet\packs\Microsoft.NET.Runtime.Emscripten.2.0.23.Sdk.win-x64\6.0.0\tools\emscripten\cache\sysroot\lib\wasm32-emscripten\libcompiler_rt.a" "C:\Program Files\dotnet\packs\Microsoft.NET.Runtime.Emscripten.2.0.23.Sdk.win-x64\6.0.0\tools\emscripten\cache\sysroot\lib\wasm32-emscripten\libc++.a" "C:\Program Files\dotnet\packs\Microsoft.NET.Runtime.Emscripten.2.0.23.Sdk.win-x64\6.0.0\tools\emscripten\cache\sysroot\lib\wasm32-emscripten\libc++abi.a" "C:\Program Files\dotnet\packs\Microsoft.NET.Runtime.Emscripten.2.0.23.Sdk.win-x64\6.0.0\tools\emscripten\cache\sysroot\lib\wasm32-emscripten\libdlmalloc.a" "C:\Program Files\dotnet\packs\Microsoft.NET.Runtime.Emscripten.2.0.23.Sdk.win-x64\6.0.0\tools\emscripten\cache\sysroot\lib\wasm32-emscripten\libc_rt_wasm-optz.a" "C:\Program Files\dotnet\packs\Microsoft.NET.Runtime.Emscripten.2.0.23.Sdk.win-x64\6.0.0\tools\emscripten\cache\sysroot\lib\wasm32-emscripten\libsockets.a" -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-cxx-exceptions -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr --allow-undefined --export putchar --export stackSave --export stackRestore --export stackAlloc --export __wasm_call_ctors --export __errno_location --export malloc --export free --export __cxa_is_pointer_type --export __cxa_can_catch --export setThrew --export _get_tzname --export _get_daylight --export _get_timezone --export ntohs --export htons --export htonl --export memset --export memalign --export emscripten_main_thread_process_queued_calls --export-if-defined=__start_em_asm --export-if-defined=__stop_em_asm --export-table -z stack-size=5242880 --initial-memory=536870912 --no-entry --max-memory=2147483648 --global-base=1024
   "C:\Program Files\dotnet\packs\Microsoft.NET.Runtime.Emscripten.2.0.23.Sdk.win-x64\6.0.0\tools\bin\wasm-emscripten-finalize" --minimize-wasm-changes -g --dyncalls-i64 D:\Dev\PublicTests\BlazorAotTest\WasmApp\obj\Release\net6.0\wasm\for-publish\dotnet.wasm -o D:\Dev\PublicTests\BlazorAotTest\WasmApp\obj\Release\net6.0\wasm\for-publish\dotnet.wasm --detect-features
   "C:\Program Files\dotnet\packs\Microsoft.NET.Runtime.Emscripten.2.0.23.Node.win-x64\6.0.0\tools\bin\node.exe" "C:\Program Files\dotnet\packs\Microsoft.NET.Runtime.Emscripten.2.0.23.Sdk.win-x64\6.0.0\tools\emscripten\src\compiler.js" C:\Users\cecco\AppData\Local\Temp\tmpi6_3gchs.txt
   "C:\Program Files\dotnet\packs\Microsoft.NET.Runtime.Emscripten.2.0.23.Sdk.win-x64\6.0.0\tools\bin\wasm-opt" --strip-dwarf --post-emscripten --no-exit-runtime -Oz --low-memory-unused --zero-filled-memory --strip-debug --strip-producers D:\Dev\PublicTests\BlazorAotTest\WasmApp\obj\Release\net6.0\wasm\for-publish\dotnet.wasm -o D:\Dev\PublicTests\BlazorAotTest\WasmApp\obj\Release\net6.0\wasm\for-publish\dotnet.wasm -g --mvp-features --enable-mutable-globals
   "C:\Program Files\dotnet\packs\Microsoft.NET.Runtime.Emscripten.2.0.23.Node.win-x64\6.0.0\tools\bin\node.exe" "C:\Program Files\dotnet\packs\Microsoft.NET.Runtime.Emscripten.2.0.23.Sdk.win-x64\6.0.0\tools\emscripten\tools\acorn-optimizer.js" C:\Users\cecco\AppData\Local\Temp\emscripten_temp_1b672lya\dotnet.js AJSDCE minifyWhitespace
   "C:\Program Files\dotnet\packs\Microsoft.NET.Runtime.Emscripten.2.0.23.Node.win-x64\6.0.0\tools\bin\node.exe" "C:\Program Files\dotnet\packs\Microsoft.NET.Runtime.Emscripten.2.0.23.Sdk.win-x64\6.0.0\tools\emscripten\tools\acorn-optimizer.js" C:\Users\cecco\AppData\Local\Temp\tmpigjuu55b.js emitDCEGraph noPrint
   "C:\Program Files\dotnet\packs\Microsoft.NET.Runtime.Emscripten.2.0.23.Sdk.win-x64\6.0.0\tools\bin\wasm-metadce" --graph-file=C:\Users\cecco\AppData\Local\Temp\tmptfalyeyy.txt D:\Dev\PublicTests\BlazorAotTest\WasmApp\obj\Release\net6.0\wasm\for-publish\dotnet.wasm -o D:\Dev\PublicTests\BlazorAotTest\WasmApp\obj\Release\net6.0\wasm\for-publish\dotnet.wasm -g --mvp-features --enable-mutable-globals
   "C:\Program Files\dotnet\packs\Microsoft.NET.Runtime.Emscripten.2.0.23.Node.win-x64\6.0.0\tools\bin\node.exe" "C:\Program Files\dotnet\packs\Microsoft.NET.Runtime.Emscripten.2.0.23.Sdk.win-x64\6.0.0\tools\emscripten\tools\acorn-optimizer.js" C:\Users\cecco\AppData\Local\Temp\tmp0a634nux.js applyDCEGraphRemovals minifyWhitespace
   "C:\Program Files\dotnet\packs\Microsoft.NET.Runtime.Emscripten.2.0.23.Node.win-x64\6.0.0\tools\bin\node.exe" "C:\Program Files\dotnet\packs\Microsoft.NET.Runtime.Emscripten.2.0.23.Sdk.win-x64\6.0.0\tools\emscripten\tools\acorn-optimizer.js" C:\Users\cecco\AppData\Local\Temp\emscripten_temp_1b672lya\dotnet.js.jso.js.jso.js AJSDCE minifyWhitespace
   "C:\Program Files\dotnet\packs\Microsoft.NET.Runtime.Emscripten.2.0.23.Sdk.win-x64\6.0.0\tools\bin\wasm-opt" --strip-dwarf --minify-imports-and-exports-and-modules D:\Dev\PublicTests\BlazorAotTest\WasmApp\obj\Release\net6.0\wasm\for-publish\dotnet.wasm -o D:\Dev\PublicTests\BlazorAotTest\WasmApp\obj\Release\net6.0\wasm\for-publish\dotnet.wasm -g --mvp-features --enable-mutable-globals
   "C:\Program Files\dotnet\packs\Microsoft.NET.Runtime.Emscripten.2.0.23.Node.win-x64\6.0.0\tools\bin\node.exe" "C:\Program Files\dotnet\packs\Microsoft.NET.Runtime.Emscripten.2.0.23.Sdk.win-x64\6.0.0\tools\emscripten\tools\acorn-optimizer.js" C:\Users\cecco\AppData\Local\Temp\tmpbada54ok.js applyImportAndExportNameChanges minifyWhitespace
  Optimizing dotnet.wasm ...
  Compressing Blazor WebAssembly publish artifacts. This may take a while...
  WasmApp -> D:\Dev\PublicTests\BlazorAotTest\WasmApp\bin\Release\net6.0\publish\

**Comment by miketimofeev** [comment]
@ceccomil thanks for the example! I've created a VM from the image and it seems the workload doesn't install this component by default as the component is optional.
![image](https://user-images.githubusercontent.com/48208649/141348983-e550af31-40b5-4d85-861c-525244a5e2d1.png)
Could you try to install it in runtime using the following snippet and check if it helps?
```
Set-Location "C:\Program Files (x86)\Microsoft Visual Studio\Installer\"
$InstallPath = "C:\Program Files\Microsoft Visual Studio\2022\Enterprise"
$componentsToAdd = @(
  "wasm.tools"
)
[string]$workloadArgs = $componentsToAdd | ForEach-Object {" --add " +  $_}
$Arguments = ('/c', "vs_installer.exe", 'modify', '--installPath', "`"$InstallPath`"",$workloadArgs, '--quiet', '--norestart', '--nocache')
$process = Start-Process -FilePath cmd.exe -ArgumentList $Arguments -Wait -PassThru -WindowStyle Hidden
if ($process.ExitCode -eq 0)
{
    Write-Host "components have been successfully added"
}
else
{
    Write-Host "components were not installed"
    exit 1
}
```

**Comment by ceccomil** [comment]
@miketimofeev Many thanks the installation during the pipeline execution solved the problem.
![image](https://user-images.githubusercontent.com/40296947/141369884-bcb0ce52-beb7-4a02-8984-0a5db9a919a6.png)

I'm just wondering since is quite a time-consuming task, will it always be treated as an optional component? or is there a plan to add it to the image?

**Comment by miketimofeev** [comment]
@ceccomil since VS2022 is the reason to use windows-2022 image we don't mind adding the component. The changes will be available next week.

**Comment by KVROHITH098** [comment]
I will do this change thank you.

**Comment by KVROHITH098** [comment]
Is this done Jake?

**Comment by KVROHITH098** [comment]
I will do this on Saturday.

**Comment by mikhailkoliada** [comment]
WASM component is in the win22 image already https://github.com/actions/virtual-environments/blob/main/images/win/Windows2022-Readme.md
