### ISSUE TITLE
libgdiplus on ubuntu

### ISSUE THREAD

**Issue by ceilingfish** [actions/virtual-environments#4486]
### Tool name

libgdiplus

### Tool license

None? https://github.com/mono/libgdiplus/blob/main/LICENSE

### Add or update?

- [X] Add
- [ ] Update

### Desired version

latest

### Approximate size

140Kb

### Brief description of tool

This is a supporting library used by the `System.Drawing` API in .net 5, when it runs on linux. It's authored by the Mono project.

### URL for tool's homepage

https://github.com/mono/libgdiplus

### Provide a basic test case to validate the tool's functionality.

```bash
echo '<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net5.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Drawing.Common" Version="5.0.3" />
  </ItemGroup>

</Project>' > GdiTest.csproj

echo 'using System.Drawing;
using System.Net.Http;

using var downloader = new HttpClient();
using var imageSource = await downloader.GetStreamAsync("https://filesamples.com/samples/image/jpg/sample_640%C3%97426.jpg");
using var image = Image.FromStream(imageSource);' > Program.cs

dotnet run GdiTest.csproj
# Exit code should be zero
```

### Virtual environments affected

- [X] Ubuntu 18.04
- [X] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Can this tool be installed during the build?

```bash
apt-get install libgdiplus
```

### Tool installation time in runtime

a second or so? negligible time

### Are you willing to submit a PR?

yep

**Comment by MaksimZhukov** [comment]
Hello @ceilingfish !
Considering fast installation time in runtime and maintenance concerns we would not like to add this tool to the images.

I'm going to close the issue, but feel free to contact us if you have any concerns.
Thank you!
