### ISSUE TITLE
Windows Server 2022 with Visual Studio 2022 is generally available starting from November, 15

### ISSUE THREAD

**Issue by miketimofeev** [actions/virtual-environments#4488]
### Change

Windows Server 2022 with Visual Studio 2022 is generally available starting from November, 15. Use it by putting `runs-on: windows-2022` in your workflow file.

### Target date

November, 15

### The motivation for the changes

- Visual Studio 2022 came out of preview
- Most of the software issues with the new image were resolved

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [X] Windows Server 2022

**Comment by julianxhokaxhiu** [comment]
Just wanted to let you know I've tested my pipeline on top of this image and it worked great. Smoother migration ever :)

Kudos to the team!

**Comment by KVROHITH098** [comment]
Well I can create a issue for that if u want me to Jake?

**Comment by KVROHITH098** [comment]
Well I am working on this as of right now I will let you guys now soon ok?

**Comment by KVROHITH098** [comment]
Please the new ones to me thank you!

**Comment by MattChique** [comment]
When will `windows-latest` be replaced by `windows-2022`?

**Comment by miketimofeev** [comment]
@MattChique it will be announced, but not early than next year

**Comment by azarorami** [comment]
tankyouuuuuuu
