### ISSUE TITLE
/bin/tar: not works properly on 'Hosted Agent(hosted)'

### ISSUE THREAD

**Issue by RainbowMango** [actions/virtual-environments#4496]
### Description

We are using the [fossa-contrib/fossa-action](https://github.com/karmada-io/karmada/blob/master/.github/workflows/fossa.yml), it starts falling this morning, the error message I can get as follows:
```
Run fossa-contrib/fossa-action@v1
/bin/tar xz --warning=no-unknown-keyword -C /home/runner/work/_temp/b600da16-d0fc-4618-b759-84e3b4d24187 -f /home/runner/work/_temp/7fee720e-9a2e-474b-b1b5-c68ff59b133a
/bin/tar: This does not look like a tar archive
/bin/tar: Skipping to next header
/bin/tar: Exiting with failure status due to previous errors
```
More details info you can get from [here](https://github.com/karmada-io/karmada/runs/4196669453?check_suite_focus=true).

I compared the logs against previous and found that all the falling run on the `GitHub Actions 2` runner.
```
2021-11-13T06:15:24.9669759Z Job is about to start running on the hosted runner: GitHub Actions 2 (hosted)
```

In addition, the success one runs on the `Hosted Agent`:
```
2021-11-12T12:11:52.9842795Z Job is about to start running on the hosted runner: Hosted Agent (hosted)
```

So, I guess the `hosted runner` is the most suspicious.

### Virtual environments affected

- [X] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Version: 20211108.1
https://github.com/karmada-io/karmada/runs/4196669453?check_suite_focus=true

### Is it regression?

https://github.com/karmada-io/karmada/runs/4191593702?check_suite_focus=true

### Repro steps

Retrigger the workflow, either by push or sending a PR.

**Comment by mikhailkoliada** [comment]
@RainbowMango Hello!

I believe all your concerns got solved here https://github.com/karmada-io/karmada/commit/8d8cc260bfe1401b801e2d8f1b92e259802ae310. It is though worth mentioning that all the concerns must be directed to the module's author (in the future), as we are only providing the hosted agents' environments while it seems the error you reflected concerns the module you are using.

I am going to close the issue now, feel free to ping us if you have any questions.

**Comment by RainbowMango** [comment]
Yeah, the module's author also fixed the issue.
