### ISSUE TITLE
Linux distribution available as virtual environments for GitHub Actions ( or rather lack there of )

### ISSUE THREAD

**Issue by johannbg** [actions/virtual-environments#45]
**Describe the bug**

When providing integrated linux distribution support, be it for devices, tools, build system, projects, for package management system/support in distributions there are 5 parent distribution and their package management system that should be supported always since by doing so you will cover the more or less the rest of what the 400 - 500 Linux distributions out there which are deviating from their parent distribution ( which more or less are those fives ) based on religions purposes or disagreement ( fork offs ) not from technical or development standpoint, causing needless deviation and pain points for upstream developers and system administrators in the core/baseOS stack, in which upstreams ( company's and opensource developers ) build their application stack upon and developers and system administrators have to deploy and support. 

Arch  ( derivative for example Manjaro )
Debian ( derivative for example Ubuntu )
Fedora ( derivative  for example Redhat/CentOS )
Gentoo ( derivative for example Google's ChromeOS )
OpenSuse (  derivative for example SUSE Linux Enterprise/SLES ) 

**Virtual environments affected**
The virtual environments provider itself.

**Expected behavior**
Expected behaviour is to be able to chose one of the 5 parent distributions as a supported virtual environments and hardware resources as I previously mentioned before and those distribution being outlined and mentioned here [1] and here [2] as an available OS options for "runs-on:" or atleast the "Guest operating systems supported on Azure Stack" as outlined here [3] in Azures documentations so distributions that would like to be supported as Linux distribution available as virtual environments for GitHub Actions, would then have to work towards getting themselves officially supported as an guest operating system on Microsoft's Azure Stack.

**Actual behavior**
Only Ubuntu listed as an option which is an Linux distribution that only works by hack-ish workarounds rather than solving real fundamental OS/Desktop issues and seem to attract more often than not some hipster programming diva's who spend more time on starbucks coffee shops at their employees expense rather than developing software or solve real problems in the software universe.

A better alternative would be providing Debian as the singular linux run-os option.

Another thing worth mentioning is that there seems to be no documentation why Github has chosen to chose Ubuntu as the *only* linux distribution of chose. Did Canonical/Mark Shuttleworth specifically pay Github for that Linux monopoly which then should be mentioned somewhere...  

1. https://help.github.com/en/articles/virtual-environments-for-github-actions
2. https://help.github.com/en/articles/software-in-virtual-environments-for-github-actions
3. https://docs.microsoft.com/en-us/azure-stack/operator/azure-stack-supported-os?view=azs-1908

**Comment by ADmad** [comment]
If you don't like Ubuntu can't you just use a docker image based on distro of your choice?

Other CI / CD providers like TravisCI, CircleCI also use Ubuntu for their Linux VMs so surely the "hack-ish workarounds" you claim Ubuntu needs isn't an issue for most.

**Comment by oldskool** [comment]
That's a lot of Ubuntu hate there and insulting a lot of people that use it in the process. Was that really necessary? I guess you needed to let go of some built up frustration. 😕 

Anyway, yes, Ubuntu is currently the only choice and is a Debian derivative. But one of the main benefits over Debian itself is that the apt repositories receive updates faster. Debian is more enterprise-ish with their release cycles, Ubuntu is more bleeding edge.

The latter makes it particularly useful for software development, as you generally want to test things against recent versions of software. But like ADmad said, nothing is stopping you from spinning up your jobs in a Debian container if that's more your thing.

**Comment by kaylangan** [comment]
@johannbg thanks for sharing your thoughts and feedback.

We do not plan to support other Linux distros. As others have mentioned, Docker is great for this purpose. We'd suggest using Docker for the distros you desire.

**Comment by johannbg** [comment]
Why do you not plan to support other Linux distros what's the argument for not doing so and why was Ubuntu chosen?

**Comment by johannbg** [comment]
If this was my personal preference I would just have mentioned one Linux distribution and left out the others and mentioning and referring to the Azure official guest images ( which include Ubuntu ) but might been a valid technical limitation ( we are bound to provide ( and even run on ) what Azure officially supports ). 

Compliance might be one such reason in which one might want to ( or have to  ) run anything related to the infrastructure either self hosted or virtual machines running specific OS instance ( Windows/Linux/OS-X ) running the workflows which you point to or on a platform that meets such compliance or legal requirments. Such feature could be implemented behind a paywall such as "GitHub Enterprise" while the rest of the world would be stuck with Ubuntu as their only option but given that "We do not plan to support other Linux distros" you ( read as github ) don't even seem to be considering providing alternatives on github's enterprise side of things or compliances has been a low hanging fruit on the github actions table.

**Comment by oldskool** [comment]
> run anything related to the infrastructure either self hosted or virtual machines running specific OS instance

And that will be possible since self-hosted runners [are becoming available](https://github.community/t5/GitHub-Actions/How-to-setup-GitHub-action-in-a-self-hosted-VM-instance/m-p/30800/highlight/true#M566) prior to the GA in november. So if you feel like you need to run your Actions runners on Debian, Arch or whatever OS that's not Ubuntu, go right ahead and do it.

**Comment by johannbg** [comment]
I was unaware of that possibility and thanks for pointing that out. That most certainly will make things easier from compliance and security perspective.

**Comment by andyfeller** [comment]
> And that will be possible since self-hosted runners are becoming available prior to the GA in november. So if you feel like you need to run your Actions runners on Debian, Arch or whatever OS that's not Ubuntu, go right ahead and do it.

It would have been appreciated if this was the initial reply rather than all the back and forth.

**Comment by jiridanek** [comment]
For anybody wondering how to run a workflow in a docker image, the answer is https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#jobsjob_idcontainer. You'd use ubuntu image in the `runs-on`, but then you also specify a container to be started on that ubuntu, to run your steps.

**Comment by ekohl** [comment]
https://github.com/pulp/pulpcore-selinux/commit/41d4bba87fcbb174f7c24dccce7e8891b5856d66 is an example of how to compile SELinux policies on CentOS 7 and 8. Since it's still running on an Ubuntu kernel, you obviously can't actually load the policy to see if it would work. A real VM is needed for that. However, it can provide a decent base line test.

**Comment by MTecknology** [comment]
The Mac image comes with virtualbox, so if you really need to use something else on github's hardware, you can use that.

FreeBSD - https://github.com/vmactions/freebsd-vm

It takes a lot longer to run the tests, but it works great. It seems like a fair compromise between github focusing on security, stability, and overall quality of the few images they're supporting and our ability to abuse their hardware with trillions of tests. :D

**Comment by wsdfhjxc** [comment]
For anyone interested, I've created the [Run in LXC](https://github.com/wsdfhjxc/run-in-lxc-action) action, so it's possible to run commands or scripts in LXC containers (Fedora, Debian, openSUSE, or whatever is supported by LXC). Of course, this isn't so convenient and flexible as a native runner, and has limitations, but it does the job for my simple needs (building and packaging). So, I thought I could share it here as well.

**Comment by radiomix** [comment]
@oldskool 
>Let's turn the question around. Why do you need other Linux distros

AWS EC2 instances come with AWS linux: It would be _nice_  to run Github Actions on an AWS-like OS. 
Seems as if Github - aka MicroSoft aka closed-source - and AWS are competitors, hence . . . ;-((  we woun't see any progress here.

Probably also holds true for:
>Why do you not plan to support other Linux distros what's the argument for not doing so and why was Ubuntu chosen?

This all reminds me of the 90s when monopoly IT big evil was . . . .
 

![ms](https://user-images.githubusercontent.com/6728633/196969396-d85eb038-d3cf-439f-ac8d-8a14b3385d40.jpeg)
