### ISSUE TITLE
Add Lua

### ISSUE THREAD

**Issue by greatwolf** [actions/virtual-environments#450]
**Tool information**
- Tool name: Lua Programming Language
- Add or update? Add
- Desired version: 5.1.5, 5.2, 5.3, LuaJIT 2.1
- Approximate size: <2MB for each version
- If this is an add request:
  - Brief description of tool: Dynamic programming language like Python, Ruby and JS
  - URL for tool's homepage: lua.org for vanilla lua, luajit.org for JIT version of Lua

**Area for Triage**:

**Question, Bug, or Feature?**
Feature

**Virtual environments affected**
- [x] macOS 10.15
- [x] Ubuntu 16.04 LTS
- [x] Ubuntu 18.04 LTS
- [x] Windows Server 2016 R2
- [x] Windows Server 2019

**Can this tool be installed during the build?**
Yes, someone already wrote a github action for it here: https://github.com/marketplace/actions/install-lua-luajit

**Are you willing to submit a PR?**
Sure

**Comment by alepauly** [comment]
Hi @greatwolf, since there's already an Action for it and it seems pretty quick, we won't add it to the image at this time. Thanks for suggesting it.
