### ISSUE TITLE
InnoSetup and Google Cloud SDK missing from windows-2022 agent

### ISSUE THREAD

**Issue by fernandreu** [actions/virtual-environments#4501]
### Description

Hi, I noticed that both InnoSetup 6.2.0 and Google Cloud SDK 364.0.0 are missing in the [list of tools for windows-2022](https://github.com/actions/virtual-environments/blob/main/images/win/Windows2022-Readme.md) when compared to the [windows-2019 list](https://github.com/actions/virtual-environments/blob/main/images/win/Windows2019-Readme.md).

These could have been removed from the agent on purpose of course, but it looked a bit suspicious to me that the only two tools removed are alphabetically next to each other 😇

I am not using Google Cloud SDK in my pipelines, but I definitely get a `The system cannot find the path specified` from my script which I didn't get on `windows-2019` (assuming it would still be located in `C:\Program Files (x86)\Inno Setup 6\iscc.exe`).

If they were intentionally removed, it is not a big issue for me in any case. The InnoSetup installation via Chocolatey takes about 20 seconds.

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

Version: 20211109.2
Failed build: https://dev.azure.com/fernandreu-public/OfficeRibbonXEditor/_build/results?buildId=1089&view=logs&j=7be880af-ba6b-5033-4ded-6c64e5dec773&t=2accc5c6-d489-5264-e1ae-e22b1c04d107

### Is it regression?

No (only respect to windows-2019)

### Expected behavior

The tool should be installed and available in `C:\Program Files (x86)\Inno Setup 6`

### Actual behavior

The tool does not seem to be installed

### Repro steps

Just add a task which uses Inno Setup, e.g.:

```
- script: "C:\Program Files (x86)\Inno Setup 6\iscc.exe" "$(Build.SourcesDirectory)/build/Installer/setup.iss"
```

**Comment by mikhailkoliada** [comment]
@fernandreu Hello!

Thanks, we will take a look.

**Comment by miketimofeev** [comment]
Hi @fernandreu!
Yes, we have removed this software intentionally assuming its low popularity and maintenance concerns. Please install innosetup in runtime as the installation is quite fast.
I'm going to close this issue. Please feel free to contact us if you have any concerns.
Thank you!
