### ISSUE TITLE
Update/Add Java OpenJDK

### ISSUE THREAD

**Issue by qkxc64** [actions/virtual-environments#4508]
### Tool name

Java

### Tool license

GNU GPL v2 with Classpath Exception

### Add or update?

- [X] Add
- [X] Update

### Desired version

Adoptium 11.0.13 and Eclipse Temurin 17.0.1

### Approximate size

182 MB & 182 MB

### Brief description of tool

Java OpenJDK

### URL for tool's homepage

https://adoptium.net/?variant=openjdk11 and https://adoptium.net/

### Provide a basic test case to validate the tool's functionality.

```bash
Adopdt OpenJDK is no longer maintained as it has been moved to the Eclipse Foundation hence it does not receive any security fixes.
```

### Virtual environments affected

- [X] Ubuntu 18.04
- [X] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Are you willing to submit a PR?

No

**Comment by mikhailkoliada** [comment]
Duplicate of https://github.com/actions/virtual-environments/issues/4085
