### ISSUE TITLE
Add Windows 10 SDK (10.0.14393.795) to Windows environments

### ISSUE THREAD

**Issue by riverar** [actions/virtual-environments#451]
- Tool name: Windows 10 SDK (10.0.14393.795)
- Add or update? Add
- Desired version: 10.0.14393.795
- Approximate size: 1.74GB
- If this is an add request:
  - Brief description of tool:
    Windows 10 SDK (10.0.14393.795) supports apps that target **[still supported](https://support.microsoft.com/en-nz/help/13853/windows-lifecycle-fact-sheet)** Windows 10 Enterprise 2016 LTSB and Windows 10 IoT Enterprise 2016 LTSB SKUs. 
  - URL for tool's homepage:
    https://developer.microsoft.com/en-us/windows/downloads/sdk-archive/

**Area for Triage**: .NET Framework
**Question, Bug, or Feature?**: Feature

**Virtual environments affected**
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [x] Windows Server 2016 R2
- [x] Windows Server 2019

**Can this tool be installed during the build?**
Yes. Installation requires ~**3 minutes**.

```powershell
Invoke-WebRequest -Method Get -Uri https://go.microsoft.com/fwlink/p/?LinkId=838916 -OutFile sdksetup.exe -UseBasicParsing
Start-Process -Wait sdksetup.exe -ArgumentList "/q", "/norestart", "/ceip off", "/features OptionId.WindowsSoftwareDevelopmentKit"
```

**Are you willing to submit a PR?**
Yes.

**Comment by riverar** [comment]
Any updates?

**Comment by maxim-lobanov** [comment]
@riverar, 
As I can see, component `Microsoft.VisualStudio.Component.Windows10SDK.14393` is installed on [Windows Server 2016](https://github.com/actions/virtual-environments/blob/master/images/win/Windows2016-Readme.md#visual-studio-2017-enterprise).
As for the Windows Server 2019, no plans or ETA right now.

**Comment by thejoebourneidentity** [comment]
Thanks for the suggestion @riverar , I think this is a good addition to the 2019 environment, and something that we should be consistent on across the Windows envs. @maxim-lobanov, @alepauly thinks we should go for i

**Comment by nikita-bykov** [comment]
We added Windows 10 SDK (10.0.14393.795) to Windows 2019. The image will be rolled out next week.

**Comment by nikita-bykov** [comment]
All changes were successfully deployed.
