### ISSUE TITLE
Update dotnet sdk 6.x

### ISSUE THREAD

**Issue by AClerbois** [actions/virtual-environments#4515]
### Tool name

dotnet 

### Tool license

https://dotnet.microsoft.com/download/dotnet

### Add or update?

- [ ] Add
- [X] Update

### Desired version

6.0.0

### Brief description of tool

Software Development kit to building and running .NET apps on Linux, macOS, and Windows. Runtimes, SDKs, and developer packs for .NET Framework, .NET, and ASP.NET.

### URL for tool's homepage

https://dotnet.microsoft.com/download/dotnet

### Provide a basic test case to validate the tool's functionality.

```bash
Create a new console application in .NET 6 via a CLI and check that the application compile.
```

### Virtual environments affected

- [X] Ubuntu 18.04
- [X] Ubuntu 20.04
- [X] macOS 10.15
- [X] macOS 11
- [X] Windows Server 2016
- [X] Windows Server 2019
- [X] Windows Server 2022

### Can this tool be installed during the build?

```bash
Yes, via the dotnet installer step toop
```

### Are you willing to submit a PR?

Yes

**Comment by miketimofeev** [comment]
Hi @AClerbois!
Take a look here, please https://github.com/actions/virtual-environments/issues/4424
Closing this one as a duplicate.
