### ISSUE TITLE
Generating the Ubuntu 20.04 image - kubernetes-tools.sh

### ISSUE THREAD

**Issue by aleqsss** [actions/virtual-environments#4516]
### Description

When trying to build the Ubuntu 20.04 image, with the [ubuntu2004.json Packer definition](https://github.com/actions/virtual-environments/blob/main/images/linux/ubuntu2004.json), the following error from the [kubernetes-tools.sh](https://github.com/actions/virtual-environments/blob/main/images/linux/scripts/installers/kubernetes-tools.sh) exits the build:

==> azure-arm: **Provisioning with shell script: C:\a\1\s\virtual-environments\images\linux/scripts/installers/kubernetes-tools.sh**
==> azure-arm:   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
==> azure-arm:                                  Dload  Upload   Total   Spent    Left  Speed
==> azure-arm: 100   655  100   655    0     0   2860      0 --:--:-- --:--:-- --:--:--  2860
==> azure-arm: 100   188  100   188    0     0    554      0 --:--:-- --:--:-- --:--:--   554
==> azure-arm: 100   188  100   188    0     0    415      0 --:--:-- --:--:-- --:--:--   415
==> azure-arm: 100 6660k  100 6660k    0     0  4197k      0  0:00:01  0:00:01 --:--:-- 8972k
==> azure-arm:   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
==> azure-arm:                                  Dload  Upload   Total   Spent    Left  Speed
==> azure-arm: 100   154  100   154    0     0   1294      0 --:--:-- --:--:-- --:--:--  1305
==> azure-arm: 100 44.7M  100 44.7M    0     0  69.1M      0 --:--:-- --:--:-- --:--:-- 86.6M
==> azure-arm:   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
==> azure-arm:                                  Dload  Upload   Total   Spent    Left  Speed
==> azure-arm: 100   188  100   188    0     0   1649      0 --:--:-- --:--:-- --:--:--  1649
==> azure-arm: bash: line 1: html: No such file or directory
==> azure-arm: bash: line 2: syntax error near unexpected token `<'
==> azure-arm: '

Using the [instructions from here](https://github.com/actions/virtual-environments/blob/main/docs/create-image-and-azure-resources.md), anyone else experiencing this?

Have tried several times, each time I get the same error.

Tested with both Packer version 1.7.7 and 1.7.8 (at the time of writing, the latest version).

### Virtual environments affected

- [ ] Ubuntu 18.04
- [X] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Whatever is in main, since using the [instructions from here](https://github.com/actions/virtual-environments/blob/main/docs/create-image-and-azure-resources.md).

### Expected behavior

Being able to generate the image via the provided Packer definition, and as per the [instructions](https://github.com/actions/virtual-environments/blob/main/docs/create-image-and-azure-resources.md) in the repo.

### Actual behavior

Failing at the **Provisioning with shell script: C:\a\1\s\virtual-environments\images\linux/scripts/installers/kubernetes-tools.sh** step.

### Repro steps

Build the Ubuntu 20.04 image, using the [instructions from here](https://github.com/actions/virtual-environments/blob/main/docs/create-image-and-azure-resources.md).

**Comment by mikhailkoliada** [comment]
@aleqsss Hello!

For the first glance it looks like one of your links were modified and rather than pipe a raw file to the bash interpreter you are piping a server-generated html file as no downloaded files in the script are consisting of anything with the html code/extensions.

**Comment by mikhailkoliada** [comment]
@aleqsss could you post your `kubernetes-tools.sh`?

**Comment by aleqsss** [comment]
Yes absolutely, any assistance is appreciated. 🙂

[kubernetes-tools.zip](https://github.com/actions/virtual-environments/files/7553561/kubernetes-tools.zip)

**Comment by aleqsss** [comment]
I'll close this issue now, since it seems to be connected with a temporary redirect, caused by our network security implementations.

Thank you for your time, effort and input in this matter @mikhailkoliada, much appreciated. 🙂
