### ISSUE TITLE
Update/Add .NET 6

### ISSUE THREAD

**Issue by nshenoy** [actions/virtual-environments#4517]
### Tool name

.NET 6

### Tool license

MIT

### Add or update?

- [X] Add
- [ ] Update

### Desired version

.NET 6 

### Brief description of tool

.NET 6 is now GA, but the latest version on the agents are .NET 5. 

### URL for tool's homepage

https://dotnet.microsoft.com/

### Virtual environments affected

- [X] Ubuntu 18.04
- [X] Ubuntu 20.04
- [X] macOS 10.15
- [X] macOS 11
- [X] Windows Server 2016
- [X] Windows Server 2019
- [X] Windows Server 2022

### Can this tool be installed during the build?

```bash
Yes. This can be installed via an additional line in each OS's `toolsetXXXX.json` under the `dotnet` section.
```

### Are you willing to submit a PR?

Yes

**Comment by miketimofeev** [comment]
Hi @nshenoy!
Take a look here, please #4424
Closing this one as a duplicate.
