### ISSUE TITLE
Update to Python 3.9.9

### ISSUE THREAD

**Issue by dgw** [actions/virtual-environments#4521]
### Tool name

Python

### Tool license

PSF license

### Add or update?

- [ ] Add
- [X] Update

### Desired version

3.9.9

### Virtual environments affected

- [X] Ubuntu 18.04
- [X] Ubuntu 20.04
- [X] macOS 10.15
- [X] macOS 11
- [X] Windows Server 2016
- [X] Windows Server 2019
- [X] Windows Server 2022

### Are you willing to submit a PR?

Yes, if I could figure out how

**Comment by dgw** [comment]
Further detail that didn't fit into the issue form: Python 3.9.8 broke some `argparse` behavior (a regression), and it is fixed in 3.9.9.

See azure/azure-cli#20269, sopel-irc/sopel#2210, and https://bugs.python.org/issue45235

**Comment by mikhailkoliada** [comment]
python3.9.9 is available via `setup-python` now.
It well be available in the images next week.

**Comment by mikhailkoliada** [comment]
Should be deployed now
