### ISSUE TITLE
Update/Add [tool name]

### ISSUE THREAD

**Issue by Jawz84** [actions/virtual-environments#4529]
### Tool name

.Net Core SDK

### Tool license

MIT license

### Add or update?

- [ ] Add
- [X] Update

### Desired version

6.0

### Approximate size

815MB installed size

### Virtual environments affected

- [ ] Ubuntu 18.04
- [X] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [ ] Windows Server 2022

**Comment by miketimofeev** [comment]
Hi @Jawz84!
Take a look here, please https://github.com/actions/virtual-environments/issues/4424
Closing this one as a duplicate.

**Comment by Jawz84** [comment]
Clear, thank you @miketimofeev using the github action instead!
👍
