### ISSUE TITLE
Add hci_vhci kernel module

### ISSUE THREAD

**Issue by mrquincle** [actions/virtual-environments#4532]
### Tool name

hci_vhci

### Tool license

GPL-2.0-or-later

### Add or update?

- [X] Add
- [ ] Update

### Desired version

no specific requirement

### Approximate size

28 kB

### Brief description of tool

This is the Bluetooth Virtual HCI device driver.
This driver is required if you want to use HCI Emulation software. 

### URL for tool's homepage

https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/tree/drivers/bluetooth/hci_vhci.c

### Provide a basic test case to validate the tool's functionality.

```bash
This is for example required for running the Bluetooth emulator within `bluez`:

    ./emulator/btvirt -L -U2

It would allow continuous integration tasks on Github Actions without actual Bluetooth hardware available and can potentially speed up lot's of projects that use Bluetooth.
```

### Virtual environments affected

- [ ] Ubuntu 18.04
- [X] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Can this tool be installed during the build?

```bash
No
```

### Are you willing to submit a PR?

Add virtual HCI device into the kernel or as module by typing Y or M (I'm not needed).

**Comment by mikhailkoliada** [comment]
@mrquincle Hello!

We are building our images on top of clean ubuntu/windows/macos and therefor are not responsible for managing the kernel and its subsystems at all. I think that the best course of actions for you is to ask the azure support to assist you with that.

I am going to close the issue now but feel free to ping us if you have more questions or concerns.

**Comment by mrquincle** [comment]
@mikhailkoliada I understand. If you have a concrete pointer to the team/repos where I can address someone w.r.t. this, that would be great. It's probably not even the team that's about the virtual machines themselves, but the team that's about the hardware on which it runs and the permissions of the VM on top of that hardware.

Just for my own reference, these are the loaded modules (`ubuntu-20.04`):
```
Module                  Size  Used by
xt_MASQUERADE          20480  1
nf_conntrack_netlink    49152  0
nfnetlink              16384  2 nf_conntrack_netlink
xfrm_user              36864  1
xfrm_algo              16384  1 xfrm_user
xt_addrtype            16384  2
iptable_filter         16384  1
iptable_nat            16384  1
nf_nat                 45056  2 iptable_nat,xt_MASQUERADE
br_netfilter           28672  0
bridge                249856  1 br_netfilter
stp                    16384  1 bridge
llc                    16384  2 bridge,stp
overlay               126976  0
binfmt_misc            24576  1
nls_iso8859_1          16384  1
dm_multipath           36864  0
scsi_dh_rdac           16384  0
scsi_dh_emc            16384  0
scsi_dh_alua           20480  0
xt_conntrack           16384  3
nf_conntrack          147456  4 xt_conntrack,nf_nat,nf_conntrack_netlink,xt_MASQUERADE
nf_defrag_ipv6         24576  1 nf_conntrack
nf_defrag_ipv4         16384  1 nf_conntrack
libcrc32c              16384  2 nf_conntrack,nf_nat
iptable_security       16384  1
xt_owner               16384  2
bpfilter               16384  0
crct10dif_pclmul       16384  1
crc32_pclmul           16384  0
ghash_clmulni_intel    16384  0
joydev                 24576  0
hid_generic            16384  0
aesni_intel           372736  0
crypto_simd            16384  1 aesni_intel
cryptd                 24576  2 crypto_simd,ghash_clmulni_intel
glue_helper            16384  1 aesni_intel
hid_hyperv             16384  0
hid                   122880  2 hid_hyperv,hid_generic
serio_raw              20480  0
pata_acpi              16384  0
hv_netvsc              86016  0
hyperv_fb              20480  1
cfbfillrect            16384  1 hyperv_fb
hyperv_keyboard        16384  0
cfbimgblt              16384  1 hyperv_fb
cfbcopyarea            16384  1 hyperv_fb
hv_balloon             32768  0
hv_utils               32768  1
sch_fq_codel           20480  3
msr                    16384  0
drm                   544768  0
drm_panel_orientation_quirks    20480  1 drm
i2c_core               90112  1 drm
ip_tables              32768  3 iptable_filter,iptable_security,iptable_nat
x_tables               49152  7 xt_conntrack,iptable_filter,iptable_security,xt_addrtype,xt_owner,ip_tables,xt_MASQUERADE
autofs4                45056  2
```

**Comment by vChavezB** [comment]
@mrquincle  did you manage to make it work?

A workaround at the moment for me is to use googles experimental software [bumble](https://github.com/google/bumble). It can create vhci interfaces but still require access from a host with bluetooth kernel enabled...
