### ISSUE TITLE
az keyvault logs out secret values on newest macOS image

### ISSUE THREAD

**Issue by Nasicus** [actions/virtual-environments#4535]
### Description

Since yesterday the following command prints out the value of the secret to the console / log statement of the build pipeline (which contains our passwords!). Seems to be related to the newest macos build, still works on older versions as before.

We have a bash script (`.sh`)  which looks like this:

```
vaultValue=$(az keyvault secret show --vault-name whatever --name "blabla" --query value --output tsv)
```

On the newest mac os image it now prints this to the console / log, whereas before it didn't print anything:

```
  "attributes": {
    "created": "2021-07-07T09:15:28+00:00",
    "enabled": true,
    "expires": null,
    "notBefore": null,
    "recoveryLevel": "Recoverable+Purgeable",
    "updated": "2021-07-07T09:15:28+00:00"
  },
  "contentType": null,
  "id": "https://whatever/secrets/blabla/someid",
  "kid": null,
  "managed": null,
  "name": "blabla",
  "tags": null,
  "value": "my-secret-value"
}
  "attributes": {
    "created": "2021-07-07T09:15:28+00:00",
    "enabled": true,
    "expires": null,
    "notBefore": null,
    "recoveryLevel": "Recoverable+Purgeable",
    "updated": "2021-07-07T09:15:28+00:00"
  },
  "contentType": null,
  "id": "https://whatever/secrets/blabla/someid",
  "kid": null,
  "managed": null,
  "name": "blabla",
  "tags": null,
  "value": "my-secret-value"
}

```

Note that I tried to reproeduce this locally with the same Azure CLI version and even also on MacOS but I couldn't.
See below in which MacOS image it still works as expected.

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [X] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Starting: Initialize job
Agent name: 'Hosted Agent'
Agent machine name: 'Mac-1637219675485'
Current agent version: '2.195.0'
Operating System
Virtual Environment
Environment: macos-11
Version: 20211114.1
Included Software: https://github.com/actions/virtual-environments/blob/macOS-11/20211114.1/images/macos/macos-11-Readme.md
Image Release: https://github.com/actions/virtual-environments/releases/tag/macOS-11%2F20211114.1
Virtual Environment Provisioner
Current image version: '20211114.1'
Agent running as: 'runner'
Prepare build directory.
Set build variables.
Download all required tasks.
Downloading task: DownloadBuildArtifacts (0.194.0)
Downloading task: AzureCLI (1.164.0)
Downloading task: DownloadSecureFile (1.193.0)
Downloading task: CmdLine (2.182.0)
Downloading task: AppCenterDistribute (3.186.0)
Checking job knob settings.
   Knob: AgentToolsDirectory = /Users/runner/hostedtoolcache Source: ${AGENT_TOOLSDIRECTORY} 
Finished checking job knob settings.
Start tracking orphan processes.
Finishing: Initialize job

### Is it regression?

Works on 20211106.1

### Expected behavior

Do not print gotten secret to the console

### Actual behavior

Prints secret to the console

### Repro steps

See description above.

**Comment by mikhailkoliada** [comment]
@Nasicus Hello!

I am pretty sure azure-cli's version has not changed in the version of the image you referenced ([changelog](https://github.com/actions/virtual-environments/commit/01570219dae48676fee5b295dcef94bcd409bc1d)).

Could you please try to downgrade azure-cli manually in order to make sure you can repeat the problem?

**Comment by Nasicus** [comment]
@mikhailkoliada 
Thanks for you reply.
I know it didn't change. I upgraded to the same az cli version locally (on my mac) and there it works as expected.
On the other mac os agent where it works it also has the same az cli version - the only difference I can see is the image version.
Here are all the information from the working macos image:

```
Starting: Initialize job
Agent name: 'Hosted Agent'
Agent machine name: 'Mac-1637218096416'
Current agent version: '2.195.0'
Operating System
Virtual Environment
Environment: macos-11
Version: 20211106.1
Included Software: https://github.com/actions/virtual-environments/blob/macOS-11/20211106.1/images/macos/macos-11-Readme.md
Image Release: https://github.com/actions/virtual-environments/releases/tag/macOS-11%2F20211106.1
Virtual Environment Provisioner
1.0.0.0-master-20211108-1
Current image version: '20211106.1'
Agent running as: 'runner'
Prepare build directory.
Set build variables.
Download all required tasks.
Downloading task: Bash (3.189.0)
Downloading task: AzureCLI (1.164.0)
Downloading task: DownloadBuildArtifacts (0.194.0)
Downloading task: CopyFiles (2.190.1)
Downloading task: NodeTool (0.192.0)
Downloading task: Npm (1.187.0)
Downloading task: CocoaPods (0.189.0)
Downloading task: CmdLine (2.182.0)
Downloading task: CopyPublishBuildArtifacts (1.0.32)
Downloading task: AddTag (0.90.3)
Checking job knob settings.
   Knob: AgentToolsDirectory = /Users/runner/hostedtoolcache Source: ${AGENT_TOOLSDIRECTORY} 
Finished checking job knob settings.
Start tracking orphan processes.
Finishing: Initialize job

```

**Comment by al-cheb** [comment]
@Nasicus , I can't reproduce from my side:

```
 Environment: macos-11
  Version: 20211114.1
  Included Software: https://github.com/actions/virtual-environments/blob/macOS-11/20211114.1/images/macos/macos-11-Readme.md
  Image Release: https://github.com/actions/virtual-environments/releases/tag/macOS-11%2F20211114.1
```
![image](https://user-images.githubusercontent.com/47745270/142462095-f90f0e90-5152-48d6-a353-042e41afd7a7.png)

**Comment by Nasicus** [comment]
@al-cheb hmm damn... I have no idea what to do then, because we didn't change anything in the pipeline and it literally fails in the SAME pipeline in different stages....

**Comment by Nasicus** [comment]
@al-cheb  wait: in your first screenshot, I think that's already strange, becuase the `vaultValue` should only contain the `Hello` and not everything....  => I think that's exactly what's going wrong / has changed!

maybe I should add that after getting the vaultValue we do something liek this:

```
echo "##vso[task.setvariable variable=$1]$value"
```

**Comment by al-cheb** [comment]
@Nasicus , it's a bug - https://github.com/Azure/azure-cli/issues/20348. Temporary workaround use jq:
```
vaultValue=$(az keyvault secret show --vault-name ghtest --name "test" --output json | jq -r '.value')
echo $vaultValue
```

![image](https://user-images.githubusercontent.com/47745270/142475842-4897bb5a-4315-480d-aba5-1c8b86a16c55.png)

**Comment by Nasicus** [comment]
@al-cheb Thanks for your help! 
Your workaround also worked!

**Comment by al-cheb** [comment]
@Nasicus , The new version with Python 3.10.0 has been deployed.
![image](https://user-images.githubusercontent.com/47745270/143288532-8814d0b0-318b-4aea-9509-c3ed9ce8337a.png)
