### ISSUE TITLE
Azure CLI (azure-devops) 0.22.0 installed on Ubuntu1804

### ISSUE THREAD

**Issue by tranguyen221** [actions/virtual-environments#4539]
### Description

In essence, we are running some ADO pipelines with an AML service connection to execute some code in an AML workspace. But in the past few days, we were getting this error:

The latest version of az cli (2.30.0) break while running az commands [link](https://github.com/microsoft/dstoolkit-mlops-base/issues/47)

It seems to be a wider problem that has started occurring a few days ago and it also reported in azure-cli [issue](https://github.com/Azure/azure-cli/issues/20297)

We created a temporary fixed by downgrading the version of azure cli to 2.29.2. This fix was working but today we have another issue:

**The 'azure-devops' extension version 0.22.0 is not compatible with your current CLI core version 2.29.2.
This extension requires a min of 2.30.0 CLI core._**

It seems to me that there was an upgrade of azure devops version in ubuntu 18:04 because the previous one is **[0.21.0](https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu1804-README.md)** And the bug in Azure CLI 2.30.0 is still there, should we downgrade the azure devops version?

### Virtual environments affected

- [X] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

NA

### Expected behavior

azure devops version 0.21.0 installed in ubuntu 18:04

### Actual behavior

azure devops version 0.22.0 installed in ubuntu 18:04

### Repro steps

This was initially discussion of azure cli error in the version 2.30.0 here: [https://github.com/Azure/azure-cli/issues/20297](https://github.com/Azure/azure-cli/issues/20297)

**Comment by mikhailkoliada** [comment]
@tranguyen221 Hello!

Thanks, we will take a look.

**Comment by mikhailkoliada** [comment]
@tranguyen221 azure-cli devops [got updated](https://github.com/actions/virtual-environments/commit/152addc1c7badc3f970bfa254d09b37fb7960730#) this week, so you indeed want to downgrade if you are still using older cli-core. We can not downgrade it due to the weekly nature of the releases.

Feel free to ping us if you have more questions.

**Comment by MurugeswariMuthurajan** [comment]
Hi @tranguyen221 Can you please let me know how did you downgraded the azure devops version

**Comment by tranguyen221** [comment]
> Hi @tranguyen221 Can you please let me know how did you downgraded the azure devops version

Hi @MurugeswariMuthurajan, I'm using this cmd to downgrade the azure devops version

az extension remove --name azure-devops
az extension add --name azure-devops --version 0.21.0

**Comment by MurugeswariMuthurajan** [comment]
@tranguyen221 Thanks much Tranguyen :)
