### ISSUE TITLE
Update/Add [knockd]

### ISSUE THREAD

**Issue by moiseslodeiro** [actions/virtual-environments#454]
**Tool information**
- Tool name: knockd
- Add or update? Add
- Desired version: latest
- Approximate size: 
- If this is an add request:
  - Brief description of tool: Port knocking is a simple method to grant remote access without leaving a port constantly open. This preserves your server from port scanning and script kiddie attacks.
  - URL for tool's homepage: https://help.ubuntu.com/community/PortKnocking

**Area for Triage**:
Containers

**Question, Bug, or Feature?**:
Feature

**Virtual environments affected**
- [ ] macOS 10.15
- [x] Ubuntu 16.04 LTS
- [x] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Can this tool be installed during the build?**
Not too much

**Are you willing to submit a PR?**
Yes, why not!

**Comment by maxim-lobanov** [comment]
Tool can be installed in runtime using the following script:
```
sudo apt-get install knockd -y
```
Installation takes about 7 seconds

**Comment by thejoebourneidentity** [comment]
Thanks for your suggestion, @moiseslodeiro. Considering how quick it is to install during your run, this is not something we will add to the image at this time.
