### ISSUE TITLE
Introduce $COMMIT_RANGE (simmilar to $TRAVIS_COMMIT_RANGE)

### ISSUE THREAD

**Issue by jjangga0214** [actions/virtual-environments#455]
Hi, I'm actually not sure if this feature request should be here. 
Please let me(and others) know where to forward if needed.  

**Feature Request**

I think providing an env var like `$COMMIT_RANGE` would be possible. For example, Travis provides `$TRAVIS_COMMIT_RANGE`, which is the range of commits that were included in the push or pull request. 

This would be very handy for incremental lint. For example,
```bash
eslint $(git diff --name-only --diff-filter=d $COMMIT_RANGE | egrep '\.(js|ts)$')
```
would run eslint only for modified .js or .ts files from the last push. 

P.S. For forks who want to know what the example command means,
- `--name-only` option only list filename, not content.
- `--diff-filter=d` does not list deleted files. 
- `egrep '\.(js|ts)$'` filters only files with `.js` or `.ts` extension.

_Workaround 1._

Just naively compare origin/master with HEAD of current branch.

```bash
eslint $(git diff --name-only --diff-filter=d origin/master HEAD | egrep '\.(js|ts)$')
```

_Workaround 2._

Record the last pused commit SHA into the cache, and restore it(e.g. `$THE_LAST_COMMIT`) in every push and run 

```bash
eslint $(git diff --name-only --diff-filter=d $THE_LAST_COMMIT HEAD | egrep '\.(js|ts)$')
```
But this is somewhat inconvenient.

**Advanced Feature Request**

Introduce `$COMMIT_RANGE_UNPASSED`, which is a commit range from the last success(pass every executed jobs with exit code 0) push. 
This would be useful for this scenario, for example.

1. Someone pushes files.
2. Lint is failed.
3. The one has some other priority, so does not fix the file for now.
4. The one makes some changes on other files, and pushes it.

In this case, if lint is configured to run only against `$COMMIT_RANGE`, then this time the lint would be passed, even though the previously failed file is not fixed. So, one might want to lint against `$COMMIT_RANGE_UNPASSED`, so make sure the lint is failed again. This can be useful to remind there's a file to fix later. 

**Question, Bug, or Feature?**:

Feature
**Virtual environments affected**
- [x] macOS 10.15
- [x] Ubuntu 16.04 LTS
- [x] Ubuntu 18.04 LTS
- [x] Windows Server 2016 R2
- [x] Windows Server 2019

**Can this tool be installed during the build?**

If we record the last pused commit into cache, it possible, but inconvenient.

**Are you willing to submit a PR?**

If applicable.

**Comment by miketimofeev** [comment]
@jjangga0214 thanks for your suggestion. I believe the issue should be created here https://github.com/actions/runner/issues

**Comment by jjangga0214** [comment]
@miketimofeev Thanks! 
I made the same issue https://github.com/actions/runner/issues/342.
Closing this issue.
