### ISSUE TITLE
Support for .net 6 for Ubuntu 18/20 hosted agent images

### ISSUE THREAD

**Issue by mgardi85** [actions/virtual-environments#4556]
### Description

.Net 6 is  GA now. However only Win-Server 2022 images have it pre-installed.
The Ubuntu images should have it pre-installed as well as Windows -2019 images.

### Virtual environments affected

- [X] Ubuntu 18.04
- [X] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [X] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops&tabs=yaml

### Is it regression?

No

### Repro steps

The images do not have .Net 6 SDK pre-installed as per the listing available at 
https://github.com/actions/virtual-environments/blob/main/images/win/Windows2019-Readme.md
https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-README.md
https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu1804-README.md

**Comment by dibir-magomedsaygitov** [comment]
Hi @mgardi85 !
Take a look here, please [#4424](https://github.com/actions/virtual-environments/issues/4424)
Closing this one as a duplicate.

**Comment by mgardi85** [comment]
@dibir-magomedsaygitov The workaround works but it also hides all the other .Net Code SdKs. Some extensions have dependency on previous version  (Eg SonarQube ) and by using the "UseDotNet@2" task in ADO pipeline ,  other extensions are failing.

It would also enforce that all code is moved to .Net 6 which may not work for everyone as transition/ upgrade are generally longer process

**Comment by miketimofeev** [comment]
@mgardi85 you can install any number of .net versions you need in runtime. Please take a look at this comment
https://github.com/actions/virtual-environments/issues/4424#issuecomment-983905101
