### ISSUE TITLE
Include SSIS DevOps Tool (stand alone version) to Windows builds

### ISSUE THREAD

**Issue by bnippercg** [actions/virtual-environments#4567]
### Tool name

SSIS DevOps Tool

### Tool license

MICROSOFT SOFTWARE LICENSE TERMS

### Add or update?

- [X] Add
- [ ] Update

### Desired version

Current

### Brief description of tool

The stand-alone tool available at the homepage of the URL which allows for building and deploying SSIS

### URL for tool's homepage

https://docs.microsoft.com/en-us/sql/integration-services/devops/ssis-devops-standalone?view=sql-server-ver15

### Provide a basic test case to validate the tool's functionality.

```bash
Install the tool and build an SSIS package to produce an ispac file.
```

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [X] Windows Server 2019
- [ ] Windows Server 2022

### Can this tool be installed during the build?

```bash
Yes
```

### Tool installation time in runtime

3 seconds

### Are you willing to submit a PR?

I don't know how just yet, but I'll try to learn quickly.

**Comment by MaksimZhukov** [comment]
Hello @bnippercg !
Considering fast installation time in runtime and maintenance concerns we would not like to add this tool to the images.

Please use the following snippet to install it in runtime:
```
$url = "https://aka.ms/SSISDevOpsTools"
(New-Object System.Net.WebClient).DownloadFile($url, ".\SSISDevOpsTools.exe") 
.\SSISDevOpsTools.exe /Q /C /T:${env:TEMP}
```

I'm going to close the issue, but feel free to contact us if you have any concerns.
Thank you!

**Comment by bnippercg** [comment]
Thank you @MaksimZhukov
