### ISSUE TITLE
Add Gulp to windows-2022 image

### ISSUE THREAD

**Issue by lukepuplett** [actions/virtual-environments#4577]
### Tool name

Gulp

### Tool license

MIT

### Add or update?

- [X] Add
- [ ] Update

### Desired version

latest

### Brief description of tool

Gulp is a popular client-side build system for front-end development.

### URL for tool's homepage

https://gulpjs.com

### Provide a basic test case to validate the tool's functionality.

On a machine with Node and NPM installed.

In a new, empty folder called GulpCheck...

- Run `npm init`, enter `gulp-check` as the name and accept all defaults.
- Run `npm install gulp --save-dev`
- Run `npm install gulp-cli --save-dev`
- Run `touch gulpfile.js`
- Run `node node_modules/gulp-cli/gulp.js`

You should see something like this emitted.

```
[12:00:36] Using gulpfile ~/Documents/Git/GulpCheck/gulpfile.js
[12:00:36] Task never defined: default
[12:00:36] To list available tasks, try running: gulp --tasks
```
Gulp is working and successfully finds nothing to do.

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Can this tool be installed during the build?

The developer must add `"gulp": "^4.0.2"` and `"gulp-cli": "^2.3.0"` to their `package.json` and then run `npm install` during the build.

Note that to install it on the build server requires running `npm install --global gulp` from a command prompt logged in as the same user that builds are run as. This is because, on Windows, NPM installs global stuff to the user profile.

But the reason I think it should be considered for global install is because

a) Azure Pipelines has a Gulp Task that doesn't work without it, and it seems odd to have official tasks that don't work out the box.

b) I think it used to be installed on the old Windows VS 2017 image because I only had a problem with Gulp when I moved to the windows-2022 image.

Perhaps there was good reason not to include it this time, or perhaps it worked on the old image for some other reason.

It's absence has cause noise elsewhere, see https://github.com/MicrosoftDocs/azure-devops-docs/issues/11651

I do not think this is a must-have since it can be installed via NPM. It's for your consideration.

### Tool installation time in runtime

20 seconds?

### Are you willing to submit a PR?

No. I don't really know how to use GitHub and do PRs. I have tried to learn but I'm sooo busy learning myriad other things that I don't use it and forget.

**Comment by miketimofeev** [comment]
@lukepuplett thanks for the provided points. It makes sense to pre-install gulp to windows-2022. We will take care of it.

**Comment by nikolai-frolov** [comment]
Hello. Changes were deployed, Gulp tool should be available on Windows 2022.
