### ISSUE TITLE
[SECURITY] Update Go versions to the latest minor versions for Ubuntu virtual environments

### ISSUE THREAD

**Issue by tjanez** [actions/virtual-environments#458]
**Tool information**
- Tool name: Go
- Add or update? Update
- Desired version: _See below_
- Approximate size: 

**Bug**:

As I noted in https://github.com/actions/setup-go/issues/39#issuecomment-590754775, all minor revisions of installed Go versions, e.g. [in Ubuntu 18.04 image]((https://github.com/actions/virtual-environments/blob/51d02f26f42e53bb963bb6bc9754501b28a3d2ba/images/linux/scripts/installers/1804/go.sh#L32-L34)), are out-dated:
- Go 1.11 (installed version: 1.11.12, latest version: 1.11.13)
- Go 1.12 (installed version: 1.12.7, latest version: 1.12.17)
- Go 1.13 (installed version: 1.13, latest version: 1.13.8)

All never minor releases of the respective Go versions contain fixes for security vulnerabilities, so this becomes a security issue.

**Virtual environments affected**

- [ ] macOS 10.15
- [x] Ubuntu 16.04 LTS
- [x] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

_NOTE: I didn't check the versions of Go in macOS or Windows virtual environments._

**Can this tool be installed during the build?**

Yes, using the [setup-go](https://github.com/actions/setup-go/) action, but it takes an order of magnitude more time than using a pre-installed version.

See https://github.com/actions/setup-go/issues/39 for details.

**Are you willing to submit a PR?**

Yes, it should be a trivial change, e.g. for Ubuntu 18.04, to:
https://github.com/actions/virtual-environments/blob/51d02f26f42e53bb963bb6bc9754501b28a3d2ba/images/linux/scripts/installers/1804/go.sh#L32-L34

**Comment by dmitry-shibanov** [comment]
Hello, thank you for your response. We updated default go version to the 1.14 (the latest actual  stable version) and patch versions to the latest (1.11.13, 1.12.17, 1.13.8, 1.14). Changes will be deployed to the next images rollout.

Note: @alepauly , Please pay attention, that we have improved Go installation logic so we don't need to maintain patch version manually, the latest one will be consumed automatically.

**Comment by tjanez** [comment]
> Hello, thank you for your response. We updated default go version to the 1.14 (the latest actual stable version) and patch versions to the latest (1.11.13, 1.12.17, 1.13.8, 1.14). Changes will be deployed to the next images rollout.

Great, thanks for fixing this!

> Note: @alepauly , we have improved Go installation logic so we don't need to maintain patch version manually, the latest one will be consumed automatically.

This is a very good improvement since automation will prevent Go versions being outdated :+1:.

**Comment by tjanez** [comment]
I see that the [Ubuntu 1804 (20200316 update)](https://github.com/actions/virtual-environments/releases/tag/ubuntu18%2F20200316.1) release already contains all updated Go versions, so I'm closing this issue.
