### ISSUE TITLE
Add Microsoft Installer Projects to VS 2022 on windows-2022

### ISSUE THREAD

**Issue by BartokW** [actions/virtual-environments#4580]
### Tool name

Microsoft Visual Studio Installer Projects 2022

### Tool license

N/A

### Add or update?

- [ ] Add
- [ ] Update

### Desired version

latest

### Brief description of tool

Allows compiling MS Installer Projects in Visual Studio

### URL for tool's homepage

https://marketplace.visualstudio.com/items?itemName=VisualStudioClient.MicrosoftVisualStudio2022InstallerProjects

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [X] Windows Server 2022

**Comment by dibir-magomedsaygitov** [comment]
Hello @BartokW. Thank you for your request. Could you please clarify the name of Microsoft Installer Projects Addon component in [VS](https://docs.microsoft.com/en-us/visualstudio/install/workload-component-id-vs-enterprise?view=vs-2022&preserve-view=true)?

**Comment by miketimofeev** [comment]
@BartokW we will take a look if it can be installed in runtime and then decide whether we should add it to the image or not.

**Comment by V-Zabayrachny** [comment]
Hello @BartokW. We will add the extension in the next week's image, but for now, you can use the following Powershell snippet to install the vsix in runtime (it takes about 5 minutes):
```pwsh
$vsixPackage= "VisualStudioClient.MicrosoftVisualStudio2022InstallerProjects"
$vsixPackageUrl = Get-VsixExtenstionFromMarketplace -ExtensionMarketPlaceName $vsixPackage
$FilePath = Start-DownloadWithRetry -Url $vsixPackageUrl.DownloadUri -Name $vsixPackage.FileName
$argumentList = ('/quiet', "`"$FilePath`"")
Start-Process -FilePath "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\VSIXInstaller.exe" -ArgumentList $argumentList -Wait -PassThru
```

**Comment by V-Zabayrachny** [comment]
@BartokW We have deployed the image with this improvement.
