### ISSUE TITLE
Update/Add ngrok

### ISSUE THREAD

**Issue by russorat** [actions/virtual-environments#4583]
### Tool name

ngrok

### Tool license

ngrok, Inc.

### Add or update?

- [X] Add
- [ ] Update

### Desired version

2.3.40

### Approximate size

29M

### Brief description of tool

ngrok allows you to quickly create reverse proxy tunnels to access services remotely. It can be used to open secure ssh connections for debugging and previewing what's happening during a running action.

### URL for tool's homepage

https://ngrok.com/

### Provide a basic test case to validate the tool's functionality.

```bash
ngrok -v
ngrok http 80
```

### Virtual environments affected

- [X] Ubuntu 18.04
- [X] Ubuntu 20.04
- [X] macOS 10.15
- [X] macOS 11
- [X] Windows Server 2016
- [X] Windows Server 2019
- [X] Windows Server 2022

### Can this tool be installed during the build?

Download instructions here: https://ngrok.com/download

Ubuntu: 
```bash
curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc > /dev/null && echo "deb https://ngrok-agent.s3.amazonaws.com buster main" | sudo tee /etc/apt/sources.list.d/ngrok.list && sudo apt update && sudo apt install ngrok
```              
MacOS: `brew install ngrok/ngrok/ngrok`
Windows: `choco install ngrok`

### Tool installation time in runtime

< 5s

### Are you willing to submit a PR?

yes

**Comment by MaksimZhukov** [comment]
Hi @russorat! Thank you for the request!
Considering insignificant installation time in runtime and maintenance concerns we would not like to add the tool to the image. Please use the commands you attached to install the tool in runtime.

I'm going to close the issue, but feel free to contact us if you have any concerns.
Thank you!
