### ISSUE TITLE
WIX 3 Build errors in Image version 20211122.1 (works in 20211110)

### ISSUE THREAD

**Issue by KlausLinzner** [actions/virtual-environments#4591]
### Description

On our Azure Devops hosted agents we're now getting some builds queued to image https://github.com/actions/virtual-environments/releases/tag/win19%2F20211122.1 - and in there we're getting errors with WIX 3:

`Error MSB4019: The imported project "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\WiX\v3.x\Wix.targets" was not found. Confirm that the expression in the Import declaration "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\WiX\v3.x\Wix.targets" is correct, and that the file exists on disk.`

Several other builds are still queued to image version 20211110  - in there it's still working.

* Could you please look into this issue and fix it in the image?
* Is there are a way we can (temporarily) pin a specific image version?

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [X] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

20211122.1

### Is it regression?

20211110

### Expected behavior

build should work (sorry for short description). Let me know if you need sample code

### Actual behavior

Error MSB4019: The imported project "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\WiX\v3.x\Wix.targets" was not found. Confirm that the expression in the Import declaration "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\WiX\v3.x\Wix.targets" is correct, and that the file exists on disk.

### Repro steps

Should be any build with WIX references

**Comment by al-cheb** [comment]
@KlausLinzner , Please check https://github.com/actions/virtual-environments/issues/4419.
