### ISSUE TITLE
Wix.CA.targets was not found in Visual Studio installation path

### ISSUE THREAD

**Issue by nmaheshkumarkalahasti** [actions/virtual-environments#4597]
### Description

Getting the error when trying to build wix solutions
Error MSB4019: The imported project "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\WiX\v3.x\Wix.CA.targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [X] Windows Server 2016
- [X] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Version: 20211122.1

### Is it regression?

Yes

### Expected behavior

Wix projects should be compiled successfully

### Actual behavior

Error MSB4019: The imported project "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\WiX\v3.x\Wix.CA.targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.

### Repro steps

Getting the error when trying to build wix solutions.
1. Using Azure Hosted Pipelines with Windows 2019 agent (Version: 20211122.1) results in MSB4019.
2. Was compiling successfully on Version : 20211110.1.

**Comment by al-cheb** [comment]
@nmaheshkumarkalahasti , Workaround and duplicate https://github.com/actions/virtual-environments/issues/4419

**Comment by nmaheshkumarkalahasti** [comment]
MSBuildExtensionsPath32 is set to "C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild" instead of "C:\Program Files (x86)\MSBuild any idea why?
