### ISSUE TITLE
WiX Projects Build Failure using 2019 Image

### ISSUE THREAD

**Issue by chrpai** [actions/virtual-environments#4606]
### Description

Our build last ran successfully on Wednesday 12/24 @ 12:20AM using  Current image version: '20211110.1'

Suddenly our build started failing on Wednesday 12/24 @ 12:52AM using Current image version: '20211122.1' 

Our error message is:

Error MSB4019: The imported project "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\WiX\v3.x\Wix.targets" was not found. Confirm that the expression in the Import declaration "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\WiX\v3.x\Wix.targets" is correct, and that the file exists on disk.

It would appear the WiX VS (Votive) Extension for VS2019 is not installed or not installed correctly.

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [X] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Our build last ran successfully on Wednesday 12/24 @ 12:20AM using  Current image version: '20211110.1'

Suddenly our build started failing on Wednesday 12/24 @ 12:52AM using Current image version: '20211122.1' 

### Is it regression?

yes

### Expected behavior

The project should be found and I should be able to build WiX projects.

### Actual behavior

The project is not found.

### Repro steps

Create a pipeline that builds a solution containing a WiX project.

**Comment by dibir-magomedsaygitov** [comment]
Hello @chrpai. Thank you for your report. Please take a look at #4419. Closing this issue as a duplicate.

**Comment by chrpai** [comment]
@dibir-magomedsaygitov I don't see how this is a dupe.  All those comments over there should be over here.    A change to add Votitve to VS2022 shouldn't break VS2019.

Reading through the image readme.md file I can see the components are no longer installed.  This was never announced and is a regression.   Every single customer who builds WiX is going to be affected and it's not right to say they need to update all their import statements to keep building when it was building before.
