### ISSUE TITLE
Add previous versions of macOS

### ISSUE THREAD

**Issue by kieran-rigby-focusrite** [actions/virtual-environments#461]
**Tool information**
- Tool name: macOS
- Add or update? One or even two previous versions of macOS
- Desired version: 10.14, 10.13

 
**Area for Triage**:

 
**Question, Bug, or Feature?**: Feature

**Background**:
We are evaluating GitHub Enterprise as a possible solution for our business, and have noticed that GitHub Actions currently only supports 10.15 with Xcode 11 on your macOS nodes. 

This [comment](https://github.com/actions/virtual-environments/issues/53#issuecomment-549954507) suggests that at this point in time, you don't have enough resources to support multiple versions of macOS.

For stability reasons, our policy is to base our build jobs on the previous macOS version (e.g. currently we're using 10.14).

Are you planning to provide previous versions in the future? If so, do you have a timeframe in mind which you could share with us?

**Comment by Croydon** [comment]
Azure Pipelines and GitHub actions start to use the same images. AZP has/had older images, but they start removing them step-by-step https://devblogs.microsoft.com/devops/removing-older-images-in-azure-pipelines-hosted-pools

Unfortunately, I think they won't add older images

**Comment by maxim-lobanov** [comment]
Hello,
As for the Azure DevOps, it uses approach to support two latest versions of macOS (10.14 and 10.15 for now). 10.13 is deprecating because 10.15 was added recently.
As for the Actions, I think @alepauly , @thejoebourneidentity can share any thoughts.

**Comment by alepauly** [comment]
@kieran-rigby-focusrite We are not planning to add previous versions at this time, like all plans this could change but probably not in the short term. Thanks for bringing it up.

**Comment by kcgen** [comment]
I understand the plan is to run the latest OS from Apple. 

As of today, Apple supports 10.13, 10.14, and 10.15. Therefore, GitHub projects building macOS release binaries should (ideally) provide binaries compatible with these as well.

This can be achieved on on Catalina, if these corresponding SDKs were available on the  GitHub VM, which would let CI build targets use variable like these:

This would allow projects building on Catalina to set the following Clang variables:
 - `SDK="-w -isysroot /opt/SDKs/MacOSX10.13.sdk -mmacosx-version-min=10.13"`, or
 - `SDK="-w -isysroot /opt/SDKs/MacOSX10.14.sdk -mmacosx-version-min=10.13"`, or
 - `SDK="-w -isysroot /opt/SDKs/MacOSX10.15.sdk -mmacosx-version-min=10.13"`, or

Which, when appended to CPPFLAGS, CXXFLAGS, and CFLAGS will produce binaries that are compatible with 10.13 through 10.15.

Can these SDKs (specifically, only those for Apple's supported range of OS versions) be added to the Catalina CI VM?

**Comment by maxim-lobanov** [comment]
@kcgen , I think 3 latest versions for now are 10.14, 10.15, 11.0
Hosted GitHub images provide 3 latest SDK versions on Catalina image. They are distributed with different Xcode versions. See https://github.com/actions/virtual-environments/blob/main/images/macos/macos-10.15-Readme.md#installed-sdks for details

**Comment by kcgen** [comment]
Thank you for the correction and pointer to the documentation @maxim-lobanov!

**Comment by Nightwalker-87** [comment]
@alepauly Could you please reconsider to support at least **macOS 10.14** ?
It is the last macOS system to support 32-bit binaries, which adds more significance this approach in terms of compatibility.
This may also leave certain users remaining on that specific version, if the run software does not see any chance of being rewritten for 64-bit. I can't identify a great effort on doing so. However I'd agree on not to support earlier versions though.
