### ISSUE TITLE
Add AzureAD PowerShell Module to Windows and Linux images

### ISSUE THREAD

**Issue by ksaffarian** [actions/virtual-environments#4621]
### Tool name

AzureAD PowerShell Module

### Tool license

Apache License

### Add or update?

- [X] Add
- [ ] Update

### Desired version

Stable (most recent, 2.0.2.140)

### Brief description of tool

This is one of the common modules that are needed when dealing with Azure Active Directory. It is used to run recurring tasks (using Azure Pipelines) for Azure AD and having it as part of the base image will get things much faster;
- I don't see any complication of adding this to Windows or Linux managed agents
- It takes the load off the PSGallery website to download the module in every job
- It will decrease the run-time of the job and releases agents to the pool faster

### URL for tool's homepage

https://www.powershellgallery.com/packages/AzureAD/2.0.2.140

### Provide a basic test case to validate the tool's functionality.

```bash
You should be able to find commands like this after the module is installed:
- Get-AzureADCurrentSessionInfo
- Connect-AzureAD
```

### Virtual environments affected

- [X] Ubuntu 18.04
- [X] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [X] Windows Server 2019
- [X] Windows Server 2022

### Are you willing to submit a PR?

I can try :)

**Comment by shilovmaksim** [comment]
Hi @ksaffarian. Could you please change title of the request to include tool you want to add to the image.

**Comment by ksaffarian** [comment]
May I know what is the next step about this request?

**Comment by shilovmaksim** [comment]
@ksaffarian, we will think about adding AzureAD PowerShell Module to the images and will let you know.

**Comment by MaksimZhukov** [comment]
Hello @ksaffarian! Thank you for the request!
Have you considered using Microsoft Graph instead of Azure AD? It looks like the Azure AD PowerShell module will reach EOL in 2022 in favor of Microsoft Graph. Please see the details [here](https://techcommunity.microsoft.com/t5/azure-active-directory-identity/automate-and-manage-azure-ad-tasks-at-scale-with-the-microsoft/ba-p/1942489)

**Comment by ksaffarian** [comment]
Thanks for the good point @MaksimZhukov 
We will look into using Graph SDK.
Can you confirm if that is included in the OS images?

**Comment by MaksimZhukov** [comment]
The Microsoft Graph module is preinstalled on [Windows images](https://github.com/actions/virtual-environments/blob/main/images/win/Windows2022-Readme.md#powershell-modules).

**Comment by ksaffarian** [comment]
I think we can close this issue for now;
Thanks for the help :)
