### ISSUE TITLE
GitHub Actions has encountered an internal error when running your job.

### ISSUE THREAD

**Issue by dave99galloway** [actions/virtual-environments#4627]
### Description

intermittent failure running a job that calls another workflow

1st job runs ok and sets output variables for input to the called workflow ok, but then the called workflow failsto start with only this 👎 
`GitHub Actions has encountered an internal error when running your job.`

this is in around 50% of attempts, with no changes to either workflow yml in between

### Virtual environments affected

- [ ] Ubuntu 18.04
- [X] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

https://github.com/actions/virtual-environments/releases/tag/ubuntu20%2F20211122.1

https://github.com/monek-ltd/odin-e2e-test/runs/4352385000?check_suite_focus=true

### Expected behavior

workflow to run and provide some useful output!

### Actual behavior

`GitHub Actions has encountered an internal error when running your job.`

### Repro steps

trigger workflow manually as per https://github.com/dave99galloway/github-actions-issues/actions/runs/1516395849

I have a calling workflow https://github.com/dave99galloway/github-actions-issues/blob/main/.github/workflows/main.yml which loads some variables from a file https://github.com/dave99galloway/github-actions-issues/blob/main/.github/workflows/example.env in job 

the variables are loaded and echoed
print GITHUB_ENV at end
REASON=Test
FOO=RequiredString
BAR=OptionalString
BAZ=True

in the check variables step, the variables are checked

REASON:  Test
FOO:  RequiredString 
BAR: OptionalString 
BAZ:  True 

and in job completion, all variables have been set ok

Evaluate and set job outputs
Set output 'FOO'
Set output 'BAR'
Set output 'BAZ'
Set output 'REASON'

as per the original issue inthe original repo, the called workflow fails with no helpful info:-

Calling workflow : .github#L1GitHub Actions has encountered an internal error when running your job.

TIA

**Comment by shilovmaksim** [comment]
Hi @dave99galloway. We will take a look. Could you please provide proper links to the builds and minimal repro steps workflow to help us with the investigation process.
Links to the builds you've provided either in private repo or broken.

**Comment by dave99galloway** [comment]
@shilovmaksim - I've added a full repro here :
https://github.com/dave99galloway/github-actions-issues/actions/runs/1516395849

apologies took me a while to strip out the unneccesary stuff. Looks like the issue is 100% reproducible, not intermittent

**Comment by shilovmaksim** [comment]
@dave99galloway. It looks like there's a mismatch in the `BAZ: ${{ needs.set-variables.outputs.BAZ }}` input value type.
Workflow call works fine if I set it to bool "true" directly in the call job or change the called workflow input to "string".
https://github.com/shilovmaksim/github-actions-issues/actions/workflows/main.yml

**Comment by dave99galloway** [comment]
@shilovmaksim - thanks for taking the time to investigate this - I was suspecting a boolean variable type mismatch but wasn't expecting the solution to be to change it to a string - that sounds nasty!

Could you re-paste the link to the docs - the one you posted links to the Actions results!

**Comment by shilovmaksim** [comment]
Oh, my apologies for the incorrect link.
https://docs.github.com/en/actions/learn-github-actions/reusing-workflows#using-inputs-and-secrets-in-a-reusable-workflow
Third point: "For inputs, the data type of the input value must match the type specified in the called workflow (either boolean, number, or string)."

**Comment by dave99galloway** [comment]
@shilovmaksim - no worries! so it seems that yaml and booleans don't play well together (see e.g. this [issue](https://github.com/actions/toolkit/issues/361)), so I'll need to treat them as strings and parse them. yuck! thanks for your help!

**Comment by dave99galloway** [comment]
see also this comment https://github.community/t/boolean-evaluation-workflow-yaml/173565

**Comment by dave99galloway** [comment]
actually - I'm reopening this as it really seems like the error from github actions could be more helpful - like "you tried to pass input x as astring value but input x is a boolean" or something similar :)

**Comment by shilovmaksim** [comment]
Unfortunately, there is nothing we can do from our side. This common message usually indicates that the hosted runner has disconnected for some reason and was unable to run the job. Please direct your questions to our support community forum at https://github.community/c/code-to-cloud/github-actions/41
Thanks!

**Comment by dave99galloway** [comment]
@shilovmaksim - thanks for redirecting me to the correct forum - will raise there :)
