### ISSUE TITLE
Update/Add Helm 3

### ISSUE THREAD

**Issue by polRk** [actions/virtual-environments#463]
**Tool information**
- Tool name: Helm 3
- Add or update? Update
- Desired version: https://v3.helm.sh/, https://helm.sh/
- Approximate size:
- If this is an add request:
  - Brief description of tool: The package manager for Kubernetes
  - URL for tool's homepage: https://v3.helm.sh

**Area for Triage**:
Containers, Go

**Virtual environments affected**
- [+] macOS 10.15
- [+] Ubuntu 16.04 LTS
- [+] Ubuntu 18.04 LTS
- [+] Windows Server 2016 R2
- [+] Windows Server 2019

**Comment by polRk** [comment]
You can use helm 3 inside docker container

```
docker run -i --rm -v $GITHUB_WORKSPACE/.kubeconfig:/root/.kube/config -v $GITHUB_WORKSPACE/chart:/root/chart alpine/helm upgrade NAME /root/chart --install --set image.tag=${{ github.sha }}
```

**Comment by maxim-lobanov** [comment]
Currently, helm 3 is installed on Ubuntu only. 
@alepauly , do we want to add Helm 3 to Windows and macOS for consistency?

**Comment by alepauly** [comment]
@maxim-lobanov I think we should yeah. Thanks!

**Comment by dmitry-shibanov** [comment]
Hello, thank you for your response. Pull requests with helm were merged and changes would be added in next images rollout.

**Comment by dmitry-shibanov** [comment]
Hello, helm was added to all images. If you have any concerns please feel free to reopen the issue.
