### ISSUE TITLE
Add gcloud sdk

### ISSUE THREAD

**Issue by barucoh** [actions/virtual-environments#4639]
### Tool name

gcloud util

### Tool license

free

### Add or update?

- [X] Add
- [ ] Update

### Desired version

latest

### Approximate size

~600 MB

### Brief description of tool

Similar to AWS and Azure, `gcloud sdk util` is used to interact with GCP

### URL for tool's homepage

https://cloud.google.com/sdk/gcloud

### Provide a basic test case to validate the tool's functionality.

```bash
gcloud version
```

### Virtual environments affected

- [ ] Ubuntu 18.04
- [X] Ubuntu 20.04
- [ ] macOS 10.15
- [X] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [ ] Windows Server 2022

**Comment by catthehacker** [comment]
There is an official action to setup `gcloud`
https://github.com/google-github-actions/setup-gcloud

**Comment by barucoh** [comment]
> There is an official action to setup `gcloud` https://github.com/google-github-actions/setup-gcloud

Thanks, but regardless, it's easier and less expensive for me as a user to have the image prebuilt with `gcloud` in it instead of having to do extra preparations before I can start the actual work.

**Comment by shilovmaksim** [comment]
Hi @barucoh. Google Cloud SDK is prebuilt on the [Ubuntu 20](https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-README.md) image already.
As for the MacOS, we're not going to add any software to the image that can be setup by existing action or installed in the runtime.

@catthehacker. Thank you for the link to existing action.

**Comment by martinbonnin** [comment]
Is there anything that prevents https://github.com/google-github-actions/setup-gcloud to work with Ubuntu images? 

I understand the reasoning but is there a reason it doesn't apply to Ubuntu images? This makes switching images more error prone.
