### ISSUE TITLE
Add Docker Buildx

### ISSUE THREAD

**Issue by NinoFloris** [actions/virtual-environments#464]
Add Docker Buildx, it's already shipped with docker 19.03 but it seems impossible to use because the docker daemon doesn't have experimental support enabled.

https://github.com/docker/buildx

**Comment by andy-mishechkin** [comment]
Hello, @NinoFloris 
Do you need to add Docker Buildx to all images , or to something separate image (MacOS, Ubuntu, etc)
Please specify the Virtual environments affected to your request

**Comment by AlenaSviridenko** [comment]
Hi @NinoFloris! I am closing this issue in favor of https://github.com/actions/virtual-environments/issues/690 that is prioritized and put to our To Do list. 
If you can specify the required OS that we should install Docker BuildX to, please let me know and I'll add it to https://github.com/actions/virtual-environments/issues/690.

Also, please, feel free to reopen this one if you have any concerns.
Thanks!
