### ISSUE TITLE
Add redis (server and cli)

### ISSUE THREAD

**Issue by bsergean** [actions/virtual-environments#465]
**Tool information**
- Tool name: redis
- Add or update? Add
- Desired version: Whatever is latest. Latest Stable 5 release, or 6rc1 (to be released in May) would be good.
- Approximate size: < 2M
- If this is an add request:
  - Brief description of tool: Redis is an open source (BSD licensed), in-memory data structure store, used as a database, cache and message broker
  - URL for tool's homepage: https://redis.io/

```
# I built redis on my mac and here's what I found / there are other small tools I believe but it's a small package.
(venv) rcc$ du -sh /usr/local/bin/redis-server 
1.4M	/usr/local/bin/redis-server
(venv) rcc$ du -sh /usr/local/bin/redis-cli   
284K	/usr/local/bin/redis-cli
```

**Area for Triage**:
Databases

**Question, Bug, or Feature?**:
Feature

**Virtual environments affected**
- [*] macOS 10.15
- [*] Ubuntu 16.04 LTS
- [*] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

I am not sure that stock redis is supported on Windows, there's a port though.

**Can this tool be installed during the build?**

**Are you willing to submit a PR?**
hum... not too sure where to start but it would be nice from me :)

**Comment by maxim-lobanov** [comment]
Tool can be installed in runtime using the following commands:
```
# macOS
brew install redis
# Ubuntu
sudo apt-get install redis-server # will install both server and cli
```
Installation takes about 15 seconds

**Comment by thejoebourneidentity** [comment]
Hey @bsergean, I believe that apt has the updated `5:4.0.9-1` version of redis now. Can you try again? If that doesn't work then I believe you can also specify a version using the following argument structure.

`sudo apt-get install <package name>=<version>`

**Comment by bsergean** [comment]
This is still redis 4, while in my use case I wanted redis 5.

http://download.redis.io/releases/ <http://download.redis.io/releases/>

It looks like redis 5 got released after the previous ubuntu version maybe.

**Comment by bsergean** [comment]
Feel free to close if you guys prefer not to support having redis in the base environment.

(I think it would be a great feature for Github Action to have it, but obviously it's up to you !)

**Comment by alepauly** [comment]
Thanks for the suggestion @bsergean but yeah, I think it makes sense to leave it out of the base environment for now. Let us know if something changes and we should reconsider.

**Comment by nwalters512** [comment]
Let me know if you'd rather that I open a new issue for discussion, but I figured I'd keep all the discussion in one place for now.

On `ubuntu-latest`, running `sudo apt-get install redis-server` takes 60 seconds, which is currently the longest step of our CI jobs. I understand the desire to keep the number of preinstalled packages to a minimum, but as the original issue pointed out, the Redis binaries are tiny. It'd be great to be able to cut a minute off our CI times! I'd be happy to open a PR with this change if it'd ultimately be accepted.

**Comment by miketimofeev** [comment]
@nwalters512 have you tried to use any of the actions to install Redis? I wonder if they do it quicker
https://github.com/marketplace?type=&verification=&query=redis+
