### ISSUE TITLE
npm install fails in latest versions of windows-2019 and 2022 agents

### ISSUE THREAD

**Issue by sureshbemagani** [actions/virtual-environments#4651]
### Description

We have couple of release definitions which use Azure pipelines hosted agents (windows-2019). From yesterday, they started failing at “npm install”.

The releases are failing in below agents:

•	Environment: windows-2019 (image version: '20211229.2')
•	Environment: windows-2022 (image version: '20211130.3')

The releases are working with below agents only:

•	Environment: windows-2022 (image version: '20211122.0')

Also, the windows-2022 agents doesn’t have Storage emulator. 

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [X] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

https://github.com/actions/virtual-environments/blob/win22/20211130.3/images/win/windows2019.json
https://github.com/actions/virtual-environments/blob/win22/20211130.3/images/win/windows2022.json

### Is it regression?

yes working version: Environment: windows-2022 (image version: '20211122.0')

### Repro steps

Create an RD with Azure pipelines hosted agent and select window-2019/2022 as agent
And a powershell script task with npm installl against a react app.

**Comment by shilovmaksim** [comment]
Hi @sureshbemagani. Thank you for your report. We will take a look. In the meantime, could you please provide us logs of a failing jobs?

**Comment by sureshbemagani** [comment]
[Error on windows 2019 version 20211229.2.txt](https://github.com/actions/virtual-environments/files/7640300/Error.on.windows.2019.version.20211229.2.txt
[Success on windows 2022 version 20211122.0.txt](https://github.com/actions/virtual-environments/files/7640302/Success.on.windows.2022.version.20211122.0.txt)
)

**Comment by sureshbemagani** [comment]
[Error on windows 2022 version 20211130.3.txt](https://github.com/actions/virtual-environments/files/7640502/Error.on.windows.2022.version.20211130.3.txt)

**Comment by mikhailkoliada** [comment]
Hello @sureshbemagani!

What version of node are you running?

**Comment by abdullah007001** [comment]
I did faced similar issue today with my Azure build pipeline which was using ubuntu-latest image and we have fixed our build pipeline by pinning Node version.
https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/tool/node-js?view=azure-devops

New version of NPM/Node my Agent machine - Node v16.13.0, NPM 8.1.0
Expected was 14.15.0

**Comment by sureshbemagani** [comment]
> I did faced similar issue today with my Azure build pipeline which was using ubuntu-latest image and we have fixed our build pipeline by pinning Node version. https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/tool/node-js?view=azure-devops
> 
> New version of NPM/Node my Agent machine - Node v16.13.0, NPM 8.1.0 Expected was 14.15.0

This worked! Thanks @mikhailkoliada/ @abdullah007001
