### ISSUE TITLE
Question about cargo installation directory

### ISSUE THREAD

**Issue by kt3k** [actions/virtual-environments#4652]
### Description

Until ubuntu 20.04 version 20211122.1, cargo was installed at `/usr/share/rust/.cargo`, but it now seems installed at `/home/runner/.cargo` at version 20211129.1. Is this change intentional?

### Virtual environments affected

- [ ] Ubuntu 18.04
- [X] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Version: 20211129.1

### Is it regression?

Version: 20211122.1

### Expected behavior

Cargo is installed at /usr/share/rust/.cargo

### Actual behavior

Cargo is installed at /home/runner/.cargo

### Repro steps

Create step with `run: ls /usr/share/`, you now don't find `rust` in the output

**Comment by al-cheb** [comment]
Hello, @kt3k 
This change was intentional -in scope of this https://github.com/actions/virtual-environments/pull/4575 PR , to remove symlinks and move /usr/share/rust -> to a user profile folder.

**Comment by kt3k** [comment]
@al-cheb 
Now the change makes sense to me. Thank you for the quick reply!
