### ISSUE TITLE
Is it possible to use an older image while we work through updating our end?

### ISSUE THREAD

**Issue by buckleyGI** [actions/virtual-environments#4653]
### Tool name

older devops image

### Tool license

/

### Add or update?

- [X] Add
- [ ] Update

### Desired version

20211122.1

### Brief description of tool

I think it makes sense to revert to an older image if we are working through the kinks of updating our systems.

We just got in that situation as of yesterday 

Before (success)
Included Software: https://github.com/actions/virtual-environments/blob/win19/20211122.1/images/win/Windows2019-Readme.md
Image Release: https://github.com/actions/virtual-environments/releases/tag/win19%2F20211122.1

After (fail)
Included Software: https://github.com/actions/virtual-environments/blob/win19/20211229.2/images/win/Windows2019-Readme.md
Image Release: https://github.com/actions/virtual-environments/releases/tag/win19%2F20211229.2

We tried switching to the old image but got the error below

```
jobs:
- job: Build
  displayName: Build
  timeoutInMinutes: 120
  pool:
    vmImage: 'windows-latest'
  container: mcr.microsoft.com/windows/servercore:20211122.1
```

**Error**

```
C:\Program Files\Docker\docker.EXE pull mcr.microsoft.com/windows/servercore:20211122.1
Error response from daemon: manifest for mcr.microsoft.com/windows/servercore:20211122.1 not found: manifest unknown: manifest tagged by "20211122.1" is not found
##[warning]Docker pull failed with exit code 1, back off 7.204 seconds before retry.
```

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [X] Windows Server 2019
- [ ] Windows Server 2022

**Comment by shilovmaksim** [comment]
Hi @buckleyGI. There are a lot of such requests but unfortunately it is not possible for now.
