### ISSUE TITLE
Wix.Tests Fails

### ISSUE THREAD

**Issue by Lietotajs** [actions/virtual-environments#4654]
### Description

I have tried several times Windows2019 and Windows2022 image, always fails at Running tests from 'C:\image\Tests\Wix.Tests.ps1'

Windows2019 image log - 
   vhd: Running tests from 'C:\image\Tests\Wix.Tests.ps1'
    vhd: Describing Wix
    vhd:   [+] Wix Toolset version from registry 4ms (2ms|2ms)
    vhd:   [+] Wix Toolset version from system 73ms (72ms|1ms)
    vhd: Tests completed in 231.76s
    vhd: Tests Passed: 522, Failed: 4, Skipped: 1 NotRun: 0
==> vhd: Test run has failed
==> vhd: At C:\Program Files\WindowsPowerShell\Modules\ImageHelpers\TestsHelpers.ps1:73 char:9
    vhd:
    vhd:
    vhd: Containers            : {[+] C:\image\Tests\Android.Tests.ps1, [+] C:\image\Tests\Apache.Tests.ps1, [+]
    vhd:                         C:\image\Tests\BizTalk.Tests.ps1, [+] C:\image\Tests\Browsers.Tests.ps1...}
    vhd: Result                : Failed
    vhd: FailedCount           : 4
    vhd: FailedBlocksCount     : 0
    vhd: FailedContainersCount : 0
    vhd: PassedCount           : 522
    vhd: SkippedCount          : 1
    vhd: NotRunCount           : 0
    vhd: TotalCount            : 527
    vhd: Duration              : 00:03:51.7589012
    vhd: Executed              : True
    vhd: ExecutedAt            : 12/1/2021 6:49:44 PM
    vhd: Version               : 5.3.1
    vhd: PSVersion             : 5.1.17763.2268
    vhd: PSBoundParameters     : {[Configuration, PesterConfiguration]}
    vhd: Plugins               :
    vhd: PluginConfiguration   :
    vhd: PluginData            :
    vhd: Configuration         : PesterConfiguration
    vhd: DiscoveryDuration     : 00:00:15.1522631
    vhd: UserDuration          : 00:03:29.6176700
    vhd: FrameworkDuration     : 00:00:06.9889681
    vhd: Failed                : {[-] 2021-01 Update for Windows Server 2019 for x64-based Systems (KB4589208), [-] 2021-11
    vhd:                         Cumulative Update for Windows Server 2019 (1809) for x64-based Systems (KB5007206), [-]
    vhd:                         2021-11 Cumulative Update Preview for .NET Framework 3.5, 4.7.2 and 4.8 for Windows Server
    vhd:                         2019 for x64 (KB5007406), [-] Security Update for Windows Server 2019 for x64-based Systems
    vhd:                         (KB4535680)}
    vhd: FailedBlocks          : {}
    vhd: FailedContainers      : {}
    vhd: Passed                : {[+] Sdkmanager from SDK tools is available, [+] Sdkmanager from Command-line tools is
    vhd:                         available, [+] Platform version platforms;android-19 is installed, [+] Platform version
    vhd:                         platforms;android-20 is installed...}
    vhd: Skipped               : {[!] vcredist_140}
    vhd: NotRun                : {}
    vhd: Tests                 : {[+] Sdkmanager from SDK tools is available, [+] Sdkmanager from Command-line tools is
    vhd:                         available, [+] Platform version platforms;android-19 is installed, [+] Platform version
    vhd:                         platforms;android-20 is installed...}
    vhd: CodeCoverage          :
    vhd:
==> vhd: +         throw "Test run has failed"
==> vhd: +         ~~~~~~~~~~~~~~~~~~~~~~~~~~~
==> vhd:     + CategoryInfo          : OperationStopped: (Test run has failed:String) [], RuntimeException
==> vhd:     + FullyQualifiedErrorId : Test run has failed
==> vhd:
==> vhd: Script exited with non-zero exit status: 1.Allowed exit codes are: [0]
==> vhd: Step "StepProvision" failed

Windows2022 image log - 
    vhd: Running tests from 'C:\image\Tests\Wix.Tests.ps1'
    vhd: Describing Wix
    vhd:   [+] Wix Toolset version from registry 4ms (2ms|2ms)
    vhd:   [!] Wix Toolset version from system 1ms (0ms|1ms)
    vhd: Tests completed in 137.84s
    vhd: Tests Passed: 365, Failed: 1, Skipped: 23 NotRun: 0
    vhd:
    vhd:
    vhd: Containers            : {[+] C:\image\Tests\Android.Tests.ps1, [+] C:\image\Tests\Apache.Tests.ps1, [+]
    vhd:                         C:\image\Tests\BizTalk.Tests.ps1, [+] C:\image\Tests\Browsers.Tests.ps1...}
    vhd: Result                : Failed
    vhd: FailedCount           : 1
    vhd: FailedBlocksCount     : 0
    vhd: FailedContainersCount : 0
    vhd: PassedCount           : 365
    vhd: SkippedCount          : 23
    vhd: NotRunCount           : 0
    vhd: TotalCount            : 389
    vhd: Duration              : 00:02:17.8420743
    vhd: Executed              : True
    vhd: ExecutedAt            : 11/30/2021 3:22:52 PM
    vhd: Version               : 5.3.1
    vhd: PSVersion             : 5.1.20348.320
    vhd: PSBoundParameters     : {[Configuration, PesterConfiguration]}
    vhd: Plugins               :
    vhd: PluginConfiguration   :
    vhd: PluginData            :
    vhd: Configuration         : PesterConfiguration
    vhd: DiscoveryDuration     : 00:00:11.9031222
    vhd: UserDuration          : 00:01:59.6725165
    vhd: FrameworkDuration     : 00:00:06.2664356
    vhd: Failed                : {[-] 2021-11 Cumulative Update Preview for .NET Framework 3.5 and 4.8 for Microsoft server
    vhd:                         operating system version 21H2 for x64 (KB5007293)}
    vhd: FailedBlocks          : {}
    vhd: FailedContainers      : {}
    vhd: Passed                : {[+] Sdkmanager from SDK tools is available, [+] Sdkmanager from Command-line tools is
    vhd:                         available, [+] Platform version platforms;android-27 is installed, [+] Platform version
    vhd:                         platforms;android-28 is installed...}
    vhd: Skipped               : {[!] BizTalk Registry Check, [!] BizTalk Folder Check, [!] BizTalk Build Targets files Check,
    vhd:                         [!] gitversion is installed...}
    vhd: NotRun                : {}
    vhd: Tests                 : {[+] Sdkmanager from SDK tools is available, [+] Sdkmanager from Command-line tools is
    vhd:                         available, [+] Platform version platforms;android-27 is installed, [+] Platform version
    vhd:                         platforms;android-28 is installed...}
    vhd: CodeCoverage          :
    vhd:
==> vhd: Test run has failed
==> vhd: At C:\Program Files\WindowsPowerShell\Modules\ImageHelpers\TestsHelpers.ps1:73 char:9
==> vhd: +         throw "Test run has failed"
==> vhd: +         ~~~~~~~~~~~~~~~~~~~~~~~~~~~
==> vhd:     + CategoryInfo          : OperationStopped: (Test run has failed:String) [], RuntimeException
==> vhd:     + FullyQualifiedErrorId : Test run has failed
==> vhd:
==> vhd: Script exited with non-zero exit status: 1.Allowed exit codes are: [0]
==> vhd: Step "StepProvision" failed

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [X] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

https://github.com/actions/virtual-environments/releases/tag/win22%2F20211130.3
https://github.com/actions/virtual-environments/releases/tag/win19%2F20211229.2

### Repro steps

Set-Location C:\virtual-environments

Import-Module .\helpers\GenerateResourcesAndImage.ps1

GenerateResourcesAndImage -SubscriptionId {YourSubscriptionId} -ResourceGroupName "myTestResourceGroup" -ImageGenerationRepositoryRoot "$pwd" -ImageType Windows2019 -AzureLocation "West Europe"

and

GenerateResourcesAndImage -SubscriptionId {YourSubscriptionId} -ResourceGroupName "myTestResourceGroup" -ImageGenerationRepositoryRoot "$pwd" -ImageType Windows2022 -AzureLocation "West Europe"

**Comment by al-cheb** [comment]
Hello, @Lietotajs 
As I can see an issue with `vhd: Failed : {[-] 2021-01 Update for Windows Server 2019 for x64-based Systems (KB4589208), [-] 2021-11`.  This issue was fixed - https://github.com/actions/virtual-environments/issues/4636. Please pull the latest changes from `main` branch.

**Comment by al-cheb** [comment]
Tests for Wix completed 
```
vhd: Running tests from 'C:\image\Tests\Wix.Tests.ps1'
vhd: Describing Wix
vhd: [+] Wix Toolset version from registry 4ms (2ms|2ms)
vhd: [+] Wix Toolset version from system 121ms (120ms|1ms)
vhd: Tests completed in 225.5s
```

Failed tests:
```
vhd: Failed : {[-] SDK 2.1 is available, [-] Runtime 2.1 is available, [-] SDK 3.1 is available, [-] make}
vhd: FailedBlocks : {}
vhd: FailedContainers : {[-] C:\image\Tests\Haskell.Tests.ps1}
```

Please attach full logs.

**Comment by Lietotajs** [comment]
[outputW2019.txt](https://github.com/actions/virtual-environments/files/7647723/outputW2019.txt)

**Comment by al-cheb** [comment]
@Lietotajs,
Looks like you use a custom packer template, because a lot of scripts just skipped:
```
==> vhd: Provisioning with powershell script: C:\virtual-environments\images\win/scripts/Installers/Install-SQLPowerShellTools.ps1
==> vhd: Provisioning with powershell script: C:\virtual-environments\images\win/scripts/Installers/Install-DotnetSDK.ps1
==> vhd: Provisioning with powershell script: C:\virtual-environments\images\win/scripts/Installers/Install-Mingw64.ps1
==> vhd: Provisioning with powershell script: C:\virtual-environments\images\win/scripts/Installers/Install-Haskell.ps1
==> vhd: Provisioning with powershell script: C:\virtual-environments\images\win/scripts/Installers/Install-Stack.ps1
```

For e.g. nightly build - https://github.visualstudio.com/virtual-environments/_build/results?buildId=119950&view=logs&j=011e1ec8-6569-5e69-4f06-baf193d1351e&t=5431112d-2b61-5a5f-7042-ef698f761043

```
==> vhd: Provisioning with powershell script: C:\agent\_work\3\s\images\win/scripts/Installers/Install-SQLPowerShellTools.ps1
    vhd: Downloading SQLSysClrTypes.msi...
    vhd: Downloading package from: https://download.microsoft.com/download/B/1/7/B1783FE9-717B-4F78-A39A-A2E27E3D679D/ENU/x64/SQLSysClrTypes.msi to path C:\Users\packer\AppData\Local\Temp\SQLSysClrTypes.msi .
    vhd: Package downloaded successfully in 0.11 seconds
    vhd: Starting Install SQLSysClrTypes.msi...
    vhd: Installation successful in 3.07 seconds
    vhd: Downloading SharedManagementObjects.msi...
    vhd: Downloading package from: https://download.microsoft.com/download/B/1/7/B1783FE9-717B-4F78-A39A-A2E27E3D679D/ENU/x64/SharedManagementObjects.msi to path C:\Users\packer\AppData\Local\Temp\SharedManagementObjects.msi .
    vhd: Package downloaded successfully in 0.12 seconds
    vhd: Starting Install SharedManagementObjects.msi...
    vhd: Installation successful in 8.07 seconds
    vhd: Downloading PowerShellTools.msi...
    vhd: Downloading package from: https://download.microsoft.com/download/B/1/7/B1783FE9-717B-4F78-A39A-A2E27E3D679D/ENU/x64/PowerShellTools.msi to path C:\Users\packer\AppData\Local\Temp\PowerShellTools.msi .
    vhd: Package downloaded successfully in 0.03 seconds
    vhd: Starting Install PowerShellTools.msi...
    vhd: Installation successful in 2.02 seconds
```

**Comment by Lietotajs** [comment]
I was following guide here : https://github.com/actions/virtual-environments/blob/main/docs/create-image-and-azure-resources.md
I have not done any customization to any scripts.
Could you advice, when you say "you use a custom packer template" - how to make sure I use proper template ?
Thanks.
