### ISSUE TITLE
Update/Add Docker Compose v2

### ISSUE THREAD

**Issue by SpyderHunter03** [actions/virtual-environments#4657]
### Tool name

Docker Compose v2

### Tool license

Unknown

### Add or update?

- [X] Add
- [ ] Update

### Desired version

2 (latest or whichever one we can)

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [X] Windows Server 2016
- [X] Windows Server 2019
- [X] Windows Server 2022

**Comment by shilovmaksim** [comment]
Hi @SpyderHunter03. could you please provide some more details:
- Why it should be added to image, because this change is the breaking one?
- Can docker compose be updated to v2 during the runtime?

**Comment by ToshY** [comment]
Docker announced [general availability of v2](https://www.docker.com/blog/announcing-compose-v2-general-availability/#:~:text=April%2026%2C%202022%20marks%20the,developer%20default%20on%20Docker%20Desktop.) on April 26th.

**Comment by al-cheb** [comment]
The new images with docker-compose v2 on board have been deployed.

How to use?
v1:
```
PS > docker-compose version --short
1.29.2
```

v2:
```
PS > docker compose version --short
2.5.0
```
