### ISSUE TITLE
Problem with installing package libgtkmm-3.0-dev for Ubuntu-20.04.3

### ISSUE THREAD

**Issue by vroncevic** [actions/virtual-environments#4660]
### Description

Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/main/m/mesa/libegl-mesa0_21.0.3-0ubuntu0.3~20.04.4_amd64.deb ERROR:404  
Description: Not Found, missing mesa lib version 20.04.4, detected only new version: 20.04.5
Checked libs at: http://azure.archive.ubuntu.com/ubuntu/pool/main/m/mesa/

### Virtual environments affected

- [ ] Ubuntu 18.04
- [X] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Job link with logs: https://github.com/dof2bot/motionbot/runs/4406464746?check_suite_focus=true

Added github workflow action:
motionbot_desktop_cc_checker
https://github.com/dof2bot/motionbot/blob/dev/.github/workflows/motionbot_desktop_cc_checker.yml
Step install_gtkmm is crushing:
`    - name: install GTK--
      id: install_gtkmm
      run: |
        sudo apt install libgtkmm-3.0-dev
`

### Expected behavior

Another project with same github workflow action which was passing before action:
https://github.blog/changelog/2020-10-29-github-actions-ubuntu-latest-workflows-will-use-ubuntu-20-04/

Job link with logs: https://github.com/electux/microhil/runs/4340624730?check_suite_focus=true
Similar job with same code and libs for action.

### Actual behavior

Job link: https://github.com/dof2bot/motionbot/actions/runs/1534679578
Failing to get mesa libs with version: 20.04.4

### Repro steps

Steps to reproduce issue:
runs-on: ubuntu-20.04
to use: actions/checkout@v2
run: sudo apt install libgtkmm-3.0-dev

**Comment by catthehacker** [comment]
You are missing `sudo apt-get update` before package installation
https://docs.github.com/en/actions/using-github-hosted-runners/customizing-github-hosted-runners#installing-software-on-ubuntu-runners

**Comment by vroncevic** [comment]
Updated action:
`
    - name: install GTK--
      id: install_gtkmm
      run: |
        sudo apt-get update
        sudo apt-get install jq
        sudo apt-get install libgtkmm-3.0-dev
`
Success job: https://github.com/dof2bot/motionbot/actions/runs/1534918306
Thanks for fast response @catthehacker
