### ISSUE TITLE
Default Node has custom $PATH

### ISSUE THREAD

**Issue by layday** [actions/virtual-environments#4665]
### Description

The default version of Node on the latest macOS 11 image (20211127.1) has a different $PATH than the enclosing environment.  Notably it puts Python 3.10 on path which leads to hard to debug failures for code which calls out Python from Node.

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [X] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

20211127.1

### Is it regression?

Yes, from 20211120.1

### Expected behavior

That the $PATH in Node would not differ.

### Actual behavior

The $PATH does differ.

### Repro steps

Create a new workflow with the following steps and run it:

```yaml
[...]
      - run: |
          echo '
            const child_process = require("child_process");
            const output = child_process.execFileSync("python3", ["-V"], { encoding: "utf8" });
            console.log(process.env.PATH);
            console.log(output);
          ' | node -
      - run: |
          echo $PATH
          python3 -V
```

The output for Node is:

```
/usr/local/opt/python@3.10/bin:/usr/local/Cellar/node@16/16.13.0/bin:/Users/runner/hostedtoolcache/Python/3.9.9/x64/bin:/Users/runner/hostedtoolcache/Python/3.9.9/x64:/usr/local/lib/ruby/gems/2.7.0/bin:/usr/local/opt/ruby@2.7/bin:/usr/local/opt/pipx_bin:/Users/runner/.cargo/bin:/usr/local/opt/curl/bin:/usr/local/bin:/usr/local/sbin:/Users/runner/bin:/Users/runner/.yarn/bin:/Users/runner/Library/Android/sdk/tools:/Users/runner/Library/Android/sdk/platform-tools:/Users/runner/Library/Android/sdk/ndk-bundle:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/usr/bin:/bin:/usr/sbin:/sbin:/Users/runner/.dotnet/tools:/Users/runner/.ghcup/bin:/Users/runner/hostedtoolcache/stack/2.7.3/x64
Python 3.10.0
```

And for Bash:

```
/Users/runner/hostedtoolcache/Python/3.9.9/x64/bin:/Users/runner/hostedtoolcache/Python/3.9.9/x64:/usr/local/lib/ruby/gems/2.7.0/bin:/usr/local/opt/ruby@2.7/bin:/usr/local/opt/pipx_bin:/Users/runner/.cargo/bin:/usr/local/opt/curl/bin:/usr/local/bin:/usr/local/sbin:/Users/runner/bin:/Users/runner/.yarn/bin:/Users/runner/Library/Android/sdk/tools:/Users/runner/Library/Android/sdk/platform-tools:/Users/runner/Library/Android/sdk/ndk-bundle:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/usr/bin:/bin:/usr/sbin:/sbin:/Users/runner/.dotnet/tools:/Users/runner/.ghcup/bin:/Users/runner/hostedtoolcache/stack/2.7.3/x64
Python 3.9.9
```

**Comment by al-cheb** [comment]
Hey, @layday 
We will take a look at it.

**Comment by dibir-magomedsaygitov** [comment]
Hello @layday. We've recently changed the default node version to 16.* and [the brew formula has changed](https://github.com/Homebrew/homebrew-core/blob/master/Formula/node@16.rb#:~:text=depends_on%20%22python%403.10%22%20%3D%3E%20%3Abuild) for as well. Could you please add following line before your steps to resolve the issue temporarily:
```
    - uses: actions/setup-node@v2
      with:
        node-version: '16.13.0'
```
Check example [here](https://github.com/dibir-magomedsaygitov/decomp.me/blob/main/.github/workflows/pr.yml) and the output:
![123](https://user-images.githubusercontent.com/61747324/145256168-4c0e565f-6718-43a0-a612-fa2573b7f2f2.png)

**Comment by layday** [comment]
Thanks. Was a bug opened against Homebrew?

**Comment by dibir-magomedsaygitov** [comment]
@layday brew formula for Node was using python 3.9, which also was the default version on our images - that's why this bug  hasn't appeared in the past. Recently, brew changed its formula and now it depends on [python 3.10](https://github.com/Homebrew/homebrew-core/blob/master/Formula/node@16.rb#:~:text=depends_on%20%22python%403.10%22%20%3D%3E%20%3Abuild), but we still have python 3.9 as a default version on our images - and that's why you have started experiencing issues. I suggested you to use [setup-node](https://github.com/actions/setup-node) task since it doesn't use brew and there are no conflicts between python versions.

**Comment by layday** [comment]
I understand what's happening and I have been using setup-node but I imagine this is gonna trip more people up.

**Comment by dibir-magomedsaygitov** [comment]
I'm going to close this issue. Until we switch default python version to 3.10 please use [setup-node](https://github.com/actions/setup-node) action to avoid the issue. I'm going to close this thread. If you have any concerns feel free to contact us.

**Comment by layday** [comment]
Changing the default Python is orthogonal to this issue.  Who's to say that I want to use 3.10?  Node should simply not override the Python from the environment.  The issue should be reported to Homebrew and kept open here until it's fixed.

**Comment by dibir-magomedsaygitov** [comment]
@layday could you please file an issue with [Homebrew](https://github.com/Homebrew/homebrew-core)

**Comment by dibir-magomedsaygitov** [comment]
Hello @layday. Have you had a chance to file an issue with Homebrew?

**Comment by layday** [comment]
Sigh. Aren’t you on GitHub’s payroll? Why do I need to file an issue in my free time for an issue affecting GH, which will most likely be closed without comment, because I do not use Homebrew?

Sent with [ProtonMail](https://protonmail.com/) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by dibir-magomedsaygitov** [comment]
@layday I've filed an issue in Homebrew repository. You can check updates [here](https://github.com/Homebrew/homebrew-core/issues/92116).

**Comment by dibir-magomedsaygitov** [comment]
Hello @layday. The issue with Node has been resolved and updated image is available for use. I'm going to close this issue. Feel free to contact us in case of any questions or concerns.
![test](https://user-images.githubusercontent.com/61747324/149723061-15dd8e4b-f75a-4124-b696-6edc10c7477f.jpg)

**Comment by layday** [comment]
Thanks :)
