### ISSUE TITLE
Corrupted ZIP library: C:\Miniconda\envs\test\Library\bin\zip.dll

### ISSUE THREAD

**Issue by davide-f** [actions/virtual-environments#4669]
### Description

Hi,

While executing the workflow of https://github.com/pypsa-meets-africa/pypsa-africa, we cannot run it on Windows because the error Corrupted ZIP library arises when initializing the VM:
```
Error occurred during initialization of VM
Corrupted ZIP library: C:\Miniconda\envs\test\Library\bin\zip.dll
```
See lines 851-852 at: https://github.com/pypsa-meets-africa/pypsa-africa/runs/4333471322?check_suite_focus=true

On linux and Mac, the workflow works successfully also on the VM; on our windows platforms, the workflow works, but on the virtual machine the above fails.
Currently, we have disabled the check on windows, but we would like to use that feature as well.

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [X] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Virtual Environment
  Environment: windows-2019
  Version: 20211122.1

### Expected behavior

The workflow should work without generating errors

### Actual behavior

The workflow breaks due to an apparent corrupted DLL file [line 851-852] of https://github.com/pypsa-meets-africa/pypsa-africa/runs/4333471322?check_suite_focus=true

### Repro steps

Run the workflow of https://github.com/pypsa-meets-africa/pypsa-africa on windows

**Comment by al-cheb** [comment]
Hey, @davide-f 
We will take a look at it.

**Comment by al-cheb** [comment]
@davide-f , This issue is not related to the image itself, because the same bug exists - https://github.com/conda-forge/openjdk-feedstock/issues/86. I am planning to close the thread as external.
