### ISSUE TITLE
IIS Default Document Changes

### ISSUE THREAD

**Issue by erwabo** [actions/virtual-environments#4671]
### Description

We have a python web services that runs from an ADO build pipeline. The base server image gets built from a packer pipeline. The image it was using is 'vs2017-vs2016' but due to deprecation, I changed it to 'windows-latest'.  The website now requires us to include web.config in the default document list. I validated this behavior numerous times with various builds and it was consistently happening using windows-latest. This may be an IIS 10.0 update perhaps, but I could not find anything official from MS regarding this.

This is an internally facing python application

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [X] Windows Server 2016
- [X] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

windows-latest

### Is it regression?

'vs2017-vs2016'

### Expected behavior

I expect I can hit by website without including web.config in the default document configuration

### Actual behavior

The website cannot be displayed.

### Repro steps

1. Build a packer image via ADO pipeline using 'windows-latest'
2.  Run application build pipeline using the previously built image 
3.  Attempt to hit the website without adding web.config to the default document configuration

**Comment by al-cheb** [comment]
Hey, @erwabo
We will take a look at it.

**Comment by V-Zabayrachny** [comment]
Hello, @erwabo
The microsoft documentation says that you need to use web.config with certain settings so that services IIS can properly process Python code. (https://docs.microsoft.com/en-us/visualstudio/python/configure-web-apps-for-iis-windows?view=vs-2019)

**Comment by V-Zabayrachny** [comment]
Hello, @erwabo. I'm going to close the issue, but feel free to contact us if you have any questions.
