### ISSUE TITLE
Update/Add argo-rollouts

### ISSUE THREAD

**Issue by g14com0** [actions/virtual-environments#4672]
### Tool name

argo-rollouts

### Tool license

Apache License 2.0

### Add or update?

- [X] Add
- [ ] Update

### Desired version

latest, v1.1.1

### Approximate size

More or less 70MB

### Brief description of tool

Argo Rollouts is a Kubernetes controller and set of CRDs which provide advanced deployment capabilities such as blue-green, canary, canary analysis, experimentation, and progressive delivery features to Kubernetes.

### URL for tool's homepage

https://github.com/argoproj/argo-rollouts

### Provide a basic test case to validate the tool's functionality.

```bash
kubectl argo rollouts version
```

### Virtual environments affected

- [X] Ubuntu 18.04
- [X] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [X] Windows Server 2016
- [X] Windows Server 2019
- [X] Windows Server 2022

### Can this tool be installed during the build?

```bash
Download the binary from https://github.com/argoproj/argo-rollouts/releases and make the binary executable
```

### Tool installation time in runtime

30 Seconds

### Are you willing to submit a PR?

yes

**Comment by al-cheb** [comment]
Hi @g14com0! Thank you for the request!
Considering insignificant installation time in runtime and maintenance concerns we would not like to add the tool to the image. Please use the commands you attached to install the tool in runtime.

Ubuntu Server:
```
- run: |
    curl -LO https://github.com/argoproj/argo-rollouts/releases/latest/download/kubectl-argo-rollouts-linux-amd64
    chmod +x ./kubectl-argo-rollouts-linux-amd64
    sudo mv ./kubectl-argo-rollouts-linux-amd64 /usr/local/bin/kubectl-argo-rollouts
    kubectl argo rollouts version
    
kubectl-argo-rollouts: v1.1.1+0716c5d
  BuildDate: 2021-11-29T19:14:05Z
  GitCommit: 0716c5d4417ec1cc507b24b3a400d07e4bf24303
  GitTreeState: clean
  GoVersion: go1.16.3
  Compiler: gc
  Platform: linux/amd64
```

Windows Server:
```
- run: |
    $url = "https://github.com/argoproj/argo-rollouts/releases/latest/download/kubectl-argo-rollouts-windows-amd64"
    [System.Net.WebClient]::new().DownloadFile($url, "C:\Windows\System32\kubectl-argo-rollouts.exe")
    kubectl argo rollouts version
    
kubectl-argo-rollouts: v1.1.1+0716c5d
  BuildDate: 2021-11-29T19:15:50Z
  GitCommit: 0716c5d4417ec1cc507b24b3a400d07e4bf24303
  GitTreeState: clean
  GoVersion: go1.16.3
  Compiler: gc
  Platform: windows/amd64
```
