### ISSUE TITLE
Permission issues on Windows restoring boost from cache

### ISSUE THREAD

**Issue by michaeltryby** [actions/virtual-environments#4679]
### Description

Insufficient permission to restore boost from cache on Windows2019. I use choco to install boost to C:\local. I use actions/cache to create a cache for the install. Restore fails because tar can't write back to C:\local. 

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [X] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

  Environment: windows-2019
  Version: 20211229.2

https://github.com/USEPA/Stormwater-Management-Model/runs/4445516497?check_suite_focus=true

### Is it regression?

Yes this used to work on windows-2016

### Expected behavior

Expected the boost install to restore from cache to C:\local

### Actual behavior

Boost was not restored because tar doesn't have permission to write to C:\local

### Repro steps

Step 1) Install boost using choco
Step 2) Cache boost using actions/cache
Step 3) Restore boost

**Comment by al-cheb** [comment]
Hey, @michaeltryby 
I see errors not related to permissions issue:
```
curl: (22) The requested URL returned error: 404 Not Found
ERROR: unable to download testfiles 
INFO: EXITING WITH ERRORS
Error: Process completed with exit code 1.
```

**Comment by michaeltryby** [comment]
@al-cheb Yes thanks. I am working on that one. Boost gets cached in the "Build and unit test" job.

**Comment by al-cheb** [comment]
> @al-cheb Yes thanks. I am working on that one. Boost gets cached in the "Build and unit test" job.

How do you install boost via choco?

**Comment by michaeltryby** [comment]
Actions step
```
    - name: Install boost
      if: steps.cache-boost.outputs.cache-hit != 'true'
      env:
        pkg_cmnd: choco install -y packages.config
      run: ${{ env.pkg_cmnd }}
```
packages.config
```
<?xml version="1.0" encoding="utf-8"?>

<packages>
  <package id="boost-msvc-14.1" version="1.74.0"/>
</packages>
```

**Comment by al-cheb** [comment]
@michaeltryby,
The bsd tar doesn't support symlinks which is default on Windows Server 2019. Could you please add tar.exe from git as the default one on Windows Server 2016?
```
 - name: Add tar.exe
    if: ${{ runner.os == 'Windows' }}
    run: |
          "C:\Program Files\Git\usr\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8
```

**Comment by michaeltryby** [comment]
@al-cheb I copy pasted directly from your post and got the following when I ran it

```
Run "C:\Program Files\Git\usr\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8
  "C:\Program Files\Git\usr\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8
  shell: C:\Windows\system32\cmd.EXE /D /E:ON /V:OFF /S /C "CALL "{0}""
  env:
    OMP_NUM_THREADS: 1
    BUILD_HOME: build
    TEST_HOME: nrtests
'"C:\Program Files\Git\usr\bin"' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by michaeltryby** [comment]
@al-cheb Thanks for your help. I added the step and got boost to restore from cache successfully.
