### ISSUE TITLE
Linux io_uring support and ulimit memlock

### ISSUE THREAD

**Issue by sullis** [actions/virtual-environments#4683]
### Description

OS:  Linux (ubuntu-latest)

I have a GitHub Actions workflow that tries to utilize io_uring from Java

https://github.com/sullis/netty-playground/runs/4450624231?check_suite_focus=true

The error message is:
```
java.lang.RuntimeException: failed to create io_uring ring fd Cannot allocate memory
	at io.netty.incubator.channel.uring.Native.ioUringSetup(Native Method)
	at io.netty.incubator.channel.uring.Native.createRingBuffer(Native.java:169)
	at io.netty.incubator.channel.uring.Native.createRingBuffer(Native.java:202)
	at io.netty.incubator.channel.uring.IOUring.<clinit>(IOUring.java:41)
```

In the workflow, I print the ulimit value:
```
$ ulimit -l
64
```

Is there any way to change the ulimit memlock value? Is there a workaround?

### Virtual environments affected

- [ ] Ubuntu 18.04
- [X] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

https://github.com/sullis/netty-playground/runs/4450624231?check_suite_focus=true

### Repro steps

Java code:
https://github.com/sullis/netty-playground/blob/main/src/test/java/io/github/sullis/netty/playground/IoUringTest.java

Workflow:
https://github.com/sullis/netty-playground/blob/main/.github/workflows/ci.yml

Run:
https://github.com/sullis/netty-playground/runs/4450624231?check_suite_focus=true

**Comment by al-cheb** [comment]
Hey, @sullis 

It affects only the running shell, that's why you should run all commands in it:
```
- name: Build
  run: |
          sudo env "PATH=$PATH" bash -c "ulimit -l 65536 && ulimit -a && mvn --no-transfer-progress -B clean test"
```

![image](https://user-images.githubusercontent.com/47745270/145161081-4affd029-b5dd-43c2-b281-2b4361c5d10a.png)

**Comment by sullis** [comment]
Thanks @al-cheb  - your solution works for me.  I will close this issue.
