### ISSUE TITLE
Add Xcode 13.2 RC 1

### ISSUE THREAD

**Issue by bielikb** [actions/virtual-environments#4684]
### Tool name

Xcode

### Tool license

Apple, Inc.

### Add or update?

- [X] Add
- [ ] Update

### Desired version

13.2 RC 1 (13C90)

### Brief description of tool

[Xcode IDE](https://developer.apple.com/xcode/)

### URL for tool's homepage

https://developer.apple.com/services-account/download?path=/Developer_Tools/Xcode_13.2_Release_Candidate/Xcode_13.2_Release_Candidate.xip

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [X] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Can this tool be installed during the build?

```bash
no
```

### Tool installation time in runtime

not affordable

### Are you willing to submit a PR?

no. I have no prior knowledge how to install new Xcode image on macOS 11 on GHA

**Comment by al-cheb** [comment]
Hey, @bielikb 
We are planning to start new image rollout with Xcode 13.2 RC1 and finish till next Tuesday.

**Comment by bielikb** [comment]
Perfect. Thanks for quick update @al-cheb !

**Comment by V-Zabayrachny** [comment]
Hello @bielikb. We have deployed a new image with Xcode 13.2 RC1.

**Comment by bielikb** [comment]
Perfect!
