### ISSUE TITLE
Did deployed instances become more resource constrained?

### ISSUE THREAD

**Issue by derekm** [actions/virtual-environments#4693]
### Description

Our Java unit tests started failing in Actions builds about a week and a half ago.

If I go re-run builds on old commits that passed, they all now fail.

Did instances used by GitHub Actions recently become more resource constrained?

I might suspect resource leaks in our latest code, but old commits with previously passing builds also now fail.

Thanks!

### Virtual environments affected

- [ ] Ubuntu 18.04
- [X] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Previously passing: https://github.com/pravega/pravega/actions/runs/1521651514/attempts/1
  Version: 20211122.1

Now failing: https://github.com/pravega/pravega/actions/runs/1521651514/attempts/2
  Version: 20211129.1

### Is it regression?

20211122.1

### Expected behavior

Tests should pass

### Actual behavior

Tests now fail as if the environment is too resource constrained

### Repro steps

1. Find a old build that used to pass
2. Re-run all jobs
3. Watch it fail every time now

**Comment by al-cheb** [comment]
Hey, @derekm 
We will take a look at it.

**Comment by dsame** [comment]
@derekm thanks, for you note, but my concern is the problem is with the connection to zookeeper and i see no evidences neither it was launched successfully of failed. If you can provide more info on this i could take a look as well

**Comment by derekm** [comment]
We found an issue in our tests around the New Year that once fixed allowed our builds to pass again. How it was passing previously, I don't understand, but we're fixed... Thanks!
