### ISSUE TITLE
The execution fails in the AZ of the latest version (Az 7.0.0)

### ISSUE THREAD

**Issue by mayong43111** [actions/virtual-environments#4698]
### Description

Cannot find type [Microsoft.Azure.Commands.ActiveDirectory.PSADPasswordCredential]: verify that the | assembly containing this type is loaded.

It works fine with older versions

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [X] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

sorry, no

### Repro steps

1. Install the AZ of the latest version
2. exec GenerateResourcesAndImage -SubscriptionId "" -ResourceGroupName "ActionsRG" -ImageGenerationRepositoryRoot "$pwd" -ImageType Windows2019 -AzureLocation "East US"

**Comment by al-cheb** [comment]
Hey, @mayong43111 
I have published a PR https://github.com/actions/virtual-environments/pull/4701. Could you please check and provide status?

**Comment by mayong43111** [comment]
thank you  @al-cheb , The testing results for RP #4701 look as following, The result is fine.

Host OS: Windows 2019
Packer : 1.7.8
Git : git version 2.34.1.windows.1
Azure-cli: 2.31.0
Azure Az PowerShell module : 7.0.0
source code : https://github.com/al-cheb/virtual-environments.git
branch : imggen-graph-cmdlet
command line ：``` GenerateResourcesAndImage -SubscriptionId "" -ResourceGroupName "myTestResourceGroup" -ImageGenerationRepositoryRoot "$pwd" -ImageType Windows2019 -AzureLocation "East US"` ``
