### ISSUE TITLE
Update Python 3.11.0a3

### ISSUE THREAD

**Issue by jepler** [actions/virtual-environments#4705]
### Tool name

python

### Tool license

PSF

### Add or update?

- [ ] Add
- [X] Update

### Desired version

3.11.0a3

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [ ] Windows Server 2022

**Comment by al-cheb** [comment]
Hey, @jepler 
We are working on to upload Python 3.11.0a3 version and using via [setup-python]( https://github.com/actions/setup-python) task. We will let you know when it is finish.

**Comment by miketimofeev** [comment]
@jepler the version has been uploaded to the python-version repository. Feel free to use it via https://github.com/actions/setup-python action.
I'm going to close the issue. Feel free to contact us if you have any concerns.
Thank you!
