### ISSUE TITLE
show broken link to Ubuntu2004-README.md

### ISSUE THREAD

**Issue by eitsupi** [actions/virtual-environments#4707]
### Description

The link to the document displayed in the workflow log does not work.

![image](https://user-images.githubusercontent.com/50911393/145424660-51ae3622-582e-4178-9b47-d01c9d447627.png)

### Virtual environments affected

- [ ] Ubuntu 18.04
- [X] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

https://github.com/actions/virtual-environments/blob/ubuntu20/20211208.3/images/linux/Ubuntu2004-README.md

### Repro steps

1. Run a workflow that uses ubuntu-latest.
2. Press the link from the log.

**Comment by al-cheb** [comment]
Hey, @eitsupi 
Sorry for inconvenience. We have found out some internal issue on Ubuntu images and rollback process is in progress.
