### ISSUE TITLE
Incomplete Llvm.Clang toolset support for windows-2022

### ISSUE THREAD

**Issue by dmitrykobets-msft** [actions/virtual-environments#4716]
### Description

Passing the `-T ClangCL` flag to `cmake` in `windows-2022` does not work, and errors with
```
-- Building for: Visual Studio 17 2022
-- The CXX compiler identification is unknown
CMake Error at CMakeLists.txt:6 (project):
  No CMAKE_CXX_COMPILER could be found.



-- Configuring incomplete, errors occurred!
See also "D:/a/1/s/build/CMakeFiles/CMakeOutput.log".
See also "D:/a/1/s/build/CMakeFiles/CMakeError.log".
```

Running the exact same pipeline except with `windows-2019` image instead of `windows-2022`, succeeds, 

```
-- Building for: Visual Studio 16 2019
-- The CXX compiler identification is Clang 12.0.0 with MSVC-like command-line
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/Llvm/x64/bin/clang-cl.exe - skipped
```

In the virtual environment README for `windows-2019`, there are entries for
```
Microsoft.VisualStudio.Component.VC.Llvm.Clang 16.11.31603.221
Microsoft.VisualStudio.Component.VC.Llvm.ClangToolset 16.3.29207.166
Microsoft.VisualStudio.ComponentGroup.NativeDesktop.Llvm.Clang 16.11.31603.221
```
But for `windows-2022`, there is only

```
Microsoft.VisualStudio.Component.VC.Llvm.ClangToolset 17.0.31804.368
```

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

20211206.1

https://dev.azure.com/cppstat/GSL/_build/results?buildId=258&view=results

### Expected behavior

Windows 2022 image should support VS with Clang

### Actual behavior

Windows 2022 image does not support VS with Clang, even though the ClangToolset is listed in the image description (README).

### Repro steps

Try building a cmake project with `-T ClangCL` with VS 2019 on `windows-2019` image, and then VS 2022 on `windows-2022` image. The 2019 version succeeds, the 2022 version fails.

**Comment by al-cheb** [comment]
Hey, @dmitrykobets-msft 
This `Microsoft.VisualStudio.Component.VC.Llvm.Clang` component was added in scope of https://github.com/actions/virtual-environments/pull/4670 PR.
