### ISSUE TITLE
Update Android SDK Build-Tools to 29.0.3 in Ubuntu and Windows

### ISSUE THREAD

**Issue by davidmigloz** [actions/virtual-environments#472]
**Tool information**
- Tool name: Android SDK Build-Tools
- Update
- Desired version: [29.0.3](https://developer.android.com/studio/releases/build-tools)
- Approximate size: ?

**Virtual environments affected**
- [ ] macOS 10.15
- [x] Ubuntu 16.04 LTS
- [x] Ubuntu 18.04 LTS
- [x] Windows Server 2016 R2
- [x] Windows Server 2019

**Comment by andy-mishechkin** [comment]
SDK has been updated.
New images has been tested for using this SDK version. If you will find some issues - feel free to reopen this ticket

**Comment by miketimofeev** [comment]
@davidmigloz sorry for the misinformation. VM image with the changes will be rolled out next week.

**Comment by andy-mishechkin** [comment]
Android SDK 29.0.3 has been validated in Windows and Ubuntu images - closing the issue.
If you'll detect some bugs - please feel free to reopen
