### ISSUE TITLE
[Help]Can I run virtual-environments in local computer?

### ISSUE THREAD

**Issue by hhhaiai** [actions/virtual-environments#4723]
### Description

Can I run virtual-environments in local computer?

### Virtual environments affected

- [X] Ubuntu 18.04
- [X] Ubuntu 20.04
- [X] macOS 10.15
- [X] macOS 11
- [X] Windows Server 2016
- [X] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

[Help]Can I get virtual-environments images , use in natvie ?

### Repro steps

1.
[Help]Can I get virtual-environments images , use in natvie ?
2.
test sth

**Comment by hhhaiai** [comment]
@nikolai-frolov   I want  use virtual-environments  in local computer,  how can I do?

**Comment by hhhaiai** [comment]
@nikolai-frolov   How can I do?

**Comment by nikolai-frolov** [comment]
Hello @hhhaiai, unfortunately we have no ability to provide a created VHDs but you can build an image locally by using Hyper-V or VirtualBox (there is no step-by-step guideline for this unfortunately).

**Comment by hhhaiai** [comment]
hi, mgd. thx. 

@nikolai-frolov  Our virtual-environments is docker image , or other?

**Comment by nikolai-frolov** [comment]
Virtual-environments repository contains the source used to create the [virtual environments](https://help.github.com/en/actions/reference/virtual-environments-for-github-hosted-runners) for GitHub Actions hosted runners, as well as the VM images of [Microsoft-hosted agents](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops#use-a-microsoft-hosted-agent) used for Azure Pipelines. To build a VM machine from this repo's source, see the [instructions](docs/create-image-and-azure-resources.md).

**Comment by hhhaiai** [comment]
HI， @nikolai-frolov  ok，get it. thx
