### ISSUE TITLE
Add yq

### ISSUE THREAD

**Issue by hendrikhalkow** [actions/virtual-environments#473]
**Tool information**
- Tool name: yq
- Add or update? Add
- Desired version: 3.1.2 or whatever is latest
- Approximate size: 5885736 bytes
- If this is an add request:
  - Brief description of tool: manipulate YAML files. I want to use this to dynamically add a version attribute to the Chart.yaml file in a Helm chart that comes from [semantic release](https://semantic-release.gitbook.io/semantic-release/).
  - URL for tool's homepage: https://github.com/mikefarah/yq

**Area for Triage**:

**Question, Bug, or Feature?**:
Feature

**Virtual environments affected**
- [x] macOS 10.15
- [x] Ubuntu 16.04 LTS
- [x] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Can this tool be installed during the build?**
As the build time should be as short as possible and this is a common tool, it shouldn't be installed during the build.

**Are you willing to submit a PR?**
yes

**Comment by thejoebourneidentity** [comment]
Is this tool applicable to all our environments, or Ubuntu only?

**Comment by hendrikhalkow** [comment]
It's for Ubuntu and macOS. See https://mikefarah.gitbook.io/yq/

**Comment by alepauly** [comment]
@hendrikhalkow This is a great candidate for a `setup-yq` Action instead of baking it into the image so we won't be adding it right now. Thanks for your suggestion.
