### ISSUE TITLE
Unable to load OSXFUSE/macFUSE kext in macOS-11

### ISSUE THREAD

**Issue by mcafaro** [actions/virtual-environments#4731]
### Description

Additional permissions were granted to allow installing OSXFUSE (now called macFUSE) on `macos-10.15` here: https://github.com/actions/virtual-environments/issues/598

However, while macFUSE can be installed on `macos-11`, its kernel extension cannot be loaded due to permissions issues. The kernel extension must be loaded to mount a filesystem using FUSE.

Please see the error messages produced on the `macos-11` image below. `load_macfuse` is a command to load the extension without rebooting the machine. Notice it produces a non-zero exit code. `kextload` is a lower-level command to load the extension. Notice it produces an error message stating that the extension identifier is not approved to load.

**macFUSE**
```
$ brew install macfuse
$ sudo /Library/Filesystems/macfuse.fs/Contents/Resources/load_macfuse; echo $?
1
$ sudo kextload /Library/Filesystems/macfuse.fs/Contents/Extensions/10.16/macfuse.kext
Executing: /usr/bin/kmutil load -p /Library/Filesystems/macfuse.fs/Contents/Extensions/10.16/macfuse.kext
Error Domain=KMErrorDomain Code=27 "Extension with identifiers com.apple.nke.rvi,io.macfuse.filesystems.macfuse not approved to load. Please approve using System Preferences." UserInfo={NSLocalizedDescription=Extension with identifiers com.apple.nke.rvi,io.macfuse.filesystems.macfuse not approved to load. Please approve using System Preferences.}
```

**OSXFUSE**
```
$ brew install osxfuse
$ sudo /Library/Filesystems/osxfuse.fs/Contents/Resources/load_osxfuse; echo $?
1
$ sudo kextload /Library/Filesystems/osxfuse.fs/Contents/Extensions/10.16/osxfuse.kext
Executing: /usr/bin/kmutil load -p /Library/Filesystems/osxfuse.fs/Contents/Extensions/10.16/osxfuse.kext
Error Domain=KMErrorDomain Code=27 "Extension with identifiers com.github.osxfuse.filesystems.osxfuse,com.apple.nke.rvi not approved to load. Please approve using System Preferences." UserInfo={NSLocalizedDescription=Extension with identifiers com.github.osxfuse.filesystems.osxfuse,com.apple.nke.rvi not approved to load. Please approve using System Preferences.}
```

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [X] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

macos-11 (20211207.1)

### Is it regression?

Yes. It works on macos-10.15 (20211207.1).

### Expected behavior

`$ sudo /Library/Filesystems/macfuse.fs/Contents/Resources/load_macfuse; echo $?`

Should display 0.

### Actual behavior

`$ sudo /Library/Filesystems/macfuse.fs/Contents/Resources/load_macfuse; echo $?`

Displays 1.

### Repro steps

```
brew install macfuse
sudo /Library/Filesystems/macfuse.fs/Contents/Resources/load_macfuse; echo $?
```

**Comment by nikolai-frolov** [comment]
Hello @mcafaro. Thanks for reporting, we'll take care about the issue investigation.

**Comment by mcafaro** [comment]
I just discovered you can load the kext on the `macos-10.15` image but not the `macos-11` image, so I updated the issue appropriately.

**Comment by GITHUBGUY12357999** [comment]
Ok, So can we see any changes after this change was implemented?

**Comment by GITHUBGUY12357999** [comment]
or not?

**Comment by nikolai-frolov** [comment]
Hi @mcafaro, I've investigated the issue and can confirm that issue exists (https://github.com/nikolai-frolov/image-testing/runs/4532750599?check_suite_focus=true), but looks like it's a compatibility issue of the macfuse tool with MacOS 11 (at least I found several similar issues like https://github.com/osxfuse/osxfuse/issues/828). Unfortunately, macfuse is external tool which is out of our responsibility so we can't do much here. We are going to close this one issue if you have no objections.

**Comment by mcafaro** [comment]
@nikolai-frolov Thanks for looking into it. I'll keep an eye on the macFUSE issue. Can you confirm the "com.apple.nke.rvi,io.macfuse.filesystems.macfuse" identifiers are actually on the approved list for `macos-11`?

I don't see it when I run:
```
$ sudo sqlite3 /private/var/db/SystemPolicyConfiguration/KextPolicy "select * from kext_policy;"
EG7KH642X6|com.vmware.kext.vmhgfs|1|VMware, Inc.|8
EG7KH642X6|com.vmware.kext.vmmemctl|1|VMware, Inc.|8
EG7KH642X6|com.vmware.kext.VMwareGfx|1|VMware, Inc.|8
Z3L495V9L4|com.intel.kext.intelhaxm|1|Intel Corporation Apps|8
```

**Comment by nikolai-frolov** [comment]
Hello @mcafaro, sorry for delay with answer. Unfortunately the way which was used in mentioned issue ([#598](https://github.com/actions/virtual-environments/issues/598)) is not applicable for MacOS 11 since the used feature ("/usr/sbin/spctl kext-consent add TEAMID") was closed for this version. We've investigated and tried additional ways for its resolving: TCC and KextPolicy DBs update, attempt to install macfuse -> apply permissions -> delete macfuse (since we still can't add this tool to image due to limitation of the tool license policy) but unfortunately all of them didn't allow to resolve issue for the second installation. Additionally we found the issue during "brew install macfuse" usage: for some cases window with new system software requires doesn't appear. It works fine for installation via .dmg file, so looks like it's a brew's issue.
We are going to close this issue since further investigation doesn't look possible. Please let us know if you have any objections or suggestions.

**Comment by mcafaro** [comment]
@nikolai-frolov OK, thanks for your effort. We really appreciate it! Feel free to close this issue.
