### ISSUE TITLE
Ubuntu 20.04 MySQL service start attempt failure

### ISSUE THREAD

**Issue by n3rdkid** [actions/virtual-environments#4732]
### Description

I have been using MySQL in my Github Actions workflows, I use the following command to start the service:
 `sudo /etc/init.d/mysql start`
 
But since a few hours ago, it started to fail.

Here is a screenshot of it in a sample project.

![image](https://user-images.githubusercontent.com/32503224/145840715-87704561-1430-41b8-b8e9-c49ba8546aa2.png)

Currently I fixed this issue by running  `sudo service mysql start` to start the service.

### Virtual environments affected

- [ ] Ubuntu 18.04
- [X] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

  Environment: ubuntu-20.04
  Version: 20211209.3
  Included Software: https://github.com/actions/virtual-environments/blob/ubuntu20/20211209.3/images/linux/Ubuntu2004-README.md
  Image Release: https://github.com/actions/virtual-environments/releases/tag/ubuntu20%2F20211209.3

### Is it regression?

No

### Expected behavior

The following screenshot shows a previous workflow run in a sample project.

![image](https://user-images.githubusercontent.com/32503224/145841439-d79af8c0-8c39-4292-98ec-04efed750e1f.png)

### Actual behavior

The following screenshot shows the current workflow.

![image](https://user-images.githubusercontent.com/32503224/145841294-4e909967-2a8c-4538-b1c5-0115c5ffa76d.png)

### Repro steps

```
run: |
     sudo /etc/init.d/mysql start
```

**Comment by wojsmol** [comment]
Hi
Try `sudo systemctl start mysql` instead.

**Comment by nikolai-frolov** [comment]
Hello @n3rdkid. Thanks for reporting, we'll take care about the issue investigation. At the first sight `sudo /etc/init.d/mysql start` doesn't look like correct approach, please try to use `sudo systemctl start mysql` as was suggested.

**Comment by n3rdkid** [comment]
@wojsmol Thank you. It is working.

@nikolai-frolov For your reference, we had been using the command as suggested in the following article. 

[Ubuntu virtual environments will no longer start the MySQL service automatically](https://github.blog/changelog/2020-02-21-github-actions-breaking-change-ubuntu-virtual-environments-will-no-longer-start-the-mysql-service-automatically/)

**Comment by miketimofeev** [comment]
@n3rdkid it looks like the behavior changed after this PR https://github.com/actions/virtual-environments/pull/4674 since the installation method has changed. We will take a look if it is possible to return sudoless service start.
Sorry for the inconvenience.

**Comment by wojsmol** [comment]
@miketimofeev This looks like `init.d` vs `systemd` not `sudo` vs `non-sudo`.

**Comment by mikhailkoliada** [comment]
Hello @n3rdkid!

`/etc/init.d/` scripts are the canonical-provided ones to keep backward compatibility with old sysVinit systems. This approach is long ago deprecated and should not be used. In our recent ubuntu20.04 images we have downgraded canonical-provided mysql-8.0.27 to 8.0.26 as the former one has bugs. We used oracle-supplied deb packages for the images and they surely do not have that legacy bit. As was said, the best thing to do is to switch to the `systemctl` command so you do not depend on legacy stuff anymore.

As there is nothing for us to do I am going to close the issue now, feel free to ping us if you have questions left.

**Comment by n3rdkid** [comment]
@mikhailkoliada Thank you for the quick response. :bow:

**Comment by mattlord** [comment]
Hi @mikhailkoliada! 

Just FYI, this change is likely to cause far more problems than it solved. It broke any of our actions that use ubuntu-latest and simply try to install the `mysql-{client, server}` packages via `apt-get`. Installing either one now exits with:
```
The following packages have unmet dependencies:
 mysql-client : Depends: mysql-client-8.0 but it is not going to be installed
 mysql-server : Depends: mysql-server-8.0 but it is not going to be installed
```

For an example that's failing:
  - source: https://github.com/vitessio/vitess/blob/main/.github/workflows/check_make_parser.yml#L31
  - run: https://github.com/vitessio/vitess/runs/4510817416?check_suite_focus=true

So I'm unsure how you would even get to the point where you try to start mysqld?

Should I open a new ticket for this?

Thank you!

**Comment by mikhailkoliada** [comment]
We have restored the old init script for Ubuntu 20.04. It should be available for everyone by the end of this week (expect Thursday).

**Comment by mikhailkoliada** [comment]
The newer image has been just released, and the fix is available to anyone.
