### ISSUE TITLE
Update Python 3.10 to 3.10.1

### ISSUE THREAD

**Issue by felix-hilden** [actions/virtual-environments#4735]
### Tool name

Python 3.10

### Tool license

PSF license for Python 3.10.1

### Add or update?

- [ ] Add
- [X] Update

### Desired version

3.10.1

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [ ] Windows Server 2022

**Comment by felix-hilden** [comment]
A bit of background as well: the bugfix release is currently preventing some Python 3.10 tests with two common libraries: the ubiquitous test runner `pytest` and a popular HTTP client `requests`. I documented this in an [issue](https://github.com/felix-hilden/sphinx-codeautolink/issues/33#issuecomment-985594294).

**Comment by miketimofeev** [comment]
Hey @felix-hilden!
We will update the images with python 3.10.1 next week yet we are currently struggling with the macOS 3.10.1 build thus macOS update can be delayed.

**Comment by felix-hilden** [comment]
Thanks for the quick response, looking forward to the update!

**Comment by miketimofeev** [comment]
@felix-hilden windows and ubuntu images were updated. The macOS one will be updated early next year.

**Comment by mikhailkoliada** [comment]
macOS containing python 3.10.1 has been deployed.
