### ISSUE TITLE
Uninstalling moby in the docker.sh script

### ISSUE THREAD

**Issue by vladonemo** [actions/virtual-environments#474]
**Describe the bug**
First of all, the moby is misspelled in the docker.sh:
```
apt-get remove -y moby-engine mobi-cli
``` 
Notice the 'i' in the mobi-cli.

Why is moby actually removed and installed again in this script? It is installed in the docker-moby.sh.

**Area for Triage**: 
Containers

**Question, Bug, or Feature?**: 
Bug

**Virtual environments affected**
- [ ] macOS 10.15
- [x] Ubuntu 16.04 LTS
- [x] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Expected behavior**
The moby should not be reinstalled in docker.sh script

**Comment by maxim-lobanov** [comment]
Hi!
We are working to fix it in scope of the PR #470

**Comment by vladonemo** [comment]
Ok, fair enough ;) Closing the issue and the related PR then.

**Comment by maxim-lobanov** [comment]
@vladonemo , Anyway, thank you for contribution! You are welcome
