### ISSUE TITLE
Problems getting python-apt properly installed

### ISSUE THREAD

**Issue by elear** [actions/virtual-environments#4741]
### Description

I am struggling to find a way to get python apt modules to properly load.  This is for a program that needs to examine the install using apt.cache and apt.package etc.

I've tried whacking both the PYTHONPATH and LD_LIBRARY_PATH but I am still eating it.  Thanks for any and all help.

### Virtual environments affected

- [ ] Ubuntu 18.04
- [X] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

ubuntu-latest with python 3.9.9 (I image it would recur with 3.10 as well).

### Is it regression?

don't know

### Expected behavior

No traceback

### Actual behavior

```
 Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.9.9/x64/bin/apt2sbom", line 5, in <module>
    from apt2sbom import cli
  File "/home/runner/work/apt2sbom/apt2sbom/apt2sbom/__init__.py", line 7, in <module>
    from .dp2json import *
  File "/home/runner/work/apt2sbom/apt2sbom/apt2sbom/dp2json.py", line 11, in <module>
    from apt.cache import Cache
  File "/usr/lib/python3/dist-packages/apt/__init__.py", line 23, in <module>
    import apt_pkg
ModuleNotFoundError: No module named 'apt_pkg'
Error: Process completed with exit code 1.
```

### Repro steps

apt install python-apt
or
apt install python3-apt

foo.py:

```
from apt.cache import Cache
```

**Comment by nikolai-frolov** [comment]
Hello @elear. Thanks for reporting, we'll take care about the issue investigation.

**Comment by V-Zabayrachny** [comment]
Hello @elear. Could you share your workflow, please? The usage scenario is a bit unclear for us at the moment

**Comment by elear** [comment]
Of course. If you have a look at [apt2sbom](https://github/com/apt2sbom), and check out the fix-integration branch, you can see all of my toils, exposed to the world.  Check out pylint.yml, and blame away.  README.md explains what I'm trying to do.  I've held off on further CI/CD actions until you guys have had a chance to tell me what I'm doing wrong ;-)

**Comment by elear** [comment]
Sorry link correction: https://github.com/elear/apt2sbom.

**Comment by V-Zabayrachny** [comment]
I would like to clarify how pythons are installed on our Ubuntu20 image. What we have is:
- Python 3.8.10 installed from the Ubuntu upstream — this is the default python thus when you run  `sudo apt-get -y install python-apt` the python-apt module is being installed for this default python
- Lots of pre-cached pythons (3.7, 3.8, 3.9, 3.10) are located in the /opt/hostedtoolcache directory and intended to use with the https://github.com/actions/setup-python action. When you specify the version the action simply adds this version to the PATH and that's it.
Given the explanation above I'm afraid you can't install python-apt module to any non-default python version from the toolcache. The possible options here:
- Use the default python
- Install any python3 version from the ppa (for example https://launchpad.net/~deadsnakes/+archive/ubuntu/ppa), install apt-python, and do a trick described here https://askubuntu.com/questions/1069087/modulenotfounderror-no-module-named-apt-pkg-error

**Comment by elear** [comment]
Ok, thanks for the advice.  I understand the difficulty in this case, so I'm sticking right now with just the built in ubuntu version of python.
