### ISSUE TITLE
[All OSs] Python version 3.5 will be removed from the images on January 24, 2022

### ISSUE THREAD

**Issue by miketimofeev** [actions/virtual-environments#4744]
### Breaking changes

Pre-cached python 3.5 will be removed from the images.

### Target date

January 24, 2022

### The motivation for the changes

According to our [Software and image guidelines](https://github.com/actions/virtual-environments/blob/main/docs/software-and-images-guidelines.md) tools and versions will typically be removed 6 months after they are deprecated or have reached end-of-life. Python 3.5 [has reached the end of life ](https://github.com/actions/virtual-environments/blob/main/docs/software-and-images-guidelines.md)more than a year ago thus we have to remove it.

### Possible impact

- GitHub actions — runs can take a bit more time as https://github.com/actions/setup-python will have to download and install 3.5 version instead of using the pre-cached one
- AzureDevOps — builds using python 3.5 will be broken

### Virtual environments affected

- [X] Ubuntu 18.04
- [X] Ubuntu 20.04
- [X] macOS 10.15
- [ ] macOS 11
- [X] Windows Server 2016
- [X] Windows Server 2019
- [ ] Windows Server 2022

### Mitigation ways

- GitHub actions — nothing needed, the https://github.com/actions/setup-python is able to download the version on the fly
- AzureDevOps — consider switching your projects to more recent python versions (at least 3.7)

**Comment by BrianMouncer** [comment]
WRT "According to our Software and image guidelines tools and versions will typically be removed 6 months after they are deprecated or have reached end-of-life. Python 3.5 has reached the end of life more than a year ago thus we have to remove it."

Python 3.6 was supposed to to hit End of Life last month.
Does that mean I can expect Python 3.6 to be removed around  June or July of this year?

**Comment by miketimofeev** [comment]
@BrianMouncer we will also consider Python 3.6 usage across GH Actions and ADO before removing the version so I'd say _not early_ than July

**Comment by freddy123098** [comment]
So, should a open a pull request and see the changes there or something like that?

And will this do any help to this issue?

**Comment by freddy123098** [comment]
But I think that it was in July right. Or is it in a different time and month?

**Comment by moovy2** [comment]
> ### Veranderingen doorbreken
> Python 3.5 met pre-cache wordt uit de afbeeldingen verwijderd.
> 
> ### Streefdatum
> 24 januari 2022
> 
> ### De motivatie voor de veranderingen
> Volgens onze [software- en afbeeldingsrichtlijnen](https://github.com/actions/virtual-environments/blob/main/docs/software-and-images-guidelines.md) worden tools en versies meestal 6 maanden nadat ze zijn afgeschaft of het einde van de levensduur hebben bereikt, verwijderd. Python 3.5 heeft meer dan een jaar geleden [het einde van zijn levensduur bereikt, ](https://github.com/actions/virtual-environments/blob/main/docs/software-and-images-guidelines.md)dus we moeten het verwijderen.
> 
> ### Mogelijke impact
> * GitHub-acties - uitvoeringen kunnen iets meer tijd in beslag nemen omdat https://github.com/actions/setup-python 3.5-versie moet downloaden en installeren in plaats van de vooraf in de cache opgeslagen versie te gebruiken
> * AzureDevOps — builds met python 3.5 worden verbroken
> 
> ### Getroffen virtuele omgevingen
> * [x]  Ubuntu 18,04
> * [x]  Ubuntu 20,04
> * [x]  MacOS 10,15
> * [ ]  MacOS 11
> * [x]  Windows Server 2016
> * [x]  Windows Server 2019
> * [ ]  Windows Server 2022
> 
> ### Mitigatie manieren
> * GitHub-acties - niets nodig, de https://github.com/actions/setup-python kan de versie on-the-fly downloaden
> * AzureDevOps: overweeg uw projecten over te schakelen naar recentere Python-versies (ten minste 3.7)

**Comment by andresmo001** [comment]
Start the software

**Comment by MaksimZhukov** [comment]
The images without Python 3.5 have been deployed.

**Comment by asmeurer** [comment]
Anyone know what the best workaround is for those of us who still need to test against 3.5?
