### ISSUE TITLE
Add UWP C++ tools for ARM64 (was on windows-2019, missing from windows-2022)

### ISSUE THREAD

**Issue by mcooley** [actions/virtual-environments#4745]
### Tool name

C++ Universal Windows Platform support for v143 build tools (ARM64)

### Tool license

(part of Visual Studio)

### Add or update?

- [X] Add
- [ ] Update

### Desired version

v143 (matching Visual Studio)

### Brief description of tool

Visual Studio's C++ toolset for UWP apps has a separate component which is needed to compile apps for the ARM64 platform.

The windows-2019 image included this component, but windows-2022 does not.

### URL for tool's homepage

https://docs.microsoft.com/en-us/visualstudio/install/workload-component-id-vs-community?view=vs-2022#universal-windows-platform-development

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Can this tool be installed during the build?

Yes, this can be installed during Visual Studio installation. See the windows-2019 toolset for reference: https://github.com/actions/virtual-environments/blob/07a22999fec8b179e4905490ed5910bd7e827c15/images/win/toolsets/toolset-2019.json#L306

The component name is "Microsoft.VisualStudio.Component.UWP.VC.ARM64".

### Are you willing to submit a PR?

_[Edit]_ Yes, submitted #4750

**Comment by miketimofeev** [comment]
Hi @mcooley!
We don't have any objections, thanks for your contribution!

**Comment by miketimofeev** [comment]
@mcooley the new image has been deployed!
I'm going to close the issue. Please feel free to contact us if you have any concerns.
Thank you!
