### ISSUE TITLE
[ubuntu-18.04] Mirror http://azure.archive.ubuntu.com/ubuntu now corrupted for i386, breaks libexpat CI

### ISSUE THREAD

**Issue by hartwork** [actions/virtual-environments#4746]
### Description

Starting today, a corruption of files in default mirror http://azure.archive.ubuntu.com/ubuntu breaks `sudo dpkg --add-architecture i386 && sudo apt-get update` and hence now makes image `ubuntu-18.04` builds fail for libexpat that were working fine yesterday:

```
[..]
# sudo dpkg --add-architecture i386
# sudo apt-get update
[..]
Err:12 http://azure.archive.ubuntu.com/ubuntu bionic-updates/main i386 Packages
  File has unexpected size (1386788 != 1386576). Mirror sync in progress? [IP: 52.250.76.244 80]
  Hashes of expected file:
   - Filesize:1386576 [weak]
   - SHA256:d3d30b2c4850b0509bb30096b534bc70358cc3b32ace288d4bf2360128a039f7
   - SHA1:f9963614468ce6227f3baff07d651d4a270f410f [weak]
   - MD5Sum:4313a0c7624a8b92ef4f2737ff97b76d [weak]
  Release file created at: Wed, 15 Dec 2021 22:24:39 +0000
[..]
E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/dists/bionic-updates/main/binary-i386/Packages.xz  File has unexpected size (1386788 != 1386576). Mirror sync in progress? [IP: 52.250.76.244 80]
   Hashes of expected file:
    - Filesize:1386576 [weak]
    - SHA256:d3d30b2c4850b0509bb30096b534bc70358cc3b32ace288d4bf2360128a039f7
    - SHA1:f9963614468ce6227f3baff07d651d4a270f410f [weak]
    - MD5Sum:4313a0c7624a8b92ef4f2737ff97b76d [weak]
   Release file created at: Wed, 15 Dec 2021 22:24:39 +0000
E: Some index files failed to download. They have been ignored, or old ones used instead.
[..]
```

I have given it some time to go away, but after a few hours and build attempt 4 with the same failure, reporting the issue here seemed like the right step. Any chance this could be fixed?

Version: 20211209.3
Build: https://github.com/libexpat/libexpat/runs/4541423933

### Virtual environments affected

- [X] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Version: 20211209.3
Build: https://github.com/libexpat/libexpat/runs/4541423933

### Is it regression?

20211209.3 (same version, worked yesterday)

### Expected behavior

Default mirror http://azure.archive.ubuntu.com/ubuntu should be free of corruptions and ` sudo dpkg --add-architecture i386 && apt-get update` should work out of the box, like it still did yesterday. Thank you!

### Actual behavior

Mirror http://azure.archive.ubuntu.com/ubuntu seems to have become corrupted:
```
[..]
# sudo dpkg --add-architecture i386
# sudo apt-get update
[..]
Err:12 http://azure.archive.ubuntu.com/ubuntu bionic-updates/main i386 Packages
  File has unexpected size (1386788 != 1386576). Mirror sync in progress? [IP: 52.250.76.244 80]
  Hashes of expected file:
   - Filesize:1386576 [weak]
   - SHA256:d3d30b2c4850b0509bb30096b534bc70358cc3b32ace288d4bf2360128a039f7
   - SHA1:f9963614468ce6227f3baff07d651d4a270f410f [weak]
   - MD5Sum:4313a0c7624a8b92ef4f2737ff97b76d [weak]
  Release file created at: Wed, 15 Dec 2021 22:24:39 +0000
[..]
E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/dists/bionic-updates/main/binary-i386/Packages.xz  File has unexpected size (1386788 != 1386576). Mirror sync in progress? [IP: 52.250.76.244 80]
   Hashes of expected file:
    - Filesize:1386576 [weak]
    - SHA256:d3d30b2c4850b0509bb30096b534bc70358cc3b32ace288d4bf2360128a039f7
    - SHA1:f9963614468ce6227f3baff07d651d4a270f410f [weak]
    - MD5Sum:4313a0c7624a8b92ef4f2737ff97b76d [weak]
   Release file created at: Wed, 15 Dec 2021 22:24:39 +0000
E: Some index files failed to download. They have been ignored, or old ones used instead.
[..]
```

### Repro steps

- Use image `ubuntu-18.04`
- `sudo dpkg --add-architecture i386`
- `sudo apt-get update`

**Comment by nikolai-frolov** [comment]
Hello @hartwork. Thanks for reporting, we'll take care about the issue investigation.

**Comment by hartwork** [comment]
A quick update: attempt #5 seems to have worked just now: https://github.com/libexpat/libexpat/actions/runs/1583922433 .

**Comment by miketimofeev** [comment]
@hartwork look like there was an issue on Canonical side rather than the problem with the image

**Comment by hartwork** [comment]
@miketimofeev I see your point. Should we close the issue?

**Comment by miketimofeev** [comment]
@hartwork yes, please. If the problem appears again feel free to reopen the issue.
Thank you!
