### ISSUE TITLE
Rscript not available on macOS 11

### ISSUE THREAD

**Issue by edvinf** [actions/virtual-environments#4747]
### Description

For macOS 11 R seems to install both for version 4.0.5 and 3.6.3, but the command Rscript does not seem to be available the way it was for macOS 10.15.

Issues with R 4.* was listed in the issue reporting that macOS-latest would change to macOS-11, and standard tool request process is referred to, but it seems that also R 4.1.2 is now available. This version fails at a different stage in the process compared to 4.05 and 3.6.3.

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [X] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

The following examples failed after macOS-latest changed from macOS 10.15 to macOS 11:
4.0.5:
https://github.com/StoXProject/RstoxData/runs/4531222963?check_suite_focus=true#step:6:5
3.6.3:
https://github.com/StoXProject/RstoxData/runs/4531223017?check_suite_focus=true#step:6:5

R install was OK for these two:
3.6.3:
https://github.com/StoXProject/RstoxData/runs/4531223017?check_suite_focus=true#step:4:40
4.0.5:
https://github.com/StoXProject/RstoxData/runs/4531222963?check_suite_focus=true#step:4:50

Version 4.1.2 exhibits different behaviour and fails at:
https://github.com/StoXProject/RstoxData/runs/4531222994?check_suite_focus=true#step:4:56
Also for 4.1.2 install is reported to be successful:
https://github.com/StoXProject/RstoxData/runs/4531222994?check_suite_focus=true#step:4:50

### Is it regression?

yes

### Expected behavior

Expected Rscript to be running as in:

version 3.6.3 and 4.0.5:
https://github.com/StoXProject/RstoxData/runs/4401269504?check_suite_focus=true
https://github.com/StoXProject/RstoxData/runs/4401269572?check_suite_focus=true

version 4.1.2:
https://github.com/StoXProject/RstoxData/runs/4401269541?check_suite_focus=true

### Actual behavior

Build fails with error message:

Error: Rscript: command not found

### Repro steps

I believe the issue can be reproduced by the following steps:
1. set up a macOS-latest image with one of the R versions 3.6.3, 4.0.5 or 4.1.2
2. set up some action that runs in shell 'Rscript'. snippet from a yaml file below.
3. contrast with macOS-10.15 to verify that it works there.

yaml-snippet:
- name: Query dependencies
        run: |
          install.packages('remotes')
          saveRDS(remotes::dev_package_deps(dependencies = TRUE), "depends.Rds", version = 2)
          writeLines(sprintf("R-%i.%i", getRversion()$major, getRversion()$minor), ".github/R-version")
        shell: Rscript {0}

**Comment by nikolai-frolov** [comment]
Hello @edvinf. Thanks for reporting, we'll take care about the issue investigation.

**Comment by al-cheb** [comment]
Hey, @edvinf 
Could you please use `r-lib/actions/setup-r@v2` action instead of v1?
` - uses: r-lib/actions/setup-r@v2`
![image](https://user-images.githubusercontent.com/47745270/146409009-e9527930-1198-42a7-870f-39e87c4de019.png)
![image](https://user-images.githubusercontent.com/47745270/146409146-664e6742-29b9-41a6-85c3-d2b56cfad914.png)

**Comment by edvinf** [comment]
Thanks a lot, that resolved my problems for all three builds.
