### ISSUE TITLE
Sometimes workflow is unable to find Xcode 13.2

### ISSUE THREAD

**Issue by simondelphia** [actions/virtual-environments#4749]
### Description

Most of the time running `setup-xcode` in our workflow works fine (at least 80% of the time). But sometimes it fails to find Xcode 13.2 and the workflow run fails prematurely. 

Failure:

```
Prepare all required actions
Getting action download info
Download action repository 'maxim-lobanov/setup-xcode@v1' (SHA:86839dbc5bbd0e843469a29e29672baa578e81f6)
Run ./.github/workflows/actions/xcode
Run maxim-lobanov/setup-xcode@v1
Switching Xcode to version '13.2'...
Available versions:
┌─────────┬──────────┬─────────────┬─────────────┬────────┬──────────────────────────────────┐
│ (index) │ version  │ buildNumber │ releaseType │ stable │               path               │
├─────────┼──────────┼─────────────┼─────────────┼────────┼──────────────────────────────────┤
│    0    │ '13.2.0' │ '13C5081f'  │   'Beta'    │ false  │  '/Applications/Xcode_13.2.app'  │
│    1    │ '13.1.0' │ '13A1030d'  │    'GM'     │  true  │  '/Applications/Xcode_13.1.app'  │
│    2    │ '13.0.0' │  '13A233'   │    'GM'     │  true  │  '/Applications/Xcode_13.0.app'  │
│    3    │ '12.5.1' │  '12E507'   │    'GM'     │  true  │ '/Applications/Xcode_12.5.1.app' │
│    4    │ '12.4.0' │   '12D4e'   │    'GM'     │  true  │  '/Applications/Xcode_12.4.app'  │
│    5    │ '11.7.0' │  '11E801a'  │    'GM'     │  true  │  '/Applications/Xcode_11.7.app'  │
└─────────┴──────────┴─────────────┴─────────────┴────────┴──────────────────────────────────┘
Error: Could not find Xcode version that satisfied version spec: '13.2'
```

Success:

```
Prepare all required actions
Getting action download info
Download action repository 'maxim-lobanov/setup-xcode@v1' (SHA:86839dbc5bbd0e843469a29e29672baa578e81f6)
Run ./.github/workflows/actions/xcode
Run maxim-lobanov/setup-xcode@v1
Switching Xcode to version '13.2'...
Xcode is set to 13.2.0 (13C90)
```

So it seems that some of Github Action's machines are still running the RC build of Xcode (13C5081f) whereas others have the new one (13C90). Why is there variation?

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [X] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

See comments below

### Expected behavior

Xcode 13.2 GM should either be consistently available or not available.

### Actual behavior

Xcode 13.2 GM is unavailable sometimes. 

### Repro steps

1. Create workflow that runs [`setup-xcode`](https://github.com/marketplace/actions/setup-xcode-version)
2. Specify Xcode version as "13.2" for the workflow
3. Run several times

**Comment by al-cheb** [comment]
cc @maxim-lobanov , Any ideas as the owner task?

**Comment by miketimofeev** [comment]
Hi @simondelphia!
Could you provide an example of such run and also provide an image version? We have checked all the environments and it seems all of them are updated with the latest image.
Here is how to find the image version
![image](https://user-images.githubusercontent.com/48208649/146329370-0bbbb3ba-ff09-496e-86ba-99c6b2e02ebd.png)

**Comment by simondelphia** [comment]
Oh there, thank you

This is from a failed run that couldn't find Xcode:

Started at Thu, 16 Dec 2021 04:41:54 GMT
```
Current runner version: '2.285.1'
Operating System
  macOS
  11.6.1
  20G224
Virtual Environment
  Environment: macos-11
  Version: 20211127.1
  Included Software: https://github.com/actions/virtual-environments/blob/macOS-11/20211127.1/images/macos/macos-11-Readme.md
  Image Release: https://github.com/actions/virtual-environments/releases/tag/macOS-11%2F20211127.1
Virtual Environment Provisioner
  1.0.0.0-main-20211208-1
```

A successful run: Thu, 16 Dec 2021 04:47:40 GMT

```
Current runner version: '2.285.1'
Operating System
  macOS
  11.6.1
  20G224
Virtual Environment
  Environment: macos-11
  Version: 20211207.1
  Included Software: https://github.com/actions/virtual-environments/blob/macOS-11/20211207.1/images/macos/macos-11-Readme.md
  Image Release: https://github.com/actions/virtual-environments/releases/tag/macOS-11%2F20211207.1
Virtual Environment Provisioner
  1.0.0.0-main-20211208-1
```

Looking at our runs it seems to have happened about 5 times since we switched to specifying Xcode 13.2 (2 days ago) out of  a couple dozens runs total since then.

**Comment by miketimofeev** [comment]
@simondelphia we found some issues with the configuration, all the environments should have `20211207.1` version now, sorry for the inconvenience.
I'm going to close the issue. Please feel free to contact us if you have any concerns.
Thank you!
