### ISSUE TITLE
Add Service Fabric SDK 8.2.1235.9590 to the windows-2022 image

### ISSUE THREAD

**Issue by edferretti** [actions/virtual-environments#4751]
### Tool name

Service Fabric SDK

### Tool license

GNU General Public License v3.0

### Add or update?

- [X] Add
- [ ] Update

### Desired version

8.2.1235.9590

### Brief description of tool

Powershell cmdlets from the Service Fabric SDK are used to connect to Service Fabric clusters.
The [windows-2019 image](https://github.com/actions/virtual-environments/blob/win19/20211207.2/images/win/Windows2019-Readme.md) has Service Fabric SDK 8.2.1235.9590, so it should be straightforward to install it on windows-2022 as well.

### URL for tool's homepage

https://techcommunity.microsoft.com/t5/azure-service-fabric-blog/azure-service-fabric-8-2-release/ba-p/2895108

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [X] Windows Server 2022

**Comment by miketimofeev** [comment]
Hi @edferretti!
I'm afraid Service Fabric SDK is not yet available for windows-2022, please take a look at this issue
https://github.com/actions/virtual-environments/issues/4546
I'm going to close this one, please feel free to reopen once the support for 2022 is available.
