### ISSUE TITLE
Microsoft Hosted Azure Pipeline Agent windows 2022 - Default Uses Nuget Tool Version 4.1.X whereas Azure Agent Windows 2019 -Default Uses Nuget Tool Version 5.8.x ? Any logic during Nuget Version selection

### ISSUE THREAD

**Issue by 199219921992** [actions/virtual-environments#4754]
### Description

We are experiencing a weird behavior of Azure Pipeline Agents windows 2022 and 2019 where the default usage of Nuget tool version to download Nuget packages are different even though both supports latest 6.0.0 Nuget tool version.

We would like to know is there a bug with Azure Pipeline agent or what is the factor Azure DevOps consider in order to pick the Nuget tool version at 2022 and 2019 windows agent.  

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [X] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

Version- 20211122.0 (https://dev.azure.com/ZEISSgroup-VIS/VTS-VISUCONSULT%20500/_build/results?buildId=43155&view=logs&j=b40dce07-9987-5d5c-66c7-f1cbf9f58af1&t=5a2e6d53-4472-45ee-bc12-52bfd7e2ef5f&l=6)

For Log 2022- https://dev.azure.com/ZEISSgroup-VIS/VTS-VISUCONSULT%20500/_build/results?buildId=43155&view=logs&j=b40dce07-9987-5d5c-66c7-f1cbf9f58af1&t=8e95c669-db9d-57d4-173d-664f7cfffe5b&l=9

Version- 20211212.1 (https://dev.azure.com/ZEISSgroup-VIS/VTS-VISUCONSULT%20500/_build/results?buildId=46487&view=logs&j=728319a4-47c5-53aa-abac-b155214c1fb4&t=d2e03859-33ee-433b-8202-49852af51ad9&l=8)

For Log 2019- https://dev.azure.com/ZEISSgroup-VIS/VTS-VISUCONSULT%20500/_build/results?buildId=46487&view=logs&j=728319a4-47c5-53aa-abac-b155214c1fb4&t=b08a384f-e8ef-576f-001a-de44357da351&l=11

### Repro steps

When same pipeline run with selection 2022 and 2019 the behavior of Nuget tool version is different.

For Windows Microsoft Hosted Agent 2022 selects- 4.1.X as Nuget tool version
For Windows Microsoft Hosted Agent 2019 selects- 5.8.X as Nuget tool version

**Comment by nikolai-frolov** [comment]
Hello @199219921992. Thanks for reporting, we'll take care about the issue investigation.

**Comment by 199219921992** [comment]
Any Update on above request please?

**Comment by dibir-magomedsaygitov** [comment]
Hello @199219921992. We are investigating the issue at the moment. We will come back with the results as soon as we have anything to share. Thank you for your patience.

**Comment by dibir-magomedsaygitov** [comment]
Hello @199219921992. In order to use 6.0.0 Nuget tool version you have to add [NuGet Tool Installer task](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/tool/nuget?view=azure-devops). See example:
```
steps:
- task: NuGetToolInstaller@1
  displayName: 'Use NuGet 6'
  inputs:
    versionSpec: 6.0.0
```

**Comment by dibir-magomedsaygitov** [comment]
Hello @199219921992. Any updates on the issue?

**Comment by dibir-magomedsaygitov** [comment]
Hello @199219921992. I'm going to close this issue. Please use [NuGet Tool Installer task](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/tool/nuget?view=azure-devops) in order to use 6.0.0 Nuget tool version. In case of any questions or concerns feel free to contact us.

**Comment by 199219921992** [comment]
Hi, We wanted to understand the Azure Pipeline agent "windows-2022" seems to pick different version of Nuget tool to run the restore as shown above.

Just want to know how Azure Pipeline agent gonna a pickup the Nuget tool version? Is there any criteria it follows if we doesn't mentioned "Nuget tool Installer" step.

**Comment by al-cheb** [comment]
> Hi, We wanted to understand the Azure Pipeline agent "windows-2022" seems to pick different version of Nuget tool to run the restore as shown above.
> 
> Just want to know how Azure Pipeline agent gonna a pickup the Nuget tool version? Is there any criteria it follows if we doesn't mentioned "Nuget tool Installer" step.

Nuget version is the same for Win19&Win22:

Windows Server 2019 - https://github.com/actions/virtual-environments/blob/main/images/win/Windows2019-Readme.md:
![image](https://user-images.githubusercontent.com/47745270/149078634-d0fbc81d-f6a3-41f2-8032-cbc50228b0d7.png)
![image](https://user-images.githubusercontent.com/47745270/149078311-e76fdb20-159c-47a7-b236-7621d72e7fad.png)


Windows Server 2022 - https://github.com/actions/virtual-environments/blob/main/images/win/Windows2022-Readme.md:
![image](https://user-images.githubusercontent.com/47745270/149078672-4eae2524-9654-4218-bb48-92c58fe35cd7.png)
![image](https://user-images.githubusercontent.com/47745270/149078378-7c64e87e-36d2-4ad7-bafb-b5db05c77776.png)
