### ISSUE TITLE
Add Visual Studio 2022 for Mac to macos-11 instance

### ISSUE THREAD

**Issue by CartBlanche** [actions/virtual-environments#4762]
### Tool name

Visual Studio 2022 for Mac

### Tool license

MS-PL (I think) It's a Microsoft product so unsure.

### Add or update?

- [X] Add
- [ ] Update

### Desired version

17.0.x.x

### Brief description of tool

Latest (preview) version of the Visual Studio for Mac IDE.

### URL for tool's homepage

https://devblogs.microsoft.com/visualstudio/visual-studio-2022-for-mac-preview-4/

### Provide a basic test case to validate the tool's functionality.

```bash
The current version that is installed on your Mac instances (VS 8.10.x) allows the installation of .NET 6, but it cannot build projects that use some of the latest features from the language (eg. global uses) as those features are only supported in the VS2022 for Mac (17.0.x.x).
```

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [X] macOS 10.15
- [X] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Can this tool be installed during the build?

```bash
Not that I'm aware of, as it's currently only available as a dmg, which contains an Installer exe/app inside it. It may be possible to launch that exe/app silently, after mounting the dmg, but you'd have to talk to the the VS4M devs inside Microsoft to find out what the parameters are. 
If you can tell me I'll do that temporarily until it is part of an instance.
```

### Tool installation time in runtime

Unsure

### Are you willing to submit a PR?

Yes, I'd love to! But your pages says for Mac you don't accept them.

**Comment by miketimofeev** [comment]
Hi @CartBlanche!
I'm afraid VS 2022 for macOS is still in preview and not intended for use on production computers or for creating production code — https://docs.microsoft.com/en-us/visualstudio/releases/2022/mac-release-notes-preview
The stable version will be released in the first half of 2022. I'm going to close the issue, please reopen\contact us when the stable version is released.
Thank you!

**Comment by CartBlanche** [comment]
@miketimofeev Don't the Windows Instances have a "preview" tag, which then pulls in latest preview versions of Visual Studio VS022?

**Comment by miketimofeev** [comment]
@CartBlanche no, stable VS2022 for Windows was released on November, 8th. macOS one has a different cadence

**Comment by CartBlanche** [comment]
@aherrick I opened a new issue asking for putting it on macOS-12 instance and apparently it will be added on the 30th of May or similar. More details in the other issue. It's still open.
