### ISSUE TITLE
mysql-community-client and mysql-community-server missing requirements

### ISSUE THREAD

**Issue by spyder007** [actions/virtual-environments#4764]
### Description

The [mysql.sh](templates/buildagents/lib/virtual-environments/images/linux/scripts/installers/mysql.sh) provisioning script specifies packages to install.

```
mysql_debs=(
        mysql-common*
        mysql-community-client-plugins*
        mysql-community-client*
        mysql-client*
        mysql-community-server*
        mysql-server*
        libmysqlclient21*
        libmysqlclient-dev*
    )
```
When running this provisioning script, I'm getting errors about missing dependencies 
* `mysql-community-client-core`  as a dependency of `mysql-community-client`
* `mysql-community-server-core` as a dependency of `mysql-community-server`

I modified the script to install client-core and re-ran, only to run into the server-core dependency.  I'm testing adding server core as well, so my new package list is as follows:

```
mysql_debs=(
        mysql-common*
        mysql-community-client-plugins*
        mysql-community-client-core*
        mysql-community-client*
        mysql-client*
        mysql-community-server-core*
        mysql-community-server*
        mysql-server*
        libmysqlclient21*
        libmysqlclient-dev*
    )
```
I don't see any changes in the repository history that would explain this, so I hesitate on making a PR with the change because I'm not sure why it started happening.

### Virtual environments affected

- [ ] Ubuntu 18.04
- [X] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

I use this library as a submodule in another project that I have for provisioning Hyper-V build agents on a local server, and my last successful agent build was 9/29/2021.  I will update this bug if my above local change succeeds.

### Expected behavior

mysql.sh should provision without error on Ubuntu 20.04

### Actual behavior

mysql.sh is unable to run based on missing dependencies.

### Repro steps

1. Provision Ubuntu 20.04 machine - In my case, I am provisioning a Hyper-V VM with Ubuntu 20.04.3 iso
2. Execute the mysql.sh as part of provisioning.

Here is the log for the mysql.sh provisioning - Note that this is log is AFTER I added `mysql-community-client-core` to the package list, but before i added `mysql-community-server-core`.

==> hyperv-iso.autogenerated_1: Provisioning with shell script: templates/buildagents/lib/virtual-environments/images/linux/scripts/installers/mysql.sh
    hyperv-iso.autogenerated_1: /tmp /home/matt
    hyperv-iso.autogenerated_1: Reading package lists...
    hyperv-iso.autogenerated_1: Building dependency tree...
    hyperv-iso.autogenerated_1: Reading state information...
    hyperv-iso.autogenerated_1: libaio1 is already the newest version (0.3.112-5).
    hyperv-iso.autogenerated_1: libaio1 set to manually installed.
    hyperv-iso.autogenerated_1: The following packages were automatically installed and are no longer required:
    hyperv-iso.autogenerated_1:   liblldb-10 liblldb-12
    hyperv-iso.autogenerated_1: Use 'sudo apt autoremove' to remove them.
    hyperv-iso.autogenerated_1: The following NEW packages will be installed:
    hyperv-iso.autogenerated_1:   libmecab2
    hyperv-iso.autogenerated_1: 0 upgraded, 1 newly installed, 0 to remove and 13 not upgraded.
    hyperv-iso.autogenerated_1: Need to get 233 kB of archives.
    hyperv-iso.autogenerated_1: After this operation, 1,865 kB of additional disk space will be used.
    hyperv-iso.autogenerated_1: Get:1 http://us.archive.ubuntu.com/ubuntu focal/main amd64 libmecab2 amd64 0.996-10build1 [233 kB]
    hyperv-iso.autogenerated_1: Fetched 233 kB in 0s (1,025 kB/s)
    hyperv-iso.autogenerated_1: Selecting previously unselected package libmecab2:amd64.
    hyperv-iso.autogenerated_1: (Reading database ... 217216 files and directories currently installed.)
    hyperv-iso.autogenerated_1: Preparing to unpack .../libmecab2_0.996-10build1_amd64.deb ...
    hyperv-iso.autogenerated_1: Unpacking libmecab2:amd64 (0.996-10build1) ...
    hyperv-iso.autogenerated_1: Setting up libmecab2:amd64 (0.996-10build1) ...
    hyperv-iso.autogenerated_1: Processing triggers for libc-bin (2.31-0ubuntu9.2) ...
    hyperv-iso.autogenerated_1: /tmp/mysql /tmp /home/matt
    hyperv-iso.autogenerated_1: (Reading database ... 217222 files and directories currently installed.)
    hyperv-iso.autogenerated_1: Preparing to unpack mysql-common_8.0.26-1ubuntu20.04_amd64.deb ...
    hyperv-iso.autogenerated_1: Unpacking mysql-common (8.0.26-1ubuntu20.04) over (5.8+1.0.5ubuntu2) ...
    hyperv-iso.autogenerated_1: Setting up mysql-common (8.0.26-1ubuntu20.04) ...
    hyperv-iso.autogenerated_1: Installing new version of config file /etc/mysql/conf.d/mysql.cnf ...
    hyperv-iso.autogenerated_1: Installing new version of config file /etc/mysql/my.cnf.fallback ...
    hyperv-iso.autogenerated_1: Selecting previously unselected package mysql-community-client-plugins.
    hyperv-iso.autogenerated_1: (Reading database ... 217223 files and directories currently installed.)
    hyperv-iso.autogenerated_1: Preparing to unpack mysql-community-client-plugins_8.0.26-1ubuntu20.04_amd64.deb ...
    hyperv-iso.autogenerated_1: Unpacking mysql-community-client-plugins (8.0.26-1ubuntu20.04) ...
    hyperv-iso.autogenerated_1: Setting up mysql-community-client-plugins (8.0.26-1ubuntu20.04) ...
    hyperv-iso.autogenerated_1: Selecting previously unselected package mysql-community-client-core.
    hyperv-iso.autogenerated_1: (Reading database ... 217232 files and directories currently installed.)
    hyperv-iso.autogenerated_1: Preparing to unpack mysql-community-client-core_8.0.26-1ubuntu20.04_amd64.deb ...
    hyperv-iso.autogenerated_1: Unpacking mysql-community-client-core (8.0.26-1ubuntu20.04) ...
    hyperv-iso.autogenerated_1: Setting up mysql-community-client-core (8.0.26-1ubuntu20.04) ...
    hyperv-iso.autogenerated_1: Processing triggers for man-db (2.9.1-1) ...
    hyperv-iso.autogenerated_1: Selecting previously unselected package mysql-community-client.
    hyperv-iso.autogenerated_1: (Reading database ... 217244 files and directories currently installed.)
    hyperv-iso.autogenerated_1: Preparing to unpack mysql-community-client_8.0.26-1ubuntu20.04_amd64.deb ...
    hyperv-iso.autogenerated_1: Unpacking mysql-community-client (8.0.26-1ubuntu20.04) ...
    hyperv-iso.autogenerated_1: Setting up mysql-community-client (8.0.26-1ubuntu20.04) ...
    hyperv-iso.autogenerated_1: Processing triggers for man-db (2.9.1-1) ...
    hyperv-iso.autogenerated_1: (Reading database ... 217293 files and directories currently installed.)
    hyperv-iso.autogenerated_1: Preparing to unpack mysql-community-client-core_8.0.26-1ubuntu20.04_amd64.deb ...
    hyperv-iso.autogenerated_1: Unpacking mysql-community-client-core (8.0.26-1ubuntu20.04) over (8.0.26-1ubuntu20.04) ...
    hyperv-iso.autogenerated_1: Setting up mysql-community-client-core (8.0.26-1ubuntu20.04) ...
    hyperv-iso.autogenerated_1: Processing triggers for man-db (2.9.1-1) ...
    hyperv-iso.autogenerated_1: (Reading database ... 217293 files and directories currently installed.)
    hyperv-iso.autogenerated_1: Preparing to unpack mysql-community-client-plugins_8.0.26-1ubuntu20.04_amd64.deb ...
    hyperv-iso.autogenerated_1: Unpacking mysql-community-client-plugins (8.0.26-1ubuntu20.04) over (8.0.26-1ubuntu20.04) ...
    hyperv-iso.autogenerated_1: Setting up mysql-community-client-plugins (8.0.26-1ubuntu20.04) ...
    hyperv-iso.autogenerated_1: Selecting previously unselected package mysql-client.
    hyperv-iso.autogenerated_1: (Reading database ... 217293 files and directories currently installed.)
    hyperv-iso.autogenerated_1: Preparing to unpack mysql-client_8.0.26-1ubuntu20.04_amd64.deb ...
    hyperv-iso.autogenerated_1: Unpacking mysql-client (8.0.26-1ubuntu20.04) ...
    hyperv-iso.autogenerated_1: Setting up mysql-client (8.0.26-1ubuntu20.04) ...
    hyperv-iso.autogenerated_1: Selecting previously unselected package mysql-community-server.
    hyperv-iso.autogenerated_1: (Reading database ... 217299 files and directories currently installed.)
    hyperv-iso.autogenerated_1: Preparing to unpack mysql-community-server_8.0.26-1ubuntu20.04_amd64.deb ...
    hyperv-iso.autogenerated_1: Unpacking mysql-community-server (8.0.26-1ubuntu20.04) ...
==> hyperv-iso.autogenerated_1: dpkg: dependency problems prevent configuration of mysql-community-server:
==> hyperv-iso.autogenerated_1:  mysql-community-server depends on mysql-community-server-core (= 8.0.26-1ubuntu20.04); however:
==> hyperv-iso.autogenerated_1:   Package mysql-community-server-core is not installed.
==> hyperv-iso.autogenerated_1:
==> hyperv-iso.autogenerated_1: dpkg: error processing package mysql-community-server (--install):
==> hyperv-iso.autogenerated_1:  dependency problems - leaving unconfigured
==> hyperv-iso.autogenerated_1: Errors were encountered while processing:
==> hyperv-iso.autogenerated_1:  mysql-community-server
==> hyperv-iso.autogenerated_1: Provisioning step had errors: Running the cleanup provisioner, if present...

**Comment by mikhailkoliada** [comment]
Hello @spyder007!

Thanks, we will take a look.

**Comment by spyder007** [comment]
@mikhailkoliada For what it's worth, my updated package list in mysql.sh seems to have worked:

```
mysql_debs=(
        mysql-common*
        mysql-community-client-plugins*
        mysql-community-client-core*
        mysql-community-client*
        mysql-client*
        mysql-community-server-core*
        mysql-community-server*
        mysql-server*
        libmysqlclient21*
        libmysqlclient-dev*
    )
```

**Comment by mikhailkoliada** [comment]
@spyder007 Hi!

Well, the main problem is that apt guessing a deptree if mysql was previously installed, no matter how it was done.
Could you please confirm that the current state of the main branch works for you?

**Comment by spyder007** [comment]
@mikhailkoliada the new mysql provisioning step in `main` works fine.  Thanks for the quick response.

**Comment by rumeshmadhusanka** [comment]
mysql-client is still broken. I'm using https://github.com/linux-training-group-1/asset-registry/blob/bb5731dc2e4659eba587209b5b04b1222ced9bd2/.github/workflows/ci.yml#L50
