### ISSUE TITLE
Add Xcode 13.2.1

### ISSUE THREAD

**Issue by bielikb** [actions/virtual-environments#4769]
### Tool name

Xcode

### Tool license

Apple, Inc.

### Add or update?

- [X] Add
- [ ] Update

### Desired version

Xcode 13.2.1 (build 13C100)

### Brief description of tool

Xcode IDE

### URL for tool's homepage

https://developer.apple.com/services-account/download?path=/Developer_Tools/Xcode_13.2.1/Xcode_13.2.1.xip

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [X] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Can this tool be installed during the build?

```bash
no
```

### Are you willing to submit a PR?

no. I have no prior knowledge how to install new Xcode image on macOS 11 on GHA

**Comment by miketimofeev** [comment]
Hi @bielikb!
The new image with Xcode 13.2.1 will be deployed in the next few days

**Comment by 3a4oT** [comment]
Thanks for the quick request/response 👍

**Comment by miketimofeev** [comment]
@3a4oT @bielikb the image with the new Xcode version has been depoyed

**Comment by idelfonsog2** [comment]
Hi @miketimofeev I see it listed here for macOS agents but how can we make use of that particular version of Xcode ? https://github.com/actions/virtual-environments/blob/macOS-11/20211219.1/images/macos/macos-11-Readme.md

**Comment by miketimofeev** [comment]
@idelfonsog2 Hi!
This should help
`sudo xcode-select -s "/Applications/Xcode_13.2.1.app"`

**Comment by idelfonsog2** [comment]
This also applies to the Azure DevOps macOS agents ?

**Comment by miketimofeev** [comment]
@idelfonsog2 correct, the image is the same

**Comment by idelfonsog2** [comment]
How long till that becomes the default version?

**Comment by miketimofeev** [comment]
@idelfonsog2 probably we will switch the version some time in the second half of January
