### ISSUE TITLE
java-tools fails silently on apt-fast ANT install 

### ISSUE THREAD

**Issue by tonywildey-valstro** [actions/virtual-environments#4780]
### Description

The everyfs project [action runner](https://github.com/evryfs/github-actions-runner) using the virtual installers here to facilitate building a runner image, in the porcess of using this I discovered that if apt-fast is not installed then the java-tools.sh fails at the Ant install step with no error or log and the rest of the script fails to execute. 

It would make sense to me to not use apt-fast in these installers unless absolutely necessary. 
Additionally it would make sense to either break out the java tools script or have it be tolerant to failure of a step. 

### Virtual environments affected

- [ ] Ubuntu 18.04
- [X] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

N/A

### Is it regression?

No

### Repro steps

Run java-tools.sh without apt-fast installed

**Comment by mikhailkoliada** [comment]
@tonywildey-valstro Hello!

Thanks, we will take a look at it.

**Comment by mikhailkoliada** [comment]
The fix will be rolled out after January 9th.

**Comment by tonywildey-valstro** [comment]
Thanks for the quick turnaround - agree on the fact theres no need to use apt-fast :)

**Comment by mikhailkoliada** [comment]
The fix has been deployed this week.
