### ISSUE TITLE
Installing 32-bit libpcre2-8-0 fails

### ISSUE THREAD

**Issue by madewokherd** [actions/virtual-environments#4781]
### Description

Attempting to install the 32-bit version of libpcre2-8-0, or anything that depends on it, fails.

GLib depends indirectly on libpcre2, so this can indirectly affect a lot of things.

The cause seems to be a custom version of amd64 libpcre2 (10.39-2+ubuntu20.04.1+deb.sury.org+1) which is required to have the same version as the i386 package if installed, but no i386 package with that version exists.

As a work-around, it is possible to downgrade this package, but it's rather fragile.

### Virtual environments affected

- [ ] Ubuntu 18.04
- [X] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

20211214.2

### Repro steps

```
        sudo dpkg --add-architecture i386
        sudo apt update
        sudo apt install -y libpcre2-8-0:i386 libpcre2-8-0
```

**Comment by catthehacker** [comment]
Duplicate of #4589

**Comment by madewokherd** [comment]
Just putting this out there: if you kept current issues open I'd probably be able to find them instead of filing duplicates.

**Comment by madewokherd** [comment]
Still, thank you for your quick response in pointing me to that at least.
