### ISSUE TITLE
cpan not works on Ubuntu18.04 and Ubuntu-20.04

### ISSUE THREAD

**Issue by leleliu008** [actions/virtual-environments#4783]
### Description

```
cpan -i App::Cpan
```

Use of uninitialized value $_[0] in substitution (s///) at /usr/share/perl/5.30/File/Basename.pm line 341.
fileparse(): need a valid pathname at /usr/share/perl/5.30/CPAN/FirstTime.pm line 1413.

**pre-installed cpan 1.64 has bug, please update to the latest version.**

### Virtual environments affected

- [X] Ubuntu 18.04
- [X] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

https://github.com/leleliu008/test/actions/runs/1605647744

https://github.com/actions/virtual-environments/blob/ubuntu18/20211212.1/images/linux/Ubuntu1804-README.md#package-management
https://github.com/actions/virtual-environments/blob/ubuntu20/20211214.2/images/linux/Ubuntu2004-README.md#package-management

### Is it regression?

No

### Expected behavior

`cpan -i App::Cpan` can be run successfully.

### Actual behavior

`cpan -i App::Cpan` failed and reported follwoing error log:

```
Use of uninitialized value $_[0] in substitution (s///) at /usr/share/perl/5.30/File/Basename.pm line 341.
fileparse(): need a valid pathname at /usr/share/perl/5.30/CPAN/FirstTime.pm line 1413.
```

### Repro steps

run `cpan -i App::Cpan`

**Comment by mikhailkoliada** [comment]
@leleliu008 Hello!
Thanks, we will take a look! By the way, repository you are referencing either does not exist or private, could you please make it visible?

**Comment by leleliu008** [comment]
Sorry, I have updated the link. https://github.com/leleliu008/test/actions/runs/1605647744

**Comment by mikhailkoliada** [comment]
@leleliu008 Hello! 
The problem you experience is related to the `local::lib` module (the default method for non-root calls), it simply uses the wrong `PERL_*` specific variables on the first cpan call (cpan itself is irrelevant). You should either re-bootstrap `local::lib` as shown below or simply run cpan shell as a root user (with sudo).
Please let us know if it is viable for you.

```name: cpan test
on: [push, pull_request]
jobs:
  build-dist:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: setup locallib
        run: |
          tempdir=$(mktemp -d)
          cd $tempdir
          wget https://cpan.metacpan.org/authors/id/H/HA/HAARG/local-lib-2.000024.tar.gz
          tar zxvf local-lib-2.000024.tar.gz
          cd local-lib-2.000024
          PERL_LOCAL_LIB_ROOT=$GITHUB_WORKSPACE/perl5
          perl Makefile.PL --bootstrap=$PERL_LOCAL_LIB_ROOT
          make
          make test
          echo "PERL_LOCAL_LIB_ROOT=$PERL_LOCAL_LIB_ROOT" >> $GITHUB_ENV
          echo "PERL5LIB=$PERL_LOCAL_LIB_ROOT/lib/perl5" >> $GITHUB_ENV
          echo "PERL_MB_OPT=--install_base \"$PERL_LOCAL_LIB_ROOT/\"" >> $GITHUB_ENV
          echo "PERL_MM_OPT=INSTALL_BASE=$PERL_LOCAL_LIB_ROOT" >> $GITHUB_ENV
          echo "PATH=$PERL_LOCAL_LIB_ROOT/bin:$PATH" >> $GITHUB_ENV
      - name: install cpan module
        run: |
          cpan -i App::Cpan```

**Comment by leleliu008** [comment]
@mikhailkoliada yes, it works, thanks!

**Comment by mikhailkoliada** [comment]
@leleliu008 Hello!

Given that we are unable to do anything more here I am going to close the issue, but feel free to ping us if you have questions left.
