### ISSUE TITLE
Need add EnableHttpsTrafficOnly for New-AzStorageAccount

### ISSUE THREAD

**Issue by alex-3sr** [actions/virtual-environments#4788]
### Description

Hi,

On some azure tenants, there are many Azure Policy for compliance. I've many multiple change that I did in locally for permit module to run with compliance, but I think that permit new Azure Storage in https only need to be add in main.

We can add a variable paramter _EnableHttpsTrafficOnly_ in boolean then on line 196 this ->
`
New-AzStorageAccount -ResourceGroupName $ResourceGroupName -AccountName $storageAccountName -Location $AzureLocation -SkuName "Standard_LRS" -AllowBlobPublicAccess $AllowBlobPublicAccess -EnableHttpsTrafficOnly $EnableHttpsTrafficOnly 
`

Is it possible to have this one in next release please ?

Thanks
Alexandre

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Not relevant

### Repro steps

1. Add Azure Policy who enforce HTTPS traffic on Storage
2. run GenerateResourcesAndImage

**Comment by miketimofeev** [comment]
@alex-3sr thank you for the contribution! The pr is merged so I'm going to close the issue.
Please feel free to contact us if you have any concerns.
