### ISSUE TITLE
Update/Add azure cli to 2.1.0

### ISSUE THREAD

**Issue by gregorybleiker** [actions/virtual-environments#479]
**Tool information**
- Tool name: az cli
- Add or update? update
- Desired version: 2.1.0

**Area for Triage**:

**Virtual environments affected**
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [x ] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [x ] Windows Server 2019

**Can this tool be installed during the build?**
Don't know

**Are you willing to submit a PR?**
No

**Comment by miketimofeev** [comment]
Hi @gregorybleiker!
Az-Cli 2.1.0 is already rolling out. You can find it in pre-release readmes here:
https://github.com/actions/virtual-environments/releases

**Comment by miketimofeev** [comment]
Feel free to reopen the issue if you have any concerns.
Thanks!

**Comment by gregorybleiker** [comment]
Can I use this in my pipelines somehow? What is the ETA for the rollout?
