### ISSUE TITLE
python3-vtk7 broken for version 20211209.3 of Ubuntu 20.04

### ISSUE THREAD

**Issue by MarDiehl** [actions/virtual-environments#4790]
### Description

Since the update to v20211209.3, installing python3-vtk7 via apt results in a non-working setup.

Importing vtk gives results in a `ModuleNotFoundError`:
```Python
2021-12-21T19:56:09.4752704Z python/damask/_vtk.py:7: in <module>
2021-12-21T19:56:09.4753315Z     import vtk
2021-12-21T19:56:09.4754697Z /usr/lib/python3/dist-packages/vtk/__init__.py:114: in <module>
2021-12-21T19:56:09.4755482Z     from .vtkIOGDAL import *
2021-12-21T19:56:09.4756637Z /usr/lib/python3/dist-packages/vtk/vtkIOGDAL.py:9: in <module>
2021-12-21T19:56:09.4757541Z     from vtkIOGDALPython import *
2021-12-21T19:56:09.4758676Z E   ModuleNotFoundError: No module named 'vtkIOGDALPython'
```

The same configuration works for Version: 20211129.1

### Virtual environments affected

- [ ] Ubuntu 18.04
- [X] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Broken (Version: 20211214.2)
https://pipelines.actions.githubusercontent.com/rfRIUWtEez1VC9tQFMukWvYEA8EEWkf0BlI6xzQ3JzzEHQyTjK/_apis/pipelines/1/runs/114/signedlogcontent/2?urlExpires=2021-12-21T20%3A59%3A23.9284584Z&urlSigningMethod=HMACV1&urlSignature=nsXcAKwCXfyAs0oRFeRvGyUYKeO2XPmEmsv4YWbMT9Y%3D

Working (Version: 20211129.1)
https://pipelines.actions.githubusercontent.com/MSp0EcqmQXBff2CkP41NMkNZp3FCfE95dnQsSJH7m9veWOnJVR/_apis/pipelines/1/runs/136/signedlogcontent/2?urlExpires=2021-12-21T21%3A03%3A41.9095087Z&urlSigningMethod=HMACV1&urlSignature=T2u82ScSo2npkm%2BQzA3Yp4vIH1AGj%2Fanmn833tSPrLo%3D

### Is it regression?

yes

### Expected behavior

installation via apt should give a working python environment.

### Actual behavior

some libraries are missing, cannot import the vtk module in python.

### Repro steps

Something like the following should be a MWE (not tested):

1. `sudo apt-get update && sudo apt-get install python3-pip python3-pytest python3-pandas python3-scipy python3-h5py python3-vtk7`
1. `python -c 'import vtk'`

**Comment by mikhailkoliada** [comment]
@MarDiehl hello!

It looks like links you have provided are broken, it returns a json object rather than a web page.

**Comment by MarDiehl** [comment]
my bad, I did not realize that the links to raw logs expire.

Broken
- https://github.com/eisenforschung/DAMASK/runs/4594578838

Working
- https://github.com/eisenforschung/DAMASK/runs/4494893960

**Comment by miketimofeev** [comment]
@MarDiehl 
Running the following workflow produces no errors so I wonder if something changed in your code or in some dependencies?

```yml
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test python vtk
        run: |
          sudo apt-get update && sudo apt-get install python3-pip python3-pytest python3-pandas python3-scipy python3-h5py python3-vtk7
          python -c 'import vtk'
```

https://github.com/miketimofeev/actionstest/runs/4604114480?check_suite_focus=true

**Comment by MarDiehl** [comment]
thanks!
My specification it the following:
```
- name: Install dependencies
  run: >
    sudo apt-get update &&
    sudo apt-get install python3-pip python3-pytest python3-pandas python3-scipy
    python3-h5py python3-vtk7 python3-matplotlib python3-yaml -y

- name: Run unit tests
  run: |
    export PYTHONPATH=${PWD}/python
    COLUMNS=256 python -m pytest python
```

Maybe setting PYTHONPATH causes the problem. I've never seen that is was set for package installed via apt but maybe vtk now makes use of it. I'll keep you posted.

**Comment by MarDiehl** [comment]
it seems to be an issue with pytest:

https://stackoverflow.com/questions/67274135

**Comment by MarDiehl** [comment]
instead of running pytest, I now simply import my library, which in turn imports vtk. Now I get a slightly clearer message

```
python3 -c 'import damask'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/vtk/vtkIOGDAL.py", line 5, in <module>
    from .vtkIOGDALPython import *
ImportError: /lib/x86_64-linux-gnu/libstdc++.so.6: cannot allocate memory in static TLS block

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/runner/work/DAMASK/DAMASK/python/damask/__init__.py", line 23, in <module>
    from ._vtk             import VTK              # noqa
  File "/home/runner/work/DAMASK/DAMASK/python/damask/_vtk.py", line 7, in <module>
    import vtk
  File "/usr/lib/python3/dist-packages/vtk/__init__.py", line 114, in <module>
    from .vtkIOGDAL import *
  File "/usr/lib/python3/dist-packages/vtk/vtkIOGDAL.py", line 9, in <module>
    from vtkIOGDALPython import *
ModuleNotFoundError: No module named 'vtkIOGDALPython'
```

the main issue is `ImportError: /lib/x86_64-linux-gnu/libstdc++.so.6: cannot allocate memory in static TLS block`. Not sure what that means,

**Comment by miketimofeev** [comment]
@MarDiehl take a look at this issue, please, there is a workaround available
https://github.com/actions/virtual-environments/issues/4733
@dsame it looks like we have another example of the libstdc  issue

**Comment by miketimofeev** [comment]
For reference — this is most likely caused by this PR with MySQL downgrade
https://github.com/actions/virtual-environments/pull/4674
There is a bug related to this
https://bugs.launchpad.net/ubuntu/+source/opencv/+bug/1890170

**Comment by MarDiehl** [comment]
@miketimofeev: Many thanks, this partly solves the issue:
```
LD_PRELOAD=/lib/x86_64-linux-gnu/libstdc++.so.6:${LD_PRELOAD} python3 -c 'import damask'
```
works, but when calling pytest I still get the initial error.

**Comment by miketimofeev** [comment]
@MarDiehl would you mind preparing a full repro so we can investigate what can be done next?

**Comment by MarDiehl** [comment]
There is a test repository on https://github.com/MarDiehl/python-vtk_github-actions_reproducer

the error message differs slightly between loading vtk in `conftest.py` (pytest configuration), see

```
ImportError while loading conftest '/home/runner/work/python-vtk_github-actions_reproducer/python-vtk_github-actions_reproducer/python/tests/conftest.py'.
python/tests/conftest.py:10: in <module>                                                            
    import damask                                                                                   
python/damask/__init__.py:10: in <module>                                                           
    from ._vtk             import VTKd              # noqa                                          
python/damask/_vtk.py:2: in <module>                                                                
    import vtk                                                                                      
/usr/lib/python3/dist-packages/vtk/__init__.py:114: in <module>                                     
    from .vtkIOGDAL import *                                                                        
/usr/lib/python3/dist-packages/vtk/vtkIOGDAL.py:9: in <module>                                      
    from vtkIOGDALPython import *                                                                   
E   ModuleNotFoundError: No module named 'vtkIOGDALPython'
```

and loading only in the module that is tested, see https://github.com/MarDiehl/python-vtk_github-actions_reproducer/runs/4606284602

```
/usr/lib/python3/dist-packages/vtk/vtkIOGDAL.py:5: in <module>                                      
    from .vtkIOGDALPython import *                                                                  
E   ImportError: /lib/x86_64-linux-gnu/libstdc++.so.6: cannot allocate memory in static TLS block   
                                                                                                    
During handling of the above exception, another exception occurred:                                 
python/tests/test_VTK.py:8: in <module>                                                             
    import vtk                                                                                      
/usr/lib/python3/dist-packages/vtk/__init__.py:114: in <module>                                     
    from .vtkIOGDAL import *                                                                        
/usr/lib/python3/dist-packages/vtk/vtkIOGDAL.py:9: in <module>                                      
    from vtkIOGDALPython import *                                                                   
E   ModuleNotFoundError: No module named 'vtkIOGDALPython'
```

**Comment by MarDiehl** [comment]
using `LD_PRELOAD=libstdc++.so.6:libgomp.so.1:${LD_PRELOAD}` solves the issue, but only in the small reproducer. For the actual code it does not help, see https://github.com/MarDiehl/DAMASK/runs/4606857823. The error message is different in that case: `ids must be list of strings, found: 0 (type: <class 'int'>)`. This message seems to originate from pytest (https://github.com/pytest-dev/pytest/blob/main/src/_pytest/python.py)

**Comment by MarDiehl** [comment]
I'm no out of ideas for further investigations. Import order seems to play a role (https://stackoverflow.com/questions/67735216), but I suspect that it is also related to missing resources...

**Comment by miketimofeev** [comment]
@MarDiehl we suppose it's related to mysql packages so thanks for the repro it will help us find a workaround. We'll get back once we have some ideas

**Comment by mikhailkoliada** [comment]
@MarDiehl I have forked the original repo of yours (no the repro one, the DAMASK one), and have performed mysql upgrade straight in your pipeline's apt job by putting the `apt-get remove mysql* && apt-get install -y mysql-server` there, I think it might serve as a workaround for the time being, at least unless canonical/oracle do not have a properly fixed version of mysql rolled out/released.

**Comment by miketimofeev** [comment]
@MarDiehl we have provided a workaround in this announcement. Sorry for the inconvenience
https://github.com/actions/virtual-environments/issues/4799

**Comment by MarDiehl** [comment]
@miketimofeev and @mikhailkoliada: Many thanks for the very quick and very good support. Impressive!
