### ISSUE TITLE
Fail to create the Windows2019 image

### ISSUE THREAD

**Issue by jiaweis2021** [actions/virtual-environments#4792]
### Description

Fail to cerate the Windows2019 image on a new created VM(clean).
Unsuccessful exit code returned by the installation process: 2003.
Steps follow on this:https://github.com/actions/virtual-environments/blob/main/docs/create-image-and-azure-resources.md

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [X] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Windows Server 2019

### Repro steps

Local machine or Azure VM can be used as a build agent.
Download packer from https://www.packer.io/downloads, or install it via Chocolately.
choco install packer
Install the Azure Az PowerShell module - https://docs.microsoft.com/en-us/powershell/azure/install-az-ps.
Install-Module -Name Az -Repository PSGallery -Force
Install Azure CLI - https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-windows?view=azure-cli-latest&tabs=azure-cli.
Invoke-WebRequest -Uri https://aka.ms/installazurecliwindows -OutFile .\AzureCLI.msi; Start-Process msiexec.exe -Wait -ArgumentList '/I AzureCLI.msi /quiet'; rm .\AzureCLI.msi
Download Virtual-Environments repository.
Set-Location c:\
git clone https://github.com/actions/virtual-environments.git
Import GenerateResourcesAndImage script from /helpers folder, and run GenerateResourcesAndImage function via Powershell.
Set-Location C:\virtual-environments
 
Import-Module .\helpers\GenerateResourcesAndImage.ps1
 
GenerateResourcesAndImage -SubscriptionId {YourSubscriptionId} -ResourceGroupName "myTestResourceGroup" -ImageGenerationRepositoryRoot "$pwd" -ImageType Ubuntu1604 -AzureLocation "East US"
Where:
•	SubscriptionId - The Azure subscription Id where resources will be created.
•	ResourceGroupName - The Azure resource group name where the Azure resources will be created.
•	ImageGenerationRepositoryRoot - The root path of the image generation repository source.
•	ImageType - The type of the image being generated. Valid options are: "Windows2016", "Windows2019", "Ubuntu1604", "Ubuntu1804", "Ubuntu2004".
•	AzureLocation - The location of the resources being created in Azure. For example "East US".
The function automatically creates all required Azure resources and kicks off packer image generation for the selected image type.
Please, check synopsis of GenerateResourcesAndImage for details about non-mandatory parameters.

**Comment by mikhailkoliada** [comment]
Hello @jiaweis2021!

Could you please the entire build log of yours?

**Comment by jiaweis2021** [comment]
@mikhailkoliada Hello, this image is created by CMD, this is the entire log. Not build in DevOps pipeline.

**Comment by miketimofeev** [comment]
@jiaweis2021 please provide packer log. You can enable it as described here if it is not
https://www.packer.io/docs/debugging#debugging-packer

**Comment by ItzLevvie** [comment]
> @mikhailkoliada Hello, this image is created by CMD, this is the entire log. Not build in DevOps pipeline.

It looks like you forgot to modify your `GenerateResourcesAndImage`.

You're trying to build Ubuntu 16.04 instead of Windows Server 2019.

**Comment by al-cheb** [comment]
@jiaweis2021, I am planning to close this thread. If you have any concerns feel free to open one.
