### ISSUE TITLE
default-mysql-client cannot be installed anymore

### ISSUE THREAD

**Issue by gallusenrico** [actions/virtual-environments#4797]
### Description

We are using the virtual environment `ubuntu-20.04` to build our application and need the `mysqldump` to be available during our test execution.
For this reason we execute a run step that looked the following
```
run: |
          sudo apt-get update
          sudo apt-get install -y default-mysql-client
```

This worked just fine until the 13th of December this year using the following environment-virtual-version: `20211129.1`

Since the 15th of December of this year using the following environment-virtual-version: `20211209.3`, the run-command fails with the following message:
```
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 default-mysql-client : Depends: mysql-client-8.0 but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

We have not changed the build-script that's why I assume something changed in the virtual environment.

We tried to install the `mysql-client-8.0` package instead of the `default-mysql-client` package, which ended in the following error:
```
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 mysql-client-8.0 : Depends: mysql-common (>= 5.5)
E: Unable to correct problems, you have held broken packages.
```

What is the expected way to install the mysql-client on the ubuntu-20.04 virtual environment? 

### Virtual environments affected

- [ ] Ubuntu 18.04
- [X] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

it started to fail for us with the following image version: 20211209.3
it still fails using the following image version: 20211214.2

### Expected behavior

The `default-mysql-client` package gets correctly installed by apt-get without any errors and the binary `mysqldump` is available.

### Actual behavior

An error is shown and the build-script fails with the following error:
```
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 mysql-client-8.0 : Depends: mysql-common (>= 5.5)
E: Unable to correct problems, you have held broken packages.
```

### Repro steps

Execute a workflow-build that runs on `ubuntu-20.04`
And add a step that looks like this
```
- name: Install mysql client for mysqldump
        run: |
          sudo apt-get update
          sudo apt-get install -y default-mysql-client
```

**Comment by wojsmol** [comment]
Hi
Try temporally remove this step from your workflow as mysql-clir4nt should be installed be default see https://github.com/actions/virtual-environments/blob/main/images/linux/scripts/installers/mysql.sh#L33-L44. Reason for this change is described in https://github.com/actions/virtual-environments/pull/4674 - this is a temporary change.

**Comment by gallusenrico** [comment]
seems to work properly even without installing the package additionally. Thank you very much for the information
