### ISSUE TITLE
[Ubuntu] Issue with libstdc++ cannot allocate memory in static TLS block

### ISSUE THREAD

**Issue by miketimofeev** [actions/virtual-environments#4799]
### Breaking changes

Due to a bug in MySql 8.0.27 (https://bugs.mysql.com/bug.php?id=105288) we had to revert the version to 8.0.26 yet it's not possible to use ubuntu upstream repo as it doesn't contain older versions. In this PR we switched the installation to install all the dependencies step by step utilizing the `dpkg -i `command https://github.com/actions/virtual-environments/pull/4674

This leads to unpredictable behavior in libstdc++ usage when calling from Python (there could be other cases we are not aware of) — https://github.com/actions/virtual-environments/issues/4733, https://github.com/actions/virtual-environments/issues/4790
Please use the provided workaround until we either got 8.0.26 in the upstream repo or the new version 8.0.28 is released.

### Possible impact

If your Python code uses some C++ libraries it can be broken.

### Virtual environments affected

- [X] Ubuntu 18.04
- [X] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Mitigation ways

Reinstall MySQL version 8.0.27 using upstream repo:
```bash
sudo apt-get update
sudo apt-get remove mysql* && sudo apt-get install -y mysql-server
```

**Comment by mikhailkoliada** [comment]
Announce with the workaround has been published. Sorry for inconvenience caused.

**Comment by freddy123098** [comment]
Hi I saw this as open so may I help you? And what is the issue?

**Comment by freddy123098** [comment]
Please provide repo-steps thank you.

**Comment by freddy123098** [comment]
@miketimofeev pls provide repo steps thank you.

**Comment by freddy123098** [comment]
Hi I saw this issue open.

**Comment by Misshunter1** [comment]
to much violence do not want resilence

**Comment by RW21** [comment]
To add to the mitigation method provided, if you are using `mysql-client`, you will need to install `libmysqlclient-dev`, otherwise you will get `OSError: mysql_config not found`. 
So:
```
    - name: GA fixes
      run: |
        sudo apt-get update
        sudo apt-get remove mysql* && sudo apt-get install -y mysql-server libmysqlclient-dev

```

**Comment by anthillofoppies44** [comment]
jyz Ndoid havr linux 
idk

**Comment by marcelgerber** [comment]
I think this issue can be fixed by now, right?
[The underlying bug](https://bugs.mysql.com/bug.php?id=105288) is fixed in 8.0.28, and [8.0.28 is available from `apt` in 20.04 LTS](https://packages.ubuntu.com/focal/mysql-client). So simply reverting #4674 should do the trick.

**Comment by miketimofeev** [comment]
thanks @marcelgerber for the update!
We will test the behavior to make sure it's is really fixed and then rollback the workaround 🙂

**Comment by W786786** [comment]
Duplicate of #

**Comment by feliciakelley** [comment]
`[FaLeasecAnnA ](https://faleasecanna.atlassian.net/wiki/spaces/STATUSBLOC/overview) `

**Comment by laounimomo12** [comment]
dggf

**Comment by miketimofeev** [comment]
@marcelgerber we have reverted mysql client installation to the upstream repo, this shouldn't be the issue anymore.
