### ISSUE TITLE
[macOS] Default Xcode on Big Sur image will be set to Xcode 13.2.1 on January, 24

### ISSUE THREAD

**Issue by miketimofeev** [actions/virtual-environments#4800]
### Breaking changes

Default Xcode will be changed to 13.2.1 on macOS 11 Big Sur.

### Target date

Update propagation will start on January, 24 and will take 2-3 days.

### The motivation for the changes

We would like to provide images with the latest stable updates as default ones.

### Possible impact

If you use the default Xcode version and your project is not compatible with Xcode 13.1 your build can be broken.

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [X] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Mitigation ways

Please consider switching Xcode in runtime to the version that you need to build an app.
The following snippet can be used to switch Xcode:

`sudo xcode-select -s "/Applications/Xcode_13.1.app"`

The list of all available Xcode versions can be found in the [image documentation
](https://github.com/actions/virtual-environments/blob/main/images/macos/macos-11-Readme.md#xcode)

**Comment by bhargavas12** [comment]
is this rolled out ?

**Comment by miketimofeev** [comment]
@bhargavas12 the rollout is starting tomorrow

**Comment by Keki91** [comment]
Has this been fully rolled out, I'm getting inconsistent runs where some get 13.1 and some get 13.2.1 which is causing build failures due to different SDK's being available for iOS 15.0 and 15.2.

**Comment by miketimofeev** [comment]
@Keki91 the deployment is completed. Please contact us if you still observe the issue.
