### ISSUE TITLE
Perl

### ISSUE THREAD

**Issue by yuki-kimoto** [actions/virtual-environments#4804]
### Tool name

Perl

### Tool license

Artistic License and GPL

### Add or update?

- [X] Add
- [ ] Update

### Desired version

5.34

### Brief description of tool

Perl is an programing language such as Python or Ruby

### URL for tool's homepage

https://perldoc.perl.org/

### Virtual environments affected

- [X] Ubuntu 18.04
- [X] Ubuntu 20.04
- [X] macOS 10.15
- [X] macOS 11
- [X] Windows Server 2016
- [X] Windows Server 2019
- [X] Windows Server 2022

### Tool installation time in runtime

In 30 second using apt or yum

### Are you willing to submit a PR?

Yes

**Comment by mikhailkoliada** [comment]
@yuki-kimoto Hello!
 on macOS we are installing latest perl from brew
on Windows we are installing strawberry perl (which is 5.32 for now, it will be updated as soon as version in strawberry is updated)
on Ubuntu we are installing the latest Canonical-provided perl (as we are using LTS) so you will need to download an upstream binary and add it to `$PATH`.

Taking into account that there is no anything for us to act on I am going to close the issue, but feel free to ping us / open a new issue if you have questions left.

**Comment by yuki-kimoto** [comment]
@mikhailkoliada mikhailkoliada

Thank you.

This is document problem.

I could not know Perl is installed from the document.

https://github.com/actions/virtual-environments/blob/main/images/win/Windows2022-Readme.md

Would you add Perl above page?

If you hope, I can it.

And Ubuntu link(20 and 18) is broken.

https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#preinstalled-software

**Comment by yuki-kimoto** [comment]
If it is OK, I can create this issue.

**Comment by miketimofeev** [comment]
@yuki-kimoto sorry for the links, they will be fixed next year. The links on https://github.com/actions/virtual-environments should work.
Windows 2022 is indeed missing Perl. We will add it in mid-January.

**Comment by yuki-kimoto** [comment]
Thank you! I wait for a while.
