### ISSUE TITLE
Some actions VM running actions/checkout very slow

### ISSUE THREAD

**Issue by shoucandanghehe** [actions/virtual-environments#4807]
### Description

![image](https://user-images.githubusercontent.com/51957264/147414032-6abf87e1-2f20-469d-ab8d-613920e787fd.png)

### Virtual environments affected

- [ ] Ubuntu 18.04
- [X] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [X] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

20211219.1
https://github.com/shoucandanghehe/Quatrack/runs/4636893968

### Repro steps

1.run some actions casually
2.some VM will be slow

**Comment by shoucandanghehe** [comment]
My actions only use Ubuntu 20.04 and Windows server 2019
So I’m not sure that other virtual opportunities will not have these problems

**Comment by hungphongbk** [comment]
The same, have no idea why.
Is it comes from GitHub team?

**Comment by dibir-magomedsaygitov** [comment]
Hello @shoucandanghehe. Thank you for your report. We will take a look.

**Comment by lazka** [comment]
Our API calls/actions have started to time out ~16-12 hours ago: https://github.com/msys2/msys2-autobuild/actions

**Comment by deivid-rodriguez** [comment]
Not sure how this could be useful or mean anything, but from what I observed yesterday, for us it was always the same workflows running into issues while others worked fine although they all do the same kind of network operations. Really strange.

**Comment by Tirke** [comment]
We are seeing random timeouts on every steps of our CI this morning (Ubuntu 20 Github Hosted runners)

**Comment by deivid-rodriguez** [comment]
Nevermind, the above seems just pure chance, I'm now seeing failures in all workflows.

**Comment by asenyaev** [comment]
@deivid-rodriguez these issues started from yesterday :disappointed:

**Comment by deivid-rodriguez** [comment]
Yes, I'm aware, luckily GitHub people seem to be already on it :)

**Comment by miketimofeev** [comment]
Status page updated
https://status.githubapp.com/incidents/664

**Comment by miketimofeev** [comment]
The incident is now resolved
https://www.githubstatus.com/incidents/gh0vvxtlj5v7
