### ISSUE TITLE
Add Nerdbank.GitVersioning

### ISSUE THREAD

**Issue by josesimoes** [actions/virtual-environments#4818]
### Tool name

Nerdbank.GitVersioning

### Tool license

MIT

### Add or update?

- [X] Add
- [ ] Update

### Desired version

latest

### Brief description of tool

This package adds precise, semver-compatible git commit information to every assembly, VSIX, NuGet and NPM package, and more. It implicitly supports all cloud build services and CI server software because it simply uses git itself and integrates naturally in MSBuild, gulp and other build scripts.

The usage of this tool has been increasing and it has become pretty much *the* tool for git versioning, large projects (like msbuild) use it. 

### URL for tool's homepage

https://github.com/dotnet/nerdbank.gitversioning

### Provide a basic test case to validate the tool's functionality.

```bash
nbgv --version
```

### Virtual environments affected

- [X] Ubuntu 18.04
- [X] Ubuntu 20.04
- [X] macOS 10.15
- [X] macOS 11
- [X] Windows Server 2016
- [X] Windows Server 2019
- [X] Windows Server 2022

### Can this tool be installed during the build?

```bash
dotnet tool install -g nbgv
```

### Tool installation time in runtime

30s to 2min

### Are you willing to submit a PR?

yes

**Comment by mikhailkoliada** [comment]
Hi @josesimoes!

We will consider possibility of adding this tool to our images and get back to you :)

**Comment by miketimofeev** [comment]
Hi @josesimoes!
We recommend using the official action as it's more flexible — you can either stick to the latest version or choose any other version you like. The installation time is 10-20 seconds depends on OS.
```
    name: Install nbgv
    steps:
      - uses: actions/checkout@v2
      - uses: dotnet/nbgv@master
        with:
          setAllVars: true
      - name: Check install!
        run: nbgv --version
```
Given that fact and maintenance concerns, we wouldn't like to add the tool to the image. Please let us know if you have any concerns or objections and feel free to reopen the issue.
Thank you!

**Comment by josesimoes** [comment]
> Hi @josesimoes! We recommend using the official action as it's more flexible — you can either stick to the latest version or choose any other version you like. The installation time is 10-20 seconds depends on OS.

hey @miketimofeev ! 

That's for github actions. I was referring to use on Azure Pipelines.
I've been using the `DotNetCoreCLI@2` task to perform the install. It takes from a few seconds up to one minute. Average it's around 20-30s.
It's not much, granted, but it's something and (to my knowledge) there is no way to cache dotnet tools.
As for maintenance, the update would be as simple as `dotnet tool update -g nbgv`...
If needed to override in order to get a specific version, one could always revert to the `DotNetCoreCLI@2` task to install it.

But that's fine, just thought that because this tool has become so widespread (even in Microsoft tools) it was worth to have it preinstalled. 😉

**Comment by miketimofeev** [comment]
@josesimoes thanks for the update!
I agree it's worth having it in ADO then. Feel free to submit PRs for each OS except macOS (we will take care of it separately)

**Comment by josesimoes** [comment]
> Feel free to submit PRs for each OS except macOS (we will take care of it separately)

Awesome @miketimofeev! Will do. Some guidance please as I didn't find any dotnet CLI tool installed.
How would you prefer this being handled? A separate PS1? Adding this to an existing one? If yes, which one? Would need any testing? What would that be? Pulling the tool version?

Thanks!

**Comment by miketimofeev** [comment]
@josesimoes I believe a new section can be created in the toolset under the dotnet
https://github.com/actions/virtual-environments/blob/29dbc46881136406ea6830a1dff33c4c152aee27/images/win/toolsets/toolset-2022.json#L277-L283
Something like
```pwsh
    "dotnet": {
        "versions": [
            "3.1",
            "5.0"
        ],
        "tools": [
             "nbgv"
        ]
        "warmup": false
    },
```
and then install all the tools described in the toolset in the same script that installs dotnet. In addition, a simple pester test should be done (in [DotnetSDK tests](https://github.com/actions/virtual-environments/blob/main/images/win/scripts/Tests/DotnetSDK.Tests.ps1) if we are speaking about windows) and the tool should be added to the [software report generator](https://github.com/actions/virtual-environments/blob/main/images/win/scripts/SoftwareReport/SoftwareReport.Generator.ps1).

**Comment by josesimoes** [comment]
@miketimofeev please check #4820

**Comment by josesimoes** [comment]
I've just tested this in production in one of my pipelines, by removing the install step of ngbv.
It turns out that the tool is not available. You can check it here: https://dev.azure.com/nanoframework/nanoFramework.M5Stack/_build/results?buildId=27690&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=5caf77c8-9b10-50ef-b5c7-ca89c63e1c86

A path missing? Something misplaced?

**Comment by al-cheb** [comment]
The new images with fixed path have been deployed.

**Comment by josesimoes** [comment]
@al-cheb I've updated our pipelines here and everything it's running as expected.
Thank you again for your work on this.

**Comment by caesay** [comment]
Hi, It looks like nbgv is available on windows-latest & ubuntu-latest, but it is still not available on macos-latest. Is this planned?
