### ISSUE TITLE
Add Windows 10 SDK (10.0.17763.132)

### ISSUE THREAD

**Issue by riverar** [actions/virtual-environments#4825]
### Tool name

Windows 10 SDK

### Tool license

Microsoft

### Add or update?

- [X] Add
- [ ] Update

### Desired version

10.0.17763.132

### Approximate size

1GiB

### Brief description of tool

Windows 10 SDK (10.0.17763.xxx) supports apps that target Windows 10, version 1809 SKUs (e.g. LTSC). This target is in [mainstream support until 2024-01-09](https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fwindows%2Frelease-health%2Frelease-information%23%3A~%3Atext%3DEnterprise%2520only%291-%2C1809%2C2029-01-09%2C-1607).

Example of error when SDK is not present:
```
(_GetSdkToolsPathsFromSdk target) -> 
C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Microsoft\VisualStudio\v17.0\AppxPackage\
Microsoft.AppXPackage.Targets(1097,5): error APPX3217: SDK folder containing 'UAP.props' for 'UAP 10.0.17763.0'
cannot be located. See http://go.microsoft.com/fwlink/?LinkID=798187 for more information. 
```

See also #451

### URL for tool's homepage

https://developer.microsoft.com/en-us/windows/downloads/sdk-archive/

### Provide a basic test case to validate the tool's functionality.

```bash
- name: Test for Windows 10 17763 SDK
shell: pwsh
run: |
    Describe Test { It 'Verifies 17763 SDK is installed' { Test-Path "${env:ProgramFiles(x86)}\Windows Kits\10\DesignTime\CommonConfiguration\Neutral\UAP\10.0.17763.0\UAP.props" | Should Be $True } }
```

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [] Windows Server 2016
- [] Windows Server 2019
- [X] Windows Server 2022

### Can this tool be installed during the build?

```bash
- name: Workaround - Install Windows 10 17763 SDK
shell: powershell
run: |
    Invoke-WebRequest -Method Get -Uri https://go.microsoft.com/fwlink/p/?LinkID=2033908 -OutFile sdksetup.exe -UseBasicParsing
    Start-Process -Wait sdksetup.exe -ArgumentList "/q", "/norestart", "/ceip off", "/features OptionId.UWPManaged OptionId.UWPCPP OptionId.UWPLocalized OptionId.DesktopCPPx86 OptionId.DesktopCPPx64 OptionId.DesktopCPParm64"
```

### Tool installation time in runtime

3 minutes

**Comment by shilovmaksim** [comment]
Hi @riverar 
Windows images already has Windows 10 17763 SDK precached:
- [Windows2016-Readme.md](https://github.com/actions/virtual-environments/blob/3c2f1c6350b3d34a557f12f62e3ee47a839ea401/images/win/Windows2016-Readme.md?plain=1#L428)
- [Windows2019-Readme.md](https://github.com/actions/virtual-environments/blob/3c2f1c6350b3d34a557f12f62e3ee47a839ea401/images/win/Windows2019-Readme.md?plain=1#L418)

**Comment by riverar** [comment]
@shilovmaksim Yep, my mistake. I'll edit the original issue to only reflect windows2022 impact.

**Comment by miketimofeev** [comment]
Hi @riverar!
Could you please clarify why you need this version on windows-2022? Is it possible for you to use the windows-2019 image?

**Comment by riverar** [comment]
Sure. Our app targets all supported OS versions,  and now utilizes .NET 6 which requires Visual Studio 2022. This version of Visual Studio is not available on the `windows-2019` image.

**Comment by miketimofeev** [comment]
@riverar am I right that installing .NET 6 on windows-2019 with VS2019 is not a solution as VS2022 is required anyway?

**Comment by riverar** [comment]
@miketimofeev That's my understanding. See also https://dotnet.microsoft.com/en-us/download/dotnet/6.0

Wish I had a better escape hatch for you, truly. 

![image](https://user-images.githubusercontent.com/475132/148912335-f4515c84-c4f8-4bdd-afc6-ee8d6b7038b2.png)

**Comment by miketimofeev** [comment]
@riverar got your point, thanks for the explanation!
Is it enough to setup only `"/features OptionId.WindowsSoftwareDevelopmentKit"` or all these options should be set `"/features OptionId.UWPManaged OptionId.UWPCPP OptionId.UWPLocalized OptionId.DesktopCPPx86 OptionId.DesktopCPPx64 OptionId.DesktopCPParm64"`?

**Comment by miketimofeev** [comment]
> @riverar got your point, thanks for the explanation! Is it enough to setup only `"/features OptionId.WindowsSoftwareDevelopmentKit"` or all these options should be set `"/features OptionId.UWPManaged OptionId.UWPCPP OptionId.UWPLocalized OptionId.DesktopCPPx86 OptionId.DesktopCPPx64 OptionId.DesktopCPParm64"`?

@riverar gentle ping on this ^

**Comment by riverar** [comment]
@miketimofeev Sorry for the delay. Investigating now.

**Comment by riverar** [comment]
@miketimofeev `OptionId.WindowsSoftwareDevelopmentKit` doesn't exist.
![image](https://user-images.githubusercontent.com/475132/151458475-989d14e3-dff6-4092-8bd2-6c692df1e7a6.png)

I selected those options from this list:
![image](https://user-images.githubusercontent.com/475132/151458616-fae85fa0-a175-4e38-80af-461850c4508c.png)

The remaining options do not appear to be useful in an actions environment. But you can opt for `/features +` to install everything. It's not clear if the installer is smart enough to skip what isn't applicable to the host machine, however.

**Comment by al-cheb** [comment]
The new Windows Server 2022 image has been deployed with Windows 10.0.17763.0 SDK component on board - https://github.com/actions/virtual-environments/blob/main/images/win/Windows2022-Readme.md
