### ISSUE TITLE
Add Python 3.5.2

### ISSUE THREAD

**Issue by Delgan** [actions/virtual-environments#4826]
### Tool name

Python

### Tool license

PSF

### Add or update?

- [ ] Add
- [X] Update

### Desired version

3.5.2

### Brief description of tool

Python 3.5.2 is an old version but it's the default one on Ubuntu 16.04.

There are subtle differences in Python 3.5.2 compared to Python 3.5.3 (in particular for `asyncio`). For these differences to be handled properly, it is sometimes necessary to implement workarounds in the code. Adding support for Python 3.5.2 in Github Actions would help ensuring these workarounds are fully working.

### URL for tool's homepage

https://www.python.org/downloads/release/python-352/

### Virtual environments affected

- [X] Ubuntu 18.04
- [X] Ubuntu 20.04
- [X] macOS 10.15
- [X] macOS 11
- [X] Windows Server 2016
- [X] Windows Server 2019
- [X] Windows Server 2022

**Comment by shilovmaksim** [comment]
Hi @Delgan 
Python 3.5.* versions will be removed from images on January 24th. https://github.com/actions/virtual-environments/issues/4744
You can setup python specific version within your workflow with [setup-python](https://github.com/actions/setup-python) action.

**Comment by Delgan** [comment]
Hi @shilovmaksim, thanks for the answer.

Sorry, I'm new to Github Actions. When I tried to use `3.5.2` as `python-version` argument, it failed with the following error:

```python
2021-12-31T15:06:21.4229532Z ##[group]Run actions/setup-python@v2
2021-12-31T15:06:21.4230077Z with:
2021-12-31T15:06:21.4230595Z   python-version: 3.5.2
2021-12-31T15:06:21.4231594Z   token: ***
2021-12-31T15:06:21.4232087Z ##[endgroup]
2021-12-31T15:06:22.0542163Z Version 3.5.2 was not found in the local cache
2021-12-31T15:06:22.1084401Z ##[error]Version 3.5.2 with arch x64 not found
The list of all available versions can be found here: https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json
```

From what I understand:
* The `setup-python` can only configure environment for versions listed in`versions-manifest.json`
* The 3.5 versions will be remove from cache only, it won't be removed from `versions-manifest.json`
* To setup the desired workflow, the `3.5.2` version needs to be listed in `versions-manifest.json` which is not the case yet 

Am I missing something? I wasn't able to setup the python specific version (3.5.2).

**Comment by shilovmaksim** [comment]
> From what I understand:
> - The setup-python can only configure environment for versions listed inversions-manifest.json
> - The 3.5 versions will be remove from cache only, it won't be removed from versions-manifest.json
> - To setup the desired workflow, the 3.5.2 version needs to be listed in versions-manifest.json which is not the case yet

@Delgan , all your points are correct. 
Since Python 3.5.2 is not listed in `versions-manifest.json`, I think it is not supported there already also.

I'm afraid it is not possible for us to add this specific version to the images due to 3.5 version "end-of-life" and upcoming deprecation.

**Comment by Delgan** [comment]
Ah ok, I didn't realize it was not possible to add old versions due to the software support policy. Thanks for the clarifications.

For what it worth, I might try to submit a PR but I understand there are also maintenance costs that I don't know about.

I will try to adapt according to the final decision. :+1:

**Comment by miketimofeev** [comment]
@Delgan we will try to make this version available through the https://github.com/actions/setup-python action. We will keep you posted

**Comment by shilovmaksim** [comment]
Hi @Delgan .
Unfortunately we cannot add 3.5.2 version to the manifest. This version is quite old and already not supported by the build pipelines.
I'm going to close this feature request. Feel free to contact us if you still have any questions.

**Comment by freddy123098** [comment]
I think we can, right?

So what is the problem of this failure if i may ask?

**Comment by freddy123098** [comment]
What is the problem?

**Comment by freddy123098** [comment]
Welcome- @Madhavan ***@***.***>

**Comment by freddy123098** [comment]
I think the VM is the one which is looking bad from both ways.

**Comment by freddy123098** [comment]
Because this issue is not over yet according to me.
