### ISSUE TITLE
Link issue with C++ ATL libraries for ARM and ARM64 with windows-2019 environment when using toolset v141

### ISSUE THREAD

**Issue by jbrianceau** [actions/virtual-environments#4828]
### Description

When using the `windows-2019` environment, build of a C++ project relying on ATL libraries is successful for x86 and x64 platforms, but is failing for ARM and ARM64 platforms when using the `v141` `PlatformToolset`.

Note that this is not the case with the `windows-2016` environment version `20211219.1`

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [X] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

```
Environment: windows-2019
Version: 20211219.1
Included Software: https://github.com/actions/virtual-environments/blob/win19/20211219.1/images/win/Windows2019-Readme.md
Image Release: https://github.com/actions/virtual-environments/releases/tag/win19%2F20211219.1
```

### Is it regression?

Unknown

### Expected behavior

Build should be successful for ARM and ARM64, as ATL libraries for these 2 platforms are part of the environment according to https://github.com/actions/virtual-environments/blob/main/images/win/Windows2019-Readme.md

### Actual behavior

Link is failing for ARM and ARM64 platforms with the following message:
```
LINK : fatal error LNK1104: cannot open file 'atls.lib'
```

### Repro steps

1. Create a sample C++ project in Visual Studio 2019
2. Add the following include in any file of the project to pull the ATL dependency:
```
#include <atlbase.h>
```
3. Build the project for ARM or ARM64 platform on the `windows-2019` environment

**Comment by jbrianceau** [comment]
As far as I understand, the issue is that there are 2 different versions of the ATL library installed on the `windows-2019` environment:
* one in `/c/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/14.16.27023/` that only contains x86 and x64 builds of ATL
* one in `/c/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/14.29.30133/` that contains x86, x64, arm and arm64 builds of ATL

So I guess the oldest one from MSVC 14.16.27023 is picked by msbuild whatever the target platform is, leading to this issue.

**Comment by shilovmaksim** [comment]
Hi @jbrianceau 
We will take a look at this.

**Comment by shilovmaksim** [comment]
Hi @jbrianceau . Could you please provide a minimal workflow with reproduced issue?

**Comment by jbrianceau** [comment]
Hi @shilovmaksim, I've created a repro project with an azure pipeline yaml definition:
- Project: https://github.com/jbrianceau/SampleATLProject
- Azure pipeline definition; https://github.com/jbrianceau/SampleATLProject/blob/main/build/pipelines/build-all.yaml

While doing this, I found out that the issue occurs when using the v141 platform toolset, but doesn't occur with v142.

Here is the result of the pipeline run with project configured with v141 (commit [041f69ae0799abed0199effb97c964d8075a52d9](https://github.com/jbrianceau/SampleATLProject/commit/041f69ae0799abed0199effb97c964d8075a52d9)):
![image](https://user-images.githubusercontent.com/5746498/148800828-9121f415-c3ca-4d36-bca0-47864b733698.png)
![image](https://user-images.githubusercontent.com/5746498/148800896-677fb3d8-0ed1-4429-87cd-1a62a5aa1278.png)


Here is the result of the pipeline run with project configured with v142 (not run against vs2017 on purpose, commit [a1f7df1ac337d2070ddc8657ad0a09b905b9edc0](https://github.com/jbrianceau/SampleATLProject/commit/a1f7df1ac337d2070ddc8657ad0a09b905b9edc0)):
![image](https://user-images.githubusercontent.com/5746498/148801249-0c4c7188-ac7a-4de2-9bad-d85320ca1301.png)

I'll update the issue title and description to mention the toolset version to use.

**Comment by shilovmaksim** [comment]
Hi @jbrianceau 
Here's the VS2019 config from the VM regarding ATL:
![image](https://user-images.githubusercontent.com/89912354/148927725-ea0ff7b6-213e-4392-b4b6-8e8be1710d58.png)

I suspect that failures using toolset v141 might take place because these two components not installed. Could you please confirm my guess?

**Comment by jbrianceau** [comment]
Yes, I confirm that's very likely the root cause of the issue.

**Comment by shilovmaksim** [comment]
Thanks.

Lets check whether it is sufficient to mitigate the issue by adding these components.
Could you please try to install them during runtime using following PowerShell snippet:
```
Set-Location "C:\Program Files (x86)\Microsoft Visual Studio\Installer\"
$InstallPath = "C:\Program Files\Microsoft Visual Studio\2022\Preview"
$componentsToAdd = @(
  "Microsoft.VisualStudio.Component.VC.v141.ATL.ARM",
  "Microsoft.VisualStudio.Component.VC.v141.ATL.ARM64",
)
[string]$workloadArgs = $componentsToAdd | ForEach-Object {" --add " +  $_}
$Arguments = ('/c', "vs_installer.exe", 'modify', '--installPath', "`"$InstallPath`"",$workloadArgs, '--quiet', '--norestart', '--nocache')
$process = Start-Process -FilePath cmd.exe -ArgumentList $Arguments -Wait -PassThru -WindowStyle Hidden
if ($process.ExitCode -eq 0)
{
    Write-Host "components have been successfully added"
}
else
{
    Write-Host "components were not installed"
    exit 1
}
```

**Comment by shilovmaksim** [comment]
I updated snippet. There were some mistakes in paths.

**Comment by jbrianceau** [comment]
I've created a dedicated `with-v141-atl-install-on-the-fly` branch here: https://github.com/jbrianceau/SampleATLProject/tree/with-v141-atl-install-on-the-fly

I've triggered a pipeline run with this branch (not run against vs2017 on purpose, commit 76c33678df147259477ec72fc66d38b9e09d0e45), this is still ongoing, but looking good so far:
![image](https://user-images.githubusercontent.com/5746498/148955152-cc916e09-014d-4f72-8260-9babcdfcfb10.png)

**Comment by shilovmaksim** [comment]
Hi @jbrianceau.
PR #4857 that adding components to the image is merged. Image with update will be deployed next week.

**Comment by jbrianceau** [comment]
@shilovmaksim that's great news, thanks a lot 👍

**Comment by jbrianceau** [comment]
Hi @shilovmaksim
For the record, I confirm that this issue does not repro with the below image version so I'm closing this issue. Thanks again!
```
Environment: windows-2019
Version: 20220116.1
Included Software: https://github.com/actions/virtual-environments/blob/win19/20220116.1/images/win/Windows2019-Readme.md
Image Release: https://github.com/actions/virtual-environments/releases/tag/win19%2F20220116.1
```
