### ISSUE TITLE
[Linux] Add Apache Cassandra™

### ISSUE THREAD

**Issue by msmygit** [actions/virtual-environments#4829]
### Tool name

Cassandra

### Tool license

Apache License 2 - https://github.com/apache/cassandra/blob/trunk/LICENSE.txt

### Add or update?

- [X] Add
- [ ] Update

### Desired version

4.x

### Brief description of tool

Open Source NoSQL Database server. [Apache Cassandra&trade;](http://cassandra.apache.org/) is a highly-scalable partitioned row store. Rows are organized into tables with a required primary key.

### URL for tool's homepage

http://cassandra.apache.org/

### Virtual environments affected

- [X] Ubuntu 18.04
- [X] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Tool installation time in runtime

about a minute maximum

### Are you willing to submit a PR?

Yes

**Comment by msmygit** [comment]
Draft PR #4830

**Comment by freddy123098** [comment]
Hi

**Comment by freddy123098** [comment]
So I say this issue in open do u need any help?

**Comment by miketimofeev** [comment]
Hi @msmygit!
Apache Cassandra can be installed pretty fast (about 15 seconds) in runtime using tarball.
```
curl -OL https://downloads.apache.org/cassandra/4.0.1/apache-cassandra-4.0.1-bin.tar.gz
tar xzvf apache-cassandra-4.0.1-bin.tar.gz
df -hm
cd apache-cassandra-4.0.1/bin
nohup ./cassandra &
ps -ef | grep cassandra
```
Given tool popularity, maintenance concerns, and fast installation time in runtime we wouldn't like to add it to the image.
Please feel free to contact us if you have any concerns.
Thank you!

**Comment by msmygit** [comment]
@miketimofeev do you have any other suggested recommendation as to how to get it in the default image? Also, could you please provide / elaborate how tool popularity and maintenance concerns are quantified here to get a better understanding? Thank you in advance!
