### ISSUE TITLE
Provide Windows 10 SDK build 14393 (LTSB 1607) to windows-2022

### ISSUE THREAD

**Issue by moses70** [actions/virtual-environments#4831]
### Tool name

Windows 10 SDK build 14393 (LTSB 1607)

### Tool license

Part of Microsoft Visual Studio

### Add or update?

- [ ] Add
- [X] Update

### Desired version

Windows 10 SDK build 14393

### Approximate size

1.7 GB

### Brief description of tool

In issue #451 this SDK version was added to windows-2019.
I would like to request the same for windows-2022.
This windows version is supported (and used, unfortunately) until 2026 (see https://docs.microsoft.com/de-de/lifecycle/products/windows-10-iot-enterprise-ltsb-2016)

### URL for tool's homepage

https://developer.microsoft.com/en-us/windows/downloads/sdk-archive/

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Can this tool be installed during the build?

```bash
Can be done, but it is very large and will add several minutes of build time to each build.
```

**Comment by miketimofeev** [comment]
Hi @moses70!
Could you please clarify why you need this version on windows-2022? Is it possible for you to use the windows-2019 image?

**Comment by moses70** [comment]
Hi @miketimofeev,

we are using the windows-2019 now as a workaround. 
But in the future, we would like to use VS2022 with .NET 6.0 and I suppose this will be available only on the windows-2022 image, right?

The current option to fall back on .NET 5.0 will go away when it falls out of service (which is quite soon - May 8, 2022).

How could we handle this?

**Comment by miketimofeev** [comment]
@moses70 Correct, VS2022 is available only on windows-2022 image. However, you can install .Net 6 on windows-2019 as well using either https://github.com/actions/setup-dotnet action or https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/tool/dotnet-core-tool-installer?view=azure-devops task (it takes a few seconds). Does this suit you?

And I believe once 5.0 reaches EOL, VS2019 bundled .NET will be updated to the recent version (5.1 or 6.0 probably?)

**Comment by moses70** [comment]
Hi @miketimofeev 

thank you for your suggestions. 
I am a bit concerned if this  "you can install .Net 6 on windows-2019" will be a valid option,
because VS2019 does not support .NET 6.0 and this most certainly will not change.

Could we please leave this issue open until more detailed info is available on how Microsoft suggests to handle the EOL of .NET 5 in connection with VS 2019?

**Comment by miketimofeev** [comment]
@moses70 for sure! Please ping us when there is an update about .NET support in VS2019 and we will reconsider adding this SDK if needed.
