### ISSUE TITLE
Update Azure PowerShell 7.1

### ISSUE THREAD

**Issue by dcaro** [actions/virtual-environments#4832]
### Tool name

Azure PowerShell

### Tool license

Apache 2

### Add or update?

- [ ] Add
- [X] Update

### Desired version

7.1

### Brief description of tool

Azure PowerShell modules 

### URL for tool's homepage

https://github.com/Azure/azure-powershell

### Provide a basic test case to validate the tool's functionality.

```bash
Connect-AzAccount
```

### Virtual environments affected

- [X] Ubuntu 18.04
- [X] Ubuntu 20.04
- [X] macOS 10.15
- [X] macOS 11
- [X] Windows Server 2016
- [X] Windows Server 2019
- [X] Windows Server 2022

**Comment by Afsoning2** [comment]
#4085 #3577 #4313 #4815 #4838

**Comment by miketimofeev** [comment]
Hi @dcaro!
We will update the version next week, here is the announcement https://github.com/actions/virtual-environments/issues/4841

**Comment by nikolai-frolov** [comment]
Azure PowerShell update was deployed to all images.
