### ISSUE TITLE
Update GitHub CLI

### ISSUE THREAD

**Issue by marcinbak** [actions/virtual-environments#4835]
### Tool name

GitHub CLI

### Tool license

https://github.com/cli/cli/blob/trunk/LICENSE

### Add or update?

- [ ] Add
- [X] Update

### Desired version

2.4.0

### Virtual environments affected

- [ ] Ubuntu 18.04
- [X] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Are you willing to submit a PR?

Yes

**Comment by marcinbak** [comment]
From what it looks like building of new Ubuntu image will download latest GitHub CLI, so no change is required, only creation of new release and rebuilding of the image.

**Comment by shilovmaksim** [comment]
Hi @marcinbak . 
New versions of the images will be deployed next week.

**Comment by miketimofeev** [comment]
@marcinbak the images were updated.
I'm going to close the issue. Please feel free to contact us if you have any concerns.
Thank you!
