### ISSUE TITLE
MacOS iOS 15.2 simulator unavailable

### ISSUE THREAD

**Issue by slhodson969** [actions/virtual-environments#4839]
### Description

I am upgrading our workflow to use Xcode `13.2.1` and we have it setup to run snapshot tests on an iPhone 12 mini using the latest OS. Based on what I read [here](https://github.com/actions/virtual-environments/blob/main/images/macos/macos-11-Readme.md) I would expect the latest OS version to be `15.2`.

However, after updating all the snapshots locally the workflow started to fail when running the tests. I decided to list the installed simulators and noticed this in the log:

```
== Devices ==
86
-- iOS 15.0 --
...
...
-- Unavailable: com.apple.CoreSimulator.SimRuntime.iOS-15-2 --
```

So I am presuming it is using `15.0` instead.

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [X] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

`20211219.1`

### Expected behavior

The tests to be ran on an iOS 15.2 simulator

### Actual behavior

The tests are ran on an iOS 15.0 simulator

### Repro steps

Setup a workflow to run on `macos-11`, using Xcode `13.2.1` and an iOS simulator with OS set to `latest`

**Comment by dmitry-shibanov** [comment]
Hello @slhodson969. Thank you for your report. For now default version of Xcode is [13.1](https://github.com/actions/virtual-environments/blob/main/images/macos/macos-11-Readme.md#xcode). Could you please try to use this [action](https://github.com/maxim-lobanov/setup-xcode) to change Xcode version. Possible snippet:
```
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
```
By the way, the default version of Xcode will be changed to 13.2.1 on [January, 24](https://github.com/actions/virtual-environments/issues/4800).

**Comment by freddy123098** [comment]
hi, I am a Mac user and I am going to help you.

**Comment by slhodson969** [comment]
@dmitry-shibanov: Using the setup-xcode action has the same result. The snapshots still fail as the iOS 15.2 runtime is not available.

As the [README](https://github.com/actions/virtual-environments/blob/main/images/macos/macos-11-Readme.md) states that iOS 15.2 should be available, I am presuming this is a bug.
Or is the information in the README wrong?
Or is my presumption wrong?

**Comment by dmitry-shibanov** [comment]
Hello @slhodson969. Thank you for your answer. Could please provide public repository or minimum repro steps to reproduce the issue. 

After changing Xcode version to the latest I have a such output:
```
== Runtimes ==
iOS 15.2 (15.2 - 19C51) - com.apple.CoreSimulator.SimRuntime.iOS-15-2
tvOS 15.2 (15.2 - 19K50) - com.apple.CoreSimulator.SimRuntime.tvOS-15-2
watchOS 8.3 (8.3 - 19S51) - com.apple.CoreSimulator.SimRuntime.watchOS-8-3
== Devices ==
-- iOS 15.2 --
    iPhone 8 (F5E9BC45-8CDA-4102-AD9A-8AC761F74B3D) (Shutdown) 
    iPhone 8 Plus (CE6BF842-33DA-4A92-944B-FF39132D7D66) (Shutdown) 
    iPhone 11 (067A9D60-CFBF-414C-810E-CA18BB97A72A) (Shutdown) 
    iPhone 11 Pro (C591C4D4-239D-485F-97A2-92E6E1B5F47E) (Shutdown) 
    iPhone 11 Pro Max (928F677E-4FA8-4D42-9777-5B365265DE2B) (Shutdown) 
    iPhone SE (2nd generation) (9EAF7167-3EAA-4DDA-998F-013B852FE148) (Shutdown) 
    iPhone 12 mini (72D644EE-065B-4595-BB1D-DBBA8AA9F405) (Shutdown) 
    iPhone 12 (337CED20-156E-4692-8B76-58E4FD2F2D5A) (Shutdown) 
    iPhone 12 Pro (2DBD14E6-1AB1-4483-A45A-98FD529A85B5) (Shutdown) 
    iPhone 12 Pro Max (974116E5-6ED5-4972-9C95-EA8C2A660B19) (Shutdown) 
    iPhone 13 Pro (4086F8A1-4170-4C5C-A09B-E8337A2EC0B4) (Shutdown) 
    iPhone 13 Pro Max (7D153E55-404F-422B-B651-E1228A3FCA0C) (Shutdown) 
    iPhone 13 mini (1BD3F20D-16B1-4B4C-980C-C91119FF8317) (Shutdown) 
    iPhone 13 (52B4CA1B-0C66-44F5-9DBA-524E31F43B22) (Shutdown) 
    iPod touch (7th generation) (93A1D325-3E2B-4127-8F4A-7DE0ECCF4364) (Shutdown) 
    iPad Pro (9.7-inch) (30C25640-832E-4CA6-8009-8DCF80050093) (Shutdown) 
    iPad (7th generation) (9CEEDA45-8969-40F0-8065-7F96683C18B5) (Shutdown) 
    iPad Pro (11-inch) (2nd generation) (DE406318-C77F-44E3-9419-B92F65E178EE) (Shutdown) 
    iPad Pro (12.9-inch) (4th generation) (4755358D-9831-4E8A-BB33-6BCD561CB9C2) (Shutdown) 
    iPad Air (3rd generation) (580B1748-3D14-4745-92EB-0605A2683132) (Shutdown) 
    iPad (8th generation) (5109F274-B7B5-41F7-881E-B539D4D8FB9E) (Shutdown) 
    iPad (9th generation) (437F7268-49EC-4810-81B8-AF72E2666B60) (Shutdown) 
    iPad Air (4th generation) (E4D793FA-AE8C-4919-8918-86BE7F01E7F2) (Shutdown) 
    iPad Pro (11-inch) (3rd generation) (3BB7A3C7-519F-45E7-BD33-9D8AF7AF365F) (Shutdown) 
    iPad Pro (12.9-inch) (5th generation) (4402F5DA-F4E4-45FB-8922-774D6380679B) (Shutdown) 
    iPad mini (6th generation) (D01967A6-0874-465C-855F-0BC9B2376365) (Shutdown) 
-- tvOS 15.2 --
    Apple TV (577B3D88-B1AC-48E4-9723-5A42B7986507) (Shutdown) 
    Apple TV 4K (B04D1BBA-CF05-4586-AF9B-3690511AC29C) (Shutdown) 
    Apple TV 4K (at 1080p) (B5FAFC4B-4B42-423A-9846-8C99EBCFBF71) (Shutdown) 
    Apple TV 4K (2nd generation) (E67E1B1E-E753-4E0B-93A8-69AA6808AAD6) (Shutdown) 
    Apple TV 4K (at 1080p) (2nd generation) (EEA782F4-EE17-47A0-9C6A-792416C80139) (Shutdown) 
-- watchOS 8.3 --
    Apple Watch Series 4 - 40mm (FB590F0F-BE0E-453F-9603-50D2EB3B32B2) (Shutdown) 
    Apple Watch Series 4 - 44mm (4F5DC98C-5D12-4B4A-B71A-E516B6228BC0) (Shutdown) 
    Apple Watch Series 5 - 40mm (BB2754BC-1D41-449C-BA9F-7E23029FEB79) (Creating) 
    Apple Watch Series 5 - 44mm (16D8803D-9568-42BA-9866-E41E119FDDB7) (Shutdown) 
    Apple Watch Series 6 - 40mm (6483DC10-C44A-444B-A4D5-735F79E1EE7A) (Shutdown) 
    Apple Watch Series 6 - 44mm (D982B20C-68F6-40B0-8BAC-64DD9789E541) (Shutdown) 
    Apple Watch Series 7 - 41mm (F890646B-1A96-458E-86F0-5FC2B2ABBC68) (Shutdown) 
    Apple Watch Series 7 - 45mm (AFB5ED89-79F9-4837-8CEF-2AD0595270D7) (Shutdown) 
```
After booting a default simulator with the command: `open -a Simulator.app` I get such output:
```
== Runtimes ==
iOS 15.2 (15.2 - 19C51) - com.apple.CoreSimulator.SimRuntime.iOS-15-2
tvOS 15.2 (15.2 - 19K50) - com.apple.CoreSimulator.SimRuntime.tvOS-15-2
watchOS 8.3 (8.3 - 19S51) - com.apple.CoreSimulator.SimRuntime.watchOS-8-3
== Devices ==
-- iOS 15.2 --
    iPhone 8 (F5E9BC45-8CDA-4102-AD9A-8AC761F74B3D) (Shutdown) 
    iPhone 8 Plus (CE6BF842-33DA-4A92-944B-FF39132D7D66) (Shutdown) 
    iPhone 11 (067A9D60-CFBF-414C-810E-CA18BB97A72A) (Shutdown) 
    iPhone 11 Pro (C591C4D4-239D-485F-97A2-92E6E1B5F47E) (Shutdown) 
    iPhone 11 Pro Max (928F677E-4FA8-4D42-9777-5B365265DE2B) (Shutdown) 
    iPhone SE (2nd generation) (9EAF7167-3EAA-4DDA-998F-013B852FE148) (Shutdown) 
    iPhone 12 mini (72D644EE-065B-4595-BB1D-DBBA8AA9F405) (Shutdown) 
    iPhone 12 (337CED20-156E-4692-8B76-58E4FD2F2D5A) (Shutdown) 
    iPhone 12 Pro (2DBD14E6-1AB1-4483-A45A-98FD529A85B5) (Shutdown) 
    iPhone 12 Pro Max (974116E5-6ED5-4972-9C95-EA8C2A660B19) (Shutdown) 
    iPhone 13 Pro (4086F8A1-4170-4C5C-A09B-E8337A2EC0B4) (Shutdown) 
    iPhone 13 Pro Max (7D153E55-404F-422B-B651-E1228A3FCA0C) (Shutdown) 
    iPhone 13 mini (1BD3F20D-16B1-4B4C-980C-C91119FF8317) (Shutdown) 
    iPhone 13 (52B4CA1B-0C66-44F5-9DBA-524E31F43B22) (Booted) 
    iPod touch (7th generation) (93A1D325-3E2B-4127-8F4A-7DE0ECCF4364) (Shutdown) 
    iPad Pro (9.7-inch) (30C25640-832E-4CA6-8009-8DCF80050093) (Shutdown) 
    iPad (7th generation) (9CEEDA45-8969-40F0-8065-7F96683C18B5) (Shutdown) 
    iPad Pro (11-inch) (2nd generation) (DE406318-C77F-44E3-9419-B92F65E178EE) (Shutdown) 
    iPad Pro (12.9-inch) (4th generation) (4755358D-9831-4E8A-BB33-6BCD561CB9C2) (Shutdown) 
    iPad Air (3rd generation) (580B1748-3D14-4745-92EB-0605A2683132) (Shutdown) 
    iPad (8th generation) (5109F274-B7B5-41F7-881E-B539D4D8FB9E) (Shutdown) 
    iPad (9th generation) (437F7268-49EC-4810-81B8-AF72E2666B60) (Shutdown) 
    iPad Air (4th generation) (E4D793FA-AE8C-4919-8918-86BE7F01E7F2) (Shutdown) 
    iPad Pro (11-inch) (3rd generation) (3BB7A3C7-519F-45E7-BD33-9D8AF7AF365F) (Shutdown) 
    iPad Pro (12.9-inch) (5th generation) (4402F5DA-F4E4-45FB-8922-774D6380679B) (Shutdown) 
    iPad mini (6th generation) (D01967A6-0874-465C-855F-0BC9B2376365) (Shutdown) 
```
iPhone 13 was booted and I could get an image from it with the `xcrun simctl io booted screenshot screen.png` command.

**Comment by slhodson969** [comment]
Hey @dmitry-shibanov,

It looks like I made a mistake when debugging why the snapshots were failing and was listing the simulators before I had set the Xcode version to `13.2.1`. I therefore presume it was using the default version of Xcode which does not include the iOS 15.2 simulators. Once I moved the listing of simulators to after setting the Xcode version, the iOS 15.2 runtime is found.

I am still having the issue with my snapshots passing locally but failing during the workflow, but I guess I need to do some more debugging myself there to see what's going on. I will close this issue (as the 15.2 runtime is there) and open a new one if I am unable to solve the failing snapshots.

**Comment by bhargavas12** [comment]
@slhodson969 I tried to set xcode version in azure pipeline as below:

- task: Xcode@5
  displayName: 'Build with XCode - Workforce'
  inputs:
    actions: 'archive'
    scheme: 'Workforce'
    sdk: 'iphoneos'
    configuration: 'Release'
    xcWorkspacePath: '**/*/Workforce.xcworkspace'
    xcodeVersion: '/Applications/Xcode_13.2.1.app'
    signingOption: 'manual' # Options: nosign, default, manual, auto
    signingIdentity: '$(APPLE_CERTIFICATE_SIGNING_IDENTITY)'
    provisioningProfileUuid: $(APPLE_PROV_PROFILE_UUID)
    useXcpretty: false # Makes iyt easier to diagnose build failures
    args: '-allowProvisioningUpdates -IPHONEOS_DEPLOYMENT_TARGET=15 -UseModernBuildSystem=0'
    packageApp: true

after setting to this I am getting the below error:

##[error]Error: Unable to resolve the developer path for Xcode `/Applications/Xcode_13.2.1.app`. Set the `XCODE_/Applications/Xcode_13.2.1.app_DEVELOPER_DIR` environment variable on the agent machine, or set `Xcode version` to `Default` or `Specify path`.

**Comment by bhargavas12** [comment]
@dmitry-shibanov  still the xcode default is pointing to 13.1.
I guess the change you mentioned is already rolledout? is that right?

**Comment by miketimofeev** [comment]
@bhargavas12 I'm afraid, no, the rollout started yesterday and will take 2-3 days.
