### ISSUE TITLE
Update SSDT to latest version

### ISSUE THREAD

**Issue by fan130** [actions/virtual-environments#484]
**Tool information**
- Tool name: SQL Server Data Tools
- Add or update? Update
- Desired version: 15.9.3
- Approximate size: 

**Area for Triage**:
Recently we added a new property in SSIS runtime, and current version of SSDT installed in vs2017-win2016 cannot build the ispac with this property, so we want to update the SSDT version to latest to unblock our customers from using Microsoft-hosted agents. Please note that please use the SSDT standalone installer downloaded from https://docs.microsoft.com/en-us/sql/ssdt/download-sql-server-data-tools-ssdt?view=sql-server-ver15#ssdt-for-vs-2017-standalone-installer, and make sure "SQL Server Integration Services" is checked.

**Question, Bug, or Feature?**:
Bug

**Virtual environments affected**
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [X] Windows Server 2016 R2
- [ ] Windows Server 2019

**Can this tool be installed during the build?**
It's a Burn installer, which will download payload during installation. The payload contains MSI, EXE,and VSIX. It has command line arguments support for unattended installation. Please launch the installer with "/?" for more details.

**Are you willing to submit a PR?**
I'm willing to, but I don't know how to do the change.

**Comment by m-minasyan** [comment]
Hello, @fan130. I updated the SSDT version to the 15.9.3. VM image with the changes will be rolled out next week.

**Comment by fan130** [comment]
@m-minasyan , thanks a lot for your quick action!

**Comment by blueelvis** [comment]
@m-minasyan - I tried this in the same pool above but I am still seeing the older version. Any idea what could be wrong?
```
LocalDB instance "MSSQLLocalDB" created with version 13.1.4001.0.
```

**Comment by AlenaSviridenko** [comment]
Hi @blueelvis! 
MS SQL LocalDB is installed through Visual Studio installer, so installation of SSDT don't affect it.
We will consider the idea of installing a separate SQL Server Express in order to have more up-to-date version of LocalDB.
Thanks for raising this issue!
