### ISSUE TITLE
Running `softwareupdate --list-full-installers` does not show the latest version of macOS 11

### ISSUE THREAD

**Issue by cadsit** [actions/virtual-environments#4840]
### Description

We're using the hosted Mac pools to generate bootable images of the latest versions of macOS through `softwareupdate`.

macOS 11.6.3 was released on Dec 19th, yet it does not appear as an available download when running `softwareupdate --list-full-installers` (which performs a scan for all available installers through Apple), and I can verify that an installer does exist on my personal machine, which runs macOS 11.6.2.

Could there be a configuration issue on the Hosted Pool that's preventing `softwareupdate` from finding the latest version?

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [X] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Version: 20211219.1

Build link: https://dev.azure.com/devdiv/DevDiv/_build/results?buildId=5597915&view=results

### Is it regression?

no

### Expected behavior

The 11.6.3 installer is present in the following:

```
% softwareupdate --list-full-installers
Finding available software
Software Update found the following full installers:
* Title: macOS Monterey, Version: 12.1, Size: 12157035487K
* Title: macOS Monterey, Version: 12.0.1, Size: 12128428704K
* Title: macOS Big Sur, Version: 11.6.3, Size: 12422234465K
* Title: macOS Big Sur, Version: 11.6.2, Size: 12433351292K
* Title: macOS Big Sur, Version: 11.6.1, Size: 12428472512K
* Title: macOS Big Sur, Version: 11.6, Size: 12428553042K
* Title: macOS Big Sur, Version: 11.5.2, Size: 12440916552K
```

### Actual behavior

The 11.6.3 is absent in the following:

```
% softwareupdate --list-full-installers
Finding available software
Software Update found the following full installers:
* Title: macOS Monterey, Version: 12.1, Size: 12157035487K
* Title: macOS Monterey, Version: 12.0.1, Size: 12128428704K
* Title: macOS Big Sur, Version: 11.6.2, Size: 12433351292K
* Title: macOS Big Sur, Version: 11.6.1, Size: 12428472512K
* Title: macOS Big Sur, Version: 11.6, Size: 12428553042K
* Title: macOS Big Sur, Version: 11.5.2, Size: 12440916552K
* Title: macOS Catalina, Version: 10.15.7, Size: 8248985973K
* Title: macOS Catalina, Version: 10.15.7, Size: 8248196334K
* Title: macOS Catalina, Version: 10.15.7, Size: 8248854894K
* Title: macOS Catalina, Version: 10.15.6, Size: 8248781171K
* Title: macOS Catalina, Version: 10.15.6, Size: 8250022229K
* Title: macOS Catalina, Version: 10.15.5, Size: 8236829020K
* Title: macOS Catalina, Version: 10.15.4, Size: 8250718056K
* Title: macOS Catalina, Version: 10.15.3, Size: 8184371561K
* Title: macOS Mojave, Version: 10.14.6, Size: 6038419486K
* Title: macOS Mojave, Version: 10.14.5, Size: 6033811488K
* Title: macOS Mojave, Version: 10.14.4, Size: 6036269091K
* Title: macOS High Sierra, Version: 10.13.6, Size: 5221689433K
```

### Repro steps

1. Run `softwareupdate --list-full-installers` through a bash/zsh session
2. Check the output for the 11.6.3 installer

**Comment by al-cheb** [comment]
Hey, @cadsit 
The macOS 11.6.3 is still beta.

```
 - run: |
           sudo "/System/Library/PrivateFrameworks/Seeding.framework/Versions/Current/Resources/seedutil" enroll DeveloperSeed
           sleep 5
           softwareupdate --list-full-installers
```

![image](https://user-images.githubusercontent.com/47745270/148724968-85621980-90ab-4601-8344-48b6585995c6.png)
