### ISSUE TITLE
[All OSs] Az PowerShell Module will be upgraded to 7.1.0 on January, 17

### ISSUE THREAD

**Issue by MaksimZhukov** [actions/virtual-environments#4841]
### Breaking changes

Az PowerShell Module will be upgraded to 7.1.0 on all available images.

### Target date

Deployment will start January 17 and will take 3-4 days.

### The motivation for the changes

We'd like to keep images up-to-date with recent software updates.

### Possible impact

There are several breaking changes in 7 release of Az PowerShell Module thus your builds can be broken after the update. More information about breaking changes can be found on the official changelog:
- [Az 7.0.0](https://github.com/Azure/azure-powershell/releases/tag/v7.0.0-December2021)
- [Az 7.1.0](https://github.com/Azure/azure-powershell/releases/tag/v7.1.0-January2022)

### Virtual environments affected

- [X] Ubuntu 18.04
- [X] Ubuntu 20.04
- [X] macOS 10.15
- [X] macOS 11
- [X] Windows Server 2016
- [X] Windows Server 2019
- [X] Windows Server 2022

### Mitigation ways

Consider using the following actions\tasks to use pre-cached Az versions or to install desired version in runtime:
- [Azure PowerShell action](https://github.com/marketplace/actions/azure-powershell-action) for GitHub
- [Azure PowerShell task](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-powershell?view=azure-devops) for Azure DevOps

These actions\tasks don't support macOS. To downgrade Az version on macOS images, please use the following PowerShell snippet:
```
Install-Module Az -RequiredVersion <desired version> -Force -Scope AllUsers
```

**Comment by paulb76** [comment]
Is the update also going onto Microsoft Hosted Agents?

**Comment by nikolai-frolov** [comment]
@paulb76 images will be updated for GitHub Actions hosted runners and [Microsoft-hosted agents](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops&tabs=yaml#use-a-microsoft-hosted-agent) used for Azure Pipelines

**Comment by paulb76** [comment]
Thank you.

**Comment by nikolai-frolov** [comment]
@BraisGabin, thanks for the issue reporting. Unfortunately, you are right and default Java version was mistakenly downgraded for `ubuntu-20.04`. It will be fixed ASAP.

**Comment by nikolai-frolov** [comment]
Azure PowerShell update was deployed to all images.
