### ISSUE TITLE
Access is denied:  azure-devops\\azure_devops-0.22.0.dist-info

### ISSUE THREAD

**Issue by mayong43111** [actions/virtual-environments#4842]
### Description

Run azure/login@v1
C:\Windows\system32\cmd.exe /D /S /C ""C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin\az.cmd" cloud set -n azurecloud"
ERROR: The command failed with an unexpected error. Here is the traceback:
ERROR: [WinError 5] Access is denied: 'C:\\Program Files\\Common Files\\AzureCliExtensionDirectory\\azure-devops\\azure_devops-0.22.0.dist-info'
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 512, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/__init__.py", line 475, in load_command_table
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/__init__.py", line 346, in _update_command_table_from_extensions
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/extension/__init__.py", line 163, in get_metadata
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\pkginfo/wheel.py", line 16, in __init__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\pkginfo/distribution.py", line 115, in extractMetadata
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\pkginfo/wheel.py", line 33, in read

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [X] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Current runner version: '2.283.3'
Runner name: 'Default-01'
Runner group name: 'Default'
Machine name: 'GitHub-Actions-'
GITHUB_TOKEN Permissions
Prepare workflow directory
Prepare all required actions
Getting action download info
Download action repository 'actions/checkout@v2' (SHA:5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f)
Download action repository 'microsoft/setup-msbuild@v1.1' (SHA:ab534842b4bdf384b8aaf93765dc6f721d9f5fab)
Download action repository 'azure/login@v1' (SHA:66d2e78565ab7af265d2b627085bc34c73ce6abb)
Download action repository 'azure/sql-action@v1' (SHA:f9ff4fa54cc7a5c627afd5fce45ad466065759cf)

### Repro steps

1. build new image
2. run actions az login

**Comment by al-cheb** [comment]
Hey, @mayong43111 
We will take a look at it.

**Comment by al-cheb** [comment]
@mayong43111, Please provide the output of `whoami /groups`  command.

**Comment by al-cheb** [comment]
@mayong43111, Any updates?

**Comment by mayong43111** [comment]
> @mayong43111，请提供命令的输出。`whoami /groups`

Hi @al-cheb ，before I used the account is "network service" (github actions runner default option), now is system.  system is ok, but that's not a good idea.

before
```
GROUP INFORMATION
-----------------

Group Name                                  Type             SID                                            Attributes                                        
=========================================== ================ ============================================== ==================================================
Mandatory Label\System Mandatory Level      Label            S-1-16-16384                                                                                     
Everyone                                    Well-known group S-1-1-0                                        Mandatory group, Enabled by default, Enabled group
GitHub-Actions-\GITHUB_ActionsRunner_G8c556 Alias            S-1-5-21-1981952160-1679621179-3613932367-1003 Mandatory group, Enabled by default, Enabled group
BUILTIN\Users                               Alias            S-1-5-32-545                                   Mandatory group, Enabled by default, Enabled group
NT AUTHORITY\SERVICE                        Well-known group S-1-5-6                                        Mandatory group, Enabled by default, Enabled group
CONSOLE LOGON                               Well-known group S-1-2-1                                        Mandatory group, Enabled by default, Enabled group
NT AUTHORITY\Authenticated Users            Well-known group S-1-5-11                                       Mandatory group, Enabled by default, Enabled group
NT AUTHORITY\This Organization              Well-known group S-1-5-15                                       Mandatory group, Enabled by default, Enabled group
LOCAL                                       Well-known group S-1-2-0                                        Mandatory group, Enabled by default, Enabled group
```

now
```
  whoami /groups
  shell: C:\Program Files\PowerShell\7\pwsh.EXE -command ". '{0}'"

GROUP INFORMATION
-----------------

Group Name                             Type             SID          Attributes                                        
====================================== ================ ============ ==================================================
BUILTIN\Administrators                 Alias            S-1-5-32-544 Enabled by default, Enabled group, Group owner    
Everyone                               Well-known group S-1-1-0      Mandatory group, Enabled by default, Enabled group
NT AUTHORITY\Authenticated Users       Well-known group S-1-5-11     Mandatory group, Enabled by default, Enabled group
Mandatory Label\System Mandatory Level Label            S-1-16-16384      
```

**Comment by al-cheb** [comment]
All our agents are run under a user account member of Administartor group in interactive session with enabled autologon. Closed as external configuration issue.
