### ISSUE TITLE
Inconsistent string normalization between OS's

### ISSUE THREAD

**Issue by LTA-Thinking** [actions/virtual-environments#4844]
### Description

On Jan 6 2022 we noticed in our Linux build machines that unit tests focusing on globalization and string normalization started failing with no changes to our repo. 

The issues we are running into:
- German (de-DE) number format changed the separator character from a comma to a period. Expected value: 27,765, Actual value: 27.765
- String normalization form KD is no longer splitting certain characters. Example: Input: ü (00FC), Expected value: (0075)(0308), Actual value: (00FC)

Our repo is running .NET 5.0.402, Image ubuntu-latest.
We are not seeing these issues on our tests run in a machine with the windows-latest image.

Was this an expected change?

### Virtual environments affected

- [ ] Ubuntu 18.04
- [X] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Version: 20211219.1

### Expected behavior

Consistent behavior between Windows and Linux images.

### Actual behavior

Different behavior for globalization and normalization tasks. See issue description.

### Repro steps

Run the following tests in a .NET unit test in a Linux and Windows image and view the output.
```
[Fact]
public void GivenAString_WhenNormalized_ExpectedValuesAreReturned()
        {
            var testString = "Müller";
            var normalizedString = testString.Normalize(System.Text.NormalizationForm.FormKD);

            Console.Write("Characters in normalized string = ");
            foreach (short x in normalizedString)
            {
                Console.Write("{0:X4} ", x);
            }

            Console.WriteLine();

            var charArray = normalizedString.ToCharArray();
            Assert.Equal((char)117, charArray[1]); // Lowercase u
            Assert.Equal((char)776, charArray[2]); // Combining Diaeresis
        }

[Fact]
public void GivenACulture_WhenFormatingAStirng_ThenExpectedStringIsReturned()
        {
            System.Threading.Thread.CurrentThread.CurrentCulture = new System.Globalization.CultureInfo("de-DE");
            var numberString = string.Format("{0:00.0000000}", 27 + 0.765);

            Assert.Equal("27,7650000", numberString);
        }
```

**Comment by LTA-Thinking** [comment]
Debugging further I think this might be caused by the image missing the ICU library.

**Comment by al-cheb** [comment]
Hey, @LTA-Thinking 
We will take a look at it.

**Comment by LTA-Thinking** [comment]
Thanks @al-cheb 
We were able to fix the issue for our repo by upgrading our .Net sdk to version 5.0.403. It is unclear why this change fixed the issue, but all our tests are now passing in both OS images.

**Comment by V-Zabayrachny** [comment]
Hello @LTA-Thinking. We always recommend using the latest version of dotnet. For problems related to the work of dotnet itself, you can contact with [dotnet team](https://github.com/dotnet) . I'm going to close the issue. If you have any concerns feel free to ping us.
