### ISSUE TITLE
Unable to retrieve qemu packages

### ISSUE THREAD

**Issue by MacDaddyFPV** [actions/virtual-environments#4848]
### Description

We have been running our OpenHD image builder in Ubuntu 20.04 successfully for a while now.
A few days ago we started having issues with retrieving qemu and qemu-static-user packages.
The deps stage is trying to retrieve http://azure.archive.ubuntu.com/ubuntu/pool/main/q/qemu/qemu_4.2-3ubuntu6.18_amd64.deb and http://azure.archive.ubuntu.com/ubuntu/pool/universe/q/qemu/qemu-user-static_4.2-3ubuntu6.18_amd64.deb but these  packages no longer exist. There are packages for 6.19 but these are not being recognised as the latest. 

### Virtual environments affected

- [ ] Ubuntu 18.04
- [X] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

https://github.com/OpenHD/Open.HD_Image_Builder/actions/workflows/nightlybuild_20.yml

### Expected behavior

Expect the latest qemu packages to be retrieved for ubuntu 20.04.

### Actual behavior

Builder is trying to retrive older packages which have been removed

### Repro steps

Have tried re-running the builder but the problem persists.

**Comment by wojsmol** [comment]
Hi
Add `apt get update` before installing packages from `apt`.

**Comment by MacDaddyFPV** [comment]
This fixed the issue, Thanks.
