### ISSUE TITLE
Add [procdump]

### ISSUE THREAD

**Issue by FrancescElies** [actions/virtual-environments#4850]
### Tool name

procdump

### Tool license

﻿Sysinternals Software License Terms

### Add or update?

- [X] Add
- [ ] Update

### Desired version

latest

### Approximate size

400K

### Brief description of tool

ProcDump is a command-line utility whose primary purpose is monitoring an application for CPU spikes and generating crash dumps during a spike that an administrator or developer can use to determine the cause of the spike. ProcDump also includes hung window monitoring (using the same definition of a window hang that Windows and Task Manager use), unhandled exception monitoring and can generate dumps based on the values of system performance counters. It also can serve as a general process dump utility that you can embed in other scripts.

### URL for tool's homepage

https://docs.microsoft.com/en-us/sysinternals/downloads/procdump

### Provide a basic test case to validate the tool's functionality.

When a process crashes I would like to generate a crash dump to continue debugging or providing more information to other developers, e.g. https://github.com/llvm/llvm-project/issues/52728

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Can this tool be installed during the build?

```bash
Sure, just download it and use.
```

### Tool installation time in runtime

Not much but I thought it would be nice to have it.

### Are you willing to submit a PR?

With a bit of guidance I would

**Comment by al-cheb** [comment]
Hey, @FrancescElies 

This tool is easy to install in runtime.
```
 - run: |
      curl.exe -s "https://download.sysinternals.com/files/Procdump.zip" -o "Procdump.zip"
      7z x Procdump.zip -o"C:\Windows
```

**Comment by miketimofeev** [comment]
@FrancescElies Considering fast installation time in runtime and maintenance concerns we would not like to add the tool to the image. Please use the snippet provided.
I'm going to close the issue, feel free to contact us if you have any concerns.
Thank you!
