### ISSUE TITLE
Update/Add .NET Core SDK

### ISSUE THREAD

**Issue by hvitved** [actions/virtual-environments#4851]
### Tool name

.NET Core SDK

### Tool license

?

### Add or update?

- [X] Add
- [ ] Update

### Desired version

6.0.101

### Brief description of tool

.NET 6 is already installed for [windows-2022](https://github.com/actions/virtual-environments/blob/main/images/win/Windows2022-Readme.md#net-core-sdk), could we please have it added to [ubuntu-latest](https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-Readme.md#net-core-sdk) as well?

Thanks!

### Virtual environments affected

- [ ] Ubuntu 18.04
- [X] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [ ] Windows Server 2022

**Comment by al-cheb** [comment]
Hey, @hvitved 
Close - https://github.com/actions/virtual-environments/issues/4424#issuecomment-967012616

**Comment by hvitved** [comment]
Sorry, I hadn't seen that issue.
