### ISSUE TITLE
windows-2022 image does not include .NET 4.7 Targetting Pack

### ISSUE THREAD

**Issue by Styxxy** [actions/virtual-environments#4858]
### Description

The windows-2022 image does not include the .NET 4.7 Targetting Pack (compared to windows-2019). This causes issues in some of our multi-targetted libraries, that target net47.

Can you add it back?

| windows-2022 | vs | windows-2019 |
|-|-|-|
| ![image](https://user-images.githubusercontent.com/1635825/148989895-3c27a91b-1a77-41ab-bd29-a015ace56fba.png) | | ![image](https://user-images.githubusercontent.com/1635825/148989934-96557727-2fbc-4e15-822e-ec09c8489a9d.png) |

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

Environment: windows-2022
Version: 20211219.1
Included Software: https://github.com/actions/virtual-environments/blob/win22/20211219.1/images/win/Windows2022-Readme.md
Image Release: https://github.com/actions/virtual-environments/releases/tag/win22%2F20211219.1

### Repro steps

Create a project that targets .NET 4.7 and try to build it on the image.

**Comment by al-cheb** [comment]
Hey, @Styxxy 
Please provide a simple repo how to reproduce the issue.

**Comment by Styxxy** [comment]
@al-cheb Do you need me to create the most dummy basic .NET 4.7 repo?

Hereby the steps:
1. Open Visual Studio 2022 (make sure you have the .NET 4.7 Targetting Pack installed).
2. Create new project -> Console App (.NET Framework) -> choose .NET 4.7 as targetting platform.
3. Commit
4. Try building it on windows-2022.

**Comment by al-cheb** [comment]
@Styxxy , Could you check if the snippet above fix your issue?

**Comment by Styxxy** [comment]
> @Styxxy , Could you check if the snippet above fix your issue?

It might work, but does add a lot of overhead to pipelines to include that snipped, rather than have it by default included in the image (like it was with windows-2019)?

**Comment by al-cheb** [comment]
> > @Styxxy , Could you check if the snippet above fix your issue?
> 
> It might work, but does add a lot of overhead to pipelines to include that snipped, rather than have it by default included in the image (like it was with windows-2019)?

We need to be sure that this fix the issue, maybe we will add some more components.

**Comment by Styxxy** [comment]
> > > @Styxxy , Could you check if the snippet above fix your issue?
> > 
> > 
> > It might work, but does add a lot of overhead to pipelines to include that snipped, rather than have it by default included in the image (like it was with windows-2019)?
> 
> We need to be sure that this fix the issue, maybe we will add some more components.

Ok, will try to test tomorrow to make sure it works.

**Comment by Styxxy** [comment]
> > > @Styxxy , Could you check if the snippet above fix your issue?
> > 
> > 
> > It might work, but does add a lot of overhead to pipelines to include that snipped, rather than have it by default included in the image (like it was with windows-2019)?
> 
> We need to be sure that this fix the issue, maybe we will add some more components.

I tested and it works, but ... It adds another 5 minutes to the execution time, which is not something I would consider as acceptable.

**Comment by al-cheb** [comment]
@Styxxy, I have create a https://github.com/actions/virtual-environments/pull/4874 PR to add Net.Component.4.7.TargetingPack component.  The new image will be deployed next week.

**Comment by Styxxy** [comment]
> @Styxxy, I have create a #4874 PR to add Net.Component.4.7.TargetingPack component. The new image will be deployed next week.

Great, thanks!

**Comment by al-cheb** [comment]
@Styxxy, the image with `Microsoft.Net.Component.4.7.TargetingPack` on board has been deployed.
https://github.com/actions/virtual-environments/blob/main/images/win/Windows2022-Readme.md

**Comment by miketimofeev** [comment]
@jcansdale the minimal targeting pack for VS2022 is 
`Microsoft.Net.Component.4.5.2.TargetingPack
`
https://docs.microsoft.com/en-us/visualstudio/install/workload-component-id-vs-enterprise?view=vs-2022

**Comment by jcansdale** [comment]
Interesting. Thanks for taking a look!
