### ISSUE TITLE
DNS name resolution failure

### ISSUE THREAD

**Issue by NiKiZe** [actions/virtual-environments#4863]
### Description

Trying to check DNS records fails if the DNS server is IPv6 only.
Even if the host it self does not have IPv6, the recursive DNS server that a client uses should have IPv6.

Fixing #668 would probably resolve this as well.
If not then the local DNS service should use a recursive DNS that works as expected.

### Virtual environments affected

- [ ] Ubuntu 18.04
- [X] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

`Current runner version: '2.285.1`
https://github.com/ip-update/gh-actions-v6-broken/runs/4785668521?check_suite_focus=true

### Expected behavior

Even if host does not have IPv6, recursive DNS should have v6 support

```
$ dig ns dnslabs.nl

;; ANSWER SECTION:
dnslabs.nl.             600     IN      NS      ns6.forfun.net.
dnslabs.nl.             600     IN      NS      xs.forfun.net.

;; ADDITIONAL SECTION:
xs.forfun.net.          6766    IN      AAAA    2001:980:5270:1:83:163:210:97
ns6.forfun.net.         6766    IN      AAAA    2600:3c03::f03c:91ff:fedf:1e98
```

### Actual behavior

```
;; ANSWER SECTION:
dnslabs.nl.		1800	IN	NS	xs.forfun.net.
dnslabs.nl.		1800	IN	NS	ns6.forfun.net.
```

no DNS response
`dns.resolver.NoNameservers: All nameservers failed to answer the query dnslabs.nl. IN SOA: Server 127.0.0.53 UDP port 53 answered SERVFAIL`

### Repro steps

Try to lookup a DNS record where the DNS is hosted on IPv6 only.
`dig soa dnslabs.nl`

**Comment by al-cheb** [comment]
Hey, @NiKiZe 
We will take a look at it.

**Comment by nikolai-frolov** [comment]
@alepauly looks like  ipv6 isn't configured on the environment side [due to infrastructure constraints](https://github.com/actions/virtual-environments/issues/668#issuecomment-624080758). Is it still actual?

**Comment by alepauly** [comment]
> @alepauly looks like ipv6 isn't configured on the environment side [due to infrastructure constraints](https://github.com/actions/virtual-environments/issues/668#issuecomment-624080758). Is it still actual?

apologies for my delayed response. Unfortunately, that is still the case and we don't have plans in our roadmap to change it right now.

**Comment by NiKiZe** [comment]
@alepauly So your official stance is that IPv6 will not be supported on github actions? And even worse, you don't care about DNS being broken in your environment?

Even if you don't have a plan for IPv6, you need to fix so that DNS is working properly.

**Comment by NiKiZe** [comment]
We had a workaround using external NS, which is no longer working.
Is this an intentional change, if so why?, and if not should I open a different issue?

**Comment by NiKiZe** [comment]
We had a workaround using external NS, which is no longer working.
Is this an intentional change, if so why?
If not should I open a different issue?

https://github.com/ip-update/gh-actions-v6-broken/runs/4902023026?check_suite_focus=true

**Comment by Misshunter1** [comment]
I am releasing the info

**Comment by manish2307github** [comment]
Hello Team,

In my github actions pipeline i am trying to run the integration test cases written in java.
Those test cases are calling api's from micro service in Azure cloud which is failing with hostname resolve issue.
javax.ws.rs.ProcessingException: RESTEASY004655: Unable to invoke request: java.net.UnknownHostException: XXX-AAA-service-TTT.RRR.api.AAA: Name or service not known

any idea how to resolve this
