### ISSUE TITLE
Update/Add [Microsoft.VisualStudio.Component.VC.Modules.x86.x64]

### ISSUE THREAD

**Issue by Pyzyryab** [actions/virtual-environments#4870]
### Tool name

Microsoft.VisualStudio.Component.VC.Modules.x86.x64

### Tool license

-

### Add or update?

- [X] Add
- [ ] Update

### Desired version

latest

### Brief description of tool

I would like to know if it's possible to add to VS 2022 the support for C++20 modules as a new component of the installation of the VS suite in the `windows-2022` machine.

The tool's name is: `Microsoft.VisualStudio.Component.VC.Modules.x86.x64`

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [X] Windows Server 2022

**Comment by miketimofeev** [comment]
@Pyzyryab Hi!
We have no objections regarding adding the component.

**Comment by Pyzyryab** [comment]
@miketimofeev Nice. When would I expect to be ready the implementation?

Thanks for your attention, guys.

**Comment by miketimofeev** [comment]
@Pyzyryab we are going to take care of it this week and the new image will be deployed next week.

**Comment by Pyzyryab** [comment]
@ that's fantastic to hear. Thanks for the support.

**Comment by nikolai-frolov** [comment]
Windows images have been successfully deployed.
