### ISSUE TITLE
Update Node

### ISSUE THREAD

**Issue by asklar** [actions/virtual-environments#4876]
### Tool name

NodeJS

### Tool license

MIT

### Add or update?

- [ ] Add
- [X] Update

### Desired version

16.3.2

### Provide a basic test case to validate the tool's functionality.

Node pushed some security updates: https://nodejs.org/en/blog/vulnerability/jan-2022-security-releases/

Please update the version of node used in GHA to the patched versions

### Virtual environments affected

- [X] Ubuntu 18.04
- [X] Ubuntu 20.04
- [X] macOS 10.15
- [X] macOS 11
- [X] Windows Server 2016
- [X] Windows Server 2019
- [X] Windows Server 2022

**Comment by al-cheb** [comment]
Hey, @asklar 
The new image rollout has been starting with Node 16.3.2 on board. It will have been finished on Monday.

**Comment by freddy123098** [comment]
So can we be done with the image today or something, @al-cheb

**Comment by freddy123098** [comment]
So I can help you on this.

**Comment by freddy123098** [comment]
As soon as possible.

**Comment by MaksimZhukov** [comment]
All images with Node.js 16.3.2 have been deployed
