### ISSUE TITLE
Add Microsoft OLE DB Driver for SQL Server

### ISSUE THREAD

**Issue by JasonTracey1** [actions/virtual-environments#4881]
### Tool name

Microsoft OLE DB Driver for SQL Server (MSOLEDBSQL)

### Tool license

Microsoft Software License

### Add or update?

- [X] Add
- [ ] Update

### Desired version

18.6.3 (latest)

### Approximate size

7104KB

### Brief description of tool

The OLE DB Driver for SQL Server is a stand-alone data access application programming interface (API), used for OLE DB, that was introduced in SQL Server 2005 (9.x). OLE DB Driver for SQL Server delivers the SQL OLE DB driver in one dynamic-link library (DLL). It also provides new functionality above and beyond that supplied by the Windows Data Access Components (Windows DAC, formerly Microsoft Data Access Components, or MDAC). The OLE DB Driver for SQL Server can be used to create new applications or enhance existing applications that need to take advantage of features introduced in SQL Server 2005 (9.x), such as multiple active result sets (MARS), user-defined data types (UDT), query notifications, snapshot isolation, and XML data type support.

This replaces the previously included SQL NCLI driver packaged with windows-2016. Without either of these drivers, linked servers are broken in Azure Hosted ADO Pipelines.

### URL for tool's homepage

https://docs.microsoft.com/en-us/sql/connect/oledb/oledb-driver-for-sql-server

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [X] Windows Server 2019
- [X] Windows Server 2022

### Can this tool be installed during the build?

```bash
Download from https://docs.microsoft.com/en-us/sql/connect/oledb/oledb-driver-for-sql-server

msiexec /i msoledbsql.msi ADDLOCAL=ALL IACCEPTMSOLEDBSQLLICENSETERMS=YES /qn
(needs admin rights)
```

### Tool installation time in runtime

less than a minute

### Are you willing to submit a PR?

Yes but would need some help to.

**Comment by al-cheb** [comment]
Hey, @JasonTracey1 
Does that work for you if you install OLE DB driver in runtime on Windows Server 2019/2022? Which version X86 vs X64 do you want to install?

**Comment by miketimofeev** [comment]
> Hey, @JasonTracey1 Does that work for you if you install OLE DB driver in runtime on Windows Server 2019/2022? Which version X86 vs X64 do you want to install?

@JasonTracey1 could you please clarify?

**Comment by JasonTracey1** [comment]
Hi @miketimofeev it works if a copy of the .msi is included:

```
- script: |
    curl.exe -s -L "https://go.microsoft.com/fwlink/?linkid=2183083" -o "msoledbsql.msi"
    msiexec /i msoledbsql.msi ADDLOCAL=ALL IACCEPTMSOLEDBSQLLICENSETERMS=YES /qn
```

**Comment by miketimofeev** [comment]
@JasonTracey1 provided link is for the x64 version. We will add it then, thanks.

**Comment by shilovmaksim** [comment]
Hi @JasonTracey1 . MS SQL OLEDB driver added to windows 19 and 22 images. Changes will be deployed next week.

**Comment by JasonTracey1** [comment]
Thanks all!

**Comment by shilovmaksim** [comment]
Hi @JasonTracey1 .
Changes with MS SQL OLEDB driver installation has been deployed and now available on [windows19](https://github.com/actions/virtual-environments/blob/main/images/win/Windows2019-Readme.md#database-tools)

**Comment by shilovmaksim** [comment]
Hi @JasonTracey1 .
Changes with MS SQL OLEDB driver were also deployed on [windows22](https://github.com/actions/virtual-environments/blob/main/images/win/Windows2022-Readme.md#database-tools).
Thank you for your request.
