### ISSUE TITLE
I found that most of the actions are enqueued but not executed

### ISSUE THREAD

**Issue by totalo** [actions/virtual-environments#4883]
### Description

```
Found online and idle hosted runner in the current repository's organization account that matches the required labels: 'ubuntu-latest'
Waiting for a Hosted runner in the 'organization' to pick this job...
Job was not picked up by the preferred runner, try requesting additional runners to run this job
Waiting for a self-hosted runner to pickup this job...
```

### Virtual environments affected

- [X] Ubuntu 18.04
- [X] Ubuntu 20.04
- [X] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

https://github.com/apache/shardingsphere/runs/4813120878?check_suite_focus=true

### Repro steps

N/A

**Comment by al-cheb** [comment]
Hey @totalo,
We will take a look at it.

**Comment by totalo** [comment]
> Hey @totalo, We will take a look at it.

Thank you so much.

**Comment by shilovmaksim** [comment]
Hi @totalo . Are you using GitHub hosted or self hosted runners?
I see that workflow run you've mentioned in the description already started.

**Comment by al-cheb** [comment]
@totalo , You have exceeded parallel running job limits(the current limit is 300).

**Comment by totalo** [comment]
> @totalo , You have exceeded parallel running job limits(the current limit is 300).

ok~ thank you.

**Comment by totalo** [comment]
> Hi @totalo . Are you using GitHub hosted or self hosted runners? I see that workflow run you've mentioned in the description already started.

GitHub hosted.

**Comment by totalo** [comment]
> Hi @totalo . Are you using GitHub hosted or self hosted runners? I see that workflow run you've mentioned in the description already started.

thank you.
