### ISSUE TITLE
Windows server 2022 .Net 6.0.101 SDK not found

### ISSUE THREAD

**Issue by Herostwist** [actions/virtual-environments#4884]
### Description

Windows server 2022 claims to have .Net 6.0.101 SDK installed, but when a pipeline tries to use it, it isnt found and needs to be downloaded each time, even when performMultiLevelLookup is true.

### Here is the agent details:

Starting: Initialize job
Agent name: 'Hosted Agent'
Agent machine name: 'WIN-356CQ3OAI9R'
Current agent version: '2.196.2'
Operating System
Virtual Environment
Virtual Environment Provisioner
Current image version: '20211219.1'

### Here is the result of use .net

Starting: UseDotNet
Tool to install: .NET Core sdk version 6.0.x.
Found version 6.0.101 in channel 6.0 for user specified version spec: 6.0.x
Version 6.0.101 was not found in cache.
Getting URL to download .NET Core sdk version: 6.0.101.
Detecting OS platform to find correct download package for the OS.
C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -NoLogo -Sta -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command "& 'D:\a\_tasks\UseDotNet_b0ce7256-7898-45d3-9cb5-176b752bfea6\2.195.1\externals\get-os-platform.ps1'"
Primary:win-x64
Detected platform (Primary): win-x64
Downloading: https://download.visualstudio.microsoft.com/download/pr/8e55ce37-9740-41b7-a758-f731043060da/4b8bfd4aad9d322bf501ca9e473e35c5/dotnet-sdk-6.0.101-win-x64.zip
Extracting downloaded package D:\a\_temp\fca8152b-55ed-4971-92e4-2d27c13eaf85.
Extracting archive
C:\Windows\system32\chcp.com 65001
Active code page: 65001
C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -NoLogo -Sta -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command "$ErrorActionPreference = 'Stop' ; try { Add-Type -AssemblyName System.IO.Compression.FileSystem } catch { } ; [System.IO.Compression.ZipFile]::ExtractToDirectory('D:\a\_temp\fca8152b-55ed-4971-92e4-2d27c13eaf85', 'D:\a\_temp\a86a')"
Successfully installed .NET Core sdk version 6.0.101.
Creating global tool path and pre-pending to PATH.
Finishing: UseDotNet

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

20211219.1

### Expected behavior

.Net 6.0.101 SDK ti be found in local cache

### Actual behavior

.Net 6.0.101 SDK required downloading and installing

### Repro steps

pool:
  vmImage: 'windows-2022'

steps:
- task: UseDotNet@2
  inputs:
    version: '6.0.x'
    includePreviewVersions: false
    performMultiLevelLookup: true

**Comment by al-cheb** [comment]
Hey @Herostwist,
You should create an issue in https://github.com/microsoft/azure-pipelines-tasks repo who manages `UseDotNet@2` task, because nothing we can do from our side.

I have checked the code - https://github.com/microsoft/azure-pipelines-tasks/blob/6016379acef680cf8535b6f931f5f7a3f68b1604/Tasks/UseDotNetV2/versioninstaller.ts#L102

```
isInstalled = tl.exist(path.join(this.installationPath, utils.Constants.relativeSdkPath, version)) && tl.exist(path.join(this.installationPath, utils.Constants.relativeSdkPath, `${version}.complete`)); 
```

As ugly hack:
```
steps:
- powershell: 'Get-ChildItem "C:\Program Files\dotnet\sdk" -Directory | Foreach {New-Item -Type File -Path "$($_.FullName).complete"}'
  displayName: 'Create complete files'
- task: UseDotNet@2
  displayName: 'Use .NET Core sdk 6.0.101'
  inputs:
    version: 6.0.x
    installationPath: 'C:\Program Files\dotnet'
```

![image](https://user-images.githubusercontent.com/47745270/149507337-36327429-2762-433f-ab84-4b146ed9a6d0.png)

**Comment by Herostwist** [comment]
thank @al-cheb will do.
