### ISSUE TITLE
Crash: /lib/x86_64-linux-gnu/libstdc++.so.6: cannot allocate memory in static TLS block

### ISSUE THREAD

**Issue by kpj** [actions/virtual-environments#4894]
### Description

When running automated tests on `ubuntu-20.04, 20211219.1` involving R and the [sf package](https://r-spatial.github.io/sf/), the following error occurs:
```bash
Error in dyn.load(file, DLLpath = DLLpath, ...) : 
  unable to load shared object '/home/runner/work/_temp/Library/sf/libs/sf.so':
  /lib/x86_64-linux-gnu/libstdc++.so.6: cannot allocate memory in static TLS block
```
See https://github.com/kpj/rwrap/runs/4752576801 for a failing example.
This setup used to work before (see, e.g., https://github.com/kpj/rwrap/runs/3815967740).

I saw https://github.com/actions/virtual-environments/issues/4733 and https://github.com/actions/virtual-environments/issues/4799.
Is `export LD_PRELOAD=/lib/x86_64-linux-gnu/libstdc++.so.6:$LD_PRELOAD` still the recommended workaround?

### Virtual environments affected

- [ ] Ubuntu 18.04
- [X] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Public example: https://github.com/kpj/rwrap/runs/4752576801

Image information:
```bash
Current runner version: '2.285.1'
Operating System
  Ubuntu
  20.04.3
  LTS
Virtual Environment
  Environment: ubuntu-20.04
  Version: 20211219.1
  Included Software: https://github.com/actions/virtual-environments/blob/ubuntu20/20211219.1/images/linux/Ubuntu2004-README.md
  Image Release: https://github.com/actions/virtual-environments/releases/tag/ubuntu20%2F20211219.1
Virtual Environment Provisioner
  1.0.0.0-main-20211214-1
```

### Is it regression?

https://github.com/kpj/rwrap/runs/3815967740, "Error: We are currently unable to download the log. Please try again later."

### Expected behavior

The tests should successfully pass.

### Actual behavior

The tests crash with the aforementioned error.

### Repro steps

See https://github.com/kpj/rwrap/runs/4752576801

**Comment by nikolai-frolov** [comment]
Hello @kpj, we'll take care about this issue investigation and reply with findings.

**Comment by miketimofeev** [comment]
@kpj Hi!
This is a known issue. Please take a look at the announcement.
https://github.com/actions/virtual-environments/issues/4799

**Comment by kpj** [comment]
Thanks a lot!

I fixed the issue by adding the following step to my GA workflow:
```yaml
- name: GA fixes
   run: |
     sudo apt-get update
     sudo apt-get remove mysql* && sudo apt-get install -y mysql-server
```
