### ISSUE TITLE
404 error when clicking on rollout status badge

### ISSUE THREAD

**Issue by lupine86** [actions/virtual-environments#4897]
### Description

When I click on the status badges for latest release I'm getting a 404

![image](https://user-images.githubusercontent.com/11162250/149988161-2fca97e9-0ca2-486b-89a2-c49da412826a.png)

It is redirecting to: https://github.com/actions/virtual-environments/blob/releases/ubuntu20/20220116/images/linux/Ubuntu2004-README.md

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

N/A

### Repro steps

Navigate to https://github.com/actions/virtual-environments
click on the status badge

**Comment by miketimofeev** [comment]
Hey @lupine86!
The Ubuntu readme has changed its name from README to Readme.
I'm going to change the azure function to fix this.

**Comment by miketimofeev** [comment]
Fixed!

**Comment by Avasam** [comment]
@miketimofeev  This issue is back

**Comment by miketimofeev** [comment]
@Avasam should be fixed now, sorry for the inconvenience.
