### ISSUE TITLE
Add [geoip-database]

### ISSUE THREAD

**Issue by kostya-ten** [actions/virtual-environments#49]
**Tool information**
- Tool name: geoip-database
- Add or update? Add
- Desired version:latest
- Approximate size: 
- If this is an add request:
  - Brief description of tool: IP Address databases
  - URL for tool's homepage: https://www.maxmind.com/en/geoip2-databases

**Virtual environments affected**
- [ ] macOS 10.14
- [x] Ubuntu 16.04 LTS
- [x] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Can this tool be installed during the build?**
No

**Are you willing to submit a PR?**
Yes

**Comment by oldskool** [comment]
This would be problematic as their [EULA](https://www.maxmind.com/en/end-user-license-agreement) forbids offering the service/database to third parties other than yourself.

> providing Geolocation Functionality to applications or online platforms if users other than Licensee can access or use the Geolocation Functionality for their own purposes or benefit

**Comment by kaylangan** [comment]
@kostya-ten thanks for the suggestion!

It looks like @oldskool is correct. As per the EULA, we won't be able to install this without a commercial license. We do not intend to secure a commercial license at this time.

**Comment by kostya-ten** [comment]
Free version https://dev.maxmind.com/geoip/geoip2/geolite2/ !!!!

`apt-get install geoip-database geoipupdate`

**Comment by jakejarvis** [comment]
@kostya-ten you have sudo permissions on runners so you should be able to do this yourself if you'd like :)

```yaml
- name: Install GeoIP2
  run: |
    sudo apt-get update
    sudo apt-get install -y --no-install-recommends geoip-database geoipupdate
```
