### ISSUE TITLE
Getting operation not permitted when tests from workflow attempt to modify or remove a file

### ISSUE THREAD

**Issue by derberg** [actions/virtual-environments#4902]
### Description

We have a test that modifies a file and test that removes a file. It is related to our CLI and it's context file.
Our test fails (randomly, but more often fails that is successful) with `EPERM: operation not permitted, open 'D:\a\cli\cli\test.asyncapi'`

For example [this](https://github.com/asyncapi/cli/pull/135) PR fails [here](https://github.com/asyncapi/cli/runs/4864670498?check_suite_focus=true) even though it is not really adding the failing tests, they are already there. Interesting is that this doesn't happen with other PRs.

We tried to modify CLI to have custom context file location, so it is not on `C` drive but where the workflow runs, but this didn't solve the problem.

Any ideas?

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [X] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

```
  Environment: windows-2019
  Version: 20220116.1
  Included Software: https://github.com/actions/virtual-environments/blob/win19/20220116.1/images/win/Windows2019-Readme.md
  Image Release: https://github.com/actions/virtual-environments/releases/tag/win19%2F20220116.1
```

Build: https://github.com/asyncapi/cli/runs/4864670498?check_suite_focus=true

### Is it regression?

yes

### Expected behavior

it should pass test

### Actual behavior

provided ☝🏼 in description

### Repro steps

Random so not reproducable. We have no idea why it is happening exactly in this PR randomly, issue with tests that were not modified

**Comment by nikolai-frolov** [comment]
Hello @derberg. We'll take care about this issue investigation and reply with findings.

**Comment by nikolai-frolov** [comment]
Hi @derberg, as far as I can see, test.asyncapi file is created by [fs.writeFileSync()](https://nodejs.org/api/fs.html#fswritefilesyncfile-data-options) and [options.flag is `w` by default](https://github.com/aayushmau5/cli/blob/9d2351622d5814f6127890ef517cada0f7272b3d/test/testHelper.ts#L29). According to [File system flags](https://nodejs.org/api/fs.html#file-system-flags) documentation:
`On Windows, opening an existing hidden file using the 'w' flag (either through fs.open() or fs.writeFile() or fsPromises.open()) will fail with EPERM. Existing hidden files can be opened for writing with the 'r+' flag.`
I'm going to close this issue since it's not related to image generation. Please let us know if you have any objections.

**Comment by derberg** [comment]
@nikolai-frolov we will test it out, but it will be super strange if that works. Tests fail randomly, and only on one PR 🤔

**Comment by derberg** [comment]
@nikolai-frolov please have a look at below discussion from linked PR

![Screenshot 2022-01-24 at 11 34 28](https://user-images.githubusercontent.com/6995927/150767302-23f00978-07a2-4f36-a5e2-5f3c33a7b686.png)

**Comment by nikolai-frolov** [comment]
@derberg could you please test `w+` flag instead and/or async version of function? As I can see from error stack, file was created but can't be opened, so as an additional debugging I would suggest check if file actually exists and it's access attributes.

**Comment by nikolai-frolov** [comment]
@derberg as far as I can see, [the issue root](https://github.com/asyncapi/cli/pull/135#issuecomment-1025881159) was found in the project code, so I'm going to close this issue. Feel free to reach us in case of any issues.

**Comment by derberg** [comment]
@nikolai-frolov yes, sorry for bothering you 😞 🙏🏼 and thanks a lot for taking time to investigate it with us 🙇🏼
