### ISSUE TITLE
Ubuntu-latest suddenly chaned java 11 to 1.8 by default 

### ISSUE THREAD

**Issue by rymsha** [actions/virtual-environments#4911]
### Description

In Ubuntu 20220116.1 java 8 is default 
In 20220111.1 java 11 was default 

Without announcement java default version was changed. IMO default java version at least should not be downgraded 

### Virtual environments affected

- [ ] Ubuntu 18.04
- [X] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

https://github.com/enonic/xp/actions/runs/1718045021

### Is it regression?

20220111.1 https://github.com/enonic/xp/runs/4853307557

### Expected behavior

Java 11 is default 

### Actual behavior

Java 1.8 is default 

### Repro steps

1. run: java -version

**Comment by miketimofeev** [comment]
@rymsha sorry for the inconvenience, we have rolled back the image.

**Comment by nikolai-frolov** [comment]
Hi, [Ubuntu 20.04](https://github.com/nikolai-frolov/image-testing/runs/4878272460?check_suite_focus=true) has a correct default Java version `11.*`, but [Ubuntu 18.04](https://github.com/nikolai-frolov/image-testing/runs/4878272431?check_suite_focus=true) returns incorrect version `1.8.0_292`. We'll take a look at this.
