### ISSUE TITLE
Add OpenVPN

### ISSUE THREAD

**Issue by ynouri** [actions/virtual-environments#4912]
### Tool name

OpenVPN

### Tool license

GPL v2

### Add or update?

- [X] Add
- [ ] Update

### Desired version

latest

### Approximate size

~2MB

### Brief description of tool

Open Source VPN Client.

### URL for tool's homepage

https://github.com/OpenVPN/openvpn

### Provide a basic test case to validate the tool's functionality.

Connect to a private network (e.g. within an AWS account) through a VPN endpoint and access the resources within that network in the following GH Actions steps of the job.

### Virtual environments affected

- [X] Ubuntu 18.04
- [X] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Can this tool be installed during the build?

```bash
Yes

      - name: Install Open VPN
        run: sudo apt-get install openvpn
```

### Tool installation time in runtime

~10-20s

### Are you willing to submit a PR?

Yes

**Comment by nikolai-frolov** [comment]
Hi, for the [similar issue](https://github.com/actions/virtual-environments/issues/124#issuecomment-602834711) it was decided that this would be better developed as an `setup-*` action

**Comment by miketimofeev** [comment]
@ynouri we wouldn't like to add openvpn to the images due to maintenance concerns and relatively fast installation time in runtime.
Feel free to contact us if you have any concerns.
Thank you!
