### ISSUE TITLE
Add xcbeautify to macOS & Ubuntu to format build logs when building Swift packages or macOS/iOS apps

### ISSUE THREAD

**Issue by nekrich** [actions/virtual-environments#4918]
### Tool name

xcbeautify

### Tool license

[MIT](https://github.com/tuist/xcbeautify/blob/main/LICENSE)

### Add or update?

- [X] Add
- [ ] Update

### Desired version

0.11.0

### Approximate size

1.4 MB

### Brief description of tool

In the [upcoming 2.201.0 release](https://github.com/fastlane/fastlane/pull/19629) fastlane tools will be able to support [xcbeautify](https://github.com/tuist/xcbeautify) as a formatter for `xcodebuild` output.

Now Azure utilizes `xcpretty`, but it's old, not supported for a long time, and has a lot of issues. `xcbeautify` on the contrary is supported and become more popular across developers.

I think it will be a good addition to the pre-installed tools on macOS & Ubuntu platforms.

### URL for tool's homepage

https://github.com/tuist/xcbeautify

### Provide a basic test case to validate the tool's functionality.

```bash
xcodebuild -workspace Some.xcworkspace  -scheme SomeScheme -destination 'generic/platform=macOS' archive | xcbeautify
```

### Virtual environments affected

- [X] Ubuntu 18.04
- [X] Ubuntu 20.04
- [X] macOS 10.15
- [X] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Can this tool be installed during the build?

```bash
brew cask install thii/swift-runtime/swift-runtime
brew install xcbeautify

or

mint install tuist/xcbeautify
```

### Tool installation time in runtime

3s if you have good internet and updated homebrew repo. But update homebrew is a long process

### Are you willing to submit a PR?

No. I don't think I can make a correct PR 😅

**Comment by nikolai-frolov** [comment]
Hi @nekrich,
this tool can be installed in runtime via `brew install xcbeautify` in less than a minute. Considering this fact, we wouldn't like to pre-install it on the image. We are trying not add tools that are easily installed in runtime due to maintenance reasons.

I'm going to close this issue. Please, feel free to open a new one in case of any questions.
Thanks.
