### ISSUE TITLE
windows-2019 environment ships with NuGet v5.8.0.6930 (not v6.0.0.280 as documented)

### ISSUE THREAD

**Issue by xpouyat** [actions/virtual-environments#4920]
### Description

I found that NuGet v5.8.0.6930 is shipped in windows-2019 environment. It's not v6.0.0.280 as documented in
https://github.com/actions/virtual-environments/blob/main/images/win/Windows2019-Readme.md
![2022-01-20_14h15_11](https://user-images.githubusercontent.com/8104205/150346773-5d9cf19e-fbe5-4a29-b8fb-c1119bcc962e.png)

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [X] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Version: 20220116.1

### Expected behavior

NuGet v6.0.0.280 to be shipped.

### Repro steps

Use Azure devops with windows-2019.
You can see the NuGet version when executing a task like :

- task: NuGetCommand@2
  inputs:
    restoreSolution: '**\AMSExplorer\AMSExplorer.csproj'

**Comment by nikolai-frolov** [comment]
Hello @xpouyat. Thanks for the issue reporting. We'll take care about this issue investigation and reply with findings.

**Comment by nikolai-frolov** [comment]
@xpouyat as far as I can see, `20220116.1` image version has a correct NuGet version on [all environments](https://github.com/nikolai-frolov/image-testing/runs/4882828042?check_suite_focus=true)
![image](https://user-images.githubusercontent.com/90333448/150351098-7a4184bf-43e2-4c98-bc1e-2ecb43cda25d.png)
Could you please try to run `(nuget help) -match "NuGet Version"` under PowerShell task on Azure DevOps? If issue still occurs please share your build link for investigation.

**Comment by xpouyat** [comment]
Ok, I got this
![2022-01-20_15h08_57](https://user-images.githubusercontent.com/8104205/150354379-83bbb388-6923-4090-be47-7690754d6891.png)
