### ISSUE TITLE
Add built images on docker hub

### ISSUE THREAD

**Issue by y-nk** [actions/virtual-environments#4929]
### Description

For people interested into debugging issues related to the runners, it'd be pretty convenient to be able to run them without having to build the images. For example, I've pulled the `ubuntu:20.04` image but the softwares added by these images are not installed, so the repro is quite difficult.

Related: https://github.com/semantic-release/semantic-release/issues/2340

### Virtual environments affected

- [X] Ubuntu 18.04
- [X] Ubuntu 20.04
- [X] macOS 10.15
- [X] macOS 11
- [X] Windows Server 2016
- [X] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

-

### Repro steps

docker pull ubuntu:20.04

**Comment by nikolai-frolov** [comment]
Hi, @y-nk, we don't provide any images but to build a VM machine from this repo's source you can see [the instructions](https://github.com/actions/virtual-environments/blob/main/docs/create-image-and-azure-resources.md).

**Comment by al-cheb** [comment]
Duplicate: https://github.com/actions/virtual-environments/issues/666

**Comment by y-nk** [comment]
@nikolai-frolov yes i have read the README and the instructions and it is clear that there's no image distributed, which is why i opened this ticket : i think it should be highly useful to help debugging if we could run the images locally.

@al-cheb thank you and sorry for creating a duplicate.
