### ISSUE TITLE
Update Chocolatey

### ISSUE THREAD

**Issue by Tyler887** [actions/virtual-environments#4937]
### Tool name

Chocolatey

### Tool license

SPDX identifier `Apache-2.0`

### Add or update?

- [ ] Add
- [X] Update

### Desired version

0.12.0

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [X] Windows Server 2019
- [X] Windows Server 2022

**Comment by mikhailkoliada** [comment]
Hi @Tyler887, the newer version will be fetched in this week, as we are installing the latest choco version.

**Comment by mikhailkoliada** [comment]
Done

**Comment by Tyler887** [comment]
Ready to remove `awaiting-deploymemt` tag @mikhailkoliada ;)
