### ISSUE TITLE
`Finalize-VM.ps1` removes required directory `$env:SystemRoot\Temp` 

### ISSUE THREAD

**Issue by HofmeisterAn** [actions/virtual-environments#4944]
### Description

I've noticed the following error messages while building the `windows2019` image:

```
Clean up various directories
    vhd: Removing C:\Recovery
    vhd: Removing C:\Windows\logs
    vhd: Removing C:\Windows\winsxs\manifestcache
    vhd: Removing C:\Windows\Temp
    vhd: Removing C:\Users\packer\AppData\Local\Temp
    vhd: Finalize-VM.ps1 - completed
==> vhd: . : The term 'c:/Windows/Temp/packer-ps-env-vars-61ea9b1c-521e-256d-aac7-b07dd321060d.ps1' is not recognized as the
==> vhd: name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was
==> vhd: included, verify that the path is correct and try again.
==> vhd: At line:1 char:138
==> vhd: + ... ontinue'};. c:/Windows/Temp/packer-ps-env-vars-61ea9b1c-521e-256d-aac ...
==> vhd: +                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
==> vhd:     + CategoryInfo          : ObjectNotFound: (c:/Windows/Temp...07dd321060d.ps1:String) [], CommandNotFoundException
==> vhd:     + FullyQualifiedErrorId : CommandNotFoundException
```

I can't explain the error (the log message order does not fit), however, it looks like line 37 of the `Finalize-VM.ps1`  script is wrong. The directory `$env:SystemRoot\Temp` gets removed a couple of lines above at line 21.

https://github.com/actions/virtual-environments/blob/05fc7efd600bc4b6832e123637e87187ef01f4e0/images/win/scripts/Installers/Finalize-VM.ps1#L37

If I remove line 14, the error is gone. `Out-Null` will not suppress `Write-Error`. I guess your pipeline can not remove the directory, that's why the message does not appear. `Remove-Item` use `-ErrorAction SilentlyContinue`.

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [X] Windows Server 2016
- [X] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

\-

### Repro steps

1. Run `Finalize-VM.ps1`

**Comment by al-cheb** [comment]
Hey, @HofmeisterAn 
What commit and branch do you use? Could you check that `"skip_clean": true` is set in the packer  https://github.com/actions/virtual-environments/blob/129a56046f637d39f8835c202520cb2c5532d6b9/images/win/windows2019.json#L311 config?

**Comment by HofmeisterAn** [comment]
We're using 05fc7efd600bc4b6832e123637e87187ef01f4e0. `skip_clean` was not set. I added it and queued a new build. Sorry, it seems like I missed the parameter somehow.

**Comment by HofmeisterAn** [comment]
The error message doesn't appear anymore if [skip_clean](https://www.packer.io/docs/provisioners/shell#skip_clean) is `true`.

**Comment by al-cheb** [comment]
You should build an image against `main` branch always to have the latest updates and fixes, we don't backport any changes.
