### ISSUE TITLE
Visual Studio 2022 - Modeling SDK (DslTools not available)

### ISSUE THREAD

**Issue by davidmiguelalves** [actions/virtual-environments#4946]
### Tool name

Visual Studio 2022 - Modeling SDK

### Tool license

Visual Studio 2022 - Modeling SDK

### Add or update?

- [x] Add
- [X] Update

### Desired version

latest

### Brief description of tool

In the Visual Studio 2022 the Modeling SDK installed:

`
##[error]The nuget command failed with exit code(1) and error(D:\a\1\s\XXXX.csproj(4,11): error MSB4226: The imported project "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Microsoft\VisualStudio\v17.0\DSLTools\Microsoft.DslTools.settings.targets" was not found. Also, tried to find "Microsoft\VisualStudio\v17.0\DSLTools\Microsoft.DslTools.settings.targets" in the fallback search path(s) for $(MSBuildExtensionsPath) - "C:\Program Files (x86)\MSBuild" . These search paths are defined in "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\bin\msbuild.exe.Config". Confirm that the path in the <Import> declaration is correct, and that the file exists on disk in one of the search paths.
`

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Can this tool be installed during the build?

```bash
No
```

**Comment by miketimofeev** [comment]
Hi @davidmiguelalves!
Could you try installing the component in runtime and see if it helps? If yes we will add the component to the image
```pwsh
Set-Location "C:\Program Files (x86)\Microsoft Visual Studio\Installer\"
$InstallPath = "C:\Program Files\Microsoft Visual Studio\2022\Enterprise"
$componentsToAdd = @(
  "Microsoft.VisualStudio.Component.DslTools"
)
[string]$workloadArgs = $componentsToAdd | ForEach-Object {" --add " +  $_}
$Arguments = ('/c', "vs_installer.exe", 'modify', '--installPath', "`"$InstallPath`"",$workloadArgs, '--quiet', '--norestart', '--nocache')
$process = Start-Process -FilePath cmd.exe -ArgumentList $Arguments -Wait -PassThru -WindowStyle Hidden
if ($process.ExitCode -eq 0)
{
    Write-Host "components have been successfully added"
}
else
{
    Write-Host "components were not installed"
    exit 1
}
```

**Comment by davidmiguelalves** [comment]
Hi @miketimofeev it worked! I have notice that the component is in toolset-2019.json an not in toolset-2022.json.

Regards

**Comment by al-cheb** [comment]
The new image has been deployed with "Microsoft.VisualStudio.Component.DslTools" component on board.
