### ISSUE TITLE
Add GraalVM to MacOS

### ISSUE THREAD

**Issue by perezd** [actions/virtual-environments#4949]
### Tool name

GraalVM

### Tool license

https://github.com/oracle/graal/blob/master/LICENSE

### Add or update?

- [X] Add
- [ ] Update

### Desired version

CE 21.3.0

### Brief description of tool

This is an alternate compiler/runtime for polyglot software compilation.
It's already present in the ubuntu image and it'd be nice to have in MacOS for cross-compilation reasons:
https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-Readme.md

### URL for tool's homepage

https://github.com/oracle/graal

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [X] macOS 10.15
- [X] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Are you willing to submit a PR?

ok

**Comment by miketimofeev** [comment]
@perezd we have no objections to adding graalvm to macOS for consistency with ubuntu images. We will prepare the changes as we don't accept macOS contributions at the moment.

**Comment by perezd** [comment]
Cool, thanks!

**Comment by shilovmaksim** [comment]
Hi @perezd .
GraalVM was added to image. Changes will be deployed next week.

**Comment by shilovmaksim** [comment]
Hi @perezd  .
Changes were deployed and GraalVM is now available on [macOS10-15](https://github.com/actions/virtual-environments/blob/main/images/macos/macos-10.15-Readme.md#graalvm) and [macOS-11](https://github.com/actions/virtual-environments/blob/main/images/macos/macos-11-Readme.md#graalvm)
Thank you for your request.
