### ISSUE TITLE
"The L2TP connection attempt failed because the security layer encountered a processing error during initial negotiations with the remote computer."

### ISSUE THREAD

**Issue by aalohr-pt** [actions/virtual-environments#4957]
### Description

Many of my pipelines require resources on an external network and so I have a job to connect to a VPN. 

As of 24th January GMT, The VPN connection job has failed with error:

"Remote Access error 789 - The L2TP connection attempt failed because the security layer encountered a processing error during initial negotiations with the remote computer"

This is a similar issue that was plaguing Windows 10/11 installs recently: https://docs.microsoft.com/en-us/answers/questions/691993/can39t-connect-to-any-vpn-after-today39s-windows-u.html

I don't think i'm able to uninstall updates on the build images so I am currently blocked in any of my pipelines on Microsoft hosted agents. I have tried windows-2019 and windows-2022.

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [X] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

Starting: Initialize job
Agent name: 'Hosted Agent'
Agent machine name: 'WIN-BIQBKUFF0CU'
Current agent version: '2.196.2'
Operating System
Virtual Environment
Virtual Environment Provisioner
Current image version: '20220116.1'

### Is it regression?

yes, last success was on image '20211219.1'

### Repro steps

1. Attempt to connect to an L2TP VPN as part of a pipeline

**Comment by mikhailkoliada** [comment]
Hello @aalohr-pt!

unfortunately we can not manage camulative updates, the only way is probably using a different vpn service. I believe someone at https://github.community/ has come across this problem too, so we highly recommend asking for help there, but please feel free to reach us out again if you have questions left.
