### ISSUE TITLE
Update/Add R

### ISSUE THREAD

**Issue by paulmueller** [actions/virtual-environments#4960]
### Tool name

R

### Tool license

GPL v2

### Add or update?

- [X] Add
- [ ] Update

### Desired version

4.*

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [X] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [ ] Windows Server 2022

**Comment by mikhailkoliada** [comment]
@paulmueller hello!

We will consider the possibility of adding R into macOS images and get back to you with a decision

**Comment by shilovmaksim** [comment]
Hi @paulmueller 
PR https://github.com/actions/virtual-environments/pull/4996 that added R installation has been merged.
Changes will be deployed later this week.

**Comment by shilovmaksim** [comment]
Hi @paulmueller .
Changes were deployed and R is now available on [macOS10-15](https://github.com/actions/virtual-environments/blob/main/images/macos/macos-10.15-Readme.md#language-and-runtime) and [macOS-11](https://github.com/actions/virtual-environments/blob/main/images/macos/macos-11-Readme.md#language-and-runtime)
Thank you for your request.
