### ISSUE TITLE
Document that Postgres isn't started automatically

### ISSUE THREAD

**Issue by dunglas** [actions/virtual-environments#4964]
### Description

The readme file of Ubuntu images documents that MySQL must be started manually, but it's also the case for Postgres and it's not documented.
Fixed by #4909.

### Virtual environments affected

- [X] Ubuntu 18.04
- [X] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

All.

### Repro steps

n/a

**Comment by miketimofeev** [comment]
@dunglas thanks for the PR, we will take a look
