### ISSUE TITLE
Dacfx invoke test getting failed

### ISSUE THREAD

**Issue by prabhusirpi** [actions/virtual-environments#4965]
### Description

It looks like the test path needs to be updated for Dacfx in Tools.Tests.ps1 file. Deployment getting failed with error message: Expected path 'C:\Program Files\Microsoft SQL Server\150\DAC\bin\SqlPackage.exe' to exist, but it did not exist.

I tried to install the Dacfx manually in the windows server, it looks like the correct path for sqlpackage is "C:\Program Files\Microsoft SQL Server\160\DAC\bin\SqlPackage.exe".

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [X] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Windows 2019

### Repro steps

It looks like the test path needs to be updated for Dacfx in Tools.Tests.ps1 file. Deployment getting failed with error message: Expected path 'C:\Program Files\Microsoft SQL Server\150\DAC\bin\SqlPackage.exe' to exist, but it did not exist.

I tried to install the Dacfx manually in the windows server, it looks like the correct path for sqlpackage is "C:\Program Files\Microsoft SQL Server\160\DAC\bin\SqlPackage.exe".

**Comment by al-cheb** [comment]
Hey @prabhusirpi ,
We will take a look at it.

**Comment by prabhusirpi** [comment]
> Hey @prabhusirpi , We will take a look at it.

Thanks @al-cheb . Let me know once its corrected.

**Comment by miketimofeev** [comment]
@prabhusirpi this is now fixed, please update your fork's main branch.

**Comment by prabhusirpi** [comment]
> @prabhusirpi this is now fixed, please update your fork's main branch.

Sure and thank you
