### ISSUE TITLE
Update CocoaPods to v1.9.0 on macOS

### ISSUE THREAD

**Issue by adamhaafiz** [actions/virtual-environments#497]
**Tool information**
- Tool name: CocoaPods
- Update
- Desired version: [v1.9.0](https://github.com/CocoaPods/CocoaPods/releases/tag/1.9.0)
- Approximate size: 

**Virtual environments affected**
- [x] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Comment by miketimofeev** [comment]
Hi @adamhaafiz Cocoa Pods will be updated in the next 2 days with the new image version. 
Closing the issue, but feel free to reopen if you have any concerns.
Thank you!
