### ISSUE TITLE
Enable Java Script on Microsoft Windows Hosted Agents

### ISSUE THREAD

**Issue by mahant-desai** [actions/virtual-environments#4970]
### Description

We are running the the builds using Microsoft Hosted agents. In the pipeline I am using the task "Notify build status to Bitbucket" to update the build status to bit bucket. When we run pipeline, the task is failing to upload the status to Bitbucket. The error details is as below.

**You should enable JavaScript to work with this page. JavaScript load error. We tried to load scripts but something went wrong. Please make sure that your network settings allow you to download scripts from the following** 

Log File in attachment.

[build pipeline error.txt](https://github.com/actions/virtual-environments/files/7959291/build.pipeline.error.txt)

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [X] Windows Server 2016
- [X] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

https://dev.azure.com/RM******VOPS/Kal***%20A**/_build/results?buildId=572&view=results

### Is it regression?

No

### Expected behavior

It should update the build status to BitBucket

### Actual behavior

Getting Error

**You should enable JavaScript to work with this page. JavaScript load error. We tried to load scripts but something went wrong. Please make sure that your network settings allow you to download scripts from the following** 

### Repro steps

run the pipeline

https://dev.azure.com/RM*******PS/Ka*****%20A**/_build?definitionId=35

**Comment by dibir-magomedsaygitov** [comment]
Hello @mahant-desai. Thank you for your report. Could you please provide repro steps to help us with the investigation. The link in the description leads to an error page.

**Comment by mahant-desai** [comment]
Hi Dibir,

Sorry, please find the link here
https://dev.azure.com/RMKRDEVOPS/Kalitta%20Air/_build?definitionId=35.

With Regards,
Mahantesh desai

**Comment by miketimofeev** [comment]
@mahant-desai this is a custom task from the marketplace and I'm afraid we can't help here as we are responsible only for hosted images. Please file an issue in the task repository https://marketplace.visualstudio.com/items?itemName=SwintDC.notify-build-status-to-bitbucket
I'm going to close the issue. Feel free to contact us if you have any concerns.
Thank you!
