### ISSUE TITLE
Update/Add [tool name]

### ISSUE THREAD

**Issue by kdschlosser** [actions/virtual-environments#4972]
### Tool name

Ninja

### Tool license

Apache License, Version 2.0

### Add or update?

- [X] Add
- [ ] Update

### Desired version

latest

### Brief description of tool

It would be nice to have Ninja available for Darwin and also Linux builds. Ninja is available on the Windows builds as it is apart of the Visual Studio cmake installation. cmake is installed on both Darwin and Linux and having Ninja would make it easier to facilitate multicore compiling. 

### URL for tool's homepage

https://ninja-build.org/

### Provide a basic test case to validate the tool's functionality.

```bash
cmake -GNinja -S"/path/to/source/files"  -B"/path/to/place/cmake/files"
ninja -C"/path/to/source/files" -j 4
```

### Virtual environments affected

- [X] Ubuntu 18.04
- [X] Ubuntu 20.04
- [X] macOS 10.15
- [X] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Can this tool be installed during the build?

```bash
if homebrew is available

brew install ninja
```

### Tool installation time in runtime

don't know

### Are you willing to submit a PR?

I would if I knew how to go about it

**Comment by dibir-magomedsaygitov** [comment]
Hello @kdschlosser. Thank you for your request. We will consider adding this tool to our images. Meanwhile, could you please correct the title.

**Comment by dibir-magomedsaygitov** [comment]
Hello @kdschlosser. Due to maintenance concerns, fast and easy installation in runtime, we wouldn't like to add `ninja` to our `macOS` and `ubuntu` images. 
I'm going to close the issue, but feel free to contact us if you have any concerns.
Thank you!

**Comment by marc-hb** [comment]
> thanks for your suggestion but considering that it' easy to add Ninja to workflows on demand,...

I just asked runtime installation to be officially documented, please upvote:
- #11235 

Ever growing list of duplicates gathered at:
- https://github.com/actions/runner-images/issues/514#issuecomment-2558554588
