### ISSUE TITLE
Any way to update this version WinAppDriver 1.2.2009.02003 ? it has bugs.

### ISSUE THREAD

**Issue by sachinerandecapita** [actions/virtual-environments#4975]
### Description

Any way to update WinAppDriver version for microsoft hosted agent `WinAppDriver 1.2.2009.02003` ? 
It is not the actual released version and appears to be just prerelease. We experience bugs with this WinAppDriver version and would like to update.
Latest release is 1.2.1
https://github.com/microsoft/WinAppDriver/releases/tag/v1.2.1 ?

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [X] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

All agent images having this prerelease version installed `WinAppDriver 1.2.2009.02003`

### Expected behavior

Able to specify somewhere which winappdriver version to install.
`WinAppDriver 1.2.2009.02003` is not available anywhere on the github release https://github.com/microsoft/WinAppDriver/releases/tag/v1.2.1
so this is incorrect version of software installed.

### Actual behavior

`WinAppDriver 1.2.2009.02003` has bugs and blocking us from using pipeline. so we would like to install the correct one.

### Repro steps

NA

**Comment by dibir-magomedsaygitov** [comment]
Hello @sachinerandecapita. Thank you for your report. We will take a look.

**Comment by miketimofeev** [comment]
@sachinerandecapita we install the latest stable release https://github.com/microsoft/WinAppDriver/releases/tag/v1.2.1 as you can see from our code
https://github.com/actions/virtual-environments/blob/02547255ff32628a1584be67e1b337b2be49785d/images/win/scripts/Installers/Install-WinAppDriver.ps1#L6-L8
The version of the file installed is 1.2.2009.02003 and this is correct, we haven't changed the version for more than a year.

**Comment by miketimofeev** [comment]
@sachinerandecapita I suggest you file a bug in the https://github.com/microsoft/WinAppDriver repository as I'm afraid nothing we could do from the image generation side.
