### ISSUE TITLE
Can't build from a tag if package default location changes

### ISSUE THREAD

**Issue by davidaughey** [actions/virtual-environments#4985]
### Description

I'm trying to build win19/20220123.1 but it's failing during the test phase.

Upon closer inspection, it's failing because the install package that's placing SqlPackage.exe has changed to deploy to a different location.

In win19/20220123.1 both Tools.Test.ps1 and SoftwareReport.Tools.psm1 believe that the location is:
$env:ProgramFiles\Microsoft SQL Server\150\DAC\bin\sqlpackage.exe
C:\Program Files\Microsoft SQL Server\150\DAC\bin\sqlpackage.exe

However, on the filesystem it's being installed to:
C:\Program Files\Microsoft SQL Server\160\DAC\bin\sqlpackage.exe

Configuration Management principles require the same outputs for the same inputs.  In this case, the package inputs aren't locked and the consequence is being unable to recreate the same image with the same source inputs.

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [X] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

win19/20220123.1 

### Expected behavior

For a tag, I would expect to be able to build exactly what was built before.

### Actual behavior

Newer versions of external packages are being used for historic tags giving a different result.

### Repro steps

Build against win19/20220123.1

**Comment by miketimofeev** [comment]
@davidaughey please avoid using release branches as we merge all the fixes in the `main` branch. The issue with DACFx is already fixed there.

**Comment by davidaughey** [comment]
I'm hear what you're saying but I need to lock onto a "stable" version.  The main branch is a bit too bleeding edge and it's caught fire on me before.  What I'm doing is locking on to the current version that's in use by the hosted agents in Azure DevOps.  

Are the images available pre-built for use in Azure?  That would avoid my need to build them completely.

**Comment by miketimofeev** [comment]
@davidaughey I'm afraid not. But the release branch doesn't guarantee anything as for most of the software we install the latest available version so even when you use the same branch you will have a different set of software throughout the week

**Comment by davidaughey** [comment]
Thanks.  I'll start a discussion to explain my use case and see if anyone has any ideas.
