### ISSUE TITLE
`pacman -S mingw-w64-x86_64-icu` fails with `signature from "David Macek <...>" is unknown trust` (starting 2022-01-23)

### ISSUE THREAD

**Issue by andreasabel** [actions/virtual-environments#4987]
### Description

Concerning MSYS2 on `windows-latest`:

From inside `bash`, command
```
pacman -S mingw-w64-x86_64-icu
```
started failing 2022-01-23 with this error log, see https://github.com/agda/agda/runs/4913233976?check_suite_focus=true#step:9:1
```
Packages (6) mingw-w64-x86_64-gcc-libs-10.3.0-2  mingw-w64-x86_64-gmp-6.2.1-2  mingw-w64-x86_64-libwinpthread-git-9.0.0.6215.788f57701-1  mingw-w64-x86_64-mpc-1.2.1-1  mingw-w64-x86_64-mpfr-4.1.0-3  mingw-w64-x86_64-icu-68.2-3

Total Download Size:    23.22 MiB
Total Installed Size:  120.12 MiB

:: Proceed with installation? [Y/n] 
:: Retrieving packages...
downloading mingw-w64-x86_64-gmp-6.2.1-2-any.pkg.tar.zst...
downloading mingw-w64-x86_64-mpfr-4.1.0-3-any.pkg.tar.zst...
downloading mingw-w64-x86_64-mpc-1.2.1-1-any.pkg.tar.zst...
downloading mingw-w64-x86_64-libwinpthread-git-9.0.0.6215.788f57701-1-any.pkg.tar.zst...
downloading mingw-w64-x86_64-gcc-libs-10.3.0-2-any.pkg.tar.zst...
downloading mingw-w64-x86_64-icu-68.2-3-any.pkg.tar.zst...
checking keyring...
checking package integrity...
error: mingw-w64-x86_64-mpfr: signature from "David Macek <david.macek.0@gmail.com>" is unknown trust
:: File /var/cache/pacman/pkg/mingw-w64-x86_64-mpfr-4.1.0-3-any.pkg.tar.zst is corrupted (invalid or corrupted package (PGP signature)).
error: mingw-w64-x86_64-mpc: signature from "David Macek <david.macek.0@gmail.com>" is unknown trust
Do you want to delete it? [Y/n] 
:: File /var/cache/pacman/pkg/mingw-w64-x86_64-mpc-1.2.1-1-any.pkg.tar.zst is corrupted (invalid or corrupted package (PGP signature)).
error: failed to commit transaction (invalid or corrupted package)
Do you want to delete it? [Y/n] 
Errors occurred, no packages were upgraded.
Error: Process completed with exit code 1.
```

Until 2022-01-22 it used to work (on `windows-latest`) see https://github.com/agda/agda/runs/4911117506?check_suite_focus=true#step:9:1
```
resolving dependencies...
looking for conflicting packages...

Packages (6) mingw-w64-x86_64-gcc-libs-10.3.0-2  mingw-w64-x86_64-gmp-6.2.1-2  mingw-w64-x86_64-libwinpthread-git-9.0.0.6215.788f57701-1  mingw-w64-x86_64-mpc-1.2.1-1  mingw-w64-x86_64-mpfr-4.1.0-3  mingw-w64-x86_64-icu-68.2-3

Total Download Size:    23.22 MiB
Total Installed Size:  120.12 MiB

:: Proceed with installation? [Y/n] 
:: Retrieving packages...
downloading mingw-w64-x86_64-gmp-6.2.1-2-any.pkg.tar.zst...
downloading mingw-w64-x86_64-mpfr-4.1.0-3-any.pkg.tar.zst...
downloading mingw-w64-x86_64-mpc-1.2.1-1-any.pkg.tar.zst...
downloading mingw-w64-x86_64-libwinpthread-git-9.0.0.6215.788f57701-1-any.pkg.tar.zst...
downloading mingw-w64-x86_64-gcc-libs-10.3.0-2-any.pkg.tar.zst...
downloading mingw-w64-x86_64-icu-68.2-3-any.pkg.tar.zst...
checking keyring...
checking package integrity...
loading package files...
checking for file conflicts...
checking available disk space...
:: Processing package changes...
installing mingw-w64-x86_64-gmp...
installing mingw-w64-x86_64-mpfr...
installing mingw-w64-x86_64-mpc...
installing mingw-w64-x86_64-libwinpthread-git...
installing mingw-w64-x86_64-gcc-libs...
installing mingw-w64-x86_64-icu...
```

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [X] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

Unsuccessful run on `windows-2022`:
https://github.com/agda/agda/runs/5011411700?check_suite_focus=true#step:9:1

First unsuccessful run on `windows-latest` (= `windows-2019`):
https://github.com/agda/agda/runs/4913233976?check_suite_focus=true#step:9:1

### Is it regression?

Last successful run: https://github.com/agda/agda/runs/4911117506?check_suite_focus=true#step:9:1

### Expected behavior

Package installation via `pacman` should succeed.

### Actual behavior

Package installation via `pacman` fails.

### Repro steps

See build logs above.

I tried to apply workarounds as in https://stackoverflow.com/questions/68669920/invalid-pgp-signature-when-updating-packages-in-msys2-despite-fixes/70088371#70088371.
However, `pacman-key` does not seem to be in the `PATH` and not in the default location `C:/msys64/usr/bin`, and installing `pacman-key` itself via `pacman` is not possible as it is supposed to be pre-installed.

**Comment by dibir-magomedsaygitov** [comment]
Hello @andreasabel. Thank you for your report. We will take a look.

**Comment by mikhailkoliada** [comment]
@andreasabel Hello! 

It is definitely not a runner problem but rather a gpg problem (gpg networks tend to be fragile per se over the long period of time, so no wonders from me).

Have you tried different workarounds, like described there: https://github.com/msys2/MSYS2-packages/issues/2343?

**Comment by andreasabel** [comment]
@mikhailkoliada : Yes, I tried to workaround, but these suggestions require calls to `pacman-key`, which strangely does not seem available on the vm.

**Comment by mikhailkoliada** [comment]
@andreasabel I am unable to reproduce the issue:
<img width="731" alt="Screenshot 2022-02-02 at 11 49 37" src="https://user-images.githubusercontent.com/88318005/152121949-588295c5-19aa-418a-a9e8-3d7595e1a184.png">

I've used this minimal workflow:

```
name: msys2

on:
  [push]

jobs:
  test:
    runs-on: windows-latest
    steps:
      - name: msys2
        run: |
          $env:PATH = "C:\msys64\mingw64\bin;C:\msys64\usr\bin;$origPath;$env:PATH"
          pacman --noconfirm -Syuu
          pacman-key --refresh
          pacman --noconfirm -S mingw-w64-x86_64-icu
```

**Comment by MehdiChinoune** [comment]
Please update package database, before installing. I see that pacman is trying to install icu-68.2 while the latest is 69.1

It looks like github-actions is using an old MSYS2 installer.

**Comment by mikhailkoliada** [comment]
@andreasabel as of comments you left in the linked issues, are there matters you want to help us with yet? :)

**Comment by andreasabel** [comment]
Thanks for your excellent input!  It helped me fixing my issues.  Solutions:
- With Haskell/Cabal: https://github.com/agda/agda/blob/ff82d4ab9009d5af8bd267661b65614564f63ed6/src/github/workflows/cabal.yml#L78-L83
- With Haskell/Stack: https://github.com/agda/agda/blob/ff82d4ab9009d5af8bd267661b65614564f63ed6/src/github/workflows/stack.yml#L158-L163
