### ISSUE TITLE
windows-2022 doesn't include Embedded tools like windows-latest does

### ISSUE THREAD

**Issue by MichaelGoulding** [actions/virtual-environments#4998]
### Description

-- The C compiler identification is unknown
-- The CXX compiler identification is unknown
CMake Error at CMakeLists.txt:8 (project):
  The CMAKE_C_COMPILER:

    C:/Program Files/Microsoft Visual Studio/2022/Enterprise/Linux/gcc_arm/bin/arm-none-eabi-gcc.exe

  is not a full path to an existing compiler tool.

  Tell CMake where to find the compiler by setting either the environment
  variable "CC" or the CMake cache entry CMAKE_C_COMPILER to the full path to
  the compiler, or to the compiler name if it is in the PATH.

CMake Error at CMakeLists.txt:8 (project):
  The CMAKE_CXX_COMPILER:

    C:/Program Files/Microsoft Visual Studio/2022/Enterprise/Linux/gcc_arm/bin/arm-none-eabi-g++.exe

  is not a full path to an existing compiler tool.

  Tell CMake where to find the compiler by setting either the environment
  variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
  to the compiler, or to the compiler name if it is in the PATH.

-- Configuring incomplete, errors occurred!

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

Current image version: '20220131.1'

### Is it regression?

yes

### Repro steps

Run a build that looks for the   C:/Program Files/Microsoft Visual Studio/2022/Enterprise/Linux/gcc_arm/bin/arm-none-eabi-* files

**Comment by dibir-magomedsaygitov** [comment]
Hello @MichaelGoulding. Thank you for your report. We will take a look.

**Comment by miketimofeev** [comment]
@MichaelGoulding am I right that you need `Component.MDD.Linux.GCC.arm` component?
Could you try installing it in runtime and see if it helps?
```pwsh
Set-Location "C:\Program Files (x86)\Microsoft Visual Studio\Installer\"
$InstallPath = "C:\Program Files\Microsoft Visual Studio\2022\Enterprise"
$componentsToAdd = @(
  "Component.MDD.Linux.GCC.arm"
)
[string]$workloadArgs = $componentsToAdd | ForEach-Object {" --add " +  $_}
$Arguments = ('/c', "vs_installer.exe", 'modify', '--installPath', "`"$InstallPath`"",$workloadArgs, '--quiet', '--norestart', '--nocache')
$process = Start-Process -FilePath cmd.exe -ArgumentList $Arguments -Wait -PassThru -WindowStyle Hidden
if ($process.ExitCode -eq 0)
{
    Write-Host "components have been successfully added"
}
else
{
    Write-Host "components were not installed"
    exit 1
}
```

**Comment by al-cheb** [comment]
The new image has been deployed with "Component.MDD.Linux.GCC.arm" component on board.

**Comment by MichaelGoulding** [comment]
Thanks!
