### ISSUE TITLE
ffmpeg

### ISSUE THREAD

**Issue by sachinerandecapita** [actions/virtual-environments#4999]
### Tool name

ffmpeg

### Tool license

Opensource

### Add or update?

- [X] Add
- [ ] Update

### Desired version

Latest

### Brief description of tool

I think mac and windows agent should have ffmpeg tool, which is normally used for automating testing to record the videos.
We have to install it explicitly on pipeline. as of now macOS we use following bash task to install it.
      - bash: |
          brew install ffmpeg
        displayName: 'Install ffmpeg for Screen Recording in mac'

This consumes some time, so thought to raise this could be a part of image itself. I am requesting for mac now, but feel free to add it for windows, if you can. thanks!

### URL for tool's homepage

https://www.ffmpeg.org/

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [X] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Can this tool be installed during the build?

```bash
Task usually we run is

      - bash: |
          brew install ffmpeg
        displayName: 'Install ffmpeg for Screen Recording in IOS'
```

### Tool installation time in runtime

5 to 9 minutes based

**Comment by miketimofeev** [comment]
Hi @sachinerandecapita!
Have you tried using https://github.com/FedericoCarboni/setup-ffmpeg action? It took 5 seconds to install ffmpeg on macOS and 8 seconds to install on windows.

**Comment by sachinerandecapita** [comment]
Is this available for azure devops pipelines ? I could not find it when adding task on pipeline yaml file.

**Comment by miketimofeev** [comment]
@sachinerandecapita I'm afraid there is no task for AzDO. Could you try using pre-compiled binaries then? This is the way the action works https://github.com/FedericoCarboni/setup-ffmpeg. For example, macOS binaries are here https://evermeet.cx/ffmpeg/. Downloading, extracting, and adding to the path should take not more than 10 seconds.

**Comment by sachinerandecapita** [comment]
@miketimofeev : it solved for macOS. 13 seconds, it completed on pipeline. thanks very much.
Do you happen to know similar solution for windows agents(19/22) ?

**Comment by al-cheb** [comment]
For Windows:
```
          curl.exe -L 'https://www.gyan.dev/ffmpeg/builds/ffmpeg-release-full.7z' -o ffmpeg-release-full.7z
          7z e ./ffmpeg-release-full.7z "-oC:\Windows" "**/bin/ffmpeg.exe" "**/bin/ffprobe.exe" "**/LICENSE" "**/README.txt"
```

**Comment by sachinerandecapita** [comment]
@al-cheb Thanks for sharing about windows. I'll try some time later. 
Closing thread as my problem is solved.
