### ISSUE TITLE
Update/Add RVM

### ISSUE THREAD

**Issue by scottohara** [actions/virtual-environments#5]
**Tool information**
- Tool name: RVM
- Add or update? Add
- Desired version: latest
- Approximate size: 
- If this is an add request:
  - Brief description of tool: install/switch between Ruby versions, auto-installs & uses the ruby version as specified in a project’s `.ruby-version` file
  - URL for tool's homepage: https://rvm.io

**Virtual environments affected**
- [x] macOS 10.14
- [x] Ubuntu 16.04 LTS
- [x] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Can this tool be installed during the build?**

Yes, but not easily. See https://github.community/t5/GitHub-Actions/How-to-share-shell-profile-between-steps-or-how-to-use-nvm-rvm/td-p/33185

**Are you willing to submit a PR?**

**Comment by scottohara** [comment]
Same reasoning as per https://github.com/actions/virtual-environments/issues/4#issuecomment-537231029

**Comment by eregon** [comment]
This seems overkill just for getting the version from `.ruby-version`.
I think it's better to support reading from `.ruby-version` in setup-ruby, and I see you filed https://github.com/actions/setup-ruby/issues/31

Is there any other reason to add RVM here? Otherwise I'd suggest to close this.

**Comment by scottohara** [comment]
Happy for this to be closed in favour of `setup-ruby` support for installing the version of ruby specified in `.ruby-version`.
