### ISSUE TITLE
Update pip to 22.0.2 on macos-latest

### ISSUE THREAD

**Issue by seve** [actions/virtual-environments#5004]
### Tool name

pip

### Tool license

MIT

### Add or update?

- [ ] Add
- [X] Update

### Desired version

22.0.2

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [ ] Windows Server 2022

**Comment by seve** [comment]
https://github.com/chanzuckerberg/single-cell-infra/runs/5043992126?check_suite_focus=true#step:6:262

**Comment by dibir-magomedsaygitov** [comment]
Hello @seve. Thank you for your request. Python should be updated to 3.9.10 with the next week's image rollout. I'll post an update message when image is ready for use.

**Comment by dibir-magomedsaygitov** [comment]
Hello @seve. Thank you for your request. I'll post an update message when pip 22.0.2 is available for use. 
Meanwhile, you can run command below to upgrade it in runtime:
`pip3 install --upgrade pip==22.0.2 `

**Comment by miketimofeev** [comment]
@seve I'm going to close the issue as the python 3.9 formula still contains pip 21.* 
https://github.com/Homebrew/homebrew-core/blob/49a025a7429cc4b216b60684b08d7b94a550a96f/Formula/python%403.9.rb#L67
The new version of pip is included with python 3.10
https://github.com/Homebrew/homebrew-core/blob/49a025a7429cc4b216b60684b08d7b94a550a96f/Formula/python%403.10.rb#L53
We have no ETA on switching the default python version so please either follow @dibir-magomedsaygitov advice or consider using the [setup-python](https://github.com/actions/setup-python) action.
