### ISSUE TITLE
Update/Add Inno Setup to windows-2022 image

### ISSUE THREAD

**Issue by drakkan** [actions/virtual-environments#5006]
### Tool name

Inno Setup

### Tool license

Modified BSD

### Add or update?

- [X] Add
- [ ] Update

### Desired version

6.2.0

### URL for tool's homepage

https://jrsoftware.org/isinfo.php

### Provide a basic test case to validate the tool's functionality.

```bash
iscc.exe <path to the installer script>
```

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [X] Windows Server 2022

**Comment by drakkan** [comment]
Inno Setup was installed in windows-2019 image and it is not present in windows-2022 image. It "was removed due to its low popularity and maintenance concerns". Can you please better explain this decision? Inno Setup seems quite popular. I currently use the preinstalled version in my workflows, however I think it will also be fine if [cinst InnoSetup -y](https://github.com/git-lfs/git-lfs/blob/main/.github/workflows/release.yml#L24) will continue to work

**Comment by miketimofeev** [comment]
@drakkan given the high demand for Inno Setup we will add it to windows 2022 image back.

**Comment by drakkan** [comment]
> @drakkan given the high demand for Inno Setup we will add it to windows 2022 image back.

Great! Thank you

**Comment by miketimofeev** [comment]
@drakkan InnoSetup has been added. The new image will be deployed next week.

**Comment by al-cheb** [comment]
The new Windows Server 2022 image has been deployed with InnoSetup 6.2.0 on board - https://github.com/actions/virtual-environments/blob/main/images/win/Windows2022-Readme.md
