### ISSUE TITLE
Documentation for install software is wrong

### ISSUE THREAD

**Issue by slushysnowman** [actions/virtual-environments#5008]
### Description

Previously, on Ubuntu 20.04, helm 3.7.2 was installed.

The [readme](https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-Readme.md) still says that this is the case.

However, the version of helm actually installed is now 3.8.0 (I know because it broke some of our stuff). it seems that the script to install helm doesn't actually look for a specific version, just the latest from v3 (https://github.com/actions/virtual-environments/blob/7c1956be8a89fcecb122f8f11d893ccd5a342e8f/images/linux/scripts/installers/kubernetes-tools.sh)

The readme probably needs updating to reflect new version - I'm not sure if other images are also affected.

### Virtual environments affected

- [ ] Ubuntu 18.04
- [X] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Current image version: '20220131.1'

### Expected behavior

Documentation should be correct - it seems that the script to install helm doesn't actually look for a specific version, just the latest from v3 (https://github.com/actions/virtual-environments/blob/7c1956be8a89fcecb122f8f11d893ccd5a342e8f/images/linux/scripts/installers/kubernetes-tools.sh). Either the version in docs should be updated automatically, or helm version should be pinned.

### Actual behavior

Documentation doesn't match reality

### Repro steps

- Create an Azure DevOps pipeline using:
```
pool:
  vmImage: ubuntu-20.04
```

Directly on the agent run `helm version`

**Comment by miketimofeev** [comment]
@slushysnowman image propagation takes a few days so it looks like you hit [the new image version](https://github.com/actions/virtual-environments/pull/4993/files#diff-fbbd26652e305be8b13c83d79ad91d7105dc03f8ea64a13eeaf95b857118f5aaR33), which will be fully deployed soon. You can follow the link to the readme in the Initialize job step to check the included software 
![image](https://user-images.githubusercontent.com/48208649/152359729-cc2f768a-5510-4a20-b102-ef6aadb5a12f.png)
