### ISSUE TITLE
Visual Studio 2022 - Microsoft.VisualStudio.ComponentGroup.UWP.VC.v142 not installed

### ISSUE THREAD

**Issue by v-lomer** [actions/virtual-environments#5011]
### Description

Testing out MMS2022 with Visual Studio 2022, our UWP v142 builds fail while our Win32 v142 builds are successful.

The issue can be tracked down to Visual Studio 2022 installation is missing the component `Microsoft.VisualStudio.ComponentGroup.UWP.VC.v142`

As a work-around, we have our pipeline builds checking and installing the missing Visual Studio component. The better solution would be to have the MMS2022 Visual Studio 2022 installation include this component.

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

Environment: windows-2022
Version: 20220131.1
Included Software: https://github.com/actions/virtual-environments/blob/win22/20220131.1/images/win/Windows2022-Readme.md
Image Release: https://github.com/actions/virtual-environments/releases/tag/win22%2F20220131.1

### Expected behavior

Pipelines building for UWP v142 to build correctly with MMS 2022

### Actual behavior

C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Microsoft\VC\v170\Microsoft.CppBuild.targets(436,5): error MSB8020: The build tools for Visual Studio 2019 (Platform Toolset = 'v142') cannot be found. To build using the v142 build tools, please install Visual Studio 2019 build tools.  Alternatively, you may upgrade to the current Visual Studio tools by selecting the Project menu or right-click the solution, and then selecting "Retarget solution".

### Repro steps

Switch pipeline image from MMS2019 to MMS2022 for UWP v142 and Win32 v142 projects
Build both pipelines
Win32 v142 pipeline is successfully
UWP v142 pipeline fails with `Actual behavior` during our cmake generator step

**Comment by miketimofeev** [comment]
Hi @v-lomer!
Here is the PR https://github.com/actions/virtual-environments/pull/5012
The changes will be available next week.

**Comment by al-cheb** [comment]
The new Windows Server 2022 image has been deployed with Microsoft.VisualStudio.ComponentGroup.UWP.VC.v142 component on board - https://github.com/actions/virtual-environments/blob/main/images/win/Windows2022-Readme.md
