### ISSUE TITLE
Waiting for SSH to be available

### ISSUE THREAD

**Issue by vamshisiram** [actions/virtual-environments#5020]
### Description

We are in a healthcare setting and are very locked down, when i am trying to use the image generation script i get "waiting for SSH to be available". As i said, all traffic is blocked by default.

Can someone please let me know what are the IP Addresses i need to open up for this to work on port 22?

And are there any additional ports/ranges we need to poke in our firewall?

I am using central US as my region when running the script.

![image](https://user-images.githubusercontent.com/90816346/152554377-5ecf3559-398e-4db0-b99e-7eee7d06c94f.png)

### Virtual environments affected

- [ ] Ubuntu 18.04
- [X] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

We are in a healthcare setting and are very locked down, when i am trying to use the image generation script i get "waiting for SSH to be available". As i said, all traffic is blocked by default.

Can someone please let me know what are the IP Addresses i need to open up for this to work on port 22?

And are there any additional ports/ranges we need to poke in our firewall?

I am using central US as my region when running the script.

### Repro steps

We are in a healthcare setting and are very locked down, when i am trying to use the image generation script i get "waiting for SSH to be available". As i said, all traffic is blocked by default.

Can someone please let me know what are the IP Addresses i need to open up for this to work on port 22?

And are there any additional ports/ranges we need to poke in our firewall?

I am using central US as my region when running the script.

**Comment by shilovmaksim** [comment]
Hi @vamshisiram .
Are you using the latest version of the virtual-environments repo? Are you modifying it somehow?

As far as I understand the ip printed at the `-> IP address` line.

Unmodified code should look like following: 
```
==> azure-arm: Getting the VM's IP address ...
==> azure-arm: Waiting for SSH to become available...
==> azure-arm: Connected to SSH!
```

**Comment by miketimofeev** [comment]
@vamshisiram looks like you need to allow access from the IP of the machine where packer is installed and running.

**Comment by vamshisiram** [comment]
Thanks @miketimofeev . I figured that would be the case but is there a range for which I can request the firewall rules for?

**Comment by miketimofeev** [comment]
@vamshisiram I'm afraid I can't suggest anything as I don't know your network configuration

**Comment by miketimofeev** [comment]
@vamshisiram I believe you can create a virtual network in azure in advance and use static ips for it. Then you need to pass this network as a variable to packer. 
Or you can try to ask azure support for a range of public ips available for Azure VMs. We don't use public IP at all as our image generation agents are placed in Azure and thus we can use a private network to communicate with generated VM.

**Comment by vamshisiram** [comment]
@miketimofeev 

That is where I am headed next. Thanks for chatting it out.
