### ISSUE TITLE
Update/Add TypeScript globally

### ISSUE THREAD

**Issue by Tyler887** [actions/virtual-environments#5026]
### Tool name

TypeScript

### Tool license

Apache License, version 2.0

### Add or update?

- [X] Add
- [ ] Update

### Desired version

latest

### Brief description of tool

TypeScript is JavaScript with syntax for types, giving you better tooling at scale.

### URL for tool's homepage

https://typescriptlang.org

### Provide a basic test case to validate the tool's functionality.

```bash
# Windows Only
cinst typescript
typescript --version
# Other OSes (MacOS, or GNU/Linux)
brew install typescript
typescript --version
```

### Virtual environments affected

- [X] Ubuntu 18.04
- [X] Ubuntu 20.04
- [X] macOS 10.15
- [X] macOS 11
-  Windows Server 2016 (deprecated)
- [X] Windows Server 2019
- [X] Windows Server 2022

### Can this tool be installed during the build?

```bash
# Windows Only
cinst nodejs.lts
cinst typescript
# Other OSes (MacOS, or GNU/Linux)
brew install typescript
```

### Tool installation time in runtime

about 1 minute

### Are you willing to submit a PR?

Yes

**Comment by shilovmaksim** [comment]
Hi @Tyler887 
We will take a look at this.

**Comment by miketimofeev** [comment]
@Tyler887 typescript is already available on Ubuntu and Windows images via `tsc` alias:
```
tsc --version
Version 4.5.5
```
for macOS it can be installed during the run in 2-3 seconds
```
npm install -g typescript
tsc --version
```
Please also take a look at this comment https://github.com/actions/virtual-environments/issues/1218#issuecomment-656981131
I'm going to close this issue but feel free to contact us if you have any concerns.
Thank you!
