### ISSUE TITLE
Update/Add [tool name]

### ISSUE THREAD

**Issue by azamshaikh** [actions/virtual-environments#5028]
### Tool name

Visual Studio

### Tool license

Microsoft

### Add or update?

- [X] Add
- [ ] Update

### Desired version

2017

### Brief description of tool

Hi

Windows Server 2016 with Visual Studio 2017 will be removed on 3/15 but to migrate the projects in this short span is not possible, hence requesting you to please add Visual Studio 2017 with .Net Framework 4.7.1 on windows-2019 agent.

Regards
Azam Shaikh

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [X] Windows Server 2019
- [ ] Windows Server 2022

**Comment by shilovmaksim** [comment]
Hi @azamshaikh .
We will take a look at this.

**Comment by miketimofeev** [comment]
@azamshaikh I'm afraid it's not possible due to maintenance concerns and consumed disk space. Please consider using self-hosted agents.
