### ISSUE TITLE
Update Powershell Core to 7.0.0

### ISSUE THREAD

**Issue by MattJeanes** [actions/virtual-environments#503]
**Tool information**
- Tool name: Powershell Core
- Add or update? Update
- Desired version: 7.0.0
- Approximate size: ~50-80MB installer depending on platform

**Area for Triage**:

.NET Core

**Question, Bug, or Feature?**:

Feature

**Virtual environments affected**
- [X] macOS 10.15
- [X] Ubuntu 16.04 LTS
- [X] Ubuntu 18.04 LTS
- [X] Windows Server 2016 R2
- [x] Windows Server 2019

**Can this tool be installed during the build?**

Yes, probably a minute or so

**Are you willing to submit a PR?**

Looks like it will automatically update on Ubuntu when pushed to the apt repository and Windows whenever the next image build is ran so should be automatic (unsure on Mac since sources are not here), but raising this issue to help track progress of Powershell 7 deployment

**Comment by miketimofeev** [comment]
@MattJeanes Hi! macOS PowerShell updates automatically as well so it will be available on next week's image rollout.

**Comment by VOVELEE** [comment]
it will be great if PS7 is available so quick. Let me know if help in development is needed :)

**Comment by miketimofeev** [comment]
@VOVELEE Thanks for offering assistance! The latest Powershell version is installed automatically during the image generation.

**Comment by JustinGrote** [comment]
@miketimofeev it looks like it took effect for all except ubuntu-18.04 for some reason:
![image](https://user-images.githubusercontent.com/15258962/76706623-099b5300-66a6-11ea-854b-3cfc72cc07fc.png)

Once that gets sorted I think we are good and this issue can be closed.

**Comment by miketimofeev** [comment]
@JustinGrote Ubuntu-18 is still rolling out and supposed to be finished today.

**Comment by miketimofeev** [comment]
All the images have been updated. @MattJeanes feel free to reopen if you have any concerns.
