### ISSUE TITLE
macOS 11 could update its intermediate certificates

### ISSUE THREAD

**Issue by Keith-CY** [actions/virtual-environments#5037]
### Description

I may encounter a similar [problem](https://github.com/actions/virtual-environments/issues/1620) in `macos-latest(macos-11)`.

A fresh `Developer ID Application Certificate` was generated today and marked `untrusted` in my local macos. Then I followed a guide to update the intermediate certificate([Developer ID - G2 (Expiring 09/17/2031 00:00:00 UTC)](https://www.apple.com/certificateauthority/DeveloperIDG2CA.cer) from https://www.apple.com/certificateauthority/ to make it trusted. It worked and signed my app successfully.

However, the validation failed in the CI, the certificate is denoted as an invalid identity with error `CSSMERR_TP_NOT_TRUSTED`. I go through several posts and think it's possibly related to the `intermediate certificates` in the host.

I'm not sure which version of the intermediate certificate is adopted in the host. But according to the last paragraph in this [post](https://developer.apple.com/support/expiration/), the `Developer ID Intermediate Certificate` was just updated on January 27, 2022.

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [X] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

[20220201.3](https://github.com/nervosnetwork/neuron/runs/5093688199?check_suite_focus=true#step:1:8)

### Repro steps

[GitHub Action](https://github.com/nervosnetwork/neuron/runs/5093688199?check_suite_focus=true#step:9:135)

Steps:
1. Generate a new `Developer ID Application` certificate in Apple
2. Export it in `p12` file and encode it into a base64 string
3. Set env `CSC_LINK` with the base64 string encoded above and `CSC_KEY_PASSWORD` with the password of `p12` file
4. Set other env
5. Run the GitHub Action

**Comment by shilovmaksim** [comment]
Hi @Keith-CY .
Thank you for your report. We will take a look at this.

**Comment by miketimofeev** [comment]
@Keith-CY we install only one intermediate certificate on the VM here
https://github.com/actions/virtual-environments/blob/f747f0983b8bd7d182869c830ae39ea75894453b/images/macos/provision/configuration/configure-machine.sh#L28-L33
According to your issue, do we need to install any other one? If yes, could you please tell us which? You can try experimenting in runtime in the meantime adding certificate using [this swift code](https://github.com/actions/virtual-environments/blob/main/images/macos/provision/configuration/add-certificate.swift) as we do it for macOS-11
https://github.com/actions/virtual-environments/blob/f747f0983b8bd7d182869c830ae39ea75894453b/images/macos/provision/configuration/configure-machine.sh#L38-L40

**Comment by Keith-CY** [comment]
> @Keith-CY we install only one intermediate certificate on the VM here
> 
> https://github.com/actions/virtual-environments/blob/f747f0983b8bd7d182869c830ae39ea75894453b/images/macos/provision/configuration/configure-machine.sh#L28-L33
> 
> 
> According to your issue, do we need to install any other one? If yes, could you please tell us which? You can try experimenting in runtime in the meantime adding certificate using [this swift code](https://github.com/actions/virtual-environments/blob/main/images/macos/provision/configuration/add-certificate.swift?rgh-link-date=2022-02-07T15%3A50%3A35Z) as we do it for macOS-11
> https://github.com/actions/virtual-environments/blob/f747f0983b8bd7d182869c830ae39ea75894453b/images/macos/provision/configuration/configure-machine.sh#L38-L40

@miketimofeev, thanks for the response.

According to the `issuer name` of our `Developer id application` certificate and the [news](https://developer.apple.com/news/?id=jzd7wqva) from Apple, [Developer ID - G2 (Expiring 09/17/2031 00:00:00 UTC)](https://www.apple.com/certificateauthority/DeveloperIDG2CA.cer) is desired.

I've tried the `DeveloperIDG2CA` and `AppleWWDRCAG3` in my local macos respectively and confirmed that `DeveloperIDG2CA` works while `AppleWWDRCAG3` does not.

I'd like to verify it in GitHub Action host and add a script as follow
```bash
#!/bin/bash

curl https://www.apple.com/certificateauthority/DeveloperIDG2CA.cer --output $HOME/DeveloperIDG2CA.cer --silent
swiftc $HOME/image-generation/add-certificate.swift
sudo ./add-certificate $HOME/DeveloperIDG2CA.cer
rm add-certificate
```

but get an error
```
<unknown>:0: error: error opening input file '/Users/runner/image-generation/add-certificate.swift' (No such file or directory)
```

What should I do to fix it

**Comment by miketimofeev** [comment]
@Keith-CY thanks for the confirmation! We will add [Developer ID - G2 (Expiring 09/17/2031 00:00:00 UTC)](https://www.apple.com/certificateauthority/DeveloperIDG2CA.cer) to the image and will update all the environments next week.

**Comment by al-cheb** [comment]
The new macOS-11 image has been deployed with [Developer ID - G2 (Expiring 09/17/2031 00:00:00 UTC)](https://www.apple.com/certificateauthority/DeveloperIDG2CA.cer) certificate on board.

![image](https://user-images.githubusercontent.com/47745270/154488597-6d85b9df-1f37-4a31-bc35-e80d29917ee8.png)
