### ISSUE TITLE
"fatal error - cygheap base mismatch detected" when run unzip - windows server 2022

### ISSUE THREAD

**Issue by alemuntoni** [actions/virtual-environments#5039]
### Description

When running `unzip` in windows 2022 (bash shell), it fails with the following error:
```
0 [main] unzip (6576) C:\Program Files\Git\usr\bin\unzip.exe: *** fatal error - cygheap base mismatch detected - 0x180348408/0x180349408.
This problem is probably due to using incompatible versions of the cygwin DLL.
Search for cygwin1.dll using the Windows Start->Find/Search facility
and delete all but the most recent version.  The most recent version *should*
reside in x:\cygwin\bin, where 'x' is the drive on which you have
installed the cygwin distribution.  Rebooting is also suggested if you
are unable to find another cygwin DLL.
``` 
This did not happen on windows 2019.

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

version: 20220131.1

https://github.com/alemuntoni/cygheap-mismatch-example/runs/5094831755?check_suite_focus=true

### Repro steps

Create a new github action workflow like [this](https://github.com/alemuntoni/cygheap-mismatch-example/blob/main/.github/workflows/blank.yml).

**Comment by al-cheb** [comment]
@alemuntoni, You could use the default shell with curl and unzip:
```
- run:  |
      curl.exe -sL https://boostorg.jfrog.io/artifactory/main/release/1.75.0/source/boost_1_75_0.zip --output boost_1_75_0.zip
      unzip boost_1_75_0.zip
      rm boost_1_75_0.zip
```

**Comment by al-cheb** [comment]
@alemuntoni, In that case we should install wget&unzip:
```
      - run: |
          # Add msys2 bin tools folders to PATH temporary
          $env:PATH = "C:\msys64\mingw64\bin;C:\msys64\usr\bin"
          pacman.exe -S --noconfirm --noprogressbar wget unzip
      - name: Download boost
        shell: C:\shells\msys2bash.cmd {0}
        run: |
            wget https://boostorg.jfrog.io/artifactory/main/release/1.75.0/source/boost_1_75_0.zip
            unzip boost_1_75_0.zip
            rm boost_1_75_0.zip   
```

**Comment by alemuntoni** [comment]
that's better, thanks @al-cheb!
I don't know if the issue could be set as solved, since still there is a behavior that was working on 2019 and does not anymore on 2022, but this alternative solution works fine for my specific case!

**Comment by al-cheb** [comment]
I don't think that we should mix git utils(with their own msys2  binaries) and msys2 due to unpredictable behavior. Because it works in msys2 environment I am planning to close the thread.
