### ISSUE TITLE
Update/Add Azure-devops extension to Azure CLI

### ISSUE THREAD

**Issue by sennerholm** [actions/virtual-environments#5053]
### Tool name

Azure CLI (azure-devops) 0.22.0

### Tool license

MIT 

### Add or update?

- [X] Add
- [ ] Update

### Desired version

0.22.0

### Brief description of tool

# Azure DevOps Extension for Azure CLI

[![Build Status](https://dev.azure.com/ms/azure-devops-cli-extension/_apis/build/status/Azure%20DevOps%20CLI%20-%20Merge%20GitHub?branchName=master)](https://dev.azure.com/ms/azure-devops-cli-extension/_build/latest?definitionId=39&branchName=master)

The Azure DevOps Extension for Azure CLI adds Pipelines, Boards, Repos, Artifacts and DevOps commands to the Azure CLI 2.0.

> The Azure CLI with the Azure DevOps Extension has replaced the VSTS CLI. The VSTS CLI has been deprecated and will no longer be receiving new features. We recommend that users of the VSTS CLI switch to the Azure CLI and add the Azure DevOps extension. See the [Command Mapping](/doc/command_mapping.md) section to view the mapping between VSTS CLI and Azure DevOps Extension commands.

# Reason 
The tools is already installed in the other images, but by some reason not on Mac. 

### URL for tool's homepage

https://github.com/Azure/azure-devops-cli-extension

### Provide a basic test case to validate the tool's functionality.

```bash
Verify that it's installed:

 extension list | grep devops

To verify the the functionality we probably need a PAT token and some azure devops project to test against, but I'm not sure that is in the other Agent installations. If it exists test cases in the Linux install those should hopefully be possible to reuse.
```

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [X] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Can this tool be installed during the build?

```bash
- task: CmdLine@2
    inputs:
      script: |
        az config set extension.use_dynamic_install=yes_without_prompt
        az extension add --name azure-devops
```

### Tool installation time in runtime

3m10s

### Are you willing to submit a PR?

Maybe

**Comment by sennerholm** [comment]
The test cases in Linux are:
https://github.com/actions/virtual-environments/blob/952ee3e7407ee7567f7a1f5b92c40f2a58acd885/images/linux/scripts/tests/CLI.Tools.Tests.ps1#L8-L11

and installation are:
https://github.com/actions/virtual-environments/blob/main/images/linux/scripts/installers/azure-devops-cli.sh
Seems like it's possible to reuse but the structure of the mac builds are different so I don't know where to put them if you want a PR.

**Comment by al-cheb** [comment]
@sennerholm, We will take a look at it. But currently we don't accept PRs for macOS.

**Comment by sennerholm** [comment]
@al-cheb  Thanks, let me know if it's anything you want me to do. When you accept PRs I could to create one, but it should really be easy to copy paste some of the setup from the Linux one.

**Comment by al-cheb** [comment]
The new macOS images have been deployed with azure-devops on board.

**Comment by sennerholm** [comment]
Verified on our side. Thanks again.
