### ISSUE TITLE
Git version included in Windows Server 2019 (20220131.1) has a bug that causes tasks to fail when executing `git status`

### ISSUE THREAD

**Issue by edgariscoding** [actions/virtual-environments#5054]
### Description

Git version 2.35.1 includes a bug which causes the `git status` Git operations to fail with the following error:

```
BUG: refs/files-backend.c:465: returning non-zero -1, should have set myerr!
##[error]PowerShell exited with code '1'.
```

This was reported here: https://github.com/git-for-windows/git/issues/3655
Was fixed here: https://github.com/git-for-windows/git/pull/3678
And the fix is included in Git version 2.35.1(2): https://github.com/git-for-windows/git/releases/tag/v2.35.1.windows.2

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [X] Windows Server 2016
- [X] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

Version: 20220131.1

### Expected behavior

I expected the `git status` operation to complete like it has done previously.

### Actual behavior

Failing task with the following error:

```
BUG: refs/files-backend.c:465: returning non-zero -1, should have set myerr!
##[error]PowerShell exited with code '1'.
```

### Repro steps

Create a Powershell task and execute `git status`

**Comment by shilovmaksim** [comment]
Hi @edgariscoding 
Thank you for your report. We will take a look at this.

**Comment by shilovmaksim** [comment]
@edgariscoding ,
Unfortunately I'm unable to reproduce it on my workflow:
https://github.com/shilovmaksim/test-repo/runs/5136959910?check_suite_focus=true

**Comment by shilovmaksim** [comment]
@edgariscoding , gentle ping.
Could you please provide a sample repo or a workflow where this issue reproduces?

**Comment by edgariscoding** [comment]
@shilovmaksim, sorry for the delay.

I'll attach the exact commands that were in the powershell script that was failing. Here's a weird thing though. This script is part of a task group which is called multiple times within the same pipeline with different variables passed in as parameters. In the same pipeline run, this script succeeded once and then failed the second time it was run. The version of Git used by the build agent did not change from one task run to the next so not sure why it would have succeeded the first time. On a subsequent run it failed on the first try. There's a few other places we use similar git commands and they also failed in the same way.

In all occasions the exception seems to be thrown when calling `git status` after running different commands.

If you would like for me to send you a link to the exact pipeline run that failed I can do that, just let me know.

In our case `$(sourceBranch)` could be `"develop"` and `$(targetBranch)` could be `"release/22.2.2"`

```
Write-Host === Clone Repo $(gitRepoName) into /$(gitRepoName) ===
git clone -b $(sourceBranch) https://ORGANIZATION:$(System.AccessToken)@dev.azure.com/ORGANIZATION/ORGANIZATION/_git/$(gitRepoName)
Write-Host === Done! ===

Write-Host === Set Git username and email ===
$env:UserName
git config --list
git config --global user.email "VssAdministrator@factoryvm-az639.(none)"
git config --global user.name "VSTS Admin"
Write-Host === Done! ===

Write-Host === Change directory to /$(gitRepoName) ===
cd $(gitRepoName)
Write-Host === Done! ===

Write-Host === Fetch Origin ===
#git fetch origin
Write-Host === Done! ===

Write-Host === Checkout Source Branch: $(sourceBranch) ===
git checkout origin/$(sourceBranch)
Write-Host === Done! ===

Write-Host === Checkout Target Branch: $(targetBranch) ===
git checkout origin/$(targetBranch)
Write-Host === Done! ===

Write-Host === Push Changes ===
git push origin +$(sourceBranch):$(targetBranch)
Write-Host === Done! ===

Write-Host === Status of $(targetBranch)
git status
Write-Host === Done! ===
```

**Comment by shilovmaksim** [comment]
Hi @edgariscoding . 
I am unable to reproduce this issue in the azure pipelines either.
![image](https://user-images.githubusercontent.com/89912354/154249030-75039c05-847a-4587-bdc7-f43afde1751f.png)

**Comment by edgariscoding** [comment]
@shilovmaksim 

Could you take a look at this pipeline: 

https://dev.azure.com/CiraConnect/CiraConnect/_build/results?buildId=18016&view=results

**Comment by shilovmaksim** [comment]
@edgariscoding , unfortunately, I don't have access to this org/project.

**Comment by edgariscoding** [comment]
@shilovmaksim 

Ok no problem, in that case we can go ahead and close this issue. 

If anyone else runs into this problem and needs a workaround until the agents get updated again you can just update Git to the latest version by adding a Powershell task with the following:

Powershell:
```
choco upgrade git
```

**Comment by shilovmaksim** [comment]
Thank you @edgariscoding .
Since we're always installing latest version of git on the image, git version [2.35.1.windows.2](https://github.com/git-for-windows/git/releases/tag/v2.35.1.windows.2) should be deployed and became available later this week.
However I noticed that we're output not the full version in the image readme's that can confuse customers. We will update this.
