### ISSUE TITLE
windows-2022 image is missing the ARM libraries windows-2019 image provided

### ISSUE THREAD

**Issue by robmen** [actions/virtual-environments#5056]
### Description

The windows-2019 image [contained the libraries required to build ARM64 binaries](https://github.com/actions/virtual-environments/blob/52011e5c44240b1b77ee56c8d664d353172ac1ff/images/win/toolsets/toolset-2019.json#L327). The windows-2022 image is missing those libraries preventing builds.

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

windows-2022

### Is it regression?

windows-2019

### Expected behavior

Building ARM64 binaries on windows-2022 (soon to be `windows-latest`) should be possible.

### Actual behavior

The windows-2022 image does not have ARM64 libraries so ARM64 builds fail.

### Repro steps

1. Look at the 2019 image to see ARM and ARM64 available: https://github.com/actions/virtual-environments/blob/52011e5c44240b1b77ee56c8d664d353172ac1ff/images/win/toolsets/toolset-2019.json#L325-L328

2. Look at the 2022 imageARM and ARM64 not available:  https://github.com/actions/virtual-environments/blob/52011e5c44240b1b77ee56c8d664d353172ac1ff/images/win/toolsets/toolset-2022.json#L212-L213

**Comment by shilovmaksim** [comment]
Hi @robmen . Thank you for your report.

We will add missing components to the image.
