### ISSUE TITLE
Installation of MySQL Client Fails

### ISSUE THREAD

**Issue by theory** [actions/virtual-environments#5067]
### Description

In [this workflow], I use [this script] to install the MySQL client. This is all it does:

``` sh
sudo apt-get update -qq
sudo env DEBIAN_FRONTEND=noninteractive apt-get install -qq mysql-client default-libmysqlclient-dev
```

It started [failing] recently with this error:

```
E: Unable to correct problems, you have held broken packages.
##[error]Process completed with exit code 100.
```

This has not been an issue for similar database scripts like for [firebird]. For now I have disabled the script, since the runner already has MySQL clients installed, but I'd like to get it back for completeness at some point.  I assume some existing package in the runner borks the upstream MySQL client install or something. I can try to replicate if you could point me to a docker image for the runners; otherwise, can you replicate the issue?

  [this workflow]: https://github.com/sqitchers/sqitch/blob/develop/.github/workflows/mysql.yml
  [this script]: https://github.com/sqitchers/sqitch/blob/develop/.github/ubuntu/mysql.sh
  [failing]: https://github.com/sqitchers/sqitch/runs/5169916165?check_suite_focus=true
  [firebird]: https://github.com/sqitchers/sqitch/blob/develop/.github/ubuntu/firebird.sh

### Virtual environments affected

- [ ] Ubuntu 18.04
- [X] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

```
2022-02-12T22:03:36.8867063Z ##[group]Virtual Environment
2022-02-12T22:03:36.8867461Z Environment: ubuntu-20.04
2022-02-12T22:03:36.8867881Z Version: 20220207.1
2022-02-12T22:03:36.8868531Z Included Software: https://github.com/actions/virtual-environments/blob/ubuntu20/20220207.1/images/linux/Ubuntu2004-Readme.md
2022-02-12T22:03:36.8869271Z Image Release: https://github.com/actions/virtual-environments/releases/tag/ubuntu20%2F20220207.1
```

Previous build that worked without issue:

```
2021-12-05T21:21:55.6674537Z ##[group]Virtual Environment
2021-12-05T21:21:55.6675368Z Environment: ubuntu-20.04
2021-12-05T21:21:55.6675881Z Version: 20211129.1
2021-12-05T21:21:55.6676895Z Included Software: https://github.com/actions/virtual-environments/blob/ubuntu20/20211129.1/images/linux/Ubuntu2004-README.md
2021-12-05T21:21:55.6678223Z Image Release: https://github.com/actions/virtual-environments/releases/tag/ubuntu20%2F20211129.1
```

### Is it regression?

https://github.com/sqitchers/sqitch/actions/runs/1542150949

### Expected behavior

The `apt-get update` and `apt-get install` commands should work.

### Actual behavior

It fails:

```
E: Unable to correct problems, you have held broken packages.
##[error]Process completed with exit code 100.
```

### Repro steps

Try running these commands in a workflow:

``` sh
sudo apt-get update -qq
sudo env DEBIAN_FRONTEND=noninteractive apt-get install -qq mysql-client default-libmysqlclient-dev
```

**Comment by al-cheb** [comment]
Hello @theory,
We will take a look at it.

**Comment by miketimofeev** [comment]
@theory this is most likely related to the https://github.com/actions/virtual-environments/issues/4799
Could you try to remove every bit of previous MySQL installation first?
```
sudo apt-get update
sudo apt-get remove mysql
```

**Comment by theory** [comment]
Tired it, did not seem to help. I removed the `--q` option to get more context, which you can see [here](/sqitchers/sqitch/runs/5253234853?check_suite_focus=true). Important bit:

```
Package 'mysql' is not installed, so not removed
```

Must be a different package. Hrm…

**Comment by theory** [comment]
Removing `mysql-common` [does the trick](https://github.com/sqitchers/sqitch/runs/5253357168)

**Comment by miketimofeev** [comment]
@theory sorry, there was an error in the code snippet, should have been with an asterisk at the end:
`sudo apt-get remove mysql*`
I'm going to close the issue.
Thank you!

**Comment by theory** [comment]
Presumably the change in #4799 will be reversed at some point, and then this workaround would no longer be necessary, yes? Might be nice to keep this issue open and close it at that time so it's easier for people to find in the interim. Or if not open tagged in some kind of meaningful way.

**Comment by miketimofeev** [comment]
@theory thanks for the idea, will see how many people come with the issue and re-open if needed. For now, it's unclear how long it will take to fix the initial problem.
