### ISSUE TITLE
My all jobs are getting failed with error: This check failed

### ISSUE THREAD

**Issue by ranjithvbr** [actions/virtual-environments#5069]
### Description

when running all my jobs on GitHub action, I'm getting "This check failed" error

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

<img width="1331" alt="Screen Shot 2022-02-13 at 10 16 52 AM" src="https://user-images.githubusercontent.com/37235948/153770985-4cc81c43-a78f-4141-8ce5-f80b12e1710b.png">

### Expected behavior

All jobs should be run

### Actual behavior

when creating PR, jobs are not getting called on GitHub action with error: This check failed

### Repro steps

create push requests to run the GitHub Jobs

OR

Re-run all the jobs on Github action

Unable to provide a repository link, because its private repo

**Comment by al-cheb** [comment]
Hello @ranjithvbr ,
Please provide links to your private repo builds and attach logs. If you can't provide these logs you should create an issue - https://github.community/

**Comment by ranjithvbr** [comment]
Private repo builds: https://github.com/NEOM-KSA/meld-mobile-app/actions
<img width="1720" alt="Screen Shot 2022-02-13 at 9 03 26 PM" src="https://user-images.githubusercontent.com/37235948/153808938-9de2ec0c-f57f-4b20-876f-d777a3569de3.png">

Please check @al-cheb

**Comment by al-cheb** [comment]
@ranjithvbr, The job was not started because recent ****account payments have failed**. Please ensure payment in order to proceed.** Please contact to support - https://support.github.com/contact about  [billing.](https://docs.github.com/en/billing/managing-billing-for-your-github-account/about-billing-for-github-accounts)

**Comment by ranjithvbr** [comment]
okay got it, Thanks for your support 🙂
