### ISSUE TITLE
Rust project paho-mqtt-sys fails to compile on windows-2022, works on 2019

### ISSUE THREAD

**Issue by stefangalowicz** [actions/virtual-environments#5079]
### Description

A Rust project of mine used to be able to compile its dependency `paho-mqtt-sys` on `windows-latest`. Now I need to explicitly set `windows-2019`.

I reported the issue to the `paho-mqtt-sys` project here: https://github.com/eclipse/paho.mqtt.rust/issues/147

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

not public

### Is it regression?

windows-2019

### Expected behavior

```
[...]
   Compiling paho-mqtt-sys v0.6.0
   Compiling paho-mqtt v0.10.0
```

### Actual behavior

```
[...]
error: failed to run custom build command for `paho-mqtt-sys v0.6.0`

Caused by:
  process didn't exit successfully: `D:\a\anon\anon\repo\target\release\build\paho-mqtt-sys-0350774f96c83411\build-script-build` (exit code: 101)
  --- stdout
  debug:Running the bundled build for Paho C
  debug:Building for Windows
  debug:Building with MSVC
  cargo:rerun-if-changed=build.rs

  --- stderr
  fatal: not a git repository (or any of the parent directories): .git
  thread 'main' panicked at '

  couldn't determine visual studio generator
  if VisualStudio is installed, however, consider running the appropriate vcvars script before building this crate
  ', C:\Users\runneradmin\.cargo\registry\src\github.com-1ecc6299db9ec823\cmake-0.1.45\src\lib.rs:797:25
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: build failed
Error: Process completed with exit code 1.
```

### Repro steps

1. Add this dependency to a Rust project:
```
paho-mqtt = { version = "0.10.0", default-features = false, features = ["bundled"] }
```
2. Set up a workflow with `runs-on: windows-latest`
3. Add a compile step `cargo build --target=i686-pc-windows-msvc --locked --release --manifest-path=anon\Cargo.toml`

**Comment by al-cheb** [comment]
Hello @stefangalowicz,
We will take a look at it.

@alexcrichton,  Do you support Visual Studio 2022 on Windows Server 2022?

**Comment by alexcrichton** [comment]
This is likely a bug with the `cmake` Rust crate, not with GitHub Actions. I suspect that version of Visual Studio isn't detected yet or something like that, but that's a Rust-`cmake`-crate problem rather than a GitHub Actions problem.

**Comment by stefangalowicz** [comment]
@alexcrichton thanks for pointing that out. Could this be the issue then https://github.com/alexcrichton/cmake-rs/blob/7793895d88acc45d29fac7c711ddaef11c897ea9/src/lib.rs#L610 ? I assume Vs17 must be added.

**Comment by al-cheb** [comment]
Thank you, @alexcrichton.
@stefangalowicz , I am planning to close this thread as an external issue.
