### ISSUE TITLE
Add AWSPowershell Module

### ISSUE THREAD

**Issue by animusyosho** [actions/virtual-environments#5083]
### Tool name

AWSPowerShell Module

### Tool license

Apache license version 2.0

### Add or update?

- [X] Add
- [ ] Update

### Desired version

Latest

### Brief description of tool

AWS tools powershell module. Having this available on hosted agents will greatly speed up the usage and performance of the "AWS Tools for Windows PowerShell Script" task. Every time this task runs currently there is over 2 minutes of delay to install it. This probably eats tons of CPU cycles every day as well (We run this 4 times per environment so this averages out to an hour or 2 of time spent only on waiting for this module package to install repeatedly each day). 

### URL for tool's homepage

https://www.powershellgallery.com/packages/AWSPowerShell

### Provide a basic test case to validate the tool's functionality.

```bash
try {
  Import-Module -Name AWSPowershell -ErrorAction Stop
}
catch {
  $_ | Write-Error
  throw "Could not import AWSPowershell module."
}
```

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [X] Windows Server 2016
- [X] Windows Server 2019
- [X] Windows Server 2022

### Can this tool be installed during the build?

```bash
Maybe? I don't know your build process but this is how I usually do it in my code:

#Dependencies 
[version]$TargetVersion = '4.1.17.0'
$InstalledModule = Get-Module -ListAvailable -Name AWSPowershell -ErrorAction SilentlyContinue
if (!$InstalledModule -or $InstalledModule.Version -lt $TargetVersion) {
  if (!(Get-PackageProvider | Where-Object { $_.Name -eq 'NuGet' -and $_.version -ge [version]'2.8.5.208' })) {
    Install-PackageProvider -Name Nuget -RequiredVersion '2.8.5.208' -Force
  }
  $UninstallWrongModules = Get-InstalledModule -ErrorAction SilentlyContinue | Where-Object { $_.Name -like 'AWS*'} | Uninstall-Module -Force -ErrorAction SilentlyContinue
  $InstalledModule | Select-Object -ExpandProperty ModuleBase | Remove-Item -Recurse -Force -ErrorAction SilentlyContinue
  Install-Module -Name AWSPowershell -MinimumVersion $TargetVersion.ToString() -Force -SkipPublisherCheck -AllowClobber
}
Import-Module AWSPowershell -MinimumVersion $TargetVersion.ToString()

Perhaps a better option is to do it like the task authors do at AWS:
https://github.com/aws/aws-toolkit-azure-devops/blob/master/src/tasks/AWSPowerShellModuleScript/RunAWSPowerShellModuleScript.ps1

    # suppress any progress bars to attempt to speed things up
    $ProgressPreference = 'SilentlyContinue'

    # Agent.TempDirectory was added in agent version 2.115.0, which may not
    # be available in 2015 installs of TFS, so probe for and fallback to
    # another temp location variable if necessary. This allows us to set
    # minimunm agent version that's compatible with TFS 2015 editions
    # preventing an issue causing our tasks to not be listed after install
    # if a higher agent version is specified.
    $tempDirectory = Get-VstsTaskVariable -Name 'agent.tempDirectory'
    if (!$tempDirectory) {
        Write-Host 'Agent.TempDirectory not available, falling back to user temp location'
        $tempDirectory = $env:TEMP
    }

    Assert-VstsPath -LiteralPath $tempDirectory -PathType 'Container'

    # install the module if not present (we assume if present it is an an autoload-capable
    # location)
    Write-Host (Get-VstsLocString -Key 'TestingAWSModuleInstalled')
    if (!(Get-Module -Name AWSPowerShell -ListAvailable)) {
        Write-Host (Get-VstsLocString -Key 'AWSModuleNotFound')

        # AllowClobber is not available in Install-Module in the Hosted agent (but is in the
        # Hosted 2017 agent). We always install/update the latest NuGet package
        # provider to work around Install-Module on the Hosted agent also not having -Force and
        # producing the error
        #
        # 'Exception calling “ShouldContinue” with “2” argument(s): “Windows PowerShell is in NonInteractive mode.'
        #
        Write-Host (Get-VstsLocString -Key 'InstallingAWSModule')
        Install-PackageProvider -Name NuGet -Scope CurrentUser -Verbose -Force
        $installModuleCmd = Get-Command Install-Module
        if ($installModuleCmd.Parameters.ContainsKey("AllowClobber")) {
            Install-Module -Name AWSPowerShell -Scope CurrentUser -Verbose -AllowClobber -Force
        }
        else {
            Install-Module -Name AWSPowerShell -Scope CurrentUser -Verbose -Force
        }
    }

    Import-Module -Name AWSPowerShell
```

### Tool installation time in runtime

~2 minutes

### Are you willing to submit a PR?

If it is powershell, yes.

**Comment by miketimofeev** [comment]
Hi @animusyosho!
Please feel free to submit a PR. Adding the module should be easy as we already have a helper to install modules that are described in the toolset.json https://github.com/actions/virtual-environments/blob/main/images/win/scripts/Installers/Install-PowerShellModules.ps1
toolsets are available here https://github.com/actions/virtual-environments/tree/main/images/win

**Comment by animusyosho** [comment]
Thanks much for the quick response @miketimofeev ! 
So am I reading correctly that all that should be required is to add to the powershellModules array in the toolset json files?

**Comment by miketimofeev** [comment]
@animusyosho correct, here is a similar PR https://github.com/actions/virtual-environments/pull/4274

**Comment by miketimofeev** [comment]
@animusyosho the PR is merged. The new images will be deployed next week. We will update the issue when the deployment is finished.

**Comment by animusyosho** [comment]
@miketimofeev Thanks for the help! This was very easy and you all are great to work with. :)

**Comment by miketimofeev** [comment]
@animusyosho the new images have been deployed.
I'm going to close the issue. Feel free to contact us if you have any concerns.
Thank you!
