### ISSUE TITLE
Provide slim image variants

### ISSUE THREAD

**Issue by jan-kiszka** [actions/virtual-environments#5098]
### Tool name

-

### Tool license

-

### Add or update?

- [X] Add
- [ ] Update

### Desired version

-

### Approximate size

Up to -42GB, according to our experiments

### Brief description of tool

[Selecting this form as no others fit better]

As already discussed in #4663, there are use cases that would benefit from to also having a base image available with more space free and, therefore, only a minimal set of tools pre-installed. Specifically when you run container workloads, there is no need for most of the default tools, just docker or podman and related things. Purging pre-installed tools is possible but needlessly consumes a lot of CI time and likely also bandwidth to deploy the larger images in the first place.

### Virtual environments affected

- [ ] Ubuntu 18.04
- [X] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Can this tool be installed during the build?

Yes, but takes time and needs maintenance with new image releases. 

### Tool installation time in runtime

5 to 10 minutes are needed for purging so far

### Are you willing to submit a PR?

in principle, yes

**Comment by al-cheb** [comment]
@jan-kiszka , This is a roadmap plan to provide base image with minimal pre-installed software and different runner specs - https://github.com/github/roadmap/issues/161

Currently ,we support only - https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners
```
Supported runners and hardware resources
Hardware specification for Windows and Linux virtual machines:

2-core CPU
7 GB of RAM memory
14 GB of SSD disk space
Hardware specification for macOS virtual machines:

3-core CPU
14 GB of RAM memory
14 GB of SSD disk space
```

We cannot honor requests to increase disk space on GitHub-hosted runners, or to provision more powerful machines. If the specifications of GitHub-hosted runners do not meet your needs, then you should consider [self-hosted runners](https://docs.github.com/en/actions/hosting-your-own-runners/about-self-hosted-runners)

**Comment by jan-kiszka** [comment]
This is not about increasing disk size, it's about providing another image flavor, for the benefit also of your resources. Just like you already provide two version of Ubuntu images.

**Comment by al-cheb** [comment]
> 

Currently, we don't have any progress - https://github.com/actions/virtual-environments/discussions/3242

**Comment by jan-kiszka** [comment]
Thanks for the link, missed that discussion. Good to see that this direction is on the radar at least.
