### ISSUE TITLE
'VMCustomization' is not enabled for the Subscription

### ISSUE THREAD

**Issue by rennerg** [actions/virtual-environments#5099]
### Description

`az vm create` fails using the Azure hosted CLI v2.33.0. 

```json
{
  "code":"BadRequest",
  "message": {
    "error": {
      "code":  "BadRequest",
      "message":  "'VMCustomization' is not enabled for the Subscription. Please register the Subscription for 'Microsoft.Compute/VMCustomizationPreview' to use the feature."
    }
  }
}
```

This is a [known issue](https://docs.microsoft.com/en-us/answers/questions/727655/39vmcustomization39-is-not-enabled-for-the-subscri.html) with Azure Cloud Shell v2.33.0 and a fix in being worked on, if not available already. 

Updating to v2.33.1 as soon as it is available should fix the issue.

### Virtual environments affected

- [X] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

20220213.1

### Expected behavior

No errors.

### Actual behavior

`az vm create` fails to complete with the following error output:

{"status":"Failed","error":{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.","details":[{"code":"BadRequest","message":"{\r\n  \"error\": {\r\n    \"code\": \"BadRequest\",\r\n    \"message\": \"'VMCustomization' is not enabled for the Subscription. Please register the Subscription for 'Microsoft.Compute/VMCustomizationPreview' to use the feature.\"\r\n  }\r\n}"}]}}

### Repro steps

1. Run `az vm create` using Azure Cloud Shell after February 1, 2022.

**Comment by miketimofeev** [comment]
Hi @rennerg!
Az 2.33.1 is already available — https://github.com/Azure/azure-cli/releases/tag/azure-cli-2.33.1
The new images will be deployed next week.

**Comment by rennerg** [comment]
> Hi @rennerg! Az 2.33.1 is already available — https://github.com/Azure/azure-cli/releases/tag/azure-cli-2.33.1 The new images will be deployed next week.

Thanks for the quick reply Mikhail. Any idea what day exactly? We're blocked and unable to release at the moment. Thanks

**Comment by miketimofeev** [comment]
@rennerg we will force the deployment a bit so I hope will finish it by Tuesday or Wednesday.
In the meantime you can update az-cli in runtime
```bash
curl -sL https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/microsoft.gpg > /dev/null
echo "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/azure-cli.list
sudo apt-get update
sudo apt-get install azure-cli
az version
```

**Comment by miketimofeev** [comment]
@rennerg we have updated both Ubuntu images with the new azure-cli version.
I'm going to close the issue. Feel free to contact us if you have any concerns.
Thank you!
