### ISSUE TITLE
Update/Add protobuf

### ISSUE THREAD

**Issue by jmhodges** [actions/virtual-environments#51]
**Tool information**
- Tool name: protobuf
- Add or update? Add
- Desired version: v3.10.0
- Approximate size: 
- If this is an add request:
  - Brief description of tool: Includes protoc (the protobuf compiler) and the built-in protobuf types
  - URL for tool's homepage: https://github.com/protocolbuffers/protobuf/releases

**Virtual environments affected**
- [ ] macOS 10.14
- [X] Ubuntu 16.04 LTS
- [X] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Can this tool be installed during the build?**
Yep. But takes well over 15 minutes to build all of the languages it supports.

I've got one GH Action attempt working now, but the 15 minute time line is too long and I'm going to try if building fewer language supports makes it faster. It's a lot of C++. And, unfortunately, ubuntu-latest only supports protobuf 3.0.

**Are you willing to submit a PR?**
Sure, but I don't see any directions on where and how to do that?

**Comment by jmhodges** [comment]
Example build: https://github.com/jmhodges/gocld3/commit/4a70128563f25492efb88ab4f65b813759c6412e/checks?check_suite_id=273185502

**Comment by jmhodges** [comment]
Ping!

**Comment by maxim-lobanov** [comment]
@jmhodges , thank you for sharing feature request.

Have you tried to use [actions/cache](https://github.com/marketplace/actions/cache) to build it once and then cache? I believe it will significantly reduce the time of your build

**Comment by alepauly** [comment]
@jmhodges well it took me a while to get here, apologies for the delay in responding. We can't add protobuf to the environments at this time considering that it's fairly specialized and it we are unsure of maintenance going forward. Hopefully the actions/cache as suggested by @maxim-lobanov can improve the timing.
