### ISSUE TITLE
Can not build Analysis services projects in Windows Server 2019 with Visual Studio 2019 (	windows-2019) probably due to Analysis Services Project extension missing in VS2019. 			

### ISSUE THREAD

**Issue by raghu4sangeeth** [actions/virtual-environments#510]
**Describe the bug**
Can not build Analysis services projects (Tabular) in Windows Server 2019 with Visual Studio 2019 (	windows-2019) probably due to "Analysis Services Project extension" missing in VS2019. however the build succeeds in VS2017-win2016 as the extension is already installed by default by VS2017. from VS2019 onwards the extension is optional and the installation is user driven.			

**Area for Triage**: 
Deployment/Release

**Question, Bug, or Feature?**: 
"Bug"

**Virtual environments affected**
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [ X] Windows Server 2019

**Expected behavior**
Able to build the Analysis services projects. 

**Actual behavior**
Analysis Services Build Fails.

1. Create a tabular Project in VS2019 
2. Use the windows-2019 build agent to build the project.

**Comment by miketimofeev** [comment]
Related issue
https://github.com/actions/virtual-environments/issues/324

**Comment by miketimofeev** [comment]
This extension should be installed to resolve the issue
https://marketplace.visualstudio.com/items?itemName=ProBITools.MicrosoftAnalysisServicesModelingProjects

**Comment by miketimofeev** [comment]
PR has been merged. A new image will be rolled out next week.

**Comment by elduddz** [comment]
is this in 20200308 not a major issue, the installer file is spelt wrong, it is all ok as the misspelling is carried through to the json :)

**Comment by miketimofeev** [comment]
@raghu4sangeeth @elduddz the image has been deployed recently. Could you check extension is presented now?

**Comment by miketimofeev** [comment]
@elduddz sorry, I can't find the wrong spelling, could you help me? 😅

**Comment by miketimofeev** [comment]
@raghu4sangeeth everything works fine(was discussed in teams). Closing the issue, but feel free to reopen if you have any concerns.
Thank you!

**Comment by elduddz** [comment]
> @elduddz sorry, I can't find the wrong spelling, could you help me identify it, please?

Install-AnalysisExtenstion.ps1

**Comment by miketimofeev** [comment]
@elduddz oh, the name of the script, thanks. We are going to change the naming anyway.
