### ISSUE TITLE
Ruby `gem install ronn` fails on Windows Server 2022

### ISSUE THREAD

**Issue by chrisd8088** [actions/virtual-environments#5100]
### Description

In our Windows CI build [job](https://github.com/git-lfs/git-lfs/blob/5e126183dd2b9fcb66f42429ed41175e7544fde0/.github/workflows/ci.yml#L24) for the Git LFS project, we have a step which installs the `ronn` Ruby gem (https://github.com/rtomayko/ronn) with `gem install ronn`.  This succeeds on a Windows Server 2019 Actions runner, but fails on a Windows Server 2022 runner, due to a what seems to be a C library or header problem.  The specific failure is outlined in the "Actual behavior" section below.

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

Environment: windows-2022
Version: 20220207.1
Failed build: https://github.com/chrisd8088/git-lfs/runs/5236350328?check_suite_focus=true

### Is it regression?

This is a regression from Windows Server 2019.

Environment: windows-2019
Version: 20220131.1
Successful build: https://github.com/chrisd8088/git-lfs/runs/5236480511?check_suite_focus=true

### Expected behavior

We expect the Ruby gem to install cleanly and successfully, as it does with Windows Server 2019:
```
▶ Run gem install ronn
  gem install ronn
  shell: C:\Program Files\Git\bin\bash.EXE --noprofile --norc -e -o pipefail {0}
Successfully installed mustache-1.1.1
Temporarily enhancing PATH for MSYS/MINGW...
Building native extensions. This could take a while...
Successfully installed rdiscount-2.2.0.2
Building native extensions. This could take a while...
Successfully installed hpricot-0.8.6
Successfully installed ronn-0.7.3
Parsing documentation for mustache-1.1.1
Installing ri documentation for mustache-1.1.1
Parsing documentation for rdiscount-2.2.0.2
Installing ri documentation for rdiscount-2.2.0.2
Parsing documentation for hpricot-0.8.6
Installing ri documentation for hpricot-0.8.6
Parsing documentation for ronn-0.7.3
Installing ri documentation for ronn-0.7.3
Done installing documentation for mustache, rdiscount, hpricot, ronn after 5 seconds
4 gems installed
```

### Actual behavior

The build failure output is as follows; it appears that the key issue may be a failure to build a small C test [program](https://github.com/ruby/ruby/blob/3fb7d2cadc18472ec107b14234933b017a33c14d/lib/mkmf.rb#L737-L751) used to check the system configuration during the build process.  The result is perhaps a failure to run the test program and [check](https://github.com/ruby/ruby/blob/3fb7d2cadc18472ec107b14234933b017a33c14d/lib/mkmf.rb#L755) its return value.

```
▶ Run gem install ronn
ERROR:  Error installing ronn:
	ERROR: Failed to build gem native extension.
Temporarily enhancing PATH for MSYS/MINGW...
Building native extensions. This could take a while...

    current directory: C:/hostedtoolcache/windows/Ruby/3.0.3/x64/lib/ruby/gems/3.0.0/gems/rdiscount-2.2.0.2/ext
C:/hostedtoolcache/windows/Ruby/3.0.3/x64/bin/ruby.exe -I C:/hostedtoolcache/windows/Ruby/3.0.3/x64/lib/ruby/3.0.0 -r ./siteconf20220217-1960-zhwi49.rb extconf.rb
checking for random()... no
checking for srandom()... no
checking for rand()... yes
checking for srand()... yes
checking size of unsigned long... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=C:/hostedtoolcache/windows/Ruby/3.0.3/x64/bin/$(RUBY_BASE_NAME)
	--with-rdiscount-dir
	--without-rdiscount-dir
	--with-rdiscount-include
	--without-rdiscount-include=${rdiscount-dir}/include
	--with-rdiscount-lib
	--without-rdiscount-lib=${rdiscount-dir}/lib
C:/hostedtoolcache/windows/Ruby/3.0.3/x64/lib/ruby/3.0.0/mkmf.rb:755:in `Integer': can't convert nil into Integer (TypeError)
	from C:/hostedtoolcache/windows/Ruby/3.0.3/x64/lib/ruby/3.0.0/mkmf.rb:755:in `block in try_constant'
	from C:/hostedtoolcache/windows/Ruby/3.0.3/x64/lib/ruby/3.0.0/mkmf.rb:419:in `popen'
	from C:/hostedtoolcache/windows/Ruby/3.0.3/x64/lib/ruby/3.0.0/mkmf.rb:419:in `block in xpopen'
	from C:/hostedtoolcache/windows/Ruby/3.0.3/x64/lib/ruby/3.0.0/mkmf.rb:331:in `open'
	from C:/hostedtoolcache/windows/Ruby/3.0.3/x64/lib/ruby/3.0.0/mkmf.rb:412:in `xpopen'
	from C:/hostedtoolcache/windows/Ruby/3.0.3/x64/lib/ruby/3.0.0/mkmf.rb:754:in `try_constant'
	from C:/hostedtoolcache/windows/Ruby/3.0.3/x64/lib/ruby/3.0.0/mkmf.rb:1366:in `block in check_sizeof'
	from C:/hostedtoolcache/windows/Ruby/3.0.3/x64/lib/ruby/3.0.0/mkmf.rb:971:in `block in checking_for'
	from C:/hostedtoolcache/windows/Ruby/3.0.3/x64/lib/ruby/3.0.0/mkmf.rb:361:in `block (2 levels) in postpone'
	from C:/hostedtoolcache/windows/Ruby/3.0.3/x64/lib/ruby/3.0.0/mkmf.rb:331:in `open'
	from C:/hostedtoolcache/windows/Ruby/3.0.3/x64/lib/ruby/3.0.0/mkmf.rb:361:in `block in postpone'
	from C:/hostedtoolcache/windows/Ruby/3.0.3/x64/lib/ruby/3.0.0/mkmf.rb:331:in `open'
	from C:/hostedtoolcache/windows/Ruby/3.0.3/x64/lib/ruby/3.0.0/mkmf.rb:357:in `postpone'
	from C:/hostedtoolcache/windows/Ruby/3.0.3/x64/lib/ruby/3.0.0/mkmf.rb:970:in `checking_for'
	from C:/hostedtoolcache/windows/Ruby/3.0.3/x64/lib/ruby/3.0.0/mkmf.rb:1365:in `check_sizeof'
	from extconf.rb:11:in `block in sized_int'
	from extconf.rb:11:in `each'
	from extconf.rb:11:in `find'
	from extconf.rb:11:in `sized_int'
	from extconf.rb:15:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  C:/hostedtoolcache/windows/Ruby/3.0.3/x64/lib/ruby/gems/3.0.0/extensions/x64-mingw32/3.0.0/rdiscount-2.2.0.2/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in C:/hostedtoolcache/windows/Ruby/3.0.3/x64/lib/ruby/gems/3.0.0/gems/rdiscount-2.2.0.2 for inspection.
Results logged to C:/hostedtoolcache/windows/Ruby/3.0.3/x64/lib/ruby/gems/3.0.0/extensions/x64-mingw32/3.0.0/rdiscount-2.2.0.2/gem_make.out
Error: Process completed with exit code 1.
```

### Repro steps

1. An Actions workflow which runs `gem install ronn` on a Windows Server 2022 runner, e.g.:
    ```
    name: CI
    on: [push, pull_request]
    
    jobs:
      build-windows:
        name: Build on Windows
        runs-on: windows-2022
        steps:
        - run: gem install ronn
          shell: bash
    ```

2. Note that the same workflow but with `runs-on: windows-2019` succeeds.
3. Also note that while our legacy CI job for the Git LFS project first runs the now-deprecated `actions/setup-ruby@v1` action, the problem can be seen without that step, as per the reproduction workflow script above.

**Comment by chrisd8088** [comment]
A few further notes:

- The actual build problem appears to stem not from the `ronn` gem itself but from Ruby's own build tooling, and specifically occurs when building one of ronn's dependencies, the RDiscount Markdown processor gem (https://github.com/davidfstr/rdiscount).

- We have experimented with first running the `ruby/setup-ruby@v1` action, as [recommended](https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-ruby), but while this does permit the `gem install` to succeed, it unfortunately installs a number of other tools like MSYS2 and [alters](https://github.com/ruby/setup-ruby/blob/0bb302e3c333be797c0a573524c3b70f2f18a97d/dist/index.js#L437-L455) the `PATH` such that a considerable number of our CI tests fail.
    - In turn that means that workflow steps with `shell: bash` don't run `C:\Program Files\Git\bin\bash.EXE` but `C:\msys64\usr\bin\bash.EXE` instead, with an environment that looks like:
        ```
        env:
          MSYS2_PATH_TYPE: inherit
          Path: C:\Program Files\MongoDB\Server\5.0\bin;C:\aliyun-cli;C:\vcpkg;C:\Program Files (x86)\NSIS\;C:\tools\zstd;C:\Program Files\Mercurial\;C:\hostedtoolcache\windows\stack\2.7.3\x64;C:\cabal\bin;C:\\ghcup\bin;C:\tools\ghc-9.2.1\bin;C:\Program Files\dotnet;C:\mysql\bin;C:\Program Files\R\R-4.1.2\bin\x64;C:\SeleniumWebDrivers\GeckoDriver;C:\Program Files (x86)\sbt\bin;C:\Program Files (x86)\GitHub CLI;C:\Program Files\Git\bin;C:\Program Files (x86)\pipx_bin;C:\hostedtoolcache\windows\go\1.16.13\x64\bin;C:\hostedtoolcache\windows\Python\3.9.10\x64\Scripts;C:\hostedtoolcache\windows\Python\3.9.10\x64;C:\tools\kotlinc\bin;C:\hostedtoolcache\windows\Java_Temurin-Hotspot_jdk\8.0.322-6\x64\bin;C:\npm\prefix;C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin;C:\ProgramData\kind;C:\Program Files\Microsoft\jdk-11.0.12.7-hotspot\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\dotnet\;C:\ProgramData\Chocolatey\bin;C:\Program Files\Docker;C:\Program Files\PowerShell\7\;C:\Program Files\Microsoft\Web Platform Installer\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\;C:\Program Files\Microsoft SQL Server\150\Tools\Binn\;C:\Program Files\nodejs\;C:\Program Files\LLVM\bin;C:\Program Files\OpenSSL\bin;C:\Strawberry\c\bin;C:\Strawberry\perl\site\bin;C:\Strawberry\perl\bin;C:\ProgramData\chocolatey\lib\pulumi\tools\Pulumi\bin;C:\Program Files\TortoiseSVN\bin;C:\Program Files\CMake\bin;C:\ProgramData\chocolatey\lib\maven\apache-maven-3.8.4\bin;C:\Program Files\Microsoft Service Fabric\bin\Fabric\Fabric.Code;C:\Program Files\Microsoft SDKs\Service Fabric\Tools\ServiceFabricLocalClusterManager;C:\Program Files\Git\cmd;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\Program Files\GitHub CLI\;c:\tools\php;C:\Program Files (x86)\sbt\bin;C:\SeleniumWebDrivers\ChromeDriver\;C:\SeleniumWebDrivers\EdgeDriver\;C:\Program Files\Amazon\AWSCLIV2\;C:\Program Files\Amazon\SessionManagerPlugin\bin\;C:\Program Files\Amazon\AWSSAMCLI\bin\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Users\runneradmin\.dotnet\tools;C:\Users\runneradmin\.cargo\bin;C:\Users\runneradmin\AppData\Local\Microsoft\WindowsApps
        ```
    - As a result of these `PATH` changes the Git which is found and run by default is `C:\Program Files\Git\bin\git.exe` instead of `C:\Program Files\Git\mingw64\bin\git.exe`.  That might be OK for us, as they may even be the same binary.
    - However, we then need to test the `git-lfs.exe` binary which our CI jobs compile.  Our CI suite prepends the location of the compiled `git-lfs.exe` binary to the `PATH` environment variable, and then runs `git lfs`, which should invoke the default Git binary, which then looks for a `git-lfs` binary in the `PATH` locations and executes it.  That's how Git looks up all of its own individual programs, such as `git-commit`, `git-merge`, etc.  This all works normally on other platforms (Linux, macOS) and on Windows Server 2019 runners.
    - But seemingly as a result of the introduction of MSYS2 by the `ruby/setup-ruby@v1` action, when Git looks through the set of `PATH` locations, it appears to get only the `PATH` as defined above, not as it has been adjusted by our CI scripts.  This may be due to the way MSYS2 can [reset](https://github.com/msys2/MSYS2-packages/blob/85d54481612aea963af4ce822a6d9d98cb2a189b/filesystem/profile#L40-L44) `PATH`.  Supposedly this behaviour is changed by setting `MSYS2_PATH_TYPE` to `inherit`, but that may not be taking effect (see, for instance, msys2/MSYS2-packages#2140).  The consequence is that the default Git LFS binary is run, not the one compiled by our CI job, so of course the test suite then fails.
- We don't particularly care if we need to run `ruby/setup-ruby@v1` or not to get `get install ronn` to run to completion, but we do need a working environment afterwards and not one which overwrites `PATH` in a way that can't be undone by the usual ability to prepend paths, i.e., `PATH=/new/path:$PATH`.  That breaks all kinds of assumptions throughout our test suite.

**Comment by al-cheb** [comment]
Hello @chrisd8088 ,
We will take  a look at it.

**Comment by mikhailkoliada** [comment]
@chrisd8088 hello!

the failure happens just because we are having different versions of ruby be default on win19 and win22 (2.5 and 3.0 respectively). `setup-ruby` indeed helps mitigating this, but given that you can't use it at the moment the most suitable workarond for you would be changing the default `$PATH` value and put there a ruby version you wish, say, by executing the  [same](https://github.com/actions/virtual-environments/blob/main/images/win/scripts/Installers/Install-Ruby.ps1#L89) function as we do in your pipeline's runtime.

**Comment by chrisd8088** [comment]
Thanks for the advice and info, @mikhailkoliada!  That's helped us formulate an alternative approach; I suspect we will stop using ronn altogether and replace it with either Pandoc or Asciidoctor.  It'll be a bit more work on our end but as ronn appears to be unmaintained at this point, I think this is probably the right direction.  Thanks again!
