### ISSUE TITLE
macOS Monterey 12.3 will remove system-provided python environment

### ISSUE THREAD

**Issue by n8felton** [actions/virtual-environments#5101]
### Description

Per https://developer.apple.com/documentation/macos-release-notes/macos-12_3-release-notes, Apple is deprecating Python 2.7 with macOS Monterey 12.3 and will no longer be bundling a system provided version of Python.

> Python
> Deprecations
> Python 2.7 was removed from macOS in this update. Developers should use Python 3 or an alternative language instead. (39795874)

I noticed there are a number of python scripts used to provision macOS virtual environments that will likely be impacted by this.

A few quick examples:
https://github.com/actions/virtual-environments/blob/8432c6614bcaa7c8c9ea1a02c0f6ee706fe0a347/images/macos/provision/configuration/autologin.sh
https://github.com/actions/virtual-environments/blob/8432c6614bcaa7c8c9ea1a02c0f6ee706fe0a347/images/macos/provision/bootstrap-provisioner/kcpassword.py
https://github.com/actions/virtual-environments/blob/8432c6614bcaa7c8c9ea1a02c0f6ee706fe0a347/images/macos/provision/configuration/configure-hostname.sh

Related: #3649

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [X] macOS 10.15
- [X] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

(doesn't exist yet)

### Repro steps

(doesn't exist yet)

**Comment by al-cheb** [comment]
Hello @n8felton ,
Thank you for bring it up. We will take a look at it.

**Comment by al-cheb** [comment]
@n8felton, Thank you. All scripts have been migrated to python3.
