### ISSUE TITLE
"Architecture" is missing in OS info

### ISSUE THREAD

**Issue by am11** [actions/virtual-environments#5108]
### Description

For sake of completeness, please call out the architecture of operating system the job is running on. It will make this particular section of the logs more self-explanatory for the reader, and save them from looking for arch related info elsewhere.

### Virtual environments affected

- [X] Ubuntu 18.04
- [X] Ubuntu 20.04
- [X] macOS 10.15
- [X] macOS 11
- [X] Windows Server 2016
- [X] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

This issue is present in all VEs.

### Expected behavior

Excerpt from AzDO logs:
```diff
...
##[group]Operating System
macOS
+ x86_64
11.6.3
20G415
...
```
or
```diff
...
##[group]Operating System
- macOS
+ macOS (x86_64)
11.6.3
20G415
...
```

### Actual behavior

It is missing from:
linux https://github.com/actions/virtual-environments/blob/3c2f1c6350b3d34a557f12f62e3ee47a839ea401/images/linux/scripts/installers/preimagedata.sh#L23
macOS https://github.com/actions/virtual-environments/blob/3c2f1c6350b3d34a557f12f62e3ee47a839ea401/images/macos/provision/configuration/preimagedata.sh#L25
and win https://github.com/actions/virtual-environments/blob/3c2f1c6350b3d34a557f12f62e3ee47a839ea401/images/win/scripts/Installers/Update-ImageData.ps1#L30

### Repro steps

1. Create a basic workflow on GitHub Actions or AzDO.
2. Try to determine OS architecture by looking at `Set up job > Operating System` in GitHub Actions or `Initialize Job > Operating System` in AzDO.

**Comment by miketimofeev** [comment]
Hi @am11!
All the runners have `x86_64` architecture at the moment. We will come back to this once macOS M1 runners are publicly available. 
I'm going to close the issue.
Thank you!
