### ISSUE TITLE
Update/Add [tool name]

### ISSUE THREAD

**Issue by yanz-androidify** [actions/virtual-environments#511]
**Tool information**
- Tool name: 
- Add or update? 
- Desired version: 
- Approximate size: 
- If this is an add request:
  - Brief description of tool: 
  - URL for tool's homepage: 

**Area for Triage**:

**Question, Bug, or Feature?**:

**Virtual environments affected**
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [x] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Can this tool be installed during the build?**

**Are you willing to submit a PR?**

**Comment by yanz-androidify** [comment]
#501

**Comment by miketimofeev** [comment]
@yanz-androidify could you provide additional information about what tool should be added(and change the title as well)?

**Comment by miketimofeev** [comment]
No information provided
