### ISSUE TITLE
[macOS] Update MSBuild to 16.10.2

### ISSUE THREAD

**Issue by andrejohansson** [actions/virtual-environments#5110]
### Tool name

msbuild

### Tool license

mit

### Add or update?

- [ ] Add
- [X] Update

### Desired version

Atleast 16.10.2 (due to bug in current 16.10.1)

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [X] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Can this tool be installed during the build?

```bash
For more informatino, see:
https://developercommunity.visualstudio.com/t/error-xabld7024-sharing-violation-on-path-due-to-o/1671090?from=email&moreInfo=true&viewtype=all
```

**Comment by miketimofeev** [comment]
Hi @andrejohansson!
`MSBuild` comes along with mono bundled with Visual Studio so I'm afraid nothing we can do here rather than waiting for the new mono version.

**Comment by nikolai-frolov** [comment]
@andrejohansson you can use [setup-msbuild](https://github.com/marketplace/actions/setup-msbuild) as a workaround until the Mono package update. I'm going to close the issue, feel free to contact us if you have any objections.

**Comment by andrejohansson** [comment]
Ok, thats unfortunate for me! Thank you for your quick response and input, will look into your recommendation.
