### ISSUE TITLE
Visual Studio 4 Mac 8.10.18 (current running on VM macOS 11) is broken running Xamarin.iOS app with touch gestures. Need upgrade

### ISSUE THREAD

**Issue by haavamoa** [actions/virtual-environments#5120]
### Description

Hi, the past days we have experienced issues with our Xamarin.iOS app version where touch gestures are not working in our app. This was resolved in Visual Studio 4 Mac 8.10.19. The problem is that our VMs that build the app is running macOS11 which has 8.10.18, so we are unable to deliver our app with this critical error.

I can't seem to find any issue regarding this anywhere, but we do see that the new version are handling DisposableObjects differently from Xamarin.iOS:
https://docs.microsoft.com/en-us/visualstudio/releasenotes/vs2019-mac-relnotes#--visual-studio-2019-for-mac-version-81019-810192

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [X] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

20220212.1

### Expected behavior

Touch gestures working in iOS app.

### Actual behavior

Touch gestures does not work in iOS app.

### Repro steps

1. Create a Xamarin.Forms app, a view element with a gesture recogniser that changes something in the page.
2. Run the app locally with Visual Studio 4 Mac latest version, observe that it works.
3. Run the app through azure pipeline running Visual Studio 4 Mac 8.10.18 and download the app, observe that it does not work.

**Comment by haavamoa** [comment]
I can see that you have released pre-releases of new macOS11 that runs 8.10.19, but I am unable to understand how I can use that in my azure DevOps pipeline. If you could please provide me some links on how to do that, it would be appreciated so we can deliver our iOS app running our pipeline.

**Comment by nikolai-frolov** [comment]
Hello, you are correct, new macOS-11 image with 8.10.19.2 Visual Studio for Mac will be deployed during this week to all environments. After that you will be able to use it as usual.

**Comment by miketimofeev** [comment]
@haavamoa VS4mac has been updated.
I'm going to close the issue. Feel free to contact us if you have any concerns.
Thank you!

**Comment by haavamoa** [comment]
Seems like the bug still persists after update.

From initialise step in pipeline:
![image](https://user-images.githubusercontent.com/2527084/156124340-b8c3b375-a56a-4839-ad48-1b4646435b6b.png)

**Comment by haavamoa** [comment]
No difference if I selected **15.6** of Xamarin.iOS. Help!

**Comment by nikolai-frolov** [comment]
@haavamoa looking at the Agent name and Agent version, you use some self-hosted agent which is not supported by our team. Please contact to your organization administrator who owns these agents.

**Comment by haavamoa** [comment]
You can close it :)
