### ISSUE TITLE
Add Ubuntu 21.10 as runner option "ubuntu-tip"

### ISSUE THREAD

**Issue by JonKohler** [actions/virtual-environments#5122]
### Tool name

Ubuntu 21.10

### Tool license

na

### Add or update?

- [X] Add
- [ ] Update

### Desired version

21.10

### Brief description of tool

The current GitHub hosted runner option is Ubuntu 20.04, which for most things is just fine; however, some projects depend on having a newer kernel available in the runner. Given the long-term nature of 20.04, they've picked/stuck with kernel 5.4 as their long-term strategy. 

There are a few ways around this, such as installing the linux-oem package which would bring us up to a newer kernel; however, a much better, more broadly applicable option would simply be to provide an option like `ubuntu-tip` so that GitHub actions consumers can test their code on the most recent Ubuntu release. At the time of writing, that is Ubuntu 21.10, which has kernel 5.13 as well as all of the usual latest-and-greatest userspace packages.

This would allow a smoother onramp going in between ubuntu long-term releases as well.

### URL for tool's homepage

https://wiki.ubuntu.com/Releases

### Virtual environments affected

- [ ] Ubuntu 18.04
- [X] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Are you willing to submit a PR?

sure, if this sort of thing is user PR-able

**Comment by miketimofeev** [comment]
Hi @JonKohler!
We support [only LTS versions](https://github.com/actions/virtual-environments/blob/main/docs/software-and-images-guidelines.md#software-and-images-support-policy) so the next Ubuntu image available will be 22.04 LTS.
I'm going to close the issue. Feel free to contact us if you have any concerns.
Thank you!
