### ISSUE TITLE
Install-Haskell.ps1 verification is failing

### ISSUE THREAD

**Issue by balajipunniyakoadi** [actions/virtual-environments#5123]
### Description

https://github.com/actions/virtual-environments/blob/main/images/win/windows2016.json#L232

"{{ template_dir }}/scripts/Installers/Install-Haskell.ps1",

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [X] Windows Server 2016
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

[459680](https://github.com/459680) [Updating readme file for win16 version 20220131.1](https://github.com/actions/virtual-environments/commit/030286659efd040e1fd221eb35189ca1d89eea2d)

### Expected behavior

This step has to pass after the successful installation

### Actual behavior

This step has failed after the successful installation

### Repro steps

Step 1: Create a Image with Win2016, you can repro the issue

**Comment by Chaouki-Tiouassiouine** [comment]
Indeed for Windows 2019 it is still occuring:

vhd: Running tests from 'C:\image\Tests\Haskell.Tests.ps1'
    vhd: Describing Haskell
    vhd:   [+] GHCUP_INSTALL_BASE_PREFIX environment variable exists 536ms (294ms|243ms)
    vhd:   [+] GHCUP_MSYS2 environment variable exists 4ms (2ms|2ms)
    vhd:   [+] Accurate 3 versions of GHC are installed 490ms (484ms|5ms)
    vhd:   [+] GHC 8.10.7 is installed 2.08s (2.08s|4ms)
    vhd:   [+] GHC 9.0.2 is installed 2.09s (2.08s|3ms)
    vhd:   [+] GHC 9.2.1 is installed 2s (1.99s|11ms)
    vhd:   [+] GHC 9.2.1 is the default version and should be the latest installed 86ms (83ms|2ms)
    vhd:   [+] Cabal is installed 133ms (131ms|2ms)
    vhd:   [-] cabal config was modified and exists 219ms (215ms|4ms)
    vhd:    Expected path 'C:\cabal' to exist, but it did not exist.
    vhd:    at $env:CABAL_DIR | Should -Exist, C:\image\Tests\Haskell.Tests.ps1:53
    vhd:    at <ScriptBlock>, C:\image\Tests\Haskell.Tests.ps1:53
    vhd:   [+] ghcup is installed 53ms (51ms|2ms)
==> vhd: Test run has failed
==> vhd: At C:\Program Files\WindowsPowerShell\Modules\ImageHelpers\TestsHelpers.ps1:73 char:9
    vhd: Tests completed in 11.69s
==> vhd: +         throw "Test run has failed"
    vhd: Tests Passed: 9, Failed: 1, Skipped: 0 NotRun: 0

**Comment by al-cheb** [comment]
@Chaouki-Tiouassiouine , @balajipunniyakoadi , Please always use `main` branch.

https://github.visualstudio.com/virtual-environments/_build/results?buildId=122992&view=logs&j=011e1ec8-6569-5e69-4f06-baf193d1351e&t=5431112d-2b61-5a5f-7042-ef698f761043




```
    vhd: Describing Haskell
    vhd:   [+] GHCUP_INSTALL_BASE_PREFIX environment variable exists 461ms (233ms|228ms)
    vhd:   [+] GHCUP_MSYS2 environment variable exists 3ms (1ms|2ms)
    vhd:   [+] Accurate 3 versions of GHC are installed 404ms (400ms|4ms)
    vhd:   [+] GHC 8.10.7 is installed 53ms (50ms|3ms)
    vhd:   [+] GHC 9.0.2 is installed 48ms (46ms|2ms)
    vhd:   [+] GHC 9.2.1 is installed 66ms (64ms|2ms)
    vhd:   [+] GHC 9.2.1 is the default version and should be the latest installed 38ms (37ms|1ms)
    vhd:   [+] Cabal is installed 82ms (80ms|1ms)
    vhd:   [+] cabal folder does not exist 45ms (44ms|1ms)
    vhd:   [+] CABAL_DIR environment variable exists 10ms (9ms|1ms)
    vhd:   [+] ghcup is installed 112ms (28ms|83ms)
```
