### ISSUE TITLE
dacfx test getting failed in windows 2019 deployment

### ISSUE THREAD

**Issue by prabhusirpi** [actions/virtual-environments#5124]
### Description

Hi All,

While running the pipeline execution, we are getting error as Expected path 'C:\Program Files\Microsoft SQL Server\130\Tools\Binn\SqlLocalDB.exe' do not exist. Its for windows 2019 deployment and it was working fine earlier, is there any path modification needs to be done in the [Tools.Tests.ps1] script?

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [X] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

[Tools.Tests.ps1](https://github.com/actions/virtual-environments/blob/6865a4ccfe6c5bcf5ac3a96c4eb84d035136903c/images/win/scripts/Tests/Tools.Tests.ps1)

### Repro steps

Hi All,

While running the pipeline execution, we are getting error as Expected path 'C:\Program Files\Microsoft SQL Server\130\Tools\Binn\SqlLocalDB.exe' do not exist. Its for windows 2019 deployment and it was working fine earlier, is there any path modification needs to be done in the [Tools.Tests.ps1] script?

**Comment by al-cheb** [comment]
@prabhusirpi , Nightly build was successful - https://github.visualstudio.com/virtual-environments/_build/results?buildId=122992&view=logs&j=011e1ec8-6569-5e69-4f06-baf193d1351e&t=5431112d-2b61-5a5f-7042-ef698f761043

```
   vhd: Running tests from 'C:\image\Tests\Tools.Tests.ps1'
    vhd: Describing DACFx
    vhd:   [+] DACFx 889ms (693ms|196ms)
    vhd:   [+] SqlLocalDB 4ms (3ms|1ms)
    vhd: Tests completed in 4.49s
    vhd: Tests Passed: 2, Failed: 0, Skipped: 0 NotRun: 42
```
Please always use the `main` branch to build an image.
