### ISSUE TITLE
Update/Add Microsoft.VisualStudio.Component.VC.Redist.MSM

### ISSUE THREAD

**Issue by Hoikas** [actions/virtual-environments#5143]
### Tool name

Microsoft.VisualStudio.Component.VC.Redist.MSM

### Tool license

Unknown

### Add or update?

- [X] Add
- [ ] Update

### Desired version

Whatever the VS installer provides

### Brief description of tool

The windows-2019 image includes Microsoft.VisualStudio.Component.VC.Redist.MSM for Visual Studio 2019, however, the windows-2022 image does not have the corresponding component for Visual Studio 2022. This was a nasty surprise when I tried to switch my workflows to windows-2022. It is needed to build Windows installers for C++ projects.

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [X] Windows Server 2022

**Comment by miketimofeev** [comment]
Hi @Hoikas!
We will add the component and deploy the new image next week. Until then you can use the following powershell snippet to install the component in runtime
```pwsh
Set-Location "C:\Program Files (x86)\Microsoft Visual Studio\Installer\"
$InstallPath = "C:\Program Files\Microsoft Visual Studio\2022\Enterprise"
$componentsToAdd = @(
  "Microsoft.VisualStudio.Component.VC.Redist.MSM"
)
[string]$workloadArgs = $componentsToAdd | ForEach-Object {" --add " +  $_}
$Arguments = ('/c', "vs_installer.exe", 'modify', '--installPath', "`"$InstallPath`"",$workloadArgs, '--quiet', '--norestart', '--nocache')
$process = Start-Process -FilePath cmd.exe -ArgumentList $Arguments -Wait -PassThru -WindowStyle Hidden
if ($process.ExitCode -eq 0)
{
    Write-Host "components have been successfully added"
}
else
{
    Write-Host "components were not installed"
    exit 1
}
```

**Comment by KrisWragg** [comment]
@Hoikas you might want to consider switching to using the redistributable installers such as vc_redist.x64.exe

Merge modules usage is deprecated:
https://docs.microsoft.com/en-us/cpp/windows/redistributing-components-by-using-merge-modules?view=msvc-170

**Comment by Hoikas** [comment]
Thanks for the quick response everyone. I would really like to use the standard vc_redist, but it can't be trivially executed from an .msi (because vcredist runs an msi itself). I may, at some point, have to find the time to make a coordinating installer wrapper to do that 😞.

**Comment by KrisWragg** [comment]
@Hoikas totally understand :) Possibly the easiest option is a WiX bundle project that will wrap your msi and any other installers into a single .exe. It is installed as part of the default scripts for the virtual machine build image.

https://wixtoolset.org/documentation/manual/v3/bundle/

**Comment by slonopotamus** [comment]
> We will add the component and deploy the new image next week

Are we there yet?

**Comment by miketimofeev** [comment]
@slonopotamus @Hoikas sorry for the delay due to unpredictable circumstances. The changes are merged now and will be deployed next week.

**Comment by igorboskovic3** [comment]
@slonopotamus @Hoikas 

The new Windows 2022 image have been deployed
We added Microsoft.VisualStudio.Component.VC.Redist.MSM to Windows 2022
https://github.com/actions/virtual-environments/blob/main/images/win/Windows2022-Readme.md

![image](https://user-images.githubusercontent.com/68074361/162416331-f592c4a2-77a5-4205-b3fa-9f4950f5d496.png)

Sorry for the delay due to unpredictable circumstances
