### ISSUE TITLE
Building Xamarin.Forms app isn't working since VS 2022 is used

### ISSUE THREAD

**Issue by florian-berger** [actions/virtual-environments#5154]
### Description

A few days ago, building our Xamarin.Forms application via Azure Pipeline works like a charm.
But a few days ago, the build was no longer possible without any code changes.

I figured out that the problem is caused by the new Visual Studio version that is used. We are using the `windows-latest` image.

The definition in the yml files looks like the following:
```
- task: XamarinAndroid@1
  displayName: 'Build Android app'
  inputs:
    projectFile: '**/*Droid*.csproj'
    outputDirectory: '$(outputDirectory)'
    configuration: '$(buildConfiguration)'
    msbuildArguments: '-restore -t:SignAndroidPackage -p:AndroidPackageFormat=aab -p:AndroidKeyStore=True -p:AndroidSigningKeyStore=$(keystore.secureFilePath) -p:AndroidSigningStorePass=$(keystorePassword) -p:AndroidSigningKeyAlias="our-alias-name" -p:AndroidSigningKeyPass=$(keystorePassword)'
```

Log of the failed build:

> _CompileToDalvik:
  C:\Program Files\Microsoft\jdk-11.0.12.7-hotspot\bin\java.exe -Xmx8G -classpath "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Xamarin\Android\r8.jar" com.android.tools.r8.D8 --release --min-api 24 --output obj\ReleaseApp\100\android\bin\ --lib "C:\Program Files (x86)\Android\android-sdk\platforms\android-30\android.jar" obj\ReleaseApp\100\android\bin\classes.zip "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\ReferenceAssemblies\Microsoft\Framework\MonoAndroid\v10.0\mono.android.jar" "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Xamarin\Android\\java_runtime.jar" C:\Users\VssAdministrator\.nuget\packages\xamarin.androidx.annotation\1.2.0.1\buildTransitive\monoandroid90\..\..\jar\androidx.annotation.annotation.jar C:\Users\VssAdministrator\.nuget\packages\xamarin.androidx.collection\1.1.0.8\buildTransitive\monoandroid90\..\..\jar\androidx.collection.collection.jar C:\Users\VssAdministrator\.nuget\packages\xamarin.androidx.lifecycle.common\2.3.1.1\buildTransitive\monoandroid90\..\..\jar\androidx.lifecycle.lifecycle-common.jar C:\Users\VssAdministrator\.nuget\packages\xamarin.androidx.arch.core.common\2.1.0.9\buildTransitive\monoandroid90\..\..\jar\androidx.arch.core.core-common.jar C:\Users\VssAdministrator\.nuget\packages\xamarin.androidx.constraintlayout.core\1.0.0\buildTransitive\monoandroid90\..\..\jar\androidx.constraintlayout.constraintlayout-core.jar C:\Users\VssAdministrator\.nuget\packages\xamarin.androidx.concurrent.futures\1.1.0.3\buildTransitive\monoandroid90\..\..\jar\androidx.concurrent.concurrent-futures.jar obj\ReleaseApp\100\androidx\jl\8888b682-9e0e-47ba-9ef5-63eefe81d5bc.jar obj\ReleaseApp\100\lp\10\jl\__reference__pass-v1.2.0.jar obj\ReleaseApp\100\lp\10\jl\__reference__sdk-v1.0.0.jar obj\ReleaseApp\100\lp\100\jl\classes.jar obj\ReleaseApp\100\lp\101\jl\classes.jar obj\ReleaseApp\100\lp\102\jl\classes.jar obj\ReleaseApp\100\lp\103\jl\classes.jar obj\ReleaseApp\100\lp\104\jl\classes.jar obj\ReleaseApp\100\lp\105\jl\classes.jar obj\ReleaseApp\100\lp\106\jl\classes.jar obj\ReleaseApp\100\lp\107\jl\classes.jar obj\ReleaseApp\100\lp\108\jl\classes.jar obj\ReleaseApp\100\lp\109\jl\classes.jar obj\ReleaseApp\100\lp\110\jl\classes.jar obj\ReleaseApp\100\lp\111\jl\classes.jar obj\ReleaseApp\100\lp\112\jl\classes.jar obj\ReleaseApp\100\lp\113\jl\classes.jar obj\ReleaseApp\100\lp\114\jl\classes.jar obj\ReleaseApp\100\lp\115\jl\classes.jar obj\ReleaseApp\100\lp\116\jl\classes.jar obj\ReleaseApp\100\lp\117\jl\classes.jar obj\ReleaseApp\100\lp\118\jl\classes.jar obj\ReleaseApp\100\lp\119\jl\classes.jar obj\ReleaseApp\100\lp\120\jl\classes.jar obj\ReleaseApp\100\lp\121\jl\classes.jar obj\ReleaseApp\100\lp\122\jl\classes.jar obj\ReleaseApp\100\lp\124\jl\classes.jar obj\ReleaseApp\100\lp\125\jl\classes.jar obj\ReleaseApp\100\lp\126\jl\classes.jar obj\ReleaseApp\100\lp\6\jl\formsviewgroup.jar obj\ReleaseApp\100\lp\79\jl\classes.jar obj\ReleaseApp\100\lp\80\jl\classes.jar obj\ReleaseApp\100\lp\81\jl\classes.jar obj\ReleaseApp\100\lp\82\jl\classes.jar obj\ReleaseApp\100\lp\83\jl\classes.jar obj\ReleaseApp\100\lp\84\jl\classes.jar obj\ReleaseApp\100\lp\85\jl\classes.jar obj\ReleaseApp\100\lp\86\jl\classes.jar obj\ReleaseApp\100\lp\87\jl\classes.jar obj\ReleaseApp\100\lp\88\jl\classes.jar obj\ReleaseApp\100\lp\89\jl\classes.jar obj\ReleaseApp\100\lp\90\jl\classes.jar obj\ReleaseApp\100\lp\91\jl\classes.jar obj\ReleaseApp\100\lp\92\jl\classes.jar obj\ReleaseApp\100\lp\93\jl\classes.jar obj\ReleaseApp\100\lp\94\jl\classes.jar obj\ReleaseApp\100\lp\95\jl\classes.jar obj\ReleaseApp\100\lp\96\jl\classes.jar obj\ReleaseApp\100\lp\97\jl\classes.jar obj\ReleaseApp\100\lp\98\jl\classes.jar obj\ReleaseApp\100\lp\99\jl\classes.jar 
  Error: java.lang.ArrayIndexOutOfBoundsException: Index 4 out of bounds for length 4
  Compilation failed
##[error]C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.D8.targets(79,5): Error : java.lang.ArrayIndexOutOfBoundsException :  Index 4 out of bounds for length 4
C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.D8.targets(79,5): error : java.lang.ArrayIndexOutOfBoundsException :  Index 4 out of bounds for length 4 [D:\a\1\s\MobileApp\MobileApp\MobileApp.Android\MobileApp.Android.csproj]
Done Building Project "D:\a\1\s\MobileApp\MobileApp\MobileApp.Android\MobileApp.Android.csproj" (SignAndroidPackage;PackageForAndroid target(s)) -- FAILED.
> 
> Build FAILED.

As the XamarinAndroid task has no possibility to specify the used VS Version, we are not able to publish a new version of our app!

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

- Agent name: 'Hosted Agent'
- Agent machine name: 'WIN-GHH09QJNS8O'
- Current agent version: '2.200.2'
- Operating System
  - Microsoft Windows Server 2022
  - 10.0.20348
  - Datacenter
- Virtual Environment
  - Environment: windows-2022
  - Version: 20220220.1
  - Included Software: https://github.com/actions/virtual-environments/blob/win22/20220220.1/images/win/Windows2022-Readme.md
  - Image Release: https://github.com/actions/virtual-environments/releases/tag/win22%2F20220220.1
- Virtual Environment Provisioner
  - 1.0.0.0-main-20220215-1
- Current image version: '20220220.1'

### Repro steps

Try to build your Xamarin.Forms application for Android

**Comment by mikhailkoliada** [comment]
@florian-berger Thanks, we will take a look!

**Comment by vsafonkin** [comment]
> Repro steps
> Try to build your Xamarin.Forms application for Android

Hi @florian-berger, I have successful build of Xamarin.Forms application for Android on the Windows-2022 hosted-agent:
https://dev.azure.com/v-vsafonkin/v-vsafonkin/_build/results?buildId=7

Repository: https://github.com/vsafonkin/MyWeather.Forms

Maybe you can provide some repro steps of this issue?

**Comment by vsafonkin** [comment]
@florian-berger, I'm going to close this issue, feel free to reopen it if you have any concerns, thanks!
