### ISSUE TITLE
SetX command fail with invalid syntax

### ISSUE THREAD

**Issue by samrobillard** [actions/virtual-environments#516]
**Describe the bug**
The build fails after the first few minutes with this error:

==> image: ERROR: Invalid syntax.
    image: SUCCESS: Specified value was saved.
==> image: Type "SETX /?" for usage.

**Question, Bug, or Feature?**: 
Bug

**Virtual environments affected**
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [X] Windows Server 2019

**Expected behavior**
Image builds successfully

**Actual behavior**
Running packer build fails after these commands:

==> image: Provisioning with Powershell...
2020/03/06 20:00:01 packer.exe plugin: Found command: setx ImageVersion 2020.03.06 /m
2020/03/06 20:00:01 packer.exe plugin: Found command: setx ImageOS  /m
2020/03/06 20:00:01 packer.exe plugin: Opening C:\Users\svc_vsts\AppData\Local\Temp\powershell-provisioner984693383 for reading
==> image: Provisioning with powershell script: C:\Users\svc_vsts\AppData\Local\Temp\powershell-provisioner984693383
2020/03/06 20:00:01 packer.exe plugin: Uploading env vars to c:/Windows/Temp/packer-ps-env-vars-5e62a779-0f54-d85c-e71f-90c14828f960.ps1
2020/03/06 20:00:01 packer.exe plugin: [INFO] 70 bytes written for 'uploadData'
2020/03/06 20:00:01 [INFO] 70 bytes written for 'uploadData'
2020/03/06 20:00:01 packer.exe plugin: Uploading file to 'c:/Windows/Temp/packer-ps-env-vars-5e62a779-0f54-d85c-e71f-90c14828f960.ps1'
2020/03/06 20:00:02 packer.exe plugin: #< CLIXML
2020/03/06 20:00:02 packer.exe plugin: <Objs Version="1.1.0.1" xmlns="http://schemas.microsoft.com/powershell/2004/04"><Obj S="progress" RefId="0"><TN RefId="0"><T>System.Management.Automation.PSCustomObject</T><T>System.Object</T></TN><MS><I64 N="SourceId">1</I64><PR N="Record"><AV>Preparing modules for first use.</AV><AI>0</AI><Nil /><PI>-1</PI><PC>-1</PC><T>Completed</T><SR>-1</SR><SD> </SD></PR></MS></Obj></Objs>#< CLIXML
2020/03/06 20:00:02 packer.exe plugin: [INFO] 49 bytes written for 'uploadData'
2020/03/06 20:00:02 [INFO] 49 bytes written for 'uploadData'
2020/03/06 20:00:02 packer.exe plugin: <Objs Version="1.1.0.1" xmlns="http://schemas.microsoft.com/powershell/2004/04"><Obj S="progress" RefId="0"><TN RefId="0"><T>System.Management.Automation.PSCustomObject</T><T>System.Object</T></TN><MS><I64 N="SourceId">1</I64><PR N="Record"><AV>Preparing modules for first use.</AV><AI>0</AI><Nil /><PI>-1</PI><PC>-1</PC><T>Completed</T><SR>-1</SR><SD> </SD></PR></MS></Obj></Objs>Uploading file to 'c:/Windows/Temp/script-5e62a779-5b71-90d0-715e-e34ad06a2b6f.ps1'
2020/03/06 20:00:03 packer.exe plugin: #< CLIXML
2020/03/06 20:00:03 packer.exe plugin: <Objs Version="1.1.0.1" xmlns="http://schemas.microsoft.com/powershell/2004/04"><Obj S="progress" RefId="0"><TN RefId="0"><T>System.Management.Automation.PSCustomObject</T><T>System.Object</T></TN><MS><I64 N="SourceId">1</I64><PR N="Record"><AV>Preparing modules for first use.</AV><AI>0</AI><Nil /><PI>-1</PI><PC>-1</PC><T>Completed</T><SR>-1</SR><SD> </SD></PR></MS></Obj></Objs>#< CLIXML
2020/03/06 20:00:03 packer.exe plugin: <Objs Version="1.1.0.1" xmlns="http://schemas.microsoft.com/powershell/2004/04"><Obj S="progress" RefId="0"><TN RefId="0"><T>System.Management.Automation.PSCustomObject</T><T>System.Object</T></TN><MS><I64 N="SourceId">1</I64><PR N="Record"><AV>Preparing modules for first use.</AV><AI>0</AI><Nil /><PI>-1</PI><PC>-1</PC><T>Completed</T><SR>-1</SR><SD> </SD></PR></MS></Obj></Objs>[INFO] starting remote command: powershell -executionpolicy bypass "& { if (Test-Path variable:global:ProgressPreference){set-variable -name variable:global:ProgressPreference -value 'SilentlyContinue'};. c:/Windows/Temp/packer-ps-env-vars-5e62a779-0f54-d85c-e71f-90c14828f960.ps1; &'c:/Windows/Temp/script-5e62a779-5b71-90d0-715e-e34ad06a2b6f.ps1'; exit $LastExitCode }"
2020/03/06 20:00:04 [INFO] 51 bytes written for 'stderr'
2020/03/06 20:00:04 [INFO] 39 bytes written for 'stdout'
2020/03/06 20:00:04 packer.exe plugin: [INFO] command 'powershell -executionpolicy bypass "& { if (Test-Path variable:global:ProgressPreference){set-variable -name variable:global:ProgressPreference -value 'SilentlyContinue'};. c:/Windows/Temp/packer-ps-env-vars-5e62a779-0f54-d85c-e71f-90c14828f960.ps1; &'c:/Windows/Temp/script-5e62a779-5b71-90d0-715e-e34ad06a2b6f.ps1'; exit $LastExitCode }"' exited with code: 1
2020/03/06 20:00:04 packer.exe plugin: [INFO] RPC endpoint: Communicator ended with: 1
2020/03/06 20:00:04 [INFO] RPC client: Communicator ended with: 1
2020/03/06 20:00:04 [INFO] RPC endpoint: Communicator ended with: 1
2020/03/06 20:00:04 packer.exe plugin: [INFO] 39 bytes written for 'stdout'
    image:

**Comment by miketimofeev** [comment]
HI @samrobillard! What packer version do you use? Is that happens on the latest master? I'm asking because we haven't seen such kind of errors before and now.

**Comment by samrobillard** [comment]
Hi @miketimofeev, I'm using version 1.5.4.

**Comment by miketimofeev** [comment]
@samrobillard thanks for the update. Is that happens all the time or occasionally? We've built several Win19 VMs recently without any issues.

**Comment by samrobillard** [comment]
@miketimofeev it happens all the time. I wasn't able to build a single image.

**Comment by miketimofeev** [comment]
@samrobillard As far as I can see you've missed some variables because `ImageOS` is set to "win19" by default, but you have empty instead
`2020/03/06 20:00:01 packer.exe plugin: Found command: setx ImageOS /m`
could you please provide an exact `packer build` string?

**Comment by samrobillard** [comment]
Thank you! You are right, this variable was missing. I modify a bunch of thing in the json to build an image instead of a vhd. I'm running a build right now and I'll close the ticket if it goes past this step.

**Comment by samrobillard** [comment]
My issue is solved. Thank you @miketimofeev for your help.
