### ISSUE TITLE
Add wget2

### ISSUE THREAD

**Issue by MrAlex94** [actions/virtual-environments#5162]
### Tool name

wget2

### Tool license

GPLv3+

### Add or update?

- [X] Add
- [ ] Update

### Desired version

2.0.0

### Brief description of tool

GNU Wget2 is the successor of GNU Wget, a file and recursive website downloader.

Designed and written from scratch it wraps around libwget, that provides the basic functions needed by a web client.

Wget2 works multi-threaded and uses many features to allow fast operation.

In many cases Wget2 downloads much faster than Wget1.x due to HTTP2, HTTP compression, parallel connections and use of If-Modified-Since HTTP header.

### URL for tool's homepage

https://gitlab.com/gnuwget/wget2

### Provide a basic test case to validate the tool's functionality.

```bash
wget2 -r --tries=10 https://example.com/ -o log
```

### Virtual environments affected

- [X] Ubuntu 18.04
- [X] Ubuntu 20.04
- [X] macOS 10.15
- [X] macOS 11
- [X] Windows Server 2016
- [X] Windows Server 2019
- [X] Windows Server 2022

### Can this tool be installed during the build?

```bash
wget https://gnuwget.gitlab.io/wget2/wget2-latest.tar.gz
tar xf wget2-latest.tar.gz
cd wget2-*
./configure
make
make check
sudo make install
```

### Tool installation time in runtime

2 minutes (depending on system specs).

### Are you willing to submit a PR?

Maybe

**Comment by mikhailkoliada** [comment]
@MrAlex94 Hello, thanks for the report!

for ubuntu we mostly rely on the ubuntu repos, wget2 can be installed from there and it only takes about 18s (alongside with the `apt-get update` call.)

**Comment by maxim-lobanov** [comment]
We wouldn't like to pre-install this tool to images. Please consider installation in runtime as @mikhailkoliada suggested above
