### ISSUE TITLE
yq command hangs when using env() function (only on Azure agent Ubuntu Latest with yq > 4.19.1)

### ISSUE THREAD

**Issue by jojolb** [actions/virtual-environments#5165]
### Description

Since yq has been updated on Ubuntu20 to 4.20.2, a feature of this tool is not working anymore if ran from a pipeline agent.
Consider the following:
```bash
  export yamlcontent="a: bar"
  yq e -n -v ".foo += env(yamlcontent)"
```
If this is run from the agent through an Azure pipeline, the yq command will hang forever. It is not the case with yq 4.19.1.
If I run the same from example from my laptop on Ubuntu 20.04, or from inside a docker image on Ubuntu 20.04, then it runs perfectly

It is a bug because the yq tool works fine on other targets, it only fails on Azure pipeline runner.

See logs on Repro steps

### Virtual environments affected

- [ ] Ubuntu 18.04
- [X] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Starting: Initialize job
Agent name: 'Azure Pipelines 4'
Agent machine name: 'fv-az209-77'
Current agent version: '2.200.2'
Operating System
Ubuntu
20.04.3
LTS
Virtual Environment
Environment: ubuntu-20.04
**Version: 20220220.1**
Included Software: https://github.com/actions/virtual-environments/blob/ubuntu20/20220220.1/images/linux/Ubuntu2004-Readme.md
Image Release: https://github.com/actions/virtual-environments/releases/tag/ubuntu20%2F20220220.1
Virtual Environment Provisioner
Current image version: '20220220.1'
Agent running as: 'vsts'
Prepare build directory.
Set build variables.
Download all required tasks.
Downloading task: CmdLine (2.198.0)
Checking job knob settings.
   Knob: AgentToolsDirectory = /opt/hostedtoolcache Source: ${AGENT_TOOLSDIRECTORY} 
   Knob: AgentPerflog = /home/vsts/perflog Source: ${VSTS_AGENT_PERFLOG} 
Finished checking job knob settings.
Start tracking orphan processes.
Finishing: Initialize job

### Is it regression?

yes since 20220213.1 (yq was 4.19.1)

### Expected behavior

When following is run from an Azure pipeline:
```bash
export yamlcontent="a: bar"
yq e -n -v ".foo += env(yamlcontent)"
```

Expected output:
```yaml
foo:
  a: bar
```

### Actual behavior

The pipeline hangs forever until canceled

### Repro steps

1. Create a pipeline with the following:
```yaml
pool:
  vmImage: "ubuntu-latest"

stages:
  - stage: testYq
    pool:
      vmImage: "ubuntu-latest"
    jobs:
      - job: testYqJob
        steps:
          - task: CmdLine@2
            displayName: "Test yq"
            inputs:
              script: |
                set -x
                date
                sudo wget -q https://github.com/mikefarah/yq/releases/download/v4.19.1/yq_linux_amd64 -O /tmp/yq && sudo chmod +x /tmp/yq
                /tmp/yq --version
                export yamlcontent="with_version: 4.19.1"
                /tmp/yq e -n -v ".foo += env(yamlcontent)"
                echo "result: $?"
                date
                echo "Now test with yq 4.20.2"
                yq --version
                export yamlcontent="with_version: 4.20.2"
                yq e -n -v ".foo += env(yamlcontent)"
                echo "result: $?"
                date           
  ```
What it does:

- Pull yq 4.19.1 and do simple command using env(), check the result
- Then use yq 4.20.2 (system one), do same command and check the result
2. Launch the pipeline, it will hang forever on yq call

---
Logs from Azure pipeline run:
[yq_4.20.2_pipeline_issue.log](https://github.com/actions/virtual-environments/files/8170788/yq_4.20.2_pipeline_issue.log)

Logs same commands run on a fresh ubuntu docker image:
[yq_4.20.2_local_ok.log](https://github.com/actions/virtual-environments/files/8170799/yq_4.20.2_local_ok.log)

**Comment by mikhailkoliada** [comment]
@jojolb Hello! Thank you for the report.

Given that we are using the same images for Azure DevOps and Github I've tested your expression using ubuntu 18.04 and 20.04 there, and got the expected result:

![image](https://user-images.githubusercontent.com/88318005/156880874-f1e9cfb4-14d1-43a8-821b-c506173590bb.png)

**Comment by Jims55jr** [comment]
Helloworld!
