### ISSUE TITLE
windows-2022 image appears to be missing the .Net 4.6.1 Reference Assemblies

### ISSUE THREAD

**Issue by leezer3** [actions/virtual-environments#5167]
### Description

After the **windows-latest** image auto-upgraded, I discovered that Windows builds only were failing, due to missing .Net 4.6.1 reference assemblies.

Scanning the virtual environments changelog, only thing I can really see that's standing out as changed is that you appear to only now be shipping the 4.8 developer pack only, and have dropped the 4.7.2 developer pack as opposed to shipping both.

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

```
Agent name: 'Hosted Agent'
Agent machine name: 'WIN-13FDROU35QH'
Current agent version: '2.200.2'
Operating System
Microsoft Windows Server 2022
10.0.20348
Datacenter
Virtual Environment
Environment: windows-2022
Version: 20220220.1
Included Software: https://github.com/actions/virtual-environments/blob/win22/20220220.1/images/win/Windows2022-Readme.md
Image Release: https://github.com/actions/virtual-environments/releases/tag/win22%2F20220220.1
Virtual Environment Provisioner
1.0.0.0-main-20220225-1
Current image version: '20220220.1'
```

https://dev.azure.com/leezer3/OpenBVE/_build/results?buildId=985

### Is it regression?

windows-2019

### Expected behavior

.Net 4.6.2 reference assemblies are present, and build completes successfully.

Revert to the windows-2019 image, and build completes successfully:
https://dev.azure.com/leezer3/OpenBVE/_build/results?buildId=986

### Actual behavior

```Error MSB3644: The reference assemblies for .NETFramework,Version=v4.6.1 were not found. To resolve this, install the Developer Pack (SDK/Targeting Pack) for this framework version or retarget your application. You can download .NET Framework Developer Packs at https://aka.ms/msbuild/developerpacks```

### Repro steps

1. Create a .Net project, which refers to something in the .Net 4.6.1 reference assemblies / targets .Net 4.6.1.
2. Build using the windows-2022 image.
3. Observe that the build fails due to the above error.

**Comment by frankschierle** [comment]
Hi,

the reference assemblies for .Net 4.5 are missing as well:

`Error MSB3644: The reference assemblies for .NETFramework,Version=v4.5 were not found. To resolve this, install the Developer Pack (SDK/Targeting Pack) for this framework version or retarget your application. You can download .NET Framework Developer Packs at https://aka.ms/msbuild/developerpacks`

**Comment by shilovmaksim** [comment]
Hi @leezer3 .

Could you please try to install missing components during the runtime via following snippet which should resolve your issue:

```
steps:
  - displayName: Install component on windows 2022
    pwsh: |
      Set-Location "C:\Program Files (x86)\Microsoft Visual Studio\Installer\"
      $InstallPath = "C:\Program Files\Microsoft Visual Studio\2022\Enterprise"
      $componentsToAdd = @(
        "ADD COMPONENT NAME HERE"
      )
      [string]$workloadArgs = $componentsToAdd | ForEach-Object {" --add " +  $_}
      $Arguments = ('/c', "vs_installer.exe", 'modify', '--installPath', "`"$InstallPath`"",$workloadArgs, '--quiet', '--norestart', '--nocache')
      $process = Start-Process -FilePath cmd.exe -ArgumentList $Arguments -Wait -PassThru -WindowStyle Hidden
      if ($process.ExitCode -eq 0)
      {
          Write-Host "components have been successfully added"
      }
      else
      {
          Write-Host "components were not installed"
          exit 1
      }
```

Also please take a look at the similar issue https://github.com/actions/virtual-environments/issues/5055

**Comment by duyhthai** [comment]
Hi,

I had the same issue with .NET Framework 4.6.1. The pipeline was running fine before VS2022
- Adding script to install the component didn't help.
- Switching back to windows-2019 gets me this error 
`C:\Users\VssAdministrator\.nuget\packages\microsoft.net.sdk.functions\1.0.29\build\netstandard1.0\Microsoft.NET.Sdk.Functions.Build.targets(41,5): Error : It was not possible to find any compatible framework version The framework 'Microsoft.NETCore.App', version '2.1.0' was not found. - The following frameworks were found: 3.1.4 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App] 3.1.6 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App] 3.1.20 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App] 3.1.22 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App] 5.0.4 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App] 5.0.9 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App] 5.0.14 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App] You can resolve the problem by installing the specified framework and/or SDK. The specified framework can be found at: - https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=2.1.0&arch=x64&rid=win10-x64`

**Comment by leezer3** [comment]
It took some bashing to get the script above to work, but as above, it appears to not help.
https://dev.azure.com/leezer3/OpenBVE/_build/results?buildId=1000

**Comment by miketimofeev** [comment]
@leezer3 could you try my suggestion from here? https://github.com/actions/virtual-environments/issues/5055#issuecomment-1040757930

**Comment by leezer3** [comment]
Whilst that works. that's got a different set of absolute utter mess, in that it dumps practically the entire system reference DLL collection into the build folder. (4.6.1 is a *lot* quieter in this regard, with only a few)
https://stackoverflow.com/questions/53428460/why-are-there-system-dlls-in-my-bin-release-directory

I need to stay at this level in order to keep Debian Buster happy, which has Mono 5.18

**Comment by miketimofeev** [comment]
@leezer3 I'm afraid we can't do much here as this is out of our hands.
Windows-2019 will be supported for a few next years so it is safe to stick to it and seems to be the only option in your case.
I'm going to close the issue. Feel free to contact us if you have any concerns.
Thank you!

**Comment by jameseedi** [comment]
Just reflagging this here: https://learn.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops&tabs=windows-images%2Cyaml#windows-server-2019-hosted-image-deprecation-schedule that Windows-2019 support in Azure is due to be removed "Scheduled removal date for Windows Server 2019 hosted image: December 31, 2025"

**Comment by leezer3** [comment]
Thanks.

I've now found a (better) workaround using the Chocolatey azure devops extension (see my repos linked PR above), but frankly the decision to remove these is stupid, and I'm singularly unimpressed. This is core .Net stuf, not some extension....

There are plenty of .Net projects with legacy stuff about.

**Comment by jameseedi** [comment]
Thanks for the hint, I've added the below to the DevOps pipeline and tested with `Windows-2022` and the build works!

```
steps:
- powershell: |
   # Install Chocolatey if not present
   if (!(Get-Command choco -ErrorAction SilentlyContinue)) {
    Set-ExecutionPolicy Bypass -Scope Process -Force
    [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072
    iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))
    Write-Host "Chocolatey installed"
   } else {
    Write-Host "Chocolatey already installed"
   }
   
   # Install .NET Framework 4.6.1 Developer Pack
   Write-Host "Installing .NET Framework 4.6.1 Developer Pack..."
   choco install netfx-4.6.1-devpack -y
  displayName: 'Install Chocolatey & .NET 4.6.1 SDK'
```

**Comment by bitbang00111** [comment]
$ErrorActionPreference = "Stop"

Write-Host "Preparando reference assemblies para .NET Framework 4.6.1 desde NuGet..."

$workDir = Join-Path $env:AGENT_TEMPDIRECTORY "net461-reference-assemblies"
$nugetExe = Join-Path $workDir "nuget.exe"
$packagesDir = Join-Path $workDir "packages"

New-Item -ItemType Directory -Force -Path $workDir | Out-Null
New-Item -ItemType Directory -Force -Path $packagesDir | Out-Null

if (!(Test-Path $nugetExe)) {
    Write-Host "Descargando nuget.exe..."
    Invoke-WebRequest `
        -Uri "https://dist.nuget.org/win-x86-commandline/latest/nuget.exe" `
        -OutFile $nugetExe
}

Write-Host "Instalando paquete Microsoft.NETFramework.ReferenceAssemblies.net461..."

& $nugetExe install Microsoft.NETFramework.ReferenceAssemblies.net461 `
    -Version 1.0.3 `
    -OutputDirectory $packagesDir `
    -Source "https://api.nuget.org/v3/index.json" `
    -NonInteractive `
    -Verbosity detailed

if ($LASTEXITCODE -ne 0) {
    throw "nuget install falló con código $LASTEXITCODE"
}

$packageFolder = Get-ChildItem $packagesDir -Directory |
    Where-Object { $_.Name -like "Microsoft.NETFramework.ReferenceAssemblies.net461*" } |
    Select-Object -First 1

if ($null -eq $packageFolder) {
    throw "No se encontró la carpeta del paquete Microsoft.NETFramework.ReferenceAssemblies.net461."
}

$referenceRoot = Join-Path $packageFolder.FullName "build"
$net461Path = Join-Path $referenceRoot ".NETFramework\v4.6.1"
$mscorlibPath = Join-Path $net461Path "mscorlib.dll"
$frameworkListPath = Join-Path $net461Path "RedistList\FrameworkList.xml"

Write-Host "Reference root candidato:"
Write-Host $referenceRoot

Write-Host "Validando contenido:"
Write-Host $mscorlibPath
Write-Host $frameworkListPath

if (!(Test-Path $mscorlibPath)) {
    throw "No se encontró mscorlib.dll en las reference assemblies descargadas."
}

if (!(Test-Path $frameworkListPath)) {
    throw "No se encontró RedistList\FrameworkList.xml en las reference assemblies descargadas."
}

Write-Host "Reference assemblies net461 preparadas correctamente."

Write-Host "##vso[task.setvariable variable=Net461ReferenceAssembliesRoot]$referenceRoot"

Write-Host "Variable Azure DevOps creada:"
Write-Host "Net461ReferenceAssembliesRoot=$referenceRoot"

**Comment by bitbang00111** [comment]
El script de PowerShell anterior soluciona el problema, se tiene que colocar como aparece en la imagen siguiente:

<img width="631" height="387" alt="Image" src="https://github.com/user-attachments/assets/05ae5a62-252b-4e5e-bc5d-d6b42c52fe28" />
