### ISSUE TITLE
Add htmlq

### ISSUE THREAD

**Issue by jmarrec** [actions/virtual-environments#5169]
### Tool name

htmlq

### Tool license

MIT

### Add or update?

- [X] Add
- [ ] Update

### Desired version

latest

### Approximate size

14 MB

### Brief description of tool

Like [jq](https://stedolan.github.io/jq/), but for HTML/XML. Uses [CSS selectors](https://developer.mozilla.org/en-US/docs/Learn/CSS/Introduction_to_CSS/Selectors) to extract bits of content from HTML files.

### URL for tool's homepage

https://github.com/mgdm/htmlq

### Provide a basic test case to validate the tool's functionality.

```bash
It "Htmlq" {
   "htmlq --version" | Should -ReturnZeroExitCode
}
```

### Virtual environments affected

- [X] Ubuntu 18.04
- [X] Ubuntu 20.04
- [X] macOS 10.15
- [X] macOS 11
- [X] Windows Server 2016
- [X] Windows Server 2019
- [X] Windows Server 2022

### Can this tool be installed during the build?

```bash
cargo install htmlq
```

### Tool installation time in runtime

< 20 sec

### Are you willing to submit a PR?

Yes

**Comment by maxim-lobanov** [comment]
Hello @jmarrec , thank you for feature request. Considering pretty quick installation, we wouldn't like to bake this tool into images due to maintenance concerns. Installation in runtime should work for the most of the cases.
