### ISSUE TITLE
Update/Add Android SDK - CMake 3.10.2.4988404

### ISSUE THREAD

**Issue by yongce** [actions/virtual-environments#517]
**Tool information**
- Tool name: Android SDK - CMake
- Add or update? update
- Desired version: 3.10.2.4988404
- Approximate size: 
- If this is an add request:
  - Brief description of tool: To build native code in Android projects
  - URL for tool's homepage: 

**Area for Triage**:
Android

**Question, Bug, or Feature?**:
Bug

**Virtual environments affected**
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [X ] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Can this tool be installed during the build?**
Yes

**Are you willing to submit a PR?**
No

**Comment by yongce** [comment]
The build error info (https://github.com/yongce/AndroidLib/runs/490562783):
```
> com.android.builder.sdk.InstallFailedException: Failed to install the following SDK components:
      cmake;3.10.2.4988404 CMake 3.10.2.4988404
  The SDK directory is not writable (/usr/local/lib/android/sdk)


* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
```

**Comment by ligol** [comment]
A PR( #217 ) exist for adding support of that Cmake version. Could anybody look at it?

**Comment by maxim-lobanov** [comment]
@ligol , sorry for delay.
I have responded in PR, hope it will be merged soon

**Comment by maxim-lobanov** [comment]
Pull-request #217 was merged, thank you for contribution!
Will keep this issue opened until changes are deployed to all VMs (about 1 week)

**Comment by yongce** [comment]
Fixed now. Thanks!

**Comment by EwoutH** [comment]
It looks like CMake 3.10.2 is now the version used by default on the Ubuntu 18.04 image, is that intended behaviour?

**Comment by maxim-lobanov** [comment]
@EwoutH , just checked and `cmake --version` shows `cmake version 3.17.0` for me.
In scope of this issue, new cmake was added to Android sdkmanager. It doesn't affect default system cmake.

**Comment by EwoutH** [comment]
Thanks, I checked again and it was a docker issue on my side.
