### ISSUE TITLE
VS 2017 support after `windows-2016` is deprecated

### ISSUE THREAD

**Issue by seladb** [actions/virtual-environments#5177]
### Description

Hi GitHub Actions team!

As you [announced](https://github.blog/changelog/2021-10-19-github-actions-the-windows-2016-runner-image-will-be-removed-from-github-hosted-runners-on-march-15-2022/) a few months ago `windows-2016` will be removed on Mar 15, 2022. 
I'm using this image to [build my project using VS 2017](https://github.com/seladb/PcapPlusPlus/blob/master/.github/workflows/build_and_test.yml#L338-L346) which as far as I can tell isn't supported in any of the newer Windows images.
What options do I have to continue building with VS 2017?

I created a [discussion item](https://github.com/actions/virtual-environments/discussions/5161) but didn't see any response so far, so I thought I'd create an issue as well.

Thank you,
PcapPlusPlus maintainer

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [X] Windows Server 2016
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

windows-2016

### Repro steps

N/A

**Comment by Jaifroid** [comment]
I also need to build my project with VS 2017. It is a JSPROJ type which is not supported in VS 2019 or VS 2022.

VS 2017 can be installed alongside VS 2019, so it would not be problematic to provide this. It would be necessary to ensure that the [setup-msbuild](https://github.com/marketplace/actions/setup-msbuild) action can select the VS 2017 version of msbuild.

**Comment by mikhailkoliada** [comment]
@seladb Hello, thank you for the report!

We are not planning to continue supporting vs2017 as soon as windows-2016 is disbanded, due to support expanses and security concerns. If one wants to continue having vs2017 they are free to install it on their own risk straight in the runtime (using self-hosted runners).
