### ISSUE TITLE
kotlinc not available(?) on windows

### ISSUE THREAD

**Issue by SoniEx2** [actions/virtual-environments#5181]
### Description

We may well be doing something wrong here, but it seems kotlinc isn't available on the Windows image?

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [X] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

https://github.com/SoniEx2/wasm2kotlin/runs/5426920384?check_suite_focus=true

### Expected behavior

kotlinc should just work, as it does on every other image.

### Actual behavior

kotlinc doesn't work.

### Repro steps

1. Attempt to run kotlinc.exe?

**Comment by mikhailkoliada** [comment]
@SoniEx2 Hello, thanks for the report!

I've just run a plain workflow which is in turn running `kotlinc -version` I can confirm that everything is working as expected, something is wrong with your `$env:PATH` var possibly.

**Comment by SoniEx2** [comment]
hmm ohh wait, it's not an .exe is it?

**Comment by SoniEx2** [comment]
yeah that was that >.<
