### ISSUE TITLE
Windows-2022 image does not seem to have .NET 6 SDK installed

### ISSUE THREAD

**Issue by deviousasti** [actions/virtual-environments#5184]
### Description

According to the list of installed software (in https://github.com/actions/virtual-environments/blob/main/images/win/Windows2022-Readme.md#net-core-sdk), .NET SDK `6.0.200` is expected to be present.

In the recent upgrade to windows-22, this breaks build pipelines because SDK 6 isn't installed.
According to the discussion in #4856, it should be installed as part of VS 2022.

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

Image: windows-latest
Agent: Azure Pipelines 6

Failed build:
https://dev.azure.com/jet-opensource/opensource/_build/results?buildId=9452&view=logs&j=2d2b3007-3c5c-5840-9bb0-2b1ea49925f3&t=0f0b056b-e9f7-5ce7-8817-a8ca2fd77699

### Expected behavior

Build should not fail with SDK not found error.

### Actual behavior

Build fails saying SDK 6.0 could not be found.

```
     A compatible installed .NET SDK for global.json version [6.0.200] from [D:\a\1\s\global.json] was not found.
        3.1.416 [C:\Program Files\dotnet\sdk]
      Install the [6.0.200] .NET SDK or update [D:\a\1\s\global.json] with an installed .NET SDK:
        5.0.104 [C:\Program Files\dotnet\sdk]
        5.0.211 [C:\Program Files\dotnet\sdk]
        5.0.303 [C:\Program Files\dotnet\sdk]
        5.0.405 [C:\Program Files\dotnet\sdk]
```

### Repro steps

Run a build targeting .NET SDK 6 on the `windows-latest` image.

**Comment by stijnherreman** [comment]
On Azure, `windows-latest` still points to `windows-2019`. See the log output of the top-level Windows job:

> ##[warning]windows-latest pipelines will use windows-2022 soon.

And the comment at https://github.com/actions/virtual-environments/issues/4856#issuecomment-1050662080:

> **GitHub migration completed!** Azure DevOps one is delayed and will be completed by the end of March or even the beginning of April.

So for now you need to specify `windows-2022`.

**Comment by deviousasti** [comment]
Thank you.
