### ISSUE TITLE
zh-CN and zh-TW .NET resources are not generated in `windows-latest` (`windows-2022`)

### ISSUE THREAD

**Issue by JustArchi** [actions/virtual-environments#5189]
### Description

One of the users of my **[ASF](https://github.com/JustArchiNET/ArchiSteamFarm)** software has reported that the program is missing zh-CN (Chinese simplified) translations. After short investigation I came to conclusion that this had to be GitHub runner environment change, as I couldn't narrow it to any other component. A quick **[commit](https://github.com/JustArchiNET/ArchiSteamFarm/commit/28937a628fd760adb857e65fbd047fcc18c11bd1)** for testing has confirmed my suspicion, as downgrading the image from `windows-latest` to `windows-2019` fixes the issue and there are `zh-CN` resources generated again.

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

Build on `windows-latest` which doesn't include correct translations: https://github.com/JustArchiNET/ArchiSteamFarm/actions/runs/1945418953

```
  Environment: windows-2022
  Version: 20220227.1
  Included Software: https://github.com/actions/virtual-environments/blob/win22/20220227.1/images/win/Windows2022-Readme.md
  Image Release: https://github.com/actions/virtual-environments/releases/tag/win22%2F20220227.1
```

Build on `windows-2019` which does: https://github.com/JustArchiNET/ArchiSteamFarm/actions/runs/1946785489

```
  Environment: windows-2019
  Version: 20220227.1
  Included Software: https://github.com/actions/virtual-environments/blob/win19/20220227.1/images/win/Windows2019-Readme.md
  Image Release: https://github.com/actions/virtual-environments/releases/tag/win19%2F20220227.1
```

Both happened the same day, 5 hours apart, so I'm pretty sure nothing else affected the outcome.

For verification, download `windows-latest_ASF-generic` and `windows-2019_ASF-generic` artifacts. In the downloaded zip file navigate to `zh-CN` folder, there should be `ArchiSteamFarm.resources.dll` file available, which doesn't exist in `windows-latest` run.

![obraz](https://user-images.githubusercontent.com/1069029/157084824-491953c4-1e8f-4347-b078-e37dcd40b583.png)

### Is it regression?

Yes, `windows-2019` works fine - https://github.com/JustArchiNET/ArchiSteamFarm/actions/runs/1946785489

### Expected behavior

If there are `zh-CN` resources, they should be embedded in the resulting build output. This is what happens with all other languages, such as `pl-PL` among others.

### Actual behavior

`zh-CN` and `zh-TW` resources are missing, only those two seem affected, as other translations are working just fine. I suspect some missing cultures installed or something like that, there is for sure some difference in `2022` version compared to `2019` in this regard. Sadly I'm unable to assist further as I don't know what exactly is missing, in fact I'm surprised something is.

### Repro steps

You can run my public **[publish.yml](https://github.com/JustArchiNET/ArchiSteamFarm/blob/main/.github/workflows/publish.yml)** workflow, `publish` job is enough, simply replace `windows-XXX` in OS matrix to the one you want to test. You can analyze the output `windows-XXX_ASF-generic` build artifact, where `XXX` is the windows version that was used for build.

Alternatively, you can also build the program source manually:

```pwsh
# Install latest 6.0 .NET SDK if needed: https://dotnet.microsoft.com/en-us/download/dotnet/6.0

git clone https://github.com/JustArchiNET/ArchiSteamFarm.git
cd ArchiSteamFarm
dotnet publish ArchiSteamFarm -c Release -o out -f net6.0

# Verify if out/zh-CN/ArchiSteamFarm.resources.dll exists, it should at least on windows-2019
Get-ChildItem out\zh-CN
```

Thank you in advance for considering this issue, let me know if I can aid you further in any way. The project and all resources are public, so reproducing it shouldn't be an issue.

For now I've decided to downgrade the used version as part of https://github.com/JustArchiNET/ArchiSteamFarm/pull/2533 - not ideal, but fixes the problem.

**Comment by JustArchi** [comment]
Additional info:

I don't want to analyze all the builds but for record, `windows-latest` from 25 days ago worked fine as it was still pointing to `2019` variant:

```
  Environment: windows-2019
  Version: 20220131.1
  Included Software: https://github.com/actions/virtual-environments/blob/win19/20220131.1/images/win/Windows2019-Readme.md
  Image Release: https://github.com/actions/virtual-environments/releases/tag/win19%2F20220131.1
```

You can find its release **[here](https://github.com/JustArchiNET/ArchiSteamFarm/releases/tag/5.2.3.3)** (V5.2.3.3).

---

The first problematic build was produced 11 days ago, where `windows-latest` already pointed to `2022` variant:

```
  Environment: windows-2022
  Version: 20220220.1
  Included Software: https://github.com/actions/virtual-environments/blob/win22/20220220.1/images/win/Windows2022-Readme.md
  Image Release: https://github.com/actions/virtual-environments/releases/tag/win22%2F20220220.1
```

You can find its release **[here](https://github.com/JustArchiNET/ArchiSteamFarm/releases/tag/5.2.3.4)** (V5.2.3.4).

This confirms that `2022` version is the problematic one and not some internal upgrade across the same release.

**Comment by mikhailkoliada** [comment]
@JustArchi Hi, thanks for the report! We will take a look.

**Comment by JustArchi** [comment]
@mikhailkoliada thanks for triage, you can consider adding .NET Core label as well, as this issue seems to affect both - .NET Framework and .NET Core, my ASF project builds a binary for both and it seems they're both suffering from the same issue - I've verified that checking `-generic-netf` package in addition to `-generic` which I've originally opened the issue about.

**Comment by dsame** [comment]
i confirm
windows-2019 has zh-CN and zh-TW locales installed 
https://github.com/akv-platform/dotnet-locales/runs/5814137648
and windows-2020 has not
https://github.com/akv-platform/dotnet-locales/actions/runs/2089010332

i am looking for a reason and solving the problem

**Comment by dsame** [comment]
@JustArchi According to https://cldr.unicode.org/index/cldr-spec/language-tag-equivalences , namely the wording "This means that zh ~ zh-CN ~ zh-Hans ~ zh-Hans-CN, and that zh-Hant ~ zh-TW ~ zh-Hant-TW." at the very bottom  

zh-CN and zh-TW replaced with their equivalents zh-Hans-CN and zh-Hant-TW

Can you use the OS provided locales?

**Comment by JustArchi** [comment]
@dsame thank you for evaluation. Yes, I probably could rename my locales to those two. Give me a moment to give it a try and I'll come back to you with results.

**Comment by dsame** [comment]
@JustArchi thank you  for cooperation!
