### ISSUE TITLE
Making scripts executable is required for some, not for others on Ubuntu

### ISSUE THREAD

**Issue by TomasHubelbauer** [actions/virtual-environments#5191]
### Description

Hi, this is a weird one. I have a repository with a bunch of associated pipelines and I just added a few extra: 

https://github.com/TomasHubelbauer/hubelbauer.net/commit/14854b93601fa01bfbb8f414690a752e0780e589

As you can see, three extra pipelines were introduced, three similar YML files all calling shell scripts of the same name internally. The hubelbauer.cz one just worked straight off the bat. However, the other two were failing with a 126 error code permission denial error:

https://github.com/TomasHubelbauer/hubelbauer.net/actions/runs/1947317567 https://github.com/TomasHubelbauer/hubelbauer.net/actions/runs/1947317565

The error happened for both on the very first push and I re-ran them manually to make sure it wasn't a flake. It stayed the same.

I tried making the shell scripts executable prior to calling them (something that's not necessary for the other scripts) and it helped:

https://github.com/TomasHubelbauer/hubelbauer.net/commit/e22a4b96fa3596395b274ae90196648b263760fd 
https://github.com/TomasHubelbauer/hubelbauer.net/actions/runs/1947344827 
https://github.com/TomasHubelbauer/hubelbauer.net/actions/runs/1947344816

However, I don't think I should need to do this? At first I figured maybe it was needed because the new pipelines had double periods in their name and their extensions could have been interpreted as domain.tld-redirect.sh instead of just .sh. But if that was the case, why did the hubelbauer.cz-redirect.sh one work and the other two did not? It is the same pattern... Are the file names too long or something?

I think this is a bug, like other shell files, I should not need to make these executable in the pipeline before calling them. I just don't know why these two stand out.

### Virtual environments affected

- [X] Ubuntu 18.04
- [X] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

ubuntu-latest

### Is it regression?

don't know

### Expected behavior

chmod +x is not needed to run shell scripts

### Actual behavior

chmod +x is sometimes but not always needed to run shell scripts

### Repro steps

Fork my repo https://github.com/TomasHubelbauer/hubelbauer.net - it will fork its pipelines and you can see the problem will come back if you remove the chmod +x step I had to introduce to fix the error.

**Comment by panekj** [comment]
You need to change executable permission bit because `git` preserves that information in the repository
```sh
pj in marten in ~/.loc/tmp/hubelbauer.net/.github/workflows on  master
❯ ll -a
drwxr-xr-x pj pj 4.0 KB Mon Mar  7 23:53:54 2022  .
drwxr-xr-x pj pj 4.0 KB Mon Mar  7 23:53:54 2022  ..
.rw-r--r-- pj pj  72 B  Mon Mar  7 23:53:54 2022  .gitignore
.rwxr-xr-x pj pj 486 B  Mon Mar  7 23:53:54 2022  dns-a-records.sh
.rw-r--r-- pj pj 540 B  Mon Mar  7 23:53:54 2022  dns-a-records.yml
.rwxr-xr-x pj pj 505 B  Mon Mar  7 23:53:54 2022  dns-aaaa-records.sh
.rw-r--r-- pj pj 549 B  Mon Mar  7 23:53:54 2022  dns-aaaa-records.yml
.rwxr-xr-x pj pj 447 B  Mon Mar  7 23:53:54 2022  dns-cname-record.sh
.rw-r--r-- pj pj 553 B  Mon Mar  7 23:53:54 2022  dns-cname-record.yml
.rwxr-xr-x pj pj 376 B  Mon Mar  7 23:53:54 2022  http-https-redirect.sh
.rw-r--r-- pj pj 580 B  Mon Mar  7 23:53:54 2022  http-https-redirect.yml
.rwxr-xr-x pj pj 380 B  Mon Mar  7 23:53:54 2022  http-www-redirect.sh
.rw-r--r-- pj pj 580 B  Mon Mar  7 23:53:54 2022  http-www-redirect.yml
.rwxr-xr-x pj pj 7.2 KB Mon Mar  7 23:53:54 2022  https-ssl-certificates.sh
.rw-r--r-- pj pj 565 B  Mon Mar  7 23:53:54 2022  https-ssl-certificates.yml
.rwxr-xr-x pj pj 381 B  Mon Mar  7 23:53:54 2022  https-www-redirect.sh
.rw-r--r-- pj pj 583 B  Mon Mar  7 23:53:54 2022  https-www-redirect.yml
.rwxr-xr-x pj pj 375 B  Mon Mar  7 23:53:54 2022  hubelbauer.cz-redirect.sh
.rw-r--r-- pj pj 585 B  Mon Mar  7 23:53:54 2022  hubelbauer.cz-redirect.yml
.rw-r--r-- pj pj 380 B  Mon Mar  7 23:53:54 2022  tomashubelbauer.cz-redirect.sh
.rw-r--r-- pj pj 732 B  Mon Mar  7 23:53:54 2022  tomashubelbauer.cz-redirect.yml
.rw-r--r-- pj pj 381 B  Mon Mar  7 23:53:54 2022  tomashubelbauer.net-redirect.sh
.rw-r--r-- pj pj 737 B  Mon Mar  7 23:53:54 2022  tomashubelbauer.net-redirect.yml
```

You can fix that by running
```sh
git update-index --chmod=+x <path to file>
```

**Comment by TomasHubelbauer** [comment]
Ah, thank you! I did not realize Git kept this information, I operated with the assumption that the Ubuntu image was configured such that the executable flag was implicit. This makes way more sense. The reason these two workflows specifically were failing was because they were a copy-paste job I figured was not worth testing locally since the changes were so small.
