### ISSUE TITLE
Add .NET 6 for macOS virtual environments

### ISSUE THREAD

**Issue by AlexSrizhevskiy** [actions/virtual-environments#5193]
### Tool name

.NET 6

### Tool license

free

### Add or update?

- [X] Add
- [ ] Update

### Desired version

.NET 6

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [X] macOS 10.15
- [X] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [ ] Windows Server 2022

**Comment by maxim-lobanov** [comment]
Hello @AlexSrizhevskiy , have you considered using [actions/setup-dotnet](https://github.com/actions/setup-dotnet) task? It is recommended approach to get specific .NET Core version

**Comment by mikhailkoliada** [comment]
Hi @AlexSrizhevskiy, please use the setup-dotnet task for the time being as recommended by @maxim-lobanov .Net 6 will be available later this year with the VS 2022 for macOS.

**Comment by mattjohnsonpint** [comment]
I don't understand this decision.  If .NET 6 SDK is kept updated for Ubuntu (see @Steve-Glass 's comment on the related issue here: https://github.com/actions/virtual-environments/issues/4424#issuecomment-1021249739), then why would you not do the same for macOS?  We don't need Visual Studio for Mac to use .NET on macOS.
