### ISSUE TITLE
Problems with building Xamarin android projects in Windows 2022 image

### ISSUE THREAD

**Issue by Dolphinsimon** [actions/virtual-environments#5198]
### Description

We can build the project in version 20220116.1, after that all builds were failed.

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

20220220.1/20220227.1

### Is it regression?

Yes

### Expected behavior

The XamarinAndroid task should be running successfully.

### Actual behavior

_AndroidAot:
  [mkbundle stderr] 
  [cc stderr] 'C:\Program' is not recognized as an internal or external command,
  [cc stderr] operable program or batch file.
  [cc stderr] 
##[error]C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Legacy.targets(729,5): Error XA5103: NDK C compiler exited with an error. Exit code 0

### Repro steps

I have created an issue here: [azure-pipeline-tasks](https://github.com/microsoft/azure-pipelines-tasks/issues/15960)
The task maintainer believes the issue is related to virtual environment.

**Comment by miketimofeev** [comment]
Hi @Dolphinsimon!
Have you tried switching the version? Does it help?
https://github.com/microsoft/azure-pipelines-tasks/issues/15960#issuecomment-1058397677

**Comment by mikhailkoliada** [comment]
@Dolphinsimon kind ping regarding a comment from @miketimofeev

**Comment by Dolphinsimon** [comment]
> Hi @Dolphinsimon!
> 
> Have you tried switching the version? Does it help?
> 
> https://github.com/microsoft/azure-pipelines-tasks/issues/15960#issuecomment-1058397677

I have tried to set the ndk version. The build was successful. Do you have a plan to make the new version as default?

**Comment by soroshsabz** [comment]
related to https://github.com/xamarin/xamarin-android/issues/6808#issuecomment-1102662611
