### ISSUE TITLE
Update go to go1.17.8 which was released 2022-03-03

### ISSUE THREAD

**Issue by ncw** [actions/virtual-environments#5202]
### Tool name

go

### Tool license

MIT

### Add or update?

- [ ] Add
- [X] Update

### Desired version

go1.17.8

### Virtual environments affected

- [X] Ubuntu 18.04
- [X] Ubuntu 20.04
- [X] macOS 10.15
- [X] macOS 11
- [X] Windows Server 2016
- [X] Windows Server 2019
- [X] Windows Server 2022

**Comment by ncw** [comment]
I made this issue here because go1.17.8 is missing from https://github.com/actions/go-versions and the README there said make the issue here!

**Comment by aloviedo** [comment]
@ncw would just installing 1.18 resolve your issue?

**Comment by maxim-lobanov** [comment]
Hello @ncw ,
Go 1.17.8 and 1.18.0 were added to go-versions. Sorry for delay and thank you for your patience:
https://github.com/actions/go-versions/blob/main/versions-manifest.json#L28
