### ISSUE TITLE
`Install-Chrome.ps1` fails with `-2147012894` behind a proxy

### ISSUE THREAD

**Issue by HofmeisterAn** [actions/virtual-environments#5203]
### Description

It looks like that `Install-Chrome.ps1` does not work well behind a proxy. We're facing similar issues described [here](https://support.google.com/chrome/thread/49401854?hl=en). The `GoogleUpdate` process cannot download the latest version.

The download URL looks "ambiguous" too. It does not install the version `375.126`. It downloads the "online" installer (about 1MB), which installs the latest version instead:

https://github.com/actions/virtual-environments/blob/c8b63063441fb63048458f7907292a814c25189f/images/win/scripts/Installers/Install-Chrome.ps1#L8

I suggest to replace the installer with the stand-alone version, something like (this fixes the issue for us):

```powershell
$ChromeInstallerFile = "googlechromestandaloneenterprise64.msi"
$ChromeInstallerUrl = "https://dl.google.com/tag/s/dl/chrome/install/${ChromeInstallerFile}"
Install-Binary -Url $ChromeInstallerUrl -Name $ChromeInstallerFile -ArgumentList @()
```

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [X] Windows Server 2016
- [X] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

\-

### Is it regression?

No

### Expected behavior

Chrome is installed.

### Actual behavior

`Install-Chrome.ps1` fails with `-2147012894`.

### Repro steps

1. Run `Install-Chrome.ps1` behind a proxy.

**Comment by maxim-lobanov** [comment]
Hello @HofmeisterAn , thank you for reporting.
Are you willing to submit PR?

**Comment by HofmeisterAn** [comment]
Yes, I can create a pr in the next days.
