### ISSUE TITLE
Update default go version to 1.16 or higher

### ISSUE THREAD

**Issue by g14com0** [actions/virtual-environments#5208]
### Tool name

go

### Tool license

MIT

### Add or update?

- [ ] Add
- [X] Update

### Desired version

1.16.*

### Brief description of tool

Upgrade default version of golang at least to v1.16 since golang 1.15 reached end of life and it's vulnerable.

### Virtual environments affected

- [X] Ubuntu 18.04
- [X] Ubuntu 20.04
- [X] macOS 10.15
- [X] macOS 11
- [x] Windows Server 2016
- [X] Windows Server 2019
- [X] Windows Server 2022

### Are you willing to submit a PR?

yes

**Comment by g14com0** [comment]
Hello, [here](https://github.com/g14com0/virtual-environments/pull/1) you can find a PR in my forked repo, i didn't remove go 1.15 because i think you want first to announce this change also, go 1.16.15 and 1.17.8 are out and can be used once the pipeline in [go-version](https://github.com/actions/go-versions/actions/workflows/get-go-versions.yml) repo will be fixed as mentioned in #5202

**Comment by maxim-lobanov** [comment]
Hello @g14com0 , thank you for bringing our attention to it.
Considering the fact that Go 1.15 reached EOL, we definitely should update default to 1.16 or 1.17 but I think we should some announcement regarding it.
I will double check and will return back.

**Comment by g14com0** [comment]
v1.16 reached as well EOL as reported [here](https://endoflife.date/go), please consider only 1.17 and 1.18 as the default version
