### ISSUE TITLE
Gibhub action slow performance due CRL

### ISSUE THREAD

**Issue by erdembayar** [actions/virtual-environments#5209]
### Description

Hi,

I’m from NuGet.Client team, which owns NuGet functionality in .NET and Visual Studio.
We’re following up on issue [#11548](https://github.com/NuGet/Home/issues/11548) which raised by customer about slow perf in Github actions due certificate revocation list download.
We did some performance investigation, and it looks legit issue.
I’m looking into improving this experience, and I was wondering if I could meet/contact someone from Github action team to see what we can do about it? By the way I'm MS internal, you can ping me teams.

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [X] Windows Server 2016
- [X] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

https://github.com/StackExchange/StackExchange.Redis/runs/5029970749?check_suite_focus=true#step:4:1

### Is it regression?

n/a

### Repro steps

https://github.com/NuGet/Home/issues/11548
I can provide more details if you give us your contact.

**Comment by erdembayar** [comment]
I sent offline email.

**Comment by miketimofeev** [comment]
@alepauly @maxim-lobanov could you contact with @erdembayar?

**Comment by miketimofeev** [comment]
Continued the discussion in the e-mail thread.
