### ISSUE TITLE
Update CMake

### ISSUE THREAD

**Issue by rick-de-water** [actions/virtual-environments#521]
**Tool information**
- Tool name: **CMake**
- Add or update? **Add**
- Desired version: **Latest**
- Approximate size: **Small**

**Area for Triage**:
C/C++

**Question, Bug, or Feature?**:
Feature

**Virtual environments affected**
- [ ] macOS 10.15
- [x] Ubuntu 16.04 LTS
- [x] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Can this tool be installed during the build?**
Probably, but it is difficult because `apt` only has quite old versions of CMake.

**Are you willing to submit a PR?**
No

The I'm having is right now is the lack of C++20 support in these older versions of CMake. `cxx_std_20` is not supported at all, making it impossible to use the basic features of C++20. Also, modules are being added to C++ which will impact the build systems as well, so it is important to stay up to date to make sure that everything works with the latest version of C++.

**Comment by miketimofeev** [comment]
hi @rick-de-water! Could you provide the exact version number, please? As I can see we have `CMake (cmake version 3.16.2)` on Ubuntu images that doesn't look quite old.

**Comment by rick-de-water** [comment]
I seem to have interpreted the errors I was getting incorrectly. It is indeed already up to date. Thank you for the quick response, and sorry if wasted any of your time.
