### ISSUE TITLE
Unable to run command with required permissions

### ISSUE THREAD

**Issue by onuzbee** [actions/virtual-environments#5213]
### Description

Workflows have started to fail, requiring to run as administrator privileges. [Failed workflow link
](https://github.com/twilio/scoop-twilio-cli/runs/5491214973?check_suite_focus=true)

We have just started to see this issue, and wasn't persistent before. Did something change with the windows-latest upgrate to v2022? [Docs](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners ) still mention the following: 

```
Windows virtual machines are configured to run as administrators with User Account Control (UAC) disabled.
```

Could someone help us navigate through this? Or if we'd need to provide runAs flag somewhere in case there have been some permission changes? 

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [X] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

https://github.com/twilio/scoop-twilio-cli/runs/5491214973?check_suite_focus=true

### Repro steps

Rerun the workflow given above.

**Comment by al-cheb** [comment]
Hellp @onuzbee ,
All scripts are run by default with disabled UAC under runner user which is a member of Administrator group, that's why we get `Running the installer as administrator is disabled by default, use -RunAsAdmin parameter if you know what you are doing.` error.

To fix an issue you should pass `RunAsAdmin` flag to the script:
```
- run: |
          (New-Object System.Net.WebClient).DownloadFile('https://get.scoop.sh', 'scoop.ps1') 
          ./scoop.ps1 -RunAsAdmin

```
![image](https://user-images.githubusercontent.com/47745270/157864335-211187b4-e136-420e-a01f-a154b01ee591.png)

**Comment by chukkalasandeep** [comment]
Hi @al-cheb ,

I am getting the permission error when running powershell script to stop an application service, I tried passing `-RunAsAdmin` parameter but still the script doesn't successfully execute 

> run:  |
  ./manageservice.ps1 -RunAsAdmin -action stop -env ${{ env.ENV_TYPE }} -servicepath ${{ env.APPS_ROOT_PATH }}\ListenerService
  
 
![image](https://github.com/actions/runner-images/assets/9654621/8cac842d-1b02-47cc-ab8f-b17d51296ada)
