### ISSUE TITLE
Add autoconf tool

### ISSUE THREAD

**Issue by newhoggy** [actions/virtual-environments#5216]
### Tool name

autoconf

### Tool license

GPL

### Add or update?

- [X] Add
- [ ] Update

### Desired version

2.71

### Brief description of tool

This tool is required to build some software from source.  For example the following build shows that building from source on Windows fails because `autoreconf` is missing:

https://github.com/newhoggy/secp256k1/runs/5495746739?check_suite_focus=true

And `autoreconf` is part of `autoconf`.

### URL for tool's homepage

https://www.gnu.org/software/autoconf/

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [X] Windows Server 2016
- [X] Windows Server 2019
- [X] Windows Server 2022

### Can this tool be installed during the build?

```bash
Not sure how, but msys2 provides `autoconf`.  It might be possible to install this there with pacman -S autoconf
```

**Comment by miketimofeev** [comment]
@newhoggy Hi!
We wouldn't like to add the tool to the image as we set on not adding any msys packages to the image. You can install autotools, which include autoconf https://www.msys2.org/docs/autotools/,  using the [setup-msys2](https://github.com/msys2/setup-msys2) action:
```
      - uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >-
            autotools
```
I'm going to close the issue. Feel free to contact us if you have any concerns.
Thank you!
