### ISSUE TITLE
Purge npm/yarn cache before shipping images

### ISSUE THREAD

**Issue by imbsky** [actions/virtual-environments#522]

**Comment by miketimofeev** [comment]
Hi @imbsky. We're already working on disabling pre-cached npm/yarn packages on the macOS VM image if I get your issue right.

**Comment by imbsky** [comment]
Nice

**Comment by miketimofeev** [comment]
Closing this issue as it's a duplicate.
Feel free to reopen if you have any concerns.
Thank you!

**Comment by smorimoto** [comment]
@miketimofeev This happens again in the Windows image. Please re-open this issue.

**Comment by smorimoto** [comment]
Honestly, why don't you stop installing many tools by default? It seems that you all aren't able to maintain that properly. If you continue to do that, users will just lose.

**Comment by smorimoto** [comment]
As I've said many times, continuing to ship such dirty images is not a good idea from a CI perspective. Even if you want to keep shipping such images, it's a really good idea to ship the completely plain images.

**Comment by LeonidLapshin** [comment]
Hey, @smorimoto !
Could you please open a new issue with problem description using a [template](https://github.com/actions/virtual-environments/issues/new?assignees=&labels=needs+triage&template=bug-report.md&title=) ?
Thank you!

**Comment by smorimoto** [comment]
@LeonidLapshin I have no strong objection to opening a new issue, but the problem is quite simple, and everything is as the title says.
