### ISSUE TITLE
Chrome version not updated causing failure

### ISSUE THREAD

**Issue by mkathu** [actions/virtual-environments#5221]
### Description

The actions workflow which was working earlier by testing the configured urls on chrome does not work any more due to chrome version mismatch.

### Virtual environments affected

- [ ] Ubuntu 18.04
- [X] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Operating System
  Ubuntu
  20.0[4](https://github.com/AEMCS/axe-scan-ci-cd/runs/5511347862?check_suite_focus=true#step:1:4).4
  LTS
Virtual Environment
  Environment: ubuntu-20.04
  Version: 2022022[7](https://github.com/AEMCS/axe-scan-ci-cd/runs/5511347862?check_suite_focus=true#step:1:7).1
  Included Software: https://github.com/actions/virtual-environments/blob/ubuntu20/20220227.1/images/linux/Ubuntu2004-Readme.md
  Image Release: https://github.com/actions/virtual-environments/releases/tag/ubuntu20%2F20220227.1

### Expected behavior

I am trying to execute a test which scans urls on chrome browser. This was working earlier. Now its failing due to version of chrome
Below are the set of commands executed as part of actions.

 sudo apt-get update
          sudo apt-get --only-upgrade install google-chrome-stable
          google-chrome --version
          npm install -g webdriver-manager
          npm i @axe-core/cli@4.3.2-alpha.209 -g
          axe ${{steps.pickUrls.outputs.urls}} --show-errors --load-delay=${{ github.event.client_payload.load-time }} --tags ${{env.STANDARD_TO_CHECK}} --save ${{ github.event.client_payload.file-to-read }}-$(date +%Y%m%d%H%M).json
 
Expectation is that all the steps should pass.

### Actual behavior

![Uploading image.png…]()
Tests are failing

### Repro steps

sudo apt-get update
sudo apt-get --only-upgrade install google-chrome-stable
 google-chrome --version
npm install -g webdriver-manager
npm i @axe-core/cli@4.3.2-alpha.209 -g
axe ${{steps.pickUrls.outputs.urls}} --show-errors --load-delay=${{ github.event.client_payload.load-time }} --tags ${{env.STANDARD_TO_CHECK}} --save ${{ github.event.client_payload.file-to-read }}-$(date +%Y%m%d%H%M).json

**Comment by ctrongminh** [comment]
Hi @mkathu  ,
somehow, I cannot see your image yet.
I got the error updating chrome where the ubuntu-latest only update to chrome version 98, and the webdriver-manager requires chrome version 99.

I'm not sure my problem is the same as yours, as I can't see your image atm

**Comment by fdintino** [comment]
I think this is also the cause of cypress-io/github-action#518

**Comment by fdintino** [comment]
The strange thing is that all of the jobs are running the same environment and version (ubuntu-20.04.4 and 20220306.1) but some of the workers have chrome 98.0.4758.102 and others have chrome 99.0.4844.51

**Comment by ctrongminh** [comment]
For me, I do a workaround like this:

1. Update the latest chrome (or just get the current binary)
2. output the version of chrome to a variable
3. echo that variable to $GITHUB_ENV, so in the next step we can use that env variable
4. In the step install/update/start webdriver-manager, input the specific version from the env var.

This is the example with chromium (I'm using ubuntu-latest)
step 1 - update chromium
```
CHROMIUM_VERSION=$(/usr/bin/chromium --version | awk '{print $2}')
echo "CHROMIUM_VERSION=$CHROMIUM_VERSION" >> $GITHUB_ENV
```

step 2 - update / start webdriver-manager
```
webdriver-manager update --versions.chrome $CHROMIUM_VERSION
webdriver-manager start --versions.chrome $CHROMIUM_VERSION &
```

**Comment by mikhailkoliada** [comment]
@mkathu Hello! Thanks for the report! Are you still encountering the issue? I see chrome version has been updated.

**Comment by miketimofeev** [comment]
@markhobson we haven't updated Ubuntu20 due to the bug with the static web app that's why the version is outdated there.

**Comment by markhobson** [comment]
@miketimofeev Thanks, is there another issue for that I can follow?

**Comment by markhobson** [comment]
@miketimofeev Great, thanks for letting me know!

**Comment by miketimofeev** [comment]
Chrome version was updated, sorry for the delay.

**Comment by george-gca** [comment]
Got here because of an old chrome version in `ubuntu-latest` compared to the driver version in `axe-cli`. My solution was to force update both `chromium` version and its driver, as I posted in [axe issues](https://github.com/dequelabs/axe-core-npm/issues/401#issuecomment-1917605607). Leaving the link here if anyone else faces the same issue.
