### ISSUE TITLE
Update/Add Visual C++ Build Tools 2015

### ISSUE THREAD

**Issue by andrew-gresyk** [actions/virtual-environments#5227]
### Tool name

Visual C++ Build Tools 2015

### Tool license

https://visualstudio.microsoft.com/vs/older-downloads/

### Add or update?

- [X] Add
- [ ] Update

### Desired version

Latest

### Brief description of tool

Compiler and libraries to build C++

### URL for tool's homepage

https://visualstudio.microsoft.com/vs/older-downloads/

### Provide a basic test case to validate the tool's functionality.

```bash
Build a Visual Studio 2015 solution
```

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [X] Windows Server 2019
- [X] Windows Server 2022

### Can this tool be installed during the build?

```bash
It's several gigabytes large
```

### Tool installation time in runtime

Long

**Comment by maxim-lobanov** [comment]
Hello @andrew-gresyk , 
We wouldn't like to pre-install Build Tools 2015 to Windows Server 2019 and 2022 images because this component is pretty old and can cause compatibility problems with already pre-installed builds-tools and Visual Studio. Please consider installation in runtime.
