### ISSUE TITLE
Why is artifact download url to be expired in 1 minute?

### ISSUE THREAD

**Issue by jjangga0214** [actions/virtual-environments#523]
I'm not sure whether this issue is proper to be here. Please let me know where to forward if desired.

[The official docs](https://developer.github.com/v3/actions/artifacts/#download-an-artifact) for action api says `artifact download URL` expires in 1 minute.

Why is there such expiration and even so short?

What if someone needs a fixed, lasting URL without an expiration?

Thanks.

**Comment by miketimofeev** [comment]
Hi, @jjangga0214. It seems these are the better places for the issue.
https://github.com/actions/download-artifact
https://github.com/actions/upload-artifact
Closing that one, but feel free to reopen if you have any concerns.
Thank you!
