### ISSUE TITLE
Add WDK to VS 2022 image

### ISSUE THREAD

**Issue by thhous-msft** [actions/virtual-environments#5235]
### Tool name

WDK

### Tool license

Microsoft

### Add or update?

- [X] Add
- [ ] Update

### Desired version

Latest

### Brief description of tool

The WDK is used for building kernel mode binaries. It was added to the 2019 image, but because a 2022 was not available at all until recently,

https://github.com/actions/virtual-environments/issues/4139 was made by our team earlier, and closed pending a WDK release. Now that one has been released (Even though its a preview) we would like it installed so we can test our pipelines.

### URL for tool's homepage

https://docs.microsoft.com/en-us/windows-hardware/drivers/installing-preview-versions-wdk

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [X] Windows Server 2022

**Comment by maxim-lobanov** [comment]
Hello @thhous-msft , are you willing to submit PR?

**Comment by al-cheb** [comment]
As per discussion with @thhous-msft , there are not public links to download WDK/SDK in CI, we should wait an official release.

**Comment by miketimofeev** [comment]
@thhous-msft please re-open this one or open a new issue when the public release is available.
Thank you!

**Comment by miketimofeev** [comment]
@thhous-msft thanks for the update! We will take care of adding wdk to win2022

**Comment by johnstep** [comment]
We also need the WDK. How about adding it and including a release note in the image readme?

**Comment by namazso** [comment]
@al-cheb  I don't think anyone is going to debug drivers with the VS gui in a CI pipeline, so the regression is not relevant to this issue, you could simply just not install the debug extensions.

**Comment by al-cheb** [comment]
@namazso , I agree but it breaks VS first initialization creating additional windows with errors.

**Comment by namazso** [comment]
If you don't install it it doesn't. It's optional in the WDK installer

**Comment by johnstep** [comment]
@al-cheb Here is the full list of features from `wdksetup.exe /help`:
```
Windows Driver Kit - Windows 10.0.22621.1
---------------------------
Available features: (Features marked with * can be downloaded but cannot be installed on this computer)

   OptionId.WindowsDriverKitComplete
   OptionId.WindowsDriverKitARMAddons
   OptionId.WDKVisualStudioDev17
   OptionId.WDKVisualStudioDownlevel
   OptionId.ARMSoftwareDevelopmentKit
   OptionId.ARMWindowsDesktopDebuggers
   OptionId.MinWLPC
```
For CI pipelines, the first is likely sufficient: `wdksetup.exe /features OptionId.WindowsDriverKitComplete /quiet`

**Comment by kouzhudong** [comment]
how to use it?
can any tell me?
