### ISSUE TITLE
repository conflict

### ISSUE THREAD

**Issue by pheiduck** [actions/virtual-environments#5236]
### Description

W: Conflicting distribution: https://packages.microsoft.com/ubuntu/20.04/prod focal InRelease (expected focal but got testing)
E: Repository 'https://packages.microsoft.com/ubuntu/20.04/prod focal InRelease' changed its 'Origin' value from 'microsoft-ubuntu-focal-prod focal' to 'microsoft-ubuntu-focal-prod testing'
E: Repository 'https://packages.microsoft.com/ubuntu/20.04/prod focal InRelease' changed its 'Label' value from 'microsoft-ubuntu-focal-prod focal' to 'microsoft-ubuntu-focal-prod testing'
E: Repository 'https://packages.microsoft.com/ubuntu/20.04/prod focal InRelease' changed its 'Codename' value from 'focal' to 'testing'

### Virtual environments affected

- [ ] Ubuntu 18.04
- [X] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

https://github.com/microsoft/vscode/runs/5560140312?check_suite_focus=true

### Expected behavior

no repository conflict by default

### Actual behavior

repository conflict present

### Repro steps

Spin up ubuntu-latest Action
Try to update repo install or update pkgs

**Comment by gamegine** [comment]
I have the same issue on my run
https://github.com/gamegine/pv-utility/runs/5559983985
```
 Current runner version: '2.288.1'
Operating System
  Ubuntu
  20.04.4
  LTS
Virtual Environment
  Environment: ubuntu-20.04
  Version: 20220227.1
  Included Software: https://github.com/actions/virtual-environments/blob/ubuntu20/20220227.1/images/linux/Ubuntu2004-Readme.md
  Image Release: https://github.com/actions/virtual-environments/releases/tag/ubuntu20%2F20220227.1
```
but the update works on the version 18.04
https://github.com/gamegine/pv-utility/runs/5560467171
```
Current runner version: '2.288.1'
Operating System
  Ubuntu
  18.04.6
  LTS
Virtual Environment
  Environment: ubuntu-18.04
  Version: 20220306.1
  Included Software: https://github.com/actions/virtual-environments/blob/ubuntu18/20220306.1/images/linux/Ubuntu1804-Readme.md
  Image Release: https://github.com/actions/virtual-environments/releases/tag/ubuntu18%2F20220306.1
```

**Comment by PartialVolume** [comment]
I'm seeing this same issue today [https://github.com/PartialVolume/nwipe/runs/5560126486?check_suite_focus=true](https://github.com/PartialVolume/nwipe/runs/5560126486?check_suite_focus=true)

**Comment by mimartin12** [comment]
Runners are working for me now.
https://github.com/actions/virtual-environments/issues/5237

**Comment by PartialVolume** [comment]
Working for me now too. 👍

**Comment by alepauly** [comment]
The team that maintains the repositories at packages.microsoft.com confirmed the issue was resolved: https://github.com/microsoft/linux-package-repositories/issues/3
