### ISSUE TITLE
Add Go version 1.18

### ISSUE THREAD

**Issue by mikemadden42** [actions/virtual-environments#5242]
### Tool name

Go

### Tool license

https://github.com/golang/go/blob/master/LICENSE

### Add or update?

- [x] Add
- [ ] Update

### Desired version

1.18

### Approximate size

135 MB

### Brief description of tool

Go is an open source programming language that makes it easy to build simple, reliable, and efficient software.

### Virtual environments affected

- [X] Ubuntu 18.04
- [X] Ubuntu 20.04
- [X] macOS 10.15
- [X] macOS 11
- [X] Windows Server 2016
- [X] Windows Server 2019
- [X] Windows Server 2022

### Are you willing to submit a PR?

Yes

**Comment by maxim-lobanov** [comment]
Hello, thank you for feature request.
Go 1.18 is available through `actions/setup-go` task: https://github.com/actions/setup-go

As for the default Go version on images, we will update it later with proper announcement. Usually, we wait for some time after release before updating default versions. Using setup tasks is the recommended approach.
