### ISSUE TITLE
Package (`libc++1-8`) seems to be missing from azure focal universe mirror

### ISSUE THREAD

**Issue by 2opremio** [actions/virtual-environments#5245]
### Description

```
sudo wget -qO - https://apt.stellar.org/SDF.asc | APT_KEY_DONT_WARN_ON_DANGEROUS_USAGE=true sudo apt-key add -
sudo bash -c 'echo "deb https://apt.stellar.org focal unstable" > /etc/apt/sources.list.d/SDF-unstable.list'
sudo apt-get update && sudo apt-get install -y stellar-core=18.0.3-746.f3baea6.focal
```

fails with:

```
The following packages have unmet dependencies:
 stellar-core : Depends: libc++1-8 but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

which just worked before

### Virtual environments affected

- [ ] Ubuntu 18.04
- [X] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Version: 20220227.1

See: https://github.com/stellar/go/runs/5577252723?check_suite_focus=true

### Is it regression?

I believe so, since it used to work before, with the same GitHub actions code, see https://github.com/stellar/go/runs/5478828050?check_suite_focus=true

### Expected behavior

The package installation should work (as it does in stock ubuntu 20.04).

It also worked previously with the same GitHub action, see https://github.com/stellar/go/runs/5478828050?check_suite_focus=true

### Actual behavior

See the description

### Repro steps

```
sudo wget -qO - https://apt.stellar.org/SDF.asc | APT_KEY_DONT_WARN_ON_DANGEROUS_USAGE=true sudo apt-key add -
sudo bash -c 'echo "deb https://apt.stellar.org focal unstable" > /etc/apt/sources.list.d/SDF-unstable.list'
sudo apt-get update && sudo apt-get install -y stellar-core=18.0.3-746.f3baea6.focal
```

**Comment by mikhailkoliada** [comment]
@2opremio hello!

Thanks for the report, we will take a look.

**Comment by 2opremio** [comment]
The action seems to work again (without any relevant changes on our side), so it seems like a transient error which hits us from time to time.

We've already had two occurrences of the problem, with a duration of ~2 days each.

**Comment by mikhailkoliada** [comment]
@2opremio yes, it might be some weird networking issue (I could not reproduce this as well) :(

I am going to close the ticket now, feel free to reach us out if you have questions left.

**Comment by 2opremio** [comment]
Please reopen. We are having the same problem again https://github.com/stellar/go/runs/5772310302?check_suite_focus=true

**Comment by jacekn** [comment]
Would somebody on the Github side be able to confirm reasons for the `libc++1-10` package to be installed and confirm timeline?

From what we saw:
* everything was fine until 27th of February
* things broke after 27th of February
* things started working again around 21st of March
* they broke again on 31st of March

If this timing matches configuration changes to the image that would confirm root cause @2opremio found. It would be useful to know what's the desired state (package installed or not installed) and reasons for changes to it.

**Comment by jacekn** [comment]
The only repository we add is our own, it's `apt.stellar.org`. We test the repository regularly and build ubuntu 20.04 based docker images using it without problems so we know for sure that the `stellar-core` package is installable on a fresh Ubuntu 20.04.

As my colleague @2opremio mentioned forcing the `libc++1-10` to be removed fixes the problem and we can successfully install `staller-core` and its dependencies. Please note that the problem disappeared for us a few times already but it keeps coming back so maybe the image you're testing with is not affected?

Also please note that `libc++1` is not quite the same as `libc++1-8` or `libc++1-10`. `libc++1` is a virtual package that will pull `libc++1-10` (exact version is `libc++1-10_10.0.0-4ubuntu1`) while we need `libc++1-8` (exact version is `libc++1-8_8.0.1-9`)

**Comment by mikhailkoliada** [comment]
I have just checked the installation combination of libc++1-10 and libc++1-8 on the hosted ubuntu runners:

- by default we are having the version 10 installed
- version 8 can be installed flawlessly, apt just notifies you of the package's ongoing downgrade

**Comment by mikhailkoliada** [comment]
To clarify, I tested on the following pipeline (azure devops is used here by the image for azure devops and github actions is the same so you can easily reproduce it on gh with slightly different syntax)

```
trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: none

- bash: |
    sudo apt-cache policy libc++1-10
  displayName: show 10

- bash: |
    sudo apt-cache policy libc++1-8
  displayName: show 8

- bash: |
    sudo apt-get install libc++1-10
    sudo apt-get install libc++1-8
  displayName: conflict
  ```
On the conflict stage smooth downgrade happens.
I am afraid we are unable to provide more help here, but if you have more details please reach us and let us know!
