### ISSUE TITLE
Set env is not working for powershell, pwsh, cmd

### ISSUE THREAD

**Issue by jyeros** [actions/virtual-environments#5251]
### Description

According to the [doc](https://github.com/jyeros/github-action-set-env/actions/runs/1999199923). After do this `echo "myenv=myval" >> $GITHUB_ENV`, all subsequent steps in the job will have access to `myenv`. It is not working on `pwsh`.

### Virtual environments affected

- [X] Ubuntu 18.04
- [X] Ubuntu 20.04
- [X] macOS 10.15
- [X] macOS 11
- [ ] Windows Server 2016
- [X] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

Build: https://github.com/jyeros/github-action-set-env/actions/runs/1999252431, get env step is returning empty, and the environment set in that step is empty too for pwsh, cmd and powershell.
![image](https://user-images.githubusercontent.com/43852295/158840849-2833d86a-c75e-46db-9ee6-e3234f75ecb4.png)

```yaml
windows-2022:
  Version: 20220306.1
  
windows-2019:
  Version: 20220306.1
```

### Expected behavior

Env should be available in all subsequent steps for pwsh, powershell and cmd.

### Actual behavior

Env is available in all subsequent steps only for bash and sh.

### Repro steps

Steps in this workflow https://github.com/jyeros/github-action-set-env/blob/bae28c0c038db7c08438736110eaea0d3de2cbb2/.github/workflows/main.yaml

**Comment by maxim-lobanov** [comment]
Hi @jyeros , it is expected behavior.
The syntax that you use is valid only in bash and doesn't suit PowerShell.
In powershell, you should use `echo "VERSION=5" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append`

**Comment by panekj** [comment]
It is mentioned also here: https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#environment-files

**Comment by jyeros** [comment]
> Hi @jyeros , it is expected behavior. The syntax that you use is valid only in bash and doesn't suit PowerShell. In powershell, you should use `echo "VERSION=5" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append`

Thanks. I just copied and pasted from the doc, and I forgot to add the `env:` prefix needed for powershell. I am using `pwsh`, so I think I don't need the workaround mentioned for powershell.

**Comment by nimrod365** [comment]
the option described here (https://github.com/orgs/community/discussions/25713) also works
"VERSION=5" >> $env:GITHUB_ENV
