### ISSUE TITLE
Update/Add Xcode 13.3

### ISSUE THREAD

**Issue by jcarltonj** [actions/virtual-environments#5253]
### Tool name

Xcode 13.3

### Tool license

Apple

### Add or update?

- [ ] Add
- [X] Update

### Desired version

13.3

### Brief description of tool

Xcode 13.3.  Xcode 13.2.1 doesn't support version 2 of package.resolved files which prevents projects built on 13.2.1 to 13.3

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [X] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [ ] Windows Server 2022

**Comment by jessesquires** [comment]
One issue here, which I imagine is part of the delay, is that Xcode 13.3 now **requires macOS 12 Monterey**. It cannot be installed on macOS 11.

**Comment by jcarltonj** [comment]
Do they have a beta of macOS 12 yet? My code requires some of the tools that Xcode 13.3 added

**Comment by JoeMatt** [comment]
XCode 13.3 breaks Swift `Package.resolved` formatting. Very annoying for a point release to do.

**Comment by cbaker6** [comment]
To fix the `Package.resolved` issue, you can just add it to your `.gitignore`, then remove it from your repo, and you can build across Xcode versions without an issue. I build locally with Xcode 13.3, but still use Actions to build in CI https://github.com/netreconlab/CareKitSample-ParseCareKit/pull/90

**Comment by jcarltonj** [comment]
> To fix the `Package.resolved` issue, you can just add it to your `.gitignore`, then remove it from your repo, and you can build across Xcode versions without an issue. I build locally with Xcode 13.3, but still use Actions to build in CI https://github.com/netreconlab/CareKitSample-ParseCareKit/pull/90

This really isn't a solution. The package.resolve ensures that the pipeline is using the same packages as the user. I don't want the pipeline to accidentally grab newer versions of the packages that we have not tested.

**Comment by dungi** [comment]
> > To fix the `Package.resolved` issue, you can just add it to your `.gitignore`, then remove it from your repo, and you can build across Xcode versions without an issue. I build locally with Xcode 13.3, but still use Actions to build in CI [netreconlab/CareKitSample-ParseCareKit#90](https://github.com/netreconlab/CareKitSample-ParseCareKit/pull/90)
> 
> This really isn't a solution. The package.resolve ensures that the pipeline is using the same packages as the user. I don't want the pipeline to accidentally grab newer versions of the packages that we have not tested.

What about setting the version to exact the version you need? 
<img width="426" alt="image" src="https://user-images.githubusercontent.com/3323565/159220970-ad8c45b2-cb08-4982-af94-b9f7301784c9.png">

We use Xcodegen to sync something like this.

**Comment by cbaker6** [comment]
> This really isn't a solution. The package.resolve ensures that the pipeline is using the same packages as the user. I don't want the pipeline to accidentally grab newer versions of the packages that we have not tested 

This doesn’t mean, “really isn’t a solution”. If you are really concerned about, “I don't want the pipeline to accidentally grab newer versions of the packages that we have not tested”, you should setup your Package.swift file to protect against this as @dungi mentioned. If your Package.swift file allows newer versions, then it’s, “no accident” or a “developer oversight”.

My comment is for those who want to use what’s currently available in GitHub actions, but have upgraded locally to the newer Xcode. If Actions can’t add the new Xcode immediately, my comment is a workaround

**Comment by mikhailkoliada** [comment]
@jcarltonj Hello! Thanks for the report!

The new version will be automatically deployed upon new macOS images rollout

**Comment by mikhailkoliada** [comment]
I have actually forgotten to mention that xcode 13.3 is only available for macOS monterey (my bad), we have no monterey available yet that is why we can not help anyone with this issue right now, I have to close this issue for the time being.

**Comment by jcarltonj** [comment]
> > This really isn't a solution. The package.resolve ensures that the pipeline is using the same packages as the user. I don't want the pipeline to accidentally grab newer versions of the packages that we have not tested 
> 
> 
> 
> This doesn’t mean, “really isn’t a solution”. If you are really concerned about, “I don't want the pipeline to accidentally grab newer versions of the packages that we have not tested”, you should setup your Package.swift file to protect against this as @dungi mentioned. If your Package.swift file allows newer versions, then it’s, “no accident” or a “developer oversight”.
> 
> 
> 
> My comment is for those who want to use what’s currently available in GitHub actions, but have upgraded locally to the newer Xcode. If Actions can’t add the new Xcode immediately, my comment is a workaround

"Apple directly states that you should commit package resolved. Most projects that contain or depend on Swift packages don’t require additional configuration. However, be sure to commit your project’s Package.resolved file to your Git repository. This ensures a reliable CI workflow that always uses the expected version of a package dependency. If your project depends on packages that require authentication, or you need to use your Mac’s Git tooling instead of the tooling which comes bundled with Xcode, you may need to perform additional configuration." https://developer.apple.com/documentation/swift_packages/building_swift_packages_or_apps_that_use_them_in_continuous_integration_workflows

**Comment by bdrelling** [comment]
Agreed, we need to understand if this will be added and what the ETA is. Closing this issue doesn't help your consumers track the status at all, and it doesn't even really make sense from a product management perspective either. If we closed Jira tickets that we just weren't ready to work on or were blocked by, we'd have a very clean and very unhelpful backlog.

GitHub Actions takes far too long to add proper macOS and Xcode versions sometimes. I understand there are complexities and limitations with what Apple provides, but I also know that many other CI providers are able to get these rolled out much, much faster.

Please consider re-opening this issue until it has been properly resolved.

**Comment by EliteTechnicalCare** [comment]
Why is this issue closed? Fairly significant issue.

**Comment by JoeMatt** [comment]
> To fix the `Package.resolved` issue, you can just add it to your `.gitignore`, then remove it from your repo, and you can build across Xcode versions without an issue. I build locally with Xcode 13.3, but still use Actions to build in CI [netreconlab/CareKitSample-ParseCareKit#90](https://github.com/netreconlab/CareKitSample-ParseCareKit/pull/90)

technically this would work, but not ideal for a few reasons.

1. Reloading spm packages is very fragile in xcode and would require a few restarts
2. Other developers could be on different versions

Would work for your own repos maybe, but team repos, no.

**Comment by JoeMatt** [comment]
> > This really isn't a solution. The package.resolve ensures that the pipeline is using the same packages as the user. I don't want the pipeline to accidentally grab newer versions of the packages that we have not tested
> 
> This doesn’t mean, “really isn’t a solution”. If you are really concerned about, “I don't want the pipeline to accidentally grab newer versions of the packages that we have not tested”, you should setup your Package.swift file to protect against this as @dungi mentioned. If your Package.swift file allows newer versions, then it’s, “no accident” or a “developer oversight”.
> 
> My comment is for those who want to use what’s currently available in GitHub actions, but have upgraded locally to the newer Xcode. If Actions can’t add the new Xcode immediately, my comment is a workaround

sorry man, this just doesn't work in the real world at all.

You realize upstream dependencies may have no exact requirements too?
Please don't give bad advice, and especially don't double down on it.

**Comment by cbaker6** [comment]
> Do you realize upstream dependencies may have no exact version requirements too?

Sounds like you should do better job at selecting your dependencies...

> Please don't give bad advice, and especially don't double down on it.

Who are you to tell me what to suggest and not to suggest?

> Manually cloning all your dependencies and ditching SPM is a "work-around" too by this definition.

This makes no sense and isn't part of what I defined, do make stuff up

My suggestion was a workaround, if it doesn't work for you, guess what, don't use it.

**Comment by jcarltonj** [comment]
Again, just going off of what apple suggest when they state "be sure to commit your project’s Package.resolved file to your Git repository. This ensures a reliable CI workflow that always uses the expected version of a package dependency."

https://developer.apple.com/documentation/swift_packages/building_swift_packages_or_apps_that_use_them_in_continuous_integration_workflows

**Comment by JoeMatt** [comment]
> > Do you realize upstream dependencies may have no exact version requirements too?
> 
> Sounds like you should do better job at selecting your dependencies...

What a ridiculous statement. 
Compare you github profile to mine and get back to me on 'best practices'

Stop doubling down on bad advice to save face.

**Comment by APvanGrootel** [comment]
> I have actually forgotten to mention that xcode 13.3 is only available for macOS monterey (my bad), we have no monterey available yet that is why we can not help anyone with this issue right now, I have to close this issue for the time being.

And when is it going to be re-opened? I have to deploy 20+ apps in two weeks. Why is MacOS Monterey still not available to you?

**Comment by miketimofeev** [comment]
@APvanGrootel please take a look at this comment https://github.com/actions/virtual-environments/discussions/5370#discussioncomment-2544316

**Comment by APvanGrootel** [comment]
@miketimofeev Thanks. I have sent in the request. Do you have any idea how long this can take, before the request is granted?

**Comment by miketimofeev** [comment]
@APvanGrootel we onboard new users weekly, the next turn will be this Friday (04\22)

**Comment by APvanGrootel** [comment]
@miketimofeev Thanks. That would be great. I have sent it in a few times, so it could be that you received a lot of requests from me.

**Comment by samitaha2** [comment]
We have an issue where our app crashes in 13.2 but not 13.3 because Xcode 13.3 contains Swift 5.6: 
https://stackoverflow.com/questions/71410242/swift-mainactor-not-enforced-on-subclasses

**Comment by APvanGrootel** [comment]
> @APvanGrootel we onboard new users weekly, the next turn will be this Friday (04\22)

@miketimofeev Should I get an email when it is approved? I didn't get one I am afraid.

**Comment by APvanGrootel** [comment]
@miketimofeev Any update on this? I have to deploy 20+ apps tomorrow morning. Doing this by hand takes me more than 5 hours.

**Comment by miketimofeev** [comment]
@APvanGrootel we have opened macOS-12 for all GH actions users. For the AzDO ones we will sent an e-mail once approved.

**Comment by APvanGrootel** [comment]
@miketimofeev Thank you! So I can use Xcode 13.3.1?

**Comment by miketimofeev** [comment]
@APvanGrootel if you use GH Actions — yes

**Comment by APvanGrootel** [comment]
@miketimofeev I use GHA. This is what I get when I switch to the latest stable version, after
```
...
runs-on: macos-latest
...
- uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
...
```
```
Run maxim-lobanov/setup-xcode@v1
Switching Xcode to version 'latest-stable'...
Xcode is set to 13.2.1 (13C100)
```
Why is it not switching to 13.3.1?

**Comment by miketimofeev** [comment]
@jcarltonj yes, as `macOS-latest` spec will be switched to use `macOS-12` when we are out of beta (most likely in July-Aug)

**Comment by APvanGrootel** [comment]
@miketimofeev OK, thanks. That is probably where the confusion came from. maxim-lobanov/setup-xcode@v1 xcode-version has a concept of `latest-stable` and `latest`. The latter takes (or should take) beta's into account. But that is not the case with `macos-latest`, since there is no `macOS-latest-stable`. Thanks for your help. I managed this weekend to automate our releases with this.
