### ISSUE TITLE
Add or speed-up (cache) PowerShell module Microsoft.Graph

### ISSUE THREAD

**Issue by krispenner** [actions/virtual-environments#5255]
### Tool name

Microsoft.Graph (PowerShell module)

### Tool license

https://docs.microsoft.com/en-us/legal/mdsa?redirectedfrom=MSDN

### Add or update?

- [X] Add
- [ ] Update

### Desired version

latest

### Approximate size

14KB

### Brief description of tool

Many Azure pipelines are managing Azure and require access to Azure service principals, roles, groups, etc...
Installing the PowerShell module Microsoft.Graph takes a considerable amount of time, I'm not sure if that time is spent downloading or installing or both. If you cannot add the module to the images, is there any way you or I can speed up the install step?

### URL for tool's homepage

https://www.powershellgallery.com/packages/Microsoft.Graph

### Provide a basic test case to validate the tool's functionality.

```bash
(Get-Module -Name "Microsoft.Graph" -ListAvailable)[0].Version -eq "1.9.3"
```

### Virtual environments affected

- [X] Ubuntu 18.04
- [X] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [X] Windows Server 2019
- [X] Windows Server 2022

### Can this tool be installed during the build?

```bash
Install-Module -Name "Microsoft.Graph" -RequiredVersion "1.9.3" -Force -Scope CurrentUser -AllowClobber
Import-Module -Name "Microsoft.Graph" -RequiredVersion "1.9.3" -Force
```

### Tool installation time in runtime

3:20 (three minutes and twenty seconds)

### Are you willing to submit a PR?

I can try!

**Comment by mikhailkoliada** [comment]
@krispenner Hello! Thank you for the report, we will decide on adding the module to the images.

**Comment by krispenner** [comment]
@mikhailkoliada Oh that’s great news. Sorry I didn’t realize it was on the Windows images, I didn’t see it listed on the installed packages list. Maybe I missed it or maybe you could update the docs if needed.

Any ballpark eta on when it would be added to Ubuntu images for use?

**Comment by miketimofeev** [comment]
@krispenner it's here
https://github.com/actions/virtual-environments/blob/af8332e66d6fc43f786eba49c0d7480c5f9de1b8/images/win/Windows2022-Readme.md?plain=1#L499
We will add the module to Ubuntu in next two weeks.

**Comment by krispenner** [comment]
Thank you very much, I can confirm module `Microsoft.Graph v1.9.3` is installed on the `unbuntu-latest` images. This is great!
I will leave you to close the issue in case you have other tasks that need to be finalized first.

**Comment by miketimofeev** [comment]
All the images have been updated.
