### ISSUE TITLE
 import numpy as np\r\nModuleNotFoundError: No module named \'numpy\'\r\n'

### ISSUE THREAD

**Issue by MOMOANNIE** [actions/virtual-environments#5257]
### Description

When I use pipenv to create a virtual environment of python 3.10.3 and then run my project in that virtual environment, the following problem occurs:
![1](https://user-images.githubusercontent.com/26375536/159216565-50114f7f-37c4-4ba4-9303-9451d1e646ab.png)

The remove_all_0_layers.py  reports the error points to this place:
![2](https://user-images.githubusercontent.com/26375536/159216783-789d1e88-55fe-40c8-8343-250366612eae.png)

But I use` import numpy` in this virtual environment, and it shows that it is installed successfully. Why is there no such module?

![3](https://user-images.githubusercontent.com/26375536/159217093-1f347432-a4dc-4750-9f95-21cd223c583e.png)

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [X] Windows Server 2016
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

None available, testing locally with Pipenv

### Repro steps

1、Checkout releases/Windows10/20220316
2、Build packer image
3、Wait for failure

**Comment by mikhailkoliada** [comment]
@MOMOANNIE Hi! Thank you for the report!

Could you please elaborate what are you trying to do there? Because now it looks like you do some manipulations locally and this is unclear how we can help you in such a situation.

**Comment by MOMOANNIE** [comment]
> @MOMOANNIE Hi! Thank you for the report!
> 
> Could you please elaborate what are you trying to do there? Because now it looks like you do some manipulations locally and this is unclear how we can help you in such a situation.

I want to use the numpy module, but when I import numpy, the script will give me an error message: `in <module>\r\n    import numpy as np\r\nModuleNotFoundError: No module named \'numpy\'\r\n'`

![2](https://user-images.githubusercontent.com/26375536/159606467-e09e449e-2802-42fc-98aa-0e55fce9ddeb.png)


but I have installed numpy as follows:
![1](https://user-images.githubusercontent.com/26375536/159605793-95b408f5-4fef-4982-8b58-cf5e32209177.png)


I don't know why this is happening, I am using python3.10.3，when I use python3.9, python3.6 , this error will not appear

**Comment by mikhailkoliada** [comment]
@MOMOANNIE Hi!

Sorry, I am not completely following here, it seems you are trying to import numpy somewhere locally, if this is true, I do not really understand how the github images are relevant here. Could you please be kind and provide more context regarding your workflow?

Thanks!

**Comment by mikhailkoliada** [comment]
@MOMOANNIE As there is no progress I am currently going to close this issue. Please feel free to reach us again if you have new details and/or questions left.
