### ISSUE TITLE
nuget version going backwards from windows 2019 to windows 2022

### ISSUE THREAD

**Issue by SamWhitby** [actions/virtual-environments#5258]
### Description

**Situation**
We are using a windows-latest vm image for our pipelines that makes use of the NuGetCommand@2 task. The latest windows os version has recently been changed from windows-2019 to windows-2022. 

**Problem**
The problem is that the latest vm image seems to have a old version of nuget installed on it as the NuGetCommand@2 task is now using version 4.1.0. This was previously using 5.8.0 for the windows 2019 image. This old version does not work with our software.

The version specified in the docs say windows 2022 should be using 6.1.0.106 https://github.com/actions/virtual-environments/blob/main/images/win/Windows2022-Readme.md#package-management

I know i can install the latest version of nuget in a separate task, however i would prefer not to do this and just use the default version installed on the vm image assuming it should be the latest.

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

 2.200.2

### Expected behavior

something akin to how windows 2019 image worked
![image](https://user-images.githubusercontent.com/3334161/158879004-794f41e8-707a-49b1-af53-b182bda61e90.png)
![image](https://user-images.githubusercontent.com/3334161/158878752-2ab59dce-d805-462e-a55f-0e90ae3d43ea.png)

### Actual behavior

windows 2022
![image](https://user-images.githubusercontent.com/3334161/158879234-078fab17-47b1-4ba8-b6a7-39f3ee2b7e69.png)
![image](https://user-images.githubusercontent.com/3334161/158879626-7beecb5e-3bf2-4487-9cfb-3555edcc4e71.png)

### Repro steps

Create a pipeline using windows latest image and add the NuGetCommand@2 task. Run and observe the version used is an old one.

**Comment by maxim-lobanov** [comment]
Hello @SamWhitby , 
Both Windows Server 2019 and 2022 contains NuGet 6.1.0.106. ([2019 docs](https://github.com/actions/virtual-environments/blob/main/images/win/Windows2019-Readme.md#package-management), [2022 docs](https://github.com/actions/virtual-environments/blob/main/images/win/Windows2022-Readme.md#package-management)).
All `NuGet*` related tasks in ADO brings its own version of NuGet that doesn't depend on image somehow. Please log an issue in https://github.com/microsoft/azure-pipelines-tasks repository if you see any issues with this task and NuGet version
