### ISSUE TITLE
Update Go to v1.18

### ISSUE THREAD

**Issue by g14com0** [actions/virtual-environments#5262]
### Tool name

Go

### Tool license

MIT

### Add or update?

- [ ] Add
- [X] Update

### Desired version

1.18

### Virtual environments affected

- [X] Ubuntu 18.04
- [X] Ubuntu 20.04
- [X] macOS 10.15
- [X] macOS 11
- [X] Windows Server 2016
- [X] Windows Server 2019
- [X] Windows Server 2022

### Are you willing to submit a PR?

yes

**Comment by miketimofeev** [comment]
@g14com0 thank you for your contribution!
We will take care of macOS.

**Comment by ddobranic** [comment]
@g14com0 Update has been merged and will be deployed this week.

**Comment by azboyzranch** [comment]
> ### Tool name
> Go
> 
> ### Tool license
> MIT
> 
> ### Add or update?
> * [ ]  Add
> * [x]  Update
> 
> ### Desired version
> 1.18
> 
> ### Approximate size
> _No response_
> 
> ### Brief description of tool
> _No response_
> 
> ### URL for tool's homepage
> _No response_
> 
> ### Provide a basic test case to validate the tool's functionality.
> _No response_
> 
> ### Virtual environments affected
> * [x]  Ubuntu 18.04
> * [x]  Ubuntu 20.04
> * [x]  macOS 10.15
> * [x]  macOS 11
> * [x]  Windows Server 2016
> * [x]  Windows Server 2019
> * [x]  Windows Server 2022
> 
> ### Can this tool be installed during the build?
> _No response_
> 
> ### Tool installation time in runtime
> _No response_
> 
> ### Are you willing to submit a PR?
> yes

**Comment by ddobranic** [comment]
@g14com0 Images with Go update are deployed.
