### ISSUE TITLE
Supported .NetFramework versions

### ISSUE THREAD

**Issue by marceardz** [actions/virtual-environments#5263]
### Description

Seems like .NET Framework 4.6.1 is not supported by the 2022 agent. Could you please share which are the supported versions for it?

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

AzureDevOps Image version Windows-2022
https://microsoftit.visualstudio.com/OneITVSO/_build/results?buildId=7717840&view=results

### Is it regression?

Windows-2019. https://microsoftit.visualstudio.com/OneITVSO/_build/results?buildId=7717840&view=logs&j=fd490c07-0b22-5182-fac9-6d67fe1e939b&t=6a7ac225-8257-51f6-8eed-20c2e5179b9e

### Repro steps

Agent is now pointing to Windows-2022, would like to know which are the supported versions for .NET Framework as with the 2019 image everything was working as expected with version 4.6.1.

**Comment by maxim-lobanov** [comment]
Hello @marceardz , Windows Server 2022 docs contain the list of installed versions: https://github.com/actions/virtual-environments/blob/main/images/win/Windows2022-Readme.md#net-core-sdk
You can also switch your pipeline to use Windows Server 2019 - just use `windows-2019` label instead of `windows-latest`. We don't have plans to deprecate Windows Server 2019 in near future.

**Comment by miketimofeev** [comment]
@marceardz the minimal 4.6.* version is 4.6.2 judging by the components list:
<img width="901" alt="image" src="https://user-images.githubusercontent.com/48208649/159436586-c37db55b-6437-4163-a3e1-506817efa25a.png">
https://docs.microsoft.com/en-us/visualstudio/install/workload-component-id-vs-enterprise?view=vs-2022
This component is already installed on the image so feel free to change your project from 4.6.1 to 4.6.2
https://github.com/actions/virtual-environments/blob/af8332e66d6fc43f786eba49c0d7480c5f9de1b8/images/win/Windows2022-Readme.md?plain=1#L265
I'm going to close the issue but feel free to contact us if you have any concerns.
Thank you!
