### ISSUE TITLE
Error RC1015: cannot open include file 'afxres.h'

### ISSUE THREAD

**Issue by kuhnboy** [actions/virtual-environments#5264]
### Description

I am having an issue building an Azure Devops Pipeline. We have an msbuild step that builds a collection of solutions. I am experiencing an error with both the 2019 and 2022 vmImage.

I have seen: https://github.com/actions/virtual-environments/issues/3957 which I would think addresses the issue but there seems to still be an issue from the Resource Compiler side of things.

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

Environment: windows-2022
Version: 20220316.1
Included Software: https://github.com/actions/virtual-environments/blob/win22/20220316.1/images/win/Windows2022-Readme.md
Image Release: https://github.com/actions/virtual-environments/releases/tag/win22%2F20220316.1

### Expected behavior

Resource Compiler should exit with no error. (C:\Program Files (x86)\Windows Kits\10\bin\10.0.22000.0\x86\rc.exe /l"0x0409" /ID:\a\1\s\src\MyProject\\inc /nologo /fo"obj\Debug\MyProject.res" Resources\MyProject.rc)

### Actual behavior

Error RC1015: cannot open include file 'afxres.h'

### Repro steps

Add a resource (rc) file to a build that has an #include statement for afxres.h.

**Comment by medicalbio** [comment]
n

**Comment by miketimofeev** [comment]
@kuhnboy hi! Could you please prepare a repo with repro steps? It will speed up the investigation.

**Comment by kuhnboy** [comment]
Hello,
I have a sample project at: https://rkuhn0931@dev.azure.com/rkuhn0931/OldWindowsApp/_git/OldWindowsApp

You can see if it is run in a pipeline that the error:

```
##[error]OldWindowsApp\OldWindowsApp.rc(10,0): Error RC1015: cannot open include file 'afxres.h'.
```

Upon further investigation, changing the platform version from v142 to v143 will fix the build issue. Older applications that don't seem to be MFC library dependent still depend on artifacts like afxres.h and afxres.rc. 

It does seem on the windows 2022 image that MSVC v142 is installed. Therefore my expectation would be that C++ MFC for v142 would also be installed (which I believe is the package in Visual Studio that would fix this issue).

**Comment by vsafonkin** [comment]
Hi @kuhnboy, the required Visual Studio components were added to Windows-2022, it will be available after next Windows runner rollout, in two weeks approximately.

**Comment by kuhnboy** [comment]
Thank you @vsafonkin.

**Comment by al-cheb** [comment]
@kuhnboy, The new image rollout has been completed.
