### ISSUE TITLE
Build Pipeline's Agent Specification Ignored

### ISSUE THREAD

**Issue by osdagoso** [actions/virtual-environments#5268]
### Description

The agent specification in one of our build pipeline seems to be ignored every time we attempt to create a run, forcibly replaced by the deprecated 'vs2017-win2016' agent. We've tried editing our pipeline configuration to set the agent specification to 'windows-2019', 'windows-2022' and 'windows-latest' as well as manually running the pipeline with each of those agents, but the issue persists.

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [X] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

Versions: 'windows-2019', 'windows-2022' and 'windows-latest'

https://microsoftit.visualstudio.com/OneITVSO/_build/results?buildId=7729420&view=results

### Is it regression?

https://microsoftit.visualstudio.com/OneITVSO/_build/results?buildId=7670813&view=results

### Expected behavior

We expect our build run to be linked to the specified agent.

### Actual behavior

New build runs are linked to 'vs2017-win2016' agent, regardless of the agent specification.

### Repro steps

1. Go to Build Pipeline view
2. Create a new run, selecting a valid windows agent
3. Run will be created with 'vs2017-win2016' agent, regardless of the agent selected in the previous step, and fail

**Comment by miketimofeev** [comment]
HI @osdagoso!
There are two places where you can set up an agent spec. First one is here:
<img width="1491" alt="image" src="https://user-images.githubusercontent.com/48208649/159647968-0b9c8b37-95dd-4994-888d-cc89eacaedf8.png">
But then you override it with the `vs2017-win2016` here
<img width="1496" alt="image" src="https://user-images.githubusercontent.com/48208649/159648026-0e700634-1813-44a8-a76c-0728fe80290a.png">
You can choose to inherit the agent spec like this and the issue will be resolved
<img width="905" alt="image" src="https://user-images.githubusercontent.com/48208649/159648366-6356d811-9722-4ae5-96aa-46477363659b.png">

I'm going to close the issue. Feel free to contact us if you need any help.
Thank you!
