### ISSUE TITLE
Actions failing with Postgres out of memory errors

### ISSUE THREAD

**Issue by fjfish** [actions/virtual-environments#527]
**Describe the bug**
When running Actions we're seeing

PG::OutOfMemory: ERROR: out of shared memory
HINT: You might need to increase max_locks_per_transaction.

If you keep re-running it will eventually get through, must be some feature of the order the test run in. We don't have this problem locally so it's very hard to debug.

On your well-known competitor's site, we could tweak the Docker container parameters and get past this by setting max_locks_per_transaction

Can't seem to find that option on your CI

This is quite a common problem, so there must be a solution for it somewhere

**Area for Triage**: 

This triage URL appears to be dead?

**Question, Bug, or Feature?**: 

Question

**Virtual environments affected**
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Expected behavior**
A description of what you expected to happen.

Not see out of memory error for Postgres

**Actual behavior**
A description with steps to reproduce the issue. If your have a public example or repo to share,
please provide the link.

We don't have a public repo for this. Just a lot of tests.

**Comment by al-cheb** [comment]
Hello, @fjfish
We don't have pre-installed PostgreSQL server. If you want to install it and change config on Ubuntu:

```
jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
    - name: PostgreSql
      run: |
          sudo apt update
          sudo apt install postgresql postgresql-contrib
          sudo systemctl stop postgresql
          echo max_locks_per_transaction = 128 | sudo tee -a /etc/postgresql/10/main/postgresql.conf
          sudo systemctl start postgresql
          sudo -u postgres psql -c 'SHOW max_locks_per_transaction;'
```
![psql](https://user-images.githubusercontent.com/47745270/76292165-c31db100-62bf-11ea-84ae-e9cae070db54.JPG)

**Comment by fjfish** [comment]
Thank you - will test :)
