### ISSUE TITLE
ERR:No visual studio instance with SSIS runtime available in this machine.

### ISSUE THREAD

**Issue by bbawcom** [actions/virtual-environments#5275]
### Description

Using `windows-2022`, now `windows-latest`, I get an error attempting an SSIS_Build step:
```
ERR:No visual studio instance with SSIS runtime available in this machine.
```

This breaks our automated deployments of Integration Services projects.  I'm submitting this bug report to understand if the pipelines.yml task `SSISBuild@0` will be supported eventually in `windows-2022` and, if so, when it is released.

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

20220316.1 windows-2022

### Is it regression?

20220316.1 windows-2019

### Expected behavior

SSISBuild@0 task results in traversing project folders to build ispac files

### Actual behavior

SSISBuild@0 task fails because the required software is not included.

### Repro steps

Set up a pipelines.yml file for a repo that includes Visual Studio solutions containing Integration Services projects.

   steps:
    - task: SSISBuild@0
      inputs:
            projectPath: .\$(FOLDER_CONTAINING_PROJECTS)
            configuration: 'Development'
            outputPath: '$(Build.StagingDirectory)\Ispacs'

Execute the pipeline job.

**Comment by miketimofeev** [comment]
@bbawcom  I'm afraid Integration Services are not available for VS2022 at the moment
https://docs.microsoft.com/en-us/sql/ssdt/download-sql-server-data-tools-ssdt?view=sql-server-ver15#changes-in-ssdt-for-visual-studio-2022
Please continue using windows-2019 with VS2019.
I'm going to close the issue. Feel free to contact us if you have any concerns.
Thank you!
