### ISSUE TITLE
windows-2022 (windows-latest) does not have .NET 4.6.1 available

### ISSUE THREAD

**Issue by SenseiJoe** [actions/virtual-environments#5279]
### Description

Don't know if this was intended.
2022 Environment does not contain - Microsoft.Net.Component.4.6.1.TargetingPack

So my build using the image windows-latest fails to build app using .NET 4.6.1

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

Virtual Environment
Environment: windows-2022
Version: 20220316.1
Included Software: https://github.com/actions/virtual-environments/blob/win22/20220316.1/images/win/Windows2022-Readme.md
Image Release: https://github.com/actions/virtual-environments/releases/tag/win22%2F20220316.1

### Expected behavior

C:\Program Files\dotnet\sdk\6.0.201\Microsoft.Common.CurrentVersion.targets(1220,5): error MSB3644: The reference assemblies for .NETFramework,Version=v4.6.1 were not found. To resolve this, install the Developer Pack (SDK/Targeting Pack) for this framework version or retarget your application. You can download .NET Framework Developer Packs at https://aka.ms/msbuild/developerpacks 

Build FAILED.

C:\Program Files\dotnet\sdk\6.0.201\Microsoft.Common.CurrentVersion.targets(1220,5): error MSB3644: The reference assemblies for .NETFramework,Version=v4.6.1 were not found. To resolve this, install the Developer Pack (SDK/Targeting Pack) for this framework version or retarget your application. You can download .NET Framework Developer Packs at https://aka.ms/msbuild/developerpacks 

    0 Warning(s)
    1 Error(s)

### Actual behavior

Expect a successful build

### Repro steps

Target an application with .NET 4.6.1
Use windows-latest as the pipeline host.

**Comment by miketimofeev** [comment]
@SenseiJoe the minimal 4.6.* version is 4.6.2 judging by the components list:
<img width="901" alt="image" src="https://user-images.githubusercontent.com/48208649/159436586-c37db55b-6437-4163-a3e1-506817efa25a.png">
https://docs.microsoft.com/en-us/visualstudio/install/workload-component-id-vs-enterprise?view=vs-2022
This component is already installed on the image so feel free to either change your project from 4.6.1 to 4.6.2 or stick to windows-2019.
https://github.com/actions/virtual-environments/blob/af8332e66d6fc43f786eba49c0d7480c5f9de1b8/images/win/Windows2022-Readme.md?plain=1#L265
I'm going to close the issue but feel free to contact us if you have any concerns.
Thank you!

**Comment by SenseiJoe** [comment]
I'll see if the developer can change it.  But seems like it should be there anyway.
