### ISSUE TITLE
[All OSs] Go versions less than 1.16 will be removed and the default will be set to 1.17 on April, 11

### ISSUE THREAD

**Issue by ddobranic** [actions/virtual-environments#5280]
### Breaking changes

All pre-cached Go versions less than 1.16 will be removed from all operating systems. Version 1.17 will be set as the new default version.

### Target date

April 11, 2022.

### The motivation for the changes

According to our [Software and image guidelines
](https://github.com/actions/virtual-environments/blob/main/docs/software-and-images-guidelines.md) we support [3 latest minor versions of Go],
(https://endoflife.date/go) which are 1.16, 1.17 & 1.18 at the moment.

Version 1.17 will be the new default as it is most popular according to telemetry data.

### Possible impact

If your project depends on a pre-installed Go version 1.15 it can be broken.

### Virtual environments affected

- [X] Ubuntu 18.04
- [X] Ubuntu 20.04
- [X] macOS 10.15
- [ ] macOS 11
- [X] Windows Server 2016
- [X] Windows Server 2019
- [ ] Windows Server 2022

### Mitigation ways

To install any versions in runtime use:
- https://github.com/actions/setup-go action for GH actions
- https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/tool/go-tool?view=azure-devops task for AzDO

**Comment by nauil** [comment]
جميل جد @ #

- [ ] 
![Uploading 16502566231168533349594927354681.jpg…]()
