### ISSUE TITLE
Update LLVM to 14.0.0

### ISSUE THREAD

**Issue by mmuffins** [actions/virtual-environments#5285]
### Tool name

LLVM

### Tool license

Apache v2.0 

### Add or update?

- [ ] Add
- [X] Update

### Desired version

14.0.0

### Brief description of tool

LLVM 14.0 was released and is available on chocolatey, failing the builds for server 2016 and 2019 because their toolset manifest still check for version 13.

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [X] Windows Server 2016
- [X] Windows Server 2019
- [ ] Windows Server 2022

### Are you willing to submit a PR?

Yes

**Comment by miketimofeev** [comment]
@mmuffins please take a look at the comment https://github.com/actions/virtual-environments/pull/5286#issuecomment-1079553563
We will update llvm a bit later and announce it first.

**Comment by miketimofeev** [comment]
@FrancescElies hi! The announcement is right here https://github.com/actions/virtual-environments/issues/5835
