### ISSUE TITLE
macOS-latest does not compile with Clang/LLVM 13.0.1

### ISSUE THREAD

**Issue by ingo-h** [actions/virtual-environments#5287]
### Description

I try to use Clang/LLVM 13.0.1 on **macOS-latest** instead of default Clang/LLVM 13.0.0 but building fails with compiler errors. After some tries I end up to just build a simple `std::cout << "working" << std::endl;` but it doesn't. Here are the files I use:

cat CMakeLists.txt

    cmake_minimum_required(VERSION 3.18)
    project(build-on-macos VERSION 0.1
		    DESCRIPTION "Test how to build on github action for macOS"
		    HOMEPAGE_URL "https://github.com/ingo-h/build-on-macos.git")

    # specify the C++ standard
    set(CMAKE_CXX_STANDARD 11)
    set(CMAKE_CXX_STANDARD_REQUIRED ON)

    add_executable(build-macos
	    main.cpp
    )

cat main.cpp

    #include <iostream>

    int main() {
        std::cout << "working" << std::endl;
        return 0;
    }

cat ./.github/workflows/build_on_macos.yml

    name: Build on macOS

    on:
      push:
	branches: [ main ]

    jobs:
      Build_on_macOS:
	name: Build on macOS
	runs-on: macOS-latest

	strategy:
	  fail-fast: false

	steps:
	  - uses: actions/checkout@v2

	  - name: Configure
	    run: cmake -S . -B build -D CMAKE_C_COMPILER=$(brew --prefix llvm)/bin/clang -D CMAKE_CXX_COMPILER=$(brew --prefix llvm)/bin/clang

	  - name: Build
	    run: cmake --build build

	  - name: Execute
	    run: ./build/build-macos

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] #5293
- [ ] macOS 10.15
- [X] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

My last test run:
https://github.com/ingo-h/build-on-macos/runs/5698699650?check_suite_focus=true

### Expected behavior

Successful build and execute the test program.

### Actual behavior

Does not compile, aborts with error messages.

### Repro steps

Create a project with the files above and push it to github.

**Comment by mikhailkoliada** [comment]
Hi @ingo-h! on macOS `clang` does not automatically symlink to `clang++`, so you literally must specify `clang++` as your `CXX` compiler, the following snippet will work:

```
- name: Configure
    run: cmake -S . -B build -D CMAKE_C_COMPILER=$(brew --prefix llvm)/bin/clang -D CMAKE_CXX_COMPILER=$(brew --prefix llvm)/bin/clang++
```

I am going to close this ticket, feel free to reach us out if you have questions left.

**Comment by ingo-h** [comment]
Hi @mikhailkoliada,
thank you for the fix :-) It is working now. But the issue isn't really finished. I followed the documentation as given at https://github.com/actions/virtual-environments/blob/macOS-11/20220322.1/images/macos/macos-11-Readme.md.

You should improve the documentation there that is given as:
`Clang/LLVM 13.0.1 is available on '$(brew --prefix llvm)/bin/clang'`
