### ISSUE TITLE
Add jsonnet tool

### ISSUE THREAD

**Issue by eguo** [actions/virtual-environments#5294]
### Tool name

jsonnet

### Tool license

Apache License

### Add or update?

- [X] Add
- [ ] Update

### Desired version

0.18.0

### Approximate size

992KB

### Brief description of tool

A data templating language for app and tool developers

- Generate config data
- Side-effect free
- Organize, simplify, unify
- Manage sprawling config

A simple extension of [JSON](https://json.org/)

- Open source (Apache 2.0)
- Familiar syntax
- Reformatter, linter
- Editor & IDE integrations
- Formally specified

### URL for tool's homepage

https://jsonnet.org/

### Provide a basic test case to validate the tool's functionality.

```bash
jsonnet -v
```

### Virtual environments affected

- [ ] Ubuntu 18.04
- [X] Ubuntu 20.04
- [ ] macOS 10.15
- [X] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Can this tool be installed during the build?

```bash
apt update
apt install jsonnet
```

### Tool installation time in runtime

a copule seconds

### Are you willing to submit a PR?

Yes.

**Comment by mikhailkoliada** [comment]
@eguo Hello! Thank you for the submission!

We will decide on adding the tool to the images and get back to you.

**Comment by miketimofeev** [comment]
Hi @eguo!
Thank you for the feature request. Considering pretty quick installation, we wouldn't like to bake this tool into images due to maintenance concerns. Please install the tool in runtime as it doesn't take more than 15 seconds.
- Ubuntu:
```bash
sudo apt-get update
sudo apt-get install jsonnet
```
- macOS
```bash
brew install jsonnet
```
