### ISSUE TITLE
Azure pipeline for a window docker container will not run on windows server 2022

### ISSUE THREAD

**Issue by mhartman464** [actions/virtual-environments#5296]
### Description

We are using microsoft devOps and use azure pipelines (.yml files) for deploying our applications out in azure.  Some of these applications run in an instance of a docker container.  Both windows and in linux.   Recently, I fixed a defect in one of our container apps that ran in a docker windows container.  The pipeline script file (.yml) did not change.  The docker file script to build the image also di not change.  Nor did the app fail to build.    

However, in dev ops, it started to fail the deployment during the step we named
"build image".  The build image step simply does the following task in the pipeline.yml file to build the docker image:

**- task: Docker@2
      displayName: Build image
      inputs:
        containerRegistry: '$(containerRegistry)'
        repository: '$(imageName)'
        command: 'build'
        Dockerfile: 'ControllerExtraction/Dockerfile'
        tags: '$(Tag)'
        arguments: '--build-arg NugetSource=$(NugetSource)'
        addPipelineData: false 
      env:
        DOCKER_BUILDKIT: 0**

As I mentioned, the docker file script also did not change.   Our docker file script since it is for a window image begins with the following:

**FROM mcr.microsoft.com/dotnet/framework/runtime:4.8-windowsservercore-ltsc2016 AS base
WORKDIR /app
FROM mcr.microsoft.com/dotnet/framework/sdk:4.8 AS build**

Later in our docker file script we explicitly clean up some directory folders with the following powershell command lines that are now throwing an error:

**#Clear out the bin and obj directories if they exist
RUN $ErrorActionPreference = 'SilentlyContinue'; Remove-Item -Path C:\src\Microservices\ControllerExtraction\bin -Force -Recurse; exit 0
RUN $ErrorActionPreference = 'SilentlyContinue'; Remove-Item -Path C:\src\Microservices\ControllerExtraction\\obj -Force -Recurse; exit 0**

In our pipeline run, we receive the following message:   

**'$ErrorActionPreference' is not recognized as an internal or external command,**

So it seems it does not recognize "$ErrorActionPreference" as a powershell variable.   It is acting as if it was running in the command console instead in powershell.
   
The simple work around to make the deployment successful again is to change the "vmImage" in the pipeline yml file from "windows-latest" to "windows-2019."   However, we like it to work using "windows-latest."  Please make the appropriate fix.  Thank you.

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

 It is failing on version: 2.201.0.   The url for one of the failed jobs is the following:  

https://myagdataidm.visualstudio.com/IdmMyAgData/_build/results?buildId=11606&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9

I beleive we may have it private since we are a private software development company.

![image](https://user-images.githubusercontent.com/102550547/160477574-9bec2847-94df-4caf-b028-b622be7a30e8.png)

### Expected behavior

Running the pipeline yml script file should complete as successful as it did in the past when azure devOps was on windows-2019 server.

### Actual behavior

Please see description above.  Seems to be running the docker script file in the command console than in powershell.

### Repro steps

Please see description above.  But in summary do the following steps:

1) Create a docker file for a windows container.  Linux seems to be no issue.
2)  Add a powershell variable in your docker script file.  Please see above in description as an example.  
3) Set the vmImage attribute under pool in your yml pipeline azure file to "windows-latest." 
4) Run the azure pipeline job in dev ops that is running on windows 2022 server.

**Comment by mhartman464** [comment]
Mikhail,

As I stated in issue, both the pipeline file and the docker file has not changed.   The  yml file task ran fine in the past without issue.    It will only run now when I change the "vmImage" under the pool from "windows-latest" to ''windows-2019."    In summary, the only thing that changed was the server from 2019 to 2022 in azure dev ops.

The docker file will run without issue on windows 10 or windows server 2019.  Again, the issue is when it runs on windows server 2022 only.

Attached, is a simple version of a docker file that will cause the same error on line 12 when you run it on windows server 2022.



Michael L Hartman

Sr. Web Developer

614-325-0321



***@***.***<https://twitter.com/MyAgData>  ***@***.*** <https://www.facebook.com/MyAgData>   ***@***.*** <https://www.linkedin.com/company/independentdatamanagementllc/>


________________________________

**Comment by maykonrds** [comment]
I have a similar issue. I am using Azure DevOps and on my docker file, I have the PowerShell command new-item.
When I use the Windows Server 2022 I got this error:
'New-item' is not recognized as an internal or external command.
If I change the image to windows-2019 the Pipeline works fine.

**Comment by ghelyar** [comment]
As a work around, you can set the shell of the docker image at the top of the docker build stage:
```
SHELL ["powershell", "-Command"]
```

**Comment by zoran-bjelica** [comment]
After doing some research, I have also found that shell commands need to be assigned for RUN commands when running build commands.

Here are results of two initial tests where I ran first without PowerShell addition to RUN commands, and second test was with addition of PowerShell addition:
![initial_test](https://user-images.githubusercontent.com/100371150/161502623-6e40b00d-999c-4e42-b0b4-55582defd1ba.png)

Run commands work fine in following format:
RUN **powershell -command** $ErrorActionPreference = 'SilentlyContinue'; Remove-Item -Path C:\src\Microservices\ControllerExtraction\bin -Force -Recurse; exit 0
RUN **powershell -command** $ErrorActionPreference = 'SilentlyContinue'; Remove-Item -Path C:\src\Microservices\ControllerExtraction\obj -Force -Recurse; exit 0

I also ran a secondary test via image build job, and everything worked fine when using above commands:
![image_build_test](https://user-images.githubusercontent.com/100371150/161503033-40abcd21-5e1d-4e42-98b5-8f568a532ce8.png)
