### ISSUE TITLE
Support for macOS Catalina 10.15?

### ISSUE THREAD

**Issue by cclauss** [actions/virtual-environments#53]
https://www.apple.com/macos/catalina/

In GitHub Actions, `runs-on: macOS-10.14` works as expected but `runs-on: macOS-10.15` does not.

https://github.community/t5/GitHub-Actions/Support-for-macOS-Catalina-10-15/m-p/35457#M2229

**Comment by oldskool** [comment]
That would make sense since 10.15 is not [officially supported](https://help.github.com/en/github/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions#jobsjob_idruns-on) (yet). Just 10.14 is available for now.

**Comment by kaylangan** [comment]
We currently only offer macOS 10.14. We plan to replace macOS 10.14 with 10.15 before 11/13.

**Comment by LeoNatan** [comment]
Hi @kaylangan 🙂
Small world, isn't it?

**Comment by sfynx** [comment]
Why don't we keep all macOS versions that are still supported by Apple (commonly the last three), so you are able to test workloads against multiple OS versions that are in the wild?

**Comment by kaylangan** [comment]
@sfynx we've considered this, but at this point in time don't have enough VM capacity to support multiple versions of macOS.

**Comment by hugovk** [comment]
Are 10.14 image being removed and replaced with 10.15 right now?

[This build](https://github.com/python-pillow/Pillow/pull/4195/checks?check_run_id=288243449) uses explicit `macOS-10.14`, and 5 jobs passed, but 4 jobs just say "This check failed" with no further info:

![image](https://user-images.githubusercontent.com/1324225/68319471-0f18d900-00c7-11ea-9778-ee69d1e49003.png)

One says "This check was neutral" with no further info:

![image](https://user-images.githubusercontent.com/1324225/68319557-2c4da780-00c7-11ea-80db-75ccf6e60b93.png)

Replacing with `macOS-latest` lets them [all pass](https://github.com/python-pillow/Pillow/commit/0c46177804a62e5d146e27077d64ecb77e8e1836/checks?check_suite_id=298770896) but I've no idea which macOS version is actually being used. Are some using removed 10.14 and others a new 10.15? 

![image](https://user-images.githubusercontent.com/1324225/68319770-80f12280-00c7-11ea-8cd5-b6a6eb4756d3.png)

Please could you could output the OS version along with other pertinent tools and version numbers at the start of each run?

This can really help debug problems when things are upgraded in the image. For example, Travis CI begins builds with "Build system information":

![image](https://user-images.githubusercontent.com/1324225/68320106-0aa0f000-00c8-11ea-834d-d02d84af3734.png)

Thank you!

**Comment by cclauss** [comment]
Yes!! 
Display platform information
              version() = Darwin Kernel Version 19.0.0: Thu Oct 17 16:17:15 PDT 2019; root:xnu-6153.41.3~29/RELEASE_X86_64
Run import inspect
         architecture() = ('64bit', '')
              mac_ver() = ('10.15.1', ('', '', ''), 'x86_64')

**Comment by hugovk** [comment]
And it's official: https://github.blog/changelog/2019-11-06-github-actions-macos-virtual-environment-updated-to-catalina
