### ISSUE TITLE
WDK

### ISSUE THREAD

**Issue by davidgurnsey** [actions/virtual-environments#5300]
### Description

On Windows Server 2019 we had access to WDK. It appears to not be present in Windows Server 2022.

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

20220316.1

### Repro steps

A CMake project that uses this:
https://github.com/SergiusTheBest/FindWDK/blob/master/cmake/FindWdk.cmake

**Comment by al-cheb** [comment]
Duplicate: https://github.com/actions/virtual-environments/issues/5235
