### ISSUE TITLE
NodeJs or NodeJs-LTS

### ISSUE THREAD

**Issue by freyrfinnboga** [actions/virtual-environments#5304]
### Description

Script Install-NodeLts.ps1 installs NodeJs in latest version (17.8.0) with chocolatey causes Pestertest to fail.
Chocolatey has the option of installing only LTS packages with choco install nodejs-lts

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [X] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

[Buildlog.txt](https://github.com/actions/virtual-environments/files/8379153/Buildlog.txt)

### Expected behavior

I expect that Install-NodeLts.ps1 installs only the LTS versions of nodejs packages available in chocolatey package repository
So I would think that Install-NodeLts.ps1 should contain
Choco-Install -PackageName nodejs-lts -ArgumentList "--version=$versionToInstall"

Like described here https://community.chocolatey.org/packages/nodejs-lts#versionhistory 

### Actual behavior

This line
$defaultVersion = (Get-ToolsetContent).node.default
in Install-NodeLts.ps1 for some reason results in an empty string resulting in the following lines
$versionToInstall = Get-LatestChocoPackageVersion -TargetVersion $defaultVersion -PackageName "nodejs"
Choco-Install -PackageName nodejs -ArgumentList "--version=$versionToInstall"

to be
choco install nodejs -y --version=
which resulted in
nodejs.install v17.8.0 [Approved]
But Pester test then fails

### Repro steps

Cloned repo
Run build with packer
packer build    -var "capture_name_prefix=$ResourcesNamePrefix" `
                -var "client_id=$ClientId" `
                -var "client_secret=$ClientSecret" `
                -var "install_password=$InstallPassword" `
                -var "github_feed_token=$GitHubFeedToken" `
                -var "location=$Location" `
                -var "resource_group=$ResourceGroup" `
                -var "storage_account=$StorageAccount" `
                -var "subscription_id=$SubscriptionId" `
                -var "temp_resource_group_name=$TempResourceGroupName" `
                -var "tenant_id=$TenantId" `
                $TemplatePath `

**Comment by al-cheb** [comment]
Hello @freyrfinnboga ,
We don't preinstall Node 17  on Windows Server 2019/2022,  the default version is Node 16 LTS, please check toolset - https://github.com/actions/virtual-environments/blob/main/images/win/toolsets/toolset-2019.json, https://github.com/actions/virtual-environments/blob/main/images/win/toolsets/toolset-2022.json

**Comment by miketimofeev** [comment]
@freyrfinnboga given the fact that the version is hardcoded there is no need to change the package name.
I'm going to close the issue. Please feel free to contact us if you have any concerns.
Thank you!

**Comment by freyrfinnboga** [comment]
Hella @al-cheb 
Yes I understand and I saw the toolset-...json files had three major versions. But in this run that I had the resulting parameter from
$defaultVersion = (Get-ToolsetContent).node.default was empty and therefore the chocolatey installed latest versions.
Why and how the paramter was empty is unknown to me since previous runs on my end resulted in correct version
