### ISSUE TITLE
Update Xcode to 13.3

### ISSUE THREAD

**Issue by darecki** [actions/virtual-environments#5317]
### Tool name

Xcode

### Tool license

idk

### Add or update?

- [ ] Add
- [X] Update

### Desired version

13.3

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [X] macOS 10.15
- [X] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [ ] Windows Server 2022

**Comment by luxiaohuaniyaoqunaili** [comment]
Please check the network. Our test download can only run to 5m and upload
is only 1m

Darek Cieśla ***@***.***> 于2022年3月31日周四 14:41写道：

**Comment by miketimofeev** [comment]
Hi @darecki!
Xcode 13.3 is available only on macOS-12, which is in private preview for now. If you'd like to have access please submit [the form](https://forms.gle/D1ihWjw3xDfjYbu67).
I'm going to close the issue. Thank you!
