### ISSUE TITLE
##[error]Could not find the modules: 'Az.Accounts' with Version: '5.5.0'. If the module was recently installed, retry after restarting the Azure Pipelines task agent

### ISSUE THREAD

**Issue by rdoetjes** [actions/virtual-environments#5319]
### Description

After the Build Agents for vmImage: windows-latest, were moved to Windows 2022, we get the following error on every task that uses Az.Accounts

##[error]Could not find the modules: 'Az.Accounts' with Version: '5.5.0'. If the module was recently installed, retry after restarting the Azure Pipelines task agent

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

We are not allowed to share this data publically, as we are a European Financial institution.

### Is it regression?

no it' s a new issue

### Expected behavior

Az.Accounts 5.5.0 will be loaded without errors

### Actual behavior

Build Agent throws an error
##[error]Could not find the modules: 'Az.Accounts' with Version: '5.5.0'. If the module was recently installed, retry after restarting the Azure Pipelines task agent

### Repro steps

Create a task that uses 5.5.0 for Az.Accounts and run it.

**Comment by al-cheb** [comment]
Hello @rdoetjes,
We don't preinstall Az.Account=5.5.0 on Windows Server 2022, you can check the doc file - https://github.com/actions/virtual-environments/blob/main/images/win/Windows2022-Readme.md#powershell-tools

**Comment by al-cheb** [comment]
@rdoetjes, Any updates?

**Comment by rdoetjes** [comment]
Hi Alexander,

We have not yet reached the people who create our resource templates, to check what they are using.
Big corporations make these sorts of things always hard :)

**Comment by al-cheb** [comment]
Feel free to open the issue if you get a chance to collect more info how to reproduce it.
