### ISSUE TITLE
Add Scoop

### ISSUE THREAD

**Issue by Tyler887** [actions/virtual-environments#5333]
### Tool name

Scoop

### Tool license

Unlicense

### Add or update?

- [X] Add
- [ ] Update

### Desired version

0.1.0 (latest, but it's recommended that new versions are deployed. The GitHub hosted runner is cleaned after a job is done.)

### Approximate size

382kB

### Brief description of tool

A command-line installer for Windows.

### URL for tool's homepage

https://scoop.sh

### Provide a basic test case to validate the tool's functionality.

```bash
pwsh -c "Invoke-Expression (New-Object System.Net.WebClient).DownloadString('https://get.scoop.sh')"
```

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [X] Windows Server 2019
- [X] Windows Server 2022

### Can this tool be installed during the build?

```bash
pwsh -c "Invoke-Expression (New-Object System.Net.WebClient).DownloadString('https://get.scoop.sh')"
```

### Tool installation time in runtime

About 5 seconds.

### Are you willing to submit a PR?

Yes! ;)

**Comment by al-cheb** [comment]
Hello @Tyler887,
Thank you for the feature request. Considering pretty quick installation, we wouldn't like to bake this tool into images due to maintenance concerns. Please install the tool in runtime as it doesn't take more than 15 seconds.
