### ISSUE TITLE
composer self-update requires sudo

### ISSUE THREAD

**Issue by hugovk** [actions/virtual-environments#534]
**Describe the bug**
A clear and concise description of what the bug is, and why you consider it to be a bug.

Permission denied for `composer self-update` with the newly-released Composer 1.10.

**Area for Triage**: 

Scripting and command line

**Question, Bug, or Feature?**: 

Bug

**Virtual environments affected**
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [x] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Expected behavior**
A description of what you expected to happen.

I expect Composer to be updated, like it does on my macOS machine:

```
Updating to version 1.10.0 (stable channel).
   Downloading (100%)
Use composer self-update --rollback to return to version 1.9.3
```

**Actual behavior**
A description with steps to reproduce the issue. If your have a public example or repo to share,
please provide the link.

1. Run `composer self-update`

```
Updating to version 1.10.0 (stable channel).
   Downloading (connecting...)Downloading (100%)         

                                                                                                
  [ErrorException]                                                                              
  rename(/home/runner/.composer/cache/composer-temp.phar,/usr/bin/composer): Permission denied  
                                                                                                

self-update [-r|--rollback] [--clean-backups] [--no-progress] [--update-keys] [--stable] [--preview] [--snapshot] [--set-channel-only] [--] [<version>]

##[error]Process completed with exit code 1.
```

https://github.com/hugovk/test/runs/498138460?check_suite_focus=true

Here's a minimal workflow file:

```yml
name: Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false

    steps:
      - name: Composer update
        run: |
          composer self-update
```

This was reported to Composer https://github.com/composer/composer/issues/8678, but they say:

> well, the actions runner is probably not allowed to write in `/usr/bin`. That's not something that composer can solve.

> Yup, sounds like you'll need to sudo or similar, I am not familiar enough with GH Actions to help with a fix..

It works with `sudo composer self-update`: 
https://github.com/hugovk/test/runs/498268510?check_suite_focus=true

Should we use `sudo` here? Or is there some other fix to be made at GHA?

**Comment by al-cheb** [comment]
Hello, @hugovk 

User can't write to system folder(`/usr/bin/`), to elevate permissions you should use `sudo` :
`rename(/home/runner/.composer/cache/composer-temp.phar,/usr/bin/composer): Permission denied `

**Comment by al-cheb** [comment]
@hugovk, https://getcomposer.org/doc/00-intro.md#installation-linux-unix-osx
If you like to install it only for your user and avoid requiring root permissions, you can use ~/.local/bin instead which is available by default on some Linux distributions.
**Note: If the above fails due to permissions, you may need to run it again with sudo.**

Feel free to reopen the thread if you have any concerns.

**Comment by hugovk** [comment]
We used `sudo`, thanks for the clarification!
