### ISSUE TITLE
Add Microsoft Reporting Services Projects support

### ISSUE THREAD

**Issue by arnoj** [actions/virtual-environments#5340]
### Tool name

Microsoft Reporting Services Projects

### Tool license

Microsoft

### Add or update?

- [X] Add
- [ ] Update

### Desired version

2022

### Brief description of tool

Extension for Microsoft Reporting Services Projects support. 

"The Microsoft RDL report designer, projects and wizards for creating professional reports. This package provides support for the .rptproj type and is designed for the most recent versions of Microsoft Reporting Services."

This is [included](https://github.com/actions/virtual-environments/blob/1ede8085f53bf7b38163389282bed3b8173b4d62/images/win/toolsets/toolset-2019.json#L381) in the 2019 image.

### URL for tool's homepage

https://marketplace.visualstudio.com/items?itemName=ProBITools.MicrosoftReportProjectsforVisualStudio2022

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [X] Windows Server 2022

**Comment by al-cheb** [comment]
Hello @arnoj ,
We will take a look at it.

**Comment by arnoj** [comment]
I don't have time to create a PR, but found some info which might be helpful. As found by @pavelpikatamcs `Get-VsixExtenstionFromMarketplace` probably needs to change to get the (marketplace external) VSIX download URL.

The data currently used to determine the variables (JSON in the page) looks to come from the (not public) API endpoint `extensionquery` (unofficial info [here](https://old.reddit.com/r/vscode/comments/am1k1t/is_there_an_api_for_getting_list_of_all/efj1zp9/)) which has all the needed info.

[This comment](https://gist.github.com/wanglf/7acc591890dc0d8ceff1e7ec9af32a55?permalink_comment_id=4151555#gistcomment-4151555) is helpful to determine the download URL which is (currently) structured as:

`https://marketplace.visualstudio.com/_apis/public/gallery/publishers/${publisherName}/vsextensions/${extensionName}/${version}/vspackage`

So for this extension that is:
https://marketplace.visualstudio.com/_apis/public/gallery/publishers/ProBITools/vsextensions/MicrosoftReportProjectsforVisualStudio2022/3.0.1/vspackage

**Comment by arnoj** [comment]
@al-cheb,

It looks like this gets installed by using that download URI and passing it to the `VSIXInstaller` from Visual Studio which probably adds a unique identifier.

These type of URLs were used before too: cd4ecad2e636fbea5182332679e04d793fbf642c. Where it gets passed: [here](https://github.com/actions/virtual-environments/blob/df8580f2f095420873177e17932da1de0799f827/images/win/scripts/ImageHelpers/InstallHelpers.ps1#L286).

**Comment by bryandam** [comment]
@arnoj Is the PR just adding 'ProBITools.MicrosoftReportProjectsforVisualStudio2022' ([Marketplace](https://marketplace.visualstudio.com/items?itemName=ProBITools.MicrosoftReportProjectsforVisualStudio2022)) to the 2022's VSIX toolset ([here](https://github.com/actions/virtual-environments/blob/1ede8085f53bf7b38163389282bed3b8173b4d62/images/win/toolsets/toolset-2022.json#L258))?

We updated to .NET 6 and now we're in a pickle.  The 2019 VM won't build .NET 6 projects but the 2022 VM won't build report projects.

**Comment by AlexanderGitin** [comment]
Hello @arnoj, we deployed a new image with the addition of MicrosoftReportProjectsforVisualStudio2022. I'm going to close the issue. Feel free to contact us if you have any concerns. Thank you!

**Comment by bryandam** [comment]
Thanks @AlexanderGitin.

Has anyone got this working?  It now complains about .NET 4.0 being missing which makes sense because I believe VS 2022 no longer supports it.  However, you don't specify a framework version in the report project.  I tried just now anyways without luck.  Every reporting project throws this:
`##[error]C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(1221,5): Error MSB3644: The reference assemblies for .NETFramework,Version=v4.0 were not found. To resolve this, install the Developer Pack (SDK/Targeting Pack) for this framework version or retarget your application. You can download .NET Framework Developer Packs at https://aka.ms/msbuild/developerpacks`

I realize this wouldn't be a AzureDO Pipeline VM issue so I'd need to make an issue some other place but just wanted to see if anyone following this issue can confirm/deny that they are successful before I do.

**Comment by arnoj** [comment]
Hi @bryandam, just checking this a bit late (on vacation), but I found the answer on the extensions [Q&A page](https://marketplace.visualstudio.com/items?itemName=ProBITools.MicrosoftReportProjectsforVisualStudio2022&ssr=false#qna) (first comment on 3/1). It works if you add `<TargetFrameworkVersion>v4.8</TargetFrameworkVersion>` to the `rptproj` project file since that developer pack is [installed](https://github.com/actions/virtual-environments/blob/main/images/win/Windows2022-Readme.md#net-framework) in the 2022 environment.

**Comment by Da13Harris** [comment]
@arnoj Manually adding the `TargetFrameworkVersion` works, but unfortunately it gets removed from the `rptproj` file every time a new report is added to the project. 😢

**Comment by batetech** [comment]
> @arnoj Manually adding the `TargetFrameworkVersion` works, but unfortunately it gets removed from the `rptproj` file every time a new report is added to the project. 😢

If you are building via msbuild from the command line, you can add `-p:TargetFrameworkVersion=4.8` build arg for the `rptproj` builds and it should succeed without the "Error MSB3644: The reference assemblies for .NETFramework,Version=v4.0 were not found"
