### ISSUE TITLE
[META] Please try to update the virtual environments at the same time

### ISSUE THREAD

**Issue by danielhjacobs** [actions/virtual-environments#5341]
### Description

When the browser version in one virtual environment is updated but the browser version in another virtual environment is not, it means that there can be software that relies on a specific version that, whether updated or not, causes at least one workflow to fail. For example, because https://github.com/actions/virtual-environments/pull/5314 is merged but https://github.com/actions/virtual-environments/pull/5325 is not merged, the Ubuntu Node.js workflow is failing on https://github.com/ruffle-rs/ruffle/pull/6553 because chromedriver is still using version 98. However, if chromedriver were updated to version 100 (as in this dependabot PR: https://github.com/ruffle-rs/ruffle/pull/6586), the Windows Node.js workflow would fail since that virtual environment doesn't have Chrome 100.

### Virtual environments affected

- [X] Ubuntu 18.04
- [X] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [X] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

https://github.com/ruffle-rs/ruffle/runs/5818686649?check_suite_focus=true
https://github.com/ruffle-rs/ruffle/runs/5823590998?check_suite_focus=true

### Repro steps

Try to set up a Github actions workflow that relies on https://github.com/giggio/node-chromedriver and see that it fails on Ubuntu when using version 98 and fails on Windows when using version 100.

**Comment by al-cheb** [comment]
Hello @danielhjacobs,
It's impossible to use the same software at the same time on all images. Nothing we can do from our side.

**Comment by danielhjacobs** [comment]
> It's impossible to use the same software at the same time on all images. 

 That's not what I'm requesting. All I'm asking is that if multiple pull requests are opened at the same time can you please try to merge them at the same time?

**Comment by miketimofeev** [comment]
@danielhjacobs the pool request is opened automatically once the update is started and merged also automatically once the deployment is completed. Unfortunately, sometimes we face unpredictable issues during a rollout and it takes more time than usual to update all the environments for a particular OS.
