### ISSUE TITLE
Update Curl to 7.71

### ISSUE THREAD

**Issue by rtroch** [actions/virtual-environments#5342]
### Tool name

curl

### Tool license

Free open source software

### Add or update?

- [ ] Add
- [X] Update

### Desired version

7.71

### Approximate size

250kB

### Virtual environments affected

- [X] Ubuntu 18.04
- [X] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

Version 7.71 added a really useful option which is `--retry-all-errors`. Would be great to have it available out of the box in github actions 🙂

**Comment by miketimofeev** [comment]
@rtroch Hi!
I'm afraid we have to wait until the upstream repository is updated, the current one is 7.68 for Ubuntu 20 https://packages.ubuntu.com/focal/curl and 7.58 for Ubuntu 18 https://packages.ubuntu.com/bionic/curl
I'm going to close the issue as nothing we can do from our side.
Thank you!
