### ISSUE TITLE
Update Az Module to 7.3.0 version of PowerShell

### ISSUE THREAD

**Issue by Khalifah** [actions/virtual-environments#5345]
### Tool name

PowerShell Tools - PowerShell 7.2.1

### Tool license

Apache License Version 2.0

### Add or update?

- [ ] Add
- [X] Update

### Desired version

PowerShell 7.3.0

### Brief description of tool

There was a fix for Azure Data factory released by Microsoft in the PowerShell 7.3.0 version - released a month ago.  

### URL for tool's homepage

https://www.powershellgallery.com/packages/Az/7.3.0

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [X] Windows Server 2019
- [X] Windows Server 2022

**Comment by al-cheb** [comment]
@Khalifah , Please update the title of the issue. Do you mean update Az module to 7.3 version or PowerShell?

**Comment by Khalifah** [comment]
Yes please @al-cheb - now updated.

**Comment by Khalifah** [comment]
Hi @al-cheb , thanks once again for your help on this request. I just noticed the Powershell Version was updated to **7.2.2 from 7.2.1** - albeit my request was for upgrade to 7.3.0. Could you kindly check and advise?

**Comment by al-cheb** [comment]
> Hi @al-cheb , thanks once again for your help on this request. I just noticed the Powershell Version was updated to **7.2.2 from 7.2.1** - albeit my request was for upgrade to 7.3.0. Could you kindly check and advise?

Currently PowerShell 7.3.0 is in [v7.3.0-preview.3](https://github.com/PowerShell/PowerShell/releases/tag/v7.3.0-preview.3), we install only latest release.

**Comment by Khalifah** [comment]
Alright can you

> > Hi @al-cheb , thanks once again for your help on this request. I just noticed the Powershell Version was updated to **7.2.2 from 7.2.1** - albeit my request was for upgrade to 7.3.0. Could you kindly check and advise?
> 
> Currently PowerShell 7.3.0 is in [v7.3.0-preview.3](https://github.com/PowerShell/PowerShell/releases/tag/v7.3.0-preview.3), we install only latest release.

alright can you please confirm the latest release installed? is it 7.2.2 or 7.3.2 that you requested? I don't even see the 7.2.2 in the PS Gallery https://www.powershellgallery.com/packages/Az/7.3.0 - Please see version history.

**Comment by al-cheb** [comment]
> Alright can you
> 
> > > Hi @al-cheb , thanks once again for your help on this request. I just noticed the Powershell Version was updated to **7.2.2 from 7.2.1** - albeit my request was for upgrade to 7.3.0. Could you kindly check and advise?
> > 
> > 
> > Currently PowerShell 7.3.0 is in [v7.3.0-preview.3](https://github.com/PowerShell/PowerShell/releases/tag/v7.3.0-preview.3), we install only latest release.
> 
> alright can you please confirm the latest release installed? is it 7.2.2 or 7.3.2 that you requested? I don't even see the 7.2.2 in the PS Gallery https://www.powershellgallery.com/packages/Az/7.3.0 - Please see version history.

Don't mix PowerShell and Az module for PowerShell. PowerShell latest release is 7.2.2. Az module - https://www.powershellgallery.com/packages/Az/7.3.2

**Comment by al-cheb** [comment]
We are planning to start new image rollout with Az 7.3.2 version next week. It will take about one week.

**Comment by Khalifah** [comment]
> We are planning to start new image rollout with Az 7.3.2 version next week. It will take about one week.

Great! Thank you @al-cheb

**Comment by al-cheb** [comment]
Windows Server images have been deployed with Az 7.3.2 on board.

**Comment by JustinGrote** [comment]
@al-cheb  curious, why are they not in the ubuntu image? Microsoft Graph is but not Az (which is far more popular going by PowerShell Gallery downloads)?

**Comment by al-cheb** [comment]
> @al-cheb curious, why are they not in the ubuntu image? Microsoft Graph is but not Az (which is far more popular going by PowerShell Gallery downloads)?

@JustinGrote, We don't add Az module to PsModulePath by default but this module still exists on Ubuntu Server images - https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2204-Readme.md#az-powershell-modules

**Az PowerShell Modules**

- 7.3.2

![image](https://user-images.githubusercontent.com/47745270/172313243-3077df98-2917-49c4-a2bb-378582a93bef.png)

**Comment by JustinGrote** [comment]
My issue was actually https://github.com/Azure/login/issues/231
