### ISSUE TITLE
momo

### ISSUE THREAD

**Issue by laounimomo12** [actions/virtual-environments#5352]
### Breaking changes

@ @sergey-akhalkov    d 

### Target date

12/12/2024

### The motivation for the changes

@gokaygurcan d 

### Possible impact

@ @d

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [X] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Mitigation ways

@ @timheuer

**Comment by laounimomo12** [comment]
e

**Comment by gokaygurcan** [comment]
🤔
