### ISSUE TITLE
cmake 3.23 in 20220330.0 breaks package finding

### ISSUE THREAD

**Issue by ned14** [actions/virtual-environments#5353]
### Description

Working: https://github.com/ned14/outcome/runs/5808486360?check_suite_focus=true

Not working: https://github.com/ned14/outcome/runs/5841557904?check_suite_focus=true

Symptom:

```
CMake Error at build-gcc7-cxx14/quickcpplib/repo/cmakelib/QuickCppLibUtils.cmake:394 (find_package):
  Could not find a package configuration file provided by "quickcpplib" with

    quickcpplibConfig.cmake
    quickcpplib-config.cmake

  Add the installation prefix of "quickcpplib" to CMAKE_PREFIX_PATH or set
  "quickcpplib_DIR" to a directory containing one of the above files.  If
  "quickcpplib" provides a separate development package or SDK, be sure it
  has been installed.
```

Suspected cause: upgrade from cmake 3.22.2 to 3.23

(Tip for future: never upgrade to the first release of cmake, always wait for a bugfix point release)

### Virtual environments affected

- [ ] Ubuntu 18.04
- [X] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

20220330.0 https://github.com/actions/virtual-environments/releases/tag/ubuntu20%2F20220330.0

### Is it regression?

20220227.1

### Expected behavior

cmake finds packages

### Actual behavior

cmake is not finding packages

### Repro steps

Run repo above in newer image

**Comment by al-cheb** [comment]
Hello @ned14,
We will take a look at it. Could you please create a ticket in the repo https://gitlab.kitware.com/cmake/cmake/-/issues?scope=all&state=opened about that issue?

**Comment by miketimofeev** [comment]
@ned14 could you try downgrading cmake in runtime in meantime. Does it help? Feel free to ask for any help with downgrading.

**Comment by ned14** [comment]
> Could you please create a ticket in the repo https://gitlab.kitware.com/cmake/cmake/-/issues?scope=all&state=opened about that issue?

They'd want a repro, and that would take non-work time I don't have. This is a common enough thing for new cmake releases. Anybody in the industry waits for the first bugfix release before upgrades. Me personally, I always trail the latest cmake release by a full version, and my life is very considerably easier for doing this.

> @ned14 could you try downgrading cmake in runtime in meantime. Does it help? Feel free to ask for any help with downgrading.

I'll figure it out. This is a bad time for GA to break for me, that specific breakage was a bugfix for the upcoming Boost C++ libraries release. I need to get bugs in my own libraries fixed before thinking about cmake's bugs.

**Comment by miketimofeev** [comment]
@ned14 the problem is that we can't control CMake version on macOS as the version that comes from the brew is always the latest one that's why we set on not hardcoding the CMake version for all the other OSs.

There is an action that allows you to install any CMake version in about 10 seconds please consider using it to stick to the version you need
```yml
    steps:
    - name: Setup cmake
      uses: jwlawson/actions-setup-cmake@v1.12
      with:
        cmake-version: '3.22.3'
        github-api-token: ${{ secrets.API_REQUEST_TOKEN }}
```

**Comment by ned14** [comment]
> @ned14 the problem is that we can't control CMake version on macOS as the version that comes from the brew is always the latest one that's why we set on not hardcoding the CMake version for all the other OSs.

I found the PR where you made the change to always use latest cmake release. Seems to me the shell scripting could choose the last point release of the minor version before the latest. But that's up to you, depends on how much inadvertent breaking people's GA matters.

> There is an action that allows you to install any CMake version in about 10 seconds please consider using it to stick to the version you need

Already deployed that exact solution this morning and everything is green again: https://github.com/ned14/outcome/actions

**Comment by al-cheb** [comment]
@bradking, Could you please assist?

**Comment by bradking** [comment]
> They'd want a repro, 

Yes.  There is not enough information here for me to help without spending significant time.  Please create a standalone example and report an issue.

Or, build CMake from source in a relevant environment, and use `git bisect` to find the culprit.

**Comment by al-cheb** [comment]
Feel free to reopen the thread if you have the repro.
