### ISSUE TITLE
automake autoconf libtool are pre-installed in ubuntu-18.04 and ubuntu-20.04, but not motioned in document.

### ISSUE THREAD

**Issue by leleliu008** [actions/virtual-environments#5360]
### Description

`automake` `autoconf` `libtool` are pre-installed in `ubuntu-18.04` and `ubuntu-20.04`, but not motioned in document.

In addition, `libtool` was installed version is `2.4.6`, `libtool` version in HomeBrew is up to `2.4.7`, if someone install libtool from HomeBrew, this will case problem. Beacause `aclocal` which is shipped with `automake` will search `/usr/share/aclocal`, `libtool-2.4.6 m4` will be used. `/home/linuxbrew/.linuxbrew/bin/libtoolize` which is shipped with `HomeBrew libtool` will confict with `libtool-2.4.6`

```
libtool: Version mismatch error.  This is libtool 2.4.7, but the
libtool: definition of this LT_INIT comes from libtool 2.4.6.
libtool: You should recreate aclocal.m4 with macros from libtool 2.4.7
libtool: and run autoconf again.
```

There are two ways to resolve this problem:
1. update pre-installed libtool version up to `2.4.7`, and always keep same with HomeBrew's libtool version, it seems dificult.
2. remove pre-installed automake autoconf libtool

### Virtual environments affected

- [X] Ubuntu 18.04
- [X] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

https://github.com/leleliu008/test/runs/5864284891?check_suite_focus=true

https://github.com/leleliu008/test/runs/5864284821?check_suite_focus=true

### Is it regression?

No

### Repro steps

```
brew install libtool

curl -LO https://mediaarea.net/download/source/libzen/0.4.39/libzen_0.4.39.tar.bz2
tar vxf libzen_0.4.39.tar.bz2
cd ZenLib/Project/GNU/Library
./autogen.sh
./configure
make
```

**Note:** You may ask why you install libtool from HomeBrew, Here I just given you a example that can be used to reproduce this issue. Actually, In my real instance, I need install `graphviz` from Homebrew which depend on `libtool`.

**Comment by al-cheb** [comment]
We don't mention packages that depend on another package:

https://github.visualstudio.com/virtual-environments/_build/results?buildId=124256&view=logs&j=011e1ec8-6569-5e69-4f06-baf193d1351e&t=5431112d-2b61-5a5f-7042-ef698f761043
```
Suggested packages:
    azure-arm:   binutils-doc cpp-doc gcc-9-locales debian-keyring g++-multilib
    azure-arm:   g++-9-multilib gcc-9-doc gcc-multilib manpages-dev autoconf automake libtool
    azure-arm:   flex bison gdb gcc-doc gcc-9-multilib glibc-doc bzr libstdc++-9-doc make-doc
```

1. update pre-installed libtool version up to 2.4.7, and always keep same with HomeBrew's libtool version, it seems dificult. - There is no libtool version 2.4.7+ in the official repo `azure-arm: Get:25 http://azure.archive.ubuntu.com/ubuntu focal/main amd64 libtool all 2.4.6-14 [161 kB]`
2. remove pre-installed automake autoconf libtool - We can't do it because it will break a lot of packages, you can check - ` apt-cache rdepends automake autoconf libtool`

**Comment by leleliu008** [comment]
libtool 2.4.7 is installed from HomeBrew, not from APT

**Comment by leleliu008** [comment]
https://mirror.us-midwest-1.nexcess.net/gnu/libtool/

libtool 2.4.7 is released at 17-Mar-2022.

libtool in APT repo is old version(2.4.6),  libtool in HomeBrew repo is new version(2.4.7)

libtool is pre-installed on Ubuntu, and it's version is 2.4.6. may it was installed from APT repo.

**Comment by leleliu008** [comment]
automake autoconf libtool are widely used, I think they should be documented if they are pre-installed.

**Comment by al-cheb** [comment]
> automake autoconf libtool are widely used, I think they should be documented if they are pre-installed.

I have created a https://github.com/actions/virtual-environments/pull/5362 PR to add version info about those tools.

**Comment by al-cheb** [comment]
Fixed:
Ubuntu18 - https://github.visualstudio.com/virtual-environments/_build/results?buildId=124263&view=logs&j=011e1ec8-6569-5e69-4f06-baf193d1351e&t=72559e73-928c-58e0-b67e-e22d7a78faae
Ubuntu20 - https://github.visualstudio.com/virtual-environments/_build/results?buildId=124264&view=logs&j=011e1ec8-6569-5e69-4f06-baf193d1351e&t=72559e73-928c-58e0-b67e-e22d7a78faae

![image](https://user-images.githubusercontent.com/47745270/162183462-f53c924e-1174-49c5-9f26-3ebbc9a3133b.png)

The next image rollout will include updated md doc files with versions.

**Comment by leleliu008** [comment]
Ok, Thank you. I recommend you updating `libtool` version up to `2.4.7` if possible, or users may do some extra jobs. my solution is run `sudo apt remove automake autoconf libtool`

**Comment by al-cheb** [comment]
> Ok, Thank you. I recommend you updating `libtool` version up to `2.4.7` if possible, or users may do some extra jobs. my solution is run `sudo apt remove automake autoconf libtool`

It's very dangerous and unpredictable impact for customers. Feel free to build your own image with these changes or remove in runtime.

**Comment by al-cheb** [comment]
The documentation has been updated for Ubuntu Server 18.04/20.04.
