### ISSUE TITLE
CodeQL Bundle gives errors in Windows build image

### ISSUE THREAD

**Issue by Chaouki-Tiouassiouine** [actions/virtual-environments#5361]
### Description

Hello team, as you can see down below, the script is giving errors in CodeQL bundle.

==> vhd: Provisioning with powershell script: C:\a\3\s\virtual-environments\images\win/scripts/Installers/Install-CodeQLBundle.ps1
    vhd: Downloading CodeQL bundle 0.0.0-20220322...
    vhd: Downloading package from: https://github.com/github/codeql-action/releases/download/codeql-bundle-20220322/codeql-bundle.tar.gz to path C:\Users\packer\AppData\Local\Temp\codeql-bundle.tar.gz .
    vhd: Package downloaded successfully in 40.65 seconds
    vhd: Expand archive 'C:\Users\packer\AppData\Local\Temp\codeql-bundle.tar.gz' to 'C:\Users\packer\AppData\Local\Temp' directory
==> vhd: ERROR: Unexpected end of data : codeql-bundle.tar
    vhd: There is an error during expanding 'C:\Users\packer\AppData\Local\Temp\codeql-bundle.tar.gz' to 'C:\Users\packer\AppData\Local\Temp' directory
==> vhd: Provisioning step had errors: Running the cleanup provisioner, if present...

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [X] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Version 2019

### Repro steps

Build the image and you will see that packer build will fail in codeQL

**Comment by mikhailkoliada** [comment]
@Chaouki-Tiouassiouine Hi, thanks for the report!

For the first look it looks like you downloaded inconsistent datum somehow, but we will take a look deeper.

**Comment by Chaouki-Tiouassiouine** [comment]
@mikhailkoliada I have rerun the pipeline and it is working, I guess this was a hick-up or something somewhere. I was not able to retrieve from the logs what actually caused the error. Will close this issue, thank you for looking into it!
