### ISSUE TITLE
`wasm-ld` not directly available

### ISSUE THREAD

**Issue by andrewaylett** [actions/virtual-environments#5366]
### Description

Clang calls its linker automatically during a build.  Unfortunately, due to an upstream bug the wasm linker isn't available as its standard name.

Attempting to run (as part of a build, this won't work standalone):

    clang --target=wasm32 -nostdlib -Wl,--no-entry -Wl,--export-all -o build/com.athaydes.wasm.c.Adder.wasm src/main/c/add.c

Gives the output:

    clang: error: unable to execute command: Executable "wasm-ld" doesn't exist!

Following https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=976431, the linker may be available as `wasm-ld-11` and indeed adding this run command to my Action allows the build to succeed:

    sudo ln -s $(which wasm-ld-13 || which wasm-ld-12 || which wasm-ld-11 || which wasm-ld-10) /usr/bin/wasm-ld

So I have a workaround, but the bug is still there.

### Virtual environments affected

- [ ] Ubuntu 18.04
- [X] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

https://github.com/andrewaylett/asmble/runs/5857823550?check_suite_focus=true

Runner version is `20220330.0`.

### Is it regression?

No

### Expected behavior

Clang should be able to build and link a binary targeting wasm32.

### Actual behavior

Clang is unable to link a binary targeting wasm32 because it can't find `wasm-ld`.

### Repro steps

Run this command:

    clang --target=wasm32 -nostdlib -Wl,--no-entry -Wl,--export-all -o test.wasm -x c <(echo "int foo() { return -1; }")

Or the workflow contained in this example repository: https://github.com/andrewaylett/clang-wasm-ld-example

**Comment by al-cheb** [comment]
Hello @andrewaylett,
We will take a look at it.

**Comment by al-cheb** [comment]
We don't manage lld packages, that's why we don't want to create any symlinks due to prevent any unpredictable situations for other customers. Yo should ask `LLVM Packaging Team` to fix this issue in Ubuntu repo.

```
$ dpkg -L lld-10 | grep wasm-ld
/usr/bin/wasm-ld-10
/usr/lib/llvm-10/bin/wasm-ld
$ dpkg -L lld-11 | grep wasm-ld
/usr/bin/wasm-ld-11
/usr/lib/llvm-11/bin/wasm-ld
$ dpkg -L lld-12 | grep wasm-ld
/usr/bin/wasm-ld-12
/usr/lib/llvm-12/bin/wasm-ld
```
