### ISSUE TITLE
windows-latest has installed PS 5 not 7.2

### ISSUE THREAD

**Issue by Raffaello** [actions/virtual-environments#5367]
### Description

using `windows-latest` and importing a Powershell 7.2 module i have the following error :

```
Import-Module : The version of Windows PowerShell on this computer is '5.1.20348.558'. The module 
'D:\a\1\s\PowerDir\bin\Debug\net6.0\mymodule.psd1' requires a minimum Windows PowerShell version of '7.2' 
to run. Verify that you have the minimum required version of Windows PowerShell installed, and then try again.
```

the spec on windows-latest suggest that PS 7.2 is installed:
- ref https://github.com/actions/virtual-environments/blob/main/images/win/Windows2022-Readme.md#powershell-tools

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

azure devops
```
Version: 20220330.1
```

### Expected behavior

well i was expecting PS 7.2 was the default PS in win 2022

### Actual behavior

instead PS is still ver 5

### Repro steps

well just check the powershell version, i think just this mini pipeline can do that:

```yaml
pool:
  vmImage: 'windows-latest'
  
steps:
  - powershell: |
    $host.Version | Where-Object {$_.Major -eq 7}  
```
and check the result.

**Comment by al-cheb** [comment]
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions - 
 <html>
<body>


Windows | pwsh | This is the default shell used on Windows. The PowerShell Core. GitHub appends the extension .ps1 to your script name. If your self-hosted Windows runner does not have PowerShell Core installed, then PowerShell Desktop is used instead. | pwsh -command ". '{0}'".
-- | -- | -- | --



</body>
</html>

```
- run: $PSVersionTable
- name: Set PowerShell Desktop Shell
  shell: powershell
  run: $PSVersionTable
```
![image](https://user-images.githubusercontent.com/47745270/162379898-ec7dabfe-698d-45dc-8431-a34d74d057e4.png)

**Comment by Raffaello** [comment]
@al-cheb sorry i think there is a misunderstanding. 
I wrote about the `windows-latest` in **_Azure Devops Pipelines_**, not GitHub Actions. 
What you posted is not neither a valid syntax for Azure Pipelines.

Anyway it is the same and thank you to put me on the right direction 🙂 .

```yaml
steps:
- pwsh: $PSVersionTable
- powershell: $PSVersionTable
```

so the solution of this ticket is to use `pwsh:` (Powershell Core) instead of `powershell` (Powershell Desktop).

I will suggest to highlight more in the documentation the difference between `powershell:` and `pwsh:` 
As a quick look at it, they look like just aliases of `- task: PowerShell@2`.

- ref: https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/powershell?view=azure-devops#yaml-snippet

**Comment by al-cheb** [comment]
https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/powershell?view=azure-devops#yaml-snippet

<html>
<body>


pwshUse 
PowerShell Core | (Optional) If this value is true, then on Windows the task will use pwsh.exe from your PATH instead of powershell.exeDefault value: false
-- | --



</body>
</html>
