### ISSUE TITLE
Build fails - StepProvision

### ISSUE THREAD

**Issue by lonevvolf** [actions/virtual-environments#5368]
### Description

Building win22/20220330.1 , no changes to the default scripts, gives the following error:

    vhd: Running tests from 'C:\image\Tests\Wix.Tests.ps1'
    vhd: Describing Wix
    vhd:   [+] Wix Toolset version from registry 7ms (3ms|3ms)
    vhd: Tests completed in 195.94s
    vhd: Tests Passed: 402, Failed: 0, Skipped: 17 NotRun: 0
==> vhd: Provisioning with Powershell...
==> vhd: Provisioning with powershell script: C:\Users\RYANAD~1\AppData\Local\Temp\powershell-provisioner1177737807
==> vhd: Provisioning with Powershell...
==> vhd: Provisioning with powershell script: C:\Users\RYANAD~1\AppData\Local\Temp\powershell-provisioner237760074
    vhd: Software list with blank version:
    vhd: - Composer version
    vhd:
==> vhd: Script exited with non-zero exit status: 1.Allowed exit codes are: [0]
==> vhd: Step "StepProvision" failed
==> vhd: [c] Clean up and exit, [a] abort without cleanup, or [r] retry step (build may fail even if retry succeeds)? 

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

win22/20220330.1

### Expected behavior

Should build without errors

### Actual behavior

See description

### Repro steps

Build image using specified version

**Comment by al-cheb** [comment]
You have to use only `main` branch we don't backport anything in release branches.
Nightly build was green - https://github.visualstudio.com/virtual-environments/_build/results?buildId=124288&view=logs&j=011e1ec8-6569-5e69-4f06-baf193d1351e

**Comment by lonevvolf** [comment]
@al-cheb 

Tried on the main branch, still failed:
==> vhd: Test run has failed
    vhd: Tests completed in 11.58s
==> vhd: At C:\Program Files\WindowsPowerShell\Modules\ImageHelpers\TestsHelpers.ps1:73 char:9
    vhd: Tests Passed: 31, Failed: 1, Skipped: 0 NotRun: 0
==> vhd: +         throw "Test run has failed"
    vhd:
    vhd: Containers            : {[-] C:\image\Tests\Android.Tests.ps1}
    vhd: Result                : Failed
    vhd: FailedCount           : 1
    vhd: FailedBlocksCount     : 0
    vhd: FailedContainersCount : 0
    vhd: PassedCount           : 31
    vhd: SkippedCount          : 0
    vhd: NotRunCount           : 0
    vhd: TotalCount            : 32
    vhd: Duration              : 00:00:11.5795963
    vhd: Executed              : True
    vhd: ExecutedAt            : 4/8/2022 9:56:22 AM
    vhd: Version               : 5.3.1
    vhd: PSVersion             : 5.1.20348.558
    vhd: PSBoundParameters     : {[Configuration, PesterConfiguration]}
    vhd: Plugins               :
    vhd: PluginConfiguration   :
    vhd: PluginData            :
    vhd: Configuration         : PesterConfiguration
    vhd: DiscoveryDuration     : 00:00:03.8565446
    vhd: UserDuration          : 00:00:04.8737392
    vhd: FrameworkDuration     : 00:00:02.8493125
    vhd: Failed                : {[-] Platform version platforms;android-27 is installed}
    vhd: FailedBlocks          : {}
    vhd: FailedContainers      : {}
    vhd: Passed                : {[+] Sdkmanager from SDK tools is available, [+] Sdkmanager from Command-line tools is
    vhd:                         available, [+] Platform version platforms;android-28 is installed, [+] Platform version
    vhd:                         platforms;android-29 is installed...}
    vhd: Skipped               : {}
    vhd: NotRun                : {}
    vhd: Tests                 : {[+] Sdkmanager from SDK tools is available, [+] Sdkmanager from Command-line tools is
    vhd:                         available, [-] Platform version platforms;android-27 is installed, [+] Platform version
    vhd:                         platforms;android-28 is installed...}
    vhd: CodeCoverage          :
    vhd:
==> vhd: +         ~~~~~~~~~~~~~~~~~~~~~~~~~~~
==> vhd:     + CategoryInfo          : OperationStopped: (Test run has failed:String) [], RuntimeException
==> vhd:     + FullyQualifiedErrorId : Test run has failed
==> vhd:
==> vhd: Script exited with non-zero exit status: 1.Allowed exit codes are: [0]
==> vhd: Step "StepProvision" failed

**Comment by lonevvolf** [comment]
Comparing my output to the nightly build, this seems relevant from mine:
    vhd:  Context Packages
    vhd:    [-] Platform version platforms;android-27 is installed 248ms (238ms|10ms)
    vhd:     Expected regular expression 'platforms;android-27' to match 'Loading package information...                                                   Loading local repository...                                                      [=========                              ] 25% Loading local repository...        [=========                              ] 25% Fetch remote repository...         [=======================================] 100% Fetch remote repository...        Installed packages:   Path                               | Version      | Description                     | Location                              -------                            | -------      | -------                         | -------                               build-tools;27.0.0                 | 27.0.0       | Android SDK Build-Tools 27      | build-tools\27.0.0\                   build-tools;27.0.1                 | 27.0.1       | Android SDK Build-Tools 27.0.1  | build-tools\27.0.1\                   build-tools;27.0.2                 | 27.0.2       | Android SDK Build-Tools 27.0.2  | build-tools\27.0.2\                   build-tools;27.0.3                 | 27.0.3       | Android SDK Build-Tools 27.0.3  | build-tools\27.0.3\                   build-tools;28.0.0                 | 28.0.0       | Android SDK Build-Tools 28      | build-tools\28.0.0\                   build-tools;28.0.1                 | 28.0.1       | Android SDK Build-Tools 28.0.1  | build-tools\28.0.1\                   build-tools;28.0.2                 | 28.0.2       | Android SDK Build-Tools 28.0.2  | build-tools\28.0.2\                   build-tools;28.0.3                 | 28.0.3       | Android SDK Build-Tools 28.0.3  | build-tools\28.0.3\                   build-tools;29.0.0                 | 29.0.0       | Android SDK Build-Tools 29      | build-tools\29.0.0\                   build-tools;29.0.1                 | 29.0.1       | Android SDK Build-Tools 29.0.1  | build-tools\29.0.1\                   build-tools;29.0.2                 | 29.0.2       | Android SDK Build-Tools 29.0.2  | build-tools\29.0.2\                   build-tools;29.0.3                 | 29.0.3       | Android SDK Build-Tools 29.0.3  | build-tools\29.0.3\                   build-tools;30.0.0                 | 30.0.0       | Android SDK Build-Tools 30      | build-tools\30.0.0\                   build-tools;30.0.1                 | 30.0.1       | Android SDK Build-Tools 30.0.1  | build-tools\30.0.1\                   build-tools;30.0.2                 | 30.0.2       | Android SDK Build-Tools 30.0.2  | build-tools\30.0.2\                   build-tools;30.0.3                 | 30.0.3       | Android SDK Build-Tools 30.0.3  | build-tools\30.0.3\                   build-tools;31.0.0                 | 31.0.0       | Android SDK Build-Tools 31      | build-tools\31.0.0\                   build-tools;32.0.0                 | 32.0.0       | Android SDK Build-Tools 32      | build-tools\32.0.0\                   cmake;3.18.1                       | 3.18.1       | CMake 3.18.1                    | cmake\3.18.1\                         emulator                           | 31.2.9       | Android Emulator                | emulator\                             extras;android;m2repository        | 47.0.0       | Android Support Repository      | extras\android\m2repository\          extras;google;google_play_services | 49           | Google Play services            | extras\google\google_play_services\   extras;google;m2repository         | 58           | Google Repository               | extras\google\m2repository\           ndk;21.4.7075529                   | 21.4.7075529 | NDK (Side by side) 21.4.7075529 | ndk\21.4.7075529\                     ndk;22.1.7171670                   | 22.1.7171670 | NDK (Side by side) 22.1.7171670 | ndk\22.1.7171670\                     ndk;23.1.7779620                   | 23.1.7779620 | NDK (Side by side) 23.1.7779620 | ndk\23.1.7779620\                     patcher;v4                         | 1            | SDK Patch Applier v4            | patcher\v4\                           platform-tools                     | 33.0.1       | Android SDK Platform-Tools      | platform-tools\                       platforms;android-28               | 6            | Android SDK Platform 28         | platforms\android-28\                 platforms;android-29               | 5            | Android SDK Platform 29         | platforms\android-29\                 platforms;android-30               | 3            | Android SDK Platform 30         | platforms\android-30\                 platforms;android-31               | 1            | Android SDK Platform 31         | platforms\android-31\                 platforms;android-32               | 1            | Android SDK Platform 32         | platforms\android-32\               ', but it did not match.
    vhd:     at "$installedPackages" | Should -Match "$platformVersion", C:\image\Tests\Android.Tests.ps1:75
    vhd:     at <ScriptBlock>, C:\image\Tests\Android.Tests.ps1:75

**Comment by al-cheb** [comment]
> @al-cheb Please reopen, or advise if I should open a new issue. Thanks!
We reopen this issue if we can reproduce from our side on nightly builds in next 4-5 days. Currently, I was not able to reproduce.

**Comment by lonevvolf** [comment]
Strange, as I am not doing anything non-standard, and we have always used this process to build our images.  I will try to get to the root of the issue and feedback here.

**Comment by al-cheb** [comment]
> Strange, as I am not doing anything non-standard, and we have always used this process to build our images. I will try to get to the root of the issue and feedback here.

Today we have generated at least 6 Windows images without any problem on the `main` branch.

**Comment by lonevvolf** [comment]
Found this error earlier in the logs:
    vhd: Expand archive 'C:\Program Files (x86)\Android\android-sdk\android-sdk-licenses.zip' to 'C:\Program Files (x86)\Android\android-sdk' directory
    vhd: Removing previous platform-tools installation from Visual Studio component
    vhd: [=======================================] 100% Unzipping... platform-tools/sqlit
**==> vhd: Warning: An error occurred while preparing SDK package Android SDK Platform 27: Tag mismatch!.**
    vhd: [=======================================] 100% Unzipping... android-9/framework.
    vhd: [=======================================] 100% Unzipping... android-10/framework
    vhd: [=======================================] 100% Unzipping... android-11/framework

**Comment by lonevvolf** [comment]
Found basically the same issue reported here (tag mismatch from sdkmanager):
https://stackoverflow.com/questions/24791678/android-sdk-manager-doesnt-work-download-interrupted-tag-mismatch

It looks like a timing issue on fast connections, which can explain why you're not seeing it in the pipelines.

**Comment by tonnesen-ncqa** [comment]
I am seeing this same failure as of 5/11/22. I have run this build twice and ends with this:

```
    vhd:   [+] Cabal is installed 78ms (77ms|1ms)
    vhd:   [+] cabal folder does not exist 44ms (43ms|1ms)
    vhd:   [+] CABAL_DIR environment variable exists 10ms (8ms|1ms)
    vhd:   [+] ghcup is installed 30ms (28ms|2ms)
    vhd: Tests completed in 4.49s
    vhd: Tests Passed: 8, Failed: 2, Skipped: 0 NotRun: 0
    vhd:
    vhd:
    vhd: Containers            : {[-] C:\image\Tests\Haskell.Tests.ps1}
    vhd: Result                : Failed
    vhd: FailedCount           : 2
    vhd: FailedBlocksCount     : 0
    vhd: FailedContainersCount : 0
    vhd: PassedCount           : 8
    vhd: SkippedCount          : 0
    vhd: NotRunCount           : 0
    vhd: TotalCount            : 10
    vhd: Duration              : 00:00:04.4851053
    vhd: Executed              : True
    vhd: ExecutedAt            : 5/11/2022 3:33:42 AM
    vhd: Version               : 5.3.3
    vhd: PSVersion             : 5.1.20348.643
    vhd: PSBoundParameters     : {[Configuration, PesterConfiguration]}
    vhd: Plugins               :
    vhd: PluginConfiguration   :
    vhd: PluginData            :
    vhd: Configuration         : PesterConfiguration
    vhd: DiscoveryDuration     : 00:00:00.7302669
    vhd: UserDuration          : 00:00:01.2467709
    vhd: FrameworkDuration     : 00:00:02.5080675
    vhd: Failed                : {[-] Accurate 3 versions of GHC are installed, [-] GHC 9.0.2 is the default version and should
    vhd:                         be the latest installed}
    vhd: FailedBlocks          : {}
    vhd: FailedContainers      : {}
    vhd: Passed                : {[+] GHCUP_INSTALL_BASE_PREFIX environment variable exists, [+] GHCUP_MSYS2 environment
    vhd:                         variable exists, [+] GHC 8.10.7 is installed, [+] GHC 9.0.2 is installed...}
    vhd: Skipped               : {}
    vhd: NotRun                : {}
    vhd: Tests                 : {[+] GHCUP_INSTALL_BASE_PREFIX environment variable exists, [+] GHCUP_MSYS2 environment
    vhd:                         variable exists, [-] Accurate 3 versions of GHC are installed, [+] GHC 8.10.7 is installed...}
    vhd: CodeCoverage          :
    vhd:
==> vhd: Test run has failed
==> vhd: At C:\Program Files\WindowsPowerShell\Modules\ImageHelpers\TestsHelpers.ps1:73 char:9
==> vhd: +         throw "Test run has failed"
==> vhd: +         ~~~~~~~~~~~~~~~~~~~~~~~~~~~
==> vhd:     + CategoryInfo          : OperationStopped: (Test run has failed:String) [], RuntimeException
==> vhd:     + FullyQualifiedErrorId : Test run has failed
==> vhd:
==> vhd: Script exited with non-zero exit status: 1.Allowed exit codes are: [0]
==> vhd: Step "StepProvision" failed
==> vhd: [c] Clean up and exit, [a] abort without cleanup, or [r] retry step (build may fail even if retry succeeds)?
```
