### ISSUE TITLE
Add Imagemagick to macOS agent

### ISSUE THREAD

**Issue by gianlucapisati** [actions/virtual-environments#5371]
### Tool name

Imagemagick

### Tool license

Apache 2.0

### Add or update?

- [X] Add
- [ ] Update

### Desired version

7.1.0

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [X] macOS 10.15
- [X] macOS 11
- [X] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Can this tool be installed during the build?

```bash
brew install imagemagick
```

### Tool installation time in runtime

2 minutes

**Comment by igorboskovic3** [comment]
@gianlucapisati Thanks for you suggestion. We will post update soon.

**Comment by miketimofeev** [comment]
@gianlucapisati thanks for creating the issue, we have no objections to adding the tool to the image. We will prepare a PR and deploy the new image next week.

**Comment by gianlucapisati** [comment]
Thanks a lot, also for your speed

**Comment by al-cheb** [comment]
The new images have been deployed with ImageMagick on board.
