### ISSUE TITLE
Add Windows Driver Kit

### ISSUE THREAD

**Issue by Javagedes** [actions/virtual-environments#5386]
### Tool name

Windows Driver Kit

### Tool license

N/A

### Add or update?

- [X] Add
- [ ] Update

### Desired version

latest

### Brief description of tool

The WDK has been removed from the windows-2022 vm for azure pipelines, which was present in windows-2019. I'm not sure which of the three, if not all, of the following components are necessary for WDK to be present, however the following components that were in windows-2019 are no longer present in windows-2022.

- Component.Microsoft.Windows.DriverKit
- Windows Driver Kit
- Windows Driver Kit Visual Studio Extension

 I would like to request that these be added back into windows-2022.

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Are you willing to submit a PR?

Yes

**Comment by Javagedes** [comment]
I believe the following change would install the necessary components. The change would be here: https://github.com/actions/virtual-environments/blob/06446ddb68fa8afa21cd8d2676a1757cbf6e9ce3/images/win/windows2022.json#L173

```json
"type": "powershell",
"scripts": [
    "{{ template_dir }}/scripts/Installers/Install-Wix.ps1",
    "{{ template_dir }}/scripts/Installers/Install-Vsix.ps1",
    "{{ template_dir }}/scripts/Installers/Install-AzureCli.ps1",
    "{{ template_dir }}/scripts/Installers/Install-AzureDevOpsCli.ps1",
    "{{ template_dir }}/scripts/Installers/Install-NodeLts.ps1",
    "{{ template_dir }}/scripts/Installers/Install-CommonUtils.ps1",
    "{{ template_dir }}/scripts/Installers/Install-JavaTools.ps1",
    "{{ template_dir }}/scripts/Installers/Install-Kotlin.ps1"
]
```

to 

```json
"type": "powershell",
"scripts": [
    "{{ template_dir }}/scripts/Installers/Install-Wix.ps1",
    "{{ template_dir }}/scripts/Installers/Install-WDK.ps1",
    "{{ template_dir }}/scripts/Installers/Install-Vsix.ps1",
    "{{ template_dir }}/scripts/Installers/Install-AzureCli.ps1",
    "{{ template_dir }}/scripts/Installers/Install-AzureDevOpsCli.ps1",
    "{{ template_dir }}/scripts/Installers/Install-NodeLts.ps1",
    "{{ template_dir }}/scripts/Installers/Install-CommonUtils.ps1",
    "{{ template_dir }}/scripts/Installers/Install-JavaTools.ps1",
    "{{ template_dir }}/scripts/Installers/Install-Kotlin.ps1"
]
```

**Comment by al-cheb** [comment]
Duplicate: https://github.com/actions/virtual-environments/issues/5235
