### ISSUE TITLE
Add Xcode 13.3.1 to macos-12 image

### ISSUE THREAD

**Issue by bielikb** [actions/virtual-environments#5391]
### Tool name

Xcode

### Tool license

Apple, Inc.

### Add or update?

- [X] Add
- [ ] Update

### Desired version

13.3.1 (build 13E500a)

### Brief description of tool

Xcode 13.3.1 (build 13E500a), macOS 12+.
 
https://developer.apple.com/services-account/download?path=/Developer_Tools/Xcode_13.3.1/Xcode_13.3.1.xip

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [X] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Can this tool be installed during the build?

```bash
no
```

### Are you willing to submit a PR?

no

**Comment by miketimofeev** [comment]
Hi @bielikb!
We have already added Xcode 13.3.1 to the image and will start the deployment ASAP

**Comment by salvatoreboemia** [comment]
> Hi @bielikb! We have already added Xcode 13.3.1 to the image and will start the deployment ASAP

is it possible to already use macOS12 as an available environment?

I don't see it

<img width="841" alt="Screenshot 2022-04-12 at 16 00 37" src="https://user-images.githubusercontent.com/20614870/162979663-5f2b4e56-1ba0-435a-99c3-6c97b2d8ae51.png">

**Comment by VladislavAntonyuk** [comment]
what about macos-latest?

**Comment by miketimofeev** [comment]
@VladislavAntonyuk macOS-latest is pointed to macOS-11 at the moment. Once macOS-12 is out of private preview we will start the macOS-latest spec transitioning

**Comment by brugg** [comment]
Hi @miketimofeev is there a way for us to use macos-12 now? When setting our work flow to use it is always showing 
```
Waiting for a runner to pick up this job...

**Comment by miketimofeev** [comment]
@brugg please take a look at this comment
https://github.com/actions/virtual-environments/discussions/5370#discussioncomment-2544316

**Comment by miketimofeev** [comment]
@brugg the new image with Xcode 13.3.1 has been deployed.
