### ISSUE TITLE
Add Visual Studio Tools for Office (VSTO)

### ISSUE THREAD

**Issue by Colin-b** [actions/virtual-environments#541]
**Tool information**
- Tool name: Visual Studio Tools for Office (VSTO)
- Add or update? Add
- Desired version: 
- Approximate size: 
- If this is an add request:
  - Brief description of tool: Visual Studio Tools for Office (VSTO)
  - URL for tool's homepage: https://visualstudio.microsoft.com/vs/features/office-tools/

**Area for Triage**:

**Question, Bug, or Feature?**:
Feature

**Virtual environments affected**
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [x] Windows Server 2016 R2
- [x] Windows Server 2019

**Can this tool be installed during the build?**

**Are you willing to submit a PR?**

Yes I am, but I did not dig into what should be done and I will not be able to do it before some time. So if anyone feel like he could, please do :)

**Comment by maxim-lobanov** [comment]
Thank you for your request @Colin-b ,
In scope of #532 , we add `Microsoft.VisualStudio.Workload.Office` component to Visual Studio. Am I right that it is what you are looking for?

**Comment by Colin-b** [comment]
I don't think so unfortunately, But I can test once it's there.

Please find attached a screenshot of dependencies:

![image](https://user-images.githubusercontent.com/7591933/76759880-dbdd0980-678c-11ea-8c12-7fdd07b480e5.png)

**Comment by dsame** [comment]
PR with the required components has beeb merged. The changes will be available in flows on the next deploy

**Comment by Colin-b** [comment]
Thanks a lot @dsame

**Comment by dsame** [comment]
> Thanks a lot @dsame 

Btw, if you upgrade VS2019 and next your project to 142 toolset you do not need to wait for this compatibility fix

**Comment by miketimofeev** [comment]
@Colin-b the image has been deployed. Could you check the behavior, please?

**Comment by miketimofeev** [comment]
@Colin-b I'm going to close the issue. Feel free to contact us if you have any concerns.
Thank you!

**Comment by jsherm-fwdsec** [comment]
Hey @miketimofeev and team. I'm running in to what looks like similar errors when building with the Windows Server 2019 image: 
````
*.vb(26,53): error BC30002: Type 'Excel.Range' is not defined. 
*.vb(96,29): error BC30002: Type 'Excel.Application' is not defined.
````

This project is using VSTO as well. Please let me know if you have any ideas?
