### ISSUE TITLE
Xcode UI test not working on MacOS 12 Monterey runner

### ISSUE THREAD

**Issue by mroi** [actions/virtual-environments#5410]
### Description

I was invited to the macOS 12 beta. I have an Xcode UI test for a macOS app which worked on macOS 11, but now fails to run:
https://github.com/mroi/movie-archive/runs/5846738269

The problem appears to be that macOS 12 is asking the user for consent before running UI automations. On the headless runners, this user interaction never happens and the tests fail with a timeout after a while.

I think the solution would be to reconfigure the Monterey image as described here:
https://developer.apple.com/forums/thread/693850

### Virtual environments affected

macOS 12

### Image version and build link

https://github.com/mroi/movie-archive/runs/5846738269

### Expected behavior

Xcode UI tests for macOS apps should run.

### Actual behavior

Xcode UI tests for macOS apps fail to run with a timeout:
> 2022-04-16 17:26:56.268262+0000 Tests macOS-Runner[5434:806804] Failed to initialize for UI testing: Error Domain=com.apple.dt.XCTest.XCTFuture Code=1000 "Timed out while enabling automation mode." UserInfo={NSLocalizedDescription=Timed out while enabling automation mode.}

### Repro steps

0. Create an Xcode project from the macOS app template, accepting all default settings.
1. Add an actions file to run tests on GitHub.
2. Run the action.

**Comment by al-cheb** [comment]
Hello @mroi,
We will take a look at it.

**Comment by nekrich** [comment]
We are having the same issue with UI test on macOS-12 on MS Hosted Azure Pipelines VMs. It looks like macOS requires user authentication to enable Automation Mode.
@al-cheb , executing `automationmodetool enable-automationmode-without-authentication` on VM and updating the image should help. Unfortunately, this command requires user authorization even with sudo, so we can't add this command to our piplines.

**Comment by al-cheb** [comment]
@mroi , @nekrich - The new image have been deployed.

![image](https://user-images.githubusercontent.com/47745270/165493273-39cd3232-0738-4803-bab7-d628e6019906.png)

**Comment by PadraigK** [comment]
This fixed the issue for me, thank you!
