### ISSUE TITLE
.Net Core 3.1.4 is still in Base-Image 

### ISSUE THREAD

**Issue by Chaouki-Tiouassiouine** [actions/virtual-environments#5416]
### Description

Hi Microsoft,

I am wondering why the base image of Microsoft still includes version 3.1.4:

**.NET Core Runtime**
Location: C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App
3.1.4 3.1.6 3.1.20 3.1.23 5.0.4 5.0.9 5.0.15

Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App
3.1.4 3.1.6 3.1.20 3.1.23 5.0.4 5.0.9 5.0.15

Location: C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App
3.1.4 3.1.6 3.1.20 3.1.23 5.0.4 5.0.9 5.0.15

Version 3.1.4 still has vulnerablities: 
https://www.cvedetails.com/vulnerability-list/vendor_id-26/product_id-43007/version_id-637952/Microsoft-.net-Core-3.1.html

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [X] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

https://github.com/actions/virtual-environments/blob/main/images/win/Windows2019-Readme.md

### Repro steps

Installing image without 3.1.4

**Comment by miketimofeev** [comment]
@Chaouki-Tiouassiouine as per our[ software guidelines](https://github.com/actions/virtual-environments/blob/main/docs/software-and-images-guidelines.md#software-and-images-support-policy) we support 2 latest LTS versions and 1 latest version. For each feature version, only the latest patch is installed. 
I'm afraid we can't remove the version as it will break some customers who still use it. We will remove all the 3.1 set when it is reached end of life.
