### ISSUE TITLE
ubuntu-latest vm image fails to provision - downgrading to ubuntu-18.04 resolves issue

### ISSUE THREAD

**Issue by AaronButler-Veracode** [actions/virtual-environments#5425]
### Description

Previously working ubuntu-latest pipelines have stopped working. It appears to be an provisioning issue:

##[error]An error occurred while provisioning resources (Error Type: Failure).
,##[error]The remote provider was unable to process the request.

### Virtual environments affected

- [ ] Ubuntu 18.04
- [X] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Pool: [Azure Pipelines](https://dev.azure.com/aabutler-veracode/a667cb69-94a6-4f9c-9123-1a138c21d42f/_settings/agentqueues?poolId=&queueId=36)
Image: ubuntu-latest
Started: Today at 11:05 AM
Duration: 39m 24s

### Expected behavior

Expect a ubuntu-latest image to provision and run the maven build command.

### Actual behavior

fails to provision any image and never gets to run

### Repro steps

1) Clone https://github.com/MicrosoftDocs/pipelines-java
2) Create your first Java pipeline - Go to Pipelines, and then select New pipeline.
3) Use Azure project/repo - Azure Pipelines will analyze your repository and recommend the Maven pipeline template.
4) When your new pipeline appears, take a look at the YAML to see what it does (defaults to ubuntu-latest). When you're ready, select Save and run.
5) You're prompted to commit a new azure-pipelines.yml file to your repository. After you're happy with the message, select Save and run again.
6) Follow the build log and the system fails to provision.

**Comment by AaronButler-Veracode** [comment]
This is the one that is failing:
`# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
`
and when I make one change it works again: 
`# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: ubuntu-18.04

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
`

I just tested it again and it is still failing with the ubuntu-latest tag

**Comment by ayyub-nifsc** [comment]
Having the same issue and can confirm `ubuntu-18.04` works, and `ubuntu-latest` doesn't.

**Comment by miketimofeev** [comment]
@AaronButler-Veracode @ayyub-nifsc could you share your Azure DevOps organization names or even better — links to the failed pipelines with `ubuntu-latest`?

**Comment by AaronButler-Veracode** [comment]
Here is a link to one of the failed runs:
https://dev.azure.com/aabutler-veracode/pipelines-java/_build/results?buildId=34&view=results

**Comment by miketimofeev** [comment]
@AaronButler-Veracode is this still an issue for you? Some changes were rolled back from the Azure DevOps side

**Comment by AaronButler-Veracode** [comment]
I just rechecked and I am still getting the same errors: 
https://dev.azure.com/aabutler-veracode/pipelines-java/_build/results?buildId=75&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=78db2542-c627-4140-8a7a-d06178fff4e4

**Comment by miketimofeev** [comment]
@AaronButler-Veracode we have identified the root cause and fixed the issue, sorry for the inconvenience. Could you please try again?

**Comment by AaronButler-Veracode** [comment]
@miketimofeev It is working now! Thank you so much for your help!
