### ISSUE TITLE
Update/Add [hdiutil attach]

### ISSUE THREAD

**Issue by idelfonsog2** [actions/virtual-environments#5426]
### Tool name

hdiutil attach

### Tool license

macOS

### Add or update?

- [X] Add
- [ ] Update

### Desired version

latest

### Brief description of tool

the tool `hdiutil attach` helps mount volumes `.dmg` files on macOS instances

### URL for tool's homepage

https://ss64.com/osx/hdiutil.html

### Provide a basic test case to validate the tool's functionality.

```bash
`hdiutil attach Microsoft\ Intune\ Application\ Restrictions\ Packager\ for\ iOS.dmg`
```

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [X] macOS 10.15
- [X] macOS 11
- [X] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Can this tool be installed during the build?

```bash
not sure its native to macOS
```

**Comment by al-cheb** [comment]
The hdiutil program is a native Apple command line utility for working with disk images

**Comment by idelfonsog2** [comment]
Thank you for the reply al-cheb, does this mean is not included in the `macOS-latest`

**Comment by miketimofeev** [comment]
@idelfonsog2 hdiutil should be included in all macOS versions

**Comment by idelfonsog2** [comment]
Thank you @miketimofeev
