### ISSUE TITLE
Ruby env regression on macOS 11 & macOS 12 images

### ISSUE THREAD

**Issue by nekrich** [actions/virtual-environments#5431]
### Description

We are using MS-hosted VMs on Azure Pipelines.

For two days already we are experiencing issues with UseRubyVersion@0 job.
We want to use 3.0 but it randomly selects [3.1](https://dev.azure.com/macpaw/Cocoa/_build/results?buildId=380770&view=logs&jobId=aaf49f90-569a-552f-f7d1-4900cfb0561e&j=aaf49f90-569a-552f-f7d1-4900cfb0561e&t=fe638b74-ab51-5fb9-6a03-443af0aae648) and trying to access cached gems system still thinks that Ruby [2.7](https://dev.azure.com/macpaw/Cocoa/_build/results?buildId=380812&view=logs&j=96e27d35-3224-5728-c788-87c4dfbffa4c&t=4c2adc8c-020d-5807-81d4-93197c0fe354) is selected.

Attempts to select [3.1 can randomly fail](https://dev.azure.com/macpaw/Cocoa/_build/results?buildId=380057&view=logs&j=ed6dac55-fe15-51da-fc80-662127f776d0&t=303e7c1f-025b-53f5-4fe7-095b178e44c4).

Since the source code of RubyVersion was changed 2 months ago I treat this issue as an environment regression.

And it's strange that Ruby 3.1 is not listed yet, but forcefully selected (or it just logs) when asking for 3.0, but asking for 3.1 fails 🤷.

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [X] macOS 11
- [X] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

20220410.1

### Is it regression?

Yes. We have [successful builds](https://dev.azure.com/macpaw/Cocoa/_build/results?buildId=378689&view=logs&j=96e27d35-3224-5728-c788-87c4dfbffa4c&t=93b79af5-fe1d-4e68-a256-e08710af13a6)

### Expected behavior

Ruby 3.0 is selected

### Actual behavior

An incorrect Ruby version is selected.

### Repro steps

1. Add UseRubyVersion@0 step.
2. Set Ruby version  3.0.
3. Check the current Ruby version.

**Comment by mikhailkoliada** [comment]
Hello @nekrich! It seems we do not have access to your organization's builds.

**Comment by mikhailkoliada** [comment]
Hi again! I am unable to reproduce the problem with the following yaml snippet:

```
strategy:
  matrix:
    mac-11:
      imageName: 'macos-11'
    mac-12:
      imageName: 'macos-12'

pool:
  vmImage: $(imageName)

steps:
- task: UseRubyVersion@0
  inputs:
    versionSpec: '3.0'
- bash: ruby --version
```
<img width="1125" alt="image" src="https://user-images.githubusercontent.com/88318005/165302526-6a010251-f031-40a0-8ac9-f8331a6ca0a6.png">

In the screenshot you can see macOS-11 results, but 12 has no difference.

**Comment by mikhailkoliada** [comment]
Given, that there is no any activity for a week I am going to close the ticket, feel free to reach us out again!
