### ISSUE TITLE
macOS 12 not available as devops hosted agent

### ISSUE THREAD

**Issue by stefanrenne** [actions/virtual-environments#5433]
### Description

macOS 12 is not listed as available hosted agent on https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [X] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

N/A

### Is it regression?

no

### Expected behavior

Being able to select macOS 12 as agent specification in devops pipelines.

### Actual behavior

macOS 12 is not selectable in agent specification in devops pipelines.

### Repro steps

In devops
- Go to pipelines
- Open existing pipeline
- press Edit
- select tasks -> build pipeline
- open dropdown 'agent specification'
- change into macOS12 -> fail / unavalable

**Comment by mikhailkoliada** [comment]
Hello! macOS 12 is in limited preview now, track the progress here https://github.com/actions/virtual-environments/issues/3649
