### ISSUE TITLE
Unable to locate package libicu66

### ISSUE THREAD

**Issue by wangxiaoying** [actions/virtual-environments#5456]
### Description

Previously working ubuntu-latest pipelines has error: `Unable to locate package libicu66` when using `apt install`.

### Virtual environments affected

- [ ] Ubuntu 18.04
- [X] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Version: 20220425.1

Run with error: https://github.com/sfu-db/connector-x/runs/6233230712?check_suite_focus=true
Latest successful: https://github.com/sfu-db/connector-x/runs/6115784269?check_suite_focus=true

### Expected behavior

No error

### Actual behavior

 Error message: `E: Unable to locate package libicu66`.

### Repro steps

Simply install `libicu66` in `ubuntu-latest` or `ubuntu-18.04`:
1. run `apt-get update`
2. run `apt-get install -y libicu66`

**Comment by MehdiChinoune** [comment]
Ubuntu 18.04 has libicu60, and Ubuntu 20.04 has libicu66

**Comment by wangxiaoying** [comment]
> Ubuntu 18.04 has libicu60, and Ubuntu 20.04 has libicu66

Thanks for the heads up. I have unchecked 18.04. My error occurs in 20.04:  https://github.com/sfu-db/connector-x/runs/6233230712?check_suite_focus=true#step:1:4

**Comment by al-cheb** [comment]
> > Ubuntu 18.04 has libicu60, and Ubuntu 20.04 has libicu66
> 
> Thanks for the heads up. I have unchecked 18.04. My error occurs in 20.04: https://github.com/sfu-db/connector-x/runs/6233230712?check_suite_focus=true#step:1:4

Hello @wangxiaoying,
As I can see you use **Ubuntu 22.04 LTS (Jammy Jellyfish)** docker container:

```
jobs:
  rust:
    runs-on: ubuntu-latest
    container: ubuntu
```
![image](https://user-images.githubusercontent.com/47745270/166202358-b86b9206-ce4c-4816-9325-329676a3b796.png)

You should change container tag in your pipeline from the `latest` -> `ubuntu:20.04`.

**Comment by wangxiaoying** [comment]
Hi @al-cheb , thanks for the help! It works perfectly after updating the container version.

**Comment by tuxerrante** [comment]
Hi did this package libicu66 change name in ubuntu 22.04?
