### ISSUE TITLE
Add/Update Resharper Command Line Tools

### ISSUE THREAD

**Issue by jgowdy** [actions/virtual-environments#546]
**Tool information**
- Tool name: Resharper Command Line Tools
- Add or update? Add
- Desired version: Latest
- Approximate size: 
- If this is an add request:
  - Brief description of tool: Free CLI version of Resharper's static code analysis
  - URL for tool's homepage: https://www.jetbrains.com/resharper/download/index.html#section=commandline

**Area for Triage**:

**Question, Bug, or Feature?**: Feature

**Virtual environments affected**
- [X ] macOS 10.15
- [X ] Ubuntu 16.04 LTS
- [X ] Ubuntu 18.04 LTS
- [X ] Windows Server 2016 R2
- [X ] Windows Server 2019

**Can this tool be installed during the build?**

Yes

**Are you willing to submit a PR?**

No

**Comment by maxim-lobanov** [comment]
@jgowdy , thank you for your request!
How much time it takes to install Resharper CTL during the build?

**Comment by litan1106** [comment]
The binaries are about 140 mb.

**Comment by litan1106** [comment]
> The binaries are about 140 mb.

It took around 14s in ubuntu-latest but you could use action/cache to make it even faster.

**Comment by alepauly** [comment]
@jgowdy Thanks for your suggestion but considering that it's a pretty simple install, I think we shouldn't bake into the image. Instead, I would suggest creating an Action to facilitate setting it up.
