### ISSUE TITLE
Update macOS 12 VM to use Xcode 13.3.1 as the default

### ISSUE THREAD

**Issue by JussiPekonen** [actions/virtual-environments#5460]
### Tool name

Xcode

### Tool license

Proprietary

### Add or update?

- [ ] Add
- [X] Update

### Desired version

13.3.1

### Brief description of tool

From [Xcode 13.3.1 Release notes](https://developer.apple.com/documentation/xcode-release-notes/xcode-13_3_1-release-notes):
> When you target iOS 13.4 and later and enable bitcode, the bitcode segment is now stripped correctly. This fixes a crash that prevented some apps from running in older operating systems (iOS 14 and earlier).

In other words, the current default Xcode version (13.3) has a bug that causes crashes at launch on iOS 14 and earlier, thus making builds done with CI automation using the current macOS 12 image have this issue. Once the default Xcode version has been updated, the issue would resolve automatically in the next build(s).

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [X] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

**Comment by miketimofeev** [comment]
@JussiPekonen thanks for the information about the bug. We will announce version switching and prepare PRs soon.

**Comment by miketimofeev** [comment]
https://github.com/actions/virtual-environments/issues/5463
