### ISSUE TITLE
fbgemm missing when I run macOS-11 virtual environment

### ISSUE THREAD

**Issue by bcm-at-zama** [actions/virtual-environments#5461]
### Description

Hello,

On my macOS (intel), 

$ poetry run python -c "import torch; print(torch.backends.quantized.supported_engines)"
['qnnpack', 'none', 'fbgemm']

On the virtual environment (macOS-11),

```
Current runner version: '2.290.1'
Operating System
  macOS
  11.6.5
  20G527
Virtual Environment
  Environment: macos-11
  Version: 20220424.1
  Included Software: https://github.com/actions/virtual-environments/blob/macOS-11/20220424.1/images/macos/macos-11-Readme.md
  Image Release: https://github.com/actions/virtual-environments/releases/tag/macOS-11%2F20220424.1
Virtual Environment Provisioner
  1.0.0.0-main-20220421-1
)
```

I have:

$ poetry run python -c "import torch; print(torch.backends.quantized.supported_engines)"
['qnnpack', 'none']

This is a problem for me because 

```
torch_quantized_model = torch.quantization.quantize_dynamic(
    torch_fc_model, {nn.Linear}, dtype=torch.qint8
)
```

seems to break because of this. 

I have torch (1.11.0) on both my macOS and the GitHub action. 

--

I don't know if it is because of a mistake of mine.

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [X] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

20220424.1

### Expected behavior

I would like 

```
torch_quantized_model = torch.quantization.quantize_dynamic(
    torch_fc_model, {nn.Linear}, dtype=torch.qint8
)
```

to work as on my macOS

### Actual behavior

It doesn't work. It does

```
.venv/lib/python3.8/site-packages/torch/ao/quantization/quantize.py:420: in quantize_dynamic
    convert(model, mapping, inplace=True)
.venv/lib/python3.8/site-packages/torch/ao/quantization/quantize.py:505: in convert
    _convert(
.venv/lib/python3.8/site-packages/torch/ao/quantization/quantize.py:543: in _convert
    reassign[name] = swap_module(mod, mapping, custom_module_class_mapping)
.venv/lib/python3.8/site-packages/torch/ao/quantization/quantize.py:568: in swap_module
    new_mod = mapping[type(mod)].from_float(mod)
.venv/lib/python3.8/site-packages/torch/nn/quantized/dynamic/modules/linear.py:110: in from_float
    qlinear = cls(mod.in_features, mod.out_features, dtype=dtype)
.venv/lib/python3.8/site-packages/torch/nn/quantized/dynamic/modules/linear.py:34: in __init__
    super(Linear, self).__init__(in_features, out_features, bias_, dtype=dtype)
.venv/lib/python3.8/site-packages/torch/nn/quantized/modules/linear.py:161: in __init__
    self._packed_params = LinearPackedParams(dtype)
.venv/lib/python3.8/site-packages/torch/nn/quantized/modules/linear.py:19: in __init__
    self.set_weight_bias(wq, None)

--     


self = <[AttributeError("'LinearPackedParams' object has no attribute '_packed_params'") raised in repr()] LinearPackedParams object at 0x14617c9a0>
weight = tensor([[4.]], size=(1, 1), dtype=torch.qint8,
       quantization_scheme=torch.per_tensor_affine, scale=1.0, zero_point=0)
bias = None

    @torch.jit.export
    def set_weight_bias(self, weight: torch.Tensor, bias: Optional[torch.Tensor]) -> None:
        if self.dtype == torch.qint8:
>           self._packed_params = torch.ops.quantized.linear_prepack(weight, bias)
E           RuntimeError: Didn't find engine for operation quantized::linear_prepack NoQEngine

.venv/lib/python3.8/site-packages/torch/nn/quantized/modules/linear.py:24: RuntimeError
```

which I think is related to the missing `fbgemm`.

### Repro steps

- Install torch 1.11 on a native macOS
- Save

```
import torch
from torch import nn


class FC(nn.Module):
    def __init__(self, input_output):
        super().__init__()
        self.fc1 = nn.Linear(in_features=input_output, out_features=input_output)
        self.act_f = nn.ReLU()
        self.fc2 = nn.Linear(in_features=input_output, out_features=input_output)

    def forward(self, x):
        out = self.fc1(x)
        out = self.act_f(out)
        out = self.fc2(out)

        return out


print(torch.quantization.quantize_dynamic(FC((10)), {nn.Linear}, dtype=torch.qint8)```

as a.py
- Run `python3 a.py`
- You get:

```
FC(
  (fc1): DynamicQuantizedLinear(in_features=10, out_features=10, dtype=torch.qint8, qscheme=torch.per_tensor_affine)
  (act_f): ReLU()
  (fc2): DynamicQuantizedLinear(in_features=10, out_features=10, dtype=torch.qint8, qscheme=torch.per_tensor_affine)
)
```

- Do the same on an instance, it should fail. You should have 

```
    @torch.jit.export
    def set_weight_bias(self, weight: torch.Tensor, bias: Optional[torch.Tensor]) -> None:
        if self.dtype == torch.qint8:
>           self._packed_params = torch.ops.quantized.linear_prepack(weight, bias)
E           RuntimeError: Didn't find engine for operation quantized::linear_prepack NoQEngine
```

which I think might be related to the missing `fbgemm`

**Comment by miketimofeev** [comment]
Hi @bcm-at-zama!
Have you tried building fbgemm from the source? Does it help?
```bash
git clone --recursive https://github.com/pytorch/FBGEMM.git
cd FBGEMM
# if you are updating an existing checkout
git submodule sync
git submodule update --init --recursive
mkdir build && cd build
cmake ..
make
make install
```

**Comment by bcm-at-zama** [comment]
Thanks, let me have a look

**Comment by al-cheb** [comment]
@bcm-at-zama, Any updates?

**Comment by bcm-at-zama** [comment]
Hey. I've asked the question in PyTorch community, https://discuss.pytorch.org/t/torch-backends-quantized-supported-engines-is-different-on-macos-virtual-env/150612 . I have no answer for the moment. I would like to avoid to have to compile 3rd party things on GHA, I would like first to understand why the installation of torch on GHA or on my local MacBookPro is different
