### ISSUE TITLE
[macOS] Xcode versions 13.2 & 13.3 will be removed, 13.3.1 will be set as the default one on May, 16

### ISSUE THREAD

**Issue by miketimofeev** [actions/virtual-environments#5463]
### Breaking changes

We are going to deprecate Xcode versions 13.2 & 13.3 from the image and create symlinks from 13.2 to 13.2.1 and from 13.3 to 13.3.1 instead.
Xcode 13.3.1 will be set as the default version.

### Target date

The image deployment is starting on May, 16 and will take 3-4 days.

### The motivation for the changes

According to our [Software and image guidelines](https://github.com/actions/virtual-environments/blob/main/docs/software-and-images-guidelines.md)
old patch Xcode versions are deprecated in 3 months, which have already passed since Xcode 13.2 release. Xcode 13.3 contains a critical bug that causes crashes at launch on iOS 14 and earlier so we would like to replace it in favor of 13.3.1

### Possible impact

There should be no impact as 13.2 will point to 13.2.1 and 13.3 to 13.3.1

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [X] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Mitigation ways

n\a

**Comment by BastiaanAndriessen** [comment]
Hi, any update on this? I'm having issues resolving swift packages on the CI since locally I'm running a newer version of Xcode (13.3.1).

**Comment by miketimofeev** [comment]
Hi @BastiaanAndriessen!
This is now deployed Xcode 13.3.1 should be the default one

**Comment by TimotiusLeonardo** [comment]
Hi @miketimofeev sorry to bother you.... thanks for update the new XCode to our CI recently, we really glad for the update. But it seems that in App Center still using XCode 13.2.1 (Correct me if i am wrong 😁). So i wonder, when we can use XCode 13.3.1 in App Center too?

**Comment by miketimofeev** [comment]
@TimotiusLeonardo please address this question to AppCenter support as they are responsible for such changes
