### ISSUE TITLE
Need add Azure Tags when resources are created

### ISSUE THREAD

**Issue by alex-3sr** [actions/virtual-environments#5468]
### Description

Hi,

It's happen that some tenant have Azure Policy with tag enforcement.
So, for build DevOps images, we need create resources with at least corporate tags even if temporary, and it's especially right cause  resource (like resource groupe for pkr-***) doesn't exist yet, and scope exclusion is not possible.

I already start a new PR who include Azure tags for the AzureRM part. I'm still working on packer part, but I'm not expert on this. I Found a workaround by using a temporary file, but I don't this this is the "beautiful way".

Here the PR -> https://github.com/actions/virtual-environments/pull/5467

Thanks, and have a nice day
Alexandre

### Virtual environments affected

- [X] Ubuntu 18.04
- [X] Ubuntu 20.04
- [X] macOS 10.15
- [X] macOS 11
- [X] macOS 12
- [X] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

Not Relevant

### Is it regression?

New feature

### Expected behavior

Add tags to new Azure resources

### Actual behavior

It's not possible at this time to use `GenerateResourcesAndImage` on a tenant who have Azure Tag Policy enforcement

### Repro steps

1. Add an Azure Policy with at least 1 tag enforcement
2. Start a GenerateResourcesAndImage
3.  You'll get an error like `==> vhd: ERROR: -> RequestDisallowedByPolicy : Resource 'pkr-Resource-Group-ihlt9tthli' was disallowed by policy. Policy identifiers ....`

**Comment by miketimofeev** [comment]
@alex-3sr thanks for the contribution, left a comment in the PR
