### ISSUE TITLE
macos-12 / Xcode 13.3 / Xcode 13.3.1: xcodebuild error "Requested but did not find extension point with identifier Xcode.IDEKit.ExtensionSentinelHostApplications for extension Xcode.DebuggerFoundation.AppExtensionHosts.watchOS of plug-in com.apple.dt.IDEWatchSupportCore"

### ISSUE THREAD

**Issue by crdisdero** [actions/virtual-environments#5469]
### Description

When I try to execute a script in a GitHub Actions workflow using macos-12 and Xcode 13.3 or 13.3.1 (tried both) that uses xcrun xctrace to get a list of simulators installed and the UUID for the one that I'm looking for, I get two errors reported and the script fails:

```
2022-05-02 18:44:17.656 xcodebuild[1223:12528] Requested but did not find extension point with identifier Xcode.IDEKit.ExtensionSentinelHostApplications for extension Xcode.DebuggerFoundation.AppExtensionHosts.watchOS of plug-in com.apple.dt.IDEWatchSupportCore
2022-05-02 18:44:17.656 xcodebuild[1223:12528] Requested but did not find extension point with identifier Xcode.IDEKit.ExtensionPointIdentifierToBundleIdentifier for extension Xcode.DebuggerFoundation.AppExtensionToBundleIdentifierMap.watchOS of plug-in com.apple.dt.IDEWatchSupportCore
```

The script in question does this:
```
#!/bin/sh

simudid=`xcrun xctrace list devices | grep "$SIMULATOR_NAME" | grep -E -o -i "([0-9a-f]{8}-([0-9a-f]{4}-){3}[0-9a-f]{12})"`
xcrun simctl boot $simudid
```

The output from the build step in my GitHub Actions workflow is:
```
Run exec ./.github/scripts/preheat_sim.sh
  exec ./.github/scripts/preheat_sim.sh
  shell: /bin/bash -e {0}
  env:
    simulator_name: iPhone SE (2nd generation)
    simulator_version: 15.4
    sdk_version: iphonesimulator15.4
    xcode_version: 13.3
    cache_branch_name: master
    derived_data: ./output
    SSH_AUTH_SOCK: /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T//ssh-v5f1fzHcrzBt/agent.1208
    SSH_AGENT_PID: 1209
    SIMULATOR_NAME: iPhone SE (2nd generation) Simulator (15.4)
2022-05-02 18:44:17.656 xcodebuild[1223:12528] Requested but did not find extension point with identifier Xcode.IDEKit.ExtensionSentinelHostApplications for extension Xcode.DebuggerFoundation.AppExtensionHosts.watchOS of plug-in com.apple.dt.IDEWatchSupportCore
2022-05-02 18:44:17.656 xcodebuild[1223:12528] Requested but did not find extension point with identifier Xcode.IDEKit.ExtensionPointIdentifierToBundleIdentifier for extension Xcode.DebuggerFoundation.AppExtensionToBundleIdentifierMap.watchOS of plug-in com.apple.dt.IDEWatchSupportCore
```

I've executed this on my own box running macOS-12.3.1 and Xcode 13.3.1 and it works fine with no errors:
```
% xcrun xctrace list devices | grep "iPhone SE (2nd generation) Simulator (15.4)" | grep -E -o -i "([0-9a-f]{8}-([0-9a-f]{4}-){3}[0-9a-f]{12})"
E67592B5-8893-416A-B347-E9EF42A99C25
```

I've read that some people who've run into this on their local boxes could fix by installing Xcode updates or additional install items, but I'm not sure if that applies here or how I could do this in a workflow.  Any help is most appreciated.

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [X] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Virtual Environment
  Environment: macos-12
  Version: 20220425.3
  Included Software: https://github.com/actions/virtual-environments/blob/macOS-12/20220425.3/images/macos/macos-12-Readme.md
  Image Release: https://github.com/actions/virtual-environments/releases/tag/macOS-12%2F20220425.3

### Expected behavior

```
% xcrun xctrace list devices | grep "iPhone SE (2nd generation) Simulator (15.4)" | grep -E -o -i "([0-9a-f]{8}-([0-9a-f]{4}-){3}[0-9a-f]{12})"
E67592B5-8893-416A-B347-E9EF42A99C25
```

With no errors and the UUID of the simulator "iPhone SE (2nd generation) Simulator (15.4)"

### Actual behavior

Get errors:
```
2022-05-02 18:44:17.656 xcodebuild[1223:12528] Requested but did not find extension point with identifier Xcode.IDEKit.ExtensionSentinelHostApplications for extension Xcode.DebuggerFoundation.AppExtensionHosts.watchOS of plug-in com.apple.dt.IDEWatchSupportCore
2022-05-02 18:44:17.656 xcodebuild[1223:12528] Requested but did not find extension point with identifier Xcode.IDEKit.ExtensionPointIdentifierToBundleIdentifier for extension Xcode.DebuggerFoundation.AppExtensionToBundleIdentifierMap.watchOS of plug-in com.apple.dt.IDEWatchSupportCore
```

### Repro steps

1. Create a workflow that uses macos-12 VM and Xcode 13.3 or higher.
2. Create a run step that executes the following script:

```
xcrun xctrace list devices | grep "iPhone SE (2nd generation) Simulator (15.4)" | grep -E -o -i "([0-9a-f]{8}-([0-9a-f]{4}-){3}[0-9a-f]{12})"
```

**Comment by miketimofeev** [comment]
Hi @crdisdero!
We will take a look.

**Comment by abarisain** [comment]
The logs are an Apple bug: I get those logs on my actual macOS computer every time I use "xcodebuild" for the first time after rebooting (along with a lot of MobileDevice.framework logs [just like that](https://developer.apple.com/forums/thread/698628) )


Even though this is printed to stderr, it can safely be ignored if you can. Not seeing the simulators is unrelated to those logs on my computer: I get those and I get my device list

**Comment by crdisdero** [comment]
> The logs are an Apple bug: I get those logs on my actual macOS computer every time I use "xcodebuild" for the first time after rebooting (along with a lot of MobileDevice.framework logs [just like that](https://developer.apple.com/forums/thread/698628) )
> 
> Even though this is printed to stderr, it can safely be ignored if you can. Not seeing the simulators is unrelated to those logs on my computer: I get those and I get my device list. Your issue is probably valid, but the logs are a dead end and can't be solved.

Thanks for the info, but this seems to be more than a warning for me - it actually prevents the command from working, so I think this issue needs to be fixed on the VM - unless I'm missing something.

**Comment by abarisain** [comment]
No it doesn't, I have the same errors on my mac (and a LOT more) and the command works fine. Also, only Apple can fix this.

Something is wrong, but that's not it.

**Comment by crdisdero** [comment]
You are correct, [abarisain](https://github.com/abarisain).  The real issue here is NOT those log messages, but a small syntax error in my script.  The grep commands you indicate are correct and if typed in properly, work just fine.  This issue is NOT a problem with the VM on GitHub Actions, but was a syntax error in my script.  Thanks for all your help and feedback.  Sorry for the noise on this.

**Comment by abarisain** [comment]
Glad you figured it out!

**Comment by Eronred** [comment]
got this error! any update?

**Comment by abarisain** [comment]
Those are warnings, if you have an issue it's coming from somewhere else

Nothing GitHub can do anyway, it's on Apple to fix those

**Comment by Gerst20051** [comment]
Seeing this gave me the idea to create a script to show a list and launch the selected simulator.

`[$]> xcrun simctl boot $(xcrun xctrace list devices | \grep -E -i '([0-9a-f]{8}-([0-9a-f]{4}-){3}[0-9a-f]{12})' | fzf --no-sort | \grep -E -o -i '([0-9a-f]{8}-([0-9a-f]{4}-){3}[0-9a-f]{12})')`

<img width="959" alt="Screen Shot 2022-08-07 at 2 48 41 PM" src="https://user-images.githubusercontent.com/235372/183312291-b3f4ad29-b93f-407a-9b59-2598c16eb1af.png">
