### ISSUE TITLE
Cleanup does not remove the service principal used in resource deployment.

### ISSUE THREAD

**Issue by swapnilrkambli** [actions/virtual-environments#5472]
### Description

Cleanup script should remove the service principal used in resource provisioning. Or either reuse the existing service principal instead of creating new service principal for every run.

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [X] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

NA

### Expected behavior

Cleanup script should remove the service principal used in resource provisioning. Or either reuse the existing service principal instead of creating new service principal for every run.

### Actual behavior

Every run creates a new service principal and it is not removed in cleanup section.

### Repro steps

1. Note the existing service principals and the contributor role assignments role assignments at subscription level.
2. Run the script GenerateResourcesAndImage.
3. Once the script completes/fails, list the service principals and contributor role assignments at subscription level.

**Comment by al-cheb** [comment]
Hey @swapnilrkambli, 
We will take a look at it.

**Comment by al-cheb** [comment]
@swapnilrkambli,
1. _Or either reuse the existing service principal instead of creating new service principal for every run._ - You can pass `AzureClientId` parameter to the script.
2. Cleanup script should remove the service principal used in resource provisioning - https://github.com/actions/virtual-environments/pull/5481
