### ISSUE TITLE
Kubectl in ubuntu20-20220503.1 breaks EKS integration

### ISSUE THREAD

**Issue by shallax** [actions/virtual-environments#5493]
### Description

When trying to use kubectl to communicate with AWS EKS, it reports the following:

```error: exec plugin: invalid apiVersion "client.authentication.k8s.io/v1alpha1"```

I can't follow the Kubectl version numbers. The previous image used Kubectl v1.23.6, this new one uses Kubectl 4.5.4?

Issue is similar to this: https://www.reddit.com/r/k8s/comments/ui46zf/deploying_on_eks_cia_travis_ci_fails/

### Virtual environments affected

- [ ] Ubuntu 18.04
- [X] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

No public example

### Expected behavior

Kubectl authentication should work.

### Actual behavior

Kubectl authentication does not work.

### Repro steps

Try using kubectl to communicate with an EKS cluster in any way.

**Comment by al-cheb** [comment]
We have updated kubectl version to 1.24.0. Looks like it is a known issue - https://github.com/kubernetes/kubectl/issues/1210

**Comment by shallax** [comment]
Thanks for the quick response. I went with the former set of sudo commands to fudge the version in the image and it worked.

Suspect this is going to cause a storm, so is there any chance of downgrading in the image?

**Comment by bendotexe** [comment]
Great to see this being sorted so quickly! Is there an Azure DevOps Pipelines equivalent to that task?

**Comment by shallax** [comment]
`steps:
- script: |
    which kubectl
    kubectl version || true
    sudo curl -o /usr/local/bin/kubectl -LO "https://dl.k8s.io/release/v1.23.6/bin/linux/amd64/kubectl"
    sudo chmod +x /usr/local/bin/kubectl
    kubectl version || true
    exit 0
  displayName: Downgrade kubectl`

then in each of your jobs (joy!):

`jobs:
- job: build_and_publish
  displayName: Build and publish
  dependsOn: ${{parameters.dependsOn}}
  steps:
  - template: /pipelines/jobs/downgrade_kubectl.yaml
....`

**Comment by bendotexe** [comment]
An ADO supported root level spec would be best yeah but in the meantime that's going to unblock us by the looks of things so thanks!

**Comment by ahilmathew** [comment]
> As a workaround you can rollback to 1.23.6:
> 
> ```
> sudo curl -o /usr/local/bin/kubectl -LO "https://dl.k8s.io/release/v1.23.6/bin/linux/amd64/kubectl"
> sudo chmod +x /usr/local/bin/kubectl
> ```


Thanks for the workaround. Had pipeline failures out of nowhere.

**Comment by checor** [comment]
I can confirm that this also happens to Ubuntu 18.04.
I will wait some days and if there are still problems, I will apply the workaround. Kudos!

**Comment by Voxelot** [comment]
Now that [aws-cli](https://github.com/aws/aws-cli/issues/6920) has resolved the issue on their end, it seems like the problem is that the Github hosted runners are running on stale images.

**Comment by oxeye-schmil** [comment]
I've encountered the same issue with azure/setup-helm@v1
Is there a workaround for like the the one for azure/setup-kubectl@v2.0

**Comment by jake8787** [comment]
Seems like facing it for Windows19 here [20220503](https://github.com/actions/virtual-environments/releases/tag/win19%2F20220503.1) however on paper it says Kubectl **1.23.6** 
I am using Azure and Packer to build an image. Is there a way to resolve it or new image [20220511](https://github.com/actions/virtual-environments/releases/tag/win19%2F20220511.2) has everything sorted already?

**Comment by al-cheb** [comment]
Close as external - https://github.com/aws/aws-cli/issues/6920
