### ISSUE TITLE
SwiftFormat removed from macOS 12

### ISSUE THREAD

**Issue by bdrelling** [actions/virtual-environments#5494]
### Description

SwiftFormat 0.49.7 is on the `macos-11` runner: https://github.com/actions/virtual-environments/blob/main/images/macos/macos-11-Readme.md#tools

But it's missing from the `macos-12` runner: https://github.com/actions/virtual-environments/blob/main/images/macos/macos-12-Readme.md#tools

1. Why was it removed? I can't find any news or information on this.
2. Can it be added back? SwiftFormat is an extremely widespread tool. If `macos-12` includes SwiftLint, it should probably also include `SwiftFormat`.

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [X] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

n/a

### Is it regression?

Yes, macos-11 included SwiftFormat.

### Expected behavior

SwiftFormat is included.

### Actual behavior

SwiftFormat is not included.

### Repro steps

Attempt to run SwiftFormat on `macos-12`.

**Comment by al-cheb** [comment]
Hey @bdrelling,
We will pre-install  ` SwiftFormat` on macOS-12.

**Comment by bdrelling** [comment]
@al-cheb Incredibly quick response, really appreciate it! 

I'm not sure how to keep up with changes to the runners, do you know when/how this would be added to the image?

In the meantime, it is simple enough to add a `brew install swiftformat` step for now, so this isn't urgent, just inconvenient.


Thanks again!

**Comment by al-cheb** [comment]
The new image has been deployed with swiftformat on board.
