### ISSUE TITLE
Update/Add [tool name]

### ISSUE THREAD

**Issue by SayakMukhopadhyay** [actions/virtual-environments#5498]
### Tool name

GNU moreutils

### Tool license

Probably GPL

### Add or update?

- [X] Add
- [ ] Update

### Desired version

0.67-1

### Approximate size

237kb

### Brief description of tool

This package provides a collection of tools that can be very handy when working on the shell. Right now, Ubuntu Focal can install 0.63-1 but newer versions are available upto 0.67-1

### URL for tool's homepage

https://joeyh.name/code/moreutils/

### Virtual environments affected

- [X] Ubuntu 18.04
- [X] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Tool installation time in runtime

On my VM it took around 8 seconds

### Are you willing to submit a PR?

Yes

**Comment by al-cheb** [comment]
hi @SayakMukhopadhyay, considering that installing moreutils is fast on demand, we won't be adding it to the image at this time. thanks for the suggestion.
