### ISSUE TITLE
overlayfs: consider setting redirect_dir=off module parameter

### ISSUE THREAD

**Issue by mythi** [actions/virtual-environments#550]
**Describe the bug**
We just moved to use Actions but realized that our (Clear Linux based) container builds suffer from `redirect_dir` being enabled with `overlay`. Would you consider adding `redirect_dir=off` module parameter?

It also looks `docker info` gives `Native Overlay Diff` false. [This conversation](https://stackoverflow.com/questions/46787983/what-native-overlay-diff-mean-in-overlay2-storage-driver) suggests that `true` would give better performance.

**Area for Triage**: 
linux
docker

**Question, Bug, or Feature?**: 
Bug/Feature

**Virtual environments affected**
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [X] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Comment by alepauly** [comment]
hi @mythi, we looked into this briefly and one concern we currently have is what effect this would have on existing jobs that depend on the current setting. Any idea?

**Comment by mythi** [comment]
> one concern we currently have is what effect this would have on existing jobs that depend on the current setting

no idea, sorry. I've noticed the equivalent kernel config (`CONFIG_OVERLAY_FS_REDIRECT_DIR`) is not set in Fedora and Debian (stable) kernels at least.

**Comment by alepauly** [comment]
hi @mythi, we have been unable to verify the side effects from doing this work and considering the risk to existing workflows I don't think we can make the change at this time. I'll close this but if you are able to figure out more information or a workaround to ensure we won't break things, please reopen and we can discuss. Thanks for reaching out!
