### ISSUE TITLE
Update/Add AIX on ppc64, Linux on s390x, Linux on ppc64le

### ISSUE THREAD

**Issue by bmarwell** [actions/virtual-environments#5501]
### Tool name

OS

### Tool license

linux: GPLv2+, AIX: IBM

### Add or update?

- [X] Add
- [ ] Update

### Desired version

latest

### Brief description of tool

Linux is already a tool. Let's add some more platforms for build support and AIX for platform support.

SLES supports s390x and ppc64le, not sure about others.

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Are you willing to submit a PR?

no

**Comment by panekj** [comment]
This won't happen as Azure doesn't provide VMs running on those architectures.

You can use Docker containers with Qemu to run different architectures in GHA.

**Comment by al-cheb** [comment]
@bmarwell , If you want to use more platform you should create a self-hosted pool.
