### ISSUE TITLE
Pre-install main iOS Simulators for all Xcode versions

### ISSUE THREAD

**Issue by maxim-lobanov** [actions/virtual-environments#551]
**Tool information**
- Tool name: iOS Simulators
- Add or update? Add
- Approximate size: 
- If this is an add request:
  - Brief description of tool: 
  - URL for tool's homepage: 

**Context**
For now only default iOS simulators are installed on macOS images. The list of pre-installed simulators is located in macOS High Sierra docs and macOS Mojave docs.

Sometimes customers need to use non-default simulators (like iOS 11 simulators for Xcode 10.3). For now they have to use xcversion tool to install those simulators during the build. It takes some time and it would be great to pre-install some simulators for all Xcode versions.

**Suggestion**
Pre-install the latest minor version of each major version of Xcode (like 10.3.2, 11.4).
This issue was created to track customers' interest for this feature.

**Area for Triage**:
Apple

**Question, Bug, or Feature?**:
Feature request

**Virtual environments affected**
- [x] macOS 10.15

**Can this tool be installed during the build?**
The command `xcversion simulators --install='iOS <VERSION>'` can be used to install specific simulator for all Xcode versions.

**Comment by maxim-lobanov** [comment]
Move the work item from https://github.com/microsoft/azure-pipelines-image-generation/issues/1199 because it is very popular and it is something that we would like to consider in future

**Comment by manuyavuz-pointr** [comment]
Hi,

Are there any updates on this?

https://github.com/actions/virtual-environments/blob/master/images/macos/macos-10.15-Readme.md#installed-simulators

According to above list, macos image only has iOS 13 as major version, which is pretty limited imo.

Do you have any plan on maintaining additional previous major versions?

Thanks

**Comment by b-onc** [comment]
We're also in need of this. Currently, installing the simulators take too long.

**Comment by svenmuennich** [comment]
A workaround we found is to symlink any simulators from the Xcode bundles they are part of to `/Library/Developer/CoreSimulator/Profiles/Runtimes`, which is where Xcode also installs additional runtimes.

So based on the [this list of simulators](https://github.com/actions/virtual-environments/blob/master/images/macos/macos-10.15-Readme.md#installed-simulators) an iOS 12.4 device can be added as follows:
```yml
- name: Prepare iOS 12 simulator
  run: |
    sudo mkdir -p /Library/Developer/CoreSimulator/Profiles/Runtimes
    sudo ln -s /Applications/Xcode_10.3.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/Library/CoreSimulator/Profiles/Runtimes/iOS.simruntime /Library/Developer/CoreSimulator/Profiles/Runtimes/iOS\ 12.4.simruntime
    xcrun simctl list runtimes
    xcrun simctl create custom-test-device "iPad Pro (9.7-inch)" "com.apple.CoreSimulator.SimRuntime.iOS-12-4"
    xcrun simctl list devices 12.4
```

**Comment by dmitry-shibanov** [comment]
Hello, we have investigated provided workaround with symlink simulators to CoreSimulator directory and it works without drawbacks.
To use specific simulator with any Xcode, you should
1) Find Xcode where this simulator is [installed](https://github.com/actions/virtual-environments/blob/main/images/macos/macos-10.15-Readme.md#installed-simulators)
2) Create symlink using the following command
- For Xcode > 10.3
<XCODE_PATH>/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime /Library/Developer/CoreSimulator/Profiles/Runtimes/iOS\ <IOS_VERSION>.simruntime

**Comment by erisu** [comment]
I am also in favor of preinstalling the latest minor version of each major version of Xcode.

I have been trying to find a way to test with the iOS 11 simulator but the versions of Xcode that are bundled do not come with iOS 11 Simulator.
`xcversion simulators` does seem like an option but downloading around 2gb each run? Doesn't sound very efficient.

Though the iPhones where iOS 11 was initially released with are discontinued, they are still supported. It would be nice to still include iOS 11 in a testing matrix.

**Comment by kylebshr** [comment]
We'd like to move to Github Actions on the [Blueprint](https://github.com/square/Blueprint) repo, but we need to run our tests using the latest version of Xcode on simulators for iOS 10, 11, 12, 13 and 14. While it seems like we can set up an iOS 12 and 13 simulator, there's no way to install an iOS 10 or 11 one. We would definitely appreciate a way to install those, as well as an easier way to set up versions other than the primary version shipped with the Xcode version.

**Comment by kyleve** [comment]
Going to +1 this as well – our tests run on Xcode 12, but we deploy back to iOS 11 – so we need the sim runtimes of 14, 13, 12, and 11 installed to feasibly be able to use Github actions.

My understanding is that these runtimes just need to be installed once when prepping the Xcode version image – and then everyone will be able to use them.

**Comment by AlenaSviridenko** [comment]
Hi folks,
after long and hot internal discussions, we come up to a conclusion to not install additional simulators due to several reasons:
1. Workaround provided in [this comment](https://github.com/actions/virtual-environments/issues/551#issuecomment-669226983) allows using simulators of different Xcode versions without any noticeable build time increase.
2. We cannot afford to install more simulators for each Xcode due to maintenance, image generation time and image space concerns.

I am closing this issue, please, feel free to contact us in case of any other questions. 
Thank you.

**Comment by skyflow-tejesh-reddy** [comment]
We are facing the same issue as above. @zeeshankhan were you able to find a solution to this?

**Comment by couchdeveloper** [comment]
Dear @maxim-lobanov 

During evaluation of GitHub Actions for our app, I ran in to the situation that on macOS-11 runner, only iOS 15 version is available in the simulators.

Xcode ships simulators only with the newest iOS versions. However, for testing it is absolutely crucial to have simulators for several major versions of iOS on each runner:

In practice it is never the case, that an App will only be deployed to the AppStore which runs only on the newest iOS version. The code to test can have several iOS version availability constraints. Some code only runs on the newest iOS versions, some other uses a fallback when run on older versions. So, we have to test this.

Having to preinstall the simulators with the iOS versions required for testing, simply takes too long and is no option, not even a temporary solution. So, for us, this is a bummer!

So, we would be very happy if there will be  a couple more iOS Simulators preinstalled on the runners. I would suggest to install the latest version for every major version and the most recent version which are available in the Simulator, for example, 13.6, 14.5, and 15.1

**Comment by svenmuennich** [comment]
> ```
> xcrun simctl create "iPhone 8" "com.apple.CoreSimulator.SimRuntime.iOS-14-4"
> ```

`xcrun simctl create` takes up the three arguments, where the runtime is the optional third argument. The second argument must be a device type identifier (can be listed via `xcrun simctl list devicetypes`). So for an iPhone 8 running iOS 14.4 the command would have to look as follows:
```
xcrun simctl create "iPhone 8" "com.apple.CoreSimulator.SimDeviceType.iPhone-8" "com.apple.CoreSimulator.SimRuntime.iOS-14-4"
```

**Comment by jshier** [comment]
> Hi folks, after long and hot internal discussions, we come up to a conclusion to not install additional simulators due to several reasons:
> 
> 1. Workaround provided in [this comment](https://github.com/actions/virtual-environments/issues/551#issuecomment-669226983) allows using simulators of different Xcode versions without any noticeable build time increase.
> 2. We cannot afford to install more simulators for each Xcode due to maintenance, image generation time and image space concerns.
> 
> I am closing this issue, please, feel free to contact us in case of any other questions. Thank you.

It's increasingly clear that GitHub's current approach isn't sustainable and doesn't track how customers actually want to use the product, so the single OS images should be abandoned. Instead, GitHub should follow the approach of various other CI vendors and create Xcode versioned images. This increases the number of images but allows each to fully represent the capabilities of the Xcode version it contains. All simulators, the latest compatible tools, everything. Otherwise GitHub's macOS will continue becoming less and less competitive as the overall size of the image forces more and more compromise on the version of tools installed.

**Comment by abegehr** [comment]
I agree that this issue should be re-opened. GitHub Actions should support all latest major iOS version on the latest Xcode version. Target usage: run iOS UI tests on iOS 18, 17, and 16 from a Xcode 16 project.

**Comment by abegehr** [comment]
Also, it seems the work-around no longer works with Xcode 15 and 16, since they save the simruntime in some volume instead of the path mentioned above.
