### ISSUE TITLE
Commandline tools on macos-12 runners printing errors on stdout

### ISSUE THREAD

**Issue by PatTheMav** [actions/virtual-environments#5510]
### Description

Using any tool from the Xcode commandline tools on a macos-12 runner leads to multiple error messages being printed on `stdout` breaking build scripts and other systems parsing output of these tools.

In our case Qt runs `/usr/bin/xcrun` to detect the available macOS SDK on the machine, but expects a simple version string (e.g. "12.3").

Right now the following two lines are always printed by commandline tools (we also confirmed this happens when running e.g. `lipo`):

```
2022-05-09 20:39:45.963 xcodebuild[5420:22038] Requested but did not find extension point with identifier Xcode.IDEKit.ExtensionSentinelHostApplications for extension Xcode.DebuggerFoundation.AppExtensionHosts.watchOS of plug-in com.apple.dt.IDEWatchSupportCore
2022-05-09 20:39:45.964 xcodebuild[5420:22038] Requested but did not find extension point with identifier Xcode.IDEKit.ExtensionPointIdentifierToBundleIdentifier for extension Xcode.DebuggerFoundation.AppExtensionToBundleIdentifierMap.watchOS of plug-in com.apple.dt.IDEWatchSupportCore
```

Note that this will only happen on the first ever invocation of the tool on the runner. Any consecutive invocation will return the expected results.

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [X] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

20220429.1

### Is it regression?

20220501.1

### Expected behavior

The Xcode and commandline tool environment on runners should be in workable condition and should not print errors.

### Actual behavior

Invoking a Xcode commandline tool for the first time pollutes output with several error messages.

### Repro steps

1. Set up GitHub Actions job with a macos-12 runner
2. Run the command `/usr/bin/xcrun --sdk macosx -show-sdk-version` in a bash shell step
3. Observe the output before the expected output of "12.3"

**Comment by al-cheb** [comment]
Hi @PatTheMav,
As a temporary workaround you can use:
```
- run: |
     sudo xcode-select -s /Library/Developer/CommandLineTools
     /usr/bin/xcrun --sdk macosx -show-sdk-version
```
![image](https://user-images.githubusercontent.com/47745270/167590552-0d72426f-643e-4fc6-873e-add43f3d7fe7.png)

**Comment by al-cheb** [comment]
We should wait a fix from Apple. I am planning to close the thread as external issues:
https://developer.apple.com/forums/thread/703233
https://developer.apple.com/forums/thread/706472
