### ISSUE TITLE
Add clang-tidy

### ISSUE THREAD

**Issue by juliancarrivick** [actions/virtual-environments#5518]
### Tool name

clang-tidy

### Tool license

Apache

### Add or update?

- [ ] Add
- [X] Update

### Desired version

For each available clang toolset

### Brief description of tool

Provide linting of C/C++ code.

### URL for tool's homepage

https://releases.llvm.org/14.0.0/tools/clang/tools/extra/docs/index.html

### Provide a basic test case to validate the tool's functionality.

```bash
echo "struct S{};" >> test.cpp
clang-tidy --checks=.* test.cpp
```

### Virtual environments affected

- [X] Ubuntu 18.04
- [X] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Can this tool be installed during the build?

```bash
Should already be provided by the APT sources as far as I can tell. I think all that needs doing is adding `clang-tidy-$version` to the `apt-get` call in `clang.sh`, then adding appropriate `update-alternatives` lines for `clang-tidy` and `run-clang-tidy`.
```

### Tool installation time in runtime

<30s

### Are you willing to submit a PR?

Yes :)

**Comment by igorboskovic3** [comment]
Hi @juliancarrivick, thank you for feature request. 
We will decide on adding the tool to the images and let you know.

**Comment by miketimofeev** [comment]
@juliancarrivick feel free to submit a PR

**Comment by juliancarrivick** [comment]
Great, I'll have a go next week :)

**Comment by miketimofeev** [comment]
@juliancarrivick the images with clang-tidy are deployed.
Thank you for your contribution!
