### ISSUE TITLE
Cannot add PPA: 'ppa:~git-core/ubuntu/ppa'

### ISSUE THREAD

**Issue by Siebrandf** [actions/virtual-environments#5519]
### Description

The packer build based on the Ubuntu2004.json (Azure Devops) fails with the following errors since a couple days. Nothing has changed on our end. Strangely enough the ubuntu2204.json build does work fine but we can't use this image with an Azure VMSS because there's no supported OMSAgent available yet. 

==> azure-arm: Provisioning with shell script: /agent/_work/4/s/virtual-environments/images/linux/scripts/installers/git.sh
    azure-arm: Cannot add PPA: 'ppa:~git-core/ubuntu/ppa'.
    azure-arm: ERROR: '~git-core' user or team does not exist.
==> azure-arm: Provisioning step had errors: Running the cleanup provisioner, if present...
==> azure-arm: 
==> azure-arm: Deleting individual resources ...

I searched for a way to prevent packer to start the cleanup process so we can login to the build VM. Does anyone has some suggestions to resolve the issue or prevent the cleanup right away?

### Virtual environments affected

- [ ] Ubuntu 18.04
- [X] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

"image_offer": "0001-com-ubuntu-server-focal",
"image_sku": "20_04-lts",

### Expected behavior

==> azure-arm: Provisioning with shell script: /agent/_work/2/s/virtual-environments/images/linux/scripts/installers/git.sh
    azure-arm: Hit:1 http://azure.archive.ubuntu.com/ubuntu focal InRelease
    azure-arm: Hit:2 http://azure.archive.ubuntu.com/ubuntu focal-updates InRelease
    azure-arm: Hit:3 http://azure.archive.ubuntu.com/ubuntu focal-backports InRelease
    azure-arm: Hit:4 http://azure.archive.ubuntu.com/ubuntu focal-security InRelease
    azure-arm: Hit:5 https://packages.microsoft.com/ubuntu/20.04/prod focal InRelease
    azure-arm: Get:6 http://ppa.launchpad.net/git-core/ppa/ubuntu focal InRelease [23.8 kB]
    azure-arm: Get:7 http://ppa.launchpad.net/git-core/ppa/ubuntu focal/main amd64 Packages [3024 B]
    azure-arm: Get:8 http://ppa.launchpad.net/git-core/ppa/ubuntu focal/main Translation-en [2252 B]
    azure-arm: Fetched 29.1 kB in 1s (52.6 kB/s)
    azure-arm: Reading package lists...
    azure-arm: Hit:1 http://azure.archive.ubuntu.com/ubuntu focal InRelease
    azure-arm: Hit:2 http://azure.archive.ubuntu.com/ubuntu focal-updates InRelease
    azure-arm: Hit:3 http://azure.archive.ubuntu.com/ubuntu focal-backports InRelease
    azure-arm: Hit:4 http://azure.archive.ubuntu.com/ubuntu focal-security InRelease
    azure-arm: Hit:5 http://ppa.launchpad.net/git-core/ppa/ubuntu focal InRelease
    azure-arm: Hit:6 https://packages.microsoft.com/ubuntu/20.04/prod focal InRelease
    azure-arm: Reading package lists...
    azure-arm: Reading package lists...
    azure-arm: Building dependency tree...
    azure-arm: Reading state information...
    azure-arm: The following additional packages will be installed:
    azure-arm:   git-man
    azure-arm: Suggested packages:
    azure-arm:   git-daemon-run | git-daemon-sysvinit git-doc git-email git-gui gitk gitweb
    azure-arm:   git-cvs git-mediawiki git-svn
    azure-arm: The following packages will be upgraded:
    azure-arm:   git git-man
    azure-arm: 2 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
    azure-arm: Need to get 7788 kB of archives.
    azure-arm: After this operation, 2729 kB of additional disk space will be used.
....

### Actual behavior

==> azure-arm: Provisioning with shell script: /agent/_work/4/s/virtual-environments/images/linux/scripts/installers/git.sh
    azure-arm: Cannot add PPA: 'ppa:~git-core/ubuntu/ppa'.
    azure-arm: ERROR: '~git-core' user or team does not exist.
==> azure-arm: Provisioning step had errors: Running the cleanup provisioner, if present...
==> azure-arm: 
==> azure-arm: Deleting individual resources ...

### Repro steps

Packer build using https://github.com/actions/virtual-environments/blob/main/images/linux/ubuntu2004.json

**Comment by mikhailkoliada** [comment]
@Siebrandf hello!

We do not observe any problems, say, in todays builds (neither in earlier)m what are your modifications to the install scripts?

**Comment by al-cheb** [comment]
> The build-image.ps1 is slightly deviated from the original, but this worked fine until yesterday (attached).
> 
> Is there a way to prevent packer to do the immediate cleanup after failure? [build-image.ps1.txt](https://github.com/actions/virtual-environments/files/8671220/build-image.ps1.txt)

Add `-on-error=ask` param:

[ask](https://www.packer.io/docs/commands/build#ask) presents a prompt and waits for you to decide to clean up, abort, or retry the failed step.

`packer build -on-error=ask`

**Comment by al-cheb** [comment]
Nightly builds were green - https://github.visualstudio.com/virtual-environments/_build?definitionId=71&_a=summary

![image](https://user-images.githubusercontent.com/47745270/168051831-8be072e1-8510-488b-bc69-25ebabc5fad2.png)


Looks like you have an issue with corporate network(e.g. proxy)
