### ISSUE TITLE
Add Musl

### ISSUE THREAD

**Issue by slinkydeveloper** [actions/virtual-environments#552]
**Tool information**
- Tool name: Musl libc
- Add or update? Add
- Desired version: Latest version from debian package manager
- Approximate size: 300/400 kb
- If this is an add request:
  - Brief description of tool: Musl is a small libc implementation, used to be statically linked. Different languages/build tools relies on it to create fully statically linked executables, including [Rust](https://doc.rust-lang.org/edition-guide/rust-2018/platform-and-target-support/musl-support-for-fully-static-binaries.html)
  - URL for tool's homepage: https://www.musl-libc.org/manual.html

**Area for Triage**:

**Question, Bug, or Feature?**:
Feature

**Virtual environments affected**
- [ ] macOS 10.15
- [x] Ubuntu 16.04 LTS
- [x] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Can this tool be installed during the build?**
Yes, using `apt-get install -y musl`

**Are you willing to submit a PR?**
Yes, point me where i must do the changes :smile:

**Comment by maxim-lobanov** [comment]
Tool can be installed in runtime using the following command
```
sudo apt-get install -y musl
```
Installation takes 6 seconds

**Comment by slinkydeveloper** [comment]
Thank you for the hint, however i think it would be nice to have it installed by default. Note this package is also really tiny.

**Comment by thejoebourneidentity** [comment]
Thanks for your suggestion, @slinkydeveloper. Considering how easy it is to install during your run, this is not something we will add to the image at this time.
