### ISSUE TITLE
Update/Add amazon-ecr-credential-helper

### ISSUE THREAD

**Issue by dimitriosstander** [actions/virtual-environments#5521]
### Tool name

amazon-ecr-credential-helper

### Tool license

Apache 2.0

### Add or update?

- [X] Add
- [ ] Update

### Desired version

latest

### Brief description of tool

The Amazon ECR Docker Credential Helper is a [credential helper](https://github.com/docker/docker-credential-helpers) for the Docker daemon that makes it easier to use [Amazon Elastic Container Registry](https://aws.amazon.com/ecr/).

### URL for tool's homepage

https://github.com/awslabs/amazon-ecr-credential-helper

### Virtual environments affected

- [X] Ubuntu 18.04
- [X] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Can this tool be installed during the build?

```bash
sudo apt install amazon-ecr-credential-helper
```

**Comment by igorboskovic3** [comment]
Hi @dimitriosstander, thank you for you request.
We will decide on adding the tool to the images and let you know.

**Comment by dimitriosstander** [comment]
@miketimofeev if it is not present in the image we are unable to use github hosted runners with jobs the run in inside ecr pulled containers. We need to use self hosted runners where the package is present.

**Comment by miketimofeev** [comment]
@dimitriosstander oh, sorry, didn't know that. Then it makes sense to preinstall the helper.

**Comment by al-cheb** [comment]
@dimitriosstander , The new images have been deployed.

![image](https://user-images.githubusercontent.com/47745270/171604781-e0ec3fe1-050b-4ec9-bd11-94534f8c61d1.png)
