### ISSUE TITLE
This check was cancelled

### ISSUE THREAD

**Issue by Yurunsoft** [actions/virtual-environments#5532]
### Description

I have a job in this repository that is 100% auto-canceled.

Why?

<https://github.com/Yurunsoft/php-tdengine/runs/6207501347?check_suite_focus=true>
<https://github.com/Yurunsoft/php-tdengine/runs/6417818105?check_suite_focus=true>

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Windows Server 2016

### Is it regression?

https://github.com/Yurunsoft/php-tdengine/runs/5766444154?check_suite_focus=true

### Repro steps

I don't know

**Comment by igorboskovic3** [comment]
Hi @Yurunsoft , thank you reporting this issue, we will take a look.

**Comment by miketimofeev** [comment]
@Yurunsoft your matrix contains the follwing image, which is deprecated and not available in GH actions anymore, you should remove this step:
```
      matrix:
        php:
          - version: 7.4
            runs-on: windows-2016
            vs: 2017
```
I'm going to close the issue, please feel free to contact us if you have any concerns.
Thank you!

**Comment by Yurunsoft** [comment]
I have code that needs to be compiled with vs2017. How to use vs2017 in Windows 2019 and 2022?
