### ISSUE TITLE
Microsoft.VisualStudio.Component.VC.MFC.ARM64.Spectre and Microsoft.VisualStudio.Component.VC.MFC.ARM.Spectre missing from MMS2022 image

### ISSUE THREAD

**Issue by chorkin** [actions/virtual-environments#5535]
### Description

I'm unable to build using v143 with MFC libraries with Spectre for ARM or ARM64.  Build keeps complaining I need to install MFC libraries with Spectre for ARM/ARM64.  I do not see these listed on the supported list of components either.

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

SKU: Standard_D8ds_v4
Image: MMS2022Compliant
Image Version: 16.0.0 

The build is internal to MSFT within Mixed Reality, link would be inaccessible.

### Expected behavior

I can build using VS2022 using MFC libraries with Spectre for ARM and ARM64

### Actual behavior

I cannot build using VS2022 using MFC libraries with Spectre for ARM and ARM64.  Build fails.

### Repro steps

1. Create a project for v143 that uses MFC libraries + Spectre for ARM/ARM64
2. Build using the image.

**Comment by miketimofeev** [comment]
Hi @chorkin!
Sure, we will add these components.

**Comment by chorkin** [comment]
I see this has been merged.  @miketimofeev , how often do the images get released?

**Comment by miketimofeev** [comment]
@chorkin weekly, the new deployment will start on Monday or Tuesday and will take 3-4 days

**Comment by chorkin** [comment]
Hey @miketimofeev, I saw that there was a new image released so I tried it out.  The result is unexpected.  My ARM64 build now passes (great), but my ARM build is still failing.  I looked at the commit, it would seem both of these should be supported.  Is there some way that the ARM part might not have made it into the image?  I'm confused how half of this would work and not the other half.

**Comment by miketimofeev** [comment]
@chorkin I'm afraid I don't know. Maybe some other components needed?

**Comment by chorkin** [comment]
I root caused.  I think it's this: Microsoft.VisualStudio.Component.VC.Runtimes.ARM.Spectre

Can you add it?

Thanks.

**Comment by miketimofeev** [comment]
@chorkin already added here https://github.com/actions/virtual-environments/pull/5559
The new image will be deployed this week. Please track this issue https://github.com/actions/virtual-environments/issues/5554
I'm going to close this one but feel free to contact us if you have any concerns.
Thank you!

**Comment by miketimofeev** [comment]
@chorkin the image is deployed.

**Comment by chorkin** [comment]
@miketimofeev , thank you!  Yes.  This is working for me now.  Thank you!
