### ISSUE TITLE
Restart script exited with non-zero exit status: 16001

### ISSUE THREAD

**Issue by KexyBiscuit** [actions/virtual-environments#5537]
### Description

Generating disk image for Windows 2022 failed due to the following error.

```
==> vhd: Restarting Machine
==> vhd: Restart script exited with non-zero exit status: 16001
==> vhd: Step "StepProvision" failed
```

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

16fb116cf0032eec57907dd164cf797e9d23aaac

### Repro steps

`GenerateResourcesAndImage -SubscriptionId [REDACTED] -ResourceGroupName "rg-virtenv-shared-001" -ImageGenerationRepositoryRoot "$pwd" -ImageType Windows2022 -AzureLocation "West US 2"`

**Comment by al-cheb** [comment]
@KexyBiscuit, You should ask this question in packer  - https://github.com/hashicorp/packer
