### ISSUE TITLE
Update bicep to latest version to address regressions in v0.6.1

### ISSUE THREAD

**Issue by pb111111** [actions/virtual-environments#5538]
### Tool name

Azure Bicep CLI

### Tool license

MIT License

### Add or update?

- [ ] Add
- [X] Update

### Desired version

v0.6.18+

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

**Comment by pb111111** [comment]
The current image uses version 0.6.1 which has two major regressions and caused a lot of problems for our builds. These issues have now been corrected in version v0.6.18

**Comment by al-cheb** [comment]
Hey @pb111111,
We are planning to start a new image rollout with update bicep v0.6.18 version on board.

**Comment by al-cheb** [comment]
The new Ubuntu images have been deployed with bicep v0.6.18 version on board.
