### ISSUE TITLE
"Shock and awe" is not the way to migrate a repo.

### ISSUE THREAD

**Issue by StingyJack** [actions/virtual-environments#554]
There is a note on the old repo from 8 days ago saying it moved here. That's not enough and MSFT should know better.

None of the open issues were migrated.

Nobody who had an open issue got a note with this info or a request to move the issue. I got a threat from the always offensive stalebot, which doesn't count. Actually migrating was your choice so you should be doing the move of issues anyway and not creating work for everyone else due to your choice

New issues can be reported still, which is terribly misleading.

There are PRs still outstanding.

If you are going to close the repo, finish the job in a responsible and ethical way.

**Comment by alepauly** [comment]
Thanks for the feedback @StingyJack, we are always working to improve.

**Comment by StingyJack** [comment]
@alepauly I tagged at least one issue to bring over, and one request for you too take a look at
