### ISSUE TITLE
python 3.11 is not aliased

### ISSUE THREAD

**Issue by ssbarnea** [actions/virtual-environments#5540]
### Description

That is the same problem we had with 3.10, where there is no alias for future release of python and only pre-release specific builds. See https://github.com/actions/virtual-environments/issues/3343

Once the first pre-release version of a new version is added, we already need to add generic alias.

Many developers will want to add pipelines that test with unreleased versions of python, pipelines that would not need to be updated whenever a new pre-release is made or when the release happens. 

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

n/a

### Actual behavior

Always have a generic alias working

### Repro steps

Try to configure python version to "3.11", it will not work, even if there are versions of 3.11 available.

**Comment by nulano** [comment]
Have you tried `3.11-dev`?

**Comment by ssbarnea** [comment]
I am sure that `3.11-dev` works, but the bug is about not having a `3.11` alias from start. We really need a `3.11` alias as the moment someone adds a pipeline to verify compatibility with python 3.11 should not be dependent on the effective release of python 3.11, or a post-release of it.

It is not reasonable to force each repository owner to update all pipelines at least twice: once for 3.11-dev before the release and another time to replace it with 3.11 after. Having a `3.11` alias would avoid a LOT of work. Most of the time we do not care if is alpha, beta1, beta2, rc2,... 3.11 GM, 3.11.1 or 3.11.999, we just want latest 3.11 is available today, and that is what the aliases are for.

Some issue happened with previous releases, where we did not had an alias for them.

**Comment by nulano** [comment]
You might want to clarify your original message then. The author of #3343 was asking for *any* way to specify 3.10, including a `-dev` specifier. Also, while I haven't tested it myself, I would expect `3.11-dev` to also work after it is released. It isn't just specifying pre-release versions, but instead the latest version including pre-releases.

**Comment by mikhailkoliada** [comment]
Hi @ssbarnea 

virtual environments has nothing to do with this, we only pre-install existing python versions from the `actions/python-versions` repo which are in turn managed by the `actions/setup-python` action. Please consider addressing your concerns there.

**Comment by ssbarnea** [comment]
As python-versions has the issue tracker disabled I did not know where to file the bug. It seems that this is linked to https://github.com/actions/setup-python/issues/108 which was closed. Hopefully it will be revised.
