### ISSUE TITLE
Add Visual Studio for Mac 2022 to your macOS-11 and macOS-12 VMs

### ISSUE THREAD

**Issue by CartBlanche** [actions/virtual-environments#5542]
### Tool name

Visual Studio 2022 for Mac

### Tool license

MS-PL (I think) It's a Microsoft product so unsure.

### Add or update?

- [X] Add
- [ ] Update

### Desired version

17.0.x.x

### Brief description of tool

Currently you have Visual Studio 8.x installed on your instances. VS 17 aka 2022 is the new version of the aforementioned IDE and is currently a release candidate and can be installed side by side with the 8.x version.

### URL for tool's homepage

https://devblogs.microsoft.com/visualstudio/visual-studio-2022-for-mac-release-candidate/

### Provide a basic test case to validate the tool's functionality.

```bash
We are trying to build a VS4Mac 2022 extension on Github. You can see that using macos-latest as and instance fails here

https://github.com/WildernessLabs/VS_Mac_Meadow_Extension/runs/6434371632?check_suite_focus=true

with missing assembly references, being the issue. Having VS4Mac 2022 installed on the instance, should fix this issue.
```

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 10.15
- [X] macOS 11
- [X] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Can this tool be installed during the build?

```bash
Only if DMGs are allowed. Are they?
```

### Are you willing to submit a PR?

Yes, I'd love to! Just tell me what is required.

**Comment by miketimofeev** [comment]
Hi @CartBlanche!
We will take a look if it is possible to install VS2022 along with the current VS release on macOS-12. Usually, we do not install beta\RC versions but it looks like it makes sense to prepare the image with the new version in advance.

**Comment by CartBlanche** [comment]
@miketimofeev Thanks for letting me know. Looking forward to it being on there.

**Comment by CartBlanche** [comment]
I've updated the tool link above to the latest RC (April 2022)

**Comment by fcaminada** [comment]
Hi @al-cheb, I noticed that you have merged a PR #5561 including the VS 2022 preview on the macOS-12 toolset. Do you know when that will be available to use? Thanks!

**Comment by al-cheb** [comment]
Hi @fcaminada, we are planning to deploy these changes by next Thursday.

**Comment by fcaminada** [comment]
Thank you! Do we need to do any configuration to be able to use this preview version or will it be already available when using the macos-12 agent?

**Comment by CartBlanche** [comment]
@al-cheb Great news! Thanks!

**Comment by miketimofeev** [comment]
@fcaminada it will be available for all macOS-12 users by the path `/Applications/Visual Studio Preview.app`

**Comment by CartBlanche** [comment]
@miketimofeev As VS2022 for Mac is now officially released as GA/Stable, the path should just be `/Applications/Visual Studio.app` . Just remember that in your CI for VS2022 projects you need to use `dotnet msbuild...` for it to use .NET 6. If you just use `msbuild...` it will use mono. 
eg our Github Action run command is 
`dotnet msbuild Path/ToCSProjOrSln/MyProject.csproj /t:Build /p:Configuration=Release` and it should pick up the right version installed (one the instance has been updated) on the CI, without needing to specifically use a path to it.

**Comment by miketimofeev** [comment]
@CartBlanche thanks! We will provide an image with the GA version next week, here is the announcement https://github.com/actions/virtual-environments/issues/5601

**Comment by CartBlanche** [comment]
@miketimofeev I thought I was replying to another Github customer not an GitHub employee. Sorry about that😀

**Comment by al-cheb** [comment]
The new image with VS 2022 on board has been deployed - https://github.com/actions/virtual-environments/blob/main/images/macos/macos-12-Readme.md#visual-studio-for-mac

**Comment by CartBlanche** [comment]
@al-cheb @miketimofeev Seem you fixed the macOS-12 image, but now the macOS-11 image is broken. 

/Users/runner/.nuget/packages/monodevelop.addins/0.4.7/build/MonoDevelop.Addins.targets(76,5): error : Could not find a global instance of Visual Studio for Mac or MonoDevelop. Try providing an explicit value with MDBinDir. [/Users/runner/work/VS_Mac_Meadow_Extension/VS_Mac_Meadow_Extension/main/VS4Mac_Meadow_Extension/Meadow.Sdks.IdeExtensions.Vs4Mac.csproj]

Did someone remove VS2019 from the macOS image? Should I raise another issue?
