### ISSUE TITLE
Job run longer time more than 6 hours.

### ISSUE THREAD

**Issue by Exnadella** [actions/virtual-environments#5549]
### Description

The pull requests created by Snyk have executed our Github Actions for longer than 6 hours.  On observation by the GitHub Support team version of the OS was updated when compared with the successful run.

### Virtual environments affected

- [ ] Ubuntu 18.04
- [X] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

https://github.com/ExcentITSolutionspvtltd/URCASH-UK/runs/6315501397
Version: 20220503.1 (Jobs terminated after 6 hours).

https://github.com/ExcentITSolutionspvtltd/URCASH-UK/runs/6302429498
Version: 20220425.1 (Executed without any issues)

### Is it regression?

https://github.com/ExcentITSolutionspvtltd/URCASH-UK/runs/6302429498

### Expected behavior

The Actions job should run without any issue.

### Actual behavior

The operations are canceled due to long-running hours.

### Repro steps

When we run the existing Pull requests the issue is repeated once again.

The repository is a private repository.

**Comment by mikhailkoliada** [comment]
Hi @Exnadella!

We ca not access your ci logs as links you have provided belong a private repository.

**Comment by Exnadella** [comment]
Hello Mikhail,

Please find the attached logs with the issue in the .zip file and without issue in the .txt file. 
[Log_Without_Issue.txt](https:/
[logs_716.zip](https://github.com/actions/virtual-environments/files/8701270/logs_716.zip)
/github.com/actions/virtual-environments/files/8701243/Log_Without_Issue.txt)

Thanks,
Ranganath.

**Comment by Exnadella** [comment]
Hello Mikhail,

Please find the .zip file for the logs for the job that ran without issues.
[logs_715.zip](https://github.com/actions/virtual-environments/files/8701291/logs_715.zip)

**Comment by miketimofeev** [comment]
@Exnadella we are not sure this issue is introduced by the changes in the image as nothing critical was changed between those image versions
https://github.com/actions/virtual-environments/commit/ad831b8f26dfdbedce8a9a8e4ca9ab86499e5936
I found a new sensor that is presented in the logs with the issue. Could you try to run the same workflow and codebase on the newer image?
```
2022-05-06T00:09:56.6127549Z [INFO] Sensor javabugs [dbd]
2022-05-06T00:09:56.6130976Z [INFO] Reading IR files from: /home/runner/work/URCASH-UK/URCASH-UK/target/sonar/ir/java
2022-05-06T00:09:56.6428831Z [INFO] Analyzing 646 functions to detect bugs.
```

**Comment by Exnadella** [comment]
Hello Mike,

Thanks for the update, we have found that the issue is faced by several others in the Sonar Community.  There is a posting on the Sonar Community about the same issue and a probable fix.  Please find the screenshot for the same.

I have changed the .yml file and executed the job and it ran successfully, but issued several warnings.

![image](https://user-images.githubusercontent.com/22579094/168649244-77f440d3-e01f-487e-a1b6-7b77fc16d0ea.png)

**Comment by miketimofeev** [comment]
Thanks for the confirmation.
I'm going to close the issue as an external one. Please feel free to contact us if you need any help.
Thank you!
