### ISSUE TITLE
libcurl4-openssl-dev missing om mac

### ISSUE THREAD

**Issue by TonGarcia** [actions/virtual-environments#5553]
### Description

I'm trying to compile kafka on M1, but it is missing libcurl4-openssl-dev

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [X] macOS 10.15
- [X] macOS 11
- [X] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Using master

### Repro steps

git clone https://github.com/edenhill/librdkafka

./configure --install-deps --source-deps-only
make
sudo make install

**Comment by al-cheb** [comment]
Hey @TonGarcia,
We don't have M1 in our environment.
