### ISSUE TITLE
Microsoft.VisualStudio.Component.VC.Runtimes.ARM.Spectre missing from MMS2022 image

### ISSUE THREAD

**Issue by craigktreasure** [actions/virtual-environments#5554]
### Description

When building an application targeting the v143 platform toolset requiring Spectre mitigated libraries, we encounter build issues for our ARM flavor due to Microsoft.VisualStudio.Component.VC.Runtimes.ARM.Spectre missing from the installation.

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

Internal build pipeline.

Virtual Environment:
> Environment: windows-2022
> Version: 20220511.2

1ES Hosted Pool:
> SKU: Standard_D8ds_v4
> Image: MMS2022TLS
> Image Version: 29.0.0

### Expected behavior

I can build an application for ARM using the v143 platform toolset using the Spectre Mitigated libraries.

### Actual behavior

Error MSB8040: Spectre-mitigated libraries are required for this project. Install them from the Visual Studio installer (Individual components tab) for any toolsets and architectures being used. Learn more: https://aka.ms/Ofhn4c

### Repro steps

1. Create a native project with the following properties:
    ```xml
    <SpectreMitigation>Spectre</SpectreMitigation>
    <PlatformToolset>v143</PlatformToolset>
    ```
2. Build it for ARM using the current Windows Server 2022 image.

**Comment by al-cheb** [comment]
Hey @craigktreasure,
We will add this component.

**Comment by craigktreasure** [comment]
Thanks!

**Comment by al-cheb** [comment]
The new image has been deployed.
