### ISSUE TITLE
[macOS] cmake cannot find OpenMP

### ISSUE THREAD

**Issue by vkedwardli** [actions/virtual-environments#5555]
### Description

When trying to `brew install libomp`, OpenMP is already built-in
https://github.com/flyinghead/flycast/runs/6452216091?check_suite_focus=true#step:2:993
```
Warning: libomp 14.0.0 is already installed and up-to-date.
To reinstall 14.0.0, run:
  brew reinstall libomp
```

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 10.15
- [X] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Virtual Environment
  Environment: `macos-11`
  Version: `20220508.1`
  Included Software: https://github.com/actions/virtual-environments/blob/macOS-11/20220508.1/images/macos/macos-11-Readme.md
  Image Release: https://github.com/actions/virtual-environments/releases/tag/macOS-11%2F20220508.1

### Is it regression?

not sure

### Expected behavior

On my Mac, with libomp installed by homebrew and AppleClang, cmake is returning:
```
-- Found OpenMP_C: -Xclang -fopenmp (found version "4.5") 
-- Found OpenMP_CXX: -Xclang -fopenmp (found version "4.5") 
-- Found OpenMP: TRUE (found version "4.5")  
```

### Actual behavior

But virtual environment's cmake cannot find the library
https://github.com/flyinghead/flycast/runs/6452216091?check_suite_focus=true#step:9:21
```
-- Could NOT find OpenMP_C (missing: OpenMP_C_FLAGS OpenMP_C_LIB_NAMES) 
-- Could NOT find OpenMP_CXX (missing: OpenMP_CXX_FLAGS OpenMP_CXX_LIB_NAMES) 
-- Could NOT find OpenMP (missing: OpenMP_C_FOUND OpenMP_CXX_FOUND) 
```

### Repro steps

`find_package(OpenMP)`

**Comment by mikhailkoliada** [comment]
@vkedwardli Hi!

I personally have not checked what are clang-supported features on the images (yet), but what happens if you specify openmp variables in the CMakeLists.txt manually?

**Comment by vkedwardli** [comment]
@mikhailkoliada Hi!

yes, it can compile with OpenMP on x86_64 build [successfully](https://github.com/vkedwardli/flycast/runs/6542241371?check_suite_focus=true#step:9:12895) if I provide the below variables:

```
 	set(OpenMP_C "${CMAKE_C_COMPILER}")
 	set(OpenMP_C_FLAGS "-Xclang -fopenmp -I/usr/local/Cellar/libomp/14.0.0/include")
 	set(OpenMP_C_LIB_NAMES "libomp")
 	set(OpenMP_libomp_LIBRARY "omp")

 	set(OpenMP_CXX "${CMAKE_CXX_COMPILER}")
 	set(OpenMP_CXX_FLAGS "-Xclang -fopenmp -I/usr/local/Cellar/libomp/14.0.0/include")
 	set(OpenMP_CXX_LIB_NAMES "libomp")
 	set(OpenMP_libomp_LIBRARY "omp")

 	link_directories("/usr/local/Cellar/libomp/14.0.0/lib/")
 	target_link_directories(${PROJECT_NAME} PRIVATE "/usr/local/Cellar/libomp/14.0.0/lib/")
```

 (Unfortunately the homebrew provided binary isn't universal, so it cannot link on the arm64 build successfully)

**Comment by vkedwardli** [comment]
After providing a universal binary OpenMP, cmake can locate it now (https://github.com/flyinghead/flycast/pull/645/commits/d26d6a745c5ef319e5f4da16f0970d7541cd7294)

The problem is if cmake can only link with the x86_64 OpenMP but not the arm64 OpenMP, it would report `Could NOT find OpenMP_C`

So this issue won't exists if:
- cmake can report which architecture cannot be linked
- homebrew provides universal binary
- GitHub virtual env provides universal binary

Please close the issue if you think it is not related to virtual env
