### ISSUE TITLE
Could not load file or assembly Microsoft.VisualStudio.TestPlatform.Extensions.VSTestIntegration

### ISSUE THREAD

**Issue by alazarev-msft** [actions/virtual-environments#5556]
### Description

Hi, we started getting the following error a week ago when running integration tests on our 1ES hosted pool, both VS2019 and VS2022 boxes. There was no change from our side.
 
MMS2019TLS:

2022-05-09T15:11:33.3811285Z ##[warning]DiscoveryMessage : Could not load file or assembly 'Microsoft.VisualStudio.TestPlatform.Extensions.VSTestIntegration, Version=16.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. Exception from HRESULT: 0x80131902

MMS2022TLS:

2022-05-12T04:49:56.3002434Z ##[warning]DiscoveryMessage : Could not load file or assembly 'Microsoft.VisualStudio.TestPlatform.Extensions.VSTestIntegration, Version=17.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. Exception from HRESULT: 0x80131902

These DLLs are supposed to be a part of the VS installation.

We are using MMS2019TLS and MMS2022TLS images. It worked fine before about a week ago, we are wondering if there was any breaking change recently.

Thanks.

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [X] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

Environment: windows-2019
Version: 20220503.1

Environment: windows-2022
Version: 20220509.1

### Is it regression?

yes

### Expected behavior

VSTEST should run the tests

### Actual behavior

Tests fail to run with an error

### Repro steps

Create a Visual Studio test task in Azure DevOps with the following YAML:

steps:
- task: VSTest@2
  displayName: 'Test Assemblies $(System.DefaultWorkingDirectory)/_CMS.Service.Command.IntegrationTests/drop/Microsoft.OnlinePublishing.Integration.Command.IntegrationTests.dll'
  inputs:
    testAssemblyVer2: '$(System.DefaultWorkingDirectory)/_CMS.Service.Command.IntegrationTests/drop/Microsoft.OnlinePublishing.Integration.Command.IntegrationTests.dll'
    testFiltercriteria: '(TestCategory=EnvironmentAll | TestCategory=EnvironmentIntInternal) & TestCategory!=Nightly'
    runSettingsFile: '$(System.DefaultWorkingDirectory)/_CMS.Service.Command.IntegrationTests/drop/Main.runsettings'
    runInParallel: true
    rerunFailedTests: true
    rerunFailedThreshold: 20
    rerunMaxAttempts: 5

**Comment by mikhailkoliada** [comment]
@alazarev-msft hi!

Could you provide a minimak repo with a minimal code to reproduce the issue?

**Comment by miketimofeev** [comment]
@alazarev-msft does this happen on hosted images as well? Visual Studio 2019 & 2022 received an update last Tuesday, that can be the reason

**Comment by vsafonkin** [comment]
Hi @alazarev-msft, is this issue still actual for you?

**Comment by al-cheb** [comment]
I am planning to close the thread. Feel free to open it if you have any concerns.
