### ISSUE TITLE
Demanding java makes windows-latest use windows-2019

### ISSUE THREAD

**Issue by quasarea** [actions/virtual-environments#5560]
### Description

I dont understand how it is happening by one of my jobs has:
``` 
jobs:
  - job:
    pool:
      vmImage: windows-latest
      demands:
        - java
...
```
and when run it picks
```
Pool: [Hosted Windows 2019 with VS2019](...)
Agent: Hosted Agent
```
once `demands` were removed it picks 
```
Pool: [Azure Pipelines](...)
Image: windows-latest
Agent: Azure Pipelines 16
```

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [X] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

latest

### Expected behavior

To use windows-latest, not sure why I had this demand defined there but it should not introduce such a downgrade in my opinion. Unless windows-latest is mixture of 2019 and 2022 and those have different capabilities defined

### Repro steps

Run a job on windows-latest with dependency on java defined

**Comment by al-cheb** [comment]
Hey @quasarea,
You should not use [demands ](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/demands?view=azure-devops&tabs=yaml) with hosted-agents:

> Demands and capabilities are designed for use with self-hosted agents so that jobs can be matched with an agent that meets the requirements of the job. When using Microsoft-hosted agents, you select an image for the agent that matches the requirements of the job, so although it is possible to add capabilities to a Microsoft-hosted agent, you don't need to use capabilities with Microsoft-hosted agents.

**Comment by quasarea** [comment]
Thanks, it was leftover, but still the behavior is odd. Would not expect 2019 resurface on windows-latest

**Comment by miketimofeev** [comment]
@quasarea please contact azure devops support as it looks like a bug in the service
