### ISSUE TITLE
Cannot access home directory from Python on MacOS

### ISSUE THREAD

**Issue by rayzchen** [actions/virtual-environments#5564]
### Description

I'm trying to use `pathlib.Path.home()` to get the home directory, but printing it seems to indicate its an empty string. Using `Path.home() / "Library"` gives `/Library` so I'm not sure what is going wrong. I don't want to use `$HOME` because apparently it's not set for GUI scripts. `os.path.expanduser("~")` is meant to work for any platform yet it is also just an empty string.

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [X] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Environment: macos-11
  Version: 20220508.1
  Included Software: https://github.com/actions/virtual-environments/blob/macOS-11/20220508.1/images/macos/macos-11-Readme.md
  Image Release: https://github.com/actions/virtual-environments/releases/tag/macOS-11%2F20220508.1

### Expected behavior

Return `"/Users/runner"`

### Actual behavior

Returns ""

### Repro steps

Run `python -c "import os; print(os.path.expanduser("~"))"`
Run `python -c "import pathlib; print(pathlib.Path.home())"`

**Comment by mikhailkoliada** [comment]
Hi! Your syntax is incorrect.

<img width="515" alt="image" src="https://user-images.githubusercontent.com/88318005/168886156-cf434715-da78-4c0a-b14f-e65a1d19b2fb.png">

**Comment by rayzchen** [comment]
Wasn't this problem, but seems that stdout was getting redirected and I had an extra slash that made it lose the first half of the path. Thanks for the reply though!
