### ISSUE TITLE
macOS-12 image - appcenter cli doesn't work.

### ISSUE THREAD

**Issue by neoswallow** [actions/virtual-environments#5569]
### Description

I used this image on Azure Pipelines and when I use `appcenter` at CmdLine@2 task, the task throws `Bash exited with code '127'` which is command not found.

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [X] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Virtual Environment
Environment: macos-12
Version: 20220516.1

### Is it regression?

no

### Expected behavior

`appcenter` cli runs (macOS-11 image [version 20220508.1] runs the same task without any issue)

### Actual behavior

CmdLine@2 task throws `Bash exited with code '127'` error.

### Repro steps

Azure Pipeline task used
```yaml
      - task: CmdLine@2
        displayName: "Create a release to an App Center Group via App Center cli"
        condition: succeeded()
        inputs:
          script: >
            appcenter distribute release
            --app $(appCenterAppName)
            --group "$(appCenterGroupName)"
            --token $(appCenterToken)
            --file "$(appFileName)"
            --release-notes '$(releaseNote)'
            --quiet
            --disable-telemetry
          workingDirectory: '$(System.DefaultWorkingDirectory)'
```

**Comment by mikhailkoliada** [comment]
@neoswallow Thanks!

We will take a look.

**Comment by al-cheb** [comment]
The new image has been deployed with appcenter on board.

**Comment by neoswallow** [comment]
I can confirm that appcenter cli now works on macOS-12 👍🏼
