### ISSUE TITLE
Ubuntu 20.04 Unable to fetch Podman

### ISSUE THREAD

**Issue by ramesp71** [actions/virtual-environments#5574]
### Description

I get the following error when I run GenerateResourcesAndImage, and cannot continue.   `==> azure-arm: E: Failed to fetch https://provo-mirror.opensuse.org/repositories /devel:/kubic:/libcontainers:/stable/xUbuntu_20.04/amd64/podman_3.4.2-1_amd64.de b File has unexpected size (17679080 != 17706544). Mirror sync in progress? [IP : 91.193.113.70 443]
==> azure-arm: Hashes of expected file:
==> azure-arm: - SHA256:4eb9b58413f602cf18ec21a742acd99ae10e71df467e7b9a63c3 b1f7e8229f16
==> azure-arm: - SHA1:cf1fefe5c85321fe9b562339a79494c9eda9dd60 [weak]
==> azure-arm: - MD5Sum:58fa232055dff2700aa55e13c7932536 [weak]
==> azure-arm: - Filesize:17706544 [weak]
==> azure-arm: E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?`

### Virtual environments affected

- [ ] Ubuntu 18.04
- [X] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

GenerateResourcesAndImage -SubscriptionId [subscriptionId] -ResourceGroupName [resourcegroup] -ImageGenerationRepositoryRoot "$pwd" -ImageType Ubuntu2004 -AzureLocation "Central US" -AzureClientId '[azureclientId]' -AzureClientSecret '[azureclientSecret]' -AzureTenantId '[azureTenantId]'

### Repro steps

- Run GenerateResourcesAndImage in Ubuntu 20.04.
- Error happens when it gets to the point where it's trying to fetch podman.

**Comment by mikhailkoliada** [comment]
Hey @ramesp71!

I guess it is connected with https://github.com/containers/podman/issues/14278#issuecomment-1131743956

We will consider what to do next soon-ish.

**Comment by miketimofeev** [comment]
@ramesp71 we have removed container tools installation from Ubuntu 18 & 20 images. Please pull the latest main and try building the image again.
Thank you!
