### ISSUE TITLE
GH Actions build succeeded despite failed tests

### ISSUE THREAD

**Issue by mazgajmaciek** [actions/virtual-environments#5576]
### Description

We have GH Actions pipeline that executes test suite depending on whether it recognizes a change in the latest commit sha on master branch - it consists of two jobs:
1st job - it retrieves commit sha cache from previous run and compares it with the newest run and if it has changed, it allows to run 2nd job
2nd job - executes test suite based on result of 1st job.

This setup is working fine but we've had a single instance where 2nd job would be marked as success despite the fact there were failing tests during that 2nd job. Also the step within 2nd job during which test execution happens is not marked in red as it would normally be.

This single particular build, compared to others that were working fine, has substantially bigger log file (because of warnings being thrown during compilation that are not related to tests themselves) - about 25mb in total - file in .zip named `5_Run UI Tests and publish jUnit report` - could it potentially be a reason for erroneous build indication? I guess this also poses a question - based on what exactly GH Actions decides to mark a build green or red? Could it be that something got missed in the logfile? This again is just my educated guess, nothing more.

Build logs attached below
[logs_1944.zip](https://github.com/actions/virtual-environments/files/8732602/logs_1944.zip)

GH Actions .yaml file itself
[UI Tests (Full Regression Suite).txt](https://github.com/actions/virtual-environments/files/8732634/UI.Tests.Full.Regression.Suite.txt)

<img width="1783" alt="image" src="https://user-images.githubusercontent.com/20247520/169365907-345fd9f1-52f9-4d10-9695-4c9d2384c8bb.png">

### Virtual environments affected

- [ ] Ubuntu 18.04
- [X] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 10.15
- [x] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

https://github.com/baas-devops-reference/android-us-retail-app/actions/runs/2273633421
20220501.1

### Is it regression?

https://github.com/baas-devops-reference/android-us-retail-app/actions/runs/2343030670

### Expected behavior

build step that has a step for running tests should fail since there were failing tests

### Actual behavior

build (and job that runs the tests within the build) was marked as success

### Repro steps

1. Execute a gh workflow pipeline that runs the UI tests (link to example workflow and logs provided)

**Comment by mikhailkoliada** [comment]
Hi @mazgajmaciek 

Please consult https://github.community/

We are only responsible for hosted runners but not for inner actions logic. Feel free to reach us out again if questions left.
