### ISSUE TITLE
Windows 2022: Hostname resolves to inconsistent IP addresses

### ISSUE THREAD

**Issue by sonndinh** [actions/virtual-environments#5577]
### Description

Hello,

We are using Windows 2022 on GitHub Actions as part of our CI for the OpenDDS project (https://github.com/objectcomputing/OpenDDS). An issue we are having with using Windows 2022 is that the hostname can resolve to different IP addresses in a short period of time. So a chosen IP address can be unavailable/invalid while a program is running and cause a network issue. This issue isn't observed on Windows 2019 or other Ubuntu runners, i.e., the IP addresses returned are consistent.

I created a program that prints out the list of IP addresses from each hostname associated with a Windows 2022 GitHub Actions runner (only IPv4s are printed out for now). It attempts to resolve hostnames to IP addresses a number of times with a few seconds in between attempts. The program can be found at: https://github.com/sonndinh/AddressLookup. Example output for the IP addresses is at: https://github.com/sonndinh/AddressLookup/runs/6511928769?check_suite_focus=true, under the "run program" step. For convenience, I am going to summarize the output from that link here.

There are 3 interfaces were found: `127.0.0.1`, `172.29.64.1`, and `10.1.0.193`, which map to the following hostnames, respectively, `MiningMadness.com`, `fv-az365-919`, and `fv-az365-919.qb1wfigipftehopcrrqhmdmnnh.bx.internal.cloudapp.net`. These hostnames are then used to look up their corresponding IP addresses. The first two hostnames seem to work fine - they resolve back to the same IP addresses found above: `MiningMadness.com` resolves to `127.0.0.1`, `fv-az365-919` to `172.29.64.1` and `10.1.0.193`. But `fv-az365-919.qb1wfigipftehopcrrqhmdmnnh.bx.internal.cloudapp.net` resolves to different IP addresses such as `10.1.0.74`, `10.1.0.196`, which are different than any of the IPs found from the interfaces.

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

https://github.com/sonndinh/AddressLookup/runs/6511928769?check_suite_focus=true
20220515.1

### Is it regression?

No, the issue happened the first time we tried Windows 2022.

### Expected behavior

Consistent IP addresses are resolved from the hostnames on Windows 2022.

### Actual behavior

A hostname resolves to different IP addresses in a short period of time (in the order of a few seconds).

### Repro steps

2 ways to reproduce:
1. Fork the repo https://github.com/sonndinh/AddressLookup and push some changes to the master branch to trigger a workflow run.
2. Create a PR to https://github.com/sonndinh/AddressLookup and the PR should have its own workflow run.

**Comment by mikhailkoliada** [comment]
Hi @sonndinh!

Thanks, we will take a look.

**Comment by sonndinh** [comment]
> Hi @sonndinh!
> 
> Thanks, we will take a look.

Hi @mikhailkoliada. Have you had a chance to look at this issue? Thanks.

**Comment by al-cheb** [comment]
@sonndinh, does the issue still reproduce on Windows Server 2022?

**Comment by al-cheb** [comment]
I am going to close the thread. If you have any concerns feel free to reopen it.
