### ISSUE TITLE
[Ubuntu] Container tools (buildah, podman, skopeo) will be removed from Ubuntu 18 & 20 images

### ISSUE THREAD

**Issue by miketimofeev** [actions/virtual-environments#5578]
### Breaking changes

Container tools buildah, podman, and skopeo will be removed from Ubuntu 18 and Ubuntu 20 images.

### Target date

Image deployment will start on May 30 and will take 3-4 days to propagate to all the environments.

### The motivation for the changes

The packages were removed from the  https://download.opensuse.org/repositories/devel:/kubic repository and we are not able to install these packages to Ubuntu 18 & 20 images anymore. More details can be found here https://github.com/containers/podman/issues/14278

### Possible impact

If your build depends on using one of these tools it will be broken.

### Virtual environments affected

- [X] Ubuntu 18.04
- [X] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Mitigation ways

Migrate your workflows to Ubuntu 22 image, which will include all three tools by the target date.

**Comment by lsm5** [comment]
Hello, looks like this issue is still open, so in case you haven't removed container tools yet, we might be ok to close this one. 

I got lots of pushback on the kubic repo deletion because of which I have resurrected the packages. Those should be published soon on the same path. I'd still like to caution everyone that those are unmaintained and could also be prone to issues including security vulnerabilities over time (podman v3.4.2 has 4 CVEs, 3 of them being low sev, 1 moderate sev IIRC).

So, I hope everyone is aware of that fact before using these packages.

Sorry about the hassle to you all.

**Comment by lsm5** [comment]
ubuntu 20.04 should be good to go, there are some hiccups in 18.04 which I'm fixing right now. Will update here.

**Comment by lsm5** [comment]
18.04 should be fixed as well now. Let me know if any pending issues.

**Comment by miketimofeev** [comment]
@lsm5 thanks for the updates. We will close this announcement then and revert the removal.

**Comment by miketimofeev** [comment]
@lsm5 looks like not everything is restored. 
On ubuntu18:
```
install_packages=(podman buildah skopeo)
sudo apt-get -y install ${install_packages[@]}
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 buildah : Depends: crun (>= 100:0.18-3) but it is not going to be installed
 podman : Depends: crun (>= 100:0.19.1-1) but it is not going to be installed
          Recommends: slirp4netns (>= 100:1.1.8-3) but it is not going to be installed
          Recommends: containernetworking-plugins (>= 100:1.0.0-1) but it is not going to be installed
          Recommends: fuse-overlayfs but it is not installable
E: Unable to correct problems, you have held broken packages.
```
on Ubuntu20 it simply does nothing:
```
install_packages=(podman buildah skopeo)
sudo apt-get -y install ${install_packages[@]}
Reading package lists... Done
Building dependency tree       
Reading state information... Done
0 upgraded, 0 newly installed, 0 to remove and 14 not upgraded.
```

**Comment by lsm5** [comment]
@miketimofeev let me fix those.

**Comment by lsm5** [comment]
rootless should be fixed now on 18.04. Let me know if any other pending issues.

**Comment by miketimofeev** [comment]
@lsm5 Unfortunately, the problem with ub18 & ub20 reappeared:
```
    azure-arm: Err:18 https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_18.04  podman 100:3.4.2-4
    azure-arm:   File has unexpected size (18660200 != 18684404). Mirror sync in progress? [IP: 91.193.113.70 443]
    azure-arm:   Hashes of expected file:
    azure-arm:    - SHA256:260ac686758f6ed9160b99642ce278d7b175e3f354b31c7b3076653449e53ca4
    azure-arm:    - SHA1:a46da407925b088b8e2f3ec02a83817ce9003cf0 [weak]
    azure-arm:    - MD5Sum:1e98238abb397cbd3b006906ddd9a433 [weak]
    azure-arm:    - Filesize:18684404 [weak]
    azure-arm: Get:19 https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_18.04  skopeo 100:1.5.0-3 [6319 kB]
    azure-arm: Get:20 https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_18.04  slirp4netns 100:1.1.8-4 [691 kB]
    azure-arm: Get:21 https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_18.04  containernetworking-plugins 100:1.1.1~1 [7006 kB]
    azure-arm: Fetched 26.5 MB in 10s (2605 kB/s)
==> azure-arm: E: Failed to fetch https://provo-mirror.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_18.04/amd64/podman_3.4.2-4_amd64.deb  File has unexpected size (18660200 != 18684404). Mirror sync in progress? [IP: 91.193.113.70 443]
==> azure-arm:    Hashes of expected file:
==> azure-arm:     - SHA256:260ac686758f6ed9160b99642ce278d7b175e3f354b31c7b3076653449e53ca4
==> azure-arm:     - SHA1:a46da407925b088b8e2f3ec02a83817ce9003cf0 [weak]
==> azure-arm:     - MD5Sum:1e98238abb397cbd3b006906ddd9a433 [weak]
==> azure-arm:     - Filesize:18684404 [weak]
==> azure-arm: E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
```
and
```
    azure-arm: Err:22 https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_20.04  podman 100:3.4.2-4
    azure-arm:   File has unexpected size (18676884 != 18659032). Mirror sync in progress? [IP: 91.193.113.70 443]
    azure-arm:   Hashes of expected file:
    azure-arm:    - SHA256:ef68bbab3752d524ec6be1b94f47a645dfc985b1ac497fc8ef7768278f560048
    azure-arm:    - SHA1:abe4b75985be6e70a1768032df4fcfc27f0f0d30 [weak]
    azure-arm:    - MD5Sum:aa95d7eb1bc9ca28edd3ef9b3a37805c [weak]
    azure-arm:    - Filesize:18659032 [weak]
    azure-arm: Get:23 https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_20.04  skopeo 100:1.5.0-3 [6325 kB]
    azure-arm: Get:24 https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_20.04  slirp4netns 100:1.1.8-4 [708 kB]
    azure-arm: Get:25 https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_20.04  containernetworking-plugins 100:1.1.1~1 [7009 kB]
    azure-arm: Fetched 27.1 MB in 9s (2910 kB/s)
==> azure-arm: E: Failed to fetch https://provo-mirror.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_20.04/amd64/podman_3.4.2-4_amd64.deb  File has unexpected size (18676884 != 18659032). Mirror sync in progress? [IP: 91.193.113.70 443]
==> azure-arm:    Hashes of expected file:
==> azure-arm:     - SHA256:ef68bbab3752d524ec6be1b94f47a645dfc985b1ac497fc8ef7768278f560048
==> azure-arm:     - SHA1:abe4b75985be6e70a1768032df4fcfc27f0f0d30 [weak]
==> azure-arm:     - MD5Sum:aa95d7eb1bc9ca28edd3ef9b3a37805c [weak]
==> azure-arm:     - Filesize:18659032 [weak]
==> azure-arm: E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
```

**Comment by lsm5** [comment]
@miketimofeev hope you're not seeing that issue anymore.

Btw, is it possible to do any `trial runs` to check if my new repo with the latest podman, buildah and skopeo for ubuntu 18.04 and 20.04 would be mature enough for github actions? The new repo is at: https://build.opensuse.org/project/show/devel:kubic:libcontainers:unstable

**Comment by miketimofeev** [comment]
@lsm5 sure! Will check both Ubuntu18 and Ubuntu20 using the new repo today

**Comment by lsm5** [comment]
@miketimofeev thanks, I'll try to fix those. Would you prefer I open a separate issue for this, or is it ok to continue here?

**Comment by miketimofeev** [comment]
@lsm5 I'm ok to continue here 😀

**Comment by lsm5** [comment]
@miketimofeev hi, can you give this a try again on Ubuntu 22.04 ? The maintainer filed annoyance should be fixed now and the latest released podman is usable as well.

cc @korijn please give this a try as well if you're on 22.04.

If things work well for github actions, I'll create a separate repo with the packaging sources duplicated under a different repo name than `unstable`.

**Comment by lsm5** [comment]
@miketimofeev ping, can you give this another try please? Only on 22.04 though. Other versions have a long way to go.

**Comment by miketimofeev** [comment]
@lsm5 thanks! We haven't heard any complaints about the outdated version so we'd rather avoid adding a PPA and will use canonical repo.

**Comment by bwoodsend** [comment]
> We haven't heard any complaints about the outdated version so we'd rather avoid adding a PPA and will use canonical repo.

In that case then count me as the first complaint! I've just discovered that the reason why one of my projects falls apart when ran only on Ubuntu and only with podman instead of docker is due to a bug which is in 3.4.4 but as been fixed since.

**Comment by lsm5** [comment]
just curious, can github actions use packages from homebrew? Or do they have to be debs ?
