### ISSUE TITLE
Add pgtap to enable unit testing PostgreSQL databases

### ISSUE THREAD

**Issue by mattdeluco** [actions/virtual-environments#558]
**Tool information**
- Tool name: pgtap
- Add or update? Add
- Desired version: Latest
- Approximate size: ~310kb zip from Github
- If this is an add request:
  - Brief description of tool: "pgTAP is a suite of database functions that make it easy to write TAP-emitting unit tests in psql scripts or xUnit-style test functions."
  - URL for tool's homepage: https://pgtap.org

**Area for Triage**:
Databases
Testing and code coverage

**Virtual environments affected**
- [x] macOS 10.15
- [x] Ubuntu 16.04 LTS
- [x] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Can this tool be installed during the build?**
Unknown

**Are you willing to submit a PR?**
Unsure how to get started, but will look into it.

**Comment by maxim-lobanov** [comment]
Hello, this tool can be installed in runtime using the following commands:
```
# Ubuntu
sudo apt-get install -y pgtap 
# macOS
brew install https://raw.githubusercontent.com/Homebrew/homebrew-core/3c66798c39fdb6a7c8b15630035125cac63c3fa2/Formula/pgtap.rb 
```
Installation takes about ~15 seconds

**Comment by thejoebourneidentity** [comment]
Thanks for your suggestion 🙏. Considering how easy it is to install during your run, this is not something we will add to the image at this time.

**Comment by mattdeluco** [comment]
Thank you, @maxim-lobanov!
