### ISSUE TITLE
Update/Add Terragrunt

### ISSUE THREAD

**Issue by sit-md** [actions/virtual-environments#5582]
### Tool name

Terragrunt

### Tool license

MIT License

### Add or update?

- [X] Add
- [ ] Update

### Desired version

v0.37.1

### Brief description of tool

Terragrunt is a thin wrapper for [Terraform](https://www.terraform.io/) that provides extra tools for keeping your Terraform configurations [DRY](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself), working with multiple Terraform modules, and managing remote state.

### URL for tool's homepage

https://github.com/gruntwork-io/terragrunt

### Provide a basic test case to validate the tool's functionality.

```bash
terragrunt version
```

### Virtual environments affected

- [X] Ubuntu 18.04
- [X] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Can this tool be installed during the build?

```bash
brew install terragrunt
```

### Tool installation time in runtime

1 minute

### Are you willing to submit a PR?

Generally yes

**Comment by miketimofeev** [comment]
Hi @sit-md!
There is an action available in marketplace that allows installing Terragrunt in a second or two https://github.com/marketplace/actions/terragrunt-installer
Please consider using the action as it is a recommended way to install new tools in runtime.
I'm going to close the issue. Feel free to contact us if you have any concerns.
Thank you!

**Comment by sit-md** [comment]
@miketimofeev Is there also a solution for Azure DevOps Agents? This is where I need it.

**Comment by miketimofeev** [comment]
@sit-md I'm afraid no, but you can use this snippet to install the latest version in runtime in just 1 second
```bash
json=$(curl -s "https://api.github.com/repos/gruntwork-io/terragrunt/releases/latest")
downloadUrl=$(echo $json | jq -r ".assets | .[] | select(.name==\"terragrunt_linux_amd64\").browser_download_url")
curl $downloadUrl -4 -sL -o '/usr/local/bin/terragrunt'
chmod +x /usr/local/bin/terragrunt
```

**Comment by sit-md** [comment]
@miketimofeev You Sir, saved me a minute of my lifetime every time I run the pipeline. Thank you very much!
