### ISSUE TITLE
GenerateResourcesAndImage is still expecting a json file for Ubuntu2204

### ISSUE THREAD

**Issue by jeffpuckett** [actions/virtual-environments#5590]
### Description

Pretty straightforward I think. 

GenerateResourcesAndImage -SubscriptionId "*****" -ResourceGroupName "testresource" -ImageGenerationRepositoryRoot "$pwd" -ImageType Ubuntu2204 -AzureLocation "East US"
GenerateResourcesAndImage : Template for image 'Ubuntu2204' doesn't exist on path
'C:\temp\virtual-environments\images\linux\ubuntu2204.json'

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

N/A

### Expected behavior

Building Ubuntu2204 according to the documentation should work. 

### Actual behavior

It broke halp plz

### Repro steps

1. Sync the latest
2. Follow the directions here https://github.com/actions/virtual-environments/blob/main/docs/create-image-and-azure-resources.md
3. Try to use Ubuntu2204 as the image
4. fall down go boom

**Comment by jeffpuckett** [comment]
Caused by https://github.com/actions/virtual-environments/pull/5517. Ubuntu2004 works fine.

**Comment by mikhailkoliada** [comment]
Thanks, we will provide a fix shortly

**Comment by mikhailkoliada** [comment]
@jeffpuckett fixed, please pull the changes from main and try again.

**Comment by jeffpuckett** [comment]
working, thank you!

**Comment by jeffpuckett** [comment]
well, i've got another bug, something about not specifying a public ip, but i can use 2004 for now
