### ISSUE TITLE
Error building Ubuntu 22.04 using GenerateResourcesAndImage - Inappropriate value for attribute "allowed_inbound_ip_addresses"

### ISSUE THREAD

**Issue by jeffpuckett** [actions/virtual-environments#5593]
### Description

GenerateResourcesAndImage -SubscriptionId "*****" -ResourceGroupName "testresourcegroup" -ImageGenerationRepositoryRoot "$pwd" -ImageType Ubuntu2204 -AzureLocation "East US"

Running this doesn't last long and the resulting output is below

*****

Output: Latest commit:
Date: Mon May 23 16:50:28 2022 +0300; Commit: 64e497aba9254bc120d3587f22724ae96588c134 - Add clang-tidy to Ubuntu images (#5541); Author: juliancarrivick <jcarrivick@outlook.com>Error: Incorrect attribute value type

  on C:\temp\ve\virtual-environments\images\linux\ubuntu2204.pkr.hcl line 148:
  (source code not available)

with var.allowed_inbound_ip_addresses as "".

Inappropriate value for attribute "allowed_inbound_ip_addresses": list of string
required.

==> Wait completed after 0 seconds

==> Builds finished but no artifacts were created.

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

n/a

### Repro steps

1. Sync latest
2. Follow steps https://github.com/actions/virtual-environments/blob/main/docs/create-image-and-azure-resources.md but use Ubuntu2204 for the templatefilepath
3. That's it

**Comment by igorboskovic3** [comment]
Hi @jeffpuckett , than you for reporting this error, we will take a look.

**Comment by al-cheb** [comment]
@jeffpuckett, I have updated the script, try to use - https://github.com/al-cheb/virtual-environments/tree/fix-genimage-script

**Comment by jeffpuckett** [comment]
this worked for me, thank you

**Comment by al-cheb** [comment]
Merged https://github.com/actions/virtual-environments/pull/5602.
