### ISSUE TITLE
[all OSs] Android NDK 22 will be replaced in favor of 24, version 23 will be set as the default one on June, 6

### ISSUE THREAD

**Issue by miketimofeev** [actions/virtual-environments#5595]
### Breaking changes

There are two changes:
- Ndk 22 will be replaced by Ndk 24
- Ndk 23 will be the new default (ndk-bundle) instead of Ndk 21

### Target date

The propagation is starting on June, 6 and will take 3-4 days

### The motivation for the changes

According to our [Software and image guidelines](https://github.com/actions/virtual-environments/blob/main/docs/software-and-images-guidelines.md) we support 1 latest non-LTS and 2 latest LTS versions of NDK. Currently, our image contains NDK r22 whereas the latest non-LTS is 24. LTS version of NDK 21 is not supported so we would like to set version 23 as the new default.

### Possible impact

- If your project depends on NDK r22 it can be broken
- If your project relies on ndk-bundle based on r21 it can be broken

### Virtual environments affected

- [X] Ubuntu 18.04
- [X] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [X] macOS 10.15
- [X] macOS 11
- [X] macOS 12
- [X] Windows Server 2019
- [X] Windows Server 2022

### Mitigation ways

- To install NDK r22 in runtime use the following snippets;
    - Windows
     ```pwsh
     $sdkRoot = "C:\Android\android-sdk"
     $sdkManager = "$sdkRoot\cmdline-tools\latest\bin\sdkmanager.bat"
     Install-AndroidSDKPackages -AndroidSDKManagerPath $sdkManager `
                                -AndroidSDKRootPath $sdkRoot `
                                -AndroidPackages "ndk;21.4.7075529"
    ```
    - macOS
    ```bash
     ANDROID_HOME=$HOME/Library/Android/sdk
     SDKMANAGER=$ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager
     echo y | $SDKMANAGER "ndk;21.4.7075529"
    ```
    - Ubuntu
     ```bash
     ANDROID_ROOT=/usr/local/lib/android
     ANDROID_SDK_ROOT=${ANDROID_ROOT}/sdk
     SDKMANAGER=${ANDROID_SDK_ROOT}/cmdline-tools/latest/bin/sdkmanager
     echo "y" | $SDKMANAGER "ndk;21.4.7075529"
    ```
- To change default NDK version (ndk-bundle) use the following snippets:
    - Windows
     ```pwsh
       $sdkRoot = "C:\Android\android-sdk"
       $sdkManager = "$sdkRoot\cmdline-tools\latest\bin\sdkmanager.bat"
       $ndkRoot = "$sdkRoot\ndk-bundle"
       New-Item -Path $ndkRoot -ItemType SymbolicLink -Value "$sdkRoot\ndk\21.4.7075529" -Force
    ```
    - macOS
    ```bash
      ANDROID_HOME=$HOME/Library/Android/sdk
       ln -sfn $ANDROID_HOME/ndk/21.4.7075529 $ANDROID_HOME/ndk-bundle
    ```
    - Ubuntu
     ```bash
      ANDROID_ROOT=/usr/local/lib/android
      ANDROID_SDK_ROOT=${ANDROID_ROOT}/sdk
      ANDROID_NDK_ROOT=${ANDROID_SDK_ROOT}/ndk-bundle
      ln -sfn $ANDROID_SDK_ROOT/ndk/21.4.7075529 $ANDROID_NDK_ROOT
    ```

**Comment by mikhailkoliada** [comment]
Will be deployed next week.

**Comment by Bercon** [comment]
At least my builds are failing since the NDK 23 being default was deployed already?

**Comment by miketimofeev** [comment]
@Bercon no, it was not. The new image rollout will start today

**Comment by Bercon** [comment]
After further debugging, it appears my issue is most likely ndk 23 updating from 23.1 to 23.2 which didn't work out of the box with https://github.com/moritz-wundke/Boost-for-Android we are using.

**Comment by mikhailkoliada** [comment]
All the images have been updated

**Comment by MBilderbeek** [comment]
Thanks for this work! But how exactly can I make sure my build uses ndk r24 instead of the default 23 on the Ubuntu 22.04 image? See https://github.com/openMSX/openMSX/actions/workflows/build_snapshots.yml
Our code needs clang-13, so ndk r24 is the only way...

**Comment by miketimofeev** [comment]
@MBilderbeek you can try the following snippet to replace ndk-bundle with NDK r24
```bash
 ANDROID_ROOT=/usr/local/lib/android
 ANDROID_SDK_ROOT=${ANDROID_ROOT}/sdk
 ANDROID_NDK_ROOT=${ANDROID_SDK_ROOT}/ndk-bundle
 ln -sfn $ANDROID_SDK_ROOT/ndk/24.0.8215888 $ANDROID_NDK_ROOT
```

**Comment by MBilderbeek** [comment]
@miketimofeev Thanks, got it working by just adding this step:
`echo "$ANDROID_NDK_LATEST_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin" >> $GITHUB_PATH`
However, for some reason, the clang-14 in NDK r24 can't compile what normal clang can, and thus we have failing builds. This is probably an NDK question, but if someone has any idea, please contact me.
In detail: it doesn't recognize std::identity and several other C++-20 features. Standard is probably specified, though.

**Comment by soroshsabz** [comment]
related to https://github.com/xamarin/xamarin-android/issues/6808#issuecomment-1102662611
