### ISSUE TITLE
Update CMake on Linux

### ISSUE THREAD

**Issue by wipe2238** [actions/virtual-environments#56]
**Tool information**
- Tool name: cmake
- Add or update? Update
- Desired version: 3.15.4 (as on windows/macOs)
- Approximate size:

**Virtual environments affected**
- [ ] macOS 10.14
- [x] Ubuntu 16.04 LTS
- [x] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Can this tool be installed during the build?**
Yes (download .tar.gz from cmake.org, extract, add to PATH).

It would be nice if we had same version everywhere in future; there won't be need to check versions on each OS before tweaking project with newer features.

**Are you willing to submit a PR?**
???

**Comment by al-cheb** [comment]
Hello, @wipe2238 

Thank you for taking the time to report an issue. I have created PR to fix this issue(PR https://github.com/actions/virtual-environments/pull/274)

**Comment by maxim-lobanov** [comment]
This issue will also resolve https://github.com/actions/virtual-environments/issues/110

**Comment by zbeekman** [comment]
#274 was merged and upgraded to 3.16.2. I think this issue can be closed now
