### ISSUE TITLE
Add lcov

### ISSUE THREAD

**Issue by rick-de-water** [actions/virtual-environments#560]
**Tool information**
- Tool name: lcov
- Add or update? Add
- Desired version: 1.14-2 or later
- Approximate size: small
- Brief description of tool:
`lcov` can process `gcov` output to generate coverage reports. None of the `apt` versions are compatible with GCC 9, which IS installed in the environment.
- URL for tool's homepage: https://github.com/linux-test-project/lcov

**Area for Triage**:
C/C++

**Question, Bug, or Feature?**:
Feature

**Virtual environments affected**
- [ ] macOS 10.15
- [x] Ubuntu 16.04 LTS
- [x] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Can this tool be installed during the build?**
Ubuntu 18.04 has 1.13-3, and 16.04 has 1.12-2 on apt-get. 1.14-2 is required for GCC 9. So to get the correct version you would have to do it manually

**Are you willing to submit a PR?**
No

**Comment by maxim-lobanov** [comment]
As an option, Icov can be installed in runtime using the following script:
```
VERSION="1.14"
mkdir Iconv
cd Iconv
wget "https://github.com/linux-test-project/lcov/releases/download/v1.14/lcov-$VERSION.tar.gz"
tar -xzf "lcov-$VERSION.tar.gz"
cd "lcov-$VERSION"
sudo make install
```
It takes about 10 seconds to run.
Does it work for you?

**Comment by rick-de-water** [comment]
Sadly it doesn't. That gives me 1.14, and I need 1.14-2.

**Comment by rick-de-water** [comment]
You can see it fail here: https://github.com/rick-de-water/Lingo/runs/533178209

**Comment by maxim-lobanov** [comment]
[The change](https://github.com/linux-test-project/lcov/commit/75fbae1cfc5027f818a0bb865bf6f96fab3202da) that you are looking for was done in master but the new version was not released yet. Release 1.14 is the last one in [lcov repository](https://github.com/linux-test-project/lcov/releases).

1.14-2 can be installed directly from master branch using the following code:
```
wget "https://github.com/linux-test-project/lcov/archive/master.zip"
unzip "master.zip"
cd "lcov-master"
sudo make install
```
Installation takes about 7 seconds as previously

**Comment by rick-de-water** [comment]
Got it to work by also adding `sudo apt install libperlio-gzip-perl libjson-perl`, otherwise lcov will get a runtime error on not finding these perl modules.

**Comment by thejoebourneidentity** [comment]
Thanks @rick-de-water, we're going to close this issue for now and not add `lvoc` directly to the image. Let us know if you continue to see problems over at the community forum.

https://github.community/t5/GitHub-Actions/bd-p/actions
