### ISSUE TITLE
Add ccache

### ISSUE THREAD

**Issue by yujincheng08** [actions/virtual-environments#5600]
### Tool name

ccache

### Tool license

GPL-3.0

### Add or update?

- [X] Add
- [ ] Update

### Desired version

latest

### Approximate size

less than 5M

### Brief description of tool

Ccache is a compiler cache. It [speeds up recompilation](https://ccache.dev/performance.html) by caching previous compilations and detecting when the same compilation is being done again. Ccache is free software, released under the [GNU General Public License version 3](http://www.gnu.org/licenses/gpl.html) or later. See also the [license page](https://ccache.dev/license.html).

### URL for tool's homepage

https://ccache.dev

### Virtual environments affected

- [X] Ubuntu 18.04
- [X] Ubuntu 20.04
- [X] Ubuntu 22.04
- [X] macOS 10.15
- [X] macOS 11
- [X] macOS 12
- [X] Windows Server 2019
- [X] Windows Server 2022

### Tool installation time in runtime

less than 30s

**Comment by igorboskovic3** [comment]
Hi @yujincheng08, thank you for your request. We will take a look and get back to you.

**Comment by miketimofeev** [comment]
@yujincheng08 there are a few gh actions available to install and use ccache, for example, https://github.com/marketplace/actions/ccache-for-gh-actions
Using actions is a recommended way to install the software in runtime.
I'm going to close the issue. Feel free to contact us if you have any concerns.
Thank you!
