### ISSUE TITLE
[macOS] Default Visual studio for mac will be changed to version 2022 for macOS 11&12 on May, 30

### ISSUE THREAD

**Issue by miketimofeev** [actions/virtual-environments#5601]
### Breaking changes

We are going to change the default Visual Studio for Mac from 2019 to 2022 for macOS 11 and macOS 12 images. The previous version will still be available for a few next weeks under the `/Applications/Visual Studio 2019.app` path.

### Target date

The new image deployment will start on May, 30 and will take 3-4 days to propagate to all the environments.

### The motivation for the changes

Visual Studio 2022 for Mac is now generally available and we would like to provide the latest stable version on our images https://devblogs.microsoft.com/visualstudio/visual-studio-2022-for-mac-is-now-available/

### Possible impact

If your project is incompatible with Visual Studio for Mac 2022 it can be broken.

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 10.15
- [X] macOS 11
- [X] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Mitigation ways

Visual Studio 2019 for Mac will be available under the `/Applications/Visual Studio 2019.app` path. The deprecation will be announced additionally.

**Comment by Brosten** [comment]
So, what's the new installation path for vs 2022 and for msbuild? (Since the current c# 9 [workaround](https://github.com/microsoft/appcenter/issues/86) using 
mono /Applications/Visual\ Studio.app/Contents/Resources/lib/monodevelop/bin/MSBuild/Current/bin/MSBuild.dll 
doesn't work any more.) And switching to the 2019 path seems like a real short term solution.

**Comment by al-cheb** [comment]
@Brosten, https://github.com/actions/virtual-environments/blob/main/images/macos/macos-12-Readme.md#visual-studio-for-mac

**Comment by al-cheb** [comment]
The new image with VS 2022 on board has been deployed.

**Comment by al-cheb** [comment]
The new macOS 11 image with VS 2022 on board has been deployed - https://github.com/actions/virtual-environments/blob/main/images/macos/macos-11-Readme.md

**Comment by qwertylolman** [comment]
is .net6 will be available also?

**Comment by al-cheb** [comment]
> is .net6 will be available also?

Our recommendation is to use `https://github.com/actions/setup-dotnet` task to install .Net.
