### ISSUE TITLE
Flapak-builder fails to download glu-9.0.2 on Ubuntu 22.04

### ISSUE THREAD

**Issue by MehdiChinoune** [actions/virtual-environments#5607]
### Description

I have created a repo to reproduce the issue:
https://github.com/MehdiChinoune/flatpak-22-04

https://github.com/MehdiChinoune/flatpak-22-04/runs/6588263107

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Version: 20220522.1

### Repro steps

Fellow the same steps as in the flatpak.yml file

**Comment by al-cheb** [comment]
@MehdiChinoune , External bug - https://github.com/flatpak/flatpak-builder/issues/468
