### ISSUE TITLE
Add Clang 14 to Ubuntu 22.04

### ISSUE THREAD

**Issue by BertalanD** [actions/virtual-environments#5608]
### Tool name

clang-14

### Tool license

Apache-2.0 WITH LLVM-exception

### Add or update?

- [ ] Add
- [X] Update

### Desired version

14

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

**Comment by BertalanD** [comment]
The [software guidelines](https://github.com/actions/virtual-environments/blob/main/docs/software-and-images-guidelines.md#software-and-images-support-policy) says that the 3 latest versions of Clang are supposed to be supported. Currently, the Ubuntu 22.04 image ships with version 11 and 12, while Clang 14 is the latest version, and is available in the official Ubuntu repository.

Having Clang 14 be available by default would make the life of C++20 projects easier.

**Comment by igorboskovic3** [comment]
Hi @BertalanD we will take a look.

**Comment by miketimofeev** [comment]
@BertalanD thanks, looks like we missed that part during the beta image preparation. We will remove Clang 10 & 11 and add 13 & 14

**Comment by BertalanD** [comment]
Hey @miketimofeev! Thank you for the quick fix. Do you know when we can expect the new image to be rolled out?

**Comment by miketimofeev** [comment]
@BertalanD we will update the image throughout next week, I'll post an update once it's fully available

**Comment by miketimofeev** [comment]
@BertalanD the new image with Clang 12,13 & 14 has been deployed.
I'm going to close the issue. Feel free to contact us if you have any concerns.
Thank you!
