### ISSUE TITLE
Executables built with windows-2022 segfault on some machines.

### ISSUE THREAD

**Issue by veluca93** [actions/virtual-environments#5609]
### Description

Binaries produced on the windows-2022 version of the Windows virtual environment for our project seem to segfault on _some_ machines.

See also bug reports https://github.com/libjxl/libjxl/issues/1426 and https://github.com/libjxl/libjxl/issues/1282 

If there is a pattern that identifies machines where it segfaults from those were it works, I couldn't find it: it works on my personal Windows 11 machine, but it segfaults on some other Windows 11 machines. It also segfaults on all Windows 10 installations I tried it on.

The only variable I thought of that I didn't exclude is Secure Boot being enabled, although given the nature of the crash (trying to access address `0x880`, at least on one of the machines), it seems somewhat unlikely.

A local build with MSVC 2022 on both Windows 11 and Windows 10 machines works without any issue.
A build on Actions with windows-2019 works without any issues.
Linux builds (both with Actions and local) also work without any issues.

I do not believe this to be a potential issue in our codebase (although of course I could be proven wrong ;)), especially since the same compiled executable works on _some_ machines, and the same compiler major version produces working local builds on all machines I tested this on.

For completeness, the crash happens in AVX2 code, on a `vbroadcastf128` instruction inside (a callee of) this function: https://github.com/libjxl/libjxl/blob/main/lib/jxl/convolve.cc#L946 -- more precisely, I believe at this line https://github.com/libjxl/libjxl/blob/main/lib/jxl/convolve.cc#L95 (where `LoadDup128` is a thin wrapper for `vbroadcastf128`). The data is loaded from this struct/array: https://github.com/libjxl/libjxl/blob/main/lib/jxl/gaborish.cc#L33

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

Version 20220515.1: https://github.com/libjxl/libjxl/runs/6549710805?check_suite_focus=true

However, the problem has been present since ~February (when windows-latest switched to windows-2022 for our repository)

The 20220515.1 version of the windows-2019 build produces working executables: https://github.com/libjxl/libjxl/runs/6556401360?check_suite_focus=true

### Repro steps

- Download the `jxl-x64-windows-static` build from a run using `windows-2022`, i.e. https://github.com/libjxl/libjxl/actions/runs/2369266817
- Obtain any PNG file
- Run `cjxl.exe image.png out.jxl`
- On some machines, the execution returns with exit code 0xC0000005 without creating an `out.jxl` file. On other machines, it will complete successfully.

**Comment by al-cheb** [comment]
@veluca93,
Unfortunately, at this time out agents are not guaranteed to have AVX2, and only the way to enable the feature for you on permanent basis is to use **self-hosted agents**(where it is possible to control the underlying hardware). 

https://github.com/MicrosoftDocs/azure-docs/issues/8785#issuecomment-456637322

**Comment by veluca93** [comment]
> @veluca93, Unfortunately, at this time out agents are not guaranteed to have AVX2 CPU instruction, and only the way to enable the feature for you on permanent basis is to use **self-hosted agents**(where it is possible to control the underlying hardware).
> 
> [MicrosoftDocs/azure-docs#8785 (comment)](https://github.com/MicrosoftDocs/azure-docs/issues/8785#issuecomment-456637322)

Note that the crash does not happen on the runner itself (in fact the built application is not executed at all on the runner), but when executing the resulting executable on a system that _does_ have AVX2.

**Comment by veluca93** [comment]
For that matter, the binary uses runtime CPU feature detection, and would not attempt to execute AVX2 code on machines that do not have AVX2 instructions.

**Comment by miketimofeev** [comment]
@veluca93 I tried this binary https://github.com/libjxl/libjxl/suites/6614694285/artifacts/249001955 on my local win10 machine and everything works just fine
![image](https://user-images.githubusercontent.com/48208649/170261848-9a24eb00-66c6-463e-ad04-749d8d70361c.png)

```
PS C:\Users\Administrator\Downloads\test> .\cjxl.exe .\pngwing.com.png out.jxl
JPEG XL encoder v0.7.0 b432598 [AVX2,SSE4,SSSE3,Scalar]
Read 1280x664 image, 27.9 MP/s
Encoding [VarDCT, d1.000, squirrel], 8 threads.
```
This is the png I used 
![pngwing com](https://user-images.githubusercontent.com/48208649/170261898-61f2cad7-de6d-4d14-b5ce-82eeb9477417.png)

**Comment by veluca93** [comment]
Was a `out.jxl` file produced? I believe it wasn't, as the output you see is not the complete output of the program (and indeed identical to the output receives on a segmentation fault).

**Comment by al-cheb** [comment]
I don't have out.jxl on Windows 11 either.
![image](https://user-images.githubusercontent.com/47745270/170264978-3f5f7f32-69eb-41ee-9c31-1069547cb9d3.png)

![image](https://user-images.githubusercontent.com/47745270/170264878-415419b0-142c-4336-a659-e4cac33af7d5.png)

**Comment by veluca93** [comment]
If one downloads the second build I linked, https://github.com/libjxl/libjxl/runs/6556401360?check_suite_focus=true / https://github.com/libjxl/libjxl/actions/runs/2371672648, which is built on windows-2019, it should work without specifying any flags. Note that the commit in question only changes windows-latest to windows-2019.

**Comment by miketimofeev** [comment]
@veluca93 you are right, it wasn't produced. But it's still unclear to us how we can help debug this, I'm afraid. If it is connected to the underlying hardware then we can't do anything at all as we don't control what hardware Azure provides to us but on the other hand, the same hardware should be used for windows-2019 machines as well so might be not related.

**Comment by veluca93** [comment]
I doubt this is related to the underlying hardware, as compiler output typically doesn't depend on the hardware that runs the compiler.

I would guess this to be related to some atypical configuration of Windows Server 2022 / MSVC 2022 on the builder.

For example, it might enable some Windows Server only features for the dynamic linker in the resulting executable (assuming such a thing exists).

**Comment by miketimofeev** [comment]
Do you have a chance to build your binaries on some other win server 22 machine? I wonder if a clean win serv 2022 machine will have the same issue

**Comment by veluca93** [comment]
I do not have any Windows Server machines I can access.

**Comment by miketimofeev** [comment]
You can try a free Azure trial and create a windows-2022 Virtual Machine
https://azure.microsoft.com/en-us/free/

**Comment by veluca93** [comment]
I managed to do a local build on a Windows Server 2022 VM.

Interestingly, on the VM the executable crashes both with the GitHub Actions executable and with a local build.

So perhaps this is a MSVC2022 bug that only triggers on Windows Server 2022? If that's the case, would you be able to point me to the best place to file an issue?

**Comment by al-cheb** [comment]
I think - https://developercommunity.visualstudio.com/
