### ISSUE TITLE
Why is the image "vs2015-win2012r2"  removed ? 

### ISSUE THREAD

**Issue by sqlenders** [actions/virtual-environments#561]
I am using that image to build SSRS reports for SQL server 2014. Migrating to VS 2017 is not possible. SSRS is not avaible in VS 2019
According to the life cycle https://docs.microsoft.com/en-us/visualstudio/releases/2019/servicing
I am expecting that this image is available to October 2025.

**Comment by Croydon** [comment]
Related to #387 

I haven't got any response anywhere so far.

**Comment by sqlenders** [comment]
I will be happy with VS2015 on WIN2019

**Comment by JustinGrote** [comment]
@sqlenders 
https://devblogs.microsoft.com/devops/removing-older-images-in-azure-pipelines-hosted-pools/

Looks like you are the 5% :)

**Comment by vijayma** [comment]
@sqlenders, I am sorry that we cannot maintain an increasing number of images to meet all the needs of our customers. At some point, we will have to pick new ones and deprecate old ones, and that is based on customer demand. Self-hosted agents and [elastic self-hosted agents](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/vmss?view=azure-devops) are your options.

**Comment by Croydon** [comment]
What about adding a VS 2015 installation to the newest image? -> #387

**Comment by AlenaSviridenko** [comment]
Hi @sqlenders ! I am closing this issue in favor of https://github.com/actions/virtual-environments/issues/387 that is prioritized and put in our "To Do" backlog. We will keep your posted with the updates there.
Please, feel free to reopen this issue if you have any concerns.
Thanks!
