### ISSUE TITLE
windows 2019 deployment fails

### ISSUE THREAD

**Issue by celenn** [actions/virtual-environments#5616]
### Description

    vhd: Running tests from 'C:\image\Tests\Node.Tests.ps1'
    vhd: Describing Node.JS
    vhd:  Context Basic modules
    vhd:    [+] node  797ms (489ms|308ms)
    vhd:    [+] npm  971ms (969ms|1ms)
    vhd:  Context Global NPM Packages
    vhd:    [+] yarn 334ms (331ms|3ms)
    vhd:    [+] newman 762ms (761ms|1ms)
    vhd:    [+] lerna 279ms (277ms|1ms)
    vhd:    [+] typescript 228ms (227ms|1ms)
    vhd:    [+] grunt-cli 267ms (266ms|1ms)
    vhd:    [+] gulp-cli 475ms (474ms|1ms)
    vhd:    [-] parcel 185ms (183ms|3ms)
    vhd:     Command 'parcel --version' has finished with exit code
    vhd:         node:internal/modules/cjs/loader:936
    vhd:           throw err;
    vhd:           ^
    vhd:
    vhd:         Error: Cannot find module 'C:\npm\prefix\node_modules\parcel\lib\bin.js'
    vhd:             at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    vhd:             at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    vhd:             at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    vhd:             at node:internal/main/run_main_module:17:47 {
    vhd:           code: 'MODULE_NOT_FOUND',
    vhd:           requireStack: []
    vhd:         }

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [X] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Cannot find module 'C:\npm\prefix\node_modules\parcel\lib\bin.js'

### Repro steps

While running the pipeline execution, we are getting error as 
    vhd:         Error: Cannot find module 'C:\npm\prefix\node_modules\parcel\lib\bin.js'
    vhd:             at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    vhd:             at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    vhd:             at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    vhd:             at node:internal/main/run_main_module:17:47 {
    vhd:           code: 'MODULE_NOT_FOUND',
    vhd:           requireStack: []
    vhd:         }
 Its for windows 2019 deployment and it was working fine earlier, is there any path modification needs to be done in the [Tools.Tests.ps1] script?

**Comment by AlexanderGitin** [comment]
Hello @celenn, thank you reporting this one. We will take a look.

**Comment by prabhusirpi** [comment]
Hello @AlexanderGitin - We are currently facing the similar issue in our environment, please let us know if there is any further update on it.

**Comment by al-cheb** [comment]
@celenn, @prabhusirpi  - You have to pull the latest changes from main branch.
