### ISSUE TITLE
Windows 2016 removal

### ISSUE THREAD

**Issue by prajwalar97** [actions/virtual-environments#5617]
### Description

We are having a pipeline which runs on 2016 Agent Specification. After changing the Agent Specification to 2019 or windows Latest we are getting below

022-04-21T15:06:27.3818037Z Project file contains ToolsVersion="15.0". This toolset may be unknown or missing, in which case you may be able to resolve this by installing the appropriate version of MSBuild, or the build may have been forced to a particular ToolsVersion for policy reasons. Treating the project as if it had ToolsVersion="4.0". For more information, please see http://go.microsoft.com/fwlink/?LinkId=291333.
error CS1519: Invalid token '(' in class, struct, or interface member declaration
error CS1519: Invalid token '.' in class, struct, or interface member declaration

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [X] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

<img width="295" alt="Version" src="https://user-images.githubusercontent.com/105055576/170512650-3ab5d257-3996-475f-9f22-298f62d68c56.PNG">

### Is it regression?

It is working fine in windows 2016, but not for the others win versiona

### Expected behavior

Build should happen without any issue.

### Actual behavior

Project build is not happening if we select Agent Specification as 2019 or Latest.

### Repro steps

 Use the the Win 2019 or latest as Agent Specification in classic editor and try build the .Net framework project.

**Comment by AlexanderGitin** [comment]
Hello @prajwalar97, thank you reporting this one. We will take a look.

**Comment by miketimofeev** [comment]
@prajwalar97 could you start with this article and try to migrate your project to a newer VS version?
https://docs.microsoft.com/en-us/visualstudio/porting/port-migrate-and-upgrade-visual-studio-projects?view=vs-2022

**Comment by prajwalar97** [comment]
@miketimofeev the article doesn't have the steps for Migration of .Net Framework project with toolsversion 15 to latest, and manually changing the toolsversion not working.

**Comment by miketimofeev** [comment]
@prajwalar97 please try to find the answer in the https://developercommunity.visualstudio.com/ as we don't have access to your project and I'm afraid can't help migrating.
