### ISSUE TITLE
Building Windows 2022 Image Fails

### ISSUE THREAD

**Issue by srofewd** [actions/virtual-environments#5622]
### Description

The Windows 2022 image build is failing during tests.

 vhd: Running tests from 'C:\image\Tests\CLI.Tools.Tests.ps1'
    vhd: Describing AWS
    vhd:   [+] AWS CLI 1.7s (1.5s|206ms)
    vhd:   [+] Session Manager Plugin for the AWS CLI 265ms (263ms|2ms)
    vhd:   [+] AWS SAM CLI 1.94s (1.93s|2ms)
    vhd: Tests completed in 7.44s
    vhd: Tests Passed: 3, Failed: 0, Skipped: 0 NotRun: 7
==> vhd: Provisioning with powershell script: C:\virtual-environments\images\win/scripts/Installers/Install-DACFx.ps1
    vhd: Downloading DacFramework.msi...
    vhd: Downloading package from: https://aka.ms/dacfx-msi to path C:\Users\packer\AppData\Local\Temp\DacFramework.msi .
    vhd: Package downloaded successfully in 1.42 seconds
    vhd: Starting Install DacFramework.msi...
    vhd: Installation successful in 2.13 seconds
    vhd: Pester v5.3.3
    vhd:
    vhd: Starting discovery in 1 files.
    vhd: Discovery found 44 tests in 1.43s.
    vhd: Filter 'FullName' set to ('DACFx').
    vhd: Filters selected 2 tests to run.
    vhd: Running tests.
    vhd:
    vhd: Running tests from 'C:\image\Tests\Tools.Tests.ps1'
    vhd: Describing DACFx
    vhd:   [-] DACFx 1.08s (869ms|215ms)
    vhd:    Expected $true, but got $false.
    vhd:    at (Get-ItemProperty HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\*).DisplayName -Contains "Microsoft SQL Server Data-Tier Application Framework (x64)" | Should -BeTrue, C:\image\Tests\Tools.Tests.ps1:43
    vhd:    at <ScriptBlock>, C:\image\Tests\Tools.Tests.ps1:43
    vhd:   [!] SqlLocalDB 4ms (0ms|4ms)
    vhd: Tests completed in 5.27s
==> vhd: Test run has failed
    vhd: Tests Passed: 0, Failed: 1, Skipped: 1 NotRun: 42
    vhd:
    vhd:
    vhd: Containers            : {[-] C:\image\Tests\Tools.Tests.ps1}
    vhd: Result                : Failed
    vhd: FailedCount           : 1
    vhd: FailedBlocksCount     : 0
    vhd: FailedContainersCount : 0
    vhd: PassedCount           : 0
    vhd: SkippedCount          : 1
    vhd: NotRunCount           : 42
    vhd: TotalCount            : 44
    vhd: Duration              : 00:00:05.2699584
    vhd: Executed              : True
    vhd: ExecutedAt            : 5/26/2022 4:50:42 PM
    vhd: Version               : 5.3.3
    vhd: PSVersion             : 5.1.20348.643
    vhd: PSBoundParameters     : {[Configuration, PesterConfiguration]}
    vhd: Plugins               :
    vhd: PluginConfiguration   :
    vhd: PluginData            :
    vhd: Configuration         : PesterConfiguration
    vhd: DiscoveryDuration     : 00:00:01.3671307
    vhd: UserDuration          : 00:00:01.0474016
    vhd: FrameworkDuration     : 00:00:02.8554261
    vhd: Failed                : {[-] DACFx}
    vhd: FailedBlocks          : {}
    vhd: FailedContainers      : {}
    vhd: Passed                : {}
    vhd: Skipped               : {[!] SqlLocalDB}
    vhd: NotRun                : {[ ] Azure Cosmos DB Emulator install location registry key exists, [ ] Azure Cosmos DB
    vhd:                         Emulator exe file exists, [ ] <ToolName>, [ ] <ToolName>...}
    vhd: Tests                 : {[ ] Azure Cosmos DB Emulator install location registry key exists, [ ] Azure Cosmos DB
    vhd:                         Emulator exe file exists, [ ] <ToolName>, [ ] <ToolName>...}
    vhd: CodeCoverage          :
    vhd:
==> vhd: At C:\Program Files\WindowsPowerShell\Modules\ImageHelpers\TestsHelpers.ps1:73 char:9
==> vhd: +         throw "Test run has failed"
==> vhd: +         ~~~~~~~~~~~~~~~~~~~~~~~~~~~
==> vhd:     + CategoryInfo          : OperationStopped: (Test run has failed:String) [], RuntimeException
==> vhd:     + FullyQualifiedErrorId : Test run has failed
==> vhd:
==> vhd: Script exited with non-zero exit status: 1.Allowed exit codes are: [0]
==> vhd: Step "StepProvision" failed
==> vhd: [c] Clean up and exit, [a] abort without cleanup, or [r] retry step (build may fail even if retry succeeds)?

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

OS Version: 10.0.20348 Build 707
Image Version: 20220522.1

### Is it regression?

no

### Expected behavior

I expected the build not to fail.

### Actual behavior

Build is failing

### Repro steps

I am running from a Windows 11 desktop building to our Azure tenant.

GenerateResourcesAndImage -SubscriptionId xxxxxxxxxxxxxx -ResourceGroupName "xxxxxxxxxxxx" -ImageGenerationRepositoryRoot "$pwd" -ImageType "Windows2022" -AzureLocation "East US"

I have removed the actual subscription id and resource group name.

**Comment by al-cheb** [comment]
@srofewd, fixed in https://github.com/actions/virtual-environments/pull/5613 PR.
