### ISSUE TITLE
Add miniconda on macOS-12

### ISSUE THREAD

**Issue by goanpeca** [actions/virtual-environments#5623]
### Tool name

miniconda

### Tool license

License: Free use and redistribution under the terms of the EULA for Miniconda.

### Add or update?

- [X] Add
- [ ] Update

### Desired version

Whatever is default (like the other runners)

### Approximate size

56.0 to 72 MB (depends on the version)

### Brief description of tool

Miniconda is a free minimal installer for conda. It is a small, bootstrap version of Anaconda that includes only conda, Python, the packages they depend on, and a small number of other useful packages, including pip, zlib and a few others. Use the conda install command to install 720+ additional conda packages from the Anaconda repository.

### URL for tool's homepage

https://docs.conda.io/en/latest/miniconda.html#macos-installers

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [X] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Can this tool be installed during the build?

```bash
I am the author of this action https://github.com/conda-incubator/setup-miniconda

And we have relied on the bundled miniconda on runners. We also provide a way to install a new version, but using the bundled version often saves a lot of time.
```

### Tool installation time in runtime

About a minute or less?

### Are you willing to submit a PR?

If I can get some pointers? But it already seems to be bundled on all the other runners

**Comment by miketimofeev** [comment]
Hi @goanpeca!
If the preinstalled miniconda saves time during the action then we have no concerns adding it. We will take care of it.

**Comment by al-cheb** [comment]
The new macOS-12 image has been deployed with miniconda on board - https://github.com/actions/virtual-environments/blob/main/images/macos/macos-12-Readme.md

```
Package Management
-Miniconda 4.12.0
```
