### ISSUE TITLE
Add Salesforce CLI

### ISSUE THREAD

**Issue by SenthilnathanThang** [actions/virtual-environments#5626]
### Tool name

Salesforce CLI

### Tool license

Free

### Add or update?

- [X] Add
- [ ] Update

### Desired version

whatever is latest

### Brief description of tool

Salesforce CLI tool will help to execute SFDX commands which will be used in the build pipeline and release pipeline.

### URL for tool's homepage

https://developer.salesforce.com/tools/sfdxcli

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

**Comment by AlexanderGitin** [comment]
Hello @SenthilnathanThang, thank you reporting this one. We will take a look.

**Comment by miketimofeev** [comment]
@SenthilnathanThang a few questsion:
- Do you use Azure DevOps or GitHub actions?
- What OS do you use in your pipelines that need this tool?

**Comment by al-cheb** [comment]
@SenthilnathanThang, gentle ping. Please answer to questions above.

**Comment by SenthilnathanThang** [comment]
> @SenthilnathanThang a few questsion:
> 
> * Do you use Azure DevOps or GitHub actions?
> * What OS do you use in your pipelines that need this tool?

@miketimofeev , Sorry or the delay in response.

>* Do you use Azure DevOps or GitHub actions?
     Yes, I use GitHub as Repository and Azure DevOps for Pipeline.

> * What OS do you use in your pipelines that need this tool?
     I'm using Windows OS.

**Comment by miketimofeev** [comment]
@SenthilnathanThang I'm afraid we are not going to pre-install this tool due to its popularity and maintenance concerns. Please use the following powershell snippet to install the CLI in runtime:
```pwsh
$InstallerName = "sfdx.exe"
$InstallerUrl = "https://developer.salesforce.com/media/salesforce-cli/sfdx/channels/stable/sfdx-x64.exe"
$ArgumentList = ("/S","/D=C:\sfdx")

Install-Binary -Url $InstallerUrl -Name $InstallerName -ArgumentList $ArgumentList
C:\sfdx\bin\sfdx.cmd --version
C:\sfdx\bin\sf.cmd --version
```

**Comment by jatin-tenguriya-intapp** [comment]
just need to confirm that post executing these snippets github self hosted runner will have sfdx cli install, right?

**Comment by jatin-tenguriya** [comment]
just need to confirm that post executing these snippets github self hosted runner will have sfdx cli install, right?
