### ISSUE TITLE
IMAGEREPOSITORYPATH needs a default set in GenerateResourcesAndImage.ps1

### ISSUE THREAD

**Issue by jeffpuckett** [actions/virtual-environments#5636]
### Description

#5462 Added an environment variable for building Ubuntu2204 to the packer hcl file and the azure pipelines. However the GenerateResourcesAndImage.ps1 file does not set this variable. If it is not set you may (probably will) receive this error.

Latest commit:
Date: Sat May 28 09:14:05 2022 +0200; Commit: a814bcd5134b607cd09e188d99ac0e95ef33d8af - Adding beta indicator (#5628); Author: Larissa Fortuna <56982181+lkfortuna@users.noreply.github.com>Restricting access to packer generated VM to agent IP Address: 40.77.40.242
Error: open /images/linux/scripts/base/configure-legacy-ssh.sh: The system cannot find the path specified.

  on D:\a\1\virtual-environments\images\linux\ubuntu2204.pkr.hcl line 148:
  (source code not available)

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

latest (main)

### Repro steps

I'm running GenerateResourcesAndImage in a pipeline but I'm not sure where it matters this is run.

**Comment by al-cheb** [comment]
@jeffpuckett, Would you like to publish a PR?

**Comment by al-cheb** [comment]
@jeffpuckett, you should update packer version to 1.8.1 and temporary use https://github.com/actions/virtual-environments/pull/5645 branch.
