### ISSUE TITLE
Windows 2016 removal

### ISSUE THREAD

**Issue by prajwalar97** [actions/virtual-environments#5637]
### Description

Please confirm will Azure devops provide support of vs2017-win2016 for self-hosted agents after June 30.

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [X] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Please confirm will Azure devops provide support of vs2017-win2016 for self-hosted agents after June 30.

### Repro steps

Please confirm will Azure devops provide support of vs2017-win2016 for self-hosted agents after June 30.

**Comment by al-cheb** [comment]
You can find the answer - https://github.com/actions/virtual-environments/issues/5403#issuecomment-1132804918
