### ISSUE TITLE
Update xcpretty

### ISSUE THREAD

**Issue by arielelkin** [actions/virtual-environments#5642]
### Tool name

xcpretty

### Tool license

MIT

### Add or update?

- [X] Add
- [X] Update

### Desired version

Using a different fork

### Brief description of tool

The macOS runners have xcpretty [pre-installed as an Xcode support tool](https://github.com/actions/virtual-environments/blob/main/images/macos/macos-12-Readme.md#xcode-support-tools). 

That version of xcpretty is four years old and missing support for multiple new Xcode 13 features. 

Please replace the original xcpretty with this fork of xcpretty, which is actively maintained and has support for new Xcode features:
https://github.com/Lightricks/xcpretty

### URL for tool's homepage

https://github.com/xcpretty/xcpretty

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [X] macOS 10.15
- [X] macOS 11
- [X] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Can this tool be installed during the build?

```bash
sudo gem install xcpretty
```

### Tool installation time in runtime

60 seconds

### Are you willing to submit a PR?

yes

**Comment by al-cheb** [comment]
@arielelkin, we will take a look at it, but we install xcpretty as part of `xcode-install` gem and it has a lot of dependencies.

**Comment by miketimofeev** [comment]
@arielelkin xcpretty is already installed on the macOS images. I'm going to close the issue.
Feel free to contact us if you have any concerns.
Thank you!

**Comment by arielelkin** [comment]
@miketimofeev This issue is about updating the currently installed version of xcpretty. Please re-open. 

@al-cheb The fork of xcpretty which I'm referring to can be installed with gem too. What would be the issue?

**Comment by miketimofeev** [comment]
@arielelkin sorry, haven't paid attention to the fork. The installation process is quite different for such non-standard gems. Are you able to install it in runtime? I've got an error
```bash
gem cleanup xcpretty
gem install specific_install
gem specific_install https://github.com/Lightricks/xcpretty
```
```
Invalid gemspec in [/usr/local/lib/ruby/gems/2.7.0/specifications/xcpretty-0.3.0.gemspec]: /usr/local/lib/ruby/gems/2.7.0/specifications/xcpretty-0.3.0.gemspec:44: syntax error, unexpected `end', expecting end-of-input
/usr/local/lib/ruby/site_ruby/2.7.0/rubygems.rb:278:in `find_spec_for_exe': can't find gem xcpretty (>= 0.a) with executable xcpretty (Gem::GemNotFoundException)
	from /usr/local/lib/ruby/site_ruby/2.7.0/rubygems.rb:297:in `activate_bin_path'
	from /usr/local/lib/ruby/gems/2.7.0/bin/xcpretty:25:in `<main>'
```

**Comment by miketimofeev** [comment]
@arielelkin yeah, updating rubygem helps, however, we can't install the latest version due to the issue with the old CLAide package that comes from Xcode-install. There is a PR with the fix, but since it's the same xcpretty repo not sure if it will be merged at all https://github.com/xcpretty/xcode-install/pull/454

**Comment by miketimofeev** [comment]
@arielelkin The issue preventing easy xcpretty installation has been fixed and the new images are deployed, however, Lightricks/xcpretty is also not updated for more than two years so we are not going to change the official package to the fork. Please use this snippet to install the fork in runtime, it takes only 3 seconds. Thank you!
```bsah
gem cleanup xcpretty
gem install specific_install
gem specific_install https://github.com/Lightricks/xcpretty
```
