### ISSUE TITLE
Update Python to 3.11.0 beta 2

### ISSUE THREAD

**Issue by davidfstr** [actions/virtual-environments#5654]
### Tool name

Python

### Tool license

https://github.com/python/cpython/blob/main/LICENSE

### Add or update?

- [ ] Add
- [X] Update

### Desired version

3.11.0 beta 2

### URL for tool's homepage

https://www.python.org/downloads/release/python-3110b2/

### Virtual environments affected

- [X] Ubuntu 18.04
- [X] Ubuntu 20.04
- [X] Ubuntu 22.04
- [X] macOS 10.15
- [X] macOS 11
- [X] macOS 12
- [X] Windows Server 2019
- [X] Windows Server 2022

### Are you willing to submit a PR?

Yes, if there are existing instructions for updating to a new Python version

**Comment by al-cheb** [comment]
@davidfstr,  Python 3.11.0-beta-2 has been published - https://github.com/actions/python-versions/releases/tag/3.11.0-beta.2-2415919900

**Comment by davidfstr** [comment]
@al-cheb , Python 3.11.0-beta-2 has not been added to [versions-manifest.json](https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json) and therefore is not discoverable by [actions/setup-python@v3](https://github.com/actions/setup-python). So I think there is still some work required.
