### ISSUE TITLE
CHROMEWEBDRIVER on mac-os doesn't have accessible file permissions

### ISSUE THREAD

**Issue by Mcgurk-Adam** [actions/virtual-environments#5655]
### Description

When trying to use the file held at the CHROMEWEBDRIVER environment variable on the `macos-11` runner, I am getting the following error:
```bash
node:events:505
      throw er; // Unhandled 'error' event
      ^

Error: spawn /usr/local/Caskroom/chromedriver/101.0.4951.41 EACCES
    at Process.ChildProcess._handle.onexit (node:internal/child_process:283:19)
    at onErrorNT (node:internal/child_process:478:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (node:internal/child_process:289:12)
    at onErrorNT (node:internal/child_process:478:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  errno: -13,
  code: 'EACCES',
  syscall: 'spawn /usr/local/Caskroom/chromedriver/101.0.4951.41',
  path: '/usr/local/Caskroom/chromedriver/101.0.4951.41',
  spawnargs: [ '--port=49[24](https://github.com/Mcgurk-Adam/appt-runner/runs/6675390302?check_suite_focus=true#step:3:25)2' ]
}
```

I have tried `sudo chmod 755` the file, and it runs successfully, but I still get the error here

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 10.15
- [X] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

https://github.com/Mcgurk-Adam/appt-runner/runs/6675390302?check_suite_focus=true

### Expected behavior

I would expect to not have access issues trying to use the built-in chromedriver.

### Actual behavior

The chromedriver doesn't have accessible permissions, and so trying to instantiate my selenium service fails because it can't access the chromedriver.

### Repro steps

Try to use the file held at the CHROMEWEBDRIVER environment variable to instantiate a selenium service, and it will fail.

**Comment by al-cheb** [comment]
Hey @Mcgurk-Adam,
We will take a look at it.

**Comment by al-cheb** [comment]
Hey @Mcgurk-Adam,
I see in your code you pass a folder to the node app instead of a path to a binary chromedriver file.


https://github.com/actions/virtual-environments/blob/main/images/macos/macos-11-Readme.md#environment-variables-1

Name | Value
-- | --
CHROMEWEBDRIVER | /usr/local/Caskroom/chromedriver/102.0.5005.61

Fix:

```
- name: Run Integration Test
  run: |
    export CHROMEWEBDRIVER="${CHROMEWEBDRIVER}/chromedriver"
    ./ci/test-get-schedule.sh
```

**Comment by Mcgurk-Adam** [comment]
Ah, I see, that definitely did get me fixed up, thank you and my apologies! I thought the docs were pointing to the actual executable, and not the folder where the executable named `chromedriver` was stored. Thank you so much!
