### ISSUE TITLE
Add CPython 2.6 to actions/python-versions

### ISSUE THREAD

**Issue by gamer191** [actions/virtual-environments#5674]
### Tool name

CPython 2.6

### Tool license

I believe it's the PSF license, but it might be wrong

### Add or update?

- [X] Add
- [ ] Update

### Desired version

2.6.9

### Approximate size

Unknown for Python 2.6.9. The x86-64 MSI of Version 2.6.6 is 14.8MB

### URL for tool's homepage

https://www.python.org

### Platforms where you need the tool

- [ ] Azure DevOps
- [X] GitHub Actions

### Virtual environments where you need the tool

- [x] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

**Comment by miketimofeev** [comment]
@gamer191 please open an issue in the https://github.com/actions/setup-python

**Comment by gamer191** [comment]
> @gamer191 please open an issue in the https://github.com/actions/setup-python

Sorry, my bad
