### ISSUE TITLE
Can't use 'tar -xzf'

### ISSUE THREAD

**Issue by ramykl** [actions/virtual-environments#5675]
### Description

Builds are regularly (but not always) failing with 
`Can't use 'tar -xzf' extract archive file: /home/runner/work/_actions/_temp_e69d87bb-0ed5-4a0a-9086-ffc937203f44/e3ee3c76-94a8-4a44-9396-63d8da0dceac.tar.gz. return code: 2.`

<img width="1059" alt="Screen Shot 2022-06-02 at 10 27 21 AM" src="https://user-images.githubusercontent.com/5079228/171588260-001d29ef-9939-43a3-a82f-154ab8f89a33.png">

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions

### Virtual environments affected

- [ ] Ubuntu 18.04
- [X] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Environment: ubuntu-20.04
Version: 20220529.1
Included Software: https://github.com/actions/virtual-environments/blob/ubuntu20/2022052[9](https://github.com/Milkywire/enterprise/runs/6704797523?check_suite_focus=true#step:1:10).1/images/linux/Ubuntu2004-Readme.md
Image Release: https://github.com/actions/virtual-environments/releases/tag/ubuntu20%2F20220529.1

### Is it regression?

yes, 20220515.1

### Expected behavior

Able to Untar the file during setup without error 
<img width="1126" alt="image" src="https://user-images.githubusercontent.com/5079228/171589230-60929e26-e6e7-40f4-b6c0-8962f8151240.png">

### Actual behavior

Unable to complete set up job as tar fails 
<img width="1099" alt="Screen Shot 2022-06-02 at 10 30 45 AM" src="https://user-images.githubusercontent.com/5079228/171588892-2a4c94e5-2d0b-4390-8d01-a5030c17ac97.png">

### Repro steps

1. Create github action with a couple of steps
2. Run github action

**Comment by al-cheb** [comment]
Hey @ramykl,
We will take a look at it.

**Comment by azarudeena** [comment]
Same here 

Referencing similar issues reported in different relevant repos 
https://github.com/actions/runner/issues/1923

https://github.com/actions/cache/issues/811

**Comment by domdfcoding** [comment]
I'm seeing this on macOS as well, although not for all jobs:

https://github.com/repo-helper/mkrecipe/runs/6705229831?check_suite_focus=true

**Comment by azarudeena** [comment]
This seems like majorly a infrastructure issue. some Virtual environments are able to continue with the run. but some are failing. Been hitting that rerun like crazy to catch the right pool

**Comment by al-cheb** [comment]
@ramykl , @ramykl , @domdfcoding - https://github.com/actions/cache/issues/811#issuecomment-1144627411 . Nothing we can do from our side. Close as external issue.
