### ISSUE TITLE
macos-11 builds fail when using xcode 13.2

### ISSUE THREAD

**Issue by acoats2** [actions/virtual-environments#5678]
### Description

This morning we had breaking builds with the following message when using macos-11 agents:
`xcodebuild: error: SDK "/Applications/Xcode_13.2.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk" cannot be located.`

I suspect this pr is the root cause:  https://github.com/actions/virtual-environments/pull/5638.  According to the mentioned issue https://github.com/actions/virtual-environments/issues/5463 there should have been no impact to customers using 13.2 as we should have been pointed to 13.2.1 automatically.

Manually bumping our xcode version to 13.2.1 did resolve the issue, but if I understand correctly we shouldn't have had to do this.

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 10.15
- [X] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Azure DevOps
macos-11 version 20220530.2

### Is it regression?

20220523.2

### Expected behavior

Even though we were targetting xcode 13.2 our builds should have simply started using 13.2.1 with no changes as per https://github.com/actions/virtual-environments/issues/5463.

### Actual behavior

Builds broke

### Repro steps

Execute a build on the macos agent while targeting xcode 13.2.

**Comment by al-cheb** [comment]
Hey @acoats2,
We will take a look at it.

**Comment by mikhailkoliada** [comment]
@acoats2 Hi

Few questions:

1.) Could you please provide a minimal repro steps so we could reproduce the problem?
2.) What happens if you switch to xcode 13.2.1

For now I see that the files in question are placed as expected

![image](https://user-images.githubusercontent.com/88318005/171672836-55cf278a-515e-4a23-8764-419ff6911301.png)

**Comment by acoats2** [comment]
Hello @mikhailkoliada - 

Bumping our build to use 13.2.1 does in fact resolve our problem.  I just wasn't expecting to have to do this manually given the work item I linked.

But, likely the devil is in the details.

This is a xamarin.ios application and so we do 2 things in order to ensure the correct xcode version is used.
1.  xcode-select
  `sudo xcode-select --switch /Applications/Xcode_$(XcodeVersion).app/Contents/Developer`
2.  We create the Settings.plist with the correct AppleSdkRoot so msbuild will use the expected version of xcode.
  `echo '<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd"><plist version="1.0"><dict><key>AppleSdkRoot</key><string>/Applications/Xcode_$(XcodeVersion).app</string></dict></plist>' > /Users/runner/Library/Preferences/Xamarin/Settings.plist`
  
Then we use the [Xamarin.IOS task](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/xamarin-ios?view=azure-devops) to perform the build.

Likely the problem is with step 2 above.  You can see the technique being used in various places across the internet, and I believe it is what MS used to recommend.  We've been using this for quite some time.

I just found the [latest recommendation](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops&tabs=yaml#xamarin) does it slightly differently.  

```
In case you are using a non-default version of Xcode for building your Xamarin.iOS or Xamarin.Mac apps, you should additionally execute this command line:

/bin/bash -c "echo '##vso[task.setvariable variable=MD_APPLE_SDK_ROOT;]'$(xcodeRoot);sudo xcode-select --switch $(xcodeRoot)/Contents/Developer"

where $(xcodeRoot) = /Applications/Xcode_13.2.app
```

I haven't tried to set the vso task variable 'MD_APPLE_SDK_ROOT' in my pipeline yet to see if this issue recreates.

**Comment by mikhailkoliada** [comment]
@acoats2 

I have no idea if MS Build can handle symlinks correctly, that is why I recommend you switching to 13.2.1 directly (you would end up like that in anyway even with the symlink). 

If MD_APPLE_SDK_ROOT works for you please let us know.

**Comment by mikhailkoliada** [comment]
@acoats2 I have discussed this issue with other colleagues of mine and we have not found an alternative way here other that I have described above, so I am going to close the issue. Feel free to reach us out any time later if you have questions left.
