### ISSUE TITLE
[Ubuntu] AWS CLI on Ubuntu18 image will be upgraded to V2 on June 20

### ISSUE THREAD

**Issue by miketimofeev** [actions/virtual-environments#5679]
### Breaking changes

The AWS Command Line Interface (CLI) will be upgraded from V1 to V2.

### Target date

The propagation will start on June, 20 and will take 3-4 days.

### The motivation for the changes

AWS CLI v1 installer stopped working on Ubuntu18 as it now requires Python 3.7 ([changelog](https://github.com/aws/aws-cli/blob/develop/CHANGELOG.rst)) while Ubuntu18 has python 3.6. V2 installer doesn't require system python to operate so can be installed on the Ubuntu18.

### Possible impact

If your workflow depends on AWS CLI V1 it can be broken.

### Platforms affected

- [X] Azure DevOps
- [X] GitHub Actions

### Virtual environments affected

- [X] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Mitigation ways

Install AWS CLI V1 1.25 which supports python 3.6
```bash
sudo rm /usr/local/bin/aws
sudo rm /usr/local/bin/aws_completer
sudo rm -rf /usr/local/aws-cli
curl https://s3.amazonaws.com/aws-cli/awscli-bundle-1.24.10.zip -4 -sL -o '/tmp/awscli-bundle.zip'
unzip -qq /tmp/awscli-bundle.zip -d /tmp
sudo python3 /tmp/awscli-bundle/install -i /usr/local/aws -b /usr/local/bin/aws
```

**Comment by mikhailkoliada** [comment]
Changes will be deployed next week.

**Comment by mikhailkoliada** [comment]
Deployed.

**Comment by Oatelaus** [comment]
I hope it's okay to document here, but this caused issues with our pipelines and we weren't aware of this change. If you come across an error which looks like the following, it might be because of IMDS.

https://github.com/aws/aws-cli/issues/5623

https://florian.ec/blog/github-actions-awscli-errors/

**Comment by bryevdv** [comment]
Seem to be having the same issues as @Oatelaus
