### ISSUE TITLE
Nuget restore fails on Ubuntu-20.04 with ImageVersion 20220529.1

### ISSUE THREAD

**Issue by dotlegacy** [actions/virtual-environments#5681]
### Description

The same dotnet code, which targets net6.0 worked when it was on the previous image 20220515.1 (which I had a build that passed a week ago) and fails on the newly release image 20220529.1 with a build that ran today.  It is somehow defaulting to net5.0, which make sense that it fails.  The pipeline is using Nuget version 6.2.0.  The only workaround that I was able to use to get it to work was to use the UseDotNet@2 task and force it to use version 6.0.x

Error message:
/usr/bin/mono /opt/hostedtoolcache/NuGet/6.2.0/x64/nuget.exe restore /home/vsts/work/1/s/xxxxx.sln -Verbosity Detailed -NonInteractive -ConfigFile /home/vsts/work/1/Nuget/tempNuGet_42628.config
NuGet Version: 6.2.0.146
MSBuild auto-detection: using msbuild version '15.0' from '/usr/lib/mono/msbuild/15.0/bin'. Use option -MSBuildVersion to force nuget to use a specific version of MSBuild.
MSBuild P2P timeout [ms]: 120000
/usr/bin/msbuild "/tmp/NuGetScratch/fk6blu2e.geo.nugetinputs.targets" /t:GenerateRestoreGraphFile /nologo /nr:false /v:q /p:NuGetRestoreTargets="/tmp/NuGetScratch/gok36zzu.a0w.nugetrestore.targets" /p:RestoreUseCustomAfterTargets="True" /p:RestoreTaskAssemblyFile="/opt/hostedtoolcache/NuGet/6.2.0/x64/nuget.exe" /p:RestoreSolutionDirectory="/home/vsts/work/1/s/" /p:RestoreConfigFile="/home/vsts/work/1/Nuget/tempNuGet_42628.config" /p:SolutionDir="/home/vsts/work/1/s/" /p:SolutionName="xxxx" /p:RestoreBuildInParallel="False" /p:RestoreUseSkipNonexistentTargets="False"
NuGet.CommandLine.ExitCodeException: Exception of type 'NuGet.CommandLine.ExitCodeException' was thrown.
  at NuGet.CommandLine.MsBuildUtility.GetProjectReferencesAsync (NuGet.CommandLine.MsBuildToolset msbuildToolset, System.String[] projectPaths, System.Int32 timeOut, NuGet.CommandLine.IConsole console, System.Boolean recursive, System.String solutionDirectory, System.String solutionName, System.String restoreConfigFile, System.String[] sources, System.String packagesDirectory, NuGet.ProjectModel.RestoreLockProperties restoreLockProperties) [0x00489] in <af8534eafb63495d8371e5bcb1c62bd9>:0 
  at NuGet.CommandLine.RestoreCommand.GetDependencyGraphSpecAsync (System.String[] projectsWithPotentialP2PReferences, System.String solutionDirectory, System.String solutionName, System.String configFile) [0x0012b] in <af8534eafb63495d8371e5bcb1c62bd9>:0 
  at NuGet.CommandLine.RestoreCommand.DetermineInputsFromMSBuildAsync (NuGet.CommandLine.RestoreCommand+PackageRestoreInputs packageRestoreInputs) [0x000e5] in <af8534eafb63495d8371e5bcb1c62bd9>:0 
/usr/share/dotnet/sdk/5.0.408/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.TargetFrameworkInference.targets(141,5): error NETSDK1045: The current .NET SDK does not support targeting .NET 6.0.  Either target .NET 5.0 or lower, or use a version of the .NET SDK that supports .NET 6.0. [/home/vsts/work/1/s/xxxx1.csproj]
/usr/share/dotnet/sdk/5.0.408/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.TargetFrameworkInference.targets(141,5): error NETSDK1045: The current .NET SDK does not support targeting .NET 6.0.  Either target .NET 5.0 or lower, or use a version of the .NET SDK that supports .NET 6.0. [/home/vsts/work/1/s/xxxx2.csproj]

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions

### Virtual environments affected

- [ ] Ubuntu 18.04
- [X] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

20220529.1

### Is it regression?

No

### Expected behavior

Nuget restore should have used the latest net6.0

### Actual behavior

It used net5.0

### Repro steps

Unfortunately, the older image is unavailable; so unable to replicate

**Comment by dotlegacy** [comment]
I have a second .net 6.0 project that ran successfully on 5/26 and has now failed with the same error

**Comment by al-cheb** [comment]
Hey @dotlegacy,
Please prove a test repo and steps to reproduce the issue.

**Comment by TordJoranger** [comment]
Hi, same issue. Workaround with  - task: UseDotNet@2  version: '6.0.x'

**Comment by MatiKloster** [comment]
Same issue... started failing out of nowhere

**Comment by msavara** [comment]
> Hi, same issue. Workaround with - task: UseDotNet@2 Edit: nvm, saw you already wrote this.

How it's possible to use UseDotNet? :) i have github actions and not azure devops :) it's somehow possible to use that also in actions?

**Comment by al-cheb** [comment]
> > Hi, same issue. Workaround with - task: UseDotNet@2 Edit: nvm, saw you already wrote this.
> 
> How it's possible to use UseDotNet? :) i have github actions and not azure devops :) it's somehow possible to use that also in actions?

You could use [actions/setup-dotnet](https://github.com/actions/setup-dotnet) task install .Net in runtime.

**Comment by msavara** [comment]
> > > Hi, same issue. Workaround with - task: UseDotNet@2 Edit: nvm, saw you already wrote this.
> > 
> > 
> > How it's possible to use UseDotNet? :) i have github actions and not azure devops :) it's somehow possible to use that also in actions?
> 
> You could use [actions/setup-dotnet](https://github.com/actions/setup-dotnet) task to install .Net in runtime.

I'm using that. But with this i have an issue which was mentioned above. 

![image](https://user-images.githubusercontent.com/34938369/172829535-5d26084a-56b6-4506-8587-34e72c18bcc9.png)

**Comment by al-cheb** [comment]
@dotlegacy, Does the issue still reproduce?

**Comment by MatiKloster** [comment]
> @dotlegacy, Does the issue still reproduce on the recent image?

Sandly, the problem is still happening for me

**Comment by al-cheb** [comment]
@dotlegacy, Any updates?
@MatiKloster, Could you share a repo with minimal steps how to reproduce the issue?

**Comment by al-cheb** [comment]
@MatiKloster, Thank you. If we swap nuget and .net installation step it's working:

```
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
          
      - name: Restore NuGet package
        run:
          nuget restore ./test/NugetRestoreFail.csproj
      - name: Run Unit Test suite
        run: dotnet test ./test/NugetRestoreFail.csproj
```
![image](https://user-images.githubusercontent.com/47745270/176205457-3706ff00-3463-45d4-a458-1a6d3c102484.png)

**Comment by MatiKloster** [comment]
> @MatiKloster, Thank you. If we swap nuget and .net installation step it's working:
> 
> ```
>       - name: Setup .NET Core
>         uses: actions/setup-dotnet@v1
>         with:
>           dotnet-version: '6.0.x'
>           
>       - name: Restore NuGet package
>         run:
>           nuget restore ./test/NugetRestoreFail.csproj
>       - name: Run Unit Test suite
>         run: dotnet test ./test/NugetRestoreFail.csproj
> ```
> 
> ![image](https://user-images.githubusercontent.com/47745270/176205457-3706ff00-3463-45d4-a458-1a6d3c102484.png)

Exactly, that's what we did

But do you how this file stopped working?

**Comment by dotlegacy** [comment]
@MatiKloster thanks for setting up the test repo; been swamp lately at work.

I have mentioned that it was picking up net5.0 even though net6.0 is installed in the Ubuntu image used by Azure DevOps.  I compared the previous working image with the broken one but couldn't find the cause.  There was a small change in the nuget version and if I recalled correctly, I tested the broken image with the nuget version on the working image but that didn't work as well.

I will test again on the new image and update.

**Comment by al-cheb** [comment]
I am planning close the thread as external.

Workaround:
1. Use [setup-dotnet](https://github.com/actions/setup-dotnet) / [UseDotNet@2](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/tool/dotnet-core-tool-installer?view=azure-devops)
2. Create [global.json](https://docs.microsoft.com/en-us/dotnet/core/tools/global-json)
3. Replace nuget restore to dotnet restore

**Comment by msavara** [comment]
Same issue as i had before. Just changed from .NET 6 to .NET 7 and same issue.
