### ISSUE TITLE
Github Actions now break, since Visual Studio (v8.*) on Mac has been renamed to "Visual Studio 2019.app"

### ISSUE THREAD

**Issue by CartBlanche** [actions/virtual-environments#5682]
### Description

@al-cheb @miketimofeev Seem you fixed the macOS-12 image for VS2022, but now the macOS-11 image is broken for VS2019

/Users/runner/.nuget/packages/monodevelop.addins/0.4.7/build/MonoDevelop.Addins.targets(76,5): error : Could not find a global instance of Visual Studio for Mac or MonoDevelop. Try providing an explicit value with MDBinDir. [/Users/runner/work/VS_Mac_Meadow_Extension/VS_Mac_Meadow_Extension/main/VS4Mac_Meadow_Extension/Meadow.Sdks.IdeExtensions.Vs4Mac.csproj]

I see you've rename the VS2019 app to "Visual Studio 2019.app". So from a Github Action how do we specify that specific VS version for a particular build?

### Platforms affected

- [ ] Azure DevOps
- [ ] GitHub Actions

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 10.15
- [X] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

https://github.com/WildernessLabs/VS_Mac_Meadow_Extension/runs/6712367837?check_suite_focus=true

### Is it regression?

Yes, It was working last before the app rename happened

### Expected behavior

Well I wish our build didn't suddenly break.

### Actual behavior

It breaks our builds and I suspect anyone's build who used to use VS 8.* on Mac to build their projects.

### Repro steps

on macOS-11 run the following command on a C# project.

`msbuild MySpecial.csproj /t:Build /p:Configuration=Release /p:CreatePackage=true`

**Comment by al-cheb** [comment]
Hey @CartBlanche,
You could pick up VS2019 using snippet below:

```
- name: Set VS2019 
  run: |
        mv "/Applications/Visual Studio.app" "/Applications/Visual Studio 2022.app"
        mv "/Applications/Visual Studio 2019.app" "/Applications/Visual Studio.app"
        /usr/libexec/PlistBuddy -c 'Print CFBundleVersion' '/Applications/Visual Studio.app/Contents/Info.plist'
```

![image](https://user-images.githubusercontent.com/47745270/171803944-4f8748a6-7f32-4231-8f84-fa05a0a326d3.png)

_It breaks our builds and I suspect anyone's build who used to use VS 8.* on Mac to build their projects._  _ That's why we post an announce that customers could validate and migrate their applications due to some breaking changes.

**Comment by CartBlanche** [comment]
@al-cheb Thanks, I'll give that a try and if it works I'll report back. 
Maybe consider having an environment variable we can set, rather than having to rename the apps?

**Comment by miketimofeev** [comment]
@CartBlanche we are going to remove VS 8.* instance from the images in a few weeks or so giving users time to adapt their workflows to use VS2022. I'm not sure having the variable will help as the Visual Studio is being observed by the default path anyway.

**Comment by CartBlanche** [comment]
@miketimofeev if you remove 8.* totally, I don't believe VS2022 will be able to build extensions for the 8.* IDE, they use totally different nugets and the new one isn't backwards compatible. I'll have to talk with the VS4Mac developers if they are aware of the removal of 8.* from images and what customers like us should do. Not all our customers will be jumping to VS2022 soon, AFAIK.

**Comment by CartBlanche** [comment]
@miketimofeev I've spoken to the VS for Mac devs  ( @mrward and sent a message to @jmatthiesen)  and If GitHub removes VS2019 from their instances, any extension developer who uses the VS2019 add-maker, will no longer be able to support VS2019/v8.* IDE. It isn't included in the VS2022, so project won't build with that either. Most of the Wilderness Labs customers are still on VS2019 on Mac and I suspect that might be the case for most MS customers too, at least for the next 6-9 months. Can the removal of VS2019 from instances be delayed at least 6 months while customers move to VS2022?

**Comment by jmatthiesen** [comment]
Hey @miketimofeev - I'm the Product Manager on Visual Studio for Mac and agree this would be good to maintain Visual Studio 2019 for Mac on these images for 6 months or so, to enable customers to migrate. Feel free to email me if you have some questions we should discuss outside the thread, though! jomatthi -at microsoft.com.

**Comment by miketimofeev** [comment]
@CartBlanche @jmatthiesen thanks for the update! We can keep both versions for any timeframe if needed, this is not a problem. Is it ok to have VS for Mac 2019 in such a custom path or there could be some better solution to install both versions side by side?

**Comment by mrward** [comment]
Existing VS Mac 2019 customers will have it in the `/Applications/Visual Studio.app` directory if they have never installed VS Mac 2022.

The VS Mac 2022 installer will move the VS Mac 2019 install to `/Applications/Visual Studio (2019).app` since VS Mac 2022 will be installed into `/Applications/Visual Studio.app`.

Not sure if that helps here with any custom path for VS Mac 2019 in the github action or not :) Presumably your 'mv script' can be used if the old `/Applications/Visual Studio.app` location for VS Mac 2019 is needed.

**Comment by CartBlanche** [comment]
@miketimofeev, @jmatthiesen,  @mrward The `mv *` work around mentioned here - https://github.com/actions/virtual-environments/issues/5682#issuecomment-1145654760 works for our Github CI and I assume would also work for others. It just needs to be mentioned in the release imaging docs, IMHO, so that people don't need to find this issue to find out what needs to be done to get up and running quickly.

**Comment by miketimofeev** [comment]
@CartBlanche good idea, opened a PR with software report generator update here https://github.com/actions/virtual-environments/pull/5701

**Comment by CartBlanche** [comment]
Thanks again @miketimofeev, for sorting all this out quickly. Greatly appreciated!
