### ISSUE TITLE
Ubuntu2204: Error: Missing expression var.run_validation_diskspace from arguments

### ISSUE THREAD

**Issue by mzarglis** [actions/virtual-environments#5690]
### Description

When trying to build ubuntu 2204 image i get:

Ubuntu2204: Error: Missing expression var.run_validation_diskspace from arguments

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

https://dev.azure.com/michaelzarglis/ado-build-agent-images/_build/results?buildId=236&view=logs&j=011e1ec8-6569-5e69-4f06-baf193d1351e&t=5431112d-2b61-5a5f-7042-ef698f761043

### Is it regression?

No

### Expected behavior

Build to work

### Actual behavior

Build VM job exits with following error

```
Error: Missing expression

  on <value for var.run_validation_diskspace from arguments> line 1:
  (source code not available)

Expected the start of an expression, but found the end of the file.


##[error]PowerShell exited with code '1'.
```

### Repro steps

Pull latest from main.
Run ubuntu2204 build pipeline

**Comment by igorboskovic3** [comment]
Hi @mzarglis we will take a look, thank you for reporting this one.

**Comment by al-cheb** [comment]
@mzarglis, we define the environment variable `RUN_VALIDATION_FLAG` to true before running a pipeline. 

![image](https://user-images.githubusercontent.com/47745270/172113688-d3599291-4896-482c-9db6-c6708d2993b5.png)

**Comment by mzarglis** [comment]
@al-cheb Thanks added this to my var group and it is working. I have one more question that i don't see any documentation for around the Create release for VM deployment stage that calls create-release.ps 

```
   [UInt32] [Parameter (Mandatory)] $BuildId,
    [String] [Parameter (Mandatory)] $Organization,
    [String] [Parameter (Mandatory)] $Project,
    [String] [Parameter (Mandatory)] $ImageName,
    [String] [Parameter (Mandatory)] $DefinitionId,
    [String] [Parameter (Mandatory)] $AccessToken
```
What exactly is $DefinitionID? and i assume $AccessToken is a personal access token?

I see the documentation for the API call here https://docs.microsoft.com/en-us/rest/api/azure/devops/release/releases/create?view=azure-devops-rest-6.0

But this step still fails for me i assume i need to create a release first but there is not really any documentation i could find around this. Any light you can shine on this would be greatly appreciated. I would be happy to work on a PR expanding documentation in this area once i understand what exactly it does.

**Comment by al-cheb** [comment]
Feel free to remove this step from CI because it is not relevant for image generation process. The [create-release.ps1](https://github.com/actions/virtual-environments/blob/main/images.CI/linux-and-win/create-release.ps1) script is used only for an internal pipeline that's why we don't have any documentation about.

**Comment by mzarglis** [comment]
@al-cheb  makes sense thanks again!
