### ISSUE TITLE
Add tfenv

### ISSUE THREAD

**Issue by sburns** [actions/virtual-environments#57]
**Tool information**
- Tool name: tfenv
- Add or update? add
- Desired version: latest
- Approximate size:
- If this is an add request:
  - Brief description of tool: tfenv makes it easier to install a specific version of terraform at runtime
  - URL for tool's homepage: github.com/tfutils/tfenv

**Virtual environments affected**
- [ ] macOS 10.14
- [x] Ubuntu 16.04 LTS
- [x] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Can this tool be installed during the build?**
Installation is a git-clone of `https://github.com/tfutils/tfenv.git` and then appropriately putting it into PATH using `echo ::add-path::$HOME/.tfenv/bin`.

This yaml is now working in my actions:

```
      - name: Install tfenv
        run: |
          git clone https://github.com/tfutils/tfenv.git ~/.tfenv
          echo ::add-path::$HOME/.tfenv/bin
```

You might go so far as _not_ include any specific version of terraform? Obviously backwards-incompatible, but _potentially_ better to make users specifically install what they need than depend on what is provided, whose version may float and produce awful incompatible state errors.

**Are you willing to submit a PR?**
👍

**Comment by sburns** [comment]
@kaylangan Is this on the roadmap? The robots are attacking :)

**Comment by alepauly** [comment]
@sburns sorry it too so long to get to this. I don't think we should bake tfenv into the virtual-environments at this time. Seems pretty straightforward and a good candidate for a `setup`-style Action, not sure if have considered that. Thanks for the suggestion.
