### ISSUE TITLE
Add support for JAVA 11

### ISSUE THREAD

**Issue by pramodKarande** [actions/virtual-environments#5708]
### Tool name

Java

### Tool license

free

### Add or update?

- [X] Add
- [ ] Update

### Desired version

java 11

### URL for tool's homepage

https://www.java.com/en/

### Platforms where you need the tool

- [X] Azure DevOps
- [ ] GitHub Actions

### Virtual environments where you need the tool

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [X] macOS 10.15
- [X] macOS 11
- [X] macOS 12
- [X] Windows Server 2019
- [ ] Windows Server 2022

**Comment by al-cheb** [comment]
We already pre-install java 11 on Windows and macOS . If you need to set up java 11 by default you could use the [setup-java](https://github.com/actions/setup-java) task as preferable way.
