### ISSUE TITLE
New Node version wth Npm version causes devops pipeline to fail due to npm bug

### ISSUE THREAD

**Issue by lgriveras** [actions/virtual-environments#5716]
### Description

Our devops pipeline is reporting a warning due to a bug from npm on the node and npm versions used in this new release (see this issue: https://github.com/npm/cli/issues/4980). It is blocking our CI pipeline due to having our policies to not allow warnings even when successful. Using vs 2017 is a workaround we have right now but it is soon to be removed so it is not really a good option for us. We also tried downgrading npm and node and seems it doesn't fix the issue. Our pipeline was working until this PR was merged and released.

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [X] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Environment: windows-2019
Version: 20220606.1
Included Software: https://github.com/actions/virtual-environments/blob/win19/20220606.1/images/win/Windows2019-Readme.md
Image Release: https://github.com/actions/virtual-environments/releases/tag/win19%2F20220606.1
Virtual Environment Provisioner
Current image version: '20220606.1'

### Is it regression?

Yes.
Working Environment:
Environment: windows-2019 | Version: 20220522.1 | Included Software: https://github.com/actions/virtual-environments/blob/win19/20220522.1/images/win/Windows2019-Readme.md | Image Release: https://github.com/actions/virtual-environments/releases/tag/win19%2F20220522.1

### Expected behavior

For the build to not throw an npm warning and to be successful

### Actual behavior

Throws npm warning:
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
 
and fails because a warning is thrown

### Repro steps

Run any npm command like `npm -v` in pipeline

**Comment by al-cheb** [comment]
I think as a temporary workaround you could use recommendation - https://github.com/npm/cli/issues/4980#issuecomment-1145334203:

```
$npmPath = "C:\Program Files\nodejs\npm.cmd"
(Get-Content $npmPath -Raw).replace('prefix -g', 'prefix --location=global') | Out-File $npmPath -Encoding ascii
```

![image](https://user-images.githubusercontent.com/47745270/173008930-40e56c9c-e065-4841-8ac8-fdfb7f76226d.png)

**Comment by miketimofeev** [comment]
@lgriveras please use either the workaround provided by @al-cheb or consider using https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/tool/node-js?view=azure-devops task to install 16.15.0 node version in runtime 
![image](https://user-images.githubusercontent.com/48208649/173019287-3064300a-a69d-40e5-a977-07dce46cfe7e.png)
Once the new Node version with fixed npm is released it will be updated on the images as well.
I'm going to close the issue. Feel free to contact us if you have any concerns.
Thank you!

**Comment by lgriveras** [comment]
Unfortunately, neither of these approaches worked for me. I still get the same problem at the end of my build:
<img width="671" alt="image" src="https://user-images.githubusercontent.com/63885913/173081239-be3d5e8b-e9b0-4bba-a33d-a72bdf840c56.png">

**Comment by Steve51D** [comment]
We're also seeing this problem on our Azure DevOps builds.
We build and test against multiple platforms and language versions.
This problem is affecting Node 16.15.1 on all the platforms we currently test against (Windows 2019, Ubuntu 18.04 and MacOS 11)

**Comment by lgriveras** [comment]
@Steve51D Doing these 2 recommended steps together fixed our issue; Maybe it helps you too
