### ISSUE TITLE
Location of vcpkg

### ISSUE THREAD

**Issue by TerensTare** [actions/virtual-environments#573]
In the Windows images, vcpkg is located at C:\vcpkg (mentioned in the .md files here), but the .md files don't mention anything about the location of vcpkg in Linux/MacOSX. Where is it located? Can you please add that information to the corresponding .md files?

**Comment by m-minasyan** [comment]
Hello, @TerensTare.
I think that vcpkg in Linux you can find in this path:
`/usr/local/share/vcpkg`
You can also find the link in the folder:
`/usr/local/bin`

**Comment by TerensTare** [comment]
It seems like `/usr/local/share/vcpkg` is where vcpkg is located. Thanks a lot @m-minasyan ! Happy coding!

**Comment by patrikhuber** [comment]
Is there any platform-independent way to retrieve and use the vcpkg install location in GitHub Actions workflows, for example an environment variable or something like that?

**Comment by patrikhuber** [comment]
I found this https://github.com/actions/runner-images/issues/6376#issuecomment-1304667352, which is probably what I'm looking for.
