### ISSUE TITLE
Add google/bundletool

### ISSUE THREAD

**Issue by nevardreik** [actions/virtual-environments#5751]
### Tool name

google/bundletool

### Tool license

Apache License 2.0

### Add or update?

- [X] Add
- [ ] Update

### Desired version

1.10.0

### Brief description of tool

Bundletool is a tool to manipulate Android App Bundles. The Android App Bundle is a new format for publishing Android apps in app distribution stores such as Google Play.

Bundletool has a few different responsibilities:

Build an Android App Bundle from pre-compiled modules of a project.
Generate an APK Set archive containing APKs for all possible devices.
Extract APK(s) from the APK Set compatible with a given device.
Install APK(s) from the APK Set compatible with a connected device.
Extract device spec from a device as a JSON file.
Add code transparency to an Android App Bundle. Code transparency is an optional code signing mechanism.

Verify code transparency inside an Android App Bundle, APK files or an application installed on a connected device.

### URL for tool's homepage

https://github.com/google/bundletool

### Provide a basic test case to validate the tool's functionality.

```bash
bundletool version
```

### Platforms where you need the tool

- [X] Azure DevOps
- [X] GitHub Actions

### Virtual environments where you need the tool

- [X] Ubuntu 18.04
- [X] Ubuntu 20.04
- [X] Ubuntu 22.04
- [X] macOS 10.15
- [X] macOS 11
- [X] macOS 12
- [X] Windows Server 2019
- [X] Windows Server 2022

### Can this tool be installed during the build?

```bash
brew install bundletool
```

### Tool installation time in runtime

3m 30s

**Comment by AlexanderGitin** [comment]
Hello @nevardreik , we will take a look

**Comment by miketimofeev** [comment]
@nevardreik we wouldn't like to use homebrew bundletool package as it would bring OpenJDK as well.
Please download and use the jar file directly as it's pretty simple and quick:
- windows:
```pwsh
$json = Invoke-RestMethod -Uri "https://api.github.com/repos/google/bundletool/releases/latest"
$downloadUrl = $json.assets.browser_download_url
$filePath = ".\bundletool.jar"
(New-Object System.Net.WebClient).DownloadFile($downloadUrl, $filePath)
java -jar bundletool.jar
```
- macos
```bash
json=$(curl -s "https://api.github.com/repos/google/bundletool/releases/latest")
downloadUrl=$(echo $json | jq -r ".assets | .[].browser_download_url")
curl $downloadUrl -4 -sL -o 'bundletool.jar'
java -jar bundletool.jar version
```
- ubuntu:
```bash
json=$(curl -s https://api.github.com/repos/google/bundletool/releases/latest)
downloadUrl=$(echo $json | jq -r ".assets | .[].browser_download_url")
curl $downloadUrl -4 -sL -o 'bundletool.jar'
java -jar bundletool.jar version
```

I'm going to close the issue. Please feel free to contact us if you have any concerns.
Thank you!
