### ISSUE TITLE
Unix-based agents cannot download build artifacts

### ISSUE THREAD

**Issue by mattleibow** [actions/virtual-environments#5767]
### Description

I have a build here: https://dev.azure.com/xamarin/public/_build/results?buildId=64422&view=logs&j=b5f87e8d-65cd-564c-4ec8-feedcce3d1c8&t=ea3f294e-1129-53ed-3599-2a7255a56ad0&l=11

```
Downloading items from container resource #/15035605/native_android_x86_macos
Downloading artifact native_android_x86_macos from: https://dev.azure.com/xamarin//_apis/resources/Containers/15035605?itemPath=native_android_x86_macos&isShallow=true&api-version=4.1-preview.4
Retrying download of , retry count: 1
Retrying download of , retry count: 2
Retrying download of , retry count: 3
Retrying download of , retry count: 4
Error: in Download container - native_android_x86_macos, so retrying => retries pending  : 1
Downloading items from container resource #/15035605/native_android_x86_macos
Downloading artifact native_android_x86_macos from: https://dev.azure.com/xamarin//_apis/resources/Containers/15035605?itemPath=native_android_x86_macos&isShallow=true&api-version=4.1-preview.4
Retrying download of , retry count: 1
Retrying download of , retry count: 2
Retrying download of , retry count: 3
Retrying download of , retry count: 4
##[error]Failed in Download container - native_android_x86_macos with error: Error: Failed request: (statusCode) 404
```

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions

### Virtual environments affected

- [X] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 10.15
- [X] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

```
Starting: Initialize job
Agent name: 'Azure Pipelines 9'
Agent machine name: 'Mac-1655399065725'
Current agent version: '2.204.0'
Operating System
macOS
11.6.6
20G624
Virtual Environment
Environment: macos-11
Version: 20220614.2
Included Software: https://github.com/actions/virtual-environments/blob/macOS-11/20220614.2/images/macos/macos-11-Readme.md
Image Release: https://github.com/actions/virtual-environments/releases/tag/macOS-11%2F20220614.2
Virtual Environment Provisioner
1.0.0.0-main-20220531-1
Current image version: '20220614.2'
Agent running as: 'runner'
Prepare build directory.
Set build variables.
Download all required tasks.
Downloading task: PowerShell (2.200.0)
Downloading task: Bash (3.201.1)
Downloading task: UsePythonVersion (0.200.0)
Downloading task: DownloadBuildArtifacts (0.200.1)
Downloading task: PublishBuildArtifacts (1.200.0)
Checking job knob settings.
   Knob: AgentToolsDirectory = /Users/runner/hostedtoolcache Source: ${AGENT_TOOLSDIRECTORY} 
Finished checking job knob settings.
Plugin: 'Test Result Parser plugin' is running in background.
Plugin: 'Test File Publisher plugin' is running in background.
Start tracking orphan processes.
Finishing: Initialize job
```

### Is it regression?

Not sure, this download logic is new

### Expected behavior

The download works

### Actual behavior

The download fails every time

### Repro steps

Run the build? But it is just a simple step so I am not sure. ~The issue is that this may be an issue with fork build only? I do have secrets available but that should not be required as the build is public and so are the artifacts.~ Scrap that, it works on Windows.

Here is a build that is not a fork: https://dev.azure.com/xamarin/public/_build/results?buildId=64562&view=results

**Comment by al-cheb** [comment]
Hello @mattleibow.
We will take a look at it.

**Comment by al-cheb** [comment]
I think it could be related to this https://status.dev.azure.com/_event/313560682 issue, also I didn't find any builds with the same issue since Wed,15. I will close the thread, because it affects Azure DevOps Artifact Service(support forum - https://developercommunity.visualstudio.com/search?space=21), but not the image itself.

**Comment by mattleibow** [comment]
I logged this issue as it still happens  every time: https://developercommunity.visualstudio.com/t/Unix-based-agents-cannot-download-build/10082907

**Comment by miketimofeev** [comment]
@mattleibow there could be also an issue with the DownloadBuildArtifacts@0 task so the issue could be filed in the https://github.com/microsoft/azure-pipelines-tasks as well. 
Also, the documentation recommends upgrading from build artifacts to [Pipeline Artifacts](https://docs.microsoft.com/en-us/azure/devops/pipelines/artifacts/pipeline-artifacts?view=azure-devops) for faster performance. Could you try it?
![image](https://user-images.githubusercontent.com/48208649/176381430-7c76f6e4-ff6d-4976-adff-4ced4f403607.png)

**Comment by mattleibow** [comment]
I can't upgrade as the feature I need is not supported. I push from several jobs to a single package and this is not supported.

But I will open an issue for that task. Not sure why I opened an issue here tbh.
