### ISSUE TITLE
Update Python to 3.8.13

### ISSUE THREAD

**Issue by olivierlefloch** [actions/virtual-environments#5772]
### Tool name

Python

### Tool license

https://github.com/python/cpython/blob/main/LICENSE?rgh-link-date=2022-05-31T15%3A06%3A19Z

### Add or update?

- [ ] Add
- [X] Update

### Desired version

3.8.13

### URL for tool's homepage

https://www.python.org/downloads/release/python-3813/

### Platforms where you need the tool

- [ ] Azure DevOps
- [X] GitHub Actions

### Virtual environments where you need the tool

- [X] Ubuntu 18.04
- [X] Ubuntu 20.04
- [X] Ubuntu 22.04
- [X] macOS 10.15
- [X] macOS 11
- [X] macOS 12
- [X] Windows Server 2019
- [X] Windows Server 2022

### Are you willing to submit a PR?

Yes, if there are existing instructions for updating to a new Python version

**Comment by mikhailkoliada** [comment]
Hi @olivierlefloch, we will take a look

**Comment by mikhailkoliada** [comment]
@olivierlefloch it should be available for `actions/setup-python` right now and will be in the image by the end of this week.

**Comment by mikhailkoliada** [comment]
Should be available now.
