### ISSUE TITLE
Unable to build virtual environment

### ISSUE THREAD

**Issue by altwohill** [actions/virtual-environments#5773]
### Description

When building a Server 2022 environment following these instructions https://github.com/actions/virtual-environments/blob/main/docs/create-image-and-azure-resources.md, I get an error

```
==> vhd: Resize-Partition : Size Not Supported
==> vhd:
==> vhd: Extended information:
==> vhd: The partition is already the requested size.
==> vhd:
==> vhd: Activity ID: {a0fdd1f6-989d-4623-922f-18e6b90c58b5}
==> vhd: At C:\Windows\Temp\script-62adac62-5b69-c32d-bedc-bc1c4b2dcb9a.ps1:75 char:1
==> vhd: + Resize-Partition -DriveLetter $driveLetter -Size $size.SizeMax
==> vhd: + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
==> vhd:     + CategoryInfo          : NotSpecified: (StorageWMI:ROOT/Microsoft/.../MSFT_Partition) [Resize-Partition], CimExce
==> vhd:    ption
==> vhd:     + FullyQualifiedErrorId : StorageWMI 4097,Resize-Partition
==> vhd:
==> vhd: Script exited with non-zero exit status: 1.Allowed exit codes are: [0]
==> vhd: Step "StepProvision" failed
==> vhd: [c] Clean up and exit, [a] abort without cleanup, or [r] retry step (build may fail even if retry succeeds)?
```

Retry does not succeed. 

### Platforms affected

- [ ] Azure DevOps
- [ ] GitHub Actions

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

n/a

### Is it regression?

n/a

### Expected behavior

Environment builds successfully

### Actual behavior

Environment fails to build

### Repro steps

https://github.com/actions/virtual-environments/blob/main/docs/create-image-and-azure-resources.md

**Comment by al-cheb** [comment]
Check the thread - https://github.com/actions/virtual-environments/discussions/5432

**Comment by mxa0079** [comment]
Why is this issue closed? It is still happening in main. The discussion referred to does not find the root cause, and the workaround is to choose a different region - IMO that is not ideal.
