### ISSUE TITLE
Windows Server 2019: Install-VS.ps1 fails with exit-code 1

### ISSUE THREAD

**Issue by SaschaJohn** [actions/virtual-environments#5774]
### Description

vhd: Script exited with non-zero exit status: 1. Allowed exit codes are: [0 3010]

==> vhd: Provisioning with Powershell...
==> vhd: Provisioning with powershell script: /agent/_work/1/s/virtual-environments/images/win/scripts/Installers/Install-VS.ps1
    vhd: Downloading Bootstrapper ...
    vhd: Downloading package from: https://aka.ms/vs/16/release/vs_Enterprise.exe to path C:\Users\INSTAL~1\AppData\Local\Temp\vs_Enterprise.exe .
    vhd: Package downloaded successfully in 0.14 seconds
    vhd: Enable short name support on Windows needed for Xamarin Android AOT, defaults appear to have been changed in Azure VMs
    vhd: Starting Install ...
    vhd: [045c:000a][2022-06-19T17:36:21] Error 0x8013153b: Failed install: The operation was canceled.
    vhd:    at Microsoft.VisualStudio.Setup.InstallOperation.Run(CancellationToken token)
    vhd:    at Microsoft.VisualStudio.Setup.Engine.RunOperation(InstallOperation installOperation, CancellationToken token, ExecuteAction action, ITelemetryOperation telemetryOperation)
    vhd:
    vhd: Non zero exit code returned by the installation process : 1

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [X] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

win19/20220614.0

### Is it regression?

no

### Expected behavior

Install-VS.ps1 should install and return 0

### Actual behavior

Install-VS.ps1 fails with exit-code 1

### Repro steps

Run the packer build for win19/20220614.0

**Comment by al-cheb** [comment]
The nightly build on the main branch is green - https://github.visualstudio.com/virtual-environments/_build/results?buildId=127045&view=results . Looks like flaky network error, try to restart.

**Comment by SaschaJohn** [comment]
@al-cheb can you tell me from which region your pipeline is running? I tried WestEurope and EastUS, EastUS got further than WestEurope but still fails during VS install. The instances are in our Azure tenant and created via the Packer build on demand. So no possibility to restart manually to fix a flaky connection. Thanks in advance

**Comment by al-cheb** [comment]
@SaschaJohn , we use centralus and westus2.

**Comment by SaschaJohn** [comment]
@al-cheb running in centralus works without any issue, thanks for pointing to that. Maybe something that can be added to the documentation?
