### ISSUE TITLE
Android emulator script working on Github Actions but not on Azure Pipelines

### ISSUE THREAD

**Issue by nevardreik** [actions/virtual-environments#5775]
### Description

I have the following script which works fine with `macos-11` in Github Actions, but when running the same script in Azure Pipelines it doesn't work (when it should).

Script:
```
echo "y" | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --install "system-images;android-31;default;x86_64" --verbose
echo "no" | $ANDROID_HOME/cmdline-tools/latest/bin/avdmanager -v create avd \
  -n testRunnner \
  -k "system-images;android-31;default;x86_64" \
  --force
echo "Emulators:"
$ANDROID_HOME/emulator/emulator -list-avds

nohup $ANDROID_HOME/emulator/emulator -avd testRunnner \
  -skin 1080x1920 \
  -no-snapshot \
  -no-audio \
  -no-boot-anim \
  -accel auto \
  -gpu auto
  -qemu -lcd-density 420 > /dev/null 2>&1 & \
  $ANDROID_HOME/platform-tools/adb wait-for-device shell 'while [[ -z $(getprop sys.boot_completed | tr -d '\r') ]]; do sleep 1; done'
$ANDROID_HOME/platform-tools/adb devices
echo "Emulator started"
```

This is the error in Azure Pipelines:
```
Auto-selecting single ABI x86_64
Do you wish to create a custom hardware profile? [no] Emulators:
Starting emulator...
ERROR   | Unknown AVD name [testRunnner], use -list-avds to see valid list.
ERROR   | HOME is defined but there is no file testRunnner.ini in $HOME/.android/avd
ERROR   | (Note: Directories are searched in the order $ANDROID_AVD_HOME, $ANDROID_SDK_HOME/avd and $HOME/.android/avd)
INFO    | Android emulator version 31.2.10.0 (build_id 8420304) (CL:N/A)
```

This is the success output in Guthub Actions:
```
Auto-selecting single ABI x86_64
Do you wish to create a custom hardware profile? [no] Emulators:
testRunner
Starting emulator...
* daemon not running; starting now at tcp:5037
* daemon started successfully
```

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 10.15
- [X] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

20220614.2

### Is it regression?

N/A

### Expected behavior

Android emulator should run the selected AVD

### Actual behavior

AVD is being created in `~/.android/avd/testRunner.avd` however the emulator doesn't see it.

### Repro steps

Run the above script in an Azure Pipeline using `macos-11` agent and verify `avdmanager` creates the avd correctly, and the emulator can load it.

**Comment by mikhailkoliada** [comment]
Hi @nevardreik!

Thanks, we will take a look.

**Comment by nevardreik** [comment]
@mikhailkoliada I was able to resolve this by overriding the `ANDROID_AVD_HOME` environment variable to point to `$(Pipeline.Workspace)/.android` 

`ANDROID_AVD_HOME` environment variable typically points to `~/.android` however this doesn't exist on the Azure agents, instead it lives in `~/work/1/.android` - so when `emulator` tries to locate the AVD, it will never be able to find it as it will only search specific locations.

Can you please check if something has changed with environment variables on the specific image version above? Seems strange that I'm the only one reporting this issue where it should be impacting many others...

**Comment by al-cheb** [comment]
I am going to close the thread as not reproducible. Feel free to open it if you have any concerns.

**Comment by RuslanKuziak** [comment]
This issue still occurs to me. Randomly, the emulator will be started, but only using 'macOS-latest'.
After this successful launch, the next time will fail to start again.

The following message:
`* daemon not running; starting now at tcp:5037
* daemon started successfully`

will be displayed until the pipeline fails with a timeout.
Do you guys have any idea how it can be fixed?

@nevardreik  Can you please share how/where you've overwritten `ANDROID_AVD_HOME` variable?

**Comment by jkyoo82** [comment]
overwrite environment  variable
export ANDROID_AVD_HOME=$HOME/.android/avd
