### ISSUE TITLE
dotnet workload install: Workload ID xxx is not recognized

### ISSUE THREAD

**Issue by Apollo3zehn** [actions/virtual-environments#5776]
### Description

My [builds](https://github.com/Nexusforge/nexus/runs/6963708342?check_suite_focus=true) fail early when trying to run `dotnet workload install wasm-tools` since image version 20220614.0. As far as I can see, the only thing that has changed was the update from SDK version 6.0.300 to 6.0.301. However, on my local PC (Windows), `dotnet workload install wasm-tools` works just fine with SDK version 6.0.301.

### Platforms affected

- [ ] Azure DevOps
- [x] GitHub Actions

### Virtual environments affected

- [ ] Ubuntu 18.04
- [X] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Environment: ubuntu-20.04
Version: 20220614.0
https://github.com/Nexusforge/nexus/runs/6963708342?check_suite_focus=true

### Is it regression?

20220605.1, https://github.com/Nexusforge/nexus/runs/6883715893?check_suite_focus=true

### Expected behavior

`dotnet workload install wasm-tools` should work.

### Actual behavior

Getting error message `Workload ID wasm-tools is not recognized.`

### Repro steps

Run `dotnet workload install wasm-tools` in a GitHub Actions job as shown [here](https://github.com/Nexusforge/nexus/blob/master/.github/workflows/build-and-publish.yml#L49).

**Comment by mikhailkoliada** [comment]
@Apollo3zehn Hi!

Thanks! We will take a look.

**Comment by al-cheb** [comment]
It should be fixed in the next image rollout by Friday.

**Comment by Apollo3zehn** [comment]
It works again, thanks!
