### ISSUE TITLE
mac-os-latest failing to build for aarch64-apple-darwin due to missing stdlib.h

### ISSUE THREAD

**Issue by benwis** [actions/virtual-environments#5781]
### Description

```
warning: /Applications/Xcode_13.2.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/stdlib.h:93:15: fatal error: 'stdlib.h' file not found
warning: #include_next <stdlib.h>
warning:               ^~~~~~~~~~
warning: 1 error generated.
```
I'm attempting to compile a rust package with some c++ dependencies in the form of tree-sitter-html, and it looks like the macos-latest environment is missing the standard library for arm processors. The same host builds the package normally for x86_64 mac.

### Platforms affected

- [ ] Azure DevOps
- [ ] GitHub Actions

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [X] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Really not sure what to put here. Here is a link to the failed run.
https://github.com/benwis/femark/actions/runs/2532062746

### Is it regression?

I don't think so, but I am unsure

### Expected behavior

I expect it to build as the x86_64 mac version did.

### Actual behavior

It is failing to build because it cannot load stdlib.h

### Repro steps

Push code to the repo, causing github action to run, or rerun failed action.
CI.yml github action will run, and it will build for linux, windows and x64 mac.
darwin mac will fail to build with aforementioned error.

**Comment by mikhailkoliada** [comment]
@benwis HI!

Does the file actually exist for you?

**Comment by benwis** [comment]
Since it builds for x64 on mac, wouldn't that mean the file exists? I haven't tried to explore that directory though during the arm build process, I could do that.

**Comment by mikhailkoliada** [comment]
@benwis Hello!

Have you tried switching to the command-line tools for xcode with the

```sudo xcode-select -s /Library/Developer/CommandLineTools```

command?

**Comment by mikhailkoliada** [comment]
@benwis I am going to close this ticket now, but feel free to reach us out if you have questions left.
