### ISSUE TITLE
Is Set-ExecutionPolicy -ExecutionPolicy Unrestricted -Scope LocalMachine needed?

### ISSUE THREAD

**Issue by olandese** [actions/virtual-environments#579]
https://github.com/actions/virtual-environments/blob/0ddeb1ac4b2e81f45ba752d49ec5825b77141d40/images/win/scripts/Installers/Windows2019/Initialize-VM.ps1#L71

https://github.com/actions/virtual-environments/blob/0ddeb1ac4b2e81f45ba752d49ec5825b77141d40/images/win/scripts/Installers/Windows2016/Initialize-VM.ps1#L71

In the initialize-VM scripts for the Windows Agents the following is done:  Set-ExecutionPolicy -ExecutionPolicy Unrestricted -Scope LocalMachine  -ErrorAction Continue | Out-Null

This gives an error during the packer build process because packer is starting a powershell process using the -ByPass policy at process level, which is more specific.

This is the error from the Packer logs:
```
==> vhd: Set-ExecutionPolicy : Windows PowerShell updated your execution policy successfully, but the setting is overridden by
==> vhd: a policy defined at a more specific scope.  Due to the override, your shell will retain its current effective
==> vhd: execution policy of Bypass. Type "Get-ExecutionPolicy -List" to view your execution policy settings. For more
==> vhd: information please see "Get-Help Set-ExecutionPolicy".
```

My questions are: 

1. Do we need to set the execution policy to Unrestricted?
2. If yes, then the way to solve the error is to do the following in the packer build: 
```       {
            "type": "powershell",
            "environment_vars": [
                "ImageVersion={{user `image_version`}}"
            ],
            "scripts":[
                "{{ template_dir }}/scripts/Installers/Windows2019/Initialize-VM.ps1"
            ],
            "execution_policy": "unrestricted"
```
3. If no, then remove the Set-ExecutionPolicy from the Initialize-VM (in 2016 and 2019)

**Comment by al-cheb** [comment]
Hello, @olandese 
1. Yep, we need this statement, because we change **system-wide Powershell ExecutionPolicy="Unrestricted"**.
2. If we set "execution_policy": "unrestricted" in the packer build and run the `Initialize-VM.ps1` script. It will be changed  ExecutionPolicy  only for current process. The setting doesn't change system-wide PowerShell ExecutionPolicy.

`execution_policy` - To run ps scripts on windows packer defaults this to
    "bypass" and wraps the command to run. Setting this to "none" will prevent
    wrapping, allowing to see exit codes on docker for windows. Possible values
    are "bypass", "allsigned", "default", "remotesigned", "restricted",
    "undefined", "unrestricted", "none".

https://github.com/hashicorp/packer/blob/9eda2031d25bf4f02749ae0d2d727efa84a49168/provisioner/powershell/provisioner.go#L88

`		return fmt.Sprintf(`powershell -executionpolicy %s "%s"`, p.config.ExecutionPolicy, baseCmd)`

**Comment by olandese** [comment]
@al-cheb thank you for the quick reply! 

What I mean with the "execution_policy": "unrestricted" in Packer is to run the Initialize-VM script with **still** the Set-Execution policy in it. 
This will prevent the error showing up and still applying the Unrestricted execution policy (because the powershell process spinned up by Packer has the same policy we apply in the script).

**Comment by al-cheb** [comment]
@olandese Feel free to prepare PR for this issue.

**Comment by olandese** [comment]
@al-cheb done, https://github.com/actions/virtual-environments/pull/581

**Comment by olandese** [comment]
@al-cheb the build is runnig and the Initialize-VM script has already been executed, as you can see in the packer log in the build output the Set-ExecutionPolicy has run successfully without any error :) 
Let's wait the build to finish to see if in the VM is applied correctly
