### ISSUE TITLE
ubuntu-latest: Failing to run NET6 app due to missing Microsoft.NETCore.App

### ISSUE THREAD

**Issue by mary-georgiou-sonarsource** [actions/virtual-environments#5792]
### Description

After the [latest ](https://github.com/actions/virtual-environments/commit/7de34e33a87a3142a38576970e61542902020766) update in `ubuntu-latest` we started having issues in our Azure pipeline while running a NET5 app with the error

```/usr/share/dotnet/sdk/6.0.301/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(356,5): error NETSDK1127: The targeting pack Microsoft.NETCore.App is not installed. Please restore and try again.```

### Platforms affected

- [x] Azure DevOps
- [ ] GitHub Actions

### Virtual environments affected

- [ ] Ubuntu 18.04
- [X] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

```
Ubuntu 20.04.4 LTS
Virtual Environment
Environment: ubuntu-20.04
Version: 20220614.0
Included Software: https://github.com/actions/virtual-environments/blob/ubuntu20/20220614.0/images/linux/Ubuntu2004-Readme.md
Image Release: https://github.com/actions/virtual-environments/releases/tag/ubuntu20%2F20220614.0
Virtual Environment Provisioner
1.0.0.0-main-20220531-1
Current image version: '20220614.0'
```

### Is it regression?

Environment: ubuntu-20.04 Version: 20220605.1

### Expected behavior

Run the App without a runtime error.

### Actual behavior

Having an error:
```/usr/share/dotnet/sdk/6.0.301/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(356,5): error NETSDK1127: The targeting pack Microsoft.NETCore.App is not installed. Please restore and try again.```

### Repro steps

Haven't managed to reproduce outside of the pipeline.
Changing the image to `[ubuntu-22.04](https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2204-Readme.md)` seems to solve the issue.

**Comment by al-cheb** [comment]
Hey @mary-georgiou-sonarsource.
Please use [setup-dotnet](https://github.com/actions/setup-dotnet) task, the new image rollout should fix it.

**Comment by mary-georgiou-sonarsource** [comment]
@al-cheb I confirm that the issue has been resolved.
Thanks a lot for the super quick fix!
