### ISSUE TITLE
`dash` shell is not a valid shell and is not listed in preinstalled software Ubuntu 20.04 LTS

### ISSUE THREAD

**Issue by EmilySeville7cfg** [actions/virtual-environments#5795]
### Description

`dash` shell is not a valid [shell][docs] and is not listed in [installed software][soft] for Ubuntu 20.04 LTS.

[docs]: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsshell
[soft]: https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-Readme.md

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions

### Virtual environments affected

- [ ] Ubuntu 18.04
- [X] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Environment: ubuntu-20.04
  Version: 20220619.1
  Included Software: https://github.com/actions/virtual-environments/blob/ubuntu20/2022061[9](https://github.com/EmilySeville7cfg/test/runs/7003764912?check_suite_focus=true#step:1:10).1/images/linux/Ubuntu2004-Readme.md
  Image Release: https://github.com/actions/virtual-environments/releases/tag/ubuntu20%2F20220619.1

### Is it regression?

No

### Expected behavior

`dash` shell is a valid shell and is listed in preinstalled software for Ubuntu 20.04 LTS.

### Actual behavior

Now GitHub actions don't allow use `dash` shell directly (via [shell][key] key).

[key]: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsshell

### Repro steps

Create the following sample workflow:

```yaml
name: CI
on:
  push:
    branches:
    - main

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - shell: dash
        run: |
          dash -c 'echo Dash executed'
```

Obtain linting error for `- shell: dash` line.

**Comment by al-cheb** [comment]
Hey @EmilySeville7cfg,
GitHub actions doesn't support `dash` shell as the default one. GH Actions allows to use a custom shell using shell {0} syntax:

```
- name: dash shell
  run: |
       ps $$
  shell: dash {0}
```

![image](https://user-images.githubusercontent.com/47745270/175031224-cb4f6b8a-1ee5-43ad-bcde-da9f910ceaa3.png)

I will update doc file to include info about dash shell version.

**Comment by al-cheb** [comment]
The documentation in the repo has been updated.
