### ISSUE TITLE
Update/Add Windows SDK version 10.0.22621

### ISSUE THREAD

**Issue by davidmatson** [actions/virtual-environments#5797]
### Tool name

Windows SDK

### Tool license

see website

### Add or update?

- [X] Add
- [ ] Update

### Desired version

10.0.22621 (currently, the latest RTM)

### URL for tool's homepage

https://developer.microsoft.com/en-us/windows/downloads/windows-sdk/

### Platforms where you need the tool

- [X] Azure DevOps
- [ ] GitHub Actions

### Virtual environments where you need the tool

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Can this tool be installed during the build?

```bash
unknown
```

### Tool installation time in runtime

unknown

**Comment by al-cheb** [comment]
Duplicate: https://github.com/actions/virtual-environments/issues/5235#issuecomment-1149995269

**Comment by al-cheb** [comment]
@davidmatson, https://github.com/actions/virtual-environments/pull/5755

**Comment by al-cheb** [comment]
The new image and documentation have been updated.
