### ISSUE TITLE
deprecation warning for 'az group deployment create'

### ISSUE THREAD

**Issue by Mwalima** [actions/virtual-environments#5799]
### Description

https://docs.microsoft.com/en-us/cli/azure/deployment/group?view=azure-cli-latest#az-deployment-group-create

deprecation warning and error on az function 

should be:  az deployment group create

### Platforms affected

- [X] Azure DevOps
- [X] GitHub Actions

### Virtual environments affected

- [X] Ubuntu 18.04
- [X] Ubuntu 20.04
- [X] Ubuntu 22.04
- [X] macOS 10.15
- [X] macOS 11
- [X] macOS 12
- [X] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

no

### Is it regression?

no

### Expected behavior

no error on this point

### Actual behavior

Creating the VM
This command is implicitly deprecated because command group 'group deployment' is deprecated and will be removed in a future release. Use 'deployment group' instead.

### Repro steps

run the script:
GenerateResourcesAndImage -SubscriptionId {YourSubscriptionId} -ResourceGroupName "myTestResourceGroup" -ImageGenerationRepositoryRoot "$pwd" -ImageType Ubuntu1804 -AzureLocation "East US"

**Comment by al-cheb** [comment]
Hey @Mwalima,
We will take a look at it.

**Comment by al-cheb** [comment]
Fixed in https://github.com/actions/virtual-environments/pull/5803 PR
