### ISSUE TITLE
Update/Add ginkgo/gomega

### ISSUE THREAD

**Issue by dbyington** [actions/virtual-environments#58]
**Tool information**
- Tool name: ginkgo
- Add or update? Add
- Desired version: v1.10.2 (latest release)
- Approximate size: 
- If this is an add request:
  - Brief description of tool: 
> Ginkgo is a BDD-style Go testing framework built to help you efficiently write expressive and comprehensive tests. It is best paired with the Gomega matcher library but is designed to be matcher-agnostic.
  - URL for tool's homepage: https://onsi.github.io/ginkgo/
  - And: https://github.com/onsi/gomega

**Virtual environments affected**
- [ X ] macOS 10.14
- [ X ] Ubuntu 16.04 LTS
- [ X ] Ubuntu 18.04 LTS
- [ X ] Windows Server 2016 R2
- [ X ] Windows Server 2019

**Can this tool be installed during the build?**
Yes, typically installed with 
```
go get github.com/onsi/ginkgo/ginkgo
go get github.com/onsi/gomega/...
```

**Are you willing to submit a PR?**
Yes.
(I have not found a CONTRIBUTING policy so some initial direction would be nice.)

**Comment by maxim-lobanov** [comment]
@dbyington , how much time does it take to install it in runtime?

**Comment by maxim-lobanov** [comment]
Installation in runtime takes about 26 seconds on macOS and 35 seconds on Ubuntu / Windows using the following commands:
```
go get github.com/onsi/ginkgo/ginkgo
go get github.com/onsi/gomega/...
```

**Comment by alepauly** [comment]
hi @dbyington considering this installs pretty quickly on runtime, we won't be adding it to the environment at this time.
