### ISSUE TITLE
Build broken with `ubuntu-20.04` version `20220619.1`

### ISSUE THREAD

**Issue by egvimo** [actions/virtual-environments#5800]
### Description

After the version update to `20220619.1` of the `ubuntu-20.04` image our builds are broken.

Unfortunately I can not say what exactly is broken. Our Scenario:

- Compile and Package a Java App ✔️
- Start depending services (database, IAM, ...) ✔️
- Run Java App ✔️
- Run E2E Tests ❌

The error is inside the Java App, which appears to missing a session.
I have no idea how this is related to the new VM image.

I've changed the image to `ubuntu-22.04` (20220614.0) and it work again. So something in the `20220619.1` breaks our build.

Update: `ubuntu-22.04` 20220619.1 is also breaking our build.

It would be very helpful in such cases to be able to pin the image (#2894)

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions

### Virtual environments affected

- [ ] Ubuntu 18.04
- [X] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Environment: ubuntu-20.04
Version: 20220619.1
Included Software: https://github.com/actions/virtual-environments/blob/ubuntu20/20220619.1/images/linux/Ubuntu2004-Readme.md
Image Release: https://github.com/actions/virtual-environments/releases/tag/ubuntu20%2F20220619.1

### Is it regression?

20220614.0

### Expected behavior

Build runs normally.

### Actual behavior

Build breaking with strange behavior.

### Repro steps

I try to create a minimal app to reproduce.

**Comment by mikhailkoliada** [comment]
Hi @egvimo!

Yes, please provide us a minimalistic example so we could reproduce the issue.

**Comment by miketimofeev** [comment]
@Kolfering most likely your issue is unrelated to this one judging by the logs. You have a problem with `libudev-dev` installation. Could you please file a new issue for that?

**Comment by al-cheb** [comment]
@egvimo, Any updates?

**Comment by egvimo** [comment]
@al-cheb Unfortunately I did not managed to create a minimalistic example to reproduce this issue.

I've "fixed" that on the application side so that our builds are running again, because my workaround (switching to 22.04) did not last very long. After some builds the version also switched to 20220619.1 braking the builds again.

It would be very helpful to be able to pin the VM version.

So since you cannot reproduce, feel free to close.
