### ISSUE TITLE
Coming breaking change: zone is mandatory when sku = Standard

### ISSUE THREAD

**Issue by Mwalima** [actions/virtual-environments#5802]
### Description

Creating a public IP address
WARNING: [Coming breaking change] In the coming release, the default behavior will be changed as follows when sku is Standard and zone is not provided: For zonal regions, you will get a zone-redundant IP indicated by zones:["1","2","3"]; For non-zonal regions, you will get a non zone-redundant IP indicated by zones:null.
{

_Standard SKU public IP is recommended for production workloads. For more information about SKUs, see [Public IP addresses](https://docs.microsoft.com/en-us/azure/virtual-network/ip-services/public-ip-addresses).

The following command works for API version 2020-08-01 or later. For more information about the API version currently being used, please refer to [Resource Providers and Types](https://docs.microsoft.com/en-us/azure/azure-resource-manager/management/resource-providers-and-types)._

### Platforms affected

- [X] Azure DevOps
- [X] GitHub Actions

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

no

### Is it regression?

no

### Expected behavior

no alert

### Actual behavior

Creating a public IP address
WARNING: [Coming breaking change] In the coming release, the default behavior will be changed as follows when sku is Standard and zone is not provided: For zonal regions, you will get a zone-redundant IP indicated by zones:["1","2","3"]; For non-zonal regions, you will get a non zone-redundant IP indicated by zones:null.

### Repro steps

run script CreateAzureVMFromPackerTemplate

**Comment by al-cheb** [comment]
Fixed in https://github.com/actions/virtual-environments/pull/5803 PR
