### ISSUE TITLE
Build stop working on Ubuntu 22.04 since 20220619.1

### ISSUE THREAD

**Issue by Kolfering** [actions/virtual-environments#5806]
### Description

The builds are now broken with Ubuntu 22.04 since 20220619.1 while nothing changed in our workflows.
It was working with the previous version: 20220614.0. It happens in the apt-get install step which fails with this error message:

```
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
libudev-dev : Depends: libudev1 (= 249.11-0ubuntu3) but 249.11-0ubuntu3.1 is to be installed
E: Unable to correct problems, you have held broken packages.
##[error]Process completed with exit code 100.
```

Thanks for your help.

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

20220619.1

Failed build: https://github.com/Aleph-One-Marathon/alephone/runs/7025132822?check_suite_focus=true

### Is it regression?

20220614.0 (https://github.com/Aleph-One-Marathon/alephone/runs/6973930681?check_suite_focus=true)

### Expected behavior

Successful run.

### Actual behavior

The run fails.

### Repro steps

Run sudo apt-get update -y
Run sudo apt-get install autoconf-archive libboost-all-dev libsdl2-dev libsdl2-image-dev libsdl2-net-dev libsdl2-ttf-dev libspeexdsp-dev libzzip-dev libavcodec-dev libavformat-dev libavutil-dev libswscale-dev libswresample-dev libpng-dev libcurl4-gnutls-dev libminiupnpc-dev libsndfile-dev

**Comment by lucasw** [comment]
I've been seeing something similar at a step that installs libsdl2-dev
https://github.com/lucasw/ros_from_src/runs/7026816609

One odd thing is that a build of the same version triggered by release did succeed: https://github.com/lucasw/ros_from_src/runs/7006499800


(I was also experimenting with restarting services that are noted as needing restarting, but maybe I shouldn't be doing an apt upgrade at all)

**Comment by al-cheb** [comment]
Some Ubuntu mirrors are out of sync, we should wait:

Current:
```
libudev1 | 249.11-0ubuntu3.1 | http://azure.archive.ubuntu.com/ubuntu jammy-updates/main amd[6](https://github.com/roasted-eggplant/alcheb-test/runs/7027175613?check_suite_focus=true#step:2:7)4 Packages
  libudev1 | 249.11-0ubuntu3 | http://azure.archive.ubuntu.com/ubuntu jammy/main amd64 Packages
libudev-dev | 249.11-0ubuntu3.1 | http://azure.archive.ubuntu.com/ubuntu jammy-updates/main amd64 Packages
libudev-dev | 249.11-0ubuntu3 | http://azure.archive.ubuntu.com/ubuntu jammy/main amd64 Packages
```

My test vm:
```
libudev1 | 249.11-0ubuntu3.3 | http://rs.archive.ubuntu.com/ubuntu jammy-updates/main amd64 Packages
libudev1 | 249.11-0ubuntu3 | http://rs.archive.ubuntu.com/ubuntu jammy/main amd64 Packages
libudev-dev | 249.11-0ubuntu3.3 | http://rs.archive.ubuntu.com/ubuntu jammy-updates/main amd64 Packages
libudev-dev | 249.11-0ubuntu3 | http://rs.archive.ubuntu.com/ubuntu jammy/main amd64 Packages

```

**Comment by al-cheb** [comment]
As a temporary workaround manually update to the latest version:
```
- run: |
          sudo apt-get update
          sudo apt-get install libudev1=249.11-0ubuntu3.3 libudev-dev=249.11-0ubuntu3.3 -y
```

![image](https://user-images.githubusercontent.com/47745270/175344799-0bb7c2a9-693d-41f3-b0e6-e10aea5b850f.png)

**Comment by bluca** [comment]
The azure mirror has the new packages, and the metadata lists it, but the problem is still occurring:

https://azure.archive.ubuntu.com/ubuntu/pool/main/s/systemd
http://azure.archive.ubuntu.com/ubuntu/dists/jammy-updates/main/binary-amd64/Packages.gz

**Comment by bluca** [comment]
On a minimal jammy image, with the exact same sources.list that GH actions uses, the installation works fine. Is there some local caching happening in GH?

**Comment by al-cheb** [comment]
> sudo apt-get install libudev1=249.11-0ubuntu3.3 libudev-dev=249.11-0ubuntu3.3 -y

I have check package policy:
```
libudev1:
  Installed: 249.11-0ubuntu3.1
  Candidate: 249.11-0ubuntu3.1
  Version table:
     249.11-0ubuntu3.3 1 (phased 70%)
        500 http://azure.archive.ubuntu.com/ubuntu jammy-updates/main amd64 Packages
 *** 249.11-0ubuntu3.1 100
        100 /var/lib/dpkg/status
     249.11-0ubuntu3 500
        500 http://azure.archive.ubuntu.com/ubuntu jammy/main amd64 Packages
```

After enable option allow to install phased updates:
```
echo 'APT::Get::Always-Include-Phased-Updates "true";' | sudo tee -a /etc/apt/apt.conf.d/99-phased-updates
sudo apt-get update
sudo apt-get install libudev-dev -y
```

![image](https://user-images.githubusercontent.com/47745270/175526332-cfe9aa83-e6a7-4633-ad71-b0af8d534ccd.png)


We should wait a new image rollout or use workaround above.

**Comment by bluca** [comment]
good fine - so the issue is that there are local packages from src:systemd installed, that are no longer in the -updates repository as there's a new phased update. But extra packages (we hit it with systemd-container) have a hard dependency on other packages from src:systemd that are newer, but they can't be installed because they are phased.

**Comment by bluca** [comment]
I've been told this is a known issue and it is being worked on: https://irclogs.ubuntu.com/2022/06/23/%23ubuntu-devel.html

**Comment by al-cheb** [comment]
Close as external.
