### ISSUE TITLE
win22 v20220619.1 appears to have broken support for zlib compared to 20220614.0 or win19

### ISSUE THREAD

**Issue by gf777** [actions/virtual-environments#5818]
### Description

It appears that the [latest update of win22](https://github.com/actions/virtual-environments/blob/win22/20220619.1/images/win/Windows2022-Readme.md) broke c++ support for zlib (-lz) compared to the [version of a few days before](https://github.com/actions/virtual-environments/blob/win22/20220614.0/images/win/Windows2022-Readme.md) 

### Platforms affected

- [ ] Azure DevOps
- [ ] GitHub Actions

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

broken: https://github.com/vgl-hub/gfastats/runs/7056899645?check_suite_focus=true
working if reverting to 19: https://github.com/vgl-hub/gfastats/runs/7056908329?check_suite_focus=true

### Is it regression?

working version: https://github.com/vgl-hub/gfastats/runs/6941819260?check_suite_focus=true

### Expected behavior

compile normally

### Actual behavior

cant compile, missing zlib

### Repro steps

try to compile https://github.com/vgl-hub/gfastats under win

**Comment by al-cheb** [comment]
Hello @gf777.
We have updated mingw from 8.1.0 to 11.2.0 version and looks like zlib headers are missing. We will take a look at it.

**Comment by al-cheb** [comment]
@abrown, Any ideas about this regression?

**Comment by abrown** [comment]
(Though I wonder if zlib is now a separate library... see [here](https://packages.msys2.org/package/mingw-w64-x86_64-zlib))

**Comment by gf777** [comment]
hi @mikhailkoliada 

Thanks and sorry for the late reply. Do you have an example of how to install mingw-w64-x86_64-toolchain ? The approach I tried seem to have worked but takes a long time to compile. For now I reverted to 2019
