### ISSUE TITLE
Reusing build-image script without VNET

### ISSUE THREAD

**Issue by ALTrijssenaar** [actions/virtual-environments#5820]
### Description

When reusing the build-image.ps1 script in a custom pipeline it is required to provide the VNET parameters
PACKER can also omit these parameters to provide the image an public IP, so the only limiting factor is the scripts itself.
If you don't make these parameters mandatory, the scripts is reusable.

### Platforms affected

- [X] Azure DevOps
- [X] GitHub Actions

### Virtual environments affected

- [X] Ubuntu 18.04
- [X] Ubuntu 20.04
- [X] Ubuntu 22.04
- [X] macOS 10.15
- [X] macOS 11
- [X] macOS 12
- [X] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

NA

### Is it regression?

no

### Expected behavior

Exactly the same as right now, but reusing the build-image.ps1 in a custom pipeline will be possible in a situation where you provide no VNET in formation.

### Actual behavior

The build-image.ps1 requires to provide a VNET configuration, but is not required for packer.

### Repro steps

Modify the image-generation.yml to not provide the VNET information aka run it in public-IP mode.

**Comment by al-cheb** [comment]
Merged https://github.com/actions/virtual-environments/pull/5821
