### ISSUE TITLE
Error while creating macOS ISO/DMG using macOS-11 Runner

### ISSUE THREAD

**Issue by RudraSen2** [actions/virtual-environments#5823]
### Description

When I’m trying to run this:

```bash
sudo hdiutil create -o /tmp/BigSur -size 16384m -volname BigSur -layout SPUD -fs HFS+J
sudo hdiutil attach /tmp/BigSur.dmg -noverify -mountpoint /Volumes/BigSur
sudo /Applications/Install\ macOS\ Big\ Sur.app/Contents/Resources/createinstallmedia --volume /Volumes/BigSur --nointeraction
hdiutil eject -force /Volumes/Install\ macOS\ Big\ Sur
hdiutil convert /tmp/BigSur.dmg -format UDTO -o ~/Desktop/BigSur
mv -v ~/Desktop/BigSur.cdr ~/Desktop/BigSur.iso
sudo rm -fv /tmp/BigSur.dmg
```

There comes an error with it’s output:

```
created: /tmp/BigSur.dmg
/dev/disk2              Apple_partition_scheme          
/dev/disk2s1            Apple_partition_map             
/dev/disk2s2            Apple_HFS                       /Volumes/BigSur
Erasing disk: 0%... 10%...
Error erasing disk error number (22, 0)
An error occurred erasing the disk.
Error: Process completed with exit code 252.
```

How do I fix this?

[Repository Link](https://github.com/Comp-Labs/Download-macOS)

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 10.15
- [X] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Latest Failed Run:

https://github.com/Comp-Labs/Download-macOS/runs/7071190487?check_suite_focus=true

### Is it regression?

No

### Expected behavior

Based on my `yml` file, it should successfully generate an ISO File and Upload it as an artifact.

### Actual behavior

Actual Behaviour is given in the Description. Error code 252.

### Repro steps

Follow the steps below to reproduce the issue:

1. Fork the Repo.
2. Run the `Generate ISO` or `Generate DMG` Job.
3. Check the failing output.

**Comment by RudraSen2** [comment]
Latest run: https://github.com/Comp-Labs/Download-macOS/runs/7071879039?check_suite_focus=true

**Comment by al-cheb** [comment]
Test CI:

```
    runs-on: macos-latest
    steps:
      - name: Download macOS Ventura Beta Latest
        run: |
          sudo "/System/Library/PrivateFrameworks/Seeding.framework/Versions/Current/Resources/seedutil" enroll DeveloperSeed
          sleep 5
          softwareupdate --fetch-full-installer --full-installer-version 13.0
      - name: ISO and Upload
        run: |
          hdiutil create -o /tmp/Ventura -size 16384m -volname Ventura -layout SPUD -fs HFS+J
          hdiutil attach /tmp/Ventura.dmg -noverify -mountpoint /Volumes/Ventura
          sleep 10
          sudo /Applications/Install\ macOS\ Ventura\ beta.app/Contents/Resources/createinstallmedia --volume /Volumes/Ventura --nointeraction
          hdiutil eject -force /Volumes/Install\ macOS\ Ventura\ beta/
          hdiutil convert /tmp/Ventura.dmg -format UDTO -o ~/Desktop/Ventura
          mv -v ~/Desktop/Ventura.cdr ~/Desktop/Ventura.iso
          rm -fv /tmp/Ventura.dmg
```

![image](https://user-images.githubusercontent.com/47745270/175941752-47022f86-384a-4ec9-a8d5-d40b6e280954.png)
