### ISSUE TITLE
Update chrome version to  latest

### ISSUE THREAD

**Issue by SaiDeepthi574** [actions/virtual-environments#5829]
### Breaking changes

Update chrome version to  latest 103

### Target date

*

### The motivation for the changes

lSystem.InvalidOperationException : session not created: This version of ChromeDriver only supports Chrome version 103
 Current browser version is 102.0.5005.115 with binary path C:\Program Files\Google\Chrome\Application\chrome.exe (SessionNotCreated)

### Possible impact

*

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [X] Windows Server 2019
- [ ] Windows Server 2022

### Mitigation ways

*

**Comment by al-cheb** [comment]
We are planning to start the new image rollout with Chrome 103 on board.

**Comment by al-cheb** [comment]
The deployment has been starting - https://github.com/actions/virtual-environments/pull/5830

**Comment by al-cheb** [comment]
The new image has been deployed.
