### ISSUE TITLE
Update docs for memory limit for macOS machines? [azure devops pipelines]

### ISSUE THREAD

**Issue by benasher44** [actions/virtual-environments#583]
Hi! I've been searching the docs, and I can't find info on this. What is the memory limit for pipelines running on Microsoft-hosted mac machines? Thanks!

**Tool information**
- Tool name: Azure Devops Pipelines
- Add or update? Docs for Azure Devops Pipelines
- Desired version: master?
- Approximate size:
- If this is an add request:
  - Brief description of tool: 
  - URL for tool's homepage: 

**Area for Triage**:
Apple

**Question, Bug, or Feature?**:
Question 

**Virtual environments affected**
- [x] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Can this tool be installed during the build?**

**Are you willing to submit a PR?**

**Comment by al-cheb** [comment]
Hello, @benasher44 

I don't think it's possible to update documentation about memory settings , because it highly related on hardware environments. You can easily query memory in runtime using command:
`sudo /usr/sbin/system_profiler SPHardwareDataType`

or

`sudo sysctl hw.memsize`

Example output:
```
Hardware:

    Hardware Overview:

      Model Name: Apple device
      Model Identifier: VMware7,1
      Processor Speed: 3.33 GHz
      Number of Processors: 2
      Total Number of Cores: 4
      L2 Cache (per Core): 256 KB
      L3 Cache (per Processor): 12 MB
      Memory: 12 GB
      Boot ROM Version: VMW71.00V.13989454.B64.1906190538
      Apple ROM Info: [MS_VM_CERT/SHA1/27d66596a61c48dd3dc7216fd715126e33f59ae7]Welcome to the Virtual Machine
      SMC Version (system): 2.8f0
      Serial Number (system): VMAhptVno0hT
      Hardware UUID: 4203018E-580F-C1B5-9525-B745CECA79EB
```

**Comment by benasher44** [comment]
Thanks! So to clarify, there is no limit, except for the hardware limit (either physical or virtual)?

**Comment by al-cheb** [comment]
@benasher44, We use factory default settings and  don't have any additional configuration limits for macOS image.

**Comment by benasher44** [comment]
Thanks! Closing.
