### ISSUE TITLE
VS studio dependencies cannot be downloaded during build

### ISSUE THREAD

**Issue by TLaborde** [actions/virtual-environments#5831]
### Description

Building the agent from latest source, it has been failing for several days when downloading some dependencies:

```
    vhd: Package 'Microsoft.VisualStudio.WorkflowV1.Debugger.Msi,version=16.10.31306.167,chip=x64' failed to download from 'https://download.visualstudio.microsoft.com/download/pr/af620239-98ad-431d-8a3d-f04ac1b3dc34/5ee63b07d3efaf9855db6f9c34ec784086e79da9494503621c02823b0e1a58ea/WorkflowDebugger_Legacy.msi'.
    vhd:     Search URL
    vhd:         https://aka.ms/VSSetupErrorReports?q=PackageId=Microsoft.VisualStudio.WorkflowV1.Debugger.Msi;PackageAction=DownloadPackage;ReturnCode=0x800704dd
    vhd:     Details
    vhd:         WebClient download failed: The remote server returned an error: (400) Bad Request.
    vhd:         WinInet download failed: Function: HttpQueryInfo-ResponseCode, HR: -2147024496, Message: Url 'https://download.visualstudio.microsoft.com/download/pr/af620239-98ad-431d-8a3d-f04ac1b3dc34/5ee63b07d3efaf9855db6f9c34ec784086e79da9494503621c02823b0e1a58ea/WorkflowDebugger_Legacy.msi'
    vhd:         Bits download failed: The operation being requested was not performed because the user has not logged on to the network. The specified service does not exist. (Exception from HRESULT: 0x800704DD)
```
The agent is working from Japan East region.
the file can be accessed from Japan without issue.
there is no firewall between the VM and internet.
The error seems related to BITS log in?

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [X] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

image is built using the previous working image, so win19/20220619.1

### Is it regression?

latest version ok: 2022-06-19

### Expected behavior

I expect the dependencies to be downloaded and installed in the agent

### Actual behavior

error 400 when trying to download the dependencies

### Repro steps

run packer using the source from repo on Azure devops pipeline

**Comment by TLaborde** [comment]
Trying to find similar bugs, it seems to indicate an issue with the CDN, like here: https://github.com/actions/virtual-environments/issues/4222

**Comment by al-cheb** [comment]
Nothing we can do with CDN, our recommendation is to switch to WESTUS2 or CentralUS,
