### ISSUE TITLE
[Windows, macOS] LLVM will be updated to version 14 on July, 11

### ISSUE THREAD

**Issue by miketimofeev** [actions/virtual-environments#5835]
### Breaking changes

LLVM will be updated from version 13 to version 14 on Windows and macOS images.

### Target date

The propagation will start on July 11 and take 2-3 days.

### The motivation for the changes

We'd like to keep images up-to-date with recent software updates.

### Possible impact

If your builds depend on LLVM 13 they can be broken.

### Platforms affected

- [X] Azure DevOps
- [X] GitHub Actions

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [X] macOS 10.15
- [X] macOS 11
- [X] macOS 12
- [X] Windows Server 2019
- [X] Windows Server 2022

### Mitigation ways

LLVM 13 can be installed in runtime using the following snippets:
- Windows
```pwsh
choco uninstall llvm
$llvmVersion = "13"
$latestChocoVersion = Get-LatestChocoPackageVersion -TargetVersion $llvmVersion -PackageName "llvm"
Choco-Install -PackageName llvm -ArgumentList '--version', $latestChocoVersion
clang --version
```
- macOS
```bash
brew uninstall llvm
brew install llvm@13
```

Or using the https://github.com/marketplace/actions/install-llvm-and-clang GitHub Action.

**Comment by strager** [comment]
How can I subscribe to announcements like this so I can be aware of breaking changes?
