### ISSUE TITLE
windows-latest 20220626.1: regression `ThreadSanitizer failed to allocate...` with `go test -race`

### ISSUE THREAD

**Issue by mark-pictor-csec** [actions/virtual-environments#5841]
### Description

Something in the latest win22 image ([win22/20220626.1](https://github.com/actions/virtual-environments/releases/tag/win22%2F20220626.1)) is causing a regression. This is not seen with the previous image ([win22/20220614.0](https://github.com/actions/virtual-environments/releases/tag/win22%2F20220614.0)).

The errors seen are of the form
```
==5248==ERROR: ThreadSanitizer failed to allocate 0x0000019b9000 (26972160) bytes at 0x200d965c00000 (error code: 87)
```
while running
```
go test -v ./... -race -coverprofile=coverage.txt -covermode=atomic
```

Something similar has been seen by other people, and I suspect the cause is the same: https://github.com/tailscale/tailscale/issues/4926, https://github.com/gobuffalo/.github/issues/2

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

failed image https://github.com/actions/virtual-environments/releases/tag/win22%2F20220626.1
failed build https://github.com/Contrast-Security-OSS/go-test-bench/runs/7101854784?check_suite_focus=true#step:4:105

working image https://github.com/actions/virtual-environments/releases/tag/win22%2F20220614.0
working build https://github.com/Contrast-Security-OSS/go-test-bench/runs/6992890616?check_suite_focus=true#step:4:620

### Is it regression?

yes

### Expected behavior

the build to pass, or at least to fail for reasons under our control

### Actual behavior

the test run fails with errors like
```
==5248==ERROR: ThreadSanitizer failed to allocate 0x0000019b9000 (26972160) bytes at 0x200d965c00000 (error code: 87)
```

### Repro steps

Re-run [this job](https://github.com/Contrast-Security-OSS/go-test-bench/runs/7101854784?check_suite_focus=true), which is the `windows-latest` test on our branch [broken-cmd-exercise](https://github.com/Contrast-Security-OSS/go-test-bench/tree/broken-cmd-exercise). 
The workflow config can be seen at [continuous-integration-workflow.yml:L29](https://github.com/Contrast-Security-OSS/go-test-bench/blob/broken-cmd-exercise/.github/workflows/continuous-integration-workflow.yml#L29)

**Comment by mark-pictor-csec** [comment]
Is it possible to specify a specific image version for github actions? I didn't see it in the gh actions docs, but if it is possible it'd be a temporary workaround.

**Comment by al-cheb** [comment]
Hello @mark-pictor-csec.
We updated mingw in this https://github.com/actions/virtual-environments/pull/5729 PR to the v11.2.0 version. I have found out the same issue in golang official repo - https://github.com/golang/go/issues/46099. The recommendation is to downgrade mingw to 10.2.0 in runtime - https://github.com/golang/go/issues/46099#issuecomment-1158744544

```
- name: Install mingw 10.2.0
  run: choco install mingw --version 10.2.0 --allow-downgrade
```

![image](https://user-images.githubusercontent.com/47745270/176371876-b7fe8d07-010b-4023-84c0-dd3b26a7fb98.png)
