### ISSUE TITLE
Add Microsoft Edge (chromium) to Ubuntu 20.04

### ISSUE THREAD

**Issue by dministro** [actions/virtual-environments#5845]
### Tool name

Microsoft Edge

### Tool license

Proprietary software, based on open source components

### Add or update?

- [X] Add
- [ ] Update

### Desired version

latest stable

### Brief description of tool

Microsoft Edge (chromium) is Microsofts latest incarnation of the Edge browser. A fork of the popular Chromium open source project.

### URL for tool's homepage

https://www.microsoft.com/en-us/edge

### Platforms where you need the tool

- [ ] Azure DevOps
- [ ] GitHub Actions

### Virtual environments where you need the tool

- [ ] Ubuntu 18.04
- [X] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Can this tool be installed during the build?

```bash
yes

curl -O https://packages.microsoft.com/repos/edge/pool/main/m/microsoft-edge-stable/microsoft-edge-stable_102.0.1245.39-1_amd64.deb
sudo apt install ./microsoft-edge-stable_102.0.1245.39-1_amd64.deb
```
```


### Tool installation time in runtime

_No response_

### Are you willing to submit a PR?

_No response_

**Comment by dministro** [comment]
Hi @miketimofeev 
Thank you for the prompt response.

**Comment by mikhailkoliada** [comment]
Changes will be deployed next week

**Comment by mikhailkoliada** [comment]
Deployed

**Comment by Piedone** [comment]
Thank you!
