### ISSUE TITLE
macos-10.15 missing LLVM 13

### ISSUE THREAD

**Issue by strager** [actions/virtual-environments#5846]
### Description

The [documentation for macos-10.15](https://github.com/actions/virtual-environments/blob/main/images/macos/macos-10.15-Readme.md) says that LLVM 13 is installed in `/usr/local/opt/llvm`:

> Clang/LLVM 13.0.1 is available on '$(brew --prefix llvm)/bin/clang'

I have relied on this tool at this location for many months.

Today (or yesterday), my CI scripts stopped working correctly. It looks like `/usr/local/opt/llvm` no longer exists on macos-10.15 workers.

According to `brew`, `llvm@13` is installed. However, `$(brew --prefix llvm)/bin/clang` doesn't exist:
```
$ brew list llvm@13 
/usr/local/Cellar/llvm@13/13.0.1/bin/FileCheck
/usr/local/Cellar/llvm@13/13.0.1/bin/analyze-build
/usr/local/Cellar/llvm@13/13.0.1/bin/bugpoint
/usr/local/Cellar/llvm@13/13.0.1/bin/c-index-test
/usr/local/Cellar/llvm@13/13.0.1/bin/clang
/usr/local/Cellar/llvm@13/13.0.1/bin/clang++
/usr/local/Cellar/llvm@13/13.0.1/bin/clang-13

$ brew --prefix llvm
/usr/local/opt/llvm
$ ls /usr/local/opt/llvm
ls: /usr/local/opt/llvm: No such file or directory

$ sw_vers
ProductName:    Mac OS X
ProductVersion: 10.15.7
BuildVersion:   19H1922
```

### Platforms affected

- [ ] Azure DevOps
- [ ] GitHub Actions

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [X] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

  Environment: macos-10.15
  Version: 20220627.1
  Included Software: https://github.com/actions/virtual-environments/blob/macOS-10.15/20220627.1/images/macos/macos-10.15-Readme.md
  Image Release: https://github.com/actions/virtual-environments/releases/tag/macOS-10.15%2F20220627.1

https://github.com/quick-lint/quick-lint-js/runs/7123423723?check_suite_focus=true

### Is it regression?

yes; 20220622.2; https://github.com/quick-lint/quick-lint-js/runs/7105900086?check_suite_focus=true

### Expected behavior

`$(brew --prefix llvm)/bin/clang` exists and is executable

### Actual behavior

`$(brew --prefix llvm)/bin/clang` does not exist

### Repro steps

Run `ls /usr/local/opt/llvm` in a job

**Comment by al-cheb** [comment]
Hello @strager.
It's expected that the path `/usr/local/opt/llvm` doesn't exist - https://github.com/actions/virtual-environments/pull/5819#issuecomment-1167815588

> If you're explicitly installing llvm@13, then it will only be found through /usr/local/opt/llvm@13. /usr/local/opt/llvm will only exist if you've installed llvm, and it will point to LLVM 14. So if anything was previously hardcoded to /usr/local/opt/llvm, it will have to be changed to /usr/local/opt/llvm@13 or LLVM 14 will have to be used instead.

**Comment by strager** [comment]
> It's expected that the path `/usr/local/opt/llvm` doesn't exist

Then the documentation should be updated.

**Comment by al-cheb** [comment]
https://github.com/actions/virtual-environments/pull/5837 is in progress.
