### ISSUE TITLE
[Windows] Configure-Antivirus.ps1 is marked as dangerous 

### ISSUE THREAD

**Issue by olandese** [actions/virtual-environments#5847]
### Description

During my onw nightly build the Windows 2002 throwed the following error:

![image](https://user-images.githubusercontent.com/1708128/176592287-6f0f4c51-bcef-40c8-b80e-0c15df5e66b0.png)

After opening the repo and the file in question (Configure-Antivirus.ps1) on my laptop, Windows warned me about a dangerous file:

![image](https://user-images.githubusercontent.com/1708128/176592447-50028f4e-97bb-4276-8946-30cefcde0be6.png)

![image](https://user-images.githubusercontent.com/1708128/176592496-7079f529-3948-4a88-b5b5-a6255091896c.png)

I think this is probably a false positive and Windows Defender latest signature is giving this problem. 
Windows Defender Signature: 
Security Intelligence Update for Microsoft Defender Antivirus - KB2267602 (Version 1.369.468.0)
Installed on 30-6-2022

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

.

### Is it regression?

Yes

### Expected behavior

No Error 

### Actual behavior

![image](https://user-images.githubusercontent.com/1708128/176592889-09a682b2-e861-4ffa-b562-2268be3c2eeb.png)

### Repro steps

Open the repo on a WIndows OS  (I am using Win 11 21H2 Build 22000.778) with the latest windows defender definition installed: Security Intelligence Update for Microsoft Defender Antivirus - KB2267602 (Version 1.369.468.0)
Open the Confgure-Antivirus.ps1 file

**Comment by al-cheb** [comment]
Hello @olandese.
Add the repo path to Windows Defender to the exclusion path:
`Set-MpPreference -ExclusionPath REPO_PATH`

**Comment by alainvezina** [comment]
@al-cheb this is still an issue since my last successful build on June 5.

I have the same described issue by @olandese.

I tried to test your solution, but it is something that can not be done on a Azure Build Server.

![image](https://user-images.githubusercontent.com/22731865/178316029-e9e9a119-de17-49e6-9845-4aa2463bbaac.png)
