### ISSUE TITLE
Installed Python packages are not documented

### ISSUE THREAD

**Issue by abitrolly** [actions/virtual-environments#5851]
### Description

There are quite a few Python packages that are installed, but not documented.

![Screenshot from 2022-07-01 09-07-59](https://user-images.githubusercontent.com/8781107/176837762-8748bfb9-50a1-496a-96df-b7e2b71926c1.png)

I also don't see build image logs to see who installs them.

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions

### Virtual environments affected

- [X] Ubuntu 18.04
- [X] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

https://github.com/yakshaveinc/python/runs/7144602632?check_suite_focus=true

### Is it regression?

No

### Expected behavior

Explain why these packages are there.

### Actual behavior

No info.

### Repro steps

Run `pip list`.

**Comment by abitrolly** [comment]
With build logs I could check it myself.

**Comment by al-cheb** [comment]
You can find it - https://github.visualstudio.com/virtual-environments/_build?definitionId=71

**Comment by al-cheb** [comment]
If you deploy in Azure a vm with Ubuntu Server 20.04 LTS the `colorama` package is pre-installed by default:
![image](https://user-images.githubusercontent.com/47745270/176899311-2b160ea3-6d9d-49e8-a3f3-f6a132f59a17.png)

```
$ find /usr/lib/python3/dist-packages -maxdepth 1 -type d | grep -i colorama
/usr/lib/python3/dist-packages/colorama
/usr/lib/python3/dist-packages/colorama-0.4.3.egg-info
```

<details>
  <summary>Packages</summary>
  
  ```javascript
attrs                  19.3.0
Automat                0.8.0
blinker                1.4
certifi                2019.11.28
chardet                3.0.4
Click                  7.0
cloud-init             22.2
colorama               0.4.3
command-not-found      0.3
configobj              5.0.6
constantly             15.1.0
cryptography           2.8
dbus-python            1.2.16
distro                 1.4.0
distro-info            0.23ubuntu1
entrypoints            0.3
httplib2               0.14.0
hyperlink              19.0.0
idna                   2.8
importlib-metadata     1.5.0
incremental            16.10.1
Jinja2                 2.10.1
jsonpatch              1.22
jsonpointer            2.0
jsonschema             3.2.0
keyring                18.0.1
language-selector      0.1
launchpadlib           1.10.13
lazr.restfulclient     0.14.2
lazr.uri               1.0.3
MarkupSafe             1.1.0
more-itertools         4.2.0
netifaces              0.10.4
oauthlib               3.1.0
pexpect                4.6.0
pip                    20.0.2
pyasn1                 0.4.2
pyasn1-modules         0.2.1
PyGObject              3.36.0
PyHamcrest             1.9.0
PyJWT                  1.7.1
pymacaroons            0.13.0
PyNaCl                 1.3.0
pyOpenSSL              19.0.0
pyparted               3.11.2
pyrsistent             0.15.5
pyserial               3.4
python-apt             2.0.0+ubuntu0.20.4.7
python-debian          0.1.36ubuntu1
PyYAML                 5.3.1
requests               2.22.0
requests-unixsocket    0.2.0
SecretStorage          2.3.1
service-identity       18.1.0
setuptools             45.2.0
simplejson             3.16.0
six                    1.14.0
sos                    4.3
ssh-import-id          5.10
systemd-python         234
Twisted                18.9.0
ubuntu-advantage-tools 27.8
ufw                    0.36
unattended-upgrades    0.1
urllib3                1.25.8
wadllib                1.3.3
WALinuxAgent           2.2.46
wheel                  0.34.2
zipp                   1.0.0
zope.interface         4.7.1
  ```
</details>

**Comment by abitrolly** [comment]
> If you deploy in Azure a vm with Ubuntu Server 20.04 LTS the colorama package is pre-installed by default:

I don't see how it is related.

According to this log - https://github.visualstudio.com/08427f54-005b-4b34-b700-dca767ba7c14/_apis/build/builds/127430/logs/14 - the package is being pulled by `miniconda`.

So why not document the dependencies?

**Comment by al-cheb** [comment]
> > If you deploy in Azure a vm with Ubuntu Server 20.04 LTS the colorama package is pre-installed by default:
> 
> I don't see how it is related.
> 
> According to this log - https://github.visualstudio.com/08427f54-005b-4b34-b700-dca767ba7c14/_apis/build/builds/127430/logs/14 - the package is being pulled by `miniconda`.
> 
> So why not document the dependencies?

The colorama **is pre-installed by default on a Azure vm**. We don't install it.

 According to this log - https://github.visualstudio.com/08427f54-005b-4b34-b700-dca767ba7c14/_apis/build/builds/127430/logs/14 - the package is being pulled by `miniconda`. - Please check version that installed with miniconda `colorama==0.4.4=pyhd3eb1b0_0` vs `0.4.3` came from apt-get

**Comment by abitrolly** [comment]
Are GitHub Action runners the same as Azure vms?

**Comment by al-cheb** [comment]
> Are GitHub Action runners the same as Azure vms?

That's right, for image generation we use Standard_D4s_v4 size and Standard_DS2_v2 for runners.

**Comment by abitrolly** [comment]
It doesn't make it better, unless you want to say that default Ubuntu image (not Azure) comes with preinstalled `colorama`.

**Comment by al-cheb** [comment]
> It doesn't make it better, unless you want to say that default Ubuntu image (not Azure) comes with preinstalled `colorama`.

We use Azure vm images from the marketplace which come with pre-installed `colorama`:

```
            "os_type": "Linux",
            "image_publisher": "canonical",
            "image_offer": "0001-com-ubuntu-server-focal",
            "image_sku": "20_04-lts"
```
E.g.:
`az vm image show --location westus2 --urn "canonical:0001-com-ubuntu-server-focal:20_04-lts:latest"`

**Comment by abitrolly** [comment]
@al-cheb the marketplace"?

**Comment by al-cheb** [comment]
> @al-cheb the marketplace"?

https://docs.microsoft.com/en-us/azure/virtual-machines/windows/cli-ps-findimage

**Comment by abitrolly** [comment]
My point - if it is not pristine Canonical Ubuntu image, the extra installed dependencies should be documented.

**Comment by al-cheb** [comment]
> My point - if it is not pristine Canonical Ubuntu image, the extra installed dependencies should be documented.

We don't include into the doc implicitly installed packages.

**Comment by abitrolly** [comment]
For the user it doesn't matter how the packages were installed. They change system behavior in an unexpected way, and should be documented.
