### ISSUE TITLE
Erlang tool installation not passing tests for Ubuntu Focal (20.04)

### ISSUE THREAD

**Issue by gaui** [actions/virtual-environments#5859]
### Description

I am getting the following error:

```
==> azure-arm: Provisioning with shell script: /home/vsts/work/1/s/images/linux/scripts/installers/erlang.sh
    azure-arm: Hit:1 http://azure.archive.ubuntu.com/ubuntu focal InRelease
    azure-arm: Hit:2 http://azure.archive.ubuntu.com/ubuntu focal-updates InRelease
    azure-arm: Hit:3 http://azure.archive.ubuntu.com/ubuntu focal-backports InRelease
    azure-arm: Hit:4 http://azure.archive.ubuntu.com/ubuntu focal-security InRelease
    azure-arm: Hit:5 https://packages.microsoft.com/ubuntu/20.04/prod focal InRelease
    azure-arm: Ign:6 https://packages.erlang-solutions.com/ubuntu focal InRelease
    azure-arm: Get:7 https://packages.erlang-solutions.com/ubuntu focal Release [3132 B]
    azure-arm: Get:8 https://packages.erlang-solutions.com/ubuntu focal Release.gpg [833 B]
    azure-arm: Ign:8 https://packages.erlang-solutions.com/ubuntu focal Release.gpg
    azure-arm: Reading package lists...
==> azure-arm: W: GPG error: https://packages.erlang-solutions.com/ubuntu focal Release: The following signatures were invalid: BADSIG D208507CA14F4FCA Erlang Solutions Ltd. <packages@erlang-solutions.com>
==> azure-arm: E: The repository 'https://packages.erlang-solutions.com/ubuntu focal Release' is not signed.
    azure-arm: Reading package lists...
    azure-arm: Building dependency tree...
    azure-arm: Reading state information...
==> azure-arm: E: Unable to locate package esl-erlang
    azure-arm: Downloading 'https://github.com/erlang/rebar3/releases/latest/download/rebar3' to '/usr/local/bin/rebar3'...
    azure-arm: Download completed
    azure-arm: Pester v5.3.3
    azure-arm:
    azure-arm: Starting discovery in 1 files.
    azure-arm: Discovery found 100 tests in 577ms.
    azure-arm: Filter 'FullName' set to ('erlang').
    azure-arm: Filters selected 3 tests to run.
    azure-arm: Running tests.
    azure-arm:
    azure-arm: Running tests from '/imagegeneration/tests/Tools.Tests.ps1'
    azure-arm: Describing erlang
    azure-arm:   [-] erlang erl -version 235ms (203ms|33ms)
    azure-arm:    Command 'erl -version' has finished with exit code
    azure-arm:        /usr/bin/bash: erl: command not found
    azure-arm:    at "$ErlangCommand" | Should -ReturnZeroExitCode, /imagegeneration/tests/Tools.Tests.ps1:143
    azure-arm:    at <ScriptBlock>, /imagegeneration/tests/Tools.Tests.ps1:143
    azure-arm:   [-] erlang erlc -v 35ms (33ms|2ms)
    azure-arm:    Command 'erlc -v' has finished with exit code
    azure-arm:        /usr/bin/bash: erlc: command not found
    azure-arm:    at "$ErlangCommand" | Should -ReturnZeroExitCode, /imagegeneration/tests/Tools.Tests.ps1:143
    azure-arm:    at <ScriptBlock>, /imagegeneration/tests/Tools.Tests.ps1:143
    azure-arm:   [-] erlang rebar3 -v 13ms (12ms|1ms)
    azure-arm:    Command 'rebar3 -v' has finished with exit code
    azure-arm:        /usr/bin/env: ‘escript’: No such file or directory
    azure-arm:    at "$ErlangCommand" | Should -ReturnZeroExitCode, /imagegeneration/tests/Tools.Tests.ps1:143
    azure-arm:    at <ScriptBlock>, /imagegeneration/tests/Tools.Tests.ps1:143
    azure-arm: Tests completed in 1.15s
    azure-arm: Tests Passed: 0, Failed: 3, Skipped: 0 NotRun: 97
    azure-arm:
    azure-arm: Containers            : {[-] /imagegeneration/tests/Tools.Tests.ps1}
    azure-arm: Result                : Failed
    azure-arm: FailedCount           : 3
    azure-arm: FailedBlocksCount     : 0
    azure-arm: FailedContainersCount : 0
    azure-arm: PassedCount           : 0
    azure-arm: SkippedCount          : 0
    azure-arm: NotRunCount           : 97
    azure-arm: TotalCount            : 100
    azure-arm: Duration              : 00:00:01.1523868
    azure-arm: Executed              : True
    azure-arm: ExecutedAt            : 07/04/2022 11:14:26
    azure-arm: Version               : 5.3.3
    azure-arm: PSVersion             : 7.2.5
    azure-arm: PSBoundParameters     : {[Configuration, PesterConfiguration]}
    azure-arm: Plugins               : 
    azure-arm: PluginConfiguration   : 
    azure-arm: PluginData            : 
    azure-arm: Configuration         : PesterConfiguration
    azure-arm: DiscoveryDuration     : 00:00:00.5621498
    azure-arm: UserDuration          : 00:00:00.2570051
    azure-arm: FrameworkDuration     : 00:00:00.3332319
    azure-arm: Failed                : {[-] erlang erl -version, [-] erlang erlc -v, [-] erlan
    azure-arm:                         g rebar3 -v}
    azure-arm: FailedBlocks          : {}
    azure-arm: FailedContainers      : {}
    azure-arm: Passed                : {}
    azure-arm: Skipped               : {}
    azure-arm: NotRun                : {[ ] azcopy, [ ] azcopy10 link exists, [ ] Bicep, [ ] R
    azure-arm:                         ustup is installed…}
    azure-arm: Tests                 : {[ ] azcopy, [ ] azcopy10 link exists, [ ] Bicep, [ ] R
    azure-arm:                         ustup is installed…}
    azure-arm: CodeCoverage          : 
    azure-arm:
==> azure-arm: Exception: Test run has failed
```

### Platforms affected

- [ ] Azure DevOps
- [ ] GitHub Actions

### Virtual environments affected

- [ ] Ubuntu 18.04
- [X] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

20220626.1

### Is it regression?

Not sure

### Expected behavior

Erlang should be installed successfully with erl, erlc and escript CLI available.

### Actual behavior

Failing to install following CLI: erl, erlc and escript

### Repro steps

Run images/linux/scripts/installers/erlang.sh

**Comment by igorboskovic3** [comment]
Hi @gaui, thank you for reporting this error, we will take a look.

**Comment by SPALLADI** [comment]
Hi, Can we exclude the Erlang tool while building the image? Do we have any ETA on this?

**Comment by mayong43111** [comment]
> Hi @gaui, thank you for reporting this error, we will take a look.

I had the same problem today  :(

**Comment by mikhailkoliada** [comment]
> Hi, Can we exclude the Erlang tool while building the image? Do we have any ETA on this?

Hello, we have no ETA yet, we are awaiting a response from the repo owners first.

**Comment by jappenzesr** [comment]
> > Hi, Can we exclude the Erlang tool while building the image? Do we have any ETA on this?
> 
> try remove it ("{{template_dir}}/scripts/installers/erlang.sh",) on [ubuntu2004.json](https://github.com/actions/virtual-environments/blob/main/images/linux/ubuntu2004.json)

Simply excluding erlang is not possible because it is also referenced from SoftwareReportGenerator:
```
==> azure-arm: Provisioning with shell script: /home/vsts/work/1/s/virtual-environments/images/linux/scripts/base/apt-mock-remove.sh
==> azure-arm: Provisioning with shell script: /tmp/packer-shell804581750
==> azure-arm: /imagegeneration/SoftwareReport/SoftwareReport.Generator.ps1 : The term 'erl' is not recognized as a name of a cmdlet, function, script file, or executable program.
```

which is due to 

```
function Get-ErlangVersion {
    $erlangVersion = (erl -eval '{ok, Version} = file:read_file(filename:join([code:root_dir(), "releases", erlang:system_info(otp_release), ''OTP_VERSION''])), io:fwrite(Version), halt().' -noshell)
    $shellVersion = (erl -eval 'erlang:display(erlang:system_info(version)), halt().' -noshell).Trim('"')
    return "Erlang $erlangVersion (Eshell $shellVersion)"
}
```
In general, it would be great to not have an explicit dependencies in the software report generator, but instead to exclude the specific software (erlang in this case) from the generated report if it not found.

**Comment by jappenzesr** [comment]
@mikhailkoliada can you please post the link to where this has been reported to the repo owners, thanks

**Comment by SPALLADI** [comment]
I am also facing error due to softwarereport generator error.
==> azure-arm: /imagegeneration/SoftwareReport/SoftwareReport.Generator.ps1 : The term 'erl' is not recognized as a name of a cmdlet, function, script file, or executable program.

==> azure-arm: Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

==> azure-arm: + CategoryInfo          : ObjectNotFound: (erl:String) [SoftwareReport.Generator.ps1], CommandNotFoundException

==> azure-arm: + FullyQualifiedErrorId : CommandNotFoundException,SoftwareReport.Generator.ps1

==> azure-arm: Provisioning step had errors: Running the cleanup provisioner, if present...

**Comment by al-cheb** [comment]
cc @garazdawi, could you please escalate?

**Comment by ALTrijssenaar** [comment]
Same problem here. Trying to recreate the same images that the Azure Pipelines are using, but the current agent with build label ubuntu20/20220626.1 are not able to be rebuilt again due to:

    azure-arm: Err:7 https://packages.erlang-solutions.com/ubuntu focal/contrib amd64 esl-erlang amd64 1:25.0.2-1
    azure-arm:   File has unexpected size (40579688 != 40585792). Mirror sync in progress? [IP: 65.9.86.96 443]
    azure-arm:   Hashes of expected file:
    azure-arm:    - SHA256:8645d44d27d641ba927f4899aabfd1e6317b56efb620495051b899de5d3ca57f
    azure-arm:    - SHA1:77df6ed1e992c5714ca968e7637500ee1604e60f [weak]
    azure-arm:    - MD5Sum:1c383df15d0fa762c9312daca01c5175 [weak]
    azure-arm:    - Filesize:40585792 [weak]
    azure-arm: Fetched 5548 kB in 0s (40.2 MB/s)

**Comment by jappenzesr** [comment]
Above workaround solved the problem for us, many thanks. 

Please consider the refactoring proposed above to remove the tight coupling between the set of tools installed, and the SoftwareReport generator. Allowing tools to be excluded easily by removing the installation script from the packer file would be beneficial not only in cases such as this one, but also more generally. E.g. if I would like to prepare a build agent based on this template, but remove all tools that I know are not used within my environment in order to reduce disk footprint, image buildtime and inventory security risks.

**Comment by gaui** [comment]
Thank you for the workaround @mikhailkoliada :pray:

**Comment by mikhailkoliada** [comment]
The fix was reverted now as everything looks fine by default.

**Comment by HoLengZai** [comment]
@mikhailkoliada 
Facing the same issue today... Seems the issue is back again..
In the meantime, I will overwrite the original erlang.sh by your workaround #5867 in my pipeline.
Hope you will consider @jappenzesr suggestions https://github.com/actions/runner-images/issues/5859#issuecomment-1177461072
