### ISSUE TITLE
Install-PyPy Fails

### ISSUE THREAD

**Issue by raherrebrugh** [actions/virtual-environments#5860]
### Description

Python installation fails in Install-PyPy.ps1 when getting the list of PyPy releases

The following error message is thrown
```
==> vhd: At C:\Windows\Temp\script-62c33980-23e8-aec5-701e-7b79bcb44dc9.ps1:83 char:17
==> vhd: + ... yVersions = Invoke-RestMethod https://downloads.python.org/pypy/versi ...
==> vhd: +                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
==> vhd:     + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebExc
==> vhd:    eption
==> vhd:     + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand
```

When manually navigating to https://downloads.python.org/pypy/versions.json I get the following error
```
Error 503 certificate has expired
certificate has expired

Error 54113
Details: cache-ams21071-AMS 1657002125 3472553759

Varnish cache server
```

It is unclear to me whether this file is supposed to be there but not available (temporarily) or that it was moved and the script needs to be updated

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [X] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

1.185.1924

### Is it regression?

1.185.1924

### Expected behavior

Install-PyPy is installed/executed succesfully

### Actual behavior

Script fails with error (see description)

### Repro steps

Build packer

**Comment by al-cheb** [comment]
This is an external issue you could track one - https://foss.heptapod.net/pypy/pypy/-/issues/3773 .

**Comment by jappenzesr** [comment]
This also affects the build of the Ubuntu virtual environments.

**Comment by mikhailkoliada** [comment]
pypy upstream fixed it
