### ISSUE TITLE
 terraform: command not found

### ISSUE THREAD

**Issue by SPALLADI** [actions/virtual-environments#5865]
### Description

    azure-arm:   [-] terraform 109ms (79ms|31ms)

    azure-arm:    Command 'terraform --version' has finished with exit code

    azure-arm:        /usr/bin/bash: terraform: command not found
    azure-arm:    at "terraform --version" | Should -ReturnZeroExitCode, /imagegeneration/tests/Tools.Tests.ps1:219

    azure-arm:    at <ScriptBlock>, /imagegeneration/tests/Tools.Tests.ps1:219

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

[](url)

### Is it regression?

yes

### Expected behavior

    azure-arm:   [-] terraform 109ms (79ms|31ms)
    azure-arm:    Command 'terraform --version' has finished with exit code
    azure-arm:        /usr/bin/bash: terraform: command not found
    azure-arm:    at "terraform --version" | Should -ReturnZeroExitCode, /imagegeneration/tests/Tools.Tests.ps1:219
    azure-arm:    at <ScriptBlock>, /imagegeneration/tests/Tools.Tests.ps1:219

### Actual behavior

It should work without issue

### Repro steps

    azure-arm:   [-] terraform 109ms (79ms|31ms)
    azure-arm:    Command 'terraform --version' has finished with exit code
    azure-arm:        /usr/bin/bash: terraform: command not found
    azure-arm:    at "terraform --version" | Should -ReturnZeroExitCode, /imagegeneration/tests/Tools.Tests.ps1:219
    azure-arm:    at <ScriptBlock>, /imagegeneration/tests/Tools.Tests.ps1:219

**Comment by al-cheb** [comment]
Nightly build for Ubuntu Server 22.04 is green - https://github.visualstudio.com/virtual-environments/_build/results?buildId=127542&view=logs&j=011e1ec8-6569-5e69-4f06-baf193d1351e&t=5431112d-2b61-5a5f-7042-ef698f761043
