### ISSUE TITLE
reconsider proposals adding Firebase CLI

### ISSUE THREAD

**Issue by mklarsen** [actions/virtual-environments#5866]
Hi There,
basically I disagree in the result/solution given: Use GitHub-Actions. 
if so, why even make these platforms like Ubuntu, Mac, etc.?

My take on these platforms (Like Ubuntu, Mac et.c) at there were super swiss army knives and therefor had many tools preinstalled.  

In my case I have a flutter barley. Who will build an android, ios and a Docker / web images. all in all it takes 20-30 just to install tools. That is, before anything is built at all.   So if I have to build / test my app 10-20 times a day, then the use of github actions ends up being very expensive, probably WAY too expensive.

Please reopen this case, or my issue.

And btw. If I can participate, help make these platforms better then I would like to participate, just reach out. :-)

BR,
Martin

_Originally posted by @mklarsen in https://github.com/actions/virtual-environments/issues/3666#issuecomment-1174912025_

**Comment by mikhailkoliada** [comment]
@mklarsen Hello!

We would not like to have firebase-cli pre-installed, the installation time is literally 10 seconds so we strongly believe that the overhead of not having this tool pre-installed is not really big, even if someone has multiple builds a day. The fact that a project might have a ready to use installators for multiple OSes does not play a key role when we decide what we might add and what not, we only appeal to common sense with the support of the [software and image guidelines](https://github.com/actions/virtual-environments/blob/main/docs/software-and-images-guidelines.md).

If you have questions please feel free to reach us out.
