### ISSUE TITLE
Update/Add OCI cli

### ISSUE THREAD

**Issue by theelderbeever** [actions/virtual-environments#5869]
### Tool name

Oracle Cloud CLI

### Tool license

Universal Permissive License 1.0 and the Apache License 2.0

### Add or update?

- [X] Add
- [ ] Update

### Desired version

latest

### Brief description of tool

CLI for managing Oracle cloud resources. Necessary for authenticating to Oracle Cloud as well.

### URL for tool's homepage

https://github.com/oracle/oci-cli

### Provide a basic test case to validate the tool's functionality.

```bash
oci -v
```

### Platforms where you need the tool

- [ ] Azure DevOps
- [X] GitHub Actions

### Virtual environments where you need the tool

- [X] Ubuntu 18.04
- [X] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Can this tool be installed during the build?

```bash
# Note that the secrets in this setup are necessary to use the cli with the cloud however, they are not necessary for the installation of the client.
      - name: Setup OCI CLI
        run: |
          mkdir ${HOME}/.oci
          echo "${{ secrets.ORACLE_CLI_CONFIG }}" > ${HOME}/.oci/config
          echo "${{ secrets.ORACLE_CLI_KEY_FILE }}" > ${HOME}/.oci/key.pem
          curl -L -O https://raw.githubusercontent.com/oracle/oci-cli/master/scripts/install/install.sh
          chmod +x install.sh
          ./install.sh --accept-all-defaults
          echo "${HOME}/bin" >> $GITHUB_PATH
          exec -l $SHELL
          $HOME/bin/oci setup repair-file-permissions --file ${HOME}/.oci/config
          oci setup repair-file-permissions --file ${HOME}/.oci/key.pem
```

### Tool installation time in runtime

<60s

### Are you willing to submit a PR?

With a little help, yes

**Comment by igorboskovic3** [comment]
Hi @theelderbeever, thank you for your proposal. We will consider and get back to you.

**Comment by igorboskovic3** [comment]
Hi @theelderbeever we already had this feature request and you can check it [here](https://github.com/actions/virtual-environments/issues/3909), so I will close this one as duplicated issue. 
Thank you
