### ISSUE TITLE
Azure DevOps Hosted Agents

### ISSUE THREAD

**Issue by leonardoalmiron** [actions/virtual-environments#5875]
### Tool name

Azure DevOps Hosted Agents

### Tool license

visual studio professional

### Add or update?

- [X] Add
- [ ] Update

### Desired version

latest

### Brief description of tool

Availability to have the powershell module Az pre-installed in Azure DevOps hosted agents since this causes lot of delays in connecting to Azure portal through the Azure DevOps Pipelines.

### URL for tool's homepage

dev.azure.com

### Platforms where you need the tool

- [X] Azure DevOps
- [ ] GitHub Actions

### Virtual environments where you need the tool

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [X] Windows Server 2019
- [ ] Windows Server 2022

### Can this tool be installed during the build?

```bash
yes it can
```

### Tool installation time in runtime

between 3 to 20 minutes

**Comment by igorboskovic3** [comment]
Hi @leonardoalmiron , thank you for your request, we will look and get back to you.

**Comment by ddobranic** [comment]
Hi @leonardoalmiron, you can see that Az module has been preinstalled and list of other installed modules for Windows Server 2019 [here](https://github.com/actions/virtual-environments/blob/main/images/win/Windows2019-Readme.md#azure-powershell-modules)

**Comment by leonardoalmiron** [comment]
Hi team,

Is this pre-installed in Azure Hosted Agents from DevOps?

Regards,

Leonardo Almirón
Tech Arch Delivery Specialist
Accenture - CIO – DaaS SQL Team – MS Azure
P
Before printing this e-mail think carefully if it is necessary

From: Dusko Dobranic ***@***.***>
Sent: Friday, July 8, 2022 4:03 AM
To: actions/virtual-environments ***@***.***>
Cc: Almiron, Leonardo ***@***.***>; Mention ***@***.***>
Subject: [External] Re: [actions/virtual-environments] Azure DevOps Hosted Agents (Issue #5875)

This message is from an EXTERNAL SENDER - be CAUTIOUS, particularly with links and attachments.
________________________________


Hi @leonardoalmiron<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_leonardoalmiron&d=DwMCaQ&c=eIGjsITfXP_y-DLLX0uEHXJvU8nOHrUK8IrwNKOtkVU&r=yFsv1SJSGrUwocxSiV_1JAFymwxKS0G1yqQiHaM7Gws&m=nyQCLR_ixaEjSk4BjM9NtXzrl_dafZ2Za7JpN2Z_2QTPgY907DkSj2TZWlBn46IQ&s=TTBgft1Dt1YaPYjTOKnhzhWebuESkt5ppOZUQJn8WJI&e=>, you can see that Az module has been preinstalled and list of other installed modules for Windows Server 2019 here<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_actions_virtual-2Denvironments_blob_main_images_win_Windows2019-2DReadme.md-23azure-2Dpowershell-2Dmodules&d=DwMCaQ&c=eIGjsITfXP_y-DLLX0uEHXJvU8nOHrUK8IrwNKOtkVU&r=yFsv1SJSGrUwocxSiV_1JAFymwxKS0G1yqQiHaM7Gws&m=nyQCLR_ixaEjSk4BjM9NtXzrl_dafZ2Za7JpN2Z_2QTPgY907DkSj2TZWlBn46IQ&s=0aRurA8hxgRHuhmK_vjVggNmznM8sHeglNDQSnIHpu0&e=>

—
Reply to this email directly, view it on GitHub<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_actions_virtual-2Denvironments_issues_5875-23issuecomment-2D1178629956&d=DwMCaQ&c=eIGjsITfXP_y-DLLX0uEHXJvU8nOHrUK8IrwNKOtkVU&r=yFsv1SJSGrUwocxSiV_1JAFymwxKS0G1yqQiHaM7Gws&m=nyQCLR_ixaEjSk4BjM9NtXzrl_dafZ2Za7JpN2Z_2QTPgY907DkSj2TZWlBn46IQ&s=-Msld3e9KwiWTroSNfT6SulX-c4RoVLsG4XijjjjGBk&e=>, or unsubscribe<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AZ62AC3ZJQLORNZMBT2WQZ3VS7HBVANCNFSM526MPFPQ&d=DwMCaQ&c=eIGjsITfXP_y-DLLX0uEHXJvU8nOHrUK8IrwNKOtkVU&r=yFsv1SJSGrUwocxSiV_1JAFymwxKS0G1yqQiHaM7Gws&m=nyQCLR_ixaEjSk4BjM9NtXzrl_dafZ2Za7JpN2Z_2QTPgY907DkSj2TZWlBn46IQ&s=2dgUMeLa67buNSnq-_-mDFmh66zJAaOA7huIFCPdfsg&e=>.
You are receiving this because you were mentioned.Message ID: ***@***.******@***.***>>

________________________________

This message is for the designated recipient only and may contain privileged, proprietary, or otherwise confidential information. If you have received it in error, please notify the sender immediately and delete the original. Any other use of the e-mail by you is prohibited. Where allowed by local law, electronic communications with Accenture and its affiliates, including e-mail and instant messaging (including content), may be scanned by our systems for the purposes of information security and assessment of internal compliance with Accenture policy. Your privacy is important to us. Accenture uses your personal data only in compliance with data protection laws. For further information on how Accenture processes your personal data, please see our privacy statement at https://www.accenture.com/us-en/privacy-policy.
______________________________________________________________________________________

www.accenture.com

**Comment by miketimofeev** [comment]
@leonardoalmiron Az Powershell 7.3.2 is available in all AzDO hosted agents.
