### ISSUE TITLE
ubuntu-22.04 action runners missing python3-oauth

### ISSUE THREAD

**Issue by stuarta** [actions/virtual-environments#5895]
### Description

Attempts to install python3-oauth package on an ubuntu-22.04 runner fail with the following error
`
E: Unable to locate package python3-oauth
Error: Process completed with exit code 100.
`

This package is available on a normal ubuntu-22.04 installation, and is available for installation on a ubuntu-20.04 runner

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

https://github.com/MythTV/mythtv/actions/runs/2656411496

### Is it regression?

yes, works on 20.04, see above build link

### Expected behavior

The python3-oauth package is installable

### Actual behavior

Installation fails, due to missing package, and therefore the action run fails on ubuntu-22.04

### Repro steps

Setup an action workflow that attempts the following
- sudo apt install python3-oauth

This fails on ubuntu-22.04 action runner, but works on 20.04. The package is available on a normal ubuntu-22.04 installation

**Comment by panekj** [comment]
It's not available on Ubuntu 22.04
[20.04](https://packages.ubuntu.com/search?suite=focal&searchon=names&keywords=python3-oauth)
[22.04](https://packages.ubuntu.com/search?suite=jammy&searchon=names&keywords=python3-oauth)
