### ISSUE TITLE
Add .NET 6 SDKs for macOS virtual environments

### ISSUE THREAD

**Issue by mattjohnsonpint** [actions/virtual-environments#5896]
### Tool name

.NET 6 SDK

### Tool license

MIT

### Add or update?

- [X] Add
- [X] Update

### Desired version

6.0.xxx (latest)

### Brief description of tool

The macOS virtual images only include the .NET SDK through version 5, which is out of support.  While .NET 6 can be installed via the `setup-dotnet` action, that shouldn't be required anymore, because:

- Windows and Ubuntu images already include .NET 6, and there's no good reason macOS shouldn't have it preinstalled as well (AFAIK).
- Issue #5193 previously requested this, but it was closed [stating](https://github.com/actions/virtual-environments/issues/5193#issuecomment-1073868487) that it would be done when Visual Studio 2022 for Mac was added.  This is silly, because .NET doesn't depend on VS, it's the other way around.
- Even so, VS 2022 for Mac was added already. See issue #5542 #5601.  Still we don't have the .NET 6 SDK pre-installed.  The [recommendation](https://github.com/actions/virtual-environments/issues/5601#issuecomment-1145804281) continues to be to install it manually.

Please understand - most people that use .NET in a CI/CD environment do not need the Visual Studio IDE.  They need the .NET SDK.  The only reason I'm aware of to have the IDE on CI/CD is if you are building plugins for Visual Studio itself.

Please - just add the .NET 6 SDKs to macOS in the exact same way you already have the .NET 5 and .NET Core 3.1 SDKs, and have already done for Ubuntu.  This should be trivial.

### URL for tool's homepage

https://dotnet.microsoft.com/en-us/download/dotnet/6.0

### Platforms where you need the tool

- [ ] Azure DevOps
- [X] GitHub Actions

### Virtual environments where you need the tool

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 10.15
- [X] macOS 11
- [X] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

**Comment by miketimofeev** [comment]
@mattjohnsonpint we found out that our Visual Studio 2022 installation method doesn't bring .Net 6 component. We will install .Net 6 additionally on macOS-11 and macOS-12 images. The new deployment will happen this week.

**Comment by mattjohnsonpint** [comment]
Thank you. 👍

**Comment by al-cheb** [comment]
The new images with .Net 6.0 on board have been deployed.
