### ISSUE TITLE
Update/Add Valgrind

### ISSUE THREAD

**Issue by thoward27** [actions/virtual-environments#59]
**Tool information**
- Tool name: valgrind
- Add or update? add
- Desired version: >= 3.14
- Approximate size: 
- If this is an add request:
  - Brief description of tool: Debugging and profiling executables
  - URL for tool's homepage: http://valgrind.org/

**Virtual environments affected**
- [ ] macOS 10.14
- [x] Ubuntu 16.04 LTS
- [x] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Can this tool be installed during the build?**
Not that I am aware of, but if it is, please tell me.

**Are you willing to submit a PR?**
It depends on how much work it would be. I am not familiar with the underlying structure here, but if someone can guide me I'd be willing to give it a shot.

**Comment by Kreyren** [comment]
>  Not that I am aware of, but if it is, please tell me. -- @thoward27 

in theory `apt install -y valgrind` and then passing configuration which is pita

**Comment by thoward27** [comment]
Yes @Kreyren but last time I checked `apt install` isn't allowed in actions. Has this changed?

**Comment by Kreyren** [comment]
@thoward27 Not that i am aware of, but i don't have a way to test the contribution due to the requirement for Azure VM.

**Comment by maxim-lobanov** [comment]
Tool can be installed in runtime using the following script:
```
sudo apt install -y valgrind
```
Installation takes about 13 seconds

**Comment by thoward27** [comment]
Is `apt install` allowed inside of actions now?

**Comment by maxim-lobanov** [comment]
@thoward27 , yep, you can install any software in runtime if needs

**Comment by alepauly** [comment]
@thoward27 thanks for your suggestion and sorry it took so long to respond. As @maxim-lobanov mentioned, yes you should be able to install during your build. I'll close this request because I don't think it's something we need to bake into the environment but let me know if you have any questions.

**Comment by juanmanzanero** [comment]
Hello! Sorry to open this post again, but although "sudo apt install -y valgrind" worked in recent times, it does not since 2 days ago. This is the output of the command, any clue on how to proceed now?

```
Run sudo apt install -y valgrind

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

Reading package lists...
Building dependency tree...
Reading state information...
The following additional packages will be installed:
  gdb libbabeltrace1 libboost-regex1.[7](https://github.com/juanmanzanero/fastest-lap/runs/5415587068?check_suite_focus=true#step:6:7)1.0 libc6-dbg libipt2
  libsource-highlight-common libsource-highlight4v5 libxxhash0
Suggested packages:
  gdb-doc gdbserver valgrind-dbg valgrind-mpi kcachegrind alleyoop valkyrie
The following NEW packages will be installed:
  gdb libbabeltrace1 libboost-regex1.71.0 libc6-dbg libipt2
  libsource-highlight-common libsource-highlight4v5 libxxhash0 valgrind
0 upgraded, 9 newly installed, 0 to remove and 33 not upgraded.
Need to get 35.1 MB of archives.
After this operation, 1[8](https://github.com/juanmanzanero/fastest-lap/runs/5415587068?check_suite_focus=true#step:6:8)1 MB of additional disk space will be used.
Get:1 http://azure.archive.ubuntu.com/ubuntu focal/main amd64 libbabeltrace1 amd64 1.5.8-1build1 [156 kB]
Get:2 http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu focal/main amd64 gdb amd64 10.2-0ubuntu1~20.04~1 [3282 kB]
Get:3 http://azure.archive.ubuntu.com/ubuntu focal/universe amd64 libipt2 amd64 2.0.1-1 [42.8 kB]
Get:4 http://azure.archive.ubuntu.com/ubuntu focal/universe amd64 libsource-highlight-common all 3.1.8-1.2build5 [50.7 kB]
Get:5 http://azure.archive.ubuntu.com/ubuntu focal/universe amd64 libboost-regex1.71.0 amd64 1.71.0-6ubuntu6 [471 kB]
Get:6 http://azure.archive.ubuntu.com/ubuntu focal/universe amd64 libsource-highlight4v5 amd64 3.1.8-1.2build5 [232 kB]
Get:7 http://azure.archive.ubuntu.com/ubuntu focal/universe amd64 libxxhash0 amd64 0.7.3-1 [15.3 kB]
Err:8 http://azure.archive.ubuntu.com/ubuntu focal-updates/main amd64 libc6-dbg amd64 2.31-0ubuntu[9](https://github.com/juanmanzanero/fastest-lap/runs/5415587068?check_suite_focus=true#step:6:9).2
  404  Not Found [IP: 40.81.13.82 80]
Get:9 http://azure.archive.ubuntu.com/ubuntu focal-updates/main amd64 valgrind amd64 1:3.15.0-1ubuntu9.1 [20.3 MB]
Fetched 24.6 MB in 60s (4[10](https://github.com/juanmanzanero/fastest-lap/runs/5415587068?check_suite_focus=true#step:6:10) kB/s)
E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/main/g/glibc/libc6-dbg_2.31-0ubuntu9.2_amd64.deb  404  Not Found [IP: 40.81.[13](https://github.com/juanmanzanero/fastest-lap/runs/5415587068?check_suite_focus=true#step:6:13).82 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
Error: Process completed with exit code 100.
```

**Comment by thoward27** [comment]
@juanmanzanero have you tried executing `apt-get update`? I would also suggest upgrading your base image as a potential option

**Comment by juanmanzanero** [comment]
It works!!! Thank you very much!!!

**Comment by bradleypeterson** [comment]
> @juanmanzanero have you tried executing `apt-get update`? I would also suggest upgrading your base image as a potential option

Thank you. I used this:

`run: sudo apt install -y valgrind`

And then I got this error:

```
Run sudo apt install -y valgrind
... edited down ... 
Err:10 http://security.ubuntu.com/ubuntu jammy-updates/main amd64 libc6-dbg amd64 2.35-0ubuntu3.1
  404  Not Found [IP: 52.147.219.192 80]
Fetched 19.0 MB in 1s (29.5 MB/s)
E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/g/glibc/libc6-dbg_2.35-0ubuntu3.1_amd64.deb  404  Not Found [IP: 52.147.219.192 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
Error: Process completed with exit code 100.
```

So I updated mine to this:

`run: sudo apt update && sudo apt install -y valgrind`

That did the trick.
