### ISSUE TITLE
Cocoapods version unstable

### ISSUE THREAD

**Issue by piterwilson** [actions/virtual-environments#590]
**Describe the bug**
We have a pipeline setup for a MacOS project with a step that runs:

```
pod install
```
Our vm image was set to 
```
vmImage: 'macOS-latest'
```
It looks like some time in the last days the cocoapods version installed there changed to `1.9.1` and then back to `1.9.0`. This is causing problems and delays as the build will break with the error:

```
Verifying no changes
[!] There were changes to the lockfile in deployment mode:
COCOAPODS:
  New Lockfile: 1.9.0
  Old Lockfile: 1.9.1
```
I checked the specs on the vimage lister here: https://github.com/actions/virtual-environments/blob/master/images/macos/macos-10.15-Readme.md and they specify `1.9.0`. Then i found this other conflicting spec for the same image: https://github.com/microsoft/azure-pipelines-image-generation/blob/master/images/macos/macos-10.15-Readme.md which specifies `1.9.1`

I can see that the latter repo is declared obsolete and replaced with the former but it raises the question to whether we should expect the cocoapods version to stay consistent. 

What can we expect from this? are there any best practices we should employ to avoid having our pipeline break from this seemly random changes to the cocoapods version? Is there a way to specify this version or lock it down to something specific? 

**Area for Triage**: 

Apple

**Question, Bug, or Feature?**: 

Question

**Virtual environments affected**
- [ X] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Expected behavior**
Cocoapods version to be constant and predictable OR way to set cocoapods version

**Actual behavior**
Cocoapods version changed from 1.9.0 to 1.9.1 and then back to 1.9.0

1. Step with `pod install` in pipeline, vmImage set to `macOS-latest`
2. run step
3. step fails

```
Verifying no changes
[!] There were changes to the lockfile in deployment mode:
COCOAPODS:
  New Lockfile: 1.9.1
  Old Lockfile: 1.9.0
```
4. devs update their cocoapods
5. run pipeline sometime later
6. pipeline fails

```
Verifying no changes
[!] There were changes to the lockfile in deployment mode:
COCOAPODS:
  New Lockfile: 1.9.0
  Old Lockfile: 1.9.1
```

**Comment by al-cheb** [comment]
Hello, @piterwilson 
I think it's related with image deployment process, because it's impossible to update all VM's at the same time and some builds may have queued on previous version of image. Let's try to check in 5 hours is the issue still exist.

As workaround update cocoapods to the latest version:
```
echo "Updating cocoapods..."
gem uninstall cocoapods
gem install cocoapods
```

**Comment by maxim-lobanov** [comment]
Hello @piterwilson ,
- https://github.com/actions/virtual-environments/blob/master/images/macos/macos-10.15-Readme.md points to the documentation for GA macOS image.
- https://github.com/microsoft/azure-pipelines-image-generation/blob/master/images/macos/macos-10.15-Readme.md points to the documentation for AzDO macOS image.
Actually, image content is the same but they can be updated in the different time.

The updating of all VMs take some time so during the machine deployment your build can be scheduled on any machine (with old image version or the new one).

Usually, it is not a problem but cocoapods is the tool that depend on accurate version and even patch update can break your build. On our images we install the latest available version always.
I would suggest the following pre-build step:
```
CUR_COCOAPODS_VER=`sed -n -e 's/^COCOAPODS: \([0-9.]*\)/\1/p' ios/Podfile.lock`
ENV_COCOAPODS_VER=`pod --version`

# check if not the same version, reinstall cocoapods version to current project's
if [ $CUR_COCOAPODS_VER != $ENV_COCOAPODS_VER ];
then
    echo "Uninstalling all CocoaPods versions"
    sudo gem uninstall cocoapods --all --executables
    echo "Installing CocoaPods version $CUR_COCOAPODS_VER"
    sudo gem install cocoapods -v $CUR_COCOAPODS_VER
else 
    echo "CocoaPods version is suitable for the project"
fi;
```
It will add ~ 10 seconds to the build but you will be able to control cocoapods version using your Podfile.lock file

**Comment by piterwilson** [comment]
Thank you for the quick response and suggestion. The script above should helps us to have a controlled migration on our end when updates to cocoapods occur.

**Comment by maxim-lobanov** [comment]
Btw, @piterwilson , there is an action [Setup Cocoapods](https://github.com/marketplace/actions/setup-cocoapods) that does pretty the same like script above but could be more convenient to use in the pipeline.
