### ISSUE TITLE
Rollback ORAS CLI version to 0.12 instead of 0.13 as it breaks login for GHCR

### ISSUE THREAD

**Issue by suyash691** [actions/virtual-environments#5906]
### Tool name

ORAS CLI

### Tool license

MIT License

### Add or update?

- [ ] Add
- [X] Update

### Desired version

0.12

### Platforms where you need the tool

- [ ] Azure DevOps
- [X] GitHub Actions

### Virtual environments where you need the tool

- [X] Ubuntu 18.04
- [X] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Tool installation time in runtime

Less than 10s

### Are you willing to submit a PR?

Yes

**Comment by suyash691** [comment]
Raised [PR](https://github.com/actions/virtual-environments/pull/5907)

**Comment by al-cheb** [comment]
> Raised [PR](https://github.com/actions/virtual-environments/pull/5907)

You can easily install oras in runtime:
```
 - run: |
        curl -LO https://github.com/oras-project/oras/releases/download/v0.12.0/oras_0.12.0_linux_amd64.tar.gz
        sudo tar xzf oras_0.12.0_linux_amd64.tar.gz -C /usr/local/bin oras
```

**Comment by suyash691** [comment]
Yes i understand but this is to ensure better out of the box experience with GHCR for actions

**Comment by miketimofeev** [comment]
@suyash691 do you know how long will it take to release the new ORAS CLI version with the fix? I'm asking as we tend to start rollouts on Monday but can wait till Tuesday if the fix is available early next week.

**Comment by suyash691** [comment]
I am not sure, the maintainers for ORAS CLI have yet to respond to my request.
That is why I wanted to ensure that we are fixing the experience for GitHub customers first; WRT the actual fix in the newer version i'll report back with to this issue when we can upgrade the ORAS CLI

**Comment by suyash691** [comment]
Updating here from the issue in ORAS CLI. The newer version has removed support for protocol detection, which is why we were seeing the above issue. They are still considering whether to add back protocol detection or not

**Comment by miketimofeev** [comment]
@suyash691 I'm going to close this as external then. Feel free to contact us if you have any objections.
Thank you!
