### ISSUE TITLE
errors building Linux VHD - packer ssh error

### ISSUE THREAD

**Issue by jeffpuckett** [actions/virtual-environments#5911]
### Description

Here is the error I'm getting.

==> azure-arm.build_vhd: Running builder ...
==> azure-arm.build_vhd: Getting tokens using client secret
==> azure-arm.build_vhd: Getting tokens using client secret
    azure-arm.build_vhd: Creating Azure Resource Manager (ARM) client ...
==> azure-arm.build_vhd: Warning: You are using Azure Packer Builder to create VHDs which is being deprecated, consider using Managed Images. Learn more https://www.packer.io/docs/builders/azure/arm#azure-arm-builder-specific-options
==> azure-arm.build_vhd: WARNING: Zone resiliency may not be supported in East US, checkout the docs at https://docs.microsoft.com/en-us/azure/availability-zones/
==> azure-arm.build_vhd: Getting source image id for the deployment ...
==> azure-arm.build_vhd:  -> SourceImageName: '/subscriptions/8962376a-03e2-44a3-8c90-e62403de6736/providers/Microsoft.Compute/locations/East US/publishers/canonical/ArtifactTypes/vmimage/offers/0001-com-ubuntu-server-jammy/skus/22_04-lts/versions/latest'
==> azure-arm.build_vhd: Creating resource group ...
==> azure-arm.build_vhd:  -> ResourceGroupName : 'pkr-Resource-Group-pumwpsl724'
==> azure-arm.build_vhd:  -> Location          : 'East US'
==> azure-arm.build_vhd:  -> Tags              :
==> azure-arm.build_vhd: Validating deployment template ...
==> azure-arm.build_vhd:  -> ResourceGroupName : 'pkr-Resource-Group-pumwpsl724'
==> azure-arm.build_vhd:  -> DeploymentName    : 'pkrdppumwpsl724'
==> azure-arm.build_vhd: Deploying deployment template ...
==> azure-arm.build_vhd:  -> ResourceGroupName : 'pkr-Resource-Group-pumwpsl724'
==> azure-arm.build_vhd:  -> DeploymentName    : 'pkrdppumwpsl724'
==> azure-arm.build_vhd:
==> azure-arm.build_vhd: Getting the VM's IP address ...
==> azure-arm.build_vhd:  -> ResourceGroupName   : 'pkr-Resource-Group-pumwpsl724'
==> azure-arm.build_vhd:  -> PublicIPAddressName : 'pkrippumwpsl724'
==> azure-arm.build_vhd:  -> NicName             : 'pkrnipumwpsl724'
==> azure-arm.build_vhd:  -> Network Connection  : 'PublicEndpoint'
==> azure-arm.build_vhd:  -> IP Address          : '20.124.248.125'
==> azure-arm.build_vhd: Waiting for SSH to become available...
==> azure-arm.build_vhd: Error waiting for SSH: Packer experienced an authentication error when trying to connect via SSH. This can happen if your username/password are wrong. You may want to double-check your credentials as part of your debugging process. original error: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain
==> azure-arm.build_vhd: 

I'm running it in a pipeline like this

        steps:
        - powershell: |
            git clone https://github.com/actions/virtual-environments.git
          displayName: git clone virtual-environments
          workingDirectory: '$(Agent.BuildDirectory)'
        - powershell: |
            Install-Module -Name Az -Repository PSGallery -Force -AllowClobber 
          displayName: install AZ Powershell Module
        - powershell: |
            az extension add -n storage-preview
          displayName: Install storage-preview extension
        - powershell: |
            Set-Location $(Agent.BuildDirectory)\virtual-environments
            Import-Module .\helpers\GenerateResourcesAndImage.ps1
            GenerateResourcesAndImage -SubscriptionId "*****" -ResourceGroupName "$(resourceGroup)" -ImageGenerationRepositoryRoot "$pwd" -ImageType Ubuntu2204 -AzureLocation "East US" -AzureClientId "*****" -AzureClientSecret "$env:SECRET" -AzureTenantId '*****' -RestrictToAgentIpAddress -Force -OnError cleanup

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Current agent version: '2.204.0'

### Is it regression?

n/a

### Expected behavior

no errors

### Actual behavior

it's broken halp

### Repro steps

see description

**Comment by al-cheb** [comment]
Hello @jeffpuckett.
You should update packer version to the latest one 1.8.2 - https://www.packer.io/downloads .
