### ISSUE TITLE
Update Clang/LLVM

### ISSUE THREAD

**Issue by RytoEX** [actions/virtual-environments#5915]
### Tool name

Clang/LLVM

### Tool license

Apache-2.0 WITH LLVM-exception

### Add or update?

- [ ] Add
- [X] Update

### Desired version

14.0.6

### Platforms where you need the tool

- [ ] Azure DevOps
- [X] GitHub Actions

### Virtual environments where you need the tool

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

**Comment by mikhailkoliada** [comment]
Hi!

14.0.6 is only available in 22.10 for now, there is no ETA when it will be available in the LTS repo, but as soon it is, it will be released as a part of the ubuntu 22.04 image.
