### ISSUE TITLE
Add WSL2 to the Windows 2022 image

### ISSUE THREAD

**Issue by nzbr** [actions/virtual-environments#5920]
### Tool name

Windows Subsystem for Linux version 2

### Tool license

Proprietary (included with Windows)

### Add or update?

- [X] Add
- [ ] Update

### Desired version

2

### Brief description of tool

WSL2 allows running Linux applications on windows by using a Hyper-V VM running a real Linux kernel

### URL for tool's homepage

https://docs.microsoft.com/en-us/windows/wsl/about

### Provide a basic test case to validate the tool's functionality.

```bash
Describe "WSL2" {
  It "should be possible to install a wsl2 distro and run commands in it" {
    wsl --install -d Ubuntu
    wsl -d Ubuntu echo works | Should -Match "works"
  }
}
```

### Platforms where you need the tool

- [ ] Azure DevOps
- [X] GitHub Actions

### Virtual environments where you need the tool

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Can this tool be installed during the build?

```bash
Installing WSL2 during the build is not possible due to the fact that enabling the required Windows features requires a reboot
```

### Are you willing to submit a PR?

Yes

**Comment by al-cheb** [comment]
https://github.com/actions/virtual-environments/issues/5760#issuecomment-1157585475

**Comment by nzbr** [comment]
Given that hosted runners [do seem to support nested virtualization now](https://github.com/DeterminateSystems/nix-installer-action/pull/56), is it conceivable that WSL2 will be enabled on windows runners in the future?

**Comment by mikhailkoliada** [comment]
@nzbr only [larger runners](https://docs.github.com/en/actions/using-github-hosted-runners/about-larger-runners/about-larger-runners) officially support nested now, not the standard ones, unfortunately (yet), so we can not replace v1 with v2 for the time being. Eventually nested will be supported by the standard runners as well, but we have no ETA on this.

**Comment by wmmc88** [comment]
@mikhailkoliada According to https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#cloud-hosts-used-by-github-hosted-runners it seems like the standard runners are now using `Dadsv5` which supports nested virtualization. Does this mean WSL2 can be used in github-hosted windows runners now?

Searching around seems to show that the change to the new VMs happened in January: https://github.blog/2024-01-17-github-hosted-runners-double-the-power-for-open-source/

**Comment by ssbarnea** [comment]
@mikhailkoliada Any updates or hints on how to make WSL2 work in 2024? We cannot really use WSL1 because we need to make use of docker/podman from inside WSL.

When we are on larger runners, we could attempt to upgrade wsl version from inside the pipeline but I am not sure how long it will take to perform this action as it could easily double the execution time for the pipelines.
