### ISSUE TITLE
Windows Server 2022 image build fails at Configure-Antivirus.ps1

### ISSUE THREAD

**Issue by greha** [actions/virtual-environments#5938]
### Description

I am trying to build the Windows Server 2022 image but it fails.
==> vhd: Provisioning with powershell script: C:\agent\_work\21\s\virtual-environments\images\win/scripts/Installers/Configure-Antivirus.ps1
==> vhd: Provisioning step had errors: Running the cleanup provisioner, if present...

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

Cloning from commit aa8b6672e00beee9d79473a0786a12456804ce99 with tag win22/20220710.1 published on 07/11/2022 09:38:12

### Is it regression?

Probably, this version worked Cloning from commit 2b567ccb3c17f5d307b4363171df92c6f2f8e267 with tag win22/20220330.1 published on 03/31/2022 14:32:21

### Expected behavior

Image build is possible without errors.

### Actual behavior

==> vhd: Provisioning with powershell script: C:\agent\_work\21\s\virtual-environments\images\win/scripts/Installers/Configure-Antivirus.ps1
==> vhd: Provisioning step had errors: Running the cleanup provisioner, if present...

### Repro steps

Clone virtual agents repo and run the packer build for win2022 image

**Comment by al-cheb** [comment]
Duplicate: https://github.com/actions/virtual-environments/issues/5847
