### ISSUE TITLE
Add Linux docker containers on Windows 2019 environment

### ISSUE THREAD

**Issue by DanielOverdevest** [actions/virtual-environments#5948]
### Tool name

Linux docker containers

### Tool license

?

### Add or update?

- [X] Add
- [ ] Update

### Desired version

latest

### Brief description of tool

At the moment it's not possible to use the Windows 2019 image within Azure DevOps Pipeline to build Linux based docker images. Now we need to use ubuntu-latest to get this working - but it would be nice that this is also available within the Windows 2019 image.

Problem is that the installation of Docker on Windows 2019 only supports platform 'windows' and not 'linux.
For this reason it's not possible to build image of: `node` or `nginx` which only supports linux containers.

### URL for tool's homepage

https://docs.microsoft.com/en-us/virtualization/windowscontainers/deploy-containers/linux-containers

### Provide a basic test case to validate the tool's functionality.

```bash
docker run --rm --platform linux alpine ls
```

### Platforms where you need the tool

- [X] Azure DevOps
- [ ] GitHub Actions

### Virtual environments where you need the tool

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [X] Windows Server 2019
- [ ] Windows Server 2022

### Can this tool be installed during the build?

```bash
Couldn't find a way to do this.
```

### Are you willing to submit a PR?

Yes - if I've the solution

**Comment by al-cheb** [comment]
Hey @DanielOverdevest.
Unfortunately, we can't add linux container support due to Azure vm spec limitation we use, at that moment it is [DSv2-series](https://docs.microsoft.com/en-us/azure/virtual-machines/dv2-dsv2-series) without supporting nested Hyper-V virtualization.

![image](https://user-images.githubusercontent.com/47745270/180405349-51f020aa-782c-41e7-bbf4-ecd7e290ec46.png)

**Comment by DanielOverdevest** [comment]
Thanks for swift response! I understand.
