### ISSUE TITLE
Update/Add Git for windows SDK

### ISSUE THREAD

**Issue by evandrocoan** [actions/virtual-environments#596]
**Tool information**
- Tool name: Git for windows (SDK)
- Add or update? Update git for windows
- Desired version: latest https://github.com/git-for-windows/build-extra/releases/download/git-sdk-1.0.7/git-sdk-installer-1.0.7-64.7z.exe
- Approximate size: 5GB
- If this is an add request:
  - Brief description of tool: Git for windows already installed, contains a unix environment, but it does not have a package manager (https://stackoverflow.com/questions/32712133/package-management-in-git-for-windows). While the Git for windows SDK contains a package manager (pacman) with a complete unix environment. This can be used to drop chocolatey mingw installation which does not have a package manager (https://github.com/actions/virtual-environments/blob/master/images/win/scripts/Installers/Install-MinGW.ps1).
  - URL for tool's homepage: https://github.com/git-for-windows/build-extra

**Question, Bug, or Feature?**:
"Enhancement"

**Virtual environments affected**
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [x] Windows Server 2016 R2
- [x] Windows Server 2019

**Can this tool be installed during the build?**
Yes, it takes about 8 minutes to download a 1GB git repository and extract it to 5GB. (https://github.com/evandroforks/anki/runs/524380395?check_suite_focus=true#step:2:113)

**Are you willing to submit a PR?**
Yes.

**Comment by evandrocoan** [comment]
I am not entirely sure if worth using the `Git for Windows SDK` because its size is too big. For now, I am manually installing and caching `pacman` on the `Git for Windows` already shipped with Windows. This is the recipe:
```yml
- name: Configure environment variables
  run: |
    echo "::set-env name=pacmanbin::pacman-5.1.1-3-x86_64.pkg.tar.xz"
    echo "::set-env name=pacmanmirror::pacman-mirrors-20200307-1-any.pkg.tar.xz"
    echo "::set-env name=pacmankeys::msys2-keyring-r9.397a52e-1-any.pkg.tar.xz"

- name: Cache pacman
  id: cache-pacman
  uses: actions/cache@v1
  with:
    path: C:\Program Files\Git
    key: ${{ runner.os }}-pacman-${{ hashFiles('**/windows_checks.yml') }}

- name: Set up pacman, rsync
  if: steps.cache-pacman.outputs.cache-hit != 'true'
  shell: cmd
  run: |
    echo on
    curl -LO http://repo.msys2.org/msys/x86_64/%pacmanbin%
    curl -LO http://repo.msys2.org/msys/x86_64/%pacmanmirror%
    curl -LO http://repo.msys2.org/msys/x86_64/%pacmankeys%

    :: https://stackoverflow.com/questions/1359793/programmatically-extract-tar-gz
    7z x "%pacmanbin%" -so | 7z x -aoa -si -ttar -o"%programfiles%\Git"
    7z x "%pacmanmirror%" -so | 7z x -aoa -si -ttar -o"%programfiles%\Git"
    7z x "%pacmankeys%" -so | 7z x -aoa -si -ttar -o"%programfiles%\Git"

    :: Manually Install Pacman Binaries
    :: https://github.com/Alexpux/MSYS2-pacman/issues/50
    cd /d "%programfiles%\Git\usr\bin"
    .\bash pacman-key --init
    .\bash pacman-key --populate msys2
    .\bash pacman-key --refresh-keys
    .\pacman -Tv
    .\pacman -Syuv --overwrite='*'
    .\pacman --version

    :: We must install bash first, otherwise we will have bash fork errors:
    :: https://github.com/evandroforks/anki/runs/524857054?check_suite_focus=true
    :: 0 [main] pacman 748 dofork: child -1 - forked process 2896 died unexpectedly
    .\pacman -Sv --noconfirm --overwrite='*' bash
    .\pacman -Sv --noconfirm --overwrite='*' rsync
```

Perhaps, just run this and install `pacman` over the actual installation of `Git for Windows`?

The only problem with it is that when installing packages, I always have to pass the argument `--overwrite='*'` because `pacman` does not know which files are already installed or not.

But not using the `Git for Windows SDK` is good because the `Git for Windows` with `pacman` only has `173MB` of size. Meaning I can cache the `C:\Program Files\Git` directory with all packages I need installed at once, instead of installing them everything: https://github.com/evandroforks/anki/runs/528013790?check_suite_focus=true#step:6:16
```
 Cache pacman 51s
Cache restored from key: Windows-pacman-df13c0aa939feb57f24309282ac41a4951b9d3c07309c516f6c8bad3642f9178
Run actions/cache@v1
Cache Size: ~173 MB (180914473 B)
C:\windows\System32\tar.exe -xz -f D:\a\_temp\45a5c042-0d27-48f6-ace7-bf046a6ecdfb\cache.tgz -C "C:\Program Files\Git"
Cache restored from key: Windows-pacman-df13c0aa939feb57f24309282ac41a4951b9d3c07309c516f6c8bad3642f9178
```

**Comment by thejoebourneidentity** [comment]
Hey @evandrocoan , agreed that we will most likely not install `Git for Windows SDK`. I think the more interesting part of this request is whether we should add pacman on Windows. Can you shed more light on your need for that tool?

**Comment by evandrocoan** [comment]
I used `pacman` because it seems well maintained and certainly is better than some other environment as Cygwin apt-cyg. I was trying to use Cygwin and `msys2` (installed by `choco install msys2`), but none of them worked (probably due https://github.com/actions/virtual-environments/issues/594 - fatal error - cygheap base mismatch detected). 

The difference of having or not `pacman` is that `pacman` or any package manager, is that they automate the installation of packages. On this case, Unix Packages available on ` http://repo.msys2.org/msys/ <archtecture>`.

Instead of using `pacman` I could just install any other package from ` http://repo.msys2.org/msys/x86_64/` the same why I installed `pacman`. But if you look at the installation of `pacman` you will see that manual installation of packages (by unzipping them) can be quite complicated depending on the package. 

For example, a package may depend on others (like `pacman` depended on `pacman-mirrors` and `msys2-keyring`). Now `pacman` is installed, (and not conflicting with https://github.com/actions/virtual-environments/issues/594), I can use `pacman` to install packages, including its dependencies and requires setup commands. Without `pacman` I would be required to figure out by myself how to install each package and which dependencies it may have.

Now I have `pacman` and a very small Unix environment (173MB) installed on `C:\Program Files\Git`, which can be easily cached by the [Cache Actions](https://github.com/actions/cache).

Perhaps there is no need for any changes as long as I can install `pacman` on the Unix Environment at `C:\Program Files\Git`. The only problem remains is that https://github.com/actions/virtual-environments/issues/594 (fatal error - cygheap base mismatch detected). Which could be happening because you run `choco install mingw` and `choco` is installing `mingw` directly on `C:\ProgramData\chocolatey\bin`, making `chocolatey` installation mixed with unix stuff (https://chocolatey.org/packages/mingw#comment-4791193719)
> It seems that this installer vomits the mingw installation into C:\ProgramData\chocolatey\bin. I'd like to install it to C:\MinGW, but I'm having a really hard time finding what command line options I would need to pass to make that happen.

If the `mingw` installation was not directly into `C:\ProgramData\chocolatey\bin`, but instead in some other directory as `C:\mingw\bin`, I could easily remove the `mingw` from the system path. But as of now, they do not have either a package manager or a way to install it on `C:\mingw\bin`.

I rather just do not install mingw (https://github.com/actions/virtual-environments/blob/master/images/win/scripts/Installers/Install-MinGW.ps1) by default and just use the Unit Environment on `C:\Program Files\Git\usr\bin`. If in case it is missing some package as `make`, you could install `pacman` on it and use it to install make:
```
C:\Program Files\Git\usr\bin>.\pacman -Sv --noconfirm --overwrite='*' make
Root      : /c/Program Files/Git/
Conf File : /etc/pacman.conf
DB Path   : /var/lib/pacman/
Cache Dirs: /var/cache/pacman/pkg/
Hook Dirs : /c/Program Files/Git/usr/share/libalpm/hooks/  /etc/pacman.d/hooks/
Lock File : /var/lib/pacman/db.lck
Log File  : /var/log/pacman.log
GPG Dir   : /etc/pacman.d/gnupg/
Targets   : make
resolving dependencies...
looking for conflicting packages...

Packages (1) make-4.3-1

Total Download Size:   0.45 MiB
Total Installed Size:  1.48 MiB

:: Proceed with installation? [Y/n]
:: Retrieving packages...
 make-4.3-1-x86_64        456.7 KiB   468K/s 00:01 [#######] 100%
(1/1) checking keys in keyring                     [#######] 100%
(1/1) checking package integrity                   [#######] 100%
(1/1) loading package files                        [#######] 100%
(1/1) checking for file conflicts                  [#######] 100%
(1/1) checking available disk space                [#######] 100%
:: Processing package changes...
(1/1) installing make                              [#######] 100%
```

**Comment by maxim-lobanov** [comment]
Currently, we are working to add MSYS2 and pacman: https://github.com/actions/virtual-environments/pull/585.
Pull-request is still in progress

**Comment by alepauly** [comment]
thanks @maxim-lobanov. @vsafonkin can you please close this issue when pacman actually rolls out?

**Comment by vsafonkin** [comment]
Closed, Windows images with msys2 and pacman were rolled out.
