### ISSUE TITLE
nsis is not listed in  virtual-environments/images/win/Windows2019-Readme.md 

### ISSUE THREAD

**Issue by dlech** [actions/virtual-environments#597]
**Describe the bug**
I added `choco install nsis` to my github actions .yml file since it was not listed as preinstalled in  virtual-environments/images/win/Windows2019-Readme.md . When it ran the action, however, it gave the message that this package was already installed.

```
Chocolatey v0.10.15
Installing the following packages:
nsis
By installing you accept licenses for the packages.
nsis v3.5.0.20200106 already installed.
 Use --force to reinstall, specify a version to install, or try upgrade.

Chocolatey installed 0/1 packages. 
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Warnings:
 - nsis - nsis v3.5.0.20200106 already installed.
 Use --force to reinstall, specify a version to install, or try upgrade.
```

**Area for Triage**: 

**Question, Bug, or Feature?**: 
Documentation

**Virtual environments affected**
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [x] Windows Server 2019

**Comment by maxim-lobanov** [comment]
@dlech, thank you for report!
Looks like creating documentation line is commented: https://github.com/actions/virtual-environments/blob/master/images/win/scripts/Installers/Validate-NSIS.ps1#L31
Definitely need to fix it.

**Comment by maxim-lobanov** [comment]
Fixed with PR above. Will keep work item opened until updated docs are deployed with next image.

**Comment by maxim-lobanov** [comment]
Change-log was updated. Closing the issue
