### ISSUE TITLE
.NET Core SDK is not correct always

### ISSUE THREAD

**Issue by HenrikSommer-eng** [actions/virtual-environments#5976]
### Description

Hi.

I can see you have update [Windows2022-Readme.md](https://github.com/actions/virtual-environments/blob/main/images/win/Windows2022-Readme.md) yesterday to include new version of .NET Core SDK (6.0.302)

We have update our code to use it but can see pipeline are failing from time to time because of the agent image only have version: 6.0.301

Did you update the documentations to early ? 
Normal we see it the other way around that sometime agents have a newer version that the documentations say.

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

Agent machine name: 'WIN-RG9C5L770HQ'
Current agent version: '2.206.1'
Operating System
Virtual Environment
Virtual Environment Provisioner
Current image version: '20220710.1'
Agent running as: 'VssAdministrator'

### Is it regression?

.

### Expected behavior

When dokumentations is update all agent are also running that image

### Actual behavior

it seem that maybe 90-95% of the image are updated.

### Repro steps

1. Create a repo in azure devops
2. Create a pipeline
3. Usage      
   ```yml
   pool:
     vmImage: 'windows-latest'
    ```
4. Add a powershell step that call:
   ```powershell
   if(-not (dotnet --list-sdks)[-1].Contains("6.0.302"))
   {
      exit 1
   }
   ```

**Comment by miketimofeev** [comment]
Hey, @HenrikSommer-eng!
It looks like your builds are on the old image version judging by `Current image version: '20220710.1'`. Could you share a few links to such builds? We will check telemetry to understand which environments are affected.
Sorry for the inconvenience!

**Comment by HenrikSommer-eng** [comment]
Hi
Our pipeline are not public so dont know if help you.
And yes it is running on an old image version.

When running the same pipeline it got this:
Agent name: 'Azure Pipelines 3'
Agent machine name: 'fv-az569-656'
Current agent version: '2.206.1'
Operating System
Virtual Environment
Virtual Environment Provisioner
`Current image version: '20220724.1'`

**Comment by HenrikSommer-eng** [comment]
If you still need the links I can provide it in an email.

**Comment by al-cheb** [comment]
@HenrikSommer-eng, Do you have builds that were run in less than 12 hours on the version '20220710.1'?

**Comment by HenrikSommer-eng** [comment]
Yes.
```
2022-07-27T05:10:25.2065593Z ##[section]Starting: Initialize job
2022-07-27T05:10:25.2067689Z Agent name: 'Azure Pipelines 20'
2022-07-27T05:10:25.2068419Z Agent machine name: 'WIN-RG9C5L770HQ'
2022-07-27T05:10:25.2068761Z Current agent version: '2.206.1'
2022-07-27T05:10:25.2146602Z ##[group]Operating System
2022-07-27T05:10:25.2147002Z Microsoft Windows Server 2022
2022-07-27T05:10:25.2147892Z 10.0.20348
2022-07-27T05:10:25.2148143Z Datacenter
2022-07-27T05:10:25.2148626Z ##[endgroup]
2022-07-27T05:10:25.2149135Z ##[group]Virtual Environment
2022-07-27T05:10:25.2149465Z Environment: windows-2022
2022-07-27T05:10:25.2149730Z Version: 20220710.1
```

**Comment by HenrikSommer-eng** [comment]
latest error happen:
`2022-07-27T11:02:13.4651094Z`
And have queue about 40 jobs since with out the problem

**Comment by al-cheb** [comment]
We need a `planId` for this build, click `View raw log` button, remove at the end of the link `/logs/XXX`(`_apis/build/builds/2470053/logs/13 -> _apis/build/builds/2470053` ), find planId and paste it.

![image](https://user-images.githubusercontent.com/47745270/181256300-97fefb7a-0841-49fd-980a-ddff1f670b40.png)
![image](https://user-images.githubusercontent.com/47745270/181256421-f7a08045-122c-4412-b7e1-50548bb1392f.png)

**Comment by HenrikSommer-eng** [comment]
"plans":[{"planId":"4fa8239d-664e-4cd8-a556-d702f2b0ff28"}]

**Comment by HenrikSommer-eng** [comment]
I can see i was wrong about last failed run and had 1 about 30 min later.
```
"orchestrationPlan":{"planId":"c3f1bd96-2e2e-4d02-aa05-7876aa3dc380"} '2022-07-27T05:10:52.4934991Z'
"orchestrationPlan":{"planId":"22a0cdd4-d908-4efe-a3dc-c183a018509e"} '2022-07-27T05:12:17.4600319Z'
"orchestrationPlan":{"planId":"4fa8239d-664e-4cd8-a556-d702f2b0ff28"} '2022-07-27T11:02:13.4651094Z'
"orchestrationPlan":{"planId":"4b4a6a84-6cd6-45f1-b138-e27ea3f1924c"} '2022-07-27T11:37:27.0922797Z'
```

**Comment by HenrikSommer-eng** [comment]
Just an update we have not seen the problem today.

**Comment by al-cheb** [comment]
@HenrikSommer-eng, Thank you. I am planning to close the thread. We tracked this issue in our internal backlog and we will continue monitoring.

**Comment by HenrikSommer-eng** [comment]
That is fair, thanks for looking into it.
