### ISSUE TITLE
Update/Add osxfuse

### ISSUE THREAD

**Issue by netheril96** [actions/virtual-environments#598]
**Tool information**
- Tool name: osxfuse
- Add or update? Add
- Desired version:  latest
- Approximate size: 10MiB
- If this is an add request:
  - Brief description of tool: Library and kernel module for [FUSE filesystems](https://en.wikipedia.org/wiki/Filesystem_in_Userspace) on macOS.
  - URL for tool's homepage: https://osxfuse.github.io/

**Area for Triage**:

Apple
C/C++

**Question, Bug, or Feature?**:

Feature

**Virtual environments affected**
- [x] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Can this tool be installed during the build?**

No, because it requires a reboot after installation, which will break the workflow.

**Are you willing to submit a PR?**

Yes.

**Comment by siscia** [comment]
I was here to open the exact same issue.

It would be extremely useful to us having the ability to use FUSE.

**Comment by thejoebourneidentity** [comment]
Thanks for the suggestion @netheril96 abd @siscia. Can you expand on the type of workflow you're trying to create that requires FUSE? We're discussing adding FUSE and would like the additional context.

**Comment by netheril96** [comment]
I need to continuously test my own FUSE based filesystem:  https://github.com/netheril96/securefs/actions?query=workflow%3A%22C%2FC%2B%2B+CI%22

The action works on both Linux and Windows now, but not on macOS.

**Comment by siscia** [comment]
While we do have a fuse filesystem where files are installed and are necessary on build time.

We would like to mount our own fuse filesystem, complete the build linking or using files in our own filesystem and move along the build artifact.

**Comment by al-cheb** [comment]
Hello, @netheril96 and @siscia
We have granted an additional permissions on macOS image. Now you can able to install the  osxfuse tool on runtime(`brew cask install osxfuse`) without reboot. Sorry we can't pre-install the osxfuse tool on the macOS image due to limitation the osxfuse tool license policy.

Example securefs build:
```
jobs:
  build:
    runs-on: macos-latest
    steps:
    - name: osfux
      run: |
        brew cask install osxfuse
        git clone --recursive https://github.com/netheril96/securefs
        cd securefs
        mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Debug ..
        cd ..
        cmake --build build
        cd build && ctest -V
```

![osxfuse](https://user-images.githubusercontent.com/47745270/80311515-b9f19080-87e8-11ea-8706-db311378cd7a.JPG)

**Comment by netheril96** [comment]
Thanks! It works now.

**Comment by siscia** [comment]
CC: @jbloomer

**Comment by mcafaro** [comment]
Running into trouble with macFUSE on these machines. It installs fine but I can't actually mount anything with it. If I try to load the kext, I get an error saying the extension is not approved to be loaded:

**macFUSE**
```
$ brew install osxfuse
$ sudo kextload /Library/Filesystems/macfuse.fs/Contents/Extensions/10.15/macfuse.kext
Executing: /usr/bin/kmutil load -p /Library/Filesystems/macfuse.fs/Contents/Extensions/10.15/macfuse.kext
Error Domain=KMErrorDomain Code=27 "Extension with identifiers com.apple.nke.rvi,io.macfuse.filesystems.macfuse not approved to load. Please approve using System Preferences." UserInfo={NSLocalizedDescription=Extension with identifiers com.apple.nke.rvi,io.macfuse.filesystems.macfuse not approved to load. Please approve using System Preferences.}
```

**osxFUSE**
```
$ brew install macfuse
$ sudo kextload /Library/Filesystems/osxfuse.fs/Contents/Extensions/10.15/osxfuse.kext
Executing: /usr/bin/kmutil load -p /Library/Filesystems/osxfuse.fs/Contents/Extensions/10.15/osxfuse.kext
Error Domain=KMErrorDomain Code=27 "Extension with identifiers com.github.osxfuse.filesystems.osxfuse,com.apple.nke.rvi not approved to load. Please approve using System Preferences." UserInfo={NSLocalizedDescription=Extension with identifiers com.github.osxfuse.filesystems.osxfuse,com.apple.nke.rvi not approved to load. Please approve using System Preferences.}
```

**Comment by miketimofeev** [comment]
@mcafaro it looks like additional permissions requiered. Could you file an issue and we will take a look?

**Comment by mgree** [comment]
I have this issue for https://github.com/mgree/ffs... am I correct in understanding that #4731 is WONTFIX and I should find a way to install the .dmg on CI?

**Comment by cafarm** [comment]
@mgree Yes, that is my understanding. I suspect you will have trouble with any installation approach of macFUSE on GitHub-hosted runners using macOS-11. You can use macOS-10.15 for now but it may go away at some point. If you discover something that works on macOS-11, please share.

**Comment by mgree** [comment]
Alas: installing from .dmg doesn't seem to work---you can [see the logs](https://github.com/mgree/ffs/runs/4970362072?check_suite_focus=true#step:2:154).

What is the longterm solution for this? Is there something the macfuse developer should do differently, or what? It'd be nice to be able to test my code on more recent macOS environments!

**Comment by mgree** [comment]
We have arrived at macos-10.15 deprecation. Has anyone figured out something clever in the meantime?

I'm using CI to generate my macOS artifacts, and it'd be a shame to no longer be able to distribute on macOS. 😢

**Comment by mikhailkoliada** [comment]
@mgree Hello!

Please see my reply https://github.com/actions/virtual-environments/issues/5583#issuecomment-1196763627, unfortunately we can not support macfuse as a part of runner images.

**Comment by mgree** [comment]
I see... thanks for following up!

**Comment by anacrolix** [comment]
What about fuse-t?
