### ISSUE TITLE
Add Rust to MacOS

### ISSUE THREAD

**Issue by jhpratt** [actions/virtual-environments#6]
**Tool information**
- Tool name: Rust
- Add or update? Add
- Desired version: Stable (currently 1.38.0)
- Approximate size: Similar to Ubuntu, given that they're both Unix. `rustc` by itself is 11M on my Ubuntu system.
- If this is an add request:
  - Brief description of tool: Rust language. It's already present on Ubuntu and Windows virtual envs.
  - URL for tool's homepage: https://rust-lang.org

**Virtual environments affected**
- [x] macOS 10.14
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Can this tool be installed during the build?**
Yes, though it adds a couple minutes to the build.

**Are you willing to submit a PR?**

If someone can show me what would need to be changed, certainly.

---

On a related note, it would be great if various stable versions were also provided!

**Comment by kaylangan** [comment]
Thanks for the suggestion! We definitely want to add Rust to macOS to make sure that it's available across all the OS's. I can't give an ETA for when it will be added, but it is very much on our radar. 🙂

**Comment by kaylangan** [comment]
@nrajpurkar FYI

**Comment by kaylangan** [comment]
We should also consider adding rustup.

**Comment by vmapetr** [comment]
Hi @jhpratt! We have added Rust and Rustup support in macOS10.14 and macOS10.15. It will be available after next image rollout.

**Comment by miketimofeev** [comment]
The image rollout has been completed. 
@jhpratt feel free to open a new issue if there is something wrong with preinstalled Rust.
