### ISSUE TITLE
Packer build fails on Ubuntu 20.04 image with a 404 error while installing ruby-builder

### ISSUE THREAD

**Issue by rybal06** [actions/virtual-environments#6007]
### Description

    azure-arm: Error — Either HTTP response code for 'https://github.com/ruby/ruby-builder/releases/download/toolcache/' is wrong - '404' or exit code is not 0 - '23'. Waiting 30 seconds before the next attempt, 1 attempts left
    azure-arm: Error — Either HTTP response code for 'https://github.com/ruby/ruby-builder/releases/download/toolcache/' is wrong - '404' or exit code is not 0 - '23'. Waiting 30 seconds before the next attempt, 0 attempts left
    azure-arm: Could not download https://github.com/ruby/ruby-builder/releases/download/toolcache/

### Platforms affected

- [X] Azure DevOps
- [X] GitHub Actions

### Virtual environments affected

- [ ] Ubuntu 18.04
- [X] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

 20220724.1 

### Is it regression?

No

### Expected behavior

package installs successfully 

### Actual behavior

    azure-arm: Error — Either HTTP response code for 'https://github.com/ruby/ruby-builder/releases/download/toolcache/' is wrong - '404' or exit code is not 0 - '23'. Waiting 30 seconds before the next attempt, 1 attempts left
    azure-arm: Error — Either HTTP response code for 'https://github.com/ruby/ruby-builder/releases/download/toolcache/' is wrong - '404' or exit code is not 0 - '23'. Waiting 30 seconds before the next attempt, 0 attempts left
    azure-arm: Could not download https://github.com/ruby/ruby-builder/releases/download/toolcache/

### Repro steps

Attempt to perform a packer build using this repository

**Comment by al-cheb** [comment]
The nightly build is green - https://github.visualstudio.com/virtual-environments/_build/results?buildId=128288&view=logs&j=011e1ec8-6569-5e69-4f06-baf193d1351e&t=5431112d-2b61-5a5f-7042-ef698f761043 . Looks like a flaky network issue.
