### ISSUE TITLE
mismatch from documentation?

### ISSUE THREAD

**Issue by asottile** [actions/virtual-environments#6010]
### Description

I've been tracking a bug in git 2.36 which is fixed in 2.37 -- the image information for 20220724.1 claims it has git 2.37.1 but I'm still seeing 2.36

here's my job run: https://dev.azure.com/asottile/asottile/_build/results?buildId=13799&view=logs&j=94d9d3b4-8e3d-5cdc-d6c7-40ce0e4fea69&t=3be1b07c-7b5b-4b02-84ff-33b8af3eb53d

(excerpt from setup):

```
Current image version: '20220724.1'
```

(excerpt from checkout)

```
git version
git version 2.36.1.windows.1
```

the documentation for 20220724.1 is at this commit: https://github.com/actions/virtual-environments/pull/5957 and contains this information:

```
Git 2.37.1.windows.1
```

I'm wondering why I'm seeing a disparity from the documentation -- and would really like to be on git 2.37 :D

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

`20220724.1`

https://dev.azure.com/asottile/asottile/_build/results?buildId=13799&view=logs&j=94d9d3b4-8e3d-5cdc-d6c7-40ce0e4fea69&t=3be1b07c-7b5b-4b02-84ff-33b8af3eb53d

### Is it regression?

kind of? but not really -- it's a regression in `git` -- here's a passing run though (which was on git 2.30.2): https://dev.azure.com/asottile/asottile/_build/results?buildId=13615&view=results

### Expected behavior

I expect to have git 2.37.1 as the documentation states

### Actual behavior

I am seeing git 2.36.1

### Repro steps

1. run any job which checks out code
2. note the git version

notably git 2.36.1 on windows has a bug with the output of `pre-push` hooks is in an undefined order which one of my tests is sensitive to

**Comment by al-cheb** [comment]
Hello @asottile.
The documentation is correct. There are a couple of git versions available on Azure DevOps images:

1. https://github.com/microsoft/azure-pipelines-agent
2. Pre-installed on an image

![image](https://user-images.githubusercontent.com/47745270/182543721-020bdaa1-912d-47d4-9b53-690f0b0eca7c.png)

If we take a look at the build we can find the agent version - `Current agent version: '2.206.1'` - https://github.com/microsoft/azure-pipelines-agent/releases

```
PS > cd .\vsts-agent-win-x86-2.206.1\
PS D:\vsts-agent-win-x86-2.206.1> .\externals\git\cmd\git.exe -- version
PS D:\vsts-agent-win-x86-2.206.1> .\externals\git\cmd\git.exe --version
git version 2.36.1.windows.1
```

Please create a new issue in the https://github.com/microsoft/azure-pipelines-agent repository.

cc @geekzter

**Comment by al-cheb** [comment]
> shouldn't the docs show the version that's being used rather than the version that's not? I don't see the point in having the wrong one documented

No, it shouldn't. It's part a 3rd party external agent. You can still use git version which mentioned in the doc.
