### ISSUE TITLE
Feature request: GNU/Hurd runner

### ISSUE THREAD

**Issue by Zopolis4** [actions/virtual-environments#6011]
Having a gnu/hurd runner would be very convenient to test that software still builds on hurd, as it is not used by a ton of people and so could easily have silently introduced bugs.

### Name

GNU/Hurd

### License

GPL

### Add or update?

- [X] Add
- [ ] Update

### Desired version

Debian GNU/Hurd 2021

### URL for tool's homepage

https://www.gnu.org/software/hurd/

### Platforms where I need a runner

- [ ] Azure DevOps
- [X] GitHub Actions

### Are you willing to submit a PR?

Yes

**Comment by al-cheb** [comment]
Hello @Zopolis4 .

**Looking for other Linux distributions?** We do not plan to offer other Linux distributions. We recommend using Docker if you'd like to build using other distributions with the hosted virtual environments. Alternatively, you can leverage [self-hosted runners](https://help.github.com/en/actions/hosting-your-own-runners) and fully customize your environment to your needs.

**Comment by Zopolis4** [comment]
Hurd isin't linux, and I can't use it as a self-hosted runner because it isnt on the supported list of OS's. I suppose I could use qemu, but that is hardly practical.
