### ISSUE TITLE
Temporary failure resolving 'deb.debian.org'

### ISSUE THREAD

**Issue by probal31** [actions/virtual-environments#6013]
### Description

Hello Team,

We have GitHub actions setup for building/running some scripts.

However, we see some issues while the script is run.
Probably not an issue with the scripts but seems to be a system/environment issue.

Please find the error snippet below:

```
+ update
+ apt update
WARNING: apt does not have a stable CLI interface. Use with caution in scripts.
Ign:1 http://deb.debian.org/debian unstable InRelease
Ign:1 http://deb.debian.org/debian unstable InRelease
Ign:1 http://deb.debian.org/debian unstable InRelease
Err:1 http://deb.debian.org/debian unstable InRelease
  Temporary failure resolving 'deb.debian.org'
Reading package lists...
Building dependency tree...
All packages are up to date.
W: Failed to fetch http://deb.debian.org/debian/dists/unstable/InRelease  Temporary failure resolving 'deb.debian.org'
W: Some index files failed to download. They have been ignored, or old ones used instead.
```

Can you please look into the issue and suggest any way to avoid the issue?

Thanks in advance,

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions

### Virtual environments affected

- [ ] Ubuntu 18.04
- [X] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

```
Virtual Environment
  Environment: ubuntu-20.04
  Version: 20220[7](https://github.com/Nitrux/iso-tool/runs/7609018841?check_suite_focus=true#step:1:8)24.1
  Included Software: https://github.com/actions/virtual-environments/blob/ubuntu20/20220724.1/images/linux/Ubuntu2004-Readme.md
  Image Release: https://github.com/actions/virtual-environments/releases/tag/ubuntu20%2F20220724.1
```

### Is it regression?

No

### Expected behavior

The below error is not expected:

```
Failed to fetch http://deb.debian.org/debian/dists/unstable/InRelease  Temporary failure resolving 'deb.debian.org'
```

### Actual behavior

The build is failing with the exception:

```
Failed to fetch http://deb.debian.org/debian/dists/unstable/InRelease  Temporary failure resolving 'deb.debian.org'
```

The build should complete successfully.
Please note that this same script runs successfully when using Travis.

### Repro steps

Here is the link to the GitHub actions.
https://github.com/Nitrux/iso-tool/blob/legacy-minimal/.github/workflows/build.yml

Probably not an issue with the scripts but seems to be a system/environment issue.

**Comment by mikhailkoliada** [comment]
@probal31 I do not see the exact problem with debian's mirror, could you please point a place in your repo where exactly it is used in your build script/

**Comment by probal31** [comment]
@mikhailkoliada 

It fails here: https://github.com/Nitrux/iso-tool/blob/legacy-minimal/bootstrap.sh#L64

After the Debian source is added (here https://github.com/Nitrux/iso-tool/blob/legacy-minimal/bootstrap.sh#L58) 
and `apt update` command is run

**Comment by mikhailkoliada** [comment]
@probal31 as I said I do not observe any problems with debian's mirror at the moment. In anyway, it is a dns' fault, so we are unlikely to help here as we are taking Ubuntu from azure marketplace and do not modify systemd-resolved or systemd-networkd settings, my only advice here could be to play around different dns servers in runtime once you see the problem again and see if it helps.

If you have questions left or any additional info, feel free to reach us out again :)

**Comment by probal31** [comment]
@mikhailkoliada This issue does not happen in a VM while in the dev system. Also this same configuration works fine in Travis as well.  But it fails to run while using GitHub actions. 

That's the reason we raised an issue here. It seems to be an issue specifically while using GitHub actions.

Can you please comment how to proceed with this?

Thanks.

**Comment by mikhailkoliada** [comment]
@probal31 issues like that are probably to go to Azure support in the worst case, it is completly out of our hands
