### ISSUE TITLE
Add Google Cloud SDK on macos

### ISSUE THREAD

**Issue by BoD** [actions/virtual-environments#6020]
### Tool name

Google Cloud SDK

### Tool license

Apache License v. 2.0

### Add or update?

- [X] Add
- [ ] Update

### Desired version

The latest

### Brief description of tool

This is [already available](https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-Readme.md#cli-tools) on Ubuntu images, but not on MacOS images.

### URL for tool's homepage

https://cloud.google.com/sdk

### Provide a basic test case to validate the tool's functionality.

```bash
gcloud # should be in the path
```

### Platforms where you need the tool

- [ ] Azure DevOps
- [X] GitHub Actions

### Virtual environments where you need the tool

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [X] macOS 10.15
- [X] macOS 11
- [X] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Can this tool be installed during the build?

```bash
The tool can be installed with this GitHub action: https://github.com/google-github-actions/setup-gcloud

But it would be even nicer if it was there by default, like on Ubuntu.
```

### Tool installation time in runtime

Unknown

**Comment by mikhailkoliada** [comment]
Hello @BoD I believe the reasoning was provided [there](https://github.com/actions/virtual-environments/issues/4639) already, and I believe we still would not like pre-installing it as the github action might be used.
