### ISSUE TITLE
macOS-latest and macOS-12 MSBuild 17 update eta

### ISSUE THREAD

**Issue by twofingerrightclick** [actions/virtual-environments#6028]
### Tool name

MSBuild 17 

### Tool license

na

### Add or update?

- [ ] Add
- [X] Update

### Desired version

17.x

### Brief description of tool

[The Mac OS images have installs of MSBuild 16](https://github.com/actions/virtual-environments/blob/f1bb031e436bbb5c5645ddc366ca0856ddbf0131/images/macos/macos-11-Readme.md?plain=1#L28). Looking for eta of when MSBuild 17 will be the default so that tasks that use MSBuild instead of `dotnet build` will work with C# 10. 

### Platforms where you need the tool

- [X] Azure DevOps
- [X] GitHub Actions

### Virtual environments where you need the tool

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 10.15
- [X] macOS 11
- [X] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

**Comment by ddobranic** [comment]
hi @twofingerrightclick, MSBuild16 is the latest stable version at the moment.

**Comment by mikhailkoliada** [comment]
@twofingerrightclick msbuild is a part of mono, which in turn is a part of xamarin bundle in macOS images (we are installing mono from xamarin), so there is no specific ETA, but it will be likely added as soon as new mono is added.
