### ISSUE TITLE
Allow actions to globally specify a default shell (or at least an option to default to bash on windows)

### ISSUE THREAD

**Issue by jherico** [actions/virtual-environments#61]
**Describe the bug**
When building complex actions that depend on environment variables, I don't want to have to write different versions depending on the OS (windows uses `%VARNAME%` for env variable access, while other platforms use `$VARNAME`).  As such I tend to explicitly use bash for my shell, so that I can use the same env variable syntax in commands regardless of OS.  It would be nice if I didn't have to do this on a per-step basis but could just declare the default shell at the top 

**Virtual environments affected**
- [ ] macOS 10.14
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [X] Windows Server 2016 R2
- [X] Windows Server 2019

**Expected behavior**
Set a top level `shell: bash` directive in my workflow and have it applied to all jobs / steps that don't have an explicit `shell` value set. 

**Actual behavior**
Produces an error:

```
- Your workflow file was invalid: The pipeline is not valid. .github/workflows/dump.yml (Line: 4, Col: 1): Unexpected value 'shell'
```

**Comment by chrispat** [comment]
I have captured this feedback in our backlog.  Thank you.

**Comment by Andy-AO** [comment]
Even on Linux, I also want the default script runner to be pwsh, hope this problem can be solved as soon as possible

**Comment by T-rvw** [comment]
What is the status of this feature? It seems that I still can't set global shell explicitly.

**Comment by rghdrizzle** [comment]
Hey @T-rvw  can you share me the document link ?

**Comment by T-rvw** [comment]
> Hey @T-rvw can you share me the document link ?

Search `jobs.<job_id>.steps[*].shell` in this document:
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsrun
