### ISSUE TITLE
[macOS] Update/Add MacTeX

### ISSUE THREAD

**Issue by jeroen** [actions/virtual-environments#613]
**Tool information**
- Tool name: MacTeX
- Add or update? Add
- Desired version: Latest
- Approximate size: 3.8GB
- If this is an add request:
  - Brief description of tool: Latex for macOS. Used by lots of scientific tools.
  - URL for tool's homepage: https://tug.org/mactex/

**Area for Triage**:
Apple?

**Question, Bug, or Feature?**:
Feature

**Virtual environments affected**
- [x] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Can this tool be installed during the build?**
Yes, but it takes 8 minutes: `brew cask install mactex`

**Are you willing to submit a PR?**
Sure.

**Comment by thejoebourneidentity** [comment]
Thanks for the suggestion @jeroen, I don't think we're going to be taking this one right now.
