### ISSUE TITLE
Different browsers have different locale in the same OS

### ISSUE THREAD

**Issue by motss** [actions/virtual-environments#614]
**Describe the bug**

Some browsers installed in the same OS returns different locale, e.g. `en-US` on Chrome but `en-GB` on Firefox.

**Area for Triage**: 

**Question, Bug, or Feature?**: 

**Virtual environments affected**
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [x] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Expected behavior**

`en-US` for all browsers on the same OS (same machine?)

**Actual behavior**

1. Run the following JavaScript snippet to return locale information in different browsers in the affected virtual env:

    ```ts
    console.log(Intl.DateTimeFormat().resolvedOptions());

    // Chrome returns 'en-US' while Firefox returns 'en-GB'
    ```

**Comment by dmitry-shibanov** [comment]
Hello, pull request with changing locale for firefox was merged and changes would be delivered in next images rollout.

**Comment by motss** [comment]
@dmitry-shibanov Thank you.

**Comment by dmitry-shibanov** [comment]
Hello, changes were added. If you have any concerns feel free to reopen the issue.
