### ISSUE TITLE
Update SSDT to 15.9.4 for vs2017-win2016

### ISSUE THREAD

**Issue by fan130** [actions/virtual-environments#616]
**Tool information**
- Tool name: SQL Server Data Tools
- Add or update? Update
- Desired version: 15.9.4
- Approximate size:

**Area for Triage**:
Our previous releases use a web installer which will download payloads during installation. However, one of the payloads is not signed with SHA256, which is out of compliance with Microsoft's security policy. So to quickly solve this issue, we have made a new release that replaces the web installer with a full installer that is signed with SHA256 and does not require downloading payloads. And the old releases will be unpublished soon, so please switch to 15.9.4 ASAP because the old download links will be unavailable soon.
Please use this link to download and install SSDT 15.9.4 for vs2017-win2016 image: https://go.microsoft.com/fwlink/?linkid=2124518

**Question, Bug, or Feature?**:
Bug

**Virtual environments affected**
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [x] Windows Server 2016 R2
- [ ] Windows Server 2019

**Can this tool be installed during the build?**
Yes

**Are you willing to submit a PR?**
I'm willing to, but I don't know how to do the change.

**Comment by dibir-magomedsaygitov** [comment]
SSDT for SSDT to 15.9.4 for vs2017-win2016 has been updated in scope of this [634](https://github.com/actions/virtual-environments/pull/634) PR

**Comment by dibir-magomedsaygitov** [comment]
SSDT for SSDT to 15.9.4 for vs2017-win2016 has been successfully updated. All changes are delivered to VMs. Feel free to contact if you have any issues.
