### ISSUE TITLE
git error with windows-latest image - can't run more than one git command per script

### ISSUE THREAD

**Issue by MIchaelMainer** [actions/virtual-environments#617]
**Describe the bug**
I've got two Azure pipelines (GUI based) that are identical that run against the same repo, targeting the same branch, running the same script. They only differ in that they read a different file in the repo, and both files are the same type of data. The only other difference is that the two pipelines target different VM images. The one that is failing targets *windows-latest*. The one that is successful targets *vs2017-win2016*. I recently changed one of them to target *windows-latest*, which has started to fail when running more than one git command in a script. Image 1. shows the error:

**Image 1. failure running git command**
![image](https://user-images.githubusercontent.com/8527305/77506314-c74ee000-6e22-11ea-9fe1-11bf26cbee05.png)

I encountered this issue in other pipelines and accidently figured out I could get around it by running a single git command per an inline script in an Azure pipeline. But now I'm confident it has nothing to do with an inline script, and occurs with file based scripts as well. It has to do with some environment configuration in *windows-latest*. 

**Area for Triage**: 
Git

**Question, Bug, or Feature?**: 
Bug

**Virtual environments affected**
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [x] Windows Server 2019

**Expected behavior**
I can run multiple git commands in a single script.

**Actual behavior**
I get the error from Image 1. when there are multple got commands run against the windows-2019 image. I can repro this issue outside of my repro.

1. Create a new pipeline that targets *windows-2019*
2. Add a PowerShell script that runs 2 git commands. I used the following to repro:

```powershell
Write-Host "Hello World"
git checkout -b test1 | Write-Host
git checkout master | Write-Host
```

Image 2. Failure from running the script.
![image](https://user-images.githubusercontent.com/8527305/77507021-9cfe2200-6e24-11ea-9d6f-6c3902016cef.png)

**Comment by al-cheb** [comment]
Hello, @MIchaelMainer 
You should use small hack with `GIT_REDIRECT_STDERR` env variable in your pipeline:

`$env:GIT_REDIRECT_STDERR= "2>&1" `

or
```

     - name: git
       env:
        GIT_REDIRECT_STDERR: "2>&1" 
       run: |
        Write-Host "Hello World"
        git clone https://github.com/PowerShell/PowerShell.git
        cd PowerShell
        git checkout -b test1
        git checkout master 
```

https://git-scm.com/docs/git-checkout

```
--no-progress
Progress status is reported on the standard error stream by default when it is attached to a terminal, unless --quiet is specified. This flag enables progress reporting even if not attached to a terminal, regardless of --quiet.
```

**Comment by MIchaelMainer** [comment]
Thank you @al-cheb for the workaround. So, then why did the behavior change between Windows 2016 and Windows 2019 images?

**Comment by al-cheb** [comment]
> Thank you @al-cheb for the workaround. So, then why did the behavior change between Windows 2016 and Windows 2019 images?

@MIchaelMainer ,  I think the better place to ask this question in [actions/runner](https://github.com/actions/runner) about different behavior between powershell desktop in 2016 vs 2019 in build output when you are using PowerShell Desktop version. PowerShell Core works as expected:

```
- name: ls
      run: |
        Write-Host "Hello World"
        git clone https://github.com/PowerShell/PowerShell.git
        cd PowerShell
        git checkout -b test1
        git checkout master 
      shell: pwsh
```
