### ISSUE TITLE
boost_default variable is not removed from Azure-2019.json

### ISSUE THREAD

**Issue by frankzo** [actions/virtual-environments#618]
**Describe the bug**
boost_default variable has been removed from the installation but remains referenced in the Azure-2019.json file.

**Question, Bug, or Feature?**: 
Bug

**Virtual environments affected**
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [X ] Windows Server 2019

**Expected behavior**
boost_default to have been removed from Azure-2019.json too

pull request: 
https://github.com/actions/virtual-environments/pull/619

**Comment by maxim-lobanov** [comment]
@frankzo , thank you for reporting and fixing it. Very appreciate.
I have merged your pull-request!
