### ISSUE TITLE
Add more iOS simulators and iOS device models

### ISSUE THREAD

**Issue by sarunw** [actions/virtual-environments#62]
**Virtual environments affected**
- [/ ] macOS 10.14

I try to run a test with xcodebuild against iOS13 and new iPhone 11, but the newest one is 12.4

**Comment by colinhumber** [comment]
In addition, a lot of developers run tests against multiple iOS versions. With only the latest iOS Simulators being installed, this becomes very difficult apart from installing them on each test run. Other CI providers, like Circle, include versions as far back as 8.3.3. Including at least iOS 10+ simulators would be a HUGE help to devs.

**Comment by marc-scig** [comment]
Our team has been gradually moving CI tasks to GitHub Actions and this is probably the last thing that's preventing us from fully completing the switch. We maintain an SDK that offers support for older iOS versions (currently 11 and 12), and being able to run tests against multiple simulators is a critical feature for avoiding regressions. We'd be grateful if this were resolved soon.

**Comment by acantarero** [comment]
Similar to the prior comment, we have an SDK that support older version of XCode and iOS. 

We would like to be able to test on 🥇 
- iOS 11
- iOS 12

And build on 
- XCode 10.3

None of these are available on macOS-latest

**Comment by yueno12** [comment]
+1

**Comment by jeroenleenarts** [comment]
Adding at least iOS 12 simulators would greatly increase the usefulness of using GitHub Actions for iOS related CI.

**Comment by alemar11** [comment]
+1

**Comment by maxim-lobanov** [comment]
Hi, there is a duplicate issue #551 , it contains workaround using `xcversion` tool
