### ISSUE TITLE
Update Xcode 11.4

### ISSUE THREAD

**Issue by pixyzehn** [actions/virtual-environments#620]
**Tool information**
- Tool name: Xcode
- Add or update? Update
- Desired version: 11.4 (11E146)
- Approximate size: 7.5 GB

**Virtual environments affected**
- [x] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Can this tool be installed during the build?**

**Are you willing to submit a PR?**

No.

**Comment by miketimofeev** [comment]
Hi, @pixyzehn! Image with Xcode 11.4 will be rolled out during next week's image deployment.

**Comment by ydnar** [comment]
Apple is now rejecting uploads built with the current version of Xcode 11.4 (breaking our CD). Do you have an ETA for this deploy?

**Comment by miketimofeev** [comment]
@pixyzehn @ydnar the image has been updated. Could you check it, please?

**Comment by ydnar** [comment]
@miketimofeev thanks! We’re also looking forward to the deployment of Swift on Ubuntu (#609), which lets us run a number of Swift workflows on Linux instead of macOS without having to spend 40s installing Swift.

**Comment by andyhuber** [comment]
@miketimofeev 
This situation is unfortunately quite severe for companies that are relying solely on GitHub Actions to upload builds. Our whole build pipeline is built on GitHub actions and that's the second time after 11.2 that we run into the same problems. Since we are doing nightly builds for all our inhouse testing we need this going.

Is there a possibility for future updates that you can have them ready when Apple is changing their acceptance criteria?

**Comment by ydnar** [comment]
@andyhuber strongly agree.

Possible to decouple Xcode from the normal Catalina / macOS build train?

**Comment by miketimofeev** [comment]
@andyhuber @ydnar sorry for the inconvenience. Image with Xcode 11.4 is rolling out right now and the will be delivered in a couple of hours. We are going to make such Xcode updates much faster in the future.
Thank you!

**Comment by ydnar** [comment]
Thank you! Appreciate your hard work right now.

**Comment by MaxDesiatov** [comment]
@miketimofeev does this include Azure Pipelines images with macOS 10.15? Could one assume that GitHub Actions images and Azure Pipelines images are now identical, given that the [Azure Pipelines images repository](https://github.com/microsoft/azure-pipelines-image-generation/) redirects to this one?

**Comment by miketimofeev** [comment]
@MaxDesiatov Unfortunately, no. Azure pipelines pools are updated separately from GitHub ones. They will be updated tomorrow(you can follow this PR https://github.com/microsoft/azure-pipelines-image-generation/pull/1511, it will be merged when the deployment is done)

**Comment by stephencelis** [comment]
@miketimofeev Any idea how long it usually takes for these rollouts to complete? It looks like the current environment is still on the beta.

**Comment by andyhuber** [comment]
@stephencelis it seems to be updated by now. 
@miketimofeev Thanks. The documentation https://github.com/actions/virtual-environments/blob/master/images/macos/macos-10.15-Readme.md
seems to still be outdated. Still mentioning 11.4 beta

**Comment by miketimofeev** [comment]
@stephencelis @andyhuber it's not yet updated for all the environments. The PR will be completed once it's done.
Thank you for your patience!

**Comment by miketimofeev** [comment]
@pixyzehn @andyhuber @stephencelis image rollout finished. Closing this issue, but feel free to reopen if you have any concerns.
Thank you!

**Comment by arek-avanade** [comment]
Something is not quite right with XCode 11.4 rollout. I'm seeing 2 different images in Azure Pipelines for macos-latest:
```
Agent name: 'Azure Pipelines 3'
Agent machine name: 'Mac-1624'
Current agent version: '2.165.2'
Current image version: '20200328.1'
```

**This one works as expected and contains XCode 11.4.**

However there is also another version that's being queued from time to time:
```
Agent name: 'Hosted Agent'
Agent machine name: 'Mac-1383'
Current agent version: '2.165.2'
Current image version: '20200404.1'
```

**This one seems to be newer, however does NOT seem to have XCode 11.4 installed. I'm getting the following error when running xcode-select:**
`xcode-select: error: invalid developer directory '/Applications/Xcode_11.4.app/Contents/Developer'`

**Comment by miketimofeev** [comment]
@arek-avanade Thanks for the information! We have had some infrastructure changes recently and that might have caused some mess with image versions. I'll take a look and update all the 20200328.1 pools shortly. Sorry for the inconvenience.

**Comment by miketimofeev** [comment]
@arek-avanade it looks like some of your builds are run on Mojave agents(20200404.1), where Xcode 11.4 is not presented, and sometimes on Catalina(20200328.1). Could you please check your agent specifications?

**Comment by arek-avanade** [comment]
@miketimofeev This is an excerpt from my YAML:
```
- job:
    pool:
      vmImage: macOS-latest
      demands:
      - xcode
      - Xamarin.iOS
      - Xamarin.Android
```
When saying macOS-latest, I'd expect to actually get Catalina all the time, as described in this article:
https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops

**Comment by miketimofeev** [comment]
So it's the same pipeline, which sometimes triggered on 20200328.1 and sometimes on 20200404.1, right?
If so, could you please provide examples? If it's not possible then a plan-id for both builds will be helpful. It can be found by the following link:
`https://dev.azure.com/{organization}/{project}/_apis/build/builds/{buildId}`

**Comment by arek-avanade** [comment]
Yes, the same pipeline, however different stages/jobs. So the failing scenario is for a job which is declared with pool/demands as above, it picks 20200404.1 image. 
https://dev.azure.com/essity-projects/CIU/_apis/build/builds/31300

The successful scenario is when I just specify `vmImage: macOS-latest`, but NO demands. In that case somehow 20200328.1 is picked. I'm not sure if this is a coincidence but it consistently happened a few times.
https://dev.azure.com/essity-projects/CIU/_apis/build/builds/30782

**Comment by miketimofeev** [comment]
Thanks, but unfortunately, I don't have access to the builds. Would you mind providing plan-id for them?

**Comment by arek-avanade** [comment]
Oh, my bad. Didn't understand your previous ask. I've updated my previous answer with ids.

**Comment by miketimofeev** [comment]
Thanks!  Yeah, one build is queued against 10.14 while another against 10.15
And what are those demands that you mentioned? I will try to repro it if I have the exact specifications.

**Comment by miketimofeev** [comment]
And I've found one important note
![image](https://user-images.githubusercontent.com/48208649/79217129-fb805400-7e56-11ea-837f-28e5516ba880.png)
https://docs.microsoft.com/en-us/azure/devops/pipelines/process/demands?view=azure-devops&tabs=yaml
Looks like it's better to avoid using demands at all.

**Comment by arek-avanade** [comment]
The one that triggers 10.14 and fails has:
```
pool:
      vmImage: macOS-latest
      demands:
      - xcode
      - Xamarin.iOS
      - Xamarin.Android
```

The one that triggers 10.15 has just:
```
pool:
      vmImage: macOS-latest
```

**Comment by arek-avanade** [comment]
> And I've found one important note
> ![image](https://user-images.githubusercontent.com/48208649/79217129-fb805400-7e56-11ea-837f-28e5516ba880.png)
> https://docs.microsoft.com/en-us/azure/devops/pipelines/process/demands?view=azure-devops&tabs=yaml
> Looks like it's better to avoid using demands at all.

Oh, didn't know that. I'll simplify my YAML and try again in that case. Although I think this should still not drive the selection of agent image IMHO.

**Comment by miketimofeev** [comment]
I'm able to repro it with your demands. I'll ask the engineering team about that strange behavior, but yeah, please avoid using demands for now.

**Comment by maxim-lobanov** [comment]
@arek-avanade , yep, that is it.
All images have Xcode and Xamarin tools installed so we don't need to specify demands. Could you please try to remove them and test again?

**Comment by arek-avanade** [comment]
Removed 'demands' and now it works as expected. Thanks for the quick feedback and resolution guys!

**Comment by darthwillis** [comment]
There is a bit of legacy around custom user capabilities and demands for hosted pools that results in this behavior. We have some work on the backlog to make it better, but it hasn't been prioritized yet. Essentially, when demands are presented, we assign the job to the most relevant legacy hosted pool (i.e. one of the pools that existed before the single hosted "Azure Pipelines" pool).

If the YAML specifies a pool by name, then it will not redirect. So you could take your original YAML and add name: Azure Pipelines to the pool specification, and it would get to the right place like so:

```
- job:
    pool:
      name: Azure Pipelines
      vmImage: macOS-latest
      demands:
      - xcode
      - Xamarin.iOS
      - Xamarin.Android
```

This blog post covers a bit more details:
https://wouterdekort.com/2020/01/14/moving-to-the-azure-pipelines-agent-pool/
