### ISSUE TITLE
NuGet restore failing on windows-2019 image

### ISSUE THREAD

**Issue by mmichtch** [actions/virtual-environments#625]
**Describe the bug**
the pipe line was working correctly for the long time (more than month), the last successful run was on 2020-03-20. The builds using windows-2019 build failed today. To make sure that problem is caused by the Azure image, I have switched the pipeline to the self-hosted agent. The run of then same pipeline succeeded using self-hosted agent.

**Area for Triage**: 
.NET Framework
.NET Core

**Question, Bug, or Feature?**: 
Bug

**Virtual environments affected**
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [x] Windows Server 2019

**Expected behavior**
I expect pipeline to successfully run the build and publish the artifacts.

**Actual behavior**
Run pipe line with the NuGet restore task:
``steps:``
``- task: NuGetCommand@2``
``  displayName: 'NuGet restore' ``
``  inputs: ``
 ``   restoreSolution: OMS.sln ``
 ``   feedsToUse: config ``
 ``   nugetConfigPath: NuGet.config ``

result is: 
Could not load file or assembly 'Microsoft.Build.Framework, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
see attached file for full log

[PipeLine log.txt](https://github.com/actions/virtual-environments/files/4382277/PipeLine.log.txt)

**Comment by maxim-lobanov** [comment]
Hello,
Probably, it is related to VS 16.5 that is rolling out right now.
Could you please try to add this step before using Nuget Command and check if it works?
```
- task: NuGetToolInstaller@1
  displayName: 'Use NuGet Latest'
  inputs:
    versionSpec: '*'
    checkLatest: true
```

**Comment by mmichtch** [comment]
Yes this did solve the problem, I have changed step "Use Nuget 4.1.1" to "Use NuGet Latest" as per your instructions and it is working now. 
thank you.

**Comment by mmichtch** [comment]
I suggest that you update the pipe line template to use latest NuGet instead of specific version (4.1.1)

**Comment by alepauly** [comment]
> I suggest that you update the pipe line template to use latest NuGet instead of specific version (4.1.1)

Thanks @mmichtch, we contacted the team that owns the tasks and they're looking into it.
