### ISSUE TITLE
Update default Go version to 1.13.3

### ISSUE THREAD

**Issue by hairyhenderson** [actions/virtual-environments#63]
On Windows, Go 1.13 is available in `GOROOT_1_13_X64`, but the `PATH` and default `GOROOT` still point to Go 1.12.

On Linux, Go 1.13 is available as well, but not in the regular `PATH`/`GOROOT`

On macOS, the default seems already to be 1.13.1, though it needs to be updated to 1.13.3.

**Tool information**
- Tool name: Go
- Add or update? update
- Desired version: 1.13.3
- Approximate size: 

**Virtual environments affected**
- [x] macOS 10.14
- [x] Ubuntu 16.04 LTS
- [x] Ubuntu 18.04 LTS
- [x] Windows Server 2016 R2
- [x] Windows Server 2019

**Can this tool be installed during the build?**

Yes, with something like:

```yaml
- uses: actions/setup-go@v1
        with:
          go-version: 1.13.x
```

It takes an extra ~minute though!

**Are you willing to submit a PR?**

Yup.

**Comment by dmitry-shibanov** [comment]
Hello, thank you for your response. We updated default go version to the 1.14 (the latest actual  stable version). Changes will be deployed to the next images rollout.

**Comment by hairyhenderson** [comment]
Thanks @dmitry-shibanov. How often do new images roll out?

**Comment by maxim-lobanov** [comment]
@hairyhenderson , usually, it takes about 1-1.5 weeks to deploy the image with new changes

**Comment by maxim-lobanov** [comment]
@hairyhenderson , usually we keep issue opened until the changes are fully deployed everywhere.
So if you don't mind I will reopen it for now and will notify you when the deployment is done

**Comment by hairyhenderson** [comment]
Oh I’m sorry! Didn’t realize. 😅

**Comment by dmitry-shibanov** [comment]
Hello, changes were added. Current default go version is 1.14. If you have any concerns please feel free to reopen the issue.
