### ISSUE TITLE
Add AuthenticationServices to hosted macOS agent azure pipeline

### ISSUE THREAD

**Issue by nsalianInmar** [actions/virtual-environments#633]
Azure pipeline build with hosted macos agent is failing because The type or namespace name 'AuthenticationServices' could not be found, I am suspecting this is because its not pointing to the correct version of Xamarin.ios or the hosted macos agent does not have the latest version of Xamarin.ios installed , could you please look into it

**Virtual environments affected**
- [x] macOS 10.15

**Comment by maxim-lobanov** [comment]
Hello,
Currently, the following versions are installed by default on macOS image:
- Xamarin.Android 10.1
- Xamarin.iOS 13.10
- Xamarin.Mac 6.10
- Mono 6.6
- .NET Core 3.1.200

Could you please share sample project with repro of your issue?
What versions of Xamarin / Mono do you use locally for build?

**Comment by maxim-lobanov** [comment]
I am closing this issue for now but please let me know if it is still an issue and you are ready to provide additional details
