### ISSUE TITLE
Windows environment path has an illegal character

### ISSUE THREAD

**Issue by jetersen** [actions/virtual-environments#635]
**Describe the bug**
Seems like there is an illegal character coming from Microsoft SQL

```
Caused by: java.nio.file.InvalidPathException: Trailing char < > at index 36: C:\Program Files (x86)\Microsoft SQL 
```

https://github.com/jenkinsci/hashicorp-vault-plugin/runs/540184036#step:4:193

This used to work in the past so a recent change made it borked:

https://github.com/jenkinsci/hashicorp-vault-plugin/actions/runs/47619076

**Area for Triage**: 
Java

**Question, Bug, or Feature?**: 
Bug

**Virtual environments affected**
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [X] Windows Server 2019

**Expected behavior**
Environment variables should be possible to normalize.

**Actual behavior**
Code that tries to normalizes the windows path sees an illegal character

**Comment by Jetersen** [comment]
https://github.com/jenkinsci/configuration-as-code-plugin/pull/1302/checks?check_run_id=541313850#step:5:599

**Comment by al-cheb** [comment]
Hello, @Jetersen 
I can reproduce the bug. Thank you for mention about it.

```
 - name: Trail space
      run: |
        $env:Path.split(";") -match " $"
```

"C:\Program Files (x86)\Microsoft SQL " - contains space  as the last character

**Comment by Jetersen** [comment]
Hopefully it would be fixed at the source? 🤔 I assume this is a bug in the Microsoft SQL installer?

**Comment by al-cheb** [comment]
@Jetersen , I don't think it's a bug in the Microsoft SQL installer. Looks like we reach env var 2048 limit - https://devblogs.microsoft.com/oldnewthing/20100203-00/?p=15083

**Comment by Jetersen** [comment]
Well that's somewhat disappointing 😞

I guess we need to start using more variables and using short paths.

**Comment by Jetersen** [comment]
This stackoverflow goes over some of the steps to go through: https://stackoverflow.com/questions/34491244/environment-variable-is-too-large-on-windows-10

Some even suggest Microsoft SQL is partly responsible for the issue.

**Comment by al-cheb** [comment]
I think the root cause: `setx`  Path is truncating the path to 1024 characters.

**Comment by Jetersen** [comment]
That's even more concerning 😰

**Comment by jetersen** [comment]
As there are released windows 2019 images according to the tags: https://github.com/actions/virtual-environments/commit/f67375ac5cd480959b184c92c9dda601c9db3982

I can validate that the issue is fixed: https://github.com/jenkinsci/hashicorp-vault-plugin/pull/95
