### ISSUE TITLE
Virtual env

### ISSUE THREAD

**Issue by WilsonHorse1** [actions/virtual-environments#639]

**Comment by andy-mishechkin** [comment]
Hello.
Could you please update issue description to provide details about your issue, build steps and affected environments

**Comment by WilsonHorse1** [comment]
You’re obviously a puff
    	
    	

    	Get Outlook for iOS
    
  




On Mon, Mar 30, 2020 at 7:48 AM +0100, "Andy Mishechkin" <notifications@github.com> wrote:















Hello.

Could you please update issue description to provide details about your issue, build steps and affected environments
