### ISSUE TITLE
Is there a changelog of deployed environment changes.

### ISSUE THREAD

**Issue by phadej** [actions/virtual-environments#644]
I'm suspecting that I'm experiencing an issue with the same underlying reason as https://github.com/actions/virtual-environments/issues/625. There is a comment

> Probably, it is related to VS 16.5 that is rolling out right now.

Having these changes easily discoverable would simplify adopting to the changes: one would know what changed without reporting "what broke".

EDIT: The releases do contain notes, but it's very hard to filter what changed from these.
EDIT2: the https://github.com/actions/virtual-environments/releases/tag/win19%2F20200319.1 notes do not have asterisk to show that `Version: VisualStudio/16.4.5+29806.167` is changed to `Version: VisualStudio/16.5.0+29911.84`

**Comment by JustinGrote** [comment]
I agree, some sort of json manifest or something of an images contents would be extremely helpful.

**Comment by alepauly** [comment]
Thanks @phadej, we agree and we'll look into improving the release notes to capture the changes only and make differences easier to discover.

 @JustinGrote, can you open a separate issue for a machine readable version of the contents. I think it's an interesting idea and having it on its own issue could help drive some discussion about what it should look like if it was to get done. Thank you.

**Comment by maxim-lobanov** [comment]
Hello everyone, recently we have implemented this improvement in scope of another feature.
New releases contain diff between old image and new one instead of full documentation. [Example](https://github.com/actions/virtual-environments/releases/tag/macos-10.15%2F20200618.1).
I am closing the issue but feel free to ping if you have any additional questions
