### ISSUE TITLE
Conflict of CPack in PATH

### ISSUE THREAD

**Issue by dragon-archer** [actions/virtual-environments#649]
**Describe the bug**
There are two `cpack.exe` in PATH
1. The alias of `choco pack` for Chocolatey
2. The pack module of the CMake suite

The first one (placed in `%ChocolateyInstall%\bin\`) is in front of the second one (placed in CMake  installtion dir), so when use `cpack` in cmd, it will call the first one.
But actually, the first one is just an alias, while the second one is an important program, and the second one is more important the the first one. 

**Area for Triage**: 
Packages

**Question, Bug, or Feature?**: 
Bug

**Virtual environments affected**
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [x] Windows Server 2016 R2
- [x] Windows Server 2019

**Expected behavior**
The cpack in CMake suite is in front of the  alias in PATH, and `cpack` command will call the second one above.

**Actual behavior**
The `cpack` command call the alias

**Solution**
There are two ways to solve this problem
1. Remove the alias (can be done with `del /F /Q %ChocolateyInstall%\bin\cpack.exe`)
2. Change the PATH order, put the Chocolatey behind CMake

**Comment by xnorpx** [comment]
this one is really annoying please fix

**Comment by al-cheb** [comment]
Hello, @dragon-archer 
The default cmake has been set to - `C:\Program Files\CMake\bin\cpack.exe`

![cpack](https://user-images.githubusercontent.com/47745270/80343430-86594980-886e-11ea-9569-edf2d17d40b7.JPG)

Feel free to open the thread if you have any concerns.

**Comment by antonioborondo** [comment]
The same problem is happening again.
