### ISSUE TITLE
Preinstalled now cli has bugs, and can't override with `npx`.

### ISSUE THREAD

**Issue by antony** [actions/virtual-environments#65]
**Describe the bug**

Now CLI releases multiple times per week and therefore it is unlikely to remain up-to-date for long. Sadly, their releases do sometimes break things, and the currently preinstalled now cli version has a problem with custom builders which is critical to deployment.

Generally, `npx` could be used with `--ignore-existing` to simply override the preinstalled cli and use the requested one:

```bash
npx now@latest --ignore-existing -v
```

However this yields the error:

```bash
##[error]Process completed with exit code 1.
Run npx now@latest --ignore-existing -v
> Error! Could not remove your previous Now CLI installation.
Please use this command to remove it: `sudo rm /usr/local/bin/now`.
Then try to install it again.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! now@16.4.3 preinstall: `node ./scripts/preinstall.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the now@16.4.3 preinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2019-10-28T14_37_35_285Z-debug.log
Install for now@latest failed with code 1
##[error]Process completed with exit code 1.
```

Having preinstalled software is a boon to productivity, but it is important to be able to override versions easily (and npx is a great tool for this purpose). Enabling it to work properly is critical to making github actions useful as a CI/CD service.

**Virtual environments affected**
- [ ] macOS 10.14
- [X] Ubuntu 16.04 LTS
- [X] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Expected behavior**

I would expect `npx` in combination with `--ignore-existing` to be able to override any preinstalled global `npm` dependency.

**Actual behavior**

1. `npx now@latest --ignore-existing -v`

Should show version 16.4.3 (at the time of this writing).

**Comment by alepauly** [comment]
Hi @antony, thanks for reporting. We're currently rolling out new versions for the Ubuntu 16.04 and Ubuntu 18.04 environments built on 10/25 and that report Zeit Now 16.4. The currently deployed environments have 16.3.1. Depending on where your repos are in our infrastructure and assuming there are no deployment delays, you should get the new versions between 10/29 and 10/31. I'll keep you posted on delays.

I'm not sure why ```npx``` is not working as expected, we'll investigate that as well but it would be helpful if you can provide the output of the additional logging output (e.g. /home/runner/.npm/_logs/2019-10-28T14_37_35_285Z-debug.log). If it's too long or you prefer not to share it here please attach it to an email to alepauly@github.com. Thanks!

**Comment by alepauly** [comment]
@antony I just ran a quick test and got the same results using ```npx now@latest --ignore-existing -v``` (even running as ```sudo```). I also tried ```sudo npm i -g now@latest``` and that seemed to update to the latest (16.4.4). Give it a try to see if it unblocks you while we rollout the latest, not sure why ```npx``` doesn't behave though so we'll still look into that.

**Comment by maxim-lobanov** [comment]
Hi!
It looks like the issue is not actual anymore? Could you please confirm?

**Comment by antony** [comment]
Yeah I was able to work around the issue. However I left this open since @alepauly wanted to look into the issue with npx.

I'll close this for now and a more relevant issue can be opened regarding the npx issue if it still exists.
