### ISSUE TITLE
Ruby 2.7.1 support

### ISSUE THREAD

**Issue by raulpopadineti** [actions/virtual-environments#656]
**Tool information**
- Tool name: [Ruby lang](https://www.ruby-lang.org/en/)
- Add or update? update
- Desired version: `2.7.1`
- Approximate size: 
- If this is an add request:
  - Brief description of tool: Ruby is a dynamic, open source programming language with a focus on simplicity and productivity. It has an elegant syntax that is natural to read and easy to write. 
  - URL for tool's homepage: https://www.ruby-lang.org/en/

**Area for Triage**:
Ruby

**Question, Bug, or Feature?**:
"Feature"

**Virtual environments affected**
- [ ] macOS 10.15
- [x] Ubuntu 16.04 LTS
- [x] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Can this tool be installed during the build?**
No.

**Are you willing to submit a PR?**
I'm not sure I'm proficient enough to do it 😰

**Comment by miketimofeev** [comment]
@raulpopadineti thanks for keeping an eye on ruby releases! We will include all new ruby releases in the next image rollout(approx 1 week): 2.7.1, 2.6.6, 2.5.8, 2.4.10

**Comment by miketimofeev** [comment]
@raulpopadineti we have deployed the new image with Ruby 2.7.1
I'm going to close the issue, but feel free to ping me if you have any concerns.
Thank you!

**Comment by raulpopadineti** [comment]
Thank you very much @miketimofeev !! 🙇
