### ISSUE TITLE
Apple builds suddenly super slow internet connection

### ISSUE THREAD

**Issue by kceb** [actions/virtual-environments#657]
**Describe the bug**

Recently the setup step for my macOS machines, which only downloads github actions, takes around 5 minutes. NPM install takes 10-20 minutes. In the past, the times for installing dependencies were comparable to ubuntu machines, which I use for Android app builds.

In comparison, the same step takes 30 seconds or less on ubuntu machines.

Was internet access in these machines recently throttled?

**Area for Triage**: Apple

**Question, Bug, or Feature?**: Bug

**Virtual environments affected**
- [x] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Expected behavior**
Setup step in the beginning and npm install should be a lot quicker

**Actual behavior**
Any step that installs dependencies from the internet takes a very long time.

**Comment by miketimofeev** [comment]
Hi @kceb! Could you please provide any samples that work fine on Ubuntu, but not on macOS?

**Comment by kariharju** [comment]
Ran in to same issue on separate projects as well during last week and the problem seems to continue.

A step where we perform yarn install or npm install last Friday took over 8 mins for macos-latest. 
Same step on ubuntu-latest 58 s, and on windows-latest 117 s

At the time of posting this I'm running into similar behavior also on ubuntu-latest. For windows the full pipeline ran in under 5 mins (setup step took 106 s), but the same step in the same workflow for ubuntu took over 11 mins and with mac 10 mins.

**Comment by miketimofeev** [comment]
@kceb @kariharju could you provide some repro steps, please?

**Comment by kariharju** [comment]
Was just about to comment that just now got one Mac run to pass setup phase in 45 s.
The same step yesterday took over 10min.
The step is running npm install in one folder and yarn in another:
_cd ui ; yarn install --frozen-lockfile; cd ../agent ; npm ci_

**Comment by kariharju** [comment]
Again the setup step on Mac is back to taking several minutes (ranging between 4-10 mins). Windows and Ubuntu have now been stable at around 1 min for the same step.
Have to ask: These are probably considered as billable action minutes..?

**Comment by miketimofeev** [comment]
@kariharju @kceb could you provide any runs with issues so we will be able to get the information about the environment for that run? It'd be very helpful for further investigation because we still can't repro it on our side.

**Comment by kceb** [comment]
@miketimofeev honestly, the time has improved drastically over the past couple days. Maybe it had to do with caching? I did notice the runner version has went through several patch updates since then.

Mac setup steps now take around 1 minute, ubuntu takes around 20 seconds. 1 minute is a lot better than the previous 5 minutes.

These are the logs from the 5 minute setup step from last week:

```
2020-03-30T19:19:57.3265410Z Current runner version: '2.165.2'
2020-03-30T19:19:57.3267110Z Prepare workflow directory
2020-03-30T19:19:57.3640750Z Prepare all required actions
2020-03-30T19:19:57.3657280Z Download action repository 'actions/checkout@v2'
2020-03-30T19:20:04.2196730Z Download action repository 'kceb/git-message-action@v1'
2020-03-30T19:20:14.0203710Z Download action repository 'kceb/pull-request-url-action@v1'
2020-03-30T19:20:24.0213180Z Download action repository 'shimataro/ssh-key-action@v2'
2020-03-30T19:20:24.9335590Z Download action repository 'dcodeIO/setup-node-nvm@master'
2020-03-30T19:20:25.6587380Z Download action repository 'bahmutov/npm-install@v1.4.0'
2020-03-30T19:20:26.6992040Z Download action repository 'kceb/fastlane-action@v1.5.0'
2020-03-30T19:23:59.2174660Z Download action repository 'rnkdsh/action-upload-diawi@v1.0.0'
2020-03-30T19:25:05.9053360Z Download action repository 'Gottox/url-shortener-action@v1.0.0'
2020-03-30T19:25:14.5960930Z Download action repository 'archive/github-actions-slack@master'
2020-03-30T19:25:15.6390110Z Download action repository 'kceb/add-pr-comment@v1.1.0'
```

Maybe the update to 2.168.0 solved some things? Not sure, but I'm fine with closing unless @kariharju has more details for his builds.

**Comment by miketimofeev** [comment]
@kceb @kariharju we've worked out some issues with one of the environments and that might potentially resolve the issue. Let's wait for a few more days.

**Comment by kariharju** [comment]
For us as well the install step times have now settled into the 1 min range on Mac as well.

Thanks a bunch! 
This helps out significantly in figuring out the maze of Mac signing process.
The actual mac notarizing phase also takes around 10 mins (don't know if this is the electron-builder or the actual mac stuff) so now we can build in 15 mins instead of 30 which is .. significant 🥇

**Comment by al-cheb** [comment]
@kceb @kariharju Feel free to open the thread if you have any concerns.
