### ISSUE TITLE
Boost Package version suddenly changed

### ISSUE THREAD

**Issue by 9prady9** [actions/virtual-environments#661]
**Describe the bug**
[ArrayFire](https://github.com/arrayfire/arrayfire) is an open source GPGPU library. We use github actions to build/test our CPU backend. We started using Ubuntu 16.04 which had boost 1.69 since we began. All of a sudden, since couple of days, our build process reported boost 1.58 and failed. I can verify this from our logs also.

**Area for Triage**:  C/C++

**Question, Bug, or Feature?**:  Bug

**Virtual environments affected**
- [ ] macOS 10.15
- [x] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Expected behavior**
Ubuntu 16.04 had boost 1.69 before couple of days. I can confirm this from out old cmake build log that shows boost found as 1.69 - https://ci.arrayfire.org/viewConfigure.php?buildid=8440

**Actual behavior**
1. And since couple of days, cmake reports ubuntu 16.04 has boost 1.58 - https://ci.arrayfire.org/viewConfigure.php?buildid=9323
2. Even github README says ubuntu 16.04 should have boost 1.69 - https://github.com/actions/virtual-environments/blob/master/images/linux/Ubuntu1604-README.md

The issue can be reproduced by trying to configure/build a CMake project that requires boost (versions 1.67 or greater). You can look at our workflow file and use that for issue reproduction as well. https://github.com/arrayfire/arrayfire/blob/master/.github/workflows/cpu_build.yml

Please let us know if this going to be fixed soon or we have to adjust our yml to this new change where Ubuntu 1.604 LTS image will have boost 1.58 unlike earlier.

Thank you,
Pradeep.

**Comment by al-cheb** [comment]
Hello, @9prady9 
We have deprecated `BOOST_ROOT` environment variable - https://github.com/actions/virtual-environments/issues/319.

Current image variables:
```
BOOST_ROOT_1_72_0=/usr/local/share/boost/1.72.0
BOOST_ROOT_1_69_0=/usr/local/share/boost/1.69.0
```

Could you please define `BOOST_ROOT` environment variable at runtime?

BOOST_ROOT=$BOOST_LIB/$BOOST_VERSION

**Comment by 9prady9** [comment]
That would mean the ubuntu 16.04 images have system boost package (1.58) also installed along with 1.69 and 1.72.0, right ? I was under the impression that system package was replaced by newer version that were listed in the documentation. I can use these versioned boost variables to set `BOOST_ROOT` cmake option. That should do the job for us.

Please feel free to close the issue, I think my question has been answered. Thank you!

**Comment by 9prady9** [comment]
@al-cheb Are these variables available on macos-latest image too ?

**Comment by al-cheb** [comment]
@9prady9, We have never had boost package (1.58) on Ubuntu images. I think it's related with FindBoost function in cmake when BOOST_ROOT is missing and installed on non-default directory.

Sorry, but we don't have boost on macOS image and don't plan to add it - https://github.com/actions/virtual-environments/issues/356#issuecomment-587519480

```
thejoebourneidentity commented on Feb 18
Thanks for your suggestion 🙏. Considering the maintenance concerns for the added disk footprint, this is not something we will add to the image at this time.
```

**Comment by 9prady9** [comment]
sounds good.
