### ISSUE TITLE
Add Android Emulator and tools for macOS image

### ISSUE THREAD

**Issue by another-dave** [actions/virtual-environments#663]
**Tool information**
- Tool name: Android's `emulator` and latest system images
- Add or update? Add
- Desired version: Ideally, System images that can run the last few version of Android (e.g. API levels 30/29/28) with Google Play Services installed.
- Approximate size: 
- If this is an add request:
  - Brief description of tool: Google's `emulator` tool for Android to allow Instrumentation Tests to run as part of CI build. Basically, looking for the functionality of [ReactiveCircus/android-emulator-runner](https://github.com/ReactiveCircus/android-emulator-runner) but pre-installed
  - URL for tool's homepage: https://developer.android.com/studio/command-line/

**Area for Triage**: Android, Apple

**Question, Bug, or Feature?**: Feature

**Virtual environments affected**
- [x] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Can this tool be installed during the build?**
Currently solving via [ReactiveCircus/android-emulator-runner](https://github.com/ReactiveCircus/android-emulator-runner). Takes between 4min–8mins, as large files downloaded.

**Are you willing to submit a PR?** If possible, sure

**Comment by maxim-lobanov** [comment]
Hello, thank you for your suggestion.
Considering the size of emulators, we don't have resources to pre-install and support android emulators on macOS image for now. Probably, we will be able to revisit this decision in future if we see more interests for it and have resources to support it.

Emulators can be installed in runtime using the following code (it takes about 1 minute to install one particular emulator):
```
${ANDROID_HOME}/tools/bin/sdkmanager --install "system-images;android-29;google_apis_playstore;x86_64"
```
