### ISSUE TITLE
Create docker images for linux environment

### ISSUE THREAD

**Issue by oleg-brizy** [actions/virtual-environments#666]
**Tool information**
- Tool name: Docker
- Add or update? Add
- Desired version: -
- Approximate size: -
- If this is an add request:
  - Brief description of tool: Docker image to be used as base for self hosted runner containers
  - URL for tool's homepage: https://hub.docker.com/

**Area for Triage**: -

**Question, Bug, or Feature?**: Feature

**Virtual environments affected**
- [ ] macOS 10.15
- [x] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Can this tool be installed during the build?** No

**Are you willing to submit a PR?**
No. I am not familiar with current environments format.

----

I tried to create a self hosted runner for a PHP project but it doesn't work https://github.com/shivammathur/setup-php/issues/209

I am not sure why, but I guess I need to install [a bunch of packages](https://github.com/actions/virtual-environments/blob/releases/ubuntu18/20200330/images/linux/Ubuntu1804-README.md) in my docker container (where the self hosted runner is installed) so it will be compatible with the same setups that work with `ubuntu-latest`.

**Comment by alepauly** [comment]
hi @oleg-brizy, unfortunately we won't be able to work on this but I'll leave this open in case someone out there has a chance to figure it out. Thanks for the feedback. It's not the first time it's requested: https://github.com/actions/virtual-environments/issues/196

**Comment by lgmorand** [comment]
I do agree, that's a need. Especially because it was available for AzDO (https://github.com/Microsoft/azure-pipelines-image-generation/)

I do hope, it'll get in the backlog at one moment :)

**Comment by ezYakaEagle442** [comment]
👍 
see also [https://github.com/MicrosoftDocs/azure-docs/issues/54750](https://github.com/MicrosoftDocs/azure-docs/issues/54750)

**Comment by shivammathur** [comment]
For [`shivammathur/setup-php`](https://github.com/shivammathur/setup-php) after `2.2.0` release, [`shivammathur/node`](https://github.com/shivammathur/setup-php) docker images can be used for ubuntu workflows. For `windows` workflows `servercore` docker image with `pwsh` installed would work.

Example Dockerfile for setting up self-hosted runner - [Ubuntu](https://github.com/shivammathur/setup-php/wiki/Dockerized-self-hosted-runner-on-Ubuntu), [Windows](https://github.com/shivammathur/setup-php/wiki/Dockerized-self-hosted-runner-on-Windows)

**Comment by CatTheHacker** [comment]
I've built `ubuntu-20.04` in Docker, https://quay.io/repository/catthehacker/virtual-environments?tab=tags
This image has almost all software that is in GitHub Actions runner except for: cached Docker images (due to not being able to run Docker inside Docker build), Android (it randomly fails), currently tests for all Dotnet versions were skipped due to how time consuming they are, there are certain tests that are also skipped because I couldn't get them to work during build (mysql, postsgres, `docker info`), GitHub Actions Self-Hosted Runner is not included as well.

**Comment by 01e9** [comment]
https://hub.docker.com/r/01e9/github-actions-runner

**Comment by lgmorand** [comment]
@01e9 thanks! could you edit the hub description with a link to your repo. Always safer to know what's inside the container :) and also to see argument, especially the TZ your defaulted with your city

**Comment by catthehacker** [comment]
IMHO, there is a better base image containing `runner`: https://github.com/myoung34/docker-github-actions-runner

**Comment by 01e9** [comment]
> @lgmorand https://github.com/actions/virtual-environments/issues/666#issuecomment-779031706

Done https://github.com/actions/virtual-environments/issues/666#issuecomment-778866469

**Comment by shughes-uk** [comment]
this would be very helpful for those of us who want to use self hosted runners without breaking support for almost every action on the marketplace which makes assumptions about what is available

**Comment by catthehacker** [comment]
@shughes-uk might want to look at https://github.com/nektos/act && https://github.com/nektos/act/blob/master/IMAGES.md

**Comment by shughes-uk** [comment]
> @shughes-uk might want to look at https://github.com/nektos/act && https://github.com/nektos/act/blob/master/IMAGES.md

The actions/virtual-environment's full images seem to have last been updated feb 2020 which means they're pretty stale. Official docker images would be hopefully fully maintained.

**Comment by catthehacker** [comment]
@shughes-uk It will not happen since some of the software cannot be redistributed due to licencing.
https://github.com/actions/virtual-environments/discussions/2320#discussioncomment-328445

`catthehacker/full-20.04` has been updated 5 months ago if that's ok for you

**Comment by shughes-uk** [comment]
> @shughes-uk It will not happen since some of the software cannot be redistributed due to licencing.
> [#2320 (comment)](https://github.com/actions/virtual-environments/discussions/2320#discussioncomment-328445)
> 
> `catthehacker/full-20.04` has been updated 5 months ago if that's ok for you

I'd love to but after codecov everyone is a little shaky on introducing unofficial things like this. What a pain.

**Comment by catthehacker** [comment]
There are plans for smaller images though: https://github.com/actions/virtual-environments/discussions/3242

**Comment by shughes-uk** [comment]
> There are plans for smaller images though: #3242

awesome! might solve things.

**Comment by miketimofeev** [comment]
Closing this for now as now progress was made throughout the year
