### ISSUE TITLE
Update Visual C++ to 16.5.2

### ISSUE THREAD

**Issue by leecbaker** [actions/virtual-environments#667]
**Tool information**
- Tool name: Visual C++
- Add or update? Update
- Desired version: 16.5.2
- Approximate size: 

**Area for Triage**:
C/C++

**Question, Bug, or Feature?**:
Bug

**Virtual environments affected**
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [x] Windows Server 2019

**Can this tool be installed during the build?**
Unknown/probably not.

**Are you willing to submit a PR?**
No

Visual C++ has a couple of bugs causing internal compiler errors when compiling templated code. One has been fixed in version 16.5.1 (released March 24), and one in 16.5.2 (March 31). Would be great to get the latest updates installed, as it seems to be affecting a significant number of people.

Reference: https://docs.microsoft.com/en-us/visualstudio/releases/2019/release-notes

**Comment by andy-mishechkin** [comment]
Visual Studio Version 16.5.2 will be updated in the next image automatically.

**Comment by leecbaker** [comment]
A couple of additional patch releases of Visual Studio have come out since I created this issue- we're now up to [16.5.4](https://docs.microsoft.com/en-us/visualstudio/releases/2019/release-notes). I hope we can get the latest version included in the runners soon.

> The tools included in GitHub-hosted runners are updated weekly.

I see that runner software was [updated weekly](https://help.github.com/en/actions/reference/software-installed-on-github-hosted-runners), but it looks like no updates have happened since the 20200319 version. I know the covid19 situation is affecting all of us- are there any updates to when the runner software might be updated again?

**Comment by maxim-lobanov** [comment]
Hello @leecbaker , we had a bunch of infra issues that prevented us to start deployment earlier. Sorry for delay and inconvenience.
We are planning to start new deployment today. It will contain VS 16.5.4 on board.
We are expecting it to reach all VM on Tue next week.

**Comment by maxim-lobanov** [comment]
@leecbaker , Image with VS 16.5.4 has been deployed recently. Closing the issue. Please let me know if you have any issues with it
