### ISSUE TITLE
Node.js Assertion failed: new_time >= loop->time

### ISSUE THREAD

**Issue by alexlamsl** [actions/virtual-environments#67]
**Describe the bug**
Node.js (libuv) fails with the following error:
```
Assertion failed: new_time >= loop->time, file src\win\core.c, line 309
```

According to https://github.com/libuv/libuv/issues/1633, this is due to system clock drifting, which is why I reckon I'll file an issue report here.

**Virtual environments affected**
- [ ] macOS 10.14
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [x] Windows Server 2019

**Expected behavior**
Runs `node.exe` without hitting any assertion errors.

**Actual behavior**
(Node.js 8.16.2)
https://github.com/alexlamsl/UglifyJS2/runs/283660602#step:3:53

**Comment by alexlamsl** [comment]
Another occurrence (Node.js 4.9.1): https://github.com/alexlamsl/UglifyJS2/runs/302975920#step:4:46

**Comment by miketimofeev** [comment]
@alexlamsl thanks for reporting this. Is it still actual? If yes, could you please provide another build example? Previous ones have already expired.

**Comment by alexlamsl** [comment]
There has been other failures with e.g. provision but not this particular type recently, and given the previous frequency of occurence this may have been resolved already.

Closing for now &minus; thanks for your time!

**Comment by alepauly** [comment]
@alexlamsl thanks for the update. I actually was looking briefly into this and I wonder if disabling the Ntp update would help. I found the following instructions [here](https://docs.microsoft.com/en-us/azure/virtual-machines/windows/time-sync#host-only):

```
reg add HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\w32time\TimeProviders\VMICTimeProvider /v Enabled /t REG_DWORD /d 1 /f
reg add HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\w32time\TimeProviders\NtpClient /v Enabled /t REG_DWORD /d 0 /f
echo 'restarting'
net stop w32time
net start w32time
```
Based on what I read, it's possible this can alleviate the issue if you still see it pop up once in a while. You should be able to add this at the beginning of your builds.
