### ISSUE TITLE
Add enviroment variable to contain runner version

### ISSUE THREAD

**Issue by traversaro** [actions/virtual-environments#670]
**Describe the bug**
In the GitHub Actions there is now the ImageVersion env variable that contains the image version, but it would be useful to have also a variable that contains the runner version. As on some platforms (for example macOS) the `${GITHUB_WORKSPACE}` path contains the runner version, this can create problems with tools that hard-code their path in the build files if they are cached. To invalidate in an easy way the cache in this case, it would be great to have a env variable that contains the runner version, so it can be include in the cache id to automatically invalidate the cache when the  `${GITHUB_WORKSPACE}` changes. Unfortunately using directly the `${GITHUB_WORKSPACE}`  env variables does not work, probably because it contains strange characters as `/`.

**Area for Triage**: 

**Question, Bug, or Feature?**: 
Feature

**Virtual environments affected**
- [x] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Expected behavior**
It would be great to have an environment variable that contains the runner version, for use with cache.

**Actual behavior**
At the moment, there is no direct env variable that contains the runner version.

**Comment by traversaro** [comment]
See https://github.com/robotology/whole-body-estimators/issues/60 for a related downstream issue.

**Comment by maxim-lobanov** [comment]
Hello @traversaro , thank you for your suggestion.
I believe it is request for https://github.com/actions/runner

**Comment by traversaro** [comment]
Thanks @maxim-lobanov , that probably make sense, thanks for the hint! 
In any case, I discovered that while `${{ env.GITHUB_WORKSPACE }}` is not working correctly for some reason (probably you can use like that only the enviromental variable that you explicitly declared in the `yml` file) the `${{ runner.temp }}` expression works correctly (see https://github.com/robotology/idyntree/pull/667) so that is working for me, thanks!
