### ISSUE TITLE
Remove the reference to 3.1.102 in the .Net Core SDK installation scripts

### ISSUE THREAD

**Issue by SeanFarrow** [actions/virtual-environments#673]
Now that .Net Core sdk 3.1.201 has been released, do we need to concern ourselves with
[this](https://github.com/dotnet/aspnetcore/issues/19133)
issue?
If not, I'm happy to update the scripts to remove all checks for 3.1.102.
Thanks,
Sean.

**Comment by dsame** [comment]
The changes have been merged and are in the deploy process

**Comment by miketimofeev** [comment]
@SeanFarrow we've removed all checks and 3.1.102 is presented on all the images. I'm going to close the issue, but feel free to contact us if you have any concerns.
Thank you!

**Comment by SeanFarrow** [comment]
Hi,

Thanks for doing this.

Does this mean it will use the latest SDK at the time the image is updated?

My concern is the fact that the .Net core 3 SDK is updated and these images will not receive updates in a timely fashion.

**Comment by AlenaSviridenko** [comment]
Hi @SeanFarrow,
we are using the latest stable released .Net Core SDK from [GitHub releases](https://raw.githubusercontent.com/dotnet/core/master/release-notes/releases-index.json) as the default one, so for .Net Core 3 SDK the latest one is the 3.1.301. It will be updated automatically to the next one with new release in .Net Core 3 SDK
