### ISSUE TITLE
images/macos/macos-10.15-Readme.md - use ImageVersion in commit subject

### ISSUE THREAD

**Issue by MSP-Greg** [actions/virtual-environments#676]
**Describe the bug**

Feature request:

Please consider using the environment variable `ImageVersion` in the commit subject for the commits to images/macos/macos-10.15-Readme.md.

**Area for Triage**: 

**Question, Bug, or Feature?**: 
Feature

**Virtual environments affected**
- [x] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Expected behavior**

**Actual behavior**

**Comment by miketimofeev** [comment]
@MSP-Greg A really good point, thanks! We will include ImageVersion in the commit subject starting this week.
