### ISSUE TITLE
Boost header(s) files not found

### ISSUE THREAD

**Issue by MonkeyBreaker** [actions/virtual-environments#687]
**Describe the bug**

After updating `BOOST_ROOT` according to #661 to `list(APPEND BOOST_ROOT $ENV{BOOST_ROOT_1_72_0})`. CMake finds the this folder:

```bash
 - Boost_INCLUDE_DIRS: C:/hostedtoolcache/windows/Boost/1.72.0
```

The problem is our compilation fails because it cannot find some headers files:

```bash
* boost/pending/disjoint_sets.hpp
* boost/function_output_iterator.hpp
* boost/range.hpp
```

I looked into `C:/hostedtoolcache/windows/Boost/1.72.0/boost` but the files are not present (starting at line [165](https://dev.azure.com/maintainers/Giotto/_build/results?buildId=1935&view=logs&j=f8540817-cc79-5629-04f4-2ad22f18b9fe&t=ec14c9e1-a75a-5e32-39b4-48b213856522) of our pipeline, youll see all the files present in `boost` folder).

I also tried with `1_69_0` same result.

Do I need to do something special to have access to the previous header files ?

**Area for Triage**: 

**Question, Bug, or Feature?**: 

Bug and question.

**Virtual environments affected**
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [X] Windows Server 2016 R2
- [ ] Windows Server 2019

**Expected behavior**
Build passes succesfully.

**Actual behavior**
Build fails with boost header files not found.

**Comment by al-cheb** [comment]
Hello, @MonkeyBreaker 
These headers are located in `{BOOST_ROOT_1_72_0}\include\boost`.

**Comment by MonkeyBreaker** [comment]
Okay, thank you !

But why is `Boost_INCLUDE_DIRS` set to `C:/hostedtoolcache/windows/Boost/1.72.0`  ? It should point to the folder containing the headers files, no ? If I understood correctly the documentation.

**Comment by al-cheb** [comment]
We use non default path for boost thus, not be found by CMake, you can tell CMake where to look for:
```
SET (BOOST_ROOT "$ENV{BOOST_ROOT_1_72_0}")
SET (BOOST_INCLUDEDIR "$ENV{BOOST_ROOT_1_72_0}\boost\include")
SET (BOOST_LIBRARYDIR "$ENV{BOOST_ROOT_1_72_0}\lib")
```

**Comment by MonkeyBreaker** [comment]
We could also add them to the `.yaml` file directly as variables ?
Or would they be overwritten if we call `find_package(Boost)` ?

**Comment by al-cheb** [comment]
@MonkeyBreaker, any updates?

**Comment by MonkeyBreaker** [comment]
I'll look this week for a solution to add the variables into the `.yaml` file.
As a workaround, we download boost header into a specific location, It's not very efficient, but it works.

As I said before, I'll look for a better solution this week, and post here any updates.

**Comment by MonkeyBreaker** [comment]
Hi,

Well after digging this morning on the issue, I did not find any solution with only touching the .yaml file. I'm not an expert on this field, maybe someone else could come with a solution, but I'm won't explore further.

The solution in our case that would not impact other users for the library is to do as follow:

```cmake
if(DEFINED $ENV{BOOST_ROOT_1_72_0})
    list(APPEND BOOST_ROOT "$ENV{BOOST_ROOT_1_72_0}")
    list(APPEND BOOST_INCLUDEDIR "$ENV{BOOST_ROOT_1_72_0}\boost\include")
    list(APPEND BOOST_LIBRARYDIR "$ENV{BOOST_ROOT_1_72_0}\lib")
endif()

find_package(Boost ...)
```

I only have a last remark, could it be possible that you create a "generic" variable to the latest version of boost in the system ? Something around `BOOST_ROOT_LATEST`, in my opinion, if you update to a newer release in the future, I won't need to update my files to use the latest version in the pipeline. 

Have a nice day,
Julián

**Comment by MonkeyBreaker** [comment]
Hello @al-cheb,

I like your solution, if you update on your side, we only need to touch the `yaml` file.

For me we can close this issue, but I don't know if it's already in the documentation, maybe add more information about the boost include directories, what do you think ?

Otherwise, thank you for your help,
Julián

**Comment by maxim-lobanov** [comment]
@MonkeyBreaker thank you for your suggestion!
We are planning to add some troubleshooting page for our images to describe such cases. We will add this point there as soon as it is ready.

I am closing this issue for now. Feel free to ping if you have any questions
