### ISSUE TITLE
Add gperf

### ISSUE THREAD

**Issue by brentru** [actions/virtual-environments#69]
**Tool information**
- Tool name: gperf
- Add or update? Add
- Desired version: Latest
- Approximate size: 
- If this is an add request: 
  - Brief description of tool: GNU gperf is a perfect hash function generator. For a given list of strings, it produces a hash function and hash table, in form of C or C++ code, for looking up a value depending on the input string. The hash function is perfect, which means that the hash table has no collisions, and the hash table lookup needs a single string comparison only.
  - URL for tool's homepage: https://www.gnu.org/software/gperf/

**Can this tool be installed during the build?**
Yes

**Are you willing to submit a PR?**
Yes

**Comment by maxim-lobanov** [comment]
Hello @brentru , what images do you need to install it?
Also you mentioned that this tool can be installed in runtime, how much time does it take?

**Comment by maxim-lobanov** [comment]
Tool can be installed in runtime:
```
# Ubuntu
sudo apt-get install -y gperf
# macOS
brew install gperf
# Windows
choco install gperf
```
Installation takes about 10 seconds

**Comment by alepauly** [comment]
Considering this is a small tool and easy to install during the workflow, I dont think we should bake it into the image. Thanks for the suggestion @brentru.
