### ISSUE TITLE
Update CMake to 3.17.0

### ISSUE THREAD

**Issue by rick-de-water** [actions/virtual-environments#694]
**Tool information**
- Tool name: CMake
- Add or update? Update
- Desired version: 3.17.0 (latest)
- Approximate size: ~38.7 MB, but it replaces the old version.

**Area for Triage**:
C/C++

**Question, Bug, or Feature?**:
Feature

**Virtual environments affected**
- [ ] macOS 10.15
- [x] Ubuntu 16.04 LTS
- [x] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Can this tool be installed during the build?**
Yeah, not sure how long it takes, but I'm guessing it mostly depends on the download speed.

Also worth to mention, the windows scripts seem to just grab the latest version from chocolatey, so when building a new image it will update automatically. Is this desirable?

**Are you willing to submit a PR?**
I'll give it a shot.

**Comment by rick-de-water** [comment]
I'm not sure how the mac images are updated, but according to the documentation it is already at 3.17.0. So only Linux would be affected, and the Windows documentation would need to be updated.

**Comment by maxim-lobanov** [comment]
Hello @rick-de-water !
You are right, CMake on macOS and Windows images are updated automatically (latest versions are installed). So only Ubuntu should be updated. I believe [this file](https://github.com/actions/virtual-environments/blob/master/images/linux/scripts/installers/cmake.sh).

**Comment by maxim-lobanov** [comment]
I have merged pull-request, thank you for contribution!

**Comment by maxim-lobanov** [comment]
Closing the issue since update was delivered to all images. Sorry for delay
