### ISSUE TITLE
Why is MacOS 10.15 showing a 10.13 SDK?

### ISSUE THREAD

**Issue by bsolomon1124** [actions/virtual-environments#696]
I use `runs-on: [macOS-10.15]` to build a MacOS Python wheel.

The config is here: https://github.com/bsolomon1124/pycld3/blob/wheels/.github/workflows/pythonpackage.yml

Notice this line which initially started out as a sanity check:

```bash
{
  protoc --version;
  sw_vers;
  python3 -c "import distutils.util; print(distutils.util.get_platform())";
} > system_info.log
```

This gives me:

```
libprotoc 3.11.4
ProductName:	Mac OS X
ProductVersion:	10.15.4
BuildVersion:	19E266
macosx-10.13-x86_64
```

And a wheel that looks like:

```
pycld3-0.20-cp38-cp38-macosx_10_13_x86_64.whl
```

As explained in https://github.com/MacPython/wiki/wiki/Spinning-wheels, this means that _the version of the SDK used to compile Python is different than the host OS itself._

Where, if anywhere, is this disclosed in https://github.com/actions/virtual-environments/tree/master/images/macos? 

On my own Mac I see they match, which, without being an expert on this, seems to make more intuitive sense:

```
ProductName:	Mac OS X
ProductVersion:	10.15.4
BuildVersion:	19E266
macosx-10.15-x86_64
```

The 10.13 SDK is kind of outdated at this point, which means the wheel is pointless unless a user has a stale SDK.

**Comment by maxim-lobanov** [comment]
Hello @bsolomon1124,
You are right, currently macOS Python is built on macOS 10.13 and used across all images 10.13, 10.14, 10.15. It was done to simplify maintenance (all images use the same Python binaries, it is easier to diagnose customers' issues) because Python 10.13 is compatible with newer versions of macOS and we have never heard about any issues come from that before.
We definitely agree that 10.13 SDK is outdated at this point (especially because 10.13 image was deprecated on AzDO) and, currently, we are working to switch to Python from 10.14. We are planning to use 10.14 binaries on both macOS 10.14 and 10.15 images (again, to simplify maintenance).
Will it work for you?

If it doesn't work for you and your use-case requires Python with 10.15 binaries, we can consider split binaries for 10.14 / 10.15

**Comment by bsolomon1124** [comment]
Thank you for the quick response @maxim-lobanov . One more question for you if you have the time - you mention:

> used across all images 10.13, 10.14, 10.15

I only see a MacOS-10.15 image listed at https://github.com/actions/virtual-environments/tree/master/images/macos.  Is there a way to use .13 and .14 that I'm missing?  I think the ideal case would be: `runs-on: [macOS-10.15, macOS-10.14, macOS-10.13]`, and where Python is built from a matching SDK on each.

**Comment by maxim-lobanov** [comment]
@bsolomon1124 , As it is mentioned in readme file, this repository contains source code for GitHub Actions and Azure DevOps images. Unfortunately, there is only `macos-10.15` on GitHub Actions. AzDO supports `macos-10.14` and `macos-10.15`.

Thank you for your request. We will consider splitting binaries.

**Comment by bsolomon1124** [comment]
Okay, I believe I may stand correct here.

I originally stated:

```
The 10.13 SDK is kind of outdated at this point, which means the wheel is pointless unless a user has a stale SDK.
```

Some reading and experiment indicates that's not how this actually works.  pip will not require an exact match of the SDK version; it just wants your (the user's) SDK to be greater than or equal to the SDK in the wheel tag. ([more detail here](https://github.com/MacPython/wiki/wiki/Spinning-wheels#question-will-pip-give-me-a-broken-wheel))

```
 [envs/] $ python3 -V
Python 3.8.2
 [envs/] $ python3 -c "import distutils.util; print(distutils.util.get_platform())"
macosx-10.15-x86_64
 [envs/] $ python3 -m venv venv
 [envs/] $ source ./venv/bin/activate
(venv)  [envs/] $ python3 -m pip install --only-binary :all: yarl
Collecting yarl
  Using cached https://files.pythonhosted.org/packages/00/b6/9f8ea44953ec35b824b82a89b99ea2e909c3cb5add81ab367ddd8e204815/yarl-1.4.2-cp38-cp38-macosx_10_13_x86_64.whl
Collecting idna>=2.0 (from yarl)
  Using cached https://files.pythonhosted.org/packages/89/e3/afebe61c546d18fb1709a61bee788254b40e736cff7271c7de5de2dc4128/idna-2.9-py2.py3-none-any.whl
Collecting multidict>=4.0 (from yarl)
  Using cached https://files.pythonhosted.org/packages/bf/da/1b24e4d1bd9fe1b98e9c94bd2007755a2aa48d93d85766ed7f3fadf7c5bb/multidict-4.7.5-cp38-cp38-macosx_10_13_x86_64.whl
Installing collected packages: idna, multidict, yarl
Successfully installed idna-2.9 multidict-4.7.5 yarl-1.4.2
```

Notice in this output:

```
yarl-1.4.2-cp38-cp38-macosx_10_13_x86_64.whl
```

In this example, I am running MacOS 10.15 that uses a Python from 10.15 SDK but am able to install [`yarl`](https://pypi.org/project/yarl/#files) that is tagged 10.13.

So, at least as far as the ease of installing the wheels built via `macos-latest`, I think having a slightly older SDK does not hurt and might actually be beneficial, if I'm reading this all right.

**Comment by maxim-lobanov** [comment]
@bsolomon1124 thank you for the provided details, they are very useful.
Considering these points, I would prefer to keep the current approach for now and use the single set of binaries for all macOS versions. As I mentioned previously, It is significantly easier to debug issues and support the single set of binaries.
We are ok to revisit this strategy in future if we see that it blocks / prevents any customers' use cases.

I think this issue can be closed in this case, please let me know if you have any concerns / objections

**Comment by gerrymanoim** [comment]
I think I'm running into a similar issue. My team is using GA to build + test python extensions with native code on macOS. I was surprised to see that the `macos-10.15` runner was creating `build/temp.macosx-10.14-x86_64-3.8` builds. 

Unfortunately, I believe we're getting errors from clang, because it thinks it is running on 10.14. 

```
    /Users/runner/hostedtoolcache/Python/3.8.3/x64/lib/python3.8/site-packages/libpy/include/libpy/from_object.h:256:29: error: 'path' is unavailable: introduced in macOS 10.15
        static std::filesystem::path f([[maybe_unused]] py::borrowed_ref<> ob) {
                                ^
    /usr/local/opt/llvm/bin/../include/c++/v1/filesystem:738:24: note: 'path' has been explicitly marked unavailable here
    class _LIBCPP_TYPE_VIS path {
```

**Comment by bisoldi** [comment]
I might have a similar issue...Trying to install datadog-lambda and am getting `ERROR: Could not build wheels for ddtrace which use PEP 517 and cannot be installed directly`.  Link to the datadog issue:

https://github.com/DataDog/dd-trace-py/issues/1385
