### ISSUE TITLE
Performance UI Tests won't Pass for macOS Apps

### ISSUE THREAD

**Issue by herzi** [actions/virtual-environments#699]
**Describe the bug**

In Xcode, I created a sample macOS project which works as expected on all my Macs: It builds, the tests pass, archiving works.

**Area for Triage**: 
- Area: Apple

**Question, Bug, or Feature?**: 
Bug

**Virtual environments affected**
- [x] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Steps performed**

1. Create a simple macOS app using Xcode's template (enable unit test and UI tests): [GithubActionSample](https://github.com/herzi/GithubActionSample).
2. Make sure everything works locally: Cmd-B to compile the app, Cmd-U to run unit and UI tests. Select “Product” -> “Archive” to create an archive.
3. Push to Github.
4. Set up a straightforward [set of actions](https://github.com/herzi/GithubActionSample/blob/master/.github/workflows/main.yml).

**Expected behavior**

5. Watch the code be built, tested and archived successfully.

**Actual behavior**

5. The [performance UI tests crash](https://github.com/herzi/GithubActionSample/runs/561967742).

**Comment by dmitry-shibanov** [comment]
Hello @herzi, thank you for your response. Could you please try to add this option `-enableThreadSanitizer YES` to tests. I forked your repository and tests passed: 
- github actions workflows [file](https://github.com/dmitry-shibanov/GithubActionSample/blob/master/.github/workflows/main.yml)
- [test result ](https://github.com/dmitry-shibanov/GithubActionSample/runs/573489506?check_suite_focus=true)

**Comment by maxim-lobanov** [comment]
@herzi , closing this for now because @dmitry-shibanov has provided solution above.
Please let me know if you have any concerns
