### ISSUE TITLE
Chrome not up to date.

### ISSUE THREAD

**Issue by BlueDragon709** [actions/virtual-environments#701]
**Describe the bug**
When running browser test I install the latest chrome-driver to test on. But the chrome-driver is a higher version than the chrome install on the ubuntu latest virtual environment.

**Area for Triage**: 
Testing and code coverage

**Question, Bug, or Feature?**: 
Bug

**Virtual environments affected**
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [x] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Expected behavior**
An up to date chrome version on the virtual environments.

**Actual behavior**
![image](https://user-images.githubusercontent.com/11785665/78888539-1707eb00-7a62-11ea-87d1-7b5ff26eaf9d.png)

**Comment by maxim-lobanov** [comment]
Hello @BlueDragon709 ,
According to documentation, currently, the following versions are available on our image:
- Google Chrome 80.0.3987.149
- ChromeDriver 80.0.3987.106

We update these versions to latest ones on weekly basis and keep them consistent to make sure that customers' builds will work as expected.

As I can see, Google Chrome was updated to 81 in [apt repository a few days ago](https://www.ubuntuupdates.org/package/google_chrome/stable/main/base/google-chrome-stable) so we are expecting to update both Chrome and Chrome WebDriver to 81.x on images next week.

If you want to update Chrome Driver during build to latest version, I would suggest to consider updating Google Chrome too to make sure that the versions are consistent

**Comment by BlueDragon709** [comment]
how would I upgrade Google Chrome in the action?

**Comment by maxim-lobanov** [comment]
It looks like you use incorrect syntax, This doesn't work for me too.
```
sudo apt-get update | sudo apt-get --only-upgrade install google-chrome-stable
```


 Could you please try to use
```
sudo apt-get update
sudo apt-get --only-upgrade install google-chrome-stable
google-chrome --version
```
It works perfect for me:
![image](https://user-images.githubusercontent.com/16715858/78892508-28f18a00-7a72-11ea-81dd-8ec4bea24391.png)

**Comment by BlueDragon709** [comment]
Like so?
![image](https://user-images.githubusercontent.com/11785665/78893031-cb0d7400-7a6a-11ea-8645-7d5a81291208.png)

**Comment by maxim-lobanov** [comment]
Almost, we need to use `|` after `run:` because we use multiline command:
![image](https://user-images.githubusercontent.com/16715858/78893170-7e7a6680-7a73-11ea-9e49-4ca199bb783d.png)

**Comment by BlueDragon709** [comment]
That fixed it.
Thanks 👌

**Comment by maxim-lobanov** [comment]
You are welcome! Please let me know if I can help you somehow
