### ISSUE TITLE
Update macOS agent browser list to include `Safari`

### ISSUE THREAD

**Issue by mydiemho** [actions/virtual-environments#703]
**Tool information**
- Tool name: macOS-10.15 documentation
- Add or update? Update
- Desired version: 
- Approximate size: 
- If this is an add request:
  - Brief description of tool: 
  - URL for tool's homepage: https://github.com/actions/virtual-environments/blob/master/images/macos/macos-10.15-Readme.md#browsers

**Area for Triage**: Apple

**Question, Bug, or Feature?**: 
The [browser section](https://github.com/actions/virtual-environments/tree/master/triage-rules.yml) does not list `Safari` when it is in fact installed on the macOS-10.15 agent.

**Virtual environments affected**
- [x] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Can this tool be installed during the build?**

**Are you willing to submit a PR?** Yes

**Comment by al-cheb** [comment]
Hello, @mydiemho 
We have updated the documentation file to provide info about Safari version  - https://github.com/actions/virtual-environments/blob/master/images/macos/macos-10.15-Readme.md .

Feel free to open the thread if you have any concerns.
