### ISSUE TITLE
Add/Enable FS-iSCSITarget-Server

### ISSUE THREAD

**Issue by pradyunsg** [actions/virtual-environments#708]
**Tool information**
- Tool name: FS-iSCSITarget-Server (feature of Windows)
- Add or update? Add (more like, enable out-of-the-box)
- Desired version: The one that comes as part of respective Windows version
- Approximate size: 
- If this is an add request:
  - Brief description of tool: Allows for putting a directory in a RAMdisk
  - URL for tool's homepage: It's an optional feature of Windows

**Area for Triage**: Packages / Scripting and command line (I guess?)

**Question, Bug, or Feature?**: Feature

**Virtual environments affected**
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [x] Windows Server 2016 R2
- [x] Windows Server 2019

**Can this tool be installed during the build?**
Yes, it can be installed during the build; adds 30 seconds to every build.

**Are you willing to submit a PR?**
I don't know enough about Windows, to be able to file a PR... but I am willing to do so if I could get pointers, about what would need to be done.

See https://github.com/microsoft/azure-pipelines-image-generation/issues/1353 for original upstream request that @vtbassmatt filed based on our feedback + request in pypa/pip#7263.

**Comment by maxim-lobanov** [comment]
Hello @pradyunsg ,
Did you consider enabling this feature in runtime? As I know, enabling of this feature doesn't require reboot so it can be enabled in runtime using the following command (you should add PowerShell step at the begin of your pipeline with the following code):
```
Install-WindowsFeature -Name FS-iSCSITarget-Server -IncludeAllSubFeature -IncludeManagementTools
```
Could you please try and confirm that it works for you?

**Comment by pradyunsg** [comment]
@maxim-lobanov  o/

We do that already -- it was added to our pypa/pip#7263. This issue is a request for it to be enabled by default. There's more context on why we requested this in https://github.com/microsoft/azure-pipelines-image-generation/issues/1353#issuecomment-578533816.

This issue is a follow up on https://github.com/pypa/pip/pull/7263#issuecomment-546973933, which resulted in a filing of microsoft/azure-pipelines-image-generation#1353 which was closed when the repository moved.

**Comment by maxim-lobanov** [comment]
@pradyunsg , thank you for context!
I believe that makes sense to enable it by default

**Comment by pradyunsg** [comment]
@maxim-lobanov Thank you! What would be the next step to enable this by default?

**Comment by maxim-lobanov** [comment]
сс @alepauly to take a look and approve for work when you have a chance

**Comment by al-cheb** [comment]
Hello, @pradyunsg 
The `FS-iSCSITarget-Server` feature is now pre-installed on Windows images. Feel free to open the thread if you have any concerns.

![fs - Copy](https://user-images.githubusercontent.com/47745270/81778573-cd486f80-94fb-11ea-9109-0ca4ef3a89a2.JPG)
