### ISSUE TITLE
Add MingW32

### ISSUE THREAD

**Issue by Tnze** [actions/virtual-environments#71]
**Tool information**
- Tool name: MingW32
- Add or update? Add
- Desired version: latest
- Approximate size: 
- If this is an add request:
  - Brief description of tool: `gcc -m32` on windows
  - URL for tool's homepage: www.mingw.org

**Virtual environments affected**
- [ ] macOS 10.14
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [x] Windows Server 2016 R2
- [x] Windows Server 2019

**Can this tool be installed during the build?**
I'm not sure.

**Are you willing to submit a PR?**
No

**Comment by mingwandroid** [comment]
Wouldn't MSYS2 be a better option here? It supports both 32-bit and 64-bit software and has a very active community around it.

**Comment by Tnze** [comment]
Maybe, I don't know much.

**Comment by larskanis** [comment]
MSYS2 is certainly the better option. There's already an issue for it: #30

**Comment by kaylangan** [comment]
Closing in favor of #30.
