### ISSUE TITLE
Add fonts-noto-color-emoji

### ISSUE THREAD

**Issue by dtinth** [actions/virtual-environments#710]
**Tool information**
- Tool name: fonts-noto-color-emoji
- Add or update? Add
- Desired version: whatever is latest
- Approximate size: 7 MB
- If this is an add request:
  - Brief description of tool: A color emoji font. By default, when capturing web page screenshots via Puppeteer/headless Chrome, emojis are rendered as □□□□. Adding this package fixes that.
  - URL for tool's homepage: https://www.google.com/get/noto/help/emoji/

**Area for Triage**: Packages

**Question, Bug, or Feature?**: Feature

**Virtual environments affected**
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [x] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Can this tool be installed during the build?**
```
sudo apt-get install fonts-noto-color-emoji -y
```
Takes 23 seconds.

**Are you willing to submit a PR?**
Yup

**Comment by C0retek** [comment]
I was just searching for a sollution to Puppeteer/headless Chrome rendering emojis as □□□□ - tried sudo apt-get install fonts-noto-color-emoji -y but did'not work.

Do you have a sollution / workaround?

**Comment by alepauly** [comment]
thanks @dtinth, I don't think this is something we should bake into the runners at this time. To make install during workflows easier you could create an Action that runs the install steps that @C0retek documented (thanks for those!)
