### ISSUE TITLE
 Runner path on macOS changes

### ISSUE THREAD

**Issue by JosephDuffy** [actions/virtual-environments#713]
**Describe the bug**
The path the action being run in changes, which means that caching SwiftPM is not possible because it will fail with the following error:

`<unknown>:0: error: PCH was compiled with module cache path '/Users/runner/runners/2.161.0/work/PROJECT/PROJECT/.build/x86_64-apple-macosx/debug/ModuleCache/Z7RNZCZNAHFT', but the path is currently '/Users/runner/runners/2.162.0/work/PROJECT/PROJECT/.build/x86_64-apple-macosx/debug/ModuleCache/Z7RNZCZNAHFT'`

You can see [an example of this in one of my projects](https://github.com/JosephDuffy/Shepherd/pull/20/checks?check_run_id=340950782).

**To Reproduce**
1. Create a workflow that runs a job on macOS
2. Cache something that uses the path as part of the cache (e.g. SwiftPM)
3. Wait for a new runner version to be deployed
4. Re-run workflow

**Expected behavior**
The path of the runner should not change.

## Runner Version and Platform
macOS

## What's not working?
The path of the runner changes when runner is updated.

Note: This was originally https://github.com/actions/virtual-environments/issues/137

**Comment by alepauly** [comment]
hi @JosephDuffy, apologies that your first attempt at getting help for this got missed. In looking at this, there's a few reasons why we need the current setup for the runner, so it wouldn't be a simple fix. Have you considered creating a symlink as the first step in your workflow and using that directory to do the work? I believe caching should work against that symlink and it wouldn't be affected by the runner version changing.

**Comment by maxim-lobanov** [comment]
@JosephDuffy ,
To work with symlink as Alejandro proposed, we can use the following code:
```
- name: Create symlink for current runner
  run: |
    currentAgentPath=$(dirname $(dirname $RUNNER_WORKSPACE))
    targetAgentPath="/Users/runner/runners/current"
    ln -s $currentAgentPath $targetAgentPath
```
And then, you will be able to cache path `/Users/runner/runners/current/work/<repository_name>/.build` instead of just `.build`.

Could you please try this workaround with symlink and report back if it helps?

**Comment by JosephDuffy** [comment]
I don't know how to test this using GitHub actions (since I can't trigger a runner update) but I tried to following locally:

```
mkdir Package
ln -s Package PackageLink
cd PackageLink
swift package init --name PackageLinkTest
swift build
cd ..
rm PackageLink
mv Package Package2
ln -s Package2 PackageLink
cd PackageLink
swift build
```

This produces an error due to a path change.

I think when Swift does the building it is taking the real path, not the path of the symbolic link.

So I don't think this will work on GitHub Actions.

**Comment by maxim-lobanov** [comment]
Okay, thank you for attempt.
In this case, we can try another trick: move repository outside `/Users/runner/runners/2.161.0/work`.
```
- uses: actions/checkout@v2
- run: |
    cp -r $GITHUB_WORKSPACE $HOME/repository 
```
and then try to build in `$HOME/repository`. 
Hope, it will help because in this case, the same path will be used independent of runner.

**Comment by JosephDuffy** [comment]
This is a bit of a pain because most actions assume they are running in the work directory, so files may need to be copied back and forth or more paths need to be hardcoded.

Since this is primarily an issue with caches I have added `github.workspace` to the cache key. This means caches are invalidated if runner updates, but it's simpler that juggling the work directory.

**Comment by maxim-lobanov** [comment]
@JosephDuffy , thank you for your feedback.
Unfortunately, we don't have quick solution for this issue because runner installation layout is not something that can be changed quickly and without impact.

I am closing this issue but we will keep it on mind and will post update if we have a plan to rework it in future

**Comment by maxim-lobanov** [comment]
Just an update: Issue should be fixed since runner was moved to `/Users/runner/work/{repo}/`

**Comment by Nikunjrupapara** [comment]
Can I run github actions runner on home/src path instead of runner default path ?
Basically, I want to run job on "home/src" using ubuntu runner. Suggestions would be appreciated!
Thanks.
