### ISSUE TITLE
Update Chrome and ChromeDriver to version  81.0

### ISSUE THREAD

**Issue by aaltat** [actions/virtual-environments#715]
**Tool information**
- Tool name: Chrome browser and ChromeDriver
- Please update
- Desired version: 81.0 

**Area for Triage**:
No idea what should go here.

**Virtual environments affected**
- [ ] macOS 10.15
- [x] Ubuntu 16.04 LTS
- [x] Ubuntu 18.04 LTS
- [x] Windows Server 2016 R2
- [x] Windows Server 2019

**Can this tool be installed during the build?**
In theory it could be, but at least on Ubuntu 18.04, doing `sudo apt-get upgrade google-chrome-stable -y` did run in to this:
```
Get:11 http://ppa.launchpad.net/ondrej/php/ubuntu bionic/main amd64 python3-httplib2 all 0.11.3-1+ubuntu18.04.1+deb.sury.org+1 [28.9 kB]
Fetched 54.2 MB in 4s (12.6 MB/s)
E: Failed to fetch http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu/pool/main/g/gcc-9/lib32gcc1_9.2.1-17ubuntu1~18.04.1_amd64.deb  404  Not Found [IP: 91.189.95.83 80]
E: Failed to fetch http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu/pool/main/g/gcc-9/lib32stdc++6_9.2.1-17ubuntu1~18.04.1_amd64.deb  404  Not Found [IP: 91.189.95.83 80]
E: Failed to fetch http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu/pool/main/g/gcc-9/libobjc4_9.2.1-17ubuntu1~18.04.1_amd64.deb  404  Not Found [IP: 91.189.95.83 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
##[error]Process completed with exit code 100.
```
Did not try other OS. 

**Are you willing to submit a PR?**
I could, no idea how tough.

**Comment by miketimofeev** [comment]
Hi @aaltat!
Chrome will be updated automatically the next image rollout(approx 1 week).
As a workaround you can you use these steps:
```
sudo apt-get update
sudo apt-get upgrade google-chrome-stable -y
```
Close this issue for now, but feel free to reopen if you have any concerns.
Thank you!

**Comment by aaltat** [comment]
Thank you for quick response, I did got the problem solved.
