### ISSUE TITLE
Default clang in Ubuntu 16.04 is broken

### ISSUE THREAD

**Issue by zrax** [actions/virtual-environments#72]
**Describe the bug**
Attempting to use the default clang (version 3.8) from the ubuntu-16.04 image runs into incompatibilities with the libstdc++ provided on the same image.

**Virtual environments affected**
- [ ] macOS 10.14
- [X] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Expected behavior**
The provided clang++ from Ubuntu should be able to compile code that would otherwise work on an Ubuntu 16.04 machine.

**Actual behavior**
It appears the provided libstdc++ is from GCC 7, whereas the default in Ubuntu is from GCC 5.  When using libstdc++ 7, many standard C++ headers run into errors such as:

    In file included from /usr/bin/../lib/gcc/x86_64-linux-gnu/7.4.0/../../../../include/c++/7.4.0/memory:62:
    In file included from /usr/bin/../lib/gcc/x86_64-linux-gnu/7.4.0/../../../../include/c++/7.4.0/bits/stl_algobase.h:64:
    In file included from /usr/bin/../lib/gcc/x86_64-linux-gnu/7.4.0/../../../../include/c++/7.4.0/bits/stl_pair.h:59:
    In file included from /usr/bin/../lib/gcc/x86_64-linux-gnu/7.4.0/../../../../include/c++/7.4.0/bits/move.h:54:
    /usr/bin/../lib/gcc/x86_64-linux-gnu/7.4.0/../../../../include/c++/7.4.0/type_traits:2661:5: error: 'inline' can only appear on functions
        _GLIBCXX17_INLINE constexpr bool is_swappable_v =
        ^

An example can be seen here:
https://github.com/zrax/string_theory/runs/285221827

(Note also that the Travis CI build using the same OS and compiler works successfully)

**Comment by maxim-lobanov** [comment]
Hello!
In scope of #104, we have updated clang on Ubuntu images, could you please double check if the issue is resolved?

**Comment by zrax** [comment]
It appears to remain unresolved:  https://github.com/zrax/string_theory/runs/471074583

Is there some version of clang other than the one(s) provided by apt that we should be using?

**Comment by nikita-bykov** [comment]
We made changes that should solve the issue. Ubuntu 16.04 image will be rolled out next week.

**Comment by maxim-lobanov** [comment]
Changes were deployed.
Please let me know if something doesn't work yet
