### ISSUE TITLE
Update/Add [tool name]

### ISSUE THREAD

**Issue by Mellbabe** [actions/virtual-environments#720]
**Tool information**
- Tool name: 
- Add or update? 
- Desired version: 
- Approximate size: 
- If this is an add request:
  - Brief description of tool: 
  - URL for tool's homepage: 

**Area for Triage**:

**Question, Bug, or Feature?**:

**Virtual environments affected**
- [x] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [x] Ubuntu 18.04 LTS
- [x] Windows Server 2016 R2
- [x] Windows Server 2019

**Can this tool be installed during the build?**

**Are you willing to submit a PR?**

**Comment by al-cheb** [comment]
@Mellbabe, Could you please fill the issue and provide information about tool that you want to install?

**Comment by maxim-lobanov** [comment]
Closing the issue because neigher description nor tool name was provided
