### ISSUE TITLE
Update/Add [Update]

### ISSUE THREAD

**Issue by Mellbabe** [actions/virtual-environments#727]
**Tool information**
- Tool name: 
- Add or update? 
- Desired version: 
- Approximate size: 
- If this is an add request:
  - Brief description of tool: 
  - URL for tool's homepage: 

**Area for Triage**:

**Question, Bug, or Feature?**:

**Virtual environments affected**
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Can this tool be installed during the build?**

**Are you willing to submit a PR?**

**Comment by al-cheb** [comment]
Duplicate https://github.com/actions/virtual-environments/issues/720
