### ISSUE TITLE
Add trainer

### ISSUE THREAD

**Issue by HenrikBacher** [actions/virtual-environments#729]
**Tool information**
- Tool name: trainer
- Add or update? Add
- Desired version: latest
- Approximate size: 
- If this is an add request:
  - Brief description of tool: used to convert test results from xcode test results into junit. Similar to xcpretty, however with newer features, specifically for my use case supports collection of results from parallel test execution, per this issue: https://github.com/microsoft/azure-pipelines-tasks/issues/10132
  - URL for tool's homepage: https://github.com/fastlane-community/trainer

**Area for Triage**:
Apple

**Question, Bug, or Feature?**:
Feature

**Virtual environments affected**
- [x] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Can this tool be installed during the build?**
Can be installed by the command line "gem install trainer", install time varies by download speed approximately 90 seconds, however requires sudo. Haven't tested with --user-install option

**Comment by alepauly** [comment]
@HenrikBacher this should be doable during your workflow (passwordless sudo is enabled) so we won't add it to the image at this time.
