### ISSUE TITLE
Add Ruby shared library

### ISSUE THREAD

**Issue by y-yagi** [actions/virtual-environments#73]
**Tool information**
- Tool name: Ruby shared library
- Add or update? Add
- Desired version: Latest
- Approximate size: 
- If this is an add request:
  - Brief description of tool: GitHub Actions Virtual Environments already supported Ruby but it seems it does not build with a shared library. The shared library need when use libraries like using FFI.
  - URL for tool's homepage: 

**Virtual environments affected**
- [x] macOS 10.14
- [x] Ubuntu 16.04 LTS
- [x] Ubuntu 18.04 LTS
- [x] Windows Server 2016 R2
- [x] Windows Server 2019

**Can this tool be installed during the build?**
Yes

**Are you willing to submit a PR?**
Yes

**Comment by eregon** [comment]
> The shared library need when use libraries like using FFI.

Could you give an example?
The FFI gem doesn't need `libruby` at least.

**Comment by ankane** [comment]
A few examples are [Rice](https://github.com/jasonroelofs/rice) and gems that depend on it (like [Torch-rb](https://github.com/ankane/torch-rb) and [fastText](https://github.com/ankane/fastText)). Here's the error message from Rice:

```txt
Unfortunately Rice does not build against a staticly linked Ruby.
You'll need to rebuild Ruby with --enable-shared to use this library.

If you're on rvm:    rvm reinstall [version] -- --enable-shared
If you're on rbenv:  CONFIGURE_OPTS="--enable-shared" rbenv install [version]
If you're on Heroku: upgrade your stack to heroku-16 or later
```

**Comment by maxim-lobanov** [comment]
Hello, recently we have switched Ruby to official Ruby binaries for all os. Currently, binaries are consumed from https://github.com/ruby/ruby-builder
As far as I know, new binaries use shared libraries and this issue can be resolved.
Please let me know if you have any concerns
