### ISSUE TITLE
Installed Android SDK binaries on Ubuntu are only executable by root

### ISSUE THREAD

**Issue by kentonv** [actions/virtual-environments#738]
**Describe the bug**

On `ubuntu-latest`, the binaries installed in `$ANDROID_SDK_ROOT/tools/bin` are marked executable only by root.

**Area for Triage**: Android

**Question, Bug, or Feature?**: Bug

**Virtual environments affected**
- [ ] macOS 10.15
- [x] Ubuntu 16.04 LTS
- [x] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Expected behavior**

Installed binaries should be executable by all users.

**Actual behavior**

From an actual action log:
```
▶ Run ls -l $ANDROID_SDK_ROOT/tools/bin
total 64
-rwxr--r-- 1 root root 6742 Sep 13  2017 apkanalyzer
-rwxr--r-- 1 root root 5253 Sep 13  2017 archquery
-rwxr--r-- 1 root root 6040 Sep 13  2017 avdmanager
-rwxr--r-- 1 root root 5250 Sep 13  2017 jobb
-rwxr--r-- 1 root root 6834 Sep 13  2017 lint
-rwxr--r-- 1 root root 3323 Sep 13  2017 monkeyrunner
-rwxr--r-- 1 root root 5613 Sep 13  2017 screenshot2
-rwxr--r-- 1 root root 6047 Sep 13  2017 sdkmanager
-rwxr--r-- 1 root root 3076 Sep 13  2017 uiautomatorviewer
```

And:
```
/home/runner/work/_temp/2fdf16f4-50b2-4c0d-adb3-024bbe42a1aa.sh: line 3: /usr/local/lib/android/sdk/tools/bin/avdmanager: Permission denied
```

**Comment by Darleev** [comment]
Hi @kentonv, $ANDROIDK_SDK_ROOT path is: /usr/local/lib/android/sdk. User cannot write to `/usr/bin/` folder by default. In order to elevate required permissions, it is required to use `sudo`. For example:

`sudo lint`

or by full path

`sudo $ANDROID_SDK_ROOT/tools/bin/lint`

Also, let me provide you with link, where a [similar case](https://github.com/actions/virtual-environments/issues/534) was discussed. In case of any questions, please let me know, we will be glad to assist you further.

**Comment by Darleev** [comment]
@kentonv Thank for the reported issue and the investigation. I have created [pull request](https://github.com/actions/virtual-environments/pull/747) to fix insufficient permissions for android sdk. Please let me know in case of any questions.

**Comment by Darleev** [comment]
@kentonv we have verified and merged [pull request](https://github.com/actions/virtual-environments/pull/747). All changes will be applied after next VM rollout.
In case of any questions, feel free to contact us.

**Comment by kentonv** [comment]
Thanks!

**Comment by Darleev** [comment]
@kentonv The fix still not deployed due to postponed releases last time. We are doing our best to make release sooner.
We will keep you posted.

**Comment by Darleev** [comment]
@kentonv I glad to inform you that the issue has been fixed in the current Ubuntu release.
```
-rwxr-xr-x 1 root root 5253 Sep 13  2017 archquery
-rwxr-xr-x 1 root root 6040 Sep 13  2017 avdmanager
-rwxr-xr-x 1 root root 5250 Sep 13  2017 jobb
-rwxr-xr-x 1 root root 6834 Sep 13  2017 lint
-rwxr-xr-x 1 root root 3323 Sep 13  2017 monkeyrunner
-rwxr-xr-x 1 root root 5613 Sep 13  2017 screenshot2
-rwxr-xr-x 1 root root 6047 Sep 13  2017 sdkmanager
-rwxr-xr-x 1 root root 3076 Sep 13  2017 uiautomatorviewer
```
I'm going to close the issue. In case of any questions feel free to open new ticket.
