### ISSUE TITLE
MySQL Breaking Changes

### ISSUE THREAD

**Issue by michaelhelmick** [actions/virtual-environments#739]
**Describe the bug**
Not so much a bug, but more of a clearer description on how to use software on the OS.

**Area for Triage**: 
Question

**Question, Bug, or Feature?**: 
Question

**Virtual environments affected**
- [x] Ubuntu 18.04 LTS

**Expected behavior**
mysql to work out of the box without starting

**Actual behavior**
I looked across the community for solutions (including adding `services`, updating ports, trying different hosts, and it ended up being that mysql doesn't start automatically anymore (via https://github.blog/changelog/2020-02-21-github-actions-breaking-change-ubuntu-virtual-environments-will-no-longer-start-the-mysql-service-automatically/) I think it would be appreciated if that was noted somewhere other than a blog post.

**Comment by maxim-lobanov** [comment]
Hello @michaelhelmick ,
Am I right that your proposal is about updating documentation to include information that MySQL service is not enabled by default and instructions how it can be enabled. Please correct me if I am wrong

**Comment by michaelhelmick** [comment]
Correct! The only place I could find that MySQL is no longer started by default was the blog post disconnected from documentation. Would be super helpful!

**Comment by dibir-magomedsaygitov** [comment]
Documentation has been successfully updated. Changes were merged and will be delivered to all VMs in a week.

**Comment by dibir-magomedsaygitov** [comment]
Documentation has been successfully updated. All changes are delivered to VMs. Feel free to contact if you have any issues.
