### ISSUE TITLE
Update/Add Ninja

### ISSUE THREAD

**Issue by compnerd** [actions/virtual-environments#741]
**Tool information**
- Tool name: Ninja
- Add or update? Add
- Desired version: latest
- Approximate size:
- If this is an add request:
  - Brief description of tool: `ninja` is a build tool focused on speed
  - URL for tool's homepage: https://github.com/ninja-build/ninja

**Area for Triage**:
Packages

**Question, Bug, or Feature?**:
Feature

**Virtual environments affected**
- [x] macOS 10.15
- [x] Ubuntu 16.04 LTS
- [x] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Can this tool be installed during the build?**
Yes, the install is bound by download time (usually ~1m)

**Are you willing to submit a PR?**
Yes

**Comment by compnerd** [comment]
The ninja tool is already included in the Windows hosts via Visual Studio.  It would be nice to include it on the macOS and Ubuntu VMs.  For Ubuntu, `apt-get install -y ninja-build` is sufficient.

**Comment by miketimofeev** [comment]
Hi @compnerd! As I know ninja is installed along with vcpkg, here is the vcpkg installation log:
```
    azure-arm: Downloading ninja...
==> azure-arm:   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
==> azure-arm:                                  Dload  Upload   Total   Spent    Left  Speed
==> azure-arm: 100   624  100   624    0     0   2034      0 --:--:-- --:--:-- --:--:--  2039
==> azure-arm: 100 99857  100 99857    0     0  99025      0  0:00:01  0:00:01 --:--:--  322k
    azure-arm: Downloading ninja... done.
    azure-arm: Extracting ninja...
    azure-arm: Extracting ninja... done.
```
I wonder if it could be used for your purposes?

**Comment by compnerd** [comment]
@miketimofeev interesting, `ninja` is definitely not found on the Linux builders (on Azure).  I thought that the Azure and GitHub actions were merged into a single repository.

```
CMake Error: CMake was unable to find a build program corresponding to "Ninja".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
-- Configuring incomplete, errors occurred!
See also "/home/vsts/work/1/b/.../CMakeFiles/CMakeOutput.log".
```

**Comment by miketimofeev** [comment]
@compnerd Unfortunately, I'm not so familiar with CMake builds, but is it possible to use vcpkg for them?
https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/vcpkg_configure_cmake.md

**Comment by compnerd** [comment]
@miketimofeev no, it is not possible to use `vcpkg` for building for my purposes.  I need to be able to use ninja directly through CMake as that is the only way that you can build Swift packages with CMake.  The projects only support CMake, and supporting vcpkg is not viable as adding yet another build system to projects is not likely to be acceptedf.

**Comment by compnerd** [comment]
@miketimofeev actually, thinking more about this - isn't this actually better?  Adding ninja to the base image allows CMake to use it and vcpkg could use the host provided ninja builder as well.

**Comment by miketimofeev** [comment]
Oh, I see. Can that ninja from vcpkg be used directly from `/usr/local/share/vcpkg/downloads/tools/ninja-1.10.0-linux/ninja`?
We try to avoid tools duplicating, that's why I'm trying to find any possible ways.

**Comment by compnerd** [comment]
Hardcoding random paths doesn't work very well for the azure pipelines if you are using different builders.  Can you not use `ninja` from `/usr/bin/ninja` instead of `/usr/local/share/vcpkg/downloads/tools/ninja-1.10.0-linux/ninja`?

**Comment by miketimofeev** [comment]
If this path works `/usr/local/share/vcpkg/downloads/tools/ninja-1.10.0-linux/ninja` then we can simply add a symlink

**Comment by compnerd** [comment]
Where the tool resides is not a big deal, if ninja can be added to the path for all the builders, that is perfectly acceptable (though beyond my ability to help with).

**Comment by miketimofeev** [comment]
Can you confirm that 
`sudo ln -s /usr/local/share/vcpkg/downloads/tools/ninja-1.10.0-linux/ninja /usr/local/bin/ninja` solves your task?
If yes – we'll consider making the symlink during the vcpkg installation

**Comment by compnerd** [comment]
@miketimofeev nope, that still fails.  I can verify that `sudo apt-get install ninja-build` does fix it though.

**Comment by compnerd** [comment]
@miketimofeev also can verify that `sudo ln -s /usr/local/share/vcpkg/downloads/tools/ninja-1.10.0-linux/ninja /usr/bin/ninja` fails.  Its not a PATH issue AFAICT.

**Comment by Darleev** [comment]
Hi @compnerd . We had very [similar request](https://github.com/actions/virtual-environments/issues/514) for ninja tool. Unfortunately, we can't add it at the moment. I would like to suggest you to install ninja tool in runtime using the following steps:
```
# macOS
brew install ninja

# Ubuntu
sudo apt-get install ninja-build
```
So, currently, it's easy to install ninja in runtime on demand, since installation takes about 10 seconds and there are no issues with it. 
If additional assistance or information is required, please do not hesitate to contact us.

**Comment by abique** [comment]
> Hi @compnerd . We had very [similar request](https://github.com/actions/virtual-environments/issues/514) for ninja tool. Unfortunately, we can't add it at the moment. I would like to suggest you to install ninja tool in runtime using the following steps:
> 
> ```
> # macOS
> brew install ninja
> 
> # Ubuntu
> sudo apt-get install ninja-build
> ```
> 
> So, currently, it's easy to install ninja in runtime on demand, since installation takes about 10 seconds and there are no issues with it. If additional assistance or information is required, please do not hesitate to contact us.

it is on windows that it is difficult to install ninja

**Comment by al-cheb** [comment]
> it is on windows that it is difficult to install ninja

@abique , You can use choco to install ninja tool on Windows.

```
- run: |
        choco install ninja
        Get-Command ninja.exe
```

**Comment by jpr42** [comment]
FWIW to CMake/Ninja users [get-cmake](https://github.com/marketplace/actions/get-cmake) has been amazing at work for grabbing the exact version of CMake/Ninja you want. It also implements GitHub caching 👍🏽  so you don't have to worry about sporadic network failures.

**Comment by marc-hb** [comment]
> > The ninja tool is already included in the Windows hosts via Visual Studio. 

> it is on windows that it is difficult to install ninja


I'm confused: is it available by default on Windows Server or not?

ninja just started randomly disappearing on Windows:
- https://github.com/thesofproject/sof/issues/8250

**Comment by marc-hb** [comment]
Looks like ninja was dropped from Windows image 20230918.1.

Either dropped or it's not in the PATH anymore.

**Comment by jhasse** [comment]
You can get it back on the path by adding https://github.com/marketplace/actions/enable-developer-command-prompt before calling CMake.

**Comment by marc-hb** [comment]
This `enable-developer-command-prompt` action looks great but unfortunately we use `shell: msys2 {0}` so I'm not optimistic enough to try it :-(

**Comment by marc-hb** [comment]
Gosh this really annoying:
- 20230910.1 ninja found
- 20230918.1 not found
- 20231016.1.0 ninja found
- 20231023.1.0 not found

To confuse users even more, the same run gets a mix of versions with some builds passing and others not. Who's having fun with this back and forth?


> You can use choco to install ninja tool on Windows.

BTW this worked for us, thanks! Now we just need to use it on all our branches.

**Comment by marc-hb** [comment]
> We had very https://github.com/actions/virtual-environments/issues/514 for ninja tool. Unfortunately, we can't add it at the moment.

I just pleaded for #514 to be re-opened and reconsidered:
- https://github.com/actions/runner-images/issues/514#issuecomment-1915351379

**Comment by dofuuz** [comment]
For now, using [seanmiddleditch/gha-setup-ninja](https://github.com/seanmiddleditch/gha-setup-ninja) is fast and easy way to use ninja.
```
    - uses: seanmiddleditch/gha-setup-ninja@v5
```
It takes ~1sec to setup ninja.

**Comment by marc-hb** [comment]
This looks great but security-conscious projects should not have to all perform duplicate audits of some 3rd party action for a build tool as fundamental as ninja.

**Comment by marc-hb** [comment]
> thanks for your suggestion but considering that it' easy to add Ninja to workflows on demand,...

I just asked runtime installation to be officially documented, please upvote:
- #11235 

Ever growing list of duplicates gathered at:
- https://github.com/actions/runner-images/issues/514#issuecomment-2558554588
