### ISSUE TITLE
Update/Add Wine

### ISSUE THREAD

**Issue by martmists** [actions/virtual-environments#743]
**Tool information**
- Tool name: Wine
- Add or update? Add
- Desired version: 5.0 (latest stable)
- Approximate size:
- If this is an add request:
  - Brief description of tool: Run windows executables on linux
  - URL for tool's homepage: https://www.winehq.org/

**Area for Triage**:
Packages

**Question, Bug, or Feature?**:
Feature

**Virtual environments affected**
- [x] macOS 10.15
- [x] Ubuntu 16.04 LTS
- [x] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Can this tool be installed during the build?**
Unsure.

**Are you willing to submit a PR?**
No.

**Comment by Darleev** [comment]
In order to install Wine in runtime, need to use the following steps:

```
## MacOS
brew cask install wine-stable

## Ubuntu
sudo dpkg --add-architecture i386
wget -qO - https://dl.winehq.org/wine-builds/winehq.key | sudo apt-key add -
sudo add-apt-repository ppa:cybermax-dexter/sdl2-backport
sudo apt-add-repository "deb https://dl.winehq.org/wine-builds/ubuntu $(lsb_release -cs) main"
sudo apt install --install-recommends winehq-stable
```

Installation takes about 1,5-2 minutes.

**Comment by Sv443** [comment]
https://github.com/actions/virtual-environments/issues/743#issuecomment-616349857  
This works, thank you very much, you saved my day!

**Comment by kahuang** [comment]
This stopped working within the last few days, have there been any changes to the virtual environments that could cause this?

I've narrowed down the install-chain to the following:

```
The following packages have unmet dependencies:
 wine-stable-i386:i386 : Depends: libgphoto2-6:i386 (>= 2.5.10) but it is not going to be installed
                         Depends: libxml2:i386 (>= 2.9.0) but it is not going to be installed
                         Recommends: libodbc1:i386 but it is not going to be installed
                         Recommends: libsane:i386 or
                                     libsane1:i386 but it is not going to be installed
                         Recommends: libxslt1.1:i386 but it is not going to be installed
```

**Comment by kahuang** [comment]
cc @Darleev , this was on ubuntu 18.04, started may 2nd.

**Comment by Darleev** [comment]
@kahuang @Sv443 @martmists I'm not completely sure, but It seems official wine repository is broken or something like this, since I tried to install on clean Ubuntu 18, but with no luck, I also tried to install all required libs etc, but it does not help as well.
I have found another way to install wine-5 on ubuntu, you can find it below:
```
sudo dpkg --add-architecture i386
sudo apt update
wget -qO- https://dl.winehq.org/wine-builds/winehq.key | sudo apt-key add -
sudo apt install software-properties-common
sudo apt-add-repository 'deb http://dl.winehq.org/wine-builds/ubuntu/ bionic main'
wget -qO- https://download.opensuse.org/repositories/Emulators:/Wine:/Debian/xUbuntu_18.04/Release.key | sudo apt-key add -
sudo sh -c 'echo "deb https://download.opensuse.org/repositories/Emulators:/Wine:/Debian/xUbuntu_18.04/ ./" > /etc/apt/sources.list.d/obs.list'
sudo apt update
sudo apt-get install --install-recommends winehq-stable
```
Please let us know in case of any questions, We will be glad to assist you further.

**Comment by Sv443** [comment]
I'm using your solution https://github.com/actions/virtual-environments/issues/743#issuecomment-616349857 for a GitHub Actions runner on the latest Ubuntu and haven't had any problems

**Comment by ustun** [comment]
@Darleev Would it be possible to re-open this and have Wine installed by default? 

It takes 6 minutes for us on average (about half the time of the total build time.)

**Comment by ustun** [comment]
@miketimofeev Thank you for the explanation. That's still a relief :)
