### ISSUE TITLE
Update/Add binutils-arm-none-eabi

### ISSUE THREAD

**Issue by martmists** [actions/virtual-environments#744]
**Tool information**
- Tool name: binutils-arm-none-eabi
- Add or update? Add
- Desired version: 2.25-5+5 (latest)
- Approximate size: 
- If this is an add request:
  - Brief description of tool: GNU assembler, linker and binary utilities for ARM Cortex-A/R/M processors
  - URL for tool's homepage: https://packages.debian.org/source/jessie/binutils-arm-none-eabi

**Area for Triage**:
Packages

**Question, Bug, or Feature?**:
Feature

**Virtual environments affected**
- [x] macOS 10.15
- [x] Ubuntu 16.04 LTS
- [x] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Can this tool be installed during the build?**
Unlikely.

**Are you willing to submit a PR?**
No.

**Comment by maxim-lobanov** [comment]
Tool can be installed in runtime via the following code (installation takes about 30 seconds):
```
# Ubuntu 
sudo apt-get install gcc-arm-none-eabi
# macOS
brew tap ArmMbed/homebrew-formulae
brew install arm-none-eabi-gcc
```

**Comment by alepauly** [comment]
Hi @martmists, considering that it's fairly easy to install on runtime we won't be baking this into the image at this time. Depending on popularity and interest we might reconsider later. Thanks for the suggestion.
