### ISSUE TITLE
Boost regression

### ISSUE THREAD

**Issue by pitrou** [actions/virtual-environments#749]
It seems that, following the latest environment changes, Boost cannot be found by CMake anymore on Windows Server 2019:
https://github.com/apache/arrow/pull/6991/checks?check_run_id=601773054#step:7:105
```
-- Could NOT find Boost (missing: Boost_INCLUDE_DIR regex system filesystem) (Required is at least version "1.58")
```

**Area for Triage**: 
C/C++

**Question, Bug, or Feature?**: 
Bug

**Virtual environments affected**
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [x] Windows Server 2019

**Comment by al-cheb** [comment]
Hello, @pitrou 
We have deprecated BOOST_ROOT environment variable - [#319](https://github.com/actions/virtual-environments/issues/319).  How to fix - https://github.com/actions/virtual-environments/issues/661 and https://github.com/actions/virtual-environments/issues/687

**Comment by pitrou** [comment]
@al-cheb This seems to have worked, thank you.
