### ISSUE TITLE
Update/Add bmake, thank you!

### ISSUE THREAD

**Issue by katef** [actions/virtual-environments#75]
**Tool information**
- Tool name: bmake
- Add or update? Add
- Desired version: Any version
- Approximate size: 1MB
- If this is an add request:
  - Brief description of tool: Portable package of the BSD dialect of make(1)
  - URL for tool's homepage: http://crufty.net/help/sjg/bmake.htm - it's packaged for Ubuntu though, packaged as `bmake`

**Virtual environments affected**
- [x] macOS 10.14
- [x] Ubuntu 16.04 LTS
- [x] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Can this tool be installed during the build?**
Takes less than a minute to build

**Are you willing to submit a PR?**
Yes, if it's just adding "apt-get install bmake" somewhere!

Thank you kindly

**Comment by katef** [comment]
Hey... that's not fair

**Comment by maxim-lobanov** [comment]
The tool can be installed in runtime using the following script:
```
# Ubuntu
sudo apt-get install -y bmake
# macOS
brew install bmake
```

Installation takes about 10 seconds

**Comment by alepauly** [comment]
@katef, since it looks like installing `bmake` on the run is pretty simple and fast, we won't bake it in the image. To further simplify and perhaps make it platform-ag you can create a `setup-bmake` to take care of it? Not sure what your use case is. Thanks for the suggestion and sorry it took sooo long to answer.

@maxim-lobanov thanks for looking into it as well.

**Comment by katef** [comment]
Hi,

I am installing it at runtime. That works, but I think it's a shame - because I thought the purpose of this image is to provide things developers might need for CI. I expect I'm not the only one using it!

I think you could argue the same for other various make utilities, and those do seem to be included.

Thanks for looking at it.
