### ISSUE TITLE
Clean up apt package cache

### ISSUE THREAD

**Issue by congyiwu** [actions/virtual-environments#751]
**Describe the bug**
At the end of image generation we should cleanup the apt package cache (apt-get clean). There's no use for it on deployed images.  Doing this would free up multiple GB of disk space.

**Area for Triage**: 

I couldn't find an area that matched (this is an OS-wide issue)

**Question, Bug, or Feature?**: 
Bug

**Virtual environments affected**
- [ ] macOS 10.15
- [x] Ubuntu 16.04 LTS
- [x] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Expected behavior**
I shouldn't see wasted disk space due to .deb files for packages that were already installed.
```
df -h
apt-get clean
df -h # free space should not increase greatly
```

**Actual behavior**
A description with steps to reproduce the issue. If your have a public example or repo to share,
please provide the link.

free space increases greatly

**Comment by al-cheb** [comment]
Hello, @congyiwu 
Fixed in the https://github.com/actions/virtual-environments/pull/757 PR.
