### ISSUE TITLE
Fail fast in image generation if not enough disk space for customers

### ISSUE THREAD

**Issue by congyiwu** [actions/virtual-environments#752]
**Describe the bug**
A clear and concise description of what the bug is, and why you consider it to be a bug.

If we promise X GB of free disk space for customers, we should check that there is enough space at the end of image generation, and fail fast if there isn't.

**Area for Triage**: 

There wasn't an area for general stuff

**Question, Bug, or Feature?**: 

Feature

**Virtual environments affected**
- [x] macOS 10.15
- [x] Ubuntu 16.04 LTS
- [x] Ubuntu 18.04 LTS
- [x] Windows Server 2016 R2
- [x] Windows Server 2019

**Expected behavior**
A description of what you expected to happen.

There should always be at least X GB of free space.

**Actual behavior**
A description with steps to reproduce the issue. If your have a public example or repo to share,
please provide the link.

I don't think there are any safeguards besides customer's noticing and filing a bug.

**Comment by congyiwu** [comment]
potentially also fail fast or warn really loudly if we're getting close to X GB

**Comment by miketimofeev** [comment]
@congyiwu @nikita-bykov we shouldn't forget about additional 8Gb swap file on ubuntu, which is created later during VM provision

**Comment by congyiwu** [comment]
Also if we switch to the temp disk (via a bind mount, symlink, or changing the working for to /mnt), that would obviate this issue

**Comment by nikita-bykov** [comment]
We have added validation for available disk space.
Images with changes will be rolled out around next week.

**Comment by maxim-lobanov** [comment]
Closing the issue since test works as expected on all images
