### ISSUE TITLE
regression on 20200415.3?

### ISSUE THREAD

**Issue by lechen26** [actions/virtual-environments#753]
**Describe the bug**
seems like there is a regression on ubuntu-18.04 version 20200415.3.
the PATH on that image doesnt includes the /snap/bin hence packages installed through snap couldnt be found.

**Area for Triage**: 
we are using Github action workflow using runs-on: ubuntu-latest
for some reason yesterday , although the latest images is still 20200406.2 , few workflows pulled the 20200415.3. version which included this issue of missing PATH.

**Virtual environments affected**
- [ ] Ubuntu 18.04 LTS

**Comment by Darleev** [comment]
Hi @lechen26, thank you for the reported issue. We rolled back the latest Ubuntu release, and, I guess,  the issue should not be actual at this moment. We will check the issue further on our side and prepare fix for the issue. 
I will keep you posted about status of the issue.

**Comment by dsame** [comment]
Fix provided in https://github.com/actions/virtual-environments/pull/755 and will be available for use in a week or two

**Comment by lechen26** [comment]
10x!

**Comment by maxim-lobanov** [comment]
@lechen26 , new image was deployed. Could you please check if snap works as expected?

**Comment by lechen26** [comment]
working, 10x!

**Comment by miketimofeev** [comment]
@lechen26 thanks for the update!
I'm going to close the issue, feel free to ping us if you have any concerns.
