### ISSUE TITLE
Add xmlsec1

### ISSUE THREAD

**Issue by ruslan-shuster** [actions/virtual-environments#759]
**Tool information**
- Tool name: xmlsec1
- Add
- Desired version: latest
- Approximate size: 
- If this is an add request:
  - Brief description of tool: xml cryptography library
  - URL for tool's homepage: https://linux.die.net/man/1/xmlsec1

**Area for Triage**:
Area: Scripting and command line

**Question, Bug, or Feature?**:
"Feature"

**Virtual environments affected**
- [X] macOS 10.15
- [X] Ubuntu 16.04 LTS
- [X] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Comment by maxim-lobanov** [comment]
Tool can be installed in runtime:
```
# Ubuntu; installation takes ~5 seconds
sudo apt-get install -y xmlsec1
# macOS; installation takes ~13 seconds 
brew install libxmlsec1
```

**Comment by alepauly** [comment]
hi @ruslan-shuster, considering the install is pretty quick and simple we won't bake it into the images. We've been having issues with disk space and so we are trying to prioritize only the more critical tools. Thanks for reaching out.
