### ISSUE TITLE
Add Ubuntu 14.04 Docker Environment to C/C++ CI

### ISSUE THREAD

**Issue by davwheat** [actions/virtual-environments#76]
**Tool information**
- Tool name: Ubuntu 14.04
- Add or update? Add
- Approximate size: 
- If this is an add request:
  - Brief description of tool: It's Ubuntu! 14.04 is still the recommended version for Android builds as well as many other open source projects that have existed for a long time.

**Are you willing to submit a PR?**
Of course!

**Comment by hugovk** [comment]
The README says:

> We offer Ubuntu 16.04 and Ubuntu 18.04. We do not plan to offer other Linux distributions. If you want to build using other distributions with the hosted virtual environments, we suggest you use Docker. Alternatively, you can host your own VMs and make use of self-hosted runners which will be available when GitHub Actions becomes generally available on November 13, 2019.

**Comment by thejoebourneidentity** [comment]
Hey @davwheat, are you asking us to include an additional container layer? It would be helpful if you could link to the specific one you want. This is what we cache today:

https://github.com/actions/virtual-environments/blob/master/images/linux/Ubuntu1804-README.md

> Cached container images
> node:10 (Digest: sha256:df200903ff34c07c1b9112b4fd9d1342c11eb7d99525f2b366c487f91dda8131)
> node:12 (Digest: sha256:facc1cbde6e5aa3255092b1a1417451953c80bd31ab5a4403f8bcd90b90a8407)
> buildpack-deps:stretch (Digest: sha256:dc901bbf4b34e4ca8771c0d0773e557221452f97bcf0c732de7ecda3782bdf97)
> debian:9 (Digest: sha256:ddb131307ad9c70ebf8c7962ba73c20101f68c7a511915aea3ad3b7ad47b9d20)
> debian:8 (Digest: sha256:2c9b2323299846c5298c12db373da310f8114f2941ae3f496e95270cc8ca5ebd)
> node:10-alpine (Digest: sha256:e8d05985dd93c380a83da00d676b081dad9cce148cb4ecdf26ed684fcff1449c)
> node:12-alpine (Digest: sha256:bba77d0ca8820b43af898b3c50d4e8b68dc703ebbd958319af2f21f2d3c309f5)
> alpine:3.8 (Digest: sha256:2bb501e6173d9d006e56de5bce2720eb06396803300fe1687b58a7ff32bf4c14)
> alpine:3.9 (Digest: sha256:115731bab0862031b44766733890091c17924f9b7781b79997f5f163be262178)
> alpine:3.10 (Digest: sha256:7c3773f7bcc969f03f8f653910001d99a9d324b4b9caa008846ad2c3089f5a5f)
> jekyll/builder:latest (Digest: sha256:875de39aa06300c749e26a79f39cdfa31404e4f2dbd2953cd4ebb0442bffda9e)
> alpine:3.7 (Digest: sha256:8421d9a84432575381bfabd248f1eb56f3aa21d9d7cd2511583c68c9b7511d10)
> mcr.microsoft.com/azure-pipelines/node8-typescript:latest (Digest: sha256:e52e60b9f71183969830a3664279b5d8c799b4b0ec2c25a0686f7c02f6a9669a)

**Comment by davwheat** [comment]
Yes, I think that was what I was asking!

Android is (almost) solely built on Ubuntu 14.04, so it would be amazing to have that container available.

**Comment by andy-mishechkin** [comment]
Docker images have been checked. Ubuntu 14.04 docker image is present.
I think we can close this ticket
