### ISSUE TITLE
The runner has received a shutdown signal. This can happen when the runner service is stopped, or a manually started runner is cancelled

### ISSUE THREAD

**Issue by labski42** [actions/virtual-environments#7609]
### Description

We fixed our problem with suggestions in the community / forums / here.  Thank you.

We pinned `ubuntu-20.04` instead of `ubuntu-latest` and added following to gradle.properties;
`org.gradle.workers.max=4`;

However, I was just wondering if you/Github have an ETA of when this will be fixed?  There's enough closed cases with the same error and enough descriptions of the same environmental setups given in those cases.  We would love to use `ubuntu-latest` again.  It's just another thing we have to remember to unpin should 20.04 ever get deprecated.

Thanks.

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

n/a

### Is it regression?

no

### Expected behavior

Builds should pass in 22.04/latest as they did in 20.04

### Actual behavior

Failing with the above-mentioned error message.

### Repro steps

As mentioned.

**Comment by shamil-mubarakshin** [comment]
Hello @labski42,
Could you provide more information about your issue and links to successful and unsuccessful executions?
