### ISSUE TITLE
SQL2019 Express Instance Removed from windows-latest

### ISSUE THREAD

**Issue by adam-page-st** [actions/virtual-environments#761]
**Describe the bug**
The SQL2019 local instance has been removed as of the 20200416.1 windows-latest image.

**Area for Triage**: 
Databases

**Question, Bug, or Feature?**: 
Bug

**Virtual environments affected**
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [x] Windows Server 2019
(other images not tested)

**Expected behavior**
Its not really clear to me why the service was disabled, Get-Service outputs below.
`gsv *SQL*` as of 20200331.1:
```
Status   Name               DisplayName
------   ----               -----------
Running  MSSQL$SQL2019      SQL Server (SQL2019)
Stopped  SQLAgent$SQL2019   SQL Server Agent (SQL2019)
Running  SQLBrowser         SQL Server Browser
Running  SQLTELEMETRY$SQL2… SQL Server CEIP service (SQL2019)
Running  SQLWriter          SQL Server VSS Writer
```

**Actual behavior**
`gsv *SQL*` as of 20200416.1:
```
Status   Name               DisplayName                           
------   ----               -----------                           
Running  SQLWriter          SQL Server VSS Writer   
```

We are upgrading the MSSQLLocalDB instance with every run, and having the SQL2019 Express version preinstalled saved 3-4 minutes on every build.

**Comment by al-cheb** [comment]
Hello, @adam-page-st 
We have temporary remove in the https://github.com/actions/virtual-environments/pull/707 PR due to bug with incorrect dynamic-link library search order.  We are working on the fix to resolve the issue and enable MSSQL back.

**Comment by maxim-lobanov** [comment]
Closing this issue because installation of SQL is tracked by #413. 
Please let us know if you have any concerns
