### ISSUE TITLE
Update/Add gcovr

### ISSUE THREAD

**Issue by johanneskares** [actions/virtual-environments#764]
**Tool information**
- Tool name: gcovr
- Add or update? Add
- Desired version: Latest
- Approximate size: 5.7 MB
- If this is an add request:
  - Brief description of tool: Popular Code Coverage generator
  - URL for tool's homepage: https://github.com/gcovr/gcovr

**Area for Triage**:

**Question, Bug, or Feature?**:

**Virtual environments affected**
- [x] macOS 10.15
- [x] Ubuntu 16.04 LTS
- [x] Ubuntu 18.04 LTS
- [x] Windows Server 2016 R2
- [x] Windows Server 2019

**Can this tool be installed during the build?**
pip install gcovr

**Are you willing to submit a PR?**

**Comment by alepauly** [comment]
Hi @johanneskares, we won't be able to bake this into the images at this time. Have you looked into creating an Action that simplifies install during workflows?
