### ISSUE TITLE
Add Xcode 15 beta

### ISSUE THREAD

**Issue by ForeverQ** [actions/virtual-environments#7672]
### Tool name

Xcode 15 beta

### Tool license

Apple, Inc.

### Add or update?

- [X] Add
- [ ] Update

### Desired version

Xcode 15 beta

### Approximate size

13.54 GB with iOS 17 beta and watchOS 10 beta

### Brief description of tool

Xcode IDE

### URL for tool's homepage

https://developer.apple.com/download/applications/

### Platforms where you need the tool

- [X] Azure DevOps
- [ ] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [X] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Can this tool be installed during the build?

```bash
No.
```

**Comment by mikhailkoliada** [comment]
Added to the image

**Comment by MarkParker5** [comment]
Hi. I am using `runs-on: macos-13` but `sudo xcode-select -s '/Applications/Xcode_15_beta.app/Contents/Developer'` returns `xcode-select: error: invalid developer directory '/Applications/Xcode_15_beta.app/Contents/Developer'`. 

Am I using the wrong image or path? Or the xcode 15 hasn't been added yet?

**Comment by alicerunsonfedora** [comment]
I believe the images have been built, but not deployed yet...

**Comment by caoimhebyrne** [comment]
Hopefully they deploy it soon, my CI requires it

**Comment by ilia-shipitsin** [comment]
please try "Xcode_15.0.app"


```
Run ls /Applications/
Firefox.app
Google Chrome.app
Julia-1.9.app
Microsoft Edge.app
PowerShell.app
Python 3.11
Safari.app
Utilities
Visual Studio.app
Xcode.app
Xcode_1[4](https://github.com/ilia-shipitsin/xcode-list/actions/runs/5311699091/jobs/9615253077#step:3:5).1.0.app
Xcode_14.1.app
Xcode_14.2.0.app
Xcode_14.2.app
Xcode_14.3.0.app
Xcode_14.3.1.app
Xcode_14.3.app
Xcode_15.0.0.app
Xcode_15.0.app
```

**Comment by ilia-shipitsin** [comment]
btw, it was deployed.

**Comment by caoimhebyrne** [comment]
Was it? Do I have to enable it? Using `macos-latest` as my runner btw.
<img width="770" alt="image" src="https://github.com/actions/runner-images/assets/71222289/ee88213f-eb49-484c-a7d3-e57154a64109">

**Comment by caoimhebyrne** [comment]
```
ls /Applications
Firefox.app
Google Chrome.app
Julia-1.9.app
Microsoft Edge.app
PowerShell.app
Python 2.7
Python 3.11
Safari.app
Utilities
VirtualBox.app
Visual Studio 2019.app
Visual Studio.app
Xcode.app
Xcode_13.1.0.app
Xcode_13.1.app
Xcode_13.2.1.app
Xcode_13.2.app
Xcode_13.3.1.app
Xcode_13.3.app
Xcode_13.4.1.app
Xcode_13.4.app
Xcode_14.0.1.app
Xcode_14.0.app
Xcode_14.1.0.app
Xcode_14.1.app
Xcode_14.2.0.app
Xcode_14.2.app
```

**Comment by caoimhebyrne** [comment]
Looks like you need to use `macos-13`, not `macos-latest`.

**Comment by ilia-shipitsin** [comment]
> Looks like you need to use `macos-13`, not `macos-latest`.

Indeed :)

**Comment by NullIsOne** [comment]
Hey guys. 
I'm also need Xcode 15.0 Beta for my project and already tried new runner image setting
`env:
  DEVELOPER_DIR: /Applications/Xcode_15.0.app/Contents/Developer`
, but got next issue
>{ platform:iOS, id:dvtdevice-DVTiPhonePlaceholder-iphoneos:placeholder, name:Any iOS Device, error:iOS 17.0 is not installed. To use with Xcode, first download and install the platform }
Should I set some other environment or I  need just wait for final deployment of new runner?

**Comment by caoimhebyrne** [comment]
The default download for Xcode 15 only includes the macOS SDK, everything else is optional, that may be why.

**Comment by davdroman** [comment]
@shamil-mubarakshin @mikhailkoliada this condition is preventing the additional runtimes from being downloaded for Xcode 15 https://github.com/actions/runner-images/blob/a9bb38099f8f6faf14576a8386d34065835b42ba/images/macos/helpers/Xcode.Installer.psm1#LL169C5-L172C6

**Comment by mikhailkoliada** [comment]
@davdroman please file the spare issue so things are not getting confused
