### ISSUE TITLE
macOS jobs never starts for me

### ISSUE THREAD

**Issue by tonymorony** [actions/virtual-environments#77]
**Describe the bug**

Trying Github actions for a first time: https://github.com/tonymorony/komodo/actions
https://github.com/tonymorony/komodo/blob/github-actions-plays/.github/workflows/komodod_ci.yml
 
For MacOS worker at first getting `Starting your workflow run...` message, then when other jobs finishing MacOS job state screen changing to "This check was neutral"
Windows and Ubuntu jobs working like a charm

**Virtual environments affected**
- [x] macOS 10.14
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Expected behavior**
Perform macOS part of job workflow

**Actual behavior**
macOS jobs never performing 

1. Triggering the job
2. Waiting...

**Comment by hugovk** [comment]
This happened for me around the same time: some macOS jobs completed, some never started, one just said "neutral".

But I re-pushed the commit and they built fine now. I guess it was just a temporary thing.

**Comment by tonymorony** [comment]
Yeah, looks like today jobs starts sometimes. Hope it'll be improved when product go out of beta or at least some paid options will be added for guaranteed job start.

**Comment by whyoleg** [comment]
The same Issue now also present
here: https://github.com/whyoleg/ktd/runs/305110181 (generate jni step)
and also one time some strange things happens here https://github.com/whyoleg/ktd/runs/304433929
```
Fri, 15 Nov 2019 09:26:49 GMT Commit for version 1.5.0: e2734d4fb6815da5f357da4731d3013f64410e6b
Fri, 15 Nov 2019 10:03:17 GMT tdlib commit: e2734d4fb6815da5f357da4731d3013f64410e6b
```
Here, it's just 2 println one after another
