### ISSUE TITLE
Add XQuartz to macOS default machine

### ISSUE THREAD

**Issue by p-smirnov** [actions/virtual-environments#771]
**Tool information**
- Tool name: XQuartz
- Add or update? Add
- Desired version: Latest
- Approximate size: 76 MB
- If this is an add request:
  - An X11 server is no longer standard for macOS, however some open source libraries cross-compiling onto the system require it to be installed. Having it there by default would be great. 
  - URL for tool's homepage: https://www.xquartz.org

**Area for Triage**: Apple

**Question, Bug, or Feature?**: Feature

**Virtual environments affected**
- [x ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Can this tool be installed during the build?**
Yes, takes about 2 minutes with download from the website. Following commands used:

```- name: Install XQuartz
        if: runner.os == 'macOS'
        run: |
          wget https://dl.bintray.com/xquartz/downloads/XQuartz-2.7.11.dmg
          sudo hdiutil attach XQuartz-2.7.11.dmg
          sudo installer -package /Volumes/XQuartz-2.7.11/XQuartz.pkg -target / 
```

**Are you willing to submit a PR?**
Once I understand how GitHub Actions work, maybe!

**Comment by alepauly** [comment]
@p-smirnov can you help us understand what kind of workflows would benefit from having this built into the image?

**Comment by p-smirnov** [comment]
Sure! 
I am using Github Actions to test R package development across platform. Some existing libraries in R, which are unfortunately quite common dependencies, rely on TCL/TK libraries to build. On macOS, this creates a dependency on X11.

I am not 100% sure, but I think a similar situation could happen with scientific package development in other languages, such as Python or Julia.

**Comment by alepauly** [comment]
thanks for the info @p-smirnov, considering some compat concerns and other work we have to prioritize right now we won't be able to preinstall it at this time. Please reopen if this becomes a blocker or you want to discuss further.

**Comment by cooljeanius** [comment]
> thanks for the info [@p-smirnov](https://github.com/p-smirnov), considering some compat concerns and other work we have to prioritize right now we won't be able to preinstall it at this time. Please reopen if this becomes a blocker or you want to discuss further.

I personally would find this really useful; please consider reopening, or at least point me to another action someone's already written that I can include from my own workflow to simplify things 

(Edit, yes, I guess I could just copy and paste the lines mentioned as an alternative in the OP, but those contain a hardcoded version number, and I don't want to be responsible for keeping that updated)
