### ISSUE TITLE
macOS source

### ISSUE THREAD

**Issue by olafure** [actions/virtual-environments#774]
I know it's already planned to add the source for the macOS env.

From the README.md:
> We are in the process of preparing our macOS source to live in this repo so we can take contributions from the community. Until then, we appreciate your patience and ask you continue to make tool requests by filing issues.

I just wanted to create this issue to track it and so people can follow it and get notified when it's there.

**Comment by maxim-lobanov** [comment]
@olafure , thank you for creating it.

Unfortunately, we can't provide any ETA for now because there are a bunch of internal problems that we have to solve before macOS source code is open sourced.
We are working on it and we are happy to see your interest in it.

**Comment by maxim-lobanov** [comment]
Hello everyone!

We have published source code of MacOS image generation and you can find it under https://github.com/actions/virtual-environments/tree/main/images/macos

Unfortunately, our validation CI doesn't support external contributions. So we can't accept contributions but it should be resolved very soon.

**Comment by tobylane** [comment]
The [Azure Pipelines folder](https://github.com/microsoft/azure-pipelines-image-generation/tree/master/images/macos) for this information points to this repository. Will the older macOS versions have their own readmes too?

**Comment by miketimofeev** [comment]
@tobylane we're not going to migrate azure-pipelines readmes to this repo at the moment. They will be updated in the https://github.com/microsoft/azure-pipelines-image-generation/tree/master/images/macos folder as previous
