### ISSUE TITLE
Update/Add XCode 10.x

### ISSUE THREAD

**Issue by jherico** [actions/virtual-environments#78]
**Tool information**
- Tool name: XCode 
- Add or update? Add
- Desired version: 10.3
- Approximate size: 
- If this is an add request:
  - Brief description of tool: default mac development environment
  - URL for tool's homepage: 

**Virtual environments affected**
- [X] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Can this tool be installed during the build?**
No

**Are you willing to submit a PR?**
No

The recent update of the macos build environment to 10.15 also seems to have removed all XCode versions < 11.  However, I'm currently working with a Qt application that crashes deep inside the Qt OpenGL code when built with XCode 11, but not with XCode 10.  See this forum report https://forum.qt.io/topic/107531/qt-qglwidget-and-xcode-11-fail/8  and this bug report https://bugreports.qt.io/browse/QTBUG-79315

Removing both XCode 9 and 10 seems needlessly restrictive and is breaking my build while I'm trying to sell my company on the viability of moving to Github Actions.

**Comment by Techcadia** [comment]
I would have expected to be able to pin my runs-on MacOS-Latest back to MacOS-10.14 to access 10.x Xcode. But this does not seem to be the case either.

Kind of disappointing since we have everything from Xcode 9 to Xcode 11 in our platform.

https://gist.github.com/fabianfett/fd811d7921eb856bb100c5c15565077f dump from a bit ago showing they used to exist.

Current dump from today.
```
Run ls -n /Applications/ | grep Xcode*
lrwxr-xr-x  1 0    80   28 Nov  2 09:18 Xcode.app -> /Applications/Xcode_11.1.app
drwxr-xr-x  3 501  20   96 Sep 21 02:01 Xcode_11.1.app
lrwxr-xr-x  1 501  80   28 Nov  2 08:42 Xcode_11.1_beta.app -> /Applications/Xcode_11.1.app
drwxr-xr-x  3 501  20   96 Oct 23 11:29 Xcode_11.2.app
lrwxr-xr-x  1 501  80   28 Nov  2 09:01 Xcode_11.2_beta.app -> /Applications/Xcode_11.2.app
drwxr-xr-x  3 501  20   96 Sep 11 11:50 Xcode_11.app
lrwxr-xr-x  1 501  80   26 Nov  2 08:22 Xcode_11_beta.app -> /Applications/Xcode_11.app

**Comment by ikesyo** [comment]
The removal of Xcode 9.x and 10.x is also problematic for Swift OSS projects which supports multiple Xcode and Swift versions aiming backward compatibility.

**Comment by norio-nomura** [comment]
I thought that at least one previous generation version would remain, and I didn't expect the old version to be abruptly deleted without prior notice.
I'm wondering if there will be operations in the future, or only during the beta period, where setting `runs-on: macOS-10.14` can be meaningless. 🤔

**Comment by ppaulweber** [comment]
I would be very happy myself, if Xcode 10.x could be present in the `macOS-10.15` or in the former `macOS-10.14` OS base image, see: https://github.community/t5/GitHub-Actions/GitHub-Actions-base-image-macOS-10-14-is-missing-Xcode-10-tools/m-p/37305#M2897

**Comment by Techcadia** [comment]
```
Thank you for being a part of the GitHub Actions beta program and trying out our macOS virtual environments. This week we completed migrating the macOS virtual environment to Catalina. This means all macOS jobs, including any that use the line `runs-on: macOS-10.14`, are running on Catalina (v10.15). On December 3rd, any workflows with jobs that still include the line `runs-on: macOS-10.14` will fail to run and return a failed check suite. 
```

Just to keep everyone here in the loop if you didn't get one of these emails.

**Comment by yueno12** [comment]
+1

**Comment by jshier** [comment]
This is still an issue, and as @ikesyo pointed out, a major issue for OSS Swift projects which need to test against multiple Swift compilers. Given the resources available to GitHub I fail to see how supporting additional versions of Xcode in an image would be a burden. Given that Travis and GitHub Actions macOS runners ultimately run through the same service (MacStadium), it seems obvious this is an arbitrary restriction on a service for which GitHub already charges 10x the other platforms.

**Comment by coder3101** [comment]
+1. If not macOS 10.14, atleast add old Xcode version!

**Comment by nikita-bykov** [comment]
We have added Xcode 10.3 to macOS 10.15.
Images with it will be rolled out around next week.

**Comment by miketimofeev** [comment]
@jherico Xcode 10.3 is now available on the image. Could you check it, please?

**Comment by jherico** [comment]
In the months since I filed this bug, I've been laid off 
![image](https://user-images.githubusercontent.com/1533642/80748437-c708cb00-8ad9-11ea-8f51-175f3bc35e9e.png)

...from the job where I was working on supporting desktop software on out of date MacOS versions and started a new Job in backend development where that sweet sweet container magic ensures I'm always working in a reliable environment with exactly the development environment I want.  

So, not a lot of free time or motivation to do anything with this.  

![image](https://user-images.githubusercontent.com/1533642/80748402-b6585500-8ad9-11ea-864c-3051b7471e3d.png)

Perhaps one of the others that was clamoring for this can assist.

**Comment by miketimofeev** [comment]
Close the issue in that case. If anyone has concerns, please open a new issue.
Thank you!
