### ISSUE TITLE
Add yq

### ISSUE THREAD

**Issue by tamalsaha** [actions/virtual-environments#781]
**Tool information**
- Tool name: yq
- Add or update? Add
- Desired version: latest
- Approximate size: 6 MB
- If this is an add request:
  - Brief description of tool: yq is a portable command-line YAML processor (like jq but for YAML)
  - URL for tool's homepage:  https://github.com/mikefarah/yq

**Area for Triage**:
Containers

**Question, Bug, or Feature?**:
Feature

**Virtual environments affected**
- [x] macOS 10.15
- [x] Ubuntu 16.04 LTS
- [x] Ubuntu 18.04 LTS
- [x] Windows Server 2016 R2
- [x] Windows Server 2019

**Can this tool be installed during the build?**
Currently I can `curl | bash` it.

**Are you willing to submit a PR?**
May be

**Comment by alepauly** [comment]
I think this should be implemented as an Action instead of baking into the image. See #365 and #473. Thanks for suggesting @tamalsaha
