### ISSUE TITLE
[Minor] Found a typo

### ISSUE THREAD

**Issue by alexrosenfeld10** [actions/virtual-environments#782]
**Describe the bug**
Was reading through the readme for virtual environment support and found a small typo. Relevant for folks using `kubectl`.

**Area for Triage**: 
https://github.com/actions/virtual-environments/blame/ubuntu18/20200406.2/images/linux/Ubuntu1804-README.md#L159

**Question, Bug, or Feature?**: 
Bug

**Comment by vsafonkin** [comment]
Pull request with fix: #799
