### ISSUE TITLE
Running a Linux self-hosted agent in Docker

### ISSUE THREAD

**Issue by nreddipalle** [actions/virtual-environments#783]
**Describe the bug**
This is more of a question/request. Anyone able to successfully build a docker image using the script file https://github.com/actions/virtual-environments/blob/master/images/linux/ubuntu1804.json setting up as dockerfile as reference and try to build an image..

**Area for Triage**: 

**Question, Bug, or Feature?**: 
Question

**Virtual environments affected**
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [x] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Expected behavior**
Build an image successfully using the https://github.com/actions/virtual-environments/blob/master/images/linux/ubuntu1804.json as reference

**Actual behavior**
Failing at various shell scripts..

1. Step 1
2. Step 2

**Comment by alepauly** [comment]
Hi @nreddipalle, you might be interested in this: https://github.com/actions/virtual-environments/issues/196. This has been tried in the past with mixed results.

**Comment by nreddipalle** [comment]
Thanks @alepauly . I will take a look.

**Comment by miketimofeev** [comment]
Closing as duplicate of https://github.com/actions/virtual-environments/issues/666
