### ISSUE TITLE
Microsoft hosted agent shows ProcessTelemetry window preventing UI tests to work correctly

### ISSUE THREAD

**Issue by nehsharmMS** [actions/virtual-environments#788]
Microsoft hosted agent shows ProcessTelemetry window preventing UI tests to work correctly

**Question, Bug, or Feature?**: Bug

**Virtual environments affected**
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [x] Windows Server 2019

**Expected behavior**
Note : Creating this issue on customer's behalf. Refer  [Dev Community Issue].(https://developercommunity.visualstudio.com/content/problem/993590/microsoft-hosted-agent-shows-processtelemetry-wind.html)

###Copying the issue description#######

UI tests (WPF - .NET Core 3.1) are failing intermittently due to a button that cannot be found. I am saving a screenshot as part of each test that fails, and you can clearly see a ProcessTelemetry.exe console on top blocking most of the UI, with the message "Start collecting data!".

It is basically the same window and sort of issue as in here:

https://github.community/t5/GitHub-Actions/ProcessTelemetry-exe-console-window-visibility/td-p/41478

I do not recognize that window at all, have not changed any NuGet package and do not see it when running the UI tests locally, so everything suggests that this is an issue specific to the agents, not the code itself.

**Actual behavior**
Customer provided public repo with Issue reproduced  :  [Pipeline Link](https://dev.azure.com/fernandreu-public/ProcessTelemetry/_build?definitionId=9&_a=summary)

Config :
Pool:  windows-2019
Current agent version: '2.166.4'
Current image version: '20200416.1'

To debug the issue, I created two more public projects : 

- With Issue : [Pipeline Link](https://clttestsu0.visualstudio.com/Debug-Test/_build?definitionId=339&_a=summary)

Config :
Pool:  windows-2019
Current agent version: '2.166.4'
Current image version: '20200426.1'

- Without Issue : [Pipeline Link]( https://dev.azure.com/nehsharm/TestEnv/_build?definitionId=41&_a=summary)

Config :
Pool:  windows-2019
Current agent version: '2.166.3'
Current image version: '20200416.1'

As per my investigation, **the problem is with agent version: '2.166.4'**. Also, I asked customer to set environment variable DOTNET_CLI_TELEMETRY_OPTOUT to opt out of telemetry to mitigate the issue but seems not working.

**Comment by alepauly** [comment]
Hi @nehsharmMS, from what we can tell this is not a recent regression, but regardless I don't think we can make guarantees of certain UI interactions during the jobs that run on the hosted agents so there's really nothing to fix sustainably here. I think in this case the best would be for the tests to be resilient to the environment, meaning they should either minimize all existing Windows or be able to identify their Windows and bring them to the forefront.

**Comment by barrett777** [comment]
It's a bit frustrating to me that the docs lead me to believe Microsoft hosted agents are ready for UI tests, yet this issue is dismissed so quickly

https://docs.microsoft.com/en-us/azure/devops/pipelines/test/ui-testing-considerations?view=azure-devops&tabs=mstest

For myself who is somewhat new to Azure devops, it took me several hours to get screenshots of the UI tests so I could finally figure out why some of my UI tests were failing.  Perhaps you could update the linked doc and point out that users will need to manage window focus themselves as there are system windows that may be popping up
