### ISSUE TITLE
Build system info in the log

### ISSUE THREAD

**Issue by hugovk** [actions/virtual-environments#79]
**Tool information**
- Tool name: Information
- Add or update? Add
- Desired version: All the versions
- Approximate size: A few bytes per log

**Virtual environments affected**
- [x] macOS 10.15
- [x] Ubuntu 16.04 LTS
- [x] Ubuntu 18.04 LTS
- [x] Windows Server 2016 R2
- [x] Windows Server 2019

**Are you willing to submit a PR?**
Yes, given pointers.

Please could you could output the OS version along with other pertinent tools and version numbers at the start of each run?

This can really help debug problems when things are upgraded in the image. For example, Travis CI begins builds with "Build system information":

![image](https://user-images.githubusercontent.com/1324225/68320106-0aa0f000-00c8-11ea-834d-d02d84af3734.png)

For example, see https://github.com/actions/virtual-environments/issues/53#issuecomment-550405295 for confusion caused by not knowing what is running. 

Thank you!

**Comment by hugovk** [comment]
See also https://github.com/actions/virtual-environments/issues/81#issuecomment-562761489 for more confusion about what is running.

**Comment by hugovk** [comment]
In the meantime, I added a DIY version (https://github.com/python-pillow/Pillow/pull/4262) to our builds, which was useful in finding out why PyPy3 builds are now failing (`python` runs CPython 2 instead, https://github.com/actions/setup-python/issues/54).

**Comment by maxim-lobanov** [comment]
Hi @hugovk , the information which are printed to build log is determined by runner, not the image itself.
Could you please try to log the issue in https://github.com/actions/runner repository

**Comment by maxim-lobanov** [comment]
Closing this issue, feel free to reopen if needs

**Comment by hugovk** [comment]
Thanks, requested at https://github.com/actions/runner/issues/346.
