### ISSUE TITLE
Is the backup of /etc/environment to /etc/environmente deliberate?

### ISSUE THREAD

**Issue by rbellamy** [actions/virtual-environments#790]
**Describe the bug**
Within `etc-environment.sh` there is the following `sed` command:
https://github.com/actions/virtual-environments/blob/master/images/linux/scripts/helpers/etc-environment.sh#L29

```shell script
sudo sed -ie "s%^${variable_name}=.*$%${variable_name}=\"${variable_value}\"%" /etc/environment
```

The `-ie` has the effect of backing up the file with an `e` suffix. Was this deliberate?

```shell script
root@897f04685dc1:/# ls /etc/environment*
/etc/environment  /etc/environmente
root@897f04685dc1:/# diff /etc/environment /etc/environmente
1c1
< PATH="/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:/snap/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games"
---
> PATH="/snap/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games"
```

**Area for Triage**: 
Deployments/Release

**Question, Bug, or Feature?**: 
Question

**Virtual environments affected**
- [ ] macOS 10.15
- [x] Ubuntu 16.04 LTS
- [x] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Expected behavior**
Either `.bak` or no suffix.

**Actual behavior**
Unexpected file in `/etc`.

**Comment by dsame** [comment]
@rbellamy Thanks for your note, the fix is applied in the PR https://github.com/actions/virtual-environments/pull/792 and will be deployed in a week or two

**Comment by dsame** [comment]
The fix deployed to the production
