### ISSUE TITLE
Add Qt for Windows environments

### ISSUE THREAD

**Issue by dagheyman** [actions/virtual-environments#8]
**Tool information**
- Tool name: Qt
- Add or update? Add
- Desired version: Latest stable
- Approximate size: 
- If this is an add request:
  - Brief description of tool: Qt, cross platform UI framework
  - URL for tool's homepage: https://www.qt.io/

**Virtual environments affected**
- [ ] macOS 10.14
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [x] Windows Server 2016 R2
- [X] Windows Server 2019

**Can this tool be installed during the build?**
It can be, but it's not trivial. There is some discussions going on in the feature request thread on the community site: https://github.community/t5/GitHub-Actions/Feature-request-Pre-installed-Qt-on-Windows/m-p/31004#M680

**Comment by kaylangan** [comment]
Thanks for the suggestion! I'm going to also check the Windows Server 2016 box because I think people would likely want to have it on both Windows virtual environments. I can't give an ETA, but this is definitely on our list of software to add.

**Comment by traversaro** [comment]
It would be great if the Qt version was the one installed via vcpkg, so that if you then need to manually install vcpkg dependencies that depend on qt, you would not need to also compile qt for vcpkg (that takes an incredible amount of time).

**Comment by Shatur95** [comment]
It would be nice to see Qt on Linux machines too

**Comment by simonsan** [comment]
Qt is imho a dealbreaker for me. 
- downloading is not really possible due to the size
- building with vcpkg is not really possible due to the time it takes

In the meantime you could use aqtinstall though. Hope Qt gets added asap.

**Comment by thiagomacieira** [comment]
Ditto here, I can't transition until there's Qt available. Building it on the image is not possible and it's too big for cache too.

I recommend installing like AppVeyor does. That is, install each the latest in each of the LTS versions plus the current stable:
* `C:\Qt\5.6.3` (junction at `C:\Qt\5.6`), or maybe not since this LTS is going EOL soon
* `C:\Qt\5.9.8` (junction at `C:\Qt\5.9`)
* `C:\Qt\5.12.6` (junction at `C:\Qt\5.12`)
* `C:\Qt\5.13.2` (junction at `C:\Qt\5`) (in a couple of weeks' time, that will be 5.14.0)

**Comment by LorenzE** [comment]
fyi: there is also an action available (based on acqtinstall) https://github.com/jurplel/install-qt-action

**Comment by simonsan** [comment]
Now that there is a general Qt Account required to download and install, it would be pretty lovely to preinstall it to spare people the hussle installing it manually during their CI-builds and use their cache for it.

https://www.qt.io/blog/qt-offering-changes-2020

**Comment by alepauly** [comment]
@dagheyman thanks for suggesting this, sorry it's taken so long to respond. We're adding this to our backlog but will track it with #245 so I'll close this one as a duplicate for now since that one encompasses all platforms.
