### ISSUE TITLE
Error compiling a Python dependency package

### ISSUE THREAD

**Issue by julian-lamoso** [actions/virtual-environments#803]
**Describe the bug**
Since Monday 27/04/2020 i am experimenting an error when installing a Python dependency during my CI workflow. The command 'pip install tesserocr==2.5.1' downloads the package properly, but then it is not able to install it. There is an error compiling the python binding of the C++ package. The package was successfully installed several times before, using the same configuration, but since that day is not working any more. Locally, I am able to install the package in a docker image with same configuration as the workflow. Has there been any change on the environments? Please find the error traceback:

> 2020-04-28T14:43:33.6277863Z     Running setup.py install for pyrsistent: started
> 2020-04-28T14:43:34.8795632Z     Running setup.py install for pyrsistent: finished with status 'done'
> 2020-04-28T14:43:35.3775443Z     Running setup.py install for tesserocr: started
> 2020-04-28T14:43:40.7383300Z     Running setup.py install for tesserocr: finished with status 'error'
> 2020-04-28T14:43:40.7384878Z     ERROR: Command errored out with exit status 1:
> 2020-04-28T14:43:40.7386240Z      command: /opt/hostedtoolcache/Python/3.6.10/x64/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-s6ivqbgd/tesserocr/setup.py'"'"'; __file__='"'"'/tmp/pip-install-s6ivqbgd/tesserocr/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-8gypzhf8/install-record.txt --single-version-externally-managed --compile --install-headers /opt/hostedtoolcache/Python/3.6.10/x64/include/python3.6m/tesserocr
> 2020-04-28T14:43:40.7386943Z          cwd: /tmp/pip-install-s6ivqbgd/tesserocr/
> 2020-04-28T14:43:40.7387537Z     Complete output (17 lines):
> 2020-04-28T14:43:40.7388074Z     Supporting tesseract v4.1.1-rc2-21-gf4ef
> 2020-04-28T14:43:40.7388783Z     Configs from pkg-config: {'library_dirs': [], 'include_dirs': ['/usr/include', '/usr/include'], 'libraries': ['tesseract', 'archive', 'lept'], 'cython_compile_time_env': {'TESSERACT_VERSION': 67174656}}
> 2020-04-28T14:43:40.7389189Z     running install
> 2020-04-28T14:43:40.7389465Z     running build
> 2020-04-28T14:43:40.7389739Z     running build_ext
> 2020-04-28T14:43:40.7390251Z     building 'tesserocr' extension
> 2020-04-28T14:43:40.7390564Z     creating build
> 2020-04-28T14:43:40.7391043Z     creating build/temp.linux-x86_64-3.6
> 2020-04-28T14:43:40.7392075Z     gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/usr/include -I/usr/include -I/opt/hostedtoolcache/Python/3.6.10/x64/include/python3.6m -c tesserocr.cpp -o build/temp.linux-x86_64-3.6/tesserocr.o -std=c++11 -DUSE_STD_NAMESPACE
> 2020-04-28T14:43:40.7393594Z     tesserocr.cpp: In function â€˜int __pyx_f_9tesserocr_13PyTessBaseAPI__init_api(__pyx_obj_9tesserocr_PyTessBaseAPI*, __pyx_t_9tesseract_cchar_t*, __pyx_t_9tesseract_cchar_t*, tesseract::OcrEngineMode, char**, int, const GenericVector<STRING>*, const GenericVector<STRING>*, bool, tesseract::PageSegMode)â€™:
> 2020-04-28T14:43:40.7394330Z     tesserocr.cpp:19759:20: error: redeclaration of â€˜PyGILState_STATE __pyx_gilstate_saveâ€™
> 2020-04-28T14:43:40.7394686Z        PyGILState_STATE __pyx_gilstate_save = __Pyx_PyGILState_Ensure();
> 2020-04-28T14:43:40.7395009Z                         ^
> 2020-04-28T14:43:40.7395574Z     tesserocr.cpp:19756:20: note: â€˜PyGILState_STATE __pyx_gilstate_saveâ€™ previously declared here
> 2020-04-28T14:43:40.7395936Z        PyGILState_STATE __pyx_gilstate_save;
> 2020-04-28T14:43:40.7396269Z                         ^
> 2020-04-28T14:43:40.7396786Z     error: command 'gcc' failed with exit status 1
> 2020-04-28T14:43:40.7397273Z     ----------------------------------------
> 2020-04-28T14:43:40.8754469Z ERROR: Command errored out with exit status 1: /opt/hostedtoolcache/Python/3.6.10/x64/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-s6ivqbgd/tesserocr/setup.py'"'"'; __file__='"'"'/tmp/pip-install-s6ivqbgd/tesserocr/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-8gypzhf8/install-record.txt --single-version-externally-managed --compile --install-headers /opt/hostedtoolcache/Python/3.6.10/x64/include/python3.6m/tesserocr Check the logs for full command output.
> 2020-04-28T14:43:40.9942228Z ##[error]Process completed with exit code 1.
> 2020-04-28T14:43:40.9965692Z Cleaning up orphan processes

**Area for Triage**: 
Package, C++

**Question, Bug, or Feature?**: 
Bug

**Virtual environments affected**
- [ ] macOS 10.15
- [x] Ubuntu 16.04 LTS
- [x] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Expected behavior**
The environment should be able to compile the dependency package in order to install it

**Actual behavior**
Setting python version to 3.6:
`- name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tesserocr==2.5.1`

**Comment by vmapetr** [comment]
Hi @julian-lamoso! Thank you for reporting the issue. Could you please provide image version of successful build, so we're can track changes in dependencies?

**Comment by fgsalomon** [comment]
> Hi @julian-lamoso! Thank you for reporting the issue. Could you please provide image version of successful build, so we're can track changes in dependencies?

Hi, @julian-lamoso and me are on the same organization.

The last successful build whas with this image:
```
Current runner version: '2.169.1'
Operating System
  Ubuntu
  18.04.4
  LTS
Virtual Environment
  Environment: ubuntu-18.04
  Version: 20200406.2
  Included Software: https://github.com/actions/virtual-environments/blob/ubuntu18/20200406.2/images/linux/Ubuntu1804-README.md
```

**Comment by vmapetr** [comment]
Hi @fgsalomon! Strangely, this is the same version that we use currently.
According to the [tesserocr 2.5.1](https://pypi.org/project/tesserocr/) requirements Cython is also required. 
Could you please check following workaround:
```
          sudo apt-get install tesseract-ocr libtesseract-dev libleptonica-dev pkg-config -y
          python -m pip install --upgrade pip
          pip install Cython
          pip install tesserocr
```

**Comment by julian-lamoso** [comment]
By adding 'pip install Cython' it worked! Thanks a lot @vmapetr  :)
How is it possible that worked just a few days ago? Was Cython installed by default?

**Comment by vmapetr** [comment]
Glad I could help! Cython wasn't installed previously and we didn't deployed Ubuntu images more than a week. Could you please provide image version for failed builds, so we could compare it with successful?

**Comment by AlenaSviridenko** [comment]
I am closing this issue, since problem seems to be resolved.
Please, feel free to file the new ticket, if anything new comes up. Thanks!
