### ISSUE TITLE
Update Windows config for error reporting

### ISSUE THREAD

**Issue by vtbassmatt** [actions/virtual-environments#804]
[Original request](https://developercommunity.visualstudio.com/idea/1012461/hosted-build-agents-have-error-reporting-set-to-re.html)

When something crashes on a hosted Windows agent, Windows hangs waiting for consent to send telemetry. Consider either disable error reporting, or offer a way to auto-consent.

**Area for Triage**:

**Question, Bug, or Feature?**:
Feature

**Virtual environments affected**
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [X] Windows Server 2016 R2
- [X] Windows Server 2019

**Comment by vtbassmatt** [comment]
@jessehouwing

**Comment by jessehouwing** [comment]
I consider it a bug ;).

**Comment by alepauly** [comment]
closing in lieu of #806 thanks @vtbassmatt and @jessehouwing !
