### ISSUE TITLE
Hosted build agents have Error Reporting set to require consent

### ISSUE THREAD

**Issue by alepauly** [actions/virtual-environments#806]
originally reported here: https://developercommunity.visualstudio.com/idea/1012461/hosted-build-agents-have-error-reporting-set-to-re.html

**Describe the bug**
I had a process crash in the build, causing the build to hang.
![image](https://user-images.githubusercontent.com/6873951/80640810-f532d000-8a31-11ea-988e-d1adc95d4bb7.png)

I believe the build agents should either:

Auto-queue crashes
Disable crash reporting.
To work around this issue, you can set these settings yourself:

```
echo Disabling Just-In-Time Debugger
reg add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\AeDebug" /v Debugger /d - /t REG_SZ /f
reg add "HKLM\SOFTWARE\Microsoft\.NETFramework" /v DbgManagedDebugger /d - /t REG_SZ /f
reg add "HKLM\SOFTWARE\Microsoft\Windows\Windows Error Reporting" /v DontShowUI /d 1 /t REG_DWORD /f
reg add "HKLM\SOFTWARE\Microsoft\Windows\Windows Error Reporting" /v ForceQueue /d 1 /t REG_DWORD /f
reg add "HKLM\SOFTWARE\Microsoft\Windows\Windows Error Reporting\Consent" /v DefaultConsent /d 1 /t REG_DWORD /f


reg add "HKCU\SOFTWARE\Microsoft\Windows NT\CurrentVersion\AeDebug" /v Debugger /d - /t REG_SZ /f
reg add "HKCU\SOFTWARE\Microsoft\.NETFramework" /v DbgManagedDebugger /d - /t REG_SZ /f
reg add "HKCU\SOFTWARE\Microsoft\Windows\Windows Error Reporting" /v DontShowUI /d 1 /t REG_DWORD /f
reg add "HKCU\SOFTWARE\Microsoft\Windows\Windows Error Reporting" /v ForceQueue /d 1 /t REG_DWORD /f
reg add "HKCU\SOFTWARE\Microsoft\Windows\Windows Error Reporting\Consent" /v DefaultConsent /d 1 /t REG_DWORD /f
```

**Question, Bug, or Feature?**: 
Bug/suggestion

**Virtual environments affected**
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [x] Windows Server 2016 R2
- [x] Windows Server 2019

**Comment by miketimofeev** [comment]
@alepauly Image with the fix has been deployed.
