### ISSUE TITLE
Xcode 11.2.0 and 11.3.0 will be deprecated on Catalina image on May 13 

### ISSUE THREAD

**Issue by maxim-lobanov** [actions/virtual-environments#809]
Hello everyone,
Recently, we have added Xcode 10.3 and Xcode 11.4.1 on Catalina image. Xcode 11.5 beta will come very soon.

To simplify image maintenance and reduce image generation time / image size, we would like to deprecate Xcode 11.2.0 and 11.3.0 from our images.

Our images will keep Xcode 11.2.1 and 11.3.1 (they are fully compatible because patch version doesn't bring any breaking changes) and we will create symlinks from Xcode `11.2.0 -> 11.2.1` and `11.3.0 -> 11.3.1`.

Please let us know if you have any concerns / objections

**Comment by AlenaSviridenko** [comment]
Images with changes were deployed everywhere
