### ISSUE TITLE
Python 2.7.7

### ISSUE THREAD

**Issue by SerVB** [actions/virtual-environments#810]
Hi. Please add Python 2.7.7 support.

Follow-up of https://github.com/actions/setup-python/pull/82#issuecomment-619853247.

**Comment by miketimofeev** [comment]
Hi @SerVB! Did you mean 3.7.7? There is no 2.7.7, the very latest version is 2.7.18

**Comment by maxim-lobanov** [comment]
Hello,  @SerVB ,
Just to confirm: Am I right that you need this particular version `2.7.7` and `2.7.17` doesn't work for your use-case? Usually, patch version doesn't bring breaking changes.

**Comment by SerVB** [comment]
@maxim-lobanov , hi, yep, I think I need exactly `2.7.7`.

Why exactly `2.7.7`? I'm developing a modification for a video game that uses Python 2.7.7 in its core.

Why does not another Python 2.7 version suit me?
* I compile my code to `pyc` files, and maybe there is no guarantee that latest Python 2 versions will generate bytecode compatible with `2.7.7`.
* In `2.7.7` there isn't many built-in modules, for example, many modules backported from Python 3 are missing. When I run tests on CI, I want to be sure that the code doesn't use imports not available in my target runtime.

**Comment by alepauly** [comment]
Hi @SerVB, we looked briefly into compiling 2.7.7 and it looks like it might need some tweaks. Considering the version is 6 years old now, it's not something we can prioritize. My suggestion would be for you to precompile and host off your repo, then use a version of the changes you have for `setup-python` to load in your workflow. Thanks for reaching out.

**Comment by alepauly** [comment]
> then use a version of the changes you have for `setup-python` to load in your workflow

I should clarify, you should be able to do this off your fork since we can't really support custom hosts in the generally available action.

**Comment by SerVB** [comment]
Hi! I think I'll then just continue using my `setup-python` that downloads and compiles it:

https://github.com/SerVB/TheRecentStatOfYou/blob/4ce343779458450ca075c289635d61852603635a/.github/workflows/build.yml#L9-L12

```yml
      - uses: SerVB/setup-python@customPythonVersion
        with:
          python-version: "2.7.7"
          architecture: "x86"
```

This variant's totally fine for me, it works as expected. I can wait this extra time needed for compilation.

And understanding how to precompile and host 2.7.7 in a fork will take much more of my time I suppose.

**Comment by SerVB** [comment]
Just for history.

Finally I've decided to install a deb package like this:
```
wget https://github.com/SerVB/setup-python/releases/download/2.7.7/python_2.7.7-1_amd64.deb
sudo apt install ./python_2.7.7-1_amd64.deb -y --allow-downgrades
```

This takes about 20 seconds instead of 6 minutes of compilation which I've used previously.

Example run: https://github.com/SerVB/TheRecentStatOfYou/runs/960151988.
