### ISSUE TITLE
After Powershell `Set-Date`, Windows is resetting to live Date shortly

### ISSUE THREAD

**Issue by Gustl22** [actions/virtual-environments#8102]
### Description

In order to install a certificate for a virtual audio device (see #2528, which is also not resolved completely), I need to reset the system date time.

But after setting the time with:
```powershell
Set-Date (Get-Date "2023-07-04 12:00:00");
```
It is reset immediately after that. See [the run](https://github.com/bluefireteam/audioplayers/actions/runs/5854052282/job/15869226966).

I already asked this in the Microsoft QA: https://learn.microsoft.com/en-us/answers/questions/1345225/powershell-set-date-is-resetting-to-its-original-v

They proposed, that the error is in the system host, which constantly trying to keep the date up to date. Is there a way to disable resetting the system time from the host side?

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

Version: 20230804.1.0

### Is it regression?

I don't think so

### Expected behavior

If setting the time with `Set-time`, then keep the time on the guest system.

### Actual behavior

The time is resetting immediately after setting the custom time, see "Show timestamps" on a regular GH action run.

### Repro steps

```powershell
net stop w32time; W32tm /unregister; Set-Date (Get-Date "2023-07-04 12:00:00")
# Do stuff....
# ...date is reset to current DateTime before finishing the tasks
# Reset the time if wanted:
# W32tm /register; net start w32time; w32tm /resync /force; $currentDate = Get-Date; Write-Host "Current System Date: $currentDate"

**Comment by shamil-mubarakshin** [comment]
Hello @Gustl22, thanks for reporting.
We will take a look
