### ISSUE TITLE
Update/Add swift-format

### ISSUE THREAD

**Issue by compnerd** [actions/virtual-environments#813]
**Tool information**
- Tool name: apple/swift-format
- Tool license: Apache 2
- Add or update? add
- Desired version: 5.2 (matching swift version)
- Approximate size:
- If this is an add request:
  - Brief description of tool: auto-formatting/linting for Swift
  - URL for tool's homepage: https://github.com/apple/swift-format

**Area for Triage**: Apple, Testing and Code Coverage

**Question, Bug, or Feature?**: Feature

**Virtual environments affected**
- [x] macOS 10.15
- [x] Ubuntu 16.04 LTS
- [x] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Can this tool be installed during the build?**
You can build it using `swift build -c release` and then add it to your path using `echo ::add-path::${PWD}/.build/release`

**Tool installation time in runtime**
It takes about 5 minutes to build.

**Are you willing to submit a PR?**
With guidance on adding it, I could submit a PR for it.

**Comment by Darleev** [comment]
Hello,
Let me describe current situation regarding this package:
- First of all, I tried to setup it according to provided steps, but with no luck.
- Then, I tested another way:

```
git clone https://github.com/apple/swift-format.git
cd swift-format
swift build -c release
PATH="$PATH:${PWD}/.build/release/swift-format"
```
and It takes around 4-5 minutes to install everything.

@compnerd I also found the following [swift-format package ](https://github.com/nicklockwood/SwiftFormat), which has meaningful documentation and steps to install on Ubuntu/MacOS. Installation time for this package takes about 3-4 minutes and works out of the box. I'm not sure that [nicklockwood SwiftFormat](https://github.com/nicklockwood/SwiftFormat) is compatible for you, and would like to ask you about this.

**Comment by ydnar** [comment]
@Darleev NickLockwood/swiftformat is a completely different, but still useful, formatter than apple/swift-format. It’s arguably more mature.

FWIW we use Nick’s swiftformat in our projects and spend the N minutes to install it on Ubuntu for running our CI on GitHub Actions.

I’d love to have it preinstalled.

**Comment by compnerd** [comment]
Thanks @Darleev for looking into this.  The version that you found is not really complete enough for the needs of the packages that I’m trying to use it on.  I think that using the official swift format would be better than Nick Lockwood’s version

I should mention that the official swift format should match the version of Swift that’s installed (the current images have Swift 5.2).

If there’s specific documentation that’s missing, I can help you through those steps and try to get that documentation added to the repository.

**Comment by ydnar** [comment]
@compnerd both can be installed—`swiftformat` and `swift-format` don’t conflict with each other. Nick Lockwood’s is mature and feature-complete.

**Comment by compnerd** [comment]
@ydnar yeah, I agree that they can both be installed, but don't they both provide `swift-format`?

**Comment by ydnar** [comment]
> @ydnar yeah, I agree that they can both be installed, but don't they both provide `swift-format`?

One provides `swiftformat` and the other provides `swift-format`.

**Comment by compnerd** [comment]
Ah, good, that avoids the conflict.  I’m still looking to use the official swift format though.

**Comment by alepauly** [comment]
thanks for the suggestion @compnerd but considering that we are working on fixing disk space issues in Linux, we won't bake this into the images at this time
