### ISSUE TITLE
Add Xcode 11.5 beta (for COVID-19 contact tracing APIs)

### ISSUE THREAD

**Issue by ydnar** [actions/virtual-environments#815]
**Tool information**
- Tool name: Xcode 11.5 beta
- Tool license: commercial
- Add or update? update
- Desired version: 11.5 beta
- Approximate size:

**Area for Triage**:
Apple

**Question, Bug, or Feature?**:
Feature

Xcode 11.5 adds support for Apple + Google’s[ COVID-19 contact tracing API](https://developer.apple.com/documentation/exposurenotification?changes=latest_minor). Given the current crisis, folks developing contact tracing apps on GitHub might need this.

**Virtual environments affected**
- [X] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Are you willing to submit a PR?**
Sure?

**Comment by miketimofeev** [comment]
Hi @ydnar! We've already added Xcode 11.5 to the image and it will be rolled out next week (approx. on Wednesday)

**Comment by ydnar** [comment]
Thanks!

**Comment by UBaggeler** [comment]
I assume you're talking about beta 1. Apple yesterday released beta 2 (11N605f), which should allow to upload apps with Exposure Notification to Testflight. Do you already know when we can expect this?

**Comment by maxim-lobanov** [comment]
`beta 1` will be available today.
`beta 2` will be available on Wed / Thu next week

We have a lot of VMs that we need to update with new software so it takes ~1 week time to propagate update to all VMs

**Comment by maxim-lobanov** [comment]
`Xcode 11.5 beta 1` is available on all VMs

**Comment by miketimofeev** [comment]
@ydnar I'm going to close the issue, feel free to ping me if you have any concerns.
Thank you!
