### ISSUE TITLE
Add Ubuntu 20.04 LTS envrionment

### ISSUE THREAD

**Issue by rigtorp** [actions/virtual-environments#816]
Ubuntu 20.04 LTS (https://releases.ubuntu.com/20.04/) is now out and makes sense to add it as a supported environment while deprecating Ubuntu 16.04 LTS.

**Comment by peaceiris** [comment]
This is a duplicate of https://github.com/actions/virtual-environments/issues/228

**Comment by vmapetr** [comment]
Hi @rigtorp! Thank you for your feedback! Please check details about Ubuntu 20.04 in related issue https://github.com/actions/virtual-environments/issues/228.
