### ISSUE TITLE
helm init no longer present in helm 3

### ISSUE THREAD

**Issue by rbellamy** [actions/virtual-environments#818]
**Describe the bug**
The script https://github.com/actions/virtual-environments/blob/master/images/linux/scripts/installers/1804/kubernetes-tools.sh#L37 installs helm 3. It uses a deprecated command:

```shell script
helm init --client-only
```

See https://github.com/helm/helm-www/pull/485.

**Area for Triage**: 

Servers

**Question, Bug, or Feature?**: 

Bug

**Virtual environments affected**
- [ ] macOS 10.15
- [x] Ubuntu 16.04 LTS
- [x] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Comment by vsafonkin** [comment]
Hi @rbellamy , thank you for reported issue! Fix for it was added to PR: #799
