### ISSUE TITLE
Update/Add conda (via Miniconda latest)

### ISSUE THREAD

**Issue by mingwandroid** [actions/virtual-environments#82]
**Tool information**
- Tool name: conda (via Miniconda latest)
- Add or update? Add
- Desired version: Latest
- Approximate size: 200MB
- If this is an add request:
  - Brief description of tool: Conda is an open source package management system and environment management system that runs on Windows, macOS and Linux
  - URL for tool's homepage: https://docs.conda.io/en/latest/miniconda.html

**Virtual environments affected**
- [*] macOS 10.15
- [*] Ubuntu 16.04 LTS
- [*] Ubuntu 18.04 LTS
- [*] Windows Server 2016 R2
- [*] Windows Server 2019

**Can this tool be installed during the build?**
It can take 5 to 10 minutes to download and install.

**Are you willing to submit a PR?**
Yes.

**Comment by veritas9872** [comment]
I think that this would be an awesome feature for actions!

**Comment by goanpeca** [comment]
I was playing a bit with this and created this action which works for all operating systems. It still requires some attention on activation steps.

https://github.com/goanpeca/action-setup-conda

The activation issues are related to how the shell are executed. Bash and SH shells skip any bash_profile config. The same goes for CMD shells which ignore the `Comand Process/Autorun` entry from the windows registry.

Cheers!

**Comment by goanpeca** [comment]
@mingwandroid https://github.com/marketplace/actions/setup-miniconda

**Comment by maxim-lobanov** [comment]
Hello everyone, the task `setup-miniconda` should cover this feature requests. Is it still actual to have miniconda preinstalled on the image?

**Comment by goanpeca** [comment]
Yes, miniconda comes in the images but the action allows for downloading and  installing a specific version.

**Comment by alepauly** [comment]
@mingwandroid Since it looks like `setup-miniconda` addresses what you're looking for, I'll close this issue. Thanks for your suggestion.

and thanks @goanpeca for your contributions and @maxim-lobanov for looking into it!
