### ISSUE TITLE
Add workload Live Dependency Validation for Visual Studio 2019

### ISSUE THREAD

**Issue by deloorc** [actions/virtual-environments#822]
**Tool information**
- Tool name: Visual Studio 2019
- Tool license: n/a
- Add or update? Add
- Desired version: n/a
- Approximate size: 1MB (see Visual Studio Installer when checked)
- If this is an add request:
  - Brief description of tool: [Live Dependency Validation](https://docs.microsoft.com/en-us/visualstudio/modeling/validate-code-with-layer-diagrams?view=vs-2019)
  - URL for tool's homepage: [workload-component-id-vs-enterprise](https://docs.microsoft.com/en-us/visualstudio/install/workload-component-id-vs-enterprise?view=vs-2019#net-desktop-development)

**Area for Triage**:

**Question, Bug, or Feature?**:
Feature

**Virtual environments affected**
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [x] Windows Server 2019

**Can this tool be installed during the build?**
Yes. Add the following workload to the Visual Studio installation:

Microsoft.VisualStudio.Component.DependencyValidation.Enterprise

**Tool installation time in runtime**
n/a

**Are you willing to submit a PR?**
Yes

**Comment by miketimofeev** [comment]
Hi @deloorc!
As a workaround component can be installed in runtime, but it takes about 10 min.
```
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: add workload
        run: |
          cd "C:\Program Files (x86)\Microsoft Visual Studio\Installer\"
          $InstallPath = "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise"
          $WorkLoads = '--add Microsoft.VisualStudio.Workload.ManagedDesktop'
          $Arguments = ('/c', "vs_installer.exe", 'modify', '--installPath', "`"$InstallPath`"", $WorkLoads, '--quiet', '--norestart', '--nocache')
          $process = Start-Process -FilePath cmd.exe -ArgumentList $Arguments -Wait -PassThru -WindowStyle Hidden
        shell: powershell
```

**Comment by deloorc** [comment]
Hi @miketimofeev!

Thanks for the update and workaround. Any chance this enhancement will get added? Happy to create PR.

**Comment by miketimofeev** [comment]
@deloorc we'll consider adding of the workload. Do you see any drawbacks of adding this except disk space(about 500Mb as I've noticed) in terms of VS stability? I'm asking because it seems we've faced some issues after workloads installation(I can't find any example, unfortunately)

**Comment by deloorc** [comment]
Currently we have this workload installed on our private agents and did not encounter any issues. If you would encounter any issue I would love to help diagnose.

**Comment by alepauly** [comment]
Hi @deloorc, considering disk space usage and popularity of this we can't bake it into the images at this time. Thanks for reaching out.
