### ISSUE TITLE
Add Terragrunt

### ISSUE THREAD

**Issue by CallumHibbert** [actions/virtual-environments#823]
**Tool information**
- Tool name: Terragrunt
- Tool license: Open source
- Add or update? Add
- Desired version: Latest compatible with Terraform
- Approximate size: ~30MB
- If this is an add request:
  - Brief description of tool: Helper for Terraform
  - URL for tool's homepage: https://github.com/gruntwork-io/terragrunt/

**Area for Triage**: Deployment

**Question, Bug, or Feature?**: Feature

**Virtual environments affected**
- [ x ] macOS 10.15
- [ x ] Ubuntu 16.04 LTS
- [ x ] Ubuntu 18.04 LTS
- [ x ] Windows Server 2016 R2
- [ x ] Windows Server 2019

**Can this tool be installed during the build?**
Yes, something like

`curl -sL https://github.com/gruntwork-io/terragrunt/releases/download/v0.23.13/terragrunt_linux_amd64 -o /bin/terragrunt && chmod +x /bin/terragrunt`

**Tool installation time in runtime**
Seconds.

**Are you willing to submit a PR?**
No, I'm not a expert with containers.

**Comment by alepauly** [comment]
Hi @CallumHibbert, considering it's a pretty quick install and this isn't a common request, we won't be adding this to the images at this time. Thanks for the suggestion.
