### ISSUE TITLE
Wrong permissions for PHP .composer directory 

### ISSUE THREAD

**Issue by derhansen** [actions/virtual-environments#824]
**Describe the bug**
When using PHP composer, it is not possible to use the composer cache, since the `.composer` directory permissions are wrong. This leads to the situation, that the composer cache cannot be saved during built steps

**Area for Triage**: 

Error Message:
```
Cannot create cache directory /home/runner/.composer/cache/repo/https---repo.packagist.org/, or directory is not writable. Proceeding without cache
Cannot create cache directory /home/runner/.composer/cache/files/, or directory is not writable. Proceeding without cache
```

Permissions:

![image](https://user-images.githubusercontent.com/2629896/80945560-5a007880-8dec-11ea-96a1-08b8cf275975.png)

**Question, Bug, or Feature?**: 
Bug

**Virtual environments affected**
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [X] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Expected behavior**
Directory `.composer` must be writeable to the runner user.

**Actual behavior**
Directory is not writeable. As a workaround, I added `sudo chmod 777 ~/.composer` to my built pipeline

**Comment by Darleev** [comment]
@derhansen Hello,
Thank you for the reported issue and the investigation details. I have reproduced the issue on my side and I'm working on the fix at this time.
I will keep you posted.

**Comment by Darleev** [comment]
@derhansen We have added fix for the issue to the image and it will be rolled out next week.
In case of any questions, please let us know, we will be glad to assist you further.

**Comment by derhansen** [comment]
@Darleev Awesome, thanks a lot for your work!

**Comment by Darleev** [comment]
@derhansen I have verified that after deployment .composer directory exists in home(~/) directory with the following rights:
drwxrwxrwx   2 vsts docker 4.0K May 13 03:16 .composer
I'm going to close the issue, in case of any questions feel free to open new issue:)

**Comment by derhansen** [comment]
@Darleev Thanks, works as expected
