### ISSUE TITLE
macOS 10.15 Does Not Include .NET 2.1 SDK/Runtime

### ISSUE THREAD

**Issue by mletterle** [actions/virtual-environments#827]
**Tool information**
- Tool name: .NET SDK 2.1

[The image](https://github.com/actions/virtual-environments/blob/d3b4d6b4d1fb00e6c50ed79bacc4aca7767714a3/images/macos/macos-10.15-Readme.md#language-and-runtime) already includes the non-LTS .NET 2.0 SDK, it should also include the LTS 2.1 SDK/Runtime

**Area for Triage**:
.NET Core

**Question, Bug, or Feature?**:
Bug

**Virtual environments affected**
- [X] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Can this tool be installed during the build?**
Yes, it can, but it shouldn't have to be.

**Tool installation time in runtime**
Not Long

**Are you willing to submit a PR?**
I would but the macOS source [isn't available](https://github.com/actions/virtual-environments/issues/774) yet.

**Comment by alepauly** [comment]
Thanks for the suggestion @mletterle. 

@maxim-lobanov, should we get rid of 2.0?

**Comment by maxim-lobanov** [comment]
Yep, we should but we need to do some announcement here. I will take care about it.

**Comment by maxim-lobanov** [comment]
Oh, just found that .NET Core 2.0 is installed to fix some legacy compatibility issue related to miniconda. Need to check if it can be safety removed.

Also will install .NET Core 2.1 to macOS 10.15 images

**Comment by al-cheb** [comment]
Hello, @mletterle 
`.Net 2.1[Image Version: 20200530.1]` is now available on macOS 10.15 image - https://github.com/actions/virtual-environments/blob/master/images/macos/macos-10.15-Readme.md

Pre-installed versions are - 2.1.300 2.1.301 2.1.302 2.1.401 2.1.402 2.1.403 2.1.500 2.1.502 2.1.503 2.1.504 2.1.505 2.1.506 2.1.507 2.1.602 2.1.603 2.1.604 2.1.607 2.1.700 2.1.701 2.1.801 2.1.802 2.1.803 2.1.804 2.1.805 2.1.806

Feel free to open the thread if you have any concerns.
