### ISSUE TITLE
Update Android NDK bundle to R21B in Ubuntu 18.04 LTS

### ISSUE THREAD

**Issue by mganandraj** [actions/virtual-environments#829]
**Tool information**
- Tool name: Android SDK/NDK
- Tool license: No change
- Add or update? Update
- Desired version: NDK R21B (v21.1.6352462 ) which has some critical bug fixes , Current version is NDK R21A (21.0.6113669)
- Approximate size: 
- If this is an add request:
  - Brief description of tool: 
  - URL for tool's homepage: 

**Area for Triage**: Android

**Question, Bug, or Feature?**: Bug

**Virtual environments affected**
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [x] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Can this tool be installed during the build?**
Yes

**Tool installation time in runtime**
Depends on the download time.

**Are you willing to submit a PR?**
Yes

**Comment by andy-mishechkin** [comment]
Hello.
The last version of Android NDK will be included in the next Ubuntu 18 build. Please wait for the next image deployment.

**Comment by maxim-lobanov** [comment]
New image with NDK v21.1.6352462 was deployed.
