### ISSUE TITLE
Add Windows SDK 8.1

### ISSUE THREAD

**Issue by jamesmcguirepro** [actions/virtual-environments#842]
**Tool information**
- Tool name: Microsoft Windows SDK
- Tool license: 
- Add or update? Update
- Desired version: 8.1
- Approximate size: 0.98 GB
- If this is an add request:
  - Brief description of tool: Windows Software Development Toolkit
  - URL for tool's homepage: https://developer.microsoft.com/en-us/windows/downloads/sdk-archive/

**Area for Triage**:

**Question, Bug, or Feature?**:

**Virtual environments affected**
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [x] Windows Server 2019

**Can this tool be installed during the build?**
Possibly, with admin rights and a restart.

**Tool installation time in runtime**

**Are you willing to submit a PR?**
Yes. It existed before: https://github.com/actions/virtual-environments/blob/master/images/win/scripts/Installers/Windows2016/Install-VS2017.ps1#L61

**Comment by maxim-lobanov** [comment]
@jamesmcguirepro , Could you please share the approximate size of this SDK?

Also I see that Windows 8.1 SDK is officially deprecated in VS 2019.

> The Windows 8.1 SDK is no longer available in the Visual Studio installer. Please upgrade your C++ projects to the latest Windows 10 SDK. If you have a hard dependency on 8.1, you can download it from the Windows SDK archive.

**Comment by jamesmcguirepro** [comment]
@maxim-lobanov
It's listed as 0.98 GB on my local machine's Uninstall Programs list

**Comment by riverar** [comment]
All SKUs of Windows 8.1 have left mainstream support. Only extended support is available for this version of Windows.

Azure Pipelines has green lit the addition of this SDK to their image
https://github.com/Microsoft/azure-pipelines-image-generation/commit/2b478e34162f61738bf10d02bc2e11a56ec1223c

You can install just the desktop/.NET SDK features (no tooling) via:
`sdksetup.exe /features OptionId.WindowsDesktopSoftwareDevelopmentKit OptionId.NetFxSoftwareDevelopmentKit /quiet`

The SDK footprint is about **505MB**, calculated from a clean machine install via:
* `C:\Program Files (x86)\Windows Kits\8.1` @ 490MB
* `C:\Program Files (x86)\Microsoft SDKs\Windows\v8.1A` @ 15MB

**Comment by alepauly** [comment]
Hi @jamesmcguirepro, considering that it can be installed on runtime and it's a pretty old version, we won't install it by default in the images. Thanks for the suggestion though.

**Comment by abergmeier** [comment]
So IIUC the steps for getting Windows SDK 8.1 on _windows-latest_ would be to:

1. Download https://go.microsoft.com/fwlink/p/?LinkId=323507
1. Extract to C:\temp
1. Run `C:\temp\sdksetup.exe /features OptionId.WindowsDesktopSoftwareDevelopmentKit OptionId.NetFxSoftwareDevelopmentKit /quiet`

**Comment by riverar** [comment]
@abergmeier Yep, specifically this should do:

```
- name: Install Windows 8.1 SDK
  shell: powershell
  run: |
    Invoke-WebRequest -Method Get -Uri https://go.microsoft.com/fwlink/p/?LinkId=323507 -OutFile sdksetup.exe -UseBasicParsing
    Start-Process -Wait sdksetup.exe -ArgumentList "/q", "/norestart", "/features", "OptionId.WindowsDesktopSoftwareDevelopmentKit", "OptionId.NetFxSoftwareDevelopmentKit"
```

**Comment by abergmeier** [comment]
That is what I tried and `Invoke-WebRequest` fails with:

```
Response status code does not indicate success: 301 (Moved Permanently).
```

**Comment by abergmeier** [comment]
What works for me is:

```
    - name: Download and install Windows SDK
      run: |
        import subprocess
        import urllib.request
        urllib.request.urlretrieve("https://go.microsoft.com/fwlink/p/?LinkId=323507", "sdksetup.exe")
        subprocess.run(["sdksetup.exe", "/q", "/norestart", "/features", "OptionId.WindowsDesktopSoftwareDevelopmentKit", "OptionId.NetFxSoftwareDevelopmentKit"], check=True, capture_output=True)
      shell: python
```

**Comment by riverar** [comment]
If you use PowerShell Core, you'll run into questionable semantics around HTTP 3xx status codes (see PowerShell/4534), hence the `shell: powershell` instead 😉 But looks like you got there with Python instead.

**Comment by ben-spiller** [comment]
NB: MS SDK 8.1 is the default SDK you get when you install Visual Studio 2015 SP3 (even on a Windows 10 machine), and VS2015 itself is supported until 2025. So maybe there is an argument for providing it until VS2015 goes out of support?

Or at least providing an action to install it when needed. 

The powershell example above works, but after a quick download it takes several minutes to install. Does anyone have an action or workflow recipe for caching the actual installation (or even know if that's possible - not sure if there are registry aspects needed in addition to the files themselves)?

**Comment by laurence-myers** [comment]
You can also install the SDK using an older version of vs_buildtools.exe. This is handy if you also need to install an older version of MSVC.

In this example, I use v15 of vs_buildtools.exe to install platform tools v140 (VS 2015) and the windows 8.1 SDK.

```yaml
    - name: Install MSVC 2015 (v140) and Windows 8.1 SDK
      shell: powershell
      run: |
        $VS_BTOOLS_EXE="vs_buildtools.exe"
        $VS_BTOOLS_URI="https://aka.ms/vs/15/release/vs_buildtools.exe"
        Invoke-WebRequest -Uri $VS_BTOOLS_URI -OutFile $VS_BTOOLS_EXE
        Start-Process -FilePath ./vs_BuildTools.exe -ArgumentList `
        "--add", "Microsoft.VisualStudio.Component.VC.140", `
        "--add", "Microsoft.VisualStudio.Component.Windows81SDK", `
        "--quiet", "--norestart", "--force", "--wait" -Wait -PassThru
```

(I based the example on [this StackOverflow answer](https://stackoverflow.com/a/74673996/953887))
