### ISSUE TITLE
libsodium

### ISSUE THREAD

**Issue by johanatan** [actions/virtual-environments#843]
**Tool information**
- Tool name: libsodium
- Tool license: ISC license
- Add or update? Add.
- Desired version: latest.
- Approximate size: No idea.
- If this is an add request:
  - Brief description of tool: it's required for cryptography (which is required for your "secrets API").
  - URL for tool's homepage: https://github.com/jedisct1/libsodium

**Area for Triage**:

**Question, Bug, or Feature?**:

**Virtual environments affected**
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Can this tool be installed during the build?**

**Tool installation time in runtime**

**Are you willing to submit a PR?**

**Comment by andy-mishechkin** [comment]
Hello, Johanatan!
Please select the Virtual environments, where you plan to use libsodium. 
Also may you provide approximate size of this feature (it may be different on various virtual environments).
Thank you

**Comment by jleonard-r7** [comment]
I believe it is too late for me to edit but I need it for latest Ubuntu and it’s approximately 2MB. Thanks!

**Comment by andy-mishechkin** [comment]
libsodium is shipped by ISC license

**Comment by jleonard-r7** [comment]
Yes. And?

**Comment by maxim-lobanov** [comment]
ISC license should work for us since it allows to distribute software.
Did you consider installation of this tool in runtime?

It can be installed using the following code (it takes about 5 seconds to install):
```
sudo apt-get install -y libsodium-dev
```

**Comment by jleonard-r7** [comment]
Yea I tried that but Clojure tools.deps caesium compile could not find it. Probably there is a way to make it work but I will have to troubleshoot some more.

**Comment by alepauly** [comment]
@johanatan, since this is a pretty quick install and due to maintenance concerns, we won't bake it into the image. Thanks for bringing it up though.

**Comment by jleonard-r7** [comment]
Seems an odd choice since your Actions API requires it.
