### ISSUE TITLE
Update Data Tools

### ISSUE THREAD

**Issue by arvindshmicrosoft** [actions/virtual-environments#850]
**Tool information**
- Tool name: sqlpackage for Windows / Data Tools
- Tool license: MSFT redistributable
- Add or update? Update
- Desired version: current latest from https://go.microsoft.com/fwlink/?linkid=2128142
- Approximate size: 
- If this is an add request:
  - Brief description of tool: 
  - URL for tool's homepage: 

**Area for Triage**: Databases

**Question, Bug, or Feature?**:
 Feature

**Virtual environments affected**
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [X] Windows Server 2019

**Can this tool be installed during the build?**

**Tool installation time in runtime**

**Are you willing to submit a PR?**

**Comment by Darleev** [comment]
Hello @arvindshmicrosoft 
I have added few changes to upgrade Data Tool to the latest version. Currently, [feature request](https://github.com/actions/virtual-environments/pull/863) in review state. I will keep you posted about status.

**Comment by Darleev** [comment]
@arvindshmicrosoft We have added Data Tools latest to the image and it will be rolled out next week.
In case of any questions, please let us know, we will be glad to assist you further.

**Comment by Darleev** [comment]
@arvindshmicrosoft The latest data tools have been added to the image.
I'm going to close the issue.
In case of any questions please let us know
