### ISSUE TITLE
Windows Application Packaging Project doesn't compile against recently added Windows 10 SDK (10.0.14393.795)

### ISSUE THREAD

**Issue by riverar** [actions/virtual-environments#858]
**Describe the bug**
Windows 10 SDK 14393 was added to Windows virtual images per my issue #451 (added via PR #580). (Thanks!) But the [14393 SDK feature](https://github.com/actions/virtual-environments/pull/580/commits/b7714ce050888355c6ac0611539afc190ffd8b1d#diff-dd501d5a81da549f4f4e3133b66b66fdR124) installed via Visual Studio 2019 installation does not appear to install the components necessary for Windows Application Packaging Projects to compile correctly. Attempting to compile such a project will result in msbuild task `_GetSdkToolPaths` failure:

```
(_GetSdkToolPaths target) -> 
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\
VisualStudio\v16.0\AppxPackage\Microsoft.AppXPackage.Targets(1007,5):
error APPX3217: SDK folder containing 'UAP.props' for 'UAP 10.0.14393.0'
cannot be located. See http://go.microsoft.com/fwlink/?LinkID=798187 for
more information.
```

**Area for Triage**: 
.NET Framework

**Question, Bug, or Feature?**: 
Bug

**Virtual environments affected**
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [x] Windows Server 2016 R2
- [x] Windows Server 2019

**Expected behavior**
Successful workflow execution.

**Actual behavior**
Compilation failure of project(s) targeting 14393.
Full repro. repo. located at https://github.com/riverar/GHA-Repro-14393

**Workaround**
Install 14393 SDK manually (adds ~3 minutes to workflow execution time).

```
- name: Workaround - Install Windows 10 14393 SDK
  shell: powershell
  run: |
    Invoke-WebRequest -Method Get -Uri https://go.microsoft.com/fwlink/p/?LinkId=838916 -OutFile sdksetup.exe -UseBasicParsing
    Start-Process -Wait sdksetup.exe -ArgumentList "/q", "/norestart", "/ceip off", "/features OptionId.WindowsSoftwareDevelopmentKit"
```

**Comment by miketimofeev** [comment]
Hi @riverar!
Unfortunately, I've found there is no such SDK component for VS19, that's why compile doesn't work.
![image](https://user-images.githubusercontent.com/48208649/81540787-d52cd600-937a-11ea-9859-07db8e0251c9.png)
We will consider adding the SDK through the setup file as you suggested.
Thank you!

**Comment by riverar** [comment]
@miketimofeev In the meantime, I'll send an email to the Visual Studio folks. I don't understand why 14393 was removed ([prematurely too](https://github.com/MicrosoftDocs/visualstudio-docs/commit/37e6886087e40f8576eaa82dfd5e87e524c2319f#diff-757fef660bf40737850ce059881acf40L387)) as it's the current LTSC build.

**Comment by miketimofeev** [comment]
@riverar PR with the change has been merged. I'll notify you when the image is deployed.
Thank you!

**Comment by miketimofeev** [comment]
@riverar the image has been deployed. Could you check the SDK, please?

**Comment by riverar** [comment]
@miketimofeev Verified https://github.com/riverar/GHA-Repro-14393/runs/700336612 🚀

**Comment by miketimofeev** [comment]
@riverar thanks for the update! I'm going to close the issue.
