### ISSUE TITLE
Update/Add XCode 9.4.1

### ISSUE THREAD

**Issue by Margen67** [actions/virtual-environments#859]
**Tool information**
- Tool name: XCode
- Tool license: 
- Add or update? Add
- Desired version: 9.4.1
- Approximate size: 
- If this is an add request:
  - Brief description of tool: XCode ~9.4.1 is the last version of XCode to support building 32-bit applications. It used to be in older versions of the macOS environment.
Travis, and CircleCI also have it:
https://docs.travis-ci.com/user/reference/osx/#xcode-version
https://circleci.com/docs/2.0/testing-ios/#supported-xcode-versions
  - URL for tool's homepage: https://developer.apple.com/xcode/

**Area for Triage**:

**Question, Bug, or Feature?**:
Feature.

**Virtual environments affected**
- [x] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Can this tool be installed during the build?**
Yes* (requires an Apple ID): https://github.com/marketplace/actions/setup-xcode

**Tool installation time in runtime**

**Are you willing to submit a PR?**
No.

**Comment by maxim-lobanov** [comment]
Hello,
Unfortunately, it is not possible to add Xcode 9.4.1 to our images.
For GitHub Actions, we provide the single macOS version - 10.15 (Catalina). Xcode 9.4.1 is not supported on it (Actually, you can't install this version of Xcode through https://github.com/marketplace/actions/setup-xcode action)
A few related threads on Apple forum:
- https://forums.developer.apple.com/thread/126968
- https://forums.developer.apple.com/thread/126967
