### ISSUE TITLE
Add bison

### ISSUE THREAD

**Issue by udzura** [actions/virtual-environments#86]
**Tool information**
- Tool name: bison
- Add or update? Add
- Desired version: any
- Approximate size: -
- If this is an add request:
  - Brief description of tool: Bison is a parser generator like Yacc. Some project requires this ,especially [mruby](https://mruby.org/). 
  - URL for tool's homepage: https://packages.ubuntu.com/search?keywords=bison

**Virtual environments affected**
- [x] macOS 10.15
- [x] Ubuntu 16.04 LTS
- [x] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Can this tool be installed during the build?**
No, this is usually provided as a OS package.

**Are you willing to submit a PR?**

`y`

**Comment by senden9** [comment]
GLIBC needs bison also.
At the moment I need to do a `sudo apt install bison` on `ubuntu-latest` aka 18.04.

**Comment by kaylangan** [comment]
Looks like this can be installed during your build then? Approximately how much time does that add to your build?

**Comment by senden9** [comment]
Last build 1m7sec. So it is doable.

**Comment by simonsan** [comment]
2 min with chocolatey under Win.

**Comment by maxim-lobanov** [comment]
Tool can be potentially installed in runtime:
```
# Ubuntu: takes 8 seconds to install
sudo apt install bison
# macOS: takes 11 seconds to install
brew install bison
```

**Comment by simonsan** [comment]
> Tool can be potentially installed in runtime:

`2 min with chocolatey under Win`

🤔

**Comment by alepauly** [comment]
@udzura We won't be adding this at the moment considering that it's somewhat specialized and we have maintenance concerns. Thanks for the suggestion.
