### ISSUE TITLE
MacOSX images with case sensitive APFS filesystem

### ISSUE THREAD

**Issue by moljac** [actions/virtual-environments#865]
MacOSX installation defaults to case insensitive APFS filesystem, but it would be good to have images with case sensitive filesystem. Case insensitive FS are more tolerant and a lot of errors are undetected. 

Building on case sensitive MacOSX would also cover some tests for Linux, which has case sensitive by default.

Some errors due to case sensitivity:

https://github.com/novotnyllc/MSBuildSdkExtras/issues/224

https://github.com/xamarin/AndroidX/issues/101

**Area for Triage**:  Apple

Feature

- [x] macOS 10.15
- [x] macOS (any)

**Comment by maxim-lobanov** [comment]
Thank you for feature request.

@alepauly , a few thoughts:
We definitely can't switch existing images because it will be breaking change for the most of the builds. It can be done only as a separate image (we have to use different filesystem)

**Comment by moljac** [comment]
Morn @maxim-lobanov 

I pinged you on Xamarin slack in a reply to your question about Xamarin.Android images. Please ignore/disregard that thread.

> We definitely can't switch existing images because it will be breaking change for the most of the builds.

No. Please don't do it on existing images. There would be too much problems.

Separate image would be the best option, excluding the fact that MacOSX could be built twice, so energy consuption is higher (and I'm green aware freak).

**Comment by moljac** [comment]
For example: Users could build only on case sensitive MacOSX image. It is more restrictive, so errors would pop up earlier, thus no need to build on case insensitive OS at all.

So, additional MacOSX images are the best option.

**Comment by alepauly** [comment]
Thanks for reaching out @moljac. We can't offer another image at this time since it would affect overall capacity of Mac and be costly to maintain.
