### ISSUE TITLE
Update/Add azcopy

### ISSUE THREAD

**Issue by Poil** [actions/virtual-environments#868]
**Tool information**
- Tool name: azcopy
- Tool license: MIT
- Add or update? update
- Desired version: v10
- Approximate size: 20Mb
- If this is an add request:
  - Brief description of tool: AzCopy v10 is a command-line utility that you can use to copy data to and from containers and file shares in Azure Storage accounts
  - URL for tool's homepage: https://github.com/Azure/azure-storage-azcopy

**Area for Triage**:

**Question, Bug, or Feature?**:
Feature

**Virtual environments affected**
- [ ] macOS 10.15
- [x ] Ubuntu 16.04 LTS
- [x ] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Can this tool be installed during the build?**

```
wget -O azcopy.tar.gz https://aka.ms/downloadazcopy-v10-linux
tar zxvf azcopy.tar.gz --strip-components=1 -C /usr/local/bin
```

**Tool installation time in runtime**
1 minute

**Are you willing to submit a PR?**
If you agree with this upgrade, why not. (Not sure why you are in v7)

**Note**
This will allow to do "sync" between fileshares or blob containers

**Comment by miketimofeev** [comment]
@Poil could you please update the description with `Approximate size: 20Mb`?

**Comment by miketimofeev** [comment]
@Poil I've created a PR with Azcopy10, but we can't get rid of version 7 at the moment to not break any workflows, which depend on version 7 functional.

**Comment by miketimofeev** [comment]
@Poil We've deployed the image with azcopy10.
```
  which azcopy10
  azcopy10 --version
  shell: /bin/bash -e {0}
/usr/local/bin/azcopy10
azcopy version 10.4.3
```
I'm going to close the issue, but feel free to ping me if you have any concerns.
Thank you!
