### ISSUE TITLE
Windows: CMake MSVC configuration is very slow

### ISSUE THREAD

**Issue by zeux** [actions/virtual-environments#87]
On Windows VM, the CMake configuration step is very slow, taking 1-1.5 minutes on average to configure a simple C++ project.

This can be seen in meshoptimizer project that runs builds on both GitHub CI and Travis CI.

Here's an example build from GitHub CI (windows-latest, aka Windows Server 2019):
https://github.com/zeux/meshoptimizer/commit/309349f71fb444eaf9cf4d04665c70d012f941c2/checks?check_suite_id=303776539
Note that "cmake configure" step here took 1m32s for 32-bit build on Windows, and 1m56s for 64-bit build.

Here's the same project built on Travis CI:
https://travis-ci.org/zeux/meshoptimizer/builds/609870328
Note that cmake configure here took 7s for 32-bit build on Windows, and 8s for 64-bit build.

Running CMake with the same command line on my own desktop (Windows 10, Visual Studio 2019) results in ~3 seconds runtime. This is with an i7 8700K and a M.2 SSD so it's understandable that a cloud VM will be slower - Travis CI time seems reasonable here, but GitHub CI seems like a clear anomaly.

I'm not sure how to investigate this further. Please note that the CMake build here is already optimized to only require configuring one (C++) compiler. The GitHub CI times are very inconsistent, ranging from ~50 seconds to ~2 minutes as shown in the link above.

Any advice to try to narrow this down is appreciated; this seems like a software configuration issue to me but I'm not sure how to identify the specific culprit.

**Comment by zeux** [comment]
Just out of curiosity decided to test Windows Server 2016 VM with Visual Studio 2017 (this is a bit closer to what Travis CI is using), and in that build (https://github.com/zeux/meshoptimizer/runs/296231360) cmake configure took 2.5 minutes 😱

**Comment by zeux** [comment]
I tried to debug this using `wtrace` with no particular luck - it looks like MSBuild invocation via CMake is taking a lot of time (30-40 seconds?) but when trying to trace MSBuild itself it looks like it just takes a lot of time loading various files.

I've just finished converting another project that is not CMake based but that needs to use msbuild directly to build .vcxproj files, and the results are similarly alarming:

Here's an AppVeyor build this time (not Travis), that shows that each architecture takes 1m 30s to build - this includes two msbuild invocations that build the same code in two different configurations. Build times for these configurations are expected to be approximately equal.

https://ci.appveyor.com/project/zeux/qgrep/builds/28751238

Here's a GH build for the same project, with the two configurations split into two separate steps:

https://github.com/zeux/qgrep/runs/296512654

You can see that while the *second* run to MSBuild takes approximately half of the AppVeyor build time, the first run takes much much longer. Curiously, if you look at the timestamps, it doesn't look as if there's just a large delay up front - the delays seem to be spread throughout execution, accumulating near compilation of the first few files, linking, etc.

This makes me suspect that the issue is that on Windows, access to Visual Studio files takes a lot of time when you do it the first time around - perhaps lazily downloading files on demand?

**Comment by zeux** [comment]
While the time that CMake takes to configure is still non-negligible, it looks like it's much more consistent at about 35 seconds now, so I'm going to assume this was improved and close this.

**Comment by eustas** [comment]
35 seconds is still too much. Would be nice to know what happens during this period. Perhaps simple extra cache entry would make this instantly fast (for repeated run)
