### ISSUE TITLE
Update/Add Conan

### ISSUE THREAD

**Issue by zscgeek** [actions/virtual-environments#876]
**Tool information**
- Tool name: Conan
- Tool license: MIT
- Add or update? Add
- Desired version: Latest
- Approximate size: 
- If this is an add request:
  - Brief description of tool: Conan C++ Package Manager
  - URL for tool's homepage: https://conan.io/

**Virtual environments affected**
- [X ] macOS 10.15
- [X ] Ubuntu 16.04 LTS
- [X ] Ubuntu 18.04 LTS
- [ X] Windows Server 2016 R2
- [X ] Windows Server 2019

**Can this tool be installed during the build?**
pip3 install conan

**Tool installation time in runtime**
Min or two - not long but would be nice to have on standard image.

**Comment by alepauly** [comment]
Hi @zscgeek, how big is Conan on disk and how long would it take to install it on the fly?

**Comment by alepauly** [comment]
Considering that we already support other package managers and Conan installs pretty quickly we'll keep this off the image for now.
