### ISSUE TITLE
Update/Add OCaml

### ISSUE THREAD

**Issue by Takashiidobe** [actions/virtual-environments#877]
**Tool information**
- Tool name: OCaml
- Tool license: GNU Lesser General Public License. More details at: https://ocaml.org/docs/license.html
- Add or update? Add
- Desired version: [4.10.0, 4.09.1, 4.09, 4.08.1] (This list can be altered as necessary).
- Approximate size: ~307MB on Mac OS X with homebrew, ~400MB on Linux installing OPAM and using `opam switch`
- If this is an add request:
  - Brief description of tool: OCaml is an industrial strength programming language supporting functional, imperative and object-oriented styles.
  - URL for tool's homepage: https://ocaml.org/

**Area for Triage**:
I could not find a section for OCaml, but that would go there if allowed.

**Question, Bug, or Feature?**:
Feature

**Virtual environments affected**
- [X] macOS 10.15
- [X] Ubuntu 16.04 LTS
- [x] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Can this tool be installed during the build?**

- https://github.com/avsm/setup-ocaml installs OPAM (a package manager for OCaml) and installs the desired OCaml compiler version afterwards.

Otherwise, the System Package managers can install OCaml.

** Mac OS X **
`brew install ocaml` will install Ocaml on Mac OS X @v4.09.0

** Ubuntu LTS **
- Ubuntu LTS 16.04
   - `apt install ocaml` will install OCaml @v4.02.3
- Ubuntu LTS 18.04
  - `apt install ocaml` will install OCaml @v4.05.0

I believe OCaml can be installed on windows, but I am not very familiar with windows.

**Tool installation time in runtime**
Using avsm/setup-ocaml, which installs OPAM and then runs `opam switch` to install in the current Ubuntu 18.04 LTS takes ~6-8 minutes.

**Are you willing to submit a PR?**
I would love to make a PR :)

**Notes**
If OCaml will not be supported, please feel free to close this Feature Request.
If OCaml will be supported, I would like to have some discussion on which versions of OCaml would be most popular to support, as well as development tools (such as Dune and OPAM).

**Comment by alepauly** [comment]
Thanks for the request @Takashiidobe but at this time we can't add it to the images, mostly due to disk space concerns.

**Comment by artob** [comment]
It's easy enough to install OCaml on Linux with [avsm/setup-ocaml](https://github.com/avsm/setup-ocaml), but where this would be really valuable is for the macOS environment, since right now installing OCaml takes 5-6 minutes which translates into 50-60 billed minutes (!) just to be able to run unit tests.
