### ISSUE TITLE
Update node 8.x on Windows

### ISSUE THREAD

**Issue by hashtagchris** [actions/virtual-environments#88]
**Tool information**
- Tool name: node
- Add or update? Add
- Desired version: v8.16.2
- Approximate size: 

Currently v8.10.0 is installed on Windows. That comes with npm v5.6.0, which doesn't support the `npm ci` command. `npm install` can be used as a workaround, but its slower.

**Virtual environments affected**
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [x] Windows Server 2016 R2
- [x] Windows Server 2019

**Can this tool be installed during the build?**
`npm install -g npm` can be used to update npm. Completes in ~10 seconds probably.

**Are you willing to submit a PR?**
Not at this time

Related issue: https://github.com/actions/virtual-environments/issues/42

**Comment by cschleiden** [comment]
In the past, `npm install -g npm` has been difficult on Windows, leading to projects like https://github.com/felixrieseberg/npm-windows-upgrade#upgrade-npm-on-windows, just to keep in mind when doing anything to upgrade here.

**Comment by joshmgross** [comment]
Once this is resolved, we should update the node starter template to go back to using `npm ci`

**Comment by kaylangan** [comment]
We've updated the installed version to 12. Does that fix this issue or do you still need Node 8 latest?

**Comment by hashtagchris** [comment]
We still need Node 8 latest, as https://github.com/actions/starter-workflows/blob/master/ci/node.js.yml references it.

**Comment by richardlau** [comment]
> 
> 
> We still need Node 8 latest, as https://github.com/actions/starter-workflows/blob/master/ci/node.js.yml references it.

FWIW I've submitted a PR (https://github.com/actions/starter-workflows/pull/307) to remove Node.js 8 from the starter-workflow as it went End-of-Life at the end of last year.

**Comment by kaylangan** [comment]
I think the right approach is what @richardlau suggested. Closing this out.
