### ISSUE TITLE
Add vercel

### ISSUE THREAD

**Issue by brunowowk** [actions/virtual-environments#882]
**Tool information**
- Tool name: Formely `now`, renamed to `vercel`
- Tool license:  Apache-2.0
- Add or update? Add
- Desired version: latest
- Approximate size: ?

ref: https://github.com/zeit/now/releases/tag/vercel%4019.0.0
> We will continue publishing now and vercel in tandem until January 2021 at which point, new updates will only be published to vercel.

it's probably best to keep both `now` and `vercel` until then. Maybe install `vercel` and create a symlink for `now` because it's the same package

**Area for Triage**: JavaScript and Node.js

**Virtual environments affected**
- [ ] macOS 10.15
- [x] Ubuntu 16.04 LTS
- [x] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Comment by miketimofeev** [comment]
Hi @brunowowk!
Can it be installed during runtime? How much time does it take?

**Comment by brunowowk** [comment]
yes, it's an npm package. It's actually an update to the `now` bin that's already included. 

Then only change would be to install `vercel` instead of `now`, or to install both over here:
https://github.com/actions/virtual-environments/blob/51d02f26f42e53bb963bb6bc9754501b28a3d2ba/images/linux/scripts/installers/zeit-now.sh#L11

**Comment by maxim-lobanov** [comment]
if they are fully compatible (you mentioned that it is identical package), installing `vacel` instead of `now` and creating symlink sounds good

**Comment by andy-mishechkin** [comment]
Hello!
We have made these changes, as we discussed above. Please wait for the next Ubuntu Images deployment, which will bring Zeit Vercel CLI and symlibk "now" to this.

**Comment by andy-mishechkin** [comment]
Hello, @styfle 
Thank you for your note.
I've fixed this issue. The right name should be present after the next Ubuntu VM updating.
If it will not be fixed - please feel free to ping me here

**Comment by andy-mishechkin** [comment]
Deployment has been successful. The valid name is present.
