### ISSUE TITLE
Add 7-zip to macOS image

### ISSUE THREAD

**Issue by ihnorton** [actions/virtual-environments#884]
**Tool information**
- Tool name: 7-zip
- Tool license: LGPL
- Add or update? add (exists in other images)
- Desired version: same as other images
- Approximate size: n/a

**Area for Triage**:

**Question, Bug, or Feature?**:

Feature

**Virtual environments affected**
- [x] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Can this tool be installed during the build?**

**Tool installation time in runtime**

**Are you willing to submit a PR?**

---

x-ref https://github.com/microsoft/azure-pipelines-image-generation/issues/791

**Comment by al-cheb** [comment]
Hello, @ihnorton 
7-Zip 16.02[Image Version: 20200530.1] is now available on macOS 10.15 image - https://github.com/actions/virtual-environments/blob/master/images/macos/macos-10.15-Readme.md

Feel free to open the thread if you have any concerns.
