### ISSUE TITLE
Add zstd

### ISSUE THREAD

**Issue by imbsky** [actions/virtual-environments#89]
- Tool name: zstd
- Add or update?: Add
- Desired version: latest
- Approximate size:
- If this is an add request:
  - Brief description of tool: Zstandard is a real-time compression algorithm, providing high compression ratios. It offers a very wide range of compression / speed trade-off, while being backed by a very fast decoder.
  - URL for tool's homepage: https://github.com/facebook/zstd

**Virtual environments affected**

- [x] macOS 10.15
- [x] Ubuntu 16.04 LTS
- [x] Ubuntu 18.04 LTS
- [x] Windows Server 2016 R2
- [x] Windows Server 2019

**Can this tool be installed during the build?**
I don't know...

**Are you willing to submit a PR?**
Maybe?

**Comment by imbsky** [comment]
Related issue: https://github.com/actions/cache/issues/6

**Comment by imbsky** [comment]
I can help with this, where and what should I do? or are you already working on it?

**Comment by imbsky** [comment]
Ubuntu:

```console
apt install zstd
```

macOS:

```console
brew install zstd
```

Windows:

```console
choco install zstandard
```

**Comment by imbsky** [comment]
I tried to open PR, but I couldn't find the installer directory of macOS, so I gave up. Can you help this? Cache Action needs it now!

**Comment by imbsky** [comment]
What is the current status of this?

**Comment by imbsky** [comment]
I just opened a PR.

**Comment by miketimofeev** [comment]
PR for windows and linux has been merged. MacOS in on the way

**Comment by miketimofeev** [comment]
zstd has been added to macOS. Waiting for vm rollout(approx 1-1.5 weeks)

**Comment by imbsky** [comment]
Cool! Thanks for your help 🙂

**Comment by miketimofeev** [comment]
@imbsky the image has been deployed. Could you check zstd is available, please?

**Comment by imbsky** [comment]
Sure! I will check!

**Comment by miketimofeev** [comment]
@imbsky thanks for checking, I'll take a look at Windows. And what about Ubuntu?

**Comment by imbsky** [comment]
I will check it tonight

**Comment by miketimofeev** [comment]
Uh, it seems windows-latest was forgotten in this PR
https://github.com/actions/virtual-environments/pull/414
I'll made a fix

**Comment by imbsky** [comment]
Thanks!

**Comment by miketimofeev** [comment]
@imbsky the image has been deployed. Could you check the windows-latest, please?

**Comment by imbsky** [comment]
Great, thanks. Sure, I will check it tomorrow.

**Comment by miketimofeev** [comment]
@imbsky I've checked it and everything seems fine. Closing the issue, but feel free to reopen if you have any concerns.

**Comment by imbsky** [comment]
Thanks!
