### ISSUE TITLE
Misidentification of "Mingw-w64" as "MinGW"

### ISSUE THREAD

**Issue by SlySven** [actions/virtual-environments#890]
Not sure if this is the best place to mention it but I will be pleases to see MSYS2 added by #30 . 

However on the https://github.com/actions/virtual-environments/blob/master/images/win/Windows2019-Readme.md page it confusingly lists MinGW but that is WRONG - as the original developers of THAT project at https://osdn.net/projects/mingw/releases/ pointedly point out:
> "MinGW is a registered trademark of Software in the Public Interest Inc., registration number 86017856; this trademark has been registered on behalf of the MinGW.org Project, and its use by any other project is unauthorized."

Therefore can that be edited to refer to the correct designation as **Mingw-w64**, ~~who are, as I understand it the developers of MSYS2 as well~~ *Edit: further research suggests that is that is perhaps not the situation - but it seems possible that they do talk to each other*!

Apart from anything else using the correct name helps as it indicates that we can use a subsystem that is actively being developed and maintained and supports 64-bit processors - the last of which is not something that can be said of the original MinGW project...

Edit: should be closed by #893 .

**Comment by 1480c1** [comment]
It's possible the MinGW that they mention in that readme is the actual MinGW and not a Mingw-w64 toolchain

**Comment by SlySven** [comment]
I was going to say that the version number (8.1.0 IIRC) *seems* more likely to be a Mingw-w64 one (though, looking at http://mingw-w64.org/doku.php/download it seems that that is actually the GCC version - and the MSYS2 builds of Mingw-w64 are now official offering a 9.x one, though having done a sort of homunculus installation of the interesting parts of GitForWindows as per https://github.com/git-for-windows/git/wiki/Install-inside-MSYS2-proper I seem now to have 10.x to compile with) - but when I go to look for a semantic version identifier for Mingw-w64 - it is, *um*, difficult to track...

The latest *version* of MinGW (from https://osdn.net/projects/mingw/releases/72860) seems to be 5.3.1 .

Wikipedia does not give precise details either - the highest that it suggests for a part of MinGW is only **5.2.1** (for "WSL" {?}) and for Mingw-w64 is **7.0.0**.

**Comment by 1480c1** [comment]
I believe the versioning between MinGW, Mingw-w64, and gcc are all separate (sort of), so I think the 8.1.0 they are referring to is gcc 8.1.0 and not necessarily referring to mingw-w64 or MinGW 8.1.0, but the quickest way to confirm is to check the gcc they have in their runner.

**Comment by 1480c1** [comment]
```
Run gcc -v
Using built-in specs.
COLLECT_GCC=C:\ProgramData\Chocolatey\lib\mingw\tools\install\mingw64\bin\gcc.exe
COLLECT_LTO_WRAPPER=C:/ProgramData/Chocolatey/lib/mingw/tools/install/mingw64/bin/../libexec/gcc/x86_64-w64-mingw32/8.1.0/lto-wrapper.exe
Target: x86_64-w64-mingw32
Configured with: ../../../src/gcc-8.1.0/configure --host=x86_64-w64-mingw32 --build=x86_64-w64-mingw32 --target=x86_64-w64-mingw32 --prefix=/mingw64 --with-sysroot=/c/mingw810/x86_64-810-posix-seh-rt_v6-rev0/mingw64 --enable-shared --enable-static --disable-multilib --enable-languages=c,c++,fortran,lto --enable-libstdcxx-time=yes --enable-threads=posix --enable-libgomp --enable-libatomic --enable-lto --enable-graphite --enable-checking=release --enable-fully-dynamic-string --enable-version-specific-runtime-libs --disable-libstdcxx-pch --disable-libstdcxx-debug --enable-bootstrap --disable-rpath --disable-win32-registry --disable-nls --disable-werror --disable-symvers --with-gnu-as --with-gnu-ld --with-arch=nocona --with-tune=core2 --with-libiconv --with-system-zlib --with-gmp=/c/mingw810/prerequisites/x86_64-w64-mingw32-static --with-mpfr=/c/mingw810/prerequisites/x86_64-w64-mingw32-static --with-mpc=/c/mingw810/prerequisites/x86_64-w64-mingw32-static --with-isl=/c/mingw810/prerequisites/x86_64-w64-mingw32-static --with-pkgversion='x86_64-posix-seh-rev0, Built by MinGW-W64 project' --with-bugurl=https://sourceforge.net/projects/mingw-w64 CFLAGS='-O2 -pipe -fno-ident -I/c/mingw810/x86_64-810-posix-seh-rt_v6-rev0/mingw64/opt/include -I/c/mingw810/prerequisites/x86_64-zlib-static/include -I/c/mingw810/prerequisites/x86_64-w64-mingw32-static/include' CXXFLAGS='-O2 -pipe -fno-ident -I/c/mingw810/x86_64-810-posix-seh-rt_v6-rev0/mingw64/opt/include -I/c/mingw810/prerequisites/x86_64-zlib-static/include -I/c/mingw810/prerequisites/x86_64-w64-mingw32-static/include' CPPFLAGS=' -I/c/mingw810/x86_64-810-posix-seh-rt_v6-rev0/mingw64/opt/include -I/c/mingw810/prerequisites/x86_64-zlib-static/include -I/c/mingw810/prerequisites/x86_64-w64-mingw32-static/include' LDFLAGS='-pipe -fno-ident -L/c/mingw810/x86_64-810-posix-seh-rt_v6-rev0/mingw64/opt/lib -L/c/mingw810/prerequisites/x86_64-zlib-static/lib -L/c/mingw810/prerequisites/x86_64-w64-mingw32-static/lib '
Thread model: posix
gcc version 8.1.0 (x86_64-posix-seh-rev0, Built by MinGW-W64 project) 
```
It seems they do use the `MinGW-W64` distribution of gcc rather than MinGW installed through chocolatey

**Comment by al-cheb** [comment]
Hello, @SlySven
Thank you for provide info about documenation. I have updated documentation. Could you please take a look if it's good to you - https://github.com/actions/virtual-environments/pull/893?

**Comment by al-cheb** [comment]
PR : https://github.com/actions/virtual-environments/pull/893
