### ISSUE TITLE
Support Ubuntu 20.04 in virtual environments

### ISSUE THREAD

**Issue by cyfrost** [actions/virtual-environments#891]
Hi, the current `ubuntu-latest` points to Ubuntu 18.04 LTS. Since Ubuntu 20.04 LTS is available, can we please add it to the list of supported virtual environments for running github actions on? Thanks!

**Comment by maxim-lobanov** [comment]
Hello @cyfrost , 
We have already started to work on it but unfortunately, can't provide ETA for now.
Please track current progress by #228 .
