### ISSUE TITLE
Add sha256sum to macOS

### ISSUE THREAD

**Issue by ZacSweers** [actions/virtual-environments#90]
**Tool information**
- Tool name: sha256sum
- Add or update? Add
- Desired version: Latest
- Approximate size: 
- If this is an add request:
  - Brief description of tool: 

```
tldr sha256sum

Calculate SHA256 cryptographic checksums.

- Calculate the SHA256 checksum for a file:
    sha256sum filename1

- Calculate SHA256 checksums for multiple files:
    sha256sum filename1 filename2

- Read a file of SHA256 sums and verify all files have matching checksums:
    sha256sum -c filename.sha256
```
  - URL for tool's homepage: https://linux.die.net/man/1/sha256sum

**Virtual environments affected**
- [x] macOS 10.15
- [] Ubuntu 16.04 LTS
- [] Ubuntu 18.04 LTS
- [] Windows Server 2016 R2
- [] Windows Server 2019

**Can this tool be installed during the build?**
It could be installed, but my understanding is that this is normally a standard unix tool.

**Are you willing to submit a PR?**
Possibly! Unclear where this is maintained but can happily take a look if someone could point me in the right direction.

**Comment by ZacSweers** [comment]
Example use case: https://github.com/uber/AutoDispose/pull/403

**Comment by ZacSweers** [comment]
Workaround suggested by @imbsky on the example case above is to `brew install coreutils` first. It does add ~12sec to our build time, so it's not ideal but it is a doable workaround.

```yml
- name: Install coreutils for macOS
  run: brew install coreutils
```

or

```yml
- name: Install coreutils for macOS
  if: matrix.os == 'macOS-latest'
  run: brew install coreutils
```

**Comment by zbeekman** [comment]
@ZacSweers question: Why can't you use macOS' default tool for this? I.e.,

```
shasum -a 256 foo.txt > foo-sha256.txt
shasum -c foo-sha256.txt
```

I admit it is annoying to have to condition your calls to the checksum program by OS, but there is a native tool that ships with the OS (or at least with Xcode) that will do this.

**Comment by ZacSweers** [comment]
Didn’t know about it!

**Comment by zbeekman** [comment]
@ZacSweers If this is a suitable work around for you, I would recommend closing this issue to help the GHA team focus on the most pertinent tasks. But if you still want/need` `sha256sum` then keep it open.

**Comment by codefromthecrypt** [comment]
I would prefer this to be open as it makes build glitch workarounds multiply.

**Comment by jasonm23** [comment]
👍🏽 I just ran into this issue too.  Installing core-utils or alias shasum seems to be a reasonable workaround, but it'd be better if it was just added to the image.

**Comment by oech3** [comment]
Would you add GNU coreutils? I don't `sha256sum`, but the fact that `install -Dm644` does not work on macOS is painful.
