### ISSUE TITLE
Azure Devops Windows images could do with chromedriver updating to 81.0.4044.138

### ISSUE THREAD

**Issue by haymansfield** [actions/virtual-environments#900]
**Describe the bug**
Azure Devops Windows images are using a version of chromedriver which is causing an issue with tests

**Area for Triage**: 

**Question, Bug, or Feature?**: 
Bug/Feature

**Virtual environments affected**
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Expected behavior**
Chrome and chromedriver work together.

**Actual behavior**
An issue occurs with version 81.0.4044.69 of chromedriver with error output this.each is not a .....

I'm having to pull in the update (ChromeDriver 81.0.4044.138) to get the tests to work.

**Comment by maxim-lobanov** [comment]
Hello @haymansfield , currently, we are deploying new image with Chrome driver 81.0.4044.138: https://github.com/actions/virtual-environments/releases/tag/win19%2F20200517.1
It should be deployed this week / early next week.

**Comment by haymansfield** [comment]
@maxim-lobanov Thanks for the update.

**Comment by miketimofeev** [comment]
@haymansfield we've finished with the deployment. I'm going to close the issue. Feel free to open a new one if you have any concerns.
Thank you!
