### ISSUE TITLE
safaridriver returns error

### ISSUE THREAD

**Issue by imbsky** [actions/virtual-environments#91]
**Describe the bug**

Maybe due to a bug in the upstream, safaridriver doesn't working from current version, you will need to update if a new release is already available. I found out about this on @mizchi's article, and when I actually tried it, it doesn't work yet. (Maybe you are more familiar with this issue than me, so please forgive me for pinging you.)

**Virtual environments affected**

- [x] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Expected behavior**

It should work.

**Actual behavior**

(Keep empty cause there is nothing to explain.)

**Comment by raido** [comment]
Safari driver is simply  not enabled (`safaridriver --enable`). But it is not possible to manually enable driver from the job as enabling requires user password.

**Comment by murt** [comment]
I'm able to run `sudo safaridrver --enable` and then start it with `safaridriver -p 0 &` successfully but I still get the "Allow Remote Automation" error.

**Comment by imbsky** [comment]
Changed title.

**Comment by jeffposnick** [comment]
We're running into this issue as well, using a configuration that led to working Safari automation inside Travis CI's Mac environment.

Here's an example GitHub Actions [workflow config](https://github.com/GoogleChrome/workbox/blob/c99b079866f8ae8c8d91c1fc6c9f828af328c493/.github/workflows/main.yml#L48-L52) that seems to do the right things in terms of enabling automation in Safari, but still leads to thee same failures mentioned above:

```
    - run: |
        defaults write com.apple.Safari IncludeDevelopMenu YES
        defaults write com.apple.Safari AllowRemoteAutomation 1
        sudo safaridriver --enable
        safaridriver -p 0 &
```

**Comment by maxim-lobanov** [comment]
Hello, issue is fixed and fix will be deployed with next image rollout

**Comment by mucsi96** [comment]
Great news! 🎉  When can we expect the next image rollout?

**Comment by maxim-lobanov** [comment]
It will happen in a week

**Comment by adadkins** [comment]
@maxim-lobanov Has this been fixed?

**Comment by miketimofeev** [comment]
@imbsky @mucsi96 @adadkins the image has been deployed. Could you check safaridriver, please?

**Comment by adadkins** [comment]
@miketimofeev This is working for me now. Amazing that this was fixed so quickly! It'd be nice if they confirmed it as well.

Is @jeffposnick comment the proper way to enable this(since this is working for me now), or is there a better way?

> ```
>     - run: |
>         defaults write com.apple.Safari IncludeDevelopMenu YES
>         defaults write com.apple.Safari AllowRemoteAutomation 1
>         sudo safaridriver --enable
>         safaridriver -p 0 &
> ```

**Comment by imbsky** [comment]
@adadkins In latest environment, you only need to run `sudo safaridriver--enable`.

**Comment by imbsky** [comment]
This has been fixed in the latest environment and should be closed.

**Comment by imbsky** [comment]
I opened a PR to a Japanese developer's repository, so please check it for details.
https://github.com/mizchi/frontend-gh-action-playground/pull/8
