### ISSUE TITLE
Update/Add CPython 3.9.0 beta 1

### ISSUE THREAD

**Issue by zooba** [actions/virtual-environments#912]
**Tool information**
- Tool name: CPython
- Tool license: Python Software Foundation License
- Add or update? Add
- Desired version: 3.9.0b1 (for CPython, "beta" == "library devs should test with this")
- Approximate size: 

**Area for Triage**:
Python

**Question, Bug, or Feature?**:
Feature

**Virtual environments affected**
- [x] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [x] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [x] Windows Server 2019

(Older Ubuntu and Windows is fine too if it's easier, but I don't consider them blocking.)

**Can this tool be installed during the build?**

Only on Windows via a Nuget package. You can build from source during build for other platforms, which I assume only takes 3-4 minutes (based on our CI running on the same images).

**Tool installation time in runtime**
Should be under 1 minute

**Are you willing to submit a PR?**
Sure! Though hopefully this is fairly mechanical, since there's very little difference between how 3.8 is treated and how 3.9 should be treated.

**Comment by konradpabjan** [comment]
Since this is an in-development version of Python, I would put this under the same issue: https://github.com/actions/setup-python/issues/20

The `v2` version of `setup-python` can now JIT download and install specific versions of Python from the [actions/python-versions](https://github.com/actions/python-versions) repo so ideally we should add all in-development versions there.

**Comment by maxim-lobanov** [comment]
@zooba , as a possible solution, you can build Python 3.9.0 once and cache it using https://github.com/actions/cache. Restoring from cache will take seconds after first build

**Comment by zooba** [comment]
@maxim-lobanov I work on CPython itself - I don't need the solution. I'm filing it because _everyone else_ needs it, and someone needs to raise the notification that 3.9.0 beta _3_ is now out.

**Comment by alepauly** [comment]
@konradpabjan @maxim-lobanov I think it makes sense to support latest pre-release via `setup-python`.

**Comment by jadchaar** [comment]
[Beta 5 is scheduled for release on July 20](https://www.python.org/dev/peps/pep-0596/), so it would be great if this could come soon so we can begin testing our packages on GH actions. Thanks for the hard work!

Ideally it would be cool to just generally support the latest nightly like Alejandro hinted above.

**Comment by maxim-lobanov** [comment]
Hello @jadchaar ,
We are working on this request right now. We are not planning to pre-cache pre-release versions on image but they will be available for installation on-flight via [actions/setup-python](https://github.com/actions/setup-python) with minor latency (15-20 seconds). I think we will finish this request in a week (we have to rework some internal logic to support it).

**Comment by The-Compiler** [comment]
With https://github.com/actions/setup-python/issues/20#issuecomment-660026867 I suppose this can be closed? (cc @konradpabjan)

**Comment by maxim-lobanov** [comment]
Yep, Python 3.9.0 beta 4 is available with latest release of `actions/setup-python`. Please find details on https://github.com/actions/setup-python/issues/20#issuecomment-660026867

**Comment by sco1** [comment]
Will this also come to the Azure environments?

**Comment by mattip** [comment]
How do I use actions/setup-python on Azure pipelines? Or is there another way to activate 3.9 on the Azure images?

**Comment by maxim-lobanov** [comment]
@mattip , as far as I know, no way for Azure Pipelines.
`actions/setup-python` can download versions on-flight and download 3.9.
AzDO [UsePython](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/tool/use-python-version?view=azure-devops) task can't do that. I have logged issue for that some time ago: https://github.com/microsoft/azure-pipelines-tasks/issues/13319
But looks like it is not implemented yet.
