### ISSUE TITLE
Random IO failures during nightly actions

### ISSUE THREAD

**Issue by sixlettervariables** [actions/virtual-environments#915]
**Describe the bug**
We receive random IO failures on a nightly matrix job that runs a build across two JDK versions on both Windows and Linux. The failures are always during an IO operation and vary which JDK and OS depending on the night.

**Area for Triage**: 

**Question, Bug, or Feature?**: 
Bug

**Virtual environments affected**
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [X] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [X] Windows Server 2019

**Expected behavior**
Consistent IO performance when executing workflow.

**Actual behavior**
From [MekHQ's repo](
https://github.com/MegaMek/mekhq/actions?query=workflow%3A%22MekHQ+Nightly+CI%22), 3 of the last 5 nightlies have failed:
- https://github.com/MegaMek/mekhq/actions/runs/109858317
    - ubuntu-latest JDK8 is the only failure with File Not Found: `> Directory '/home/runner/work/mekhq/mekhq/megamek/megamek/build/resources/main' specified for property '$2' does not exist.`
- https://github.com/MegaMek/mekhq/actions/runs/106916147
    - ubuntu-latest JDK8 failed with File Not Found: `Could not set UNIX mode on /home/runner/work/mekhq/mekhq/megamek/megamek/build/resources/main/megamek/client/bot/messages_ru.properties: could not chmod file (errno 2: No such file or directory)`
    - windows-latest JDK8 failed for two reasons:
        - `> Couldn't read file content: 'D:\a\mekhq\mekhq\megamek\megamek\build\resources\main\megamek\MegaMek.properties'.`
        - `> java.io.IOException: Unable to delete directory D:\a\mekhq\mekhq\megamek\megamek\build\resources\main\megamek\client.`
- https://github.com/MegaMek/mekhq/runs/669049985
    - windows-latest JDK11 failed: `> java.io.IOException: Unable to delete directory D:\a\mekhq\mekhq\megamek\megamek\build\resources\main\megamek\common\templates\tro`

From [MegaMekLab's repo](https://github.com/MegaMek/megameklab/actions?query=workflow%3A%22MegaMekLab+Nightly+CI%22), we have fewer failures:
- https://github.com/MegaMek/megameklab/actions/runs/108718941
    - ubuntu-latest JDK11 failure to copy a file because: `Could not set UNIX mode on /home/runner/work/megameklab/megameklab/megamek/megamek/build/resources/main/megamek/common/options/messages_ru.properties: could not chmod file (errno 2: No such file or directory)`
    - windows-latest JDK8 failure to delete a directory: `Unable to delete directory D:\a\megameklab\megameklab\megamek\megamek\build\resources\main\megamek\client`
- https://github.com/MegaMek/megameklab/runs/681764139
    - ubuntu-latest JDK11 failure to copy a file because: `Could not set file mode 644 on '/home/runner/work/megameklab/megameklab/megamek/megamek/build/resources/main/megamek/common/equipmentmessages_de.properties'`

Both of those repos depend on the MegaMek repo, and include its source when performing the nightly job. Looking at it as the common problem was my first step, however...

From [MegaMek's repo](https://github.com/MegaMek/megamek/actions?query=workflow%3A%22MegaMek+Nightly+CI%22), we find it is remarkably stable, with only one recent failure which is unrelated:
- ubuntu-latest JDK8: Could not download a dependency due to a transient network failure

**Comment by dmitry-shibanov** [comment]
Hello @sixlettervariables , thank you for your response. We investigated the issue about random failures and my concerns about it that it's the issue related to gradle. We have a banch of gradle tests and they pass. Also as my research your issues are similar to this:
1. For deleting - https://github.com/gradle/gradle/issues/9813
2. For permissions - https://github.com/gradle/gradle/issues/1245

Do you have some small project with repro of this issue for further investigation?

**Comment by sixlettervariables** [comment]
We're on Gradle 4.9 so the first doesn't apply, and the second fails due to permissions rather than not finding the file.

This feels more like an underlying container issue as Java itself reports the missing files yet they are certainly there.

**Comment by dmitry-shibanov** [comment]
I don't think underlying container issue because we have never had similar reports. So I believe it's something related to your specific project configuration. 
As for the gradle issues that I have shared above:
1. Based of the logs of your builds you use gradle 5.6 (so the first can be applied)
![image](https://user-images.githubusercontent.com/28229110/83255987-3695d700-a1ba-11ea-8d09-9a0b9ac5c747.png)

2. The second permissions issue looks pretty similar to the logs you shared.

Also I tested project in our ci with docker and it fails too. https://github.com/dmitry-shibanov/mekhq/runs/719810866?check_suite_focus=true
Is it possible to provide minimum repro steps project for this issue?

**Comment by dmitry-shibanov** [comment]
Also I have run your repository code in docker container and faced the same issue: https://github.com/dmitry-shibanov/mekhq/runs/719810866?check_suite_focus=true

**Comment by sixlettervariables** [comment]
Interesting, we've never run into this on a local machine (Windows, Mac OS, and Linux).

**Comment by sixlettervariables** [comment]
After debugging this yesterday I noticed our CI jobs which run for PRs have never encountered an error like this and is functionally identical as far as Gradle is concerned, just we don't run a matrix build.

How does GH Actions handle matrix builds differently so that I can take a look at that?

**Comment by dmitry-shibanov** [comment]
We are not super familiar with matrix runs but as far as I know it works pretty same like other builds, it just replace variables with values defined in matrix

**Comment by dmitry-shibanov** [comment]
Hello @sixlettervariables , Please let me know if you still need any help with this issue.

**Comment by dmitry-shibanov** [comment]
We are closing the issue, if you have any concerns feel free to reopen the issue.
