### ISSUE TITLE
Is GHC and cabal-install now pre-installed on windows images?

### ISSUE THREAD

**Issue by phadej** [actions/virtual-environments#919]
**Describe the bug**

Starting today I see failures like:

```
Run choco install -y ghc --version 8.6.5
Chocolatey v0.10.15
Installing the following packages:
ghc
By installing you accept licenses for the packages.
A newer version of ghc (v8.10.1) is already installed.
 Use --allow-downgrade or --force to attempt to install older versions, or use side by side to allow multiple versions.

Chocolatey installed 0/1 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Failures
 - ghc - A newer version of ghc (v8.10.1) is already installed.
 Use --allow-downgrade or --force to attempt to install older versions, or use side by side to allow multiple versions.
```

- Example job: https://github.com/haskell/cabal/runs/696423815
- https://github.com/haskell/cabal/pull/6829/checks?check_run_id=696535334

**Area for Triage**: 

**Question, Bug, or Feature?**: 

**Virtual environments affected**
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [x] Windows Server 2019

**Expected behavior**

I think this failure is expected **if** GHC and cabal-install are pre-installed, but I see no Haskell related changes in Windows images on release page.

**Comment by maxim-lobanov** [comment]
Hello @phadej , exactly.

Recently, we have installed ghc and cabal on Windows images in scope of #645 .
We are planning to keep 3 latest ghc versions (the latest one as default) on image and latest cabal version.

**Comment by phadej** [comment]
@maxim-lobanov It's great to hear that you consider Haskell stuff worth having in the default images.

Yet because there are no indication of GHC / cabal-install in releases or https://github.com/actions/virtual-environments/blob/master/images/win/Windows2019-Readme.md I'm unhappy. Could you priorize the https://github.com/actions/virtual-environments/issues/644 issue. It's not fun to play detective when CI suddenly breaks. Ironically, the `cabal-install` CI.

**Comment by maxim-lobanov** [comment]
Actually, the latest pre-release contains both ghc and cabal in software report: https://github.com/actions/virtual-environments/releases/tag/win19%2F20200517.1
This pre-release will become release as soon as deployment is finished.
Anyway, I agree that current release description is not clear to determine difference between old and new software set. We have the nearest plan to fix it.

I am closing this issue. Feel free to reopen if any questions

**Comment by phadej** [comment]
I guess I was looking for Haskell, and didn't find it on that page.
