### ISSUE TITLE
Add doxygen

### ISSUE THREAD

**Issue by subalterngames** [actions/virtual-environments#92]
**Tool information**
- Tool name: doxygen
- Add or update? Add
- Desired version: latest
- Approximate size: 
- If this is an add request:
  - Brief description of tool:  Documentation system for C, C++, Java, Python and other languages
  - URL for tool's homepage: http://www.doxygen.nl/

**Virtual environments affected**
- [ ] macOS 10.15
- [x] Ubuntu 16.04 LTS
- [x] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Can this tool be installed during the build?**
I don't think so; it's available via apt.

**Are you willing to submit a PR?**
Yes, but I'm not sure how.

**Comment by maxim-lobanov** [comment]
The tool can be installed in runtime using the following script:
```
sudo apt-get install -y doxygen
```
Installation takes about 7 seconds

**Comment by alepauly** [comment]
@subalterngames Considering that the on-demand install is pretty quick, we won't add this to the image. Thanks for the suggestion (and sorry it took me forever to look into it)

**Comment by cadop** [comment]
@alepauly  What about for windows?

**Comment by miketimofeev** [comment]
@cadop you can download and extract these binaries for windows in a few seconds https://www.doxygen.nl/files/doxygen-1.9.4.windows.x64.bin.zip

**Comment by cadop** [comment]
@miketimofeev Can you provide the commands to do the install and add to path so its available for others also looking?

**Comment by miketimofeev** [comment]
@cadop not the most elegant solution as it's not recommended to use system directories but should work
```
$url = "https://www.doxygen.nl/files/doxygen-1.9.4.windows.x64.bin.zip"
Start-DownloadWithRetry -Url $url -Name "doxygen.zip" -DownloadPath "C:\"
Extract-7Zip -Path  "C:\doxygen.zip" -DestinationPath "C:\windows\system32"
doxygen --version
```
