### ISSUE TITLE
Update/Add LLVM

### ISSUE THREAD

**Issue by zufuliu** [actions/virtual-environments#921]
**Tool information**
- Tool name: LLVM
- Tool license: Apache License v2.0 with LLVM Exceptions
- Add or update? Add
- Desired version: latest, current 10.0, 10.0.1 soon
- Approximate size: 10.0: 160 MiB download size, 1.5 GiB installation size; 10.0.1 rc1: 228 MiB download size, 1.83 GiB installation size
- If this is an add request:
  - Brief description of tool: LLVM compiler suite
  - URL for tool's homepage: http://llvm.org/ https://github.com/llvm/llvm-project/releases

**Area for Triage**:

C/C++

**Question, Bug, or Feature?**:

Feature

**Virtual environments affected**
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [x] Windows Server 2019

**Can this tool be installed during the build?**
Yes, it's a NSIS installer. brief steps (not tried):
1. download the installer, https://github.com/llvm/llvm-project/releases/download/llvmorg-10.0.0/LLVM-10.0.0-win64.exe
2. silent install with `LLVM-10.0.0-win64.exe /S`

**Tool installation time in runtime**
Not yet tried.

**Are you willing to submit a PR?**
Will try.

**Comment by zufuliu** [comment]
now I use following command to install LLVM 10.0, it takes about 1 minute:

https://github.com/zufuliu/notepad2/runs/701136763?check_suite_focus=true#step:3:2
```
curl -Ls -o "LLVM-10.0.0-win64.exe" "https://github.com/llvm/llvm-project/releases/download/llvmorg-10.0.0/LLVM-10.0.0-win64.exe"
LLVM-10.0.0-win64.exe /S
```

**Comment by alepauly** [comment]
Hi @zufuliu, thanks for reaching out with your suggestion. Considering the popularity of LLVM and concerns over maintenance we won't bake it into the image.
