### ISSUE TITLE
EXDEV: cross-device link not permitted

### ISSUE THREAD

**Issue by BrightRan** [actions/virtual-environments#922]
In [this Community Forum ticket](https://github.community/t5/GitHub-Actions/EXDEV-cross-device-link-not-permitted/td-p/59390), some users report that recently their workflows run failed with the following error message:
```
##[error]EXDEV: cross-device link not permitted, ...
```
The workflows could work fine before.

**Comment by al-cheb** [comment]
Hello, @BrightRan 
Thank you for providing information about the issue . We are currently working on the fix and planning to deploy fix soon.

**Comment by miketimofeev** [comment]
We have finished the rollback on Friday.
