### ISSUE TITLE
Provide a minimal Windows (and why not other platform) images.

### ISSUE THREAD

**Issue by phadej** [actions/virtual-environments#923]
There are special use-cases (like `cabal-install` CI), where setting up the environment from clean-ish state feels easier than trying to dodge interactions with all installed (and ever increasing?) stuff.

**Comment by MSP-Greg** [comment]
Interesting idea.

In the past I did have AppVeyor scripts where PATH was totally reset, which essentially removes issues with interactions.  I've also written several Actions scripts filled with `where` commands to find conflicts...

One issue is what is 'minimal Windows'?  Should actions work (node.js in PATH)?  Maybe some custom actions exec out to other tools?  Should Visual Studio be installed, and what add-ons for it?

One option might be to have a MIN_PATH variable that would contain only what is required for the runner and standard actions.  Users could then add the tools/services that they needed?

Or, maybe a workflow job setting that starts the system with the minimal PATH?

**Comment by phadej** [comment]
Resetting Path to something minimal would work too. 

The is ::add-path:: command, but no remove, nor clear. I’m not sure if ::set-env:: works on Windows for Path.

Because chocolatey is not licensed on GitHub arvionsa, we cannot use installationdir flag, to install somewhere else and not care about existing installations. That complicates things too ( forces us to uninstall/reinstall if versions are wrong,
).

**Comment by MSP-Greg** [comment]
> forces us to uninstall/reinstall if versions are wrong

Sometimes renaming the old then reinstall works (and is faster than uninstall), but for things like MSYS2/MinGW packages, rename doesn't work, e.g. some old Rubies that are used in CI use OpenSSL 1.0.2, and one has to uninstall 1.1.1, as it's spread across several folders...

Ignoring issues with EOL.

**Comment by maxim-lobanov** [comment]
Thank you for your proposal and feedback.

Just a quick solution while we are evaluating the initial request:
1) The following  step can be used to clean path: 
```
- run: |
    Write-Host '::set-env name=PATH::'
```
2) Special function to remove one path from PATH:
```
function RemoveFrom-Path ($pathToRemove) {
    $parts = $env:PATH.Split(";") | Where-Object { $_ -ne $pathToRemove }
    $newPATH = [string]::Join(";", $parts)
    $env:PATH = $newPATH
    Write-Host "::set-env name=PATH::$newPATH"
}
RemoveFrom-Path "C:\vcpkg"
```

**Comment by nulano** [comment]
Another option would be to run everything in a Windows docker container instead. I think the preloaded `mcr.microsoft.com/windows/servercore:ltsc2016` could be a good candidate for you.

**Comment by alepauly** [comment]
Hi @phadej, different images and more flavors of existing images is something we're always considering. Unfortunately it is not possible for us to provide a minimal Windows image as you suggest at this time. 

If there are ways where we can build the existing environment in a way that it's easier to make it appear clean as a workaround, I would be in favor of reviewing changes to the images that you think could help with this. Thanks for reaching out. I'll close this but please let me know if you have any questions.
