### ISSUE TITLE
Interactive way to debug build issues.

### ISSUE THREAD

**Issue by phadej** [actions/virtual-environments#924]
Either a ssh or remote desktop (or VirtualBox images) would be great to have.

Debugging CI environment issues via triggering new jobs simply takes too much time. I'm tempted to go for the "easiest", not the "correct" solution.

There seems to be hacks like https://github.com/nelsonjchen/reverse-rdp-windows-github-actions, but I rather not rely on them either.

**Comment by chrpai** [comment]
Is there a way to download the image to throw on Hyper-V or provision an Azure VM using the image?  I have an issue with a tool that I install during the build that works on my machine but not the hosted machine and I need a way to troubleshoot the missing dependencies.

**Comment by maxim-lobanov** [comment]
@chrpai , probably, some action like https://github.com/marketplace/actions/create-a-desktop-screenshot can be good option here. It allows to get screenshot of screen and it helps to understand where installation stucks

**Comment by thejoebourneidentity** [comment]
Thanks @phadej for the feedback. This is definitely something we're considering and want to deliver. The earliest will be next year. Stay tuned for roadmap updates from GitHub about things like this.

**Comment by brphelps** [comment]
@thejoebourneidentity  is there a way to run the images locally as @chrpai mentioned above? This would a long ways to helping understand what's going on. I'm currently debugging a test failure that's failing exclusively in an ubuntu-latest image and I can't get it to repro in 18.04 LTS.

**Comment by thejoebourneidentity** [comment]
Right now we don't have our pre-generated images available for download, but we're working on making that available. In the meantime, you can follow the instructions here to generate your own version of the images using this repo. https://github.com/actions/virtual-environments/blob/main/help/CreateImageAndAzureResources.md

**Comment by amenk** [comment]
Does this work https://github.com/marketplace/actions/debugging-with-tmate ?

**Comment by miketimofeev** [comment]
There are no official ways to interactively debug the build.
If there is any it will be announced in the GitHub blog.
