### ISSUE TITLE
EXDEV: cross-device link not permitted

### ISSUE THREAD

**Issue by tamalsaha** [actions/virtual-environments#927]
**Describe the bug**
Since yesterday, I have started seeing `EXDEV: cross-device link not permitted` error. Example:

**Area for Triage**: Npm

**Question, Bug, or Feature?**: Bug

**Virtual environments affected**
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [x] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Expected behavior**
A description of what you expected to happen.

It was working before.

**Actual behavior**
A description with steps to reproduce the issue. If your have a public example or repo to share,
please provide the link.

1. Step 1
2. Step 2

**Comment by maxim-lobanov** [comment]
Hello @tamalsaha , it is known issue and we are working to rollback breaking change.
Closing as duplicate: #922
