### ISSUE TITLE
Add WLAN AutoConfig service for Windows image

### ISSUE THREAD

**Issue by oHTGo** [actions/virtual-environments#9305]
### Tool name

WLAN AutoConfig service (wlansvc)

### Tool license

none

### Add or update?

- [X] Add
- [ ] Update

### Desired version

latest

### Brief description of tool

Wlansvc is a service of Windows OS. It is currently not enabled on Windows servers by default, it supports software that needs to use WLAN such as Cloudflare WARP.

### URL for tool's homepage

https://learn.microsoft.com/en-us/windows-server/networking/technologies/wlan/wireless-networking

### Provide a basic test case to validate the tool's functionality.

```bash
Check wlansvc has been started or not
```

### Platforms where you need the tool

- [ ] Azure DevOps
- [X] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [X] Windows Server 2019
- [X] Windows Server 2022

### Can this tool be installed during the build?

```bash
I'm not sure about this question. I tested on a self-hosted runner on a Windows server. I must add the Windows feature, restart the OS, and start the service via PowerShell.
```

### Tool installation time in runtime

2 - 3 minutes

**Comment by MaksimZhukov** [comment]
Hello @oHTGo!
We will consider enabling the Wlansvc service and will contact you as soon as we have any updates!

**Comment by Kichura** [comment]
Is the wired autoconfig enabled by default in the windows-2022 runner or is it disabled too?

**Comment by oHTGo** [comment]
@Kichura, wired autoconfig is different from wlan autoconfig. I tried enabling wlan autoconfig in GitHub hosted Windows runner but need to reboot

**Comment by Kichura** [comment]
> @Kichura, wired autoconfig is different from wlan autoconfig. I tried enabling wlan autoconfig in GitHub hosted Windows runner but need to reboot

I rather wanna ask it anyways in case this does get missed, although i do approve that wlan autoconfig should be considered upon since having it be disabled can cause specific test programs to fail.

**Comment by oHTGo** [comment]
Can you assign me for this issue? @mikhailkoliada 
I think we just add this feature to the toolset and start it when the application needs it.

**Comment by mikhailkoliada** [comment]
rolled
