### ISSUE TITLE
Update/Add Java SDK to latest version (at least version 11)

### ISSUE THREAD

**Issue by parrainc** [actions/virtual-environments#938]
**Tool information**
- Tool name: Java SDK
- Tool license:
- Add or update? Update
- Desired version: v11 (or latest)
- Approximate size:

**Area for Triage**:
Java

**Question, Bug, or Feature?**:
Feature

**Virtual environments affected**
- [ ] macOS 10.15
- [x] Ubuntu 16.04 LTS
- [x] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Can this tool be installed during the build?**
not sure

**Tool installation time in runtime**
N/A

**Are you willing to submit a PR?**
Sure

**Comment by parrainc** [comment]
I found this during a sonar analysis in our build pipelines. We got a warning message like this:
`##[warning]14:38:44.377 WARN: The version of Java (1.8.0_252) you have used to run this analysis is deprecated and we will stop accepting it from October 2020. Please update to at least Java 11.`

So, it would be good if that java sdk version is updated to at least version 11 or the latest.

**Comment by maxim-lobanov** [comment]
Java 11 is already installed on Ubuntu images and available via `JAVA_HOME_11_X64` environment variable.

The following versions are installed:
- 7 (openjdk version "1.7.0_262")
- 8 (openjdk version "1.8.0_252") (default)
- 11 (openjdk version "11.0.7" 2020-04-14 LTS)
- 12 (openjdk version "12.0.2" 2019-07-16)

One more convenient way to switch Java is [actions/setup-java](https://github.com/actions/setup-java) task.

**Comment by parrainc** [comment]
Any solution for azure pipelines?

**Comment by maxim-lobanov** [comment]
There is the same task for AzDO: [Java tool installer](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/tool/java-tool-installer?view=azure-devops).

**Comment by parrainc** [comment]
Got it, looks like sonar task is looking for JAVA_HOME var and since the default is 1.8.x that's why the warning. I'll see if I can override it with the one you listed above or use the java tool task.

Thanks, @maxim-lobanov

**Comment by maxim-lobanov** [comment]
If you need to override JAVA_HOME variable, the following step will work for you:
```
- bash: |
    echo "##vso[task.setvariable variable=JAVA_HOME]$JAVA_HOME_11_X64"
```
It will work faster than task.

**Comment by parrainc** [comment]
Yeah, I did something similar to that. The task looks cool, but I think there are too many params we need to pass through.

Anyway, things are working great. No warnings!
