### ISSUE TITLE
Add AWS SAM CLI

### ISSUE THREAD

**Issue by MichalMiko** [actions/virtual-environments#94]
**Tool information**
- Tool name: AWS SAM CLI
- Add or update? Add
- Desired version: latest
- Approximate size: 500kB
- If this is an add request:
  - Brief description of tool: AWS SAM provides you with a command line tool, the AWS SAM CLI, that makes it easy for you to create and manage serverless applications
  - URL for tool's homepage: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-install.html

**Virtual environments affected**
- [x] macOS 10.15
- [x] Ubuntu 16.04 LTS
- [x] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Can this tool be installed during the build?**
Yes, using:
`$ pip install aws-sam-cli`

But it can take some time, it requires: Flask, boto3, aws-lambda-builders, chevron, aws-sam-translator, pywin32, docker, cookiecutter, PyYAML, click, serverlessrepo, jmespath, requests, python-dateutil, dateparser 

**Are you willing to submit a PR?**
Of course ;)

**Comment by maxim-lobanov** [comment]
The fastest way to install AWS SAM CLI in runtime:
```
# macOS
brew tap aws/tap
brew install aws-sam-cli
# Ubuntu
pip install aws-sam-cli
```
Installation takes about 20 seconds

**Comment by alepauly** [comment]
We should also install it on Windows images if it makes sense.

**Comment by alnaranjo** [comment]
+1

**Comment by dsame** [comment]
Linux PR https://github.com/actions/virtual-environments/pull/615

**Comment by AlenaSviridenko** [comment]
Images with AWS SAM CLI were deployed, closing this issue. 
Please, feel free to contact up if needed.
