### ISSUE TITLE
Add cdb.exe

### ISSUE THREAD

**Issue by nibanks** [actions/virtual-environments#942]
**Tool information**
- Tool name: CDB.exe
- Tool license: Windows SDK license
- Add or update? Add
- Desired version: Latest
- Approximate size:
- If this is an add request:
  - Brief description of tool: Windows command line debugger
  - URL for tool's homepage: https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/

**Area for Triage**:

**Question, Bug, or Feature?**:
Having this installed will allow for automated crash dump processing directly on the build/test machine.

**Virtual environments affected**
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [x] Windows Server 2019

**Can this tool be installed during the build?**
I don't know

**Tool installation time in runtime**
I don't know

**Are you willing to submit a PR?**
No

**Comment by Darleev** [comment]
Hello, @nibanks.
It seems debugger tools are already installed on the windows images. You can use cdb tools using the full path:

```
C:\Program Files (x86)\Windows Kits\10\Debuggers\x64\cdb.exe
C:\Program Files (x86)\Windows Kits\10\Debuggers\x32\cdb.exe
```
We will consider adding debugger tools to PATH variable.

**Comment by Darleev** [comment]
@nibanks Currently, we are not planning to add debugging tools to PATH on Windows images, therefore I can suggest the following way to work with debugging tools:

```
- name: Add debugger to the Path
  run: echo "::add-path::c:\Program Files (x86)\Windows Kits\10\Debuggers\x64"
- name: cdb
  run: cdb.exe -version
```
In case of another architecture is required you can just change the path to the required one.

If additional information or assistance is required, do not hesitate to contact us.

**Comment by nibanks** [comment]
@Darleev can I ask why you don't want to add it to the path?

**Comment by Darleev** [comment]
@nibanks we are not planning to add debugger tools to the path, because "C:\Program Files (x86)\Windows Kits\10\Debuggers\x64" path contains tools which were installed in scope of other packages and such solution can re-write them. It can lead to unpredictable impact for other users.

**Comment by nibanks** [comment]
@Darleev Ok. Thanks for the explanation. I will try to update things on my side to add it to PATH myself. Feel free to close this issue.

**Comment by Darleev** [comment]
@nibanks if additional assistance is required from our side, please let us know, we will be glad to assist you further.

**Comment by ThadHouse** [comment]
Is `echo "::add-path::c:\Program Files (x86)\Windows Kits\10\Debuggers\x64"` a special shortcut in Azure? Trying to run it from inside a powershell script and it doesn't seem to propagate the path to subsequent steps. Also tried updating the registry based PATH from our script, and that doesn't seem to propagate either.

**Comment by maxim-lobanov** [comment]
For GitHub Actions:
```
echo "::add-path::c:\Program Files (x86)\Windows Kits\10\Debuggers\x64"
```
For Azure DevOps: ([Link](https://docs.microsoft.com/en-us/azure/devops/pipelines/scripts/logging-commands?view=azure-devops&tabs=bash#prependpath-prepend-a-path-to-the--path-environment-variable))
```
echo "##vso[task.prependpath]c:\Program Files (x86)\Windows Kits\10\Debuggers\x64"
```

**Comment by thhous-msft** [comment]
@Darleev It looks like cdb was removed from the Windows-2022 images. Can we get this reopened to investigate that? Or should I create a new issue?

**Comment by miketimofeev** [comment]
@ThadHouse cdb in included in the win-2019 image as a part of the WDK bundle. As WDK is not available for win-2022 yet there is no cdb.

**Comment by ax3l** [comment]
Any update on this for the latest images? :)
We really need to debug things in runners from time to time, such as DLL load issues.
