### ISSUE TITLE
Unable to create "Excel.Application" COM object

### ISSUE THREAD

**Issue by AntonioCuravalea-IIS** [actions/virtual-environments#9452]
### Description

Up until yesterday, my workflows were able to create "Excel.Application" COM objects (via Python with the `win32com` package, but also via VBScript). Suddenly, today, any attempt to do so results in an "Invalid class string" error.

After some searching I realized the runners never came with Excel installed, but it seems something else provided the COM class and my scripts were able to work. I do see that `Microsoft.VisualStudio.Workload.Office` is installed, but I have no idea if it has anything to do with this.

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [X] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [X] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

 Image: windows-2022
 Version: 20240225.2.0

### Is it regression?

Version: 20240225.2.0

### Expected behavior

The `Excel.Application` COM object should be available.

### Actual behavior

The `Excel.Application` COM object is no longer available.

### Repro steps

I tried running these test code snippets in a GitHub Actions workflow:

Python:
```python
from win32com.client import Dispatch

newMdd = Dispatch("Excel.Application")
newMdd.Quit()
```

VBScript:
```vbscript
dim xlApp
Set xlApp = CreateObject("Excel.Application")
xlApp.Quit()
```

**Comment by erik-bershel** [comment]
Hello @AntonioCuravalea-IIS ! 
According to the description, the problem does not quite look like an image bug - there were no updates yesterday. This looks more like dependency or configuration problem of the exact project. Please provide links to the last successful build and the first unsuccessful build, regardless of whether they were executed in a public or private repository.

**Comment by AntonioCuravalea-IIS** [comment]
Hello,

Last successful: https://github.com/Ipsos-ITCompetence/innotest_builder/actions/runs/8138236888
First failed: https://github.com/Ipsos-ITCompetence/innotest_builder/actions/runs/8155638773

I did find a solution though - installing `office365business` via Chocolatey solves the issue. It adds 6 minutes to the total runtime, but I think we're fine with that.
