### ISSUE TITLE
Ubuntu 16.04 Image 20200525.2 - has broken azure-cli

### ISSUE THREAD

**Issue by rebecca-makar** [actions/virtual-environments#948]
**Describe the bug**
Azure Devops microsoft hosted image for ubuntu 16.04 was running 20200525.2 this morning.
Last night it was running 20200517.1 - everything was passing fine. 

20200525.2 I believe has a breaking change for az-cli: https://github.com/Azure/azure-devops-cli-extension/issues/1004

I am guessing 20200525.2 is most likely running: azure-cli (2.6.0) - confirmed it is running https://github.com/actions/virtual-environments/blob/releases/ubuntu16/20200525/images/linux/Ubuntu1604-README.md

So if a user has in their pipeline automation anything with az, I think it is going to fail on the new image: 20200525.2

**Question, Bug, or Feature?**: 
Bug
**Virtual environments affected**
- [ ] macOS 10.15
- [X] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Expected behavior**
Does not fail: 
```
Agent name: 'Azure Pipelines 48'
Agent machine name: 'fv-az623'
Current agent version: '2.168.2'
Operating System
Virtual Environment
Current image version: '20200525.2'
```

```
Unable to use secure credential store in this environment.
Please refer to alternate methods at https://aka.ms/azure-devops-cli-auth
using Environment variable
or use 'az login'
_run_pip() missing 1 required positional argument: 'extension_path'
Unable to use secure credential store in this environment.
Please refer to alternate methods at https://aka.ms/azure-devops-cli-auth
using Environment variable
or use 'az login'
_run_pip() missing 1 required positional argument: 'extension_path'
```

**Comment by dibir-magomedsaygitov** [comment]
Hello, **@rebecca-makar**.
It seems you are right and azure-cli currently is broken. In order to mitigate the issue I can suggest the following steps:
**For Ubuntu**: `sudo apt-get install -y --allow-downgrades azure-cli=2.5.1-1~xenial`
**For Windows:** `choco install azure-cli --version=2.5.1 --allow-downgrade`

We will keep you informed about the status of this issue.

**Comment by miketimofeev** [comment]
Filed a bug in azure-cli repo
https://github.com/Azure/azure-cli/issues/13706

**Comment by alepauly** [comment]
Incoming fix: https://github.com/Azure/azure-cli/pull/13716

**Comment by miketimofeev** [comment]
We'll rollback azure-cli to 2.5.1 on the next image rollout that is supposed to be started on Monday

**Comment by sanghamanvir13** [comment]
@miketimofeev for Windows image 2.5.1 will cause an issue (https://github.com/Azure/azure-cli/issues/13373), windows image should use latest cli version

**Comment by miketimofeev** [comment]
@sanghamanvir13 we've decided to stay on 2.5.1 because we haven't heard any complaints about that version so far and it's presented on the latest win19 release for 2 weeks
https://github.com/actions/virtual-environments/releases/tag/win19%2F20200517.1

**Comment by dibir-magomedsaygitov** [comment]
Hello!
We have successfully rolled back azure-cli to 2.5.1 version. I'm going to close the issue, feel free to contact us if you have any concerns.
Thank you!
