### ISSUE TITLE
Xcode code signing is extremely slow

### ISSUE THREAD

**Issue by JacobWrenn** [actions/virtual-environments#949]
**Describe the bug**
Xcode code signing is extremely slow. I have tested a build of my iOS app without code signing to verify that this is what is causing the extremely slow speed.

**Virtual environments affected**
- macOS 10.15

**Expected behavior**
Xcode signs code at the normal speed.

**Actual behavior**
Xcode signs code so slowly you can't tell if it is stuck or just ridiculously slow.

1. Build an iOS app with a tool like Fastlane or the Xcode command line tools
2. Watch as it takes an extremely long time to complete

**Comment by Darleev** [comment]
Hello @JacobWrenn,
Could you please provide an example(public repo, steps to reproduce etc.) to speed the investigation? Did the problem reproduce on older versions?
We are looking forward to your reply.

**Comment by JacobWrenn** [comment]
Hi @Darleev thanks for your reply. I'm going to close the issue because I was unable to recreate the problem.

I'm going to assume that at the time I first observed this issue it was a busy period so a minimal amount of compute power was being assigned to my action.

**Comment by JacobWrenn** [comment]
Reopening because I've just had an Xcode build currently running for over 40 minutes at time of writing. I'm going to try and recreate because something is definitely not right for this to keep happening.

**Comment by Darleev** [comment]
@JacobWrenn can you please provide the time for which the build is usually going? Also, to investigate the behavior you have mentioned, steps to reproduce are required.
We are looking forward to hear from you.

**Comment by JacobWrenn** [comment]
Hi @Darleev thanks for replying. I've opened a public repo here https://github.com/JacobWrenn/test-xcode with a basic example of building an iOS app using actions. In terms of timing on my private repo I had a broken build at 3pm, one at 4pm that worked and another broken at 5pm.

**Comment by JacobWrenn** [comment]
I also want to note that my private repo is using flutter and a custom script to install profiles. In my example repo, it is using Swift and Fastlane but still suffers from the same issue.

**Comment by JacobWrenn** [comment]
Looks like I've found the perfect solution on the community forum https://github.community/t/ios-build-stuck-while-unable-to-check-log/16557 Running a Fastlane action intended for Travis CI doesn't seem like it should work but it seems to be fine

**Comment by Darleev** [comment]
@JacobWrenn thank you for the provided details and the investigation.
Did you try to apply the solution described in the topic? Does it help? I see that currently build itself is pretty fast.

**Comment by JacobWrenn** [comment]
@Darleev yes I tried the solution and it worked very well. Those fast builds started happening as soon as I applied the change. It does occur to me that some documentation and samples from GitHub would be nice so that others trying to set up iOS apps on actions don't run into similar issues.

**Comment by Darleev** [comment]
@JacobWrenn Thanks for the clarification and contribution to improving the product. I think it would be great if such information will appear in [a starter kit ](https://github.com/actions/starter-workflows). You can improve documentation for users who started to use Xcode for the first time by creating a pull request/issue in the repository provided.
If you have any questions, feel free to contact us.

**Comment by JacobWrenn** [comment]
Thanks I'll take a look.

**Comment by gustafnilklint** [comment]
I have exactly this issue too, but we do not use Fastlane.
Our "Nightly-builds" sometimes fails because it hasn't finished before our maximum execution time of 30 minutes(typically the builds finish in  < 10 min on GH and < 5 min locally).
After it has failed I can see that the build was stuck on "/usr/bin/codesign"

**Comment by miketimofeev** [comment]
@gustafnilklint feel free to open a new issue but please prepare a repro – it will help us a lot during the investigation.

**Comment by akeblom** [comment]
> https://github.community/t/ios-build-stuck-while-unable-to-check-log/16557

What was the change? It seems like the discussion is no longer available.

**Comment by JacobWrenn** [comment]
> > https://github.community/t/ios-build-stuck-while-unable-to-check-log/16557
> 
> What was the change? It seems like the discussion is no longer available.

From memory, adding the `setup_travis` step to my Fastlane file was sufficient to resolve the issues. It related to the keychain needing to be correctly setup in order for code signing to function properly.
