### ISSUE TITLE
Update Ruby to 2.5.7

### ISSUE THREAD

**Issue by frankieroberto** [actions/virtual-environments#95]
**Tool information**
- Tool name: Ruby
- Add or update? Update
- Desired version: 2.5.7 (currently 2.5.5) this is a security update
- Approximate size: 

This has been requested by several people on the setup-ruby action, see https://github.com/actions/setup-ruby/issues/36

**Virtual environments affected**
- [ ] macOS 10.15
- [x] Ubuntu 16.04 LTS
- [x] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Comment by fbjork** [comment]
+1

**Comment by Bertk** [comment]
Please also consider the ruby 2.6.5 update.
- _this version is by https://github.com/Microsoft/azure-pipelines-image-generation_

**Comment by wagnerpereira** [comment]
+1

**Comment by frankieroberto** [comment]
I think this has now been resolved - ruby 2.5.5 has been removed, and 2.5.7 is now available.

See https://github.com/actions/virtual-environments/issues/281#issuecomment-575520911
