### ISSUE TITLE
Update/Add 4.8 Sdk to Visual Studio

### ISSUE THREAD

**Issue by jesusjimenezmanas** [actions/virtual-environments#953]
**Tool information**
- Tool name: Visual Studio SDK
- Tool license: 
- Add or update? Update
- Desired version: 4.8
- Approximate size: 
- If this is an add request:
  - Brief description of tool: 4.8 Sdk and component targets for Visual Studio
  - URL for tool's homepage: https://dotnet.microsoft.com/download/dotnet-framework/thank-you/net48-developer-pack-offline-installer

**Area for Triage**:
.NET Framework

**Question, Bug, or Feature?**:
Feature

**Virtual environments affected**
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [x] Windows Server 2016 R2
- [x] Windows Server 2019

**Can this tool be installed during the build?**

**Tool installation time in runtime**

**Are you willing to submit a PR?**

At the moment,  4.7.2 Sdk, targets and dev tools are the maximum installed in Visual Studio on Windows environments.
Is it possible to also add 4.8 Sdk, targets and dev tools?
We are targeting out applications to 4.8 and we expect these to be in Visual Studio to avoid problems.

**Comment by Darleev** [comment]
Hello @jesusjimenezmanas,
In order to install required workloads in runtime you can use script below:

```
cd "C:\Program Files (x86)\Microsoft Visual Studio\Installer\"
          $InstallPath = "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise"
          $WorkLoads = '--add Microsoft.Net.Component.4.8.SDK --add Microsoft.Net.Component.4.8.TargetingPack -add Microsoft.Net.ComponentGroup.4.8.DeveloperTools'
          $Arguments = ('/c', "vs_installer.exe", 'modify', '--installPath', "`"$InstallPath`"", $WorkLoads, '--quiet', '--norestart', '--nocache')
          $process = Start-Process -FilePath cmd.exe -ArgumentList $Arguments -Wait -PassThru -WindowStyle Hidden
```
We will keep you informed regarding status of your feature.

**Comment by Darleev** [comment]
@jesusjimenezmanas In addition to my previous reply, It seems we installed NET 4.8 in scope of [script](https://github.com/actions/virtual-environments/blob/master/images/win/scripts/Installers/Install-NET48.ps1). So, NET 4.8 should be available on Windows images. Could you please provide more details about the issue you have faced?

**Comment by jesusjimenezmanas** [comment]
@Darleev Thanks for your prompt response.
It seems it the 4.8SDK is actually there indeed, as we have now built some projects that target 4.8, and they would have failed compilation if the 4.8Sdk was not there.

The confusion came because I was looking at the readmes where you detail the software that is installed, and they seem to be out of date (4.8 Sdk does not appear there):
https://github.com/actions/virtual-environments/blob/master/images/win/Windows2016-Readme.md
https://github.com/actions/virtual-environments/blob/master/images/win/Windows2019-Readme.md

So could these be updated to avoid further confusion from other people?
Thanks

**Comment by Darleev** [comment]
@jesusjimenezmanas I agree with you. This information should be added to the readme files.
I will prepare a fix for the issue.

**Comment by jesusjimenezmanas** [comment]
@Darleev  Thanks, I noticed that maybe you can tidy up the net472 as well.
There is this script:
 https://github.com/actions/virtual-environments/blob/master/images/win/scripts/Installers/Install-NET472.ps1 but 472 is present in the VS install script.

I have also noticed that there are these other scripts:
https://github.com/actions/virtual-environments/blob/master/images/win/scripts/Installers/Validate-NET472.ps1
https://github.com/actions/virtual-environments/blob/master/images/win/scripts/Installers/Validate-NET48.ps1

Not sure if they should be part of the tidy up. 
I hope is ok to install those as part of VS, unless there is something that needs them installed before VS gets installed...

**Comment by Darleev** [comment]
Hello @jesusjimenezmanas,
Install-NET472 is presented in scripts but actually does not included into final build. Currently, installing .NET 4.8 is done using the Install-NET48.ps1 script, and documented in Windows Readme files [here](https://github.com/actions/virtual-environments/blob/master/images/win/Windows2019-Readme.md#net-48). However, as far as I understand you, it is .NET 4.8 Framework without required Developer/Targeting tools, and to reach the goal need to install Developer Tools and Targeting pack for .NET 48 as Visual Studio workload. Am I correct? 
I have already tried to install these tools with Visual Studio but it leads to build failures with other packages(like Wix). It seems, need to investigate it deeper.

**Comment by jesusjimenezmanas** [comment]
Hi @Darleev 
The step in Install-NET48.ps1 installs :
# .NET 4.8 Dev pack
$InstallerName = "ndp48-devpack-enu.exe"

So the dev tools are installed, and visual studio compiles fine things that target 4.8.
but on the readme of the image is not saying the .net4.8 is installing devpack, and in the Visual Studio section it doesn't say 4.8 dev tools are installed, so it looked like they were not installed.

**Comment by Darleev** [comment]
Hello @jesusjimenezmanas,
In scope of [PR #1078](https://github.com/actions/virtual-environments/pull/1078), I have added package type for .NET Framework 4.8 and 4.7.2 .
However, in the current implementation, we cannot add this information into the workload section, since 4.8 Development Tools and Targeting packs are not included in Visual Studio workload's installation procedure. As soon as .NET 4.8 becomes a part of Visual Studio components the information is updated automatically.

**Comment by Darleev** [comment]
@jesusjimenezmanas the mentioned PR has been merged and will be available after next image rollout.

**Comment by Darleev** [comment]
Hello @jesusjimenezmanas,
We have updated readme me and added the required information to the documentation.

Feel free to open a new issue in case of any questions.
