### ISSUE TITLE
Using ClangCl compiler on Windows

### ISSUE THREAD

**Issue by jcarpent** [actions/virtual-environments#960]
**Describe the bug**
I'm trying to use ClangCl on Windows with CMake, but I'm totally failing and it seems that CMake is not able to find the compiler, while everything is working pretty well on my local machine.

**Area for Triage**: 
C/C++

**Question, Bug, or Feature?**: 
Question

**Virtual environments affected**
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [x] Windows Server 2019

**Actual behavior**
A small output of the results is available here:
```
 -- Found PkgConfig: C:/Strawberry/perl/bin/pkg-config (found version "") 
-- Package version (ROS package.xml): 2.4.5
-- The CXX compiler identification is Clang 9.0.0 with MSVC-like command-line
CMake Error at CMakeLists.txt:29 (PROJECT):
  No CMAKE_CXX_COMPILER could be found.
```

and the configuration file is available here: https://github.com/stack-of-tasks/pinocchio/blob/b6fac4bfcb88273fed11ef365699351439a1788f/.github/workflows/windows-conda.yml#L1

**Comment by al-cheb** [comment]
Hello, @jcarpent 
I can't reproduce the issue with missing clang. You provided repo -https://github.com/stack-of-tasks/pinocchio/runs/719648034?check_suite_focus=true

```
-- Found PkgConfig: C:/Strawberry/perl/bin/pkg-config (found version "") 
-- Package version (ROS package.xml): 2.4.5
-- The CXX compiler identification is Clang 9.0.0 with MSVC-like command-line
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/Llvm/bin/clang-cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/Llvm/bin/clang-cl.exe - works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done

```

On local machine I can't reproduce too:
![clan - Copy](https://user-images.githubusercontent.com/47745270/83251230-ff232c80-a1b1-11ea-918b-e6b1479d23b3.JPG)

**Comment by jcarpent** [comment]
I've checked, and the issue was coming from the cmake version provided by conda on the conda-forge channel. It is a bit weird, but now it is going well. Thanks a lot for your strong support.
