### ISSUE TITLE
README.md has broken link 

### ISSUE THREAD

**Issue by asklar** [actions/virtual-environments#962]
**Describe the bug**
The link in the root README that supposedly tells people how to track changes to the images is broken. Goes to [virtual environment project](https://github.com/actions/virtual-environments/projects/1) which is dead.

**Area for Triage**: 
Deployment/Release

**Question, Bug, or Feature?**: 
bug

**Virtual environments affected**

**Expected behavior**

**Actual behavior**

**Comment by maxim-lobanov** [comment]
I have updated link and provide a bit more details in documentation. Thank you for reporting it
