### ISSUE TITLE
How to track changes to windows-2019

### ISSUE THREAD

**Issue by asklar** [actions/virtual-environments#963]
**Describe the bug**
Our team's CI automatically started using VS 16.6. We started to see our code fail to build due to a confirmed regression in the compiler. The readme on the front page says it's still using 16.5.
The "receive updates" links on the readme just mention general github changes (i.e. feature updates), not updates to specific images like windows-2019.

a) how can we know what changes to the windows-2019 image are coming in and when
b) is it possible to set a version of VS so that it doesn't get updated as often? we've been burned by regressions in VS's compiler/linker/packaging pretty much every release.

**Area for Triage**: 
Deployment/Release

**Question, Bug, or Feature?**: 
Question

**Virtual environments affected**
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [X] Windows Server 2019

**Comment by Darleev** [comment]
Hello @asklar,
In order to track status and software installed on upcoming releases, you can table in [the main page](https://github.com/actions/virtual-environments#available-environments) of virtual environment project and click on **"Latest Release & Rollout Progress"** for required release.
If additional information is required, please let us know.

**Comment by asklar** [comment]
Thank you @Darleev - is there a way to stay on a LKG version of an image or VS? Like I mentioned, we've been burned badly with every minor VS release...

**Comment by Darleev** [comment]
@asklar there is no way to preserve Visual Studio version since we always have actual one. As a possible solution, you can consider deploying [self-hosted agents](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/agents?view=azure-devops&tabs=browser) with desired version.

**Comment by RadRussianRus** [comment]
> In order to track status and software installed on upcoming releases, you can table in [the main page](https://github.com/actions/virtual-environments#available-environments) of virtual environment project and click on **"Latest Release & Rollout Progress"** for required release.

I've noticed that there is JSON version of current status: https://actionvirtualenvironmentsstatus.azurewebsites.net/api/status

Am I correctly understood that `sum_count_` is current runner count with specified image? So now `20200531.1` has 201 runners, `20200524.1` has 364 runners and `20200517.1` has 480 runners?

```json
    {
      "DisplayName": "windows-2019",
      "ImageVersion": "20200517.1",
      "readMeUrl": "https://github.com/actions/virtual-environments/blob/releases/win19/20200517/images/win/Windows2019-Readme.md",
      "sum_count_": 480
    },
    {
      "DisplayName": "windows-2019",
      "ImageVersion": "20200524.1",
      "readMeUrl": "https://github.com/actions/virtual-environments/blob/releases/win19/20200524/images/win/Windows2019-Readme.md",
      "sum_count_": 364
    },
    {
      "DisplayName": "windows-2019",
      "ImageVersion": "20200531.1",
      "readMeUrl": "https://github.com/actions/virtual-environments/blob/releases/win19/20200531/images/win/Windows2019-Readme.md",
      "sum_count_": 201
    },
```

**Comment by maxim-lobanov** [comment]
@RadRussianRus , it is pretty unusual situation.
Previous week, we have started deployment of `20200524.1` but didn't deploy this image fully due to bug with new version of Azure CLI #948 so this image is deployed on part of agents.
Currently, we are deploying new image (20200531.1).

Usually, link above shows two images. Current one and upcoming

**Comment by RadRussianRus** [comment]
I actually was interested what `sum_count_` means, but that's interesting too.

My hopes that `20200531.1` will fix infinite building bug ([example](https://github.com/telegramdesktop/tdesktop/runs/730159503)) and builds with Visual Studio 16.6.

**Comment by asklar** [comment]
@RadRussianRus do you have more context on what that infinite building bug is? did you file a VS bug at DeveloperCommunity?

**Comment by RadRussianRus** [comment]
Sadly, no. I only know that it happens only on GitHub Actions `windows-2019` image version `20200524.1`. On desktop it works fine. If it will happen in `20200531.1`, I'll file a proper bug report.

**Comment by Darleev** [comment]
@asklar @RadRussianRus since the initial issue has been resolved, and there are no questions, I'm going to close the issue.
In case of any issues, do not hesitate to contact us.
