### ISSUE TITLE
Damaged`docker-proxy`

### ISSUE THREAD

**Issue by mchades** [actions/virtual-environments#9654]
### Description

docker-proxy is not executable occasional

Here is the normal situation:
<img width="1406" alt="image" src="https://github.com/actions/runner-images/assets/24897598/781abede-319d-40c7-b4b6-4f3231aecc93">

Here is the unnormal situation:
<img width="1511" alt="image" src="https://github.com/actions/runner-images/assets/24897598/3af3a568-3b15-430c-ba84-cb57b2bea0c5">

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

>  Image: ubuntu-22.04
>   Version: 20240403.1.0
>   Included Software: https://github.com/actions/runner-images/blob/ubuntu22/20240403.1/images/ubuntu/Ubuntu2204-Readme.md
>   Image Release: https://github.com/actions/runner-images/releases/tag/ubuntu22%2F20240403.1

### Is it regression?

https://github.com/datastrato/gravitino/actions/runs/8594338393/job/23547247372?pr=2820

### Expected behavior

docker-proxy should be executable

### Actual behavior

docker-proxy is not executable

### Repro steps

rerun the job:
https://github.com/datastrato/gravitino/actions/runs/8599818590/job/23563812247?pr=2841

**Comment by erik-bershel** [comment]
Hey @mchades!
We expecting `20240403.1.0 ` to be broken. New fast-forward image rollout will be started in a minutes.

**Comment by sayhiben** [comment]
> Hey @mchades! We expecting `20240403.1.0 ` to be broken. New fast-forward image rollout will be started in a minutes.

Can you explain further? Why do you expect 0403 to be broken, and what other issues can it cause? We have observed intermittent failures when calling `docker run` that began on April 5th and only seem to occur on the image version you mention

**Comment by Jolg42** [comment]
From my side I see the runner image was bumped in my GitHub Actions from previously 20240403.1.0 to 20240407.1.0 (https://github.com/actions/runner-images/releases/tag/ubuntu20%2F20240407.1) for ubuntu-22.04 and everything is working as expected now.

Thanks a lot for the speedy update 💚 🙌🏼

**Comment by erik-bershel** [comment]
Hey @sayhiben!
I was mainly talking about https://github.com/actions/runner-images/issues/9632. There were a confirmed incident, so I expected related rollout to fix your issue too.

**Comment by erik-bershel** [comment]
Hey @mchades,
May I ask you to check your builds today?
