### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Jamalxx** [actions/virtual-environments#967]
**Describe the bug**
A clear and concise description of what the bug is, and why you consider it to be a bug.

**Area for Triage**: 

**Question, Bug, or Feature?**: 

**Virtual environments affected**
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Expected behavior**
A description of what you expected to happen.

**Actual behavior**
A description with steps to reproduce the issue. If your have a public example or repo to share,
please provide the link.

1. Step 1
2. Step 2

**Comment by miketimofeev** [comment]
@Jamalxx I'm going to close the issue since no details provided. Feel free to open a new one, and please make sure all the necessary fields are filled.
