### ISSUE TITLE
macOS builds now failing for a previously working workflow.

### ISSUE THREAD

**Issue by vaibhavpandeyvpz** [actions/virtual-environments#969]
**Describe the bug**
The macOS builds do not happen anymore.

**Area for Triage**: 
"Apple"

**Question, Bug, or Feature?**: 
"Bug"

**Virtual environments affected**
- [x] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Expected behavior**
The build should go through.

**Actual behavior**
No runner matching the specified labels was found: macos-10.15. Using macos-latest instead of macos-10.15 works though.

**Comment by miketimofeev** [comment]
Hi @vaibhavpandeyvpz! There was an issue with build agents yesterday. Both labels are available now. I'm going to close the issue, but feel free to contact us if you have any concerns.

**Comment by aviflax** [comment]
I just ran into this same problem, just now: https://github.com/FundingCircle/md2c8e/actions/runs/120995639

**Comment by CoolCyberBrain** [comment]
Please reopen this. Still running into this today.

**Comment by rolyp** [comment]
@miketimofeev Just ran into this problem.
![Screenshot 2020-06-01 at 16 27 05](https://user-images.githubusercontent.com/121074/83424793-d0f95300-a424-11ea-8a93-e7709f2339d7.png)

**Comment by maxim-lobanov** [comment]
Hello everyone, we have escalated this issue to proper team for investigation.
We will update the thread as soon as we have results.

**Comment by chkimes** [comment]
We've identified the issue and are rolling out a fix that should be available during daytime PST tomorrow. In the meantime, you may be able to work around this issue by specifying `macos-latest`.

**Comment by congyiwu** [comment]
Actually, we finished rolling out the fix just now.  We also audited the other runs-on labels too for discrepancies and tweaked some internal processes to avoid future discrepancies.

**Comment by miketimofeev** [comment]
@vaibhavpandeyvpz @rolyp @CoolCyberBrain @aviflax could you please check macos-10.15 label now?

**Comment by rolyp** [comment]
> @vaibhavpandeyvpz @rolyp @CoolCyberBrain @aviflax could you please check macos-10.15 label now?

Working for me. Thanks.

**Comment by miketimofeev** [comment]
I'm going to close the issue, but feel free to contact us if the issue still persists.
Thank you all!

**Comment by aviflax** [comment]
Looking good. Thank you!

**Comment by ashishb** [comment]
Getting this now - https://github.com/ashishb/dotfiles/actions/runs/142923317

**Comment by miketimofeev** [comment]
@ashishb specification should be either` macos-latest` or `macos-10.15`, but you have
` runs-on: macos`

**Comment by ashishb** [comment]
Thanks @miketimofeev . This seems like a new change though as 'macos' worked earlier
