### ISSUE TITLE
Add Microsoft EdgeHTML (pre Chromium) Web Driver

### ISSUE THREAD

**Issue by raido** [actions/virtual-environments#97]
**Tool information**
- Tool name: Microsoft Web Driver - https://developer.microsoft.com/en-us/microsoft-edge/tools/webdriver/#downloads
- If this is an add request:
  - Selenium Web Driver for browser testing
  - https://developer.microsoft.com/en-us/microsoft-edge/tools/webdriver/#downloads

**Virtual environments affected**
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [x] Windows Server 2016 R2
- [x] Windows Server 2019

**Can this tool be installed during the build?**
No, because it is complicated or unknown to know which Edge version is installed on the environment.
And for Edge v18 web driver has to be installed by running following command with elevated permissions:
`DISM.exe /Online /Add-Capability /CapabilityName:Microsoft.WebDriver~~~~0.0.1.0`

**Are you willing to submit a PR?**

We need to add command 🔝 over here: https://github.com/actions/virtual-environments/blob/master/images/win/scripts/Installers/Install-SeleniumWebDrivers.ps1

And for Edge <= v17 we can pick driver from: https://developer.microsoft.com/en-us/microsoft-edge/tools/webdriver/#downloads and simply unpack it like rest of the Selenium drivers.

If it is simple as adding Zip extraction or command 🔝 I can possibly give it a try.

**Comment by raido** [comment]
It seems Edge is not even available?

Output of https://github.com/testem/testem : `npx testem launchers`

<img width="264" alt="npx-testem-launchers" src="https://user-images.githubusercontent.com/659945/69011931-a1976300-0978-11ea-8104-bc256082f0bb.png">

**Comment by taymonbeal** [comment]
My understanding is that Edge isn't available on Windows Server, only on Windows 10. There's nothing GitHub can do about this.

**Comment by maxim-lobanov** [comment]
Hello!
In scope of #99, we have added Microsoft Edge (Chromium based) and Microsoft Edge Web Driver to windows images.
Did it resolve your issue or it is still actual?

**Comment by maxim-lobanov** [comment]
I am closing the issue since Microsoft Edge (Chromium based) was added to Windows and macOS images. Feel free to reopen if any.
