### ISSUE TITLE
Add aria2

### ISSUE THREAD

**Issue by imbsky** [actions/virtual-environments#970]
**Tool information**

- Tool name: aria2
- Tool license: https://github.com/aria2/aria2/blob/master/COPYING
- Add or update? Add
- Desired version: latest
- Approximate size: 
- If this is an add request:
  - Brief description of tool: aria2 is a lightweight multi-protocol &
    multi-source, cross platform download utility operated in command-line. It
    supports HTTP/HTTPS, FTP, SFTP, BitTorrent and Metalink.
  - URL for tool's homepage: https://github.com/aria2/aria2

**Area for Triage**:

Packages

**Question, Bug, or Feature?**:

Feature

**Virtual environments affected**

- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Can this tool be installed during the build?**

**Tool installation time in runtime**

**Are you willing to submit a PR?**

Maybe?

**Comment by maxim-lobanov** [comment]
Could you please specify virtual environment where you would like to install this tool?

**Comment by miketimofeev** [comment]
@imbsky @maxim-lobanov aria2 is already available on macOS and Ubuntu(but not described in the readme) and can be invoked by `aria2c`

**Comment by imbsky** [comment]
Oh I didn’t know that. Thanks for the information.

**Comment by AnimMouse** [comment]
Can we add aria2 in the list of included software?

**Comment by catthehacker** [comment]
@AnimMouse 
https://github.com/actions/virtual-environments/pull/3916
