### ISSUE TITLE
Announce/Feedback: .NET Core 2.2 will be deprecated on 19 June for Windows, Ubuntu and macOS images

### ISSUE THREAD

**Issue by maxim-lobanov** [actions/virtual-environments#975]
We are going to deprecate .NET Core 2.2 on 19 June for Windows, Ubuntu and macOS images.
This change is because 2.2 version of .NET Core has been deprecated in January, 2020. As we try only to keep the versions which are not End Of Line (2.1, 3.0 and 3.1).
Please see related pull-request: #535 
```
In .NET Core, its recommended to always build using the latest SDK, 
if however a specific version of the SDK is required,
then use of UseDotNet task is recommended.
```
If you still need to use .NET Core 2.2.x, you will be able to install it in runtime using the following tasks:
- [UseDotNet](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/tool/dotnet-core-tool-installer?view=azure-devops) (Azure DevOps)
- [setup-dotnet](https://github.com/actions/setup-dotnet) (GitHub Actions)

If you have any concerns or questions please let use know through this issue.

Thanks!

**Comment by miketimofeev** [comment]
PRs were merged, .NET 2.2 removed.
