### ISSUE TITLE
m4 gone in ubuntu-18.04 20200531.1

### ISSUE THREAD

**Issue by favonia** [actions/virtual-environments#985]
**Describe the bug**
The `m4` tool was gone in the latest Ubuntu 18.04 update (ubuntu-18.04 20200531.1)

**Area for Triage**: 
Packages

**Question, Bug, or Feature?**: 
Bug

**Virtual environments affected**
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [x] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Expected behavior**
All tools required by the POSIX should be included in the image.

**Actual behavior**
The package `m4` was not installed, as showing in the log https://github.com/RedPRL/cooltt/runs/731061144.

**Comment by miketimofeev** [comment]
Hi @favonia! M4 comes along with PHP installation, which is missed on the latest image. We're working on the fix and already started rollback from 20200531.1
https://github.com/actions/virtual-environments/issues/981

**Comment by favonia** [comment]
@miketimofeev Did you mean there is otherwise no dependency on the m4 package? If so, I urge you to consider adding an explicit dependency on all essential tools such m4 to maintain POSIX-compatibility, independently of the status of the PHP installation.

**Comment by miketimofeev** [comment]
@favonia you're right. Could you please create an issue with a request to add m4 and other tools that you need?
