### ISSUE TITLE
Add explicit dependencies on essential packages

### ISSUE THREAD

**Issue by favonia** [actions/virtual-environments#986]
**Describe the bug**
Essential tools should be explicitly included in Ubuntu images. This is a resubmission of #985.

**Area for Triage**: 
Packages

**Question, Bug, or Feature?**: 
Feature

**Virtual environments affected**
- [ ] macOS 10.15
- [x] Ubuntu 16.04 LTS
- [x] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Expected behavior**
Essential packages should be included regardless of the installation of other packages. For example, issues in PHP installation (#981) should not cause `m4` to dissapear. I was asked to provide a list, and perhaps we could start with the following one. I probably missed many packages because it was made in a hurry, but I hope the idea of explicitly including essential packages is clear. Thank you for your consideration.

- autoconf
- automake
- bash
- binutils
- bison
- bzip2
- coreutils
- fakeroot
- file
- findutils
- flex
- gawk
- gcc
- gettext
- glibc
- grep
- groff
- gzip
- iproute2
- iputils
- libtool
- m4
- make
- patch
- ~pciutils~ (This was removed because this might not be too useful for CI? I don't know.)
- pkgconf
- sed
- shadow
- sudo
- tar
- texinfo
- util-linux
- which
- xz

**Comment by vsafonkin** [comment]
Hi @favonia , thank you for your help! I've checked your list and created PR to add some packages that are absent on the Ubuntu images, thank you!
