### ISSUE TITLE
apt-get update fails in latest ubuntu-18.04 image

### ISSUE THREAD

**Issue by lizan** [actions/virtual-environments#988]
We started to see following message from this afternoon when run `sudo apt-get update`:
```
E: Failed to fetch http://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_18.04/InRelease  403  Forbidden [IP: 195.135.221.134 80]
E: The repository 'http://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_18.04  InRelease' is no longer signed.
```

https://dev.azure.com/cncf/envoy/_build/results?buildId=41024&view=logs&j=8d802004-fbbb-5f17-b73e-f23de0c1dec8&t=deac2980-37cf-5d33-1563-9fd6e32eb17f

This have been failing all of our CI jobs on Microsoft-hosted Azure Pipelines agent.

**Comment by miketimofeev** [comment]
@lizan there is a major outage in opensuse
https://status.opensuse.org/
You can find a workaround in my comment here:
https://github.com/actions/virtual-environments/issues/987#issuecomment-637791840
Close this issue as a duplicate.
