### ISSUE TITLE
GPG for Bazel expired and causing issues when using other tools like Ansible.

### ISSUE THREAD

**Issue by darkwizard242** [actions/virtual-environments#989]
**Describe the bug**
GPG key for Bazel is expired on the Ubuntu 18.04 LTS virtual environment. This causes performing a simple apt_cache update using ansible to fail. You can also identify this by simply running `sudo apt-get update` on the Ubuntu 18.04 LTS virtual enviornment.

**Area for Triage**: 
Servers

**Question, Bug, or Feature?**: 
Bug

**Virtual environments affected**
- [x] Ubuntu 18.04 LTS

**Expected behavior**
Repository cache to be updated.

**Actual behavior**
While running `sudo apt-get update` command by itself does not break the build. Running ansible playbooks that require doing a repo cache update does break the build. Either the apt list file /etc/apt/sources.list.d/bazel.list needs to be removed after the images for these virtual environments are built or to of course, update the expired GPG key.

```shell
Err:4 https://storage.googleapis.com/bazel-apt stable InRelease
  The following signatures were invalid: EXPKEYSIG 3D5919B448457EE0 Bazel Developer (Bazel APT repository key) <bazel-dev@googlegroups.com>
```

**Temporary workaround**
Removing bazel apt list file:
```shell
sudo rm -v /etc/apt/sources.list.d/bazel*
```

**Comment by miketimofeev** [comment]
Hi @darkwizard242! This is a known issue https://github.com/actions/virtual-environments/issues/937
Closing this one as a duplicate.

**Comment by darkwizard242** [comment]
@miketimofeev - oh cool, thanks for notifying about that.
