### ISSUE TITLE
Add Microsoft Edge (chromium) to all platforms

### ISSUE THREAD

**Issue by koddsson** [actions/virtual-environments#99]
**Tool information**
- Tool name: Microsoft Edge
- Add or update? Add
- Desired version: >18
- Approximate size:
- If this is an add request:
  - Brief description of tool: Microsoft Edge (chromium) is Microsofts latest incarnation of the Edge browser. A fork of the popular Chromium open source project.
  - URL for tool's homepage: https://www.microsoftedgeinsider.com/en-gb/download/

**Virtual environments affected**
- [x] macOS 10.15
- [x] Ubuntu 16.04 LTS
- [x] Ubuntu 18.04 LTS
- [x] Windows Server 2016 R2
- [x] Windows Server 2019

**Can this tool be installed during the build?**
Yes but browsers should probably be preloaded on the containers. The virtual environments already include browsers such as Chrome and Firefox installed so there is precedent for this.

**Are you willing to submit a PR?**
Yes! The Linux build is not being produced by Microsoft right not but there are indications that it will be in the future. macOS and Windows versions exist right now. I'd feel comfortable submitting a PR for Linux when available and macOS following this issue but Windows is a bit out of my depths.

**Comment by koddsson** [comment]
Not to be confused with https://github.com/actions/virtual-environments/issues/97 which is asking for Edge =< 18. Edge version 18 and below is called EdgeHTML to differentiate between it and Edge Chromium.

**Comment by bahmutov** [comment]
Microsoft has released Edge for Mac and Windows for general public on Jan 15th 2020 https://blogs.windows.com/windowsexperience/2020/01/15/new-year-new-browser-the-new-microsoft-edge-is-out-of-preview-and-now-available-for-download/ and it would be really nice to add it to the mix of tools. We are adding built-in support for Edge to Cypress.io test runner, but really would like to run a smoke job on GH Actions CI to confirm it is working.

**Comment by dmitry-shibanov** [comment]
Hello, Microsoft Edge and Edge driver were added to Windows and macOS images. Linux is not supported currently.
